### ISSUE TITLE
Setup wizard on first run

### ISSUE THREAD

**Issue by maran** [spesmilo/electrum#1]
As a new user when I boot the application for the first time I want to see a setup wizard.

The wizard screen is divided into two screens. On the left-side will be a information panel describing what we are doing during this step and on the right-side will be room for interacting with the wizard in various ways.

The first dialog is a general introduction to electrum and it's features and an introductory text about bitcoin wallets and what they are used for.

The next dialog would explain why we need to encrypt the generated wallet with the password input on the right side.

The third dialog would display the generated seed and 12 words on the right hand side and on the left hand side could be a little story about what those words represent tying into the previous stories about wallets.

**Comment by Tomiborges** [comment]
Fecha

**Comment by Tomiborges** [comment]
Fecha
