### ISSUE TITLE
Electrum 1.9.8 fails to start once Electrum 2.0 beta is launched.

### ISSUE THREAD

**Issue by DaReaper** [spesmilo/electrum#1001]
I have a copy of Electrum 1.9.8 already installed on my windows system. I downloaded and ran Electrum 2.0 Beta and since then 1.9.8 wont load. I've tried deleting the data under appdata/roaming but it still wont work. Does this require a re-install of 1.9.8?

**Comment by ecdsa** [comment]
version 2.0 will convert your wallet file to a new format, which cannot be read by 1.9.8. anymore.
