### ISSUE TITLE
OSX .dmg - new wallet wizard issues

### ISSUE THREAD

**Issue by usezfsyo** [spesmilo/electrum#1006]
Selecting File > New/Restore displays a window asking for the new wallet name, but then doesn't show the new wallet creation wizard.  Main window loses focus, but no new window pops up.  If I select File > New/Restore a second time, both the new wallet name window and the new wallet creation wizard pop up at the same time.
![screen shot 2015-02-03 at 11 24 20 pm](https://cloud.githubusercontent.com/assets/6395016/6035162/10cc43a6-abfc-11e4-80f5-1cf2faf122a4.png)

**Comment by ecdsa** [comment]
might be related to set_layout in the wizard

**Comment by ecdsa** [comment]
does it occur with an install from source on osx?

**Comment by maran** [comment]
I haven't been able to replicate this on Yosemite 10.10.1 (14B25) neither from the DMG or from source.

Would it possible you give me some more information on your system? The information can be found at "About this Mac"

**Comment by usezfsyo** [comment]
I'm using Yosemite 10.10.2 (14C109). Python 2.7.9.

When I run from source, everything works as expected.  I have to be in the electrum source directory, though.  I have other issues if I try to run electrum from anywhere else.

**Comment by maran** [comment]
I will try to update to 10.10.2 and see if that makes me replicate it.

**Comment by ecdsa** [comment]
any news on this?

**Comment by ot4me** [comment]
my electrum (installed from dmg) "hangs pretty much every time" I use the new wallet wizard. right after it asks for the new name it stops responding. dirty workaround is to kill the app, delete the wallet directory and start over.

**Comment by ecdsa** [comment]
@maran did you update to his version?

**Comment by maran** [comment]
@ecdsa Yes I did, and I'm able to replicate the behaviour now. The first time you bring up the wallet wizard you need to click the Electrum icon in the taskbar in order to show it. Tries after that work fine. I'm not sure how to continue debugging this but I will try.

**Comment by ecdsa** [comment]
ok, maybe we just need to add a show() somewhere

**Comment by ecdsa** [comment]
try last commit: c56fe45ad7b93cdb63b6dbb27f72d97c9e789258

**Comment by maran** [comment]
Still happening, the window is showing, as in it is visible. It just 'spawns' behind the main window and won't come into focus.

**Comment by ecdsa** [comment]
added this: 6ececd500d78375862391115f4ecb69b6a53e688
