### ISSUE TITLE
Build error under OSX : No package named packages

### ISSUE THREAD

**Issue by aussiehash** [spesmilo/electrum#1007]
I can successfully build electrum beta from my pull a week back or so.

Once the first public beta was released I cloned to a new directory, and have just pull updated

    $ git pull
    remote: Counting objects: 86, done.
    remote: Compressing objects: 100% (49/49), done.
    remote: Total 86 (delta 48), reused 58 (delta 37)
    Unpacking objects: 100% (86/86), done.
    From https://www.github.com/spesmilo/electrum
       1905b47..8982a46  master     -> origin/master
     * [new tag]         2.0b2      -> 2.0b2
    Updating 1905b47..8982a46
    Fast-forward
     RELEASE-NOTES                |  5 +++++
     electrum                     |  3 +--
     gui/qt/installwizard.py      |  8 +++-----
     gui/qt/main_window.py        |  2 +-
     gui/qt/seed_dialog.py        | 68 ++++++++++++++++++--------------------------------------------------
     gui/qt/transaction_dialog.py |  2 +-
     gui/qt/version_getter.py     |  7 +++++--
     lib/account.py               |  7 +------
     lib/bitcoin.py               |  2 ++
     lib/qrscanner.py             |  2 +-
     lib/version.py               |  2 +-
     lib/wallet.py                | 27 ++++++++++++++++++---------
     setup.py                     |  2 +-
     13 files changed, 58 insertions(+), 79 deletions(-)

Next 

    $ python setup.py sdist --format=zip,gztar

No apparent errors, then

    $   ARCHFLAGS="-arch i386 -arch x86_64" sudo python setup-release.py py2app --includes sip
    Password:
    warning: no directories found matching 'doc/_static'
    warning: no directories found matching 'doc/_templates'
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.dSYM' found anywhere in distribution
    warning: no previously-included files matching '*.dSYM/*' found anywhere in distribution
    warning: no previously-included files matching '*__pycache__*' found anywhere in distribution
    no previously-included directories found matching 'examples/*/build'
    no previously-included directories found matching 'examples/*/dist'
    no previously-included directories found matching 'examples/*/*/build'
    no previously-included directories found matching 'examples/*/*/dist'
    no previously-included directories found matching 'examples/*/*/*/build'
    no previously-included directories found matching 'examples/*/*/*/dist'
    
    Installed /Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/py2app-0.9-py2.7.egg
    Searching for macholib>=1.5
    Reading https://pypi.python.org/simple/macholib/
    Best match: macholib 1.7
    Downloading https://pypi.python.org/packages/source/m/macholib/macholib-1.7.tar.gz#md5=cf03a55323d5b7ca59be530ba0b01032
    Processing macholib-1.7.tar.gz
    Writing /tmp/easy_install-I9eDml/macholib-1.7/setup.cfg
    Running macholib-1.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-I9eDml/macholib-1.7/egg-dist-tmp-8_rtKK
    warning: no directories found matching 'doc/_static'
    warning: no directories found matching 'doc/_templates'
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    
    Installed /Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/macholib-1.7-py2.7.egg
    Searching for modulegraph>=0.12
    Reading https://pypi.python.org/simple/modulegraph/
    Best match: modulegraph 0.12
    Downloading https://pypi.python.org/packages/source/m/modulegraph/modulegraph-0.12.tar.gz#md5=188bfb66058f7f446f04145d0ac63359
    Processing modulegraph-0.12.tar.gz
    Writing /tmp/easy_install-9J4410/modulegraph-0.12/setup.cfg
    Running modulegraph-0.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9J4410/modulegraph-0.12/egg-dist-tmp-eLxhdt
    warning: no directories found matching 'doc/_static'
    warning: no directories found matching 'doc/_templates'
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    
    Installed /Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/modulegraph-0.12-py2.7.egg
    Searching for altgraph>=0.12
    Reading https://pypi.python.org/simple/altgraph/
    Best match: altgraph 0.12
    Downloading https://pypi.python.org/packages/source/a/altgraph/altgraph-0.12.tar.gz#md5=916dca277fb2b747d5b1ec05b54a0825
    Processing altgraph-0.12.tar.gz
    Writing /tmp/easy_install-_GqPgy/altgraph-0.12/setup.cfg
    Running altgraph-0.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_GqPgy/altgraph-0.12/egg-dist-tmp-ae68mW
    warning: no files found matching 'ReadMe.txt'
    warning: no directories found matching 'doc/_static'
    warning: no directories found matching 'doc/_templates'
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    
    Installed /Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/altgraph-0.12-py2.7.egg
    running py2app
    creating /Users/redacted/Downloads/trezor/electrum4/electrum/build
    creating /Users/redacted/Downloads/trezor/electrum4/electrum/build/bdist.macosx-10.8-x86_64
    creating /Users/redacted/Downloads/trezor/electrum4/electrum/build/bdist.macosx-10.8-x86_64/python2.7-standalone
    creating /Users/redacted/Downloads/trezor/electrum4/electrum/build/bdist.macosx-10.8-x86_64/python2.7-standalone/app
    creating /Users/redacted/Downloads/trezor/electrum4/electrum/build/bdist.macosx-10.8-x86_64/python2.7-standalone/app/collect
    creating /Users/redacted/Downloads/trezor/electrum4/electrum/build/bdist.macosx-10.8-x86_64/python2.7-standalone/app/temp
    creating build/bdist.macosx-10.8-x86_64/python2.7-standalone/app/lib-dynload
    creating build/bdist.macosx-10.8-x86_64/python2.7-standalone/app/Frameworks
    /Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/modulegraph-0.12-py2.7.egg/modulegraph/find_modules.py:273: UserWarning: No package named packages
    *** using recipe: virtualenv ***
    *** using recipe: ftplib ***
    *** using recipe: lxml ***
    *** using recipe: xml ***
    *** using recipe: sip ***
    *** using recipe: pydoc ***
    *** using recipe: ctypes ***
    *** filtering dependencies ***
    1504 total
    39 filtered
    80 orphaned
    1465 remaining
    Traceback (most recent call last):
      File "setup-release.py", line 60, in <module>
        **extra_options
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 659, in run
        self._run()
      File "/Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 865, in _run
        self.run_normal()
      File "/Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 958, in run_normal
        pkgdirs = self.collect_packagedirs()
      File "/Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 935, in collect_packagedirs
        for pkg in self.packages
      File "/Users/redacted/Downloads/trezor/electrum4/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 1593, in get_bootstrap
        bootstrap = imp_find_module(bootstrap)[1]
      File "build/bdist.macosx-10.8-x86_64/egg/modulegraph/util.py", line 34, in imp_find_module
    ImportError: No module named packages

**Comment by aussiehash** [comment]
Editing this line 
https://github.com/spesmilo/electrum/blob/master/setup-release.py#L40

To remove `packages` fixes the problem, I read it somewhere on my github star feed, but couldn't find it in open or closed issues ....

**Comment by usezfsyo** [comment]
Was changed in this commit:
https://github.com/spesmilo/electrum/commit/fd8a931608d3676cf7220dc955b41b7b95dbc14b

I had to do the same thing...

**Comment by aussiehash** [comment]
Thanks. I knew I read the fix somewhere, but couldn't find it.

**Comment by lichtamberg** [comment]
Have the same problem.. But for me this fix doesnt work.. I get another error:

```
opying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/itertools.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/itertools.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/math.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/mmap.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/mmap.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/operator.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/operator.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/parser.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/parser.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/pyexpat.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/pyexpat.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/resource.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/resource.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/select.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/select.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/strop.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/strop.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/termios.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/termios.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/time.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/time.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/unicodedata.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/unicodedata.so
copying file /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/zlib.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/zlib.so
copying file /usr/local/Cellar/sip/4.16.1/lib/python2.7/site-packages/sip.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/sip.so
copying file /usr/local/lib/python2.7/site-packages/hidapi-0.7.99.post5-py2.7-macosx-10.9-x86_64.egg/hid.so -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/lib/python2.7/lib-dynload/hid.so
copying file data -> /Users/myuser/coding/electrum/dist/Electrum.app/Contents/Resources/data
error: [Errno 2] data: 'No such file or directory'
```

**Comment by ecdsa** [comment]
removed in b701ca185cbdadd3d4753535e5460a777366ce01

**Comment by aussiehash** [comment]
Broken again with this commit

https://github.com/spesmilo/electrum/commit/2af670ea2b92e835919b745d94afcb8b4ec32fda

**Comment by Thireus** [comment]
Same here, can we reopen this ticket please?

**Comment by skaht** [comment]
Any suggestions?

For the **master** branch, commit 8598f9ef9c8b012b8bc1aae5ad6a517ab3b44b5b on Yosemite, ran into the same issue above concerning [packages](https://github.com/spesmilo/electrum/blob/master/setup-release.py#L40) in setup-release.py. Deleting ```packages``` or replacing it with ```packaging``` seem to make no difference. Building from ```git checkout origin/osx_build``` 
```
% setenv | grep ARCH
```
```
ARCHFLAGS=-arch i386 -arch x86_64
```
```
% python setup-release.py py2app --includes sip
```
```
running py2app
creating /Users/Scott/Projects/Spesmilo/electrum/build/bdist.macosx-10.10-x86_64/python2.7-standalone/app
creating /Users/Scott/Projects/Spesmilo/electrum/build/bdist.macosx-10.10-x86_64/python2.7-standalone/app/collect
creating /Users/Scott/Projects/Spesmilo/electrum/build/bdist.macosx-10.10-x86_64/python2.7-standalone/app/temp
creating build/bdist.macosx-10.10-x86_64/python2.7-standalone/app/lib-dynload
creating build/bdist.macosx-10.10-x86_64/python2.7-standalone/app/Frameworks
/Users/Scott/Projects/Spesmilo/electrum/.eggs/modulegraph-0.12.1-py2.7.egg/modulegraph/find_modules.py:273: UserWarning: No package named packages
*** using recipe: virtualenv ***
*** using recipe: ftplib ***
*** using recipe: lxml ***
*** using recipe: xml ***
*** using recipe: sip ***
*** using recipe: matplotlib ***
*** using recipe: pydoc ***
*** using recipe: ctypes ***
*** using recipe: numpy ***
*** filtering dependencies ***
2869 total
46 filtered
108 orphaned
2823 remaining
Traceback (most recent call last):
  File "setup-release.py", line 60, in <module>
    **extra_options
  File "/Users/Scott/usr2/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/Scott/usr2/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/Scott/usr2/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/Scott/Projects/Spesmilo/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 659, in run
    self._run()
  File "/Users/Scott/Projects/Spesmilo/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 865, in _run
    self.run_normal()
  File "/Users/Scott/Projects/Spesmilo/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 958, in run_normal
    pkgdirs = self.collect_packagedirs()
  File "/Users/Scott/Projects/Spesmilo/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 935, in collect_packagedirs
    for pkg in self.packages
  File "/Users/Scott/Projects/Spesmilo/electrum/.eggs/py2app-0.9-py2.7.egg/py2app/build_app.py", line 1593, in get_bootstrap
    bootstrap = imp_find_module(bootstrap)[1]
  File "build/bdist.macosx-10.10-x86_64/egg/modulegraph/util.py", line 34, in imp_find_module
ImportError: No module named packages
```


When setup-release.py is edit and ```packages``` is deleted the following results:

```
% python setup-release.py py2app --includes sip
```
```
....
 * urllib.request.getproxies (matplotlib, matplotlib.finance, numpy.lib._datasource, setuptools.compat)
 * urllib.request.parse_http_list (matplotlib, matplotlib.finance, numpy.lib._datasource, setuptools.compat)
 * urllib.request.pathname2url (matplotlib, matplotlib.finance, numpy.lib._datasource, requests.compat)
 * urllib.request.proxy_bypass (matplotlib, matplotlib.finance, numpy.lib._datasource, setuptools.compat)
 * urllib.request.url2pathname (matplotlib, matplotlib.finance, numpy.lib._datasource, requests.compat)
 * urllib.request.urlopen (requests.compat)
 * urllib3 (requests.packages)
 * win32com (setuptools.sandbox)
 * wx (matplotlib.backends.backend_wx, matplotlib.backends.backend_wxagg)

Modules not found (conditional imports):
 * Gtk (matplotlib.backends.backend_gtk3)
 * IronPython (nose.suite)
 * Numeric (numpy.distutils.system_info)
 * PyQt5 (matplotlib.backends.qt_compat, matplotlib.pyplot)
 * PySide (matplotlib.backends.qt_compat)
 * Pyrex (numpy.distutils.command.build_src)
 * Pyrex.Compiler.Main (numpy.distutils.command.build_src)
 * _dummy_thread (cffi.lock)
 * _md5 (hashlib)
 * _sha (hashlib)
 * _sha256 (hashlib)
 * _sha512 (hashlib)
 * _thread (cffi.cparser, cffi.lock)
 * android (gui.kivy.main_window)
 * builtins (ecdsa.six, numpy, numpy.core.numerictypes, numpy.distutils.misc_util, numpy.lib._iotools, requests.packages.urllib3.packages.six, setuptools.compat)
 * cairo (matplotlib.backends.backend_gtkcairo)
 * clr (nose.suite)
 * copyreg (numpy.core)
 * electrum.account (plugins.trustedcoin.qt)
 * electrum.bitcoin (gui.kivy.main_window)
 * electrum.i18n (electrum_gui.qt.paytoedit, gui.qt.paytoedit)
 * electrum_gui.kivy.nfc_scanner (gui.kivy.uix.dialogs.nfc_transaction)
 * electrum_gui.kivy.uix.dialogs.create_restore (gui.kivy.uix.dialogs.installwizard)
 * gobject (matplotlib.pyplot)
 * google.protobuf.internal.cpp (google.protobuf.descriptor, google.protobuf.reflection)
 * gtk.glade (matplotlib.backends.backend_gtk)
 * html.entities (setuptools.compat)
 * http.client (setuptools.compat)
 * http.cookies (requests.compat)
 * http.server (setuptools.compat)
 * importlib.machinery (cffi.verifier, pkg_resources)
 * java (mock, platform)
 * java.lang (platform, xml.sax._exceptions)
 * jnius (gui.kivy.main_window, lib.util)
 * kivy.app (gui.kivy.qr_scanner.scanner_android, gui.kivy.uix.gridview, gui.kivy.uix.qrcodewidget)
 * kivy.core.text (gui.kivy.main_window)
 * kivy.core.window (gui.kivy.qr_scanner.scanner_android)
 * kivy.lang (gui.kivy.qr_scanner.scanner_android)
 * kivy.uix.modalview (gui.kivy.uix.dialogs)
 * mpl_toolkits.natgrid (matplotlib.mlab)
 * netbios (uuid)
 * numarray (numpy.distutils.system_info)
 * numpy_distutils (numpy.f2py.diagnose)
 * numpy_distutils.command.build_flib (numpy.f2py.diagnose)
 * numpy_distutils.command.cpuinfo (numpy.f2py.diagnose)
 * numpy_distutils.cpuinfo (numpy.f2py.diagnose)
 * numpy_distutils.fcompiler (numpy.f2py.diagnose)
 * org.python.core (xml.sax)
 * org.python.modules.posix.PosixModule (setuptools.sandbox)
 * plyer (gui.kivy.main_window)
 * riscospath (os)
 * scipy (numpy.testing.nosetester)
 * testing (cffi.recompiler)
 * tornado.template (matplotlib.backends.backend_webagg)
 * urllib.error (numpy.lib._datasource, setuptools.compat)
 * urllib.parse (matplotlib.textpath, numpy.lib._datasource, pkg_resources, requests.compat, setuptools.compat)
 * urllib.request (matplotlib.finance, numpy.lib._datasource, requests.compat, setuptools.compat)
 * win32pdh (numpy.testing.utils)
 * win32wnet (uuid)
 * wx (matplotlib.pyplot)
 * wxversion (matplotlib.backends.backend_wx)

Modules with syntax errors:
 * PyQt4.uic.port_v3.proxy_base
 * gui.kivy.nfc_scanner.scanner_android

Done!
find: /opt/local: No such file or directory
Sorry couldn't find your qt_menu.nib this probably won't work
Traceback (most recent call last):
  File "setup-release.py", line 88, in <module>
    shutil.copytree(qt_menu_location, resource + "qt_menu.nib")
  File "/Users/Scott/usr2/local/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: ''
```

**Comment by ongmin** [comment]
Sorry to reopen, it's 2017, I fresh installed and still have this error.

```
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/modulegraph/find_modules.py:191: UserWarning: No module named sip
  warn("No module named %s"%(mod,))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/modulegraph/find_modules.py:206: UserWarning: No package named packages
```
