### ISSUE TITLE
Deprecate PBKDF2 and use pycrypto.

### ISSUE THREAD

**Issue by gyger** [spesmilo/electrum#1012]
Hello, as seen on the website of Dwayne Litzenberger, PBKDF2 is unmaintained (https://www.dlitz.net/software/obsolete/) and the Implementation from PyCrypto should be used.

This would also be nice because PBKDF2 is not packaged in fedora, but pycrypto is, as it is maintained software.

**Comment by ecdsa** [comment]
iirc pycrypto is not pure-python, is it?

**Comment by gyger** [comment]
I don't really know if one can only use the python implemented subset, but that's a reason for packaging the other lib.

**Comment by gyger** [comment]
I saw in the PBKDF2 Code that it uses pycrypto if it's available. Electrum could do something similiar. This is more like a feature request. If this is not wanted, feel free to close.

```python
try:
    # Use PyCrypto (if available).
    from Crypto.Hash import HMAC, SHA as SHA1
except ImportError:
    # PyCrypto not available.  Use the Python standard library.
    import hmac as HMAC
```

**Comment by gyger** [comment]
Sorry, here the link to the documentation in pycrypto. It's the same author as the other library, so I guess he is aware of the same security issues.

https://www.dlitz.net/software/pycrypto/api/2.6/Crypto.Protocol.KDF-module.html

**Comment by ecdsa** [comment]
the core of electrum should remain pure python, because it ensure that it is portable.

**Comment by gyger** [comment]
I prepared a small patch, a pull request tomorrow, to show the idea. Still
pure Python.
Am 10.02.2015 17:44 schrieb "ThomasV" <notifications@github.com>:

**Comment by gyger** [comment]
I have a Pull Request here:
https://github.com/spesmilo/electrum/pull/1020
This would show the idea.

**Comment by gyger** [comment]
Then I close this issue.
