### ISSUE TITLE
Import BIP0038 encrypted private keys

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1017]
Would be nice if BIP0038 encrypted paper wallets or BitCard's could be imported or swept directly. 
Zbarcam would also add convenience here.

**Comment by wozz** [comment]
this has been implemented, but not merged to the main branch: see #816 

I believe the biggest issue is that it adds a binary dependency on scrypt

**Comment by ulrichard** [comment]
Oh, great.
Don't know why the search function didn't find that issue.

**Comment by ecdsa** [comment]
@wozz indeed, I do not want to add dependencies in the core of Electrum. But I could add it as a plugin, if you feel like rewriting it as a plugin.
