### ISSUE TITLE
2.0b2 Install doesn't work in this circumstance

### ISSUE THREAD

**Issue by tkhaew** [spesmilo/electrum#1021]
Hello,

Just tried upgrade my 1.98 to 2.0b2 for testing. I see in README there are two suggested methods. The first one using pip did not work correctly for me. After that, trying the second method, which I have used with older versions, did work ok. The install seemed fine but when starting electrum I get this error:
```
	Traceback (most recent call last):
	  File "/usr/local/bin/electrum", line 188, in <module>
	    init_plugins(config)
	  File "/usr/local/lib/python2.7/dist-packages/electrum/plugins.py", line 22, in init_plugins
	    plugin_modules = [ __import__('electrum_plugins.'+name, fromlist=['electrum_plugins']) for name in plugin_names]
	  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/aliases.py", line 20, in <module>
	    from electrum_gui import BasePlugin
	ImportError: cannot import name BasePlugin
```
After repeating with older "sudo python setup.py install" method it worked fine. Well, I seem to get an unrelated message to do with qrscanner - will post issue for that.

**Comment by ecdsa** [comment]
try to find out why you cannot use pip, it will be more helpful

**Comment by ecdsa** [comment]
hmm, looking back at your traceback: remove the file plugins/aliases.py, it seems to cause that issue.
