### ISSUE TITLE
2.0b2 - Error in qrscanner plugin

### ISSUE THREAD

**Issue by tkhaew** [spesmilo/electrum#1022]
I'm getting this error msg when testing with code checked out today:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.0b2-py2.7.egg/electrum/plugins.py", line 54, in run_hook
    r = f(*args)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.0b2-py2.7.egg/electrum_plugins/qrscanner.py", line 48, in load_wallet
    self.send_tab_grid.addWidget(b, 1, 5)
AttributeError: Plugin instance has no attribute 'send_tab_grid'
```
Maybe some recent changes making plugin incompatible?
Note that the QR buttons in interface now have no icon, and do not work. So must be something wrong there but haven't had a chance to go looking into code.

edit: more detail. Send tab has no QR scan button, but the menu item to load trx from QR (Tools, Load trx, from QR) does work and opens the qr scanner window. Likely an issue with adding qr button to send tab. Will look at this now.

**Comment by ecdsa** [comment]
there is no qrscanner plugin anymore; I don't know why you still have it

**Comment by tkhaew** [comment]
A little more exploring and I see that the qrscanner plugin present in 
/usr/local/lib/python2.7/dist-packages/Electrum-2.0b2-py2.7.egg/electrum_plugins/
is not the same as found in electrum/lib source dir.

I don't know what's changed or going on now. I decided to run scripts for rebuilding setup and install materials. It seems that re-running the 

pyrcc4 icons.qrc -o gui/qt/icons_rc.py
python setup.py sdist --format=zip,gztar

instead of steps as suggest in readme now fix problems with icons missing from screen and the qr icon now shows up on send tab, and opens scanner window. So I gather that's an issue related to installing from git pull instead of downloaded tar archive. I still get the same error message at start but seem to have working qr scanning now.

**Comment by tkhaew** [comment]
Oh, just saw you closed this. Ya, not sure why either but it does show up in the electrum 2.0b2 egg even though not found in plugins dir. Weird. Probably somehow connected with just pulling from upstream and checking out 2.0b2 tag. Have no idea. I guess I'll manually delete the 

/usr/local/lib/python2.7/dist-packages/Electrum-2.0b2-py2.7.egg/*

files and try to re-install to see if they go away.

**Comment by tkhaew** [comment]
Hmmm. Just deletedas above and re-installed. Still puts both qrscanner in the electrum dir and electrum_plugins dir.

/usr/local/lib/python2.7/dist-packages/Electrum-2.0b2-py2.7.egg/electrum/qrscanner.py
/usr/local/lib/python2.7/dist-packages/Electrum-2.0b2-py2.7.egg/electrum_plugins/qrscanner.py

Is working but gives error message when started.

**Comment by ecdsa** [comment]
I guess you need to uninstall and reinstall Electrum.
better use pip for that

**Comment by tkhaew** [comment]
I like to have source from git here so I can experiment with ideas etc. I ahven't made any changes since 2.0 so I think I'll just delete the whole dir and re-pull, and try again. When I manually delete the qrscanner.py it behaves correctly. Just wonder how the egg build is finding and including that plugin as it is not in the source plugin dir. 

Well, thanks anyway, and sorry for creating an issue without figuring out the background first.
