### ISSUE TITLE
setup.py ignores --root

### ISSUE THREAD

**Issue by prusnak** [spesmilo/electrum#1035]
Most buildsystems build python packages using the following:
```
python setup.py install --prefix=%{_prefix} --root=%{buildroot}
```

Because electrum does not follow the best practices and uses hardcoded paths this fails with the following:

```
Error: cannot write to /usr/share.
```

Suggestion: Try not to reinvent the wheel and keep setup.py as simple as possible.

**Comment by ecdsa** [comment]
can you suggest an actual solution?

**Comment by ecdsa** [comment]
done in b5ac7f2a7c5b674613e5ee9b6164cece1511db07

**Comment by prusnak** [comment]
Thanks. Much appreciated.
