### ISSUE TITLE
Wallet file is broken/won't start in electrum

### ISSUE THREAD

**Issue by DWDZoNe** [spesmilo/electrum#1039]
Hello,

I have an electrum wallet for some time now and didn't have any issues until now.
I firstly was unable to open electrum executable and after a while I thought to move the wallet to a different computer. It seems that I'm not able to open the wallet file manually and if I try to rename it to "default_wallet" , the electrum exe won't start at all.

I must mention my wallet was not password protected and unfortunately I didn't save the seed. (dumb me).

Is there any way possible to restore my wallet? I don't think I had much in it (<0.5 BTC) but it would be greatly appreciated if I am able to recover it.

p.s: at request, I could send the wallet file directly to any of the devs to take a look at.

Best wishes.

edit:
I have only used Windows 8. Didn't try linux/mac yet as I don't have any devices running them.

**Comment by ecdsa** [comment]
looks like your wallet file might be corrupted.
first make a copy of it.
then open it in a text editor, and try to see if you fan find a field named 'seed'
if you find it, you can restore a new wallet with that seed.

PS: this place is for bug reports
