### ISSUE TITLE
Make it easy to run your private Electrum server

### ISSUE THREAD

**Issue by lvella** [spesmilo/electrum#1043]
Hi, it is known to be possible to run a full Bitcoin node on a Raspberry Pi or other low resources machines, but according to electrum-server HOWTO, it requires too much memory to be run alongside the full node on a Raspberry Pi, it seems mainly because the database must be indexed and be ready to accept connections from any Electrum client.

A private and low resource version of Electrum server is desirable in such cases, so a user and would be able to use its lightweight deterministic wallet shared in multiple devices, like the phone and and the PC, and still be in control of the full node handling its transactions.

In that case, the private server itself could have the wallet's seed, so it only would have to track transactions for that wallet. It would be even better if it could generate the wallet's addresses without being able to spend it, by only having the public part of a master key, to be added to the generated keys.

**Comment by ecdsa** [comment]
out of scope
