### ISSUE TITLE
Exchange rate plugin not working as intended?

### ISSUE THREAD

**Issue by zanglebert** [spesmilo/electrum#1045]
Version 1.9.8, on OS X Yosemite.

Enabling the exchange rate plugin calculates the total value of the wallet in USD, using the selected exchange rate, but nothing else.

In particular, I cannot enter a USD amount in the transaction window to be converted to BTC given the exchange rate - which I thought should be able with the plugin active, no?

Did I forget to enable something? Or is this a bug?

**Comment by ecdsa** [comment]
it works in 2.0
