### ISSUE TITLE
Electrum doesn't add an entry to the Windows "Uninstall or change a program" screen

### ISSUE THREAD

**Issue by Nathan2055** [spesmilo/electrum#1046]
While it does add an option to do so in the Electrum "All Programs" folder, an option to remove Electrum is missing from the "Uninstall or change a program" screen.

**Comment by ecdsa** [comment]
can you tell us which operating system this is for?

**Comment by Nathan2055** [comment]
Electrum 1.9.8 on Windows 7.

On Wed, Feb 25, 2015 at 2:15 AM, ThomasV <notifications@github.com> wrote:

> can you tell us which operating system this is for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spesmilo/electrum/issues/1046#issuecomment-75916100>.
>



-- 
*Nathan Larsen*
spychicken2055@gmail.com
"I have been crucified with Christ; it is no longer I who live, but Christ
(the Messiah) lives in me; and the life I now live in the body I live by
faith in (by adherence to and reliance on and complete trust in) the Son of
God, Who loved me and gave Himself up for me." -Galatians 2:20 AMP

**Comment by bauerj** [comment]
This should work with more recent versions of Electrum.
