### ISSUE TITLE
tx fee should scale with the tx size

### ISSUE THREAD

**Issue by bitcoinfees** [spesmilo/electrum#1047]
From [this reddit thread](http://www.reddit.com/r/Bitcoin/comments/2x3529/bitcoins_sent_failed/) - user specified a fee of 0.0001 BTC, which is more than enough for normal sized transactions.

However his transaction turned out to be 17 kb, bringing the fee rate down to 600 satoshis - below the default minrelaytxfee of 1000, and causing his transaction to get stuck.

To avoid this, the client should do some basic checks on the final fee rate and decline if it is too low.

**Comment by dabura667** [comment]
Fixed in 2.0

That user was using 1.9.8.

Close.
