### ISSUE TITLE
Code reformatting/optimziation

### ISSUE THREAD

**Issue by andscho** [spesmilo/electrum#1048]
In the past few days I spent quite a bit of time going through Electrum's code and noticed semi-often minor non-critical formatting issues.
I know that might seem nit-picky but Python has this nice property that it basically forces everyone to use the same coding style (as defined in numerous PEPs).

E.g. there are many instances of "( something )" instead of "(something)" or too many or too few empty lines.
IMO, this should be fixed before releasing Electrum 2.0 this week because it gives a much better impression to the trained eye of a programmer.

I am using PyCharm to look at the code. It shows you these formatting issues and even offers to reformat everything autmagically (Keyboard shortcut Ctrl-Alt-L).

What do you think?

**Comment by ecdsa** [comment]
ok, but not before 2.0. 
Several people have provided reformatting PRs that ended up breaking things..

**Comment by andscho** [comment]
OK, cool, I understand that code formatting is not an ultra high priority :)

Have you thought about giving Pycharm and its refactoring/reformatting capabilities a try yourself? This way you could see the result immediately and can confirm that no things are broken.

**Comment by andscho** [comment]
Screenshot for electrum2b3

![image](https://cloud.githubusercontent.com/assets/3459903/6423581/955d9bca-bee8-11e4-894f-c30e36de0718.png)

**Comment by Tafelpoot** [comment]
heh.. I'm also in favor of growing towards PEP8... just be careful not to break anything.

**Comment by ecdsa** [comment]
closing, the OP did not follow up
