### ISSUE TITLE
Electrum2 does not perform wallet.synchronize() after importing Electrum1 wallets

### ISSUE THREAD

**Issue by mperklin** [spesmilo/electrum#1049]
When Electrum2 opens an Electrum1 wallet for the first time, it regenerates the addresses internally.

Online machines will see the new addresses as they are able to sync with Electrum servers, however offline machines do not have this advantage.
This results in offline machines having no addresses present in "Receiving" or "Change" trees on the 'Addresses' tab.

This can be fixed manually by using the console to "wallet.synchronize()", followed by restarting Electrum2.

I recommend performing wallet.synchronize() automatically upon completing the upgrade of the wallet file so that these addresses will be available on offline machines the next time Electrum is launched.

**Comment by piscenian** [comment]
Deleteing the blockchain_headers file located in your appdata\roaming\electrum folder solved the Sync issue i was having.
