### ISSUE TITLE
No way to get txid QR code from tx details screen.

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#1050]
Selecting tx details has an info screen with button for QR code but QR code only gives raw trx in binary. It would be very useful to have a button for just getting the txid as QR code. 

My specific use case is to copy txid to mobile phone to send a support message without typing in entire value by hand. I'm sure there are other cases where getting the txid easily when it's not possible to copy/paste easily. Maybe there is another way to do this but I can't see it off hand.

I can code this myself and submit as a pull request but would like to know if it will be accepted before putting time into doing that. I could implement as icon next to txid string, as small QR code next to info there (similar to receive address tab), or as menu item on transaction history list item (next to "details"). 

Hoping for any suggestions or input.
Thx.

**Comment by ecdsa** [comment]
better do it like in the send tab: a child class of QLineEdit, that can be recycled everywhere we need it
