### ISSUE TITLE
Tails 1.3: unsafe connection to port 110

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#1052]
On connecting Electrum 2.0 through Tails 1.3, I get  a popup dialog that includes the text: "...unsafe connection to port 110. ..." (see attached screenshot).

I didn't expect to see this message because I've never seen it with previous versions of Electrum on Tails.

![unsafe](https://cloud.githubusercontent.com/assets/34793/6466411/4438c4cc-c17c-11e4-8cf0-acc4034c50ae.png)

I'm using the "autoconnect" option with TCP/SOCKS5/port 9050.

**Comment by ecdsa** [comment]
some servers use port 110.
use SSL instead of TCP, if you want the connection to be encrypted.
