### ISSUE TITLE
Electrum crashes when network tab is opened

### ISSUE THREAD

**Issue by Villacaleb** [spesmilo/electrum#1053]
Electrum just crashes when I try to open the network tab

Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	electrum.exe
  Application Version:	0.0.0.0
  Application Timestamp:	51220b05
  Hang Signature:	2dc4
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Hang Signature 1:	2dc4c285323ca6a228e4653c8bb9b44a
  Additional Hang Signature 2:	b713
  Additional Hang Signature 3:	b7133412bba0d93c4d45b802a7e7bcc0
  Additional Hang Signature 4:	2dc4
  Additional Hang Signature 5:	2dc4c285323ca6a228e4653c8bb9b44a
  Additional Hang Signature 6:	b713
  Additional Hang Signature 7:	b7133412bba0d93c4d45b802a7e7bcc0

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Image of it crashing http://puu.sh/gkU8R/b5c0ccdd10.jpg

**Comment by SmileyChris** [comment]
I see that you're not synchronized: might be the same issue as #1054

**Comment by ecdsa** [comment]
might as well be the same issue as #1060

**Comment by Villacaleb** [comment]
@ecdsa 
Looks like it is, I upgraded windows so I can't test it anymore.
