### ISSUE TITLE
Unable to export private keys after creating a wallet from a HD private key import (xprv key) 

### ISSUE THREAD

**Issue by pikefloyd** [spesmilo/electrum#1055]
In electrum 2.0, (Windows Installer Binaries on Win7 x64) I created a new wallet from a HD private key import (xprv which had been exported from the Mycelium Android App ). There were no bitcoins in the account.

Electrum imported the key and seemed to be ok, however when I select 'Wallet' 'Private Keys' 'Export' A window pops up with 'Incorrect Password' and I am unable to export the individual private keys for all the public keys.

**Comment by ecdsa** [comment]
you need to export the xprv of a single account, maybe that's not what you did

**Comment by pikefloyd** [comment]
I think it was a single HD account, (i.e. not a single address).

I select 'Restore or import a wallet' with 'Standard wallet'
Paste in the private key;
xprv9zEznfjbcy3MeeVxXSzYoLm1pZRXvARRpE6b1Te3eeQ4kJEg32YrztqFsRdgiKNZ6892YmZEvCL5S9umXwa6GQKVhqP8jSQufmFRcSwkdfQ (no bitcoins!!)
create a new password
Electrum then generates the HD addresses.

When I attempt to export the private keys of the individual addresses a window pops up with 'Incorrect Password'.

Hope this helps, or apologies if I've misunderstood and I can only import non HD (single) private keys into electrum.

Thanks

**Comment by ecdsa** [comment]
Now that you have shown your private key to the world, you should move your bitcoins to another wallet ASAP. 

Yes you can import a HD key in electrum. I do not know why there is no coins in this account; how did you export it in mycelium? are you sure it is the right account?

The 'incorrect password' window in Electrum is a bug, I just fixed it; thanks for that

**Comment by pikefloyd** [comment]
I created the private key using Mycelium running on Androidx86 in a virtual machine just to demonstrate the problem, so there are no bitcoins there to loose.

To export the private key from mycelium I select accounts, then highlight the HD account to export, then select options, then select export, then select show private.

Thanks for all your efforts on Electrum.

**Comment by ecdsa** [comment]
oh I misunderstood.. 
I thought you had coins in the account and were not able to see them in electrum.
so this issue is only about the password bug. 
it is fixed in 490de0d8ceffe7ff0a8d730deaac227b74bb66ac

**Comment by pikefloyd** [comment]
That's correct, sorry for any confusion.

thanks again
