### ISSUE TITLE
Creating a new hardware wallet when a default wallet exists crashes Electrum

### ISSUE THREAD

**Issue by chrisrico** [spesmilo/electrum#1057]
This is in the 2.0 version for Windows. Creating the wallet for my first Trezor worked perfectly. Trying to create the second, Electrum silently exits/crashes after the clicking *Next* on the *Select your hardware wallet* dialog.

I can't find any logs (files or Windows event log), but I will happily post them if you tell me where to look.

**Comment by ecdsa** [comment]
is the default wallet a trezor wallet?

**Comment by chrisrico** [comment]
Yes, that is correct. The one it fails to create is also a Trezor wallet (different Trezor).

**Comment by ecdsa** [comment]
I guess the problem is that it does not close the connection to the first trezor wallet before opening the second one.
here is a workaround: create a standard wallet, open it, and then create your second trezor wallet

**Comment by ot4me** [comment]
happens also in 2.0.2 and on mac os. 
in 2.0 it did not crash but stopped responding and ended up in a kind of limbo. now it crashes. my point is there was some improvement but issue is not resolved.
