### ISSUE TITLE
Electrum seg faults when clicking scan qr code

### ISSUE THREAD

**Issue by TTN-** [spesmilo/electrum#1059]
Hi,

I've just downloaded the electrum client from here: https://download.electrum.org/Electrum-2.0.tar.gz

Going to file -> New/Restore -> restore or import wallet then clicking the scan qr code button gives this message:

ERROR: zbar processor in _zbar_video_open():
    system error: opening video device '/dev/video0': No such file or directory (2)

The second time I click the button it simply crashes.

Here's the terminal output:

user@userspc:~/Electrum-2.0$ python electrum
Segmentation fault

**Comment by ecdsa** [comment]
that commit should fix the segfault.
in your preferences, try to change the video device
