### ISSUE TITLE
Freeze followed by crash when clicking on the red network icon

### ISSUE THREAD

**Issue by goetzc** [spesmilo/electrum#1060]
Since the update to version 2.0, I get the message "Not connected" on the bottom-left corner. When clicking on the red Network icon (or from menu Tools), Electrum main window disappears, but the tray icon stays there, sometimes after a dozen seconds the tray icon disappears, with no more electrum process.

This is in Arch Linux, Python 2.7.9-1, python2-pyqt4 4.11.3-3

```
$ electrum
Connected to daemon on port 8001
libpng warning: iCCP: known incorrect sRGB profile
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python2: xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

[2]-  Terminated              electrum
[3]+  Aborted                 (core dumped) electrum
```
The dumped core could not be saved. This was in dmesg:
```
electrum[20028]: segfault at 4 ip b4f081a4 sp bfc7e58c error 4 in libQtCore.so.4.8.6[b4d74000+2fb000]
```

One other occasion:
```
$ electrum -v
electrum directory /home/test/.electrum
CA bundle: /etc/ssl/certs/ca-certificates.crt found
Audio MODEM is not found.
[OA] Initialiasing OpenAlias plugin, OA_READY is True
Connected to daemon on port 8001
wallet path /home/test/.electrum/wallets/default_wallet
libpng warning: iCCP: known incorrect sRGB profile
(then, when clicking on Network)
NetworkProxy: terminating
```

The crash is reproducible every time, just the output differed, which I don't know why.

**Comment by ecdsa** [comment]
you have the electrum daemon running.
what is the output of "electrum daemon status" ?
does the crash occur too if you are not running a daemon?
(you can stop it with "electrum daemon stop")

**Comment by goetzc** [comment]
If there is no electrum process running:
```$ electrum -v daemon stop
electrum directory /home/test/.electrum
CA bundle: /etc/ssl/certs/ca-certificates.crt found
Connected to daemon on port 8001
Daemon stopped
NetworkProxy: terminating
```

If there is again no electrum process running:
```$ electrum -v daemon status
electrum directory /home/test/.electrum
CA bundle: /etc/ssl/certs/ca-certificates.crt found
Connected to daemon on port 8001
NetworkProxy: terminating
```
Which starts an electrum process, if the same command is invoked again, a new process (with different PID and so) is started. Nothing more is printed on screen.
Then calling "electrum daemon stop" just starts another electrum process, which stops after a couple of seconds. The other processes don't seem to be affected.

**Comment by ecdsa** [comment]
what's in the daemon.log file?
(in  your .electrum directory)

**Comment by ecdsa** [comment]
hmm, I see, you never started the daemon, but it thinks there is an active daemon because some application is using port 8001.
do this: "electrum setconfig daemon_port 8123"  
(assuming that port number 8123 is free, otherwise pick another one yourself)

**Comment by goetzc** [comment]
There is no such file. `find ~/.electrum/ -name daemon.log` gives nothing.

But changing the port fixed everything! :)

**Comment by ecdsa** [comment]
ok I made the daemon use a file socket: 59c76f5e0969433b648d40bbef577165839f0437
this will prevent similar problems
I still do not understand how this could cause a crash. that should be investigated

**Comment by ecdsa** [comment]
I also added a short timeout to get_parameters in 33b1142

**Comment by ecdsa** [comment]
I made a bugfix release, version 2.0.1
I hope we will have binaries soon.

**Comment by goetzc** [comment]
2.0.1 fixes the problem. Thank you!
