### ISSUE TITLE
hardware wallet with passphrase - passphrase encoding different from mytrezor

### ISSUE THREAD

**Issue by ot4me** [spesmilo/electrum#1061]
use trezor hardware wallet
choose a passphrase with special characters
select 'addresses' tab and notice what addresses were derived
close electrum
open mytrezor.com website, enter the same passphrase with special characters from step 2
go to account #1 and notice what address is displayed for receiving bitcoin

**Comment by ecdsa** [comment]
without the trezor device, can you check that you can restore the wallet from its seed?

**Comment by ecdsa** [comment]
hmm, I just checked, the gui does not ask for a passphrase when restoring

**Comment by ot4me** [comment]
when using a passphrase that looks more like only 7bit chars were used, both wallets show same addresses. thus the hint that maybe encoding of diacritic is different.

**Comment by ecdsa** [comment]
we should fix this asap, using NFKD of passphrase. Once it is fixed, the master public key will not match anymore; if that happens, we should try the current derivation, and the pubkey comes from the current derivation we should warn the user.

**Comment by ecdsa** [comment]
hmm I am unable to test; the mytrezo.com website does not work on my browser

**Comment by ecdsa** [comment]
thanks for your mail, I could check my commit

**Comment by ot4me** [comment]
thanks for the fix & glad the data were useful. 
and obligatory: I will retest and confirm if resolved once I get my hands on an executable.

**Comment by ecdsa** [comment]
I made a bugfix release, 2.0.1.
I hope we will have binaries soon.

**Comment by ot4me** [comment]
I've checked the 2.0.2 build and can not reproduce the issue (fixed)
