### ISSUE TITLE
Loading Wallets Placed in Wallet Directory / Wallet Import function

### ISSUE THREAD

**Issue by oddphase** [spesmilo/electrum#1064]
I am very new to this stuff but I have been learning about code and wallets. I am testing out different programs and so far this is what I have found here. (Note this is literally my first time ever using a wallet that uses a seed)

I created my wallet offline and copied my wallet to my online computer via USB to send a little coin to my new wallet. I received the coin shortly and was ready to test the restore function with my seed. I deleted my wallet from my online computer and offline computer (with my seed written down). I then moved to my offline computer to restore my seed. This worked flawlessly. I then I copied the wallet from the offline computer to my USB so I could see it update the transaction log on my online computer once I loaded the wallet to confirm everything was intact. I selected the "Restore or import a wallet" option. When Electrum started I was only able to enter (wallet seed, a master public key, a list of Bitcoin addresses, or a list of private keys) or hit cancel and start all over again. So I thought to myself I will just paste my wallet to the wallet directory and it should load automatically. This did not work either and I was again faced with the installwizard.py page. I then renamed the wallet from test1 to default_wallet. This worked and the wallet loaded automatically.

I am extremely nub as far as experience with coding but it appears to me “import a wallet” was never created. Only the restore part of this radio button was addressed in the code. 

I think the issue is here needs an “else if” for "import a wallet" to be defined. And any other related code would need to be written as well?

<code>
action = 'create' if b1.isChecked() else 'restore'
<code/>

In regards to the program not loading a wallet that has previously not been opened in a specific install of Electrum. I assume this is most likely due to the fact it did not have a “last run” wallet from the wallet directory in the programs history. And the wallet I was running was new to this electrum install. This is because I only changed the name of the wallet after loading it with the online computer and I left the wallet as default_wallet when I generated it offline. I am making the assumption since this code is relatively young this has just not been implemented yet. But separating the two (“Restore” and “Import a wallet”) to make a third radio button for disambiguation would be a decent solution. I plan to take some python lessons on Code Academy and see about helping with this if I can or at the very least so I can learn to read code and understand it in more depth for this type of troubleshooting.
 
Anyway hope this helps, very new at all this, feel free to set me straight on this if I am misunderstanding anything. As well if anyone with more experience has a better solution!

**Comment by ecdsa** [comment]
you had wrong expectation as to what the button is for.
I modified the message.
fixed in 2ea25fbb176ff0a9b0da5eff28db140aa215cbea
