### ISSUE TITLE
Can't sign transaction made in 2.0 on <=1.9.8 clients.

### ISSUE THREAD

**Issue by dabura667** [spesmilo/electrum#1065]
I believe this was brought up before, but because of tails including 1.9.8 and most people downloading 2.0 as their watch-only client, this is a pretty big compatibility problem.

The problem can be fixed by adding the input info that was removed in 2.0 to the unsigned transaction format.

Or at least add a button to allow saving the txn / show the QR in the old format... maybe in a menu somewhere, so that at least users experiencing this problem can have a way out that doesn't involve the command line.

**Comment by ecdsa** [comment]
I will not fix that; the main problem with 1.9.8 in tails is that it does not recognize new seeds and xpub created in electrum 2.0, and there is no way to fix that.
