### ISSUE TITLE
2.0 Wont Sync, Client freezes/crashes when opening Network. - solution included

### ISSUE THREAD

**Issue by piscenian** [spesmilo/electrum#1067]
Upgraded from 1.9.8 to 2.0 and the client wouldnt Sync, clicking the network button froze and crashed the client.

The Solution, navigate to your appdata\Roaming\Electrum folder and delete the "blockchain_headers" file, restart the client. The Client will now Sync and there is no crash when opening the network window.

hope this helps.

Source for solution here https://www.reddit.com/r/Bitcoin/comments/2y5ner/electrum_wallet_issues/

im new to get, didnt see the closes issues tab, but also didnt see a temp solution to this problem.

**Comment by ecdsa** [comment]
fixed in 73d8ba24d94cc1fb36c646635efecb39b89d0c9f
