### ISSUE TITLE
Can't send BTC from 2.0 in OS X 10.10.2

### ISSUE THREAD

**Issue by HarpuaFSB** [spesmilo/electrum#1069]
Downloaded 2.0, did a clean "install" and created a new wallet without a password, didn't get prompted for a seed either.

Can process incoming transactions just fine, can see my balance and open my default wallet without a password without issue.

If I try to send BTC it prompts me for a password which I never set up.  If I leave it blank, nothing happens.  If I enter any number of passwords I've used in the past (even though I know I didn't set up my wallet with one), I get an incorrect password error.

My BTC are trapped right now =(

**Comment by ecdsa** [comment]
is there a seed icon, a password icon? can you post a screenshot of the client?

**Comment by ecdsa** [comment]
probably the same bug as #1006

**Comment by HarpuaFSB** [comment]
Yes, all the icons are there...

![1](https://cloud.githubusercontent.com/assets/11371713/6545880/94110aa0-c572-11e4-9431-d724cabce3f4.jpg)
![2](https://cloud.githubusercontent.com/assets/11371713/6545881/94111a0e-c572-11e4-837d-ef4074530a04.jpg)
![3](https://cloud.githubusercontent.com/assets/11371713/6545882/94137cd6-c572-11e4-8be2-9dd7d9c466ab.jpg)

**Comment by ecdsa** [comment]
are you sure that wallet was not created before the upgrade to 2.0 ?
(note: you can reach me on irc today, it will be more efficient)

**Comment by ecdsa** [comment]
when you started Electrum 2.0 after the install, did you see a screen asking you if you wanted to create a new wallet?

**Comment by HarpuaFSB** [comment]
How can I reach you on IRC?

The wallet *may* have existed before 2.0 but even if it did and it was password protected wouldn't it not open without a password?

**Comment by ecdsa** [comment]
no, the wallet only asks for a password when you want to send bitcoins.
on IRC I am on Freenode, on the electrum channel

**Comment by ecdsa** [comment]
again, did you see a screen asking you if you wanted to create a new wallet, or restore an old one?
it looks like that: https://static.orain.org/electrum.orain.org/images/6/69/Create2fa.png

**Comment by ecdsa** [comment]
edit: the wallet was created before, is seed v4. Not related to #1006.

**Comment by genwhy33** [comment]
Как решился этот вопрос кто нибудь знает??? У меня аналогичная ситуация! Все средства лежат на одном кошельке!
