### ISSUE TITLE
using zbar to read qr code for sending btc address, electrum 2.0.1 fails to release before electrum is closed

### ISSUE THREAD

**Issue by jontis** [spesmilo/electrum#1070]
upon successful reading of QR code, a frozen webcam image is left obscuring the desktop and the webcam is inaccessible until electrum is closed.

Electrum 2.0.1
zbar 0.10
Fedora 21_64

**Comment by ecdsa** [comment]
does this script work for you?
https://github.com/herbyme/zbar/blob/master/python/examples/read_one.py

**Comment by jontis** [comment]
yes, that script worked fine.

**Comment by ecdsa** [comment]
well, I realize that test is not meaningful because the program ends after scanning

**Comment by jontis** [comment]
Not sure if this is related but it could be good for you to knowhttps://bugs.freedesktop.org/show_bug.cgi?id=89035

**Comment by ecdsa** [comment]
clear link: https://bugs.freedesktop.org/show_bug.cgi?id=89035

**Comment by jontis** [comment]
Yes, that is me.
Tip for your options: using zbarcam with option --nodisplay avoids that bug.

**Comment by ecdsa** [comment]
git head does not use the zbar python wrappr anymore; it calls the zbar through ctypes.
could you test and tell me if that solves your issue?

**Comment by ecdsa** [comment]
closing, no answer
