### ISSUE TITLE
I'm not seeing trezor support in the 2.0.2 Windows portable version

### ISSUE THREAD

**Issue by charlierlee** [spesmilo/electrum#1072]
I'm not seeing trezor support in this download:
https://download.electrum.org/electrum-2.0.2-portable.exe

**Comment by chrisrico** [comment]
It's not there in the installable version either.

**Comment by ecdsa** [comment]
maybe it's not supported by your configuration.. 
did you see trezor support in the previous version, on the same computer?

**Comment by maran** [comment]
I can confirm the 2.0.2 binaries don't seem to work with Trezor. Will see what can be done about this.

**Comment by chrisrico** [comment]
I reinstalled 2.0 Windows release and Trezor works again.

**Comment by ecdsa** [comment]
binaries have been updated
