### ISSUE TITLE
Electrum Wallet

### ISSUE THREAD

**Issue by bing0bong0** [spesmilo/electrum#1076]
Hi,

My name is Mike, I have transferred 0.257 BTC into my Electrum Wallet and since yesterday it keeps saying "Synchronizing". 
What i want to know is how i can retrieve my BTC.

Thank you very much.

**Comment by ecdsa** [comment]
the server you are connected to is too slow.
open the network dialog, and pick another server.
actually, the client should have a timeout in auto-connect mode

**Comment by bing0bong0** [comment]
here is where my little problem is, whenever I press the Network button on the left corner of the console, it freezes up... I get the Not Responding (Error Message)... I get the same Error Message when I access the Network button from the Tools menu... 

what else should i try?

**Comment by bing0bong0** [comment]
*The Network Button from the Right Corner, not Left Corner... sorry!

**Comment by ecdsa** [comment]
update to 2.0.2

**Comment by bing0bong0** [comment]
thank you very very much. it worked, wallet open, money in... you have been most kind.

Now let me tell you about my dog: i don't have a dog. So that is the end of that.

Thanks again.
