### ISSUE TITLE
mktx won't output 0 fee transactions

### ISSUE THREAD

**Issue by shanew** [spesmilo/electrum#1077]
Must be a problem with serialize somewhere but I can't find it. Hopefully someone more familiar with the codebase will be able to spot the problem here.
$ electrum -f 0 mktx 18paW9TiBwb3cxfiMwc3AkaR359q7HQijY 1                                                                                
               <electrum.transaction.Transaction instance at 0x7fdb20c21c20>                                                                                          
                
Thanks.

**Comment by dabura667** [comment]
It won't allow fees under 10 bits.

In order to change this you must locate the source folder and change MIN_RELAY_TX_FEE in bitcoin.py to `MIN_RELAY_TX_FEE = 0`
