### ISSUE TITLE
Unable to import keys from old version

### ISSUE THREAD

**Issue by agilob** [spesmilo/electrum#1079]
I had two wallets, one bitcoin-qt and one electrum, I imported private keys from btc-qt to electrum months ago and everything was fine. After update to [2.0.2](https://www.archlinux.org/packages/community/any/electrum/) I am unable to read imported addresses. I think it happened with latest upgrade, 2.0 didn't have this problem (or I didn't notice that).

```
➜  ~  electrum -v    
electrum directory /home/agilob/.electrum
CA bundle: /etc/ssl/certs/ca-certificates.crt found
Audio MODEM is not found.
[OA] Initialiasing OpenAlias plugin, OA_READY is True
blocks: 347292
wallet path /home/agilob/.electrum/wallets/default_wallet
failed to connect us.electrum.be 50002 [Errno 111] Connection refused
connected to electrum.bitfuzz.nl 50002
sending subscriptions to electrum.bitfuzz.nl:50002:s
connected to kirsche.emzy.de 50002
connected to erbium.sytes.net 50002
"sni-qt/4396" WARN  11:51:54.358 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
connected to electrum.dragonzone.net 50002
connected to electrum.thwg.org 50002
connected to electrum0.electricnewyear.net 50002
connected to ecdsa.net 110
connected to ulrichard.ch 50002
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 527, in update_status
    c, u = self.wallet.get_account_balance(self.current_account)
AttributeError: 'ElectrumWindow' object has no attribute 'current_account'
Notifying GUI
height: 347293 electrum.dragonzone.net:50002:s
```

![electrum1](https://cloud.githubusercontent.com/assets/2544251/6617252/cb66c442-c8ae-11e4-85a6-98ad14b39d48.png)
![electrum2](https://cloud.githubusercontent.com/assets/2544251/6617253/cb689876-c8ae-11e4-8116-6f60d2ab4141.png)

**Comment by ecdsa** [comment]
the exception is not displayed..
can you pull the latest version, I added this 475424148532088a13a7042765bdb45acea1e8be

**Comment by agilob** [comment]
LOL my bad. I saved seed as password in keepass and password as username, by coping the password I was sure it's correct ;D
The exception is "invalid password".
