### ISSUE TITLE
Proxy setup is greyed out in 2.02/Mac 10.10.2

### ISSUE THREAD

**Issue by rick-li** [spesmilo/electrum#1080]
I tried to run latest Electrum in my mac, but unable to connect to server, previous version worked fine.

in network panel, there's a proxy setup but greyed out, I already removed all my proxy settings in system.

here's the screenshot
https://www.amazon.com/clouddrive/share/I_ZWR9U9X0AyeL4ldlJ16A7LVXh-_-QqGnByIrpBFTc

**Comment by ecdsa** [comment]
are you using the binary for OSX, or did you install from source?

**Comment by rick-li** [comment]
I'm using the binary.

**Comment by maran** [comment]
Did you install the binary to `/Applications/ ` if not could you give that a go?

**Comment by rick-li** [comment]
I installed that to /Applications/ already but makes no difference.

**Comment by ecdsa** [comment]
it looks like it received the option "-p sn_0_11123355" on its command line.
might be related to d2097c15d9eb5ddb12a02dbe4d837b97f091f808

**Comment by maran** [comment]
Can you open a terminal and paste this in `/Applications/Electrum.app/Contents/MacOS/Electrum -v`

**Comment by rick-li** [comment]
The cmd works for me, 
proxy no long greyed out and I and turned it off. Thanks!

**Comment by maran** [comment]
Does it work normally after subsequent launches now too?

**Comment by rick-li** [comment]
yes, it works normally for subsequent launches.

**Comment by exside** [comment]
Same here, OS X 10.7.5, Electrum 2.0.4, and it was a SOCK5 proxy configured, but the dropdown/selectbox was disabled/grayedout, so I could not change it back to NONE/localhost as before in 2.0.0, the shell command above works though! Thanks for the solution!

```
/Applications/Electrum.app/Contents/MacOS/Electrum -v
```

**Comment by ptrcarta** [comment]
OS X 10.7.5 here, Electrum 2.0.4 installed from the binary package provided on electrum.org . I have the same issue.
It starts normally from the command line, but subsequent launches from the app bundle will still have this problem

**Comment by maran** [comment]
I have no clue where this is coming from, any other developers out there want to help me track this down please feel free.

**Comment by ptrcarta** [comment]
I've started doing some printouts and I'll give it a look. I think the issues is in how py2app generates sys.argv in __boot__.py before running electrum.py

**Comment by ptrcarta** [comment]
ok. found an explanation and wrote a patch
osx by default passes a -psn argument (process serial number) when an app is launched in finder. py2app when used with `emulate_argv=True` strips this from argv.
commit d2097c15d9eb5ddb12a02dbe4d837b97f091f808 disabled `emulate_argv`, thus introducing the -psn argument.
see as reference https://mail.python.org/pipermail/pythonmac-sig/2008-January/019678.html
I'll now submit a pull request, I've tested it by modifying the `electrum.py` file in the app bundle

**Comment by ecdsa** [comment]
that patch does not work

**Comment by ecdsa** [comment]
well, I suspect @maran disabled the patch when he built the 2.1 binaries
<Animazing> also that fix for osx isnt working
<Animazing> it makes the binary crash
<ThomasV> which fix?
<Animazing> that one that skips the proxy thingy
<Animazing> by removing cli arguments

**Comment by ptrcarta** [comment]
I've tried 2.1 on OSX and it crashes at startup, but it doesn't seem to integrate https://github.com/spesmilo/electrum/commit/f9de19bd78ddf29b58cb62eae02dbb22cb8bc0c4

**Comment by ecdsa** [comment]
should be fixed now, version 2.1.1
