### ISSUE TITLE
Long sync time with Electrum 2.0 and Tor/Tails 1.3

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#1081]
Electrum 2.0 takes ~6 minutes to completely sync a watch-only wallet on Tor/Tails 1.3.

I begin by unpacking the .tar.gz file and double clicking on the "electrum" file. I select the option to restore/import a wallet. Next I paste the master public key for a watch-only wallet.

I get the notification that I'm offline, click OK.

At this point, clicking on the red dot in the lower right does nothing (and hasn't since pre-2.0, but that's probably a different issue). So I close Electrum and re-launch. Clicking on the red dot gives the network dialog this time. I keep auto-connect checked, and SSL as the protocol. I change the proxy to SOCKS5, and change the port to 9050.

It appears as if nothing is happening, so I wait. After ~1 minute of inactivity, the red circle changes to a loading symbol and my first set of transactions come in. They're all unverified. The red circle is now green.

After ~5 minutes, the loading symbol comes back, and the rest of the transactions load. Now all transactions are confirmed.

The same watch-only wallet takes less than 15 seconds to sync from scratch without Tor on a different OS and using 1.9.x.

I was expecting sync to take a little longer over Tor, but not this long. What can I do to cut the sync delay when running Tor?

**Comment by ecdsa** [comment]
the first time you open an old wallet, version 2.0 needs to regenerate your keys
this takes time, and has nothing to do with Tor
