### ISSUE TITLE
Ignore some addresses from balance updating to improve privacy

### ISSUE THREAD

**Issue by andscho** [spesmilo/electrum#1086]
When Electrum starts, it sends all addresses (receiving, change, imported) to the server it connects to. The privacy implication can be manifold, even when most Electrum servers do not log ip and btc addresses (which is a trust issue).

Would it be possible to mark certain addresses (or a bulk of addresses) as "ignored" or "not interesting" because you know that they will never receive bitcoins again? 

This could work like the freezing function right now (right click -> freeze). There should also be the possibility to unignore addresse again later on.

Edit: maybe "archive" would be a better word than "ignore".

**Comment by ecdsa** [comment]
this will be acceptable only when the user interface does not show bitcoin addresses to the user anymore, and only bip70 payment requests are used.

**Comment by ecdsa** [comment]
I think we should use the multiple accounts of the bip32 tree in order to do that.
The wallet would create a new account each time 1000 addresses have been used.
By default, it would request balance only for the two most recent accounts.

**Comment by aschoenegger** [comment]
I still think it would already be enough to let the user "deselect" addresses he is not interested in anymore. These addresses are then not sent to the electrum server anymore. 

This could be saved in the wallet file and of course would be lost if restoring a wallet from the seed. Maybe we can use the label sync to sync if the address is active or not...

**Comment by andscho** [comment]
I still think it would already be enough to let the user "deselect" addresses he is not interested in anymore. These addresses are then not sent to the electrum server anymore. 

This could be saved in the wallet file and of course would be lost if restoring a wallet from the seed. Maybe we can use the label sync to sync if the address is active or not...

**Comment by bauerj** [comment]
I don't think it would be a good idea to manually disable history refresh for addresses. As you said, that information would be lost when restoring from seed. It might also confuse users that accidentally use that functionality.

A safer way to do this would be to use an offline wallet and manually importing selected private keys into an online wallet.

I'm closing this issue since that is already possible. Please reopen the issue if you think that's not sufficient.
