### ISSUE TITLE
Label Sync Plugin Does not work

### ISSUE THREAD

**Issue by tvl83** [spesmilo/electrum#1088]
I know that's a terrible title, but that is as simple as I could put it. 

I put in the API key from the site that I have been using for a while now on 1.9.8 and it gives me a message saying they are sync'd but the labels never change. I exited and restarted electrum after the sync and it still doesnt display anything. I disabled the plugin now because I do not want it to send blank labels for everything.

**Comment by maran** [comment]
Have you confirmed on the Labelectrum website that the labels are indeed empty? 

What kind of wallet are you using? Did you give it enough to time perform the sync? If you have a large wallet it might take a while, but since it runs in a separate thread you might not notice it.

**Comment by tvl83** [comment]
no i havent checked the website, i didnt want to risk it. It said it was complete, though and nothing changed after a minute or two of it being (not responding)

**Comment by maran** [comment]
Please check the website, you are not risking anything. We need to know if the problem is with the uploading or downloading of torrents.

**Comment by tvl83** [comment]
The website still has my 250 labels.

**Comment by tvl83** [comment]
I just enabled the plugin again and did a 'force download'. it says it completed but no labels changed.

**Comment by maran** [comment]
What kind of wallet are you using?

**Comment by tvl83** [comment]
I am not sure what you mean. it's not multi-sig or anything like that just a standard wallet.

**Comment by ecdsa** [comment]
maybe he created the labels with the old version (non-deterministic initialization vector) ?

**Comment by tvl83** [comment]
all of the labels are in 1.9.8. i suppose what i could do is just open up 1.9.8, export the labels and import them in 2.0.3.

**Comment by ecdsa** [comment]
yes I think you have to do that, export and import them using a file.
there was a change in the labels encryption, so old labels might not be importable

**Comment by ecdsa** [comment]
so, does that fix it for you?

**Comment by tvl83** [comment]
Yes, opening 1.9.8, exported and then imported to 2.0.3

**Comment by CyberLizard** [comment]
@maran this is what happens when you try to force a label up-/download and manually added labels don't sync to other devices or wallet co-owners either. http://prntscr.com/7v13bp
