### ISSUE TITLE
1 of 3 multisig wallet

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1094]
Doesn't make much sense for software wallets, but in conjunction with https://github.com/spesmilo/electrum/issues/1093 it could be interesting.
That way, my wive and I could have the savings in a 2 of 3 and the spending coins in a 1 of 3 using the same hardware wallets.

**Comment by ecdsa** [comment]
that does not make sense..

**Comment by ecdsa** [comment]
this is in the git repo (v2.4)
