### ISSUE TITLE
OS X retina support: icons are still not high res

### ISSUE THREAD

**Issue by gtklocker** [spesmilo/electrum#1096]
Referencing #178 

Some icons are still not hidpi here on an rMBP running 10.10.2.

![screen shot 2015-03-18 at 12 35 12 copy](https://cloud.githubusercontent.com/assets/732062/6707063/f4f2b3cc-cd6b-11e4-8739-979f888dd2f8.png)

Specifically, the tick icon on the left of each transaction, as well as the icons on the bottom right row are evidently not hidpi.

Thanks for making Electrum! :smile:

**Comment by ecdsa** [comment]
would it be fixed with those icons?
https://github.com/blackspikeltd/BS-Electrum-Icons

**Comment by gtklocker** [comment]
Seems so.

**Comment by ansonphong** [comment]
+1 Yes this is a very noticeable issue with the GUI, the icons look very low resolution on OSX on a retina display, or any display which has pixel density over 1:1. If you could use any help with sourcing higher resolution icons let me know and I can work on a PR.

**Comment by ecdsa** [comment]
fixed in #4394
