### ISSUE TITLE
Electrum Master Key does not work for Bitcoin Payments for WooCommerce Plugin

### ISSUE THREAD

**Issue by ohouse** [spesmilo/electrum#1098]
I have done everything to the tee according to the directions but when I try to save the settings i get an error message of:

Bitcoin payment gateway is not operational: Electrum Master Public Key is invalid. Must be 128 characters long, consisting of digits and letters: 'a b c d e f'

This is a new install of WP, woocommerce and Electrum. I have made sure there is no hidden spaces either before or after the key.

The issue is that the Master Public key that Electrum is producing is only 111 characters long. According to the error message it is suppose to be 128.

**Comment by ecdsa** [comment]
please report this to the authors of the plugin, not here
