### ISSUE TITLE
History of Most of my addresses are gone.

### ISSUE THREAD

**Issue by tvl83** [spesmilo/electrum#1099]
and large portion address are highlighted red in my history. There is not a 'used' drop down either.

![image](https://cloud.githubusercontent.com/assets/141966/6761159/5f63a444-cf0d-11e4-9ef0-0e5c6165258a.png)

**Comment by ecdsa** [comment]
the server you are using has a problem.. which server is it?

**Comment by tvl83** [comment]
I didn't pay attention to which one :( I chose a new one and it sync'd up.
