### ISSUE TITLE
Display details about: error: {u'message': u'64: dust', u'code': -26}

### ISSUE THREAD

**Issue by tuxayo** [spesmilo/electrum#1101]
I'm tried to send
0.00000042 BTC
with à 0.00001BTC fee
with version 2.0.2
And I got this error and I can't find any details about that.

Client side problem? Server side problem? Invalid amount?

**Comment by Tafelpoot** [comment]
The error indicates that this is a dust transaction, so small that the electrum servers refuse to relay it.
This requires a better error message in the UI...

**Comment by Tafelpoot** [comment]
If the servers would accept dust transactions like this one, it could lock up (part of) your wallet for days, as (some of) your coins are locked in this tx. It is a double-spend countermeasure.

**Comment by tuxayo** [comment]
Is there a way to know what is the limit that defines a dust transaction?

**Comment by Tafelpoot** [comment]
Common sense and google.
http://bitcoin.stackexchange.com/questions/10986/what-is-meant-by-bitcoin-dust

**Comment by tuxayo** [comment]
Sorry, I thought it was an Electrum choice to avoid spaming the servers.

**Comment by ecdsa** [comment]
I think it's better to leave the error message as it is;
there is a number of error messages possibly returned by bitcoind

**Comment by tuxayo** [comment]
I triggered the error by manually setting the MIN_RELAY_TX_FEE constant so yeah that error should not occur in normal operation.

**Comment by mcandre** [comment]
In my case, the "dust" transaction is an attempt to use Child Pays For Parent in order to speed up a transaction that I accidentally configured with a low fee.

Sux that Electrum won't let the CPFP be broadcast :/
