### ISSUE TITLE
Wallet with two-factor authentication setup: Terms of Service is blank on OSX

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#1105]
Using 2.0.3, attempted to start a new 2FA wallet. Terms of Service screen (the one asking for my email address) is blank.

**Comment by maran** [comment]
I uploaded a new 2.0.3 binary on the 20th of March with md5 `1f883c90d88da6d71173d5da932ac8a7`, can you check if you have this version? It should have fixed this issue.

**Comment by ecdsa** [comment]
@rapodaca can you confirm that it works, so we can close this issue?

**Comment by rapodaca** [comment]
No, the "Terms of Service" section is still blank and asks for an email.

**Comment by maran** [comment]
Ugh really annoying, still working fine here. Can you try booting it from the .app using ` /Applications/Electrum.app/Contents/MacOS/Electrum -v` and give me the output?

![screenshot 2015-03-25 16 02 36](https://cloud.githubusercontent.com/assets/20855/6827566/7211c202-d308-11e4-8df8-274430d87c38.png)

**Comment by rapodaca** [comment]
The problem is that I was running Electrum from the Desktop, not the Applications directory. Moving Electrum 2.0.3 to the Applications directory solved the problem. Terms of Service shows up as expected.

**Comment by ecdsa** [comment]
I guess it should be possible to run electrum from anywhere, so we still need to find how to fix that

**Comment by maran** [comment]
@rapodaca Could you do us a favour and run that command I gave you from a location on the Desktop? Just change the path to reflect where you put it. I can't replicate it locally.

**Comment by ecdsa** [comment]
it should be fixed in 2.0.4
