### ISSUE TITLE
signing raw multisig transactions in 2.0

### ISSUE THREAD

**Issue by EvanSpiegel** [spesmilo/electrum#1107]
1.7 added signrawtransaction(), which allowed signing of raw multisig transactions.

This command appears to have been removed since, replaced with signwithwallet() and signwithkey() — however, none of these appear to support multisig raw transactions.

Am I missing something, or is it no longer possible to sign raw multisig transactions in electrum?

**Comment by ecdsa** [comment]
both commands should work with multisig. 
what makes you think they don't?

**Comment by ecdsa** [comment]
I just checked, it works.
```'./electrum -w <cosigner_wallet> signtxwithwallet <raw_tw>```
