### ISSUE TITLE
French wordlist (minor issue)

### ISSUE THREAD

**Issue by gurnec** [spesmilo/electrum#1109]
This is a **very** minor issue, but the French wordlist isn't part of the repo, even though it's included in the downloads at https://electrum.org/#download

**Comment by ecdsa** [comment]
oh that's because the french wordlist is unfinished

**Comment by gurnec** [comment]
Didn't realize that, sorry for the noise.

**Comment by ecdsa** [comment]
if you want to submit one, you are welcome
