### ISSUE TITLE
Electrum 2.0.3 executable false positives at virustotal.com

### ISSUE THREAD

**Issue by sysfu** [spesmilo/electrum#1110]
Just upgraded to Electrum 2.0.3 and noticed that process explorer is showing [3 hits at VirusTotal] (https://www.virustotal.com/en/file/58466f196778323b54e247186622252fb9804d3cf8099e466db509360e990b0e/analysis/)

Antivirus	| Result	| Update
--------- | -------------- | --------------
Avast |	Win32:GenMalicious-BQF [Trj] |	20150321
Qihoo-360 |	Win32/Trojan.335 |	20150321
TrendMicro-HouseCall |	Suspicious_GEN.F47V0320 |	20150321

The installer file integrity was verified via the GPG signing key before installation.
The sha256 hash of the executable is 58466f196778323b54e247186622252fb9804d3cf8099e466db509360e990b0e

**Comment by maran** [comment]
Are you saying these don't show up in 2.0.2 or earlier?

**Comment by ecdsa** [comment]
this is not the place to report that..

**Comment by sysfu** [comment]
I don't know if VirusTotal is flagging earlier versions. I just wanted to make the devs aware of the issue in case action on their part is needed to resolve the false positive reports.

I'll take it up with Virustotal in the mean time.
