### ISSUE TITLE
Hardcoded icon path in launcher for GNU/Linux systems

### ISSUE THREAD

**Issue by palob** [spesmilo/electrum#1111]
Hi,

currently the icon path specified in the created *.desktop* launcher file is set to: 
*Icon=/usr/share/app-install/icons/electrum.png* 

(see https://github.com/spesmilo/electrum/blob/bc3013caf0d3d6a35290e9cc9e51125b7d03d14c/electrum.desktop)

This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the freedesktop.org standards.

Please find more info here:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How

---------------------------------
According to the above resources standard icon locations are:

*/usr/share/icons/hicolor/[size]/apps/[icon name]*
*~/.local/share/icons/hicolor/[size]/apps/[icon name]*
*/usr/share/pixmaps/[icon name]*

The standard icon line in the .desktop launcher is:
*Icon=[icon name]*      (without full path, without file extension)

for instance
**Icon=electrum**  
(for an icon *electrum.svg* or *electrum.png* stored in standard location)

Could you please move the icon to one of those locations and adjust the icon path in the .desktop file accordingly?

**Comment by ecdsa** [comment]
sure, can you write a pull request?

**Comment by palob** [comment]
Alright, will do it tomorrow.

**Comment by ecdsa** [comment]
@palob I sent you a mail, did you receive it?
