### ISSUE TITLE
display suggestions when typing / submitting a recovery seed

### ISSUE THREAD

**Issue by I3ck** [spesmilo/electrum#1116]
A friend of mine wrote down his seed by hand and tried to recover his wallet.  
He couldn't hit next when doing so.  
After some research I found the word list used when creating the seeds and sent it to him.  
He then was able to figure out his typo and recover the wallet.  
# suggestions

(it may not make sense to implement all of them at once, but a combination)
- add a proper warning that the seed may be incorrect instead of just disabling the next button  
- auto-suggest the valid words when entering the seed
- don't disable the next button and then prompt the user with a corrected suggestion for the seed

**Comment by SomberNight** [comment]
Let me detail one of the suggestions you mention, for people who might implement it:

In the QT GUI, when restoring a wallet from seed words, display word suggestions. That is, given the current partial word, offer suggestions of possible words to the user.

The suggestions MUST be optional, i.e. the user must have the option to ignore them completely; as seeds can contain any string (e.g. `9dk` is a valid segwit-type Electrum seed). (but the seeds the current version of the software generates only contain words from the BIP39 English word list)

Note that the kivy GUI (that is used in the Android app) has this feature, so one might want to have a look at the implementation there.

I would suggest sticking to the English dictionaries, probably the union of the BIP39 English word list and the old Electrum mnemonic word list.

Example from the kivy GUI:
![seed_word_suggestions](https://user-images.githubusercontent.com/29142493/36751022-43cc7f7a-1bff-11e8-814c-e38aba4c9ba6.PNG)

Note that the current partial word is `bloo`, and the suggestions are `bloody`, `bloom`, `blood`.

**Comment by SomberNight** [comment]
This was done in https://github.com/spesmilo/electrum/pull/4033
