### ISSUE TITLE
Incomplete installation instructions for development version on https://electrum.org/#download

### ISSUE THREAD

**Issue by Minthos** [spesmilo/electrum#1119]
When trying to install the dev version following the instructions on https://electrum.org/#download on ubuntu 14.04 lts server, I ran into several missing dependencies.

The solution was to install the following packages:
sudo apt-get install protobuf-compiler libcurl4-openssl-dev gettext
sudo pip install pycurl

**Comment by ecdsa** [comment]
I guess pycurl is only needed for make_locale
why is libcurl4-openssl-dev needed?

**Comment by ecdsa** [comment]
I updated the page. I did not include libcurl4-openssl-dev, though.
let me know if it's really needed

**Comment by Minthos** [comment]
libcurl4-openssl-dev was needed since I used pip to install pycurl. So no, it's not really needed. I don't know why I didn't install pycurl with apt.
