### ISSUE TITLE
merchant.py: invalid xpub string causes overflow in bitcoin.py

### ISSUE THREAD

**Issue by Minthos** [spesmilo/electrum#1124]
Here is the xpub string in my wallet: "xpub": "'xpub661MyMwAqRbcEkfGf8GHzgwDxUmWG27oXing4qgfZWYa9mFf5QQbuvCC2y1XiPTg6gmbLKYKczYdsiEdikZUMcny52RdBopYvBn67oDRPvJ'"

The overflow happens on line 294 of lib/bitcoin.py with long_value: -11961106439074774312227205846945005870730494589706240778074240175112584187459756460893541411313590498161871320680571833575030130060295027600478021780496380653070795739823454886113484963643322536387

The reason is that chars.find(c) on line 288 returns -1 and the value is used without being checked to see if it's valid.

**Comment by ecdsa** [comment]
you have to write it without quotes in the config file
