### ISSUE TITLE
Load Transaction from Qr Code do not work on Mac Osx (iMac 27 2011)

### ISSUE THREAD

**Issue by prebuffo** [spesmilo/electrum#1126]
Load Transaction from Qr Code do not work on Mac Osx (iMac 27 2011).
It give this error:
ERROR: zbar processor in _zbar_video_open():
    unsupported request: not compiled with video input support

![schermata 2015-04-02 alle 15 03 20](https://cloud.githubusercontent.com/assets/11771449/6964395/106d83fa-d949-11e4-9c3c-b6b3ae10928f.jpg)

**Comment by ecdsa** [comment]
it is already mentioned on https://electrum.org/#download
