### ISSUE TITLE
Password confusion

### ISSUE THREAD

**Issue by muff1nman** [spesmilo/electrum#1129]
I know I entered a password when importing an xPriv key (2-3 multisig), but the gui says "Your wallet keys are not encrypted".  Even stranger is when I go to send a transaction: a popup appears telling me "Incorrect password" even though I was never prompted for a password.

**Comment by ecdsa** [comment]
what version of electrum are you using?

**Comment by ecdsa** [comment]
it looks like a bug introduced in #1097

**Comment by muff1nman** [comment]
2.0.4.

**Comment by muff1nman** [comment]
Just updated. Still having an issue.

**Comment by ecdsa** [comment]
yes, you will need to create a new wallet
