### ISSUE TITLE
crash after click on "Read QR code" in send tab

### ISSUE THREAD

**Issue by davidak** [spesmilo/electrum#1133]
zbar is not installed, no video device is selected in settings.

if that is needed, that option should not be showed.

OS X crash trace report: https://gist.github.com/davidak/e869f26fe79b92f88626

**Comment by ecdsa** [comment]
are you sure that zbar is not installed? 
I believe you are having that issue:
https://stackoverflow.com/questions/21612908/zbar-python-crashes-on-import-osx-10-9-1

**Comment by davidak** [comment]
i haven't installed it.

```
$ ./test
Traceback (most recent call last):
  File "./test", line 3, in <module>
    import zbar
ImportError: No module named zbar
```

**Comment by ecdsa** [comment]
are you running electrum from source or from a binary?

**Comment by davidak** [comment]
i downloaded the newest binary from the website.

**Comment by ecdsa** [comment]
oh I see..

**Comment by maran** [comment]
What kind of Mac are you using?

**Comment by davidak** [comment]
iMac 11,3 with i7 and 16 GB of RAM.

you can see that in crash reports: https://gist.github.com/davidak/e869f26fe79b92f88626#file-gistfile1-txt-L887

**Comment by Thireus** [comment]
This issue is still open, with zbar installed it keeps crashing whenever the functionality to scan QR-Codes is prompted.

**Comment by ecdsa** [comment]
@Thireus please do not add comments if they do not add any more information.

**Comment by Thireus** [comment]
@ecdsa, @davidak said it does not work without zbar installed. I have installed zbar and confirmed this feature does not work even with zbar installed. However, with zbar installed QR codes are now generated corrected (they can now be displayed) which is not the case in the latest Electrum 2.3.2 build.

Sorry for my annoying comments.

**Comment by ecdsa** [comment]
do you still have that issue with the recent binaries?

**Comment by Thireus** [comment]
No, because your compiled binaries do not provide zbar. So it prevents the action to occur and crash Electrum. I've compiled my version with zbar, and it crashed just like before. We should remove that icon on OS X.
