### ISSUE TITLE
CA not found for coinbase; request still displayed in green

### ISSUE THREAD

**Issue by ChristophHaag** [spesmilo/electrum#1137]
So I wanted to pay a humble bundle with bitcoin. You can click on the payment thingy there and it'll open a bitcoin URI with a payment request from coinbase.

So the stripped down case is this:

    ./electrum 'bitcoin:1448PbGuf75o7U2oLq2AfH2HHkCnBUEL5X?r=https://www.coinbase.com/r/5526f12c884a5a6d340000f1'

In the "pay to" field it fills in "www.coinbase.com"

So while looking for it in the code I found this unrelated curiosity where the url is parsed once and then parsed again in a try block:

https://github.com/spesmilo/electrum/blob/c381fc21946f4a29fc3fdcc3da0b0dfbe30ca1ef/gui/qt/main_window.py#L1136-L1138

But it looks like this is where instead of `pr.domain` the address should be filled in...

https://github.com/spesmilo/electrum/blob/c381fc21946f4a29fc3fdcc3da0b0dfbe30ca1ef/gui/qt/main_window.py#L1122

Not familiar with the electrum code, so I don't know how it is *supposed* to work, but maybe searching for ("address": <address>) in the tuples of `pr.outputs` ?

Another possibility is that it is working as intended, but an error message is missing, because pr.status is `'Supplied CA Not Found in Trusted CA Store.'`

And another curiosity: When you don't pay attention that it fills in "www.coinbase.com" and just try to send the money, you get this excellent error message:

![electrum2](https://cloud.githubusercontent.com/assets/781076/7078326/6a0bb9b6-df18-11e4-81f0-6eaa1f17304a.png)

**Comment by ecdsa** [comment]
When processing  a payment request, the client displays the domain in the payto field; that is expected behaviour.

I removed the duplicate line in pay_to_URI: 6f5241302c0278cee1eda873c975594254eaae67

The bug you get at the end is unrelated; it was fixed in e3e5d9579476c30da01b79b2e0dc28d2a24727c0

**Comment by ChristophHaag** [comment]
Ah, I only tried to pay with the release version, not with latest from git. Thanks for the explanation.

It's not really obvious in the UI that it's in "payment request mode" where it holds the address in an object in the background. Maybe it could display the address in parentheses behind coinbase.com. Or maybe not, it's not so important anyway.
