### ISSUE TITLE
Not compatible with Trezord (Trezor Bridge)

### ISSUE THREAD

**Issue by cryptosig** [spesmilo/electrum#1139]
If trezord is running then Electrum cannot make a connection to the Trezor device. Force quitting trezord allows Electrum to work again. 

If Electrum ran a check to see if trezord is available and if Electrum could send messages to the trezord engine, I would imagine that the two could work together.

Otherwise if the work is too much, it might be possible to add a simple check to look to see if the trezord engine is running and either shut it down or prompt the user that it needs to be shut down.

**Comment by slush0** [comment]
There's BridgeTransport in python-trezor (library used for communicating with TREZOR). Feature checking for running bridge and using BridgeTransport instead of HidTransport (which is default) should be quite straightforward.

**Comment by slush0** [comment]
Implemented in 18b7337.
