### ISSUE TITLE
Changing RECOMMENDED_FEE to floating Tx fee 

### ISSUE THREAD

**Issue by kaykurokawa** [spesmilo/electrum#1143]
The RECOMMENDED_FEE , which is the default fee per kilobyte, is currently hard coded to 50000 satoshis. As you all may know, Bitcoin core introduced floating Tx fee in 0.10 and Electrum should also move to take advantage of this feature (probably best way would be utilizing RPC call estimatefee). 

Before this change is implemented, there should be at least some clarifications/guidelines on what the hardcoded RECOMMENDED_FEE should be on each release to make sure we don't set it too high or low (Currently my Bitcoin Core node is showing tx fee of 44000 satoshis using command estimatefee 1) .

**Comment by ecdsa** [comment]
this would make the client vulnerable to the server sending a very high value

**Comment by ecdsa** [comment]
closing this, because it is a duplicate of #208
