### ISSUE TITLE
V2.1 can't create new Trezor wallets

### ISSUE THREAD

**Issue by ELM4Ever** [spesmilo/electrum#1146]
Just cloned Electrum repo today. Creating a new Trezor wallet does not work in 2.1 anymore.  It worked well in 2.0.2 and 2.0.3 (didn't try it with 2.0.4).  I kept a copy of each version on my desktop.  I tried switching to my old 2.0.3 directory and it worked fine. 

OS: Linux 
Source: git clone this repo
Setup: 
python setup.py build
sudo python setup.py install
./electrum

Error displayed:

trezor.py L221, in get client
   self.client.twd = self.twd
AttributeError : 'TrezorWallet" object has not attribute 'twd'

Could it be linked to 21ccb1e ?

**Comment by ecdsa** [comment]
yes it is linked to that commit.
