### ISSUE TITLE
Single instance instead of new windows?

### ISSUE THREAD

**Issue by HerHde** [spesmilo/electrum#1147]
Ahoj,
is it possible to set the client to a "single instance only"-mode? Always when I click on a `bitcoin:`address, it opens up a new window, so I get some trouble when I've added new contacts etc and close another window without this contact later.

I run v 2.0.4 on Linux (Mint Cinnamon, so the GUI GTK I guess)

**Comment by ecdsa** [comment]
this is a duplicate of #971
please check existing issues before submiting yours
