### ISSUE TITLE
ubuntu touch

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1148]
A build of electrum for ubuntu touch would be cool. 
Since the ubuntu touch interfaces are also built on Qt, it might be relatively easy to port.

**Comment by ecdsa** [comment]
out os scope

**Comment by jangorecki** [comment]
Any reason why this is out of scope? there is version for android available already. Ubuntu smartphones and tablets are being shipped for a while, I got mine more than a year ago. Currently there is no wallet app for Ubuntu phones.

**Comment by ecdsa** [comment]
can it be built with the kivy GUI?

**Comment by ecdsa** [comment]
at this point, there seems to be no support for ubuntu touch in Kivy: 
https://github.com/kivy/kivy/issues/1312
thus, I am closing this; it cannot be done for the moment.
