### ISSUE TITLE
Empty error message, when trying to create a transaction with CSV text with insuficient fund

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#1154]
I had to use 1.9.8 to understand what was wrong with my transaction.

**Comment by ecdsa** [comment]
I guess you used the "load csv text" window reached from the menu.
this window is kind of deprecated, you can type the csv directly in the send tab
see https://electrum.orain.org/wiki/Frequently_Asked_Questions#Can_I_do_bulk_payments_with_Electrum.3F

I will remove the menu

**Comment by ecdsa** [comment]
fixed in f02b95c
