### ISSUE TITLE
trezor: strange behaviour with 2.1.1: cannot sign, send transactions, getting "watch only mode" albeit pin and passphrase are asked

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1156]
Using trezor firmware 1.3.3
Not sure which python-trezor version I'm using. setup.py contains string "version='0.6.3'"

Here's what I do and what happens:

  * replug trezor
  * start electrum
  * getting PIN entry dialog, entering correct pin
  * immediately getting popups 1.) trezor device not detected, continuing in watch-only mode and 2.) please enter your trezor passphrase
  * entering correct trezor passphrase
  * closing popup "trezor device not detected" by clicking "ok"

now trying to sign (this problem occurs with 2.0.4, also, but it works in 2.0b3)

  * tools -> sign/verify -> enter address and message, click "sign"
  * getting popup "Got &lt;class 'trezorlib.messages_pb2.PublicKey'&gt;, expected (&lt;class 'trezorlib.messages_pb2.Success'&gt;,)

trying "send"
  * "send" tab: entering "pay to", description, amount, click "send"
  * confirm fee
  * getting "transaction popup" (have "show transaction before broadcast" enabled) without a "broadcast button". only option is to "close" or "save" transaction. I "close"

no messages on the console during everything above

**Comment by molecular** [comment]
I tried with another trezor device that has an older firmware.

Except that PIN is not asked on startup of electrum, behaviour is the same:

  * start electrum
  * passphrase is asked
  * popup "trezor not detected, watch-only"

**Comment by molecular** [comment]
I went back to 2.0b3 and the old firmware works fine (not sure which version it is, don't know how to check). With the 1.3.3 firmware I had a problem with an empty popup first, but when I wanted to document this, it worked (tested signing)

**Comment by molecular** [comment]
I tried signing and sending in 2.0.4 with firmware 1.3.3, both fail with the popup "Got &lt;class 'trezorlib.messages_pb2.PublicKey'&gt;, expected (&lt;class 'trezorlib.messages_pb2.Success'&gt;,)"

**Comment by ecdsa** [comment]
thanks for all the details. I will have a look this wek end

**Comment by molecular** [comment]
cool! Thanks for all the great work.

**Comment by chrisrico** [comment]
It seems like the fimrware-Electrum version conflicts would be solved by releasing a version of the Trezor plugin per version of the firmware. Just drop the correct version into your plugin folder. Or is it not that easy due to dependencies?

**Comment by keo** [comment]
same here with fw 1.3.3 and newest plugin / bridge...

**Comment by molecular** [comment]
@chrisrico: I used the newest python-trezor from github at the time, so unless satoshilabs was slow to sync to newest firmware, that should not have been the issue.

I just pulled python-trezor and there are some changes made since then. There were some changes by slush regarding fw update on April 9th, but I should've had these included at the time of writing OP.

Will recheck soon.

**Comment by ecdsa** [comment]
@molecular do you still have this issue?

**Comment by molecular** [comment]
doesn't occur any more like this on master or 2.2

thanks for fixing!
