### ISSUE TITLE
View Address on Block Explorer

### ISSUE THREAD

**Issue by ThePiGuy** [spesmilo/electrum#1157]
Currently, you can right-click on a transaction to view it in your default block explorer.  However, can we implement a right-click feature on the "Addresses" tab so that you can view the address on your default block explorer (to see facts like total received, and a more comprehensive breakdown of transactions [I know that the details was just implemented, but it doesn't give a "total received" amount]).  Thanks!

**Comment by kyuupichan** [comment]
https://github.com/spesmilo/electrum/pull/1159
