### ISSUE TITLE
Electrum 2.1.1 - account renameing doesn't work

### ISSUE THREAD

**Issue by Perlover** [spesmilo/electrum#1158]
Hi,

new version 2.1.1 (OS Windows 7) has a bug:
I try rename account through Tab "Addresses" (i write here russian-language words in English) -> right mouse click by standard account name -> choose "Rename" -> enter new name -> after i see new name but i see in same time old account name in bottom right corner. If i do after Ctrl + Q and run again Electrum - i don't see new account name only old one. If i don't do Ctrl + Q but change account to other and return again - i see again old account name. The version 2.0.4 didn't have this bug.

May be it's convertion bug node - before installing i have downloaded and run by mistake "Standalone Executable" (i thought it's standalone executable setup - exe file not MSI). May be in this moment there some not-right conversions were done. But may be it's not reason of this bug.

**Comment by Perlover** [comment]
No answer - to close ticket
Right?

**Comment by ecdsa** [comment]
@Perlover  that bug is not very high on my list of priorities

**Comment by JulianTosh** [comment]
My limited skills have pointed me to the following relevant code snips. The logic looks sound, but I missing some experience with objects and GUI programming to really see whats wrong.

If you can see anything glaring here, tell me whats wrong and I'll do the grunt work and see if I can write the fix, test it, and submit a pull request.

gui/qt/main_window.py
```
    def edit_account_label(self, k):
        text, ok = QInputDialog.getText(self, _('Rename account'), _('Name') + ':', text = self.wallet.labels.get(k,''))
        if ok:
            label = unicode(text)
            self.wallet.set_label(k,label)
            self.update_address_tab()
```

and

lib/wallet.py
```
    def set_label(self, name, text = None):
        changed = False
        old_text = self.labels.get(name)
        if text:
            if old_text != text:
                self.labels[name] = text
                changed = True
        else:
            if old_text:
                self.labels.pop(name)
                changed = True

        if changed:
            self.storage.put('labels', self.labels, True)

        run_hook('set_label', name, text, changed)
        return changed
```
