### ISSUE TITLE
Portable 2.1.1 Synchronizing hang

### ISSUE THREAD

**Issue by btcre** [spesmilo/electrum#1162]
Portable 2.1.1 more than an hour still in Synchronizing mode
Win 7, 32bit.

**Comment by kyuupichan** [comment]
We're trying to fix these.  Meanwhile however when it happens just reopen electrum.

**Comment by ecdsa** [comment]
might be fixed by f2c2f9d73816ac671f4bf5e6cc7b4d16550cdf9d

**Comment by ecdsa** [comment]
hmm, I realize more work need to be done

**Comment by shivaenigma** [comment]
Same thing happening to me.
Using latest source from github on Ubuntu 14.04
Steps to recreate 
  - Create a new watch only wallet
  - Add address 1LuckyG4tMMZf64j6ea7JhCz7sDpk6vdcS

Electrum gets stuck at synchronizing .. where do I see the log on what it is doing ?

**Comment by ecdsa** [comment]
it's a caching issue
working to resolve that today.

**Comment by ecdsa** [comment]
please try after this commit: 44f06de7969bf0dbcbb806e3a6449f4dc1084127

**Comment by shivaenigma** [comment]
Not hanging anymore. But didnt synchronize even after 5 min of waiting. Also didnt get balance yet in the Address. Is this expected ?

**Comment by ecdsa** [comment]
it can be that your server is offline.
use auto-connect if you want it to find a server automatically.

**Comment by Shaping** [comment]
I have just started to use Electrum 2.1.1, and I cannot send the BTC I have in the wallet.  If I use the tiny window to send, I am allowed to fill in the maximum amount of BTC I have in the wallet, but cannot click Send.  Send simple does not visually depress.  If I use the larger interface, I am not permitted to fill in the maximum amount of BTC I have in the wallet.  When I type the second digit of the amount, it turns red.  Can some one explain.  I'm a little concerned.

**Comment by Shaping** [comment]
Perhaps the tiny difference between the desired amount and the actual amount based subtracted fees can be handled automatically or with a pop warning?

**Comment by ecdsa** [comment]
@Shaping please open another issue

**Comment by ecdsa** [comment]
there was another issue, fixed in e33bc2473bf0134b3a5607fd0fb494d51c6d57a2
