### ISSUE TITLE
Historical exchange rates bugs

### ISSUE THREAD

**Issue by pooler** [spesmilo/electrum#1179]
On latest git master, when deselecting the "History Rates" checkbox in the settings of the Exchange Rates plugin:
```
AttributeError: 'ElectrumWindow' object has no attribute 'column_widths'
Traceback (most recent call last):
  File "electrum/plugins/exchange_rate.py", line 444, in on_change_hist
    for i,width in enumerate(self.win.column_widths['history']):
AttributeError: 'ElectrumWindow' object has no attribute 'column_widths'
```
Also, display of historical rates appears to be buggy. Sometimes the "Fiat amount" column does not show up, and sometimes it shows up but it's empty. (Tested with CoinDesk and Winkdex.)

**Comment by ecdsa** [comment]
thanks for the notification
