### ISSUE TITLE
Exchange Rate Plugin Not Working on v. 2.1.1

### ISSUE THREAD

**Issue by badomangue** [spesmilo/electrum#1186]
Version 2.1.1 on OSX Yosemite 

Exchange rate plugin is enabled, but no exchange rate or total amount of BTC in USD is displayed next to the total amount of BTC anymore. Tried disabling and reenabling it and restarting electrum. Also cannot enter USD amount in send window to be converted to BTC amount.
![electrum](https://cloud.githubusercontent.com/assets/12216617/7443858/0fe42d92-f12e-11e4-8e11-db93d07992cf.png)

**Comment by ecdsa** [comment]
already reported and fixed, thanks

**Comment by badomangue** [comment]
Excuse my noobness, but how do I grab the fix?

**Comment by ecdsa** [comment]
wait for the next release, or learn to use git
