### ISSUE TITLE
Bitcoins stolen on electrum wallet

### ISSUE THREAD

**Issue by coincontroller** [spesmilo/electrum#1188]
Dear,

yesterday all my bitcoins are stolen on Electrum wallet, what can we do!!!!

**Comment by miohtama** [comment]
This is usually a sign that you have virus, trojan or other such infection on your computer. Your Bitcoins are most likely irreversibly lost.

[Please read here about possible threats against Bitcoin users and how to keep your Bitcoins safe](http://bitcoin.stackexchange.com/a/30336/5464)

**Comment by coincontroller** [comment]
No there are no viruses on the computer and even if see now the stolen bitcoin are awy at electrum, not on my computer, because n local wallet they are still there just the balance is wrong...

**Comment by ecdsa** [comment]
can you provide more details? 
what OS were you using?
what are the bitcoin addresses of your wallet?

**Comment by coincontroller** [comment]
WINDOWS 7

**Comment by coincontroller** [comment]
No there are no viruses on the computer and even if see now the stolen bitcoin are awy at electrum, not on my computer, because n local wallet they are still there just the balance is wrong...
![Uploading electrum.png…]()

**Comment by ecdsa** [comment]
so, electrum is displaying a wrong balance? can you post a screenshot?

**Comment by coincontroller** [comment]
![electrum](https://cloud.githubusercontent.com/assets/12231838/7535300/d5639c70-f583-11e4-82e2-afd91096399f.png)

**Comment by ecdsa** [comment]
I don't see anything unusual in this screenshot, except the 'unknown' which is caused by pruning.

**Comment by ecdsa** [comment]
maybe you could post which bitcoin addresses are involved?

**Comment by ecdsa** [comment]
note: by using a server with a higher pruning limit, you might see your whole history

**Comment by vladare** [comment]
Ledger wallet costs only 15 euro now

**Comment by ecdsa** [comment]
@coincontroller which transaction is the suspicious one?

**Comment by ecdsa** [comment]
I see no evidence for a theft here, although it would be nice to get more details from @coincontroller 
I believe he got confused by the pruning shown on the screenshot.
at least his statements are not clear. "n local wallet they are still there"

**Comment by gustavoapoher** [comment]
Buenas todo empezo cuando quise enviar 0.00103476 desde mi billetera electrum, pero me dio un error, indicandome que era necesario actualizar la billetera, fui al sitio oficinal de electrum https://electrum.org/#download. al descargar Me mostró que el mis btc 0.06120755 fueron enviado a esta wallet 18NAeQySd4vvtM6PUiv5EkXzM2pnjNzqeD que no se de quien es, transaccion d08e6b726bf7d84eb41c3515629d4cceeea827f47a80c9ec9fc59cf19e0352fb, yo no hice ninguna transaccion, se confirmó y apareció un ícono con un círculo rojo.por favor requiero de su apoyo para recuperar mis bitcoin son 0.06173416

gracias de antemano  

![Electrum](https://user-images.githubusercontent.com/49542029/56008216-6ed21180-5ca9-11e9-8715-85ec1b5e9f86.png)
![transaccion](https://user-images.githubusercontent.com/49542029/56008217-709bd500-5ca9-11e9-84fd-f03db4d85372.png)

**Comment by gustavoapoher** [comment]
envio lo que tenia en mi cuenta
![IMG-20190411-WA0003](https://user-images.githubusercontent.com/49542029/56008667-f66c5000-5caa-11e9-9a7c-f6945edb2fb7.jpg)

**Comment by gustavoapoher** [comment]
> Buenas todo empezo cuando quise enviar 0.00103476 desde mi billetera electrónica, pero me dio un error, indicando que era necesario actualizar la billetera, fui al sitio oficial de electricidad https://electrum.org/#download . Al descargar Me mostró que el btc 0.06120755 fueron enviados a esta billetera, que es una actividad extra, que puede ser útil. mis bitcoin son 0.06173416
> 
> gracias de antemano
> 
> ![Electrum](https://user-images.githubusercontent.com/49542029/56008216-6ed21180-5ca9-11e9-8715-85ec1b5e9f86.png)
> ![transaccion](https://user-images.githubusercontent.com/49542029/56008217-709bd500-5ca9-11e9-84fd-f03db4d85372.png)

**Comment by gustavoapoher** [comment]
aqui esta la transaccion que no fue realizada por mi
![blockchain](https://user-images.githubusercontent.com/49542029/56009179-e5244300-5cac-11e9-9bf2-71e905ee8a9b.png)

**Comment by gustavoapoher** [comment]
Good everything started when I wanted to send 0.00103476 from my electrum wallet, but it gave me an error, indicating that it was necessary to update the wallet, I went to the official electrum site https://electrum.org/#download. when downloading I showed that the my btc 0.06120755 were sent to this wallet 18NAeQySd4vvtM6Pviv5EkXzM2pnjNzqeD I do not know who it is, transaction d08e6b726bf7d84eb41c3515629d4cceeea827f47a80c9ec9fc59cf19e0352fb, I did not make any transaction, it was confirmed and an icon with a red circle appeared. Please require your support to recover my bitcoin are 0.06173416

Thanks in advance
![Wallet Electrum](https://user-images.githubusercontent.com/49542029/56038879-09117400-5d01-11e9-94f7-5ab6f4cefcc8.PNG)
![Transaccion](https://user-images.githubusercontent.com/49542029/56038886-0ca4fb00-5d01-11e9-83af-9a158a00e413.PNG)
![Saldo](https://user-images.githubusercontent.com/49542029/56038891-0f9feb80-5d01-11e9-850f-763d0f444ac8.PNG)
![Blockchain](https://user-images.githubusercontent.com/49542029/56038898-12024580-5d01-11e9-804b-03f6a79f0a71.PNG)
