### ISSUE TITLE
History does not distinguish between several addresses

### ISSUE THREAD

**Issue by daedadu** [spesmilo/electrum#1200]
Hi I created addresses using a seed and I'm using the OSX version.
I labeled the first two of the adresses and got BTCs on two of them.
If I go to the Addresses pane I can see that the Tx value increased on both addresses.
I know that I got 0.003726 BTC on address  with LABEL_A
and 0.03722635 on address with LABEL_B

But what the history pane shows is something different. For LABEL_A it shows me that I received 0.04095255 which is (0.003726+0.03722635) which is obviously wrong. LABEL_B is not mentioned at all.

So the history does not mention the receive addresses seperately and shows the label of only one address where the total incoming BTCs of the wallet are displayed.

I consider this a bug or does anyone has some advice to fix this?

Regards

**Comment by ecdsa** [comment]
this is obviously because you received on both addresses in the same transaction
