### ISSUE TITLE
Add "maximum" button when sending

### ISSUE THREAD

**Issue by anduck** [spesmilo/electrum#1201]
Add a button to auto-fill the transaction amount to maximum possible when sending. This is useful when someone is for example hand-picking outputs/addresses to use as inputs and wants to clear them all.

**Comment by ecdsa** [comment]
there is a keyboard shortcut for that, but users do not read the help

**Comment by anduck** [comment]
Yup. I didn't know about the shortcut (key "!") earlier. A button could still be useful.

**Comment by ecdsa** [comment]
We cannot add a button for each and every functionality in the wallet; the gui should be light.
We recently made the help available though hover links, let us see first if it improves user awareness
