### ISSUE TITLE
Improved coin selection

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1203]
Electrum should be smarter about picking from amongst its UTXOs when creating a transaction.  At present there is no consideration of reducing the amount of information leakage (both to the receiving side, and to random observers) other than putting the change in a random position.

These are some thoughts I had; I will attempt an implementation once there is some agreement, particularly from Thomas, as to the general design.  In particular, is there any objection to any of the below?  Should we make some of this a preference, or should we aim for the behaviour to be sufficiently unobjectionable that we don't expose anything as a preference?  Any other ideas I've not thought of?

**Wallet UTXO selection**

* Consider balances by address.  Because if anything is sent from an address the other side knows your full balance at that address.  In other words, once any output sent to address A is used, there is no privacy penalty in using any other output sent to address A.
* Prefer fewer input addresses in a transaction, ideally one.
* Prefer to spend the full balance of each input address provided this doesn't bloat the transaction too much.  This helps keep the UTXO set down and enhances future transaction privacy.
* Prefer sum(input address balances) - note this is not the same as sum(total inputs) - to not be huge compared to the output (e.g. prefer not to spend from a 100 BTC address when sending 0.1 BTC).  Only becomes a major issue when the excess is greater than, say, min(10% of sent amount, 5 BTC).
* Given a set of possible transactions, prefer to have a change payment of size comparable to that being sent.  Perhaps sometimes we send not one but two or three change outputs to help towards this.  e.g. if spending an address with a 6 BTC balance on a 1.9 BTC payment, perhaps split the 4.1 BTC change across two change addresses in roughly equal amounts.
* Round the change towards the same precision as the sent amount by adding rounded dust to the fee, but don't spend more than 1,000 satoshis doing so

**Comment by ecdsa** [comment]
There is no optimal coin selection policy; it only depends on what goal you want to achieve; so I think this should be a preference

**Comment by Tafelpoot** [comment]
You can always look into how the bitcoin reference does coin selection nowadays.
Interesting article: https://medium.com/@lopp/the-challenges-of-optimizing-unspent-output-selection-a3e5d05d13ef

**Comment by kyuupichan** [comment]
Yup thanks, I'd already read that.  There's not much to disagree with in that article, but because of my first bullet item I think it is missing a bit of the point regarding UTXOs from a privacy perspective: your privacy is largely a function of the addresses that were sent to you that you're selecting for your UTXOs, I believe point A in the article is oversimplified.

**Comment by sundance30203** [comment]
The suggestion of adding rounded dust to the fee is great one, one that I hadn't considered before reading this.

>> Prefer fewer input addresses in a transaction, ideally one.

Suggest writing this as: minimize the number of input addresses.

**Comment by ulrichard** [comment]
A simple improvement of privacy would already be this : 
https://github.com/spesmilo/electrum/compare/master...ulrichard:input_selection
But of course it's possible to make it a lot fancier.

**Comment by kyuupichan** [comment]
Draft that doesn't yet optimize change.  It does a good job selecting what to spend though.  Feedback appreciated.

https://github.com/kyuupichan/electrum/commit/710e7da73ee4c05d64f56d340b3fc845a0d5158b

**Comment by kyuupichan** [comment]
https://github.com/kyuupichan/electrum/compare/master...kyuupichan:coinsel

now implements every item in the bullet list of the issue.  Please use carefully and treat as beta.  It works well for the cases I've tried.

**Comment by kyuupichan** [comment]
The first 4 bullets points are implemented by choosing the Privacy coin chooser in git HEAD.  The remaining two will be coming up soon.

**Comment by kristovatlas** [comment]
I haven't reviewed the code, but concept ACK.
