### ISSUE TITLE
cold storage instructions for mac?

### ISSUE THREAD

**Issue by cardeo** [spesmilo/electrum#1214]
Hi, I'm just wondering if nice instructions on how to create cold storage wallet using a MAC are available. Basically the MAC equivalent of 

https://electrum.orain.org/wiki/Cold_storage

I don't see many of the UI tabs mentioned in the Windows docs for MAC

**Comment by ecdsa** [comment]
there should be no difference between windows and MAC. 
can you post a screenshot of what you see?

**Comment by cardeo** [comment]
I realized I was on an older version so I just updated to 2.1.1 but I'm still seeing some inconsistencies. 

On the SEND tab, I don't see "Create Unsigned Transaction" I just see a "Send" button

Also, I don't have an invoices tab

![screen shot 2015-05-18 at 1 42 21 am](https://cloud.githubusercontent.com/assets/478551/7677267/6f6bc37e-fcff-11e4-9a50-43b4eba3f741.png)

**Comment by ecdsa** [comment]
the invoices tab has been removed in 2.1
I guess it is normal that you do not see the 'create unsigned' button; 
please lean what cold storage is and  how to use it before creating bug reports
