### ISSUE TITLE
Command line not accepting opened wallet

### ISSUE THREAD

**Issue by ELM4Ever** [spesmilo/electrum#1220]
OSX system. Cloning Electrum 2.2 from Github:

python setup.py build

Then, if starting Electrum from terminal, and specifying the wallet to open,

python electrum -w /Users/xxx/.electrum/wallets/wallet_1

The GUI comes up and shows the proper wallet (wallet_1).  However, if another command line is issued, like:

python electrum getbalance, (or listaddresses),

 the results are always from the "default_wallet"  file, not the wallet that was initially requested when starting Electrum (in this case wallet_1).

**Comment by ecdsa** [comment]
-w is an option: 
electrum -w wallet getbalance

**Comment by ELM4Ever** [comment]
Ok - thanks!
