### ISSUE TITLE
Terminal commands not accepted for Trezor wallets

### ISSUE THREAD

**Issue by ELM4Ever** [spesmilo/electrum#1221]
OSX system (Yosemite). Electrum 2.2 - from Github.

When attempting to send command lines to Electrum, when the wallet was previously set to a Trezor wallet, Electrum does not recognize this type of wallet.

python electrum -w /Users/xxx/.electrum/wallets/wallet_trezor listaddresses

Traceback (most recent call last):
  File "electrum", line 376, in <module>
    wallet = Wallet(storage)
  File "/Users/xxx/CryptoArchives/electrum-2.2/lib/wallet.py", line 1786, in __new__
    raise BaseException('unknown wallet type', wallet_type)
BaseException: ('unknown wallet type', u'trezor')

The GUI version works well with the same wallet.

**Comment by ecdsa** [comment]
this is fixed now, although you still cannot create a transaction
