### ISSUE TITLE
History is pruned when funds are received from a pubkey output

### ISSUE THREAD

**Issue by jackthemind** [spesmilo/electrum#1223]
i upgrades to 2.1.2 and now my history is broken. Amount and Balance says "unknown".
The problem is only with 1 sender (Deepbit). It looks like there is no "pubkey" in the Details.

See Screenshots!

What can i do?
![github 1](https://cloud.githubusercontent.com/assets/12545432/7749431/c42febc6-ffcd-11e4-9a72-b665cc7e1bde.JPG)
![github 2](https://cloud.githubusercontent.com/assets/12545432/7749434/cc32e12a-ffcd-11e4-97a3-a4c154f914af.JPG)

**Comment by dabura667** [comment]
Manually connect to a different server.

**Comment by jackthemind** [comment]
I have try´d at least 10 different Servers. (10000 Limit). The Upgrade was from 1.98 to 2.1.2.
Have testet 2.2 exe... same issue

**Comment by ecdsa** [comment]
what kind of wallet is this? some imported address, or generated with a seed?

**Comment by ecdsa** [comment]
can you send me master public key?

**Comment by ecdsa** [comment]
The "unknown" balance in the history is normal, it only means that the server has pruned the history of your wallet. judging from the size of your scrollbar, it is plausible.
I cannot see the status bar on the screenshot. Is the balance correct there?

**Comment by jackthemind** [comment]
Ist a normal Wallet convertet from 1.98. 
A new Wallet (revovered from seed) has the same issue.
Prunning should not be the Problem. All Servers i tryed have a Limit of 10000. 
Additionally there are no adresses in the whole history and  the labels showed are only from adress-book. One time labels are empty. Label-Import works but without Change.
i am now back to 1.98 and all is o.k.
Has anyone an idea?

**Comment by ecdsa** [comment]
ok, can you answer my questions above please?

**Comment by jackthemind** [comment]
i am not sure with the balance. i think it was arround 1 btc to low. i have no screenshot with the Balance in 2.1.2 and now i am back to 1.98

**Comment by ecdsa** [comment]
can you send me the master public key?

**Comment by jackthemind** [comment]
yes but not here... can i send it as email?

**Comment by ecdsa** [comment]
sure; thomasv1@gmx.de

**Comment by ecdsa** [comment]
thanks I will investigate.
is the balance displayed on the status bar different in 1.9.8 and 2.2 ?

**Comment by jackthemind** [comment]
i don´t know. i´m back to 1.98 and i don´t have  made a screenshot from 2.1.2. 
see my post 6 hours ago.

**Comment by ecdsa** [comment]
ok, I can confirm that there is a bug in the history, because it should not display a pruned history in that case.
however, I do not see any problem with your balance.

**Comment by jackthemind** [comment]
Is there a posible solution? 
Good that the balance is o.k. but with the bug in history and especialy with the non working labels i don´t upgrade to 2.x
