### ISSUE TITLE
Wrong ussage of comma for URI Creation in spanish locale (Ubuntu)

### ISSUE THREAD

**Issue by eladio19** [spesmilo/electrum#1226]
With the help of kyuupichan, we found that Electrum uses the computer locale to create the URI, which causes problems when user specifies an amount and the locale is in Spanish (or any other comma for decimal locale), example:

bitcoin:1CDyoGTyQaFggjUPhJetsLtQMi8xVEjpM3?amount=1,01&message=Payment%20test

As you can see, the URI is made using comma instead of dot, which makes the URI invalid. Please make the electrum locale independent so it won't conflict when the user selects Spanish locale on his OS installation.

**Comment by kyuupichan** [comment]
We shouldn't be using locale when creating URIs
