### ISSUE TITLE
network.py: unanswered_requests can be answered twice leading to a dictionary pop error

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1233]
It seems commit 44f06de7969bf0dbcbb806e3a6449f4dc1084127 introduced this dictionary.  The problem is that if we switch server from one we sent requests to (apparently typically because we determine the server is lagging) to another one, we may get responses from both, leading to a double pop.

The response from the original server can be received for reasons including:

a) it was already on our response queue at switch time, we just haven't popped it yet
b) we get the response between switching and the thread actually shutting down

As the commit 44f06de7 is only two days old, and I only noticed this issue today, I'm unsure as of yet if this problem has just started becoming more likely today, or if it's been there since commit time and I've only just noticed it.

To force the double pop, in network.py line to "if self.server_is_lagging() and self.config.get('auto_cycle')" to think there is a lag with just "if True and self.config.get('auto_cycle')".

I am investigating whether lagging servers is something that has become more common because of some recent commit, or if it's always been happening and I just noticed today because of the double pop bug.

As for fixing the double pop, here are some ideas:

a) just ignore a response if we no longer have it in the unanswered list
b) or if we should ignore all non-None responses from interfaces where is_connected() is False, or
c) something else

I'm not sure which is best; it's likely a matter of taste.  a) would seem to be more robust than b), but that might be an illusion.

**Comment by ecdsa** [comment]
we should not pop a response if it does not come from self.interface

**Comment by ecdsa** [comment]
actually we should discard it

**Comment by ecdsa** [comment]
should be fixed now
