### ISSUE TITLE
Synchronization does not work (Ubuntu, Electrum v2.2)

### ISSUE THREAD

**Issue by Frezkky** [spesmilo/electrum#1238]
It seems that transaction state is updated only when the clients starts. After that, number of confirmations for a transaction does not change (I'm sure the number of confirmations incresed a long time ago according to online block explorer). I need to restart the client to get the current state.

Does anybody else encounter the same issue?

**Comment by ecdsa** [comment]
I can reproduce it, but only with the client connecting to the daemon.
were you using it?

**Comment by Frezkky** [comment]
Yes, it was probably still running when I started client.

**Comment by ecdsa** [comment]
it should be fixed now.

**Comment by Frezkky** [comment]
thx, it looks ok.
