### ISSUE TITLE
Create new Trezor wallet when Trezor is wiped causes silent fail

### ISSUE THREAD

**Issue by dabura667** [spesmilo/electrum#1240]
When clicking the next button after selecting Trezor on the Create New Hardware wallet screen, the process terminates silently with no error message. This only happens when the Trezor is in a wiped state when the wallet is created.

If initializing Trezor is not allowed, there should be a warning message and the wizard should close and return to the currently open wallet.

**Comment by kyuupichan** [comment]
I get a "device not initialized or passphrase request cancelled" message; it is not silent.  This is true whether done from the file menu or at startup via the install wizard.

I hope to support device initialization at some stage.
