### ISSUE TITLE
auto_cycle: default value?

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1241]
There are 4 references to auto_cycle in network.py; all loading via config.get.  1 defaults to True, the others to False, which doesn't make much sense.  Let's make it a member function with common behaviour.

I note that the main electrum script sets auto_cycle to False if a specific server is specified on the command line, and otherwise leaves it to default from the config files, if any.

Creating a new wallet with the "create" command line leaves no default.

Creating a new wallet in the GUI explicitly asks.  From a usability point of view, I would argue this is a question too many when first using electrum.  Is the justification that a user setting up or restoring a wallet may want to retain his privacy?

I think we should update network.py to have an auto_cycle "get" default value of True.  In testing my next pull request I noticed that new wallets created with "create" or "restore" command lines get a random server chosen, and if it's bad or unreachable they are stuck in disconnected mode because there is no auto cycling.  I don't think this makes sense as a default and might leave a bad impression.  Thoughts?

**Comment by ecdsa** [comment]
yes we have that question in the setup for privacy reasons; some users really care about it.
btw, auto_cycle is a terrible variable name, it should have been auto_connect

**Comment by kyuupichan** [comment]
I've unified the fetching with #1243.  I'll submit a PR soon to rename to auto_connect.
