### ISSUE TITLE
Option to open existing wallet when default_wallet does not exist

### ISSUE THREAD

**Issue by ChristopherJSanborn** [spesmilo/electrum#1250]
I am a user who keeps my wallet files on an encrypted disk image that I only mount when needed.  After running Electrum for the first time, I simply renamed and moved the default_wallet file to its intended location.  However the result was that the next time I opened Electrum, it could not find the last opened wallet file (default_wallet), and so presented me with the "new wallet" dialog, which has options for restoring a wallet from seed, but NO options to simply open an existing wallet file that might be in a different file/location.  This means I have to create a dummy wallet just to get to the main menu (because if I cancel the wizard the program exits), so that I can then open the intended wallet.  This is an awkward solution, as I then have to delete the new default_wallet to make sure I don't accidentally use it.  It is somewhat helpful that the app does remember the last opened wallet, but, if the path to where I do keep my wallets changes (or if I forget to mount the disk image before opening Electrum), I will have to go through the throw-away wallet process all over again.

The current two options on the "new wallet" wizard are "create new" or "restore from seed".  Can a third option be added to "open existing wallet file"?

**Comment by thephez** [comment]
An easy alternative is to set up a shortcut to open the specific wallet(s) you want as described here - https://bitcointalk.org/index.php?topic=100502.msg1520836#msg1520836.  

In Windows, you would use the following syntax:
"C:\Program Files\Electrum\electrum.exe" -w X:\Electrum\wallets\your_wallet_name

I don't know if that will resolve your issue, but it may help.

**Comment by throwawayyy** [comment]
I agree this third option as mentioned above is needed.

**Comment by dabura667** [comment]
Currently Electrum opens the last file opened.

If the last file opened no longer exists (it was moved etc) it looks for default_wallet in the default wallet path.

If it doesn't find it, it opens the Create new wallet wizard.

Solution:

Leave a dummy default_wallet with nothing in it in the default wallet path.

Or make sure your encrypted volume is mounted BEFORE you start Electrum.
