### ISSUE TITLE
Something wrong with payment requests

### ISSUE THREAD

**Issue by nomnombtc** [spesmilo/electrum#1251]
Hello,

a few days ago I set firefox to handle bitcoin: requests with electrum,
so today I ordered a Pizza and click the link on bitpay checkout page.

Now electrum wants to send 90913 mBTC instead of 90,913 mBTC
I also tried with electrum set to BTC instead mBTC and it wanted to send 90913 BTC.

here is a screenshot: http://i.imgur.com/evvE7xw.jpg

Not sure what, but something seems to be wrong there.

Greetings

**Comment by kyuupichan** [comment]
This will be fixed in the next release.  In the meantime you could set your locale to one that doesn't use a comma for a decimal point.

**Comment by kyuupichan** [comment]
Actually this seems to be something different to what I thought.

**Comment by kyuupichan** [comment]
Can you attach the payment request text?

**Comment by ecdsa** [comment]
I can reproduce that bug. 
It occurs if the amount includes a decimal point.

**Comment by kyuupichan** [comment]
See PR #1254 .  Does that fix it?
