### ISSUE TITLE
`pip install --user` tries to install `.desktop` to /usr/share/applications

### ISSUE THREAD

**Issue by cbm755** [spesmilo/electrum#1256]
Without root, I tried:

````
[~] pip install --user https://download.electrum.org/Electrum-2.2.tar.gz

---- 8< -----

Installing collected packages: Electrum, dnspython, tlslite, pbkdf2, slowaes
  Running setup.py install for Electrum
    changing mode of build/scripts-2.7/electrum from 644 to 755
    error: [Errno 13] Permission denied: '/usr/share/applications/electrum.desktop'
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-0mD0aH-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6h8r5d-record/install-record.txt --single-version-externally-managed --compile --user:
    running install
    
    running build
    
---- 8< -----


    
    byte-compiling /home/cbm/.local/lib/python2.7/site-packages/electrum/old_mnemonic.py to old_mnemonic.pyc
    
    running install_data
    
    copying electrum.desktop -> /usr/share/applications/
    
    error: [Errno 13] Permission denied: '/usr/share/applications/electrum.desktop'
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-0mD0aH-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6h8r5d-record/install-record.txt --single-version-externally-managed --compile --user" failed with error code 1 in /tmp/pip-0mD0aH-build
````

Perhaps you have some kind of install script (with a hardcoded path) instead of letting pip deal with it?

It should rather go to `${home}/.local/share/applications`.

**Comment by kyuupichan** [comment]
I find that hard-coding a little annoying too - it's the only part of electrum that needs patching to install in the FreeBSD/DragonglyBSD ports system.  I'm not sure what it's there for; perhaps Thomas can comment.

**Comment by ecdsa** [comment]
feel free to fix this, I am no expert

**Comment by cbm755** [comment]
sorry nor am I.  Something about $XDG?  But I'm not likely to get around to learning more...

**Comment by ecdsa** [comment]
I cannot reproduce that problem.
make sure that you have a recent version of pip, and let me know if it fixes it.

**Comment by cbm755** [comment]
Yes you're right.  Bug happens with pip `6.0.8` but seems to work fine with pip `7.0.3`.  Sorry for the noise.

**Comment by uvok** [comment]
I'm using

    $ pip --version
    pip 7.1.2 from /usr/lib64/python2.7/site-packages (python 2.7)

And when I execute

    $ pip install --user https://download.electrum.org/Electrum-2.4.4.tar.gz

it still does this

    running install_data
    copying electrum.desktop -> /usr/share/applications/
    error: [Errno 13] Permission denied: '/usr/share/applications/electrum.desktop'
