### ISSUE TITLE
electrum doesn't start on mac

### ISSUE THREAD

**Issue by thestick613** [spesmilo/electrum#1258]
I have generated a simple wallet. I have the 13 words seed, and the password. I sent some money to one of the addresses that have been generated, and I have imported a private key using the console. I exited electrum, then ran it again, and this happened.

28/05/15 12:15:14,770 Electrum[29858]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.3 instead of 10.10.3. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
28/05/15 12:15:14,770 Electrum[29858]: 0   CarbonCore                          0x00007fff9178d2b7 ___Gestalt_SystemVersion_block_invoke + 113
28/05/15 12:15:14,770 Electrum[29858]: 1   libdispatch.dylib                   0x00007fff9c5ccc13 _dispatch_client_callout + 8
28/05/15 12:15:14,770 Electrum[29858]: 2   libdispatch.dylib                   0x00007fff9c5ccb26 dispatch_once_f + 117
28/05/15 12:15:14,770 Electrum[29858]: 3   CarbonCore                          0x00007fff91716456 _Gestalt_SystemVersion + 987
28/05/15 12:15:14,771 Electrum[29858]: 4   CarbonCore                          0x00007fff917156e3 Gestalt + 144
28/05/15 12:15:14,771 Electrum[29858]: 5   QtCore                              0x000000010652dfb6 _ZN9QInternal12callFunctionENS_16InternalFunctionEPPv + 2166
28/05/15 12:15:14,771 Electrum[29858]: 6   ???                                 0x00007fff68f63ceb 0x0 + 140734954355947
28/05/15 12:15:16,075 Electrum[29858]: Traceback (most recent call last):
28/05/15 12:15:16,075 Electrum[29858]:   File "/Applications/Electrum.app/Contents/Resources/__boot__.py", line 125, in <module>
28/05/15 12:15:16,075 Electrum[29858]:     _run()
28/05/15 12:15:16,075 Electrum[29858]:   File "/Applications/Electrum.app/Contents/Resources/__boot__.py", line 62, in _run
28/05/15 12:15:16,076 Electrum[29858]:     exec(compile(source, path, 'exec'), globals(), globals())
28/05/15 12:15:16,076 Electrum[29858]:   File "/Applications/Electrum.app/Contents/Resources/electrum.py", line 250, in <module>
28/05/15 12:15:16,076 Electrum[29858]:     gui.main(url)
28/05/15 12:15:16,076 Electrum[29858]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 224, in main
28/05/15 12:15:16,076 Electrum[29858]:     w.load_wallet(wallet)
28/05/15 12:15:16,077 Electrum[29858]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/main_window.py", line 207, in load_wallet
28/05/15 12:15:16,077 Electrum[29858]:     self.update_wallet_format()
28/05/15 12:15:16,077 Electrum[29858]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/main_window.py", line 258, in update_wallet_format
28/05/15 12:15:16,077 Electrum[29858]:     if self.wallet.get_master_public_keys() and self.wallet.addresses() == []:
28/05/15 12:15:16,077 Electrum[29858]:   File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1393, in get_master_public_keys
28/05/15 12:15:16,077 Electrum[29858]:     mpk_text = '\n\n'.join( account.get_master_pubkeys() )
28/05/15 12:15:16,078 Electrum[29858]: AttributeError: 'ImportedAccount' object has no attribute 'get_master_pubkeys'
28/05/15 12:15:16,090 Electrum[29858]: Electrum Error
28/05/15 12:15:16,090 Electrum[29858]: 2015-05-28 12:15:16.089 Electrum[29858:6914278] Electrum Error

**Comment by ecdsa** [comment]
electrum version >= 2 does not allow to import a private key in a seeded wallet.
the console should not allow the user to import a private key.

**Comment by thestick613** [comment]
that's what i thought. i've created a separate wallet for it.
Still, it shouldn't have let me do it.

**Comment by ecdsa** [comment]
fixed in 3fdfd23ca995893390f6ce77f468f91f3b4f33fc
