### ISSUE TITLE
Problems with parsing Bitcoin url scheme

### ISSUE THREAD

**Issue by davidhq** [spesmilo/electrum#1259]
I get: 

```Invalid bitcoin URI:
'QByteArray' object has no attribute 'find'```
http://cl.ly/image/473W3E0I0L2H

When I click on links on the bottom of this page:
https://en.bitcoin.it/wiki/BIP_0021

Format: `bitcoin:<address>?amount=1`

My Electrum (Mac) version: Electrum v2.2

**Comment by ecdsa** [comment]
I thought the OSX version did not support bitcoin URI at all?

**Comment by ecdsa** [comment]
are you using the binaries, or running from source?

**Comment by davidhq** [comment]
binaries

**Comment by fabianfabian** [comment]
Same problem here. From binary version 2.2
![screen shot 2015-05-30 at 21 34 07](https://cloud.githubusercontent.com/assets/343640/7899012/a0ae1040-0713-11e5-99af-2a9271edeeb2.png)

Using this uri: bitcoin:1K5ZpbaxR542Qj47Jm5GwMoWsNtiHpo53g?label=bitzuma.com&amount=0.002
