### ISSUE TITLE
Showing imported keys before main wallet

### ISSUE THREAD

**Issue by KintaroBC** [spesmilo/electrum#1262]
Electrum shows imported keys before the main wallet, which is quite annoying because I have to scroll down to use addresses from the main wallet. They are the addresses I want to use, the imported ones are just from an old client and are only there for record keeping.

Another problem with this is every time the wallet syncs, the imported keys expand again. I like to have them hidden.

There are two ways to make this less annoying: allow me to keep imported keys hidden, or display the main wallet before imported keys.

**Comment by ecdsa** [comment]
won't fix.
imported addresses are deprecated in new wallets.
you should create a separate wallet for them

**Comment by KintaroBC** [comment]
How do I get them out of the wallet I'm using? Do I have to start a new wallet?

**Comment by ecdsa** [comment]
create a new wallet of imported keys
