### ISSUE TITLE
Can't broadcast 2 of 3 multisig transaction when signed with 3 wallets.

### ISSUE THREAD

**Issue by zowki** [spesmilo/electrum#1282]
I can't broadcast a signed transaction from a 2 of 3 multisig wallet. It says partially signed even though it has been signed by all 3 wallets. See screenshot: http://i.imgur.com/1YDuV4y.png

Here's how to replicate my bug:
1. Restore a 2 of 3 multisig wallet by entering all 3 seeds (13 word seeds) on an offline computer.
2. Create watch only version of this wallet on an online computer by entering all 3 master public keys.
3. Send some bitcoin to the wallet.
4. Create unsigned transaction from watch only wallet.
5. Load unsigned transaction and sign it with the wallet with all 3 seeds (offline computer).
6. Try to to broadcast the transaction from the watch only wallet (online computer).

I used Electrum 2.2 on both the offline and online computer.
Offline computer ran Linux while online computer ran Windows 7.

**Comment by dabura667** [comment]
Only sign it 2 times. 3 signatures on a 2 of 3 is not a valid transaction.

**Comment by zowki** [comment]
In that case electrum should not allow you to enter 3 seeds when restoring a 2 of 3 multisig wallet.

Alternatively, electrum should only use 2 signatures when signing a transaction if 3 seeds has been entered.

**Comment by dabura667** [comment]
By the way, why would you have 3 keys if you're only using 1 device?

**Comment by zowki** [comment]
I use 2 of 3 multisig for backup security. I backup the 3 seeds in 3 different locations. If one of the seeds is stolen, the thief won't be able to spend my bitcoins.

**Comment by ecdsa** [comment]
should be fixed now
