### ISSUE TITLE
Mining + Wallet

### ISSUE THREAD

**Issue by AidPearce** [spesmilo/electrum#1293]
Mining.
Hello.
The issue of mining on the wallet Electrum 2.2.
They came to the mining pool of money http://eligius.st/, but in coin purses are displayed as "unmatured". Admins pool, saying that it will be possible to use the facilities after the 100 blocks. It takes an average of 17 hours. In my case, four days have passed, the coins still "unmatured" and are in the "Section" spent (Used).
What is the problem?

**Comment by ecdsa** [comment]
is your wallet online? if it's offline it will not see that your coins have matured

**Comment by AidPearce** [comment]
Wallet online!

**Comment by ecdsa** [comment]
can you post a screenshot?

**Comment by AidPearce** [comment]
Screen

![scr](https://cloud.githubusercontent.com/assets/12866261/8144372/89e38648-11e4-11e5-9730-e11910d6b79c.png)

Hash:
https://blockchain.info/address/17jdJ4KdwdhQv2RrfWidhzwfFi4TDQDAv

**Comment by ecdsa** [comment]
thanks, can you post a screenshot of the 'Details'  window for the corresponding transactoion?

**Comment by ecdsa** [comment]
also, in the console, please type this, and paste the result:
wallet.history.get('17jdJ4KdwdhQv2RrfWidhzwfFi4TDQDAv')

**Comment by AidPearce** [comment]
![scr1](https://cloud.githubusercontent.com/assets/12866261/8144592/0cb031b2-11ee-11e5-955d-d0e633c7fd7d.png)

**Comment by AidPearce** [comment]
*also, in the console, please type this, and paste the result:
wallet.history.get('17jdJ4KdwdhQv2RrfWidhzwfFi4TDQDAv')

I did not quite understand!?!

**Comment by ecdsa** [comment]
all your transactions are shown as 'unverified'.
this suggests a problem with the SPV process.

go to the 'consol' tab, and type: 
network.get_local_height()

**Comment by ecdsa** [comment]
I mean, paste the result here :)

**Comment by AidPearce** [comment]
I'm sorry of course, but I hope that you correctly understood and what should be done. :)


>> wallet.history.get('17jdJ4KdwdhQv2RrfWidhzwfFi4TDQDAv')
[[u'3a1485e2d0d2f583e5c3af248f442028bd75d2d4d24c24d9c3cfe574bacc8b36', 360131]]
>> 
>> network.get_local_height()
4197L
>>

**Comment by AidPearce** [comment]
I'm sorry of course, but I hope that you correctly understood and what should be done. :)


>> wallet.history.get('17jdJ4KdwdhQv2RrfWidhzwfFi4TDQDAv')
[[u'3a1485e2d0d2f583e5c3af248f442028bd75d2d4d24c24d9c3cfe574bacc8b36', 360131]]
>> 
>> network.get_local_height()
4197L
>>

**Comment by ecdsa** [comment]
hmm, can you launch electrum from a terminal, and see if there is a traceback?

**Comment by AidPearce** [comment]
How to do it?

**Comment by ecdsa** [comment]
wha's your operating system?

**Comment by AidPearce** [comment]
Windows 7

**Comment by ecdsa** [comment]
well, isn't there something called console or terminal in windows? 
type 'electrum' in it

**Comment by ecdsa** [comment]
http://smallbusiness.chron.com/open-terminal-session-windows-7-56627.html

**Comment by dabura667** [comment]
Unfortunately, no. The windows installer will not install a cli into Windows cmd.

@AidPearce Try going to `C:\Users\YOURNAME\AppData\Roaming\Electrum` folder and deleting the file called `blockchain_headers` then restart Electrum.

**Comment by ecdsa** [comment]
@dabura667 if he deletes the headers file, we will never know why it crashed...

**Comment by dabura667** [comment]
In that case, he will need to do the following:

1. Install Python 2.7 for Windows
2. Install Python QT4 for Windows
3. Add Pythonx27 to the environment variable
4. install all the dependencies by either a. installing each one through python setup.py install for each source package, or downloading one of the many iffy pip mimicing Windows programs.
5. Run Electrum cli through python after setting it up with `python electrum <command>` in the cmd window.

in order to get the cli working.

**Comment by ecdsa** [comment]
that sounds complicated indeed..

**Comment by dabura667** [comment]
Maybe for future debugging purposes adding a preference option "Show traceback in command tab" with a checkbox might be better for Windows users debugging...

**Comment by ecdsa** [comment]
yes that's something we should have

**Comment by AidPearce** [comment]
*that sounds complicated indeed ..
I do not understand anything here. :) It's hard to somehow everything.

**Comment by ecdsa** [comment]
@AidPearce just remove the blockchain_headers file and it should work

**Comment by AidPearce** [comment]
This wallet is for experts. :)

**Comment by AidPearce** [comment]
Remove. Restart. unmatured ... ((

**Comment by dabura667** [comment]
https://mega.co.nz/#!DdI2ybyK!dWRiLfSh-n_F3F8Wd9FBJQf4RW6H4EAmOYOQj4WS_-0

Try replacing the files with this

**Comment by dabura667** [comment]
(it's my blockchain headers)

**Comment by ecdsa** [comment]
@AidPearce what does "network.get_local_height()" return this time?

**Comment by AidPearce** [comment]
>> network.get_local_height()
-1L

*(it's my blockchain headers)
Now I will try.

**Comment by ecdsa** [comment]
maybe this fixed it: ec9cdfaf48781356ad51db836c2336681d7c2caa

**Comment by AidPearce** [comment]
maybe this fixed it: ec9cdfa
?

**Comment by dabura667** [comment]
@AidPearce he made a commit to the repository.

You will not be able to use that fix until he or someone else generates an executable file for you (exe file)

**Comment by ecdsa** [comment]
yes, this is a note for myself. I failed to completely revert @kyuupichan 's commit to blochain.py; that missing line triggers a chunk-by-chunk download of the file.

**Comment by AidPearce** [comment]
It worked, after replacing blockchain headers (dabura667 commented 8 hours ago
https://mega.co.nz/#!DdI2ybyK!dWRiLfSh-n_F3F8Wd9FBJQf4RW6H4EAmOYOQj4WS_-0
Try replacing the files with this).

dabura667, ecdsa, thank you friends!
