### ISSUE TITLE
importprivkey is broken

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#1298]
Electrum 2.2 and below:
```
>> importprivkey('5KdQmGoY4m2HK1WBLyRJ64hftfciGVtcDYvFD3ZrMVoyQGM1CBF')
[
    "Keypair imported: ", 
    "1LZqQu8NBB7og3J2msoguAFK5pza4RMedi"
]
>> importprivkey('KzTrstZavueRFvCS7MT9QXLGCLP9KrT3J4pmKJfaYukS6AvsWhWN')
[
    "Keypair imported: ", 
    "1LZraDqavRX2UtsrcVG5s62b8w58ZckoxM"
]
```

Electrum 2.3 and above:
```
>> importprivkey('5KdQmGoY4m2HK1WBLyRJ64hftfciGVtcDYvFD3ZrMVoyQGM1CBF')
"Error: Keypair import failed: "
>> importprivkey('KzTrstZavueRFvCS7MT9QXLGCLP9KrT3J4pmKJfaYukS6AvsWhWN')
"Error: Keypair import failed: "
```

But if I restore the wallet using my private keys, *importprivkey()* works without problems.
It does not work only in the seed mode. Behavior of Electrum 2.2 seems more suitable.

**Comment by ecdsa** [comment]
importprivkey is not allowed with seeded wallets since 2.0
it still works with old seeds. 
I guess that's what you are expericencing.

**Comment by ecdsa** [comment]
I added a better error message here: 74d26f5bdcfcd6ca49c00ad6345ab81ca50f8f99

**Comment by lzsaver** [comment]
> importprivkey is not allowed with seeded wallets since 2.0

It looks like your statement is incorrect. I thought you know that your code performs.

```
$ test ! -e "${HOME}/.electrum" && echo OK
OK
$ virtualenv electrum-2.0
$ pushd electrum-2.0/
$ ./bin/pip install https://download.electrum.org/Electrum-2.0.tar.gz
$ ./bin/electrum create
$ ./bin/electrum importprivkey 5KdQmGoY4m2HK1WBLyRJ64hftfciGVtcDYvFD3ZrMVoyQGM1CBF
[
    "Keypair imported: ", 
    "1LZqQu8NBB7og3J2msoguAFK5pza4RMedi"
]
$ ./bin/electrum importprivkey KzTrstZavueRFvCS7MT9QXLGCLP9KrT3J4pmKJfaYukS6AvsWhWN
[
    "Keypair imported: ", 
    "1LZraDqavRX2UtsrcVG5s62b8w58ZckoxM"
]
$ popd
```

> it still works with old seeds.

I did not say that I use old seeds. I think that the default seed format was used here.
Electrum 2.0 and above creates seeds that are compatible with BIP32, does not it?

> I added a better error message here: 74d26f5

Electrum 2.0-2.2 imports my keys to my seeded wallet without any problems.
It is okay that you disabled this in a GUI. But the console is for geeks, is not it?

**Comment by ecdsa** [comment]
right, the assert statement was missing in 2.2, so technically you could still import with cmd line.
but it was not supposed to work that way
