### ISSUE TITLE
making seeds non-BIP39 compatible 

### ISSUE THREAD

**Issue by simcity4242** [spesmilo/electrum#1300]
@ecdsa I propose that all Electrum 2.x mnemonic seeds are generated such that the 12 word phrases generated are NOT BIP39 compatible. It would clearly delineate Electrum 2.x from BIP39.
@gurnec provides the [loss in entropy as <0.05 bits](http://www.wolframalpha.com/input/?i=solve++%282%5En+-+1%29+%2F+2%5En+%3D+2047%2F32768+%C3%97+1%2F16++for+n) at the [SE discussion](http://bitcoin.stackexchange.com/a/38027/9382)

**Comment by ecdsa** [comment]
I believe 12-word seeds are more user friendly than 13-word seeds.
We currently have 13 words seeds becaus of the size of the wordlist.
I plan to increase the size of the wordlist in order to get back to 12 words seeds without loss of entropy.

**Comment by gurnec** [comment]
In order to guarantee that current Electrum 2.x seeds are not BIP-39 valid, Electrum would have to (now and forever more) ship with the BIP-39 word lists. Avoiding being tied to / having to maintain any particular word list was I think one of the reasons behind Electrum 2.x's choices....

As an alternative, if a new longer (at least 2581 words) list is created for 12-word seeds, it could be created with no shared words with BIP-39. Of course, generating a decent such list is non-trivial....

**Comment by ecdsa** [comment]
A better solution is for other wallets to stop using BIP39.
BIP39 is a failed design, and this is not an Electrum issue.

**Comment by ecdsa** [comment]
OTOH if you insist on using BIP39, it is trivial to ensure that your seeds are non-electrum compatible, you don't need a wordlist for that; you just need a hash.

**Comment by gurnec** [comment]
> A better solution is for other wallets to stop using BIP39. [...] this is not an Electrum issue.

FWIW I agree.

I think the only bullet-proof solution is for @simcity4242 to "bite the bullet" and do a `is_electrum2_mnemonic()`, `is_bip39_mnemonic()`, etc. and force the user to select a type if an ambiguity is found (and likewise for ambiguities between BIP-39 word lists).

> BIP39 is a failed design,

I don't want to start an argument... I'd just say "inferior" IMHO.

**Comment by simcity4242** [comment]
>A better solution is for other wallets to stop using BIP39.

Agreed, to a certain extent. I'm just trying to be pragmatic about standards. From an outsider perspective, a mnemonic phrase should work without having to know: 

 1. the standard (BIP39, Electrum etc)
 2. standard's version (Electrum 1 or 2, for eg)
 3. language (some BIP39 word lists have ambiguities)

**Comment by andronoob** [comment]
@ecdsa I wonder if the ambiguity avoided (during Electrum 2.0 seed generation)/handled (during seed importing)?

**Comment by andronoob** [comment]
Finally, #6001 is going to avoid "BIP39-Electrum2.0 duality" - however I recently realized that even Electrum can do its best to avoid such ambiguity, Electrum itself still cannot stop other BIP39 wallets (which don't take Electrum 2.0 seed into consideration) to generate BIP39 mnemonics which are accidentally a valid Electrum2.0 seed at same time, although the probaility of the later case is very low (about 0.439%)

**Comment by klassare** [comment]
Import the following wallet will fail

> {
      sk: 'spsk1kev1AKbjd7u1BRJcAPaj3yGBqk4QH6GDZRKKabrm1d16vtv8R',
      pk: 'sppk7afSZ3W58865pREkZ7a8AkmEABLcHwivS7EdXeQefVF2dCA81Xx',
      pkh: 'tz2PQrZYkyT5Hygugj5kNYZetEyEuJZRRuPf'
}

=>

> clip ship face foster witness coach decorate slot cabbage page potato exist brother bird jelly all quit virtual into clock drastic satisfy town mention

Problem is that there's a 1/256 probability that a mnemonic is both a valid mnemnic and a valid shiftedMnemonic. Need to consider alternative approaches.
