### ISSUE TITLE
Easily changing wallets

### ISSUE THREAD

**Issue by ThePiGuy** [spesmilo/electrum#1303]
I change wallets on a regular basis (I have four HD wallets I change between on a regular basis).  It's inefficient to go File > Open > etc.

Beside the seed, prefs, network settings, etc. buttons on the bottom of the screen, could we add a dropdown menu that lets you select a wallet, and then another option to add a "Favourite Wallet" (a wallet that's listed in that list on the bottom). This would enable easy switching.  Let me know what everyone thinks.

**Comment by lathan** [comment]
:+1:

**Comment by ecdsa** [comment]
done in eef49a328a9af499c616a5bd41355ba26ed31906
