### ISSUE TITLE
Option to skip transaction fee confirmation

### ISSUE THREAD

**Issue by SmileyChris** [spesmilo/electrum#1305]
Unless I'm overlooking some option that exists already, the current behaviour seems very user unfriendly to have a popup confirmation dialog for the transaction fee for every single payment.

If it is deemed necessary, can we have an option to just automatically approve it? Am I overlooking some reason why it's critical to notify the user of this fee for every transaction they make?

**Comment by ecdsa** [comment]
did you consider enabling the 'set fees manually' option?

**Comment by SmileyChris** [comment]
This is definitely just a feature request. I realise that I could set this manually, but I'm not sure why I should have to just to avoid a popup. :smirk_cat:

**Comment by SmileyChris** [comment]
"Set fees manually" has been working fine for me, so I'm going to close this. Contrary to how I thought it'd work, it still sets the default to a sensible value which was why I had never turned it on in the first place.
