### ISSUE TITLE
"trezor device not detected" since version 2.3

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1306]
I just went through the tags starting at 2.0b3. In 2.2 things still work (trezor is detected and I'm prompted to enter PIN and passphrase, can make tx), but starting at 2.3, I consistently get the popup saying "trezor device not detected, continuing in watch only mode" on startup. This is true for 2.3, 2.3.1, 2.3.2 and master.

There's no error on the terminal. Trezor is shown in lsusb:

   Bus 001 Device 093: ID 534c:0001 SatoshiLabs Bitcoin Wallet [TREZOR]

**Comment by molecular** [comment]
damn, I started getting problems with 2.2, also.

So I tried a different usb cable and that fixed it (now works in master)

**Comment by molecular** [comment]
The problem is back even with the new cable.

I'm confused

It stopped working after I tried to make a tx (being on master) and I got this:

```
Traceback (most recent call last):
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/main_window.py", line 1113, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 341, in sign_transaction
    if not self.check_proper_device():
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor.py", line 437, in check_proper_device
    self.get_client().ping('t')
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 68, in wrapped_f
    ret = f(*args, **kwargs)
  File "/mnt/maui/home/nick/bitcoin/electrum/trezorlib/client.py", line 84, in wrapped_f
    raise Exception("Got %s, expected %s" % (ret.__class__, self.expected))
Exception: Got <class 'trezorlib.messages_pb2.PublicKey'>, expected (<class 'trezorlib.messages_pb2.Success'>,)
```

**Comment by molecular** [comment]
I'll try a different trezor device.

**Comment by ecdsa** [comment]
what's your version of the firmware?

**Comment by molecular** [comment]
firmware is version 1.3.3

**Comment by ecdsa** [comment]
hi, can you retry with latest git?

**Comment by molecular** [comment]
fixed, thank you!

**Comment by Thireus** [comment]
Hi,

Has this issue been fixed? Can we close it?

**Comment by molecular** [comment]
yes, it's fixed
