### ISSUE TITLE
[linux-debian] btchip "Invalid literal for Decimal"

### ISSUE THREAD

**Issue by ziomik** [spesmilo/electrum#1311]
when I try to send I get this error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/main_window.py", line 1113, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_plugins/btchipwallet.py", line 341, in sign_transaction
    raise BaseException(tx.error)
BaseException: Invalid literal for Decimal: '0,0001'

**Comment by ecdsa** [comment]
@btchip this is for you

**Comment by ziomik** [comment]
![errore-electrum](https://cloud.githubusercontent.com/assets/925909/8311848/6be18fe4-19d9-11e5-8b81-a98004066388.png)

**Comment by btchip** [comment]
ok, that sounds like a locale problem. I'll try to reproduce it to see what's causing it.

**Comment by ecdsa** [comment]
maybe have a look at format_satoshis_plain in util.py

**Comment by ziomik** [comment]
Debian 8 Jessie released, clean and newly installed. Chose KDE as a graphical interface.
Italian language chosen and followed as written in the pastebin (written by me to keep track): http://pastebin.com/Fc8TDPC5

**Comment by btchip** [comment]
could be worth a try, @ziomik can you try to replace all occurrences of format_satoshis by format_satoshis_plain in plugins/btchipwallet.py and retry ?

**Comment by ziomik** [comment]
I made the requested change and now it works. was born a new problem that is displayed after inserting the keycard (obviously correct)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/main_window.py", line 1113, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_plugins/btchipwallet.py", line 341, in sign_transaction
    raise BaseException(tx.error)
BaseException: Could not connect to your BTChip dongle. Please verify access permissions, PIN, or unplug the dongle and plug it again
![errore-electrum1](https://cloud.githubusercontent.com/assets/925909/8315029/d59d8b54-19ed-11e5-99c7-a31cccc742cf.png)
Tried several times

**Comment by btchip** [comment]
Are you using it in Ledger Wallet mode (paired with an external printed keycard) or in HW.1 mode (where you need to insert it / remove it again to read the PIN) ?

**Comment by ziomik** [comment]
I am using a HW.1. I tried to pull it out and put it when I asked the first pin but I got this error:

![errore-electrum2](https://cloud.githubusercontent.com/assets/925909/8315266/b54a9368-19ef-11e5-92e6-c5c069d5c55a.png)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/main_window.py", line 1113, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_plugins/btchipwallet.py", line 341, in sign_transaction
    raise BaseException(tx.error)
BaseException: Exception : Invalid status 6a80

**Comment by btchip** [comment]
ok, have you used it once with the Ledger Wallet Chrome application or is it an "old" HW.1 bought before Ledger was selling them ? 

If it's an old HW.1, the sequence to sign is the following 

- Remove it 
- Insert it again on the same computer / different program or different computer where it can type
- Read the second factor string and 2FA code
- Plug it back into the first computer (or remove it, insert it again) 
- Enter this 2FA code

And if it's a HW.1 paired with Ledger Wallet Chrome application you don't need to remove it, you can directly enter the Security Card matching characters.

**Comment by ziomik** [comment]
It is a HW.1 purchased from a few weeks. firmware 1.0.1
It works great with ledgerwallet in paring with my smartphone.
I have, perhaps, remove the paring to use the same wallet of electrum?

**Comment by btchip** [comment]
No, you don't have to remove the pairing. Electrum should prompt you to match the security card, not to remove / insert again the chip. If that's what you see, I'll try to modify something that you can test.

**Comment by ziomik** [comment]
All right. I look forward to some changes. thanks

**Comment by btchip** [comment]
Can you try with this patch ? i.e. move the 3 lines in the else: branch.

```
--- a/plugins/btchipwallet.py
+++ b/plugins/btchipwallet.py
@@ -430,9 +430,9 @@ class BTChipWallet(BIP32_HD_Wallet):
                         if not confirmed:
                             raise Exception('Aborted by user')                                            
                         pin = pin.encode()
-                    self.client.bad = True
-                    self.device_checked = False
-                    self.get_client(True)
+                        self.client.bad = True
+                        self.device_checked = False
+                        self.get_client(True)
                     waitDialog.start("Signing ...")
                 else:
                     # Sign input with the provided PIN
```

**Comment by ziomik** [comment]
Hi, I have made the required changes, but the problem persists:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/main_window.py", line 1113, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_plugins/btchipwallet.py", line 341, in sign_transaction
    raise BaseException(tx.error)
BaseException: Could not connect to your BTChip dongle. Please verify access permissions, PIN, or unplug the dongle and plug it again

**Comment by ziomik** [comment]
Hi, I have made the required changes. Now I get this message:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/main_window.py", line 1113, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_plugins/btchipwallet.py", line 341, in sign_transaction
    raise BaseException(tx.error)
BaseException: Exception : Invalid status 6a80

**Comment by btchip** [comment]
Can you try to change BTCHIP_DEBUG to True at the beginning of the plugin and post the logs ?

**Comment by ziomik** [comment]
ziomik@debian-pc:~$ electrum -v          
electrum directory /home/ziomik/.electrum
[profiler] init_plugins 0.0290
[Network] starting network
[Blockchain] 362307 blocks
wallet path /home/ziomik/.electrum/wallets/default_wallet
Loading plugin by constructor: btchipwallet
[profiler] load_transactions 0.0001
=> f026000000
<= 6d00
=> e0c4000000
<= 012001000101109000
=> e024000000
<= 019000
=> e02280000130
<= 63c3
[EAST.electrum.jdubya.info] cannot resolve hostname
[WEST.electrum.jdubya.info] cannot resolve hostname
[electrum2.hachre.de] cannot resolve hostname
[electrum.xiro.co] connected
[Network] switching to electrum.xiro.co:50002:s
[Network] sending subscriptions to electrum.xiro.co:50002:s 0 0
[electrum0.snel.it] connected
[electrum.be] connected
[electrum.thwg.org] failed to connect [Errno 111] Connessione rifiutata
[electrum.drollette.com] connected
[ecdsa.net] connected
[profiler] save_transactions 0.0343
[electrum.no-ip.org] connected
[us.electrum.be] connected
[jwu42.hopto.org] connected
=> e02200000438373335
<= 009000
=> e0c4000000
<= 012001000101109000
=> e04000000d038000002c8000000080000000
<= 410443ba492829ee426f47855c9b4d0f9e2e7fadd21abd4bf6059a0a9a336c362fabc19234858400bfb504efd49b009e78c446162de6782aacad230abee78cdc8f752231486b70347242416a33357a6672564c6165384a65444644776b58596672684c563304c5d7e3f8a3bf22ce8cb52bc3420928d9a9d7f338db8cab18b3a78bc59c40bb9000
using 1 inputs
change 10000
using 1 inputs
change 10000
using 1 inputs
change 10000
using 1 inputs
change 999000
using 1 inputs
=> e042000009000000000100000001
<= 9000
=> e04280002536174c8bd912e9e4fef1c1aa07fd97eac329213e9a462d5357d9c42e0308b21e010000006b
<= 9000
=> e04280006f483045022100b0f77410f6cba7dce0c900d898fa10281303df0117c0e9047d17ad40dbf2650602206bf30a5008f4f2f5b9e03a0abfdb71074a98c6c896443f607788d6aa213d28630121036329ca5188070bcf9eba32f007fd1d29c0f7d318c3ea9a1f4eceb954b4aa692bffffffff
<= 9000
=> e04280000102
<= 9000
=> e04280000980841e000000000019
<= 9000
=> e04280001976a9147077a3c486c5c9a7d3ede782f18ca2df7950dca188ac
<= 9000
=> e04280000928e533000000000019
<= 9000
=> e04280001976a914ec39e6ad22cc437b60d1e7d41bc2ed230c93d4b388ac
<= 9000
=> e04280000400000000
<= 3200ec8f8f368d197b4f5e3e13ca572dd8113878461c381c7b9642ca62592d226b89a3da0000000080841e0000000000371746fec9072b749000
=> e0440000050100000001
<= 9000
=> e04480003b01383200ec8f8f368d197b4f5e3e13ca572dd8113878461c381c7b9642ca62592d226b89a3da0000000080841e0000000000371746fec9072b7419
<= 9000
=> e04480001d76a9147077a3c486c5c9a7d3ede782f18ca2df7950dca188acffffffff
<= 9000
=> e04aff0015058000002c80000000800000000000000100000000
<= 6985
=> e046020048223146515a786d536467754e67717176757a6d44475751545a7a55586743466e795a7700000000000f424000000000000003e8058000002c80000000800000000000000100000000
<= 4502583e0f00000000001976a9141aa2e13563eec89e94de4810f01e0041a751864d88ac40420f00000000001976a9149e06d7cc12dd5638435a28f2335f7cd110e8e52688ac030402111d0f291acdb210df38f1c7df52934dbdfcab48bd0548ef6729492b3b759ef03ec4b317512a17caa3fa992575387b60ede0beab5d89a06d78fb91a53e4110651b1eae9000
=> e0440080050100000001
<= 9000
=> e04480003b01383200ec8f8f368d197b4f5e3e13ca572dd8113878461c381c7b9642ca62592d226b89a3da0000000080841e0000000000371746fec9072b7419
<= 9000
=> e04480001d76a9147077a3c486c5c9a7d3ede782f18ca2df7950dca188acffffffff
<= 9000
=> e04aff0015058000002c80000000800000000000000100000000
<= 6985
=> e046020048223146515a786d536467754e67717176757a6d44475751545a7a55586743466e795a7700000000000f424000000000000003e8058000002c80000000800000000000000100000000
<= 4502583e0f00000000001976a9141aa2e13563eec89e94de4810f01e0041a751864d88ac40420f00000000001976a9149e06d7cc12dd5638435a28f2335f7cd110e8e52688ac009000
=> e04800001e058000002c80000000800000000000000000000002030009060000000001
<= 6a80
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_gui/qt/main_window.py", line 1113, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.3.2-py2.7.egg/electrum_plugins/btchipwallet.py", line 341, in sign_transaction
    raise BaseException(tx.error)
BaseException: Exception : Invalid status 6a80

**Comment by btchip** [comment]
OK, the PIN is not correct, but I don't understand why. What did see before ? You should have got 4 pop up windows asking you to confirm a different letter of the address, then enter as the response a single character from the printed card.

**Comment by ziomik** [comment]
I tried to use ledgerwallet with the safety data sheet (that to be sure that my card security is correct) and the transaction is successful.
As you can see electrum asks the corresponding letters on my card security, I insert the correct and show me the error.
![errore-electrum-error](https://cloud.githubusercontent.com/assets/925909/8325223/c82c8f50-1a57-11e5-9dc8-94c3ad632b96.png)

**Comment by btchip** [comment]
Yes ok, I think I see what the issue might be. Will have something to try soon (but in btchip-python this time)

**Comment by btchip** [comment]
Can you try with that patch in btchip-python ? 

```
--- a/btchip/btchip.py
+++ b/btchip/btchip.py
@@ -272,9 +272,11 @@ class btchip:
                if result['confirmationType'] == 0x02:
                        result['keycardData'] = response[1 + response[0] + 1:]
                if result['confirmationType'] == 0x03:
-                       offset = 1 + response[0]
-                       result['keycardData'] = response[offset + 1 : offset + 1 + response[offset]]
+                       offset = 1 + response[0] + 1 
+                       keycardDataLength = response[offset]
                        offset = offset + 1
+                       result['keycardData'] = response[offset : offset + keycardDataLength]
+                       offset = offset + keycardDataLength
                        result['secureScreenData'] = response[offset:]
                result['outputData'] = response[1 : 1 + response[0]]
                return result
```

**Comment by ziomik** [comment]
Very good! All these changes have solved the problem! Congratulations and thank you for the time you have dedicated !!!!!

**Comment by btchip** [comment]
Great. Thanks to you for the tests, and of course ThomasV for the suggestions. I'll close that officially when the updated Python library is available, and this will be fixed in the next release.
