### ISSUE TITLE
global name 'paymentrequest_pb2' is not defined

### ISSUE THREAD

**Issue by gurnec** [spesmilo/electrum#1312]
Reference: <https://bitcointalk.org/index.php?topic=50936.msg11690137#msg11690137>

I'm guessing it's [here](https://github.com/spesmilo/electrum/blob/74bdc7a7fa12de756287cafb9da81d41881f2778/lib/paymentrequest.py#L227):

    import paymentrequest_pb2 as pb2
    [...]
    paymnt = paymentrequest_pb2.Payment()

s/`paymentrequest_pb2`/`pb2`/  ?

**Comment by ecdsa** [comment]
thanks, I overlooked that. it's fixed in 56f8fc62f9964743b13d045438804f26735a3eb5
