### ISSUE TITLE
Option to disable unmatured/unconfirmed/both warning in the bar at the bottom of the screen

### ISSUE THREAD

**Issue by btcspry** [spesmilo/electrum#1313]
I like to be able to see what my current balance is, assuming all transactions are confirmed and matured.

In the options, can you make it so that you can turn off the 'unmatured' thing that says: [+0.xxxxx unmatured], maybe an option to turn off the [+0.xxxxxx unconfirmed]

Love what you guys do!  Thanks.

**Comment by ecdsa** [comment]
you can already see this information in the history
