### ISSUE TITLE
Synchronizer death

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1324]
I woke up to electrum in "Synchronizing" state.  Digging around I find the synchronizer thread died:

[WalletSynchronizer] receiving history 1BcaDmEFivv4tMjX5AxLYstJ1nr6ynbAc4 2
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/neil/src/electrum/lib/synchronizer.py", line 53, in run
    self.run_interface()
  File "/home/neil/src/electrum/lib/synchronizer.py", line 149, in run_interface
    raise Exception("error: server sent history with non-unique txid", result)
Exception: ('error: server sent history with non-unique txid', [{u'tx_hash': u'aebd9c826af0e7463fe30af175318232e98a7860831467f0045825649946bf97', u'height': 362923}, {u'tx_hash': u'aebd9c826af0e7463fe30af175318232e98a7860831467f0045825649946bf97', u'height': 0}])

It looks like it originatinates in a server bug, assuming it's unmodified / not malicious.  I'll work on making the client robust to this.

**Comment by ecdsa** [comment]
I saw that too, I don't think it's malicious.
I think it occurs with tx from mempool (height 0)
it would be better fo fix it server side

**Comment by ecdsa** [comment]
it might be fixed in https://github.com/spesmilo/electrum-server/commit/2296d0221859677deb08bdfafb697f4e69766f28

(see the if statement line 758, the test was only on the hash)
