### ISSUE TITLE
Exceptions on Withdrawal

### ISSUE THREAD

**Issue by Gateway85** [spesmilo/electrum#1328]
Dear all, 
Not sure this is the right forum, but I do receive an error on withdrawal and cannot get my bitcoin out of the electrum wallet right now... 

Might this be something that I am doing wrong or is it a bug? Is there anything I can do about it? 

![screen shot 2015-06-30 at 11 50 06](https://cloud.githubusercontent.com/assets/9881114/8423692/ecd211be-1f1f-11e5-9ff8-7f3f451765da.png)

**Comment by ecdsa** [comment]
when does it occur, precisely?

**Comment by ecdsa** [comment]
oh, the address in the payto field is not even a bitcoin address.

**Comment by Gateway85** [comment]
Oh gosh. Sorry, did just realize now, that this is a testnet address. Sorry. 
Cheers, Miriam

**Comment by ecdsa** [comment]
oh I see...
I did not realize it was testnet, I thought you were using an altcoin fork of electrum.
fixed in c0858f314f16162f39b3034af85d8be59be84e39
