### ISSUE TITLE
unconfirmed transactions

### ISSUE THREAD

**Issue by tou98** [spesmilo/electrum#1329]
Hi All,
Help me pls
I recently take this purse. These transactions are not confirmed few hours. This is normal?

1. _tps://blockchain.info/tx/df6662b29d11980076004d6de6dae3a97c327e1462bc1c64c35122136e599b77
2. _tps://blockchain.info/tx/83f774dd789b2a9d7f441eec19d51b850c62d2866946bc3cdf4e46e4b7074b8a

![electrum](https://cloud.githubusercontent.com/assets/13123866/8439788/4a16d472-1f7f-11e5-8ae6-a03d12beae82.jpg)

**Comment by ecdsa** [comment]
they are now
