### ISSUE TITLE
auto_connect misleading when running daemon

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1336]
If you change the auto_connect setting in the network dialog, the proxy is correctly informed, updates and writes the config, and passes the message onto the daemon (network.py).

However set_parameters in network.py ignores the auto_connect setting and uses the stale value in its in-memory Config object, meaning that if you open the network dialog box again you see the old setting.

It doesn't seem right that both network.py and network_proxy.py should be responsible for writing out the config information so I'm not immediately sure of how best to resolve this.  Perhaps network.py should simply retain an in-memory cache of auto-connect that is loaded from the config in the constructor and updated by set_parameters?

**Comment by ecdsa** [comment]
merged
