### ISSUE TITLE
daemon not working properly because of repr()

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1338]
There are two instances of repr() in daemon.py.  This is causing the daemon history bug we discussed last night.  At least a part of the problem is that some strings are unicode and some aren't.

The repr() usage seems to be a hack in order to get items in a set.  I'm thinking of alternative solutions.

**Comment by ecdsa** [comment]
thanks, but it does not fix the issue for me

**Comment by ecdsa** [comment]
edit: yes it does fix it. :)
