### ISSUE TITLE
Ledger / HW1 not working ?

### ISSUE THREAD

**Issue by ELM4Ever** [spesmilo/electrum#1341]
https://litecointalk.org/index.php?topic=18608.msg274501#msg274501

Traceback (most recent call last):
  File "/Users/xxx/Documents/C7.Github/electrum/gui/qt/util.py", line 37, in run
    self.result = self.run_task()
  File "/Users/xxx/Documents/C7.Github/electrum/gui/qt/main_window.py", line 1145, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/Users/xxx/Documents/C7.Github/electrum/plugins/btchipwallet.py", line 341, in sign_transaction
    raise BaseException(tx.error)
BaseException: finalizeInput() takes exactly 5 arguments (6 given)

**Comment by ecdsa** [comment]
what is your version of btchip-python ?

**Comment by ELM4Ever** [comment]
Was 0.1.14.  

After your post, I have upgraded to 0.1.16.

After upgrading it worked. I was able to send BTC out.

Why not include those dependencies in your build?

**Comment by ecdsa** [comment]
atr you saying that the binaries are built with the wrong version?

**Comment by ELM4Ever** [comment]
OSX v 2.3.2 obviously didn't have the correct version of btchip-python. (electrum.org/#download).

**Comment by ecdsa** [comment]
ok thanks for the info.
notifying @maran about it
