### ISSUE TITLE
Using --wallet together with --portable

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#1349]
I'd like to run Electrum from a sources bundle stored on a USB flash drive. Electrum's block chain data should stay on the USB drive, as should the wallet.

Launching like this:

$ electrum --portable --wallet my_wallet

respects the --wallet option, but not the --portable option. In other words, I end up with my_wallet in my working directory (good), but Electrum drops its block chain data into ~/.electrum (bad).

Using either the --portable or --wallet options works just fine.

It seems that using two command line options should merge the two behaviors, but apparently it does not. Am I missing something?

Running 2.3.3 on Tails 1.4.

**Comment by CodingAnarchy** [comment]
Looks like the problem is [here](https://github.com/spesmilo/electrum/blob/bb4d175978ac39f5e6c89dc827b9d1975d283dae/electrum#L391), if I understand this right:

```python
if config_options.get('portable') and config_options.get('wallet_path') is None:
config_options['electrum_path'] = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'electrum_data')
```

**Comment by rapodaca** [comment]
Yes, I think you've got it.

However, it's not clear at the moment what the intent of the global options is. Is only one option allowed such that, for example, you can never put a portable wallet into verbose mode? Or is the intent to allow global options to be combined?

A test confirms that the latter is the case. It also makes more sense.

**Comment by rapodaca** [comment]
I found [this](https://github.com/spesmilo/electrum/blob/master/lib/simple_config.py#L57), which suggests that wallets using the --portable flag ignore other configuration settings;

    # Portable wallets don't use a system config
    if self.cmdline_options.get('portable', False):
            self.system_config = {}
    else:
        self.system_config = read_system_config_function()

**Comment by CodingAnarchy** [comment]
Right, it doesn't use any system configuration file, which makes sense.  The issue is that it seems to only put the configuration files in the working directory if you don't include a wallet path (what I linked to is where the command line argument parsing is occurring).

I'll look at changing it when I get home, and then let someone determine whether to merge it in.

**Comment by ecdsa** [comment]
thanks
