### ISSUE TITLE
Unable to send transaction from Trezor with 2.3.3

### ISSUE THREAD

**Issue by Dehumanizer77** [spesmilo/electrum#1353]
Recently I have upgraded from Electrum 2.0 which worked fine to 2.3.3 and since then, I am unable to send transactions. When I submit a transaction, it asks for a confirmation and then the error message pops up, saying `Got <class 'trezorlib.messages_pb2.PublicKey'>, expected (<class 'trezorlib.messages_pb2.Success'>,)`
The old 2.0 version still works fine though.

**Comment by prusnak** [comment]
It seems that a call using GetPublicKey message is issued, which was not a case in 2.0 release.

**Comment by nomnombtc** [comment]
Hey, I had a problem like that earlier, it seems there was a small change in wallet format
somewhere between releases (nextaccount is called nextaccount2 now)
For me creating a new wallet fixed the problem, you may want to try that. (same trezor just recreated the electrum wallet)

**Comment by Dehumanizer77** [comment]
I confirm that recreating the wallet fixes the problem. Not sure if there is anything else that can be done to fix the problem without recreating the wallet, if not, you can close the issue.
