### ISSUE TITLE
Electrum will not connect from ANY pc in the house

### ISSUE THREAD

**Issue by bojanbulut** [spesmilo/electrum#1354]
Hello everyone, my wallet was working fine for a while and now has all of a sudden it REFUSES to connect 
What i have tried :
Reinstalling
Reinstalling older versions (standalone aswell) 
Tried the same wallet on my other laptop ( I am not running VPN or tor/tails)
Opened and closed the program many times 
deleted the blockchain 
I sent $ to this wallet last night and all the transactions have MANY confirmations .. what the hell is going on..If someone could help me id be extremely thankful.
Thanks in advance !

**Comment by shsmith** [comment]
your server list may be out of date. find a working server here: http://electrum.qc.to/ and manually connect to it. once you get a server connection, it will refresh your servers list and you can go back to automatic.

**Comment by rapodaca** [comment]
I'm noticing the same problem. I get the "synchronizing" message and the blue circular arrows icon, but Electrum never finishes synchronizing.

After creating a new wallet, sync completed as expected. However, trying to sync old wallets with existing transactions failed. Tried connecting to multiple servers manually that are reported to be working on  http://electrum.qc.to/

**Comment by lathan** [comment]
Hi @bojanbulut this is probably not the right place to ask for help, but I'm not sure where the right place is so...

1. First of all, please elaborate on what "refuses to connect" mean.
2. Lets focus troubleshooting on one computer. What OS are you using on this computer?
3. Try to get a backup of your wallet at this point, if you know how to. Otherwise, we'll do that a bit later.
4. How do you normally start electrum?
5. Can you open a terminal and start electrum with `electrum -v`? Wait a while, until it stops printing output. Then copy paste all the output here so we can see.

**Comment by EagleTM** [comment]
Which OS are you using? Maybe this is related to https://github.com/spesmilo/electrum/pull/1381 ?

**Comment by ecdsa** [comment]
@OP can you disable SSL in the network dialog, and see if it works better?

**Comment by bojanbulut** [comment]
Windows 7, It works on linux, I'm not on tor

**Comment by ecdsa** [comment]
@bojanbulut can you disable SSL in the network dialog, and see if it works better?

**Comment by EagleTM** [comment]
Looks similar to #1491

Does it still happen with 2.5.1 ? Are you using the portable version? If so please try the standalone version

**Comment by gits7r** [comment]
@bojanbulut I had the same problem, #1491 and Electrum 2.5.1 fixed it for me. Please download 2.5.1 make the tests again and confirm if it works good for you. I am using the portable version of 2.5.1 and the bug is fixed.

**Comment by EagleTM** [comment]
I'm closing this for now, because OP hasn't come back since beginning of August to comment, so I'm assuming it works
