### ISSUE TITLE
probleme sending btc with electrum

### ISSUE THREAD

**Issue by krzysiu63** [spesmilo/electrum#1355]
hi Can somebody can help me i send bitcoin to my account but it still in pending and i receve nothing and i the second time i cant send it still in pending transaction and no go further

**Comment by abitfan** [comment]
There is a backlog of transactions right now which might cause your transaction to be delayed. A fix to this is to use a bigger fee than that default.

**Comment by krzysiu63** [comment]
thx i go to the préférence  and put a higher value from 0.0005to  0.0015 will see if its work

**Comment by krzysiu63** [comment]
i dont think it change somthing when i do the upper action that you told me

**Comment by abitfan** [comment]
Do you have a tx id ?

**Comment by krzysiu63** [comment]
?sory i m not a native english ?i dont know what us that

**Comment by krzysiu63** [comment]
you mean transaction id?

**Comment by abitfan** [comment]
sorry, yes, transaction id

**Comment by krzysiu63** [comment]
a41965fe41fd7fbdfbdfec67caa389d35ae179d148e00cfd5670e473541269b3
2698f54b9b082da662e63b8e8553e016c1073dac7192edafdb616aee117c5555
4d2be6cc746eb81d96cd3b284bf966bd938a37546f912a7f0f4bbda132eed7e6

**Comment by abitfan** [comment]
The fees are on the low side and it will take a while to process if ever. 
Theres nothing you can do at this point, just way for them to get into the block or cancelled.

**Comment by krzysiu63** [comment]
ok thx will wait

**Comment by krzysiu63** [comment]
hi when i go see the block chain it rite 
Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned rom our database.
i dont understand can you explain me because no money appear anywhere

**Comment by ecdsa** [comment]
these tranasctions are confirmed.
please close the issue you open once they are resolved
