### ISSUE TITLE
Importing the second signature in to an Android wallet

### ISSUE THREAD

**Issue by HostFat** [spesmilo/electrum#1359]
Is there an Android wallet where it is possible to import the second signature of a 2 of 2 or 2 of 3 electrum wallet?

So it will work as a 2FA, and maybe the third signature can be saved as backup.

**Comment by ecdsa** [comment]
electrum for android has a "authenticator.py" application, for cosigning

**Comment by HostFat** [comment]
Cool!

Anyway, I tried and I did get an error.

I followed the instructions from here:
https://electrum.org/#android

I've a Nexus 4 with Android 5.0.1 rooted.

I've entered the password two times as requested, and then the seed.

Traceback (most recent call last):  File "/storage/emulated/0/sl4a/scripts/e4a-2.3/e4a-2.3/authenticator.py", line 356, in <module>
    a = Authenticator()
  File "/storage/emulated/0/sl4a/scripts/e4a-2.3/e4a-2.3/authenticator.py", line 201, in __init__
    wallet = Wallet.from_seed(seed, storage)
TypeError: from_seed() takes exactly 4 arguments (3 given)

And then the script stopped.

**Comment by HostFat** [comment]
Do you need other informations/tests? Is there a way to give you more help to fix this?

**Comment by ecdsa** [comment]
sorry for that bug, I just fixed it.
even with that bug, it should work if you create the seed on the android wallet, instead of importing it

**Comment by HostFat** [comment]
Good, but as you see I had a problem even by running "e4a.py", so I couldn't create the seed.
Anyway, I hope that even it will be fixed on the 2.4.

I'll test it an report ;)

**Comment by ecdsa** [comment]
you don't need to run e4a.py
you create a seed with authenticator

**Comment by HostFat** [comment]
Ah ok, thank you again.

**Comment by ecdsa** [comment]
btw, what problem do you have to run e4a.py?

**Comment by HostFat** [comment]
I start "e4a.py", and select "create seed", then the scrip stops:

electrum directory /sdcard/electrum/Error: Cannot read config file.
[Network] starting network
[Blockchain] 327658 blocks
wallet path /sdcard/electrum/wallets/default_wallet
gui callback False
[NetworkProxy] stopped
[Network] stopping network
[kirsche.emzy.de] disconnecting
[WEST.electrum.jdubya.info] disconnecting
[ecdsa.net] disconnecting
[electrum.be] disconnecting
[electrum.no-ip.org] disconnecting
[electrum2.hachre.de] disconnecting
[eco-electrum.ddns.net] disconnecting
[EAST.electrum.jdubya.info] disconnecting
[Network] stopped
[Blockchain] stopped
Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/shimoda/python-for-android.git/python-build/python_arm/python-ext/python/threading.py", line 810, in __bootstrap_i
nner
  File "/storage/emulated/0/sl4a/scripts/e4a-2.3/e4a-2.3/lib/interface.py", line 312, in run
  File "/storage/emulated/0/sl4a/scripts/e4a-2.3/e4a-2.3/lib/interface.py", line 170, in get_socket
  File "/storage/emulated/0/sl4a/scripts/e4a-2.3/e4a-2.3/lib/interface.py", line 154, in get_simple_socket
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'socket'

**Comment by HostFat** [comment]
I've tried a second time, but I've waited longer before clicking on "create seed", and this time it worked.
