### ISSUE TITLE
Wrong BTC input in simple mode

### ISSUE THREAD

**Issue by gabesbit** [spesmilo/electrum#1360]
Wrong BTC input in simple mode. Latest 2.3.3 tested on Ubuntu 14.04.
In advanced mode, the input amount is OK.
http://imgur.com/kppBaYp

**Comment by ecdsa** [comment]
can you explain in what sense it is "wrong" ?

**Comment by gabesbit** [comment]
After clicking on website link, Electrum inputs wrong decimal places and zeros.
In the input field there should be 0.001878 not 187800.000000
This way the BTC can not be sent. As I wrote in advanced mode it works OK.

**Comment by ecdsa** [comment]
fixed
