### ISSUE TITLE
Adding support for jbok p2sh addresses

### ISSUE THREAD

**Issue by thedoctor** [spesmilo/electrum#1362]
Hey guys,

I had a customer who wanted to import some addresses from Gem's multisig wallets into electrum for an offline emergency backup, but our trees don't quite follow BIP32 and are subject to change, plus some inconsistent hardening behavior specific to our implementation made it seem like the path to least resistance was deriving pub/priv keys manually and generating a wallet file for electrum to use them, so I hacked the behavior I wanted into the Imported_Wallet and ImportedAccount classes.

My questions are:

1. Is this useful to anyone? Should I refine this and PR?
2. If so, do you like the Imported_Wallet containing both p2sh and p2pkh addresses or should it be its own Wallet type?
3. Does this make more sense as a plugin or part electrum core?

barely-tested-but-seemingly-functional-at-least-from-the-CLI branch with changes here: https://github.com/GemHQ/electrum/tree/jbok_multisig

**Comment by ecdsa** [comment]
we cannot spend time and energy supporting and maintaining arbitrary wallet types. 
ask your customer to move your funds.

**Comment by thedoctor** [comment]
I think you misunderstood my questions. My branch just aspires to decouple BIP32 HD wallets from P2SH functionality and has the side effect of allowing advanced users to import one-off groups of m-of-n p2sh keypairs and I just wanted to know if anyone else would find that useful enough that I should refactor to handle more edge cases and GUI support.

The customer I was referencing doesn't need to move anything, I'm not sure what you thought I was saying his problem was.

Anyway, if I continue, I'll probably build it as a plugin since it doesn't seem like you're looking for contributions to core.
