### ISSUE TITLE
Feature request - Validate Trezor seed on the fly when entered by the user

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1366]
(Tested on Mac OS X 10.10.4)

When a user mistypes a word (i.e. "value" instead of "valve") the Electrum recovery feature does not validate if the Trezor seed is valid or not before processing it. An interesting feature would be to verify on the fly that the seed is valid before letting the user click on the "Next" button.

You can reproduce the bug on OS X with Electrum 2.3.3 and using the following INvalid Trezor seed:

> garlic mirror enable gospel artefact pride zone orange demise update lumber embody illegal bus inspire use yard value creek smart sort dutch chicken bottom

**Comment by ecdsa** [comment]
already in #1116
