### ISSUE TITLE
Feature request - Allow users to remove (or edit) servers from the server list

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1367]
Users should be allowed to manage their own server list.

While unchecking the "automatic" checkbox allows users to choose one specific host it doesn't let users to specify more than one. The following lists should be available to the users from the GUI: whitelist, blacklist.

Letting users choose their own trusted servers will give them more security flexibility. Blacklisting servers would allow users to avoid communicating with compromised or insecure nodes (or even nodes that use an old version of Bitcoin and are on the wrong side of the forked Bitcoin chain for example).

It is to be noted that the default servers can be edited via:

> ./lib/network.py

A GUI interface for editing this server list would be more user-friendly.

An option to prevent the application from discovering new servers would be a huge plus in terms of confidentiality.

**Comment by ecdsa** [comment]
IMO this is beyond scope for the GUI.
could be added as a command line option

**Comment by Thireus** [comment]
For those who want to remove this list after compiling/downloading the sources, here's a patch:

## Privacy DEFAULT_SERVERS

Remove all (untrusted) DEFAULT_SERVERS:
```
#!/bin/sh

echo "[...] Patching: DEFAULT_SERVERS"

sed -i.bak -n -e '/DEFAULT_SERVERS/{' -e 'p' -e ':a' -e 'N' -e '/}$/!ba' -e 's/.*\n//' -e '}' -e 'p' dist/Electrum.app/Contents/Resources/lib/python2.7/lib/network.py &&\
rm -f dist/Electrum.app/Contents/Resources/lib/python2.7/lib/network.py.bak &&\
echo "[OK] Patch applied successfully"
```

**Comment by bauerj** [comment]
I think this would add too much complexity to the GUI. 

You can already force Electrum to use a single trusted server with command line arguments (`--oneserver -s server:port`) so there is no need to patch the default server list.
