### ISSUE TITLE
Headers downloaded on insecure channel via http://headers.electrum.org at first launch

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1368]
When the application is launched for the first time it downloads the blockchain_headers file using an insecure communication layer (HTTP):

```
IN ./lib/blockchain.py:        self.headers_url = 'http://headers.electrum.org/blockchain_headers'
```

The server hosted at headers.electrum.org supports HTTPS but for some obscure reasons these headers are downloaded using a secure channel. More than that, there is no option that prevents this automatic download, which seems to occur when the blockchain_headers file is missing (first launch for example) or broken.

The blockchain_headers file can also be downloaded in full whenever the Electrum client is connected to a node from that node.

While there might be a performance (or stats collection) reason behind this, I strongly encourage users from editing this line and blanking the host:

```
IN ./lib/blockchain.py:        self.headers_url = ''
```

Users should be allowed to choose their own host (or none) from where they wish to download the header_file. An option in the configuration file is highly suggested.

**Comment by ecdsa** [comment]
fixed

**Comment by Thireus** [comment]
There should be an option to disable this as well.
