### ISSUE TITLE
Feature request - Implement a keyboard shortcut to freeze input addresses

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1369]
The coin control system is good, but would be much better and easier to use with a keyboard shortcut to select which addresses are used as inputs to a transaction.

Instead of right clicking the addresses + Freeze/Unfreeze we could for example use a keyboard shortcut combination such as CTRL + B, which also is quite natural since blocked addresses are highlighted (CTRL + B = Bold).

**Comment by ecdsa** [comment]
are you aware of the "send from" feature? it can be used with mny addresses

**Comment by Thireus** [comment]
Yes, I've seen that option but it is only available when there is more than one imported key, am I correct? Because the "Send From" field does not appear when a single wallet is created. Is there a specific reason for that? Or am I missing something?

**Comment by ecdsa** [comment]
it's available when there are coins to send
