### ISSUE TITLE
not spending full balance

### ISSUE THREAD

**Issue by forest22** [spesmilo/electrum#1370]
I have read somewhere that it is required that a bitcoin transaction fully spends the balance of its inputs. Electrum does not adhere to that. If there is an address that has received coins in two transactions (e.g. +4 and +8), then when sending an amount (e.g. -1) in Electrum, it will empty only the balance due to the first transaction, like this: (-4, +1 +3). I would expect (-12, +1 +11). Is this expected correct behavior or a bug? Tested with 1.9.5. Found no remark about this in the 2.3.3 change log.

**Comment by ecdsa** [comment]
please learn about how bitcoin works
