### ISSUE TITLE
Multisig with Trezor

### ISSUE THREAD

**Issue by ELM4Ever** [spesmilo/electrum#1383]
Version 2.4 release notes indicates that multisig wallets can be created with Trezor being one of the co-signer.  

I attempted to create two new multisig wallets, one normally, with a new seed and the xpub from a  Trezor.   The other one with the newly generated xpub of the other co-signer, and the xpub of the Trezor.  The resulting second wallet becomes "watch-only".  If a transaction is first signed by the non-Trezor co-signer wallet, and then the partially signed tx is imported in the Trezor multisig wallet, no options are given to sign the tx with the Trezor.   

What I am doing wrong?

**Comment by ecdsa** [comment]
you need to import the partially signed tx in your non-multisig Trezor wallet

**Comment by ELM4Ever** [comment]
It worked - thanks!  

If I understand correctly,  Trezor will never be able to initiate the first signature, it will always have to sign the transaction last?

**Comment by ecdsa** [comment]
no, you can sign in any order

**Comment by ELM4Ever** [comment]
I am sorry - didn't write the question correctly.  Once the tx is written, Trezor could sign it first, I agree.  But, using Electrum, how one could create a transaction with the multisig Trezor wallet if it is only a watch-only wallet.  The transaction would have to be created with the non-multisig Trezor wallet first - correct?

**Comment by ecdsa** [comment]
the tx has to be created by a multisig wallet, not by the trezor wallet, because (for the moment) trezor wallets are not multisig.

**Comment by ELM4Ever** [comment]
Which lead to my first comment that Trezor (for the moment) has to sign last - not because it can't sign first, but because Electrum doesn't currently allow a Trezor wallet to create the multisig transaction.

**Comment by ecdsa** [comment]
no that's wrong. 
you can create it without signing it at all, then trezor signs first.

**Comment by mariodian** [comment]
How do you sign a tx with Trezor? I have created a multisig wallet (2 of 2) in my Electrum 2.4.2 (OSX Yosemite), copy pasted my trezor xpub and everything went smooth. I sent bitcoins to my newly created 2 of 2 wallet, created a transaction which is partially signed (1/2) but that's all. I don't know how to finish signing it on trezor. Am I missing something?

**Comment by dabura667** [comment]
@mariodian 
1. Create a Single sig Trezor wallet via Create New > Hardware > Trezor
2. When in the Trezor wallet, load the partially signed transaction you created on your multisig account.
3. You can still sign it and broadcast it fine.

2 drawbacks:
1. You can't view the multisig balance from the Trezor wallet, as it is single sig.
2. You can't use the transaction relay plugin.

**Comment by mariodian** [comment]
Thank you. I followed this step and when I load partially signed transaction I get "transaction unrelated to your wallet" message.

I can hit the "sign" button but the window saying "Signing transaction..." stays there forever.

**Comment by ELM4Ever** [comment]
Do you have multiple accounts in your Trezor wallet?  If so, which Trezor XPUB did you use to create the multisig wallet?

**Comment by mariodian** [comment]
I don't have multiple accounts on my Trezor, but I do have "hidden wallets" on it. However I created the multisig wallet with the XPUB from the first Trezor wallet (the one that is accessible without a passphrase).

**Comment by Christewart** [comment]
@ELM4Ever I have multiple accounts on my trezor wallet with the same problem @mariodian. How can you specify which account to look under?

**Comment by ELM4Ever** [comment]
Did you tried the latest Master branch?  I believe the problem was fixed a few weeks ago.

**Comment by Christewart** [comment]
I failed to realize that you must have xpub's to do this. Right now I have two normal public keys and one xpub off of the Trezor. From what i've read since then it seems impossible to create the transaction on Electrum. It also seems impossible to take a raw transaction created in another application and it sent to the Trezor for signing with Electrum

**Comment by ELM4Ever** [comment]
@Christewart - Assuming a 2 of 2 multisig wallet, if you create an Electrum multisig wallet with the XPUB of a Trezor as the second co-signer.  Once you funded one of the multisig address, you can create the transaction in the newly created multisig wallet - click "Save"  (or Sign and Save) - then open your Trezor hardware wallet in Electrum.  From the Trezor electrum wallet - Tools --> Load Transaction --> From File --> click Sign --> then Broadcast (if you signed it first with the standard wallet) or Save to get it signed by the other wallet.   It should be similar with a 2 of 3 wallet, or 3 of 3 wallet.

**Comment by mariodian** [comment]
I have the latest 2.4.4 and did the following:

1) created a transaction on 2 of 3 wallet sending bitcoins to a non-multisig address
2) partially signed it with the same 2 of 3 wallet
3) plugged my trezor
4) changed the wallet in Electrum and typed the trezor PIN
5) loaded transaction from the file
6) clicked sign

and **nothing** happens. The "sign" button stays grayed out forever. Please see the attached images.

I even tried to sign with trezor wallet with a passphrase, I got the "transaction is unrelated to the wallet" message and also nothing happened.

![multisig-1](https://cloud.githubusercontent.com/assets/3636406/9782523/583e8e76-57d0-11e5-93b6-7b5403130aa3.png)
![multisig-2](https://cloud.githubusercontent.com/assets/3636406/9782524/58820976-57d0-11e5-94db-f8e70ee7ffb7.png)
![multisig-3](https://cloud.githubusercontent.com/assets/3636406/9782525/588362da-57d0-11e5-96e0-fb444032ea30.png)
![multisig-4](https://cloud.githubusercontent.com/assets/3636406/9782526/5884f47e-57d0-11e5-9292-c9a43cf6acdc.png)

**Comment by ELM4Ever** [comment]
@mariodian:  2.4.4 is not enough.  Please github to the Master branch and download the latest version. The latest version works. 

You also have to do (if on Linux or OSX): sudo python setup.py install, within the Electrum directory.

**Comment by mariodian** [comment]
"python electrum" is getting stuck at [this error](http://pastebin.com/8wA6fYhb).

I have pyqt installed via brew installer on OSX. I think I will just wait for the release.

**Comment by Christewart** [comment]
@ELM4Ever What you told me before ONLY applies if I have THREE xpubs, not just ONE xpub and TWO public keys, correct?

**Comment by ELM4Ever** [comment]
@Christewart If you have the private keys to the two "public keys" that you have set the multisig wallet, plus the XPUB of the Trezor, you should be able to create a raw transaction from the either one of the non-trezor wallet.  Like I mentioned, the Trezor Electrum wallet can't create the raw transaction - but it can sign it.    You have to create the transaction with one of the other co-signer.

**Comment by ELM4Ever** [comment]
@mariodian Did you "brew install qt pyqt gettext"  ?

**Comment by mariodian** [comment]
@ELM4Ever yes, I have those installed already.

```
$ brew install qt pyqt gettext
Warning: qt-4.8.6 already installed
Warning: pyqt-4.11.1 already installed
Warning: gettext-0.19.3 already installed
```
