### ISSUE TITLE
REQ: CoinTape fee estimation plugin

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum#1384]
CoinTape provides an estimation of 'the best' fee API:

http://www.cointape.com/api

Electrum could have a plugin to utilise this information.

**Comment by ecdsa** [comment]
is that better than bitcoind's estimatefee? if yes, why?

**Comment by ecdsa** [comment]
the estimate returned by that website is not suited for wallets; it returns an instantaneous estimate of the min fee to be included in the next block, based on the current memorypool. as a result, it drops everytime a new block is found, and increases slowly from then.
what we need is an estimate that does not depend on the instant situation of the mempool.

**Comment by ecdsa** [comment]
note: 2.4.1 will have dynamic fees
