### ISSUE TITLE
Feature request: Deeply offline transaction signing

### ISSUE THREAD

**Issue by DaveCTurner** [spesmilo/electrum#1386]
In a fit of paranoia, I would like to be able to sign transactions on a completely disconnected machine using only a keyboard to transfer data to/from the connected machine, to dramatically reduce the possibility of a covert channel being used to extract a private key.

In more detail, I would like to use something like [BitKey](http://bitkey.io/) but believe that

- mucking around with USB drives is potentially risky
- pointing a digital camera at an air-gapped computer to read a QR code rather defeats the purpose of the air gap, and
- QR codes are opaque and contain enough error-correcting redundancy to hide all sorts of juicy data.

To make this slightly more feasible than it first appears, note that:

- the full unsigned transaction does not need to be transferred to the disconnected machine - it is sufficient to send its SHA-256 hash as this is all that is signed.

- the full signed transaction does not need to be transferred back to the connected machine - it is sufficient to send the public key and the two signature values `r` and `s`.

In experiments it has proved tricky to correctly transfer binary data by copying hex strings from one screen to another, but a word-list encoding has proven effective. For security, I believe it is important that the word-list encoding can be checked by hand. A length-256 word list seems too short, and 65536 seems too long. For some reason 2048 is popular (see BIP-0039 and RFC 1730) but this is hard to check by hand as the padding rules are quite complicated, and there is a risk that some data could be hidden in the padding if it is not checked. I think that an encoding that maps nicely onto Base 64 would work well in terms of transparency: 4096 'main' words which map onto pairs of Base 64 characters, plus a separate list of 16 'odd' words for the 16 single characters that might be left over at the end.

In a list I have been experimenting with, the first 256 main words come strictly before the word 'AT', all 4096 main words come before the letter 'Y', and the remaining 16 'odd' words begin with Y or Z. This means that it is easy to check valid padding by eye: all but the last word must begin with a letter from 'A' to 'X', and

- if there are an even number of words then the last word may be anything, and
- if there are an odd number of words then the last word must be strictly before the word 'AT'.

Unfortunately this list is encumbered by copyright so I would have to generate a new list with similarly pleasant properties.

Given such a word list, the proposed workflow is:

- generate an unsigned transaction in the 'connected' Electrum. Calculate the SHA-256 hash for signing, and convert it to a sequence of 22 words as described above.

- copy the words into the 'disconnected' Electrum, pick the appropriate key and sign the hash with it. Convert the signature into three sequences of words:

  - `r` and `s`, each 14 words long, and
  - the public key itself, which is either 22 or 44 words long depending on whether it's compressed or not.

- check that these sequences are the right length and have nothing hidden in their padding (by eye, as described above)

- copy these word sequences back into the 'connected' Electrum, which inserts them into the transaction, checks it is now valid, and sends it out.

If the resulting transaction is valid then there's almost no way that this can leak information.

Does this seem like a reasonable feature to add?

**Comment by ecdsa** [comment]
This is clearly out of scope for Electrum lib/gui. 
maybe as a plugin

**Comment by DaveCTurner** [comment]
A plugin seems a sensible idea, sure.

**Comment by ecdsa** [comment]
closing this
