### ISSUE TITLE
When displaying large numbers they become hard to distringuish

### ISSUE THREAD

**Issue by stefment** [spesmilo/electrum#1388]
For example i have my balance in Bits. I know. Shoot  me...

But the option comes with electrum as default, and when doing so the numbers become large and hard to distinguish. For example 2109495.00 is not easy to read. I suggest adding , like normal. So the number will become 2,109,495.00  It makes it easier to read.

**Comment by ecdsa** [comment]
electrum uses the locale setting of your computer. what is your OS?

**Comment by stefment** [comment]
Thats interesting. Im on Win7.

**Comment by ecdsa** [comment]
well, I don't know if that option works on windows. maybe we should set it in the preferences

**Comment by kyuupichan** [comment]
ecdsa - perhaps we forget doing it by locale, which seems to have brought several issues, and just force commas and decimal points all the time (i.e. US/UK-style)?

**Comment by stefment** [comment]
Any updates on this?

**Comment by shawnpringle** [comment]
Perhaps the user' s computer is using the C locale.  That would explain why it does that.

**Comment by bauerj** [comment]
After a quick test, the amount was correctly formatted here. If you still experience this issue, please reopen.
