### ISSUE TITLE
Feature Request: Sort/Filter Addresses

### ISSUE THREAD

**Issue by AdvancedStyle** [spesmilo/electrum#140]
I would be nice if addresses in the "Receive" tab could:

1) Be sorted (by address, balance, transactions etc..) but clicking on the column header

2) Be filtered (have a search box where you start typing the address and lists gets filtered)

**Comment by ecdsa** [comment]
2) addresses can be filtered by label now, using the search box.

**Comment by ecdsa** [comment]
1) done in d94aee83b99ffe405a4875ccb215ab6c774c12e2
