### ISSUE TITLE
UI: Blank message due "not enough founds" in multiple "Send from"

### ISSUE THREAD

**Issue by petrkr** [spesmilo/electrum#1401]
There is in ui some blank message which has information icon but text.

Steps to reproduce:
1) Go to addresses
2) select two (or more) of them
3) Do right click and select "Send From"
4) put some amount which is higher than balance
5) Send

I realized two situactions, 1st will appear blank message imidiately, in other there is windows with question "send xxxx mBTC to <address> ?" if you will say "YES" also blank message will appear.

![image](https://cloud.githubusercontent.com/assets/6428351/9292533/e900022a-4400-11e5-8c9e-7654dee9c0e9.png)

**Comment by petrkr** [comment]
In verbose mode, in console is exception
```
using 1 inputs
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/main_window.py", line 1198, in do_send
    tx = self.wallet.make_unsigned_transaction(coins, outputs, fee)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 910, in make_unsigned_transaction
    raise NotEnoughFunds()
NotEnoughFunds
```

**Comment by ecdsa** [comment]
this is unrelated to the "send from" feature. it also occurs on normal send
