### ISSUE TITLE
hw1 and unicode

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1403]
after upgrading to any revision past  98930575546d9a18df646e72198deb22a750992a  (unicode conversion)  I can no longer sign transactions with the HW1.
When I click the sign button, I get the following :

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 43, in run
    self.result = self.run_task()
  File "/home/richi/sourcecode/electrum/gui/qt/main_window.py", line 1292, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 397, in sign_transaction
    self.get_client() # prompt for the PIN before displaying the dialog if necessary
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 231, in get_client
    raise Exception("Could not connect to your Ledger wallet. Please verify access permissions, PIN, or unplug the dongle and plug it again")
Exception: Could not connect to your Ledger wallet. Please verify access permissions, PIN, or unplug the dongle and plug it again 

Looks like some string needs to be converted back to ascii before sending it to the ledger hardware wallet...

**Comment by ecdsa** [comment]
I really don't see the link between  98930575546d9a18df646e72198deb22a750992a and your issue..

**Comment by ulrichard** [comment]
Yes, when I checked out all the revisions one by one, it was the one that I expected the least.

**Comment by ecdsa** [comment]
let me know if that fixed it

**Comment by ulrichard** [comment]
No it still looks the same with  2ffd419e66ac4d2cedae1dd5e91d11203101f4ec

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 43, in run
    self.result = self.run_task()
  File "/home/richi/sourcecode/electrum/gui/qt/main_window.py", line 1291, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 397, in sign_transaction
    self.get_client() # prompt for the PIN before displaying the dialog if necessary
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 231, in get_client
    raise Exception("Could not connect to your Ledger wallet. Please verify access permissions, PIN, or unplug the dongle and plug it again")

**Comment by ecdsa** [comment]
are you sure about revision  98930575546d9a18df646e72198deb22a750992a causing this?
(sorry I dont have a working hw1 at the moment)

**Comment by ecdsa** [comment]
@btchip can you have a look please?

**Comment by ulrichard** [comment]
Yes, I just verified again. 
It works with 6232a0b76cc041126af62b628394020115cbace0
But doesn't work with 98930575546d9a18df646e72198deb22a750992a  onward.
I know it looks strange and unconnected.

**Comment by btchip** [comment]
Can you try to report the parent exception ? Also make sure that you get the latest python API from https://github.com/ledgerhq/btchip-python

I'll have a look when I get a chance but it'll probably be fine for me as it was working during my tests.

**Comment by ulrichard** [comment]
I have the python API from https://launchpad.net/~richi-paraeasy/+archive/ubuntu/bitcoin/+sourcepub/5175183/+listing-archive-extra  which has worked nicely since end of June.
The HW1 doesn't have the newest firmware. Could that be an issue?

I'll try to debug it for the parent exception in the evening.

**Comment by btchip** [comment]
No, the firmware will not be an issue for this. The Python library version should be fine.

**Comment by btchip** [comment]
That should help

**Comment by ulrichard** [comment]
Yes that fixes the problem.
Thanks a lot!

**Comment by btchip** [comment]
new commit fixes it
