### ISSUE TITLE
v2.4.2 - plugin option "cosigner pool" does not "stick"

### ISSUE THREAD

**Issue by CyberLizard** [spesmilo/electrum#1406]
IN version 2.4.2 the option to enable the multi-sig cosigner pool plugin does not stick when enabled and is thus broken / not available for multi-sig transactions. Need to export the tx and send it to the cosigner(s).

**Comment by ecdsa** [comment]
what do you mean by "does not stick" ?

**Comment by ecdsa** [comment]
this plugin works fine for me. please explain the issue.

**Comment by CyberLizard** [comment]
@ecdsa with doesn't stick I mean that when you tick the option in the plugin settings and close the settings and you open plugins again then it's un-ticked again. I have this issue in the current version and I'm not alone, my cosigners have the same issue so we need to export the raw txn and share it with the cosigner.

**Comment by CyberLizard** [comment]
To visualize... 

Selecting cosigner plugin... http://prntscr.com/87mwc2 and close the menu, open it again and http://prntscr.com/87mzeu

**Comment by ecdsa** [comment]
I see.. the binaries are missing xmlrpclib

**Comment by ecdsa** [comment]
fixed. download the 2.4.4 binaries
