### ISSUE TITLE
v2.4.2 History column headings wrong when Exchange Rates Plugin + History Rates is on

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#1408]
When the Exchange Rates plugin is enabled and History Rates are turned on, the History tab sometimes shows the wrong column headings.  
For example, it is currently showing "Description" over the date column, "Amount" over the description, Balance over the amount column. The actual balance column is missing. Only the last column "Fiat Amount" is correct.

![image](https://cloud.githubusercontent.com/assets/859149/9373739/be1bfb46-46a2-11e5-9763-fdf8e4b29b61.png)

Turning off "History Rates" in the Exchange Rates plugin clears it up.
This is happening in both Windows and OS X

**Comment by ecdsa** [comment]
fixed in 486d181
