### ISSUE TITLE
Please Add Chinese to the wordlist

### ISSUE THREAD

**Issue by BED822** [spesmilo/electrum#1409]
http://lcprichi.hkbu.edu.hk/table_search.html contains chinese character in order of character frequency. (click 常用度 from the top left corner, second bar)

**Comment by ecdsa** [comment]
can you write a pull request?

**Comment by dabura667** [comment]
BIP39 already has chinese wordlists.

Can be used easily FYI

**Comment by ecdsa** [comment]
ok

**Comment by ecdsa** [comment]
@dabura667 it would be better if you could write a pull request, because I do not know chinese

**Comment by dabura667** [comment]
Note to self:

1. Copy simplified wordlist from BIP39 repo
2. Add language code zh to point to text file in mnemonic.py
3. Add ability to discern simplified and traditional??? (Would require larger change to mnemonic.py)

I think simplified only is ok, @BED822 what do you think?

**Comment by BED822** [comment]
Please use traditional Chinese,  because I ain't no stinking communist.

**Comment by dabura667** [comment]
Just lost all will to do this.

**Comment by BED822** [comment]
Traditional Chinese only is good enough

**Comment by dabura667** [comment]
#1411 adds simplified Chinese wordlist. This will be shown when the user sets their language to Simplified Chinese and generates a new phrase.

Currently Electrum does not support traditional Chinese in the UI, and until then it can not support traditional Chinese in the mnemonic.

**Comment by dabura667** [comment]
# 飘 编 距 念 夜 酒 腾 男 畜 改 项 乌 一

Here's a nice wallet phrase :-)

**Comment by dabura667** [comment]
(Please keep in mind that Electrum wallets remove all spaces for Chinese, Japanese, and Korean wordlists... (no Korean wordlist yet) so you don't need to enter spaces at all, actually. This is different from BIP39 which requires spaces.)

**Comment by ecdsa** [comment]
beautiful, thanks :)
