### ISSUE TITLE
OS X Fails to understand any python get_ca_path functions

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1412]
I'm facing a new issue with a ca_path directories on OS X. It seems like the function that gets the OS ca_path is not defined:

	Aug 20 09:54:49 dev.local Electrum[497]:   File "./Electrum.app/Contents/Resources/lib/python2.7/packages/requests/utils.py", line 38, in <module>
	Aug 20 09:54:49 dev.local Electrum[497]:     DEFAULT_CA_BUNDLE_PATH = get_os_ca_bundle_path()
	Aug 20 09:54:49 dev.local Electrum[497]: NameError: name 'get_os_ca_bundle_path' is not defined

OS X doesn't have any bundled ca file, CAs are stored in the keychain.

Unfortunately, I had to set it to set the value to "None":

	DEFAULT_CA_BUNDLE_PATH = None

Users could eventually use their own custom path.

It might be best to do something like this: https://github.com/pypa/pip/pull/1866/files

**Comment by ecdsa** [comment]
I don't know where you grabbed 'requests' from, but you don't seem to have the correct version

**Comment by Thireus** [comment]
pip list returns (on OSX):
requests (2.7.0)

**Comment by ecdsa** [comment]
well, I would say that's not electrum issue...

**Comment by Thireus** [comment]
You're right, I'll try to find a way around that issue.

**Comment by ecdsa** [comment]
ok, see my other comment with the osx bug
