### ISSUE TITLE
Dynamic banner - Is there any way to fetch it again from the console?

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1413]
So, I have a server that runs Electrum-server and I have a dynamic banner that provides my clients with health info (refreshed every minute on the server side). I would like my clients to be able to re-fetch the banner without having to restart their Electrum clients.

Would it be possible to have a command in the console to make it possible? Thank you.

**Comment by ecdsa** [comment]
>>network.network.interface.send_request({'method':'server.banner','params':[]})

**Comment by Thireus** [comment]
Working great, thank you!

**Comment by Thireus** [comment]
Annnd, not working anymore in the last versions :(
```
>> network.network.interface.send_request({'method':'server.banner','params':[]})
Traceback (most recent call last):
```

**Comment by ecdsa** [comment]
remove one of the two "network."
