### ISSUE TITLE
Electrum 2.4.4 impossible send bitcoins

### ISSUE THREAD

**Issue by nannarone** [spesmilo/electrum#1422]
Hello everyone, i am new to Electrum, a couple of days ago I sent few btc to my electrum wallet and now i cannot send it back to my main wallet. when i made a transaction clicking on "send" i fill all the blanks, then sign, insert password and wait for confirmations but my transactione never appears on history, nor pending or unverified. so at the moment it is impossible for me move my bitcoins, are stuck in Electrum and I don't know how to handle this problem. Can you help me? What I have to do? Thanks in advance to everyone

**Comment by ecdsa** [comment]
can you provide more details?
 - did you click on send?
 - was your client connected when you did it?
 - did you see a popup window with your transaction id ?

**Comment by nannarone** [comment]
yes i click send and i was connected. yes, a pop up appears but is written transaction unknown even after signed and insert 2fa. There's a screenshot attached that shows this step.


Am I doing something wrong?


Thanks


Gaspare


&nbsp;



--------- Original Message --------

 Da: "spesmilo/electrum" &lt;reply@reply.github.com&gt;

 To: "spesmilo/electrum" &lt;electrum@noreply.github.com&gt;

 Oggetto: Re: [electrum] Electrum 2.4.4 impossible send bitcoins (#1422)

 Data: 25/08/15 17:36

 

 
can you provide more details?



did you click on send?
was your client connected when you did it?
did you see a popup window with your transaction id ?

&mdash;

Reply to this email directly or view it on GitHub.


&nbsp;



 
 
 --
 ZE-Light e ZE-Pro: servizi zimbra per caselle con dominio email.it, per tutti i dettagli 
Clicca qui http://posta.email.it/caselle-di-posta-z-email-it/?utm_campaign=email_Zimbra_102014=main_footer/f
 
 Sponsor:
 Idee regalo classiche o alternative? Trova l'offerta migliore in un click
 Clicca qui: http://adv.email.it/cgi-bin/foclick.cgi?mid=13327&d=25-8

**Comment by ecdsa** [comment]
yes, please post a screenshot of the popup window

**Comment by pattygreen** [comment]
I have the same problem,
I can not send bitcoin
After the transition, the balance is always the same and it does not appear in history...

**Comment by ecdsa** [comment]
@pattygreen is this also a two-factor wallet?

**Comment by pattygreen** [comment]
yes, my electrum version is 2.3.1

**Comment by ecdsa** [comment]
can you reproduce it with ecdsa.net as server, and post here the transaction id ?

**Comment by pattygreen** [comment]
I try..

**Comment by pattygreen** [comment]
I can not connect to ecdsa.net...the connection is not private
could you help me in another way?

**Comment by pattygreen** [comment]
after the process of sending, I insert the password and then, it asks me to insert the 
 authentication google code. After, It appears a pop-up about the transition with unknown ID and status: partially signed (1/2).
That's it

**Comment by ecdsa** [comment]
what do you mean by 'the connection is not private' ?

**Comment by ecdsa** [comment]
@badmofo could it be a server side issue? 
I just tested, client side works fine for me

**Comment by ecdsa** [comment]
the behaviour corresponds to what I get if the Google Auth password is wrong.
maybe a clock drift issue?

**Comment by badmofo** [comment]
@ecdsa I haven't seen any errors on the server side.  

Not a drift issue: trustedcoin's server's clocks are ntp-synced to atomic clocks.

**Comment by ecdsa** [comment]
ok.. 
one issue is that the GUI fails to report the 'wrong OTP' message to the user.
it shows the partially transaction instead, which is confusing.
I think this is a regression

**Comment by ecdsa** [comment]
@pattygreen can you check in your Google Authenticator application, there is an option to synchronize the clock. Try it, and retry to send coins

**Comment by ecdsa** [comment]
@nannarone @pattygreen please resync your Google Authenticator, and retry.
Let me know if it worked or not.

**Comment by pattygreen** [comment]
It works now...thanx!

**Comment by ecdsa** [comment]
@pattygreen can you tell us if you synchronized Google Authenticator to make it work, or if it works for another unexplained reason? that kind of short answer does not really help... :-(

**Comment by pattygreen** [comment]
I synchronized Google Authenticator... 
Thanks x tips!

**Comment by ecdsa** [comment]
ok, then I will close this issue

**Comment by nannarone** [comment]
i cannot re-sync google authenticator, in my settings i don't have the
option, where i can find it? my version is 2.4.4


thanks


&nbsp;



--------- Original Message --------

 Da: "spesmilo/electrum"
&lt;reply@reply.github.com&gt;

 To: "spesmilo/electrum" &lt;electrum@noreply.github.com&gt;

 Oggetto: Re: [electrum] Electrum 2.4.4 impossible send bitcoins (#1422)

 Data: 27/08/15 17:02

 

 
ok, then I will close this issue


&mdash;

Reply to this email directly or view it on GitHub.


&nbsp;



 
 
 --
 ZE-Light e ZE-Pro: servizi zimbra per caselle con dominio email.it, per tutti i dettagli 
Clicca qui http://posta.email.it/caselle-di-posta-z-email-it/?utm_campaign=email_Zimbra_102014=main_footer/f
 
 Sponsor:
 Soluzioni di email hosting per tutte le esigenze: dalle caselle gratuite a quelle professionali su piattaforma Zimbra, da quelle su proprio dominio a quelle certificate PEC. Confronta le soluzioni
 Clicca qui: http://adv.email.it/cgi-bin/foclick.cgi?mid=13326&d=27-8

**Comment by ecdsa** [comment]
@nannarone in your Google Auth application. it's not an electrum issue
