### ISSUE TITLE
getrawtransaction is missing in jsonrpc and command line.

### ISSUE THREAD

**Issue by uzyn** [spesmilo/electrum#1427]
Are we able to have `getrawtransaction()` without going through python?

Thanks.

**Comment by ecdsa** [comment]
it's called gettransaction

**Comment by uzyn** [comment]
How do we get inputs and outputs from `gettransaction`?
Thanks.

**Comment by uzyn** [comment]
Just realized there's a second param to `gettransaction`. Passing `True` returns full raw tx.

Thanks. Sorry for the bad opening of issue.

**Comment by ecdsa** [comment]
with the latest version you can use -d for the deserialized version
