### ISSUE TITLE
Unable to specify sending ALL/MAX coins

### ISSUE THREAD

**Issue by JulianTosh** [spesmilo/electrum#1428]
The only way to spend ALL available coins is to guess. Often this results in an error regarding dust.

A "max" button near the btc amount field when spending can calculate the exact fees and will resolve this issue.

**Comment by JulianTosh** [comment]
> error: {u'message':u'64:dust',u'code':-26}

Workaround is to "set transaction fees manually" in preferences, and do the math yourself. Be careful no to be too generous with your fee.

**Comment by ELM4Ever** [comment]
Enter the exclamation mark  " ! "  in the box where you would input the amount of coins to send.

**Comment by JulianTosh** [comment]
Works like a charm! Now if it could work for one of the lines in a multi-pay transaction!

**Comment by ecdsa** [comment]
@JulianTosh is an early adopter of Electrum, and he never saw that feature
this makes me think we need to make it more visible

**Comment by DavidGriffith** [comment]
A button making this explicit would be very welcome for those who didn't catch the special '!' trick.

**Comment by ulrichard** [comment]
Or a tooltip help window with all the options. 
I know these options exist, but when I want to use, I can't remember the syntax.

**Comment by ecdsa** [comment]
@ulrichard: what do you mean, there already is a tooltip help window...

**Comment by ulrichard** [comment]
@ecdsa  Ah, I only found it now that you say there is one.
I was thinking it would appear when I hover slowly over the entry field, and also disappear automatically. 
Or placing a blue 'i' in a circle next to the entry field that opens the existing message box.
