### ISSUE TITLE
Recent daemon / proxy changes

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1431]
Opening this to record issues I notice with recent daemon / proxy changes.

At present just one thing: occasionally when starting a second or subsequent wallet, something goes wrong and nothing appears.  However the electrum command exits successfully, and the daemon says client quit, but then nothing else happens.  There is no error message anywhere.

Unfortunately I don't know how to make this happen at will so have been unable to figure out what causes it, and I don't have a log of the last time it happened.

**Comment by kyuupichan** [comment]
This is opening a 2nd wallet:

$ LC_ALL=en_GB.UTF-8 python2.7 ./electrum -v -w my_wallet
electrum directory /home/neil/.electrum
[profiler] init_plugins 0.4417
ok
neil@zotac:~/src/electrum$

And the daemon process:

new client: 1
electrum directory /home/neil/.electrum
client quit: 0

and that's it.  No window appears.

**Comment by kyuupichan** [comment]
Ah, this causes it:

a) open my_wallet
b) either start another wallet window and then close my_wallet window, or open a different wallet from the existing window
c) open my_wallet again

I think the daemon thinks it's already open when it's not

**Comment by kyuupichan** [comment]
Another issue I've just noticed: with multiple windows and the exchange rate plugin, only one window has the additional widgets.

**Comment by ecdsa** [comment]
first issue fixed in bbe64621ca983375365c547f89311f245bc473fb

**Comment by ecdsa** [comment]
concerning the plugin, I think similar issues will arise elsewhere.

**Comment by kyuupichan** [comment]
Closing this.  Generic handling is good.  The 3 hardware wallets and trustedcoin plugins still need some work.
