### ISSUE TITLE
standalone version should use electrum_data

### ISSUE THREAD

**Issue by triorr** [spesmilo/electrum#1438]
the version 2.3.2 standalone in windows 7 used  to make and use "electrum_data" folder in the same folder as the application . With the update its not any more . Instead it create the data folder in  \AppData\Roaming folder like the non-portable version.

**Comment by ecdsa** [comment]
i it the case with the latest version?

**Comment by triorr** [comment]
yes it is .

**Comment by triorr** [comment]
A workaround:
electrum.exe -P

**Comment by ecdsa** [comment]
are "standalone" and "portable" supposed to be the same thing?
