### ISSUE TITLE
tor access only

### ISSUE THREAD

**Issue by Braivnuwrld** [spesmilo/electrum#1442]
my wallet used to work no matter what. now it only works if i'm running tor. how do i get it to work like it used to

**Comment by ecdsa** [comment]
did you you open the non-tor ports on your firewall?

**Comment by Braivnuwrld** [comment]
thanks but i figured it out it's just i updated wallet and ssl is always checked so i just set it to none and it works fine.

**Comment by ecdsa** [comment]
wait, ssl does not work?
