### ISSUE TITLE
Wrong fee calculation

### ISSUE THREAD

**Issue by sledgehammer999** [spesmilo/electrum#1443]
I am coming from 1.9.8 but I backed up wallet before upgrading to 2.4.4 (Windows 7).
I tried to do an "internal move" of BTC. The input and output address was the same. I was trying to consolidate my BTC into one tx(?) to avoid fees in the future.

I have set fees to 0 from the options and I also enabled the "set fees manually" option. When I populate the `Amount` field the `Fee` field gets automatically updated with `0.00001 BTC` which I reset to 0 BTC.
I tried to send it but Electrum 2.4.4 doesn't let me. It insists that I need to set a fee of `0.00001 BTC`.

I refused and I downgraded to 1.9.8 and restored my backed up wallet. I did the same procedure and it sent them without any complain. The transaction on blockchain.info appeared as "medium priority".
I had the same happen to me with a transaction that appeared on blockchain.info as "very soon - high priority". (I also downgraded to 1.9.8 to send it without fee)

Btw, since I set fees to 0 from the Preferences why does it automatically append `0.00001` to the `Fee` field? Isn't this a bug too?

Anyway, **for the main bug:** If this change was deliberate on the 2.x series I couldn't find any documentation of it.
Here is my [BTC address](https://blockchain.info/address/1PuTGwQvCF5hjp1uMKy7PPJqbM8uTjRtvU) to examine the tx and see why the new algo fails. I was trying to move everything up until(and including) [this tx](https://blockchain.info/tx/b3d07f03a7af0d2cbc823132bcc55a6bc9e52de9b450b56d2c054f15bcf8fca8) and this is [the tx](https://blockchain.info/tx/1edf5427a10729f1124604506d8efb21f22c9c01183ac7aacd307387ddd68ed7) 1.9.8 created.

**Comment by ecdsa** [comment]
Setting a zero value in your preferences will not work, because Electrum will still add the minimum needed for transaction propagation. If you want to force a zero fee, you need to type it before you type the amount.
1. activate the option 'set fees manually'
2. type 0 in the fee field
3. type ! in the amount field

**Comment by ecdsa** [comment]
note: I've added that question to the FAQ

**Comment by sledgehammer999** [comment]
That's the thing. My particular transaction shouldn't need a minimum fee. That's why 1.9.8 didn't require a fee and send it. When my transaction doesn't qualify for no fee 1.9.8 prompts me for the fee. It doesn't send it anyway. That's why I say there is something wrong with 2.4.4.
