### ISSUE TITLE
paytomany expects csv_file, which does not make sense for JSONRPC

### ISSUE THREAD

**Issue by uzyn** [spesmilo/electrum#1444]
Or is there a way to pass in CSV file through JSONRPC calls?

**Comment by dabura667** [comment]
"address1,amount1\naddress2,amount2\naddress3,amount3"...so on so forth.

**Comment by uzyn** [comment]
Thanks @dabura667 Let me try that.

**Comment by uzyn** [comment]
It does not work.

Tried various combinations:

- address1,amount1\naddress2,amount2\naddress3,amount3
- "address1",amount1\n"address2",amount2\n"address3",amount3

They all gave the same error:

```
{ error: 
   { message: 'Server error:   File "electrum/commands.py", line 418, in _read_csv | IOError: [Errno 2] No such file or directory: u\'1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\'',
     code: -32603 },
  jsonrpc: '2.0',
  id: '746fb40a-80b6-49b1-8f50-54759c464f98' }
```

**Comment by ecdsa** [comment]
I agree, it would be better to pass the raw data

**Comment by ecdsa** [comment]
fixed in f90ca26

**Comment by ecdsa** [comment]
example with the new syntax:
```
echo "[[\"1HYuHGztWoxR5cAw3QwAd89LCU7sM2QuAk\", 1]]" | ./electrum paytomany -
```

**Comment by uzyn** [comment]
Thanks @ecdsa :+1:

**Comment by ecdsa** [comment]
btw @uzyn are you using the command line or the jsonrpc GUI ?

**Comment by uzyn** [comment]
@ecdsa I'm using jsonrpc "GUI"

**Comment by ecdsa** [comment]
ok. please note that it will soon be replaced by the daemon

**Comment by uzyn** [comment]
@ecdsa How does that work?

**Comment by ecdsa** [comment]
'electrum daemon start'

**Comment by uzyn** [comment]
And jsonrpc would still be available right?

Actually that would be really cool!
Right now I find it frustrating sometimes as when I'm running Electrum in JSONRPC GUI, I lose the ability to query via command line, unless I start another daemon.

**Comment by ecdsa** [comment]
yes, that's the reason why I want to do that

**Comment by ecdsa** [comment]
do you need to access jsonrpc by a port number, or could you use a file socket?

**Comment by uzyn** [comment]
@ecdsa Yes, I'll need a port as I'm running it in a separate docker container.

**Comment by uzyn** [comment]
@ecdsa Can you give me an sample call via JSONRPC? I can't seem to get it to work, though command line works fine. Regardless if I pass in the param as string or as object, it would fail. 

Error:
```
Server error:   File "/usr/local/lib/python2.7/dist-packages/electrum/commands.py", line 388, in _mktx | ValueError: need more than 1 value to unpack
```

**Comment by ecdsa** [comment]
this works with current git head:
```
curl --data-binary '{"id":"curltext","method":"getbalance","params":[]}'  http://127.0.0.1:7777
```

**Comment by ecdsa** [comment]
Note: if you start the jsonrpc GUI (or any other GUI), you do have the ability to query via command line.
If you stop the GUI, the command line will ask you to launch a daemon

**Comment by uzyn** [comment]
@ecdsa Sorry I mean sample call of `paytomany` via JSONRPC. I'm already interfacing an app with Electrum via JSONRPC, just couldn't get `paytomany` to work even for HEAD.

**Comment by ecdsa** [comment]
outputs are a list of list, so this hast to be like this:
```
curl --data-binary '{"id":"curltext","method":"paytomany","params":[[["ecdsa.net",1]], null, null, null, null, true]}'  http://127.0.0.1:7777
```

**Comment by uzyn** [comment]
Thanks @ecdsa 
Let me give that a try.

**Comment by ecdsa** [comment]
I realize if would be more convenient to be able to pass options by name

**Comment by uzyn** [comment]
@ecdsa Yeah definitely. 
Electrum is working really well for the GUI part, it's just the command part can still get rather confusing sometimes.

Thanks for all the help!

**Comment by ecdsa** [comment]
jsonrpc does not have a 'options' field.
in order to be compliant, options would need to be part of 'params', which is ugly..

**Comment by uzyn** [comment]
1 suggestion is for the recipients to be in actual JSON instead of a list, i.e. 

```json
[
    {"address1": 0.01},
    {"address2": 1.2)
]
```

**Comment by ecdsa** [comment]
jsonrpc 2.0 is supposed to accept named parameters: http://www.jsonrpc.org/specification#examples
I'm trying it, but it does not seem to work on my system

**Comment by ecdsa** [comment]
ok, I fixed named parameters in 458b62f5de5c9223acbfedd4f1f5ceb042a01ef5
you can do this now:
```
curl --data-binary '{"id":"curltext","method":"paytomany","params":{"outputs":[["ecdsa.net",1]], "unsigned":true}}'  http://127.0.0.1:7777
```

you cannot pass the password though; you would need to pass it to the gui on startup

**Comment by uzyn** [comment]
Looks good @ecdsa 

When there are more than 1 output, is it

```
curl --data-binary '{"id":"curltext","method":"paytomany","params":{"outputs":[["ecdsa.net",1], ["address2",1]], "unsigned":true}}'  http://127.0.0.1:7777
```

**Comment by ecdsa** [comment]
yes

**Comment by html5-ninja** [comment]
is it possible to create a signed transaction ready for broadcast instead of unsigned transaction ?

**Comment by ecdsa** [comment]
of course. there's a 'sign' button in the transaction window.

**Comment by html5-ninja** [comment]
I mean using the json rpc api 
`curl --data-binary '{"id":"curltext","method":"paytomany","params":{"outputs":[{"ecdsa.net":1}, {"address2":1}], "unsigned":true}}'  http://127.0.0.1:7777`

but without the "unsigned":true

**Comment by ecdsa** [comment]
type "electrum help" to see the list of RPCs

**Comment by html5-ninja** [comment]
thank @ecdsa , I know all electrum commands I like this wallet 
but it's the first time that I use the jsonRPC api , as mentioned by you ,"you cannot pass the password"
so if you remove "unsigned":true it will simply generate an error .
My solution not really elegant but its work, I've simply update the _mktx method on lib/commands.py 

```
        if not unsigned:
	    self.wallet.sign_transaction(tx, 'mypassword')
```

I like electrum :D , and @ecdsa  you are doing great job thank you

**Comment by ecdsa** [comment]
yes, you can pass the password in the options.
the command line actually uses the jsonRPC api
