### ISSUE TITLE
Payments requests generated by  Electrum 2.4 not accepted by 2.3.2

### ISSUE THREAD

**Issue by tl121** [spesmilo/electrum#1445]
Following the instructions I installed 2.4 on a server and proceeded per the instructions to generate a payment request as a test.  When this was sent to bitcoin-core 11.0 the request was accepted and shown as authenticated.  Changing my web browser to use Electrum 2.3.2 the "Send" tab came up, but the Pay to field hung with the message ::"Please wait..."

Please note:  the 2.3.2. client has successful processed several payment requests generated by Bitpay.

Payment request on an Ubuntu server.  Web browser and 2.3.2 client on Windows 7.  Bitcoin-core 11.0 also on Windows 7.

**Comment by ecdsa** [comment]
does it work with a recent client?
if not, can you post a link with the payment request?

**Comment by tl121** [comment]
I don't want to post a link.  I will be glad to email it to you, but don't know what your address is.

**Comment by ecdsa** [comment]
my email address is on my profile, just click on my user page

**Comment by tl121** [comment]
email sent.  fresh example, good for about 60 minutes.

**Comment by ecdsa** [comment]
thanks. a definition was missing.
fixed in ebd5a565ed0e9fe5313ecf514739d1240d697e04

**Comment by tl121** [comment]
Was this a change in the checking code or the generating code?  
Incidentally, sha1 itself is no deprecated.  When I renew my node's certificate in a few weeks I will end up with sha2 in the chain.  (The node didn't get an "A+" rating from SSL Labs because of the sha1 support.

**Comment by ecdsa** [comment]
it's an update in the verification code. generation is ok.
yes, sha1 is kind of deorecated today.
