### ISSUE TITLE
Description vanished

### ISSUE THREAD

**Issue by bitcoinmichi** [spesmilo/electrum#1447]
All my entered descriptions for transaction just have vanished! Using version 2.4.4

Electrum was somehow synchronizing in a endless loop and I had to shut it down. After the restart the descriptions where gone. Also the assigned lables in the Addreses tab.

**Comment by ecdsa** [comment]
on windows?

**Comment by bitcoinmichi** [comment]
Yes, its on Windows 10.

Later the day when i used Electrum again the description where there again. HOWEVER new description which I made for new incoming payments dissapared. 

Thanks

Michael

**Comment by ecdsa** [comment]
Windows is an inexhaustible source of mysteries..

**Comment by ecdsa** [comment]
closing (unresolved)
