### ISSUE TITLE
listaddresses behave weirdly when more than 1 of the params are True

### ISSUE THREAD

**Issue by uzyn** [spesmilo/electrum#1448]
- receiving: Defaulted to False, but still returning list of receiving addresses
- If set both `receiving` and `change` to true, results is empty.

and various other weird combinations.

**Comment by ecdsa** [comment]
indeed, maybe we should change the syntax.
suggestions are welcome

**Comment by ecdsa** [comment]
by default, the command returns all addresses.
receiving and change are filters. their intersection is empty

**Comment by ecdsa** [comment]
fixd help in 849cc0200bca9862c22473bea1df41af4668cbe7
