### ISSUE TITLE
Branch to make trezor plugin multi-window compatible

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1450]
@ecdsa, I've pushed this but am completely unable to test anything, so there are likely several issues.

Things that should be tested include:

a) creating new wallet
b) restoring wallet
c) right-click receive_menu
d) opening an existing wallet as 2nd window of 2 and that 1st window continues to be fine
e) opening an existing wallet as 1st window of 2 and that 2nd window is fine
f) command-line only usage
g) signing and sending a transaction
h) Two trezor wallets simultaneously if possible...

I'd appreciate your help in getting this completed.  Once this works getting keepkey and btchip plugins converted will be easier.

**Comment by ecdsa** [comment]
thanks!

**Comment by ecdsa** [comment]
this branch does not work.. it behaves as if the wallet was watching-only

**Comment by ecdsa** [comment]
also, you changed the number of arguments required by tx_outputs, but it is still called with the wrong number of arguments

**Comment by ecdsa** [comment]
also, why is self.wallets a dict ?

**Comment by kyuupichan** [comment]
It's a dict because it is in the other plugins; in case I want to associate data with each wallet.  Maybe trezor as-is didn't need anything.

**Comment by ecdsa** [comment]
I don't see why the plugin should handle several wallets.

**Comment by kyuupichan** [comment]
Perhaps not, but given it has to handle the wallet being opened first or
second it really doesn't make much difference in terms of changes required.

**Comment by ecdsa** [comment]
I don't really understand what you are trying to achieve..
perhaps it would be better to explain what you are trying to fix?

**Comment by kyuupichan** [comment]
As the plugin only has one wallet variable, how can it possibly work with 2
windows?  Think about what happens.

If you don't think it's broken then let's leave it; I have no axe to grind
as none of the hardware wallets works for me.

**Comment by ecdsa** [comment]
there is currently no way for the plugin to handle several trezor wallets simultaneously, and your branch does not fix that; in order to do that, we would need to work with several usb ports simultaneously.

if we assume that only a single trezor wallet is plugged, then it will be the wallet variable of the plugin.
A few minor things might be broken because we have multiple windows, but I think it's better to fix them individually, than to go for a solution where the plugin manages several wallets.

**Comment by kyuupichan** [comment]
As Thomas says handling multiple USB wallets is a different issue
