### ISSUE TITLE
Electrum stuck on synchronising

### ISSUE THREAD

**Issue by carstoiucosmin** [spesmilo/electrum#1451]
Hello, everyone, I really need some help. My electrum wallet got stuck on synchronising for some time now. When I hit the arrows button for refresh, the wallet becomes unresponsive. I cannot get to the server list and probably that is why I am blocked. I can only force quit. Please give me a solution. I am using Electrum for Mac, Yosemite, version 2.4.4.
![screen shot 2015-09-15 at 09 08 51](https://cloud.githubusercontent.com/assets/14288397/9869151/7a6bf5c6-5b89-11e5-8427-0dba57201a6f.png)

**Comment by ecdsa** [comment]
can you try to delete your configuration file, and report if it worked?

**Comment by ecdsa** [comment]
closing, no answer from OP
