### ISSUE TITLE
error: {u'message': u'66: insufficient priority', u'code': -26}

### ISSUE THREAD

**Issue by Koepferus** [spesmilo/electrum#1453]
I want to send 1BTC to an other adress. As soon as i entered my verification code this error arrived.  error: {u'message': u'66: insufficient priority', u'code': -26} Can someone help please?

**Comment by ulrichard** [comment]
Verification code sounds like a ledger hardware wallet?

**Comment by EagleTM** [comment]
Just a guess but "priority" is associated with fee free transactions. Maybe the tx did not have a fee (and electrum did not catch it as one that bitcoind won't accept, hence the error code directly from bitcoind)

**Comment by gits7r** [comment]
Yeah that is plausible bitcoind won't accept via rpc 0 fee tx. @Koepferus can you confirm if you included a fee in your transaction? And if yes, please tell us the exact electrum version you are using and on which server are you getting this error.

**Comment by ecdsa** [comment]
losing this. Electrum 2.6 uses "relayfee" sent by the server
