### ISSUE TITLE
plugin for exchange rate is not working

### ISSUE THREAD

**Issue by Braivnuwrld** [spesmilo/electrum#1456]
my exchange rate plugin is supposed to show me the btc in usd, but it does'nt work. Although it used to. Any suggestions?

**Comment by ecdsa** [comment]
this is a useless report. please provide a description of how it is failing

**Comment by ulrichard** [comment]
Sometimes one of the providers doesn't seem to respond.
Then just choose another source in the settings. The next day the original source will probably work again. 
Nothing to do with electrum.
