### ISSUE TITLE
auto resize send tab

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1458]
All other tabs correctly adapt the layout when I resize the main window.

**Comment by kyuupichan** [comment]
Can you explain what the issue is in more detail?

**Comment by ulrichard** [comment]
When I increase the size of the main window, the content of most tabs fills the window.
The receive tab has dynamic resizing behavior in that the horizontal size and position of the widgets adapt.
The widgets of the send tab just sit in the top left corner, when I grow the electrum window to full screen.
I mean it's enough room to fit the information they are supposed to contain, but it would look nicer if they also filled the window, at least horizontally.
I had a quick look into the code, and the tab seemed to have similar layout controls as the receive tab.

**Comment by kyuupichan** [comment]
It would be nice if you could test my changes and let me know what you think.
