### ISSUE TITLE
Seed doesn't work! Seed says there are no transactions

### ISSUE THREAD

**Issue by terribletoast** [spesmilo/electrum#1464]
So my problem is that i have reinstalled my Pc and now i want to restore my Wallet with the Seed but it does not work. I have made a screenshot from the seed so there are not any spelling mistakes. I don't know what i have to do so is there any chance to help me? I know my exactly Bitcoins.
Please help me

**Comment by abitfan** [comment]
What happens when you try to restore your wallet ?

**Comment by terribletoast** [comment]
So i wirte down the 12 words and then the server load informations and
their comes the window: No transactions found.
But I know exactly how much bitcoins i have on my account.
Am 28.09.2015 08:01 schrieb "abitfan" <notifications@github.com>:

**Comment by dabura667** [comment]
How long ago did you create the wallet?

**Comment by terribletoast** [comment]
I have create it in the last february
Am 28.09.2015 11:37 schrieb "dabura667" <notifications@github.com>:

How long ago did you create the wallet?

—
Reply to this email directly or view it on GitHub
<https://github.com/spesmilo/electrum/issues/1464#issuecomment-143691645>.

**Comment by ecdsa** [comment]
are you sure it is an electrum seed?
electrum seeds are backward compatible.

**Comment by terribletoast** [comment]
Yes i have installed it because i do not download the full bitcoin client.
Then I made a screenshot from the Seed and now After the reinstall from
windows I want to use my seed to restore the wallet
Am 28.09.2015 16:02 schrieb "ThomasV" <notifications@github.com>:

**Comment by ecdsa** [comment]
you probably made a typo when writing the seed.

**Comment by terribletoast** [comment]
I have also checked this more than 4 times. Is there any Person I can call
or write some kind of official persons? Or do I need more than the seed to
revover the wallet?
Am 28.09.2015 16:34 schrieb "ThomasV" <notifications@github.com>:

**Comment by ecdsa** [comment]
you only need the seed and nothing else.
your wallet must be online and synched (see above question, that you did not answer)

**Comment by dabura667** [comment]
> Or do I need more than the seed to recover the wallet?

All you need is the seed.

If you input the seed and your bitcoins aren't there, there are only 2 possibilities:

1. The network is having problems.
2. You are inputting the wrong seed. (ie. a different seed from the one you deposited to)

1 can be checked by looking at one of the addresses (the one at the top) on a block explorer site and seeing if there is a history. If there is a history, but it is not showing in Electrum, then your Electrum network connection is bad.

2 can only be checked by inputting the seed and checking the balance.

However, I must warn you: there are a LOT of words with similar spelling in the wordlist (ie. "through" and "though") so please double check your spelling.

**Comment by terribletoast** [comment]
I have checked it once more it does not work i get only their are no
transactions found.
Now i don't know what i have to do because thats all okay
Am 28.09.2015 17:01 schrieb "dabura667" <notifications@github.com>:

**Comment by terribletoast** [comment]
Now I need my Mistake so for all I only import my private keys with the
Bitcoins and I do not know that they are not restoreable with the seed. Can
I get the Bitcoins back when I already have the private keys?

2015-09-28 20:13 GMT+02:00 Felix B <broeker.felix@googlemail.com>:

**Comment by ecdsa** [comment]
yes you can; just read the documentation.
http://docs.electrum.org/en/latest/faq.html

**Comment by terribletoast** [comment]
I already find it out and it works. Thanks for all your answers and the try
to help me. Very nice forum :)
Am 29.09.2015 22:51 schrieb "ThomasV" <notifications@github.com>:
