### ISSUE TITLE
Can't Recover Electrum Wallet

### ISSUE THREAD

**Issue by quietmouse** [spesmilo/electrum#1465]
I need help in recovering an Electrum wallet that I fucked up.  It contains $220 approximately.  Willing to pay you to help me!!!!!

**Comment by abitfan** [comment]
Can you describe the problem ?

**Comment by ecdsa** [comment]
op recovered his wallet

**Comment by quietmouse** [comment]
Actually, kind fellows, and I can't tell you how much I appreciate you
taking time out of your day to assist me, I still have the same full coin
stuck in my Electrum wallet.

Although I was indeed able to make the wallet reappear, which I assume is
considered recovering, I cannot send out my coin from my Electrum wallet.
After I make preparations to send, and Electrum notifies of the fee, and I
accept, it gives me an error that reads "NoneType" object has no attribute
'_getitem_'

Being a techno dummy, although I understand this error is communicating to
me that my coin has no value, I have no idea how to fix it.

If you gents could assist me I would greatly appreciate it!

Troy

**Comment by JBDC18** [comment]
Hi, is there a solution for this problem, I have the same problem, please someone help.. please
