### ISSUE TITLE
Error: nonetype object has no attribute _getitem_

### ISSUE THREAD

**Issue by quietmouse** [spesmilo/electrum#1466]
Well, I finally restored my wallet.  But now when I hit send and agree to the fee up pops the error message nonetype object has no attribute _getitem_

I'm just not techno enough for Electrum, if I ever get this btc out I know when to call it quits.

Anyone have any insight on how to solve this error?

**Comment by kyuupichan** [comment]
If you could run from the command line with -v and provide the relevant
output (the last 30 lines or so, say) that would be helpful.

**Comment by ecdsa** [comment]
is this with git head, or with a released version?

**Comment by quietmouse** [comment]
released version

**Comment by quietmouse** [comment]
@kyu where do I find the command line and relevant output?  Sorry, I'm so terribly bad at this.

**Comment by ecdsa** [comment]
could you be specific enough to disclose which released version???

**Comment by murder77** [comment]
you programm security is a type non error?

**Comment by ecdsa** [comment]
closing this. reopen if the issue exists in 2.5.
