### ISSUE TITLE
Lost BTC

### ISSUE THREAD

**Issue by HannesBloom** [spesmilo/electrum#1475]
I tryed to send BTC to a second wallet of mine. First I generated a new "Receiving address".
After that i copied this address and send BTC from the first wallet to the second one. 

"Receiving address" did not appear in "Adresses".
I send BTC to this address wich is not listed in "Addresses".

Are the BTC lost now?

**Comment by ecdsa** [comment]
are you sure? is this all the relevant information?

**Comment by HannesBloom** [comment]
I don't know.
I think the description is complete. 
What else do you need?
I still have the address.

**Comment by ecdsa** [comment]
if you generated the address, then it also appears in the wallet's list of addresses.

**Comment by kyuupichan** [comment]
If you copied and pasted the address, there is a possibility you have malware on your machine that replaces the clipboard contents with a different address belonging to the malware author.  This is most likely on Windows.

**Comment by HannesBloom** [comment]
Ok.
Thank you guys.
I think they are gone.

**Comment by JustinTArthur** [comment]
To test what @kyuupichan suggests, you could try copy and pasting another receiving address into another program and just double-check they are the same.

**Comment by ecdsa** [comment]
Not sure if it is useful to invoke a malware attack here, because user mistake is probably 100 times more likely. But ok, if we do that, I agree we should at least ask the user to reproduce it.

**Comment by gits7r** [comment]
@HannesBloom check via a web block explorer if there are any coins in that address which you sent to. The addresses in electrum are deterministic and it doesn't matter if it's above the limit of addresses electrum generates automatically, if there are any coins in it, it will show up in your wallet. 

Check the address via a web blockexplorer like blockchain.info or something and try to restore your wallet from seed if there are coins in that address.

If there are coins in that address but it still not appears in your wallet after restoring from seed, try again the very same steps, generate a new address but don't send any coins to it, just check the new generated address on a web block explorer to see if there are coins in it. At least this way you will identify if there's malware involved.

**Comment by kyuupichan** [comment]
@HannesBloom - can you come back to us?  Can you test if copying and pasting addresses as you did before properly preserves them?

What about the block explorer question?

**Comment by EagleTM** [comment]
It sounds trivial but: Did the balance in the second wallet increase since you've sent it? 
It looks like you're generated a payment request an the "Receive tab" which has has an expiry date (for the request) and then possibly.

Just a long shot and I'm testing this out at the moment but it might possible that the address in the "addresses" tab vanishes to the usually hidden "Used" section once the request has expired. This won't mean the coins are lost though

**Comment by kyuupichan** [comment]
No repsonse from OP
