### ISSUE TITLE
Mac Version, Failure to Send When Changing Miner Fee Options

### ISSUE THREAD

**Issue by swt83** [spesmilo/electrum#1476]
In the settings, if I change the miner fees to anything other than the default -- as in, set my own fee, or use dynamic fees -- the transaction will fail and the Bitcoin won't send.  It will give an error.

**Comment by ecdsa** [comment]
what error?

**Comment by swt83** [comment]
I wasn't able to replicate the error.  At the time I remember it being some
kind of json string or something -- not human readable.

**Comment by ecdsa** [comment]
probably 'insufficient priority'

**Comment by Thireus** [comment]
I can confirm it's the 'insufficient priority' one.

@swt83 set the tx fee to 0.00005 BTC at a minimum.

**Comment by ecdsa** [comment]
ok, so this should be closed, as it is a duplicate of #1453 
still, we should make the error message more 'human readable'
