### ISSUE TITLE
Add support for electrum in mackup

### ISSUE THREAD

**Issue by rbartoli** [spesmilo/electrum#1477]
Hi,

I'm interested in adding support for electrum in [mackup](https://github.com/lra/mackup) and I'd like to clarify a couple of things before getting my PR accepted (in mackup).

The files I was thinking of backing up are the followings:

* `~/.electrum/config`
* `~/.electrum/wallets/default_wallet`

Is the default_wallet encrypted by default? Is it a good idea to back that up?

Thanks

**Comment by dabura667** [comment]
> default_wallet encrypted by default

Not unless the user sets a password. This is not required.

> Is it a good idea to back that up?

I would lean towards no. Users should have written down their seeds, which is all the backup they will ever need.

I also don't trust Dropbox, so i would recommend against supporting Electrum in mackup.

**Comment by rbartoli** [comment]
Perfect. Considering that [mackup](https://github.com/lra/mackup) should only copy settings, it's probably worth only including `~/.electrum/config` in the backup.

Thanks a lot for your clarifications and prompt reply.
