### ISSUE TITLE
FIDO U2F two-factor authentication

### ISSUE THREAD

**Issue by RJacksonm1** [spesmilo/electrum#1480]
Electrum currently supports 2fa via TOTP with the TrustedCoin plugin.  I would also like Electrum to support physical two-factor security keys via the FIDO U2F protocol: https://www.yubico.com/applications/fido/

U2F works via standard public-private key crytography: There is an upfront registration process where the U2F device generates a public-private key pair and stores the private key on the device (or in the case of the Yubico implementations, the private key is deterministic based upon a hardware secret, a generated nonce, and the app id for the registering application), and returns the public key and a key-handle.  When it comes to challenging users, the device is sent the key-handle for the previously registered key as well as a challenge, and the U2F device then signs the challenge with the relevant private key, and returns that signed challenge to the authenticating service.

Yubico already offer a Python package for interacting with FIDO U2F compatible devices: https://github.com/Yubico/python-u2flib-host

I have reviewed the TrustedCoin plugin to understand how the TOTP 2fa is implemented, which appears to be using an undocumented TrustedCoin API, but none of the implementation details are surprising: TrustedCoin have an end point which generates a TOTP secret, and an endpoint to sign transactions which validates requests by the given TOTP code.

Implementing FIDO U2F would require changes to TrustedCoin's API to support the U2F registration and challenge process, and then I guess the easiest implementation, Electrum-wise, would be to create a new wallet-type for U2F-backed wallets (so 2fa with TOTP, and 2fa with U2F).  Yubico offer several libraries for both the server-side and client-side implementation of the protocol: https://developers.yubico.com/U2F/Libraries/List_of_libraries.html

What's required, on the API front, is:
* An 'enroll' endpoint to start the device-registration process. This generates an initial challenge for the device, but not specify a 'keyHandle' (i.e. it instructs the device to set up a new key pair).
* A 'bind' endpoint, which will bind the device's response to the registration challenge to the relevant user object in the API.
* A 'sign' endpoint, which will generate a challenge for the device - noting which device the challenge is for by including the key-handle for the device(s) stored against the user.  This generated challenge should be stored server-side, so the challenge response can be validated against it in a future request.
* Modifying the 'sign' endpoint to validate the device's response against the earlier generated challenge.

If TrustedCoin can implement U2F support via their API then adding support to Electrum should be quite simple, using Yubico's client library.  It would require some extra dialogues and requests back and forth to communicate with TrustedCoin for the registration and challenge processes, but - looking at the codebase - Electrum extendible enough to easily add that behaviour.

I hope I've been clear in my explanations here.  Please let me know if you have any questions.

Thanks,
RJ

**Comment by ecdsa** [comment]
I guess you need to submit that idea to TrustedCoin. Note that the point of using TrustedCoin is that their solution uses only software. If the user is willing to buy a physical device in order to secure their bitcoins, I suppose they might prefer to buy a hardware wallet.

**Comment by ecdsa** [comment]
@badmofo you may want to answer too

**Comment by badmofo** [comment]
@ecdsa He submitted the idea to us directly too but I only responded via email.  

I have a U2F device that I've toyed with before so I said I'd investigate adding it to the server API.  Support in the plugin looks like it would require a lot of dependent packages (which I can't realistically imagine you would be enthusiastic about bundling by default), but other than that it looks straightforward.  I'm happy to try my hand at adding it in a way where it only shows up if the user installs the extra packages.

All this being said, I largely agree with your hardware wallet point and I generally  haven't seen a lot of demand for U2F so this is pretty low priority.

**Comment by RJacksonm1** [comment]
Thanks for your comments; you both make complete sense.  I haven't toyed with hardware wallets before, but I am certainly aware they exist and the more optimum solution for securing coins with a physical device.

My desire for U2F support in Electrum came about primarily because I got a U2F security key via the recent Yubico/GitHub promotion, and it is such a more compelling and secure two-factor solution versus standard TOTP codes.  This got me wondering - what software/services do I use that utilise two-factor authentication, and that I could contribute my time towards adding U2F support to?

Electrum was my first thought, but implementing 2fa in Bitcoin requires multi-sig addresses, and so there's the dependency on a third-party, in this case TrustedCoin, to be the third signature and 2fa service provider.  That's not inherently a bad thing, it just means I can't implement it all on my own. :(

Anyway you're both right, this is a very low priority task.  I think it's still a good idea to offer a variety of methods to help users secure their coins, so I think there is value in having U2F support, but it's certainly not worth troubling yourselves over if there aren't a lot of people asking for it.

**Comment by ecdsa** [comment]
closing this
