### ISSUE TITLE
my wallet is blocked, doesn't work, i don't understand why

### ISSUE THREAD

**Issue by misterbenetnuts** [spesmilo/electrum#1485]
Please, can someone help me??

My wallet is blocked since yesterday.

When I bought bitcoins on bitboat, i don't know why, but 2 operations where written on my history board, whereas i only made one (the byement of my btc's).

Since this moment, my wallet is blocked, no transaction is possible.

What can i do???  Who can i tell this to help me???

Thank you.

**Comment by ecdsa** [comment]
was it twice the same operation?
do you have a screenshot?

**Comment by ecdsa** [comment]
it might be related to malleability; 
if the issue persists, restore your wallet from seed

**Comment by misterbenetnuts** [comment]
yes it was twice the same operation.

I have tried to restore my wallet gfrom the seed but it's also blocked.

What can i do??

CAn someone help me via teamviewer, or something else?

**Comment by abitfan** [comment]
Can you provide a screenshot ?

**Comment by misterbenetnuts** [comment]
yes
https://www.sendspace.com/file/wr15ck

**Comment by ecdsa** [comment]
well, before you report a bug, please update to the most recent version. 
screenshot shows that you used 2.1, which is really old.

**Comment by misterbenetnuts** [comment]
ok thank you i try it immediatly

**Comment by misterbenetnuts** [comment]
https://www.sendspace.com/file/pamngg

**Comment by ecdsa** [comment]
ok, this might be caused by the malleability issue.
can you explain what you mean by 'is blocked' ?
also, did you try to restore from seed AFTER the 2.5 update?

**Comment by kyuupichan** [comment]
So if you right-click on one of the pending ones, and view it on a block explorer, how many confirmations does it have?

**Comment by misterbenetnuts** [comment]
i try to restore now

**Comment by misterbenetnuts** [comment]
the same problem.

Can someone help me with a timeviewer session or something like that please?

**Comment by ecdsa** [comment]
can you email me your master public key, as well as the server you are using?

**Comment by ecdsa** [comment]
@misterbenetnuts in the python console, type this:
```ẁallet.clear_history``` and press enter
then restart electrum

**Comment by misterbenetnuts** [comment]
the python console is the terminal?

**Comment by ecdsa** [comment]
no, the 'console' tab in the GUI

**Comment by misterbenetnuts** [comment]
thank you soooooo much!!!
