### ISSUE TITLE
insight is an unreliable source of data

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum#1487]
It is not first time that https://insight.bitpay.com/ is off line. IMHO we remove that unreliable transactions data provider.

![screenshotsselection_007](https://cloud.githubusercontent.com/assets/231537/10559827/17e3bf0c-7523-11e5-90e6-bdc66e71d920.png)

**Comment by kyuupichan** [comment]
No one is forcing you to use it.  We should provide users the choice.
