### ISSUE TITLE
electrum commands not working 

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [spesmilo/electrum#1489]
none of the commands listed here no longer work: http://docs.electrum.org/en/latest/cmdline.html

pressing tab gives me a list of commands & /Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py has the rest of them

would much appreciate if some one updates the documentation and commands starting with electrum no longer function as of 2.5

EG: electrum help gives the following error:
>> electrum help
Traceback (most recent call last):
                ^
SyntaxError: invalid syntax

**Comment by ecdsa** [comment]
you are confusing console and terminal. "electrum help" is for the terminal
