### ISSUE TITLE
Can't send payments after upgrading to 2.5

### ISSUE THREAD

**Issue by gubatron** [spesmilo/electrum#1490]
Every time I try to send a payment, I enter my wallet password, it tries to sign the payment and after that window is closed I get this error popup.

<img width="460" alt="screen shot 2015-10-17 at 2 18 21 pm" src="https://cloud.githubusercontent.com/assets/163977/10560472/010339dc-74da-11e5-905d-a5908fe1948e.png">

**Comment by ecdsa** [comment]
which server are you using?

**Comment by ecdsa** [comment]
also, are you sure you upgraded to 2.5?

**Comment by ecdsa** [comment]
should be fixed in 19ec56b92310103ebe0e1f72e5e63913bdfb139b
I will make a bugfix release today
