### ISSUE TITLE
Porable executable 2.5 doesn't connect to any server

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#1491]
Electrum 2.5 windows portable executable doesn't connect to any server. It says Synchronizing... for > 3 hours. Tried with all servers, including ecdsa.net and my own server which I was logged in and saw electrum server was running fine up to date with 120 sessions. 

Enabled auto connect, still the same, Synchronizing... and stays like that.

If I try to change the server by clicking on the network tab and selecting a different server, it outputs Not connected and red dot instead of Synchronizing... and just stays like this. Maybe it has something to do with the networking thread updates. Tried with socks5 proxy, without, tried everything results are the same as described above.

**Comment by EagleTM** [comment]
Have you tried toggling SSL / non-SSL?  2.5 had an issue with non-ssl connections.
Please try 2.5.1 and let us know whether it helps

**Comment by gits7r** [comment]
2.5.1 works for both SSL and non-ssl apparently. I can switch between servers on the fly, it will just disconnect and reconnect fast. Tried with socks5 proxy and without, both seam to work and changes are persistent after I close electrum and start again. This is expected an wanted behavior, so it's good. Closing this.
