### ISSUE TITLE
Better formatting

### ISSUE THREAD

**Issue by stefment** [spesmilo/electrum#1493]
Hello,

I was wondering if you have any plans to increase formatting. I have a few examples here that show how it can be messed up if you use bits. I know bits is not really an official denomination yet, but i still prefer using it.

Anyway, do you think there is a way to have better formatting so the amounts are easier to understand?

[Imgur](http://i.imgur.com/9Uxm6T4.jpg)

[Imgur](http://i.imgur.com/SHEL14M.jpg)

**Comment by ecdsa** [comment]
you already opened an issue on this #1388 
why do you open a new one?
