### ISSUE TITLE
Error importing private key with 2.5.1

### ISSUE THREAD

**Issue by NiExTy** [spesmilo/electrum#1494]
It was working in 2.0 and is not working after upgrading to 2.5.1.

**electrum create**
> Error: Cannot read config file. /home/user2/.electrum
> Password (hit return if you do not wish to encrypt your wallet):
> [...]
> Your wallet generation seed is: XXX
> Please keep it in a safe place; if you lose it, you will not be able to restore your wallet.
> Wallet saved in '/home/user2/.electrum/wallets/default_wallet'

**electrum deseed**
> Error: Cannot read config file. /home/user2/.electrum
> Warning: you are going to create a seedless wallet'
> It will be saved in '/home/user2/.electrum/wallets/default_wallet.seedless'
> Are you sure you want to continue? (y/n) y
> Done.

**electrum importprivkey XXX**
> Error: Cannot read config file. /home/user2/.electrum
> "Error: This wallet cannot import private keys"

Trying same with -w flag is giving the same error.

**Comment by dabura667** [comment]
Individual private keys were relegated to a separate wallet file type.

You need to create a new wallet and select "Imported private keys" then paste one or multiple (separated by line break) WIF private keys, and a new wallet file is created.

I haven't used cli electrum for so long, not too sure how that would work.

**Comment by NiExTy** [comment]
Unfortunately GUI version is not an option. I would like to know if it is still possible with latest version and command line only.

**Comment by dabura667** [comment]
> electrum create

This can not create a private key wallet from cli currently. However, you could hard-code (or store somewhere) a blank private key wallet file, and instead of "electrum create" you could just copy that blank wallet template into the electrum folder, then import from cli (which still works)

A blank wallet is below.

```python
{
    "accounts": {
        "/x": {
            "imported": {}
        }
    }, 
    "accounts_expanded": {}, 
    "pruned_txo": {}, 
    "stored_height": 379471, 
    "transactions": {}, 
    "txi": {}, 
    "txo": {}, 
    "use_encryption": false, 
    "wallet_type": "imported"
}
```

The steps would be 1. Copy the above wallet and name it default_wallet 2. run electrum importprivkey XXX from cli 3. After importing, you might want to add a password using the password command.

**Comment by ecdsa** [comment]
unfortunately there is no wat to create an imported wallet from command line.
you can do what @dabura667 said.
a blank wallet only needs to contain this:
{  "wallet_type": "imported" }

**Comment by NiExTy** [comment]
That did work. But wallet functions are not working e.g. ```listunspent``` and ```getbalance``` are not showing correct information.

```mkdir -p .electrum/wallets```
```echo '{ "wallet_type": "imported" }' > .electrum/wallets/default_wallet```

#### electrum importprivkey XXX
> "Keypair imported: XXX"

#### electrum daemon start
> starting daemon (PID 9921)

#### electrum getbalance
> {
>     "confirmed": "0"
> }

That data is only updated once GUI is started and then stays unchanged when queried from command line despite having new incoming transactions.

**Comment by ecdsa** [comment]
you are right. I will fix that.

**Comment by ecdsa** [comment]
the restore command was changed.
you need to pass the seed (or list of addresses) as a parameter
example:

`./electrum restore 1NMYBdZhG3drLP4YFeLFpehjevVnt7agEL`

if you dont want to display your seed, use:

`./electrum restore : `
