### ISSUE TITLE
error: {u'message': u'64: non-mandatory-script-verify-flag (No error)', u'code': -26}

### ISSUE THREAD

**Issue by OldMike** [spesmilo/electrum#1495]
Hi,

Just installed a Fresh Manjaro system and imported my wallet. When trying to send some BTC I got this error.
Fees are dynamic, tried with/out Tor gateway.

EDIT: Mybad... Updated Electrum to the Git version. It's okay.

**Comment by gits7r** [comment]
The old class was being used for transaction signatures. This was fixed, subject of  #1490 and included in the 2.5.1 release.
