### ISSUE TITLE
Lost 120$ !!!!

### ISSUE THREAD

**Issue by 3amunyk** [spesmilo/electrum#1496]
I send 120 $ http://storage5.static.itmages.com/i/15/1018/h_1445193119_1648572_5e2d86d645.png
From my wallet http://storage9.static.itmages.com/i/15/1018/h_1445193164_4738563_0090a88ee2.png
To wallet my friend 15pLrnSPrrfBRxQf4wHnopH4z6Q8CAoTbE
But !!! This is transaction does not exist !!!! https://blockchain.info/ru/address/167K7BJCPoCUnSUHk2yxGx98FepftYekZA 
My BTC send in 1PiM2JhjeGy4vjHWGNazDBEth9rnuaSqPz adress - who this ?? 
https://blockchain.info/ru/address/1PiM2JhjeGy4vjHWGNazDBEth9rnuaSqPz
Where is my money ????

**Comment by ecdsa** [comment]
your transaction is here:
https://blockchain.info/ru/tx/cdb3c6b811dc5cb1cc999656934a1eaef67149eb5114bd8b8a91f4236531b2d2

**Comment by 3amunyk** [comment]
After my post, transaction appeared. Sorry !
