### ISSUE TITLE
Messy edit textbox in history tab 

### ISSUE THREAD

**Issue by petrkr** [spesmilo/electrum#1500]
There is problem with fonts while editing history, they are overlapping with original text. In 2.4.4 it was fine, so it must be connected with some UI change.

Tested in 2.5.1

![image](https://cloud.githubusercontent.com/assets/6428351/10571950/102da850-7644-11e5-924a-868f222c76a0.png)

![image](https://cloud.githubusercontent.com/assets/6428351/10571971/42eae924-7644-11e5-9ce3-1c40e8b1b243.png)

![image](https://cloud.githubusercontent.com/assets/6428351/10571983/55a1dbc2-7644-11e5-800c-e365aaf0cd61.png)

**Comment by ecdsa** [comment]
are these screenshots? I cannot reproduce that

**Comment by ecdsa** [comment]
also, which OS is it?

**Comment by petrkr** [comment]
It is arch linux with qt4 and qt5, which one is used by pyqt do not know now.

I will provide more info after i'll be on laptop

**Comment by petrkr** [comment]
[petrkr@petrkr-dell ~]$ python2
Python 2.7.10 (default, Sep  7 2015, 13:51:49) 
[GCC 5.2.0] on linux2


extra/python2-pyqt4 4.11.4-2 [installed: 4.11.4-1]

**Comment by petrkr** [comment]
Looks it's some my problem, probably in same time when I updated electrum, It must also update something, because other QT applications do same, I just recognized it now...
