### ISSUE TITLE
electrum ignores umask

### ISSUE THREAD

**Issue by a3nm** [spesmilo/electrum#1502]
Hi,

electrum sets the permissions of its wallet file to 006 (user-readable and user-writeable), no matter what its umask is. This happens here https://github.com/spesmilo/electrum/blob/master/lib/wallet.py#L136

I understand that in most cases this is the right thing to do. However, I run electrum as its own user and would like my regular user to be able to access its files, which I would accomplish by putting it in electrum's group, and setting electrum's umask to make its files readable by the group as well.

Sadly, I cannot do this because electrum ignores umask. Would it be possible to add a setting or option of some sort to ask electrum not to mess around with file permissions?

**Comment by ecdsa** [comment]
this should fix it a9f451decd3d967ab3e6199999ba02acee9e816b

**Comment by a3nm** [comment]
Great, thanks a lot! :)
