### ISSUE TITLE
Electrum 2.5.1 does not start on Windows 7

### ISSUE THREAD

**Issue by Sasha000** [spesmilo/electrum#1505]
Hello all!
I have a problem. I used a client electrum version 2.4.4 and everything was fine until recently when trying to send the transaction did not occur here such error:

http://s010.radikal.ru/i312/1510/bf/8e71a757efad.jpg

I went to the website and download the latest version of electrum - 2.5.1. I remove the old version by uninstaller and set a new one. But the new version of the client does not start. After clicking the mouse on the icon client window appears on the one second and disappears. My system Windows 7. Help please!

**Comment by ecdsa** [comment]
I will have to investigate, which might take a while. If you have an urgent need to access to your coins, reinstall the 2.4.4 version (it is still available on the website) and use a server that still accepts high-S transactions (such as ecdsa.net).

**Comment by Sasha000** [comment]
Hi! I went back to the old version. You've already figured out what was my problem?

**Comment by ecdsa** [comment]
not really. is there a way you could run Electrum in a console, and see what the error message is?

**Comment by Sasha000** [comment]
How can I do that?

**Comment by Sasha000** [comment]
I have a new problem. When I want to send a transaction error "incorrect size of the commission." I connected to the server ecdsa.net

Screen: http://s020.radikal.ru/i703/1510/1f/ed264af50924.jpg

**Comment by Sasha000** [comment]
No server from the list does not accept transactions from my client version 2.4.4 and version 2.5.1 is not started of my computer. Previously, the transaction took ecdsa.net server but now he writes, "is not the correct size of the commission." I tried to put the commission manually 0.0001 btc for 1k byte, tried to specify the size automatically Committees but none of this helps.

I have reinstalled the operating system to run the client version 2.5.1 the program offers to restore my old purse from a seed, and i enter the seed I have introduced the program immediately closed and stopped running. My money is stuck on the purse Electrum. Help me please!

**Comment by virus70** [comment]
me and my friend have the same problem version 2.4.4 above, none does not start when you start the program pops up a window and immediately disappears and the version 2.4.4 is no longer supported translations and our money stuck in purses can not do anything we please establishing windose 7 Please help me thank you

**Comment by Sasha000** [comment]
I'm sorry, you decide my problem? I have to wait long.

**Comment by Sasha000** [comment]
Help me!

**Comment by s0metea** [comment]
Hello. I had the same problem on Windows 10. Electrum window immediately disappears. Attempt to build client from sources caused the same result.
My solution for using Electrum on Windows — run VirtualBox with Windows XP, install Electrum and restore wallet using my seed. It's works for me.

**Comment by ecdsa** [comment]
@Sasha000 can you try the 2.7 binaries and check it it works now?
I tested tem on Windows10, they work for me

**Comment by ecdsa** [comment]
closing, no answer
