### ISSUE TITLE
invalid lines

### ISSUE THREAD

**Issue by MARUSICH99** [spesmilo/electrum#1508]
try to send coins from eectrum wallet cant keeps saying invalid lines

**Comment by ecdsa** [comment]
try to fix the address you entered, or post a screenshot of the error

**Comment by MARUSICH99** [comment]
![1021151024a 1](https://cloud.githubusercontent.com/assets/15233482/10641379/a56cd0f8-77de-11e5-958b-8d938ec9c721.jpg)
not sure how to get screen shot here but is not  wrong address

**Comment by MARUSICH99** [comment]
any help would be greatly appriceated

**Comment by ecdsa** [comment]
I suppose the bitcoin address is incorrect. 
the error message should be more informative.

**Comment by MARUSICH99** [comment]
ive tried two separet addresses im sure there right how do i view error message

**Comment by MARUSICH99** [comment]
oh i see what ur saying sorry any idea at all on what i could do

**Comment by ecdsa** [comment]
I typed it manually, to check: 1Hcd81d8XUBVZYMBKvKMJ2yyfubVeX5zPi
This is not a valid address.
