### ISSUE TITLE
The exchange rate for BitcoinVenezuela shows Cannot convert None to Decimal

### ISSUE THREAD

**Issue by rdymac** [spesmilo/electrum#1510]
In this line https://github.com/spesmilo/electrum/blob/master/plugins/exchange_rate.py#L113

```
def get_rates(self, ccy):
        json = self.get_json('api.bitcoinvenezuela.com', '/')
        return dict([(r, Decimal(json['BTC'][r]))
                     for r in json['BTC']])

```
Electrum shows this error when running with -v tag: `<Notice>: [BitcoinVenezuela] failed fx quotes: Cannot convert None to Decimal`

**Comment by kyuupichan** [comment]
This is because they've added LTC and messed up the JSON served

**Comment by rdymac** [comment]
The LTC price has always been there. The only thing that have changed it the LTC price is broken.

**Comment by rdymac** [comment]
is* the LTC price is broken == null

**Comment by rdymac** [comment]
Fixed
