### ISSUE TITLE
No Trezor support on OS X with Electrum 2.5.0 - 2.5.1 builds

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1512]
For some reasons the Trezor plugin is not present in the latest Trezor OS X executable builds.

<img width="552" alt="capture d ecran 2015-10-23 a 14 18 02" src="https://cloud.githubusercontent.com/assets/721759/10692321/11e26e88-7991-11e5-894b-d8d4ad39a694.png">

**Comment by murder77** [comment]
Probablly is OS server, man.

2015-10-23 7:20 GMT-05:00 Thireus ☠ <notifications@github.com>:

**Comment by ecdsa** [comment]
that dialog does not show hardware wallet plugins anymore.
it does not mean trezor is not supported.
