### ISSUE TITLE
2.5.1 never ends "Broadcasting transaction..."

### ISSUE THREAD

**Issue by gubatron** [spesmilo/electrum#1513]
perhaps there should be a timeout there (or maybe there's one and I have not hit it in ~30mins of waiting)

<img width="369" alt="screen shot 2015-10-23 at 3 42 12 pm" src="https://cloud.githubusercontent.com/assets/163977/10703287/f4a32374-799c-11e5-96f8-2be2403cf648.png">

and just so you don't doubt I'm on 2.5.1 again...
<img width="443" alt="screen shot 2015-10-23 at 3 42 26 pm" src="https://cloud.githubusercontent.com/assets/163977/10703293/0052f17c-799d-11e5-8578-9f5ba877cc43.png">

**Comment by gubatron** [comment]
(sucks to miss a trade because of this btw.)

**Comment by ecdsa** [comment]
this happens because the user is not connected.

**Comment by ecdsa** [comment]
same here: https://bitcointalk.org/index.php?topic=1171319.0

**Comment by ecdsa** [comment]
and here: https://www.reddit.com/r/Bitcoin/comments/3qiira/why_is_my_electrum_wallet_not_sending_funds/

**Comment by ecdsa** [comment]
@kyuupichan I believe this is caused by the changes you made to network.py and interface.py
network.send does not raise an exception when the connection is down

**Comment by gubatron** [comment]
Thank you!

**Comment by thor-the-norseman** [comment]
Seems to be doing this still on Mac OS X. I left the client open for a few days, bringing my laptop around, putting it asleep, waking it up, and Electrum kept showing the green dot whenever I checked it, so I figured nothing was wrong. But it got stuck on "Broadcasting transaction" when I eventually tried to carry out a transaction. I'm using version 2.5.4.

**Comment by ecdsa** [comment]
there's a timeout now in the code.
it will be in version 2.6
