### ISSUE TITLE
able to restore a wallet with seed from words not in wordlist

### ISSUE THREAD

**Issue by grg2rsr** [spesmilo/electrum#1516]
Hi,
stumbled over a potential bug as I am unable to restore my wallet with my seed. Quick search suggested that my seed contains words which aren't in the word list, which is not the case, and I am quite sure my seed is correct.

I started playing around a bit and found that using the first 13 words from the  wordlist (https://github.com/spesmilo/electrum/blob/master/lib/wordlist/english.txt) _plus the first letter of the 14th word_, so seed is

> abandon ability able about above absent absorb abstract absurd abuse access accident account a

can generate a wallet:

> Password (hit return if you do not wish to encrypt your wallet):
seed:abandon ability able about above absent absorb abstract absurd abuse access accident account a
Recovering wallet...
1FaLeLoxz3ip9BbEA8jJPfFTNAo5ec9MbN
1MvKgyJpCcsAxgkkZCc4GuCZeMwsB9ns24
1FZ7EKRatNJ34AKUqzye92xUHDeMtYLMR5
17U2rJkKNZaHNsG6S2WBcr6sRrEPUnkZ92
1AocKeNbQMwieaUVrePmqhEuZ4zG86Mqr3
12Dq1GBvL15P1XGkxGofASbfjnbUFVPpwd
1Lkynnwd7DmxmZ9uwaosjYkwjJUe6H5mSX
1LhVG9nsHUafhyZpPnCkmXzj5bRfEQbDNL
16aAAtbqk2yUebF6SWYx4Sp4Kp43oRnZPV
1KhNhW5XtfRSEAxNDfrHNpErRNS9LoJiXH
1Cz4xNuVeoBjQJNhRAfR7sjFQSwSKbxX3E
12NN2PHZ7ZTKxbDGxTadzkBdWJEHS3nQzu
1JYG8ACegMMg3VCePRmi5u787vSHT7wtpq
1B9rjFu5ANLyd8P55oJ6TGia561x9C2fsv
1ATibp4An19swAoTsxyRamqi1cPJsyBYmJ
1NQvhFoKqnvFSCQ5nUwPikCjWbZ7LnFNAt
1HbJ36TCq1qqZ9MYtAdY2cLmtsbjcXHJka
13MEnGB8CotzkLsvQnWL1qUdSfS7uZ3ipH
1BCAoxQsCczPd9jeRs4KAR5gE1xQAJfKxg
16b1mrkieZPyNKcSmbFfhaffzrtRmNGJad
1GxtwWwyQbXuiDxNsLiDz9Qa4jdD9SDhGC
1MtfDgeXx12TPiVQ2xSyobY4VcpeucfyyX
1MikCnKR3ZFymYb1GFtXQed2jWYKNarXDA
1KeLrk7jUSnqJL3ZXuoDdLqsyQG1YntMpR
1LqaS4UXAq6cw2odHx2VhxKF49tLtPhqip
1Kj8iGnjXC6supBjfTnQUY4HS96HJdvSeG
Warning: Found no history for this wallet

this seed contains 14 words and `a` is not in the seed list. Potential bug?

I am using electrum version 2.5.1, on Ubuntu 14.04, installed via
`sudo pip install https://download.electrum.org/Electrum-2.5.1.tar.gz`

link to a thread I opened at  bitcointalk: https://bitcointalk.org/index.php?topic=1219223.0

thanks for your help

**Comment by ecdsa** [comment]
This is not a bug; you can restore from any string that has the correct checksum.
PTPH, if you cannot restore from a string seed, it does mean that that string is not a valid seed.
