### ISSUE TITLE
URI links don't work in windows.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#1518]
Hard to believe this can still be an issue at this point.

I must be missing something, I see URI as a feature but it doesn't work on windows 

Did an install with the installer and use chrome/opera to click a bitcoin: URI . Nothing happen.

**Comment by ecdsa** [comment]
I don't think this has ever been added to the windows installer. 
I know how to do it, btw.

**Comment by Transisto** [comment]
Is is something that is hard to add to the code ? I don't need that feature this much but think it would facilitate adoption, reduce amount typo mistakes and "maybe" even thwart clipboard replacing attacks.

Could someone who know the work required to add this suggest me a bounty to put toward this effort ?

**Comment by Transisto** [comment]
How to manually add Electrum as bitcoin: application ?

**Comment by dabura667** [comment]
```bash
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\bitcoin]
@="URL:Bitcoin Protocol"
"URL Protocol"=""
"UseOriginalUrlEncoding"=dword:00000001

[HKEY_CLASSES_ROOT\bitcoin\DefaultIcon]
@="electrum-2.2.exe,1"

[HKEY_CLASSES_ROOT\bitcoin\shell]
@=""

[HKEY_CLASSES_ROOT\bitcoin\shell\open]
@=""

[HKEY_CLASSES_ROOT\bitcoin\shell\open\command]
@="\"D:\\Users\\dabura667\\Downloads\\electrum-2.2.exe\" \"%1\""
```

Change the path in the last one to reflect the location of your electrum exe file (remember to use double \\ for the path) and change the name of the exe file for the DefaultIcon thing.

Then save this as a text file and change the extension from "txt" to "reg". Then double click the reg file.

**Comment by Transisto** [comment]
I tried this with the portable version, I've let it create a new wallet which went to C:\Program Files (x86)\Google\Chrome\Application\46.0.2490.80\electrum_data

When clicking URI link it seems like it's ordering the wallet to add a label to an address, no transaction.

**Comment by dabura667** [comment]
> It work , thanks !

Great to hear!

> C:\Program Files (x86)\Google\Chrome\Application\46.0.2490.80

That must be where the exe file is stored, as the portable versions just create electrum_data folder in the same folder as the exe. If you use the Install version it will create a folder in your user's Appdata.

**Comment by Transisto** [comment]
>  That must be where the exe file is stored, as the portable versions just create electrum_data folder in the same folder as the exe. If you use the Install version it will create a folder in your user's Appdata.

My portable .exe is in some c:\folder\  Electrum should be able to locate itself and find his /data/, The scary part is that there are multiple /46.0.2490.86../ so could that wallet file get crushed with a chrome update. ? 

Also in my URI format I was using label: as a label for the transaction. It is wrong, should be decription: but electrum really doesn't handled these well.  When I click the link elctrum launch and ask me to approve the addition of said label to receiver address, If I click YES Electrum shuts down. If I chose NO, URI information get populated in the fields and label get added anyway. 
![image](https://cloud.githubusercontent.com/assets/388716/11168457/ee549638-8b5d-11e5-9ff2-eeba76bba5e7.png)

**Comment by Transisto** [comment]
When using the installer version of windows with this, every time I click an URI it open a new electrum, and the other electrums do not connect to the Trezor.

**Comment by ecdsa** [comment]
@dabura667 is there a way to add this to the install script?

**Comment by ecdsa** [comment]
@Transisto I believe this has been fixed in windows binaries. can this issue be closed?

**Comment by ecdsa** [comment]
PR #1708 should have fixed it, closing. issue #1732 remains.
