### ISSUE TITLE
UI Errors on Ubuntu 15.10

### ISSUE THREAD

**Issue by Levino** [spesmilo/electrum#1521]
Hey there, the GUI seems to be broken on Ubuntu 15.10 for me. Getting these of errors in the console:

```
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0

```

**Comment by ecdsa** [comment]
which plugins/options are active in your config?

**Comment by Levino** [comment]
Should be vanilla. Would appreciate guide to remove them all.

**Comment by ecdsa** [comment]
just untick all plugins (or remove your config file)

**Comment by Levino** [comment]
did an
```
rm .electrum/config
```
in my home folder. Same result.

**Comment by ecdsa** [comment]
Thanks. did you recently upgrade to 15.10? is the issue caused by that upgrade?

**Comment by Levino** [comment]
Kinda. It crashed my system so I took a boot usb stick and had 15.10 replace it all. Everything else works fine and I had to reinstall everything (but not electrum, funnily enough)

**Comment by Levino** [comment]
I tried to reinstall electrum with pip already.

**Comment by ecdsa** [comment]
This is probably not an Electrum issue, but something wrong with your update.
Try to see if other pyqt applications are affected.

**Comment by camponez** [comment]
Same problem here.

It looks like that it's related to the upgrade, but I can't figure out what.

I don't know if I have any other pyqt application to test :/

**Comment by ecdsa** [comment]
can you check how old are the .pyc files in your electrum dir? 
maybe they need to be recompiled, and this forced it

**Comment by ecdsa** [comment]
@camponez : Did the problem arise in the same conditions (upgrading ubuntu or qt) ?

**Comment by camponez** [comment]
The problem arise after Ubuntu upgrade from 15.04 to 15.10

**Comment by ecdsa** [comment]
ok, can you check how old are the .pyc files in your electrum dir?

**Comment by camponez** [comment]
They are all from "now".

I did the electrum upgrade today. It also worked. So unfortunately, I don't think it means much any more.

**Comment by Levino** [comment]
I can check later.

**Comment by ecdsa** [comment]
cosing this; I believe it's a Qt issue, it cannot be fixed it in Electrum

**Comment by Levino** [comment]
Agreed

**Comment by Levino** [comment]
For reference: I missed the first lines complaining about out of space issues. This is probably what is behind all of it: http://stackoverflow.com/questions/33469060/python-error-message-in-pycharm-unable-to-attach-to-shared-memory-segment

**Comment by webloem** [comment]
Just had the same problem after brand new installation on 15.10. Reboot solved the problem.

**Comment by Levino** [comment]
For reference: My problem occurs when I run Webstorm. It takes all the shared memory. I think electrum should handle the situation better. Here is a link where I found the solution: http://askubuntu.com/questions/696323/qt-interfaces-broken/697034
