### ISSUE TITLE
jsonrpc: listrequests / addrequest problem

### ISSUE THREAD

**Issue by dotpack** [spesmilo/electrum#1523]
> curl --data-binary '{"id":"curltext","method":"listrequests"}' http://127.0.0.1:7777
{"jsonrpc": "2.0", "result": [], "id": "curltext"}

> curl --data-binary '{"id":"curltext","method":"addrequest","params":["0.005"]}' http://127.0.0.1:7777
{"jsonrpc": "2.0", "result": {"status": "Unknown", "amount (BTC)": "0.005", "memo": "", "time": 1446066341, "exp": 3600, "address": "SomeAddress", "id": "SomeId"}, "id": "curltext"}

> curl --data-binary '{"id":"curltext","method":"listrequests"}' http://127.0.0.1:7777
{"error": {"message": "Server error:   File \"/workspace/electrum/lib/commands.py\", line 534, in _format_request | KeyError: 'amount'", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}

**Comment by ecdsa** [comment]
are you using 2.5.2?

**Comment by dotpack** [comment]
Yes, I do. Probably,  should use "out.pop()" instead "out.get()":
https://github.com/spesmilo/electrum/blob/511b23fee6940681701ef83950fdd8f95b0bd9e8/lib/commands.py#L534

**Comment by ecdsa** [comment]
ok, you are right. good catch
