### ISSUE TITLE
problem google  Authenticator

### ISSUE THREAD

**Issue by pattygreen** [spesmilo/electrum#1526]
I changed mobile phone and I installed google authenticator on my new phone, but now it doesn't work with electrum. The transaction is always partially signed.
Solutions?

**Comment by ecdsa** [comment]
In principle you can extract your secret key from google auth, and use it on the new device.
However, that looks very complicated (see http://dpron.com/3-ways-to-move-google-authenticator/)

If you don't feel like doing that, the easy method is to restore your wallet from its seed, and to send all your coins to a new wallet.
