### ISSUE TITLE
Electrum starts in offline mode with the networking pop-up broken in Tails (Debian Wheezy) sometimes, sometimes not.

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#1531]
@ecdsa I have reproduced what we were talking about on IRC in a vm and documented it step by step with screenshots and everything. the config file in ~/.electrum is not the issue, it breaks with a good one (generated by electrum itself) and with it missing as well. Please see:

http://www.sky-ip.org/electrum/

If it has the blockchain_headers file in ~/.electrum it will start OK apparently. See all the steps there and the comments at the bottom of the page.

**Comment by ecdsa** [comment]
this commit should fix it.
note that the network dialog will be shown if no configuration file exists.
