### ISSUE TITLE
Electrum 2.5.2 for android doesn't start: ImportError: No module named plugins

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#1532]
Android Lollipop (latest); sl4a and python latest (recommended on electrum.org). Error:
ImportError: No module named plugins

Screenshot:
![android](https://cloud.githubusercontent.com/assets/6549887/10853702/0f82ea1e-7f40-11e5-8ea2-fdb2c8b14458.png)

**Comment by ecdsa** [comment]
fixed. thanks
