### ISSUE TITLE
"Ledger device not detected."

### ISSUE THREAD

**Issue by LukAss741** [spesmilo/electrum#1535]
Hi. If I close my ledger nano wallet in Electrum and then reopen it then it returns "Ledger device not detected. Continuing in watching-only mode." To get it working again I need to close the whole electrum and start it again.

**Comment by ecdsa** [comment]
@btchip I think it is because the btchip plugin lacks a close_wallet method (see trezor plugin)

**Comment by kyuupichan** [comment]
I added a close_wallet method.  Did this solve the problem?  It's not in a release but it is in git HEAD.

**Comment by kyuupichan** [comment]
Closing - no response from OP; believed fixed in 2.6 with close_wallet method.
