### ISSUE TITLE
I use electrum wallet several withdraws I made never appeared but did disappear from wallet

### ISSUE THREAD

**Issue by shakar0178** [spesmilo/electrum#1536]
now I just made a withdraw for a payment and now it says unverified with -1 confirmations? what is going on I have lost over half a btc using electrum plz help and I have made 3 withdraws that never appeared where I sent what is going on?

**Comment by ecdsa** [comment]
which version of Electrum are you using?
what is the transaction ID of the transaction?

**Comment by shakar0178** [comment]
version 2.5 and Ive had 2 .3 transactions disappear they would appear as pending deposits but cant be confirmed.

**Comment by shakar0178** [comment]
8d04f45da879cbcc50a6e7b4821a1cc5e3c14b6c924a71aafc24ebadbd3357c4

**Comment by shakar0178** [comment]
That is one of the trans ids somebody plz find out what happened.

**Comment by ecdsa** [comment]
that transaction is in the blockchain.
first, upgrade Electrum to latest version.
Then, if that does not fix it, in the python console, type "wallet.clear_history()", then restart your client

**Comment by shakar0178** [comment]
what do you mean its just floating in the BC?

**Comment by ecdsa** [comment]
I'm saying that the transaction is confirmed.

**Comment by ecdsa** [comment]
is that issue resolved? did you follow my instructions ?

**Comment by shakar0178** [comment]
Hey sorry Ive been busy. Yes I followed your instructions but I still do not have my missing btc. I am now using electrum version  2.5.2 any more suggestions? plz

**Comment by ecdsa** [comment]
you are not providing enough information for me to understand your situation.
what is the issue? is the failing transaction a deposit or a withdrawal?

**Comment by shakar0178** [comment]
It was two different deposits at two different markets. It showed up as a pending deposit in account then stayed that way. I contacted support and they both said the deposits could not be confirmed or fraudulent.

**Comment by shakar0178** [comment]
I guess they just felt like keeping them?

**Comment by ecdsa** [comment]
ok, let's use different words: are you having difficulties to send money from your Electrum wallet, or to receive it in your Electrum wallet? 
can you give the transaction IDs, or provide screenshots?

**Comment by shakar0178** [comment]
All information is above thank you

**Comment by ecdsa** [comment]
ok, in the absence of extra information, I can only assume that you created a transaction that did not get confirmed. I do not have enough information to know why.

To prevent this from occuring again, make sure you pay enough fees when creating a transaction, and do not create transactions that are too large (with lots of inputs)

**Comment by shakar0178** [comment]
no I never got it back I guess someone did I got scammed I guess

**Comment by shakar0178** [comment]
I sent btc to marketplace account it appeared as a pending transaction then
was canceled they said it was fraudulent somehow ?

**Comment by shsmith** [comment]
Did you intend to send 0.3 BTC to 1LnhseJMgLmyyeH1Ra6YmnxZUas5gc5QJT?
The tx you quoted shows 0.3 sent to that address.
If that is not what you wanted, please tell us what you DID want. 

If the owner of 1LnhseJMgLmyyeH1Ra6YmnxZUas5gc5QJT claims they did not receive 0.3 BTC, they are not telling the truth.

You have not given any proof that you sent this transaction. As far as we know, you just picked that tx at random from blockchain.info.  You CAN prove it though, by signing a message using the input address 1EVdgVyBVDjx9qFdcRgHoVCnNid8GQ2zBk (which has to be in your wallet if you are the sender).
