### ISSUE TITLE
Money no longer appearing in wallet 

### ISSUE THREAD

**Issue by ctt1** [spesmilo/electrum#1537]
I am using electrum 1.9.8 on tails.  I transferred  Point to bitcoins into my electrum wallet, it appeared pending, then it confirmed. My computer shut down, and I went to recover the wallet with my seed, in the wallet recovered. However, none of my funds  have appeared in my account, nor any information in my receiving tab where my address should be. I've lost about $80, what can I do?

**Comment by ecdsa** [comment]
first, upgrade to the latest version of Electrum.
second, did you ever modify the gap limit setting?

**Comment by ecdsa** [comment]
does the recovered wallet display some transactions, or is the history completely empty?

**Comment by ctt1** [comment]
How do I upgrade inside of tails? I dont have persistent volume and am unable to get it, so im sure if i will be able to. Also the recovered wallet shows no history at all, however where i sent the bitcoin from shows the transaction was completed

**Comment by ecdsa** [comment]
if the recovered wallet has no history, then you made a typo writing down your seed.
