### ISSUE TITLE
Stdio and text GUIs can't create transactions

### ISSUE THREAD

**Issue by jurov** [spesmilo/electrum#1538]
Any attempt to create outgoing transaction in stdio/text GUIs fails with 

> ValueError: 'need more than 2 values to unpack'

in wallet.py make_unsigned_transaction() at line:

> for type, data, value in outputs:

My analysis so far is that it expects the outputs elements be ("address",address,amount) and Qt gui supplies that. Text and stdio GUIs provide only (address, amount) data.

**Comment by ecdsa** [comment]
indeed

**Comment by jurov** [comment]
Fixed in pull #1539 .
