### ISSUE TITLE
Feature request: Importing wallet.dat from bitcoin-core

### ISSUE THREAD

**Issue by nomnombtc** [spesmilo/electrum#1540]
Hello,

I see a lot of posts lately where people have problems getting up and running again after beeing away some time with bitcoin-core (long sync etc). 

Instead of telling them to export the private keys and use another wallet, it would be nice if electrum had the option to sweep a wallet.dat from bitcoin-core. 

I think this could be easily done with parts from https://github.com/jackjack-jj/pywallet maybe, but I am not a programmer so sadly I can't attach any code.

Greetings

**Comment by ecdsa** [comment]
I don't think it is a good idea.
it would encourage people to keep using their non deterministic wallets

**Comment by nomnombtc** [comment]
Hmm true. I did not think about this, maybe as a sweeping import then so it
creates a transaction to an address from the hd seed?

I just thought it would be good to have, because I had seen a link to blockchain.info ( I have never used it so I don't know if that even still works )  which seems to have an import function like that: https://blockchain.info/wallet/import-wallet

**Comment by ecdsa** [comment]
wont fix (out of scope)
