### ISSUE TITLE
Transaction pending 36 hours+ and sync issues

### ISSUE THREAD

**Issue by obroc** [spesmilo/electrum#1541]
I am running Electrum 2.5.2 and I tried to send a transaction over 36 hours ago, still pending.  I was running 2.3.x when I initially tried sending the transaction but have since updated in an attempt to fix the issue.  The dollar to bitcoin rate listed at the bottom has 1 BTC worth over $600, making me think there is a syncing issue.

I also saw it display server lagging (2 blocks) in the past, but restarted my PC and haven't seen it since.  Any advice would be much appreciated.

**Comment by ecdsa** [comment]
probably a high S transaction. 
connect to ecdsa.net, and that transaction should be gone.

**Comment by obroc** [comment]
Perfect, thank you for your help!
