### ISSUE TITLE
minimum window dimensions are too big

### ISSUE THREAD

**Issue by DavidGriffith** [spesmilo/electrum#1542]
The minimum dimensions of the Electrum window are too big to neatly tile with xterms.  Is there any particular reason why the minimums are set the way they are?

**Comment by ecdsa** [comment]
no real reason.
removed in 798664e299d79315ab876271591e2c7dd8eb1b9e

**Comment by kyuupichan** [comment]
I think one of the tabs, perhaps the receive tab, doesn't look good or has other issues IIRC at smaller dimensions.
