### ISSUE TITLE
Transaction doesn't exist

### ISSUE THREAD

**Issue by asbator** [spesmilo/electrum#1545]
Transaction went away and gone.
Still visible as pending though, see attachment

I'm trying to make it 4th or 5th time over last two weeks,
it just doesn't work.

**Comment by ecdsa** [comment]
this transaction is very large (296 inputs)
try to make smaller transactions.

**Comment by asbator** [comment]
OK, now i understand.
But how? It is stuck now.

**Comment by ecdsa** [comment]
find a server that does not have the transaction in its memory pool, and double spend it

**Comment by asbator** [comment]
Thank You!
