### ISSUE TITLE
getbalance from command line ignores -w

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1546]
It returns the balance of default_wallet

**Comment by kyuupichan** [comment]
My confusion; the -w must come after the command not before it.

**Comment by ecdsa** [comment]
it should work in both cases

**Comment by kyuupichan** [comment]
OK, then I've reopened it.  I'm on 1525 at present.

**Comment by kyuupichan** [comment]
This problem seems to happen for many commands; e.g. ismine, getbalance etc.  The -w is ignored before the command and correctly processesed if after the command

**Comment by kyuupichan** [comment]
Note I don't have a .electrum/wallets/default_wallet:

neil@zotac:~/src/electrum$ python2.7 ./electrum -w mywallet ismine 1BitcoinEaterAddressDontSendf59kuE
Error: Wallet file not found.
Type 'electrum create' to create a new wallet, or provide a path to a wallet with the -w option
neil@zotac:~/src/electrum$ python2.7 ./electrum ismine  -w mywallet 1BitcoinEaterAddressDontSendf59kuE
false
neil@zotac:~/src/electrum$

**Comment by ecdsa** [comment]
what is your version of argparse?

**Comment by kyuupichan** [comment]
How do I determine that?  I believe it's builtin.  I'm using Python 2.7.10 as reported by python --version.

**Comment by ecdsa** [comment]
I am on 2.7.6; that might explain it

**Comment by kyuupichan** [comment]
Unfortunately the argsparse documentation is dense and I don't see it clearly specifying behaviour in this case

**Comment by kyuupichan** [comment]
As this appears to be an issue, if at all, with argparse I don't see any point leaving this open; it's not something I want to fix on the electrum side.
