### ISSUE TITLE
cant get bitcoins from electrum 1.9.8 on linux

### ISSUE THREAD

**Issue by YakuTzevs** [spesmilo/electrum#1547]
Hello, i was using electrum 1.9.8 on linux for a couple of weeks receiving btc, but then when i tryed to transfer money out from my wallet i got an error, something about that my client produced a transaction that is not accepted by the Bitcoin network any more... and asked to upgrade to Electrum version 2.5.1 or newer... but when i installed 2.5.2 on this computer seed from the old wallet didn't feet
"your wallet has unsupported seed version ..... open your wallet-file with version 1.9.8 and move your coins to a new wallet"
how should i move my coins to another wallet if i cannot create any transaction??

and more interesting thing(bug) i can renew my wallet on another 1.9.8 Electrum on another computer with Linux... and there were all my coins but still i couldn't pass them to anyone .... BUT when i tried to recover my wallet on Electrum 1.9.8 on Windows it appeared empty as if it is just created...

please help solve this problem...

**Comment by gits7r** [comment]
What kind of wallet do you use? Standard wallet?

**Comment by YakuTzevs** [comment]
2 gits7r, yes, the first one

**Comment by ecdsa** [comment]
"unsupported seed version" : you must have used a git development version

**Comment by ecdsa** [comment]
sorry, closed by mistake.

**Comment by ecdsa** [comment]
"unsupported seed version" means that you did not use 1.9.8, nor any official release.
it must be a git development version.
in the console, what is wallet.seed_version ?

**Comment by YakuTzevs** [comment]
2 ecdsa, wallet.seed_version shows "6"

**Comment by YakuTzevs** [comment]
i got this version of Electrum from ArchLinux community, there were the only one version (1.9.8-4 - something like that)

**Comment by YakuTzevs** [comment]
i forgot to tell - my coins stuck on this system - PuppyRus-A (game) - if it can be usefull... - http://wiki.puppyrus.org/puppyrus/pra , https://ru.wikipedia.org/wiki/PuppyRus_Linux

**Comment by ecdsa** [comment]
please report this bug to ArchLinux, and ask them to take this version offline asap

**Comment by ecdsa** [comment]
to recover your coins, the easiers way is to export the relevant private keys using your old electrum version, and sweep them in the latest version of Electrum

**Comment by YakuTzevs** [comment]
i did it! exporting private keys helped! 
also i reported to ArchLinux community about bug in Electrum 1.9.8-4 and asked to get it away from repository...
thanks to every one! 
i hope my comments here will help to somebody else in the same situation ))
