### ISSUE TITLE
How do you decode redeem scripts?

### ISSUE THREAD

**Issue by 09128319047** [spesmilo/electrum#1548]
It does not seem there is an obvious way in the GUI or CLI to decode redeem scripts. 

Is this feature planned? Would it be possible to put a bounty on this feature?

**Comment by dabura667** [comment]
for what?

**Comment by 09128319047** [comment]
Decoding multisig transaction redeem scripts.

I would pay a fair sum of Bitcoin to have this feature added.

**Comment by ecdsa** [comment]
see transaction.parse_scriptSig

**Comment by ecdsa** [comment]
Note: you can call this function from the console, or write your own script.
I don't see a compeling use case to add it to the GUI, though

**Comment by romanz** [comment]
You can also use: https://github.com/richardkiss/pycoin/blob/master/pycoin/tx/script/tools.py#L121

**Comment by 09128319047** [comment]
There are several tools to use but it would be better if someone could solely use Electrum for working with multisig. 

esdsa: The use case is to verify a multisig address someone else created. For average users the console is difficult to use, and being able to quickly check a redeem script to see if a person was included in a multisig before sending Bitcoin.

I'm serious about putting a Bitcoin bounty on this feature.

**Comment by 09128319047** [comment]
What is the best way to reach active developers? The Freenode IRC channel? I would put several BTC bounty to get this feature added in the GUI.

**Comment by 09128319047** [comment]
esdsa: Can you please email me: electrumbounties@tutanota.com

I would like to put up a bounty to get this issue fixed as soon as possible. I can explain in more detail through email. I would also like to donate to the Electrum project in general and it is not easy for me to get on freenode IRC.

**Comment by ecdsa** [comment]
email sent.

**Comment by ecdsa** [comment]
no answer

**Comment by HostFat** [comment]
How is it possible to get the redeem scripts from the v2.8.3 ?
It seems that transaction.parse_scriptSig doesn't work anymore.

**Comment by ecdsa** [comment]
@HostFat why not?

**Comment by HostFat** [comment]
>> transaction.parse_scriptSig
Traceback (most recent call last):
NameError: name 'transaction' is not defined

Anyway I've found another solution by using the public key here https://coinb.in/#newMultiSig

**Comment by ecdsa** [comment]
lol, you need to import the transaction module first.

**Comment by rdymac** [comment]
For the record, this user `09128319047` has been accused of introducing a malicious code into https://github.com/WalletWasabi/WalletWasabi back in February 2024 . https://github.com/WalletWasabi/WalletWasabi/issues/14410 

Source: https://x.com/noosphere888x2/status/2088290231250210827
