### ISSUE TITLE
ElectrumWindows are not freed on close

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1549]
I've figured out this is because there are several places where references to the window are retained, that fall into 2 categories.

One is the network callbacks; this is fixable but requires a reworking of how we approach them.  The main problem at the moment is they are not unregistered.

The other is QKeyShortcuts - those taking lambdas never release the lambdas, which contain references to the window or its subobjects.

I'm going to work on fixing these - @ecdsa I assume you agree that releasing a window, its wallet, and associated resources is desirable when closing a QT window.

**Comment by kyuupichan** [comment]
@ecdsa - I'm also thinking of adding the GC debugging code I used to figure this out to the codebase, but to be enabled only via a command line switch - thoughts?

**Comment by ecdsa** [comment]
we need to remove the callbacks when the window is closed.
eg each address has a number of subscriptions (list of callbacks)
this kind of logic is implemented in the electrum server, not sure if you're familiar with it.
