### ISSUE TITLE
Cannot sign transactions with ledger HW1 in current git head

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1553]
In git#53f6fb9876d1b558f61df488d6440f3b5127f011  I can send transaction with my HW1
In git#47e5bd653a749043ea6af3357247541e460474fd I get the following behavior:

When I open the wallet file it doesn't ask for the pin, and when I attempt to sign a transaction, the following:
Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 43, in run
    self.result = self.run_task()
  File "/home/richi/sourcecode/electrum/gui/qt/main_window.py", line 1262, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 406, in sign_transaction
    self.get_client() # prompt for the PIN before displaying the dialog if necessary
  File "/home/richi/sourcecode/electrum/plugins/btchipwallet.py", line 236, in get_client
    raise Exception("Could not connect to your Ledger wallet. Please verify access permissions, PIN, or unplug the dongle and plug it again")
Exception: Could not connect to your Ledger wallet. Please verify access permissions, PIN, or unplug the dongle and plug it again

**Comment by ecdsa** [comment]
does it work with 2.5.4 ?

**Comment by ulrichard** [comment]
Yes, git#0d4de870a5159d491b604d29780f6bfb539c49f3  is still fine.

**Comment by ecdsa** [comment]
@kyuupichan could this be caused by one of your recent commits?

**Comment by kyuupichan** [comment]
Given the information provided it must be.  @ulrichard I hate to ask you to do this, but can you determine the exact commit?  There are only 3 or 4 between your success / failure points.  In particular I wonder if e9384f was the problem, in which case I'll revert just that and keep the rest.  Thanks.

**Comment by ulrichard** [comment]
Yes, it is  git#e9384f15ed80ded5fa5723b00171009c98419206

**Comment by kyuupichan** [comment]
I think I know why this happens (ugly plugin interface), but I'll just revert it for now.
