### ISSUE TITLE
Electrum on windows start a new instances everytime I click an URI (installer and portable)

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#1554]
Since I'm using a trezor it cannot connect to it if it's open in another app.

Doing a transactoin with an URI + Trezor is very tedious, on top of having to close Electrum and having to wait for it to start again, I need to click send transaction then click Yes, then log into my trezor, push approve 3 time for the transaction to complete.

Most other wallet I know will only ask to confirm the transaction when launched with URI arguments, I believe this step can also be removed when using a physical wallet.

**Comment by ecdsa** [comment]
which version of Electrum is that?
it should not be the case with 2.5.x versions

**Comment by Transisto** [comment]
The latest one, installed it on a fresh
Windows 10

**Comment by Transisto** [comment]
I've tested it on every machines around, same thing.

What does that mean ? 
> Release 2.5
> * The Qt GUI supports multiple windows in the same process. When a
   new Electrum instance is started, it checks for an already running
   Electrum process, and connects to it.

Should we see two windows opening up ?

**Comment by ecdsa** [comment]
only for different wallets.
it should not open two windows with the same wallet.

is the trezor wallet your default_wallet ?

**Comment by Transisto** [comment]
yes, Trezor is my defaut wallet, I've tried a standard wallet, with  latest portable and it does the same thing.

**Comment by ecdsa** [comment]
are you able to run Electrum on Windows from source, and does it behave similarly as the binaries?

**Comment by Transisto** [comment]
No, sorry I'm not equipped to run from python source.

**Comment by ecdsa** [comment]
oh, nvm, I think that I know what causes it. 
the daemon socket cannot use AF_UNIX on windows

**Comment by ecdsa** [comment]
firefox seems to avoid AF_UNIX, it uses a symlink instead:
`lrwxrwxrwx 1 voegtlin voegtlin       16 nov.  18 02:10 lock -> 127.0.1.1:+26401`

**Comment by Transisto** [comment]
http://stackoverflow.com/questions/94274/return-to-an-already-open-application-when-a-user-tries-to-open-a-new-instance
http://stackoverflow.com/questions/184084/how-to-force-c-sharp-net-app-to-run-only-one-instance-in-windows

**Comment by Transisto** [comment]
I don't full understand your fix, it talk about Firefox, just to add some information, Electrum start as a new instance whenever I launch electrum and not just with URI.

**Comment by ecdsa** [comment]
@Transisto you will need to wait for the next version

**Comment by Transisto** [comment]
This is still an issue with new version.

My business would like to use URI + electrum to send coins but every time an URI is clicked a new instance of Electrum starts, (taking as long as 30 second to launch).

**Comment by bauerj** [comment]
I couldn't reproduce this bug with 3.0.5.

If you still experience this issue, please reopen.
