### ISSUE TITLE
merchant.py network error

### ISSUE THREAD

**Issue by WebDesZ** [spesmilo/electrum#1555]
Hello. Is this a bug? Try to run merchant.py but it keeps failing.

electrum daemon start
>starting daemon (PID 673)

python merchant.py 
>Traceback (most recent call last):
  File "merchant.py", line 262, in <module>
    network = electrum.Network(config)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 143, in __init__
    self.num_server = 8 if not self.config.get('oneserver') else 0
TypeError: get() takes at least 3 arguments (2 given)

merchant.conf
```
[main]
host = mydomain
port = 50443
password = testpassword

[sqlite3]
database = electrum_sqlite3

[electrum]
xpub = xpubblablabla
wallet_path = /root/.electrum/wallets/

[callback]
received = "http://mydomain/r"
expired = "http://mydomain/g"
password = testpassword

```

/root/.electrum/config 
```
{
    "alias": "", 
    "auto_connect": true, 
    "console-history": [
        "wallet.storage.put('gap_limit',100)"
    ], 
    "dynamic_fees": false, 
    "fee_factor": 36, 
    "fee_per_kb": 20000, 
    "gui_last_wallet": "/root/.electrum/wallets/default_wallet", 
    "is_maximized": false, 
    "proxy": null, 
    "recently_open": [
        "/root/.electrum/wallets/default_wallet" 
    ], 
    "server": "ELECTRUM.jdubya.info:50001:t"
}
```

**Comment by ecdsa** [comment]
this script is deprecated, I will remove it.
use this instead:
http://docs.electrum.org/en/latest/merchant.html

**Comment by WebDesZ** [comment]
Thank you.
Do you also plan to integrate a callback function? Or am I just unable to find it?

Something like the "Receive Payments API V2" of Blockchain.info would be awesome. As it would help people to integrate electrum in their web projects and be independently from other services.
I know that this is not the place for feature requests but this would really help web developers.

Source: https://blockchain.info/api/api_receive

**Comment by ecdsa** [comment]
yes, I will add a callback URL, as in the merchant.py script
working on it now

**Comment by ecdsa** [comment]
callback added here 9b5b9849d74f62dfa684c472ccbd2047104fb28b
I removed merchant.py. it can now be completely replaced with the daemon.
note that the daemon supports jsonrpc calls directly.
closing this; let me know if you have more problems/questions
