### ISSUE TITLE
Synchronization problems on Auto-connect and multiple connections to servers

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#1557]
When starting Electrum with a config file that includes just the proxy set to socks5:127.0.0.1:9050, after finishing installwizard and using "Auto-connect" it won't sync, it will just stay as "Synchronizing". If I open the network pop-up and select a server manually (any server), it'll connect. How does Auto-connect actually work? What could cause the endless loop for synchronizing, as I remember we have fixed this.

I saw that immediately after starting electrum, while in installwizard, electrum will connect to multiple servers in the list. Isn't this look-up doing harm to users? Shouldn't electrum try to use the network only after the user was able to enter a proxy or not? This could leak that one is using electrum without user intention.

**Comment by ecdsa** [comment]
I think that is the expected behaviour if you choose auto-connect in the wizard.
if you want to enter a proxy in the wizard, you must not choose auto-connect

**Comment by gits7r** [comment]
@ecdsa not really - it attempts to connect before installwizard finishes so I can select Auto-Connect or Select server manually.

**Comment by gits7r** [comment]
@ecdsa Could we fix this until 07.12 so I can include it in Tails 1.8? I'll have it packaged for Debian fast if we make a new release. It's blocking the update in Tails, since we will ship it with a hardcoded proxy setting (socks5 127.0.0.1:9050) and it'll just say Synchornizing... forever and annoy the users.

Basically, it is needed to:
1) Fix synchronization on auto-connect (behind proxy or not, I saw it works better with no proxy but still not perfect. it'll successfully auto-connect on first start on about 30% of tries, and 70% will not sync).

2) This is not as urgent as 1), but if we can make electrum not try to do DNS queries (i think it tries to bootstrap servers) before installwizard finishes so we can select auto connect or manual connect? This could have privacy implications that's why I am concerned about it.

**Comment by ecdsa** [comment]
note: starting with a config file that only includes the tor proxy setting works for me, it connects through tor.

**Comment by ecdsa** [comment]
for the purpose of your distribution, you could as well use the command line option:
`electrum --proxy localhost:9050:socks5`

**Comment by gits7r** [comment]
Indeed on a 'normal OS' it will work.

In Tails however, it doesn't. If I start with no config file, it cannot auto connect obviously because it doesn't know it needs a proxy. I tried using the command electrum --proxy localhost:9050:socks5, created a wallet and clicked auto-connect. It just stays with red dot and says Not Connected. I need to manually select a server to connect. I tried over 200 times consecutively. In 85% of cases it doesn't connect to any server on auto-connect, regardless how long time you give it.  It just stays like that and states Not connected. Sometimes, very rare, it did connect.

My guess is that it gets confused when it tries to fetch blockchain_headers to get the height and the hash from peers, and in Tails it cannot do that because it has no internet for any application, except the socks5 proxy (Tor). Could this be the reason? We can setup a session where you can connect to my desktop on a live Tails instance and try to see for yourself.  I got the idea that this might be the issue because I saw it tries to do some dns bootstrap and request some kb of data even before wallet is generated and I can select auto connect or manual connect. Maybe we need to reconfigure networking start order. Do we need to be connected before we generate the addresses? I guess it tries to do that before so it knows how many addresses in advance needs to create (determinate the used addresses from that wallet) but can we do that after auto connect or manual connect is selected?

**Comment by ecdsa** [comment]
I don't think it is linked to fetching blockchain_headers.. 
that file is fetched from http://electrum.org to make things faster, but if http fails, then the client gets it from the servers.

**Comment by ecdsa** [comment]
hmm, the issue seems to be that auto-connect is not properly set by the wizard

**Comment by ecdsa** [comment]
that is fixed here: e9ee851bb2278c60485c48d644d945e382b3e098

**Comment by gits7r** [comment]
the latest commit indeed makes it much better. It will at least always connect if you select auto-connect. Some times it will take longer to connect, like over 60 seconds. My guess is that some of the harcoded servers cannot be reached via Tor, or their DNS name cannot be resolved and Electrum takes too much time until moving to the next server on the list. What is the amount of retries we keep here and time intervals?

**Comment by gits7r** [comment]
Sometime it connects in 10 seconds on auto connect and sometimes in 10 minutes.

**Comment by gits7r** [comment]
Average is 22 seconds, all successful connects on a set of 150 auto-connect requests through Tor. I guess the delay would be even shorter if without Tor and less overhead. It is acceptable. I think the delay may come from getting the headers from several other servers. Given the security implications, it's a hell of a good tradeoff here so I don't think we should change this.

I would still like to know the algorithm for connections on auto-connect (how many servers are tried, at what interval, how many attempts per server, etc.) maybe there's something we can do to improve it.

**Comment by gits7r** [comment]
Ok, finished testing, there is no problem with Electrum. The few seconds delay comes from downloading the blockchain headers (30 MB) which via Tor takes some time obviously. We'll just ship headers at a certain recent block height. Closing this.

Closed. Fixed in https://github.com/spesmilo/electrum/commit/e9ee851bb2278c60485c48d644d945e382b3e098
