### ISSUE TITLE
Python version not explicit in shebang

### ISSUE THREAD

**Issue by mariuszskon** [spesmilo/electrum#1562]
You enforce python2 in a couple of places ([python2 search](https://github.com/spesmilo/electrum/search?utf8=%E2%9C%93&q=%23!%2Fusr%2Fbin%2Fenv+python2&type=Code)) but there are many without the explicit 2 ([python search](https://github.com/spesmilo/electrum/search?utf8=%E2%9C%93&q=%23!%2Fusr%2Fbin%2Fenv+python&type=Code)).

EDIT: Not a problem on systems with python3 as default, but it is still a god idea to make it explicit

**Comment by kyuupichan** [comment]
I've done it on the scripts intended to be run directly; I think the rest are harmless.
