### ISSUE TITLE
Electrum close when URI "label=" what to use then ?

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#1564]
When using an URI with "label:".  When I click the link elctrum launch and ask me to approve the addition of said label to receiver address, If I click YES Electrum shuts down (crash). If I chose NO, URI information get populated in the fields and the label get added anyway.

I personally don't think addresses should be labeled from a URI but transaction should be.
The only way that make sense for electrum to use "label=" when meaning a label to the receiver address was if it would add the address to the Contacts tab.

Mycelium is using "Label="  as labels for a transactions.
Coinofsale.com is also using "Label=" for product description

**Comment by ecdsa** [comment]
Mycelium is wrong. The correct way to label a transaction is to use "message".
The purpose of the "label" parameter is to add a label to an address.
see https://en.bitcoin.it/wiki/BIP_0021

I will fix the crash

**Comment by ecdsa** [comment]
I fixed it by handling "label" as "message". 
this is not BIP21 compliant, but the use of "label" should be discouraged anyway.
