### ISSUE TITLE
Add notifications to electrum

### ISSUE THREAD

**Issue by Jzarecta** [spesmilo/electrum#1568]
Would be nice to have sound and visual notification on wallet movements. Notifications are important where the software is not on the active desktop (minimized). Doing transfers and expecting a deposit by the user could be greatly enhaced by a sound notification. Using Qsound is rather easy to add this feature to the electrum wallet. 

``` python
from PyQt4 import QtGui
s = QtGui.QSound('test.wav')
s.play()
while not s.isFinished():
    sleep(0.1)
```

Visual notification can be used through Growl or libnotify.

``` python
    def notify(self, receiver, event):
        """ Pass the event on, printing diagnostics if enabled. """

        if self.assertOnEvents:
            print('Post-termination event: receiver = %s, event = %s' % (receiver, event))
        return QApplication.notify(self, receiver, event)
```

Here is an example of the NuWallet Qt app using growl:
https://bitbucket.org/JordanLeePeershares/nubit/src/6fe88883f316b1ff3448d52438e9d122f808da51/src/qt/notificator.cpp?at=master&fileviewer=file-view-default

**Comment by ecdsa** [comment]
there are already notifications, using the system tray
is this not working for you?

**Comment by Jzarecta** [comment]
Correct, I find sound notifications more useful.

**Comment by pdroalves** [comment]
I miss sound notifications either. I added to my client's code a routine to play a sound for new events and my experience became much better.

**Comment by kyuupichan** [comment]
Can you provide two or three suggested sounds?  Unless ThomasV objects, and as he's left this open he probably doesn't, I will look to adding this if we have a couple of appropriately licensed sounds.

**Comment by Jzarecta** [comment]
I would look into the KDE audio sounds which are very rich, particularly I like /usr/share/sounds/KDE-Im-Contact-In.ogg /usr/share/sounds/KDE-Im-Highlight-Msg.ogg and /usr/share/sounds/KDE-Im-Sms.ogg 
If you dont use KDE or Linux let me know I could put them somewhere.

Here are some: https://github.com/KDE/oxygen/tree/master/sounds

**Comment by Jzarecta** [comment]
Any updates?

**Comment by ecdsa** [comment]
please provide a pull request

**Comment by bauerj** [comment]
Electrum does show OS notifications now for incoming transactions. Since you can configure the notification sound on the OS level, I close this issue.
