### ISSUE TITLE
Electrum not updating Blockchain headers

### ISSUE THREAD

**Issue by mmitech** [spesmilo/electrum#1569]
I forked Electrum 2.3 for Creditbit, everything seems to be working, I can send receive transactions, but the Electrum client will show transactions as unverified, however I can spend them after they get confirmed, the client show pending for unconfirmed incoming transactions than they switch to unverified once they are confirmed.

After investigating I found out that blockchain_headers are not updating, when I delete the blockchain_headers it gets downloaded from self.headers_url provided in the lib/blockchain.py, and that solve the problem for the previous transactions, but the blockchain_headers don't update from that point forward !! and I have to repeat this every time !!

any suggestions on how to solve this ?

**Comment by ecdsa** [comment]
sorry, we don't have time to support altcoin forks.

**Comment by ecdsa** [comment]
note: you probably need to create another headers file for your altcoin

**Comment by mmitech** [comment]
Hello, I know that your hands are full, but I don't know where else to ask !! and I apologize in advance for this...

How do I create another headers for my altcoin ?

**Comment by ecdsa** [comment]
I do not know. Ask the authors of creditbit
