### ISSUE TITLE
Support custom_entropy from command line

### ISSUE THREAD

**Issue by the9ull** [spesmilo/electrum#1574]
The method [Mnemonic().make_seed()](https://github.com/spesmilo/electrum/blob/master/lib/mnemonic.py#L150) supports entropy provided by the user.

Would be useful add to the command line create command the options --entropy-{dice,permutation,...} to manage the custom entropy parameter.

Entropy could be provided in different formats:

* a single big integer
* a list of dice rolls, different dice type could be supported (base 6, 8, 12, 20, 30)
* permutation of n elements. The id of the elements are chosen by the user.

**Comment by ecdsa** [comment]
I think this is out of scope; you have more flexibility by passing entropy as a parameter

**Comment by the9ull** [comment]
How is it possible now pass the entropy as parameter? `electrum create` doen't have a way, am I wrong?

**Comment by ecdsa** [comment]
you can use make_seed and restore from it
