### ISSUE TITLE
Electrum 0 balance bug/vulnerability 

### ISSUE THREAD

**Issue by treodu** [spesmilo/electrum#1575]
Is electrum still a safe client to store/recieve/send bitcoins?  I have discovered an electrum bug but i find it hard to believe im the only one - im technically savy but not a programmer who may try things that stress the code electrum is built on such as https://github.com/spesmilo/electrum/issues/1525 but none the less i seem to have uncovered this new/undiscovered weaknesses/bug in this 4yr old software - i have not found any identically similar problems anywhere on the web (onion network nor open web) - under persumption bug-reporting from scratch may be needed i furnish all relevant background, specs, and bug descriptions for review.  .If any further information is needed to duplicate and resolve this bug please email me - i will promptlu provide.

Problem specs:
Linux kali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
Electrum 1.9.8 via tor localhost port (this setup works - i have sent, recieved, and verified transactions via tor port for anonymity)

The Electrum Bug: 
 - i can find the transaction on https://blockchain.info/ and blockchainbdgpzk.onion - i can see the balance using a watch-only address -
  -is uninstall/reinstall electrum the only way to properly update wallet balances?
  -wallet.clear_history() from http://bitcoin.stackexchange.com/questions/41042/why-i-am-not-seeing-received-money-in-my-electrum#comment47223_41056 does not  work
  -github still seems to be working the bug out https://github.com/spesmilo/electrum/issues/1525 , or may not fully realize this bug exists

  -electrum can locate the funding transaction on the blockchain (should i broadcast? it is already recorded on blockchain.info so broadcasting seems redundent) i have saved the imported transaction if posting it here would be of help.troubleshooting

Thank you electrum delvelopers in advance for you time and attention to keeping electrum a strong bitcoin client - bitcoin community needs and appreciates you.

**Comment by ecdsa** [comment]
please don't report bugs about 1.9.8. 
upgrade to the latest version first, and check if the bug exists with it

**Comment by treodu** [comment]
sure about that? Both versions seem to slow debian systems - very questionable as to coding
both versions have same bug
I will report this again and bring to the for front the VERY strange behavior of electrum and perhaps the code would benefit from independent review for safety and functionality.  Other wallets do not seem to run so many "unidentified" processes in the background - this coupled with this balance bug that recurs in so many forms (as detailed in my initial question) any one concerned about there bitcoins will be concerned about what im uncovering
