### ISSUE TITLE
password checked after output selection on private key export

### ISSUE THREAD

**Issue by strk** [spesmilo/electrum#1576]
Exporting private keys first asks you for a password, then makes you select an output and only after that checks the given password. I'm not sure if the waste of time is intentional...

**Comment by ecdsa** [comment]
what do you mean by " makes you select an output " ?

**Comment by strk** [comment]
It prompts you for selecting an output file. Opens up the file browser.

**Comment by ecdsa** [comment]
yes, and what makes you believe it checks the password only after that?

**Comment by strk** [comment]
The fact that I give it a wrong password and it tells me so
only after I selected the output file.

**Comment by ecdsa** [comment]
you must be using an old version. 
the current version does not do that.

**Comment by strk** [comment]
1.9.7-1 here, packaged on Ubuntu 14.04.3 LTS

**Comment by ecdsa** [comment]
ok, closing
