### ISSUE TITLE
The problem with the launch of Electrum 2.5.4

### ISSUE THREAD

**Issue by AidPearce** [spesmilo/electrum#1578]
Hello.
The problem with the launch of Electrum 2.5.4. After clicking, the program opens and closes immediately. Operating system Windows 10. What is the problem and how to solve it?

**Comment by ecdsa** [comment]
try to run it from a console and post the error you see

**Comment by AidPearce** [comment]
How to start the console, in the sense of a team?

**Comment by ecdsa** [comment]
I don't know about windows
