### ISSUE TITLE
Recommended fee/kb too high -> should be set to 10k or lower

### ISSUE THREAD

**Issue by Levino** [spesmilo/electrum#1580]
I just stumbled upon the fact that the default fee per KB (RECOMMENDED_FEE) is set to 50000 satoshis. The current "official" min_relay_fee is 5000. As far as I can tell if one is just slightly above this, it suffices to get txs confirmed quickly. I would think that something like 10000 should be fine to be sure that the transactions have high priority. 50000 however is a waste of money, if you ask me.

Introduced here: https://github.com/spesmilo/electrum/commit/bde0ca3ea1e82a50e7422db57617f879865c7f19#diff-b026615fe6f31bfcbd95d0860025eccdR43

**Comment by ecdsa** [comment]
you cannot compare these things:
min_relay_fee is not a per kb value, it is an absolute value.
recently, the recommended fe/kb sent by bitcoind has fluctuated between 20000 and 30000
