### ISSUE TITLE
Zero balance + possible electrum keylogger warning and request for review

### ISSUE THREAD

**Issue by treodu** [spesmilo/electrum#1581]
Please be advised i uncovered a zero balance bug in electrum 1.9.8.  (see my earlier posts to existing issues and new issues) https://github.com/spesmilo/electrum/issues/1575 https://github.com/spesmilo/electrum/issues/1525

I was TOLD not to report bug in 1.9.8  by an administrator here and advised to upgrade.  I did upgrad and not only did i discover the same issue but in upgrading i was able to see that a new debian system burned from a clean debian based iso was quickly infected and corrupted after running electrum 2.5.4.  Electrum seems to act as a keylogger or other high process software, not like other bitcoin clients that do no effect all other running programs and services.  

Additionally the orginal problem that was reported https://github.com/spesmilo/electrum/issues/1575 is still occuring exactly as it was reported in 1.9.8  

I warn anyone with bitcoins in electrum wallet to be advised and weary of these bugs/issues.  Had i created an online electrum wallet i fear my coins would be FREED from me.  Offline created electrum wallets seem to retain coins as verified by blockchain.info but electrum is not dependable to rely upon at present i justifiably fear.

**Comment by ecdsa** [comment]
this report does not contain much useful information...
coan you try to explain what the bug is, and not to make your own interpretations?

**Comment by treodu** [comment]
not being a coder and not being involved in the development of electrum i cant point specifically to what problem(s) are causing the issues. If any logs are available pls detail how i can generate them and i will provide them for review.   I have detailed very carefully in all linked discussions - the collective issues/possible causes/possible fixes/possible related issues are too numerous (as electrum coders surely know electrum code is not re-written fresh from scratch each version so residual bugs may live in daughter versions)  What i can offer is that the same issues seem to be recurring on multiple versions (1)zero balance when address has bitcoin in it even after sync (2)sluggishness of system when electrum is run - and the issues are occuring on comparatively stable and verified clean debian installs. thru a local tor proxy with matching socks5 for tor and electrum.  A similar issue on command line version is linked to above, although one of the lead programmers patronized my linking the to similar issues as non-related i dont believe that issue was fully resolved but perhaps they can give deeper explanations.  My concern is more for those trying to use the functionality of electrum but may be being taken advantage so hopefully any white hat who wants  a gold star and positive notoriaty may do their part for the bitcoin community :)

**Comment by ecdsa** [comment]
- can you post a bitcoin address that is showing up with zero balance in Electrum, and not in blockchain.info?
- which server were you using when it happened?
- was your Electrum client fully synchronized?
