### ISSUE TITLE
I cannot find "Import" in "Wallet > Privet keys" v. 3.5.4 Portable

### ISSUE THREAD

**Issue by Alookard** [spesmilo/electrum#1582]
I cannot find "Import" in "Wallet > Privet keys" v. 3.5.4 Portable

Pic:

![2015-12-15_18-31-46](https://cloud.githubusercontent.com/assets/16308682/11816686/358eab60-a35a-11e5-8df7-17de21e74189.jpg)

**Comment by ecdsa** [comment]
this is not possible with standard wallets. 
if you want to import keys you need to create a new wallet file.

please read the documentation before reporting bugs
