### ISSUE TITLE
change address substitution attack for trezor-backed electrum

### ISSUE THREAD

**Issue by tphyahoo** [spesmilo/electrum#1586]
When sending bitcoin from trezor-backed electrum, the trezor device demands user confirmation on two addresses: the original send address, and also confirmation for the change address.

This is different from the behavior on mytrezor.com, which is safer because it only asks for confirmation on the send address, reassuring the user that any change address was calculated by the trezor device, and not the mytrezor.com app.  In more detail, on mytrezor, the behavior is as described here:

https://www.reddit.com/r/TREZOR/comments/2nrp8l/how_does_trezor_handle_change_addresses/

"Change addresses are not shown at all and are hidden from user because they are handled automatically by TREZOR device. Each time user send transaction a new unused change address inside account is generated for transaction change.  Path to the change address is displayed on the right while composing transaction in mytrezor.com wallet."

To clarify, change addresses are not only hidden on mytrezor.com, they are also not stated on trezor device for confirmation.   With trezor confirmations from mytrezor.com transactions, you confirm the send address but not the change address.  

I assume this is because a different api action is used for mytrezor.com sends than for electrum sends.

But on electrum, the change address is just another output and you have to confirm it. Change addresses aren't special, and an attacker could substitute a bad address for a legitimate change address.

This attack can be mitigated by keeping a list of known safe change addresses handy, but that's a lot to ask for from a user and I can certainly see funds being stolen because the user assumes "it's a trezor so it's safe."

**Comment by prusnak** [comment]
"I assume this is because a different api action is used for mytrezor.com sends than for electrum sends."

Correct. If you specify the address by providing its BIP44 path instead of the address directly, it is considered as hidden and not shown on TREZOR. (You can have max 1 change address per TX).

**Comment by tphyahoo** [comment]
OK, so this looks like a fix to

https://github.com/spesmilo/electrum/blob/c7b1721f585ff8863e1df0f14452bd27b1291bbf/plugins/trezor/trezor.py

It seems that 

    def tx_outputs

is already address_n aware, so I am not sure what the problem is.  Needs closer reading.

I will also try to reproduce the problem with updated trezor firmware and fresh electrum and electrum-trezor plugin.  Maybe I am just on an old version.

**Comment by tphyahoo** [comment]
I can't reproduce this on fresh hardware with everything reinstalled.

Closing.
