### ISSUE TITLE
Feature request: calculate and display fiat currency value.

### ISSUE THREAD

**Issue by Owidiusz** [spesmilo/electrum#1588]
It's nice to have amount of bitcoins owned in status bar on the bottom of program window.
Why not specify fiat currency value next to bitcoin value?
It could be downloaded from exchange service of user's choice, and in currency of user's choice.

I would be glad to see my account balance in USD, EUR or PLN automatically.
I would also be happy to see it increase as BTC appreciates over time :)

**Comment by kyuupichan** [comment]
Already exists, See the exchange rate plug in.
