### ISSUE TITLE
Sign final developer with apple id

### ISSUE THREAD

**Issue by fulldecent** [spesmilo/electrum#1589]
When launching a user receives the error 

> “Electrum” can’t be opened because it is from an unidentified developer.

There is a work around. However, best practice is to sign these binaries.

**Comment by ecdsa** [comment]
I will do that

**Comment by justlurking** [comment]
@ecdsa I wanted to try Electrum but the latest version is still not signed. (As a rule I don't install unsigned software.)

Is this not ever going to happen? I realize Apple charges $99/year for the privilege, which is a significant hurdle for many volunteer projects.

**Comment by ecdsa** [comment]
it is going to happen. the Apple fee is not an issue.

**Comment by ecdsa** [comment]
osx builds are signed now.
not sure why this issue has not been closed earlier
