### ISSUE TITLE
Open wallet.dat

### ISSUE THREAD

**Issue by fulldecent** [spesmilo/electrum#1590]
Boom right here

![screen shot 2015-12-23 at 8 09 37 pm](https://cloud.githubusercontent.com/assets/382183/11987666/1fce59ee-a9b1-11e5-85da-0240c0b19075.png)

![screen shot 2015-12-23 at 8 10 17 pm](https://cloud.githubusercontent.com/assets/382183/11987671/344c8256-a9b1-11e5-8da1-f4529ac7e2cf.png)

**Comment by ecdsa** [comment]
will not do that, sorry.
