### ISSUE TITLE
Hardware wallet restore is poor

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1592]
We should not require any special libraries (like trezor lib) to restore a hardware wallet, as they are simply BIP32 wallets.

We should also not require those libraries, in order to use a restored hardware wallet.  If I restore on a machine with the libraries I cannot use the restored wallet on one without.

I think a restored trezor wallet should not have wallet_type "trezor" but instead "BIP32_HD" or something like that.

**Comment by dabura667** [comment]
+1

but

> We should not require any special libraries (like trezor lib) to restore a hardware wallet, as they are simply BIP32 wallets.

Isn't trezor lib required to talk to the Trezor device at all?

**Comment by kyuupichan** [comment]
Yes trezor lib is required. But it is unneeded for anything relating to restored or restoring wallets.

**Comment by kyuupichan** [comment]
Fixed mostly in 11d135b32d7c59782dbbd3327f65adfda1fdf1dd.
