### ISSUE TITLE
Creating BIP32 accounts

### ISSUE THREAD

**Issue by MineForeman** [spesmilo/electrum#1593]
Hi Guys,

I need help fixing my faulty logic.  What I am trying to do is to create a new bip BIP32_Account that I can use for receiving (something like m/44'/0'/1'/0/1) .  Creating the xpub/xprv is not a problem, as is adding the xprv to the wallet and creating the account.

Where I am failing is associating the Account/xpub with the xprv.

I see the account in addresses as I think I should but when I right click and go to private key I get a blank box.

So, that is what I am trying to do and here is the latest incarnation of how I am trying to do it (the world's simplest plugin);-

    from lib.account import BIP32_Account

    class Plugin(BasePlugin):

        @hook
        def load_wallet(self, wallet, window):

        xpub = 'xpub661MyMwAqRbcF8M4CH68NvHEc6TUNaVhXwmGrsagNjrCja49H9L4ziJGe8YmaSBPbY4ZmQPQeW5CK6fiwx2EH6VxQab3zwDzZVWVApDSVNh'
        xprv = 'xprv9s21ZrQH143K2eGb6FZ81nLW44cyy7mrAiqg4VB4pQKDrmizjc1pSuynnpeiaMPdZxvrfvdBi5oqFi9hmsV7MrsVquKkruQ7TJPCfVuPSdw'
        password = None
        account_name = 'test'

        account = BIP32_Account({'xpub': xpub})
        wallet.add_account(account_name, account)
        wallet.add_master_private_key(account_name, xprv, password)

Those keys are taken from electrum/lib/tests/test_account.py but I am using properly derived keys with my example (I can give the code for that if that matters).

SO!  Can someone please tell me how it is supposed to work before I am forced to scoop my eyeballs out with a rusty spoon?  My python is not good enough yet to understand something as complex as electrum and I could really use a pointer in the right direction.

P.S. I am using git origin/master with a ‘standard wallet’, the work going into electrum is great, I especially like the new plugin layout.

**Comment by kyuupichan** [comment]
Make sure you're using hit HEAD as it has a new BIP 44 base class which you
should use that I put in yesterday. Also the KeepKey and Trezor plugin code
has been much simplified and cleaned up.

**Comment by MineForeman** [comment]
Yep on HEAD.  I say your BIP44 stuff come in this morning when I pulled but have not had a look at it yet.


Just to clarify, am I using Accounts wrong?  I cannot do what I am after using them (create a spendable account under a standard wallet)?


Why I ask is because I thought that you could only have a single Wallet object in storage.  I was kind of hoping that someone could enable my plugin and have it appear in their existing wallet instead of making a new one.


Sorry if my questions are a bit dense but you are realy helping me by giving me the right direction to go in.

**Comment by kyuupichan** [comment]
Check out create_main_account in lib/wallet.py.  As this is not an issue with electrum itself I will close this.  Please ask on IRC and someone may help.
