### ISSUE TITLE
[Idea] Sign XPUB P2SH Multisig Transaction

### ISSUE THREAD

**Issue by jaebird** [spesmilo/electrum#1594]
It would be nice if I could sign a multisig transaction from command line or utility when XPUB is from a HW device like Trezor. I created a watchonly 2of2 multisig wallet from 2 Trezors with XPUBs from 44'/0'/100'. Cannot sign from Electrum gui until all of the previous subaccounts are known.

Something like this would be useful:
electrum signtransaction --hw_plugin trezor --xpub_path "44'/0'/100" tx

This would then follow normal txn sign workflow.

**Comment by ecdsa** [comment]
it should be possible without passing the xpub path as a parameter, using Electrum's extended format
http://docs.electrum.org/en/latest/transactions.html

**Comment by ecdsa** [comment]
@kyuupichan this relates to what we discussed over IRC this morning

**Comment by ecdsa** [comment]
you can do this now with the gui in 2.7
