### ISSUE TITLE
DIsambiguating the dynamic fee settings

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#1595]
Turning on dynamic fees also displays the Fee multiplier slider. The way it is realized has a number of issues in my opinion.

![sdf](https://cloud.githubusercontent.com/assets/7106231/12074423/7e835e36-b153-11e5-8ecd-060886f9b8bc.png)

First, the slider is confusing, because "dynamic" implies (and it is) something automatically set, while the slider is a manual input. For me, until I figured it out, it was frustrating. Then, only after carefully looking at the slider tooltip, did I realize that it is a multiplier of the fee/kB recommended by the server.

I recommend placing a textbox element above/below/next to the slider which communicates at least as much as "Fee multiplier", with a tooltip explaining that it can be used to make the transaction confirm slower or quicker.

Second, the slider limits (as of now, 50% and 150%) are vague until activating the tooltip, and the actual percentage set is never displayed.

I recommend displaying the set percentage somewhere near to the slider, and maybe, if it's feasible and aesthetic, displaying the limits and possibly the 100% tick under the slider for easier navigation.

**Comment by ecdsa** [comment]
I agree; I think we need to display more details

**Comment by ecdsa** [comment]
the slider now has its own line with a label

**Comment by leafcutterant** [comment]
Thank you, @ecdsa!

**Comment by kyuupichan** [comment]
Can this be closed?

**Comment by kyuupichan** [comment]
@leafcutterant @ecdsa I've pushed a rearrangement including ticks and updating-as-you-slide label, based on similar thiing I did for hardware wallet session timeouts.  Let me know if it's no good.
