### ISSUE TITLE
Still don't understand how connecting to server work

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#1597]
I've been using Electrum for more than a year and I still don't understand how the connection panel work.

![image](https://cloud.githubusercontent.com/assets/388716/12077157/2689da18-b1a1-11e5-8b2a-b47733dd53ce.png)

I have no idea if when I click Autoconnect it will chose a server from the list automatically or if it will connect to the selected server automatically whenever I start Electrum.

It would be great id there was something in the status bar that say connected to "server_same"

**Comment by ecdsa** [comment]
maybe the label of 'auto-connect' button should be more explanatory, and not on the same line
I disagree with showing the server name in the status bar.

**Comment by dabura667** [comment]
> maybe the label of 'auto-connect' button should be more explanatory, and not on the same line as the server name field.

I used to have the same misconception as OP. I think this will fix it. +1
