### ISSUE TITLE
[Idea] Display BIP44 Path for derived addresses

### ISSUE THREAD

**Issue by jaebird** [spesmilo/electrum#1598]
This is only applicable for wallets that use BIP44 paths (ie Trezor). It would be nice to either allow for a custom column in the address tab to display the path or a right-click menu option to show "details" of an address. This doesn't need to be shown by default, as it is not normally needed. However it helps users with very active wallets understand how long their HD chain is as well as interop with other tools.

It would show something like this:  44'/0'/1'/0/1.

Idea comes from: mytrezor.com, which shows this info to the user

**Comment by ecdsa** [comment]
I don't like the idea of having that as an extra column.
maybe a menu item for the details, that would include the current public keys item

**Comment by kyuupichan** [comment]
@ecdsa I'll add it to the right-click -> public keys menu item
