### ISSUE TITLE
trustedcoin plugin fee is broken

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#1600]
if the user did not buy prepaid transactions, extra_fee is not added to the fee.

**Comment by ecdsa** [comment]
This was broken when estimated_fee was removed from the wallet class.
That method was overloaded in trustedcoin.py
Now Wallet_2fa.estimated_fee() is not called anymore

**Comment by kyuupichan** [comment]
@ThomasV

This logic :

# trustedcoin won't charge if the total inputs is lower than their fee

Is this enforced in Electrum only,  or on the server side too?

**Comment by ecdsa** [comment]
on both sides

**Comment by kyuupichan** [comment]
ThomasV - honestly from your description I can't understand what is broken.  Is it make_unsigned_transaction?

**Comment by ecdsa** [comment]
create a two-factor wallet, fund it, then try to spend from it.
make_unsigned transaction will create a tx with a negative miner fee.
This is because the plugin adds an extra output (to pay trustedcoin), but it fails to take the extra amount into account in the inputs. (this used to be achieved with estimated_fee).
