### ISSUE TITLE
ledger hw1 plugin unusable with current git head

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1605]
I didn't test the hw1 for a while, but in the current git head it is unusable.

First It complained about missing QMessageBox, so I added the following line:
from electrum_gui.qt.util import *

If I then try to open the hw1 wallet without the dongle plugged in, I get a message box with the following:
Exception: Exception : No dongle found
And it doesn't open the wallet for viewing.

If I then try to open the hw1 wallet wit the dongle plugged in, I get a message box with the following:
Exception: Could not connect to your Ledger wallet. Please verify access permissions, PIN, or unplug the dongle and plug it again
And it still doesn't open the wallet for viewing.

**Comment by ecdsa** [comment]
I just tried with a fresh ledger; I get this errror: Invalid status 6d00

**Comment by btchip** [comment]
this error is pretty generic, it basically means that the chip is not in
the right state to process this command. I'd need the command logs to
understand what's happening (you can get it by setting DEBUG to True in the
plugin) and I'll take a look at git head as soon as I can (which probably
means in a few days right now)

**Comment by ecdsa** [comment]
@btchip : FYI, that was one of the new ledgers you sent me lately 
(the previous one was too old and I could not update its firmware). 
the ledger was fresh and uninitialized.

**Comment by kyuupichan** [comment]
I've got HEAD to a state where you can create a new wallet from an already-setup ledger.
Untangling the GUI from the core logic will take some time; I will be trying to narrow the differences with it and the Trezor / KeepKey code.

**Comment by btchip** [comment]
I should also have some simplified code coming up soon

**Comment by ulrichard** [comment]
It's a lot better now. But there's a problem left.
After entering the TAN for a tx, I get this:

  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 226, in run
    self.result = self.task()
  File "/home/richi/sourcecode/electrum/gui/qt/main_window.py", line 1268, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 281, in sign_transaction
    self.give_error(e, True)
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 57, in give_error
    raise Exception(message)
Exception: global name 'client' is not defined

**Comment by ulrichard** [comment]
It's also strange that it generates transactions with 4 or 5 outputs when the ledger supports only 2.
I can get around this by entering ! . Then I get to the above problem.

**Comment by kyuupichan** [comment]
ulrichard: Ledger only supports <= 2-output txs?  Are you using the privacy coin chooser?

**Comment by ulrichard** [comment]
yes that was with the privacy coin chooser

**Comment by ulrichard** [comment]
with the current git head I get this when trying to sign a tx:

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 550, in run
    result = task.task()
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 194, in sign_transaction
    for txinput in tx.inputs:
TypeError: 'instancemethod' object is not iterable

**Comment by ecdsa** [comment]
@ulrichard that should fix it: 78e9a84c2f2ed09800f0e571e39c0bf071fca64d

**Comment by ulrichard** [comment]
Now the problem is somewhere else:

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 550, in run
    result = task.task()
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 282, in sign_transaction
    self.give_error(e, True)
  File "/home/richi/sourcecode/electrum/plugins/ledger/ledger.py", line 58, in give_error
    raise Exception(message)
Exception: global name 'client' is not defined

**Comment by ecdsa** [comment]
@ulrichard maybe, line 269, replace client by self.client..
sorry I cannot test
@btchip please help

**Comment by btchip** [comment]
what's the status of @kyuupichan code ? I don't really have time to test
right now.

**Comment by ulrichard** [comment]
Yes, it was a one liner
https://github.com/spesmilo/electrum/pull/1648
