### ISSUE TITLE
Bitcoin Stuck Pending

### ISSUE THREAD

**Issue by ctt1** [spesmilo/electrum#1606]
I have sent 2 Bitcoin transactions to a used address in my electrum wallet because the only addresses that showed were used. The first transaction showed up in my history as pending, so I took it as a successful address and then sent one more large transaction. I have waited a couple hours now and the first transaction is still pending, and the second transaction never showed up in my history. I am very concerned for my money. What can I do to fix this/what have I done wrong?

**Comment by ecdsa** [comment]
the fact that an address is used is not relevant. however, it is very weird that your wallet shows only used addresses; maybe this is the symptom of a broader problem.

did you pay the recommended fee, or less?

what are the transaction IDs of both transactions?

**Comment by ctt1** [comment]
It seems as the two transactions have gone through and they weren’t updating because my status was offline. However, now I have run into another issue, and that is that I can not get electrum wallet to run online in one of the operating systems I use. When I retrieve the wallet via seed, it brings up my history and used addresses, but will not give me new ones no an online status. What can I do about this? The operating system that I am using that is getting the error is Tails, and the second to most updated version. I don’t think it would be because it isn’t updated since I have successfully used it since the update came out. Thanks.

**Comment by ctt1** [comment]
Also, I did indeed pay the recommended fees. The transactions IDs are cb3a5ff589e05626f13f8aa323175182326611f32761667e787cb69568cf13e7

as well as 
4fd1ea5b7372215db39cedda68026184c854f4554940ed524a3393fa5f526f40

**Comment by ecdsa** [comment]
probably a setting related to TAILS, eg the proxy
