### ISSUE TITLE
allow non-root installation on Linux

### ISSUE THREAD

**Issue by andreas-h** [spesmilo/electrum#1607]
I want to install Electrum on my Ubuntu machine in my user's `$HOME` directory, i.e., not via `sudo`.  If I run the command

    pip install https://download.electrum.org/2.5.4/Electrum-2.5.4.tar.gz

I get an error when the installation tries to create a desktop shortcut:

    copying electrum.desktop -> /usr/share/applications/
    
    error: [Errno 13] Permission denied: '/usr/share/applications/electrum.desktop'

Maybe the installation script could `try` if this copy operation works, and try again at `$HOME/.local/share/applications` (or, better, `$XDG_DATA_HOME/applications`) in case it doesn't.

If you agree this would make sense and point me to the file where I would need to do this, I'd be happy to provide a PR.

**Comment by andreas-h** [comment]
PS: I should add that as it stands, the installation fails; at least I cannot find any executable `electrum` script, i.e. in `~/.local/bin`.

**Comment by ecdsa** [comment]
did you get a recent version of pip and try with the --user option?

**Comment by andreas-h** [comment]
using stock pip from Ubuntu 14.04:

    $ pip --version
    pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

And yes, used `--user` but forgot to put it when copy-pasting.

**Comment by ecdsa** [comment]
can you try without pip?
 'python setup.py install --user'

**Comment by andreas-h** [comment]
Thanks for the suggestion, but this also doesn't work:

    $ python setup.py install --user
    [...]
    running install_data
    copying electrum.desktop -> /usr/share/applications/
    error: [Errno 13] Permission denied:
'/usr/share/applications/electrum.desktop'

**Comment by ecdsa** [comment]
ok, in that case I think you should update setuptools

**Comment by andreas-h** [comment]
also happened with up-to-data setuptools 19.2.

prepared a small patch to `setup.py` which fixes the issue for me.

**Comment by ecdsa** [comment]
you are right; I did not see the issue because the --user installation works if the file was already installed on the system.
