### ISSUE TITLE
create icons_rc.py from setup routine?

### ISSUE THREAD

**Issue by andreas-h** [spesmilo/electrum#1609]
After installing Electrum via `python setup.py --user` (see #1607), I get the following error:

    $ electrum 
    Error: Could not import icons_rc.py, please generate it with: 'pyrcc4 icons.qrc -o gui/qt/icons_rc.py'

so then, I ran the command from the Electrum source tree, and still got the same error. I additionally needed to re-install Electrum for the error to go away.

Two suggestions:

1. amend the error message with "and re-install Electrum"
2. automatically run the command within the setup routine if the `icons_rc.py` file doesn't exist yet.

**Comment by ecdsa** [comment]
that would make sense, indeed.
note that qt is not (and should not) be required for install.

**Comment by ecdsa** [comment]
I amended the error message; I think doing it in setup.py is a bad idea.
