### ISSUE TITLE
provide QR-independent way to initialize 2FA wallet

### ISSUE THREAD

**Issue by andreas-h** [spesmilo/electrum#1610]
When creating a 2-factor-auth wallet in Electrum 2.5.4, the pop-up only shows a QR code for ingestion in my Google Authenticator.  However, the camera on the phone I use for this is broken, so I cannot scan the QR code, and I'm lost without hope.

Please provide the information needed for "manual setup" of the Google Authenticator in human-readable form in the same pop-up window.

**Comment by ecdsa** [comment]
I agree, that would be an improvement.
