### ISSUE TITLE
idea: allow spaces in private keys to be swept

### ISSUE THREAD

**Issue by andreas-h** [spesmilo/electrum#1612]
When sweeping private keys, it would be good if Electrum would support spaces in the private keys the user enters into the "Private keys" text box.  Some other wallets export/show private keys with spaces, and it's very tiresome to manually remove these spaces from all the keys to be swept.

If you point me to the right location in Electrum's source, I'm happy to provide a patch.

**Comment by ecdsa** [comment]
I think that would be in qt/installwizard.py
currently spaces and new lines are handled similarly. if we introduce a distinction, we have to be careful about people entering their seed words on several lines

**Comment by andreas-h** [comment]
Mhh, if I understand the code correctly, changes would need to be done at https://github.com/spesmilo/electrum/blob/97c443a86d908d1ee5558d9da372a7b191bbd689/lib/wallet.py#L1997 and at https://github.com/spesmilo/electrum/blob/97c443a86d908d1ee5558d9da372a7b191bbd689/gui/qt/main_window.py#L2499.

The question is if such a change is wanted?  Currently, user can enter priv keys separated by spaces, tabs, and newlines.  If we change here, then the user would be forced to use newlines to separate keys, but would be allowed to have spaces within the keys. In that case, maybe the dialog should say something like *Please enter one private key per line*.  I could imagine introducing something like replacing `pk.split()` with `pk.replace(' ', '').split()`. But it would be a break of current behaviour.  I don't know if this is something you want or not.

**Comment by dabura667** [comment]
Why not use regex to find WIF keys with any whitespace inbetween, and bring up 0 matches if anything besides WIF keys or whitespace is present.

You could capture the key parts and generate a list from that using submatches (if I remember python regex correctly)

It would add your functionality without hurting any existing functionality.

**Comment by ecdsa** [comment]
this can be done now; we use a different widget for seeds and private keys

**Comment by ecdsa** [comment]
done in ac5929684699a458b4599b8c6e2dc65519ba94f7
