### ISSUE TITLE
Lost seed + Password

### ISSUE THREAD

**Issue by JayPeezy12** [spesmilo/electrum#1613]
I have about $110 worth of bitcoin in my wallet that i'm staring at that i cannot send. I kept my password and seed on a file on my computer that was deleted. I know this is for bugs but i was wondering if there was any possible way to recover my wallet.

**Comment by ecdsa** [comment]
not if you have lost both seed and password.
as I understand, you still have your seed, but it is encrypted.
maybe you can try to bruteforce the password, if it was an easy one

**Comment by JayPeezy12** [comment]
I believe it was a bunch of random numbers, do you think it is recoverable?
