### ISSUE TITLE
Electrum 2.5.4 Locale preferences don't appear to work

### ISSUE THREAD

**Issue by thrasher-** [spesmilo/electrum#1614]
I downloaded the Electrum 2.5.4 setup installer [https://download.electrum.org/2.5.4/electrum-2.5.4-setup.exe] for Windows 10 x64, installed it (fresh install) and it appears that adjusting the locale preference doesn't seem to work.

Just wondering if I'm missing anything to get this working?

**Comment by leafcutterant** [comment]
Confirmed on Win 7 x64, portable.

**Comment by losh11** [comment]
Confirmed on multiple Macs (OS X 10.10 and OS X 10.11).
Also confirmed on Windows 10.

**Comment by kyuupichan** [comment]
What are you expecting to see happen?  Where are you adjusting locale preference?

**Comment by thrasher-** [comment]
Expected to see the program strings adjust to the selected locale preference after restarting the client. 

I changed it via Tools -> Preferences -> Appearance and then selected any language (French) under the Language section. Restarted the client as per the prompt (made sure there wasn't any running instances) and then relaunched it, but did not notice any change take place.

**Comment by JanaNovakova** [comment]
Electrum v2.5.4 Portable
For portable version does not work change the language

**Comment by ecdsa** [comment]
this will be fixed in the 2.6 binaries.
