### ISSUE TITLE
Text box contents can flow "under" the elements (currency sign/icon) at the end of the text boxes

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#1616]
Both on Send and Receive tabs.

![clipboard01](https://cloud.githubusercontent.com/assets/7106231/12188455/d68cb616-b5b5-11e5-943d-3f79c2836e22.png)

**Comment by kyuupichan** [comment]
For valid input it should be fine.  Please reopen if you have an example of something valid, otherwise this isn't worth "fixing".
