### ISSUE TITLE
Problem with transactions

### ISSUE THREAD

**Issue by jfxsigaint** [spesmilo/electrum#1621]
Hello!

I put some money to my wallet, then made 2 payments. All transactions are showed in my bitcoin client (see attachment). But payments was not recieved and blockchain.info shows no transactions. What is the problem?

![111](https://cloud.githubusercontent.com/assets/16631202/12220346/6352ae5e-b767-11e5-8bd3-cd0c6a25d6cc.png)
![222](https://cloud.githubusercontent.com/assets/16631202/12220347/635422e8-b767-11e5-9b22-60e0b259d094.png)

**Comment by ecdsa** [comment]
probably that you did not send to the right address..
not much info here

**Comment by kyuupichan** [comment]
To OP: you can right-click and see the TX details including where the outgoing txs went to
