### ISSUE TITLE
can't download file on electrum.org site

### ISSUE THREAD

**Issue by abcabc0** [spesmilo/electrum#1625]
can't download file from electrum btc wallet site 

i need to update it cause i can't send my btc before i update it i already have the money inside 

please help i need it asap

**Comment by ErwinJanssen** [comment]
I have the same problem, download.electrum.org is unreachable. Connections time out.

**Comment by ecdsa** [comment]
fixed

**Comment by ZaneCEO** [comment]
Seems to be down again now. https://downforeveryoneorjustme.com/download.electrum.org
