### ISSUE TITLE
cannot send LTC or upgrade to newer version (new balance 0)

### ISSUE THREAD

**Issue by myghubuser2016** [spesmilo/electrum#1628]
I want to send LTC and I get the error message:

*error: Your client produced a transaction that is not accepted by the Litecoin network any more. Please upgrade to Electrum 2.5.1 or newer.*

My revision is 2.3.2.2.

I downloaded and installed electrum-2.5.4-setup.exe (I use Win 10 64 bit; but on my old Vista notebook its similar). I tried do it in different location and I tried to do it in same directory. I tried to do it with previous uninstall or not with uninstall.
I do File->New/Restore and then  "Restore a wallet or import keys" (Standard wallet).
After typing my wallet word the "Next" Button is enabled. I chose no password.
Electrum is generating my address ...
I do Auto connect
**And my Balance is 0 now.**
I open my Wallet with 2.3.2.2 again and I see my LTCs with non zero balance.

What shall I do now? I cannot send LTC with old 2.3.2.2 and in new version 2.5.4 I don't see my balance.

I exported private keys with the old version in csv and json format. 
But both are not accepted in 2.5.4 (Next Button stays gray, I select file with dialog box and tried with cut & paste too).

The network icon on bottom right is green.

Sorry, I am beginner. Probably I do something basic things wrong.

**Comment by ecdsa** [comment]
no LTC support here
