### ISSUE TITLE
Electrum error message

### ISSUE THREAD

**Issue by ghost** [spesmilo/electrum#1629]
I get an Electrum error message. 
And I export something with Electrum old version and its not possible to import it with new version.
Whats that? Is this an Electrum issue or not???
Electrum exports invalid keys and invalid json formats.
Electrum does not care that newer version should support older version.
Very helpful that the network has the error and not Electrum.
I did not forgot anything. With old version it worked with new not.

**Comment by myghubuser2016** [comment]
When you don't support it then say url where i can get help please. Or let topic open that others can answer.

**Comment by ecdsa** [comment]
not much usable information here...

**Comment by kyuupichan** [comment]
No useable info forthcoming
