### ISSUE TITLE
error: The transaction was rejected by network rules.(64:dust)

### ISSUE THREAD

**Issue by ghanielane** [spesmilo/electrum#1630]
I am using Electrum Version 2.5.4

I can't send money out anywhere, I seem to only be able to receive. 
Each time I try I receive the following error - "error: The transaction was rejected by network rules.(64:dust)"

My last attempt I tried to send 0.2 btc

**Comment by ecdsa** [comment]
does it help if you choose a different server? (eg ecdsa.net)

**Comment by cusa79** [comment]
I have exactly the same problem. I´m so angry with electrum... I have freeze my bitcoins due to it.
How can I choose a different server? Thanks!

**Comment by ghanielane** [comment]
Choosing a different server fixes this. On the bottom right corner, double click the green dot, uncheck "auto-connect" and double click a new server.

**Comment by cusa79** [comment]
Ohhhh! Thank you so much!
Knowledge is power....
Have a nice day and thanks again!
