### ISSUE TITLE
QR Code Generated Did Not Work

### ISSUE THREAD

**Issue by omouse** [spesmilo/electrum#1633]
I generated a QR code for one of the addresses in the wallet and it did not work. That's really all the info I can give because I tried scanning it with an ATM and it didn't work but then I tried the QR code for a new address from the bitcoin app on android and it did work.

**Comment by ecdsa** [comment]
may I suggest the problem is more likely to be with the ATM ?

**Comment by omouse** [comment]
Yep I can see that being the case, just wanted to report in case other people have the same issue.

Thanks!

**Comment by ecdsa** [comment]
just for the record, which QR code did you show ot the ATM ? 
the one in the receive tab of the Qt GUI, or another one?

**Comment by omouse** [comment]
From the addresses tab -> public key -> QR

I thought that this would just give me the address as a QR code that I
could share. Should I always be using the Receive tab QR code?

**Comment by ecdsa** [comment]
no that will not give you a bitcoin address
