### ISSUE TITLE
Sign complex transactions with Trezor

### ISSUE THREAD

**Issue by lukavia** [spesmilo/electrum#1634]
I have prepared a complex transaction using bitcoin-cli createrawtransaction, and one of the inputs has to be signed with Trezor. 
However when I load it in electrum and try to sign it I get the following error: 

``` python
Jan 16 13:27:58  Electrum[37720] <Notice>: Traceback (most recent call last):
Jan 16 13:27:58  Electrum[37720] <Notice>:   File "/opt/homebrew-cask/Caskroom/electrum/2.5.4/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/util.py", line 43, in run
Jan 16 13:27:58  Electrum[37720] <Notice>:   File "/opt/homebrew-cask/Caskroom/electrum/2.5.4/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/main_window.py", line 1246, in sign_thread
Jan 16 13:27:58  Electrum[37720] <Notice>:   File "/opt/homebrew-cask/Caskroom/electrum/2.5.4/Electrum.app/Contents/Resources/lib/python2.7/plugins/trezor.py", line 484, in sign_transaction
Jan 16 13:27:58  Electrum[37720] <Notice>: KeyError: 'x_pubkeys'
Jan 16 13:28:00  Electrum[37720] <Notice>: 2016-01-16 13:28:00.362 Electrum[37720:2829568] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
```

I'm not familiar with python but looking around in the code and playing around with the transactions I guess in order for this to work the scriptSig of the prepared transaction has to contain the pubkey. I think however that this is not necessary and can be changed if the pubkey is not there to get the address from the txHash and then if this is part of the opened wallet, so it can be signed. 

This will make Electrum the perfect tool for playing around with Trezor and transactions

**Comment by ecdsa** [comment]
the capability to combine trezor and multisig was added in 1159f85e053d14cf931f5b32444bda071860619c
I have not tested with a transaction generated by bitcoin-cli, there might be some incompatibilities, so not closing now

**Comment by bauerj** [comment]
I assume this works now. If that's not the case, please reopen the issue.
