### ISSUE TITLE
daemon creation is racy

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1638]
Daemon creation isn't race free.  I created two independent ones on my Mac just starting two sessions close together.  I wasn't even trying to trigger a race, so this must be easy.  Here's the log on shutdown of the later session:

[Network] stopping network
[Network] stopped
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/neil/src/electrum/lib/daemon.py", line 169, in run
    os.unlink(lockfile(self.config))
OSError: [Errno 2] No such file or directory: '/Users/neil/.electrum/daemon'

**Comment by ecdsa** [comment]
summary of previous attempts:

1. on posix systems, we can use a socket file; this is how the daemon used to work.
unfortunately, that will not work on Windows.

2. on any system, we can also lock the application with a socket and a hardcoded port number.
unfortunately, it will not work if the port is not available.

**Comment by kyuupichan** [comment]
I think we need something platform dependent from looking on the net. We can fix Mac and Unix in a few lines with the python fcntl API. This won't work for Windows but at least fixes two of the three platforms we support. Someone who uses Windows will have to test or supply something there, I will do the POSIX fix.

**Comment by kyuupichan** [comment]
I think this is fixable portably with O_EXCL and O_CREAT.  The problem doing that is mostly the structure of the current code.  What do you think?

**Comment by ecdsa** [comment]
that should work according to http://stackoverflow.com/questions/15071541/on-which-systems-filesystems-is-os-open-atomic

**Comment by kyuupichan** [comment]
OK I will try and figure out how to do this.  The main thing I see at the moment is that there is a gap between asking if a daemon exists and deciding to actually use it.  This isn't how we want it to be for O_EXCL and O_CREAT to be useful.

I was trying to narrow the gap with my daemon change but you reverted it.  Was there a problem with it, or was it just that I put start() in the constructor?  There is nothing in python docs saying that is bad; and it's just putting common code in one place from what I see.  Similarly for the network creation - why construct a daemon with a config, and not create the network there, when all the callers create the network from the config and then construct the daemon from both?  It's just moving common code to one place.

**Comment by ecdsa** [comment]
The python Thread class has a separation between thread initialisation and execution. It makes the code more difficult to read to violate that basic assumption, because it forces everyone else to learn about the particularities of your classes. 

I'm not religious about that, but in that particular commit the code looked dirtier after than before. I agree that network initialisation could be moved to the daemon.

Concerning the race condition, maybe get_daemon could return the lockfile, if it fails to connect to the daemon.

**Comment by kyuupichan** [comment]
Well it's a Network class, you don't even know it's a thread until you look at it... but anyway I'll leave the start() outside.

**Comment by kyuupichan** [comment]
If we go the O_CREAT route, for which I  have a mostly working version, the difficult part now is ensuring the lockfile is removed when the process exits.  I don't think we can do that, particularly as it might be shut down uncleanly.  So the best we can do is try and connect on seeing a lockfile, and if that fails, say twice in a row with a short random sleep in-between, start a server and replace the lockfile.  This reduces the scope for races but it seems impossible to eliminate them entirely.   What do you think?
