### ISSUE TITLE
Will Electrum switch to Bitcoin Classic?

### ISSUE THREAD

**Issue by en90** [spesmilo/electrum#1639]

**Comment by berdario** [comment]
This is a valid feature request, it'd be nice if @ecdsa actually elaborate while closing these issues.

If this needs more discussion, a thread somewhere might be a better fit, but the only place for a permanent discussion seems to be bitcointalk.org, which has the well known censorship problem when dealing with non-bitcoin-core stuff (though Bitcoin Classic is a shallow-fork that's as shallow as you can get)

**Comment by ecdsa** [comment]
This is not a feature request, it's a question, that is completely irrelevant for Electrum development, so it does not belong here. The decision to run a Bitcoin core or Classic belongs to Electrum servers operators, not to me. I do not have the power to impose them a particular choice.

That being said, I do not support Bitcoin Classic. I support Segwit.

**Comment by berdario** [comment]
Yup, I realized that this might've been better suited as an electrum-server issue and I updated my comment earlier.

Re. your support for Segwit: Good to know, I don't know the tradeoffs about it yet, but I'll educate myself on it

**Comment by en90** [comment]
I should probably have written a bit more in my original issue. I am using Electrum client and was just wondering about whether or not I'd still be able to send and receive transactions using Electrum client in case the majority of the people who use Bitcoin move to Bitcoin Classic. I don't know so much about Bitcoin, I just have a few satoshis which I bought online. Apologies for any confusion.

**Comment by dabura667** [comment]
> this might've been better suited as an electrum-server issue

It's not really even that.

electrum-server runs on Bitcoin. All these hardfork fad-implementations are literally just a change in a single value. afaik electrum-server doesn't even do anything with the max blocksize value, and it trusts that the underlying node software will check those rules for it.

So someone running Classic would be able to run electrum-server the exact same as someone running Core. It makes no difference.

**Comment by ABISprotocol** [comment]
Verification is an issue for the end user.  I wish to point out that I have struggled to convey the difficulty for end-users of being able to verify what the server operators are actually running.
For details on this please see [a bitcointalk thread which covers more of the issues](https://bitcointalk.org/index.php?topic=1157545.msg12196537#msg12196537).
