### ISSUE TITLE
Electrum 2.5.4 on Tails 1.8 - "NOT CONNECTED" - wont connect? have i lost my money? *PLEASE HELP

### ISSUE THREAD

**Issue by btchelptails** [spesmilo/electrum#1645]
hi guys

im worried as i have over 1000 deposited in my wallet, but i have updated tails and that updated electrum and now it just stays "not connected" 

any idea how i can get it to connect?

please help

thanks

**Comment by btchelptails** [comment]
and i cant see my funds or history etc as im not connected^

**Comment by kyuupichan** [comment]
Relax, if you have your seed your money isn't gone.  It sounds like you have a network issue; try connecting to a different server (network dialog / red circle at bottom right) and check  your other internet connections work

**Comment by btchelptails** [comment]
@kyuupichan Neil thanks for your quick response. Thats made me feel better lol.

I have clicked the red circle and changed the server multiple times, but it just doesn't seem to want to do anything. everything remains "not connected" 

is there an actual "start connection" type button that im missing?

my internet seems fine as tor is working, should I try without SSL? I noticed I couldn't get on IRC earlier due to SSL issue. Or am i way off with that thought process?

**Comment by ecdsa** [comment]
dont use ssl over tor

**Comment by btchelptails** [comment]
@ecdsa I've unticked "use SSL" on the network dialog, I've tried every server, still not connected.

**Comment by gits7r** [comment]
@btchelptails you have updated Tails and probably you still have the old config file in ~/.electrum (the one for Electrum 1.9.8 which is incompatible with 2.5.4).

Please do the following (hope you still have the seed to restore the wallet):
Make sure Electrum is closed.
Open a console window (Choose Applications -> Accessories -> Terminal) and type exactly this command:

echo '{"auto_connect": true, "proxy": "socks5:localhost:9050"}' > ~/.electrum/config

Start Electrum again and tell us if it connects.

**Comment by abbasranjbar1988** [comment]
Hi guys this is very simple to solve problem "NOT_CONNECTED" in electrum-xvg wallet If you have problem with #electrum-xvg by showing "NOT_CONNECTED" you should get private key by right clicking to your address and select private key then you should download COINOMI android app and add XVG (Verge) in it. finally, choose "sweep wallet" in coinomi app then enter your private key and it shows your coin in coinomi and you can send your XVG to any address. i hope this was good for you.

**Comment by ZebbHB** [comment]
Great!
But I already have a verge wallet in coinomi with some coins in it - can I add a second verge wallet, or should I create a totally new coinomi wallet/account?

**Comment by abbasranjbar1988** [comment]
@ZebbHB 
I didn't test it, i had a coinomi wallet like you and first i created a new coinomi wallet in another device then recover my XVG by my private key. finally i transfferd my XVG from new wallet to old wallet.
good luck friends :)
