### ISSUE TITLE
Electrum crashes

### ISSUE THREAD

**Issue by frutta007** [spesmilo/electrum#1659]
I installed Electrum on Windows 10 (64bit) after creating a wallet the program just closed itself without any error or sign. After i try to open it the icon appear in tray and in 1 second shuts down. 

The same was when i installed windows 7 (32 bit) on virtual drive.

I cannot find the same problem on the web and dont know what seems to be the problem.

Please help.

**Comment by ecdsa** [comment]
I cannot help you if you don't provide a traceback, or a log of your system that shows what hapened.

**Comment by PocketSam** [comment]
Same problem here. Where can I find a logfile?

**Comment by ecdsa** [comment]
try to launch electrum from a console

**Comment by PocketSam** [comment]
Windows doesn't output anything. (Win 10 x64 as in the issue description) Probably I could make a traceback, but I need some kind of instruction, as I'm not skilled enough for this. :(

**Comment by PocketSam** [comment]
If I try to run portable app it says 
![_039](https://cloud.githubusercontent.com/assets/1718821/17276941/05af0744-5761-11e6-9baa-f7f814dfef6b.png)

But after I click OK it shows first run wizard.

**Comment by PocketSam** [comment]
If I'm not mistaken version 2.4.4 installed and works fine.
