### ISSUE TITLE
Upload on PyPI

### ISSUE THREAD

**Issue by almet** [spesmilo/electrum#1667]
Hi, and thanks for you work!

I was wondering why this package wasn't published on PyPI, and why you recommend installing it via the .tar.gz archive.

Thanks,

**Comment by ecdsa** [comment]
because it adds one element to the chain of trust

**Comment by almet** [comment]
I would actually be way more confident having a signed package -- with GPG -- on PyPI (see how to do here) rather than relying only on a SSL certificate: the contents can be tempered with by the server owners or by anyone who gains access there.

You can read more about how to upload and sign packages to the python package index [here](http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#uploading-your-project-to-pypi).

HTH

**Comment by ecdsa** [comment]
pip does not verify GPG signatures client side, does it?

**Comment by ecdsa** [comment]
so, closing this.
I don't think it's a good idea to distribute via PyPI, until they provide client-side verification.
Otherwise, it just adds another element that one has to trust.
