### ISSUE TITLE
Compile instructions at contrib/build-wine do not work

### ISSUE THREAD

**Issue by PokerBeast** [spesmilo/electrum#1670]
I've followed those instructions precisely, tried different docker configurations, followed instructions on other issues here.

For the life of me, I can't generate an exe.

Could you update the instructions, so we can follow your steps in compiling the latest version?

Thank you.

**Comment by ecdsa** [comment]
some paths need to be updated. I will assume that's your issue, because you are not providing any useful information.

**Comment by ecdsa** [comment]
fixed in 62f2095faa0c285118ce7d3fad22b675d4b2af5c

**Comment by Alex-Jaeger** [comment]
Hi, I'm sorry, I wasn't clear in my original post and the text reads a bit rude now that I went back to it.
After running prepare-wine.sh and prepare-hw.sh, when running build-electrum-git.sh, I get an error with the line "cp -r ../../../packages $WINEPREFIX/drive_c/electrum/", saying it can't find the source.

If I try to run "make_packages, I get:

`version 2.6.1
Traceback (most recent call last):
  File "./electrum-master/contrib/make_packages", line 28, in <module>
    f, pathname, descr = imp.find_module(module)
ImportError: No module named aes
`
If I comment that line, the next step also fails, "cp -r ../../../lib/locale $WINEPREFIX/drive_c/electrum/lib/", with the same error, the source is non-existent.

Finally, if I comment that line,I get:

`Pull
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Last commit: 2.6.1
230 INFO: Testing for ability to set icons, version resources...
289 INFO: ... resource update available
294 INFO: UPX is not available.
334 INFO: Processing hook hook-os
561 INFO: Processing hook hook-time
565 INFO: Processing hook hook-cPickle
726 INFO: Processing hook hook-_sre
1016 INFO: Processing hook hook-cStringIO
1226 INFO: Processing hook hook-encodings
1256 INFO: Processing hook hook-codecs
Traceback (most recent call last):
  File "C:/pyinstaller/pyinstaller.py", line 18, in <module>
    run()
  File "C:\pyinstaller\PyInstaller\main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\pyinstaller\PyInstaller\main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\pyinstaller\PyInstaller\build.py", line 1924, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\pyinstaller\PyInstaller\build.py", line 1873, in build
    execfile(spec)
  File "deterministic.spec", line 24, in <module>
    hookspath=[])
  File "C:\pyinstaller\PyInstaller\build.py", line 409, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'C:\electrum\packages/requests/utils.py' not found
`

Thank you!

**Comment by ecdsa** [comment]
before you run make_packages you need to install all the python dependencies
