### ISSUE TITLE
File|Open a bitcoin txn could be more friendly

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1671]
Instead of tools|load transaction I did File|Open and get thrown into an install wizard giving me a seed to write down.

This isn't very friendly; we should give an error message if the file cannot be read as a wallet file rather than trying to create a new wallet out of it.

**Comment by ecdsa** [comment]
I agree.
note that this is not expected behaviour; the app crashes if I try to open a non-json file

**Comment by ecdsa** [comment]
a related note: in order to reduce the chance of users opening the wrong type of file, we could have a dedicated directory for transactions, like we have for wallets.

**Comment by kyuupichan** [comment]
In my case I was sent the tx; I don't think that would have helped me.

**Comment by ecdsa** [comment]
fixed in b69cb213335481aeb3d7d9363d4871159d427d51
