### ISSUE TITLE
trezor/keepkey: when requesting passphrase, only require it be input once

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#1672]
At present you have to type it twice.  I don't see much value in that; you only enter your PIN once for example.  And if you type it wrong you get a clear message saying the device could not pair.

When creating a wallet you should be asked twice, of course.

**Comment by prusnak** [comment]
> And if you type it wrong you get a clear message saying the device could not pair.

You would need to store the hash of the passphrase somehow to detect this.

**Comment by kyuupichan** [comment]
We do it already without a hash...

**Comment by prusnak** [comment]
So you store the passphrase? That is not good.

**Comment by kyuupichan** [comment]
Or, more likely, your premise was false.
