### ISSUE TITLE
Can't sign/verify message with Ledger hardware wallet on Windows

### ISSUE THREAD

**Issue by filchef** [spesmilo/electrum#1675]
When I try to sign/verify message there is warning window which say I have to open text editor and unplug and plug again token but noting happened when I do it and I can't see correct pin - my Electrum is last stable version 2.5.4

**Comment by ulrichard** [comment]
Can you try it on linux?

**Comment by filchef** [comment]
No I didn't try on Linux because I am not Linux user. If you use Linux can you try to sign message with Ledger.

**Comment by ulrichard** [comment]
I regularly sign transactions with Ledger HW1.
Sometimes you have to wait a few seconds for the virtual keyboard to start typing the details. 
Can you try plugging it into another computer for the second factor?

**Comment by filchef** [comment]
> I regularly sign transactions with Ledger HW1.
Sometimes you have to wait a few seconds for the virtual keyboard to start typing the details.
Can you try plugging it into another computer for the second factor? > 

This issue its not for transaction - this Issue is for sign/verify MESSAGE please try to sign/verify MESSAGE

**Comment by ulrichard** [comment]
Powercycle then confirm signature of .test. for address 1Bw3fPcgf578ZM1S2WS7FZv2
K8EQymT9pV with PIN 1234

IAKGQ7pb8n2pP+SBXG984X8hbZ0OWcrWjyyyVSr5RuJGfaxENbZ4+m/9vFT9IKwoPdll1AvX7i6V6waffYRyT6s=

Signature verified

**Comment by filchef** [comment]
Did you do this on linux or Windows

**Comment by ulrichard** [comment]
On linux. I don't have a Windows box to test.
It took longer than usual to start typing. 
When I used the device on windows in the past, sometimes the first part of the message didn't make it into the text editor. But the last part with the TAN was always there.

**Comment by ulrichard** [comment]
Just to be sure, the token is configured to use keyboard 2FA and not with keyCard?

I just checked in the code. keyCard is not currently implemented for signing messages.

**Comment by filchef** [comment]
No my is new HW.1 and I have  keyCard  so can I reconfigure It

**Comment by ulrichard** [comment]
I don't know if you can change it after initialization. 

You can try it with btchip_setAlt2FA from btchip-c-api. 

If the token is only for testing, you can probably reset it (by entering a wrong pin three times) and then reinitialize it with the keyboard2FA method.

**Comment by filchef** [comment]
So I am not familiar with Linux and Git so I will waiting next firmware update from Ledger.I ask support about sign/verify message and hi told me will be possible after next firmware update.

**Comment by ecdsa** [comment]
I can sign a message with the ledger nano S. it does not display the message on its screen, though, but only the hash of the message, which does not really increase security.
