### ISSUE TITLE
import queue problem

### ISSUE THREAD

**Issue by mf0hka** [spesmilo/electrum#1676]
running electrum after fresh install, from the command-line. (debian 8)
```
$ electrum 
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 30, in <module>
    import Queue
```

ok fine. So I changed that import to:
`from multiprocessing import Queue`

then got this error:
```
  File "/usr/local/bin/electrum", line 50, in <module>
    import aes
  File "/usr/local/lib/python3.4/dist-packages/aes.py", line 643
    raise ValueError, emsg % keysize
```

ok, to be fair, I didn't see that aes import error until just now, so Ill look into that. 
I haven't explored the source code yet. I was hoping to just install this. Is the assertion on`  from multiprocessing import Queue` correct for Queue?

**Comment by wozz** [comment]
can you make sure you're using python2?

**Comment by mf0hka** [comment]
Ah, then why is python3 explicitly specified? on the first line of /usr/local/bin/electrum ?
thats kinda confusing. 
Could change the import expectations, pending on version
```
#!/usr/bin/python3
try:
    # for Python2
    from package import *
except ImportError:
    # for Python3
    from someOtherPKG import *
```

**Comment by wozz** [comment]
https://github.com/spesmilo/electrum/blob/master/electrum#L1

It looks like it should say python2 to me.  I'm not sure where you got the file you have at /usr/local/bin/electrum

**Comment by kyuupichan** [comment]
Looks like a local modification / package manager issue.  Electrum is very much Python2 only at the moment,

**Comment by brianbowles** [comment]
i just installed electrum and the first line of my electrum file says python3.4 and I get the same error.  Ugh.
