### ISSUE TITLE
change request: 

### ISSUE THREAD

**Issue by mf0hka** [spesmilo/electrum#1677]
Real minor, but in the *nux version, change the first line from 
 #!/usr/bin/python3
 to 
 #!/usr/bin/env python3

[This SO post might clarify the compatibility issue that may warrant the change.](http://stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script)

**Comment by kyuupichan** [comment]
Electrum is Python 2

**Comment by mf0hka** [comment]
You say this, but `cat /usr/local/bin/electrum`
