### ISSUE TITLE
import dependency recomend doesnt recomend a package name.

### ISSUE THREAD

**Issue by mf0hka** [spesmilo/electrum#1678]
From /usr/local/bin/electrum
 ```
except ImportError as e:
      sys.exit("Error: %s. Try 'sudo pip install <module-name>'"%e.message)
```
doesn't echo string module name.
(Im not a python dev, but maybe I can figure this out:)
%e is an exponent, and %s is a string. if the missing module were to be listed, it would need to be a variable, which if it is, I cant find it.  I'd also guess that message is a system reserve word, but I have no idea. I think the exception handle you want would look something like this:
```
except ImportError as e:
   # sys.exit("Error: %s. Try 'sudo pip install <module-name>'"%s.message)
    e = e.replace("No module named '", "")
    e = e.replace("'", "")
    sys.exit("'Error: Try sudo pip install %s'" % e)

```

**Comment by mf0hka** [comment]
python3 might format the output of importError a little differently.

**Comment by ecdsa** [comment]
use python2
