### ISSUE TITLE
Can't send transaction with Ledger when "Use change addresses" is unchecked - Windows

### ISSUE THREAD

**Issue by filchef** [spesmilo/electrum#1679]
Can't send transaction with Ledger when "Use change addresses" in settings is unchecked.
I like to use the same address for change of transaction to consolidate bitcoins in one address  but with Ledger this is impossible.Give me error "Multiple outputs with no change not supported"
Version of Electrum 2.5.4

**Comment by kyuupichan** [comment]
Sounds like a hardware limitation.  I'm really not clear why they enforce all this daft rules; it's not just Ledger.

**Comment by ecdsa** [comment]
it works for me, with the ledger nano S. the only problem is that it displays the wrong address on the  screen, but that's a separate issue.
