### ISSUE TITLE
wont gather any confirmations; 6+ hours ? - linux - 2.5.4

### ISSUE THREAD

**Issue by shadycarrot1258** [spesmilo/electrum#1680]
Tried to send my coins and it has been on 0 confirmations for 6 hours now.. I don't understand. There is no way to cancel the transaction.. it showed up on the blockchain.info. So i dont really understand what is going on....
Please help.. Quite a bit of money floating...
Thanks in advance. 
Shady

**Comment by abitfan** [comment]
Should be confirmed by now but if not post the transaction id
