### ISSUE TITLE
slowaes broken

### ISSUE THREAD

**Issue by alekna** [spesmilo/electrum#1689]
[lauris@alpha ~]$ sudo pip3 install --upgrade https://download.electrum.org/2.6/Electrum-2.6.tar.gz
[sudo] password for lauris: 
You are using pip version 7.1.0, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting https://download.electrum.org/2.6/Electrum-2.6.tar.gz
  Using cached https://download.electrum.org/2.6/Electrum-2.6.tar.gz
Collecting slowaes>=0.1a1 (from Electrum==2.6)
Requirement already up-to-date: ecdsa>=0.9 in /usr/lib/python3.4/site-packages (from Electrum==2.6)
Requirement already up-to-date: pbkdf2 in /usr/lib/python3.4/site-packages (from Electrum==2.6)
Requirement already up-to-date: requests in /usr/lib/python3.4/site-packages (from Electrum==2.6)
Requirement already up-to-date: qrcode in /usr/lib/python3.4/site-packages (from Electrum==2.6)
Requirement already up-to-date: protobuf in /usr/lib/python3.4/site-packages (from Electrum==2.6)
Requirement already up-to-date: dnspython in /usr/lib/python3.4/site-packages (from Electrum==2.6)
Requirement already up-to-date: jsonrpclib in /usr/lib/python3.4/site-packages (from Electrum==2.6)
Requirement already up-to-date: colorama in /usr/lib/python3.4/site-packages (from qrcode->Electrum==2.6)
Requirement already up-to-date: six in /usr/lib/python3.4/site-packages (from qrcode->Electrum==2.6)
Requirement already up-to-date: setuptools in /usr/lib/python3.4/site-packages (from protobuf->Electrum==2.6)
Building wheels for collected packages: Electrum
  Running setup.py bdist_wheel for Electrum
  Stored in directory: /root/.cache/pip/wheels/56/a2/0f/52a49797d90cb6086f20e919ed79930d9bd72a0f936072efa9
Successfully built Electrum
Installing collected packages: slowaes, Electrum
  Found existing installation: Electrum 2.6
    Uninstalling Electrum-2.6:
      Successfully uninstalled Electrum-2.6
Successfully installed Electrum-2.6 slowaes-0.1a1
[lauris@alpha ~]$ electrum 
Traceback (most recent call last):
  File "/usr/bin/electrum", line 72, in <module>
    check_imports()
  File "/usr/bin/electrum", line 46, in check_imports
    import aes
  File "/usr/lib/python3.4/site-packages/aes.py", line 643
    raise ValueError, emsg % keysize
                    ^
SyntaxError: invalid syntax

**Comment by ecdsa** [comment]
I think you need python2

**Comment by ecdsa** [comment]
yeah, you used pip3 instead of pip
