### ISSUE TITLE
can't do online unsigned transaction after electrum upgrade to 2.6

### ISSUE THREAD

**Issue by ortolda** [spesmilo/electrum#1691]
After electrum upgrade from 1.9.7 to 2.6, "send unsigned transaction" button is not shown anymore.  Now only a "send" button in shown.  Using such button, the saved transaction is not parsed anymore by the cold storage electrum.
Can anyone help?

Thanks you in advance

**Comment by kyuupichan** [comment]
Transaction formats for 1.x and 2.x are incompatible.

**Comment by ecdsa** [comment]
indeed, you need to upgrade your software on the cold storage too

**Comment by ortolda** [comment]
Thank you Thomas.
Your quick response is very much appreciated.

Actually I kind of realized that after a deeper look at the documentation.
Now you confirmed that.
Thank you again


2016-02-29 8:16 GMT+01:00 ThomasV <notifications@github.com>:
