### ISSUE TITLE
Transactions stuck on pending

### ISSUE THREAD

**Issue by 275LdFV40fqAQ** [spesmilo/electrum#1692]
Electrum 2.5.4
transactions: 
**03a0de698b415b0123f58c4a86872e5652601e8f9115547bc74564bf4cf96be0**
And 
**dbce907bed8a048a4d0cd60477aafd8ec533c05afc79e2165292fb5e683cdd41**
have been stuck on "pending" for several hours and still have 0 confirmations.
Please advise what can be done to fix this.
Thank you

**Comment by ecdsa** [comment]
you need to pay more fees if you want your transactions to be processed quickly.
you cannot change the fee after the transaction is sent; you can try to chreate a child transaction, though. google for "child pays for parent"
