### ISSUE TITLE
In the console I cannot get command list

### ISSUE THREAD

**Issue by bravefish** [spesmilo/electrum#1693]
Supposed to be 
>>help()
List of commands: contacts, create, createmultisig, createrawtransaction, daemon, decoderawtransaction, deseed, 
dumpprivkey, dumpprivkeys, freeze, getaddressbalance, getaddresshistory, getaddressunspent, getbalance, getconfig, 
getmpk, getproof, getpubkeys, getrawtransaction, getseed, getservers, getutxoaddress, getversion, help, history, 
importprivkey, listaddresses, listunspent, mksendmanytx, mktx, password, payto, paytomany, restore, sendrawtransaction, 
setconfig, setlabel, signmessage, signrawtransaction, unfreeze, validateaddress, verifymessage

But currently I get
>> help()
Traceback (most recent call last):

**Comment by ecdsa** [comment]
fixed in 40281a3193e7d3b6da5b03ea1196fa29a2452258
