### ISSUE TITLE
Pending

### ISSUE THREAD

**Issue by leburto** [spesmilo/electrum#1694]
Transaction id
1b4e8efa8b4ce2d1381ce9743147044ed380f52cc90cb7926c42e0ca324af8e5
and
cac15abd9e01ebdddd50b47e6b8fba94ce48ade9969910dc809b42ba5e656c39
have been sitting pending for a while with no confirmations
Please help as this transfer is kind of desperate

**Comment by ecdsa** [comment]
see #1692

**Comment by leburto** [comment]
So how long will this take if just left?

**Comment by ecdsa** [comment]
I don't know. 
see also https://bitcoinfees.github.io/#3h
