### ISSUE TITLE
'NoneType' object has no attribute 'getitem' v2.6 on Win7 on sending tx 

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#1696]
Reported error on reddit with v2.6.0
Win7, freshly recovered seed, when user tries to send funds he gets the error 
"'NoneType' object has no attribute 'getitem'"

Thread is https://www.reddit.com/r/Bitcoin/comments/485ssp/help_recovering_an_electrum_wallet/

Not sure if this was fixed by either bug #1688 or bug #1690

**Comment by ecdsa** [comment]
probably not.
without a complete traceback, it will be difficult to see what it is

**Comment by EagleTM** [comment]
I did a simple test and couldn't reproduce on Win 7, so at least it's nothing trivial.

**Comment by ecdsa** [comment]
could be related to #1716

**Comment by ecdsa** [comment]
since the user was drunk and the wallet did not prompt for passsword, I think it is likely he recovered a watching-only wallet from a bitcoin address. I asked on reddit. will close this if he does not answer.
