### ISSUE TITLE
Transaction suddenly hidden?

### ISSUE THREAD

**Issue by NekNekx** [spesmilo/electrum#1697]
I dont know if this was reported but i received a payment 2 hours ago and it showed up in my wallet. After 2 Hours of still not confirmed (damn you servers) it suddenly wasnt shown in my wallet anymore. If i check my chain the network still knows that its in my wallet and there where no transactions after that. Still unconfirmed though. I dont know if electrum removes them from the list after a time if not confirmed or not never saw that though .

**Comment by ecdsa** [comment]
if the fee is low, it's also possible that thetransaction was not propagated to the whole Bitcoin network.
Bitcoin nodes have different relayfee settings.

**Comment by NekNekx** [comment]
Well i received the payment with a 0.001 fee According to numerous pages it should be enough to get a confirm in 10-15 minutes its now 5 hours almost with 0 confirms....exchange vendor just said the server are busy......
