### ISSUE TITLE
use all "!" for multiple outputs

### ISSUE THREAD

**Issue by LukAss741** [spesmilo/electrum#1698]
Hi. I really like the use all "!" feature. Anyway it would be really good if it was possible to use in a transaction with multiple outputs. In example wallet balance is 5 BTC and in send->pay to field there is:
address1,1.5
address2,2
address3,!

! should be replaced by: wallet balance - outputs in addresses - fee. In this case ! should be replaced with: 5-1.5-2-fee.

**Comment by kyuupichan** [comment]
I agree, I've missed this

**Comment by ecdsa** [comment]
The current syntax means "send 100% minus fees to this address"
If there are multiple outputs, I think it would be better to augment the syntax.
I am looking for some easy way to send fractions of the total to fiven tx outputs.
for example "send 25% to X, 75% to Y"

**Comment by ecdsa** [comment]
The "user friendly" way would be to ask the user to write percentages, eg "25%" 
`<address1>, 25%
<address2>, 75%`
(that requires the sum  to be 100)

The "mathematically correct" way would be to use weights
`<address1>, 25!
<address2>, 75!`
This does not require to check the total, and allows to write non-decimal fractions:
`<address1>, 1!
<address2>, 2!`

**Comment by LukAss741** [comment]
ecdsa, do you mean both exact amounts with ! for the rest and percentual fractions would be implemented or only fractions? I don't think fractions are wery useful as people typically want to send an exact amount in example to buy or eachange something for 1.123456 btc and then send the rest to another address using "!".

**Comment by ecdsa** [comment]
the use case is people sharing some revenue

**Comment by ecdsa** [comment]
@LukAss741  your use case sounds more like "send change to this address"

**Comment by molecular** [comment]
I'm interested in the "send change to this address" use case originally described. The "sharing revenue" use case seems there could be demand, too.

**Comment by SomosPolvo** [comment]
¿Es esto posible justo ahora? ¿Se puede enviar el cambio a otra dirección usando ese atributo?
