### ISSUE TITLE
TX still pending

### ISSUE THREAD

**Issue by 275LdFV40fqAQ** [spesmilo/electrum#1699]
I brought this problem up a day or two ago:
"Transactions stuck on pending:
Electrum 2.5.4
transactions:
03a0de698b415b0123f58c4a86872e5652601e8f9115547bc74564bf4cf96be0
And
dbce907bed8a048a4d0cd60477aafd8ec533c05afc79e2165292fb5e683cdd41
have been stuck on "pending" for several hours and still have 0 confirmations.
Please advise what can be done to fix this.
Thank you"

and I was advised, "you need to pay more fees if you want your transactions to be processed quickly..."
The thing is that 1) I paid the exact same fee for these tx's (0.00005 and 0.00006 respectively) as previous ones and 2) I'm not even trying for "quickly" at this point as much as I am a reasonable amount of time (it's been two days so far). As I mentioned, I paid the same tx fee previously and they were confirmed in less than one hour. What has changed? Is there something else going on?
Thanks for you help

**Comment by ecdsa** [comment]
see https://bitcoinfees.github.io/#3h
