### ISSUE TITLE
[Android] Add build instructions

### ISSUE THREAD

**Issue by dllud** [spesmilo/electrum#1701]
Please add instructions on how to build the Android apk from source into https://electrum.org/#download 

You have instructions for all other platforms, only Android is missing.

**Comment by ecdsa** [comment]
The build instructions are in gui/kivy/Readme.txt
However, the difficult part is to install and learn how to use Kivy. 
Therefore, I don't think it makes sense to add instructions to the download page.

**Comment by dllud** [comment]
Thus place there a link to gui/kivy/Readme.txt

Being complex to build is no good argument to omit build instructions. Actually it should prompt you to simplify the build process or write better instructions.

As you correctly did for all other platforms, having build instructions is a must for any open-source project. It will ease the life of those that want to add their modifications or experiment with Electrum. Like any other open-source project, Electrum will gain a lot if it welcomes new contributors.

**Comment by dabura667** [comment]
The old Android client didn't have instructions to build on the website.

imo I always thought that the build from source instructions were not necessary on the website, but rather should be on the readme.md in the root of the repo only.

**Comment by dllud** [comment]
> The old Android client didn't have instructions to build on the website.

Because it wasn't built. The old Android client was pure Python code that was directly interpreted.

> I always thought that the build from source instructions [...] should be on the readme.md in the root of the repo only.

Agreed! That's a good place for them. The download page can be made simpler and more user-friendly, while Readme.md becomes developer-friendly. The problem right now is that the build instructions are buried in the repo.

**Comment by ecdsa** [comment]
done, see 1af48b3769a2649cf73465b4d4c8bc0ec59f60ff
