### ISSUE TITLE
2FA restore no longer works as documented in 2.6+

### ISSUE THREAD

**Issue by badmofo** [spesmilo/electrum#1704]
The 2FA restore procedure before 2.6 would (by design) result in a wallet that could spend without the 2nd factor as documented here:

http://docs.electrum.org/en/latest/2fa.html#restoring-from-seed

Starting with 2.6 the restored wallet is missing:

`wallet["master_private_keys"]["x2"]`

which breaks the functionality. 

I suspect the fix is to add: 

wallet.add_xprv_from_seed(' '.join(words[n:]), 'x2/', password)

In the vicinity of:

https://github.com/spesmilo/electrum/blob/305843999eabdb4276109e3dc6b70bf21dbbc29a/plugins/trustedcoin/trustedcoin.py#L360

**Comment by ecdsa** [comment]
thanks for the info. 
I will create new binaries asap

**Comment by badmofo** [comment]
There's a typo in your fix: xpv should be xprv I think
