### ISSUE TITLE
[Android] Store data on /data/data not /sdcard

### ISSUE THREAD

**Issue by dllud** [spesmilo/electrum#1706]
Electrum should follow Android guidelines and store all its data on `/data/data/org.electrum.electrum/`.

Currently Electrum stores configurations and sensitive information (wallets) on `/sdcard/electrum/`. This is wrong on many levels:
- Security/Privacy: on most devices, Full Device Encryption (FDE) only encrypts `/data` directory. Files on `/sdcard`are left out. Thus, someone finding my lost phone instantly gets my wallet. He can now see all my addresses and transactions, and is one simple PIN away from spending my Bitcoins.
- Backup: virtually all backup methods for Android work by copying what is on `/data`. Files on `/sdcard` are left out. Thus, Electrum's `config` file won't get backed-up.

`/sdcard` should only be used for large data files, that are neither user configurations or sensitive information, and which can be easily retrieved through the Internet. Two good examples are [OsmAnd~](http://osmand.net/) map files and [QuickDic](https://github.com/rdoeffinger/Dictionary) dictionaries.
On Electrum, `blockchain_headers` would be a good candidate to be on `/sdcard`. ~~Though, looking at the current picture, it's not worth to keep an sdcard directory just for it. `blockchain_headers` is 5 MiB big, which is little compared to the 30 MiB of Python bytecode currently stored on `/data/data/org.electrum.electrum/`.~~

(On previous versions this unwanted behaviour was easy to change in the Python scripts. But now, with the Kivy version, things are more complex as the apk brings Python bytecode.)

**Comment by ecdsa** [comment]
ACK. The wallets are stored on /sdcard for compatibility with the previous android version, but that version is now derecated, so we can change that.

note that blockchain_headers is 30Mb currently.

**Comment by dabura667** [comment]
+1

**Comment by dllud** [comment]
> note that blockchain_headers is 30Mb currently.

That way better leave it in `/sdcard/electrum`. 30 MiB is too much already, and `blockchain_headers` is a good candidate to stay in the sdcard (as explained above).

**Comment by ecdsa** [comment]
it seems we cannot use internal storage until this is resolved:
https://github.com/kivy/python-for-android/pull/350

thanks @akshayaurora for the info

**Comment by ecdsa** [comment]
ok, this commit shoud fix it: 4c7bbb4e865aaf533d4c37d967771e0ac2ca6ede
It needs more testing before it can be deployed.

**Comment by ecdsa** [comment]
tests look good. will release a new apk today.

**Comment by ecdsa** [comment]
done. closing

**Comment by dllud** [comment]
Tested and working good. Thanks for being this quick!
