### ISSUE TITLE
[Android] Integrate with Orbot or add proxy settings

### ISSUE THREAD

**Issue by dllud** [spesmilo/electrum#1707]
Electrum for Android should add Orbot integration. That way users without rooted devices\* will be able to connect through Tor.
The easiest way to use Orbot is through [OnionKit](https://guardianproject.info/code/onionkit/) library, though I don't know whether it is possible to interface with it from your Python code.

As a workaround, you should at least add SOCKS proxy support as present in the desktop version.

\* Users with rooted devices can already use Tor through Orbot's transparent proxying. Though, this is an error prone setup. If Orbot is accidentally turned off Electrum will connect through the clearnet.

**Comment by ecdsa** [comment]
added in 59b0b51f248feb0e25cac238f329c31c7b3eb4b0
