### ISSUE TITLE
[Android] Pre-xpub MPK format defaults to used address

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#1709]
The receive tab in Android shows my first used/hidden address in OSX. I would have expected it to show the first unused address due to the 1-time-use address policy.

**Comment by ecdsa** [comment]
I believe this is a refresh issue.
does it persist if you restart the app?

**Comment by TheButterZone** [comment]
Ok, the 2.6.2 update was stuck, had to force stop the unresponsive Google Play Store and restart the installation.

It didn't seem to want to connect to electrum.jdubya.info, so I put it on auto-connect, and it did switch the receive address to first unused.
