### ISSUE TITLE
Electrum for websites: addrequest error

### ISSUE THREAD

**Issue by Satevg** [spesmilo/electrum#1713]
I follow [this doc](http://docs.electrum.org/en/latest/merchant.html)
And in cli: `electrum addrequest 1 -v`
I'm getting
`jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/electrum/pem.py", line 154, in _parsePKCS8 | NameError: global name \'bytestr_to_int\' is not defined')`

Electrum version - 2.6.2

**Comment by ecdsa** [comment]
thanks
