### ISSUE TITLE
Sending 20.187 bitcoin freezing

### ISSUE THREAD

**Issue by word20** [spesmilo/electrum#1714]
I have tried to send 20.187 bitcoins but it is unconfirmed after 30 minutes.
If this wallet should function as usual, there should not be any unconfirmed transaction after 5 minutes.
What is the reason that this is unconfirmed after so long time?
I think that this is bad functionality and not user friendly at all.

**Comment by ecdsa** [comment]
please learn how bitcoin works, and why there are transaction fees.
