### ISSUE TITLE
Watch-only public-address "payto" transaction cannot be signed with "signtransaction"

### ISSUE THREAD

**Issue by jaafit** [spesmilo/electrum#1715]
Summary: A transaction created by payto from a watch-only wallet containing one public address cannot be signed with signtransaction, yet this same transaction can be signed via Tools > Load transaction.

**1** create watchonly address with one bitcoin address
**2** electrum payto -u -w ~/.electrum/wallets/watchonlyone -f 0.0005 -F 1M3MD3C8fkSuHH7UNXfWbPPR26r7dgRdJs -c 16kbyj3XiyHJLQJas1RVx9ppBmWWdv4FZR 16kbyj3XiyHJLQJas1RVx9ppBmWWdv4FZR 0.001
**3** electrum signtransaction -v --privkey "?" "{
    \"complete\": false, 
    \"hex\": \"010000000137d4a7ba2548f460ccf935a208bd3997fa0459a6d6e0aaaa0de22e03ed664ceb000000001901ff16fd00dbd4374c7c5591e6f905d7098aa558c2c44e79f0ffffffff0204550100000000001976a9143f17b6a4d4ce55348ead4d1c9e6eef515d4aee0888aca0860100000000001976a9143f17b6a4d4ce55348ead4d1c9e6eef515d4aee0888ac00000000\"}"

**Expected result:** a new transaction with "complete":"true"
**Actual result:** the same exact transaction

I suspect that it's because the "signatures" array has one "null" item and this is counted as good enough in Transaction:sign
`if len(signatures) == num:`
                    # txin is complete
                    `break`

Note: I have not tried wallets other than this one watch-only wallet with exactly one address imported.

**Comment by ecdsa** [comment]
the issue is with --privkey
