### ISSUE TITLE
Watch-only wallet with one address cannot Send

### ISSUE THREAD

**Issue by jaafit** [spesmilo/electrum#1716]
Summary: A wallet with only one bitcoin address fails to create transactions from the Send tab.

Steps:
**1** Create a new wallet choosing to "Restore a wallet or import keys"
**2** Enter a bitcoin address that has a balance.
**3** In the Send tab, click Send, then Yes to confirm.

**Expected result:** A dialog box allowing user to save the transaction.
**Actual result:** 'Nonetype attribute has no attribute '__getitem__'

**Comment by ecdsa** [comment]
ack, I can reproduce.
occurs only if the wallet is freshly created.
