### ISSUE TITLE
[Android] Reproducable crash when entering Umlauts (ÄÜÖ) in Description

### ISSUE THREAD

**Issue by doublehelix24** [spesmilo/electrum#1717]
Android Client: 2.6.2

Steps to reproduce:
1) Go in the receive tab. Towards the bottom the address, amount, and description fields are shown.
2) Tap the description field
3) Enter any description containing any Umlaut (like the word "Übernahme")

Result: Electrum crashes

**Comment by ecdsa** [comment]
thanks, it is fixed.
will be in the next update

**Comment by doublehelix24** [comment]
Cheers

**Comment by ecdsa** [comment]
ok, the new APK is deployed: 2.6.2.2
