### ISSUE TITLE
android 2.6.2 client doesn't always update transactions

### ISSUE THREAD

**Issue by tfestate** [spesmilo/electrum#1718]
i noticed a couple of times that if i send a transaction and don't put the app down it sometimes doesn't update. If i then close it and relaunch it updates.

auto-connect is off. i also pinged the electrum server in the problem state and it was alive. waited for a long time...no update

thanks

**Comment by ecdsa** [comment]
did the phone go to sleep mode between the moment you sent the transaction and the moment you noticed it did not update?

**Comment by tfestate** [comment]
here's what happened, as well as i can remember

1)i sent a transaction. the history correctly showed a confirmation pending transaction

2)i went a way for a few hours with the wallet running; the phone was on my desk. Then i came back and i woke the phone up and saw the app as expected on the display and that there were still no confirmations according to history

3)i kept an eye on the wallet for quite a while, over 5 minutes. it still showed confirmation pending. so i closed the app and reopened and then it updated. 

of course, i don't know what really happened, but it seemed like after i woke the phone up the app didn't contact its SPV server...

**Comment by EagleTM** [comment]
Is this still an issue on 2.8.x mobile?

**Comment by tfestate** [comment]
No issue now. I doubt that Electrum software was the source of tbe behavior
I was seeing.

Regardless, current versions have been smooth for me.

Now if only you could do something about miners' fees.  ;)

Thanks.
