### ISSUE TITLE
Electrum. btc never arrive

### ISSUE THREAD

**Issue by greenedw** [spesmilo/electrum#1722]
Hi
I'm using electrum wallet 2.6.2 .
I'm waiting for 2 transactions that never arrive to my wallet. The adresse used for receiving them dont appear in the part "adresses used". Im gonna be crazy !

https://blockchain.info/fr/address/1AVdyqWpiXNy3jpQHWDFQZuhBuvodY2QgC

https://blockchain.info/address/1JJy1npBfxg14TS22YptB5WZb5q4qtgLxQ

I've tested to prove it, to send a small amount to myself who never arrive too

https://blockchain.info/fr/address/1EdRWJpme1bRtQzDCBB2xiMc

**Comment by ecdsa** [comment]
your client is probably not synchronized
