### ISSUE TITLE
install instructions need updating (see corrections)

### ISSUE THREAD

**Issue by bugelectrum124** [spesmilo/electrum#1724]
sudo apt-get install python-slowaes python-protobuf
sudo pip install dnspython jsonrpclib ecdsa qrcode pbkdf2

Also you need to run:
pyrcc4 icons.qrc -o gui/qt/icons_rc.py
(the current README says gui/icons_rc.py)

The message inside main.py saying 'pip install <module name>' is not helpful, and confusing.

**Comment by bugelectrum124** [comment]
remove the python setup.py install - it is not needed with the lines above, and not helpful.

And a good idea might be a build script, then the instructions would be much simpler.

**Comment by ecdsa** [comment]
this is actually making things more complicated; 
not everybody uses pip, nor apt-get
