### ISSUE TITLE
electrum broadcast: error: argument tx: invalid <lambda> value:

### ISSUE THREAD

**Issue by eharvest** [spesmilo/electrum#1726]
This problem occurs from version 2.6 & higher. No such error with 2.5.4. 

electrum payto `bitcoin-addr` 0.001 -w `wallet`
... returns  `tx`
electrum broadcast `tx`
..  electrum broadcast: error: argument tx: invalid lambda value ....

payto output `tx` looks different between 2.5.4 and 2.6. In addition 2.6 `tx` is 3 characters longer than 2.5.4 `tx.` 

[python 2.7.6]

**Comment by ecdsa** [comment]
it's fixed in git master; wait for ttodays release
