### ISSUE TITLE
gettransaction command in console doesn't work

### ISSUE THREAD

**Issue by rhz** [spesmilo/electrum#1727]
I have a raw transaction that I'd like to sign with the private key of an address in my wallet. I couldn't find out how to do it with the gui so I went to the console to try to do it there. I tried `tx = gettransaction("...")` and after pressing enter nothing happens. It doesn't even give an error. The cursor just stays where it is, as if I hadn't pressed enter. Is this a bug? How can I sign a raw transaction?

I'm using Electrum 2.6.2.

Thanks,
Ricardo

**Comment by ecdsa** [comment]
to sign a transaction, use 'signtransaction'
still, we should not freeze the GUI; I set the timeout to 30s to prvent that 753a28b452dca1023fbde548469c36a34555dc95

**Comment by rhz** [comment]
It's not that the gui freezes. I can still move the cursor. The problem is that it doesn't execute the command.
Regarding `signtransaction`, should I just do `signtransaction("...", privatekey)` where `...` is the raw transaction?

**Comment by ecdsa** [comment]
to sign a transaction with the GUI, just load it from the menu.
if you want to use commands, use them from a terminal, not from the python console.
documentation: "electrum --help"

**Comment by rhz** [comment]
When I say command, I'm talking about a Python function available at the console. That's what isn't working.
After I load the transaction from the menu, it doesn't let me sign it with the private key of an address because it says that the transaction isn't related to my wallet.

**Comment by ecdsa** [comment]
where does the raw tx come from?

**Comment by rhz** [comment]
I used the public key of that address to set up a multisig and the other party gave me that raw transaction to sign it.

**Comment by rhz** [comment]
any ideas how such raw transaction can be signed using electrum?
