### ISSUE TITLE
2.6.3 jsonrpclib.jsonrpc.ProtocolError

### ISSUE THREAD

**Issue by eharvest** [spesmilo/electrum#1728]
I get the above error when calling `electrum broadcast <tx>`. It worked until 2.5.4. `<tx>` is valid, since I can broadcast it with 2.5.4 and it gets confirmed.

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 371, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32700, u'Request {"jsonrpc": "2.0", "params": [{"verbose": false, "tx": {"raw": "010000000.........", "_inputs": null, "_outputs": null, "__jsonclass__": ["electrum.transaction.Transaction", []]}, "cmd": "broadcast", "timeout": 30, "password": null, "cwd": "/home/user/test", "portable": false}], "id": "42gbswnq", "method": "run_cmdline"} invalid. (__init__() takes exactly 2 arguments (1 given))')
```

[Ubuntu 14.04 LTS - 64 bit]

**Comment by ecdsa** [comment]
I can reproduce it. I will fix ASAP

**Comment by ecdsa** [comment]
the regression was introduced in 9659e8542d716dc1d87b4064906c444e4f18a95a

**Comment by eharvest** [comment]
Thanks a lot. broadcast works now and is accepted by mempools.

What format is the output of `electrum broadcast`? It changed since 2.5.4. In 2.5.4 it just returned the txid. Now it returns more. Is that valid json fromat?

Here is what I see:

```
[
    true, 
    "e5021......"
]

```

**Comment by ecdsa** [comment]
yes, the boolean shows the success/failure of the operation

**Comment by eharvest** [comment]
I see. Is it possible to use the same format as with e.g. `electrum pay_to`? Would be easier to process, since output is more uniform. Thanks. 

`electrum pay_to` json output:
```
{
    "complete": true, 
    "hex": "010000000...."
}
```

**Comment by html5-ninja** [comment]
I have the same problem how can I fix it ?

**Comment by ecdsa** [comment]
the problem is fixed in git master.
use it, or wait for next release

**Comment by html5-ninja** [comment]
Awesome thank you for the quick reply :+1:
