### ISSUE TITLE
Feature Request: Open Wallet in Wizard?

### ISSUE THREAD

**Issue by JPUnix** [spesmilo/electrum#1730]
As part of the wallet creation wizard. It would be nice if one of the options could be to open a pre-existing wallet that is located at a different directory location other than the default.

**Comment by JPUnix** [comment]
As part of the wallet creation wizard. It would be nice if one of the options could be to open a pre-existing wallet that is located at a different directory location other than the default.

**Comment by ecdsa** [comment]
no, that option should not be a new button in the wizard.
the main window should support wallet == None instead

**Comment by RealBTC** [comment]
I vouch for this feature as well. It's getting tiresome sometimes to always create a new wallet just to open an existing one.

So if the wallet is on a pendrive or external harddisk, or its moved to another place you alway have to create a new one to open it.

**Comment by gits7r** [comment]
better wallet == Import from file rather than wallet == none. This should be more explicit.

**Comment by RealBTC** [comment]
I agree with the OP and @gits7r , I made an illustration how it would look like

http://i.imgur.com/it6IYks.png

Pretty simple, just 1 more option needs to be added to the wizard.

**Comment by gits7r** [comment]
@RealBTC ACK I totally agree with that, just one more addition: If "Open wallet from file" is selected at <What do you want to do?> disable selection possibility (make everything grey) at <Wallet kind:> since Electrum will read that automatically if we choose to open wallet from file.

**Comment by RealBTC** [comment]
@gits7r  yes, that seems logical, since when we open a wallet, the electrum software should recognize what type it is.
