### ISSUE TITLE
Error when using JSONRPC interface

### ISSUE THREAD

**Issue by Satevg** [spesmilo/electrum#1731]
So I have in my config file following line:

`"rpcport": 7777,`

When I try to use from curl addrequest or getbalance commands, I always get errors like this:

`{"error": {"message": "Server error:   File \"/usr/local/lib/python2.7/dist-packages/electrum/commands.py\", line 568, in addrequest | AttributeError: 'NoneType' object has no attribute 'get_unused_address'", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}`

**Comment by ecdsa** [comment]
ack. I can reproduce that

**Comment by wadako111** [comment]
:+1:
