### ISSUE TITLE
Pay to Many "file icon" is actually a QR scan button and reverts out of Pay To Many mode.

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#1735]
As in title. QR code icon for "Pay to Many" trx should be a file icon and not open a QR scan window.

Also, when you choose that icon and quit the scan it then reverts to a regular send trx not a "Pay to Many" trx any more - while wiping out any details you have entered.

Ideally you could load a csv file and it would append onto any address-amount pairs already entered.

**Comment by ecdsa** [comment]
that does not make sense to me.
anyone understand what the OP means?

**Comment by neocogent** [comment]
When you choose "Pay to Many" from the menu it displays a message saying,

> Enter a list of outputs in the 'Pay to' field.
> One output per line.
> Format: address, amount.
> You may load a CSV file using the file icon.

But the file icon does not exist - there is only a QR code icon. And if you click that and don't scan a QR code (because you want to load a CSV file) then when it closes it reverts the "Pay to Many" enrty field back to a regular "Send To" (single address) field.

This part of the interface is very clumsy along with my other open issue about copy/paste from contacts to this "Pay to Many". And yet "Pay to Many" is something I use a lot to move funds from offline to several people/places at once, and is a genuinely useful feature.

**Comment by thephez** [comment]
What version of Electrum you using and what Operating System (Windows, OS X, etc.) do you have?  Normally (on Windows 7 with Electrum 2.6.3 in my case) there is both a QR icon and a folder icon.  The folder icon opens a file browser dialog for selecting a file.

**Comment by neocogent** [comment]
That's what I would have expected to see.

I'm on Linux Mint 17.03 (Ubuntu 14.04) using Electrum 2.6

**Comment by neocogent** [comment]
I'd also note it wasn't clear to me that "Pay to Many" is the same entry field as "single pay" because it expanded and had several lines. I thought this was an altered / different entry field. But it seems that it's just expanding to let you know that normally you can also use more than one line. SO "Pay to Many" is just a prompt to let you know you can enter more than one but it doesn't really make that clear. If I had known I can always enter multiple lines then I'd never bother using the "Pay To Many" menu item. So... just odd.

**Comment by neocogent** [comment]
More info - it seems that this is a case of the icon being present but not visible. I noticed the QR icon was oddly positioned and tried clicking on the blank area next to it. That did prompt for a file. So if you're looking to fix this then know the button is there but icon not visible.

**Comment by ecdsa** [comment]
how did you install Electrum?

**Comment by neocogent** [comment]
This is on my dev system so I'm 99% sure it's pulled from git and then built using the procedure in the readme. So maybe some missing icon resource or linkage? It would have been a while back I last built.

**Comment by ecdsa** [comment]
ok, so that's because you did not rebuild the icons.
see the README

**Comment by neocogent** [comment]
I did manage to rebuild Electrum to include the icon. But that is not what the REDAME instructs users to do to run Electrum. You have to build the package in the instructions for "How official packages are built", rather than what instructions say to run Electrum. That is the reason the icon was not included when I cloned the repo and then followed the readme. Maybe this should be made more clear that users need to build the package before they install it.

**Comment by ecdsa** [comment]
you are referring to an old version of the README
the current one does not have the section you are referring to
