### ISSUE TITLE
Self Hosted Electrum Server - SSL Mode/Cert

### ISSUE THREAD

**Issue by webdawg** [spesmilo/electrum#1744]
When trying to connect to a single specified server over SSL I get no connection:

This is the output if I run from command line.

> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/site-packages/electrum/interface.py", line 207, in run
>     socket = self.get_socket()
>   File "/usr/lib/python2.7/site-packages/electrum/interface.py", line 130, in get_socket
>     if s and self.check_host_name(s.getpeercert(), self.host):
>   File "/usr/lib/python2.7/site-packages/electrum/interface.py", line 91, in check_host_name
>     for attr, val in peercert["subject"]:
> ValueError: need more than 1 value to unpack

As soon as I switch it from SSL to no SSL, everything works.  I actually have a valid SSL cert installed on the server.  Self generated but the SSL is signed by an installed CA on the client.  Last thing I read though electrum only verified the date?

**Comment by ecdsa** [comment]
what did you do exactly?

**Comment by webdawg** [comment]
I have electrum-server installed on a host.  That server is configured to allow connections but not advertise.

I use internal host names on my internal network.  So the name of the electrum-server host is:
exa-mpleeee.localdomain

The host is resolvable by the system.

electrum-server is configured for ssl and normal connections on 50001 and 50002 respectively.  I have both a private key and crt configured for use in the conf file for the server.

I get that error when I put in exa-mple.localdomain and 50002 into the input boxes @ the server configuration in the electrum client.  Actually I just uncheck the automatic button, SSL stays checked and I change the server name.  I could try and manually enter the port but the port on the dialog box stays @ 50002 which is correct.

**Comment by ecdsa** [comment]
can you publish the hostname and port number, so I can give it a try?

**Comment by webdawg** [comment]
I will work something up for you.

**Comment by ecdsa** [comment]
so?

**Comment by EagleTM** [comment]
It only checks the date for self-signed certs. If the cert is liked to something in client's CA store it'll actually try to verfiy it X.509 style (like BIP70)

**Comment by webdawg** [comment]
You guys got the email then with the info?  I will double check all the certs and everything then.

**Comment by ecdsa** [comment]
I got it, thanks

**Comment by webdawg** [comment]
Where you able to connect to the server, it was offline.

**Comment by webdawg** [comment]
I ended up turning it off.

Right after I gave it to you the server crashed.  Did you do anything to it?

The server would not start, would always crash.

I did a git upgrade and it seems to be working.

Did you see the divide by zero error I posted?

**Comment by EagleTM** [comment]
I'll close for now
