### ISSUE TITLE
Python traceback occurs instead of an error message

### ISSUE THREAD

**Issue by fortran77** [spesmilo/electrum#1746]
Suppose ~/.electrum/wallet is a dangling symlink. This might occur, for example, if electrum wallets are kept in a directory normally mounted on an encrypted filesystem. So we make ~/.electrum/wallet a symlink to such a directory. If that encrypted filesystem is not mounted, we have a dangling symlink.

When electrum encounters this dangling symlink, it goes into a Python traceback ending in something like:

```
OSError: [Errno 17] File exists: '/Users/myusername/.electrum/wallets'
```

On OS X 10.10, the GUI aborts without reporting any specific error. The debugging console can then be accessed to see the Python traceback.

On Ubuntu 12.04, the GUI when  invoked from desktop menus simply never starts running. If I invoke electrum from the command line, the Python traceback can be seen.

It would be better to print an explicit error message, instead of triggering a traceback. The error message might say something like "cannot make directory xxx because: 'File exists'".

[ edited to fix typos. ]

**Comment by ecdsa** [comment]
could you post the entire traceback please?

**Comment by fortran77** [comment]
Here is the traceback from Ubuntu 12.04.

    Traceback (most recent call last):
      File "/usr/local/bin/electrum", line 329, in <module>
        d.init_gui(config, plugins)
      File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 235, in init_gui
        self.gui.main()
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 190, in main
        if not self.start_new_window(self.config.get_wallet_path(),
      File "/usr/local/lib/python2.7/dist-packages/electrum/simple_config.py", line 153, in get_wallet_path
        os.mkdir(dirpath)
    OSError: [Errno 17] File exists: '/home/myusername/.electrum/wallets'

**Comment by bauerj** [comment]
I think not catching this specific exception is fine. Once #2339 is merged, users will see the traceback in an error window if they use the Qt GUI.
