### ISSUE TITLE
How to uninstall it?

### ISSUE THREAD

**Issue by FAlbanni** [spesmilo/electrum#1747]
I want to PURGE uninstall completely this software but I can't please help me

I am using Ubuntu 15.04
I did
sudo pip install https://download.electrum.org/2.6.3/Electrum-2.6.3.tar.gz

but if I do
apt-cache search electrum
texlive-fonts-extra - TeX Live: Additional fonts

nothing there

I cannot remove it using
apt-get remove
since it doesn't exist! Please help me I need it deleted ASAP

**Comment by FAlbanni** [comment]
In desperation I did

python setup.py install --record files.txt

with prompted this
http://pastebin.com/XUdzF51V

if safe if I remove everything manually? also I shouldn't touch...
/usr/local/bin/qr
/usr/local/bin/easy_install
right?

I know this software is free and done with lot of effort, but is the worst thing I ever installed/used, it crashed on two different ubuntus machines, it stays "synchronizing" forever, when I close the window the process keeps running, it made my CPU went to 100% for like an hour, in one machine when I installed it crashed the /usr/local folder restricting permissions or something making ubuntu software center stop working I had to do "sudo chown -R `whoami` /usr/local" to recover and now it seems it cannot be uninstalled! What a nightmare!

**Comment by ecdsa** [comment]
if you install with pip, you should uninstall with pip: 'pip uninstall'

**Comment by FAlbanni** [comment]
already tried that and it didn't work, I think I deleted everything anyway manually, electrum never worked for me in neither of my machines, I loved the pregen keys and everything such a shame :(

**Comment by ecdsa** [comment]
closing, no usable info here.
if you want to see bugs fixed, the least you an do is describe them properly.
