### ISSUE TITLE
Android: Crashes after entering seed for existing wallet

### ISSUE THREAD

**Issue by mondjunge** [spesmilo/electrum#1749]
I am running current electrum from PlayStore on CM13 (Android 6.0.1) with only the Nano Package of OpenGapps installed. LG Nexus 4 (mako)

Like with older Versions you had to compile for yourself, it works when generating a new wallet, but after entering a valid seed for my existing wallet, Electrum shows its Logo for like 5 Minutes and then crashes without any message. When trying to restart, it will crash after a few minutes showing nothing but the electrum logo.

I am willing to provide any additional information, debug logs or anything if you just tell me how to gain this information.

**Comment by ecdsa** [comment]
it would be great to see a Python traceback.
were you running older versions on a desktop machine?

**Comment by ecdsa** [comment]
on android, you can get a debug log using adb
in a terminal, type "adb logcat |grep python"

**Comment by mondjunge** [comment]
I am also running Electrum Version 2.5.4 on two different ubuntu desktops (14.04, 15.04). I normally update as soon as there is an update notification. I use Electrum for about 6 month now (or so, can't tell exactly).

I reinstalled Electrum, started it, activated adb logcat and then I entered my seed. Afterwards I had some time to see "Synchronizing" in the top bar and switch the view a few times until it died:
[electrumCrashAfterSeedLog.txt](https://github.com/spesmilo/electrum/files/204669/electrumCrashAfterSeedLog.txt)

Here is the tracelog of Electrum starting and crashing with my wallet restored from seed. This is from before I reinstalled, but the error is still occuring the exact same way after reinstall:
[electrumStartupCrashLog.txt](https://github.com/spesmilo/electrum/files/204648/electrumStartupCrashLog.txt)

For me it looks like "ValueError: None is not allowed for HistoryItem.value" is somehow related to the crash.

Hope this helps to fix the Problem. 
Thx for your great work so far, I appreciate Electrum very much.

**Comment by ecdsa** [comment]
thank you very much for the logs!

**Comment by ecdsa** [comment]
this should fix it. 
I will update the app on play store

**Comment by mondjunge** [comment]
Thank you very much! You are awesome.

I will try again and report bugs as I encounter them.

**Comment by ecdsa** [comment]
I uploaded the new APK (2.6.3.2)
let me know it it works

**Comment by mondjunge** [comment]
I just installed the updated apk from website to check your fix. And everything is working fine now.

Great work! Thx a lot!
