### ISSUE TITLE
[SUGGESTION] Transaction History/Historical Prices

### ISSUE THREAD

**Issue by RustyNomad** [spesmilo/electrum#1752]
When exporting the transaction history the details of the transaction is exported WITHOUT the historical fiat prices. I understand that the historical fiat prices are provided by the plugin and that they are essentially not part of the transaction but it would be a very nice feature if this could be included in the export.

**Comment by ecdsa** [comment]
I agree. this is needed for accounting.

**Comment by ecdsa** [comment]
note: this plugin is going to be merged with the main code

**Comment by ecdsa** [comment]
note: the plugin is merged now.
