### ISSUE TITLE
[Android] Fee slider leaks privacy by using 4 random-looking digits

### ISSUE THREAD

**Issue by fortran77** [spesmilo/electrum#1753]
In version 2.6.3 for Android, the fee slider reached from Settings => Fees usually ends up at some position with 4 random-looking digits after the decimal point. Now the fee will always be a multiple of this arbitrary number, and multiple payments from the same wallet might be identifiable as such.

A possible fix would be to replace the continuous slider with one that has discrete stops at round numbers, for example, 0.1, 0.2, 0.3, ... (or, for dynamic fees, at discrete percentage values such as 100, 90, 80, 70, ...).

Or, keeping the current slider, slightly randomize the fee for each transaction.

Or both.

**Comment by ecdsa** [comment]
good point

**Comment by EagleTM** [comment]
Does this apply to Android only or to the desktop version too?

The fee slider value in the desktop version is actually populated by bitcoin core's estimatefee - so it should vary over time. estimatefee is also used by core itself and other electrum users within the block generation timeframe so there should always be number of tx using it.

**Comment by ecdsa** [comment]
it applies to both.
the issue is that we use continuous values

**Comment by ecdsa** [comment]
done for Qt: 3314b3acc70f3878a2a93a1832029fd184e68d80
I still have to do it for Kivy
