### ISSUE TITLE
Change the green circle to blue when we are connected to proxy

### ISSUE THREAD

**Issue by barmitzvah21** [spesmilo/electrum#1754]
The green circle on the bottom-right section of the window should be a blue circle when we are connected to a proxy like Tor.

And when it's a clearnet connection, then it will be green. When offline , then red.

The separation between blue and green colors is necessary, so that people who work in privacy should not make a mistake and connect over clearnet to a privacy wallet. And when they work with a normal wallet they will use the clearnet and have the green circle.

This will help minimize the mistakes people can make, and make privacy more visual. It can help many privacy enthusiasts.

**Comment by Johnbitcoiner** [comment]
I would support this. I am always worried to not connect to a wrong wallet when i`m working in a proxy, this would be a great visual helper for privacy users.

The color of the dot can be: **#0094FF**

It's a pretty fitting blue color, not too dark, not too bright.
