### ISSUE TITLE
No way to cancel the multi-sig wallet generation wizard on fresh install

### ISSUE THREAD

**Issue by IntegersOfK** [spesmilo/electrum#1755]
Naturally, when you have a fresh installation of Electrum (or if there are no wallet files because you've deleted them), you must create a new wallet before you're able to use the software. However, if you choose to generate a multi-sig wallet the first time you've run through the wizard but wish to cancel this process at the "Please enter the master public key of cosigner" screen, the cancel button will simply close the application. The next time you open Electrum you're stuck at the same screen as the wizard resumes with the prompt to give it x public keys of cosigners. There are two ways for users to exit the wizard, one is to give it public keys and continue through the steps, which is inconvenient for users who may have had the impression that the wizard will _also_ generate the cosigner wallets in the process. The other way is to delete the default_wallet file from where it's saved on the computer, so the next time you open Electrum you can choose a "standard" wallet as you probably intended.

I recommend prompting the user when they try to exit the wizard from the cosigners input screen, asking them if they would like to "continue inputting cosigners later" or "discard and delete the entire wallet".

**Comment by ecdsa** [comment]
there are two moments where we can propose to delete the wallet: 
when the user exit the wizard, or when they open an unfinished wallet.

**Comment by ecdsa** [comment]
it looks like this was removed in 11d135b32d7c59782dbbd3327f65adfda1fdf1dd
@kyuupichan can you explain why you removed the dialog offering to remove an incompletely created wallet?

**Comment by kyuupichan** [comment]
If you recall I completely removed the incompete wallet saving thing as I thought it was a misfeature. You then put it back but apparently not all of it.

**Comment by ecdsa** [comment]
you mean that I did not completely fix the regression you introduced?
it would have been nice to let me know about it; I guess you knew about what code you removed, no?

**Comment by WilliamJamesDalrympleWest** [comment]
Unbelievable this was over a year ago, still stuck
