### ISSUE TITLE
electrum addrequest "status" not working as it could (v2.6.3)

### ISSUE THREAD

**Issue by RealBugReporter** [spesmilo/electrum#1757]
Hi again, ^^

`root@post2:~# sudo electrum listrequests`
Now it gives 4 "status" variables:
1. "Expired"
2. "Unkown"
3. "Pending"
4. "Paid"

But bitcoin supports more than 1 confirmations... So my suggestion is to extend this and implement how many confirmations there is so it would look like this:
1. "Expired"
2. "Unkown"
3. "Pending"
4. "Paid1" (Means it is low trust confirmation takes up to 10-15mins)
5. "Paid2" (Better than low  up to 10-25mins)
6. "Paid3" (Normal trust confirmation up to 20-30mins)
7. "Paid4" (Better than normal 20-40mins)
8. "Paid5" (Trustable confirmation 30-50mins)
9. "Paid6" (Best confirmation 30-60mins)

Another thing which I found is that it generates "b33af19a50" and "b33af19a50.json" files only 1 time on the run of "`sudo electrum addrequest 0.425 --expiration 1300 --force`" command. So if I am checking in my website "b33af19a50.json" file for payment verification the "status" variable seems to be frozen.

I recently found out your project and it seems really great! Hope one day I will investigate enough to get on contributing. Thanks. :)

**Comment by ecdsa** [comment]
instead of adding new status values, it should probably include the transaction id in the result

**Comment by ecdsa** [comment]
it has a 'confirmations' field now, if the amount is confirmed.

**Comment by klerms** [comment]
Great, could you also include the received amount? Sometimes is useful to notify the customer immediately after the broadcast that he sent less then required amount or more then required amount.
