### ISSUE TITLE
Electrum UI Upgrade?

### ISSUE THREAD

**Issue by losh11** [spesmilo/electrum#1760]
Is anyone here interested in an upgrade to the Electrum UI? 
I will work on it (along with some others), and here's a bunch of early mockups.

**Desktop**

![img1](http://i.imgur.com/4xtNFaE.jpg)
![img2](http://i.imgur.com/LP9Xq0t.jpg)

**Android**

![img3](http://i.imgur.com/j0Wo98m.jpg)

_Please keep in mind that this is the LTC version, but there are some changes made for the BTC mockups. Is there is any interest for this?_

**Comment by RustyNomad** [comment]
This would be nice. I love Electrum but it does look a bit dated in its current form.

**Comment by ecdsa** [comment]
I understand this is a mockup, not a working prototype. I do not have time for that at the moment, and I doubt it can be done in a way that does not require significant developer involvement.

**Comment by nipund** [comment]
How about a web UI (like SABnzbd/Sickbeard)? We can easily make it look like that and I'd be happy to work on it if enough people want it.

**Comment by ecdsa** [comment]
feel free to start such a project, but do not expect me to spend time on it
