### ISSUE TITLE
Android Electrum Server Selection

### ISSUE THREAD

**Issue by felmey** [spesmilo/electrum#1761]
There doesn't seem to be any way to enter a custom server into the Android Electrum app.  Also, if you enable this feature, would you be able to make it compatible with *.onion addresses?

**Comment by abitfan** [comment]
You can set a custom server under Settings/Network

**Comment by felmey** [comment]
abitfan, you can select from a drop down list of servers that come with the app.  But I can't see anyway to enter in my own custom server name.

**Comment by d01mf** [comment]
I can confirm. As I uncheck auto-connect, I'm only able to select a server from the drop down list and not enter any custom non-listed server.

**Comment by gits7r** [comment]
Seams like a needed feature. Ability to manually enter hostname, port and protocol (TCP/SSL).

**Comment by ecdsa** [comment]
added in 38d6c18b60989d59eb40db784121635251faff65
