### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hanaix** [spesmilo/electrum#1765]
I can not send a payment ...? Looking for advice? OS Win.7, 64bit. electrum ver. 2.62
when I start writing this buzz?
[ (http://www.imgbank.cz/images/2016/04/16/catsoKTjw.jpg)]

Thank you

**Comment by RustyNomad** [comment]
The wallet you are trying to send from is a 'watch-only' wallet meaning there are no private keys present so no way to send funds i.e. sign transactions.

If you have funds you want to send from that wallet then you will need to restore the wallet on Electrum and enter the seed of the wallet when restoring it. This will create a normal wallet, including all the private keys which will enable you to send funds from it.

**Comment by hanaix** [comment]
super weri thanks you!!
