### ISSUE TITLE
Restore 12-word seed, trailing space

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#1769]
A friend downgraded to v.1.9.x because he thought the newer versions didn't support restoring from the older 12 word seed ("next" box grayed out with him thinking it's waiting for the 13th word).

It turns out he had a trailing space: "It seems to have been an issue with a trailing space. Very frustrating that it grays out the the box rather than telling you that the the code is not accepted. I assumed the problem was that it was waiting for a 13th word."

Stripping out extra spaces like trailing spaces (from copy / paste i imagine) might help others too who are having problems with restoring from seed or complaining that their balances don't show after a restore

**Comment by ecdsa** [comment]
extra spaces are already stripped out.
the next button was probably gray because of a typo in the words your friend entered.
