### ISSUE TITLE
bitcoin.py in OSX 2.6.4 missing MIN_RELAY_TX_FEE

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#1770]
Where did it go? Can I put it back? 

https://github.com/spesmilo/electrum/issues/969#issuecomment-68506626

**Comment by ecdsa** [comment]
it requests it from the server

**Comment by dabura667** [comment]
@TheButterZone In early 2015, people could get away with hard-coding the min-relay amount and not worry about anything. Heck, if you wanted to mess around with the source and send a 0 fee transaction, that was ok back then.

Not anymore.

I have edited my comment that you linked to remove the contents as it is no longer relevant.

**Comment by ecdsa** [comment]
The relay fee depends on the server. if the client does not add it, the server does not broadcast the tx.

**Comment by TheButterZone** [comment]
What's the console query command to ask the connected Electrum server what it is?

**Comment by ecdsa** [comment]
there is no query command for that
