### ISSUE TITLE
Incoming transaction not showing up

### ISSUE THREAD

**Issue by fromheten** [spesmilo/electrum#1774]
## What i did
I made a [a bitcoin transaction](https://blockchain.info/tx/6d265ee112592132af41439181ce53f5114d99d144fb390f666f5e59e8f59dbd) to an address I have. I have made other transactions to that address, sucessfully. I made the transaction myself with the bitcoin-js library. 
## Expected behaviour
Usually TXs show up in Electrum pretty much instantly, but this one doesnt show up. Not even as "unconfirmed". It is in the blockchain.info webapp though, so I assume the error lies in Electrum. 

## What I've tried so far
* `wallet.clear_history()` in console
* Restarting Electrum
* Updating to the latest version. Currently 2.6.4, was 2.6

I don't know the Electrum source code, but I hope this can be helpful in making it even better :). Thanks everyone who contributed to this great program, I'm a very happy user for a long time! Please let me know if I can provide more information.

**Comment by ecdsa** [comment]
probably a server error.
