### ISSUE TITLE
App closes when "Create a new seed" is selected

### ISSUE THREAD

**Issue by derwinmcgeary** [spesmilo/electrum#1775]
Fresh install on Android LG-D724, Android version 5.0.2, Software version V20b-CIS-XX

Steps to reproduce: Install app, tap icon on screen to launch, select "Create a new seed" and the app disappears and we're back to the screen we launched it from.

**Comment by ecdsa** [comment]
I just saw that too. 
fixing it now..

**Comment by ecdsa** [comment]
ok, it is fixed. upgrade to version 2.6.4.1 of the app
