### ISSUE TITLE
Electrum stop working on my Arch Linux

### ISSUE THREAD

**Issue by Jzarecta** [spesmilo/electrum#1779]
I am having an issue on Arch Linux using python 2.7.11 after some update (I pressume) I get the following message:
`Error: cannot import name DependencyWarning. Try 'sudo pip install <module-name>'
`

**Comment by magicvodi** [comment]
I just installed Electrum on Arch on my PC and got the same error.
On my Laptop with Arch everything works as expected. Can I help investigating somehow?

**Comment by Jzarecta** [comment]
I solved it, it seems the issue was from a module that came from pip instead from the repo. Cant remember which module. Uninstall the module from pip and re-install it from pacman.

**Comment by cstewart90** [comment]
The problem module for me was pillow.

**Comment by ecdsa** [comment]
closing, the issue is not with electrum.
