### ISSUE TITLE
OSX retina support

### ISSUE THREAD

**Issue by wozz** [spesmilo/electrum#178]
OSX retina support is not working.  I'm not sure if that just means uploading some higher resolution images/icons or if there is more to it than that.

**Comment by gtklocker** [comment]
Some icons are still not hidpi here on an rMBP running 10.10.2.

![screen shot 2015-03-18 at 12 35 12 copy](https://cloud.githubusercontent.com/assets/732062/6707063/f4f2b3cc-cd6b-11e4-8739-979f888dd2f8.png)

Specifically, the tick icon on the left of each transaction, as well as the icons on the bottom right row are evidently not hidpi.

Thanks for making Electrum! :smile:
