### ISSUE TITLE
dns dependency name is incorrect?

### ISSUE THREAD

**Issue by dooglus** [spesmilo/electrum#1780]
I saw in README.rst:

> To run Electrum from its root directory, just do::

>     ./electrum

When I tried that, I got:

    $ python electrum
    Error: No module named dns. Try 'sudo pip install <module-name>'

I tried as it suggested but it failed:

    $ sudo pip install dns
    Downloading/unpacking dns
      Could not find any downloads that satisfy the requirement dns
    Cleaning up...
    No distributions at all found for dns
    Storing debug log for failure in /root/.pip/pip.log

It turned out I had to use 'dnspython' as the module name:

    $ sudo pip install dnspython
    Downloading/unpacking dnspython
      Downloading dnspython-1.12.0.zip (230kB): 230kB downloaded
      Running setup.py (path:/tmp/pip-build-NW3FMK/dnspython/setup.py) egg_info for package dnspython
        
    Installing collected packages: dnspython
      Running setup.py install for dnspython
        
      Could not find .egg-info directory in install record for dnspython
    Successfully installed dnspython
    Cleaning up...

I had to read the source to find the correct module name. The name reported by the error message (`dns`) was no use to me.

**Comment by popey** [comment]
On my Ubuntu 16.04 system I had to do the following:-

sudo apt install python-dnspython python-slowaes python-ecdsa python-qrcode python-pbkdf2 python-protobuf python-jsonrpclib pyqt4-dev-tools
pyrcc4 icons.qrc -o gui/qt/icons_rc.py
Then electrum runs without using any "pip install" stuff. :)

**Comment by ecdsa** [comment]
I am not sure what the README used to say when you filed this issue, but the current version is clear: you can run Electrum from its root directory if you downloaded the tar.gz, because it contains all the dependencies. This, you should never have to do that.

You need to install python dependencies only if you cloned the repo with git.

**Comment by DarkPark** [comment]
wrong instruction
doesn't work

**Comment by glendon144** [comment]
On Ubuntu 14.4, the above fix does not work.  The error persists and electrum will not run.
