### ISSUE TITLE
Bitcoin Electrum py2exe

### ISSUE THREAD

**Issue by EdwardS86** [spesmilo/electrum#1781]
dear all,

I'm trying to convert source code into .exe (using py2exe) I do not know
why it is not working.

Use:
- Sources Electrum-2.6.4.zip
- python-2.7.11.msi
- py2exe-0.6.9.win32-py2.7.exe
- OS: Windows 7

ERROR: http://s32.postimg.org/6qg7pi6dx/cmd.png

Could you give me an advice please ?

PS: Thank you very much for the development of bitcoin electrum
(electrum=best)

**Comment by ecdsa** [comment]
see the script in contrib/build_wine
