### ISSUE TITLE
2FA seeds not working with mobile

### ISSUE THREAD

**Issue by John953** [spesmilo/electrum#1787]
I have been using the pc wallet seamlessly. I downloaded the mobile version and cannot get it to accept the seed. I know i have entered it right because ive looked over it multiple times and have been trying for over two weeks to install with seed. I use the seed to reinstall on pc fine but when it comes to the mobile app i cannot click next. It is not highlighted. Any help would be great thanks

**Comment by ecdsa** [comment]
was the seed generated with Electrum?
is is a special kind of wallet, eg with two-factor authentication?

**Comment by John953** [comment]
The seed was generated with electrum. It may have two factor authentication not sure how I intially set it up. When I reinstall on PC is works fine. Dont need a password out anything extra

**Comment by ecdsa** [comment]
how many words in the seed? is it English?

**Comment by John953** [comment]
There are 25 words and yes it is English

**Comment by ecdsa** [comment]
25 words mean that it is a two-factor authentication wallet, cosigned with Trustedcoin.
you cannot use such a wallet on the mobile app.
create a standard wallet first.

**Comment by ecdsa** [comment]
2FA seeds are detected now, and an error is displayed: 827d928aaa5ae30c028a021dfd6b71870eda9df5
