### ISSUE TITLE
Empty passphrase should be allowed

### ISSUE THREAD

**Issue by slush0** [spesmilo/electrum#1788]
Hi @ecdsa,

following line (the same in new_password and old_password) is blocking users to have passphrase protection enabled in the device, but actually use empty passphrase:
https://github.com/spesmilo/electrum/blob/master/gui/qt/password_dialog.py#L149

The most straightforward way is to remove "or None" check. May I change it (directly if you allow or via PR) to something like `return unicode(self.pw.text())` ? It's outside Trezor plugin and I don't want to break anything else... Currently "OK" on empty fields behave like pressing "Cancel".

**Comment by ecdsa** [comment]
that would break things. None means no password.

**Comment by ecdsa** [comment]
maybe we should use a different dialog for that.

**Comment by kyuupichan** [comment]
I don't understand - I use an empty passphrase without an issue on a passphrase-enabled device

**Comment by ecdsa** [comment]
I don't undestand the issue either

**Comment by slush0** [comment]
Try it yourself: Create new wallet -> harware wallet -> Use already setup device -> TREZOR -> Don't fill passphrase and press Enter -> Application crashes / exits because it things I cancelled the dialog. (Empty passphrase + OK) != Cancel

I don't know what else my proposal breaks, but it fixes this issue.

**Comment by kyuupichan** [comment]
OK, thanks, I'll fix this.

**Comment by slush0** [comment]
Thanks a lot!
