### ISSUE TITLE
Electrum fails to start on a clean Ubuntu 16.04

### ISSUE THREAD

**Issue by afk11** [spesmilo/electrum#1789]
Today I did a fresh install of Ubuntu 16.04. I installed using ` sudo apt-get install python-qt4 python-pip &&  sudo pip install https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz `, which seemed to go fine. 

Starting electrum gives me this error: 

> Traceback (most recent call last):
>   File "/usr/local/bin/electrum", line 75, in <module>
>     check_imports()
>   File "/usr/local/bin/electrum", line 55, in check_imports
>     import google.protobuf
>   File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/google/__init__.py", line 2, in <module>
>     __import__('pkg_resources').declare_namespace(__name__)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
>     @_call_aside
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
>     add_activation_listener(lambda dist: dist.activate())
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
>     callback(dist)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
>     add_activation_listener(lambda dist: dist.activate())
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2513, in activate
>     for pkg in self._get_metadata('namespace_packages.txt'):
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2503, in _get_metadata
>     for line in self.get_metadata_lines(name):
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1477, in get_metadata_lines
>     return yield_lines(self.get_metadata(name))
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in get_metadata
>     return self._get(self._fn(self.egg_info, name))
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1580, in _get
>     with open(path, 'rb') as stream:
> IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/EGG-INFO/namespace_packages.txt'
>

**Comment by afk11** [comment]
Reviewed the file named at the very bottom: /usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/EGG-INFO/namespace_packages.txt

> 4.0K -rw-r----- 1 root staff 7 May  6 12:23 /usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/EGG-INFO/namespace_packages.txt

Running this command seemed to fixes it, but I can imagine new users might be frustrated. 

> sudo chmod 755 /usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b2.post2-py2.7.egg/EGG-INFO/namespace_packages.txt

**Comment by dvomaks** [comment]
sudo electrum

**Comment by afk11** [comment]
@dvomaks sudo isn't for asking nicely, it's giving software all privileges over the system.. not a solution.

**Comment by ecdsa** [comment]
@afk11 I believe the issue is not with Elctrum, but with the way protobuf was installed.
