### ISSUE TITLE
Electrum 2.6.4 gets stuck on generating addresses

### ISSUE THREAD

**Issue by ffxsam** [spesmilo/electrum#1792]
I'm on Mac OS 10.11.4. When I try to create a standard wallet with a passphrase, I progress to the page that says "Electrum is generating your addresses, please wait..." and it seems to stay there indefinitely. I'm on a high end Mac Pro, so CPU cycles shouldn't be an issue here.

**Comment by ecdsa** [comment]
is this reproducible?

**Comment by ffxsam** [comment]
Actually, no. I just tried again and it worked as expected. Must've been a fluke, but I'll reopen this if I run into it again and can reproduce it.

**Comment by gtklocker** [comment]
Just came across this on 2.6.4 as well.

<img width="642" alt="screen shot 2016-08-29 at 23 34 44" src="https://cloud.githubusercontent.com/assets/732062/18066480/467495fe-6e41-11e6-92c7-fd86246f9815.png">

Weird thing is that the addresses are actually generated.

<img width="952" alt="screen shot 2016-08-29 at 23 35 06" src="https://cloud.githubusercontent.com/assets/732062/18066487/4cd96c8a-6e41-11e6-8e41-dfd3125151ca.png">

**Comment by TonyDobbs** [comment]
Had the same issue. Closed and reopened the app and the addresses appeared to have been generated correctly.

**Comment by meeDamian** [comment]
Same here @ MacOS 10.12.2 Beta (16C63a) && Electum v2.7.12

<img width="712" alt="macos 2016-12-12 at 15 16 20" src="https://cloud.githubusercontent.com/assets/526657/21094650/f9cc8e3e-c07d-11e6-8a59-6c858a244efc.png">

**Comment by Weuxel** [comment]
Same...

**Comment by ecdsa** [comment]
please show the console message

**Comment by Weuxel** [comment]
Can´t. The installation got stuck two times and i did not want to use it as i did not know wether it was broken or not. So i deleted all files and ran the installation again. This time all went smoothly. But the logs of the other installation are obviously gone.
