### ISSUE TITLE
Bitcoins lost when sent to the same address as less than 24hrs before(closed)

### ISSUE THREAD

**Issue by insaneoperative** [spesmilo/electrum#1794]
Well, I sent 2k worth of bitcoins to the same address I used yesterday for 2k as well and now I am here with no coins :(. I believe electrum owns this wallet and can help me with getting my coins back. Here is my proof that these are in fact my coins.
My current electrum balance(Notice 2k transaction yesterday): http://prntscr.com/b3snsl
Wallet IDs from my 2k transaction yesterday: http://prntscr.com/b3so06 (notice 12ozu...)
2k Transaction that occured today: http://prntscr.com/b3sooz (notice receiving 120zu.. same address)
Screen shots of it being sent from the wallet i carry on my phone(have not set up electrum on mobile device, i messed up i know): http://prntscr.com/b3spdz 

I hope you guys can help me some how, 2k is a hefty loss to someone like me.

**Comment by kyuupichan** [comment]
It seems your device thinks it sent twice.  But I don't see the 2nd send from your address on blockchain.info, so your coins are still there.  If you have your seed you are fine.

Perhaps the network server you are connected to hasn't broadcast the tx.  Try connecting to a different server.

**Comment by insaneoperative** [comment]
the weird thing is that the address it was sent to yesterday isnt in my recent address list 
@kyuupichan

**Comment by ecdsa** [comment]
electrum does not "own" your wallet.
I do not realy understand your report. was a transaction initiated by someone else than you?

**Comment by ecdsa** [comment]
can you please post the bitcoin address from the screenshot?

**Comment by insaneoperative** [comment]
which screen shot and i sent it to the same address that bitcoin wallet said was the one i has sent it to the day before as you can see on the screen shot of my phone. I have no access to that address, it doesnt show up in my electrum or anything but somehow the day before i sent 2k through it. @ecdsa please specify which screenshot/address?

**Comment by ecdsa** [comment]
the address you keep talking about..

**Comment by insaneoperative** [comment]
@ecdsa after 3 days it appeared in my electrum wallet. pretty weird because other transactions went through but im happy lol 2k was not lost

**Comment by ecdsa** [comment]
your wallet was probably not synchronized
