### ISSUE TITLE
Incorrect decimal format when switching Base Unit from mBTC -> BTC

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#1796]
When I switch the Base Unit from mBTC -> BTC , and if the decimals are already set to 8  , and if the wallet is a new wallet, then the Balance shows like this:

**0. BTC**

instead of

**0.00000000 BTC**

Then I have to close electrum and reopen it again to show the 0.00000000 BTC format for the 8 decimal setting. This is a bug because probably the electrum doesnt update the configuration only after its reopened and it still show the mBTC format I guess

**Comment by gits7r** [comment]
Yes. And for the Android version (play store) after switching from mBTC to BTC in Settings it will remain with balance: 0. BTC no matter how many times you close it and reopen.

**Comment by RealBTC** [comment]
Tested it on v 2.7.12, it looks like the issue is fixed.

However, the decimals of the Balance can no longer be set, only in the address tab you can configure them. Well it's acceptable, atleast the bug is gone.
