### ISSUE TITLE
AVG detects Electrum wallet to be a threat due to its behavior.

### ISSUE THREAD

**Issue by uniibu** [spesmilo/electrum#1797]
I've been using Electrum on my desktop for as long as i can remember. And just this past few days, AVG anti-virus, kept saying that electrum.exe is a threat due to its behavioral pattern it even suggest that you 'secure' it or it means delete it, and if you are not paying attention to it, you might just click the button secure, and itll delete your electrum.exe. I know its not a critical issue since it only deletes the exe file, and not the wallet files. I can always redownload it. Or have it whitelisted.

 I know that i have a clean pc, and this probably just a false detection. So just letting you guys know.
Below is the screenshot of the detection..
[https://i.gyazo.com/bb0001c6c588ef3abac7191f3e995624.png](url)

**Comment by ecdsa** [comment]
I don't think there's anything we can do about that. complain to them :)
