### ISSUE TITLE
add icon to transaction list signaling relevant info such as lower fee than recommended

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#1798]
Just today I had a problem in receiving a payment - it was sent to me with a lower than recommended fee (but not 0, so it made it into the majority of node's mempools) and it took one day to confirm. This is little uncomfortable for people accepting 0-conf.

Accepting 0-conf is not safe nor is it in Bitcoin's model by default but it would be nice if we had a small icon with a yellow exclamation mark or something near the "Unverified" transaction in the list of transactions under History tab, and also in the bottom bar where we have [+n BTC unconfirmed] signaling that the fee is under the recommended fee per kb and could take more time than usual to confirm, even get dropped from miners mempools after few hours. Of course the "below recommended fee" should be computed by electrum automatically given the variables in the network at that time.

We should have a secondary such icon for rbf replaceable transactions which have a special flag. This can be implemented when electrum will also allow generating and signing rbf replaceable transactions.

Last, does it make sense to add a third icon for possible double spend transaction?  Kind of like bc.info has - i don't know if it's possible given that Electrum servers run on Bitcoin Core which do not accept in mempool double spends.

**Comment by ecdsa** [comment]
computing the fee requires downloading all the parent transactions. 
(unless we trust the server about the amounts)

**Comment by gits7r** [comment]
I think it's fair to trust the server for the amounts in this context. This is not crucial information so we could just trust the server. We can go even further and ask 3-4 random servers about these amounts and see if the majority is a match or not.

**Comment by ecdsa** [comment]
I agree; we need to upgrade server code anyway, in order to detect RBF

**Comment by ecdsa** [comment]
server code was upgraded

**Comment by ecdsa** [comment]
done in 599906eef61832718b080b87612963f3077ce9be
