### ISSUE TITLE
Japanese new "Translation"

### ISSUE THREAD

**Issue by jusukenaora** [spesmilo/electrum#1799]
Hi all,

Japanese translation is not complete. That's why I made a custom translation.
But I can not retrieve the Bitcoin portable file "electrum.mo"

What to do load the file?

**Comment by ecdsa** [comment]
translation efforts are on crowdin.
follow the link on https://electrum.org/#community

**Comment by jusukenaora** [comment]
Sorry, but I don't want to use crowdin. (Crowdin I hate him)

My question is still the same I can retrieve the file "electrum.mo" at the start of Bitcoin?

**Comment by dabura667** [comment]
Crowdin says Japanese is 100% translated.

Either:

1. Crowdin is not the latest.
2. Some strings are missing _( ) methods
3. I have no clue what this guy is talking about.

@jusukenaora 普通にサイトから落とせばいいんじゃないですか？
Crowdinの翻訳機能使いたくなくても原文のファイルくらいは載ってますよ。

**Comment by jusukenaora** [comment]
Japanese translation really is not complete + Some texts are poorly translated.

> 
@jusukenaora 普通にサイトから落とせばいいんじゃないですか？

What ??

> 
Crowdinの翻訳機能使いたくなくても原文のファイルくらいは載ってますよ。

Yes, I do not use Crowdin. It is for me a much better editing translation using file.

**Comment by dabura667** [comment]
お求めのファイルはCrowdinのページから落とせます。アカウントの登録とか必要ありません。

翻訳機能だけじゃなくて、crowdinのサイトにアクセスすること自体が嫌という認識で宜しいですか？

であればソースからElectrumを起動する手順に従い、localeフォルダからお求めのファイルを取得して下さい。

ただ、それを何らかの形でcrowdinに戻す必要があります。

代わりに転記してくれる人がいなければ、結局ご自分でcrowdinへ入力することになります。

引き続き宜しくお願い致します。

**Comment by jusukenaora** [comment]
Thank you that you write in Japanese, but you can also write in English...

Yes I understand you, that without the project Crowdin author would have to create all translations alone. Or translating each created himself.

The best option by me:
- Who wants to help with translation as a community project will use Crowdin.
- Who does not want to use the project Crowdin do your own translation by himself and he will use.

File "electrum.mo" I can edit without problems. But the launch of electrum sources and compilation for Windows is already difficult for me.

All I want is the ability to run a translation japanese "electrum.mo" for "Bitcoin Electrum portable.exe"

**Comment by ecdsa** [comment]
.exe binaries are meant to be self-sufficient.
if you want to load your own .mo file you must run Electrum from sources.

**Comment by jusukenaora** [comment]
And there is the option to add this method in the future?

Can you advise me how to run bitcoin from source on windows to function as portable bitcoin?

**Comment by ecdsa** [comment]
I do not plan to add that method in the future.
run the python with --portable option

**Comment by jusukenaora** [comment]
> run the python with --portable option
you be more specific on how to proceed?

**Comment by ecdsa** [comment]
you run the python program from the command line with that option.

**Comment by jusukenaora** [comment]
That's the only thing I understood...

- What version of Python should I install?
- What file is to run electrum? "electrum" or "setup.py" or "setup-release.py" ?

**Comment by ecdsa** [comment]
read the docs, and the README

**Comment by jusukenaora** [comment]
I read the "ReadMe" but I see nothing there about how to run electrum from sources on windows
