### ISSUE TITLE
When freezing address, do not choose it automatically in "Receive" tab

### ISSUE THREAD

**Issue by kwaaak** [spesmilo/electrum#1800]
Example:
Designating an address as the return address for something (exchange, other arbitrary service, ...)
Address has not received a transaction.

I don't want to use the address for anything else but because it is highest in the "Addresses" list, it will be automatically chosen as the receiving address under "Receive".

It would be nice if I can use freeze on the address and that excludes it from being a "Receive" candidate.

**Comment by ecdsa** [comment]
I don't think this is a good idea; freezing addresses is about coin control.

If you want to save an address for a particular purpose (e.g. as a return address for an exchange), then you should create a request with that address; you don't need to enter an amount, a description is enough.
