### ISSUE TITLE
wallet sweep + dynamic fee issue

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#1801]
I'm not the user who experienced the bug, but based upon this user's post, it sounds like there may be an issue with sweeping the full balance of a wallet when dynamic fees are used: https://www.reddit.com/r/Bitcoin/comments/4jimdw/4kb_transaction_stuck_in_limbo_what_do/d36wsno

**Comment by ecdsa** [comment]
that's not really the issue there. this user did not know how to send all his funds, and ended up paying a fee that is too small.

**Comment by jlopp** [comment]
This certainly may be more of a user experience issue rather than a technical bug, but I humbly suggest that if users are able to shoot themselves in the foot, the answer should not be "RTFM." 

Some possible technical answers to usability problems like this:
* Add sanity checks when a user wants to send a transaction with a fee that is significantly below the market fee rate
* Add a button / obvious option in the UI that is a "send all funds" feature to ensure that the wallet is completely swept
