### ISSUE TITLE
Odd error trying to paste a bitcoin Send url

### ISSUE THREAD

**Issue by SlugFiller** [spesmilo/electrum#1805]
When trying to paste a bitcoin Send url, I got the following odd error, pop up in an information box:
"Certificate has expired"

I couldn't find any additional information about this error. This did not happen previously, and I do not see why this error should pop up.

What really bothers me, is how uninformative it is. I don't know what's the source of the problem. Is it an issue with the servers? With the address? With the certificate roots? There's no clue.

**Comment by ecdsa** [comment]
was that with the android app or the desktop version?

**Comment by SlugFiller** [comment]
Desktop version. On Windows. To double check that it wasn't a version issue, I downloaded the latest installer, and tried with the latest stable version, but no change.

**Comment by ecdsa** [comment]
can you email me the URL ?

**Comment by ecdsa** [comment]
thanks for the URL
I don't think the problem is with Electrum; the coinbase certificate in this request has expired 6 days ago.

**Comment by SlugFiller** [comment]
That doesn't sound right. Checking https://www.coinbase.com right now shows a certificate valid until Feb 2017. But I still get the error on Electrum. This doesn't add up at all, gives me utterly no recourse or options, and no relevant info.

At the very least, even if the certificate was expired (which it doesn't appear to be), the error should contain some details about the certificate, and an option to add an exception. It's what I get with Firefox, at least.

**Comment by ecdsa** [comment]
the certificate used to serve their website is probably not the same they use to sign the request.
I will add an option to ignore the exception
