### ISSUE TITLE
GUI bugs at multisig creation interface

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#1806]
When you set to create a new multisig wallet, you can choose X out of Y signatures (where x is the subset and y is the set, or X is the left box and Y is the right one). The small little arrows attached to the updownbox behave weird.

If X is smaller than Y then it works well.

If X is 1, and Y is bigger then the up arrow is enabled and the lower one is disabled for X and Y is enabled if its not +1 bigger or the cap 15. So far so good.

**The bug is here:**

 If X = Y, then the lower arrow of the X looks like it's disabled (but its not because you can obviously click on it to lower the value), whereas it should look like to be enabled, as it can still be lower.

http://imgur.com/sxRTV1r

**Comment by ecdsa** [comment]
that's a qt bug, wontfix.
