### ISSUE TITLE
Hardware wallet creation screen: list index out of range

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#1807]
When you go to the new hardware wallet creation screen and if there is not hardware wallet plugged in, there is obviously no hardware wallet listed at **Select the type of hardware wallet**.

However you can still click next, and then it gives you an error:  **list index out of range**, and then the wallet crashes.

This wizard should look better, for example if there is no hardware wallet plugged in, the next button can be disabled or something more aesthetic, because this current error popup is unnecessary.

**Comment by ecdsa** [comment]
this was already reported, #1793, #1786 
please read the existing issues before adding new ones.

**Comment by kyuupichan** [comment]
https://github.com/spesmilo/electrum/commit/11ef0f5489f0df8812cc2e9cad1d70aab2a72fbe fixes this I believe
