### ISSUE TITLE
2FA wallet creation screen is broken

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#1808]
The 2FA wallet creation screen is broken in electrum 2.6.4. 

First of all the terms of service page is blank, you enter an email address, click next and then this error shows up:

http://imgur.com/JLulZWd

Then the software crashes, and when I open it again, the blank TOS page is showing up instead of the main wallet page. No matter how many times i close and reopen it, still that broken TOS page shows up. If I click cancel, the window crashes. I have to delete the default_wallet, in order to get back to the main wallet creation page again.

http://imgur.com/GvBfPFO

I dont think its possible to create 2FA wallet in this version.

**Comment by ecdsa** [comment]
@badmofo can you have a look please?

**Comment by ecdsa** [comment]
their server must have been temporarily down. it works now.

**Comment by RealBTC** [comment]
Nope it still doesn't work.

**Comment by ecdsa** [comment]
@RealBTC what OS are you using? are you running Electrum from sources?

**Comment by badmofo** [comment]
As far as I can tell the Trustecoin server has not been down anytime today.  

@RealBTC can you provide more details?

1. What is the exact time you saw first saw this error?
1. Is it possible the network you were on is/was experience some sort of issue?  
1. Are you using Electrum behind Tor or some other sort of proxy?

**Comment by RealBTC** [comment]
It works now, i had some ports disabled and my firewall settings were very strict, now it works.
