### ISSUE TITLE
Screenshot QR Code

### ISSUE THREAD

**Issue by abueide** [spesmilo/electrum#1810]
Would be cool if you could screenshot a qr code to import it. This reddit post does it with imagemagick:
https://www.reddit.com/r/Bitcoin/comments/1rsujs/scan_qr_codes_on_your_screen_with_imagemagick_and/

**Comment by ecdsa** [comment]
what is the use case for that?
most of the time, a qr code will come with a bitcoin: URL

**Comment by abueide** [comment]
@ecdsa For any time that there isn't. Maybe some one sent a picture of their qr code. I dunno, maybe i'm just lazy and wanna do that instead of copy pasta.

**Comment by ecdsa** [comment]
wont fix; I think the use case does not justify the complexity
