### ISSUE TITLE
Lost Coins

### ISSUE THREAD

**Issue by stewart-liddle** [spesmilo/electrum#1812]
So long story short, I purchased bitcoins and sent them to wallet A in electrum in tails. Upon attempting to send the coin from wallet A to wallet B in electrum from another tails application, wallet B 'malfunctioned' and I used my seed to recover it. However, when i recovered it, the receiving address for wallet B changed, after the funds from wallet A had already been sent. When viewing wallet A, it appears that the funds went through successfully but I currently cannot find them. Any help would be appreciated. Thank you!

**Comment by ecdsa** [comment]
can you provide more details about how wallet B malfunctioned?

**Comment by kyuupichan** [comment]
It's hard to know from these reports how many are genuine because of an actual software bug and how many are user confusion or something else.  When people just close them without comment it doesn't help.
