### ISSUE TITLE
electrum run linux mint (sources)

### ISSUE THREAD

**Issue by Mrkev986** [spesmilo/electrum#1815]
Hi,

I need to run electrum from sources on linux mint.

- Electrum-2.6.4.tar.gz
I extracted the files to a folder "ABC"

I created a script "setup.sh" and put it in a folder "ABC"

"setup.sh"
```
#!/bin/sh
python ./electrum --portable
```

But it does not work for me, can you help me what is the correct registration in the script?

**Comment by ecdsa** [comment]
"it does not work" is no useful description
