### ISSUE TITLE
Electrum dont open on Windows 7

### ISSUE THREAD

**Issue by moige** [spesmilo/electrum#1816]
Hi,

ELECTRUM COMUNITY 

My problem is the next.-

I installed Electrum on Windows 7 Ulitimate Edition (32 bits). When the installation finished, I started the software without problems, I made the guided creation of a new wallet but when the software ask me "How do you want to connect to a server?" and I select the "Auto connect" option and click on the next button, the software stops workin seuddenly and closes by itself. When I try to open the software again it don't work, it create the process "electrum.exe" but it closes inmediately.

Any solutions to this problem? Plase and thanks in advance.

P.S: If I erase the folder "Electrum" located in "AppData\Roaming" the software runs again with the process of creating a new wallet but the problem persits.

**Comment by ecdsa** [comment]
please run Electrum from a console and provide a traceback

**Comment by moige** [comment]
How I can do that?

**Comment by MaxXor** [comment]
I noticed something similar on Windows 7 x64. _Sometimes_ when I start Electrum the frist time (since the system booted) it doesn't show the GUI. All I can see is two processes `electrum.exe` in taskmanager. Once I kill the processes and start it again, it's working fine.

**Comment by ecdsa** [comment]
closing.
please try with the new version, and reopen an issue if the bug is still there.
