### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by Method0fControl** [spesmilo/electrum#1820]
I just downloaded Electrum and transferred bitcoin to it. I set up 2FA with google as I have with many other products, but every time i try to send to another address, i enter the code in says Incorrect Password. Can someone please help????

**Comment by ecdsa** [comment]
did you enter your Google Authenticator code in place of your password?

**Comment by Method0fControl** [comment]
I figured it out, i had to restore my wallet, and set a signature password on it, as I hadn't done that to begin with, so it wasn't even checking the google authentication!

**Comment by ecdsa** [comment]
you don't need to restore your wallet in order to set a password...

**Comment by Method0fControl** [comment]
It wasn't letting me set it any other way....
