### ISSUE TITLE
False importprivkey error

### ISSUE THREAD

**Issue by x0x7** [spesmilo/electrum#1821]
The import private key not supported error fires falsely if another linux user attempts to insert a key even if permisions would support accessing the wallet.

The setup:

    #make wallet that supports private keys
    electrum restore -w wallet.electrum "some private key"
    #insert a private key, good
    electrum importprivkey -w wallet.electrum -W thepass "another key"
    #Running as root here on out
    sudo su
    #this fails
    electrum importprivkey -w wallet.electrum -W thepass "another key"

This wallet cannot import private keys

    addgroup wallet
    usermod -aG wallet myuser
    usermod -aG wallet root
    chgrp wallet wallet.electrum
    chmod g+rw wallet.electrum
    #this fails
    electrum importprivkey -w wallet.electrum -W thepass "another key"

This wallet cannot import private keys

    chmod a+rwx wallet.electrum
    #this fails
    electrum importprivkey -w wallet.electrum -W thepass "another key"

This wallet cannot import private keys

Perhaps the behavior of failing is correct but the error message isn't accurate.  My needs are taken care of by setting the uid of the subprocess.  I thought I would just document this quark.

**Comment by ecdsa** [comment]
I cannot reproduce this; it works for me.
The only situation where the uid would matter is if you used the user's default wallet 
(that is, you did not use the -w parameter in the command line)

**Comment by ecdsa** [comment]
Note that the message "This wallet cannot import private keys" is not caused by a unix permissions problem.
It means that the wallet you are using does not allow to import keys.

**Comment by x0x7** [comment]
Interesting that the error wasn't reproduced.  I can get the same wallet that gives me an error to import private keys if used by the right user and when using nodejs `child_process.exec` if I pass into options `{uid:1000}` it works ok.  `-w` is attached to every single command, even ones where I'm not sure it does anything like `electrum daemon`

Well, if you can't produce it and it's not a critical bug I suppose we ignore it.  Interesting quandry.

**Comment by ecdsa** [comment]
well, I suppose you did not provide full information on how you created your wallet...
I believe at some point the -w parameter is either not passed, or not taken into account.

**Comment by ecdsa** [comment]
hmm, I think it is likely that you were running a daemon (or a GUI, that would act as a daemon)
Older versions of the daemon were only able to run with the default wallet.
