### ISSUE TITLE
electrum unable to start

### ISSUE THREAD

**Issue by Lavande** [spesmilo/electrum#1822]
I'm on ubuntu 16.04 and installed electrum with these instructions:

Install dependencies:
sudo apt-get install python-qt4 python-pip
Install Electrum:
sudo pip install https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz

Then I ran 'electrum' and it returned:

> Traceback (most recent call last):
>   File "/usr/local/bin/electrum", line 332, in <module>
>     d.init_gui(config, plugins)
>   File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 233, in init_gui
>     gui = __import__('electrum_gui.' + gui_name, fromlist=['electrum_gui'])
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 48, in <module>
>     from installwizard import InstallWizard
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 10, in <module>
>     from seed_dialog import SeedDisplayLayout, SeedWarningLayout, SeedInputLayout
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/seed_dialog.py", line 30, in <module>
>     from util import *
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 30, in <module>
>     class Timer(QThread):
> NameError: name 'QThread' is not defined

**Comment by dabura667** [comment]
python-qt4 is not properly installed.

Please check to make sure no error messages were thrown during installation.

**Comment by Lavande** [comment]
Thanks for the reply. I purged python-qt4 and reinstalled it but still have the same problem here.

> ~$ sudo apt purge python-qt4
> [sudo] password for foxx: 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
>   libqt4-designer libqt4-scripttools libqt4-test libqt5clucene5 libqt5designer5 libqt5help5 libqtassistantclient4 python-sip
> Use 'sudo apt autoremove' to remove them.
> The following packages will be REMOVED:
>   python-qt4*
> 0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
> After this operation, 14.9 MB disk space will be freed.
> Do you want to continue? [Y/n] 
> (Reading database ... 211236 files and directories currently installed.)
> Removing python-qt4 (4.11.4+dfsg-1build4) ...


> ~$ sudo apt install python-qt4
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
>   libqt5clucene5 libqt5designer5 libqt5help5
> Use 'sudo apt autoremove' to remove them.
> Suggested packages:
>   python-qt4-dbg
> The following NEW packages will be installed:
>   python-qt4
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 0 B/2,328 kB of archives.
> After this operation, 14.9 MB of additional disk space will be used.
> Selecting previously unselected package python-qt4.
> (Reading database ... 211177 files and directories currently installed.)
> Preparing to unpack .../python-qt4_4.11.4+dfsg-1build4_amd64.deb ...
> Unpacking python-qt4 (4.11.4+dfsg-1build4) ...
> Setting up python-qt4 (4.11.4+dfsg-1build4) ...


> ~$ electrum 
> Traceback (most recent call last):
>   File "/usr/local/bin/electrum", line 332, in <module>
>     d.init_gui(config, plugins)
>   File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 233, in init_gui
>     gui = __import__('electrum_gui.' + gui_name, fromlist=['electrum_gui'])
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 48, in <module>
>     from installwizard import InstallWizard
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 10, in <module>
>     from seed_dialog import SeedDisplayLayout, SeedWarningLayout, SeedInputLayout
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/seed_dialog.py", line 30, in <module>
>     from util import *
>   File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 30, in <module>
>     class Timer(QThread):
> NameError: name 'QThread' is not defined
> 


It seems that the installation of python-qt4 was quite successful. Any ideas what may be wrong here?

**Comment by Lavande** [comment]
just ran 

> sudo apt-get install python-qt4*

to get a lot of packages installed, but still not working

**Comment by ecdsa** [comment]
closing this. 
'still not working' is not something we can work with
