### ISSUE TITLE
Doesn't accept password, impossible to do transfert ...

### ISSUE THREAD

**Issue by maxlasco** [spesmilo/electrum#1823]
Hello,

Thanks for your time and your future reply.

I can't use my electrum wallet because when I want to do btc's transfert, electrum doesn't accept my password. 
The problem is that it is my real password and I am sure about that because i use my wallet everyday ... Now it is blocked when I try, it is write '' incorrect password '', I don't know why ...

I made one transfert today and it worked good, 5 minutes after I tried to do second transfert and it is impossible ...

What's happen ? What can I do ?

Please help me!!

Friendly Regards,

**Comment by ecdsa** [comment]
probably caps lock

**Comment by maxlasco** [comment]
It is ok, everything work now! I don't know what's happened ... I just close and open and in using same password than before it worked!!

Thanks for reply
