### ISSUE TITLE
won't start in opensuse

### ISSUE THREAD

**Issue by mmoriz** [spesmilo/electrum#1825]
I installed electrum in opensuse by installing the dependencies and then performing:
`sudo pip install https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz`

After this the electrum icon appeared in my application list but it won't start when clicking it. When starting from the terminal I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/electrum", line 75, in <module>
    check_imports()
  File "/usr/bin/electrum", line 49, in check_imports
    import aes
  File "/usr/lib/python3.4/site-packages/aes.py", line 643
    raise ValueError, emsg % keysize
                    ^
SyntaxError: invalid syntax
```
So I guess this would have to be fixed by the SlowAES project to which the aes.py belongs but I couldn't really figure out where to report issues for them :/

**Comment by ecdsa** [comment]
use python2, not python3

**Comment by mmoriz** [comment]
doesn't that mean that for every distribution that uses the python3 version of pip by default the installation instructions from the website won't work? as you would have to use pip2 to install instead of pip?
