### ISSUE TITLE
Config file parameters

### ISSUE THREAD

**Issue by Conver** [spesmilo/electrum#1826]
Hello,

I've been trying to find some docs about Electrums config file. But haven't been able to find anything.

Is there somewhere some docs over that?

I'm asking because I'm trying to find a way to allow other IP's than localhost to query the RPC interface of Electrum. It's all still in private networking, but I rather not having the electrum client on the same servers as webserver, is there a way to allow other IPs?

Maybe something to put in the config file beside the "rpcport"?

**Comment by Conver** [comment]
Doing an `netstat -lp` gives me:

`tcp        0      0 localhost:7778          *:*                     LISTEN      8574/python`

Any config options or startup inits that I can use to make it listen to outside aswell?

With "outside" I mean my private networking. It will still not be open from outside, but this still doesn't allow me to query from another server in my DC.

The DC is hosted locally, running 50+ servers, where some are web servers operating behind load balancing, the Electrum is running on its own server, so that all web servers can query it, without needing to run the same Electrum wallet on all webservers.

**Comment by EagleTM** [comment]
rpchost=
rpcport=
is what you want. 

See lib/daemon.py
host = config.get('rpchost', 'localhost')
port = config.get('rpcport', 0)

**Comment by Conver** [comment]
It worked, thank you very much.

You might want to update [merchant.html#jsonrpc-interface](http://docs.electrum.org/en/latest/merchant.html#jsonrpc-interface) to add this. Since its needed to talk to Electrum from another web-server, still in same private networking.
