### ISSUE TITLE
Import address limit?

### ISSUE THREAD

**Issue by olalonde** [spesmilo/electrum#1827]
I'm trying to create a new watch only wallet from 2000 pubkeyhash addresses and it doesn't seem to work (the continue link is disabled). If I only import 250 addresses it does work however. Is there a limit or should I wait for a few minutes?

**Comment by ecdsa** [comment]
no there's no limit. did you copy and paste them?

**Comment by olalonde** [comment]
Copy/paste them, from a file. All addresses are delimited by new lines with no extra spaces.

**Comment by ecdsa** [comment]
well, don't use copy paste for something of this size, try to load the file directly.

**Comment by olalonde** [comment]
Ah.. is there a file format for the file? One address per line?

**Comment by ecdsa** [comment]
you load the file in the textbox, so it's the same format
