### ISSUE TITLE
Electrum reports "Certificate has expired"

### ISSUE THREAD

**Issue by ThomasFreedman** [spesmilo/electrum#1829]
Using version 2.6.4 on Debian Jessie linux. Python versions installed: 2.7.9 and 3.4.2

Wallet starts and shows correct balance, but it won't allow me to send any funds. 

Despite me selecting 3 different servers to connect Electrum to, all reported the same error. 

However, when I tried to send to another address the transfer worked OK, so it must be a cert issue on the recipients server, not Electrum or Electrum servers. Apparently.

It might be nice if you provided more info in the popup, like the server name or IP address the error occurs on.

**Comment by dabura667** [comment]
This is an issue with Coinbase and Bitpay payment codes.

They have said they will update their certs next week.

**Comment by ecdsa** [comment]
this was fixed 3 weeks ago: 8c42c6d39f26b5b680be5f6b7c1c8ac4a1075609
please try to check if a bug is already fixed in git master, before reporting it.
