### ISSUE TITLE
"addresses" tab missing

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1831]
Just pulled fresh master.

The "Addresses" tab is gone.

Expectation: there should be an addresses tab showing accounts and addresses I can use to

- view all used and some future addresses
- check balances of individual addresses 
- select address for receiving coins (using context-menu, "copy address")
- set priority or freeze individual addresses (using context-menu)
- select address(es) to send from (using context-menu, "send from")
- perform signing, signature verification action

I like to take an address-centric view on my wallet and I like accessing above features through the address list.

**Comment by ecdsa** [comment]
it's going to be hidden by default. 
you can open it from the menu or using Ctrl-A

**Comment by molecular** [comment]
oh, ok. I see, thanks. And it's even stored across reboots, awesome.

sorry for the waves, I was looking in settings for some advanced mode and couldn't find it. I feared you guys had gotten rid of that tab to streamline UX or something.

good to see I can still use this ;)

**Comment by ecdsa** [comment]
NP. It also lets you view UTXOs for each address now

**Comment by ecdsa** [comment]
btw, thanks for testing the git version :)
