### ISSUE TITLE
old wallet seed does not restore properly

### ISSUE THREAD

**Issue by rnewsham** [spesmilo/electrum#1832]
I have an old wallet, circa march 2014. I had trouble running whatever version of electrum I had at the time, so I upgraded to 2.6.4, but none of my addresses/balance/history were there.

I restored (on multiple machines) from the seed, but get the same result.

Please advise.

I still have copies of the old wallet, which show transactions and addresses and balances.

I had restored from this seed in the past, and I've tried it multiple times. I'm positive I'm typing it in accurately.

**Comment by rnewsham** [comment]
I was able to downgrade to 1.9.5 and use the command line interface to dump priv keys.   (could not connect to servers, could not restore from seed, but was able to find my old wallet and dump)

I'll sweep them into a new wallet.

**Comment by dabura667** [comment]
Is your phrase 12 words?

Old phrases are only restored properly if they are 12 words.

(I am aware some people would add words for "extra randomness" on the old wallet manually... those will not be restored... but one that was generated by electrum <2.0 will be restored.)

**Comment by rnewsham** [comment]
yes, it's a 12 word phrase.

I've getseed'ed it out of the old wallet (multiple times) to be sure I was not in error.

**Comment by rnewsham** [comment]
greatly relieved to have gotten through this. was able to sweep to new wallet.

**Comment by ecdsa** [comment]
what was the issue? can you email me the old seed, or a copy of the old wallet?
