### ISSUE TITLE
Plans to support stealth addresses

### ISSUE THREAD

**Issue by Jzarecta** [spesmilo/electrum#1833]
Wonder if there are plans to support the **stealth addresses**. This will increase the privacy of the user. 
Here is some documentation that is on this topic:
http://sx.dyne.org/stealth.html

These scripts could be integrated into the wallet and make it easier for people to use such feature.

**Comment by dabura667** [comment]
I was one of the guys working on stealth addresses.

I have a branch on my fork of electrum that supports sending to them (based on a very old version of eleectrum)... But managing receives FROM them is an extremely difficult problem.

Darkwallet devs have abandoned stealth addresses and are saying that once dark wallet dev starts again they will implement BIP47 instead.

Please look up BIP47. These are much better than stealth addresses, and can be monitored by SPV wallets like Electrum

**Comment by ecdsa** [comment]
yeah, you need a full node to monitor payments to stealth addresses
