### ISSUE TITLE
Upgraded electrum can't see any of my info

### ISSUE THREAD

**Issue by stuaxo** [spesmilo/electrum#1842]
I had an old version of electrum, I've upgraded (having to run in a virtualenv, as it seems impossible to install outside).

When I start it, I can't see any of my info, which is obviously a little concerning.

**Comment by ecdsa** [comment]
do you understand that we can't help you if you provide so little information?
if you are not able to describe the situation with words, please post a screenshot.

**Comment by stuaxo** [comment]
When I ran the older version I could see some transactions, which were pending.

There isn't much to show in my screenshot, as it just looks like a fresh install.

Current screenshot
http://imgur.com/7OD14RW

I don't have a screenshot of what it did look like unfortunately.

I guess I need to find the bit of paper with the seed info on it, which is ... somewhere.

**Comment by stuaxo** [comment]
Looks like my key was a 12 word key, so I guess that was generated in Electrum 1.x ?

Found the bit of paper, of course now can't read my handwriting for the last word.   I can easily write some python to iterate all the words for the last one, how can I check if it is actually my wallet for each one ?

**Comment by ecdsa** [comment]
Closing this issue, this is not an electrum bug.
you can check with the is_seed() function in bitcoin.py
FYI, Electrum 2.x sometimes creates seeds with 12 words.

**Comment by stuaxo** [comment]
OK, retrieving it is not.  How it went may be -

How did I go from having a wallet, to not having a wallet ?

I upgraded and my wallet wasn't there any more (or at least didn't seem to be - originally I had transactions pending, where I transfered from the official bitcoin wallet to electrum) - and then after upgrade there was nothing.

**Comment by stuaxo** [comment]
I guess I could have had both versions running concurrently, could that cause an issue ?

**Comment by ecdsa** [comment]
maybe you created another wallet file? I have no idea. you are not clear about what you've been doing.
