### ISSUE TITLE
Exception while trying to initialize new hardware wallet

### ISSUE THREAD

**Issue by lmacken** [spesmilo/electrum#1843]
I plugged in my new KeepKey, started Electrum 2.6.4, and got the following exception when trying to initialize a new hw wallet.

```
Traceback (most recent call last):
  File "/home/luke/Electrum-2.6.4/gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/home/luke/Electrum-2.6.4/lib/wizard.py", line 151, in run
    cr, wallet = self.create_or_restore(storage)
  File "/home/luke/Electrum-2.6.4/lib/wizard.py", line 225, in create_or_restore
    wallet_type = hw_wallet_types[choice]
IndexError: list index out of range
```

The "Select the type of hardware wallet" section is also empty...

**Comment by lmacken** [comment]
Okay, I managed to get the python keepkey bindings built and now it's appearing in the list of hardware wallets. Still having some permission error, I'm guessing around udev, but either way the IndexError could possibly be handled a little more gracefully.

**Comment by ecdsa** [comment]
this bug is not relevant with the new wizard
