### ISSUE TITLE
windows build - update python-trezor

### ISSUE THREAD

**Issue by prusnak** [spesmilo/electrum#1846]
please update bundled dependency of python-trezor to at least version 0.6.13 for windows build

this fixes issues with firmware 1.3.6 (it is unusable with older python-trezor) on windows

**Comment by slush0** [comment]
Who to bribe to publish fixed Windows builds? :-) Lot of users are asking...

**Comment by ecdsa** [comment]
@slush0 is your last commit needed?

**Comment by ecdsa** [comment]
please test http://download.electrum.org/test/

**Comment by ecdsa** [comment]
<RainMan28> ThomasV: hi, just downloaded it. Still not detecting my trezor.
<RainMan28> the version number is still 2.6.4?
<ThomasV> any error message?
<RainMan28> No just that Could not connect to your TREZOR. Verify the cable is connected...

**Comment by ecdsa** [comment]
I guess it does not work because commit fdb810ba622dc7dbe1259cbafb5b28e19d2ab114 is needed with recent versions of python-trezor. If the trezor guys are willing to backport their patch to 2.6.4, I can try to create new builds. Otherwise it will need to wait until 2.7 is ready

**Comment by prusnak** [comment]
As discussed with slush: Please do the rebuild of 2.6.x with python-
trezor 0.6.13.
  
.7.0 is meant for master only.

**Comment by ecdsa** [comment]
ok, new binaries in http://download.electrum.org/test/ using 0.6.13

**Comment by Tisbox** [comment]
@ecdsa; I just installed this new build over the previous 2.6.4. installation.
Results: everything works just fine again, so thank you for that.
What I tried was connecting the Trezor and then starting Electrum (Electrum now asked for the PIN again). Also I created a transaction to see if the Trezor could sign it correctly, and it did.
If there's anything else I can do for you (send logs or whatever) please let me know.

**Comment by ecdsa** [comment]
thanks for testing, I uploaded the binaries to the download page

**Comment by prusnak** [comment]
Thank you very much for prompt response.

**Comment by Aragonite** [comment]
Mac OS was spared this time - Trezor 1.3.6 and Electrum 2.6.4 playing well together...

**Comment by Tisbox** [comment]
@ecdsa: shouldn't you release it as version 2.6.4a or 2.6.5 with the release note mentioning added support for Trezor firmware 1.3.6? Or at least on the download page mention the fact that the binaries are updated?
Because others who run in to the same problem and check the download page will think they already have the latest version while in fact they don't.

**Comment by ecdsa** [comment]
@Tisbox I made an announcement on twitter.
