### ISSUE TITLE
Allow stuck transactions to be zapped from mempool

### ISSUE THREAD

**Issue by cryptonaut420** [spesmilo/electrum#1847]
Sometimes, for various reasons, it is possible for a transaction to get stuck in limbo and seemingly never get picked up by any miners (I once had an electrum TX take over 7 days to get fully dropped from network). It would be nice for situations like this if there was an advanced feature equivalent to bitcoind's -zapwallettx option. Basically drop the unconfirmed tx from electrum mempool and allow user to double spend the coins with higher fee.

**Comment by ecdsa** [comment]
the next electrum release will have RBF.
it's already available in git master.
