### ISSUE TITLE
Please help!!

### ISSUE THREAD

**Issue by hanaix** [spesmilo/electrum#1848]
Hi,
I have a problem, I can not send me out of my wallet ?? He writes me this message?
Look at the picture !!
[http://www.imgbank.cz/images/2016/06/27/cats.jpg]

**Comment by dabura667** [comment]
The fee is too low.

In the options, check "dynamic fees" checkbox and set the slider to 100%

Then try sending again.

**Comment by hanaix** [comment]
yes. OK thank you so much ))
