### ISSUE TITLE
Trezor with firmware 1.3.6 not recognized by Electrum 2.6.4

### ISSUE THREAD

**Issue by Tisbox** [spesmilo/electrum#1852]
Since upgrading my Trezor to firmware v1.3.6, Electrum v2.6.4 for Windows won't recognize the Trezor at all anymore. Neither the Trezor nor Electrum ask for a password etc., it's just like the Trezor is not connected at all. I'm running Windows 10.
The Trezor works just fine with the website mytrezor.com (having 'Trezor Bridge' software installed).

**Comment by ecdsa** [comment]
duplicate of #1846
