### ISSUE TITLE
Console password() doesn't work

### ISSUE THREAD

**Issue by wirion** [spesmilo/electrum#1853]
Steps in Electrum 2.6.4 (Windows and Linux):
1. Create a new standard wallet with password.
2. In the console, type `password()`
3. In the appearing dialog, click cancel.
4. Check Wallet->Seed.

The seed is now garbled, and the wallet isn't password protected anymore. If at 3. you type in the password and click ok, the wallet gets decrypted, i.e. loses its password protection.

I'm new to Electrum, but this behavior struck me as odd. Additionally, the electrum CLI password command seems to work correctly.

**Comment by ecdsa** [comment]
indeed that's a bug
