### ISSUE TITLE
User config broken and undocumented

### ISSUE THREAD

**Issue by angelogladding** [spesmilo/electrum#1855]
Can't find details regarding config structure anywhere.

Digging in I find that `~/.electrum/config` is the correct location. The sample provided is named `electrum.conf.sample` which seems to imply that the final filename will be `electrum.conf`. An error message pointed me to `~/.electrum` but only the code references a `config` file expected therein. Furthermore the `ast.literal_eval` fails with the sample config.

`read_user_config` in `lib/simple_config.py` initially attempts to parse JSON. Reformatting the config into JSON and placing it in the correct location `~/.electrum/config` appears to work..

Why both JSON and AST parsing? Is everyone fumbling through these same steps or am I missing something from the GUI as I'm in a strictly headless environment.

**Comment by ecdsa** [comment]
Early versions used ast; the parsing code is here for backward compatibility.
The /etc/electrum.conf file is a system wide configuration.
it is properly documented, read line 4

**Comment by angelogladding** [comment]
Now I see master with JSON only parsing. However the current `electrum.conf.sample` looks to be in `configparser` syntax or something -- definitely not JSON. Furthermore there remains no documentation of the user-writable home directory configuration setup. [This commit](https://github.com/spesmilo/electrum/commit/86d463123020afa6cfb08a1cb66286aebad2e898) shows where the comment semantics drifted. I recommend updating the sample to JSON with a comment: `{"client": {"gui": "qt", . . ., "__comment": "copy this file to /etc/electrum.conf if you want read-only system-wide settings or ~/.electrum/config if you want user-writable settings"}}`.

**Comment by angelogladding** [comment]
Here's what the sample conf would look like:

    {"client": {"num_zeros": 2, "fee": 10000, "proxy": null, "use_change": true, "gap_limit": 5, "gui": "qt", "winpos-qt": [799, 226, 877, 435], "server": "electrum.novit.ro:50001:t", "__comment": "Settings defined here are shared across wallets. Copy this file to /etc/electrum.conf if you want read-only system-wide settings or ~/.electrum/config if you want user-writable settings."}}

JSON comments are ugly, yes.

Keeping the current config format really does seem to make the most sense. Here's what the parsing code would look like:

    import configparser
    parser = configparser.ConfigParser()
    parser.read("electrum.conf.sample")
    config = dict(config["client"].items())

**Comment by angelogladding** [comment]
Now I see the problem. [`read_system_config`](https://github.com/spesmilo/electrum/blob/master/lib/simple_config.py#L191) *is* using `configparser` which is why your config sample is named and structured as it is. [`read_user_config`](https://github.com/spesmilo/electrum/blob/master/lib/simple_config.py#L211) however still expects JSON..

I believe the issue still stands. Updated description: `read_user_config` has fallen out of sync with `read_system_config` in `simple_config.py` and `electrum.conf.sample` does *not* explain user-writable configuration.

Thanks.

**Comment by ecdsa** [comment]
I don't think there is an issue here, except wrong user expectation.
system configuration is different from user config. 
the use cases for system config are limited, maybe we should remove it altogether.
