### ISSUE TITLE
PIN protect master public key

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#1856]
The master public key should also be password protected to be revealed like the seed.

It is semi-confidential information or at least hurts the privacy of the user if revealed. Not just that but a child private key + master public key can be used to guess the seed, therefore the master public key plays not just a privacy role, but also a security role.

So in my opinion it should be treated as semi confidential, or atleast a warning should popup when a user tries to reveal it. However a PIN protection would be ideal.

**Comment by ecdsa** [comment]
this has been discussed already. the answer is no.
use google for more details.
