### ISSUE TITLE
KeepKey hardware wallet not supported in Windows builds

### ISSUE THREAD

**Issue by rcd** [spesmilo/electrum#1857]
I mentioned this on Twitter but decided it would be good to create an actual ticket. 

The builds for Windows do not support the KeepKey hardware wallet. TREZOR and Ledger support is included. This is true for standalone, portable, and installer based builds.

I have tested the [integration instructions](https://support.keepkey.com/support/solutions/articles/6000090280-electrum-keepkey-integration-windows-7-8-10-) on the KeepKey support website and they do work. I have been using these instructions with the 2.6.4 release code for several weeks without issue.

The builds for Mac and Linux do contain KeepKey support and work well.

![electrum_hardware](https://cloud.githubusercontent.com/assets/280475/16547380/21b9c942-4131-11e6-9322-60db64c4457d.png)

**Comment by ecdsa** [comment]
can you test if it's fixed in the new 2.7 builds?
http://download.electrum.org/2.7.0/

**Comment by rcd** [comment]
Windows does not detect the KeepKey in either portable or setup builds.

KeepKey is detected and works on macOS.

**Comment by frizop** [comment]
2.6.4 doesn't show the wallet as an option (this was linked earlier) 2.7 only lists what wallets it finds (I currently don't have the device plugged in so I can't test).

**Comment by rcd** [comment]
macOS finds the KeepKey (2.6.4 & 2.7) and it works well.  Windows does not have the option for KeepKey in 2.6.4 and the device is not detected in 2.7.

**Comment by snakies** [comment]
Im running windows 10 and Electrum 2.7.1 portable doesnt detect my KeepKey either. I see error "No hardware device detected". I cant wait until I can use Electrum portable with my KeepKey.

**Comment by ecdsa** [comment]
fixed in 2.7.3
