### ISSUE TITLE
Empty error message on sending

### ISSUE THREAD

**Issue by jonasvp** [spesmilo/electrum#1858]
I use Electrum (rarely) and it works fine for sending and receiving. A few years ago I imported a private key from another program (can't even remember which one) and the BTC in there are inaccessible. Sending from the address or trying to sweep them into an Electrum address returns a popup just saying "error: "

Diving in with `pdb` I see the failure is in [this line](https://github.com/spesmilo/electrum/blob/master/lib/network.py#L867) with `out` being the empty string (`''`) while `tx_hash` is not empty.

I'm fine with Python but don't know enough about BTC internals to be able to debug this. Does anyone have an idea what might be causing this?

**Comment by ecdsa** [comment]
updating title; I don't think it has anything to do with the address being imported

**Comment by ecdsa** [comment]
Do you still have this issue? if yes please post the transaction (in hexadecimal) and the server.
Note: you can create the transaction with 'preview' and 'sign'

**Comment by bauerj** [comment]
Closing since there was no response in the past year. If you still encounter this issue, please reopen.
