### ISSUE TITLE
Editing description shows hard-to-read white-on-blue text overlaid with black-on-blue text

### ISSUE THREAD

**Issue by fortran77** [spesmilo/electrum#1861]
Ubuntu 14.04.4 LTS, electrum 2.6.4, also latest "master" branch electrum 2.7.0.

Editing the description of a transaction on the history screen shows the current description as white-on-blue text, overlaid with the same description as black-on-blue text. The two fonts are not of the same width, making the result hard to read.

Editing keys affect only the black-on-blue text. After editing is done, hitting Return leaves behind only the white-on-blue text, correctly edited.

The screenshots below were obtained using the latest "master" branch, which identifies itself as electrum 2.7.0. However, the issue is identically exhibited by the official 2.6.4 release.

First, here is a screenshot showing the initial electrum window.

![screenshot from 2016-07-07 17 11 58](https://cloud.githubusercontent.com/assets/6755457/16673849/b3e14a74-4466-11e6-938c-3190bfd87480.png)

After I double-click on the description, electrum enters editing mode, and the text looks like this.

![screenshot from 2016-07-07 17 14 06](https://cloud.githubusercontent.com/assets/6755457/16673860/d1731a72-4466-11e6-86bd-73dd61545eae.png)

**Comment by ecdsa** [comment]
did you try to upgrade qt?

**Comment by fortran77** [comment]
I am not sure how to answer this question. Maybe there's some missing context.

Ubuntu 14.04.4 LTS was fully updated via the usual methods (namely: sudo apt-get dist-upgrade; or in some cases by running the Chrome OS "crouton" script, which yields the same result), so all the packages would have been at the revision level specified by Ubuntu 14.04.4 LTS.

I did not explicitly try to update any qt library to any level higher than that bundled into Ubuntu 14.04.4 LTS.

**Comment by ecdsa** [comment]
what does "dpkg -s python-qt4" return?

**Comment by fortran77** [comment]
Output from

    % dpkg -s python-qt4

is:

    Status: install ok installed
    Priority: optional
    Section: python
    Installed-Size: 13845
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Architecture: amd64
    Version: 4.10.4+dfsg-1ubuntu1
    Replaces: python-qt4-dev (<< 4.4.4-3~)
    Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libpython2.7 (>= 2.7), libqt4-dbus (>= 4:4.8.0-1~), libqt4-declarative (>= 4:4.8.0-1~), libqt4-designer (>= 4:4.8.0-1~), libqt4-help (>= 4:4.8.0-1~), libqt4-network (>= 4:4.8.0-1~), libqt4-script (>= 4:4.8.0-1~), libqt4-scripttools (>= 4:4.8.0-1~), libqt4-svg (>= 4:4.8.0-1~), libqt4-test (>= 4:4.8.0-1~), libqt4-xml (>= 4:4.8.0-1~), libqt4-xmlpatterns (>= 4:4.8.0-1~), libqtassistantclient4 (>= 4.6.3), libqtcore4 (>= 4:4.8.0-1~), libqtgui4 (>= 4:4.8.0-1~), libqtwebkit4, libstdc++6 (>= 4.1.1), sip-api-11.0
    Suggests: python-qt4-dbg
    Breaks: python-kde4 (<= 4:4.6.80-3+b1), python-qscintilla2 (<= 2.5.1-1), python-qt4-dbg (<< 4.8.3-3), python-qt4-gl (<< 4.8.3-3), python-qt4-gl-dbg (<< 4.8.3-3), python-qt4-phonon (<< 4.8.3-3), python-qt4-phonon-dbg (<< 4.8.3-3), python-qt4-sql (<< 4.8.3-3), python-qt4-sql-dbg (<< 4.8.3-3), python-qwt3d-qt4 (<< 0.1.7~cvs20090625-7), python-qwt5-qt4 (<= 5.2.1~cvs20091107+dfsg-6), python-sip4 (<< 4.13.1~)
    Description: Python bindings for Qt4
     PyQt4 exposes the Qt4 API to Python. The following modules are supported:
      * QtCore
      * QtDBus
      * QtGui
      * QtNetwork
      * QtXml
      * QtScript
      * QtSvg
      * QtTest
      * QtAssistant
      * QtWebKit
      * QtOpenGL (in python-qt4-gl)
      * QtSql (in python-qt4-sql)
      * phonon (in python-qt4-phonon)
    Homepage: http://www.riverbankcomputing.co.uk/software/pyqt/
    Original-Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>

**Comment by ecdsa** [comment]
FYI, I have version 4.11.2+dfsg-1
I do not know if that is the reason, yours seems fairly recent.

**Comment by ecdsa** [comment]
do you have the same issue if you right click the label and use 'edit description' in the popup menu ?

**Comment by fortran77** [comment]
Right click then 'edit description' gives the same behavior.

**Comment by ecdsa** [comment]
ok, in that case I don't think it can be fixed in Electrum; you probably want to upgrade qt or python-qt.
closing this.
