### ISSUE TITLE
Recent loss of previous compatibility with seed words from non-electrum software wallets

### ISSUE THREAD

**Issue by fortran77** [spesmilo/electrum#1862]
On Ubuntu 14.04.4 LTS, in electrum 2.6.4, one could begin to restore a Trezor hardware wallet, then enter the seed words from any of Mycelium, Coinomi, and the like. No actual hardware wallet needed to be connected. This provided a certain amount of compatibility between electrum and other software wallets, allowing electrum to be used to monitor and manipulate balances in almost any wallet.

Certain other sequences of commands caused a hang or a loop if no hardware wallet was connected. See issues #1772 and #1793.

In the latest "master" branch electrum 2.7.0, no hardware wallet import is permitted if no hardware wallet is connected. Presumably this is intended to fix the above-mentioned issues.

But this also seems to have lost us a useful feature that allowed compatibility with other software wallets that generate seed words differently. I was unable to find any other combination of commands that would let me import seed words from Mycelium and Coinomi.

**Comment by dabura667** [comment]
Relying on unintended "features" is never a good idea.

NACK.

This should be rephrased as "Feature Request: add BIP44 wallet restore option" and mention the stuff you mention in this post.

**Comment by ecdsa** [comment]
I am preparing a major code rewrite. Multiple accounts will no longer be supported in a single GUI window. This means that Trezor compatible wallets will have to be split into several wallet files.

**Comment by ecdsa** [comment]
update: I pushed the refactored code to the 'dev' branch.

**Comment by ecdsa** [comment]
this is merged now
