### ISSUE TITLE
SCAM ON ELECTRUM(PLEASE HELP ADMIN)

### ISSUE THREAD

**Issue by purestmoney** [spesmilo/electrum#1864]
I register Multisig account on multisig for the purpose of business with a vendor, now after i have deposited money into the wallet, he sent me a fake document to show that he has done my job, but it was not done, and since he has one of the key, i cannot withdraw my money without the second key and i cannot pay him my money because he is a scam, i want admin to please tell me how i can withdraw my money, am ready to do anything am told to do please. This is a borrowed money, if lost then i will run on big loss.  Thanks  youcancomein2@yahoo.com

**Comment by dabura667** [comment]
If you have made a 2 of 2 wallet, the only thing you can do is wait until he sends it to you and don't ever send it to him.

There is nothing we can do to help.

**Comment by purestmoney** [comment]
he is not ready to send anything sir, but you can trace it in the account that the money was put in the wallet by me, he only said he will delete the wallet and will not have access to the money anymore, this is not small money please help, its your site, you should be able.  i have  51.001831 BTC

**Comment by purestmoney** [comment]
he is said that i was smart and did not become scammed, so there is not way he will release the second key, because he pay him that i lose everything and he has nothing to lose

**Comment by purestmoney** [comment]
if am help, i will make donation to this site

**Comment by purestmoney** [comment]
i can open a single account then you can help me transfer it to the single account

**Comment by dabura667** [comment]
Electrum is not a web service. All keys are generated by the users and no information is shared with anyone except the users.

The other person has scammed you.

The only way you can remedy this is:

1. Convince him to sign a transaction.
2. Steal his key somehow and sign the transaction for him.

**Comment by purestmoney** [comment]
after signing a transaction , how will i now get the key?

**Comment by dabura667** [comment]
No. I mean OR.

Convince him to return the money to you.

OR

Steal his keys somehow... (I dunno, hire a world class hacker from Russia or something) and sign with both keys by youself.

--------------

Have you tried negotiating? Like "I will give you 10% if you sign to give me back 90%" etc.

If he has "nothing to lose" then maybe agreeing to give him a small part will give him something "to lose" so he won't throw away his keys.

You can create a transaction sending to two different people at the same time, so there is no need to worry about who sends first. You can send at the same time in the same transaction.

**Comment by purestmoney** [comment]
he was even offered 20%, he is just adamant, he want 99% of money which is not his, any idea of such hacker, those i could think of are not available, and another thing is what if he did not store the key on the computer

**Comment by ecdsa** [comment]
we cannot do anything ; Electrum is software, not a service.

**Comment by purestmoney** [comment]
he was even offered 20%, he is just adamant, he want 99% of money which is not his, any idea of such hacker, those i could think of are not available, and another thing is what if he did not store the key on the computer
