### ISSUE TITLE
Cannot restore wallet with right seed

### ISSUE THREAD

**Issue by tempora95** [spesmilo/electrum#1867]
I try to restore the wallet with my seed, which I type exactly as it is on my paper and check it 5 times and I cannot press the NEXT button. I have 24 words seed.
Account was created on 2.5.4 version and currently use 2.6.4.

Is it possible to generate my seed again if I have the password?

**Comment by ecdsa** [comment]
if you have a two-factor wallet, you need to select that option in the menu.

**Comment by tempora95** [comment]
I do not have two factor wallet

**Comment by dabura667** [comment]
did Electrum generate that 24 word phrase for you?

If not, then your phrase is not supported.

**Comment by kyuupichan** [comment]
The other possibility is a hardware wallet.

**Comment by tempora95** [comment]
Yes, I created the wallet like 8 months ago and saved that 24 words seed from Electrum
