### ISSUE TITLE
Help with transaction

### ISSUE THREAD

**Issue by tempora95** [spesmilo/electrum#1868]
I do not understand:
Let's say my balance is 0.01539360 BTC and I want to send the entire amount minus minor fee, but when I type somewhere around that amount it writes me "insufficient funds". Or if I try to put the USD equivalent of even 10.0$, it shows me again "insufficient funds", although I see it shows the balance of 10.33$, how can a transaction fee be more than 33 cents for this tiny amount?
I totally do not understand this, help me.

**Comment by dabura667** [comment]
Type ! into the amount box and it will send all the money in your wallet minus the fee.

Fees are related to data size, so if you have received many small transactions, over 33 cents is very common.

If you have a very small transaction (data size, not amount) it will usually be about 4 cents.

**Comment by tempora95** [comment]
Thank you for your advice!

I had just one transaction in my wallet. I typed ! in the amount field, and it is still only 9.92$ (while it is showing my balance at 10.26$). If I add up the amount + transaction fee - it does not add up to full balance.

How to measure the transaction data size?
