### ISSUE TITLE
Turkish Language Translations?

### ISSUE THREAD

**Issue by FlashBoot** [spesmilo/electrum#1869]
Hi, 
I want to translate Turkish language.
Where translation is done?

**Comment by dabura667** [comment]
https://crowdin.com/project/electrum

It looks like they haven't added Turkish yet.

@rdymac @ecdsa Could you add Turkish to Crowdin? Thanks.

**Comment by rdymac** [comment]
@dabura667 added. I'm not up to date to be sure if crowdin is still used in the current builds. Confirm if you find it out.

**Comment by ecdsa** [comment]
yes it is stil used

**Comment by FlashBoot** [comment]
Thanks.
