### ISSUE TITLE
All translations are not updated

### ISSUE THREAD

**Issue by kevlarsefirot** [spesmilo/electrum#1870]
Hi,

Example: Chinese translation is complete "Electrum-2.6.4/lib/locale/zh_CN/LC_MESSAGES/electrum.mo" when I looked into it all is translated.
But when I run Bitcoin Electrum some things are not translated.
It seems that all translations are complete, but the old version (ID text is missing or incorrect and, therefore, cannot be translated)
https://s32.postimg.org/h886vlsp1/text.png

**Comment by kevlarsefirot** [comment]
Can anyone answer me?
@rdymac @ecdsa

**Comment by kevlarsefirot** [comment]
Up

**Comment by ecdsa** [comment]
you need to run contrib/make_locale
