### ISSUE TITLE
"Pay to many": Is there a way to spend all funds?

### ISSUE THREAD

**Issue by Prachtlappen** [spesmilo/electrum#1871]
Hello there,

I just love Electrum but I miss something: a way to spend all non-frozen funds when using "pay to many".

Input in the "pay to" field might look like this:

`<bitcoin-address1>,<amount1>
<bitcoin-address2>,!`

This would mean it sends the given amount to address1 and all the rest minus the calculated fee to address2 - is this possible to do with the current client or possible to implement?

Thanks in advance,

Prachtlappen

**Comment by RustyNomad** [comment]
Would also like to see this feature implemented. See it has been discussed on issue 1698 already.

[https://github.com/spesmilo/electrum/issues/1698](url)

**Comment by ecdsa** [comment]
closing, duplicate of #1698
