### ISSUE TITLE
major electrum wallet issue

### ISSUE THREAD

**Issue by smalltimetrader** [spesmilo/electrum#1872]
I sent all the btc i had in my electrum wallet to the tumbler helix lite address for my transaction from my electrum wallet. This wallet had lots of smaller transactions in to make up the total btc I was tumbling so I decided I wanted to set up a new wallet to run alongside the default wallet in electrum that i could keep tidier. So i created a new wallet, verified the seed and password, and selected the first receive address from there for my helix lite transaction to be received. I then sent through my payment to helix lite and waited for it to be processed. 

However, this is where I got the problem. I had a bug on my computer that meant I had to uninstall then reinstall electrum. The first wallet that I sent from had all my transaction history and addresses. Unfortunately the new wallet did not have the receiving Payment Address that I had used to withdraw from helix lite and so I no longer have access to this wallet and am going crazy. There have been 8 confirmations but I have nothing and don't know how to get it back. This is not a lot of money for many of you but it is all my bitcoin that I have saved for a long time and I don't know how to get it back and in truth don't think I can ever get it back. 

Any help would be so great!! Surely if this was a wallet address in my electrum and I restored the wallet with the seed less than 30 minutes later when I re-installed there is some way that this address can be re-associated with my wallet?! I'm having a breakdown....!

**Comment by ecdsa** [comment]
do you have both seeds?
if you don't have the seed that generated the payment address, there's no way to recover the coins.
