### ISSUE TITLE
allow client daemon to be launched in the foreground

### ISSUE THREAD

**Issue by abuisine** [spesmilo/electrum#1873]
Looking quickly at the code (maybe too quickly :)  ) I do not see any way to launch the daemon in the foreground from the command line.

Context : I would like to spawn the daemon on a separate docker container and use JSON RPC only from another PHP container

**Comment by ecdsa** [comment]
"electrum daemon start"

**Comment by abuisine** [comment]
Sorry if I was not clear but I meant foreground as "not detaching",
today `electrum daemon start` launch it in the background

**Comment by abuisine** [comment]
`electrum daemon start | cat` does the job but I was wondering if any command line flag would be considered

**Comment by ecdsa** [comment]
sorry, I read 'background'.
I never considered that... why do you need it?

**Comment by abuisine** [comment]
Pretty simple, I am packaging electrum in a docker container.
Docker basically attach to one process and provide logging based on stdout
/ stderr as well as restart when process stops, etc ...

I then connect from one other container with php code.

Side note: It is even better if there is no fork as we stick to one process
only in the container.

**Comment by abuisine** [comment]
Ping ? :)

**Comment by ecdsa** [comment]
so the sytax is `electrum daemon` with no extra argument
