### ISSUE TITLE
All translations are not updated.

### ISSUE THREAD

**Issue by kevlarsefirot** [spesmilo/electrum#1875]
https://bitcointalk.org/index.php?topic=1555887.msg15680220#msg15680220

The problem remains...

@rdymac @ecdsa @dabura667

**Comment by dabura667** [comment]
1. Do all the strings have the gettext underscore around them?
2. Is the pot file reflecting the most recent translations on crowdin?
3. Is the crowdin project built?

@ecdsa just did 3, so either 1 or 2...

**Comment by ecdsa** [comment]
there was an error in app.fil, that caused the script to break
it should work now.

**Comment by ecdsa** [comment]
there's another issue, new strings are not pushed to crowdin
