### ISSUE TITLE
[Feature Request] Creating a Multisignature Wallet using Hardware Wallets as Co-Signers

### ISSUE THREAD

**Issue by JaredCClark** [spesmilo/electrum#1879]
Currently Electrum supports all three major hardware wallets (Trezor, Keepkey, and Ledger), however upon creating a new wallet, the option to create a hardware wallet is separate from the option to create a multisignature wallet.

When clicking "create multisignature wallet", this results in Electrum automatically creating one of the keys, and does not give users any way to use hardware devices to create the keys.  Clicking "create hardware wallet" only enables the user to create a standard wallet using the device.

Allowing for hardware wallet input when creating multisignature wallets will expand Electrum's features and give its users more flexibility and security.

Thank you for everything you do!

**Comment by ecdsa** [comment]
this will be supported soon.
in the meantime, you can use this workaround: 
1. create a watching-only multisig wallet, with the xpub corresponding to your trezor wallet.
2. create an unsigned tx with this wallet, save it.
3, open your trezor wallet, load the tx, sign it.

**Comment by JaredCClark** [comment]
That's great, thank you! I look forward to it

**Comment by ecdsa** [comment]
this is now possible if you check out the 'dev' branch.

**Comment by gits7r** [comment]
I find this feature useful as well.

**Comment by ecdsa** [comment]
the dev branch should be merged this week

**Comment by ecdsa** [comment]
dev branch merged in 1159f85e053d14cf931f5b32444bda071860619c
