### ISSUE TITLE
Default wallet (trezor linked) cannot pair with trezor, but other wallets pair with the device no problem.  

### ISSUE THREAD

**Issue by Benc93** [spesmilo/electrum#1883]
Default wallet (trezor linked) cannot pair with trezor, but other wallets pair with the device no problem.

My Trezor is PIN protected, but the default wallet I've set up cannot pair with the Trezor device, even when the correct PIN is entered as a prompt to sending bitcoins. 

I'm pretty sure I've therefore lost any coins sent to addresses on that wallet, but wanted to make sure I've definately screwed up, and I'm not missing something obvious, or that this is a real fault with the software (doubtful) 

![image](https://cloud.githubusercontent.com/assets/9297921/17398297/f9fd0ede-5a33-11e6-90c2-dee32de39a76.png)

**Comment by ecdsa** [comment]
make sure your trezor firmware is up to date

**Comment by Benc93** [comment]
Yes, it's Firmware 1.3.6. 

I've added more detail in the forum
https://bitcointalk.org/index.php?topic=1575191.new#new

**Comment by ecdsa** [comment]
are you running a binary, or from python sources?
python-trezor has been updated recently, you may want to upgrade that too

**Comment by Benc93** [comment]
I'm running the easy install on Version 2.6.4

**Comment by ecdsa** [comment]
that will only install electrum, not python-trezor

**Comment by Benc93** [comment]
thing is, I can recover the trezor wallets from My trezor into electrum, but the default wallet is not sync'd with it.

**Comment by ecdsa** [comment]
I do not understand your last statement. can you describe your situatino more clearly?
Also, did you upgrade your python-trezor library?

**Comment by Benc93** [comment]
Apologies, these are the full circumstances https://bitcointalk.org/index.php?topic=1575191.new#new

I'll update that library once I've worked out how, not sure it's related to what I've done but I'm willing to try anything.

**Comment by ecdsa** [comment]
ok, closing. thanks for the notification.
