### ISSUE TITLE
Error after receipt of payment

### ISSUE THREAD

**Issue by IvanKovBy** [spesmilo/electrum#1884]
I get an error after receipt of payment when I run a console command - `electrum getaddressbalance address`

```
`Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 371, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 830, in synchronous_get | BaseException: Server did not answer')
```

PLease help me.

**Comment by ecdsa** [comment]
this is not related to receiving a payment. the server did not answer to your request.

**Comment by osminogin** [comment]
Also, get similar error but with ``getaddresshistory``. I get a request via notify from electrum and then make a request ``getaddresshistory`` back to electrum JSON RPC after some timeout this error returns.

Do I understand correctly that the electrum (including JSON RPC) works in one single thread and all operations it is blocked?

**Comment by bios-ben** [comment]
I had the same problem and restarted the daemon then it started working again. I don't know how to help debug besides mentioning the fact that I had two wallets running on daemons at the same time and status would return a list of them. Since I've restarted it there's now only one daemon and one wallet going and it's working.

**Comment by ecdsa** [comment]
@bios-ben wht is your OS ?

**Comment by bios-ben** [comment]
This is running on Ubuntu Server 16.04.1 LTS

**Comment by bios-ben** [comment]
Update: I misread the error due to skimming, the end of my exception is:
BaseException: \'Node\' object has no attribute \'__getitem__\'

**Comment by shaman** [comment]
The same problem.

Electrum 2.6.4
Debian Jessie

**Comment by ecdsa** [comment]
the same problem as who? there are two separate problems described here...

**Comment by shaman** [comment]
Forgot to say, it means topic starter's issue. 

I have following output after some time after daemon running:

```
electrum addrequest 1 -m 'test' --force
Traceback (most recent call last):
  File "/usr/bin/electrum", line 371, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 225, in _request
    check_for_errors(response)
  File "/usr/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 529, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/lib/python2.7/dist-packages/electrum/util.py
```

**Comment by bauerj** [comment]
If you also got the "Server did not answer" error (Your traceback seems to be truncated), this is not an error. There are probably either connectivity or server issues.

If you can rule out both options (e.g. by choosing a different server and checking that your network connection is stable), please reopen.
