### ISSUE TITLE
Cosigner Pool Fails to send transaction to cosigner

### ISSUE THREAD

**Issue by cosinepool** [spesmilo/electrum#1886]
Electrum 2.6.4 Mac cosigner pool plug-in does not work for multis 2-2 wallet. I honestly don't know anything about coding or tech back end of this software. I am just a frustrated user who spent the morning trying to find a fix in the forums. I could only find one other person who has posted about this pb but they have yet to receive a response.

https://bitcointalk.org/index.php?topic=1406751.0

In the above post it is suggested that only some servers support the cosigner pool plug-in.  

Here are my questions: why? if so, which ones?  c'mon guys! this is such a great feature!

**Comment by ecdsa** [comment]
it's currently down, although it was still up when you posted, so that might not be your issue

**Comment by ecdsa** [comment]
fixed in e18e323c4579198a8910bc697a62fc2e0cec7ebb

**Comment by johnvamo** [comment]
Hello,

I have the same error: Cosigner Pool Fails to send transaction to cosigner.
Both wallets have activated the plugin Cosigner Pool.
I am using version 2.9.2...Any advise?


Thanks for the help.
