### ISSUE TITLE
Incorrect Balance in Electrum Wallet HELP PLEASE 

### ISSUE THREAD

**Issue by JACKTHEINBOX234433** [spesmilo/electrum#1890]
Hello,

I sent 0.10003595 BTC from Circle Pay to my Electrum Wallet. That is the only transaction I ever made, since I am new to Electrum, and my current balance says 100.03595 mBTC which is incorrect. When I click on it's details and go to the Block explorer page it shows the correct value of the transaction of 0.10003595 BTC on that page. I also have the receipt from the Circle Pay app. Can this be a possible bug? 

![screen shot 2016-08-08 at 9 54 37 am](https://cloud.githubusercontent.com/assets/20910133/17488453/5b6006b4-5d4e-11e6-96b3-07a46320a042.png)
![screen shot 2016-08-08 at 9 55 12 am](https://cloud.githubusercontent.com/assets/20910133/17488452/5b5e82d0-5d4e-11e6-9583-2ecc2d8e28ed.png)
![screen shot 2016-08-08 at 9 55 53 am](https://cloud.githubusercontent.com/assets/20910133/17488451/5b5ac1fe-5d4e-11e6-924c-2d6f28139a00.png)

**Comment by ecdsa** [comment]
1000mBTC = 1BTC
welcome to the metric system.
