### ISSUE TITLE
High Resolution Compatibility 

### ISSUE THREAD

**Issue by mohanx** [spesmilo/electrum#1891]
I wish the program would scale to high resolution screens. Tried it on both Linux and Windows and the setting up was very difficult. Lines very small, can't resize the frame, missed some sentences. 

Thank you for work. I love it anyways.

**Comment by ulrichard** [comment]
On my new XPS13DE with 4K display I have a 1.75 scaling. 
Some electrum dialogs are ok, some don't look so nice, and a few are barely usable.

**Comment by bauerj** [comment]
This is now being tracked in #1927.
