### ISSUE TITLE
Invisible Window after copying wallet to another PC with smaller screen

### ISSUE THREAD

**Issue by TS32423** [spesmilo/electrum#1892]
The wallet file also saves the position of the current window. When you copy the wallet file to another PC with a smaller screen, the window disappaers under some circumstances while opening it. It is open then but not visible.

To avoid this "bug" simply check the screen size of the current PC when opening the wallet. When it is smaller than the positions in the wallet, place the new window in the middle of the screen.

**Comment by oatesch** [comment]
I can't replicate this change (Ubuntu 16.04). Which OS?

**Comment by TS32423** [comment]
Both Windows 10, 22 inch and 15 inch screen

I have a 22 inch screen at work. When I place the Electrum Window on
this screen to the most right position and close Electrum and the
positions are stored in the wallet like this:

"winpos-qt": [
        1184,
        335,
        495,
        340
    ]

When I copy this wallet to my PC at Home (old 15 inch monitor) and open
Electrum, the window is invisible. The solution that I have is to edit
the wallet file with an editor and replace the 1184 with 184 for
example, like this..

"winpos-qt": [
        184,
        335,
        495,
        340
    ]

Then the window opens and everything is OK.

Am 12.08.2016 um 11:50 schrieb oatesch:

**Comment by ecdsa** [comment]
that should fix it
