### ISSUE TITLE
Support for Ledger Nano S

### ISSUE THREAD

**Issue by Macthetrix** [spesmilo/electrum#1897]
I just tried to setup electrum with the Ledger Nano S but it does not recognize it.

exception no dongle found

**Comment by ivorpad** [comment]
@Macthetrix https://www.reddit.com/r/Bitcoin/comments/4ycmpp/can_i_manage_ledger_nano_s_with_electrum/d6mmxgr

**Comment by ecdsa** [comment]
merged
