### ISSUE TITLE
Maidsafe coins sent to Omni then sent to Electrum 2fa addresses, cannot be sent back to Omni

### ISSUE THREAD

**Issue by MontyKirkman** [spesmilo/electrum#1900]
I used 2fa with Electrum thinking it would help with security, but it's turned into a nightmare. I've been trying to get my MAID and Synereo off Omni for 14 hours straight but with no luck.

I sent MAID coins from Exchange to Omni then on sent them to Electrum 2fa account.  When returning them back to Omini...major problems bit me in the backside.

This address has all my MAID and Synero starts with 3JAX9xkuAc93............ (created in electrum 2FA)
When I enter my private key to Omni for the above address I get this address 1KNzUe8RddBG3kTgi9rrfqmVgCNLokLQZK which doesn't show my MAID and Synereo
When I put 3JAX9xkuAc93...............in as a watch address I can see it all sitting there but I can't do anything with it.

This is a major bug for anyone that wants to use 2fa (multisig) when storing Omnilayer coins.  It's a serious 'gotcha' and users need to be warned about it somehow.

I've reached out to Lucas Ryan from TrustedCoin and this is what he said.

Reply from Lucas Ryan:
The short answer is that (as you suspected) this has to do with multisig. Electrum 2FA wallets use 2-of-3 multisig addresses (where Trustedcoin has the first key, the second key is stored in your wallet and the third key is recoverable from your seed). 
OmniWallet does not appear to support multisig. However, as far as I can tell (although I haven't read the entire OmniLayer spec) the OmniLayer protocol does support multisig so it is in theory possible to create wallet software that will allow you to move your OmniLayer coins. Or a programmer familiar with the OmniLayer software could attempt to write a one-off script that manually constructs and signs a transaction to transfer your coins.
I suggest you contact the omniwallet developers (or post on omnilayer-related forums for help). 
One additional note: If you recover your Electrum 2FA wallet from it's seed and then attempt to view the private key associated with an address you will be shown 2 private keys instead of 1. Any software written to transfer your coins will need these 2 keys.

I've also reached out to Adam from Omni and this is his response:
Hey Monty, 
That is very weird indeed. I think there are certain Electrum wallets that do a weird Multisig type of wallet where they only give you 1 of the address/private keys (which won't work with Omniwallet natively). 
Can you provide the address: 
As it exists in Electrum 
As Omniwallet shows it after you import it 
And the type of wallet you created in electrum?
If you take the private key (or rather try with any other private key from that wallet that has no balance) and try to import those in Omniwallet or any other wallet/website do they produce the same address as what is displayed in your electrum wallet?
While your funds are secure it may require some additional effort and the use of a few different tools to create the tx necessary to move them out of Electrum. But we will try our best to help you through it.
________________________________________
Ticket #193 Created by Monty Kirkman

**Comment by ecdsa** [comment]
This is out of scope for Electrum. 
you should ask Omni developers for help.
btw, our 2FA wallets give you two private keys, but only one is on your computer. if you want two, you have to restore the wallet from its seed.

**Comment by MontyKirkman** [comment]
Ok thanks
