### ISSUE TITLE
Client on OpenSuse Leap does not start

### ISSUE THREAD

**Issue by obel1x** [spesmilo/electrum#1903]
Installed as written on site - program is not starting.
What happened:
xxxx@pcwohnfest:~> su
Passwort:
pcwohnfest:/home/obel1x # pip install https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz
Collecting https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz
  Downloading https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz (5.7MB)
    100% |████████████████████████████████| 5.7MB 146kB/s 
Collecting slowaes>=0.1a1 (from Electrum==2.6.4)
  Downloading slowaes-0.1a1.tar.gz
Collecting ecdsa>=0.9 (from Electrum==2.6.4)
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)
    100% |████████████████████████████████| 90kB 2.5MB/s 
Collecting pbkdf2 (from Electrum==2.6.4)
  Downloading pbkdf2-1.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3.4/site-packages (from Electrum==2.6.4)
Collecting qrcode (from Electrum==2.6.4)
  Downloading qrcode-5.3-py2.py3-none-any.whl
Collecting protobuf (from Electrum==2.6.4)
  Downloading protobuf-3.0.0-py2.py3-none-any.whl (342kB)
    100% |████████████████████████████████| 344kB 1.2MB/s 
Collecting dnspython (from Electrum==2.6.4)                                                                                                                                      
  Downloading dnspython-1.14.0.zip (251kB)                                                                                                                                       
    100% |████████████████████████████████| 253kB 844kB/s 
Collecting jsonrpclib (from Electrum==2.6.4)                                                                                                                                     
  Downloading jsonrpclib-0.1.7.tar.gz                                                                                                                                            
Collecting six (from qrcode->Electrum==2.6.4)                                                                                                                                    
  Downloading six-1.10.0-py2.py3-none-any.whl                                                                                                                                    
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3.4/site-packages (from protobuf->Electrum==2.6.4)                                        
Installing collected packages: slowaes, ecdsa, pbkdf2, six, qrcode, protobuf, dnspython, jsonrpclib, Electrum                                                                    
  Running setup.py install for slowaes                                                                                                                                           
  Running setup.py install for pbkdf2                                                                                                                                            
  Running setup.py install for dnspython                                                                                                                                         
  Running setup.py install for jsonrpclib                                                                                                                                        
  Running setup.py install for Electrum                                                                                                                                          
Successfully installed Electrum-2.6.4 dnspython-1.14.0 ecdsa-0.13 jsonrpclib-0.1.7 pbkdf2-1.3 protobuf-3.0.0 qrcode-5.3 six-1.10.0 slowaes-0.1a1                                 
You are using pip version 7.1.2, however version 8.1.2 is available.                                                                                                             
You should consider upgrading via the 'pip install --upgrade pip' command.                                                                                                       
pcwohnfest:/home/obel1x # pip install --upgrade pip                                                                                                                              
Collecting pip                                                                                                                                                                   
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)                                                                                                                             
    100% |████████████████████████████████| 1.2MB 398kB/s 
Installing collected packages: pip                                                                                                                                               
  Found existing installation: pip 7.1.2                                                                                                                                         
    Uninstalling pip-7.1.2:                                                                                                                                                      
      Successfully uninstalled pip-7.1.2                                                                                                                                         
Successfully installed pip-8.1.2                                                                                                                                                 
pcwohnfest:/home/obel1x # exit
obel1x@pcwohnfest:~> electrum                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                               
  File "/usr/bin/electrum", line 75, in <module>                                                                                                                                 
    check_imports()
  File "/usr/bin/electrum", line 49, in check_imports
    import aes
  File "/usr/lib/python3.4/site-packages/aes.py", line 643
    raise ValueError, emsg % keysize
                    ^
SyntaxError: invalid syntax
obel1x@pcwohnfest:~>

**Comment by obel1x** [comment]
btw...
obel1x@pcwohnfest:~> uname -a
Linux pcwohnfest 4.1.27-27-default #1 SMP PREEMPT Fri Jul 15 12:46:41 UTC 2016 (84ae57e) x86_64 x86_64 x86_64 GNU/Linux

**Comment by ecdsa** [comment]
use python2
