### ISSUE TITLE
Bitcoin missing

### ISSUE THREAD

**Issue by stevens-apps** [spesmilo/electrum#1904]
Transferred ~0.17 Bitcoin between Electrum wallets and must have closed the application before the transaction posted to the blockchain, now the Bitcoin is nowhere to be seen. Definitely shouldn't have closed the application as soon as I did so i don't fault anyone but myself. Would be great if this could be prevented in the future though.

**Comment by ecdsa** [comment]
that does not make sense.
either the transaction is in the blochchain, or it is not.

**Comment by stevens-apps** [comment]
My thoughts exactly. It's like the Bitcoin was never in my wallet which is extremely weird. No sign of it in the blockchain for either wallet and even previous transactions show an incorrect wallet total as if the Bitcoin was never there even though I know for a fact that it was

**Comment by ecdsa** [comment]
are you sure you are looking at the right wallet?
does the wallet you call "my wallet" have the right seed?

**Comment by stevens-apps** [comment]
Yes I'm looking at the correct wallet. Other than the wallet total for each transaction the history is the same. There is a specific transaction that I know the wallet total was about 0.19 Bitcoin which is what I was basing the transfer of the 0.17 Bitcoin off of but now that same transaction says the wallet total was 0.02 Bitcoin instead of the 0.19 that it used to be and previous transactions reflect the missing 0.17 Bitcoin.

**Comment by ecdsa** [comment]
that does not make sense, and your report is too vague to be investigated. if you want someone to have a look, please post the master public key of both wallets, and the ID of the transaction

**Comment by David2201** [comment]
No I have to agree with Steven.
I had a balance of more that 0.202 with transactions coming into my wallet address and also transactions going out of my wallet address.

My balance is reporting as it was on the 14-08-2016 with every transaction after that missing.
![electrum](https://cloud.githubusercontent.com/assets/20452576/18030727/1b28e18a-6d05-11e6-9c2c-30e4c8e7ba07.PNG)

I have been generating bitcoins, and all of the new ones I cannot see.

I am running Electrum 2.6.4.

I had an issue the other day when I went to transfer some bitcoins and I got errors from the main servers. But eventually the transfer went through 24 hours after I transferred the coins.

My issues started when the 46.166.165.18 server started lagging. At present it is behind by 1927 Blocks.

**Comment by ecdsa** [comment]
@David2201 if the server is lagging then it's normal that your history is not complete. use another server.

**Comment by David2201** [comment]
Thanks, I can see the transactions are all there from blockchain.info

The server VPS.hsmiths.com is green and it shows my correct balance from the 28/08.

Just an FYI, I don't know if this is in your control or it if helps but:
- 46.166.165.18 is lagging (1969 blocks) and shows my balance from the 14/08
- ELEC.Pieh0.co.uk is green but shows my balance from the 14/08
- ELECTRUM.top-master.com is green but shows my balance from the 14/08
- Electrum.Online is green but shows my balance from the 14/08
- Electrum.hsmiths.com is green but shows my balance from the 14/08
- JElectrum.jdubya.info is green but shows my balance from the 14/08

Thanks for your help.

**Comment by ecdsa** [comment]
@David2201 if it is 'green' then it should display the corect balance.
can you post the ID of a transaction that you don't see?

**Comment by David2201** [comment]
This is the transaction on the 14/08. Anything after this I cannot see depending on which server I connect to.
4eada37f0e454f4368ae23bbbe4b930630c9abc24aa2312bdc4934d26ba77833

This is an example of a receiving transaction that I cannot see (21/08): 11ca2b926dac1a10c43447ce39649de4cb2e8876e35afcb109e2c4e4de2f4f0a

This is an example of a sending transaction I cannot see (22/08):
41f2e5c4c380ae3a984303ef340a61f4f4e658f11eb476e83e5017cf2244a809

Hope this helps.

**Comment by ecdsa** [comment]
@David2201 does it get fixed it you restart Electrum?

**Comment by leangjia** [comment]
@David2201 does it get fixed it you restart Electrum?

**Comment by ecdsa** [comment]
no answers, closing.
