### ISSUE TITLE
Export history silently fails with NameError: global name 'confirmations' is not defined

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#1906]
Opened an old wallet containing imported keys.
Went to Wallet > Export History > Export.
No output file is generated.

This traceback appears in the verbose output:

Traceback (most recent call last):
 File "C:\Users\x\electrum\gui\qt\main_window.py", line 2109, in export_history_dialog
    self.do_export_history(self.wallet, filename, csv_button.isChecked())
  File "C:\Users\x\electrum\gui\qt\main_window.py", line 2142, in do_export_history
    lines.append([tx_hash, label, confirmations, value_string, time_string])
NameError: global name 'confirmations' is not defined

This happened with the git-head version.

**Comment by ecdsa** [comment]
is that with git head? old wallets with imported keys are supposed to be split

**Comment by shsmith** [comment]
Yes, it was git head.  When I first opened the wallet it split it.  Then I opened the .imported part and tried to export the history.

**Comment by ecdsa** [comment]
ack

**Comment by shsmith** [comment]
fix confirmed. thanks!
