### ISSUE TITLE
Slight usability issue repeated prompts to split wallet causing infinite user-involved loop

### ISSUE THREAD

**Issue by fortran77** [spesmilo/electrum#1908]
In the latest master branch, which identifies itself as 2.7, the following sequence will cause an infinite user-involved loop.

Suppose the last wallet used was wallet X, used by electrum 2.6, and it contains multiple accounts not supported by electrum 2.7.

**LOOP:**

When the user invokes electrum 2.7 as `electrum` without any arguments, it asks for permission to split wallet X into multiple files. The user happily answers Yes. Then electrum 2.7 asks for permission to delete the old wallet file. The user,

- wanting to be generally cautious,
- wanting to preserve the option of using electrum 2.6 in case 2.7 turns out to have some serious bug,
- and figuring that deletion is not mandatory since the old wallet won't interfere in any way with the new split wallets,

answers No.

At this point electrum 2.7 exits, still leaving wallet X as the wallet that was the one last in use. The user notices that electrum has exited and decides to run it again.

**goto LOOP**

**Comment by ecdsa** [comment]
ok, let's rename the old wallet then

**Comment by ecdsa** [comment]
won't fix. I think it's better to do nothing.
