### ISSUE TITLE
Command line 'notify' .

### ISSUE THREAD

**Issue by angrypie** [spesmilo/electrum#1915]
Can someone explain how to 'notify' command exactly work?  I do like this:
`electrum notify <some_address> localhost/notify.php`
<some_address> it is adress that i got using this command:
`electrum addrequest 0.0001` 
All i get is empty request  when 'electrum notify ...' executed and nothing else than.
I guess i'm do something wrong, but i don't even know what should happen and what order.

**Comment by MarcGodard** [comment]
Have you figured this out? I know this is old, but I am also looking into this.

**Comment by angrypie** [comment]
I didn't figure it out  but found workaround for a while (now i'm not using electrum).
Method receive_tx_callback in lib/wallet.py executes when address in wallet receives some funds, so your can work with this.

**Comment by dabura667** [comment]
notify tells the electrum server to send you a callback.

localhost doesn't work unless you have an electrum server running locally and connect your electrum client to your local electrum server.

**Comment by ecdsa** [comment]
@dabura667 no, not the electrum server, but the electrum daemon.
@angrypie did you start the electrum daemon? (I did not investigate the issue further)

**Comment by angrypie** [comment]
@ecdsa yes, it was started and it was 2.6.4 version. Since then, i have not tried.

**Comment by MarcGodard** [comment]
What format do you make the command???

Is this how you do it?

```electrum notify 1ADDRESS1 "https://yoursite.com/ipn/"```

**Comment by ecdsa** [comment]
@MarcGodard yes. see the help.

**Comment by MarcGodard** [comment]
@ecdsa Well it isn't working for me.

I have tried and tried. Does the URL need to be url encoded?

**Comment by MarcGodard** [comment]
@ecdsa If you are talking about the documentation, it says nothing about notify.

http://docs.electrum.org/en/latest/search.html?q=notify&check_keywords=yes&area=default

So if you know where this help is, please let me know, because the electrum help also doesn't say.

```
usage: electrum notify [-h] [-v] [-D ELECTRUM_PATH] [-P] [-w WALLET_PATH]
                       [--testnet] [--segwit] [--nolnet]
                       address URL

Watch an address. Everytime the address changes, a http POST is sent to the
URL.

positional arguments:
  address               Bitcoin address
  URL

optional arguments:
  -h, --help            show this help message and exit

global options:
  -v, --verbose         Show debugging information
  -D ELECTRUM_PATH, --dir ELECTRUM_PATH
                        electrum directory
  -P, --portable        Use local 'electrum_data' directory
  -w WALLET_PATH, --wallet WALLET_PATH
                        wallet path
  --testnet             Use Testnet
  --segwit              The Wizard will create Segwit seed phrases (Testnet
                        only).
  --nolnet              Use Nolnet
```

**Comment by dabura667** [comment]
Are you using Python3 by chance?

**Comment by MarcGodard** [comment]
@dabura667 I have both installed, but it is using 2.7

I did try it on another of my machines that only has 2.7 installed and it still didn't work.

**Comment by ValtteriL** [comment]
Is there a way to unsubscribe from an address (stop receiving callbacks for an address)? It seems like a memory leak if you can only subscribe to them.

Also what are the changes notify will fire the callback on? Something received? Transaction confirmed first/second/xth time?

**Comment by ecdsa** [comment]
notify is called everytie the history of an address changes.
only the first confirmation affects history

**Comment by sime** [comment]
Thanks for the note that first confirmation affects history.

I'm experimenting with `notify` on testnet and watching my addresses and the testnet faucet address:

```bash
$  electrum notify 2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF https://requestb.in/zyjh83zy --testnet
$  electrum notify mnXN6umT4JcdsSwkHbjdpanWp2vMbXv7Py https://requestb.in/zyjh83zy --testnet
```

Though nothing is reaching the `requestb.in` address. Any reason why `notify` wouldn't work on `testnet` ?

**Comment by bauerj** [comment]
@sime Did it work on mainnet?

**Comment by sime** [comment]
Never tried mainnet

**Comment by SomberNight** [comment]
Does the command work now?
There was e.g. this commit recently https://github.com/spesmilo/electrum/commit/d808bf057e21ef728e71f926523ad58056f8c526

**Comment by vzelenko** [comment]
The callback is working in master branch, just not on 3.0.6 tag

**Comment by SomberNight** [comment]
@vzelenko Status is defined here: https://github.com/kyuupichan/electrumx/blob/master/docs/PROTOCOL.rst#blockchainscripthashsubscribe

> To calculate the status of an address, order confirmed transactions touching the address by height (and position in the block if there are more than one in a block). Form a string that is the concatenation of strings 'tx_hash:height:' for each transaction in order. tx_hash is the transaction hash in hexadecimal, height the height of the block it is in. Next, with mempool transactions in any order, append a string that is the same, but where height is -1 if the transaction has at least one unconfirmed input, and 0 if all inputs are confirmed. The status is the sha256 hash of this string expressed as a hexadecimal string.

**Comment by vzelenko** [comment]
@SomberNight - thank you for details.

**Comment by 93Kamuran** [comment]
Hello, I'm using an electrum with my trezor. I have lots of addresses in my wallet and I want to take ınvoices on my website. So I have to notified when one of these addresses has received. Could I use another method except "notify"? (can be like "wallet notify" in bitcoin-core).

**Comment by canihojr** [comment]
the comands are how they said before, on the callback you need to recive the $_GET["WALLET"] and after do wharever you want with this.... (save on database for example), the notify should rise 2 times, one with somethings its coming and other one as soon gets the first confirmation.
