### ISSUE TITLE
fix of hid-api on mac with new Trezor firmware

### ISSUE THREAD

**Issue by runn1ng** [spesmilo/electrum#1923]
Hello,

we made a fix of hid-api in order for Trezor with new firmware to work on mac with python

https://pypi.python.org/pypi/hidapi/0.7.99.post18

(we are using our fork of hid-api C library, since the PR is stuck on signal11 github now - https://github.com/signal11/hidapi/pull/288 , https://github.com/signal11/hidapi/pull/40 )

Anyway, I don't understand electrum mac build system well enough, so I am not sure what is needed to be done so that electrum mac binary is using new hidapi library (trezor plugin is using python-trezor, and that has hidapi as a dependency).

**Comment by ecdsa** [comment]
I think nothing else needs to be done.
if you are building electrum binaries, you only need to make sure you use the right library.
I will create binaries today and test it.

**Comment by ecdsa** [comment]
can you check the 2.7 binaries to see if it's fixed for you? 
http://download.electrum.org/2.7.0/
they work for me.

**Comment by xbach** [comment]
Imported Trezor into 2.7 without an issue, all transactions were displayed, but I didn't try to send a transaction

**Comment by ecdsa** [comment]
ok
