### ISSUE TITLE
bug: electrum unusable on windows 10 with high-dpi display

### ISSUE THREAD

**Issue by jkokorian** [spesmilo/electrum#1927]
I have an HP spectre 360 laptop with a high-dpi display. Unfortunatly, electrum is completely unusable on it. The initial dialog looks like this:

![image](https://cloud.githubusercontent.com/assets/6113878/18505837/5ffcf456-7a69-11e6-9e17-6290b3e7cd29.png)

I can click next, which gives me a similarly tiny window with a new seed phrase:

![image](https://cloud.githubusercontent.com/assets/6113878/18505841/686b77c0-7a69-11e6-8293-b09f02aa6655.png)

Eventually, I end up at the main screen:

![image](https://cloud.githubusercontent.com/assets/6113878/18505857/79f4ae4e-7a69-11e6-8ba4-2fa584587885.png)

I have no way to restore my original seed phrase. I've seen more Qt applications with high-dpi scaling issues, including TeXStudio, but at least that one is still usable.

Hopefully this can be fixed!

**Comment by jkokorian** [comment]
The screenshots appear are all blown-up here. On my screen all text is sized normally, as are dialog buttons, the title bar, and the menu bar. Everything else is way too small.

**Comment by jkokorian** [comment]
When I run electrum directly from python I have the option to resize the dialogs. When I make them slightly larger, everything suddenly 'pops into place' and looks completely normal! Simply making the dialogs a bit larger might solve the issue. The toolbar buttons in the main screen are still very small, but I can live with that for the moment.

**Comment by oatesch** [comment]
Could be fixed if qt5 used rather than qt4 - provides high dpi support.

Does this fix work?
RC electrum-2.6.4.exe -> Properties -> Compatability -> Disable display scaling on high DPI settings

Seems to be a repeat of #1891

**Comment by jkokorian** [comment]
that doesn't solve it, checking or unchecking the box makes no difference.

**Comment by ecdsa** [comment]
note: http://doc.qt.io/qt-5/highdpi.html

**Comment by stax76** [comment]
there are two critical and one cosmetic issues on the send tab on 288 DPI, pay to and amount text boxes are too small, this is critical, icons are too small, this is cosmetic.

![unbenannt](https://cloud.githubusercontent.com/assets/11410540/23540713/37501682-ffe3-11e6-802d-7b2dc0b74c7c.png)

**Comment by ecdsa** [comment]
note: I don't have a high DPI display so I am not able to test a fix.

**Comment by stax76** [comment]
Thanks for the quick response. You can test different environments with vmware (player is free), I used it this week working on staxrip UI code, what I did is generate icons at runtime with segeo mdl2 assets and font awesome, it worked out really well.

https://s29.postimg.org/5ghf7voaf/Screenshot_46.png

**Comment by bauerj** [comment]
@stax76 Can you confirm if this issue is resolved with Electrum 3? We use Qt5 now.

**Comment by stax76** [comment]
@bauerj

It's fine now, one small issue left is the amount text box on the send tab is not wide enough, right now only 3-4 characters fit into it.

Vielen Dank!

**Comment by bauerj** [comment]
That's great to hear! Can you post a screenshot of that input box?

**Comment by stax76** [comment]
https://i.imgur.com/Y6J6Nqc.png

**Comment by eliasnaur** [comment]
FWIW, I run into similar problems with text overflowing edit fields, buttons, status bar etc. because I run with

gsettings set org.gnome.desktop.interface text-scaling-factor 1.5

to make text easier to read on my 4k monitor.

resetting the text-scaling-factor 1 makes the problems go away.

I'm on Fedora 27.
