### ISSUE TITLE
Trezor OsX not connecting

### ISSUE THREAD

**Issue by rube563** [spesmilo/electrum#1929]
When I try to connect my trezor the following message pop-up:

Two devices with the same path and S/N found. This is Mac, right? :-/

I have no clue how to fix this problem, everything was working fine until last time I used.
Os X El Capitan - version:10.11.05
Trezor Firmware 1.4.0

**Comment by ecdsa** [comment]
is this with git head?

**Comment by rube563** [comment]
I had contacted the Trezor Team and I am forwarding their message:

> 
Thank you for contacting SatoshiLabs customer support. I'm happy to help you.

The Issue has been reported to Electrum-Dash developers, we fixed it for them and now it's waiting to be implemented into the Electrum-Dash wallet. You can see the issue reported here: https://github.com/dashpay/electrum-dash/issues/81

There are multiple options how to proceed further:

1] wait until it gets implemented by the Electrum-Dash developers (you can try to push them to do it sooner)
2] run the Electrum-Dash in virtual environment with different operating system (Windows or Linux) on your computer
3] run the Electrum-Dash on different computer with Windows or Linux

If you try the option with Windows, you need to use this older version of Electrum-DASH wallet - https://dashpay.atlassian.net/builds/browse/ELMW-DEV-117/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

There is one more option, which we do not recommend unless you are very experienced user or developer
1. download the old firmware here: https://github.com/trezor/webwallet-data/tree/master/firmware
2. download and install the python TREZOR: https://github.com/trezor/python-trezor
3. install the old version of firmware using Python TREZOR
4. it's possible the firmware downgrade will wipe your device, in such case you have to recover your TREZOR seed into the device

Unfortunately, the implementation into Electrum-Dash is currently out of our hands and we are not able to do anything about it. Hope you will understand.

Best regards,
Ben
Customer Support

**Comment by koalalorenzo** [comment]
I am having the same problem here. Is it going to be fixed?

**Comment by ecdsa** [comment]
@koalalorenzo with the latest version of electrum? for BTC or Dash?

**Comment by koalalorenzo** [comment]
Dash, at the moment. The BTC version is saying that I have 2 devices available.

**Comment by ecdsa** [comment]
please do not report Dash issues here. we do not support Dash.

**Comment by koalalorenzo** [comment]
Sorry then!
