### ISSUE TITLE
electrum crashes with socket.gaierror on Linux

### ISSUE THREAD

**Issue by mateuszviste** [spesmilo/electrum#1932]
Hi, I'm running (well, trying to run) electrum 2.6.4 from sources on my OpenSUSE 42.1 system. I fetched the electrum-2.6.4.tar.gz achive, unpacked it, and naively launched the "electrum" executable.

All I got in return was this:

> mateusz@mateusz:~/Downloads/Electrum-2.6.4> ./electrum 
> Error: Cannot read config file. /home/mateusz/.electrum
> Traceback (most recent call last):
>   File "./electrum", line 330, in <module>
>     d = daemon.Daemon(config, fd)
>   File "/home/mateusz/Downloads/Electrum-2.6.4/lib/daemon.py", line 120, in __init__
>     requestHandler=RequestHandler)
>   File "/home/mateusz/Downloads/Electrum-2.6.4/packages/jsonrpclib/SimpleJSONRPCServer.py", line 211, in __init__
>     bind_and_activate)
>   File "/usr/lib64/python2.7/SocketServer.py", line 417, in __init__
>     self.server_bind()
>   File "/usr/lib64/python2.7/SocketServer.py", line 431, in server_bind
>     self.socket.bind(self.server_address)
>   File "/usr/lib64/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)                                                      
> socket.gaierror: [Errno -2] Name or service not known                                           
> mateusz@mateusz:~/Downloads/Electrum-2.6.4>

Running "python ./electrum" or "python2 ./electrum" leads to the exact same output, while "python3 ./electrum" ends up with other troubles (presumably because electrum is a python2 application?):

> mateusz@mateusz:~/Downloads/Electrum-2.6.4> python3 electrum
> Traceback (most recent call last):
>   File "electrum", line 75, in <module>
>     check_imports()
>   File "electrum", line 49, in check_imports
>     import aes
>   File "/home/mateusz/Downloads/Electrum-2.6.4/packages/aes.py", line 643
>     raise ValueError, emsg % keysize
>                     ^
> SyntaxError: invalid syntax
> mateusz@mateusz:~/Downloads/Electrum-2.6.4>

Any hints?

**Comment by mateuszviste** [comment]
I straced electrum, and from the strace output (attached) I noticed that it goes wrong around DNS-related operations. Additional context: I run a dnsmasq daemon on my PC for cache. It runs bound to 127.0.0.1, as follows:

> mateusz@mateusz:~> netstat -anup
> Active Internet connections (servers and established)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name   
> udp        0      0 127.0.0.1:53            0.0.0.0:*                           -                   
> mateusz@mateusz:~>

And obviously, my resolv.conf points out to 127.0.0.1.

For a test, I stopped the dnsmasq service and modified my resolv.conf to point to a public DNS server. Now, electrum launches fine. Question is, why would electrum have a problem against a local DNS cache running? Also, this is the kind of errors that it would be nice to present to the user in some humanly readable way, not everyone will jump right away into stracing. Another example of poor error reporting is when no resolution can be made at all (either because there is no networking available at the time, or because of a dns misconfiguration):

> mateusz@mateusz:~/Downloads/Electrum-2.6.4> ./electrum 
> Traceback (most recent call last):
>   File "./electrum", line 330, in <module>
>     d = daemon.Daemon(config, fd)
>   File "/home/mateusz/Downloads/Electrum-2.6.4/lib/daemon.py", line 120, in __init__
>     requestHandler=RequestHandler)
>   File "/home/mateusz/Downloads/Electrum-2.6.4/packages/jsonrpclib/SimpleJSONRPCServer.py", line 211, in __init__
>     bind_and_activate)
>   File "/usr/lib64/python2.7/SocketServer.py", line 417, in __init__
>     self.server_bind()
>   File "/usr/lib64/python2.7/SocketServer.py", line 431, in server_bind
>     self.socket.bind(self.server_address)
>   File "/usr/lib64/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> mateusz@mateusz:~/Downloads/Electrum-2.6.4>

[strace.log.gz](https://github.com/spesmilo/electrum/files/484359/strace.log.gz)

**Comment by ecdsa** [comment]
iirc this was fixed some weeks ago, can you try git head?

**Comment by mateuszviste** [comment]
Hello, I confirm that the problem is not present with current electrum-master. I guess I will use that then waiting for the next formal release :) Thank you.
