### ISSUE TITLE
12 word seed generated instead of 13 words during new wallet creation in version 2.6.4

### ISSUE THREAD

**Issue by mwebb43** [spesmilo/electrum#1939]
I've created some wallets previously, and it always created 13 word seeds.

ISSUE:
Today, Electrum 2.6.4 is generating 12 word seeds for me.   
Sometimes it's 13, sometimes it's 12.

QUESTION:
Isn't the current version of Electrum ( 2.6.4 ) supposed to always create a 13 word seed?

I have changed nothing at all since I've last run the software over a week ago, in fact I've not even updated the machine in any way (disabled ethernet, wifi, etc).

Details:
Ubuntu 14.04.1 LTS initial install - updated to Ubuntu 14.04.5 LTS   
64-bit machine
Installed Electrum 2.6.4
Disabled Wifi, Disabled Ethernet, Disabled Bluetooth
Nothing updated or installed after installing Electrum
Always generated 13 word wallets previously until today

**Comment by ecdsa** [comment]
That's normal. Version 2.6 created seeds that have sometimes 13 words, sometimes 12. 
In 2.7 the number of words is always 12.
