### ISSUE TITLE
Add support for BIP39 Italian wordlist

### ISSUE THREAD

**Issue by HostFat** [spesmilo/electrum#1942]
https://github.com/bitcoin/bips/pull/306

**Comment by ecdsa** [comment]
we currently generate only English seeds, because the Android version does not allow to change the language used in predictive typing.

**Comment by HostFat** [comment]
Is it something that you will be able to fix? Do you think that it need something like a huge change on the android version code?

**Comment by ecdsa** [comment]
not a huge change, but it's not done yet.

**Comment by ecdsa** [comment]
closing this; we will not add non-english wordlists. see #6860
