### ISSUE TITLE
SDL error couldn't load python3.5m on Android app

### ISSUE THREAD

**Issue by Bubblejet** [spesmilo/electrum#1947]
Running Electrum 2.7.0.0 on a Samsung Rugby (SGH-I547) Android version 4.1.2
Kernel version 3.0.31-1371191

When attempting to open the app you get an error message
"SDL Error
An error occurred while trying to start the application. Please try again and/or reinstall.
Error: Couldn't load python3.5m: findLibrary returned null"

Have removed and re-installed app. Same error.

**Comment by ecdsa** [comment]
this bug is caused by kivy.
see https://github.com/kivy/python-for-android/issues/866

**Comment by rdymac** [comment]
I downloaded 2.7.0 APK from the website, it freezes the screen at the Electrum logo/splash, can't even use the Home button to close the app.

Installing 2.7.1 from the Play Store to check if it works better.

**Comment by ecdsa** [comment]
Fixed; the new APK is on Goge Play 2.7.4.0
