### ISSUE TITLE
Bug with max send fee slider interaction after changing amount

### ISSUE THREAD

**Issue by Derek701** [spesmilo/electrum#1948]
Setting max causes amounts to reset to max when adjusting the fee slider after changing amount.

Steps to reproduce:

1. From Send tab, click Max button
2. Change Amount
3. Adjust Fee slider

Result: Amount changes to max amount, adjusted for the new fee
Expected: Only the fee changes, not the custom amount set

**Comment by ecdsa** [comment]
that's expected. you may want to send all your coins and then adjust the fee.

**Comment by ecdsa** [comment]
sorry, I misread, didnt see that you changed the amount. reopening.
