### ISSUE TITLE
Can't send BTC with Ledger HW1 Wallet

### ISSUE THREAD

**Issue by JPUnix** [spesmilo/electrum#1949]
I'm using 2.7.0 under Windows 7 Home Edition with a Ledger HW.1. Whenever I try to send BTC using my HW.1 Wallet I get the error Exception: Invalid Status 6985. I can reproduce the error every time.

**Comment by ecdsa** [comment]
I think @btchip has seen that

**Comment by JPUnix** [comment]
On 10/5/2016 1:01 AM, ThomasV wrote:
> I think @btchip <https://github.com/btchip> has seen that


Awesome! Thanks!

-- 
John Perry
http://www.jpunix.net

**Comment by JPUnix** [comment]
Any word on this?

**Comment by ecdsa** [comment]
note: this user reports that hw1 works for him, for non-multisig transactions: 
https://www.reddit.com/r/Electrum/comments/57389i/failed_to_compile_output_cant_send_tx_from_trezor/d8okp9w

**Comment by JPUnix** [comment]
well this issue seems to have been fixed. Now I will post about another issue.
