### ISSUE TITLE
argparse not consistent

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#1950]
The deseed command line option doesn't work. The error message is "Remove the existing wallet first!". This happens in both 2.6.4 and 2.7.1

**Comment by ecdsa** [comment]
indeed. is there still a use case for that command? I would rather like to remove it

**Comment by AbdussamadA** [comment]
it makes it easy to create watching only wallets. but of course it's your choice to keep it around or not.

**Comment by ecdsa** [comment]
well, if it was broken since the 2.6.4 release and nobody complained, I suppose it's not really used.
if you need to create a watching only wallet from the command line, you can do like this:
```
MPK=$(electrum getmpk)
electrum -w watching_only restore $MPK
```

**Comment by AbdussamadA** [comment]
I'm sure it can be done with grep and cut. But what you've written above won't work for a number of reasons. For one the output of getmpk is json. Second -w usually has to go after commands now.

**Comment by AbdussamadA** [comment]
I guess I'll close this since you've decided to deprecate the deseed command.

**Comment by ecdsa** [comment]
this commit should make it work with pipes: e0ba4a967c112bcd59382fc10ce6accd7a67fce3

```electrum getmpk | electrum -w watching_only restore -```

**Comment by ecdsa** [comment]
are you on OSX ? on linux -w does not have to go after commands.

**Comment by ecdsa** [comment]
and no, the output of getmpk is not json, unless you are using an old version

**Comment by AbdussamadA** [comment]
indeed you are right. these were problems in 2.6.4. my bad.

**Comment by AbdussamadA** [comment]
no I just checked even in 2.7.1 some commands don't like -w before the command. create and restore for example.

**Comment by ecdsa** [comment]
are you on OSX or linux?

**Comment by AbdussamadA** [comment]
linux. opensuse is running 2.6.4. debian vm running 2.7.1

**Comment by AbdussamadA** [comment]
debian install is jessie (8)

**Comment by ecdsa** [comment]
do the other commands accept -w before the command?
what happens with create and restore, do they throw an error?

**Comment by ecdsa** [comment]
deseed command removed here: df6dae90d6ecc54f990d0cbfe116708c96d57fd5

**Comment by AbdussamadA** [comment]
This is the error that I get on create and restore:
```
electrum -w test7 create
Error: Remove the existing wallet first!

```
getseed and getmasterprivate also doesn't work with -w ahead of the command. I bet there are others like these too. Is there some common command line parsing function where this bug might be?

**Comment by ecdsa** [comment]
it uses a python module called argparse.
do you have the version of argparse that comes originally with python?

**Comment by AbdussamadA** [comment]
> 
do you have the version of argparse that comes originally with python?


how would i go about finding this out?

**Comment by ecdsa** [comment]
run python: 
```
>>> import argparse
>>> argparse._version__
```
mine is 1.1

**Comment by AbdussamadA** [comment]
1.1 here too. python version is 2.7.9

**Comment by ecdsa** [comment]
I do not quite understand that..
can you add "print args" in electrum, line 277 
(after parse_args)
and see how it behaves with various commands?

**Comment by ecdsa** [comment]
here is something else you can try: instead of writing -w use the full syntax:
```electrum --wallet xx create```

**Comment by AbdussamadA** [comment]
Looks like it doesn't parse the args correctly:

```abdussamad@debian:~/electrum$ electrum -w another_test create
Namespace(cmd='create', electrum_path=None, portable=False, verbose=False, wallet_path=None)
Error: Remove the existing wallet first!
abdussamad@debian:~/electrum$ electrum --wallet=another_test create
Namespace(cmd='create', electrum_path=None, portable=False, verbose=False, wallet_path=None)                                       
Error: Remove the existing wallet first!                                                                                           
abdussamad@debian:~/electrum$ electrum -w=another_test create                                                                
Namespace(cmd='create', electrum_path=None, portable=False, verbose=False, wallet_path=None)                                       
Error: Remove the existing wallet first!                                                                                           
abdussamad@debian:~/electrum$ electrum --wallet another_test create                                                                
Namespace(cmd='create', electrum_path=None, portable=False, verbose=False, wallet_path=None)                                       
Error: Remove the existing wallet first!  
```

There is no problem with -w after the command:

```

abdussamad@debian:~/electrum$ electrum create -w yet_another_test
Namespace(cmd='create', electrum_path=None, portable=False, verbose=False, wallet_path='yet_another_test')

```

The shell I'm using:

```
abdussamad@debian:~/electrum$ bash --version
bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

```

**Comment by ecdsa** [comment]
perhaps it is a difference in the python release?
I use Python 2.7.6.
@kyuupichan had the same issue, and it is solved for him. he uses Python 2.7.12

**Comment by AbdussamadA** [comment]
I have python 2.7.12 on the opensuse host OS.  I just installed electrum 2.7.1 on it too to see if the problem is still there and it is.

Anyway it's not that big a deal. I'm sure any other people who encounter this will see that putting -w after the command works all the time.

**Comment by ecdsa** [comment]
yes, closing it because the bug is probably not in electrum
