### ISSUE TITLE
Incompatible API in TREZOR plugin

### ISSUE THREAD

**Issue by slush0** [spesmilo/electrum#1951]
Hey Thomas,

I've spent some time to refactor python-trezor in a way it don't use google's python protobuf library, but lightweight pure-python implementation. The side effect is that the API slightly changed; for example where Electrum prepare data for sign_tx, it uses ".extends()", which is google's construct, no longer available in new library (new API uses standard python lists, making is even more awesome).

I'm ready to prepare pull request to Electrum so the change won't require your effort. The question is, how we can do that when the codebase is shared between Trezor and Keepkey (which uses google's protobuf)? Maybe it's a time to make separate plugins for both devices, because this is second time in recent month or two when the shared code makes unnecessary hassle.

**Comment by ecdsa** [comment]
ok, let us have separate plugins.
make sure your PR does not affect the keepkey plugin, though.

**Comment by slush0** [comment]
If the keepkey plugin won't depend on trezor plugin, I won't have anything to break :-).
