### ISSUE TITLE
IP address server (command > show IP)

### ISSUE THREAD

**Issue by Generator-X** [spesmilo/electrum#1955]
Hi,

Is there a command to the console in electrum which shows the current IP address of the connected server?

**Comment by ecdsa** [comment]
network.interface.host

**Comment by Generator-X** [comment]
Thank you, there is a complete list of commands for electrum console?

**Comment by ecdsa** [comment]
that was not an Electrum 'command', that was a python variable.
Electrum commands are designed for the command line, but the console accepts them too.
just type help()
