### ISSUE TITLE
IP Tor Browser (command > show IP)

### ISSUE THREAD

**Issue by Generator-X** [spesmilo/electrum#1956]
https://s18.postimg.org/x69rwry89/VVVV1.png

What is the IP address of TOR (Command)?

**Comment by ecdsa** [comment]
you have to setup the proxy in order to connect with tor

**Comment by Generator-X** [comment]
Yes I know, (but what is the command to display the **IP TOR** > Server)

**Comment by ecdsa** [comment]
not sure what you mean, maybe 'network.proxy' is what you're looking for?

**Comment by Generator-X** [comment]
My IP address (Example "10.10.10.10") is changed to TOR Browser (Example "20.20.20.20").
Server: (Example "bitcoin.sk") They see the IP address of the TOR.

There Electrum command that displays this address (Example "20.20.20.20")?

**Comment by ecdsa** [comment]
sorry I do not understand your question.

**Comment by Generator-X** [comment]
My English is not good bug is on my side, I'll try to describe it otherwise give me time

**Comment by Generator-X** [comment]
https://s11.postimg.org/v032j4ndf/TOR1.png

Command in the console that displays the IP address "109.163.234.8"

**Comment by ecdsa** [comment]
if you want the IP of the exit node, I don't think it is possible to have it.

**Comment by Generator-X** [comment]
Yes That's exactly what I want :-P

And there is no other method to receive this IP ? (A simple script)?

**Comment by ecdsa** [comment]
I am not an expert on TOR. this question is not about Electrum.

**Comment by tunkaflux** [comment]
@Generator-X If you are indeed connected to Tor as your last drawing shows and you want to know the ip address of the exit node you are using I think you can surf to http://whatismyipaddress.com/ and see that information.
If that's not what you want, I don't understand the question :)
