### ISSUE TITLE
Ledger Nano S displays change instead of output address.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#1961]
I tried everything, sending to 2 address, plugged, unplugged, retarted electrum.

Everytime the Ledger Nano S is being instructed to send a different amount of bitcoin to a different address.

It's always the same address and I cannot find anywhere where this address could be coming from.

**Comment by ecdsa** [comment]
is this on linux? windows?

**Comment by Transisto** [comment]
Update : Problem is not with electrum, The Nano S respond want to send to the same on Mycelium, (very sketchy !)

**Comment by ecdsa** [comment]
is it confusing the output and change addrress?

**Comment by ecdsa** [comment]
does it want to send to the same address for both Mycelium and Electrum?

**Comment by Transisto** [comment]
Yes, I think so, The Ledger app instruct to send to the right address.

**Comment by ecdsa** [comment]
which address are you trying to send to?

**Comment by Transisto** [comment]
The transaction got processed as it should, but the device would show change amount and change address as the main transaction.

This could be a  vulnerability because the change address is not being displayed and it is obviously not an address belonging to the NanoS.

**Comment by Transisto** [comment]
![image](https://cloud.githubusercontent.com/assets/388716/19218251/3d93e632-8dc3-11e6-9175-796e52b06584.png)

![image](https://cloud.githubusercontent.com/assets/388716/19218274/647dedd8-8dc3-11e6-83eb-a4238f3c78d7.png)

**Comment by ecdsa** [comment]
I can reproduce it.
it seems to depend on the order of outputs.
