### ISSUE TITLE
[Bug] Portable version launched from URL does not open wallet and autofill send form

### ISSUE THREAD

**Issue by Kristinita** [spesmilo/electrum#1962]
### Summary

Links of `bitcoin:` protocol not correct open in Electrum client.
### Expected behavior

Example link. I use standard [Bitcoin URI scheme](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki):

```
bitcoin:17uctxtsWG3gpyAy6iJ8AVd5rdSjkJH2?label=In%20the%20treatment%20of%20Sasha's%20teeth&amount=0.0037
```

I want, when I open that link in browser, autofill forms.

![Electrum Autofill forms](http://i.imgur.com/vcs43P1.png)
### Actual behavior

When I open my link in browser, start Electrum window open for me:

![Start Window](http://i.imgur.com/yegAlF9.png)
### Steps to reproduce

I create my link for `bitcoin:` protocol. I set in my browser Firefox Electrum for Bitcoin protocol links:

![Electrum for Bitcoin protocol](http://i.imgur.com/XPxqPMW.png)

I open my bitcoin link and I get Electrum start window.
### Litecoin

Exactly the same problem when I open Litecoin links use [Electrum-LTC](https://electrum-ltc.org/).
### Environment

**Operating system and version:**
Windows 10.0.14393
**Electrum:**
Portable 2.7.3
**Browser:**
Firefox 49.0.1

Thanks.

**Comment by ecdsa** [comment]
do you have the same issue with the standalone version, instead of the portable version?

**Comment by ecdsa** [comment]
please try with the standalone version, I need to know

**Comment by Kristinita** [comment]
@ecdsa , Standalone version still crashed for me. See #1933. Thanks.

**Comment by ecdsa** [comment]
if it still crashed, why did you close the issue?

**Comment by ysangkok** [comment]
@Kristinita I have updated the issue description to the best of my understanding. Is the new description correct?

If I understand you correctly, you expect clicking on an bitcoin: url scheme link to open the wallet automatically, which is does not. Is this understanding correct?

Could you test with the most recent version, please? If you cannot, please let us know, so that the issue does not linger.

**Comment by Kristinita** [comment]
In 3.0.4 version I have an expected behavior (however, I still need to enter a password before open wallet).

Thanks!
