### ISSUE TITLE
Restore custom entropy option

### ISSUE THREAD

**Issue by jaekwon** [spesmilo/electrum#1964]
From https://github.com/spesmilo/electrum/commit/e0c38b31b40b42138527e9fd3f4bad78e0b12802#diff-994412d86e91569aed9057984c68a54e : 

`remove custom entropy option; nobody uses it`

Somebody uses it.  Just saying.

**Comment by ecdsa** [comment]
what is the use case?

**Comment by RealBTC** [comment]
I back this, if PC rng is weak it is logical to have the option to have more entropy. The 12 word seeds since 2.7 are too weak, but atleast have the option to have more entropy.

**Comment by ecdsa** [comment]
ok, I restored it. I guess it is cheaper to have it than to educate users about entropy.
