### ISSUE TITLE
Create light option without dependencies, for offline systems

### ISSUE THREAD

**Issue by jaekwon** [spesmilo/electrum#1965]
I tried to install this on an airgapped machine, and the amount of dependencies makes it very difficult to install without first connecting to the internet.

I would much prefer to have a standalone system that can be audited in its entirety, without having to trust the various dependency management systems.

Any thoughts on reducing the amount of external dependencies, and keeping the overall count of external dependencies to a minimum, to increase audit-ability?

**Comment by ecdsa** [comment]
you do not need to install them. 
all the dependencies are included in the tar.gz
