### ISSUE TITLE
Incorrect password after importing private key

### ISSUE THREAD

**Issue by annaparker** [spesmilo/electrum#1966]
I did an upgrade to version 2.7.5, then I have started getting "Incorrect password" message each time once I try to send Bitcoins. My wallet is password protected. Tried several servers, tried different fee, different amount - same error. Finally I did downgrade to 2.6.4, imported private keys and it works fine. Got back to 2.7.5 (did a full backup from %appdata% and didn't share Electrum folders between 2.6.x and 2.7.5 versions). My default_wallet.imported is pretty big, 6.68 MB, because I have hundred or thousand of private keys already imported, maybe that's the reason, but I don't see why - as on 2.6.4 I had no problem. Also on 2.7.4 also didn't notice the problem as far as I remember, but I'm not sure. Maybe some password protection things have been changed since 2.7.5 and it won't decrypt my wallet using my correctly entered password (even I wrote it on notepad.exe then pasted to password entry box).

OS: Win7 x64, Electrum started through TOR with --proxy socks5:127.0.0.1:9150 parameter.

**Comment by ecdsa** [comment]
someone reported a similat issue on irc.
does it get fixed if you restart electrum?

**Comment by ecdsa** [comment]
did you import a private key after upgrading to 2.7 ?

**Comment by annaparker** [comment]
@ecdsa That was me on IRC. ;-) No - as I wrote on IRC the restart helps, but it's not. Tested several times. I didn't import private key(s) after upgrading to 2.7.5, but I did import after 2.7.

**Comment by ecdsa** [comment]
ok, which IRC user are you?
I am testing a fix.

**Comment by ecdsa** [comment]
note: it is the same bug as:
```<raedah> mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation) ```

**Comment by ecdsa** [comment]
the commit I made above is not sufficient. more will follow shortly.

**Comment by ecdsa** [comment]
f0611c456938eb485da765895dc482456fa292d1 should fix it. 
I'll test a bit more before tagging a new version.

**Comment by annaparker** [comment]
You have to know I didn't import private keys on 2.7.5, but on 2.7.0 and I think it worked fine on 2.7.1 up to 2.7.4. Just stopped on 2.7.5.

**Comment by ecdsa** [comment]
yes I got that. the key import is broken, you'll have to reimport it in the next version.

**Comment by ecdsa** [comment]
all right, it is fixed, please upgrade to 2.7.6

**Comment by ecdsa** [comment]
and don't forget to reimport the private keys you imported in 2.7.x (see release notes)
