### ISSUE TITLE
Electrum 2.7 will not accept my password

### ISSUE THREAD

**Issue by bakkerthehacker** [spesmilo/electrum#1967]
When entering my password, electrum responds with:

> 'ascii' codec can't decode byte 0xed in position 2: ordinal not in range(128)

I cannot spend any bitcoins.  Electrum 2.7 is unusable for me.

**Comment by ecdsa** [comment]
hi, are you using imported keys?

**Comment by bakkerthehacker** [comment]
I upgraded my 2.6 client to 2.7 and have just now noticed the loss in functionality when trying to send bitcoins.  I set up my wallet initially on 2.6

**Comment by ecdsa** [comment]
is this a wallet with a seed, or a wallet with imported keys?

**Comment by bakkerthehacker** [comment]
> **without importing anything**

**Comment by ecdsa** [comment]
ok, what is the exact version of Electrum you're using?

**Comment by bakkerthehacker** [comment]
I have 2.6.4 and upgraded to 2.7.5 when the error happened

**Comment by ecdsa** [comment]
does it happen both when you enter your password in order to spend btc, and in order to view the seed?

**Comment by raymond-w-ko** [comment]
I am also getting the same error when trying to view the seed.

**Comment by raymond-w-ko** [comment]
More info:
Seed was originally created in the 1.9.X era, so it was probably the 9 word variant.
If I remember correctly the password and seed components were in English.

**Comment by raymond-w-ko** [comment]
Using a git checkout and `./electrum getseed` command, I got the following stack trace.

```
Traceback (most recent call last):
  File "./electrum", line 369, in <module>
    result = run_offline_command(config, config_options)
  File "./electrum", line 225, in run_offline_command
    seed = wallet.check_password(password)
  File "/home/rko/src/electrum/lib/wallet.py", line 1544, in check_password
    self.keystore.check_password(password)
  File "/home/rko/src/electrum/lib/keystore.py", line 440, in check_password
    self.check_seed(seed)
  File "/home/rko/src/electrum/lib/keystore.py", line 431, in check_seed
    secexp = self.stretch_key(seed)
  File "/home/rko/src/electrum/lib/keystore.py", line 392, in stretch_key
    x = hashlib.sha256(x + seed).digest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)
```

**Comment by raymond-w-ko** [comment]
I did a little investigation, and somehow the seed was of 'unicode' type. This obviously not play well through the hashing loop. If I apply the following hack/fix (?) then I could get my original seed, at least in the command line.

I am unsure whether this is actually safe to apply in the GUI version.

```
diff --git a/lib/keystore.py b/lib/keystore.py
index 1c9f5a8..b1aa035 100644
--- a/lib/keystore.py
+++ b/lib/keystore.py
@@ -387,6 +387,7 @@ class Old_KeyStore(Deterministic_KeyStore):
 
     @classmethod
     def stretch_key(self, seed):
+        seed = seed.encode("ascii")
         x = seed
         for i in range(100000):
             x = hashlib.sha256(x + seed).digest()
```

**Comment by ecdsa** [comment]
thanks for investigating. I guess it was broken by this commit 2833a5bae93b891c54c6a15f06dd77173dd927d4
