### ISSUE TITLE
Pay to: please wait...

### ISSUE THREAD

**Issue by l29ah** [spesmilo/electrum#1969]
If i copy-paste a bitcoin payment URL from BitPay to the Send tab, it fills with "please wait..." and that's it.
```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/electrum_gui/qt/main_window.py", line 1356, in get_payment_request_thread
    if self.payment_request.verify(self.contacts):
  File "/usr/lib64/python2.7/site-packages/electrum/paymentrequest.py", line 108, in verify
    pr.ParseFromString(self.raw)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1083, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.
```

**Comment by ecdsa** [comment]
it works for me, using this URI:
bitcoin:1AG94XZ4wB33536nG1aWUgHMvKXb3R3L4w?amount=1.000000&r=https%3A%2F%2Fbitpay.com%2Fi%2F4L85gM9Rsgv1W471Ns3k7z

are you using the latest version? can you post the URI ?

**Comment by ecdsa** [comment]
oh well, you are not using the current version of Electrum, I can tell from the traceback.
please try with the latest version, before you post something here.

**Comment by l29ah** [comment]
It's the same on 2.7.6 using your url:
```
Exception in thread Thread-75:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/electrum/util.py", line 455, in get_payment_request_thread
    on_pr(request)
  File "/usr/lib64/python2.7/site-packages/electrum_gui/qt/main_window.py", line 1348, in on_pr
    if self.payment_request.verify(self.contacts):
  File "/usr/lib64/python2.7/site-packages/electrum/paymentrequest.py", line 120, in verify
    pr.ParseFromString(self.raw)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib64/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1083, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.
```

**Comment by l29ah** [comment]
Same on 2.7.7.

**Comment by ecdsa** [comment]
ok, maybe we don't have the same versino of google protobuf. are you running from sources, or from a binary?

**Comment by l29ah** [comment]
I have Gentoo, so everything is compiled from sources, if you meant that.

**Comment by ecdsa** [comment]
did you install electrum with pip?
you could try to upgrade protobuf: 
```pip install protobuf --upgrade```

for me it installs protobuf-3.1.0.post1

**Comment by ecdsa** [comment]
ok, I can make it crash if I send a wrong URL; that needs to be fixed

**Comment by l29ah** [comment]
Upgraded protobuf to 3.1.0, same stuff.

**Comment by ecdsa** [comment]
that commit prevents the crash.
I do not know why it could not parse the request, I would need to see the URI for that.

**Comment by l29ah** [comment]
On Thu, Oct 13, 2016 at 09:42:28PM -0700, ThomasV wrote:
> that commit prevents the crash.
> I do not know why it could not parse the request, I would need to see the URI for that.

Again: i've used the URI you've posted above.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by ecdsa** [comment]
did you copy-paste it? maybe it is safer if you try this from the command line:
```
electrum "bitcoin:1AG94XZ4wB33536nG1aWUgHMvKXb3R3L4w?amount=1.000000&r=https%3A%2F%2Fbitpay.com%2Fi%2F4L85gM9Rsgv1W471Ns3k7z"
```

**Comment by l29ah** [comment]
On Fri, Oct 14, 2016 at 05:07:02AM -0700, ThomasV wrote:
> did you copy-paste it? maybe it is safer if you try this from the command line:
> ```
> electrum "bitcoin:1AG94XZ4wB33536nG1aWUgHMvKXb3R3L4w?amount=1.000000&r=https%3A%2F%2Fbitpay.com%2Fi%2F4L85gM9Rsgv1W471Ns3k7z"
> ```

Yes. Using the command line gives the same result.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by ecdsa** [comment]
ok, just to be sure, can you run electrum from its own directory? that way it will use the dependencies located in the 'packages' subdirectory, and not whatever Gentoo provides.
download the tar.gz, unpack it, cd to the directory and run electrum from there.

**Comment by l29ah** [comment]
On Fri, Oct 14, 2016 at 05:16:10AM -0700, ThomasV wrote:
> ok, just to be sure, can you run electrum from its own directory? that way it will use the dependencies located in the 'packages' subdirectory, and not whatever Gentoo provides.
> download the tar.gz, unpack it, cd to the directory and run electrum from there.

Okay, it works that way.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by ecdsa** [comment]
ok, so Gentoo has one of its dependencies that does not work.
if it's not protobuf, it's probably requests

**Comment by l29ah** [comment]
On Fri, Oct 14, 2016 at 05:28:36AM -0700, ThomasV wrote:
> ok, so Gentoo has one of its dependencies that does not work.
> if it's not protobuf, it's probably requests

Printed the self.raw thing:


```
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> bitpay.com</h2>
```

I wonder why cloudflare shit likes your library more than the same one shipped by Gentoo.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by ecdsa** [comment]
ok, we should try to detect if we're sent html
