### ISSUE TITLE
Can't create offline wallet on Linux/signing fails because it wants server

### ISSUE THREAD

**Issue by Bjoern** [spesmilo/electrum#1972]
I've downloaded the python version for 2.7.7 and start it from the console with ./electrum (or python electrum, same result)

When it comes to the networking dialog, it says to hit "cancel" to create an offline wallet. But there is no cancel button. When I select "Back" the app quits. I tried clearing the form and deselecting "select server automatically" and pressing "Next". However, when I try to sign a transaction, it still tries to connect to a server and fails.

Actually I don't understand why it needs to connect to a server to sign a transaction to begin with?

Update: I now used version 2.6 to sign the transaction instead. That one has a "Cancel" button and it works as expected. So it seems the issue was introduced with version 2.7.

**Comment by ecdsa** [comment]
indeed, that button is missing

**Comment by ecdsa** [comment]
Electrum does not connect to a server in order to sign a transaction.
I changed the message, it instructs the user to press 'next'.
Note: if you do not want Electrum to connect to try to connect at all, start it with the ```--offline``` flag.
