### ISSUE TITLE
HW.1 sending issues again

### ISSUE THREAD

**Issue by JPUnix** [spesmilo/electrum#1979]
When I try to send BTC with version 2.7.8 from a HW.1 hardware wallet under Windows 7 I get as far as being prompted to sign the transaction with the HW.1 security card but it goes into a loop because the transaction ID is "Unknown". I can reproduce this behavior every time.

**Comment by ecdsa** [comment]
what do you mean by 'it goes in a loop' ?
does it fail to sign the transaction?

**Comment by JPUnix** [comment]
It continues to loop back to the section where I am prompted for the codes from the security card. the window at the upper left says "says that the transaction ID is unknown".

**Comment by ecdsa** [comment]
@btchip any iidea?

**Comment by btchip** [comment]
No, never saw that one

**Comment by JPUnix** [comment]
hmm then I guess no more Electrum for me for a while until this is addressed.

**Comment by ecdsa** [comment]
I cannot reproduce that. please update your ledger firmware.

**Comment by JPUnix** [comment]
Wow!! You closed the ticket? I've been a supporter of Electrum since it's inception. I bought several Ledgers just to work on helping it to work with Electrum. I AM on the most current firmware. I have been using the most current firmware for some time now and check the version frequently. What a flippant answer!

**Comment by btchip** [comment]
I'll retest with the latest official firmware over the week-end and see what happens - in my opinion it shouldn't work right now (until either the Segwit firmware is released for HW.1 or the plugin is updated to support the old sending method) but it shouldn't crash that way either.

**Comment by ecdsa** [comment]
see #1992
