### ISSUE TITLE
Cancel button doesn't cancel in new wallet wizard

### ISSUE THREAD

**Issue by wirion** [spesmilo/electrum#1984]
When I do:
1. File->New/Restore->Ok
2. On the "what kind of wallet" page I press Cancel
3. I select any of the options (e.g. "Standard wallet")
4. I press Next
Then nothing happens.

I guess Cancel in step 2 should already close the dialog, but it also prevents Next from working.

This happens with 2.7.8 on Windows and 2.7.7 on Arch Linux.

**Comment by ecdsa** [comment]
thanks, fixed

**Comment by badzso** [comment]
port.

Report for Tuesday, 06 September 2016

Date	04.09.2016
2 days ago	05.09.2016
Yesterday	06.09.2016
Today
BTC Price	539,34 EUR
597,82 USD	545,00 EUR
608,99 USD	542,37 EUR
608,50 USD
Coins	
12.756.878,00	BTC	6.880.242.277,32 EUR
12.685.514,09 BTC	6.952.498.510,00 EUR
12.818.737,23 BTC	6.918.947.920,86 EUR
12.756.878,00 BTC
Currencies	
-858.605,00	EUR	-858.605,00 EUR
-1.583,06 BTC	-858.605,00 EUR
-1.583,06 BTC	-858.605,00 EUR
-1.583,06 BTC
Sum Coins	6.880.242.277,32 EUR
12.685.514,09 BTC	6.952.498.510,00 EUR
12.818.737,23 BTC	6.918.947.920,86 EUR
12.756.878,00 BTC
Sum Currencies	-858.605,00 EUR
-1.583,06 BTC	-858.605,00 EUR
-1.583,06 BTC	-858.605,00 EUR
-1.583,06 BTC
Profit / Loss	6.879.383.672,32 EUR
12.683.931,03 BTC	6.951.639.905,00 EUR
12.817.154,17 BTC	6.918.089.315,86 EUR
