### ISSUE TITLE
RBF when sending MAX, "Cannot bump fee : could not find a change output"

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#1985]
![image](https://cloud.githubusercontent.com/assets/388716/19432878/690b868e-942c-11e6-8d0b-989871bff1d8.png)

If it is not possible to use RBF when sending the MAX amount should there be a notification when selecting "Replaceable" and MAX ?

**Comment by dabura667** [comment]
No. you could receive a transaction after sending but before confirmation which would then be able to be included to allow replacing.

**Comment by ecdsa** [comment]
Note that this restriction is not imposed by Bitcoin. It is not possible in Electrum because I tried to be nice with that fraction of users who dislike RBF. Maybe 'send max' could be considered as an exception to that rule.
