### ISSUE TITLE
Creating a wallet with trezor doesn't work.

### ISSUE THREAD

**Issue by bitcoinauge** [spesmilo/electrum#1993]
After I set the pin I see "Please wait." for hours.

This happened once immediately after I set the pin, and once after I confirmed the pin.

I use ubuntu 16.10 and installed electrum via pip.

**Comment by ecdsa** [comment]
do you still have this issue?
if yes, run electrum from the terminal and see if there is a traceback when it displays 'please wait'

**Comment by ecdsa** [comment]
can't reproduce issue, it works for me
