### ISSUE TITLE
Offline Txn Signing on Android = Crash

### ISSUE THREAD

**Issue by fracture-point** [spesmilo/electrum#1995]
I cannot sign a transaction on the android app unless I'm online, which completely defeats the purpose of cold storage.  If I am online, the transaction signs fine, and I get the option to broadcast it.  If I am offline, the app says "signing" for about 20 seconds, and then the app quits (crashes), dumping me back to the Android home screen.

Running Electrum v2.7.9.0 on Android v4.0.4, normal wallet on Android + a watching wallet on OSX generating the unsigned txn.

**Comment by ecdsa** [comment]
thanks for the report. the same issue was reported on desktop, hopefully it will be fixed today.
