### ISSUE TITLE
Encrypt/Decrypt message 

### ISSUE THREAD

**Issue by micromatrix14** [spesmilo/electrum#1998]
What encrypt/decrypt message is supposed to do ?
when I enter a message and use one of addresses as a public key and hit encrypt, it shows non-hexadecimal digit found ??

**Comment by ecdsa** [comment]
you're not supposed to enter an address in a field that is called 'public key'

**Comment by micromatrix14** [comment]
Excuse me sir, why you closed that thread, I haven't even said, if I got what you meant or not!!
in addition, this isn't exist in your document !
and finally I tried without entering any address in the public key, and only random text in the message, and showed me index out of range 
tried with entering a random number in the public key and showed me odd number, so I tried with even number, then showed me a message with a title of warning and contains nothing!!

**Comment by micromatrix14** [comment]
![screenshot from 2016-10-25 14-02-54](https://cloud.githubusercontent.com/assets/22969054/19685241/e066e8be-9abb-11e6-9dfa-0a3c6bc5b5a0.png)
![screenshot from 2016-10-25 14-03-05](https://cloud.githubusercontent.com/assets/22969054/19685242/e0772152-9abb-11e6-8b5f-4ff728ef027d.png)

**Comment by micromatrix14** [comment]
I tried again, and again until I knew what was the problem, Thank you but, I think you need to add all Electrum features in the document, because this one doesn't exist
and be more little nice to people, don't close the thread till, you are sure, what we report or ask about, we already get it, Thank you ;)
