### ISSUE TITLE
Clicking "max" or using "!" leaves behind a tiny balance, coin selection of incorrect coins even without "max"

### ISSUE THREAD

**Issue by psb777** [spesmilo/electrum#2000]
When clicking "max" or using "!" to send the full balance a tiny amount is left behind. I think this did not use to happen. And I think it may be a consequence of the dynamic fee feature.

**Comment by ecdsa** [comment]
I noticed this oo. It is not because of the dynamic fee. it is because the new coin chooser does not spend dust when spending it is more expensive than not. I think this is not a good feature, it should not behave like that when max is selected. so, not closing this.

**Comment by ecdsa** [comment]
note: if you want to get rid of the dust, you can spend it as fee with an OP_RETURN transaction

**Comment by psb777** [comment]
Is there no way to combine the tiny slivers of previous transactions which compose the balance at an address? I am sure I never noticed this phenomenon before. I run the danger of having many many tiny but non-zero balances cluttering up my wallet. There is even the possibility an entire wallet could end up being composed of them, none of them usable. OP_RETURN just means you lose the "dust" or "slivers".

**Comment by psb777** [comment]
And there seems to be no way to get Electrum to issue an OP_RETURN. Am I missing something?

**Comment by ecdsa** [comment]
You can issue any script you like with Electrum.
1. Select the dust output, add it to your "send from" field
2. write OP_RETURN in the recipient field, and set the amount to zero.
3. set the fee manually, to match the exact amount in the output.

**Comment by psb777** [comment]
Thanks.

**Comment by psb777** [comment]
I think it isn't only when "max" is clicked the wrong coins get selected. If I want to send 0.0019 (0.0018 + 0.0001 fee) what coin should be used out of { 20.2, 0.2, 0.02, 0.002 }? If the 0.002 coin is used I will be left with the unspendable 0.0001 change. Or is that the unavoidable situation anyway, and it remains better to always keep the biggest possible coins? Am I better off left with 0.0001 or a 0.0201 coin (if the second smallest were used)?

**Comment by ecdsa** [comment]
no, it does not work like that.
if the change amount is dust then it is automatically added to the mining fee

**Comment by psb777** [comment]
You can pick at my suggestion around the edges if you like but it leaves the issue of choosing the correct coin unaddressed. There would be no dust (to be left behind or to be added  to the mining fee) in the above example if the 0.02 coin were selected instead of the 0.002 coin. The coin selection algorithm is wrong. 

I acknowledge you can force selection of the coin, but the one the algorithm selects is often not ideal. It creates dust. That is the issue I am trying to address. Dust.
