### ISSUE TITLE
Build on macOS Sierra 10.12 without pyqt4?

### ISSUE THREAD

**Issue by 2600box** [spesmilo/electrum#2001]
Hi,

I have looked extensively for anyone reporting this problem, let alone a solution and not found one.

On macOS 10.12 (Sierra) pyqt4 will not install with homebrew

`This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.`

pyqt5 is installed, but electrum doesn't see it and of course says `Error: Could not import PyQt4 on Linux systems, you may try 'sudo apt-get install python-qt4'`

is it possible to build electrum with pyqt5? or a way to get pyqt4 working?

**Comment by ecdsa** [comment]
I don't think it is possible to build with qt5. the code would need to be rewritten for qt5.

**Comment by 2600box** [comment]
For anyone searching for this. The answer to install pyqt4 without homebrew is here: https://apple.stackexchange.com/questions/258745/install-python-pyqt4-on-macos-10-12-sierra

This can probably be closed, but could a milestone for shifting to pyqt5 be considered?

**Comment by JikkuJose** [comment]
Stumbled on the same problem, while trying make electrum work for Mac in commandline mode. Any alternative or solutions to this, please reply.

**Comment by lukaszdrynski** [comment]
```brew install cartr/qt4/pyqt``` 
You may need to uninstall the version you have installed first with ```brew uninstall pyqt```

**Comment by bauerj** [comment]
We're now on PyQt5 so this is not an issue any more.
