### ISSUE TITLE
Dust created by Electrum dynamic fee algorithm

### ISSUE THREAD

**Issue by psb777** [spesmilo/electrum#2003]
I am being troubled by the creation of Bitcoin dust in Electrum which makes everything untidy.

Where does the dust come from? I never used to have any coins the size of dust. Nobody delivered me dust. What's happening (I think), is illustrated by this example: 

I choose to send a relatively small amount, say 2mBTC (millibits), somewhere and the dynamic fee algorithm generates a fee of 0.00018403. This has far too many significant figures. A figure of 0.000184 has no material difference in value, I suggest neither does 0.00018 and I bet that no one would care were this rounded by the algorithm to 0.0002. Thereby is the dust created.

I am forced, for sanity's sake, to give away the dust to the miners using the OP_RETURN mechanism. The miners may or may not be able to profit from the dust they collect, I don't know and I don't mind too much as long as the dust is not being created systematically and deliberately! The OP_RETURN mechanism could be made a little easier to use in Electrum, but that too is not my complaint. It's the creation of the dust.

I appreciate this may seem similar to a recently raised issue of mine. I partially accept the answer - that there is a fault with the coin selection mechanism when "max" is clicked. I think there is a problem with that algorithm even when "max" is not clicked. The wrong coins are being selected leaving behind dust as change. This is encouraged by these exquisitely finely defined fees. Dust is created as a consequence.

**Comment by ecdsa** [comment]
no, the algorithm does not create dust.
the problem probably is that the dust threshold varies from server to server.
a small amount maybe considered dust by a server, and not by another

**Comment by dabura667** [comment]
> I am forced, for sanity's sake, to give away the dust to the miners using the OP_RETURN mechanism.

OP_RETURN has nothing to do with fees. If you set a BTC amount to a OP_RETURN output, that bitcoin is not retrieved by anyone. Not even miners.

**Comment by psb777** [comment]
OK, I may be wrong re OP_RETURN but nevertheless I am using that mechanism to tidy up my Electrum wallet. Where is the dust coming from? I think it is also wrong coin selection - nothing to do with the servers - have a look at the {2, 0.2, 0.02, 0.002} example at #2000 https://github.com/spesmilo/electrum/issues/2000

**Comment by ecdsa** [comment]
closing, I don't think there's any issue other than #2000, which is fixed now.
