### ISSUE TITLE
Electrum doesn't generate valid mnemonic seeds (according to bip39)

### ISSUE THREAD

**Issue by YiumPotato** [spesmilo/electrum#2005]
The seed generated by Electrum, 'furnace airport hen praise knife anxiety spice police cause hurry clown easily' (no money has been depoed don't need to bother & also pretty creepy seed =P), has an invalid checksum.

(you can check it in https://iancoleman.github.io/bip39/#english , it doesn't allow me, and such as pycoin and python-mnemonic, all telling me that its checksum isn't valid)

**Comment by dabura667** [comment]
It only uses the same exact wordlist, which may mislead you, but it is not BIP39.

The reasoning for why it does not use BIP39 has been explained in previous issues countless times.

**Comment by ecdsa** [comment]
see http://docs.electrum.org/en/latest/seedphrase.html
