### ISSUE TITLE
I have already a seed - no next

### ISSUE THREAD

**Issue by bom64** [spesmilo/electrum#2010]
After enter the 12 seed word to Electum, generated by Mycelium, the next key is not enabled. Same bug in Android and the Portable Windows version..
If the 12 seed word is generated of Electum the next button is enabled.

Is it by design that Electrum don't support aliens seeds as 12 word?

**Comment by dabura667** [comment]
Yes.

Electrum does not use the same algorithm as Mycelium.

**Comment by ecdsa** [comment]
see http://docs.electrum.org/en/latest/seedphrase.html
