### ISSUE TITLE
Help please - Sent coins to my electrum wallet and they haven't come through

### ISSUE THREAD

**Issue by A-Liberty** [spesmilo/electrum#2011]
Hi all, I need some advice on how to retrieve coins. After purchasing bitcoins I sent them through to my electrum wallet as normal but they never came through. The address I sent them to was definitely correct. They didn't even come through as unconfirmed, the request is just sat there pending. I have contacted the site where I purchased the coins and everything went through successfully on their end. I've looked at the transaction id on the blockchain and it has 26 confirmations so why have I not recieved any coins? Can anyone give me some advice? 
Any help would be much appreciated.
Cheers

**Comment by micromatrix14** [comment]
I have the same issue, some of my transactions are confirmed, but shows unconfirmed, I noticed when, I leave the electrum wallet opened for a long time maybe hours, it receive the right number of confirmations, which is very annoying something

**Comment by ecdsa** [comment]
@A-Liberty we cannot help you if you don't post the transaction ID

**Comment by ecdsa** [comment]
closing, no useful info from OP
