### ISSUE TITLE
Sign/Verify Message Electrum 2.7.11

### ISSUE THREAD

**Issue by crwthatonic** [spesmilo/electrum#2015]
Whenever I try to sign, it asks for my password which is normal. After I input my password, nothing happens. No dialog boxes, no signatures etc. So I tried to input a wrong password and it shows a dialog box saying it's the incorrect password. 

Next I tried changing the password. I put my password (same password I input in the Sign/Verify Message) now it says wrong password. 

Please help

**Comment by ecdsa** [comment]
I cannot reproduce that issue. what is your platform?

**Comment by crwthatonic** [comment]
Windows 10 64 bit.

**Comment by ecdsa** [comment]
if you restore your wallet from seed, does the issue persist with the restored wallet?

**Comment by MaxXor** [comment]
The sign/verify message functions don't work for 2FA wallets (the ones with TrustedCoin).

**Comment by crwthatonic** [comment]
Now it is explained  i understand. Thanks

**Comment by ecdsa** [comment]
closing as duplicate of #2064
