### ISSUE TITLE
Sweep fee doesn't respect the 'fee per kb' setting

### ISSUE THREAD

**Issue by fastercheaper** [spesmilo/electrum#2017]
Settings
Transaction fee : 0.0005 BTC/kb
Dynamic fees : Yes
Feel multiplier : 100%

The following example transaction was 14KB but the fee was only 0.0005BTC
https://blockchain.info/tx/f21235e55e242aac902f10b9c964e0076b6fa01e5dabf7b70bf70badbaafee04

Shouldn't it be more? Or does sweep have different settings?

**Comment by ecdsa** [comment]
you are using an old version; there is no more 'fee multiplier' in 2.7
please do not report bugs about old versions; upgrade first!
