### ISSUE TITLE
Import History description of transactions

### ISSUE THREAD

**Issue by filippogasbarro** [spesmilo/electrum#2018]
Now there is only the option to export the history, can you please add the feature to import the history?

Thank you

**Comment by kyuupichan** [comment]
Lol

**Comment by filippogasbarro** [comment]
Why LOL? I don't won't to lost my history details of my transactions :P

**Comment by micromatrix14** [comment]
Hahahaha, dammit you made my day lol xD

**Comment by dabura667** [comment]
lol

**Comment by filippogasbarro** [comment]
Now is written better

**Comment by ecdsa** [comment]
see "import labels"

**Comment by filippogasbarro** [comment]
Excuse me, but where is import labels?

**Comment by ecdsa** [comment]
in the menu

**Comment by micromatrix14** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22969054/20059646/ee960da4-a4ff-11e6-8c17-5f85e14eb279.jpg)
Here ya go man 👍 :)

**Comment by micromatrix14** [comment]
and ecdsa, please be more interactive with us =D 
you are the developer of the wallet, we are users, you know everything, we don't :)
Have a good time :)
Electrum is very awesome wallet, and we like it, so best regards :)

**Comment by filippogasbarro** [comment]
Ok Thank you :)

So, by exporting the history is not possible to import in labels? The only way to import is by exporting the labels?

**Comment by micromatrix14** [comment]
Yes because the electrum wallet automatically get the history, when you have internet.
exporting history is just to read it on another pc without interent or even with internet but with different wallet

**Comment by micromatrix14** [comment]
history is related to each address, and the history is never been gone in the blockchain
so what electrum do, is checking each address in the blockchain, and import the history in your local wallet interface

**Comment by filippogasbarro** [comment]
@micromatrix14 yes I know that the history is knowed by all the people in the world that know my Bitcoin address, thanks by the public register (blockchain). What I say from the start is the description for all the transaction and is closely reserved and not exists in the blockchain because is a local change. For example transaction xxxxxx with xx BTC have the description "Hotel reservation".

**Comment by micromatrix14** [comment]
Yes you can save you descriptions by exporting labels ,and restore that using importing labels
but history only exporting, importing is done automatically by electrum wallet from the blockchain
