### ISSUE TITLE
bitcoins did not arrive to my electrum account

### ISSUE THREAD

**Issue by vale7777** [spesmilo/electrum#2019]
Hi,
now nearly a month passed, and the 0,05 bitcoins haven´t arrived at my electrum wallet.
This is the address where I have sent them successfully to:
1LQgqiC8WhnJmsMBdSnkq139BdvRseTTFk 
maybe the problem is, that I haven´t saved the address at my electrum wallet.
please help
 regards
vale7777

**Comment by ecdsa** [comment]
why is this an Electrum issue?
