### ISSUE TITLE
Transaction reversed? Error message about fees

### ISSUE THREAD

**Issue by timotej777** [spesmilo/electrum#2020]
So I made this transaction, it was pending and my money came back to my account:

https://blockchain.info/tx/ba05d41b878bc6a2f9b47c7ddf141cd2b6af830f991adf475549c267dff6903b

However, when I try to make a payment again, I get an error about a min fee even though I can cover it (there was another topic created about this issue).

**Comment by ecdsa** [comment]
please post the exact error message

**Comment by ecdsa** [comment]
closing, no answer.
