### ISSUE TITLE
Search shortcut should be CTRL+F

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#2025]
In every text editing software, and in every browser, when you search for a text, the shortcut buttons are CTRL+F, so why not use that too in electrum.

It would be easier for newbies to get used to it, with familiar button combinations. So the search function shortcut should be CTRL+F.

Perhaps "search" could be renamed "find", but at least the shortcut combination should be changed.

**Comment by ecdsa** [comment]
ever used emacs?

**Comment by dabura667** [comment]
I would say a larger number of users are accustomed to Ctrl + F than whatever emacs uses.
