### ISSUE TITLE
Send button

### ISSUE THREAD

**Issue by Freddyturk** [spesmilo/electrum#2027]
Hi,
I am having issues with Electrum 2.7.11 macOS. I fill the address, amount, fee and press send.. Nothing happens!
Thank you in advance

**Comment by Freddyturk** [comment]
I've tried to restore my wallet using seeds, tried to send bitcoin, still same issue: Either Invalid fee or send does nothing.
Would really appreciate some help.
Cheers

**Comment by ecdsa** [comment]
could you publish the master public key? (or email it to me if you don't want it to be published)

**Comment by Freddyturk** [comment]
I would prefer to email it to you if that's possible
Thank you so much for your reply

**Comment by Freddyturk** [comment]
Thank you for your message, really appreciate it.
Should I email it here?

**Comment by ecdsa** [comment]
thank you. I can reproduce the problem.

**Comment by ecdsa** [comment]
fixed. this bug affects mining payouts.
