### ISSUE TITLE
could not display bitcoin address on Receive Tab with "watch bitcoin addresses" wallet

### ISSUE THREAD

**Issue by tim-le** [spesmilo/electrum#2031]
on android, create a new none default_wallet wallet and import a new btc address,  then relaunch app and open this new wallet, tap the Receive tab, hope you can reproduce it

**Comment by ecdsa** [comment]
you have to create a new request, use the 'new' button

**Comment by tim-le** [comment]
I tried, told me 'please use the existing requests first', but actually there isn't any requests existing in tab:Request

**Comment by ecdsa** [comment]
ok, sorry. save the current request and create a new one.
I know it's a bit awkward, it will be improved soon.

**Comment by ecdsa** [comment]
ok, I can reproduce your issue now. thanks for the report.

**Comment by ecdsa** [comment]
note: it occurs only when the imported address has already been used

**Comment by ecdsa** [comment]
note 2: it occurs on desktop too, not just on android
