### ISSUE TITLE
Create new wallet from one private key → no signing of messages possible

### ISSUE THREAD

**Issue by toxicacd** [spesmilo/electrum#2034]
In a wallet (non HD) with imported private keys I am unable to sign messages.
After entering the correct password a dialog box like this appears, nothing gets signed.
Using Eletrum 2.7.12

![electrum](https://cloud.githubusercontent.com/assets/6892215/20230256/4f8ba5a2-a85b-11e6-8e31-6eaaa0317773.PNG)

**Comment by spacz80** [comment]
I reproduce the same issue. There is no problem to encrypt a message or to verify a signature, so it seems that the problem is only in the password required operations. As @toxicacd says no problem with HD wallets only with imported key(s) ones

**Comment by gits7r** [comment]
Thanks - this is important. The problem doesn't occur on normal wallets as well.

**Comment by birdie-github** [comment]
@ecdsa 

I'd love you to give this bug the highest priority if possible.

**Comment by kwaaak** [comment]
Happens on 2.7.12 on OS X as well.
Imported key wallet, not password protected

**Comment by birdie-github** [comment]
@ecdsa 

Any updates on this one? It's mission critical for many of us :-(

**Comment by gg2001** [comment]
Same problem still happening for me.

**Comment by birdie-github** [comment]
@gg2001 this bug was fixed in trunk 24 days ago. Wait for a new official release.

**Comment by ecdsa** [comment]
@birdie-github there have been several releases since it has been fixed.
