### ISSUE TITLE
Watch only bitcoin address copy paste minor bug

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#2035]
When you create a` Watch Bitcoin Addresses` type of wallet and watch a bitcoin address, then you can copy the latest transaction ID from below it (in Addresses Tab) with CTRL+C, yet when you right click no menu pops up.

So I suggest that when you **right click** on the Watch Only address's transaction ID at least a menu should show up with a `Copy` button in it, so that people should know that you can copy that txid.

**Comment by ecdsa** [comment]
wontfix ; I will add a separate tab for UTXOs
