### ISSUE TITLE
Show Addresses Tab by default

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#2036]
I see that the Addresses tab was set to be hidden by default. I think this is not good, many people like to organize their transactions in the address tab, and when a newbie creates an new wallet for himself, he should know the addresses he has.

The receive tab is a bit complicated, it creates an invoice TX which I dont know how it works (never used it myself). **It creates a false sense in newbies that bitcoin transactions are pull type, when in reality it's push. We need to teach this to newbies what is the difference between Creditcard TX and BTC TX.**

But when I used Electrum for first time, I had no problem understanding what Bitcoin addresses were.

Perhaps we could add a warning for people to not reuse the addresses, but otherwise I dont see the point of keeping the Addresses tab hidden.

**Here is an idea:**

- Make Precerences>Transactions>Coin Selection:  `Privacy` by default, so that addresses are not reused by default
- Make Addresses tab visible again.

So this way a newbie who doesnt not understand what he is doing can't mess things up, all addresses are his/hers, and he can receive money to any of them, and when money is sent it will not be reused.

**Comment by ecdsa** [comment]
I disagree. 
btw, selecting the privacy coin selection policy will not prevent users from reusing addresses.
