### ISSUE TITLE
Tab Indexes

### ISSUE THREAD

**Issue by deviratech** [spesmilo/electrum#2037]
When I send or receive payments I like using tab to traverse the fields but as it stands the tab indexes are somewhat out of order.

To replicate, make sure the the following conditions are true:

- You are in the send tab.
- You have the exchange rates plugin enabled.

**Currently the tab order is:**  Pay to -> Description -> Amount (BTC) -> Send -> Clear -> Amount (USD)
**It should be changed to:** Pay to -> Description -> Amount (BTC) -> Amount(USD) -> Send -> Clear

Also, if the above conditions are true and you also enable set transactions fees manually,
**the tab order is:**  Pay to -> Description -> Amount (BTC) -> Fee (BTC) -> Send -> Clear -> Amount (USD)
**it should be:** Pay to -> Description -> Amount (BTC) -> Amount(USD) -> Fee(BTC) -> Send -> Clear

**Comment by ecdsa** [comment]
I think this is because the Fiat amount field is added by plugin.
I plan to merge the exchange rates plgin into the main code, so this issue should disappear
