### ISSUE TITLE
can't send from my wallet

### ISSUE THREAD

**Issue by KevinDesloges** [spesmilo/electrum#2038]
nothing happen when i press send, i tryed check dynamic fees then it say "invalid fee"

**Comment by gits7r** [comment]
Please provide a screenshot. Also try a with a different server. Let us know the exact steps to reproduce.

**Comment by ecdsa** [comment]
it's probably the same bug as #2027 ; please use the latest version

**Comment by KevinDesloges** [comment]
it finaly worked, i dont know exactly what caused this but i desinstalled it then reinstalled twice and been able to send my coins

**Comment by ecdsa** [comment]
closing. it would have been more useful to provide a screenshot.
