### ISSUE TITLE
Notification alert when transaction confirmed

### ISSUE THREAD

**Issue by chris-belcher** [spesmilo/electrum#2040]
A useful feature for Electrum could be to be able to notify the user when a desired number of confirmations has been reached. For example the user could right-click a transaction on the History tab and tell Electrum to emit a sound, or start blinking, when 3 confirmations are reached.

I've been reading a little around forums where people use bitcoin for commerce. A lot of people's workflow involves broadcasting a transaction then waiting around for it to confirm before handing over the goods. It would improve user experience if they could set this alert, the minimize Electrum and do something else like check their emails.

**Comment by paintballpanda** [comment]
Would also appreciate some sort of desktop notificatio when a transaction is received/confirmed on Electrum.

**Comment by shsmith** [comment]
There is already a mechanism to show toast notifications.
https://github.com/spesmilo/electrum/blob/23e51e7c9e74960642a9c34f8896372b9710e84d/gui/qt/main_window.py#L518-L544
https://github.com/spesmilo/electrum/blob/08fd7d95ab663cd0f6be02d6e4b7fd0b0c0f631b/gui/kivy/main_window.py#L600-L610
I have seen it work occasionally, but usually not.

**Comment by bauerj** [comment]
This was resolved in #3361 and #3366.
