### ISSUE TITLE
 Include a proper license header in source files

### ISSUE THREAD

**Issue by hegjon** [spesmilo/electrum#2041]
It would make it easier to redistribute Electrum if each source file contains a license header.

The following source files are without license headers:
Electrum-2.7.12/gui/kivy/i18n.py
Electrum-2.7.12/gui/kivy/main_window.py
Electrum-2.7.12/gui/kivy/nfc_scanner/scanner_android.py
Electrum-2.7.12/gui/kivy/nfc_scanner/scanner_dummy.py
Electrum-2.7.12/gui/kivy/uix/combobox.py
Electrum-2.7.12/gui/kivy/uix/context_menu.py
Electrum-2.7.12/gui/kivy/uix/dialogs/amount_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/bump_fee_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/checkbox_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/choice_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/fee_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/fx_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/installwizard.py
Electrum-2.7.12/gui/kivy/uix/dialogs/label_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/nfc_transaction.py
Electrum-2.7.12/gui/kivy/uix/dialogs/password_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/qr_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/qr_scanner.py
Electrum-2.7.12/gui/kivy/uix/dialogs/question.py
Electrum-2.7.12/gui/kivy/uix/dialogs/seed_options.py
Electrum-2.7.12/gui/kivy/uix/dialogs/settings.py
Electrum-2.7.12/gui/kivy/uix/dialogs/tx_dialog.py
Electrum-2.7.12/gui/kivy/uix/dialogs/wallets.py
Electrum-2.7.12/gui/kivy/uix/drawer.py
Electrum-2.7.12/gui/kivy/uix/gridview.py
Electrum-2.7.12/gui/kivy/uix/menus.py
Electrum-2.7.12/gui/kivy/uix/qrcodewidget.py
Electrum-2.7.12/gui/kivy/uix/screens.py
Electrum-2.7.12/gui/qt/amountedit.py
Electrum-2.7.12/gui/qt/console.py
Electrum-2.7.12/gui/qt/icons_rc.py
Electrum-2.7.12/gui/qt/installwizard.py
Electrum-2.7.12/gui/qt/qrcodewidget.py
Electrum-2.7.12/gui/qt/qrtextedit.py
Electrum-2.7.12/gui/qt/util.py
Electrum-2.7.12/gui/stdio.py
Electrum-2.7.12/gui/text.py
Electrum-2.7.12/lib/msqr.py
Electrum-2.7.12/lib/paymentrequest_pb2.py
Electrum-2.7.12/lib/simple_config.py
Electrum-2.7.12/lib/tests/test_account.py
Electrum-2.7.12/lib/tests/test_bitcoin.py
Electrum-2.7.12/lib/tests/test_interface.py
Electrum-2.7.12/lib/tests/test_mnemonic.py
Electrum-2.7.12/lib/tests/test_simple_config.py
Electrum-2.7.12/lib/tests/test_transaction.py
Electrum-2.7.12/lib/tests/test_util.py
Electrum-2.7.12/lib/tests/test_wallet.py
Electrum-2.7.12/lib/version.py
Electrum-2.7.12/plugins/audio_modem/qt.py
Electrum-2.7.12/plugins/exchange_rate/exchange_rate.py
Electrum-2.7.12/plugins/exchange_rate/kivy.py
Electrum-2.7.12/plugins/exchange_rate/qt.py
Electrum-2.7.12/plugins/keepkey/client.py
Electrum-2.7.12/plugins/keepkey/cmdline.py
Electrum-2.7.12/plugins/keepkey/keepkey.py
Electrum-2.7.12/plugins/keepkey/qt.py
Electrum-2.7.12/plugins/labels/kivy.py
Electrum-2.7.12/plugins/labels/labels.py
Electrum-2.7.12/plugins/labels/qt.py
Electrum-2.7.12/plugins/ledger/cmdline.py
Electrum-2.7.12/plugins/ledger/ledger.py
Electrum-2.7.12/plugins/ledger/qt.py
Electrum-2.7.12/plugins/plot/qt.py
Electrum-2.7.12/plugins/trezor/client.py
Electrum-2.7.12/plugins/trezor/clientbase.py
Electrum-2.7.12/plugins/trezor/cmdline.py
Electrum-2.7.12/plugins/trezor/plugin.py
Electrum-2.7.12/plugins/trezor/qt.py
Electrum-2.7.12/plugins/trezor/qt_generic.py
Electrum-2.7.12/plugins/trezor/trezor.py
Electrum-2.7.12/plugins/trustedcoin/cmdline.py
Electrum-2.7.12/plugins/virtualkeyboard/qt.py
Electrum-2.7.12/scripts/bip70
Electrum-2.7.12/scripts/block_headers
Electrum-2.7.12/scripts/estimate_fee
Electrum-2.7.12/scripts/get_chunk
Electrum-2.7.12/scripts/get_donation_address
Electrum-2.7.12/scripts/get_history
Electrum-2.7.12/scripts/peers
Electrum-2.7.12/scripts/servers
Electrum-2.7.12/scripts/txradar
Electrum-2.7.12/scripts/util.py
Electrum-2.7.12/scripts/watch_address
Electrum-2.7.12/setup-release.py

Can you confirm the licensing of code and/or content/s and to add license headers? https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Check https://bugzilla.redhat.com/show_bug.cgi?id=1187084#c26 for more details.

**Comment by hegjon** [comment]
Electrum-2.7.12/lib/socks.py is licensed as BSD (2 clause)

**Comment by ecdsa** [comment]
Electrum is under the MIT licence.
the socks.py file was removed from the repo because it is now provided by PySocks
