### ISSUE TITLE
Electrum daemon persists in pointless resends

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#2044]
Suppose you request something expensive from the command line:

$ ./electrum getaddresshistory 135zDqhbNcmPk3gbyeJmH75yiLdVZechsK

This address has a long history and the server is unlikely to be able to deliver it quickly.  Electrum daemon is quite impatient and disconnects quite quickly from the server if it doesn't get a response.  The error is then reported to the command line.

But the daemon remembers the request and that it failed, and will reconnect to a server and send the request again.  And disconnect impatiently, etc.  But it no longer even has a reason to be requesting this as it has already told the command line user the request has failed.

At least, this is the behaviour I seem to observe.  The only solution is to kill the daemon.

**Comment by ecdsa** [comment]
this is not specifc to the daemon; the client does it too.

**Comment by Lastrellik** [comment]
>$ ./electrum getaddresshistory 135zDqhbNcmPk3gbyeJmH75yiLdVZechsK

I just tried running that command and rather than it disconnecting and reconnecting I get a "response too large (at least 1020631 bytes)" exception. I wonder if this has already been taken care of and if this is the result we expect. What do you think, @bauerj?

**Comment by helpau** [comment]
It is not reproducible for me. I used electrum 4.4.6 for the topk-starter address and for the address with ten transactions. In Wireshark I didn't see any repeated requests, excluding periodic requests from the daemon to different IPs. For address 135zDqhbNcmPk3gbyeJmH75yiLdVZechsK I get The server returned an error.

**Comment by ecdsa** [comment]
thanks for testing this. this issue is quite old, I guess the code has changed a lot.
closing it.
