### ISSUE TITLE
Android: importing public key for watch only wallet

### ISSUE THREAD

**Issue by psb777** [spesmilo/electrum#2046]
The following problem happens when taking the third option on a new install - not the first.

On Android creating a watch-only wallet, upon either (1) scanning the QR-code obtained from desktop Electrum for the public key for any particular address, or for the wallet's master public key, or (2) pasting that key, the "Next" button is left greyed out, unable to click. 

I deleted and re-installed the Electrum App from the Google Play store.
I rebooted the phone.
No improvement.

Android 6.0.1 
OnePlus One A0001
Cyanogen 13.1.2 "bacon"

**Comment by ecdsa** [comment]
the public key of an address is not usable by the wizard.
as you can read on the screen, you have to use the master public key (xpub) of the wallet, or a list of bitcoin addresses.

**Comment by ecdsa** [comment]
note: to use the master public key, you need to select the first option 'standard wallet' then the 3rd.
