### ISSUE TITLE
Android: minor usability issue on startup

### ISSUE THREAD

**Issue by psb777** [spesmilo/electrum#2047]
Upon firing up Electrum on Android there is initially a long unexplained delay. This is true when the app is first installed but also afterwards. I guess a server is being contacted and block headers downloaded. But I do not know and I am not told and I think this is disconcerting especially for new users. When 20 secs pass one is likely to conclude something is broken with the app. I would suggest a "please wait, downloading blockchain headers" with a %age complete indicator would be a minor but important improvement to the app. Also that blue Electrum atom logo is particularly ugly low res.

**Comment by ecdsa** [comment]
The long startup time is not caused by a server being contacted; 
If that was the case it would be similarly long to start the desktop version.

I believe the long startup time is needed to load the Kivy/p4a environment.
@akshayaurora can we improve on this?

**Comment by ecdsa** [comment]
fixed in  bc70513
