### ISSUE TITLE
'NoneType' object has no attribute 'get' when i send Bitcoin

### ISSUE THREAD

**Issue by Adrenokrome** [spesmilo/electrum#2050]
Hello, 
I have problem with electrum, when i send Bitcoin, a windows appear with: 'NoneType' object has no attribute 'get.
I need help.
Thank

**Comment by ecdsa** [comment]
which version of Electrum do you use?

**Comment by ecdsa** [comment]
can you provide a full screenshot?

**Comment by ecdsa** [comment]
can you please check if this is fixed in the latest version?

**Comment by ecdsa** [comment]
closing, OP not answering
