### ISSUE TITLE
Feature Request - Fee sat/byte value on send or preview screen.

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#2051]
This would make it more helpful in judging if a good fee is included. I'd be willing to make a pull request for this if it will be merged. I won't bother if it will be ignored. I'd like input on whether better on the Tx Preview pop up or the actual Send screen next to fee value.

**Comment by ecdsa** [comment]
the fee per kb is already display as a tooltip on the dynamic fee slider.
how would that differ?

**Comment by dabura667** [comment]
> the fee per kb is already display as a tooltip on the dynamic fee slider.

Yes, but it would be nice to double check and make sure that the actual fee subtracted from the change worked out to the correct fee per kb.

I agree it would be nice to have an extra line on the transaction preview (broadcast) screen that shows the precise fee and precise fee per kb that was actually allocated to the tx data in question.

A lot of people use Electrum for high value transactions, and adding pertinent information at every step is a good idea to double check before sending.

**Comment by neocogent** [comment]
I'd like to manually double check values as I've been bitten before by being mixed up in difference between mbtc/KB and sat/byte. It would be very clear if the preview stated byte size and sat/byte used for fee. Otherwise I have to mentally try and figure out what sat/byte actually is and the tx byte size is not disclosed. So then it's kind of a guess - oh, 1 in/ 2out maybe that's about 250 bytes.

As mentioned I have a couple times sent a tx and then realized afterwards the fee was not what I expected. I'd just like to avoid this kind of surprise by having plainly stated fee details on the preview screen. That is, after all, the purpose of Preview - to doubel check everything is as expected. I don't think this should involve mental gymnastics or ambiguity about tx size in bytes.

**Comment by dabura667** [comment]
@neocogent I disagree with using satoshi/byte instead of bitcoin/kilobyte. Electrum has been using bitcoin/kilobyte since a long time ago, and suddenly changing it without notice would probably confuse more users than it helps.

to convert bitcoin/kilobyte to satoshi/byte, just move the decimal point over to the right 5 times.

0.0001 bitcoin/kilobyte = 10 satoshi/byte  (imagine extra 0 after the 1)

**Comment by neocogent** [comment]
That's odd. On mine it displays mbtc/kB. So maybe it uses whatever unit you choose in preferences. That's fine. My main point is that currently it doesn't display it in the preview and not the byte size either. Both should be available for checking without having to mentally calculate it or get out a calculator. I'd prefer sat/byte only because that's commonly used on sites that show mempool activity so it's easy to compare.

**Comment by neocogent** [comment]
I've added a pull request with very simple update to transaction details dialog.

Shows extra fee info in brackets as: ( byte size, base_unit/kB, sat/byte )

**Comment by ecdsa** [comment]
thanks, I merged your PR
