### ISSUE TITLE
BTC Inaccessible - Invalid Fee v2.7.12 for Windows

### ISSUE THREAD

**Issue by InvalidFee** [spesmilo/electrum#2052]
Hi, I am trying to send some bitcoins to an online exchange to sell them. However, I keep getting an error message that I have never seen before:

![invalid fee error](https://cloud.githubusercontent.com/assets/23711735/20585017/876d8336-b243-11e6-8708-842c945a0097.JPG)

When I am in the send section I copy the address (no spaces), and I enter the amount i wish to send.

Now, whether I click preview or send I get the same error message: "Invalid Fee".

This is how I have my dynamic fee settings:

![dynamic fee setting](https://cloud.githubusercontent.com/assets/23711735/20585046/bcfe4594-b243-11e6-9e99-04496370e41d.JPG)

 I have had successful transactions before where everything went perfectly using the exact set up I have now. The last transaction I did was the 1st of October, so there may have been updates or something since then. However, as you can see I have already updated my client to 2.7.12.

Please tell me if you need any more screengrabs!

Thanks!

**Comment by ecdsa** [comment]
can you retry now? there's been a server side issue with 2fa yesterday

**Comment by ecdsa** [comment]
no answer from OP, so I'm closing this.
