### ISSUE TITLE
PLEASE HELP - Unconfirmed transactions

### ISSUE THREAD

**Issue by lextao1** [spesmilo/electrum#2053]
im trying to send a payment on my wallet and its not getting confirm.
can you kindly assist?
Transaction unconfirmed on my wallet,

**Comment by klarkis** [comment]
a similar situation and I have (
Sent from a wallet on the  exchange BTC, more than 24 hours is not confirmed (

**Comment by ecdsa** [comment]
this is not an electrum issue.
use dynamic fees, and learn how bitcoin works.

**Comment by klarkis** [comment]
I understand it . Dynamic commission is worth.
