### ISSUE TITLE
Transaction still uncomfirmed..

### ISSUE THREAD

**Issue by unreaLx33** [spesmilo/electrum#2054]
My transactions are still uncomfirmed, they were sent like 2-3 days ago.. and I don't know what to do

https://blockchain.info/tx/bcc7b7252669528e6d9b3f2ecd5edf6ee850905577de1419600a4101aee25be5
https://blockchain.info/tx/c644cf8ea0a4d7d893f5170f73a1c149789f7f4f2297a2d8b771062e12ed31b2
https://blockchain.info/tx/6c66d711bb28ff0ad4dbfddd52d7421aa34765a83e28ffdcd28eca119696e198
https://blockchain.info/tx/34ee0e8f23093d752e90e4b9b859135bdbf918a4ccf9b97ad165053c8ec324d0

**Comment by micromatrix14** [comment]
they are confirmed dude :)

**Comment by micromatrix14** [comment]
They are confirmed :)
