### ISSUE TITLE
Electrum does not re-sync after computer sleep (OS X)

### ISSUE THREAD

**Issue by sime** [spesmilo/electrum#2055]
I experience Electrum not syncing when I awake in OS X computer from a sleep.

Steps to reproduce:

1. Open wallet that is synced
2. Take note of an receiving address that has a zero balance.
3. Sleep computer
4. Send transaction to an above address
4. Awaken computer
5. Note this new transaction hasn't arrived in the wallet

If Electrum is exited, and re-opened the wallet will sync and the new transaction will be visible.

**Comment by ecdsa** [comment]
I can confirm that. I have been tying to fix it for a long time.

**Comment by lupa18** [comment]
Here the same, with version 2.7.18 and Ubuntu based Linux. 

I think with previous versions it worked well.

**Comment by bauerj** [comment]
I just tried it and it seems to work now. Not sure if I've left it in sleep mode long enough though. Please reopen if the issue persists.
