### ISSUE TITLE
High Fee Warning Should Take Transaction Size Into Account

### ISSUE THREAD

**Issue by paintballpanda** [spesmilo/electrum#2060]
Currently it seems that electrum gives the warning/prompt:

> The fee for this transaction seems unusually high.

based upon the total BTC amount of the fee rather than the fee in terms of BTC/KB. It does not seem that transaction size is taken into account when determining if a fee is too high.

With fees reaching 100 satoshis/byte or higher currently, it would be more accurate for electrum to only show this warning when the fee is larger than it should be after taking transaction size into account.

**Comment by dabura667** [comment]
+1

I would set two limits:

1. Hard coded warning limit @ 10,000 sat/byte ( 0.1 BTC per kB ) (If the fee market gets this large and people are still using bitcoin transactions directly, we can always change it later down the line)
2. Changing warning limit based on the recommended fee per kB given by the server. (I would say anything 10x more than the recommended fee of the server would be a good place to throw a warning)

So even if the recommended fee was 0.2 BTC per kB, the hard coded limit in 1 would trigger.

**Comment by gits7r** [comment]
I don't see any benefits of a hard coded warning limit. How is it actually helpful? Usually hard coded limits should be avoided, they provide only pain in the future and the additional worry that it needs to be modified in some scenarios. It's fine to use a warning for something 10x more than the recommended fee of the server.

**Comment by ecdsa** [comment]
@gits7r without hard coded limits, the server can recommend arbitrarily large values to the client.
