### ISSUE TITLE
no module named jnius

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#2063]
When trying to convert a wallet

Traceback (most recent call last):
  File "/home/neil/src/electrum/electrum", line 338, in <module>
    d.init_gui(config, plugins)
  File "/home/neil/src/electrum/lib/daemon.py", line 253, in init_gui
    self.gui.main()
  File "/home/neil/src/electrum/gui/qt/__init__.py", line 204, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/home/neil/src/electrum/gui/qt/__init__.py", line 165, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/neil/src/electrum/gui/qt/installwizard.py", line 157, in run_and_get_wallet
    file_list = '\n'.join(self.storage.split_accounts())
  File "/home/neil/src/electrum/lib/storage.py", line 210, in split_accounts
    storage2.upgrade()
  File "/home/neil/src/electrum/lib/storage.py", line 222, in upgrade
    self.convert_wallet_type()
  File "/home/neil/src/electrum/electrum", line 33, in <module>
    import jnius
ImportError: No module named jnius

**Comment by kyuupichan** [comment]
The cause is the lame naked raise in convert_wallet_type()

The fix is

        elif wallet_type in ['trezor', 'keepkey', 'ledger', 'bip44']:

where bip44 is new

**Comment by kyuupichan** [comment]
Except that then fails complaining about unknown wallet types.

2.7 has been an extremely frustrating experience.

**Comment by ecdsa** [comment]
that's not the correct way to fix it; you need to create a 'bip32' keystore.
that 'elif' branch creates a 'hardware' keystore.

**Comment by ecdsa** [comment]
would the following patch fix it?
```
--- a/lib/storage.py
+++ b/lib/storage.py
@@ -275,6 +275,19 @@ class WalletStorage(PrintError):
             self.put('wallet_type', 'standard')
             self.put('keystore', d)
 
+        elif wallet_type in ['bip44']:
+            xpub = xpubs["x/0'"]
+            xprv = xprvs.get("x/0'")
+            derivation = self.get('derivation', bip44_derivation(0))
+            d = {
+                'type': 'bip32',
+                'xpub': xpub,
+                'xpub': xprv,
+                'derivation': derivation,
+            }
+            self.put('wallet_type', 'standard')
+            self.put('keystore', d)
+
         elif wallet_type in ['trezor', 'keepkey', 'ledger']:
             xpub = xpubs["x/0'"]
             derivation = self.get('derivation', bip44_derivation(0))

```

**Comment by shsmith** [comment]
I have an old ledger wallet file that generates the same traceback when attempting to split.
inside the wallet I see this:
>   "wallet_type": "bip44", 

I think the wallet is empty, but no way to tell since I can't open it.
Same thing in both 2.7.12 and git-head.

**Comment by ecdsa** [comment]
@shsmith please let me know if this fixes it.
