### ISSUE TITLE
No signature generated to sign message

### ISSUE THREAD

**Issue by delivbuds** [spesmilo/electrum#2064]
I have updated to the most recent version 2.7.12 wallet 2fa on mac. I am trying to sign a message using a previously used receiving address. When I hit "Sign", it asks for password, after providing the password, the signature field remains empty.

**Comment by ecdsa** [comment]
https://www.reddit.com/r/Electrum/comments/5g7r4l/no_signature_generated_to_sign_message/

**Comment by ecdsa** [comment]
todo: gray the 'sign' button when a message cannot be signed
