### ISSUE TITLE
what is wallet hd path?

### ISSUE THREAD

**Issue by eMosbat** [spesmilo/electrum#2069]
I am creating an online bitcoin service. I do not like to ask users to provide me private keys or generate and store them in my server. I like to ask users to send me an xpub and generate addresses from it.
I like that generated address appears immediately in electrum so I should use same BIP32 path that electrum use? so what path electrum use? currently I generate using `bx` tool using this path:
```
    M/x/y
    x = user id
    y = address index

   cat xpub | bx hd-public -i x | bx hd-public -i y | bx hd-to-address


```
what should be path and  command?

**Comment by ecdsa** [comment]
electrum generates addresses directly from the provided xpub: m/change/index

**Comment by eMosbat** [comment]
thanks. will electrum display recieved addresses automatically or it only show first 20 addresses and we should tell user add addresses?

**Comment by ecdsa** [comment]
it uses a 'gap limit'. please read the docs.
