### ISSUE TITLE
Could you use xor to add custom entropy without letting users shoot themselves in the foot?

### ISSUE THREAD

**Issue by n8n3k** [spesmilo/electrum#2070]
As I understand you don't let users add custom entropy because a user might just type 12345 and think they're clever.

Could you let people automatically add custom entropy, using the xor function to combine the custom entropy with the generated entropy?

This wouldn't reduce the entropy even if the user typed in "1111" and thus couldn't hurt.

**Comment by AbdussamadA** [comment]
you can add entropy using the command line option "make_seed". type `electrum help make_seed` to learn more. the entropy has to be provided as a decimal number

There is also the option to extend the seed with your own custom words. You can do that in the gui wallet creation wizard.

**Comment by ecdsa** [comment]
indeed, see @AbdussamadA answer.
