### ISSUE TITLE
NoneType oject has no attribute 'get' when sending bitcoins 2.7.12

### ISSUE THREAD

**Issue by kiersrj** [spesmilo/electrum#2072]
When trying to send bitcoins i get the error above. Attached is a screenshot.

![electrum-error](https://cloud.githubusercontent.com/assets/24459411/21017920/db987b62-bd62-11e6-8695-28d6dba1d366.PNG)

**Comment by ecdsa** [comment]
can you provide full details ? (wallet type, etc)

**Comment by CoolBlackFriend** [comment]
I'm helping kiersrj with this issue. When you say wallet type, what do you mean? The user is running Electrum 2.7.12 on Windows 10, and using the electrum exe file.

**Comment by ecdsa** [comment]
does the wallet have a seed?

**Comment by ecdsa** [comment]
closing since duplicate of #2050

**Comment by ecdsa** [comment]
can you provide a full screenshot?
