### ISSUE TITLE
FEATURE REQUEST SOCKS5 Proxy With Authentication

### ISSUE THREAD

**Issue by mamamia88** [spesmilo/electrum#2073]
I have a paid vpn/proxy combo and would like to be able to route electrum through the proxy rather than connecting my entire machine to the vpn. It would be nice if it was possible to login to my proxy to connect.

**Comment by ecdsa** [comment]
how would that differ from wht we currently have?

**Comment by mamamia88** [comment]
There is no field to fill in your username and password

**Comment by desantis** [comment]
@mamamia88 I implemented this last night. I'll submit a PR later tonight.

**Comment by ecdsa** [comment]
thanks! looking forward to it

**Comment by mamamia88** [comment]
Any update on said pull request @desantis

**Comment by desantis** [comment]
@mamamia88 cleaning as we speak. Sorry, a few other things popped up.
