### ISSUE TITLE
problems with google authenticator

### ISSUE THREAD

**Issue by edyfab** [spesmilo/electrum#2077]
hi recently I tried to transfer some bitcoins but when it`s asking me for google authenticator code it`s telling me it`s incorrect. Can I get some advices please now my btc are stuck ...
that happened with electrum wallet 2.7.12
![untitled](https://cloud.githubusercontent.com/assets/24556674/21166096/57091ea0-c19b-11e6-9790-e86aa2df77a3.png)

**Comment by edyfab** [comment]
that happened with electrum wallet 2.7.12

**Comment by edyfab** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24556674/21165685/d06e5dbc-c198-11e6-87d9-24b1b9e676d0.png)

**Comment by ecdsa** [comment]
it's your password that is incorrect, not your google auth code.
if you lost your password, you need to restore from seed.

**Comment by edyfab** [comment]
can you explain me how to do that please? I`m newbie in this kind of wallets. Should i restore the account ?
 

    On Wednesday, December 14, 2016 7:20 AM, ThomasV <notifications@github.com> wrote:
 

 it's your password that is incorrect, not your google auth code.
if you lost your password, you need to restore from seed.—

**Comment by ecdsa** [comment]
read the documentation please

**Comment by edyfab** [comment]
Hi again look i tried to recover my account with the seed but when i`m trying to restore the wallet is just telling me please wait and that`s it i`m waiting and waiting but for nothing  

    On Wednesday, December 14, 2016 7:08 PM, ThomasV <notifications@github.com> wrote:
 

 read the documentation please—

**Comment by edyfab** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24556674/21242151/d8c6cbca-c30a-11e6-8d56-17f9d79248d3.png)

**Comment by edyfab** [comment]
sort it out thank you for all help

**Comment by ecdsa** [comment]
could clarify? does "sort it out" mean "I sorted it out", or "please sort it out" ?
