### ISSUE TITLE
unable to restore and remove 2FA

### ISSUE THREAD

**Issue by utiee** [spesmilo/electrum#2080]
hi,

I have Electrum 2.7.12 installed. recently upgraded (can't remember previous version

I am trying to follow the restore process.

File->new/Restore->Wallet Name
select wallet with 2FA->I already have a seed
Entered the 13 word seedm, select options ->BIP39 Seed->disable 2FA->next

I have the original 13 word seed phrase, but when i complete the wizard it gets stuck and shows the attached screen. I have waited for over 5 hours and it never completes.

![electrum stuck](https://cloud.githubusercontent.com/assets/24628178/21290318/58d5da70-c501-11e6-9ca0-1b214c4fb3aa.jpg)

**Comment by ecdsa** [comment]
why did you select 'bip39 seed' in the options?

**Comment by ecdsa** [comment]
after you enter your seed, does it display 'seed type: standard' ?

**Comment by utiee** [comment]
I choose the bip39 seed option, as without it. I couldn't proceed, the Net button was greyed out.

**Comment by utiee** [comment]
with respect to the seed type, I will check when I get home.

**Comment by utiee** [comment]
yes, when i enter the seed. the seed type says 'standard'. however; the next button is greyed out

**Comment by ecdsa** [comment]
This means that your seed is not a 2FA seed.
If you have a 2FA wallet, it has a different seed.
If you want to restore a wallet from that seed, you need to select 'standard wallet' in the wizard.

the GUI should not allow you to use that seed after you select 2FA ; I will fix that.

**Comment by utiee** [comment]
Thanks, fixed issue by using the correct seed.

**Comment by ecdsa** [comment]
reopening issue; the GUI still needs to be fixed.
