### ISSUE TITLE
[FAQ] Setup LM 17.3 with Electrum 2.7.12 and Trezor 1.4

### ISSUE THREAD

**Issue by thob** [spesmilo/electrum#2088]
Install via Synaptic

* Cython
* libudev-dev

Then in the shell `sudo pip install trezor`

The launch Electrum, then  
- Create New Wallet
- Hardware

**Comment by ecdsa** [comment]
why are you opening this issue here?

**Comment by thob** [comment]
Just for the record. I was looking for a solution, and thought it might help someone.
