### ISSUE TITLE
Bitcoin URIs don't work on Mac

### ISSUE THREAD

**Issue by Jaxkr** [spesmilo/electrum#209]
Not completely sure why they aren't supported.
Bitcoin URIs are becoming more and more popular, and Electrum is by far my favorite client. However, its one downfall is that it lacks support for these convenient URIs on computers running OSX.

**Comment by larafale** [comment]
interesting thread. 5 years later, anyone know why on OSX, nothing happens when I click on a bitcoin link from a browser ? I'd like electrum to open. I'm running latest 3.0.5 electrum. It seems it requires an intervention at the OS level, but can't find any clear solution. thx for the help
