### ISSUE TITLE
wallet.create_new_address() not working

### ISSUE THREAD

**Issue by whizz** [spesmilo/electrum#2090]
Hello there. Using 2.7.13, trying to create a bunch of adresses as per http://electrum.readthedocs.io/en/latest/faq.html#how-can-i-pre-generate-new-addresses 

> If you need to pre-generate more addresses, you can do so by typing wallet.create_new_address() in the console. This command will generate one new address. Note that the address will be shown with a red background in the address tab, to indicate that it is beyond the gap limit. The red color will remain until the gap is filled.

When I enter the call into console, I get this:

```
>> wallet.create_new_address()
Traceback (most recent call last):
TypeError: create_new_address() takes exactly 2 arguments (1 given)
```

Either the function or the docs are wrong. Any help is appreciated, thanks.

Michal

**Comment by ecdsa** [comment]
`wallet.create_new_address(True)`
