### ISSUE TITLE
Monetization Idea for Electrum

### ISSUE THREAD

**Issue by RealBTC** [spesmilo/electrum#2093]
I think Electrum relies too much on donations, which is not very sustainable, and hinders it's growth. Most commercial wallets have more users, because they have more funds that they can spend on development and research. I think adding a little bit of commercial aspect to Electrum, without compromising on security is a good idea. So that Developers would have a full time income, more developers could be hired, and the Servers would have money to pay their bills, which would spawn more servers. (More Servers = More Security)

**Here is my suggestion explained in this thread:**
https://bitcointalk.org/index.php?topic=1738501.0

**Comment by ecdsa** [comment]
thanks. will answer there
