### ISSUE TITLE
Bug "Invalid Fee" vers. 2.7.13 (win7, x64)

### ISSUE THREAD

**Issue by Praga9** [spesmilo/electrum#2096]
![1](https://cloud.githubusercontent.com/assets/19350440/21647764/5ad2eb1e-d2bd-11e6-9d20-efa81a8dd52e.jpg)
"invalid fee" - message in different settings. changed the servers, commission etc. no result.
sometimes it get this message - global name "coins" is not defined 
please help fix

**Comment by ecdsa** [comment]
did you upgrade from 2.7.12 or from an earlier version?

**Comment by ecdsa** [comment]
should be fixed. will do another release as soon as I can

**Comment by Praga9** [comment]
i did no upgrade path, just download with off.site ver. 2.7.13

**Comment by Praga9** [comment]
@ecdsa i did no upgrade path, just download with off.site ver. 2.7.13

**Comment by Praga9** [comment]
@ecdsa thanks 2.7.14.
