### ISSUE TITLE
Bitcoin sent from from multisig wallet without co-signing

### ISSUE THREAD

**Issue by villabacho** [spesmilo/electrum#2098]
I set up a 2-of-2 multisig wallet with Electrum 2.7.13 on 2 devices. I then sent some BTC to this wallet's address, and it showed up on both devices, so everything looked fine.
Then I sent BTC from the first of my multisig wallet pair. After pressing the "Send" button on the "Send" tab, I would have expected that electrum asks me to co-sign it,
but instead the BTC was sent already (I confirmed that it arrived at the target address). The outgoing transaction is also seen by the second wallet of the multisig wallet pair.

I'm new to Electrum, so my question might be stupid, but at least a quick google / forum / stack exchange search didn't give me an answer.
I'm pretty sure also that I did the multi-sig setup correctly (following the [documentation](http://docs.electrum.org/en/latest/multisig.html)) and the electrum title bar also says "default_wallet [2of2]".

I wasn't sure if this is a bug or a misunderstanding on my side, so I also posted on [bitcointalk](https://bitcointalk.org/index.php?topic=1740254.msg17405445#msg17405445), hope that cross-posting is ok in this case.

**Comment by ecdsa** [comment]
you must have entered the xprv of your cosigner insteead of their xpub

**Comment by ecdsa** [comment]
closing this, since you already posted the same info on bitcointalk, and there is no evidence that this is a bug.
