### ISSUE TITLE
Error:  Electrum cannot pair with your TREZOR.

### ISSUE THREAD

**Issue by halloreneous** [spesmilo/electrum#2100]
I use Electrum 2.7.12.
I use TREZOR 1.4.0

I try to use TREZOR with Electrum but cannot.  What happening is this:

1 - Open Electrum and Electrum ask for PIN.
2 - I use PIN matrix to enter.  Okay!
3 - Electrum ask for Passphrase.
4 - I enter Passphrase (old, new, anythings is same result)
5 - I get window with error:

Electrum cannot pair with your TREZOR.
Before you request bitcoins to be sent to addresses in this wallet, ensure you can pair with your device, or that you have its seed (and passphrase, if any). Otherwise all bitcoins you receive will be unspendable.

**Comment by ecdsa** [comment]
are you sure it is the right wallet and passphrase?
a good test would be to restore your wallet in a new file, using your trezor device

**Comment by ecdsa** [comment]
closing, works for me.

**Comment by halloreneous** [comment]
Thank you for write me.  Sorry for my English.  Okay!  You say:

> are you sure it is the right wallet and passphrase?

What this is mean?  Should be possible use multiple passphrase.  Not only "right" passphrase.  Everythings I read say that if I enter different passphrase, electrum automatic to create new addresses.  Even if I do typo.

BUT is also true that is right passphrase.  I try right passphrase.  I also try new passphrase.  I get same error if right or if new.  Is possible I make mistake first time I enter passphrase and now every time I enter is not correct?  This is not usually for me but is possible.

> a good test would be to restore your wallet in a new file, using your trezor device

How I can do this?  Everythings I read say I must use only Electrum or Mycelium with TREZOR.  I have no Android.  Also I am must use TOR and this mean I cannot use myTrezor.com

Also I have new informations!  I try wipe_device and reset_device for TREZOR.  Now I have different result!  Now what is happen is different.



1: I enter original passphrase and everything is look okay!  No error, okay!



2: I enter new passphrase for create new addresses and I am get error.



But this is being MUCH better!  Is give me two things to think:



a) maybe first time I really did enter wrong passphrase and so every time I try use Electrum and TREZOR I am use wrong passphrase?  Stupid me but is possible.



b) why is not working that I enter new passphrase and it create new wallet?  Is supposed to be TREZOR working this way.  You enter wrong passphrase and you get new addresses completely.  Many passphrase using one seed.



Thank you.

**Comment by ecdsa** [comment]
a). yes, you entered a wrong passphrase.
b). it will not create a new wallet until you ask him to create a new  wallet

**Comment by halloreneous** [comment]
> a). yes, you entered a wrong passphrase.

If you sure then probably this happened.  I am sorry.  Bug is not a bug.  I am a bug.

> b). it will not create a new wallet until you ask him to create a new wallet

Can you show me manual for explain how do this?  I can create first wallet.  But do not know how I create second wallet.  I look in http://docs.electrum.org/en/latest/ but do not see anywheres.

Thank you for taking this time.

**Comment by ecdsa** [comment]
"File -> New"

**Comment by halloreneous** [comment]
> "File -> New"

No this is not work.  I try and try.  But I think I solve problem.  I should create new ticket?  Here is problem:

File, New, Standard Wallet, Hardware Device = TREZOR not detected.  But I know is working because I enter PIN only back one minute of time.  Solution: is necessary UNPLUG TREZOR.  Now "Rescan" and only this make TREZOR detect.  Enter PIN and now can enter new password.

Is same for using new wallet.  Is necessary open with old passphrase.  Now Open, <new wallet>, UNPLUG TREZOR, plug TREZOR, enter PIN, enter new password.  NOW I see new wallet.

This is bug?  This is supposed happen?  I don't see anything tell me that I should must do this so maybe is bug.

TREZOR 1.4.0
Electrum 2.7.12

Thank you for helping.

**Comment by ArbenKarb** [comment]
Got a similar problem. Created a multisig wallet using multiple Trezor and Other HW Devices. I can only pair the Trezors if **all** Trezors are connected, otherwise I get the pairing error.

**Comment by SomberNight** [comment]
@ArbenKarb You get a warning, but you can keep using the wallet, and e.g. partially sign transactions, right? If so, that is how it's intended to work.
