### ISSUE TITLE
Receiving address not updated

### ISSUE THREAD

**Issue by c-kr** [spesmilo/electrum#2101]
After upgrading from 2.7.12 to 2.7.15 electrum always shows the the first (used) address in the receiving tab (using a trezor wallet)

I need to manually click on new to get a new unused address.
![electrum1](https://cloud.githubusercontent.com/assets/1288215/21723989/d7f0c136-d432-11e6-9a88-01c1f3effd42.png)
![electrum2](https://cloud.githubusercontent.com/assets/1288215/21723990/d7f0ef8a-d432-11e6-93c6-1c25d5328194.png)

**Comment by ecdsa** [comment]
sorry about that; fixed
