### ISSUE TITLE
No mining fee generated

### ISSUE THREAD

**Issue by stilicrafter** [spesmilo/electrum#2102]
Hi.
If i type an amout , for example 0.12345 or 1.23 or something else  , it wount generate a fee.
Eaven after i move the Slider .

**Comment by ecdsa** [comment]
in your preferences select 'Edit fees manually'

**Comment by stilicrafter** [comment]
I did enable this checkbox , but then i need to calculate it myself , and i am not perfect in this .
The last calucation resulted in a 10 hour delay ! until first approve

**Comment by ecdsa** [comment]
I dont understand what you are talking about.
can you describe exactly what you are seeing and expecting?

**Comment by stilicrafter** [comment]
Please see screenshot : 
![screenshot 825](https://cloud.githubusercontent.com/assets/22886797/21750222/af47a1fa-d5ae-11e6-97df-e27a55746137.jpg)

**Comment by dabura667** [comment]
How much bitcoin are you trying to send, and how many transactions has your wallet received so far in the past?

It could be that the recommended fee > your total balance, so the fee algorithm is asking you to put in manually... maybe?

**Comment by ecdsa** [comment]
can you post a screenshot it showing "Insufficient fee, sure to send?"

**Comment by stilicrafter** [comment]
see screenshot 1 & 2 : 

![screenshot 827](https://cloud.githubusercontent.com/assets/22886797/21753664/385b18bc-d5f2-11e6-9140-3c775f47561b.png)
![screenshot 826](https://cloud.githubusercontent.com/assets/22886797/21753665/385f4e78-d5f2-11e6-9f87-459ceab1b244.png)

**Comment by ecdsa** [comment]
this is not "insufficent fee", but "invalid fee". please try to be accurate in your descriptions.

I think you are using dynamic fees and the server did not send the fee estimates properly.
are you connected to a public server?
does the issue persist if you restart electrum?

**Comment by dabura667** [comment]
Ah yes. This is "invalid fee"
https://crowdin.com/translate/electrum/68/en-de#q=Ung%C3%BCltige+Geb%C3%BChr

Invalid fee means that the server is sending you bad information, or python is choking on something for some reason.

Which method are you using for installing?
Windows installer (has install wizard like normal program)?
Windows Portable (has no installer, the exe you download runs Electrum immediately)?
Source Install from Python directly (If you don't know what python is, this is not it)?

**Comment by ecdsa** [comment]
it should be fixed in a2e7fc3
I will make a new release today

**Comment by stilicrafter** [comment]
Hi.
After a reinstall : Works now ^^
I had used the installer , but i dont use the default install location , i use D:,not C:
And yes, i restarted electrum serveral times.
And I think i use the normal servers ... I didn't change any of the settings there.
