### ISSUE TITLE
"Preferences" window doesn't show

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#2104]
Windows 7 x64, portable version, run with "-P" operator
Reproduced with 2.7.14 and 2.7.15

When clicking on the menu bar Tools > Preferences, nothing visible happens.

**Comment by leafcutterant** [comment]
It still works in 2.7.13. Maybe the exchange rate code merging caused this?

**Comment by ecdsa** [comment]
does it work if you delete your config file?

**Comment by ecdsa** [comment]
please email me your config file I can have a look

**Comment by leafcutterant** [comment]
Deleting the config file "fixes" it. I'll send you the config file soon.

**Comment by ecdsa** [comment]
thanks

**Comment by leafcutterant** [comment]
If this was merged into 2.7.15, then it doesn't fix it for me--same behavior.

**Comment by ecdsa** [comment]
2.7.15 is old. please update.

**Comment by leafcutterant** [comment]
Sorry, I typed the wrong version it. I mean 2.7.17. I tried it with the newest release and the problem persists.
