### ISSUE TITLE
Please help unconfirmed transaction

### ISSUE THREAD

**Issue by bittycoin** [spesmilo/electrum#2105]
Hi, I have used Electrum many times without a problem and today when I wanted to consolidate my wallets to one wallet by transferring between two wallets within Electrum it has been stuck on pending all day, I would usually be patient and wait longer but the transaction IDs date even says "pending". Also on blockchain the transaction cant be found. I have tried hexing it etc can someone please please help me I cant begin to imagine if I have lost that transaction...

**Comment by ecdsa** [comment]
please post the transaction id.
