### ISSUE TITLE
Electrum 2.7.16 "Send From" without function (Windows)

### ISSUE THREAD

**Issue by toxicacd** [spesmilo/electrum#2106]
When selecting an address in the Addresses tab and selecting "Send From" from the context menu after right clicking it, nothing happens.

Using Electrum 2.7.16 (standalone executable) on Windows 10.

**Comment by ecdsa** [comment]
"send from" has been removed, and I forgot to remove it from the menu.
if you want to perfom coin control, open the new "Coins" tab and selectr UTXOs there.

**Comment by ecdsa** [comment]
done in bffb10f53fe8fcb86744c0b3f617499b0c596585
