### ISSUE TITLE
Cant Change mBTC to BTC?

### ISSUE THREAD

**Issue by captkirk07** [spesmilo/electrum#2108]
Just downloaded Electrum and its displaying my bitcoin in mBTC. I went to appearances and tried to change it to BTC but everytime i click close nothing happens. How do i get it to change?

**Comment by CodeWarrior4Life** [comment]
Same problem here. It's been awhile since i've had it installed but never had this problem before.  mBTC shouldn't be default anyway.

**Comment by shsmith** [comment]
This traceback is logged:

```
Traceback (most recent call last):
  File "path\electrum\gui\qt\main_window.py", line 2477, in on_unit
    edits = self.amount_e, self.fee_e, self.receive_amount_e, fee_e
NameError: global name 'fee_e' is not defined

```

**Comment by captkirk07** [comment]
could be a glitch. hopefully theres a solution's i need my bits to be displayed in BTC mBTC confuses me
