### ISSUE TITLE
Can someone help me with a transaction issue. Stuck on LOW FEE 

### ISSUE THREAD

**Issue by va413** [spesmilo/electrum#2109]
I never used electrum before and I tried to send BTC to an address and now its stuck on LOW FEE. I didnt know that it wouldnt include a fee... When I click on details nothing comes up. I tried to view it on blockchain it says no transaction. Can someone please let me know if I can fix this? are my BTCs gone?

**Comment by shsmith** [comment]
Your bitcoins are not gone. The tx will eventually get included in a block or eventually will expire from the mempool and come back to your balance.
If you don't see the tx on block explorers then you could try switching to different electrum servers. If you get on one that doesn't have the tx in it's bitcoin mempool it should clear the tx so you can try again.
You might also want to enable the "replace by fee" option. When that is on you can "bump" the fee of an existing tx so make it go through faster.

**Comment by va413** [comment]
Thank you shsmith for that info . I was able to switch to different electrum server and was able to see the tx. It is still stuck on low fee though and unconfirmed. I did enable the replace by fee option in the preferences, but how do bump the fee one the existing tx so it goes through?

**Comment by shsmith** [comment]
It is too late to use RBF on that tx. You have to flag the initial tx as "replaceable".
Do that next time. For this one you have to wait. If multiple servers are seeing the tx, there is a good chance it will eventually be confirmed in a block, though depending on the fee it might take several hours.

**Comment by va413** [comment]
I wish it took only several hours. Thing is I been waiting for it for almost 16 hours and nothing has happened... still stuck on low fee. How much longer do I have to wait aprox? Thanks for your help!
