### ISSUE TITLE
Cant convert balance to BTC?

### ISSUE THREAD

**Issue by captkirk07** [spesmilo/electrum#2110]
My balance is stuck in mBTC base units. When i go to appearances to change it to BTC it will not work.

**Comment by micromatrix14** [comment]
What Electrum version do you have ?

**Comment by micromatrix14** [comment]
I have the latest version 2.7.17 and I don't have such problem

**Comment by captkirk07** [comment]
i downloaded it a few days again apparently i was running on 2.7.16...

**Comment by captkirk07** [comment]
problem fixed ty

**Comment by micromatrix14** [comment]
you are welcome
