### ISSUE TITLE
Please restore ability to set static fee rate in Preferences

### ISSUE THREAD

**Issue by paintballpanda** [spesmilo/electrum#2112]
After upgrading from 2.7.12 to 2.7.17 I see that the ability to set a static rate for fees is no longer available.

It's great that there's a dynamic fee option but if dynamic fee option is turned off, the user can either use the max rate as set by the slider (which can many times be insufficient for next-block confirmation), or is forced to manually calculate the fee before sending their transaction. But the problem with the second option is that the user has no way of knowing what their transaction size is, so can't accurately calculate what the fee should be.

Please bring back the option to be able to set a static fee rate in Preferences if dynamic fees are turned off.

Thank you.

**Comment by ecdsa** [comment]
in the console type: `setconfig('max_fee_rate', 200000)`
