### ISSUE TITLE
bug: Raw tx window closes on Win 10

### ISSUE THREAD

**Issue by off-bank** [spesmilo/electrum#2113]
v2.7.17, when I try to load a raw tx, window disappears when "Load transaction" button is clicked. Tried loading from text and also from file. Same results. 
I had no problem loading tx in version 2.6.4.

**Comment by off-bank** [comment]
I just tried v2.7.3 portable and it does not present the issue. Loads tx fine.

**Comment by off-bank** [comment]
Checked all versions. It's working up to v2.7.12. It doesn't load tx from v2.7.13 up.

**Comment by ecdsa** [comment]
is it an unsigned transaction?

**Comment by ecdsa** [comment]
could you post the raw transaction?

**Comment by off-bank** [comment]
Yes, unsigned.

0100000001559284001153d1b8a41109d3e1f1f7ffa93798b5fb6ac18a235e0696879451ae000000001976a914cd282b5f23631d832af2bd880d4309c6c7df9e7488acffffffff02a0860100000000001976a9149063ad94a682cdfcf4ff03f9b4930b3c7f46757488ac6eab4a00000000001976a914cd282b5f23631d832af2bd880d4309c6c7df9e7488ac00000000

**Comment by off-bank** [comment]
Actually up to v2.7.12 it loads the tx, but I just realized the Sign button is grayed out.

**Comment by ecdsa** [comment]
how did you generate the transaction?

**Comment by off-bank** [comment]
It was generated by coinprism's web wallet to where I've imported a cold address generated by the same Electrum wallet I'm trying to load and sign the transaction.

**Comment by ecdsa** [comment]
I fixed the error that prevents the tx from loading. This transaction uses an address-type script (scriptPubKey) as scripSig, I guess this is an issue with coinprism.
