### ISSUE TITLE
bug: Marking freeze on Address tab does not freeze on Coins tab on Win 10

### ISSUE THREAD

**Issue by paintballpanda** [spesmilo/electrum#2114]
Electrum 2.7.17, Windows 10. 

Marking an address as frozen on the Address tab does not mark those coins as frozen on the Coins tab until you restart electrum.

**Comment by ecdsa** [comment]
ok, I think it would be better to move the "freeze/unfreeze" menu to the Coins tab, since it has to do with spending.

**Comment by paintballpanda** [comment]
Rather than move it, it would be great if we could have it on both tabs, along with the "Send from" functionality.

**Comment by ecdsa** [comment]
not sure if it's a good thing to replicate things around.. but I will think about it.
I am trying to separate what has to do with receiving from spending. (so maybe merge Addresses and the requests list)

**Comment by ecdsa** [comment]
ok, keeping that in 'addresses' for now
