### ISSUE TITLE
Sweep from Paper Wallet to Electrum

### ISSUE THREAD

**Issue by LewKontnik** [spesmilo/electrum#2121]
I have 34.07294 mBTC given me as a gift on BitcoinPaperWallet.com
I decrypted my Private key on bit2factor.com and entered a Sweep on Electrum
I have a Transaction ID showing 33.96094 mBTC have been transferred
How do I complete this Sweep and actually take possession of my BTC in my Electrum wallet
I have /Users/LewKontnik/Downloads/electrum-2.7.17.dmg, Created Jan 10 2017
I have tried every combo of the pulldowns and buttons I can find on my Electrum and cant find any way to move forward.
Any help greatly appreciated (I do have screen shots of my step by step process)

**Comment by ecdsa** [comment]
what's the bitcoin address?

**Comment by LewKontnik** [comment]
I am not 100% sure. I did a "ismine ('XXXX')" query on Electrum with the address i got when I decrypted my Private Key and It came back "false". But I initiated the Sweep from within Electrum and I do have the Transaction information (no and amounts)
Again--any help greatly appreciated!!

**Comment by ecdsa** [comment]
ok post the transaction id please

**Comment by LewKontnik** [comment]
Here you are
2b3bc05d8626d51a82b1d46890c38f890782c9fd567b97a367eaeb12b21d2199

**Comment by LewKontnik** [comment]
Thanks for the notes—here is the transaction note from Electrum



Sincerely,

Lewis Kontnik, Strategic Advisor
Supply Chain Security and Serialization

LewKontnik@gmail.com

www.linkedin.com/pub/lew-kontnik/5/b0/b26/ 

O +1 321 775 3327 (new number)
C +1 805 558 2295

GS1 Global Healthcare Initiative Leadership Team Member
Rx-360 Communications Team

**Comment by ecdsa** [comment]
please post the correct transaction ID...

**Comment by LewKontnik** [comment]
Thomas—I have carefully verified the Transaction Number it is correct—here are two recent attempts that I have made on Electurm about this transaction—I am totally lost with this—about to give up. Again, any help appreciated!!!





Sincerely,

Lewis Kontnik, Strategic Advisor
Supply Chain Security and Serialization

LewKontnik@gmail.com

www.linkedin.com/pub/lew-kontnik/5/b0/b26/ 

O +1 321 775 3327 (new number)
C +1 805 558 2295

GS1 Global Healthcare Initiative Leadership Team Member
Rx-360 Communications Team

**Comment by ecdsa** [comment]
well, you seem unable to provide the the bitcoin address, and the transaction ID you posted is not in the blockchain. how am I supposed to find which address you are talking about?

**Comment by LewKontnik** [comment]
Thanks for the response—Im feel totally incompetent and confused and Im very thankful of any/all of your help—by the way are you with Electrum?

Im glad to give you all of the details I have about every aspect of this transaction to try to track it down. I figured Id do this little sweep before I started buying some more larger quantities. At this point I feel I need to succeed with this test before I think about anything else involving BTC.

Ask me specifically for any information you need (including my private key) and, yes, lets get this puppy tracked down.

Thanks so much.

Sincerely,

Lewis Kontnik, Strategic Advisor
Supply Chain Security and Serialization

LewKontnik@gmail.com

www.linkedin.com/pub/lew-kontnik/5/b0/b26/ 

O +1 321 775 3327 (new number)
C +1 805 558 2295

GS1 Global Healthcare Initiative Leadership Team Member
Rx-360 Communications Team

**Comment by ecdsa** [comment]
please provide the bitcoin address that corresponds to your private key

**Comment by ecdsa** [comment]
ok, saw your email. you need to click on the 'broadcast' button...

**Comment by LewKontnik** [comment]
Where is the Broadcast Button—do I push in in the Receive screen?

Sincerely,

Lewis Kontnik, Strategic Advisor
Supply Chain Security and Serialization

LewKontnik@gmail.com

www.linkedin.com/pub/lew-kontnik/5/b0/b26/ 

O +1 321 775 3327 (new number)
C +1 805 558 2295

GS1 Global Healthcare Initiative Leadership Team Member
Rx-360 Communications Team
