### ISSUE TITLE
Crash on Raspberry Pi Zero when creating new/restoring wallet

### ISSUE THREAD

**Issue by kacperzuk** [spesmilo/electrum#2124]
Electrum throws this exception when creating new standard wallet or restoring from seed on Raspberry Pi Zero:

```
Traceback (most recent call last):
  File "./electrum", line 342, in <module>
    d.init_gui(config, plugins)
  File "/home/pi/Electrum-2.7.17/lib/daemon.py", line 257, in init_gui
    self.gui.main()
  File "/home/pi/Electrum-2.7.17/gui/qt/__init__.py", line 208, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/home/pi/Electrum-2.7.17/gui/qt/__init__.py", line 174, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/home/pi/Electrum-2.7.17/gui/qt/__init__.py", line 147, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/home/pi/Electrum-2.7.17/gui/qt/main_window.py", line 179, in __init__
    self.load_wallet(wallet)
  File "/home/pi/Electrum-2.7.17/gui/qt/main_window.py", line 317, in load_wallet
    self.clear_receive_tab()
  File "/home/pi/Electrum-2.7.17/gui/qt/main_window.py", line 902, in clear_receive_tab
    addr = self.wallet.get_receiving_address()
  File "/home/pi/Electrum-2.7.17/lib/wallet.py", line 1120, in get_receiving_address
    choice = domain[0]
IndexError: list index out of range
```

It happens both on:

* Arch Linux ARM, with Electrum 2.7.17 from repository
* Raspbian, with Electrum 2.7.17 downloaded from Electrum.org. python-pyqt4 version: 4.11.2, libqt4: 4.8.6.

It doesn't happen on Electrum 2.7.17 on x86 systems.

Exact steps to reproduce are:

1. start fresh, without ~/.electrum directory
2. select "Auto connect", click Next
3. select "Standard wallet", click Next
4. select "Create a new seed", click Next
5. copy seed, click next, reenter seed, click next
8. leave password empty, click Next
9. message "Electrum is generating your addresses, please wait..." is shown as expected, but after couple seconds the exception above is thrown. Electrum doesn't close yet
11. Electrum closes after few more seconds
12. Everything seems ok after reopening Electrum, generated addresses are correct

Any guide on what may be wrong or what I can do to get better debugging information? It's weird that it works on x86, but not on Raspberry. Raspberry Pi Zero is pretty slow, so maybe that's a race condition somewhere?

You can find complete output of `electrum -v` here: http://pastebin.com/raw/ENfxfM3t

**Comment by ecdsa** [comment]
check if you can import hashlib

**Comment by kacperzuk** [comment]
I've tried with latest version from master branch (a736dc305295f96aa982b706a478b39ca65d6383) and experienced the same thing. However it did work correctly after adding delay before get_receiving_address():

```diff
diff --git a/lib/wallet.py b/lib/wallet.py
index 4fe7ec8..e9b8a48 100644
--- a/lib/wallet.py
+++ b/lib/wallet.py
@@ -1116,6 +1116,7 @@ class Abstract_Wallet(PrintError):
 
     def get_receiving_address(self):
         # always return an address
+        time.sleep(120)
         domain = self.get_receiving_addresses()
         choice = domain[0]
         for addr in domain:
```

I'm not familiar with Electrum codebase, but I think it confirms there's a race condition here.

**Comment by ecdsa** [comment]
indeed it looks like a race condition

**Comment by kacperzuk** [comment]
Adding `with self.lock:` instead of delay also fixes this for me:

```diff
diff --git a/lib/wallet.py b/lib/wallet.py
index 4fe7ec8..7203859 100644
--- a/lib/wallet.py
+++ b/lib/wallet.py
@@ -1116,7 +1116,8 @@ class Abstract_Wallet(PrintError):
 
     def get_receiving_address(self):
         # always return an address
-        domain = self.get_receiving_addresses()
+        with self.lock:
+            domain = self.get_receiving_addresses()
         choice = domain[0]
         for addr in domain:
             if not self.history.get(addr):
```

However I'm not sure whether it should go here or into `get_receiving_addresses()` directly.

**Comment by ecdsa** [comment]
could you test this instead
```diff
diff --git a/gui/qt/installwizard.py b/gui/qt/installwizard.py
index b2a5c14..31ed08c 100644
--- a/gui/qt/installwizard.py
+++ b/gui/qt/installwizard.py
@@ -345,6 +345,7 @@ class InstallWizard(QDialog, MessageBoxMixin, BaseWizard):
         self.refresh_gui()
         t = threading.Thread(target = task)
         t.start()
+        t.join()
 
     @wizard_dialog
     def choice_dialog(self, title, message, choices, run_next):
```

**Comment by kacperzuk** [comment]
This works too.
