### ISSUE TITLE
Windows 10 Can't connect to Trezor

### ISSUE THREAD

**Issue by Propulsions** [spesmilo/electrum#2125]
Unable to connect to Trezor through windows 10 host. Yet on same machine, I am able to connect to the Trezor through the web interface https://wallet.trezor.io/

Currently utilizing Electrum version  2.7.17 with Trezor firmware 1.4.0

Exact error message from Electrum client when attempting to establish connection is 'Connection failed'.

Any assistance troubleshooting would help. 

Thanks!

**Comment by ecdsa** [comment]
I suppose that it is because the web interface is connecting through Trezor Bridge.
Electrum connects using Hid ; it used to try both Hid and Trezor Bridge, but I disabled that.

I would need to be sure my theory is correct, though. I have a win10 machine and Electrum 2.7.18 detects Trezor without problem for me. (I just upgraded the trezor firmware)

**Comment by Propulsions** [comment]
Same issue on Electrum 2.7.18 
Trezor Firmware version 1.4.2

I'm under the impression it may be due to other software installed on the host. I'll start wiping it one by one and report back.

Thanks.

**Comment by ecdsa** [comment]
maybe you could try with Electrum 2.6.4. (use a separate directory if you do so, because the wallet file format is different)

**Comment by Propulsions** [comment]
> maybe you could try with Electrum 2.6.4. (use a separate directory if you do so, because the wallet file format is different)

Oddly enough after successful installation of 2.6.4 in separate data directory, Electrum refuses to launch the gui.

**Comment by ecdsa** [comment]
maybe there's an electrum process still running from the old one?

**Comment by Propulsions** [comment]
> maybe there's an electrum process still running from the old one?

No, uninstalled all versions of Electurm. Installed 2.6.4 only (still in non-default directory), rebooted host and same issue. 2.6.4 refuses to launch.

I've gone ahead and uninstalled all software that was installed after Electrum initially before the 'Unable to Connect' error. The only software that I'm having trouble removing is Hyper-V which seems to be a known issue on Windows 10. At this point, I still don't know if hyper-v is even related but it's the last option before formatting.

I'm going to attempt to at least disable hyper-v then will report back. Worst case: format completely.

**Comment by Propulsions** [comment]
Purged Hyper-V. (shot in the dark anyway) No idea what's causing the issue. Going to format.

**Comment by ecdsa** [comment]
whydid you close the issue? is it resolved?

**Comment by Propulsions** [comment]
> why did you close the issue? is it resolved?

I think this'll be a one-off situation just with my environment. If you'd like I can reopen to continue troubleshooting.

**Comment by Head** [comment]
Same here.

**Comment by RustyNomad** [comment]
Just downloaded version 2.8 and have same problem on Windows 10, does not connect to Trezor. Gets to the 'Hardware Keystore' screen and when clicking on Next, with Trezor plugged in, it just flashes a quick 'Please wait' and then nothing. Does not pickup the Trezor.

Trezor works fine with online Trezor wallet. Have the Trezor chrome extension installed. Is the Trezor bridge perhaps required for Electrum?

Also tried versions 2.7.18/17 and same problem on them.

**Comment by ecdsa** [comment]
I have the same problem now.
It does detect other hardware wallets (ledger, digital bitbox)

**Comment by Propulsions** [comment]
>I have the same problem now.
>It does detect other hardware wallets (ledger, digital bitbox)

Now that's interesting; what changed?

**Comment by ecdsa** [comment]
see #2318. 
help added in 33a32be576002de26808a1b5878d41924e982dc8
