### ISSUE TITLE
Ability to define Electrum datadir?

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#2127]
I'm not certain, apologies in advance if this is a non-issue. I'm also not sure what is the difference between the Windows portable and standalone instances in handling this.

Basically, I want to be able to define the "datadir" (where the certs directory, wallets directory, config file, etc. are located). The aim is to have a non-installed instance of Electrum at location _A_, have the datadir at location _B_, have the wallets at _B_\wallets, and not to have anything stored in C:\Users\X\AppData or _A_\electrum_data (as the portable version does).

Is this possible now? If so, which version and which operators should I use?

**Comment by ecdsa** [comment]
electrum --dir <yourpath>

**Comment by leafcutterant** [comment]
Thank you. I noticed the portable version doesn't work with --dir, only the standalone. If the standalone version is used with --dir, is there writing to any other place than <mypath>? Or, in other words, is the standalone version somehow less portable with this operator than the portable version?

**Comment by ecdsa** [comment]
the portable version uses the --portable option, which overrides --dir with the current directory.
the portable binaries exist only for users who cannot use the command line
