### ISSUE TITLE
They stole money from a purse without my knowledge

### ISSUE THREAD

**Issue by avangard88** [spesmilo/electrum#2131]
stolen funds to your wallet without my knowledge! give advice on how to return or even how it might turn out

**Comment by ecdsa** [comment]
Sorry for your loss, but you ask this in a forum/reddit. Github is a place for reporting bugs, and not to get advice on how to secure your bitcoins. Since you are not providing any relevant information, we have no reason to think this loss or theft was caused by a bug in the software.
