### ISSUE TITLE
Sent mbtc by accident and need to send btc( still unconfirmed)

### ISSUE THREAD

**Issue by julmoney7** [spesmilo/electrum#2134]
Hello I sent mbtc by accident to a address that accepts bicoins is there a way to send those funds again through bicoins . Thank you

**Comment by JazzTp** [comment]
1 mBTC = 1 BTC / 1000

I'm still a newbie with a rather superficial knowledge on Bitcoins, but I
really believe that that only affects how the amount is displayed to you,
not how it's handled, so you should be fine.

If you left the "dynamic fees" option active, you should get one
confirmation each ten minutes. With 6 confirmations, the transaction is
considered confirmed.
