### ISSUE TITLE
i have all the time unconfirmed operation

### ISSUE THREAD

**Issue by slepbee** [spesmilo/electrum#2136]
i send yesterday 24 jan 2017 23:00  small amount of BTC but till 25 jan 2017 18:09 it still unconfirmed operations what is the problem
electrum version 2,6,4

**Comment by ecdsa** [comment]
Do not open an issue on github for that.
Use a recent version of Electrum and enable dynamic fees in your preferences.

**Comment by ecdsa** [comment]
https://bitcoinfees.github.io/#3h
