### ISSUE TITLE
Allow double-spending as a workaround for low fee stuck transactions

### ISSUE THREAD

**Issue by mcandre** [spesmilo/electrum#2137]
When a low fee transaction becomes stuck for many hours, it would be helpful if Electrum allowed the user to apply the Bitcoin convention of double-spending, so that the desired transaction can go through.

Currently, Electrum presents an insufficient funds error in this situation :/

**Comment by ecdsa** [comment]
what is "the convention of double spending" ??

**Comment by ecdsa** [comment]
we support RBF, you should learn what it is.
