### ISSUE TITLE
Auto-connect does not give time to download blockchain_headers chunks

### ISSUE THREAD

**Issue by mustaqimM** [spesmilo/electrum#2139]
I uninstalled Electrum and removed the wallet on Linux. I then reinstalled it and opened the wallet again to be shown: 
![screenshot_20170131_185710](https://cloud.githubusercontent.com/assets/24436622/22475469/b9e4de0c-e7e7-11e6-9693-d1560720e19d.png)

It seems to be issue #1379. The current fix is to deselect 'Select server automatically', restart and wait for it show correctly.

**Comment by ecdsa** [comment]
known issue. changed title to reflect what's actually going on.

**Comment by ecdsa** [comment]
this is fixed: the initial headers file download is no longer needed, see d1b8a6fae6d44e78c8093b01321f8d430442b687
