### ISSUE TITLE
2.7.18 Synchronizing....

### ISSUE THREAD

**Issue by brohemath** [spesmilo/electrum#2140]
Getting endless synchronizing......... 

I thought upgrading to .18 would fix the problem but alas nay. had same problem on .16

tried all the old tricks, change server, even unplug my modem nothing to my avail. 

bitcoin is up to 970 would like to cash out, someone help please will make it worth your time$.

**Comment by brohemath** [comment]
my mistake I should include more info. Windows 10. ( x86 )   removed VPN to eliminate conflict still no joy.

**Comment by AbdussamadA** [comment]
have you tried changing to a different server via tools menu > network?

**Comment by ecdsa** [comment]
this is probably a server issue. (electrumx running without -reindex)
closing this, because the report does not have enough info.
chaging server should fix it.

**Comment by JazzTp** [comment]
Could it depend on the firewall setup? Windows firewall or what you have.

Is the Electrum version you are using authorized for outgoing connections?
