### ISSUE TITLE
zbar not installed

### ISSUE THREAD

**Issue by erm3nda** [spesmilo/electrum#2141]
Tried several times to restore a wallet from it's seed in qr format, but everytime i push the qr icon i see a error telling me that zbar is not installed.

I've installed zbar-tools, but still seeing that error.
I've also opened the program from the console to see "any" output, but nothing more than just a error popup info is shown.

Any hint?
I've restored the wallet using the "text" version of the seed, but wanna make the qr work.

**Comment by ecdsa** [comment]
I assume you are running an Electrum binary, not sources.
it is not supported, read the info on that page: https://electrum.org/#download

**Comment by erm3nda** [comment]
Theres no info about "you have no zbar support" when you "easy install it".

Btw, i could not really understand why the binary can't "use" a Linux tool like zbar.

If you say that building from sources makes it working (cuz compiles with zbar support) that's what i will do. 
I opened issue without try sources cuz i didn't really expect to not get QR support at all.

Thank you.
