### ISSUE TITLE
Seed extensions and old seeds

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#2142]
Extending a seed with certain custom words can be a way of creating memorizable "subwallets" or secondary wallets (for whatever reason: to separate funds for different purposes, to defend privacy by not linking transaction chains, etc.).

However, it seems old-version seeds can't be extended. The option can be ticked in the separate window, but the extension screen doesn't show up. Therefore, the above functionality is not available those who use an old seed.

Are there any technical or security reasons for not letting old seeds be extended?

If there are and they are serious, can you gray out the extension option if the entered seed is of the old version? Or at least have some text in parenthesis that only new/standard/post-vX.Y seeds can be extended? Just so that it's clear to the user.

**Comment by ecdsa** [comment]
It is not possible to add extensions to old seeds, for technical reasons. I don't think adapting the gui to old seeds is worth the effort; there are more urgent things to do. I think users with old seeds should upgrade to a new wallet in order to pay less fees.

**Comment by leafcutterant** [comment]
I see, thank you.

I didn't know fee amount and seed type are related. How? (I've read the related part of the documentation, but can't remember reading anything about that.)

**Comment by ecdsa** [comment]
yes, old seeds create bitcoin addresses with uncompressed keys, which make the transactions larger. I was thinking about displaying message asking users to create a new wallet, but it might be better to wait until segwit is activated.

**Comment by leafcutterant** [comment]
Okay, good to know. Will segwit need a new type of wallets/addresses to utilize all advantages?

**Comment by ecdsa** [comment]
yes it will.
