### ISSUE TITLE
HTTPS cert expired on LabelSync server

### ISSUE THREAD

**Issue by sergey-cheperis** [spesmilo/electrum#2144]
The cert on https://sync.bytesized-hosting.com:9090/ has expired and the LabelSync plugin stopped working

**Comment by dabura667** [comment]
looks like the person didn't set up the renewal cronjob correctly...

In case that person comes on here:

https://certbot.eff.org/  (This is the new name for "Let's Encrypt")

1. Choose the server software and the system.
2. Read the instructions.

Lately their packages come auto-matically with an automated cronjob to check for renewal every 2 hours (the script exits immediately if the cert is not up for renewal, so it is ok to be frequent.)

https://certbot.eff.org/#ubuntuother-apache

from this example on ubuntu based apache

`./path/to/certbot-auto renew --quiet --no-self-upgrade` and FYI --quiet --no-self-upgrade both work on the old lets-encrypt packages too, just change "certbot" with "lets-encrypt" and place this exact same one liner in your crontab or systemd. (I had permission problems when setting up my own, so I suggest using root crontab.)
