### ISSUE TITLE
"Encountered Invalid prevhash" error when sending out the soloed segwit block

### ISSUE THREAD

**Issue by huiguorou** [spesmilo/electrum#2145]
Hi Electrum develop team,
I'm a user of Electrum as well as the Trezor hardware bitcoin wallet. by early Jan 2017. I use my Trezor generated wallet address as the solo mining receiving address and normally I use electrum to manage the coins. I managed found 2 blocks by early Jan 2017 and the address I use did receive the mined coins but when I try to send out these 2 blocks, the electrum always pop up error  "Encountered Invalid prevhash". while when I spend the other tx in the same address. I was able to send out as normal. The only difference is the 2 blocks are segwit block and only have coinbase input. Please help on this issue and advise how can I use the 2 blocks. Many thanks. And I'm using the 2.6.4 in one win10 laptop and 2.7.18 at another win10 laptop. both have encountered the same error. Please help. Many thanks

**Comment by ecdsa** [comment]
I suppose you mean "segwit-signalling" blocks, because currently there are no segwit blocks.
This is probably an issue with Trezor; try to update your firmware.

**Comment by huiguorou** [comment]
Thanks for the quick response ecdsa, I updated the Trezor firmware to the latest version. while the 2.7.17 and 2.7.18 vision of Electrum can not recognise the updated Trezor. but the older version 2.6.4 can. which the error is still there. any suggestion? many thanks

**Comment by ecdsa** [comment]
the error message "Encountered Invalid prevhash" comes from trezor, not from Electrum:
https://github.com/trezor/trezor-mcu/blob/master/firmware/signing.c#L380

you should ask the trezor developers about it.

**Comment by huiguorou** [comment]
Thanks Thomas. I have submitted a help ticket to Trezor. Will follow up with them.

**Comment by ecdsa** [comment]
ok. I think your other issue is redundant with #2125, so I will close this issue.
