### ISSUE TITLE
Restore from 1.9.7 seed failed

### ISSUE THREAD

**Issue by joyceZ916** [spesmilo/electrum#2148]
I can still see coins on my wallet, however after trying all the possible password on Electrum 1.9.7 on Windows 7 (in safe mode with network) none worked. I tried to restore from my seed on Electrum 2.7.18, 1.8.1 and 1.9.7 Windows 10 but with no luck. Tried with Electrum 2.7.18 and 1.9.7 on Linux Ununtu 16.04 and didn't work. I tried to restore from Electrum 1.9.7 on Windows 7, where I originally have this wallet, still didn't work. It came out as an empty wallet, "no transaction was found".
I saved a copy of the wallet from Electrum 1.9.7 on Windows 7 and opened on Electrum 1.9.7 on Windows 10 and it worked. I can see the coins.
I have copied and saved my seed separately at two places and they are identical. The seed should be good.

**Comment by ecdsa** [comment]
This means that the seed you have saved is for a different wallet.
If you do not have the seed for your wallet, you need to find your password.

**Comment by joyceZ916** [comment]
ecdsa, you are right.
I figured out my password. It turned out the seed is a different one...
Thank you for your time.
