### ISSUE TITLE
i can't send my btc and have error The transaction was rejected by network rules

### ISSUE THREAD

**Issue by shift23** [spesmilo/electrum#2150]
when i try to sent my btc i have error The transaction was rejected by network rules.(16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element))

**Comment by JazzTp** [comment]
I guess the developers will need more info, which operative system and its
precise version, and which Electrum version.

**Comment by shift23** [comment]
windows7 and last version of electrum. yesterday I did not have any problems. but today I have this problem

**Comment by ecdsa** [comment]
try to restore your wallet from seed. 
also, include the wallet type in your report.

**Comment by shift23** [comment]
ok, i used another laptop with seed restore and i could send my btc. but i think it isn't best solution, because i would like to use my laptop
wallet 2.7.18

**Comment by ecdsa** [comment]
nothing prevents you from doing it on your own laptop.
just delete your wallet file.

**Comment by shift23** [comment]
I tried to remove my wallet several times but it did not help
