### ISSUE TITLE
SyntaxError - raise ValueError, emsg % keysize (aes.py line643)

### ISSUE THREAD

**Issue by redbullpeter** [spesmilo/electrum#2151]
Hi,

I just installed electrum using the pip. There were no errors on install but trying to launch electrum from the command line returns this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 90, in <module>
    check_imports()
  File "/usr/local/bin/electrum", line 64, in check_imports
    import aes
  File "/usr/local/lib/python3.5/dist-packages/aes.py", line 643
    raise ValueError, emsg % keysize
                    ^
SyntaxError: invalid syntax
```

I'm using Python 3.5.2

**Comment by JazzTp** [comment]
Hi, I guess the developers will need more info, which operative system and
its precise version, and which Electrum version.

**Comment by redbullpeter** [comment]
Ubuntu 16.04.1
Electrum 2.7.18

**Comment by ecdsa** [comment]
use python2

**Comment by affansamad93** [comment]
just add parenthesis around this and error will be resolved.

e.g. raise (ValueError, emsg % keysize)
