### ISSUE TITLE
Electrum andriod - unconfimed due to system glitch

### ISSUE THREAD

**Issue by a-shafiq** [spesmilo/electrum#2152]
I sent coin and entered wrong pin so when i switched my app on phone to look up my pin and then when i got back to electrum it said the coins has been sent and its been unconfirmed since. Its been about 20 hours.

https://blockchain.info/tx/4f15d4f0c95b58130d96255bb8c2cdaff3fbe28e59d7941e1220266d6f53aa49

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
