### ISSUE TITLE
Received only 95% of a deposit

### ISSUE THREAD

**Issue by RockyTop144** [spesmilo/electrum#2156]
I transfered $1842 from another site, and only received $1752 worth of bitcoins. How is that possible? That would amount to a 5% transaction fee, which is insane. Who can I talk to to get this resolved!? All previous fees were much smaller. 

Thanks

**Comment by JazzTp** [comment]
Hi, I'm pretty much a newbie here.

The main developer did and does a great job, a huge job, but I bet he has
no crystal ball... I see that a lot of questions arrive here missing any
information... like operative system and version, Electrum version and
wallet type, and in this case, probably, transaction ID... and possibly
which site the transaction originated from (is it possible that a
withdrawal fee was so high from there?).

**Comment by ecdsa** [comment]
without any relevant information, I suppose this user is complaining about volatility. that's not fixable.
