### ISSUE TITLE
server and proxy (network) settings do not persist after restart

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#2157]
Latest 2.7.18 (at least on Windows, portable mode) doesn't remember network settings after Electrum wallet application is closed and started again. It doesn't remember the server (just starts with server selection automatically) and the worst thing, it does not remember any proxy/socks5 set even if it was, which could have privacy implications if one user configures it for the first time to go via a socks and second time it launches it goes using the default IP address.

I am not sure how to handle this when we open multiple wallets (application instances). My guess would be to include this in the wallet file, so each wallet can have its own proxy/socks and server, should an user need it.

**Comment by gits7r** [comment]
I am closing this for the moment being, because somehow I can't reproduce in a normal environment (it happened initially on a virtual machine that is configured in a somewhat amnesic mode, so big chances I was missing an exception for the electrum data dir folder). I will reopen in case I can reproduce in a way that others can too.

**Comment by ecdsa** [comment]
it could happen if you had multiple instances of Electrum running on the same machine, and they fail to detect eachother

**Comment by gits7r** [comment]
True, I had 2 instances. Neither of them were using a proxy, but the right wallets were opened in each instance, so the wallets worked and were read properly just the network settings didn't. By the way, the file that contains the socks proxy can contain multiple entries in case more concurrent instances run?

**Comment by ecdsa** [comment]
the proxy setting is written in the config file, it is shared across the wallets opened with the same daemon

**Comment by gits7r** [comment]
2 instances running at the same time cannot use different proxies / servers?

**Comment by ecdsa** [comment]
not if they use the same daemon.
yes, if they really are two instances.
