### ISSUE TITLE
Sweep not working properly???

### ISSUE THREAD

**Issue by esiu69** [spesmilo/electrum#2159]
Hello,
Just installed Electrum for the first time and tried to shift my coins from Bitcoin Core following this guide: https://en.bitcoin.it/wiki/Transferring_coins_from_Bitcoin-Qt_to_Electrum
Obtained all addresses with funds using "listreceivedbyaddress" (there were 7), obtained the corresponding private keys, went to use "Sweep", pasted all 7 private keys in, clicked "Broadcast" and received 72 BTC.  The problem is that Bitcoin Core had 368 BTC.  So where are the missing 296 BTC?  Can someone help please?  Bitcoin Core is still downloading blockchain (14 weeks to go).  It's still showing the full balance but I'm scared of what it'll show once the blockchain finishes downloading....  I'm aware that in a Bitcoin transaction, the sum of Outputs must equal the sum of Inputs.  If Sweep did not put the transaction together properly, the difference is gone in transaction fees...  Anyone???
Thanks...
EDIT:
I actually did a test first on one of the keys.  The test transaction is still unconfirmed, the later one (with 6 keys) has 9 confirmations at the moment.  Both transactions look OK on the block explorer:
https://blockchain.info/tx/08d35c8c365400ebfe050d8e13075739eb8be7f55aaeefb44757bee7860e98c4
https://blockchain.info/tx/3b2352def98e267535da1ad49b4a2cbf4812816c758c901e7e7c5faaa61ece38
Still no idea what that Sweep thing did exactly though, hope my coins are left intact though...
Also, the first transaction (the unconfirmed one) was deducted from my Bitcoin Core balance, the other one was not, as yet.  All strange...

**Comment by ecdsa** [comment]
what are the 7 addresses?

**Comment by esiu69** [comment]
1DEWcYwgfcMrDmSbfYw36zEXiPTRgJFmA
13yYE9UoeXKyHNiqCfHG3r7wviV8Qwv87J
15yYGnQUYm36PjRPjeDVoTvRBJeJsd9PbY
1AKsbTz36N3uQVmBuSV84WZFKq6y2RpVMw
1G4qaysabtcLWtn2doLJLnY17CzdkhW4UE
1HQEQugyvwdQBK1KNYzEHgbrb9GvP8mJHa
1Nq3ts7fEw5b4LvGk4o4za5XLVzhwh7pHP

**Comment by ecdsa** [comment]
The balance of these addresses is zero. I don't know why Bitcoin Core shows a different amount; I suppose you did not fully synchronize your Bitcoin Core wallet. Closing this, because Electrum sweep is working properly.

**Comment by esiu69** [comment]
OK, I found my missing coins at this address:  1FaaKKvTVUkbJFfnkRgaHgDAwomE6ZKC2G
For some reason it does not show up on "listreceivedbyaddress" but I got a longer list of addresses using "listaddressgroupings" and I checked them all.  Thanks for your help ecdsa.  Just Sweeped this one and will see what happens...
