### ISSUE TITLE
Crash on send with Ledger Nano S

### ISSUE THREAD

**Issue by viorels** [spesmilo/electrum#2166]
This is happening after clicking send, using a Ledger Nano S hardware wallet, right after confirming the transaction on the hardware wallet. The transaction is not published on the network.

Electrum version 2.7.18

$ electrum 
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
fish: “electrum” terminated by signal SIGABRT (Abort)

**Comment by ecdsa** [comment]
does it occur reliably?

**Comment by viorels** [comment]
Almost, about 4 in 5 tries. How can I help with more debug info?

**Comment by joesixpack** [comment]
Can we please get this problem fixed?  It's been 10 months.

**Comment by joesixpack** [comment]
Can we please get this problem fixed?  It's been 10 months.

![image](https://user-images.githubusercontent.com/23145642/34027106-5dd780e8-e10f-11e7-8216-50a4f5c43f70.png)

**Comment by SomberNight** [comment]
The problem in the OP should have been fixed by https://github.com/spesmilo/electrum/commit/5800a2455908e8470eb9152e4cf59441b8cd733b which is in 3.0.0.

@joesixpack probably ran into https://github.com/spesmilo/electrum/issues/3264 which has been fixed since 3.0.3.
