### ISSUE TITLE
Creating watch-only wallet from address not working from command line

### ISSUE THREAD

**Issue by jmliz** [spesmilo/electrum#2173]
I'm trying to receive notifications for a multisig address from command line in Electrum wallet. 

AFAICT there are 2 ways of receiving address notifications with electrum as merchant server backend:

1. Following the merchant documentation for websockets notifications.
2. Using `notify` command would send POST requests to my server.

* I know the merchant documentation, but I don't want the addrequest command to choose one of the existing addresses, I want to specify one of my own, like a multisig one.

* I've also tried the `notify` command that sends a POST request to a specified URL. My server didn't receive any notifications on testnet.

So the last thing I've tried is running the `addrequest` command specifing a watch-only wallet for that particular multisig (with `-w` param.) and hoping it will generate the payment request and work as well with websockets as in the merchant docs with autogenerated addresses.

-----
It gives me the following error while trying to create a watch only wallet (restoring from address):

`electrum -w walletfile.dat --testnet restore mtestnetbtcaddress`

If wallet file doesn't exists, the above command would return:

`Error: Seed or key not recognized`

If wallet file does exist:

`Error: Remove the existing wallet first!`

So:

- merchant docs seems to work only for autogenerated addresses.
- `notify` command for adding multisig addrs does not send POST at least on `--testnet`.
- I couldn't create a watch-only from restore command.

please help, thanks in advance.

**Comment by dabura667** [comment]
Affected area:

https://github.com/spesmilo/electrum/blob/d99855f06072c33cef144edce68acded561e339a/electrum#L139

This check does not recognize address(es)
