### ISSUE TITLE
koki1

### ISSUE THREAD

**Issue by koki1** [spesmilo/electrum#2174]
Can't send transactions because it shows an error: "Your client produced a transaction that is not accepted by the network any more. Please upgrade to Electrum 2.5.1 or newer".

But I can't find Electrum-DASH 2.5.1 version...

**Comment by dabura667** [comment]
Electrum-DASH is not supported here. This is issues for Bitcoin Electrum. Please close this issue and ask at the appropriate place.

**Comment by dabura667** [comment]
https://github.com/dashpay/electrum-dash/issues/new
