### ISSUE TITLE
label formatting visual corruption caused by newline characters

### ISSUE THREAD

**Issue by fortran77** [spesmilo/electrum#2176]
In both Electrum 2.6.4 and 2.7.18, if we use copy-and-paste to edit a transaction label, newline characters also get pasted in.

The resulting onscreen formatting then looks corrupted.

Newline characters often get included in a copy of a single line if we use triple-click to copy an entire line of text. it's very common behavior in most software that a triple-click copies a single line of text and includes a trailing newline character. Pasting this into an electrum transaction label leaves a newline character at the end of the label.

Embedded newlines can also occur, if we copy-and-paste two lines of text.

**Comment by bauerj** [comment]
This will be fixed in the next version of Electrum.
