### ISSUE TITLE
Allow Electrum to not open any wallet when started

### ISSUE THREAD

**Issue by ahmarlen** [spesmilo/electrum#2177]
If Electrum opens when started a default wallet (wallet A) linked to one identity and the user opens wallet B that is linked to another identity after Electrum has opened then the two identities can be linked which is a privacy issue.

This can be fixed if users are allowed the option to have Electrum open nothing when started.

**Comment by bauerj** [comment]
You **can** choose which wallet to open when starting Electrum. Just set the wallet using the `-w` command line switch.

**Comment by EagleTM** [comment]
I guess it would be a GUI option feature to start with an dialgoue to open a wallet file

**Comment by t4777sd** [comment]
Yes, I agree with this. In addition, I think this dialog should include the option to open a "RAM-only wallet" as described as the fix to this security issue: https://github.com/spesmilo/electrum/issues/2208

So, for example, a diaglog that has 3 buttons: "Open", "New", "Ram / Temporary Wallet"

Open will of course let them select which one to open. New will let them create a new disk-based wallet. And the "Ram / Temporary Wallet" will let them either input seed words or connect to a Trezor, but the important thing being that NOTHING is written to disk, so once electrum closes it is as-if the wallet never existed.

**Comment by ecdsa** [comment]
closing as duplicate of #1730 
please check the list of existing issues before posting
