### ISSUE TITLE
when sweeping, no way to set a fee

### ISSUE THREAD

**Issue by ivanhoe1982** [spesmilo/electrum#2179]
it gets a default 50 satoshi per byte, which in current circumstances results in 8-12 hour confirmation times
(ubuntu)

**Comment by gits7r** [comment]
Go to Preferences and use dynamic fees and enable option edit fees manually.

**Comment by ivanhoe1982** [comment]
I did just that even before posting the bug. I am testing on 2.7.18. After sweep, I get a transaction window with the usual transaction id, ins and outs, copy, save, sign (greyed out since it is already signed with the pk) and broadcast. No obvious (or non-obvious) way to edit the fee. The fee message actually says "unknown". Am I missing something?

**Comment by LawnboyMax** [comment]
When you press `sweep`, a sweep function from wallet.py is called with fee field set as `None` no matter what, which creates a transaction with an estimated fee (by using estimate_fee function from wallet.py) which is determined by the dynamic fee setting. 

This means that if the fee is to be changed when sweeping, it has to be done somehow before you press `sweep` and create a transaction, similar to how you can change the fee when sending. 

I've also had problems with default default dynamic fees, when my transactions got stuck as unconfirmed for more than a day.

I think something has to be changed about how the dynamic fees are calculated or, even better, a fee slider added to the sweep window (where you are prompted to enter private keys).

**Comment by ivanhoe1982** [comment]
Yup, I agree, I did exactly the same trace yesterday... Sweep window is a very special 'transaction' window, and I feel like the sweep function should just hand off to the transaction window, instead of being this weird standalone case. Then one could use functionality already built into transaction.

**Comment by JazzTp** [comment]
Newbie question, I could most likely find an answer from docs:

How does sweep differ from just creating a transaction and choosing Max
amount?

**Comment by JazzTp** [comment]
Ooops, maybe the answer is that you only use sweep to extract all funds
from a wallet which private key you imported into an Electrum wallet, not
to send all funds out of an Electrum wallet.

**Comment by schildbach** [comment]
I can attest that when sweeping you cannot set the fee. Also you cannot RBF the transaction.

**Comment by ecdsa** [comment]
as a workaround, you can create a temporary wallet with the privkeys that you want to sweep.
then, all the advanced fee and rbf options are available.

**Comment by donnlee** [comment]
Yes, please allow editing of the fee when sweeping a private key.
Thanks to google websearch for finding this github issue and confirming that I wasn't missing a checkbox setting somewhere.

**Comment by Engelberg** [comment]
+1

**Comment by dan-da** [comment]
+1

**Comment by wrkc** [comment]
+1

**Comment by ecdsa** [comment]
fixed in #3380
