### ISSUE TITLE
"payto -f" multiplies fee by 10^8 twice

### ISSUE THREAD

**Issue by MentalCollatz** [spesmilo/electrum#2183]
If you create a transaction from the command line using `electrum payto -f .00000001 addr`, you'll find that the resulting transaction has a 1 BTC fee, rather than 1 satoshi as intended.

Side note: can someone confirm that dynamic fees actually work when using the command line?  The reason I was trying `-f` in the first place is the fees seem lower than they ought to be.

**Comment by ecdsa** [comment]
I cannot reproduce that. which version of Electrum are you using?

**Comment by ecdsa** [comment]
could it be that your command line did not get parsed correctly? 
try `payto -f 0.00000001`

**Comment by ecdsa** [comment]
note: dynamic fees do not work from the command line, because the `payto` command is run offline. 
I can try to improve that.

**Comment by ecdsa** [comment]
I think I see the problem: 
did you use the jsonrpc interface instead of the command line?

**Comment by ecdsa** [comment]
another possibility is tat you are running an electrum daemon that is older than your currently installed electrum script

**Comment by MentalCollatz** [comment]
Ah yes, that was probably it.  I upgraded then forgot to restart the daemon.  Thanks for figuring it out so quickly!
