### ISSUE TITLE
Increase length passphrase

### ISSUE THREAD

**Issue by HostFat** [spesmilo/electrum#2184]
Can we have the possibility for choosing an increase of length of passphrase? Maybe 24 words? (so the user can still choose the current length )

**Comment by JazzTp** [comment]
You have the option of extending the seed with your own custom words.

**Comment by HostFat** [comment]
Ok, I'll use this way then, thank you :)

**Comment by JazzTp** [comment]
You are welcome.

**Comment by ecdsa** [comment]
"electrum make_seed --nbits=264"

**Comment by JazzTp** [comment]
Thank you!

**Comment by HostFat** [comment]
I see that it is possible even in the console of the GUI version:

make_seed(264)

**Comment by JazzTp** [comment]
Is it exactly the same, or is it the numeric initialization of the seed of
the pseudo random generator?

**Comment by HostFat** [comment]
The lower the number in the argument, the smaller the seed (less words)

**Comment by JazzTp** [comment]
Thank you.
