### ISSUE TITLE
Unconfirmed Transaction problem

### ISSUE THREAD

**Issue by CharlotteStuttgart** [spesmilo/electrum#2185]
Hi,

I have been using my wallet some time but this is a transaction that I sent last night at 8pm European time. It needs to arrive latest before 8 pm today but it is still unconfirmed. I am really worried that when it is sent after 8 pm my money is gone. I really hope someone here can help me.

The transaction ID: 6870684550f148fbe58d6b4ca055d00189358e2214c8311ae97b7b73eba9586a

As saud if it is not sent before 8 pm I loose my money and the worse thing is there is nothing I can do.

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by JazzTp** [comment]
In issue #2153 another user added useful information and reminded to
activate the option ”enable replace by fee" and mark the outgoing
transaction as "replaceable".

**Comment by JazzTp** [comment]
If you didn't do that, you or the recipient should still be able to do a
"child pays for parent" transaction to speed up the unconfirmed one, see
issue #2153.

**Comment by CharlotteStuttgart** [comment]
Dear Ecdsa, Sorry but I am not sure how to do this Child Pays for Parent. I found my change address in the wallet but unfortunately when I rightclick there is no send from this change address in my Electrum wallet. I am really non computer savy. I did not find clear instructions from Electrum how this child pays for parent works. If you could please send those to me I would be really happy and gratefull. Thank you so much!
