### ISSUE TITLE
(CRITICAL) Wrong key derivation for BIP44

### ISSUE THREAD

**Issue by a49q258k** [spesmilo/electrum#2186]
TEST CASE:

Mnemonic `fruit wave dwarf banana earth journey tattoo true farm silk olive fence`
Passphrase `banana`

Electrum
m/44'/0'/0'/0/0 `17rxURoF96VhmkcEGCj5LNQkmN9HVhWb7F`

BitPay/Copay
m/44'/0'/0'/0/0 `13EuKhffWkBE2KUwcbkbELZb1MpzbimJ3Y`

Also see https://github.com/iancoleman/bip39/issues/58 and https://github.com/bitpay/copay/issues/5667, I am not sure which clients are deriving properly / improperly, but we have a BIP39 mnemonic and passphrase that derives different addresses on different clients

**Comment by ecdsa** [comment]
"The derivation in Copay (and anything using bitcore-lib) is incorrect. The bug is when there is a leading zero of the private key and the hash during derivation does not include the zero. The BIP32 specification states that the size of the private key is always 32 bytes before it's hashed."
