### ISSUE TITLE
Security Issue: Wallet files stored as plain text (no encryption!!!)

### ISSUE THREAD

**Issue by t4777sd** [spesmilo/electrum#2187]
Wwallets are using plain text to store wallet files. That means that anyone whether someone with access to the computer to malware to state agencies, etc, can view all wallet data including balances and coins to track spending patterns.

This is particularly important as many cross-border checks require people to submit their laptop to inspections and even copying. This would give an attacker full information about any bitcoin balances, which they may use to extort money, solicit bribes, etc.

Default behavior should always be an encrypted wallet file. At a minimum, people should have the option to encrypt the wallet file. And, since electrum encrypts the wallet for every other wallet type I have to assume that it would be easy to implement.

Also, this issue would be partially solved by the "RAM-only wallet" described in https://github.com/spesmilo/electrum/issues/2208

**Note:** Original issue was solved, so I edited this issue with a completely different issue.

**Comment by ecdsa** [comment]
since when are non-hardware wallets encrypted? all wallet types are in plain text. I suppose you are confusing file encryption and seed encryption. Please read the FAQ in order to understand the issue: http://docs.electrum.org/en/latest/faq.html#why-can-i-open-the-wallet-without-entering-my-password

I am working on an asymmetric encryption format, but this is not released yet; 
see the 'encrypt' branch on github

**Comment by t4777sd** [comment]
Wow, I guess this applies to all wallets (sorry, I have only ever used hardware). I am glad you have an encrypted branch to solve some of the privacy concerns that this causes! Great work btw I really like electrum!

**Comment by JazzTp** [comment]
You can always use encrypted pendrives, one as offline cold storage, one
with the watching only part of your wallet.

Once mounted with the password, each pendrive content is accessible
decrypted, admittedly, but at least it isn't accessible when you are not
using Electrum.

**Comment by ecdsa** [comment]
this was merged yesterday
