### ISSUE TITLE
2 Dash Lost with Electrum Dash

### ISSUE THREAD

**Issue by yassutaro** [spesmilo/electrum#2188]
Hello friends, greetings!

I have installed Electrum Dash version 2.4.1 on my computer (Windows 10). Select the network manually for "electrum.masternode.io", I left the rate on the automatic, however, I can only receive Dash. When trying to send, no confirmation is obtained and my dash gets lost in space time. I have read several tutorials in forums, about trying to import my wallet into other applications, but none of them, because my sentence contains 13 words. They all support only 12. Is this an aberration, I was awarded? I did not find any that would allow me to import the private keys and I'm starting to think that I lost over 40 dollars when opting for Electrum. I've read that there is no way to cancel the upload, just try to duplicate to overlap through another wallet, but I can not even import it into other ...
I am in this situation for several days. I tried to import with Exodus and Jaxx without success. Currently I keep the Dash that I have left in Jaxx. Is it possible to resolve this problem? I have not seen anyone yet who has succeeded in this. I've met countless people who lost their Dash forever with Electrum. Could you help me, please?
Thank you and a big hug to the whole community!

_P.S. Errors due to Google Translator ...  : D_

**Comment by yassutaro** [comment]
Closed?

**Comment by thelazier** [comment]
@yassutaro , Please check and create issue at https://github.com/dashpay/electrum-dash/issues

**Comment by yassutaro** [comment]
Why did you end my call for help without explanation? Did I hurt some
standard without knowing?
I apologize, I only used this tool because I did not know what to do
to recover my Dash.


@yassutaro



2017-02-23 4:45 GMT-03:00 ThomasV <notifications@github.com>:

**Comment by yassutaro** [comment]
Okay. Thank you!
