### ISSUE TITLE
How to co-sign with Android app?

### ISSUE THREAD

**Issue by jmliz** [spesmilo/electrum#2189]
I read in the electrum-docs repo that it's possible from the desktop client to import a transaction for cosigning. The android wallet lets you create a multisig wallet but I can't find a way to import a transaction. 

I only see a simple payment request to and address, but no option to prepare and share a transaction with cosigners, like share an encrypted file, qr codes, etc.

How can we accomplish that?

**Comment by ecdsa** [comment]
via qr code. 
scan the transaction using the camera button.
