### ISSUE TITLE
Bitcoins stuck for over three days I even used a good fee

### ISSUE THREAD

**Issue by iwreckshaun** [spesmilo/electrum#2190]
Hey guys its been about three days when I sent my bitcoins but they are still unconfirmed. The fee is used was about 50s/byte. Is it a lost cause or is there anyway I can get my money back..

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
