### ISSUE TITLE
2FA Wallets (25 word seeds) recovered as normal wallets end up with error message on send

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#2195]
It happens that users restore a 25 word 2FA wallet from seed as a normal wallet (with 13 words). When they send a tx they get "16: mandatory-script-verify-flag-failed" from via e-s / bitcoind because the 2nd factor is missing. 

It's not easy to debug this with users who join IRC to ask what's wrong. Ideally we should bring up an extra message with the error to tell the user he is missing signatures and to question the user whether he might have an 2FA wallet which he has recovered the wrong way.

**Comment by ecdsa** [comment]
no, that's not the reason why they get this message.
if they restore from seed they should not get this message.

did they restore with the latest version?

**Comment by ecdsa** [comment]
see the release notes of 2.7.15, I think that's the issue here.
