### ISSUE TITLE
transaction unconfirmed not came back in wallet

### ISSUE THREAD

**Issue by crreek31** [spesmilo/electrum#2196]
Hello

I had a transaction unconfirmed and the money doesnt come back in my electrum wallet .

I don t understand why ? 

https://blockexplorer.com/address/153XpTWgagK24NHEGnHiudF4NivduvhPCp

**Comment by ecdsa** [comment]
read the faq http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
