### ISSUE TITLE
feature request to add possibility to not use unconfirmed inputs in transaction

### ISSUE THREAD

**Issue by LukAss741** [spesmilo/electrum#2197]
Hi.
Would you please consider adding a feature to be able to not use unconfirmed transactions as inputs while sending transactions in electrum?
Or is there such possibility already?

I encountered a situation when my wallet balance consisted of a few unconfirmed and a few confirmed transactions. I wanted to use only the confirmed ones but I couldn't choose which ones it will use - I used amount which was a little less than sum of confirmed transactions. Therefore I lowered amount of BTC to be sent. Then it used only one input. This input unfortunately was an unconfirmed transaction with unconfirmed parent.

Some feature like "(checkbox) don't use unconfirmed transactions as inputs in this transaction" or possibility to manually choose transactions for inputs would be perfect in electrum.
thanks

**Comment by ecdsa** [comment]
what is your coin selection setting, Privacy or Priority?

**Comment by LukAss741** [comment]
priority

**Comment by ecdsa** [comment]
I suppose it had to use another input because you did not include the transaction fee.
if you want to select which input you spend, use the "coins" tab, and then the "max" button.
