### ISSUE TITLE
System Tray

### ISSUE THREAD

**Issue by Thoh2Phophuh** [spesmilo/electrum#2198]
Hello, add the ability to minimize/close the program to the system tray, thank you.

**Comment by ecdsa** [comment]
this feature already exists.

**Comment by Thoh2Phophuh** [comment]
it minimizes to task panel, not to tray

**Comment by ecdsa** [comment]
what OS  are you using?

**Comment by Thoh2Phophuh** [comment]
Debian XFCE 4.12 / OpenSUSE 13.2

**Comment by ecdsa** [comment]
can you show a screenshot? 
according to Qt, it minimizes to whatever Qt calls "tray"

**Comment by Thoh2Phophuh** [comment]
Seems that it is a window manager issue. When I press "minimize" button on the window border Electrum minimizes to both system tray and task panel. But if I choose "Show/Hide" in the menu at Electrum tray icon - it minimizes only to system tray, not to task panel.

**Comment by Thoh2Phophuh** [comment]
Could you add a settings option to minimize to tray like in qBitTorrent? 
![qbittorrent](https://cloud.githubusercontent.com/assets/26010015/23314831/6d549a3c-fabb-11e6-8be5-86bd75b4e9be.png)
