### ISSUE TITLE
Win portable version 2.7.18 does not store label description in local wallet file

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#2199]
Win portable version 2.7.18 does not store label description in local wallet file.
When you enter a label and resart electrum opening the same wallet, the info is not there anymore.

It worked in 2.7.13 and works for the user (Kralle on IRC) in 2.7.18 with the normal version.  Local disk is writable.

Something between 2.7.13 and 2.7.18 seems to have broken it - probably path related as the portable version writes to DRIVE:\Electrum\electrum_data.

I've asked Kralle to narrow the version down further

**Comment by EagleTM** [comment]
Kralle narrowed it down Portable 2.7.17 works

**Comment by EagleTM** [comment]
I can't see any changes in the code between 2.7.17 and 2.7.18 which would cause this. Maybe it has to do with the way 2.7.18 was build for portable?

**Comment by ecdsa** [comment]
could you reproduce it yourself?

**Comment by ecdsa** [comment]
I believe it is not related to labels; 
writing to disk is unreliable on windows
