### ISSUE TITLE
Can't start Electrum: Error: cannot import name integer_types. Try 'sudo pip install <module-name>'

### ISSUE THREAD

**Issue by AaronM04** [spesmilo/electrum#2205]
Hi,

Electrum suddenly stopped working (perhaps after upgrading Fedora). When I run `electrum` on the command line, I now get this:

```
Error: cannot import name integer_types. Try 'sudo pip install <module-name>'
```

Any help would be much appreciated! :) I really need to pay for stuff. I'm running Fedora 25.

**Comment by ecdsa** [comment]
please report this to Fedora ; from googling, it looks like they use a bad version of the requests package.
if you need to access your wallet, download the electrum tar.gz from electrum.org, and run it from its directory; it will not use Fedora's version of requests

**Comment by AaronM04** [comment]
Thank you!
