### ISSUE TITLE
BTC stuck in Electrum, keep getting "object of type 'NoneType' has no len()" when trying to send, please help!

### ISSUE THREAD

**Issue by brandonjabr** [spesmilo/electrum#2215]
After sending some bitcoin to my electrum wallet, I tried sending it back out again to another wallet of mine, however I am completely unable to do so and keep getting the error "object of type 'NoneType' has no len()". I tried restoring the wallet by copying the original's seed value and using the "New/Restore" option with the same seed, however this new wallet doesn't have any balance, I'm not sure what to do from here.

Running Version 2.7.18 on MacOS Sierra 10.12.3

Thank you

**Comment by ecdsa** [comment]
in the first wallet, are you able to open the seed dialog to check the seed?

**Comment by brandonjabr** [comment]
Yea I can, maybe I'm not doing the restore method properly?

Best,
Brandon

**Comment by ecdsa** [comment]
can you check that it is the same seed you restored with?

**Comment by brandonjabr** [comment]
Yes it is, no luck still unfortunately

**Comment by ecdsa** [comment]
did you ever modify the gap limit?

**Comment by brandonjabr** [comment]
No I haven't...is this not a known bug?

**Comment by ecdsa** [comment]
no, there's no known bug like what you describe.
you should give more details.
was the seed created by Electrum? what is the seed type? can you share the master public key?

**Comment by ecdsa** [comment]
also, did you save the seed on paper when you created the wallet?

**Comment by brandonjabr** [comment]
Here's the output of running password() in  console: 

 File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 99, in _run
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 76, in func_wrapper
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/commands.py", line 126, in password
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1576, in update_password
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/keystore.py", line 305, in update_password
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/keystore.py", line 301, in check_password
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/bitcoin.py", line 749, in deserialize_xprv
  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/bitcoin.py", line 733, in deserialize_xkey
TypeError: object of type 'NoneType' has no len()

**Comment by ecdsa** [comment]
could you please answer the questions asked?

**Comment by brandonjabr** [comment]
And yes the seed was made by Electrum and is BIP32

**Comment by ecdsa** [comment]
are the master public key in your wallet and in the restored wallet the same?

**Comment by brandonjabr** [comment]
No actually those dont seem to be the same

**Comment by ecdsa** [comment]
ok, I see 3 possibilities:
 - The seeds are not the same (you made a typo)
 - You created the wallet with a development version of Electrum, before 2.0 was released (from github).
 - Someone or something modified the wallet file and replaced the xpub (in other words, your computer has been compromised)

I believe the first option is the most likely. 
if it's not the case, I can have a look if you email me your wallet file (ENCRYPTED WITH PGP)

**Comment by brandonjabr** [comment]
I think it is the second actually, when was 2.0 released? I made the original wallet well over a year ago

**Comment by ecdsa** [comment]
version 2.0 was released in March 2015, but I think the seed version was stable already in dec 2014.
have you used the github repository before that date? 
if you have done that, any official release of Electrum should have refused to open the file after you upgrade.

**Comment by ecdsa** [comment]
closing, no answer
