### ISSUE TITLE
Not work Replace-by-fee (Low fee)

### ISSUE THREAD

**Issue by EarlVadim** [spesmilo/electrum#2216]
Hello. 
Yesturday I create of transaction https://blockchain.info/tx/7430413049ff253d241d04b275d36ae41a44310484ba39908ffb2f4398e8c9a2

it marked as Low fee. .  
Today I enable   Tool-> Options -> Enable Replace-by-fee and create new transaction
https://blockchain.info/tx/c9a02eaff4a00290fafed2f124fb70238235cd7f1965dec7811a6842407336c9
with enable checkbox  "Replaceble" ... 

In total:  second transaction is complete, my first transaction "Low fee" as usual...

What I can do more?!!!

**Comment by JazzTp** [comment]
Hi,

Newbie here but I'm pretty sure that "enable replace by fee" works for
transactions created AFTER you activate the option, and marked as
replaceable.

For the other one, maybe it can be treated like unconfirmed transactions,
by creating a "child pays for parent" transaction to increase the
associated fee (somebody with more expertise might confirm or correct me).

In order to do that, you might want to see

http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

and

#2153 and #2056

**Comment by EarlVadim** [comment]
But,.. Last wallet is 2.7.18 havn't option "child pays for parent"

**Comment by EarlVadim** [comment]
I don't understand, what I can do????

**Comment by JazzTp** [comment]
You haven't checked out the links I've pointed you to.

**Comment by EarlVadim** [comment]
I read it, but i don't understand. not see solve of problem.

**Comment by JazzTp** [comment]
I also pointed you to two issues where the creation of "child pays for
parent" transactions was discussed:

In #2056 I described step by step how I could do it.

In #2153 a more knowledgeable user confirmed that those steps had been
correct (he also suggested another way to do it in earlier versions of
Electrum).

**Comment by EarlVadim** [comment]
I read it...   
" then went to the "Coins" tab, right-clicked on the address "   - i try do it.. but, in Coins-tab i havn't any addresses, and on Right-click nothing...

**Comment by JazzTp** [comment]
Maybe if you could share the transaction id some more knowledgeable user
could help...

Also, I read, in case of an unconfirmed transaction, the person to whom you
sent the transaction can create a "child pays for parent" transaction by
creating a transaction which spends the unconfirmed incoming coins you sent
him, by sending them to himself.

I guess he would see an "unconfirmed parent" error but then miners should
associate and sum fees and both transactions should go through.

NOT SURE, but if you don't do anything at all, I think there should be a
time limit (one week? more?) after which the transaction expires and funds
are again available in your balance for spending... provided you can do
that by arranging someway with the other person.

(I need to move and do stuff elsewhere I won't be able to check here for a
while, sorry, anyway I've pretty much shared what I know.)
