### ISSUE TITLE
Lost wallet

### ISSUE THREAD

**Issue by sergej-shkuruk** [spesmilo/electrum#2217]
There was one purse. I worked with him and mainil him bitcoins. Then he disappeared and appeared in another. How can I regain access to my wallet?

**Comment by ecdsa** [comment]
what disappeared? can you reformulate with more details?

**Comment by sergej-shkuruk** [comment]
I checked Electrum ,got the wallet 1MPp6TmVENsQTvFzvsQSre93qT5tkEpEfz . Mainil him NiceHashMining . Today opened Electrum .Prescribed to obtain a purse 1PqhRFTN6NheC9NLB4VizMqcHpL9DtvKla. How to regain access to my wallet 1MPp6TmVENsQTvFzvsQSre93qT5tkEpEfz ?

**Comment by ecdsa** [comment]
open the addresses tab (ctrl+A), visit the address you want, open the drop down menu and select 'request payment'. does that solve your issue?

**Comment by sergej-shkuruk** [comment]
Yes. Thank you for your help. Please tell me how to check the balance of the purse. ?

**Comment by ecdsa** [comment]
the balance of each address is displayed in the addresses tab.

**Comment by sergej-shkuruk** [comment]
[url=http://uploads.ru/Xgn97.jpg][img]http://s4.uploads.ru/t/Xgn97.jpg[/img][/url]
[url=http://uploads.ru/BcECM.jpg][img]http://s3.uploads.ru/t/BcECM.jpg[/img][/url]

**Comment by sergej-shkuruk** [comment]
<a href="http://uploads.ru/tvWq5.jpg"><img src="http://s0.uploads.ru/t/tvWq5.jpg" border="0" /></a>
[url=http://uploads.ru/tvWq5.jpg][img]http://s0.uploads.ru/t/tvWq5.jpg[/img][/url]

**Comment by sergej-shkuruk** [comment]
<a href="http://uploads.ru/xb5nu.jpg"><img src="http://s7.uploads.ru/t/xb5nu.jpg" border="0" /></a>
<a href="http://uploads.ru/TCtia.jpg"><img src="http://s8.uploads.ru/t/TCtia.jpg" border="0" /></a>
