### ISSUE TITLE
Unconfirmed parent / low Fee

### ISSUE THREAD

**Issue by yoshidu91** [spesmilo/electrum#2219]

**Comment by yoshidu91** [comment]
Hello i'am a new user of electrum and i send bitcoins to an other wallet and this is write 'unconfirmed parent' in my first transaction and 'Low Fee' in my second . can you tell me what is the signification of this message . Sory for my english

**Comment by JazzTp** [comment]
Hi, newbie here.

Unconfirmed parent: maybe you tried to spend coins from an unconfirmed
transaction.

Low fee: I suggest you keep the "dynamic fees" option active, as well as
"enable replace by fee",  and mark any outgoing transaction as replaceable,
so you will be able to easily raise the associated fee in case your
transaction remains unconfirmed longer than you can wait for it to go
through.

Also, you might want to check out

http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

and previous issues

#2153 and #2056
