### ISSUE TITLE
Wishlist: make electrum more tor friendly

### ISSUE THREAD

**Issue by captainchap** [spesmilo/electrum#222]
I would like to use electrum trough tor, but the tor network is slow and electrum's connection timeout and retry intervals are too short; electrum ends up hammering the tor proxy and it take a long time to successfully connect to a server. Could you make these intervals configurable or, better yet, create a tor mode that increases all timeouts and retry intervals as needed?

The final touch would be to have a dedicated list of .onion servers for this "Tor mode".

**Comment by ecdsa** [comment]
works for me
