### ISSUE TITLE
Transaction stuck for more than 72 hours on electrum

### ISSUE THREAD

**Issue by aventadorie** [spesmilo/electrum#2221]
Transaction ID 
3825138f6867819ee051c0a0d0ddde2d824f9e975834ba3ae698695bd09e7901

0 confirmations

Please help
https://blockchain.info/tx/3825138f6867819ee051c0a0d0ddde2d824f9e975834ba3ae698695bd09e7901

**Comment by JazzTp** [comment]
Hi, newbie here, you might want to see

http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

and check out these previous issues:

#2153 and #2056
