### ISSUE TITLE
what's going on with this wallet? 

### ISSUE THREAD

**Issue by EarlVadim** [spesmilo/electrum#2223]
I tried to send the tx with fee of 0.0002.  It hung a day, but returned. 
I increase fee to 0.0030 and sent again .. https://blockchain.info/en/tx-index/227328268
now, it also hangs a day and stated that the fee again 0.0002 .. 
And today there was some kind of second TX?
https://blockchain.info/en/tx-index/227328268
What does it mean?

**Comment by bauerj** [comment]
You tried to spend the same input twice.

A fee of 0.0009824 BTC (80.196 sat/B) won't get you far:
https://bitcoinfees.21.co/

According to their statistics, 220 sat/B would be a decent fee right now.

If you use a recent version of Electrum, you can use the dynamic fee feature so you won't have to worry about calculating the right fee manually.

**Comment by EarlVadim** [comment]
Ok.. TX is cancelled,  
I make TX again with  the dynamic fee ... and NOTHING!!!
My TX have "Low fee" again!!!   
https://blockchain.info/en/tx-index/227980758
WHY????!!!!

**Comment by ecdsa** [comment]
if you enable dynamic fees, the wallet needs a few seconds to download the fee estimates, otherwise it still uses static fees. I recently pushed a fix to correct that. In the meantime, make sure your wallet is fully synchronized before creating a new transaction.

**Comment by EarlVadim** [comment]
at last!!!
payment is completed.
thank you .. but, I are unlikely again will use Bitcoin.
