### ISSUE TITLE
One time nag screen to notify users of static fees

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#2224]
There are a lot of reports of people wondering about the fee slider behaviour (suggesting a "low fee" or suggesting 25 blocks as 2nd to best setting).
Turns out these are users unaware they are still on "static fees".

My suggestion for a future version: 

Upon start or send check if static fees are set and whether the nag screen has already been shown. 
If yes, display a secreen saying something along the lines of ""Warning: You're using static fees. This is not the recommended default setting for new installations anymore and can lead to long confirmation times.  If you're an expert and intend to keep static fees click abort otherwise click OK to set dynamic fees"".
Act according to user choice (i.e. keep setting or switch to dynamic)
Then save that the nag screen has been shown

**Comment by ecdsa** [comment]
dynfees were not default until you open the settings, this was missing: 83e925c0cd31e31c467343c39fba0f889157f21a

we should try with that first, before adding a nag screen
