### ISSUE TITLE
My btc stuck with unconfirmed for about 1 day

### ISSUE THREAD

**Issue by electrumwallet123** [spesmilo/electrum#2227]
Really i need to wait so much :| my btc is stuck with unconfirmed transaction for 1 day
I use 0.0005 fee but really 1 day and still unconfirmed!!
How i can recover it back?
Thanks.

**Comment by shsmith** [comment]
Please read this: https://github.com/spesmilo/electrum/issues/2153

**Comment by electrumwallet123** [comment]
I do not know how to make CPFP im new to BTC can you help me?

Inputs: ccbf3541...87dd2427:0    1LjWYfY44x6dQipFM3E9CweoBUMxqWFpAP
Outputs: 18VXHPW8UMoXWD7fpq32BeWJAG4sAroLDo	     0.07713467
Tax id: 0eb5f5e85f30677675ec91e1b1abe3483ea87009350e940c38396a63209605af

What i need to do is still unconfirmed for 2 days.

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by electrumwallet123** [comment]
Well still don't know how to make it :| can you be more specify man:
Create a ‘child pays for parent’ transaction, with a generous fee. A CPFP is a new transaction, that compensates for the small fee of the parent transaction. It can be done by the recipient of the funds, or by the sender, if the transaction has a change output.

What's mean that!!! i go to preference and i check all box from Fee menu
Now i go and send for example 0.05000 BTC to another address BTC which anyway is mine?
Just that i need to do or what?
be more specify man im new to this i do not understand very well!!! that's BTC which is unconfirmed for 3 days the BTC address is valide just for 6 days after that i can't get those BTC anymore.
I have left 3 days if i can't confirm it i lose those BTC.
Help please and do not close the ticket again :|.
