### ISSUE TITLE
Modify RBF transactions

### ISSUE THREAD

**Issue by inaltoasinistra** [spesmilo/electrum#2228]
Among the advantages of RBF there is the possibility of update transactions, not only the fee is upgradable.
In these days of long confirmations is not uncommon to make a new transaction while the previous is not confirmed yet. It would improve scalability and decrease the fee if it is possible to add an output (and sometimes and input) to an existing transaction instead of create a new transaction.

**Comment by ecdsa** [comment]
closing this. the requested feature has been added as "RBF batching", a few months ago...
