### ISSUE TITLE
p, li { white-space: pre-wrap; }  error: The transaction was rejected by network rules.  (258: txn-mempool-conflict) 

### ISSUE THREAD

**Issue by martinsoul07** [spesmilo/electrum#2230]
What does it mean? how to solve a problem?

**Comment by ecdsa** [comment]
you probably created a transaction before your wallet was synchronized.

**Comment by martinsoul07** [comment]
What now?

**Comment by martinsoul07** [comment]
What now?

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

3. Mar 2017 16:27 by notifications@github.com:

**Comment by JazzTp** [comment]
The answer, to me, newbie, clearly meant "try again but wait a bit more,
before (*), so that your wallet gets fully synchronized".

(*) Before broadcasting or even before creating the transaction, better, I
guess.

**Comment by martinsoul07** [comment]
sorry. I do not understand
