### ISSUE TITLE
Does not display the balance of the wallet electrum

### ISSUE THREAD

**Issue by sergej-shkuruk** [spesmilo/electrum#2233]
Does not display the balance of the wallet electrum.What to do? On kashelek is mining and the balance is zero. Where is the error? Electrum wallet doesn't work?
<a href="http://uploads.ru/sBMPF.jpg"><img src="http://sf.uploads.ru/t/sBMPF.jpg" border="0" /></a>
<a href="http://uploads.ru/yNadj.jpg"><img src="http://sf.uploads.ru/t/yNadj.jpg" border="0" /></a>
<a href="http://uploads.ru/WLHZj.jpg"><img src="http://sd.uploads.ru/t/WLHZj.jpg" border="0" /></a>
http://uploads.ru/sBMPF.jpg
http://uploads.ru/yNadj.jpg
http://uploads.ru/WLHZj.jpg

**Comment by ecdsa** [comment]
please paste the bitcoin address

**Comment by sergej-shkuruk** [comment]
18QrpKNvz4rcXcgz22s6QXNyDBbPV7P3i3

**Comment by ecdsa** [comment]
the balance of that address is zero, therefore it is correctly displayed.
can you explain what your problem is?

**Comment by sergej-shkuruk** [comment]
the program NiceHashMiner — 1.7.3.12( seen in attached photo) shows that the balance on this wallet 0.00094375 BTC . Wallet shows 0 .?

**Comment by ecdsa** [comment]
well maybe that program is lying to you?

**Comment by JazzTp** [comment]
You can check the address balance in http://blockchain.info

Here, if I did not operate badly from my phone, it is here (actually at
present zero):

https://blockchain.info/address/18QrpKNvz4rcXcgz22s6QXNyDBbPV7P3i3

**Comment by sergej-shkuruk** [comment]
03.03.2017, 20:45, "Nicola Bernardelli B." <notifications@github.com>:You can check the address balance in http://blockchain.infoHere, if I did not operate badly from my phone, it is here (actually atpresent zero):https://blockchain.info/address/18QrpKNvz4rcXcgz22s6QXNyDBbPV7P3i3—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.I have attached screenshots. Your program NiceHashMiner shows that the account has funds. Where do I Maini, and that it in this case, shows?

**Comment by sergej-shkuruk** [comment]
Your program NiceHashMiner shows that the account has funds. Where do I Maini, and that it in this case, shows?

**Comment by ecdsa** [comment]
sorry but I don't understand your English. 
you probably need the help of a translator.

**Comment by sergej-shkuruk** [comment]
Seen in the photo . The program NiceHashMiner reports on the successful transfer of funds to the wallet.

**Comment by sergej-shkuruk** [comment]
<a href="http://uploads.ru/WaZeV.jpg"><img src="http://s8.uploads.ru/t/WaZeV.jpg" border="0" /></a>
<a href="http://uploads.ru/SzQ0A.jpg"><img src="http://s7.uploads.ru/t/SzQ0A.jpg" border="0" /></a>
<a href="http://uploads.ru/kx8Km.jpg"><img src="http://s1.uploads.ru/t/kx8Km.jpg" border="0" /></a>

**Comment by sergej-shkuruk** [comment]
[url=http://uploads.ru/WaZeV.jpg][img]http://s8.uploads.ru/t/WaZeV.jpg[/img][/url]
[url=http://uploads.ru/SzQ0A.jpg][img]http://s7.uploads.ru/t/SzQ0A.jpg[/img][/url]
[url=http://uploads.ru/kx8Km.jpg][img]http://s1.uploads.ru/t/kx8Km.jpg[/img][/url]

**Comment by ecdsa** [comment]
I am not the author of NiceHashMiner
please report the problem to them.
