### ISSUE TITLE
Non standard Multisig support?

### ISSUE THREAD

**Issue by jmliz** [spesmilo/electrum#2234]
Does Electrum provides non standard multisig support for P2SH addresses? I know it's possible for standard multisig, but what if the transaction requires more specific conditions?

It would be *awesome* if Electrum provided some way to specify the script hash from the UI (like a QR code) and I wonder if this can it be done now with the command line.

**Comment by ecdsa** [comment]
sorry but you are not clear. are you talking about spending or sending to?

**Comment by jmliz** [comment]
@ecdsa I mean creating and spending non standard p2sh. for example, with additional opcodes like op_if,  op_checksequenceverify, etc. that would allow more flexibility.

**Comment by ecdsa** [comment]
that is not supported at the moment.

**Comment by jmliz** [comment]
ok thanks!
