### ISSUE TITLE
BTC stuck for 3 days

### ISSUE THREAD

**Issue by electrumwallet123** [spesmilo/electrum#2240]
Well still don't know how to make it :| can you be more specify man:
Create a ‘child pays for parent’ transaction, with a generous fee. A CPFP is a new transaction, that compensates for the small fee of the parent transaction. It can be done by the recipient of the funds, or by the sender, if the transaction has a change output.

What's mean that!!! i go to preference and i check all box from Fee menu
Now i go and send for example 0.05000 BTC to another address BTC which anyway is mine?
Just that i need to do or what?
be more specify man im new to this i do not understand very well!!! that's BTC which is unconfirmed for 3 days the BTC address is valide just for 6 days after that i can't get those BTC anymore.
I have left 3 days if i can't confirm it i lose those BTC.
Help please and do not close the ticket again :|.

**Comment by shsmith** [comment]
the process is described in detail here: https://github.com/spesmilo/electrum/issues/2153

**Comment by shsmith** [comment]
Did your tx finally confirm?
If not, please post the txid.
