### ISSUE TITLE
My BTC gone!!!

### ISSUE THREAD

**Issue by slukeemery** [spesmilo/electrum#2241]
Hi,

I had 0.4 BTC moving from a vendor to myself - https://blockchain.info/tx-index/7d9ff31014755ca281f327fff3df8cca6d385bf2f000fc9174b7400f726ff83a.

It was showing up in my wallet as unconfirmed parent and now it has disappeared?!!

Has your wallet just lost me 0.4 BTC?

**Comment by JazzTp** [comment]
Hi,

Newbie here, checked your link, your transaction is at present still
unconfirmed, so the wallet lost nothing.

The associated fee 44.248 satoshi/Byte is not expected to give a fast
delivery, you might want to check up these pages:

https://bitcoinfees.21.co/

https://support.21.co/bitcoin/transactions-and-fees/how-do-i-calculate-my-transaction-fee

As for "seen then disappeared", I'm unable to figure out a reason with
certainty...

Maybe - purely speculating now - the vendor saw the stuck transaction and
created a "child pays for parent" one to sum up more fees... or he had
created it with "enable replace by fee" active and "replaceable", and did
replace it... Not sure what the visible effect would be on your side,
though.

**Comment by shsmith** [comment]
Your tx is now confirmed.

**Comment by dabura667** [comment]
Your transaction has confirmed, @slukeemery 

Please confirm that you have seen the 0.4 BTC on your wallet at 1GCwUKQ94VYXT5BXATntt2ayysChRZEfZB
