### ISSUE TITLE
Sign transaction command line not working

### ISSUE THREAD

**Issue by angelsilva** [spesmilo/electrum#2242]
Hi friends, I am trying to run a transaction in electrum per console:

electrum payto -f 0.0003 -F 19LYUf4NSvmAq5ZbJKTAHWYbMFz4uj2AYf 1E1vDcXnYEnhP8jaJWbSnLDThEM5rmXLFn 0.001 --unsigned | electrum signtransaction --privkey [PRIVATE_KEY_FOR:19LYUf4NSvmAq5ZbJKTAHWYbMFz4uj2AYf] - | electrum broadcast -

However, the following error is generated:

error: The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation))\n[0100000001f87cbcafd5bb1605cb61922a05d1c0fb2f91542778702efc1dda4c674834dbd3010000005701ff4c53ff0488b21e0000000000000000005b98d5e7bf71c012fe95da0fda275e2d532775c0ffe19a2b357b5217639c4ceb03f19d0b9df05db93e03bb5d12cfc07fb59d9d6459195b641e17ade2696254f3c801000100ffffffff0250c30000000000001976a914dc34f3f00d49bf1dfb910ad7b8ca985048e8382f88aca0860100000000001976a9148ec60f132dd3e89c1573d7becf1f1133f6c162a188ac00000000]

I have noticed that the transaction before and after signed with the private key is identical, as if it were not signing, my version of electrum is: 2.7.18. If someone is so kind to help me, I thank you. Happy day.

**Comment by fizgig10** [comment]
I'm having the same problem.  Multiple input transactions don't seem to be signed by three Linux offline client.  Using 2.8.2 on both windows and Linux.
