### ISSUE TITLE
problem with transaction

### ISSUE THREAD

**Issue by evg77** [spesmilo/electrum#2243]
f949d1481cfb44ebaceca3228e90113767791ba84026aa9946039f0329ed9314

blockchain : Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned from our database.

the translation hasn't taken place. there are no coins also on a purse.

**Comment by dabura667** [comment]
Your transaction is "20 satoshis / byte" of fees.

https://bitcoinfees.21.co/

Currently there are over 35000 transactions with 11-20 satoshis/byte fees waiting to confirm...

It will likely never confirm.

You need to re-create the transaction with a higher fee.

How did you create the transaction?

**Comment by evg77** [comment]
how to recreate the transaction with higher collection?

**Comment by dabura667** [comment]
How did you create the first transaction?

**Comment by evg77** [comment]
has specified number of a purse and the commission. has pressed "to pay"

**Comment by dabura667** [comment]
I'm sorry. I can't understand you... What language do you speak? Maybe someone can speak the language... or Google Translate might be helpful...

**Comment by evg77** [comment]
I have entered the address into "translation" purse bitcoin, have specified fee, have pressed to send

**Comment by evg77** [comment]
coins bitcoin aren't available in a purse though блокчейн has written that the tranaktion is cancelled by system

**Comment by evg77** [comment]
blockchain*

**Comment by evg77** [comment]
why are you silent?

**Comment by evg77** [comment]
I can't change fee in a purse. what shall I do? support in general works for electrum?

**Comment by shsmith** [comment]
This may help: https://github.com/spesmilo/electrum/issues/2219 https://github.com/spesmilo/electrum/issues/2153

**Comment by shsmith** [comment]
Your tx has a single output to 1CbfpAa2vxiKdbGCs5SduLuyF1JJQf6yFV. 

If you control this address, you can try spending from this address to another address in your wallet. You need to include a much higher fee. This will cause the original tx and your new tx to be confirmed at the same time.

If you do not control this address, but you know the person who does, you can advise them to do the same thing (spending the unconfirmed input to another address with a higher fee).

In the future you can avoid this situation by enabling "Dynamic Fees" and "Enable Replace By Fee" and by checking "Replaceable" each time you send a new tx.

**Comment by evg77** [comment]
I can't operate 1CbfpAa2vxiKdbGCs5SduLuyF1JJQf6yFV the address. It is Poloniex.

**Comment by evg77** [comment]
bitcoin will arrive in this respect ever (7 days or 14 days for example) or transaction is cancelled by blockchain?

**Comment by shsmith** [comment]
You could attempt a double spend. To do that, connect to a different electrum server that does not have your tx in its memory pool. Try raspi.hsmiths.com ssl port 51002. This will make the tx disappear from your history. You can then attempt to send again, but this time using about 10 times higher fee (200 satoshi/byte instead of your current 20 satoshi/byte).

I submitted your tx to the https://www.viabtc.com/tools/txaccelerator/
This has helped some other stuck txs to confirm faster. If that workes, your tx may confirm within a few hours.

**Comment by evg77** [comment]
I have understood thanks. Excuse for my English. I use an online translator. Thanks for yours help.

**Comment by shsmith** [comment]
Your tx has confirmed. Most likely it was due to the viabtc txaccelerator.

**Comment by evg77** [comment]
it will be to me a good lesson. thanks once again
