### ISSUE TITLE
Electrum 2.7.18 Problem with certificate

### ISSUE THREAD

**Issue by Onkovat** [spesmilo/electrum#2246]
Electrum 2.7.18 Problem with certificate

![electrum error](https://cloud.githubusercontent.com/assets/12331722/23634146/138af7c4-02c9-11e7-981e-88a7d85c9291.png)

I do not see what the problem of this can be. Can someone help me with this? Does someone know how I can fix this?

**Comment by bauerj** [comment]
Is this Windows 7? Portable Electrum? Does it happen every time you start Electrum?

**Comment by Onkovat** [comment]
I'm using electrum portable on windows 7 pro, yes. This error does not happen on start. It only shows up when I signed a transaction and try to broadcast it. And only after I updated to the newest electrum version.

**Comment by Onkovat** [comment]
I found the cert directory. After deleting all files in there I could send again.
