### ISSUE TITLE
Electrum problem with descriptions

### ISSUE THREAD

**Issue by qiuchu2017** [spesmilo/electrum#2248]
Why notes under the electrum wallet descrptions lable were disappeared?

**Comment by ecdsa** [comment]
there is no useful information in your report.
please provide more details.

**Comment by qiuchu2017** [comment]
All of the notes which I typed on my Electrum app to describe the transactions were disapeared when I opened the desk app again.

**Comment by ecdsa** [comment]
I cannot reproduce that. Are you on Windows 7?
It might be Windows failing to write the file to disk (there are other issues open about that).

**Comment by ecdsa** [comment]
also, if you write your wallet to a usb stick, be sure to eject the volume before unplugging it.
