### ISSUE TITLE
A problem with Google Authenticator code

### ISSUE THREAD

**Issue by h54style** [spesmilo/electrum#2249]
Did get my transfert cause of an invalid otp.
Please, any skills?

**Comment by ecdsa** [comment]
please read the online documentation, or write a better description of your issue.

**Comment by h54style** [comment]
Yes, of course, sorry for my english. But Imean, I use my wallet one time few month ago and I have lost le google authenticator app. Instead, I've still my seed and my password, but when a redownload the app of google I think I didn't got a good code

**Comment by ecdsa** [comment]
restore from seed, and request a new authenticator code

**Comment by h54style** [comment]
thks Thomas
