### ISSUE TITLE
BTC Transaction disapparead after being sent

### ISSUE THREAD

**Issue by 123Aurelius** [spesmilo/electrum#2251]
Greetings,

I've sent a Bitcoin payment but it hasn't shown confirmation and hasn't even shown in my transaction list.  The transaction was sent to address '1M6qa5Dtqpjbh45aSdzRDZUYPdjQHcfRgA' but nothing is showing as sent or received. I'm perplexed as to why it's happening. I haven't had problems sending or receiving the last few payments. My fees are above default and multiplied. It's like I click sent and nothing happened.

Any help is appreciated. Thanks much.

**Comment by bauerj** [comment]
I couldn't find any transaction to that address.

It's safe to just send the transaction once more as long as you spend the same coins.

Was there an error message or something like that? Do you have the transaction in your history?

**Comment by 123Aurelius** [comment]
I didn't receive any error message or anything like that.

Here is the BTC Transaction: 134d6959ecdac811b7dc256138504c6677395dc97d34d7ce7721ac7550936a69

My wallet isn't showing any transaction on that date, though.

**Comment by bauerj** [comment]
That's from a week ago and to a different address.
