### ISSUE TITLE
Lost telephone with 2fa and keys

### ISSUE THREAD

**Issue by eugcamp93** [spesmilo/electrum#2252]
Hello

Someone stole my telephone with 2fa keys and all seeds saved. Is there a way to recover my money on the wallet?

**Comment by bauerj** [comment]
Sure, just restore from seed.

**Comment by eugcamp93** [comment]
I had the seed saved on that telephone 

    Il Martedì 7 Marzo 2017 19:36, Johann Bauer <notifications@github.com> ha scritto:
 

 Sure, just restore from seed.—

**Comment by bauerj** [comment]
If you have no backup of either the seed or the second factor, you can't restore your wallet.

**Comment by ecdsa** [comment]
It is not possible to recover your funds from the wallet, that's the point of 2FA. The only thing you can do it contact TrustedCoin and convince them that you are the legitimate owner of the funds. The will check your identity.
