### ISSUE TITLE
Electrum 2.7.18 Does not work off-line

### ISSUE THREAD

**Issue by jimmysong** [spesmilo/electrum#2253]
```
root@ubuntu:~# electrum --offline
No systemtrayicon available
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 343, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 257, in init_gui
    self.gui.main()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 208, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 174, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 147, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 126, in __init__
    tabs.addTab(self.create_history_tab(), _('History') )
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 689, in create_history_tab
    self.history_list = l = HistoryList(self)
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/history_list.py", line 55, in __init__
    self.refresh_headers()
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/history_list.py", line 59, in refresh_headers
    ccy = self.parent.fx.ccy
AttributeError: 'NoneType' object has no attribute 'ccy'

```
Most likely this is due to the fact that the exchange rate module is assumed to work, even if explicitly turned off using `use_exchange_rate = False` in the `electrum.conf` file.

**Comment by ecdsa** [comment]
known issue, fixed in master

**Comment by seanc-1** [comment]
image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1
image2.JPG
image1.GIF

Sean C.Campbell  image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1



Sean C.Campbell  Merchant Coinbase Bloomberg  Coinbase Bloomberg .PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1
image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1


Sean C.Campbell  Merchant Coinbase Bloomberg age1


Sean C.Campbell  Merchant Coinbase Bloomberg 


Sean C.Campbell  Merchant Coinbase Bloomberg 


Sean C.Campbell  Merchant Coinbase Bloomberg 

Sean C.Campbell  Merchant Coinbase Bloomberg 


Sean C.Campbell  Merchant Coinbase Bloomberg .PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1
image2.JPG
image1.GIF

Sean C.Campbell  image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1



Sean C.Campbell  Merchant Coinbase Bloomberg  Coinbase Bloomberg .PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1
image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1


Sean C.Campbell  Merchant Coinbase Bloomberg age1


Sean C.Campbell  Merchant Coinbase Bloomberg 


Sean C.Campbell  Merchant Coinbase Bloomberg 


Sean C.Campbell  Merchant Coinbase Bloomberg 

Sean C.Campbell  Merchant Coinbase Bloomberg 


Sean C.Campbell  Merchant Coinbase Bloomberg .PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.image1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGimage1.PNGPNGimage1PNGimage1


Sean C.Campbell  Merchant Coinbase Bloomberg


Sean C.Campbell  Merchant Coinbase Bloomberg 


Sean C.Campbell  Merchant Coinbase Bloomberg


Sean C.Campbell  Merchant Coinbase Bloomberg
