### ISSUE TITLE
bitcoin stuck in limbo all day!!

### ISSUE THREAD

**Issue by thatbguy** [spesmilo/electrum#2254]
i didnt think the fee was too small, purchaced bitcoin for time sensitive matter and now its stuck. need to get this confirmed asap any help please??

**Comment by shsmith** [comment]
See http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

These pages go into more detail:
https://github.com/spesmilo/electrum/issues/2153 and https://github.com/spesmilo/electrum/issues/2056
