### ISSUE TITLE
Request for User Friendly CPFP

### ISSUE THREAD

**Issue by LousyCrypto** [spesmilo/electrum#2255]
Increasing fees are resulting in a lot of stuck transactions. Electrum makes CPFP easy enough for experienced users, but many beginners don't even know it's possible to do. (They can wind up getting price gouged, like [this service](https://i.redd.it/tj3wi4v9pujy.png) that charges about 10 mBTC/kB.) Electrum could help address the issue by allowing the user to easily set up a CPFP transaction. (e.g., right-click on the stuck transaction, click "accelerate with CPFP", or something like that.)

**Comment by shsmith** [comment]
This feature is already present in the git-head version and will be included in the next release version.

**Comment by LousyCrypto** [comment]
That's great. (Guess I should check these things first...)

**Comment by JazzTp** [comment]
In the meantime, to avoid having to do CPFP transactions, you can activate
the "enable replace by fee" option and mark any outgoing transaction as
replaceable, so when it's unconfirmed you can easily and reliably increase
fees.

(Personally, I believe that if both conditions were activated by default,
developers here could avoid facing a whole lot of "unconfirmed" issues...
Looking forward to see the new feature anyway, I did not know about it.)
