### ISSUE TITLE
Send Transaction "Max" Button Replaced With "Fee-Inclusive"

### ISSUE THREAD

**Issue by t4777sd** [spesmilo/electrum#2260]
I think that the "Max" button is a potential area that may cause users to click without thinking and empty their wallet. Especially because it will replace any user-typed values without any alert box (a user may click max and think shoot wrong button and then quickly click send without realizing their user-inputted values were changed).

A much better solution is remove the Max button altogether. The Max button is simply a Fee-Inclusive transaction with the wallets balance as the amount. So, it makes much more sense to just support fee-inclusive transactions because they should be supported anyways. For example, someone may have an agreement to pay someone where the other part pays transaction costs (fee-inclusive).

So, for example, if a transaction is for 1BTC and the fee is 0.1BTC then normally this would cause 1.1BTC to be substracted from the wallet. With a fee-inclusive transaction it would cause 1BTC to be substracted, 0.9BTC to the receiver and 0.1BTC for the fee.

There is no loss in functionality. For the rare cases that someone wants to empty their wallet they would simply type their wallet balance as the amount to send and click fee-inclusive, which would empty the entirety of their wallet.

**Comment by ecdsa** [comment]
Electrum has had this functionality for a long time without a button, through the ! keyboard shortcut.
Because the button was not visible, users thought that the function was not available at all, and switched to other wallets.

**Comment by ecdsa** [comment]
Also, the use case of this button is less rare than what you think. 
You do not use it only to empty your wallet, but also to empty an address or a set of addresses.

**Comment by ecdsa** [comment]
so, keeping the button for now, unless you come up with a better proposal.

**Comment by t4777sd** [comment]
Would it be possible to add a confirmation or alert when clicking the button? At least in the cases where it overwrites user inputted data at a minimum? Silently overwriting user inputted values with a button click that may be clicked on error is pretty bad.

I made this ticket because someone sent me their entire wallet wallet balance as a result of this UI-issue. They had inputted data, clicked max, did not realize it rewrote the inputs they clicked and hit send without checking. They panicked, thought I hacked them somehow, and were quite stressed until I told them I will send them back the difference.

**Comment by fortran77** [comment]
Although I haven't had any problems with the send max feature in Electrum, in other contexts, with other software, heuristics to detect user errors have saved me many times.

Google has added many such heuristics to Gmail. For example, if you mention "attachment" in the body of an email and try to send it without attaching anything, Gmail will ask you if you're sure you want to do that. And this has been quite useful to me a couple of times.

I have a VOIP service that let me set the maximum per-minute rate I'm willing to pay for an outgoing call. Some day, if I try to return a call to some "473 scam" number that charges $10 per minute, it will save me.

In the Electrum case, if the user enters a send amount of x BTC, and then the send max feature changes it to 10x BTC, that's probably an error that the user might want to be warned about. Or, the software could require that send max be used only if the send amount has been left empty by the user, but allow editing of the amount after send max fills it in.

However, there could be an endless amount of user-protecting heuristics added to any software, and at some point they begin to come in the way of the user (and possibly make the code ugly).  So which ones to add are always going to be a judgement call for the implementor.

**Comment by t4777sd** [comment]
It probably makes sense to disable the max button if there is user inputted data. I agree  that you cannot protect against all user errors. however, this is more than user error, it is just bad interface design.

**Comment by fortran77** [comment]
In the spirit of "things should be as simple as possible, and no simpler", I propose the following solution.

The send max button can simply print a message: "To send all available funds, specify the amount to be sent as a single exclamation mark (!)."

**Comment by ecdsa** [comment]
@t4777sd done in 8cc8f8a
