### ISSUE TITLE
Electrum doesn't work with cyrillic usernames (?)

### ISSUE THREAD

**Issue by aa-novik** [spesmilo/electrum#2261]
Windows 10 x64.

Electrum (portable, standalone, installed) doesn't work on several computers. It starts when creating a new wallet, then it writes something like "Generating new wallets..." and suddenly closes. After these operations Electrum doesn't work at all: new processes appear in Windows Task Manager for a few seconds and close by themselves.

Google helped me to find the roots of the problem on Russian boadrs.

I live in a country where cyrillic alphabet is used. All Windows users on my computers have cyrillic names. So I've tried to create a new Windows user with only latin characters. Electrum works great in this case.

I think it's strange that Electrum doesn't work with national languages correctly in 2017 even in portable (!) version.

**Comment by ecdsa** [comment]
I believe this fixes it: 6318bda54d55c381d40057a76cdac843ac918936
version 2.8 will be released today, let me know if the issue persists
