### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by evg77** [spesmilo/electrum#2264]
Hello! The week can not get through. I understand that the low commission and many transactions are blockchain, but in other services such payments reach much faster under the same conditions. There is no confirmation for a week. What's happening? Number 97524e14759b5a631d59595da9f3470583d201d096736ef724d8f729bc123a36

**Comment by evg77** [comment]
Support electrum exists?

**Comment by ecdsa** [comment]
we are working ona new version of Electrum that will pay higher fees.
in the meantime, read the FAQ
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by evg77** [comment]
You are working on a new version, and I can not use my money for a week. I repeat. In third-party services such transactions at the same time have long gone !!!!!!!
