### ISSUE TITLE
Derivation strategy for Electrum wallets

### ISSUE THREAD

**Issue by jmliz** [spesmilo/electrum#2266]
found this. can someone confirm it's the same derivation scheme for electrum?

https://github.com/mazaclub/encompass/pull/56/files#diff-9a32635d4a93b6e41c91fec9e4001d4aR1559

**Comment by jmliz** [comment]
solved. read this. 
https://bitcoin.stackexchange.com/a/36956

thanks to Abdussamad from bitcointalk.

**Comment by dabura667** [comment]
Why would it be? That project has nothing to do with Electrum.

**Comment by ecdsa** [comment]
I don't know, and I do not have time to read the source code of that project in order to answer you.
you should read the source code of Electrum to know what Electrum is doing...

**Comment by jmliz** [comment]
@dabura667 @ecdsa  there's no standard specification for multisig derivation and it's not always feasible for all developers to read thousands of lines of code for every project to know which derivation was chosen, for example. I also don't have that much time.

If there's some standard used it would be great if you gave me some hints. thanks anyway.

**Comment by ecdsa** [comment]
if it's for a hardware wallet, see line 220 of base_wizard.py
for non hardware wallets we use the root.

**Comment by jmliz** [comment]
@ecdsa thanks! I'll check.

**Comment by jmliz** [comment]
thanks It's solved :) 

**answer**: the derivation strategy of the linked  implementation it's _Not_ compatible with Electrum wallet since it's modified to allow altcoins.

the derivation strategy of Electrum for standard and multisig wallets is:
- unlike bip45 the shared xpub is the root one.
- addresses are derived from root starting m/0/0.

closed.
