### ISSUE TITLE
transactions 

### ISSUE THREAD

**Issue by evg77** [spesmilo/electrum#2267]
Hello! The week can not get through. I understand that the low commission and many transactions are blockchain, but in other services such payments reach much faster under the same conditions. There is no confirmation for a week. What's happening? Number 97524e14759b5a631d59595da9f3470583d201d096736ef724d8f729bc123a36

**Comment by evg77** [comment]
You are working on a new version, and I can not use my money for a week. I repeat. In third-party services such transactions at the same time have long gone !!!!!!!

**Comment by evg77** [comment]
I will create until you give me an objective reason for the delays in my translation.

**Comment by ecdsa** [comment]
read this http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by evg77** [comment]
Why are you asking me to read this? You, besides copying the links themselves, can explain why Electrum my transaction can not hold in a week? I spent the whole week monitoring the status of the network on the site https://bitcoinfees.21.co/ and it should have been a long time ago ....

**Comment by evg77** [comment]
I will be satisfied with the answer of a competent officer in these matters. Judging by your answer, you do not understand

**Comment by evg77** [comment]
My transaction several times then disappeared from the block, then came back again. She even once disappeared completely out of her purse and this gives me the right to believe that my problems are related to the actions of Electrum itself, rather than the system of blockchain

**Comment by evg77** [comment]
Communicating on this topic in the forums, I realized that this situation is very often happening at Elektrum. Payments go much longer with equal commissions. To my regret, I learned this after I translated bitcoin

**Comment by evg77** [comment]
Ignoring the problem will not solve it, but only exacerbate it. It is unfortunate that the people responsible for Electrum's support are so different in their competence. I'm surprised why some people take it when the link copying functions can be assigned to the robot

**Comment by evg77** [comment]
There is no support. I have never met the worst. Usually this is how scammers act. Disgusting quality especially for the service of financial services. I will try to make sure that as many people as possible are warned about what awaits them if they trust to store their biton to you. I hope you leave this business.
