### ISSUE TITLE
Yellow Triangle - unconfirmed transaction

### ISSUE THREAD

**Issue by bear2596** [spesmilo/electrum#2268]
Hi there, 
Hi there, I am trying to send some bitcoins out from my electrum wallet. In the first collum were there is usually the two cogs and the world unverified, there is just a yellow triangle with an ! in the middle. the next collum says low fee. and that's it. I've been waiting a few hours now and I don't know whether to be worried. I am new to this. Thanks.
It has been like this for about three hours. Is there anything I can do?

**Comment by evg77** [comment]
You are still too early to worry ... I have had a week and all the same and support ignores

**Comment by bear2596** [comment]
have you had it the same as in it is unconfirmed with the yellow triangle, instead of the cogs?

**Comment by evg77** [comment]
yes

**Comment by ecdsa** [comment]
@bear2596 please read http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
if you use the latest release (2.8), you will have the possibility to create a CPFP transaction from the GUI
