### ISSUE TITLE
Cyrillic Windows user names again

### ISSUE THREAD

**Issue by aa-novik** [spesmilo/electrum#2269]
Hello. Thank you for a new release.

I've just tried to install and run Electrum 2.8.0 from Windows 10 x64 user with a cyrillic name, and I still have a problem with it.

As I can see, the new version created a directory in AppData/Roaming after start (a previous version 2.7.18 didn't create it), but it still doesn't work normally. Here is a screenshot of the last window which I can see:
http://oi65.tinypic.com/11vkzmg.jpg

After typing a password and clicking the "Next" button Electrum disappears from my screen and Windows Task Manager.

**Comment by ecdsa** [comment]
do you have the same issue if the username is latin and the wallet name is cyrillic?

**Comment by aa-novik** [comment]
As I see it works pretty good with the cyrillic wallet name:
https://imgdepo.com/id/10392248.jpg
