### ISSUE TITLE
not to use unconfirmed inputs

### ISSUE THREAD

**Issue by alexandrz** [spesmilo/electrum#2270]
Is it possible to configure electrum to avoid using unconfirmed inputs for new transactions?

**Comment by ecdsa** [comment]
no, there is no such option.
however, electrum always uses confirmed coins if possible.
it only uses unconfirmed inputs if there is no other way.

**Comment by alexandrz** [comment]
There is a bug then. I have a wallet with 6000 addresses and thousands of confirmed inputs, but it still uses newer unconfirmed inputs for new transactions. Before upgrading from some older version of electrum it never used unconfirmed inputs.

**Comment by alexandrz** [comment]
I sent you more info on the address I found in your github profile.

**Comment by ecdsa** [comment]
what is your coin selection policy?

**Comment by alexandrz** [comment]
priority

**Comment by ecdsa** [comment]
can you confirm that you are using the latest release?

**Comment by ecdsa** [comment]
I believe the issue was that some of your coins had unconfirmed parents.
that commit should fix it.

**Comment by alexandrz** [comment]
It's fixed. Thank you!
