### ISSUE TITLE
Right-click in Coins jumps immediately to Send tab without waiting for context menu

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2272]
Electrum 2.8 on Windows 10 gives a "Spend" context menu when you right-click on a coin in the coins tab.

Electrum 2.8 on on Ubuntu 16.04 briefly shows the "Spend" context menu, but then instantly jumps to the Send tab. I do not think this was intended.

**Comment by shsmith** [comment]
Also tested on Mac OS Sierra. Works fine there. Issue seems Ubuntu / Linux specific.

**Comment by ecdsa** [comment]
are you sure? I have ubuntu and I cannot reproduce that

**Comment by shsmith** [comment]
I tried again and can still reproduce, but I think I understand now what is different.

On Windows and Mac you can "tap" and release to get a context menu. You then navigate the menu and click again to make a selection.

On Ubuntu 16.04 the menu is visible only while you continue to hold the right click. As soon as the right-click is released the menu disappears. This happens in the Address list as well as the Coins tab. I went back to 2.7.18 and saw the same thing, so this isn't new to 2.8. Maybe not an issue as it is usable, but not consistent with how context menus work in other apps on the same system.

**Comment by ecdsa** [comment]
I can't reproduce that either...
are you sure other apps are not affacted?
maybe you changed something in your window manager?

**Comment by shsmith** [comment]
I did my testing on an old install that had been upgraded multiple times, so unusual settings are possible.
I tested in a clean install of 16.04 and was not able to reproduce.
