### ISSUE TITLE
iOS-App

### ISSUE THREAD

**Issue by BeardedBadass** [spesmilo/electrum#2274]
Hi,
I would like to create an electrumapp for iOS either from scratch (using the server API and implement it in C# or Swift) or creating a python library for iOS with kivy.
Did anyone start with something like this yet or do I have to go where no man went before? 
Thanks for your answer.
Kind regards

**Comment by ecdsa** [comment]
Electrum already has a kivy GUI, which is used in the Android app. 
It can be compiled for iOS. 
I have not done it yet, and I would be curious about your experience.
