### ISSUE TITLE
Password change dialog error message

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#2277]
If I go to wallet > password, enter nothing and press OK I sometimes get this error message:

>object of type 'NoneType' has no len()

And in one instance this message:

>Python int too large to convert to C long

It doesn't occur in all wallets. The common thread seems to be wallets of newer type 2.0+ and with 0 balance.

Electrum version is 2.8.0

**Comment by ecdsa** [comment]
are you using binaries or running from source?

**Comment by ecdsa** [comment]
I can reproduce the first message. it should be replaced by InvalidPassword.
I would like to know how you got the second one.

**Comment by AbdussamadA** [comment]
>are you using binaries or running from source?

Not sure what you mean by that. I'm on linux. I downloaded electrum from download.electrum.org and installed with pip2. 

The wallet that leads to the second error is attached. Password is tempistan


[muckabout.txt](https://github.com/spesmilo/electrum/files/834858/muckabout.txt)

**Comment by ecdsa** [comment]
thanks! I'll have a look tomorrow
