### ISSUE TITLE
Error in listaddresses with jsonrpc

### ISSUE THREAD

**Issue by angelsilva** [spesmilo/electrum#2279]
I have Electrum 2.8 Version.
When call listaddresses with jsonrpc:

curl --data-binary '{"id":"curltext","method":"listaddresses","params":{"funded":true}}' http://127.0.0.1:5001

This is the error:

{"error": {"message": "Server error:   File \"/usr/local/lib/python2.7/dist-packages/Electrum-2.8.0-py2.7.egg/electrum/commands.py\", line 490, in listaddresses | AttributeError: 'NoneType' object has no attribute 'get_addresses'", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}

PD: Electrum daemon is start and loaded wallet with: electrum daemon load_wallet

**Comment by dariusc93** [comment]
Odd... this should be fix but im getting the same error in 2.8.2. Any idea why?
