### ISSUE TITLE
[OSX] CPU >100% overload when encrypting

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#2281]
2.8.0 OSX
Opened old deterministic Electrum wallet (non-xpub) with 8 used/zeroed addresses with 2-3 TX each.
Wallet>Password, input 3 passwords correctly, "Encrypt wallet file checked", OK
Then in about a minute or less, this happens, and I have to force-quit:
![screen shot 2017-03-10 at 17 45 59](https://cloud.githubusercontent.com/assets/2625857/23819354/0354f29e-05ba-11e7-9340-c47f916b8a83.jpg)

The above repeats on every reattempt.

Is there some way to throttle back the CPU load when encrypting?

ETA: Since I didn't care about labels, what I just did was restore from seed and encrypt as the new wallet was freshly created, rather than waste any more time trying to encrypt the original one.

**Comment by ecdsa** [comment]
are you running electrum from python sources?
the binaries use PyCryptodome to speed up encryption, maybe you want to install it.
also, what is the size of the file with the labels?

**Comment by TheButterZone** [comment]
Electrum from https://download.electrum.org/2.8.0/electrum-2.8.0.dmg
I installed it, was told I needed to upgrade pip itself, so I did.
25.3MB with labels, 20KB labelless encrypted restore from seed.

Considering the ridiculous disparity in sizes, should I even bother messing with the original one anymore?

**Comment by ecdsa** [comment]
ok, installing pycryptodome is not relevant, because you are using a binary.
the slowness is caused by the size of your wallet file.
I remember there used to be a bug with the labels sync plugin, a long time ago.
that bug was duplicating labels and resulted in that kind of oversized wallet files.
