### ISSUE TITLE
Electrum Wallet not working on Windows 10

### ISSUE THREAD

**Issue by userpnha** [spesmilo/electrum#2282]
So I downloaded Electrum Wallet 2.7.18 Standalone Executible, the Windows Installer and the Portable Version and neither of them worked on my Windows 10 PC. I also tried to download previous versions but did not have sucsess. I tried to run it using Windows 7 and 8 compatibility mode, nothing. Just to make sure, I turn off Avast annnd no luck. It wont open, no matter what I do. I did not find any processes on the task manager.
It seems to be a little odd. Searching in forums I coudn't find anyone with the same problem, so I appreciate if somebody who has been through that could help me out!

**Comment by SomberNight** [comment]
A lot of code and build scripts changed since the issue was opened. Probably not applicable anymore. Closing.
