### ISSUE TITLE
Non-canonical signature: S value is unnecessarily high)' ,u'code':-26

### ISSUE THREAD

**Issue by parparanga** [spesmilo/electrum#2287]
I tried for the first time to Send one DASH, but obtained this error.
Please advise

Best regards
P.P.
![error when sending one dash to shapeshift](https://cloud.githubusercontent.com/assets/26366597/23835553/a7eceee6-0769-11e7-9f41-9c88c04f93d4.JPG)

**Comment by bauerj** [comment]
This repository is not related to Electrum-DASH. You need to contact the Electrum-DASH authors.
