### ISSUE TITLE
Unable to send BTC from wallet

### ISSUE THREAD

**Issue by jorodriguez97** [spesmilo/electrum#2289]
I get this error when I try to send BTC from my default_wallet to another (via BTC address):

object of type 'NoneType' has no len()

I have tried to restore my wallet via seed, but no luck because it gives me a "Please wait" and does not continue no matter how long I wait. 

My electrum is version 2.7.9

**Comment by ecdsa** [comment]
on which platform are you ? can you try with the latest version of Electrum?

**Comment by jorodriguez97** [comment]
I am using tails OS. Is there a way to update to the latest version? I do not see any 'check for update' features on it.

Thanks for the swift reply!

**Comment by ecdsa** [comment]
if it's on tails OS then then it's probably a server not answering, or answering too slow.
do you have the option to choose the server you are connecting to, before you type your seed?
disabling TOR might help too.

**Comment by ecdsa** [comment]
does your wallet have two-factor authentication? (if yes it might be this #2097 )

**Comment by JazzTp** [comment]
> I am using tails OS. Is there a way to update to the latest version?

(Answering from phone while traveling.)

If you can search issues for Tails... I commented about how I use the
latest Electrum on it, nothing difficult.
