### ISSUE TITLE
dynfees passes "-1 BTC/kB" if estimatefee returns -1

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#2292]
I can't seem to find code that deals with "-1" return by estimatefee on the client-side.

arubi on IRC posted this image
http://i.imgur.com/x9bzHLQ.png (Testnet with e-x)

making me believe electrum might in fact pass through the "-1"  (no info / too little info) as a dynamic fee. 

I thought 
https://github.com/spesmilo/electrum/blob/584b19a11e0a21c96e3659fefea82d169978b6f7/lib/wallet.py#L810 might deal with it, but doesn't appear to...

**Comment by fivepiece** [comment]
Seems like this is very much related to `Use dynamic fees` being on or off.  Turning it off, the wallet is usable again with setting any fee on the bar.
RBF also works now, before I could broadcast a very low fee tx then RBF it with another pretty low fee one, but anything above the middle bar would fail, showing the same negative value.
