### ISSUE TITLE
make_packages not working ubuntu1404

### ISSUE THREAD

**Issue by dadaista** [spesmilo/electrum#2294]
Hi, I get a strange ImportError: No module named pyaes when I try to build the code. I get the same with my usual ubuntu1404 and with a fresh install of same version in another machine.

If I load the module from python it works. However, the imp.find_module(module) fails in the line 29 (see below)

root@2d2e6c6314f3:/home/electrum# python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyaes
>>> pyaes
<module 'pyaes' from '/usr/local/lib/python2.7/dist-packages/pyaes-1.6.0-py2.7.egg/pyaes/__init__.pyc'>
>>> 
root@2d2e6c6314f3:/home/electrum# ./contrib/make_packages
version 2.8.1
Traceback (most recent call last):
  File "./contrib/make_packages", line 29, in <module>
    f, pathname, descr = imp.find_module(module)
ImportError: No module named pyaes

**Comment by ecdsa** [comment]
run setup first

**Comment by dadaista** [comment]
I did. This is why I can load the module from python shell.

**Comment by ecdsa** [comment]
that might be because the file /usr/local/lib/python2.7/dist-packages/pyaes-1.6.0-py2.7.egg/pyaes/init.pyc does not exist (it's an egg).

**Comment by ecdsa** [comment]
so, iirc it should work if you install pyaes using easy_install

**Comment by dadaista** [comment]
the egg seems to be the  issue. I'm trying a fresh install using setup.py sdist instead of install. It should install with sources. I'll write back for updates

**Comment by dadaista** [comment]
fyi, the egg issue is solved using 
`pip install .` 
instead of 
`python setup.py install`
