### ISSUE TITLE
Electrum dash 2.4.1 - help!

### ISSUE THREAD

**Issue by Mrtibbs316** [spesmilo/electrum#2296]
Hello .

I have an electrum dash wallet - version 2.4.1 - i recently tried to move some dash coins but i get an error message saying i cant do this, and need to upgrade to 2.5.1.

Only thing is there is no link to a 2.5.1 upgrade. ALmost like its not even out yet? 

Can someone please advise how i get round this?

Please note my knowledge is pretty basic, but if someone can provide a some assistance i would really appreciate it.

Thanks people

**Comment by bauerj** [comment]
Hi,

the authors of Electrum do not support Electrum-DASH. You will need to file your issue here:

https://github.com/dashpay/electrum-dash/issues
