### ISSUE TITLE
Error in paytomany command line with jsonrpc

### ISSUE THREAD

**Issue by angelsilva** [spesmilo/electrum#2297]
Hi, When i try this command:

curl --data-binary '{"id":"curltext","method":"paytomany","params":{ "outputs" : [ ["1FCFe7k8kkdkX2xvTG9iwKbif1fVQKYVzK","0.001"],["167gb24GBnKtdhvWk78dXanZutqBiU9Rob","0.001"] ],"tx_fee":"0.0003","from_addr":"1GDiRRGNMzB3rkXv79QRztznVgnqVBwNSV","unsigned":"true"}}' http://127.0.0.1:4999

This is the error:

{"error": {"message": "Server error:   File \"/usr/local/lib/python2.7/dist-packages/Electrum-2.8.1-py2.7.egg/electrum/commands.py\", line 433, in paytomany | NameError: global name 'to_satoshis' is not defined", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}

My version of electrum is: 2.8.1.

**Comment by ecdsa** [comment]
this was already fixed a few days ago.
