### ISSUE TITLE
In preperation for Oct 2017, Upgrade DNSSEC root_KSK

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#2300]
IANA is going to switch the DNSSEC root_KSK on 11th Oct 2017
which we hardcode here: https://github.com/spesmilo/electrum/blob/a3b4409e6e8d1c510f53494ca068633ce03f0cc7/lib/dnssec.py#L189

The reference is here, however I don't see the equivalent DNSKEY, so that needs to be found out
https://www.iana.org/dnssec/files

Ideally Electrum should use the new root_KSK if date is 11th Oct 2017 or later.

See also
https://www.heise.de/newsticker/meldung/DNSSEC-Schluesseltausch-2017-ICANN-setzt-Testseite-fuer-Resolver-auf-3653644.html

**Comment by EagleTM** [comment]
It appears icann does not yet publish both of them.

Once
dig . dnskey | grep  -e '^\.' | grep 257

returns both keys we can add the second one...

Reference: http://www.digitalinternals.com/internet/get-dnssec-root-keys/534/

**Comment by bauerj** [comment]
I'm not sure if relying on the system clock is a good way to make the switch anyway. What if the clock doesn't work properly? There would also be issues with timezones.

Maybe we should add the new KSK-2017 (as soon as we can get ahold of it) and modify `dnssec.py` to validate with either of them instead, as KSK-2010 should still be secure.

Once the root ZSK is signed with the new KSK, we can remove the old one (probably in October).

**Comment by EagleTM** [comment]
FWIW BIP70 TLS Certs also rely on system clock / date.

but yea verifying against both and if one works accept that and then phasing out the old key in a future release sounds good to me too

**Comment by bauerj** [comment]
It wasn't easy to find, but there it is 🎆 

    . 19722 IN DNSKEY 257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU=
