### ISSUE TITLE
BTCs stuck between Electrum and Alphabay

### ISSUE THREAD

**Issue by Stonesthrowing** [spesmilo/electrum#2304]
Hi,
5 days ago the money left my electrum wallet, has 807 and going confirmations with each one in- and output. I checked the address and it fits. How is it possible that I still get confirmations while the BTCs are withdrawn from the wallet (with a green check-symbol next to the transaction. Its more than 0.01 BTC.
Hope someone can help, I didnt find a similar case anywhere

**Comment by bauerj** [comment]
Hey,

basically, your transaction will get another confirmation every 10 minutes. What this means is that a new Bitcoin block will be mined that references to the previous block. So your transaction having 807 confirmations means that there are 807 blocks in the blockchain that confirm that the coins belong to the recipient of the transaction.

You can check that Electrum is showing the right data with a block explorer like [blockcypher.com](https://live.blockcypher.com/).

**Comment by Stonesthrowing** [comment]
Thanks for the explanation.
It still just seems to be a way too long duration for the transfer. It used to be a couple of hours max with minimum fee. I upped the fee because with a few trys before nothing happened, but at least the transaction was canceled by itself and I could try again. Now the BTCs are withdrawn but didnt arrive where they supposed to arricve...

**Comment by bauerj** [comment]
Your Bitcoin already "arrived" where they were supposed to arrive 807 blocks (about 5-6 days) ago.

**Comment by Stonesthrowing** [comment]
oh ok, thanks. Then I need to bother Alpha bay I guess...
