### ISSUE TITLE
Unconfirmed parent

### ISSUE THREAD

**Issue by kuziozmc** [spesmilo/electrum#2307]
Hello, 
I have a problem with unconfirmed parent. Whenever I see block explorer, i see "Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned from our database."
I have not done anything, one hour ago status of the transaction ws waiting for the confirmation, now seems like is cancelled. 
I had selected dynamic fees, so that should not be a problem with low fee issue. 
Transaction ID is: 54b98397bc82bbe7ee43619eaa9b5149c868a9a4a7ea5af8d1f71d120edeaa3c

Any ideas what to do next. I made the transfer yesterday around 7pm.

Any comments appreciated. Cheers

**Comment by dabura667** [comment]
Its confirmed
