### ISSUE TITLE
View on block explorer accidentally doxxes you

### ISSUE THREAD

**Issue by SirTristan78** [spesmilo/electrum#2308]
When you want to see a Xaction on the blockchain to know if it went you want to click "View on block explorer" but if you do this then your OS default browser is open.  But what if you're connected with Electrum to a SOCKS proxy and the browser you use isn't the default one because it's also connected to a proxy.

It would be better if View on block explorer lets you copy a link that you can paste in to your browser of choice or something so you don't accidentally giving away your transaction to your local network because you're using the default browser.

**Comment by ecdsa** [comment]
if you want to copy-paste something, why can't you copy-paste the txid?

**Comment by SirTristan78** [comment]
I don't know where that is and anyway where would I paste it?  The View on blockchain shouldn't mislead you into doing something that is different from the proxy settings you set up in the program you are clicking from.
 
Anyway it's easier to cut and paste a link right?  Where is the txid anyway and anyway where would I paste it?
 
-----Original Message-----

**Comment by ecdsa** [comment]
if you don't know where to paste the txid, I think you should learn that first.
I'm not going to add a new menu for that. it makes the GUI more complex without obvious benefit.

**Comment by SirTristan78** [comment]
You miss the whole idea that is when you set the SOCKS settings for the application you don't think anythign in the application is going to change that and hurt your anonymity.  Take out the whole button is better than have a button that does somethign that is different from the settings you already gave it.
 
Ur just mad because I'm not as smart as you about blockchain and txid and whatever.
 
-----Original Message-----

**Comment by dabura667** [comment]
"View on block explorer" is obviously talking about opening a website in a browser.

Electrum does not have a browser.

2 + 2 = 4 People connecting with TOR or SOCKS should not click that.

**Comment by dabura667** [comment]
@ecdsa We could just say:

```python
if not is_tor() and not is_socks():
    add_menu_item()
```

**Comment by ecdsa** [comment]
@dabura667 why so? you can use TOR both with your browser and Electrum.

**Comment by dabura667** [comment]
> can use TOR ... with your browser

We can't know if their system's default browser has TOR setup or proxy setup finished. So best to just remove the feature (if tor or proxy) or at least make a popup say (if tor or proxy) "Hey, you're using Proxy/Tor with Electrum, and we're gonna open your default browser to open the explorer. Would you like to continue?" to just let them know...

I think this user thought like "View in block explorer" would open some Electrum window (they didn't know what a block explorer was).

**Comment by SirTristan78** [comment]
> @dabura667 why so? you can use TOR both with your browser and Electrum.

But View on block explorer doesn't let you pick your browser.  I dont run my default browser with socks only the browser I want to use with socks.  So there should either be a choice of browser, a link to let me paste into the browser I wanna use, or no View on block explorer.

**Comment by SirTristan78** [comment]
> 2 + 2 = 4 People connecting with TOR or SOCKS should not click that.

No way.  Some people don't know what a block explorer is only in a browser.  I didn't until I clicked!  I thought it was going to be a new screen in Electrum showing me the blocks.  Thats most logical since I was in electrum.

**Comment by SirTristan78** [comment]
> o best to just remove the feature (if tor or proxy) or at least make a popup say (if tor or proxy) "Hey, you're using Proxy/Tor with Electrum, and we're gonna open your default browser to open the explorer. Would you like to continue?" to just let them know...

I think this user thought like "View in block explorer" would open some Electrum window (they didn't know what a block explorer was).

This.

**Comment by SirTristan78** [comment]
I just thought of something. T if everyone is smarter than me and knows that a txid goes on a website in a block explorer then why have the button at all you could just give the txid and let the smart people who know what to do with it paste it wherever they want.
