### ISSUE TITLE
Error When Setting Up KeepKey Wallet

### ISSUE THREAD

**Issue by PolkaD0T** [spesmilo/electrum#2311]
![keepkeyinstallerror](https://cloud.githubusercontent.com/assets/26518635/24079529/636f263e-0c47-11e7-8d16-3a652310e88a.png)

I received the error shown in the attachment when installing my KeepKey device on Electrum.

**Comment by ecdsa** [comment]
this was already fixed, see 2dc7ba96c4c6064fd0450d68430785ade9f42e50

**Comment by PolkaD0T** [comment]
This is a KeepKey device, not a Trezor; however, I'll try reinstalling.

**Comment by ecdsa** [comment]
I know. Just wait for the next release.
