### ISSUE TITLE
2 Minor GUI bugs

### ISSUE THREAD

**Issue by Coding-Enthusiast** [spesmilo/electrum#2312]
1. In `Tools > Preference > Fees tab > Propose Replace-By-Fee` doesn't have any help.
Adding something in here may be helpful in understanding how 3 options work.
https://github.com/spesmilo/electrum/blob/master/gui/qt/main_window.py#L2424

2. Same place `> Appearance tab` when changing "Base unit" doesn't update "Zeros after decimal" limitation. 
example:
* Changing "Base unit" from initial mBTC to BTC doesn't allow setting a value higher than 5 in "Zeros after decimal". You need to close Preference and open it again to be able to update 5 to a higher value.
* Changing "Base unit" from initial BTC to mBTC while "Zeros after decimal" is on 8 doesn't change 8 and setting it to 8,7,6 is still allowed. You need to close preference and open it again. Now value is on 5 but underlying GUI is not updated unless the value is changed from 5 to 4 and back again so it updates.

**Comment by bauerj** [comment]
1)  has already been changed so this will be closed once the fix to 2) is merged.

Thanks for reporting this!
