### ISSUE TITLE
Blockchain headers obtained from server on different chain prevent verification of transactions

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2314]
When one server is on a different chain that has a higher height than the majority chain, the client will download blockchain_headers from that server and the result is SPV verification failure for transactions. This happens even when "select server automatically" is unchecked and one of the majority servers is selected. 

It would be prudent to obtain headers from servers with the majority height rather than from a single server with the highest height.

**Comment by shsmith** [comment]
This has been happening on testnet since > 24 hours ago.
Here is an example:
```
[Network] switching to testnet.hsmiths.com:53012:s
[Network] sending subscriptions to testnet.hsmiths.com:53012:s 0 0
[Network] testnet.hsmiths.com:53012:s is lagging (1094605 vs 1094790)
[14.3.140.101] requesting header 1094793
[Network] fee_estimates[25] 1022
[Network] fee_estimates[10] 1022
[Network] fee_estimates[5] 1022
[Network] fee_estimates[2] 1022
[Network] relayfee 1000
[Synchronizer] receiving history mkS2ZSZc3NxiDABjsY5BmZsqVqYfC5fMf6 34
[default_wallet] removing tx from history 6113b0ef4f6dc10c13893563817c5fccef7a09cd77fd79581eb33245d3350284
[SPV] requested merkle 6113b0ef4f6dc10c13893563817c5fccef7a09cd77fd79581eb33245d3350284
[Synchronizer] receiving history n4feH3pAQyPXBxmiEapNnW72S43PMyBbFP 1
[SPV] requested merkle 3dd4c506c779989546a45d94e4d8e675901b50331cc26fbb10eda3a5351c7814
[14.3.140.101] requesting header 1094792
[Synchronizer] receiving history msjYvFNUfDk6QXN7tXb7nxysQtMxATQS8Y 2
[SPV] merkle verification failed for 6113b0ef4f6dc10c13893563817c5fccef7a09cd77fd79581eb33245d3350284
[SPV] merkle verification failed for 3dd4c506c779989546a45d94e4d8e675901b50331cc26fbb10eda3a5351c7814

```

**Comment by shsmith** [comment]
I guess the answer to this is to use the "oneserver" command line option. 
This is likely needed only in a netsplit, and is explained here: http://docs.electrum.org/en/latest/hardfork.html

**Comment by ecdsa** [comment]
we should also add an option that allows users to add checkpoints from the GUI

**Comment by ecdsa** [comment]
you can now configure a checkpoint using setconfig
see dd0b018a35e1ab66f7e4f814f9404e6042b31abb

**Comment by ecdsa** [comment]
note: this require more testing; it would be nice if you could mine a fork on testnet
