### ISSUE TITLE
Windows 10 "Trezor not found" ISSUE FIX

### ISSUE THREAD

**Issue by FrancisPouliot** [spesmilo/electrum#2318]
ISSUE FIX

I had a really annoying issue for a while, which I realized was pretty common. Issues is basically:

- Trezor is working on trezor.io, but not on electrum
- Windows 10 - I was using a Surface book
- When you try to connect the trezor, it will say "No hardware device found". No matter how much you re-scan, it will never work.

FIX

1. Download USDBVIEW from http://www.nirsoft.net/utils/usb_devices_view.html
(I do not endorse this particular software version, but it worked for me)
2. Run the software. For better view, select to view only the connected devices.
3. You will NOT see trezor there.
4. Sort by "last plugged in" and the make sure the last device plugged in was trezor.
5. Right-click on the latest device and **uninstall**
6. You will see the Trezor appear in the list
7. Unplug and replug, try again.
8. It works :D

**Comment by ecdsa** [comment]
thanks for the info

**Comment by ecdsa** [comment]
Note: I found that you can do it without downloading this software.
In windows, open "settings", go to "devices" and uninstall Trezor

**Comment by ecdsa** [comment]
info added in 33a32be576002de26808a1b5878d41924e982dc8

**Comment by stefano-p** [comment]
The procedures proposed in this thread do not work at all with me. I am still having the same issue. Maybe it is due to the Creator Update. I have also tried rebooting the PC or uninstalling TRESOR drivers and then plugging the key again. No way! No problem with Win 7.
