### ISSUE TITLE
(BUG) I have win 7 x86 and the .exe not open 

### ISSUE THREAD

**Issue by flakirito33** [spesmilo/electrum#2322]
i already cleaned the registry use the antivirus ccleaner and nothing i cant open the program any version is not able to opened, the problem appear when i restart my pc

**Comment by ecdsa** [comment]
did you recently upgrade electrum? which version are you using?

**Comment by flakirito33** [comment]
Hi i dont know what did happen now works perfectly like always, i used to us the last version 2.8.2
