### ISSUE TITLE
Upgrade from 1.9.7 to 2.18.2 fails

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2326]
This was originally reported here: https://www.reddit.com/r/Electrum/comments/5yptl0/cant_open_electrum_after_downloading_new_version/

I was able to reproduce with the following steps:
1) I copied electrum-1.9.7-portable.exe to an empty directory and ran it.  I created a new wallet and noted the seed phrase
2) I coped electrum-2.18.2-portable.exe to the same folder and launched it.  After a prompt to "Autoconnect" the application window closed.
3) Any additional attempt to launch gives no visible window and no error message.

To diagnose this I ran Electrum from git-head source with the -v and -D parameters.

On each launch this exception was logged:
```
[WalletStorage] wallet path g:\temp\electrum_data\wallets\default_wallet
Traceback (most recent call last):
  File "electrum", line 379, in <module>
    d.init_gui(config, plugins)
  File " electrum\lib\daemon.py", line 283, in init_gui
    self.gui.main()
  File " electrum\gui\qt\__init__.py", line 200, in main
    if not self.start_new_window(path, self.config.get('url')):
  File " electrum\gui\qt\__init__.py", line 157, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File " electrum\lib\daemon.py", line 206, in load_wallet
    storage = WalletStorage(path)
  File " electrum\lib\storage.py", line 77, in __init__
    self.load_data(self.raw)
  File " electrum\lib\storage.py", line 83, in load_data
    raise IOError("Cannot read wallet file '%s'" % self.path)
IOError: Cannot read wallet file 'g:\temp\electrum_data\wallets\default_wallet'
[Network] stopping network
[Network] stopped
[Plugins] stopped
[Daemon] shutting down network
[Daemon] stopped
```

Next I deleted the contents of electrum_data and restored the wallet from seed noted in step 1. I was not able to reproduce the issue of the "next" button not lighting up.

**Comment by ecdsa** [comment]
my bad; I forgot to add back some backward compatibility code that was removed when I added wallet file encryption.
