### ISSUE TITLE
Child transaction cancellation using replace by fee

### ISSUE THREAD

**Issue by eug13768** [spesmilo/electrum#2327]
The method is perfectly described here (although in Russian): https://bitnovosti.com/2017/03/22/how-to-safely-buy-hold-and-sell-btc/ - works until 1st confirmation received.

1. Сreate transaction with a fee small enough so that it could stay in mempool forever. The transaction output must point to one of owner's addresses. Set RBP when creating.
2. Create child transaction with input taken from fee address of 1st transaction. This is the transaction that will be shown to a victim.
3. Now both transactions stay in mempool without any confirmations for indefinite time
4. It works until 1st confirmation so it's time to show child transaction to a victim merchant to get some goods or services from him - if he does not care to wait for confirmation(s).
5. When goods are taken, let's go and create new transaction instead of 1st one (parent) by just increasing fee up to high enough. This way transaction #1 and it's child #2 will show disappeared from mempool and new transaction #3 (still pointed to one of the attacker's addresses) with high enough fee will start getting confirmations. 

Result: Child (#2) showed as payment transaction disappeared, although goods and/or services might be already taken by the attacker from gullible merchant.

**Comment by ecdsa** [comment]
this is normal; it's a feature of Bitcoin, not of Electrum.
This is why the GUI warns you about "unconfirmed parents"

**Comment by eug13768** [comment]
Mycelium mark such child transaction on blockchain so that merchant could see its in RED.

**Comment by ecdsa** [comment]
"on blockchain" ? what does that even mean?
