### ISSUE TITLE
Replacable: Cannot bump fee: cound not find suitable outputs

### ISSUE THREAD

**Issue by anemol** [spesmilo/electrum#2329]
I sent a transaction with lower fees (0.0002)  and when i want to increase fees i get this error:
"Cannot bump fee: cound not find suitable outputs"

I tried different amounts of fees, same error.

I have the "Replacable" flag.

**Comment by ecdsa** [comment]
that's because your transaction does not have change, or the change amount is too small for the fee you want to add. can you post the tx id?

**Comment by anemol** [comment]
Too late, the transaction was confirmed.

TxID is 122668b4420480ab79f5586828359fb3399ae820600f2f24baf85c9c42d3fa1f

**Comment by ecdsa** [comment]
thanks. I guess the small output is the change address.

**Comment by anemol** [comment]
Electrum proposed by default (for increasing the fees) 0.000330 BTC. But i got the error with this default amount. I tried with different amounts (even with 0.003) and still same error. I tried with "Final" checked too.

**Comment by bauerj** [comment]
Closing this since it doesn't seem to be a bug. If you feel that's a mistake, please reopen.
