### ISSUE TITLE
electrum google authenticator

### ISSUE THREAD

**Issue by kuziozmc** [spesmilo/electrum#2330]
Hello, 
I have a problem to make the transction after i restored my iphone to default settings. Is there any chance to get the second factor authentication QR code for my wallet? 
Grateful for any help. Cheers

**Comment by kuziozmc** [comment]
I have lost all google authenticator codes

**Comment by ecdsa** [comment]
yes you can restore from seed. during the restore process you can request a new google authenticator code.
