### ISSUE TITLE
electrum wallet exits instantly on being run

### ISSUE THREAD

**Issue by ThanosTitan168** [spesmilo/electrum#2331]
A very good day to you Sir,

I hope you are doing Great Sir,

I am running Windows 10 Pro 64Bit

I installed a VMWare Machine with Linux Mint 8.1 64Bit and used it to build my electrum windows wallet

I have followed the instructions and compiled electrum Wallet for Windows

However I am having an issue with the - electrum wallet as it exits instantly on being run

Why does the electrum wallet exits instantly when it is being run ?

I have checked the Windows event viewer and found no errors or warnings in the Application logs or the Systems logs.

I have tried running electrum wallet from a MsDos Prompt and there is no error messages, it just runs and then exits the next instant

Can someone please kindly help me out on this issue ?

Hope to hear from you soon.

Thank you very much for your time and kind help 

Kind Regards as Always

**Comment by shsmith** [comment]
Sounds very similar to https://github.com/spesmilo/electrum/issues/2326

**Comment by ecdsa** [comment]
@shsmith I don't think so. he compiled windows builds and something is wrong with his builds.
@ThanosTitan168 did you try to run the binaries we distribute?

**Comment by ThanosTitan168** [comment]
I did not run the distributed binaries ... 

What I did was to use the /Electrum/Contrib/Build-Wine/build-electrum-git.sh Script 

It will build all the binaries in the /Electrum/Dist folder

and I am only interested in the /Electrum/Dist/Portable Version of the EXE 

I tried the rest of the 2 other EXE and they too did not seem to work ... 

When I built the binaries, they all built into the EXE's with out any warning or errors ... 

Just that the EXE's does not seem to work when copied onto a Windows 10 64 Bit System.

I am not sure where I went wrong on this ...

**Comment by ecdsa** [comment]
I do not know; there are many things that you can do wrong when building binaries, it's not really easy to help. You should try running from sources first.

**Comment by ThanosTitan168** [comment]
May I please kindly ask that if I am able to successfully build the EXE binaries, 

that I should have done everything right thus far ?

and that if I have done something wrong in between, the EXE binaries should not even have been successfully built ?

**Comment by ecdsa** [comment]
I don't think so; the building script probably does not check everything.
I am building binaries on linux using Wine. is that what you are doing too?

**Comment by ThanosTitan168** [comment]
Yes I am building windows EXE binaries using this script /Electrum/Contrib/Build-Wine/build-electrum-git.sh 

and the EXE binaries will be created in /Electrum/Dist

**Comment by ecdsa** [comment]
do you know what Wine is? are you using it?

**Comment by ThanosTitan168** [comment]
no ... i copy the EXE into my Windows 10 64 bit pc and run it from there

**Comment by ThanosTitan168** [comment]
that should be ok ... is it not ?

**Comment by ecdsa** [comment]
probably not.
sorry but I am not going to help you more.
I do not plan to support building binaries using another method than the current one.

**Comment by ThanosTitan168** [comment]
can you please kindly at least let me know where the issue may be regarding my setup ? 

I can copy my entire sequence of commands that i run in Linux that eventually lead up to the building of the Windows EXEs 

if that may be of help to trying to resolve this issue ... 

And I would like to say A Big Thank You for taking the time to look into this matter for me ... 

I know that you are extremely busy and has spent your own time looking into this matter for me ...

**Comment by ecdsa** [comment]
I already told you: I do not know. 
The only thing I know is that I build under linux+wine, not under windows.

why do you need to build these binaries, btw?

**Comment by ThanosTitan168** [comment]
I just want to take a look at Electrum's code and to do that i need a fully working setup ... 

So first thing is to compile a working set of EXEs 

then I will take a look at the code ... 

so i am currently stuck in trying to get the EXE to work ...

**Comment by ecdsa** [comment]
if you want to take a look at the code, then you do not need to create binaries.
Electrum works with Python, you can download the zip file and run it with python.

**Comment by ThanosTitan168** [comment]
May I please kindly ask how can i run the electrum wallet that i have downloaded in the zip file from within windows 10 ?

regards

**Comment by ecdsa** [comment]
install python and learn to use it
