### ISSUE TITLE
Android: Crash upon typing name for new wallet

### ISSUE THREAD

**Issue by plammens** [spesmilo/electrum#2333]
The electrum android app consistently crashes upon pressing a key on keyboard when naming new wallet. Screenshot immediately prior to the crash:
![screenshot_20170326-182317](https://cloud.githubusercontent.com/assets/18049056/24333107/e7c5abc2-1252-11e7-98fd-4b8fdfdf40a6.png)

The device is a non-rooted Android 6.0.1 Moto G3.

**Comment by ecdsa** [comment]
thanks for the report.
does it crash if you set your keyboard to English?

**Comment by plammens** [comment]
@ecdsa Yes; I have tried with four keyboard languages, including English (UK), obtaining the same result. I'm using Google Keyboard (Gboard)

**Comment by ecdsa** [comment]
@akshayaurora I think this is probably a kivy bug; I don't see how electrum could cuse this. I could reproduce it on one of my phones.

**Comment by plammens** [comment]
@akshayaurora The crash happens when typing in any textbox, I have found (i.e. labels or new wallet)

**Comment by Crankson** [comment]
For me it only crashes when I press a number to name a wallet.

**Comment by damianpeterson** [comment]
I can confirm this, too. My language/keyboard settings are US English. I was able to get around this by copying text from gmail and long-holding and pasting the text in instead of using the keyboard. I don't know how to get crash logs from my phone but if you can tell me how I'll give it a go.

**Comment by Rcomian** [comment]
I can confirm this too. Google Pixel XL, android 7.1.2, stock keyboard, UK english. Any free text box using the keyboard causes electrum to immediately crash.

**Comment by markcross** [comment]
**Try ANYTHING but the Android Stock Keyboard**. For examaple on a tablet which did not work the "SwiftKey Keyboard" worked fine, on a phone, changing to the native Huawei Keyboard made it work!

**Comment by LeaTex** [comment]
Same issue here! Any news?

**Comment by randyperkins** [comment]
I was able to work around this issue by using 'Google Voice Typing' as a keyboard and speaking the digits I wanted entered.  the field I was trying to populate was the 'port' field in the 'Server' section under the 'Network' menu

**Comment by markcross** [comment]
Or clipboard what you need, then hold and paste when creating a new wallet :-(

**Comment by johnyybananas** [comment]
I had the same problem creating a new wallet. No issues a week ago on same device. Gboard was the problem. I switched back  to stock LG Keyboard  and problem solved. Except for stock lg board being a POS. ( Haven't switched back yet)

**Comment by ariard** [comment]
@johnyybananas are you on Android 7.0 or 7.1 ? Gboard + electrum fine on 6.0, i'm looking on this

**Comment by johnyybananas** [comment]
My regular phone crapped out on me last week. I'm running 5.1 on an old LG I had laying around. Haven't fixed or given up on the other phone yet.  I had just reset this one and was setting it up as a backup.

**Comment by ecdsa** [comment]
should be fixed with APK 2.9.2.1.
Please confirm

**Comment by randyperkins** [comment]
confirmed.  working now with 
Phone Nexus 6. Android 7.1.1 with security patches thru July 5, 2017.
Thanks for the quick response
