### ISSUE TITLE
Using Vialectrum wallet, hoping you guys can help.

### ISSUE THREAD

**Issue by chorobes** [spesmilo/electrum#2336]
I am currently using Vialectrum 1.9.8.4 and get an error code anytime I try to send any funds out. The error code is "  error: {u'message': u'64: non-mandatory-script-verify-flag (No error)', u'code': -26}.

Anyone have any ideas? Thank you

**Comment by ecdsa** [comment]
update to recent version

**Comment by chorobes** [comment]
To my knowledge, this is the most recent version of Vialectrum.

**Comment by ecdsa** [comment]
we don't support alt coins. contact the authors of vialectrum.
