### ISSUE TITLE
Electrum 2.8.2 fails to display GUI

### ISSUE THREAD

**Issue by userp7** [spesmilo/electrum#2337]
Both Electrum 2.8.2 standalone version and the installed version fail to display GUI on Windows 10, 64 bit.    Version 1.x worked except that today it told me to upgrade after I attempted to do a bitcoin transaction.  How to resolve?

**Comment by ecdsa** [comment]
did you upgrade from 1.x ? there is a bug with the file format, that prevents the upgrade.
we'll fix it in the next release. if you don't want to wait you can rename your defaul wallet file and restore rom seed.

**Comment by userp7** [comment]
I never was able to find an "upgrade" button, so I uninstalled version 1.x,  then installed version 2.8.2.    I copied and renamed default wallet file, but I still can't see GUI.    I'll restore from seed or whatever I need to do to get access to my bitcoin today.

**Comment by userp7** [comment]
Is the seed unique to Electrum?  In other words, can I take my seed and enter it into a different software application  (ie. not electrum) and restore my wallet?

**Comment by ecdsa** [comment]
it needs Electrum.
can you try renaming your wallet file please? 
as I already explained, the crash is probably caused by the old wallet file.

**Comment by userp7** [comment]
It seems like you're not able to read my entire messages because I already stated that I re-named my default wallet file.  It didn't do anything.  I still can't see the GUI.   Why would you force people out of version 1, when version 2 has not been tested?  Let me remind you that people have REAL money at stake here.

**Comment by userp7** [comment]
Also, I  never stored the default wallet file in the electrum default location. So not sure how version 2 would even know where to find any wallet since it never prompted me for the path.  Can you tell me the default path that electrum expects to find a wallet file?

**Comment by ecdsa** [comment]
I am not forcing you out of version 1; the Bitcoin network is. 
default path, see http://docs.electrum.org/en/latest/faq.html#where-is-my-wallet-file-located
if the crash is not caused by the wallet file, then I do not know what causes it. maybe try 2.7 and let us know.

**Comment by userp7** [comment]
Problem resolved after renaming the DEFAULT wallet file.  You initially told me to rename "your wallet file".  These are two different things!   It's a good thing I'm not a layman, and this is precisely why bitcoin will always be a huge failure in the mainstream, because you need a goddamn degree in computer science to make it work.   Several years after bitcoin has been developed, the software, wallets, exchanges, networks, etc that support bitcoin are all shit.   I encourage everyone to stay out of bitcoin.
