### ISSUE TITLE
some problem about the function of making unsigned transaction

### ISSUE THREAD

**Issue by ypc1117** [spesmilo/electrum#2343]
yesterday,i has been made unsigned transaction successfully~ but today,there seems to have some problem,the wallet of testnet has five testing bitcoin ,why it shows "NotEnoughFunds"? thanks
![Uploading 屏幕快照 2017-03-29 下午5.26.08.png…]()
![Uploading 屏幕快照 2017-03-29 下午5.28.13.png…]()

**Comment by ecdsa** [comment]
please fix your links to screenshots

**Comment by ypc1117** [comment]
sorry.. ^^
![2017-03-29 5 26 08](https://cloud.githubusercontent.com/assets/15722845/24456260/1146716a-14c5-11e7-8221-f10fbce30646.png)
![2017-03-29 5 28 13](https://cloud.githubusercontent.com/assets/15722845/24456273/1e139dd2-14c5-11e7-9890-2539b580f22c.png)

**Comment by ecdsa** [comment]
that's probably because your wallet is not fully stnchronized. 
(that's the meaning of "false" in the response of daemon status

**Comment by ypc1117** [comment]
thanks for you answer. i'll try to wait more time
