### ISSUE TITLE
Newest Release Inconsistencies

### ISSUE THREAD

**Issue by Rspigler** [spesmilo/electrum#2344]
Hello,

It looks like 2.8.3 was added to the release notes on github 6 days ago (https://github.com/spesmilo/electrum/commit/482ad3b20f648a86d278663aab5034721c797987), but I only see 2.8.2 in releases and on the website.

**Comment by ecdsa** [comment]
that's normal. the release notes are written in advance

**Comment by Rspigler** [comment]
Got it, thanks!
