### ISSUE TITLE
Error in on_get_chunk in testnet mode

### ISSUE THREAD

**Issue by the9ull** [spesmilo/electrum#2345]
I get an error after the connection to the server in `--testnet` mode.
At [this](https://github.com/spesmilo/electrum/blob/master/lib/network.py#L760) point the value of result is: 
`{'method': 'blockchain.block.get_chunk', u'jsonrpc': u'2.0', u'id': 12, 'params': [543], u'error': {u'message': u'internal error processing request', u'code': -32603}}`
so Electrum fails quering `response['result']`.
I tryed to change the server but the result is the same. I does not have this problem in mainnet.

**Comment by ecdsa** [comment]
are you on master? could you post a traceback?

**Comment by the9ull** [comment]
On master it works. I was on 2.8.2. My error, sorry.
