### ISSUE TITLE
Invalid Password and "Please Wait" Restore

### ISSUE THREAD

**Issue by jonathonlrowe** [spesmilo/electrum#2346]
Hi all,

I tried to send funds, but Electrum says my password is invalid. It is the same password I used when I created the wallet. To circumvent the password I tried to restore the wallet from the seed I wrote down as told during initial setup. The program has been running for over an hour but remains on the screen as shown. I'm running Windows 10. Electrum worked just fine during set up and receiving funds. I also uninstalled and reinstalled Electrum to the latest version.

<img width="473" alt="restore please wait" src="https://cloud.githubusercontent.com/assets/20433948/24573185/3b5ca496-163d-11e7-808c-31974ac06e50.png">

**Comment by bauerj** [comment]
Is that a 2FA wallet?

**Comment by ecdsa** [comment]
Is the window in the background another wallet, or is that the wallet you restored?

**Comment by jonathonlrowe** [comment]
Yes, 2FA wallet. The wallet in the background is the wallet I restored.

**Comment by ecdsa** [comment]
so I guess the issue is that it did not properly close the wizard window.
you should be able to send bitcoins from the other window.

**Comment by jonathonlrowe** [comment]
Thank you for the reply.

I was able to send it just now. I have no idea what happened that made it work, but I appreciate your helpfulness.
