### ISSUE TITLE
timelock tx to current height

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#2349]
as done by Core, (long-term miners incentives)

**Comment by dabura667** [comment]
I've never really understood the merit in doing this. Nor do I really see any demerit, so I don't care either way.

Perhaps writing one or two lines as to why you were convinced that "doing what Core does" in this instance is good for the project would help others include their input.

**Comment by ecdsa** [comment]
Primary reason is long term incentives: as the block reward is zero, miners will want to orphan blocks in order to steal their tx fees. (that's why Core does it). Second reason is privacy: if other wallets do it, not doing it means that we leak some info about which wallet is used.

**Comment by dabura667** [comment]
> if other wallets do it, not doing it means that we leak some info about which wallet is used.

That second point makes sense as a reason for the question "Why now?"

ACK

**Comment by ecdsa** [comment]
this seems to be unsupported by both ledger and trezor.
(at least with the firmware that I have now; did not try to upgrade)
