### ISSUE TITLE
Nano Ledger S and test-net

### ISSUE THREAD

**Issue by yura-pakhuchiy** [spesmilo/electrum#2350]
Nano Ledger S displays incorrect destination address when Electrum is in test-net mode. It displays main-net style adress (1...), instead of test-net one (m...). Everything else seems to work fine: amount and fee displayed correctly and transaction get signed. However, displaying main-net address may scare user away if he stores both main-net and test-net coins in the wallet.

I contacted Ledger developers regarding this issue and they proposed following fix:
> invoke SET ALTERNATE COIN VERSION (https://github.com/LedgerHQ/blue-app-btc/blob/master/src/btchip_apdu_set_alternate_coin_version.c) in your code to set the new values (APDU would be E014000005006F00C401 for Testnet)"

https://github.com/LedgerHQ/ledger-nano-s/issues/13

**Comment by ecdsa** [comment]
@btchip does it require to update the firmware?

**Comment by bauerj** [comment]
I don't have a Ledger myself so I can't test: Is this still an issue?

**Comment by yura-pakhuchiy** [comment]
@bauerj Yes, issue is still present. And moreover, it is a security issue, not just UX issue as I originally reported. You can read details [here](https://github.com/LedgerHQ/ledger-nano-s/issues/13). Still no updates from @btchip. Looks like Ledger is too busy with scaling their sales, rather than fixing security issues in theirs product. :-(

**Comment by btchip** [comment]
It is not a security issue. If you choose to run the BTC Mainnet app, it'll display Mainnet addresses. I'd appreciate if you could refrain from any slanderous speculation on our roadmap.

**Comment by yura-pakhuchiy** [comment]
@btchip If user is prompted to sign transaction on one chain (bitcoin testnet, dash, etc.), but signed transaction actually moves coins on another more valuable chain (eg. bitcoin), how it is not a security issue? There is no way to check derivation path for keys on ledger right now, to make sure that you signing transaction for correct coin.

**Comment by yura-pakhuchiy** [comment]
It is exactly the same issue, device is displaying misleading information which may result in funds lost. I reported this issue almost one year ago. Why it is taking so long to fix it? https://github.com/LedgerHQ/ledger-nano-s/issues/13#issuecomment-291135137 you indicated that it is easy to fix and do not required firmware update.

**Comment by btchip** [comment]
You might want to recheck the title of this issue and my last comment in the link you provided

**Comment by yura-pakhuchiy** [comment]
Both issues are caused by exactly the same thing, but OK, you can call it different issue if you like. It does not matter.
But what is important here, is that security issues is stays unfixed for almost one year. :-(

**Comment by bauerj** [comment]
> If you choose to run the BTC Mainnet app, it'll display Mainnet addresses.

Is there anything we can do to use the Testnet app in stead or does it require changes to the btchip-python library?

**Comment by btchip** [comment]
You can install the BTC testnet app from Ledger Manager in the developer apps

**Comment by bauerj** [comment]
So that's not an issue in Electrum?

**Comment by btchip** [comment]
No

**Comment by bauerj** [comment]
Alright, thanks for clarifying!
