### ISSUE TITLE
testnet and derivation path

### ISSUE THREAD

**Issue by yura-pakhuchiy** [spesmilo/electrum#2351]
Electrum uses `m / 44' / 0' / 0' / 0 / 0 ` derivation path for both mainnet and testnet. However according to BIP44[1] it should use `m / 44' / 1' / 0' / 0 / 0` for testnet. Electrum does not see addresses/transactions from another wallets which use `m / 44' / 1' / 0' / 0 / 0`.

1. https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

**Comment by ecdsa** [comment]
that has been fixed a month ago, see 9d6f816b15fd6c224b3d07620f5eee246b070ce8

**Comment by yura-pakhuchiy** [comment]
No, it is not. At least not in 2.8.2 (which includes commit you linked to) with restore from BIP39 seed or with nano ledger s.

Test case:
Electrum 2.8.2
Restore from BIP39 seed: remove garden bone easily cloth lake fat demand east outside shell fix absorb treat middle transfer surface hair shuffle primary maximum model grunt kangaroo
Electrum will generate first address: mmwZSHHuvps8k6qydh6GYNES33AuNehMrB (m/44'/0'/0'/0/0)
However correct address would be: mrkoc6S6fAKji9ZwBehArbE6rMw9KE1M2e (m/44'/1'/0'/0/0)
You may check with https://iancoleman.github.io/bip39/

**Comment by yura-pakhuchiy** [comment]
@ecdsa No, it is not. At least not in 2.8.2 (which includes commit you linked to) with restore from BIP39 seed or with nano ledger s.

Test case:
Electrum 2.8.2
Restore from BIP39 seed: remove garden bone easily cloth lake fat demand east outside shell fix absorb treat middle transfer surface hair shuffle primary maximum model grunt kangaroo
Electrum will generate first address: mmwZSHHuvps8k6qydh6GYNES33AuNehMrB (m/44'/0'/0'/0/0)
However correct address would be: mrkoc6S6fAKji9ZwBehArbE6rMw9KE1M2e (m/44'/1'/0'/0/0)
You may check with https://iancoleman.github.io/bip39/

**Comment by ecdsa** [comment]
another proof that, "import *" is evil

**Comment by yura-pakhuchiy** [comment]
@ecdsa you might want update [this](https://github.com/spesmilo/electrum/blob/master/plugins/ledger/ledger.py#L456) line as well. BTW, ledger firmware is 1.3 already.

**Comment by ecdsa** [comment]
that line is not relevant
