### ISSUE TITLE
Watch-only HD wallet has transaction mistakenly stuck as Unconfirmed

### ISSUE THREAD

**Issue by scottj97** [spesmilo/electrum#2355]
I created a watch-only wallet in Electrum (on WIn10) using the xpub key from an air-gapped copy of Electrum. I then sent bitcoins to this wallet via my phone, and it showed up instantly as Unconfirmed.

The problem is, days later that transaction is still listed as Unconfirmed, but the blockchain says otherwise.

I created a new copy of the wallet using the same xpub, and this time Electrum shows it properly as confirmed.

The attached screenshot shows both wallets side-by-side. I launched this Electrum instance on 4/6/17.

![electrum bug report - stuck unconfirmed](https://cloud.githubusercontent.com/assets/86350/24764848/844ebe7a-1aaa-11e7-8fc8-3693451e067c.png)

**Comment by bauerj** [comment]
Probably related: #2055

**Comment by scottj97** [comment]
Related, but I don't think it's the same. There, a restart of Electrum solved the issue. I have exited and re-started Electrum multiple times and it is still out of date.

Is there any way to force a resync of a wallet? That would be a suitable workaround for now.

**Comment by bauerj** [comment]
Oh, that's interesting. Are you connected to the same server with both clients?

**Comment by scottj97** [comment]
Not sure...I'm new at this. How can I tell which server it's connected to?

**Comment by bauerj** [comment]
Click on the green circle in the bottom right hand corner. It's the one in the textbox above the list.

**Comment by scottj97** [comment]
Both wallets show the exact same thing in the Network popup (electrum.no-ip.org, Use SSL checked, Select server automatically checked). These are all defaults, as far as I know.

**Comment by scottj97** [comment]
Also both instances show the same number of blocks in the blockchain (460745). Yet one still shows the transaction as Unconfirmed.

**Comment by scottj97** [comment]
Another data point: I sent a transaction today that had been signed on the airgapped machine. On the connected machine, I did Tools, Load Transaction, From text, then Broadcast. This showed up in my wallet as an Unconfirmed transaction.

This time I left Electrum open and running on the online machine. Hours later the blockchain has 9 confirmations for that transaction, but Electrum still shows Unconfirmed.

So the problem doesn't seem to be related to disconnecting or sleeping the PC.

**Comment by scottj97** [comment]
This morning when I opened Electrum, both wallets were up to date. So it does sync eventually, just takes way too long.

**Comment by ecdsa** [comment]
I believe this should be fixed by 6931ffada55087c481b9d098afa5d0fa8c1794ec
