### ISSUE TITLE
Where is the button for importing private keys?

### ISSUE THREAD

**Issue by ibred** [spesmilo/electrum#2357]
The Import button in the Wallet -> Private keys menu is missing.
![2017-04-09_16-26-10](https://cloud.githubusercontent.com/assets/19796511/24837644/751237ea-1d41-11e7-99ad-46dc417a2012.png)

**Comment by dabura667** [comment]
Create New Wallet > Import > Paste list of private keys.

You can no longer mix HD and imported wallets. They must be managed as separate wallet files.
