### ISSUE TITLE
Unconfirmed Transaction.

### ISSUE THREAD

**Issue by mediumted** [spesmilo/electrum#2362]
I have a unconfirmed transaction that is pending for 1 day and 18 hrs.
I have had other ones take 4 hours.
This last one I am a bit worried about and am wondering why Electrum has so many Unconfirmed Transaction history's .
To the user it is like a frozen bank account.

**Comment by helraw** [comment]
i have the same probleme, i do the transfert 3d ago.. please help

**Comment by ecdsa** [comment]
see http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
