### ISSUE TITLE
Use change address 

### ISSUE THREAD

**Issue by EastActivist** [spesmilo/electrum#2363]
Electrum use change address is not working as you can see in attached image
"....mJZ74bJM2PnHJsx7vTe" is my electrum wallet address and ",,,2r8ih6nXTX6HzW" is the address that I wanted to send btc (electrum has not used a proxy address)
and as you can see electrum has used same address used for receiving btc for sending it too
![capture](https://cloud.githubusercontent.com/assets/27496531/25044620/d530674c-213c-11e7-90d7-55bd7fa38fef.PNG)

**Comment by ecdsa** [comment]
that's the expected behaviour.
"change" addresses are not what you think

**Comment by EastActivist** [comment]
now, the explanation i found is this "The change is sent to a change address to obfuscate your payments" but still you can see that no other payments that my direct ones exits
