### ISSUE TITLE
Unconfirmed Parent HELP 

### ISSUE THREAD

**Issue by johnzorhovich** [spesmilo/electrum#2364]
Hello, whats going on ? 

I sent 4 transactions and its frozen for 2 days now . 

https://blockchain.info/tx/564c4273c772ab5e64e360cddd97d40739f7f7d305ec7e618fe712068c1337da
https://blockchain.info/tx/5964a9d268778297bfb6392c0d5e59d883857208e6cf2847d73e4b1195ef6fb0
https://blockchain.info/tx/bdbbdecb03861f76c06ab1bb6210b10b5327822c2c23e7f0cb673c916d80de68
https://blockchain.info/tx/1f6b28b2a459211a05d9a15e6c790b6a8d7098e6c25f981c55394a52f8dce212

Please help ,  my balance is also 0 and i cant cancel anything. 

Balance 0.690413 [-0.690413 unconfirmed] .

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
