### ISSUE TITLE
[Enchancement] Separate privatekeys by custom categories

### ISSUE THREAD

**Issue by Plasmmer** [spesmilo/electrum#2366]

**Comment by ecdsa** [comment]
can you provide a description please?

**Comment by Plasmmer** [comment]
@ecdsa, I'm getting confused here with a lot of privatekeys I can use everyday for my ZeroNet sites. Would be nice a feature to create categories/divisories to insert privatekeys.

**Comment by ecdsa** [comment]
where do these private keys come from?
are you importing them in Electrum, or generating them from Electrum?

**Comment by Plasmmer** [comment]
Importing.

**Comment by ecdsa** [comment]
why don't you import them in separate wallets?

**Comment by Plasmmer** [comment]
Because I need to use only one wallet.

**Comment by ecdsa** [comment]
ok, I guess that would fall in the same category as #1854
