### ISSUE TITLE
Sources version can not run!

### ISSUE THREAD

**Issue by tomas06** [spesmilo/electrum#2368]
Hi,

I have Windows 7 64bit Ultimate
- python-2.7.13.msi
- PyQt4-4.11.4-gpl-Py2.7-Qt4.8.7-x32.exe

I can not run these versions:
- Electrum-2.8.2
- Electrum-2.8.1
- Electrum-2.8.0

This version works:
- Electrum-2.7.18

I use this command:
"start python electrum --portable"

Why can not I run the latest versions in the same way?

**Comment by bauerj** [comment]
What happens when you run that?

**Comment by tomas06** [comment]
Nothing happens that is the problem :-D

**Comment by tomas06** [comment]
OK,

A window appears for one second: https://s15.postimg.org/etq1r6njf/ERROR.png
I had to use OBS-Studio :-D

**Comment by bauerj** [comment]
Related: #2358

Do you use the source archive from https://electrum.org/#download?

**Comment by bauerj** [comment]
In any case, if you have pip installed, this should work:

    python -m pip install win_inet_pton

**Comment by tomas06** [comment]
thx

**Comment by ecdsa** [comment]
can this be closed?

**Comment by tomas06** [comment]
yes, 
"python -m pip install win_inet_pton" This solved my problem
