### ISSUE TITLE
Adding translation using the config file.

### ISSUE THREAD

**Issue by tomas06** [spesmilo/electrum#2369]
Hi,

For the version "electrum-2.8.2-portable.exe" It is possible to modify the config file somehow and add a translation in format "electrum.mo"?

To launch Electrum portable with my own translation?

**Comment by bauerj** [comment]
What exactly do you want to do? Why do you want to replace the translation file at all?

Depending on your use-case you could consider changing the translation on [crowdin](https://crowdin.net/project/electrum) or compiling your own modified portable version.

**Comment by tomas06** [comment]
My mother language Czech is very complicated...

I want to make my own translation that will not be changed by other people in each new version.

"compiling your own modified portable version."
- Yes, that's the way to do it


But a simpler solution would be to load the "electrum.mo" file in the version "electrum-2.8.2-portable.exe".

**Comment by ecdsa** [comment]
already answered in other issue
