### ISSUE TITLE
Add Altert if send x Bitcoin(s)

### ISSUE THREAD

**Issue by Machou** [spesmilo/electrum#2370]
Hello

Could you add an alert / confirmation if i send a defined number of bitcoins in the preferences.

To avoid being mistaken, because I just sent 1 bitcoin, instead of 1 euro.

Thanks

**Comment by bauerj** [comment]
>  I just sent 1 bitcoin, instead of 1 euro.

That's quite a difference!

So you want an option to specify the maximum value of a single transaction? Or a daily limit?

**Comment by Machou** [comment]
Just an alert if i mistake. :P

Single transac yes, maybe daily limit like all Market Bitcoins.

**Comment by EagleTM** [comment]
Might be something for a plugin. Should be configurable as well

**Comment by ecdsa** [comment]
are you talking about the android version?
there is already a confirmation dialog in the desktop version.

**Comment by bauerj** [comment]
Closing this since there has been no response form @Machou in the last 266 days.

**Comment by Machou** [comment]
Sorry, i talk about Windows Version (Desktop)
