### ISSUE TITLE
Electrum Bitcoin Wallet on Android will no longer open

### ISSUE THREAD

**Issue by jamesfmay** [spesmilo/electrum#2375]
My Electrum Bitcoin Wallet was working fine on Android version 6 on my Samsung Galaxy Note 5, but since I upgraded​ to Android version 7 it just hangs indefinitely at the big Bitcoin symbol when I try to open it.

**Comment by jamesfmay** [comment]
Electrum version 2.8.2

**Comment by ecdsa** [comment]
can you uninstall/reinstall it?

**Comment by jamesfmay** [comment]
After removing and reinstalling using my seed phrase it's working fine now, and all my settings, transaction history, and funds were in tact... Thanks for your help!
