### ISSUE TITLE
Old version translation?

### ISSUE THREAD

**Issue by tomas06** [spesmilo/electrum#2377]
Hi,

488 <-> 501
The crowdin.com are translations with 488 rows.
When I use the development version and "./contrib/make_locale" translations with 501 rows.

What is the template ".pot" update time interval to crowdin.com. Since the release of the new version of electrum?

**Comment by bauerj** [comment]
Hey,

the template on crowdin was last updated 2 months ago. Ideally, that should happen automatically when there are new strings to translate.
