### ISSUE TITLE
"make_locale" on Windows

### ISSUE THREAD

**Issue by tomas06** [spesmilo/electrum#2378]
Hi,

I was looking to do it "make_locale" on Windows and i found it very simple.

I Use: gettext "xgettext.exe" and command "xgettext -s --no-wrap -f app.fil -o new.pot"

https://ctrlv.cz/shots/2017/05/01/10NB.png
There are some warnings, i do not understand...
But the file is exactly the same as using "make_locale" on linux.

Please. you can add this information to the translation instructions for people who do not have Linux.

**Comment by bauerj** [comment]
Hey,

`make_locale` should work fine on Windows. Make sure to put `xgettext.exe` and `msgfmt.exe` in your `PATH`.

**Comment by tomas06** [comment]
I probably wrote it wrong :-D

What you wrote, i did of course and works.
The file was created but I got some error alert. It's in the picture above.

I repeat that:
But the file is exactly the same as using "make_locale" on linux.

So it's probably not a big error alert in creating a .pot file.

**Comment by bauerj** [comment]
In the screenshot it looks like you executed xgettext directly without using `make_locale`.

You can ignore those warnings.

**Comment by tomas06** [comment]
If it's just about this, it's in order :-D

**Comment by ecdsa** [comment]
fixed in 67c561e4cdad8a49f94e54e89b8d686d514622ef
