### ISSUE TITLE
electrum wallet charging a huge fee and taking a long time.

### ISSUE THREAD

**Issue by jaderayub** [spesmilo/electrum#2379]
![fuckingelectrumwallet](https://cloud.githubusercontent.com/assets/28266413/25586269/f512a9b8-2e74-11e7-9800-0d4c54a074b9.jpg)
well look at this 0.3 fee bitcoin for a 2 bitcoin transfer. i used standard fee didnt change anything. it just charged me a lot!!! and probably since it was a temporary wallet this payment will be denied and they will refund me without fee. how can i have this thing canceled please im really angry with this wallet and this bitcoin stuff.

**Comment by jaderayub** [comment]
and its taking a long time!!! whats wrong with all this? im really pissed please help me guys!

**Comment by dabura667** [comment]
0.367 mBTC is not 0.3 BTC

1 BTC = 1000 mBTC

You paid a normal fee. About $0.55 worth. On a transaction that sent $3000 around the world.

**Comment by jaderayub** [comment]
nono watch carrefully its 300 mbtc so 0.3 btc. its some sort of bug. also my deposit is 2.02 btc and its going 2.39 so its more than 0.3 btc or around 500 dolars fee!!!!! this is an absurd|!!!!

**Comment by gits7r** [comment]
you paid 0.36732 mBTC from your print screen , which means about 0.00036732 BTC.  With an expected confirmation time of 5 blocks. So, there is no bug clearly in this case.

**Comment by jaderayub** [comment]
and why is it transfering 2.39697??? my transfer was just 2.02965 the rest is fee and its not even happening its been hours.

**Comment by jaderayub** [comment]
i think the transfer didnt go fine something happen and its sounds like its back into my account.

**Comment by jaderayub** [comment]
now its fine. actually i made a huge noob mistake and sent only 2.3 mbtc to them :(
