### ISSUE TITLE
unconfirmed transaction since 2 days - raise suggested fee

### ISSUE THREAD

**Issue by lupa18** [spesmilo/electrum#2385]
Hello ! 
Again I'm having troubles with an unconfirmed transaction. I choose the suggested fee for 5 blocks, so I believe that 1 hour will be enough. 
But I still waiting since 2 days ago. 

Can you fix/increase those suggested feeds and estimations?
thanks in advance

**Comment by bauerj** [comment]
Could you provide some more information?

What version of Electrum do you use?
What's the fee for the transaction (mBTC/kB)?

**Comment by lupa18** [comment]
yes, sorry. 
Version: 2.8.2
Amount sent: 0,025606
Fee (suggested for 5 blocks): 0,0002064 
Dynamic fees enabled. 

May I try with CPFP ? (I'm not sure what really is, bit trying to understand it)

**Comment by bauerj** [comment]
Probably, if you have a change output in that transaction.

What is the fee per kB?

**Comment by lupa18** [comment]
Not sure, here the detail: https://blockexplorer.com/tx/dff95948ea97c84a5325b758eac2765dc5261372f7e8c52c26c2ffdda4b43c7a

**Comment by lupa18** [comment]
so ? If I apply a CPFP it's possible to get part of the money back ?

**Comment by lupa18** [comment]
I didn't make de CPFP and now I have a "low fee" notice in Electrum. How can I solve it?

please help :)

**Comment by ecdsa** [comment]
cpfp should be possible, because the tx has change.
