### ISSUE TITLE
Unconfirmed Transaction since 5 days. Need help 

### ISSUE THREAD

**Issue by PaDaNoX** [spesmilo/electrum#2387]
Hello community,
I made a transaction with a high fee on first of may but waiting until today that it gets confirmed.
Nothing happens.
The recipient needs the money pretty urgent and i do not know what to do know.

Greetings Padanox

**Comment by bauerj** [comment]
How much is the fee? Can you find the transaction on a block explorer?

**Comment by PaDaNoX** [comment]
https://blockchain.info/tx/bf25dfa6d4818185541a71ca77195f5aa737c98d3a5493fd9b188eff4c977409 
this is the transaction. Was worth 1540$ do not know why it says 1636$
I used a higher fee than the automatic function wanted

**Comment by bauerj** [comment]
34.692 sat/B is a very low fee. Did you have dynamic fees enabled when sending the coins? What version of Electrum did you use?

**Comment by PaDaNoX** [comment]
i know it is low. i had it activated but it said 0.0003 and i changed it to 0.0005 cuz it was suspicious.
if i am right than i use 2.6 at the moment

**Comment by bauerj** [comment]
Okay, please update to 2.8.2: https://www.reddit.com/r/Bitcoin/comments/5zchm8/sent_transaction_with_low_fees_in_electrum_can_i/dex2alq/

**Comment by PaDaNoX** [comment]
how do i update that? and is there a risk of losing the money on the wallet? 
Since english is not my native language i do not understand everything in the reddit post. Where do i find preferences and the children parent option?

**Comment by bauerj** [comment]
> how do i update that?

That depends on your operating system. 

> and is there a risk of losing the money on the wallet?

There is no risk as long as you have the seed phrase backed up.

> Where do i find preferences and the children parent option?

![image](https://cloud.githubusercontent.com/assets/598790/25747737/d7c1b2aa-31a8-11e7-9de3-98e89a039169.png)
![image](https://cloud.githubusercontent.com/assets/598790/25747774/fab25026-31a8-11e7-8f15-8c70233ce6a1.png)

Right-click on your transaction to find the CPFP option.

**Comment by PaDaNoX** [comment]
I just opened the 2.8.2 version and everything showed up immediately. There was nothing i had to export before and i did not have to use my seed.
Now the tx is market with a warning sign ''low fee'' but i still do not see the cpfp option. dynamic fees is activated

**Comment by PaDaNoX** [comment]
and is there a chance that the tx gets rejected? since the price rised and i want to safe money :D

**Comment by bauerj** [comment]
Sure, you can try and double-spend the coins if you want.

**Comment by PaDaNoX** [comment]
since the amount of the tx is all i had on that wallet i can not spend it. it tells me not enough funds

**Comment by dabura667** [comment]
Do you know which wallet software the other person is using? They can CPFP the transaction.

**Comment by PaDaNoX** [comment]
No I do not.
How can i double spent the money now?

**Comment by PaDaNoX** [comment]
This issue is not closed mate.
