### ISSUE TITLE
[Android] Can't delete Requests

### ISSUE THREAD

**Issue by Crankson** [spesmilo/electrum#2392]
When I delete the request, close and reopen the app, the payment requests are there again. It's only those 3 that are stuck there. Other ones I can delete.

![screenshot_2017-05-06-18-55-20-463_org electrum electrum](https://cloud.githubusercontent.com/assets/27394238/25774379/ba73f448-328d-11e7-95e3-59da3f5db7fc.png)

**Comment by ecdsa** [comment]
this should be fixed with the current version. 
please reopen this issue if you still have it
