### ISSUE TITLE
"Unconfirmed parent", transaction pending since a couple of days

### ISSUE THREAD

**Issue by Jonasmichiels** [spesmilo/electrum#2393]
Hi, 

The last two times I tried to transfer Btc electrum says "unconfirmed parent" and the other "Low fee" It's been a couple of days now that these transactions are not followed thru. 

Is there anything I can do, or is there someone who knows how to handle this? 
<img width="705" alt="schermafbeelding 2017-05-06 om 19 31 22" src="https://cloud.githubusercontent.com/assets/28489816/25774547/3c73998c-3291-11e7-9d31-614725d6877a.png">

**Comment by gonderie** [comment]
me too

**Comment by popsmail2015** [comment]
no way, just wait  Mr @Jonasmichiels I had this issue  about 4 days, after and I get the confirmation.

**Comment by gits7r** [comment]
Please close this in favor of #2396 - I've documented it little better there and might be something we could do to at least know in advance when we are dealing with such cases.
