### ISSUE TITLE
Email validation on 2fa wallet

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#2394]
Hi

Email validation for 2fa wallets is not good. I tried creating a wallet with an \@localhost.k address and it caused the wallet creation/restoration process to crash with this message:

>electrum_plugins.trustedcoin.trustedcoin.TrustedCoinException: Invalid request.  Parameter 'email' is not a valid email.

**Comment by bauerj** [comment]
How would you expect that address to be validated?

**Comment by AbdussamadA** [comment]
In this case checking that the TLD has more than one character would do it. But the bigger problem is the uncaught exception. Electrum should catch that and handle it gracefully instead of crashing outright.

**Comment by bauerj** [comment]
Okay, that makes sense.
