### ISSUE TITLE
i Can't send my BITCOINS any address 

### ISSUE THREAD

**Issue by gonderie** [spesmilo/electrum#2399]
Unconfirmed 3 times, I add FEE 25 Blocks 1time, 5 Block 2times
3 address  
i wait it 2 weeks ,Now i can't success

**Comment by Fornax96** [comment]
The bitcoin network is quite overcrowded right now, as a result transactions take longer to confirm. I just had a bitcoin transaction go through that I submitted 8 days ago, just be patient.

You posted this 21 days ago, has the transaction gone through yet?
