### ISSUE TITLE
[$200 bounty in bitcoin] - Dead Man's Switch

### ISSUE THREAD

**Issue by Rspigler** [spesmilo/electrum#2401]
AFAIK there is currently no bitcoin wallet that allows easy adjustment of the nLockTime field.  This would enable a so called 'Dead Man's Switch', where transactions could be created and signed, but not broadcasted.  This transaction could then be given to loved ones, and the broadcasted transaction would then only be valid and accepted into a block at some absolute time in the future (block x).  Before that point in time, you moving your bitcoin to another address in your control permanently invalidates the transaction, and a new nLockTime signed transaction can be passed along in case something happens to you in whatever period of time you choose (1 month, 6 months, etc).

This is a greatly requested feature by the community (just google "Bitcoin Dead Man's Switch" to find many posts), but so far has no easy GUI available for this in any wallet.

This is a copy of (https://github.com/spesmilo/electrum/issues/1685), but with an extended explanation and bounty attached.

I may not be very well known in this community, but this GitHub account is associated with my main/personal PGP key, email address, real name, and photo.  However, I of course would be willing to set up an escrowed payment for those more comfortable with that.

My preferences are that the nLockTime is easily adjustable through the GUI, and that this would work with all current types of addresses/wallets already supported by Electrum (standard, multisignature, standard hardware wallet, and multisignature wallet with hardware wallet co-signers).

**Comment by ecdsa** [comment]
please don't post duplicates; you're just adding to the noise
