### ISSUE TITLE
No way to uninstall on Ubuntu

### ISSUE THREAD

**Issue by alexgleason** [spesmilo/electrum#2403]
Same issue as #1747. I uninstalled with pip, but the desktop icon, the executable, and all the files still persist. I tried cloning the repo and guessimating that I could `python setup.py uninstall` with no such luck. It seems the only way is to manually delete the files.

**Comment by bauerj** [comment]
Hey, I just tested installing and uninstalling using pip and it worked just fine here. If you still encounter this issue, please reopen.
