### ISSUE TITLE
Signing messages not working with Trezor

### ISSUE THREAD

**Issue by MarvinOl** [spesmilo/electrum#2410]
Moved to 2.8.2 and everything seems to work except singing messages. Fails with:
'TrezorKeyStore' object has no attribute 'get_coin_name'

**Comment by nomnombtc** [comment]
Can confirm, same error also with git master. Could not find 'get_coin_name' in the other plugins, so I reverted this [commit](https://github.com/spesmilo/electrum/commit/2a45e32e0e63e1b746ac0b22b847ed1d33f4925b), which introduced it, and signing works again.

**Comment by ecdsa** [comment]
please test the fix

**Comment by nomnombtc** [comment]
@ecdsa seems to work fine again now, thanks :)
