### ISSUE TITLE
creating multisig address from daemon

### ISSUE THREAD

**Issue by zottirik** [spesmilo/electrum#2414]
I created multisig address from daemon.
Electrum gives me an address and reedemscript.
But this address not seen in my addresses, I can't do anything with this address.

What can I do?

**Comment by shaggy34** [comment]
Do u have windows 10

**Comment by zottirik** [comment]
No, I am using Ubuntu Server

**Comment by bsbits** [comment]
What do you mean from daemon ? command line ?

**Comment by zottirik** [comment]
Yes, command line on Ubuntu Server

**Comment by ecdsa** [comment]
createmultisig is not supposed to create a wallet address.
next time, explain what you want to do
