### ISSUE TITLE
wallet not sinking 

### ISSUE THREAD

**Issue by samill68** [spesmilo/electrum#2415]
the wallet will not sink with blockchain...

**Comment by bauerj** [comment]
I'm not sure if that is a good or a bad thing.

**Comment by samill68** [comment]
its not loading all the way it shows balance but no green lite that its ready to be used....

**Comment by bauerj** [comment]
Do you have a slow internet connection? Or a lot of addresses? Can you try to switch the server?

**Comment by samill68** [comment]
ya I am addressing I rite now
