### ISSUE TITLE
Prepare to use new estimatesmartfee in client

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#2420]
bitcoin core 0.14.2 will have "estimatesmartfee" and deprecates use of estimatefee 
See https://github.com/bitcoin/bitcoin/pull/10199

As we're already hitting the MAX_FEE_RATE sanity check fee it would make sense to prepare to move towards 
estimatesmartfee. Server needs to be prepared to answer for estimatesmartfee and those servers that don't should fall back to ask for estimatefee.

The GUI needs to be updated to access the new range of estimates (whith fallback to the old slider intervals in case we only get estimatefee). Core suggests providing options for targets of: 2,4,6,12,24,48,144,504,1008  where 1008 is one week.

**Comment by ecdsa** [comment]
perhaps this can be decided by requesting the bitcoind version from the client

**Comment by EagleTM** [comment]
Another possbile approach would be to do this server side and prefer to take / send estimatesmartefee if it's available. That would be nice in that it's compatible with old versions and does not require any GUI change for now.

**Comment by ecdsa** [comment]
except that it does not have the same set of targets

**Comment by EagleTM** [comment]
It has more targets but should have all the targets estimatefee has?

**Comment by fresheneesz** [comment]
It seems like the algorithm used by this site is pretty good: https://bitcoinfees.21.co/ . Can we just use the same algo in electrum? It might be a good idea to have this done server side - since it needs a number of the latest blocks to do a proper calculation.

**Comment by dabura667** [comment]
@fresheneesz That site is not very accurate... it over estimates a lot.

**Comment by fresheneesz** [comment]
@dabura667 Ok, well its "over estimates" are still a ton lower than electrum's estimates.

**Comment by dabura667** [comment]
Maybe right now, but not necessarily.

I remember for quite a long time bitcoind's (used in Electrum) estimates were lower than 21's.

**Comment by EagleTM** [comment]
I'd suggest to do this server side and leave things as they are client side including the confirmation targets. 

Server side (electrumx) it can try to get estimatesmartfee there, if that fails (because bitcoin core is < 0.15.0) it can go back to query estimatefee. estimatesmartfee returns data in a slightly different way so server should "normalize" that to appear like the output of estimatefee. This way it's backward compatible with old clients.

**Comment by ecdsa** [comment]
closing: @SomberNight's PR is merged.
