### ISSUE TITLE
Transaction rejected by our node. Reason: Transaction is trying to double spend. Input 4 is already spent.

### ISSUE THREAD

**Issue by freelancer38** [spesmilo/electrum#2422]
Transaction rejected by our node. Reason: Transaction is trying to double spend. Input 4 is already spent.
https://blockchain.info/tx/4e4d46a513a6f619b490baa8b07be671cd8c7c01d6196f0a0399893469c521e9
What happened ?

**Comment by bauerj** [comment]
There is a second transaction that spends the inputs: https://blockchain.info/de/tx/a456361919207c1ca3d9d187318fa079eb7819c958592c667ecd93762db7ee79

**Comment by freelancer38** [comment]
Yes, I try do double spend.

**Comment by freelancer38** [comment]
Status changed:
Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned from our database.
https://blockchain.info/tx/28ea67c0b9754c435ac7071273fba9ff40b34a6cff5076be13346fde8eb6ccc1
