### ISSUE TITLE
NEW TO THIS ELECTRUM, but loosing all coin

### ISSUE THREAD

**Issue by onduks** [spesmilo/electrum#2423]
Using Masterkey for my website to receive coin. Create account send several coin to the wallet, for 5days I have not seen my coin.

if you loose your Password no way to resset password.

Please correct me if am wrong.

Charles

**Comment by ecdsa** [comment]
if this is a bug report, please be more precise.

**Comment by onduks** [comment]
How can i get the bitcoin transfer to my wallets

**Comment by ecdsa** [comment]
maybe you could start by producing a usable bug report?
