### ISSUE TITLE
History tab shows not actual balance

### ISSUE THREAD

**Issue by abrikos** [spesmilo/electrum#2424]
2.7.2
History tab looses some transactions. It shows balance, but it is not actual. Button "Max: on "Send" tab puts actual balance.
upgrading to 2.8.2 not helps

**Comment by ecdsa** [comment]
can you post a screenshot please?

**Comment by rgnixon** [comment]
Perhaps I have the same issue. I'm new to Electrum, so I don't understand it all yet.
Installed 2.8.2 on Win 10 64-bit yesterday. Sent some BTC to it. Watched my NZD balance move up and down slightly over an hour or so.

Today, the NZD balance on the History tab is 'frozen'. Closing and opening Electrum doesn't help.
I do see a DIFFERENT NZD on the Status Bar. This balance *IS* fluctuating, and appears more correct.
Values from UI are as follows:
• History tab: 324.50615 mBTC, NZD 1,042.13
• Status Bar:  324.50615 mBTC, NZD 1,001.41
• Send Max with lowest fee: 324.08845 mBTC, NZD 999.33

Live BTC price is currently USD 2151.93. Exchange rate is 0.7033. NZD price will be about $3,060.
324.50615 mBTC should therefore show my balance at about NZD 992.99 - therefore I conclude the History tab balance is 'faulty*.

**Comment by ecdsa** [comment]
@rgnixon I don't think you are talking about the same thing.
the history tab shows the fiat value of the transaction, at the day the transaction took place.
so, it's normal that it is "frozen". the current value is shown in the status bar.
