### ISSUE TITLE
dont receive payments

### ISSUE THREAD

**Issue by researchgroup** [spesmilo/electrum#2426]
Hi,

Im using electrum 2.8.2 and its connected to my webshop. Last couple days i noticed i dont receive much payments. Just a couple each day. Normal its allot more. So i made a small order myself and send the money to the bitcoin address it told me to send it. I checked the address its one off my own addresses. And i see the money go out the wallet. But i dont see it come back in my wallet. 

Whats going on? There is allot money at stake for me so in worried. For now we shut down the bitcoin payments on my website untill we know whats wrong.

Thanks for your help!

**Comment by EagleTM** [comment]
Possible reason - There is a increas in popularity and a huge backlog of transactions (200k plus) and fees are currently prohibitively high for Bitcoin payment usage of smaller denomination. 
See https://jochen-hoenicke.de/queue/#30d for the mempool
Personal advice (not necessarily endorsed by Electrum team): For the time being consider also accepting other Cryptocurrencies which can currently offer lower fees.

Unless there is anything technically wrong with Electrum (and it doesn't sound like it) I'm closing here.

**Comment by ecdsa** [comment]
probably because the payer did not pay enough fee fot his tx to be added to the memory pool of your server

**Comment by researchgroup** [comment]
what about the incoming transactions? Where are they? 

What other crytocurrency do you advice me to use?

**Comment by ecdsa** [comment]
what is the transaction ID and which server are you using?

**Comment by researchgroup** [comment]
this is one off the payments:  https://blockchain.info/tx/6e1b84e2a05d63dc560f5796afe019877fa0829c83f8ce44d1c3c0e04caa490c

im using server from blockchain info.

**Comment by researchgroup** [comment]
is it better to use different one?

**Comment by ecdsa** [comment]
what is the electrum server you are using with your electrum client?

**Comment by researchgroup** [comment]
mooo.not.fyi

**Comment by ecdsa** [comment]
I see the transaction using that server.
maybe you should try to restart the electrum GUI, and see if it fixes it?

**Comment by researchgroup** [comment]
you mean just shut down and open again?  I did that but not helping.

**Comment by ecdsa** [comment]
how did you create the wallet, and which is your address in the transaction?

**Comment by researchgroup** [comment]
the wallets will be created by electrum.  

its realy strange because i cant find this addresses in my wallet.

i tried a transaction to my own wallet:  1d9878214237a39e8637d88aa2e2f8537bba650cb27d6cc50d0cefcab16b7d9d

its going out but not coming in. I took a new not used address for this transaction. But after sending the money i cant find the address again in my wallet?

**Comment by ecdsa** [comment]
what do you mean by 'going out but not coming in'? can you post a screenshot of the transaction details from electrum?

**Comment by ecdsa** [comment]
how is your "webshop" generating addresses? 
is it possible that you generated addresses beyond your gap limit?

**Comment by researchgroup** [comment]
http://prntscr.com/f9opp4

i mean that the bitcoins are out off my wallet but not coming back. the webshop is connected with electrum and this proces is automatic no idea how it works.  How can i change the gap limit?

**Comment by researchgroup** [comment]
maybe you can mail me direct? I can pay you money if you can solve this problem?

contact me at info@researchgroupnederland.com

**Comment by ecdsa** [comment]
everything looks fine on your screenshot. 
the bitcoins are not leaving your wallet.

**Comment by ecdsa** [comment]
in the console type wallet.create_new_address() a few times

**Comment by researchgroup** [comment]
it says invalid syntax

**Comment by researchgroup** [comment]
can we talk skype ore something to fix this asap

i can pay you money if you can help me out

**Comment by ecdsa** [comment]
see http://docs.electrum.org/en/latest/faq.html#what-is-the-gap-limit
I don't do skype support, but maybe someone else will, if you ask in the irc channel

**Comment by ecdsa** [comment]
also check the docs of your "webshop" to see if it tells you how many addresses itt generated

**Comment by researchgroup** [comment]
i understand what gap limit is but how can i make it bigger?

**Comment by researchgroup** [comment]
i can see in electrum that the list from adresses is realy long. Couple hundred. 

So maybe there is the problem?

**Comment by researchgroup** [comment]
where can i find this channel to ask for skype support?

**Comment by ecdsa** [comment]
IRC channel: #electrum channel on Freenode

**Comment by researchgroup** [comment]
oke , can you tell me how to make the gap limit bigger?

**Comment by ecdsa** [comment]
wallet.change_gap_limit(n) from the console should do that.
make sure you understand what you are doing before trying that (I do not think you are)

**Comment by researchgroup** [comment]
so whats your advice? can i share xpub key ?

**Comment by emilrus** [comment]
I've debugged this over skype. Seems its a bug in electrum, they payments show up under the Addresses tab but not under History

**Comment by ecdsa** [comment]
@emilrus please provide screenshots.

**Comment by EagleTM** [comment]
I suspect it might be a subscription limit. If you have many addresses and you want to monitor them all the servers might cut you off, if you request the balance for too many addresses. you could run your own server with a high limit to circumvent or try and find a server operator to increase the limit for you to debug this (because this is just a guess by me)

**Comment by ecdsa** [comment]
I synchronized your wallet from xpub and I can see the transaction 1d9878214237a39e8637d88aa2e2f8537bba650cb27d6cc50d0cefcab16b7d9d

this transaction is internal (from wallet to wallet), and it paid a high fee, -2,19767 mbtc.
everything looks normal.

I believe you are misinterpreting the way things are displayed.
if you send from the wallet to the wallet, there will be only one entry in history.

**Comment by ecdsa** [comment]
the other transaction 6e1b84e2a05d63dc560f5796afe019877fa0829c83f8ce44d1c3c0e04caa490c does not seem to be related to your wallet. you should check why the webshop software cretaed them.

**Comment by researchgroup** [comment]
Hi,

The problem is not fixed. They payment you find here are payments i did to myself from my own wallet. Just to check if its working.

But im still missing 20/30 payments from customers. 

@EagleTM  How can i run my own server to fix this problem? (ore prevent it wont happen again?
