### ISSUE TITLE
Cómo recuperar cartera

### ISSUE THREAD

**Issue by diegotco** [spesmilo/electrum#2427]
**Hola**

**Estoy en la versión 2.8.2** y  **no puedo recuperar mi cartera**, es decir, a donde debo ir para colocar mi frase (de solo 12 palabras y no de 24) y por lo tanto recuperar mi cartera?

Cuando doy clic a recuperar y sigo los pasos para poner mi "**seed**" no se activa el botón de "siguiente"

![ele1](https://cloud.githubusercontent.com/assets/22822405/26247572/1ea8aa14-3c64-11e7-9747-274a24fa6220.png)
![ele2](https://cloud.githubusercontent.com/assets/22822405/26247573/1ea9813c-3c64-11e7-9413-4cfbb53dd01f.png)

**Qué sucede?**

Desde ya agradeco cualquier ayuda :)

**Comment by bauerj** [comment]
Does your seed phrase consist of 12 english words? Make sure you are spelling all words correctly.

When did you create your seed?

**Comment by diegotco** [comment]
Yes, they are english words and I wrote correctly. I created the seed 8 months ago. I don't sure but it was last year

**Comment by ecdsa** [comment]
either you made a typo, or you did not create the seed with electrum

**Comment by diegotco** [comment]
Bet I do. I am a very organized person ;) I know which every single seed are from ;)

But this not solves my problem :(

**Comment by diegotco** [comment]
Hey guys. False alarm. False Alarm. Now I got it. Wouuu. I can finally recovery my wallet. Woouuuu :)

Nice

**Comment by diegotco** [comment]
I have had 2 wallets with almost same name, damn it 

Then I realized I was putting the another seed. F... hehe. I lesson of humility to me. Sorry guys
