### ISSUE TITLE
wallet problem

### ISSUE THREAD

**Issue by researchgroup** [spesmilo/electrum#2431]
Hi,

I already opened a topic :  https://github.com/spesmilo/electrum/issues/2426

The admin closed it because he thought it was no problem in the electrum wallet.
But it must be a problem im the wallet:

I tried to send btc to different wallet and it worked fine, and when i send to my own wallet i see it goes out the wallet but i dont see it incoming. 

Its connected to my webshop and i dont see incoming payment last days ( maybe something with the gap limit?)

I willing to pay €50 to the person who can solve this problem for me.

**Comment by ecdsa** [comment]
do not open duplicate issues
