### ISSUE TITLE
Latest git version fails to create valid transaction if ledger nano s is used 

### ISSUE THREAD

**Issue by yura-pakhuchiy** [spesmilo/electrum#2432]
All transactions are rejected with following error:
```
error: The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))
```
Git commit: ac77c9b9bdb9a3618a0febd98cc72bece9eb7c25
I tried only with testnet coins, do not know whether it works with mainnet.

@btchip

**Comment by ecdsa** [comment]
I think it's not an electrum issue.
check that you have a recent firmware, and a recent version of btchip-python

**Comment by yura-pakhuchiy** [comment]
@ecdsa Thanks, indeed updating  btchip-python helped.
Could be more user-friendly though, if electrum would check btchip-python version and display a warning.
