### ISSUE TITLE
signing with btchip (ledger HW1) not possible on windows - missing websocket module

### ISSUE THREAD

**Issue by torusJKL** [spesmilo/electrum#2433]
I have installed electrum 2.8.2 on Windows 10.

When I try to sign a message with a HW1 wallet (btchip) I get the error message "No module named websocket".

On Ubuntu I fixed this by installing the package "python-websocket".

How can I resolve this issue on Windows?

**Comment by Xav1986** [comment]
Hi torusJKL. I am having the same problem on windows but I will install Ubuntu instead. 
Can you explain how we can install the "python-websocket" in the electrum wallet, and where to find it?
Thanks in advance.
Xavier

**Comment by ptilancelot** [comment]
0x7068D71569E9c514805c71008dA69D8F3445225F

**Comment by torusJKL** [comment]
Hi Xav1986, on Ubuntu please execute the following: `sudo apt install python-websocket`

**Comment by alexandrz** [comment]
I am having the same issue on Mac. Is it possible to install the library?

**Comment by alexandrz** [comment]
Electrum 2.8.3 installed from dmg.

**Comment by alexandrz** [comment]
Fixed it by installing websocket client:

`pip install websocket-client`

and then copying to the package content:

`cp -R /usr/local/lib/python2.7/site-packages/websocket /Applications/Electrum.app/Contents/Resources/lib/python2.7/packages`

**Comment by alexandrz** [comment]
I get "read error" after reinstalling the wallet and entering code.

**Comment by alexandrz** [comment]
Exception:

```
Traceback (most recent call last):
  File "Electrum-2.8.3/gui/qt/util.py", line 582, in run
    result = task.task()
  File "Electrum-2.8.3/lib/wallet.py", line 1553, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "Electrum-2.8.3/plugins/ledger/ledger.py", line 233, in sign_message
    self.give_error(e, True)
  File "Electrum-2.8.3/plugins/ledger/ledger.py", line 197, in give_error
    raise Exception(message)
Exception: read error
```

**Comment by ecdsa** [comment]
this should be fixed in version 2.9.2 (windows builds). can you confirm?

**Comment by alexandrz** [comment]
not fixed on macos

**Comment by ecdsa** [comment]
@alexandrz I will need to add it to the dmg too.
is the second issue you reported (read error) solved?

**Comment by alexandrz** [comment]
@ecdsa not fixed

**Comment by Smiggel** [comment]
Same issue here on OS X. Using Electrum 3.0.2

**Comment by jwbats** [comment]
Last activity on this issue was almost a month ago. Are there plans to fix this?

**Comment by bitcoinland** [comment]
Still the same on MacOS High Sierra (10.13.3) with Electrum 3.0.5. When you try to sign a transaction with the ledger HW1 a popup with the "No module named websocket" message.

@ecdsa do you need some help testing this ?

Thanks!!
