### ISSUE TITLE
unconfirmed transaction over a week ago

### ISSUE THREAD

**Issue by sud0society0217** [spesmilo/electrum#2435]
so i still have an unconfirmed transaction and idk what to do..ive been using electrum for over a year and didnt start having iusses till about 6 months ago...it tells me transaction fee too low or miner fee too low i dont remember exactly. basically its stuck. is my money gone? cause ive read yes and ive read no. so is there any suggestions?? .. help me please guys! thanks.

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
