### ISSUE TITLE
How to Increase transaction fee rate

### ISSUE THREAD

**Issue by racerx2000** [spesmilo/electrum#2436]
I am using Electrum on my remote server. I have no GUI there so only use command line
And question, how I can increase minimum of fee rate ? now all pay outs from my server has 50 satoshi/Byte 
How to change that amount for eg to 120 satoshi/Byte . Is there any way to do that ?

**Comment by ecdsa** [comment]
use setconfig and getconfig, to set the relevant variables: 
    "dynamic_fees"
    "fee_level"
    "fee_per_kb"

**Comment by racerx2000** [comment]
Thanks for quick answer. But... I set "dynamic_fees" to false and "fee_per_kb" to 120000. It still show fee = 50 satoshi/byte.

**Comment by racerx2000** [comment]
And what number it need : satoshi? mBTC ?
example: NOW all my transaction have 50 satoshi/Byte - I need 120. I do
electrum setconfig "fee_per_kb": 1.2
or 
electrum setconfig "fee_per_kb": 120000
Or 
?
