### ISSUE TITLE
Bitcoins not received after making transaction.

### ISSUE THREAD

**Issue by benw360** [spesmilo/electrum#2437]
I recently made a transaction to my btc wallet but bitcoins is not coming up in the wallet after sending it ... $300+ electrum!!! what's happening! bacth i/d :  https://blockchain.info/tx/d0e46632dde99f0c8a25ab893deb0b7395430ec2fdf31a4108a3fc89c63e3912

**Comment by dabura667** [comment]
There is definitely $300+ in the address 1DCZvGRvwZ2Y7CsfbGs2HkF9jVJ5skf5bT

The questions I would ask are:

1. Is that address really in your wallet? (are you being tricked by the sender and/or malware?)
2. Is the network connecting properly to your wallet? (Try connecting manually to many different servers to see if it shows up)

**Comment by ecdsa** [comment]
closing, user not answering

**Comment by benw360** [comment]
It has been resolved
