### ISSUE TITLE
low fee and unconfirmed parent

### ISSUE THREAD

**Issue by xuxien** [spesmilo/electrum#2438]
I am really angry about electrum and transaction with them
i send two transaction and both , one is stuck for low fee from two days ago and the other one i set a higher fee but it's still uncofirmed and it is already pass 12 hours
What can i do now?

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by xuxien** [comment]
thanks i already read this

I had enabled "replace by fee" in my Preference  How can i increase my transaction fee now? it is not clear this...

**Comment by ecdsa** [comment]
if the transaction is replaceable there is a context menu to bump the fee

**Comment by xuxien** [comment]
![electryum](https://cloud.githubusercontent.com/assets/28889849/26346179/b0f2c6cc-3fa5-11e7-8448-5daafc8303fc.JPG)

in this transaction i there is no any kind of options if i right click on, so i just have to wait that credit me back th BTC? is it right?

**Comment by xuxien** [comment]
thanks both transactions are just arrive now!
