### ISSUE TITLE
Sending BTC with 'use multiple change addresses' and trezor asks for confirmation of unexplained movements

### ISSUE THREAD

**Issue by artvogel** [spesmilo/electrum#2440]
- Using Electrum 2.8.2 with Trezor, 
- select 'use multiple change addresses' 
-  initiate a bitcoin-sending transaction 

Observed behavior:
 - Trezor asks user to confirm transfers to change addresses never seen before. User must manually go to the 'Console' pane and run 'listaddresses()' to confirm that the change transfers are to addresses in their control.
 
Expected behavior:
 -  Electrum program will explain all btc transfers in the transaction, so user can easily confirm on the trezor that change is going to the correct addresses.

**Comment by ptilancelot** [comment]
0x7068D71569E9c514805c71008dA69D8F3445225F

**Comment by ecdsa** [comment]
shall we always open the 'preview' window if there are multple change addresses?

**Comment by prusnak** [comment]
For the record, we changed the behaviour of the Trezor firmware to allow multiple change-outputs. See https://github.com/trezor/trezor-firmware/pull/1100 - for 2 change-outputs there is no extra screen, for 3 and more change-outputs we show an extra confirmation screen.

I think this can be closed as the issue will resolve itself once a user has FW 2.3.2+ or 1.9.2+.
