### ISSUE TITLE
The current fee unit used is BTC/kB.  Popular convention is b/B [enhancement]

### ISSUE THREAD

**Issue by cluelessperson** [spesmilo/electrum#2441]
My current max fee is 0.0043584 BTC/kB

This is tedious (math is hard) to translate to b/B for users, which most sites use by popular convention. This will alleviate further fee confusion and help people conform to the same known glossary.

Examples:  

https://bitcoinfees.21.co/
https://blockchain.info/tx/68973cd03a6d264c1396cb1e60f27fe87214f90aa20e70abb39cc201c706a1c5

Thanks

**Comment by dabura667** [comment]
Count five decimals from the point.

436 satoshis/byte
0.00436 BTC/kB

I don't get how this is hard... move the decimal left 8 times to convert satoshi to BTC, then right 3 times to convert byte to kB.

Totals out to move the point 5 to the left.

Once you've heard it once, now you're going to remember it, but yeah...

**Comment by bauerj** [comment]
Of course it's easy to convert. It's also easy to convert inches (?) to meters if you remember the conversion factor. However, it would be even easier if you didn't have to convert at all.

I don't see any disadvantage in using the same unit everyone else is using.

**Comment by dabura667** [comment]
Less like converting inches to meters ( / 39.37)

More like converting kilometers to meters ( x 1000)

All you have to do is cover the decimal point with your finger.

If you can't divide 159 by 10 in your head to get 15.9 then I seriously doubt you should be investing in Bitcoin...

That being said, I see no reason to change it nor do I see a reason to not change it.

Therefore, for backwards compatibility, status quo is the best option imo.

**Comment by cluelessperson** [comment]
I was mistaken, current standard it Sat/B

**Comment by Engelberg** [comment]
I would like to see the fee expressed in terms of Satoshis per Weight Unit, since Sat/Byte is no longer really the correct way of computing fees.

**Comment by ecdsa** [comment]
@Engelberg the "bytes" counted in segwit tx are actually WU/4

**Comment by Engelberg** [comment]
Thanks. That makes sense as long as that's what the various fee estimators also mean by bytes.
