### ISSUE TITLE
Problem with electrum

### ISSUE THREAD

**Issue by diamond7777** [spesmilo/electrum#2442]
I have unconfirmed transaction over 1 week. Please help me. https://blockchain.info/tx/4507f85676d681909d9676cb652c2f3f2ef5dbdaac1a9975a44f23480c12a4e1

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
