### ISSUE TITLE
Upgrade mac wallet from 1.9.8, keeps crashing "Electrum error"

### ISSUE THREAD

**Issue by volcanicc** [spesmilo/electrum#2443]
![screen shot 2017-05-24 at 10 32 17 am](https://cloud.githubusercontent.com/assets/8055666/26382004/44d23f14-406c-11e7-81ac-e3f676cef5e9.png)

I've got the backup 1.9.8 working fine, but the upgrade is giving me no love.

Error console log attached the system specs for the mac are as follows
![screen shot 2017-05-24 at 10 32 51 am](https://cloud.githubusercontent.com/assets/8055666/26382030/64d04e64-406c-11e7-8afd-bee5146f9758.png)

[electrumerrorlog.txt](https://github.com/spesmilo/electrum/files/1024085/electrumerrorlog.txt)

**Comment by ecdsa** [comment]
save your seed on paper and remove the existing wallet/config

**Comment by ecdsa** [comment]
looks like #2326 
upgrade to 2.7 first

**Comment by volcanicc** [comment]
Thanks for the help, sorry didn't get to reply but re-seeded on 2.8.2 and that worked just fine.

**Comment by ecdsa** [comment]
ok; note that I released 2.8.3, which should fix it too.
