### ISSUE TITLE
unicodeobject.c

### ISSUE THREAD

**Issue by bitmodeler** [spesmilo/electrum#2444]
I suffered through fixing up jsonrpclib issues (and SimpleXMLRPCServer...)

I am on Windows, 64 bit, using python 3.6.1 (pycrypto, pyqt4, etc. are all installed...)

When electrum starts, python bombs on a module called unicodeobject.c, and the problem is an strlen is evidently being performed on a null pointer.

Does this suggest what I might be doing wrong, or what may have been overlooked in this port?

The routine that gets a null pointer passed to it is unicode_fromformat_write_cstr

**Comment by knocte** [comment]
Please copy+paste exact and complete error messages or stacktraces/backtraces.

**Comment by bitmodeler** [comment]
It's not a python stacktrace; it's the C code in python itself that craps out when I try to run electrum.
I installed the debug symbols for python.

Python call stack in (V)C is attached:
[stack.txt](https://github.com/spesmilo/electrum/files/1024411/stack.txt)

The code that it is bombing on in that module is:

`static int
unicode_fromformat_write_cstr(_PyUnicodeWriter *writer, const char *str,
                              Py_ssize_t width, Py_ssize_t precision)
{
    /* UTF-8 */
    Py_ssize_t length;
    PyObject *unicode;
    int res;

    length = strlen(str); // referencing the argument str is causing an access violation...`

And the access violation is: "Unhandled exception at 0x0000000054D4CB53 (python36.dll) in python.exe: 0xC0000005: Access violation reading location 0x0000000100013451."

My python 3.6.1 has been solid to date (I did a web app using falcon and filewatch, without incident, and another that did communication over the USB port...)

**Comment by bitmodeler** [comment]
I also set PYTHONPATH to the site packages folder...

**Comment by bitmodeler** [comment]
AND just for laughs, tried running it as Admin; same result.

Also prepped the icons...

**Comment by ecdsa** [comment]
use python2

**Comment by bitmodeler** [comment]
Are you guys interested in completing the upgrade of this code to python 3?

**Comment by ecdsa** [comment]
there's already a python3 branch.
it's not being deployed because pythonforandroid is not ready

**Comment by bitmodeler** [comment]
Well, it's evident that there are Unicode issues lurking in the code (a big difference between python 2 and 3, right?) Let me know if you want me to work with you on isolating what they are...

**Comment by ecdsa** [comment]
well, you can checkout the python3 branch and try to rebase it
