### ISSUE TITLE
big problem

### ISSUE THREAD

**Issue by stanch3vv** [spesmilo/electrum#2446]
I wait confimations from 2 week,s still 0....my transaction ID is d85532e6619fd37f751f54ac6faf04756412bee0cb2e0200b1b1fda81d009309

you have to find a solution, other wallets are way faster than electrum,this is just a joke.Now i have no choice but to change the wallet

**Comment by bauerj** [comment]
The network confirms transactions, not the wallet.

**Comment by stanch3vv** [comment]
why 
all other wallets work faster than? Why 
xapoo 
confirmate the trasactions for few minutes? How can i pay more fees for fast transacitons?







 >-------- Оригинално писмо --------

 >От: Johann Bauer notifications@github.com

 >Относно: Re: [spesmilo/electrum] big problem (#2446)

 >До: spesmilo/electrum  

 >Изпратено на: 24.05.2017 16:22



 
 
  
The network confirms transactions, not the wallet.  
   —
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  mute the thread .   
    
       
      
    {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spesmilo/electrum","title":"spesmilo/electrum","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/spesmilo/electrum"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bauerj in #2446: The network confirms transactions, not the wallet. "}],"action":{"name":"View Issue","url":"https://github.com/spesmilo/electrum/issues/2446#issuecomment-303721813"}}}

**Comment by bauerj** [comment]
Just pay higher fees if you want your transaction to be confirmed faster. Make sure to enable dynamic fees in Electrum: http://docs.electrum.org/en/latest/faq.html?highlight=fee#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
