### ISSUE TITLE
2 issues and 2 pending transactions

### ISSUE THREAD

**Issue by BitCoinDave** [spesmilo/electrum#2448]
I am running the most up to date software 2.8.2.  I have 1 transaction that says "low fee" and another that says "unconfirmed parent"  neither transaction when through and I don't know what to do.  Please help.

Here is image of issue:  https://gyazo.com/8fdd66a1adaa4ffd3ca3c99a30ef1e2c

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
