### ISSUE TITLE
Support possible for altcoins through modified BIP44 ?

### ISSUE THREAD

**Issue by eriksank** [spesmilo/electrum#2449]
Electrum is a great wallet. Thanks for working so hard on it.

At the moment, it is possible to use electrum for bitcoin, electrum-ltc for litecoin, and an incomplete fork (not available for linux) that can supposedly handle dash. The newer wallets such https://coinomi.com and https://jaxx.io seem to have trivially added support for most altcoins by implementing BIP44.

Now that bitcoin dominance has effectively falling below 50%, it becomes harder and harder and even financially unsound to keep ignoring the altcoin onslaught. 

Of course, it is also a question of NOT implementing the BIP44 core flaw. Since BIP44 derivations are always hardened, it is not possible to have watch-only wallets under BIP44. With a watch-only wallet requiring a copy of the seed/private keys, what is the point in having them. Therefore, the system of cold storage that we came to appreciate so much in electrum, is not possible with BIP44.

In that sense, it would be needed to fork BIP44 and make hardening optional. It would make electrum addresses -- the ones that have watch-only capability -- incompatible with other wallet systems, but that would not be an issue, since standards are not meant to be dumb tools to impose bugs and inconsistencies onto others. We should therefore ignore BIP44 where it is obviously flawed.

Of course, that would make things harder for the electrum team, because they would not be following the standard. No matter how bug-ridden the BIP44 standard may be, this is not really an enviable position.

So, overruling and forking BIP44, and being right anyway, while everybody else is wrong?

**Comment by ecdsa** [comment]
sorry, but this is out of my scope.
electrum ports for altcoins are done by other people.
