### ISSUE TITLE
Silent crash when using old wallet file

### ISSUE THREAD

**Issue by archgod79** [spesmilo/electrum#2450]
Hello,

I used version 1.9.8 when I created a wallet. I tried to sell now and saw that I need to update due to some incompatibility, so I downloaded 2.8.2. It got to the prompt about automatic server selection and then crashed (no error, just disappeared). I've tried to use the 2.8.2 portable and the 2.8.0 versions as well -they both opened normally first with an empty, new wallet, but when I copied the old wallet file over the new one, they started to do the exact same thing: silent crash when started. When deleting the config file I could get to the server selection screen but that's it, no matter what I choose there, it crashes.

Seems like there's something in the old wallet file that causes the new versions to crash, could you please check?

**Comment by ecdsa** [comment]
I believe it is fixed in 2.8.3
