### ISSUE TITLE
Preferences pane not appearing, ver 14.06 under Ubuntu 16.04

### ISSUE THREAD

**Issue by revamped83** [spesmilo/electrum#2451]
As heading. Can't change any preferences as the preferences pane doesn't appear. Checked and the .conf file doesn't exist in either etc/electrum or ~/.electrum . Even after copying the sample .conf file into both the pane still doesn't appear. Frustrating as cannot set transaction fees.

**Comment by ecdsa** [comment]
remove the file named 'config'
