### ISSUE TITLE
InstallWizard: Changing wallet name does not work

### ISSUE THREAD

**Issue by ubruhin** [spesmilo/electrum#2452]
Hi,

When starting Electrum the very first time, the InstallWizard automatically asks for creating a new wallet, and a name can be entered manually. For example, I have entered "test":
![electrum - install wizard_009](https://cloud.githubusercontent.com/assets/5374821/26500058/e96ae76e-4234-11e7-8203-d3bc57ca1ba4.png)

Then I clicked on "Next", and saw that the wallet name has changed back to "default_wallet" instead of "test":
![electrum - install wizard_010](https://cloud.githubusercontent.com/assets/5374821/26500074/f882ea1c-4234-11e7-8b88-ca786e5fcdc2.png)

Tested with `2.8.2` and the current `master` branch.

**Comment by ptilancelot** [comment]
Hello sorry,
Closed #2452 <https://github.com/spesmilo/electrum/issues/2452> via 2a53e85
<https://github.com/spesmilo/electrum/commit/2a53e85e8d4ecb4bcebecfde1b34826bc4e88578>.sur
GitHub..,,,,,???????
J'apprends les crypto.
...
Il y à 2 mois que j'ai connu le Bitcoin...
Maintenant toutes les autres monnaies. Du coup, j'ai tous essayé,..wallet,
blog...  etc etc..
Je suis perdu, les 50e en Ethereum vallait que 60 80 euro...Et depuis
je cherche ou sont les 50e que j'ai mis ailleurs que sur Coinbase????
 Je crois que c'est un portefeuille Ethereum...Je sais plus???????
Pourquoi autant de messages?? Je ne me rapelle plus trop bien....GITHUB
stp EXPLIQUE MOI SE QUE JE DOIS FAIRE OU, COMMENT, ET POURQUOI,
Un grand merci ThomasV

...


2017-06-29 18:23 GMT+02:00 ThomasV <notifications@github.com>:
