### ISSUE TITLE
Creating a new wallet asks two times for a name

### ISSUE THREAD

**Issue by ubruhin** [spesmilo/electrum#2453]
Hi,

When clicking File -> New/Restore, a dialog asks for the name of the new wallet:
![new wallet_011](https://cloud.githubusercontent.com/assets/5374821/26500275/973beb18-4235-11e7-83e7-417d8ba09375.png)

Then one clicks on "OK", and the InstallWizard appears which asks for the wallet name again:
![electrum - install wizard_012](https://cloud.githubusercontent.com/assets/5374821/26500315/c2eaa42a-4235-11e7-9f97-95fd3fd6c724.png)

This is quite confusing. Btw, changing the wallet name again in the InstallWizard does not work, as reported in #2452.

**Comment by bauerj** [comment]
That's especially confusing since it starts on step 2 of the wizard.

**Comment by ptilancelot** [comment]
Bonjour,
Comme tu dis, suis à force de tous essayer depuis 2 ou 3 mois? Pour ne pas faire de bêtises avec les manipulations en euro, bitcoin, puis ethereum....qui depuis mai à commencer à monter,...monter, Comme l'av perdu ma carte d'identité...j'ai fait du grand n'importe quoi, en essayant quant même sans ma CI. D'où j'ai perdu et je cherche encore les 40e de base..... si il son sur Ethereum ou ICI?????? Un petit foi 5...je serai super heureux....Car je veux pas me brûler les ailes....Mais avec cette somme je pourrai m'interresser à autre chose..

Bon là, tu ma tel bien expliqué, que je ne sais pourquoi je dois faire tous ses trucs, depuis j'ai déjà bien perdu de temps à chercher ...et comprendre aussi les crypto....
Si c'est pour m'aider, franchement merci mais pourquoi mdr...
Allez si ça fonctionne ton truc en même temps je sais pas pourquoi????rrrr
Je t'offre une biére bien fraiche..

**Comment by ptilancelot** [comment]
DONC JE MET UN WALLET ETHEREUM.....
je ne me rappelle plus si j'ai ouvert où non un Wallet Ether....Vu qu'après il l'on tous mis dans leur site...
Je peux en mettre une nouvelle?..
Domage que tu ne sois pas là..
Biz
