### ISSUE TITLE
Is there anyway to know tx output and input addresses

### ISSUE THREAD

**Issue by zottirik** [spesmilo/electrum#2458]
On daemon; especially, with electrum history command, i can see TX ID but, I can't see input and output addresses. Is there anyway to see input and output addresses of transaction id?

**Comment by dabura667** [comment]
This should work.

https://github.com/spesmilo/electrum/blob/d4e8f4beb630d46cdc196df11dcf57540f0bec71/lib/commands.py#L439

```python
@command('w')
def history(self):
    """Wallet history. Returns the transaction history of your wallet."""
    balance = 0
    out = []
    for item in self.wallet.get_history():
        tx_hash, height, conf, timestamp, value, balance = item
        if timestamp:
            date = datetime.datetime.fromtimestamp(timestamp).isoformat(' ')[:-3]
        else:
            date = "----"
        label = self.wallet.get_label(tx_hash)

        # START ADDING HERE
        tx = self.wallet.transactions.get(tx_hash)
        tx.deserialize()
        input_addresses = []
        output_addresses = []
        for x in tx.inputs():
            addr = x.get('address')
            if x['type'] == 'coinbase': continue
            if addr == None: continue
            if addr == "(pubkey)":
                prevout_hash = x.get('prevout_hash')
                prevout_n = x.get('prevout_n')
                _addr = self.wallet.find_pay_to_pubkey_address(prevout_hash, prevout_n)
                if _addr:
                    addr = _addr
            input_addresses.append(addr)
        for addr, v in tx.get_outputs():
            output_addresses.append(addr)
        # END ADDING HERE

        out.append({
            'txid': tx_hash,
            'timestamp': timestamp,
            'date': date,
            'input_addresses': input_addresses, # ADD THESE TWO LINES AS WELL
            'output_addresses': output_addresses, # ADD THESE TWO LINES AS WELL
            'label': label,
            'value': float(value)/COIN if value is not None else None,
            'height': height,
            'confirmations': conf
        })
    return out
```

**Comment by zottirik** [comment]
Hi,

It works, but now, only one transaction is coming.

**Comment by dabura667** [comment]
Please check your spacing.

Could you copy paste your code directly to pastebin or something so I can check your spacing?

**Comment by zottirik** [comment]
great, it works..
Thanks,

**Comment by ecdsa** [comment]
@dabura667 can you add this in a PR?

**Comment by dabura667** [comment]
Sure

**Comment by dabura667** [comment]
@ecdsa Done #2465

**Comment by zottirik** [comment]
It will be good to view output addresses with balances, is it possible?

**Comment by dabura667** [comment]
Current balance at time of command (current time) or the amount that was given to the address at the time? (The amount of the input and output of the transaction)

**Comment by zottirik** [comment]
The amounts of the inputs and outputs of the transaction

**Comment by dabura667** [comment]
amounts of outputs is easy

amounts of inputs that are within your wallet (so change addresses essentially) is slightly difficult

amounts of inputs that are not related to your wallet would require querying the server for every entry and is very hard.

For outputs, just change
```
output_addresses.append(addr)
```
To
```
addr_dict = {}
addr_dict[addr] = v
output_addresses.append(addr_dict)
```

**Comment by dabura667** [comment]
Thinking about it further, there is really no need to know the input amounts, as any input in a transaction you made is a previous output anyways, and any deposit to your wallet from the outside will show you the outputs that went into your wallet which is really all you need.

Unless you have a specific need besides "because I want all the information possible" then I will not look into this further.

**Comment by zottirik** [comment]
Output's amount is enough, thanks @dabura667

**Comment by zottirik** [comment]
Hi @dabura667,
I have a personal question.
Is it easy to see an output address is mine or not on history json.
Ex:

"outputs": [
            0 => ["address":1CFSKjEm4ipcC5bfvUULQk6whQWtH1vCWo,
                   "value":399200,
                   "ismine":true
                    ],
            1 => ["address":1PaHt7VTFEZ7mcwJiqEKkhaf7guubRTqTx,
                   "value":400000,
                   "ismine":false
                    ]
        ]

**Comment by dabura667** [comment]
addr_dict['is_mine'] = self.wallet.is_mine(addr)
