### ISSUE TITLE
2fa problem, HELP PLEASE !!!

### ISSUE THREAD

**Issue by tanlucle** [spesmilo/electrum#2459]
lost my phone in april, still had $92 in it but cannot send it anywhere due to not having the 2fa, i created a new wallet on electrum. now transferred $1000 like an idiot, will i be able to send out the coins without the 2fa, man waiting for confirmations and arrival. i really hope i dont run into that problem

**Comment by ecdsa** [comment]
did you save your seed on paper? if yes, read the FAQ please.

**Comment by tanlucle** [comment]
Im afraid i did not 😔

**Comment by tanlucle** [comment]
Will i still have the same problem with  my new wallet ?

Tan Le

**Comment by ecdsa** [comment]
if you persist at not saving the seed on paper and losing your phone, then yes, you will have the same problem again.

**Comment by tanlucle** [comment]
Dammit so  my money is practically stuck forever, you guys cant help me right ? Wait  are you someone who can help me by the way

**Comment by ecdsa** [comment]
not if you do not have your seed.

**Comment by tanlucle** [comment]
i honestly dont have anything, i try to send it out and it asks for 2fa, where do i go from here? is there anyway to reset the security measures, i have the password and all. 2fa screwed me once again
