### ISSUE TITLE
upgrade not working

### ISSUE THREAD

**Issue by hermann-san** [spesmilo/electrum#2460]
recently I've tried to upgrade 1.9.7 to 2.8.2 (on Linux Mint 17), but that upgrade failed due to issue #2326 
Then I installed 2.7.8, which worked ok. I can start the GUI.
Then I installed 2.8.2, but when I start electrum then Version 2.7.8 opens anyways (verified in the GUI - Help - about).
When I start electrum from the CLI,  I get this:
` "sni-qt/7488" WARN  16:09:38.613 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE `

` $ electrum version `
`2.7.18 `

`$ sudo pip2 list`

> ....
> 
> ecdsa (0.10)
> Electrum (2.8.2)
> .....

`$ sudo pip2 show electrum`
> 
> Name: Electrum
> Version: 2.8.2
> Location: /usr/local/lib/python2.7/dist-packages
> Requires: pyaes, ecdsa, pbkdf2, requests, qrcode, protobuf, dnspython, jsonrpclib, PySocks
> 

` $ sudo pip2 install https://download.electrum.org/2.8.2/Electrum-2.8.2.tar.gz`
> Downloading/unpacking https://download.electrum.org/2.8.2/Electrum-2.8.2.tar.gz
>   Downloading Electrum-2.8.2.tar.gz (2.3MB): 2.3MB downloaded
>   Running setup.py (path:/tmp/pip-q9sBdb-build/setup.py) egg_info for package from https://download.electrum.org/2.8.2/Electrum-2.8.2.tar.gz
>     
>   Requirement already satisfied (use --upgrade to upgrade): Electrum==2.8.2 from https://download.electrum.org/2.8.2/Electrum-2.8.2.tar.gz in /usr/local/lib/python2.7/dist-packages
> Requirement already satisfied (use --upgrade to upgrade): pyaes in /usr/local/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.9 in /usr/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): pbkdf2 in /usr/local/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): qrcode in /usr/local/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): protobuf in /usr/local/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): dnspython in /usr/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): jsonrpclib in /usr/local/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Requirement already satisfied (use --upgrade to upgrade): PySocks>=1.6.6 in /usr/local/lib/python2.7/dist-packages (from Electrum==2.8.2)
> Cleaning up...
> `

`$ sudo pip2 install --upgrade electrum==2.8.2`

> Could not find any downloads that satisfy the requirement electrum==2.8.2 in /usr/local/lib/python2.7/dist-packages
Downloading/unpacking electrum==2.8.2
Cleaning up...
No distributions at all found for electrum==2.8.2 in /usr/local/lib/python2.7/dist-packages
Storing debug log for failure in /home/hermann/.pip/pip.log

` $ sudo pip2 uninstall electrum`
`Can't uninstall 'Electrum'. No files were found to uninstall.`

Anything else I can try to make the upgrade work?

**Comment by hermann-san** [comment]
I've not found a solution to this problem. It may have to do with the fact that I've installed Electrum 1.9.7 with my Software Manager of Distro Mint.  So before trying to upgrade your 1.9.7, you should probably backup your electrum and uninstall 1.9.7 first with the software manager.

**Comment by ecdsa** [comment]
just released 2.8.3, which has the fix.

**Comment by hermann-san** [comment]
thanks for this fix.
I've tried it and it didn't work for me. I guess I've messed up the Electron Phyton package anyways before already, somehow.
I've now switched to Electron on Windows and I'm ok with it, for now.
