### ISSUE TITLE
Transaction not being confirmed for over 2 weeks

### ISSUE THREAD

**Issue by VeslavMalik** [spesmilo/electrum#2461]
I have sent a transaction with high fee (within 25 blocks) but on the next day it was not being confirmed and I realized that I have older Electrum version so I upgraded it. Now I am waiting for over 2 weeks and this transaction is not being confirmed at all. How long will I have to keep waiting for it to be finally confirmed? If this is not gonna be confirmed ever I will be forced to stop using your Electrum wallet and move to other Bitcoin software :(

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
