### ISSUE TITLE
Transaction rejected by our node. Reason: Transaction is trying to double spend. Input 0 is already spent.

### ISSUE THREAD

**Issue by Deogeron** [spesmilo/electrum#2463]
How can I rollback or delete rejected transaction? because my transaction hug as unconfirmed many days...

**Comment by bauerj** [comment]
There is no way to undo a transaction. However, most nodes will forget about a transaction after at most 2 weeks. If you want to spend the coins earlier, upgrade to 2.8.3 and try RBF or CPFP.
