### ISSUE TITLE
Cannot sign a message with keepkey

### ISSUE THREAD

**Issue by kyuupichan** [spesmilo/electrum#2469]
Several operations fail, likely same cause, but signing a message gives

"KeepKey_keystore object has no attribute get_coin_name" on pressing Sign button and after entering PIN.

**Comment by bauerj** [comment]
I think this should be fixed with 2.8.3. Do you use an older version?

**Comment by bauerj** [comment]
Related: #2410

**Comment by kyuupichan** [comment]
I'm using 2.8.3; the bug is still present

**Comment by bauerj** [comment]
Indeed, 265fd5ad3f7299d2c57f574e576734c97bbb2354 is not in 2.8.3.

**Comment by ecdsa** [comment]
since master is unstable at the moment, 2.8.3 was branched off 2.8.2, and does not have that commit.

**Comment by ecdsa** [comment]
closing; the fix will be in 2.9
