### ISSUE TITLE
'TrezorKeyStore' object has no attribute 'get_coin_name'

### ISSUE THREAD

**Issue by goodc0re** [spesmilo/electrum#2471]
Electrum v 2.8.2 on OSX 10.10.5 

With Trezor (fw 1.4.2) connected and trying to sign a message with a key, after entering the Trezor PIN, 
I always get the following error: 

'TrezorKeyStore' object has no attribute 'get_coin_name' 

Happens every time, can be reproduced.

**Comment by bauerj** [comment]
See: #2410
