### ISSUE TITLE
import error while running electrum/lib test cases

### ISSUE THREAD

**Issue by timgabets** [spesmilo/electrum#2473]
Guys, 

as I see, there are some test cases in **electrum/lib/tests** , but when trying to run some, I see something this:
``$ cd electrum/lib/tests``
``$ python test_bitcoin.py ``
``Traceback (most recent call last):``
``  File "test_bitcoin.py", line 5, in <module>``
``    from lib.bitcoin import (``
``ImportError: No module named lib.bitcoin``

I also can't see the ``unittest.main()`` calls anywhere in the code.
So, the questions is - how the Electrum lib/ routines are tested? 
Many thanks.

**Comment by bauerj** [comment]
I guess you should run them with `tox` (although `pytest` would probably work too(.

**Comment by timgabets** [comment]
Thanks, it makes sense now!
