### ISSUE TITLE
It would be good if Electrum were a package for easier installation on Termux. 

### ISSUE THREAD

**Issue by sdrausty** [spesmilo/electrum#2475]
It would be good if Electrum were a package for easier installation on Termux. 
![1ed9e362-35ad-11e7-9c7e-62ee97ea8254](https://cloud.githubusercontent.com/assets/27742457/26629058/c2be6e36-45ce-11e7-90de-0240c06e466d.png)

https://github.com/termux/termux-packages/issues/945

https://github.com/termux/termux-create-package

**Comment by sdrausty** [comment]
Can this be reopened? I think you may have closed it accidentally or maybe a little too soon.

**Comment by ecdsa** [comment]
no, it's out of scope.
ask termux to do that.
