### ISSUE TITLE
Higher fee in config

### ISSUE THREAD

**Issue by racerx2000** [spesmilo/electrum#2476]
How to increase transaction fee using command line ? 
I want to set "fee_per_kb" to 120 satoshi/byte
what amount I need to set in config 120 ? 120000 ?
need to set "dynamic_fees" to false to make new fee_per_kb work ?
Now fee every time is 50satoshi/kb how increase it to 120 ? I have no client, just command line

**Comment by bsbits** [comment]
see https://github.com/spesmilo/electrum/issues/2447

**Comment by racerx2000** [comment]
Excellent. Thanks

**Comment by racerx2000** [comment]
Wait. Set fee_level to 4 and still it shows 50satoshi/byte .. I need 200 and more. What number I should set ?

**Comment by dabura667** [comment]
Did you activate dynamic fees first?

**Comment by racerx2000** [comment]
Here is part of my config file
"dynamic_fees": true,
    "fee_level": 4,
    "fee_per_kb": 220000,

**Comment by dabura667** [comment]
Are you running electrum daemon as your current user? (Not sudo or root?)

**Comment by racerx2000** [comment]
I am running daemon as root

**Comment by dabura667** [comment]
run daemon as your user.

or run `sudo electrum setconfig` to set the config for root.

`electrum setconfig` will only change the config for the current logged in user.

**Comment by racerx2000** [comment]
I made it as root, and I see changes in root config, but nothing happened. 
I made fee_level 3 and 4, set fee_per_kb to 200000 and 300000 but everytime fee is 50s/byte
And sure, I reloaded daemon

**Comment by dabura667** [comment]
> everytime fee is 50s/byte

What commands are you using?

**Comment by racerx2000** [comment]
Run them as root
electrum dynamic_fees true
electrum fee_level 4
electrum fee_per_kb 220000

**Comment by racerx2000** [comment]
I am using electrum 2.6.3
Also I have electrum 2.8.2 where that settings works perfect
