### ISSUE TITLE
Non standard uncompressed public keys found in multisig redeem scripts

### ISSUE THREAD

**Issue by moodytomatoes** [spesmilo/electrum#2478]
This issue has 3 parts:

(1) - I was playing with Electrum multisig txs and I was surprised to discover non standard uncompressed derived public keys being part of the partially signed redeem scripts.

If uncompressed version is used, users would need to pay more tx fees if they use Electrum as fees are calculated on satoshis per byte.

- **Partially signed raw hex tx generated by Electrum wallet**:

`0100000001d6092ce364a662dd2fd3dd7acb5ad170e6a1004057dfb76900fad47d9c839ece00000000fd1e0100473044022041dee8a9ef00a23514205d8d08082f29821f0b6b9fbc77480e8979d80cf8c5c602206e4e9106e186b0d80e614e245f04552d8a6fa66dbba7de18efacf44cd535327e0101ff01ff4ccf522102d4c13772e97950783b2a77388264cd7978ca68b64f89454af63ec8bbc721e25e4c53ff0488b21e0320b9e4ae80000000a366f3a0ecdf14e11d3f6bd2c4d32ff4bbf20af34ddc6c691f3ead7ce847a72202af8db9fd4d6dd8f4ea2bf7b691867b6b7cd739ace17b8da69deaa08dc284d909000000004c53ff0488b21e03e0f2ff5c800000006764f416174007a50b3a6952700fd20a74bd41d96e9ee5de1c15c90d2e00d11f03632eef2f90dec92ce51c7a5ba623f9b45a0e6c17efd3b2aa2d239b262f4998970000000053aeffffffff01f4e40700000000001976a91493acc1373a05eb66814b107d128081b9a450238d88ac00000000`

- **Input script**: 

`OP_0 0x47 0x3044022041dee8a9ef00a23514205d8d08082f29821f0b6b9fbc77480e8979d80cf8c5c602206e4e9106e186b0d80e614e245f04552d8a6fa66dbba7de18efacf44cd535327e01 0x01 0xff 0x01 0xff OP_PUSHDATA1 0xcf 0x522102d4c13772e97950783b2a77388264cd7978ca68b64f89454af63ec8bbc721e25e4c53ff0488b21e0320b9e4ae80000000a366f3a0ecdf14e11d3f6bd2c4d32ff4bbf20af34ddc6c691f3ead7ce847a72202af8db9fd4d6dd8f4ea2bf7b691867b6b7cd739ace17b8da69deaa08dc284d909000000004c53ff0488b21e03e0f2ff5c800000006764f416174007a50b3a6952700fd20a74bd41d96e9ee5de1c15c90d2e00d11f03632eef2f90dec92ce51c7a5ba623f9b45a0e6c17efd3b2aa2d239b262f4998970000000053ae`

- **Decoded redeem script**:

`OP_2 0x21 0x02d4c13772e97950783b2a77388264cd7978ca68b64f89454af63ec8bbc721e25e OP_PUSHDATA1 0x53 0xff0488b21e0320b9e4ae80000000a366f3a0ecdf14e11d3f6bd2c4d32ff4bbf20af34ddc6c691f3ead7ce847a72202af8db9fd4d6dd8f4ea2bf7b691867b6b7cd739ace17b8da69deaa08dc284d90900000000 OP_PUSHDATA1 0x53 0xff0488b21e03e0f2ff5c800000006764f416174007a50b3a6952700fd20a74bd41d96e9ee5de1c15c90d2e00d11f03632eef2f90dec92ce51c7a5ba623f9b45a0e6c17efd3b2aa2d239b262f49989700000000 OP_3 OP_CHECKMULTISIG`

The first pubkey was generated from seed by Electrum wallet and the other two were derived from the imported xpubs. So the uncompressed ones came only from the imported xpubs.

According to [the docs](https://github.com/spesmilo/electrum-docs/blob/master/transactions.rst) they are encoded as uncompressed and occupy a lot more than compressed.

Same redeem script but with compressed keys:

- **redeem script**:

`OP_2 0x21 0x02d4c13772e97950783b2a77388264cd7978ca68b64f89454af63ec8bbc721e25e 0x21 0x02fe54097cbd201094483ffb8b650de21edbcddac7c518a3ff00ad6a70ea02307e 0x21 0x037444c79558cf3293e244c12dc20774bd13ea75f7ab1b439a524afcbb60893be6 OP_3 OP_CHECKMULTISIG`

- **redeem hex**:

`0x522102d4c13772e97950783b2a77388264cd7978ca68b64f89454af63ec8bbc721e25e2102fe54097cbd201094483ffb8b650de21edbcddac7c518a3ff00ad6a70ea02307e21037444c79558cf3293e244c12dc20774bd13ea75f7ab1b439a524afcbb60893be653ae`

Is there any reason that explains why Electrum is using uncompressed keys?

(2) Anyone watching the blockchain could infer that every redeem script with one compressed and two or more uncompressed derived keys were generated by an Electrum wallet and even which of the keys were generated by the wallet. Isn't that a privacy/security issue? If a flaw was discovered in Electrum wallet, could an attacker easily target vulnerable wallets?

(3) It seems like Electrum doesn't accept multisig input scripts with no signatures when signing. The ui doesn't send any response when importing the tx. When at least there's one signature the process goes fine, but I want the ability to create custom tx and let the cosigners scan and sign the tx even with no predefined signatures at all.

**Comment by ecdsa** [comment]
you are confused. there is no uncompressed keys in redeem scripts.

**Comment by dabura667** [comment]
Electrum uses a special un/partially/signed raw tx format.

You are confusing some special serialized data for uncompressed pubkeys, and your independantly generated unsigned tx data does not contain the proper data necessary for Electrum to sign it.

**Comment by moodytomatoes** [comment]
@ecdsa thanks for your reply but what about point (3)? @dabura667 what is electrum using then? why the wallet needs to have 'special serialized data' instead of the plain pubkeys? and what that serialized data is? It's not stated in the docs afaict (https://github.com/spesmilo/electrum-docs/blob/master/transactions.rst). I 'm trying to build custom multisig txs compatible with electrum.

**Comment by moodytomatoes** [comment]
@ecdsa @dabura thanks I see it now:

Electrum uses different redeem and input scripts serialization. It only uses the derived public keys in the redeem when there's a signature present for that key in the input script. When there's no signature yet Electrum puts the extended shared public key with a zeroed checksum appended. When signing the wallet replaces the extended keys with the derivation. It also uses custom signature slots for the input script.

There's no uncompressed keys in any stage of the process above (sorry for my noobness). As there is no standard for this between wallets it's good to let this info here. 

Closed #2478.
