### ISSUE TITLE
Why this error?

### ISSUE THREAD

**Issue by diegotco** [spesmilo/electrum#2479]
Can anyone help me to encrypt a message?

![2017-06-01_0755](https://cloud.githubusercontent.com/assets/22822405/26680656/e65e0a50-469f-11e7-9b0f-55673ec39f8b.png)

**Comment by ecdsa** [comment]
the public key should be in the same format as the public keys of bitcoin your addresses in electrum

**Comment by diegotco** [comment]
Sure. But it doesn't solve my problem :(

Any ideas?

**Comment by ecdsa** [comment]
it should
