### ISSUE TITLE
Anyone has examples about Public Key formats?

### ISSUE THREAD

**Issue by diegotco** [spesmilo/electrum#2480]
Owner says: "the **public key** should be in the same format as the **public keys** of bitcoin your addresses in electrum"

**Comment by diegotco** [comment]
This is my electrum public key

xpub6CBDNQeZ64HAyWBdbjZx7ZPenGpSWgtEwcnxA84Lu8P7vzFo6jWmQUJgRSYyNNqPFzHdDDeTSmSigNHNtp5nApk2BD6ZM7wyxyxXvWQcxqe

**Comment by ecdsa** [comment]
no that is a master public key
get the pubkey of one of your addresses

**Comment by diegotco** [comment]
Thank you very much. Where can I find every public key of my 27 btc addresses in my Electrum wallet?

**Comment by laszlomakk** [comment]
In the GUI, on the top row, go to `Wallet -> Addresses`. A new tab should appear named `Addresses`.

In this tab, you will find all of your addresses with a history plus a few unused ones. (this is simplified, actually only addresses within the gap limit are shown)
Right-click on any of the listed bitcoin addresses, and then click `Public Keys`.

**Comment by diegotco** [comment]
Thank you very much. I finished a pic to help other people ;)

Thank you @ecdsa and @laszlomakk :)
![2017-06-01_0855](https://cloud.githubusercontent.com/assets/22822405/26683266/db711d0e-46a8-11e7-84ee-f730c744c81b.png)
