### ISSUE TITLE
MultiSig Wallet (2of3) Big Problem

### ISSUE THREAD

**Issue by lennyy16** [spesmilo/electrum#2481]
Hey Guys,

i transfered invadvertently a lot of Bitcoins on my MultiSig Wallet and not on my Standart Wallet. I used the MultiSig Wallet bevore 2 Month and dont know the second person. Are there any options to get my Bitcoins? It is very annoying because it's about 2 000 euros.

It would be very nice if someone could help me.

Regards

**Comment by AbdussamadA** [comment]
how many of the 3 keys do you have? A 2 of 3 wallet means any 2 out of the 3 keys can be used to sign spending transactions.

**Comment by lennyy16** [comment]
If i klick on Detail at the transfer bevore 2 month i see under inputs this:

4db4d60e...8b3fc1ef:0    1M11NuwZSeEE18A6gJroFguSxrAJi4Xosu
9711f3c2...7b9b0f4b:0    1ELgrovYdDXnYUBC4xkCRAASq7FsjApLtT

Are this the Keys ?

Regards

**Comment by dabura667** [comment]
No.

When creating a wallet you must write down a 12 word phrase for each wallet.

In a 2-of-3 wallet that means there are 3 phrases. You probably have one, and the other 2 participants have one phrase each.

You need to get one more phrase, OR contact the person you made the wallet with and ask them to approve your send transaction to return your money.

**Comment by ecdsa** [comment]
I suppose he means "second factor" instead of "second person", so it's probably a two-factor authenticated wallet. @lennyy16 did you save the seed phrase on paper?

**Comment by ecdsa** [comment]
closing, no answer
