### ISSUE TITLE
"Replaceable"?

### ISSUE THREAD

**Issue by dja123** [spesmilo/electrum#2482]
I have a Replaceable name on my wallet every now and again that keeps happening and I need it's access

**Comment by bauerj** [comment]
I don't understand your problem.

**Comment by dja123** [comment]
d07cdf41e11ee9474263d93cec3d35d7d7994ecc55d62a44baac47ab3b022818

**Comment by dja123** [comment]
that's the tID

**Comment by dja123** [comment]
![untitled](https://cloud.githubusercontent.com/assets/29127583/26691889/714ab6d0-46c4-11e7-8a81-ebcaaa1a3e95.png)

**Comment by bauerj** [comment]
Bump the fee if you want it to confirm faster.

**Comment by dja123** [comment]
I tried but the fee in the Transaction box above has not changed.

**Comment by dja123** [comment]
the output is to a wallet that is no longer in service and I would like it to go back to my wallet which it usually does..

**Comment by dja123** [comment]
@spesmilo

**Comment by AbdussamadA** [comment]
You can't change the destination of the coins. You can only increase the fee.
