### ISSUE TITLE
Transaction didn't send

### ISSUE THREAD

**Issue by m4tysiak** [spesmilo/electrum#2484]
Welcome,
Yesterday i send transaction using electrum wallet. Watched it today, and it didn't even send. Adressess and TX show, that there is no transaction, it just wasn't send.

What to do ?

**Comment by m4tysiak** [comment]
One more word from me: in wallet it's unconfirmed

**Comment by AbdussamadA** [comment]
Follow these steps: https://bitcointalk.org/index.php?topic=1916963.msg19015496#msg19015496
