### ISSUE TITLE
Low transaction fee transaction

### ISSUE THREAD

**Issue by caddia** [spesmilo/electrum#2485]
I would like to try and cancel a transaction to raise the miner fee (I had messed up in not updating my electrum wallet before sending the transaction onward) if possible. I looked at the supposed other options (Wait several days for it to auto cancel, or the CPFP function), and because of coinbases transfer amount having to be over so much I cant just send enough to then resend with a higher fee. Thusly seeing as transactions will eventually cancel: Is there anyway, since the transaction has been marked as low transaction fee, I could have it cancelled early? Also just to make sure, Upon reading further into this, some wallets Auto-Refresh the mempool - so does that mean to have this cancel it would potentially be a week plus or manageable to cancel early?

**Comment by ecdsa** [comment]
read the faq
