### ISSUE TITLE
Trying to avoid the issue tracker becoming customer support

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2486]
Recently, I have noticed that many "issues" are support requests in nature (such as stuck transactions or needing help to achieve something with the GUI). These clutter the issue tracker.
In my view, the aims of the issue tracker should be highlighted to people, and some of the queries should be redirected to IRC and Bitcointalk. This could be stated in the README or in pre-filled issue templates. Prepending a paragraph to the README might be sufficient.

I suggest something along these lines:
> Please do not use Github's Issue tracker for support requests. Ask for help on IRC (#electrum on Freenode) or use the forums at [BitcoinTalk/Electrum](https://bitcointalk.org/index.php?board=98.0) instead. The issue tracker is for development/bug tracking purposes only!

**Comment by dabura667** [comment]
I agree adding a prefilled template for issues would help keep clutter down.

Most people will delete it and write whatever they want anyways... but it might help

**Comment by ecdsa** [comment]
maybe we should refuse to answer questions here when they are not really bug reports.

**Comment by jmliz** [comment]
@ecdsa yeah, but without previous notice for non dev people that approach would seem rude at least.

**Comment by anoadragon453** [comment]
Perhaps tag those issues as "support" and those that do and don't want to see them can filter them out?

**Comment by bauerj** [comment]
I'm closing this since there hasn't been any activity to this discussion in the past half year.
