### ISSUE TITLE
Why is it impossible to see my Master Public Key when I import my paper wallet keys?

### ISSUE THREAD

**Issue by diegotco** [spesmilo/electrum#2489]
Check it out:
![2017-06-03_1019](https://cloud.githubusercontent.com/assets/22822405/26754753/3ef8f88a-4846-11e7-8cb5-6fda4e8cde5f.png)

**Comment by ecdsa** [comment]
this website is not a FAQ. please use it to report bug.

**Comment by diegotco** [comment]
Ok, sorry
