### ISSUE TITLE
Error: I sent money to this 2FA address but It does't appear on my Wallet

### ISSUE THREAD

**Issue by diegotco** [spesmilo/electrum#2494]
This is the transaction:
https://live.blockcypher.com/btc/address/3KQQEFskXimBwpghmJBbW59ZRNZ3awNjcy/

But on my Electrum wallet I see this:

![2017-06-06_0830](https://cloud.githubusercontent.com/assets/22822405/26834408/e2877926-4a9a-11e7-86a6-5d98b6df20f2.png)

I am a lot worry about it ;(

Can you help me?

How can I spend those bitcoins :(

**Comment by diegotco** [comment]
I also followed this instruction http://docs.electrum.org/en/latest/2fa.html but it returns to me an address started with number 1. So I think I lost my money :( 

So sad

**Comment by diegotco** [comment]
Any Idea @laszlomakk

**Comment by diegotco** [comment]
Fixed :)

Problem was new version. It is ok 

Read more at: https://bitcointalk.org/index.php?topic=1599738.0

Thank you Thomas

**Comment by ecdsa** [comment]
@diegotco FYI, this kind of report is vague and useless for us. We are just wasting our time trying to understand what you could be talking about.

If you want to report bugs, please learn to give information that is complete and relevant.
