### ISSUE TITLE
Electrum Multisig w/ HW wallets

### ISSUE THREAD

**Issue by vmatekole** [spesmilo/electrum#2496]
I've had a difficult time getting Multisig (2 of 3) to work on electrum with a combination of HW wallets(Ledger/Trezor) and Android wallet.... With a lot of strange failures and have decided not to use it for multisig with HW wallets.

I'd like to transfer out the coins I used for testing but can't seemed to do that with a 2nd wallet I created — I've never been able to get the co-signer plugin to work...  Here is the saved transaction (unsigned):

{
    "hex": "01000000011d0617e85d5f978cc45a0eeab8f754acde5493b827b6dabab898d44de2bdcdda00000000fd0c010001ff01ff01ff4d0201524c53ff0488b21e000000000000000000ccd1623a5b51df8d6f657885b6b4e8f9155fff2e73a243254481a16efcf5b95b02920eb5f36bccee461f345ac3624a0d227de7615af559267b76ab9dd12a1d6ee8000000004c53ff0488b21e03b9155f47800000003efa6afe69a1f9c287d2f4e79ac9b6bc60dfbc500f469ad83e147a81044263e4032ef735b2082343d54e442fe124553d9cc4a9538c2abb7dc153c55ed28cd531a3000000004c53ff0488b21e02b278cb0c00000000a0738b3dcecf5a00da70790138a769057693dde79c2aaafb42d26f426eec339a035484d375159f96c45073e35a42933cc8c85faa1206d916f45614aecd6398b9f00000000053aefdffffff01710e06000000000017a91422f11d511bb1ae3ca190dfc85316e459d46c151d8700000000", 
    "complete": false, 
    "final": false
}

Let me know if you need anything else.

**Comment by ecdsa** [comment]
sorry but "a lot of strange failures" is not something we can work with.
this place is to submit bug report, not to provide end user support.

**Comment by vmatekole** [comment]
@ecdsa Granted — what I can say is I have suffered from a number of Bitcoin HW related issues already listed here e.g. https://github.com/spesmilo/electrum/issues/2471  ... I would like to get the remaining funds off this wallet.... Why isn't there a co-sign option? And no I didn't use xpriv keys to create the wallet but xpub...

![screenshot 2017-06-07 09 32 38](https://user-images.githubusercontent.com/424339/26867251-e33bdb94-4b64-11e7-968b-c4216be42f2a.png)

**Comment by vmatekole** [comment]
@ecdsa some further progress made on this.... The co-sign option appeared after I registered a separate wallet using the 2nd signatory (Ledger wallet) but that doesn't make any sense — since the android phone (3rd signatory) was already registered. Presumably, there is some registration process happening with the co-sign pool that the Android has failed to do....

Nonetheless, now I get failed to send to co-sign pool. Nothing appears on the console. 

![screenshot 2017-06-07 10 02 03](https://user-images.githubusercontent.com/424339/26868189-62a4f2b4-4b68-11e7-950d-523e2708ddb0.png)

**Comment by vmatekole** [comment]
I managed to find a workaround to the issues faced and transferred all funds... It appears I made a mistake of manually using the default xpub of one of the HW wallets. I did this as there were a number of failures in reading from one of the wallets, however, it appears Electrum doesn't use the xpub of the default account, which makes sense if you want to preserve privacy of the HW wallet when in single use. 

Nonetheless, it still doesn't explain why the Android signatory was unable to receive payment requests furthermore I couldn't determine how to read a raw transaction with the Android app. 

If anyone is attempting to create multisig with combination of different devices — Trezor/Ledger/Android – feel free to ping me. I have acquired some valuable experience in this  ;)  

Closing @ecdsa

**Comment by ecdsa** [comment]
there is no known bug with signing transactions.
the bug you are referring to is about signing messages, that is a completely different thing.

if you use a mobile phone as cosigner, you need to send the transaction over by qr code. the 'cosigning pool' is not supported by the android version.

if that's too difficult, just use trezor + ledger on you desktop, that should be enough (2 of 3)
