### ISSUE TITLE
does not confirmed password after his change

### ISSUE THREAD

**Issue by np87** [spesmilo/electrum#2503]
electrum 2.8.3 on win 8.1
I am create new wallet, and save password, After that i wanted send from this wallet, but my new password, which i copy/paste in file, does not work, i see message "incorrect password"
what i did wrong ?

this wallet does not have seed

**Comment by ecdsa** [comment]
are you sure you did not copy paste an extra space with the password?

**Comment by np87** [comment]
yep, absolutely sure

**Comment by ecdsa** [comment]
" can you explain " this wallet does not have seed ?

**Comment by np87** [comment]
i mean this
https://gyazo.com/a2c1bd2758397319a220d7c7ef419245

**Comment by ecdsa** [comment]
it is difficult to understand your situation with the limited information you give.
do these two wallets have the same history?

**Comment by ptilancelot** [comment]
escusez moi, je comprends? J'essaye beaucoup de faucet, ..Essaye de
comprendre bitcoin ethereum:...Donc c'est possiblle que j'ai plusieurs
adresses....Dont une coinbase que je retrouve plus...et j'ai de l'argent
dessus....c'est quoi la question, pour quel cite....

2017-06-09 13:12 GMT+02:00 ThomasV <notifications@github.com>:

**Comment by np87** [comment]
oh I'm also hard to understand

no i think this two wallets is different

**Comment by ecdsa** [comment]
@np87 any idea how you created the second wallet? are you sure it was created by you, or could it be someone else who accessed your computer?

**Comment by np87** [comment]
You know, I think that in the future I just need to be more careful about preserving personal data. (Well that the amount is not big on the wallet)

Thank you very much for the answers, I think this issue can be deleted as not informative

**Comment by micromatrix14** [comment]
Lol I laughed a lot, np87 you have a problem with your English level so, I guess it would be much better if you spoke with your native language, in addition you asked about claimed issue, then you should give information about what you have, what is the violation privacy, if we need information to fix the problem??
anyway I have to say you made my day, have a good time!
