### ISSUE TITLE
Electrum 2.7.17 Not Connected

### ISSUE THREAD

**Issue by Jammybam** [spesmilo/electrum#2504]
Hi,

I have Electrum Stratis 2.7.17 installed on a Windows 10 machine. The wallet simply states that it is 'Not connected' in the bottom lefthand pane. 

I have performed the following to no avail:

- Unchecked 'Use SSL'
- Disabled Anti-Virus
- Created a rule to allow both inbound and outbound traffic relating to 'electrum-stratis.exe'

Is there anything else I can try to troubleshoot this lack of connection? I have recently deposited some STRAT to my receive address and worried it'll be lost.

Any help is much appreciated!

**Comment by bauerj** [comment]
Please report that too [stratisproject/electrum-stratis](https://github.com/stratisproject/electrum-stratis).
