### ISSUE TITLE
Coins were sent to another address from my wallet

### ISSUE THREAD

**Issue by josedriving** [spesmilo/electrum#2507]
Hello
I logged in to my Electrum wallet from a different PC and synced my wallet using the seeds. But the coins in my wallet seems to be sent from my wallet to another wallet> I have 2fa enabled on the wallet. So how on earth can the coins be sent out from my wallet. Is this a bug issue ? Pls urgent help will be much appreciated

**Comment by ecdsa** [comment]
please provide relevant information (txid, addresses)

**Comment by josedriving** [comment]
902593d5e24253e1633b105f4e46f2bb4c4468776037f48cca6124aaaf0851d9  txid of the transaction and the adresss the coins were sent to is 1C2vbcjkSjUPS2xtspbeQmsmADq2NLB63Q

**Comment by ecdsa** [comment]
could it be that your seed phrase got compromised?

**Comment by ecdsa** [comment]
there are two ways to spend coins in a 2FA wallet: with your password and google authenticator, or with your seed phrase. it is possible to know which way was used, if you provide the 3 master public keys of your wallet.

**Comment by josedriving** [comment]
Ok I willl send them to your email . Pls provide your email. And thanks for your prompt replies

**Comment by ecdsa** [comment]
see my profile

**Comment by josedriving** [comment]
sent to your email

**Comment by ecdsa** [comment]
I can confirm that the transaction was signed with the two keys dericed from your seed and not by Trustedcoin. Maybe you disabled 2FA when you "synchronized the wallet using the seeds", or your seed was somehow compromised.

**Comment by josedriving** [comment]
I didnt disable 2fa. It must have been somehow compromised, God damned

**Comment by ecdsa** [comment]
let us know if you find out how.

**Comment by josedriving** [comment]
Looks like a keylogger was installed to the pc and the coins were sent out bypassing 2fa. thanks for your help and prompt response. Cheers

**Comment by ecdsa** [comment]
are you using windows? how did you find about the keylogger?
