### ISSUE TITLE
Cold Storage wallet reports "Server did not answer" after signing

### ISSUE THREAD

**Issue by anoadragon453** [spesmilo/electrum#2508]
Hey all.

After creating a transaction in my Watching Only electrum wallet, I brought it over to a Cold Storage wallet which has no internet access to sign. Upon pressing Sign and entering my password the wallet waits for a moment then returns "Server did not answer".

It seems that this is a recent problem, and I have been able to sign transactions completely offline in the past.

[Also seems as though I am not the only user hitting this issue](https://www.reddit.com/r/BitcoinBeginners/comments/6do5ru/electrum_cold_storage_cant_sign_transaction/)

Is there any reason we would need to connect to an Electrum server to sign a transaction? 

Thanks!

**Comment by SomberNight** [comment]
Hi.
What Electrum version is this with? If you are using Tails, I bet 2.7.9 (that's the one in the debian repositories).
Unfortunately, that version (and a few before/after) [have a bug with offline signing](https://github.com/spesmilo/electrum/blob/283/RELEASE-NOTES#L77).
You will need to update to a newer version.

**Comment by anoadragon453** [comment]
It is indeed 2.7.9. Will update to a later version, thanks!

**Comment by Kimland** [comment]
anoadragon453, could you share how you took care of this issue?  I updated Tails after finding this thread, but what was showing as version 3 point something ended up installing the same 2.7.9.  I did not realize till i signed the transaction only to see "Server did not respond."  Then I thought the cloning must have failed.  I went to using the intermediary USB, and that's when I realized the update was no update at all.  It was called 3.1 ... but it is just the same old 2.7.9.  I will appreciate your lead, if you don't mind.

**Comment by anoadragon453** [comment]
Hm, strange. I ended up uninstalling the current electrum (shouldn't remove your wallet file, but probably best to back it up just in case. You can find it under `~/.electrum/wallets/`.

Then download the latest .tar.gz from: https://download.electrum.org/2.9.3/

In the terminal, decompress with `tar xzvf Electrum-2.9.3.tar.gz`, `cd` into the directory, then run `sudo python setup.py install` to install the latest version.

Launch electrum and it should be v2.9.3.

**Comment by Kimland** [comment]
anoadragon453,

I presumed you did this update on Tails.  Was that the case?

I wrote back to the Tails developers and they told me that indeed the Electrum they have on the Downloads page showing as 3.1 (+ something on top) is actually 2.7.9.  They did not explain why the misnomer.

After something like 2 days of work I managed to update my Electrum in Ubuntu to 2.9.3, but not on Tails.  If you managed on Tails, please let me know so I don't have to give up.  Any further guidance you can offer would be greatly appreciated as well.

**Comment by tkarcher** [comment]
Thanks anoadragon453, I followed your steps but when I run `sudo python setup.py install` I get an error:

> Traceback (most recent call last):
>   File "setup.py", line 5, in <module>
>     from setuptools import setup
> ImportError: No module named setuptools

How do I get the missing module on the air-gapped machine? Thanks for your help!

**Comment by anoadragon453** [comment]
@Kimland I did this on Qubes on a [Split Bitcoin](https://www.qubes-os.org/doc/split-bitcoin/) installation. It was debian, as it Tails, so it shouldn't be any different unless Tails is wiping your install after you reboot.

@tkarcher Download setuptools from this link on a connected machine: https://pypi.python.org/pypi/setuptools#downloads (Check the md5 of the download matches that on the page)

Then install with `sudo pip install setuptools-36.4.0-py2.py3-none-any.whl`. Do this for any other missing dependencies, you should be able to find them all on the same website (PyPI).

**Comment by Kimland** [comment]
@anoadragon453, Thanks!!!   I figured much of it but installed the wrong pop.   The link to the downloads will be a huge help.

**Comment by Kimland** [comment]
I cannot get that ## setuptools to install.  However I found that once ## tar xzvf Electrum-2.9.3.tar.gz works I can open a spending Electrum-2.9.3 swallet with "./electrum" entry on the terminal.  Apparently it is only a bridge that is uninstalled after the decompression.  That will be good enough.

**Comment by engenegr** [comment]
Hi.

This code http://paste.debian.net/1030208/ produce errors on completely offline storage. The reason is obvious -- it has no inputs because it is offline. I can't figure out not what to do to fix a situation.

Version 3.1.3

**Comment by SomberNight** [comment]
@engenegr What are you trying to do? Sign with hardware wallets offline? see https://github.com/spesmilo/electrum/issues/3302

**Comment by engenegr** [comment]
@SomberNight I'm trying to make multisignature cold wallet.
Hack opportunity approved. If you import your cold wallet on online computer, export after txn history update and import on cold wallet back (with all history) it becomes able to sign a transaction.

So I see way to implement proper txn history import (not only inputs but also txn which have wallet addresses as outputs) and it could solve a problem. We need only extra step for history synchronization.
