### ISSUE TITLE
"Low fee" 

### ISSUE THREAD

**Issue by BiTBiX** [spesmilo/electrum#2511]
Hey my friends from electrum,
im waiting now since yesterday evening, but always on processing..
Pls look on this:
https://blockchain.info/tx/1199829e263aaabe900e2ff5656969bb05edfc44dc72920ba8221a9062b3d13a

**Comment by EagleTM** [comment]
Please note, github issues are not meant for user support, please consider using https://www.reddit.com/r/Electrum/ or IRC #electrum on Freenode instead.

wrt to your question: You're paying 100 sat/byte right at a time when the mempool was starting to fill up with many new transactions - see
Please note https://jochen-hoenicke.de/queue/#2w

Chances are the tx will confirm within the next few days, latest on the weekend, where less transactions are happening.
Try making further transactions "replaceable" so you can bump the fee after sending the transaction.
For this transaction you also try "Child pays for children" if you want it to confirm faster - see https://redd.it/5zchm8

**Comment by ecdsa** [comment]
see also http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
