### ISSUE TITLE
Can't Replace-by-fee stuck transaction after downloading latest version

### ISSUE THREAD

**Issue by 123345545** [spesmilo/electrum#2512]
I sent a transaction while in an older version which recommended a too low fee, transaction has been stuck for 24 hours, I downloaded the latest version of electrum but it won't let me replace-by-fee that transaction to get it unstuck. Thanks

**Comment by bauerj** [comment]
Replace-by-fee needs to be activated before sending the transaction you intend to replace. There is no way to enable RBF later.

You can try using CPFP instead:

https://redd.it/5zchm8
