### ISSUE TITLE
Can I load more wallet on dameon?

### ISSUE THREAD

**Issue by zottirik** [spesmilo/electrum#2514]
Is there any way to load more wallet same time on daemon?

**Comment by bauerj** [comment]
Please note, Github issues are meant for bug reports only.

To get support using Electrum, take a look at either

* https://www.reddit.com/r/Electrum/ 
* IRC #electrum on [Freenode](http://webchat.freenode.net/)
* https://bitcointalk.org/index.php?board=98.0

instead.

**Comment by ecdsa** [comment]
@zottirik yes, with 'electrum daemon load_wallet'
please read the inline help.
