### ISSUE TITLE
recovering from old seed

### ISSUE THREAD

**Issue by gidimic** [spesmilo/electrum#2515]
help.. all i have is the 12 word passphrase. and a bitcoin receiving address.
it seems that i opened a new wallet with this same passphrase, can this be true?
anyway, is there a way to recover from seed? I somehow don't seem to get it.
thanks in advance for any help,
and if this is not the right place for this kind of question - sorry then, let me know and i will delete it.
cheers
gidimic

**Comment by hachre** [comment]
Did you use the option to extend your seed when you first created the wallet? It sounds like it. If so you have to choose that in the options while restoring.

**Comment by gidimic** [comment]
Thank you hachre !
it is possible, i don't seem to find this option, i'm running OSX.
I also have a 18 word passphrase - completely different then the 12 word I have. can it be it?

**Comment by hachre** [comment]
You have to:
- go to File -> New/Restore
- choose "Standard Wallet", hit next
- choose "I already have a seed", hit next
- enter the 12 word seed and hit "Options"
- choose "Extend this seed with custom words", press okay and hit next
- enter the 18 word passphrase in the next screen
- finish the rest of the dialogs normally

and fingers crossed, hopefully that will be it

**Comment by ecdsa** [comment]
closing, no answer from OP
