### ISSUE TITLE
24 hours and transaction still pending 

### ISSUE THREAD

**Issue by bcgould04** [spesmilo/electrum#2516]
sent money from electrum to payment address - 24 hours later still shows pending

**Comment by bauerj** [comment]
Please note, Github issues are meant for bug reports only.

To get support using Electrum, take a look at either

* https://www.reddit.com/r/Electrum/ 
* IRC #electrum on [Freenode](http://webchat.freenode.net/)
* https://bitcointalk.org/index.php?board=98.0

instead.

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
