### ISSUE TITLE
Showing not even half of my coins being sent to wallet.

### ISSUE THREAD

**Issue by Hamrix** [spesmilo/electrum#2518]
I've had this problem with a friends wallet and tried mine today and the same problem. Localbitcoins is saying I bought $825.77 after fee to be sent to my wallet, but the unconfirmed is showing $335. I know there aren't fees in this range and I've never had a problem before, after contacting Localbitcoins.com they claim it's on Electrums end. I have all the information needed to prove my transaction.

**Comment by SomberNight** [comment]
Forget fiat. Think about all amounts in BTC.
Look at your transaction using a block explorer. Is there a discrepancy between what you see there and what your wallet is showing?

**Comment by Hamrix** [comment]
Looking at my blockchain in explorer. Can you tell me what to look for please?

**Comment by Hamrix** [comment]
It your saying what I see looks like a discrepancy than yes. I would believe so.

**Comment by ecdsa** [comment]
closing, no transaction ID
