### ISSUE TITLE
"Error: 'BIP32_KeyStore' object has no attribute 'import_key'" |WIF

### ISSUE THREAD

**Issue by romanornr** [spesmilo/electrum#2524]
Hi importing WIF privkeys doesn't work anymore.

````>> importprivkey('privkey_in_wif_format')````

results in ````"Error: 'BIP32_KeyStore' object has no attribute 'import_key'"````

**Comment by bauerj** [comment]
You can only import private keys into wallets that don't use seeds.

**Comment by romanornr** [comment]
@bauerj How do you generate a wallet that doesn't use seeds ? I didn't know it was possible.

**Comment by bauerj** [comment]
Just choose a different keystore when creating the wallet:

![electrum-2 8 3_2017-06-16_23-29-47](https://user-images.githubusercontent.com/598790/27245422-bb3c6f6c-52eb-11e7-964e-7a993607763d.png)

**Comment by zottirik** [comment]
How can we generate public or private keys?

**Comment by dabura667** [comment]
@zottirik 
```python
import os
from electrum.bitcoin import SecretToASecret
print SecretToASecret(os.urandom(32), True)
```

This will create private keys that you can import, but there is no reason to do so. BIP32 deterministic wallets are always a better idea.

**Comment by zottirik** [comment]
I think so @dabura667 , but I wish there was a way to import address

**Comment by dabura667** [comment]
There is a way. But you must use a separate wallet file.

**Comment by zottirik** [comment]
What is the way? I have a private key and address, how can add this address to my wallet?

**Comment by dabura667** [comment]
> how can *add* this address to my wallet?

You can't. You have to make a new wallet just for the separate keys.

**Comment by dabura667** [comment]
Example: (this requires there to be no "default_wallet" file present.)
```bash
~ $ electrum restore KxHGZLWSVaXS6GNfNvJLng2uo6ULe2xqzyMDDRWnSoGjXKn3FmBe
Password (hit return if you do not wish to encrypt your wallet):
Recovering wallet...
Found no history for this wallet
Wallet saved in '/home/dabura667/.electrum/wallets/default_wallet'
```
