### ISSUE TITLE
Electrum Wallet shows "No Data"

### ISSUE THREAD

**Issue by shshsgh** [spesmilo/electrum#2525]
Hello my Electrum wallet shows, 10 days now,
"NO Data" is see the btc transfer adresses but not my Money. there standing only "No Data"
i have create a new wallet, ther is self problem.
What can i do?
Thx

**Comment by bauerj** [comment]
Where does it show that? In the status bar?

**Comment by shshsgh** [comment]
@bauerj yes in the statusbar the normal screen. it shwos no data , and bx credit, it shows NO Fx Rade

**Comment by ecdsa** [comment]
this is because it failed to get the exchange rate
