### ISSUE TITLE
Appending higher transaction fee to unconfirmed transaction

### ISSUE THREAD

**Issue by userp7** [spesmilo/electrum#2526]
Is there a way to append a higher transaction fee to a transaction that hasn't been confirmed in more than 1 month (apparently due to low transaction fee) ?

**Comment by ecdsa** [comment]
read the faq

**Comment by userp7** [comment]
After reading the FAQ, I learn that there is a way to create a "Child Pays For Parent" transaction, however, it doesn't explain how to create such transaction.  Further searching the documentation for  HOW to create a Child Pays For Parent transaction results in nothing found.  Also nothing is found when looking through the various menus within Electrum.  Definitely a problem that needs to be fixed.  Also, at the bottom of the electrum window, it shows a non-zero balance, but the history textbox shows a 0 balance.  This is confusing because both balances should be equal.

**Comment by dabura667** [comment]
Did you try right clicking the transaction and clicking "Child pays for Parent"?

**Comment by userp7** [comment]
I right-clicked on the transaction, but there is no choice "Child pays for Parent".  The only choices are:
COPY DATE
DETAILS
VIEW ON BLOCK EXPLORER

I also tried creating a new transaction since it shows I have a non-zero balance (the software should actually show a 0 balance, but the 2.8.2 software has a bug), and the block explorer says "Transaction rejected by our node. Reason: Transaction is trying to double spend. Input 0 is already spent."
