### ISSUE TITLE
15 Words Seed from old Version unusable

### ISSUE THREAD

**Issue by electrumuserlein** [spesmilo/electrum#2529]
I tryed to grade up from Electrum 2.7.18 to 2.8.x. Electrum closed while reading the old wallet. I tryed to create a new wallet with my old 15 words seed, but the new electrum doesn't accept 15 words as seed. So my old (secure) seed is absolute unusable in the new electrum. This should not be.

**Comment by KeefeJ** [comment]
Although it's certainly not cool if Electrum 2.8.3 is unable to restore from certain old seeds, there's a possibility it's crashing when opening the wallet for another reason. Try opening a copy of the old wallet in a text editor and removing the contacts list (if any), then try opening the modified wallet in 2.8.3.

**Comment by dabura667** [comment]
No version of Electrum has ever produced 15 word mnemonics.

Electrum only guarantees backward compatibility for phrases that Electrum produces.

**Comment by electrumuserlein** [comment]
KeefeJ : Thanks, it works.
But i have realy a problem with the seed. I created a seed, without words a long time ago. The original seed is a text string or a hash (i don't know). And this Seed is not working if i import it in a new wallet. If I try to show my seed in electrum, it shows me 15 words. I remember, that i used years ago an option to generate a seed with a hi entropy.

Here the URL to the screenshot while showing the 15 words in electrum: https://abload.de/img/unbenannt1aulu.png

**Comment by ecdsa** [comment]
I suppose it is a custom made seed; early versions of electrum used to accept them.
please create a new wallet with an electrum seed, and send your coins there.

**Comment by electrumuserlein** [comment]
Yes it is a costum seed. But why is this costum seed not compatible with newer versions?

**Comment by ecdsa** [comment]
because seeds now have a version number.

**Comment by eepstein** [comment]
Try it with MyEtherWallet.com
