### ISSUE TITLE
No balance data in history

### ISSUE THREAD

**Issue by zuku81** [spesmilo/electrum#2530]
Hi I have problem with displaying Balance in Electrum, it shows at the bottom "No FX rate available" and in History on columns "PLN Amount" and "PLN Balance" it shows "No data" on every transaction.
To fix this I need disable "Show history rates" in setting because when it's enabled then only source I can choose is "BictoinAverage" and then this problem occur. When I disable "Show history rates" then columns PLN Amount and PLN Ballance disappears but I have at the bottom my current balance showing correctly.

**Comment by bauerj** [comment]
This will be fixed when a version with #2498 is released.
