### ISSUE TITLE
Generating DMG package from OSX fails because make_packages

### ISSUE THREAD

**Issue by ottodevs** [spesmilo/electrum#2531]
make_packages use of function imp.find_module() does not find the right path for modules, so it fails complaining about a "module not find" error, making imposible to generate the DMG install package.

I looked into python documentation and it says you can pass module name + optional path as imp.find_module arguments, maybe we can solve the problem just pointing to the right path?
(I verified that I have all modules installed by pip, I also tried with a python virtual env without success...)

Since I am not python insights expert I would like to receive some help to fix this problem, not only for electrum BTC, but for every altcoin electrum forks that have the same problems.

Thanks in advance.

Steps to reproduce:
Just clone the repo from osx and try to execute `python contrib/make_package` from project folder

Affected code block (find_module from imp):
```
    for module in deps:
        f, pathname, descr = imp.find_module(module)
        target = 'packages/' + module + descr[0]
        if os.path.exists(target):
            continue
        d = os.path.dirname(target)
        if d and not (os.path.exists(d)):
            os.makedirs(d)
        if descr[0]:
            shutil.copy(pathname, target)
        else:
            shutil.copytree(pathname, target, ignore=shutil.ignore_patterns('*.pyc'))
```

**Comment by bauerj** [comment]
`imp` is deprecated in favor of `importlib` anyway.

Can you check how your packages are installed? E.g. `import requests; print(requests)` should print where `requests` is stored.

**Comment by ecdsa** [comment]
I think make_packages will not be needed anymore once we use pyinstaller3

**Comment by ecdsa** [comment]
see cfffe2b53c4243cf99c6a532b78ef3318636e257

**Comment by ecdsa** [comment]
no longer needed with python3
