### ISSUE TITLE
Electrum (build-electrum-git.sh) does not build working windows binaries

### ISSUE THREAD

**Issue by t4777sd** [spesmilo/electrum#2532]
There is an issue with either the scripts or the instructions for building windows binaries from source. I have followed exact instructions starting from a fresh ubuntu installation with both Wine 1.6 (included with ubuntu) and Wine 2.01. The resultant binaries do not work. They are also 5MB smaller than the distributed versions, so either something is missing when installing from source with the instructions or something is added to the distributed versions.

Considering the readme in contrib/build-wine/ refers to "build-electrum.sh" which has not even existed since version 2.5 of electrum and has since been replaced by build-electrum-git.sh, I am pretty sure that the build instructions are lacking other relevant information.

**Does anyone know what is missing in the instructions that cause a failed build?** It appears to affect several userse: https://github.com/spesmilo/electrum/issues/2331

**Steps to Build**

1) Download the source for 2.8.3 from github

2) Install all the dependencies listed for linux to run it from the python code according to readme in root directory

3) Run the following according to the readme in the root directory:
./contrib/make_packages

4) Run the following according to the readme in ./contrib/build-wine/readme
./prepare-wine.sh
./prepare-hw.sh
./build-electrum-git.sh

**Result**
3 executables are created. Standalone, portable, and install. The Install executable will run the install process, but the resultant electrum executable does not work and immediately exit. The standalone / portable items also immediately exit.

**Comment by t4777sd** [comment]
It appears that the scripts do not include everything that electrum needs to build. Pretty scary because that means no one has been verifying the official builds to make sure they are the same as the source code. That is probably a big security risk.

When I run the built executables from the command line via wine, it outputs that it is missing "urllib3". I then add urllib3 to the make_packages.sh script and re-run. Re-build. It then says I am missing "chardet". I do repeat the steps again.

At this point it says that "ordered_dict" is missing. That I do not know how to correct. Based on a search, it appears that ordered_dict may be part of urllib3, so it should have already been included.

**Anyone have any advice?**

**Comment by Kolabolla** [comment]
Considering you closed the issue, it looks like you found a fix? If so, what's the fix?
