### ISSUE TITLE
Can't get dynamic fee estimates on testnet: "Waiting for fee estimates..."

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2534]
At the moment, Electrum fails to retrieve dynamic fee estimates on testnet. In the GUI, the fee slider shows unknown fees and the status message gets stuck on "Waiting for fee estimates...".

I have tried with both Electrum 2.8.3 and git master `31ab5b2e0a911a014ea1398f6f73fa3f311e76ec`.

This is around block height 1,140,000.

The currently online servers (on the most PoW chain) are:
```
electrum-btc-testnet.petrkr.net (ElectrumX 1.0.4, bitcoind 0.14.0)
electrum.akinbo.org (ElectrumX 1.0.10, bitcoind 0.14.0)
```
(and both are producing the "error")

I've been experiencing this for the past ~7 hours. Note that in this time frame, there have been more than 10,000 (!) blocks mined. Hence, the root of the problem might actually be with e-x or bitcoind not being able to provide a fee estimate.

The lack of a dynamic fee estimate makes sending transactions difficult. (When you click on "send", a popup window tells you "Dynamic fee estimates not available", which you can only "OK")
If you allow "Edit fees manually" in Preferences, and set a fee yourself, it works.

However, I would also like to report that sending RBF transactions seems NOT to be possible at all (when dynamic fee estimates are not available). It seems that the "replaceable" checkbox only appears when the client obtains the estimates, which it does not, hence it doesn't show up. (even if "Propose Replace-By-Fee" is set to "Always")
I tried, and with the checkbox not being there, if you send a tx, it's not RBF.

Also, it might be relevant to #2533, that I encountered that issue under these circumstances.

**Comment by ecdsa** [comment]
probably caused by 2533
