### ISSUE TITLE
Is there any page for the contributors (translators) ?

### ISSUE THREAD

**Issue by indetronable** [spesmilo/electrum#2536]

**Comment by bauerj** [comment]
Please note, Github issues are meant for bug reports only.

To get support using Electrum, take a look at either

* https://www.reddit.com/r/Electrum/ 
* IRC #electrum on [Freenode](http://webchat.freenode.net/)
* https://bitcointalk.org/index.php?board=98.0

instead.

**Comment by bauerj** [comment]
If you want to translate Electrum, you can find it on crowdin: https://crowdin.net/project/electrum
