### ISSUE TITLE
2.8.3: Create Keystore from Keys: 'Next' button grayed out

### ISSUE THREAD

**Issue by ErhardDu** [spesmilo/electrum#2537]
Hi,
after pasting keys into the text field 'Next' button stays grayed...
regards erhard

**Comment by ErhardDu** [comment]
It's running on a windows 10 machine

**Comment by bauerj** [comment]
What's the first character of the private keys? Do you have an "empty" private key you can post here?

**Comment by ErhardDu** [comment]
Example for private key:
5LL...

Example for public key:
1Fmp...

**Comment by ecdsa** [comment]
you cannot paste a mixture of private keys and addresses

**Comment by ErhardDu** [comment]
didn't mix it, tried them separately.
Is E parsing the input while it's in the textbox?

**Comment by ecdsa** [comment]
yes it is. I'm pretty sure there is no bug, you must have made a mistake.

**Comment by ErhardDu** [comment]
You are right. Private key is read without problems.
The address code from my test paper wallet doesn't work. Isn't this identical with the master private key?

**Comment by ecdsa** [comment]
an address is not a master private key.
read the docs for more info

**Comment by ErhardDu** [comment]
Thank you very much for answering my newbie question! Problem solved.
