### ISSUE TITLE
electrum history is now very slow now

### ISSUE THREAD

**Issue by zottirik** [spesmilo/electrum#2540]
@dabura667 hi,

My wallet size about 10M and electrum history command responds too late.
Actually, I need last 100 transactions only. Can you give any advice?

**Comment by ecdsa** [comment]
how many addresses are there in your wallet?

**Comment by zottirik** [comment]
There are 5200 addresses

**Comment by ecdsa** [comment]
you should create a new wallet and send your funds there.

**Comment by zottirik** [comment]
But I must listen all of my addresses. Can I split my wallet?

**Comment by ecdsa** [comment]
what is your use case?

**Comment by zottirik** [comment]
Continuous payments by customers.

**Comment by ecdsa** [comment]
is each address reused several times by the customer?

**Comment by zottirik** [comment]
Yes, you right

**Comment by ecdsa** [comment]
you can try to split your wallet, but that will not really solve your issue.
public electrum servers might answer slowly to this type of request, as a DOS protection.

you should probably run a private electrum server if you want to get over that.

**Comment by zottirik** [comment]
I think that all addresses are being scanned when the history command is running. Is there any way to save the last 200 tx list when Sync works? So I won't need to call history.

**Comment by ecdsa** [comment]
you are wrong, this is not related to the history command.
all addresses are updated when you synchronize your wallet

**Comment by zottirik** [comment]
How can I split my wallet?

**Comment by ecdsa** [comment]
export private keys, make smaller wallets out of them

**Comment by ecdsa** [comment]
note: you can also try to synchronize your wallet with a server that prunes histories.
in the server list, check one of those who have a limit equal to 100

**Comment by svenove7** [comment]
How do you find a server that only shows latest 100 transactions ? That is exactly what I want I think. After a while electum gets slow and it even takes time for the transactions I send to go to the history tab.  In tools/network you can unclick select server automatically but there is no information about the servers so how would I know one has a limit ?

**Comment by ecdsa** [comment]
@svenove7 there are no more pruning servers. if your wallet file is getting too large, you should move your funds to a new wallet

**Comment by SomberNight** [comment]
@svenove7 How big is your wallet (num addresses/transactions)?

**Comment by svenove7** [comment]
108 transactions now in my history. So then I have to do new wallets all the time if I do lots of transactions ?

**Comment by SomberNight** [comment]
> 108 transactions now in my history. 

That is a relatively small number of txns and the application should easily handle that. Modern Electrum becomes really sluggish around 10k transactions, so something else might be going on in your case.

- What OS are you using?
- What version of Electrum are you using?
- Are you running from source or using one of the official binaries? (if binary, which one?)
- What exactly do you mean by "electrum gets slow"? Does the GUI freeze (become unresponsive)?
- Could you please upload [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging)? (enable logging, do some tasks that make electrum slow so that they are logged, and then upload those logs for us)

**Comment by svenove7** [comment]
windows 10.
3.3.8  Installed it.
No electrum gui doesn't get slow but it was slow to add new transactions to the history. It seemed to do a lot more synching than it did before.
Right now the transaction was fast. Maybe it could be something temporarily ?

10k sounds better yes, 100 seems a bit low for a modern program to have problem.

**Comment by SomberNight** [comment]
>  No electrum gui doesn't get slow but it was slow to add new transactions to the history. It seemed to do a lot more synching than it did before.
Right now the transaction was fast. Maybe it could be something temporarily ?

Maybe you happened to connect to a slow server. You can try other servers if this happens.

**Comment by svenove7** [comment]
I think when I did send funds, then it should be no problem to add it immediatly in the history ?
But I don't know how all work in the bitcoin world. If a new entery is added do electum have to check every transaction before that one again ?
I have select server automatically now as a setting.

**Comment by svenove7** [comment]
It is working better now. I think the problem was too little RAM available or too little discspace on C:
