### ISSUE TITLE
False Balance

### ISSUE THREAD

**Issue by talal2** [spesmilo/electrum#2542]
Hello,
When i look at my amount, it looks like this : http://prntscr.com/fmktya
But when i see it on blockchain, the amount is not showing the same amount: https://blockchain.info/tx/296f46ca15b8fdf40f5798dbb12e80208d3d8daf0d67cca22b165171b70741fc
    -0.00635406 => 16.92$ on preev, but when i see it on blockchain, it looks like this: https://blockchain.info/tx/296f46ca15b8fdf40f5798dbb12e80208d3d8daf0d67cca22b165171b70741fc

                                  Thanks & Good luck to electrum team ;) :) .

**Comment by SomberNight** [comment]
I don't see the problem. Blockchain.info also shows that same amount:
```
Total Input	0.00635406 BTC
```

**Comment by ecdsa** [comment]
cannot use this report, not enough info
