### ISSUE TITLE
My Transactions Arent Going Through

### ISSUE THREAD

**Issue by Eddyboi** [spesmilo/electrum#2543]
My Transactions Arent Going through once again!, i had this issue about last week my transactions wouldnt go through or confirm any chainblocks for like 15 hours, i made a transaction there 2 hours ago and its taking ages...

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
