### ISSUE TITLE
My transaction history is blank

### ISSUE THREAD

**Issue by n0rw00d** [spesmilo/electrum#2544]
I have sent a transaction from my bitstamp and it has not showed up in my wallet. it has 6 confirmation and the address seems to be correct.  Please help.

**Comment by ecdsa** [comment]
either the address is not in your wallet, or your wallet is not synchronized.
why do you believe that the address is correct?

**Comment by n0rw00d** [comment]
3NVYu9UcyRW5b5NAo3ZgrxMPy6NDQjRMAe

Is cut and pasted from the address in the Electrum wallet.
and the following is cut and pasted from https://live.blockcypher.com

8.75757743 LTC to
 3NVYu9UcyRW5b5NAo3ZgrxMPy6NDQjRMAe
<https://live.blockcypher.com/ltc/address/3NVYu9UcyRW5b5NAo3ZgrxMPy6NDQjRMAe/>
 (unspent)

What do you suggest? Are the funds available?  Am I having software issues?

Thank you.  I am lost at what my next step is to do.

Chris Norwood

**Comment by n0rw00d** [comment]
how would I synchronize the wallet?

**Comment by ecdsa** [comment]
oh you sent LTC to a Bitcoin wallet? LOL

**Comment by n0rw00d** [comment]
What do I do?
can I fix it?

**Comment by ecdsa** [comment]
I don't know, I have no idea what you did.
please do not request support for the LTC version of Electrum here.
we do not distribute this version of Electrum.

**Comment by n0rw00d** [comment]
I understand but it was sent to the Electrum wallet on the block chain. Is
there anything I can do to reverse it?

**Comment by ecdsa** [comment]
not on the blockchain. the LTC blockchain is another blockchain.
please request support with the authors of Electrum for LTC, not here.

**Comment by n0rw00d** [comment]
Thank you
