### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Natthapo** [spesmilo/electrum#2547]
I want to cancel transaction.
I want my ฺBTC back.

Transaction ID:
a1319146ea6514f622398590564ff6b7c21ff94a9bc10c53841ff86c3dcebb42
 
status 13 confirmatoin

Date 2017-06-23 09:30

Amount sent:2.mBTC

Size:780 bytes

Free:0.5 mBTC ( 0.64102 mBTC/kB )
input (5)
03698d37...95db0419:22   1DNpy4L8fRdwQRWC1bj5fCwpKAofZ9KS2M
40a330a0...101c5197:15   1DNpy4L8fRdwQRWC1bj5fCwpKAofZ9KS2M
73c4ce31...8549ed96:19   1DNpy4L8fRdwQRWC1bj5fCwpKAofZ9KS2M
c266f950...bf6274ae:33   1DNpy4L8fRdwQRWC1bj5fCwpKAofZ9KS2M
dedf5cc4...d78f84f5:20   1DNpy4L8fRdwQRWC1bj5fCwpKAofZ9KS2M

output (1)
3F6NJpE23ButFEpziiXX4yzsD7Xw3ghUGW	        2.   

 
![12111](https://user-images.githubusercontent.com/27444888/27466752-23cfaa06-5807-11e7-998d-f1c31d5b2fae.jpg)

**Comment by ecdsa** [comment]
use google to learn about Bitcoin
