### ISSUE TITLE
Invalid OTP

### ISSUE THREAD

**Issue by Nemanja92M** [spesmilo/electrum#2549]
I just installed the Electrum wallet on my PC and I'm unable to send the mBTC to Poloniex. I keep getting this "invalid OTP" message. Please, help!

**Comment by bauerj** [comment]
Do you use a 2FA wallet?

**Comment by ecdsa** [comment]
make sure you synchronize your phone's clock

**Comment by Nemanja92M** [comment]
@bauerj Electrum 2.8.3 2FA.
@ecdsa How to do that?

**Comment by Nemanja92M** [comment]
I use the default wallet. :/

**Comment by bauerj** [comment]
Just make sure the time on your phone is correct. If you can't get it to work with your phone, restore from seed.

**Comment by ecdsa** [comment]
you can resync the phone in Google Authenticator's settings

**Comment by nopdejong1** [comment]
Hi, this is the second time it says "invalid OTP" after syncing phone and reinstalling Electrum twice. But I read somewhere you can switch off "time settings" when you reinstall Electrum/wallet?
Does anybody know where/how to do this?
Thanks in advance.... 
Nop/the Netherlands
