### ISSUE TITLE
PLEASE HELP!

### ISSUE THREAD

**Issue by Nemanja92M** [spesmilo/electrum#2551]
I just installed the Electrum wallet on my PC and I'm unable to send the mBTC to Poloniex. I keep getting this "invalid OTP" message. Please, help!

**Comment by bauerj** [comment]
Please don't open multiple issues for the same question,

**Comment by Nemanja92M** [comment]
ok, but can you help me?

**Comment by Nemanja92M** [comment]
Ok, thank you.
