### ISSUE TITLE
Downloaded client, sent myself bitcoin, can't send the bitcoin because I need a "password"

### ISSUE THREAD

**Issue by JohnJacobs** [spesmilo/electrum#2552]
I used this software to send bitcoin and after receiving my bitcoin I cannot send it using this application because I need a "password" that I have never put in or have been asked to put in prior.

**Comment by JohnJacobs** [comment]
I have been trying to figure out the issue because there is a lot of money involved on the line and I wasn't ever prompted to create a password after downloading and installing the Electrum 2.8.3 wallet. I do have a wallet key/bitcoin address but that is it.

**Comment by dabura667** [comment]
Did you write down the seed phrase?

Use that to recover to a new wallet file and this time remember your password.
