### ISSUE TITLE
I only received a fraction of the bitcoin I sent

### ISSUE THREAD

**Issue by AGUY765** [spesmilo/electrum#2555]
I sent 106 dollars worth of bitcoin to my electrum wallet, and I only received 41 dollars. What happened to my coins?? If someone could help I'd appreciate it

**Comment by hachre** [comment]
need a lot more info than that! 
- where did you send it from
- how much in bitcoin did you send
- from where did you send it (what kind of wallet, service)
- what's the transaction id
- how much of a fee did you pay

**Comment by AGUY765** [comment]
I sent the bitcoin from Coinbase, I sent 0.04271034. I sent it from the bitcoin wallet on Coinbase, and the fee was like 4 dollars

**Comment by bauerj** [comment]
How much BTC did you receive?

**Comment by AGUY765** [comment]
41.832 mBTC

**Comment by bauerj** [comment]
So you received 98% of the coins? The remaining 2% is the bitcoin network fee.

**Comment by AGUY765** [comment]
No, I recieved less than half of the bitcoins, I sent 106 US Dollars worth and only got 41 US Dollars worth

**Comment by bauerj** [comment]
The 41.832mBTC you received is worth about 100USD.

**Comment by AGUY765** [comment]
Okay I see where I went wrong

Electrum used to show me my bitcoin in dollar amounts, but it switched over to showing mBTC without letting me know. 

Thank you for helping me realize this. Saved me a lot of headache

**Comment by bauerj** [comment]
No worries!

Could you please close this issue?
