### ISSUE TITLE
This wallet is watching-only (HELP)

### ISSUE THREAD

**Issue by sebsava** [spesmilo/electrum#2556]
I need help 
![image](https://user-images.githubusercontent.com/29712491/27551095-0bdcca1c-5a70-11e7-888a-3c4bb3997142.png)

**Comment by hachre** [comment]
Do you have your Seed?

**Comment by sebsava** [comment]
mmm... No, How do I get it?

**Comment by hachre** [comment]
You got it when you set up Electrum for the first time. It's a string of 12 words. I don't think there's anything you can do in this situation without having your Seed.

**Comment by sebsava** [comment]
Can not recover?

**Comment by bauerj** [comment]
Not without the seed.

**Comment by sebsava** [comment]
I mean, I lost all those bitcoins :(

**Comment by bauerj** [comment]
Well, what did you do?

**Comment by sebsava** [comment]
I do not know, I opened the wallet and it was like this

**Comment by bauerj** [comment]
Do you recognize the transactions in the history tab? Do they belong to your wallet?

**Comment by sebsava** [comment]
Yes, they are payments that they made me

**Comment by bauerj** [comment]
If you didn't recently upgrade Electrum or anything I cannot imagine what could have caused this.

**Comment by sebsava** [comment]
I updated it a while ago and well, it appeared like this

**Comment by ecdsa** [comment]
If you never received a seed, then the wallet was probably installed on your system before you used Electrum for the first time, by someone else. It might be a theft attempt.

Older versions of Electrum did not display the "waching only" popup to warn the user. We display it now in order to prevent this kind of attack.
