### ISSUE TITLE
No shortcuts, no entry in the startmenu

### ISSUE THREAD

**Issue by Golddouble** [spesmilo/electrum#2558]
System: Windows 7, 32 bit

On my system I have two accounts: Administrator and "user" (Standarduser).

I installed Electrum (latest version) as user. After the installation there was no shortcut and no entry in the start menu. So I was confused.

But I was able to solve this. I found the shortcuts in the start menu of my administrator account. I was able to copy this shortcuts into my user account. No I can run it with my user account.

First:
I am very astonished, that the electrum installer does not consider if I install it as user or administrator. Am I the only one who want to use eletctrum as user instead of administrator and until now, no person did inform about this behavior?

Second: Suggestion:
Please make this a little bit userfirendly in the next version, so that electrum makes his shortcuts in the menu of the user, if it is installed through a user account.

**Comment by hachre** [comment]
To answer your first question: I think that's likely since an admin account is what Microsoft sets up for users by default and I've never seen anyone use non-admin accounts outside of an enterprise setting myself.

I just tried this out on Windows 10 1703 and can confirm it. When you use a non-admin account to install Electrum, you are asked to enter the account details for an admin on the same computer. Once you've done so, the installer seems to run in the context of that user instead of the user that's installing it and thus puts the start menu and desktop entries into the admin user's profile.

**Comment by Golddouble** [comment]
> To answer your first question: I think that's likely since an admin account is what Microsoft sets up for users by default and I've never seen anyone use non-admin accounts outside of an enterprise setting myself.

Maybe. But if you want to use your PC more secure, you should never use the administrator account, if it is not needed. In every magazine and in the internet you will find a lot of sites who advice never ever use the administrator account when it is not absolutely needed. And so I obey this advice.

> I just tried this out on Windows 10 1703 and can confirm it. When you use a non-admin account to install Electrum, you are asked to enter the account details for an admin on the same computer. Once you've done so, the installer seems to run in the context of that user instead of the user that's installing it and thus puts the start menu and desktop entries into the admin user's profile.

Glad, that you were able to reproduce this. Thank you.

The normal behavioir of a normal install of a windows programme is the following:
I start the setup.exe as user. Then it asks for the administrator. So I type in the password. The installation process starts. When it is finished I can normaly find the shortcuts in my user menu although during the installation process it asked for the administrator account.
-> So this is the way a normal windows  programme installation works.

So where can I place this as a suggestion to make a further version of Electrum more userfriendly?

Thank you.
