### ISSUE TITLE
Confusing help for `getprivatekeys` command

### ISSUE THREAD

**Issue by chipmixer** [spesmilo/electrum#2559]
Help for command `getprivatekeys` specifies this: Get private keys of addresses. You may pass a single wallet address, or **a list of wallet addresses**.

There is no way to pass a list of wallet addresses to this command. It expects an address: https://github.com/spesmilo/electrum/blob/b2332af77b2edfd22ba7b951d589546f7cc40c22/lib/commands.py#L271

**Comment by SomberNight** [comment]
I just tested this and it worked (used the console tab in the GUI):

```
>> getprivatekeys(["15F...","19L..."])
[
    [
        "Ky..."
    ], 
    [
        "L1..."
    ]
]
```

**Comment by chipmixer** [comment]
How do you define list in the CLI?

**Comment by SomberNight** [comment]
Should be clear from the above I think.
Use python syntax.
["alice","bob","charlie"] is a list of 3 strings: "alice", "bob", and "charlie"
But it might be the case that I don't understand your question.

**Comment by chipmixer** [comment]
By CLI I mean executing electrum script with parameters in linux terminal
```
usage: electrum [-h] [-v] [-D ELECTRUM_PATH] [-P] [-w WALLET_PATH] [--testnet]
                [--segwit] [--nolnet]
                <command> ...
```
You can execute
`electrum getprivatekey "15F..."` but executing `electrum getprivatekey ["15F...", "19L..."]` will throw:
electrum: error: unrecognized arguments: 19L...]

**Comment by bauerj** [comment]
Try `'["15F...", ...]'`

**Comment by chipmixer** [comment]
Thanks, it worked.
