### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by Golddouble** [spesmilo/electrum#2560]
I found, that we can enable "two factor authentication" in Electrum in combination with the service of TrustedCoin and three keys.

Question: 
Is it possible to enable "two factor authentication" without using the service of TrustedCoin and having only one key? I did not found this possibility. 

Seems I only can choose between 
-one password without "two factor authentication" or
-three passwords + TrustedCoin service + "two factor authentication"

Even online Wallets have the possibility to activate "two factor authentication" together with a single password. It astonishes me, that this is not possible with Electrum. Wouldn't this be an urgent security feature against key logger?

Why isn't this not implemented in Electrum until now?

Or did I miss it?

Would be interested for any clarification.

**Comment by SomberNight** [comment]
Online wallets/other not necessarily bitcoin-related services often implement 2FA with traditional password and time-based one time password being the two factors. This type of authentication doesn't fit easily into bitcoin's private key model. A time-based one time password does not translate into a private key without a central server and trust. This is essentially what TrustedCoin provides.
With TrustedCoin, even if they renege on their promise of signing your transactions, you can just use your own two private keys. With an online wallet, if you enable 2FA, there is no way for them to provide you with a comparable (trustless) solution. If you have a high-level description of an implementation in mind, please go ahead, I would be curious.

Alternatively, you can just set up a multisig wallet yourself for true multi-factor authentication.

**Comment by AbdussamadA** [comment]
You can create a 2of2 multisig wallet. It won't have just one key though but it will allow you to have second factor authentication without trusted coin. You will need two computing devices like a PC and a mobile or a PC and a laptop. Spend transactions will have to be approved by both devices.

http://docs.electrum.org/en/latest/multisig.html

BTW this place is not for general support questions. Next time post on the forum:

https://bitcointalk.org/index.php?board=98.0

Or ask in #electrum IRC channel on freenode

**Comment by ecdsa** [comment]
thanks @AbdussamadA 
yes, if you don't want to use Trustedcoin you can create your own multisig wallet.
using a third party cosigner is just more user friendly
