### ISSUE TITLE
Bitcoin stuck in wallet due to an error during wallet creation

### ISSUE THREAD

**Issue by Joshuam98** [spesmilo/electrum#2561]
A few years back I created my first electrum wallet. I was new to the whole idea of BTC so I just followed instruction from one of my friends. During the creation of the wallet, I was not provided with a wallet seed and the password I provided has never worked. I only had $40 worth of BTC so I wasn't too worried about it then, but the value has went up considerably and I'd really like for it to be usable. Is there anything to do about this, or am I just completely screwed? Thank you!

**Comment by ecdsa** [comment]
if you were not given a wallet seed, it is because someone else installed the wallet on your machine before you used Electrum for the first time. 

in order to prevent this attack, recent versions of Electrum require the password in order to open the wallet.
