### ISSUE TITLE
cold wallet tx, 16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)

### ISSUE THREAD

**Issue by boxxiet** [spesmilo/electrum#2566]
both machines linux/elect 2.8.3:

cpu 1 (online machine) - made a new watch wallet, for a Core 0.9 address I own, then created unsigned spend.

cpu 2 (offline machine) - made new wallet by importing that Core 0.9 privkey, then signed the above transaction with it.

copied tx to cpu 1 - broadcast it but get error:

error: The transaction was rejected by network rules.(16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation))

The address I am trying to spend is just a regular address made of 2 inputs, the tx spent 100% of it (minus fees) to 1 single output

**Comment by ecdsa** [comment]
can you check #2519 and see if it's a duplicate?

**Comment by boxxiet** [comment]
His issue sounds similar, but he describes a 2nd error I did not encounter.

Here is my problem again, I took detailed notes:

send to: 1NTFKEQxQVX1Wxfm4WAySW5pSosbyagfNA
amt: 0.00181857
fee: 0.00018143
replaceable: yes

create this tx on the Watch-only wallet , it will create this unsigned tx:

0100000001540e95841b477f496e1b0f5b7dcb0f9589e591443546d711c33ae8ed3a9ec1fd000000001901ff16fd001fadf4e0f90d612af18eaee141f7ed43e2743c19fdffffff0161c60200000000001976a914eb5167ccc89bb8ba9ae3fb802eee51091179703788ac00000000

Then transfer to the signing-wallet, which will sign that as:

0100000001540e95841b477f496e1b0f5b7dcb0f9589e591443546d711c33ae8ed3a9ec1fd00000000604830450221009b6b6decd1f9c279293a517585819aebca05778c18ed35abbccfaa16f269c3980220108324294ca6b5217645ce4277d5cb2dd3dc17e2b9c796fca4836fdc455317bd0116fd001fadf4e0f90d612af18eaee141f7ed43e2743c19fdffffff0161c60200000000001976a914eb5167ccc89bb8ba9ae3fb802eee51091179703788ac00000000

which gives the error if broadcast. ( "mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)" )

However if you make a new wallet, and import the privkey , it creates this unsigned tx instead:

0100000001540e95841b477f496e1b0f5b7dcb0f9589e591443546d711c33ae8ed3a9ec1fd000000002401ff21031be30fa29d3dc22c8abcc8bbab5ac10ce8c695229291bd670b594848570fda59fdffffff0161c60200000000001976a914eb5167ccc89bb8ba9ae3fb802eee51091179703788ac00000000

which looks similar, but is 22 chars longer.

and now, that same wallet will sign it as:

0100000001540e95841b477f496e1b0f5b7dcb0f9589e591443546d711c33ae8ed3a9ec1fd000000006b4830450221009b6b6decd1f9c279293a517585819aebca05778c18ed35abbccfaa16f269c3980220108324294ca6b5217645ce4277d5cb2dd3dc17e2b9c796fca4836fdc455317bd0121031be30fa29d3dc22c8abcc8bbab5ac10ce8c695229291bd670b594848570fda59fdffffff0161c60200000000001976a914eb5167ccc89bb8ba9ae3fb802eee51091179703788ac00000000

which broadcasts Correctly .

**Comment by boxxiet** [comment]
here is the Correct tx https://blockchain.info/tx/35414fc66e524a83f1b7fe566a0fd04651579a7244ae7d0b4465e26da56af523

**Comment by ecdsa** [comment]
thank you

**Comment by boxxiet** [comment]
I am very curious what the Bug was, if you could provide a quick explanation, I would appreciate it!
Thanks for writing Electrum.

**Comment by ecdsa** [comment]
The bug is not with the signature; that is why it took me so long to find it, I first thought the signature was incorrect. The problem is that the public key is not correctly serialized in the final transaction; it is serialized as "extended pubkey", which is an Electrum format that means "the pubkey that corresponds to the following address"

**Comment by boxxiet** [comment]
Was this bug introduced recently?

**Comment by ecdsa** [comment]
I believe in 2.8.0
previous versions should be fine

**Comment by boxxiet** [comment]
Thanks again.
I removed info for My privacy's sake but if you need it again I will repost it.

**Comment by kirillseva** [comment]
@ecdsa fighting the same issue now, coupled with generating lots of addresses using `wallet.create_new_address(False)` on another machine. On 2.8 I was able to open electrum wallet in vim, add the address into `receiving` field in addresses, and I was able to send those funds.
However, because of the broken multisig (or whatever is wrong with 2.8), I cannot reproduce this step.
I tried installing and running electrum 2.6 but the wallet format is different. How to I force-add an address to electrum 2.6 wallet?

**Comment by ecdsa** [comment]
@kirillseva please upgrade to 2.9. I'm not going to help you with older versions.

**Comment by jjduhamel** [comment]
I'm getting this issue on v2.9.2.  Earlier versions of Electrum either won't open (prompts me to open console), or can't ready my wallet file.

**Comment by kirillseva** [comment]
I dug through the sources and fixed my problem (it wasn't in the source
code, but in my brain). Works flawlessly now, thank you very much for
Electrum, we all really appreciate it

**Comment by PhoenixFS** [comment]
kirillseva,
You SOLVED this NIGHTMARE???  How? Where can I find the information? I just “met” Electrum a few days ago, have money stuck in it with the this stupid verify problem. The transaction gets signed ok, but will  Broadcast! What do I need to do? Please advis... ASAP? I truly appreciate your anticipated help in this matter. I’m getting close to Panic Mode; you know, when I start REALLY screwing thing up?
