### ISSUE TITLE
How to get the redeem script form P2SH address?

### ISSUE THREAD

**Issue by heropzy** [spesmilo/electrum#2567]
I am using Electrum two factor Authentictation wallet which is P2SH start with 3.
want to claim XLM, it said 'For P2SH (multisig) addresses, you will be asked for a redeem script' How can I get the redeem script?
Any one can support?
Many thanks

**Comment by AbdussamadA** [comment]
@ecdsa please close this as OP has also made a forum thread

**Comment by heropzy** [comment]
Close
