### ISSUE TITLE
kivy (Android): CJK characters cannot be displayed

### ISSUE THREAD

**Issue by SwimmingTiger** [spesmilo/electrum#2575]
When I switch the language from English to Arabic, Chinese or Japanese, these Arabic, Chinese and Japanese words will cannot be displayed. It looks like some fonts are missing when the character is rendered. Although proper fonts exist in my system (example: /system/fonts/Miui-Regular.ttf. I have no DroidSansFallback.ttf in my system), Electrum looks like don't use them.

There is a screenshot:

![screenshot_2017-07-01-06-12-24-587_org electrum electrum](https://user-images.githubusercontent.com/4986069/27755962-0e8356aa-5e26-11e7-9c21-af421857fd2c.png)

**Comment by bauerj** [comment]
Closed in favour of #2032.
