### ISSUE TITLE
Issue with recent transaction

### ISSUE THREAD

**Issue by daberb** [spesmilo/electrum#2584]
I did a transaction this morning to a person I've done transaction with before.  It has been a couple of hours now, on the history page of Electrum in the date field it is showing "Replaceable" with a yellow triangle to the left of it with the amount sent still in unconfirmed status, and she does not see the transaction on her end.  What did I do wrong and how can I fix this? 

Thanks
David

**Comment by hachre** [comment]
Right click and choose "show on block explorer" & post the link to the page that opens up here.

**Comment by daberb** [comment]
https://blockchain.info/tx/d19ce6d248f3914e1435b67de2710bee983ae3e813a27c8d68e4a17ec4a0d640

**Comment by hachre** [comment]
Your fee per byte is very low (~35). You can check the following page: https://bitcoinfees.21.co/

On the left side you see the Fee range and on the right side you see outstanding transactions that have to be worked off. Higher Fees always have priority. By using a ~35 fee you have to expect up to 32-42 blocks currently of transaction time which is roughly between 6 and 8 hours. 

The replaceable allows you to increase the fee on this transaction to make it go faster. The currently recommended fee for a fast transaction (<30 minutes) is around 330. The site shows you that below the graphs. 

You can either wait a few more hours for it to complete or increase the transaction fee by right clicking and choosing that option.

**Comment by daberb** [comment]
Thank you hachre..... I'm still new with BTC and learning.. thanks for your help...

**Comment by hachre** [comment]
No problem! Please also close this bug report.
