### ISSUE TITLE
Failing to respond to a notify event causes electrum to hang

### ISSUE THREAD

**Issue by block8437** [spesmilo/electrum#2588]
Hi!

So I was having issues with `getaddresshistory` returning the `BaseException: Server did not answer` error through the JSONRPC, and I've isolated it to the following steps:

    $ python electrum daemon start
    starting daemon (PID 67645)

    $ python electrum daemon load_wallet
    Password:
    true

    $ curl --data-binary '{"id":"curltext","method":"getaddresshistory","params":{"address": "1Pr12KnNfU9DUk1L9H7BgqcB1pMViFcaFL"}}' http://127.0.0.1:7777
    {"jsonrpc": "2.0", "result": [{"tx_hash": "06fdfc940e0b2e095c574df0ccfa9a7b8bacd51829eb33e6e05d3a12837ae100", "height": 475002}], "id": "curltext"}

    $ python electrum notify 1Pr12KnNfU9DUk1L9H7BgqcB1pMViFcaFL http://127.0.0.1:8060/tx/1Pr12KnNfU9DUk1L9H7BgqcB1pMViFcaFL
    true

    $ curl --data-binary '{"id":"curltext","method":"getaddresshistory","params":{"address": "1Pr12KnNfU9DUk1L9H7BgqcB1pMViFcaFL"}}' http://127.0.0.1:7777
    {"error": {"message": "Server error:   File \"/Users/avisaven/Downloads/electrum/lib/network.py\", line 1052, in synchronous_get | BaseException: Server did not answer", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}

    $ python electrum getaddresshistory 1Pr12KnNfU9DUk1L9H7BgqcB1pMViFcaFL
    [
        {
            "height": 475002,
            "tx_hash": "06fdfc940e0b2e095c574df0ccfa9a7b8bacd51829eb33e6e05d3a12837ae100"
        }
    ]

Pretty much, `getaddresshistory` works fine until I apply a notify event on the address, after which case it stops working. However, using just the client it still does work.

This was tested as of commit `b02ce2d02caa2001d1b54b021351615426222017`

**EDIT**: On further analysis, the problem was the page not responding to the notify request, which caused electrum to hang.

**Comment by ecdsa** [comment]
cannot reproduce.
'server did not answer' is not something that depends on the client
