### ISSUE TITLE
Can't send to self, offline signing test

### ISSUE THREAD

**Issue by boxxiet** [spesmilo/electrum#2590]
doing a test-

pc1- made a new standard electrum wallet, funded one of the addresses

pc2- made a watch wallet, of the above funded address. Correctly sees the balance.

Created a Send of 100% (minus fee) to a different adress which also belongs to pc1. In other words I'm sending from myself to myself.

Problem:
took tx to pc1 to sign... but after loading, "Sign" is greyed out!

says Amount Sent: 0.

But It shows the correct Source and Dest inputs, both are Green, shows the correct output amount..  just can't sign!   Why not?

**Comment by ecdsa** [comment]
use your maser public key to create the watching only wallet

**Comment by boxxiet** [comment]
I don't understand why that would make a difference, and (2) why does the Offline pc refuse to sign a valid message?

**Comment by boxxiet** [comment]
Also The xpub would link those addresses together , for privacy sake I should be able to watch just one or two of them ? And still be able to spend offline

**Comment by ecdsa** [comment]
it makes a difference because the offline pc cannot recognize an arbitrary number of addresses if the xpub is not attached.

**Comment by ecdsa** [comment]
the other solution is that you create an offline wallet from the corresponding private key.

the following combinations work:
xpub <-> xprv
privkeys <-> addresses

**Comment by boxxiet** [comment]
> create an offline wallet from the corresponding private key.

I am confused why that would work but this will not :) What is making it grey out Sign when it knows the private key and even shows the input as Green ...

**Comment by boxxiet** [comment]
Ie I am unclear what you mean when you say "the offline pc cannot recognize an arbitrary number of addresses if the xpub is not attached" ... because the offline PC does have it, in fact that is where I would get the xpub from...

**Comment by ecdsa** [comment]
you can create an arbitrary number of addresses from an xpub.

if the transaction you pass to the offline signer only contains addresses, then the offline signer would potentially need to generate an arbitrary large number of addresses from its xpub, in order to test ownership of the addresses included in the transaction. this is absurd.

**Comment by boxxiet** [comment]
Ok, I think I understand now, thank you.

So the reason my offline pc showed these as Green was because they were addresses from "the first 20 generated" 

and if It had been a valid address, 1,000 after the "first 20" it would NOT have shown as Green.  Is that correct?

**Comment by ecdsa** [comment]
that's correct
