### ISSUE TITLE
Password isnt working to send coin from elecectrum

### ISSUE THREAD

**Issue by cole262** [spesmilo/electrum#2596]
I used the password to login and then went to sent the coin and the password didn't work. Then tried to use my seed to reset it, but there was never an option to do this. Please help in need of some major assistance.

**Comment by bauerj** [comment]
> Then tried to use my seed to reset it, but there was never an option to do this.

Are you on Windows?

**Comment by cole262** [comment]
Yes. After a few more times of trying the same password it finally went through. Just tested it with multiple small transactions, and seems to be working fine now.

**Comment by hachre** [comment]
Maybe you had Capslock on by accident?
