### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by jalbritt** [spesmilo/electrum#2597]
I created an electrum wallet today and wrote down my mnemonic and password, but when I tried to send coins I got a message that the password I was entering was invalid. I tried closing electrum and re opening the program using a different server, but I still got the invalid password message. I have tried entering the password in many different ways and none of them worked. I have my seed written down, so I deleted all of the electrum files off of my computer except for a copy of the wallet file with funds in it and tried to recover my wallet with the seed. When the wallet recovered, there were no funds in the wallet and all of the addresses were different than my original wallet.

**Comment by kyuupichan** [comment]
Did you perhaps confuse passwords and extension phrases (a.k.a. passphrases)?

**Comment by jalbritt** [comment]
No, when I created the wallet I wrote down exactly what I typed into the "password" and "confirm password" forms. When I tried to enter this password to send the coins I got the error message.

**Comment by hachre** [comment]
@jalbritt It sounds like you used a seed with custom extended words. If so you have to select that option during the restore and add those words in the given field.
