### ISSUE TITLE
Max Gap Limit for electrum wallet

### ISSUE THREAD

**Issue by deveshaggrawal19** [spesmilo/electrum#2598]
I am developing a website, which requires creating a bitcoin address for each user. On reading BIP 0044 I came across with gap limit. On my understanding, there can not be more than x consecutive unused address where x is the gap limit or else it won't restore them after backing it up. Stop me if I am wrong. So what is the max of gap limit for electrum. And also during backing up does electrum backs up all the address that are consecutively unused also.
Please help a fellow enthusiast of the crypto domain.

**Comment by dabura667** [comment]
1. 20
2. by definition BIP32 allows access to all address indices, so yes.

**Comment by deveshaggrawal19** [comment]
I read somewhere that it can be increased to 100. So during restoring, if electrum finds 20 consecutive unused addresses it won't' recover after that

**Comment by dabura667** [comment]
Yes, unless you change the value.

It could be 5000 or whatever you want.

**Comment by deveshaggrawal19** [comment]
okay thanks for the quick reply, one more question, can you help me how to interact with electrum wallet using python3 using scripts. If you point me in the right direction, it would be a great help

**Comment by wildlily980** [comment]
> Yes, unless you change the value.
> 
> It could be 5000 or whatever you want.

Electrum was frozen when I set gap_limit to 40,000 and reamained in syncing for ever.
