### ISSUE TITLE
wallet not able to load in daemon mode with testnet

### ISSUE THREAD

**Issue by deveshaggrawal19** [spesmilo/electrum#2600]
command: electrum --testnet -w /home/devesh/.electrum/testnet/wallets/default_wallet daemon load_wallet
It asks for password, after entering password it outputs daemon not running

What could be the problem

**Comment by ecdsa** [comment]
that you did not start the daemon in testnet mode?

**Comment by deveshaggrawal19** [comment]
What do you mean?
I first tried to load main net wallet by this
electrum -w /home/devesh/.electrum/wallets/devesh_wallet daemon load_wallet
It was running just fine. Then I tried the same with testnet wallet and with --testnet extra parameter like above, but it was not able to start the daemon.
NOW I tried again with the mainnet wallet, and the same problem is occurring. I couldn't understand, how can a working thing break. GUI of both testnet and mainnet are working fine

**Comment by ecdsa** [comment]
if the GUI is open, it behaves like a daemon, so you don't need to start a daemon

**Comment by deveshaggrawal19** [comment]
I need the daemon process so that I can interact it with over jsonrpc

**Comment by deveshaggrawal19** [comment]
Found the mistake. I was supposedly first run the daemon and the load the wallet. I was not doing that.

**Comment by deveshaggrawal19** [comment]
One more question
testnet wallet gui is showing the btc but json rpc is not:
![screenshot from 2017-07-13 02-40-53](https://user-images.githubusercontent.com/17562041/28140182-e8ba2de2-6774-11e7-9832-f267c8b0ab21.png)




$curl --data-binary '{"id":"curltext","method":"getbalance","params":[]}' http://127.0.0.1:7777
{"jsonrpc": "2.0", "result": {"confirmed": "0", "unconfirmed": "0"}, "id": "curltext"}

**Comment by l3v1k** [comment]
I had same issue. Run daemon with --testnet flag, but all RPC commands return data from mainnet. But if i run cli command with --testnet flag i get right response with testnet addresses
<img width="1029" alt="screen shot 2018-08-27 at 19 04 33" src="https://user-images.githubusercontent.com/6277287/44670704-19076c80-aa2c-11e8-816e-75ccb705f25b.png">
.

**Comment by l3v1k** [comment]
Oh, it was simple: you need to specify port and get password with **--testnet** option:
```
electrum setconfig rpcport 7778 --testnet
electrum getconfig rpcpassword --testnet
```
And then using this.

**Comment by xiaods** [comment]
it's not working currently in 3.2.3

**Comment by xiaods** [comment]
not reproduce this bug.
