### ISSUE TITLE
'NoneType' object has no attribute 'decode' when trying to sign multisig transaction with Ledger Nano S

### ISSUE THREAD

**Issue by willyloman** [spesmilo/electrum#2609]
I am on macOS X 10.12.5, Electrum 2.8.3 (downloaded from website), and have an updated Ledger Nano S which I have used as a cosigner in a multisignature wallet. I have also successfully `pip install`ed `btchip-python`. I am able to fund the multisig wallet, but when I try to send funds from the wallet in Electrum, I am unable to successfully sign the transaction and send it to the other cosigners. After I create the transaction and try to sign it with my Ledger Nano S (which is plugged in and unlocked), I briefly see a "Confirm transaction on device" dialog before the error prompt displays "'NoneType' object has no attribute 'decode'" and then Electrum becomes unresponsive.

I've seen a couple of [related](https://github.com/spesmilo/electrum/issues/2352) [issues](https://github.com/spesmilo/electrum/issues/1959), but it's very possible that I've constructed my wallet incorrectly (I used the 3 xpub keys I extracted from the cosigner hardware devices). Is this an incompatibility bug I'm running into or have I mis-stepped along the way in creating the wallet/txn?

**Comment by willyloman** [comment]
FWIW, I was able to get around this and sign a transaction using a hardware wallet by downgrading to 2.7.18. I initially tried using 2.8.0, but the issue was present there, too. Now, however, it fails to send the transaction to the cosigner pool: "failed to send transaction to cosigning pool".

**Comment by ecdsa** [comment]
this should be fixed in 2.9. please confirm.

**Comment by ecdsa** [comment]
closing, no answer

**Comment by willyloman** [comment]
@ecdsa: Yes, I can confirm that I am able to sign transactions using the Ledger S Nano in version 2.9.2. Thank you! If it's easy, do you have a pointer to the code fix/PR that was made to address this?

This probably merits opening another issue: after signing the transaction with one of the private keys, I am unable to send the partially signed transaction to the cosigner pool.
