### ISSUE TITLE
Windows binary will not work when using the guide

### ISSUE THREAD

**Issue by Kolabolla** [spesmilo/electrum#2610]
**Binaries build on** 
- Ubuntu 16.04 - 64 bit, Wine 2.0.1 
- Ubuntu 16.04 - 32 bit, Wine 2.0.1 

**Tested using**
- latest commit
- version 2.8.3 commit
- sources on electrum.org

The binaries will be created without any issues or errors being thrown. It's noteable that, for some reason, the sizes of the binaries are different from the binaries on electrum.org. The source will also install just fine on Ubuntu itself.

**Issuse**
Setup, nor standalone, nor portable binaries will actually work on Windows. Once started they will terminate afte a view seconds without actually doing anything. The setup exe will actually install Electrum but it will not work as stated above.

Using the binaries from electrum.org Electrum launches just fine and works as intended.

This might be a related issue: https://github.com/spesmilo/electrum/issues/2532

**Comment by ecdsa** [comment]
closing, not enough details here
