### ISSUE TITLE
Double click on history item to bring up details

### ISSUE THREAD

**Issue by ybop** [spesmilo/electrum#2611]
Very minor enhancement but very useful I think.  Currently viewing the details of a history item requires a right mouse click and select.  A double click on the item to do the same would be elegant, neat and helpful.

**Comment by ecdsa** [comment]
a double click allows the user to edit the label.

**Comment by ybop** [comment]
Yeah I was thinking more about a double click on the left most column (as opposed to the description).  This column indicates the status and it would be neat if a double click there brought up the details.
