### ISSUE TITLE
Some commands are not working with php

### ISSUE THREAD

**Issue by MaZyGer** [spesmilo/electrum#2612]
Hello I try to write a client with php. I am using one which already exists.

Some commands work and some not. For example "version" is working while "is_synchronized" not.
I get result "false" and as error: 

> string(185) "Server error:   File "C:\Users\Nickname\AppData\Local\Temp\_MEI137642\lib\commands.py", line 640, in is_synchronized | AttributeError: 'NoneType' object has no attribute 'is_up_to_date'"

If I do "version" result is: "2.8.3"

if I try getbalance: 
> string(178) "Server error:   File "C:\Users\Nickname\AppData\Local\Temp\_MEI137642\lib\commands.py", line 301, in getbalance | AttributeError: 'NoneType' object has no attribute 'get_balance'"

Note: I also tried this: https://github.com/spesmilo/electrum/blob/master/lib/www/example.php  I get same error there.

If I do getaddressbalance with parameter I get result, balance with confirmed and unconfirmed.

I am using this. Maybe this script have a bug or it is electrum?
https://github.com/Padrio/php-electrum-api/blob/master/src/Client.php

I also noticed, if commands has w for example **@command('w')** so they are not working. Do I miss something there?

**Comment by dabura667** [comment]
@command('w') means "this command requires there to be a wallet file specified. if none is specified there must be a wallet file in ~/.electrum/wallets/default_wallet"

Do you have a wallet file called ~/.electrum/wallets/default_wallet ?

If not, you need to pass the wallet file path as an argument.

**Comment by MaZyGer** [comment]
I do but I use testnet. Does it make any differents? I also tested it without testnet.  I do not use the default_wallet. I use renamed wallet. 

I thought it is using the same "wallet" like my electrum client has currently opened.

**Comment by dabura667** [comment]
so you started electrum daemon by running:

```
$ electrum daemon start
$ electrum daemon load_wallet
```

right?

**Comment by dabura667** [comment]
Yeah, I just tried the same commands you did WITHOUT using `electrum daemon load_wallet` first and got the same results as you.

You have to load your wallet before you can use it in daemon mode.

**Comment by MaZyGer** [comment]
No I am on windows and I used 

> electrum-2.8.3 --testnet

**Comment by dabura667** [comment]
ok... run the following in cmd window

```
electrum-2.8.3 --testnet daemon start
electrum-2.8.3 --testnet daemon load_wallet
```

Then try.

**Comment by MaZyGer** [comment]
Thanks now its starts in background but I cannot connect anymore. I guess I do need to type password. What is parameter for wallet password?

**Comment by dabura667** [comment]
nope.

Anyone can run commands against it. But if your wallet is password protected they can not get any info from your wallet without the password.

**Comment by dabura667** [comment]
also, the password parameter name is "password"

**Comment by ecdsa** [comment]
no real issue here I guess
