### ISSUE TITLE
No data for fiat value

### ISSUE THREAD

**Issue by sebthauvette** [spesmilo/electrum#2618]
Fiat values from BitcoinAverage don't seem to work. Since it's the only source for CAD, it's impossible to get fiat values in CAD. I aslo tried with USD and only Winkdex is working. 

I suggest adding cbix.ca for CAD values.

**Comment by bauerj** [comment]
BitcoinAverage changed their API. You need to either wait for an update or change the provider.

See #2585, #2535, #2499, #2498, #2525.

Also: https://www.reddit.com/r/Electrum/comments/6hqa6u/help_no_fx_rate_available/

**Comment by sebthauvette** [comment]
Thanks for the answer, I should have tried harder when I search if there was already an existing ticket for that.

I think adding at least an other source ( like cbix.ca ) is worth it though, but I guess it's a whishlist at this point.

**Comment by bauerj** [comment]
There are already plenty of other sources for BTC/CAD if you disable historic rates. I'm not sure if cbix.ca provides that?

**Comment by sebthauvette** [comment]
From their doc, they do support it up to 2011-09-01  . 
https://www.cbix.ca/api#history

**Comment by djmaze** [comment]
AFAICS, this was fixed in #2498 and was released in version 2.9.0.
