### ISSUE TITLE
is_synchronized return false for large wallets

### ISSUE THREAD

**Issue by bsbits** [spesmilo/electrum#2619]
Hello, 

I have a wallet with 100K addresses.

I use electrum on linux via command line, I start the deamon and load the wallet.

whenever I check that specific wallet, it says the wallet is not synchronized.

**Comment by ecdsa** [comment]
that's normal. Electrum servers have anti DOS protection, they will not let you request 100K addresses.

**Comment by bsbits** [comment]
What is the solution for my case then ? 

What is the max amount of addresses electrum servers support ?

**Comment by bauerj** [comment]
That depends on the server.

**Comment by ecdsa** [comment]
what is the use case? how did you create the wallet?
the solutions are either to run your own private electrum server, or to create a smaller wallet.
you could also bribe a server operator so that they whitelist you.

**Comment by bsbits** [comment]
The use case is using electrum wallet to process (receive / sign / broadcast) lots of transactions.

creating smaller wallets will be a pain to manage, I would end up with hundred of wallets and operate them simultaneously will take all my time.

I will attempt running my own electrumx and update you, can you paste a link to the config where I can allow unlimited requests ?

**Comment by ecdsa** [comment]
you should ask in the electrumx project for the config

**Comment by dabura667** [comment]
self.max_send = self.integer('MAX_SEND', 1000000)
        self.max_subs = self.integer('MAX_SUBS', 250000)
        self.max_session_subs = self.integer('MAX_SESSION_SUBS', 50000)
        self.bandwidth_limit = self.integer('BANDWIDTH_LIMIT', 2000000)

These are the environment variables pertaining to anti-DOS for electrumX and their defaults.

You can install and then set up the service with much higher limits.
