### ISSUE TITLE
Corrupted Seed Wallet? v 2.8.3

### ISSUE THREAD

**Issue by bnm008** [spesmilo/electrum#2623]
Hi,
I'm experiencing a weird issue and was told it might be an actual bug after a few hours of having some more experienced people try and help me troubleshoot in IRC. Here's the timeline:

1. Install Windows client on Windows 10. Everything is fine. Wallet connects without a hitch
2. Purchase 3.5 BTC from a friend.
3. He transfers the funds to my fresh receiving ID
4. Funds Confirm: https://blockchain.info/address/39iWj5WFyRKjiYsXNByCy3CyVuCwGmntqk
5. Client becomes stuck in Sync
6. Get Frustrated, download portable app
7. Experience Same Sync lock situation
8. Try removing all Electrum files and reinstalling several times
9. Try creating about a dozen new wallets of various combinations to see if I can get one to connect.
10. Go into IRC, some experienced people help me troubleshoot (basically doing the same stuff I was stumbling through in steps 8 and 9
11. Install fresh Ubuntu and stumble my way through a python/electrum installation
12. Hop back into IRC, someone suggests I run electrum -v
13. Terminal spits out the following: https://pastebin.com/rRV7aFX0

Is this a legitimate bug? If not, what can I do to synch up my wallet and gain control of my funds?

edit: those ubuntu error logs are from after generating a *fresh* wallet on ubuntu, I didn't try to use the bad wallet on the linux install.

**Comment by cluelessperson** [comment]
Here's a copy of the weird bad wallet,  it syncs forever on my windows machine.
Works FINE on my linux machine.

[https://cluelessperson.com/share/public/electrum/troubleshooting/weird_bad_wallet](Weird Bad Wallet)

**Comment by bnm008** [comment]
Yeah, any new wallet I make on windows gets stuck in synch lock. Thanks for the help by the way. I gave clueless full control of my funds and he safely transferred them back. Very upstanding guy.

**Comment by bauerj** [comment]
This is the same issue as #2576. The next version will include a fix.

I assume "clueless's linux machine" uses a development version that contains the fix (615a5b3f8e8853dafc62cd6b26c3b6d51768b606)?

**Comment by ecdsa** [comment]
yes, cluelesperson recently installed the development version
