### ISSUE TITLE
Feature Request: Electrum needs a more fool-proof backup method

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#2627]
Electrum's "generation seed" (which is basically a brain wallet) is not conducive to use by non-technical users. If users follow instructions, unless they're security-savvy, they're basically forced to write it down on paper in plain text. This is simply not secure in any sense of the word. Any traditional thief breaking in to your home could steal your bitcoins. Not only that, but users not following all the instructions may simply store their wallet words in a file on their computer somewhere (in plain text as its given). Backups MUST be encrypted, or they're not secure, regardless of whether they're stored on disk or on paper. Advocating in the application that people store their password unencrypted is bad for Electrum users and bad for Bitcoin. 

There are two options Electrum should provide:
* Encrypted file backup. This could be as simple as an aes-256 encrypted file containing the generation seed, encrypted with a password the user puts in. Its probably best that this file be a well known standard. 
* Encrypted paper wallet. Basically the same as the above, except where the information is stored as a QR code that can be printed out on a piece of paper. 

I'm going to repeat this, since this mistake seems to be pervasive in Bitcoin wallets for some reason:

UNENCRYPTED WALLET WORDS ARE NOT SECURE

Please fix this guys. The state of secure backups in the options for Bitcoin wallets is simply embarrassing.

**Comment by dabura667** [comment]
NACK

I completely disagree.

**Comment by SomberNight** [comment]
> Encrypted file backup. This could be as simple as an aes-256 encrypted file containing the generation seed, encrypted with a password the user puts in. Its probably best that this file be a well known standard.

The wallet file can be encrypted and while it stores a whole bunch of other things besides xprv/seed, and while it certainly is not in a standard format, people can just backup that if they want.


In any case, I think giving out unencrypted seed words, **as done currently, is ideal**. If the seed was encrypted, that would just propagate the "unencrypted secret" problem further down the line: how would people backup that password? People are prone to forgetting passwords.

Anyone is free to employ whatever extra security practices she wishes and feels competent to employ.

Also note that relatively larger funds are best stored in multisig wallets where cosigners' backups are stored separately. The problem you mentioned is a lot less serious there.

**Comment by fresheneesz** [comment]
@SomberNight 

"The wallet file can be encrypted"

Ok, so maybe the user should be told that this is an option. Casual users aren't going to know this is an option unless they're told. Also, I think (hope?) the wallet file is *always* encrypted, right?

"how would people backup that password?"

I would imagine people would be much less prone to losing a password they use all the time to make payments. Usually passwords don't need to be "backed up", since you can remember them. But sure, there can be an option for people who think they're prone to forgetting such an important password I guess. But I don't think this is the usual case.

"Anyone is free to employ whatever extra security practices.."

Yeah, anyone with the know-how and industriousness. I'm specifically talking about the casual user and the lazy user. For me, I know how to encrypt text, and I know how to remember a strong password. This feature request isn't for me. Its for the 99.99% of the world who couldn't be bothered to learn about how to properly backup their bitcoins. I think we (the Bitcoin community) needs to start working on making things like backup as dead-simple and fool-proof as possible, in preparation for the day when Bitcoin is truly mainstream.

"larger funds are best stored in multisig wallets where cosigners' backups are stored separately"

Sure, but this is kind of a more advanced move that the casual user isn't even going to give a second thought to. Its kind of not an option for the casual user. 

@dabura667 You're comment isn't helpful unless you give reasons that you disagree.

**Comment by bauerj** [comment]
> Ok, so maybe the user should be told that this is an option.

That's part of the initialization wizard. Electrum will ask for a password to encrypt the wallet when you create a new wallet.

> Also, I think (hope?) the wallet file is always encrypted, right?

No, users can choose not to encrypt it.

> I would imagine people would be much less prone to losing a password they use all the time to make payments. 

But what about people who want to invest in Bitcoin and not "make payments" "all the time"?

> Usually passwords don't need to be "backed up", since you can remember them.

That's not true. People forget passwords all the time.

----

I also the think that when storing the seed on paper the danger is far less imminent than you think. It would be quite surprising to see thieves breaking into homes to specifically look for Electrum seeds.

**Comment by ecdsa** [comment]
NACK. A paper backup that cannot be decrypted without a computer is dangerous for most users. 
it just shifts the problem.

**Comment by fresheneesz** [comment]
@bauerj 

> Electrum will ask for a password to encrypt the wallet when you create a new wallet.

That's not what I'm talking about. I'm talking about telling the user how to back up their encrypted wallet. 

> No, users can choose not to encrypt it.

Well that's absolutely terrible. Why would anyone want to store an unencrypted electrum wallet file? Why does this option exist? You're just asking for hackers to steal your bitcoins if you leave unencrypted wallets on your network-connected computer. Electrum doesn't even warn you that leaving your wallet unencrypted puts you at major risk of theft! 

> But what about people who want to invest in Bitcoin and not "make payments" "all the time"?

If they don't make payments all the time, and don't have an offline password they use all the time. Then they can write down their password. This is such a razor thin edge case. I'm not sure why you think its appropriate to optimize a bitcoin wallet application for those 1.2 people in the world this applies to. 

> It would be quite surprising to see thieves breaking into homes to specifically look for Electrum seeds.

A thief doesn't look for one specific thing when they break in. They'd break in and steal anything they can carry that they think might have significant value. In a world where Bitcoin is the primary currency, any piece of paper with jibberish words on it is going to be the first thing a thief pockets. They'd then go home and try that code on every wallet that uses wallet words until they find those bitcoins and spend them. This should not be surprising to you.

@ecdsa 

> A paper backup that cannot be decrypted without a computer is too dangerous for most users.
it just shifts the problem.

What? That makes 0 sense. Any Bitcoin wallet needs a computer to be used. Removing a computer as a requirement is not an option. I have to assume I'm misunderstanding you. Could you please clarify what you mean?

**Comment by pierre-pretorius** [comment]
Not being able to backup to an encrypted QR code is why I'm sticking to a greenaddress wallet.  Restoring a bitcoin wallet by scanning a QR code and then entering a password is the easiest and safest way I could find when it comes to leaving crypto behind for loved ones.

**Comment by fresheneesz** [comment]
@ecdsa Can you please respond to my previous comment? You closed this without discussing, I don't think that's very cool.
