### ISSUE TITLE
Segfault by 2.8.0 and higher running on Tails 3.0.1 when reading QR code

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#2637]
I downloaded the source bundle, and ran by executing the `electrum` script. Clicked on Send tab, then on QR code icon. Segfault without any other output.

I'm using Tails 3.0.1 on a MacBook Pro. Attempted to set camera preferences from the Electrum Preferences window, but segfault still happens. See https://github.com/spesmilo/electrum/issues/1059

2.7.18 runs flawlessly on the same setup.

**Comment by rapodaca** [comment]
FWIW, I've traced the segfault to this line:

https://github.com/spesmilo/electrum/blob/2.8.0/lib/qrscanner.py#L48

However, commenting this line out also triggers a segfault, which is caused by execution of the next line.

**Comment by ecdsa** [comment]
please check existing issues before posting duplicates..

**Comment by rapodaca** [comment]
Somehow missed duplicate of #2527. Will follow up there.
