### ISSUE TITLE
Lost seed and 2fa

### ISSUE THREAD

**Issue by eugcamp93** [spesmilo/electrum#2640]
Hello,

I recently created a wallet in which I deposited an amount in btc. After that, they stole my iphone with seed and 2fa generator in it. Is there a way to recover the amount? I can access private keys and master public key of the wallet

**Comment by bauerj** [comment]
If you still have private keys from that wallet, you can sweep them into a new wallet.

**Comment by eugcamp93** [comment]
Yes, I tried it but the answer was "No inputs found (note that inputs need to be confirmed)

**Comment by ecdsa** [comment]
there is a method to recover the master private key (xprv) from the master public key (xpub) and a single private key. you should try to find out about it.
see https://bitcoinmagazine.com/articles/deterministic-wallets-advantages-flaw-1385450276/

**Comment by ecdsa** [comment]
that's out of scope for Electrum, though; closing this issue
