### ISSUE TITLE
The transaction was rejected by network rules.(64: dust)

### ISSUE THREAD

**Issue by bsbits** [spesmilo/electrum#2642]
So electrum sent a dust amount to a change address and now I can not send btc anymore.

Whenever I try to send btc, I get this error
`
The transaction was rejected by network rules.(64: dust)`

I am using electrum via command line and RPC, is there anyway to solve  this ?

**Comment by yangwao** [comment]
@bsbits how did you solve it?

**Comment by ecdsa** [comment]
@yangwao are you sure you have the same issue? what is the transaction you are trying to create?

**Comment by yangwao** [comment]
@ecdsa solved, here https://github.com/spesmilo/electrum/issues/2710
