### ISSUE TITLE
Electrum closes/crashes after entering password for wallet

### ISSUE THREAD

**Issue by davecrosslmt** [spesmilo/electrum#2643]
I have a pretty serious problem.  After using Electrum for about a month successfully without any issues, I now can't get my wallet to open.  Electrum loads up, I select the wallet, and enter the correct password (also tried entering the incorrect password to see what would happen and it just prompted me that I had entered the incorrect password), and when I click next, the program crashes.  When I hover over the icon in the taskbar background apps area, it just disappears.  I'm a bit worried now because I have a lot invested in this wallet and selected Electrum as the best option for security sake because of the "forgiving" nature of the program, thinking I would be able to recover my funds no matter what should happen, and now this happens. 

I found a post to delete all the data files except the wallet files, which from what I understand was all the files and folders one level up from the Wallet directory, and when I did that it simply prompted me to select a server (or to auto-select `it) as it did on first startup.  Ive also tried uninstalling the program and reinstalling it, no help.  I even tried transferring the wallet over to another PC and using Electrum 2.9.0 on another PC to open that wallet, and it does the same exact thing, which is leading me to think there is something with the wallet file that I cannot figure out, though it makes no sense because nothing has been done to it except for starting it up in the Electrum program.
``
Could someone please assist me?

Thank you.

**Comment by fyookball** [comment]
Don't delete anything.  Copy the wallet file safely over to another working folder and try running an earlier version like 2.8.2 with that wallet file.   Also no matter what happens if you have your mnemonic seed phrase you are safe.

**Comment by davecrosslmt** [comment]
Actually I was originally running 2.8.2 when this problem arose.  I only upgraded to 2.9.0 when I thought it might help the program start.  Still, the same problem happening.

**Comment by fyookball** [comment]
do you have your seed?

**Comment by davecrosslmt** [comment]
Yes I do

**Comment by fyookball** [comment]
i would go back even farther than 2.8.2 there's been a lot of "interesting" code lately.  Try 2.5.2

**Comment by davecrosslmt** [comment]
Loading it now.  Should I just try to load the same wallet with that version?  Or do I need to use the Wallet Seed at some point in this restoration?

**Comment by fyookball** [comment]
try the wallet file as itll have all your history

**Comment by davecrosslmt** [comment]
Hmmm it says it cannot load the wallet file.

**Comment by davecrosslmt** [comment]
I tried 2.8.0, no luck, but it can actually load the program to the same screen that 2.8.2 and 2.9.0 got me to, before crashing after entering the password.  But 2.5.2 won't even load to the password screen, saying that it can't load the wallet file.

**Comment by davecrosslmt** [comment]
I went back to 2.7.18, and was able to just use my seed to create a new wallet.  Got everything back up and running.  Thanks.

**Comment by AbdussamadA** [comment]
you could just have restored from seed using the latest version. just make sure there are no wallet files where electrum expects to find one (the wallet directory you already talked about) and it'll display the new wallet creation wizard. Then you just select standard wallet > i already have a seed and the rest is self-explanatory.

The old versions have bugs in them so you should use the latest. The wallet file format changed in 2.7.0 so trying to use 2.5.2 with your wallet file like @fyookball advised was never going to work.

**Comment by SomberNight** [comment]
@davecrosslmt It would be nice to know if restoring from seed works for you on the newer versions (e.g. 2.9.0). If it doesn't, that would point towards interesting bugs.

**Comment by ecdsa** [comment]
can you check if it is the same issue as #2676 ?
