### ISSUE TITLE
Portable version broken

### ISSUE THREAD

**Issue by yura-pakhuchiy** [spesmilo/electrum#2647]
Electrum 2.9.0 in portable mode can not connect to network.

**Comment by yura-pakhuchiy** [comment]
Hm, after stalling for few minutes it managed somehow to connect. Some user visible indication should be added to allow user understand that it is doing something and not broken.

**Comment by ecdsa** [comment]
yes, it was downloading the headers file.

**Comment by ecdsa** [comment]
fixed in 2.9.2

**Comment by yura-pakhuchiy** [comment]
@ecdsa works much better in 2.9.2, but still there is 15-20s delay while it says disconnected, instead of syncing.
