### ISSUE TITLE
2.9.0 status is not responding application.

### ISSUE THREAD

**Issue by devidSH** [spesmilo/electrum#2648]
Runs very long, I get the status of the application all the time (the application does not respond)(Windows 10, electrum portable 2.9.0) It's impossible to use the program now

**Comment by devidSH** [comment]
All changes you settings are not saved, after a time the standard becomes again.

**Comment by HardCorePawn** [comment]
Are you running it from a location that either has no write permissions or not enough disk space?

Portable needs to create an electrum_data folder and store around 35-36megs of blockheader, config files and other data... in addition to any wallet files you generate.

I'm able to run 2.9.0 Portable OK on Windows 10 from both a local harddrive and a USB drive.

**Comment by bauerj** [comment]
I assume this is not relevant to current Electrum any more. Please reopen if this issue still persists.
