### ISSUE TITLE
RECOVERY FAILURE, Hard Drive wiped, have seed and wallet address, no keys

### ISSUE THREAD

**Issue by kitclif** [spesmilo/electrum#2651]
The title pretty much explains it. I tried to recover my wallet with BTC but my account shows as 0 BTC. My wallet address with the BTC isn't in my receiving addresses. I have re-downloaded electrum multiple times. No clue where to go from here. Here is my public key; My assumption is that it is different from my old pub key but I have no way to know. I entered my seed correctly when creating new wallet. 

xpub661MyMwAqRbcGvYRWxxeVGm4wEMNUiVzA8bmhShCHPam4CaoLcRRzcBBbcSRiygFq8ZW2wtkpWwqRnNkRsPrAPwsX4P5zcvsHEnyE4o1RQj

![qrcode](https://user-images.githubusercontent.com/30550022/28744595-0f55474c-7419-11e7-80d8-f9a868812e92.png)

**Comment by dabura667** [comment]
If the wallet shows 0 BTC it is the wrong wallet.

Try checking spelling or word order, also check to make sure you don't have other seeds written down.

**Comment by kitclif** [comment]
Wow this is going to sound stupid but that literally never crossed my mind. Took me a lot of searching but Its all there. Thank you!
