### ISSUE TITLE
Is it possible to send money from specific address?

### ISSUE THREAD

**Issue by n0n0n0n0** [spesmilo/electrum#2652]
For example for every income i generate new address with MPK feature, how can i send money from this addresses? Is here any user-friendly commands in CLI?
Using debian 8.

**Comment by dabura667** [comment]
Yes, payto and paytomany have an optional named argument called from_addr

This will only consider coins that are on that address when sending. (If you try to send more that it has it will not look at other addresses and raise an insufficient balance Error)

**Comment by n0n0n0n0** [comment]
Great, also question about perfomance. How many addresses generated with MPK electrum can handle? If i create about 100k accounts will it works properly?

**Comment by dabura667** [comment]
If you need to use 100k addresses, public servers will give you errors.

Please run your own server, point your client to only use your server, and set the limits of your server high enough to handle your needs.

**Comment by dabura667** [comment]
I recommend installing this:

https://github.com/kyuupichan/electrumx
