### ISSUE TITLE
Problem with payto

### ISSUE THREAD

**Issue by n0n0n0n0** [spesmilo/electrum#2653]
Using CLI to send money like this:

`curl --data-binary '{"id":"curltext","method":"payto","params":{"destination":"DEST_ADDR", "amount":0.5,"from_addr":"FROM_ADDR"}}' http://127.0.0.1:7777`

Then sign and broadcast transaction, but in transaction i can see that remaining funds (about 0.6 btc, there was 1.1 btc) **moved to another address in wallet**, how to keep them in from_addr and **NOT** to move to another addr? 
Didnt use "change_addr" option and etc as above.

**Comment by ecdsa** [comment]
electrum uses change addresses by default.
please read the documentation, or ask questions in the forums
github issues are for bugs.

**Comment by dabura667** [comment]
set change_addr to the same address as from_addr.

The default for change_addr (if you don't pass it) is to generate a new change address.
