### ISSUE TITLE
ELECTRUM WONT CONNECT

### ISSUE THREAD

**Issue by RANIx807** [spesmilo/electrum#2655]
Someone please help, my electrum wallet will not connect.

I am on Windows, and have the 2.9 version of the wallet.
I have already uninstalled and reinstalled it, allowed it through windows firewall, attempted to manually choose each server on SOCKS5 & 4, I did check USE SSL & even unchecked it. 

What can I do? Have I completely lost my currency?? 
Please help

**Comment by ecdsa** [comment]
does it still not connect?

**Comment by RANIx807** [comment]
No the issue has been fixed thank you so much for your response 😊
