### ISSUE TITLE
electrum does not create wallet file in some pathes

### ISSUE THREAD

**Issue by klkvsk** [spesmilo/electrum#2660]
On windows, if you choose to enter absolute path for a new wallet file, in some cases the file would not be created without any error given. Electrum would start up with in-memory copy of wallet data and work fine until it's closed, so most users will only notice file missing on the next run.

I have found two cases:
1) when one of folders in path start with a dot (tried `C:\foo\.bar\default_wallet`)
2) when there is cyrillic symbols in path (tried `C:\foo\хуй\default_wallet`)

Tests done on Windows 10 64-bit build 1607

**Comment by AbdussamadA** [comment]
what version of electrum are you using? this sounds like an old bug to me

**Comment by klkvsk** [comment]
I use 2.9.0 -- latest stable release.

**Comment by emoticon** [comment]
> хуй

**Comment by ecdsa** [comment]
this is fixed in master, wait for release 3.0
