### ISSUE TITLE
Sending to multisig address, from Ledger Nano S, by using spend from a single address

### ISSUE THREAD

**Issue by HostFat** [spesmilo/electrum#2662]
I get this error on Electrum 2.9

http://imgur.com/a/23Lp1

I tried to use back Electrum 2.8.3, and it works without any issue.

**Comment by charleshsu168** [comment]
I've got a very similar error.
I am using Electron Cash 2.9 which is a fork of Electrum 2.9.
So they might be related.
Sending to a bitcoin cash( bcc ) address result in the same error.
http://imgur.com/a/KR8cV
please fix it soon!!!

**Comment by ecdsa** [comment]
closing, OP was connected to a BCC server.
