### ISSUE TITLE
my btc has gone from my electrum wallet

### ISSUE THREAD

**Issue by hzolka** [spesmilo/electrum#2664]
hallo, 
what was happened? balance is 219,591 mBTC and the max amount can be sent is 2,36278???
pictures attached.
pls help, thx.

![hzolka_error1](https://user-images.githubusercontent.com/30606564/28798944-a0274016-7646-11e7-8304-6f528f8ab363.JPG)
![hzolka_error2](https://user-images.githubusercontent.com/30606564/28798965-c4740972-7646-11e7-9dbb-cecc7a57546f.JPG)
![hzolka_error3](https://user-images.githubusercontent.com/30606564/28799010-019748a0-7647-11e7-999b-d1e84516d1a8.JPG)

**Comment by ecdsa** [comment]
there is a new preference to send unconfirmed coins.
it is disabled by default.

**Comment by hzolka** [comment]
Hi Thomas,

Now it seems OK now, error is fixed, panic was unnecessary as i see. Mining
is going ahead as normally.
Sorry for disturbing...

Zoltan

ThomasV <notifications@github.com> (időpont: 2017. aug. 1., K, 0:17) ezt
írta:
