### ISSUE TITLE
Password of my Wallet

### ISSUE THREAD

**Issue by maaadisss** [spesmilo/electrum#2665]
Hello, i never set a Passwort on my electrum wallet but now i cant send anythin of my coins becous i dont now the passowrd. is there a way to get my coins back ? greets

**Comment by ecdsa** [comment]
it is likely that someone else created the wallet you used to receive coins, or that you created it a long time ago and forgot about it. check if you have saved the seed on paper.

**Comment by maaadisss** [comment]
i createt it 4 months ago but then i deletet the Password did u mean the seed like giant Ketchup etc.. becous i have this but this is not my passowrd

**Comment by maaadisss** [comment]
i dont deleted the passoword i deletet electum and 5 days ago i reinstall it becous my i want to use electum and not copay anymore

**Comment by ecdsa** [comment]
ok, if you need help about what is your seed/password, please read the docs and use the forums.
this site is for bug tracking, not for asking newbie questions.

**Comment by maaadisss** [comment]
hello u closed my thread on github...
but i already have the seed but this is not my password, i dont know what u mean..
can u help me please?

Sent with [ProtonMail](https://protonmail.com) Secure Email.
