### ISSUE TITLE
Custom derivation path [Electrum 2.9.0]

### ISSUE THREAD

**Issue by the9ull** [spesmilo/electrum#2668]
I found inconsistencies when I change the derivation path of imported BIP39 wallets. I'm trying to import a bread wallet seed.

I used the tool iancoleman.github.io/bip39 as comparison. My wallet derivation path is `m/0'` and address `m/0'/0/0` is 1kryhqTv9dm1AkxxYuLpt5K2aePbyZw3V (Bread and iancoleman's tool compute this address).

I cannot compute this address in an Electrum BIP39 wallet, I got 17d1z8iLpRyoKHYAJ6ArSd2a2WmFMpFdPF as first address. I specified `m\0'` as derivation path.

The seed is `secret leave wing absorb cheese winner raise wide nothing celery hundle paper`

**Comment by ecdsa** [comment]
this is not a valid bip39 mnemonic

**Comment by the9ull** [comment]
Fixed, I wrote one wrong letter here in the post, but the issue is valid

**Comment by ecdsa** [comment]
no, issue is not valid because you entered the invalid seed in electrum; it does not check.
