### ISSUE TITLE
i can not send coins

### ISSUE THREAD

**Issue by stanch3vv** [spesmilo/electrum#2671]
i cna not send a coins to adress.....i recive a message  ,,the transaction was rejected by the network rules,, please help....thsi si a big absurd

**Comment by EagleTM** [comment]
I'm just guessing here, but please also give more info. Which version are you using... please update if you're not on a recent version. How much BTC are you trying to send...

**Comment by stanch3vv** [comment]
i use version 2.6.4...it should workds

**Comment by EagleTM** [comment]
yea it should, but you will only get support if you're on a more recent version. Please pick another server and try again and please provide more info

**Comment by ecdsa** [comment]
do not open a ticket here before you have upgraded to the latest version
