### ISSUE TITLE
Coins stolen

### ISSUE THREAD

**Issue by rafal954** [spesmilo/electrum#2672]
Hello, my coins probably were stolen. Can you verify an IP address of the hacker to be able to call the police? Can I send you an email with the transactions?

**Comment by AbdussamadA** [comment]
You alone are responsible for your bitcoins. There is no one in charge you can turn to for justice. Also this is not a support forum. This place is for bug reports and development related matters. You should post in the forum:

https://bitcointalk.org/index.php?board=98.0

If you do post in the forum provide more details. Perhaps your coins have not been stolen and you've simply misunderstood what's happening. But ultimately it is a decentralized system and you alone are responsible for your bitcoins. It is not a bank.
