### ISSUE TITLE
electron cash wallet 2.9 having error 16 Signature must be zero for failed CHECK(MULTI)SIG operation)

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#2673]
I am using Electron Cash 2.9 which is a fork of Electrum 2.9.
I though I might ask as they might be related and it seems some people are having this issue as well, not just me, with Electrum 2.9:
https://www.reddit.com/r/Electrum/comments/6q4d2a/is_anyone_else_getting_error_16_network_rules/

Sending to a regular bitcoin cash address, not a multisig address, from my 2FA wallet result in the error .
"error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))"
see http://imgur.com/a/KR8cV
please fix it soon!!!

**Comment by ecdsa** [comment]
you cannot use 2FA with electron cash.
restore the wallet from seed, and disable 2FA.

**Comment by charleshsu168** [comment]
I did as you suggested. 
Restored the wallet from seed.
i disabled 2fa.
wallet got restored with correct balance. 
however, i still have the same issue trying to spend from the wallet.
same error message came up.
this is for electron cash wallet 2.9.
