### ISSUE TITLE
electron cash wallet can't spend again error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#2674]
I am using Electron Cash 2.9 which is a fork of Electrum 2.9.
I though I might ask as they might be related and it seems some people are having this issue as well, not just me, with Electrum 2.9:
https://www.reddit.com/r/Electrum/comments/6q4d2a/is_anyone_else_getting_error_16_network_rules/

Sending to a regular bitcoin cash address, not a multisig address, from my 2FA wallet result in the error .
"error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))"
see http://imgur.com/a/KR8cV
please fix it soon!!!

**Comment by charleshsu168** [comment]
the issue is still open. i tried the suggestion of restoring seed and disabling 2fa.
same problem.
can't spend as shown http://imgur.com/a/KR8cV
maybe earlier version works. but this is definitely not working in electron cash wallet 2.9.

**Comment by AbdussamadA** [comment]
you're seeing this error in electron cash because the cosigner trusted coin does not support bitcoin cash transactions.

**Comment by charleshsu168** [comment]
i disabled 2fa. so that should be work. i no longer need trusted coin as cosigner.

**Comment by ecdsa** [comment]
if the issue persists then it is probably a bug in Electron Cash.
why don't you open an issue with them?

**Comment by ecdsa** [comment]
oh I guess it is because your Electron Cash client is connected to a Bitcoin server.
see https://twitter.com/ElectrumWallet/status/892433256385261568

**Comment by charleshsu168** [comment]
my Electron cash client is connected to the right server. i manually corrected it to  a bcc server.

**Comment by ecdsa** [comment]
yes you can report an issue there

**Comment by ecdsa** [comment]
but I think you should try again with the bcc server. 
you probably made a mistake

**Comment by ecdsa** [comment]
closing; 
it looks like same user opened an issue with electron cash, under a new name

**Comment by HostFat** [comment]
It isn't an issue of Electron Cash, it is this same issue #2662

**Comment by ecdsa** [comment]
@HostFat can you provide more details? why does 2FA still work with BTC?

**Comment by HostFat** [comment]
I was using Ledger Nano S, it isn't related to 2FA, the problem seems related to sending to a multisig address.

**Comment by ecdsa** [comment]
no, the recipient address has nothing to do with that.

**Comment by HostFat** [comment]
Well, I'm not sure about this, but I always used "Electrum" while I did get this issue, so I was connected to a Bitcoin Cash server, maybe...

**Comment by sollar1** [comment]
I had the same problem and the solution is to choose another server manually.
try the server electroncash.cascharia.com

**Comment by lxcosmo** [comment]
>sollar1:  I had the same problem and the solution is to choose another server manually.
try the server electroncash.cascharia.com

It work!!!

**Comment by ZittoTx** [comment]
Ye, but on electroniccash.cascharia.com does not have any confirmations

**Comment by aabulkhairov** [comment]
Tried electroniccash.cascharia.com, it worked, BCC was sent, but wan't received on the received wallet. Fuuuuu :)

**Comment by quintela78** [comment]
sorted out?
