### ISSUE TITLE
Ledger Nano S Electrum 2.9.0 binary The transaction was rejected by network rules

### ISSUE THREAD

**Issue by joelinzy** [spesmilo/electrum#2678]
electrum binary: https://download.electrum.org/2.9.0/electrum-2.9.0.dmg
OS: macOS Sierra
Ledger Nano S: secure element 1.3.1, MCU: 1.0
action: send to non-multi signature address (1...)
error: The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))
server: electrum.hsmiths.com

**Comment by ecdsa** [comment]
please post the transaction.
in the absence of more information, I believe it is likely you were connected to a BCC server
