### ISSUE TITLE
Cannot encrypt Wallet file

### ISSUE THREAD

**Issue by LoveElectrum** [spesmilo/electrum#2680]
I use Linux Debian Stretch and Electrum 2.9.1. When I try to encrypt only seed and private keys everything is ok... but when I try to choose Encrypt Wallet file, Electrum stops responding! When I start Electrum again, it starts without any password. And again I have only my seed and private keys encrypted.

The terminal shows only this

> "sni-qt/10318" WARN  14:12:21.422 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
> 
> ** (python:10318): WARNING **: Invalid borders specified for theme pixmap:
>         /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png,
> borders don't fit within the image
> 
> ** (python:10318): WARNING **: invalid source position for vertical gradient
> 
> ** (python:10318): WARNING **: invalid source position for vertical gradient
> 
> ** (python:10318): WARNING **: invalid source position for vertical gradient
> 
> ** (python:10318): WARNING **: invalid source position for vertical gradient

After that Electrum stops responding! And I have to kill Electrum process! That's all!

**Comment by ecdsa** [comment]
try to install pycryptodomex

**Comment by LoveElectrum** [comment]
Thank you! It helped, And now everything is ok!
