### ISSUE TITLE
Ubuntu electrum wallet showing Not verified payment

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#2681]
i compiled the latest development version of electrum in Ubuntu 14 using: git clone git://github.com/spesmilo/electrum.git

the history in the electrum wallet is showing all payment history as NOT verified.
![image](https://user-images.githubusercontent.com/5799190/28912624-d6d25f7a-77e9-11e7-9217-1e31ac121de1.png)

furthermore, the Network is empty. no severs listed. blockchain height is 1.
I tried connecting to many different servers. still get the same result.
![image](https://user-images.githubusercontent.com/5799190/28912779-807cb49e-77ea-11e7-8694-c0f2271672b3.png)

**Comment by EagleTM** [comment]
Please update to 2.9.1
Header downloads are impaired with 2.9.0 as it fetches from https but then re-gets them from servers.
Just let it run, it should eventually work. ALso change to the "Server" tab to select a server to connect to.

**Comment by charleshsu168** [comment]
i did upgrade to 2.9.1 just now..still the same
![image](https://user-images.githubusercontent.com/5799190/28913203-0e01329e-77ec-11e7-95fa-9ace224454ae.png)

**Comment by charleshsu168** [comment]
i disabled "select server automatically" and got the list of available servers
![image](https://user-images.githubusercontent.com/5799190/28913465-ffbf6ab0-77ec-11e7-91dc-a92749da44ab.png)

**Comment by ecdsa** [comment]
yes there was a bug with initial headers download.
it is fixed now.
you'll have to wait until it has downloaded the headers.

**Comment by charleshsu168** [comment]
no...downloading headers is taking forever...not sure if it eve works..it's been more than 30 minutes

**Comment by ecdsa** [comment]
if you want a faster download, install 2.9.1 and remove your current headers file

**Comment by charleshsu168** [comment]
i am using 2.9.1. where  is the current header file?

**Comment by ecdsa** [comment]
"blockchain_headers" in your electrum directory

**Comment by charleshsu168** [comment]
yes..that works now.
after  I removed the headers, it got sync right away.
but this should not have been an issue. isn't there a way to remove headers automatically by the wallet when it's taking a long time to download headers?

**Comment by ecdsa** [comment]
we're working on it

**Comment by charleshsu168** [comment]
ok. thank you for your help.

**Comment by charleshsu168** [comment]
this is the headefile that was created when it hangs 
![image](https://user-images.githubusercontent.com/5799190/28915365-be592866-77f3-11e7-8a17-187bcda5c2f0.png)
i removed it and it sync right away

**Comment by ecdsa** [comment]
thanks for the info.
the client is not robust to that, so it's a bug.
I'll do another release today, to fix it

**Comment by EagleTM** [comment]
@charleshsu168 : doesn't restart fix it? If I rm blockchain_headers, touch the file and put random garbage in it, then restart electrum it starts fetching chunks from servers.

**Comment by charleshsu168** [comment]
@EagleTM Nope. restarting doesn't help. it only works after removing the junk 404 file not found headers file.

**Comment by EagleTM** [comment]
OK seems the specific formatting that causes it. With the tests I did it worked, but those were not good tests...

**Comment by ecdsa** [comment]
fixed in 2.9.2
