### ISSUE TITLE
wrong values in send transactions on wallet imported from Breadwallet private keys

### ISSUE THREAD

**Issue by kanguru007** [spesmilo/electrum#2682]
I imported the private keys from my old Breadwallet to Electrum.
All the receiving transactions appeared correctly.
All the send transactions have wrong values, and the final balance is wrong.

**Comment by bauerj** [comment]
Can you be more specific? What exactly is wrong?

Can you share an address that shows a wrong balance in Electrum?

**Comment by ecdsa** [comment]
nothing wrong here
