### ISSUE TITLE
No way to run Electrum if the last encrypted wallet cannot be unlocked

### ISSUE THREAD

**Issue by birdie-github** [spesmilo/electrum#2686]
I'm sorry if this bug has already been fixed or if I don't understand how Electrum is meant to work.

In Electrum 2.8.3 if your last open wallet is encrypted, and you run the application, you see this dialog:

![wallet](https://user-images.githubusercontent.com/4958603/28950630-162acf92-78b5-11e7-8de5-c0c655460f74.png)

Obviously without entering the password you cannot click Next.

What this bug is about is that pressing "Back" (without entering a password) also doesn't work: you get an error: "Incorrect password" and you cannot return to the application. Kinda a bummer.

**Comment by ecdsa** [comment]
this bug has already been fixed
