### ISSUE TITLE
Preview/Send Button Not Responding

### ISSUE THREAD

**Issue by Torquemada99** [spesmilo/electrum#2689]
Hi All,

Hoping someone can offer some advice.  I have recently created a wallet using 2.9.0 on windows 10 and successfully sent bitcoins to the wallet.  However now when I am trying to send coins both the Preview and Send options do not respond.  Does not prompt me for my password, does not seem to do anything.

Thanks,
kevin

**Comment by ecdsa** [comment]
did you see a popup telling you that the wallet is "watching only" ?

**Comment by ecdsa** [comment]
please post a screenshot

**Comment by Torquemada99** [comment]
![capture](https://user-images.githubusercontent.com/30727556/28973071-10aacc14-792a-11e7-8bda-b4d9715aca4f.PNG)

**Comment by Torquemada99** [comment]
No, not that I am aware.  Created the wallet as a new seed.


________________________________

**Comment by ecdsa** [comment]
do you still have this problem with 2.9.3 ?

**Comment by zmbcgn** [comment]
i do. i just opened a new issue for this problem (https://github.com/spesmilo/electrum/issues/3084). maybe those two can be linked?

**Comment by SomberNight** [comment]
closing; https://github.com/spesmilo/electrum/issues/3084 contains more info, and also the buttons now give a response to the user since https://github.com/spesmilo/electrum/commit/d0352379d7f5c5aac2cfb63ec383603538860c93
