### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by tuxcanfly** [spesmilo/electrum#269]
Hi all,

I've tried setting up the deb builds of the electrum, slowaes, ecdsa on my personal ppa:

https://launchpad.net/~tuxcanfly/+archive/ppa

Sources for the builds are:

https://github.com/tuxcanfly/python-slowaes
https://github.com/tuxcanfly/python-ecdsa/tree/deb
https://github.com/tuxcanfly/electrum/tree/deb

_warning_: be careful when installing anything from untrusted ppas (including this one)

is there interest in having an official electrum PPA? If so, I can create a PR from the branch I'm working on.

Might be useful for signed releases as mentioned in #267 (only ubuntu though)

Thanks.

**Comment by orschiro** [comment]
Is the Debian repository compatible with Ubuntu? I would like to install the latest version 2.x on Ubuntu. Is someone still interested and capable of providing a PPA for it?

Thanks in advance!

Robert

**Comment by natrius** [comment]
So, should Electrum be available on Ubuntu 18.04 ? I can't install electrum via `sudo apt install electrum`. Maybe this should be opened again @ecdsa ? Or do i need to include the outdated ppa from tuxcanfly?
