### ISSUE TITLE
No module named matplotlib

### ISSUE THREAD

**Issue by dexX7** [spesmilo/electrum#2690]
Hi guys,

I'm using the standalone version electrum-2.9.2.exe for Windows, and when trying to plot the history via Wallet - History - Plot, the following error is shown:

```
No module named matplotlib
```

What can I do?

**Comment by ecdsa** [comment]
this is not available in the executables.
if you want plots, you need to run electrum from python sources

**Comment by LeaTex** [comment]
Same issue here with portable version.

Could you please show a user friendly error message? Or maybe remove the menu option if it's not available?
