### ISSUE TITLE
BIP39 seed with spanish words from Copay wallet incomplete restore in Electrum

### ISSUE THREAD

**Issue by LeaTex** [spesmilo/electrum#2691]
I have my wallet in Copay with my 12 words **in spanish**.
The words are correct and I can restore the wallet in other Copay installation.

When I put the BIP39 seed in Electrum it seems to be working, but the addresses with balance aren't there.

When I search for a transaction from _Tools -> Load Transaction_ it can be found, but shows "Transaction unrelated to your wallet".

I'm using Electrum portable version 2.9 (same issue with portable version 2.8.3).

Any idea? Maybe the language of the seed?

**Comment by ecdsa** [comment]
no the laguage of the seed is not relevant. either the seed or the derivation is wrong. ask copay.
if you use Electrum in the future, we recommend that you move your coins away from bip39, to an Electrum seed

**Comment by LeaTex** [comment]
I could restore using this https://iancoleman.github.io/bip39/ to decrypt the seed and writing the master private key in Electrum.

Derivation path was correct. I think the problem was that the seed also need a passphrase.
After that, I try again using the "extend seed using custom words" and it works. Maybe this option is not so clear.

Thanks for your support!
