### ISSUE TITLE
Import From Multibit HD - Electrum 2.9.2 showing zero balance

### ISSUE THREAD

**Issue by x101x101x101x** [spesmilo/electrum#2692]
I followed the guide on how to use Electrum and import from Multibit HD and now have a zero balance. I should have 1.4BTC https://blockchain.info/xpub/xpub698qZU9bW6SDrWc9WRLcpWkdbQZjE53Dxh83hVR3wQKSBxY6QgZNCz25DMyXcjm18jK4RmywUZqimeXqYvicAfBC6xzigNdJTDGgaBTxjcj

Also, I am seeing transactions I received and then they seem to appear as outgoing transactions right after, I circled the first one as an example in the attachment. There are numerous instances of this though through out the transaction list.
![electrum](https://user-images.githubusercontent.com/16826754/28993748-5a3f0600-797b-11e7-8a6b-73ff00953bab.jpg)

I thought maybe I could just start up my old MultiBit HD wallet, but now my original password only unlocks the Electrum wallet with a zero balance.

**Comment by ecdsa** [comment]
ask Multibit support about this. We do not have the time and resources to investigate how various other wallets have implemented BIP39, and what incompatibilities might exist between them.

if you use Electrum, please move your coins away from a BIP39 seed, to an Electrum seed.

**Comment by x101x101x101x** [comment]
Figured it out. Bread wallet can import just fine.
