### ISSUE TITLE
UX improvement: less wizard screens

### ISSUE THREAD

**Issue by LeaTex** [spesmilo/electrum#2695]
I think  the screens in wizard have so much empty space. Maybe you can reduce the steps and put togeter some options.
For example in the seed screen, you can remove the "option" button and put the checkboxes in the same screen. Also put the extended words in the same screen, by enabling/disabling the text field according to checkbox.

Also in disclaimer "note that this is not your encryptation password" you could add "(this is BIP39 passphrase)". 

![electrum screen](https://user-images.githubusercontent.com/6115573/28997020-dc070f6e-79e1-11e7-9113-ab6c7ba744e8.png)

**Comment by ecdsa** [comment]
no, options should not be visible to users who don't know what they are

**Comment by LeaTex** [comment]
But you are thinking as a programmer, not like a common end user. And how do you know what users know about every option?

According to you comment, you shuold hide the restore using, for example, a master private key, because many users don't know about this.

And there is a disclaimer: "if you do not know what this is, leave this field emtpy". That's all we need.

And please, add to disclaimer "(this is BIP39 passphrase)".
