### ISSUE TITLE
The money Disappeared from her purse . 

### ISSUE THREAD

**Issue by violinist2** [spesmilo/electrum#2699]
The money Disappeared from her purse . Good day! After a fork of bitcoin I deleted from the computer your wallet is electrum. ElectronCash I Then installed. After getting BCC I re-installed electrum and opened the new wallet, which launched after the fork bitcoin.It was All good. Elektrum saw 2 old wallet (empty-where were born and new KBK wallet with old Bitcoins.) After I decided to play safe and have copied the new wallet in another location on the computer and decided to check and open that copied file from the new location. After opening this file I saw that started the transaction(unconfirmed) on the withdrawal of all funds. I thought it was some mistake , closed the wallet and went to sleep. The next day, opening the wallet, I saw that it was not a mistake and that money is there and they are gone somewhere. I did not create this transaction. This is a bug and glitch. What to do? Can provide all files . At the time the transaction started(the disappearance of the money) have version 2.9. After it was installed 2.9.2    
 https://blockchain.info/tx/225e2ee1206ed423b4e194a5b44d94b1228c3a1f10e86388f42d7be51998c54a

**Comment by ecdsa** [comment]
it looks like your private keys have been stolen.
where did you download ElectronCash from?
we recommended not to install it on the same machine, see https://electrum.org/bcc2.txt

**Comment by violinist2** [comment]
Electron cash downloaded from the official website. Didn't think this story can happen so quickly and so easily. And it all happened in front of me. In front of me when the purse appeared this transaction. This is a good lesson.

**Comment by violinist2** [comment]
I think this may encounter many people in the future. More expensive the bitcoin, the more thieves.

**Comment by ecdsa** [comment]
if you can, please have your computer examined by a security expert.
also, do not remove any software from your computer, that would be destroying the evidence

**Comment by charleshsu168** [comment]
For bcc, use blockchair.com explorer, not blockchain.info

**Comment by ecdsa** [comment]
@violinist2 do you still have the file tht you downloaded?

**Comment by violinist2** [comment]
Yes, I have. Can I send it?

**Comment by violinist2** [comment]
Hello! Here is my ElectronCash distrib, which is probably HACKED or COMPROMISED.
http://dropmefiles.com/Phz8I (DANGER! Probably hacked!)
I've downloaded it from official site (electroncash.org) and I use it during 1-2 days. Than, all my Electrum's private keys (maybe, full wallet's files too) was stolen and ALL MY BITCOINS was disappered (transfered without my conclusion or any my action to unknown bitcoin address).

**Comment by ecdsa** [comment]
thank you. this file's checksum matches with the executable on electroncash.org.
can you please describe in detail what you did? (your first post is a bit confused)

**Comment by violinist2** [comment]
Hello! I've installed my Electrum wallet (client) after receiving BCC on my ElectronCash wallet. Then, NEW Electrum wallet founded OLD wallet file (which have no money, as I see in your instruction). Then, I've created NEW Bitcoin Electrum wallet and used 12 words (seed, passphrase) of my NEW wallet (where now are situated my transferred money). All was OK, I see my money on this new wallet.
Then, I tried to test it, and I opened another time 1 or 2 times old wallet file and new wallet file. All was OK. Than, I copied NEW wallet file (with BTC) and put it to с:/users/1/skyDrive/Документы/
After that, I started Electrum wallet and opened this wallet file  (copied in new place)... And IN THIS TIME I see new unconfirmed transaction with all BTC from my wallet!!! Unfortunately, in that time I think that this is unknown bug, I closed my wallet and go sleep tonight. Two wallet files was placed in different folders (one – default wallet folder, second - “skyDrive” folder in Users Documents folder.
System (OS): Windows 8.1 (with last updates). 
Sorry for my bad English. Thanks for your attention. If anything is not clear, I'm ready to explain it or send any files for your analize.

**Comment by ecdsa** [comment]
The file you provided is 2.9.2, from the official site. However, at the time of the theft you were running a version 2.9.0. With the information we have, it is not possible to know for sure if you downloaded 2.9.0 from the official site, of from one of the copycat websites that existed at the time. Do you still have the 2.9 version that you were using when the theft happened?

**Comment by violinist2** [comment]
Here Electrum distribs, which I used with stolen wallets http://dropmefiles.com/EBQBg

**Comment by ecdsa** [comment]
I ran the downloaded version of electron cash with netstat, I did not see anything suspicious.
No evidence that the downloaded version of electron cash was involved in the theft.
it could as well have been a keylogger.
