### ISSUE TITLE
I have balance in my wallet but cannot use, the electrum told insuficient funds

### ISSUE THREAD

**Issue by pcuadros1** [spesmilo/electrum#2701]
I have a bitcoins balance in my electrum wallet but cannot use.

**Comment by pcuadros1** [comment]
![image](https://user-images.githubusercontent.com/30782986/29007395-c1caf670-7b02-11e7-9a04-82c8ade7d7b7.png)

**Comment by pcuadros1** [comment]
Someone can help me?

**Comment by ecdsa** [comment]
untick 'spend only confirmed coins' in your preferences
