### ISSUE TITLE
building android apk with make apk failed: p4a.source dir does not exist

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#2702]
![image](https://user-images.githubusercontent.com/5799190/29007594-62fbcd32-7abb-11e7-83e6-f7cafd2b800c.png)

**Comment by ariard** [comment]
Are you sure that python-for-android is installed in /usr/local/lib/python2.7/dist-packages ? If not try pip install python-for-android

**Comment by charleshsu168** [comment]
I tried pip install python-for-android.
it **did not** put the source file in the dir specified by the buildozer.spec. 
see below.

p4a.source_dir = **/opt/python-for-android**

the workaround i did to fix it is:
i manually downloaded python-for-android.zip into the gui/kivy dir
then i modify buildozer.spec file line to:
p4a.source_dir = .
