### ISSUE TITLE
building android apk. IOError: [Errno 2] No such file or directory: './contrib/versions.py'

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#2703]
sudo make apk 
produces IOError: [Errno 2] No such file or directory: './contrib/versions.py'
![image](https://user-images.githubusercontent.com/5799190/29011596-2c7c44ca-7ae9-11e7-8b35-497290d33290.png)
not sure where i can download this from?

**Comment by ecdsa** [comment]
you have to create that file

**Comment by charleshsu168** [comment]
how? make apk should create it automatically..but it's not.

**Comment by ecdsa** [comment]
no, the process is not fully automated.

**Comment by charleshsu168** [comment]
so how do i creat this versions.py file?

**Comment by charleshsu168** [comment]
not clear from documentation ??
