### ISSUE TITLE
Unexpected address change.

### ISSUE THREAD

**Issue by cn2ts** [spesmilo/electrum#2704]
Hello, I'm very new to this. I started mining on NiceHash a few weeks ago, the first amount was sent to my fresh Electrum wallet, to which I forgot the password and had to use the string key to get it back, which worked flawlessly. What I didn't know was that my address changed for some reason (upon recovery?), something I noticed just now, after I wondered why they haven't processed the newly mined amount to my wallet yet. What I find weird is that even though the address appears to be different, the amount sent to the original address is there, as well as the logs of it. What's happened and how do I get those mbtc now? Thanks in advance.

**Comment by ecdsa** [comment]
thats normal.
read the docs if you want to learn more, github is not a support hotline.

**Comment by cn2ts** [comment]
I did, I still don't know if I can recover the bitcoins.

**Comment by AbdussamadA** [comment]
@cn2ts https://bitcoinelectrum.com/frequently-asked-questions/#why-does-electrum-give-me-a-different-address-everytime
