### ISSUE TITLE
building android apk. IOError: [Errno 2] No such file or directory: './contrib/versions.py' 

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#2706]
Please don't close the issue yet. I don't know how to create versions.py. It's not clear from the documentations. all it says in the documentation is just "make apk"

**Comment by charleshsu168** [comment]
![image](https://user-images.githubusercontent.com/5799190/29035380-3ae26014-7b50-11e7-946e-058b9fe369ee.png)

**Comment by ecdsa** [comment]
you can set the version number in buildozer.spec
please read the docs of kivy/buildozer.
