### ISSUE TITLE
Electrum incorrectly tells me "not enough funds" when using the "Max" button

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#2709]
So first of all, I'm using the Electron Cash client trying to sell the very last bit of my BCC - so apologies if this has already been fixed (tho other issues I've found in the fork exist in Electrum proper). 

On the send view, if I press "Max" it fills up my amount section with an appropriate fee based on the slider. If I then type the *same* number in manually into the amount section, it tells me "not enough funds". I've confirmed by doing my own math that this number that Max filled (and that I'm trying to manually type in) is the correct number to bring my balance to 0. So something is going wrong in that check there.

Also, kind of a feature request, if I slide the fee slider, it correctly updates the amount. But if I manually change the fee, it does *not* automatically update the amount. It should.

**Comment by ecdsa** [comment]
that's because it does not include unconfirmed coins.
I changed the defaylt value of that setting 08fab753e88f1b24a8e76f9262eb64b38ffc2572
