### ISSUE TITLE
Better clarification of inheriting base unit for pay to many 

### ISSUE THREAD

**Issue by yangwao** [spesmilo/electrum#2710]
I'm using pay to many, but I noticed when started using new Electrum, it switched base unit to mBTC and it did not work as I assume. I expected base unit in pay to many is every time in BTC.
However, I can't find where is this feature exactly documented well. Only found this http://docs.electrum.org/en/latest/faq.html#can-i-do-bulk-payments-with-electrum
![image](https://user-images.githubusercontent.com/5887929/29074831-f1b02d16-7c50-11e7-8969-148cca615e5c.png)
![image](https://user-images.githubusercontent.com/5887929/29074879-0fc45160-7c51-11e7-9c1b-78edfc86d831.png)
This leaded me than to this error https://github.com/spesmilo/electrum/issues/2642

* It should be documented, that pay to many inherits base unit
* Choose pay to many base unit in preferences

Thanks in advance, you are doing great job.

**Comment by ecdsa** [comment]
it's obvious from the screenshot that the unit is mBTC; no extra documentation is needed.
making it non-inherited would be way more confusing.
