### ISSUE TITLE
unable to start electum app

### ISSUE THREAD

**Issue by bymaximus** [spesmilo/electrum#2711]
getting some permission error, any way to enable logs to see it?

![e__program files x86 _electrum_electrum-2 9 2 exe 2017-08-08 13 21 06](https://user-images.githubusercontent.com/595991/29082681-9e45f0de-7c3c-11e7-8bf2-dbc7a0e9c1a1.png)

**Comment by bauerj** [comment]
Is there anything in `%Appdata%\Electrum`?

**Comment by bymaximus** [comment]
No, this Electrum folder doesnt exist there

**Comment by ecdsa** [comment]
check that you have the permissions to create the directory
