### ISSUE TITLE
Electrum can not run on Windows 10 64 bit system

### ISSUE THREAD

**Issue by zeng3r** [spesmilo/electrum#2712]
I have tried to run electrum wallet on win 10, but unfortunately it is not start even though i have tried a lot of version. Please try to fix this issue in the next patch, thank you.

**Comment by bauerj** [comment]
I can assure you it works on my installation of Windows 10.

What happens when you try to start Electrum? Do you get an error message?

**Comment by Lukiz** [comment]
What is your user name in directory C:\Users\<username> ? 
I have similar or the same issue and I assume its because my username contains letter ě (e with caron). I only make electrum to run with portable version located out of my user account directory (like C:\programs\electrum )

**Comment by ecdsa** [comment]
closing, no useful information here
