### ISSUE TITLE
Hello, I have a problem with a transaction to the Electrum Wallet

### ISSUE THREAD

**Issue by WilhelmN** [spesmilo/electrum#2714]
Yesterday I sent 0.076284 BCC to my walletaddress 1AQ4jzBoXV925YzzKwBYznwovkiWZKEaH5, and till now I can not find the BCC.
Is this a bug, or did I something wrong?
Many thanks WilhelmN

Amount 0.1 ETH 
Money received 08 Aug 2017, 12:41:01 
Fee 0.00219238 BCC 
Exchange rate 1 ETH = 0.76667336 BCC 
Receiver 1AQ4jzBoXV925YzzKwBYznwovkiWZKEaH5 
Output transaction hash 82d8197933d3effa3981f6e59086dcc0b46f23f086c2b5fdd11ad52b13790dd8 
Amount 0.076284 BCC 
Money sent 08 Aug 2017, 13:22:58

**Comment by hachre** [comment]
Electrum only does BTC, not BCC.

**Comment by ecdsa** [comment]
that's a BCC address

**Comment by WilhelmN** [comment]
Hello,
thx for the answer, it seems I have made a misstake. Do you know if it is possible to get back the BCC? 
Thx a lot.
Wilhelm Neunteufel

**Comment by hachre** [comment]
Sorry, I don't know.
