### ISSUE TITLE
wallet

### ISSUE THREAD

**Issue by tacha136** [spesmilo/electrum#2717]
I downloaded the wallet and sent some BCC to one of my addresses but never received the coins
Am I doing something wrong?
Do I need to keep the wallet/electrum on or open all the time to receive coins/
Confused

**Comment by hachre** [comment]
Electrum is for BTC, not BCC.

**Comment by tacha136** [comment]
I did a search for Bitcoin Cash wallets and Electrum was one of the choices
If it is only for BTC where can I get a BCC wallet

**Comment by bauerj** [comment]
See https://www.bitcoincash.org/

**Comment by ecdsa** [comment]
and read https://electrum.org/bcc2.txt first
