### ISSUE TITLE
error with trezor multisig

### ISSUE THREAD

**Issue by fireduck64** [spesmilo/electrum#2718]
Environment:
- ubuntu
- Electrum 2.9.2 installed via pip2

Process:
- Plugged in unconfigured trezor, updated to latest trezor software (1.5.0 via https://wallet.trezor.io)
- In electrum, created new wallet.  Multisig, 2of2.
- First signer is regular electrum seed
- Second signer is hardware trezor.  Selected 12 word seed because I am just testing.
- Funded account with test amount (38uYAkCYFof3ekmnq3SwuvRBprsxVc4Suf)
- Tried to send funds, got error: "sign_tx() got an unexpected keyword argument 'lock_time'"

Log as follows, I tried it twice, one with replaceable and one without.

electrum/wallets$ electrum -vv -w trezor_test_1 
[SimpleConfig] electrum directory /usr/local/google/home/jgleason/.electrum
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', u'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', u'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', u'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', u'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0043
[Network] blockchains [0, 478785, 478559]
[Network] starting network
[Network] connecting to kirsche.emzy.de:50002:s as new interface
[FxThread] using exchange BitcoinAverage
[VPS.hsmiths.com] failed to connect [Errno 111] Connection refused
[gh05.geekhosters.com] failed to connect [Errno 111] Connection refused
[us11.einfachmalnettsein.de] connected
[WalletStorage] wallet path /usr/local/google/home/jgleason/.electrum/wallets/trezor_test_1
[mash.1209k.com] connected
[Plugins] loaded trezor
[Electrum.hsmiths.com] connected
[profiler] load_transactions 0.0002
[profiler] build_reverse_history 0.0000
[profiler] check_history 0.0001
[Network] no height for main interface
[Network] switching to us11.einfachmalnettsein.de:50002:s
[Network] sending subscriptions to us11.einfachmalnettsein.de:50002:s 0 0
[kirsche.emzy.de] failed to connect [Errno 111] Connection refused
[Network] fee_estimates[25] 93343
[Network] fee_estimates[10] 101447
[Network] fee_estimates[5] 123006
[Network] fee_estimates[2] 135501
[Network] relayfee 1000
[profiler] write 0.0001
[profiler] save_transactions 0.0006
[profiler] on_update 0.0008
[ElectrumWindow/trezor_test_1] Notifying GUI
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[trezor] Trying to connect over USB...
[de01.hamster.science] connected
[trezor] connected to device at 0002:000d:00
[mash.1209k.com] binary search
[DeviceMgr] Registering white1/D76AD5DCC2AE24B49EA1B3D6
[trezor] Trying to connect over USB...
[trezor] cannot connect at 0002:000d:01 Connection failed
[trezor] cannot connect to device
[electrum.no-ip.org] connected
[erbium1.sytes.net] connected
[profiler] on_update 0.0014
[electrum3.hachre.de] connected
[ultra-ecoelectrum.my-gateway.de] connected
[profiler] on_update 0.0015
[node.xbt.eu] connected
[134.119.179.55] saving certificate
[134.119.179.55] connected
[elex01.blackpole.online] failed to connect timed out
[s2.noip.pl] saving certificate
[s2.noip.pl] connected
[DeviceMgr] end client for keystore
[profiler] estimated_size 0.0003
[profiler] estimated_size 0.0003
[profiler] estimated_size 0.0002
[profiler] estimated_size 0.0002
adding signature for ff0488b21e0000000000000000004b2d4fb7ac65f96cabd19547899f76c8554acb0fd6a36c91e3e4c8dd0cf15f39026622075c29788e019cbea7db289f0d27f1e08b68f9da567b5b3d2a7752b978fa00000000
is_complete False
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 242, in sign_transaction
    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/clientbase.py", line 221, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 98, in wrapped_f
    return f(*args, **kwargs)
TypeError: sign_tx() got an unexpected keyword argument 'lock_time'
[profiler] estimated_size 0.0003
[profiler] estimated_size 0.0002
[profiler] estimated_size 0.0002
adding signature for ff0488b21e0000000000000000004b2d4fb7ac65f96cabd19547899f76c8554acb0fd6a36c91e3e4c8dd0cf15f39026622075c29788e019cbea7db289f0d27f1e08b68f9da567b5b3d2a7752b978fa00000000
is_complete False
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 242, in sign_transaction
    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/clientbase.py", line 221, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 98, in wrapped_f
    return f(*args, **kwargs)
TypeError: sign_tx() got an unexpected keyword argument 'lock_time'
[ElectrumWindow/trezor_test_1] close_wallet /usr/local/google/home/jgleason/.electrum/wallets/trezor_test_1
[TrezorClient] closing client
[TrezorClient] clear session: white1/D76AD5DCC2AE24B49EA1B3D6
[Network] stopping network
[Network] stopped
[Plugins] stopped
[profiler] save_transactions 0.0002
[WalletStorage] saved /usr/local/google/home/jgleason/.electrum/wallets/trezor_test_1
[profiler] write 0.0691
[Daemon] shutting down network
[Daemon] stopped

**Comment by fireduck64** [comment]
Looks like I'm not the only one:
https://www.reddit.com/r/Electrum/comments/6rno1u/electrum_and_trezor_with_latest_firmware/

**Comment by fireduck64** [comment]
"fixed" by this:

pip2 install trezor --upgrade

now I get: 
dding sig 0 0 02dca74e82757a568661484bb353bc075dce1721d41367b0d1fcc948016f44ced6 3045022100e768706ba4ab56832d2fcf7d64ee329c34bedc0957fa463d1f8ecf1fd7fcb80602203583132ec4cfe3ec6ab66aa7bc6e10af66893ab45fff41691cc6ce06a26a0ab801
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 244, in sign_transaction
    tx.update_signatures(raw)
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 559, in update_signatures
    r, s = ecdsa.util.sigdecode_der(sig.decode('hex')[:-1], order)
  File "/usr/local/lib/python2.7/dist-packages/ecdsa/util.py", line 240, in sigdecode_der
    binascii.hexlify(empty))
UnexpectedDER: trailing junk after DER sig: 01

**Comment by ecdsa** [comment]
update trezorlib

**Comment by ecdsa** [comment]
it works with the sig in your traceback:
```
import ecdsa
sig='3045022100e768706ba4ab56832d2fcf7d64ee329c34bedc0957fa463d1f8ecf1fd7fcb80602203583132ec4cfe3ec6ab66aa7bc6e10af66893ab45fff41691cc6ce06a26a0ab801'
order = ecdsa.ecdsa.generator_secp256k1.order()
r, s = ecdsa.util.sigdecode_der(sig.decode('hex')[:-1], order)
```
so, you're probably running an older instance of electrum
