### ISSUE TITLE
trezor and electrum doing different bip39?

### ISSUE THREAD

**Issue by fireduck64** [spesmilo/electrum#2723]
I could really be misunderstanding how things are supposed to work so this might not be an actual problem.  Before I use something for real, I like to ensure that I understand the recovery mechanism and can restore it so I was doing a test.

I'll be revealing some private seeds here, but they have no transactions so I'm fine with that.

Wiped trezor.  Generate new wallet.  Seed words:
borrow monkey share marble day gosple home first grid imitate grit cannon rocket autumn day produce yellow report unknown negative pigeon narrow orchard horse

wallet.trezor.io and electrum when attached this trezor say the xpub is
xpub6DSD9w9kgY3KNvKckcJkNR6FZtiQp8H2AZvWUyx2yK7upBfAZEXH5pqJsUE7gAFLZeoJVRGYpUWnaDdvrjxQmTdQzVwrpmjb8RuBPy3VJuh
and first address is 19qZ6jT6kiM2Q5Fh1tsFKL3AYt2D5GaXB3

However, lets say I lost my trezor and needed to use that wallet.  I should be able to import that seed into electrum as a bip39 seed, right?

I put it in and it accepts it and tells me the xpub is xpub6CZus7DgxciQ49ibdFwz2XC1YZ7gLAs2y8RL2tbnbHbLwadBQvWgpoZxpNtRAaEU83QjGZkRS9DiVWJmKuiBqVwX81AonmBb3RJpMvmdTLX and the first address is 1599zNT1td2tDorHDqqxzMgyePeKS8K1Zp

This doesn't seem right.

**Comment by ecdsa** [comment]
gosple -> gospel 
(electrum does not check the bip39 checksum)

**Comment by leafcutterant** [comment]
Just to reduce the number of users running into problems, do you think you can add BIP39 checksum checking?

**Comment by leafcutterant** [comment]
Correction: now i noticed it *does* check the checksum. But doesn't stop the user from proceeding, just silently notes it under the text box.

Making the note under the text box red when the BIP39 checksum is incorrect, or throwing a message "BIP39 checksum is incorrect, are you sure you want to proceed? Yes/No" would be a good idea.
