### ISSUE TITLE
Can't access Electrum Win 10 64 Bit

### ISSUE THREAD

**Issue by kliskey** [spesmilo/electrum#2725]
Ok, similar to the issue already posted.... but here is what is happening for me :/

Newly installed version 2.9.3 and tested with a quick transfer. Everything seems ok. So, I next closed it down and tried to reopen it.

I enter my password, hit next (all checks out) and then nothing happens (like, nothing at all)

Try running the application again, enter wrong password/ no pass intentionally and I get an error message, try with the correct and the same issue presents itself.

The only workaround I have is to delete the "config" and "block_chain header" files, creating a new wallet with original seeds. However, when I close down the wallet and try to reopen, I have to go through the same process once more....

Surely this isn't how the wallet is supposed to function? 🦄

**Comment by BartKnucle** [comment]
Works for me, where did you get the binairies? Have you tried the standalone version?

**Comment by ecdsa** [comment]
when you create the wallet, try to disable wallet file encryption.

**Comment by ecdsa** [comment]
closing, no answer
