### ISSUE TITLE
2.9.3 dies silently on Win 10 64-bit

### ISSUE THREAD

**Issue by whizz** [spesmilo/electrum#2729]
Hello. After upgrading to 2.9.3, Electrum will not start. When I launch the executable, I see it in the task list for a bit and then it silently exits. No UI elements are visible in the process. After downgrading to 2.9.2 everything works fine. I am unable to locate any log files in the executable directory or in %AppData%\Roaming\Electrum, so I am at a loss.

I tried both the portable and installer versions, both behave the same.

**Comment by RedTea** [comment]
So do I on Win 10 64-bit

**Comment by ache** [comment]
Me too.

**Comment by ecdsa** [comment]
sorry, there was a mising file in the last windows binaries.
I rebuilt the files, please download again, and let me know

**Comment by ache** [comment]
Thanx, fixed.

**Comment by whizz** [comment]
Confirmed fix. Thank you for a super fast response. You rock!
