### ISSUE TITLE
Problems: Creating multisig wallet with electrum commandline

### ISSUE THREAD

**Issue by xmkane** [spesmilo/electrum#2730]
As @ecdsa said in the issue : [https://github.com/spesmilo/electrum/issues/2414](url)
"createmultisig is not supposed to create a wallet address.
next time, explain what you want to do"

Currently I have successfully create multisig wallet in electrum GUI,
but have  problems of creating multisig wallet with electrum command line, there is no manual about this.

This how I did:
1. create 2 standard wallets in sperated machines;
2. electrum createmultisig address with 2 wallets first standard address's publickey;
3. I use other address payto the p2sh address, and have been confirmed by network;
but the multisig address not show in my wallet with listaddresses, and also show in unspent :(

Is there a step of create multisig wallet with electrum command line?  How to do this

**Comment by ecdsa** [comment]
no there is no way to create a full wallet with the command line.
