### ISSUE TITLE
electrum 64bit Windows 10 crash when selecting restore Hardware wallet

### ISSUE THREAD

**Issue by MarcusMM2** [spesmilo/electrum#2731]
TREZOR is connected via USB, crash when "use a hardware device" and not using standard wallet name but own wallet name

**Comment by ecdsa** [comment]
are you sure it is caused by trezor? does it work if you restore a standard wallet from seed?
does the filename contain special characters?

**Comment by MarcusMM2** [comment]
yes with standard wallet it works (wallet_1)
maybe because I gave filename with extension

**Comment by MarcusMM2** [comment]
or maybe because filename has Space (yes, it has)

**Comment by ecdsa** [comment]
1) what is the filename you gave?
2) do you experience similar issues if you create a software wallet (without trezor)

**Comment by MarcusMM2** [comment]
it's no longer crashing (I just tried several filenames). But for sure it was crashing twice.
I think the first time it was crashing I had "C.\abc\Marcus Wallet.db" open (non-standard) and tried then to "use hardware device".
The next time when I have problems I will excactly remind the steps/filenames.

**Comment by MarcusMM2** [comment]
to clarify: "C:\abc\Marcus Wallet.db" is another (0,00 EUR) Wallet. I have to open "something", otherwise I cannot select "File - Restore/new". With this Wallet opened I used "File - Restore/new" ... "use Hardware device" -> crash

**Comment by ecdsa** [comment]
closing, not reproducible
