### ISSUE TITLE
Can't open Electrum 2.9.3 on Windows 7 SP1 x64

### ISSUE THREAD

**Issue by agiudiceandrea** [spesmilo/electrum#2732]
Electrum 2.9.3 fails to execute after proper installation on my system with Windows 7 SP1 x64.
The process seems to abort after few seconds from launch.
Instead Electrum 2.9.3 standalone works.

Previous installations of Electrum (2.9.0, 2.9.1, 2.9.2) worked without problems on my system.

Is there anything I can do to debug the problem?

**Comment by ecdsa** [comment]
the initial 2.9.3 builds were crashing, and we updated them.
maybe you downloaded the initial ones? please retry

**Comment by agiudiceandrea** [comment]
Probably you are right! I've downloaded a new copy of Electrum 2.9.3 Windows installer: after installation now Electrum 2.9.3 works without problem.
Thank you.
