### ISSUE TITLE
trezor multisig key mismatch

### ISSUE THREAD

**Issue by fireduck64** [spesmilo/electrum#2734]
I seem to get a wrong key when attaching a wallet to a trezor with multisig.  I imagine I am doing something wrong, but can't figure out what.  I am getting a strange xpub for a trezor but only when used as a multisig cosigner.

How I got here is making a 2of2 multisig wallet with one of the cosigners being a trezor device.

Anyways, take a trezor that is wiped.  Restore this bip39 seed:
echo view wide maze wear rug enforce coil raise stock taxi nasty genre soft sketch warfare mountain evoke deliver ginger violin differ fly lobster

If you do that as a standard wallet (no multisig) you get:
xpub6CnWhPtqMqPkUFfkAxSagD8s1BwucdG4ie7fJDxzECTb3szuvQ4zRSTsJwPYjVy1VCycRNoVE7CtVxeCC24wF4hywBrrEUuHh2sGZDH3uWj

This is agreed as correct by https://iancoleman.github.io/bip39/ and by connecting the trezor to wallet.trezor.io/#/

Now create a multisig (2of2) wallet, with the first signer being a normal electrum seed and the second being your hardware device.

That same trezor now shows up as xpub6BCsJo29CGRmd3TXCLDm3tpupeLWu3cy8VFjtx4QmcssiTEgHLSZvonZQ2ohUek6oR1DKp6tRq4RJVwki5Fi4zWMShSun7fx5e8iDKidAG5

I am puzzled.

**Comment by fireduck64** [comment]
Ok, it looks like the xpub...AG5 is coming from derivation path m/45'/0, which seems strange.

Why would it be different than the path used when importing the same seed as a bip39 seed rather than using a trezor?
If you go to https://iancoleman.github.io/bip39/ and bip32 and put in m/45'/0 as the custom path it does indeed show this xpub.

**Comment by ecdsa** [comment]
that's for privacy.
