### ISSUE TITLE
trezor multisig failure to sign

### ISSUE THREAD

**Issue by fireduck64** [spesmilo/electrum#2738]
After creating a multisig 2of3 wallet with two standard electrum seeds and one trezor cosigner I get the following error when trying to send a transaction that involves change:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 242, in sign_transaction
    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/clientbase.py", line 221, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 824, in sign_tx
    res = self.call(proto.TxAck(tx=msg))
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/client.py", line 201, in call
    msg = handler(resp)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/clientbase.py", line 35, in callback_Failure
    raise RuntimeError(msg.message)
RuntimeError: Failed to compile output

However, if I send a transaction that spends the entire wallet with no change, I get no errors.

This is with electrum 2.9.3 and python trezor 0.7.16

**Comment by ecdsa** [comment]
I cannot reproduce that; is your firmware up to date?

**Comment by fireduck64** [comment]
Yeah, 1.5.0

**Comment by fireduck64** [comment]
Also, I have the pin disabled.  Maybe that changes the flow?

**Comment by BTCgithub** [comment]
Try downgrading to Electrum 2.9.2
This resolved another Trezor signing issue in 2.9.3

**Comment by fireduck64** [comment]
Same error on 2.9.2

**Comment by fireduck64** [comment]
I did some more testing, if seems to open be a problem when the change address is a multisig address.  I can do a pay to many and if I structure it to spend the entire wallet with no change it signs just fine.

**Comment by ecdsa** [comment]
note: my trezor shows the change address as a recipient address if the change is multisig

**Comment by fireduck64** [comment]
I get the same error on 2.9.2 standalone on windows.  I did it with a new set of keys on a new trezor (my other one is a first edition and I was thinking maybe something in the hardware is different).

**Comment by fireduck64** [comment]
Seems to be a new version of #1975

**Comment by fireduck64** [comment]
Probably coming from this code: https://github.com/trezor/trezor-mcu/blob/3440ead4c9b3ec4f39a8faee558f1ec8f974b854/firmware/signing.c#L992

**Comment by jhoenicke** [comment]
My first guess is that the plugin gives an address for the change output.  Older firmwares just ignored such an address (as you mustn't trust the PC to give the correct change address), newer firmware complains with this generic error message.

 I'll try later to reproduce this issue, to see if this is the case.

**Comment by jhoenicke** [comment]
My first guess was wrong.   The problem is that Electrum doesn't set `address_n` at  all for multisig change addresses.  I don't think that would work with any firmware.

Patch is here, but I haven't thoroughly tested this yet: https://github.com/spesmilo/electrum/compare/master...jhoenicke:multisigfix

**Comment by jhoenicke** [comment]
There is still a problem that the second signer needs to confirm the return address.  This is an electrum problem, though.  The information in x_pubkeys is replaced by a pubkey if there is already a signature present, so the input doesn't look like it comes from the same wallet.  The raw transaction only contains the x_pubkey information until the signature is filled.

**Comment by fireduck64** [comment]
@jhoenicke Thanks for working on this.  Your change in #2755 does allow me to sign multisig transactions, however it makes it look to the trezor as if both the payment and the change are outputs from the wallet to confirm.  I'm not sure I follow your comments, do we need to make the trezor always first or always last?  Would that help? 

But I can sign the transactions now so I am unblocked.  Thank you very much.

**Comment by jhoenicke** [comment]
Making it always first, would help, but is an ugly workaround (and doesn't work for me as I'm testing with two Trezors :))

I'm not sure if it is better to change the multisig code to only replace the xpubs when all signatures are finished, or to extend the `add_hw_info` code to reconstruct the xpubs for inputs.

**Comment by ecdsa** [comment]
@jhoenicke not sure what you mean; tx.output_info already has the list of xpubs, doesn't it?

**Comment by jhoenicke** [comment]
The first time the transaction is serialized x_pubkeys is set to a ff... key, i.e., xpub + path.  When the first Trezor signs the transaction, its x_pubkeys entry is replaced by 02/03.., the final public key.  This is done in `update_signatures` and also in `sign` in transaction.py.

Trezor needs to know the original xpub of all parties to sign the transaction.

**Comment by ecdsa** [comment]
sorry I did not understand you were talking about inputs; @fireduck64's issue seems to be about outputs.
why does trezor need that? is that a new feature?

**Comment by ecdsa** [comment]
@jhoenicke I just upgraded my trezor firmware and I do not see the issue.
I can sign a 2 of 2 transaction with change, using ledger and trezor, (trezor signing after ledger)

**Comment by jhoenicke** [comment]
TREZOR checks that the change output has the same signers as all inputs.  If there is a mismatch it will treat the change output as a normal output and ask for confirmation.  It still allows to sign it, but it will ask if it is okay to send the full amount.

**Comment by ecdsa** [comment]
@jhoenicke my device is not asking for confirmation.
I see a first screen with "confirm sending <output_value> to <destination>". Then another screen with "really send <output_value + fee_value>" from your wallet? Fee included: <fee_value>"
The tx is multisig 2 of 2, the first signer is ledger

**Comment by jhoenicke** [comment]
I see, ledger doesn't change `x_pubkeys`, so that answers my question whether it is necessary :)

So signing with cosigning with ledger works, signing with two Trezor or first with Electrum and then with Trezor would make confirming the change output necessary. 

I would suggest removing line 570 and 835 in [transaction.py](https://github.com/spesmilo/electrum/blob/master/lib/transaction.py).  This means that in a partially signed transaction all public keys are kept in the xpub format (ff+xpub+path).  In line 621 the serialization code already makes sure to switch to the pubkeys as soon as all signatures are present.
I don't know the code that well yet, so do you see any reason why keeping the x_pubkeys as long a possible would make problems?

**Comment by ecdsa** [comment]
indeed that explains it. I do not think it would be a problem to keep x_pubkeys until all cosigners have signed.

**Comment by ecdsa** [comment]
I have commented out these lines. I am not 100% sure if that breaks something, we will have to test
