### ISSUE TITLE
Can't Restore Trezor from Written Seed

### ISSUE THREAD

**Issue by optimator999** [spesmilo/electrum#2739]
I am using Tails 3.1. The issue occurs in Electrum 2.7.9, 2.7.18, and 2.9.3. The error messages are from 2.9.3

1) Start with a wiped Trezor
2) Launch Electrum
3) Plug in Trezor
4) Choose New/Restore, Accept wallet name
5) Select Standard Wallet 
6) Select Use a Hardware Wallet
7) Select Device
8) Select Recover from seed you have....
9) Name device, keep PIN checked, keep passphrase unchecked

At this point the following happen
a) An Error dialogue box appears
b) The boxes text says "You'll be ask to enter 24 words regardless..."
c) The Trezor shows the PIN pad like it is expecting a PIN to be input

If you select OK a "Please wait" message appears and nothing happens.

After #2 The following error occurs

```
Gtk-Message: Failed to load module "gail"

** (python:20965): WARNING **: (bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost.localdomain
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost.localdomain
Qt: Session management error: Could not open network socket

```

After #6 The following error occurs

```
Qt: Session management error: Could not open network socket
Traceback (most recent call last):
  File "/home/amnesia/Persistent/Electrum-2.9.3/lib/plugins.py", line 150, in get_hardware_support
    p = self.get_plugin(name)
  File "/home/amnesia/Persistent/Electrum-2.9.3/lib/plugins.py", line 178, in get_plugin
    self.load_plugin(name)
  File "/home/amnesia/Persistent/Electrum-2.9.3/lib/plugins.py", line 102, in load_plugin
    p = loader.load_module(full_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/amnesia/Persistent/Electrum-2.9.3/plugins/ledger/qt.py", line 12, in <module>
    from btchip.btchipPersoWizard import StartBTChipPersoDialog
ImportError: No module named btchip.btchipPersoWizard
```

**Comment by ecdsa** [comment]
update btchip-python

**Comment by optimator999** [comment]
Unfortunately, the problem still persists.

To implement your suggestion on tails, the following commands were executed:

```
sudo apt-get update
sudo apt-get install python-qt4 pyton-pip python-setuptools
sudo apt-get install cython python-wheel build-essential python-dev libusb-1.0-0-dev libudev-dev
torsocks pip install btchip-python -U
```

This installed btchip-python-0.1.20

Once btchip-python was updated, I repeated the steps above. The second error (Error after #6) was resolved (That is no error log was produced), however the device behavior is the same.

To further illustrate, if in step #9 you uncheck PIN, Trezor prompts you to enter the Nth word of your passphrase, while the UI prompts you with the "enter 24 words regardless..." textbox. Again, if you select OK, the dialog box disappears and the underlying UI says "please wait". And there is never a way to enter your passphrase.

**Comment by jhoenicke** [comment]
Can you update python-trezor  (pip install trezor -U)?  Tails comes with trezor-0.7.6 which is too old for electrum.

**Comment by optimator999** [comment]
I installed python-trezor (torsocks pip install trezor -U) trezor-0.7.16, however, the problem still exists.

Some additional testing. This is with Electrum 2.9.3 and the behavior is the same regardless of the python-trezor version.

1) I connect to Electrum with a Trezor that has previously been seeded;
2) I am prompted for PIN. Everything works.
3) I click on the Trezor icon on the bottom right and then select advance.
4) I click "Disable PIN" 
5) I get a confirmation message on the Trezor but the Electrum UI freezes. No matter if I choose cancel or accept on the Trezor Electrum remains frozen.

In fact, all feature in the Advance section do not work.

**Comment by optimator999** [comment]
I've also confirmed this behavior on ubuntu 16.04 LTS, latest Electrum, Trezor, and btchip.

**Comment by SomberNight** [comment]
Closing this as related code changed too much since this was opened.
