### ISSUE TITLE
My lost bitcoin

### ISSUE THREAD

**Issue by Neuronix38** [spesmilo/electrum#2740]
My bitcoins were transferred to an address I do not know.
My bitcoins are in transfer mode and not send to the address.
How to recover my bitcoins

**Comment by bauerj** [comment]
You probably got some kind of Malware.

Did you recently install Electrum or Electron Cash? If so, can you post the download links you used?

**Comment by Neuronix38** [comment]
No I have not recently installed electrum

**Comment by Neuronix38** [comment]
My bitcoins were transferred to the address 1QH9RcftX9kKpbAWbmpQxDVpPcNtsMFTg3 without my permission

**Comment by bauerj** [comment]
Can you provide more information?

Are you using Windows? If so, do you still have the installer file? What version of Electrum are you using? Were your entire funds transferred?

**Comment by Neuronix38** [comment]
Yes I use Windows. I no longer have the windows installation file.
The version of my electrum is 2.9.0
My background has been transferred to an address

**Comment by Neuronix38** [comment]
How I Can Recover My Bitcoins

**Comment by bauerj** [comment]
You can't. Bitcoin transactions are irreversible.

**Comment by Neuronix38** [comment]
Even if I did not make the transaction

**Comment by bauerj** [comment]
Yes. The only one who could return your Bitcoins is the receiver of that transaction. Even if you convinced everyone that you didn't make that transaction, Bitcoin still relies on cryptography and not good words.

You should concentrate your efforts on finding out how someone got access to your wallet.

**Comment by Neuronix38** [comment]
https://download.electrum.org/2.9.3/electrum-2.9.3-setup.exe

2017-08-12 22:25 GMT+02:00 Johann Bauer <notifications@github.com>:

**Comment by bauerj** [comment]
That's certainly not the link you used to install Electrum 2.9.0.

**Comment by Neuronix38** [comment]
My bitcoin was sent to another bitcoin address on my own without doing
any transaction. Is there a way to recover my bitcoins?


2017-08-12 22:27 GMT+02:00 Neuronix 38 <bonnelnicolas52@gmail.com>:

**Comment by fyookball** [comment]
> Is there a way to recover my bitcoins?

Unfortunately not.  Are you sure it wasn't a tx you made or a change address?

**Comment by Neuronix38** [comment]
No I did not do tx
But yes it is a change address but how to access this new address

**Comment by fyookball** [comment]
from top menu, choose view, then address.  this will make address tab available.
go to this address tab, then expand the "Change" list, and then expand the "used" list

**Comment by Neuronix38** [comment]
Ok and then I have to do what to get the bitcoins

**Comment by Neuronix38** [comment]
And then how to recover the bitcoins

**Comment by fyookball** [comment]
they are already in your balance.  you dont have to do anything special.  electrum will use those and any other addresss automatically.  if you want to specifically spend from that address (not that you need to because again electrum does it automatically) you can right click -> spend from

**Comment by Neuronix38** [comment]
My balance displays 0 btc so they are not in my balance

**Comment by fyookball** [comment]
if theres an address with a balance then it will show in the wallet balance

**Comment by Neuronix38** [comment]
I do not understand. My bitcoins will come back on my own

**Comment by Neuronix38** [comment]
It appears well in the balance of the portfolio but how to recover them since it was in my basic portfolio

**Comment by fyookball** [comment]
cant follow what youre saying. post some screenshot with your addresses crossed out for privacy but the last few characters visible so i can follow

**Comment by Neuronix38** [comment]
![preuve](https://user-images.githubusercontent.com/30877091/29244259-f2f37dc0-7fb3-11e7-8576-4b3f104d32ac.PNG)

**Comment by Neuronix38** [comment]
![preuve2](https://user-images.githubusercontent.com/30877091/29244260-ffe48812-7fb3-11e7-9f18-e84d25969473.PNG)

**Comment by Neuronix38** [comment]
![preuve3](https://user-images.githubusercontent.com/30877091/29244263-06ab33da-7fb4-11e7-8b3e-2b8d19149630.PNG)

**Comment by Neuronix38** [comment]
The transaction is not marked as sent but transferred

**Comment by fyookball** [comment]
i dont see this address 1QH9RcftX9kKpbAWbmpQxDVpPcNtsMFTg3  in your wallet.

**Comment by Neuronix38** [comment]
Yes the address is not in my portfolio but the transaction is marked as transfer so how to find this address

**Comment by fyookball** [comment]
marked as transfer where? in what platform?

**Comment by Neuronix38** [comment]
So my bitcoins have been transferring to a new address that is mine but I do not see it and how I made it to access this new wallet

**Comment by Neuronix38** [comment]
On the blockchaine site I have an account so I import my address 1LP8SH2UNfcDtjiHXkBkDq1MNS6zgYFtRZ as read-only to see the transactions and the last transaction is transferred.
I am sending you screenshots

**Comment by Neuronix38** [comment]
![preuve4](https://user-images.githubusercontent.com/30877091/29244349-61bfac54-7fb6-11e7-8837-43bfa5679218.PNG)
![preuve5](https://user-images.githubusercontent.com/30877091/29244350-63d5ad9a-7fb6-11e7-88c4-0b3585f51f22.PNG)

**Comment by fyookball** [comment]
sounds like you should ask the blockchain site where you have your account

**Comment by Neuronix38** [comment]
It is electrum that sent my bitcoins to an address that I do not know, the site blockchain serves me just to verify the transactions of my wallet and the last transaction is to transfer

**Comment by Neuronix38** [comment]
How do I get my bitcoins?

**Comment by fyookball** [comment]
>It is electrum that sent my bitcoins to an address that I do not know

Can  you screenshot that part in electrum?

**Comment by Neuronix38** [comment]
![capture](https://user-images.githubusercontent.com/30877091/29244534-ce452b02-7fba-11e7-8c34-2d3d8ea30224.PNG)

**Comment by Neuronix38** [comment]
so

**Comment by fyookball** [comment]
Ok i see the tx, but honestly it doesnt look good because i dont see that address 1QH9RcftX9kKpbAWbmpQxDVpPcNtsMFTg3 in your wallet.

**Comment by Neuronix38** [comment]
We robbed my bitcoin

**Comment by fyookball** [comment]
if youre sure you didnt just send it somewhere and forgot where, then yes :(  

Fortunately, it was only .013 BTC.   If that is true, you have to assume your entire computer is compromised and re-install the operating system.

**Comment by dabura667** [comment]
@Neuronix38 When you created your Electrum wallet brand new, did you write down the 12 word backup phrase?

Were you instructed by anyone to enter your 12 word phrase into a website?

Are you using a business computer given to you by your employer?

How did you buy your computer?

Do you visit bad websites (warez, pirated content, adult videos) that usually have viruses?

There is a good chance that someone besides you knows your 12 word backup phrase. Anyone who knows that phrase can send bitcoins on your behalf, even without using Electrum.

**Comment by Neuronix38** [comment]
Yes I keep my sentence of recovery of 12 words.

No one informed me to enter my 12 word phrase into a website.

No this computer is personal.

I bought my pc in a magazine, it was completely new.

I do not visit pirated content.

My computer has an antivirus.

2017-08-13 3:39 GMT+02:00 Dabura667 <notifications@github.com>:

**Comment by ecdsa** [comment]
there is nothing we can do if your bitcoins have been stolen
as @dabura667 said, someone has gained access to your seed.

to prevent this kind of theft, you should invest in a hardware wallet, or use two-factor authentication

**Comment by gargkanishka90** [comment]
@Neuronix38 I have the same problem. I lost all my BTC. Were you able to recover your money? If Yes, then how? Thanks in advance.

**Comment by Beardiied** [comment]
I invested $20,000 worth of bitcoin with a scam trading platform called Finrally option. I was worried and i stumbled on SpyHacklord007 on google. He has been a big help to me. Contact: Spyhacklord007@gmaildotcom

**Comment by Paulayates** [comment]
I lost my entire fortune to trading with wrong crypto currency brokers or maybe so unlucky that i lost over $500k, of not just my money but from also friends and family. As fate would have it through a friend who met this genius on the darknet although skeptical at first he was able to help me Recover all of my funds back from the broker companies in no less than 72hours. I can confidently say Blackwebs is the best, he can be contacted through Recovery@blackwebs.org    or  508-556-9312. Please mention that you were referred by Yates.
