### ISSUE TITLE
Electrum v2.9.3 with Trezor = sign_tx() got an unexpected keyword argument 'lock_time'

### ISSUE THREAD

**Issue by BTCgithub** [spesmilo/electrum#2741]
I've been using Electrum with Trezor for quite some time and had no problem until v2.9.3. 

I've was successfully sending/signing BTC via Trezor and Electrum in v2.8.3 
Trezor Firmware v1.5.0 was used for all tests.

Electrum v2.9.3 will not allow you to Sign transactions with Trezor and returns a dialog box with the error:        'sign_tx() got an unexpected keyword argument 'lock_time'

Downgrading to Electrum v2.9.2 resolves this and you can then send BTC signing with Trezor.

Was it possibly related to: 
# Release 2.9.3
* fix ledger signing of non-RBF transactions

P.S. I edited/removed the History issue as it appears unrelated.

**Comment by ecdsa** [comment]
upgrade your python trezor library

**Comment by BTCgithub** [comment]
Hi,

I was running the Windows Installer version 2.9.3 below (before downgrading to Windows Installer 2.9.2)
https://download.electrum.org/2.9.3/electrum-2.9.3-setup.exe

**Comment by ecdsa** [comment]
could you re-download the 2.9.3 installer file? I had to do the windows binaries twice, and there is a chance you have this issue because you downloaded the first version.

**Comment by BTCgithub** [comment]
Will do and will reply back after testing.

I did download the 2.9.3 Installer very quickly after the release was posted. Possibly within 2 hours of it's release.

**Comment by BTCgithub** [comment]
Hello,

Yes, re-downloading and re-installing the 2.9.3 Windows Installer resolved the Trezor Signing problem.

Just to note that the file size of the original v2.9.3 and the current v2.9.3 Installer were different as well.

Thank you for developing & supporting Electrum.
