### ISSUE TITLE
2FA enabled on wallet after update.

### ISSUE THREAD

**Issue by Hashifier** [spesmilo/electrum#2744]
I just updated Electrum from 2.6 to 2.9.3 and now it says that my wallet is 2FA... Which I never have setup, do anyone have a solution for this? I saw someone else talking about this also #2677 and #2574. My second wallet is still fine and says "standard". Anyone got an idea?

**Comment by SomberNight** [comment]
Do you still have the seed words for the wallet in question? Try restoring from that.

**Comment by ecdsa** [comment]
do you recognize this wallet as yours? 
were the transactions in the history made by you?

**Comment by Hashifier** [comment]
@ecdsa Yes, infact I sent a transaction to the wallet with a very low fee and since I had an outdated version of Electrum pay for parent transactions was not an option... Which led me to update, I might try to downgrade and see if it makes any difference.

**Comment by Hashifier** [comment]
@SomberNight I tried restoring the wallet and as soon as I typed in my seed it said "2FA seed" and when I pressed next the page froze which was abit weird. I'm 100% sure I haven't enabled 2FA for this wallet, this must be some sort of bug.

**Comment by ecdsa** [comment]
I guess you never sent bitcoins from the wallet, because you only mention that you sent to the wallet. 
Since you have the seed, then you probably created this wallet with 2FA, and then you forgot about it, having never used the 'send' function.
Restoring from seed should work, though.

**Comment by Hashifier** [comment]
@ecdsa What's weird is when I enter my seed and press next nothing happends, the page just turns blank.

**Comment by ecdsa** [comment]
that's probably a display refresh bug

**Comment by ecdsa** [comment]
closing, no answer
