### ISSUE TITLE
tor proxy setting does not stay selected

### ISSUE THREAD

**Issue by raedah** [spesmilo/electrum#2747]
When selecting Use Tor Proxy in the Gui from Tools->Network, settings are not saved after app restart and need to be reselected.

**Comment by SomberNight** [comment]
To be more specific, and as the underlying cause, in the Network options, changes to "auto_connect" and "proxy" settings only get saved (or rather, persisted to disk) if "server" (host address/port/protocol) also gets changed.

**Comment by ecdsa** [comment]
fixed in a22cf973b4a43ef03ef08d8d6fa576fb35221a29
