### ISSUE TITLE
Sweeping Mini Private Key defaults to Compressed [bug][enhancement]

### ISSUE THREAD

**Issue by cluelessperson** [spesmilo/electrum#2748]
I had a user with multiple Casascius coins unable to sweep the mini key in electrum.  It seems electrum assumes the mini keys use compressed keys, and derive addresses with no amounts on them.

Mini Private Key -> RAW key -> WIF(**compressed**) = Wrong WIF -> Wrong Pub -> Wrong Address
Mini Private Key -> RAW key -> WIF(**UNcompressed**) = Right WIF -> Right Pub -> Right Address

It would probably require checking the contents of both compressed and uncompressed keys to determine which to actually sweep, or easier still, allowing the user to check a flag for uncompressed.

---

We wound up using an external tool to convert the mini private key to an uncompressed WIF key, then imported THAT into electrum.  :)

**Comment by ecdsa** [comment]
this is an issue with the mini private key format.
it is probably out of scope for us to fix that.

**Comment by ecdsa** [comment]
we could add a button in the gui, as a workaround

**Comment by SomberNight** [comment]
Note: I'm currently experimenting with this and it seems Electrum 2.9.3 assumes uncompressed pubkeys for minikeys, while Electrum 3.0.1 assumes compressed pubkeys.
