### ISSUE TITLE
Electron cash 2.9.2 History and Balance problem

### ISSUE THREAD

**Issue by VaanG** [spesmilo/electrum#2749]
I did create wallet for bitcoin cash , followed the instruction correctly ,used my 12 security words from bitcoin wallet. Now I got bitcoin cash wallet  , but it has no history in it and balance is 0! On my bitcoin wallet I had 0,27 btc at 1 of august 2017. What's wrong here? Any suggestion?

**Comment by bauerj** [comment]
Electrum is not a BCH wallet.

**Comment by VaanG** [comment]
It is bitcoin cash wallet.

**Comment by bauerj** [comment]
No.

**Comment by dabura667** [comment]
https://github.com/fyookball/electrum/issues

Please follow the link above to post ossues for "Electron Cash"

"Electrum" is not a Bcash wallet.
