### ISSUE TITLE
Btc addresses generated but btc never received (not a synchro prob)

### ISSUE THREAD

**Issue by khan69** [spesmilo/electrum#2761]
Hello
this is the third time i use eletrum and i have this problem.
It simple i paste the btc address for receiving my btc but btc are never received and the transactions are with status unrelated to your wallet???
WTf??
1 time ok but 3 just no way ! i tried to restore many times and nothing, its all synchronised the problem is not that. The addresses are not anymore in the address section so what?
please a response. i've seen this topic and i hope this is not scam .

https://wordpress.org/support/topic/scam-unknown-btc-addresses-are-generated-funds-never-received-on-electrum/

as you can my btc are still on those addresses:
https://blockchain.info/fr/address/1APd9sDV27Ftgi8KdygvViETy4rHZMz5cG
https://blockchain.info/address/1JJy1npBfxg14TS22YptB5WZb5q4qtgLxQ

**Comment by ecdsa** [comment]
it is very likely that you or the wordpress plugin messed with the gap limit.
please learn how that plugin works.
we are not the distributor of that plugin, and we are not offering support for it.

**Comment by khan69** [comment]
where do you read me talking about a plugin ? my problem is the same about addresses generated with funds i cannot touch. so now my btc are lost thanks to electrum?

**Comment by khan69** [comment]
where do you read me talking about a plugin ? my problem is the same about addresses generated with funds i cannot touch. so now my btc are lost thanks to electrum? 

----- Mail original -----

De: "ThomasV" <notifications@github.com> 
À: "spesmilo/electrum" <electrum@noreply.github.com> 
Cc: "khan69" <benitez69@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 16 Août 2017 22:24:59 
Objet: Re: [spesmilo/electrum] Btc addresses generated but btc never received (not a synchro prob) (#2761) 



it is very likely that you or the wordpress plugin messed with the gap limit. 
please learn how that plugin works. 
we are not the distributor of that plugin, and we are not offering support for it.

**Comment by ecdsa** [comment]
you posted a link to the wordpress plugin.

**Comment by ecdsa** [comment]
please provide a better explanation of your problem.
without precise information it is difficult to guess.

**Comment by khan69** [comment]
simple
someone sent me some btc to the address i found in : receiving address
then i closed my electrum, when i opened it again, the address is gone. i dont see the address anymore. 
the btc ares still on the adress but i cant spend them

**Comment by khan69** [comment]
thanks for help

**Comment by ecdsa** [comment]
will you please post precise information? 
what's the receiving address, transaction ID?

**Comment by ecdsa** [comment]
you probably have some malware that modifies the bitcoin addresses in your clipboard.
please test if bitcoin addresses are modified when you copy-paste them

**Comment by khan69** [comment]
here are the adresses reiceiving the funds
https://blockchain.info/fr/address/1APd9sDV27Ftgi8KdygvViETy4rHZMz5cG
https://blockchain.info/address/1JJy1npBfxg14TS22YptB5WZb5q4qtgLxQ

**Comment by khan69** [comment]
i was thinking too about it but nothing after virus check and copy past works

**Comment by ecdsa** [comment]
for me that remains the most likely explanation, given the information you provide.

**Comment by khan69** [comment]
bizar...i downloaded the soft on the official website. i checked my pc nothing on it.
i think i just have to open a blockchain account or something else but never again electrum.
thank you for your answers
