### ISSUE TITLE
LOW FEE Transaction Unconfirmed

### ISSUE THREAD

**Issue by alexbritoab** [spesmilo/electrum#2763]
Hello! Today FaucetHub sent me a payment of 33303 Satoshis and they placed the Fee of 300 Satoshis. When I get to my electrum wallet I get in that "Unconfirmed" and "Low Fee" status in the Date column.
What I can do?
Help!

**Comment by AbdussamadA** [comment]
ask for help in the [forum](https://bitcointalk.org/index.php?board=98.0). this place is only for bug reports and development related discussion.
