### ISSUE TITLE
One transaction blocked ...

### ISSUE THREAD

**Issue by maxlasco** [spesmilo/electrum#2766]
Hello,

I have one transaction with 32 confirmations but It does not appear on my electrum wallet ... btc address is correct ( I double checked ).

What's happen ? What can I do ?

**Comment by ecdsa** [comment]
post the address and a screnshot of your wallet's address list

**Comment by maxlasco** [comment]
It is ok, Transactions is arrives with 2 days laters ... I don't know why!

I just change servor automatically several times.

Thanks for all!!
