### ISSUE TITLE
2fa - SIGHASH-FORKID Issue - 100USD reward

### ISSUE THREAD

**Issue by Regipl** [spesmilo/electrum#2767]
Hi

I have a issue when i try to send my BCH to a new address. I know the reason is my 2fa wallet and the option is to restore/create a new one using the seed words but i do not have my seed words for this wallet.

I have only access to my encrypted wallet file, private keys and the google code/phone. Any options?

Will this 2fa be fixed in some future Electron versions?

I can correctly sign a transaction the only issue is with broadcast..

thx

**Comment by ecdsa** [comment]
please do not post this here; this repo is about Electrum
