### ISSUE TITLE
Electrum doesn't start when path to executable contains space

### ISSUE THREAD

**Issue by TheodorD** [spesmilo/electrum#2769]
I am having an Issue where, every time I put the executable for electrum into a folder with a space in the name, or a subdirectory, the application does not start, and does not throw any errors.
When this is done to a wallet, electrum will simply say the wallet "isn't there" and give me the option to create a new one (possibly **overwriting** the old one)

This Issue only happens, when the folder is on a partition other than C: , but only if that partition is on the same physical hard drive than the operating system.
The hard drive this was tested on is split into three partitions: C; D; F:.
The application launches on C:, yet not on D: or F:.
On any partition of any other connected hard drive, as well as on any network drive, it works fine.

Tested environment:
Windows 10 Pro x64
MBR Hard Drive (1TB WD Green)
NTFS Partition (730GiB)

**Comment by ecdsa** [comment]
this is fixed in master, wait for 3.0 release
