### ISSUE TITLE
Latest ElectronCash 2.9.2 holding my money, not letting me send it. 

### ISSUE THREAD

**Issue by RIPAC** [spesmilo/electrum#2771]
I finally figured out how to get my BCC off a paper wallet, now only to have it stuck in my Electron Cash wallet. 

I read around and people are suggesting to disable 2fa, fine. I can create a new wallet to do this, but I can't transfer funds to it apparently. My current one with 2fa doesn't seem to have a way to turn off the 2fa.

So is my BCC stuck forever or can someone help to fix this?

**Comment by ecdsa** [comment]
read the docs

**Comment by dabura667** [comment]
Google searched "Electrum recover 2fa account" and it sent me here: http://docs.electrum.org/en/latest/2fa.html#restoring-from-seed

10 seconds of my day were just lost :-P

**Comment by RIPAC** [comment]
Sir, can I pay you to help me? Don't waste time on things if you're not trully going to help, but if you want to and your just grumpy, then help me. I have my BCC confirmed in a 2fA secured "ELECTRON CASH" wallet, not Electrum, when I tried the directions and started a new wallet using my Electron Cash seed, it actually created a wallet, but nothing was in it. It was marked for BTC, not BCC and I have no idea how to get my BCC off of Electron Cash or if possible, my old paper wallet I was holding BTC on when the fork happened. Is that possible? Can my Electron Cash wallet be hacked open and BCC retrieved with my seed and password info? Are they going to release an upgrade? Any ideas anyone? I have about $1000 in there right now of BCC and Electron Cash gives an error everytime I go to add my 2fA to send it to my exchange or other Electon Cash wallet without 2fA.

**Comment by RIPAC** [comment]
What docs exactly do you speak of ecdsa? Electron Cash has no docs on their website so what docs are you speaking of? Thanks for the help. I will happily pay someone some of my BCC should I be able to recover it and send it to my exchange or a better BCC wallet that will let me spend it.

**Comment by ecdsa** [comment]
I am talking about the two statements about BCC that are displayed on electrum.org, and about the documentation about 2FA wallets in the electrum documentation.

If you had read the documentation about Electrum 2FA, you would know that it is possible to disable the cosigning in a 2FA wallet.

If you had read the BCC statements, you would understand that we are not Electron Cash, and that we do not provide support for software that does not come from us, that we do not endorse, and that we consider as dangerous.

**Comment by dabura667** [comment]
@RIPAC Electron Cash (BCC wallet) support can be done through this link:

https://github.com/fyookball/electrum/issues
