### ISSUE TITLE
again problem wiht electrum

### ISSUE THREAD

**Issue by stanch3vv** [spesmilo/electrum#2772]
i have 15 mbtc, my fee is around 0.0006, and i can not send more than 11 MBTC .Take a look on the photos
![1vairant](https://user-images.githubusercontent.com/28753352/29449353-09546022-8403-11e7-8ee5-21d55c9eacf9.png)
![variant 2](https://user-images.githubusercontent.com/28753352/29449365-0efab1b6-8403-11e7-8c2a-8964c52260cd.png)

**Comment by ecdsa** [comment]
I think the fee should be visible by default in the send screen, or we will keep getting messages like that

**Comment by stanch3vv** [comment]
no,the fee is not visible on the second pic, but when i try with lower amouth i see the fee is around 0.0006 and i can make the fee hier or lower, it depends how fast transaction i want.I belive this is really kind of bug, no other explanation

**Comment by XingZheZ** [comment]
A bug? Are you sure ?

**Comment by stanch3vv** [comment]
Give better explanation....i have 15mbtc and i can not send 12+ 0.0006 fee

**Comment by stanch3vv** [comment]
no one have idea whats going on????

**Comment by umsiddiqui** [comment]
same issue, please help!!!!

**Comment by ecdsa** [comment]
0.0006 is probably your fee/kb, not the fee for this transaction

**Comment by stanch3vv** [comment]
No , this is the all fee....and if you use electrum ,you should know that...Electrum show the full fee.

**Comment by stanch3vv** [comment]
i know how hight is the fee cause i have done many trasnactions

**Comment by ecdsa** [comment]
what do you get if you click on 'max'?

**Comment by charleshsu168** [comment]
@stanch3vv 
go to preferences and enable edit fee manually.
then you can see exactly how much fee is.
 by default, it's hidden. So I always turn this on manually

**Comment by stanch3vv** [comment]
yes that helped, thank you
