### ISSUE TITLE
I can´t open with the password and I for gotten the seed

### ISSUE THREAD

**Issue by Samira888** [spesmilo/electrum#2775]
I can´t open with the password and I for gotten the seed, It´s horrible.
Thanks for help me

**Comment by ecdsa** [comment]
if you forgot the password and the seed, then you lost your bitcoins.
the only thing you can do is to try to remember your password

**Comment by Mackklarson** [comment]
the only option for you is to brute-force your password. you can send me message if you need help 
anywalletrecovery (at) gmail (dot) com
