### ISSUE TITLE
SIGSEGV on HW wallet create

### ISSUE THREAD

**Issue by almindor** [spesmilo/electrum#2776]
If I try and create a new standard/hw wallet Electrum just crashes with a segmentation fault.

I have a TREZOR device, but it happens if it's plugged in or not, it doesn't even get to any actual trezor-specific setup.

OS: Arch/Antergos/x86_64
Electrum version: 2.8.3

**Comment by ecdsa** [comment]
before opening an issue here, please use a recent version
