### ISSUE TITLE
Electrum send 0,01 automatic to an unknown BTC wallet.

### ISSUE THREAD

**Issue by Sellerbull** [spesmilo/electrum#2777]
Please help me.
I send 0,026 BTC to my Wallet. Only 0,016 come and 0,01 was sent to an unknown wallet. Where is it gone??

**Comment by ecdsa** [comment]
post transaction id

**Comment by ecdsa** [comment]
is this a wallet with two-factor authentication? 
it looks like the prepaid fee for 100 transactions

**Comment by ecdsa** [comment]
closing, no answer

**Comment by Sellerbull** [comment]
So sorry for the late answer. Yes, the wallet have two-factor authentication. So the payment is right?

**Comment by ecdsa** [comment]
two-factor authentication is a paying service by Trustedcoin. 
you should have seen this information during the wallet creation procedure.
click on the trustedcoin logo to see your payment preferences.
