### ISSUE TITLE
Electrum doesn't allow 8digit decimal for mBTC

### ISSUE THREAD

**Issue by umsiddiqui** [spesmilo/electrum#2779]
Hi, 

I have 109.28562mBTC as balance. When i try to SEND, electrum only allows 0.10928. How to fix this?

Because of this one of my payments is pending full payment.  **Please** help!!!

**Comment by AbdussamadA** [comment]
ask in the forums and they'll educate you about the divisibility of bitcoin:

https://bitcointalk.org/index.php?board=98.0

this place is for development related matters not general support issues.

**Comment by ecdsa** [comment]
because of the mining fees
