### ISSUE TITLE
Feature Request: German word list (and some related questions)

### ISSUE THREAD

**Issue by prof7bit** [spesmilo/electrum#2780]
I have seen there are some other than English language word lists already in the repository.  Would it be possible to add a German word list if I (or someone else) provides a pull request with this file? Would this also require changes in other areas of the code?

Related questions:
If just replace the English word list with a German word list in my own copy of Electrum and make no other changes, would it be able to generate a working seed? If so, would this seed also be able to restore the wallet in a standard installation of Electrum that does not have this private word list installed?  And even if it worked now, would it be guaranteed to work in future versions too?

**Comment by ecdsa** [comment]
it would work, but the android version requires a seed generated with the English wordlist.
that's why we will not add other languages for the moment
