### ISSUE TITLE
Bitcoin Cash sent to Electrum

### ISSUE THREAD

**Issue by renedegrootfr** [spesmilo/electrum#2783]
Hi, without knowing Electrum doesn't support BitCoin Cash, I sent money to my Electrum Wallet. Now, on their website, I read this:

"How to redeem my BCC?
---------------------
BCC wallets will require you to import your seed or your private keys,
which can be exported from Electrum. Doing so will expose all your
Bitcoin funds associated with that seed to the BCC wallet you decide
to use.
Therefore, *after* the BCC fork, but *before* you enter a seed or
private key in a BCC wallet, you should move all your funds to a new
Electrum wallet, with a new seed. You will still be able to use the
old seed or private key with BCC, because BCC has replay
protection. Wait until your funds are confirmed in your new Bitcoin
wallet, before you enter the old private key in a BCC wallet. This
will protect your BTC funds from rogue/untrusted software."

Now,can anyone help me how I can possibly recover what I sent to my Electrum wallet, but will never arrive since they don't support BitCoin Cash?
This was my order: (from litebit.eu):
Order ID | LB360549
-- | --
Date and Time | 19-08-2017 16:36
Coin | Bitcoin-Cash
# | 0.09511400 BCC
Amount | €74.34
Receiving address| 19bZojZ7HxpmUefQ2FE5MzNUp3Mu7hPJex
Network ID (txid) | a278edde0b8dc40cb6f775a26a86d46d42463caf5923b0476fed6397a11810b8

Thank you so much,
Sincerely, René de Groot

**Comment by fireduck64** [comment]
If you look on an explorer that supports both you can see that address has a balance on both Bitcoin and Bitcoin Cash.
https://blockchair.com/search?q=19bZojZ7HxpmUefQ2FE5MzNUp3Mu7hPJex

The Bitcoin Cash funds can be accessed by a client other than Electrum.

You can use electron cash from http://electroncash.org/#downld

As always, you should absolutely check the signatures with GPG.  This doesn't guaranty that the binary is safe, but it does guaranty that the author has actually created that binary.
