### ISSUE TITLE
UI Feature Request: Color the input boxes for send amount and fee differently

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#2788]
I got confused today because the text inside the USD amount field was blue, and the fee btc was blue, and because the colors were the same (and the text for the btc amount was different), I associated the usd amount and btc fee together and was just about to file a bug that the fee was labeled as in USD. I think it would make sense to color code the controls subtly to associate the correct items together.

For example, color the border of the btc amount input field, fiat amount input field, one color (say rgb(0,120,)) and color the border around the fee slider tab and border around the btc fee amount another color (say rgb(120,0,0)).

It probably also makes sense to align those text boxes so the BTC amount and BTC fee are vertically aligned - that associates them on another angle (BTC vs fiat). The slider bar should appear either above or below the BTC fee text field, not to the side of it.

**Comment by ecdsa** [comment]
not relevant anymore: the fee is set on a separate dialog now.
