### ISSUE TITLE
Error when running ./contrib/make_packages

### ISSUE THREAD

**Issue by linuxdaddy** [spesmilo/electrum#2790]
Hello, i am installing Electrum on Kali Linux. Everything is updated, and i'm facing this error:

![screenshot from 2017-08-23 03-27-54](https://user-images.githubusercontent.com/26394383/29594742-46d2c1a6-87b3-11e7-92c0-b7a4ce5fb03b.png)

Waiting on reply. Regards!

**Comment by charleshsu168** [comment]
see this fix. https://github.com/spesmilo/electrum/issues/2294
