### ISSUE TITLE
What do users of electrum have to do to take advantage of segwit?

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#2791]
Segwit is coming out tomorrow. I've heard ([from here](https://bitcoincore.org/en/2016/10/27/segwit-upgrade-guide/)) that wallets must generate P2SH addresses (that start with a '3') in order to use segwit. But all the addresses I see generated in my Electrum start with '1'. Is there anything users have to do to start using segwit? Could something be added to the readme or website to clarify to users what they need to do, if anything, for segwit?

I've checked through a bunch of commits, but nothing makes it clear to me how segwit will be usable: 
* https://github.com/spesmilo/electrum/commit/f7096010f08c3567f6fc473f2013767ccd809336
* https://github.com/spesmilo/electrum/commit/6bd66279b0e808d2f823bec8261d90dd71165d65
* https://github.com/spesmilo/electrum/commit/9c70540a2fe04019975aa945a3aa5fe4d6efe7e1
* https://github.com/spesmilo/electrum/commit/aed2b04dbdb6d52e3db42b15e7dffc7c220e7b76
* https://github.com/spesmilo/electrum/commit/d5ab8f82f2f9a302d6d958de0a0c58f7abbdeaa3
* https://github.com/spesmilo/electrum/commit/af54ba023bd67ba9a3321b23e079b145370732bd
* https://github.com/spesmilo/electrum/commit/ce11a2fac5ec4d79de48058069042a48ad3eae0a
* https://github.com/spesmilo/electrum/commit/3a64ec0f2ed9c845b5c01daa07fafcbfa26c3cb7

**Comment by SomberNight** [comment]
The current release (2.9.3), or the master branch, does not yet have segwit ready to be used on mainnet. It can only be used on testnet at the moment (as evident in the commits you referenced, such as af54ba023bd67ba9a3321b23e079b145370732bd).

I believe p2sh-p2wpkh type addresses (the successor of p2pkh, the current '1' type addresses) are fully implemented, but p2sh-p2wsh addresses (which would be needed for e.g. multisig) are not.

Hence, most users will **need to wait for a new release** of Electrum that at least enabled the currently implemented functionality on mainnet, and **then create new "segwit" type wallets** (to clarify, this means a wallet with new "seed words", as the current code implies that a wallet having segwit addresses is a [property of the seed](https://github.com/spesmilo/electrum/blob/2.9.3/lib/bitcoin.py#L233-L234).

**Comment by fresheneesz** [comment]
@SomberNight Thanks for the information. Mind if I add that info to the readme for this project? If that's not the right place for it, where can I add it?

**Comment by ecdsa** [comment]
soon

**Comment by fresheneesz** [comment]
@ecdsa Cool, but many users (myself included before this thread) are probably assuming Electrum will support Segwit. I think users should have the info, about how segwit will be dealt with, now (ie regardless of how soon support might happen). How can I help make that happen? 

I'm actually surprised p2sh-p2wpkh addresses weren't made the default like a year ago - my understanding is that its been about that long since we've known users will need updated addresses to use Segwit. Had that been done, most people now might not even have had to switch to a new wallet. Electrum is a popular client and getting users on Segwit is important to get people on segwit and lower fees so the community will stop yelling about how they can't buy coffee or whatever.

**Comment by SomberNight** [comment]
> I'm actually surprised p2sh-p2wpkh addresses weren't made the default like a year ago

Coins sent to a p2sh-p2wpkh address **before SegWit** activation are spendable upon presenting the redeemscript without a valid signature. They are only protected by the hash algorithm of p2sh. That is, anyone that can present a script that has RIPEMD160(SHA256(script)) "==" address, can spend from that address. If you tried spending those coins, you would need to reveal the redeemscript, and rational miners would forge their own tx instead of including yours in their block, and steal your coins. This is the basis of all the "anyone-can-spend" "FUD" "segwit-haters" argued for months.

So that is why

> p2sh-p2wpkh addresses weren't made the default like a year ago

**Comment by fresheneesz** [comment]
Ahh, I didn't know that. Thanks again for the helpful info @SomberNight !

**Comment by bainsmit** [comment]
Hello,
As a user of Electrum I must confess that I am a little confused. As I own an wallet with addresses starting to 1 (no other is currently possible but that) I am wondering will they be fully functional in the future (I do understand that they will exist but I do not understand how transactions will be concluded between segwit and now segwit addresses. Will it be like for now or not and if many adopts segwit will there be a problem with  confirmation of transactions for old addresses, also will receiving and sending be possible with old addresses to new one and vice versa)?.

I do realize that this are noob questions but I can not find too many straight answers...

**Comment by fresheneesz** [comment]
@bainsmit Your addresses starting with 1  will remain fully functional in the foreseeable future. You can send between segwit and non-segwit addresses in both directions.

**Comment by Engelberg** [comment]
Trezor now supports segwit.  If I create a hardware wallet type in Electrum using the Trezor, will Electrum automatically see and support the segwit addresses?

**Comment by fresheneesz** [comment]
@Engelberg Its not quite automatic, but not difficult. Here's the guide I used to setup my Trezor through electrum: https://blog.trezor.io/using-trezor-with-electrum-v3-a0b9bcffe26e?gi=96884803f8fc
