### ISSUE TITLE
Invalid interface to SNW_SERVICE  is logged after start, not sure if the wallet yet connected.

### ISSUE THREAD

**Issue by CasaSky** [spesmilo/electrum#2794]
I am a new user of electrum wallet and i don't if my wallet is connected to the blockchain.
Here is my log: 
```
~ $ cd Electrum-2.9.2/
~/Electrum-2.9.2 $ ./electrum 
"sni-qt/15347" WARN  23:17:54.303 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
```

After starting electrum the warning message below is logged.
I don't know if i can ignore this warning. I also don't know if Electrum is connected to the blockchain. I don't see any Blocks like other wallets. Here is a screenshot.

![electrum](https://user-images.githubusercontent.com/12476711/29639554-62b4c524-885b-11e7-803b-8d679b16cdca.png)

Any advice?

**Comment by ecdsa** [comment]
you are connected. that warning is harmless.
