### ISSUE TITLE
Electrum transaction was rejeted by network rules (64: dust)

### ISSUE THREAD

**Issue by Shuwn6** [spesmilo/electrum#2795]
Hello ! I have a big problem I can not send money, when I try to send it says: error the transaction was rejected by network rules (64: dust) ... I have visited several forums and tried all the server ! But nothing makes it become annoying
Sorry if my english is not perfect

**Comment by fresheneesz** [comment]
I've seen this issue when I was transferring BCC using Electron Cash (a bcc clone of Electrum). The issue, I think, was that I had sent a transaction very recently, and Electron Cash used the change output of that transaction as the input for the next transaction - but the node I was connected to didn't have the first transaction in its mempool. So if you wait a few minutes, this problem should disappear.

**Comment by Shuwn6** [comment]
The problem is actually solved all alone thank you for your reply!
