### ISSUE TITLE
Close Validation Error: Error #-25: Missing inputs

### ISSUE THREAD

**Issue by PijushS** [spesmilo/electrum#2796]
I am not able to do any transaction .. not able to transfer BTC getting error "Close Validation Error: Error #-25: Missing inputs"
How to resolve it

**Comment by ecdsa** [comment]
you are trying to spend coins already spent.
check that you are connected to a server that is not lagging.

**Comment by PijushS** [comment]
@ecdsa
 I am trying to send and it window wallet of blockchain.info
