### ISSUE TITLE
Transaction fees

### ISSUE THREAD

**Issue by Oceane83** [spesmilo/electrum#2802]
Hello, 

I don't understand how transaction fees work on the electrum wallet. I wanted to send btc for €41 and the received received only for €31.
On the order detail, there were aproximately 30% of transaction fees. I find that these fees are extremely high. I've always had fees on my transcactions (I've made 2 transactions before this one) and the fees haven't been this high. 
Can you explain me these fees ? 

Thx

**Comment by gits7r** [comment]
The fees are not dependent on the amount you send in BTC or $. The fees are dependent on the number of inputs you are trying to spend (in simple terms depends on how many transactions you received that compose the amount you are trying to spend). It is a lot cheaper to spend 10000$ that were received in a single transaction (one input) versus spending 25$ received in 3 separate incoming transactions.

**Comment by charleshsu168** [comment]
what's the transaction id on block explorder? maybe the electrum's dynamic fee calculation is too high?
