### ISSUE TITLE
Somethng wrong with my Electrum wallet version 2.9.3

### ISSUE THREAD

**Issue by electrumuser90** [spesmilo/electrum#2804]
Hello , i have some problems using my wallet , this happend 2 day`s ago and still continue , at first all my transaction  is  status like : Low Fee , Unconfirmed Parent , and etc , I make all as its should Dynamic fees , Propose replace ": Always, im waiting atleast 2  days , also the fee`s for sending money is bigger than ussual ,  i try to withdrall 100$ and the fee was like half from 100$ ? please tell me whats going on ?

**Comment by gits7r** [comment]
There is too little information to help. In order for us to tell you if the fees are too high you need to tell us the number if inputs you are trying to spend, not the amount in $ or BTC. In simple terms how many transactions you received that compose the amount you are trying to spend? Also, dynamic fees have a slider best set it to "within 5 blocks".
