### ISSUE TITLE
Support for native SegWit address format, implement BIP 173

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#2805]
Now that we have SegWit active, we need to take all the advantages that it provides. These include native SegWit address format + new P2WSH (pay-to-witness-script-hash, the legacy P2SH) that provides 256-bit hash vs. 160-bit hash which is quite nice.

The spec is here: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

This needs to be implemented in two distinct parts:
1. To be able to validate such addresses and accept / use them in "Send" tab and "Pay to Many" fields. This should be simple.

2. Have these type of addresses in the wallet for both receiving and change. Given that the migration will not be instant in the entire ecosystem, maybe it makes sense to not add a new seed version that will make this feature optional unless the user creates a totally new different wallet. Instead, the keys that result from the older seeds will also be mapped to new address format and maintain the legacy format at the same time (for cases where the sender can only accept a legacy address).

**Comment by dabura667** [comment]
The legacy address concern is solved by using P2SH to mask the P2WSH or P2WPKH.

But, iirc, Electrum servers need to be fixed to index the new addresses as well... otherwise it's useless.

**Comment by gits7r** [comment]
Yes, for sure. Opened issue 234 also on ElectrumX so this is taken care of from both sides.

**Comment by ecdsa** [comment]
see https://github.com/kyuupichan/electrumx/pull/243

**Comment by ecdsa** [comment]
@gits7r BIP173 is implemented in the native_segwit branch
The new seeds will be used to derive native addresses, not P2SH addresses. 
Segwit will be opt-in at seed creation, until the ecosystem has more support.

**Comment by ecdsa** [comment]
this is merged now
