### ISSUE TITLE
Next option does not activate after copy of multibit private keys info .....

### ISSUE THREAD

**Issue by earfling** [spesmilo/electrum#2806]
HI ... I am trying to import some private keys that were previously held within Multibit classic however once pasted the 'Next' option does not activate, same issue for Sweep too. I am using Electrum version 2.9.3, any ideas? Thanks

**Comment by ecdsa** [comment]
do they have the same format as electrum private keys?

**Comment by earfling** [comment]
Hi Thomas

Thanks for coming back, issue was due to invalid private keys, I restored
my multibit wallet again and it worked

Have a good one
