### ISSUE TITLE
Problem with seed portability

### ISSUE THREAD

**Issue by thekrugers** [spesmilo/electrum#2812]
With a wallet generated in version 2.8.3 on Windows, I seem to be unable to import the seed in version 2.9 on Android. The Next button remains grayed out, whether I type the seed or scan the QR code from the Windows version.

Is there a compatibility issue or a documentation/on-screen info issue?

**Comment by ecdsa** [comment]
no, there is no difference.
you probably made a mistake typing the seed.

**Comment by thekrugers** [comment]
And did the QR scanner also make a mistake scanning the QR code generated by the Windows version of the application?

I went the typing route three times, then I scanned the QR code and checked that the seed it scanned was identical to the one generated on Windows, three times. The Next button does not become available.

**Comment by ecdsa** [comment]
Also, you cannot scan the seed, you must type it manually. 
This is because scanning the seed would leave a trace in the history of the QR scanner application.
So, if you used the "use public or private keys" screen, it will not let you to the next screen.

**Comment by ecdsa** [comment]
if you really cannot type your seed in the android app, please move all your coins to a new wallet and send me the seed by email, I will have a look. 
Do not send the seed before you move your funds to a new wallet; I do not want to be responsible of your funds.

**Comment by thekrugers** [comment]
I tried with a newly generated seed, the Next button became available and the app locked up when I tapped it. Then I went back and tried again with the existing seed and it seems to have worked this time.
