### ISSUE TITLE
HELP: Electrum balance 0. Fees on preview not matching with prescribed fees!!

### ISSUE THREAD

**Issue by joefloggs** [spesmilo/electrum#2814]
I just sent bitcoin to activate a ripple account. I changed the fee to an acceptable one as screenshot below

<img width="899" alt="screenshot 2017-08-28 15 35 22" src="https://user-images.githubusercontent.com/31411695/29778231-8dcb9b44-8c06-11e7-81ff-f7ba28b9d704.png">

I noticed that the transaction was confirmed straight away - which I found odd. I then saw in blockchain explorer that my wallet balance was zero!!!  Checking blockchain explorer I could see that the fee was rediculously high!

https://www.blocktrail.com/BTC/tx/8d357f159823cc2380616db42915ad89d988b1e631588c039d1265602ed893e2

My electrum wallet shows this in the history screen which is what I expect

<img width="1170" alt="screenshot 2017-08-28 15 37 31" src="https://user-images.githubusercontent.com/31411695/29778307-d1b6ab3c-8c06-11e7-9c8b-9248b2e9798d.png">

So I started to panic. The two things didn't marry up, I put in a fee of about £1.22 and my balance seems to be zero on the blockchain, 0.15BTC on electrum. So I tried to re-trace my steps

This time I clicked the preview button. Note below how the outputs completely do not match the expected transaction + fees!

<img width="992" alt="screenshot 2017-08-28 15 39 19" src="https://user-images.githubusercontent.com/31411695/29778382-1e073966-8c07-11e7-8593-fc6cc1d01a4c.png">

Guys - what the hell is going on here?? The only thing I did different here was to change the base unit from MBTC to BTC! I'm beginning to think that Electrum put the fee as the maximum in my wallet and then sent it!!!

**Comment by joefloggs** [comment]
<img width="1214" alt="screenshot 2017-08-28 15 41 20" src="https://user-images.githubusercontent.com/31411695/29778455-59a45eb8-8c07-11e7-96ad-5a1af5c6203e.png">

better screenshot

**Comment by ecdsa** [comment]
google "bitcoin change address"

**Comment by joefloggs** [comment]
Thank you - I feel really stupid now
