### ISSUE TITLE
I have thousands of addresses in wallet, I want to get notify when any of the addresses have been changed, how to do?

### ISSUE THREAD

**Issue by hcaihao** [spesmilo/electrum#2816]
Method1: I don't know how to let the electrum notify me. Will I need call "electrum notify address url" thousands times?

Method2: I try to modify "receive_tx_callback" function to report current transaction, but how to get the address info?

Help pls!

**Comment by ecdsa** [comment]
what is your use case?

**Comment by hcaihao** [comment]
I assign every user an address in my website to receive funds. I need know the transaction immediately.

**Comment by hcaihao** [comment]
@ecdsa Help pls!

**Comment by ecdsa** [comment]
there is currently no global notification. you can try to modify the code in synchronizer.py
