### ISSUE TITLE
Electrum can not run on Windows 10 64 bit system

### ISSUE THREAD

**Issue by Demi7** [spesmilo/electrum#2818]
I clicked and clicked and clicked... and they do not seem to respond at all:

electrum-2.9.3.exe
electrum-2.9.3-portable.exe

**Comment by dabura667** [comment]
Works fine for me.

Where did you download them from and did you verify the signatures?

**Comment by Demi7** [comment]
It's solved. I delete a "$" sign in the directory name (laugh at me) and it works now.
