### ISSUE TITLE
Lost BTC

### ISSUE THREAD

**Issue by aleksei-belka** [spesmilo/electrum#2827]
Hi! I send 0.00216956 BTC on the wallet 17ghieC6RhbNSNDcY4eMUmcbfPv7Aa3C36. But I getting 0.00016956 BTC and 0.002 BTC on the unknown wallet 1DT1PJo2bmc8cErtsyZQcc41GFN15rhBNk. Why ? Please help me !!!

**Comment by ecdsa** [comment]
I guess you have a two-factor authenticated wallet, and this 2mBTC is the fee for 10 transaction.
That fee was displayed in the GUI confirmation dialog when you made the payment.
