### ISSUE TITLE
when changing unit of currency + enabling dynamic fees slider offers retarded options

### ISSUE THREAD

**Issue by blowjobs4btc** [spesmilo/electrum#2828]
If you switch units between bit, mbtc or btc in preferences, and also have dynamic fees enabled, if you go to send btc, the slider has insanely low fees, even if you slide it all the way to the right.

 Now I have $1100 floating in the mempool, despite using the highest possible fee on the slider, it still only came out to 100 sat/B 

TX:
https://blockchain.info/tx/1a6a31ff2822f9d3404bd3edc6951274c44960c0eb7724d271596cb77567a180 

maybe inanely low fees shouldnt be n option because I doubt this will ever mke it to the blockchain

CentOS / 2.7.17 

Also, got Segwit?

**Comment by blowjobs4btc** [comment]
Not sure if this is  a bug or if im just a moron (probably the latter) but it shouldnt allow you to send a transaction with 0% chance of ever getting mined, no matter how hung over you are or how much coffee you have had

**Comment by ecdsa** [comment]
2.7.17, really?

**Comment by blowjobs4btc** [comment]
dont hate me cause you aint me. Im also headbanging to MC Hammer in my parachute pants. 

This is the version that came with CentOS7 and yum update doesnt update it to the newest rev

**Comment by blowjobs4btc** [comment]
Ok, downloading 2.9.3 sorry lol
