### ISSUE TITLE
How to load wallet on Win Gui?

### ISSUE THREAD

**Issue by AugerSoft** [spesmilo/electrum#2830]
Hello! 
I'm trying to use JSON RPC on Windows. 
I"m execute this comand
> C:\Program Files (x86)\Electrum>electrum-2.9.3.exe daemon load_wallet -w K:\electrum_data\wallets\default_wallet

But after this, i'm send new request to eletrum and get error...

`{"error": {"message": "Server error:   File \"C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI37002\\lib\\commands.py\", line 306, in getbalance | AttributeError: 'NoneType' object has no attribute 'get_balance'", "code": -32603}, "jsonrpc": "2.0", "id": 99}`

How load wallet on windows?

**Comment by ecdsa** [comment]
if you load it with -w, you probably need -w for the other commands
