### ISSUE TITLE
Stored MAID in electrum with 2fa, need help

### ISSUE THREAD

**Issue by Usogeking** [spesmilo/electrum#2831]
I was stupid enough to store MAID in my electrum wallet using 2fa, so the address I have my MAID on 3Jnz4bDfgmB9DYiZkxZ....... does contain the MAID according to www.omniwallet.org, but the corresponding private key does not and shows this address : 1Jgt1MzurJrTHByGmBdhLc..... 

I know this address (3Jnz4bDfgmB9DYiZkxZ.......) does not have a single private key (but multiple or something) which makes me wonder how I will ever retrieve the MAID on it, or is it just locked up in my wallet forever?

**Comment by dabura667** [comment]
You can recover all keys necessary. The question is: is there a multisig omniwallet you could import to?
