### ISSUE TITLE
Daemon not reading config file

### ISSUE THREAD

**Issue by glerbo** [spesmilo/electrum#2839]
I'm having trouble with the Electrum 2.9.3 Daemon not reading the config file.

`electrum daemon start --testnet`
`electrum daemon load_wallet -v --testnet`

I get the message:

`[SimpleConfig] electrum directory /home/me/.electrum/testnet`
`Warning: Cannot read config file. /home/me/.electrum/testnet/config`

This is the permissions on the file:

`ls -lash ~/.electrum/testnet/config`
`12K -rw-rw-r-- 1 me me 365 Sep  5 01:00 .electrum/testnet/config`

`cat ~/.electrum/testnet/config`

And the contents:
```
}
    "blockchain_index": 0,
    "gap_limit": 250,
    "rpcport": 6161
}
```
Status of daemon:

`electrum daemon status -v --testnet`
```
{
    "auto_connect": true,
    "blockchain_height": 1179095,
    "connected": true,
    "fee_per_kb": null,
    "path": "/home/me/.electrum/testnet",
    "server": "testnetnode.arihanc.com",
    "server_height": 1181053,
    "spv_nodes": 6,
    "version": "2.9.3",
    "wallets": {
        "/home/me/.electrum/testnet/wallets/default_wallet": true
    }
}
```
The daemon is running:

`tcp        0      0 127.0.0.1:41460         0.0.0.0:*               LISTEN      10268/python`

But listening on incorrect (random) port:

`10268 pts/0    Sl     0:00 /usr/bin/python /usr/local/bin/electrum daemon start --testnet`

**Comment by ecdsa** [comment]
remove the config file, it will create a new one.
refrain from editing it manuallly.
