### ISSUE TITLE
Bitcoin transaction not showing up in electrum wallet

### ISSUE THREAD

**Issue by PPrincess2017** [spesmilo/electrum#2841]
I sent some bitcoin from Coinbase to my electrum wallet 24 hours ago and the transaction isn't even showing up as "pending" in electrum even though coinbase and the blockchain info say it was fully sent/confirmed yesterday.

What's weirder still is that the receive address I used in electrum is now moved to the addresses tab as a used receiving address as though it knows it received a transaction at that address already. What is going on here?

I've been using this same wallet and process for years and this has never happened . . . I'm at a loss to figure out how to find that coin. Can anyone give me any tips on what to try? I have tried rebooting several times, changing servers, and restoring the wallet using the seed, but always the balance is still showing as zero. Thanks for any help you can provide.

txid: 2ee96e5b7de6ef74ec37145d3f6814abe017f9a8a86690b26f018bfa824019b4

**Comment by ecdsa** [comment]
make sure the receiving address actually is in your wallet

**Comment by ecdsa** [comment]
whats the receiving address?

**Comment by PPrincess2017** [comment]
Receiving address: 18onvZHCnvP7CuZAAq2pRzwq1HZpFd68FS

**Comment by PPrincess2017** [comment]
The receiving address is in the wallet. It moved to the used addresses after the transaction even though the bitcoin never showed up in the wallet.

**Comment by ecdsa** [comment]
it looks like the wallet history is somehow corrupted.
if you display the details of this address, how many transactions are shown in the history?

**Comment by PPrincess2017** [comment]
It's got 58 transactions showing in the history, which looks about correct. It's even showing the last transaction I did, which was less than a week ago. This just came out of nowhere.

**Comment by ecdsa** [comment]
I am talking about the history of that address

**Comment by PPrincess2017** [comment]
I guess I'm not sure what you mean. How do I check that?

**Comment by PPrincess2017** [comment]
I checked the history of the receiving address in electrum and nothing is showing up in there (it's blank), and that's the same for all of the addresses there I looked at. Is that normal and if not, what can I do to fix this? Please help, as I'm at a total loss as to what to do here to retrieve my coin.

**Comment by PPrincess2017** [comment]
If I check both coinbase and the blockchain for the receiving wallet I can see the coin was sent and is just sitting in there, but something must be wrong with my electrum wallet since it won't show up in there or let me access it. Is there a way for me to restore the electrum wallet on another wallet program online since the tails version seems to be faulty?

**Comment by ecdsa** [comment]
you can restore the wallet from seed, in another wallet file

**Comment by ecdsa** [comment]
oh you are using tails? why dont you start with the beginning, and tell me what version of electrum is in your system?

**Comment by ecdsa** [comment]
You should use a more recent version of Electrum. If Tails does not have it, do not use Tails. You should not post github issues if they are caused with old versions of Electrum, because that is really wasting our time. Before anything, check that the issue still exists with recent software. The purpose of github issues is to help developers fix bugs, and not to guide you through older versions. 

So, I am closing this issue. Reopen this issue if the problem still exists with the latest version of Electrum.
