### ISSUE TITLE
Money Dissapeared

### ISSUE THREAD

**Issue by Chapske** [spesmilo/electrum#2843]
![image](https://user-images.githubusercontent.com/31416829/30113798-2cff4f6a-9316-11e7-8dfe-5f747443a1b3.png)
Hey,
I am a new user of electrum and I tried to transfer the money back to my bank to see if it works.
While trying to do that my money never came back. Could I have some information what happend?
Already thanks for helping

Steven

**Comment by ecdsa** [comment]
what does "back to your bank" mean?
you probably used an address that is not linked to your account.
