### ISSUE TITLE
Can you import LocalBitcoins.com and Bisq.network wallet into Electrum?

### ISSUE THREAD

**Issue by sami10007** [spesmilo/electrum#2845]
Hi, 

I am testing the decentralised bitcoin services. I am trying to understand the role of Electrum there. 
I really would like to isolate the bitcoin wallet from those decentralised programs i.e. Electrum would be my choice of wallet. 

Best regards, 

Sami

**Comment by bauerj** [comment]
You can just send your coins from e.g. localbitcoins to your Electrum wallet.
