### ISSUE TITLE
PLEASE HELP ELECTRUM HAD ME SEND A $480 DOLLAR FEE WITH MY TRANSACTION!!!!!!!!!

### ISSUE THREAD

**Issue by theman321** [spesmilo/electrum#2848]
i have no way of getting it back. theres no way i should of been able to do that and me fees have not changed. im trying to get ahold of the miner and hope hes a good guy but i believe my electrum was bugged. i cant take this loss. the miners were bitclub network if anyone could help me get ahold of them i have proof of addresses hopefully theyll do the right thing and give me the money back

**Comment by dabura667** [comment]
Transaction ID please.

**Comment by ecdsa** [comment]
I guess he confused fee and change
