### ISSUE TITLE
How to compile Electrum executables on Windows

### ISSUE THREAD

**Issue by fujicoin** [spesmilo/electrum#2849]
Please refer to the link below:
https://github.com/fujicoin/electrum-fjc-2.9.3/tree/master/build-win

Enjoy!

**Comment by Transisto** [comment]
This guide is telling people to compile from a shitcoin repository. http://fujicoin.org/
Don't follow this guide to the letter.
Do not download anything from  https://github.com/fujicoin/electrum-fjc/
