### ISSUE TITLE
Can't oppen the carema to send bitcoin in the android app

### ISSUE THREAD

**Issue by estebanbecker** [spesmilo/electrum#2852]

**Comment by bauerj** [comment]
Can you provide more details? Is https://play.google.com/store/apps/details?id=com.google.zxing.client.android installed?

**Comment by estebanbecker** [comment]
Ok, it's now ok but it wasn't indicated that I must download this app

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
