### ISSUE TITLE
Missing a versions.py file

### ISSUE THREAD

**Issue by eddrickliu** [spesmilo/electrum#2854]
My question is that when I am working through the documentation, particularly in the android documentation inside gui/kivy.  When I get to make theming, it says versions.py is missing in the contrib folder, tried searching for an answer everywhere on the internet and it is not showing up.

**Comment by charleshsu168** [comment]
https://github.com/spesmilo/electrum/blob/master/gui/kivy/tools/buildozer.spec
you need to modify the path to where the main.py is

**Comment by eddrickliu** [comment]
So I modified that line after copying the buildozer.spec line out and creating the main.py file.  
specifically as such: source.dir = /home/eddrickliu/personalproject/electrum/main.py
Not crashing anymore but not creating anything either.  
Here are the outputs on my terminal.  eddrickliu@ubuntu:~/swag/electrum/gui/kivy$ make apk
make[1]: Entering directory '/home/eddrickliu/swag/electrum/gui/kivy'
# running pre build setup
# copy electrum to main.py
make[1]: Leaving directory '/home/eddrickliu/swag/electrum/gui/kivy'
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.18.10 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'pip install -q --user '
# Cwd None
# Apache ANT found at /home/eddrickliu/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/eddrickliu/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/eddrickliu/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=Electrum --bootstrap=sdl2 --requirements=hostpython2,android,openssl,pycrypto,pil,plyer,kivy==master --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/eddrickliu/swag/electrum/.buildozer/android/platform/build'
# Cwd /home/eddrickliu/.local/lib/python2.7/site-packages/pythonforandroid/
[INFO]:    Recipe kivy: version "master" requested
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19, 24)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	Electrum: includes recipes (hostpython2, jpeg, openssl, png, sdl2_image, sdl2_mixer, sdl2_ttf, python2, pil, pycrypto, sdl2, six, android, pyjnius, kivy, plyer), built for archs (armeabi-v7a)
[INFO]:    Electrum has compatible recipes, using this one
# Build the application #20
# Copy application source from /home/eddrickliu/swag/electrum/main.py
# Package the application
# project.properties updated
# Run '/usr/bin/python -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name Electrum --name Electrum --version 1.9.8 --package org.electrum.electrum --android_api 19 --sdk 19 --minsdk 9 --private /home/eddrickliu/swag/electrum/.buildozer/android/app --permission INTERNET --permission WRITE_EXTERNAL_STORAGE --permission READ_EXTERNAL_STORAGE --presplash /home/eddrickliu/swag/electrum/main.py/icons/electrum_presplash.png --icon /home/eddrickliu/swag/electrum/main.py/icons/electrum_launcher.png --orientation portrait --window --intent-filters /home/eddrickliu/swag/electrum/gui/kivy/tools/bitcoin_intent.xml --copy-libs --arch armeabi-v7a --color=always --storage-dir=/home/eddrickliu/swag/electrum/.buildozer/android/platform/build'
# Cwd /home/eddrickliu/.local/lib/python2.7/site-packages/pythonforandroid/
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Getting Android API version from user argument
[INFO]:    Available Android APIs are (19, 24)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	Electrum: includes recipes (hostpython2, jpeg, openssl, png, sdl2_image, sdl2_mixer, sdl2_ttf, python2, pil, pycrypto, sdl2, six, android, pyjnius, kivy, plyer), built for archs (armeabi-v7a)
[INFO]:    Electrum has compatible recipes, using this one
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:    	Electrum: includes recipes (hostpython2, jpeg, openssl, png, sdl2_image, sdl2_mixer, sdl2_ttf, python2, pil, pycrypto, sdl2, six, android, pyjnius, kivy, plyer), built for archs (armeabi-v7a)
[INFO]:    Electrum has compatible recipes, using this one
[INFO]:    -> directory context /home/eddrickliu/swag/electrum/.buildozer/android/platform/build/dists/Electrum
BUILD FAILURE: No main.py(o) found in your app directory. This
file must exist to act as the entry point for you app. If your app is
started by a file with a different name, rename it to main.py or add a
main.py that loads it.
# Command failed: /usr/bin/python -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name Electrum --name Electrum --version 1.9.8 --package org.electrum.electrum --android_api 19 --sdk 19 --minsdk 9 --private /home/eddrickliu/swag/electrum/.buildozer/android/app --permission INTERNET --permission WRITE_EXTERNAL_STORAGE --permission READ_EXTERNAL_STORAGE --presplash /home/eddrickliu/swag/electrum/main.py/icons/electrum_presplash.png --icon /home/eddrickliu/swag/electrum/main.py/icons/electrum_launcher.png --orientation portrait --window --intent-filters /home/eddrickliu/swag/electrum/gui/kivy/tools/bitcoin_intent.xml --copy-libs --arch armeabi-v7a --color=always --storage-dir=/home/eddrickliu/swag/electrum/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
make[1]: Entering directory '/home/eddrickliu/swag/electrum/gui/kivy'
# Cleaning up
# rename main.py to electrum
# remove buildozer.spec
make[1]: Leaving directory '/home/eddrickliu/swag/electrum/gui/kivy'

**Comment by ariard** [comment]
You don't need to create main.py, buildozer will copy the electrum file to be main.py, let source.dir as "."

Use the application versioning method 2 : comment the first one in buildozer.spec, decomment the second one, update to the good version : 2.9.3 and it should work !

**Comment by ecdsa** [comment]
you can also create the versions.py file manually
