### ISSUE TITLE
Bitcoin transactions disappearing

### ISSUE THREAD

**Issue by Chuck1973** [spesmilo/electrum#2855]
First a few september transactions disappeared from my history and now it is all the back to July. Is this a glitch? I do not see any history it is like they never existed.

**Comment by Chuck1973** [comment]
This is OSX as well.

**Comment by EagleTM** [comment]
Which server are you using? Please try changing it and restart Electrum. We're receiving a few of these reports

**Comment by Chuck1973** [comment]
Ok, I will try that.

**Comment by EagleTM** [comment]
Please do report back which server does not show all transactions

**Comment by Chuck1973** [comment]
bcc.arihanc.com

**Comment by EagleTM** [comment]
Right, that's most likely as Bitcoin Cash (BCH) node. Please update to 2.9.x and choose a server on the Bitcoin chain

**Comment by Chuck1973** [comment]
Ok, I did notice I am not 2.9 but my mac was resisting the update. I will mess with it and get back.

**Comment by Chuck1973** [comment]
That worked, thank you
