### ISSUE TITLE
Feature request - 2FA regen.

### ISSUE THREAD

**Issue by pingram3541** [spesmilo/electrum#2860]
It would be of great convenience when upgrading devices to be able to reset 2fa using the old device and not be forced to restore to a new wallet from seed.

Also, I am uncertain if the restore forgoes the loss of any prepaid 2fa verifications too.  For example, if one has prepaid for 100 x 2fa transactions, used a few but has considerable amount remaining and then later needs to upgrade their phone, how does one go about moving 2fa to the new device without losing this credit?

**Comment by SomberNight** [comment]
Recap of "2FA" wallets in Electrum:
- uses 2-of-3 multisig
- cosigner1's xprv is generated on your PC when you create the wallet, and it will be stored on your PC
- cosigner2's xprv is generated on your PC when you create the wallet, but will NOT be stored on your PC
- when you create the wallet, you are given seed words, from which BOTH cosigner1's and cosigner2's xprv can be derived; this guarantees your funds are not locked in any way, but using the seed words to restore your wallet greatly diminishes the security of the setup and should no longer be considered truly 2FA after that
- cosigner3's xprv is generated by the company called TrustedCoin, and only they have access to it
- when you create the wallet, you are given a QR code that represents a shared secret between you and TrustedCoin, from which Time-based One-Time Passwords (TOTP) can be derived
- this QR code is usually scanned using your phone (e.g. Google Authenticator on Android), and consequently the shared secret will be stored on that phone
- your transactions normally get signed by cosigner1's xprv (stored on your machine) and cosigner3's xprv (stored on TrustedCoin's servers) -- TrustedCoin signs for you, as a service, if you know the TOTP, for which you need the QR code

Hence, to answer your question, you should create an offline backup of the QR code when the wallet is created initially. When you change phones you simply scan the QR code on the new phone.

**Comment by pingram3541** [comment]
Thanks for the clarity and I think I found that suggestion elsewhere and is great advice.  Yet this was my first wallet and I was none-the-wiser at the time.  I would love to retain the history and just keep using it.

So far, most every other mechanism in which I use GA provides a way to regenerate a new QR code as long as the original can still authorize it.  It think this would help simplify things greatly for newcomers but I realize this probably relies on the API not hindering this capability as it pertains to retaining credit.

**Comment by charleshsu168** [comment]
you can't reset 2FA. you can disable it or to create a new 2FA, create a new wallet with a new 2fa. then send your coins to the new wallet.

**Comment by SomberNight** [comment]
@charleshsu168 
This is a feature request. It is theoretically possible to cooperate with TrustedCoin in generating a new QR code.

**Comment by pingram3541** [comment]
The process of restoring a wallet is a bit intimidating for newcomers especially if one has enough coin to be concerned of a loss if anything goes wrong.  In my case, I didn't feel I had enough information about the restore process (step-by-step each OS) and if there was anything irreversible, like losing my TrustedCoin credit which happens to be 92 at the moment.

Additionally, I'd preferably like to avoid fees transferring to another wallet.  Maybe this is another indicator of being green and there is a way to do with without fees and praying over the next few days that the transaction gets accepted eventually.

I wound up restoring a wallet from seed after fumbling through the Linux version and discovering that eventually you'll get the options one is looking for (restore from seed) if you click through the create new wallet wizard accessed by simply typing "electrum" in the CLI, the actual CLI restore command kept failing with an error not found when searching here, except of course the file producing the error text output.

After a few screens into the wizard it detected a 2fa version based on the seed. I waited a few days at this part due to uncertainty of how this worked but eventually took a leap of faith and found that it does allow for a new QR code that matched the time stamp code of the original that was given on my original wallet.

Does this mean it's the same QR code and it's just not mentioned anywhere that this will happen?  This would have saved me two days waiting for TrustedCoin support to respond.

Either case, I'm all good now. The original wallet address updated and both are in sync.  The second was done on a thumb drive OS so it could be wiped to 0's.

I still think avoiding this process by providing a regen option of the 2fa QR, provided you have access to the current 2fa to unlock it.  This would make device transfers much simpler while still secure.  Folks that have lost their device will still have to restore, i.e. go the long route.

**Comment by ecdsa** [comment]
I don't understand the issue here. You can request a new 2FA code if you restore from seed. The whole seed is actually needed because you need to sign a message that proves that you can spend the funds. Not requiring that signature would lower security. You keep your prepaid transactions when you restore from seed.

Please do not post issues on github for this kind of questions. Github is for bug reports, not for questions

**Comment by pingram3541** [comment]
@ecdsa Hi Thomas, true It's not a bug report, it's a feature request that originated as a plea for help and understanding not easily otherwise known to those not involved with the actual programming of this wallet.

This is a clear indication of where the User Experience is very confusing and uninformative for non-technicals, let alone those like myself that actually have some tech and programming experience.

The fact that I need to restore a wallet from seed just to regen and/or "see" the original QR so I can add a new device is ridiculous in my opinion.  I understand that initially one could think that this would defeat the purpose of the 2FA protection but if you require the 2FA to see or regen the QR then that is still secure because you need at least 1 already set up 2FA device to get access before you can add a new device.  This makes changing devices so much easier than the guessing game of how the restore process works.

At least update the documentation so we know what to expect through every step of the wizard / restore process.  Last I checked, the screenshots were not even current in the documentation.

As far as posting non-bug issues on Github, please provide instructions where the community can ask these types of questions.  In this case, as an end-user of the open-source software community, I am asking for either a) clarity on use, b) documentation improvements and/or c) a feature enhancement by updating the software to ease the pain of this particular process in which the steps of said process are not known to us until we actually go through them, in this case the 2FA QR integration.

Thanks for consideration and hearing from your community.
