### ISSUE TITLE
Combine remaining unspend outputs on transaction

### ISSUE THREAD

**Issue by FloFri** [spesmilo/electrum#2862]
I think it would be nice to to have an option to combine all remaining unspend outputs in your wallet if you send a transaction. So you can use the transactions, you already send to combine all remaining outputs to one new output. That way you can save some fees, because you do not need an extra transaction to combine them.

So like, when you have 4 unspend ouputs:

A -> 0.1 BTC
B -> 0.1 BTC
C -> 0.15 BTC
D -> 0.2 BTC

Now you send a transaction of 0.18 BTC to Address X electrum would use output A and B for the transaction and create a new output with the remaining 0.02 BTC, so now you have 3 outputs in your wallet. With that option, electrum uses all 4 Outputs in the transaction and creates a new ouput of 0.37 BTC. So you now only have 1 output in your wallet.

I hope, you understand what I mean.

**Comment by charleshsu168** [comment]
You can set coin preference to privacy in the preference. By default, it's set at priority.
This will reduce the unspent outputs number to as little as possible to keep your unspent balance private.

**Comment by SomberNight** [comment]
You can already do this, though manually.
The `Pay to` line allows specifying multiple outputs, "batching"; there is also a dedicated option for it: `Tools`>`Pay to many`. As value, you can use `!` to send "the remainder".

So you would fill in the `Pay to` line as:
```
destination address, value
your receive address, !
```

I don't think there is a real need/demand for this to be automated. Also, there are privacy implications of doing this.
