### ISSUE TITLE
No symbol sign - GUI

### ISSUE THREAD

**Issue by unknown85** [spesmilo/electrum#2866]
Is it normal that the program changes my mouse cursor to the no symbol(prohibition sign) when clicking on the question mark symbol in the preference page?

This is happening on my Windows 10 machine running version 2.9.3

**Comment by ecdsa** [comment]
can you post a screenshot?

**Comment by bauerj** [comment]
![electrum-2 9 3_2017-09-13_21-34-01](https://user-images.githubusercontent.com/598790/30396846-44b35e16-98cb-11e7-8b09-636609989d54.png)

Yes, that's normal.

**Comment by ecdsa** [comment]
@bauerj any idea what that question mark is?
