### ISSUE TITLE
'sign' button is disabled in the version 2.9.3 windows for the cold wallet

### ISSUE THREAD

**Issue by jasonOramo** [spesmilo/electrum#2870]
I install two electrum wallet, which one is standarded version and is used as cold wallet and another one is watch only wallet. I use master pub key to generate the watch only wallet. Now I use 'preview' button to get the transaction and try to sign it in the cold wallet. But the 'sign' button never enables. I try to check the codes to find out the issue. And I found this:

In the 'https://github.com/spesmilo/electrum/blob/master/lib/keystore.py'  file line 68, the method 'get_pubkey_derivation' is tried to be called in 'get_tx_derivations', but it isn't be declared in the class 'KeyStore'. See the codes for details. Could someone could give me a hint about it?
Here are the relevent codes:
`
class KeyStore(PrintError):

    def has_seed(self):
        return False

    def is_watching_only(self):
        return False

    def can_import(self):
        return False

    def get_tx_derivations(self, tx):
        keypairs = {}
        for txin in tx.inputs():
            num_sig = txin.get('num_sig')
            if num_sig is None:
                continue
            x_signatures = txin['signatures']
            signatures = [sig for sig in x_signatures if sig]
            if len(signatures) == num_sig:
                # input is complete
                continue
            for k, x_pubkey in enumerate(txin['x_pubkeys']):
                if x_signatures[k] is not None:
                    # this pubkey already signed
                    continue
                derivation = self.get_pubkey_derivation(x_pubkey)
                if not derivation:
                    continue
                keypairs[x_pubkey] = derivation
        return keypairs

    def can_sign(self, tx):
        if self.is_watching_only():
            return False
        return bool(self.get_tx_derivations(tx))

`

**Comment by jasonOramo** [comment]
Update：
Ｉdowngrade the watch only wallet to version 2.5.0 and it works. The transaction generated in the online wallet could be signed in the cold wallet although I haven't got a clue why it works.

**Comment by ecdsa** [comment]
make sure you use the same version for cold storage and watching-only
