### ISSUE TITLE
RPC payto from specific address

### ISSUE THREAD

**Issue by ValtteriL** [spesmilo/electrum#2875]
I want to make payment from a specific bitcoin address.

In the payto command there is argument to specify the source address.
```
  -F FROM_ADDR, --from FROM_ADDR
                        Source address. If it isn't in the wallet, it will ask
                        for the private key unless supplied in the format
                        public_key:private_key. It's not saved in the wallet.
```
But when trying to do the same via RPC using parameters 'F', 'from' or 'FROM_ADDR' I get 
'got an unexpected keyword argument'

Is there a way to specify the from address in RPC call? If not, is there a plan to implement it?

**Comment by ecdsa** [comment]
"from_addr" works for me. the doc is not clear about that.
