### ISSUE TITLE
Native SegWit scriptPubKeys are incorrectly constructed

### ISSUE THREAD

**Issue by sipa** [spesmilo/electrum#2876]
In `lib/bitcoin.py`, the following code is used to construct scriptPubKeys for BIP173 addresses:

```python
def address_to_script(addr):
    if is_segwit_address(addr):
        witver, witprog = segwit_addr.decode(SEGWIT_HRP, addr)
        script = bytes([witver]).hex() + push_script(bytes(witprog).hex())
return script
```

This will produce a script whose first byte is the witness version. However, the correct behaviour according to BIP141, is using `OP_n` for witness version n. This is the same when n = 0, but incorrect otherwise. If this code is used to send to future witness version addresses, it will likely result in funds loss.

Please consider implementing the BIP173 test vectors as unit tests; they would have caught this.

**Comment by gmaxwell** [comment]
The correct code would look something like this:

assert(witver >= 0 and witver<=16)
script = bytes([(witver+0x50)*(witver>0)]).hex() + push_script(bytes(witprog).hex())

(But please do not just take my word for it, add the tests too)

**Comment by dabura667** [comment]
@gmaxwell I like #2877 with the exception that multiplying by a boolean is hard to read.

Please see my comment: https://github.com/spesmilo/electrum/pull/2877#discussion_r139274210

**Comment by ecdsa** [comment]
thanks for this

**Comment by ecdsa** [comment]
see also 6e9b2a4459a108d438a917241c97f315544644c9
