### ISSUE TITLE
address_to_scripthash needs to be updated

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2880]
```
electrum/bitcoin.py, line 361, in address_to_scripthash
return bytes(reversed(h)).hex()
AttributeError: 'bytes' object has no attribute 'hex'
```

**Comment by ecdsa** [comment]
use python3. see release notes.

**Comment by wakiyamap** [comment]
bytes.hex is newer python3.5
https://docs.python.org/3.5/library/stdtypes.html#bytes.hex

use higher python3.5

**Comment by lzsaver** [comment]
wakiyamap, thanks.

I used python3.4. It was not clear that I have to use python3.5. We need to added this info to the RELEASE-NOTES file.

**Comment by SomberNight** [comment]
Shouldn't we do something with this?
E.g. change
https://github.com/spesmilo/electrum/blob/7b2ff57d0cafba6afa6f77257176e7c77947cada/setup.py#L14-L15
