### ISSUE TITLE
Clicking QR-icon in Send-tab causes segmentation fault

### ISSUE THREAD

**Issue by mhulscher** [spesmilo/electrum#2885]
Clicking the icon results in: `[1]    22312 segmentation fault  electrum`

QR is properly generated in Receive-tab. Can also be enlarged.

Running latest master, commit 10b35e3545001f1e98f92942e7f7ba49e915c27a
Installed with `setup.py`
OS is Debian Testing.
Python 3.5.4, also tried 3.6.2.

Running electrum with `--verbose` doesn't show anything relevant. Not sure how to proceed. Please let me know if more info is required in case it can't be reproduced.

**Comment by SuBPaR42** [comment]
Clicking the QR icon (to the right of the 'Pay to') just loads zbar?  Maybe that is what is crashing?

**Comment by mhulscher** [comment]
Very likely. I tried this with an Electrum clone and the same problem arises. Closing this issue.
