### ISSUE TITLE
Electrum testnet gap limit?

### ISSUE THREAD

**Issue by juniorjp** [spesmilo/electrum#2887]
I don't know if this is intended, but I tried to increase the gap limit of a testnet wallet and it did not work.

```
storage.put('gap_limit',501)
storage.write()
```
It worked fine in a real wallet.

I also searched the docs but I couldn't find if testnet wallets should have this feature.

**Comment by SomberNight** [comment]
What version is this with? I've just tried on git master (c12c1685d7ef3d9598a7eddd48d3876cd3cff871), and it worked. Well, sort of. Did you prefix those commands with ```wallet.```?
```
wallet.storage.put('gap_limit',501)
wallet.storage.write()
```
Or rather, you should use:
```
wallet.change_gap_limit(501)
```

**Comment by juniorjp** [comment]
I'm using 2.9.3 on Ubuntu 16.04

I'm not using the console, this is the full script:

```
from electrum import WalletStorage
storage = WalletStorage(my_folder_address)
storage.put('gap_limit',501)
storage.write()
```

If there is a better way to do this outside of the console please let me know.

**Comment by bauerj** [comment]
You probably need to switch to testnet mode first:
```python
from electrum import bitcoin
bitcoin.set_testnet()
```

**Comment by SomberNight** [comment]
Also note that `my_folder_address` is different for testnet.

**Comment by juniorjp** [comment]
It worked thank you guys.
