### ISSUE TITLE
Install wizard instructions cut off

### ISSUE THREAD

**Issue by songproducer** [spesmilo/electrum#2888]
Ubuntu 16.04.3 - installed through Ubuntu Software.

Problem:
Install wizard instructions cut off:
![screenshot from 2017-09-18 17-06-33](https://user-images.githubusercontent.com/597346/30535180-f83b763c-9c93-11e7-86b9-9981b407d57f.png)

Steps to reproduce:
Create a new wallet
Wallet with two-factor authentication

**Comment by SomberNight** [comment]
This should now be fixed with #2891 merged
