### ISSUE TITLE
Deleting addresses from Imported_KeyStore does not refresh Receive tab

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2890]
Using version 2.9.3.
Assume a wallet of imported individual private keys (`Standard_Wallet` with `Imported_KeyStore`).

In the `Addresses` tab of the QT GUI, when right-clicking an address, you are given the option to `Remove from wallet`. When you do this, the address in the `Receive` tab does not change.
Hence, if you delete the address (and therefore the private key) that is currently shown in the `Receive` tab, you might end up asking for payment to an address you can no longer spend "from".

Restarting the app refreshes the address in the `Receive` tab.

A user in #electrum (freenode IRC) claimed to have lost funds due to this. The importance of backups should be obvious to anyone reading this though.

**Comment by AbdussamadA** [comment]
woah i think that option should be removed. deleting priv keys should not be an option at all.

**Comment by ecdsa** [comment]
the current version does not allow to delete imported keys.
but I think the option should exist

**Comment by ecdsa** [comment]
update: I re-added that option
