### ISSUE TITLE
display fees in sat/B units

### ISSUE THREAD

**Issue by LukAss741** [spesmilo/electrum#2892]
Would you consider changing units to display fees from BTC/kB to sat/B or add an option to change units it in settings?

Most of services such as estimatefee.com, blockchain.info, bitcoinfees.21.co, jochen-hoenicke.de/queue/ and more display fees in sat/B units. Currently users who set their fees manually most often need to convert fees from sat/B to BTC/kB.

sat/B is also clearer for displaying fees than BTC/kB because for example 50 sat/B is 0.0005 in BTC/kB. Leading zeroes are easy to mistype so that people may accidentally write too many or too few zeroes. I already sent a few transactions with accidentally 10x lower or 10x higher fee than expected due to mistype.

Thank you.

**Comment by lzsaver** [comment]
Look here: #2667.

IMHO, satoshi/byte is a de facto standard, so Electrum have to use it by default.
