### ISSUE TITLE
Preferences -> Identity, Needs Updating

### ISSUE THREAD

**Issue by ekerstein** [spesmilo/electrum#2893]
In the preferences, on the identity tab, it shows cryptoname.co and xmr.link, but neither of these URLs work.

`
msg = _('OpenAlias record, used to receive coins and to sign payment requests.') + '\n\n'\
              + _('The following alias providers are available:') + '\n'\
              + '\n'.join(['https://cryptoname.co/', 'http://xmr.link']) + '\n\n'\
              + 'For more information, see http://openalias.org'
`

**Comment by F1ash** [comment]
maybe 'https://cryptoname.com/' ?

**Comment by ecdsa** [comment]
no longer relevant
