### ISSUE TITLE
Lost all my BTC from my Electrum Wallet

### ISSUE THREAD

**Issue by gargkanishka90** [spesmilo/electrum#2894]
This morning I logged back into my Electrum Wallet and was surprised (and severely shocked) to see that all my BTC have been transferred to an unknown address. My current BTC balance is 0.0 BTC :(

The transaction shows that it was transferred to some address 'A' from one of my addresses. This address A is not on the list of my addresses (neither used nor change addresses). Is there a way to know what happened here?

**Comment by ecdsa** [comment]
if your coins have been stolen, then your seed or password has been compromised.
the only way to know how it happened is to check your system's security, and who has access to it.

**Comment by ecdsa** [comment]
closing, not much we can do without more info
