### ISSUE TITLE
Unable to remove 2FA

### ISSUE THREAD

**Issue by mdhz** [spesmilo/electrum#2896]
Hello,

The version that I am using is 2.7.12 and I have downloaded the new version and I'm afraid that I might lose the Bitcoin Cash that the wallet is having if I upgrade the present client(don't want to risk).

So basically what I did is to disable the 2FA, I tried to restore it and entered the seed and then in the next step I selected the disable button and clicked NEXT and all went fine with creating new wallet but I can still see [2fa] written and I'm unable to use it on android client to claim the bitcoin cash.

Hope you'll give a solution.

-Regards.

**Comment by AbdussamadA** [comment]
This is the bitcoin electrum github not the support forum for electron cash which is maintained by a different developer. Go ask him for help!

**Comment by mdhz** [comment]
Did you even read the post ?
@AbdussamadA

**Comment by ecdsa** [comment]
that's normal. 2fa is still written because it is the wallet type.
however, if you see the seed button it means that you can sign withoutTrustedcoin

not sure if you can use that on Android. You need the desktop version, for both bitcoin and bitcoin cash.
