### ISSUE TITLE
SSL option in network dialog

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#2898]
This option seems to be about electrum servers yet it is on the proxy tab of the network dialog. Shouldn't it be on the server tab instead?

**Comment by bauerj** [comment]
See #2615

**Comment by SomberNight** [comment]
Alternatively, the `Proxy` tab could be renamed to something like `Connection`.

**Comment by ecdsa** [comment]
we could also remove the SSL option from the GUI, it is not very useful.
a command line option should be enough
