### ISSUE TITLE
Multi-sign with Trezor: Failed to compile output

### ISSUE THREAD

**Issue by Paulnternet** [spesmilo/electrum#2903]
This topic in similar way has been resolved here before but I still get an error
"Failed to compile output"

Im loading a 1-of-3 signed transaction by file, and am trying to add the final 2-of-3 signature. Using Trezor for the multisig wallet.

The transaction is spending 1 input and generating 2 outputs: one goes to a change address of the same wallet (also 2-of-3 of course), one goes out to a different multisig address

Trezor asks for confirmationg of the output that leaves the wallet. After confirming, the error shows up.

From what I've read in the other threads I suspect it's the change address output that Trezor is not able to confirm or something.

Electrum 2.9.3
Trezor 1.5.2

(A single input to non-multisig output transaction works just fine.)

**Comment by fireduck64** [comment]
Dup of #2738

**Comment by fireduck64** [comment]
Short version is, if you run from git head, you should be fine.  Should be fixed in next release.

**Comment by Paulnternet** [comment]
I have no idea how to compile and run it on windows by myself. I cloned everything with git windows and ran 
$ py setup.py install
which I think completed successfully, but now I'm stuck

**Comment by fireduck64** [comment]
can you just run it from there?  py electrum

**Comment by Paulnternet** [comment]
Weird stuff. It doesn't work (see below). But it does work when I run the normal stand-alone electrum, in that case it just opens a second instance. Weird. Thanks for your help though

$ py electrum
Traceback (most recent call last):
....
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\lnternet\electrum\plugins\cosigner_pool\qt.py", line 31, in <module>
    from PyQt4.QtGui import *
ModuleNotFoundError: No module named 'PyQt4'
Error: Could not import PyQt4 on Linux systems, you may try 'sudo apt-get install python3-pyqt4'
