### ISSUE TITLE
Problem with QR code scan on Android

### ISSUE THREAD

**Issue by Dosh22** [spesmilo/electrum#2909]
Hello, on my Xiaomi Redmi 4 32GB (Android 6.0) don't work the QR code scanning.... Electrum don't open camera, or crash.

**Comment by SomberNight** [comment]
Do you have this app installed? https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en

**Comment by Dosh22** [comment]
no, I have this one https://play.google.com/store/apps/details?id=com.gamma.scan&hl=en

**Comment by SomberNight** [comment]
I think Electrum needs ZXing (the one I linked) for QR codes to work.
Though this most certainly should be made more obvious to the user. :/

**Comment by bauerj** [comment]
It would be even better not to require an external app to do that.

**Comment by lzsaver** [comment]
> The zxing app wants to many access (contacts, etc....)
ZXing is open-source but you prefer Gamma Scan which seems to be proprietary. This is strange.

> It would be even better not to require an external app to do that.
The ZXing library is written in Java. Any ideas how to link it to the Kivy-based app? Or do we need some python library with a QR detector and a QR scanner? Such library should be able to detect and scan the QR code from the image which we will get using Kivy API.

**Comment by bauerj** [comment]
Something like this should work:

https://github.com/spesmilo/electrum/blob/227a553a9942d0168ab7611e5ce896eb1c837815/gui/kivy/main_window.py#L390-L408

**Comment by SomberNight** [comment]
Thanks to https://github.com/spesmilo/electrum/pull/3624 this should now be resolved. The QR code scanner is bundled with the Android app since version 3.0.4
