### ISSUE TITLE
Stuck on Synchronizing. Wont connect to servers

### ISSUE THREAD

**Issue by idealself** [spesmilo/electrum#2913]
Electrum 2.6.4

Wallet has been stuck on Synchronizing for over 24 hours now and wont connect to any other servers when selected manually. 

Any help would be much appreciated!

**Comment by AbdussamadA** [comment]
That version is way too old! Write down your seed if you haven't already done so and update to the latest version (2.9.3). You can get your seed from wallet menu > seed. To update just install electrum again for your operating system.

**Comment by idealself** [comment]
Yup, that worked 👍  Thank you!!
