### ISSUE TITLE
Connectd server

### ISSUE THREAD

**Issue by Moissh** [spesmilo/electrum#2914]
Hi
I install, unistall, reinstall a try again, but im not able to connect my electrum with a server
I try to connect automatically, manually but it is not posible.
I have not a antivirus connected, i check and give permit a Windows defender to use
how can i do for connect? when unistall and install, appear in the phase of my pasword and i can`t put all new again.

**Comment by SomberNight** [comment]
Hard to say from this... Are you using the latest version (2.9.3) ?

**Comment by ecdsa** [comment]
closing, not useful
