### ISSUE TITLE
Cold wallet Public key not recognised

### ISSUE THREAD

**Issue by andremcmorais** [spesmilo/electrum#2923]
I’m using TAILS as a Cold Wallet and Windows as a “watch only” wallet, I copy my Public Master Key from my Wallet on Eletrum on TAILS and when I try copy it, while registering, to the watch only on Electrum on Windows to add the wallet it doesn’t let me continue, the button stays in a darker tone of grey. Please let me know if I am doing something wrong or is it a Electrum problem. Thank you.

**Comment by SomberNight** [comment]
What version of Electrum on Tails, and what version on Windows?

**Comment by andremcmorais** [comment]
Latest on both

**Comment by SomberNight** [comment]
So is that version 2.9.3?

Also, on Windows, when trying to create the watch-only wallet, in the wizard, make sure you choose
- `Standard Wallet` and then `Use public or private keys`, and not
- `Watch Bitcoin addresses`

**Comment by andremcmorais** [comment]
I can’t confirm that is that version right now and I’ll see if I made that mistake, couple of hours and I will reply, thank you.
