### ISSUE TITLE
Plugins are not loaded in Windows builds

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2928]
On git master 6dfd3a0cabbb1bf2040773984cf19aed280d30e4 with #2918 applied and some extra logging of len(plugins...)

![electrum_plugins_not_loaded](https://user-images.githubusercontent.com/29142493/30817472-38c4efc8-a219-11e7-8a80-101a2c45fa0e.png)

As can be seen in the picture, plugins have not been loaded.

**Comment by ecdsa** [comment]
I believe the detection of plugins does not work well with pyinstaller3.
try to declare plugins explicitly in plugins/__init__.py
