### ISSUE TITLE
electrum password and seed

### ISSUE THREAD

**Issue by Bitoma** [spesmilo/electrum#2934]
Good morning everybody, I lost both:  password and seed in my electrum wallet . 
It's installed in my PC from the biginning, how can I retrieve my bitcoins? the program is open on my desktop . Is it possible to recover the seed ?  .......at last,  is there anybody that can  help me , indicate me some programs can that  help me?
Thanks in advance for your answers

**Comment by AbdussamadA** [comment]
Please post on the forum. This place is not for general support queries.

https://bitcointalk.org/index.php?board=98.0
