### ISSUE TITLE
Sync UX improvement

### ISSUE THREAD

**Issue by mryellow** [spesmilo/electrum#2937]
As demonstrated by the endless threads stating issues with "Synchronizing..." it's apparent that the UI is lacking any clear information for the user on the status of this action.

There appears to be no logs, progress bars or otherwise. Only a text "Synchronizing..." which shows no indication of failure, errors or progress.

**Comment by mryellow** [comment]
If #2867 is any indication then sync is not functioning at all for me. However due to poor UX, I have no indication that this is the case.

**Comment by SomberNight** [comment]
Try starting with the `-v` (verbose) flag if you are on Linux.

**Comment by mryellow** [comment]
Version 3 is much improved, extra columns and details explain what is happening a bit better. 

I wonder if it will gracefully degrade in future, past versions are left with very little to describe issues with API incompatibility.

**Comment by ecdsa** [comment]
nothing useful here

**Comment by mryellow** [comment]
> nothing useful here

Yet users remain lost and this lack of an error remains undocumented.
