### ISSUE TITLE
Electrum Sychnronizing

### ISSUE THREAD

**Issue by geargirl** [spesmilo/electrum#2945]
Funds aren't transferring to wallet due to electrum being stuck in synchronizing mode. Can anyone explain how to fix this issue?

**Comment by AbdussamadA** [comment]
switch to a different electrum server via tools > network. uncheck select server automatically, switch to server tab, right click on a server there and choose use this server. see if it syncs now.

if the above doesn't work upgrade to the latest electrum version.

**Comment by AbdussamadA** [comment]
Also in future post on the forum for support: https://bitcointalk.org/index.php?board=98.0

**Comment by geargirl** [comment]
Upgrading worked! Thank you so much!!
