### ISSUE TITLE
Version 2.9.3 and master brach won't export or accept testnet master public key when running in --testnet mode

### ISSUE THREAD

**Issue by hoangan** [spesmilo/electrum#2946]
I run Electrum with command: 
```python
 python3 electrum --testnet
```
Electrum generate testnet address correctly. However, when exporting TESTNET master public key, it exported MAINNET master public key (xpub...) instead. Also when creating testnet multisig wallet, Electrum did not accept testnet master public key, it only allowed to enter mainnet master public key.

Regards,
An

**Comment by ecdsa** [comment]
it's not a bug, it is a feature.
we now use the version bytes to signal for the type of script, and not the network.
doing both makes little sense.

**Comment by hoangan** [comment]
Hi,
Then how do I ask electrum to export testnet master public key (tpub...), and accept testnet master public key to generate multisig wallet? Please advice. 

Right now it only export and accept mainnet key.

Thanks

**Comment by ecdsa** [comment]
just export it as it is now.
xpub no longer means mainnet

**Comment by SomberNight** [comment]
Electrum 3.0 broke compatibility with pre-3.0 **testnet** master public keys. They will no longer work as is.
If you also have the corresponding seed, you can re-derive the new master public key from it, using the new code. That is, restore wallet from seed, and export the new master public key from the application.

**Comment by hoangan** [comment]
I'm not sure if I got it. 
Here's my codes to derive key using bitcoinlib-js:

```javascript 
var bitcoin = require('bitcoinjs-lib');
var network = bitcoin.networks.testnet;
var bip39 = require('bip39');

var mnemonic = 'mail fix blue section cost agent oxygen donor domain sound exit cruel response dish sun mammal truly fish awkward say arrange shed topple gossip'
var seed = bip39.mnemonicToSeed(mnemonic)
var root = bitcoin.HDNode.fromSeedBuffer(seed, network);
var master = root.derivePath("m/44'/1'/0'");
var xpub = master.neutered().toBase58();

var masterPubKey = bitcoin.HDNode.fromBase58(xpub, network);

var child = masterPubKey.derivePath("0/" + 1)
console.log(xpub);   
// tpubDDhX9wCe9aSJZ3ytbPMeJ1tTzjwFu7uHSr1TV3D5efca3DuJEH8FLDhjnmXzgwF7DYSGszgBnMrdytYVisarf9FSwGugPWxYKDXeNnAZi5x

console.log(child.getAddress()); // momMFVY7BA3CLmEJjdggeRo8FCe1iMTXoY
```
However, when I entered to same seed into electrum in testnet mode. It would produce:

```javascript
xpub6DKtdhNxSJUrHFo39CNZ66Z6fcqbujQDuDRA8V9wJkrgHwEbA4HABn2uYjTDASHsRduNGRAKFG2bHi3tL1jcmho9sgANhzJJjFwEcju6aNC

momMFVY7BA3CLmEJjdggeRo8FCe1iMTXoY
```
The addresses match, but the master public key don't

**Comment by ecdsa** [comment]
if the addresses match, then everything is fine

**Comment by hoangan** [comment]
But when I enter 
```javascript
xpub6DKtdhNxSJUrHFo39CNZ66Z6fcqbujQDuDRA8V9wJkrgHwEbA4HABn2uYjTDASHsRduNGRAKFG2bHi3tL1jcmho9sgANhzJJjFwEcju6aNC
```
for creating multisig wallet in testnet mode, it didn't work (the window just went blank), and it didn't accept the other tpub either.

**Comment by ecdsa** [comment]
that's a separate issue. there's a bug with multisig creation in master.

**Comment by hoangan** [comment]
actually in 2.9.3 too. Thanks for clarification. Do you know when it got fixed?

**Comment by ecdsa** [comment]
it should work in 2.9.3
but you should not mix tpub from 3.0 and xpub from 3.0

**Comment by hoangan** [comment]
Hmm...because it didn't work in 2.9.3, so I tried master branch. I'm on MacOS, currently there's only 2.9.2 binary for MacOS. I have to download zip file and run:  python electrum. Not sure the windows version have this issue. 

What do you mean tpub from 3.0 and xpub from 3.0 btw?

**Comment by ecdsa** [comment]
I'm saying that you cannot take a testnet xpub from 3.0 and enter it as cosigner in 2.9.x, because 2.9.xexpects tpub

**Comment by hoangan** [comment]
After compiling and run master brach, electrum 2.9.2 cannot run in testnet mode anymore. It only popup a error message: Electrum Error.

**Comment by ecdsa** [comment]
that's normal, that's because it does not recognize the new xpub.
delete the wallet if you want to run an old version

**Comment by hoangan** [comment]
Many thanks!
