### ISSUE TITLE
Wrong Electrum QR code ?

### ISSUE THREAD

**Issue by repsorp** [spesmilo/electrum#2947]
QR code generated by Electrum (payment request) is not working and is different from the one generated by [blockchain.info](https://blockchain.info/address/15fQBuWcnfRBN3cbd8nEhwPFvd99SLvwYe)  ?
Is there any way to reset QR code cache ?
Anything else ?

Ubuntu 16.04
Electrum 2.9.3

![qr](https://user-images.githubusercontent.com/6297032/30965389-92286e6c-a455-11e7-9117-49834f382558.png)

**Comment by SomberNight** [comment]
The QR code on blockchain.info only encodes the bitcoin address itself.
The QR code shown in the `Receive` tab in Electrum encodes additional information. At the very least, the encoded text starts with `bitcoin:` as in [BIP0021](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki)

You should try decoding the QR code and see for yourself.

**Comment by repsorp** [comment]
Thanks for the explanation
So there's something wrong with Jaxx Wallet that couldn't read Electrum QR code


_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by repsorp** [comment]
Thanks for the explanation
So there's something wrong with Jaxx Wallet that couldn't read Electrum QR code
 

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by repsorp** [comment]
Thanks for the explanation
So there's something wrong with Jaxx Wallet that couldn't read Electrum QR code
