### ISSUE TITLE
Wallet stuck exploring blockchain

### ISSUE THREAD

**Issue by njgturk** [spesmilo/electrum#2949]
Hello.

My wallet was stock exploring the blockchain at the block 439480. So I have install Electrum to another computer and the wallet was able to explore the blockchain until the same block. After, he stop to exploring but always show the Synchronizing status. 

What can I do please.

thank you

**Comment by SomberNight** [comment]
Hi. What version of Electrum is this with? I would guess you need to update.
By the way, where did you see that block height?

**Comment by njgturk** [comment]
Hello SomberNight.

my version is 2.9.2.

I see the block when I open tools/network under the blockchain indication.

**Comment by njgturk** [comment]
Problem solve by restarting the wallet client again. But I still o not understand the problem. Anyway... Thank you
