### ISSUE TITLE
Cannot sign transactions while offline

### ISSUE THREAD

**Issue by noobcoiner** [spesmilo/electrum#2951]
I created a cold storage/offline wallet using Electrum 2.7.9 and TAILS OS 3.0 which was disconnected from internet. The master public key was used to create a watch only wallet in an online windows computer using Electrum 2.8.3 portable. 

I made an unsigned transaction using the internet connected watch only wallet as said in the documentation and saved in a file. The transaction was RBF enabled. I used the seed which I wrote down earlier to regenerate the offline wallet in TAILS and the resulting wallet had the same addresses as the watch only wallet which means the seed was entered correctly. When I tried to 'Sign' the transaction from file made using the watch only wallet it throws the error message "Server did not answer" and the signing fails.

I then downloaded Electrum 2.7.9 portable for windows and made a watch only wallet using master public key. Saved a transaction without RBF to a file as before, thinking the previous failure was either because RBF was enabled or I used a newer version to make the the transaction than the one used for signing. Yet it failed to sign throwing the same error as before.

**Comment by SomberNight** [comment]
There is a [known issue](https://github.com/spesmilo/electrum/blob/2.9.3/RELEASE-NOTES#L119) in 2.7.9 (and nearby versions) with offline signing. Please update.
