### ISSUE TITLE
Electrum does not run on Windows for users having accented user names

### ISSUE THREAD

**Issue by literakl** [spesmilo/electrum#2956]
I want to confirm a trouble mentioned in https://github.com/spesmilo/electrum/issues/2712 and the comment. I have installed Electrum 2.9.3 and when I entered my password Electrum crashed. I have removed electrum directory and tried again. The path is c:\Users\Leo**š**\AppData\Roaming\electrum. It started to work when I copied portable version into c:\apps folder.

**Comment by literakl** [comment]
ecdsa, what is a close reason? Is it a duplicate? This problem does exist in current version.

**Comment by ecdsa** [comment]
it is a duplicate, and it is fixed in master
