### ISSUE TITLE
Unsuitable colors for a dark theme

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2957]
PyQt5 uses a theme of the OS. It's cool. But Electrum is not adapted. It's hard to read such colored text.

[electrum-color-addr.png](https://ipfs.io/ipfs/zdj7WWNGHTH48M7zYKoRvGbbyMw2HW38jjGmvHCFXfX7SgFva/electrum-color-addr.png)
[electrum-color-send.png](https://ipfs.io/ipfs/zdj7WimejcHsFgbepkqx4vkNwFBRreTZsiWPbUfnUmdhSZwS3/electrum-color-send.png)
[electrum-color-tx.png](https://ipfs.io/ipfs/zdj7WnRUucpGZdWBfbXg6MhX6djZzEozb6Yrd3dqQinENPuhu/electrum-color-tx.png)

There are some ways to fix it:
- somehow do not apply the current theme of the OS to Electrum;
- remove colors;
- use different colors for light and dark themes (how to know is the current theme dark or not?);
- (the best one?) choose some good colors, these colors should be okay for light and dark themes.

**Comment by bauerj** [comment]
That does look cool! I'll try to implement using different colours.

What is your desktop environment?

**Comment by lzsaver** [comment]
It's hard to say. Dom0 is Xfce, DomU is without DE. It's Qubes OS (Xen-based).

It seems that (Py)Qt5 reads GTK 3 settings.

Try this:
```
# ~/.config/gtk-3.0/settings.ini
[Settings]
gtk-application-prefer-dark-theme=1
```

**Comment by lzsaver** [comment]
I'm also getting a dark text on a dark background if I press the Address button on the Sweep window.

[electrum-color-sweep-white.png](https://ipfs.io/ipfs/zdj7WeUfvdP5S9Lf71gupfS7hc8Hbo2yjrQSSe6FDzREXpZHQ/electrum-color-sweep-white.png)
[electrum-color-sweep-black.png](https://ipfs.io/ipfs/zdj7WnRe3JKnSro1T6Hz5aivNsVpD573xbzF2Zn4Ej9XXX4o1/electrum-color-sweep-black.png)

**Comment by lzsaver** [comment]
@bauerj, I think there should be just one place in the code to define colors so we can do things like _object.setStyleSheet(color.fg_ok if ok() else color.fg_notok)_ instead of using BLACK_FG, RED_FG, etc.

**Comment by bauerj** [comment]
Indeed, I agree. Can you take a look at #2983 and tell me if you have any suggestions or if I missed anything?

**Comment by lzsaver** [comment]
It's much better now. I've noticed that you also fixed the QR code icon in the address dialog.

The transaction dialog is not fixed yet.
[electrum-color-tx.png](https://ipfs.io/ipfs/zdj7WnRUucpGZdWBfbXg6MhX6djZzEozb6Yrd3dqQinENPuhu/electrum-color-tx.png)

**Comment by lzsaver** [comment]
[electrum-color-tx-yellow.png](https://ipfs.io/ipfs/zdj7WepTTWs18hFB37ddh2Tu6a1L4r59w7BmQteztcFF7TdJD/electrum-color-tx-yellow.png)

Also do we need to reuse _icon = qrcode_white if dark_scheme else qrcode_ everytime or it would be better to move it to the ColorSchemeItem class?
