### ISSUE TITLE
Unable to sign transaction offline using Trezor

### ISSUE THREAD

**Issue by paul-so** [spesmilo/electrum#2959]
This is similar to issue #2508.

I created a transaction using a watch-only wallet and transferred it to an offline computer with Electrum 2.9.3 installed. I linked offline Electrum with a Trezor device (firmware 1.5.2) and attempted to sign the transaction. After several seconds Electrum returned "Server did not answer" and was unable to sign the transaction.

The workaround is to copy wallet.dat from online watch-only wallet and replace its "keystore" section with its corresponding section from the offline wallet.dat linked to Trezor. After this, offline Electrum is able to successfully sign the transaction.

**Comment by ecdsa** [comment]
that's normal. Trezor requires the list of input transactions.
your offline wallet did not have them and tried to fetch them.

we will not fix that. the list of previous tx will no longer be needed with segwit.
In addition, combining hardware wallet with cold storage is redundant.

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/issues/3302
