### ISSUE TITLE
[3006932] QTreeWidgetItem

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2968]
```
Traceback (most recent call last):
  File "/home/user/electrum/lib/python3.5/site-packages/electrum_gui/qt/address_list.py", line 133, in <lambda>
    menu.addAction(_("Copy %s")%column_title, lambda: self.parent.app.clipboard().setText(item.text(col)))
RuntimeError: wrapped C/C++ object of type QTreeWidgetItem has been deleted
```

**Comment by SomberNight** [comment]
Do you have a way to reproduce?

**Comment by SomberNight** [comment]
I posted a workaround for #2969, feel free to try with that if you have the time.

**Comment by lzsaver** [comment]
I've got it again. I still don't know steps to reproduce.

**Comment by SomberNight** [comment]
On git master 5480b7dff50eaac8a10af9fc7d17c8e0a6f410c9.
When testing #3009, I have occasionally encountered the following:
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/plugins/trustedcoin/qt.py", line 210, in on_result
    tos_e.setText(self.TOS)
RuntimeError: wrapped C/C++ object of type QTextEdit has been deleted
Aborted
```

**Comment by ecdsa** [comment]
I believe this is happens when the list is refreshed while a popup menu is open;

**Comment by lzsaver** [comment]
self = <electrum_gui.qt.address_list.AddressList object at 0x7d2539324f78>
self.headerItem().text(col) = "Address"
item.text(col) = some bitcoin address

These values do not differ from the case when it does not crash, so they do not help.
That's all that I know for my case for now. I did not check on 01108d8 yet. I'll check it.

**Comment by SomberNight** [comment]
68ca0b73b17aed22e69fd672dfb6d45b880a5a12 indeed fixes the issue in the OP but not the issue at heart. For example, editing a label will still crash the app, as the `item` reference is no longer valid. And that can't be fixed this easily, as that operation writes (not reads, like copying an address) an item.
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/address_list.py", line 151, in <lambda>
    menu.addAction(_("Edit %s")%column_title, lambda: self.editItem(item, col))
  File "/home/user/wspace/electrum/gui/qt/util.py", line 409, in editItem
    self.editing_itemcol = (item, column, item.text(column))
RuntimeError: wrapped C/C++ object of type QTreeWidgetItem has been deleted
Aborted
```
https://github.com/spesmilo/electrum/blob/ddc989c672231392c07ab26c5721ac8b9605407e/gui/qt/address_list.py#L150-L151

**Comment by lzsaver** [comment]
I can't reproduce it on 01108d8 so far. But I can't be sure that it can not happen on 01108d8 at all.

**Comment by SomberNight** [comment]
Well, if you mean the edit-label-crash, I've now just reproduced on current HEAD of master (8deb57e600d56d61718891ab550ba235dc1d708d).
