### ISSUE TITLE
Trezor cannot send to bech32 addresses

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2976]
File -> New/Restore -> Standard wallet -> Create a new seed -> Segwit

I'm getting bc1-addresses, is it okay? I thought I should get 3-addresses.

**Comment by SomberNight** [comment]
Yes, that is expected. Electrum "segwit" seeds have native segwit outputs with BIP173 ("bech32") addresses.

https://github.com/spesmilo/electrum/blob/91ed74a95ff705265da5f64dadd3c59c71cdd2bb/RELEASE-NOTES#L12-L24

**Comment by lzsaver** [comment]
Oh, I did not read [BIP173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki). Has it already been accepted?

**Comment by lzsaver** [comment]
```
Traceback (most recent call last):
  File "/home/user/electrum-good/lib/python3.5/site-packages/electrum_gui/qt/util.py", line 589, in run
    result = task.task()
  File "/home/user/electrum-good/lib/python3.5/site-packages/electrum/wallet.py", line 1138, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/user/electrum-good/lib/python3.5/site-packages/electrum_plugins/trezor/plugin.py", line 70, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/user/electrum-good/lib/python3.5/site-packages/electrum_plugins/trezor/plugin.py", line 248, in sign_transaction
    outputs = self.tx_outputs(keystore.get_derivation(), tx, keystore.is_segwit())
  File "/home/user/electrum-good/lib/python3.5/site-packages/electrum_plugins/trezor/plugin.py", line 368, in tx_outputs
    addrtype, hash_160 = b58_address_to_hash160(address)
  File "/home/user/electrum-good/lib/python3.5/site-packages/electrum/bitcoin.py", line 315, in b58_address_to_hash160
    return _bytes[0], _bytes[1:21]
TypeError: 'NoneType' object is not subscriptable
```

I can't send coins to the bc1-address. Tested on 088b1e6 and 91ed74a + your patch.
Not implemented?

I'm not sure that it's good idea to use BIP173 by default while it is just a draft.

**Comment by SomberNight** [comment]
It's likely not implemented in Trezor (or at least the Trezor plugin). I think this warrants a separate issue.

**Comment by lzsaver** [comment]
I'll check it with your b1167e9 patch.

**Comment by lzsaver** [comment]
It does not work with the b1167e9 patch, and it does not work on dd006b5. I seems to be trezor-related.

**Comment by lzsaver** [comment]
> By the way, is it good idea to use BIP173 by default while it is just a draft?

It seems they are going to accept it, [bech32 support was added to Bitcoin Core](https://github.com/bitcoin/bitcoin/commit/aa624b61c928295c27ffbb4d27be582f5aa31b56).

**Comment by ecdsa** [comment]
I added this blind fix: 0df24d9321eb1c9ecc38685bdb70c0aa1d3fc9cb
it still fails for me, but it might work on recent firmware

**Comment by ecdsa** [comment]
https://github.com/trezor/trezor-common/pull/15#issuecomment-338641393

**Comment by jhoenicke** [comment]
FYI, I finished my implementation of bech32 in TREZOR firmware trezor/trezor-mcu#236.
Electrum doesn't need any changes to send to bech32 addresses with the TREZOR with the new firmware:  https://www.blocktrail.com/tBTC/tx/f7236e1da665db69bfb931ed2d0e7cd3c46f2d36fc6cc5c7199ca317c04c45d1

It would need some changes to use a wallet with bech32 addresses with Trezor, but I think we don't want to go that way soon.

Now I need a blockexplorer that shows the address.

**Comment by lzsaver** [comment]
> Now I need a blockexplorer that shows the address.

_Blockchain.info_ shows bc-addresses if you click '_Show scripts & coinbase_'.

Example: [link](https://blockchain.info/tx/834dce8d6e9f5323af8f00869220c357bc8540ecfd8d868261da15f4a6c6ba2d?show_adv=true).

**Comment by lzsaver** [comment]
Thank you. It works (tested on Trezor 1.6).
