### ISSUE TITLE
Message signing with bech32 addresses crashes Electrum

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2977]
Signing messages with p2wpkh and p2wpkh-p2sh addresses is not standardized (yet?), see e.g. bitcoin/bitcoin#10542
I think for the time being it can be disabled altogether, which is also what the current code (91ed74a95ff705265da5f64dadd3c59c71cdd2bb) aims to do:
https://github.com/spesmilo/electrum/blob/91ed74a95ff705265da5f64dadd3c59c71cdd2bb/gui/qt/main_window.py#L1901-L1903
Though perhaps this remark needs updated?
https://github.com/spesmilo/electrum/blob/91ed74a95ff705265da5f64dadd3c59c71cdd2bb/gui/qt/main_window.py#L1890-L1892

However, on current master, trying to sign a message with a bech32 address results in a crash:
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1957, in <lambda>
    b.clicked.connect(lambda: self.do_sign(address_e, message_e, signature_e))
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1281, in request_password
    return func(self, *args, **kwargs)
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1901, in do_sign
    if not bitcoin.is_p2pkh(address):
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 562, in is_p2pkh
    addrtype, h = b58_address_to_hash160(addr)
  File "/home/user/wspace/electrum/lib/bitcoin.py", line 314, in b58_address_to_hash160
    return _bytes[0], _bytes[1:21]
TypeError: 'NoneType' object is not subscriptable
Aborted
```

**Comment by lzsaver** [comment]
The same thing if I try to send coins to the bech32 address (#2976).

**Comment by ecdsa** [comment]
added in e299df7b82f626f669098ccc0dbe041934d72d86

**Comment by prusnak** [comment]
@ecdsa you should have used the scheme proposed in https://github.com/bitcoin/bitcoin/issues/10542#issuecomment-316032523
