### ISSUE TITLE
"Cannot get argument from stdin" when using command line

### ISSUE THREAD

**Issue by qirtaiba** [spesmilo/electrum#2988]
I have electrum on a machine that doesn't have a GUI, so I am reliant upon the text and command line modes.  Some of the functions I need are only available in command line mode, such as sweep. But I get errors when I try it:

`electrum sweep - [redacted]`
`Traceback (most recent call last):`
  `File "/usr/local/bin/electrum", line 4, in <module>`
    `__import__('pkg_resources').run_script('Electrum==2.9.3', 'electrum')`
  `File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script`
    `self.require(requires)[0].run_script(script_name, ns)`
  `File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script`
    `execfile(script_filename, namespace, namespace)`
  `File "/usr/local/lib/python2.7/dist-packages/Electrum-2.9.3-py2.7.egg/EGG-INFO/scripts/electrum", line 313, in <module>`
    `raise BaseException('Cannot get argument from stdin')`
`BaseException: Cannot get argument from stdin`

This is on a Debian stretch machine.  Any advice?

**Comment by ecdsa** [comment]
you need to send something to stdin
for example "echo privkey | electrum sweep - dest"

**Comment by qirtaiba** [comment]
Thanks!  It still gives an error when I do that, though (I'm sweeping to a multisignature wallet if that's the problem).  But I had assumed electrum dying was a bug rather than a usage error, so if I should be discussing this on some other forum rather than in github, please let me know.

`Traceback (most recent call last):`
`  File "/usr/local/bin/electrum", line 4, in <module>`
`    __import__('pkg_resources').run_script('Electrum==2.9.3', 'electrum')`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script`
`    self.require(requires)[0].run_script(script_name, ns)`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script`
`    execfile(script_filename, namespace, namespace)`
`  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.9.3-py2.7.egg/EGG-INFO/scripts/electrum", line 419, in <module>`
`    result = server.run_cmdline(config_options)`
`  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 288, in __call__`
`  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 238, in _request`
`  File "build/bdist.linux-x86_64/egg/jsonrpclib/jsonrpc.py", line 567, in check_for_errors`
`jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/dist-packages/Electrum-2.9.3-py2.7.egg/electrum/bitcoin.py", line 418, in public_key_from_private_key | AssertionError')`

**Comment by ecdsa** [comment]
you cannot sweep from a multisig address.

note: there were other errors with version 3.0, they are fixed in 15ab48aaa8b291777086c95658f4808443c8a289

**Comment by qirtaiba** [comment]
No I'm sweeping *to* a multisig address, not *from* one. But anyway, you have provided me with the answer by suggesting that I upgrade to the latest version of Electrum. The sweep operation now completes successfully without any of the errors that I received before. Thanks!
