### ISSUE TITLE
Imported_KeyStore.get_private_key() is "broken"

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2990]
On git master 3d54011c5d53c405ad22ace08e038bf3ec327e91.

Assume a `Standard_Wallet` with `Imported_KeyStore`, p2pkh addresses.
Exporting private keys is broken
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1867, in show_private_key
    pk, redeem_script = self.wallet.export_private_key(address, password)
  File "/home/user/wspace/electrum/lib/wallet.py", line 276, in export_private_key
    pk = self.keystore.get_private_key(index, password)
  File "/home/user/wspace/electrum/lib/keystore.py", line 154, in get_private_key
    sec = pw_decode(self.keypairs[pubkey], password)
KeyError: (False, 0)
``` 
(This trace specifically is from when you right-click an address in the `Addresses` tab of the QT GUI and choose `Private key`)

And of course also message signing, message encryption, and probably many things requiring a private key.

Also note #2989, specifically https://github.com/spesmilo/electrum/issues/2989#issuecomment-334306819.

**Comment by ecdsa** [comment]
this type of wallet should be converted to Imported_Wallet

**Comment by ecdsa** [comment]
see 3dabb94046cd94e145ee19f38cf6a0b36a6edcf9
