### ISSUE TITLE
Wallets created from command-line are not encrypted (regression?)

### ISSUE THREAD

**Issue by TJC** [spesmilo/electrum#2991]
Version 2.9.3 on Linux

`electrum -w test.dat create` and `electrum -w test.dat restore` both prompt for a password to encrypt wallet.

however the resulting test.dat file is plaint-text JSON and can be loaded into the daemon without a password being required.

Edit: The daemon claims to have loaded the file, but attempts to do anything result in error message "Wallet not open", although `daemon status` lists the wallet as open.

**Comment by ecdsa** [comment]
there is no bug here, only wrong expectations.
I guess we should improve the error messages so that users understand how to use -w

**Comment by TJC** [comment]
Yes, please do!

I couldn't for the life of me figure out how to get a working second wallet, and this *looks* like it should make sense:
```
electrum daemon start
# ok

electrum -w new_wallet create
# ok

electrum daemon -w new_wallet load_wallet
# ok

electrum daemon status | grep new_wallet
# looks loaded

electrum getbalance
# error wallet not opened!
```

**Comment by ecdsa** [comment]
why do you expect getbalance to use new_wallet?

**Comment by TJC** [comment]
I expected "getbalance" to use which-ever wallet I had chosen to load. There was only one wallet loaded, so I expected that wallet to be used.

I'm... guessing that's not the case?

**Comment by ecdsa** [comment]
no, that is not the case.
if that was the case, getbalance would return a different result depending on previous actions.
that would be really bad.

**Comment by TJC** [comment]
I can see there being issues if you had multiple wallets open simultaneously.

With just a single wallet open, I feel like it's reasonable to expect that to become the default wallet for actions. Just my feeling, mind, but I think that's how a lot of other tools works.
