### ISSUE TITLE
Kraken to Electrum Deposit "Waiting for fee estimates" & "Dynamic fee estimates not available"

### ISSUE THREAD

**Issue by AngrySiberianBear** [spesmilo/electrum#2993]
Hi Electrum Community,

I'm new to using Electrum and I would like to understand how long it can take to calculate / get fee estimates? 1 hour passed and still nothing (well, at least I see funds in my wallet but can't send them) or maybe I got a bug? I'm using 2.9.3. version

Thank you in advance.

**Comment by ecdsa** [comment]
"Waiting for fee estimates" means the server is not responding.
just select another server in the network dialog

**Comment by AngrySiberianBear** [comment]
What if I have only 1 server in server list?

**Comment by ecdsa** [comment]
disable auto connect, and visit the 'servers' tab
