### ISSUE TITLE
TrustedCoin - No Postpaid / Per Transaction Fee Option

### ISSUE THREAD

**Issue by AngrySiberianBear** [spesmilo/electrum#2994]
According to info coming from TrustedCoin:

"_Every transaction sent using two-factor auth costs 0.0005 BTC. You have the option of including this payment in each transaction or prepaying in chunks of 100 transactions for 0.025 BTC (half-off the individual price)_"

I see prepaid options:
![image](https://user-images.githubusercontent.com/32540634/31227976-845f15e4-a9e4-11e7-9fd5-83e4f8b3cf2b.png)

But when I try to send transaction without prepaid bundle purchase it obliges me to buy it:
![image](https://user-images.githubusercontent.com/32540634/31228001-99f11114-a9e4-11e7-805f-362397d73244.png)

**Is there any option to pay just 0.0005 fee per transaction without paying bundle fee of 0.002**

**Comment by ecdsa** [comment]
no, the pay per transaction option has been removed, because it caused too much mining fees.
@badmofo can you update the trustedcoin website?

**Comment by badmofo** [comment]
thanks for pointing this out.  trustedcoin website copy updated.
