### ISSUE TITLE
I forgot to press save when requesting.

### ISSUE THREAD

**Issue by rw514wrg65** [spesmilo/electrum#3007]
I forgot to press the save button when requesting in Electrum.
Yes,I can not receive payment.

I think that it is the reason that the line was interrupted on the way, but there is a sign of
 "in sync" in the place where the balance is displayed in Electrum.

Can I collect this BTC with just an address and signature in such a case?
Address signature can be verified.

**Comment by ecdsa** [comment]
you do not need to press save to receive.
