### ISSUE TITLE
transaction_dialog.closeEvent() crash

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3016]
On git master 4694717dc0651f5aedfdb0d0d395a586242f4ab1.

Using the QT GUI, in the `Send` tab, I was previewing a tx.
I clicked the `Close` button of the preview dialog but the app was unresponsive, so I clicked `Close` again a second time; then Electrum crashed.

```
[profiler] estimated_size 0.0003
[profiler] estimated_size 0.0004
DNSSEC error: The DNS operation timed out.
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/transaction_dialog.py", line 151, in closeEvent
    dialogs.remove(self)
ValueError: list.remove(x): x not in list
Aborted
```

**Comment by sunnyville01** [comment]
Were you able to reproduce the issue, or did it just happen that one time?

**Comment by SomberNight** [comment]
I could not reproduce this; it only happened that one time. Did it also happen for you now?

**Comment by sunnyville01** [comment]
I wasn't able to reproduce it. However, reading from the error output, it seems like the preview dialog was already removed from the `list` and it was just not rendered in the `gui` for some reason, which allowed you to click the `Close` button again and trigger the event. 

Perhaps we can check to see if a dialog exists in the `list` before trying to remove it, but I think it was just a one-off situation.
