### ISSUE TITLE
'Imported_KeyStore' object has no attribute 'get_xpubkey'

### ISSUE THREAD

**Issue by qirtaiba** [spesmilo/electrum#3021]
Under the latest Electrum 3.0 from github when I try to send from either the command online or the text GUI, I get "'Imported_KeyStore' object has no attribute 'get_xpubkey'".

**Comment by SomberNight** [comment]
What type is the wallet? `type(wallet)`
I don't think the problem is related to command-line/text UI usage.

**Comment by qirtaiba** [comment]
Multisig, imported

**Comment by ecdsa** [comment]
how did you create that wallet?

**Comment by qirtaiba** [comment]
To use it with Electrum I restored it using the private key. I originally created it using coinb.in if I recall correctly.

**Comment by ecdsa** [comment]
how did you restore a multisig wallet with "the private key" ?

**Comment by qirtaiba** [comment]
Eh you're right I guess it's not a multisig wallet is it?  It's just a normal wallet.

**Comment by SomberNight** [comment]
Again, could you check either the output of `type(wallet)` from the `Console` tab in the QT GUI, or the value of `wallet_type` in the wallet file?

If it is `Standard_Wallet` / `standard`, then the v14 conversion did not run for some reason; and if it is `Imported_Wallet` / `imported`, then either something went horribly wrong, or you are not on latest master.

**Comment by qirtaiba** [comment]
It's imported, but I am on the latest master. To be sure, I installed from source again just five minutes ago.

**Comment by ecdsa** [comment]
v14 conversion requires load_wallet to be called, which is not the case if he uses the command line

**Comment by qirtaiba** [comment]
seed_version says 14

**Comment by ecdsa** [comment]
can you paste the content of the wallet file (obfuscate whatever is private)

**Comment by qirtaiba** [comment]
OK here it is and I made a mistake! It says "wallet_type: standard". I mistook "keystore type: imported" for "wallet_type".

`{`
`    "addr_history": {`
`        "13FEd6gUFvhk--------SyA65LfABTU7Dw": [`
`...`
`        ]`
`    },`
`    "addresses": {`
`        "change": [],`
`        "receiving": [`
`            "13FEd6gUFvhk--------SyA65LfABTU7Dw"`
`        ]`
`    },`
`    "keystore": {`
`        "keypairs": {`
`            ---`
`        },`
`        "type": "imported"`
`    },`
`    "pruned_txo": {},`
`    "seed_version": 14,`
`    "stored_height": 488434,`
`    "transactions": {`
`...`
`    "tx_fees": {`
`...    },`
`    "txi": {`
`...    },`
`    "use_encryption": true,`
`    "verified_tx3": {`
`...`
`    },`
`    "wallet_type": "standard"`
`}`

**Comment by SomberNight** [comment]
right, so it might be https://github.com/spesmilo/electrum/issues/3021#issuecomment-335912532

**Comment by qirtaiba** [comment]
Can I fix this by just deleting the wallet and recreating it from the private key?

**Comment by SomberNight** [comment]
Yes. There has been a storage structure change for wallets (those that store imported private keys) recently, and the problem is about the conversion process of old->new. Freshly created wallets will work (unless there are other bugs :P)
