### ISSUE TITLE
Segmentation fault on closing

### ISSUE THREAD

**Issue by achow101** [spesmilo/electrum#3022]
Using master f381eae25134bbeeafee047f9cc495278f7bcfaf, whenever I close electrum, it segmentation faults and whatever I did in that session is not remembered. E.g, if I made a new wallet, it has me do the setup wallet wizard even though that was already done. Or if I added a label to some addresses they are not saved.

I am experiencing this on two machines both running Ubutnu 17.04 and python 3.5.3

**Comment by SomberNight** [comment]
I confirm this on a freshly installed Ubuntu 17.04 VM.

**Comment by SomberNight** [comment]
Note: when sending `^C` (ctrl+C) to the terminal, there is no segfault, but a graceful shutdown as expected

**Comment by SomberNight** [comment]
Also segfaults if you have more than one wallet open at the same time.

Crash happens at
https://github.com/spesmilo/electrum/blob/f381eae25134bbeeafee047f9cc495278f7bcfaf/gui/qt/__init__.py#L126

**Comment by ecdsa** [comment]
does it go away if you comment out that line?
