### ISSUE TITLE
Request: Add QR Code scan option to sweep keys dialog.

### ISSUE THREAD

**Issue by dan-da** [spesmilo/electrum#3027]
Many times a user may wish to read private keys from paper wallets or another device that have the private key in a QR code.

Unfortunately, at present the sweep dialog does not have an option to scan, so the user must manually type in the private key from the external source.   This is cumbersome and error-prone.

Please add QR scanning option.

**Comment by ecdsa** [comment]
good point

**Comment by dan-da** [comment]
awesome, thanks!
