### ISSUE TITLE
Plugin/addon but not in Python

### ISSUE THREAD

**Issue by GildedHonour** [spesmilo/electrum#3029]
> Electrum is written in pure python. if you want to add a feature
>    that requires non-python libraries, then it must be submitted as a
>    plugin. 

However, all the plugins in https://github.com/spesmilo/electrum/tree/master/plugins are in python.

1) Is it possible to create one in some other language? C++, C, etc....

2) At http://docs.electrum.org plugings aren't mentioned at all. Where is the documentation for creating plugins?

**Comment by ecdsa** [comment]
1. you will have to do the python bindings yourself.
2. there is no documentation, please use current plugins as examples.

**Comment by GildedHonour** [comment]
1. Is it possible to create one in some other language? C++, C, etc....

**Comment by bauerj** [comment]
Yes, but you will have to add Python bindings.

**Comment by GildedHonour** [comment]
Alright.
Does a plugin have access to the seed? If yes, how?
