### ISSUE TITLE
Semi-rare crash in network.py (assert not self.interfaces)

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3037]
On git master 1672bb1ffa11e9d8a7b558b624c789e57a0f5a28.

In the network dialog of the QT GUI, I had been spam-clicking the enable/disable proxy checkbox.

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/network_dialog.py", line 465, in set_proxy
    self.network.set_parameters(host, port, protocol, proxy, auto_connect)
  File "/home/user/wspace/electrum/lib/network.py", line 457, in set_parameters
    self.stop_network()
  File "/home/user/wspace/electrum/lib/network.py", line 432, in stop_network
    assert not self.interfaces
AssertionError
Aborted
```

**Comment by ecdsa** [comment]
we launch a new thread for each new connection. 
this thread lives until the connection is established or times out
if the thread finishes after you called stop_network, it can cause that

**Comment by ecdsa** [comment]
not really worth fixing, IMO. 
it would be better to rewrite the network layer using python3's async modules
