### ISSUE TITLE
Access to the seed from a plugin

### ISSUE THREAD

**Issue by GildedHonour** [spesmilo/electrum#3040]
Does a plugin have access to the seed? Can a plugin read the seed? If yes, how?

**Comment by ecdsa** [comment]
this question does not make sense.
why would a plugin differ from any other part of the code?
are you a programmer?

**Comment by GildedHonour** [comment]
no, I'm a tractor driver

plugin is what communicates with a software via api which that software exposes and therefore it might not have access to everything.

**Comment by ecdsa** [comment]
well, read the code of the existing plugins, then.
plugins have access to everything.
