### ISSUE TITLE
compiled android apk successfully but Android app closed after splash screen

### ISSUE THREAD

**Issue by NathiyaK** [spesmilo/electrum#3041]
I compiled the APK succesfully. But after installation of apk app closed after splash screen.

Below are the logcat output when it crashed. 

Displayed org.electrum.electrum/org.kivy.android.PythonActivity,cp,ca,523
11-14 18:14:00.546 1040-1053/? I/ActivityManager: Displayed org.electrum.electrum/org.kivy.android.PythonActivity: +523ms
11-14 18:14:01.060 26513-26535/org.electrum.electrum I/python: Initialized python
11-14 18:14:01.060 26513-26535/org.electrum.electrum I/python: AND: Init threads
11-14 18:14:01.061 26513-26535/org.electrum.electrum I/python: testing python print redirection
11-14 18:14:01.062 26513-26535/org.electrum.electrum I/python: Setting up python from ANDROID_PRIVATE
11-14 18:14:01.066 26513-26535/org.electrum.electrum I/python: Android path ['.', '/data/data/org.electrum.electrum/files/app/crystax_python/stdlib.zip', '/data/data/org.electrum.electrum/files/app/crystax_python/modules', '/data/data/org.electrum.electrum/files/app/crystax_python/site-packages']
11-14 18:14:01.067 26513-26535/org.electrum.electrum I/python: os.environ is environ({'ANDROID_STORAGE': '/storage', 'SECONDARY_STORAGE': '/storage/sdcard1', 'PYTHON_NAME': 'python', 'ANDROID_ENTRYPOINT': 'main.pyo', 'ANDROID_ASSETS': '/system/app', 'ANDROID_ARGUMENT': '/data/data/org.electrum.electrum/files/app', 'PYTHONHOME': '/data/data/org.electrum.electrum/files/app', 'ANDROID_PROPERTY_WORKSPACE': '9,0', 'PYTHONOPTIMIZE': '2', 'BOOTCLASSPATH': '/system/framework/core.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework2.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/webviewchromium.jar:/system/framework/telephony-msim.jar:/system/framework/qcmediaplayer.jar:/system/framework/oem-services.jar:/system/framework/qcom.fmradio.jar', 'PATH': '/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin', 'ANDROID_PRIVATE': '/data/data/org.electrum.electrum/files', 'EMULATED_STORAGE_SOURCE': '/mnt/shell/emulated', 'EXTERNAL_STORAGE': '/storage/emulated/legacy', 'ANDROID_ROOT': '/system', 'LD_LIBRARY_PATH': '/vendor/lib:/system/lib', 'EMULATED_STORAGE_TARGET': '/storage/emulated', 'ASEC_MOUNTPOINT': '/mnt/asec', 'ANDROID_DATA': '/data', 'LOOP_MOUNTPOINT': '/mnt/obb', 'ANDROID_UNPACK': '/data/data/org.electrum.electrum/files/app', 'ANDROID_SOCKET_zygote': '11', 'PYTHONPATH': '/data/data/org.electrum.electrum/files/app:/data/data/org.electrum.electrum/files/app/lib', 'ANDROID_BOOTLOGO': '1', 'ANDROID_APP_PATH': '/data/data/org.electrum.electrum/files/app'})
11-14 18:14:01.067 26513-26535/org.electrum.electrum I/python: Android kivy bootstrap done. __name__ is __main__
11-14 18:14:01.067 26513-26535/org.electrum.electrum I/python: AND: Ran string
11-14 18:14:01.067 26513-26535/org.electrum.electrum I/python: Run user program, change dir and execute entrypoint
11-14 18:14:01.067 26513-26535/org.electrum.electrum I/python: main.py

1-14 18:14:05.552 26513-26535/org.electrum.electrum I/python: Traceback (most recent call last):
11-14 18:14:05.552 26513-26535/org.electrum.electrum I/python:   File "main.py", line 91, in <module>
11-14 18:14:05.554 26513-26535/org.electrum.electrum I/python:     imp.load_module('electrum', *imp.find_module('lib'))
11-14 18:14:05.554 26513-26535/org.electrum.electrum I/python:   File "/data/data/org.electrum.electrum/files/app/crystax_python/stdlib.zip/imp.py", line 244, in load_module
11-14 18:14:05.555 26513-26535/org.electrum.electrum I/python:   File "/data/data/org.electrum.electrum/files/app/crystax_python/stdlib.zip/imp.py", line 216, in load_package
11-14 18:14:05.555 26513-26535/org.electrum.electrum I/python:   File "<frozen importlib._bootstrap>", line 693, in _load
11-14 18:14:05.556 26513-26535/org.electrum.electrum I/python:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
11-14 18:14:05.556 26513-26535/org.electrum.electrum I/python:   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
11-14 18:14:05.558 26513-26535/org.electrum.electrum I/python:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
11-14 18:14:05.559 26513-26535/org.electrum.electrum I/python:   File "./lib/__init__.py", line 2, in <module>
11-14 18:14:05.562 26513-26535/org.electrum.electrum I/python:     from .util import format_satoshis, print_msg, print_error, set_verbosity
11-14 18:14:05.562 26513-26535/org.electrum.electrum I/python:   File "./lib/util.py", line 614, in <module>
11-14 18:14:05.566 26513-26535/org.electrum.electrum I/python:     import ssl
11-14 18:14:05.566 26513-26535/org.electrum.electrum I/python:   File "/data/data/org.electrum.electrum/files/app/crystax_python/stdlib.zip/ssl.py", line 98, in <module>
11-14 18:14:05.567 26513-26535/org.electrum.electrum I/python: ImportError: No module named '_ssl'
11-14 18:14:05.646 26513-26535/org.electrum.electrum I/python: Python for android ended.

**Comment by ecdsa** [comment]
compiling the APK with ssl is currently difficult. see gui/kivy/Readme.txt for instuctions.
