### ISSUE TITLE
cannot import name 'icons_rc' error while opening electrum wallet

### ISSUE THREAD

**Issue by vishva007** [spesmilo/electrum#3042]
Hi,

I have electrum 2.9.3 installed in a Ubuntu 17.03. I tried to open the gui, but it was closing without any window opening . 
So I tried to open it with terminal. I saw the following error :

:~$ electrum
cannot import name 'icons_rc'
Error: Could not find icons file.
Please run 'pyrcc5 icons.qrc -o gui/qt/icons_rc.py', and reinstall Electrum

I ran the above command and I get the following error :

:~$ pyrcc5 icons.qrc -o gui/qt/icons_rc.py
/usr/lib/python3/dist-packages/PyQt5/pyrcc_main.py: File does not exist 'icons.qrc'

I tried reinstalling electrum but no change 
I tried reinstalling using "sudo -H pip2 install --log=installation.log -vvv https://download.electrum.org/2.9.3/Electrum-2.9.3.tar.gz"
I saw no error while installing . This is the install log -> https://pastebin.com/Y3en7ifD 

How do I fix this issue and open my electrum wallet ?

Electrum : 2.9.3
OS : ubuntu 17.04
Python versions : both 2.7.13[runs with the "python" command] and 3.5.3[runs with "python3" command]

Thank you

**Comment by ecdsa** [comment]
you mixed up versions.
please do not open an issue for that

**Comment by vishva007** [comment]
How do i fix this now ? I can't open my electrum wallet now and it has some btc in it .  
And by mixing do you mean python versions ?

**Comment by SomberNight** [comment]
electrum 3.0 (unreleased, development version) uses python3, pyqt5 and pyrcc5
electrum 2.9.3 (latest release) uses pyton2, pyqt4 and pyrcc4

See what was meant by mixing versions?
I suggest `cd`-ing into a folder with a specific version of Electrum, and running `./electrum` there.

**Comment by vishva007** [comment]
I previously tried to run electrum from the github master branch code. That must have screwed up electrum installation.

I tried running the installing the dev version[from github master branch 3.0] again and it worked.

I will try installing 2.9.3 from github code and run it. Hope it works. Thanks for help @SomberNight  and @ecdsa  . Sorry for hijacking the issues thread on github.

**Comment by nitinsurana** [comment]
I'm getting the exact same error, but in a different usecase.

I'm having venv with python3.5.2. Executing `python3 electrum` works and the UI starts. But when I build for macOS using `python3 /usr/local/bin/pyinstaller --name 3.0.5 --clean --log-level DEBUG ./contrib/osx.spec`, then the generated executable throws the `icons_rc` error. Any pointers ?

**Comment by marijnfs** [comment]
I have this problem as well on debian. explicitly opening through python3 or running setup with python3 doesn't seem to help.

**Comment by lzsaver** [comment]
Python2 + PyQt4:
`pyrcc4 icons.qrc -o gui/qt/icons_rc.py -py2`

Python3 + PyQt4:
`pyrcc4 icons.qrc -o gui/qt/icons_rc.py -py3`

Python3 + PyQt5:
`pyrcc5 icons.qrc -o gui/qt/icons_rc.py`
