### ISSUE TITLE
Unable to import private keys

### ISSUE THREAD

**Issue by andrew0776** [spesmilo/electrum#3043]
Hi,
I'm using electrum-2.9.3-portable.exe
I was playing with multi-signature wallet option and created such type of wallet
Then I deleted the default_wallet file as well as all the files in the Electrum directory
And started a new standard wallet
The issue is that now the option "Wallet" - "Private Keys" - "Import" is not shown any more
Also I can see that options "Seed" and "Master Public Keys" are still shown
I don't understand where "Master Public Key" is saved on my PC now
It's not possible to get rid of multi-signature config

![no_import](https://user-images.githubusercontent.com/32815066/31585061-69a8e752-b1c3-11e7-93be-e07146df50b6.png)

**Comment by SomberNight** [comment]
> The issue is that now the option "Wallet" - "Private Keys" - "Import" is not shown any more

That option is not shown for deterministic wallets (e.g. those with a standard Electrum seed) to avoid confusing users as some might assume that imported keys would also be recoverable from seed alone (which is not the case).

You should create a new wallet that explicitly allows importing private keys.
In version 2.9.3, in the install wizard, choose `Standard wallet`/`Use public or private keys`.

**Comment by andrew0776** [comment]
Thank you, SomberNight. Yes, I can see "Import" option after creating a new wallet with the option "Standard wallet - use public or private keys" and entering a private key. But if I do again "Standard wallet - Create a new seed", I still see that public private key which is taken from unknown place. Can you tell me where the multi-signature wallet configuration is saved on my PC? It's not in any files, because I deleted everything and started from the scratch. Is it saved somewhere in the registry?

**Comment by SomberNight** [comment]
> I still see that public private key which is taken from unknown place

What do you mean? Please clarify.

> Can you tell me where the multi-signature wallet configuration is saved on my PC?

Wallets (regardless of type) are stored in `%appdata%/Electrum/wallets` on Windows (except for portable installations).

**Comment by andrew0776** [comment]
Thank you, SomberNight. Sorry, it was some misunderstanding from my side. Now I can see it works as expected. Thank you for you time!
