### ISSUE TITLE
Is there support for testnet?

### ISSUE THREAD

**Issue by JikkuJose** [spesmilo/electrum#3048]
Have been trying to find some information on support for testnet, I ended up not finding anything meaningful. Can someone clarify is there any support for it or provide some pointers?

**Comment by SomberNight** [comment]
There is.

https://github.com/spesmilo/electrum/blob/6b9bfddda2d9b8febf88f1264be70f1e0e359396/lib/commands.py#L830

Use the `--testnet` option when invoking Electrum.

**Comment by AbdussamadA** [comment]
ask in the forum not here. this place is for bug reports and development.

https://bitcointalk.org/index.php?board=98.0
