### ISSUE TITLE
2FA wallet creation TOS crash

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3062]
(originally reported at https://github.com/spesmilo/electrum/issues/2968#issuecomment-335046788)

On git master 0a648e2b1cdb7852d80c0626c62984ef01c1c7e9.
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/plugins/trustedcoin/qt.py", line 210, in on_result
    tos_e.setText(self.TOS)
RuntimeError: wrapped C/C++ object of type QTextEdit has been deleted
Aborted
```
There might be other ways to reproduce (I seem to recall there are), but a reliable way is to
- enter an email address and then click next, **before** the daemon thread receives the TOS over the network (Not too hard to accomplish when using a high-latency proxy.)

**Comment by ecdsa** [comment]
heh, I guess we should disable next until TOS are received.
