### ISSUE TITLE
stolen btc?

### ISSUE THREAD

**Issue by helloyello33** [spesmilo/electrum#3070]
I have recovered my electrum wallet with my seed. I wanted to send a rather large transaction to the address I know, I triple checked address is good, I put in 6170 mbtc to send, and then my password. then after that, all my wallets btc, which is more than 13 btc, got sent to a different address.
im devastated and dont know what happened why happened..... pls someone help me, It looks like I lost 70k usd. my browser history shows eelctrum.org that i went there before i downloaded the wallet to recover my wallet. is there anything to do here?? or its lost and I was part of a scam....
thanks for any comments

**Comment by ecdsa** [comment]
it might be a keylogger.
please have your computer investigated by a security expert.
(stop using it, as it might destroy evidence)

**Comment by RusAlex** [comment]
`eelctrum.org` is not correct url of electrum wallet software

**Comment by ecdsa** [comment]
@helloyello33 did you really visit eelctrum.org or is that a typo in your post?

**Comment by helloyello33** [comment]
i checked in my browser history, i mistyped probably or have no idea how but it went to this scam website, my history shows eelctrum.org
i stopped using my laptop as you said. it was weird bc I installed the software and put in my recovery seed and the wallet didnt come up. then I clicked the the standalone exe file again
and the wallet came up after I entered my pasword all my money was there. I said its great. so I made my transaction and as I said above it sent not the amount that I have put in but all my wallet contents to a different address.....

**Comment by ecdsa** [comment]
well, if you visited eelctrum.org, no need to investigate more; you downloaded malware.
I will try to have that website removed by contacting their ISP

**Comment by ecdsa** [comment]
sadly there is nothing we can do, your coins have been stolen.

**Comment by helloyello33** [comment]
when i download the standalone exe file from the right webiste it has different file size then the one I donwloaded.... and this happens if I mistype one letter in the word electrum, doesnt matter which letter, it goes to the malicious site. but Im asking this, how is it possible to recover my wallet from a malware, it recovers something that they otherwise wouldnt have? how do the hackers whatever have this kind of information.... to be able to log into that wallet (bc i gave my correct seed and then basically I was already done???)
also what is keylogger, dunno much about that. this is a cybercrime, no? can it be investigated more?

**Comment by helloyello33** [comment]
if you mistype any letter with electrum, the right website pops up https://electrum.org/#home
what is this?

**Comment by ecdsa** [comment]
yes, I saw that too. it looks like this website randomly redirects to electrum.org. 
that is probably in order to avoid attracting attention

**Comment by ecdsa** [comment]
note: the following names are active and phishing:
`eelctrum.org`
`electurm.org`
`electrmu.org`
`eletcrum.org`
`elecrtum.org`
I will update this list if I find more

**Comment by AbdussamadA** [comment]
bitcoin transactions are irreversible so if the money is gone it's gone. nothing can be done about it. sorry for your loss.

the seed allows them to recover your whole wallet. since you installed their software and gave them the seed they got access to all your bitcoins.

**Comment by helloyello33** [comment]
thanks for the info guys. the irreversible part I understand, but no trace even if I give the address to someone? or get the domain where it is registered and go after that. just bc its a lot of money....

**Comment by ecdsa** [comment]
you should definitely file a police report with the address.
for the domain registration, it is likely that they did it anonymously

**Comment by helloyello33** [comment]
im impressed a little bit by the way they stole money from me. may they rot in hell though, this was no slouch job. please let this post beware of these phishing websites, I just lost years of savings..... devastated.

**Comment by ecdsa** [comment]
we will try to have these phishing websites closed.
I also added a warning with a screenshot of the URL bar to https://electrum.org/#download
unfortunately there is nothing more we can do.
