### ISSUE TITLE
JSONRPC: Make password missing error explicit

### ISSUE THREAD

**Issue by danuker** [spesmilo/electrum#3073]
I was using the `payto` command without a password.

The error message I got was an assertion failure in `public_key_from_private_key` (`assert pkey`). 
This was very confusing, and it took me quite a while to figure out the problem: I was not sending the password.

Please validate that the password is provided in the JSONRPC arguments if the wallet requires it, and return a friendlier error message.

**Comment by ecdsa** [comment]
it does. please upgrade your software before posting issues.
