### ISSUE TITLE
Electrum Portable freezes frequently

### ISSUE THREAD

**Issue by lothendriel** [spesmilo/electrum#3076]
I have loaded the portable Electrum wallet on a Samsung 32GB USB stick and it freezes a lot. Freezes on exit, freezes on trying to add contacts, freezes going into and adjusting preferences. No matter what computer I'm on it seems.

Is there a fix for this that I can do without much technical experience? Thanks!

**Comment by lzsaver** [comment]
Have you tried on another flash drive?

**Comment by ecdsa** [comment]
that's a windows problem.
we cannot fix it. don't use the portable version if it does not work on your system.
