### ISSUE TITLE
Cosigner Pool plugin can't handle multiple multisig wallets open

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3080]
Possibly not a real world use case, certainly not a common one, but I've run into this during testing.

With more than one multisig wallet open simultaneously, depending on the order of these being opened/closed, the Cosigner Pool plugin only deals with at most one of them.

Probably because there is only one instance of the plugin running, and that instance works as follows:
https://github.com/spesmilo/electrum/blob/0c967e555e3408f97a6dc168931cb1dc0bd223c6/plugins/cosigner_pool/qt.py#L111-L117
https://github.com/spesmilo/electrum/blob/0c967e555e3408f97a6dc168931cb1dc0bd223c6/plugins/cosigner_pool/qt.py#L122-L135

EDIT: Maybe at least the scenario where one **had** multiple multisig wallets open, but then closes all but one, should be fixed. (where currently even that single wallet won't have a functioning Cosigner Pool plugin)

**Comment by ecdsa** [comment]
indeed, there should be one listener per wallet.

**Comment by Transisto** [comment]
Was this using two portable versions?

**Comment by lunarovic** [comment]
> Was this using two portable versions?

I tried all three versions (standalone, installer and portable), the issue is the same.
