### ISSUE TITLE
[Windows] Electrum crashes when the wallet file is located on the network drive

### ISSUE THREAD

**Issue by Psychosynthesis** [spesmilo/electrum#3081]
Always when i'm using a network drive as a storage of the wallet, Electrum crashes after i input the pass.

Win 7, x64

**Comment by lzsaver** [comment]
SMB or NFS?

**Comment by Psychosynthesis** [comment]
to @lzsaver
I use a standard Windows network drives interfaces. So, i think is SMB.

**Comment by ecdsa** [comment]
this is probably the unicode issue. (fixed in python3)

**Comment by Psychosynthesis** [comment]
@ecdsa if this is fixed, why not update the exe's on this site - https://electrum.org/#download ?

Just want to store the file in NAS, but for now it's uncomfortable...

**Comment by SomberNight** [comment]
There isn't a new release for every single bug fixed. No reasonable project works that way.
Still, there will be a new release soon.

**Comment by Psychosynthesis** [comment]
@SomberNight This is obvious if it concerns any small bugs. But in this case, the program stupidly crashes, while the user does not do anything special. In such cases, usually release so-called. "hotfix".  I thought here on GitHub all coders are connoisseurs and heard about such things.

Anyway, I understand you. Thank you!.
