### ISSUE TITLE
"Not Verified" after 2 hours

### ISSUE THREAD

**Issue by BrentCB** [spesmilo/electrum#3082]
So my wallet shows that my transaction is "Not Verified" even though everything went through just fine.

I keep reading that this is a problem for a lot of people. D

Does this mean that my VTC Coins are NOT in my wallet? 

How can I get them "Verified"?

**Comment by lzsaver** [comment]
No altcoins, please!

**Comment by BrentCB** [comment]
what do you mean? The Electrum Wallet works with Altcoins.

So who do I talk to about this problem then?



Brent Cameron
Owner @ *CopyWritingControl*
https://www.linkedin.com/feed
https://www.Facebook.com/CopyWritingControl
https://medium.com/@CopyWritingStud

**Comment by lzsaver** [comment]
Electrum-VTC works with VTC. Vanila Electrum does not work with altcoins.

Look here: https://github.com/vertcoin/electrum-vtc/issues

**Comment by BrentCB** [comment]
Yep...I download and used Electrum-VTC. I have screenshots to prove it's
the correct one.

Since this is still "Not Verified" what do I do next?



Brent Cameron
Owner @ *CopyWritingControl*
https://www.linkedin.com/feed
https://www.Facebook.com/CopyWritingControl
https://medium.com/@CopyWritingStud

**Comment by lzsaver** [comment]
Do not ask in _spesmilo/electrum_, ask in _vertcoin/electrum-vtc_.

**Comment by BrentCB** [comment]
I did Alexx. Here's a screenshot where you can see that my question is
appropriately asked in the "*vertcoin/electrum-vtc"* area.

So what's the next step, now that I'm doing everything that I'm suppossed
to be doing, but nobody is answering my question.

[image: Inline image 1]



Brent Cameron
Owner @ *CopyWritingControl*
https://www.linkedin.com/feed
https://www.Facebook.com/CopyWritingControl
https://medium.com/@CopyWritingStud
