### ISSUE TITLE
"Sending"-Button broken

### ISSUE THREAD

**Issue by zmbcgn** [spesmilo/electrum#3084]
Hi!

I'm currently running the Windows version of electrum. (Version 2.9.3) . My OS ist Win10 and i'm not able to send any bitcoins because the sending button does nothing.

please help.

cheers 
zmbcgn

**Comment by bauerj** [comment]
Do you mean this one?

![image](https://user-images.githubusercontent.com/598790/31855116-679dcdfc-b6a4-11e7-93e6-93c958d46aea.png)

**Comment by zmbcgn** [comment]
excaclty.

**Comment by bauerj** [comment]
What kind of wallet do you use? (It's in the window title).

What happens when you clear all input fields and then click on send?

**Comment by zmbcgn** [comment]
i'm using a 2fa wallet and when i clear all inputs fields and click send also nothing happens. i just created a standard empty test wallet and there is the same behaviour.

**Comment by zmbcgn** [comment]
found something. when i disable ssl interception on my firewall, it works. i noticed that electrum uses it's own certification store. so i guess i need to copy my own CA certificate there. or i disable ssl interception at all..

**Comment by ecdsa** [comment]
@zmbcgn in the console, can you check the value of wallet.billing_info ?
@badmofo can you have a look?

**Comment by zmbcgn** [comment]
ecdsa: sure. how?

**Comment by badmofo** [comment]
@zmbcgn if you can disable ssl interception on a per-site basis i suggest you disable it for api.trustedcoin.com.  The 2fa plugin depends on unimpeded communication with that host in order to function properly.

**Comment by zmbcgn** [comment]
yep. works. thanks! as for me the issue can be closed than. i guess issue 
#2689 can be closed as well.
