### ISSUE TITLE
wallet becomes practically unusable once you have too many transactions

### ISSUE THREAD

**Issue by cryptonaut420** [spesmilo/electrum#3089]
Once you have several thousand transactions in your wallet, especially if you receive several hundred in a short period of time, Electrum becomes extremely ineffecient and practically unusable. It simply hangs on "synchronising..." forever (going on well over 12 hours now, even with several restarts) and it does not even show the correct balances. Creating a fresh wallet file with the same recovery seed does not work either, hangs on synchronsing and even worse, no transactions load at all. Trying to use different backend servers does not work either. This is the third time over the years that I've had to create an entirely fresh wallet and then use a different system (e.g bitcoind sever) to manually load in private keys and consolidate to the new wallet. After that, it works great for a year or so until I run into the same problem with a large tx history. 

Using v 2.9.3 on linux.

**Comment by bauerj** [comment]
The servers probably return an error because the history is too big for a response.

The client should show such errors to the user so they don't wait for something that will never happen.

**Comment by cryptonaut420** [comment]
right. Seems like if it tries to do the entire wallet history in one response, that should probably be broken up into smaller chunks.

**Comment by dabura667** [comment]
Yeah. It’s mainly a server side problem.

Run your own personal ElectrumX server with lots of resources and set your rate limiting super high.

As long as you don’t make it public, only you will connect.

**Comment by ecdsa** [comment]
there are already issues open about that, that are less vague

**Comment by cryptonaut420** [comment]
I looked and didn't see any, but I guess I must have missed them. 

Looking forward to seeing more efficient backend servers that make the wallet suitable to long term / power users like myself.

**Comment by ecdsa** [comment]
note: it is a good idea to create a new wallet from time to time; you will leak less info to servers

**Comment by kyuupichan** [comment]
@dabura667 it's not a server side problem; the client does scale poorly, and the problem with history is a protocol problem.
