### ISSUE TITLE
Import Privkey from bitcoinpaperwallet.com not work

### ISSUE THREAD

**Issue by RadentMamad** [spesmilo/electrum#3093]
Dear Dev of Electrum...
today i try to import privkey from bitcoinpaperwallet.com to electrum wallet, but why can't work.
thanks

**Comment by SomberNight** [comment]
What version of Electrum?
What is the first character of the private key? "5" or "K"/"L"
Can you elaborate (give more details) on what is actually happening and when?

**Comment by RadentMamad** [comment]
version 2.9.3 install on windows 10, not portabel.

**Comment by SomberNight** [comment]
so... what is the problem? I can import that into Electrum 2.9.3 on Windows just fine.

**Comment by RadentMamad** [comment]
this is my error screenshoot 
![11](https://user-images.githubusercontent.com/9060568/31867045-9cdf805a-b7b2-11e7-8788-5fe2f326fe50.png)
![12](https://user-images.githubusercontent.com/9060568/31867048-a323550e-b7b2-11e7-8111-78dc0ff79ae5.png)

**Comment by SomberNight** [comment]
That error just shows that Electrum could not find any bitcoins that can be spent by that private key. Which I assume is what you expected, given you just shared the private key with the world.

**Comment by RadentMamad** [comment]
I just tried to take my bitcoin from the wallet paper that actually have a balance, it can.

Will import privkey to electrum always cut some of my Bitcoin?
This I have import bitcoin a number of 0.5 BTC but that goes 0.49980881 BTC, so it decreases 19119 satoshi.
cbe8e2ca5d5bc3377b37827e818666f069f87ada2a57aa72ab5fbfb15e5d976c

**Comment by SomberNight** [comment]
What you did is not "importing" but "sweeping". Sweeping involves **sending** the coins to an address that belongs to your Electrum wallet. To do this, you create a bitcoin transaction, which has fees. The fee is the difference that was "cut".

**Comment by SomberNight** [comment]
You need to create a new wallet that specifically allows importing private keys.
In version 2.9.3, to do this, choose `Standard wallet` and then `Use public or private keys`.

**Comment by RadentMamad** [comment]
Okay.. thanks very much...
I just found out that way. I'll try someday.

The privately imported trial of some of my previous addresses was unsuccessful, not because there was no balance, but I suppose because the address may already be linked to other wallet platforms, since that is my active address in Omni Wallet, Blockchain Wallet and Counter Wallet.

**Comment by RadentMamad** [comment]
Is wallet electrum able to get Bitcoin Gold reward, if my bitcoin balance stays in wallet?
Does it need an additional setting for it?
