### ISSUE TITLE
Incorrect balance and sent amount

### ISSUE THREAD

**Issue by Maxikq** [spesmilo/electrum#3094]
Hi,

I noticed issue with history, it shows incorrect sent amount (should be -0.001 BTC, but in Electrum it's -0.000373). It happens for address: 197kz71iVkD66Xrr3fKapPFuxTRpZmDxo3 and standard wallet retrieved from public key. However, if I create a wallet "Watch bitcoin addresses" it shows amounts properly.

I tried to create a new wallet, but this issue still occurs.

**Incorrect values in standard wallet retrieved from public key:**
<img width="846" alt="screen shot 2017-10-23 at 00 26 07" src="https://user-images.githubusercontent.com/3128467/31867067-0e49d5d0-b789-11e7-8c53-f3395d019b62.png">

**Correct values in "Watch bitcoin addresses" wallet:**
<img width="842" alt="screen shot 2017-10-23 at 00 34 33" src="https://user-images.githubusercontent.com/3128467/31867115-ccafe262-b789-11e7-831f-e4fe593cf258.png">

**Comment by SomberNight** [comment]
Is that a transaction that sends to another address belonging to this same wallet? The history tab shows differences from the perspective of the whole wallet.

**Comment by Maxikq** [comment]
@SomberNight transaction has been sent to address not related with this wallet. Yes, transaction details seems to be correct, but history is not.

**Comment by Maxikq** [comment]
@SomberNight Uhh, you're right, It's because some BTCs has been transfered to change address.

**Comment by hotbits420** [comment]
1)do not know if this transaction reference is from MY history or the
result of my choosing this thread during one of my frantic ,fedup ,but not
ready to give up tantrums .

2)regardless,i have conducted all those actions and as test!

                 3) "experimenting" ensued and not in lieu of ACTIVELY and
ceaselessly searching  and asking  everywhere.
4) after a month i finally got AN E-MAIL !a direct response or a
confirmation that there may be others resorting to "creative"methods" to
understand or JUST plain stupid as I,either way I GOTMAIL !
                                                       5)I BLAME
BLOCKCHAIN. no reason that"experimenting"need engage ever! .i got more
confused reading their PDF instructions   YES i do understand  the security
and nature of the BLOCK-CHAIN!
                              Somber night please help me get on track or
direct me to some guidance i am breaching my own security .i am very
inspired by the cryptocurrency movement .proof that humans are
synchronizing in spite of and beyond ugly archaic governments .i will be an
advocate and asset .       thank you ! Shelly
