### ISSUE TITLE
build for Android

### ISSUE THREAD

**Issue by hannesa2** [spesmilo/electrum#3099]
I'm not able to build it for Android, I follow `gui/kivy/Readme.txt`with first command 

`make theming`

and this is the result 
>  make theming
> python3 -m kivy.atlas theming/light 1024 theming/light/*.png
> usr/local/opt/python3/bin/python3.6: Error while finding module specification for 'kivy.atlas' (ModuleNotFoundError: No module named 'kivy')
> make: *** [theming] Error 1

any clue what's wrong here ?

**Comment by SomberNight** [comment]
Try to install kivy.
https://kivy.org/docs/installation/installation-linux.html

And install buildozer.
https://github.com/kivy/buildozer#installing-buildozer-with-python3-support

Java JDK will also be needed
```
sudo apt-get install default-jdk
```

Install Python for Android
https://github.com/kivy/python-for-android
and put it here
https://github.com/spesmilo/electrum/blob/020f0637d7d8ec412df3762cfa9485a36574d274/gui/kivy/tools/buildozer.spec#L123

**Comment by hannesa2** [comment]
Thanks for the kick start guide ! It's almost perfect, this was missing
`pip3 install image`
now it works
