### ISSUE TITLE
URGENT - Replaceable Fee Problem !! 

### ISSUE THREAD

**Issue by abruzzy** [spesmilo/electrum#3100]
Hello
I am trying to send 1  BTC
https://www.blocktrail.com/BTC/tx/fc451382fcd1ccab9f6f251363b313b3270d6de939f766b05d113dccd161a2f2

Everytime i try to increase the fee i get an error: " CANNOT BUMP FEE: COULD NOT FIND SUITABLE OUTPUTS "

What can i do in this case ?

http://prntscr.com/h12gh7
http://prntscr.com/h12gpa
http://prntscr.com/h12gbr

**Comment by fireduck64** [comment]
Do you have any more funds in the wallet?  It looks like it can't increase the fee.

Reading the code, first it reduces your change (you have next to no change) so can't do that.
Next it should try to find other unspent outputs to use.  If you don't have any worth enough, you get this error.

**Comment by abruzzy** [comment]
Yes i still have around 0.22 BTC in the wallet ! and still getting the same error !

**Comment by lzsaver** [comment]
Your tx is confirmed.
