### ISSUE TITLE
Importing private keys takes way too long

### ISSUE THREAD

**Issue by daneos** [spesmilo/electrum#3101]
I have a file with over 8000 private keys backed up from numerous versions of Satoshi client using `dumpwallet` command.
I'm trying to create new Electrum wallet from this file.
It's currently running for over 24h, constantly using 100% of one processor core and I have no way of telling if it just hanged or if it will finish someday.

Electrum version is 2.9.3 running on Linux Mint 17.3.

**Comment by fr3aker** [comment]
I noticed this problem, too, in an earlier version. It appears to be a GUI problem. It seems the complexity of adding private keys scales exponentially with the amount of keys added. Adding them in batches of 500 worked but adding even a single more key to the text field would again cause Electrum to hang for a couple of seconds.
