### ISSUE TITLE
Getting Started asking for module dns?

### ISSUE THREAD

**Issue by elcolie** [spesmilo/electrum#3103]
> If you downloaded the official package (tar.gz), you can run Electrum from its root directory, without installing it on your system; all the python dependencies are included in the 'packages' directory. To run Electrum from its root directory, just do:
>./electrum

Refer to #3097 It is not fully support Python3 yet
Here is my setup
1. Download the latest relase `.tar.gz`
1. pyenv using python 2.7.14
1. `./electrum`

**Error:**
```bash
(electrum) sarit@sniper:~/electrum-2.9.3$ ./electrum 
Error: No module named dns. Try 'sudo pip install <module-name>'
(electrum) sarit@sniper:~/electrum-2.9.3$ python -V
Python 2.7.14
```

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/blob/55e6c247bc79e2a13625e1d0c40a68af7625657c/RELEASE-NOTES#L1-L6

**Comment by elcolie** [comment]
I use `pyenv`. Instead of install python3-pyqt5. I have to use `pip install pyqt5`
