### ISSUE TITLE
Android app won't pass the startup screen unless online, at least temporarily (ver 2.9.3.0)

### ISSUE THREAD

**Issue by JazzTp** [spesmilo/electrum#3104]
The Electrum Android app (ver 2.9.3.0) doesn't go past the startup screen unless online, at least temporarily online.

It happens on two different phones, with Android 5+ and 6+.

The app _**should**_ also be able to start with the phone offline, in flight mode, no data connection no wifi, because it could be used as cold storage (alone or more prudently for a multi-signature wallet, given the number of radio devices a smartphone contains).

Once the app startup has finished, the phone can be put again offline in flight mode and the app can successfully sign transactions.

**Comment by JazzTp** [comment]
Ver 3.0 starts ok also when offline. Closing this issue.

**Comment by ecdsa** [comment]
thanks for the info

**Comment by JazzTp** [comment]
Thank you for the great work, Thomas.
