### ISSUE TITLE
BIP32 generated addresses

### ISSUE THREAD

**Issue by dylankilkenny** [spesmilo/electrum#3105]
I generated addresses using my master public key and I'm only after realising the addresses I sent bitcoin to are beyond the gap limit of my electrum wallet. 

So in short I have 20 unused addresses in my wallet, I generated 50+ addresses and sent bitcoin to alot of those addresses but my wallet hasn't picked up those addresses so my wallet balance appears as 0.

Is there any way from me to load in the address that I have been sending bitcoin to?

**Comment by lzsaver** [comment]
_View -> Show Console_
go to the Console tab
type this code:
`for x in range(0, 100): print(wallet.create_new_address(False))`

**Comment by dylankilkenny** [comment]
Worked great, Thank you

**Comment by dylankilkenny** [comment]
Unfortunately this method hasn't loaded all of the addresses that payments were sent to. Is there anything else i could try?

**Comment by lzsaver** [comment]
Try it again. You may change 100 to let's say 500.
