### ISSUE TITLE
wrong transfering

### ISSUE THREAD

**Issue by Perviz-ganca** [spesmilo/electrum#3109]
Yesterday evening I transferred from my account to this address: 1taZJX62ZWA3RRrnoFGhGhLvicTjtxeiw all my bitcoin. Please help me.
![print screen](https://user-images.githubusercontent.com/33023805/31966656-6884a31a-b91c-11e7-9b40-5e8b490f6f7a.jpg)

**Comment by lzsaver** [comment]
Okay. You transferred your bitcoins. And? It was not expected, right? I do not understand your issue.
