### ISSUE TITLE
Error: Keep on Missing my accounts in the default wallet

### ISSUE THREAD

**Issue by rylcrypto** [spesmilo/electrum#3112]
Dear Electrum,

My wallet keep on missing some bitcoins. I log in yesterday and some of it missing. Then I re-log in saw it again. Now I Log In and the Account are missing.. What is happening. Is this a sync problem?

**Comment by SomberNight** [comment]
Please provide more details.
What version of Electrum? Are you using the QT graphical user interface? Is the orb in the lower right green/blue? Are there more or less transactions in the `History` tab than what you would expect?

**Comment by rylcrypto** [comment]
Great Day,

I got version 2.8.3 and has no QT GUI.

The orb turns green.

I was expecting more transactions in History Tab but I get missing wallet balances instead

**Comment by ecdsa** [comment]
not clear.
