### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by xlodei** [spesmilo/electrum#3116]
Здравствуйте, при использовании вашего кошелька Электрум у меня произошла проблема. October 23, 2017 at 22.42,Я пытался отправить 1 btc, со своего кошелька ELECTRUM на адрес 1AknSTg5hNBLqnWUQARVBLiHPUPeadogd5, однако мне постоянно появлялась "ошибка транзакции", затем транзакция все таки состоялась но биткоины ушли на адрес 19rq6LDMD4fYYu1SjmPB215aYXUDSd9bqZ который я не указывал! По моему мнению ошибка произошла на Вашей стороне. Какая то ошибка вашего сервера. Подскажите как мне вернуть теперь свои биткоины???
Hello, when using your electrum wallet I had a problem. October 23, 2017 at 22.42,I tried to send 1 btc from my ELECTRUM wallet on 1AknSTg5hNBLqnWUQARVBLiHPUPeadogd5, but I kept getting a "transaction error", then the transaction still took place but bitcoins went to the address 19rq6LDMD4fYYu1SjmPB215aYXUDSd9bqz which I did not specify! In my opinion an error has occurred on Your side. Some sort of error on your server. Tell me how can I return my bitcoins now???

transaction ID 9f19200017a6fb20fd8c4d7e893c301f8a26bd482a98cc2169752dd2517e1ea0

**Comment by ecdsa** [comment]
there is no "our side", we are not a bank. 
we are not involved in the transactions that you make. 

if you send your money to the wrong address there is nothing we can do

**Comment by xlodei** [comment]
That's it, what I sent to the right one, I rechecked, clicked to send, an error popped up, but in the history there was a transaction to quite another address as possible? It's not my fault!

**Comment by xlodei** [comment]
That's it, what I sent to the right one, I rechecked, clicked to send, an error popped up, but in the history there was a transaction to quite another address as possible? It's not my fault!

**Comment by ecdsa** [comment]
we have no way to know what you did.
it can be a mistake from you, or some virus on your system that replaced the address.
if you believe it is not a mistake, you should have your computer investigated by a security expert.
