### ISSUE TITLE
this doesn't work

### ISSUE THREAD

**Issue by doug111** [spesmilo/electrum#3119]
! have spent an hour so far with the app and also the desktop version. All ! want to do is get my BTC on BCH off my paper wallet. When ! do receive it pops up with a QR code. Unfortunately my paper wallet doesn't read QR codes (duh). On the desktop version, ! got to "create keystore from keys". !'ve entered the private key twice and the public key once. The "NEXT" button stays greyed out so ! can't click it. The only options ! get are "back" and the QR reader button. The QR button says it can't open because something called a Zbar is not installed.

**Comment by ecdsa** [comment]
we do not support BCH, and this place is only for bug reports
