### ISSUE TITLE
Will my Electrum wallet follow the Segwit2x chain?

### ISSUE THREAD

**Issue by billkle1n** [spesmilo/electrum#3120]
After the Segwit2x hard fork, which chain will Electrum follow by default? Is it going to follow whichever chain with the most PoW?

**Comment by ecdsa** [comment]
read the docs

**Comment by billkle1n** [comment]
I did and nothing came up:

<img width="1094" alt="screen shot 2017-10-28 at 22 53 23" src="https://user-images.githubusercontent.com/30122870/32141043-da89b5b8-bc32-11e7-9aa1-938495c72eeb.png">
