### ISSUE TITLE
Please add option to avoid Tor Proxy for localhost server connections.

### ISSUE THREAD

**Issue by dan-da** [spesmilo/electrum#3126]
With my current setup which is using --oneserver against electrumx on localhost, if I check the "Use Tor proxy at port 9050" option then I immediately lose the server connection. I assume this is because it is trying to connect to localhost over Tor, which of course fails.

So it seems that at present one cannot simultaneously route requests to 3rd party providers (eg exchange rate) over Tor and also connect to a local electrum server. That would be the most private setup, I believe.

One possible solution would be an option such as:
   [x] avoid proxy for localhost server connections

It doesn't appear to be possible for user to work around this via torrc either.  Tor project explicitly avoids allowing localhost connections through Tor proxy.  At least according to https://tor.stackexchange.com/a/12688.

This issue is created as a followup to #3028, as I'm still trying to achieve usage of electrum client without leaking host's IP (beyond first tor hop).

**Comment by emilrus** [comment]
What you can do to work around this is to configure a hidden service pointing to your electrum server.

**Comment by dan-da** [comment]
@emilrus that's a good suggestion, thx.   I will look into that.

I do think though that electrum can make this a lot easier for people with just a small change.
