### ISSUE TITLE
disappearance of $32 during $50 transaction

### ISSUE THREAD

**Issue by adextetoo** [spesmilo/electrum#3138]
today (27th of October, 2017) i made a transaction using the electrum system application from my address 1QCqpLmdJLmMe2QFZFZNpc2beKnBKXAaYY sent $50 (0.0086775) to 1MeWrEdU38MvZLMcLprbrZV8gnfCkr419Y, unfortunately another transaction from my address occurred to 17nwGZGUwRRUpFKV7FvqPrEvVa22bHtYJt (0.0056668) . till this moment i dont know what happened during the transaction. this is the transaction id 1428c9aae0ef353fdd9667ad59d2b0c04ef99e9f124e5f7d4b1d460568e484c5 , i will be happy if an explanation can be made.

**Comment by SomberNight** [comment]
https://en.bitcoin.it/wiki/Change
