### ISSUE TITLE
3 Outputs in same transaction

### ISSUE THREAD

**Issue by Sancap** [spesmilo/electrum#3139]
I send only 0.002 BTC from my Electrum Wallet can you check in this hash tx: 3ca01bc116a67504bf43be8d1d9052d7b6ff6cbaa7ff3e800d818ec483ba013f   but appear in this transaction this Address 17RrnCKQy3DxeHuhDRnFFFJYbHQdRR1TAN  with amount 0.005 BTC i dont know what is this. In my Electrum wallet show total debit 0.007 BTC but i swear i send ONLY 0.002 BTC. Its another chain the 0.005 BTC ? Maybe I was hacked ?  Please help me to solve this problem. Why in same Hash have 2 differents Address? And why debit to my wallet 0.005 BTC without my consent?
Thanks.
Ricardo.
![transaction](https://user-images.githubusercontent.com/33169114/32130639-2ffdd6a6-bb6a-11e7-98aa-0e5cffe50e20.jpg)

**Comment by dabura667** [comment]
Probably you got hacked.

**Comment by SomberNight** [comment]
Are you using a 2FA wallet?

I'm guessing the outputs are:
- intended destination
- change
- 2FA tx prepayment

![issue_3139_2fa_prepayment](https://user-images.githubusercontent.com/29142493/32131576-08bfbeb8-bbb2-11e7-84dd-57170f55955e.png)

**Comment by Sancap** [comment]
Maybe this issue is because i have in Settings "Use Change Addresses". Do you guys use this option? And yes i use 2FA.

**Comment by AbdussamadA** [comment]
It's the 2fa fee like SomberNight said. Please use the forum for such questions in future:

https://bitcointalk.org/index.php?board=98.0

**Comment by Sancap** [comment]
Thanks SomberNight now i confirm its the cost for 2FA for 100 Transaction. I only see 0.00005 but not BTC/tx. So the cost for 2FA is 0.0005 x 100 transactions = 0.005 BTC. So i pay without knowing for that service. Thanks guys for help!
