### ISSUE TITLE
How does this PGP file signature stuff work?

### ISSUE THREAD

**Issue by imkane** [spesmilo/electrum#3142]
I'm super confused with how to verify that a downloaded file is legit before I run it. #safetyfirst

Why isn't this described in the docs? I surely can't be the only one confused. Most file signatures use some form of SHA.

Here's what I tried:

1. I used this tool: http://cirw.in/gpg-decoder/

2. Pasted the entire contents from https://download.electrum.org/2.9.3/electrum-2.9.3-setup.exe.asc, clicked "Decode"

3. Observed that it said (so I assumed it was giving me the SHA-512 sig):
`hashAlgorithm: "SHA512 (0xa)"`

Also:
`signature: "2275e40c14a1abd645b427d6d875773a7b75c44390c3b72e3470729dc7b1d11a751902bb0c1b56ad0c8118b6b5c9bcf3ae25f6574c5ced2a27001aa92307fc6822dc79fadc9a3f1c42ee6db31b3b9c72c01445e935aad618596d340e2fc2f983769dd888263d4596144f58d9cc1f03c6c79e7a940cb1769022ecaed5768d4e7f83ff75b82e7c0910a228350184707f979670800bf31d51e65adefaffac1c9a5e7c7c07e241f80dd92a5f48b3663958dc2964db89c3e5bfbfc213d436edb9e31415ec44ef949e3f532638c01a8d9372bb2b3d6aa2bef7e68258d84432f5d4a702174b552cea558440ad13607bd4d06049012551ef0d9f92caa9b4f917399dfd2218144b7b06052291bf74ce4cb0a65ac0d8f8f02bc8b128be515977491acfb7febb662cb880bf7f0ca118b79c88bb4d2c4c6aa636096647120ebf7e542307b778cee476e02c9b48bcad869515cd089b40385b7566613daa0e3c0bf332d60f6c8fd73ab04edbbd66708910817f485105a2e9192e61bb30d5dc778a28f7221375f86863e099dd8042d1f1d5026d97afca4710dd4cc07106e47469fdbb499ff0ddf7d53149b0a5f288e914967ae6fc25e8bc64cc0b1a72e8ac3a6f0ba16b053f844b43896ddb93f4bc6d03f6991ca84f2fba0dffb54c7a15dc8b20560a5ba2e0a0d9e5fa778c72e738c59c3dcdc7a34bcc85a10d8289c76c5537d07db5a734e885ee"`

Then in Windows I used the "MD5 & SHA Checksum Utility 2.1" on the .exe which resulted in an SHA-512 of:

`9222137882A13C5FBD29BE6F1B45338F1BF09195341C54CA9049B117E7D6DE5CFADCD1C5015A9C70673433B01C38C7E5DBDB2CA7153062D9BC5DFF216D6E96F9`

**Comment by fr3aker** [comment]
SHA is not a signature but a checksum. It does not guarantee the creator of the checksum is a trusted entity.

A PGP signature does guarantee that the file has not been modified and has been approved by the owner of the PGP key.

A popular program to verify PGP signatures on windows is gpg4win.

**Comment by imkane** [comment]
Ok thanks, but do I use for the "Private Key" that most of the decrypter tools ask for?

**Comment by imkane** [comment]
Using https://pgptool.github.io/

![screenshot - 10_28_2017 11_56_56 am](https://user-images.githubusercontent.com/2041683/32137560-2f7b1438-bbd7-11e7-9c47-5c36c6625d37.png)

**Comment by imkane** [comment]
Also tried using Gpg4win along with "ThomasV"'s public key from https://pgp.mit.edu/pks/lookup?op=get&search=0x2BD5824B7F9470E6

And no bueno :(

Obviously I'm doing this completely wrong, but I have no idea how to verify that this download is legit before running it. It'd be great if there were step-by-step instructions in the Electrum docs, similar to what Gpg4win provides here: https://wiki.gnupg.org/Gpg4win/CheckIntegrity

**Comment by imkane** [comment]
Ok I think I got it:

1. Install Gpg4win

2. In the Kleopatra app, Import ThomasV's public key from https://pgp.mit.edu/pks/lookup?op=get&search=0x2BD5824B7F9470E6 (have to copy and paste it to a file, starting from the "BEGIN" block - maybe there's an easier way to just download it?)

3. Download the signature file, https://download.electrum.org/2.9.3/electrum-2.9.3-setup.exe.asc

4. From the command-line, run: 
`gpg --verify electrum-2.9.3-setup.exe.asc electrum-2.9.3-setup.exe`
