### ISSUE TITLE
Ledger native segwit test failed

### ISSUE THREAD

**Issue by qazasds** [spesmilo/electrum#3144]
Hello,
I tested Ledger native segwit but it failed. Is it fully supported now? Thank you!

Test environment & steps:
1. Electrum 3.0 (master branch)
2. Ledger Nano S Firmware 1.3.1; Bitcoin App 1.1.10
3. Set env: export LEDGER_NATIVE_SEGWIT=1
4. Create new wallet->Standard Wallet->Hardware Wallet
5. The PATH dialogue popped up, I left it as default (m/44/0) (I thought it should be native segwit related value?)

6. Error message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Electrum-3.0-py3.6.egg/electrum_plugins/ledger/ledger.py", line 88, in get_xpub
    xpub = bitcoin.serialize_xpub(xtype, nodeData['chainCode'], publicKey, depth, self.i4b(fingerprint), self.i4b(childnum))
  File "/usr/local/lib/python3.6/dist-packages/Electrum-3.0-py3.6.egg/electrum/bitcoin.py", line 903, in serialize_xpub
    xpub = xpub_header(xtype) + bytes([depth]) + fingerprint + child_number + c + cK
  File "/usr/local/lib/python3.6/dist-packages/Electrum-3.0-py3.6.egg/electrum/bitcoin.py", line 894, in xpub_header
    return bfh("%08x" % XPUB_HEADERS[xtype])
KeyError: 'segwit'

**Comment by SomberNight** [comment]
Hi. Can you try with #3146 ? I don't have a ledger.

**Comment by qazasds** [comment]
Hello,
It works for p2wpkh, thank you!
I am going to do further tests for multisig wallet with ledger native segwit later.

**Comment by qazasds** [comment]
Hello,
I tested 2-of-2 multisig wallet (Ledger + Electrum). If xtype=p2wpkh (#3146), we will get error "Wrong key type p2wpkh". And I changed xtype=p2wsh, it works.
It looks like we need individual xtype for standard wallet (p2wpkh) and multisig wallet (p2wsh).

Thank you!

**Comment by ecdsa** [comment]
are you able to spend from p2wpkh with your ledger?

**Comment by qazasds** [comment]
Hi,
I tested to spend from p2wpkh (Ledger plugin with patch #3146 ) to p2sh-p2wpkh on testnet, and it failed:

error: {'message': 'the transaction was rejected by network rules.\n\n64: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)\n[0100000000010157917d13a6a8beda26cfe54c17c65cd9777d22792b8fd831e71174773a58d02a0000000000fdffffff02809698000000000017a914f9198f413e57dee7d04c2322c97f1d3a5bbd6db7873859620200000000160014cd861735ef6b795e131d7873af5ee3edb1fe17f502483045022100c595cae13b7de594db9acecd3d0affe4a82da8c90a602c1eca2dad05089d8a29022057b0e506133029da8318f0479605782bf8416ba54805c5805b56bfa159b655fd012102560f8226a5ca0d16c66962522094f36bc4e72dc7bc1c9a32ed35522d5ef161f1d47b1200]', 'code': -1}

**Comment by qazasds** [comment]
I made a successful test for spending from p2wsh multisig wallet with ledger today. Do you think it is ready for native segwit supporting for hardware devices? Thank you!

Test environment & steps:
1. Electrum master branch with arbitrarily set xtype=p2wsh in function on_hw_derivation()
2. btchip-python 0.1.23
3. Ledger nano s firmware 1.3.1
4. 2-of-2 multisig wallet with electrum p2wsh & ledger p2wsh, and spent to p2wpkh address.
5.Transaction data:
{
    "hex": "01000000000101fdd2522b9366080e67f61b9f2eb8e144136f295d3c25896d4fd285caa7c49f740100000000feffffff0214410f00000000002200201b398517bfbabb1284501fdd587df4962bca758187ab766df5caa528f35388ee80841e0000000000160014fc816bc88b700e1711280fb426d86d2515375d0d0400473044022074a805931549003b7854323ca52597813392c387b33af506ba90f29f496f2b4e022049d2d3a8b3b3d030a7a5ff0ca4fd06bb0c7029122bcd8ce3a79d2729a07320a001483045022100a8e82bca802b6eee8c2f42f9450563aeee5b122ba24bed2272852eeae5f054210220160f239f63846aa9f88f66857adb170934ac946a65c2d2ceb24f0610485679a301475221020aa318b16f931ba91b68e1c8154014bdcf062453efc37cb3df7c494e6509d53021035bc84f85017f42eee35da4b256856ee56eda163cf9dac6cb76a29b2a8e3469b552ae82c81200",
    "complete": true,
    "final": true
}

**Comment by SomberNight** [comment]
Thank you for testing it.

Support for `p2wsh-p2sh`, `p2wpkh` and `p2wsh` for hardware devices (or bip39 seeds) is unlikely to be included in a release until there is a standard/proposal for what derivation path to use for those kind of scripts. The project would generally like to avoid reusing derivation paths (as that means reusing private keys) for different purposes.

**Comment by qazasds** [comment]
That makes perfect sense, thank you!
However maybe we can consider to let users specify their derivation paths arbitrarily rather than waiting for the proposal. 
It's off topic, since this issue has been resolved, I am going to close it, thank you!
