### ISSUE TITLE
Electrum wallet not showing Trezor transaction history

### ISSUE THREAD

**Issue by zeiphod** [spesmilo/electrum#3151]
Hi

I've successfully created an Electrum wallet for my Trezor but it is not displaying the Trezor transaction history - should it be able to do this?

Trezor 1.5.2
Electrum 2.9.2

Thanks

**Comment by 7jaka7** [comment]
If you are talking about Bitcoins, did you checked if you have SegWit addresses? As I have seen Electrum is not supporting SegWit yet.

**Comment by zeiphod** [comment]
Thanks for the reply - yes that's possibly the reason, Trezor 1.5.2 accounts use SegWit addresses.
