### ISSUE TITLE
Cosigner Pool Fails to send transaction

### ISSUE THREAD

**Issue by johnvamo** [spesmilo/electrum#3152]
Hello,

I have the same error: Cosigner Pool Fails to send transaction to cosigner.
Both wallets have activated the plugin Cosigner Pool.
I am using version 2.9.2...Any advise?

Thanks for the help.

**Comment by ecdsa** [comment]
it was a server side issue. it should work now

**Comment by johnvamo** [comment]
Hello, I have tried again...and the same message...Failed to send transaction to cosigning pool.
???
Please help...
Thank you.

JOHN

**Comment by johnvamo** [comment]
When I open the wallet it shows a message: Unexpected magic characters

then I close it and the wallet seems to work as normal.
