### ISSUE TITLE
Electrum 2fa restore

### ISSUE THREAD

**Issue by Bonifaciy61** [spesmilo/electrum#3153]
lost access to a 2fa key, do the restore through the seed, but the balance is still zero in the new wallet. on the old all can be seen... I have tried everything that I found on the Internet. the currency is BTC, please help! support TCoin is silent... using mac, tried on windows, no result.

**Comment by ecdsa** [comment]
are you sure it is the correct seed?
if yes, did you add custom words to the seed?

**Comment by Bonifaciy61** [comment]
totally sure about this! kind of like you using another wallet to recover (ele... cash I do not remember the name) I tried using it and I swear that for a second I saw all of the transactions which you see now on your mac, but don't have access to them (coins I mean) tried to do the recovery through windows - all to no avail... please Explain what kind of custom words? I understand that this is not the seed of the word?

**Comment by ecdsa** [comment]
Not sure to understand what you mean; this lacks clarity. In any case, you cannot use electron cash to recover your bitcoins, it is not the same blockchain; this might explain why you do not see any transactions in your history.

Anyway, your report is not clear enough to understand your situation. the only thing I can guarantee is that if you use the same seed in Electrum, then you will see the same history and balance.
