### ISSUE TITLE
Synchronization wallet

### ISSUE THREAD

**Issue by ViktorVl7** [spesmilo/electrum#3156]
Hello!
The wallet is not synchronization. What is the problem?

**Comment by bauerj** [comment]
Hello!

Can you provide more details? What server are you connected to? What kind of wallet do you use? Did you try to restart Electrum?

**Comment by ViktorVl7** [comment]
Electrum 2.6.4. The server is automatically selected. Electrum restarted.

**Comment by bauerj** [comment]
Please update to 2.9.3.

**Comment by ViktorVl7** [comment]
Thank you.
