### ISSUE TITLE
Transaçao

### ISSUE THREAD

**Issue by arthurdoche** [spesmilo/electrum#3157]
A Parcial de 0,002 BTC fora para o endereço: 1DMaost2gEE5YW3AZHkkVeUH6E9p5SguPU ( 0.002 00000 ) Como a imagem abaixo esta mostrando. E esse endereço é desconhecido e não é o da Fox Bit. Mas no momento do envio foi inserido somente o endereço: 1M6PfyNSN9KsmtEcg8zvZW6BdfAvxtR4hv  que foi gerado no site da Fox Bit. Entendeu?

**Comment by arthurdoche** [comment]
Ola, meu envio para a carteira Foxbit foi dividido em 2, 0,002 foi para o endereço 1DMaost2gEE5YW3AZHkkVeUH6E9p5SguPU e 0.00041757 foi para minha carteira na foxbit no endereço: 1M6PfyNSN9KsmtEcg8zvZW6BdfAvxtR4hv , oque houve ?

**Comment by SomberNight** [comment]
Is this with a 2FA wallet? Because 0.002 BTC sounds like a TrustedCoin 2FA prepayment fee.
![](https://user-images.githubusercontent.com/29142493/32131576-08bfbeb8-bbb2-11e7-84dd-57170f55955e.png)

Alternatively, it might be [change](https://en.bitcoin.it/wiki/Change).

**Comment by arthurdoche** [comment]
A Parcial de 0,002 BTC fora para o endereço: 1DMaost2gEE5YW3AZHkkVeUH6E9p5SguPU ( 0.002 00000 ) Como a imagem abaixo esta mostrando. E esse endereço é desconhecido e não é o da Fox Bit. Mas no momento do envio foi inserido somente o endereço: 1M6PfyNSN9KsmtEcg8zvZW6BdfAvxtR4hv <https://www.blocktrail.com/BTC/address/1M6PfyNSN9KsmtEcg8zvZW6BdfAvxtR4hv>  que foi gerado no site da Fox Bit. Entendeu?


[cid:image001.png@01D3521D.6F1431C0]

[cid:image002.png@01D3521D.6F1431C0]

De: SomberNight [mailto:notifications@github.com]
Enviada em: segunda-feira, 30 de outubro de 2017 23:36
Para: spesmilo/electrum <electrum@noreply.github.com>
Cc: arthurdoche <arthurdoche@msn.com>; Author <author@noreply.github.com>
Assunto: Re: [spesmilo/electrum] Transaçao (#3157)


Is this with a 2FA wallet? Because 0.002 BTC sounds like a TrustedCoin 2FA prepayment fee.
[https://user-images.githubusercontent.com/29142493/32131576-08bfbeb8-bbb2-11e7-84dd-57170f55955e.png]<https://user-images.githubusercontent.com/29142493/32131576-08bfbeb8-bbb2-11e7-84dd-57170f55955e.png>

Alternatively, it might be change<https://en.bitcoin.it/wiki/Change>.
