### ISSUE TITLE
Cosigner Pool Fails to send transaction to cosigner

### ISSUE THREAD

**Issue by johnvamo** [spesmilo/electrum#3160]
I have been trying for 4 days to send a electrum transaction from a electrum shared wallet. Always it says: Failed to send transaction to cosigning pool...I am stucked ! 

The pluging cosigner pool is activated in both accounts....

When I inizialized the wallet is comes out a box saying: Unexpected magic characters...

help please...

**Comment by ecdsa** [comment]
"unexpected magic characters" is probably an issue with a trezor wallet

**Comment by johnvamo** [comment]
The question is...the message  "unexpected magic characters" prevents the transaction been sent to the cosigner's pool? Is it correlated? 

Because the transaction is been signed correctly by the trezor...is the moment when sending to the pool that comes out the problem of failing the transaction.

**Comment by ecdsa** [comment]
I restarted the cosignerpool server. please retry now

**Comment by johnvamo** [comment]
The transaction went through.. waiting for cosigner signature...til this evening...

Seams the server restarted solved the issue til now...

I will tell you the final result before closing the thread.

Thanks

**Comment by johnvamo** [comment]
Hello,

the cosigner wallet was opened after sending the transation to the cosigner pool....but shows nothing about where to accept or sign it...how to call it?

Thanks

**Comment by johnvamo** [comment]
I am checking the 3 ways of sending electrum multi-signature transactions... 1. File  2.QR code and 3. Cosigner Pool...which is most effective or recommended?

**Comment by ecdsa** [comment]
they all work, but cosigner pool sometimes is down

**Comment by johnvamo** [comment]
If the wallets are showing the same receive addresses, same balance, same shared public master keys...the sending transaction should work...both are signed with trezors... what other should be check in order to know the wallet are working correctly?

Thanks for the support.

**Comment by neocogent** [comment]
@johnvamo 
Usually when using the cosignor pool you will be prompted to confirm/sign the tx as soon as you open the cosigning wallet. There's no button or menu item to sign - it just pops up. But I have had times it wouldn't do that and I just tried sending again and it worked. It's really easy when it works.

**Comment by johnvamo** [comment]
I am going to resend the transaction to the cosigner pool again...
Thanks

**Comment by johnvamo** [comment]
At last the transaction went through...via the file option.
The cosigner pool did not work.

Thanks for the support given.

**Comment by Juaninappa** [comment]
Hello, can you pls advise why the cosignor pool is down in the Electrum testnet?
Thnaks

**Comment by bauerj** [comment]
Hey @Juaninappa 

the cosignerpool is currently offline as it is being moved to a different server. It should be back up soon.

**Comment by bauerj** [comment]
@Juaninappa It will be back up in a few hours now.

**Comment by aaxx** [comment]
Got the same error today - Failed to send transaction

**Comment by aaxx** [comment]
Error response
Error code: 501
Message: Unsupported method ('GET').
Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.

**Comment by bauerj** [comment]
What version of Electrum do you use?

**Comment by aaxx** [comment]
the latest, 3.1.*

**Comment by joshfutureforex** [comment]
I am having a similar issue, getting this error on Electrum 4.5:
![image](https://github.com/spesmilo/electrum/assets/147170659/2cb76f7d-e348-4077-a6be-cd9f8e86d620)

My colleagues get the same issue on Electrum 4.5.4
