### ISSUE TITLE
AWOL Bitcoins

### ISSUE THREAD

**Issue by Kirk2NCC1701** [spesmilo/electrum#3163]
My Electrum Wallet had BTC in it since 2014, and as recently as a couple of weeks ago.
When I checked today, 1. it was empty, and 2. it asked me for my BTC address.
WTF?  Has it been hacked? 
Thanks.

**Comment by ecdsa** [comment]
please post a screenshot of your wallet asking you for your BTC address

**Comment by Kirk2NCC1701** [comment]
Thank you for your prompt response.  Now it only shows an empty
wallet.
I copy/pasted my address into to pwd-protected Word file.
Can I recover it with the BTC address?
Thanks.
Kirk2NCC1701
On 31.10.2017 at 2:51 PM, "ThomasV"  wrote:

	please post a screenshot of your wallet asking you for your BTC
address

**Comment by ecdsa** [comment]
this is not useful. we cannot help you unless you post accurate information.

**Comment by ecdsa** [comment]
it is possible that you have been hacked.
it is also possible that you are confusing bitcoin address, wallet seed and wallet password.

closing this issue, because this is not helpful.
this is a place to report bugs so they can be fixed.
