### ISSUE TITLE
BTC not in wallet

### ISSUE THREAD

**Issue by quazzyquazzy** [spesmilo/electrum#3165]
I made a bitcoin transaction into my Electrum wallet last night (10/30) but the BTC never showed up. 

I looked up the transaction on tradeblock.com and it is showing that it went through and is confirmed but it has not shown up in my history and the BTC is not there. 

While I made the transaction Electrum was "synchronizing" and couldn't find a server but I have made transactions while it was doing this before and it always ends up popping up after it connects but not this time. 

also have tried using Electrum's load transaction tool to load the transaction i.d but just get error message {u'message': u"daemon error: {'code': -5, 'message': 'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.'}", u'code': -1}. I can confirm that the transaction is on tradeblock.com

I checked multiple times that I sent it to the correct Electrum address and it IS correct.

Confused, Please Help

**Comment by quazzyquazzy** [comment]
Now getting this message.. {u'message': u'https://blockchain.info/tx/1ea357c4fe7aa77d90dfeef6606e1bb978f57e7bb103ec36ffcf07715089efe8 should be a transaction hash', u'code': -1}

**Comment by ecdsa** [comment]
please post the relevant address, and a screenshot of Electrum that displays the address.

**Comment by quazzyquazzy** [comment]
![screen shot 2017-11-01 at 6 32 15 am](https://user-images.githubusercontent.com/33269125/32272965-72f5ab5c-bece-11e7-9b8a-c9a072db7523.png)

**Comment by quazzyquazzy** [comment]
This one has last shown transaction history

![screen shot 2017-11-01 at 6 33 51 am](https://user-images.githubusercontent.com/33269125/32273025-b2c81102-bece-11e7-9c90-8f7c0af34ba6.png)

**Comment by ecdsa** [comment]
which server are you connected to? (open network dialog)

**Comment by ecdsa** [comment]
that IP address is a Bitcoin Cash server, that's why it does not see your coins.
the screenshot with the green icon suggests you are connected to it.
does your client stay permanently connected to that server, or does it disconnect itself and retries all the time?

in any case, the problem should go away it you use the "auto-connect" option in the network dialog

**Comment by quazzyquazzy** [comment]
ok they have shown up now, thank you for your help. my wallet had actually auto-connected to that server but i changed it manually and it worked.
