### ISSUE TITLE
google autheticator

### ISSUE THREAD

**Issue by matvey111** [spesmilo/electrum#3166]
how to reconnect an autheticator to a new phone? I have an old phone with an attached autheticator, but I would like to transfer it to a new one)

**Comment by ecdsa** [comment]
you need to restore the wallet from seed, and then you can request a new code

**Comment by vimugi** [comment]
I installed google authenticator through the QR  scan but did not save the key ,lost my phone after a week ,am now unable to log in to my facebook due to the code.Kindly help
