### ISSUE TITLE
Cannot send to p2sh-p2wpkh address from standard wallet on testnet

### ISSUE THREAD

**Issue by Raulo** [spesmilo/electrum#3169]
Using latest HEAD (e8b634ac4a2982fb09dd4a3ad78e1bced8d637ae).

When trying to send to a P2SH-P2WPKH address from standard wallet created in Electrum 2.9.3, error appears:

File "/usr/local/bin/electrum/lib/bitcoin.py", line 920, in deserialize_xkey
    raise BaseException('Invalid xpub format', hex(header))
BaseException: ('Invalid xpub format', '0x4358394')

The address (e.g, 2Mw3VRgFG1RGNyp3eYLJY9nuXhiZWEAZy5C) was created in Bitcoin core testnet via addwitnessaddress. 

The problem does not appear in a wallet generated in Electrum 3.0 and also form a 
P2SH-P2WPKH wallet generated in electrum from BIP39 seed with  the BIP49 purpose  (is there any other way to create  P2SH-P2WPKH wallet in electrum?)

**Comment by ecdsa** [comment]
that error is not related to the address you are sending to.
you created your wallet with an earlier version, that used different magic numbers for xpubs.
restore your wallet from seed, or create a new one
