### ISSUE TITLE
outdated URL on website: windows/pyqt5

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3172]
![win_pyqt5](https://user-images.githubusercontent.com/29142493/32305108-bcada2cc-bf73-11e7-8454-f61b24b91e71.png)
The link for PyQt5 for Windows points to https://riverbankcomputing.com/software/pyqt/download
It should point to https://www.riverbankcomputing.com/software/pyqt/download5

**Comment by ecdsa** [comment]
fixed, thanks
