### ISSUE TITLE
Install Wizard remains open after 2 to 3.0 conversion

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#3173]
For every wallet I've converted so far in OSX 10.12.6

Shouldn't it clear itself away?

**Comment by TheButterZone** [comment]
And why is it called Install Wizard?

**Comment by ecdsa** [comment]
can you clarify what you mean by "imported" ?

**Comment by TheButterZone** [comment]
I didn't say "imported"

**Comment by ecdsa** [comment]
sorry, "converted"

**Comment by TheButterZone** [comment]
The non-backwards-compatible wallet format conversion that we're prompted for when we open our Electrum 2.x wallets with Electrum 3.0...

**Comment by rex4539** [comment]
I see the same. On first launch of 3.0 (upgrading from 2.9) the "install wizard" window remained open after successful completion of the conversion.

**Comment by ecdsa** [comment]
closing, deprecated
