### ISSUE TITLE
3.0's Show Fiat balance for addresses

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#3174]
is shown without regard to the checkbox setting for it. Fiat balances were already shown even though it was initially unchecked, then I checked it, and unchecked it again, and nothing happened.

**Comment by SomberNight** [comment]
![fiat_balance_for_addresses](https://user-images.githubusercontent.com/29142493/32307947-7bf52902-bf83-11e7-9c72-e3f689191610.png)

Do you mean that checkbox (in image)? Because it works for me.

**Comment by TheButterZone** [comment]
Yes. OSX 10.12.6

**Comment by ecdsa** [comment]
cannot reproduce that.

**Comment by TheButterZone** [comment]
Oh, it only applies to the Addresses tab, not the USD Amount & USD Balance columns in History. The capitalization of 'Fiat' & non-capitalization of 'addresses' threw me off.
