### ISSUE TITLE
3.0 does not start on Windows 7: Error loading Python DLL

### ISSUE THREAD

**Issue by pdario** [spesmilo/electrum#3177]
Hello, I just installed Electrum 3.0 but it does not even start!

It shows a Fatal Error that says:
Error loading Python DLL
'C:\...... path ....\Temp\_MEI476547\python35.dll'

LoadLibrary: An attempt to set the process default activation context failed because the process default activation context was already set

Please help!

**Comment by ecdsa** [comment]
duplicate
