### ISSUE TITLE
3.0 low resolution on retina Mac

### ISSUE THREAD

**Issue by Dedados** [spesmilo/electrum#3178]
After updating Electrum from 2.9.x to 3.0, it runs with a lower resolution, meaning everything looks blurry and I can see individual pixels. BTW I had recently installed electron cash to retrieve BCC (using an empty BTC wallet), but uninstalled it before updating to 3.0.

Running on sierra 10.13.1 retina macbook pro.

**Comment by ecdsa** [comment]
duplicate

**Comment by Dedados** [comment]
Link plz?

**Comment by ysangkok** [comment]
maybe https://github.com/spesmilo/electrum/issues/1096 ?

**Comment by Dedados** [comment]
Nope, all UI is in low res. 
<img width="948" alt="screen shot 2017-11-02 at 3 59 36 pm" src="https://user-images.githubusercontent.com/25583757/32329878-fd2429de-bfe6-11e7-8291-240a7305d775.png">

**Comment by Dedados** [comment]
@ecdsa

**Comment by aericson** [comment]
It looks really blurried here (Macbook pro 2016):

Comparing to electrum-ltc, Click to see full size:
<img width="970" alt="screen shot 2017-11-10 at 00 46 40" src="https://user-images.githubusercontent.com/692542/32642159-0397cf8a-c5b1-11e7-99d1-943c55b45df2.png">

**Comment by Dedados** [comment]
Same

**Comment by Dedados** [comment]
@ecdsa 
It doesn't have anything to do with low res icons as issue #1096

I don't see how this is a duplicate.

**Comment by Dedados** [comment]
[Fix](https://apple.stackexchange.com/questions/69038/open-in-low-resolution-checkbox-on-retina-macbook-pro-checked-and-disabled)

**Comment by aericson** [comment]
@Dedados there is some similar info here: http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

I tried building it with the changes but it did not work. I have no experience with Qt, so I might have done something wrong.

**Comment by Dedados** [comment]
I followed the instructions the link had and it worked. For some reason, by default 3.0.0 (and 3.0.1) runs on 'low-res mode'. I had to force it to run on HD mode by the method described in the link.

Here is what I mean:
![screen shot 2017-11-10 at 9 00 12 pm](https://user-images.githubusercontent.com/25583757/32674122-9e08703e-c65a-11e7-894c-789019a1d58c.jpg)

**Comment by aericson** [comment]
Yea, that worked, without the needing to rebuild, just by editing the `.app` file. Thanks.
