### ISSUE TITLE
Enable (optional) encryption for watch-only wallet files

### ISSUE THREAD

**Issue by zzAD26KAH59cYpL** [spesmilo/electrum#3183]
The user should be prompted to set a password to encrypt watch-only wallet files.

The user should also be prompted to set a password to encrypt watch-only wallet files created when an hardware wallet is used with Electrum.

Without encryption for watch-only wallet files the user's privacy is potentially exposed because is possible for an adversary to access the master public keys, this is possibly a security issue too as reported here:

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
> One weakness that may not be immediately obvious, is that knowledge of a parent extended public key plus any non-hardened private key descending from it is equivalent to knowing the parent extended private key (and thus every private and public key descending from it).

**Comment by zzAD26KAH59cYpL** [comment]
Another possible security implication is the possibility for an adversary to spoof addresses editing the watch-only (not encrypted) wallet files.
Maybe this should be addressed for not encrypted wallet files too, possibly checking the single addresses against the public master key when opening a wallet file.

**Comment by AbdussamadA** [comment]
If an adversary has file system access then at that point in time your computer is compromised and it doesn't matter what you do. 

The reason whole wallet file encryption was introduced is to prevent people from receiving money to a wallet they can't spend from. With a watch-only wallet even if you know the password there is no guarantee that you can spend from this wallet since the seed is in another wallet file. 

So overall I don't agree that this is a feature worth adding.

**Comment by FomgbdsLQeC2LPq** [comment]
@AbdussamadA 
> The reason whole wallet file encryption was introduced is to prevent people from receiving money to a wallet they can't spend from. 
Do you care to explain how exactly wallet files encryption can protect users from receiving funds to an address they can't spend from? 

Encryption is by definition a tool to reduce the risks of private information leaks, the master public key is an information that you should keep private as much as possible, and an option to encrypt this information is a simple and useful tool that can help user's to protect their own privacy.
Keep in mind that a watch-only wallet is intended to be used in less secure and maybe shared on-line environments (while using cold storage or hardware wallets to protect your private keys). Being able to (optionally) encrypt a file containing privacy sensitive data can help to mitigate at least a part of the privacy and security problems in this context.

**Comment by AbdussamadA** [comment]
>Do you care to explain how exactly wallet files encryption can protect users from receiving funds to an address they can't spend from?

To get an address to receive bitcoin to you need to open your electrum wallet file. If you have full wallet file encryption you will have to enter a password to decrypt your wallet file first. Only then can you get a receive address. The fact that you entered the correct password also means you can spend from that wallet. Of course it doesn't prevent you from handing out addresses that you have recorded outside the wallet file.

Previously electrum only encrypted the secrets in the wallet i.e. the seed and private keys. This allowed people to view the wallet and get receiving addresses without entering any password. Some people would receive bitcoin to their wallet but when they went to spend it they would be asked the password and they would discover that they didn't know the password. So their funds were stuck in a wallet they couldn't spend from. In most cases they had backed up the seed and could restore their wallet from that. But in cases where they didn't back up the seed their funds were stuck in that wallet forever.

**Comment by FomgbdsLQeC2LPq** [comment]
@AbdussamadA 
Thanks for your reply, I understand that this can be somehow a way to protect unsavvy users, in my honest opinion implementing such a feature only to protect careless users can be considered overkill, I think encryption is much more useful to protect users' privacy. 
The official Electrum FAQ seems to point in that direction too:
http://docs.electrum.org/en/latest/faq.html#how-is-the-wallet-encrypted
> Wallet file encryption is activated by default since version 2.8. It is intended to protect your privacy, but also to prevent you from requesting bitcoins on a wallet that you do not control.

 "Wallet file encryption is [...] intended to protect your privacy": if it's so, then adding encryption for watch-only wallet files is advisable and necessary even.

**Comment by fr3aker** [comment]
> If an adversary has file system access then at that point in time your computer is compromised and it doesn't matter what you do.

This is a little misguided. The assumption that whoever is able to access your watch-only wallet file must have fully compromised your computer is pretty far-fetched. Especially a watch-only wallet might be used on a mobile device (eg a smartphone) or backed up to a thumb drive to allow to monitor incoming (or outgoing) transactions on the go. Protecting your privacy in case of loss of your backup device (or a compromised backup cloud storage) is a legitimate goal.

> The reason whole wallet file encryption was introduced is to prevent people from receiving money to a wallet they can't spend from.

I would be surprised to learn this was the sole reason to add wallet encryption. For example, besides privacy, encryption also prevents an attacker from tampering with the wallet. An attack scenario might be adding public keys to the victim's watch-only wallet (assuming an attacker has access) to trick them into believing they received funds that in reality were sent to an attacker-controlled address.

**Comment by SomberNight** [comment]
This should now be resolved, due to merging https://github.com/spesmilo/electrum/pull/3346
