### ISSUE TITLE
Funds sent from Electrum without my knowledge

### ISSUE THREAD

**Issue by falcone123** [spesmilo/electrum#3187]
Hi, Please help as I am new to Bitcoin and Electrum Wallet. On Sunday 29 October at 08:58 I received funds that I had transferred from another wallet in my Electrum Wallet. I could see the Amount and Balance which was correct. I assumed the funds are now safely in the wallet. However on Sunday 29 October at about 23:45 the funds were Sent from my wallet and my balance is now zero. I did not send the funds myself. Can someone please explain what happened and where my funds were sent to? 

The transaction ID is 029f70aaeb6d99cd4b9cd3d53f28667e77b2cc109b84a70bcea037b428cce9c2

Thank you and Best rgds

**Comment by falcone123** [comment]
Please see attachment.
![electrumwallet](https://user-images.githubusercontent.com/33329570/32344798-b823556a-c010-11e7-8844-275af562d623.png)

**Comment by AbdussamadA** [comment]
looks like you were hacked. sorry for your loss.

**Comment by falcone123** [comment]
Thank you for your email. Yes looks that way. Lesson well learnt! Luckily
was a small amount...

Best rgds

**Comment by falcone123** [comment]
I contacted Cryptopay as well just to see if the funds was perhaps sent back to them. They responded by saying funds was not sent to them. So I guess account was hacked. Lesson well learnt and I hope others may learn from this as well.

**Comment by AbdussamadA** [comment]
Your computer has been compromised so you will have to do a nuke and pave. delete everything, format our hard drive and reinstall your operating system. Otherwise you could find funds stolen from future bitcoin wallets that you create.

**Comment by falcone123** [comment]
Hi AbdussamadA

Thank you. Yes i will definitely be doing that
