### ISSUE TITLE
MacOS text washed out

### ISSUE THREAD

**Issue by DocSnyd3r2** [spesmilo/electrum#3188]
![image](https://user-images.githubusercontent.com/33177964/32346859-29b17db2-c00f-11e7-99c8-7836e2acf6bb.png)
Text is very poor. Using MacOS high sierra with Electrum 3.0.0

**Comment by henryfletch** [comment]
![electrum](https://user-images.githubusercontent.com/6097493/32347078-6fff0b70-c007-11e7-98ae-96c26c755bb5.jpeg)

Same problem. It looks like the app doesn't support HiDPI (retina) for some reason, even though 2.x did.

Also, the version number seems to now be missing from this binary?

**Comment by jonathancross** [comment]
Hi @henryfletch I have opened #3190 - for the version number issue.  Please remove that info from the comment here so devs can focus on one issue at a time.  Thanks.

**Comment by barryvdh** [comment]
Should be fixed in 3.0.2 already.
