### ISSUE TITLE
Ledger Nano S can't connect to segwit

### ISSUE THREAD

**Issue by yorickdowne** [spesmilo/electrum#3189]
When trying to create a new Electrum wallet and connecting to a Nano S FW 1.3.1 with a m/49'/0'/0' derivation path to use segwit, UI shows an error "Cannot read xpub from device". Under the hood, an exception is thrown "Firmware version too old" because self.supports_segwit() returns false.

``
elif bip32_path.startswith("m/49'/"):
                 if not self.supports_segwit():
                     raise Exception("Firmware version too old for Segwit support. Please update at 
https://www.ledgerwallet.com")
``

**Comment by ecdsa** [comment]
ok, we should show the correct error message
