### ISSUE TITLE
v3 OSX Info.plist missing version number (0.0.0)

### ISSUE THREAD

**Issue by jonathancross** [spesmilo/electrum#3190]
`Info.plist` is missing version number:
 
```xml
<key>CFBundleShortVersionString</key>
<string>0.0.0</string>
```

Looks like this `0.0.0` is a default version added by PyInstaller: https://github.com/pyinstaller/pyinstaller/blob/master/PyInstaller/building/osx.py#L45

Version was correctly set in previous versions.

Hopefully this is as simple as adding the `version` here:
https://github.com/spesmilo/electrum/blob/master/contrib/osx.spec#L65

Screenshot:
![image](https://user-images.githubusercontent.com/5115470/32356674-fc5b06c6-c036-11e7-8c9d-93083bdc734e.png)

**Comment by ecdsa** [comment]
I have restored Info.plist in the 3.0.1 builds.
can you check if that works?

**Comment by jonathancross** [comment]
No, unfortunatly the same issue is still here in 3.0.1 release.  See attached file: [Info.plist.txt](https://github.com/spesmilo/electrum/files/1447855/Info.plist.txt) (added `.txt` extension to make github happy)

[osx.spec](https://github.com/spesmilo/electrum/blob/master/contrib/osx.spec#L65) doesn't seem to have changed, did you try that?

**Comment by Dedados** [comment]
[Fix](https://apple.stackexchange.com/questions/69038/open-in-low-resolution-checkbox-on-retina-macbook-pro-checked-and-disabled)

**Comment by jonathancross** [comment]
@Dedados This has nothing to do with #3178 or the [Fix](https://apple.stackexchange.com/questions/69038/open-in-low-resolution-checkbox-on-retina-macbook-pro-checked-and-disabled) you posted.

**Comment by Dedados** [comment]
Sorry, my mistake!

**Comment by ecdsa** [comment]
@jonathancross it is possible to set NSHighResolutionCapable in the .spec file, according to the documentation: https://pythonhosted.org/PyInstaller/spec-files.html
so, fixing info.plist should fix both issues
I will try that with the next builds

**Comment by jonathancross** [comment]
@ecdsa Great!  So, I guess there is a connection between the two issues afterall  :-)

**Comment by ecdsa** [comment]
please try https://download.electrum.org/test/electrum-3.0.1-40-g8fcf165.dmg 
Let me know if the low resolution issue is fixed too

**Comment by JustinTArthur** [comment]
That DMG fixes the low resolution issue (#3178) for me.

**Comment by ecdsa** [comment]
thanks. closing this

**Comment by jonathancross** [comment]
Yep, version number is fixed too  :-)
Thanks!
![image](https://user-images.githubusercontent.com/5115470/32756235-69eeef22-c8d9-11e7-8db0-3d4cde601e50.png)
