### ISSUE TITLE
gpg --verify gives warning message  

### ISSUE THREAD

**Issue by dblokhin** [spesmilo/electrum#3192]
Hi all!

I've downloaded last win release right now, but my Norton AntiVirus alert:

> Heur.AdvML.B is a heuristic detection designed to generically detect malicious files using advanced machine learning technology. A file detected by this detection name is deemed by Symantec to pose a risk to users and is therefore blocked from accessing the computer.

`Type:
Trojan, Virus
Infection Length:
Varies
Systems Affected:
Windows`

I've checked the sig:

```bash
$ gpg --verify electrum-3.0.0-portable.exe.asc electrum-3.0.0-portable.exe
gpg: Signature made Thu 02 Nov 2017 09:36:23 AM VLAT using RSA key ID 7F9470E6
gpg: Good signature from "Thomas Voegtlin (https://electrum.org) <thomasv@electrum.org>"
gpg:                 aka "ThomasV <thomasv1@gmx.de>"
gpg:                 aka "Thomas Voegtlin <thomasv1@gmx.de>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6694 D8DE 7BE8 EE56 31BE  D950 2BD5 824B 7F94 70E6
```

Is it safe to use that?

**Comment by SomberNight** [comment]
Not sure about the antivirus, but that fingerprint is for the **correct key**, and it clearly says "Good signature".
The GPG warning is about you not having a connection to the key through the web of trust, which if you not use GPG much is totally expected.

**Comment by dblokhin** [comment]
Thanks you.
