### ISSUE TITLE
v3 on ubuntu not reading Ledger nano s

### ISSUE THREAD

**Issue by leviadam** [spesmilo/electrum#3195]
Hi,
Upgraded to v3 on ubuntu 17.04, now unable to connect to my ledger. Getting:
```
No hardware wallet support found or your system.
Please install the relevant libraries (...)
```
The original ledger app works fine, as well as v2.9.3

**Comment by ecdsa** [comment]
that's because you installed their library for python2
you need to reinstall it for python3

**Comment by leviadam** [comment]
Thanks. Do you have a link maybe?
Couldn't find it.

**Comment by ecdsa** [comment]
it is the same library as for python2
you need to reinstall it with python3

**Comment by leviadam** [comment]
I don't remember I installed a library.
I installed the chrome apps, and the bash script from [here.](https://ledger.groovehq.com/knowledge_base/topics/ledger-wallet-is-not-recognized-on-linux)

**Comment by ecdsa** [comment]
https://github.com/LedgerHQ/btchip-python

**Comment by leviadam** [comment]
Thanks.
