### ISSUE TITLE
Asking for Google Authenticator Code on SENDING

### ISSUE THREAD

**Issue by cancerea** [spesmilo/electrum#3196]
I CANNOT SEND MY BITCOINCASH BECAUSE IT ASK FOR GOOGLE AUTHENTICATOR CODE. .  

WHERE/HOW CAN I GET THIS CODE TO BE ABLE TO SEND THE BITCOINCASH . . ?

**Comment by ecdsa** [comment]
please ask this the bitcoin cash developers
