### ISSUE TITLE
GUI incorrecly signs previously saved segwit transaction

### ISSUE THREAD

**Issue by Raulo** [spesmilo/electrum#3197]
3.0.0 version. 

Deserialized transaction created and signed from GUI (or created and signed from command line). This transaction works fine. 

{
    "inputs": [
        {
            "address": "2N646eRzEDQmA3kFEE71ATfyiVDR2jJouR8",
            "num_sig": 1,
            "prevout_hash": "6a3d29615ebdf5affe6e3607c842c3aee4906b93f4057d4be9b416a2d38540fa",
            "prevout_n": 1,
            "pubkeys": [
                "021a93e1082a1eab5a95c2ee88623f8c3714378439a0d27fc599deab6600eecc43"
            ],
            "scriptSig": "160014cfbe8bebc668980be48c820d35634f55a86c6d02",
            "sequence": 4294967294,
            "signatures": [
                "3044022072793521c7cf0e1d8eb3401a3dfdbabfff395284a0d4a3fc95cd0fe173f9cd5e022054afb0fa81f0ca040a017f7789874c0ad2fb37430f8747921f5c972b7ef1ceed01"
            ],
            "type": "p2wpkh-p2sh",
            "x_pubkeys": [
                "021a93e1082a1eab5a95c2ee88623f8c3714378439a0d27fc599deab6600eecc43"
            ]
        }
    ],
    "lockTime": 1223113,
    "outputs": [
        {
            "address": "2MzGcncD84os4e8yrexdvDK685k2LVg6A9a",
            "prevout_n": 0,
            "scriptPubKey": "a9144d0c53ecfa260cb03f50150d171e08fa416d0b4287",
            "type": 0,
            "value": 40000
        },
        {
            "address": "2N1K4jqn55X8ULQYhL3A9T8JVReFSbR2zg5",
            "prevout_n": 1,
            "scriptPubKey": "a914587af30e6bf018558fa56644a03c7e0ee0cf35ae87",
            "type": 0,
            "value": 295564200
        }
    ],
    "version": 1
}

The same transaction saved before signing. Loaded in GUI (Tools/Load Transaction/From file) and signed again. Signature is different:

 "30440220708e5d2bc4064da545f440ae1a560e89514801f5605b9813080977744fa105be0220013124705deead4215203a19571c1ec3e145af03fc991551cd1c9f52f0aae9aa01"

Cannot be broadcast, fails with error:

error: {'message': 'the transaction was rejected by network rules.\n\n64: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)\n[01000000000101fa4085d3a216b4e94b7d05f4936b90e4aec342c807366efeaff5bd5e61293d6a0100000017160014cfbe8bebc668980be48c820d35634f55a86c6d02feffffff02409c00000000000017a9144d0c53ecfa260cb03f50150d171e08fa416d0b4287a8f39d110000000017a914587af30e6bf018558fa56644a03c7e0ee0cf35ae87024730440220708e5d2bc4064da545f440ae1a560e89514801f5605b9813080977744fa105be0220013124705deead4215203a19571c1ec3e145af03fc991551cd1c9f52f0aae9aa0121021a93e1082a1eab5a95c2ee88623f8c3714378439a0d27fc599deab6600eecc43c9a91200]', 'code': -1}

The same problem is with bech32 p2wpkh wallet. 

There is no such a problem in standard non-segwit wallet.

**Comment by neocogent** [comment]
Have tested and was about to report same error. Same version. Using BIP39 Segwit (m/49'/1'/0') on testnet so not just bech32 native segwit. Also, first time I tried was using a QR code. Show on tx preview, snap with mobile phone. Try loading from QR code to sign and worked but broadcast fails, same error. 

I'm guessing maybe input ordering again as I think occurred before with ledger wallets.

**Comment by ecdsa** [comment]
thanks, fixed
