### ISSUE TITLE
Cant send bitcoin from electrum 2.9.3

### ISSUE THREAD

**Issue by rob1972** [spesmilo/electrum#3199]
Can anyone help I am trying to send out from my wallet but I get the following error

error: the transaction was rejected by network rules.

64: scriptpubkey
[010000....etc]

btw, I have dynamic fees box checked

**Comment by ecdsa** [comment]
please give more details. what kind of wallet are you using, how was it created

**Comment by rob1972** [comment]
its an electrum 2.9.3 default_wallet [standard]

I bought bitcoin on coinify and installed the electrum program for it to be deposited into

**Comment by ecdsa** [comment]
which server are you connected to?
