### ISSUE TITLE
Electrum 3.0 Fails to recognize Trezor wallet

### ISSUE THREAD

**Issue by Extremed** [spesmilo/electrum#3202]
**Upgraded Electrum from 2.93 to 3.0 on Ubuntu Linux**
Install dependencies:
sudo apt-get install python3-pyqt5 python3-pip
Install Electrum:
sudo pip3 install https://download.electrum.org/3.0/Electrum-3.0.tar.gz

**Electrum Hardware Keystore gives the message:**
> No hardware wallet support found on your system.
> Please Install the relevant libraries (eg python-trezor for Trezor).

**From the Command Line**
$ pip list (shows trezor (0.6.10))

$ sudo apt-get install python-trezor (shows the message below)
python-trezor is already the newest version (0.6.10-1).

???? what next !

**Comment by ecdsa** [comment]
make sure you installed trezor for python3.
for example, install it with pip3

**Comment by charlespax** [comment]
@Extremed Have you solved this? I'm experiencing the same problem (issue #3214 ).

**Comment by Extremed** [comment]
**I got Electrum 3.0 working with the Trezor by the following:**

**Python-trezor from GitHub**
https://github.com/trezor/python-trezor 
**(You have to re-install Trezor for python3 with Electrim 3.0)**
It didn't work correct until I executed the following commands first.
sudo apt-get install python-dev cython libusb-1.0-0-dev libudev-dev git
sudo pip3 install setuptools
sudo pip3 install trezor
