### ISSUE TITLE
Error "Private keys sweep"

### ISSUE THREAD

**Issue by wakiyamap** [spesmilo/electrum#3208]
On git master https://github.com/spesmilo/electrum/commit/0a10d6512bc8f73709aac2b7b0a7fba7feaf30ac .

If sweep the secret key more than once, the following error will occur.
It crashes in Windows.

![image](https://user-images.githubusercontent.com/7189933/32386666-52a307e4-c105-11e7-8485-e5452d22fee0.png)

>   File "/home/wakiyamap/electrum/gui/qt/main_window.py", line 2193, in <lambda>
    self.computing_privkeys_signal.connect(lambda: e.setText("Please wait... %d/%d"%(len(private_keys),len(addresses))))
RuntimeError: wrapped C/C++ object of type QTextEdit has been deleted
Traceback (most recent call last):
  File "/home/wakiyamap/electrum/gui/qt/main_window.py", line 2190, in show_privkeys
    e.setText(s)
RuntimeError: wrapped C/C++ object of type QTextEdit has been deleted

**Comment by SomberNight** [comment]
Not sure I understand. When does this occur?

**Comment by ecdsa** [comment]
if you export the private keys several times

**Comment by wakiyamap** [comment]
Sorry. English is too difficult for me....
1. Click on this menu to display "Private keys".
2. Erase the "Private keys" dialog and click this menu again to display the "Private keys" dialog.
3. An error occurs.

![image](https://user-images.githubusercontent.com/7189933/32390502-03035a7e-c112-11e7-82e4-da7a82e20c8a.png)

**Comment by wakiyamap** [comment]
Thanks!!
