### ISSUE TITLE
3.0 encodes a weird QR for raw TX hex

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#3210]
Load transaction>From the blockchain
TXID: 43f44caed3017b08211e7570b15d9e1efc16f3f1edc08ce82d875a0b817ab6e3
QR button shows
![screen shot 2017-11-03 at 17 32 12](https://user-images.githubusercontent.com/2625857/32400432-3ffad3c6-c0bd-11e7-9dd6-d434785edd39.jpg) - https://play.google.com/store/apps/details?id=de.gavitec.android decoded some weird format with symbols mixed in, probably exactly the same as what https://zxing.org/w/decode.jspx decoded:
`V8QMO*RT00F*FOV$AJC+ZKA9-.+E*-92P$C1EZU3XAZM32:S2VAFGCU2LS3+F1B8R0G:DB4C//QX5N/M0EDRD.K$BHQL*JC89Q$*:5IEH40IM9LZU+DCPY020XYU9BU2:W.Z7W201H5/UWYH*5.Z-XOSF8D$PBEAOMPAFGBT+*S+ZX+W9KID7:UA/XRMNS0/IH:27P32O03V/CLHQ.9B74FVY7D*67AT6AJHPPJH1VAHFQFXL6D3P4TTZO8SU1I3/WRXW-ZNDG4V3L*K5QZJQL9M+J+PH$XS+TKVBBPLKZC/CIW8M51Y*B2CS*63Y:3A0./$DVJ:I2-VF-BD45IX$XKTH:QT:ZNIK+ZC8I+41KPN99UJQ00X8W1B/59IQF9G38FH-52281*YVP3.7W:828:CH5I88E17+6/KYVTSM87$OBEN*DB64C8LV/V7VU:O.H6$$MNUJIRR$C./-/W6DPEHT*SW$$NP1HJXFF0FJM-+E1G-.427$F/ZH6:L*$*S*$ORQJOLNYS88C0+W-GMJVFX6UY686D..8BFBMSPRY-1NGA3E5SFB:T65RZNB+-12D2NLBQ9N7*CU55730+IQ9ZUOMC1W-BI:ZZ0K8-P6H:ZMJ0A*+X-*FF-*8D:*03WE-CW$BZG.MYBY-:31$5H3LGD6STAKGE.X9JRX:VHKHXCLDGFRS/1WQR0PW+3BG*TBZU:W36JJA-74*4M+39ZOSKZ-F.T*ZF84+:485QJAI5ZPBW-6MVSSLF4P7*7S2F1Z0CTYOQCPY2K.M5Y3VQIC.WK2GKTYF8C-T27/A6/U2Y0N:5D9BP$:871VNFO:0$9XCTC8.*3$B3$HYRIQUUF5FLHDLR96H.ZCVNICFS:SOP.K0G7G4NP:XU9S:$VB1W:D2:77A30JSHFGJ+FFSY67SWI07VC1A.B$PN7LWO*IXX:CUQZ99KK7WVG7351CFRX+Y/J*596Z$:*UI:JIJQ4JGXT55+OHT3BBO*F547IOPLDP4AM-9OQBI4DRFBY-D+CI-0T86EN*5AOZA9:P4HIKYX58XRMRCZ362V*QBMW55L5LQRC0*:URBQ68KB.BSK6.LP*MBQOK9REUA9KLB1W0NRL21TBQCTTT1JR1TE.V*.FG5QQZ/3URX5E51YSSLML3AM9FF/JABWC.Q$PWGELT923UDV*4$ZQMC/ANBL1YI01E-AQSQ$2B2SDPMQONJTXPBCN/9Z.A59.5R+*DHZ$A-+80BZ15+5VZLXMLTVD5N$TL8FP/G6T68.7$OKQGJW:V*ASGDUWPHA588W/-UBZAA7.-R2UNJ*-K8V429K64RXMCJXRNREL//FEH:SY8:4Z41H+INY972GR37A+MD.IUKDIB5*XICUPNJV$QI52YC7Z2IIMK8PHT5L$QCC:FXUP:23QU+3EDTV2+XH+R8UJBSML/2QEIGGAG5M5F.BO/BT8G.I1UMOD98MKV$$QPW7TBYJ/PP76$YU8A*6$S$IW2ZL8B:-FB3C/8XGBJR2*.*MXVHEFF8Z0Y2LJH0B5APYG/DWY*79:C/KULO0*DU/V**E4Z*GE*024XK-ZMIYJ5D2J4KH22E.NNHZLVC0G::B542K54J5YMA:FYFZA1GIELZVM6F/OBHDU94X.+NIVZYCDJQO19PSH.L$JM*UH8-C*HB/66KKKE/OT$PZGWRR+H55Z+OVICXS.+YCGKN-FR659AMJQDROF2YTPJA5RI$.RU8$YW0OQY*PN4R$--AMP*Y59$Z8KBRH$W-926RDCBYD$.23B1V.6MQ9Q4C56+JGE1T7I5LW6U.B2NN7P-:I/W$Y0ZZDYMCE.NJYQP:K.EDT37DRGM7SJWU845P+W1U03R27W/$Z:-.PHDOFCC::EP846KC7X$/IW0WU/./HTIWF16CA/0RX+9-UPOUXNUALX/R/H+--8CV8ZCNWPD8SV+/TPRMSQP:Q-9NGOVVKJY.J435I`

Copy button puts `02000000071619b5ecef54f1f0251a7f23bbfb985b1c637101bec0b09dc902295e4a80ec2e5f0000008b4830450221009554dc1601a40541593a692fde0e5ec169c6a41b409e6365bdab5ed313c63ee102201a1c6231ff87b274e67b2118019a4a3e73f333a7aa57ca063681ca32d9af3d260141043233f8fbb32f564eb1b698bf3d5773d5f2c7282a70c49dd273ba705c73dee43f3c289f46e4cffb8e6438c99c4900aaf79ffff5207231bd66a6ebcef082fca1fbfeffffff37cf3cfcf53010b4ac672b51e303b39e0fd8b41f54a43dd30743a8fe2947c768060000008a47304402201e227b62b2fe698bc387292f2039b5a9d0105c39431d613b0585461c9748518802200fde9628a35b00d1ccb7fd0136017ece883ed7945d47a97b187fcd38102f51b6014104ddf801fd5c8cd63073901720eae81d1d53e04e24d9b30960ba2948b0a64b8d0d539cfb1ab6266c1a22fef011683b70e2bfa47ac35d7e8346ff55aba1bed2643bfeffffff383ffe0e452cc327039e0b3112b3122fd975a296dbb57e9609c8e34f4ae26b00000000008a4730440220560e079d7d9ccbbd65e99b11a115787c2f0ebe004fbdbe13407d2d0d9c19cfcf02200d4c026c7f11a42b207e76888172eef888741ab0c455e71c28b40d264de78a91014104a80bb95d1762e0cf064ef74c9a1086d568ea2f250a98226bdd8749bcd00381e3a7a65e0417676f14cc8b558420c77cc1b245e4650d81e560ae8ef4712080c35efeffffff56a00f15ea14fb6a7d0b2f7969963d8ee54df5478bce6d06cb7c94ee0d08e72c530000008b483045022100aa2b24390dcd56c48067eed4e151368fb1690856f0f6001ce7b3504f799852d8022019b5338301cc502908140c0a8cbfd1106355ccb06db0a8d58bedee0dc1e4d5500141043233f8fbb32f564eb1b698bf3d5773d5f2c7282a70c49dd273ba705c73dee43f3c289f46e4cffb8e6438c99c4900aaf79ffff5207231bd66a6ebcef082fca1fbfeffffff8faf74579458d2dcd7337d2a8c5fd66a5684343fb9abb81bce4bfa8e6c9b4bb5000000008b483045022100964727e35660f16f52b0fb0e59704276bdf0538ed3fb9db407fc216cf56ea14402201e0b2b61c274699c88a8cc8c7dc28d323d6de5ce727695727ecba0b904ebe8440141042356a6a9065c915294e2aaa61c08367fb5ee50c9347ad9ec6d17ec6483d430fc1e9ad09d8ac61fea17257430f1fb0e915ebdd7601373c2a74b6f6526b90e700efeffffff9bd561b340b5eda2de6cef2f718f40b00a46881caf0a724786227af983e84e1a020000008a473044022029994b0d536b1ad7ff3e91c0539d63184a77fef0cfd18b43df6bd3d75ca7722b022062bfce132271adc08b163d1deab08589daf0732806661746e23e992c6fd80aa2014104011aa81dbe50bdc2abfebb24c0e39bb52607423206f050bafffdc44cd3721719b8c58f6ffd2b22223437858a6553948f23b5e9c91ea8e732c68fd6ae15e8b915feffffffdbba46e680ab1ddc926e689ba082fba7133f1ba124014bea4cbc94ba16dd079d010000008b483045022100afd895e1a7adc68728bddffefec14999b82e14bf5762574dffa5e91c65dfffd302202156f1d268b74055ef532657153031c64878496ded3ffd4f600c2c4a3a602ecf014104b93e5354e4000e642213c7a4ef50875c72ff30812a7b90f69bf6afe0ee822c41ff392e657e24f2dfcd8d2e218208f3630155220d2164ecf41c0b709dc771dd86feffffff02e0490f00000000001976a914e1829d33e043a20636104fcec4bf53f2fc2f0c1d88ac21c8a611000000001976a9142975fa511e3676ef78afb7b04297e4cd098ac2cd88ac88850700` 

into the clipboard, which, when decoded on https://blockchain.info/decode-tx shows  "hash":"43f44caed3017b08211e7570b15d9e1efc16f3f1edc08ce82d875a0b817ab6e3",

**Comment by SomberNight** [comment]
This is also how 2.9.3 behaved. There is no bug here.
ZXing scans it correctly; your first string (based on a few chars I checked) looks okay, it's just a particular encoding of the raw tx. The second string is a hex encoding of the tx.
Try scanning the QR code with the Electrum Android app, and it will load the transaction.

**Comment by TheButterZone** [comment]
Both the QR above & the that hex encoded to QR are too complex for my 8MP camera, apparently.
