### ISSUE TITLE
CANNOT SPEND FROM ELECTRON CASH

### ISSUE THREAD

**Issue by cancerea** [spesmilo/electrum#3212]
I am getting this error and cannot spend my money.

THE ERROR  

error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)) [0100..... .... . .

PLEASE HELP . . . 
![ec](https://user-images.githubusercontent.com/4168830/32403713-fb25e4ba-c162-11e7-82aa-d2d26785ef91.jpg)

**Comment by AbdussamadA** [comment]
This forum is not for electron cash. Go complain in their git repo:

https://github.com/fyookball/electrum

**Comment by quintela78** [comment]
Good afternoon,

Did you solve the issue?

**Comment by quintela78** [comment]
If you have not solved, call me leonardquintela@gmail.com. Maybe I can help. I rarely go here.
