### ISSUE TITLE
Electrum 3.0 not detecting Trezor

### ISSUE THREAD

**Issue by charlespax** [spesmilo/electrum#3214]
I have been using multiple Trezors successfully with a previous version of Electrum and with wallet.trezor.io. I recently upgraded to Electrum 3.0. I can no longer use my Trezors with Electrum 3.0. I can, however, successfully use my Trezors with wallet.trezor.io.

I installed Electrum 3.0 using the following command.
```
sudo pip3 install https://download.electrum.org/3.0/Electrum-3.0.tar.gz
```

Here is the output of an Electrum 3.0 session. In this session I start Electrum and attempt to make a new wallet.
```
charles@mbx:~$ electrum version
3.0
charles@mbx:~$ electrum -v -w new-temp-wallet
[SimpleConfig] electrum directory /home/charles/.electrum
[get_server] [Errno 111] Connection refused
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0025
[Network] blockchains dict_keys([0])
[Network] starting network
[Network] connecting to electrum.cutie.ga:50002:s as new interface
[FxThread] using exchange BitcoinAverage
[BitcoinAverage] requesting fx history for USD
[BitcoinAverage] getting fx quotes for USD
[WalletStorage] wallet path /home/charles/new-temp-wallet
[WalletStorage] wallet path /home/charles/new-temp-wallet
[electrum2.everynothing.net] connected
[WalletStorage] wallet path /home/charles/new-temp-wallet
[bitcoin.cluelessperson.com] connected
[Network] no height for main interface
[Network] switching to electrum2.everynothing.net:50002:s
[Network] sending subscriptions to electrum2.everynothing.net:50002:s 0 0
[electrum.cutie.ga] failed to connect [Errno 111] Connection refused
EOF occurred in violation of protocol (_ssl.c:645)
[helicarrier.bauerj.eu] connected
[BitcoinAverage] received fx quotes
[BitcoinAverage] received fx history for USD
[electrum.festivaldelhumor.org] connected
[electrum.antumbra.se] connected
[electrum3.hachre.de] connected
[electrum.be] connected
[ndnd.selfhost.eu] connected
[electrumx.schneemensch.net] connected
[daedalus.bauerj.eu] connected
[Network] fee_estimates[25] 189825
[Network] fee_estimates[10] 230831
[Network] fee_estimates[5] 255661
[Network] fee_estimates[2] 280212
[Network] relayfee 1000
```
This windows opens with the new wallet name as expected. No change in terminal output. I click Next.
![screenshot from 2017-11-04 12-30-34](https://user-images.githubusercontent.com/281642/32407217-12ba4afa-c15c-11e7-89be-90335297de2c.png)

This window opens as expected. No change in terminal output. I click Next.
![screenshot from 2017-11-04 12-32-07](https://user-images.githubusercontent.com/281642/32407228-3ffcae68-c15c-11e7-9819-fd2071e1e3f0.png)

This window opens as expected. I choose 'Use a hardware device'. No change in terminal output. I click Next.
![screenshot from 2017-11-04 12-46-18](https://user-images.githubusercontent.com/281642/32407378-37bd5c1e-c15e-11e7-83be-46b5f2bf82c5.png)

The following text is output to the terminal and the following window opens.
```
[Plugins] loaded keepkey
[Plugins] loaded digitalbitbox
[Plugins] loaded ledger
[Plugins] loaded trezor
```
![screenshot from 2017-11-04 12-33-22](https://user-images.githubusercontent.com/281642/32407395-7fdb7b16-c15e-11e7-8632-cd92c44e5588.png)

I disconnect and reconnect the Trezor, then click Next again. No change in output.

When I disconnect and reconnect the Trezor `dmesg` gives the following output.

```
[11745.966282] usb 1-1: USB disconnect, device number 17
[11752.842645] usb 1-1: new full-speed USB device number 18 using xhci_hcd
[11752.983738] usb 1-1: New USB device found, idVendor=534c, idProduct=0001
[11752.983742] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[11752.983745] usb 1-1: Product: TREZOR
[11752.983747] usb 1-1: Manufacturer: SatoshiLabs
[11752.983749] usb 1-1: SerialNumber: D92354331081A68D27B0CD57
[11752.986110] hid-generic 0003:534C:0001.001E: hiddev0,hidraw1: USB HID v1.11 Device [SatoshiLabs TREZOR] on usb-0000:00:14.0-1/input0
[11752.988234] hid-generic 0003:534C:0001.001F: hiddev1,hidraw2: USB HID v1.11 Device [SatoshiLabs TREZOR] on usb-0000:00:14.0-1/input1
```

The Trezor manager says I'm using firmware v1.5.2.
![screenshot from 2017-11-04 12-53-01](https://user-images.githubusercontent.com/281642/32407428-27164f96-c15f-11e7-8a17-294d895f8a94.png)

**Comment by charlespax** [comment]
I did a `git clone` of the electrum repo (at commit c79655d26a37d9cd11902c938c72152fa8d52a50). Running `./electrum` from the repo gives the same result.

**Comment by charlespax** [comment]
If I checkout version 2.9.3 from the repo, Electrum is able to detect the Trezor.

```
git checkout 2.9.3
pyrcc4 icons.qrc -o gui/qt/icons_rc.py
./electrum -v -w new-temp-wallet
```
![screenshot from 2017-11-04 13-02-01](https://user-images.githubusercontent.com/281642/32407498-679905c6-c160-11e7-8b66-6281ac3f905a.png)

The error returns if I go back to running version 3.0.
```
charles@mbx:~/github/electrum$ git checkout master
Previous HEAD position was 24e3fab... prepare version 2.9.3
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
charles@mbx:~/github/electrum$ ./electrum version
3.0
charles@mbx:~/github/electrum$ pyrcc5 icons.qrc -o gui/qt/icons_rc.py
charles@mbx:~/github/electrum$ ./electrum -v -w new-temp-wallet
```
![screenshot from 2017-11-04 13-07-22](https://user-images.githubusercontent.com/281642/32407546-273bd782-c161-11e7-9fe9-decbf7bec6ed.png)

**Comment by SomberNight** [comment]
Electrum 3.0 was migrated to python 3; previous release used python 2.
Make sure the Trezor library and related dependencies are available to python 3, not just 2.
E.g. try `python3 -m pip install trezor`
