### ISSUE TITLE
keeps synchronizing and / or ist not able to connect

### ISSUE THREAD

**Issue by atlatrk** [spesmilo/electrum#3215]
I was using version 2.6.4 on Windows 7, 64 bit.
When I choosed several servers either it was directly showing me disconnected or just keeping synchronizing.
Then I was downloading Version 3.0, when I tried to start it I've got the Python DLL-Error like the other people here, I can just open the 2.6.4-Version.

What I am supposed to do know? I am really thankful for every help

**Comment by SomberNight** [comment]
Please use 2.9.3 for the time being.

**Comment by atlatrk** [comment]
Thx 4 reply. Shall I deinstall the other Versions ?

**Comment by ecdsa** [comment]
yes
