### ISSUE TITLE
(Unity) Menubar missing after Hide->Show

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3218]
On git master c79655d26a37d9cd11902c938c72152fa8d52a50.
On Ubuntu 17.04 (with Unity), using the QT GUI, assume one wallet/window open.

0. check that the (native) menubar for Electrum is working
1. click the tray icon for Electrum
2. go into the submenu for the window
3. choose `Show/Hide`
4. Electrum gets minimised
5. repeat steps 1-3
6. Electrum reappears
7.  the menubar is no longer available

At step 0:
![ubuntu_17_04_menubar](https://user-images.githubusercontent.com/29142493/32408386-2b544ca6-c197-11e7-9efc-f3f4bcd93683.png)

At step 7:
![ubuntu_17_04_no_menubar](https://user-images.githubusercontent.com/29142493/32408388-31556ae0-c197-11e7-8eaa-db6e6ba0110c.png)

Ubuntu 17.10 (with GNOME) is not affected.

Ubuntu 16.04 (Unity) is affected, or it would be were it not for #3216 (as due to that issue you can't minimise Electrum), but if you circumvent that bug and directly call
https://github.com/spesmilo/electrum/blob/c79655d26a37d9cd11902c938c72152fa8d52a50/gui/qt/main_window.py#L270-L274
then this issue can be reproduced.

-----
Test machines:

```
Ubuntu 16.04 (Unity)
Qt version: 5.5.1
SIP version: 4.17
PyQt version: 5.5.1
```

```
Ubuntu 17.04 (Unity)
Qt version: 5.7.1
SIP version: 4.18.1
PyQt version: 5.7
```

```
Ubuntu 17.10 (GNOME)
Qt version: 5.9.1
SIP version: 4.18.1
PyQt version: 5.7
```

-----

Possibly related:
https://bugreports.qt.io/browse/QTCREATORBUG-17519
https://forum.qt.io/topic/7276/menu-not-showing-up-in-menubar/9

I have tried the workaround of not using the native menubar mentioned in those links. It works for Ubuntu 17.04. On Ubuntu 16.04, the option seems to be ignored for some reason, as the native menubar is still used regardless the setting.

```
diff --git a/gui/qt/__init__.py b/gui/qt/__init__.py
index ad733a52..a1b29a7c 100644
--- a/gui/qt/__init__.py
+++ b/gui/qt/__init__.py
@@ -98,6 +98,7 @@ class ElectrumGui:
         self.efilter = OpenFileEventFilter(self.windows)
         self.app = QElectrumApplication(sys.argv)
         self.app.installEventFilter(self.efilter)
+        self.app.setAttribute(Qt.AA_DontUseNativeMenuBar)
         self.timer = Timer()
         self.nd = None
         self.network_updated_signal_obj = QNetworkUpdatedSignalObject()
```

**Comment by bauerj** [comment]
This looks like a bug in either Qt or Unity. I'm not sure if this can be fixed in Electrum.

**Comment by SomberNight** [comment]
probably outdated.
