### ISSUE TITLE
Specific Crash Issue When entering amounts to receive BTC on Linux Mint.

### ISSUE THREAD

**Issue by Plumbuss** [spesmilo/electrum#3220]
Hey all, I'm new to Github as a whole, but I found a minor bug that is reproducible on my machine. When navigating to the "Receive" menu, one can enter a "Requested amount" of mBTC. When using the program, I accidentally held down a number, and upon having a 26 digit number in the box, the program crashed. 
I tested the USD box and the amount options under the "Send" menu, but none of them produce a crash. I have reproduced this bug and it is very consistent. This wouldn't be an issue in daily use, and I only found it by accident, but I decided to sign up here and leave my two cents just to help a bit. Thanks.

**Comment by ariard** [comment]
Hi, i tried it with more than 26 digit and an amount in BTC and nothing happens (fedora), are you using the last version of Electrum ? It was a special number ?

**Comment by hegjon** [comment]
I could not reproduce this on Electron 3.0.3 on Fedora 26

**Comment by SomberNight** [comment]
Could not reproduce. Could you test with 3.0.6 or master?
Also, please try starting Electrum with the `-v` flag and provide the logs; hopefully there is a stack trace there.
