### ISSUE TITLE
"Invalid Fee" error when sending from address used to mine

### ISSUE THREAD

**Issue by GSXswe** [spesmilo/electrum#3221]
Hi,

I have a problem with Electrum Verge wallet version 2.4 and 2.4.1, have a address used for mining that I can't send my XVG from, what ever I do I get the "invalid fee" error message.  
Have tried to use the "send from" function from the address too and then nothing happens at all, no error message, nothing... 
Have also tried to restore wallet, tried the Tor Electrum wallet with the exact same result.

Help! 

Regards, GSXswe.

**Comment by SomberNight** [comment]
Hi. Sorry but you're unlikely to get support for altcoins here.
That project is a fork of Electrum, try to ask them.
