### ISSUE TITLE
Verge Electrum Wallet wont open.

### ISSUE THREAD

**Issue by jzeped10** [spesmilo/electrum#3227]
I have been having issues with the wallet not connecting to a server, and now I tried opening the wallet, and it says that there is a "python error in the main script". How can I recover my coins?

**Comment by ecdsa** [comment]
please do not post this here

**Comment by jzeped10** [comment]
Sorry, do you know where I can get an answer?

**Comment by ecdsa** [comment]
no

**Comment by ecdsa** [comment]
this repo is about electrum, a Bitcoin wallet.
