### ISSUE TITLE
fee show up as "UNKNOWN" on the ledger nano s

### ISSUE THREAD

**Issue by Thoragh** [spesmilo/electrum#3230]
The fee show up as "UNKNOWN" on the ledger nano s when sending a transaction.
And then electrum hangs when I confirm or deny the transaction.

Im using electrum 3.0.1 and have the latest software on the nano s (1.1.10)

**Comment by ecdsa** [comment]
that is expected. It is because of this commit: 1ecfcea8dcfe37df4c6dceeaf071f19c7660c44b
I did that because ledger crashes with inputs sent from segwit addresses

**Comment by ecdsa** [comment]
see https://github.com/LedgerHQ/btchip-python/issues/30

**Comment by ecdsa** [comment]
I reverted 1ecfcea, because it has been fixed. 
you will need to upgrade to the latest version of btchip-python

**Comment by ecdsa** [comment]
note: reverted in ea4d2343d3d0cb0b69a8641428129004f742a819
