### ISSUE TITLE
Troian false positive?

### ISSUE THREAD

**Issue by Hostile** [spesmilo/electrum#3232]
Hi, can you evaluate on https://www.virustotal.com/pl/file/0d4884b3da33b1e390420691661652028dca178b860e079e520deec0a13220b4/analysis/

**Comment by SomberNight** [comment]
That is the correct sha-256 hash for the `setup` Windows binary. You can check the GPG signature yourself.
It almost surely is a false positive warning. There is at least one other issue about this #3198.
