### ISSUE TITLE
Lost Password

### ISSUE THREAD

**Issue by Marago70** [spesmilo/electrum#3241]
It may sound careless, but somehow I wrote down my password incorrectly. Can someone please help me to restore with wallet seed.
Thank you.

**Comment by neocogent** [comment]
If you cannot find the password your only choice is to use a password cracker like [JohnTheRipper](https://github.com/magnumripper/JohnTheRipper)(fastest but hardest to use) , [btcrecover](https://github.com/gurnec/btcrecover) (easier but slower) or my own [pwscanx](https://github.com/neocogent/misc/blob/master/scripts/pwscanx) (even slower and easy too, pre-2.8.0 only).
