### ISSUE TITLE
strange additional output address

### ISSUE THREAD

**Issue by lkthomas** [spesmilo/electrum#3242]
![image](https://user-images.githubusercontent.com/581053/32547340-f00ee36c-c4bc-11e7-9fe0-d879e49878e4.png)

I am trying to send 1 mBTC out, but somehow my Trezor asking me to confirm two destination address with different amount, why is there have another address within output list?

Remark: two output address have been removed for security reason

**Comment by SomberNight** [comment]
I am guessing it's just change.
https://en.bitcoin.it/wiki/Change

Is the intended destination the "1" address?
The green colour for the "3" address output suggests that's a receiving address of yours though...

**Comment by SomberNight** [comment]
Based on IRC chat, the wallet is 2-of-2 p2sh multisig with two Trezor cosigners.
User had the "use change addresses" option disabled, hence one of the output addresses (for the change) is the same as the input address.
There is no bug here.

**Comment by lkthomas** [comment]
Thanks, I didn't know there is a "change"
