### ISSUE TITLE
2 of 3 multisignature segwit transaction requires 3 signatures

### ISSUE THREAD

**Issue by Raulo** [spesmilo/electrum#3244]
Electrum HEAD 
368aaebb23f7c0c6a7cc1bd603d2a3eefa65590f

Created 2 of 3 multisignature segwit bech32 wallets.

Transaction created with such a wallet in GUI shows only 2 signatures required (after first signature). Deserialized transaction saved before signing:

{
    "inputs": [
        {
            "address": "tb1qldrj87p59ktf3ftpqwvphc9jtp3nhjylaefjvps8aje7n6ac94squ8drdw",
            "num_sig": 3,
            "prevout_hash": "8e7c55e2357753170c038be93d9c0629fc5b9bf66ae775d5d2380548da53c2cf",
            "prevout_n": 1,
            "pubkeys": [
                "02789e33ffd800ba3ffd28c77a92f98004e87a601b568f48a3be70ed5f1c4fc3ca",
                "0344dcd80ce2e5c8d09e1ed1c4cbf611f18c102ceb27e469a33510be36e34dce4e",
                "03af6766ab9baeba03ff0e03caee05bc91db7b50ca53d2bbcba62b23e153c09ca6"
            ],
            "scriptSig": "",
            "sequence": 4294967293,
            "signatures": [
                null,
                null,
                null
            ],
            "type": "p2wsh",
            "value": 10000,
            "witnessScript": "522102789e33ffd800ba3ffd28c77a92f98004e87a601b568f48a3be70ed5f1c4fc3ca210344dcd80ce2e5c8d09e1ed1c4cbf611f18c102ceb27e469a33510be36e34dce4e2103af6766ab9baeba03ff0e03caee05bc91db7b50ca53d2bbcba62b23e153c09ca653ae",
            "x_pubkeys": [
                "ff02aa7ed3017784a48280000001ed23d5e297612e7f0cb73f44581c03ef4b82f7797a91df54f033fda72b41458a02330d1635efbca7fe9feb3d523dbf71361f9aa9a3cdf03fa6c43fce26cc6a067f00000000",
                "ff02aa7ed30119cb50d8800000010b4c4f63bb3c194be4d3e7269c48153b7b4b4ace9fe86139722787e8b7079eb2039c2f20b5f05e39dbaf8587fe9cc84a176f9e84041375e10173a595f3e0eaf61600000000",
                "ff02aa7ed301cda0865180000001199684fb24ec50ed7592006fb0101914e0ef564af01e914108cc5cfba7649747034271cf5bcbb08f245bf77d9cb7bfb6515ea51f7e221f88cdc97ea55fe822c84000000000"
            ]
        }
    ],
    "lockTime": 1226296,
    "outputs": [
        {
            "address": "myk428Uu8x5ZT1YuJNv1pmF6USoppZeWSy",
            "prevout_n": 0,
            "scriptPubKey": "76a914c7ec7372e009de6c85cbd191e7e73e01f3d33d0188ac",
            "type": 0,
            "value": 9700
        }
    ],
    "version": 1
}

After signing:

{
    "inputs": [
        {
            "address": "tb1qldrj87p59ktf3ftpqwvphc9jtp3nhjylaefjvps8aje7n6ac94squ8drdw",
            "num_sig": 3,
            "prevout_hash": "8e7c55e2357753170c038be93d9c0629fc5b9bf66ae775d5d2380548da53c2cf",
            "prevout_n": 1,
            "pubkeys": [
                "02789e33ffd800ba3ffd28c77a92f98004e87a601b568f48a3be70ed5f1c4fc3ca",
                "0344dcd80ce2e5c8d09e1ed1c4cbf611f18c102ceb27e469a33510be36e34dce4e",
                "03af6766ab9baeba03ff0e03caee05bc91db7b50ca53d2bbcba62b23e153c09ca6"
            ],
            "scriptSig": "",
            "sequence": 4294967293,
            "signatures": [
                "304402205e0f8b8b2e5aef39cd6bf30b685b673fa816458aececcaa15bccf25052cc0b5602205e22e62bcfc0fbd14c450f24df7a553abdc7ed08fa801cf7212e473e8c27dd4101",
                null,
                null
            ],
            "type": "p2wsh",
            "value": 10000,
            "witnessScript": "522102789e33ffd800ba3ffd28c77a92f98004e87a601b568f48a3be70ed5f1c4fc3ca210344dcd80ce2e5c8d09e1ed1c4cbf611f18c102ceb27e469a33510be36e34dce4e2103af6766ab9baeba03ff0e03caee05bc91db7b50ca53d2bbcba62b23e153c09ca653ae",
            "x_pubkeys": [
                "ff02aa7ed3017784a48280000001ed23d5e297612e7f0cb73f44581c03ef4b82f7797a91df54f033fda72b41458a02330d1635efbca7fe9feb3d523dbf71361f9aa9a3cdf03fa6c43fce26cc6a067f00000000",
                "ff02aa7ed30119cb50d8800000010b4c4f63bb3c194be4d3e7269c48153b7b4b4ace9fe86139722787e8b7079eb2039c2f20b5f05e39dbaf8587fe9cc84a176f9e84041375e10173a595f3e0eaf61600000000",
                "ff02aa7ed301cda0865180000001199684fb24ec50ed7592006fb0101914e0ef564af01e914108cc5cfba7649747034271cf5bcbb08f245bf77d9cb7bfb6515ea51f7e221f88cdc97ea55fe822c84000000000"
            ]
        }
    ],
    "lockTime": 1226296,
    "outputs": [
        {
            "address": "myk428Uu8x5ZT1YuJNv1pmF6USoppZeWSy",
            "prevout_n": 0,
            "scriptPubKey": "76a914c7ec7372e009de6c85cbd191e7e73e01f3d33d0188ac",
            "type": 0,
            "value": 9700
        }
    ],
    "version": 1
}

Loaded to second wallet show 1/3 signatures. 

Standard 2 of 3 wallet works without any problems.

**Comment by ecdsa** [comment]
thanks for reporting this. please try with current HEAD

**Comment by Raulo** [comment]
Works fine with the current HEAD
