### ISSUE TITLE
"Not enough funds" in Electrum (3.0.1/OSX) wallet

### ISSUE THREAD

**Issue by lezhnev74** [spesmilo/electrum#3246]
Hi!
This is my situation:
- I made a new wallet in Electrum wallet;
- Exported xpub address and generate few sub-addresses;
- Accepted funds on those addresses;
- I can see confirmed incoming transactions in Electrum, as well as total Balance, shows a correct amount.

The problem is that when I click "send" and try to transfer accumulated funds somewhere else it says `Not enough funds`.  

How can solve the problem and send my funds?

**Comment by AbdussamadA** [comment]
>Exported xpub address and generate few sub-addresses;

What do you mean by this? You created a watch-only wallet?

**Comment by DeRain** [comment]
@AbdussamadA no, i think the wallet was created by the mnemonic phrase, and then the 3rd party has created some addresses from the master public key.

**Comment by lezhnev74** [comment]
Well, I have created a normal wallet with seed phrase, password and private keys.
Then I utilized features that [BIP32 protocol](https://bitcoinmagazine.com/articles/deterministic-wallets-advantages-flaw-1385450276/) offers and generated a few derived public addresses which I gave to clients. By this (I think) I had my private keys safe and yet I allowed each client to transfer funds to a new unique address (which I generated from my master public key).

**Comment by ecdsa** [comment]
just set the fee manually

**Comment by lezhnev74** [comment]
I fact, @ecdsa suggested the solution. It worked!

What was the problem actually? Just so Electrum has automatically set too high fee amount which were greater than my total balance?

**Comment by ecdsa** [comment]
the problem was that you did not see the fee
