### ISSUE TITLE
Ledger and segwit addresses: unable to send

### ISSUE THREAD

**Issue by TheGoldenEye** [spesmilo/electrum#3248]
If I want to send some coins from / to a multisigature (P2SH) address, I will get the following error:
`error: {'message': 'the transaction was rejected by network rules.\n\n64: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)\n[01000000000101284b0cc8b7ef51d1b12788da3f9155c688323c5f7f7955a17a9fec20a2e7c43d0000000017160014ee2f0a4d8d7a504ac349e3ede463a44bb53dfe14feffffff02a08601000000000017a91458f73dcd4ac46be112d73e8ed5c8ea25a403cfa987b42a0d000000000017a914d800e5f11618ba520dd95c409b9901869c6eb13587024730440220725c8d51fc9e709cfbb99ac3f077fcb29943cf54b7a8d8e0aafb35718d97423902201d6a1acbbb41eb2b6b9bed92fafa3a9bb5cb5d405de05a1fde884b997ba547d401210371a2a9ba55019e78d0f0044ecf95464cd3497e55fd939eeb6a4f9cb83404a1bb60880700]', 'code': -1}`

Ledger Nano S with current firmware
address type segwit (3...)
Electrum V3.0.1

**Comment by SomberNight** [comment]
So what is your wallet type in which you are creating the tx? Is it a single signer p2sh-segwit (`p2wpkh-p2sh`), using a Ledger?

**Comment by TheGoldenEye** [comment]
yep

**Comment by SomberNight** [comment]
I think this might be related to https://github.com/spesmilo/electrum/commit/1ecfcea8dcfe37df4c6dceeaf071f19c7660c44b

Could you test with `btchip-python` version `0.1.23`:
```
python3 -m pip install --upgrade btchip-python
```
AND also (at the same time) with Electrum master (git HEAD) so that it contains https://github.com/spesmilo/electrum/commit/ea4d2343d3d0cb0b69a8641428129004f742a819 ?

**Comment by ecdsa** [comment]
@SomberNight not related.

**Comment by Raulo** [comment]
I have the same problem for single signature segwit Ledger testnet wallet (m/49'/1'/0')
with HEAD ce4be1f and btchip-python version 0.1.23. I get the same error message "Signature must be zero for failed CHECK(MULTI)SIG operation". 

Non-segwit wallet works OK (even though Ledger incorrectly prints mainnet addresses instead of testnet)

**Comment by neocogent** [comment]
Where is btchip-python 0.1.23 coming from? When I pip upgrade I only see 0.1.22.

**Comment by Raulo** [comment]
> Where is btchip-python 0.1.23 coming from? When I pip upgrade I only see 0.1.22.

Manual install from git source: [https://github.com/LedgerHQ/btchip-python](url)

**Comment by Raulo** [comment]
If it can help to track the problem, I created the same transaction from two testnet wallets:  a Ledger  m/49'/1'/0'  one and an Electrum m/49'/1'/0' wallet from the Ledger BIP39 seed. Electrum transaction works fine:

{
    "inputs": [
        {
            "address": "2Mw962ywgrv3yU7Z2hbShBLvnnSaZUfthXz",
            "num_sig": 1,
            "prevout_hash": "591c2a184276e472a03cc377c4e1821cee731a125472fc3a26c12b472f7aa98b",
            "prevout_n": 0,
            "pubkeys": [
                "0392364d50dbce7fd5398c57b71a2d53ec4888df8acd37ae878b5c7c52e1881462"
            ],
            "scriptSig": "1600143b80cade95de96bfa2e35117d53d095eee40fa3e",
            "sequence": 4294967293,
            "signatures": [
                "3045022100de1532988132432d9c940ecfa5224df3fe653e331a85ea45de4bd37efa66b839022048a150d3e5e23408502d4485be3813db01e7c556d9a279b925d948821dde389701"
            ],
            "type": "p2wpkh-p2sh",
            "x_pubkeys": [
                "0392364d50dbce7fd5398c57b71a2d53ec4888df8acd37ae878b5c7c52e1881462"
            ]
        }
    ],
    "lockTime": 1229711,
    "outputs": [
        {
            "address": "2NDnpJiwzdwsrewmLxneBtUQMWNnkABnMWw",
            "prevout_n": 0,
            "scriptPubKey": "a914e15c0ec2b94c039ac9a24bf46a809f33f4d7991c87",
            "type": 0,
            "value": 4823
        },
        {
            "address": "2N9q6uC7DhHGSwhEor7Z7JvniLc3T6dYpVc",
            "prevout_n": 1,
            "scriptPubKey": "a914b5ea3d187bfb46d4436066ec8e56edb66a1a712887",
            "type": 0,
            "value": 5011
        }
    ],
    "version": 1
}

Transaction signed by Ledger has the same pubkey but a different signature:

"signatures": [
                "3045022100bda22b8e842c2a0b8514dfb6d131e8b14a4ce2e65a2b046447e99667c665ccf3022018d9e6e051aead31e6b6a4d8c3b4de12c1bea094c99cfd99ed67245957884c1a01"
            ],

and is rejected by the network.

**Comment by ecdsa** [comment]
yes, that means ledger is not signing the corrrect preimage

**Comment by Raulo** [comment]
So is it an Electrum bug, btchip-python bug, or ledger firmware bug? Is there anything I can do to help finding the bug?

**Comment by ecdsa** [comment]
@btchip

**Comment by DocSnyd3r2** [comment]
Same here with Electrum 3.0.1 on Mac, tried to use child pays for parent.

Can you please point to the btchip issue with a deep link or di we need to open one?

**Comment by Raulo** [comment]
It is seems the problem is in missing lockTime=tx.locktime in the ledger plugin. The attached patch fixes my problem with the ledger segwit signing. 

[locktimediff.patch.txt](https://github.com/spesmilo/electrum/files/1463651/locktimediff.patch.txt)

**Comment by ecdsa** [comment]
thanks

**Comment by wonbinbk** [comment]
Thanks.
