### ISSUE TITLE
Tools-> Network crashes on Windows 7x64

### ISSUE THREAD

**Issue by maxit77** [spesmilo/electrum#3250]
Hello everybody,

Every time I want to go to the Network menu (under Tools), electrum 3.01 crashes. I got a popup with : "Windows Explorer has stopped working"
![capture](https://user-images.githubusercontent.com/33501002/32579147-2c406cc0-c4e0-11e7-8835-28a393c14525.PNG)
Any idea ?

Thank you.

**Comment by SomberNight** [comment]
I think this is #3237. It is due to a badly formatted translation, and is a locale specific problem.

**Comment by ecdsa** [comment]
indeed
