### ISSUE TITLE
wallet emptied by Electrum on phone

### ISSUE THREAD

**Issue by cristhewiss** [spesmilo/electrum#3251]
i put some bitcoin into my phone electrum wallet. a coupe of days later it all went out without me doing anything.
i have the address it went to and its still there. how do i get it back.

**Comment by ecdsa** [comment]
it is possible that somebody got access to your seed and stole the bitcoins.
if that is the case you cannot get them back; bitcoin transactions are not reversible

**Comment by cristhewiss** [comment]
Hi ThomasI had the Electrum wallet on my phone so i guess it could have been hacked?My friend looked into it and said (1.097 bit, the entire wallet)  was sent to an address:1D5KX2LEJcHBnMMbP2jRvJ2WK4LrNGPEQU on the 4/11/17from my address:1CiVZqJM5Xf7HnMDMmYYpGJRyYTTNic4mSthen split into 2 and sent on.Is there any way of tracking these address or putting out a stop on them?Cris--- notifications@github.com wrote:From: ThomasV <notifications@github.com>To: spesmilo/electrum <electrum@noreply.github.com>Cc: cristhewiss <innovation@surf.co.nz>,  Author <author@noreply.github.com>Subject: Re: [spesmilo/electrum] wallet emptied by Electrum on phone (#3251)Date: Thu, 09 Nov 2017 08:57:49 +0000 (UTC)it is possible that somebody got access to your seed and stole the bitcoins.
if that is the case you cannot get them back; bitcoin transactions are not reversible

**Comment by neocogent** [comment]
There's no way of putting a stop on them. If you want help trying to track down where they went I'd suggest posting a thread on http://reddit.com/r/electrum as that is a better place to get users support and help. It will be seen by more people who try to help with problems. This issue tracker is for dealing with bugs and programming issues.

**Comment by cristhewiss** [comment]
do i start a new thread?Cris --- notifications@github.com wrote:From: neoCogent <notifications@github.com>To: spesmilo/electrum <electrum@noreply.github.com>Cc: cristhewiss <innovation@surf.co.nz>,  Author <author@noreply.github.com>Subject: Re: [spesmilo/electrum] wallet emptied by Electrum on phone (#3251)Date: Fri, 10 Nov 2017 04:46:07 +0000 (UTC)There's no way of putting a stop on them. If you want help trying to track down where they went I'd suggest posting a thread on http://reddit.com/r/electrum as that is a better place to get users support and help. It will be seen by more people who try to help with problems. This issue tracker is for dealing with bugs and programming issues.

**Comment by ecdsa** [comment]
@cristhewiss this website is for bug reports. we would be happy to investigate your issue if we had any reason to believe that the theft occurred because of a bug in the software. However, with the information you provided, there is nothing we can do to help you, and there is no reason to believe it is a software issue.

Theft can occur if you do not protect your seed, or if you use an insecure system. Since Android is fairly secure (compared to windows), I believe someone had access to your seed, or to your phone and PIN. Of course these are just assumptions; with the very poor information that you give, we can only make assumptions. 

if you post this to a forum, I suggest you provide much more information that what you just did.

**Comment by cristhewiss** [comment]
Hi Thomasthanks for your replyI'm new to this as you can see, but would like to get to the bottom of it.No one had access to my phone physically or the seed, so I think this only leaves a software bug or back door as possibles?Please let me know what information you need to look into this furtherBest RegardsCris--- notifications@github.com wrote:From: ThomasV <notifications@github.com>To: spesmilo/electrum <electrum@noreply.github.com>Cc: cristhewiss <innovation@surf.co.nz>,  Mention <mention@noreply.github.com>Subject: Re: [spesmilo/electrum] wallet emptied by Electrum on phone (#3251)Date: Fri, 10 Nov 2017 08:36:55 +0000 (UTC)@cristhewiss this website is for bug reports. we would be happy to investigate your issue if we had any reason to believe that the theft occurred because of a bug in the software. However, with the information you provided, there is nothing we can do to help you, and there is no reason to believe it is a software issue.
Theft can occur if you do not protect your seed, or if you use an insecure system. Since Android is fairly secure (compared to windows), I believe someone had access to your seed, or to your phone and PIN. Of course these are just assumptions; with the very poor information that you give, we can only make assumptions.
if you post this to a forum, I suggest you provide much more information that what you just did.
