### ISSUE TITLE
"No module named 'setuptools'" error upon installation

### ISSUE THREAD

**Issue by durbanpoison** [spesmilo/electrum#3252]
I am trying to follow the "Installation from Python source" instructions for Linux on the website using Linux Mint 18.2 and am getting an error after entering this command:  

```

sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'

```  

Any idea what could be going wrong? I am trying to install from Python source because the regular installation instructions (included below for reference) were throwing me a similar error.

* Reference  

Install dependencies:
`sudo apt-get install python3-pyqt5 python3-pip`
Install Electrum:
`sudo pip3 install https://download.electrum.org/3.0.1/Electrum-3.0.1.tar.gz`

**Comment by SomberNight** [comment]
`sudo apt-get install python3-setuptools`

**Comment by ecdsa** [comment]
I thought that setuptools would have been required by pip.
anyway, I added it to the download page
