### ISSUE TITLE
Electrum 3.0.0 SSL issues

### ISSUE THREAD

**Issue by shyrwall** [spesmilo/electrum#3253]
Commit https://github.com/spesmilo/electrum/commit/d304ccdf17be860b2828c1b6b31a6ba7aaa32020#diff-526a42e182c50a4695423d9e4d197f01

breaks connections to ElectrumX servers using valid non self-signed certs since ElectrumX is using TLSv1.2.
Not sure why it doesn't break self-signed servers also.

Suggest changing PROTOCOL_TLSv1_1 to just PROTOCOL_TLS

**Comment by SomberNight** [comment]
server:
https://github.com/kyuupichan/electrumx/blob/8c9731f0ad724766982d5e6bb4c6f2d639f15124/server/controller.py#L271

client:
https://github.com/spesmilo/electrum/blob/ccc94155429241c3d344183a4efdddbbcf6736cf/lib/interface.py#L137
https://github.com/spesmilo/electrum/blob/ccc94155429241c3d344183a4efdddbbcf6736cf/lib/interface.py#L153
https://github.com/spesmilo/electrum/blob/ccc94155429241c3d344183a4efdddbbcf6736cf/lib/interface.py#L178

python doc:
https://docs.python.org/3/library/ssl.html#ssl.wrap_socket

Seems to me, that the server is setting TLS, and the client is setting TLSv1.1; and that looks to be compatible based on the table in the python doc. (?)
Have you tried what you're suggesting and if so did that fix the problem for you?

**Comment by shyrwall** [comment]
Hi

I found the problem and it's a little bit my fault but also not :D I'm running Debian Unstable and they have dropped support for TLS 1.0/1.1 (https://linux.slashdot.org/story/17/08/07/1823244/openssl-support-in-debian-unstable-drops-tls-1011-support) in OpenSSL. So my server is only accepting TLS 1.2.

I still however think it's wrong of Electrum not to support TLS 1.2. Until you are ready for Python 3.6 support and can do PROTOCOL_TLS I think the appropriate flag should be , 
PROTOCOL_SSLv23, OP_NO_SSLv2, OP_NO_SSLv3. If I understood it correctly this will make it support TLS 1.0,1.1,1.2 and not SSLv2,v3. Difference from current flag is adding TLS1.0 and 1.2 support.

Or as an alternative ,

PROTOCOL_SSLv23, OP_NO_SSLv2, OP_NO_SSLv3, OP_NO_TLSv1 which is same as the current flag but adds tls 1.2 support.
