### ISSUE TITLE
Fee selection not satoshi accurate. Fee is round up

### ISSUE THREAD

**Issue by Raulo** [spesmilo/electrum#3255]
3.0.1 version.

Fee selection from GUI (but surprisingly also from command line) is not accurate up to satoshi level. E.g,, for 142 byte transaction, lowest fee possible is 200 satoshi. If one selects max funds, full satoshi resolution is available. Tested both standard and segwit wallets.

**Comment by SomberNight** [comment]
Could you clarify what "142 byte" means in your particular example?

https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#transaction-size-calculations

If you've obtained that number from Electrum, it should be "virtual transaction size":
https://github.com/spesmilo/electrum/blob/ccc94155429241c3d344183a4efdddbbcf6736cf/lib/transaction.py#L831-L839

**Comment by Raulo** [comment]
Yes, virtual size. But for non-segwit transactions (that also are not satoshi level accurate) size=virtual size. 

For a 224 byte (non-segwit) transaction, specifying 2.24 bits fee results in rounding up to 3.00 bits. Also, e.g. 3.5 bits fee is rounded up to 4 bits

**Comment by SomberNight** [comment]
As a workaround, you can set `wallet.relayfee = (lambda: 0)` in the console (if using the QT GUI). This will allow you to broadcast a tx with an arbitrarily low fee but if it is below the relay fee of the Electrum server, you will be presented with an error message from the server.

**Comment by SomberNight** [comment]
Disregard above comment, I see the issue.

**Comment by SomberNight** [comment]
Indeed, fees can only be set to 100 sat precision (in most cases), due to this code snippet:
https://github.com/spesmilo/electrum/blob/ce4be1f8f236cf1ad33ee1aae2c4599bcb8e8e5a/lib/coinchooser.py#L147-L151

Changing this would have privacy implications. Though a choice could be given to the user by e.g. introducing a new CoinChooser, possibly.

**Comment by Raulo** [comment]
I see. It explains why if one chooses Max (no change), there is full precision. I realized now that if you send amount with full satoshi accuracy, the fee is up to satoshi level, too.  

And indeed replacing amounts.append(amount) with amounts.append(remaining) fixes the problem 

But the benefits of the code seem too elusive to me to institute a tax to miners. Sure if I send, say, 6786 bits, the change may look like the amount sent. But if I send 1 BTC, rounding to 1 bit will not mask the obvious change.

**Comment by principiante** [comment]
io ho scelto la tassa minima , ho fatto due transazioni ma non sono mai arrivate, ho perso tutto? op devo aspettare? come mi posso comportare?
grazie

**Comment by SomberNight** [comment]
Note: it is planned that we make this "privacy" rounding optional in version 3.1. However, there is also a "rounding" due to not keeping dust change but adding it instead to the fee, that will be kept as is.
