### ISSUE TITLE
KeepKey Unable to Pair w/Electrum 3.0.1 Wallet

### ISSUE THREAD

**Issue by PolkaD0T** [spesmilo/electrum#3260]
I am unable to pair my KeepKey with Electrum 2.7.10, 2.8.2, and now 3.0.1. See error message.

I will attempt to reproduce the steps I took:
1. I upgraded the firmware with the KK extension in Chrome
2. I tried initializing the KK device in Electrum (various ver) using the wizard. It hung (Please wait...)
3. I then initialized the device in Chrome and wrote down the seed
4. I then plugged in the KK and followed the wizard in 2.8.2. It worked.
5. I sent a small test transaction and saw it appear in the wallet. I exited.
6. I changed the PIN for the KK to a stronger code via Chrome extension
7. I relaunched 3.0.1 w/KK attached and entered the longer code. The error message appeared.

I can "watch" the wallet in any version of Electrum above but I cannot pair w/KK. I can also authenticate to the Chrome extension using the PIN and send small amount of coin. I don't want to do that though. I want to use Electrum.

Thanks,

![electrum-kk-pairing-issue](https://user-images.githubusercontent.com/26518635/32639858-973f6acc-c57a-11e7-9927-c52262e3b54a.png)

**Comment by ecdsa** [comment]
are you on linux? did you try to upgrade python-keepkey?

**Comment by PolkaD0T** [comment]
No. OSX. I used 2.7.10 or 2.8.2 binary to initially pair the KK with Electrum. I can still read the wallet with 2.7.10/2.8.2/3.0.1, but can no longer pair the KK with any version.

Are you saying I need to use the Python version and not the binary? I guess I can, but like the simplicity of the binary for OSX. Please advise.

**Comment by SomberNight** [comment]
Can you please try with 3.0.6 and report back?

**Comment by SomberNight** [comment]
> I changed the PIN for the KK to a stronger code via Chrome extension

See https://support.keepkey.com/support/solutions/articles/6000036899-error-message-could-not-parse-protocol-buffer-message
> When creating a new PIN, the maximum digits that can be entered is 9. Any additional digits entered when creating the PIN, generates the following error message in the KeepKey Wallet:
Could not parse protocol buffer message.

Your PIN is too long.

**Comment by SomberNight** [comment]
But if you think that's not the case, please
- say how many characters it contains
- if the issue still occurs with 3.1.3
- if you can use the keepkey with the chrome extension
