### ISSUE TITLE
Need Help Recovering LTC

### ISSUE THREAD

**Issue by Volvigo** [spesmilo/electrum#3263]
Hi guys, I am relatively new to online currencies and really screwed up when trying my hand at it for the first time. So I bought LTC off of coinbase and then tried moving my LTC to an electrum wallet. After moving the LTC to the wallet I realized that I had moved my LTC into a BTC type of electrum wallet. So, after spending a bit trying to figure out that I finally moved it to a 2-of-3 type of multisig, electrum LTC wallet but here is where the really problem starts. I lost my seed to my 2-of-3 wallet, also I cannot send any currency from said wallet because I was really excited when I saw I had my LTC back that I forgot to make a second wallet for signatures. I do not know if there is any way to retrieve my LTC back, I am still currently in full control of the LTC just unable to access the wallet seed and spend and of my coins. Thanks in advance for all the help.

**Comment by ecdsa** [comment]
offtopic
