### ISSUE TITLE
Electrum 3.0 crashes when signing transactions with Ledger

### ISSUE THREAD

**Issue by Dedados** [spesmilo/electrum#3264]
For the first time, I used my ledger nano s to send BTC using electrum but after pressing confirm on the device, Electrum freezes and doesn't respond. I tried on both MacOs and Win7, with the same exact behaviour, both running v3.0.1. I encountered no problems when using the ledger wallet.

**Comment by aaqilaziz** [comment]
I'm using win10. And the same happens to me but when I decline a transaction.

**Comment by ken2812221** [comment]
it might stuck on [clear_dialog](https://github.com/spesmilo/electrum/blob/e9191caf3912066d3660becc11cab9c11ea17ba2/plugins/ledger/ledger.py#L424) ,

**Comment by yorickdowne** [comment]
Same behavior Win10-64, Electrum 3.0.2, Ledger Nano S, attempting to send from Ledger. Get prompted to sign on Ledger and then Electrum hangs, "not responding". If forcefully closed and then re-opened, the transaction does not show up in history.

**Comment by SomberNight** [comment]
I can reproduce this on Windows 10, using the official 3.0.2 binaries;
but not on Debian 9, where it works correctly.

The `Confirm transaction on your Ledger device...` window pops up, the Ledger Nano S gets notified and asks me to confirm, but Electrum does not react to whatever buttons on the Ledger I push, and just hangs.

![ledger_electrum3_windows](https://user-images.githubusercontent.com/29142493/32954807-705f3834-cbb4-11e7-981c-80f4b9b721ab.png)

**Comment by SomberNight** [comment]
As a workaround, if you close the popup window before pushing the buttons on the Ledger, it will work.

**Comment by bustacapptv** [comment]
That workaround doesn't work for me. My Ledger never acknowledges any activity from the wallet. If I close the popup, nothing happens. If it try again, I then get a read error msg. This Ledger works with Ledger wallet apps.

**Comment by renkcub** [comment]
I have 3.0.2 is it possible to go back to 3.0.1 and try the workaround? or better to wait for 3.0.3?

**Comment by barryvdh** [comment]
I've also encountered this. Steps taken:

 - Create new wallet, choose standard -> with hardware
 - Change derivation path to `m/49'/0'/0' ` for segwit
 - It connects and shows the history/balance/receive address etc correctly
 - Send transaction and confirm on the device 
 - read error popup

**Comment by SomberNight** [comment]
@barryvdh 
This should be fixed in 3.0.3. If you're on an older version, please update.

If you're already on 3.0.3, this might be a different bug...
- Please describe "read error popup". 
- What OS are you using?

**Comment by barryvdh** [comment]
I'm using Windows 10, downloaded just a few hours ago. 

It didn't say much more except read error and I think an empty array (`[]`) on the next line, not 100% sure. Will test with next transaction, but cost me a couple of euros every time I try (and it works).

**Comment by barryvdh** [comment]
FYI, it also didn't recognize the Segwit address, had to manually change the derivation path which is kind of scary still.

**Comment by SomberNight** [comment]
> It didn't say much more except read error and I think an empty array (`[]`) on the next line

Ok, then that is a separate bug. Please open a new issue for it if it happens again, and reference this issue there. I will also try to reproduce.
If you have some time, you can also setup a testnet wallet, and try to reproduce there, to avoid paying btc fees.

> FYI, it also didn't recognize the Segwit address, had to manually change the derivation path which is kind of scary still.

What do you mean by that?
When you create the wallet, you can choose a bip32 derivation path, and Electrum will only create addresses for that subtree. Some paths have special meaning, such as due to bip49, which is used to decide what type of scripts to create. The derivation path dialog is currently simply prefilled according to bip44, there is no magic guessing.

**Comment by barryvdh** [comment]
I just mean that it might be more helpful if it was explained what it does, or that you can choose a format in a dropdown (eg. classic -> bip44, segwit -> bip49 etc)
