### ISSUE TITLE
Electrum Help PLEASE

### ISSUE THREAD

**Issue by Anonleo** [spesmilo/electrum#3266]
OKay so I wanted to see how safe electrum is so what your saying is if i lose my phone or cant use it I found out that when restoring it I can either disable it but still log in and can't use 2fa no more or keep the 2fa but it's pointless if you lose your phone or its not working and if i click forgot google authenticator code and click next it closes the whole client am i missing something here im using a macbook pro not sure if that helps someone help please?

**Comment by cluelessperson** [comment]
Chat with us here:
http://webchat.freenode.net/?channels=electrum

Give us more than 2 seconds to respond.lol

**Comment by Anonleo** [comment]
Thanks as we found out it was a bug in the system goodluck with fixing guys

**Comment by ecdsa** [comment]
fixed in 7bdaf01
