### ISSUE TITLE
Retrieving Private keys from used addresses?

### ISSUE THREAD

**Issue by Dnnyslll** [spesmilo/electrum#3267]
Hi Team
I had BTC in my account prior to the BCC/BCH fork and wasn't able to use electron cash due to the 2fa issue on their end (Is that fixed yet? I used a default wallet and don't think a seed was given, all the seeds I recorded don't show any BCC/BCH balance)

I thought about retrieving the private key for the address used but could not find the address in Electrums Address tab, is there a way to get this?

Thanks

**Comment by ecdsa** [comment]
a single private key is not sufficient to access your funds in the case of a 2fa address.
you can restore a 2fa wallet from seed and then spend from it without the cosigner

**Comment by Dnnyslll** [comment]
The private key was to export it to coinomi or something, and then spend, Like I said I don't have the seed for the default wallet
