### ISSUE TITLE
payment unconfirmed yet

### ISSUE THREAD

**Issue by umeshsavalia** [spesmilo/electrum#3269]
f31374e6308839031cb4b20e0ea46492a786e21614294cdf3c11efa1c2ae7b38 
payment not confirmed yet what should i do

**Comment by umeshsavalia** [comment]
why this is closed

**Comment by ecdsa** [comment]
because this is not the place to ask that kind of question

**Comment by umeshsavalia** [comment]
so where we ask

**Comment by umeshsavalia** [comment]
can you direct me

**Comment by umeshsavalia** [comment]
can you give me path for complaining
