### ISSUE TITLE
Electrum does not start on old Mac OS versions

### ISSUE THREAD

**Issue by maquei** [spesmilo/electrum#3270]
Hi everyone, hope you can help me out here, I was using Electrum 2.7 and it stopped sincronyzing. I tried updating to the 3.1 and the version came as 0.0.0 after installing. I am sure I downloaded it from electrum.org
Later I thew it away and tried the 2.9.3 version, even though it installed ok, it never opens. I've also tossed it.
I have backed up all the files from the .electrum folder to an offline drive, I have the seed and the password. 
I have deleted the previous 2.7 version from my computer, both app and folder.
Do you have any idea why this isn't working?
Thanks!

**Comment by bauerj** [comment]
What do you mean it "came as 0.0.0"? Where did it show that?

**Comment by maquei** [comment]
When you see the info about the app, where it should say the version, it only showed 0.0.0 instead of 3.0.1 or something like it.
The app was already installed in my applications folder. I am guessing it is because I am running Maverick...Because the 2.9.3 downloaded fine, and it appeared alright in the folder, but just wouldn't open.

**Comment by SomberNight** [comment]
Re "0.0.0" version: #3190 
That is just a "cosmetic" thing, should not be related to being able to synchronize in any way.

**Comment by maquei** [comment]
Ok, let me see if I can be clearer:
Version 2.7 was not syncronizing.
Opening version 2.9.3 was not possible, it crashes before opening any windows.
Opening version 3.1 dosn't work either, and on top of that it says the version is 0.0.0. 
Now I have no wallet.

**Comment by ecdsa** [comment]
@maquei try to create a new wallet with your seed, and report if it gets synchronized

**Comment by maquei** [comment]
That's what I am trying to do. I download, install, but the new versions of the wallets are not working here. I am asking if the fact that I am working on a OS 10.9.5 is the problem. There is no information on Electrum website about the system requirements for installation. If that is not the issue, then I really don't understand why I cannot create a new updated wallet. I hope you can assist me with this. Thanks.

**Comment by maquei** [comment]
Electrum 3.0.1 is 20.5 MB after installed (and shows it is version 0.0.0). It doesn't even open, the window only blinks.
Electrum 2.9.3 is 75MB after installed. It doesn't open, but the jumping icon appear as if it was trying to, until it crashes.

**Comment by maquei** [comment]
Hi, just so you know, I managed to install the version 2.9.2 and it worked well. I could restore my seed and verify all transactions. 
Thanks.

**Comment by SomberNight** [comment]
MacOS 10.9 might be too old for Electrum 3.0+ :(
The releases are built on 10.11 (El Capitan) and they might not work on anything older than that.

**Comment by nikitavoloboev** [comment]
Electrum-3.1.0 I just downloaded from [official page](https://electrum.org/#download) does not work on my macOS version 10.11 (El Captain).

I moved the .app to `/Applications` then tried to boot it up but nothing happens. The app doesn't boot up.

Thank you for any help.

**Comment by bauerj** [comment]
Hey Nikita,

you're lucky - El Capitan is the oldest version we still support!

To help you solve this problem, we need some debug logs from you.

Here is how you can provide the logs:

Open the terminal app, paste

    /Applications/Electrum.app/Contents/MacOS/Electrum -v

and press return.

Please respond with the output here.

**Comment by nikitavoloboev** [comment]
Here is the log:
```Bash
❯ /Applications/Electrum.app/Contents/MacOS/Electrum -v
[SimpleConfig] electrum directory /Users/nikivi/.electrum
[get_server] unexpected EOF while parsing (<unknown>, line 0)
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0062
[Network] blockchains dict_keys([0])
[Network] starting network
[Network] connecting to 88.198.43.231:50002:s as new interface
[FxThread] using exchange BitcoinAverage
Traceback (most recent call last):
  File "electrum", line 426, in <module>
  File "Electrum-3.1.0-py3.6.egg/electrum/daemon.py", line 135, in __init__
  File "Electrum-3.1.0-py3.6.egg/electrum/daemon.py", line 141, in init_server
  File "Electrum-3.1.0-py3.6.egg/electrum/daemon.py", line 111, in get_rpc_credentials
  File "Electrum-3.1.0-py3.6.egg/electrum/simple_config.py", line 140, in set_key
  File "Electrum-3.1.0-py3.6.egg/electrum/simple_config.py", line 149, in _set_key_in_user_config
  File "Electrum-3.1.0-py3.6.egg/electrum/simple_config.py", line 214, in save_user_config
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nikivi/.electrum/config'
[80725] Failed to execute script electrum
[electrumx-core.1209k.com] failed to connect [Errno 65] No route to host
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[Plugins] stopped
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[Network] stopping network
[Network] stopped
```

**Comment by bauerj** [comment]
Closing in favour of #4056.

**Comment by wzup** [comment]
Related
https://github.com/spesmilo/electrum/issues/5435
