### ISSUE TITLE
coins doesnt arrive 

### ISSUE THREAD

**Issue by YugoHack1996** [spesmilo/electrum#3271]
I bought before 3 days btc and they doesnt arrived yet.. 
Yesterday stayed there "parent unconfirmed"
At my history now there stays nothing , not even that coins are sending.  but when i look at blockchain there stays that i have a balance of the coins which i bought. 
but i cant see anything in electrum , why ?
and yes it is the correct btc adress , i've checked all

**Comment by Tomdub5** [comment]
I have a same issue.
I had 2 transactions more then 2 days and currently unconfirmed

**Comment by janhn** [comment]
Most likely the fee is too low for the current state of the network. Mempool has 150000+ unconfirmed transactions. If you've marked the transaction replaceable, you can try to increase the fee, but the fees are very high at the moment.

**Comment by Tomdub5** [comment]
How can I cancel the transaction?

**Comment by janhn** [comment]
@Tomdub5 If it's replacable, you could try to double spend the input (again, with a higher fee) to send the coins to yourself, and so have the original tx canceled. Not sure exactly how.

**Comment by ecdsa** [comment]
please do not open an issue for that.
you have to pay hight fees at the moment because the network is saturated
https://core.jochen-hoenicke.de/queue/#24h
