### ISSUE TITLE
Seed option grayed out

### ISSUE THREAD

**Issue by Dnnyslll** [spesmilo/electrum#3272]
![screen shot 2017-11-12 at 11 46 42 am](https://user-images.githubusercontent.com/33562987/32695139-2f09d95c-c79f-11e7-8c9c-60ddb75fbe99.png)

Hi team
my default wallet has  it's seed grayed out, is there anyway of retrieving it? my other wallets can access the seed.
Thanks
D

**Comment by ecdsa** [comment]
probably because you are using a 2FA wallet, or a watching-only wallet
