### ISSUE TITLE
false BC number and Bitcoins he dont sent 

### ISSUE THREAD

**Issue by baddog5436** [spesmilo/electrum#3273]
Please help me with the issue ;(

![unbenannt](https://user-images.githubusercontent.com/33594967/32697923-a0c39762-c79b-11e7-831a-4501fbc29d82.png)

**Comment by ecdsa** [comment]
I see no issue here. please explain

**Comment by baddog5436** [comment]
he sent the bitcoins not to my another wallet,this are 0,01240 BTC and it take more then 2 days and says " unconfirmed"

**Comment by baddog5436** [comment]
ecdsa,What do i wrong ? ;( 





![unbenannt](https://user-images.githubusercontent.com/33594967/32699323-e8113b84-c7b3-11e7-8547-2537653a5c88.png)

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
