### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by Arkanisbbc** [spesmilo/electrum#3274]
Sent 0.33485613 btc to the Bitrex exchange. Means did not reach, writes that the transaction is not confirmed. What to do?

**Comment by lzsaver** [comment]
[FAQ: My transaction has been unconfirmed for a long time. What can I do?](http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do)

**Comment by chadchen2017** [comment]
they stole your cash

**Comment by DanielBompart** [comment]
please help me a little of mBTC my email daniel.bompartr@gmail.com
