### ISSUE TITLE
Not enough funds (Win wallet v3.0.1 with 2fa)

### ISSUE THREAD

**Issue by mazzod** [spesmilo/electrum#3275]
Hi all,

I setted up another electrum wallet and I'm trying to send my btc from the old one to the new one, but when I put the coin amount on the "Amount" tab, the wallet always tell me "Not enough funds".
This's the initial situation:
![issue1](https://user-images.githubusercontent.com/20927620/32698708-18008994-c7aa-11e7-89f2-c811f0c03147.JPG)
And this's after I put all my coins on the amount cell:
![issue2](https://user-images.githubusercontent.com/20927620/32698710-31103358-c7aa-11e7-9749-0868d53f9723.JPG)

I can't understand this strange behaviour, this's the first time that I have the problem.

Regards

**Comment by SuBPaR42** [comment]
Just start/recover the new wallet with your seed (from the other/older install)- no need to send the funds.

**Comment by mazzod** [comment]
Hi @SuBPaR42 

thanks for your response. Unfotunatelly I need to have two separated wallet, and the old one need to be empty, I haven't point this out before.

**Comment by AbdussamadA** [comment]
enter a fee manually. you're not taking fees into account.

**Comment by SomberNight** [comment]
As @AbdussamadA says, this is probably due to fees.
