### ISSUE TITLE
help unconfirmed BTC 

### ISSUE THREAD

**Issue by baddog5436** [spesmilo/electrum#3277]
my bitcoins i want to send are unconfirmed still 2 day

![unbenannt](https://user-images.githubusercontent.com/33594967/32701647-cde8b518-c7d9-11e7-8895-c3bccd2e394f.png)

**Comment by SomberNight** [comment]
Hi. This is not the place to ask this kind of question.
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by adlererik** [comment]
Make sure you are using the newest Electrum. Right click on the stuck tx and use CPFP (Child Pays For Parent). Use the slider to pick the right fee. This tx will pay the fee of the one that got stuck.

**Comment by baddog5436** [comment]
but the option is not there


![unbenannt](https://user-images.githubusercontent.com/33594967/32702210-b8ef1b66-c7e3-11e7-8820-b4d0429ee36b.png)

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by DanielBompart** [comment]
please help me a little of mBTC my email daniel.bompartr@gmail.com
