### ISSUE TITLE
50hr no confirmation

### ISSUE THREAD

**Issue by chadchen2017** [spesmilo/electrum#3278]
i sent a electrum amount 50hrs ago and no confirmation. can someone please help me, i added a 15$
fee

https://www.blocktrail.com/BTC/tx/93fdc6125f406658d84d4e80da8e338e8e41fbeb7bc11630569d6cffb4378e68

**Comment by baddog5436** [comment]
i have the same problem please help

**Comment by chadchen2017** [comment]
if it does not confirm when do i get my btc back or is it gone for good

**Comment by baddog5436** [comment]
i think the bitcoins are 4ever gone ;( i have the same pr
![unbenannt](https://user-images.githubusercontent.com/33594967/32702338-fbebbaa8-c7e5-11e7-90e6-8004c4c9795c.png)
oblem

**Comment by ecdsa** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by chadchen2017** [comment]
Electrum is the worst wallet. Lol

**Comment by chaelbulatao** [comment]
Hello,

kindly help me to push may transaction, coz still un confirmed for almost 24 hours

BITCOIN TRANSACTION

https://www.blocktrail.com/BTC/tx/9100c4b1acf1ce1c1d5cf6e6f68ad836aec46abef19ac00d8c9959c199571a2e
