### ISSUE TITLE
Package electrum for debian

### ISSUE THREAD

**Issue by Engelberg** [spesmilo/electrum#3281]
One popular way to use electrum is via the Tails OS.  My understanding is that the Tails developers grab the latest Debian package of electrum to bundle in with each new release of Tails.  Tails currently is bundling an older version of Electrum that had several significant bugs, for example, the inability to sign a transaction without a live connection to the Internet (especially concerning for people who are using Tails to create an offline cold-storage wallet).  And now, Electrum 3.0.1 is required for segwit support.

Can we get a recent debian package of electrum so it can be included in Tails?

**Comment by AbdussamadA** [comment]
you should take this up with the maintainer of the electrum package for debian. 

alternatively here's a guide to using 2.9.3 on tails: https://www.reddit.com/r/Electrum/comments/78p9dz/electrum_in_running_in_tails_os_does_not/dovztij/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=Electrum

**Comment by Engelberg** [comment]
who is the maintainer? My searches haven't turned up anything about the process by which the packaging happens.

**Comment by SomberNight** [comment]
Debian testing has 2.9.3 at the moment: https://packages.debian.org/buster/electrum

**Comment by AbdussamadA** [comment]
`apt-cache show electrum` will tell you who the maintainer is

**Comment by ecdsa** [comment]
closing: out of scope here.
