### ISSUE TITLE
Electrum does not start

### ISSUE THREAD

**Issue by grandemestre** [spesmilo/electrum#3290]
I use Win10 64bit and am trying to start Electrum but it does not start. If windows is in safe mode it works, but not in normal mode. How could I solve this ?! Is there any log where I can get more information? No visual error occurs, just does not start.

**Comment by AbdussamadA** [comment]
This was [reported on the forum too](https://bitcointalk.org/index.php?topic=2395038.0). The portable version seems to be working for one user.

**Comment by grandemestre** [comment]
The error occurs with Electrum 3.0.1 and Electrum 3.0.2 do not know if it affects previous versions.

I tried: Standalone Executable and Windows Installer

**Comment by AbdussamadA** [comment]
try the portable version. it's different from the standalone one.

**Comment by lgfischer** [comment]
I'm also having problems running Electrum 3.0.2 on Win10 Pro 64bit. Like @grandemestre, nothing happens when I click on the shortcut created by the installer on my Desktop: no errors, no popup, nothing happens, like if I did not clicked on the shortcut. The same happens with the standalone and the portable versions of Electrum 3.0.2.

I tried running it as administrator, nothing happened too. Tried running from the command line to see if any message is printed, but it didn't helped. Tried the Windows Event Viewer, but could not find any relevant entry.

I did never tried Electrum before, this is my first try running this wallet.

**Comment by SomberNight** [comment]
What is the exact version of Windows where this occurs? E.g. [Version 10.0.15063]

**Comment by lgfischer** [comment]
Hi @SomberNight, I'm running on Windows 10 Pro Version 1703, Build SO 15063.726.

Today I've uninstalled Electrum 3.0.2 and installed for the first time Electrum 2.9.3, which worked without any problems. I did not tried Electrum 3.0 nor 3.0.1.

**Comment by gabrielpeixoto** [comment]
I'm having the same problem, nothing happens when I click on the shortcut or electrum.exe.

But it works when I run Electrum 3.0.2 using the [Python sources](https://download.electrum.org/3.0.2/Electrum-3.0.2.zip).
`python electrum`

**Comment by zenyattaBR** [comment]
Same issue here. Windows 10 64 bits.

When I try to use version 3.0 and beyond nothing happens, I click and the app does not launch. Version 2.9.3 works OK.

I tried to run the application as Administrator, but when I did that, Windows Defender showed a message saying that there was a malware. I think it is just a false positive, but there is something in the application that Windows is seeing as a threat and it is stopping the app.

**Comment by fernandovarella** [comment]
Same issue here. Windows 10 64 bits version  10.0.15063 - 15063

Electrum 2.8.3 opens normally, electrum 3.0.2 won't open. 

I checked in the system monitor and the 3.0.2 executable shows up with the 'finished' status

**Comment by SomberNight** [comment]
Any chance this is to do with ASLR as in https://github.com/spesmilo/electrum/issues/3319#issuecomment-348170094 ?

**Comment by SomberNight** [comment]
Lots have changed re the Windows build since this was opened. Closing.
