### ISSUE TITLE
Generate custom addresses

### ISSUE THREAD

**Issue by miranos** [spesmilo/electrum#3292]
Hi,

Where i can modify the code to get custom addresses please ?

I want my address begin with: Fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. (Same lenght as Bitcoin).

Give me a starting way please.

Thank's.

**Comment by SomberNight** [comment]
Do you mean to change the network constants to create an altcoin, or do you want a vanity address for Bitcoin? Even with a vanity address, the first character can't be an "F". Support for altcoins is not provided here.

**Comment by miranos** [comment]
Not a vanity address but i need to do it for a another currency than Bitcoin, but for this, i just need to generate another type of addresses that begin with F.

Like others that forked electrum for dogecoin, namecoin, novacoin etc.

If you need more information please let me know.

Thank's.
