### ISSUE TITLE
Wrong symbol on balance

### ISSUE THREAD

**Issue by marck0z** [spesmilo/electrum#3294]
I'm using Electrum 3.0.1 on Linux, my BTC balance shows wrong characters at the beginning

**Comment by SomberNight** [comment]
What is your system locale? Is it English?
Also, what did you need to do to get that symbol to change? (between the two screenshots)

**Comment by marck0z** [comment]
My system locale is english. I don't do anything special to change that symbol, sometimes it changes when interacting with the menus, sometimes it doesn't. I have seen like 4 different symbols but the most common one is [.

I discovered that this only happens when I have BTS as my base unit on Tools -> Preferences -> Appearance. With mBTC and bits, the amount is correct.

Maybe this has something to do with the way amounts are showed too, they used to be +0.3494 etc. but now they show up like this:
![3](https://user-images.githubusercontent.com/15240827/32759602-d3a02582-c8af-11e7-8883-9f5fcc122df5.png)

**Comment by SomberNight** [comment]
Some new info on this from user pm7 on IRC:
![](https://i.imgur.com/9aUS1V5.png)
