### ISSUE TITLE
Seed from 1.9.7 can't be retrieved

### ISSUE THREAD

**Issue by slawdog** [spesmilo/electrum#3296]
Hello.

I have a wallet with seed from version 1.9.7 and I cannot find a version which can open this seed. The original machine is an Windows XP, and the old version wallet still functions, but does not connect online so transfers cannot occur. Trying to install 1.9.7 onto other computers will not open the wallet. Any help would be appreciated.

**Comment by SomberNight** [comment]
What kind of seed is it? Have you tried restoring from it in 3.0.x?

**Comment by slawdog** [comment]
Ohp, sorry, I was just a freakin' idiot and wrote down a word incorrectly. However, it's still the case that the app will not launch on version 1.9.7 or 1.9.8.

**Comment by SomberNight** [comment]
Those versions are several years old; it's not worth it to troubleshoot at this point. You should update (start using 3.0.x), or explain why you need to use those specific versions.
