### ISSUE TITLE
Offline signing with hardware wallet

### ISSUE THREAD

**Issue by badikumar** [spesmilo/electrum#3302]
Using Electrum 3.0.2

### **Machine Setup**

- I have two machines. One offline and one online. 
- Online machine has a watch-only standard wallet I created with 1 xpub.
- The 1 xpub was generated by a standard wallet on the offline computer using a Ledger device (Nano S).

### **Creating a transaction (online computer)**

1. I create a transaction on the online computer 
2. Copy the transaction onto a file.
3. Transfer this file over to the offline computer

### **Signing a transaction (offline computer)**

1. Load the transaction created from the previous step
2. Click on "Sign"
3. Electrum says "Signing transaction". The prompt to confirm never appears on the Ledger device. After a while, it says "Server not reachable" 

### **Code**

Looking at the code, it looks like the `add_hw_info` in `wallet.py` is being called by `sign_transaction` if `isinstance(k, Hardware_KeyStore)`. That means you **have** to be online to sign a transaction using the Ledger device which defeats the purpose of a cold storage device.

Please advise.

**Comment by ecdsa** [comment]
@btchip could it be related to the websocket thing?

**Comment by btchip** [comment]
no, this shouldn't be used with a Nano S, only with a Nano / HW.1. Not sure what add_hw_info is, doesn't ring a bell

**Comment by badikumar** [comment]
@btchip add_hw_info is in wallet.py code. It looks that code wants to get online before signing

**Comment by ecdsa** [comment]
I see, it needs to request the input transactions in order to verify the fee.
that is not needed anymore for segwit wallets, and we can remove that.
for older wallets we are not going to fix that

**Comment by badikumar** [comment]
What does old wallet mean? Non-segwit or wallets created with older version of Electrum?

**Comment by badikumar** [comment]
I see you've clarified that in your message.

But what I don't understand is why does it require the previous tx if it is hardware keystore and not if it isnt?

**Comment by badikumar** [comment]
What if I have a mult-sig wallet? Will this be solved for that case too?

**Comment by SomberNight** [comment]
I've implemented this for Trezor in https://github.com/spesmilo/electrum/pull/4005.

-----

I have had a look at Ledger as well, but looking at the way how we pass amounts to btchip-python, and then to the ledger fw, they don't seem to be optional for segwit. Or at least it's very unclear how we can avoid needing to pass them.

https://github.com/spesmilo/electrum/blob/7816edc3428f7148de1b2c4b567408b68c1d25cb/plugins/ledger/ledger.py#L336
https://github.com/spesmilo/electrum/blob/7816edc3428f7148de1b2c4b567408b68c1d25cb/plugins/ledger/ledger.py#L374-L381
https://github.com/spesmilo/electrum/blob/7816edc3428f7148de1b2c4b567408b68c1d25cb/plugins/ledger/ledger.py#L400-L402
https://github.com/LedgerHQ/btchip-python/blob/eb57d503962df367108fd7f9feaadceb0369318e/btchip/btchip.py#L202
https://github.com/LedgerHQ/btchip-python/blob/eb57d503962df367108fd7f9feaadceb0369318e/btchip/btchip.py#L225
https://github.com/LedgerHQ/btchip-python/blob/eb57d503962df367108fd7f9feaadceb0369318e/btchip/btchip.py#L241
https://github.com/LedgerHQ/btchip-python/blob/eb57d503962df367108fd7f9feaadceb0369318e/btchip/btchip.py#L260-L262

**Comment by SomberNight** [comment]
Note: it seems the digital bitbox does not need the previous transactions when signing (not just for segwit but for legacy either); so offline signing works there.

**Comment by SomberNight** [comment]
Recap:
- Trezor:
    - legacy does not work, no plan to implement support
    - segwit works
- KeepKey:
    - legacy does not work, no plan to implement support
    - segwit: keepkey itself does not support segwit
- Ledger:
    - legacy does not work, no plan to implement support
    - segwit: does not work, would like to implement, but unclear how
- Digital Bitbox:
    - legacy works (because dbb does not want previous transactions)
    - segwit works

Multisig:
there should be no difference AFAICT now, so see above, but note that segwit multisig hardware (and bip39) wallets are currently disabled due to there not being a standard for what derivation path to use for keys

**Comment by SomberNight** [comment]
I now had another look and turns out it was not hard for ledger either. Oops. :)

**Comment by SomberNight** [comment]
@engenegr You need to explain your setup because otherwise it's hard to help.
What hardware wallet are you using? What kind of wallet do you have? Does it have segwit addresses?
And also, what kind of online wallet do you have (because currently it only works if it's an xpub, not with imported addresses)?

**Comment by engenegr** [comment]
@SomberNight 
Sorry,

I'm testing both Ledger and Trezor. So multisig is Electrum, Trezor, Ledger (2-of-3).

No, I'm dealing now with Legacy. I know problem with them.

Online part is Electrum which has all xpubs imported as watch-only wallet.

**Comment by SomberNight** [comment]
Ok, yes, then you understand the situation now I guess.
To sign a legacy transaction, you need the parent transactions, but the offline wallet does not have them.

**Comment by engenegr** [comment]
@SomberNight 
The problem appeared only in Electrum-3.1.3 binaries from the site.
The fresh pulled sources work fine, I mean Electrum imports all transactions from hot side correctly and allows to sign offline.

Sorry for the disturbance.
