### ISSUE TITLE
Electrum Client 3.0.2 Connected Node Limit

### ISSUE THREAD

**Issue by all-encrypted** [spesmilo/electrum#3307]
Is there a max number of permitted Nodes that the client/server can connect to at one time? I usually see 10 but installing 3.0.2 on a new machine for the 1st time i noticed 11 nodes connected in network tab for a brief period then back to 10. Is this something out of the ordinary?

Thank you for any clarification.

**Comment by ecdsa** [comment]
thats normal. it depends whether your history server is in the random list or not
