### ISSUE TITLE
export electrum wallet to btg core

### ISSUE THREAD

**Issue by scgbckbone** [spesmilo/electrum#3314]
Does electrum provides this option ? BTG core works with '.dat' format.

**Comment by ecdsa** [comment]
no

**Comment by scgbckbone** [comment]
Is there any alternative way?

**Comment by ecdsa** [comment]
export private keys

**Comment by scgbckbone** [comment]
I went over several 'how-tos' on the net and feel like my understanding of the process is low. Can you, please, be more verbose (-vv) and describe the process, How would I export my private key from electrum so that it is usable in BTG core wallet.

**Comment by Raulo** [comment]
@scgbckbone,

This is a bug tracker not a support line. Why do you think a person that maintains Electrum and does a lot of important stuff should spend time to explain to you something completely unrelated to Electrum? 

If you ask nicely on reddit or some Bitcoin forum, you may get a reply. Or better, learn about private/public keys, addresses and all the Bitcoin intrinsics and do it yourself.
