### ISSUE TITLE
Electrum 3: No traceback in console

### ISSUE THREAD

**Issue by nonsequitur** [spesmilo/electrum#3315]
To reproduce:
enter `a` in console and press return.
Actual output (Electrum 3.0.2):
```
Traceback (most recent call last):
```
Expected output (from previous versions): 
```
Traceback (most recent call last):
NameError: name 'a' is not defined
```

**Comment by SomberNight** [comment]
I confirm this on Windows 10.
Electrum 2.9.3 prints full trace; 3.0.2 only prints first line.

However, on Debian 9, I get the full trace with both 2.9.3 and 3.0.2.

**Comment by helpau** [comment]
Reproduced on Windows 10, Electrum 4.4.6
