### ISSUE TITLE
Electrum 3.0.2 unable to start (0xc0000005). (mandatory ASLR, Windows setting)

### ISSUE THREAD

**Issue by robdevops** [spesmilo/electrum#3319]
I am unable to start Electrum 3.0 or 3.0.1 or 3.0.2 on Windows 10 Pro 64-bit.
Electrum 2.9.3 works.
I have verified the PGP signature of 3.x and the .exe is good.

The error is:

> ---------------------------
> electrum-3.0.2.exe - Application Error
> ---------------------------
> The application was unable to start correctly (0xc0000005). Click OK to close the application. 
> ---------------------------
> OK   
> ---------------------------

**Comment by SomberNight** [comment]
Are any other programs giving you this error, or is it only Electrum 3.0.x?

I assume you tried to look up this error in a search engine, but if not:
- https://us.battle.net/forums/en/hearthstone/topic/20742904659
- http://www.tomshardware.co.uk/answers/id-1770644/0xc0000005-application-errors.html
- https://answers.microsoft.com/en-us/windows/forum/all/the-application-is-unable-to-start-correctly/bbb9c037-77b3-4fae-93b9-ded70f7f9a17?auth=1
- https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/win-10-0xc0000005-for-most-progs/fcfd4b51-9cca-4d0c-8327-a9d8cc348753

If it's only Electrum giving you the error, maybe try disabling your antivirus temporarily and see if that fixes it (as per the first URL).

**Comment by solikeumyeah** [comment]
Thank you for your reply. I've just tried:

- "Run as" -> Administrator on Electrum 3.0.2. It does not open but no error message is displayed. This might relate to #3219 or #3290.
- Setting Windows compatibility mode (XP) on the Electrum 3.0.2 exe. It does not open but no error message is displayed. This might relate to #3219 or #3290.
- Launching other apps I have installed, including Chrome, Lightroom, GIMP, Steam, KeePass 2 and others. All working.
- Electrum 2.9.2. Working, just like 2.9.3.

I still get error 0xc0000005 on Electrum 3.0.2 after:
- Rebooting 
- Disabling Windows Defender real-time protection (I don't use third party AV).
- Setting Windows compatibility mode (Windows Vista, Windows 7).
- Logging in under a different user account (administrator).
- Logging in under a different user account (user).
- Moving Electrum exe to another filesystem and granting 'everyone' 'full control' of it.

And here's the corresponding [event log entry](https://github.com/spesmilo/electrum/files/1482640/event.log.txt).


I should have mentioned, my Windows 10 version is 1709, build 16299.64. It would be good if someone else can confirm Electrum 3.x is working on this build. 

Also, does Electrum 3.x have any new runtme dependencies or was it built with a new dev environment? 



Thanks

**Comment by SomberNight** [comment]
> Also, does Electrum 3.x have any new runtme dependencies or was it built with a new dev environment?

Yes, well, a lot changed between 2.9.x and 3.0.x.
The Windows binaries are now built using pyinstaller 3 (instead of 2), and using python 3.5 (instead of 2.7). The new Windows binaries depend on UCRT (win10 visual cpp runtime); see https://github.com/spesmilo/electrum/issues/3171

It would indeed be nice if someone could test with that build of Windows 10.

**Comment by solikeumyeah** [comment]
> I should have mentioned, my Windows 10 version is 1709, build 16299.64. It would be good if someone else can confirm Electrum 3.x is working on this build.

Ok, I found another system with the same Windows build, and Electrum 3.0.2 works there. 

I'm primarily suspecting a missing dependency, as my Windows install is only a few weeks old. UCRT, from what I can see, should be built-in and covered by Windows Update though. I had a quick look at Electrum 2.x vs 3.x in Microsoft Dependency Walker, but I'm not very experienced with this tool. The first level of dependencies looked the same. I can look at it again tomorrow.

**Comment by solikeumyeah** [comment]
> I had a quick look at Electrum 2.x vs 3.x in Microsoft Dependency Walker, but I'm not very experienced with this tool. The first level of dependencies looked the same. I can look at it again tomorrow.

I did a [Dependency Walker export](https://github.com/spesmilo/electrum/files/1484210/electrum-3.0.2.notworking.txt) ("Text with Import/Export Lists") on both systems and diffed the results. All the same DLLs are present and they have the same checksums.

At this point, I'm not interested in running Electrum 3.x but I'm available to help debug if this is deemed a wider problem affecting others.

**Comment by entity279** [comment]
Ițm getting the same error for electrum 3.0.2 but also for the jaxx desktop wallet

**Comment by munichhilton** [comment]
This is caused by Windows Address Space Layout Randomization, ASLR
https://blogs.technet.microsoft.com/srd/2017/11/21/clarifying-the-behavior-of-mandatory-aslr/

If you fix "the windows setting" to enforce ASLR for all processes Electrum crashes win 0x5...

**Comment by entity279** [comment]
Thanks, excellent point. I was toying with these setting earlier and got surprized how ASLR is off by default.

I was thinking 'who on earth would make her program depend on various memory positions?' , enabled it and forgot. I was wrong somehow with my rethoric question

**Comment by SomberNight** [comment]
@munichhilton is correct. I was able to reproduce the issue when enabling mandatory ASLR using EMET on Windows 10.0.15063.

**Comment by solikeumyeah** [comment]
I can confirm disabling Mandatory ASLR via Windows Defender Security Center allows Electrum 3.x to run. 
![image](https://user-images.githubusercontent.com/9821269/34089826-fc0a1736-e406-11e7-8ee5-92f893b208b5.png)
However, I don't believe I have toyed with this setting, so it may have been enforced by something else.

**Comment by pioruns** [comment]
Same here, default system settings and error as above.

**Comment by SomberNight** [comment]
I've just tested with Electrum 4.2.0 and can no longer reproduce.
I can reproduce with Electrum 3.0.2.

Not sure when this got fixed though.
