### ISSUE TITLE
3.0.2 release tarball has no "packages" directory

### ISSUE THREAD

**Issue by teran-mckinney** [spesmilo/electrum#3323]
Hi,

README says the following:

> If you downloaded the official package (tar.gz), you can run Electrum from its root directory, without installing it on your system; all the python dependencies are included in the 'packages' directory. To run Electrum from its root directory, just do:

However, I don't see a "packages" directory in 3.0.2. And ./electrum complains about the lack of a dns module.

Thank you,

Teran

**Comment by ecdsa** [comment]
you did not download the officiaal tar.gz

**Comment by teran-mckinney** [comment]
I assumed that the Github releases would be the "official" packages. https://download.electrum.org/3.0.2/Electrum-3.0.2.tar.gz seems to have it. Thanks!
