### ISSUE TITLE
Searching an old address within Electrum

### ISSUE THREAD

**Issue by Annychenka** [spesmilo/electrum#3324]
I have bought BTC with Electrum, I saw a pending request with my address. Then this address disappeared, I can see it only in a blockchain with a successfully done transaction. How can I find this address in Electrum? The history is empty, moreover  I have 0 BTC in the wallet. Could someone advise me? I'm a newbie here.

**Comment by ecdsa** [comment]
in the View menu,  display the addresses tab

**Comment by Annychenka** [comment]
Thanks, for sure, but it is absent in that View menu. I couldn't find it between addresses. How to find an old address in the Electtrum?

**Comment by sunnyville01** [comment]
You can try increasing the [gap limit](http://docs.electrum.org/en/latest/faq.html#gap-limit), or keep [generating new addresses](http://docs.electrum.org/en/latest/faq.html#how-can-i-pre-generate-new-addresses) until you find the one your looking for.

Hope this helps.

**Comment by Annychenka** [comment]
Thank you so much, sounds good.
