### ISSUE TITLE
Electrum 3.0.2 on linux stuck synchronizing

### ISSUE THREAD

**Issue by gaboto83** [spesmilo/electrum#3327]
With some server it doesn't connect. But with some others, it keeps synchronizing and never ends showing the wallet.

**Comment by AbdussamadA** [comment]
if it's a large wallet then synchronizing is going to take many minutes. if your wallet has thousands of addresses then it's time to think of moving to a new wallet. you can begin the process of creating a new wallet via file > new/restore
