### ISSUE TITLE
Transaction BCC to BTC wallet

### ISSUE THREAD

**Issue by Po3cilot** [spesmilo/electrum#3329]
Hello,

Last week (Nov 11, 2017 7:56:42 PM) I moved BCC from exchange to my BTC wallet. As you think I didn't received these coins. Can you back this transaction to exchange? Can I give you transaction id or something else to verification this case?

I'll very grateful for your help.

**Comment by dabura667** [comment]
BTC wallets can not manage BCC.

Electrum is a BTC wallet. So it can not manage BCC.

**Comment by Po3cilot** [comment]
I understand it. Only what I want is back my transaction because it was forwarding to Electrum so they can return it to me.

**Comment by ecdsa** [comment]
no we cannot

**Comment by SomberNight** [comment]
If you have the private keys/seed for the address, you should be able to use Electron Cash (fork of Electrum for BCC) to access these coins. Note that doing this might compromise the security of your Electrum wallet.
