### ISSUE TITLE
Trezor pin code gives string overflow.

### ISSUE THREAD

**Issue by MichaelBrimer** [spesmilo/electrum#3331]
electrum-3.0.2
Trezor bridge
Get fine connection to Trezor.
During entering I get message "strong"
My pincode is long.
When  I am done with the code I get the Error:  string owerflow

**Comment by SomberNight** [comment]
How long is "long"? And you mean the numerical PIN, not the passphrase, right?

**Comment by SomberNight** [comment]
See https://github.com/spesmilo/electrum/issues/4122
The PIN code can only be up to 9 characters long but we had not been enforcing this before.
