### ISSUE TITLE
Electrum crashes when confirming/denying transactions on the Ledger nano s

### ISSUE THREAD

**Issue by Highflyer108** [spesmilo/electrum#3332]
On 3.0.2 and it always crashes.

**Comment by jeikoo** [comment]
Confirm with 3.0.2. No crash but dialog becomes unresponsive and has to be killed.

Nano S firmware 1.3.1 and Bitcoin app 1.1.10. Windows 10/64. Electrum full install and standalone, no difference.

**Comment by Highflyer108** [comment]
Yeah sorry it doesn’t CTD I meant it just becomes unresponsive.

**Comment by SomberNight** [comment]
duplicate of https://github.com/spesmilo/electrum/issues/3264

**Comment by ecdsa** [comment]
ok, closing
