### ISSUE TITLE
Fake Electrum website in google search

### ISSUE THREAD

**Issue by sasatefa2009** [spesmilo/electrum#3333]
I found this fake website while searching google for electrum and it's also a paid ad

I which if know how to report it.

![electrum fake](https://user-images.githubusercontent.com/22708418/32994298-be87c89a-cd6d-11e7-8468-b6b87ef5ef05.jpg)

**Comment by kamk** [comment]
You can report sites such as this to https://safebrowsing.google.com/safebrowsing/report_phish/

**Comment by Optimizingroman** [comment]
Is it possible to have false verification when using correct key in openPGP but fake .asc file and .dmg file?
