### ISSUE TITLE
How to install dependencies on Mac?

### ISSUE THREAD

**Issue by quantumproducer** [spesmilo/electrum#3336]
~/electrum/python electrum
Traceback (most recent call last):
  File "electrum", line 85, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/Users/quantum/electrum/lib/__init__.py", line 2, in <module>
    from .util import format_satoshis, print_msg, print_error, set_verbosity
  File "/Users/quantum/electrum/lib/util.py", line 35, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request]

how do I install these?

I tried to install Python QT UI on mac and couldn't find a working solution, all the answers were old.

**Comment by bauerj** [comment]
To install it on your system, run: `sudo python3 setup.py install`.

**Comment by quantumproducer** [comment]
@bauerj I ran that, successfully. Then:

~/electrum/./electrum
Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/usr/local/lib/python2.7/site-packages:"
     You should `unset PYTHONPATH` to fix this.
~/electrum/unset PYTHONPATH
~/electrum/./electrum
Error: Could not import PyQt5 on Linux systems, you may try 'sudo apt-get install python3-pyqt5'
~/electrum/

**Comment by bauerj** [comment]
Please follow the instructions on the download page:

https://electrum.org/#download


- Install Homebrew
- Install dependencies 'brew install qt5 pyqt5 gettext'
- Install Electrum-3.0.2.zip 
- In the electrum directory, run 'python3 electrum'

**Comment by nitinsurana** [comment]
@quantumproducer were you able to get it working ? I've been trying for last couple of days, but no luck. 
I tried with Electrum-3.0.2.zip and 3.0.5.zip but no luck.
FYI - I'm using python 3.5.2
