### ISSUE TITLE
Use Electrum as Python library for talking with Electrum daemon

### ISSUE THREAD

**Issue by teran-mckinney** [spesmilo/electrum#3338]
Hi,

Are there any examples for importing electrum as  Python library and using the calls natively in Python? getaddressbalance(), etc.

I see surprisingly little on the subject and am wondering if I'm missing an examples folder somewhere. Would be really handy to do this.

Thank you,

Teran

**Comment by teran-mckinney** [comment]
Looks like jsonrpc is a good way to interact with the daemon.

**Comment by ecdsa** [comment]
look in the scripts directory
