### ISSUE TITLE
Problem with Google authentification

### ISSUE THREAD

**Issue by Po5itive** [spesmilo/electrum#3340]
Dear Sirs.

Please advise with following issue:
I have the account in electrum with BTC. 
Account requires Google authentification (Google Authenticator) for each payment. Currently I've lost all data on my mobile phone, including google Authenticator customized for my Electrum. Now I can't proceed with any transaction in Electrum without this code. 

Please advise Is it possible to solve this issue? Looking forward to your reply.

**Comment by SomberNight** [comment]
Restore your wallet from your seed words, that you have backed up when creating it originally. You will be offered to keep 2FA enabled, and shown the QR code again.

**Comment by Po5itive** [comment]
Google Authenticator have no such option of using seed words. I didn't have the opportunity to use them when I installed it last name the same as now(. In Electrum (Desktop version) I have all information and key, but I can't make any transaction with code in Authenticator.

**Comment by SomberNight** [comment]
No, I mean, using desktop Electrum, restore the wallet from seed words. It will offer you to show the QR code again.

**Comment by Po5itive** [comment]
ah, ok, I will try that. Thank you very much
