### ISSUE TITLE
Cannot use payto without a loaded wallet when providing private key

### ISSUE THREAD

**Issue by teran-mckinney** [spesmilo/electrum#3345]
It seems like I should be able to use `payto` without a wallet in electrum, but I cannot.

```
$ electrum payto public_destination_address -F mypublic:myprivate_in_wif_format 0.0001
Error: Wallet file not found.
Type 'electrum create' to create a new wallet, or provide a path to a wallet with the -w option
```

`payto()` in commands.py has a command decorator of 'wp'. If I drop that, the next error I have is from electrum being unable to resolve the address as it's trying to open a wallet.

I'd like to run electrum as a local daemon without an electrum wallet and use my own as I provide.

Thank you for your time.

-Teran

**Comment by ariard** [comment]
Electrum need a wallet open for getting infos like spendable coins, balance, etc so u can't drop random address on the fly like you try

**Comment by ecdsa** [comment]
"payto" is a wallet command, that picks coins and sends change to a change address.
you need to use "sweep" in order to achieve what you want.

"sweep" also requires a wallet to be loaded, but that is something we can fix; it should not require one

**Comment by ecdsa** [comment]
so, the documentation is wrong about passing a private key.

**Comment by teran-mckinney** [comment]
Ok, thank you. I will stick with using electrum for getaddressunspents, gettransaction, getaddressbalance and pushtx.

I have that working now with walkingliberty: https://github.com/teran-mckinney/walkingliberty-python/commit/ec8a8156f44389b45855d2e6026f00768cfb97bd
