### ISSUE TITLE
Fee slider is calculating fee lower than specified

### ISSUE THREAD

**Issue by NiExTy** [spesmilo/electrum#3347]
For example set slider to 100 sat/byte and sign transaction (1 input, 2 outputs):
> Size: 168 bytes
> Fee: 0.00014236 (84 sat/byte)

Large 16 sat/byte difference.
Expected result - never lower than specified (at least 0.00016800 in this example).

Electrum 3.0.2
P2SH-P2WPKH BIP49 wallet

**Comment by ecdsa** [comment]
I can reproduce it. Transaction.estimated_input_size() should return the virtual size (including witness)
