### ISSUE TITLE
Feature request: add an option to hide your balance

### ISSUE THREAD

**Issue by someone235** [spesmilo/electrum#3350]
Whenever I show someone my QR code in the mobile application, I have to show them my balance as well, because the balance is always written in top of the screen. This is a bit problematic for me, because I don't want to disclose this information.
This is why I suggest to remove the balance from the top of the screen, or at least to add an option to hide it.

**Comment by ecdsa** [comment]
actually, I was planning to do exactly that

**Comment by someone235** [comment]
Cool! I'm glad to hear it
