### ISSUE TITLE
Sign Electrum Windows executable

### ISSUE THREAD

**Issue by yorickdowne** [spesmilo/electrum#3355]
This is an enhancement request. To protect against Electrum impostors (we've seen a few already) and to avoid Windows SmartScreen warnings, sign the Electrum executable. The most affordable offer I could find was http://codesigning.ksoftware.net/ at 67 bucks / year.

I understand that even that amount may be prohibitive to the devs. If you were to rattle a tin for it (some form of crowd funding), I imagine you'd get donations sufficient for a 4-year cert. I'd certainly be happy to chip in.

**Comment by EagleTM** [comment]
We're considering code sigining. We wanted to try Comodo but there were severe issues getting the certficate generated, so it might be good to use a different vendor which does not actually use the browser to generate important certs

**Comment by ignus2** [comment]
K Software actually uses Comodo, but at a discount (they have a deal with Comodo afaik). It's standard practice to obtain the cert through the browser, what's the problem with that (is it the key generation process being done by the browser)?
But I agree, the installer and electrum executable most definitely has to be signed, checking the PGP sig manually is a major pain in the rear.

**Comment by bauerj** [comment]
> It's standard practice to obtain the cert through the browser, what's the problem with that (is it the key generation process being done by the browser)?

For a sufficient level of paranoia, the private key should never be on an online machine. A lot of people trust a lot of money to Electrum so the signing key should be as secure as possible.

**Comment by SomberNight** [comment]
Note: this is work in progress, see e.g. https://github.com/spesmilo/electrum/pull/3846
