### ISSUE TITLE
Minor UI issue: Can't "spend from" receive & change addresses at same time

### ISSUE THREAD

**Issue by eli-collins** [spesmilo/electrum#3356]
Under the new 3.0.2 ui, you can't see "receive" and "change" addresses at the same time, making it impossible to select a group of "spend from" addresses that include both types at once. 

The 2.x UI displayed this as a tree view, allowing picking a mixture.  Maybe 3.0.3 could add an "all" option to the "receive/change" filter at the top, allowing this ability again?

**Comment by SomberNight** [comment]
Note that you can probably achieve what you want using the `Coins` tab.
