### ISSUE TITLE
electrum 3.0.2 Windows testnet Fatal Error

### ISSUE THREAD

**Issue by wessjan** [spesmilo/electrum#3357]
When starting electrum on Win7/64 with --testnet, after a few seconds a Pop-up windows with title "Fatal Error!" and the message "Failed to execute script electrum" comes up, with only an "OK" button.

When using with "--offline" everything worked fine, but obviously with out access to the the testnet. I can't find any log or error report.

Running electrum without --testnet also works fine (as far as I can see, but I don't have made any transaction until now, but as I see, that I'm connected to 10 hosts).

Jan

**Comment by SomberNight** [comment]
duplicate of #3321

Should be fixed in next minor release.

**Comment by wessjan** [comment]
have not seen that, Thanks for your help.
