### ISSUE TITLE
Bugs with tor-connection and with console

### ISSUE THREAD

**Issue by Annychenka** [spesmilo/electrum#3358]
I can see my transaction in blockchain.info. I upgraded the wallet to the latest - 3.0.2. Nothing in the history or in the used addresses. I bought some BTC on the 13 of November 2017, my wallet has connected to the network, but I still don't have my BTC in the wallet. Moreover, there are 2 bugs. In meanwhile I'm trying to use a wallet through the tor, my wallet is disconnected (I waited for a long time, believe me) If I choose an option "select the server automatically" everything would work and connected to the network.  Another bug - command console. It works a bit with Fedora OS but doesn't work with Windows system. I presume it must show me history, but the console doesn't. In any of systems.
How can I find my transaction in the wallet in while the history is empty and no certain mentioned address among all addresses?

**Comment by SomberNight** [comment]
> my wallet has connected to the network, but I still don't have my BTC in the wallet
> Nothing in the history or in the used addresses

Do you have the expected addresses in the wallet? (`Addresses` tab)

> history is empty and no certain mentioned address among all addresses

So I guess you don't. Then this is unrelated from connection/network issues.

It's hard to tell more going from just the details you gave, which is probably why no one replied for so long -- sorry for that.

Regarding the Tor thing you mention, it sounds like there was just a single server the client with Tor could not connect to, and as soon as it tried to connect to another server, it worked.

Regarding the "command console" not working, not sure what you mean. Is it the `Console` tab in Qt, or using Electrum with CLI? CLI is known not to work on Windows with the release builds (it works when running from source).

**Comment by Platinumwrist** [comment]
I have unused addresses in my Electrum wallet how do I use them need help getting I the loop everything say it's functional thanks in advance
