### ISSUE TITLE
Feature request: make text in the stausbar selectable

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#3360]
The status bar (when enabled) contains a lot of useful information (full balance, dollar worth, etc.). If one were to use that information for other purposes, it would be helpful to be able to select and copy them.

**Comment by KibbledJiveElkZoo** [comment]
This is a feature I would find useful.

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/pull/3435 implements this; hence closing.
