### ISSUE TITLE
Feature request: Allow users to input sat/byte instead/along with the fee slider

### ISSUE THREAD

**Issue by ejose19** [spesmilo/electrum#3365]
The current slider is very unpredecible if you're using dynamic fees, as servers tends to over estimate the fees to get the confirmation on a decent time, and the non dynamic fee is a bit unflexible as the intervals cannot be change.

With a single input for the custom sat/byte, the problem is easily solved by letting users select the number that's most appropiate for their needs.

Since this feature requires having knowledge about the current fees, you can allow this change in Tools -> Preferences -> Fees having a checkbox for "Allow sat/byte input" so new users aren't affected.

**Comment by KibbledJiveElkZoo** [comment]
I would also like the ability to enter a custom fee in this way.

**Comment by ejose19** [comment]
Will this feature be implemented in the client?

**Comment by ecdsa** [comment]
yes
