### ISSUE TITLE
Not able to "create keystore from a master key" in windows

### ISSUE THREAD

**Issue by nickgust** [spesmilo/electrum#3368]
Hi there, 
I have followed the instructions in this video https://www.youtube.com/watch?v=LaijbTcxsv8 to import the private key from Multibit to Electrum. When I get to the "create keystore from a master key" step in the wizard, the "next" button never becomes active. I have no reason to think I have not put in the correct type of key, although I assume you guys are doing some checking before enabling the button maybe. 

The version of Electrum I am running is 3.0.2. Thanks in advance for any light you can shine on this.

**Comment by SomberNight** [comment]
If you have single private keys, as in the video, those no longer go into a standard wallet, rather an "imported wallet". Instead of clicking `Standard wallet` in the install wizard, choose `Import Bitcoin addresses or private keys`. This was changed around 3.0.0.

**Comment by nickgust** [comment]
Sweet. That worked. Many thanks for the help SomberNight.
