### ISSUE TITLE
Electrum 3.0.2 doesn't start at Win 7 x64

### ISSUE THREAD

**Issue by Psychosynthesis** [spesmilo/electrum#3376]
I try a portable version, try a standalone exe, and finely try the install... so they all have similar error:

"The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

And, yes - i have an administrator rights.

Best regards.

**Comment by SomberNight** [comment]
There's a note on the [website](https://electrum.org/#download) regarding this:
```
Note: Some old versions of Windows might need to install the KB2999226 Windows update.
```

**Comment by Psychosynthesis** [comment]
Seriously? How about the very concept of "standalone"?

**Comment by bauerj** [comment]
Well, you still need an Operating System. In this case one that's not outdated. I don't think that contradicts the term "standalone".

**Comment by Psychosynthesis** [comment]
Well, your argument is appropriate. However, as far as I understand, in this case the update is necessary only to support the transition to a new SDK in the development of the application.

The question is: did this new framework really need?

**Comment by bauerj** [comment]
The update is needed to run a recent version of Python. We don't necessarily need to use it but it enables us to use new features.

**Comment by Psychosynthesis** [comment]
How about to first get rid of all the bugs in the old features?

**Comment by bauerj** [comment]
Thanks for that suggestion. Do you have any specific bug in mind?

**Comment by Psychosynthesis** [comment]
As I can see, you already have at least 2 hundred: https://github.com/spesmilo/electrum/issues
