### ISSUE TITLE
Best way to run electrum scripts standalone?

### ISSUE THREAD

**Issue by Ericxgao** [spesmilo/electrum#3378]
Just curious if there was an established way to run electrum scripts on their own without needing to run the script in the command line.

I currently have a wallet setup like:

    storage = WalletStorage("./central_wallet")
    wallet = Wallet(storage)
    network = Network()
    network.start()
    wallet.start_threads(network)
    wallet.synchronize()
    wallet.wait_until_synchronized()
    print(wallet.get_balance())

This seems to work as I've mostly just been copying the initialization code from electrum.py - just curious if this was redundant or if there was a better way to do this as I don't want to miss any steps.

**Comment by dabura667** [comment]
https://github.com/spesmilo/electrum/tree/master/scripts

Check these for some hints at ways to make new scripts.
