### ISSUE TITLE
I'm getting "Invalid password" and there's nothing I can do about it

### ISSUE THREAD

**Issue by igalt** [spesmilo/electrum#3382]
Hi, I just set up my wallet a few days ago and I've written down my password.
When I opened Electrum again on my windows 10 machine I'm getting "invalid password" and there's no restore option... I've reinstalled Electrum and it still the same, I only get this screen:
![image](https://user-images.githubusercontent.com/3851970/33241709-2ded1816-d2d2-11e7-9425-806ecb8d9d42.png)

I can't see how I'm supposed to open a new wallet using my seed.
Any suggestions?

**Comment by ecdsa** [comment]
you forgot your password. choose a different filename and restore from there.
