### ISSUE TITLE
Electrum stuck Synchronizing.

### ISSUE THREAD

**Issue by HelpMePlease321** [spesmilo/electrum#3383]
Hey everyone. I recently sent a small amount of bitcoins to my electrum wallet and after that It has been just stuck saying "Synchronizing". Its been over 12 hours and it still remains the same.

Anyone ever experience this? Please share and help with any info you have. I do not know much about computers so please do be patient with me. 

Thanks.

**Comment by AbdussamadA** [comment]
See this: https://bitcoinelectrum.com/frequently-asked-questions/#electrum-is-stuck-at-synchronizing-what-can-i-do-to-fix-this

**Comment by HelpMePlease321** [comment]
Hey I just went through all the servers and none of them would work. Some of the servers gave me "not connected" and some gave me the same "Synchronizing". I followed the all the instructions from that link you shared. 

What else is there that I can do?

**Comment by HelpMePlease321** [comment]
It works now. I forgot to do the update and so I did. After I did the update it automatically found the correct server. Thanks you guys. Really appreciate it.

Got one more question, is there a limit to how many bitcoins you can have on electrum or any of the other crypto currency wallets? 

Thanks.
