### ISSUE TITLE
Electrum on an offline Android phone - Can't load transaction, Can't find MPublicKey

### ISSUE THREAD

**Issue by franckn5** [spesmilo/electrum#3387]
I use electrum on an android gap machine (an always offline phone upon which Electrum was installed through APK) - and I cannot:

. Load a transaction I first created online on my desktop electrum - because the QR code option does not work; nor can I load the transaction through any other means as no other options work; (I want to load that transaction to sign it offline).

. I cannot find the Master Public Key of my cold storage wallet - in order to use it on my online desktop electrum.

Thanks a lot in advance for your kind support - and all the best.

**Comment by SomberNight** [comment]
> because the QR code option does not work

You need to install [ZXing](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) on your Android phone to be able to scan QR codes. It's a dependency at the moment.

> I cannot find the Master Public Key of my cold storage wallet

I'm assuming you mean in the Android app. In the app, touch the center of the header (where the name of your wallet is displayed, along with your current BTC balance).

**Comment by franckn5** [comment]
Thank you so much for your fast and efficient feedback!
