### ISSUE TITLE
Allow restoring BIP39 seeds on Android

### ISSUE THREAD

**Issue by franckn5** [spesmilo/electrum#3388]
Hi, 

With Android Electrum, may I use my very own seed (a combination of numbers resulting from 6-sided dices + some alphanumeric characters of my own) to create a wallet offline? (the same way I can do it on Electrum Desktop using the BIP39 option).

Thanks and all the best!

**Comment by franckn5** [comment]
Hi,

With Android Electrum, may I use my very own seed (a combination of numbers resulting from 6-sided dices + some alphanumeric characters of my own) to create a wallet offline? (the same way I can do it on Electrum Desktop using the BIP39 option).

Thanks and all the best!

**Comment by dan-da** [comment]
yes I was looking for this also.   Seems the bip39 option is missing in android version.   oversight or on purpose?

**Comment by SomberNight** [comment]
BIP39 option is not available on Android, indeed.

**Comment by Engelberg** [comment]
Also would like this.

**Comment by john-light** [comment]
+1 BIP-39 support is needed to generate p2sh-segwit addresses on mobile, would be great to have this feature.

**Comment by LeaTex** [comment]
When will you add this feature to Android? I need to restore my wallet on my device but can't.

**Comment by ecdsa** [comment]
added in a7b61fcab96ef138b9b8f9c8133081d539ace6a1
