### ISSUE TITLE
can reclaim my btg from electrum

### ISSUE THREAD

**Issue by luck777sam** [spesmilo/electrum#3390]
I own BTC before the fork and I move my btc to my ledger nano s in segwit chain, and then I try to reclaim my btg from my old seed or private key in electrum is supouse to be there my btg, if my btg move with my new adress I try to get from ledger nano S and is 0 BTG because supouse to be in my old seed on electrum wallet right? but I can reclaim from coinomi or other wallets with my private keys and my old seed, what I do wrong, can I still reclaim my BTG pls help me, thanks.

regards SAM

**Comment by ecdsa** [comment]
offtopic here
