### ISSUE TITLE
Black box instead of UI

### ISSUE THREAD

**Issue by GRANDAMERODA** [spesmilo/electrum#3392]
Dear Developers and Users,

I am running Linux Antergos with Gnome 3 as Desktop.
The Wallet works well, but when I open any folder in the menu bar, instead of the entries its a single black box.
It seems to be a compatibility problem either with Gnome 3 in this case.

Does anyone else experiences that? Before the update it worked very well.

Thanks for your incredible work.

**Comment by bauerj** [comment]
Can you show a screenshot?

**Comment by GRANDAMERODA** [comment]
Hi Bauerj,
please review. I was not able to take the screenshot while I opened the menu bar.
Its simply complete black, looks like a graphic bug.


![screenshot from 2017-11-28 23-12-01](https://user-images.githubusercontent.com/34030766/33327527-ab2d8240-d492-11e7-9270-b8fbabd0d363.png)
![screenshot from 2017-11-28 08-34-52](https://user-images.githubusercontent.com/34030766/33327528-ab5dbbd6-d492-11e7-9486-15f72cb221a5.png)

**Comment by bauerj** [comment]
That sure isn't right but I suspect it's either an issue with your DE or with Qt, since we don't theme the menu bar.

**Comment by GRANDAMERODA** [comment]
Hi Bauerj,
thanks, **# I deleted the package qt5ct.**
It works perfectly now, thank you for your time!
