### ISSUE TITLE
Android app crashes on switch to Requests tab

### ISSUE THREAD

**Issue by yrtimiD** [spesmilo/electrum#3396]
After first time creating payment request (New button on Receive tab), app started crashing on switching to the "Requests" tab.
version: 3.0.1
[adb log (grepped by python)](https://gist.github.com/yrtimiD/5b63a78531c6d0158e53fdd39655d3ee#file-adb-logcat-grep-python)

**Comment by ariard** [comment]
please switch to the version 3.0.2, "Requests" tab has been replaced

**Comment by yrtimiD** [comment]
Just checked in google play, in description it states 3.0.2, but actually installed version is still 3.0.1

**Comment by sorab2142** [comment]
Can confirm what @yrtimiD says is the case. Google Play shows 3.0.2.1 but inside the app it still shows 3.0.1.

**Comment by yrtimiD** [comment]
3.0.3 available in the play and has this issue fixed
