### ISSUE TITLE
[Suggestion] Import transactions to offline wallets

### ISSUE THREAD

**Issue by chrislake** [spesmilo/electrum#3398]
I was think about how you go about creating signed transactions by an offline wallet. I thought it would be a good idea if you could either import a transaction to an offline wallet using a QR code of a transaction, or maybe better still, export all transactions from the watch only wallet, and import them to the offline wallet. 

This way the offline wallet could generate signed transactions without needing to create and transfer unsigned transactions online first. This could be especially useful when your online wallet is on a phone and you don't get get to control the fee or coins used.

**Comment by SomberNight** [comment]
![electrum_load_tx](https://user-images.githubusercontent.com/29142493/33295943-e210cc28-d3d8-11e7-8f8b-3fc52a3fced0.png)

What exactly is your suggestion? There are already numerous options to import/export transactions.

**Comment by chrislake** [comment]
I have seen that option, however, it only loads the transaction, to show it on screen, or save to file. What it doesn't offer is to import it in to the wallet for the wallet to use to generate a signed spend transactions (unless I missed a button/option of course).

**Comment by chrislake** [comment]
Ah, OK, I didn't know that. I thought that just the UTXOs themselves would have contained enough information to generate new signed transactions.

If you can just copy the data directory, that would achieve what I was thinking here then, so nothing to do here :)
