### ISSUE TITLE
QR Code not working on Electrum Mac.

### ISSUE THREAD

**Issue by franckn5** [spesmilo/electrum#3400]
Hi - The QR code reader functionality does not seem to work on Electrum for Mac. How to solve that issue? Thanks a lot.

**Comment by SomberNight** [comment]
In what way does it not work? Does it segfault?

**Comment by franckn5** [comment]
On my Mac electrum, I am trying to load a transaction signed offline with electrum android, and I get this error message: "Cannot start QR scanner; zbar not available."

**Comment by ecdsa** [comment]
we know
