### ISSUE TITLE
no index.html ??

### ISSUE THREAD

**Issue by kenkit** [spesmilo/electrum#3402]
I've just configure electrum and want to use it to receive payments.
But all I get is a /req directory which leads into `req/9/7/97e50871a7/97e50871a7` but there is no index.html.
Any help will be appreciated
`cosmo@cosmo-T101MT:/var/www/html/r/req/9/7/97e50871a7$ cat *.json
{"address": "191C41GvwTNMvEqKtEdVkwMPoNrjbT2R4w", "memo": "this is a test", "websocket_port": 9999, "request_url": "http://192.168.137.46/r/req/9/7/97e50871a7/97e50871a7", "index_url": "http://192.168.137.46/r/index.html?id=97e50871a7", "status": 2, "exp": null, "websocket_server": "localhost", "URI": "bitcoin:191C41GvwTNMvEqKtEdVkwMPoNrjbT2R4w?amount=3.14&r=http://192.168.137.46/r/req/9/7/97e50871a7/97e50871a7", "amount": 314000000, "id": "97e50871a7", "time": 1511879649}`

**Comment by bauerj** [comment]
So there is nothing in `/var/www/html/r`?

**Comment by kenkit** [comment]
There is a `req` folder which leads to a `9` folder

**Comment by kenkit** [comment]
no `index.html` on all folders

**Comment by SomberNight** [comment]
Are you looking for this file? https://github.com/spesmilo/electrum/blob/master/lib/www/index.html

**Comment by kenkit** [comment]
yes sorry I was a bit caught up. 
Let me try copying it to the directory and test again.

**Comment by kenkit** [comment]
Hey it works!!!!
Now it's time to ditch some highly priced service
