### ISSUE TITLE
Transaction qui est bloqué sur "Replaceable" 

### ISSUE THREAD

**Issue by Eldiablovan** [spesmilo/electrum#3403]
Hello, since this morning I have a deposit from the date of update of the site "Replaceable" instead of the date of the deposit. The most weird thing is that the transaction's id displays 50 confirmation. This is the first time that I arrive at the same time as the deposit in the same way as my old deposits. I have no chance to have information with a right click on "replaceable". So if anyone can explain my problem to me because I block. thank you very much

Version 2.7.9 electrum

https://blockchain.info/fr/tx/d4268f798c3a582751fea698567d60ca978ef75adacf6f6d0bef56a086d3f0c3

![2017-11-28 1](https://user-images.githubusercontent.com/34071945/33337695-0aa66bca-d474-11e7-9ccd-121c0ae41436.png)

**Comment by bauerj** [comment]
Can you try to upgrade to Electrum 3? Just installing the newest version should work but make sure you have your seed backed up.

**Comment by Eldiablovan** [comment]
I just need to have the 13 words of my seed is it? No need to backup something else?

**Comment by bauerj** [comment]
Correct. That's also just to be extra-safe, normally the update will just work fine.

**Comment by Eldiablovan** [comment]
Perfect everything works. Thank you
