### ISSUE TITLE
App crashes if it can't find wallet

### ISSUE THREAD

**Issue by reubano** [spesmilo/electrum#3404]
Was pulling my hair trying to figure out why the app kept crashing. Turns out, I forgot to open the sparse disk file that contains my wallet. It'd be useful if the app gave a nice error message that it can't find the wallet.

**Comment by SomberNight** [comment]
- Are you using the QT GUI? Or how did you start Electrum?
- Did Electrum crash on startup upon trying to open the most recently used wallet (but the path for that was unavailable)?
- What OS is this on?
- Is there an exception trace if you start the app with the `-v` flag?

Can you please give more details in general?

**Comment by SomberNight** [comment]
I've found a crash that happens if the QT install wizard encounters an IOError for the path you enter and you still click `Next`.

```
[WalletStorage] wallet path /home/user/.electrum/wallets/wallet_112
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 443, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 199, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 225, in run_and_get_wallet
    if not self.storage.file_exists():
AttributeError: 'NoneType' object has no attribute 'file_exists'
Aborted
```

**Comment by reubano** [comment]
> Are you using the QT GUI? Or how did you start Electrum?

Downloaded img... double clicked icon

> Did Electrum crash on startup upon trying to open the most recently used wallet (but the path for that was unavailable)?

Correct

> What OS is this on?

macOS 10.13

> Is there an exception trace if you start the app with the -v flag?

N/A. app opened via icon, not cli

**Comment by SomberNight** [comment]
I can't reproduce this on Debian, nor on Windows 10. Might be specific to Mac.

**Comment by reubano** [comment]
@SomberNight try renaming the wallet folder. My tests show that renaming the file works fine, but if the folder is missing, it crashes.

**Comment by SomberNight** [comment]
I think this is not applicable anymore. The startup has been made much more robust to errors over recent years.
