### ISSUE TITLE
Address disappeared along with my mbtc after I used it to receive money

### ISSUE THREAD

**Issue by hubbard56** [spesmilo/electrum#3409]
Hello,
I sent a business one of my addresses to receive $140 in bitcoin and as soon as they sent the money to my address, the address disappeared along with my money. The address doesn't show up in my used nor unused addresses now.

My name is Steve Hubbard and the bitcoin address I used was:
1AjYmRcri61CYJpLBKMA4mAh9SdWJmgf3s
And I right clicked it to copy it under "addresses" tab.

I was using Electrum 2.8.2 when this happened but updated to see if that would fix it but unfortunately still no address or money in my wallet.

Any help would be much appreciated.
Thanks,
Steve

**Comment by SomberNight** [comment]
Do you see the transaction in the `History` tab?

**Comment by ecdsa** [comment]
please use a recent version before posting here

**Comment by AbdussamadA** [comment]
ctrl+f on the addresses tab to search for addresses.

**Comment by SomberNight** [comment]
Have you been able to figure out what happened here? Was it user error/malware?

**Comment by SomberNight** [comment]
closing; no answer
