### ISSUE TITLE
Need Help After Losing Information

### ISSUE THREAD

**Issue by alexkamens** [spesmilo/electrum#3414]
Hello! I'm having a huge issue with my Electrum wallet; essentially, a series of freak accidents happened recently where my mom threw away my seed for my wallet while cleaning for Thanksgiving, AND I accidentally erased the 2FA code for my wallet thinking that I wouldn't need it to transfer my coins to a new wallet. It was a momentary lapse of judgment, and it's left me with no way to recover my wallet, or transfer my coins to a new wallet. Is there any possible way to have 2FA turned off for my Electrum wallet provided I provide any and all personal information needed to verify my identity and prove I have complete ownership of the wallet? If not, is there anything else I can do to regain access to my Bitcoin? I have about $800 worth of it inside my wallet, which may not seem like a lot, but I'm a college student without a ton of money and every bit counts. I do still have the password to my wallet if that helps at all.

**Comment by bauerj** [comment]
Hey,

you can try to contact TrustedCoin. Maybe they will be able to help you.

**Comment by cluelessperson** [comment]
Join us here to chat real quick:
http://webchat.freenode.net/?channels=electrum

Check your wallet file on your computer to see if it has the seed in it still, you can just use that to recover if it's there.

You may also contact trusted_coin as baurj suggested.
