### ISSUE TITLE
Trezor/Ledger Electrum Issue / crash

### ISSUE THREAD

**Issue by renkcub** [spesmilo/electrum#3417]
![image](https://user-images.githubusercontent.com/4219417/33404844-158f68de-d523-11e7-88b6-f60fa4fed434.png)

Having the strangest issue. 

I created an Electrum wallet. I used whatever "default" features were didn't plug in my Ledger. 

I may have had my Trezor plugged in at the time

I don't remember any specific items checked during setup - My goal was just to create a quick, unsecured Light wallet to move some mBTC around one-time.

However, now, when I am trying to move the balance I sent in back out, it is asking me to confirm the transaction via Ledger. This makes no sense, as I never even connected my Ledger for months. I tried connecting it, and I get an error when I try to send (Exception: Invalid channel), or it crashes. Do you know of any fixes for this issue?

Is there some way I can export my private key or seed and restart without the wallet being "attached" to this "Ghost" Ledger, and just start over?

I don't know if the way I set it up, the Electrum confused my Trezor with Ledger (and the Trezor doesn't seem to be "picking up" - wallet thinks it's a Ledger wallet") or I don't know what...

There is the possibility I pulled the Trezor out mid-way during setup. If so, is this a recoverable situation?

Note, when I connect my Ledger, it shows as "green" in the bottom right of the wallet... So it is "recognized" in that sense.

**Comment by renkcub** [comment]
Another error image: 
![image](https://user-images.githubusercontent.com/4219417/33404961-99d2a1d8-d523-11e7-94dc-6df22b284715.png)

**Comment by renkcub** [comment]
Note, no "confirm transaction" option ever comes up on my Ledger.

**Comment by SomberNight** [comment]
Do not delete this wallet.
Try creating a new wallet using your Ledger; and another using your Trezor; and see if one of those matches up with the initial wallet (e.g. addresses are the same).

**Comment by renkcub** [comment]
Thanks for the response.
It did have the same addresses for Ledger.
I went ahead and tried to send via Ledger. It froze and is still spinning. Suggestions? Try again, or some way to dump the private key or seed?

**Comment by SomberNight** [comment]
Could be https://github.com/spesmilo/electrum/issues/3264
You could try https://github.com/spesmilo/electrum/issues/3264#issuecomment-345414501 or wait for the next minor release.

**Comment by renkcub** [comment]
I was able to resolve with your suggestion.
