### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by wakiyamap** [spesmilo/electrum#3420]
https://github.com/spesmilo/electrum/blob/master/gui/qt/installwizard.py#L491
"servers all fulfill the same purpose only differing in "

https://github.com/spesmilo/electrum-locale/blob/master/locale/ja_JP/electrum.po#L560
"servers all fulfil the same purpose only differing in "

**Comment by sunnyville01** [comment]
"Fulfill" and "Fulfil" are both apparently correct spellings of the word. Don't think this is an issue.

**Comment by wakiyamap** [comment]
@sunnyville01 Thanks reply. Your thinking is right. 
But these words are used localization.

English(default) is displayed even if you select other than English.
I could not tell whether "fulfil" or "fulfill" was correct.
So I write an issue.

**Comment by bauerj** [comment]
Hey,

you should use what's in the crowdin template. In [this case](https://crowdin.com/translate/electrum/68/en-de#6577), "fulfill" is used.

The translation in the other repository will be updated when there is a new release while crowdin is always up to date.

**Comment by wakiyamap** [comment]
@bauerj thanks!!
