### ISSUE TITLE
Electrum 3.0.2 - Cannot find python library for 'ledger'. Make sure you install it with python3

### ISSUE THREAD

**Issue by adrelanos** [spesmilo/electrum#3422]
Debian stretch.

    sudo apt-get install python3-setuptools python3-pyqt5 python3-pip

    sudo apt-get install libusb-1.0-0-dev libudev-dev python-btchip

https://download.electrum.org/3.0.2/Electrum-3.0.2.tar.gz

Getting a popup.

```
Cannot find python library for 'ledger'.
Make sure you install it with python3
```

There is no package python-ledger / python3-ledger or python3-btchip.

Please kindly advice which package is missing and to be installed.

**Comment by SomberNight** [comment]
Try
```
python3 -m pip install btchip-python
```

**Comment by DelasFlores** [comment]
plese help i can find a solution  

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for amnesia: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by adrelanos** [comment]
python3 -m pip install btchip-python

That worked for me. Thanks!

What about https://packages.debian.org/search?keywords=python-btchip? python-btchip is unsufficient? Debian maintainers would have to create a package python3-btchip?

**Comment by cluelessperson** [comment]
Close.  package maintainers problem

**Comment by petervnv** [comment]
I wish you hadn't closed this even though it's not really an electrum problem.

I'm on ubuntu 16.04 and none of the workarounds worked for me.

I think we really need a python3-btchip package for debian/ubuntu to get electrum to work with ubuntu, but there are none available. Does anyone have a link to the code so we could try and compile it ourselves on ubuntu?

Thanks

**Comment by SomberNight** [comment]
@petervnv 
Please provide some info regarding what is failing and how; because it is hard to help without that.

Try:
```
sudo apt-get install python3-dev cython libusb-1.0-0-dev libudev-dev git
python3 -m pip install hidapi
python3 -m pip install btchip-python
```

**Comment by petervnv** [comment]
Thanks @SomberNight 
Got it working fine with my Nano S now
