### ISSUE TITLE
Derivation presets for HW wallets

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#3423]
Electrum asks to choose seed type (standard or segwit), but it does not ask do I want segwit for Trezor, it does not create segwit by default for HW wallets. Instead it asks to enter derivation BIP32 path. What about to allow users to choose between standard and segwit for HW wallets too? There may be some presets for derivation - less likely to enter derivation incorrectly.

**Comment by SomberNight** [comment]
Somewhat discussed already in https://github.com/spesmilo/electrum/issues/3373

**Comment by lzsaver** [comment]
Thanks.
