### ISSUE TITLE
My balance is disappeared when I log in Electrum wallet

### ISSUE THREAD

**Issue by paulz555** [spesmilo/electrum#3424]
Hi Team,
29.11.17 I decided to check my balance in bitcoin, but it was zero there is no history at all. Can you kindly check please what happen there. I tried to delete and download a new one put in seed 12 words but the balance still zero. Can you please help me?

**Comment by ecdsa** [comment]
if there used to bea history, and it is not there anymore, that means you are not looking at the same wallet

**Comment by paulz555** [comment]
There was just one transaction some days ago. What should be my actions delete everything and download and try to restore with seed on computer ? But tried to look at the balance at my mobile application put seed words but 0.00 balance as well. No history at all.

**Comment by paulz555** [comment]
Is it possible that data just overlapped on my computer but the balance is normal ? How correctly restore my wallet?  Because I have seed and plus have extension seed but there is no any opportunity to put in extension seed

**Comment by SomberNight** [comment]
During the restore process, in the wizard, when you enter your seed words, choose `Options`, and tick `Extend this seed with custom words`. You will be able to enter the seed extension on the next screen.

**Comment by SomberNight** [comment]
You should probably don't delete anything related until you are sure you have access to your coins.
