### ISSUE TITLE
not able to sign a message

### ISSUE THREAD

**Issue by flex2** [spesmilo/electrum#3425]
Hello,

I am trying to claim Byether coins, which requires proving that I am the owner of that address by signing it. However, when I do try to sign it, I receive the following message:
 "Signing with an address actually means signing with the corresponding private key, and verifying with the corresponding public key. The address you have entered does not have a unique public key, so these operations cannot be performed." 
The address in question is an Electrum wallet generated address: 3MymHcNp4NfHBixRDov7ZsAkXwWD8RPeus.
I am able to extract private key of this address. Does it mean that because I made more than one deposit/withdrawal to the same address it doesn't have unique public key anymore? If so, what is a solution? Any help would be appreciated.

**Comment by SomberNight** [comment]
> Does it mean that because I made more than one deposit/withdrawal to the same address it doesn't have unique public key anymore? 

No, that's not how it works.
However, if it is a multisignature address, then it indeed has more than one public key associated with it. Bitcoin "message signing" is undefined in the case of multisignature addresses.
From a quick look at previous txs associated with the address, it does look to be multisig to me, but you should know in any case. Note that Electrum 2FA addresses use multisig.

**Comment by flex2** [comment]
I always set up Electrum wallets as standard with 2FA protection. Could 2FA protection mess this up? Also, is there a web site to check whether or not the BTC address is multisig address?

**Comment by ecdsa** [comment]
@flex2 ask byether how they deal with multisignature addresses. 
please stop posting here, you are wasting our time.

**Comment by flex2** [comment]
Well, I am sorry, but nobody is demanding you to respond. I am simply wanted to know if there is a solution to my problem. By the way - great customer support ELECTRUM.
