### ISSUE TITLE
"Pay to" in "Send" tab detects invalid address: Invalid Lines found

### ISSUE THREAD

**Issue by 1234Investor** [spesmilo/electrum#3427]
Hi,

When I try to send my BTC a box appears and it says: Invalid Lines found Line #1: 14cVa11XS57xsZMHP7CAB1hnSWBiBZd1v9

Some sort of bug.

Thank you.

D.

**Comment by danny91** [comment]
Could be that 14cVa11XS57xsZMHP7CAB1hnSWBiBZd1v9 is empty?

**Comment by SomberNight** [comment]
> Invalid Lines found

That error usually occurs when you try to send to a not valid address (e.g. mistyped).

> Could be that 14cVa11XS57xsZMHP7CAB1hnSWBiBZd1v9 is empty?

No, that should not matter. He is trying to send TO that address.

**Comment by 1234Investor** [comment]
I am able to not send to certain bitcoin addresses it turns out. Maybe my friend has an empty account and it's just not sending it there. He sent me two accounts and they both don't work. Other accounts work. Thanks.

**Comment by ecdsa** [comment]
that address works for me. did you type extra characters with the address?

**Comment by ecdsa** [comment]
are you using Testnet, or some altcoin version of Electrum?

**Comment by sevas80** [comment]
Did you solve it?
I have the same problem..

**Comment by SomberNight** [comment]
@sevas80 

> are you using Testnet, or some altcoin version of Electrum?

Also, which version of Electrum?

**Comment by sevas80** [comment]
Hello!

I don't use testnet.
Version 3.0.2

Thanks

On 10 Dec 2017 10:47 p.m., "ghost43" <notifications@github.com> wrote:

@sevas80 <https://github.com/sevas80>

are you using Testnet, or some altcoin version of Electrum?

Also, which version of Electrum?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/spesmilo/electrum/issues/3427#issuecomment-350584242>,
or mute the thread

**Comment by SomberNight** [comment]
@sevas80 
And are you absolutely certain that the address you have there is correct? It should not be mistyped, and no extra characters should be there (e.g. before or after). It should be a valid bitcoin address and nothing else.

If so, does it only happen for certain addresses? Is it reproducible (across even e.g. app restarts)?

**Comment by sevas80** [comment]
I copy the address from binance.
checked for security, but is good. there is also no space behind it.

It is the first time for me..

**Comment by sevas80** [comment]
Good morning,

This morning i tried again, but unfortunately again the same message.

I have enough on my account.
The address I want to transfer to, I copy from BInance.

Unfortunately again the same message ..

Someone another idea?

thank you in advance!

**Comment by sevas80** [comment]
I did it wrong ..

I tried to transfer money to another currency.

first had to transfer to BTC and from there purchase other currencies ..

Thank you for the assistance

**Comment by ecdsa** [comment]
shitcoins...

**Comment by JHHC** [comment]
I have the same problem... I can't send my bitcoins to another wallet.
![img_20171219_191501](https://user-images.githubusercontent.com/32079366/34172287-ce3dde5a-e4f1-11e7-8c7d-1f09635b3665.jpg 
![img_20171219_191501](https://user-images.githubusercontent.com/32079366/34172372-1ca2a0ee-e4f2-11e7-8766-151e9dce1352.jpg)

What can I do ????

**Comment by sevas80** [comment]
Are you sending from BTC to BTC?

**Comment by SomberNight** [comment]
@JHHC That's not a bitcoin address.

**Comment by JHHC** [comment]
No, Im sending BTC to altcoins and it happen in all of them

**Comment by SomberNight** [comment]
@JHHC That is not something you can do. Electrum is a bitcoin client, it **only supports bitcoin**. What you want is an exchange.

**Comment by JHHC** [comment]
THANK YOUUUUUU ! ! !  . . . .

**Comment by leocornelius** [comment]
.
