### ISSUE TITLE
Preferences window is not opening in Ubuntu 16.04

### ISSUE THREAD

**Issue by stopRequiringLoginForMinorFeedback** [spesmilo/electrum#3428]
After fresh installation using snap, preferences window is not opening in Ubuntu from what I understand is a camera access issue.

The output on the console after opening the program and clicking on preferences menu:

(process:13971): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/snap/electrum/2/gui/qt/main_window.py", line 2773, in settings_dialog
    system_cameras = qrscanner._find_system_cameras()
  File "/snap/electrum/2/lib/qrscanner.py", line 70, in _find_system_cameras
    name = open(os.path.join(device_root, device, 'name')).read()
IOError: [Errno 13] Permission denied: '/sys/class/video4linux/video0/name'

**Comment by ecdsa** [comment]
you are running deprecated code, there should be a try..except block there
