### ISSUE TITLE
wallet sync between Windows and Linux

### ISSUE THREAD

**Issue by Atlasshagged1** [spesmilo/electrum#3433]
ok setup my wallet on a win10 machine, file is  stored on dropbox. installed Electrum on ubuntu 17.10.

when i try to open the wallet on my linux box it correctly asks for the password but then the GUI disappears. Nothing. While the GUI is up during password entry phase I can see the Electrum process running. as soon as I type in my password, the Electrum process quits

**Comment by AbdussamadA** [comment]
you could try running dos2unix on the wallet file. otherwise just restore from seed on the ubuntu box.

**Comment by Atlasshagged1** [comment]
Odd. When I use the seed from my windows wallet to create a wallet under linux I get different addresses.
If I use that same seed to create multiple wallets under linux all wallets have the same addresses.

**Comment by AbdussamadA** [comment]
use the same seed to create multiple wallets under windows and see what happens. do the addresses between those windows wallets differ?
