### ISSUE TITLE
Separate TREZOR and KeepKey codebase

### ISSUE THREAD

**Issue by slush0** [spesmilo/electrum#3434]
Hello,

please separate codebase for Keepkey and TREZOR plugins. I'm trying to update Electrum for latest Trezor API (0.8) which will be released soon, but it is impossible when we have to keep compatibility with Keepkey. I even don't have Keepkey to test and debug.

There are already some "fixes" crippling Electrum-TREZOR integration like disabling support for trezord, because it does not work with Keepkey. That's keepkey issue, but it affects TREZOR user experience, which I obviously don't like.

I'll happily keep Electrum codebase updated to work seamlessly with TREZOR, but not for Keepkey.

**Comment by slush0** [comment]
I suppose this commit will break Keepkey integration because HidTransport in trezorlib>=0.8.0 (not released yet) no longer accepts path in constructor.

https://github.com/slush0/electrum/commit/0266c4d4c033365319ad97d65f90942bafbb366e

**Comment by slush0** [comment]
This is only preparation for future changes though. We plan to move from HID to WebUSB for Trezor model T, so more dramatical changes are coming. python-trezor API won't change, but currently Electrum is doing device detection on their own instead of using python-trezor's enumerate(), which won't work for model T.

I'll happily post pull request after separation of Keepkey plugin.

**Comment by ecdsa** [comment]
I agree with having such a code separation.
we can start with a commit that replicates shared classes in the keepkey plugin

**Comment by slush0** [comment]
That would be much appreciated! Do you have Keepkey yourself to test it? I worry a bit doing such things without a chance to test it.

**Comment by ecdsa** [comment]
done in 958b794bc9e38343d9a3738f4c22afc3a3b8e917
I do have a keepkey. I have not tested yet.
