### ISSUE TITLE
JSON-RPC Basic auth support

### ISSUE THREAD

**Issue by igrishaev** [spesmilo/electrum#3436]
Does the RPC server support `rpcuser` and `rpcpassword` options to prevent unauthorized access like the original Bitcoin core does? Below, here is my Electrum config with both user and password set, but the server still responds for anonymous access:

```json
{
    "auto_connect": true,
    "rpcpassword": "123",
    "rpcport": 7777,
    "rpcuser": "ivan"
}
```

```bash
curl --data-binary '{"id":"curltext","method":"getbalance","params":[]}' http://127.0.0.1:7777
{"result": {"confirmed": "0"}, "id": "curltext", "error": null}
```

**Comment by SomberNight** [comment]
No, this is currently not implemented. However there is already an issue about this. https://github.com/spesmilo/electrum/issues/3374
