### ISSUE TITLE
Does URL notification really work?

### ISSUE THREAD

**Issue by igrishaev** [spesmilo/electrum#3437]
I tried to reproduce the whole scenario when an address of mine got paid and a URL notification should be called (in testnet mode). However, it did not happen. Here are the steps I made:

1. start daemon and load wallet:
```
electrum --testnet daemon start
electrum --testnet daemon load_wallet
```

2. Create payment request
```
electrum --testnet addrequest 1
{
    "URI": "bitcoin:mmZJ2SR7Eji7Qe7SgWFVVh3p8HJ1Hv9MtW?amount=1.",
    "address": "mmZJ2SR7Eji7Qe7SgWFVVh3p8HJ1Hv9MtW",
    "amount": 100000000,
    "amount (BTC)": "1.",
    "exp": null,
    "id": "3799c3948d",
    "memo": "",
    "status": "Pending",
    "time": 1512320573
}
```

3. Add notification with RequestBin service that captures all the requests to the URL:
```
electrum --testnet notify mmZJ2SR7Eji7Qe7SgWFVVh3p8HJ1Hv9MtW https://requestb.in/w9bp68w9
```

4. Get paid to that address using Testnet Sandbox service: https://testnet.manu.backend.hamburg/faucet

The result: calling `--testnet getbalance` displays the new balance within updated wallet history. However, the target URL was not called. The https://requestb.in/w9bp68w9?inspect page does not show any caught calls.

Can you give me any tips on what did I do wrong?

**Comment by ecdsa** [comment]
some other issues have been reported about it.
you should have a look
