### ISSUE TITLE
Can't withdraw funds

### ISSUE THREAD

**Issue by Rotor123** [spesmilo/electrum#3442]
threw the program and forgot. 
found chops and wanted to withdraw. 
but can't send
![_2017-12-04_12-20-25](https://user-images.githubusercontent.com/29670160/33544916-a7061088-d8ed-11e7-8a0e-cf1b29a6449e.png)

**Comment by Rotor123** [comment]
![_2017-12-04_12-22-22](https://user-images.githubusercontent.com/29670160/33544974-ccef4288-d8ed-11e7-87a1-89117aef2c86.png)

**Comment by SomberNight** [comment]
The second output with the amount of 0.002 BTC is probably a TrustedCoin 2FA fee prepayment for 20 transactions.
I'm not sure why the `Sign` button is grayed out... Did it prompt you for a 2FA code?

Anyway, if you don't want to retain the extra security of 2FA for this wallet anymore, you should restore from your seed words, choose to "disable 2FA", and then you won't need to pay TrustedCoin to co-sign.

**Comment by Rotor123** [comment]
fuck, I got.... 
Thank you.....

**Comment by SomberNight** [comment]
@ecdsa It seems the tx in the pic is partially signed by the local cosigner, but is not signed by TrustedCoin. Do we need to look into this, or is there a plausible non-bug explanation? Otherwise this can be closed.

**Comment by Rotor123** [comment]
You can close....
