### ISSUE TITLE
how to import the multibit HD wallet to electrum

### ISSUE THREAD

**Issue by liuyazhou000** [spesmilo/electrum#3443]
i tried.but failed.thank you

**Comment by SomberNight** [comment]
What are you trying to import? Seed words? Individual private keys? An xprv or xpub?

If seed words, on the screen where you need to enter them, click `Options` and then tick `BIP39 seed`.

**Comment by liuyazhou000** [comment]
seed words.     of course , i selected the BIP39. then the electrum wallet set up, but  i can not find my multibit HD' address in electrum wallet. i hope you Can help me.thank you

**Comment by SomberNight** [comment]
> multibit HD' address

What is that?
The xpub? If so, check `Wallet`>`Information`.
If you mean individual bitcoin addresses, click `View`>`Show Addresses`, and then go into the `Addresses` tab.

**Comment by ecdsa** [comment]
some versions of multibit do not use the default bip44 derivations.
ask them, not us
