### ISSUE TITLE
Feature Request: Testnet support for 2FA wallets

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3445]
Currently, 2FA wallets can't be used on testnet.
There seems to be no support for it on the server-side by TrustedCoin, and some small bits are likely missing on the client side from Electrum.

I can code the client side, but I would need TrustedCoin to make the server side changes.

In the docs for the normal `/1/` API provided by TrustedCoin, there seem to be support for testnet.
[The docs say](https://api.trustedcoin.com/#/docs) that `POST /1/cosigner` supports an optional `'network'` property.
However Electrum uses a custom API on `/2/`.

I tried including the `'network'` property in the HTTP request the client sends but it is ignored by the server.

Patch:
```patch
diff --git a/plugins/trustedcoin/trustedcoin.py b/plugins/trustedcoin/trustedcoin.py
index 7cd2976b..bb8efed6 100644
--- a/plugins/trustedcoin/trustedcoin.py
+++ b/plugins/trustedcoin/trustedcoin.py
@@ -74,7 +74,7 @@ class TrustedCoinException(Exception):
 class TrustedCoinCosignerClient(object):
     def __init__(self, user_agent=None, base_url='https://api.trustedcoin.com/2/'):
         self.base_url = base_url
-        self.debug = False
+        self.debug = True
         self.user_agent = user_agent
 
     def send_request(self, method, relative_url, data=None):
@@ -125,6 +125,7 @@ class TrustedCoinCosignerClient(object):
             'xpubkey1': xpubkey1,
             'xpubkey2': xpubkey2,
             'billing_plan': billing_plan,
+            'network': 'testnet',
         }
         return self.send_request('post', 'cosigner', payload)
```

Log:
```
post https://api.trustedcoin.com/2/cosigner
{
  'xpubkey2': 'xpub69EkcMgnjkJnqwAWbRSeFxR3ZpA5C7ohw42MSQRhirvTTkvshpyKqQ7EfN2rLSPKZYpHc3h22HAyUt6rUUypfWQUeL5QzrQQyAEPNaRNejs',
  'network': 'testnet',
  'email': 'testing@asdads.com',
  'billing_plan': 'electrum-per-tx-otp',
  'xpubkey1': 'xpub69EkcMgnjkJnmoeepTjhWYmaC3t7sypaAZT8AdZBdRsL4d6ajhFP6dBDwtHdWmf1CKRAKdHtZFr7HjeHkNrTqWzsgk3JJeepHQNn5iY7DGM'
}

{
 "xpubkey_cosigner": "xpub661MyMwAqRbcEotrBwFuVEfan8PwDZhAw6S5CAQftiD5WnyTwjkgAuSKYbdi8LzkcRmPNRF3n3qZtKekw2iMfLWEZ6SbKURxfzt1ABSddPV",
 "billing_address": "1BcVCmr6kkhCui4jmcrN5YWfdQTBkSjuyE",
 "otp_secret": "VJ6MLBN2NXX3CA4K",
 "network": "mainnet",
 "billing_plan": "electrum-per-tx-otp",
 "billing_index": 0,
 "price_per_tx": [
  [1, 50000],
  [20, 200000],
  [100, 500000]
 ],
 "id": "eaa95b4df17f1397b1a4294d339f66699583ea7400b53bcc50bf96a49b8c1b7d",
 "tx_remaining": 0
}
```

Note that the HTTP request contains `'network': 'testnet'` but the reply contains `"network": "mainnet"`.

I would be a lot more happy to tackle issues such as https://github.com/spesmilo/electrum/issues/3429 using testnet.

Any chance for the server side changes? @badmofo

**Comment by badmofo** [comment]
2FA *is already* supported by `POST /2/cosigner`.  The docs that are confusing you are for V1 of the API `POST /1/cosigner`.  V2 of the AP1 does not take a `network` parameter but instead looks at the [version bytes](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Serialization_format) of `xpubkey1` and `xpubkey2`.  

Example:

```
POST https://api.trustedcoin.com/2/cosigner
{
    "billing_plan": "electrum-per-tx-otp",
    "email": "testing@example.com",
    "xpubkey1": "tpubDAenfwNu5GyCJWv8oqRAckdKMSUoZjgVF5p8WvQwHQeXjDhAHmGrPa4a4y2Fn7HF2nfCLefJanHV3ny1UY25MRVogizB2zRUdAo7Tr9XAjm",
    "xpubkey2": "tpubDBYR91mmnGEVD4M2wwKADarXJ422Dgcw1Ttyu2zzFci3H3Q5xrD9THqL5HcicpnLRqZooP3EdkBAfZq3eSESFzvQzyodFYXwNqcsPdW5xYb"
}

{
    "billing_address": "mrr5EixWz17RWGN9UuSzVVh6ij53EqW7Xr",
    "billing_index": 0,
    "billing_plan": "electrum-per-tx-otp",
    "id": "7b8cf4532304a529aa504b4a6072b4f53d2650480c844c0059c5df64dec78c76",
    "network": "testnet",
    "otp_secret": "LXRNTUDGSZCWAM5P",
    "price_per_tx": [
        [
            1,
            50000
        ],
        [
            20,
            200000
        ],
        [
            100,
            500000
        ]
    ],
    "tx_remaining": 0,
    "xpubkey_cosigner": "tpubD6NzVbkrYhZ4XUiuFTGcXm4mYGReaxRxzcrRo5ga4X1qo4hQ75YsZzM9bLM7D1daaLYJFMxk9z7efG3tu1JPNqZtviJS3DDiisH2LihF6ni"
}
```

**Comment by SomberNight** [comment]
> The docs that are confusing you are for V1 of the API

I know that the docs I linked to are not the API Electrum uses; I thought this was clear from my post, sorry. :) I only referred to them to provide reasoning for what I had tried.

Btw, Electrum in 3.0 deprecated version bytes in xpub/xprv for testnet, but I can work around that.

Thank you for the quick reply, I'll look into the client side changes now.

**Comment by SomberNight** [comment]
@badmofo 
Would you be able to provide the signing and billing xpubs for testnet?
https://github.com/spesmilo/electrum/blob/a4e89e822a208daa574c4bd1d8ecfea952c6c101/plugins/trustedcoin/trustedcoin.py#L45-L46

Using the values from the HTTP replies, I have now sent around a few txns, and it seems to be working. :)

**Comment by badmofo** [comment]
See https://api.trustedcoin.com/2/info?billing_plan=electrum-per-tx-otp
<https://api.trustedcoin.com//2/info?billing_plan=electrum-per-tx-otp>
