### ISSUE TITLE
Compile sources to standalone exectucable file

### ISSUE THREAD

**Issue by John13Campbell** [spesmilo/electrum#3450]
I would like compile sources to one exe file. 

So, I installed python 3.6, pyqt5 and pyinstaller. 

I checked that it run properly when it works in interpreter (command: python electrum)

But now I would like generate exectucable file.

I executed:

pyinstaller --onefile --noconsole electrum

and in dist directory was generated electrum.exe 

unfortunately, when I try run electrum.exe , I get an error message:

> Traceback (most recent call last):
> File "electrum", line 373, in <module>
> File "site-packages\electrum-3.0.2-py3.6.egg\electrum\daemon.py", line 282, in init_gui
> ModuleNotFoundError: No module named 'electrum_gui'
> [5556] Failed to execute script electrum

how to solve this problem ?

**Comment by SomberNight** [comment]
See `contrib/build-wine` for building the Windows binaries on Linux/Wine. The instructions there can probably be adapted to building on Windows.

**Comment by John13Campbell** [comment]
Directory contrib/build-wine doesn't exist

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/tree/master/contrib/build-wine
