### ISSUE TITLE
Testnet not working on windows

### ISSUE THREAD

**Issue by NicolasDorier** [spesmilo/electrum#3451]
Running

```
"C:\Program Files (x86)\Electrum\electrum-3.0.2.exe" --testnet
```

![image](https://user-images.githubusercontent.com/3020646/33652944-a8d65d60-daae-11e7-8d0e-91760ad2544f.png)

**Comment by SomberNight** [comment]
Thanks but this should be fixed on master already. https://github.com/spesmilo/electrum/issues/3321

**Comment by NicolasDorier** [comment]
Any idea when you will distribute a release ?

**Comment by ecdsa** [comment]
I will try tomorrow

**Comment by NicolasDorier** [comment]
@ecdsa any luck to do it soon? This is blocking for some users of BTCPay which would like to try on testnet.

**Comment by ecdsa** [comment]
the release is out
