### ISSUE TITLE
Error during compilation to standalone executable file

### ISSUE THREAD

**Issue by John13Campbell** [spesmilo/electrum#3454]
I get an error when I try to create binaries for windows. 

After execution all previous steps from the instructions in README file and after calling "sn build.sh" in /electrum/contrib/build-wine 

I got an error messages:

```
Clearing ./build and ./dist...
Cleaning /opt/wine64
done
wine: created the configuration directory '/opt/wine64'
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
Could not load wine-gecko. HTML rendering will be disabled.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/opt/wine64' has been updated.
Cleaning tmp
done
gpg: keybox '/root/.gnupg/keyring-electrum-build-python-dev.gpg' created
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/run/user/0/gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

It is problem with wine version ?

**Comment by bauerj** [comment]
Have you installed dirmngr?

**Comment by John13Campbell** [comment]
No, instruction contains no information that it must be installed.

I will try

**Comment by bauerj** [comment]
Indeed. If that fixes it, I will add information regarding gpg to the README.

**Comment by SomberNight** [comment]
There's a note in the actual file.
https://github.com/spesmilo/electrum/blob/c8a2ff15b881310d653d754e60566cf7993d282f/contrib/build-wine/prepare-wine.sh#L57-L59

Clearly it should have been added to the README instead, sorry about that.

**Comment by John13Campbell** [comment]
yes, it helped me

BTW: two question: what is difference between standalone and portable version ? 

What are the advantages of installing setup version ?

**Comment by John13Campbell** [comment]
I have further problems 

I made little modifications, in electrum_qui/qt/installwizard.py

I changed content of QLabel from "Wallet" to "TEST".

After this. I run python3 electrum and it displays correctly ("TEST" instead "Wallet")

unfortunately, when I recompiled the wallet by run sh build.sh, I received a file that still runs the old version

in other words, the compilation **does not occur**, at least not from sources which I have modified

Did I do something wrong ?

**Comment by SomberNight** [comment]
In `contrib/build-wine`, delete
- `build`
- `dist`
- `tmp`

You probably don't need to delete all, I'm not sure atm.

**Comment by bauerj** [comment]
It pulls whatever is on the repo right now so you need to modify build_electrum_git.sh to use local changes instead.

**Comment by John13Campbell** [comment]
What is the easiest way to modification build_electrum_git.sh so as to my local sources was used ?

**Comment by bauerj** [comment]
Use something like `cp ../../..` instead of `git pull`.
