### ISSUE TITLE
unicode is not defined

### ISSUE THREAD

**Issue by JohnnyBizzel** [spesmilo/electrum#3456]
After installing Development version, when running I get this error:
`  File "/home/me/Documents/PYTHON/electrum-master/lib/paymentrequest_pb2.py", line 66, in <module>
    has_default_value=True, default_value=unicode("main", "utf-8"),
NameError: name 'unicode' is not defined
`
Apparently according to a quick search 

> Python 3 renamed the unicode type to str, the old str type has been replaced by bytes.

**Comment by ecdsa** [comment]
you are not running electrum with the correct file
