### ISSUE TITLE
Can’t open old wallet.dat

### ISSUE THREAD

**Issue by Pazu** [spesmilo/electrum#3457]
I found an old wallet.dat from 2013 and thought to try opening it using Electrum 3.0.2 on Mac OS X.

When I do so, I see, “Cannot load wallet: ‘ascii’ codec can’t decode byte 0xa7 in position 52: ordinal not in range(128).”

![screen shot 2017-12-06 at 16 41 08](https://user-images.githubusercontent.com/2777268/33670275-f9723f32-daa4-11e7-9f0f-bd0f813b210f.png)

The debug.log in the same folder as the wallet.dat includes the following, in case it’s helpful.

`Bitcoin version v0.8.1-beta (2013-03-17 15:35:36 -0400)`

Should Electrum be able to open this file?

**Comment by SomberNight** [comment]
> Should Electrum be able to open this file?

No, it shouldn't, or at least it currently can't.

You should try with Bitcoin Core. That's not an Electrum wallet.
