### ISSUE TITLE
Electrum 3.0.2 for Windows unauthorized transaction

### ISSUE THREAD

**Issue by InsideOut21** [spesmilo/electrum#3459]
Yesterday I send 0.0023 bitcoins to my Bitfinex Adress and the transaction show up that i also send 0.002 to another unauthorized adress. What makes me dazed is that it shows under sent to only the adress of my Bitfinex adress, but in the output it shows the unauthorized adress. I just want to know what has happend.

Here you have a link to the Transaction: https://www.blocktrail.com/BTC/tx/ea36aa4d6f6474b73b0c8bdd7e8413765e537dcf0ad784ec322b1e7f25347366

**Comment by bauerj** [comment]
Is this the 2FA fee?

**Comment by InsideOut21** [comment]
Oh ok, i think so. Thank you for this fast answer.
