### ISSUE TITLE
Distribute electrum as a flatpak

### ISSUE THREAD

**Issue by mwleeds** [spesmilo/electrum#3463]
Hi,

I think Electrum should have a [flatpak](https://flatpak.org) on [flathub.org](https://flathub.org) to make it easier for Linux users to install it and to reach platforms like [Endless](https://endlessos.com) that can't otherwise be reached. I'd be happy to help make the manifest. Is that something the Electrum developers would appreciate? Flathub lets upstream developers maintain their flatpak packaging so you'd have control over it if you want.

**Comment by ecdsa** [comment]
no time for that. 
also, adding intermediaries in the chain of trust is not good.

**Comment by tmartinx** [comment]
Electrum via Flatpak and Snap would be awesome!

Pretty sure that the right people can sign the packages, right?     :-P

No time? True, today's life is busy...   :-(

Cheers!
