### ISSUE TITLE
Missing my fund

### ISSUE THREAD

**Issue by BrunoCrime** [spesmilo/electrum#3466]
Today ,later check on electrum my funds are missing i don't have send all my funds and i see replaceable
![1e](https://user-images.githubusercontent.com/34344740/33720906-b295c7a2-db65-11e7-8285-27db61ac7138.JPG)

**Comment by hachre** [comment]
Someone must have gotten your seed words or stolen your wallet file + password. Maybe you have a keylogger on your computer and typed the seed in recently?

**Comment by bauerj** [comment]
See also #3225.

**Comment by ecdsa** [comment]
we cannot help you if your coins have been stolen.

**Comment by BrunoCrime** [comment]
Ok tks to all , change wallet
