### ISSUE TITLE
[SUGGESTION] Add EUR for Bitstamp Exchange

### ISSUE THREAD

**Issue by Lokda** [spesmilo/electrum#3467]
Hello.

Can you just add euro (**EUR**) for Bitstamp in Electrum ?
Currently, there is only USD.

Thanks.

**Comment by Lokda** [comment]
Is this a solution ??

`class BitStamp(ExchangeBase):

    def get_rates(self, ccy):
        json = self.get_json('www.bitstamp.net', '/api/ticker/')
return {'USD': Decimal(json['last'])}

def get_rates(self, ccy):
    json = self.get_json('www.bitstamp.net', '/api/ticker/btceur')
return {'EUR': Decimal(json['last'])}`

**Comment by SomberNight** [comment]
this was done in https://github.com/spesmilo/electrum/commit/d6c2a0af946a7691b226a59aa5e3bcdcd6e31fa7
