### ISSUE TITLE
[Suggestion] Transaction: show fee preview in a textbox (like for the amount)

### ISSUE THREAD

**Issue by firepol** [spesmilo/electrum#3471]
Hi, now when you create a transfer and select as your currency e.g. EUR, you see as a preview an estimate in EUR of the selected amount of BTC (or mBTC).

It would be nice to have the same text box near the fee. So when you move the slider and see the total fee based on the satoshi/byte, it would be nice to see also how much is the fee, also in EUR.

Alternatively, if the box to preview the fee in fiat currency would alter too much the design of the screen, you may show it as a tooltip, mouse over the fee. (I'd prefer a box, personally. Clearer).

Thanks for considering this, cheers

**Comment by janhn** [comment]
@firepol see #2838, #3098; seems to be in the works in some form.

**Comment by SomberNight** [comment]
Closing in favour of https://github.com/spesmilo/electrum/issues/2838
