### ISSUE TITLE
[Suggestion] Show a progress bar for header download.

### ISSUE THREAD

**Issue by cluelessperson** [spesmilo/electrum#3473]
I've seen numerous complaints, and went to verify myself.
On slow connections, ~30MB of blockchain headers may take a few minutes to download.  In the meantime, users are left confused as there's no real indication anything is happening in Electrum.

This leads to them thinking "it's not working"

I don't have time to make this right now, I have to finish up my history paper. BAD.

**Comment by gits7r** [comment]
This would be nice, considering the blockchain_headers file size will continue to go up, to the point where we'll have to add a checkpoint. Important to enable it on Android version also.

**Comment by ecdsa** [comment]
irrelevant now
