### ISSUE TITLE
lost btc

### ISSUE THREAD

**Issue by porosatan** [spesmilo/electrum#3474]
I was trying to send 0.012 btc to a wallet, Electrum sent 0.0089 btc and charged me a 0.004 fee. Why?

https://blockchain.info/address/12pSLMUV8kr4bQAugNav7Qr35gvg5uK78t

**Comment by AbdussamadA** [comment]
I don't see any 0.0089 outputs in that link. Can you provide the correct tx id please?

**Comment by SomberNight** [comment]
@AbdussamadA 
The total output of c56f8e8c190719dd5f34756c8c991438662f8f94b15c85bf019b08c78d3fe92f is 0.00896358 BTC -- maybe that is what he meant.

**Comment by porosatan** [comment]
Yes that is the right id. Which confuses me as I was trying to send .012
btc. It only sent that but my balance went to 0.

**Comment by ecdsa** [comment]
closing; not usable
