### ISSUE TITLE
Replace checksum ".asc" of files with something popular

### ISSUE THREAD

**Issue by AngelTs** [spesmilo/electrum#3475]
CRC, MD5, SHA1-2-3-5, SHA3-2-3-5

**Comment by SomberNight** [comment]
That's an apples to oranges comparison. The .asc file is a gpg signature, and it uses a hash function under the hood.
Read e.g. [this stackoverflow question](https://stackoverflow.com/questions/7828053/hashing-vs-signing-binaries)

**Comment by dabura667** [comment]
.asc is not a checksum, it’s a signature.

Checksums are useless when trying to protect from malware. If I can replace the exe file, I can replace the checksum file with the checksums of my malware exe just as easily.

Thomas’s private key was used to sign the exe. Only Thomas knows the private key. You can verify it with his public key.

How do you know his public key?

You can download from github, electrum.org, and many keyservers. Compare them, if you need, and import into your gpg program to verify the signature.

**Comment by AngelTs** [comment]
So you say Thomas cannot be corrupted? Or to replace exe is less difficult than to buy Thomas?

**Comment by SomberNight** [comment]
Your original suggestion would have been horribly insecure if implemented, as described above.
We're currently using a far more secure solution, which has only one weak point, ThomasV.
Now you started complaining how what we are using is not secure enough... Do you see the flaw in that logic?

Build the binaries from source yourself, if you don't trust him.

Anyway, there is work currently underway that would make the binary builds deterministic and reduce ThomasV as a weak point. Deterministic builds with signatures is also what e.g. Bitcoin Core does.

**Comment by AngelTs** [comment]
Why to make thinsg easy when we can make them harder than the f..k

**Comment by ecdsa** [comment]
as @SomberNight said, what you propose is not secure at all.

We will soon have deterministic builds, we are working on that.

**Comment by dabura667** [comment]
One possible way to make things easier for people is to host binaries on keybase.pub via the keybase client.

Then if users open the keybase.pub folder that is associated with your pgp key they can know that it was signed by your device key.
