### ISSUE TITLE
Can't restore a wallet. Private key doesn't work on latest version, seed never worked

### ISSUE THREAD

**Issue by asartem** [spesmilo/electrum#3476]
Scenario 1
1. Download app v 3.0.2
2. Try to restore wallet using private key.
3-a. Enter correct key.
3-b. Enter correct seed form Jaxx wallet

Expected: Button next is enabled or reason error message should be shown
Actual: Button next is disabled. No error message.

Scenario 2.
1. Download app v 2.9.3
2. Try to restore wallet using seed.
3. Enter correct seed form Jaxx wallet

Expected: Button next is enabled or reason error message should be shown
Actual: Button next is disabled. No error message. 
In 2.9.3 restore from PK works fine for same PK.
Electrum created public key work ok. Electurm created private key also doesn't work.

**Comment by cluelessperson** [comment]
Come chat: http://webchat.freenode.net/?channels=electrum

**Comment by SomberNight** [comment]
As for the seed words:
Is it a BIP39 seed? In that case make sure you've clicked `Options`>`BIP39 seed`.

Re the private key:
Is it an individual private key? What's the first character, and how many characters are there?

**Comment by HardCorePawn** [comment]
Steps for importing individual (WIF) private keys changed in v3. In v3, the "standard wallet -> use public or private keys" now accepts xpubs or xprvs ONLY. It does NOT accept WIF keys.

So, in v2.9.3, you used:
File -> New\Restore -> Standard Wallet -> Use public or private keys

in v3 you need to use:
File ->New\Restore -> Import Bitcoin Address or private keys
