### ISSUE TITLE
the transaction was rejected by network rules \n\n64:too-long-mempol chain

### ISSUE THREAD

**Issue by bitbit55** [spesmilo/electrum#3479]
I have unconfirmed income transaction 
Id: 
e543eab2d9737a7f2bba9db3287c52c559048d9a0bdad4e3b795d74265610f36
When i try  **CPFP** (child pays for parent) option  this error :
http://uploads.im/ElI4H.jpg

Electrum ver 3.0.2

**Comment by ecdsa** [comment]
closing: this is not an electrum bug.
