### ISSUE TITLE
Would it be possible for Electrum to implement a system to have a "Complete transparency" status?

### ISSUE THREAD

**Issue by danielocdh** [spesmilo/electrum#3481]
I'm referring to the status shown on https://bitcoin.org/en/wallets/desktop/windows/electrum/ you can click the current status "Basic transparency" to get more info on this.
Bitcoin core https://bitcoin.org/en/wallets/desktop/windows/bitcoincore/ and bitcoin knots have a different status "Complete transparency"
It would be great if Electrum could achieve the complete transparency status mainly because it is the best wallet and it can work without a full synchronization.

I know people working on this have put a lot of effort and I don't mean to offend or not be trusting of anyone, but we all are humans after all and anyone can make a mistake.

**Comment by ecdsa** [comment]
we are working on deterministic builds
