### ISSUE TITLE
Sync issue in case of using custom seed extension

### ISSUE THREAD

**Issue by vvitkovsky** [spesmilo/electrum#3483]
Hello

I have found an issue with sync android and windows wallets. scenario:
- create windows wallet, set seed extension
- open android wallet, try to restore using current seed
- android doesn't ask seed extension and simple create new wallet

In this case android version should ask for seed extension, because it was added in original wallet.

Best regards, 
Victor

**Comment by ecdsa** [comment]
tap on the white area to get access to the extension option
