### ISSUE TITLE
GUI - core dump in Sweep private keys when pressing Address button

### ISSUE THREAD

**Issue by winch** [spesmilo/electrum#3486]
Under linux with a watching-only wallet with a single address.

In the "Sweep private keys" window (Wallet -> Private keys -> Sweep)
Both "Enter private keys:" and "Address" textboxes are blank.
Clicking the Address button results in a core dump.

^[[ATraceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/electrum_gui/qt/util.py", line 308, in func
    i = addresses.index(str(address_e.text())) + 1
ValueError: '' is not in list
Aborted (core dumped)

**Comment by SomberNight** [comment]
Thanks. I can reproduce.
