### ISSUE TITLE
electrum generating address stuck

### ISSUE THREAD

**Issue by TonyStark** [spesmilo/electrum#3499]
hi
i downloaded latest electrum in linux (3.0.2) then started and entered passphrase then it stuck on electrum generating address window
then i kill electrum process and then restart electrum so it cant connect any server
getting ```Not Connected``` and red circle on UI
also it eat my network bandwidth too...
and found 10-15 BTC address in my account too
![screenshot_2017-12-11_21-41-11](https://user-images.githubusercontent.com/5529450/33840891-3191a6b2-debc-11e7-90d0-66c79fa3e55c.png)

**Comment by AbdussamadA** [comment]
It's downloading the block headers. That's about 40MB. Once it's done that it'll show your balance. This delay is only there the first time you run electrum so just wait it out.
