### ISSUE TITLE
Hello. I ask for help. The transaction was canceled but the money was not returned. hang as decommissioned

### ISSUE THREAD

**Issue by alexon009** [spesmilo/electrum#3503]
Hello. I ask for help. The transaction was canceled but the money was not returned. hang as decommissioned

https://btc.com/0f59a469f47776cd154fb220e04d52f3bd28d64b9b91c27048cfd46564099e2d

**Comment by bauerj** [comment]
Give it a few days, the transaction will be dropped eventually.

You can also raise the fee or create a CPFP transaction if you want to speed things up.

**Comment by alexon009** [comment]
when will they return my money back?

**Comment by bauerj** [comment]
You still have your coins.

**Comment by alexon009** [comment]
they were not written off and wrote that it was not confirmed

**Comment by AbdussamadA** [comment]
Try these steps: https://bitcointalk.org/index.php?topic=1916963.msg19015496#msg19015496

**Comment by alexon009** [comment]
and money will be returned to me?

**Comment by AbdussamadA** [comment]
no the transaction will be confirmed if you bump the fee using cpfp.

**Comment by alexon009** [comment]
understood nothing. I did not receive any commission

**Comment by ecdsa** [comment]
closing: this question is about Bitcoin, not about Electrum

**Comment by alexon009** [comment]
all the same I do not understand please tell me why they write a remote double expense. but they did not return the money to me. will they be returned?

**Comment by alexon009** [comment]
https://btc.com/2202459b42dda358fc1f1b077dfae6625aa9ed88a47436fa009ebd98399ae98e
