### ISSUE TITLE
Additional fields/data in electrum-history export: (transaction fees and fiat value)

### ISSUE THREAD

**Issue by FrancisPouliot** [spesmilo/electrum#3504]
Given the substantial rise of Transaction Fees, it is becoming unavoidable for businesses using Bitcoin to thouroughly account for the trasanctions fees, for instance when doing accounting for operational expenses. In addition, it would be a good feature to have the fiat value of Bitcoin at time of transaction for accounting purposes.

Currently there are four fields in the export:

- Transaction ID
- Confirmations
- Value
- Timestamp

I think that we should add two additional fields:

- Transaction fee
- Fiat value at time of transaction

**************************************

**Transaction fee**

I think the most relevant is "total transaction fees" and not "satoshi / byte". When exporting, it is usually for accounting purposes and the satoshi/byte metric isin't particularly useful (often used to troubleshoot but not necessarily useful retroactively, or at least not in data exports).

**Fiat value at time of transaction**

This is very useful, since a lot of electrum users (me included) need to do additional data transforms to obtain fiat value of electrum transactions. Since we already have the data directly in Electrum I see no reason why this couldn't be added as part of the export format.

I wouldn't put the fiat value of the Bitcoin amount, rather just the price of 1 Bitcoin denominated in the user's specified fiat currency. This allows them to easily calculate the fiat value of the transaction fee as well without having to do an extra operation. Otherwise we would need to have to do another operation.

**Alternative option**

Alternatively, Electrum could let users specify the export format and select what data they want in there. This is far more complicated, and I'm not sure that that many users will do an export of their transactions using electrum. I don't recommend this but if there will be changes made to the export and this is not too intensive to implement it would prevent further modifications to the export format if users can just select their own format.

**Comment by EagleTM** [comment]
The JSON export has more info such as fiat_value, indeed this should be part of the csv export if fiat is set in options.

tx fee is not part of the JSON nor CSV so this is a new feature

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/commit/436f6a4870df4411c69dbca9f2bdacd5f63ba514
and https://github.com/spesmilo/electrum/commit/5376d37c24b5d60f4e8e7423326e6a42a92e2b90

**Comment by FrancisPouliot** [comment]
@SomberNight e

**Comment by FrancisPouliot** [comment]
Thanks! This low hanging fruit will save us a lot of time can formatting issues. 🙏
