### ISSUE TITLE
hardcoded p4a.source_dir

### ISSUE THREAD

**Issue by a-klimashevsky** [spesmilo/electrum#3506]
https://github.com/a-klimashevsky/electrum/blob/b88fa2046c9263cfee4d94d695addda356c1a42e/gui/kivy/tools/buildozer.spec#L122
p4a.source_dir = /opt/python-for-android doesn't work at macOs

**Comment by ecdsa** [comment]
it is hardcoded because we use a custom version of py4a.
see https://github.com/kivy/python-for-android/pull/707
