### ISSUE TITLE
My Coinbase transaction not completing

### ISSUE THREAD

**Issue by BitBitHash** [spesmilo/electrum#3507]
I made a transaction on Monday 11th transferring a small about of Litecoin to my Electrum Wallet as a test.

Still hasn't shown up.

Transactions looks as follows on the blockchain.

![capture lt 171212](https://user-images.githubusercontent.com/34490126/33906126-db2cc212-df78-11e7-9eda-450e6419bd2f.JPG)

**Comment by SomberNight** [comment]
Electrum is for bitcoin only.

**Comment by BitBitHash** [comment]
Thank you very much, I feel very stupid. How do I get the coins back?
