### ISSUE TITLE
Electrum closes/crashes after entering password for wallet 

### ISSUE THREAD

**Issue by lqdt2540** [spesmilo/electrum#3510]
Hello,
I have windows 10 pro and my electrum wallet crashes right after entering the password.

I have read "Electrum closes/crashes after entering password for wallet #2643" and followed the recommended step to delete the config file and am still having crashing issues

**Comment by bauerj** [comment]
Can you try to restore your wallet from seed?

**Comment by lqdt2540** [comment]
I can't get to the seed screen, all I can do after deleting config is to select server then enter the wallet password

**Comment by SomberNight** [comment]
In the wizard, when it wants you to enter the password, you can change the `Wallet` field to open/create a different wallet.

**Comment by lqdt2540** [comment]
I was able to load the seed but the wallet will not synchronize.. does this normally take 5+ minutes?
<img width="833" alt="screen shot 2017-12-12 at 5 02 57 pm" src="https://user-images.githubusercontent.com/34492708/33913150-546fe976-df5e-11e7-960a-f01a37abe7b8.png">
.

**Comment by bauerj** [comment]
You should contact the developers of Electrum-VTC to find out.

**Comment by lqdt2540** [comment]
I figures it out.... in the network tab I had to go to proxy and deselect "use SSL" which is checked by default which after it loaded immediately
<img width="733" alt="screen shot 2017-12-12 at 5 05 41 pm" src="https://user-images.githubusercontent.com/34492708/33913273-b63d5c9c-df5e-11e7-99a0-e16cdc489a13.png">

Thanks to you all for the quick replies!
