### ISSUE TITLE
low fee

### ISSUE THREAD

**Issue by sk1pcsgo** [spesmilo/electrum#3511]
Hi,i made a transaction with 0.011btc with fee 0.000192 (last time 15day's before it was work just fine) as was listed in recomended,but now my transaction stay as "low fee" and i dont know what to do with it.
I now know about replace-by-fee but in time when i was make transaction i was not know any other stuff more then just send btc and place recomended fee.

so my question is:there any possible way to get btc back,or it just imposible untill it not will be finished if fee drop down back or canceled by blockchain?because i send my btc to exchange site for get real money,and thay politic whery bad with this (on site they say "if your transaction dont finish in 7day we will ban your ip and transaction")

**Comment by SomberNight** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

If there is a change output, you can try to do a CPFP.

Anyway, GitHub is for development and your problem is basically a support request, so I'm closing this.
