### ISSUE TITLE
Low fee problem on the transaction.

### ISSUE THREAD

**Issue by Samual001** [spesmilo/electrum#3515]
I made low fee on my transaction, so it can't fall into the block already 2 days. My question: does electrum cancel transaction by overtime in 72 hours and what can I do if not? My version of wallet 2.7.12.

**Comment by SomberNight** [comment]
Please upgrade to the latest version. If you had done it before sending that transaction, you would now have more options.
Do it now regardless, if there is a change output in the tx, you might be able to do CPFP.

http://docs.electrum.org/en/latest/faq.html?highlight=unconfirmed#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
