### ISSUE TITLE
[Android] When user really really wishes to use his own keyboard

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3519]
When user really really wishes to use his own keyboard, there should be a small check box available to allow him to do it. Sure you could print a little message reminding him that most of the things he could do could even be done better with the built-in keyboard. However you must remember some users are 60 year old computer professionals and being denied to use their own favorite keyboard is treating them like 10 year olds.

**Comment by ecdsa** [comment]
external keyboards are insecure
