### ISSUE TITLE
Demora de pago

### ISSUE THREAD

**Issue by Leondj90** [spesmilo/electrum#3525]
Buenas me dirijo a ustedes para preguntarles cuanto el el tiempo estimado para la confirmación de pago cuando el fee es el mínimo tengo una semana esperando en otra cartea el pago desde electrum hace poco quise ver como va el envío y por sorpresa me devolvieron el monto pero en la otra cartea (que no es electrum) me dice que aun esta pendiente el pago, pero tuve que realizar nuevamente el envío desde electrum y han pasado 24 horas y nada que me llega el pago a la otra cartera en la que quiero recibir, esto es lo que me dice en la transacción de envío desde electrum  Replaceable con un aviso amarivo de un triangulo el cual no se que signifique eso y mas abajo me dice que aun no ha sido confirmado, cuanto tiempo se demora el envío cuando la transacción es de fee bajo?¿

**Comment by AbdussamadA** [comment]
see this: https://github.com/spesmilo/electrum/issues/3524#issuecomment-351714053

**Comment by SomberNight** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

**Comment by Leondj90** [comment]
Wednesday, December 6th 2017, 21:03:00 -04:00 esa es la fecha desde que envie 0.00034766 BTC para recivir 0.00029006 BTC me han cobrado 0.00005760 BTC de fee y aun así han pasado 9 días y aun no llega el envío a la otra cartera, porque tanta demora para recivir tal cantidad
