### ISSUE TITLE
Minor bug in GUI "Show Fiat balance for addresses"

### ISSUE THREAD

**Issue by Gatulibu** [spesmilo/electrum#3526]
With the option "Show Fiat balance for addresses" enabled:

In the Addresses tab the label "\<currency symbol> Balance" isn't updated if the Fiat currency is switched in the preferences until Electrum is restarted.

Tested with Electrum 3.0.3 Windows Portable (W7-64bit)

**Comment by SomberNight** [comment]
Confirmed.
Also, only the headers are stale, the amounts get updated, which can get very confusing.
