### ISSUE TITLE
Improvement request: Improve address filter + Add Address button in send

### ISSUE THREAD

**Issue by kristian** [spesmilo/electrum#3531]
As an improvment of the "Spend from" functionallity in the Addresses / Coins tab, I would love to see a "Spend From Multiple Addresses" functionallity in the Send tab, to select more than one addresses to send from. It would be way more convinient if I could add a address in the "Send" UI directly, instead of juming back and forth.

Additionally a "Funded or Unused" Filter would be exactly what I would like to see in the Addresses tab, these are the addresses I am interested the most (because I will either send from them, or receive coins on them).

**Comment by SomberNight** [comment]
> I am currently unable to spend from two addresses, in case one is a Receiving and one is a Change address

This point is a duplicate of https://github.com/spesmilo/electrum/issues/3356
As mentioned there, you can choose from the `Coins` tab.

**Comment by kristian** [comment]
@SomberNight thanks for pointing it out. I adapted my original feature request.

**Comment by ecdsa** [comment]
looks like the current GUI has those features
