### ISSUE TITLE
Ledger nano: Firmware too old for Segwit support 

### ISSUE THREAD

**Issue by romanornr** [spesmilo/electrum#3532]
I tried to make a wallet by using my hardware wallet. I received the error

```Firmware too old for Segwit support.
Please update at https://www.ledgerwallet.com
```

![screenshot from 2017-12-16 13-47-16](https://user-images.githubusercontent.com/6548898/34070527-5ad2a120-e268-11e7-925d-577352806a87.png)

But my ledger is using the latest firmware 1.3.1

**Comment by bauerj** [comment]
Does that appear after you chose to create a segwit wallet?

**Comment by romanornr** [comment]
After using this path ```m/49'/0'/0'````

![screenshot from 2017-12-16 14-24-11](https://user-images.githubusercontent.com/6548898/34070833-d1fbdd08-e26c-11e7-9cdd-be9411a0e6ab.png)

**Comment by bauerj** [comment]
Can you try upgrading the Ledger Python bindings?



    python3 -m pip install btchip-python --upgrade

**Comment by SomberNight** [comment]
Please upgrade the Bitcoin app on your ledger.
I think that will fix it, and if it does, maybe we should update that text.

**Comment by romanornr** [comment]
Thanks I tied ```python3 -m pip install btchip-python --upgrade``` and I removed and reinstalled the Bitcoin Ledger app. That worked ! 

I think this issue can be closed

**Comment by SomberNight** [comment]
Ok... but which one fixed it? :P

**Comment by misternils** [comment]
Had this problem is Electrum 3.0.5 on windows, told me to update my firmware (was up to date)
Updated the bitcoin app as described and it solved the issue.

Maybe the Error message could be more specific (it wasn't the firmware)?

**Comment by SomberNight** [comment]
The commit that changed the message was not in the 3.0.x branch, so it isn't in 3.0.5; but I cherry-picked it now: https://github.com/spesmilo/electrum/commit/d76f36df70e8fb970963e30dac56fe5ba5336e6d
It should be in the next release.
