### ISSUE TITLE
[scam website] Bitcoins stolen on electrum wallet

### ISSUE THREAD

**Issue by NikolayLe** [spesmilo/electrum#3534]
Thes same just happened to me !!!! Don't use Electrum for a while.

My money were stolen to this address: https://blockchain.info/address/144BdLLSifbZJEmqnHy8i1QkRdrxxHeFf3

Ok, maybe I have to explain what just happened with me -

I used electrum-2.9.3 to send some small amount 0.015 to 149xne93ppwQLww733hNnGmFqj51rNPjBC

I've checked all (sum, fee etc) all was correct but money were sent also to 144BdLLSifbZJEmqnHy8i1QkRdrxxHeFf3

see https://btc.com/ebdd24ff41f92aeef948133e788487e4ce1019eae85949c6be6455e27fbb38cf

I downloaded Electrum from OFFICIAL SITE https://www.electrumsource.org/#download for Windows Standalone.

And used cold storage in my wallet.

I'm shocked.

**Comment by SomberNight** [comment]
The official site is https://electrum.org/

The site you linked to is **NOT owned** by this project. They **might be hosting malware**.

You should always check the GPG signature before running any binary. The correct fingerprint for ThomasV's key is `6694 D8DE 7BE8 EE56 31BE D950 2BD5 824B 7F94 70E6`.

> And used cold storage in my wallet

I'm interested in this point. Have you not used the binary on an online machine with your wallet at any time? In that case have you used that binary to generate the wallet seed?

**Comment by ecdsa** [comment]
@EagleTM please check if we can report this website

**Comment by ecdsa** [comment]
@NikolayLe can you add some information on how you landed on that website? was it a Google Ad?

**Comment by NikolayLe** [comment]
Ok, sorry guys, I'm stupid. And I'm even going to create a site with such domain and my story :)

Ok, what happened. I sent my bitcoins as usual, and everything was ok with my balance in my wallet (it looks like here I used the correct Electrum from correct site), but then I decided to check my balance just in one address (I used to work with Multibit) in read mode and found that this address is almost empty. 

I started to panic (and found only later then my bitcoins were sent to CHANGE ADDRESS and everything was ok) and decided to download another wallet on another pc, and downloaded it from https://www.electrumsource.org/#download (using Google search and Google Ad) and entered my seed.

So now my bitcoins are really stollen and are in this wallet - 1FNuV2KRJAooRARtALUubcC15TuaVXqtkF

Sorry, my big stupid mistake and please implement change request - disable that checkbox "Use change address" by default and when enabling please add some explanation.

Sorry, thanks.
