### ISSUE TITLE
Does not run on airgapped machine

### ISSUE THREAD

**Issue by SlightlyPregnant** [spesmilo/electrum#3540]
I have an air gapped machine running Mint 18.1, Electrum 2.9.3 runs fine.

No 3.0.* version of Electrum will run (./electrum or python3 electrum), all throw up this: Error: Could not import PyQt5 on Linux systems, you may try 'sudo apt-get install python3-pyqt5'

Electrum readme says:

If you downloaded the official package (tar.gz), you can run
Electrum from its root directory, without installing it on your
system; all the python dependencies are included in the 'packages'
directory. To run Electrum from its root directory, just do::  ./electrum

Is there a way to to run 3.0.3 and still maintain an airgap?

**Comment by SomberNight** [comment]
Have you tried installing [PyQt5](https://pypi.python.org/pypi/PyQt5#downloads)?

**Comment by ecdsa** [comment]
not a bug

**Comment by SlightlyPregnant** [comment]
Have you tried installing PyQt5?

How do you do that offline?

**Comment by SomberNight** [comment]
Well how did you install Electrum offline?

**Comment by SlightlyPregnant** [comment]
Downloaded Electrum-3.0.3.tar.gz on online machine, copied to usb, transfered to offline machine. 
2.9.3 runs by open in terminal and doing ./electrum, as per the readme. No version of 3.0.* will. do this, just throws up error.
When doing an install of 3.0.3 on the online machine I notice it fetches:
libqt5clucene5, libqt5designer5, libqt5help5, libqt5test5, python3-sip, python3-pyt5
If I download these separately as .deb files on online machine from https://packages.ubuntu.com/ and try to install on offline machine I run into dependancy hell. Hey, I'm thick right, no doubt it's easy for everyone else on the planet, I'm trying to learn so any help would be very much appreciated
