### ISSUE TITLE
Ledger displays incorrect address for one-output tx to bech32

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3543]
On git master https://github.com/spesmilo/electrum/commit/3851e78454f559ec4368a4b04dd61c2b9a1f9dc1.

Using a Ledger Nano S with `btchip-python 0.1.24` on debian 9.
On Ledger, using `Bitcoin testnet (developer) 1.1.10`.

When signing a transaction with a single output (i.e. no change either), and if that output corresponds to a bech32 address (tested both p2wpkh or p2wsh), then the destination address displayed on the Ledger is actually a p2pkh address.

Tested spending from both a p2pkh (1) and also from a p2wpkh-p2sh (2) wallet.

I did not investigate if the displayed p2pkh address relates to the actual destination address in any way, but I don't think it has anything to do with the spending wallet as wallet (2) above does not have p2pkh addresses.

I'm guessing that the displayed address must correspond in some weird way to the actual destination address as the Ledger is able to correctly sign the tx.

**Comment by Raulo** [comment]
I reported this bug in the ledger app firmware github tracking  https://github.com/LedgerHQ/blue-app-btc/issues/21

No response, yet.

**Comment by SomberNight** [comment]
This has been fixed by Ledger.
