### ISSUE TITLE
Ledger sending to p2wsh: last characters are cropped on device

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3544]
On git master https://github.com/spesmilo/electrum/commit/3851e78454f559ec4368a4b04dd61c2b9a1f9dc1.

Using a Ledger Nano S with `btchip-python 0.1.24` on debian 9.
On Ledger, using `Bitcoin testnet (developer) 1.1.10`.

When signing a transaction, the Ledger displays the destination addresses for the user to confirm.
If one of these addresses is a p2wsh address, only the first 43 characters are displayed.

p2wpkh bech32 addresses are 42 characters long
p2wsh bech32 addresses are 62 characters long

See the following example, when trying to send 0.1 bitcoins on testnet:
```
tb1qgq2jk7p7pv2f4hn7rttncgm3luk3m4qdc74035xcvy90sshfqj9qlera0p
tb1qgq2jk7p7pv2f4hn7rttncgm3luk3m4qdc74035xTEST 0.1
```
The first line is what I would expect to appear on the device when confirming the address for an output.
The second line is what actually appears.

Tangentially related https://github.com/spesmilo/electrum/issues/3543

**Comment by SomberNight** [comment]
On second thought this is probably a firmware issue for Ledger, so feel free to close, but I guess it's good for reference.

**Comment by SomberNight** [comment]
Note: there is a similar issue with Trezor acknowledged in https://github.com/trezor/trezor-mcu/pull/236#issuecomment-341973341

**Comment by ecdsa** [comment]
indeed, this is not an Electrum issue
