### ISSUE TITLE
Cant load testnet wallet from public key

### ISSUE THREAD

**Issue by wuntee** [spesmilo/electrum#3547]
When running electrum in testnet mode, it is not possible to create a wallet from a master public key. I presume there is validation for the string starting with `xpub/ypub/zpub` however testnet starts with tpub. Note in the screenshot you can not click "Next."

![image](https://user-images.githubusercontent.com/794378/34086347-f50819fe-e34f-11e7-9d4f-6f058717d33f.png)

**Comment by SomberNight** [comment]
This is expected, Electrum 3.0 deprecated tpubs.
https://github.com/spesmilo/electrum/blob/b4e43754e0f60d8438b5fd412de816a466344401/RELEASE-NOTES#L67-L68
You should restore the wallet from seed using 3.0+ and see the xpub there; or you can manually convert if you find a tool.

Closing this, but there is related discussion in https://github.com/spesmilo/electrum/issues/3539 whether xpub/xprv version bytes should be distinct for testnet and mainnet.
