### ISSUE TITLE
the transaction was rejected by network rules n66: insufficient fee

### ISSUE THREAD

**Issue by F2206** [spesmilo/electrum#3548]
What does that mean? I wanted to increase a fee because my order is "replaceable" und everytime i try to increase it and broadcast it, i get this message. Even on the highest fee i can choose. 

What can i do?

**Comment by SomberNight** [comment]
Bitcoin nodes will only relay a replacement transaction if it pays more than the tx it replaces by at least the minimum relay fee, usually 1 sat/byte  (virtual byte, actually).

- What version of Electrum are you using? If older than 3.0.3, please update.
- What is the sat/byte fee the tx you are trying to replace is paying? (You can see inside the app if you right click the entry in the `History` tab and choose `Details`, or using a block explorer.)
- What is the "the highest fee you can choose"? Is that at the rightmost position of the fee slider? What is it in sat/byte?

Please answer above questions, but
you can work around the issue if you set the fee manually using the text input field in the `Bump Fee`  dialog. If you do this, double-check the numbers.

**Comment by F2206** [comment]
Hello,

my Version is 3.0.3

my actuall fee is 0.000407

Maximum fee is 0.0012



Von: ghost43 [mailto:notifications@github.com]
Gesendet: Montag, 18. Dezember 2017 17:26
An: spesmilo/electrum <electrum@noreply.github.com>
Cc: Fabian Hermansdorfer <f.hermansdorfer@imc-versicherungen.de>; Author <author@noreply.github.com>
Betreff: Re: [spesmilo/electrum] the transaction was rejected by network rules n66: insufficient fee (#3548)


Bitcoin nodes will only relay a replacement transaction if it pays more than the tx it replaces by at least the minimum relay fee, usually 1 sat/byte (virtual byte, actually).

  *   What version of Electrum are you using? If older than 3.0.3, please update.
  *   What is the sat/byte fee the tx you are trying to replace is paying? (You can see inside the app if you right click the entry in the History tab and choose Details, or using a block explorer.)
  *   What is the "the highest fee you can choose"? Is that at the rightmost position of the fee slider? What is it in sat/byte?

Please answer above questions, but
you can work around the issue if you set the fee manually using the text input field in the Bump Fee dialog. If you do this, double-check the numbers.

**Comment by SomberNight** [comment]
Not enough info; and also probably not a bug.

**Comment by indywidualny** [comment]
My thoughts about it although the issue is closed (Electrum 3.0.4 user here).

In fact Replace-by-fee doesn't work when you're trying to replace a low fee with a low fee. When you enable Dynamic Fees and use a suggested fee then it's possible to replace the fee.

So apparently OP tried to replace a low fee with another low fee.

> Bitcoin nodes will only relay a replacement transaction if it pays more than the tx it replaces by at least the minimum relay fee, usually 1 sat/byte (virtual byte, actually).

It's not precise then. Nodes will not relay a replacement transaction also when a fee is too low again (Dynamic Fee disabled, fee set manually below minimum Dynamic Fee threshold).
