### ISSUE TITLE
bech32 with Trezor

### ISSUE THREAD

**Issue by someone235** [spesmilo/electrum#3551]
Trezor [just implemented](https://blog.trezor.io/expanded-cryptos-cryptocurrency-support-firmware-1-6-0-3825b5853470) bech32 support for receiving address. Is there a way to use it with Electrum?

**Comment by bauerj** [comment]
Are you sure this is for receiving addresses? I thought they only support sending to bech32 addresses yet.

**Comment by SomberNight** [comment]
Not at the moment, no.

It is not clear for me whether only sending to native segwit outputs was implemented in the Trezor fw or receiving too.
See https://github.com/spesmilo/electrum/issues/2976#issuecomment-340871611

Even if the Trezor firmware (1.6.0) has full receiving support now,
1. the Trezor plugin in Electrum would need some changes to support this
2. Electrum is unlikely to expose this functionality to users until there is a bip43 purpose allocated (or similar, at least a reasonable proposal) for the respective scripts. Something like bip49 would be needed (which specifies a bip32 derivation path along which p2wpkh-p2sh scripts should be created)

**Comment by sneurlax** [comment]
So... closed?

**Comment by bauerj** [comment]
Yes, this has been merged.
