### ISSUE TITLE
BTC missing in Copay balance.

### ISSUE THREAD

**Issue by cepach** [spesmilo/electrum#3552]
I have recived some BTC but the transaction is missing un my Copay wallet. The deposit was made 2 weeks ago and so far it not figure in the balance, even though the transaction is confirmed in the blockchain.
I was recommended to use mycellium or electrum to access  to the wallet through the seed. Unfortunately my 12 words are in Spanish and mycellium and electrum do not recognize them.
I appreciate your help.

**Comment by SomberNight** [comment]
> electrum do not recognize them

It should work regardless of the language (though the checksum will not be checked).
Make sure to click `Options` and tick `BIP39 seed`.

![bip39_restore](https://user-images.githubusercontent.com/29142493/34128092-d0f989ee-e43f-11e7-9dc0-43e96b62c004.png)

**Comment by bauerj** [comment]
Did that solve your issue?

**Comment by SomberNight** [comment]
No answer; closing.
