### ISSUE TITLE
Fiat currency amounts do not update

### ISSUE THREAD

**Issue by ozzyogkush** [spesmilo/electrum#3553]
In the History tab, the fiat currency conversion amounts do not appear to be updating. The value shown is what I am seeing from a few weeks ago, not what its current value should be reflecting.

Using USD currency with data from BitcoinAverage. The other option, Winkdex, shows nothing where the conversion amount should be. 

App v3.0.3 on Android 7.0

**Comment by SomberNight** [comment]
The items in the `History` tab intentionally use historical value. They use the price on the given day.
For bookkeeping purposes, e.g. if you want to pay taxes, this is more useful behaviour.
