### ISSUE TITLE
Unchecking automatic server selection causes electrum to crash

### ISSUE THREAD

**Issue by Engelberg** [spesmilo/electrum#3556]
In Electrum 3.0.3 on Windows 10, when I clicked to uncheck the checkbox that says "Select server automatically", Electrum crashes and I get a Windows error message box that "electrum-3.0.3.exe has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."

I have tried this twice; it crashed both times.  When I restart electrum, the checkbox for "Select server automatically" is still selected.

**Comment by ecdsa** [comment]
there might be a problem with your config file. try to delete it and restart

**Comment by Engelberg** [comment]
That fixed the problem, but in the future, please warn that deleting the config file will turn off the Tor proxy.
