### ISSUE TITLE
Expired transaction not clearing

### ISSUE THREAD

**Issue by mfrost66** [spesmilo/electrum#3559]
I had someone send my wallet a low-fee transaction that eventually expired.  They eventually successfully resent the funds in a new transaction, but 3 weeks later, the expired transaction continues to show in the history as "low fee".   

It would be nice if there were a way to remove, hide, or filter the expired transactions.  It causes my balance to be "wrong".  Over time, these expired transactions will make it difficult to see the confirmed transactions.

**Comment by ZIBROU** [comment]
Hi, I have exactly the same problem on electrum, it's horrible, 12 days that I can't do anything and the transaction on the blockchain as removed/expired but still appears on my wallet as low fee. I tried CFPF but low fee too. 
"It would be nice if there were a way to remove, hide, or filter the expired transactions. It causes my balance to be "wrong""

The same problem and no one can reply me or to do smthg appropriate to call off this shitty transaction. I'm just so fed up with this situation. 10 days that it lasts.

**Comment by ZIBROU** [comment]
I send btc to someone. I'd like to call of the trnsaction but impossible. I tried everything, remove the wallet, recreate it, put seeds back, switch off internet, I already read all of it on internet, no solution.
