### ISSUE TITLE
My transactions are mysteriously disappearing and my balance is being deducting

### ISSUE THREAD

**Issue by bitcoiner23** [spesmilo/electrum#3560]
http://prntscr.com/hpq8q1
http://prntscr.com/hpq90h
https://blockchain.info/tx/14ba319c8b667fa715f8c545e39a5c7c8e1d53687f2ee279505178dce37768ee

This is the third transaction..

**Comment by SomberNight** [comment]
What is the issue here? That blockchain.info does not have the tx? Ask them.
Blocktrail for example [has it](https://www.blocktrail.com/BTC/tx/14ba319c8b667fa715f8c545e39a5c7c8e1d53687f2ee279505178dce37768ee).

**Comment by bitcoiner23** [comment]
This is the third transaction. 
The other two have vanished from my wallet completely along with the balance but they're showing up on blockchain..

**Comment by SomberNight** [comment]
> The other two have vanished from my wallet completely along with the balance but they're showing up on blockchain..

Do you mean they have "vanished" from Electrum? If they are still unconfirmed and have a very low fee, it might be that they are below the minimum fee of the electrum server you are currently connected to. Try different servers. Also, if they get confirmed, they will appear in the history.
