### ISSUE TITLE
Allow copying words from the Install Wizard

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3562]
Users may want to quote and send to their friends, or search Google for, or enter into bug reports, words from the Install Wizard. E.g., the words [press Next](https://github.com/spesmilo/electrum/issues/3561#issue-283397502)...
Therefore they should be able to do so with their mouse, instead of always using screenshots.

**Comment by ecdsa** [comment]
yeah, we need to disable screenshots on android
