### ISSUE TITLE
Do not allow the user to enter the "Send" screen of watching-only wallets

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3563]
Do not allow the user to enter the "Send" screen of watching-only wallets,
![x](https://user-images.githubusercontent.com/1230959/34187199-26c92042-e56b-11e7-9d0b-7105b88d2788.jpg)

**Comment by AbdussamadA** [comment]
This is used to create transactions for signing on an offline wallet. So it serves a purpose. Stop creating so many issues here without understanding what's going on. Use the community forums if you need help: https://electrum.org/#community

**Comment by SomberNight** [comment]
> This is used to create transactions for signing on an offline wallet
