### ISSUE TITLE
"Insufficient Fund" error

### ISSUE THREAD

**Issue by watsakanpnp** [spesmilo/electrum#3564]
I cant send any of my bitcoin. It keeps saying "Insufficient Fund". I got about 1.44mBTC. Even when I try pressing "MAX" I can only transfer 0.0mBTC with 1.44mBTC fees... WTH??!! Please help!

**Comment by ecdsa** [comment]
we are working on a better UI that will show transaction size.

**Comment by watsakanpnp** [comment]
So I can’t transfer anything until you fix it??

**Comment by ecdsa** [comment]
what we are fixing the UI so that you understand that your transaction is expensive because it has a large size.

**Comment by watsakanpnp** [comment]
I’m sorry I don’t quite understand, am I missing something here? 1.4mBTC is
a large transaction??? And why does it say the maximum transaction I can do
is 0.0mBTC with transaction fees of 1.4mBTC?? It doesn’t make sense.

**Comment by ecdsa** [comment]
sorry, but please learn about how fees work. 
this place is not user support, it is a bug tracker

**Comment by watsakanpnp** [comment]
That’s why am asking here. Because the transaction fees doesn’t make sense.
Even when i set the fees to the lowest(because i dont mind waiting). But
the problem is that it doesn’t let transfer any amount what so ever.

**Comment by ecdsa** [comment]
in your preferences enable "set fees manually"
