### ISSUE TITLE
Incorrect Balance, I have lost my money!

### ISSUE THREAD

**Issue by ripperroo01** [spesmilo/electrum#3566]
Hi team,

Can you help me solve this issue?? I have not started the program about 2 months.
After I start the program, Then it show that "Server is lagging by 4xx  blocks". 
So, I change the server to connect on the program.

Then, my wallet status is green. But! my money is synced up to July, 2017 only!
I have transaction almost every day. Can you check this ASAP. I lost my money now!!

What info you need from my end?

Thank you,
Roo

**Comment by ecdsa** [comment]
maybe you are running on an old version that predates the fork.
closing this issue, because you should upgrade your software before reporting bugs
