### ISSUE TITLE
Electron Cash 2.9.3, showing no balance

### ISSUE THREAD

**Issue by elmejorrematador** [spesmilo/electrum#3567]
Hello, if anyone can please help me I would be very grateful. 

I deposited BCH into my Electron Cash wallet, 0.04197211 BCH. On my interface it shows zero balance, but when I check on bitinfocharts.com, the balance shows for my address.

My address is: 19Gmk6JLSE4xh8G5mfYevQRa2xq1cBdn58
Is there a way to get the BCH out of this wallet and into another? I tried to just send it over, but when I enter any amount to send the Electon Cash wallet tells me "insufficient funds"

Not sure if sweeping the wallet is possible or updating to the newest version of the wallet. Afraid I may not be able to recover the balance. So I'm hoping someone can offer some insight before trying one of those methods. 

Thank you very much!

**Comment by ecdsa** [comment]
wrong repo
