### ISSUE TITLE
CANNOT SIGN, DOES NOT HAVE UNIQUE PUBLIC KEY???

### ISSUE THREAD

**Issue by yameyamo** [spesmilo/electrum#3568]
Hi,

I want to sign message, but I always get this error:

Cannot sign messages with this type of address.

Signing with an address actually means signing with the corresponding private key, and verifying with the corresponding public key. **### The address you have entered does not have a unique public key, so these operations cannot be performed.**

**Comment by ecdsa** [comment]
thats not a bug report, is it?

**Comment by yameyamo** [comment]
ecdsa, I donno. but why i can't sign a signature? can you explain?

**Comment by SomberNight** [comment]
@yameyamo You can't sign a message with a multisignature address. The operation is simply not defined.

**Comment by yameyamo** [comment]
Is there any other way to do so? not possible?
