### ISSUE TITLE
Low fee transaction

### ISSUE THREAD

**Issue by cpamachine** [spesmilo/electrum#3570]
Good day

I couldn't receive my BTC transaction almost 2 days
Its still unconfirmed due to low fee
Tell me please, how can I receive my transaction 8a9ceaca10ff164f80915ffa53d627d8905be19af22169d53bb7129a1033d90a

![image](https://user-images.githubusercontent.com/34722980/34227189-f5ea4748-e5d4-11e7-8088-de4287ce9b00.png)

**Comment by AbdussamadA** [comment]
See here: https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

and in future use the community forums not github for issues like these:  https://electrum.org/#community

**Comment by thethethe1** [comment]
Thank you very much for the advice guy, sorry for posting in the wrong place. I'll make sure to post somewhere else next time.
