### ISSUE TITLE
Command line electrum restore expects you to be connected to a network; this doesn't work for cold storage

### ISSUE THREAD

**Issue by johnconger** [spesmilo/electrum#3571]
using:
python3 electrum restore -w /var/cold/mywallet.dat --testnet xprv9y..... tries to access the network for blockchain headers
This doesn't work on a machine that is disconnected from all networks to be used for cold storage.

It should not need access to the network, especially because if this same operation is attempted through the UI, it works fine and a wallet file is created.

This seems to be a bug

**Comment by SomberNight** [comment]
Try with the `--offline` flag.

**Comment by johnconger** [comment]
Yep that did the trick.  It would be great if that switch was in the help text: python3 electrum help
Thanks for the quick reply!

**Comment by SomberNight** [comment]
> It would be great if that switch was in the help text: python3 electrum help

Not sure; maybe. It's only useful for some of the commands.

If you run `electrum help restore`, it will tell you about it.
