### ISSUE TITLE
electrum  3.03 charging unkown additional fee 

### ISSUE THREAD

**Issue by charleshsu168** [spesmilo/electrum#3572]
sent a txt . manually set the mining fee to 80 satoshi/byte
and in the preview windows, it showed additional fee of 0.002 btc. this is on top of the mining fee. 
so electrum is charging two fees
1. mining fee of 80 satoshi/byte that i manually set
2. unexplained additional fee of 0.002 btc.
wtf is going on? please explain the additional fee

**Comment by SomberNight** [comment]
I'm guessing this is a wallet using Two-Factor Authentication?
This was explained when you created the wallet, in the wizard.
https://api.trustedcoin.com/#/electrum-help

**Comment by charleshsu168** [comment]
oh damn...you are right...
i wish this is explained when the 2fa wallet is created. i had no idea it would cost this high..

**Comment by charleshsu168** [comment]
and electrum should include explanation for the additional fee in the preview window

**Comment by SomberNight** [comment]
> i wish this is explained when the 2fa wallet is created

![wizard_explanation](https://user-images.githubusercontent.com/29142493/34229376-5629d750-e5d4-11e7-9d12-930b552ea4d6.jpg)
![trustedcoin_2fa_fees](https://user-images.githubusercontent.com/29142493/34229383-589fb310-e5d4-11e7-887a-5c3f935eb876.PNG)

**Comment by charleshsu168** [comment]
thanks. i guess i wasn't paying attention.
