### ISSUE TITLE
not correct payment for transaction

### ISSUE THREAD

**Issue by owner779** [spesmilo/electrum#3577]
I paid for 2 block confirmation, but in software I see 25 blocks left!
It happened second time - each time I send 1 BTC and put big comission!

**Comment by ysangkok** [comment]
The estimation is incorrect when the network is very congested. This is a minor issue the fee can still be bumped. We are working on making the estimation more correct, but we have to make sure the new method can not be attacked by miners who would want to manipulate users into paying higher and higher fees.

See http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
