### ISSUE TITLE
Paid high fee (1mBTC), Still Unconfirmed after 8 hours

### ISSUE THREAD

**Issue by bballproz** [spesmilo/electrum#3580]
As the title says, I paid a high fee to send some BTC, so I could get it faster, but now it has been taking a very long time. Should I have paid a higher fee, or is there just a heavy load of transactions right now?

**Comment by SomberNight** [comment]
What really matters is the fee/byte you pay, not the absolute value of the fee.

> is there just a heavy load of transactions right now?

Yes, there are currently unusually many unconfirmed txns, paying unusually high fees.
https://dedi.jochen-hoenicke.de/queue/more/#24h

If you want faster confirmation, you need to pay higher fees; see:
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

**Comment by bballproz** [comment]
Alright, thank you for the links
