### ISSUE TITLE
Payments disappearing from wallet but balance not returning

### ISSUE THREAD

**Issue by bitcoiner23** [spesmilo/electrum#3584]
My payments are either being rejected when I increase the fee or they are completely disappearing from my wallet without the coins returning to the original address. 

here are a few examples;

https://btc.com/14ba319c8b667fa715f8c545e39a5c7c8e1d53687f2ee279505178dce37768ee
https://btc.com/333a39d80eb0b1592880abeddf16016d6875a557dfe64926a093beba2d0dbedd
https://blockchain.info/tx/a81a8436e97d052c12fe1e8efae8f97960ca9f380e3e91c895058f95eeece540?show_adv=true
https://btc.com/19cb7dd1621d868baec46c1a7ab4e8f728ec9369d185d5f6e387fdcd66b23a4d
https://live.blockcypher.com/btc/tx/14ba319c8b667fa715f8c545e39a5c7c8e1d53687f2ee279505178dce37768ee/

And neither of them have returned to my wallet. 
There were others too made by my wallet, but I can't find them because they aren't on the wallet any more!

I've lost a lot of coins in this issue. I'm using desktop electrum 3.0.1

**Comment by bitcoiner23** [comment]
my wallet:
http://prntscr.com/hr5alb
http://prntscr.com/hr5b0d

**Comment by MudWar** [comment]
I have the same issue. Please re-assure us that they are still in process of being confirmed. I had sent enough BTC to the NXT wallet when it was at $0.85 to purchase 200, so approximately $170 worth of BTC was the transaction previous to the one labelled "Blockchain". Thank you
![capture](https://user-images.githubusercontent.com/30239655/34313141-2c51a832-e7a4-11e7-9139-a047f614c594.JPG)

**Comment by SomberNight** [comment]
There are lots of unconfirmed transactions at the moment, and nodes with default mempool sizes have their mempool full. This means they started evicting low fee transactions that can no longer fit in their mempool. There is no global mempool, every node has its own view of it.

In the `History` tab, when you are connected to a server, unconfirmed transactions are only shown if that specific server has the tx in its mempool. If you connect to a server with a large mempool, it might show up, and then if you connect to a smaller mempool server, it will disappear again.

> without the coins returning to the original address

Please elaborate on this remark.

**Comment by bitcoiner23** [comment]
There are lots of unconfirmed transactions at the moment, and nodes with default mempool sizes have their mempool full. This means they started evicting low fee transactions that can no longer fit in their mempool. There is no global mempool, every node has its own view of it.

- What about these transactions?
- How do we view them in our electrum wallet?
- Are these transactions going to return?
- What's going to happen to these transactions?

As you can see from my links several of these transactions have been rejected and the bitcoins haven't returned to my wallet, what's going to happen to those transactions?

And what about the prepaid payments that has been deducted for the aforementioned transactions?

**Comment by MudWar** [comment]
@SomberNight does evicted from the mempool mean that it will still be processed eventually in a different mempool, but shall take considerably longer?

**Comment by SomberNight** [comment]
@MudWar, @bitcoiner23

Generally, once a transaction has been signed and broadcasted, it remains valid and can be included (mined) into a block forever; unless another conflicting transaction gets included in the chain.
Two transactions are conflicting if they are trying to spend the same coins (at least one of the inputs is shared).
https://github.com/spesmilo/electrum/issues/3579#issuecomment-353487856
https://github.com/spesmilo/electrum/issues/3555#issuecomment-353731603

-----

@bitcoiner23 
> How do we view them in our electrum wallet?

> If you connect to a server with a large mempool, it might show up

-----

> And what about the prepaid payments that has been deducted for the aforementioned transactions?

If you mean 2fa prepaid tx count, I don't know. Technically, I think, you're paying TrustedCoin to **sign** transactions, so it would be perfectly fair if all this was regarded to be out of scope.

**Comment by SomberNight** [comment]
> There are lots of unconfirmed transactions at the moment, and nodes with default mempool sizes have their mempool full. This means they started evicting low fee transactions that can no longer fit in their mempool. There is no global mempool, every node has its own view of it.

Transactions that drop out from the mempool will turn into "Local" transactions in the client now, and then can be rebroadcast; they won't just disappear (from the client).
