### ISSUE TITLE
[android] Electrum not working on Sony devices (only v2.9.3 and prior working)

### ISSUE THREAD

**Issue by darwusch** [spesmilo/electrum#3586]
This issue has been mentioned already:
https://github.com/spesmilo/electrum/issues/3213
However, I don't feel it has got enough attention which is why I post this under a different title.

Due to Kivy not working on Sony android devices (since using Python3) Electrum crashes immediately on startup.

To use my wallet on my Sony stock android phone, I have to use old Electrum version 2.9.3.

**Comment by bauerj** [comment]
Since it seems to be a bug in kivy, there is nothing we can do about it.

**Comment by darwusch** [comment]
Ofcourse there is, using Kivy with Python3 is a choice.
Why choose something which does not work on so many devices?

**Comment by bauerj** [comment]
Because Electrum is not compatible to Python 2.

**Comment by darwusch** [comment]
Electrum version 2.9.3 and prior, were working fine.

**Comment by SomberNight** [comment]
> Electrum version 2.9.3 and prior, were working fine.

Yes, but then the project migrated to Python 3. It was deemed to be too much work going forward to maintain compatibility with both Python 2 and 3 (developer resources are limited), especially as we wanted to start using Python3-specific functionality.

**Comment by darwusch** [comment]
...and leaving millions of people who can not use Electrum anymore with the current code.

**Comment by bauerj** [comment]
As of now this issue seems to be limited to two users only.

We still take it seriously but there are more important issues right now.

**Comment by darwusch** [comment]
Ofcourse it is not only 2 users. Most people just see it crash and simply use another wallet.
It's every user with these Sony phones ans maybe more.

**Comment by fdiengdoh** [comment]
Samething with my Motorola moto m with Android 7. Can't scan we code. And it just crash.

**Comment by bauerj** [comment]
@fdiengdoh Does it crash immediately on startup?

**Comment by fdiengdoh** [comment]
Not immediately but after few mins. And can't scan QR code.

**Comment by bauerj** [comment]
Then what you see is not related to this issue. Please [collect the log output](https://github.com/spesmilo/electrum/issues/3213#issuecomment-341902817) and open a separate issue.

**Comment by fdiengdoh** [comment]
just today there's a security update on my phone and then i reinstall electrum along with the barcode app and it didn't crash anymore. I'll create a new issue if there's crash but now I guess its pointless.

**Comment by fdiengdoh** [comment]
anyway I've just recreated the crash will open a new issue

**Comment by ser** [comment]
Electrum 3 is properly working on my two Sony devices, tablet Z4 and phone Z5

**Comment by bauerj** [comment]
@darwusch What about you?

**Comment by darwusch** [comment]
No, it's not fixed.
Force close immediately on devices:
Sony Xperia XA Ultra (android 7)
Sony Xperia Z5 compact (android 7)

And error "Could not load ctypes" on device:
Sony Xperia XZ1 (android 8)

**Comment by darwusch** [comment]
I don't know what android version ser uses on his Z5.
But the devices where it FC's are all rooted. Earlier developers told me that this could not be the cause, but I'm having doubts about that.

**Comment by ser** [comment]
Yes, I have not upgraded to 7 as it results in many problems with apps.

**Comment by darwusch** [comment]
So, which version of android do you use?

**Comment by ser** [comment]
6 - i don't see any practical sense with upgrading to 7, it slows down the devices, creates many compatibility problems.

**Comment by darwusch** [comment]
Ok, so we can safely assume that also the Sony Xperia Z5 has a Force Close on Android 7, because it is virtually the same as my Z5 compact.

**Comment by bauerj** [comment]
Well, If it's due to a buggy Android version, there's not really much we can do.

**Comment by darwusch** [comment]
No it is not, it is a problem with Kivy and Electrum.

**Comment by ecdsa** [comment]
@darwusch if you can identify that this is a kivy issue, why dont you report it in the kivy project?

**Comment by darwusch** [comment]
@ecdsa Because Kivy with Python3 is still experimental, so it should not be used in something important as a wallet.

Furthermore, the bugs are probably just some paths defined incorrectly, so could be fixed within Electrum.

**Comment by bauerj** [comment]
> Because Kivy with Python3 is still experimental

Is it? As far as I know it's considered stable.

> Furthermore, the bugs are probably just some paths defined incorrectly

Can you tell us what paths to change?

**Comment by darwusch** [comment]
The official website says it is Experimental:
http://python-for-android.readthedocs.io/en/latest/buildoptions/
_"Python3 support is experimental, and some of these details may change as it is improved and fully stabilised."_

No, I can not find the bug myself, you can see the syslogs I posted, both here on the Electrum github, as well as the Kivy github.

**Comment by darwusch** [comment]
Bug still present in v3.1.0.
Still force close immediately on start.

**Comment by rdymac** [comment]
This person says to have found a fix for the “SDL library not found” issue: https://github.com/kivy/python-for-android/issues/645#issuecomment-185977753

**Comment by darwusch** [comment]
This bug has been finally fixed since v3.3.0

**Comment by SomberNight** [comment]
Did you reopen by mistake?

**Comment by darwusch** [comment]
yes, it's fixed

**Comment by kjendis** [comment]
Just had this issue today on a huawei honor 6. Reinstalled electrum from Google play, same issue again

**Comment by ser** [comment]
It's 5 years old drastically modified Android called Emotion UI, it's really hard to support it :(
