### ISSUE TITLE
Transferred XVG to Wallet - No funds in wallet

### ISSUE THREAD

**Issue by ADuser927** [spesmilo/electrum#3587]
I recently transferred funds from my Binance Exchange account to my Electrum wallet. When I logged back into my wallet there were no funds to be found. The address I sent XVG to from Binance to Electrum is DTXJQj5U55RXqiGbN9e4SeC4cZ3bxZi3Js (this was the receiving address of my wallet) however the receiving address in my wallet is now DSFCZvJNMQY43frni3CQz5sxQPMiaDjosA. Am I screwed?

**Comment by bauerj** [comment]
Hey, this is only for Bitcoin, not for any altcoins.
