### ISSUE TITLE
Where is replace by fee option in send tab ?

### ISSUE THREAD

**Issue by thieuanh1995hn** [spesmilo/electrum#3588]
I have set the RBF in preference up but on send tab i can not see the option RBF . How can i double send my btc to resolve unconfirm transaction?

**Comment by SomberNight** [comment]
The RBF checkbox appears after you already filled out most of the details of the txn; when it can already give you a fee estimate.
![send_tab_303](https://user-images.githubusercontent.com/29142493/34323031-ec23cde6-e837-11e7-813f-87bcacccba89.png)
