### ISSUE TITLE
Help with wallet and Electrum

### ISSUE THREAD

**Issue by petermarkjansson** [spesmilo/electrum#3590]
Just set up an electrum account and then sent Verge to it - when I went back to see if it had successfully transferred my electrum account / wallet was staying offline -- I reloaded electrum and restored account using my seeds and it now stays online but still have not seen the transfer of my Verge into the wallet -- Is there a way to check on the transaction to see if it is still transferring (after 3 hours) I am having trouble finding out how to track down the transfer from the electrum side - I know the details that were sent from Binance - thanks for any input on this --

**Comment by SomberNight** [comment]
> then sent Verge to it

Electrum is for Bitcoin only.
