### ISSUE TITLE
Words cut in half on Android 

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3594]
![20171224_170405_rmscr](https://user-images.githubusercontent.com/1230959/34325464-2d2fdb78-e8cd-11e7-9d60-f23353a74a83.jpg)
Not a scrolling problem...

**Comment by neocogent** [comment]
Can confirm on Samsung Galaxy J7 Pro. Looks like maybe related to margin not accounted for in layout. I think I saw this in other places too.
