### ISSUE TITLE
missing transaction in wallet

### ISSUE THREAD

**Issue by jamesburnham111** [spesmilo/electrum#3596]
ac7797ac41b8591d4e454c925b91f87932e2c4adbbe6c2fc014a9a0864051a0e

is not showing in my history
I placed this 3 days ago

**Comment by bauerj** [comment]
No, that transaction is from May.

**Comment by SomberNight** [comment]
Probably too low fee and given server does not have it in its mempool; see e.g. https://github.com/spesmilo/electrum/issues/3584#issuecomment-353706201

Also, as already said, that's not the correct txid.
