### ISSUE TITLE
electrum 3.0.3 does not recognize hardwallets

### ISSUE THREAD

**Issue by bsbits** [spesmilo/electrum#3597]
Hello,

I have downloaded 2 versions of electrum
- electrum 2.8.2 : it works fine with KeepKey and Ledger Nano S

- electrum 3.0.3 : it asks me to install keekey with Python 3 (can't find how) and does not recognize Nano Ledger S at all.

I want to use Segwit with Nano Ledger S but this seems not possible.

**Comment by SomberNight** [comment]
What OS?

**Comment by tariq235** [comment]
@bsbits  Do you got any success ? I have ordered Ledger Nano s and it will arrive in 2 days. I want to sweep my non segwit bitcoin paper wallet to electrum 3.0.3 and transfer bitcoin to segwit ledger address.

**Comment by SomberNight** [comment]
@tariq235 When I posted the above comment, just to be sure, I've tested using both KeepKey and Ledger, and they worked. In general, Electrum supports these.
