### ISSUE TITLE
Request: sortable columns

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#3598]
Click column header, to get alpha, numeric, amount, date sorts. Especially on coin control tab for block height, so we can see which were there before various forks/snapshots.

ETA: Or maybe not needed on block height, since it looks like they are fixed sorted oldest to latest with the latest TX to an address bumping its group up (down) in the list.

**Comment by KyrosKrane** [comment]
This feature would be notably useful when trying to find a past transaction by label. Similarly, in a watch-only wallet I maintain that tracks my paper wallets, it would be useful to sort by label or amount so as to track which wallet has what.

I'd add that this applies to the History, Coins, and Addresses tabs, as all three contain data worth sorting by.

**Comment by ecdsa** [comment]
see #3787
