### ISSUE TITLE
Unable to sweep non segwit paper wallet in Electrum 3.0.3

### ISSUE THREAD

**Issue by tariq235** [spesmilo/electrum#3600]
Sweep button is disabled. It's only getting enabled if I enter enter segwit paper wallet. What i should do now ?

**Comment by SomberNight** [comment]
The `Sweep` button (in the `Sweep private keys`) window gets enabled if the private keys in the large text box are valid keys.

Are you sure that the key you are trying to sweep from is a valid Bitcoin private key? Is it in WIF format? (How many characters and what is the first character?)

**Comment by tariq235** [comment]
First character is 6. It's BIP38 encrypted.
- Do i need convert it in WIF format ?
- Ledger Nano S have now segwit support. I do not have small amount in paper wallet. Is it safe to use Electrum 3.0.3 to sweep paper wallet and send it to ledger nano s segwit address ?

**Comment by AbdussamadA** [comment]
> Do i need convert it in WIF format ?

Yes. Decrypt it via wallet details tab of bitaddress.org

>Ledger Nano S have now segwit support. I do not have small amount in paper wallet. Is it safe to use Electrum 3.0.3 to sweep paper wallet and send it to ledger nano s segwit address ?

Yes you can do that
