### ISSUE TITLE
Digital Bitbox is not recognized on Electrum 3.03

### ISSUE THREAD

**Issue by BolachaICMC** [spesmilo/electrum#3603]
I'm using Ubuntu 17.10 and Electrum 3.03, tried to use the Digital Bitbox, but it says no hardware wallet is connected

**Comment by SomberNight** [comment]
Have you configured udev rules? https://digitalbitbox.com/start_linux

**Comment by BolachaICMC** [comment]
I have, and it works on the Bitbox wallet, just not on Electrum

**Comment by SomberNight** [comment]
Ok, well it works for me on Debian 9. I'll test Ubuntu 17.10 soon...
Could you please try starting Electrum with the `-v` flag, and upload logs somewhere?

**Comment by BolachaICMC** [comment]
How do I upload logs?

**Comment by SomberNight** [comment]
Just copy-paste them here in a comment I guess, that's the easiest.

**Comment by BolachaICMC** [comment]
bolacha@bolacha-Inspiron-5548:/usr/local/bin$ ./electrum -v
[SimpleConfig] electrum directory /home/bolacha/.electrum
[get_server] [Errno 111] Connection refused
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0036
[Network] blockchains dict_keys([0])
[Network] starting network
[Network] connecting to electrum.akinbo.org:50002:s as new interface
[FxThread] using exchange Coinbase
[Coinbase] getting fx quotes for USD
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/My_Bit_wallet
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/My_Bit_wallet
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/My_Bit_wallet
[Coinbase] received fx quotes
[electrum.leblancnet.us] SSL certificate signed by CA
[electrum.leblancnet.us] connected
[helicarrier.bauerj.eu] connected
[ELECTRUMX.not.fyi] connected
[electrumx.westeurope.cloudapp.azure.com] connected
[node.xbt.eu] connected
[Network] no height for main interface
[Network] switching to electrum.leblancnet.us:50002:s
[Network] sending subscriptions to electrum.leblancnet.us:50002:s 0 0
[electrum.festivaldelhumor.org] connected
[electrum.antumbra.se] connected
[noserver4u.de] connected
[electrum.akinbo.org] connected
[Network] fee_estimates[25] 357149
[Network] fee_estimates[10] 645960
[Network] fee_estimates[5] 645960
[Network] fee_estimates[2] 955491
[Network] relayfee 1000
[ecdsa.net] timeout
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[mdw.ddns.net] saving certificate
[mdw.ddns.net] connected
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/b
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bi
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bit
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bitb
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bitbo
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bitbox
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bitbo
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bitb
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bit
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/bi
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/b
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/a
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/ab
[WalletStorage] wallet path /home/bolacha/.electrum/wallets/abc
[Plugins] loaded digitalbitbox
[Plugins] loaded keepkey
[Plugins] loaded ledger
[Plugins] loaded trezor
[DeviceMgr] error digitalbitbox
[DeviceMgr] error keepkey
[DeviceMgr] error ledger
[DeviceMgr] error trezor
[Coinbase] getting fx quotes for USD
[Coinbase] received fx quotes
[DeviceMgr] error digitalbitbox
[DeviceMgr] error keepkey
[DeviceMgr] error ledger
[DeviceMgr] error trezor
[Daemon] shutting down network
[Network] stopping network
[Network] stopped
[Daemon] stopped
[Plugins] stopped
bolacha@bolacha-Inspiron-5548:/usr/local/bin$

**Comment by BolachaICMC** [comment]
Is that it? Sorry, I'm not sure what logs are

**Comment by SomberNight** [comment]
```
[Plugins] loaded digitalbitbox
[Plugins] loaded keepkey
[Plugins] loaded ledger
[Plugins] loaded trezor
[DeviceMgr] error digitalbitbox
[DeviceMgr] error keepkey
[DeviceMgr] error ledger
[DeviceMgr] error trezor
```
^ these are the interesting lines.

Please try installing `libusb-1.0-0-dev` and `libudev-dev` using apt-get.

These are btw mentioned in https://github.com/digitalbitbox/dbb-app#linux-ubuntu-1504

If it's still not working, try
```
python3 -m pip install hidapi
```

Report back which of these was needed. :)

**Comment by BolachaICMC** [comment]
I installed all of them. It still wasn't working, but after I restarted the notebook, it is. So I'm not sure if all were needed. Thanks for the help
