### ISSUE TITLE
Electrum not transferring bitcoin

### ISSUE THREAD

**Issue by thethethe1** [spesmilo/electrum#3605]
Hey everyone, thanks in advance for any potential help.

I've been trying to transfer Bitcoin from my Electrum to another account, I've done this multiple time times in the past with no problems, however, this time I've confirmed the send from my Electrum (I have sufficient funds) but it's been 36 hours now and it's still saying 0 confirmations on my Electrum account, and I'm yet to receive anything in my second wallet. It's worth noting that my second wallet acknowledges that there's incoming, unconfirmed Bitcoin, but I'm yet to receive anything.

If anyone has any idea as to why it may be taking so long, or have a potential solution, then I would be greatly appreciative.

Thank you - Hope you all had a wonderful Christmas 

T

**Comment by AbdussamadA** [comment]
see here: https://github.com/spesmilo/electrum/issues/3570#issuecomment-353174927
