### ISSUE TITLE
Feature proposal: Semi-full node mode? 

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#3607]
I've been thinking about ways to make it easier for people to get almost the full benefit of a full node without all the cost. What if we added an option to electrum to download a UTXO set and verify that set using SPV, then validate new blocks (without storing them) and keeping its UTXO set up to date? This should require less than 100MB of disk space and not a whole lot of bandwidth if we keep retransmissions down (or simply leave them out). This would have the additional benefit of keeping load on electrum servers down (I think..) or even allow people's electrum clients to *be* electrum servers. Thoughts?

**Comment by TheButterZone** [comment]
Thumbs up.

**Comment by ecdsa** [comment]
that is not a fearture proposal, it is a completely different project.
that is out of scope for me.

**Comment by fresheneesz** [comment]
@ecdsa Could this be made as a module that could be incorporated into electrum?
