### ISSUE TITLE
very slow transaction

### ISSUE THREAD

**Issue by HaroldV** [spesmilo/electrum#3608]
I have five days and my transaction do not success 

what is happen ?

**Comment by SomberNight** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

https://dedi.jochen-hoenicke.de/queue/#2d
