### ISSUE TITLE
Android App crash on checking address.

### ISSUE THREAD

**Issue by fdiengdoh** [spesmilo/electrum#3612]
I guess its another bug. Here's how it happened.
I created a new wallet on the app by importing one private key. Then I tap the [Address] menu  it just crash. For a normal wallet it would show a lis of addresses. But since its only one private key it should display only one addresse but it crash. When I tap the [Receive] menu it shows the QR code as expected.

**Comment by SomberNight** [comment]
Thanks. I believe this should be fixed on master by https://github.com/spesmilo/electrum/pull/3592
