### ISSUE TITLE
Elektrum 2'd start… nothing done… got some "error-msg".…expect more silent. 

### ISSUE THREAD

**Issue by aotto1968** [spesmilo/electrum#3614]
~/Exodus-linux-x64> ./
Exodus      libnode.so  locales/    resources/  
???~/Exodus-linux-x64> ./Exodus 
ENV: production
bitcoin fee: 380 sat/byte
ethereum gas: 200000000000
ethereumclassic gas: 50000000000
set ripple fee: 10 drops
Exodus (production): DATA DIR: ???/.config/Exodus
main: 2142.646ms

SET WALLET LOADED
true

Failed to retrieve announcement: Not Found

{ Error: ENOENT: no such file or directory, scandir '???/.config/Exodus/backups/wallet'
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '???/.config/Exodus/backups/wallet' }
quitting: 9.437ms

**Comment by SomberNight** [comment]
How is this related to the development of Electrum?

**Comment by aotto1968** [comment]
an error message on user output is a development issue… I think.

**Comment by SomberNight** [comment]
But this is the repository for the Electrum bitcoin wallet. Those messages are for something else.

**Comment by aotto1968** [comment]
oh…sorry.
