### ISSUE TITLE
Fiat currency not available in INR.

### ISSUE THREAD

**Issue by fdiengdoh** [spesmilo/electrum#3617]
The app has limited fiat currency values while on the https://bitcoinaverage.com/ site (where the wallet pull the data from) it is available in INR. While many other wallets have most fiat currency to display alongside the coins amount. I'm not sure if this is an issue or should be a pull requests. 
Thanks.

**Comment by EnKrypt** [comment]
I wonder why something so basic is missing, especially since

* Almost every other wallet, including electrum desktop shows fiat in INR.
* The means to do it is available via the same API it's pulling the rest of the currencies from.

+1 to this issue. If this is not included soon, I will probably try writing a PR myself.

**Comment by bauerj** [comment]
> I will probably try writing a PR myself.

That would be great! Let me know if you have any questions while doing that.

**Comment by ecdsa** [comment]
due to a bug, we only show currencies for which one of the data sources provides historical values

**Comment by EnKrypt** [comment]
Does that mean this happens by design, or is it an unintended side effect that happened to remove currencies without historical values by accident?

In case someone decides to write a fix, will simply skipping such that check cause any sort of harm?

**Comment by laggingreflex** [comment]
Does that mean historical data for INR->BTC isn't available? In that case could it, at least in theory, be worked out backwards from USD->INR, assuming historical data for USD->INR be available?

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/commit/d6c2a0af946a7691b226a59aa5e3bcdcd6e31fa7
BitcoinAverage has historical data for INR; like OP said
I guess that fixes it.

(also somewhat related https://github.com/spesmilo/electrum/issues/5157)

**Comment by laggingreflex** [comment]
I don't see INR listed on Desktop still, even if I turn off the history option ([scr](https://user-images.githubusercontent.com/2523987/53540139-52837680-3b3a-11e9-9aec-16c2541d4f9a.png))

**Comment by SomberNight** [comment]
@laggingreflex are you running from source, and have that commit?

**Comment by laggingreflex** [comment]
Oops, my bad. No, not running from source. I'll wait for the fix to land 👍
