### ISSUE TITLE
Is Electrum really safe ? What are the possible limitations ?

### ISSUE THREAD

**Issue by tariq235** [spesmilo/electrum#3618]
[https://www.reddit.com/r/Electrum/comments/7m7mmn/my_electrum_wallet_got_hacked_45btc_gone/](url)

This is just 1 day ago post. As per reading his post it looks like this guy is extremely talented and he has used his laptop for just cold storage then how come his electrum got hacked ? He is going to die now. 

People do not recommend to store large bitcoin on exchange because of possible hack and not owning the private keys. I would like to know critical limitations of electrum before I store large amount of bitcoin on electrum.

**Comment by dabura667** [comment]
This is not a problem with Electrum. With the limuted information he gave it could be anything.

**Comment by ecdsa** [comment]
this is a bugtracking system. please do not misuse it
