### ISSUE TITLE
Generate bech32 QR in 3.0.3, gets stupid

### ISSUE THREAD

**Issue by TheButterZone** [spesmilo/electrum#3619]
OSX 10.12.6

Addresses tab, right click, details, click the show QR code icon, nothing happens. Except the Close button for that dialog box goes non-functional, Esc doesn't work, CMD+W doesn't work, and only random taskbar commands work. End up having to quit the program just to get the dialog box to go away and reset.

**Comment by ysangkok** [comment]
If you launch Electrum from the console, do you see any errors there? Since the QR code window is not appearing, there has probably been an exception which broke the rest of Electrum.

**Comment by TheButterZone** [comment]
"launch Electrum from the console" - how do I do that, exactly?

**Comment by ecdsa** [comment]
he means from the terminal

**Comment by TheButterZone** [comment]
How do I launch Electrum from the terminal, exactly?

**Comment by bauerj** [comment]
Open the terminal app, paste

    /Applications/Electrum.app/Contents/MacOS/Electrum -v

and press return.

**Comment by TheButterZone** [comment]
The only errors that stood out at launch were
[get_server] [Errno 61] Connection refused
[s5.noip.pl] cannot resolve hostname

After clicking the show QR code icon, these showed up; no errors in the terminal. 

[profiler] write 0.0000
[profiler] save_transactions 0.0004
[profiler] on_update 0.0050
[BitcoinAverage] getting fx quotes for USD
[BitcoinAverage] received fx quotes
[profiler] on_update 0.0001
[profiler] on_update 0.0052
[profiler] on_update 0.0048

**Comment by ecdsa** [comment]
this is fixed now in master
