### ISSUE TITLE
Electrum 3.0.2 (mac) crashes after entering password to open encrypted wallet

### ISSUE THREAD

**Issue by warnaars** [spesmilo/electrum#3622]
I recently created a segwit address in Electrum 3.0.2 and transfered my BTC into it. The wallet is encrypted. Now, when I try to open it, Electrum will crash when I enter the correct password. Any incorrect password will show me an alert that it's incorrect (and I am very certain that I have the right password).

Restoring the wallet from the seed on another machine doesn't work (seed sequence too short? after enting all the words, the next button is not becoming active).

I have the made a backup of the wallet file and I have the seed. Let me know if there is anything else I can share to find the cause of this issue.

**Comment by SomberNight** [comment]
> after enting all the words, the next button is not becoming active

- How many words are in your seed?
- This should be a "segwit" type Electrum seed, not e.g. a BIP39 seed, right? (Have you created the seed words using Electrum?)

> Now, when I try to open it, Electrum will crash

What OS? If Linux, please start Electrum with the `-v` flag, and provide logs.

**Comment by warnaars** [comment]
- there are 11 words in my seed
- this is a segwit type electrum seed, created using version 3.0.2 of Electrum for MacOS
- I am on MacOS 10.13.2 (17C88)

**Comment by SomberNight** [comment]
> there are 11 words in my seed

There's a 1/2048 chance for that for a valid seed; it should usually be 12 words. Given you said that Electrum is not letting you continue when entering it, I'm guessing you missed one of the words when writing it down.

Here's a quick python3 script that should brute-force a single missing word for a seed, assuming all other words are correct:
https://gist.github.com/SomberNight/a53257cf9e05ac07fd47ce0821b2a1fb
Change `given_seed` on line 45 for the seed you have.
It will output a few false positive seeds too, so you should test these one-by-one to find the correct one.

-----

Re the crash, if you are somewhat familiar with the terminal,
> please start Electrum with the -v flag, and provide logs

**Comment by warnaars** [comment]
Thanks for the script! I'll have someone with more understanding of command line check the log and provide info (I tried, but didn't get very far - I am not a techy by nature).

**Comment by jkwiecien** [comment]
I'm encountering the very same issue. I have the correct encryption password, which crashes electrum. I don't get to use seed. I'm using Electrum 3.0.0 mac version.

**Comment by SomberNight** [comment]
First off, please try with the latest release, 3.0.3.

> I'm encountering the very same issue

Could you please provide the logs Electrum prints to stdout? Run Electrum from the terminal with the `-v` flag, and the logs should be printed inside the terminal window, just copy and paste them here.

**Comment by jkwiecien** [comment]
https://www.electrumsource.org/#download 3.0.0 is latest on the download page. Do you want me to install development version?

BTW - I just accessed the same wallet using android app & seed. At least the heart attack is gone :)

**Comment by SomberNight** [comment]
@jkwiecien That is NOT the official site! The official site is https://electrum.org/ -- Please move any coins that app might have had access to immediately using the official application.

**Comment by jkwiecien** [comment]
Holy crap... I'm doing that right now

**Comment by jkwiecien** [comment]
Ok update - accessed the wallet using the correct app, no problem. Apparently, I created the wallet using the right one before and now tried to use this `other` one

I just wonder how did I access the wallet using https://www.electrumsource.org/Electrum-3.0.0.0-release.apk... should I be worried? Should I move the coins to another wallet for safety?

**Comment by SomberNight** [comment]
> should I be worried? Should I move the coins to another wallet for safety?

Yes, to both. A (very likely) malicious application just had a chance to access your private keys. I have no idea what that application does. I would no longer consider that machine to be safe. At the very least, you should create a new wallet (i.e. new seed words), and move the coins. If you are more paranoid, format and reinstall the whole OS.

**Comment by jkwiecien** [comment]
Thanks, I moved the coins. This fake app is better positioned in Google than the true one

**Comment by bauerj** [comment]
@jkwiecien It's probably shown as an ad on top of the search results. Sadly, there is little we can do to prevent that issue.

@warnaars Are you sure you used the official binary build of Electrum from electrum.org? If not, please reinstall with the .dmg from there. If that doesn't fix anything, here is how you can provide the logs:

Open the terminal app, paste

    /Applications/Electrum.app/Contents/MacOS/Electrum -v

and press return.

**Comment by warnaars** [comment]
Thanks @bauerj - yes, I have made sure that I have the official binary build of Electrum. Thanks for checking. Unfortunately My technical knowledge doesn't reach as far as it should to do the check for the corrupted wallet. In the mean time: the wallet has been recovered and the funds have been retrieved. Thanks for the help!

**Comment by bauerj** [comment]
Alright, that's good to hear.

I'm closing this issue then, if you encounter any other problems, let us know.
