### ISSUE TITLE
Electrum checkpoints question

### ISSUE THREAD

**Issue by romanornr** [spesmilo/electrum#3627]
Hi,

I see this is pretty "new" [https://github.com/spesmilo/electrum/blob/master/lib/checkpoints.json](url)

````
    [
        "00000000693067b0e6b440bc51450b9f3850561b07f6d3c021c54fbd6abb9763",
        26959535291011309493156476344723991336010898738574164086137773096960
    ],
````

I understand that ````00000000693067b0e6b440bc51450b9f3850561b07f6d3c021c54fbd6abb9763```` the blockhash is. 

but what should ````26959535291011309493156476344723991336010898738574164086137773096960```` be.

[https://blockexplorer.com/block/00000000693067b0e6b440bc51450b9f3850561b07f6d3c021c54fbd6abb9763](url)

**Comment by ecdsa** [comment]
please ask questions on irc, not here

**Comment by Mrwh0** [comment]
is decimal max target

**Comment by SomberNight** [comment]
Note: if you are trying to recreate the file, see
https://github.com/spesmilo/electrum/blob/f0657a35071d74e7ee0e0897601dc670709cb907/lib/network.py#L1090-L1094

**Comment by jangchongchan20** [comment]
Do

```
network.export_checkpoints("checkpoints.json")
```

on electrum console
