### ISSUE TITLE
Unknown error when signing after trying to bump fee

### ISSUE THREAD

**Issue by Stonesthrowing** [spesmilo/electrum#3628]
Hi,
after increasing the fee for a "Replaceable" transaction with a low fee, the transaction window opens and I assume I need to sign. When I do that an error message pops up with no text in it. The fee didnt change. I got some more coins in that wallet.
Hope this can be fixed easily.

**Comment by SomberNight** [comment]
Hi.
- What version of Electrum? What OS?
    - If Linux or Mac, please try running with the `-v` flag and provide logs.
- What is `Wallet type` and `Script type` in `Wallet`>`Information`?
- When exactly does the error message pop up? (When you click `Sign` in the tx dialog?)
- Does this wallet have a password? If yes, does it prompt you for the password to sign?

**Comment by Stonesthrowing** [comment]
Electrum 2.8.1 on Win 7
Standard wallet. Script type I dont know, couldnt find it, the option Wallet->Information is not available...
The message occurs after typing in my password for the signature

**Comment by SomberNight** [comment]
> couldnt find it, the option Wallet->Information is not available

Yes, that's because you are on an old version. Please update, and report back if the problem is still happening.

**Comment by griffinr3x** [comment]
I'll include this question here because i feel it is more relevant here @SomberNight if i increase the fee on a transaction, does it decrease the btc sent in the original transaction, or does it take the extra btc out of my wallet?

**Comment by SomberNight** [comment]
@griffinr3x 
GitHub is for development. Please ask these questions on [Bitcointalk/Reddit or maybe IRC](https://electrum.org/#community).
Bumping the fee usually decreases the change coming back to you in that tx.
Again, let us not continue this discussion in this thread.

**Comment by Stonesthrowing** [comment]
Problem solved with the update, thanks!
