### ISSUE TITLE
BIP49 segwit addresses generation through BIP32 path specification

### ISSUE THREAD

**Issue by jakubtrnka** [spesmilo/electrum#3629]
It is very counter intuitive to activate P2SH-encapsulated-Segwit by specifying some specific (m/49'/0'/...) BIP32 derivation path. Consistent approach, in my opinion, would be

1. ask user whether to use Legacy, Native Segwit or Encapsulated Segwit
2. suggest the user recommended BIP32 derivation path
3. generate appropriate keys

**Comment by ecdsa** [comment]
please try git master
