### ISSUE TITLE
Transaction history lost when upgrading

### ISSUE THREAD

**Issue by richardharbord** [spesmilo/electrum#3632]
I upgraded from 2.6.4 where I had a long transaction history. I moved my bitcoin out before upgrade but after I entered my seed into the 3.0.3 version there was on transaction history found for the seed. I find this incredibly worrying. I tried to go back to 2.6.4 but there were no transactions found. I am worried to put by bitcoin back if I am likely to lose them...

**Comment by bauerj** [comment]
Hey, 

are you sure you imported the right seeds? The transaction history is stored within the Bitcoin network and can never be lost as long as Bitcoin exists.

**Comment by SomberNight** [comment]
- Please cross-check addresses to make sure this is the same logical wallet, so as bauerj said, the "right seed". (`View`>`Show Addresses`, then `Addresses` tab)
    - You said you moved bitcoins so you should have some record of at least the addresses involved in that txn.
- Do you still have the wallet file you used with 2.6.4? Make a copy, and try opening that with 3.0.3.

**Comment by richardharbord** [comment]
YES thank you i had entered the seed incorrectly by one work. I admit I expected it to say this is not a valid seed so did not know I had entered it incorrectly. My apologies and thank you for your speedy support. My confidence is restored.
