### ISSUE TITLE
2FA issue for 2.8.3 version of electrum- post fork

### ISSUE THREAD

**Issue by bern8** [spesmilo/electrum#3637]
Hi All,  I could not remember my 2fa setup and accidentally deleted my google authenticator in my old phone.
When I tried to move funds recently, it asked for my OTP, which i obviously wont have now.
I restored my wallets (v2.8.3) but all were empty while my default remained locked. (I am pretty sure I have the seed correct as during the creation of the original wallet, you are asked to rekey them to confirm.)
I had tried restoring, using the same seed, setting up standards as well as new 2fa wallets with google authenticator (enabled and disabled ones), but the wallets are still empty.
at my wit's end now. pls assist...many thanks in advance
b

**Comment by ecdsa** [comment]
there's a 99.9% probability that you do not have the correct seed.
we cannot help you in that case

**Comment by SomberNight** [comment]
Please update to latest release, but make a copy of your wallet file just to be sure beforehand.
(The wallet file should be in `%appdata%/Electrum/wallets` on Windows, or `~/.electrum/wallets` on Linux)

When entering the seed words, after having entered them, what is `Seed Type` under the text box?

**Comment by AbdussamadA** [comment]
On the seed entry screen if you click on the options button there is an option to extend the seed with custom words. Did you use that option when creating your wallet? If so you need to use it again and enter the same words/characters you originally did.

**Comment by bern8** [comment]
thanks for the response guys..
@ecdsa :   :(
@SomberNight  seed type is 2fa... what version should I update to?
@AbdussamadA nope, never did

**Comment by bern8** [comment]
does it help if I had backed up the private keys?

**Comment by AbdussamadA** [comment]
update to the latest version as given here: electrum.org/#download . always use the latest version.

you don't have all the private keys only the 1 of 3. each address has 3 private keys behind it and you need any 2 to spend money. the seed consists of 2 only one of which is saved in the wallet file one. trusted coin has the third. during normal operation you need trusted coin's help to co-sign your transactions. if you had the seed you wouldn't need their help.

**Comment by bern8** [comment]
thanks so much all! I have learnt a great deal. 
I had indeed used an incorrect seed to recover the 2fa.  The folks at trustedcoin were helpful too.
Ultimately, we all need to store the seed properly. Found the correct seed and moved my btc,
cheers
