### ISSUE TITLE
3.0.2 Incorrect change address used in transaction

### ISSUE THREAD

**Issue by DopeyOne** [spesmilo/electrum#3638]
I made a transaction (d5286538233f10d4abe533c7d509829e5ce65acb45b0fcc370fc7f79ff960555) and the change address that was used does not exist in my wallet (in change or rx addresses).

Was downloaded from https://electrum.org/#download
Signatures for the exe match

Any ideas?

**Comment by SomberNight** [comment]
[2fa fee](https://api.trustedcoin.com/#/electrum-help)? And there was no change as it probably would have been dust, and dust is not kept but added to the fee.

**Comment by ecdsa** [comment]
this looks more like a prepayment for trustedcoin 2FA wallets.
you should have seen it in the fee dialog

**Comment by DopeyOne** [comment]
thanks for the quick reply's.

Makes total sense, didnt realise its a pre-pay thing.
