### ISSUE TITLE
problems on 12/24 - error in calculating urgent rates ...

### ISSUE THREAD

**Issue by cotrim126** [spesmilo/electrum#3639]
Hello how are you? I need an urgent help I could not get support from the wallet, I do not know if this is with you or the blockchain, but I went to make a transfer to exchange on 12/24 where I already made several deposits to sell my btc and buy ripple, The problem is that I requested 5.98272mbtc and it was discounted without my authorization it was all of the btc of my portfolio: 63.05857mbtc, totaling: 69.04129mbtc ...

what could have happened? need to recover the fee charged is more than eleven times more than the value sent to exchange ...

https://www.blocktrail.com/BTC/tx/e9e1a3a81a2f1a0b57eae07e640323757a5b735f4b8b59d780c22f613f9ab6bb

thank you

**Comment by cotrim126** [comment]
version electrum wallet: 3.0.3

**Comment by SomberNight** [comment]
You had lots of small value inputs, and you spent them during a high fee (in terms of sat/byte) period.

It was not really worth it, it would have made sense to wait spending these (for competitive fees to become cheaper). You paid ~760 sat/byte, which probably was ~enough even for a fast confirmation then. In the past 1-2 days, maybe a 100 sat/byte fee would have been enough.

In Bitcoin, you pay after the size of your transaction, not the value being transferred. If you have many small value inputs, those will make the transaction large, while hardly adding any value, hence their **effective value** is really low, sometimes even negative.

There is no bug here, you paid the fair market price for bitcoin transaction fees at that point in time. When people say a bitcoin transaction costs "x dollars", they mean for a typical tx; yours was ~200 times larger. Unfortunately, there is nothing that can be done now.

**Comment by cotrim126** [comment]
the problem is that neither in the exchange I received the value that I sent ... I did not receive nor the value of the rate ...

**Comment by SomberNight** [comment]
The miner who included it in a block received the difference, the "fee".

**Comment by cotrim126** [comment]
plus I do not say the rate the value sent, I did not receive so I thought it was error, because the shipping address is right.
