### ISSUE TITLE
[Linux] Segmentation fault after closing testnet wallet.

### ISSUE THREAD

**Issue by verretor** [spesmilo/electrum#3640]
After closing two testnet wallets, I got a segmentation fault. I am using Ubuntu 16.04 and Electrum 3.0.2. I did not manage to reproduce it.

My guess is that it has something to do with Qt and that there's nothing you can do about it.

**Comment by ecdsa** [comment]
sorry, but that kind of report is not useful..

**Comment by verretor** [comment]
Is there a way I could have made it more useful?
