### ISSUE TITLE
Envio de Bitcoins hacia Wallet GateHube

### ISSUE THREAD

**Issue by agus19811** [spesmilo/electrum#3641]
Hola, envíe Bitcoin desde mi Wallet de Electrum (Version 3.0.2.)  hacia una wallet de GateHube y en Electrum me figuran restando esos bitcoins y la transacción figura como no confirmada. De esto ya van 4 días. A la Wallet de GateHube tampoco llegaron. Quería saber donde estan realmente y como se soluciona el inconveniente. Muchas Gracias.

**Comment by SomberNight** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do
