### ISSUE TITLE
Error Server Did Not Answer

### ISSUE THREAD

**Issue by Throwaway35** [spesmilo/electrum#3642]
This message was popping up every time I tried to send bitcoins from tails on my electrum wallet. Then it worked once and I transferred all my coins out of my wallet thought the problem was fixed. However for the past 3 days I've been trying to send coins out been getting that message.

**Comment by Throwaway35** [comment]
not sure if picture uploaded here it is

**Comment by Throwaway35** [comment]
Not sure if it uploaded still

**Comment by SomberNight** [comment]
What version of Electrum? Tails often has very old versions, due to Debian Testing having old versions.

**Comment by Throwaway35** [comment]
I just barely downloaded it a few weeks ago

**Comment by Throwaway35** [comment]
3.3

**Comment by SomberNight** [comment]
> What version of Electrum

not Tails

Last time I checked, they still bundled 2.7.9, which is quite old at this point.

**Comment by bauerj** [comment]
Hey @Throwaway35 

maybe you missed the message from SomberNight. Can you try and find out what version of Electrum produced that error message?

**Comment by Throwaway35** [comment]
2.7.9

**Comment by bauerj** [comment]
Sorry but that release is from 2016 and not supported any more so please try a newer version and see if it fixes the bug.

**Comment by Throwaway35** [comment]
How do I do that though because I have tails and I have upgraded tails
everytime it says I need to so you'd think it'd update with it no?
