### ISSUE TITLE
Please dont make ~/.electrum/daemon executable

### ISSUE THREAD

**Issue by VeneziaDev** [spesmilo/electrum#3644]
Electrum daemon creates a lockfile in ~/.electrum/daemon 
but WHY is this file executable? Please change this to a normal file.
I'm running Electrum in a firejail environment and creating executable files is restricted in this environment for a good reason.
Also a lockfile is not an executable at all. But creating it as an executable file stops me from being able to use Electrum.

**Comment by SomberNight** [comment]
Is this just due to defaults? Can we just do:

```patch
diff --git a/lib/daemon.py b/lib/daemon.py
index de2b1361..58e1840e 100644
--- a/lib/daemon.py
+++ b/lib/daemon.py
@@ -58,7 +58,7 @@ def get_fd_or_server(config):
     lockfile = get_lockfile(config)
     while True:
         try:
-            return os.open(lockfile, os.O_CREAT | os.O_EXCL | os.O_WRONLY), None
+            return os.open(lockfile, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o644), None
         except OSError:
             pass
         server = get_server(config)
```

**Comment by VeneziaDev** [comment]
Works fine for me. Thanks.
