### ISSUE TITLE
Incorrect balance

### ISSUE THREAD

**Issue by SeEspRit** [spesmilo/electrum#3646]
Hello everyone!
I need some help with electrum. Today I sent 0.0012 BTC to Binance, it was successful, but now my balance is -0.00474535 lower. I think it is impossible high for fees, and now I dont know if is it just a bug or someone stole from me that? Transaction ID: a401461fce82b9d8146ea5a0b3d7370903513912483d15bbcb05bb09c2732a4e

**Comment by bauerj** [comment]
Do you happen to use a 2FA wallet?

**Comment by SeEspRit** [comment]
I use it with 2fa, yes.

**Comment by bauerj** [comment]
Then this is the trustedcoin fee for a few transactions in advance. Click the trustedcoin icon in the lower right hand corner to find out more.

**Comment by SeEspRit** [comment]
It says: Pay every 20 transactions 0.0001BTC/tx. Your wallet has 19 prepaid transactions.

**Comment by bauerj** [comment]
So this seems to be correct:

* 0.002BTC trustedcoin fee for 20 transactions
* 0.00154535BTC Bitcoin network fee

**Comment by SeEspRit** [comment]
That means the next 19 transactions will be "free"? Only the Bitcoin network fee will be calculated?

**Comment by bauerj** [comment]
Yes, that's correct.

**Comment by SeEspRit** [comment]
OK, now I get it, thanks for helping!
