### ISSUE TITLE
help send to electrum

### ISSUE THREAD

**Issue by razzielh** [spesmilo/electrum#3648]
Hello friends, I wanted to ask you where I could see a problem with my Electrum wallet. I made a mistaken delivery of xrp (crypto) to an Electrum version that does not accept that cryptomoneda and now the shipment is blocked since it does not reach my purse Electrum nor to my exchange from which I made the shipment. My version of Electrum is 2.8.3 Could you help me find a solution? Thanks

**Comment by SomberNight** [comment]
Electrum is for bitcoin.

Btw, I just checked and ripple addresses seem to start with "r". I have no idea how you even got an exchange to accept a bitcoin address as a ripple address. If that is indeed what happened, ask them, it's partly their fault.
