### ISSUE TITLE
REPLACEABLE increase fee cannot bump fee: could not find suitable outputs

### ISSUE THREAD

**Issue by pazuzu2000** [spesmilo/electrum#3652]
REPLACEABLE increase fee cannot bump fee: could not find suitable outputs. Electrum 3.0.3
 0.0049673 BTC is the balance.

The following are the TX details ( any ideas what the problem is and how I might dig my way out of this imbecile crypto mess:

Estimated TX Value | 0.02573330 BTC
-- | --
UNCONFIRMED
OPT-IN RBF
Thursday, January 4th 2018, 10:51:53 -06:00
blockchain search
 	View on BTC.com
BITCOIN TRANSACTION
e7f1c400bc3d5104ecxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbb20b3d587641799
Estimated TX Value	0.02573330 BTC
Confirmations	UNCONFIRMED
OPT-IN RBF
Relay time	
Thursday, January 4th 2018, 10:51:53 -06:00
Total Inputs	0.02763837 BTC
Total Outputs	0.02578632 BTC
Fee	0.00185205 BTC
Fee / KB	0.00227245 BTC
Size	815 bytes
Estimated Change	0.00005302 BTC
sent to 1MF8v41nsny1YgKgkMNyvqTDcccv5nMfVP
5 INPUTS
Total Inputs: 0.02763837 BTC
1BsadgE3z3TFYE9BqGy92t5bctwF1o1gEf(0.00096543)
1AVuBQ2ma9fcuYPAxwHQiCijzfaXTkx7Hd(0.00014442)
1Ci7qz3jpZ2PtNfSv4qMyHNhtyeUFurVaz(0.00038381)
1Nq7TsCL4TU4PxLVAyxDwozyMibhLghCBk(0.00044751)
1J2HzK6jzVCnGf7xJYGfra1ry9JWPkhikE(0.02569720)
2 OUTPUTS
0.00005302 BTC change
1MF8v41nsny1YgKgksssvqTDcccv5nMfVP(0.00005302)
13EiZrXRgBCZRYixm4EdddTELnyveZaFC6(0.02573330)

Captures are available if helpful. There are sufficient funds to increase the fee. No confirmation.

27 USD current Fee paid

375 USD transaction.

**Comment by SomberNight** [comment]
This is because currently, if there is a change output in the txn owned by your wallet, Electrum only offers to do RBF by decreasing that. In this case, there is a change output `1MF8v41nsny1YgKgkMNyvqTDcccv5nMfVP(0.00005302)`, and it cannot be decreased further (would be too small value/dust).

**Comment by pazuzu2000** [comment]
Is there anything I can do or how does this end the amount sent was 0.0257333 with a ~0.00185205 XBT = 27.5339 USD Fee (wasn't that stupid).

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

**Comment by ecdsa** [comment]
in that case the code should be able to nuke the change address

**Comment by SomberNight** [comment]
@ecdsa It's not that simple. Then the user would be able to start decreasing the other outputs in the next round of bump_fee. Or is that okay?
Maybe it should add a new input instead, and increase the change output.

**Comment by pazuzu2000** [comment]
@SomberNight ... all you folks kind enough to put your minds/experience to this.

So here is as weird as you like.

Taking the advice to clear the electrum files and reinstall with the original seed then selecting another server. Now if that has anything to do with anything, good guess. Within an hour I get an email: saying they received the Tx. nearing in mind the yellow thingy with replaceable was still on the electrum client. The recipient said it showed no confirmations but were able to access it, move it.... same as any regular completed Tx.
This am it shows completed with 33 confirmations.

Way beyond my paygrade but my takeaway is those accelerators would be funny if they weren't serious.

Reality is for my part is to pay what they are asking, wait for a low ebb on the network and i'm done with the replaceable thing. that was all in frontal assault. i'll decline that fine opportunity.

all's well that ends....

**Comment by YanhaoMo** [comment]
I'am sorry, same problem, any idea to solve this. I try to send some btc to the change output owned by myself, but still get the same error.

**Comment by YanhaoMo** [comment]
solved it with double spend, never mind

**Comment by SomberNight** [comment]
While this issue started as a question, it revealed a genuine shortcoming of the code, hence reopening.

Something should be done in the situation above, probably either
- allow removing the change output; which will then mean the user can also start reducing the other outputs
- start adding new inputs
