### ISSUE TITLE
introduce 2FA segwit wallet

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3653]
It would be nice to introduce a 2FA segwit wallet, that uses p2wsh outputs to receive on.

Required server side changes by TrustedCoin, and related notes:
- need to implement support for p2wsh e.g. Zpubs and handling segwit txns (serialisation, signing)
- the server atm uses xpub version bytes to detect mainnet/testnet (https://github.com/spesmilo/electrum/issues/3445#issuecomment-348974686)
    - ~~this is not possible with Zpubs (https://github.com/spesmilo/electrum/issues/3539)~~
    - ~~would be great to introduce a 'network' arg, and while at it, do it for xpub too :P~~
        - ~~no need to maintain backwards compat with existing testnet wallets (tpub), it's testnet afterall. just mentioning because user ids depend on the exact serialisation of xpubs (tpubs in this case)~~
     (EDIT: see comment below; testnet once again has different xpub version bytes)
- what about billing addresses? this is somewhat independent I guess
    - could keep using p2pkh for 2fa-old, and start using p2wpkh for 2fa-segwit
    - it would save fees to start using p2wpkh for all types (when running new software), and it should be possible, but some care would be needed to maintain backwards compat
    - we could also just keep using p2pkh for both but that would be wasteful

**Comment by SomberNight** [comment]
Note: 3.1 will likely have https://github.com/spesmilo/electrum/pull/3898, which means mainnet and testnet will (again) have different xpubs

**Comment by ecdsa** [comment]
merged

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/pull/4880
