### ISSUE TITLE
Bitcoins stuck on Low fee and Unconfirmed Parent.

### ISSUE THREAD

**Issue by Max319** [spesmilo/electrum#3661]
I moved bitcoin from Mycellium to Electrum.

Then I did 3 transactions out of Electrum to another address but all 3 got stuck like this.

I am trying to restore to before the transactions became stuck; it's been a week and a half and it's almost all the money I have.

Before electrum never did that to me. Maybe it's the address receiver. Before I always sent them to Circle;

But if anyone could know how to make them unstuck. I will be working on it all this time and Sunday.

Thank youuuuu,
/

**Comment by ecdsa** [comment]
you could try CPFP, or wait until the tx is confirmed or rejected from mempool.
anyway, this is not an electrum issue, closing this
