### ISSUE TITLE
Switch back to Non-Segwit address generation in Preferences

### ISSUE THREAD

**Issue by marat-chardymov** [spesmilo/electrum#3662]
It seems that [bip173 ](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki)address format is not widely adopted, so many services reject sending to such address as invalid. It's inconvenient to reinstall whole wallet just to use old address format to receive funds. Please add generator switch

**Comment by SomberNight** [comment]
Electrum seeds are versioned. You need different seed words to have segwit or non-segwit addresses, so there can not simply be a "switch".

> It's inconvenient to reinstall whole wallet

You don't need to reinstall anything. you can have multiple wallets and switch between them.
If you are using the default GUI on desktop (QT), just use the menubar: `File`>`Open`.
