### ISSUE TITLE
How to get bech32 private key compatible with importprivkey in bitcoin-qt?

### ISSUE THREAD

**Issue by vachichuong** [spesmilo/electrum#3667]
Hi guys, I need a way to get the bech32 private key and import it in bitcoin-qt, it is possible?
Right now, if I do as usually, it gives a private key error code -5

**Comment by SomberNight** [comment]
You can adapt the code in https://github.com/spesmilo/electrum/issues/3620#issuecomment-354428035

```python
import electrum
from electrum import bitcoin

key = 'LAst2SKVNx36PUY2q49cyLCcpze1YMvdJ66z3uKuiyaLKTVVsH3J'
txin_type, secret, compressed = bitcoin.deserialize_privkey(key)
wif2 = bitcoin.serialize_privkey(secret, compressed, 'p2pkh')
print(wif2)
```

**Comment by SomberNight** [comment]
(closed the issue because that should answer it; but comment here if it is not clear)

**Comment by rex4539** [comment]
It is clear but I tried it in Electrum 3.0.6 Console, then pasted the new wif2 key in Core 0.16.0 but still yields "Invalid private key encoding (code -5)".
