### ISSUE TITLE
Merchant: simple-websocket-server needs update to python 3

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum#3670]
https://github.com/ecdsa/simple-websocket-server needed for merchant to function:

```
byte-compiling /home/pay3/.virtualenvs/electrum/lib/python3.5/site-packages/SimpleWebSocketServer/SimpleExampleServer.py to SimpleExampleServer.cpython-35.pyc
  File "/home/pay3/.virtualenvs/electrum/lib/python3.5/site-packages/SimpleWebSocketServer/SimpleExampleServer.py", line 31
    print self.address, 'connected'
             ^
SyntaxError: Missing parentheses in call to 'print'
```
 
Hint: python3 is supported upstream

**Comment by ecdsa** [comment]
do we still need that repo?

**Comment by ser** [comment]
yes we need - I'll create a PR with an updated version

**Comment by ser** [comment]
I have problems with running the newest upstream on Electrum - debugging now, so it will take more time

**Comment by ser** [comment]
@ecdsa - do you remember why did you have to patch the upstream with timeout?

**Comment by ecdsa** [comment]
iirc, to ensure proper termination of electrum

**Comment by ser** [comment]
@ecdsa - in verbose daemon run i am getting a sequence:
```
connected ('10.100.100.100', 53848)
message received id:0361a81cf1
response {'id': 72, 'params': ['mhjQ2fg3wmo1PNaYkN63hrMtiYjMdGsEyW'], 'method': 'blockchain.address.subscribe', 'jsonrpc': '2.0', 'result': None}
```
and the developer console shows that WS was initiated.

But after payment, electrum says:
```
response {'method': 'blockchain.address.subscribe', 'jsonrpc': '2.0', 'params': ['mhjQ2fg3wmo1PNaYkN63hrMtiYjMdGsEyW', 'c324fce82eac87474f556ecdc63efe41222051a7649b9a5584bf085de4ff1fbf']}
```
and developer console in the browser does not react in any way, looks like nothing is getting received on client side. 

Does the exchange look normally in your opinion? I have no idea how to trace it, as additionally everything is encapsulated in SSL which makes any efforts to monitor transfer more complex.

**Comment by SomberNight** [comment]
Btw, I've tested and the fork for simple-websocket-server is no longer needed.

**Comment by ecdsa** [comment]
thats great, I'm going to delete my fork
