### ISSUE TITLE
Standalone executable 3.0.5 Windows SmartScreen Unknown publisher issue

### ISSUE THREAD

**Issue by sguryev** [spesmilo/electrum#3672]
**Reprosteps:**
1. Download https://download.electrum.org/3.0.5/electrum-3.0.5.exe
2. Run

**Expected results:**
Application should be run

**Actual result:**
![image](https://user-images.githubusercontent.com/6978458/34665337-de082852-f470-11e7-81d0-50ed35a4278c.png)

**Comment by bauerj** [comment]
Hey,

this is already being tracked in #3355. We are working on it.

**Comment by sguryev** [comment]
I didn't saw this error for 3.0.2, 3.0.4. 3.0.5 it's the first version where i saw it. Not sure about the 3.0.2 though because it was about 3 weeks ago
