### ISSUE TITLE
Electrum wallet stuck synchronizing for 3-4 days now

### ISSUE THREAD

**Issue by hidealittle** [spesmilo/electrum#3684]
I transferred around 0.01BTC into my wallet from foxbit on Saturday, foxbit says transaction complete but Electrum won't synchronize. I've tried changing servers, letting it choose a server automatically, etc. Any help please? I would rather not attempt anything else on my own because I'm afraid of losing the bitcoins (it's a LOT more money in my country than in America for example)

Thank you! 

I'm using version 2.7.18 on Windows 10

**Comment by SomberNight** [comment]
What version of Electrum, and what OS?

**Comment by hidealittle** [comment]
@SomberNight Sorry, I'm using version 2.7.18 on Windows 10.

**Comment by ecdsa** [comment]
@hidealittle please upgrade immediately to 3.0.5.

**Comment by hidealittle** [comment]
@ecdsa Thank you, issue resolved, I'll be sure to check for updates more often. My mistake.
