### ISSUE TITLE
cx_freeze: phyton error in main script

### ISSUE THREAD

**Issue by random5555** [spesmilo/electrum#3686]
https://i.imgur.com/IjbT9xr.png

can't even open the electrum verge wallet ( not the bitcoin one, but the verge one) , I got this error again and again. 

Any solution for this issue? I didn't mess anything and suddenly I got this error.

**Comment by bauerj** [comment]
This is only for the Bitcoin wallet. Please report your issue [here](https://github.com/vergecurrency/electrum-xvg).

**Comment by random5555** [comment]
thanks
