### ISSUE TITLE
refusing to connect to non-tls servers

### ISSUE THREAD

**Issue by fr3aker** [spesmilo/electrum#3689]
As of 3.0.5 electrum seems to refuse to connect to servers over non-tls secured connections.

Instead of connecting to my statically configured server over TCP, on start the server setting is replaced by a random public TLS server. I'd like to point out this is a major privacy issue since I usually only connect to my own server through a secure network.

Also the option to use a (non-)TLS server seems to have disappeared from the server settings and judging from the ports only TLS-enabled servers are available in the server browser. This is very confusing especially since there is no mention of such a change in the release notes.

**Comment by SomberNight** [comment]
The `Use SSL` checkbox is still there, in the `Connection` tab of the network dialog, in 3.0.5.
master / 3.1 will remove it though and have SSL enabled by default (with only a CLI argument to disable it)

**Comment by SomberNight** [comment]
> Instead of connecting to my statically configured server over TCP, on start the server setting is replaced by a random public TLS server

Are you sure you have `Select server automatically` disabled?

**Comment by fr3aker** [comment]
`Select server automatically` is disabled.

Where would I find the SSL checkbox? Neither in the `Preferences` nor in the `Network` dialogue I can find a `Connection` tab.

**Comment by SomberNight** [comment]
![ele_305_use_ssl_checkbox](https://user-images.githubusercontent.com/29142493/34776798-47f7a56e-f618-11e7-992b-559377f73b8a.PNG)

**Comment by fr3aker** [comment]
That looks very different for me. Do I need to delete anything when upgrading from github sources?
![screenshot_20180110_151454](https://user-images.githubusercontent.com/114561/34777009-2de74624-f619-11e7-8b57-abdc10707ecf.png)

**Comment by SomberNight** [comment]
You are on git master, not 3.0.5

**Comment by fr3aker** [comment]
damn, sorry. I assumed both are the same after a tagged release.

**Comment by SomberNight** [comment]
Usually yes, but 3.0.4 and 3.0.5 have been branched off 3.0.3 (brach: 3.0.x) due to having to fix the recent vulnerability quickly, and master not being stable.

**Comment by ecdsa** [comment]
on master you can use the --nossl option in the command line
