### ISSUE TITLE
Request: Fee options on the UI

### ISSUE THREAD

**Issue by nvk** [spesmilo/electrum#3691]
Would be great if the Send UI or Preview Modal had multiple fee option calculated ie:

```
Next block fee: 506 sat/byte
Hour fee: 415 sat/byte
Day fee: 209 sat/byte
Half-week fee: 141 sat/byte
Week fee: 65 sat/byte
```

Keep up the great work!
Thanks.

**Comment by ecdsa** [comment]
are these ETAs?

**Comment by ecdsa** [comment]
btw, version 3.1 will have mempool based fee estimates

**Comment by nvk** [comment]
Yes, ETAs.

**Comment by ecdsa** [comment]
there is no way such long ETAs can be realistic
even the short ETAs of Core are unrealistic

**Comment by nvk** [comment]
True, but they are helpful in the penny saving long confirmation crapshoot.

**Comment by ecdsa** [comment]
sorry, but we are not going to compute that kind of ETA; they are not provided by Core, and thats because the longer they are, the less reliable. if you are interested in penny saving, check out mempool based fees.
