### ISSUE TITLE
electrum in arabic how to change to english

### ISSUE THREAD

**Issue by lastfrontier999** [spesmilo/electrum#3692]
help me please I downloaded the upgrade and now everything is in Arabic  I need to change to English

**Comment by bauerj** [comment]
Is your OS in arabic?

**Comment by lastfrontier999** [comment]
i am not sure but it looks like arabic  i just know it was english and now
its not  but i will try what you said to do in your first email and get
back to you sir.

**Comment by bauerj** [comment]
To change it back to another language:

![chrome_2018-01-10_21-53-34](https://user-images.githubusercontent.com/598790/34794972-c2f7d8f0-f650-11e7-81cb-4700930bf76b.png)
![electrum-3 0 3_2018-01-10_21-53-48](https://user-images.githubusercontent.com/598790/34794976-c433ed6c-f650-11e7-89de-6b61ae6310e2.png)

**Comment by lastfrontier999** [comment]
i am not sure but it looks like arabic  i just know it was english and now
its not  but i will
