### ISSUE TITLE
Adress Elecetrum 3.0.5 don't work .

### ISSUE THREAD

**Issue by derfader123** [spesmilo/electrum#3693]
![bandicam 2018-01-10 23-25-07-375](https://user-images.githubusercontent.com/35311449/34794326-5bd0a008-f65f-11e7-8419-95cf78e96ca8.jpg)
I used my adress on several sites , but none of them don't work . 
![bandicam 2018-01-10 01-24-21-595](https://user-images.githubusercontent.com/35311449/34794316-568366bc-f65f-11e7-8bd5-c62cbb9426ab.jpg)

**Comment by bauerj** [comment]
That's what it says when creating a segwit wallet:

![image](https://user-images.githubusercontent.com/598790/34794568-5e7594ea-f64f-11e7-9502-3af3e321a469.png)

**Comment by lastfrontier999** [comment]
okay that worked   thank you very much  for the help

**Comment by ecdsa** [comment]
interesting, localbitcoins.net does not support bech32.
