### ISSUE TITLE
Backport 3.0.5 security fixes to 2.9.x 

### ISSUE THREAD

**Issue by schildbach** [spesmilo/electrum#3696]
Since not everybody has gone fully Python3, I think it would be a good idea to backport the recent security patches to 2.9.x. Ubuntu for example will take until 18.04 (due in April) for full Python3 support, including all the necessary libraries.

**Comment by ecdsa** [comment]
will do

**Comment by ecdsa** [comment]
please checkout the 2.9.x branch

**Comment by schildbach** [comment]
2.9.4 works for me so far. Many thanks!
