### ISSUE TITLE
RFC: new command: getfee

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum#3704]
# Request For Comments

### Problem

When you use Electrum as a merchant, you want to suggest your customers a correct fee to avoid problems. Electrum already has this information, why then use an another external source to create another point of failure?

### Proposed Solution

Creation of another command ```getfee``` - which will operate via RPC as well. It's code will be identical to currently displayed fee when you issue a command line ```electrum daemon status```.

### Who will write it

If concept is agreed, I will propose #PR for this.

**Comment by SomberNight** [comment]
Sure, why not?
Note that the fee returned by `electrum daemon status` is `SimpleConfig.fee_per_kb()`, and what that returns depends on your config settings (e.g. static/dynamic).
