### ISSUE TITLE
Without --nossl,  -s *:t option is silently ignored

### ISSUE THREAD

**Issue by nothingmuch** [spesmilo/electrum#3706]
When specifying e.g. `-s 127.0.0.1:8000:t` in order to connect to a private server w/o SSL, the CLI option is silently ignored (even if `-1` is specified, and no mention with `-v`), and instead proceeds with automatic server selection as if `-s` was never specified at all.

When *both* the `:t` suffix and `--nossl` are specified, then the `-s` directive takes effect as expected. `--nossl` on its own is not sufficient if `:t` is not also added to the address.

Given the potential privacy implications of connecting to unspecified servers, as well as the lack of diagnostic output (I initially thought the option was simply removed and didn't realize it was still being parsed but wasn't in effect), I think the correct behavior when given an explicit `:t` suffix would be to exit with an error message indicating that `--nossl` is now mandatory, especially is this may silently change peoples' configured setups, by starting to connect to the public servers instead.

See also #3689 and dc388d4c7c541fadb9869727e359edace4c9f6f0 which introduced this change

**Comment by SomberNight** [comment]
I agree that if the user has a selected server (i.e. the `server` config variable is set), we really SHOULD NOT silently connect to a different server.

I believe the current behaviour is by accident, and it was probably missed here
https://github.com/spesmilo/electrum/blob/dc388d4c7c541fadb9869727e359edace4c9f6f0/lib/network.py#L177-L181
that if the `assert` triggers, that is catched by the `except` block; in https://github.com/spesmilo/electrum/commit/dc388d4c7c541fadb9869727e359edace4c9f6f0.

The question is: what should happen if the `server` config variable is in contradiction with `nossl`?

Unfortunately, it would require major changes to properly pass a notification/popup about any of this to the GUI, as the daemon starts the network before the GUI.

I propose keeping the server (host) but changing the protocol (enforcing the value of the `nossl` config var), silently (with only a log message).

**Comment by SomberNight** [comment]
This should now be fixed by https://github.com/spesmilo/electrum/pull/3733 and https://github.com/spesmilo/electrum/pull/3732
