### ISSUE TITLE
Incorrect work with numeric jsonrpc passwords

### ISSUE THREAD

**Issue by epoxa** [spesmilo/electrum#3709]
Seems like [it](https://github.com/spesmilo/electrum/pull/3664) works wrong when rpc password is totally consists from digits only.
For instance when trying to execute `electrum daemon stop` I get error message 'Daemon not running' and this: 

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/electrum/jsonrpc.py", line 62, in parse_request
>     self.authenticate(myself.headers)
>   File "/usr/local/lib/python3.5/dist-packages/electrum/jsonrpc.py", line 93, in authenticate
>     and util.constant_time_compare(password, self.rpc_password)):
>   File "/usr/local/lib/python3.5/dist-packages/electrum/util.py", line 204, in constant_time_compare
>     return hmac.compare_digest(to_bytes(val1, 'utf8'), to_bytes(val2, 'utf8'))
>   File "/usr/local/lib/python3.5/dist-packages/electrum/util.py", line 295, in to_bytes
>     raise TypeError("Not a string or bytes like object")
> TypeError: Not a string or bytes like object

**Comment by nothingmuch** [comment]
I can only reproduce this with a JSON numerical type as the password, i.e. `"rpcpassword": 123` in the config, but `"rpcpassword":"123"` does work as I'd expect

Syntactically JSON types are arbitrary precision decimal numbers, and although python preserves the formatting of large ints (and I'm pretty sure there is only one canonical representation per int, though not floats), not all languages do, so I think converting `self.rpc_password` to a string if it isn't one is actually a bit sketchy.
