### ISSUE TITLE
Decryption Help

### ISSUE THREAD

**Issue by chaddybox026** [spesmilo/electrum#3713]
I have a wallet file created using a program designed for bitcoin cash. It was forked off of this repository. This wallet file crashes the program upon selecting it to use. I would like to know if there is a way I can manually decrypt the wallet to get the private keys from the wallet. Any help would be appreciated.

**Comment by ecdsa** [comment]
please create a bug report in their repository, with a description of the crash.
if it is a GUI related crash, you could try to decrypt using the command line.
