### ISSUE TITLE
Windows standalone client password box doesn't get focus

### ISSUE THREAD

**Issue by Dadadah** [spesmilo/electrum#3718]
When opening the windows standalone client defaulted to a wallet with a password the window doesn't focus the password box. 

To reproduce, launch the standalone client on a password encrypted wallet.

**Comment by SomberNight** [comment]
Hmm, the field has focus for me...
I'm testing with 3.0.5. What version are you using?

https://github.com/spesmilo/electrum/blob/7ae1a4cdebd47848f6b55461adfcbf1428fa24c5/gui/qt/installwizard.py#L209-L212

**Comment by Dadadah** [comment]
That's embarrassing. I think I am mistaken.
