### ISSUE TITLE
valid key 1NfaygNyzo9DAsA8x5A85FaLcr7KzXgEtG rejected, and synchronizer.py assert fail.

### ISSUE THREAD

**Issue by qvQoaToswG8J** [spesmilo/electrum#3719]
version 2.7.9
new wallet with one private key which has one transaction:
hits assert tx_hash == hash_encode(Hash(result.decode('hex'))) in synchronizer.py
on transaction b46f650a64fcd5e7ceb2ca569b44b6b65565ed3cfb20322885f134df64bb4dcc

new wallet with the matching public key 1NfaygNyzo9DAsA8x5A85FaLcr7KzXgEtG
rejects that key as invalid. bitcoin core accepts it.

Also the 1Nfay address was generated by a bash script derived these:

bitcoin.sh from
https://github.com/grondilu/bitcoin-bash-tools
83e56929fe40aa60f0a5ad9b987c4e44ecb334eadb1e7983863321403f85d40e bitcoin-bash-tools-master.zip

grondilu/bitcoin-bash-tools@5493c71

brainwallet.sh from
http://cycadgarden.com/BrainWallet/
ecf2c17a974a9d23745529da00b84ec7ec34668b985e9b0f80813f4d4050937e brainwallet.zip

Creating new wallet with public or private keys
public key 1NfaygNyzo9DAsA8x5A85FaLcr7KzXgEtG is rejected as invalid.
private key (undisclosed) get assertion violation in synchronizer.py
edited the code to print more:
if not tx_hash == hash_encode(Hash(result.decode('hex'))):
self.print_msg("hash mismatch, skipping. result:", result)
self.print_msg("expected hash:", tx_hash)
self.print_msg("actual hash..:", hash_encode(Hash(result.decode('hex'))))
return
$ electrum gui
[Synchronizer] hash mismatch, skipping. result: 02000000000103b8b5c36ee1136f0f2820f9d46a8affe17230ff122f8b941dcb1cd1ae1de52d96000000006b483045022100bef831c258d5b4f6b8f5f3f4375700bf0f4a6053f2106cc44237d66f3da4323c0220136dd61bc4144cbe59fb500dc17abab60003089e8ed1cfef1d6d2f7ccde0c2b301210354e69a9e06abad74e46d211e5efe4d56391cc5a8cc4f205fc7d0cf624c8739a0fefffffff8c43e355a1c11dbc7efcfc5059192a05b5d6fbc350ddfe182186adab41d0b27000000001716001496092638e41b28bdac8e82e89fb6491564d6663cfefffffffc04b50691a8af0699a8c3c3d9ce44d1b0b4191b201b99fa6c7da27ba135b9cb00000000171600144c5f4533ee32b6a8ebeee303a60b34b929ef29fdfeffffff0247750b00000000001976a9144e2a5ad951c2e2667772d8ec8d2b7baae5fd6b9088ac561b3c01000000001976a914eda6cf8e4abc51368abb8188cef4de7059a0649288ac000247304402205d0d0b9a90fb416b2b81321812006260399bccd845227f37518281051899139002207708d16d12e19549baab2647f6bd8dcb938727d7b9572db93da1c195a2efefb501210284618e584d9796ad258b4b31c35eb252af514fa69c09e8ec09fd825008855cf5024730440220507907284d68ea172261c14b6dad2730889b2cab769e8bc5716b9346d90288a3022007350dbbecaf3b9dd8e112cf7d2d159d069fa4927268bdfdf17f7db63a506439012102f6c265a1697f3782fdcf6c572d8e56979b9ccf39ffcf6cad67f9b2a5b8f2956bf3b00700
[Synchronizer] expected hash: b46f650a64fcd5e7ceb2ca569b44b6b65565ed3cfb20322885f134df64bb4dcc
[Synchronizer] actual hash..: eb27801f5614af0ce32e188b36c8f16018f484ffaec1e2158207720e1b4a1c20

blockchain shows transaction b46f650a64fcd5e7ceb2ca569b44b6b65565ed3cfb20322885f134df64bb4dcc exists, and has 1NfaygNyzo9DAsA8x5A85FaLcr7KzXgEtG as an output.

**Comment by ecdsa** [comment]
closing because 2.7.9
