### ISSUE TITLE
Sweeping/importing private keys doesn't ignore comments

### ISSUE THREAD

**Issue by Bomper** [spesmilo/electrum#3721]
I'm migrating from Multibit, which exports a key file in the following format:

```
# KEEP YOUR PRIVATE KEYS SAFE !
# Anyone who can read this file can spend your bitcoin.
#
# Format:
#   <Base58 encoded private key>[<whitespace>[<key createdAt>]]
#
#   The Base58 encoded private keys are the same format as
#   produced by the Satoshi client/ sipa dumpprivkey utility.
#
#   Key createdAt is in UTC format as specified by ISO 8601
#   e.g: 2011-12-31T16:42:00Z . The century, 'T' and 'Z' are mandatory
#
Kz...restOfTheKey YYYY-MM-DDTHH:MM:SS
Kz...restOfTheKey YYYY-MM-DDTHH:MM:SS
```

The Sweep button is disabled until I manually delete the comment lines and the timestamps at the end. This should be an easy fix, probably changing one regexp.

**Comment by AbdussamadA** [comment]
Electrum supports sweeping mini keys and full private keys in wallet import format. It doesn't support random EoL wallet's backup formats. You need to just copy paste the the private keys. Perhaps use sed and cut to remove the extra junk.
