### ISSUE TITLE
"Fee: unknown" on all sweeping transactions

### ISSUE THREAD

**Issue by Bomper** [spesmilo/electrum#3722]
I've just swept a few Base58 private keys, and in the Sweep window, the fee was clearly estimated each time. However, when I double-click each transaction, I see "Fee: unknown". If I look up the txid on Blockchain.info, it does show the fee amount.

![image](https://user-images.githubusercontent.com/34669048/34936071-dd3bedcc-f994-11e7-9999-d18c0341760c.png)

Version 3.0.5. Possibly related to #3421.

**Comment by ecdsa** [comment]
this is completely unrelated. 
we should add a help text that explains why we dont compute fee of incoming transactions

**Comment by fresheneesz** [comment]
I'm seeing fee: unknown on *all*  my transactions, even ones with 8000+ confirmations

**Comment by SomberNight** [comment]
fixed by https://github.com/spesmilo/electrum/commit/7bcb59ffb5a30d3a116b086c9ae291bf4bb788f3
