### ISSUE TITLE
Security flaw?

### ISSUE THREAD

**Issue by Logic999** [spesmilo/electrum#3727]
- I am using Windows7, Electrum version 3.0.5
- I had a watching wallet on Electrum as default.
- I used an offline wallet on the same computer offline, and deleted the wallet file from appdata/roaming/electrum. This is the wallet that is being 'watched'.
- While the watching wallet was open I was able to go to 'recently open', and I could open the 'offline wallet' of that watching wallet without entering the offline wallet seed, despite that 'offline wallet' NOT existing in my appdata/roaming/electrum wallet folder or anywhere else on my computer. (As far as i'm aware)
I'm no technical expert, but that seems like a security flaw to me.
Hope that information can be of service to you.
All the best,

**Comment by SomberNight** [comment]
> I used an offline wallet on the same computer offline, and deleted the wallet file from appdata/roaming/electrum. This is the wallet that is being 'watched'.

That is not how you should do this. That wallet is not "offline".  That is not what offline means in a cryptocurrency context. Once the private keys touch that machine, that machine should never again be connected to the Internet or if possible any network. You are doing it wrong, and this only provides you a false sense of security.

As for the actual bug report, I was only able to reproduce the following:
- start Electrum to open wallet A
- open wallet B
- close wallet B
- close wallet A, and hence Electrum altogether
- start Electrum to open wallet A 
- note: wallet B should be in the "Recently open" menu
- open wallet B
- close wallet B
- delete wallet file for B on the file system
- use the "Recently open" menu to open wallet B
    - it works
