### ISSUE TITLE
Make interface even more radically different for testnet vs. realnet/mainnet

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3728]
Thank you for implementing #3491. However I think now we should take ideas from Firefox and Chromium "private / incognito browsing" windows, and make the interface even more radically different for testnet vs. realnet. Be it a different background color, or like epiphany browser, some eyeball logo, or say like some wikis, where there is a big tilted word "DRAFT" on the canvas when one is editing a draft. I leave it up to you.

(OK please make it not actually "radically different", but superficially radically different.)

**Comment by bauerj** [comment]
We could change the application icon for testnet. Do you think that would be sufficient?

**Comment by ser** [comment]
No, icon is not enough.

**Comment by bauerj** [comment]
Well, I wouldn't want to mess with the colour scheme as that is guaranteed to cause problems with conflicting system styles.

**Comment by shamoons** [comment]
What about adding `[testnet]` on all buttons, menu items?

**Comment by jidanni** [comment]
All the above, plus https://www.google.com/search?q=trac+draft+watermark&tbm=isch .

**Comment by SomberNight** [comment]
A warning popup that the user explicitly has to close was added in https://github.com/spesmilo/electrum/commit/99f9a1b4847422ab78799f187c46a4bde7ed34dd (3.3.5).

**Comment by ecdsa** [comment]
> A warning popup that the user explicitly has to close was added in 99f9a1b (3.3.5).

indeed I forgot about that popup. I guess this issue can be closed?
