### ISSUE TITLE
Imported Addresses wallet can only "create" txns with p2pkh inputs

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3738]
Offline signing with imported wallets only works for p2pkh inputs.

https://github.com/spesmilo/electrum/blob/0dfaf9b97013ce9221bc8589ad806e52643e727d/lib/wallet.py#L1560-L1561

^ that line, it all starts with that line :)
The point is that an Imported Addresses wallet does not know what `txin_type` should be.

So...
the input script will be constructed as if it was p2pkh
https://github.com/spesmilo/electrum/blob/0dfaf9b97013ce9221bc8589ad806e52643e727d/lib/transaction.py#L718-L719

and the partial txn will be serialised using the legacy format because the input will never be seen as segwit

https://github.com/spesmilo/electrum/blob/0dfaf9b97013ce9221bc8589ad806e52643e727d/lib/transaction.py#L684-L690

https://github.com/spesmilo/electrum/blob/0dfaf9b97013ce9221bc8589ad806e52643e727d/lib/transaction.py#L805-L806

https://github.com/spesmilo/electrum/blob/0dfaf9b97013ce9221bc8589ad806e52643e727d/lib/transaction.py#L815-L821

which also means it won't contain `value` for the input.

**Comment by SomberNight** [comment]
Maybe we should scrap transaction.py and implement https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki :)

**Comment by ecdsa** [comment]
bip174 is too big and ambitious. 
implementing it would slow down other high priority projects.
