### ISSUE TITLE
The python3crystax recipe can only be built when using the CrystaX NDK. Exiting.

### ISSUE THREAD

**Issue by LorDo** [spesmilo/electrum#3740]
python3crystax says that it works only with a CrystaX NDK but it already loaded the CrystaX NDK!

```
ubuntu@LINUX-UNUNTU:~/Desktop/electrum_test-master/dist$ ./contrib/make_apk
~/Desktop/electrum_test-master/dist/lib ~/Desktop/electrum_test-master/dist
~/Desktop/electrum_test-master/dist
3.0.5.0
~/Desktop/electrum_test-master/dist/gui/kivy ~/Desktop/electrum_test-master/dist
make[1]: Entering directory '/home/ubuntu/Desktop/electrum_test-master/dist/gui/kivy'
#running pre build setup
#copy electrum to main.py
make[1]: Leaving directory '/home/ubuntu/Desktop/electrum_test-master/dist/gui/kivy'
#Check configuration tokens
#Ensure build layout
#Create directory /home/ubuntu/Desktop/electrum_test-master/dist/bin
#Check configuration tokens
#Preparing build
#Check requirements for android
#Run 'dpkg --version'
#Cwd None
b"Debian 'dpkg' package management program version 1.18.24 (amd64).\n"b'This is free software; see the GNU General Public License version 2 or\nlater for copying conditions. There is NO warranty.\n'# Search for Git (git)
#-> found at /usr/bin/git
#Search for Cython (cython)
#-> found at /usr/local/bin/cython
#Search for Java compiler (javac)
#-> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
#Search for Java keytool (keytool)
#-> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
#Install platform
#Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10,<1.12.5" "jinja2" "six"'
#Cwd None
#Apache ANT found at /home/ubuntu/.buildozer/android/platform/apache-ant-1.9.4
#Android SDK found at /home/ubuntu/.buildozer/android/platform/android-sdk-20
# Android NDK found at /opt/crystax-ndk-10.3.2
#Check application requirements
#Check garden requirements
#Compile platform
#Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=Electrum --bootstrap=sdl2 --requirements=python3crystax,android,openssl,plyer,kivy==master --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build'
#Cwd /opt/python-for-android
[INFO]:    Recipe kivy: version "master" requested
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (15, 19, 24)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['hostpython3crystax', 'openssl', 'plyer', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'android', 'pyjnius', 'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name Electrum and recipes (python3crystax, android, openssl, plyer, kivy)
[INFO]:    Dist will also contain modules (plyer) installed from pip
[INFO]:    -> running cp -r /opt/python-for-android/pythonforandroid/bootstraps/sdl2/build /home/ubuntu/Desktop/elect...(and 104 more)
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Recipe build order is ['hostpython3crystax', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3crystax', 'sdl2', 'six', 'android', 'pyjnius', 'kivy']
[INFO]:    The requirements (plyer) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3crystax
[INFO]:    Skipping hostpython3crystax download as no URL is set
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/openssl
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/openssl
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.0.2h.tar.gz
[INFO]:    openssl download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    sdl2_image download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading python3crystax
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/python3crystax
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/python3crystax
[INFO]:    -> running basename https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
[INFO]:    python3crystax download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    sdl2 download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/six
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    six download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    pyjnius download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    kivy download already cached, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3crystax for armeabi-v7a
[INFO]:    Skipping hostpython3crystax unpack as no URL is set
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.0.2h.tar.gz
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Unpacking python3crystax for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a
[INFO]:    python3crystax is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python3crystax/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    -> running rm -rf /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/o...(and 59 more)
[INFO]:    -> running cp -a /opt/python-for-android/pythonforandroid/recipes/android/src /home/ubuntu/Desktop/electru...(and 119 more)
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/build/other_builds/kivy-python3crystax-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /opt/python-for-android
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3crystax for armeabi-v7a
[INFO]:    hostpython3crystax has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3crystax for armeabi-v7a
[INFO]:    python3crystax has no prebuild_armeabi_v7a, skipping
# [ERROR]:   The python3crystax recipe can only be built when using the CrystaX NDK. Exiting.
#Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=Electrum --bootstrap=sdl2 --requirements=python3crystax,android,openssl,plyer,kivy==master --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build
#
#Buildozer failed to execute the last command
#The error might be hidden in the log above this error
#Please read the full log, and search for it before
#raising an issue with buildozer itself.
#In case of a bug report, please add a full log with log_level = 2
make[1]: Entering directory '/home/ubuntu/Desktop/electrum_test-master/dist/gui/kivy'
#Cleaning up
#rename main.py to electrum
#remove buildozer.spec
make[1]: Leaving directory '/home/ubuntu/Desktop/electrum_test-master/dist/gui/kivy'
~/Desktop/electrum_test-master/dist
```

**Comment by LorDo** [comment]
I am reinstall NDK and this fix, but i get new error

`[INFO]:    Recompiling python-crystax
[INFO]:    -> running build-target-python.sh --ndk-dir=/opt/crystax-ndk-10.3.2 --abis=armeabi-v7a -j5 --verbose /home/ubuntu/Desktop...(and 132 more)
Exception in thread background thread for pid 11660:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /opt/crystax-ndk-10.3.2/build/tools/build-target-python.sh --ndk-dir=/opt/crystax-ndk-10.3.2 --abis=armeabi-v7a -j5 --verbose /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a/python3crystax

  STDOUT:
cat: /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a/python3crystax/Include/patchlevel.h: No such file or directory
cat: /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a/python3crystax/Include/patchlevel.h: No such file or directory
ERROR: Can't detect python major version.


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/opt/python-for-android/pythonforandroid/build.py", line 574, in build_recipes
    recipe.build_arch(arch)
  File "/opt/python-for-android/pythonforandroid/recipes/python3crystax/__init__.py", line 250, in build_arch
    self.get_build_dir(arch.arch))
  File "/opt/python-for-android/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 720, in next
    self.wait()
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /opt/crystax-ndk-10.3.2/build/tools/build-target-python.sh --ndk-dir=/opt/crystax-ndk-10.3.2 --abis=armeabi-v7a -j5 --verbose /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a/python3crystax

  STDOUT:
cat: /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a/python3crystax/Include/patchlevel.h: No such file or directory
cat: /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-version3.5/armeabi-v7a/python3crystax/Include/patchlevel.h: No such file or directory
ERROR: Can't detect python major version.


  STDERR:

b'\x1b[0m\r           working: cat: /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-v...(and 84 more)  'b'\x1b[0m\r           working: cat: /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/python3crystax-v...(and 84 more)  'b"\x1b[0m\r           working: ERROR: Can't detect python major version.`

**Comment by LorDo** [comment]
I am clear chace and fix it, but it is not last error :D 
Next error:

`[INFO]:    Building six for armeabi-v7a

[INFO]:    six apparently isn't already in site-packages

[INFO]:    Installing six into site-packages

[INFO]:    -> directory context /home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/build/other_builds/six-python3crystax/armeabi-v7a/six

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/opt/python-for-android/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/opt/python-for-android/pythonforandroid/build.py", line 574, in build_recipes
    recipe.build_arch(arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 775, in build_arch
    self.install_python_package(arch)
  File "/opt/python-for-android/pythonforandroid/recipe.py", line 789, in install_python_package
    hostpython = sh.Command(self.hostpython_location)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1028, in __init__
    raise CommandNotFound(path)

sh.CommandNotFound: python3.5
`

**Comment by LorDo** [comment]
And, i create symlink python3.5 to python3.6 and fix it, but next error : 

`#Package the application

Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.35.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python3.6/dist-packages/buildozer-0.35.dev0-py3.6.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/buildozer-0.35.dev0-py3.6.egg/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.6/dist-packages/buildozer-0.35.dev0-py3.6.egg/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.6/dist-packages/buildozer-0.35.dev0-py3.6.egg/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python3.6/dist-packages/buildozer-0.35.dev0-py3.6.egg/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python3.6/dist-packages/buildozer-0.35.dev0-py3.6.egg/buildozer/targets/android.py", line 648, in build_package
    version = self.buildozer.get_version()
  File "/usr/local/lib/python3.6/dist-packages/buildozer-0.35.dev0-py3.6.egg/buildozer/__init__.py", line 710, in get_version
    with open(fn) as fd:

FileNotFoundError: [Errno 2] No such file or directory: './contrib/versions.py'
Makefile:20: recipe for target 'apk' failed
make: [apk] Error 1 (ignored)
make[1]: Entering directory '/home/ubuntu/Desktop/electrum_test-master/dist/gui/kivy'
#Cleaning up
#rename main.py to electrum
#remove buildozer.spec
make[1]: Leaving directory '/home/ubuntu/Desktop/electrum_test-master/dist/gui/kivy'
~/Desktop/electrum_test-master/dist
`

**Comment by LorDo** [comment]
AAAND, i create versions.py manualy and fix it, but i ger new error: 

`[DEBUG]:   	:compileDebugJavaWithJavac

[DEBUG]:   	:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
[DEBUG]:   	/home/ubuntu/Desktop/electrum_lbtc-master/dist/.buildozer/android/platform/build/dists/Electrum/src/main/java/org/kivy/android/PythonService.java:108: error: multi-catch statement is not supported in -source 1.6
[DEBUG]:   	            } catch (NoSuchMethodException | IllegalAccessException |
[DEBUG]:   	                                           ^
[DEBUG]:   	  (use -source 7 or higher to enable multi-catch statement)
[DEBUG]:   	1 error
[DEBUG]:   	:compileDebugJavaWithJavac FAILED
[DEBUG]:   	
[DEBUG]:   	FAILURE: Build failed with an exception.
[DEBUG]:   	
[DEBUG]:   	* What went wrong:
[DEBUG]:   	Execution failed for task ':compileDebugJavaWithJavac'.
[DEBUG]:   	> Compilation failed; see the compiler error output for details.
[DEBUG]:   	
[DEBUG]:   	* Try:
[DEBUG]:   	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[DEBUG]:   	
[DEBUG]:   	BUILD FAILED
`

how to change source ?

**Comment by SomberNight** [comment]
> [DEBUG]: /home/ubuntu/Desktop/electrum_test-master/dist/.buildozer/android/platform/build/dists/Electrum/src/main/java/org/kivy/android/PythonService.java:108: error: multi-catch statement is not supported in -source 1.6
[DEBUG]: } catch (NoSuchMethodException | IllegalAccessException |
[DEBUG]: ^
[DEBUG]: (use -source 7 or higher to enable multi-catch statement)

https://github.com/spesmilo/electrum/blame/21e44bdb57c3d60db91c877931df7847f272503a/gui/kivy/Readme.md#L75-L77

Please read the build instructions.

**Comment by LorDo** [comment]
"Use the stable branch of python-for-android."

How can I do it ?

**Comment by LorDo** [comment]
I am already use stable 

![image](https://user-images.githubusercontent.com/1587284/35104482-0aaead16-fc7a-11e7-95ca-d032966deab8.png)

**Comment by LorDo** [comment]
Please upload valid python-for-android for compile electrum

**Comment by bauerj** [comment]
You can try to manually reset HEAD to before the commit mentioned in the FAQ and then merge the ssl branch.

**Comment by bauerj** [comment]
@LorDo Can you try from scratch with the updated instructions?

**Comment by KaboomFox** [comment]
I am still having this issue with the updated instructions.

**Comment by Neustart** [comment]
Hi there
I have the same issue
I've open issue here : https://github.com/kivy/python-for-android/issues/1225

**Comment by Neustart** [comment]
@LorDo how you reinstall NDK ? Because me simply extract NDK archive, put correct path into buildozer.spec, set correct path into ANDROIDNDK global variable and still having a problem

**Comment by Neustart** [comment]
@bauerj @SomberNight  could somebody share p4a folder ? I faced completely the same issue. I am on stable branch of p4a now. I did all merges. I did everything by instruction step by step

**Comment by Neustart** [comment]
@LorDo how and where did you create version.py file ?

**Comment by Neustart** [comment]
@LorDo take a look here: I've described why source -7 issue happens and how to resolve it 
https://github.com/spesmilo/electrum/issues/3832

**Comment by ecdsa** [comment]
I had the same issue recently. 
The commit mentioned in the FAQ was there, but I also had to upgrade android sdk tools.
