### ISSUE TITLE
problems with BitPay

### ISSUE THREAD

**Issue by sHaggYcaT** [spesmilo/electrum#3742]
I tryed to pay using BitPay, and I can't. I got an error:

payment URL not pointing to a valid server

Maybe they or you updated something?

**Comment by ecdsa** [comment]
please post the payment url

**Comment by Perlover** [comment]
I paid in Bitpay and i didn't have problem
In Bitpay you need to get payment URL (second tab in Bitpay invoice) and after this URL should be entered to "address" in "Send" tab of Electrum. I did it and Electrum parsed successfully this BIP70 URL

**Comment by ecdsa** [comment]
closing, no answer

**Comment by sHaggYcaT** [comment]
The problem was in Tor network: the BitPay doesn't allow it.
And it's impossible to understand it using error message
