### ISSUE TITLE
Android App Issues

### ISSUE THREAD

**Issue by gbd-douglas** [spesmilo/electrum#3744]
Hi there,

I tried to send BTC from the Android app on my smartphone earlier by scanning the generated QR code of the recipient. I entered my details, but twice it bounced back to my phone stating "Unable to find Server". In the end, I made the transaction from my Electrum wallet on my computer to the recipient, which worked fine.

I've also noticed that ocassionally the Android app closes unexpectedly when I try and open it.

Thanks,

gbd-douglas

**Comment by SomberNight** [comment]
There have been lots of changes since the issue was opened, that could have fixed both issues mentioned.
