### ISSUE TITLE
Android app blocks at logo

### ISSUE THREAD

**Issue by tallero** [spesmilo/electrum#3745]
I used an android device as cold storage using electrum as wallet. Now the app doesn't open anymore and doesn't go past logo. This happens with both 2.8.2 and 3.0 versions.

**Comment by bauerj** [comment]
Did you try to remove the app data/uninstall the app?

**Comment by tallero** [comment]
I copied the wallet on PC and I opened through electrum desktop app. Anyway it now ask for password. Anyway, I don't remember electrum for android ever asking me for a password when setting up the wallet. Is it possible?

**Comment by SomberNight** [comment]
> It just creeps me out that exists the chance that the app could just stop opening it without any apparent reason. It means that the only way to avoid any kind of problem when securing BTC on android needs a rooted device.

You should keep a backup of your seed words.
