### ISSUE TITLE
problem with fees

### ISSUE THREAD

**Issue by tecnopro98** [spesmilo/electrum#3747]
Hello, I just made my first transaction to send bitcoins with electrum.

Here is the transaction id: e11516acefeed4753f5e41128de6a7ec9d5a4087175a56ca9ef37a2fe909aa96

and my address BTC 1FMxxG5M3t4CJJWMQ3TtDHgVMqWMSbvJNK

As you can see on blockchain.info, I sent 0.0001 BTC (nearly $ 1.25)
it was to give a try ...

Unfortunately, the fee for this transaction was .... $ 13

Electrum was set with default settings ...

I think there is a problem and that electrum should prevent when the tax exceeds the amount of the transaction, especially when it comes to 10X the amount of the transaction.

I am a student and I can not afford to pay $ 13 to send $ 1 ...
I hope there is a way to get my money back.

Good luck for the rest of your project.

Michael

**Comment by ramontayag** [comment]
@tecnopro98 there is no way to get it back unless the miner gives it to you.

**Comment by AbdussamadA** [comment]
Create a testnet wallet by running electrum with the --testnet switch for example: `electrum --testnet -w testnet_wallet`. Then you can receive money to it via faucets like the one below:

https://testnet.manu.backend.hamburg/faucet

You can play around with testnet bitcoins.

**Comment by SomberNight** [comment]
Fees do not directly depend on the number of coins being sent. Bitcoin is currently not suitable for microtransactions.
