### ISSUE TITLE
Get address at specific index

### ISSUE THREAD

**Issue by ramontayag** [spesmilo/electrum#3754]
I'm looking for a way to get an address at a specific index. I don't see anything in the docs or the code, so I hope I'm mistaken. I was thinking something like:

```
electrum getaddress --receiving=0 (1st receiving address)
electrum getaddress --change=3 (4th change address)
```

Does this sound reasonable?

**Comment by AbdussamadA** [comment]
It can be done via the console like i told you on reddit. Does that suffice?

**Comment by bauerj** [comment]
What exactly is your use-case?

**Comment by ramontayag** [comment]
@AbdussamadA it can be done in the console, but I was hoping to do it via RPC. It looks like it's not there though, so some changes will have to be made if they're acceptable.

@bauerj thinking of assigning an address to each user. Being able to query with the index does not require saving the wallet file itself (which allows for less things to worry about and back up).

**Comment by AbdussamadA** [comment]
In order to give you an address electrum daemon will need the wallet file on your server. It can be a watch only wallet that can't be spent from. You don't have to back it up if you don't want to. It can be recreated from the master public key of the seeded wallet. You can get to that via wallet menu > information.

Also, in any case, one backup is good for life when it comes to deterministic wallets.

**Comment by ramontayag** [comment]
@AbdussamadA that's correct I just need to backup the seed (or seeds in the case of a multi-sig setup). And yes I understand I don't *need* to backup the wallet file itself, but the issue is that `createnewaddress` will start from the beginning again (index 20 by default), in case the wallet file is lost.

In the case of an app that requests for a new address when a user registers, it will ping Electrum, see that the address it returns has been assigned to a user before, and then ping again until it sees as address that has not been used before. Via JSON-RPC, it takes .7 seconds for 10 addresses, so with 1000 used addresses it will take 70 seconds to find a fresh address.

This isn't a very big issue, I just really wanted to know if it was supported as an API. It looks like it isn't based on the replies. Will close this issue. Thanks for the suggestions!
