### ISSUE TITLE
Problems sending funds out of wallet

### ISSUE THREAD

**Issue by BKG2017** [spesmilo/electrum#3755]
I have over 80 Euro in my electrum wallet but it won't let me send anything out it says insufficient funds 
even tho i have the funds there in wallet in plain view  when i click the max button to send the max amount out it says 0mbtc which is ridiculus i only put the money into the wallet the day before and still i can't get it out.

The issue is on the android app and i have synched the wallet to the windows version and still the same problem on both platforms money is there but won't let it out

I have also updated the app to recent version 
![26996010_10211355064258008_1543367780_n](https://user-images.githubusercontent.com/27025780/35193874-aaa60e6c-fea1-11e7-86b4-011f3f5b9580.png)
![27045294_10211355064178006_1668518362_n](https://user-images.githubusercontent.com/27025780/35193875-aac0cd6a-fea1-11e7-9e8e-7713e0af00bc.png)
![27043327_10211355079818397_700333247_n](https://user-images.githubusercontent.com/27025780/35193899-08c11f3c-fea2-11e7-98e8-2edd61b36d6d.png)

**Comment by SomberNight** [comment]
That 8.7 mBTC is spread across 16 UTXOs, the fee to spend those are hence high. :/
See https://github.com/spesmilo/electrum/issues/3729#issuecomment-359179092

**Comment by cculianu** [comment]
Welcome to the joy of HIGH tx fees. :)
