### ISSUE TITLE
Electrum3.0.5 testnet mode

### ISSUE THREAD

**Issue by ja-heller** [spesmilo/electrum#3756]
Using electrum 3.0.5 on OS X in testnet mode, everytime I try to open a multisig transaction, which is already signed by one member, electrum is crashing.

Here's the HEX of the signed transaction:.

`02000000025cdbd2f54ff94715e5588a6f5c2e1cfc732310dcd3be1291f4f5779519cb331a00000000b40047304402202b4107485958bbbbdbcb825d867cbfa52d4c37d11223289e2d061da5ba7c78df0220294a44394d7e6f5716fc3ee1b202056b423c09ed4b675d8172d8d7a1931cc73f014c69522103294d610a4609abf49dcfa806cdbe0c07aca02e8785cea245a5bef2cb3f1679992102c1b71de5d89ee390341bf0ead4431144e488394c24400fd42fded4b60991139321021a1ae7bbcd0972b17b9bb0ed22642f4f67e64b7901fc2a41e7fa4eaf0cc7f38853aeffffffff19bba1d24e80cc1721d1c54c094fe46985f0aa742c71d7b70d26b148e4636c6e00000000b4004730440220383a3a730e39aabb7eef2e7203e4a7f6bdf8ba772ebacd544a117d28fd5475fd022000f7c8d91e7542e4d2705fe4e058877b34da37b8b41df52c515547986fb95e00014c69522103294d610a4609abf49dcfa806cdbe0c07aca02e8785cea245a5bef2cb3f1679992102c1b71de5d89ee390341bf0ead4431144e488394c24400fd42fded4b60991139321021a1ae7bbcd0972b17b9bb0ed22642f4f67e64b7901fc2a41e7fa4eaf0cc7f38853aeffffffff02307c5b020000000017a91402eb494a5ddbe6bddac1cf613a5fc45b9ffbb1708780234300000000001976a914d3c541240245fe68cff624b8248fd06d5be4d5f288ac00000000 `

All the best;

**Comment by SomberNight** [comment]
Can you provide more details regarding how this transaction was created?
- This is with a 2-of-3 standard (non-segwit) multisig wallet, right?
- What version of Electrum was used to create the txn (is the other cosigner who signed first also using 3.0.5)?
- Do you have steps to reproduce creating such a malformed partial txn as your example?

**Comment by SomberNight** [comment]
The sequence number being `0xffffffff` suggests the txn wasn't created with a recent version of Electrum.

**Comment by SomberNight** [comment]
Closing; no response. Please reopen if all signers were using recent versions of Electrum.
