### ISSUE TITLE
execute sudo ./contrib/make_apk errors

### ISSUE THREAD

**Issue by ypc1117** [spesmilo/electrum#3763]
Hi guys. i tried to execute the command "sudo ./contrib/make_apk" to package a apk. 
unfortunately,errors occured.  here are my error message: 
![2018-01-23 11 19 39](https://user-images.githubusercontent.com/15722845/35256604-8b2b1f84-002f-11e8-810c-e9eb0f7ccaa3.png)

**Comment by ypc1117** [comment]
give me some advice, thanks

**Comment by bauerj** [comment]
Hey,

the version should only consist of numbers and dots. You added parentheses, that's why it fails.
