### ISSUE TITLE
Electrum password bug

### ISSUE THREAD

**Issue by corrinedk** [spesmilo/electrum#3767]
My electrum password works perfectly. Until I try to decrypt a message. Then I get a yellow triangle with an exclamation point ( ! ) in the middle. No error text.  Help?

**Comment by ecdsa** [comment]
are you using the latest version?

**Comment by corrinedk** [comment]
Yes, I'm using a most recent version I downloaded yesterday,.
    On Wednesday, January 24, 2018, 5:34:41 AM EST, ThomasV <notifications@github.com> wrote:  
 
 
are you using the latest version?

**Comment by corrinedk** [comment]
I wanted to mention something else I just noticed too. Even if I try to open electrum 3.0.5 it always opens 3.0.1 yet there are no other versions on my computer anymore.

**Comment by ecdsa** [comment]
was the message encrypted by Electrum?

**Comment by corrinedk** [comment]
No, the encryption was  a  ---begin pgp, end pgp--- from, CGMC website (dark net). I was being required to decrypt the message to put in an authentication code so multi sig would be completed. But electrum isnt working right for decryption and i tried everything on google, including reading a thousand pages that made no sense to me :(     On Wednesday, January 24, 2018, 3:06:45 PM EST, ThomasV <notifications@github.com> wrote:  
 
 
was the message encrypted by Electrum?

**Comment by ecdsa** [comment]
please learn how encryption works before posting issues

**Comment by corrinedk** [comment]
I know how it works, I've done this before. But Electrum HAS NEVER given me errors trying to decrypt.  I listed the errors. Just because I dont know what an error means doesnt mean I shouldnt post an issue. That was so rude, I can't believe it. Try being kinder to people. This turned me off to this website 100%. That doesnt affect you but it sure will let me avoid rude messages. Have a nice f'n day.
    On Wednesday, January 24, 2018, 3:46:07 PM EST, ThomasV <notifications@github.com> wrote:  
 
 
please learn how encryption works before posting issues
