### ISSUE TITLE
Android virtual keyboard overlaps with buttons on small screen sizes

### ISSUE THREAD

**Issue by kollokollo** [spesmilo/electrum#3768]
... because the Back Button overlaps the key-buttons. (See screenshot)

![a](https://user-images.githubusercontent.com/15250834/35326529-dafe2b36-00ee-11e8-87f4-8766c185a567.png)

**Comment by andronoob** [comment]
Also, the settings may also show overlapped items on some phones.

**Comment by SomberNight** [comment]
Closing as the kivy GUI was removed in https://github.com/spesmilo/electrum/pull/8591
