### ISSUE TITLE
Electrum doesnt run on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by kollokollo** [spesmilo/electrum#3769]
Having followed the officuial installation instructions
`sudo pip3 install https://download.electrum.org/3.0.5/Electrum-3.0.5.tar.gz`
I get:

>electrum
Error: No module named 'pyaes'. Try 'sudo pip install <module-name>'
>sudo pip install pyaes
Requirement already satisfied: pyaes in /usr/local/lib/python3.5/dist-packages

**Comment by AbdussamadA** [comment]
Maybe use 2.9.4? https://github.com/spesmilo/electrum/issues/3696

**Comment by SomberNight** [comment]
You might have another instance of electrum that is being run when you execute `electrum`.
Also, make sure you are using the same version of python to run electrum and when you invoke pip.

**Comment by kollokollo** [comment]
Well, it is all strange, however running electrum out of the directory where Electrum-3.0.5.tar.gz was untared to works for me now. I have no knowledge about python, so I do not know what to do other than following the installation instructions on Electrum`s homepage. Maybe they could be improved....
