### ISSUE TITLE
What happened to Gap Limit? 

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#377]
And why isn't it's removal in the release notes?
How does this affect merchant/server use of Electrum?

**Comment by markasoftware** [comment]
Any way to create addresses beyond the gap limit from the command line or using the RPC interface? I'm writing a non-python application.

**Comment by Engelberg** [comment]
I'd like to better understand what the recommended approach is, because merchant services are still recommending using Electrum and changing the gap limit.  I imagine that's hard on Electrum servers, so if there's a better way, I'd like to know it.
