### ISSUE TITLE
Help please! Version of the purse Electrum 3.0.5

### ISSUE THREAD

**Issue by Alexey1131** [spesmilo/electrum#3772]
Hello! I sent money from Electrum purse. The purse has generated an address for the exchange of 1KHzKdiLLb9nMAdXPo8BuzQU7421BS6Uvr. At this address, a part of my funds were suspended, as early as 3 days they do not come to the address 1H5udNgCgjNwWEt4zZGhUVPGDCkWxHnooy. Tell me where they went and will they come back to me?

**Comment by bauerj** [comment]
Sorry, I don't understand your question.

You sent coins from Electrum to an exchange? Which of these addresses belongs to your wallet? What exactly went wrong?

**Comment by Alexey1131** [comment]
My wallet 3Lccs7ocCn5NDtW82Xewd42qrQZenwzY4M

**Comment by Alexey1131** [comment]
The addresses listed above are the bills sent to the stock exchange 1H5udNgCgjNwWEt4zZGhUVPGDCkWxHnooy to this address the amount has come, and at the address of the exchange 1KHzKdiLLb9nMAdXPo8BuzQU7421BS6Uvr the amount must also be taken to the binance but it is where it is stuck! (

**Comment by bauerj** [comment]
So this is an issue with the exchange and not Electrum?

**Comment by Alexey1131** [comment]
Maybe. the first time dispatched. and I'm waiting for a long time and I do not know what became of them !? In blockchain.info you can see where you left off and where you left. Purse Electrum generated this address 1KHzKdiLLb9nMAdXPo8BuzQU7421BS6Uvr.

**Comment by AbdussamadA** [comment]
You have a 2fa wallet so the money sent to 1KH.. is for 2fa fees. Click on the blue shield icon in the bottom right for more information.

**Comment by Alexey1131** [comment]
As I understand! I paid the commission for 20 transactions in Electrum purse?

**Comment by SomberNight** [comment]
(The relevant txn is 741bbe6db74d0b0a4070425043cca80a1565025ba7144334ae3138cd15df4f19)

> I paid the commission for 20 transactions in Electrum

Yes. This was described when you initially set up your wallet. You can read more about it [here](https://api.trustedcoin.com/#/electrum-help).
