### ISSUE TITLE
Multisig wallet with Trezor gives different xpub than Trezor

### ISSUE THREAD

**Issue by abrkn** [spesmilo/electrum#3773]
Version: 3.0.5
OS: macOS High Sierra

## Steps

![image](https://user-images.githubusercontent.com/843958/35405772-949e2d7c-01dd-11e8-8a5a-ec610210b3b6.png)

![image](https://user-images.githubusercontent.com/843958/35405830-9b00a15e-01dd-11e8-963b-220cee57e560.png)

![image](https://user-images.githubusercontent.com/843958/35405838-9f79c698-01dd-11e8-82b8-1d3d08516614.png)

![image](https://user-images.githubusercontent.com/843958/35405849-a70cbc6c-01dd-11e8-8ebf-ad45ff4b6b44.png)

![image](https://user-images.githubusercontent.com/843958/35405874-b9e1cc92-01dd-11e8-808a-87149c269be7.png)

![image](https://user-images.githubusercontent.com/843958/35405912-dc50d8b8-01dd-11e8-82c9-4790c58f4078.png)

![image](https://user-images.githubusercontent.com/843958/35406112-718ef928-01de-11e8-96fc-2f7ef113ca5e.png)

^ The xpub in this picture is not consistent with what is displayed in Trezor:

![image](https://user-images.githubusercontent.com/843958/35406155-886e5008-01de-11e8-90c3-8a80b068fd5a.png)

Both images are censored, but you can see they end in different characters.

What is the reason for this? Which path is Electrum using?

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/blob/78338c74eb4e1b00cf77adbd89426096d3e990d6/lib/base_wizard.py#L229-L232
Multisig wallets use keys derived from a different path to avoid key reuse.
