### ISSUE TITLE
no info for electrum wallet on block explorer 

### ISSUE THREAD

**Issue by kippy100** [spesmilo/electrum#3780]
i have a little amount btc in electrum wallet 3.0.5 but i cant find them in any block explorer ??
downloaded the wallet from original source transaction from exchange to wallet oke 
this is my recieve adress and yes it is protected :  15w3Gt58W73jcvQZ9vyrKCR1hyxJ2sNvfZ

**Comment by bauerj** [comment]
Hey,

you actually have an infinite amount of addresses with Electrum. It will always generate a fresh one when you used one to improve privacy.

To see all your addresses (and also then one that has funds on it), you can enable the addresses tab from the View menu.

**Comment by bauerj** [comment]
You can always use the same address if you want to but Electrum will always suggest a different address.

And yes, your password encrypts the whole wallet and thus all addresses in it. Make sure that you also have the seed written down somewhere safe!

**Comment by kippy100** [comment]
thank you very muts for this info ! great support guys ;-)

**Comment by bauerj** [comment]
You're welcome!

**Comment by kippy100** [comment]
thanks ow btw can i see the seed from the menu seed ? for extra copying to save it ?

**Comment by bauerj** [comment]
Yes.

**Comment by kippy100** [comment]
done... thanks and close it ;-)
