### ISSUE TITLE
[Synchronizer] cannot deserialize transaction, skipping

### ISSUE THREAD

**Issue by tudorconstantin** [spesmilo/electrum#3788]
The transaction which can not be deserialized is this [e9933221a150f78f9f224899f8568ff6422ffcc28ca3d53d87936368ff7c4b1d](https://blockchain.info/tx/e9933221a150f78f9f224899f8568ff6422ffcc28ca3d53d87936368ff7c4b1d), which looks like this serialized:
`0100000000010160f84fdcda039c3ca1b20038adea2d49a53db92f7c467e8def13734232bb610804000000232200202814720f16329ab81cb8867c4d447bd13255931f23e6655944c9ada1797fcf88ffffffff0ba3dcfc04000000001976a91488124a57c548c9e7b1dd687455af803bd5765dea88acc9f44900000000001976a914da55045a0ccd40a56ce861946d13eb861eb5f2d788ac49825e000000000017a914ca34d4b190e36479aa6e0023cfe0a8537c6aa8dd87680c0d00000000001976a914651102524c424b2e7c44787c4f21e4c54dffafc088acf02fa9000000000017a914ee6c596e6f7066466d778d4f9ba633a564a6e95d874d250900000000001976a9146ca7976b48c04fd23867748382ee8401b1d27c2988acf5119600000000001976a914cf47d5dcdba02fd547c600697097252d38c3214a88ace08a12000000000017a914017bef79d92d5ec08c051786bad317e5dd3befcf87e3d76201000000001976a9148ec1b88b66d142bcbdb42797a0fd402c23e0eec288ac718f6900000000001976a914e66344472a224ce6f843f2989accf435ae6a808988ac65e51300000000001976a914cad6717c13a2079066f876933834210ebbe68c3f88ac0347304402201a4907c4706104320313e182ecbb1b265b2d023a79586671386de86bb47461590220472c3db9fc99a728ebb9b555a72e3481d20b181bd059a9c1acadfb853d90c96c01210338a46f2a54112fef8803c8478bc17e5f8fc6a5ec276903a946c1fafb2e3a8b181976a914eda8660085bf607b82bd18560ca8f3a9ec49178588ac00000000`

Because the TX is skipped, the addresses that belong to my wallet involving that tx show as having a balance of zero and I can't get the funds out of them.

I'm using Electrum 3.0.2, but was able to reproduce it in 3.0.5.

As a quick hack, I replaced the empty `return` from [this line](https://github.com/spesmilo/electrum/blob/master/lib/transaction.py#L364) with `return [m, n, None, None, None]`, but that is not quite a fix, although it seems to work for me for now.

I tried to debug the issue, but got lost in the bitcoin and segwit protocol.

**Comment by SomberNight** [comment]
Btw can you tell who sent this txn in broad terms?

**Comment by SomberNight** [comment]
Based on https://github.com/spesmilo/electrum/issues/3798 it looks like Bitpanda is making these txns.
@ecdsa Should we do a new release?

**Comment by tudorconstantin** [comment]
Unfortunately I don't have any info regarding who created the transaction and what wallet he used to do it.

**Comment by AbdussamadA** [comment]
another person on the forum was hit by this bug: https://bitcointalk.org/index.php?topic=2843380

**Comment by ch4bes** [comment]
@AbdussamadA  and [another](https://www.reddit.com/r/Electrum/comments/7ttmeg/electrum_not_showing_balance/)

**Comment by SomberNight** [comment]
[another](https://www.reddit.com/r/Electrum/comments/7ubupo/electrum_stuck_on_synching_confirmed_tx_doesnt/) :/

**Comment by moritzgloeckl** [comment]
I was affected by this as well, but 7b8b75c7d39df2c44ebea30d1362372be830775d seems to be working and fixes the issue for me.

**Comment by SomberNight** [comment]
Note: 3.0.6 was released yesterday, and that should include the relevant fix.

**Comment by mautematico** [comment]
Another user hit, but this is not (yet) an electrum user, but a Ledger one:

https://litecointalk.io/t/ltc-transfer-to-nano-ledger-s-issues/18109


Will try to ping Ledger to fix this on their software also.
