### ISSUE TITLE
cant access electrum

### ISSUE THREAD

**Issue by flmlopes** [spesmilo/electrum#3790]
I made a payment of bitcoin using coingate to buy tokens with bitcoin. 
Now, when I try to open it, Electrum will crash when I enter the correct password. Any incorrect password will show me an alert that it's incorrect (and I am very certain that I have the right password).
The wallet is encrypted. 
I had version 3.0.2 , now updated to 3.0.5 ,but still can t access
any ideas of what might be happening? it was working fine until before this payment

**Comment by SomberNight** [comment]
- What OS are you using?
- If the OS is Linux or Mac, please try running Electrum from the terminal with the `-v` flag and paste logs. Otherwise, is there any chance you could try opening the wallet file on a Linux machine with `-v`?
- Try restoring from seed words, but keep your wallet file so that we can debug this.

**Comment by flmlopes** [comment]
how do i run electrum from the terminal ?
i am using Mac OS 10.10.5

**Comment by bauerj** [comment]
Here is how you can provide the logs:

Open the terminal app, paste

    /Applications/Electrum.app/Contents/MacOS/Electrum -v

and press return.

**Comment by flmlopes** [comment]
MacBook-Pro-de-Felipe:~ flmlopes$ /Applications/Electrum.app/Contents/MacOS/Electrum -v
[SimpleConfig] electrum directory /Users/flmlopes/.electrum
[get_server] [Errno 61] Connection refused
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0260
[Network] blockchains dict_keys([0])
[Network] starting network
[Network] connecting to btc.smsys.me:995:s as new interface
[FxThread] using exchange BitcoinAverage
[BitcoinAverage] requesting fx history for BRL
[BitcoinAverage] getting fx quotes for BRL
[WalletStorage] wallet path /Users/flmlopes/.electrum/wallets/default_wallet
[WalletStorage] wallet path /Users/flmlopes/.electrum/wallets/default_wallet
[WalletStorage] wallet path /Users/flmlopes/.electrum/wallets/default_wallet
[node1.volatilevictory.com] failed to connect [Errno 61] Connection refused
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[us.electrum.be] connected
[btc.smsys.me] connected
[electrum.qtornado.com] connected
[Network] switching to btc.smsys.me:995:s
[Network] sending subscriptions to btc.smsys.me:995:s 0 0
[Network] no height for main interface
[noserver4u.de] connected
[ele.nummi.it] connected
[electrum.cutie.ga] connected
[electrum2.villocq.com] connected
[Network] fee_estimates[25] 111272
[Network] fee_estimates[10] 190802
[Network] fee_estimates[5] 190802
[Network] fee_estimates[2] 190802
[Network] relayfee 1000
[BitcoinAverage] received fx history for BRL
[ndnd.selfhost.eu] connected
[electrum.vom-stausee.de] timeout
[electrum.be] SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[BitcoinAverage] received fx quotes
[y4td57fxytoo5ki7.onion] cannot resolve hostname
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[rbx.curalle.ovh] connected
[profiler] load_transactions 0.0002
[profiler] build_reverse_history 0.0000
[profiler] save_transactions 0.0005
[profiler] check_history 0.0006
Traceback (most recent call last):
  File "electrum", line 377, in <module>
  File "Electrum-3.0.5-py3.6.egg/electrum/daemon.py", line 304, in init_gui
  File "Electrum-3.0.5-py3.6.egg/electrum_gui/qt/__init__.py", line 249, in main
  File "Electrum-3.0.5-py3.6.egg/electrum_gui/qt/__init__.py", line 207, in start_new_window
  File "Electrum-3.0.5-py3.6.egg/electrum/wallet.py", line 970, in start_threads
  File "Electrum-3.0.5-py3.6.egg/electrum/wallet.py", line 957, in prepare_for_verifier
  File "Electrum-3.0.5-py3.6.egg/electrum/wallet.py", line 364, in add_unverified_tx
AttributeError: 'NoneType' object has no attribute 'merkle_roots'
[1110] Failed to execute script electrum
[Network] stopping network
[Daemon] shutting down network
[Plugins] stopped
[Network] stopped
[Daemon] stopped
MacBook-Pro-de-Felipe:~ flmlopes$

**Comment by flmlopes** [comment]
any ideas of what should i do? or just restore from the seed? Thanks

**Comment by SomberNight** [comment]
Thank you for this report. You should restore from seed.

**Comment by flmlopes** [comment]
ok ,i l try, thanks for the feedback. I just cant access the seed right now, only in a couple of days. Do you thinks my coins are safe? or i might have been hacked?

**Comment by SomberNight** [comment]
This is a bug in Electrum, your coins should be safe (or at least this should not affect their safety).

> I just cant access the seed right now

You can alternatively run electrum from source and merge #3791 manually; it should work.
