### ISSUE TITLE
Signed in with copy of electrum wallet/code but can't remember password or seed

### ISSUE THREAD

**Issue by swise2** [spesmilo/electrum#3800]
I can't sign a transaction because I can't remember my password to my electrum wallet, and I can't restore the wallet and create a new password because I don't have the seed. I have the coding for the wallet and am signed in, and can receive bits, but how could I fix this or bypass having to enter password to send a payment? Thanks so much

**Comment by persona5** [comment]
Your wallet is encrypted with your password. Remember it or your coins are lost.  
You should have backed up the seed.

**Comment by bauerj** [comment]
If you lost both your seed _and_ your password, you're screwed.

You can try to use btcrecover to crack your wallet password if it's short enough to be cracked easily.
