### ISSUE TITLE
How do Electrum client handle forks

### ISSUE THREAD

**Issue by alieslam** [spesmilo/electrum#3801]
I have been searching and looking up for an answer to this question for about three days and even searching within code (i am not a python programmer though) to get how Electrum clients handle forks. What i have experienced is that, server nodes doesn't inform clients with forks they already encountered, but instead they solve the fork at their side and send the next (new) block header to the client which will never be verified by the client local main chain. I was expecting that the server nodes will send the header (with same height) forks to the client so they start forking themselves, but that never happened. 
Edit: I am currently working on bitcoin testnet.

**Comment by bauerj** [comment]
Do you mean blockchain reorgs?

**Comment by alieslam** [comment]
Yes, what i am simply doing is that i am creating a SPV client connected to 5 electrum servers and everything is ok, but once a reorg happens on servers the first new header comes (equal headers from the 5 connected servers) is not verified with the last header on my local system, although the last one was verified by all connected servers (and they were all equal when they were received, which means they were on the main chain and no reorg happened back then from the point of view of my system). i want to make sure that each time a reorg happens, the servers will just send me the same equal headers and that they won't send me any different ones, as in this case i won't support handling chaining on my system, but i will just return backward requesting previous headers until i reach the parent header (which is equal to one of the old in my local chain) from these servers, then start reorganizing the chain myself.

**Comment by alieslam** [comment]
@SomberNight 
Thanks for clarification, I had a conversation with Neil "kyuupichan" (owner of ElectrumX) and he explained the behaviour of the servers dealing with the new incoming blocks. I think the statement in the documentation was meant to me in the first place 😄 as I had an [issue](https://github.com/kyuupichan/electrumx/issues/368) opened for ElectrumX repo and we ended up with this conclusion. thanks for your help 😉 Closing issue ...
