### ISSUE TITLE
User intending to restore a wallet using a public key vs. the wizard

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3804]
A first time user, intending to "restore a wallet using a public key", sees the output of

```
        message = '\n'.join([
            _("What kind of wallet do you want to create?")
        ])
        wallet_kinds = [
            ('standard',  _("Standard wallet")),
            ('multisig',  _("Multi-signature wallet")),
            ('imported',  _("Import Bitcoin addresses or private keys")),
```
User thinks "I have a **public** key that I want to "import"(?). However I
see no such choice. However that third choice sounds closest" and
chooses the third choice. There he finds himself unable to enter the
public key and gives up.

OK, now let's say he is persistent in his efforts and hits BACK and
chooses ```Standard wallet```.

Now he sees the
```
        ('restore_from_key', _('Use public or private keys')),
```
choice, and thinks "Ah, they hid it there."

**Comment by SomberNight** [comment]
So what do you suggest?

**Comment by SomberNight** [comment]
Maybe `Use public or private keys` could be changed to `Use master key` (because we want an xprv or xpub there).
`Standard wallet` is really "standard deterministic wallet" in this case, but that is even more foreign to casual users possibly.
`Import Bitcoin addresses or private keys` is really "import addresses or individual privkeys"

**Comment by jidanni** [comment]
(@SomberNight I don't know. I'm just giving you the view from the consumer. Anyways, back to the plot:)

In fact just before he gave up above, he saw
```
  message = _("Enter a list of Bitcoin addresses (this will create a watching-only wallet), or a list of private keys.")
```
and thought "Yes! That's what grandma told me to do. Create a Watching only wallet!" Alas he failed.
Only if he navigated back out and around, will he finally reach
```
         _("To create a watching-only wallet, please enter your master public key (xpub/ypub/zpub)."),
```

**Comment by AbdussamadA** [comment]
address is not a public key. you can't create a watch only wallet with a public key AFAIK. only with an xpub.

**Comment by SomberNight** [comment]
@AbdussamadA you can create a watch-only wallet from addresses, or from an xpub.

You potentially could from a public key too; it would ideally be accompanied with script info (to know what kind of script to create from it), but this is not implemented, possibly anywhere (well maybe importmulti in Bitcoin Core).

**Comment by jidanni** [comment]
@AbdussamadA many users will assume the xpub and xprv are their public and private keys. Therefore any dialog mentioning one should distinguish it from the other.
