### ISSUE TITLE
Remember state of selection upon clicking Next

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3805]
Here on the top page of the wizard
```
        title = _("Create") + ' ' + name
        message = '\n'.join([
            _("What kind of wallet do you want to create?")
        ])
        wallet_kinds = [
            ('standard',  _("Standard wallet")),
            ('multisig',  _("Multi-signature wallet")),
            ('imported',  _("Import Bitcoin addresses or private keys")),
```
chose the third choice and click ```Next```.

Now click ```Back```.

Note now the first choice is selected. All we wanted to do was have a little last peek at the page we came from and it threw away our selections just like we never arrived.

We might even have forgot which one we selected and have to call up grandma again to ask her.

Or we might just blindly click ```Next``` again and then remember to then click the "2nd choice that grandma told us to click" and end up clicking a whole other 2nd choice. Etc.

**Comment by accumulator** [comment]
fixed by #8560
