### ISSUE TITLE
Confusion between "create" and "restore"

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3806]
Having a look from the eyes of the new user,
```
        title = _("Create") + ' ' + name
        message = '\n'.join([
            _("What kind of wallet do you want to create?")
        ])
        wallet_kinds = [
            ('standard',  _("Standard wallet")),
```
And then within it,
```
message = _('Do you want to create a new seed, or to restore a wallet using an existing seed?')
```

'Wait!' he thinks. 'You said "create" in the top menu, and now "restore" within it...'

**Comment by SomberNight** [comment]
You create a wallet by
- creating a seed
- restoring from a seed

**Comment by jidanni** [comment]
(OK but he might be looking to "restore a wallet" and not find it in the top menu...)
