### ISSUE TITLE
Modularize coin name to ease forks

### ISSUE THREAD

**Issue by jidanni** [spesmilo/electrum#3807]
I have a radical new idea, but it will take a little cooperation from
the "upstream" of this (family of elec*) packages.

You see there are many derivatives, one for LiteCoin, one for BitCoin
Cash, etc.

And each one must remember to change simple character strings, e.g.,
https://github.com/fyookball/electrum/issues/521 , in many places in the code.

Now if "upstream" would be so kind as modularize, _as much as possible_,
e.g., using $currency or $coin, and then in a header file saying what
currency that was, that would make the job of the derivatives much
easier.

Sure the guts would still need to be added by each 'vendor' but at least
the word Bitcoin wouldn't occasionally still appear where Barfcoin was
supposed to.

**Comment by jidanni** [comment]
I see. Well I suppose tbere will also be no interest in
the following either. Alas, never mind.

### Modularize branding to ease forks ###

it would seem wise to modularize "branding", so throughout the code, e.g.,
```
        msg = _("Electrum is generating your addresses, please wait.")
```
would use $vendor instead of "Electrum", and then in one place, a header
file, declare what that branding that is, be it
1. Electrum
2. Electrum++
2. Electron Cash @fyook
1. Electrum-LTC @pool
2. My ETH test fork 11β
1. LiteCoin Wallet for Junior Professionals™, etc. etc.

A side benefit would be the elimination of bug reports about Electrum
when in fact it was just a half baked fork that still was leaking
Electrum branding due to the forker not having chased down all the spots.

Also when implementing this consideration should be made for
different locale strings... So one would want two levels of indirection,
$vendor and $locale so one could come up with "Electrum", "Le Electrum" etc.

###   Modularize short version of coin name ###

Also modularize in another declaration the short version of the coin
name, instead of having it hardwired throughout the code:

```
    'fee':         ("-f", "Transaction fee (in BTC)"),

**Comment by jidanni** [comment]
(#3817 is also a modularization idea.)

**Comment by SomberNight** [comment]
If someone implements this in a clean PR, it might get accepted.

**Comment by jidanni** [comment]
@SomberNight but it also might get closed with a just a flick of the wrist, so few would likely take the effort to see.

**Comment by jidanni** [comment]
Maybe the Electrum team is against forking.

If so then maybe a private repository would be more suitable. https://github.com/github/site-policy/issues/37 .

If the Electrum is not against forking, then they should state what a proper fork should look like.

And also update https://electrum.org/bcc2.txt , which even might violate https://help.github.com/articles/github-terms-of-service/ (defaming https://github.com/fyookball/electrum ,) if it were hosted on GitHub.

My #3807 here is to encourage better distinction between the forks: reducing each fork tarnishing the others' image.

Forks are going to happen. Else GitHub might not be the right place for this project.

**Comment by SomberNight** [comment]
@jidanni This project is a Bitcoin light wallet. However surprising that may sound to you, it is not a priority for us to help forking it for altcoins. Just like probably any other similar project, we are short on resources, specifically developer time. We will not spend time on this. We will spend the time and resources we have on features and bug-fixes for this wallet, which is for Bitcoin. If you think it is important maybe you could spend some of your time on implementing it, after all, this is an open-source project; though it sounds like you don't think it should be...

**Comment by jidanni** [comment]
(Actually many Issues here are actually altcoin version issues. That's why we don't include screenshots :-)).

**Comment by ahmedbodi** [comment]
WIP: https://github.com/ahmedbodi/electrum
