### ISSUE TITLE
pending deposit

### ISSUE THREAD

**Issue by shotty11** [spesmilo/electrum#3808]
i send about 1.45 zcl from cryptopia to my electrum wallet about 11 hours ago, and it still hasn't arrived into electrum. it says 'pending' on cryptopia. the wallet is connected to 1 node, and the receiving address is right. i did send it before setting up a 'description' and 'amount' on the 'receive' tab of the wallet, but the address i sent to is the same as the 'receiving address' on the receive tab. thanks

**Comment by SomberNight** [comment]
Electrum is for Bitcoin only. There are several forks of the project for different altcoins, maintained by different people.

**Comment by shotty11** [comment]
i'm using the zcl electrum wallet and sent zcl to it. the wallet's help link sent me here...

**Comment by SomberNight** [comment]
Again, they forked this project. They seem to have forgotten to change that link. This project is for bitcoin only.
Maybe try here https://github.com/BTCP-community/electrum-zcl/issues ? I don't know if this is the right fork to be honest; it's hard to keep track.
