### ISSUE TITLE
Creating watch wallet from master public key at command line?

### ISSUE THREAD

**Issue by Yuki-Inoue** [spesmilo/electrum#3822]
First asked on [bitcoin.stackexchange.com](https://bitcoin.stackexchange.com/q/69855/47528) but did not get response so asking here.

---

I know that by `electrum -w WALLET_PATH create` a usual wallet can be created. I'm now looking for way to create wallet file from master public key.

### Question

* Given I have master master public key, e.g. `xpub12345...ABCDE`, how can I create its watching wallet file at command line?

**Comment by AbdussamadA** [comment]
`electrum -w wallet_path restore <mpk>`

**Comment by Yuki-Inoue** [comment]
@AbdussamadA It seems the restore command was what I was looking for.  Thanks!
