### ISSUE TITLE
getBalance RPC returning 0 balance in the "unconfirmed" field

### ISSUE THREAD

**Issue by knocte** [spesmilo/electrum#3824]
Not sure if this is actually an issue I should file in ElectrumX rather than here, but I'm seeing all electrum servers returning 0 as the value returned in the "unconfirmed" JSON field of the [getbalance RPC method](http://docs.electrum.org/en/latest/protocol.html#blockchain-address-get-balance) (the "confirmed" one looks ok, shows the right amount).

If this is the intended way to flag "the unconfirmed balance is the same as the confirmed balance" then in my opinion this is a bug. Because then a stratum client cannot differentiate this state from the state in which an address has just spent all his balance (but the transaction to spend it hasn't been confirmed yet).

**Comment by SomberNight** [comment]
Can you give more details? This seems to work for me:
```
user@debian:~/wspace/electrum$ ./electrum -v --testnet getaddressbalance mnWJoCpLdDJTRLyjbzrCSHR1u2J9cmvMFC
[SimpleConfig] electrum directory /home/user/.electrum/testnet
[SimpleConfig] electrum directory /home/user/.electrum/testnet
[WalletStorage] wallet path /home/user/.electrum/testnet/wallets/default_wallet
{
    "confirmed": "0.5",
    "unconfirmed": "0.001"
}
user@debian:~/wspace/electrum$ ./electrum -v --testnet getaddressbalance mv72eg7Gn4cVW1UCwmNtauescqBA4VFS7i
[SimpleConfig] electrum directory /home/user/.electrum/testnet
[SimpleConfig] electrum directory /home/user/.electrum/testnet
[WalletStorage] wallet path /home/user/.electrum/testnet/wallets/default_wallet
{
    "confirmed": "0.001",
    "unconfirmed": "-0.001"
}
```

**Comment by knocte** [comment]
Seems I was misreading the documentation.

I was thinking that the amount in the `unconfirmed` field would include the confirmed funds please the unconfirmed funds, but since you just posted an example of unconfirmed funds being negative, I guess I was wrong. I'll probably send a PR to the docs to make this explicit there. Thanks and sorry for the noise.

**Comment by SomberNight** [comment]
No trouble.
By the way, there is a more recent protocol documentation here: https://github.com/kyuupichan/electrumx/blob/master/docs/PROTOCOL.rst

**Comment by SomberNight** [comment]
Also, I just made this PR after looking at the code because of your question https://github.com/spesmilo/electrum/pull/3826 :)
