### ISSUE TITLE
Lost money and Synchronizing...

### ISSUE THREAD

**Issue by Dropus** [spesmilo/electrum#3825]
Hello. This is first time i got this bug. I got money but in the field i can see "0.", but real i got https://blockchain.info/address/1APiKVVuHXBebpX1L3j9JdwPTDMXFZdvEi  , so when i am trying to right-click on this transaction , program is bugged and restarting all the time.. also Electrum Synchronizing all the time, i am trying to change server many times but this is not working at all. I am trying to reinstall Electrum using Seed, but this is not working also. What i need to do to get my money now?? I am using Electrum 3.0.5 .

**Comment by SomberNight** [comment]
Hi. This is due to https://github.com/spesmilo/electrum/issues/3788
Due to a bug, Electrum is failing to parse the transaction.
You should either wait for the next release, which should hopefully come soon; or run the code from source, as the master branch already contains the fix.

**Comment by ysangkok** [comment]
Just FYI, the money is not lost, you have received it. When Electrum is updated, it will show up. Don't worry.

**Comment by Dropus** [comment]
Where i can run the code from sourse? I cant find them on website.

**Comment by ysangkok** [comment]
See https://github.com/spesmilo/electrum#development-version

**Comment by Dropus** [comment]
omg i just a simple user and i dont understand what to do with that :)

**Comment by ysangkok** [comment]
Then wait a week or so, I am sure a new release will be out soon.

**Comment by Dropus** [comment]
OK :((((

**Comment by Dropus** [comment]
Damn... i need money to another person , he tells me he cant wait...damn, maybe someone tell me what i need to do step by step if someone have free time, please? :((
