### ISSUE TITLE
can not send from electrum wallet Z!1.0.0 2fa to exchange 

### ISSUE THREAD

**Issue by kfox73** [spesmilo/electrum#3828]
sent small amount of zcl to wallet  everything went fine. then sent all my zcl and now can not send back to exchange any ideas on how to fix?

**Comment by ysangkok** [comment]
By ZCL, do you mean ZCoin Classic? If so, you need to report it on the ZCoin Classic bugtracker, not this one. This is for Electrum. Electrum works only with Bitcoin.
