### ISSUE TITLE
Hello and first I want to apologize for bothering you all

### ISSUE THREAD

**Issue by WACOman** [spesmilo/electrum#3831]
I have bitcoin on MultiBit 5.15 and I'm following the YouTube tutorial to the letter and it stalls at the enter the key...  I have Electrum 3.0.5 installed on my Mac.
Thank you in advance for any help
Liam

**Comment by bauerj** [comment]
Hey,

what tutorial are you talking about? Does Electrum crash after you enter the key?

**Comment by WACOman** [comment]
Hi Johann
Everything work as shown on the video (YouTube-electrum wallet tutorial 2017) till after I paste the key and at that point the ‘Next key’ doesn’t highlight and stays gray…

Thanks Johann

**Comment by WACOman** [comment]
Johann, here’s the link: https://youtu.be/LaijbTcxsv8 <https://youtu.be/LaijbTcxsv8>

**Comment by bauerj** [comment]
If it's not an Electrum seed, you have to open options and enable the BIP39 option. 

I'm not even sure if Multibit seeds are BIP39 seeds though. The easiest will probably be to send your coins from Multibit to your Electrum wallet.

**Comment by WACOman** [comment]
Thanks 🙏🏼 I’ll try BIP 39, have trued sending and MultiBit refuses...
They have closed and no support available...

**Comment by WACOman** [comment]
Sorry Johann can’t find ‘options’ I’m very bad at this...

**Comment by SomberNight** [comment]
![bip39_restore](https://user-images.githubusercontent.com/29142493/35772077-5efa5b66-0938-11e8-959a-6c597b62bf7c.png)

**Comment by AbdussamadA** [comment]
@WACOman They moved some elements around in the GUI with 3.0 so that guide is out of date. See [this page](https://bitcoinelectrum.com/importing-your-private-keys-into-electrum/) instead.

@SomberNight  @bauerj Multibit classic is not an HD wallet.

**Comment by WACOman** [comment]
Thanks Guys, I did a swipe and they came right over, next question, how do i confirm transaction… I know I’m a pain in the butte!
And what do I need to do to spend some…
Thanks all for all your help
Liam

**Comment by bauerj** [comment]
That's great to hear!

Your transaction will probably be confirmed without further action from you although it might take some time (depending on the fee you paid).

To send coins, you can use the "Send" tab once the sweep transaction is confirmed.

**Comment by WACOman** [comment]
Thanks Joann and everyone, and yes I now see a little timer… eyes aren’t so good, I’m almost 72 and I’m so excited at what you all are up to… I’m with you all the way!
Thanks again!
Liam

**Comment by WACOman** [comment]
Mission accomplished! Thanks again everyone for all your help 🙏🏼
Liam
