### ISSUE TITLE
"electrum setconfig url_rewrite" is not working correctly

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum#3833]
When I use this command:
```
$ electrum --testnet setconfig url_rewrite "['file:///srv/www/', 'https://random.re/']"
```
it sets the configuration, but in config file we have:
```
"url_rewrite": "['file:///srv/www/', 'https://random.re/']",
```
and if we try to addrequest, electrum is getting mad about it:
```
Invalid call parameters: <Fault -32602: Invalid parameters: replace() takes at most 3 arguments (42 given)>
```
as it expects configuration **without quotes** as:
```
"url_rewrite": ['file:///srv/www/', 'https://random.re/'],
```
Unfortunately when we try to set it without quotes, we get:
```
$ electrum --testnet setconfig url_rewrite ['file:///srv/www/', 'https://random.re/']
usage: electrum [-h] [-v] [-D ELECTRUM_PATH] [-P] [-w WALLET_PATH] [--testnet]
                <command> ...
electrum: error: unrecognized arguments: https://random.re/]
```

**In summary: current version of Electrum does not work with payment requests when rewriting is used.**

**Comment by ser** [comment]
OK, problem solved when we use different quote characters.

So it works correctly:
```
$ electrum --testnet setconfig url_rewrite '["file:///srv/www/", "https://random.re/"]'
```

**Comment by SomberNight** [comment]
So the quotes only work one way around? And it's not even the way that is [in the docs](https://github.com/spesmilo/electrum-docs/blob/4a058ed5e130b654b8ed37f1d64df716a0610960/merchant.rst#configure-a-requests-directory)?

**Comment by SomberNight** [comment]
Is this master or 3.0.6?

**Comment by ser** [comment]
master - I will update the docs.
