### ISSUE TITLE
enhancement suggestion: new function "complete wallet" for watch-only wallets

### ISSUE THREAD

**Issue by kollokollo** [spesmilo/electrum#3835]
For a watch-only wallet a handy function would be:
* Loopover all transactions in the wallet:
** For all outgoing transactions:
*** Look at the addresses of all inputs to the transaction and import them, if they are not already in the wallet.

This function could be placed in the "wallet" menu an have a title "complete wallet". Meaning that it expands the wallet from a single imported address to the complete wallet.

**Comment by bauerj** [comment]
What's the use-case for this? I'm a bit skeptical that this would be actually useful for a lot of people.

**Comment by kollokollo** [comment]
The use case would be: When you want to make a watch-only copy of a non-HD-wallet. You usually start by importing a single bitcoin address. With the new function you would immediately get the rest of the wallet (assuming you have used it already).

**Comment by bauerj** [comment]
> With the new function you would immediately get the rest of the wallet 

But what if you have addresses that don't share a transaction with the initial address?

**Comment by kollokollo** [comment]
Only important for addresses with UTXs on them.
They would not be automatically imported. Could still be added manually...
dummy or reserve addresses need not be imported until they become used in a tx.

**Comment by ecdsa** [comment]
suggestion rejected. you should import the master public key instead.
