### ISSUE TITLE
[Electrum Website] Can we have checksums for the downloads?

### ISSUE THREAD

**Issue by yhnavein** [spesmilo/electrum#3837]
Hi guys,

Can you provide checksums for the downloads on the Electrum main website? Currently only signatures are provided, which are maybe better than simple checksums, but actually verifying if downloaded executable is the correct one is a total pain.
Electrum LTC provides checksums, and verification took me around 2seconds.
I tried to verify signature of the BTC Electrum, but I gave up. Sorry, this is just plainly unusable.
Maybe on other platforms using terminal that would be so much easier, but on Windows this is a nightmare ;(

Cheers and thanks,

**Comment by SuBPaR42** [comment]
Checksums are better than nothing but not as good as signatures.  If and .exe has been replaced by a malicious actor you can assume the checksum data has also been compromised (i.e., common user sees the checksums matches and now is infected) so not much of a security enhancement.  I suppose hosting the checksums on another site might provide some amount of improved security but again see signatures as the best option.

Just my $.02

**Comment by bauerj** [comment]
Sorry, I don't think this would be a good idea.

As @SuBPaR42 pointed out, it would create a false sense of security. 

Furthermore, the .EXE installer does a checksum test before installing anything so there should be no reason to add another checksum to it.
