### ISSUE TITLE
[Android] Should be able to access other wallets after deleting default_wallet

### ISSUE THREAD

**Issue by dmp1ce** [spesmilo/electrum#3838]
On Android, after I have imported a standard wallet with a seed. I have a `default_wallet` and a `mobile segwit` wallet. The `default_wallet` shows a balance which is not correct, and the `mobile segwit` wallet show the correct balance and transactions. If I delete the `default_wallet` then I will no longer be able to access `mobile segwit` wallet until importing my seed again.

The behaviour I expected is that I could delete the `default_wallet` and my other wallets would still be accessible.

**Comment by SomberNight** [comment]
related:
https://github.com/spesmilo/electrum/commit/ff7159495c3fd328a8895b3f566bd738ae073a0c
https://github.com/spesmilo/electrum/commit/610b37890f13191e96b347570334779b2e062462

**Comment by ecdsa** [comment]
it is possible now, the password dialog has a wallet selection button.
that issue should have been closed long ago.
