### ISSUE TITLE
[Android] Should better explain bad_txns_vin_empty errors when sending

### ISSUE THREAD

**Issue by dmp1ce** [spesmilo/electrum#3839]
Yesterday, on Android, when trying to send to another Electrum wallet, I kept getting a `bad_txns_vin_empty` error from the network. I closed my app and restarted several times but kept getting the error. I eventually restarted my phone and then tried again. My Electrum app crashed once after a phone restart. I started the app again and the send finally worked.

Why was I getting the error? I would expect that there is more explanation as why the transaction could not be used.

**Comment by ecdsa** [comment]
that is an error returned by the server. maybe your server was lagging

**Comment by SomberNight** [comment]
I would guess OP got this error when trying to broadcast a segwit transaction on a legacy full node as that would see the tx having zero inputs.
