### ISSUE TITLE
zcl electrum not sending amount

### ISSUE THREAD

**Issue by mrpvcs** [spesmilo/electrum#3840]
Hello 
Team Electrum
This morning I tried sending .07 to cryptopia, and it errored. This first two times it said it has been sent with nothing beening sent. Please help. thank you for your time on this matter.

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl

**Comment by mrpvcs** [comment]
Hello
Ghost43

Thank you for re route link, I left them message.
