### ISSUE TITLE
-D flag does not recognize existing 'default_wallet'

### ISSUE THREAD

**Issue by coinsmith** [spesmilo/electrum#3848]
The command
./electrum -D /path/to/dir/

does not recognise the 'default_wallet' entry in the directory and wants to make a new 'default_wallet'. When pointing the GUI to the specific 'default_wallet' file in that folder, it does open the existing wallet. 

edit: only happens from a fresh elecrum install. Once manually pointed, it does open from the directory via -D flag.

**Comment by ecdsa** [comment]
what does "from a fresh install" mean? are you on linux?

**Comment by coinsmith** [comment]
Yes, migrated from 14.04 to 16.04

**Comment by ecdsa** [comment]
I cannot reproduce this. 
maybe you expect it to open default_wallet the wallet in the directory you typed, which is not what it does; it looks for it in the "wallets" subdirectory

**Comment by coinsmith** [comment]
Thanks for looking into it.
