### ISSUE TITLE
Where do we send ZCL altcoin for the fork? Electrum wallet not working

### ISSUE THREAD

**Issue by awllc** [spesmilo/electrum#3852]
I had downloaded the electrum wallet 1.0.3 in preparation for the upcoming fork and was trying to deposit my ZClassic (ZCL) to it. But it isn't working.

Cryptopia doesn't recognize any of the public addresses the wallet gives me as valid for ZCL and the wallet won't sync.

Where are we supposed to send the ZCL we buy on exchanges so that it can be included in the fork? (I normally don't like to just leave coins on exchanges anyway, aside from the fork.)

**Comment by ecdsa** [comment]
off topic

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl
