### ISSUE TITLE
use QtAbstractItemModel to update lists 

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#3856]
see my comment in #3851 
with a proper model it seems that #3599 would also not be necessary

**Comment by SomberNight** [comment]
note: some work in https://github.com/spesmilo/electrum/tree/qt_standardmodel

**Comment by ecdsa** [comment]
done in #4888

**Comment by SomberNight** [comment]
also see https://github.com/spesmilo/electrum/pull/4915
