### ISSUE TITLE
Electrum not recognizing Trezor (Linux)

### ISSUE THREAD

**Issue by colourful-land** [spesmilo/electrum#3857]
On Ubuntu 17.10 Installed using 

    $ sudo pip3 install https://download.electrum.org/3.0.6/Electrum-3.0.6.tar.gz
    $ sudo pip3 install btchip-python

Trezor is working for the web (Chroimum) so I am less inclined to think that it's udev rule related. The set-up wizard simply say that no hardware is detected.

Electrum also prompted me to check the udev rule permission. I added myself to the dialout group which is specified in /lib/udev/rules.d/51-trezor.rules and rebooted cleanly with no effect. The udev rules, as you expect, has permission set to 0666. Quoting the one line relevant to my device:

    ...
    SUBSYSTEM=="usb", ATTR{idVendor}=="534c", ATTR{idProduct}=="0001", MODE="0666", GROUP="dialout", SYMLINK+="trezor%n"
    ...

The permission looks alright:

    $ ls -lh /dev/trezor3 
    lrwxrwxrwx 1 root root 15 Feb  6 18:32 /dev/trezor3 -> bus/usb/003/004
    $ ls -lh /dev/bus/usb/003/004 
    crw-rw-rw- 1 root dialout 189, 259 Feb  6 18:32 /dev/bus/usb/003/004
    $ groups
    adm dialout cdrom sudo dip plugdev lpadmin sambashare kvm libvirtd

**Comment by ecdsa** [comment]
did you close chromium first?

**Comment by colourful-land** [comment]
Thanks ecdsa. Yes, I did a clean reboot and started Electrum without any browser. I also tailed /var/log/trezord.log and it produced no output while Electrum was running.

**Comment by SomberNight** [comment]
> sudo pip3 install btchip-python

That package is for Ledger :P

**Comment by colourful-land** [comment]
@SomberNight I installed trezor. In my original post:
> Trezor is working for the web (Chroimum)

If I had not installed trezor, I wouldn't have been able to use it for the web. I also quoted  /lib/udev/rules.d/51-trezor.rules which is installed by the trezor deb package.

**Comment by SomberNight** [comment]
@colourful-land so what this this output?
```
python3 -m pip show trezor
```

**Comment by colourful-land** [comment]
Thanks for the hint. It turns out to be non-trivial to pip3 install trezor at all.

It turns out that Ubuntu 16.04 didn't ship python3-trezor. Furthermore, its dependency python3-hidapi has a requirement of hidapi>=0.7.99 - it will be satisfied at nothing but the latest version. Ubuntu (up to Bionic) ships only 0.2.1.

 I did
`sudo apt-get install python3-cffi python3-pycparser`
before attempting a `pip3 install trezor` in order to minimize binary dependency failures.

Then, `pip3 install trezor` spits out numerous dev package dependencies, so I had to do:
`sudo apt-get install libusb-1.0-0-dev libudev-dev`

This time `sudo pip3 install trezor` is satisfied to do its job.

**Comment by colourful-land** [comment]
Haha, I didn't say it worked after python3-trezor is installed. I was writing a follow-up comment when you closed it. Visitors coming from Google Search please step in #3928 if you still have "No hardware device detected" after following the said procedure.
