### ISSUE TITLE
Change addresses beyond default gap limit will stay beyond gap limit

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3859]
Suppose the user uses `create_new_address` to create change addresses.
https://github.com/spesmilo/electrum/blob/d56dba80392bd5e7d679ab9483b2cbfd50d4c506/lib/wallet.py#L1813
(Alternatively, the ~same can be triggered by changing `gap_limit_for_change`)

Let's say she creates 50 new change addresses.
The wallet, when creating a new txn, will choose from the last 6 (hardcoded `gap_limit_for_change`) change addresses.
https://github.com/spesmilo/electrum/blob/d56dba80392bd5e7d679ab9483b2cbfd50d4c506/lib/wallet.py#L999-L1007
When all among these last 6 are used, at some point, new ones will be generated.
https://github.com/spesmilo/electrum/blob/d56dba80392bd5e7d679ab9483b2cbfd50d4c506/lib/wallet.py#L1832-L1835

As a consequence, an existing "gap" will never be overcome.

**Comment by ecdsa** [comment]
is that really a concern? 
we cannot address all the possible scenarios that result from a user typing commands in the console..

**Comment by SomberNight** [comment]
Ok, fair enough. I just ran into this and it took some time to diagnose why I was missing some coins after a restore. :)
