### ISSUE TITLE
Master is not compatible with latest released version of python-trezor

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3860]
The latest release of python-trezor is still 0.7.16.
Their master branch introduced not-backwards-compatible changes, that we adapted to in https://github.com/spesmilo/electrum/pull/3621

This means, that at this point in time, our master branch is not compatible with python-trezor 0.7.16.

Until this is resolved, it is questionable whether we can/should release from master.

**Comment by ecdsa** [comment]
@slush0 can you comment on that? shall we revert #3621 ?

**Comment by SomberNight** [comment]
I would very much prefer a new Trezor tag/release, we already have a couple commits that build on #3621 so it would be non-trivial to revert it at this point >.<

**Comment by SomberNight** [comment]
Well, that was fast :)
There is now a 0.9.0 tagged and on pip; thanks.
