### ISSUE TITLE
Having issue w non signed tx zcl wallet-not a coder here...help plz

### ISSUE THREAD

**Issue by 5rings** [spesmilo/electrum#3865]
Hi all, so I downloaded the ZCL wallet on Windows 10. I imported my tokens from paper wallets. I see them in the tx read only file but they are unsigned and marked view only. I installed the latest Electrum Wallet, I import the file and then I get stuck. I do not know how to sign, verify, or broadcast a tx in Electrum. I hope somebody with some experience with this wallet can help me. Any information is obviously greatly appreciated....ty in advance (5rings)

**Comment by haydenhab57** [comment]
سلام دوست من یکسری از مطالب پراکنده من مونده که احتمالا جواب شما آنجاست


2018-02-07 4:33 GMT+03:30 5rings <notifications@github.com>:

**Comment by 5rings** [comment]
can you reply in English? I don't read Arabic, even though it is a beautiful language and the first written one...
