### ISSUE TITLE
Can't send out funds?? Please help!

### ISSUE THREAD

**Issue by SatoshiNakamotto** [spesmilo/electrum#3866]
Please someone help. I downloaded the electrum wallet to store my ZCL in anticipation for the fork, as per the Bitcoin Private instructions. However, when they announced the fork wouldn't happen until the end of the month, I wanted to move my coins back to Bittrex and its not working. When I open the wallet and go to "send", I put in the address, the amount, and click send and nothing happens... What do I do? I am using version 1.0.3 Thank you!

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl
