### ISSUE TITLE
Wallet stuck in synchronizing state

### ISSUE THREAD

**Issue by alexandrz** [spesmilo/electrum#3868]
Electrum 3.0.5, macOS

I tried to run `wallet.clear_history()` and recreate the wallet from scratch, but have got the same result. One transaction is being show as `+0.` in the list:

![screenshot](https://i.imgur.com/tZnv6Ey.png)

When I try to see its details, Electrum crashes. This transaction is not present in `listunspent()` output, but I have managed to get its id, by exporting transaction history. Nothing seems to be wrong with this transaction.

**Comment by SomberNight** [comment]
Sounds like https://github.com/spesmilo/electrum/issues/3788
Please try with 3.0.6

**Comment by alexandrz** [comment]
Yes, it's fixed.

Thank you!
