### ISSUE TITLE
Warn more thoroughly about custom WIF for private keys

### ISSUE THREAD

**Issue by erikarvstedt** [spesmilo/electrum#3881]
In Segwit wallets, Electrum uses a custom private key WIF that produces output indistinguishable from the widely-used, official WIF.
This is a UX disaster that invites misuse and user frustration. (Have just been burnt really bad by this.)

Please add a clear warning to the `Wallet -> Private keys -> Export` dialog:
Red letters with text like 
    
> Electrum uses a custom private key format that is incompatible with the regular Wallet Import Format (WIF).

Show the same warning in `(Right click on address) -> Private key`

Even better, change the custom WIF to a format that avoids confusion.
Also, maybe add an option to export private keys in the regular WIF.

**Comment by SomberNight** [comment]
> Show the same warning in (Right click on address) -> Private key

https://github.com/spesmilo/electrum/issues/3694#issuecomment-356785965

There already is such warning, though I guess it's missing from the batch-export option.

(Related: https://github.com/spesmilo/electrum/issues/3620)

**Comment by erikarvstedt** [comment]
Yes, please update the existing warning to the proposed format: Red letters and a more explicit mention of the incompatibility.

**Comment by dabura667** [comment]
@erikarvstedt to be precise. Everyone else is incompatible with Electrum, not the other way around.

Why? Because there is no standard for encoding segwit private keys.

So Electrum made one.

And no one else is using segwit with WIF private keys (since most HD wallets are of the mindset of "don't let the user export individual private keys") so no other wallet wants/needs to support this new standard made by Electrum.

If Electrum exported WIF in the traditional method, no wallet would generate a segwit address for you, since there is no info embedded in the traditional WIF key to denote "this key is for segwit"

Same thing goes for bitcoin core recovery based signatures.

**Comment by erikarvstedt** [comment]
No, WIF is Bitcoin's canonical format for private keys – it makes absolutely no assumptions about the address type. Address types and private keys are completely orthogonal topics.
(Yes, of course it makes great sense to use a serialization format which includes the address type, but this shouldn't collide with an existing, well-defined format.)

**Comment by SomberNight** [comment]
If WIF is about private keys and nothing else, then why is there a distinction of compressed/uncompressed public key?

**Comment by erikarvstedt** [comment]
Yeah, in the spirit of the original WIF design, it should include the address format. My lecturing about the 'orthogonality' was unnecessary, sorry.
But still, the potential for confusion with regular WIF is a huge problem.

**Comment by SomberNight** [comment]
> Why Electrum didn't chose a custom byte prefix for its Base58CheckEncoding is a mystery to me

https://github.com/spesmilo/electrum/issues/3694#issuecomment-356785965
We extended the original WIF format in a way such that old keys (p2pkh) have the same encoding using both schemes.

But yes, you are right, the current situation is less than ideal, especially considering Bitcoin Core essentially ignored the proposal and kept using the old WIF format (and they are already at RC3).

**Comment by ecdsa** [comment]
closing this, since #3925 fixes it
