### ISSUE TITLE
Add support for Importing Testnet master keys (tpub/tprv)

### ISSUE THREAD

**Issue by vzelenko** [spesmilo/electrum#3884]
There is no (apparent to me) way to restore a testnet wallet from exported public or private key.

I am able to "import" a Testnet deterministic wallet by importing "word phrase", which is a sufficient workaround for me.  I can also import a non-deterministic wallet using Private/Public key.  

Looking at the "keystore.py" code, Xpub logic does not account for testnet types...

If no one has the bandwidth to make the changes, perhaps expanding the docs with instructions on how to import the Testnet wallets would be helpful.

**Comment by ecdsa** [comment]
yes, we need to switch back to t,u,v letters for testnet.

**Comment by SomberNight** [comment]
Related: https://github.com/spesmilo/electrum/issues/3539
