### ISSUE TITLE
History of all transactions disappeared when bump fee

### ISSUE THREAD

**Issue by alevchuk** [spesmilo/electrum#3885]
I tired to increase the fee for a pending transaction. Immediately all history of all transactions disappeared in Electum (see screenshot).

![screen shot 2018-02-11 at 7 55 35 am](https://user-images.githubusercontent.com/64738/36075254-2f340020-0f01-11e8-9e8e-d49546ea9614.png)

I'm running  source code 6e4774870adb89be0629d066f0d38f103c65fcca (Feb 3)

The transaction got marked as double spent:
https://www.blocktrail.com/tBTC/tx/e4fb15d82d3aeaa7e5d35d7028f2c364e390da2e71e2bf5a343a54f8d3a7dd08 

and the new transaction is not getting confirmed https://www.blocktrail.com/tBTC/tx/04c575c09c77f76499c150dc2208ef3f1079638be3d141fd332e2758bc39e789

**Comment by shsmith** [comment]
Same thing happened to me a few weeks ago. I thought the wallet file was corrupted so I restored a fresh copy from seed and that caused the history to re-appear in the copy.

**Comment by alevchuk** [comment]
@shsmith That workaround works for me too. Thanks!

Hi @ecdsa, does this looks like a serious bug?

**Comment by SomberNight** [comment]
That commit is between https://github.com/spesmilo/electrum/commit/2343894e0f9b33641f43a4670949851ac59f1dd0 and https://github.com/spesmilo/electrum/commit/d9cf4c2b63ed8c6c07b26a31d322cd5e69e55ad1.

Not a good commit to be on. :P
Should not happen on current master.

**Comment by SomberNight** [comment]
(I believe this should be fixed, so closing.)
