### ISSUE TITLE
Variation on the 2FA locked out of wallet question

### ISSUE THREAD

**Issue by grumpyoldwit** [spesmilo/electrum#3888]
Hi guys, I would be very grateful if you could point me in the right direction on this!

After going travelling and not opening my electrum wallet for many months, and losing my old phone (and therefore google authenticator app) I was unable to send any bitcoins on return.

I read that I had to restore the old wallet using my seed to disable 2FA. However, when doing so, I tried to restore a standard wallet by accident, instead of a 2FA. This created a new wallet with a tiny amount of bitcoins with odd looking transaction amounts. My full wallet remained unchanged. (see image)

When I then try and restore using the 2FA option, and type in my seed, it says "old seed". I am only given the option to extend it with custom words.

If I try to restore as a default wallet, it also says old seed. I am only offered the option to try the seed as a BIP39, but this only creates a totally empty wallet. Having done a bit of research, the words in my seed seem to pre-date BIP39. I have been upgrading electrum since around 2013.

When trying to restore as a multi-sig wallet, I also have to enable BIP39 such that the next button is un-greyed. If I follow this course, it gives me a master public key and asks for a cosigner key or seed. I have tried entering a master private key from looking at my wallet.dat file which was unsuccesful.

When attempting to restore by sweeping private keys saved from my full bitcoin wallet, this only brings up an "electrum 3.0.6 has stopped working" error over the please wait window.

I have tried uninstalling and reinstalling electrum to no avail.

I messaged trustedcoin but they haven't responded as of yet.

Is there any way I can get access to my btc?

Was there an automatic switch to 2FA that I have forgotten about?

Will trying to import the keys on the bitcoin core client / completely different PC make any difference?

WIll trying to sweep the keys / restore seed on an older version of electrum be risky?

Hope that isn't too long winded, I tried to be as concise as possible, am very new to the technicalities of it all!
![electrum values](https://user-images.githubusercontent.com/36374581/36075619-674c785a-0f49-11e8-8a99-87d7417e416b.jpg)

**Comment by bauerj** [comment]
This is not the seed for your 2FA wallet, it's the seed to another wallet.

**Comment by grumpyoldwit** [comment]
Ahhhh. I see where I went wrong. It was the only 12 word seed I had, but it was actually a 25word seed hidden deep in some notes somewhere. Crisis averted!
