### ISSUE TITLE
SSL connection reports NO_PROTOCOLS_AVAILABLE on macOS for some Python distributions

### ISSUE THREAD

**Issue by hanzou-x** [spesmilo/electrum#3891]
Per discussion on IRC with Rotonen and ghost43, OpenSSL may have trouble working on some Python distributions. In my case on macOS 10.13 High Sierra, running `electrum --verbose` results in:
```
[SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)
[192.168.2.12] SSL error retrieving SSL certificate: [SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)
```
and of course at that point it is unable to download any headers or transactions. Tested on macOS 10.13.3 with commit cc55d78 of the master branch. This might be tied to macOS defaulting to libressl:
```
$ /usr/bin/openssl version
LibreSSL 2.2.7
```
or related to my running a Python 3.5 build downloaded and installed from python.org a more than a year ago:
```
$ /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 --version
Python 3.5.1
```
If I install and use a more recent Python3 implementation such as Python 3.6.4 the problem fixes itself:
```
[Network] connecting to 192.168.2.12:50002:s as new interface
```
As Rotonen suggested to try: Alternatively, sticking with Python 3.5.1 while commenting out the following lines
```
--- a/lib/interface.py
+++ b/lib/interface.py
@@ -125,9 +125,9 @@ class TcpConnection(threading.Thread, util.PrintError):
         context.check_hostname = False
         context.verify_mode = cert_reqs
 
-        context.options |= ssl.OP_NO_SSLv2
-        context.options |= ssl.OP_NO_SSLv3
-        context.options |= ssl.OP_NO_TLSv1
+        #context.options |= ssl.OP_NO_SSLv2
+        #context.options |= ssl.OP_NO_SSLv3
+        #context.options |= ssl.OP_NO_TLSv1
```
also makes Electrum able to successfully connect via SSL.

Without running with `--verbose` and paying attention to the log, to others this may seem like Electrum just never connects. Ideally, Electrum's SSL support would be less dependent on the particular installation of Python 3, or otherwise fail with a louder error when encountering these limitations.

**Comment by SomberNight** [comment]
Is there an exception thrown by these lines?
```
context.options |= ssl.OP_NO_SSLv2
context.options |= ssl.OP_NO_SSLv3
context.options |= ssl.OP_NO_TLSv1
```
If so, let's just catch that, and continue silently.

Would you be able to test and tell the type? Just catch all exceptions and `traceback.print_exc(file=sys.stdout)`.

**Comment by jogc** [comment]
Same problem here. I checked and those lines do not raise any exception. The exception gets raised later by these lines:

context = self.get_ssl_context(cert_reqs=ssl.CERT_NONE, ca_certs=None)
s = context.wrap_socket(s)

**Comment by SomberNight** [comment]
Please provide a trace.

**Comment by jogc** [comment]
Traceback (most recent call last):
  File "blabla/electrum-btcp/electrum-btcp/lib/interface.py", line 154, in get_socket
    s = context.wrap_socket(s, do_handshake_on_connect=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c:645)

**Comment by hanzou-x** [comment]
Thanks for taking care of testing that @jogc. I felt this was stalled on me and sorry I didn't get around to testing and reporting on the `try..catch` thing, but also would have been surprised if an exception was thrown on the lines that merely set options bits :)

**Comment by bauerj** [comment]
I'm not sure if it's even a good idea to allow SSLv3 connections...

Clearly this seems like the Python distribution is broken if it can't even open TLS connections.

**Comment by helpau** [comment]
I think bug is obsolete
![image](https://github.com/spesmilo/electrum/assets/30323047/0eb70af0-d9ea-4a78-a7da-391e67152d94)
https://en.wikipedia.org/wiki/Transport_Layer_Security#Applications_and_adoption

**Comment by ecdsa** [comment]
thanks for pointing this out.
