### ISSUE TITLE
electrum 3.05 not open in ubuntu 16.04 - error Qt Library

### ISSUE THREAD

**Issue by xcbtrader** [spesmilo/electrum#3896]
Hello.
I install the new versión of electrum and the wallet not open.
I see this error:
Cannot mix incompatible Qt library (version 0x50901) with this library (version 0x50a00)
Abortado (`core' generado)
I run in ubuntu 16.04
QMake version 3.0
Using Qt version 5.6.2

Any solution ???
Thanks

**Comment by bauerj** [comment]
Try

    sudo python3 -m pip install PyQt5

**Comment by xcbtrader** [comment]
Requirement already satisfied (use --upgrade to upgrade): PyQt5 in ./.local/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): sip<4.20,>=4.19.4 in ./.local/lib/python3.5/site-packages (from PyQt5)

**Comment by SomberNight** [comment]
So try with `sudo python3 -m pip install PyQt5 --upgrade`

**Comment by xcbtrader** [comment]
Same error :-(

Installing collected packages: sip
  Found existing installation: sip 4.19.5
    Uninstalling sip-4.19.5:
      Successfully uninstalled sip-4.19.5
Successfully installed sip-4.19.7
Cannot mix incompatible Qt library (version 0x50901) with this library (version 0x50a00)
Abortado (`core' generado)

**Comment by lzsaver** [comment]
As a workaround you may install Electrum in virtualenv.
```
python3 -m pip install virtualenv
python3 -m virtualenv "${HOME}/electrum"
pushd "${HOME}/electrum/bin"
./pip install -U setuptools pip wheel PyQt5 sip
./pip install -U https://download.electrum.org/3.0.6/Electrum-3.0.6.tar.gz
./electrum
popd
```

**Comment by xcbtrader** [comment]
Thanks!!!
Work Fine!
