### ISSUE TITLE
cannot deserialize transaction, skipping

### ISSUE THREAD

**Issue by jhoenicke** [spesmilo/electrum#3899]
Hi, after upgrading electrum to latest master, I get the following problem in one of my old wallets:

    [Synchronizer] cannot deserialize transaction, skipping f570d5d1e965ee61bcc7005f8fefb1d3abbed9d7ddbe035e2a68fa07e5fc4a0d

Yes I know I have weird transactions in my wallet :)

The tx is completely valid despite the strange p2sh scripts.  I think this problem is quite new (after 3.0 release). Previous releases of electrum didn't have a problem with this transaction.

**Comment by SomberNight** [comment]
Probably introduced in 3.0.0, specifically https://github.com/spesmilo/electrum/commit/d9f2edf6b0c8d8e1b5219bfa5cfeac903b6a2561#diff-0836bbd9465f2a87282f88740301e295R381
as the `return` no longer returns from `parse_scriptSig`, only from the new subroutine (`parse_redeemScript`)

Works as expected in 2.9.4.

**Comment by SomberNight** [comment]
Thank you for this report.
