### ISSUE TITLE
The wizzard of seqwit wallet won't close

### ISSUE THREAD

**Issue by stareye72** [spesmilo/electrum#3902]
Creating seqwit wallet on windows 10 with the Installer won't close it hangs on creating addresses.

**Comment by SomberNight** [comment]
What version of Electrum?
Can you try with a clean datadir? (temporarily rename `%appdata%/Electrum/` and try then)

**Comment by stareye72** [comment]
@SomberNight  3.0.6 and did it already but didn't worked.

**Comment by ecdsa** [comment]
@SomberNight can you reproduce that? what exactly does he mean?

**Comment by SomberNight** [comment]
No, I can not reproduce. I believe he gets stuck somewhere around here:
```patch
diff --git a/lib/base_wizard.py b/lib/base_wizard.py
index ab18b761..afe4c200 100644
--- a/lib/base_wizard.py
+++ b/lib/base_wizard.py
@@ -513,6 +513,7 @@ class BaseWizard(object):
 
     def create_addresses(self):
         def task():
+            while True: pass
             self.wallet.synchronize()
             self.wallet.storage.write()
             self.terminate()
```
Maybe he gets a deadlock here?
https://github.com/spesmilo/electrum/blob/51630416fc2e1b7bdea2e008f3f8f42d40fdd615/lib/wallet.py#L2056-L2057
I don't know.

@stareye72 Does it happen when creating any type of wallet, every time?
