### ISSUE TITLE
Importing contacts fails if source wallet is fully encrypted

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#3904]
So first of all the procedure for importing contacts is a little unintuitive. You can't export contacts only import them and the way to import them apparently is by selecting the wallet file you want to import from. If that wallet has full wallet encryption then importing fails silently. Even when running electrum with the -v option there are no error messages displayed. def import_file in contacts.py [just returns](https://github.com/spesmilo/electrum/blob/master/lib/contacts.py#L55) when the json in the file doesn't validate. Ideally it should prompt for the wallet password, decrypt it and then import the contacts.

**Comment by SomberNight** [comment]
I can offer https://github.com/spesmilo/electrum/commit/909c063eb1922d0a7e4b61d5538cb5b34edbf1e7 for now. The actual implementation of importing from an encrypted wallet is up for grabs.
