### ISSUE TITLE
Not able to send ZCL to another ZCL wallet

### ISSUE THREAD

**Issue by izzytoshi** [spesmilo/electrum#3905]
I have verified that the address is correct and that I have the correct ZCL value I want to send is the correct field but hitting "send" doesn't so anything.  Could I be missing a file?  Should I uninstall and reinstall wallet?  I'm using the latest version. 1.0.3

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl
