### ISSUE TITLE
Verified transaction zero amount

### ISSUE THREAD

**Issue by GerGys** [spesmilo/electrum#3909]
Hello,
I used to have an electrum wallet 2.6.4, which I upgraded to 3.0.6. I upgraded it, because it was stuck with "synchronizing" for a few days and didn't connected to any servers at all. During that time I received btc in the wallet. In 2.6.4 version this transaction was "not verified". When I upgrade the version, the transaction is "verified", but the received amount is +0.  and isn't in my balance. I've checked the transaction in blockchain and everything is fine there, it's verified. Please, check the attached file.
Please, help me! What I should do to get this amount in my balance? 
Btw. now I got both electrum wallets (the new one and the previous one) in my program files.I don't know if I have to delete the older version.
I need your help, because I don't know so much about it. And I am a women :)
Thank you in advance for your help! I really appreciate it!

![capture](https://user-images.githubusercontent.com/36502472/36256343-2ebb1f18-125b-11e8-8bf8-0fb9fca7c93b.PNG)

**Comment by ecdsa** [comment]
what is the transaction ID ?

**Comment by GerGys** [comment]
Transaction ID : ae0c29d96d5e9c513222ce5950bc8071897692721271b1272812607e2139b1f3

The new wallet 3.0.6 is connected

**Comment by ecdsa** [comment]
in this transaction, which address is yours?

**Comment by SomberNight** [comment]
Hmm. If I create a watch-only wallet for just that address in 2.6.4, it fails as you described (gets stuck syncing, etc); but when I upgrade to 3.0.6, it correctly handles the transaction (deserializes it, and requests and verifies the merkle proof).

Did you upgrade from 2.6.4 directly to 3.0.6?

**Comment by GerGys** [comment]
I downloaded 3.0.6 from https://electrum.org/. 
Now I have 2 electrum icons on my desktop, but can't open 2.6.4 . The attached screenshot is from 3.0.6. It's connected and all transactions are verified. Just the last transaction's amount isn't in my balance.

**Comment by SomberNight** [comment]
Try restoring from your seed words.

**Comment by GerGys** [comment]
Some great people from bitcointalk, who helped me with the wallet updating, adviced me to delete the blockchain_headers file. But I got 2 blockchain_headers file: blockchain_headers and blockchain_headers.tmp. Should I delete both files? Or one of them and which one?

**Comment by SomberNight** [comment]
You can delete both. I am unsure if it will help however.
Have you tried restoring from seed?

Alternatively, another thing you can do:
- back up your wallet file (make a copy!)
- unhide the console (`View`>`Show Console`)
- go into the console tab, and run:
```
wallet.remove_transaction("ae0c29d96d5e9c513222ce5950bc8071897692721271b1272812607e2139b1f3")
```
- exit electrum, and then reopen it

**Comment by GerGys** [comment]
To restore the entire wallet? How to do that? 
In my saved txt I see, that I got 13 words saved as a seeds.

**Comment by SomberNight** [comment]
> How to do that?

https://bitcoinelectrum.com/restoring-your-standard-wallet-from-seed/

**Comment by GerGys** [comment]
I uninstalled everything from the computer, do the installation again, restore it from the seeds and now everything is working and the last transaction is in my balance. Now have one working wallet on two computers. (Because, just in case, I restored it on one more computer). 
Thank you very much for your help! Thank you also to the nice people from bitcointalk, who adviced me perfect!

**Comment by SomberNight** [comment]
Great. :)

Can you answer this question:
> is the wallet still 'synchronizing'?
So, on the original picture, with the incorrect balance using the updated version, did the wallet get stuck "synchronizing" or did synchronization finish?

**Comment by GerGys** [comment]
Thank you very much for your help too! I appreciate it!
On the attached here picture is the updated version 3.0.6. The previous wallet version was 2.6.4. When I updated it to 3.0.6  and the wallet got synchronized. On the picture is synchronized and connected (with green circle).

**Comment by bauerj** [comment]
Good to know, thanks!
