### ISSUE TITLE
Electrum Wallet Malfunctioning

### ISSUE THREAD

**Issue by Chopkins995** [spesmilo/electrum#3917]
My bitcoin I purchased at an ATM is appearing in my mobile wallet, but not on my computer's wallet (same address). The transaction is confirmed on the blockchain. I am using the electrum mobile app for the first time because of this predicament. Because I'm new to the mobile app, I can't tell whether the transfer is in progress or not (it has been a day since I thought I initiated it). I keep reading the wallet is read-only, so I'm guessing I need to resolve whatever issue is preventing the bitcoin from appearing in my computer wallet.

Regardless, here's what's happening with the mobile app. The Invoice says Pending with No Signature. When I try to pay, the app shows the amount sent and fee, says the status is unsigned, and lets me view the transaction "barcode" without giving me the option to pay. Is this transfer in progress? Sorry for the noob question, ATM support person is useless. I have pics on my phone I can attach if useful.

**Comment by SomberNight** [comment]
Do you have a txid or address to share?
Also, a pic of the desktop client would be nice.

**Comment by Chopkins995** [comment]
Re_Installed electrum and solved the problem, didn't think to do that earlier. Now my keyboard is randomly capitalizing letters but that's less concerning. Thank you!
