### ISSUE TITLE
Add option to deduct fee from amount sent

### ISSUE THREAD

**Issue by elonmuskismyhero** [spesmilo/electrum#3919]
Like bitcoin core wallet,electrum should add the fucntion which deducts the transferring fee from the coins sent. It's useful when people try to clear a wallet.

**Comment by bauerj** [comment]
If you want to send all the coins, you can enter "!" into the amount field.

**Comment by SomberNight** [comment]
(or you can click the "Max" button)

**Comment by SomberNight** [comment]
Unless there is a large demand for this feature, I am against this; I think it would just introduce unnecessary complications.

**Comment by ecdsa** [comment]
ack. cited use case is "to cleear a wallet", which is covered by the mayx button
