### ISSUE TITLE
Replace python-ecdsa with faster alternative

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3926]
As in https://github.com/spesmilo/electrum/issues/3778#issuecomment-360976713

Potential options:
- https://github.com/ofek/coincurve (python wrapper for libsecp256k1)
- https://github.com/ludbb/secp256k1-py (python wrapper for libsecp256k1)
- https://github.com/Legrandin/pycryptodome

**Comment by ofek** [comment]
I can guide anyone with the use of `coincurve` :smile:

**Comment by SomberNight** [comment]
@ofek 
How should one sign and then verify a message? The signature types are incompatible..?
I would like to use `sig = PrivateKey.sign_recoverable(...)` which gives a 64 byte (+recid) sig.
Both `PublicKey.verify` and `verify_signature` expect a DER encoded signature.

I would like to use something like `cdata_to_der` but that wants a pointer, not bytes? e.g.
```
der_sig = coincurve.ecdsa.cdata_to_der(sig)
```
So currently I am using python-ecdsa as:
```
r, s = ecdsa.util.sigdecode_string(sig, SECP256k1.order)
der_sig = ecdsa.util.sigencode_der_canonize(r, s, SECP256k1.order)
```

**Comment by ofek** [comment]
Sorry, I was ill this week. You want `recoverable_convert` which you can then pass to `cdata_to_der`:
https://github.com/ofek/coincurve/blob/865db90c3e8541ebe8bf20b89e3acebfd5deb4d1/coincurve/ecdsa.py#L126

**Comment by SomberNight** [comment]
oh right. I was not really looking under the warning :)
https://github.com/ofek/coincurve/blob/865db90c3e8541ebe8bf20b89e3acebfd5deb4d1/coincurve/ecdsa.py#L79

**Comment by Engelberg** [comment]
In 3.2.2 I'm now getting a warning when running under Tails "[ecc] warning: libsecp256k1 library not available, falling back to python-ecds".  Is this a concern, or is the fallback option perfect viable?

**Comment by SomberNight** [comment]
it's only printed when running in verbose (-v) mode, right? it can be ignored; python-ecdsa is what all pre-3.2 versions of electrum used

**Comment by Engelberg** [comment]
I received the warning just when invoking "python3 electrum" to run electrum, so I wasn't explicitly triggering a verbose mode.  But thanks for letting me know it can be ignored.
