### ISSUE TITLE
Package pycryptodomex with Linux binaries

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3927]
Thanks to https://github.com/spesmilo/electrum/pull/3886 we now package pycryptodomex with MacOS and Windows binaries; but not Linux.

The main motivation for this is https://github.com/spesmilo/electrum/issues/3778

**Comment by ecdsa** [comment]
what do you mean by "package" ? add it to the tar.gz ?

**Comment by SomberNight** [comment]
Yes; so that it is available by default. (but we still wouldn't actually depend on it)

**Comment by ecdsa** [comment]
it is not pure python, it requires an installation.
I think we should figure out how to add optional dependencies to setup.py

**Comment by ecdsa** [comment]
I found that the following can be added to setup.py:
```
import pip
pip.main(['install', 'pycryptodomex'])
```
we can do the same for hardware wallet support.
