### ISSUE TITLE
Don't filter address list by default

### ISSUE THREAD

**Issue by rex4539** [spesmilo/electrum#3930]
I'm noticing some weird behavior on one of my wallets.

Although the balance on the bottom of the window appears normally and the transactions on the History window are accurate, the Addresses window does not show the balance.

![screen shot 2018-02-20 at 10 15 52](https://user-images.githubusercontent.com/227442/36413728-52a7bbfe-1628-11e8-89d2-5a9646258436.png)
![screen shot 2018-02-20 at 10 15 56](https://user-images.githubusercontent.com/227442/36413732-57b33cae-1628-11e8-829a-2c35a667be8b.png)

The balance should been shown for the address on the top, as being evident from the tx info.

![screen shot 2018-02-20 at 10 23 21](https://user-images.githubusercontent.com/227442/36413762-794593b2-1628-11e8-9745-5cfe2b832016.png)
![screen shot 2018-02-20 at 10 23 37](https://user-images.githubusercontent.com/227442/36413770-7eeedfbc-1628-11e8-99ee-bbf3206568e7.png)

For example, on another wallet everything appears fine.

![screen shot 2018-02-20 at 10 17 17](https://user-images.githubusercontent.com/227442/36413821-ab17047a-1628-11e8-9ae5-fad7fb19648c.png)
![screen shot 2018-02-20 at 10 17 25](https://user-images.githubusercontent.com/227442/36413831-b249cbb0-1628-11e8-80ea-fb54b0ee5f0e.png)

Any ideas why the first wallet is not displaying the balance in the Addresses window?

**Comment by ecdsa** [comment]
maybe de default filter should be "All & Funded".
also, green/yellow color could help

**Comment by rex4539** [comment]
I figured out what is going on.

The address with the funds is under Change filter, not Receiving.

I would argue it's quite difficult to spot. I would have never thought to look there in the first place.

Any casual user would assume Receiving filter would list all the addresses. That's where I stumbled :)

**Comment by ecdsa** [comment]
did you really assume that the "receiving" filter was listing all addresses, or did you just not see the filter?

**Comment by rex4539** [comment]
I really assumed that Receiving filter combined with "All" would mean "list all receiving addresses".

Apparently, that is not the case.

Obviously, a wrong assumption on my part but this is the logical thing to assume.

**Comment by ecdsa** [comment]
change addresses are not receiving addresses

**Comment by rex4539** [comment]
Yes, I understand now, hence the wrong assumption comment above.

It is actually a UX issue.

The average user would expect to find all the addresses listed.

Technically, you are right though.

Perhaps a solution would be to add another filter "Receiving & Change" and have it selected by default. This way, all addresses will be shown by default to the user.

Then if user wants to customize, they can manually change to "Receiving" or "Change".

**Comment by ecdsa** [comment]
fixed in 51368f6aa88dab2b2c576d4fd4260972b26ae644
