### ISSUE TITLE
string.format does not work on kivy for translated strings

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3941]
![kivy_string_format](https://user-images.githubusercontent.com/29142493/36458469-49a55958-16af-11e8-8402-4f4a5ab47979.png)

https://github.com/spesmilo/electrum/blob/363f3766d753f905bafe770114a30f489c448620/gui/kivy/uix/ui_screens/network.kv#L14

It works with `%d` or if I remove the wrap of `_()` but not like this.

**Comment by SomberNight** [comment]
Added to 3.1 milestone: we need to deal with this before a release... a potential workaround is not using string.format for kivy :)

**Comment by bauerj** [comment]
Why doesn't it work? Is `_("")` not a string?

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/blob/041ebc4583d0954fdb95114dc6343196b3e6685f/gui/kivy/i18n.py#L16-L18

consider the call: `_("{}")`

If we return `_.lang(s).format(*args, **kwargs)`
then we get `IndexError: tuple index out of range` because `args` is `()` and there are more `{}` slots than things to substitute

If we return `_.lang(s).format(args, kwargs)`
then we get back `()`, because `args` is `()`; and subsequent string.formats() won't work obviously

I checked and we don't actually seem to make use of `args` and `kwargs` to the `_()` call pretty much anywhere; so I suggest we just drop them.
