### ISSUE TITLE
Import Bech32 SegWit Wallet Seed

### ISSUE THREAD

**Issue by goodProjects** [spesmilo/electrum#3942]
I see it's only possible to create SegWit Wallet on electrum but if I have bech32 segwit wallet it's not possible to import it. 

Steps: 
0- Started Electrum on testnet
1- Wallet Kind: Standard
2- I already have a seed
3- Inserted Seed Phrase and checked bip39
4- Changed The path to 49 and coin type to 1 (testnet) 

Result Bitcoin P2SH Addresses instead of bech32! 

is that an expected behavior on TestNet Network?

**Comment by SomberNight** [comment]
> if I have bech32 segwit wallet

exactly what kind of seed do you have?

If it is an electrum seed, leave the bip39 option alone!
If it isn't, well, bip49 is specifically for p2wpkh-p2sh, which uses p2sh addresses (base58), not bech32.
Perhaps what you want is bip84, which is like bip49 but for p2wpkh. That is not yet in a release, but git master has it.

**Comment by SomberNight** [comment]
Yes, the master branch already has this (bip84). It also works with Trezor and Ledger.
It will be included in the 3.1 release.

**Comment by SomberNight** [comment]
(sorry, master is bit unstable atm... maybe try to checkout https://github.com/spesmilo/electrum/commit/670194b92037dba020ef8b6bfe5922560c7f5b26)
