### ISSUE TITLE
malformed unsigned transaction crash

### ISSUE THREAD

**Issue by alokmenghrajani** [spesmilo/electrum#3945]
I accidentally tried to load `01000000006031efe9b2e1cb1d0fb3c3a299fd5dc34712712e6da2e150e8af7748ef08d8fa000000005701ff4c53ff0488b21e010c440a00800000008b534eac3fd592293944b0f907ac57d4089aab048ca8f97efdda4fb0d17bcf7503503da8fb69557353f33f53eb68d9ed41ef0aa7ec43f51c6848fa512067b3006200000600feffffff0200e1f505000000001976a914091af9ea72970a1baf27602a622b96c7124019e888ac2097400d000000001976a9149943939f86bb7ce32baf1efd73b1d16968fa9f5588ac33981300` and Electrum crashed.

The correct transaction would have been `0100000001...`. This happened on Mac OS X. The following stack trace might help?

> Traceback (most recent call last):
>   File "Electrum-3.0.5-py3.6.egg/electrum_gui/qt/main_window.py", line 2135, in do_process_from_text
>   File "Electrum-3.0.5-py3.6.egg/electrum_gui/qt/main_window.py", line 755, in show_transaction
>   File "Electrum-3.0.5-py3.6.egg/electrum_gui/qt/transaction_dialog.py", line 43, in show_transaction
>   File "Electrum-3.0.5-py3.6.egg/electrum_gui/qt/transaction_dialog.py", line 59, in __init__
>   File "Electrum-3.0.5-py3.6.egg/electrum/transaction.py", line 589, in deserialize
>   File "Electrum-3.0.5-py3.6.egg/electrum/transaction.py", line 469, in deserialize
> AssertionError
> zsh: abort      /Applications/Electrum.app/Contents/MacOS/Electrum --testnet -v

**Comment by ecdsa** [comment]
how did you create that transaction?

**Comment by SomberNight** [comment]
This is now better protected against in https://github.com/spesmilo/electrum/commit/93619c8341dd57c7d4e7c3bd2a2d82bf47207919
If you modified the raw txn manually in any way to result in the malformed txn, there is not much more we can do, and in that case the issue can be closed.

**Comment by alokmenghrajani** [comment]
> how did you create that transaction?
I was manually taking a transaction apart and failed to properly re-assemble it.

> This is now better protected against in `93619c8`
Thanks for the quick fix!

>If you modified the raw txn manually in any way to result in the malformed txn, there is not much more we can do
IMHO, telling the user the tx is malformed is better than crashing.

**Comment by SomberNight** [comment]
> I was manually taking a transaction apart and failed to properly re-assemble it.

All right, matter resolved then. :P Thanks for saying.
