### ISSUE TITLE
Ledger Nano S not detected on Linux

### ISSUE THREAD

**Issue by ennethouse-darhsic** [spesmilo/electrum#3947]
I am trying to use electrum (version 3.0.6) with my Ledger Nano S. It works fine on my Windows machine, but is not recognized on my Debian-based OS (PureOS). I get an error from electrum that “No hardware device detected.”

I followed the instructions from Ledger: https://support.ledgerwallet.com/hc/en-us/articles/115005165269
I have verified that I am a member of group ‘plugdev’. Browser support is disabled. I installed Chromium and the Ledger Chrome App, and it works with that. Still not detected by Electrum.

Also tried multiple USB ports and cables, no luck. Seems to be recognized and have rw permissions:

$ lsusb
Bus 001 Device 011: ID 2c97:0001
$ ls -al /dev/bus/usb/001/011
crw-rw---- 1 root plugdev 189, 10 Feb 21 08:41 /dev/bus/usb/001/011

I also tried `sudo pip3 install btchip-python` but got a compilation error.

Has anyone got a Nano S to work with Electrum on Linux, any suggestions?

**Comment by SomberNight** [comment]
> Has anyone got a Nano S to work with Electrum on Linux

Yes, it should work.

> I also tried sudo pip3 install btchip-python but got a compilation error.

That would be what we need to help.

Try:
```
sudo apt-get install libusb-1.0-0-dev libudev-dev
sudo pip3 install btchip-python
```

**Comment by ennethouse-darhsic** [comment]
That worked, thank you!
