### ISSUE TITLE
Merchant - url not pointing on payment request server

### ISSUE THREAD

**Issue by silverowiec** [spesmilo/electrum#3979]
After configuring electrum merchant from steps from documentation, everything works (payment recognizing, web socket etc) but electrum wallet says ‘url not pointing on payment request server’ while clicking pay button. What could cause this? I use electrum daemon with default wallet. SSL from certbot. If the question is not complete please tell me or delete the the topic

**Comment by ecdsa** [comment]
please post the url

**Comment by silverowiec** [comment]
https://pay.app-name.com/index.html?id=4395da67fc

**Comment by SomberNight** [comment]
IIRC this error is due to not serving the file with the correct MIME-type on the webserver.

I have my Apache2 webserver at `/var/www/html/`
The payment requests are in subdirectories of `/var/www/html/r/req`
In `/var/www/html/r/req/.htaccess` I have:
```
ForceType application/bitcoin-paymentrequest
```
I also have `mod_mime` enabled.
I can't remember if I needed anything else to make it work.

**Comment by ecdsa** [comment]
oh, we should add that to the documentation

**Comment by silverowiec** [comment]
Unfortunately, it does not work yet. I did not have the file `.htaccess` but I created it and put `ForceType application/bitcoin-paymentrequest` into it. Enabled mod_mime by `sudo a2enmod mime`. After this not working, I also put `IncludeOptional mods-enabled/mime.load
ForceType application/bitcoin-paymentrequest` into my site.conf file and still the same problem.

**Comment by silverowiec** [comment]
Adding `AddType application/bitcoin-paymentrequest` in `mime.load` also does not help

**Comment by silverowiec** [comment]
Adding `ForceType` helped. Thank you for your time and help.

**Comment by SomberNight** [comment]
@silverowiec Adding it where? You had originally said that my suggestion did not work.

**Comment by silverowiec** [comment]
Into `.htaccess` file you mentioned before. Yes, but it was my fault (bad .htaccess directory) so I removed the spam
