### ISSUE TITLE
electrum doesn't allow to sen transactions with less than 2 sat/B

### ISSUE THREAD

**Issue by LukAss741** [spesmilo/electrum#3980]
Trying to send transaction with less than 2 sat/B which is totally reasonable fee nowadays leads to error something like "transaction fee too low. Transaction wouldn't propagate in network". Which is wrong because 1,5 sat/B is not too low and it will get confirmed.

Electrum is an advanced wallet so it shouldn't be limiting users from sending transactions exactly as they like.

**Comment by LukAss741** [comment]
I think it should only inform user about risk of transaction getting stuck unconfirmed in mempool but let user decide if they want to actually send it or not.
In the last weeks there were periods when mempool was totally empty so even transactions with zero or next-to-zero fee were getting confirmed.

**Comment by ecdsa** [comment]
the minimum relayfee actually depends on the server you are using
