### ISSUE TITLE
Electrum asking for Google authentication suddenly! Please Help!!

### ISSUE THREAD

**Issue by Akshansh1903** [spesmilo/electrum#3986]
The thing is earlier Electrum(2.8.3) was working without requiring any 2fa but suddenly it started. And I don't remember setting up any 2fa. I don't even remember my seed. All that I have is private key that we get by doing so.
Addresses>A list of public keys>Right clicking on the one that has the funds> private key.

Now on bitaddress.org the public address ( let this address be " address B") that I get corresponding to my private key is different from my actual public address to which I sent my funds.
On blockchain.info my actual public address does show the funds while the "address B" shows 0 funds.
How is this even possible?
Is the private key that I am getting from electrum wrong or what?
Thanks for helping :)

**Comment by SomberNight** [comment]
> earlier Electrum(2.8.3) was working

Have you now updated to the latest version? (You should always use the latest release.)
Was this "sudden change" right after you updated?

> I don't even remember my seed.

Well, that's a problem. The software warns you to backup your seed words. It even forces you to type it back.

> And I don't remember setting up any 2fa

Well, someone did.

Just to be clear, having/not having 2fa is an immutable property of the seed words themselves; hence of the wallet too. You can't just suddenly enable 2fa for e.g. a standard wallet. You need to create a seed/wallet that is of 2fa type.

> Now on bitaddress.org the public address ( let this address be " address B") that I get corresponding to my private key is different from my actual public address 

I would guess bitaddress is displaying a "1..." address (p2pkh), while Electrum is displaying a "3..." address (p2sh-multisig).  You can create multiple different types of addresses given a private key; bitaddress is just creating a different one.

2fa wallets are 2-of-3 multisig; the wallet stores one, the seed has another one (actually the seed has two, it also includes the one that is in the wallet); and the third key is controlled by the TrustedCoin company: https://api.trustedcoin.com/#/electrum-help
The key that you can export from Electrum is only one of these three, and, again, you would need two.

To control these coins in  this 2fa wallet, you need either
- the seed words
- the wallet file + password, AND the OTP codes (e.g. Google Auth app)

**Comment by SomberNight** [comment]
> 2fa wallets are 2-of-3 multisig

This means that for each address, there exist three private keys, out of which you need two to be able to spend from it. You only have one.

**Comment by AbdussamadA** [comment]
Maybe you have more than one wallet on your system. Go to file > recently open or file > open to open the other wallet. You still need the 2fa code or seed to spend from the 2fa wallet but at least it'll explain how you ended up with a 2fa wallet.
