### ISSUE TITLE
Redirect to translated pages of the website when clicking on Official Website/Documentation

### ISSUE THREAD

**Issue by iceTwy** [spesmilo/electrum#399]
The Electrum website has recently been translated to French and German, so I thought it would be better to redirect the user to the appropriate links (i.e. the translation) based on the language they've chosen in Electrum.

Example: if I was to use the French translation for Electrum, and I'd click on Official Website/Documentation, it should redirect me to http://electrum.org/fr/ and http://electrum.org/fr/documentation.html, respectively.

**Comment by ecdsa** [comment]
won't fix
