### ISSUE TITLE
Build against stable kivy

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3990]
We are building the Android app with kivy master.

https://github.com/spesmilo/electrum/blob/df9935e6af3a8c65b2d5b5f55f77e985d5c4c384/gui/kivy/tools/buildozer.spec#L34

This seems to be the case since the earliest commits related to the Android app.
Is there a particular reason for this?

I suggest to build against a stable version; say 1.10.0 atm.

We should do this so that stuff does not suddenly break in VERY subtle ways, c.f. https://github.com/spesmilo/electrum/commit/a0023791e5d116ff06b2ae250e858f34d77c5a7d >.<

**Comment by ecdsa** [comment]
ack. can any tag be used with buildozer.spec?

**Comment by ecdsa** [comment]
note: with my current installlation, it is not possible to build the apk using kivy==1.10.0

**Comment by akshayaurora** [comment]
@ecdsa any tag can be used in buildozer.spec if kivy==1.10.0 is failing then we should look into why that is failing.

**Comment by ecdsa** [comment]
@akshayaurora thank you, but I know that tags can be used with buildozer. 
Please read my comment as "I tried with kivy==1.10.0 and the build failed"

**Comment by ecdsa** [comment]
we use a fixed commit hash in buildozer.spec. this issue should have been closed long ago.
