### ISSUE TITLE
theres no connection on my 3.0.6 electrum wallet anyone know how to fix that its kind of pissed me off lol

### ISSUE THREAD

**Issue by johnwilly7** [spesmilo/electrum#3999]

**Comment by ysangkok** [comment]
Did you mistakenly try to use a proxy? How did you determine that there is no connection?

**Comment by johnwilly7** [comment]
it says it at the bottom left, the circle at the bottom right is red, i sent money to it and it says sent but on electrum its not there im guessing it because of no connection

**Comment by johnwilly7** [comment]
the proxy is checked on socks5

**Comment by ecdsa** [comment]
so, you have your answer: you mistakenly set a proxy. 
please do not abuse github, it is not a support line..
