### ISSUE TITLE
Not verified

### ISSUE THREAD

**Issue by jimslag** [spesmilo/electrum#4001]
I recently updated to 3.0.6 and when I opened all my transactions say Not Verified. How long do I have to wait for it to verify or update? It has been a week and still not updating.

**Comment by AbdussamadA** [comment]
Close it and run it again or switch servers.

**Comment by jimslag** [comment]
Did that and still get Not Verified.

**Comment by SomberNight** [comment]
Can you please retest with 3.1.0?

**Comment by ecdsa** [comment]
closing, no answer
