### ISSUE TITLE
real time fee estimator

### ISSUE THREAD

**Issue by dlebrecht** [spesmilo/electrum#4006]
hi, we're releasing a powerful fee estimator (congestion manager) and providing rest and websocket end points

https://fees.truelevel.io
https://github.com/zkao/btc-congestion-manager

it would be great to see it integrated on this powerful wallet

**Comment by bauerj** [comment]
Hey,

thanks for the suggestion. 

A big concern for a lot of our users is privacy, which means that they would not be comfortable with their wallet connecting to a third-party service by default.

If you want to give users the option to use your service, you can provide an Electrum plugin that fetches the data from your webservice.

Would you like to do that?

**Comment by ecdsa** [comment]
@bauerj I think what they call "real time" estimator is a mempool depth estimator, which we have already

**Comment by ecdsa** [comment]
thank you for your feedback. the ETA estimation is completely different from the mempool estimation, and they are not supposed to be consistent with eachother. I will try to improve the GUI, to avoid this confusion
