### ISSUE TITLE
"Sweep" Button Shaded Out for Private Key Importing

### ISSUE THREAD

**Issue by ksharm03** [spesmilo/electrum#4009]
![btcp_snip](https://user-images.githubusercontent.com/11086507/36940273-f6c6914a-1f0d-11e8-8965-d110d81e471a.JPG)

The "sweep" button is shaded and doesn't work, even after inserting the private keys and wallet address of the ZCL electrum wallet.

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl
