### ISSUE TITLE
Bitcoinprivate electrum wallet- not verified but still i can send /receive/see my btcp

### ISSUE THREAD

**Issue by yithak** [spesmilo/electrum#4010]
Hello there.

Ive installed electrum btcp wallet for windows . Ive created a new wallet, saved the seed key , set up a password. Then ive pressed sweep private key. ive introduced by typing my private key from my zcl electrum wallet. saw my amount and pressed send.
I do received in a matter of seconds my btcp in my wallet , but if I look at history even after more than 2 h its still as NOT VERIFIED.
Ok . ive made another wallet and transferred funds between them. In a matter of seconds I got my btcp in the second wallet - but in both wallets its says NOT VERIFIED. but both balances are updated.
Ok. ive sent funds to a friend. He got the funds- the clock showed up and then the green check mark.
on both sides the balances were good updated.
THEN he sent me back the amount. On his side - green and verified+ confirmations- BUT on  my side its still not verified. BUT I got my funds in my wallet.

Can anyone please tell me if I did something wrong ?
Thank you
![1](https://user-images.githubusercontent.com/37029689/36940528-ba993498-1f44-11e8-9123-60d5060b842e.jpg)
![2](https://user-images.githubusercontent.com/37029689/36940530-be26bd88-1f44-11e8-990f-d78976cef061.jpg)
![3](https://user-images.githubusercontent.com/37029689/36940531-c0faf75e-1f44-11e8-8506-730ec0709ac3.jpg)
![4](https://user-images.githubusercontent.com/37029689/36940532-c372c85e-1f44-11e8-9fad-af652b9a92dd.jpg)

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl

**Comment by dabura667** [comment]
This is not the repository for Bitcoin Private Electrum.

We have no clue how their app works. Ask them.

**Comment by yithak** [comment]
From their wallet was this site linked. Sorry- did it already.
Thank you.

**Comment by SomberNight** [comment]
Uhh that might have been the wrong repo I linked you to. It is very hard to keep track...... https://github.com/BTCPrivate/electrum-btcp
