### ISSUE TITLE
BTCP Electrum Wallet 1.0.0 - Not Connecting? 

### ISSUE THREAD

**Issue by throwawaypdx** [spesmilo/electrum#4012]
Just downloaded, ran, followed all instructions... Have been unable to get the wallet to connect for several hours. What am I missing? 

Thanks in advance for any suggestions!

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here https://github.com/BTCPrivate/electrum-btcp (?? I think)
