### ISSUE TITLE
Funds not transfered zclassic

### ISSUE THREAD

**Issue by elhefe7886** [spesmilo/electrum#4013]
i transferred funds from my zclassic native wallet to my cryptopia wallet over 3 days ago and still have not recieved it. the native zclassic wallet says it was transferred, transaction id is af8fc2fb9f4f308f25116e17ae8d37d17e89790fa2c4b7f8ff87eab79f98a533

**Comment by ysangkok** [comment]
We don't support ZClassic even if it is linked from their repo. You need to figure out where the actual ZClassic repo is, and make them fix the link so that other ZClassic users won't mistakenly report the issue here and waste everybody's time.
