### ISSUE TITLE
Restoring Trezor Segwit wallets

### ISSUE THREAD

**Issue by jackbox** [spesmilo/electrum#4014]
If you enter 24 seed words from a Trezor One to restore a wallet in electrum, select BIP39 and change derivation to "m/49'/0'/0'" the wrong addresses are generated. In order to get the correct addresss a blank space (" ") must be added after the last word. Then, and only then, will Electrum generate the correct Segwit address from Trezor seed words. Also, if you use the passphrase feature, you must add the space after both the list of word sand after the passphrase or Electrum will generate the wrong set of addresses. This should be corrected as most people won't realize they have to enter the blank space to get the correct set of addresses that match the Trezor. I only found it through a lot of trial and error and experimentation.

**Comment by dabura667** [comment]
I was not able to reproduce the issue.

Could you be more specific?

**Comment by jackbox** [comment]
Restoring Trezor One Segwit wallet using 24 word seed. It creates a wallet
with different Segwit address than the Trezor wallet has. The only way to
get the same Segwit addresses as the Trezor One wallet is to add a blank
space (i.e., hitting space bar) after the last word in the list. If you add
the blank space after the 24th word then the Segwit addresses will match
the Trezor One. This is selecting BIP39 and using derivation "m/49'/0'/0'"
for Segwit. If a passphrase is used you must add a blank space after the
word list and after the passphrase. To recreate this you need a Trezor One
with segwit account and try to get same address doing a restore in
Electrum. Don't add the space and the wallet addresses are completely
different. People are not going to know they need to add a space to get the
correct addresses. I discussed this with Slush and he said it is a bug and
asked me file the issue on Electrum Git.

**Comment by Rayserzor** [comment]
I don't think it's a bug in Electrum, because Samourai Wallet works in the same way. 

For recovery seed, you need to blank space the last word too.

**Comment by SomberNight** [comment]
**What version of Electrum?**

Let's forget about Trezor.
Let's forget about passphrases (seed extenstions), to simplify this.
From your statement it follows that you are getting different addresses, in Electrum, if you add an extra space after the last seed word. I tested this, and it is not the case for me. I also looked at the code, and I don't see how it could be the case with all the normalization we are doing, but okay.

Here is a bip39 seed:
```
photo gaze net eight mixed salt bench dune inch arch federal cycle oxygen consider pole maid vast travel soap aim hip strategy melody black
```
With the bip49 derivation of `m/49'/0'/0'`, what is your first receiving address,
- if you DO NOT add an extra space to the end of the seed?
- if you DO add an extra space to the end of the seed?
In both cases for me it is `34x8k32DoUzfhc4P4ZWEmoEo2P3MFmNu5d`.

**Comment by ecdsa** [comment]
I doubt this issue is real.

**Comment by jackbox** [comment]
It is real because with space or without I get different addresses. Only
correct if space is used.

**Comment by ecdsa** [comment]
perhaps you are not using electrum?

**Comment by jackbox** [comment]
Electrum 3.0.6

**Comment by jackbox** [comment]
Electrum 3.0.6

With your seed words above I get the same result space and no space; but
with my 24 word Trezor seeds with and without space I get a completely
different set of addresses. That is the same result with four different
Trezor One's tested. Try it with Trezor seed words from a Trezor One.

**Comment by SomberNight** [comment]
> With your seed words above I get the same result space and no space; but
with my 24 word Trezor seeds with and without space I get a completely
different set of addresses

It would be nice if you could provide such an example seed.
(not one you use with real coins please)

**Comment by jackbox** [comment]
Ok. I don't have time now as will be traveling overseas but when I have
time I will reset a Trezor and try it with the new seed words. All my seeds
right now are being used to claim forks. That is why I needed to put them
in them in Electrum to get the private keys. I will update here in about
one month.

**Comment by HardCorePawn** [comment]
I **CANNOT** replicate this issue: https://bitcointalk.org/index.php?topic=2354707.msg31613435#msg31613435

Example seed generated by Trezor One:

> feature loan detect fix glance voice cargo kangaroo pilot apple genuine parade business jazz fortune sell dynamic indoor same absorb host slight educate toe

Was able to successfully create the SegWit wallet by selecting "Options" -> "BIP39 Seed" and typing in seed WITHOUT the space at the end... "BIP39 (Checksum OK)"... and wallet created generates the same addresses as shown in the Trezor wallet:

![trezorsegwitseedtesting_01](https://user-images.githubusercontent.com/448939/37010525-d6645f32-2150-11e8-9833-578d63a05fc5.png)
![trezorsegwitseedtesting_02](https://user-images.githubusercontent.com/448939/37010526-d6a14f1e-2150-11e8-9681-ced97d6e7ee2.png)
![trezorsegwitseedtesting_03](https://user-images.githubusercontent.com/448939/37010527-d733c8c6-2150-11e8-832b-7632e2bfc90e.png)
