### ISSUE TITLE
load wallet via rpc is not working.

### ISSUE THREAD

**Issue by coineralpha** [spesmilo/electrum#4015]
curl --data-binary '{"id":"curltext","method":"daemon","params":{"subcommand":"status"}}' http://user:pass@127.0.0.1:7777

returns with error

{"id": "curltext", "error": {"code": -32602, "message": "Invalid parameters: run_daemon() got an unexpected keyword argument 'subcommand'"}, "result": null}

**Comment by bauerj** [comment]
What version of Electrum do you use?

**Comment by coineralpha** [comment]
electrum version
3.0.6

**Comment by SomberNight** [comment]
The correct usage of the `load_wallet` RPC is something like:
```
curl --data-binary '{"id":"curltext","method":"daemon","params":{"config_options":{"subcommand":"load_wallet", "wallet_path":"/home/user/.electrum/testnet/wallets/default_wallet", "password":"1234"}}}' http://user:pass@127.0.0.1:7777
```
