### ISSUE TITLE
Electrum Wallet with no transaction records

### ISSUE THREAD

**Issue by kwaldroop** [spesmilo/electrum#4018]
I successfully transferred my ZCL from Bittrex to my Electrum wallet 3.0.6 on 2/10/2018.  I tried to get back in to my wallet this morning 3/4/2018 and password didn't work so I restored my wallet using my 12 seeds. I was able to get back in to my wallet but there is no transactions in my wallet (Balance is 0). I tried the Tools, Pluggins and tried different servers by clicking on the green button but there is no change. Please help.  I have the Electrum Wallet screen shots of the receiving address I recorded, the receiving address and TxID from Bittrex, the Master Public key, and the Electrum addresses. Please let me know what I need to do.  Thank you very much

**Comment by kwaldroop** [comment]
I noticed that the Receiving Address of the Receive tab for my ZCL transitions fr Bittrex to my standard Electrum wallet started with t1U8..... which seems odd. Note that this receiving address is provided to users and nobody can change it.  I have the screen shot for my transactions.  The wallet I downloaded is electrum-3.0.6-setup.exe extract from the Electrum web site.

**Comment by bauerj** [comment]
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl

**Comment by Rayserzor** [comment]
ZCL? Electrum is bitcoin only.

**Comment by kwaldroop** [comment]
Thank you very much.
Sent from Yahoo Mail on Android 
 
  On Sun, Mar 4, 2018 at 1:11 PM, Johann Bauer<notifications@github.com> wrote:   
Hi. Electrum is for Bitcoin only. Try asking here: https://github.com/BTCP-community/electrum-zcl
