### ISSUE TITLE
p2sh error when trying to claim BTCP

### ISSUE THREAD

**Issue by JennyJennyB** [spesmilo/electrum#4021]
I held my BTC in the Electrum wallet for the BTCP fork. When I use my private key to sweep the BTCP wallet, I get the p2sh error. I had 2fa and a password on the electrum wallet. I was told to restore the wallet using my seed to a new wallet that is not password protected and I disabled the 2fa. I am still getting the same error. What should I do? I have looked over the github issues but am not a programmer and don't feel comfortable using the full node wallet.

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. You should probably try to get help from BTCP people.

However, what you could try is:
- in Electrum, restore your 2fa wallet from seed words
    - choose to disable 2fa (you should consider the security consequences of this; i.e. probably use an offline machine)
    - do not set a password on the wallet file
- open the wallet file in a text editor, and find your xprvs. I suggest searching for "keystore"
- in the BTCP Electrum fork, restore a 2-of-3 multisig (not 2fa !) wallet
    - cosigner1 is the first xprv
    - cosigner2 is the second xprv
    - cosigner3 is the "third" xpub

I am not familiar with BTCP at all, but for most bitcoin hardfork altcoins, given a decent fork of this project, this should work.

**Comment by JennyJennyB** [comment]
@SomberNight Thank you so much!

**Comment by JennyJennyB** [comment]
I set up 3 cosigners in my BTCP electrum wallet and it says i am watching only. How do I get it off watching only?

**Comment by SomberNight** [comment]
It should not be watching-only if you used 2 xprvs and 1 xpub in a 2-of-3 multisig wallet.
