### ISSUE TITLE
Recreating Tx with higher fee?

### ISSUE THREAD

**Issue by Yuki-Inoue** [spesmilo/electrum#4022]
Say I've created and broadcasted a Tx with low fee, and unfortunately, that fee was in fact too low so that no miner would mine them.

I think by recreating and broadcasting a Tx with higher fee, by spending (partially) the same TxOuts from the previous non-mined Tx, would effectively invalidate the previous Tx.

My question is: is it possible to create a Tx by spending Transaction Outputs which is already spent in an unconfirmed Tx already broadcasted?  Moreover, I mainly use Electrum from another program, so I'd like to ask, is such operation available from command line or from jsonrpc?

**Comment by ecdsa** [comment]
read the docs
