### ISSUE TITLE
BTCP electrum wallet is not getting connections

### ISSUE THREAD

**Issue by Damuammu** [spesmilo/electrum#4023]
Dear team,

Iam using electrum wallet for zcl, xvg and btcp. but for btcp connection is not getting, it says offline all time. Below are images for your investigation. Please help me.

![image](https://user-images.githubusercontent.com/749993/36962472-b4fd8682-208a-11e8-9141-74c370c561ad.png)
![image](https://user-images.githubusercontent.com/749993/36962557-045cd39a-208b-11e8-8ab6-2d0f11745c9c.png)
![image](https://user-images.githubusercontent.com/749993/36962595-28f192ae-208b-11e8-9a1e-67c13af9a990.png)

Thanks

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here https://github.com/BTCPrivate/electrum-btcp
