### ISSUE TITLE
p2sh error

### ISSUE THREAD

**Issue by Horeas** [spesmilo/electrum#4027]
I get this -2sh when i insert the data in sweep! How to fix this>?

**Comment by ysangkok** [comment]
Can you paste more details?

**Comment by SomberNight** [comment]
WIF private keys encode the script type since 3.0
It does not make sense to sweep a p2sh WIF key; it only contains a single ecdsa private key and the info that the key is used in multisig.

**Comment by SomberNight** [comment]
If you would like meaningful help, you need to provide more details regarding your intentions and context in general.
For example: have you exported the WIF keys from a 2FA wallet?

**Comment by Horeas** [comment]
Hello.

I exported the adreses from zcl wallet. I have them in a .csv file. I
downloaded the electrum btcp wallet. I made a standard wallet and tried to
sweep the adresses. I get that error.

**Comment by Horeas** [comment]
I have a multi-signiture wallet!

**Comment by Horeas** [comment]
I tried to do this:

   1. Create a new *ZCL standard wallet* and restore the 2FA wallet using
   your ZCL wallet "seed" codes.
   2. Disable the 2FA feature when presented with the option. DO NOT
   password protect this wallet.
   3. Navigate to C:/Users/YOUR-NAME/AppData/Roaming/Electrum-zcl/wallets.
   Open the new standard wallet file with Notepad.
   4. You will need to gather the 2 private keys (xprv) and one public key
   (xpub). To find this easily, press “CTRL+F” and search for “xprv”. Copy the
   2 “xprv” values as well as the last “xpub” value. You will need these in a
   later steps.
   5. Create a new *ZCL Multi-signature wallet*. Select “From 3 co-signers”
   on the first slider. Select “Require 2 signatures” on the second slider.
   6. To add the first co-signer, click “Use public or private keys”. Enter
   the first xprv key in this box.
   7. Add the second co-signer by entering the second xprv key into this
   box.
   8. Add the third co-signer by entering the pubx key into this box.
   Complete the set-up and add a password if desired.
   9. Create a new *BTCP Multi-signature wallet*. Select “From 3
   co-signers” on the first slider. Select “Require 2 signatures” on the
   second slider.
   10. To add the first co-signer, click “Use public or private keys”.
   Enter the first xprv key in this box. (Same xprv key used in step 6)
   11. Add the second co-signer by entering the second xprv key into this
   box. (Same xprv key used in step 7)
   12. Add the third co-signer by entering the pubx key into this box.
   Complete the set-up and add a password if desired. (Same xpub key used in
   step 8)
   13. Your BTCP should now be available in this new BTCP Multi-signature
   wallet.



Problem is that i have only one  private keys (xprv), not 2.

I even tried to make a btcp wallet using seeds from acl wallet and i didnt
get the btcp

**Comment by Horeas** [comment]
Hello. I tried what btcp team sugested in twitter. I opened the file from
my laptop default_wallet but i did not find the   2 private keys (xprv) and
one public key (xpub).
Then i tried to make a btcp eletrum wallet using the seed from zcl wallet.
It worked but no btcp in account.

I mention that when i try to sweep the data i get that msg: p2sh!

What can i do?

**Comment by HardCorePawn** [comment]
If you are attempting to claim from a 2FA wallet, you need to restore using your 2FA seed, but when you get to this screen:
![checkredeem8](https://user-images.githubusercontent.com/448939/37011327-786f4c30-2154-11e8-9248-47cb8c10ca19.png)

you MUST select DISABLE... and when prompted DO NOT create a password. Then you open the new wallet file using a text editor and scroll all the way to the bottom... you should see a section labeled "x1/", "x2/" and "x3/":
![disabled2fawalletfile_edit](https://user-images.githubusercontent.com/448939/37011422-ede4a06e-2154-11e8-8fed-08ba1be40d03.png)


When following your steps from your post above, use the xprv from X1 section, the xprv from X2 section and the _**xpub**_ from X3 section at steps 6,7 and 8:

> 6. To add the first co-signer, click “Use public or private keys”. Enter
   the first xprv key **(X1 xprv)** in this box.
> 7. Add the second co-signer by entering the second xprv key **(X2 xprv)** into this
   box.
> 8. Add the third co-signer by entering the pubx key **(X3 xpub)** into this box.
   Complete the set-up and add a password if desired.



Also, note that "Electrum" is BTC only... If you continue to have issues with Electrum-ZCL/BTCP, you will most likely need to contact the Electrum-ZCL devs here: https://github.com/z-classic/electrum-zcl

**Comment by SomberNight** [comment]
By now I think OP has received enough help and the issue has fully gone in the user-support direction which is not what github is for; so closing.

**Comment by Horeas** [comment]
Just so u know. I solved my problem. I had a multi sign account with 2
cosigners, not 3. I also had a extended seed. I had to mark the multi sign
then seed, then enter seed, then select the option and mark the extended
seed, click next, enter the extended seed, and then the xpub code and i
made my wallet
