### ISSUE TITLE
Allow Electrum to utilize the integrated GPU (macOS) (solution inside)

### ISSUE THREAD

**Issue by benbeton** [spesmilo/electrum#4030]
when starting Electrum 3.1.0 the discrete GPU is used instead of the integrated one. 
This can be fixed when adding 

_<key>NSHighResolutionCapable</key>
<string>True</string>_

to the **info.plist.**

please add this in the next release.

Fix -> Technical Q&A QA1734
https://developer.apple.com/library/content/qa/qa1734/_index.html

**Comment by SomberNight** [comment]
So you mean `NSSupportsAutomaticGraphicsSwitching`, right? Based on the link.

Like this?
```patch
diff --git a/contrib/build-osx/osx.spec b/contrib/build-osx/osx.spec
index a2c02f39..b33793ab 100644
--- a/contrib/build-osx/osx.spec
+++ b/contrib/build-osx/osx.spec
@@ -94,6 +94,7 @@ app = BUNDLE(exe,
              icon=electrum+ICONS_FILE,
              bundle_identifier=None,
              info_plist = {
-                 'NSHighResolutionCapable':'True'
+                 'NSHighResolutionCapable':'True',
+                 'NSSupportsAutomaticGraphicsSwitching':'True'
              }
 )
```

Maybe @bauerj can test :P

**Comment by benbeton** [comment]
yes, tested it on my machine, works fine

**Comment by bauerj** [comment]
I don't have a MacBook Pro so I can only test if the plist is generated correctly.

**Comment by bauerj** [comment]
The .plist looks good and according to the docs it should indeed fix the issue so I'm pushing the change.
