### ISSUE TITLE
Filter Addresses tab by unused by default

### ISSUE THREAD

**Issue by ejose19** [spesmilo/electrum#4035]
A common issue with Hardware wallet users (especially Trezor) is that we need to go to addresses tab, scroll down or sort by unused to grab the first unused address, right click then "Show on Trezor", this is of course longer than it should be. Previous versions of electrum displayed addresses by unused first, and I agree on this, either by making it by default or having an option to set it that persist on restart.

Also, this long process would be simplified by doing as #3364, just a nice "Show on Trezor" (or Show on HW if many hardware wallets support this) on the receiving tab, it would make the users not going to addresses tab to accomplish this.

**Comment by SomberNight** [comment]
No; I disagree, we should not filter by unused by default. By specifically changed the filtering to "all"/"all" by default, because there were users who freaked out when they could not find some of their addresses in the list... :/

What we could do however, is to persist the filter in config.

**Comment by ecdsa** [comment]
the real issue is #3364. this issue is just suggesting a workaround.
