### ISSUE TITLE
BTCP Electrum 1.0 changed addresses

### ISSUE THREAD

**Issue by javierea** [spesmilo/electrum#4051]
Sorry for my ignorance, already searched and didn´t find this:
My BTCP address changed today, same amount of coins... I still get coins sent to my "yesterday" address ? Will I lose what i mined and wasn´t send before address changed?

**Comment by enlly** [comment]
I am having the same issue; my address change today.

is it a bug? What adress do I use? new one or old one?

**Comment by ecdsa** [comment]
we are not providing support for BTCP
