### ISSUE TITLE
Testnet bip84 wallet does not work with ledger nano S

### ISSUE THREAD

**Issue by ken2812221** [spesmilo/electrum#4052]
Open ledger wallet file and it shows this:

![](https://i.imgur.com/LGrkVNG.png)

**Comment by SomberNight** [comment]
Hi. We broke existing testnet wallet files in 3.1; sorry.
https://github.com/spesmilo/electrum/blob/646044b43122e6523253fabc2702b41101bfc5d7/RELEASE-NOTES#L62-L69
Please recreate it.
