### ISSUE TITLE
Feature request: allow locking UTXO separately from addresses

### ISSUE THREAD

**Issue by yura-pakhuchiy** [spesmilo/electrum#4053]
So it would be possible to lock one UTXO without locking all other UTXOs from the same address.

**Comment by SomberNight** [comment]
do you mean the "freeze" functionality?

**Comment by ecdsa** [comment]
what is the use case for that? it seems overkill

**Comment by yura-pakhuchiy** [comment]
Yes, I meant freeze, sorry. Eg., you have several UTXO in one address and you signed transaction for future, have not broadcasted it and do not want to keep it saved in electrum. If address is not frozen, it is possible to accidentally spend UTXO from prepared transaction. But if address is frozen all others UTXO from this address will be frozen as well. One solution would be to move all other UTXO immediately after preparing transaction, but it would be easier just to freeze one UTXO.

**Comment by ecdsa** [comment]
that is not a compelling use case. 
it will add complexity to the user interface without clear benefit

**Comment by ecdsa** [comment]
I hope you are aware that electrum has coin control

**Comment by yura-pakhuchiy** [comment]
Yes, coin control is exactly what I'm speaking about. I do not see how additional item "Freeze" in right-click menu for UTXO in coin control tab will add a lot of complexity. More over, coin control is disabled by default, but this feature could be useful for people who enable it.

**Comment by yura-pakhuchiy** [comment]
Just FYI, Electron-Cash implements this:
https://github.com/Electron-Cash/Electron-Cash/issues/889

**Comment by yura-pakhuchiy** [comment]
Oops, looks like already implemented in https://github.com/spesmilo/electrum/pull/5152
