### ISSUE TITLE
Can't run nor compile Electrum-3.1.0 from source on macOS

### ISSUE THREAD

**Issue by nikitavoloboev** [spesmilo/electrum#4056]
I first tried to install Electrum-3.1.0 as macOS executable from the [official website](https://electrum.org/#download).

I opened the .dmg, transferred the .app to `/Applications` and opened it but nothing happened. The app did not boot up. Same thing happened if I tried again. No warnings were given too, it just didn't open.

I am running 10.11.6 macOS version.

I then tried to build Electrum from source. So I got the latest .zip version of Electrum from the website. Installed the dependencies with:
`brew install qt5 pyqt5 gettext`

And then in unzipped `Electrum-3.1.0` I ran: `python3 electrum` and got this error:

```Bash
~/Downloads/Electrum-3.1.0
❯ python3 electrum
Traceback (most recent call last):
  File "electrum", line 426, in <module>
    d = daemon.Daemon(config, fd, True)
  File "/Users/nikivi/Downloads/Electrum-3.1.0/lib/daemon.py", line 135, in __init__
    self.init_server(config, fd, is_gui)
  File "/Users/nikivi/Downloads/Electrum-3.1.0/lib/daemon.py", line 141, in init_server
    rpc_user, rpc_password = get_rpc_credentials(config)
  File "/Users/nikivi/Downloads/Electrum-3.1.0/lib/daemon.py", line 111, in get_rpc_credentials
    config.set_key('rpcuser', rpc_user)
  File "/Users/nikivi/Downloads/Electrum-3.1.0/lib/simple_config.py", line 140, in set_key
    self._set_key_in_user_config(key, value, save)
  File "/Users/nikivi/Downloads/Electrum-3.1.0/lib/simple_config.py", line 149, in _set_key_in_user_config
    self.save_user_config()
  File "/Users/nikivi/Downloads/Electrum-3.1.0/lib/simple_config.py", line 214, in save_user_config
    with open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nikivi/.electrum/config'
```

I checked if the directory does exist but it is a symlink:

```Bash
~/.electrum
❯ ls -la
total 77816
drwxr-xr-x    9 nikivi  staff       306  6 Mar 22:34 .
drwxr-xr-x@ 180 nikivi  staff      6120  6 Mar 22:43 ..
-rw-r--r--    1 nikivi  staff  39836160  6 Mar 22:02 blockchain_headers
drwxr-xr-x    2 nikivi  staff        68  6 Mar 22:02 cache
drwxr-xr-x   17 nikivi  staff       578 27 Nov  2014 certs
lrwxr-xr-x    1 nikivi  staff        45  4 Jul  2016 config -> /Users/nikivi/Dropbox/Mackup/.electrum/config
-rw-r--r--    1 nikivi  staff         0  6 Mar 22:34 daemon
drwxr-xr-x    2 nikivi  staff        68  6 Mar 22:02 forks
drwxr-xr-x    3 nikivi  staff       102 16 Jan  2014 wallets
```

Not sure what I can do to fix this. Thank you for any help.

**Comment by bauerj** [comment]
What happens if you remove the symlink?

**Comment by nikitavoloboev** [comment]
That solved it.

I have few questions though.

1. Why was this symlink there in the first place? I did install [electrum-ltc](https://electrum-ltc.org) and ran it before I installed electrum. Perhaps that added the symlink?
2. When I started electrum and chose to `automatically find server`, it just logged me into `default_wallet` but didn't allow me to create a password for it nor did I get a secret phrase that I got with LTC electrum wallet. What should I do in this case?

**Comment by bauerj** [comment]
1. My guess is that you (or some other program) created it. There is no code in Electrum that tracks down your Dropbox and places it's configured file there.
2. Did you create default_wallet? If not, delete it.

**Comment by nikitavoloboev** [comment]
> Did you create default_wallet? If not, delete it.

I have not. I am worried that deleting default_wallet would in some way interfere with electrum-ltc. 

Are these two wallets connected in any way?

**Comment by SomberNight** [comment]
What is in `default_wallet` if you open it with a text editor?
If it is human readable text, don't share the seed words or the xprv ("keystore"), but e.g. are the addresses there bitcoin addresses? Just to rule out the litecoin-collision.

**Comment by bauerj** [comment]
I assume that Electrum-LTC would store it's files in ~/.electrum-ltc. Does that directory exist?

**Comment by nikitavoloboev** [comment]
> Does that directory exist?

It does. 

> What is in default_wallet if you open it with a text editor?

I removed it, it was created by default for some reason.

Everything is working now I believe. Thank you for the help.

**Comment by SomberNight** [comment]
> it was created by default

Uhum.... well not by us.

**Comment by nikitavoloboev** [comment]
> Uhum.... well not by us.

It was my bad. I believe I installed electrum a long time ago and made the wallet but deleted the app after. The wallet stayed however. It was empty and unused though.
