### ISSUE TITLE
Android build issue: Path for p4a.source_dir does not exist

### ISSUE THREAD

**Issue by Devilmoon** [spesmilo/electrum#4066]
See attached picture:
<img width="433" alt="capture" src="https://user-images.githubusercontent.com/18517304/37090024-03111874-2203-11e8-8dd9-6a064c0e149c.PNG">

**Comment by ecdsa** [comment]
see the Readme.md

**Comment by HyperionPolis** [comment]
And what did you did? I'm having the same problem and the readme only says 

```
make theming
make apk
```
