### ISSUE TITLE
3.1.0 Wallet creation freeze with TREZOR Model T

### ISSUE THREAD

**Issue by Saicere** [spesmilo/electrum#4067]
According to the 3.1.0 patch notes, the TREZOR Model T is now supported. However, when creating a new wallet with my initialized and unlocked TREZOR Model T connected, Electrum 3.1.0 will freeze on the "Please wait..." screen after selecting "Use a hardware device". I left it on this screen for a few minutes, with no change.

Disconnecting the Model T makes Electrum unfreeze and present the "No hardware device detected" screen. Sometimes it will also pop up a "LIBUSB_ERROR_IO [-1]" error message.

This was tested on Windows 10 64-bit Version 1709. The standard troubleshooting steps (i.e. rebooting, removing the device) were all attempted. I tested 3.1.0 with my TREZOR One as well, and that one seems to work just fine. The TREZOR web wallet also works as expected with the Model T.

Note that I have previously encountered a USB compatibility issue with the Model T which was resolved with a bootloader update, so it is of course possible that Electrum does everything right here, and that the most recent bootloader/firmware still has some issues that cause this behavior.

**Comment by SomberNight** [comment]
See https://github.com/spesmilo/electrum/issues/4031

Unfortunately I had only tested Electrum 3.1.0 with an emulator for Trezor T, and it seems there is a difference in behaviour between the emulator and the real device. The real device does not work with the 3.1.0 binaries; technically it DOES work with 3.1.0 but it needs a newer version of python-trezor than what is packaged in the binaries. The next minor version will fix this. Sorry.
