### ISSUE TITLE
same wallet can be opened multiple times via InstallWizard

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4073]
![duplicate_wallets](https://user-images.githubusercontent.com/29142493/37132429-fd3054ac-228d-11e8-9bb7-a717b8991a14.PNG)

In Qt GUI, open wallet file, `File`>`New/Restore`.
The same wallet file can be opened multiple times simultaneously.

**Comment by Lastrellik** [comment]
I almost have a fix for this, in case anybody else was wanting to get started :)
