### ISSUE TITLE
TREZOR T - Electrum hangs

### ISSUE THREAD

**Issue by BitCryptex** [spesmilo/electrum#4095]
Electrum version - 3.1.0, Windows 10

Standard wallet -> Use a hardware device

After having TREZOR T plugged in and doing the thing described above, Electrum hangs for a couple of minutes. After that, information about no hardware wallet detected appears.

TREZOR beta wallet works fine. [Trezor-agent](https://github.com/romanz/trezor-agent/issues/215) also have problem with communication.

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/4067#issuecomment-371139774
