### ISSUE TITLE
I cannot see my coins any longer in my wallet

### ISSUE THREAD

**Issue by Tozz1958** [spesmilo/electrum#4106]
I restarted my computer and now my balance went from 15.99 BTCP to 0 !!!!!!!!!!!!!

Please help, I haven't sent or attempted to send any coins anywhere and I have my private wallet seed written down.

Thank You
Terry

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here https://github.com/BTCPrivate/electrum-btcp
