### ISSUE TITLE
Electrum 3.1.0 portable Win10 - error in console when entering command... electrum help

### ISSUE THREAD

**Issue by Hapmman** [spesmilo/electrum#4112]
**electrum help**
Traceback (most recent call last):
             ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\electrum-3.1.0-py3.5.egg\electrum_gui\qt\console.py", line 223, in runCommand
  File "<string>", line 1
    ctrum help
             ^
SyntaxError: invalid syntax
>> 
---------------------------------------------------------------------
All command-line commands produce a similar error, only the
  teams for  Phyton.

**Comment by SomberNight** [comment]
The in-app console is essentially a python interpreter.
`electrum help` is not valid python syntax.
`electrum help` is what you would write in terminal to use the CLI of electrum.

**Comment by Hapmman** [comment]
Sorry, then remove from the description of the program console commands that do not work, and I like a fool all by your description and can't understand why the program gives error. You do read your manual to the program, and then you will understand that here you are wrong!

**Comment by SomberNight** [comment]
This is the doc for the console that you are trying to use: http://docs.electrum.org/en/latest/console.html
This is the doc for the command line which is a separate thing: http://docs.electrum.org/en/latest/cmdline.html
