### ISSUE TITLE
Writing pin for Trezor device causes "String overflow" error.

### ISSUE THREAD

**Issue by alexrecuenco** [spesmilo/electrum#4122]
OS: macOS High Sierra 10.13
Electrum version: 3.1.1

I simply clicked `New File`, then chose "`standard wallet`", then "`Use a hardware device`".

It recognized my trezor device as `[trezor, initialized]` and propped up the pin window. After introducing a pin of ** >9 digits** and confirming, it displayed the error. 

After that, the trezor kept the 9 pin window opened. Therefore, trying to repeat the process just causes a "Unkown message error" without showing again the pin window.

The only way I have found to "unstuck" the trezor device, is to simply remove it and plug it back in. But I am unable to use it with electrum.

**Comment by SomberNight** [comment]
Confirmed. Note that this is actually a limitation enforced by Trezor: https://doc.satoshilabs.com/trezor-faq/threats.html#brute-forcing-the-trezor-pin

All we can do is check the length on our side too.

**Comment by SomberNight** [comment]
Can you please clarify

> But I am unable to use it with electrum.

**Comment by alexrecuenco** [comment]
Errr... no. this is not a limitation on the trezor side. This is clearly something related to electrum handling the pin incorrectly.

Trezor  does allow pins to bey >9 digits longs. In fact, I have used it myself without issue on `http://wallet.trezor.io/`.

The fact that it locks is irrelevant. The issue is the "StringOverflow", read the title :)

**Comment by alexrecuenco** [comment]
In any case, if that is intentional. An "String Overflow" error is certainly not intentional.

**Comment by SomberNight** [comment]
An example trace when trying to change the PIN of a Trezor One (python-trezor 0.9.1):
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/util.py", line 639, in run
    result = task.task()
  File "/home/user/wspace/electrum/plugins/trezor/qt_generic.py", line 314, in task
    getattr(client, method)(*args, **kw_args)
  File "/home/user/wspace/electrum/plugins/trezor/clientbase.py", line 188, in set_pin
    self.change_pin(remove)
  File "/home/user/wspace/electrum/plugins/trezor/clientbase.py", line 226, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 162, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 681, in change_pin
    ret = self.call(proto.ChangePin(remove=remove))
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 238, in call
    resp = self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 238, in call
    resp = self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 235, in call
    msg = handler(resp)
  File "/home/user/wspace/electrum/plugins/trezor/clientbase.py", line 35, in callback_Failure
    raise RuntimeError(msg.message)
RuntimeError: string overflow
``` 
The "overflow" is more likely to be in the Trezor code.. We just display the message they send us back, which is "string overflow".

**Comment by SomberNight** [comment]
I've tried on https://wallet.trezor.io/ but I could not set a PIN longer than 9 characters.

**Comment by SomberNight** [comment]
This blog post re Trezor T from a couple days ago also mentions a 9 char maximum:
https://blog.trezor.io/getting-started-with-trezor-model-t-a8db9096a7a6

> The next step is to create a PIN, which protects your TREZOR from unauthorized access. Use at least four different numbers. Try to avoid simple PINs like ‘1234’ or your date of birth. The maximum PIN length is nine digits long.

**Comment by ligi** [comment]
@alexrecuenco wonder how you could ever enter more than 9 digits - I just tried to enter the maximum digits on the old and model T - both enforce a maximum of 9 digits. The same for the web-app as well as the android manager

**Comment by alexrecuenco** [comment]
Alright, I re-checked and I see what was happening:

1. First, sorry for the inconvenience.
2. The `trezor.wallet.io` was truncating my password to only 9 digits before passing it to my device. (And not providing any warnings) whenever I was just using their UI directly. The MyEtherWallet website has the same behavior

Could we provide the same behavior as well? If the pin is longer than 9 digits, start ignoring digits entered after the 9th digit? It might be useless and only making the code more convoluted.
