### ISSUE TITLE
Forced installation of optional modules with default options

### ISSUE THREAD

**Issue by xsmile** [spesmilo/electrum#4136]
Electrum Version: 3.1.1

Since f38ca73dae307441e2a90dbf23bff184e8a99b39 optional Python modules are forcefully installed with pip ignoring all options passed to setuptools when running `python3 setup.py install [...]`'

Instead, `extras_require` can/should be used to define features and their dependent modules.

**Comment by mocmocamoc** [comment]
I've run into this too, looks like it was intentionally moved out of 
extras_require: https://github.com/spesmilo/electrum/commit/f38ca73dae307441e2a90dbf23bff184e8a99b39

**Comment by bauerj** [comment]
This is indeed unexpected.

The idea behind it was that most users want those packages but Electrum works without them.

But it looks like [PEP20](https://www.python.org/dev/peps/pep-0020/) is right again:

> Explicit is better than implicit.

**Comment by xsmile** [comment]
@bauerj As I see it the packages can be either part of `install_requires` or `extras_require`.
Personally I'm fine with both options as the setuptools installation routine is not be bypassed.

Strictly speaking the packages do not belong to `install_requires` but since the majority of users requires them, it should solve the issue.

**Comment by SomberNight** [comment]
The problem with `install_requires` is that these packages are not **required** for Electrum to function. 

E.g. pycryptodomex is a huge performance improvement for encryption if present, but we fall back to pyaes if it isn't. The idea was to always try to install the optional packages but separately of the core packages, so that they can fail but the install would still succeed.

**Comment by bauerj** [comment]
We could define an extra `full` that includes the hw packages and everything we recommend (e.g. `pycryptodome`).

Then we can instruct people to install it using `pip3 install https://download.electrum.org/3.1.1/Electrum-3.1.1.tar.gz[full]` on the download page or using `pip3 install https://download.electrum.org/3.1.1/Electrum-3.1.1.tar.gz` if they want a more minimal approach.

**Comment by xsmile** [comment]
@bauerj That sounds good and should solve both the requirement for all packages and this issue.
