### ISSUE TITLE
Clearer explaination of the coin selection (privacy) option

### ISSUE THREAD

**Issue by bernardpeh** [spesmilo/electrum#4140]
I do not know of anyone who can understand this sentence:

"Attempts to better preserve user privacy.  First, if any coin is spent from a user address, all coins are.  Compared to spending from other addresses to make up an amount, this reduces information leakage about sender holdings.  It also helps to reduce blockchain UTXO bloat, and reduce future privacy loss that would come from reusing that address' remaining UTXOs.  Second, it penalizes change that is quite different to the sent amount. Third, it penalizes change that is too big."

can this be explained in a more concised way using better english?

**Comment by bauerj** [comment]
Why did you close this issue?

**Comment by ecdsa** [comment]
@bauerj coin selection is no longer an option
