### ISSUE TITLE
electrum cost me 0.002 btc fee

### ISSUE THREAD

**Issue by cc20101001** [spesmilo/electrum#4141]
can you tell me why? thanks
[https://www.blocktrail.com/BTC/tx/8b995ceb37be18682b60ad286e1b53c5b69f8f47338dcbd1653d0013ac12a4ab](https://www.blocktrail.com/BTC/tx/8b995ceb37be18682b60ad286e1b53c5b69f8f47338dcbd1653d0013ac12a4ab)

 electrum: 3.0.6
within 25 blocks
2.0 sat/byte

**Comment by SuBPaR42** [comment]
Look closer at the link and you will see it cost you far less than 0.002 BTC


Fee:  0.00007444 BTC
Fee / KB:  0.00002056 BTC (i.e., the 2 sat/byte you said you used)

**The 0.002 BTC went to a change address in your wallet I presume.**

**Comment by cc20101001** [comment]
123nvkGnqQNWMc2vkEkzdg11t9NnPFAEc7 is not the address of mine 

![4041521306843_ pic](https://user-images.githubusercontent.com/9129999/37558744-b87d2682-2a53-11e8-935e-03240dddcf2c.jpg)
![image](https://user-images.githubusercontent.com/9129999/37558746-be58dd94-2a53-11e8-822a-f371c2784e2b.png)

any problem?

**Comment by bauerj** [comment]
> can you tell me why?

Yes:
TrustedCoin charges a small fee to co-sign transactions. The fee depends on how many prepaid transactions you buy. An extra output is added to your transaction every time you run out of prepaid transactions.

In this case you bought 20 additional transactions of which you have 16 left.

While creating the wallet you have been informed about the fees.

**Comment by SomberNight** [comment]
As said already, there is an additional fee besides miner fees for transactions using a 2FA wallet. There was a disclaimer about this during wallet creation:
![2fa_disclaimer](https://user-images.githubusercontent.com/29142493/37559800-565aa0c8-2a2c-11e8-9f9c-f11645ee5456.png)

If you go to the [URL in your picture](https://api.trustedcoin.com/#/electrum-help), it is explained there  in even more detail.
