### ISSUE TITLE
No bitcoin payments reaching wallet

### ISSUE THREAD

**Issue by stugzoid** [spesmilo/electrum#4147]
I do not appear to have any transactions recorded to my wallet since December 2017, yet Genesis Mining reports sending mined mBTc up until March 18th. Can you tell me what is going wrong?

**Comment by SomberNight** [comment]
Sorry but it's hard to help without any details.

Make sure you are using the latest version of Electrum;
and that you are connected to a server and synced (green or blue orb in bottom right corner of GUI).
Are the transactions showing up on blockchain explorers btw?

**Comment by stugzoid** [comment]
Hi there

 

I checked again and the green orb is lit and I have updated the software but still NO transactions received since December.

**Comment by SomberNight** [comment]
Well the simplest explanation is that the wallet did not receive any transactions then. Either
- you are looking at the wrong wallet
- your counterparty is lying about having sent transactions

Do you have the transaction IDs/addresses of where you allegedly received the funds?

**Comment by stugzoid** [comment]
I get the funds from Genesis Mining; there are no transaction references but every mined element is listed up to 15th March.

**Comment by AbdussamadA** [comment]
>Do you have the transaction IDs/addresses of where you allegedly received the funds?

Can you answer this question that @SomberNight posted? Did you lookup the receiving address on a block explorer like blockchain.info to see if you actually received anything or not?

**Comment by stugzoid** [comment]
Don’t worry. I got an answer. thanks

**Comment by bauerj** [comment]
Does that mean your problem is solved?
