### ISSUE TITLE
Bitcoin Transaction  Bug

### ISSUE THREAD

**Issue by Hackore55** [spesmilo/electrum#4150]
I Have send transaction to my friends.. i have Receive error.. I have resend again the same transaction.. But the wallet have send 2x the transaction and my friends have receive just 1 of this 2 transaction .. Sorry my english not good.

The Transaction

https://blockchain.info/tx/e9605c473b33354102a30e7128e101dd82e77e128f33137b2d8bce135494a362

https://blockchain.info/tx/f1104c4e801b4612ecf98b39bb1c27b764c824d69ffb360baec04662f6c55ba6

**Comment by SomberNight** [comment]
Is this the intended destination address? 1NB6p4bP3T5HE92jLEyj5GZ5xxW2wX799a
If so, as you can see on the block explorer too, that address did receive both transactions.

**Comment by Hackore55** [comment]
No my friends have just receive 1 one this transaction... I send more information tomorow.. My Friends have send report to ur Wallet Provider.

**Comment by SomberNight** [comment]
What wallet software does your friend use? The problem is on their end.

**Comment by Hackore55** [comment]
Me i Use Electrum.. My Friends Use http://Bitcoin.com

**Comment by bauerj** [comment]
The transactions look correct. If your friend received the first transaction they should have received the second too.

Please tell him to get in contact with Bitcoin.com support and show them the links you posted above.

**Comment by SomberNight** [comment]
There is no bug here; the issue is not with Electrum.
