### ISSUE TITLE
Electrum 3.1.1 fails to connect to a Trezor T on Fedora 27

### ISSUE THREAD

**Issue by eliasnaur** [spesmilo/electrum#4155]
I upgraded to Electrum 3.1.1 since that was supposed to fix connectivity issues with the new Trezor T. However, on my Fedora 27, Electrum still fails to connect to the T (on the wallet setup page, the one asking me to try again by pressing next).

I've tried to kill trezord (the Trezor Bridge) before connecting with Electrum; I've tried to install the trezor-udev rules rpm.

The device is unlocked before trying to connect and it works fine with the trezor.io wallet.

Is there anything else I can try? I didn't find any interesting logs (/var/log/trezord.log is empty on my system)? Running "electrum -v" only gives me "error trezor" whenever I click the "Next" button to retry.

**Comment by SomberNight** [comment]
Might be similar to https://github.com/spesmilo/electrum/issues/4082#issuecomment-373374233 ... as in, maybe libusb related?

What does `python3 -m pip show trezor` output?
I would try installing the Fedora alternatives of the packages here: https://github.com/trezor/python-trezor#install, notably `libusb-1.0-0-dev libudev-dev`

**Comment by eliasnaur** [comment]
Aha, thank you. The missing packages were libusb-devel and libudev-devel (their Fedora names, anyway). The connection to the Trezor T seems to work now.
