### ISSUE TITLE
Hardware device name connection dialog box

### ISSUE THREAD

**Issue by charlespax** [spesmilo/electrum#4164]
I have an Electrum (commit cd19f788ccedd7ac050141cdd15c9905011c951e) 2of4 multisig wallet using three Trezor devices: 'My name is Amy', 'My name is Bill', 'My name is Carlo' with password 1, and 'My name is Carlo' with password 2.

When signing a transaction Electrum asks me to connect a Trezor device, but does not specify which one. It would be good to remove the ambiguity. I tested my wallet by signing with 'Amy' and 'Bill', which worked, but things would not work when using a Trezor with a password. I spent several hours on this before I discovered that Electrum was requesting the devices in a specific order. Because the dialog indicated only, "TREZOR", I assumed any Trezor would do.

Anway, here is the normal dialog box:
![screenshot from 2018-03-22 16-02-31](https://user-images.githubusercontent.com/281642/37795290-7420f532-2dea-11e8-929b-20078befb5d1.png)

I dug into the code a bit to give an example of the expected behavior. Here is what I feel the dialog box should look like:
![screenshot from 2018-03-22 16-03-06](https://user-images.githubusercontent.com/281642/37795339-91fcdc4c-2dea-11e8-9747-31f9c716afb7.png)

In `lib/plugins.py` line 485 change this:
```
            msg = _('Please insert your {}.  Verify the cable is '
                    'connected and that no other application is using it.\n\n'
                    'Try to connect again?').format(plugin.device)
```
to this:
```
            msg = _('Please insert your {} \'{}\'.  Verify the cable is '
                    'connected and that no other application is using it.\n\n'
                    'Try to connect again?').format(plugin.device, keystore.label)
```

I have not tested with any other devices and I am not familiar with Electrum code, so I am not submitting a pull request.

**Comment by charlespax** [comment]
Notes:
- If the device does not have a name in the Electrum wallet file, the original behavior should be used.
- A higher level fix would be for Electrum to sign a transaction with whichever device is plugged in. I assume there is a way to compare the device's xpub (ypub, etc.) with what is in the wallet file.

**Comment by SomberNight** [comment]
The code is cycling through the signers in the original order used during wallet creation. When asked `Try to connect again?`, you can simply say `No`, and it will skip that signer and ask for the next one.

Yes, we should make it easier to distinguish same-type hw wallets, e.g. via labels; though note that only Trezors have labels
