### ISSUE TITLE
Electrum does not work with ledger bitcoin v1.2.4 app

### ISSUE THREAD

**Issue by ken2812221** [spesmilo/electrum#4167]
![image](https://user-images.githubusercontent.com/11154118/37832053-73e18c50-2ee2-11e8-86a6-fa12a49806f0.png)
Electrum does not work with ledger bitcoin v1.2.4 app

**Comment by bauerj** [comment]
Hey,

this should (hopefully) be fixed with cd19f788ccedd7ac050141cdd15c9905011c951e in the next release.

**Comment by ken2812221** [comment]
thanks, I will try it

**Comment by ken2812221** [comment]
it works for me with latest commit

**Comment by bauerj** [comment]
Thanks for testing!
