### ISSUE TITLE
Windows defender alerts about Trojan 3.1.1

### ISSUE THREAD

**Issue by alete89** [spesmilo/electrum#4172]
Hey, everybody. Is it known that Windows 10 default AV Defender blocks electrum-3.1.1.exe standalone from https://download.electrum.org/3.1.1/electrum-3.1.1.exe claiming that it contains Trojan:Win32/Fuerboos.C!cl ?

**Comment by alete89** [comment]
same with https://download.electrum.org/3.1.1/electrum-3.1.1-portable.exe 
-setup downloads fine, but I'm afraid to use it .

**Comment by SomberNight** [comment]
Yes, this is known. See https://github.com/spesmilo/electrum/issues/3198
You should [check the GPG signatures](https://www.reddit.com/r/Bitcoin/comments/7flvfy/important_for_bitcoin_users_how_to_verify_pgp/)
