### ISSUE TITLE
Replaceable 

### ISSUE THREAD

**Issue by Gummybear1221221** [spesmilo/electrum#4179]
I went to transfer bitcoin into the electrum wallet, and it showed up but it showed up saying "Replaceable" and i lost the bitcoin.

**Comment by SomberNight** [comment]
Please update to the latest released version.

What makes you think you "lost the bitcoin"?

**Comment by Gummybear1221221** [comment]
Just update the application? And it shows up “Replaceable” with a balance
of 0 on the other side

**Comment by SomberNight** [comment]
"Replaceable" means the transaction uses opt-in RBF and hence can be changed while it is not confirmed. You should only consider a payment received after it is confirmed (with possibly several confirmations).

What do you mean by "balance of 0 on the other side"?

**Comment by SomberNight** [comment]
Anyway, this issue tracker is not for user support, but for development.
Please use [BitcoinTalk](https://bitcointalk.org/index.php?board=98.0) or [Reddit](https://www.reddit.com/r/Electrum/), or perhaps [IRC](https://webchat.freenode.net/?channels=electrum) instead.
