### ISSUE TITLE
Very slow processing many transactions

### ISSUE THREAD

**Issue by alexandrz** [spesmilo/electrum#4183]
Opening a big wallet containing many transactions, as well as doing any action like switching tabs, opening transaction preview, closing it, changing transaction amount etc freezes Electrum for several minutes. It now takes about 10 minutes to open a wallet, create a transaction and broadcast it. It was fast before.

Electrum 3.0.5, MacOS

**Comment by bauerj** [comment]
Can you be a bit more specific about the number of transactions?

**Comment by AbdussamadA** [comment]
Upgrade to 3.1 There have been performance improvements since 3.0.5

**Comment by alexandrz** [comment]
How can I get the number of transaction using console? I only know how to get the number of addresses which is about 6000.

**Comment by alexandrz** [comment]
@AbdussamadA I've made a mistake, I am already using 3.1.1.

**Comment by alexandrz** [comment]
@AbdussamadA Thank you, it's faster now. It still takes some time to open the wallet though, and it slower than it used to be. I downloaded 3.1.1 two weeks ago, and forget to install.

**Comment by AbdussamadA** [comment]
You can create a new wallet via file > new/restore and move your coins there. Then once that transaction has confirmed perhaps you can share your old wallet with the developers so that they can look at optimizing Electrum for large wallets? I know @SomberNight was looking for a large wallet. I think even a watch only wallet will suffice.

**Comment by alexandrz** [comment]
@AbdussamadA I can share a master public key to some developers. @SomberNight are you interested?

**Comment by SomberNight** [comment]
Yes I am. An xpub would be welcome. See email in my github profile.
