### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by vasinkd** [spesmilo/electrum#4184]
I can't start daemon with Electrum v. 3.1.0. on Ubuntu 16.04.

>  File "wmscrypto/py_scripts/electrum/electrum", line 406, in <module>
>     d = daemon.Daemon(config, fd, False)
>  File "/home/rizor/wmscrypto/py_scripts/electrum/lib/daemon.py", line 126, in __init__
>     self.network = Network(config)
>  File "/home/rizor/wmscrypto/py_scripts/electrum/lib/network.py", line 169, in __init__
 >    self.blockchains = blockchain.read_blockchains(self.config)
>   File "/home/rizor/wmscrypto/py_scripts/electrum/lib/blockchain.py", line 75, in read_blockchains
>     if b.parent().can_connect(h, check_height=False):
>   File "/home/rizor/wmscrypto/py_scripts/electrum/lib/blockchain.py", line 314, in can_connect
>     height = header['block_height']
> TypeError: 'NoneType' object is not subscriptable 

I can see some list of forks: ['fork_0_502753', 'fork_0_499002', 'fork_0_515256', 'fork_0_508270', 'fork_0_508717', 'fork_0_502052', 'fork_0_497871', 'fork_0_503646', 'fork_0_499403', 'fork_0_503949', 'fork_0_500568', 'fork_0_498984']

and 'fork_0_515256' returns header None.

I wrapped this lines in blockchain.py with try-except statement in read_blockchains:

> if b.parent().can_connect(h, check_height=False):
> blockchains[b.checkpoint] = b
> else:
> util.print_error("cannot connect", filename)
 
and now everything is Ok. But I still worry that I could break something important

**Comment by SomberNight** [comment]
could you zip and upload the "forks" folder and the "blockchain_headers" file from the datadir?

**Comment by vasinkd** [comment]
[myforks.zip](https://github.com/spesmilo/electrum/files/1851695/myforks.zip)

**Comment by vasinkd** [comment]
Should I delete this empty text file?

**Comment by SomberNight** [comment]
Thanks.

> Should I delete this empty text file?

Yes, go ahead; it should no longer crash then.
