### ISSUE TITLE
Wallet stuck "synchronizing"

### ISSUE THREAD

**Issue by fakesmd** [spesmilo/electrum#4190]
I sent my bitcoin from coinbase to one of the addresses in my bitcoin wallet. The first transaction went through without issues. However, I sent another payment to the same address and it never appeared. I clicked the "sync" button at the bottom right and now it is stuck on "synchronizing..." and the money never appeared. Also, the addresses no longer appear under the tab and I have tried restarting it multiple times. Any help would be great.

**Comment by SomberNight** [comment]
What version of Electrum is this with?
Please try with the latest.

**Comment by fakesmd** [comment]
It worked! Thanks for the help, much appreciated.
