### ISSUE TITLE
Ledger Nano S - Invalid Sequence

### ISSUE THREAD

**Issue by skywills** [spesmilo/electrum#4191]
After i upgrade my ledger Nano S latest firmware 1.4, when setting up hardware device on electrum it showing up two _an unnamed ledger_, when i select either one will show up 

> Exception: Invalid Sequence

after this the setup dialog closed.

![capturex](https://user-images.githubusercontent.com/6055148/38009537-55dc4fb2-3287-11e8-8c96-a043b2af20b4.PNG)
![capturexy](https://user-images.githubusercontent.com/6055148/38009538-5605405c-3287-11e8-9934-39c933b11c48.PNG)
![capturexyz](https://user-images.githubusercontent.com/6055148/38009539-562e4a7e-3287-11e8-96c8-7e5301d66288.PNG)

I m using Electrum 3.1.1, Ledger Nano S SE 1.4.1, MCU 1.5, bitcoin app 1.2.4

**Comment by SomberNight** [comment]
should be already fixed on master by https://github.com/spesmilo/electrum/commit/cd19f788ccedd7ac050141cdd15c9905011c951e
