### ISSUE TITLE
Add option to "rmrequest" to delete and not re-use the address

### ISSUE THREAD

**Issue by robo2bobo** [spesmilo/electrum#4192]
In regular financial transactions, we come upon various payments that need to be cancelled, thus we use "rmrequest" to do so. This causes the address to be re-used and placed back into the pile of free addresses.

This is a problem, because we need to completely delete that address or keep it out of the free address list, so it is never re-used again.

It is vitally important for tax validation of cancelled payments, the address must not be re-used by another entity and/or payment and must be unique to that cancelled/failed payment.

Currently, I found no way to delete these re-used addresses. Thus, I would like to ask for a new option to be added to the "rmrequest" command, that would force Electrum to discard and not re-use the address of the removed payment.

Thank you.

As a similar but separate issue, I found the following problem. Once a payment is removed with "rmrequest", the address goes back to the free address list to be re-used again. The next payment that comes along and grabs that address will use it for its own payment. Effectively, commands like "getrequest" will show the most recent payment request, while in fact the same address was correct a while ago for a different "getrequest".

While it may seem like something irrelevant or insignificant (the first payment request was cancelled after all) and that may seem correct at first glance, but from a database perspective this is very wrong, two equal "getrequest" commands (same address) will give different results, just because they where used at different intervals. It would be more reasonable to use the "id" of the request instead of a re-usable address, or make "rmrequest" to delete the address instead of placing it in the free address list.

**Comment by SomberNight** [comment]
(as said on IRC)

A possible workaround is not deleting the payment request at all.

We could potentially introduce an analogue to the `freeze` functionality. `freeze` makes the wallet not use an address to send from. The new function (say `freeze-receive`, not sure about name) could make the wallet not use an address to receive to (consider it used even if it isn't).
You could then `freeze-receive` the address of the payment-request before calling `rmrequest`.

**Comment by robo2bobo** [comment]
An alternative, you could have a "cancelrequest" command, which would mark requests as cancelled and would not re-use the address. Thus, there is a historical record of the request and its also marked properly as Cancelled.
