### ISSUE TITLE
Change libusb version to 1.0.22

### ISSUE THREAD

**Issue by mocmocamoc** [spesmilo/electrum#4196]
On Windows, libusb 1.0.21 has a bug that causes Trezor T devices to be enumerated twice, although only one of the devices can actually be used. The other one gives "LIBUSB_ERROR_NOT_SUPPORTED" errors when trying to use it. See:
https://github.com/trezor/trezor-core/issues/165
https://github.com/trezor/python-trezor/issues/223

libusb 1.0.22 has recently been released and fixes this bug, please update the Windows build to use this version.

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/commit/9a12022537cb8e67dc38180ce4282f29089cf5b4

**Comment by SomberNight** [comment]
Thank you. You made me figure out why I could not reproduce the build. See https://github.com/spesmilo/electrum/issues/4276
This will have to wait again, until the next release, sorry.
