### ISSUE TITLE
Electrum address changed/disappeared

### ISSUE THREAD

**Issue by lllaaammmaaa** [spesmilo/electrum#4205]
Hello,

I cut and pasted an electrum address and sent bitcoins to it.  The address does not show up in my Electrum addresses now.  I even tried Console and "ismine" and it came out "false".  How do I get the bitcoins I sent?

**Comment by SomberNight** [comment]
You might have been a victim of malware. E.g. some other program could have changed the clipboard.
Where have you downloaded Electrum from? (get exact link from browser history)

**Comment by AbdussamadA** [comment]
Try the things mentioned in [this comment](https://www.reddit.com/r/Electrum/comments/8758bn/bitcoin_not_come_through_to_electrum_even_though/dwcw109/) and [this one](https://www.reddit.com/r/Electrum/comments/8758bn/bitcoin_not_come_through_to_electrum_even_though/dwh32zl/)

**Comment by lllaaammmaaa** [comment]
I was sending between two wallets on my phone, so I downloaded from the Play store. I tried the change gap limit, I will try the other.
