### ISSUE TITLE
Bitcoin Stuck on Watching-Only Electrum! How to Send/Use it again?

### ISSUE THREAD

**Issue by judepark** [spesmilo/electrum#4206]
Hello,

I purchased $100 worth of Bitcoin on Coinbase, moved it to cold storage in Armory, and moved that to Electrum. 

It seems like the transaction worked and in my Electrum the wallet has a balance. However it is "imported, watching only". And I can't send (under send tab the option to "send" does not even appear).

I do have my "seed" or "passphrases" from Armory saved in my person. I have tried to create a new wallet by "already have a seed" method, but it seems like Electrum does not support passphrases from Armory. (Electrum's seeds have 12 words, while passphrases in armory only has 6 words, no space.)

Any help?

**Comment by bauerj** [comment]
So you didn't actually send the funds from Armory to Electrum but imported the xpub from Armory?

In this case you should still be able to send the coins from your Armory wallet.

To properly transfer your funds to Electrum, create a new wallet and send the coins to one of your wallet addresses.

**Comment by judepark** [comment]
I did send the funds from Armory to Electrum, I can see the new balance on my watch-only Electrum wallet.

I no longer have the Armory wallet (deleted). I just want to access my bitcoin in y account.
