### ISSUE TITLE
Armory to Electrum bitcoin money stuck on Watch-Only, Help!

### ISSUE THREAD

**Issue by judepark** [spesmilo/electrum#4207]
I have a watch-only wallet on Electrum, and I cannot seem to access the bitcoin inside it (eg. send it)

The bitcoin was transferred from my Armory cold storage, I followed this method to send it from Armory to Electrum:

----------
In Armory:

Select "Wallet Properties".
Select "Backup This Wallet".
Select "See Other Backup Options".
Select "Export Key List".
Select "Omit spaces in key data".
The important string is the PrivBase58 for every bitcoin address. It is the private key of this address encoded in base58 (encoded not encrypted), which is the (only?) format Electrum accepts when importing.

In Electrum:

Select File → New Wallet
Enter the private keys you took from armory into the textbox
---------

The bitcoin was transferred into Electrum, I see it with amount on my Electrum wallet, but it is stuck in Watch-Only, and I cannot seem to access my account. Can anyone help?

(BTW, I already tried to create a new wallet on Electrum with seed entry but it seems like Armory's passphrases (6 words) are not supported by Electrum seed entry (12 words). It did not work.)

**Comment by ecdsa** [comment]
you already opened an issue about that.

**Comment by bauerj** [comment]
Hey,

it appears like you imported the public keys into Electrum. This means you will not be able to spend from Electrum until you imported your private keys, or, preferably, send your coins to Electrum through a Bitcoin transaction.
