### ISSUE TITLE
Not showing balance after Windows 10 Reset

### ISSUE THREAD

**Issue by lucellent** [spesmilo/electrum#4235]
I recently reset (reinstalled/refreshed) my PC without deleting my files but Electrum got uninstalled. When I reinstalled it, I created a new wallet, used my previous seed so I could use the same wallet again. There, before the reset, I had about 5$ worth of LTC. After the reset, it shows that my balance is zero. I'm using the latest version.

**Comment by SomberNight** [comment]
So you restored from seed words and it is not finding your transactions? Are you sure the seed is for the correct wallet?

Anyway, Electrum is for bitcoin, try asking in the litecoin repo; but they will need more details too :)
