### ISSUE TITLE
Installation error on ubuntu 17.10

### ISSUE THREAD

**Issue by Gy0m** [spesmilo/electrum#4239]
Just downloaded the last release of electrum. Followed the doc installed `sudo apt-get install python3-pyqt5` then `sudo apt-get install python3-setuptools` .
rytime the same error
I'm not sure about the `pip3 install .[full]` i tried many ways but have everytime the same error : 

> The directory '/home/gy0m/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/gy0m/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement 'Electrum-3.1.2.tar.gz' looks like a filename, but the file does not exist

and many exeptions : 

> Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 620, in unpack_file
    tarfile.is_tarfile(filename) or
  File "/usr/lib/python3.6/tarfile.py", line 2447, in is_tarfile
    t = open(name)
  File "/usr/lib/python3.6/tarfile.py", line 1568, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1633, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/gy0m/Electrum-3.1.2.tar.gz'

if someone knows what's going on ?

**Comment by SomberNight** [comment]
Maybe the readme is not clear..
https://github.com/spesmilo/electrum/blob/facf833bac60d00d745c0bafc0ee4a08d2ba1fb9/README.rst#getting-started

That part is meant to be read as:
> If you downloaded the official package (tar.gz), you can run Electrum from its root directory, ...
> You can also install Electrum on your system, by running this command:

so you need to be in the project's root folder when running `pip3 install .[full]`.

-----

If you simply want to install the latest release I suggest following the instructions on https://electrum.org/#download :

> Install dependencies:
`sudo apt-get install python3-setuptools python3-pyqt5 python3-pip`
Install Electrum:
`sudo pip3 install https://download.electrum.org/3.1.2/Electrum-3.1.2.tar.gz[full]`

**Comment by Gy0m** [comment]
Sorry i had no spript enabled on the web site so i couldn't see this command : 
`sudo python3 setup.py install` that is not in the github repo doc

I could finally install the last vertion of electrum

I close the report
