### ISSUE TITLE
synchronization

### ISSUE THREAD

**Issue by bo761** [spesmilo/electrum#4243]
4 twenty-four hours synchronization goes. Does not see сгенирированых addresses. Does not see the transaction of потвержденные вlockchain.
4 days is synchronized. does not see SGENIRIROVANYH addresses. does not see the potverzhdennye in the blockchain transaction.

**Comment by SomberNight** [comment]
Hi. Not sure I understand..
but in any case, what version of Electrum is this with? Please try with latest.

**Comment by bo761** [comment]
4 clock sync wallet. Does not see generated addresses. Does not see transactions confirmed in the blockchain. Version electrum - installed on Tails.

**Comment by bo761** [comment]
there are Russian-speaking support

**Comment by bo761** [comment]
where did

**Comment by bo761** [comment]
I updated my wallet. And now I don't see 0.71 bitcoins. how long is the synchronization. What the problem is. Even old transactions shows as unconfirmed.

**Comment by SomberNight** [comment]
Can you make a screenshot? Possibly obfuscating personal details if you want.

**Comment by bo761** [comment]
how to attach a screenshot

**Comment by bo761** [comment]
in General, he writes of the transaction have not been confirmed. And there is synchronization

**Comment by bo761** [comment]
/home/amnesia/Persistent/Tor Browser/Снимок экрана от 2018-04-09 14-09-29.png

**Comment by bo761** [comment]
screenshot you got

**Comment by bo761** [comment]
file:///home/amnesia/Persistent/Tor%20Browser/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202018-04-09%2014-09-29.png

**Comment by bo761** [comment]
![2018-04-09 14-09-29](https://user-images.githubusercontent.com/38181469/38504427-35f61828-3c04-11e8-8c5f-06a54c522d6f.png)

**Comment by bo761** [comment]
That me to do in this situation

**Comment by SomberNight** [comment]
update Tails

**Comment by bo761** [comment]
I have already updated but not to the latest version. Every time less and less bitcoins.

**Comment by bo761** [comment]
like anything it is technically possible to solve the problem through the server

**Comment by SomberNight** [comment]
Electrum 2.7.9 is really old at this point. There are almost countless bugs that have been fixed since that version. You will need to use a newer version of Electrum for it to work. The easiest way is to update Tails itself.

**Comment by bo761** [comment]
I'm afraid I'm gonna lose all my money.

**Comment by bo761** [comment]
my balance doesn't even show the real

**Comment by bo761** [comment]
I'm afraid my new update will mean 0 on my wallet

**Comment by SomberNight** [comment]
make sure you have a **backup of your seed words**; and then update Tails.
I really can't help you more.

**Comment by bo761** [comment]
the fact that the blockchain shows the receipt of money to the addresses of purses. But the wallet itself does not display the amount.

**Comment by SomberNight** [comment]
do not wait for synchronisation to finish. if it does not finish in a few minutes, it most likely never will.
update Tails.
