### ISSUE TITLE
synchronization

### ISSUE THREAD

**Issue by bo761** [spesmilo/electrum#4244]
I updated my wallet. And now I don't see 0.71 bitcoins. how long is the synchronization. What the problem is. Even old transactions shows as unconfirmed.

**Comment by SomberNight** [comment]
please don't open multiple issues for the same problem

**Comment by SomberNight** [comment]
(https://github.com/spesmilo/electrum/issues/4243)

**Comment by bo761** [comment]
you are conducting technical work in the problem.

**Comment by bo761** [comment]
ok

**Comment by bo761** [comment]
someone will answer.

**Comment by SomberNight** [comment]
I replied in the other thread; it's confusing that you made two...

> Can you make a screenshot? Possibly obfuscating personal details if you want.

**Comment by bo761** [comment]
Screenshot fails to attach.So the synchronization of the eternal will.

**Comment by bo761** [comment]
![2018-04-09 14-09-29](https://user-images.githubusercontent.com/38181469/38504335-f06090e0-3c03-11e8-8c6e-386d5b9ddaab.png)

**Comment by SomberNight** [comment]
2.7.9? that's really old.
Please install a newer version of Electrum inside Tails (not so easy); or just update Tails (it comes with newer Electrum than that now).
