### ISSUE TITLE
I fixed electrum for use with belcher's personal-electrum-server

### ISSUE THREAD

**Issue by bill-walker** [spesmilo/electrum#4251]
https://github.com/bill-walker/electrum/tree/3.1.2-personal

https://github.com/spesmilo/electrum/compare/3.1.2...bill-walker:3.1.2-personal

I disabled auto-connect in this branch, for all of the qt GUIs.

**Comment by bill-walker** [comment]
https://github.com/chris-belcher/electrum-personal-server/

here's his repo.

**Comment by bauerj** [comment]
Why don't you just use `--oneserver`?

**Comment by bill-walker** [comment]
--oneserver still lets noobs fuck it up

**Comment by bill-walker** [comment]
what I want to know, is do any bitcoin experts think my changes are safe. I'll keep using my changes going forward, in their own user folder. Ideally I'd like to not be the only maintainer of this.

**Comment by SomberNight** [comment]
`--oneserver` could only be set on the CLI, not in the config, but this was not intentional.
I've changed this in https://github.com/spesmilo/electrum/commit/1f937aa6cd85bb9297df90306afd29827c6b8109

Now you can use setconfig to set `server` and `oneserver`; you don't need to fork the whole repo...
So for example you can do:
```
./electrum setconfig oneserver true
./electrum setconfig server 127.0.0.1:50002:s
```

**Comment by SomberNight** [comment]
Your changes look okay btw, but there is really no point to fork the project just for this.

**Comment by bill-walker** [comment]
the whole reason why I forked it was to have a gui where the auto_connect button was disabled.

**Comment by bauerj** [comment]
Starting the client with `--oneserver`, lo and behold

![image](https://user-images.githubusercontent.com/598790/38646894-1819d5b4-3dea-11e8-8b1e-4565a77fa758.png)

**Comment by bill-walker** [comment]
there is still utility in having two versions of electrum with their own config files, one which connects to public servers, and one which does not.

after cloning the master branch, generating the icons, and setting the above config, it's still possible to click the button and connect to public servers.

**Comment by SomberNight** [comment]
@bauerj actually, to have all that disabled in the network dialog, you need to set `server` on the command line :/
https://github.com/spesmilo/electrum/blob/1935d7d1654b7b90f35167e342bcfc0732c69bce/gui/qt/network_dialog.py#L209

**Comment by bill-walker** [comment]
I expect you folks will do what you want in the end anyway. I'm not asking you to change anything.

Any advice on how to maintain my fork is welcome.

**Comment by SomberNight** [comment]
but I mean we could force `auto_connect` to be False if `oneserver` is set I guess, here
https://github.com/spesmilo/electrum/blob/1935d7d1654b7b90f35167e342bcfc0732c69bce/electrum#L375-L376

**Comment by bauerj** [comment]
@bill-walker You should be able to rebase your fork to newer versions of Electrum without much trouble.

**Comment by SomberNight** [comment]
can't you just create a shortcut that sets the command line arguments? :P

**Comment by bill-walker** [comment]
not sure if that question was for me. if so, no, i like having 2 instances of electrum, one which connects to public servers, and one which does not.

If --oneserver disabled auto_connect, i'd probably just fork the next version tag and only change the user folder, and put the cli switches in the readme.

**Comment by SomberNight** [comment]
As I said above, setting server on the CLI disables all the stuff @bauerj screen-capped.
There is also a CLI option for the datadir.
```
./electrum --server 127.0.0.1:50002:s --oneserver --dir /tmp/asd/
```
:)

**Comment by bill-walker** [comment]
cool. keep up the good work. closed.

**Comment by bill-walker** [comment]
would it be useful to display the data directory in the taskbar if a non-default directory is used?
