### ISSUE TITLE
Wrong version on MacOS Electrum 3.1.2

### ISSUE THREAD

**Issue by geomic** [spesmilo/electrum#4263]
The in-App version of Electrum (at least on MacOS) is reported wrong: Application header and About both state 3.1.1, where as the Finder Executable info shows the correct one, 3.1.2.

**Comment by bauerj** [comment]
Not sure what caused the issue. We will investigate this with the upcoming 3.1.3 release.

**Comment by SomberNight** [comment]
Thanks for the report. @ecdsa had looked into this
I am a bit fuzzy on the details but there was a configuration problem on the Mac where the official binaries are built and the binaries labelled as 3.1.2 were actually using the 3.1.1 codebase. This should now be resolved, and 3.1.3 should really "be" 3.1.3 :)
