### ISSUE TITLE
Bech32 addresses are NOT displayed in BlockTrail, the default block explorer on latest release version 3.1.2

### ISSUE THREAD

**Issue by nimbosa** [spesmilo/electrum#4274]
of course, this is BlockTrail.com's shortcoming, but it impacts ALL SegWit wallets as of 2018 April 18 on latest version 3.1.2 since Electrum uses BlockTrail as the default block explorer and Electrum only creates native SegWit Bech32 addresses

so when you click "_View on block explorer_" on popup menus, BAM!
_______________
### Oh Snap!
_Something went wrong there.
Maybe go back to the homepage and try again from there._
_______________

`bc1q4dgnccqsfa2yj3pxml5k73xumszcu00a928sq6e87rctsnlkvd0sgwfvpf` is a valid Bech32 SegWit address: https://www.blocktrail.com/BTC/address/bc1q4dgnccqsfa2yj3pxml5k73xumszcu00a928sq6e87rctsnlkvd0sgwfvpf

### Resolution
maybe choose an alternative block explorer (which implements native SegWit Bech32 format) or add an option to change the explorer under user preferences? this does not affect Electrum Wallets using non-SegWit, Standard addresses directly.. although incoming and outgoing txns may involve bc1* addresses

**Comment by SomberNight** [comment]
> change the explorer under user preferences

You already can.

But for testnet, blocktrail is currently the only option available
https://github.com/spesmilo/electrum/blob/95a93a3f86840bbbd8ee6e1388a8e673502c6d2b/lib/util.py#L500-L556

So we should try to find a block explorer that has both testnet and bech32 support and set that as default.

**Comment by blockonomics** [comment]
We can spawn a testnet version of blockonomics, if it is made default for both mainnet and testnet. 
Let me know your thoughts

blockr.io and biteasy can be removed. They are non operational

**Comment by SomberNight** [comment]
Note: the default block explorer has since been changed to blockstream.info

**Comment by shivaenigma** [comment]
@SomberNight can you please refer to the commit that closes this. blockstream.info is looking good for testnet as weel
However, it doesn't show bitcoin address for TX inputs that could confuse users

**Comment by SomberNight** [comment]
See https://github.com/spesmilo/electrum/commit/6d5b28a9c5228e49ab173c7e034196ae12293b84 and https://github.com/spesmilo/electrum/commit/39fb5b8f581742c9909646ae3e78db968a0c9ee1
