### ISSUE TITLE
[Windows] Load transaction from QR-code is not working 

### ISSUE THREAD

**Issue by ik105** [spesmilo/electrum#4278]
The camera window opens and immediately closes (Windows 7 x64, Electrum 3.1.3).
In linux everything is OK.

**Comment by SomberNight** [comment]
I'm guessing it also happens when you try to load an address from QR code in the `Send` tab?

**Comment by ik105** [comment]
No, in the send tab it works.

**Comment by SomberNight** [comment]
Quite a bit of code changed since the original report. Is this issue still applicable to latest Electrum?

**Comment by SomberNight** [comment]
I've just tested and it works for me, on Win10.
