### ISSUE TITLE
My ELECTRUM wallet has stolen my money obviously! What should I do?

### ISSUE THREAD

**Issue by Eki77** [spesmilo/electrum#4289]
Hi there, recently I purchased arround 200usd in BTC and the seller (in this case VIRWOX) does make the transaction which can be seen as well on the page https://blockchainbdgpzk.onion/. So the seller side did all fine. But when I enter in my wallet, it looks like the transaction has never happened and the wallet is still and after 2 weeks empty. This is now the 2nd time something like this happens and I am getting the feeling ELECTRUM has stolen my money! Does anybody have a suggestion? I checked the transaction address and it is fine. There are no mistakes on my side.

**Comment by SomberNight** [comment]
- What version of Electrum?
- What is the colour of the orb in the lower right?
- Does your wallet include the output address of the transaction? See e.g. https://bitcoinelectrum.com/frequently-asked-questions/#how-can-i-tell-if-an-address-belongs-to-my-wallet

**Comment by SomberNight** [comment]
closing, no response.
