### ISSUE TITLE
Indicate when trustedcoin API is not available

### ISSUE THREAD

**Issue by elena-g01** [spesmilo/electrum#4291]
Hi everyone! Need help!

I'm running the OS X version of Electrum (**version 3.1.3**) .
I'm not able to send any bitcoins because both Preview and Send buttons suddenly **stopped responding** today.
I think the issue **can be related to #3084** (behavior is exactly the same), but can't figure out how to apply the solution with SSL **on Mac**.
The wallet had always worked fine before this problem occured today.
Any ideas? Thank you very much in advance for any recommendations!

Kind regards,
Elena.

**Comment by bauerj** [comment]
What color does the orb in the lower right hand side of Electrum have?

**Comment by elena-g01** [comment]
Green one.

**Comment by elena-g01** [comment]
Also https://api.trustedcoin.com/ isn't available right now.
Can these two issues be connected?

**Comment by SomberNight** [comment]
are you mentioning that because this is affecting a 2fa wallet?

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/issues/4071

**Comment by SomberNight** [comment]
I can reach the TrustedCoin API now. Was the problem due to a server downtime; or were(/are) you behind a restrictive firewall perhaps?

**Comment by elena-g01** [comment]
_are you mentioning that because this is affecting a 2fa wallet?_
Not sure, just guessing :)

_I can reach the TrustedCoin API now._ 
Unfortunately I still can't.

_Was the problem due to a server downtime; or were(/are) you behind a restrictive firewall perhaps?_
The firewall on my Mac is not active.

**Comment by elena-g01** [comment]
FIXED THAT!
I couldn't reach the TrustedCoin API via my WiFi network! (I guess there are some new restrictions in Russia or smth like that)
I tried VPN connection, https://api.trustedcoin.com/ became available, and also I was able to preview and send again!

**Comment by bauerj** [comment]
We should make the user aware of that issue in a less subtle way like changing the trustedcoin icon or showing a message box.

**Comment by bauerj** [comment]
@SomberNight Or is that fixed with d0352379d7f5c5 already?

**Comment by bauerj** [comment]
Great!
