### ISSUE TITLE
bitcoin spariti

### ISSUE THREAD

**Issue by alessandrokid** [spesmilo/electrum#4295]
Recupero wallett attraverso il seed (12 parole) il mio account risulta senza bitcoin? vorrei sapere dove sono finiti?

Recover wallett through the seed (12 words) my account is without bitcoins? I would like to know where they ended up?

**Comment by SomberNight** [comment]
Read this: https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet

And give more details, preferably in English, if you would like help.

**Comment by alessandrokid** [comment]
thanks sombernight, i had a problem with the wallet electrum was saved on a smartphone. I installed the wallet on PC following the procedure to restore through the (seed) once entered my balance is 0btc

**Comment by SomberNight** [comment]
- Do you see any transactions in the History tab?
- Are the addresses familiar? (e.g. in the Addresses tab; hidden by default: `View`>`Show Addresses`)

**Comment by alessandrokid** [comment]
hello sorry for the delay, No transaction, on the smartphone I saw the transaction performed by another of my wallet

**Comment by broker10** [comment]
hello everyone for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email

**Comment by soniaklick** [comment]
Well, i was in the same situation until i sorted professional help. These guys helped me recover my wallet private key [secrettruthhackers.imfast.io], what would i have done when my wallet had investors bitcoin in there? Thanks to the secrettruthhackers.
