### ISSUE TITLE
[Android] Hide wallet name when selected tab is "Receive"

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#4297]
You don't really want to disclose the name of your wallet to a person/scanner when you want to receive and turn your screen to them. Among other privacy concerns, after multiple uses it makes it easier to tell that certain addresses belong together.

For this end, I suggest hiding the wallet's name when on the Receive tab.

**Comment by ecdsa** [comment]
fixed now: the qr code is shown in a popup
