### ISSUE TITLE
Kivy shows empty string fiat balance when cannot contact exchange

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4298]
With the kivy GUI, in the "Balance" (history) tab, Electrum will not show a fiat balance if it cannot query the current exchange rate.
I guess we could persist the last known exchange rate and use that; or display "unknown" or similar instead.

![kivy_no_fiat_balance](https://user-images.githubusercontent.com/29142493/39099115-fa5ddb72-4674-11e8-874d-f871abfce421.png)

See
https://github.com/spesmilo/electrum/blob/d0352379d7f5c5aac2cfb63ec383603538860c93/gui/kivy/uix/ui_screens/history.kv#L60
https://github.com/spesmilo/electrum/blob/d0352379d7f5c5aac2cfb63ec383603538860c93/gui/kivy/main_window.py#L661
https://github.com/spesmilo/electrum/blob/d0352379d7f5c5aac2cfb63ec383603538860c93/lib/exchange_rate.py#L528-L530

**Comment by ecdsa** [comment]
it is better to display that the exchange rate is unknown.
using deprecated exchange rate could result in fund losses
