### ISSUE TITLE
Can't run ./electrum on 32 bit system

### ISSUE THREAD

**Issue by coinsmith** [spesmilo/electrum#4303]
Hi, this

"To run Electrum from its root directory, just do: ./electrum"

Doesn't seem to work on my 32 bit Ubuntu 14.04 laptop. I can see that the file isn't an executable, when I try to make it one via 'chmod +x electrum', it's telling me I don't have the permissions to do so. The same happens when I try this as root on my own machine. Any ideas?

**Comment by bauerj** [comment]
Hey,

the file is just a Python application. You can also start it using `python3 ./electrum`. Maybe the directory resides on a filesystem where execution is not allowed (e.g. `/tmp`)?

**Comment by coinsmith** [comment]
Ah, I tried 'python3 electrum' but hadn't thought of 'python3 ./electrum'
Did the trick, great! Closing this. Thanks for the fast response.
