### ISSUE TITLE
Moving Bitcoin Private from Wallet to Exchange.

### ISSUE THREAD

**Issue by fleshfeaster** [spesmilo/electrum#4304]
I am unable to send my btcp from my wallet to an exchange. I get error message that says line #1 is wrong which is the depo address for where I want my coins to go to.

**Comment by bauerj** [comment]
Hey,

this is only for Bitcoin, please contact the authors of the specific fork for support.

**Comment by SomberNight** [comment]
(maybe https://github.com/BTCPrivate/electrum-btcp ?)

**Comment by fleshfeaster** [comment]
What?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SomberNight** [comment]
Electrum only supports bitcoin. There are forks of the project for different altcoins but these are not maintained, reviewed, or endorsed by the main team.

**Comment by fleshfeaster** [comment]
my roomate helped me. instead of copy paste the dep address he said double click and paste and though it was the exact same address it worked for some odd reason. finally sold my btcp. time to wait for a dip and buy back then sell when its listed on hitbtc and kucoin.


________________________________
