### ISSUE TITLE
Can't get QR code from Master Public Key screen of multisig wallet setup

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#4307]
Trying to set up a multisig wallet in testnet mode on 3.1.1.

This is more difficult than it needs to be because the Master Public Key screen of the setup wizard has no QR code display button:

![screen](https://user-images.githubusercontent.com/34793/39211323-21ad99b4-47c0-11e8-832d-b8727c575d9c.png)

The Add Cosigner screen does have a QR button to read a QR code, which makes me think the intent was to offer a QR code display button on the Master Public Key screen.

~~I'm running on Mac, which lacks camera support, so this might be the cause.~~ This happens regardless of whether a camera is available (Linux) or not (Mac).

The case I have in mind is that the cosigner wallet resides on a second computer the user owns. Without QR codes, the user either needs to download apps to encode/decode, manually transcribe, send through email, or rig up transfer with a USB drive.

**Comment by SomberNight** [comment]
This a regression from https://github.com/spesmilo/electrum/commit/553bf98664c87273f9e55b5699c44cc805eb4bf4#diff-a3125ab4a998d214198f55dfc03353d0
