### ISSUE TITLE
Feature Request: display fee in fiat

### ISSUE THREAD

**Issue by johnwc** [spesmilo/electrum#4314]
As mentioned by request #2838, can we get a read-only textbox next to the fee slider of the current selected fiat amount. Of course this would be the default view when the "Edit fees manually" is **not** checked.

Preview Example:
![capture](https://user-images.githubusercontent.com/2798441/39323882-87352d62-4953-11e8-9ca1-a554c23ecb92.PNG)

**Comment by SomberNight** [comment]
So are you basically asking for the same thing the existing issue is?

**Comment by SomberNight** [comment]
> It seems to be a mass amount of issues that are fixed or implemented and yet the issue is still open.

which ones? tag me in them then :P

**Comment by johnwc** [comment]
Alright, I'll try to go through some this evening when I have some extra time. I know I looked through a few earlier from older versions that are now resolved in current release.

**Comment by SomberNight** [comment]
In any case, let's focus the discussion into the existing issue (https://github.com/spesmilo/electrum/issues/2838).
