### ISSUE TITLE
build: use OS-native embedded binary signatures

### ISSUE THREAD

**Issue by toxeus** [spesmilo/electrum#4317]
Currently, electrum packages for various platforms are signed using PGP. Consequently, a user can verify the integrity and authenticity of a distributed package by downloading the corresponding `*.asc` file and executing the corresponding PGP commands. I claim that the vast majority of regular users is not doing it.

But the proprietary OSs (Win & Mac) have a native digital signature verification scheme that is embedded in the binary itself (no additional download). Furthermore, when the signature is missing the following warning is shown to the user (it's currently the case for electrum).
![sign](https://user-images.githubusercontent.com/7702854/39341352-16d10ebc-49d3-11e8-8b93-0ed779d4fb3b.png)

I'd like to raise awareness of this native digital signature scheme and make you consider using it. There are at least two good reasons for it:
* users unfamiliar with PGP can still profit from the benefits of digital signatures
* as security-minded people we should avoid for regular users to become accustomed to ignoring security warnings (like the one above). It's a similar situation as with security warnings in the browser about self-signed certificates.

Last, I want to make very clear that I'm not advocating to drop the PGP signatures. They are still very important for non-proprietary OSs. Furthermore, PGP is, because of it's decentralized structure, more trustworthy (... but has worse usability). 

References:
[Native digital signatures Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380259(v=vs.85).aspx#introduction_to_code_signing)
[Native digital signatures macOS](https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html)
[Native digital signatures Android](https://developer.android.com/studio/publish/app-signing)

**Comment by SomberNight** [comment]
Yes, I agree very much so.
This has been planned for some time now. I think it's even "ready" for Windows.
The reason the Windows binaries are not signed yet is to do with deterministic builds. It is not clear how to keep the deterministic build feature if the binaries are signed.
Maybe we should look at what bitcoin core does.

The Android apk is of course signed, it could not even be uploaded to Google Play without that. :)

See:
https://github.com/spesmilo/electrum/pull/3846
https://github.com/spesmilo/electrum/issues/3355

**Comment by toxeus** [comment]
This is great to hear :+1: 

> The reason the Windows binaries are not signed yet is to do with deterministic builds.

Determinism is probably lost because of the timestamps. But IIUC they can be omitted:

From [signtool's doc](https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764(v=vs.85).aspx):

/t URL | Specifies the URL of the time stamp server. If this option is not present, then the signed file will not          be time stamped. A warning is generated if time stamping fails.
-- | --

**Comment by toxeus** [comment]
Not sure though if the `osslsigncode` tool does allow dropping the timestamp, too. [This](https://github.com/spesmilo/electrum/pull/3846/files#diff-26e6d49b34ee41bcc392d10f689ff0c2R51) would be the relevant line in the aforementioned PR.

**Comment by bauerj** [comment]
No, that's necessary for full Windows Smart Screen functionality. It should be easy enough to just strip the signatures from the binary and compare that with the deterministic output.

**Comment by toxeus** [comment]
I see. I agree that it shouldn't be difficult to write a script that can strip the signature.

**Comment by MDrollette** [comment]
@ecdsa Is there more context around this being closed? It would be beneficial to take advantage of security features in macos and other tools (LittleSnitch) by having a natively signed release.
