### ISSUE TITLE
error when starts//then dont spend money

### ISSUE THREAD

**Issue by barsyatochka** [spesmilo/electrum#4318]
button "send" is active, but dont send

![photo_2018-04-27_17-47-21](https://user-images.githubusercontent.com/35959307/39363636-6934d82a-4a44-11e8-9e9d-2729a8c71264.jpg)
![photo_2018-04-27_17-48-12](https://user-images.githubusercontent.com/35959307/39363637-6967057a-4a44-11e8-8cfa-685579937899.jpg)

**Comment by SomberNight** [comment]
Hi. This is looks to be a duplicate of https://github.com/spesmilo/electrum/issues/4310.
You are behind a restrictive firewall (perhaps on the ISP/government level) that blocks you from connecting to the TrustedCoin server.
Can you try the workaround described in https://github.com/spesmilo/electrum/issues/4310#issuecomment-384442252 ?

**Comment by SomberNight** [comment]
Closing; no response, and my above comment explains the situation anyway.
