### ISSUE TITLE
Electrum NEEDS automated testing

### ISSUE THREAD

**Issue by BlinkyStitt** [spesmilo/electrum#432]
I can find ZERO code tests in electrum.

Do you have any plans whatsoever to add unit testing or integration testing or any kind of any testing?

**Comment by knocte** [comment]
I see that now there are some tests in https://github.com/spesmilo/electrum/tree/master/lib/tests . I'm guessing these are unit tests right? does electrum have integration tests? or maybe they are in electrum-x repo?

**Comment by ecdsa** [comment]
no, it does not really have integrated tests
