### ISSUE TITLE
wallet.is_mine behaviour when offline signing beyond gap limit is undesired

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4322]
When offline signing with deterministic wallets, on the offline machine, the tx inputs/outputs will not be recognised as is_mine (if beyond the gap limit).
The signing itself will work, but this still has some consequences.

Notably:
- the tx dialog will not colour the inputs/outputs
- in case of hw wallet, **the hw device will treat all outputs as foreign** (so e.g. change will have to be confirmed as well)
https://github.com/spesmilo/electrum/blob/530980ea37b9627b0ab26b63acc8866b799b23bc/lib/wallet.py#L1477-L1488

See e.g. below picture, where the `Sign` button is enabled, and in fact all inputs/outputs belong to this HD wallet.
![offline_signing_is_mine](https://user-images.githubusercontent.com/29142493/39401042-a2c9154e-4b3c-11e8-9638-a6a4087c3ec8.PNG)

Related: https://github.com/spesmilo/electrum/issues/3302

**Comment by SomberNight** [comment]
This is hard to fix :(
We could easily learn from the serialised transaction the is_mine inputs; as for the signing to work, the inputs already contain derivation paths.
However, the outputs are problematic. The serialisation format does not contain any extra info about them.
Actually, the outputs would be the more important thing to fix, not the inputs, for hardware wallets (so that they don't prompt the user to confirm). It is not really worth it to fix just the inputs.

Suggested workaround for users: manually increase the gap limit on the offline machine.

**Comment by SomberNight** [comment]
To increase the gap limit on the offline machine one can e.g. do
```
wallet.change_gap_limit(100)
wallet.gap_limit_for_change = 100
wallet.synchronize()
```
(note however that after changing the gap limit for change that wallet file should not be used to construct new transactions due to https://github.com/spesmilo/electrum/issues/3859 (but this wallet is the offline wallet anyway, presumably it won't create txns))

**Comment by SomberNight** [comment]
Implementing [BIP-174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) would help with this, as that partial transaction serialisation format can include the derivation path for the is_mine outputs (https://github.com/achow101/bitcoin/commit/d1957f4a68d3b04cecf3aeb112521195aac17c9c).

Related: https://github.com/spesmilo/electrum/issues/3738#issuecomment-358185706

**Comment by jonathancross** [comment]
BIP-174 support would be great, should there be a feature request created for this?

Related discussion about adding BIP-174 support to Trezor python library https://github.com/trezor/python-trezor/issues/183

**Comment by SomberNight** [comment]
there is a feature request: https://github.com/spesmilo/electrum/issues/4615

**Comment by OhCrap99** [comment]
This command did it!
wallet.gap_limit_for_change = 100

Thank you !!

**Comment by SomberNight** [comment]
Note: this should be tested again, and fixed, once https://github.com/spesmilo/electrum/pull/5721 is merged
