### ISSUE TITLE
Impossible to use Multisig Wallets

### ISSUE THREAD

**Issue by xmodefhs** [spesmilo/electrum#4325]
I got a pair error when I try to sign a BTC transaction with a Nano S and multisig wallet.

I have a wallet 2/4 and It's possible only sign the transaction with the combination Ledger 1 + Ledger 2, if I try any other combination I got an Ledger Pair Error.

I just try to create another multisig wallet and change the ledger and that time I used the Ledger 3 as consigner 1 and Ledger 4 as consigner 2 and I can see that only the combination Ledger 3 and Ledger 4 works.

My conclusion, that is some problem with Electrum when you try to use consigner 3 or 4, also you have to use in the same order, I mean, Ledger used to consigner 1 and Ledger used to consigner 2.

Any patch or configuration options to fix the issue. I'm using Ledger Nano S with PK of Consigners.

**Comment by xmodefhs** [comment]
Electrum 3.1.2

**Comment by SomberNight** [comment]
3.1.3 resolves this https://github.com/spesmilo/electrum/issues/4218
but it also "works" in earlier versions too, it is just a bit less intuitive https://github.com/spesmilo/electrum/issues/4199#issuecomment-377306332

**Comment by xmodefhs** [comment]
I can't use my Ledger in a random combination, but I could use your tips and follow the order to ready the right ledger, skip when I don't want to pair one of the ledgers and it's works...
I'm ok with it... 

Thanks.
