### ISSUE TITLE
sign message: inconsistent handling of whitespaces

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4327]
Message signing/verification gets stripped of leading/trailing whitespaces in Qt, but not when e.g. using the `signmessage` command.

https://github.com/spesmilo/electrum/blob/bc76d63f61961d1a875ba32b07da7fbe8fc7a4d1/gui/qt/main_window.py#L2148
https://github.com/spesmilo/electrum/blob/bc76d63f61961d1a875ba32b07da7fbe8fc7a4d1/gui/qt/main_window.py#L2176

**Comment by SomberNight** [comment]
In the command line, having whitespaces is very explicit, the user is fully aware;
unlike in Qt, where it's not so clear, so it's better to strip there.

**Comment by fametrano** [comment]
For the record: Bitcoin Core's Qt GUI does *not* strip whitespace. Both signing and verifying take the message verbatim — `toPlainText().toStdString()` with no `trimmed()`:

https://github.com/bitcoin/bitcoin/blob/556988790a7f961693a8fd93f73725baea66476a/src/qt/signverifymessagedialog.cpp#L141
https://github.com/bitcoin/bitcoin/blob/556988790a7f961693a8fd93f73725baea66476a/src/qt/signverifymessagedialog.cpp#L202

which is consistent with its RPCs (`signmessage`, `signmessagewithprivkey`, `verifymessage`) and with `MessageHash` hashing the exact bytes.

So the two Qt GUIs disagree: a signature produced here over " hello " actually commits to "hello" and verifies in Bitcoin-Qt only against the trimmed text, while a Bitcoin-Qt signature over " hello " never verifies here, even when the exact message is pasted.
