### ISSUE TITLE
Containerized packages; binary distributable for Linux

### ISSUE THREAD

**Issue by TerkiKerel** [spesmilo/electrum#4343]
Hi,

Is there any possibility to create one or more packages for:

snap
nix
appimage
flatpack
a standalone for linux

Thank you

**Comment by bauerj** [comment]
Hey,

as far as I know there already exists code to generate snap executables in this repository. Have you tried that?

**Comment by SomberNight** [comment]
I think he's asking for official packages.

**Comment by bauerj** [comment]
@TerkiKerel What's your use-case? Are you running a distribution that has no package for Electrum?

**Comment by Philippe734** [comment]
There is already a snap version of Electrum:
https://snapcraft.io/electrum
But the corrects questions are maybe:
Why an old version of Electrum, v2.6@october 2016 ?
Is it safe and official?

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/4054#issuecomment-445109224
