### ISSUE TITLE
Wrong Bitcoins counting (A, E instead numbers)

### ISSUE THREAD

**Issue by fervi** [spesmilo/electrum#4347]
Hello. Maybe it is something with my Devuan system, but even on new user I can't get propety Bitcoin count.

![electrum.jpeg](https://gateway.ipfs.io/ipfs/QmaR8JnNAdF5NxLA5BRdoYRFTY98mqGptJbzw68HQPfT13)

I can't even (I think?) send money, because Fee is also E and A (whatever it means). It is a bug Electrum? My system? Maybe Can I help you somehow?

**Comment by SomberNight** [comment]
Looks to be a duplicate of https://github.com/spesmilo/electrum/issues/3294 which is fixed on latest release

**Comment by fervi** [comment]
Yep, works on new version - sorry for spam and thanks for help :)
