### ISSUE TITLE
User mistakenly saves transactions locally instead of broadcasting

### ISSUE THREAD

**Issue by lashby1160** [spesmilo/electrum#4356]
Error code image below.  However, the attempted send reduced the balance, and is shown as an unconfirmed withdrawal. 

![image](https://user-images.githubusercontent.com/39205252/39951273-30afe2b6-553d-11e8-8b9b-07cf393e282d.png)

![image](https://user-images.githubusercontent.com/39205252/39951299-67bbf22c-553d-11e8-80d0-d62704fcec2b.png)

**Comment by SomberNight** [comment]
Those are "local" transactions, as the text states. They have not been broadcast to the network, only your wallet has them. If you want to broadcast them so that they can actually "happen", right click > Details > Broadcast.

**Comment by SomberNight** [comment]
![tx_dialog](https://user-images.githubusercontent.com/29142493/39951422-0eec7f84-558a-11e8-9140-64c4abe36d20.PNG)
@ecdsa Maybe we should put that `Save` button elsewhere? On the bottom left? And change the text perhaps... save local/save offline. It's probably confusing for newbies.

**Comment by ecdsa** [comment]
yes, it should be on the left

**Comment by lashby1160** [comment]
It is indeed confusing for "newbies"  - right clicking the local transaction and hitting broadcast, does not work - same or similarly indecipherable error message.  Besides that - the address that I was attempting to send to, as I understand it, has expired.  How do you simply reverse the local transaction and restore my original balance?  By removing it?

**Comment by SomberNight** [comment]
> right clicking the local transaction and hitting broadcast, does not work - same or similarly indecipherable error message

> note that if there is dependence between your local transactions, you might need to broadcast them in some specific order

---

> How do you simply reverse the local transaction and restore my original balance? By removing it?

Yes. Right click > `Remove`
