### ISSUE TITLE
Confirmed transactions remain as "Not Verified"

### ISSUE THREAD

**Issue by nolteman** [spesmilo/electrum#4359]
Confirmed transactions remain as "Not Verified" the problem appeared when I changed to a new wallet.
ALL
![image](https://user-images.githubusercontent.com/6262110/39962354-f8310108-5600-11e8-8e56-1e8e434d5b76.png)

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here https://github.com/BTCPrivate/electrum-btcp

**Comment by nolteman** [comment]
electrum?  Someone has to change the name of the wallet

**Comment by SomberNight** [comment]
Tell that to them then. They forked this project, not the other way around.
