### ISSUE TITLE
How to copy seed and mnemonic from Android Electrum client?

### ISSUE THREAD

**Issue by shnorbluk** [spesmilo/electrum#436]
I want to share with you a very small improvement I made in the Android client. Today there is no way to copy and paste seed and mnemonic to save them in a secure place. This is problematic to use it on different computers or to reinstall it later on Android.
In gui_android.py, I replaced
<code>modal_dialog('Your seed is',seed)<br>modal_dialog('Mnemonic code:', ' '.join(mnemonic_encode(seed)) )</code>
with:
<code>dialogGetInput( 'Your seed is',seed,seed)
mnemo= ' '.join(mnemonic_encode(seed));
droid.dialogGetInput('Mnemonic code',mnemo,mnemo)</code>
It is a quick and dirty fix but I think the best solution would be to add a new screen with seed and mnemonic and a button "Copy to clipboard" above each of them.
Thank you to take attention to my suggestion.

**Comment by ecdsa** [comment]
it would also expose the seed to other applications.
it is better to copy the seed phrase on paper
