### ISSUE TITLE
"Incorrect Password" bug

### ISSUE THREAD

**Issue by rowanlaw** [spesmilo/electrum#4387]
Hello,

I installed Electrum to try out Testnet coins the past 3 days. Today when I logged on again, the "Incorrect Password" message popped up. I only set a short digits only password and also successfully logged in for last two days so it's strange. The wallet name was correct. I tried many times and failed. After 10 minutes, I retried with the same password, I successfully logged in. There is possibly a bug with the password checking function.

Thanks,

**Comment by rowanlaw** [comment]
Yes, couldn't think of anything else yet

**Comment by ecdsa** [comment]
I could think of caps lock, or many other things...

**Comment by rowanlaw** [comment]
It's not caps lock, it's digits only password and I actually tried turning it on and off too. But anyway...
