### ISSUE TITLE
Where Can I Find Docs for the pip Package?

### ISSUE THREAD

**Issue by GalGreenfield** [spesmilo/electrum#4392]
Hello,

I'm not sure I'm posting this in the right place:
I installed on Windows the Electrum pip package by running `pip install electrum`  (in my terminal).
I'm assuming that this is the official Electrum package (it looks like it from running `pip show electrum`).

Assuming it's the official package, where can I find the docs for it?

**Comment by bauerj** [comment]
Hey,

this package doesn't contain Electrum. It's just the to prevent people from registering the name.

See the download page for instructions on how to install Electrum using pip.

**Comment by SomberNight** [comment]
Regarding the documentation, and using Electrum in scripts, see
http://docs.electrum.org/en/latest/coldstorage_cmdline.html
https://github.com/spesmilo/electrum/blob/master/lib/commands.py
but in the end, I mostly suggest reading the source.
