### ISSUE TITLE
[Android] Electrum wallet not starting v3.1.3.0

### ISSUE THREAD

**Issue by mychachiusername** [spesmilo/electrum#4393]
Hi guys,

Thanks a lot for providing the best wallet in the store. This is my first bug report so I'm sorry if I'm not giving enough info.

The wallet doesn't start in Android 5.1.1 Samsung Galaxy Tab A (2016). I keep getting "Unfortunately, Electrum has stopped" right after the Electrum logo shows up. I have tried to start the app after a factory reset, clean cache, clean data, reinstall a few times, but it doesn't work. The app version is 3.1.3.0. I'm not sure how to attach here a log report.

I really would like to be able to run the wallet in my android tablet.
Thanks for your help

**Comment by ecdsa** [comment]
please provide a log report, with "adb logcat"
