### ISSUE TITLE
stuck in synchronizing

### ISSUE THREAD

**Issue by plainjane224** [spesmilo/electrum#4395]
I transferred bitcoin from my coinbase account to my electrum wallet 9 days ago, coinbase says it's completed and unspent but every time I open my electrum wallet it has the gear symbol and unknown as if it looks to be accepting a transaction and the bottom says synchronizing but my bitcoin has not appeared. HELP!!!

**Comment by SomberNight** [comment]
Update to the latest version of Electrum.

**Comment by SomberNight** [comment]
I'm guessing updating worked; closing.
