### ISSUE TITLE
 does not send a transaction

### ISSUE THREAD

**Issue by CIIMOH** [spesmilo/electrum#4397]
Electrum 3.0.6
When i try to send funds (BTC), the wallet does not respond to the (send) button. Just nothing happens.
Help pls.

**Comment by bauerj** [comment]
Hey,

please update to the latest version (3.1.3) and check if that helps.

**Comment by CIIMOH** [comment]
unfortunately not, now on version 3.1.3, the same thing happens. I get into my wallet, I see my balance, but also I can not send ..

**Comment by SomberNight** [comment]
Hi. Is this for a 2FA wallet? In that case, see https://github.com/spesmilo/electrum/issues/4310#issuecomment-384442252

**Comment by CIIMOH** [comment]
guys, it helped, thanks a lot, but forgive me, I'm not experienced, I ran into another problem, I only had a wallet (password and seed) and wallet now required (google authenticator code) I do not remember creating something like this when did it. He asks to restore it from the seed, then to make a request for a new code. And then the question is, how do I make this request then a new (google authenticator code)? and one more, when recovering from the seed now, he asks (do you want to keep using two-factor authentication) I should probably keep this to get the same code?

**Comment by SomberNight** [comment]
> when recovering from the seed now, he asks (do you want to keep using two-factor authentication) I should probably keep this to get the same code?

Choose "keep" using two-factor, and then a few steps later, choose "I have lost my Google Authenticator account". Then you will need to enter your seed again, and then it will show you your QR code.

**Comment by CIIMOH** [comment]
thank you very much, everything worked .. thank you!!
