### ISSUE TITLE
3.1.4 Announced but not released?

### ISSUE THREAD

**Issue by amites** [spesmilo/electrum#4398]
Got an announcement email for electrum 3.1.4 including a link to github tag to download

either that tag hasn't been pushed / created or it's marked as private as I'm unable to access either from incognito browser or logged into github

if the announcement was fake then happy to help track down, else seems like someone jumped the gun...

**Comment by xblau** [comment]
I also got an email (on the address listed on my profile) from `"GitHub" <gjquanh@rav-4.ml>`.

The link on the page reads `https://github.com/spesmilo/electrum/releases/tag/3.1.4`,
 but the real link redirects to `https://github[.com]/spacefoxs/electrum/releases/tag/v3.1.4` which does not appear to exist or has been deleted.

It looks like a phishing attempt.

**Comment by amites** [comment]
makes sense, out of habit/paranoia I don't click links in email

closing since this is clearly fake -- hopefully gives others a heads up

**Comment by skeeto** [comment]
That's spam someone sent out to the stargazers list. Here's a copy (**don't follow any links in the message**):

https://mailchi.mp/8c0c601ab18c/github-electrum-314-released

Ignore it.

**Comment by amites** [comment]
nit: can ya put a space between the `https://` and address to break the link?

**Comment by dabura667** [comment]
https:// mailchi.mp/8c0c601ab18c/github-electrum-314-released

**Comment by SomberNight** [comment]
There is no 3.1.4 atm, and we don't send out email announcements.
Also, this page (https://github.com/spesmilo/electrum) and https://electrum.org are the only "official" sources of binaries/source.

That changelog is the 3.1.3 changelog btw.
