### ISSUE TITLE
I've been subject of a phishing attack (or at least that is what I think)

### ISSUE THREAD

**Issue by shackra** [spesmilo/electrum#4399]
I got this email:

![imagen](https://user-images.githubusercontent.com/1055216/40869183-78e370ba-65d3-11e8-8cd6-4000b720c299.png)

I thought it was weird, clicking on the link took me to the following repository:

- https://bitbucket.org/neo-project/electrum/downloads/

But I don't think this project offers its downloadable content though Bitbucket. I did not download anything.

**Comment by xblau** [comment]
Yeah, that same email was sent to other GitHub users, see  #4398.

**Comment by SomberNight** [comment]
There is no 3.1.4 atm, and we don't send out email announcements.
Also, this page (https://github.com/spesmilo/electrum) and https://electrum.org are the only "official" sources of binaries/source.
