### ISSUE TITLE
Failure to sweep Bitcoin Core P2SH segwit private key: "No inputs found."

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#4406]
All on testnet:

On Bitcoin Core 0.16:

- created a new default wallet
- accepted payment from the Receive tab
- obtained address by double-clicking (P2SH-segwit, starts with "2")
- obtained private key from Console with dumpprivkey <address>
- block explorer shows address has funds

On Electrum 3.1.3:

- created a new default wallet
- Wallet>Private Keys>Sweep
- pasted private key from Bitcoin Core
- error: "No inputs found. (Note that inputs need to be confirmed)"

I was expecting Electrum to sweep. Instead, it gave an error.

Electrum wallet created with import defaults to P2PKH, giving wrong address.

My interpretation:

Bitcoin Core is creating segwit-P2SH addresses by default. However, Electrum doesn't know this and is attempting to scan for P2PKH based off of private key.

Electrum finds no P2PKH outputs matching private key, so reports an error.

Is it possible to import into Electrum a Bitcoin Core 0.16.0 default private key?

**Comment by SomberNight** [comment]
Prefix the WIF key with `p2wpkh-p2sh:`.

Related:
https://github.com/spesmilo/electrum/pull/3925
https://github.com/spesmilo/electrum/blob/f0daf2d37bb7043105230d32ca3b179e06b17b15/RELEASE-NOTES#L88-L91

**Comment by rapodaca** [comment]
Worked - thanks!
