### ISSUE TITLE
NameError: name 'bfh' is not defined

### ISSUE THREAD

**Issue by haarts** [spesmilo/electrum#4409]
Commit 1900e58e88010eef0b4b88ec13175311c50f91a9 introduced a tiny bug leading to a 'NameError: name 'bfh' is not defined' error.

This fix is trivial: https://github.com/haarts/electrum/commit/3bfd3ae9511907fc1d33ef0573dc1b829e2617d4. I'll push the branch with the fix end of day. But feel free to cherry pick.

**Comment by bauerj** [comment]
Hey,

this is not occuring here and I don't see why it should. In `network.py` we do `from .bitcoin import *`, which also imports `bfh` into the global scope.

```python
>>> from lib.bitcoin import *
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
>>> bfh
<built-in method fromhex of type object at 0x1D60C4B8>
```

**Comment by haarts** [comment]
Ah. I see. This is a bit tricky I think. 
In the bitcoin module there's this line (https://github.com/spesmilo/electrum/blob/master/lib/bitcoin.py#L29): 
```
from .util import bfh, bh2u, BitcoinException, print_error, assert_bytes, to_bytes, inv_dict
```

Then the is this import in the [network module](https://github.com/spesmilo/electrum/blob/master/lib/network.py#L39):
```
from .bitcoin import *
```

That import I removed because it overlapped with [line 38](https://github.com/spesmilo/electrum/blob/master/lib/network.py#L38) and it affected only two constant references (`COIN`).

I'm closing this issue but I'll keep the explicit `util` reference in my branch. Thanks for being my second pair of eyes on this!

**Comment by SomberNight** [comment]
We should replace the `import *` lines with explicit imports I guess. Like #4367 but that is conflicting too much now.

**Comment by haarts** [comment]
I think we should take it slow. Just incrementally optimize the imports.

**Comment by fjhheras** [comment]
I created a pull request #4448, removing some wildcard imports (superseeds #4367)
