### ISSUE TITLE
transaction was rejected by network: missing inputs

### ISSUE THREAD

**Issue by tokenbk** [spesmilo/electrum#4413]
electrum say me this error: error: {'message': 'the transaction was rejected by network rules.\n\nMissing inputs\n[0100000001a81acc9a43115e52cd7bb12de0e4ce5ab730c3f1d00fbc974f559cb23f9903f5010000006a473044022027e10c940d18373d2ab30aae5c48415f7506bf96b02d4ad0ef4819d85b35fda2022005cd63764ba97081c7fe9aba854d46ebabf546d0e0325145a4326d382f77b3570121039d3860466373f2578e9b3a5e72779f21bc148ac20bbee80f48dd3238e55998ecfdffffff01b3cb05000000000017a9148fe59f4e2d900432d0092cad3cf97e76d6b7864b870f080800]', 'code': 1}

someone can help me please?? is my firts time in electrum and is impossible send the bircoin, always the same error..

**Comment by SomberNight** [comment]
Closing; no response.
