### ISSUE TITLE
Send to Segwit Ledger Fails on Multisig

### ISSUE THREAD

**Issue by pooleja** [spesmilo/electrum#4414]
On Electrum 3.1.3 I have a multisig wallet using Ledger.  When I try to send to a segwit address bc1qm8stlz6yt5vnee0runnlmkg207s6ke73yal60s, the transaction signing fails with error 0x6f00.

Please let me know what other information will help debug this issue.

**Comment by SomberNight** [comment]
Which Ledger device? One of the newer ones, right? The old Nano/hw.1 cannot send to bech32 IIRC.

**Comment by SomberNight** [comment]
Also please give more details about the multisig setup itself. Including copying of partial transactions between machines, if you are doing that.

I've just tested on master, with a 2of2 (trezor T + ledger Nano S) wallet, sending to a p2wpkh address (2 outputs, other is change back), on testnet, and it worked.

On the ledger, I have bitcoin testnet app 1.2.5, secure element 1.4.2, and mcu 1.5.

**Comment by pooleja** [comment]
I realized my firmware was outdated on the Ledger Nano S.  I have confirmed it worked once I updated to the latest.
