### ISSUE TITLE
Win - BTCP Electrum 1.1.1 _ Unable to send BTCP from one address to another

### ISSUE THREAD

**Issue by giob91** [spesmilo/electrum#4423]
I have imported an Electrum BTC private keys wallet into an Electrum BTCP wallet to get the coins.
Now I'm trying to send these new BTCP to another existing Electrum BTCP wallet (using a Ledger).

The problem is that when I try to send the coins, nothing happens. Like the "send" button isn't working.

So I also tried to create another new Electrum BTCP wallet and import the "not-working" BTCP wallet private keys, but it appears a "p2sh" error.

I don't know what to do to transfer and use thee BTCP coins.

Thank you

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. Try asking here https://github.com/BTCPrivate/electrum-btcp
