### ISSUE TITLE
Electrum gui doesn't attach to running daemon

### ISSUE THREAD

**Issue by marceloneil** [spesmilo/electrum#4450]
I was going through some of the code, and I noticed this line here: https://github.com/spesmilo/electrum/blob/ecf6ace975a2393696c43df6d00f46e6387fddcc/electrum#L421
The server variable is a `jsonrpclib.Server` object created here: https://github.com/spesmilo/electrum/blob/ecf6ace975a2393696c43df6d00f46e6387fddcc/lib/daemon.py#L87
The `jsonrpclib` package is separate from the electrum project so I was surprised that it would somehow interact with the gui, or any gui for that matter. Sure enough, when I tested it out there was an error:
```bash
$ electrum daemon start
starting daemon (PID 13120)
$ electrum      
Unknown method: <Fault -32601: Method gui not supported.>
Traceback (most recent call last):
  File "/usr/bin/electrum", line 421, in <module>
    result = server.gui(config_options)
  File "/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 650, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 532, in _request
    check_for_errors(response)
  File "/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32601, 'Method gui not supported.')
```

**Comment by SomberNight** [comment]
somewhat related: https://github.com/spesmilo/electrum/issues/3759

**Comment by marceloneil** [comment]
That would make a lot of sense. Since there is already a well-formatted error for when the gui is already running, maybe a different error could be provided when the command-line daemon is already running?
```
error: Electrum GUI already running
```

**Comment by SomberNight** [comment]
Closing this in favour of https://github.com/spesmilo/electrum/issues/4706
(though I guess they really are the same thing)
