### ISSUE TITLE
Problem with receiving bitcoins

### ISSUE THREAD

**Issue by legrun4ik** [spesmilo/electrum#4459]
I have problem with receiving bitcoins.
As I understood from https://chain.so/address/BTC/18sNGGitJodm2bwA3Q7eHivn47cM6bQCZg
the transaction is confirmed, but there is no money in the Electrum wallet ... In the Date column I can see the word "unknown". What does it mean? And what can I do to complete the process of receiving my funds?

**Comment by bauerj** [comment]
What version of Electrum do you use?

**Comment by legrun4ik** [comment]
Electrum 2.7.18

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-06-25 14:37 GMT+04:00 Johann Bauer <notifications@github.com>:

**Comment by SomberNight** [comment]
Please update to the latest version. It includes a fix to your problem, among hundreds of other fixes.

**Comment by legrun4ik** [comment]
I did it. Thank you

**Comment by legrun4ik** [comment]
I did it. Thank you.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-06-25 14:59 GMT+04:00 ghost43 <notifications@github.com>:
