### ISSUE TITLE
Allow selecting BIP44, 49 and 84 keypaths when creating a wallet from master key

### ISSUE THREAD

**Issue by TheCharlatan** [spesmilo/electrum#4466]
When selecting 'Use a master key' in the Keystore section of the setup wizzard it is currently only possible to create standard BIP44 wallets. There is no apparent way to create a Segwit and Native Segwit wallet with a master key.

**Comment by SomberNight** [comment]
See https://github.com/spesmilo/electrum-docs/blob/master/xpub_version_bytes.rst

**Comment by SomberNight** [comment]
BIP44/49/84 all involve hardened derivation, so I suppose you are actually referring to the script types that are usually used with them, i.e. p2pkh/p2wpkh-p2sh/p2wpkh.

**Comment by TheCharlatan** [comment]
I was purely referring to the keypaths. I added the correct version bytes to my import script now. Still I think it would be a nice addition to a let a user decide with account he wants to use his xpriv for.

**Comment by SomberNight** [comment]
I am still unsure what you would like.
Do you want to allow specifying what derivation path to use from that node onwards?
So e.g. you would paste the root xprv and then specify `m/44'/0'/0'`?

Currently we use the given master key as is, and create a two level derivation from it:
`m / is_change / address_index` -- so e.g. you would paste the master key already at `m/44'/0'/0'` to use BIP44.

**Comment by ecdsa** [comment]
When restoring a wallet from a master key, Electrum expects the master key obtained after the derivation. It would be possible to allow what you are requesting, but that would just create more ways for users to shoot themselves in the foot. So we are not going to do that, sorry.
