### ISSUE TITLE
Electrum transaction error

### ISSUE THREAD

**Issue by HELPMEPLS213** [spesmilo/electrum#4472]
error: {'code': -1, 'message': 'the transaction was rejected by network rules.\n\n64: 

scriptpubkey\n[0100000001a52d318e7bb8516de173be696efabe7f809ef1c075c8af1086caf659985987e0000

000006a473044022034a0955c0278f3d0f29e0070ce01de72cd9c97b81a825dc5928b8e8098641ee7022052

31d651d17400b15dc81bf787d1efb4d7c4f6e187de0aca621d17f668f05a0a0121032318bbdca15d3c78ede

84306daca35640b84338adfe5f66702cca7a2af14ff15fdffffff01ffce0500000000001110dff51e70339e42b08

54cb940be57103a05150800]'}

I downloaded the updated version of electrum wallet because the old version was being rejected by the network rules. I downloaded Electrum 3.1.3 on windows installer and the same issue persists. Can you guys please help me solve this issue.

**Comment by SomberNight** [comment]
What are you putting in the "Pay to" field?
(side note: we should put paying to script behind an option; it should be opt-in)

**Comment by HELPMEPLS213** [comment]
On the pay to field I put the bitcoin address I am sending to. How do I change the option to opt in

**Comment by SomberNight** [comment]
How does that address look like though because from the tx you pasted, it's not a bitcoin address?

**Comment by SomberNight** [comment]
closing, no response
