### ISSUE TITLE
TARS  should reopen issues even if they are closed in some circumstances

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#4476]
TARS tries to merge reports for the same bug together which is good because otherwise we end up swimming in open issues, but sometimes it has false positives:

Concrete example
- #4037 was fixed and issue closed;
- in 3.2.0 a new issue was not allowing to display history -> summary:
 site-packages\electrum-3.2.0-py3.5.egg\electrum_gui\qt\history_list.py", line 177, in show_summary
KeyError: 'start_fiat_value'

This was sent via the bug report tool but was merged under #4037 regardless KeyError was different. Only the history_list.py was the same.

The issue was fixed in  7f16273  because @SomberNight  was online and I reported directly, but otherwise we could have missed this if it was only reported via the tool.

So, as  discussed with @SomberNight we think TARS should reopen issues if they are closed and the version number in a new report is greater than the previous highest version number, or something like this.

**Comment by bauerj** [comment]
I agree, this sounds like a good idea.

**Comment by bauerj** [comment]
This should work with all future crash reports like here: https://github.com/spesmilo/electrum/issues/4219#issuecomment-401775504
