### ISSUE TITLE
Bitcoins sent from Localbitcoins to Electrum 3.1.1 LOST

### ISSUE THREAD

**Issue by grs3100** [spesmilo/electrum#4477]
I have made two Electrum transactions before and everything worked greatly. Now, I transferred Bitcoins from Localbitcoins to Electrum. When doing so an error message popped up. I had no time to screenshot it. Now, looking at my wallet, I see no transaction/ no bitcoins received. On the other side, Localbitcoins, does state that the Bitcoins got transferred to my Electrum wallet. Where are the bitcoins??

I also noticed that I have not been connected. How can i reset all settings, if connectivity is the issue of the wallet not showing the transaction? 

Any help is much appreciated.

**Comment by SomberNight** [comment]
> connectivity is the issue of the wallet not showing the transaction?

Uhmm yes.. it's at least one of the issues.

> How can i reset all settings

First I would try clicking the orb in the bottom right, and selecting a different server, and checking the proxy settings.
But to answer the question, delete the `config` file in the datadir, which is at:
http://docs.electrum.org/en/latest/faq.html#where-is-my-wallet-file-located

**Comment by grs3100** [comment]
Thank you for the reply! I actually found my transaction on Blockchain. The bitcoins were sent from Localbitcoins to my Electrum wallet. The problem is, I followed someone's advice and downloaded the newer Electrum version 3.2.0, which fixed my connectivity issues. Yet, my wallet that received the bitcoins is obviously gone. I tried tying in the seed in the new Electrum to restore the wallet with no success.
How do I go about this? I have the seed.
Thank you again.

**Comment by SomberNight** [comment]
Is it an Electrum seed?
What happens when you try to restore from it?
Are you connected to a server (green or blue orb in bottom right)?

**Comment by grs3100** [comment]
Yes it is the Electrum seed. When I try to restore it in my updated Electrum, nothing shows up as if no transaction has ever been made. The wallet that the Bitcoins are in does not show up either. Yes, the button is green.

**Comment by SomberNight** [comment]
If you prompt the application to show your seed, does it show you the words you expect?

Even if you can't connect to any server, you can make a transaction, preview it, sign it, copy it as hex, then load into newer Electrum, and broadcast it there.

**Comment by grs3100** [comment]
Thank you for all responses, I actually downloaded the old Electrum version closest to the one I had my lost wallet in and entered it with the seed. The wallet showed up and I was able to move the bitcoins to another wallet.
