### ISSUE TITLE
v 3.2.1 is not connecting to server

### ISSUE THREAD

**Issue by nutanchauhan** [spesmilo/electrum#4480]

**Comment by SomberNight** [comment]
Hi. Please provide more details. What OS are you using? Which server are you trying to connect to? Have you tried multiple servers? What exactly makes you think it's not connecting?

**Comment by nutanchauhan** [comment]
I am using windows 7. And i use default connection. V 3.1.3 connect
automatically but v 3.2.0 and v 3.2.1 is showing not connected.

**Comment by SomberNight** [comment]
thanks for the report.
closing in favour of https://github.com/spesmilo/electrum/issues/4483
