### ISSUE TITLE
electrum 3.2.1 isn't connecting to any servers 

### ISSUE THREAD

**Issue by brianiron** [spesmilo/electrum#4482]

**Comment by SomberNight** [comment]
Hi. Please provide more details. What OS are you using? Which server are you trying to connect to? Have you tried multiple servers? What exactly makes you think it's not connecting?

**Comment by brianiron** [comment]
sure. win 10 os. firefox browser.red non connection light on. other servers attempted beyoud default.
thank you for your attention.

**Comment by SomberNight** [comment]
thanks for the report.
closing in favour of https://github.com/spesmilo/electrum/issues/4483
