### ISSUE TITLE
Electrum 3.2.1 Windows dns resolution problems

### ISSUE THREAD

**Issue by Saicere** [spesmilo/electrum#4483]
After upgrading to 3.2.1, a custom server specified under Network -> Server is no longer prioritized as one of the 10 servers Electrum connects to. While selecting a server from one of the already connected nodes under the Overview tab works fine, selecting a different server under the Server tab or setting a custom server that does not happen to be among the connected ones will not work. Consequently, the UI persistently displays "Not connected", and transactions and transaction history are not received.

I have tested this against both my own server, as well as a handful of other random servers displayed by Electrum. In all cases, Electrum did not prioritize connecting to the node on startup, nor did it connect to it if changed while Electrum is running.

Edit: the problem is likely caused by the change involving dnspython; see below.

Reverting to 3.1.3 resolves the problem.

**Comment by SomberNight** [comment]
Can you give a few example servers you cannot connect to with 3.2.x but can with 3.1.3?

**Comment by Saicere** [comment]
Additional information: creating a DNS record for my local server and using that instead of the LAN IP address makes it work fine again, so it definitely seems to be related to the DNS library change in 3.2.0. Note that dnspython seems to bypass the Windows hosts file, so I had to set it on an actual domain.

**Comment by ecdsa** [comment]
this is the discussed change: fc6cb70c809df52fbf8152fb0dfab7213faea49c

**Comment by ecdsa** [comment]
I could reproduce the issue on wine. 
it goes away if I enter "socket.getaddrinfo=socket._getaddrinfo" in the console.
I reverted the above commit

**Comment by ecdsa** [comment]
note: this is the error I see with fast_getaddressinfo:
```
Traceback (most recent call last):
  File "site-packages\dns\resolver.py", line 1119, in reset_default_resolver
  File "site-packages\dns\resolver.py", line 603, in __init__
  File "site-packages\dns\resolver.py", line 767, in read_registry
FileNotFoundError: [WinError 2] File not found
```

**Comment by SomberNight** [comment]
@Saicere could you please try to provide a similar trace as above?
Go into the console tab and
```
import dns
dns.resolver.query(host)
```
where `host` is the host/IP failing to resolve for you.

**Comment by brianiron** [comment]
reverting to previous works again.
hopefully this bug will be corrected for the next update. thank you for the help

**Comment by Saicere** [comment]
@SomberNight Sure.

>> dns.resolver.query("13.80.67.162")
Traceback (most recent call last):
  File "site-packages\dns\resolver.py", line 1051, in query
dns.resolver.NXDOMAIN: None of DNS query names exist: 13.80.67.162., 13.80.67.162.

I guess native getaddrinfo recognizes it as an IP address and skips the actual lookup, while dnspython does not.

**Comment by brianiron** [comment]
as a confirmed luddite , i will go with the easiest fix!
not that much of a tech head i am sorry to say.
appreciate the help though

**Comment by Saicere** [comment]
Looks like the variance we're getting is caused by different behavior on different DNS servers/configurations. I did some quick testing, and;

Google DNS: 
> dig @8.8.8.8 13.80.67.162
>;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 16196
>;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

Cloudflare DNS:
>dig @1.1.1.1 13.80.67.162
>;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 33390
>;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

ISP DNS:
>dig @10.0.0.1 13.80.67.162
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9469
>;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
>;; ANSWER SECTION:
>13.80.67.162.           0       IN      A       13.80.67.162
