### ISSUE TITLE
not connecting to any servers

### ISSUE THREAD

**Issue by odinnite** [spesmilo/electrum#4487]
Its stuck on synchronizing.  I tried e1.verge-electrum.com, e2.verge-electrum.com, e3.verge-electrum.com

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. The forks of the project for different altcoins are maintained by different people and we cannot provide support for them.

**Comment by SomberNight** [comment]
What version of Electrum are you using? What OS?

**Comment by odinnite** [comment]
windows 10, 3.2.1 (I just reinstalled it). See pic below:

**Comment by SomberNight** [comment]
Ok, then it is a known bug (https://github.com/spesmilo/electrum/issues/4483).
We will try to do a release tomorrow fixing it. In the meantime, either
1. Go back to 3.1.3 -- unfortunately you might need to recreate your wallet from seed as the wallet file was upgraded and the old version won't be able to open it
2. Download the Tor browser, start it, and enable the Tor proxy in Electrum

**Comment by odinnite** [comment]
ok

**Comment by odinnite** [comment]
got it thanks
