### ISSUE TITLE
Is there a bug? 12 hours and bitcoin balance still unconfirmed

### ISSUE THREAD

**Issue by jkkjkee72** [spesmilo/electrum#4494]
![electrum screenshot](https://user-images.githubusercontent.com/40779017/42193184-13ba8946-7e3b-11e8-9add-f74dd89223b7.PNG)
![electrum screenshot2](https://user-images.githubusercontent.com/40779017/42193185-162b33c4-7e3b-11e8-9839-2ea11d1ab172.PNG)

**Comment by SomberNight** [comment]
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do
