### ISSUE TITLE
display contact names in the transaction window

### ISSUE THREAD

**Issue by agrajaghh** [spesmilo/electrum#451]
Would be great if the contact names for known adresses would be displayed in the transaction window. So you could check more easily transactions with an offline wallet. 
I'm talking about this window:
![transaction](https://f.cloud.github.com/assets/5296073/1599840/121cf43e-5361-11e3-9167-107e76a7df14.png)

Perhaps it would be usefull too, when its displayed which adresses are change adresses.

**Comment by ecdsa** [comment]
Own addresses (so are change addresses in outgoing transactions) are displayed in green in version 2.1
As we are trying to avoid address reuse, "contacts" not be bitcoin addresses, but aliases (see the openalias plugin) or email addresses
