### ISSUE TITLE
Electrum: 200 € lost

### ISSUE THREAD

**Issue by LeonSol** [spesmilo/electrum#4513]
Transfer from Bitpanda didn´t received! Got the following error from the transactions:

176 confirmations !!!!!!

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	electrum-3.0.3.exe
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	597f4ad5
  Fehlermodulname:	ucrtbase.DLL
  Fehlermodulversion:	10.0.10586.1412
  Fehlermodulzeitstempel:	5a64613e
  Ausnahmecode:	40000015
  Ausnahmeoffset:	0008480a
  Betriebsystemversion:	6.1.7601.2.1.0.768.3
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	29fc
  Zusatzinformation 2:	29fcb81abb51bfc36439ce7ad6bfe3b0
  Zusatzinformation 3:	837d
  Zusatzinformation 4:	837dbd0970cf507c75a666108d2f1e55

Lesen Sie unsere Datenschutzbestimmungen online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0407

Wenn die Onlinedatenschutzbestimmungen nicht verfügbar sind, lesen Sie unsere Datenschutzbestimmungen offline:
  C:\Windows\system32\de-DE\erofflps.txt
---------------------------
Why is there there no btc in my wallet?

**Comment by SomberNight** [comment]
please try with the latest version before reporting here.

**Comment by LeonSol** [comment]
latest version? what do you mean?

**Comment by SomberNight** [comment]
I mean Electrum 3.2.2.
Electrum 3.0.3 is 7 months old and over 1000 commits behind master. It has a known security vulnerability and at least one bug that could be directly related to your problem.

**Comment by LeonSol** [comment]
0k! Is the transaction-code guilty after updating the version?

**Comment by LeonSol** [comment]
My man!!!! I´ve updated the version and the coins received :-)
Have a nice weekend - "SomberNight"

**Comment by SomberNight** [comment]
You too. :)
