### ISSUE TITLE
.onion addresses are leaking to local DNS servers.

### ISSUE THREAD

**Issue by theultrahead** [spesmilo/electrum#4531]
The Electrum software is leaking DNS queries for .onion addresses to local DNS servers. Our client who uses Electrum also uses the Cisco OpenDNS Umbrella service, which is throwing us alerts about "malicious activity" due to the queries for .onion addresses.

These queries should always resolve only within TOR and never be directed at an everyday DNS server. Electrum should detect whether or not TOR is running before attempting to resolve .onion addresses.

We also cannot run Electrum through TOR as it would circumvent the OpenDNS Umbrella security measures.

**Comment by SomberNight** [comment]
How would you detect that you are capable of resolving .onion without trying to resolve it?

**Comment by theultrahead** [comment]
I've just read your reference article, and that is a valid point for transparent TOR situations. In that situation .onion would need "tried". What about perhaps adding a feature such as a --noonion or --notor command line parameter? Or some other way to detect that TOR is not in use (maybe via checking the external IP against the exit node list)?

At the very least, it is maybe a bit inefficient to attempt to resolve something, if you know ahead of time that you're never going to resolve or use it. Perhaps there should simply be such an option to enable/disable support for it?

**Comment by SomberNight** [comment]
I guess we could add a `--noonion` option that will filter out `.onion` hosts.
Would this really help you though? I don't fully understand your situation but I imagine it could be tiresome to educate people about using this option.

**Comment by theultrahead** [comment]
That would be great, and actually help quite a bit. I can always push that parameter out to the users' desktop shortcuts. With such an option, it would keep OpenDNS (and I'm sure some other security products) happy. 

We have to have OpenDNS in place to alert us if something actually undesirable is trying to reach out: not just to .onion, but to anything malicious. It is also there for accountability / compliance purposes.
