### ISSUE TITLE
How to calc transaction size? Want to use payto CLI method with feerate.

### ISSUE THREAD

**Issue by lightlizm** [spesmilo/electrum#4532]
Run Electrum 3.1.3 in  daemon,   How to calc transaction  block size  Before create a transaction.

In  GUI , you send  a payment,   when  setting a amount value ,   it will quick return the block size.
Has a command  that can return block size (byte) when input  a sent amount value?

**Comment by SomberNight** [comment]
Well you can't really calculate the size of the transaction without creating it..
But I think I see your point; indeed it would be nice if the `payto` and `paytomany` commands had an option to set feerate (sat/byte) instead of absolute fee. Is that why you are asking this?

**Comment by SomberNight** [comment]
No, Electrum can't tell you the tx size just from an amount to send. It's a bit of a chicken-and-egg problem; the tx size depends on the fee as well, as the fee depends on the inputs and outputs.
I still think the best solution would be to allow specifying a **feerate** for `payto` and `paytomany`, so then electrum would do this calculation you said itself.

**Comment by lightlizm** [comment]
I doubt why  Electrum running in GUI  can do it?   When I change the payment amount , the  size will be really  changed too!

**Comment by SomberNight** [comment]
the tx size in the GUI is calculated by actually creating the transaction and checking its size.
it already incorporates data such as the fee.

**Comment by lightlizm** [comment]
If I want to do it， also by creating trasaction  and checking list size？
But in daemon，creating a transaction  spent about 7-10 seconds，It is long  time to get feedback ，It is not user friendly.

**Comment by SomberNight** [comment]
Added `feerate` param to `payto` and `paytomany` in https://github.com/spesmilo/electrum/commit/eb5033dfc600a19c7b0d93237ef28c2606c8555f
