### ISSUE TITLE
ELECTRUM V 3.2.2 "no fx rate available" error

### ISSUE THREAD

**Issue by nutanchauhan** [spesmilo/electrum#4539]
Bitcoins rate is not updated automatically and it shows "no fx rate available" error 
I am using electrum v3.2.2 portable, on windows 7, and I try changing every source in "Tools > Preferences > Fiat > Source > "  but nothing happens.

**Comment by SomberNight** [comment]
Can you try with "BitcoinAverage" as source? Or try changing proxy settings, e.g. disable Tor if you have it enabled.
Many providers ban Tor exit nodes. :(

**Comment by nutanchauhan** [comment]
I TRIED EACH AND EVERY SOURCE AVAILABLE ON ELECTRUM BUT NOTHING HAPPENED

**Comment by SomberNight** [comment]
Ok, well I have just tested with 3.2.2 portable on Windows, and it works here.
Can you please try with "BitcoinAverage" **while using a Tor proxy**?

**Comment by SomberNight** [comment]
what currency btw?

**Comment by SomberNight** [comment]
closing, no response.
