### ISSUE TITLE
crowdin moved(?) download link for translations

### ISSUE THREAD

**Issue by mykhi** [spesmilo/electrum#4559]
Hi, `./contrib/make_locale` fails with:
```
Traceback (most recent call last):
  File "./contrib/make_locale", line 58, in <module>
    zfobj = zipfile.ZipFile(io.BytesIO(s))
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
`./contrib/make_locale:58` tries to download `https://crowdin.com/download/project/electrum.zip` which is 404 now.

**Comment by SomberNight** [comment]
Maybe they changed the link from
https://crowdin.com/download/project/electrum.zip
to
https://crowdin.com/backend/download/project/electrum.zip
?
The second link is alive but is that the same content we used to download? (Looks the same to me)

**Comment by mykhi** [comment]
Yes, i confirm it's downloading the proper file with locales and build them properly.
