### ISSUE TITLE
Storing deserialized outputs as tuples is problematic for extensibility

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#4570]
In `transaction.parse_output`, outputs are deserialized into a dict:

https://github.com/spesmilo/electrum/blob/8f17f38b02406ff4f90940ea66dda4b5f93bf227/electrum/transaction.py#L550-L559

However, this dict is later converted into a tuple in `transaction.Transaction.deserialize`:

https://github.com/spesmilo/electrum/blob/8f17f38b02406ff4f90940ea66dda4b5f93bf227/electrum/transaction.py#L724

This is problematic for extensibility, since it means that many places in the codebase need to be rewritten if the number of fields stored in a deserialized output changes.  For example, Namecoin's fork of Electrum stores a `name_op` field in the dict, and consequently when we convert it to a tuple, we end up needing to change every part of the Electrum codebase that accesses the tuple (otherwise we end up with tuple size mismatch errors).

Is there any particular reason that the dict is converted to a tuple?  Is this a performance optimization of some kind?  Would a PR be accepted that makes it use a dict throughout the codebase?

**Comment by SomberNight** [comment]
> Is there any particular reason that the dict is converted to a tuple? Is this a performance optimization of some kind?

It's probably just for convenience.

> we end up needing to change every part of the Electrum codebase that accesses the tuple ... Would a PR be accepted that makes it use a dict throughout the codebase?

Sure, feel free to PR.

**Comment by Nitimar** [comment]
#4570

**Comment by SomberNight** [comment]
While https://github.com/spesmilo/electrum/pull/4596 probably does not actually solve your problem; I think it should at least make it easier to introduce an extra field. (e.g. you can subclass namedtuple and introduce your own `__init__`).
