### ISSUE TITLE
Mempool depth in history tab for unconfirmed transactions should get refreshed for new fee histogram

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#4573]
When using mempool based fee estimation, under the history tab, for unconfirmed transactions a position in MB from tip is shown based on the fee. 

When you click on the transaction in question -> Details, you see a whole other position in MB from tip for the same transaction. Example:
History tab: 1.53 MB from tip
Details of tx dialog: 3.42 MB from tip
(that is more than 2x)

Same happens on Kivy / Android.

I confirm that the position on the history tab doesn't remain static until you close and reopen Electrum, it changes but much less often than tx -> Details dialog. 

Maybe the content of history tab cannot be refreshed as often as we want, so I am not sure if we can call this a bug, but should we keep it if it might not be accurate? Because we can initiate a transaction when a block has just been mined, and when we create the tx based on current fee it will show a 0.10 MB from tip position, and as more txes get into the mempool the position downgrades, but the user will still see 0.10MB from tip on the History tab, thus expecting the tx to be confirmed within relatively short time, while in fact it can be 5 MB from tip.

**Comment by SomberNight** [comment]
fixed in https://github.com/spesmilo/electrum/pull/4915
specifically https://github.com/spesmilo/electrum/pull/4915/commits/a99b92f613b40a1e65c6ea461039a8089911121f
