### ISSUE TITLE
Android app fails to display QR code for large transaction

### ISSUE THREAD

**Issue by Ahmed18** [spesmilo/electrum#4575]
hello,

when i use electrum android wallet for signing multi signature transaction. the app sign the transaction but cannot generate the qrcode for the signed transaction!

ex i have bitcoin address 3123456789..95641. this address has 4 unspent transactions 
the app will generate the signing window (partial signature 1/4) but when i click the qrcode button the app will crash and send bug report activity will appear.

in the windows wallet it can generate the qrcode but in android it can't.
with 1 unspent transaction address it is working without problems.

greets

**Comment by SomberNight** [comment]
> app will crash and send bug report activity will appear

Can you send that report? Or if you have done so already, link to it?

I am guessing that the data is too large for the QR code :(

What multisig setup do you have btw? (how many cosigners (m/n)?  and is it legacy/segwit?)

**Comment by Ahmed18** [comment]
hello SomberNight,

my multisign setup is 3/3 and legacy address
And yes i think that the problem is too large data for QR

in my condition the address had 8 unspent outputs so when signing the app give me partial signature 8/24 because mywallet is 3/3

**Comment by andronoob** [comment]
@SomberNight It still fails, doesn't it? I wonder if there will be a solution, like multi-part QR codes?
Also, I wonder why Electrum app for Android cannot copy a raw transaction as text?

**Comment by SomberNight** [comment]
> It still fails, doesn't it? I wonder if there will be a solution, like multi-part QR codes?

Yes, it still fails. The QR code cannot fit the data... :/ We are already using the lowest error correction level (`L`).
Multi-part QR codes are a bad user experience... but of course not being able to move the partial txn at all is also bad experience.

AFAIR the "fix" in above commit is to fallback to clipboard, but we could make that an option all the time, yes.
