### ISSUE TITLE
user is confused about watch-only wallet

### ISSUE THREAD

**Issue by may23082018** [spesmilo/electrum#4578]
Somehow, I Don't know how, I created an offline wallet. A warning message says: "this wallet is offline, it means that you will not be able to spend bitcoins with it.  Make sure you have the seedphrase or private key before requesting bitcoins that will be sent to this wallet."
If I introduce the seedphrase and private key I have access to an empty wallet.
My objetive is to sell bitcoins of this offline wallet, how could I do this? How could I reverse this offline state? How could I returne this actual offline wallet to an online wallet?
Version electrum 3.2.2

**Comment by may23082018** [comment]
Thanks for answer so soon. My problem is that, after a while, I tried to access to my wallet to sell my bitcoins and I only have access to this type of wallet (watch-only wallet, offline wallet or whatever). After entering the seed phrase and private keys I still do not have access to a wallet that allows me to make the transaction (to sell bitcoins) 
What can I do?
How can I get access to the wallet that allows me to sell my bitcoins?
(I feel completly blocked)

**Comment by AbdussamadA** [comment]
see [this](https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet) for possible reasons why restoring from seed might lead to a different wallet and how to get to the correct wallet.

**Comment by SomberNight** [comment]
There is not much we can do; I think https://github.com/spesmilo/electrum/issues/4578#issuecomment-407344597 answered it.
Closing for now; if you still need help, say so
