### ISSUE TITLE
Seed import bug

### ISSUE THREAD

**Issue by ik105** [spesmilo/electrum#4579]
Hi! I found the bug.

![2018-07-24_153030](https://user-images.githubusercontent.com/38519936/43138667-49831c86-8f58-11e8-8a6b-91f8546f93dc.jpg)

![2018-07-24_152158](https://user-images.githubusercontent.com/38519936/43138684-581c4a56-8f58-11e8-92fb-106bfa405c9b.jpg)

**Comment by AbdussamadA** [comment]
the seed is not dependent on any fixed dictionary so both those variations are valid seeds. however there does appear to be a display bug here. the wallet in question is for the seed beginning with quarter nor uarter.

**Comment by SomberNight** [comment]
Where is the display bug? I don't see it.

But anyway, as @AbdussamadA said, both phrases happen to be valid seeds. It happens. This is not a bug. e.g. `9dk` is a valid segwit seed.

**Comment by ik105** [comment]
Ok. Thanks.
