### ISSUE TITLE
I have lost the seed

### ISSUE THREAD

**Issue by eltiotortilla** [spesmilo/electrum#4580]
Hello, I have lost the seed of my electrum wallet, I have the public key, the addresses of my wallet and my password, but I do not have the seed and I can only enter my wallet in reading mode, I need help, please. I'm desperate

**Comment by SomberNight** [comment]
Hi. Unfortunately there is nothing we can do.

You should either
(1) try to look for your seed words harder, or
(2) try to find the wallet file on your computer that the password is for

You need `seed_words OR (wallet_file AND password)`.
