### ISSUE TITLE
My bitcoins disappeared after reopening Electrum (3.0.6)

### ISSUE THREAD

**Issue by szervaca** [spesmilo/electrum#4584]
Hey folks!

My bitcoins disappeared after reopening Electrum. Yesterday i imported few private keys (what i deleted after i imported because always was fine), and 0.203 btc shown up in my wallet. Today i restarted my computer, and after that my issue comes: I have 3 wallet, and 2 of them working well, coins still there. The third one, shows all transaction history, but no bitcoins. 
Is there anything i can do? 

Kindest Regards

**Comment by SomberNight** [comment]
> shows all transaction history, but no bitcoins.

Please clarify this.

Also, make a backup of the wallet file (or even the whole datadir), and then update to the latest version.

**Comment by szervaca** [comment]
Thanks for you answer.
I updated to 3.2.2, tried to open the wallet file on other computer, but nothing changed.
Wallet is synced well, and it's watch only wallet, so i don't have the seed to repair.

I really don't understand what's went wrong, if once the coins was imported and in the wallet(yeseterday) how is possible after the restart, 24 hours later there's no imported coin?


The wallet shows my transaction history from 2 days ago. Yesterday i imported my private keys, and was available in my wallet. Today, after the restart two wallet balance fine, the third one shows no coin. Before the restart was 0.203. Most annoying part, i deleted the private keys after i imported, because always was fine.

HELP

**Comment by SomberNight** [comment]
> and it's watch only wallet

Then it never could have contained private keys. A wallet will never "turn into" a watch only wallet, it was either always one or it was not.

Let's forget about the wallets that are "working", it's just complicating the discussion.
Did you have a pre-existing import wallet with some private keys already, into which you imported additional private keys? Is that what you did? Were they private keys and NOT addresses?

> shows no coin

In the addresses tab, are the new addresses there?

Are you sure you are not mixing up wallet files?

**Comment by szervaca** [comment]
It is "imported" wallet. Exactly, i did like you described. It was private keys, i used chipmixer and it's gives private keys after mixing your coins. Few days before i also imported some private keys, and everything was smooth. That time when i imported the 0.203 btc, i didn't shut down my electrum/computer it was randomly restarted.

In the addresses tab, i have 10 address and all have 2-4 tx. 
Is it possible those addresses was removed where the coins was storage? 

I'm sure not mixing up wallet files, because non of them contains the missing coins. 
I'm pretty sad.

**Comment by AbdussamadA** [comment]
Seems like you got scammed by chipmixer. Private keys are not meant to be shared so anyone giving you their private keys is doing it wrong. They should have sent the coins to an address you gave them i.e. one whose private keys only you know.

**Comment by SomberNight** [comment]
Note: there is related discussion on [bitcointalk](https://bitcointalk.org/index.php?topic=4754471.0) and [reddit](https://www.reddit.com/r/Electrum/comments/927ahm/my_bitcoins_disappeared_after_reopening_electrum/)

Closing; unclear what we could do.
