### ISSUE TITLE
Настройки

### ISSUE THREAD

**Issue by zhivatma** [spesmilo/electrum#4585]
Здравия! У меня настройки не открываются а все остальное открывается.

**Comment by SomberNight** [comment]
Hi. I'm not sure I understand. Do you mean the `Tools`>`Preferences` option is not working (no dialog shows up)?
What version of Electrum? What OS?

**Comment by zhivatma** [comment]
Здравствуйте! Версия 2.8.1. Да Tools > Preferences

2018-07-27 14:18 GMT+03:00 ghost43 <notifications@github.com>:

**Comment by SomberNight** [comment]
Please update to the latest version, and try with that.

**Comment by zhivatma** [comment]
В версии 2.8.1. сид был из 13 слов?

2018-07-28 3:05 GMT+03:00 ghost43 <notifications@github.com>:

**Comment by SomberNight** [comment]
There were versions that generated 13 word seeds, yes. This should not cause any problems though, they are still, and will be, supported.

**Comment by SomberNight** [comment]
Closing; it's for old version of Electrum.
