### ISSUE TITLE
electrum 3.2.2 testnet wallet segwit multisig

### ISSUE THREAD

**Issue by TankPi** [spesmilo/electrum#4586]
I've created a 2 out of 4 testnet multisig segwit wallet. When I try to receive testnet bitcoin, the receiving address is a mainnet addres i.e. with Leading symbol: 1. The private master keys have prefix: Vpub, which I can't find in https://en.bitcoin.it/wiki/List_of_address_prefixes. When I create a non-segwit multisig testnet wallet, the receiving address have prefix: 2 (Testnet script hash) and the master private keys have prefix: tpub (Testnet BIP32 pubkey).

**Comment by SomberNight** [comment]
> The private master keys have prefix: Vpub

You mean the master public key.
[See ](https://github.com/spesmilo/electrum-docs/blob/master/xpub_version_bytes.rst) for more info.

> 2 out of 4 testnet multisig segwit wallet. When I try to receive testnet bitcoin, the receiving address is a mainnet addres i.e. with Leading symbol: 1. 

Please provide steps to reproduce. This seems hard to believe.
"1..." addresses are p2pkh, meaning they are
- not multisig
- not segwit
- not testnet

**Comment by TankPi** [comment]
> You mean the master public key.
> See for more info.

You where right, I meant master public.

I had the issue with:

```
able mammal taxi refuse name table nuclear hip produce trade promote jazz
Vpub5fxWmLBzDji75BWpiqCngMfuuvTq8SNgMVksZUyVuQqS7FLtYfYGvUyW7vBs2uDwGxLzvRtn4t2FYa78ckMwC8c3TcGDKBHdhms1h6Toa86

stay glance retreat defense shoe bundle garage own fossil forward supply scene
Vpub5fd5XbgN4UP25D9JBUMcCXCsDdxGjjTbQE8Xfq7KFfSAwK98FbyEcS7RXF6E4W4ktDjZ5E83GUXTY8zYn2ghSWR4JkqybVCsARCnWmbw9ky

wait skull perfect replace virus they demise catalog verb two fresh test
Vpub5gXu9N37GvFy899RdoDZVXyECyCd3QqH7WiN26o49jHY1XMfx3rt4f3XF6Go7mQvrL6DtcwTV4q4secGAhZ39LgqMKyXzwjXZqvrB23LQZp

impact tray uphold fall claw cook rookie slow ready entire three cable
Vpub5g4xoTcKMVsaomrsn2whwKHu6LDbJYsHEWGvFTdNoMguiSF6uAofh67gwTyTvA8ZExwBSMjgJfHHd7irzArzDcFGee69Yj4VZuEYbENFoPZ

```
But when I gave it a second try, the first receiving address I got was:
`tb1qemw9ujt8ry3xshq79pyc65hzzzreww8f6t62ryj7c3j7zt4x33cscfgef2`

In non-full screen mode it shows it as:
![image](https://user-images.githubusercontent.com/11289683/43339180-f310f1ec-91d8-11e8-8ba5-965958b716ef.png)

It think that was the issue... Aldo I'm pretty sure that it not had the tb prefix after hitting the copy button, but I can't reproduce that. So, sorry for wasting your time...

**Comment by SomberNight** [comment]
Oh I see, so it does not fit into the text field :P
