### ISSUE TITLE
Using JsonRPC for making transaction

### ISSUE THREAD

**Issue by clintm90** [spesmilo/electrum#4587]
Hello,

I would like to use `payto` command for sending funds from the json-rpc but the command ask me for the password but apparently it's not possible to give password as argument.

Do you have a solution ? (and a kitkat why not)

**Comment by SomberNight** [comment]
This works for me:
`curl --data-binary '{"id":"curltext","method":"payto","params":{"destination":"tb1qu8e0pecaua4muwn57pmcfl4plgwkkp3yh4v02q", "amount": 0.0015, "fee": 0.00005, "password": "1234"}}' http://user:Hi0V-bz9jDn5iFOyhgo53Q==@127.0.0.1:7777`

**Comment by clintm90** [comment]
thanks, i will try, it's electrum zcash ?

**Comment by SomberNight** [comment]
Electrum is for Bitcoin only. All the forks of the project for different altcoins are maintained by different people. If it does not work, ask them. (it works for me here)

**Comment by clintm90** [comment]
i have said this for the address tb1qu8e0pecaua4muwn57pmcfl4plgwkkp3yh4v02q

i don't know this kind of address i'm sorry . . . . . .

**Comment by clintm90** [comment]
okay

**Comment by sanada08** [comment]
How to enable change address in json rpc?
