### ISSUE TITLE
Importing seed, no transactions founded

### ISSUE THREAD

**Issue by clintm90** [spesmilo/electrum#4588]
Hello,

I import a seed from my electrum wallet, the wallets are in same version but when i import the seed, i make the command for listing history and i get this : "{\n    \"summary\": {},\n    \"transactions\": []\n}"

but i know that my seed has transactions and a balance, i don't understand . . . 

Thanks

**Comment by AbdussamadA** [comment]
see if any of the ideas [here](https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet) helps.

**Comment by SomberNight** [comment]
What exactly are you doing? Try to provide steps to reproduce.

**Comment by clintm90** [comment]
a friend has tell me of increasing the address gap and it's worked, i have recover my funds
