### ISSUE TITLE
pay to OP_RETURN fails on trezor

### ISSUE THREAD

**Issue by TuoUP** [spesmilo/electrum#4591]
When using electrum (version: 3.2.2) for a transaction,  I typed script type data as outputs, the transaction can also successfully sign and broadcast on testnet, then I try to add or delete some elements of scripts without rules.,and it is also success signed and broadcast, as far as I know, the bytes of OP_RETURN in bitcoin is limited to 80 bytes, why can I succeed when my bytes length is far beyond this limit?

**Comment by SomberNight** [comment]
The rules are less strict on testnet for many things.

**Comment by TuoUP** [comment]
I use  https://www.blockchain.com/btc/tx/728e24b2e7dd137e574c433a8db08ac2aa0bf0588ad7716e4c5a7da45dbb5933?show_adv=true,this link inside Output Scripts 40434f5059524f424f4037333839643664313135313465633035636335663135656236353932383630383430343733346230343932636132656364396564343837326230343265666137 as output, I just want to verify that the output can be succeed signature and broadcasted, and do not care whether parsed or unparsed , but now it is impossible to enter the signature.

![webwxgetmsgimg 2](https://user-images.githubusercontent.com/28761807/43431827-815e67ce-94a2-11e8-9ed1-e5cd88bb4124.jpeg)

**Comment by SomberNight** [comment]
I don't know what the limit is on testnet, but it's higher than 80 bytes.
80 is the limit on mainnet.

In the original version of your last comment, how did you get that error dialog? I would like to reproduce and fix it.

**Comment by TuoUP** [comment]
This error occurs when signing Script (OP_RETURN) with Trezor (firmware 1.6.0), IN Addition, I try it by Electrum, and I type a script, NOT A ADDRESS, as outputs.

The details are listed as follows:

I use https://www.blockchain.com/btc/tx/728e24b2e7dd137e574c433a8db08ac2aa0bf0588ad7716e4c5a7da45dbb5933?show_adv=true,this link inside Output Scripts 40434f5059524f424f4037333839643664313135313465633035636335663135656236353932383630383430343733346230343932636132656364396564343837326230343265666137 as output, I just want to verify that the output can be succeed signature and broadcasted, and do not care whether parsed or unparsed , but now it is impossible to enter the signature.
![default](https://user-images.githubusercontent.com/28761807/43452263-9d01d2da-94e9-11e8-9b46-bc70e816ddfc.png)
IN ADDITION, when I view Electrum(version 3.2.2) source code, I notice that code convert TYPE_SCRIPT(one of output type) into PAYTOOPRETURN, and when I view Trezorlib source code, I notice that has different type, such as PAYTOADDRESS, PAYTOSCRIPTHASH, PAYTOMULTISIG, PAYTOOPRETURN, PAYTOWITNESS, PAYTOP2SHWITNESS, the same Script I typed,
without Trezor, I just use Electrum, this Script can be signed and broadcast. So, I am confused why Trezor cannot sign my Script successfully.

**Comment by SomberNight** [comment]
thanks for reporting

**Comment by TuoUP** [comment]
@SomberNight Hello, after I fixed this bug followed your step, There appears a new problem, I try to make the sign, but when I finish sign, on Trezor, it has finished confirming To Send Who and Transaction Fee, Then, I find I can not broadcast(the broadcast bottom is unable to click)
![default](https://user-images.githubusercontent.com/28761807/43456075-a639f58e-94f4-11e8-8c4f-0803551b1d08.png)

**Comment by SomberNight** [comment]
I've pushed another commit c9c8b7656d3ceb5d4d26ae443cb2ad5eaab064d0
Try again with that.
In the payto field in the send tab, write `OP_RETURN deadbeef`
