### ISSUE TITLE
ModuleNotFoundError: The module PyQt5 could not be found

### ISSUE THREAD

**Issue by ej-unos** [spesmilo/electrum#4592]
Using a vanilla install of Ubuntu 18.04 Desktop Edition and downloading the latest stable version of electrum and following all instructions to run the software results in the error: ModuleNotFoundError along with something about PyQt5.sip not being found. I've spent too much of my life trying to google the error and fix it, to no avail. Your assistance if GREATLY appreciated, since I cannot restore my BTC wallet until I can get Electrum up and running.

**Comment by SomberNight** [comment]
What instructions are you following? Exact steps you are doing would be nice.
How did you install pyqt?

In a python3 interpreter, what does the following print?
```
from PyQt5.QtCore import QT_VERSION_STR
from PyQt5.Qt import PYQT_VERSION_STR
from sip import SIP_VERSION_STR
print("Qt version:", QT_VERSION_STR)
print("SIP version:", SIP_VERSION_STR)
print("PyQt version:", PYQT_VERSION_STR)
```

**Comment by SomberNight** [comment]
Also, what does this print?
```
sudo apt-cache policy python3-pyqt5
```
And also this (if any)?
```
python3 -m pip show pyqt5
```
