### ISSUE TITLE
how do i send from multisig wallet?

### ISSUE THREAD

**Issue by farzher** [spesmilo/electrum#4593]
electrum v3.2.1 android.

i have a 2of2 segwit wallet, when i try to pay someone it just gives a popup with a bunch of nonsense that i can't do anything with. what?

![image](https://user-images.githubusercontent.com/1005136/43432667-0a8e0132-9442-11e8-921b-bd7ecd0b9f83.png)

**Comment by farzher** [comment]
nvm, restarting the app fixed it. some kind of temporary bug.

**Comment by SomberNight** [comment]
will try to reproduce later

**Comment by SomberNight** [comment]
(the interesting part of the long error message is at the beginning; should we truncate the end?)

**Comment by SomberNight** [comment]
could not reproduce so far.

**Comment by farzher** [comment]
i think it was actually because i sent 1 satoshi! (bitcoin's minimum transaction is 547).
it just doesn't give a proper error message.

**Comment by SomberNight** [comment]
Oh yes, indeed, that is below the dust limit.
The error is coming from bitcoind, we simply display it, but indeed it is unusable on your pic. I've added a commit so that we truncate it, that should be better.
