### ISSUE TITLE
Seed option is greyed out

### ISSUE THREAD

**Issue by westonal** [spesmilo/electrum#4602]
Firstly, I've seen: #2445

Electrum: 3.2.2 

I've been trying to try the revealer.cc plug-in, which requires you to get to the "seed dialog" (https://revealer.cc/how-to-use/).

No matter how I set up a wallet however (e.g: Create wallet: Create a new seed), all I seem to get is a greyed out "Seed" menu option.

![image](https://user-images.githubusercontent.com/6041352/43547778-a507d794-95b2-11e8-8fa7-a927e480d24c.png)

Can you tell me in what situation the Seed option is available in the menu, or how to otherwise get to the "seed dialog"?

**Comment by SomberNight** [comment]
Hmm. This sounds hard to believe.
Try creating a new wallet. In the Install Wizard, 
- select `Standard Wallet`
- select `Create a new seed`
- select `Segwit`
- copy seed words
- type in seed words
- set password

For this new wallet, is the `Seed` option still greyed out?

**Comment by westonal** [comment]
Right, I did not set a password. That is the difference.

**Comment by SomberNight** [comment]
Whaat? :) Following the same steps except leaving the password empty should also work.

**Comment by westonal** [comment]
Oh yeah.

OK. Well I have reproduction steps:

- New/Restore
![image](https://user-images.githubusercontent.com/6041352/43581355-0367577a-962f-11e8-93cc-a1b333c19a3a.png)
![image](https://user-images.githubusercontent.com/6041352/43581362-09e3bb5c-962f-11e8-81d0-f5d546a17086.png)
![image](https://user-images.githubusercontent.com/6041352/43581366-0eddfa64-962f-11e8-9e85-2617c89d208a.png)
![image](https://user-images.githubusercontent.com/6041352/43581434-4e2c1912-962f-11e8-9f6f-26c3396c14f9.png)
Thats: `reform merit notable carry siege devote label crystal aunt remove wire vault`
![image](https://user-images.githubusercontent.com/6041352/43581452-627ff97e-962f-11e8-8f4e-dab0b9f0c87c.png)
![image](https://user-images.githubusercontent.com/6041352/43581460-6845c6e0-962f-11e8-86aa-5a3f0361bcb3.png)
![image](https://user-images.githubusercontent.com/6041352/43581471-703081a6-962f-11e8-83cb-ca5e17a1471d.png)

**Comment by SomberNight** [comment]
Oh yes, indeed! We don't store BIP39 seeds. The difference was not in whether the wallet is passworded or not; it's whether you use an Electrum seed or a BIP39 seed.

**Comment by westonal** [comment]
> We don't store BIP39 seeds.

eh? This says that they can be imported, just not generated.

![image](https://user-images.githubusercontent.com/6041352/43586669-952e682e-963e-11e8-8b3e-38c1d9c4de70.png)

**Comment by SomberNight** [comment]
Yes, they can be imported. But what actually happens is we calculate a master private key from the seed words, store the master private key, and discard the seed words. If you want to suggest otherwise, do so, in another issue. :)

**Comment by sunknudsen** [comment]
Hey @SomberNight, relating to the following.

> If you want to suggest otherwise, do so, in another issue. :)

If one has a paper backup of BIP39 seed used to create Electrum wallet (and BIP39 seed was extended using custom words), how would one go about verifying its integrity given seed is greyed out?

Also, is there a reference implementation of Electrum’s seed generation algorithm (ideally written in Python)?

Looking for Electrum’s equivalent to Trezor’s [python-mnemonic](https://github.com/trezor/python-mnemonic).

Thanks for Electrum btw!
