### ISSUE TITLE
create transaction and boardcast it 

### ISSUE THREAD

**Issue by lightlizm** [spesmilo/electrum#4603]
**1、 My wallet balance is 0.00001322 BTC** 
      **Run command :  electrum payto  1LD8RhaV5hPS37HQY5mUJw3vDzHT22ie91  0.00000010**
      it return :  
{
    "complete": true,
    "final": false,
    "hex": "010000000148ddbf70aaf41b0caeb43cff2c24f2c56fafc67451844b3d5ed12770f2baf42e000000006a4730440220260e1dbdb5a9e6bc4a784a7780257831c52f5890f3cf83aae06ee8fa6943f75702203fc8c36fff0953a14bba422bf0d79fcc328ff6b99147c4b8c014fda9c9c53c360121020e4f919bf3c3b5c00a201f365b6957633bcf0610bdd4da4add79114a6e78e363fdffffff020a000000000000001976a914d2b59489a1de887267ce6e88e3d72a776ef66c8888ac7a020000000000001976a914b4cb5ae4bd09aa1bd81d40ab97ab9b8c935aad4988ac24290800"
}

Transaction is created.

2、**Run Command :  electrum  broadcast  "010000000148ddbf70aaf41b0caeb43cff2c24f2c56fafc67451844b3d5ed12770f2baf42e000000006a4730440220260e1dbdb5a9e6bc4a784a7780257831c52f5890f3cf83aae06ee8fa6943f75702203fc8c36fff0953a14bba422bf0d79fcc328ff6b99147c4b8c014fda9c9c53c360121020e4f919bf3c3b5c00a201f365b6957633bcf0610bdd4da4add79114a6e78e363fdffffff020a000000000000001976a914d2b59489a1de887267ce6e88e3d72a776ef66c8888ac7a020000000000001976a914b4cb5ae4bd09aa1bd81d40ab97ab9b8c935aad4988ac24290800"**

it return 
msg=[
    false,
    "error: {'code': 1, 'message': 'the transaction was rejected by network rules.\\n\\n64: dust\\n[010000000148ddbf70aaf41b0caeb43cff2c24f2c56fafc67451844b3d5ed12770f2baf42e000000006b48304502210082294fb4ea48fd37ce782dba72a2bd9677c746f4894b528f5115bdef266e280d022065aace10d758631980995135658e883adced6b6540420b7f7fc911936f47b0c70121020e4f919bf3c3b5c00a201f365b6957633bcf0610bdd4da4add79114a6e78e363fdffffff0201000000000000001976a914d2b59489a1de887267ce6e88e3d72a776ef66c8888ac83020000000000001976a914b4cb5ae4bd09aa1bd81d40ab97ab9b8c935aad4988ac23290800]'}"
]

broadcast transaction is error.

It can create a transaction why  broadcast  is error? 
what is  "the transaction was rejected by network rules."? have a detailed description?
Thanks a lot.

**Comment by SomberNight** [comment]
The reason is there: `the transaction was rejected by network rules.\n\n64: dust\n`
It's dust. Too small output.
With default settings, mainnet bitcoin nodes will only relay transactions if each output is at least ~546 satoshis.
This does not have much to do with Electrum, this is base layer Bitcoin.
