### ISSUE TITLE
problemas com fundos

### ISSUE THREAD

**Issue by rdianini** [spesmilo/electrum#4604]
boa tarde, transferi minha carteira blockchain para a electrum, mas todo o meu fundo foi como watch-only. Como sou novata não sei como fazer para usar meus fundos. Na carteira diz que é para colocar a seed ou chave privada..mas de qual da electrum ou da blockchain, completamente perdida..obrigado

**Comment by rdianini** [comment]
obrigado mas qual chave..da blockchain ou electrum

**Comment by rdianini** [comment]
poderia me dizer passo a passo, por favor, obrigado

**Comment by SomberNight** [comment]
It's hard to understand the situation.
You cannot change a watch-only wallet into a non-watch-only one. You need to restore from your seed words. Start creating a new wallet in Electrum, and select `I already have a seed`, and enter your seed words there.

**Comment by rdianini** [comment]
Muito obrigado pela dica, vou fazer isso..Deus abençoe

**Comment by SomberNight** [comment]
Closing; nothing else to add.
