### ISSUE TITLE
Request to make Electrum Poratble detect private Nodes / servers directly

### ISSUE THREAD

**Issue by juanpc2018** [spesmilo/electrum#4608]
Problem is: that Electrum Portable Wallet & mutations Need a 3rd Party Dedicated Server...
does Not work directly with an Official Node Wallet.
when the 3rd Party dedicated server is Offline, the coins are Unavailable, in Limbo.
for example: BCD Only has 1 server.

setting a 3rd Party Dedicated Server becomes inefficient,
Trusting an unknown 3rd Party server becomes a liability / risk.

with MoneroXMR can be done, using Daemon as a Private Server + monerujo or cake for Android or iOS in a private Network or a public IP with Open Ports.

with MultiDoge for DOGE coin has its own Private Prune Server, that connects to Real Nodes.

Related: 
[https://github.com/kyuupichan/electrumx/issues/549](url)
[https://github.com/eveybcd/electrumx/blob/master/docs/HOWTO.rst](url)
[https://github.com/eveybcd/electrumx/issues/3](url)

**Comment by SomberNight** [comment]
> Problem is: that Electrum Portable Wallet & mutations Need a 3rd Party Dedicated Server...
does Not work directly with an Official Node Wallet.

This is how Electrum works. The whole architecture is based on "Electrum servers" that speak the "Electrum protocol" that act as a bridge between the client and bitcoind. This is why Electrum can be a "light client".

> for example: BCD Only has 1 server.

If you care enough, run your own server then. What really matters is Bitcoin.

If you are concerned about resources (disk space, RAM, etc), have a look at [Electrum Personal Server](https://github.com/chris-belcher/electrum-personal-server).

I'm closing this as
- it's not exactly clear what your proposed change is
- it's likely out of scope for the project

**Comment by juanpc2018** [comment]
take a look at MoneroXMR Monerujo Wallet for Android &/or CAKE Wallet for iOS11,
Light Wallet/Client implementation is much better.
No need for Bridges...
Light Client works directly on the Network...

i dont see the advantage or having a parallel network/servers with bridges...

but if the parallel server becomes Offline, the coins become a Zombi in Limbo... LOL. Jajajaja
