### ISSUE TITLE
No module named 'xmlrpclib'. Try 'sudo pip install <module-name>'

### ISSUE THREAD

**Issue by kmonarch** [spesmilo/electrum#4610]
When I run_electrum in Mac, there is always this error,please help me to resolve it! Thanks

**Comment by SomberNight** [comment]
How did you install Electrum?
If you run from source, you need to manually install the dependencies https://github.com/spesmilo/electrum#getting-started

**Comment by ysangkok** [comment]
please reopen if you encounter this. closing cause it's so old now and we had no feedback
