### ISSUE TITLE
[Android] App and app icon randomly becomes dysfunctional/disappears from menu

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#4612]
Android version (website APK)
The latest disappearance was spotted with 3.1.3, but it's been happening ever since I started to use Electrum on Android (from Electrum ~2.7?)
[For what it's worth](https://github.com/spesmilo/electrum/issues/3586), it's a Sony device.

Ever since I've been using Electrum on Android, from time to time one of the following happened to the app icon in the app menu, in a seemingly random manner (= I'm unable to see a pattern or causes). I post it here because I use a bunch of other apps, but this is the only one where I've ever seen such behavior.

* App icon is grayed out/replaced with default app icon, a small red memory card icon is overlaid in the corner. Tapping on it displays a small error message (can't remember the text, maybe "App not found"?). This may have something to do with the fact that  the app is installed on the memory card. However, I have many other apps installed on the SD card, both from official APK builds, the F-Droid store and "pirate" APKs from the Play Store -- none of them ever had this problem. Also, my SD card has always been working flawlessly.
* App icon replaced with default app icon or no icon at all, a small red memory card icon is overlaid in the corner, and the item has no name, thus it's at the beginning of the list. Tapping on it displays the same error message.
* App icon is completely gone from the app menu.

In all three cases, Electrum was still on the list of the installed applications. After overwriting the present installation with a new one (or in other words, upgrading, when it was a new version), the icon was wholly restored and I could continue to use Electrum without any loss of data.

Why does this happen?

**Comment by HardCorePawn** [comment]
Sounds like an issue with your Android device... where it isn't able to find the items on your memory card during the Launcher startup... possibly due to a "slow" memory card?

I have the same issue with LineageOS on my old Galaxy S5 and a slow "class 4" card... after a restart, i'll often find a bunch of greyed out icons. Reloading "Nova Launcher" will then show them OK.

What launcher are you using? and are you able to restart it?

**Comment by leafcutterant** [comment]
This was probably a device/config-specific bug, closing.
