### ISSUE TITLE
[Android] Asking for PIN was skipped after Electrum was updated and opened

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#4613]
Happened while updating 3.1.3 to 3.2.2.0.

Related to #4612.

After the app icon completely disappeared from the app menu and I did an update in order to bring it back, as described in #4612, I pressed "Open app" right from the installer after it finished. I was taken right to the main screen (transaction history) of the default_wallet. That wallet is protected by a maximum length PIN and, as usual, the PIN should be required even just to see the history, but this time I somehow glitched myself through it. A bit disturbing.

Why did this happen?

How could this happen — isn't the wallet completely encrypted with all its parts, as in the desktop version? If not, why not?

**Comment by SomberNight** [comment]
> isn't the wallet completely encrypted with all its parts, as in the desktop version? 

No. On Android, currently only the keystore is encrypted (same as in desktop when you disable wallet file encryption). The password prompt when you open the app is just a simple dialog; it might be possible to "glitch" through it.

I'll look into encrypting the whole file though, as that would be better. We will need to bundle pycryptodome in the apk, as the pure python pyaes would be too slow.

**Comment by SomberNight** [comment]
This is now done in https://github.com/spesmilo/electrum/commit/02baae10d75f5ea95eb3096b17556a2d371f0113 and https://github.com/spesmilo/electrum/commit/9b28f6df7beab821422537f816cbacbe6035f706
