### ISSUE TITLE
electrum: error: unrecognized arguments for signrawtransaction

### ISSUE THREAD

**Issue by bellaj** [spesmilo/electrum#4614]
I am trying to sign a raw transaction (created by Bitcoin core) as following:

`electrum -w .electrum/testnet/wallets/default_wallet signrawtransaction "0200000001df2782386203fef56489a8e694a7089d9ab1143b073a5fa128a2adbebf39af460100000000ffffffff0200000000000000000d6a0b68656c6c6f20776f726c64005a62020000000017a914eb949dbde8d3b1755e7f3c20b6a62c1f1403bd908700000000" '[{"txid":"46af39bfbeada228a15f3a073b14b19a9d08a794e6a88964f5fe0362388227df","vout":1,"scriptPubKey":"76a91432d75cdddbdd1f406c2c717f9a7e97e774683fcf88ac","redeemScript":""}]' '["cN4AguKj3xQitaS2qwrXZJzzRuG2m8BoUjEm8vUnauD3qtPekiRW"]'`

I am getting:

**electrum: error: unrecognized arguments:** 
`0200000001df2782386203fef56489a8e694a7089d9ab1143b073a5fa128a2adbebf39af460100000000ffffffff0200000000000000000d6a0b68656c6c6f20776f726c64005a62020000000017a914eb949dbde8d3b1755e7f3c20b6a62c1f1403bd908700000000 [{"txid":"46af39bfbeada228a15f3a073b14b19a9d08a794e6a88964f5fe0362388227df","vout":1,"scriptPubKey":"76a91432d75cdddbdd1f406c2c717f9a7e97e774683fcf88ac","redeemScript":""}] ["cN4AguKj3xQitaS2qwrXZJzzRuG2m8BoUjEm8vUnauD3qtPekiRW"]`

any clue?

**Comment by SomberNight** [comment]
`signrequest` expects an address.

You probably want `signtransaction`

**Comment by bellaj** [comment]
sorry @SomberNight it was i typo i was using signrawtransaction

**Comment by bellaj** [comment]
thanks for the replay

I've created it using bitcoin core as following:

`bitcoin-cli createrawtransaction "[{\"txid\":\"0791521362528725683caedf998006cf68b1cd817be1694ef0daca265d9b4252\", \"vout\": 1}]" "{\"data\":\"68656c6c6f20776f726c64\",\"2MsHsi4CHXsaNZSq5krnrpP4WShNgtuRa9U\":1.0000000}"`

**Comment by SomberNight** [comment]
The partial transaction format of Electrum and Bitcoin Core is not compatible.
See https://github.com/spesmilo/electrum/issues/4514

**Comment by bellaj** [comment]
can i create raw transaction using electrum directly? i can't find any guide in the official documentation

**Comment by SomberNight** [comment]
Try something like:
```
electrum --testnet \
-w /home/user/.electrum/testnet/wallets/default_wallet \
paytomany '[["tb1qafjlz96pp60vty408mlu4phlv39ug3tasfhu4f", 0.0025],["tb1qdcuuuznxm2ed94m5rlccv30ycf28d4uyd58wyu", 0.007]]' \
--fee 0.0001 --unsigned
```
(or without `unsigned` if the wallet has keys as well)

Btw if you don't necessarily need CLI/RPC, the GUI should be easy to use for these kind of things too.

**Comment by bellaj** [comment]
Thanks @SomberNight this is much helpful. 
what if i want to create an **op_return output**

**Comment by SomberNight** [comment]
That's currently only supported in the GUI. See e.g. https://github.com/spesmilo/electrum/issues/4547
