### ISSUE TITLE
How can I improve Russian transaltion?

### ISSUE THREAD

**Issue by un1t** [spesmilo/electrum#4617]
Hi!

There many texts without russian translation.
I did try to find .po files, but I find out those files are downloaded from crowdin.com site.

How can I improve translation? May I change .po file and post it somewhere. Or could I get access to this site?

**Comment by bauerj** [comment]
Hey @un1t 

You're absolutely right, the Russian translation is missing a lot of strings.

Anyone can help translating, without any special permssion from us:
1. Go to https://crowdin.com/translate/electrum/68/en-ru
2. It will ask you to login, just select the Github option below
3. Once you're logged in with Github, you can start translating right away!

If you have any further questions, let me know.

**Comment by un1t** [comment]
Ok. I translated few main screens.

I notice this sentense was translated a year ago "Leave this field empty if you want to disable encryption.". But I see english text in program. Why is so?

**Comment by bauerj** [comment]
You're right, this is a bug. It is being tracked in #4621 and will probably be fixed in the next release.

Thanks for working on the translation. I close this issue since it seems like it works for you.
