### ISSUE TITLE
Support importing of account-depth xpub

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#4625]
I'm trying to create a multisig p2wsh-p2sh wallet where one of the cosigners provides a 3rd level (account) xpub but it seems that electrum does not notice that this is a child xpub and just assumes it's a master xpub.

In the example I'm testing using a upub derived at m/49/1/61 and the desired behavior is that the addresses should be derived starting from m/49/1/61/0/0 but the resulting addresses being generated seem to indicate that they are being derived from m/49/1/0/0/0

**Comment by SomberNight** [comment]
I am not sure I understand but it seems to work for me.

2-of-2 p2wsh-p2sh (testnet)
```
(BIP39)
cabbage dose bring match soda amount success debris voice unaware august duck
m/49'/1'/99'
Upub5Q6Lg5qRTbVo7JwBiugYE3HwVQNU3qRtzPj2CpRn7FhmbYoxDt1ASA1n4Jf8sj21PQ4xeyWiuoHg3KKrDjBuhjCScHyujXDrHNwzWnCJHAZ

(BIP39)
scrap denial truth employ language planet obvious grow genre inch usual impose
m/49'/1'/99'
Upub5RFzDnGiA1tJ95sexPmv5J1dtcpVSyax6ENgxp4Y7MRjpHgwPT7JpLMeMaKkghMueQBZswwuL2nA4t5phP1QvyPuJvtbBQeF4fSxEwUEXtu
```

The two pubkeys for the first receiving address (at `m/49'/1'/99'/0/0`)
```
03cb64ee811c4b4ab687f5e4229cf14654b38e287e639f2fcf6942bce82bb21f01
03999f7320195e4f0a58c64369a1bef41553db018d5ed0dca755bbcbf36dbb9df3
```

and the address is `2MyanzGKyLJzfPEf6zFYfpjHgDZencTn7oS`.
Is this not what you expect?

**Comment by dabura667** [comment]
I also can not reproduce the issue... could you give us a detailed repro step-by-step using garbage keys with nothing on them?

**Comment by jlopp** [comment]
Actually I think this is an issue with unhardened derivation; will close and open a different issue with more details and questions.
