### ISSUE TITLE
Trezor wallets fail to sign segwit inputs when using custom derivation path

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#4626]
I've created a 3-of-5 multisig p2wsh-p2sh wallet with 3 trezors as cosigners. I found the signing to be very finicky if I plugged and unplugged the trezors while signing, so I have plugged in all 3 simultaneously so that I can successfully sign from them all without getting pairing errors.

However, after signing with the third trezor it pops up a new "Transaction" window that says the status is Unsigned. The "Broadcast" button is greyed out. Meanwhile, if I click "sign" it just walks me through signing with all 3 trezors again and then comes back to this window.

Here's the debug output while running in verbose mode - I don't see any errors logged:

```
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
[DeviceMgr] getting client for keystore
[DeviceMgr] scanning devices...
[DeviceMgr] end client for keystore
[Network] network: retrying connections
[hsmithsxurybd7uh.onion] cannot resolve hostname
[testnet1.bauerj.eu] failed to connect [Errno 101] Network is unreachable
[electrumx.kekku.li] cannot resolve hostname
[profiler] estimated_size 0.0006
```

**Comment by jlopp** [comment]
Not sure if this will be helpful, but here's the hex that Electrum is giving to me:

```
45505446ff0001000000000101398b306687d77fc2126396e511bd4bc4a7de6d441cdf3e0ca3ea3e1b3c3959a50000000023220020197a2c8272cf10019c714b5249da398b0806ce7da06a1ab35c0fe1add14aef0bfdffffff01da5af505000000001976a91445fdf37f4d3ba3e7cb877cac89a1ad244aacddce88acfeffffffff00e1f505000000000000070001ff01ff01ff01ff01fffdac01534c53ff024289ef038559a37c00000000e64501ae48cc232b863c5dd7300de8e1380c835f53d45118354a718807b37ad502814213ae6832cf6e189f39caed71d5cd9b3f75bb58fd828c800cd10313b97cac000000004c53ff024289ef039f64a9e400000000f28767a166f27def9971e14f53d669c9125d9fa84648af71780558ee005b4a6c022e742e94fe44754866d28b3e1a50fdadc2d976abc7c1798a665c47cc40b8c284000000004c53ff024289ef0315b06ac300000000409560284299d49dc850917f45349c67c44f178222c8e2af0f3b4248eb0eb38002fd5a410463f4e02fb561df6ef69ead6349cf7ad14922c7fdd1c9cd5cc4e065fe000000004c53ff024289ef031b0c28860000000098ba5d3d43eeaff041596e6efd3d82a71f6e089425fe43f9f83db465dcbb9e8602087df82032382ae3c50e941d1dd14b563886e7290ecf3fd955770a3a392b7def000000004c53ff024289ef0347ea5d210000003d1c2adf56f3ac3f23ef2dbdc47b740b4c222b35c53003492cfe56ab6b725ed0e90313728878ea43ecff728cc3f48ac33f3c109971f08424e7bea1f61ea1c74aeef30000000055ae461c1500
```

When I try to decode it:
```
{
    "error": "sequence too long"
}
```

**Comment by SomberNight** [comment]
I could not reproduce so far :/
Are you testing on 3.2.2 or master? On Linux?

> the hex that Electrum is giving to me

That is Electrum's custom partial txn format, so deserialising it with tools that expect network serialisation will not work.

In the `Send` tab, from what you wrote I assume you are clicking `Send` initially. Try clicking `Preview` instead -- that will show the `Transaction` window right away.
Disconnect all hardware wallets, except for one, and click `Sign`. Try signing with only this one cosigner; when prompted, don't try to connect to the other hardware wallets. What is the status of the transaction after this? (should be `Partially signed (1/3)`)

It would be nice to narrow down the issue; can you try testing other setups?
- does standard p2pkh with a single trezor work?
- 2of2 p2wsh-p2sh with trezors?

**Comment by SomberNight** [comment]
Ok, I can reproduce. It's to do with the derivation; I've been testing with defaults.
The Trezor plugin code is using the derivation to guess the script type.

**Comment by SomberNight** [comment]
Thanks for the report -- hopefully it will work now :)

**Comment by jlopp** [comment]
Success! Signed with 3 trezors: https://www.blocktrail.com/tBTC/tx/7ac5932209a5521a7562a196a2a9aae0786beeb8d13c0a1e9a9dc0869ab5fb67

Thanks for getting this patched so quickly
