### ISSUE TITLE
Command line: Taking fee out of sending amount

### ISSUE THREAD

**Issue by CodeForcer** [spesmilo/electrum#4632]
I'm using Electrum command line to sweep a large amount of cold deposit addresses into a central address, preparing unsigned transactions on online computer, and then signing on cold computer.

On the online computer I cannot take the fee out of the transaction amount. Trying to send the entire amount, for example:
```
electrum payto -F muaHScHmNmSdJGe9ZWoAjvGFfGvZUoy9sr mmQBaD65JYWEzQFPfY3uBigb6LswquJ1ZM 150000 --unsigned --testnet
```
...results in a 'not enough funds error'.

How can I use Electrum command line to programmatically prepare unsigned transactions with the fee amount taken from total amount, so each address is left empty after sweeping?

**Comment by AbdussamadA** [comment]
an exclamation point in place of the amount should do it: http://docs.electrum.org/en/latest/cmdline.html#magic-words

**Comment by AbdussamadA** [comment]
plz close the issue since it is resolved.
