### ISSUE TITLE
how electrum use UTXO from different address?

### ISSUE THREAD

**Issue by toknT** [spesmilo/electrum#4640]
can anyone explain how electrum use UTXO from different address? 

if the privatekeys are belong to different address, the raw tx hex broadcaset into my regtest network will return `script failed an OP_EQUALVERIFY`.

**Comment by SomberNight** [comment]
Please try to provide instructions to reproduce the error, as your question in itself is unclear.

**Comment by toknT** [comment]
@SomberNight it`s not a error,  there are 2 utxo from 2 different address in the [transaction in testnet i created](https://www.blocktrail.com/tBTC/tx/1d3e75d5198c0b9b54a2f23ffccd0a3dc42dfced6d43b4460f16b55226cd0d65),electrum work well . 

But if I do the samething in my wallet(writed by php) it goes `script failed an OP_EQUALVERIFY`, (my code in php can deal many inputs to many outputs successfully if the UTXO of inputs are in a same address).

I just **don`t understand why electrum can do it (UTXO from many different addresses) successfully?**(I am a begginer of bitcoin/blockchain)

**Comment by toknT** [comment]
It's my mistake sorry, I get wrong private key to sign.
