### ISSUE TITLE
Windows 7 64bit > Portable versions 3.2.* > CANNOT START PROPERLY

### ISSUE THREAD

**Issue by digital-outsider** [spesmilo/electrum#4641]
Houston, we have a problem.
After upgrading to 3.2 version, the portable exe, keeps running in background without starting the GUI.
I can see the process in windows activity management panel ... but nothing happens.
I've tried with all 3 versions ( 3.2.0\1\2 ) also installing the KB2999226 update as suggested.

![windows activity](https://user-images.githubusercontent.com/42490251/44297940-404a9500-a2da-11e8-9f4d-191f405f08e9.jpg)

**The big problem is that upgrade also modify wallet data so i cannot downgrade to 3.1.3** !!!
You need to fix this asap.
THANKS

* Attached you find also a dump of the process.

[electrum-3.2.1-portable-DUMP.zip](https://github.com/spesmilo/electrum/files/2299324/electrum-3.2.1-portable-DUMP.zip)

**Comment by SomberNight** [comment]
> The big problem is that upgrade also modify wallet data so i cannot downgrade to 3.1.3 !!!

You can always just restore from your seed words.

Also, the upgrade does not happen without GUI interaction (even if your wallet does not have a password, before an upgrade, the wizard gets displayed, and you need to click "Next"). Hence, I don't understand how your wallet could have upgraded if the GUI does not even appear -- or did that window appear?

What version of Electrum were you using before?

If I built a custom binary for you that printed some debug logs, would you be willing to run that?

**Comment by SomberNight** [comment]
Ok, try with this binary then. It should open an additional window with debug logs while running.

[electrum-3.2.2-debug-portable.exe.zip](https://github.com/spesmilo/electrum/files/2299397/electrum-3.2.2-debug-portable.exe.zip)
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

8a13a224523845172c3cc6446a6879c5b55931f37cde846e7527561b8d219775	electrum-3.2.2-debug-portable.exe
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEbXohFtqQngCsIRCLsztfIyxicekFAlt3+HIACgkQsztfIyxi
celxDw/+M1uZkpnygN55vVlO3/Ze5D2YXAgiao0JXX67UMQbeDTIpgsyJmC7QAwh
DSYUNMh165Ywo3nWXj87cQw7q0d11T2EQvnhMfjwmGre4w1zjDvW2nlEA2vuMCF/
L2qNjfKNGDpf3JuQkiuCm5K4J9TZnwNtI5QXyE74kKHOAb0UC7XGP/ZwP5mg8doQ
XlnQ7LfJfn+7quBoC5A/30ncPP557iz/RGdviq2ip9FVlhL4tW4YBcOdj0eL7yan
+GL3Q2NUbTaXtdqI67m69SPymrImLG0cpLsud9reZTlFVaMwnyMHTfkgFOmkyEqq
PZNnx/FLXwvIJ7rsDFPxxZPMp+VGVhp8wMmJKe9/8m9g4Fe8+sFZFml8Gg0SvNhD
KKTylRyeDD7kdREEd2f5FRatLU+IU9jdGD51FDTj+RU/+IlJ+NleOk/srdJaSWVW
OPYJmixrp9EOmDghSDpjmtTvheB+N0IYAqCbOmbj4/wYEiyVK0+lkMp4S0xVDcUL
6uMACakjnhQe/LreIP7GHKjuwicM7Czsja7AQWqR3y/AnSnWlV6sX1PCLw9YQ2td
WKNvFsZ+8tConBb2GHAnkCO6XSjb48/9tJqk4roB8ui0b9Q5UcC422aOUHotHZ/e
Yzj5jEwo5ify2ApHos036JpHi0jaxeaFurGpCCnSsxgPXU62hDU=
=W+da
-----END PGP SIGNATURE-----
```

**Comment by digital-outsider** [comment]
In the meantime I've tried also on WIN 10 64bit ... and same problem.

![win 10](https://user-images.githubusercontent.com/42490251/44299293-692b5400-a2f3-11e8-8fce-b986acbd090b.jpg)

**Comment by digital-outsider** [comment]
OK, let me know if the debug revealed you something.

**Comment by SomberNight** [comment]
There's nothing interesting in the logs, which is not that surprising given you've said that it works.
What is surprising though is that it works -- there should be no significant difference between the official binary and this one.

Can you confirm that it the official binary (3.2.2 portable exe) still does not work (GUI does not show up), but this custom one does?

**Comment by SomberNight** [comment]
closing, probably outdated and not applicable anymore
