### ISSUE TITLE
Electrum setconfig server randomly

### ISSUE THREAD

**Issue by aghamir** [spesmilo/electrum#4644]
Hi,
I used Electrum on Ubuntu server. So I don't want to use GUI. However, I faced an issue that when server does not set in config, electrum daemon [methods such as status, load_wallet] does not work as well. Is there any possiblity that set server config as pick server randomly?
Thanks a lot

**Comment by aghamir** [comment]
I think `"auto_connect": true,` is for this purpose. Sorry I didn't find that in other issues. So you can close this issue.

**Comment by aghamir** [comment]
I'm getting exception.
```
/opt/electrum/electrum-master# ./run_electrum --testnet daemon start
[ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
starting daemon (PID 9408)
/opt/electrum/electrum-master# ./run_electrum --testnet daemon stop -v
[ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
[SimpleConfig] electrum directory /root/.electrum/testnet
[get_server] unexpected EOF while parsing (<unknown>, line 0)
Daemon not running
```

**Comment by ecdsa** [comment]
closing: this issue is deprecated, the code changed too much
