### ISSUE TITLE
Distribute source code using .tar.xz archives

### ISSUE THREAD

**Issue by ghost** [spesmilo/electrum#4645]
Currently Electrum source code is distributed using .tar.gz archives. In my opinion Electrum should use .tar.xz archives instead.

On my system:

    $ du -k Electrum-3.2.2.tar.??
    5488    Electrum-3.2.2.tar.gz
    3924    Electrum-3.2.2.tar.xz

By using the XZ format we can save about 29% of disk space and bandwidth.

What do you think?

**Comment by SomberNight** [comment]
See discussion in https://github.com/spesmilo/electrum/pull/5465.
TL;DR: the files aren't large in either case, `tar.gz` might be better supported, and it's extra complexity (/potential maintenance) to add a new format.
