### ISSUE TITLE
Not enough funds error doesn't fail gracefully

### ISSUE THREAD

**Issue by CodeForcer** [spesmilo/electrum#4646]
When I'm using Electrum command line programmatically, trying to 'payto' an address when I don't have enough funds causes the program to crash and return a traceback.

Is it possible to have Electrum fail gracefully in this situation, perhaps with a concise error message?

The problem is I'm running Electrum from other Python scripts using Check_output from Subprocess module and Electrum returning a traceback causes an exception.

**Comment by ecdsa** [comment]
fixed now.

**Comment by CodeForcer** [comment]
Wow, thanks!
