### ISSUE TITLE
only ssl servers allowed?

### ISSUE THREAD

**Issue by nkostoulas** [spesmilo/electrum#4650]
Hello

with how the following method works:

```
def pick_random_server(hostmap = None, protocol = 's', exclude_set = set()):
    if hostmap is None:
        hostmap = constants.net.DEFAULT_SERVERS
    eligible = list(set(filter_protocol(hostmap, protocol)) - exclude_set)
    return random.choice(eligible) if eligible else None
```
Are only servers with specified SSL_PORT allowed? Shouldn't this default to a TCP server if no 's' parameter is found in servers.json?

Thanks,
Nikos

**Comment by SomberNight** [comment]
Yes, the client defaults to connecting only to SSL/TLS servers.
There is no way in the GUI to connect to a plaintext TCP server.

What you can do, which is mainly for debugging purposes, is to use the CLI `-s` or `--server` flag, to specify a server along with protocol, and that can use TCP.
For example, `./run_electrum --testnet -s 127.0.0.1:51001:t`

**Comment by nkostoulas** [comment]
Ah okay good to know thanks! Is there any purpose then for the "t" field in `servers.json` or just deprecated?

**Comment by SomberNight** [comment]
Well if you connect to a TCP server by manually specifying one, the server list will be filtered to that protocol. All the connected servers use the same protocol.

**Comment by nkostoulas** [comment]
Ah yeah right. thanks
