### ISSUE TITLE
[Android] After deleting a wallet, Electrum stays in "No Wallet" mode, wallet selector is strange

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#4654]
3.2.2

As said in the title. It displays "No Wallet". You can try to open another wallet, but the wallet browser is malfunctioning. It looks like it's in an empty folder somewhere in the application data folder, but you can actually go higher in the folder hierarchy and browse where in my opinion you shouldn't be able to go. I eventually found the wallet files and opened one. Opening a wallet this way also bypasses the facade PIN screen for a few minutes,

**Comment by ecdsa** [comment]
closing, this is another instance of #6796
