### ISSUE TITLE
GUI network dialog error (line 459 in set_proxy)

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#4673]
I was testing Electrum 3.1.3 in Tails RC and got an error while playing in the gui.  I know 3.1.3 is not the latest (but it's the latest in stretch-backports which means is the latest we can use in Tails) and I also checked the issue tracker and I did not see this reported / fixed, so thought it's worth it. The automated crash reporter gave me the data but could not send it automatically and told me to report manually. I think this is due to Tails firewall settings.

Steps to reproduce:
1. Launch Electrum GUI while having Tor runninfg.
2. Go to network dialog.
3. Check box for "Use Tor proxy at 9050". Try to uncheck "Use proxy" just below. 
Sometimes it works as it unchecks both boxes automatically (when you uncheck  "Use proxy" it also unchecks automatically "Use Tor Proxy").

```traceback
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/electrum_gui/qt/network_dialog.py", line 459, in set_proxy
    self.network.set_parameters(host, port, protocol, proxy, auto_connect)
  File "/usr/lib/python3/dist-packages/electrum/network.py", line 464, in set_parameters
    self.stop_network()
  File "/usr/lib/python3/dist-packages/electrum/network.py", line 439, in stop_network
    assert not self.interfaces
AssertionError
```
 
Additional information
Electrum version: 3.1.3 
Operating system: Linux-4.17.0-2-amd64-x86_64-with-debian-9.5 
Wallet type: standard 
Locale: en_US

**Comment by SomberNight** [comment]
Looks same as https://github.com/spesmilo/electrum/issues/4029 and https://github.com/spesmilo/electrum/issues/3037
It's a race condition; should already be fixed in later versions.
Does it not happen in 3.0.6? I think it should.
