### ISSUE TITLE
Notifications for users re new versions/updates (in-app/rss/etc?)

### ISSUE THREAD

**Issue by alexis26** [spesmilo/electrum#4680]
Hi,
can you put a rss feed on the website download page https://electrum.org/#download
ty

**Comment by AbdussamadA** [comment]
you can use the github [tags feed](https://github.com/spesmilo/electrum/tags.atom).

**Comment by alexis26** [comment]
i have, but you only have the source, not the "final" version like on website

**Comment by alexis26** [comment]
yes, ty (i know that), but this is not that I ask...

i have putted this wallet at friends who do not understand anything in computer and I would like them to always been up to date (for security). with a rss feed on the download page they would know that there is an update and they must install (for them a soft it's double click on the exe! ...).
(I could do it and send them by mail, but it goes against what I explain to them for security ...)

And honestly I do not think my friends are the only ones; I think that many are not up to date. and therefore, facilitating anything that could improve safety would be welcome ...
(especially in this case where this is simple and would have an impact on many people at the same time ...)

**Comment by SomberNight** [comment]
I think we should add back the feature that checks whether there are new versions/updates. It was removed due to privacy concerns. We can make it opt-in.

**Comment by SomberNight** [comment]
this was done in https://github.com/spesmilo/electrum/pull/4985
