### ISSUE TITLE
Traceback on startup after installing 3.2.3

### ISSUE THREAD

**Issue by NiExTy** [spesmilo/electrum#4687]
After installing 3.2.3 Electrum is not starting anymore, after running it from command line I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 416, in <module>
    plugins = init_plugins(config, config.get('gui', 'qt'))
  File "/usr/local/bin/electrum", line 323, in init_plugins
    from electrum.plugin import Plugins
ImportError: No module named 'electrum.plugin'
```

I noticed output from ```sudo python3 setup.py install``` is different from previous versions, not sure if useful but there it is: https://pastebin.com/raw/9sH8JdCh

**Comment by SomberNight** [comment]
Could you please clarify exactly what commands you are running?

**Comment by NiExTy** [comment]
I am like always:
* Downloading and unpacking `Electrum-3.2.3.tar.gz`
* `cd Electrum-3.2.3` directory
* `sudo python3 setup.py install`

**Comment by NiExTy** [comment]
It works, thank you.
