### ISSUE TITLE
Feature request: Wallet->Information should show HD path

### ISSUE THREAD

**Issue by Talkless** [spesmilo/electrum#4700]
Currently (3.1.3 in Debian Sid), Wallet->Information does not display BIP32 HD derivation path. 

User might have multiple Electrum wallets (HD accounts) using same master seed generated in hardware device (like Ledger Nano S), named `BIP84_short_term_spending` for `m/84'/0'/0'`, or `legacy_hodl` for `m/44'/0'/3`, etc, etc, but there's now way to know which path was used for previously created Electrum wallet, so re-creating that wallet in another computer (or application) is difficult (if HW wallet device is available, but Electrum wallet files are not), as user has to guess, manually document, or remember these paths used for creating that HW-based wallet.

If BIP32 derivation path would be available in Electrum GUI, and if user would know in advance that it will need to "recreate" wallet in another computer (or another application), he could just check HD path in `Wallet->Information` before proceeding.

**Comment by Talkless** [comment]
I guess I could have named wallet files accordingly to paths, but, well, now it's too late :) . Again, this is manual documentation which maybe could be avoided.

**Comment by ecdsa** [comment]
this is a design choice; electrum does not know about your wallet derivation path, it does not keep that information.

**Comment by Talkless** [comment]
I see. I guess I'll try to recall paths and rename wallet files accordingly.

**Comment by Talkless** [comment]
@ecdsa maybe possibility to add arbitrary note to a wallet file would be reasonable?

**Comment by SomberNight** [comment]
It's stored in the keystore, and persisted in the wallet file for hw wallets.
https://github.com/spesmilo/electrum/blob/55b582511e8d1b6d229836a120572ff9375b891b/electrum/base_wizard.py#L353-L360
We might as well do it for generic bip39 seeds too.

**Comment by Talkless** [comment]
> and persisted in the wallet file

I am lost now. @ecdsa said Electrum does not keep that.

**Comment by SomberNight** [comment]
Yes, and I just said it does for hardware wallets. I had to check myself to be sure :P
It's hard to keep track..
For software bip39 seeds, it is not kept. We might as well keep it for those too I think.

**Comment by Talkless** [comment]
OK so my feature requests still holds, at least for HW wallets :) .

**Comment by SomberNight** [comment]
Note: in Qt console:
for non-multisig, or first cosigner in case of multisig:
```
wallet.keystore.derivation
```
multisig:
```
[k.derivation for k in wallet.get_keystores()]
```
(these will raise `AttributeError` for non-hw wallet keystores)

**Comment by SomberNight** [comment]
Looks like to fully cover PSBT usecases we will optionally have full bip32 paths for any kind of bip32-based wallet, in which case we might as well (and will probably need to) show it in the UI.

related:
https://github.com/spesmilo/electrum/issues/5715
https://github.com/spesmilo/electrum/issues/5955

**Comment by SomberNight** [comment]
For newly created wallets (and exisiting hw-keystore wallets), the derivation path is stored but is not atm exposed to the user. In console: `wallet.keystore.get_derivation_prefix()`

**Comment by fresheneesz** [comment]
I want to just add my opinion here that since derivation paths are kind of really important to be able to correctly restore from your seed, the derivation path should be shown alongside your seed and users should be instructed to record it as well. That is, unless we are aiming to have some mechanism to automatically search numerous standard derivation paths so users don't have to write it down.

**Comment by Stadicus** [comment]
+1 to show derivation path in Wallet Information dialog. When creating a multisig wallet with hardware wallets, I need to record the derivation path as crucial information during setup for a proper backup of the overall multisig setup. Otherwise the derivation path is no longer accessible using regular UI options (not counting https://github.com/spesmilo/electrum/issues/4700#issuecomment-426330978)
