### ISSUE TITLE
Billing and authentication for remote watch tower/backup server

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4709]
The watch tower and channel state backup server code will be free and open source software. Electrum, the company, will run some servers, and if the user wants to use those servers, that will be a subscription service. This needs billing and authentication.

Related:
https://github.com/spesmilo/electrum/issues/4707
https://github.com/spesmilo/electrum/issues/4708

**Comment by ecdsa** [comment]
closing, out of scope for now.
our watchtower implementation can be used in a private setup (with password authentication)
