### ISSUE TITLE
LN: mutual cooperative channel close

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4710]
Implement cooperative channel close.

**Comment by SomberNight** [comment]
Indeed, re fees negotiation, at the very least we need to set a reasonable upper bound on the fee.

Further, I believe if we start a mutual close but restart the app before it finishes, the channel gets stuck atm. (and the user will need to force close)
https://github.com/spesmilo/electrum/commit/2a7b5081c911a4679d3fa34469aea786a20d1c61#r37296777

Further, the `shutdown` state needs to be sticky in that the message needs to be resent during channel reestablish.

We really should re-read the spec and review the implementation.

**Comment by ecdsa** [comment]
Note that BOLT2 sets an upper bound: "The sending node MUST set fee_satoshis less than or equal to the base fee of the final commitment transaction [...]"

**Comment by ecdsa** [comment]
I believe this is fixed now. this took many commits.
