### ISSUE TITLE
Possible bug but in ecc.py 

### ISSUE THREAD

**Issue by cculianu** [spesmilo/electrum#4717]
Hi, Electron a cash dev here.

We came across an issue and wanted your input before we went ahead with our fix.

Please see this discussion/issue in Electron Cash and the attached bitcointalk.org discussion.

Apparently the elliptic curve algorithm does some out of spec stuff.

https://github.com/fyookball/electrum/issues/852

It basically returns the wrong points on the curve in some circumstances. See the discussion.

We are thinking of modifying it in Electron cash.. but I was curious what the history/rationale was for this particular implementation and/or if it’s actually supposed to be like that?

Also — in case you wanted to fix this in your codebase let us know and we can issue a PR to you guys too.

Thanks!

**Comment by SomberNight** [comment]
Thanks for pointing this out. Indeed there is an issue with that function.
I don't know why the offset thing is there (1); and the elliptic curve equation is wrong too (2).
Both of these issues are harmless however, without security implications.

(2) is harmless as `a == 0` for this curve (secp256k1).

(1) is harmless as,
the offset will only be non-zero if there is no corresponding `y` for the original `x`. Then, if a `y` is found for the new `x`, that `y`, by the previous statement, cannot possibly be valid for the original `x`. As in, the point `(original_x, returned_y)` will not be on the curve. And this is checked where the function is used:
https://github.com/spesmilo/electrum/blob/f05f3b430aa0d9060ed51f720607a0b012f3ce99/electrum/ecc.py#L119
https://github.com/spesmilo/electrum/blob/f05f3b430aa0d9060ed51f720607a0b012f3ce99/electrum/ecc.py#L122-L127

**Comment by cculianu** [comment]
Ok, thanks for the explanation. :)
