### ISSUE TITLE
Error: No module named 'aiorpcx'

### ISSUE THREAD

**Issue by coinsmith** [spesmilo/electrum#4719]
Error when giving the command 

python ./run_electrum 
Error: No module named 'aiorpcx'. Try 'sudo pip install <module-name>'

tried to pip install it, failed with

Collecting aiorpcx
  Could not find a version that satisfies the requirement aiorpcx (from versions: )
No matching distribution found for aiorpcx

python version 3.6, ubuntu 18, 64 bit intel.

**Comment by SomberNight** [comment]
Have you followed the readme?
https://github.com/spesmilo/electrum#development-version
Run `pip3 install .[fast]` in the project root
