### ISSUE TITLE
/usr/local/bin/electrum executable does not exist  after installation

### ISSUE THREAD

**Issue by colourful-land** [spesmilo/electrum#4721]
Following website instruction:

    $ sudo pip3 install https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz
    The directory '/home/weiwu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/weiwu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz
      Downloading https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz (8.3MB)
        100% |████████████████████████████████| 8.3MB 215kB/s 
      Requirement already satisfied (use --upgrade to upgrade): Electrum==3.2.3 from https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz in /usr/local/lib/python3.6/dist-packages
    Requirement already satisfied: PySocks>=1.6.6 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: dnspython in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: ecdsa>=0.9 in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: jsonrpclib-pelix in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: pyaes>=0.1a1 in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: qdarkstyle<3.0 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: qrcode in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: typing>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    $ electrum
    bash: /usr/local/bin/electrum: No existe el archivo o el directorio

Here "No existe el archivo o el directorio" apparently mean that an executable wasn't found.

Attempt to run it in a different way:

    $ python3 -m electrum
    [ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
    /usr/bin/python3: No module named electrum.__main__; 'electrum' is a package and cannot be directly executed

It's unclear if

- a) the installation wasn't successful, or
- b) Electrum wasn't suppose to be run by `python3 -m` and an executable is missing.

Thanks.

**Comment by ysangkok** [comment]
Could you please do `ls -l /usr/local/bin/electrum` and report the output, thanks.

You're not supposed to start Electrum with `-m`, what makes you think that?

**Comment by colourful-land** [comment]
> Could you please do ls -l /usr/local/bin/electrum and report the output

    $ sudo pip3 install https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz
    The directory '/home/weiwu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/weiwu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz
      Downloading https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz (8.3MB)
        100% |████████████████████████████████| 8.3MB 221kB/s 
      Requirement already satisfied (use --upgrade to upgrade): Electrum==3.2.3 from https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz in /usr/local/lib/python3.6/dist-packages
    Requirement already satisfied: PySocks>=1.6.6 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: dnspython in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: ecdsa>=0.9 in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: jsonrpclib-pelix in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: pyaes>=0.1a1 in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: qdarkstyle<3.0 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: qrcode in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: typing>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    $ ls -l /usr/local/bin/electrum
    ls: no se puede acceder a '/usr/local/bin/electrum': No existe el archivo o el directorio

Using Ubuntu 18.04. "No existe el archivo o el directorio" means no such file or directory.

> You're not supposed to start Electrum with python3 -m, what makes you think that?

The lack of an `electrum` executable made me think that:)

**Comment by ysangkok** [comment]
If I try to uninstall Electrum using pip3, I get this output:
```
 % sudo pip3 uninstall electrum
Uninstalling Electrum-3.2.3:
  Would remove:
    /usr/local/bin/electrum
    /usr/local/lib/python3.6/dist-packages/Electrum-3.2.3-py3.6.egg-info
    /usr/local/lib/python3.6/dist-packages/electrum/*
    /usr/share/applications/electrum.desktop
    /usr/share/pixmaps/electrum.png
Proceed (y/n)? y
  Successfully uninstalled Electrum-3.2.3
```

Could you please try that command (`sudo pip3 uninstall electrum`) and report the output here?

If it works, try [clearing the command path cache](https://unix.stackexchange.com/a/5610/14305) (using `hash -r`), reinstalling and please report whether it works.

**Comment by colourful-land** [comment]
$ sudo pip3 uninstall electrum
    The directory '/home/weiwu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Uninstalling Electrum-3.2.3:
      /usr/local/lib/python3.6/dist-packages/Electrum-3.2.3.egg-info
      /usr/local/lib/python3.6/dist-packages/electrum
    Proceed (y/n)? y
      Successfully uninstalled Electrum-3.2.3

Then install worked.

    $ sudo pip3 install https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz
    The directory '/home/weiwu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/weiwu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz
      Downloading https://download.electrum.org/3.2.3/Electrum-3.2.3.tar.gz (8.3MB)
        100% |████████████████████████████████| 8.3MB 216kB/s 
    Requirement already satisfied: PySocks>=1.6.6 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: dnspython in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: ecdsa>=0.9 in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: jsonrpclib-pelix in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: pyaes>=0.1a1 in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: qdarkstyle<3.0 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: qrcode in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from Electrum==3.2.3)
    Requirement already satisfied: typing>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from Electrum==3.2.3)
    Installing collected packages: Electrum
      Running setup.py install for Electrum ... done
    Successfully installed Electrum-3.2.3
    $ which electrum
    /usr/local/bin/electrum

Could be a glitch in the first attempt to install, then the follow-up install attempts don't redo the action of putting electrum in the right place.
