### ISSUE TITLE
p2sh-segwit PSBT issue

### ISSUE THREAD

**Issue by quantumedusa** [spesmilo/electrum#4729]
Recently began setting up Coldcard to swap over coins to a new seed, and was planning on using PSBT microSD transfers until the plugin was working with p2sh-segwit, but ran into a bug when trying to test with first deposit that signing worked properly on coldcard. Traceback dump and system info included.

Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins/coldcard/qt.py", line 40, in 
    btn.clicked.connect(lambda unused: self.export_psbt(dia))
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins/coldcard/qt.py", line 61, in export_psbt
    raw_psbt = keystore.build_psbt(tx, wallet=dia.wallet)
  File "/usr/local/lib/python3.5/dist-packages/electrum/plugins/coldcard/coldcard.py", line 456, in build_psbt
    write_kv(PSBT_GLOBAL_UNSIGNED_TX, unsigned)
NameError: name 'PSBT_GLOBAL_UNSIGNED_TX' is not defined
 
Additional information
Electrum version: 3.2.3 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] 
Operating system: Linux-4.15.0-33-generic-x86_64-with-Ubuntu-16.04-xenial 
Wallet type: 2of3 
Locale: en_US

**Comment by SomberNight** [comment]
Same trace as in https://github.com/spesmilo/electrum/issues/4698

To use most hardware wallets in Electrum, additional 3rd party packages are required. These are bundled in the Windows and MacOS binaries; but as only source is distributed on Linux, not there.
See guide at https://github.com/spesmilo/electrum-docs/blob/master/hardware-linux.rst

This is the same for all the hardware wallets. The user is usually explicitly told about missing libraries when he tries to connect to the device during wallet creation by the Install Wizard in Electrum. However I suspect people are circumventing these checks as apparently the Coldcard allows creating the wallet file for you. Is that what you did?

**Comment by quantumedusa** [comment]
Yes, will verify quickly and post in a second so you can close this, apologies.

**Comment by quantumedusa** [comment]
Working, you can close. Sorry for the waste of time.

**Comment by quantumedusa** [comment]
Actually...I'm getting an error from the Coldcard now that the redeem script is missing from the input in the PSBT. Let me set up a testnet wallet and import and see if I can reproduce, not comfortable providing the PSBT from actual coins.

**Comment by SomberNight** [comment]
I've only successfully tested spending from `p2pkh` and `p2wpkh`; not `p2wpkh-p2sh`. For this reason, the wizard does not even let you create a `p2wpkh-p2sh` wallet. I guess by creating the wallet file on the actual device even this check is circumvented though.

It would be nice to implement support for `p2wpkh-p2sh`. I don't know how difficult it would be.

@peter-conalgo what is missing for this? Is it only lack of support of p2sh redeem scripts in the electrum plugin code when (de)serialising psbt?

**Comment by peter-conalgo** [comment]
(Sorry for the late reply.) I haven't looked into the Electrum side, but AFAIK the Coldcard side is ready to sign p2wkh-p2sh inputs. The plugin probably just isn't constructing the PSBT correctly.

**Comment by SomberNight** [comment]
fixed in https://github.com/spesmilo/electrum/pull/4784
