### ISSUE TITLE
gettransaction should return deserialized data

### ISSUE THREAD

**Issue by DanielWeigl** [spesmilo/electrum#4730]
I tried to use electrum as a wallet backend for a service Im working, where we also need to monitor all transactions to and from the addresses in this wallet.

By using `history` and the iterating over all transaction-ids with `gettransaction` I was hoping to get all the needed data for bookkeeping (amount for each transaction, confirmation state, to/from address, blockheight..)

But neither does history include all low-level details nor does gettransaction return any parsed data.

I checked the code and saw that `Transaction` already does deserialize all the intressting data, but does not return it in `Transaction#as_dict`.

Just for testing i extended it to:

```
def as_dict(self, details=False):
        if self.raw is None:
            self.raw = self.serialize()
        self.deserialize()
        out = {
            'hex': self.raw,
            'complete': self.is_complete(),
            'final': self.is_final(),
        }

        if details :
            out.update({
                'inputs': self.inputs(),
                'outputs': self.outputs(),
            })
        return out
```

and wired the commandline arguments as needed.

so for example it looks like:

```
./electrum gettransaction --details 69ee5eaa151a9c3598ae0f67c251d70f704f066da5b3709d7ae13ddaf9f6ded4
{
    "complete": true,
    "final": false,
    "hex": "0200000000010161ac...2103e44674bff6778ca531e04665a87e0b485bb06450a1ee72b72b6f6c438847b1f3a3460800",
    "inputs": [
        {
            "address": "3PSBsXCyjArqZdS5XokUKkhA5k9wgB8Mnt",
            "num_sig": 1,
            "prevout_hash": "1408dcb22d84a9c8937d68497d9384adfa239951c3ee874d677288c8cd4eac61",
            "prevout_n": 1,
            "pubkeys": [
                "03e44674bff6778ca531e04665a87e0b485bb06450a1ee72b72b6f6c438847b1f3"
            ],
            "scriptSig": "1600142df48c2f07d6d0b07e4b99f50a43ea7cfeb46554",
            "sequence": 4294967293,
            "signatures": [
                "3045....80fee8201"
            ],
            "type": "p2wpkh-p2sh",
            "witness": "0248304...1f3",
            "x_pubkeys": [
                "03e44674bff6778ca531e04665a87e0b485bb06450a1ee72b72b6f6c438847b1f3"
            ]
        }
    ],
    "outputs": [
        [
            0,
            "3NjL4VhQGgTTBufsamYTEz5cwQza7Ln9fa",
            9999866000
        ]
    ]
}

```

Are there any sideeffects I dont understand or would you accept such an extension as pull request, then i tidy up my code and make a PR.

A second step would be to include also semantic details like which output is a change address, and maybe the referenced inputs value.

**Comment by ecdsa** [comment]
you should use `electrum deserialize`
