### ISSUE TITLE
What is a kvByte?

### ISSUE THREAD

**Issue by iluuu1994** [spesmilo/electrum#4733]
https://github.com/spesmilo/electrum/blob/7cc628dc7909c3ff44a5e5dfc0de60bc8e438ce1/electrum/commands.py#L661

I'm guessing this should be a kByte or Kibibyte?

**Comment by SomberNight** [comment]
Note that this (vbyte; kvByte) is the unit used by Electrum all over the UI. We just chose not to confuse the user by not mentioning explicitly it's "virtual".

**Comment by iluuu1994** [comment]
Got it, thanks!
