### ISSUE TITLE
Electrum Vertcoin Wallet 3.2.2 - Vertcoin node list is empty - no connection to a server

### ISSUE THREAD

**Issue by newuser20180929** [spesmilo/electrum#4744]
Hello,

since yesterday, September 28th, my Electrum Vertcoin wallet is not able to establish a connection to neither a node server nor the blockchain. The Vertcoin node list is empty, no connection to a server seems to be possible (repeated attempts), thus no data synchronization takes place. As for bug reports the following address is recommended on the support page, I submit my issue here. Thank you.

https://github.com/spesmilo/electrum/issues

Remark: My Electrum Bitcoin wallet, on the other hand, works without any difficulty.

**Comment by SomberNight** [comment]
Hi. Electrum is for Bitcoin only. The forks of the project for different altcoins are maintained by different people. Try asking here https://github.com/vertcoin-project/electrum-vtc
