### ISSUE TITLE
Electrum imposter site

### ISSUE THREAD

**Issue by ghost** [spesmilo/electrum#4750]
Google ads Electrum imposter site.
<img width="805" alt="screen shot 2018-10-02 at 4 37 24 pm" src="https://user-images.githubusercontent.com/33454532/46345257-888efe00-c661-11e8-9002-7265dd596afd.png">

Finally its going to **`https:// electrumwallet .org`**

**Comment by ysangkok** [comment]
What's with the screenshot? I don't see it mentioning the malicious domain.

Anyway, I sent a mail to abuse@godaddy.com which is what Whois reports the abuse email as.

**Comment by vinnyvoo** [comment]
Another one:

<img width="809" alt="screen shot 2018-10-22 at 11 53 51 am" src="https://user-images.githubusercontent.com/33454532/47279970-afea4280-d5f1-11e8-86a9-9b6603998ca2.png">

Finally its going to **`https:// electrun. net`**

Reported to Registrar.
