### ISSUE TITLE
How to run Android version in regtest?

### ISSUE THREAD

**Issue by partylana** [spesmilo/electrum#4752]
How to run Android version in regtest? Any docs?

**Comment by bauerj** [comment]
Hey,

you would have to create your own APK, I'm afraid.

**Comment by SomberNight** [comment]
It's enough to call `constants.set_regtest()` around here; just add a line that does it unconditionally:
https://github.com/spesmilo/electrum/blob/788b5b04febf45da891b1a85990385d06c6f14bc/run_electrum#L402-L407

**Comment by partylana** [comment]
@SomberNight that worked. Thanks.
