### ISSUE TITLE
android 3.2.3 freezing/locking up/crashing/black screen

### ISSUE THREAD

**Issue by farzher** [spesmilo/electrum#4756]
i'm sure you hear this all the time.
like 25% of reviews are "unstable, doesn't work, crashes"
but, this is what's happening to me:

seems to have started when i was trying to use the qr scanner.
qr scanner runs but never identifies anything. impossible to stop scanning, have to close the app.
now everytime i leave the app, when i come back it's a black frozen screen.
everything used to work fine for a bit, including the qr scanner.
i tried restarting my phone a bunch.

how can i backup all the wallet files so i can then uninstall/reinstall the app, maybe it's just messed up.
i don't want to restore from keys because i have too many wallets.

**Comment by SomberNight** [comment]
It's weird that this problem persists through phone restarts..
Did you install via Google Play? Maybe try launching the app both from the app launcher/drawer and from Google Play.

The wallet files are not meant to be backed up/exported/imported on Android. They are written to [internal storage](https://developer.android.com/guide/topics/data/data-storage#filesInternal), so only the app itself and root has access to them.
You could try [adb backup](https://gist.github.com/SomberNight/295cd950ee4fb2b3768f1ae538babe7e), but it should not work either, as we explicitly disabled it to make sure Google itself does not "helpfully backup the wallet files into its cloud for you" (but as the link shows, there have been some versions where the flag was mistakenly not set, so backups were not explicitly forbidden).

How many wallets do you have that restoring from seed words would be that cumbersome?

**Comment by SomberNight** [comment]
Oh btw you could try to get logs from the app via adb.
```
adb logcat | grep python
```

**Comment by farzher** [comment]
Hey, sorry for being slow. Wasn't looking forward to backing up/reimporting
wallets.

I uninstalled and reinstalled the app. All wallets are gone but it's the
same broken behavior. I'm not sure what else I could reset, besides my
entire phone o:

I installed from Google play and APK.

All other apps work fine on my phone.
Very weird.

I now get a crash report screen when I press the camera button.

On Oct 4, 2018 5:58 PM, "ghost43" <notifications@github.com> wrote:

Oh btw you could try to get logs from the app via adb.

adb logcat | grep python

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spesmilo/electrum/issues/4756#issuecomment-427183262>,
or mute the thread

**Comment by farzher** [comment]
i have a signed electrum 2 of 2 transaction on an offline phone.
how do i broadcast it?
i'm supposed to scan the QR on my online phone using electrum and press broadcast. but electrum doesn't work on my online phone anymore.

i tried manually broadcasting the QR code but it seems to be some kind of electrum format.
how can i get it to a raw bitcoin transaction so i can manually broadcast it?

**Comment by farzher** [comment]
^ nvm i was able to figure it out <3 open source.

it was a raw transaction just "base 43" encoded

`__b43chars = b'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ$*+-./:'` if anyone's curious

**Comment by SomberNight** [comment]
Quite a bit of code changed since the original report. Is this issue still applicable to latest Electrum?

**Comment by farzher** [comment]
i think i've reformatted my phone since then. everything is fine now
