### ISSUE TITLE
Offline setup instructions don't work - dns module missing, version 3.2.3, linux

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#4768]
I tried to install on offline system according to instructions on download page in Linux source section. It says can use: 
`sudo python3 setup.py install`

I had already installed dependencies (before disconnecting) using:
`sudo apt-get install python3-setuptools python3-pyqt5 python3-pip`

This did some install procedure but when trying to run electrum after it always gives and error saying "module dns not found" and suggests "sudo pip install <module>". That and various other similar steps don't work. 

I found the only was was to use the steps in the README which were:
`pip3 install .[fast]`

But this still does not add a menu item or icons as far as I can tell so you have to copy the icon manually from archive and then add a menu or shortcut manually.

Not sure what's going but I'd suggest updating or removing instructions using this setup method. I know it used to work on older installs as I did it several times. Due to the new version requiring offline signing to support PSBT format I had to create a new offline system and re-install.

**Comment by SomberNight** [comment]
I think we should suggest using `python3 -m pip install ....` everywhere. That might solve the issue.
I'll change the README, and @ecdsa should change the website.

**Comment by SomberNight** [comment]
> But this still does not add a menu item or icons as far as I can tell so you have to copy the icon manually from archive and then add a menu or shortcut manually.

As for this part, I don't know... What Linux distribution are you testing on?

**Comment by neocogent** [comment]
I was doing this on Mint 19 (based on Ubuntu 18.04). I did find that in the electrum.desktop file there was a command:

`sudo desktop-file-install electrum.desktop`

which did the trick and gave me a menu item. Maybe that just needs to be mentioned as an optional command or somehow combined into the pip install. I seem to recall the old setup.py method used to add a menu item but it's been a long while and I could be wrong.

**Comment by SomberNight** [comment]
I think all the docs/website have been updated to use `python3 -m pip install`.

As for the desktop icon problem; I've opened a separate issue for that: https://github.com/spesmilo/electrum/issues/5227
