### ISSUE TITLE
GUI displays only one xpub for multisig wallet

### ISSUE THREAD

**Issue by stepansnigirev** [spesmilo/electrum#4777]
When using multisig wallet (no matter with software or hardware key storage) I can't see master public keys of the co-signers. Only the very first one is displayed.

![multisig_xpubs](https://user-images.githubusercontent.com/1706012/46955854-2c31d280-d094-11e8-93b0-9c76c80d4f89.png)

**Comment by SomberNight** [comment]
Does this wallet actually work? It seems all the xpubs are the same (I don't think it's a display bug).

Try opening the [wallet file on disk](http://docs.electrum.org/en/latest/faq.html#where-is-my-wallet-file-located) with a text editor, and search for `"xpub"`.

When you create a new wallet, can you reproduce this problem there?

**Comment by stepansnigirev** [comment]
Yes, it's display issue. Wallet works - I can sign with all my hardware devices.
Wallet file has all the xpubs:
```
    "x1/": {
        "derivation": "m/45'/0",
        "hw_type": "trezor",
        "label": "trezor touch",
        "type": "hardware",
        "xpub": "xpub6APSzbcJN1zTroLEViJtjCF3cAVWwQuFTX36PxHaMGXbVbSpHqAGsrs1xmRsEPmKHtsQ8XKrii8hw9otbgEpQ674eiw2dBKkuu91eeFLWKK"
    },
    "x2/": {
        "cfg": {
            "mode": 0,
            "pair": ""
        },
        "derivation": "m/45'/0",
        "hw_type": "ledger",
        "label": "",
        "type": "hardware",
        "xpub": "xpub6A6UyKUUPQoK6JBcHc1gLhCYkkybTZGRpBs7Fmu3mtWWEQnqXGcWTVQJgaWsQiydohgJsf9L7Edrg5rLmbMN6NDHV8k65zmcYRaH5iVhsgb"
    },
    "x3/": {
        "cfg": {
            "mode": 0,
            "pair": ""
        },
        "derivation": "m/45'/0",
        "hw_type": "ledger",
        "label": "",
        "type": "hardware",
        "xpub": "xpub6Bb95ETB27TXcHw3LUugns8KEoXSQcrzu5kD424589yqu4ZDf8wPqcS6JHHnapnKdy8RKeDeDUkYyhsZAbxJYezjzXBVak17SnX4XfUb3d9"
    }
```

The same happens if you do software multisig, all xpubs are in the file but they are not displayed by the GUI.

You can just try to set up multisig address by yourself with [random xpubs](https://iancoleman.io/bip39/) and reproduce this issue. Only the first one is shown.

**Comment by stepansnigirev** [comment]
I was running an official binary from electrum.org
I also built electrum from source (master branch) - the same issue

Just tried on Windows - everything works perfectly. I will try on my other mac laptop at home and write you back.

I am running on macOS High Sierra 10.13.6

**Comment by SomberNight** [comment]
If you can run from source, maybe try:
```diff
diff --git a/electrum/gui/qt/main_window.py b/electrum/gui/qt/main_window.py
index 5be84beca..8699fe37f 100644
--- a/electrum/gui/qt/main_window.py
+++ b/electrum/gui/qt/main_window.py
@@ -2094,6 +2094,7 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
             mpk_text.addCopyButton(self.app)
             def show_mpk(index):
                 mpk_text.setText(mpk_list[index])
+                mpk_text.update()
             # only show the combobox in case multiple accounts are available
             if len(mpk_list) > 1:
                 def label(key):
```

**Comment by stepansnigirev** [comment]
Thanks for pointing out where to look =)

This helped:
```py
def show_mpk(index):
    mpk_text.setText(mpk_list[index])
    mpk_text.repaint()
```

**Comment by stepansnigirev** [comment]
`update()` didn't work.
I checked `updatesEnabled()` and `isVisible()` - both are `True`

**Comment by stepansnigirev** [comment]
I updated pyQt to latest version (5.11.3) and everything works now, without any changes in the code

**Comment by SomberNight** [comment]
Note: same thing in the wizard during the script type/derivation dialog (selecting radio button does not refresh text).

**Comment by SomberNight** [comment]
Note: the situation is a bit more complicated than just the Qt version.

- PyQt 5.10
    - macOS 10.11: display bug
    - macOS 10.12: display bug
    - macOS 10.13: display bug
- PyQt 5.11
    - macOS 10.11: display bug
    - macOS 10.12: display bug
    - macOS 10.13: OK, no "bug"

**Comment by SomberNight** [comment]
got new report on IRC for this....
using
- official electrum 3.3.6 binary
- on macOS 10.14.4
- with both dark theme and standard theme
display bug...

**Comment by SomberNight** [comment]
Ok I've tested on macOS 10.14.4
- running from source, Qt 5.11.2 and PyQt 5.11.3, python 3.7.3  ->  no bug
- running from source, Qt 5.11.2 and PyQt 5.11.3, python 3.6.5  ->  display bug
- running official 3.3.6 binary, Qt 5.11.2 and PyQt 5.11.3, python 3.6.4  ->  display bug

So I guess we should update Python in the binary...

**Comment by sunknudsen** [comment]
Experiencing the same bug.

> Try opening the wallet file on disk with a text editor, and search for "xpub".

The file is encrypted. Is there a way to list the master pub keys using command line or the Electrum console?

**Comment by SomberNight** [comment]
@sunknudsen run this in the `Console` tab:
```
[k.xpub for k in wallet.get_keystores()]
```

**Comment by sunknudsen** [comment]
Thanks @SomberNight, works like a charm.

**Comment by fireduck64** [comment]
I have reproduced this is 3.3.6 on macos.

The xpubs are different in the wallet file but show the same in the UI.
