### ISSUE TITLE
Question: Is there any feature to lock funds for some n amount of time?

### ISSUE THREAD

**Issue by vinnyvoo** [spesmilo/electrum#4781]
Is there any feature to lock funds for some n amount of time. Its not about freeze.

**Comment by dabura667** [comment]
No. Electrum has no such feature.

**Comment by SomberNight** [comment]
Well technically you can send to any scriptPubKey using the `Pay to` field in the `Send` tab in Qt; but you cannot spend those coins then in Electrum.

The `Pay to` field in Qt is very powerful, e.g.
```
021ec13d5aebd1795de65945672729a385cd87157ebede4df5b886159299f78157 OP_CHECKSIG,0.1
tb1qju64xjlnarxxwr5y8l0zm0jt2gyevtv7llck09,0.05
```
