### ISSUE TITLE
Compiling on osx.

### ISSUE THREAD

**Issue by vinnyvoo** [spesmilo/electrum#4782]
This document ( https://github.com/spesmilo/electrum/tree/master/contrib/build-osx ) mentions that "`building it on High Sierra makes the binaries incompatible with older versions`". What does the `older versions` mean? does it mean older electrum wallets or older osx?

If so how to make it compatible to all version with high sierra? Any way?

**Comment by bauerj** [comment]
I meant older versions of macOS (and OS X). 

And while there probably is some way to create backwards-compatible binaries on recent versions of macOS, it should be _a lot_ easier to install an older version, e.g. El Capitan.

**Comment by SomberNight** [comment]
The production binaries are built in a VM running the mentioned El Capitan (10.11.6).

**Comment by vinnyvoo** [comment]
@SomberNight pirated El Capitan in VM?  😂 Source please.

**Comment by SomberNight** [comment]
Who said anything about pirated? It's a Mac laptop running newer MacOS, with a VM running El Capitan.

**Comment by vinnyvoo** [comment]
cool. Thanks.
