### ISSUE TITLE
finding transaction date

### ISSUE THREAD

**Issue by utopicdev** [spesmilo/electrum#4791]
I am using electrum API on my site to receive payments, my steps to recognize a new transaction with a purpose of reusing bitcoin addresses are:

* getaddresshistory [addr]
* gettransaction [txid] foreach transaction
* add a transaction if it was not found in the local database of previous transactions for the address

I would like to avoid some possible problems in future by considering checking only recent transactions, for this I need to get the transaction date for each transaction.
I have found so far there is only a 'history' command that shows dates, but I would like to verify each transaction time individually without fetching whole wallet history for the current year.
Is there any solution?

**Comment by utopicdev** [comment]
I can use `createnewaddress` instead for getting a new address. I don't use `addrequest` because it forces me to expect some determined amount from a customer, which is not convenient for me. My system expects to accept any amount from the customer in order to top up their credit balance.

I need to reuse addresses because I have many low amount (i.e. one US dollar) transactions and having less addresses on each cash out helping to significantly reduce transaction fees.

**Comment by SomberNight** [comment]
> I need to reuse addresses because I have many low amount (i.e. one US dollar) transactions and having less addresses on each cash out helping to significantly reduce transaction fees.

You are likely misunderstanding how fees work.

Fees are based in transaction size in bytes.
Addresses used in a txn (as part of inputs or outputs) are irrelevant to transaction size.
Bitcoin is UTXO-based.
Transactions have inputs and outputs, and what determines the size of a tx is the number of inputs and outputs.

i.e. if you have 1000x one dollar deposits, it's going to cost a lot to spend that. This cost is invariant of whether the deposits are on the same address or all different addresses.

**Comment by utopicdev** [comment]
I think I got it now, will stick to not reusing practice since now.
