### ISSUE TITLE
add getblockheader command in API

### ISSUE THREAD

**Issue by ghost** [spesmilo/electrum#4793]
Hello, are there plans to introduce an API command to get block header info?

I have found Stratum has a method for that:
`blockchain.block.get_header`

I am currently using this plugin https://bitcointalk.org/index.php?topic=1110912.0 that introduce this feature, but would be nice to have it in core functionality.

**Comment by SomberNight** [comment]
Could you please give some more details what exactly you have in mind?
Would this be a command for the electrum client (daemon)?
What would be the signature for this method (arguments/return value)?

**Comment by vlanmx** [comment]
The command would be a part of the electrum client and here is a suggested specification:

#### Command:

  * `getblockheader`
    Get blockchain header information

#### Positional arguments:

  * `height`
    Bitcoin block height

#### Response parameters:
```
{
  "block_height": <integer>,
  "version": <integer>,
  "prev_block_hash": <hexadecimal string>,
  "merkle_root":  <hexadecimal string>,
  "timestamp": <integer>,
  "bits": <integer>,
  "nonce": <integer>
}
```
I got it from this specification https://electrumx.readthedocs.io/en/latest/protocol-basics.html#deserialized-headers and this is what exactly returns any electrum server on calling `blockchain.block.get_header` method.

#### Usage example - Electrum client 
This suppose we have loaded a wallet in daemon mode

```
$ electrum getblockheader 546140
{
	"version": 536870912, 
	"prev_block_hash": "0000000000000000001f1e9624ab7c1bd089458c50da991c6821ddb3fe6a61e4", 
	"merkle_root": "97c8ceb7140e83c1e00536bb4960b5c44fe1989e742777f6ea61940833a67c37", 
	"timestamp": 1539777446, 
	"bits": 388350353, 
	"nonce": 2349350086, 
	"block_height": 546140
}

```

#### Usage example - JSON RPC
```
Request: {"id":"0","jsonrpc":"2.0","method":"blockchain.block.get_header","params":["546140"]}
Response: {"id": "0","jsonrpc": "2.0", "result": {"version": 536870912, "prev_block_hash": "0000000000000000001f1e9624ab7c1bd089458c50da991c6821ddb3fe6a61e4", "merkle_root": "97c8ceb7140e83c1e00536bb4960b5c44fe1989e742777f6ea61940833a67c37", "timestamp": 1539777446, "bits": 388350353, "nonce": 2349350086, "block_height": 546140}}

```

**Comment by ecdsa** [comment]
closing, no real use case
