### ISSUE TITLE
I really like EPS, is there a way to make it easier or more used somehow

### ISSUE THREAD

**Issue by alcafo** [spesmilo/electrum#4794]
Electrum it is my favourite desktop wallet, because of many features like cold storage, watch only, coin control (freeze/unfrezze accounts) giving great privacy features and of course about how it is easy and friendly to use it with HW. The only feature that I was missing was to connect it directly to a full node.

Finally I've discovered EPS.
https://github.com/chris-belcher/electrum-personal-server

Lots of people run full nodes as they understand the benefits which implies but most of them they do not use it since there are no ways to do it. So most of nodes they are only online sharing the whole blockchain but it would be more useful if they use it and reinforce the rules.

I would like to ask and I really encourage the devs to add EPS in electrum wallet, as an addon or option in settings allowing to chose to connect to electrum servers or your own full node. That would make possible a lot of people who already has a full node running to use it which will greatly help the entire bitcoin network.

Thanks you

**Comment by chris-belcher** [comment]
I don't think adding EPS to Electrum is appropriate, because Electrum generally gets switched off and on as needed by the user, while EPS works best when its always-on just like the full node.

To get more people to use it I think education is needed.

**Comment by ecdsa** [comment]
we could have a full node option at some point, but I am not sure if it should use EPS.
ElectrumX can be configured to run privately, and it provides a better user experience 
(for example with imported wallet, lightning channels addresses, that are not part of your xpub)

anyway, this issue should be closed, it is out of scope at the moment
