### ISSUE TITLE
Recovering old wallet from electrum.dat

### ISSUE THREAD

**Issue by yanneves** [spesmilo/electrum#4801]
I've got an old `electrum.dat` file from an Android app install. It's JSON-like and I can see the following headers: `addr_history`, `transactions`, `use_encryption` (true), `master_public_key`, `server`, `blockchain_headers_path`, `seed` (encrypted string), `accounts`, `imported_keys`, `seed_version` (4), `verified_tx3`

Probably the only useful data in here is the encrypted `seed` and maybe `seed_version`. If I know the password used to lock this wallet, am I able to decrypt the seed? Couldn't find any reference to this in the Electrum docs. Being a bit hopeful, I tried just adding the wallet verbatim using Electrum 3.2.3 but it errors out when it tries to open the wallet. Equally no success using the latest Electrum distribution on Android.

**Comment by SomberNight** [comment]
> I tried just adding the wallet verbatim using Electrum 3.2.3 but it errors out when it tries to open the wallet

What is the error?

Try this:
```
from electrum.crypto import pw_decode

ctext = "B84+aykdaDMQM2q6UC8VLLnVbqWuy9aHG2ePXuXqdzq43IVwCuvtXemMvBZ0b9ERqWa+RY+Es+QRkSC13i2svGowU3vQHMDjh1GvN+fVMO/901qNLT11btbhH5Bg+9C3"
password = "1234"
seed = pw_decode(ctext, password)
print(seed)
```

**Comment by dabura667** [comment]
https://docs.python.org/3.5/library/getpass.html

getpass better imo.

saving you password to disk isn't good

**Comment by yanneves** [comment]
Thanks @SomberNight and @dabura667, I was able to decrypt the encrypted string under `seed` using your methods. The value stored under this value is the private key for the wallet.

Final code for anyone who stumbles upon this:

```python
from electrum.crypto import pw_decode
import getpass

password = getpass.getpass()

ctext = "B84+aykdaDMQM2q6UC8VLLnVbqWuy9aHG2ePXuXqdzq43IVwCuvtXemMvBZ0b9ERqWa+RY+Es+QRkSC13i2svGowU3vQHMDjh1GvN+fVMO/901qNLT11btbhH5Bg+9C3"
seed = pw_decode(ctext, password)
print(seed)
```
