### ISSUE TITLE
Old version stuck synchronizing

### ISSUE THREAD

**Issue by enunciato** [spesmilo/electrum#4804]
Thank You for getting back to me. The address that sent from coinbase is the address that I clip-boarded from my new electrum wallet. I had just installed electrum & coped it right in. I pasted it into my coin base send to the revive address in my new electrum wallet. Here is a screen shot. After some time I closed and re-opened my electrum and my receive address had changed from  1LS3eoPqsPaQ8akgkTFRqxxiEH72AEWh3j   to now   1FnBvVrh56rVgb9dwmneKGLVr9iBUWDm86  it says Synchronizing as you an see in the screen shot. So is there some thing I can do to make it sync? And why would my new electrum wallet give me a receive address that does not belong to my wallet?

Thanks Again,
Jeff
![capture](https://user-images.githubusercontent.com/44494138/47604600-42576100-d9b9-11e8-8608-32326b9e92f2.PNG)

**Comment by SomberNight** [comment]
2.6.4 is a very old version now. There has been more than 3000 commits to master since.
Please update to Electrum 3.2.3

**Comment by enunciato** [comment]
Hey Thanks o much that did the trick. You guys are all right!!! Jeff


-------- Original Message --------
Subject: Re: [spesmilo/electrum] Help (#4804)
