### ISSUE TITLE
OS X wallet import hardware ID issue

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#4806]
This one is a head scratcher but I'll do my best to describe how to reproduce.

Electrum 3.2.3 on testnet
OS X Sierra
Create 3-of-5 p2sh wrapped segwit wallet
First pubkey: import from Ledger Nano S with derivation path m/49/1/0
Second pubkey: import from Trezor One with derivation path m/49/1/0
Third pubkey: import from Trezor One with derivation path m/49/1/0
Fourth pubkey: import master upub
Fifth pubkey: import master ubpub

The problem occurs when importing the third pubkey (the second Trezor) - I unplug the first trezor immediately after importing its pubkey and plug in the second Trezor. Electrum says it detects a Trezor but it displays the label of the first Trezor rather than the second. If you proceed to import, it seems to import successfully. In fact, the wallet initializes as expected and even derives the correct addresses and finds transactions and balances.

The problem occurs when trying to spend from the wallet. You can successfully sign with the Ledger Nano S and the first Trezor, but then when trying to apply the third signature with the second Trezor, the operation fails because Electrum says it is expecting the first Trezor.

So it seems that the xpubs are all stored correctly, but something is stored incorrectly regarding the actual hardware device ID.

**Comment by jlopp** [comment]
I will note that I've been able to work around this bug by not plugging in the second trezor during the import step, allowing Electrum to throw an error that no devices were detected, and then plugging in the second trezor and hitting retry. At that point it detects the second trezor with the correct label / device ID.

**Comment by SomberNight** [comment]
> So it seems that the xpubs are all stored correctly, but something is stored incorrectly regarding the actual hardware device ID.

Can you open the wallet file on disk, and check the values for `"x1/"`, `"x2/"`, etc.
E.g.:
```
"x1/": {
	"derivation": "m/1002'/0",
	"hw_type": "digitalbitbox",
	"label": " ",
	"type": "hardware",
	"xpub": "Vpub5iMDtmUgdwnUjQVCMWbuSz5aycGS3XJeAJXpKp3rbC68oSHxkiBwBVtDAbZhZd2BzxkojLddos4ZHCDaAGdBx1iCke6v8YuvdqsS5PTJzbc"
},
"x2/": {
	"derivation": "m/1002'/0",
	"hw_type": "trezor",
	"label": "testing2",
	"type": "hardware",
	"xpub": "Vpub5h4TxHvXnmRMGrc1toG5uJCHEKmAMD9Sx2UYexgXYfCsHBbikxn5qtmpiPA2YCadR2K7p3qAgehttEusGjKPD9RKPnxTv1CkVtKdQkwLcXX"
}
```

> I've been able to work around this bug by not plugging in the second trezor during the import step, allowing Electrum to throw an error that no devices were detected, and then plugging in the second trezor and hitting retry.

Do you see any difference in the wallet files when you use this workaround compared to when not?

**Comment by SomberNight** [comment]
Ok, I now have two trezor ones to test, and I can reproduce.
```
"x1/": {
        "derivation": "m/49/1/0",
        "hw_type": "trezor",
        "label": "white",
        "type": "hardware",
        "xpub": "Upub5QnoG72tykXSkPY8qPK7VDWBoKK7pdLbcV7LTCoRz3uPr5SAmpYUgt8CBTVDnWmne71dgUZ3rD3yQC6jAuw3gUZ526NXoUq8XpBRZdQ4oaz"
    },
    "x2/": {
        "derivation": "m/49/1/0",
        "hw_type": "trezor",
        "label": "white",
        "type": "hardware",
        "xpub": "Upub5Q6wC7uBAA6bhbRoniV3TLKRHDRHJT8EY4jYw1yL1pXU9qmG6hgrb9WTmLw4UYkaEeEiokcjqYysj6L746doYg2mCrLQzH1KE17agR9GNLH"
    }
```

> Electrum says it detects a Trezor but it displays the label of the first Trezor rather than the second. If you proceed to import, it seems to import successfully. In fact, the wallet initializes as expected and even derives the correct addresses and finds transactions and balances.

the storage will have the correct xpubs but incorrect labels

**Comment by SomberNight** [comment]
Related: https://github.com/spesmilo/electrum/issues/4404

The DeviceMgr will not detect that the first trezor was disconnected as the second trezor is at the same path.

https://github.com/spesmilo/electrum/blob/32af83b7aede02f0b9bb3e8294ef2dc0481fb6de/electrum/plugin.py#L604-L614

**Comment by matejcik** [comment]
I think I'll be able to resolve this in the `has_usable_connection` method.
We might also have to fix this in trezorlib - disconnecting a device and reconnecting a different one on the same USB path is a scenario I honestly never thought to consider.
