### ISSUE TITLE
[Question] Check tx confirmations using rpc cli

### ISSUE THREAD

**Issue by max9111z** [spesmilo/electrum#4810]
How can we check a count of confirmations for a single transaction using rpc/cli?
I have found so far there is only a `history` command that shows confirmations, but parsing thousands of transactions when we need only one is not the best practice. I know `history` supports limiting the number of output with a `--year` flag, but it's too ambiguous still.

**Comment by SomberNight** [comment]
See the `get_tx_status` RPC in https://github.com/spesmilo/electrum/commit/8f5ca40d10e921f87f1faf6162d81a62d114f1d7
