### ISSUE TITLE
problems upgrading from Electrum 1.9.8 to 3.2.3 on Mac

### ISSUE THREAD

**Issue by ceeber08** [spesmilo/electrum#4811]
I tried upgrading my electrum wallet from 1.9.8 to 3.2.3. I hadn't touched bitcoins for ~ 3 years since 2015. Before upgrading my bitcoins were visible, but I couldn't connect to server. I figured upgrading to newer version of Electrum would fix this. I have seed and original password. New wallet says error something went wrong while executing Electrum. It asks me to send bug report. When I close bug report wallet says 'synchronizing.' I tried upgrading Mac OS to Mojave 10.14. Same thing happens. Can someone help?

**Comment by SomberNight** [comment]
> It asks me to send bug report.

Have you sent it? If so, can you link to it here?

> I have seed

Try restoring from seed then.

**Comment by ceeber08** [comment]
Traceback (most recent call last):
  File "electrum/util.py", line 882, in run_with_except_hook
  File "electrum/network.py", line 1085, in run
  File "electrum/network.py", line 1067, in wait_on_sockets
  File "electrum/network.py", line 719, in process_responses
  File "electrum/network.py", line 662, in process_response
  File "electrum/synchronizer.py", line 159, in on_tx_response
  File "electrum/address_synchronizer.py", line 333, in receive_tx_callback
  File "electrum/address_synchronizer.py", line 222, in add_transaction
  File "electrum/address_synchronizer.py", line 184, in get_conflicting_transactions
AssertionError
 
Additional information
Electrum version: 3.2.3 
Python version: 3.6.4 (default, Feb 28 2018, 03:24:19) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] 
Operating system: Darwin-18.0.0-x86_64-i386-64bit 
Wallet type: standard 
Locale: ?

**Comment by SomberNight** [comment]
Ahh yes, ok, https://github.com/spesmilo/electrum/issues/4689 that is a known bug.. it should be fixed on master but it's not yet released.
Create a new wallet file using the wizard, and use your seed words to restore.

**Comment by ceeber08** [comment]
How do you 'Create a new wallet file using the wizard’?

**Comment by ceeber08** [comment]
nevermind, think i got it

**Comment by SomberNight** [comment]
When Electrum is open, on menubar `File`>`New/Restore`

**Comment by ceeber08** [comment]
I restored with seed words and same thing happens when I open back up the wallet. Same error and continues to say 'synchronizing'

**Comment by SomberNight** [comment]
but are you opening the newly created file or the old one? you should open the new wallet file.

If unsure, just go the folder [where the wallet files are stored](http://docs.electrum.org/en/latest/faq.html#where-is-my-wallet-file-located),
rename the whole folder, open electrum again, and restore from seed words again.
