### ISSUE TITLE
Can't recover wallet even though 

### ISSUE THREAD

**Issue by lookwhatitdid** [spesmilo/electrum#4813]
I created the wallet and sent my coin to this wallet. https://www.blockchain.com/btc/address/1Q3eYDygtMnZezskdNsAA8SLGQnsyB4HTM
Everything is confirmed yet when I go to recover my wallet using my seed, I am unable to move on to the next step in the process once my seed is written. The "next" button simply appears grey. I am sure that my seed is correct because I created the wallet today and copied it directly from my piece of paper when confirming for my recovery, I just am unable to click next when proceeding in the process.

**Comment by lookwhatitdid** [comment]
I created the wallet and sent my coin to this wallet. https://www.blockchain.com/btc/address/1Q3eYDygtMnZezskdNsAA8SLGQnsyB4HTM
Everything is confirmed yet when I go to recover my wallet using my seed, I am unable to move on to the next step in the process once my seed is written. The "next" button simply appears grey. I am sure that my seed is correct because I created the wallet today and copied it directly from my piece of paper when confirming for my recovery, I just am unable to click next when proceeding in the process.

**Comment by ecdsa** [comment]
your seed is not correct

**Comment by lookwhatitdid** [comment]
I don’t believe that is the case, I have it saved in a text file as well as a piece of paper on top of having to confirm the seed before creating the wallet

**Comment by SomberNight** [comment]
If the "next" button is disabled after entering the seed, then the checksum in the seed is not correct, hence that is not a valid seed.
Maybe you mistyped something? Or mixed two similar words? e.g. garbage/garage
Try playing around with these kind of substitutions.

Alternatively, if you have the original wallet file, that has the seed too.

**Comment by lookwhatitdid** [comment]
Ive tried about every combo I can think of but this is the only thing I
have written down and it was also copy and pasted into my text file. I
discovered the network was down when I was using the account but it was
still somehow able to recieve money. My seed: jealous chicken wolf rice
matrix year describe input claw extra(ct?) tired sunset

**Comment by lookwhatitdid** [comment]
well, the money didnt actually go through until I shut off tails and by
then when I went to go recover the account, the seed no longer worked

**Comment by lookwhatitdid** [comment]
I figured it out. Thanks!

**Comment by SomberNight** [comment]
Don't share your seed publicly.. move your coins now.
