### ISSUE TITLE
Windows build: Binary size increased after 3.2.3

### ISSUE THREAD

**Issue by practice-programs** [spesmilo/electrum#4815]
I tried to build for windows. The size is around 58MB. But your build is around 23MB. Why's that?

Build log : https://pastebin.com/j0EruhW8

Thank you.

**Comment by wakiyamap** [comment]
It seems to be getting heavier due to 3.2.3 and subsequent changes.
3.2.3 https://travis-ci.org/spesmilo/electrum/jobs/423935946
head master https://travis-ci.org/spesmilo/electrum/jobs/448477606

**Comment by bauerj** [comment]
Indeed, that's interesting. 

Can you use `pyi_archive-viewer` to compare our binaries to yours? Maybe it's adding something to the archive that shouldn't be there.

**Comment by vinnyvoo** [comment]
looks like @bauerj is right. I compiled previous commits and they are excpected size.

**Comment by bauerj** [comment]
This is still an issue as we didn't intend to increase the binary size.

**Comment by SomberNight** [comment]
It's this commit https://github.com/spesmilo/electrum/commit/bdecef0eaf31dd5859228496d224d2b302a80e44

https://travis-ci.org/spesmilo/electrum/jobs/428365874
https://travis-ci.org/spesmilo/electrum/jobs/428598167

**Comment by cculianu** [comment]
FYI guys we Electron-Cash guys got hit by this when building for macOS.  Here is my commit that fixes it.  Binary for macOS went from ~100MB down to ~49MB by explicitly excluding QtWebEngine and other crap.

Commit is here: 

https://github.com/Electron-Cash/Electron-Cash/commit/4b0996959420dfca3d53f178d86205616d8c568b

You may want to do similar for the windows build and the osx build. I don't have time to issue a PR to you guys for it -- but just so you know there is a workaround.

There might be a more elegant way to do this with 'hooks' into pyinstaller but I don't have the time to learn how to do that.  This "just works" and is "good enough". 😃
