### ISSUE TITLE
backwards-compatibility for API breakage in python-trezor 0.11

### ISSUE THREAD

**Issue by matejcik** [spesmilo/electrum#4817]
Not an issue in Electrum as it stands, more of a call for assistance.

I'm planning to do a breaking release 0.11 of python-trezor sometime in November.

I'll contribute fixes to the trezor plugin, it should allow simplification of at least some parts of the code. With that I'd like to bump required version to 0.11 for future Electrum releases, because keeping compatibility between 0.10 and 0.11 is going to be a pain.

**This bug** is about possibilities for an upgrade path, esp. in situations when someone upgrades python-trezor on a system with pre-existing Electrum installation.
Unfortunately, Electrum has a lower-bounds check for library versions but not an upper-bounds check. And given the nature of changes, the incompatibility will manifest at client instantiation time and keeping compatibility wrappers in python-trezor would be tricky.
(mixins are gone, only the `TrezorClient` class is supported, UI is not controlled by callback methods anymore but instead through a separate `ui` instance. I could keep around enough objects so that the import statements don't fail, but at some point things are going to break.)

Instead, I was thinking of raising some sort of descriptive exception at some point, which would tell the users that they need to either downgrade python-trezor or upgrade Electrum.

What would be a good injection point for that?

Another option would perhaps be to detect Electrum in python-trezor code and monkey-patch the `check_libraries_available` method set - hopefully in a way that also works in other Electrum forks.

Thoughts, comments, ideas?

**Comment by SomberNight** [comment]
Note: with python-trezor master, there's an error during plugin init, which is not shown to the user (in the GUI) at all atm.
```
[Plugins] loaded coldcard
[Plugins] loaded digitalbitbox
[Plugins] loaded keepkey
[Plugins] loaded ledger
[Plugins] loaded safe_t
Traceback (most recent call last):
  File "...\electrum\electrum\plugin.py", line 149, in get_hardware_support
    p = self.get_plugin(name)
  File "...\electrum\electrum\plugin.py", line 177, in get_plugin
    self.load_plugin(name)
  File "...\electrum\electrum\plugin.py", line 101, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "...\electrum\electrum\plugins\trezor\trezor.py", line 90, in __init__
    from . import client
  File "...\electrum\electrum\plugins\trezor\client.py", line 11, in <module>
    TrezorClientBase.wrap_methods(TrezorClient)
  File "...\electrum\electrum\plugins\trezor\clientbase.py", line 251, in wrap_methods
    setattr(cls, method, cls.wrapper(getattr(cls, method)))
AttributeError: type object 'TrezorClient' has no attribute 'load_device_by_mnemonic'
[Plugins] cannot load plugin for: trezor
[DeviceMgr] scanning devices...
```

**Comment by SomberNight** [comment]
Note: with python-trezor master, during opening an existing wallet, the following exception is caught and displayed to the user in a dialog:
```
[WalletStorage] wallet path c:\users\user\appdata\roaming\electrum\testnet\wallets\wallet_264
Traceback (most recent call last):
  File "...\electrum\electrum\gui\qt\__init__.py", line 202, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "...\electrum\electrum\daemon.py", line 250, in load_wallet
    wallet = Wallet(storage)
  File "...\electrum\electrum\wallet.py", line 1677, in __new__
    wallet = WalletClass(storage)
  File "...\electrum\electrum\wallet.py", line 1508, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "...\electrum\electrum\wallet.py", line 1372, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "...\electrum\electrum\wallet.py", line 165, in __init__
    AddressSynchronizer.__init__(self, storage)
  File "...\electrum\electrum\address_synchronizer.py", line 85, in __init__
    self.load_and_cleanup()
  File "...\electrum\electrum\wallet.py", line 188, in load_and_cleanup
    self.load_keystore()
  File "...\electrum\electrum\wallet.py", line 1516, in load_keystore
    self.keystore = load_keystore(self.storage, 'keystore')
  File "...\electrum\electrum\keystore.py", line 712, in load_keystore
    k = ks_constructor(d)
  File "...\electrum\electrum\keystore.py", line 695, in hardware_keystore
    return constructor(d)
  File "...\electrum\electrum\plugin.py", line 179, in dynamic_constructor
    return self.get_plugin(name).keystore_class(d)
  File "...\electrum\electrum\plugin.py", line 187, in get_plugin
    self.load_plugin(name)
  File "...\electrum\electrum\plugin.py", line 104, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "...\electrum\electrum\plugins\trezor\trezor.py", line 90, in __init__
    from . import client
  File "...\electrum\electrum\plugins\trezor\client.py", line 11, in <module>
    TrezorClientBase.wrap_methods(TrezorClient)
  File "...\electrum\electrum\plugins\trezor\clientbase.py", line 251, in wrap_methods
    setattr(cls, method, cls.wrapper(getattr(cls, method)))
AttributeError: type object 'TrezorClient' has no attribute 'load_device_by_mnemonic'
```

**Comment by SomberNight** [comment]
> I'd like to bump required version to 0.11 for future Electrum releases, because keeping compatibility between 0.10 and 0.11 is going to be a pain.

Sure. It's not a priority to support old versions.

> Unfortunately, Electrum has a lower-bounds check for library versions but not an upper-bounds check.

We could fix this going forward if you think it's useful. Looks like it might be :)
The problem is that we don't know in advance when compatibility might break; but it could be set to the next non-bugfix version number or similar.

> Instead, I was thinking of raising some sort of descriptive exception at some point, which would tell the users that they need to either downgrade python-trezor or upgrade Electrum.
What would be a good injection point for that?

Well... not sure. With current python-trezor, it seems the failure is before any of the `check_libraries_available` stuff even gets to run. If you get past this, i.e. if this line does not raise
https://github.com/spesmilo/electrum/blob/0862fdb9a9082f78a78dfb566e46b1428d6f5c26/electrum/plugins/trezor/client.py#L11
then you could do something like this:

```patch
diff --git a/trezorlib/client.py b/trezorlib/client.py
index 9440952..f0651f5 100644
--- a/trezorlib/client.py
+++ b/trezorlib/client.py
@@ -80,8 +80,10 @@ class MovedTo:
 class BaseClient(object):
     # Implements very basic layer of sending raw protobuf
     # messages to device and getting its response back.
-    def __init__(self, transport, ui, **kwargs):
+    def __init__(self, transport, ui=None, **kwargs):
         LOG.info("creating client instance for device: {}".format(transport.get_path()))
+        if ui is None:
+            raise Exception("hello there")
         self.transport = transport
         self.ui = ui
         super(BaseClient, self).__init__()  # *args, **kwargs)
```

**Comment by matejcik** [comment]
yes, I was thinking of something like that. Would the `"hello there"` be displayed to the user?

**Comment by SomberNight** [comment]
Yes. I've tested with 3.2.3 and 3.1.3, and that exception text is shown to the user.
(again, unless `TrezorClientBase.wrap_methods(TrezorClient)` raises first)

In any case, I am not sure it's critical to show a helpful message to the user during this particular API breakage; I would say it's more important to have a plan for next time. :)
Do you think a max version check should be added (upper bound)?

**Comment by matejcik** [comment]
perfect.
well, since this API change breaks all currently released versions of Electrum, including various forks, I'd like to notify the users *why* that's happening :)

I would be less worried about next time actually - this particular API breakage makes it difficult to do a proper compatibility wrapper, but I've done that in the past for smaller changes and I expect to be able to do that again in the future.

But yes, an upper bounds check would help. Before we hit 1.0, it should be 0.X <= version < 0.(X+1). After 1.0 i'd just lock on the major version.

**Comment by neocogent** [comment]
Just got this error for the first time today. I didn't know an update occurred but I guess it came down through the repo package system. What is the way to around this right now? Do I have to checkout an older specific tag and install? (I keep master up to date in my dev directory but install system wide often an older version). I'm just unclear what to do so I can open my wallet again.

**Comment by SomberNight** [comment]
What error did you get? I don't see python-trezor 0.11 released yet. Or are you using python-trezor master?

**Comment by neocogent** [comment]
I added end portion of console dump above. I was able to use fine yesterday and haven't touched electrum code. Then today opened wallet and got this. Since then I pulled from electrum master to update myself but still has error. So went looking for a new issue to see if reported. I thought probably need to back up but also wondered why broken without me pulling in any new changes.

Opened my apt package log to see if a package was updated today but don't know what to search for. Nothing found for trezor or electrum.

**Comment by matejcik** [comment]
yeah, trezor requires the mnemonic module.
but 0.11 is not yet released, so it's unrelated to this bug AFAICT

maybe you have python-trezor from pip, which is why the dependency wouldn't be recorded in apt?

**Comment by SomberNight** [comment]
Ok let's track it in https://github.com/spesmilo/electrum/issues/4854

**Comment by neocogent** [comment]
Also tagged python3-ecdsa, python3-hid as not needed. 

Yes, probably I installed using pip but wouldn't that still be tracked? It's odd that it just decided today that these packages could be removed when I've been using for the last month. I do have trezor bridge and latest firmware (0.11 ?) installed by beta-wallet.trezor.io and that was working well for me. Was there possibly an update somewhere there today which rippled through to marking these pkgs as unnecessary? Anyway, I have reinstalled them and will know next time. Just strange that it occurred and without bitcoin when something odd happens it's always best to dig into why as otherwise it could be side effects of malicious tricks.

**Comment by matejcik** [comment]
@neocogent apt only tracks packages installed through apt. If you install a package with pip, apt won't know it's there.
OTOH, pip actually detect whether a package exists, and doesn't care where it comes from.
Here is what i think might have happened:
1. you installed `python3-trezor` from a repo. this pulled in ecdsa, hid, mnemonnic (nothing else uses these packages AFAICT)
2. at some point you upgraded trezor through pip. Possibly you had to remove the distro-provided python3-trezor to make it work. Pip detected that you have the deps on your system so it didn't install them separately.
3. you didn't run autoremove until today, at which point the deps went away and trezor support broke

**Comment by neocogent** [comment]
First, I'd like to apologize for wasting your time on this. I guess it's good it's in the log and someone googling may find this as answer to similar problems. 

At the risk of straying off topic I did a bit more digging in my apt history. On Oct.16 I manually removed python3-trezor. That was the date I received my new trezor one. So presumably while installing that, as you said, I needed to remove the system one. Quick check: repo one was (0.7.16-3) and current is (0.10.2). And although I do autoremoves fairly regularly the most recent was Oct. 8th. I don't know when the old one was installed as it's not in the logs going back about 1 year. So case solved.  discussing the trezor

**Comment by SomberNight** [comment]
We plan to release 3.3 soonish. 1-2 weeks maybe.
This does not need to be in that release of course, just noting.

**Comment by matejcik** [comment]
I think I'm on track for that. I'll open a PR for you to review soon, I'm getting sidetracked by issues like #4806 in the core library :)

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/pull/4875
