### ISSUE TITLE
retry failed lightning payments automatically

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4820]
When the user clicks send, to pay a lightning invoice, the app should automatically handle some cases of failures.
i.e. the app tries a route, sends the onion packet / adds htlc on direct channel. if that htlc fails within (say) <1 second, we can safely attempt paying again (on possibly another route)
On the other hand, if the htlc remains pending for more than a couple seconds, we need to declare failure in the UI, and tell the user the payment is pending. We cannot safely retry.

**Comment by ecdsa** [comment]
this is implemented now
