### ISSUE TITLE
Feature request: customizable block explorer

### ISSUE THREAD

**Issue by buttha** [spesmilo/electrum#4831]
since there're a lot of block explorer out there (and since, for example, I use my own personal block explorer), it would be nice, in settings, having two text input for block explorer, so one can write:

`https://url_explorer?tx={txid}`

`https://url_explorer?addr={address}`

electrum replaces {txid} or {address} with the transaction id / address and opens the browser at that address.

What do you think?

**Comment by SomberNight** [comment]
Can't you already make this work with [BIP-0122](https://github.com/bitcoin/bips/blob/master/bip-0122.mediawiki)?

Just choose `system default` in the dropdown.
https://github.com/spesmilo/electrum/blob/3d4773b1618cb8364b5a9a36018b305552258ad7/electrum/util.py#L650-L651

**Comment by buttha** [comment]
> Can't you already make this work with [BIP-0122]

it's not user friendly, but thank you, I didn't know it!

**Comment by d3spwn** [comment]
For what it's worth, this is how I got Electrum to launch my own block explorer on Windows.

1. set the block explorer in Electrum to `system default`
2. create a batch file to launch the block explorer with the correct url
```
@echo off
set arg=%1
set url=%arg:blockchain:=%
echo %url%
start chrome localhost%url%
```
3. register the URI by adding it to the registry
```
[HKEY_CLASSES_ROOT]
  [blockchain]
      (Default) = "URL:blockchain Protocol Handler"
      URL Protocol = ""
    [DefaultIcon]
       (Default) = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
    [shell]
       [open]
         [command]
           (Default) = "C:\Program Files (x86)\Electrum\blockchain-uri-handler.bat" "%1"
```

**Comment by petrhejna** [comment]
Ubuntu:

1. `sudo vim /usr/share/applications/blockchain-handler.sh`
```
!#/bin/bash

echo $1 | sed 's/blockchain:/https:\/\/192.168.0.38:3021/g' | xargs firefox
```
(Replace `192.168.0.38:3021` with your blockchain explorer)

2. `sudo vim /usr/share/applications/blockchain.desktop`
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=/usr/share/applications/blockchain-handler.sh %u
Name=Blockchain
Comment=Blockchain handler
Icon=
Categories=Application;
MimeType=x-scheme-handler/blockchain;
```

3. `sudo update-desktop-database`
4. `xdg-mime default apt.desktop x-scheme-handler/apt`

Main source: https://askubuntu.com/a/1023143

**Comment by petrhejna** [comment]
However this is terribly non-user friendly. I really believe there should be an setting for it.

**Using third party blockchain explorer poses thread to users privacy.**

**Comment by SomberNight** [comment]
I have an implementation in a PR (https://github.com/spesmilo/electrum/pull/6965), which tries to keep the UI simple (especially for users who would not use this feature).

> it would be nice, in settings, having two text input for block explorer, so one can write:
> `https://url_explorer?tx={txid}`
> `https://url_explorer?addr={address}`
> electrum replaces {txid} or {address} with the transaction id / address and opens the browser at that address.

Adding two text inputs would complicate the UI too much for a niche feature.
Also, AFAICT most block explorers use the same URL structure. Still, if you do need to customise this too, the PR above exposes it (though not in a simple way).

**Comment by buttha** [comment]
great, thank you!
