### ISSUE TITLE
Paytomany JSON-RPC

### ISSUE THREAD

**Issue by arcaelas** [spesmilo/electrum#4837]
I did try send command to **http://127.0.0.1:8332/** with next  $_POST params:
`{"method":"paytomany","params":[{"outputs":[{"1JSRYx9oiti21y6zNiZsvHfQnrnDhdDT4J":"0.00000001"},{"1CHdhn8c8bVcMKzLD4M8sMomR8HyKxpXao":"0.00000001"},{"1KGmuB7qua2seXUbKEeb83WhL5mfEXKeGF":"0.00000001"},{"16YhrbvD8Se69VVYsvimDXbWQis8jAoos":"0.00000001"},{"1CrbAqScVB4BB1Kd4RS6UPbRKELaxu86kh":"0.00000001"}],"fee":1.0e-5,"from":["18jkwUXwDYGXz9raoRdmGWjJFYQV3uu17Y"],"change":false,"nocheck":false,"password":"arcaelas123","unsigned":false}],"id":"curltext"}`

on cURL, my curl_init() connect successfully but response is **Password is required** how to do?

Code lines:
```
    public function __call($method, $params) {
        $params = array_values($params);
        $request = json_encode(array(
            'method' => $method,
            'params' => $params,
            'id'     => $this->id
        ));
        $url = "{$this->proto}://{$this->host}:{$this->port}/{$this->url}";
        $curl    = curl_init($url);
        $options = array(
            CURLOPT_HTTPAUTH       => CURLAUTH_BASIC,
            CURLOPT_USERPWD        => $this->username . ':' . $this->password,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS      => 10,
            CURLOPT_HTTPHEADER     => array('Content-type: application/json'),
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => $request
        );
        if (ini_get('open_basedir')) {
            unset($options[CURLOPT_FOLLOWLOCATION]);
        }
        if ($this->proto == 'https') {
            if (!empty($this->CACertificate)) {
                $options[CURLOPT_CAINFO] = $this->CACertificate;
                $options[CURLOPT_CAPATH] = DIRNAME($this->CACertificate);
            } else {
                $options[CURLOPT_SSL_VERIFYPEER] = false;
            }
        }
        curl_setopt_array($curl, $options);
        $response = curl_exec($curl);

```

**Comment by SomberNight** [comment]
What version are you on? On master, this works for me:

```
$ ./run_electrum daemon start --testnetstarting daemon (PID 2387)

$ ./run_electrum daemon --testnet load_wallet -w ~/.electrum/testnet/wallets/test_segwit_asdasd
Password:
true
```

`$ curl --data-binary '{"id":"curltext","method":"paytomany","params":{"outputs":[["tb1qq0g39r3n38y37t6yptru564m9vme6szjjy0nks", 0.001], ["tb1qqdkj9feahthysuwdypxznwu94w4hl0uqyj3x5p", 0.002], ["tb1qsl5sn4frf4tu0f3zajgv3ggqgx6wjqk8sdejjv", 0.0015]], "fee": 0.00005, "password":"1234"}}' http://user:pass@127.0.0.1:7778
`
`{"result": {"hex": "010000000001014d7a9a1e2d5537a1642356cb6aaa5aad2837b0f7d05ce4419be08a85f6774cae0100000000fdffffff044c9a00000000000016001408195125bd0bb88c62ac7e9c94ccf031d3da40f0a08601000000000016001403d1128e3389c91f2f440ac7ca6abb2b379d4052f04902000000000016001487e909d5234d57c7a622ec90c8a10041b4e902c7400d030000000000160014036d22a73dbaee4871cd204c29bb85abab7fbf80024730440220009a3813d86e14732721cecc6f2f2559edf79331d38de8fbf69abd6da0a37ebe022064ae6d1e320985302b76b1de04f6f9a462e5b646c9b6b2fe2f2cbd242e91c6d40121035a3aa6e2772f035395683fa37d6be6bc67200ab7c92859614d4f2df2cdb1ea39b7031600", "complete": true, "final": false}, "id": "curltext", "error": null}`

**Comment by arcaelas** [comment]
Version is "Electrum 3.2.3", i did try call paytomany on console and need password but dont shown password prompt;

And i dont know to do paytomany on PHP JSON-RPC

**Comment by arcaelas** [comment]
> What version are you on? On master, this works for me:
> 
> ```
> $ ./run_electrum daemon start --testnet
> starting daemon (PID 2387)
> 
> $ ./run_electrum daemon --testnet load_wallet -w ~/.electrum/testnet/wallets/test_segwit_asdasd
> Password:
> true
> ```
> `$ curl --data-binary '{"id":"curltext","method":"paytomany","params":{"outputs":[["tb1qq0g39r3n38y37t6yptru564m9vme6szjjy0nks", 0.001], ["tb1qqdkj9feahthysuwdypxznwu94w4hl0uqyj3x5p", 0.002], ["tb1qsl5sn4frf4tu0f3zajgv3ggqgx6wjqk8sdejjv", 0.0015]], "fee": 0.00005, "password":"1234"}}' http://user:pass@127.0.0.1:7778 `
> `{"result": {"hex": "010000000001014d7a9a1e2d5537a1642356cb6aaa5aad2837b0f7d05ce4419be08a85f6774cae0100000000fdffffff044c9a00000000000016001408195125bd0bb88c62ac7e9c94ccf031d3da40f0a08601000000000016001403d1128e3389c91f2f440ac7ca6abb2b379d4052f04902000000000016001487e909d5234d57c7a622ec90c8a10041b4e902c7400d030000000000160014036d22a73dbaee4871cd204c29bb85abab7fbf80024730440220009a3813d86e14732721cecc6f2f2559edf79331d38de8fbf69abd6da0a37ebe022064ae6d1e320985302b76b1de04f6f9a462e5b646c9b6b2fe2f2cbd242e91c6d40121035a3aa6e2772f035395683fa37d6be6bc67200ab7c92859614d4f2df2cdb1ea39b7031600", "complete": true, "final": false}, "id": "curltext", "error": null}`

No working on RPC

**Comment by arcaelas** [comment]
**JSON-RPC <- cURL**
`
{"method": "paytomany", "params": [{"password": "", "fee": "0.00004", "outputs": [["tb1qfl6n8lmk0sy7tua6cxtc5spx9m4jycx0rep6vu", "0.0004"] ] } ], "id": "curltext"}
`


**cURL RESPONSE**
<Fault -32603: Server error: File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 488, in _mktx | ValueError: too many values to unpack (expected 2)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 97, in func_wrapper
    return func(*args, **kwargs)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 518, in paytomany
    tx = self._mktx(outputs, tx_fee, change_addr, domain, nocheck, unsigned, rbf, password, locktime)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 488, in _mktx
    for address, amount in outputs:
ValueError: too many values to unpack (expected 2)

**Comment by SomberNight** [comment]
You have an extra nesting for the value of `params`.

Try
`{"method": "paytomany", "params": {"password": "", "fee": "0.00004", "outputs": [["tb1qfl6n8lmk0sy7tua6cxtc5spx9m4jycx0rep6vu", "0.0004"]]}, "id": "curltext"}'`

**Comment by arcaelas** [comment]
> You have an extra nesting for the value of `params`.
> 
> Try
> `{"method": "paytomany", "params": {"password": "", "fee": "0.00004", "outputs": [["tb1qfl6n8lmk0sy7tua6cxtc5spx9m4jycx0rep6vu", "0.0004"]]}, "id": "curltext"}'`

That is good, but:

**PHP**
`$cURL->paytomany($params);`
**Return: $response_a**
*45505446.......................*

**Then:**
`$cURL->signtransaction($response_a);`
**Return: $response_b**
*01000000000101...............*

**Later try:**
`$cURL->broadcast($response_b);`
**Response:**
*Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 469, in send_request | aiorpcx.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\n16: bad-txns-vin-empty\n[01000000000101...................]')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 97, in func_wrapper
    return func(*args, **kwargs)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 331, in broadcast
    return self.network.run_from_another_thread(self.network.broadcast_transaction(tx))
  File "/media/arcaela/server/Blockchain/git_files/electrum/network.py", line 234, in run_from_another_thread
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/media/arcaela/server/Blockchain/git_files/electrum/network.py", line 697, in make_reliable_wrapper
    raise success_fut.exception()
  File "/media/arcaela/server/Blockchain/git_files/electrum/network.py", line 713, in broadcast_transaction
    out = await self.interface.session.send_request('blockchain.transaction.broadcast', [str(tx)], timeout=timeout)
  File "/media/arcaela/server/Blockchain/git_files/electrum/interface.py", line 81, in send_request
    timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 469, in send_request
    raise result
aiorpcx.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\n16: bad-txns-vin-empty\n[01000000000101.....................]')*


### Now, ¿what to do?

**Comment by arcaelas** [comment]
I cant, i dont know why:


**PHP:**
$outputs = array(
	array('tb1qspe63t2n87rhvum9h02mktnk58jxz6sz4eyued','0.00004'),
);
$pay = array(
	'unsigned'=>true,
	'fee'=>((30*300)/100000000),
	'outputs'=>$outputs,
);
$hex=$blockchain->paytomany($pay);
if ($hex=$hex['response']) {
	$hex = $hex['hex'];
	// echo "(a) HEX:\n$hex\n\n";
	$sign = $blockchain->signtransaction($hex);
	if ($sign=$sign['response']) {
		$sign = $sign['hex'];
		// echo "(b) BIN:\n$sign\n\n";
		$broadcast = $blockchain->broadcast($sign);
		// echo "(c) BROADCAST:\n$broadcast\n\n";
		print_r($broadcast);
		exit();
	}
	else{
		echo "Error:\n";
		print_r($sign);
	}
}
else{
	echo "Error:\n";
	print_r($hex);
}


**RESPONSE:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 378, in _dispatch
    return func(**params)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 94, in func_wrapper
    raise Exception("wallet not loaded. Use 'electrum daemon load_wallet'")
Exception: wallet not loaded. Use 'electrum daemon load_wallet'
Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 469, in send_request | aiorpcx.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\n16: bad-txns-vin-empty\n[01000000000101d313272784243b360215479c9d4439166f32df53a376853afcedf5d98b9618c80000000000fdffffff02a00f0000000000001600148073a8ad533f87767365bbd5bb2e76a1e4616a0278690000000000001600144ff533ff767c09e5f3bac1978a40262eeb2260cf02483045022100b364d0dee4ad14ae89d84bb842eaec2126522648ddc6a52c82e4373a3de87b6502200e400513001088a4ca989177e5ecd50932b186ee209afdff88c1307eb5fc84eb0121033e90b4da418444c6a3b7f95749e8ed01a0f8e01b2f98c96c7e33622e8d27b6cbff091600]')
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
    return func(*params)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 97, in func_wrapper
    return func(*args, **kwargs)
  File "/media/arcaela/server/Blockchain/git_files/electrum/commands.py", line 331, in broadcast
    return self.network.run_from_another_thread(self.network.broadcast_transaction(tx))
  File "/media/arcaela/server/Blockchain/git_files/electrum/network.py", line 234, in run_from_another_thread
    return fut.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/media/arcaela/server/Blockchain/git_files/electrum/network.py", line 697, in make_reliable_wrapper
    raise success_fut.exception()
  File "/media/arcaela/server/Blockchain/git_files/electrum/network.py", line 713, in broadcast_transaction
    out = await self.interface.session.send_request('blockchain.transaction.broadcast', [str(tx)], timeout=timeout)
  File "/media/arcaela/server/Blockchain/git_files/electrum/interface.py", line 81, in send_request
    timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 469, in send_request
    raise result
aiorpcx.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\n16: bad-txns-vin-empty\n[01000000000101d313272784243b360215479c9d4439166f32df53a376853afcedf5d98b9618c80000000000fdffffff02a00f0000000000001600148073a8ad533f87767365bbd5bb2e76a1e4616a0278690000000000001600144ff533ff767c09e5f3bac1978a40262eeb2260cf02483045022100b364d0dee4ad14ae89d84bb842eaec2126522648ddc6a52c82e4373a3de87b6502200e400513001088a4ca989177e5ecd50932b186ee209afdff88c1307eb5fc84eb0121033e90b4da418444c6a3b7f95749e8ed01a0f8e01b2f98c96c7e33622e8d27b6cbff091600]')

**Comment by arcaelas** [comment]
Dont wrong pls, i have 2 week trying and research, i speak spanish and alls forums is in english, is so hard... help me pls

**Comment by SomberNight** [comment]
> try with another server

```
$ ./run_electrum --testnet setconfig auto_connect False
$ ./run_electrum --testnet setconfig server testnet.qtornado.com:51002:s
```

**Comment by arcaelas** [comment]
(a) Paytomany: 

45505446ff0001000000000101d313272784243b360215479c9d4439166f32df53a376853afcedf5d98b9618c80000000000feffffff02a00f0000000000001600148073a8ad533f87767365bbd5bb2e76a1e4616a027869000000000000160014c4ebd87ae51d826f84116a55264492d0a38ace5afeffffffff409c00000000000000000201ff53ff045f1cf601762b51ca800000002a27b37905641ecf398a2c6b7d44bdbae9a66c1771d74697170f19508f29ea1002bb91e916c9055df9dd090fa64197de3210d6a2697c13bbe2635e3f6b11c8e18700000600020a1600

(b) Signtransaction:

01000000000101d313272784243b360215479c9d4439166f32df53a376853afcedf5d98b9618c80000000000feffffff02a00f0000000000001600148073a8ad533f87767365bbd5bb2e76a1e4616a027869000000000000160014c4ebd87ae51d826f84116a55264492d0a38ace5a0247304402201b114fb96680615c0785e699ecdb74ecaa09db2030661a95e901d460c6ed146b022060d5b94057d859b20918276504b115c4965942a1f9a0e61e8f1a24feef579cc30121033e90b4da418444c6a3b7f95749e8ed01a0f8e01b2f98c96c7e33622e8d27b6cb020a1600

(c) Broadcast:

Server error: File "/usr/local/lib/python3.6/dist-packages/aiorpcx/session.py", line 469, in send_request \| aiorpcx.jsonrpc.RPCError: (1, 'the transaction was rejected by network rules.\n\n16: bad-txns-vin-empty\n[01000000000101d313272784243b360215479c9d4439166f32df53a376853afcedf5d98b9618c80000000000feffffff02a00f0000000000001600148073a8ad533f87767365bbd5bb2e76a1e4616a027869000000000000160014c4ebd87ae51d826f84116a55264492d0a38ace5a0247304402201b114fb96680615c0785e699ecdb74ecaa09db2030661a95e901d460c6ed146b022060d5b94057d859b20918276504b115c4965942a1f9a0e61e8f1a24feef579cc30121033e90b4da418444c6a3b7f95749e8ed01a0f8e01b2f98c96c7e33622e8d27b6cb020a1600]')

**Comment by SomberNight** [comment]
run
```
./run_electrum --testnet daemon status
```

what is the output?

**Comment by arcaelas** [comment]
QTornado is offline, but try with **testnet.hsmiths.com** and running successfully, i am happy, i using Electrum for 2 years, now i can create a blockchain, need read about your repositorie, sorry for your time, maybe i'll can help you how contribuitor....

**Thanks very much.**
