### ISSUE TITLE
Error : "qt.qpa.screen: QXcbConnection: Could not connect to display"

### ISSUE THREAD

**Issue by vinnyvoo** [spesmilo/electrum#4840]
Error while trying to run daemon.

```
root@vinnyvoo# python3 run_electrum --daemon
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```
i'm on a non desktop mode machine. Is that the problem?
Thank you.

**Comment by vinnyvoo** [comment]
sorry. wrong command. actually its "python3 run_electrum.py daemon start".

**Comment by bauerj** [comment]
> i'm on a non desktop mode machine. Is that the problem?

Yes. I think you want to use `python3 run_electrum.py daemon`
