### ISSUE TITLE
Electrum | Custom dir run | Linux Ubuntu

### ISSUE THREAD

**Issue by arcaelas** [spesmilo/electrum#4843]
I've Electrum Developer version (GITHUB), i did clone repositorie in /media/arcaela/server Or /dev/sdb1
I need run electrum from there, if run electrum command on console automatically create .electrum folder in /root/.electrum how to do run from sdb1 ?

**Comment by SomberNight** [comment]
To create the datadir locally, try running with the `--portable` option.
or you can specify a custom dir with `--dir`
