### ISSUE TITLE
Error when building Windows binaries on Ubuntu

### ISSUE THREAD

**Issue by limxdev** [spesmilo/electrum#4846]
-rwxr-xr-x  1 blabla blabla    14336 Nov 11 12:51 QtWebEngineProcess.exe
drwxr-xr-x  2 blabla blabla     4096 Nov 11 12:43 Scripts
-rw-r--r--  1 blabla blabla   276992 Nov 11 12:51 ssleay32.dll
drwxr-xr-x  7 blabla blabla     4096 Nov 11 11:18 Tools
-rw-r--r--  1 blabla blabla    83792 Nov 11 12:51 vcruntime140.dll
/opt/wine64/drive_c/electrum ~/Desktop/eletrumspemilo/electrum-3.2.3/contrib/build-wine/tmp
Last commit: untagged-4ff4fd6546b7feddbc16-1-g9d1df251-dirty
./build-electrum-git.sh: line 31: pushd: ./contrib/deterministic-build/electrum-locale: No such file or directory

Can some explain that?

Kind Regards Christian

**Comment by SomberNight** [comment]
Why did you close the issue? Have you figured out what the cause was?
