### ISSUE TITLE
2.9.3 version - +0 transaction - Synchronizing.... Issue

### ISSUE THREAD

**Issue by colbycolby45** [spesmilo/electrum#4850]
Hello. I have wallet 2.9.3 version - on my PC(laptop Lenovo  Win8)
I have yesterday +0 transaction -  and see status Synchronizing.... It is Issue
coze when I was try to send some BTC to another wallet - I saw Error:{u'message': u 'the transaction was rejected by network rules.\n\nMissing inputs\m[0100000.....afu'code': 1}
U can see it on screenpage in this upload jpg - https://www.sendspace.com/file/c4cwvz
What must I do now? can u write me by email?  colbycolby45@protonmail.com

**Comment by SomberNight** [comment]
You should update to the latest version of Electrum. The issue you describe should already be fixed in newer versions.

**Comment by colbycolby45** [comment]
> You should update to the latest version of Electrum. The issue you describe should already be fixed in newer versions.
But I want use last version. is it real?
