### ISSUE TITLE
Which parts of certificates are verified?

### ISSUE THREAD

**Issue by wisbwond** [spesmilo/electrum#4857]
Does client verify cert params like FQDN (or IP), etc ?

**Comment by SomberNight** [comment]
Do you mean for electrum servers? Then see:
https://github.com/spesmilo/electrum/blob/32af83b7aede02f0b9bb3e8294ef2dc0481fb6de/electrum/interface.py#L229-L247

**Comment by wisbwond** [comment]
no, i mean the client software. Will it verify ip address or domain in certificate provided by server?

**Comment by SomberNight** [comment]
Yes, I am talking about the client software. I was asking what certificates you meant. Re TLS certificates for electrum servers, see code above. It is all defaults basically, up to Python stdlib; except for the self-signed certificates where we skip verifying the FQDN.

**Comment by wisbwond** [comment]
> for the self-signed certificates where we skip verifying the FQDN.

right, that what i'm expecting. sweet.
