### ISSUE TITLE
Android GUI very slow/unresponsive

### ISSUE THREAD

**Issue by solinium** [spesmilo/electrum#4867]
On the latest version of the app, Android 8.1.0, Mi A2
The app works completely like expected except there is a several second delay after tapping until your press is registered in the app, essentially making it extremely slow, unresponsive and hard to use. You tap, and then 2-3 seconds later the button you press is highlighted indicating you pressed it, and even after the button is pressed it definitely seems to respond much slower than expected indicating that not only the input but the whole app is extremely slow, making it very frustrating to use. I didn't see anything noteworthy in logcat but I can post it if needed, this just seems like a general performance problem. I am on the stock Mi A2 ROM with a custom kernel if that matters, but this doesn't seem to happen with any other app so it seems to be isolated to electrum.

Besides this, the desktop version is a fantastic piece of software and I just wish I could use it on my phone as well. I can also post a video of this if needed, but all it is is the app generally behaves much, much slower than it should.
Thanks in advance!

**Comment by ecdsa** [comment]
hello,
maybe you can try to uninstall and reinstall the app 
(you will have to restore your wallet from seed)

**Comment by solinium** [comment]
Fixed after flashing different kernel. Probably just an issue on my end. Closing.
