### ISSUE TITLE
no connection to the network

### ISSUE THREAD

**Issue by holger316** [spesmilo/electrum#4878]
Hello, 
I have updated to the electurm 3.2.3. 
and now I dont get connection to a server. 
I have tryed differnt server, nothing happens, what can I do?

**Comment by SomberNight** [comment]
- Did an earlier version work, if so which one?
- What operating system is this on?
- Is your network behind a strict firewall (e.g. corporate workplace)?

You can try running the Tor Browser Bundle (or tor process) and set a Tor SOCKS proxy in the network dialog in Electrum.

**Comment by removebreeze** [comment]
I am using Tor and version 3.3.2. This has been a constant issue on every version I have used. Sometimes I just need to wait 15min, and sometimes it never connects at all. Very annoying.

I am currently using my home internet via Tor. I have connected a few times with the last version, but it was hit or miss, so I upgraded. I believe I connected once with this new version. I have tried multiple servers including select one automatically, deleted my cache and config, deleted Electron and reunziped it.

It would really be nice if a feature were added telling me WTF is going on when it is attempting to connect.

**Comment by removebreeze** [comment]
Tails 3.10.1 btw, in case it matters

**Comment by removebreeze** [comment]
Hmmm... Tor Socks proxy worked like a charm... I should have tried that before posting

**Comment by AbdussamadA** [comment]
please add more details if you can so that others in the same situation can learn from this and then mark the issue closed

**Comment by holger316** [comment]
Thanks for your message,
My earlier version was 2.8.3 it was running good.
My system is Win 10 Pro.
I have tryed with deaktivated firewall, with the same result, no conection.
I do not now how to use Tor Browser Bundle....

On my second PC, Win7 Home Premium, is still the old Electum Version.
There it is synchronizing, but I am not sure if it is working, and how long I have to wait...

**Comment by SomberNight** [comment]
Electrum 2.8.3 will almost surely not be able to synchronize anymore.

Re the machine with the new version; what do you see in the bottom left corner of the window -- what does it say there? What about the colour of the orb/circle in the bottom right?

**Comment by holger316** [comment]
I have update on my old PC and Electrum is running fine.
On the newer one Win10 PC has nothing changed.
In the bottom there it saying "Nicht verbunden" (not connected) left side and a red circle on the red side.
In the History there are my previous transacions with "Not Verified" at Date.

**Comment by SomberNight** [comment]
Download the Tor browser https://www.torproject.org/projects/torbrowser.html.en
start it; leave it running in the background
in Electrum, click the orb/circle in bottom right > `Proxy` tab > `Use Tor proxy`

**Comment by holger316** [comment]
ok, now it is running.
Thanks for your help! Tor makes it possible...

**Comment by SomberNight** [comment]
well I would still be interested in the reason why it is failing without Tor, if you manage to figure it out
