### ISSUE TITLE
Sweeping A Single Private Key via Command Line

### ISSUE THREAD

**Issue by Cryptonizor** [spesmilo/electrum#4889]
According to your documentation, you can sweep all of the existing private keys in Electrum to a specified address like this:

> `electrum listaddresses --funded | electrum getprivatekeys - | jq 'map(.[0])' | electrum sweep - [destination address]`

Example Private Key:

`KxhhD4aPYgAcKWJJNmUXHLQKnKjX8gbZNv6ehfPfWkCKAxWMU3uQ`

Example Receiving Address:

`1LzkzfpwpSrxxD6AQyHhMXUWj9FaXqCEgt`

If I wanted to sweep the Example Private Key's funds to the Example Receiving Address, what command would I need to enter in terminal?  Assume that neither the Example Private Key nor the Example Receiving Address are currently in my Electrum wallet.

Also, will Electrum allow you to sweep unconfirmed funds from a private key?  Obviously the transaction creating by the sweep won't confirm until the original transaction(s).  I was just making sure that Electrum wasn't just going to try to only sweep funds that already have X number of confirmations.

If I didn't make anything clear enough above, please let me know.

Thanks in advance!

**Comment by SomberNight** [comment]
`electrum sweep privkey addr`
```
electrum daemon start
electrum sweep KxhhD4aPYgAcKWJJNmUXHLQKnKjX8gbZNv6ehfPfWkCKAxWMU3uQ 1LzkzfpwpSrxxD6AQyHhMXUWj9FaXqCEgt
```
> will Electrum allow you to sweep unconfirmed funds from a private key?

Yes. It used to not sweep unconfirmed coins but now it does (due to a server side change). The error message will stay suggest otherwise if it can't find coins.

**Comment by Cryptonizor** [comment]
Thanks for the quick answer!

Can you confirm if this is the correct command to sweep and broadcast?

    electrum sweep KxhhD4aPYgAcKWJJNmUXHLQKnKjX8gbZNv6ehfPfWkCKAxWMU3uQ 1LzkzfpwpSrxxD6AQyHhMXUWj9FaXqCEgt | electrum broadcast -

**Comment by AbdussamadA** [comment]
@Cryptonizor Yes that'll work. Note electrum supports testnet wallets with the --testnet switch. They are useful for testing things. You can get free testnet bitcoins from faucets.
