### ISSUE TITLE
Disable dynamic fee

### ISSUE THREAD

**Issue by kodxana** [spesmilo/electrum#4898]
Is there a way to disable dynamic fee slider, and enable the custom fee box by default?
Aka so people be forced to set fee manually.

**Comment by SomberNight** [comment]
Re showing custom fee box, see https://github.com/spesmilo/electrum/blob/e8a8a172174ff49adff556be6b025fc6853b20ad/electrum/gui/qt/main_window.py#L2736-L2743

Re fee slider, search for `fee_slider` in the same file
