### ISSUE TITLE
overflow error

### ISSUE THREAD

**Issue by rhinox77** [spesmilo/electrum#4899]
this bug in my electrum 3.2.2
argument 1: <class 'OverflowError'>: int too long to convert

**Comment by SomberNight** [comment]
how to reproduce?
please give more details

**Comment by rhinox77** [comment]
this bug when i want send vertcoin from wallet get this error message i have latest version electrum 3.2.2
![2018-12-06_21h17_04](https://user-images.githubusercontent.com/35309813/49609765-c62f4080-f99c-11e8-876e-faf4a31efc3c.jpg)

**Comment by SomberNight** [comment]
Electrum is for Bitcoin only. The forks of the project for different altcoins are maintained by different people. Try asking here https://github.com/vertcoin-project/electrum-vtc

Actually it looks like it's already reported at https://github.com/vertcoin-project/electrum-vtc/issues/106
