### ISSUE TITLE
QTreeView + sort model + QStandardItemModel is not efficient performance

### ISSUE THREAD

**Issue by wo01** [spesmilo/electrum#4911]
If there are a few thousands of histories, it takes many seconds to update the list.
Therefore, the window freezes every update.
```
[profiler] HistoryList.update 30.9912
```

I found the following problem.
https://forum.qt.io/topic/55272/qtreeview-sort-model-qstandarditemmodel-the-most-efficient-way-to-update-the-model

**Comment by ecdsa** [comment]
are you on the latest HEAD? how many lines are in your history?

**Comment by ecdsa** [comment]
try the `qabstractitemmodel` branch. we will merge it soon.

**Comment by wo01** [comment]
Yes, I am using latest HEAD.
There are about 3000 lines.
OK, thanks. I will try the branch.
