### ISSUE TITLE
[Qt] Possible bug in qt/util.py -> MessageBoxMixin.top_level_window

### ISSUE THREAD

**Issue by cculianu** [spesmilo/electrum#4913]
What exactly is the rationale behind this function?

https://github.com/spesmilo/electrum/blob/762082e13d7e9db7c1ca603a04d9dc1aebe8b0af/electrum/gui/qt/util.py#L184

I suppose the rationale is to show chained message boxes such that each one in a chain is parented to the most recent one.

On Mac --  it produces buggy results.

--- 

UPDATE:  

I'm attaching a sample test script to illustrate the issue.  While the situation seems contrived -- it's a real world situation in Electron Cash (and I suspect Electrum) -- specifically in the "Internal" and "External" plugins windows which themselves quite often spawn windows themselves. 

The symptoms: Dialog windows pop up, sometimes in a chained manner through normal use of the app.  On Linux and Windows this is fine.  On macOS, after dismissing the dialogs, the original base (main window) no longer responds to user events (clicks, etc).

This script illustrates the bug.  If you run it on Windows and Linux, you can dismiss all the spawned windows and eventually you get back to the base window, and the "Quit" button works.

On macOS, after dismissing the spawned dialogs -- the base window is no longer able to be interacted with.

Here is the script as a gist: https://gist.github.com/cculianu/5c7b5bc550b4211fb48fe079ed946365

Here it is as a file: 
[test_mac_chained_dialogs.txt](https://github.com/spesmilo/electrum/files/2660728/test_mac_chained_dialogs.txt)

**Comment by kyuupichan** [comment]
@cculianu why don't you fix it in EC rather than expecting Electrum to do it?

**Comment by cculianu** [comment]
@kyuupichan Why else? So you can show up and grace this issue with your lovely sunshiny presence, of course.

**Comment by kyuupichan** [comment]
@cculianu if you try to "fix" it you might find out why it is the way it is; rather than expecting others to waste their time for you

**Comment by cculianu** [comment]
Jesus man, you have issues.

**Comment by cculianu** [comment]
I'm closing this issue because I really don't appreciate your toxicity.  In the future please refrain from commenting in anything either on here or in EC unless you have something relevant to say.

**Comment by SomberNight** [comment]
> Not ever allowing a message box's parent to be self which is undefined behavior in Qt.

https://github.com/spesmilo/electrum/blob/62e352a2a8e61ae930b6a09b1457d5419afea35c/electrum/gui/qt/util.py#L222-L233

The message box is not its own parent though? `d.parent == self` but note that self is not d in this case
What exactly is the undefined behaviour?
