### ISSUE TITLE
Fix Android build

### ISSUE THREAD

**Issue by wo01** [spesmilo/electrum#4929]
To build Android apk, your python-for-android needs the following patches.

https://github.com/kivy/python-for-android/commit/d8e3d516eb4409d3b97fb2b0ed889343ba6d233a

https://github.com/kivy/python-for-android/commit/fbb5a2887a532d5576b5d7cd57c4f1d458de72f6

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/commit/67b2aebed67988c733b3258fdc020e4ca9d2a409
