### ISSUE TITLE
remove 'requests' as a dependency

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4931]
`requests` is almost never used in the code anymore. Mostly replaced with `aiohttp`.
The remaining occurrences should be removed, and then `requests` will no longer be a dependency.

One remnant is in the `greenaddress` plugin:
https://github.com/spesmilo/electrum/blob/78f5afff7461830951245c971cec02e19d401edf/electrum/plugins/greenaddress_instant/qt.py#L92

**Comment by ecdsa** [comment]
I removed requests from requirements.txt. 
@greenaddress could you check that this works: 75f6ab913316998e1e3c4b1d256de17bc367ea8e

**Comment by ecdsa** [comment]
note: 'requests' is still required by trezorlib
