### ISSUE TITLE
Bitcoins STUCK in my Electrum Wallet

### ISSUE THREAD

**Issue by Tigrovaya** [spesmilo/electrum#4933]
I transferred 75 mBitcoins to my wallet last week.  Seems there was an issue with previous transfer of 50 mBitcoins which I spent but are still showing in there.  I spent 50mBc last week, so I should have 25, but is showing 75 and I can't transfer ANY out.  I get an 'Input Missing' error.
![electrum 3](https://user-images.githubusercontent.com/45901235/50045470-40da1900-008b-11e9-9267-b3f18695257b.JPG)
![electrum 1](https://user-images.githubusercontent.com/45901235/50045471-45063680-008b-11e9-9ccb-ebfeb132a040.JPG)
![electrum 2](https://user-images.githubusercontent.com/45901235/50045472-48012700-008b-11e9-9db3-18acb9608721.JPG)

**Comment by SomberNight** [comment]
What version of Electrum is this? Looks < 3.1.0. Try updating first.

**Comment by Tigrovaya** [comment]
It's actually version 2.8.0   :)
Which version should I download?
  I use a standalone PC using Windows 10.

![electrum 4](https://user-images.githubusercontent.com/45901235/50046435-2f990880-009b-11e9-94be-51151890aa71.JPG)

**Comment by Tigrovaya** [comment]
Uploaded new version … all looks good.  MANY THANKS!!!
