### ISSUE TITLE
Synchronisation 

### ISSUE THREAD

**Issue by MadmaxELECTRO** [spesmilo/electrum#4935]
I send btc on to my electroneum wallet and when i open my wallet, the transaction is empty (0) and electroneum can not synchronise, could you help me ?

**Comment by SomberNight** [comment]
Update to latest version of Electrum.

**Comment by ecdsa** [comment]
we do not support electroneum

**Comment by MadmaxELECTRO** [comment]
i update and it works ! thx !

**Comment by MadmaxELECTRO** [comment]
i update and it works ! thx !
