### ISSUE TITLE
Mac Gatekeeper still warns about signed binary

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#4947]
The 3.3.0 Mac binary is supposedly signed, however Gatekeeper is still warning about it as if it was not.
![mac_gatekeeper](https://user-images.githubusercontent.com/29142493/50284456-5a97a980-0459-11e9-9794-92eeafbb2afa.PNG)
```
$ codesign -dvvv electrum-3.3.0.dmg
Executable=/Users/user/Desktop/electrum-3.3.0.dmg
Identifier=electrum-3
Format=disk image
CodeDirectory v=20200 size=298 flags=0x0(none) hashes=1+6 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=ce35d9e30a99cc0f84e69a018021120d82ff4fd1
Hash choices=sha256
CDHash=ce35d9e30a99cc0f84e69a018021120d82ff4fd1
Signature size=4699
Authority=3rd Party Mac Developer Application: Electrum Technologies GmbH (L6P37P7P56)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=19 Dec 2018 at 05:04:51
Info.plist=not bound
TeamIdentifier=L6P37P7P56
Sealed Resources=none
Internal requirements count=1 size=204
```
```
$ codesign --verify --deep --strict --verbose=2 electrum-3.3.0.dmg && echo "signed"
electrum-3.3.0.dmg: valid on disk
electrum-3.3.0.dmg: satisfies its Designated Requirement
signed
```
related: https://developer.apple.com/library/archive/technotes/tn2206/_index.html

**Comment by SomberNight** [comment]
see https://discussions.apple.com/thread/5878943

> You are signing with a development certificate ("Authority=Mac Developer…"), not a distribution certificate ("Authority=Developer ID…"). You need to apply for Developer ID and sign with your Developer ID certificate instead.

> Authority=3rd Party Mac Developer Application: Electrum Technologies GmbH (L6P37P7P56)

**Comment by ecdsa** [comment]
should be fixed now
