### ISSUE TITLE
clock5.png icon at wrong angle (can't unsee)

### ISSUE THREAD

**Issue by markblundeberg** [spesmilo/electrum#4954]
![clock5.png](https://raw.githubusercontent.com/spesmilo/electrum/edb6de92d87262a5678f47817bf87ae764379c10/icons/clock5.png)

Unfortunately, the hand of the above clock is at 7/8ths instead of 5/6ths. This may cause problems with OCD users once they notice it...

:-D

**Comment by bauerj** [comment]
I consulted with a real clock and I hope this should be accurate now (please correct me if it isn't):

![clock1](https://user-images.githubusercontent.com/598790/50363341-75f2d980-056b-11e9-8bc1-5d1460fb1ecd.png)
![clock2](https://user-images.githubusercontent.com/598790/50363342-75f2d980-056b-11e9-9831-498091f0fcfe.png)
![clock3](https://user-images.githubusercontent.com/598790/50363343-75f2d980-056b-11e9-828e-213fd49ef84b.png)
![clock4](https://user-images.githubusercontent.com/598790/50363344-75f2d980-056b-11e9-8dc4-4734360855ed.png)
![clock5](https://user-images.githubusercontent.com/598790/50363340-755a4300-056b-11e9-9e24-a3bc62f970c8.png)

**Comment by markblundeberg** [comment]
Highly accurate!
