### ISSUE TITLE
TLS certificate error on https://docs.electrum.org/

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#4956]
The TLS certificate on https://docs.electrum.org/ gives the following error (using Tor Browser; tried multiple circuits):

~~~
docs.electrum.org uses an invalid security certificate.

The certificate is only valid for the following names: 
*.readthedocs.org, readthedocs.org

Error code: SSL_ERROR_BAD_CERT_DOMAIN
~~~

Any chance that could be fixed?  It's rather unfortunate that in 2018 a major Bitcoin wallet points users to a non-TLS website for documentation....

**Comment by SomberNight** [comment]
related https://github.com/spesmilo/electrum-docs/issues/35

**Comment by bauerj** [comment]
Closing this in favour of the issue in electrum-docs.
