### ISSUE TITLE
Animated QR code for extra-large transactions?

### ISSUE THREAD

**Issue by andronoob** [spesmilo/electrum#4959]
Maybe this could solve #4575?
https://github.com/divan/txqr

**Comment by ecdsa** [comment]
Maybe, but the QR code readers we use are not part of Electrum. 
We would need this type of QR code reader to be available for Linux, Windows, Android and OSX.
At this point this is not the case.

**Comment by andronoob** [comment]
Maybe this issue had already became stale, since partial transaction handling had been drastically changed (#5721).
