### ISSUE TITLE
Electrum -3.3.2 - Windows 8.1 - Bluetooth API issue and cannot open wallet

### ISSUE THREAD

**Issue by SuBPaR42** [spesmilo/electrum#4960]
Tried to open a Ledger Wallet that worked fine under 3.2.3 and now receive the following error.

https://i.imgur.com/2rjBZF7.png

> This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above).

**Comment by ecdsa** [comment]
this is probably a change in the Ledger library. @btchip ?

**Comment by SuBPaR42** [comment]
Thanks Thomas - will wait for more info...

**Comment by SomberNight** [comment]
When exactly do you get the error? I've tried in a Windows 7 VM with both a hw.1 and a Nano S; could not reproduce so far.

**Comment by SuBPaR42** [comment]
File -- Open -- Select File -- Next

Then get the error display message.  Only happens with a ledger wallet file (either Nano S or HW.1 wallet).

**Comment by SomberNight** [comment]
Trezor does not work either.

**Comment by SomberNight** [comment]
Ahh, it's most likely because python-trezor (and clones) do the same :(
https://github.com/trezor/python-trezor/blob/a9f39b94a53a51ebc4fd3c7490e07feaddfc6f5e/trezorlib/qt/pinmatrix.py#L34

**Comment by SomberNight** [comment]
I've built a binary without trezor/keepkey/safet, and now ledger at least works.

https://github.com/spesmilo/electrum/issues/4815 also looks related.
Pyinstaller is pulling in all of Qt because of these import statements.

**Comment by SomberNight** [comment]
Opened PR for Trezor. https://github.com/trezor/python-trezor/pull/349
Going to ask KeepKey/SafeT to pull upstream commit after it's merged.

I don't see how to work around this "bluetooth" issue in python land..... Qt is crashing the whole process which is horrible.

**Comment by SuBPaR42** [comment]
I owe you a beer (or 6).  Thanks for your diligence in tracking this down!
