### ISSUE TITLE
Installed 3.3.2, but 3.2.3 remains on system (Linux)

### ISSUE THREAD

**Issue by outhud** [spesmilo/electrum#4963]
Following the Easy Installation instructions on https://electrum.org/#download was always how I updated to the latest electrum with no problems.

But since 3.3.0 (I assume related to the python requirement changes), the old version 3.2.3 remains on my system (Linux Mint 19.1).  If I do "which electrum" I see /usr/local/bin/electrum and this version is 3.2.3.

Running the line for installing 3.3.2 gives:
```
sudo python3 -m pip install https://download.electrum.org/3.3.2/Electrum-3.3.2.tar.gz#egg=electrum[fast]
Requirement already satisfied: electrum[fast] from https://download.electrum.org/3.3.2/Electrum-3.3.2.tar.gz#egg=electrum[fast] in /usr/local/lib/python3.6/dist-packages
```

Where can I find the new electrum, and how can I install it correctly over the 3.2.3 version?

**Comment by SomberNight** [comment]
Uninstall Electrum several times until it can no longer be found:
```
sudo python3 -m pip uninstall electrum
```
Then reinstall Electrum.

**Comment by outhud** [comment]
Worked, thanks!
