### ISSUE TITLE
Project enhancement: Logo design

### ISSUE THREAD

**Issue by debpedrano** [spesmilo/electrum#4964]
Greetings!

I am an aspiring graphics designer and I have some designs for your project, I can show you the design if you wanted to do so.

**Comment by SomberNight** [comment]
Hi. Yes, please, feel free to share sketches/drawings/ideas/ready images/whatever :)

**Comment by debpedrano** [comment]
@SomberNight 

Outer layer for Electrum
B for Bitcoin

![image](https://user-images.githubusercontent.com/40510200/50411205-33662100-0839-11e9-8c24-02b8e2b2ac52.png)

**Comment by SuBPaR42** [comment]
Almost "too" clean :-)

**Comment by bauerj** [comment]
It should be a ₿ instead of a B inside the logo. Otherwise I think it does look nice and clean.

**Comment by SuBPaR42** [comment]
Agreed - the bitcoin logo versus a plain "B" would be better

**Comment by debpedrano** [comment]
I will change it, thank you for your comments :)

**Comment by debpedrano** [comment]
@SuBPaR42  @bauerj 
![image](https://user-images.githubusercontent.com/40510200/50500922-74f00980-0a8f-11e9-8ecb-2c4dee9d9baa.png)

**Comment by SuBPaR42** [comment]
Oh yes - very nice!

**Comment by debpedrano** [comment]
What color and please indicate the sizes

**Comment by debpedrano** [comment]
@SuBPaR42 I better make a PR under a logo file
