### ISSUE TITLE
Stolen Bitcoin with Electrum Upgrade 3.4.1

### ISSUE THREAD

**Issue by upag** [spesmilo/electrum#4975]
I had a version earlier than Electrum 3.4.1

I tried to send a small transaction.

I had a popup that said I must upgrade to the new version of Electrum.  3.4.1. before any transactions could be sent.

I upgraded and within minutes all of my bitcoin were gone.

This is the link that was displayed inside my electrum wallet.  Something I had never seen before, but trusted because it was inside my wallet.  https://github.com/electrum-project/electrum/releases/tag/ 3.4.1 . **(I have added a space to hopefully break the link.  Please do not use this link, to avoid the malware hitting your device.)**

The bitcoin were transferred to this wallet address 3CrC4UitJqNqdkXY5XbJfCaGnbxHkKNqzL

![image](https://user-images.githubusercontent.com/46190352/50523487-678e4b80-0a9e-11e9-8f7a-4ad5bb40df7e.png)

Is there any way to recover these btc that were stolen?

**Comment by shsmith** [comment]
You were tricked into installing a malware version. See https://github.com/spesmilo/electrum/issues/4968 for more discussion on this.

**Comment by Rayserzor** [comment]
There are no 3.4.1 yet. And _/electrum-project/_ is not the official github, but _/spesmilo/_.

https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES

**Comment by SuBPaR42** [comment]
Looks like there coins are resting here for now - https://www.blocktrail.com/BTC/address/1MkM9Q6xo5AHZkLv2sTGLYb3zVreE6wBkj

I hope that balance isn't all a result of the malware :-(

**Comment by marekr** [comment]
>Is there any way to recover these btc that were stolen?

Welcome to the cold hard reality of cryptocurrencies. No.

**Comment by cculianu** [comment]
@SuBPaR42 It looks like it probably is.  $1.5mln as of the time of this writing.  Jesus christ. I hope these guys get caught and do long prison sentences.

**Comment by anynamehere** [comment]
Add another $8k as of Super Bowl time. 
![desktop](https://user-images.githubusercontent.com/47309030/52186553-97c5c880-285a-11e9-8dff-bd9900e68a85.jpg)
