### ISSUE TITLE
P2SH-PWSH address for 2FA wallets

### ISSUE THREAD

**Issue by du2zy** [spesmilo/electrum#4976]
Hello!

Is it possible to create P2SH (not bech32) address in SegWit 2FA wallet?

**Comment by SomberNight** [comment]
No; there are only two types currently.

legacy (p2sh multisig. not segwit)
native segwit (p2wsh witness v0 multisig)

**Comment by chricand** [comment]
Is this feature planned for the future?

**Comment by ecdsa** [comment]
no it is not.
