### ISSUE TITLE
KeepKey WebUSB support

### ISSUE THREAD

**Issue by keepkeyjon** [spesmilo/electrum#4993]
We've started the migration to WebUSB, which will need clients to update in order to remain compatible. What version of python-keepkey does Electrum ship with? (https://github.com/keepkey/python-keepkey/issues/33 makes it hard to tell... we're working on that).

**Comment by SomberNight** [comment]
We use pip to install it from PyPI, so 4.0.2
https://github.com/spesmilo/electrum/blob/2f789468ea6d04e5024d6f1c41c88ab0ba38d06e/contrib/deterministic-build/requirements-hw.txt#L64-L65
There is a [script ](https://github.com/spesmilo/electrum/blob/2f789468ea6d04e5024d6f1c41c88ab0ba38d06e/contrib/freeze_packages.sh)we run manually sometimes to update the above list.

If there is a problem with releasing a new version there, I guess we could install from git+https.
Say so in that case; but it would be more convenient if we could keep using PyPI.

I am trying to keep an eye on our dependencies (follow changes, using newer versions), but I had assumed that the reason you stopped releasing on PyPI is that the changes are not stable.

**Comment by keepkeyjon** [comment]
Publishing it on PyPi wasn't a documented part of our release process, which led to us forgetting it needed to be done. Sorry about that.

I'm working with the PyPi folks to get maintainership of the package so I can publish, but that may take a while... so git+https sounds like the way to go in the short term. For WebUSB, you'll need https://github.com/keepkey/python-keepkey/releases/tag/v6.0.1
