### ISSUE TITLE
keepkey legacy multisig : failed to compile output

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#4998]
3 of 3 legacy multisig wallet with Trezor, Keepkey and Ledger
Trezor and Ledger sign their part, but Keepkey always fails, no matter if its the first, second or third signature. The device seems to successfully sign, but then I get the following:
`  File "/usr/local/lib/python3.7/dist-packages/electrum/plugins/keepkey/clientbase.py", line 220, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keepkeylib/client.py", line 871, in sign_tx
    res = self.call(proto.TxAck(tx=msg))
  File "/usr/local/lib/python3.7/dist-packages/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keepkeylib/client.py", line 192, in call
    resp = self.call(msg)
  File "/usr/local/lib/python3.7/dist-packages/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keepkeylib/client.py", line 189, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.7/dist-packages/electrum/plugins/keepkey/clientbase.py", line 35, in callback_Failure
    raise RuntimeError(msg.message)
RuntimeError: Failed to compile output`

electrum: 3.3.2
trezor: 0.11.1
keepkey: 4.0.2
btchip-python: 0.1.28

**Comment by SomberNight** [comment]
How many outputs are there (and what kind of scripts)?
How many of these are owned by the wallet (e.g. change)?

I've played around with the setup you described and it seems to work here.

**Comment by ulrichard** [comment]
The wallet was created in Sep 2016, so it's a simple multisig of legacy addresses.
The transactions had two outputs, both going to the wallet itself. One public, and one change address.
The keepkey firmware was recently upgraded, so could it be that it is incompatible with the keepkey python lib 4.0.2?

**Comment by SomberNight** [comment]
What is the version of the keepkey fw you have? I have 5.10.2

**Comment by ulrichard** [comment]
I just upgraded the keepkey python lib with pip to version 6.0.2
The keepkey firmware is at version 5.4.1
The behavior is still the same. I get an error "failed to compile output"

**Comment by keepkeyjon** [comment]
@ulrichard I'd recommend trying a firmware newer than v5.8.0. We fixed a lot of utxo-coin signing weirditude in that release, and there have been several security fix releases since. I highly recommend updating to the latest if you can do so safely.

**Comment by ulrichard** [comment]
@keepkeyjon How do I flash those newer versions?
I upgraded the device twice in a row today with the Cromium KeepKey Client App, but it still reports 5.4.1.

**Comment by keepkeyjon** [comment]
What version is the chrome app? That firmware is pretty old.

Alternatively, you can use python-keepkey. Hold the button down while plugging the device in, then do:

```
keepkeyctl firmware_update -f firmware.keepkey.bin
```

**Comment by ulrichard** [comment]
Ok, I had to update the bootloader as well, but now it is working again.
Thanks for the support.
I didn't see a version at the chrome app, or a way to update it. I always assumed it would use the most up to date version automatically.

**Comment by keepkeyjon** [comment]
It *should* update automatically. That it doesn't is odd. *shrug*
The version is on the settings page (click the gear icon on the top left).
