### ISSUE TITLE
to cancel a transaction

### ISSUE THREAD

**Issue by esp102** [spesmilo/electrum#4999]
Good night, I download electrum in my computer and I try to transfer money to adnother wallet (blockchain) The thing is when I sent I never receive the money in my blockchain wallet: I wrote blockchain and they told electrum changed my wallet adress trough a Hacker and I sent the money to another person. Anybody have the same problem? There is a way to put a complain?

**Comment by ecdsa** [comment]
bitcoin transactions are irreversible and cannot be cancelled.
electrum did not change your destination address; the usual attack scenario is where malware modifies bitcoin addresses in the clipboard, so that you paste a different address

**Comment by SomberNight** [comment]
You have not described the problem adequately. The details here are insufficient to help.

-------- Original Message --------

**Comment by esp102** [comment]
ok. Find attached the file I downloaded.

**Comment by esp102** [comment]
I cant add any file in this forum. Tell how can I send to you

**Comment by SomberNight** [comment]
What are you trying to upload? You can add it here if you zip it first.

**Comment by esp102** [comment]
[signed_cd55141b.zip](https://github.com/spesmilo/electrum/files/2776970/signed_cd55141b.zip)
[electrum323setup.zip](https://github.com/spesmilo/electrum/files/2776971/electrum323setup.zip)
