### ISSUE TITLE
Beware of the windows application

### ISSUE THREAD

**Issue by webzrout** [spesmilo/electrum#5001]
Do not seriously think this is a normal application ! It does not even give me so many problems when it's so many viruses.

![screenshot 26](https://user-images.githubusercontent.com/36602530/51005075-acee5680-153d-11e9-8d44-ac9da2c6ae85.jpg)

report malware: [https://www.virustotal.com/#/file/22489e88966a9939cf34a94878f7ddf1dad140cce28ebe5339af6212afa611be/detection](url)

**Comment by ysangkok** [comment]
Does it classify all Pyinstaller applications like this?

**Comment by ecdsa** [comment]
Please stop the FUD; antivirus software has false positives, and will always have. OTOH, we need people to upgrade to the latest version, given the recent phishing attack. Posts such as yours only slow down the upgrade process.
