### ISSUE TITLE
Startup error with Electrum 3.3.2 on Tails 3.11

### ISSUE THREAD

**Issue by JazzTp** [spesmilo/electrum#5008]
Electrum 3.3.2 on Tails 3.11, startup error:

```
  File "./run_electrum", line 53
    sys.exit(f"Error: {str(e)}. Try 'sudo python3 -m pip install <module-name>'")
                                                                               ^
SyntaxError: invalid syntax
```

On the other hand, the _older_ Electrum version 3.2.3 starts OK on Tails 3.11, it only issues this warning (and the QRcode scanner works, BTW):
```
[ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
```

**Comment by AbdussamadA** [comment]
IT's because the version of python on tails is too old. Use 3.2.4 instead.

**Comment by SomberNight** [comment]
As above, Electrum 3.3.x requires Python 3.6, and Tails atm comes with Python 3.5.

https://github.com/spesmilo/electrum/issues/4343 might help, otherwise we need Debian/Tails to ship newer python
