### ISSUE TITLE
Electrum - restore with latest version nothing inside

### ISSUE THREAD

**Issue by JJss11** [spesmilo/electrum#5009]

**Comment by JJss11** [comment]
Can somebody help me,

I took new laptop, 

I restore my wallet with seeds, with latest version.

But there are nothing inside, not transaction no BTC.

I tried to install older version also nothing inside.

I don't know what should I do.

On old one was working everything perfectly and now it looks like new wallet.


That is everything what I have

**Comment by JJss11** [comment]
I don't have anymore the old.

I had written seeds, and I checked before.

I already did that with the same seeds. But this time is different completely.

But on old lap it was working completely normal.

Now there is no transaction no coins, nothing.

Like new wallet

**Comment by JJss11** [comment]
Okay, I cannot open seed with this.

What is that, I cannot even click on that options?

**Comment by SomberNight** [comment]
What version of Electrum? What is the colour of the orb/circle in the bottom right corner?

> Okay, I cannot open seed with this.

How did you restore the wallet?

**Comment by SomberNight** [comment]
> It was generated by Electrum,
> But I couldn't go inside if I don't press option that its BIP39.

Electrum seeds are not BIP39 -- these are different standards.
If you enable the BIP39 option, it will treat the words as BIP39 seed, and the derived keys and addresses will be different. Of course you won't see your history in this case.

You should figure out the reason you cannot click next (without enabling BIP39). The immediate cause is that the words you entered do not form a valid Electrum seed. This can be because of typos, swapping words, or replacing words with similar words.

**Comment by JJss11** [comment]
Okay that is possible, but I already restore with same seed.

Can you tell me what is typos?

**Comment by JJss11** [comment]
Okay I tried with first 12 word, its possible next, but there is nothing inside, like old.

And whenI put extended that I have its not possible to press next.

**Comment by SomberNight** [comment]
> Can you tell me what is typos?

A "typo" is a misspelling. Replacing letters by mistake.

> Okay I tried with first 12 word

How many words do you have?

**Comment by AbdussamadA** [comment]
>And whenI put extended that I have its not possible to press next.

Seed extension isn't entered in the same box as the seed. Also you said above that you didn't use a seed extension so what are you doing?

**Comment by ecdsa** [comment]
so apparently this user has a seed extension and is not able to find where to type it?

**Comment by AbdussamadA** [comment]
To begin the wallet restoration process again go to file > new/restore, enter a unique filename, click next and follow on-screen instructions for the rest.

To enter the seed extension click on options in the seed entry step and check "extend this seed with custom words". Then in the next step you will get the option to add the seed extension.
