### ISSUE TITLE
Typo? "The transaction was rejected because it contains more than 1 OP_RETURN input."

### ISSUE THREAD

**Issue by andronoob** [spesmilo/electrum#5014]
https://github.com/spesmilo/electrum/blob/c995d5364e47fc14b4d43dbfb940168be2eeabc9/electrum/network.py#L791

**Comment by andronoob** [comment]
@SomberNight 
Another typo? Or I just misunderstood something?
https://github.com/spesmilo/electrum/blob/9cff42328d5b6c92c87a2b41bb1f4e463c39aab7/electrum/gui/qt/main_window.py#L2962

**Comment by SomberNight** [comment]
once you start spending them they become inputs
I think it's more intuitive to call them inputs there

**Comment by andronoob** [comment]
Whether "inputs" or "outputs" is inevitably confusing to newbies, since UTXO itself is unintuitive after all... Maybe "inputs" is more confusing, because:
https://github.com/spesmilo/electrum/blob/master/electrum/gui/qt/main_window.py#L2970
