### ISSUE TITLE
Send payment via console with description

### ISSUE THREAD

**Issue by AidasK** [spesmilo/electrum#5019]
I know I can send payments with description via gui, but I can't find a way to do it with console

```
electrum payto 1JuiT4dM65d8vBt8qUYamnDmAMJ4MjjxRA 0.1 | electrum broadcast -
```

Any help?

**Comment by ecdsa** [comment]
`electrum setlabel <txid>`

**Comment by AidasK** [comment]
I did:
```
electrum payto 1JuiT4dM65d8vBt8qUYamnDmAMJ4MjjxRA 0.1 | electrum broadcast -
electrum history
... copy txid ...
electrum setlabel TXID "my message"
```

I can only see this label locally, but on the receiving wallet history label is empty. Maybe I have to broadcast it somehow? Or I had to do it before a broadcast? Thanks

**Comment by AidasK** [comment]
🤯 Thank you!
