### ISSUE TITLE
+0. amount received instead of real transfer

### ISSUE THREAD

**Issue by vigen80** [spesmilo/electrum#5022]
Hello. I am using Electrum for a long time and now there's a problem with one of my incoming payments. Amount field shows +0. instead of real amount. Balance field has not changed since last operation as well. Transfer sent a few days ago. Transaction ID shows that everything went well but I haven't received my transfer. What could go wrong? How am I supposed to get that money sent to me? Thanks.

**Comment by SomberNight** [comment]
please update electrum, you must be using an old version.

**Comment by vigen80** [comment]
Thanks, it helped! Pity that portable version does not remind to update. Thanks again for a quick respond!

**Comment by toeplitz75** [comment]
Ke ne veux plurecevoir de mail silvouplait
