### ISSUE TITLE
Android build fails since 2019-01-19: build-tools and SDKs missing

### ISSUE THREAD

**Issue by homberger** [spesmilo/electrum#5025]
Android build is failing since 2019-01-19.

Last passed build: [Job #7801.4](https://travis-ci.org/spesmilo/electrum/jobs/481502343)
First failed build: [Job #7803.4](https://travis-ci.org/spesmilo/electrum/jobs/481710963)

**Please compare following output.**
Passed build with installed build-tools and installed SDKs:
https://travis-ci.org/spesmilo/electrum/jobs/481502343#L3004-L3054

Failed build with missing build-tools and missing SDKs:
https://travis-ci.org/spesmilo/electrum/jobs/481710963#L3002-L3034

I am able to reproduce this problem by following the [instructions](https://github.com/spesmilo/electrum#development-version) to create android binaries.

**Comment by SomberNight** [comment]
Looks like it started working again >.<
https://travis-ci.org/spesmilo/electrum/jobs/483466546

Any chance you have [more detailed logs](https://github.com/spesmilo/electrum/blob/920d4c2b27190f5ad8f808cbe288855dbd171fa5/electrum/gui/kivy/tools/buildozer.spec#L151) from when it was failing?

**Comment by homberger** [comment]
Yes. I was using log_level set to 2. Detailed logs are attached. 
Generated from when the android build was failing. 

[apk_build_failed_detailed_logs.log](https://github.com/spesmilo/electrum/files/2789577/apk_build_failed_detailed_logs.log)

**Comment by homberger** [comment]
> Looks like it started working again >.<

I'll try it again and report the result.

**Comment by SomberNight** [comment]
There have been no issues with the Android build for some time now I believe. Closing this.
