### ISSUE TITLE
Electrum fails to decrypt passphrase from Trezor T

### ISSUE THREAD

**Issue by stormott** [spesmilo/electrum#5029]

**Comment by SomberNight** [comment]
Please be more specific and less terse.

**Comment by stormott** [comment]
Passphrase checked zillion times. Electrum can open account in Trezor T that has no passphrase attached though.

**Comment by stormott** [comment]
It just says it fails to decrypt passphrase

**Comment by stormott** [comment]
..hello ghost43.
well Electrum just fails to decrypt passphrase, I have checked passphrase
many many times...!
The account on Trezor with no passphrase attached can be opened in Electrum
but obviously  the account with passphrase is the most important !
I have uninstalled and reinstalled version 3.3.2 already
ok let me know if you need other infos
thank you
luciano

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno gio 24 gen 2019 alle ore 16:03 ghost43 <notifications@github.com>
ha scritto:

**Comment by bauerj** [comment]
Please give more information.

When do you see this message?

What version of Electrum do you use?

What Operating System do you use?

How long have you been using this wallet?

**Comment by SomberNight** [comment]
Could you maybe attach a screenshot of the error message?

**Comment by stormott** [comment]
I have just posted  on github .
thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno gio 24 gen 2019 alle ore 16:20 ghost43 <notifications@github.com>
ha scritto:

**Comment by SomberNight** [comment]
Thanks for the picture.
You have a wallet file that is connected to your trezor device, for a specific derivation path (specific account) and for a specific passphrase. This wallet file is encrypted, with the same passphrase and the trezor device itself. To decrypt and open the wallet file, you need to enter the >>same<< passphrase you used when creating the wallet file in the first place.

To handle another account or passphrase with the trezor, you need to create >>another<< wallet file. Which can again be encrypted, using >>that<< passphrase and the device itself.

If you are confused, your best bet is to create a new wallet file using electrum (and then electrum will find your transaction history again).

**Comment by stormott** [comment]
I kind of understand and I will try .....please do not close tis post yet, I will get back to you ...
thank you

**Comment by stormott** [comment]
transaction is well confirmed. sorry to bother you so much but I really need to understand

**Comment by SomberNight** [comment]
Compare addresses in Electrum>`Addresses` tab with addresses in trezor web wallet (or whatever you expect).

derivation path, script type, and passphrase, all need to be the same -- these are configured during wallet creation/restore in electrum

**Comment by stormott** [comment]
ok I try

**Comment by stormott** [comment]
<img width="936" alt="addresses" src="https://user-images.githubusercontent.com/45269097/51691174-9266b380-1ffa-11e9-8857-aff021ee3e8c.PNG">
<img width="936" alt="receive" src="https://user-images.githubusercontent.com/45269097/51691175-9266b380-1ffa-11e9-932f-d16056480721.PNG">
well the address matches  ( first on top ) the receivin one .
perhaps I should know that I sent direct from Bc1 address format to Trezor which then now displays it as a reguar 3 Segwit address.....

**Comment by SomberNight** [comment]
try setting script type to `p2sh-segwit` when restoring:
![bip39_script_type_p2shsegwit](https://user-images.githubusercontent.com/29142493/51691709-97783280-1ffb-11e9-8489-5d875cfae59e.PNG)

**Comment by stormott** [comment]
when creating Electrum wallet , when asked for derivation path I left it  unchanged as suggested  since I did not know

**Comment by stormott** [comment]
ok so it means I will cancel and restore a newone.... I can feel I am getting close to the solution  and I appreciate very much your work and patience.... i will get back to you shortly...

**Comment by stormott** [comment]
YEAH It appeared!!!!!
before you leave Can you confirm that I will be able to manage UXTO singularly by using Trezor with Electrum?
how can I mantain Bc1 Format address instead of having it converted in £ Segwet format?

**Comment by stormott** [comment]
sorry it was 3 Segwit  format

**Comment by SomberNight** [comment]
If you want "bc1..." addresses, choose `native segwit` for script type when creating the wallet.
You will then need to send your existing coins from "3.." addresses to there.

>  you confirm that I will be able to manage UXTO singularly by using Trezor with Electrum?

You can choose which coins to spend ("coin control") when creating transactions in Electrum, if that's what you mean, yes.

**Comment by stormott** [comment]
very well . thank you very much .
Don t know which part of the world you live in ....if you pass through italy give me a shout You well deserve a nice plate of pasta.
ciao
