### ISSUE TITLE
Release process for GNU/Linux binaries not documented

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5030]
The release process for GNU/Linux binaries isn't clearly documented.  It would be highly useful to clearly document what terminal commands to run, starting with `git clone` and ending with the `.tar.gz` file that is uploaded to the website.

**Comment by bauerj** [comment]
You can check out https://github.com/spesmilo/electrum/blob/master/contrib/make_tgz, the process is fairly simple.
