### ISSUE TITLE
Wallet > Information > Seed available: False

### ISSUE THREAD

**Issue by Cerylion** [spesmilo/electrum#5035]
Hi, I'm really troubled here. 
My pc broke down a while ago and I restored my wallet with the seed. 
No problem here.
Now the tablet where I had the authenticator codes died.
And now I notice that I can't restore from seed anymore, because in the Wallet Information it says that the seed is FALSE...

I tried restoring with my original seed, and can't seem to do it...
please, help, I'm stuck.
![seed equals false](https://user-images.githubusercontent.com/8084032/51794141-fcfe2780-2191-11e9-9fe6-4e0b8ed5374d.png)

**Comment by SomberNight** [comment]
"Seed available: False" just means that the seed is not stored in the wallet file. If you have written down the seed on paper as instructed, you still have it and can restore from it any time.

The seed is not stored in the wallet file for 2FA wallets as then they would not be 2FA: the seed is a single thing that you can restore from (nothing else is needed).

> Now the tablet where I had the authenticator codes died.

Restore from seed, and choose to `keep` 2FA enabled, and check `I have lost my Google Authenticator account` 

![step1](https://user-images.githubusercontent.com/29142493/51794179-7c5d1c80-21cd-11e9-9750-edf3e97aa3ca.png)
![step2](https://user-images.githubusercontent.com/29142493/51794180-7f580d00-21cd-11e9-83d7-f70f21272ce5.png)

**Comment by Cerylion** [comment]
Thanks! I was using the wrong option to restore!!!
Problem Solved XD
