### ISSUE TITLE
Allow sub satoshi per byte tx fee

### ISSUE THREAD

**Issue by shivaenigma** [spesmilo/electrum#5043]
Hi,
This would be very useful in the current scenario to consolidate dust inputs. User can be given a Warning, but should still be allowed to broadcast the transaction at his own risk (he can use RBF)

Mempool is literally empty during weekend, wouldn't be surprised if some of these tx go through

**Comment by SomberNight** [comment]
The default minimum relay fee of bitcoin nodes is 1 satoshi per virtual byte.

In the current client code, the server is asked for its min relay fee, and then the client checks before broadcasting a transaction whether that transaction conforms to the given min relay fee:
https://github.com/spesmilo/electrum/blob/0f0cee422e1b9def25f0b8e3d21022b1cc7f2770/electrum/gui/qt/main_window.py#L1608

That is AFAICT the only check regarding minimum fee. You can try commenting it out.

However, the point is that even if you comment it out, the server('s bitcoin node) will then complain that the min relay fee is not met, and will not relay the transaction.

**Comment by shivaenigma** [comment]
Thanks. Makes sense. I will try connecting to my node with a lower relayfee. Feel free to close
