### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by 221V** [spesmilo/electrum#5050]
$ sudo python3 -m pip install https://download.electrum.org/3.3.3/Electrum-3.3.3.tar.gz#egg=electrum[fast]
  Downloading https://download.electrum.org/3.3.3/Electrum-3.3.3.tar.gz (9.2MB)
    100% |████████████████████████████████| 9.2MB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    Error: Electrum requires Python version >= 3.6.1...
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5dhrsegj/electrum/
$ python3.6 -V
Python 3.6.6

what to do?

**Comment by 221V** [comment]
why you not creating .deb for ubuntu/debian ??
why users must crying while install ?((

**Comment by 221V** [comment]
solved
create .deb for more friendly install please

**Comment by SomberNight** [comment]
next version will most likely be also distributed as an appimage (see https://github.com/spesmilo/electrum/pull/5042)
