### ISSUE TITLE
Server returned an unexpected transaction ID when broadcasting

### ISSUE THREAD

**Issue by wpr101** [spesmilo/electrum#5058]
I have the latest 3.3.3 version of Electrum, and get this error when trying to send a transaction. Multiple receiving addresses have been tried but get the same error. I have the GUI set to select the server automatically.

Exact text is:

"The server returned an unexpected transaction ID when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

Server returned unexpected transaction ID."

![electrumerror](https://user-images.githubusercontent.com/16501438/52165242-12141280-26cc-11e9-9280-b913469b6814.png)

**Comment by chris-belcher** [comment]
Looks like there's an ongoing phishing attack from malicious sybil Electrum servers. You're updated to the latest version of Electrum wallet so you're safe.

Try connecting to a few different servers, if you connect to a non-sybil honest server then your transaction should broadcast fine. Another option is to use Electrum's GUI to obtain the transaction hex string and then copypaste it into a web transaction broadcasting tool [such as this one](https://live.blockcypher.com/btc/pushtx/)

**Comment by AbdussamadA** [comment]
To switch servers go to tools > network > server tab > uncheck select server automatically > right click on a different server from the list and choose use server. Try sending your coins again.

**Comment by shsmith** [comment]
You can see a list of some known electrum servers here: https://1209k.com/bitcoin-eye/ele.php
Pick one with the Uptime Month value > 0.75 and it is most likely legit.

**Comment by Cryptolista** [comment]
I did an update and my bitcoins were transferred without my authorization, I'm desperate, help me!

**Comment by Cryptolista** [comment]
> You can see a list of some known electrum servers here: https://1209k.com/bitcoin-eye/ele.php
> Pick one with the Uptime Month value > 0.75 and it is most likely legit.

I did an update and my bitcoins were transferred without my authorization, I'm desperate, help me!

**Comment by wpr101** [comment]
How is the default behavior of the software that it's connecting to the malicious servers? Isn't there some way that the automatic connect could remove these from the list?

**Comment by Cryptolista** [comment]
Here pops up the message that this synchronizing for over 2 hours

**Comment by AbdussamadA** [comment]
>How can I know which is a legitimate server to connect to?

If you're in a hurry try the bauerj or hsmith servers. If you're not then any server that doesn't give you spurious error messages is fine. 

>Here pops up the message that this synchronizing for over 2 hours

Your situation is different and you should stick to your own issue about it. OP hasn't lost anything because he didn't download malware like you did.

**Comment by Cryptolista** [comment]
I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  1FcvMGQN9c5aE1o3WQnFqhUN9ShQssNoYd
