### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by sjaved2** [spesmilo/electrum#5062]
Hi,

I recently attempted to upgrade Electrum wallet on Linux Tails OS to version 3.3.3 however it did not work so I therefore downloaded your windows version 3.3.4 from your website at Electrum.org. I then made a transaction from my Nano Ledger to my Electrum wallet via windows as per the Blockchain track as shown in the link below:

https://www.blockchain.com/btc/tx/6a35836ca2e24eee9edada390d3c5efac0181db0e3d6f89479dcdba65d586b03

This shows the successful transfer of BTC from my Ledger to Electrum. I have then attempted to transfer to another BTC address but according to the Windows Wallet, No BTC has been transferred out however the Linux wallet shows that BTC has been paid out to 
the amount of $602.8011 to BTC address 3H14ieqxUh2WXhaiHSMuagbvBfxXcGrVHb         however is not the BTC address I actually sent it too and feel that my account may have been compromised. The track for this transaction can be seen at:

https://www.blockchain.com/btc/address/3H14ieqxUh2WXhaiHSMuagbvBfxXcGrVHb

Ultimately the Linux wallet shows funds paid out however the Windows wallet shows funds are still available. I would appreciate it if you could look into this matter as soon as possible and confirm whether or not I still have the funds in my wallet or not?

Thanks

**Comment by sjaved2** [comment]
Meant to say version 3.3.3 sorry. Typo on my part. I downloaded the windows version off the official electrum.org site.

**Comment by bitdaric** [comment]
can you upload your version to check it?

**Comment by SomberNight** [comment]
> the amount of $602.8011 to BTC address 3H14ieqxUh2WXhaiHSMuagbvBfxXcGrVHb however is not the BTC address I actually sent it too and feel that my account may have been compromised. The track for this transaction can be seen at:

That transaction 6a35836ca2e24eee9edada390d3c5efac0181db0e3d6f89479dcdba65d586b03 looks to have a significant amount of change, so it was unlikely to be malware stealing it.
Please don't use fiat values as they are irrelevant and also somewhat confusing, but I take it the output to 141gDPWZxrzggwkXriLVzztUUU3Xww33oZ is what you intended to pay. The other one is probably change back to you. In terms of inconsistency between the Windows and Linux versions, `View`>`Show Addresses`; pleases confirm you see the same addresses.

**Comment by trecurry** [comment]
what there is no version 3.3.4 it told me to upgrade the other day and i am having issues too

No transaction found with the hash c88a9f1686e3e790bfd01cda4b0657b8c4341fd54bd70f6e5333312fc53c8176

**Comment by trecurry** [comment]
there is a electrum 3.3.4 i just looked at website

**Comment by SomberNight** [comment]
> what there is no version 3.3.4

Well, there is now. There was not at that point.

**Comment by SomberNight** [comment]
> and i am having issues too
> No transaction found with the hash c88a9f1686e3e790bfd01cda4b0657b8c4341fd54bd70f6e5333312fc53c8176

What exactly is your issue?

**Comment by trecurry** [comment]
ok i transfered funds 24hours ago from electrum wallet to another wallet on paxful.com it took a while but it went, during the time i was waiting for it to clear on paxful.com i sent 2 other transfers to other wallets....those still havent made it to the wallets and when i check the hash it says it doesnt exist? but the electrum wallet shows it completed

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
