### ISSUE TITLE
plesae help restore my stolen fund due to electrum wallet which i didnt open for months

### ISSUE THREAD

**Issue by wtoung** [spesmilo/electrum#5063]
please help restore my stolen fund due to electrum wallet which i didn't open for months.
shocking to see my small lost from a PC, which i didn't touch for months.

or is that electrum itself steal our funding !! sorry, i may not know culture of dev team, but want to trust electrum developers are smart, good and honest people.

https://www.blockchain.com/btc/tx/bb08b3ed52955da3c98562638e5d1486328995e029f8b33ce35320deeddcd0b3

any clue restoring? Thanks.

**Comment by bitdaric** [comment]
there are no restore. are you sure you are downloaded official wallet from electrum.org ?

**Comment by SomberNight** [comment]
How did you notice the transaction if you haven't opened the wallet?
How did you generate the seed words originally? How did you store them?

**Comment by andronoob** [comment]
Did you installed a fake "upgrade" from a pop-up message? Old versions of Electrum have a serious bug, which allows a malicious server to do evil phishing stuff.
Electrum servers are not managed by the devs, anyone may set up his/her own server to server people.
Sadly if the coins were already transferred out, there's no way to recover. This is Bitcoin.

**Comment by ecdsa** [comment]
this is probably not related to the recent phishing attack; funds were moved on 29.10.2018.

**Comment by bitdaric** [comment]
> 
> 
> Electrum 3.3.3 show me a message to update, go to update 3.3.4 and lose all money ~12 BTC ~ $42k
> 
> PROBLEM IS THE SCAM UPDATE SHOW ME ON 3.3.3 OFFICIAL !!!!
> 
> what the fuck going on with electrum ? i feel like crazy now, my wife, my son going to dead because electrum ??? WTFFFFFCKCKKCKCKK
> 
> https://imgur.com/a/vtFSx6G

can you upload your electrum installation file for analyses?

**Comment by birdie-github** [comment]
The developers of this app cannot help you, and there's no support - it's an open source, non-profit application. Most likely your money is permanently gone.

If you still have enough money you could hire an investigator though I highly doubt he'll ever be able to find the attacker and recover your funds.

**Comment by vvivigle** [comment]
@birdie-github 

You can to track the flow of funds to any wallet or a bunch of profile's wallets and receive notifications by email or SMS.
https://vivigle.com/

**Comment by ecdsa** [comment]
comments on this thread that are related to the recent phising attack are offtopic; this user's case is different.

@wtoung Electrum is not in a position to steal your funds. your funds were stolen long ago, even if you noticed it recently. it is likely that someone has gained access to your seed words, or to your computer.
