### ISSUE TITLE
adress lost to restore electrum seed

### ISSUE THREAD

**Issue by jotawar** [spesmilo/electrum#5065]
format the pc but I have the seed on paper, when I restore the seed in electrum I do not see the address where I have the BTC, the address is 16H6zEijD9hBLtz4fJyswmfbvnQCCofS9R but when restoring with my seed does not appear, another wallet appears with balance 0, what can I do ? I do not know what to do

**Comment by SomberNight** [comment]
- How did you generate the seed originally? (Was it generated by Electrum?)
- What version of Electrum are you using now?
- What is the colour of the orb/circle in the bottom right corner?
- By "another wallet appears with balance 0", do you mean there is no history found, or that it's a different history than what you would expect?

**Comment by jotawar** [comment]
hi

the seed generated by electrum , now using new version 3.3 but i try with other versions with no sucess , the circle is green , appear balance 0 , no history , no appear my btc adress, is like a new wallet

thanks

**Comment by SomberNight** [comment]
Have you ever tried restoring from this seed before? Are you sure that address belongs to this particular seed?

**Comment by SomberNight** [comment]
Do you have a "seed extension" / "custom words" / "passphrase"?

**Comment by jotawar** [comment]
i have a 12 words seed , always i put the words in electrum and no problem , but when format the pc install new version and not appear

thanks

**Comment by SomberNight** [comment]
So you have successfully restored from seed words before? In the past, I mean.

Where did you download Electrum from this time? Do you have the link in your browser history?
