### ISSUE TITLE
BTC stolen, phishing again.

### ISSUE THREAD

**Issue by ivanbalagan** [spesmilo/electrum#5070]

**Comment by ysangkok** [comment]
Sorry. We believe we have fixed the problem by disallowing arbitrary messages. Please let us know if you think there are additional problems remaining.

**Comment by ysangkok** [comment]
Do you know which malicious domain you downloaded the malicious software from?

**Comment by ivanbalagan** [comment]
All my BTC (4.5+) was stolen from Electrum wallet.
I was surprised, that the issue took place more than a month ago, as I was using the wallet along the whole January.
The transaction of stolen money is here https://blockstream.info/tx/c2c5300eb137f042b28e268158bf0f5ba97de321ceb9405d7b50eedaf6fe02ae

The scenario is absolutely the same as I've found right after the the fraud, I've installed the update by the link from the message given by Electrum wallet application. The fact the link was given in some weird way didn't get enough attention, I was in rush and it actually looked quite suitable for the Electrum ascetic interface.

I insist for Electrum Team has stopped all the activity of the wallet asap, as any other user can lose his money.
Also I require for Electrum Team to give an official report on the problem and explained its next steps i regards to help and get users' money back

**Comment by ivanbalagan** [comment]
> Do you know which malicious domain you downloaded the malicious software from?

Hi

I think no, I don't know 
Though I can try to find the address I was sending BTC to.

Or how can I find the domain?

**Comment by ysangkok** [comment]
> I insist for Electrum Team has stopped all the activity of the wallet asap, as any other user can lose his money.

Since the Electrum servers are not run by the development team, we do not control them. Since we have patched the issue in the latest version of Electrum and done various other things to mitigate the attack, it would be pointless to just give up and ask everybody to shut down their servers.
 
> Or how can I find the domain?

You can look in your web browser history, since you most likely clicked a link in the error message, which would have opened up your web browser.

> get users' money back

The Electrum development team doesn't have the power to do this.

**Comment by ivanbalagan** [comment]
> > I insist for Electrum Team has stopped all the activity of the wallet asap, as any other user can lose his money.
> 
> Since the Electrum servers are not run by the development team, we do not control them. Since we have patched the issue in the latest version of Electrum and done various other things to mitigate the attack, it would be pointless to just give up and ask everybody to shut down their servers.
> Ok, then how the user should be warned about the updates if everything works fine and you don't even try to have the idea to visit the website or social media page?
> > Or how can I find the domain?
> 
> You can look in your web browser history, since you most likely clicked a link in the error message, which would have opened up your web browser.
> Guess browser history can't give me the domain except of this https://github.com/electrum-official/EIectrum/releases/tag/3.3.4 which I copied from the wallet message window
> > get users' money back
> 
> The Electrum development team doesn't have the power to do this.
> Am I right to understand that you're a part of Electrum team?

**Comment by ysangkok** [comment]
> Ok, then how the user should be warned about the updates if everything works fine and you don't even try to have the idea to visit the website or social media page?

We have updated the website, there is a warning on electrum.org saying "Warning: Versions of Electrum older than 3.3.3 are vulnerable to a phishing attack, where malicious servers are able to display a message asking users to download a fake version of Electrum. Do not download software updates from another source than electrum.org. In order to reach users of vulnerable versions, we have started to use the same vulnerability, and to direct them to electrum.org."

> Am I right to understand that you're a part of Electrum team?

Until the end of this month, yes.

**Comment by ysangkok** [comment]
If we asked people to shut down their Electrum servers, the scammers would just be the only ones running servers, which would mean that even more people would lose their money.

> I insist for Electrum Team has stopped all the activity of the wallet asap

What would be the point of this? If we stop development on the client, it would just give the scammers the opportunity of claiming they are the legitimate continuation of Electrum.

**Comment by ivanbalagan** [comment]
> If we asked people to shut down their Electrum servers, the scammers would just be the only ones running servers, which would mean that even more people would lose their money.
> 
> > I insist for Electrum Team has stopped all the activity of the wallet asap
> 
> What would be the point of this? If we stop development on the client, it would just give the scammers the opportunity of claiming they are the legitimate continuation of Electrum.

I don't know, just block all the wallets prpbably

If you say "The Electrum development team doesn't have the power to do this." how can I contact to a management or executive team?

**Comment by ecdsa** [comment]
@ivanbalagan Electrum is not a bank, it is a decentralized network, just like Bitcoin is. Developers do not have the power to shut it down. All we can do is try to minimize user exposure to malicious servers (by upgrading server software), and send vulnerable users the message that they need to upgrade their software.
