### ISSUE TITLE
new popup from hard-coded server , electrumdownload.org

### ISSUE THREAD

**Issue by dev8907** [spesmilo/electrum#5075]
new popup from hard-coded server
![capture](https://user-images.githubusercontent.com/47383475/52334558-e492d600-29f7-11e9-9b33-b3c5736c9d81.PNG)
![capture1](https://user-images.githubusercontent.com/47383475/52334566-e65c9980-29f7-11e9-8883-556a192f729c.PNG)

**Comment by ecdsa** [comment]
the popup is phishing
that server has been removed from the hardcoded list, and is being blacklisted.
please upgrade your client to the latest version
