### ISSUE TITLE
Trezor: PIN cannot be turned on/off with electrum

### ISSUE THREAD

**Issue by andronoob** [spesmilo/electrum#5078]
Electrum 3.3.3 on Windows 10 x64
When PIN is enabled, it cannot be turned of with Electrum. Clicking on "Disable PIN" button will only lead to a pop-up warning window of "'bool' object has no attribute 'call'".
When PIN is disabled, there's no "Enable PIN" button on Electrum's Trezor control panel at all.

**Comment by SomberNight** [comment]
> When PIN is disabled, there's no "Enable PIN" button on Electrum's Trezor control panel at all

True, but there is a `Change PIN` button in `Settings`.
