### ISSUE TITLE
Electrum Wallet Update lost all Bitcoin

### ISSUE THREAD

**Issue by Ladyluck4u** [spesmilo/electrum#5081]
I was told I could not send my payment until I installed new update 4.0 Electrum. I went to https://electrum.org installed update and while I was doing update after update all my bitcoin was gone. In my history it shows transaction of every bit of my bitcoin not just the amount of payment I was trying to make. 

Please advise

**Comment by anduck** [comment]
Sorry. You installed a malicious client. You've been phished by a malicious Electrum server. For more information, check e.g. #5072

**Comment by SomberNight** [comment]
Note that there is no version 4.0 on [https://electrum.org](https://electrum.org).

**Comment by Ladyluck4u** [comment]
So I have lost all my bitcoin??

**Comment by ecdsa** [comment]
yes, your coins have been stolen. 
could you let us know from which website you installed the malware?

**Comment by Ladyluck4u** [comment]
https://www.electrumdownload.org/#home

**Comment by Ladyluck4u** [comment]
This just makes me so frustrated!! I sure hope my experience saves someone else from this. I will tell you though that the message looked like it came from my Electrum wallet when I went to make a payment.

**Comment by ecdsa** [comment]
sorry for your loss. 
we are aware of the attack, see the warning on electrum.org and #4968

**Comment by Ladyluck4u** [comment]
Okay so I am just a beginner to buying bitcoin to pay invoices from other sites. I have uninstalled all I could fine and reinstalled Electrum wallet. Now that I have been phished is my wallet now an open target??? Should I find another wallet to use?? I really liked this wallet.

**Comment by anduck** [comment]
I would suggest you to reinstall the whole system, as the malware you downloaded and ran may have installed any kind of bad things on your operating system etc.

**Comment by ecdsa** [comment]
yes, it is safer to reinstall the whole system
In addition, you should not reuse the same wallet seed, any funds you sent to that wallet will be stolen. 
you can create a new wallet with Electrum, with a new seed.

**Comment by Ladyluck4u** [comment]
Thank you very much!!! Any advice on how to make sure all malware has been uninstalled???

**Comment by Ladyluck4u** [comment]
I understand now. Thank you gentlemen for the good advice and guidance
. :-)
