### ISSUE TITLE
Backport phishing countermeasures to 3.2.x branch

### ISSUE THREAD

**Issue by ValdikSS** [spesmilo/electrum#5089]
Fedora 29 and Rawhide Linux distribution ships Electrum 3.2.4 in the repositories. This version shows plain text phishing error messages from malicious servers.
Is it planned to backport all phishing countermeasures (fresh server list, blacklist, predefined error messages) included in 3.3.x branch to 3.2.x branch?
See: https://bugzilla.redhat.com/show_bug.cgi?id=1672145

**Comment by schildbach** [comment]
Same with Ubuntu, if you want to satisfy Electrum's dependencies from the repository.
