### ISSUE TITLE
electrum-3.3.3.exe deletes itself

### ISSUE THREAD

**Issue by LukAss741** [spesmilo/electrum#5094]
After I run electrum-3.3.3.exe then it plays asterisk sound and deletes itself.
I reinstalled it and removed c:\Users\username\AppData\Roaming\Electrum but it keeps occurring.

It started happening after installation of electrum-ltc-3.3.3.1-setup.exe but even after I uninstalled electrum-ltc I can't run electrum 3.3.3.
I can run electrum-3.3.2.exe however.

Can anyone else reproduce the same issue?
Why does electrum possibly removes its executable?

**Comment by SomberNight** [comment]
Probably related to: https://github.com/spesmilo/electrum/issues/3198 and https://github.com/spesmilo/electrum/issues/4986

Windows Defender quarantines the exe.

Please report this to Microsoft. Maybe(?) here https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by LukAss741** [comment]
Deleted by McAfee antivirus due to JTI/Suspect.196612l9ab08d7e8aaa
It is weird that electrum 3.3.3 has been working flawlessly since its release and this trouble started after update of electrum-ltc.

**Comment by SomberNight** [comment]
Then report it like this https://service.mcafee.com/webcenter/portal/cp/home/articleview?locale=en-US&articleId=TS102053

**Comment by LukAss741** [comment]
ok done. Thank you
