### ISSUE TITLE
Install error of Electrum3.3.3 on Windws10 Japanese version

### ISSUE THREAD

**Issue by nobutakai** [spesmilo/electrum#5095]
When I install Electrum 3.3.3 to version 3.3.2 on Windows10 Jaoanese version, some errors occur. If I ignore the messeges, installation ended normally. Is it Okay?

**Comment by SomberNight** [comment]
What is the error that occurs?

**Comment by nobutakai** [comment]
I have attached 2 error files.

 

Regards,

N.Ikegami

**Comment by birdie-github** [comment]
> I have attached 2 error files.

No you haven't since you replied using your email client. Please visit the issue at the GitHub tracker and upload the files manually.

**Comment by nobutakai** [comment]
Done.

**Comment by dabura667** [comment]
@nobutakai このスレッドに対するメールの返信を行った場合、添付ファイルはアップロードされませんので、ブラウザにてGithubにログインし、ブラウザのイシュー画面よりアップロードをお試し下さい。

**Comment by nobutakai** [comment]
![error2](https://user-images.githubusercontent.com/47491635/52601256-763f8f00-2ea1-11e9-9201-11f27c0eba6c.gif)
![error](https://user-images.githubusercontent.com/47491635/52601257-76d82580-2ea1-11e9-874c-cce53d2ae8c4.gif)

**Comment by nobutakai** [comment]
Done, second trial.

**Comment by SomberNight** [comment]
So these errors occur during the installation?
Have you closed the old Electrum before running the installer for the new version?

**Comment by nobutakai** [comment]
Yes, of cause. I closed old Electrum when I install new version.

**Comment by nobutakai** [comment]
I tried to newest version 3.3.4, and same error occur on the 3.3.4.

**Comment by SomberNight** [comment]
I have no idea why you are getting these errors.

To be clear, to reconfirm what you said in your first message, if you "ignore" the errors, the installation will finish and Electrum will be usable?

**Comment by nobutakai** [comment]
The installation seems to finish normally, but I have not send receive any bitcoin, since this error occurred. Electrum start normally and show my bitcoin normally.

**Comment by nobutakai** [comment]
The installation seems to finish normally, but I have not send receive any bitcoin, since this error occurred. Electrum start normally and show my bitcoin normally. 
 I think Japanese version of Electrum might be cause of this error, because I found this error on  upgrade for Electrum japanese version.

**Comment by nobutakai** [comment]
I found that My ant-virous protect to install Electrum. After adding Electrum to safe list, I was able to install Electrum 3.3.4 normally. Please close this issue. Thanks.
