### ISSUE TITLE
On Android: need to switch wallet on PIN entry startup if you forgot one

### ISSUE THREAD

**Issue by booyahbtc** [spesmilo/electrum#5097]
In Android version: If you just created a new wallet, and forgot the PIN to it, then there is no way to access the other wallets.

Proposed solution:

on the startup screen where it asks for PIN to the last-opened wallet: allow user to switch to other wallet instead (or create a new wallet if that was the only one).

**Comment by ecdsa** [comment]
ack. I closed the other issues you opened

**Comment by mdspawn** [comment]
Another issue is if you have many wallets and delete "default_wallet" it asks you to create a new wallet and have no options to open one of the existing wallets

**Comment by mdspawn** [comment]
And also the Android icon is unscaled and ugly

**Comment by ecdsa** [comment]
this has been fixed. the current dialog allows to switch wallet
