### ISSUE TITLE
PIN entry does not work on Android

### ISSUE THREAD

**Issue by booyahbtc** [spesmilo/electrum#5099]
I've just created a wallet, and when I try to open it, it says PIN is invalid.

It was the same PIN that I always used for other wallets in electrum (small funds anyway) and yet it doesn't let me in.

Either there is a rare bug with creating wallet, or something else gone wrong.

If #5098 would be implemented and would show the correct PIN when it's done, then I could confirm what happened there exactly.

**Comment by ecdsa** [comment]
not reproducible
please do not open 3 issues when you only have one
