### ISSUE TITLE
Can't create unsign transactions using CLI (Cold-Wallet)

### ISSUE THREAD

**Issue by venomone** [spesmilo/electrum#5102]
Hello, i want to use the following cmd from a cold-wallet:

electrum payto 1Cpf9za3Rm5Z5qmmGezn6ERxEDAwuZ6UJa 0.1 --unsigned > unsigned.txn

but i always get back the following response:

```
 electrum payto 1Cpf9za3Rm5Z5qmmGezn6ERxEDAwuZ6UJa 0.1 --unsigned > unsigned.txn
Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/coinchooser.py", line 334, in bucket_candidates_prefer_confirmed | electrum.util.NotEnoughFunds: Guthaben nicht ausreichend
>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/SimpleJSONRPCServer.py", line 388, in _dispatch
    return func(*params)
  File "/usr/local/lib/python3.6/dist-packages/electrum/daemon.py", line 297, in run_cmdline
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum/commands.py", line 97, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/electrum/commands.py", line 511, in payto
    tx = self._mktx([(destination, amount)], tx_fee, change_addr, domain, nocheck, unsigned, rbf, password, locktime)
  File "/usr/local/lib/python3.6/dist-packages/electrum/commands.py", line 495, in _mktx
    tx = self.wallet.make_unsigned_transaction(coins, final_outputs, self.config, fee, change_addr)
  File "/usr/local/lib/python3.6/dist-packages/electrum/wallet.py", line 681, in make_unsigned_transaction
    fee_estimator, self.dust_threshold())
  File "/usr/local/lib/python3.6/dist-packages/electrum/coinchooser.py", line 243, in make_tx
    self.penalty_func(tx))
  File "/usr/local/lib/python3.6/dist-packages/electrum/coinchooser.py", line 340, in choose_buckets
    candidates = self.bucket_candidates_prefer_confirmed(buckets, sufficient_funds)
  File "/usr/local/lib/python3.6/dist-packages/electrum/coinchooser.py", line 334, in bucket_candidates_prefer_confirmed
    raise NotEnoughFunds()
electrum.util.NotEnoughFunds: Guthaben nicht ausreichend
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 384, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 748, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 630, in _request
    check_for_errors(response)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpclib/jsonrpc.py", line 1321, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.6/dist-packages/electrum/coinchooser.py", line 334, in bucket_candidates_prefer_confirmed | electrum.util.NotEnoughFunds: Guthaben nicht ausreichend\n')
```

So why does it always says not enought funds, i guess that's 4 sure i use a wallet in watch-only ^^

CMD's to reproduce:

- create wallet if not available:
     electrum create

- get master public key from wallet:
     electrum getmpk

delete wallet:
      rm -R /home/user/.electrum

- restore as read-only wallet with the previously exported mpk:
     electrum restore xpubH4GauwAqRbcEm8MkcXvN1ghdw8...........

- start daemon:
    electrum daemon start

- load wallet
    electrum daemon load_wallet

- create unsigned txn and save to disk:
    electrum payto 1Cpf9za3Rm5Z5qmmGezn6ERxEDAwuZ6UJa 0.1 --unsigned > unsigned.txn

--> leads to error shown above.
Either this really is a bug or i'm really doing something wrong, any hint?

Kind regards

**Comment by SomberNight** [comment]
Can you run `electrum getbalance`?

**Comment by venomone** [comment]
yes that works in my test wallet:

```
electrum getbalance 
{
    "confirmed": "0"
}

```

**Comment by SomberNight** [comment]
Ok but if you have zero balance, and trying to create a tx for 0.1 btc, `NotEnoughFunds` is expected.

**Comment by venomone** [comment]
xD yes thats true ;)
But please keep in mind that i use it as a cold-wallet so to create unsign trx should be possible right? or at least it would be very useful if i want to create only public address on a machine and do the payout on another one. i guess that's the idea behind a cold-wallet. if not, please correct me.

im currently trying to figure out how i can create unsign trx without having the wallet loaded with my master key. At least this is also possible at the gui, please check the dokumentation here: http://docs.electrum.org/en/latest/coldstorage.html

**Comment by SomberNight** [comment]
First, you should test on testnet, so no money is at stake.

Create a wallet with seed, get its xpub. Now restore from xpub, send some coins to the corresponding addresses (from external sources; e.g. use a faucet when on testnet). Now you can create an unsigned transaction to pay some other address. Move this unsigned transaction to where your seeded wallet is, and there you can sign it. Then move back the signed transaction to a network-connected machine and broadcast it there.

In general, it sounds like you have the right idea, but the point you're missing is that you need coins to spend even just to create the unsigned transaction. Vaguely, the unsigned transaction is almost like a signed one, except it's missing the signatures. It still needs to reference existing unspent coins as inputs, so if you don't have coins, it cannot be created.

**Comment by venomone** [comment]
okay okay ;) thx for this info. I really appreciate that.
i guess i have to use a dirty hackaround here.
My idea is that i have a cold-storage on my website, maybe the best idea to accomplish this task is to create some kind of csv paytomany output so that i triger a payout every 12 hrs manualy from the seeded wallet.

can you give me a hint on the format of the csv. I guess that feature was available but i cant remeber. thx in advance

**Comment by venomone** [comment]
that seem to work:
3RqDGHDPxXdEfTs27UgWqTw7t5T5GdtR,0.01
