### ISSUE TITLE
No documentation on creating UpdateCheck files

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5103]
Electrum recently added an `UpdateCheck` class, which downloads a signed file from electrum.org.  Unfortunately there isn't any clear documentation about exactly how to generate the signed file.  Ideally there would be a script I could run that would create the file, and the location of that script would be documented in the README.

**Comment by SomberNight** [comment]
See the example in the code
https://github.com/spesmilo/electrum/blob/ebeed4736fc3dd60255f2808cbdead237caacc58/electrum/gui/qt/update_checker.py#L107-L113
I think it's relatively self-explanatory.

Put a version number as the value for `version`.
Sign that value using a bitcoin address.

The `signatures` dictionary maps from bitcoin addresses to signatures. (The signatures were made using the corresponding bitcoin address, the message being signed is the version number)
The dict can contain multiple signatures from different addresses, to make it possible to change the signing key (address) later.

In any case, @ecdsa probably has a script, but I suspect it's trivial.

**Comment by SomberNight** [comment]
See file added in https://github.com/spesmilo/electrum/commit/4e9dd679ab2fd8ccf3df6829772bb8a8a43d61c6

(note: this actually looks fragile; it assumes that you are on a tag, and the tag is exactly the same as the electrum version number...)

**Comment by JeremyRand** [comment]
> (note: this actually looks fragile; it assumes that you are on a tag, and the tag is exactly the same as the electrum version number...)

This was fixed by f60d1e7cb60c0193298ebd8c3ea8f9cdf8273312 .  Thanks, I consider this fixed.
