### ISSUE TITLE
del/

### ISSUE THREAD

**Issue by pananodi** [spesmilo/electrum#5104]
del

**Comment by SomberNight** [comment]
Click `Preview`. What is the "size" of the transaction?

**Comment by pananodi** [comment]
> 
> 
> Click `Preview`. What is the "size" of the transaction?

![vvv](https://user-images.githubusercontent.com/47530617/52572459-85cac380-2e20-11e9-845c-b3a71f224b75.png)

Inputs:407
Outputs:2

**Comment by SomberNight** [comment]
So the error message is correct. That transaction is too large. It is over 100 kilobytes, which is the maximum bitcoin nodes will relay on the network.

Unhide the Coins tab `View`>`Show Coins`, and then manually select some and construct a new transaction, which is smaller than 100 kilobytes.

**Comment by SomberNight** [comment]
May I ask how come you have so many small value inputs/coins?

**Comment by pananodi** [comment]
> 
> 
> May I ask how come you have so many small value inputs/coins?

Mining..0.002...0.001...0.003..

Whats i need to do? to send all btc?

**Comment by SomberNight** [comment]
In the Coins tab, select roughly half the lines, right click>`Spend`, and create a transaction. You might want to send to your own address. This way, instead of many small value coins, you will have fewer large value coins.

Also, I suggest setting the fee to as low as possible, and wait for it to confirm, as otherwise it will be potentially very expensive. (The larger the transaction in bytes, the more fees you need to pay to miners)

**Comment by pananodi** [comment]
> 
> 
> In the Coins tab, select roughly half the lines, right click>`Spend`, and create a transaction. You might want to send to your own address. This way, instead of many small value coins, you will have fewer large value coins.
> 
> Also, I suggest setting the fee to as low as possible, and wait for it to confirm, as otherwise it will be potentially very expensive. (The larger the transaction in bytes, the more fees you need to pay to miners)

and i can not link in one? i need make very many transations.

**Comment by SomberNight** [comment]
Try making the transactions you want; I am just saying that they need to be below 100 KB.

**Comment by AbdussamadA** [comment]
>and i can not link in one? i need make very many transations.

ctrl+click will let you select multiple entries on the coins tab (view menu > show coins if you can't see that tab). shift + click will also let you select multiple  contiguous entries.

**Comment by pananodi** [comment]
> 
> 
> > and i can not link in one? i need make very many transations.
> 
> ctrl+click will let you select multiple entries on the coins tab (view menu > show coins if you can't see that tab). shift + click will let you select multiple contiguous entries. then right click and choose spend to create a transaction with them.

new error..

![aaaa](https://user-images.githubusercontent.com/47530617/52575394-cdece480-2e26-11e9-98b3-dab619086060.png)

**Comment by SomberNight** [comment]
Can you share the raw transaction hex that is giving the "failed CHECK(MULTI)SIG" error?
`Preview`>`Sign` and then click `Copy`, and then paste it here.

**Comment by SomberNight** [comment]
Or if you have figured out the issue, please say so, don't just delete your posts.
This is an issue tracker, not customer support. We care about fixing bugs, not solving problems of individuals.
