### ISSUE TITLE
Decimal name collision with QCborKnownTags

### ISSUE THREAD

**Issue by oxqfsyef** [spesmilo/electrum#5109]
I was getting this error and crash with 3.3.3:

  File "/usr/local/lib/python3.7/site-packages/electrum/gui/qt/history_list.py", line 84, in lessThan
    if v1 is None or isinstance(v1, Decimal) and v1.is_nan(): v1 = -float("inf")
TypeError: isinstance() arg 2 must be a type or tuple of types

I tried:
print(type(v1), type(v2), type(Decimal))
=> "<class 'tuple'> <class 'tuple'> <enum 'QCborKnownTags'>"

I believe this is a name collision from PyQt5 (version 5.12 installed with pip)

renaming Decimal and changing everywhere fixed it:
from decimal import Decimal as PyDecimal

but not importing the other Decimal is probably the better solution.

I had previously used Electrum with Debian stable's python3 and python3-pyqt5 without issue but 3.3.3 required a python >= 3.6.

**Comment by ecdsa** [comment]
see #5101

**Comment by SomberNight** [comment]
This is fixed in https://github.com/spesmilo/electrum/commit/026448837fb23de74fc40067c82b7caa8211cccf
Please go back to pyqt 5.11 until next release, or run electrum from git master.
