### ISSUE TITLE
DEL

### ISSUE THREAD

**Issue by pananodi** [spesmilo/electrum#5112]
del

**Comment by SomberNight** [comment]
Unless it's urgent, looking at how many unconfirmed transactions you have, I would just **suggest to wait**.
It might take days though, depends on the fee market.

Looking at the error message, I suspect you might not have any outputs in these transactions that are controlled by this wallet. (Is there "change"?)
If this is the case, there is no "easy way" in the GUI to resolve this.

**Comment by pananodi** [comment]
> 
> 
> Unless it's urgent, looking at how many unconfirmed transactions you have, I would just **suggest to wait**.
> It might take days though, depends on the fee market.
> 
> Looking at the error message, I suspect you might not have any outputs in these transactions that are controlled by this wallet. (Is there "change"?)
> If this is the case, there is no "easy way" in the GUI to resolve this.

I update pictures...I see now: Local...I am afraid I will not get btc. Whats to do?

**Comment by pananodi** [comment]
Maybe i need to do deposit in wallet?

**Comment by AbdussamadA** [comment]
local means the transaction has been dropped from the server you connected to. it only exists in your wallet. you can right click on it and remove it.
