### ISSUE TITLE
Funds showing as received but balance remaining 0 and unable to access

### ISSUE THREAD

**Issue by Olizoo** [spesmilo/electrum#5113]
I transfered some funds from coinbase that have left my account and show as received by Electrum however I can't do anything with the funds as the balance has remained 0, what should I do please ?

Trans ID 663e54bf8c276201c8b88c729268c8487422306e0b159fc11deda46dd50e9323

**Comment by SomberNight** [comment]
What version of Electrum do you have?

Please update.

**Comment by Olizoo** [comment]
Hi, thanks for responding . . 3.2.3 I think !

**Comment by Olizoo** [comment]
I can screenshot you my account page showing the payment received but it has a yellow icon half filled next to it and the outgoing payment I tried to make shows as a red icon ?

**Comment by AbdussamadA** [comment]
Try switching servers. Tools > network > server tab, uncheck select server automatically, right click on a server in the list and choose use server.

**Comment by Olizoo** [comment]
Ok I will try that now . . 

If it doesn’t work can you just return the payment to coinbase and I will do it again ?

**Comment by AbdussamadA** [comment]
We don't control your wallet. Electrum is not a bank.

**Comment by ecdsa** [comment]
we cannot return the payment; this is Bitcoin, not a bank transfer.
please upgrade to the latest version on https://electrum.org

**Comment by Olizoo** [comment]
This server switch worked, thanks very much !

**Comment by Platinumwrist** [comment]
I'm getting I'm connected to 10 Nodes and the I lose connection could be on
my end the Blockchain 1579440 could I get guided in right direction thanks

**Comment by Platinumwrist** [comment]
In the Console. Welcome to ltc01.knas.system
Electrum 1.9.1
Litecoin core 0.16.3
Location Sweden
And please forgive me if I'm going at this the wrong way love some
assistance thanks
