### ISSUE TITLE
Wrong transaction fee calculation for segwit address

### ISSUE THREAD

**Issue by amokmen** [spesmilo/electrum#5116]
Electrum 3.3.3 (Win 10).

1. Trying to send BTC to segwit address.
2. **Manually set fee to 30 sat/byte**.
3. Send transaction.
4. Check transaction in [blockchain explorer](https://www.blockchain.com/btc/tx/).
5. **Real transaction fee is SMALLER than 30 sat/byte** and equal 19.054 sat/byte.

**Comment by SomberNight** [comment]
Report this to blockchain.info/com instead. Please check the feerate on https://blockstream.info/

**Comment by SomberNight** [comment]
To be clear, blockchain.info is calculating incorrectly.
