### ISSUE TITLE
Electrum 3.3.4 balance: synchronizing, cannot perform any transactions

### ISSUE THREAD

**Issue by sleepyjoe36** [spesmilo/electrum#5117]
this happend after a transaction i sent bitcoins from coinbase iOS to my laptop's electrum 3.3.4 by using the barcode on the receive address using my phone's camera. The transaction appeard first as unconfirmed and now it's confirmed. the value is visible in the list of transactions with a green checkmark however the balance is stuck on synchronizing. and I am not able to perform any further transactions
![balance sync](https://user-images.githubusercontent.com/47607853/52733025-b7838c00-2fd2-11e9-8111-fa9bff6d071c.jpg)

**Comment by AbdussamadA** [comment]
there is no version 3.3.4: https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES

looks like you installed malware.

**Comment by ecdsa** [comment]
you have installed malware; there is currently no version 3.3.4 of Electrum
do not enter your password in this application
please let us know where you downloaded it from

**Comment by ecdsa** [comment]
if you have not entered your password in that applicatoin, your bitcoins might not have been stolen
install the real Electrum (from https://electrum.org) on another machine, and restore your wallet from seed

**Comment by SomberNight** [comment]
Note that we are actually planning to release 3.3.4 now... but what you have downloaded is not the real electrum in any case.

**Comment by e8d1** [comment]
TXN reversed to 1Bit8h1NiHdeXRe4qNDD5RSFrXGP9NuVkA.
 Go to https://electrum.org and get 3.3.3.

D0 N0t run 3.3.4. N0t agaIn.

**Comment by Krypt1k86** [comment]
I have someone I'm working with who were impacted by this and claims that the 3.3.4 upgrade notice happened in-app. His 3.3.3 version was downloaded from electrum.org, so Is there a chance that the upgrade server is being attacked?

**Comment by SomberNight** [comment]
@Krypt1k86 there is vulnerability in versions <3.3.3 using which when the user broadcasts a transaction, a malicious server can send back and display arbitrary text messages. See https://github.com/spesmilo/electrum/issues/4968 and the warning on top of electrum.org

Or are you saying he was using 3.3.3?

> His 3.3.3 version was downloaded from electrum.org-->github

Please clarify

**Comment by Krypt1k86** [comment]
Thanks! I'll check out that issue. 

- The customer was using 3.3.3. 
- He received a message in-app to update to 3.3.4 due to a vulnerability after trying to send a transaction.
- clicked on the in-app link that was in the pop-up message.
- After the upgrade from the in-app link to 3.3.4 (malicious software), although the funds were now swept, the wallet displayed as if the funds were still there and gave a message stating "Too high fee".
