### ISSUE TITLE
Add documentation about signature verification of source/executable

### ISSUE THREAD

**Issue by Janaka-Steph** [spesmilo/electrum#5119]
Hello,

Regarding all the issues of phishing attacks and for security good practices, I think we should explain to the user how to verify ThomasV signature of source/executable. 
It should be explained on the readme page and/or on https://electrum.org/#download page.
Most people don't know how to do it. It's a pity not explaining it.
On Mac I use GPGTools, I download the .dmg and signature .asc, and I just double-click on the signature. It can't be easier, but you have to know it.

Thank you for considering this issue

**Comment by ecdsa** [comment]
I have updated the download page with instructions on how to verify on linux

**Comment by ecdsa** [comment]
please post more details on how to verify signatures on osx, windows, and I will add them to the site

**Comment by Janaka-Steph** [comment]
That's great but I actually don't see your documentation :-/  Yes I cleared my browser cache. 
Also, at the bottom right there is a link to "website source" which points to https://github.com/ecdsa/electrum-web …, last update in 2014.
Is the website source still open source?

**Comment by ecdsa** [comment]
that repository is deprecated, it has the former version of the website.
the current website is not hosted on github.

**Comment by Janaka-Steph** [comment]
Ok for the website.

Ha yes I found the "Verify signature" line in the "Installation from Python sources". It is better than nothing, but I think a real documentation is needed. 
Maybe a link "Learn how to verify software integrity" behind "Sources and executables are signed by ThomasV. " that points to a documentation page.

**Comment by ecdsa** [comment]
done

**Comment by Janaka-Steph** [comment]
Thank you for this update. 
Just to note one last thing. You mention the bitzuma tutorial for Windows, but it also exists for Mac https://bitzuma.com/posts/how-to-verify-an-electrum-download-on-mac/
He recommends GPG Suite and I think he is right, this software is very good, user can enjoy GPG smoothly integrated in various places of the OS. And as long as the software and signature have the same name and are located on the same folder, a user can just double-click the signature to verify the software.
