### ISSUE TITLE
Add `generate` command in regtest mode 

### ISSUE THREAD

**Issue by Janaka-Steph** [spesmilo/electrum#5120]
Hello,

I would like to play around with Electrum in regtest mode. I am able to launch it with --regtest, but I don't see any way of generating blocks. Do I miss something? What is the point of having a regtest mode if we can't generate blocks? :-/

Thank you

**Comment by SomberNight** [comment]
I'm afraid it's not that easy.

The architecture is:
electrum client  <-->  electrum server  <-->  bitcoind

So if you want to test something in regtest, you set up all three yourself, set all to regtest, and mine blocks in bitcoind.

**Comment by Janaka-Steph** [comment]
Ah yes, it makes sense. Thank you.
