### ISSUE TITLE
Exception: wallet not loaded. Use 'electrum daemon load_wallet' on Windows PC

### ISSUE THREAD

**Issue by udokaezepue** [spesmilo/electrum#5124]
I want to develop a site with PHP , so i want the site to use Electrum wallet.  When am testing it with this code:  $headers = array(
'Accept: application/json',
'Content-Type: application/json'
);

$password = 'lgKlAc27Iztnq2KKMQes9w==';         
$username = 'user';
$URL='http://127.0.0.1';   //Curl into own machine local ip is needed.
$port = 53627;

$ch = curl_init();

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

curl_setopt($ch, CURLOPT_URL,$URL);
curl_setopt($ch, CURLOPT_PORT, $port);
curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"id\":\"curltext\",\"method\":\"listaddresses\",\"params\":{\"funded\":true}}");
//curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"id\":\"curltext\",\"method\":\"getbalance\",\"params\":[13jf3cos7JQSFbaggWcfnzKm6UX8XkJK4k]}");
$result=curl_exec($ch);

if (curl_errno($ch)) { echo 'Error:' . curl_error($ch); }

 
curl_close ($ch);

echo "<br>";
var_dump($result=json_decode($result, true));
echo "<br>";
 

AM Getting the below error

C:\wamp\www\bitBarz\index1.php:67:
array (size=3)
  'result' => null
  'id' => string 'curltext' (length=8)
  'error' => 
    array (size=2)
      'code' => int -32603
      'message' => string 'Server error: File "electrum\commands.py", line 95, in func_wrapper | Exception: wallet not loaded. Use 'electrum daemon load_wallet'
' (length=134)

**Comment by ecdsa** [comment]
you need to load the wallet from the command line, you cannot do it from php

**Comment by SomberNight** [comment]
you might be able to load the wallet from php

adapt the following:
`
curl --data-binary '{"id":"curltext","method":"daemon","params":{"config_options":{"subcommand":"load_wallet", "wallet_path":"/home/user/.electrum/testnet/wallets/default_wallet", "password":"1234"}}}' http://user:pass@127.0.0.1:7777
`

**Comment by udokaezepue** [comment]
> 
> 
> you need to load the wallet from the command line, you cannot do it from php

How do i load it from command line please?

**Comment by udokaezepue** [comment]
> 
> 
> you might be able to load the wallet from php
> 
> adapt the following:
> `curl --data-binary '{"id":"curltext","method":"daemon","params":{"config_options":{"subcommand":"load_wallet", "wallet_path":"/home/user/.electrum/testnet/wallets/default_wallet", "password":"1234"}}}' http://user:pass@127.0.0.1:7777`

WOW. I have loaded the wallet using php in my localhost of windows 8.0 system. Thank you SomberNight. The below is my working code


<?php
require_once './Electrum/vendor/autoload.php';
 
  
//LOADING WALLET
 $headers = array(
'Accept: application/json',
'Content-Type: application/json'
);

$password = 'mypassword_i_got_inside_config_file_of_my_standalone_wallet_folder';         
$username = 'myusername_i_got_inside_config_file_of_my_standalone_wallet_folder';
$URL='http://127.0.0.1';   //Curl into own machine local ip is needed.
$port = myport_i_got_inside_daemon_file_of_my_standalone_wallet_folder;

$ch = curl_init();

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);


curl_setopt($ch, CURLOPT_URL,$URL);
curl_setopt($ch, CURLOPT_PORT, $port);
curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, '{"id":"curltext","method":"daemon","params":{"config_options":{"subcommand":"load_wallet", "wallet_path":"C:/Users/udoka/Desktop/electrum_data/wallets/default_wallet", "password":"myWalletPassword"}}}');
 $result=curl_exec($ch);

if (curl_errno($ch)) { echo 'Error:' . curl_error($ch); }

 
curl_close ($ch);

echo "<br>";
var_dump($result=json_decode($result, true));
if($result['result']==true){
    echo '<span style=color:green;>ELECTRUM WALLET DAEMON HAS LOADED AND STARTED RUNNING..</span>.';
}
echo "<br>";
 
?>

**Comment by udokaezepue** [comment]
WOW. I have loaded the wallet using php in my localhost of windows 8.0 system. Thank you SomberNight. The below is my working code


<?php
require_once './Electrum/vendor/autoload.php';
 
  
//LOADING WALLET
 $headers = array(
'Accept: application/json',
'Content-Type: application/json'
);

$password = 'mypassword_i_got_inside_config_file_of_my_standalone_wallet_folder';         
$username = 'myusername_i_got_inside_config_file_of_my_standalone_wallet_folder';
$URL='http://127.0.0.1';   //Curl into own machine local ip is needed.
$port = myport_i_got_inside_daemon_file_of_my_standalone_wallet_folder;

$ch = curl_init();

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);


curl_setopt($ch, CURLOPT_URL,$URL);
curl_setopt($ch, CURLOPT_PORT, $port);
curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_POSTFIELDS, '{"id":"curltext","method":"daemon","params":{"config_options":{"subcommand":"load_wallet", "wallet_path":"C:/Users/udoka/Desktop/electrum_data/wallets/default_wallet", "password":"myWalletPassword"}}}');
 $result=curl_exec($ch);

if (curl_errno($ch)) { echo 'Error:' . curl_error($ch); }

 
curl_close ($ch);

echo "<br>";
var_dump($result=json_decode($result, true));
if($result['result']==true){
    echo '<span style=color:green;>ELECTRUM WALLET DAEMON HAS LOADED AND STARTED RUNNING..</span>.';
}
echo "<br>";
 
?>
