### ISSUE TITLE
version 3.3.4 reports its version as 3.3.3

### ISSUE THREAD

**Issue by 8go** [spesmilo/electrum#5127]
On Linux running ./run_electrum version returns 3.3.3
even tough the version.py file contain 3.3.4
electrum/version.py:ELECTRUM_VERSION = '3.3.4'   # version of the client package
electrum/version.py:APK_VERSION = '3.3.4.0'      # read by buildozer.spec

**Comment by SomberNight** [comment]
Do you maybe have an unupdated electrum daemon running in the background?
```
./run_electrum daemon stop
```

**Comment by 8go** [comment]
Yes, that was the problem. Issue solved. There was no issue.Thanks.
