### ISSUE TITLE
electrum

### ISSUE THREAD

**Issue by MAK123456789** [spesmilo/electrum#5134]
Кошелёк electrum не является безопасным. Более того он является воровским 2 раза он сам менял адрес отправки воруя у меня деньги https://blockchair.com/bitcoin/transaction/a1a1e08b1ba723e700d15e4937457ddc2dfa241b158170d74efc69870013d922
https://blockchair.com/bitcoin/transaction/1b6f28778aeff1b62ec9ab778cdc01005d0c15823fd707217f1e13db98557028
Все 2 раза я тщательно проверял адрес отправки и он сам его изменял. Если вы пользуетесь electrum помните что вы рискуете отправить BTC по неизвестному адресу и потерять деньги. Не рискуйте и не используйте его.
Последний раз отправлял по адресу 388SkNYcqB6ZS5CHG4oZbAvdVgLJEsWESW два раза проверил адрес но electrum подменил адрес и ничего не дошло. Делайте выводы.

**Comment by ecdsa** [comment]
Electrum does not modify the recipient address of your transactions. 
Anyone who can read code can check the source code of Electrum to check this.
Either you have downloaded malware, or you are trying to spread misinformation.

**Comment by MAK123456789** [comment]
Я не распространяю дезу я говорю факты из за добаного  электрума я дважды потерял деньги мне как пользователю ровным счётром насрать в чём ваши проблемы но электрум меняет адрес и это факт. Насчёт вирусов я сразу как только электрум поменял адрес переустановил систему и отфармотировал диск и сново он поменял адрес. Нельзя исправить то что вы намеренно зашили в кошелёк. Мне очень жаль что вы стали воровать я пользовался им очень давно и считал его защищённым. Если вы счетаете что я лгу то объясните мне как он меняет адреса получателя и не говорите что это вирус я систему сразу переустановил и диск отфармотировал. Я дважды потерял деньги и мне не до смеха. Вот ципочки [https://blockchair.com/bitcoin/transaction/a1a1e08b1ba723e700d15e4937457ddc2dfa241b158170d74efc69870013d922 ](https://blockchair.com/bitcoin/transaction/a1a1e08b1ba723e700d15e4937457ddc2dfa241b158170d74efc69870013d922)
https://blockchair.com/bitcoin/transaction/1b6f28778aeff1b62ec9ab778cdc01005d0c15823fd707217f1e13db98557028
Я каждый раз проверял адрес но электрум менял его при отправки.

**Comment by MAK123456789** [comment]
У меня создаётся впечатление что вы специально это сделали с кошельком.
