### ISSUE TITLE
Nice trick to get windows users to upgrade version

### ISSUE THREAD

**Issue by CuplexUser** [spesmilo/electrum#5136]
The windows installer (Windows Installer binary) available from https://electrum.org/#download contains malicious code! Aka "virus". Even the signature is wrong.

Im building from source from now on and why not the Linux version.

**Comment by pjvvp** [comment]
один из разработчиков вставил вредоносный код. больше не верить.

**Comment by ecdsa** [comment]
this user is either stupid or malicious
