### ISSUE TITLE
I upgraded to 4.0.0. version and all my funds was gone to electrum tip jar

### ISSUE THREAD

**Issue by frankthebeer** [spesmilo/electrum#5142]
hi today i tried to pay something (165$CAD) with bitcoin on electrum3.2.3. as i always did, but it says i have to upgraded to electrum4.0.0. and then  they will proceed  for my transaction.But  after i upgraded to 4.0.0. my whole funds (267$CAD) was gone to an address i never saw and apparently its an electrum tip jar address.  the money was gone  without i press any key. So i would like to know what happened and how i could be refund?

01053dc29736973e1d95d932651e868d9b788955b4273d01e968e7acf0247cbe

bc1qhsrl6ywvwx44zycz2tylpexza4xvtqkv6d903q	     0.05102198btc

**Comment by ecdsa** [comment]
Sorry, but your funds have been stolen.
There is no electrum 4.0.0, you have downloaded malware.
Could you check your browser history and let us know from which website you downloaded 4.0.0 ?

**Comment by SomberNight** [comment]
> an address i never saw and apparently its an electrum tip jar address

Why do you think so?

**Comment by ecdsa** [comment]
closing, no answer

**Comment by ale8184** [comment]
it happened to me the same thing I lost 400 dollars in btc to the same wallet!
