### ISSUE TITLE
infections detected on website virus total

### ISSUE THREAD

**Issue by javiertuerca** [spesmilo/electrum#5143]
Download electrum-3.3.4-setup.exe from your website and verify the PGP signatures, all correct, but when analyzing the executable file for windows in virustotal, it throws 5 detections.
Can I consider this as false positives?

https://www.virustotal.com/es-ar/file/4afe9fe07318f7ed804ab2ccb6e6b7e65971ffeaad97c612e0d364d05b196f79/analysis/1550671469/

**Comment by ecdsa** [comment]
yes
