### ISSUE TITLE
Load transaction via QRcode has failed....

### ISSUE THREAD

**Issue by woogi013** [spesmilo/electrum#5154]
any ideas why this could be?

**Comment by SomberNight** [comment]
Please provide more details.
What kind of wallet (segwit or not, multisig or not, how many signers if so, ...)?
How big is the transaction in bytes? Or just how many inputs/outputs?
Using Android version or Desktop version for both scanner and displayer of QR code?

**Comment by ecdsa** [comment]
closing, no answer
