### ISSUE TITLE
[Android] Double-spent transactions still persist as "Local"

### ISSUE THREAD

**Issue by andronoob** [spesmilo/electrum#5156]
Version: 3.3.4

Since the coins were already spent, Electrum server returned "Missing input" after clicking the "Broadcast" button.

I'm not sure whether this issue could be reproduced, but, I still wonder if these "local transactions" could be deleted from the wallet?

**Comment by SomberNight** [comment]
ACK. we need a way to delete a local transaction in Kivy.
