### ISSUE TITLE
Android Fiat Currency "Some currency not existing as desktop".

### ISSUE THREAD

**Issue by kpstar** [spesmilo/electrum#5157]
Desktop has all currencies in setting/Fiat Currency with history options.
But android doesn't have some currencies because history option is set True by default.

I am about to use 'COP' currency but can't find in android. How can I use? Thanks.

**Comment by SomberNight** [comment]
> But android doesn't have some currencies because history option is set True by default.

Yes, you are correct.

What exactly is the suggestion? To allow toggling the history option like in Qt?

**Comment by kpstar** [comment]
![screenshot_28](https://user-images.githubusercontent.com/36706893/53345738-8b5ff780-3950-11e9-925b-47f463ba7c9b.png)

**Comment by kpstar** [comment]
Thanks for your reply, @SomberNight 
I tried to change like this as attached image and installed my phone.
It seemed there was no error regarding this action.
I am just wondering why you disable history option.

I am also a mobile developer and want to contribute to your project.
I wish you would give me some opinions. Thanks.

**Comment by SomberNight** [comment]
In Kivy, on the "Balance" tab, if you tap your balance at the top, all the values change between BTC and fiat.
This is only possible with historical conversion rates. Thus, for simplicity, only currency/exchange combos that offer historical rates can be selected.

**Comment by kpstar** [comment]
Isn't there any way for all currencies in android?

**Comment by kpstar** [comment]
For example, setting checkbox for history option like desktop.
Because I use 'COP' currency and mobile is essential.

**Comment by SomberNight** [comment]
You could add the same "show fiat history rates" option to settings like in Qt, enabled by default.

**Comment by accumulator** [comment]
qml client uses FX like desktop, closing.
