### ISSUE TITLE
£4,450 STOLEN ON ELECTRUM HACK!!

### ISSUE THREAD

**Issue by Jack-Jordan** [spesmilo/electrum#5158]
I started my computer, started Electrum, and I noticed immediately that the Electrum program asked me to update to version 4.0.  So of course I allowed this update version.  Immediately afterwards, I see that a transaction has started, been signed for, and is in progress to transfer out ALL my entire balance of bitcoin which was worth £4500, all being transferred out, by some hacker asshole because the Electrum Wallet allowed this to happen.  
So, Electrum, how are you going to make this right? You owe me 1.3bitcoin as of 25/02/2019.  So how is this being resolved? More details are available if you want to see it.
FIX THE SITUATION - PAY ME WHAT YOU OWE ME!

**Comment by QBall59** [comment]
Same thing just happened to me! I went to transfer a much smaller amount of btc and it has remained in "unconfirmed" mode for several hours now. Plus, an inbound payment that I received was immediately transferred out of my account! I'm out about USD 800. WTF Electrum?!??

**Comment by SomberNight** [comment]
There is no Electrum version 4.0. Where did you download from?

-------- Original Message --------

**Comment by Jack-Jordan** [comment]
Unplug your internet NOW and system restore to when you installed electrum, then reinstall and use 12 word seed recovery

Sent from my iPhone

On 25 Feb 2019, at 20:53, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:


Same thing just happened to me! I went to transfer a much smaller amount of btc and it has remained in "unconfirmed" mode for several hours now. Plus, an inbound payment that I received was immediately transferred out of my account! I'm out about USD 800. WTF Electrum?!??

**Comment by Jack-Jordan** [comment]
Exactly. I opened Electrum as normal, But then a pop-up screen said I needed to upgrade to 4.0, so I did that. That clearly was the scam

Sent from my iPhone

On 25 Feb 2019, at 20:53, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:


Same thing just happened to me! I went to transfer a much smaller amount of btc and it has remained in "unconfirmed" mode for several hours now. Plus, an inbound payment that I received was immediately transferred out of my account! I'm out about USD 800. WTF Electrum?!??

**Comment by QBall59** [comment]
It was just a window that popped-up when I opened the wallet to send btc. I updated it and now I’ve been ripped off.

**Comment by Jack-Jordan** [comment]
They owe us payback! For real we should start a campaign

Sent from my iPhone

On 25 Feb 2019, at 21:00, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:

It was just a window that popped-up when I opened the wallet to send btc. I updated it and now I’ve been ripped off.

**Comment by SomberNight** [comment]
>> There is no Electrum version 4.0. Where did you download from?

> It was just a window that popped-up when I opened the wallet to send btc. I updated it and now I’ve been ripped off.

You avoided the question though. I assume you went to some website. There is no version 4.0 on the [official website](https://electrum.org/#download). What you downloaded is not Electrum; it's malware.

**Comment by Jack-Jordan** [comment]
Let me make this very clear for your simple simple mind to grasp.
I double clicked electrum just like normal, just like every day, and this time instead of electrum opening, it opened in the background but in the foreground was a pop-up that said I needed to upgrade/update before I could open the program. So, like 99% of everybody else, I downloaded the so-called update.
It was only until I start the transaction that I did not authorise that I became suspicious and checked the version of program, and realised there is no 4.0.
Is that simple enough for your mind to grasp?

Sent from my iPhone

On 25 Feb 2019, at 21:22, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


There is no Electrum version 4.0. Where did you download from?

It was just a window that popped-up when I opened the wallet to send btc. I updated it and now I’ve been ripped off.

You avoided the question though. I assume you went to some website. There is no version 4.0 on the official website<https://electrum.org/#download>. What you downloaded is not Electrum; it's malware.

**Comment by mdspawn** [comment]
It's a well known malware, allowing anonymous servers to show rich text messages is irresponsible in my opinion. Here is a Reddit post: https://www.reddit.com/r/Bitcoin/comments/anycg2/electrum_targeted_phishing_malware_warning/

**Comment by SomberNight** [comment]
> I double clicked electrum just like normal, just like every day, and this time instead of electrum opening, it opened in the background but in the foreground was a pop-up that said I needed to upgrade/update before I could open the program.

"Let me make it very clear for you." There is no mechanism in Electrum that would allow it to prompt you to update directly after opening, so what you had been using must not have been Electrum to start with.

**Comment by SomberNight** [comment]
> It's a well known malware, allowing anonymous servers to show rich text messages

That is not what @Jack-Jordan described. He said the popup was shown directly after opening.

**Comment by QBall59** [comment]
Well, the plot thickens. I uninstalled the Electrum 4.0.0 wallet from my system. I then downloaded and installed, from Electrum.org, the official wallet 3.4.4. All good, except when I went to run the program, I got a fatal error message "failed to execute script run-electrum"... :-(

**Comment by SomberNight** [comment]
@QBall59 what operating system is this and exactly how did you "install" electrum?

**Comment by QBall59** [comment]
Windows 10. I downloaded the windows installer package from electrum.org and ran it.

**Comment by SomberNight** [comment]
can you please take a screenshot of the error message?

**Comment by QBall59** [comment]
![electrum_error_msg](https://user-images.githubusercontent.com/47992518/53372773-7c6a4c80-3932-11e9-98ed-9d3f733036b9.jpg)

**Comment by QBall59** [comment]
well @SomberNight, what do you make of this?

**Comment by SomberNight** [comment]
@QBall59 exactly when does this popup appear? Is it when launching Electrum before anything else appears?
Please try renaming the folder at `%appdata%/Electrum` to something else, and see if it works then.

**Comment by QBall59** [comment]
It appears as soon as I click on the Electrum link, that was installed on my desktop, to open the program

**Comment by Jack-Jordan** [comment]
You have been hacked my friend

Sent from my iPhone

On 25 Feb 2019, at 22:47, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:


It appears as soon as I click on the Electrum link, that was installed on my desktop, to open the program

**Comment by QBall59** [comment]
This is a vicious piece of malware...

**Comment by QBall59** [comment]
OK. I got rid of the corrupted folder and all its files. I re-installed Electrum and it worked. However, I've still lost all the BTC in the corrupt wallet.

Question (and I know I'm probably dreaming here..): is there any way to recover stolen BTC?

**Comment by SomberNight** [comment]
> I got rid of the corrupted folder and all its files.

Which folder was it specifically?

> is there any way to recover stolen BTC?

No.

**Comment by QBall59** [comment]
Program Files (x86)/Electrum

**Comment by Jack-Jordan** [comment]
Search online for “stolen btc recoverers “ . I am doing it now via Skype with Igo

Sent from my iPhone

On 25 Feb 2019, at 23:11, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


I got rid of the corrupted folder and all its files.

Which folder was it specifically?

is there any way to recover stolen BTC?

No.

**Comment by QBall59** [comment]
who is Igo?

**Comment by SomberNight** [comment]
> Search online for “stolen btc recoverers “ . I am doing it now via Skype with Igo

be careful not to get scammed twice in a row :/

**Comment by QBall59** [comment]
@SomberNight I don't think I downloaded a corrupted or hacked version of the wallet. I installed on my computer 6 months ago, and had made other transactions with no problems whatsoever. What happened today is somehow, some way, a pop-up window managed to force me to install the malware 4.0.0 version of the wallet. This security breach needs to be identified and fixed ASAP.

**Comment by Jack-Jordan** [comment]
Me too We are probably dealing with the same guy, and it seems like a scam to me

Sent from my iPhone

On 25 Feb 2019, at 23:35, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


Search online for “stolen btc recoverers “ . I am doing it now via Skype with Igo

be careful not to get scammed twice in a row :/

**Comment by Jack-Jordan** [comment]
Exactly

Sent from my iPhone

On 26 Feb 2019, at 00:29, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:


@SomberNight<https://github.com/SomberNight> I don't think I downloaded a corrupted or hacked version of the wallet. I installed on my computer 6 months ago, and had made other transactions with no problems whatsoever. What happened today is somehow, some way, a pop-up window managed to force me to install the malware 4.0.0 version of the wallet. This security breach needs to be identified and fixed ASAP.

**Comment by SomberNight** [comment]
What likely happened is that when you broadcasted a transaction, you got an error message. Until recently, this error message could contain arbitrary text, and some malicious servers started sending errors that told people to install malware. See https://github.com/spesmilo/electrum/issues/4968

What @Jack-Jordan described about the popup that appeared directly after opening Electrum however is something different, and I can't imagine how that could have happened.

**Comment by QBall59** [comment]
What happened to Jack-Jordan is the exact same thing that happened to me. 

Also, if memory serves me correct, I downloaded Electrum from the Bitcoin.org site, so I doubt the version I got there was malware.

**Comment by SomberNight** [comment]
Do either of you know what version of Electrum did you have when you saw this popup?

**Comment by Jack-Jordan** [comment]
Exactly. Some people are just low iQ, dumbasses can’t understand things. Not their fault

Sent from my iPhone

On 26 Feb 2019, at 00:51, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:


What happened to Jack-Jordan is the exact same thing that happened to me.

Also, if memory serves me correct, I downloaded Electrum from the Bitcoin.org<http://Bitcoin.org> site, so I doubt the version I got there was malware.

**Comment by Jack-Jordan** [comment]
I had like 3.4.4 then it told me I needed to upgrade to 4.0, before they would even open the program electrum

Sent from my iPhone

On 26 Feb 2019, at 00:53, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do either of you know what version of Electrum did you have when you saw this popup?

**Comment by SomberNight** [comment]
> I had like 3.4.4

There is no 3.4.4, so then you already had malware.

**Comment by Jack-Jordan** [comment]
3.3.3 whatever man jeez

Sent from my iPhone

On 26 Feb 2019, at 00:54, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


I had like 3.4.4

There is no 3.4.4, so then you already had malware.

**Comment by Jack-Jordan** [comment]
I got it from bitcoin.org<http://bitcoin.org> as well or whatever

Sent from my iPhone

On 26 Feb 2019, at 00:54, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


I had like 3.4.4

There is no 3.4.4, so then you already had malware.

**Comment by QBall59** [comment]
@SomberNight I had 3.3.4. installed.

**Comment by Jack-Jordan** [comment]
That’s the one. Had it also.

Sent from my iPhone

On 26 Feb 2019, at 00:56, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:


@SomberNight<https://github.com/SomberNight> I had 3.3.4. installed.

**Comment by SomberNight** [comment]
@Jack-Jordan lol. so far you have named three different versions. I am asking for a reason you know.

**Comment by Jack-Jordan** [comment]
I know bud. Look I’m stoned yeah, I knew there was a bunch of 3’s and a 4 in there. But not 4.0
Kitkat time - give me a break

Sent from my iPhone

On 26 Feb 2019, at 00:57, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


@Jack-Jordan<https://github.com/Jack-Jordan> lol. so far you have named three different versions. I am asking for a reason you know.

**Comment by SomberNight** [comment]
@QBall59 
> I don't think I downloaded a corrupted or hacked version of the wallet. I installed it on my computer 6 months ago,
> I had 3.3.4. installed.

but 3.3.4 was only released like 2 weeks ago :/

**Comment by QBall59** [comment]
Then it was 3.3.3.

**Comment by SomberNight** [comment]
3.3.3 was released 2019-01-25

**Comment by QBall59** [comment]
I originally downloaded and installed the wallet on August 16 of last year, so it was whatever version was current at that time.

**Comment by SomberNight** [comment]
Ok. That would be 3.2.2

**Comment by AbdussamadA** [comment]
@SomberNight these two are the same person and he's trolling you. Both accounts signed up at the same time and as you can see what they are saying doesn't make sense. I suggest locking this thread.

**Comment by Jack-Jordan** [comment]
I’m pretty sure you are the theif, looking st your ip and nat.table ... idiot. Why even talk here?? Guilty conscience??

Sent from my iPhone

On 26 Feb 2019, at 12:21, Abdussamad Abdurrazzaq <notifications@github.com<mailto:notifications@github.com>> wrote:


@SomberNight<https://github.com/SomberNight> these two are the same person and he's trolling you. Both accounts signed up at the same time and as you can see what they are saying doesn't make sense. I suggest locking this thread.

**Comment by QBall59** [comment]
@AbdussamadA I'm pretty sure SomberNight can simply look at our IP addresses and know we are not the same person. As Jack-Jordan says, you're probably the thief, except I doubt you even have a conscience...

**Comment by Jack-Jordan** [comment]
Lmfao- this guy gets it!

Sent from my iPhone

On 26 Feb 2019, at 12:39, QBall59 <notifications@github.com<mailto:notifications@github.com>> wrote:


@AbdussamadA<https://github.com/AbdussamadA> I'm pretty sure SomberNight can simply look at our IP addresses and know we are not the same person. As Jack-Jordan says, you're probably the thief, except I doubt you even have a conscience...

**Comment by SomberNight** [comment]
> pretty sure SomberNight can simply look at our IP addresses

I am not an admin at github.

In any case, there is nothing we can do regarding already stolen coins.

**Comment by QBall59** [comment]
@SomberNight Can you do anything to make sure it doesn't happen to anyone else? Are you involved with the development of Electrum? I still have no idea how this happened, and it certainly doesn't make me want to use the Electrum wallet again!

**Comment by Jack-Jordan** [comment]
funny how the 18 other comments after this last one of mine being flamed by some dork Who is in all likelyhood the theif...... just STFU and stop robbing people man.  Idiot.

**Comment by Jack-Jordan** [comment]
funny how the 18 other comments that were after that last qball dork got deleted... lil suspicious? aint that a lil suspicious, just a little bit suspicious......... every single flaming you with evidence gets deleted. Prickend.  Go choke on you knobcheese

**Comment by QBall59** [comment]
Jack darling… I got ripped off for about USD 850 the same way you did. I will not use the Electrum wallet ever again.

**Comment by etcrypto** [comment]
Electrum should publish about that matter.
The SAME situation Here! 
and this is was after downloading from the official site !!

**Comment by Jack-Jordan** [comment]
What’s the point, can’t recover so....

Sent from my iPhone

On 18 Mar 2019, at 16:19, etcrypto <notifications@github.com<mailto:notifications@github.com>> wrote:


Electrum should publish about that matter.
The SAME situation Here!
and this is was after downloading from the official site !!

**Comment by Jack-Jordan** [comment]
What possible good can come from publishing

Sent from my iPhone

On 18 Mar 2019, at 16:19, etcrypto <notifications@github.com<mailto:notifications@github.com>> wrote:


Electrum should publish about that matter.
The SAME situation Here!
and this is was after downloading from the official site !!

**Comment by etcrypto** [comment]
Informing others to not use that crappy wallet. 

Personally, im going to switch to other wallets and trying to convince others to do so

**Comment by SomberNight** [comment]
> and this is was after downloading from the official site !!

Please copy-paste the exact URL you've downloaded from.
Also, what exactly do you claim to have happened and when?

**Comment by Jack-Jordan** [comment]
Was a pop up when I opened my Electrum wallet to upgrade. I clicked ok. Within 6 mins my account was drained.

Sent from my iPhone

On 18 Mar 2019, at 17:12, ghost43 <notifications@github.com<mailto:notifications@github.com>> wrote:


and this is was after downloading from the official site !!

Please copy-paste the exact URL you've downloaded from.
Also, what exactly do you claim to have happened and when?
