### ISSUE TITLE
 I can not send my BTC

### ISSUE THREAD

**Issue by shoint** [spesmilo/electrum#5160]
Hello, I can not send my BTC. I have two messages:
- one who asks me to enter my password. when I enter it I get an error message that appears
- "The server returned an error while transmitting the transaction.
Try to connect to a different server or update Electrum.

Unknown error"

what can I do ? I have version 3.3.4

**Comment by AbdussamadA** [comment]
Switch to a different server. Tools > network > server tab, uncheck select automatically, right click on a different server and choose use server. Then try to send btc again.

**Comment by kuedsu** [comment]
Hello!
I get an error!

"""The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

insufficient fee"""

I already did it, but nothing helped me

""Switch to a different server. Tools > network > server tab, uncheck select automatically, right click on a different server and choose use server. Then try to send btc again.""
