### ISSUE TITLE
Only Splash screen and exit immediately 3.3.3 (Android)

### ISSUE THREAD

**Issue by kpstar** [spesmilo/electrum#5161]
Hello
I use Samsung Galaxy S7 edge for electrum.
I compiled kivy android 3.3.3 as readme.txt and got Electrum3.3.3-debug.apk.
but when I install it on my phone, it shows splash screen and exit immediately.

bash arg: -p
  bash arg: org.electrum.electrum
  bash arg: 1
args: [-p, org.electrum.electrum, 1]
 arg: "-p"
 arg: "org.electrum.electrum"
 arg: "1"
data="org.electrum.electrum"
Events injected: 1
## Network stats: elapsed time=47ms (0ms mobile, 0ms wifi, 47ms not connected)

This is what I found from adb monkey instructions. Please help me work properly on my phone.
Thanks.

**Comment by SomberNight** [comment]
Try getting logs through adb:
```
adb logcat | grep python
```

**Comment by kpstar** [comment]
02-26 19:22:02.216  3537  3571 I python  : Android kivy bootstrap done. __name__ is __main__
02-26 19:22:02.216  3537  3571 I python  : AND: Ran string
02-26 19:22:02.216  3537  3571 I python  : Run user program, change dir and execute entrypoint
02-26 19:22:02.445  3537  3571 I python  : Traceback (most recent call last):
02-26 19:22:02.445  3537  3571 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/main.py", line 68, in <module>
02-26 19:22:02.445  3537  3571 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/__init__.py", line 2, in <module>
02-26 19:22:02.445  3537  3571 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/util.py", line 44, in <module>
02-26 19:22:02.445  3537  3571 I python  : ModuleNotFoundError: No module named 'aiohttp'
02-26 19:22:02.445  3537  3571 I python  : Python for android ended.

**Comment by SomberNight** [comment]
Inside the root `electrum` folder that you cloned, after running `./contrib/make_packages`,
you should have a `packages` folder. Is there an `aiohttp` folder inside that? (`electrum/packages/aiohttp`)

In fact did you run `make_packages`?
There has been a sanity check added recently that makes sure this was not forgotten; are you on latest git HEAD? Please try on at least 3.3.4.

**Comment by SomberNight** [comment]
I believe this does not happen if you follow the instructions; so closing
