### ISSUE TITLE
Make dependency to aiorpcx optional or remove it

### ISSUE THREAD

**Issue by schildbach** [spesmilo/electrum#5164]
Version 3.3.0 of Electrum introduced a dependency to aiorpcx, which -- as far as I know -- is not available as a Debian package. Before 3.3, all mandatory dependencies of Electrum could be satisfied by installing Debian packages.

**Comment by kyuupichan** [comment]
So ... make one?

**Comment by SomberNight** [comment]
Is it important whether there is a Debian package for a dependency? I mean, obviously if you are trying to package Electrum itself, then you need to package all the dependencies too, so in that case it is, but I assume that is not the case for you (?).

What exactly is your use case? Please give some context.

@kyuupichan is aiorpcx stable enough now for packaging?

**Comment by schildbach** [comment]
Debian generally is a trusted source. They take security serious. E.g. they reproducibly build everything from source. And yeah, imho Electrum should be (optionally) be distributed via Debian too.

**Comment by kyuupichan** [comment]
@SomberNight not sure what you mean; it's packaged on PyPI.  The API is not stable yet, no.

**Comment by SomberNight** [comment]
@kyuupichan debian stable often gets stuck with a particular version of a package for 1-2 years. if the package is in debian stable but the API since that has changed (say) twice already, that's not going to be much help for anyone.
My point basically is that there's not much point in packaging libraries for Debian until they are really mature.

@schildbach ok I see. So your argument is that you trust Debian more than PyPI. Fair enough.
1. You can grab the Electrum tar.gz from the website, unpack it, and run it directly without installing:
    ```
    wget https://download.electrum.org/3.3.4/Electrum-3.3.4.tar.gz
    wget https://download.electrum.org/3.3.4/Electrum-3.3.4.tar.gz.asc
    gpg --verify Electrum-3.3.4.tar.gz.asc
    tar -xvf Electrum-3.3.4.tar.gz
    python3 Electrum-3.3.4/run_electrum
    ```
    (this is copied from the website)
    note that you also need python3.6 (and pyqt5 for it), which is not in Debian Stretch (stable)

2. On x86_64, you can use the AppImage we distribute.
    ```
    wget https://download.electrum.org/3.3.4/electrum-3.3.4-x86_64.AppImage
    wget https://download.electrum.org/3.3.4/electrum-3.3.4-x86_64.AppImage.asc
    gpg --verify electrum-3.3.4-x86_64.AppImage.asc
    chmod +x electrum-3.3.4-x86_64.AppImage
    ./electrum-3.3.4-x86_64.AppImage
    ```

**Comment by ecdsa** [comment]
I guess this can be closed now

**Comment by schildbach** [comment]
@ecdsa Does that mean the dependency is now optional?

**Comment by ecdsa** [comment]
@schildbach no, that dependency will not be optional. 
I think @SomberNight properly answered your questions

**Comment by schildbach** [comment]
@ecdsa  No, the issue is not a question.

**Comment by ecdsa** [comment]
@schildbach so what are you suggesting? that we rewrite the network layer without that module?

**Comment by schildbach** [comment]
@ecdsa Either that, or use the network layer from version 3.2.x? It didn't have that dependency.

**Comment by u451f** [comment]
It's unfortunate that this depencendy does not yet exist in Debian. This means that it's currently impossible to provide a trusted installation of Electrum for Debian users and all derivatives (Tails, Ubuntu, Mint…) But the solution would be to package aiohttp_socks and aiorpcx for Debian.
