### ISSUE TITLE
Message: Transaction was rejected by network rules\n\n16:  Tx-overwinter active.

### ISSUE THREAD

**Issue by mexican1973** [spesmilo/electrum#5166]
Hallo Community.

We have added the change to support the sapling upgrade by ZCash. We are running the network for ZClassic based on the overwinter and sapling upgrade.
There was an erorr on the electrumx server. We changed the deserializer class which was in your tx.py file. Now error doesnt come on server side but on client we get the above mentioned error.

![b62c0e4a-06a3-450f-8d54-28786febbe48](https://user-images.githubusercontent.com/36118413/53566888-d569f880-3b5d-11e9-8aac-2fcfb6bfab13.jpg)

Anyone has had similar issue ?
BR
Heinrich

**Comment by SomberNight** [comment]
This error is coming from the full node behind electrumx; the tx does not conform to some policy/consensus rule. This is specific to your altcoin though, which I am not familiar with; and altcoins are not supported by us in any case.

**Comment by vxix66734** [comment]
I have the similar issue on my Zclassic electrum wallet, same message error "Transaction was rejected by network rules\n\n16: Tx-overwinter active". How to fix this error?

**Comment by mexican1973** [comment]
You have the wrong client downloaded.
You need to get the proper version from the new github.

https://github.com/ZclassicCommunity/electrum-zclassic

There is also a Windows binary.
