### ISSUE TITLE
Bitcoins do not arrive

### ISSUE THREAD

**Issue by RentexHD** [spesmilo/electrum#5170]
Windows: 10
Version: 4.0
Problem:
I bought bitcoins yesterday and sent them to my wallet. After 3 minutes they arrived. Then I tried to load the bitcoins on a website. Before I sent the bitcoins, I have set very low on fees (Goal 25), perhaps because it will take some time until the bitcoins are loaded on my website? The bitcoins are still not there even after 24 hours and I have no message coming. Will the bitcoins still arrive?

**Comment by SomberNight** [comment]
There is no version 4.0.
https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES
https://electrum.org/#download

I am afraid you probably downloaded malware.

**Comment by SomberNight** [comment]
Where did you download Electrum from? Look for the link in your browser history / downloads tab.
