### ISSUE TITLE
Coldcard problems [Linux]

### ISSUE THREAD

**Issue by Chrozayis** [spesmilo/electrum#5174]
Electrum doesn't detect Coldcard running as a normal user, and there doesn't seem to be a plugin for it in the plugin toggles menu.

I got it to find my Coldcard and create a wallet with sudo.
However it did not detect my previous test transaction sent to an address generated by the Coldcard.

I then reran `sudo electrum` and when I click 'next' to unlock my wallet with Coldcard I get this error:
`choose_hw_device() takes from 1 to 2 positional arguments but 3 were given`
I get the error regardless of whether the Coldcard is plugged in and unlocked or not.

**Comment by SomberNight** [comment]
> Electrum doesn't detect Coldcard running as a normal user

Do you have udev rules set? See https://github.com/spesmilo/electrum-docs/blob/master/hardware-linux.rst

> there doesn't seem to be a plugin for it in the plugin toggles menu

Yes, that's expected, hw wallet plugins are handled automatically/separately.

> when I click 'next' to unlock my wallet with Coldcard I get this error:
choose_hw_device() takes from 1 to 2 positional arguments but 3 were given

Can you running Electrum with `-v` to see logs?

**Comment by Chrozayis** [comment]
Thanklls for the link to that, I found a vague reference to udev in my digging, but never found out more. Ideally this would be added to Coldcard's getting started documentation and maybe a warning within Electrum if possible.

Addign the udev rule fixes adding a Coldcard as a regular user but did not fix opening the wallet using Coldcard.

Traceback running as root with Coldcard disconnected
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/electrum/gui/qt/installwizard.py", line 273, in select_storage
    self.run('choose_hw_device', HWD_SETUP_DECRYPT_WALLET, self.temp_storage)
  File "/usr/lib/python3.7/site-packages/electrum/base_wizard.py", line 98, in run
    f(*args)
TypeError: choose_hw_device() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/electrum/daemon.py", line 340, in init_gui
    self.gui.main()
  File "/usr/lib/python3.7/site-packages/electrum/gui/qt/__init__.py", line 318, in main
    if not self.start_new_window(path, self.config.get('url'), app_is_starting=True):
  File "/usr/lib/python3.7/site-packages/electrum/gui/qt/__init__.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/electrum/gui/qt/__init__.py", line 234, in start_new_window
    path, storage = wizard.select_storage(path, self.daemon.get_wallet)
TypeError: cannot unpack non-iterable NoneType object
```

Running as a regular user I got a popup error 
```
Traceback
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/electrum/gui/qt/__init__.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/electrum/gui/qt/__init__.py", line 234, in start_new_window
    path, storage = wizard.select_storage(path, self.daemon.get_wallet)
TypeError: cannot unpack non-iterable NoneType object
 
Additional information
Electrum version: 3.3.4 
Python version: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127] 
Operating system: Linux-4.19.24-1-MANJARO-x86_64-with-arch-Manjaro-Linux 
Wallet type: standard 
Locale: en_CA
```

My original test transaction still didn't show up, and my second test transaction sent this morning is also not appearing despite being confirmed. (2nd test is also not appearing in Sentinel, so maybe I screwed something up).

**Comment by SomberNight** [comment]
Oh I see, you are on master. I fixed some regressions, please pull again and test now.

**Comment by Chrozayis** [comment]
I can now decrypt the wallet I created.
The test transactions to 1... format addresses are still not displaying, or will that take a while to load?
Also my Coldcard's caution light is now permanently lit and I'm not sure why.

**Comment by SomberNight** [comment]
> Also my Coldcard's caution light is now permanently lit and I'm not sure why.

When did that start? For me it was during a firmware upgrade (and I resolved it via "bless firmware": https://coldcardwallet.com/docs/upgrade).

> The test transactions to 1... format addresses are still not displaying

Check in the `Addresses` tab that the expected addresses for the test txns are there.

**Comment by Chrozayis** [comment]
I redid the latest firmware upgrade, logged in, out and in again, and now the light in green again. I'd assume it started while I was playing with Electrum, but it could conceivably have been after a recent firmware upgrade and I didn't notice.

The Addresses tab only shows bc1... format addresses

**Comment by SomberNight** [comment]
> The Addresses tab only shows bc1... format addresses

Well if you want `1...` addresses then select p2pkh in the script type and derivation screen during wallet file creation.

**Comment by Chrozayis** [comment]
Found a weird issue. Attempting to decrypt with the Coldcard connected, but locked results in a helpful error. But then if I unlock the Coldcard and click Next twice I get `'NoneType' object has no attribute 'decrypt'`

**Comment by Chrozayis** [comment]
Another potential issue. Trying to create a new wallet for a hardware device while that hardware device is already interacting with a wallet results in no hardware devices being detected

**Comment by Chrozayis** [comment]
Neither of the addresses I sent to for testing are showing up in the Addresses tab

**Comment by SomberNight** [comment]
> Neither of the addresses I sent to for testing are showing up in the Addresses tab

Well how did you get those addresses in the first place?

Re the issues wizard issues, you could go back to 3.3.4 for now; that's more stable; will try to fix them a bit later.

**Comment by Chrozayis** [comment]
I got the first address from the public info dump from Coldcard to SD under the `## For Electrum (not BIP44):` heading (I used `m/0/4`)
I can verify that this address works since I imported the xpub to Sentinel.
The second testing address I got using `ckcc addr` with no options. This one is not showing in Sentinel.

**Comment by SomberNight** [comment]
Well you can specify a derivation path on the script type and derivation screen during wallet creation.

**Comment by Chrozayis** [comment]
I've just spent some time playing with it. No luck.

**Comment by SomberNight** [comment]
Maybe try `m/`.

**Comment by Chrozayis** [comment]
That works thanks!
At least for the first test transaction, the second (Generated with ckcc addr) is still missing but given that Sentinel is also having issues this might not be an Electrum issue, I don't have the low level knowledge to be sure.
