### ISSUE TITLE
Website should mention that there is no Electrum 4.0

### ISSUE THREAD

**Issue by danuker** [spesmilo/electrum#5178]
The warning on the official website says "Versions of Electrum older than 3.3.3 are vulnerable".

However, a typical user won't imagine that their version 4.0 is bad, and won't update, even if they see this message.

**Comment by ecdsa** [comment]
there will be a version 4.0 soon

**Comment by danuker** [comment]
Well, then I think it should say "There is also malware claiming to be Electrum 4.0".

This is somewhat of a rat race (Electrum vs malware); but the malware would need to update as well to show a version greater than 4.0.

**Comment by danuker** [comment]
Perhaps Electrum should update straight to 4.0.1 :)

**Comment by ecdsa** [comment]
following your logic, perhaps the website should enumerate all the version numbers for which there is no Electrum?
