### ISSUE TITLE
Electrum 3.3.4 can not create window for wallet

### ISSUE THREAD

**Issue by fsc911** [spesmilo/electrum#5179]
After installation of version 3.3.4 on OS 10.13.6 I have no chance to open my existing wallet. There is always the following message: '**Cannot create window for wallet: (Errno 1) Operation not permitted: '/users/CS/.electrum/config'**

When I try to "restore from seed" there is always the same message! Any Idea what I can do?
Please give me some advice....thank you!

**Comment by ecdsa** [comment]
remove the config file, or check tat you have permissions to write it

**Comment by fsc911** [comment]
this is the solution! It works....many thanks!!!!!
