### ISSUE TITLE
Electrum continually connecting to servers which refuse to broadcast transactions

### ISSUE THREAD

**Issue by CodeForcer** [spesmilo/electrum#5182]
I'm using Electrum on command line and I'm having continuous problems connecting to servers which will actually broadcast transactions or report that they are broadcast.

I'm using Electrum for commercial purposes with an automated transaction queue and so after every transaction we check to see if it has been successful, otherwise we stop the queue for manual intervention.

But lately we've noticed a trend of either the server reports 'False' in the return but broadcasts the transaction anyway, or it refuses to broadcast the transaction and returns something like:

`
[False, 'error: {\'code\': 1, \'message\': \'<b>Transaction error.</b><h2 style="white-space:nowrap;">Required Security Update (v4.0.0)</h2><p>This important security update provides a fix for transaction deserialization vulnerability and is mandatory for all users.</p><p>Transactions can only be sent after applying this update. We sincerely apologize for any inconvenience this has caused you.</p><h3 style="text-align: center;background-color:#1c8bd0;color:#ffffff;"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMF...
`

I get that this is a phishing attack, but it's also causing massive inconvenience that we can no longer trust the output after broadcasting a transaction.

Is there anyway something can be patched to deter these malicious servers? Or at the very least prevent a transaction from being incorrectly reported as unbroadcast?

**Comment by ecdsa** [comment]
first, upgrade Electrum
second, remove your config file; it remembers connections to phising servers.
current servers blacklist the servers that perform this attack

**Comment by SomberNight** [comment]
> I'm using Electrum for commercial purposes

You should at least consider setting up your own (potentially private) Electrum server.

> second, remove your config file; it remembers connections to phising servers.

more importantly, also the `recent_servers` file

**Comment by CodeForcer** [comment]
Thank you for the prompt response. Upgrading and deleting configs and recent_servers seems to have resolved the issue.
