### ISSUE TITLE
Error when running Electrum-3.3.4

### ISSUE THREAD

**Issue by zwykx** [spesmilo/electrum#5186]
After installing the last official version from https://electrum.org/#download and running electrum, I get an error message :
```
$ python3 Electrum-3.3.4/run_electrum
  File "Electrum-3.3.4/run_electrum", line 53
    sys.exit(f"Error: {str(e)}. Try 'sudo python3 -m pip install <module-name>'")
                                                                                                                       ^
SyntaxError: invalid syntax
```

Yet I use exactly the command line indicated in "Run without installing" !

**Comment by SomberNight** [comment]
Your python version is too old. You need at least 3.6.1
See e.g. https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#electrum-requires-recent-python-my-linux-distribution-does-not-yet-have-it-what-now
