### ISSUE TITLE
Connecting to servers via Tor (onion addresses) fails

### ISSUE THREAD

**Issue by iceTwy** [spesmilo/electrum#519]
Connecting to servers via Tor's SOCKS5 proxy (onion addresses) fails with Electrum 1.9.6.

I've been trying to use Tor and it simply won't work with Electrum 1.9.6, when it used to work witth previous versions. Other applications I proxy through Tor work just fine, too.                                                                                           

I also received a mail from an user who struggled to use Tor (on Windows 7, Electrum 1.9.6) and eventually didn't manage to.

I haven't tried to use the mapaddress directive in torrc, simply because I could connect to onion addresses with no hassle on Electrum 1.9.4/1.9.5.

**Comment by ecdsa** [comment]
this work in 2.0 versions
