### ISSUE TITLE
phishing attack

### ISSUE THREAD

**Issue by poministerski** [spesmilo/electrum#5190]
Dear sirs, 

I've been a subject of phishing attack. 
Here is a transaction confirmation: 6c22b671b39859795407ffb8fb997bdff4e937b26d869be8356f9a24a5a52db1

Could my money be somehow be back?
And how can I download an Electrum one more time on Mac? It is not opening anymore.

**Comment by Boutag** [comment]
Hello @poministerski,
I had the same problem, and when sending 0.0005 BTC it sent all amount of my Wallets to somewhere, i still do not know where the money went because there is no final Bitcoin Adress but the operation was confirmed at the blockchain and my Bitcoin Adresses are all empty !!! i do not know if there is a way to get back the money :-(.
if you are using the Version 4.0.0 of Electrum you risk to lost all the amount of your wallet, so i suggest you to uninstall it and to get the Version 3.3.4 from the offical website https://electrum.org and do not go to other website, that is what i did and untill now it is ok.
Be carefull please and good luck.

**Comment by Boutag** [comment]
@poministerski, take a look at these other issues : 
- Electrum 4.0.0 : Serious Error !!! #5183
- Sending Max bitcoins automatically unintentionally #5187

**Comment by ecdsa** [comment]
@poministerski what makes you believe you have been a victim of phishing?
Did you download an Electrum upgrade from another source than electrum.org?

**Comment by poministerski** [comment]
Actually, I couldnt make a transaction from my official Electrum wallet till I updated it. It simply didnt allow me to make a transaction so I had to download it from the link as I was instructed.12.03.2019, 11:05, "ThomasV" <notifications@github.com>:@poministerski what makes you believe you have been a victim of phishing?
Did you download an Electrum upgrade from another source than electrum.org?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

-- Kind regards,Maria Korobeinikova PR ManagerDROFA Communications Agencywww.drofa-ra.com/en+79261984036Skype: +7 926 198-40-36

**Comment by sunnysider** [comment]
In my case too.. I couldnt make a transaction from my Electrum wallet. It poped up a window with the advise i have to update. just like poministerski said.
so i instaled 4.0 and did my order, as soon as i hit the send button it immediatly send all btc on the wallet to an unknown adress without asking a password:
Transaction ID:
bc012105c3766fe015ff945aa3213442d6e41c95cf50787c803c2677f4979cf2
the adress it went to: 
bc1qcla39fm0q8ka8th8ttpq0yxla30r430m4hgu3x

**Comment by poministerski** [comment]
Is there any way I can solve my problem and get my money back? 13.03.2019, 18:40, "sunnysider" <notifications@github.com>:In my case too.. I couldnt make a transaction from my Electrum wallet. It poped up a window with the advise i have to update. just like poministerski said.so i instaled 4.0 and did my order, as soon as i hit the send button it immediatly send all btc on the wallet to an unknown adress without asking a password:Transaction ID:bc012105c3766fe015ff945aa3213442d6e41c95cf50787c803c2677f4979cf2the adress it went to:bc1qcla39fm0q8ka8th8ttpq0yxla30r430m4hgu3x—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.  -- Kind regards,Maria Korobeinikova PR ManagerDROFA Communications Agencywww.drofa-ra.com/en+79261984036Skype: +7 926 198-40-36

**Comment by ecdsa** [comment]
@poministerski sorry but no, your money has been stolen.
What you can do is post here the website from where you downloaded the malware, so that we can report it as phishing, if it has not been reported already.

**Comment by poministerski** [comment]
I am really confused with the fact that the users of the best crypto wallet are not safe. 15.03.2019, 13:41, "ThomasV" <notifications@github.com>:@poministerski sorry but no, your money has been stolen.What you can do is post here the website from where you downloaded the malware, so that we can report it as phishing, if it has not been reported already.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.  -- Kind regards,Maria Korobeinikova PR ManagerDROFA Communications Agencywww.drofa-ra.com/en+79261984036Skype: +7 926 198-40-36
