### ISSUE TITLE
Electrum 3.3.4 is not recognizing trezor on ubuntu 16.04

### ISSUE THREAD

**Issue by adyshimony** [spesmilo/electrum#5191]
Hi,

I can't make electrum to recognize  trezor. 
Tried with 2 trezors, different cables, different usbs.

Checking with trezorctl list:

```
hid:0004:0006:00
bridge:lib02

```
Checking with lsusb:
`Bus 004 Device 006: ID 534c:0001 SatoshiLabs Bitcoin Wallet [TREZOR]
`
Chrome is recognizing both devices.

Electrum gives the error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/electrum/base_wizard.py", line 283, in choose_hw_device
    include_failing_clients=True)
  File "/usr/local/lib/python3.6/dist-packages/electrum/plugin.py", line 510, in unpaired_device_infos
    raise Exception(message)
Exception: Missing libraries for trezor.
Make sure you install it with python3
[DeviceMgr] error getting device infos for trezor: Missing libraries for trezor.
Make sure you install it with python3
[n] stopping network
[n] couldn't launch iface 127.0.0.1:50002:s -- CancelledError()
```

I went through all the issues with trezor, reinstalled all.
Checking with pip3 list:

`trezor                        0.11.2     
`
Thanks,
Ady.

**Comment by SomberNight** [comment]
`python3.6 -m pip install --user trezor`

**Comment by adyshimony** [comment]
> `python3.6 -m pip install --user trezor[hidapi]`
> 
> ( related https://github.com/spesmilo/electrum-docs/blob/master/hardware-linux.rst )

Done. (had to do -  "sudo apt-get install python3.6-dev" to make it work.)

Still not working from electrum.

**Comment by adyshimony** [comment]
Ok, doing this helped:

Update this file

 /etc/udev/rules.d/51-trezor.rules

To like here:
https://github.com/trezor/trezor-common/blob/master/udev/51-trezor.rules

Works!

Thanks.
