### ISSUE TITLE
Fee calculation seems to be incorrect

### ISSUE THREAD

**Issue by pinheadmz** [spesmilo/electrum#5194]
Version 3.3.4

### expected

Outgoing tx, 1-in (segwit) 2-out (one legacy, one segwit):
<img width="264" alt="Screen Shot 2019-03-13 at 12 32 07 PM" src="https://user-images.githubusercontent.com/2084648/54308819-0863b180-458c-11e9-9550-59318645cbcc.png">

This looks correct, `3514 sats / 144 bytes = 24`

### unexpected

Outgoing tx, 1-in, 2-out (all segwit):
<img width="244" alt="Screen Shot 2019-03-13 at 12 32 37 PM" src="https://user-images.githubusercontent.com/2084648/54308840-19acbe00-458c-11e9-8b0d-6726ed87f2a3.png">

This one looks wrong, and in fact, is buried in the mempool right now waiting confirmation :-)

`344 sats / 141 bytes = 2.4`

I'm not sure if `size` reported in the UI is absolute bytes or "weight". Either way, there is either bad math or lack of consistency between these two transactions.

**Comment by SomberNight** [comment]
Recheck the decimal place please. There's nothing wrong here. The feerate is round to 1 fractional decimal. Trailing zeroes are cut off from numbers unless you explicitly change that in your preferences.

**Comment by pinheadmz** [comment]
ack. sorry hard to tell 7 numbers in a row from 8 😬. I'll close but perhaps this could be a UI improvement. Just report fees in absolute satoshis as an int?

**Comment by SomberNight** [comment]
np. I think being consistent in using the same units everywhere also has its advantages.

At one point I was thinking about using some kind of "programmer notation", e.g. 41_012.000_035_14 (which is a valid literal in many programming languages), but I was told by multiple people that that would not be user-friendly :D
