### ISSUE TITLE
P2SH compatibility option to encourage use of wallet in Segwit Mode

### ISSUE THREAD

**Issue by shivaenigma** [spesmilo/electrum#5196]
### Motivation
- Bech32 adoption is low [at 1%](https://p2sh.info/dashboard/db/bech32-statistics?orgId=1&from=1512149694276&to=now) even after an year
- Merchant have major volumes, however backward compatibility must be [retained for them](https://github.com/spesmilo/electrum/issues/4736#issuecomment-468943550) 

### Summary 
- Advanced option to enable P2SH address generation in Segwit wallet mode. Can be something like _change_gap_limit_ parameter
- Both bech32 / p2sh segwit addresses are discovered by wallet and shown in receive tab
- Change addresses are default bech32
- Receive QR codes can be shown in [mixed format](https://github.com/spesmilo/electrum/issues/4736)

### Advantages
- Merchants can use _zpub_ to accept payments on website without worrying about breaking compatibility. 
- New users can choose Segwit Wallet without hesitation and get additional fee savings due to bech32 change addresses
- Easy to manage all transactions in one wallet instead of creating different wallets for segwit/legacy

**Comment by ecdsa** [comment]
segwit-in-p2sh should actually be discouraged, not encouraged.

**Comment by shivaenigma** [comment]
![Screenshot from 2019-03-25 18-00-47](https://user-images.githubusercontent.com/737092/54920001-246e3800-4f28-11e9-86c0-5de3ea21cb88.png)

When is this transition period over ? When all known wallets support sending to bech32 ? This will never be 100% and  a non compatible  wallet userbase remains

If we don't provide a staircase for the transition, we are actually further discouraging it.  Idealistically everyone will start using only bech32 address but people are much more likely to go to legacy than to bech32 when they find addresses on their e-commerce store aren't being read by a customer's wallet.

**Comment by shivaenigma** [comment]
Referring to related issue #3460

**Comment by SomberNight** [comment]
Closing this in favour of https://github.com/spesmilo/electrum/issues/6016
