### ISSUE TITLE
Wallet won't synch do I need to update my wallet?

### ISSUE THREAD

**Issue by Pinhooo** [spesmilo/electrum#5197]
I was reading up that electrum has put in place a DOS to stop phishing attacks from the old wallets. I can't connect to any servers at all? Would I need to update my tails? Also If I download the new version then recover my electrum is there any precautions I should take so I don't lose my $300 balance on my wallet? Also how would I update safely on tails. Just to say this now I really appreciate this forum as you have helped us a lot in the past!

Thank you :)

**Comment by bauerj** [comment]
Hey, 

please follow these steps to update: https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#electrum-requires-recent-python-my-linux-distribution-does-not-yet-have-it-what-now

Make sure that you have your seed stored in a safe place, no other precautions are necessary.

**Comment by SomberNight** [comment]
Closing this in favour of https://github.com/spesmilo/electrum/issues/5195
Also pinned that for visibility.
