### ISSUE TITLE
USD balance column sorted as text, not as number

### ISSUE THREAD

**Issue by uFire** [spesmilo/electrum#5198]
Found a small interface bug. USD balance column in the Addresses tab sorted as text instead of being sorted as a number. I suspect there might be similar sorting bugs with other columns.

Electrum 3.3.4
Windows 10

UPD: BTW, if I remember correct, this issue appeared after I switched to CoinDesk as exchange rate provider, so it is possible that CoinDesk provides it as text and BitcoinAverage have been providing it as number, so it seems like there is no check for data type in Electrum's code. I could be mistaken, this is just a guess.

![lectrum_sorting](https://user-images.githubusercontent.com/19604379/54466823-58a86280-478a-11e9-9f08-881204239511.JPG)

**Comment by SomberNight** [comment]
Thanks for the report. This is a known issue, see https://github.com/spesmilo/electrum/issues/4920
