### ISSUE TITLE
GPG public key link redirecting to unrelated site

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#5200]
This was [reported](https://bitcointalk.org/index.php?topic=5121057.0) on the forum. The link to keys dot gnupg dot net on the [download page](https://electrum.org/#download) is redirecting to some private equity firm. This is the link at the top labeled "ThomasV". I suggest replacing it with the link to github as was done at the bottom of the page.

Also it wouldn't hurt to decouple animazing's public key from thomas's.

**Comment by SomberNight** [comment]
> The link to keys dot gnupg dot net on the download page is redirecting to some private equity firm.

It seems one of the IPs returned by DNS is to blame. Hence, for sometimes it works as expected, other times it "redirects".

We could switch to:
https://pgp.surfnet.nl/pks/lookup?op=vindex&search=0x6694D8DE7BE8EE5631BED9502BD5824B7F9470E6
Or just link it from the repo, but then I think it's a good idea to also mention the fingerprint on the site.

> Also it wouldn't hurt to decouple animazing's public key from thomas's.

Ahh, you're right. It seems in the [ThomasV.asc](https://github.com/spesmilo/electrum/blob/master/pubkeys/ThomasV.asc) file repo also includes that key...

**Comment by ecdsa** [comment]
I replaced it with a link to github

**Comment by SomberNight** [comment]
> Also it wouldn't hurt to decouple animazing's public key from thomas's.

Done in https://github.com/spesmilo/electrum/commit/ec6f4e9f1cafbeb3cd16cb053183f1dc654632b9
