### ISSUE TITLE
3.3.4. Electrum Client stuck in synchronize

### ISSUE THREAD

**Issue by Pinhooo** [spesmilo/electrum#5206]
I have just downloaded the latest version from electrum.org. I have created a new key from scratch to experiment. I have tried to connect to various servers with the orb remaining red. I had been sent a list of non-blacklisted servers for electrum through another reliable source and non seem to connect to those either. I had tried reinstalling the software and to no avail cannot use the new Electrum? I just want to get electrum working so I can recover my original seed but is proving not as simple as what it used to be. Any help would be greatly appreciated. Shall I wait for the tails update on tuesday is tails including 3.3.4 in their update?

**Comment by SomberNight** [comment]
What OS? Is this on Tails?
Run electrum with the `-v` flag to get logs, and paste them here.

**Comment by Pinhooo** [comment]
This is in MACos mate

**Comment by SomberNight** [comment]
Run electrum with the `-v` flag to get logs, and paste them here.

**Comment by ecdsa** [comment]
closing, no answer
