### ISSUE TITLE
did not receive a transaction sent from my Coinbase wallet

### ISSUE THREAD

**Issue by HH1008** [spesmilo/electrum#5214]
I have used electrum to send and receive bitcoin for over 20 transactions. I sent my largest amount of bitcoin yet from Coinbase to my Electrum wallet yesterday and my balance still shows it has not arrived. I contacted Coinbase and they said the funds had left their wallet according to blockchain.

Please help! It's a lot of money for me thank you.

13YwrQReCDrWfzbVQax3gbTgrwvwGzHFB3   this is my electrum address I was trying to send to from coinbase

**Comment by SomberNight** [comment]
What version of Electrum do you have?
Please update to latest.

**Comment by HH1008** [comment]
I have updated to the latest version after I wasn't receiving the transaction and still have not seen in come in. thank you for your help

**Comment by HH1008** [comment]
It was Bitcoin Cash does electrum accept that?

**Comment by HH1008** [comment]
I accidentally sent BCH to my electrum wallet instead of BTC is there anyway to retrieve it? thank you

**Comment by HH1008** [comment]
I sent BCH instead of BTC anyway to retrieve it? thanks for your help

**Comment by SomberNight** [comment]
Electrum only supports bitcoin.
There is a fork of Electrum for BCH, but it's **not maintained by us**: [Electron Cash](https://github.com/Electron-Cash/Electron-Cash)

You can download that, and restore from your electrum seed words. It should find the BCH and you should be able to spend it. Note that this obviously exposes your electrum seed words to that software, so you trust that software with it.

_If you want to be cautious, you should create a new electrum seed, transfer your bitcoins to that using Electrum, and only then enter your old seed words into electron cash to find the BCH. Ideally you would even do this on a separate computer._
