### ISSUE TITLE
JSONRPC result differs from console command result

### ISSUE THREAD

**Issue by manuelsteiner** [spesmilo/electrum#5217]
Hi,

I have an issue with JSONRPC calls. The output seems to be different compared to the command executed via console. I am trying to get unspent transactions with listunspent.

The Electrum version is 3.3.4 run in daemon mode.
The RPC calls where performed via curl and authentication.

Initially the console output showed 52 entries for listunspent where the same RPC call only showed 42. Ok I though maybe there is a limit to how many results are returned. So I spent all funds.
The result was as expected 0 entries for listunspent in the console. Hoewever, the RPC call still shows the same old 43 entries from before.

I also tried the getbalance call out of curiosity. The balance was the same for console and RPC before spending the funds. After that, the console command returned the correct result but the RPC call like before still returned the old balance.

So I am not sure if there is any caching going on or if there is a bug somewhere. I am not sure how to get the RPC call to return correct results.

Any help is appreciated. Thank you.

**Comment by SomberNight** [comment]
Can you paste the commands you are running, for CLI and for JSONRPC? Are you sure they are running against the same wallet btw?

**Comment by manuelsteiner** [comment]
Hi,

I am very sorry foir opening this issue probably a bit too soon. Now that Electrum has received enough confirmations for the sending transaction both the getbalance and listunspent calls via RPC work as expected and show the same results as the CLI commands.

I wrongly was under the impression that a lower number of confirmations would be sufficient.

Thanks for the help.
