### ISSUE TITLE
I am dying

### ISSUE THREAD

**Issue by bitzicoin** [spesmilo/electrum#5219]
I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  1FcvMGQN9c5aE1o3WQnFqhUN9ShQssNoYd

**Comment by SomberNight** [comment]
This is not the place to keep pasting this. It was not the place 2 months ago. It was not the place 1 month ago. And it is still not the place. You have not even changed the bitcoin address.
