### ISSUE TITLE
can not send bitcoin

### ISSUE THREAD

**Issue by drivert12** [spesmilo/electrum#5221]
hello, I have latest version of electrum but I can not send bitcoin. 
![1](https://user-images.githubusercontent.com/48926425/54946360-f8af7a00-4f48-11e9-9d23-991b502c602f.jpg)
![1](https://user-images.githubusercontent.com/48926425/54946365-fc430100-4f48-11e9-8d22-c11d7a58e370.jpg)

**Comment by SomberNight** [comment]
Could you please provide more context/details?

- Which version of Electrum are you using? ("latest", ok, but please name it specifically)
- What OS is this? Windows? Which version?
- When exactly do you get this error?
- What colour is the orb/circle in the bottom right?
- What kind of wallet do you have? If you go to `Wallet`>`Information`, what is `Wallet type`?

**Comment by drivert12** [comment]
I tried to send it from electrum 3.3.4 full and portable version
I used Windows 10 and Mac OS high sierra
after 2fa I recived such message
![2](https://user-images.githubusercontent.com/48926425/54947147-aff8c080-4f4a-11e9-9c7b-ed62fad8271d.jpg)

**Comment by SomberNight** [comment]
I think you might not be able to connect to the 2FA (TrustedCoin server).
Please try with a Tor proxy.

Download Tor Browser, and start it.
In Electrum, click on the coloured orb in the bottom right, then go to the `Proxy` tab, and then check `Use Tor proxy at port ...`

**Comment by drivert12** [comment]
I tried to do it from tor proxy but have the same error
![3](https://user-images.githubusercontent.com/48926425/54948729-6a3df700-4f4e-11e9-996d-61594048c67b.jpg)

**Comment by SomberNight** [comment]
What colour is the orb in the bottom right when you try with a Tor proxy?

**Comment by drivert12** [comment]
blue

**Comment by drivert12** [comment]
![4](https://user-images.githubusercontent.com/48926425/54948974-fea85980-4f4e-11e9-8e9f-f62a5c5a66de.jpg)

**Comment by SomberNight** [comment]
Try clicking the shield icon in the bottom right. What happens?

**Comment by drivert12** [comment]
![5](https://user-images.githubusercontent.com/48926425/54949194-91e18f00-4f4f-11e9-80cf-319f34439642.jpg)

**Comment by SomberNight** [comment]
> I used Windows 10 and Mac OS high sierra

Could you test on MacOS, and check the logs? It's easier to see logs on Mac than on Windows.

Start Electrum with the `-v` flag, from terminal; so e.g. run something like this:
`/Applications/Electrum.app/Contents/MacOS/Electrum -v`
Try to reproduce the error again, and then copy-paste the logs here.

**Comment by drivert12** [comment]
Traceback (most recent call last):
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/qt.py", line 71, in prompt_user_for_otp
    wallet.on_otp(tx, auth_code)
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/trustedcoin.py", line 324, in on_otp
    r = server.sign(short_id, raw_tx, otp)
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/trustedcoin.py", line 212, in sign
    return self.send_request('post', 'cosigner/%s/sign' % quote(id), payload)
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/trustedcoin.py", line 153, in send_request
    raise ErrorConnectingServer(e)
electrum.plugins.trustedcoin.trustedcoin.ErrorConnectingServer
[n] network: retrying connections
[n] fee_histogram [[30, 109041], [23, 121557], [12, 106888], [9, 273809], [8, 521987], [7, 558143], [6, 442646], [5, 293449], [4, 276050], [3, 287936], [2, 346704], [1, 1643144]]
[n] fee_estimates {25: 1083, 10: 5975, 5: 14196, 2: 23296}
[CoinChooserPrivacy] Bucket sets: 2
[CoinChooserPrivacy] Winning penalty: 0.8524295568143953
[CoinChooserPrivacy] change: [TxOutput(type=0, address='3LeAdzS66TmHDiepVvpojtr9TJ6ZcoeCH9', value=4350881)]
[CoinChooserPrivacy] using 207 inputs
[CoinChooserPrivacy] using buckets: ['3NP4Hh3R9jWgqEzm9SoACnqbyKBx4dPruJ']
[CoinChooserPrivacy] Bucket sets: 2
[CoinChooserPrivacy] Winning penalty: 0.8524295568143953
[CoinChooserPrivacy] change: [TxOutput(type=0, address='3LeAdzS66TmHDiepVvpojtr9TJ6ZcoeCH9', value=4350881)]
[CoinChooserPrivacy] using 207 inputs

**Comment by SomberNight** [comment]
Ok, so this looks to be what I had originally said: you cannot connect to the 2FA server for some reason.

Can you try with Tor proxy and copy-paste logs again?

-------- Original Message --------

**Comment by drivert12** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/qt.py", line 71, in prompt_user_for_otp
    wallet.on_otp(tx, auth_code)
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/trustedcoin.py", line 324, in on_otp
    r = server.sign(short_id, raw_tx, otp)
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/trustedcoin.py", line 212, in sign
    return self.send_request('post', 'cosigner/%s/sign' % quote(id), payload)
  File "/var/folders/ph/4n811_2j1n335nff_vf3lrr40000gn/T/_MEI2SLw7m/electrum/plugins/trustedcoin/trustedcoin.py", line 153, in send_request
    raise ErrorConnectingServer(e)
electrum.plugins.trustedcoin.trustedcoin.ErrorConnectingServer
[n] fee_histogram [[39, 103741], [35, 113171], [30, 139412], [25, 137389], [24, 125867], [23, 169123], [13, 162015], [9, 351199], [8, 667433], [7, 586741], [6, 474681], [5, 300327], [4, 279966], [3, 291477], [2, 351271], [1, 1657926]]
[n] fee_estimates {25: 1083, 10: 5975, 5: 14196, 2: 23296}
[CoinChooserPrivacy] Bucket sets: 2
[CoinChooserPrivacy] Winning penalty: 0.8524295568143953
[CoinChooserPrivacy] change: [TxOutput(type=0, address='3LeAdzS66TmHDiepVvpojtr9TJ6ZcoeCH9', value=4350881)]
[CoinChooserPrivacy] using 207 inputs
[CoinChooserPrivacy] using buckets: ['3NP4Hh3R9jWgqEzm9SoACnqbyKBx4dPruJ']
[CoinChooserPrivacy] Bucket sets: 2
[CoinChooserPrivacy] Winning penalty: 0.8524295568143953
[CoinChooserPrivacy] change: [TxOutput(type=0, address='3LeAdzS66TmHDiepVvpojtr9TJ6ZcoeCH9', value=4350881)]
[CoinChooserPrivacy] using 207 inputs
[CoinChooserPrivacy] using buckets: ['3NP4Hh3R9jWgqEzm9SoACnqbyKBx4dPruJ']
[i][e-1.claudioboxx.com] disconnecting due to: SOCKSFailure('general SOCKS server failure',)
[i][electrum.coinucopia.io] could connect 568777
[HistoryModel] refreshing... reason: update_tabs
[profiler] Abstract_Wallet.get_full_history 0.0268
[profiler] HistoryModel.refresh 0.1615
[i][electrum.eff.ro] skipping header 568777
[n] network: retrying connections
[i][electrum.qtornado.com] skipping header 568777
[i][fullnode.coinkite.com] skipping header 568777
[i][anthroponomy.eLECtRumioUS.COM] skipping header 568777
[i][sekane.eLECtRumioUS.COM] skipping header 568777
[i][frightless.ELECtRuMiLY.cOm] skipping header 568777
[BitcoinAverage] getting fx quotes for USD
[i][hsmiths5mjk6uijs.onion] skipping header 568777
[BitcoinAverage] received fx quotes
[HistoryModel] refreshing... reason: fx_quotes
[profiler] Abstract_Wallet.get_full_history 0.0274
[profiler] HistoryModel.refresh 0.1612
[CoinChooserPrivacy] Bucket sets: 2
[CoinChooserPrivacy] Winning penalty: 0.8524295568143953
[CoinChooserPrivacy] change: [TxOutput(type=0, address='3LeAdzS66TmHDiepVvpojtr9TJ6ZcoeCH9', value=4350881)]
[CoinChooserPrivacy] using 207 inputs
[CoinChooserPrivacy] using buckets: ['3NP4Hh3R9jWgqEzm9SoACnqbyKBx4dPruJ']
[n] fee_histogram [[39, 103741], [35, 113171], [30, 139412], [25, 137389], [24, 125867], [23, 169123], [13, 162015], [9, 351199], [8, 667433], [7, 586741], [6, 474681], [5, 300327], [4, 279966], [3, 291477], [2, 351271], [1, 1657926]]
[n] fee_estimates {25: 1083, 10: 6944, 5: 14195, 2: 23303}
[CoinChooserPrivacy] Bucket sets: 2
[CoinChooserPrivacy] Winning penalty: 0.8524295568143953
[CoinChooserPrivacy] change: [TxOutput(type=0, address='3LeAdzS66TmHDiepVvpojtr9TJ6ZcoeCH9', value=4350881)]
[CoinChooserPrivacy] using 207 inputs
[CoinChooserPrivacy] using buckets: ['3NP4Hh3R9jWgqEzm9SoACnqbyKBx4dPruJ']
[CoinChooserPrivacy] Bucket sets: 2
[CoinChooserPrivacy] Winning penalty: 0.8524295568143953
[CoinChooserPrivacy] change: [TxOutput(type=0, address='3LeAdzS66TmHDiepVvpojtr9TJ6ZcoeCH9', value=4350881)]
[CoinChooserPrivacy] using 207 inputs
[CoinChooserPrivacy] using buckets: ['3NP4Hh3R9jWgqEzm9SoACnqbyKBx4dPruJ']
[n] network: retrying connections

**Comment by SomberNight** [comment]
If you click 'Preview' on the Send screen, how many inputs and outputs are there?

-------- Original Message --------

**Comment by drivert12** [comment]
inputs 207 and outputs 2
I have another electrum wallet and from there I can do transactions

**Comment by drivert12** [comment]
O'k, bye for tomorrow

**Comment by SomberNight** [comment]
Maybe the tx is too large in size (too many inputs). Unhide the `Coins` tab, try selecting e.g. 100 items (coins), and send them to yourself in a tx. Do it again for another 100 coins.
You probably have many very small value coins.

**Comment by drivert12** [comment]
yes. Because it comes from asic miners

**Comment by drivert12** [comment]
thx, I could do a transfer )

**Comment by SomberNight** [comment]
(note: I guess the TrustedCoin server is not using libsecp256k1; it seems a bit slow to sign)
