### ISSUE TITLE
Please blacklist electrum3.hachre.de

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#5224]
hachre came on IRC earlier today and said that hachre.de has been sold to a buyer that paid via bitcoin. The transaction is currently in escrow so he intends to go through with it. However, this puts a question mark on electrum3.hachre.de. It can't be a coincidence that this is happening now what with the phishing messages. This server is [in the default servers.json](https://github.com/spesmilo/electrum/blob/master/electrum/servers.json#L198) file as well. It should be removed and blacklisted. 

Also other server operators in the default list are going to be receiving some unexpected offers for their domains. IDK what can be done about this but it's worth pondering.

**Comment by hachre** [comment]
👍

**Comment by ecdsa** [comment]
@AbdussamadA blacklisting is not useful, because hachre's server is hardcoded.
@hachre is going to cancel the trade
