### ISSUE TITLE
electrum lose after update 

### ISSUE THREAD

**Issue by tomerkg** [spesmilo/electrum#5225]
i had the same problem like many others here , just now .
i opned my old version of electrum 3.0.3 and tried to send my money to my other wallet it sayed i have to upgrade to 3.3.4
so i did .
after the update i got in to my wallet and saw and unkown tracsation that happend on the 5th of january and all my money is gone . today is 27/03/2019 .
how is it possible that they took my money 2 months ago and i only saw it after i updated .
on the old version all my money was there .
now i cant even open the old version of electrum after the update ..
so my money is gone ? what can i do ?

**Comment by ecdsa** [comment]
if the money was stolen on the 5th of january, then you cannot blame the software update for the theft. 
Where did you download the new version from? it might as well be the official version.
Note: on the old version the money "was there" because the old version could not synchronize its history.

**Comment by tomerkg** [comment]
i donwloaded the update from the original website .
i heard about the pishing i made sure it was the original ... before i updated it i had my money and tried to send it and i got a message that says "server didnt answer "
so after a qucik check online i reallized i need to update so i did . 
and as soon as i updated it and opened the wallet i saw that money was gone on january .
how is even it possible . i got the walet on my pc and i didnt open it for at least a year .
.
i read that other people had the same problem .. after the update they got in and saw the money was gone on january on the same date .
what can i do ? nothing ? 
. i tought that the electrum offline was trustable , i will never trust a wallet like this again . 
i guess we can only trust hardware wallet .. 
@ecdsa

**Comment by ecdsa** [comment]
No, other people did not have the same problem. Other people downloaded a fake version of Electrum because of a phishing message, and the malware stole their bitcoins.

There is no evidence you downloaded a fake version of Electrum, and the theft occured long before you upgraded to 3.3.4.

**Comment by SomberNight** [comment]
ahh you've made multiple posts about this... :/ Please answer here instead of https://github.com/spesmilo/electrum/issues/3238#issuecomment-477165287

@tomerkg could you look up the unknown tx in a block explorer (e.g. [blockstream.info](https://blockstream.info/)), and double-check the timestamp?
If the client is modified, it cannot be trusted with even the timestamp.

**Comment by tomerkg** [comment]
thanks for fast reply 
thats the url      https://electrum.org/#download
i checked the timesatmp and its  2019-01-04 23:17:53
Summary
--
Size | 192 (bytes)
Weight | 768
Received Time | 2019-01-04 23:17:53
Lock Time | Block: 557058
Included In Blocks | 557059 ( 2019-01-04 23:46:05 + 28 minutes )
Confirmations | 11971
Visualize | View Tree Chart

thats the transaction id 
a5b249d759272bd5603fb67f2e7ba100dcbad32110fef229d824aa5a9c4d5196

thats the wallet that got the money

17yrKCZH8UCyPbBZTxJZnYi1vF8y4B4xdE

**Comment by ecdsa** [comment]
@tomerkg did your wallet have a password?

**Comment by tomerkg** [comment]
of course
and not an easy one it contains 
numbers letters and dots

**Comment by ecdsa** [comment]
@tomerkg the most likely explanation is that someone has had access to your seed, either on paper or on your computer. The software update you did is what alllows you to see the theft, but it is not the cause of the theft.
