### ISSUE TITLE
pip install desktop integration broken. icon/launcher is copied to incorrect path

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5227]
Split off from https://github.com/spesmilo/electrum/issues/4768

> I found the only was was to use the steps in the README which were:
`pip3 install .[fast]`
>But this still does not add a menu item or icons as far as I can tell so you have to copy the icon manually from archive and then add a menu or shortcut manually.

If I run
```
python3 -m pip install --user Electrum-3.3.4.tar.gz[fast]
```
the `data_files` passed to `setup()` in setup.py has the value:
```
data_files = (
    [('/home/user/.local/share/applications/', ['electrum.desktop']), 
     ('/home/user/.local/share/icons', ['electrum/gui/icons/electrum.png'])]
)
```
but pip/setuptools turns these absolute paths into relative compared to `site-packages`, e.g.
`~/.local/lib/python3.6/site-packages/home/user/.local/share/applications/`,
and that is where the files end up being copied to.
Which in turn, of course, breaks the desktop-integration.

This looks to be this issue: https://github.com/pypa/wheel/issues/92
And for us specifically it "broke" when we started instructing people to use
`python3 -m pip install` instead of `sudo python3 setup.py install`

**Comment by ThomasLandauer** [comment]
Workaround:

```bash
mv ~/.local/lib/python3.6/site-packages/home/<USERNAME>/.local/share/applications/electrum.desktop ~/.local/share/applications/electrum.desktop
mkdir ~/.local/share/icons
mv ~/.local/lib/python3.6/site-packages/home/<USERNAME>/.local/share/icons/electrum.png ~/.local/share/icons/electrum.png
```

**Comment by SomberNight** [comment]
Note: https://github.com/pypa/wheel/issues/92#issuecomment-410664879 says,

> here's a few things I think you have to watch out for when testing your solution:
>
>    - different python versions
>    - wheel vs no-wheel
>    - some distributions handle site-packages differently (for example, compare Arch vs Ubuntu. I think ubuntu uses dist-packages?)

And indeed the bug described here is only present if the `wheel` package is installed.
Without `wheel`, the absolute paths in `data_files` are respected.
