### ISSUE TITLE
Stuck in sync!  

### ISSUE THREAD

**Issue by veadudnalda** [spesmilo/electrum#5229]
Does not display balance. Stuck in sync. What to do???

**Comment by ecdsa** [comment]
upgrade if you are on an old version

**Comment by raindogdance** [comment]
I'm not sure if I'm experiencing the same issue as OP, but I also have troubles getting Electrum (3.3.4) to sync to my own node (with Electrum Personal Server 0.1.6).  

The Electrum wallet alternates between "Synchronizing..." and "not connected" in the GUI, and in the log file of Electrum Personal sever it says `Electrum wallet disconnected`, immediately followed by `Electrum connected from [...]`. Not sure what causes this (Electrum? EPS? My node?), but perhaps this has something to do with OP's issue as well.
