### ISSUE TITLE
Not my transaction

### ISSUE THREAD

**Issue by Emma77777** [spesmilo/electrum#5230]
Hi, I logged in to electrum wallet and I could not make a transaction becouse  there appeared a message : download a new version from site "link". Transaction failed , I tried any times and finally I went to "link" and downloaded new version ,after that I logged in and there was a new transaction with ALL my money, where they went?? How can I get my money back?? I trusted to electrum :(

**Comment by broker10** [comment]
hello everyone for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email

**Comment by broker10** [comment]
hello to all for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email investimentsfinanciaresrl@gmail.com

**Comment by ecdsa** [comment]
you downloaded malware, see the warning on electrum.org
