### ISSUE TITLE
my account does not pass further synchronization

### ISSUE THREAD

**Issue by andrey19907** [spesmilo/electrum#5231]
my account does not pass further synchronization

To me transferred the amount. The account cannot be synchronized. Account: 1D3n9JUpErRDjDLgfcXxckBhCRQVUgT5kx
help

**Comment by hachre** [comment]
if you aren't on 3.3+, go to electrum.org (always do this by manually typing it into the address bar of your browser) and download the latest version

**Comment by ecdsa** [comment]
closing, no answer from OP
