### ISSUE TITLE
Import of p2sh addresses

### ISSUE THREAD

**Issue by reardenlife** [spesmilo/electrum#5233]
I am somewhat confused with p2sh addresses.  If I will generate 1-to-1 multisig p2sh address (https://github.com/bitcoinjs/bitcoinjs-lib/issues/1371), what exactly should I do in electrum to receive the funds sended to such an address?

Since the address prefixed with 3 is a hash of the script and that script can be different due to multiple options (I.e. number of keys required to spend the transaction), how electrum will detect from the private key I am trying to import (prepended with p2sh:, I assume?) what the underlying script is? How it will generate the address from that private key (to detect the arrival of the funds)  given that parameters of the script (I.e. 1-to-1) are not provided?

**Comment by AbdussamadA** [comment]
ATM there is no way to import such an address. At best you can create a watch-only wallet with it.

**Comment by reardenlife** [comment]
@AbdussamadA

Good to know!

Is there any way for me to generate an address prefixed with 3 by using external tool such as bitcoinjs-lib that can be importable at electrum?

**Comment by reardenlife** [comment]
Hey, what about BIP49?  Does electrum support it?

**Comment by AbdussamadA** [comment]
You can restore from a bip39 seed and when you do you will get the option to derive p2sh segwit addresses (Bip49). Alternatively you can generate your own extended private key in that format and restore using that. I wrote a script that [does that](https://github.com/AbdussamadA/electrum-xprv).

**Comment by reardenlife** [comment]
@AbdussamadA

Great!

Now I just would like to understand how to import the keys into electrum: https://github.com/spesmilo/electrum/issues/5234
