### ISSUE TITLE
my electrum is on "synchorinzing" for 1 day

### ISSUE THREAD

**Issue by mohsenew** [spesmilo/electrum#5239]
my electrum 3.3.4 is on "synchorinzing" for 24 hours and more,
we are very receiving btc to our wallets in electrum,
 we are 37000 address and its for our website user,
i use from manualy and automatic server but not work and status is Synchorinzing :( and i cant manage received BTC,
please help to solve this issue.

Thanks

**Comment by shsmith** [comment]
The electrum servers are currently under DOS attack, causing many to fail syncing. Try manually selecting different servers until you find one that turns the orb green.

**Comment by mohsenew** [comment]
> The electrum servers are currently under DOS attack, causing many to fail syncing. Try manually selecting different servers until you find one that turns the orb green.

i try several times , and i very worry for this :(
Are you sure about DDOS attach for Electrum servers ?

**Comment by AbdussamadA** [comment]
to switch servers you have to right click and choose use server on the server tab of tools > network. left clicking doesn't work.

also you need to be running a recent version. update to 3.3.4 if you have anything less than 3.3.

**Comment by SomberNight** [comment]
> Are you sure about DDOS attack for Electrum servers ?

Yes. See e.g. https://github.com/kyuupichan/electrumx/issues/781

> we are 37000 address and its for our website user,

You have 37k addresses in a single wallet, and this is for a commercial use case? Consider running your own private server for this kind of usage.

**Comment by ecdsa** [comment]
closing, no answer
