### ISSUE TITLE
Unconfirmed transaction

### ISSUE THREAD

**Issue by sergijo73** [spesmilo/electrum#5242]
a couple of days ago I had a transaction and it remains unconfirmed till now. I have never experienced that before and each time it never took more then a couple of hours....

**Comment by jhoenicke** [comment]
Fees on bitcoin are high again (about 120 sat/byte for normal priority, 40 sat/byte for overnight, currently still rising).  

If you haven't, you can enable "Replace By Fee" setting in the preferences; this will allow you to increase the fee for future transactions.  For your current transaction you can check if you can increase the fee with child pays for parent (right-click on transaction).

**Comment by SomberNight** [comment]
not much else to say, I assume the tx has already confirmed btw

**Comment by stella4** [comment]
I'm having trouble I sent $10 From my wallet it's showing unconfirmed and the money has being removed but it's has locked down $91 on my wallet making it unspendable
