### ISSUE TITLE
CPFP fee calculation should include parent tx fees

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#5244]
Fees are becoming important so CPFP will likely be used more soon.

Did a CPFP of a heavy transaction earlier today.

Parent TX had ~0.002 BTC in fees, and I wanted to lift it to the top of the mempool which would have landed it at ~0.006 BTC. 

Fee estimator correctly suggested 0.006 BTC total fee, but didn't deduct the 0.002 BTC already paid for the parent transaction. I manually overrode it to 0.004 and in the end it did confirm quickly as expected. 

(some adjustments needed of course for the added tx size of the child transaction as well).

Electrum 3.3.4

**Comment by ejose19** [comment]
That's because you're creating a new transaction itself, which of course occupies space in the blockchain, you cannot expect all the fees in that transaction is going to go to the parent.

CPFP works like this:

Retrieve weight and fee from a transaction
Create a new transaction with 1 input (the parent) and 1 output (change)
Sum both the weight for the parent and the newly created transaction
Calculate the estimated fee/byte for the sum of both the weight and then deduce the already paid fees

**Comment by ziggamon** [comment]
@ejose19: Correct. Plz read the OP bug report again.

A 134 byte child transaction adds 0.1% weight to a 100kB+ transaction, the report was about the fee calculation algorithm calculating wrong, not about sub-percent accuracy.

**Comment by ejose19** [comment]
Where are you mentioning the size of the original transaction? You only said "heavy" but you can't expect us to asume it's 100kB (which I highly doubt that's the amount, unless you're an exchange and in that case you won't be using electrum, see https://www.blockchain.com/btc/tx/b30679bf3c688ad8f8b674a25c33399be23234934a488c04b8666f9486c1e5f3 it has 300-500 outputs and it's just 81kB)

" I manually overrode it to 0.004 and in the end it did confirm quickly as expected." Mempool could have drained quickly and it took your transaction in the process, but when the fees were calculated it was right. You need to provide txids for us to really confirm there's a bug in the algorithm

**Comment by SomberNight** [comment]
To be clear, I think OP is right and that the parent's fees are not deducted.
-------- Original Message --------

**Comment by ziggamon** [comment]
In deed, the original transaction was closer to 100kb. Remember that CPFP isn't for transactions generated by electrum, it's for transactions received by electrum. Can send in the txid if it helps debug but doubt it would be useful at this point and costs privacy. Better just review the code that calculates the fee and subtract parent fees.
