### ISSUE TITLE
electrum 3.3.4 for win 10 is not connecting

### ISSUE THREAD

**Issue by wayatwang0605** [spesmilo/electrum#5245]
I have uninstalled version 3.1.3 after malicious phising message.
Downloaded from electrum.org version 3.3.4. Windows Installer
It was synchronizing slowly but connected.
Since April the first I am not able to connect with Electrum 3.3.4
When I try to send BTC this message: BestEffortRequestFailed('no interface to do request on... gave up.',)
Can I check my balance somewhere with the public Key of my wallet?
For the Standalone it's working.

**Comment by SomberNight** [comment]
closing in favour of https://github.com/spesmilo/electrum/issues/5258

see https://github.com/spesmilo/electrum/issues/5258#issuecomment-481945339
