### ISSUE TITLE
[Suggestion] Better client identification as part of server.version RPC

### ISSUE THREAD

**Issue by whizz** [spesmilo/electrum#5246]
I am electrum server operator. I believe it's time to adopt better client identification. Currently, the client name, sent as part of the server.version() call, contains only semantic version, ie. "3.3.4". However, there is other software, that connects to the servers. I know of ACINQ's Eclair wallet, there is probably more.

My suggestion would be to use "SOFTWARE/VERSION".

Examples:
electrum/3.3.4
eclair/1.0

Of course, it's not a security measure or anything like that, but it would make our life as server operators a bit easier. If this is accepted in the main electrum wallet, I will reach out to other software providers and will try to convince them about the same.

**Comment by SomberNight** [comment]
ok, we now send `electrum/3.3.4`

**Comment by SomberNight** [comment]
A good argument for doing this is https://github.com/kyuupichan/electrumx/pull/760, where the server is looking at the client name string to figure out if it's an old electrum client
This kind of thing could happen in the future too, and then it's useful to filter to specific clients.

However, no one can be compelled to send their own client name, and others can continue to try to mimic electrum if they so desire.
