### ISSUE TITLE
How can I get blockchain height through JSON RPC?

### ISSUE THREAD

**Issue by rralev** [spesmilo/electrum#5247]
I'm trying to find the transaction age (blockchain height - transaction height) via JSON RPC.
I can get transaction's height through *getaddresshistory* method but I'm unable to find an appropriate way to get blockchain height.

**Comment by SomberNight** [comment]
See `get_tx_status` RPC call.
Note that it's only on master atm: https://github.com/spesmilo/electrum/commit/8f5ca40d10e921f87f1faf6162d81a62d114f1d7
