### ISSUE TITLE
Description in coin tab does not update properly

### ISSUE THREAD

**Issue by 2pac1** [spesmilo/electrum#5249]
Expected behaviour:
When you change address description under addresses tab, it is expected that the same description is changed under Coins tab

Current behaviour
When you change address description under addresses tab, it is expected that the same description is changed under Coins tab which does not happen. You need to close electrum and start it all over and only then the description will be updated to the new value

**Comment by AbdussamadA** [comment]
The two are independent of each other.

**Comment by 2pac1** [comment]
Can it be updated without the restart of the whole app?

**Comment by AbdussamadA** [comment]
Sorry, I was agreeing with you that this is less than ideal. It shouldn't require a restart.

**Comment by 2pac1** [comment]
Ok
