### ISSUE TITLE
Fee value is not sticky - resets itself to default value

### ISSUE THREAD

**Issue by 2pac1** [spesmilo/electrum#5250]
1. Coins tab - select coin in question
2. Right click - spend
3. You are now in SPEND tab - enter the address you are sending to and the fee and max value of the coins (to spend it all). If you now change tabs and go to HISTORY and back to send, fee value will be lost and reset to electrum's value.

This needs fixing so the value is sticky.

**Comment by SomberNight** [comment]
Can reproduce.
I believe this only happens if while switching tabs the cursor is in `window.fee_e`

**Comment by SomberNight** [comment]
For a different description of the same, see: https://github.com/spesmilo/electrum/issues/5403

**Comment by SomberNight** [comment]
This issue is now obsolete as setting the fee works substantially different on current master.
