### ISSUE TITLE
recover bitcoin

### ISSUE THREAD

**Issue by broker10** [spesmilo/electrum#5252]
hello everyone for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email

**Comment by broker10** [comment]
hello to all for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email investimentsfinanciaresrl@gmail.com

**Comment by gvjordan** [comment]
Scam

**Comment by broker10** [comment]
so you think but you don't know who we are we can recuerate everything
