### ISSUE TITLE
"Unconfirmed parent" in history tab even if it has been confirmed

### ISSUE THREAD

**Issue by jaimefoo** [spesmilo/electrum#5254]
I created a transaction from an unconfirmed one. Now both are confirmed but in the history tab I still find "Unconfirmed parent" and in details "Unconfirmed" even if this is no longer the case

**Comment by AbdussamadA** [comment]
you should switch servers via tools > network > server tab > right click on a different server and choose use server.

**Comment by jaimefoo** [comment]
I am actually using electrum-personal-server. Why is it not seeing the transaction is already confirmed?

**Comment by jaimefoo** [comment]
Restarting eps just solved the issue. Thanks for responding! It actually gave me the hint!

**Comment by AbdussamadA** [comment]
please close this issue if its resolved.
