### ISSUE TITLE
more than a week in DOS attack

### ISSUE THREAD

**Issue by bitdaric** [spesmilo/electrum#5255]
I like to stay with electrum, please find a solution for this. no server work

**Comment by ecdsa** [comment]
disable auto-connect and stick to a single server

**Comment by bitdaric** [comment]
> 
> 
> disable auto-connect and stick to a single server

give me name of a server that connect, I definitely stick with it :)

**Comment by SomberNight** [comment]
try servers at the top of https://1209k.com/bitcoin-eye/ele.php
try e.g. (all ssl)
```
electrum.hodlister.co:50002
arboghast.bauerj.eu:50002
btc.jochen-hoenicke.de:50002
fortress.qtornado.com:50002
```

**Comment by SomberNight** [comment]
closing in favour of https://github.com/spesmilo/electrum/issues/5258
