### ISSUE TITLE
old version of electrum cannot connect to server

### ISSUE THREAD

**Issue by gustitepe** [spesmilo/electrum#5260]
My wallet electrum 3.2.2 says proxy enabled and it does not allow me to send or receive btc. Might you help me ?? How do I solve it ??

**Comment by SomberNight** [comment]
Update to latest electrum.

**Comment by gustitepe** [comment]
como la actualizo ?? tengo que entrar en algun link ?? o lo hago directo desde la wallet ??

**Comment by gustitepe** [comment]
> Actualización al último electrum.

??

**Comment by SomberNight** [comment]
Download the latest version of Electrum from [electrum.org](https://electrum.org/#download) and install it the same way you did in the past.

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/issues/5195

I'll close this as I think the answer above resolves it.
