### ISSUE TITLE
wrong output address

### ISSUE THREAD

**Issue by DavidDaiClipperAdvisor** [spesmilo/electrum#5262]
I planned to send 0.09btc to 35SpAz7KqTFzGES5Smg2txaNzeEkMdhJDJ, and I'm sure I didn't make a mistake. But the transaction turn out to be send all my btc to a new address, I don't even know what it is, the address and amount comes from nowhere.  And now, all my btc has gone!!!!!

**Comment by AbdussamadA** [comment]
Did you recently update electrum in response to in-app messages?

**Comment by DavidDaiClipperAdvisor** [comment]
Yes, I just found I was Phished. the file version is 4.0.0

戴莽原

副总裁，研究

蓝海智投

手机：+86 189 1125 2751

电话：+86 10 5711 6500


Abdussamad Abdurrazzaq <notifications@github.com> 于2019年4月10日周三 下午2:09写道：

**Comment by Santana888** [comment]
The same happened to me on Sunday the 7th. I wanted to send 480 Euros in Bitcoin to an address and was prompted  to upgrade first to 4.0.0. Then suddenly all my Money was sent which was over 520 Euros.
After 300 authentications it still didn*t arrive. What can be done?

**Comment by Twister420** [comment]
Today I tried to transfer $ 20 to the bitcoin address 3BMEXw**********************L73uTiw to transfer the wallet offered to update the version to 4.0.0, after updating all my money $ 100 went to someone else's bitcoin wallet address, without confirming the password!!!  I transferred $ 20, And left the entire amount from the purse $ 100 and they are not returned! It's not my fault, I checked the address-bitcoin and the amount of sending!!

**Comment by SomberNight** [comment]
@DavidDaiClipperAdvisor @Santana888 @Twister420 
what version of Electrum did you use when you got the scam update notification to update to 4.0.0?

**Comment by Twister420** [comment]
> @DavidDaiClipperAdvisor @Santana888 @Twister420
> what version of Electrum did you use when you got the scam update notification to update to 4.0.0?

3.3.2

**Comment by Santana888** [comment]
I was promoted while using 3.2.2 that in order to send this amount I have to upgrade to 4.0.0

**Comment by Twister420** [comment]
transaction is not yet confirmed by me

**Comment by Santana888** [comment]
So what is going on?
Was this a scam?
Can I retrieve my money somehow?
Is the 4.0.0 version legit?

Answer please. I lost 500 Euros.

**Comment by blankcodes** [comment]
> So what is going on?
> Was this a scam?
> Can I retrieve my money somehow?
> Is the 4.0.0 version legit?
> 
> Answer please. I lost 500 Euros.

Yes, you we're hack by the phishing app there's no 4.0 version of electrum yet.

**Comment by Santana888** [comment]
How was this app activated and got on my computer with Antivirus program?

**Comment by SomberNight** [comment]
There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.
See https://github.com/spesmilo/electrum/issues/4968 and https://electrum-malware.surge.sh/

**Comment by Macukam** [comment]
I planned to send 0.00194875btc to 3D64cieUKG9LVG4jk1idVWneovaTiHuzk6, and I'm sure I didn't make a mistake. But the transaction turn out to be send all my btc to a new address 1G2fyCCGDknXWDgWruPWrjfL6iJKejQJHq !!!!!

**Comment by HardCorePawn** [comment]
What version of Electrum are you using? and where did you download it from?

**Comment by MohammedSalah12** [comment]
- Anyone who used Electrum version 4.0.0 his money gone to the attacker.
- There is no version of Electrum is 4.0.0 only now 3.3.4
- Please verify Electrum wallet before putting your coins in it, see how in:-
https://bitcoinelectrum.com/how-to-verify-your-electrum-download/
