### ISSUE TITLE
Transferred money from localbitcoin to electrum wallet  and instantly left my account says i have 0  in the same seconds

### ISSUE THREAD

**Issue by teddda** [spesmilo/electrum#5264]
i have the same problem with one guy who posted before. i send money from localbitcoin to my electrum wallet and in the same second my money go somewhere. the amount of btc wa..
0.48282351  ..  please help

**Comment by teddda** [comment]
i think this is the electrum fault. its not the first time happen like this, can someone help me plaese

**Comment by teddda** [comment]
![btc](https://user-images.githubusercontent.com/49567003/56056905-cd58c780-5d5d-11e9-89b0-609c4174542c.jpg)

**Comment by teddda** [comment]
![btcc](https://user-images.githubusercontent.com/49567003/56056958-f2e5d100-5d5d-11e9-96cd-83a0e98127bc.jpg)

**Comment by jhoenicke** [comment]
You probably have installed a malware-version of electrum; there are many versions floating around and links to the malware are distributed via youtube, google ads, and even via a vulnerability in old clients, where attackers can display a fake message asking you to download a new version from their page.  Or you have other malware that stole the contents your electrum wallet and sent your private keys to the thieves.  Don't use that wallet.

I would recommend to set up the computer from scratch to get rid of the malware.  Don't use the old seed, it is already in the hand of the thieves.  Create a completely new wallet.

Only install electrum from electrum.org and check the gpg signatures.  There is a description how to do this on the download site.

**Comment by teddda** [comment]
no, check my other transactions, i donwload only from https://electrum.org/ .. and its imposible i have malware in pc, this is not about malware, this problem its from electrum version 3.3.2.   can someone tell me what i can do to have my money back, its only that money i have,

**Comment by AbdussamadA** [comment]
The wallet filename is also different from default_wallet. Did you create more than one wallet?

Bitcoin transactions are irreversible so you can't get your money back.

**Comment by teddda** [comment]
yes i have more than 1 wallet. much people have this problem, in the moment need to send money, electrum ask you to update. and in time i update i lost my money

**Comment by teddda** [comment]
2.5 k its much for me to lose like this. no malware in my pc nothing, its electrum problem so all this people losing money where need to ask for they money? maybe fbi need to investigate this this.  i take 3 month to get this money

**Comment by AbdussamadA** [comment]
> much people have this problem, in the moment need to send money, electrum ask you to update. and in time i update i lost my money

So you updated in response to in-app messages?

**Comment by teddda** [comment]
i not update i just go to https://electrumthe.org/ download the last version and the money no more in my account. in the same second

**Comment by teddda** [comment]
i suggest who is reading this, careful of your wallet safe the wallet until electrum fix this. dont send money becouse you will lose all or try with small amount. electrum is not more safe

**Comment by AbdussamadA** [comment]
electrum the dot org is not the real electrum site. you downloaded malware. this is exactly how the phishing scam works. people are asked to manually download malware from fake sites. there is no auto update.

**Comment by thelmagina2** [comment]
I lost over 245K worth of USDT coins and other coins from a romance / investment scam. The money was sent across 3 transactions over a period of 3 months. The scammers manipulated my emotions and tricked me into trusting the fake company and its accomplices. I came across Qualified  Experties while surfing the internet and read about how they helped recover lost funds. After our conversations they kept their promises by recovering the funds I lost and got the money back.

﻿W E B S I T E : h t t p s : / / t e a m . q u a l i f i e d e x p e r t i e s . c o m /

﻿E M A I L : s u p p o r t @ q u a l i f i e d e x p e r t i e s . co m

﻿G m a i l : t e a m q u a l i f i e d r e c o v e r y e x p e r t i s e @ g m a i l . co m

﻿Wa: ‪‪+ 1 4 1 2 2 2 5 5 9 1 8
