### ISSUE TITLE
Phishing possible on 3.3.2?

### ISSUE THREAD

**Issue by dave7280** [spesmilo/electrum#5266]
Hi

I upgraded electrum some time ago to the version which was supposed not to have phishing attack - 3.3.2.

However today i got this message:

https://i.imgur.com/IRaOr8D.png
https://i.imgur.com/2deXHUV.png

It tries to convince me to visit electrum.bz which is scam domain
Shouldnt phishing be not possible on 3.3.2? I know it's not newest version, but i'd like to know on which version is this problem fixed completely

**Comment by SomberNight** [comment]
Hi, yes indeed.

3.3.2 was the version we released immediately after discovering the issue (https://github.com/spesmilo/electrum/issues/4968).

It only displays plain text messages, but it displays them nevertheless. 3.3.3 and later do not display them at all.

-------- Original Message --------

**Comment by dave7280** [comment]
Very surprised.

Why are such versions able to connect to etherum network? Why only < 3.3.0 is not allowed anymore?
Shouldnt it be < 3.3.3?

**Comment by SomberNight** [comment]
We rewrote the networking code in 3.3.0

Only the old code can be crashed. The new code was specifically hardened against servers behaving weird. It is a bug in the old code that we can crash it at all.
-------- Original Message --------
