### ISSUE TITLE
My bitcoin has gone

### ISSUE THREAD

**Issue by gcmunk** [spesmilo/electrum#5268]
Hi, I have made 2 transactions from my electrum, 1 to my friend and another to coinbase neither have went to them.

The first one to my friend was for around £30 and it sent my whole wallet to a different address than what I intended, I'm unsure how this happened as I didn't have any addresses copied.

The second one to coin base did the same thing to the same address so I don't understand what is happening.

I didn't realise till after the second transaction didn't hit my coin base that something was up then I called my friend and found out he didn't receive it either.

I believe it a software bug as I recently got prompted to update, please advise me as I'm losing my head iv lost a total of £360 which is a lot to me.

**Comment by gcmunk** [comment]
After looking on this forum iv found out I'm using a phishing version of electrum, I'm a idiot, is there anything I can do, I beg there is

**Comment by bauerj** [comment]
Apart from filing charges against the phishers, there is not much you can do.

Where did you download Electrum from and how did you find that website?

**Comment by gcmunk** [comment]
It popped up a message to update when I tried to send some BTC to my friend, can I get the bitcoins back I'm guessing not

**Comment by kronosxiv** [comment]
Hello, I had the same problem as gcmunk, the recipient did not receive the BTC sent and I was also forced to update as gcmunk otherwise I could not make a transaction! Can you help us find a solution please?

**Comment by SomberNight** [comment]
There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.

See https://github.com/spesmilo/electrum/issues/4968 and https://electrum-malware.surge.sh/

If you downloaded and used software from those phishing messages, then what you used was not Electrum. Those coins are gone.

**Comment by sharipaula** [comment]
Me too. Heartsick as notion that money is gone I'm realizing, I too cannot afford it, with every dollar precious now, also precious is what I bought, but alas didn't buy. If anyone finds recourse, please do share.

**Comment by ecdsa** [comment]
please post the website where you downloaded the malware

**Comment by kronosxiv** [comment]
Was directly on electrum

**Comment by ecdsa** [comment]
closing, no url provided
