### ISSUE TITLE
New to Crypto - Unconfirmed Transaction

### ISSUE THREAD

**Issue by gsaint5500** [spesmilo/electrum#5269]
I just purchased a small amount of bitcoin and had it transferred successfully to my Electrum wallet. I then initiated a transfer out to my poker site and the transaction appears to be in limbo as it has been listed as unconfirmed for four hours. What do I need to do? Any help greatly appreciated.

**Comment by SomberNight** [comment]
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do
