### ISSUE TITLE
The server returned an error when broadcasting the transaction. RPCError(1, 'Transaction Denied. Important Electrum Security Vulnerability.  Transactions can only be sent after upgrading to version 4.0.0 Official Website: https://www.electrumcore.com')

### ISSUE THREAD

**Issue by daffy6537** [spesmilo/electrum#5273]
The server returned an error when broadcasting the transaction. RPCError(1, 'Transaction Denied. Important Electrum Security Vulnerability.  Transactions can only be sent after upgrading to version 4.0.0 Official Website: https://www.electrumcore.com')

electrum version 3.3.2
it seems hacked?????

**Comment by daffy6537** [comment]
after upgraded to 3.3.4,  it back to normal

**Comment by jhoenicke** [comment]
Note: electrumcore DOT com is malware server (official site is electrum.org). 

3.3.2 still showed the error message from the electrum server, but at least it is not clickable.  Newer versions will not show the error message but tell you to choose a different server.
