### ISSUE TITLE
Electrum 4.0.0 

### ISSUE THREAD

**Issue by isabellajullian** [spesmilo/electrum#5276]
When I was trying to make transaction through Electrum 3.0.6 it came up a message"Transaction Error : Required Security update (v4.0.0)", then a link came up for me to update to 4.0.0.when I completed update and trying to make a transaction like 50mbtc, it sends all amount off my wallet to an unknowen adress! 
I was shocked, there are 14,903dollars, it's a huge loss for me, I also tried to downlaod the new version on https://electrum.org, but it does no help and it seems like a virus version, I feel helpless now.
Till now I am still trying to find out some solution to make it back, is there anyone could help?

**Comment by SomberNight** [comment]
There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.

See #4968 and https://electrum-malware.surge.sh/

If you downloaded and used software from those phishing messages, then what you used was not Electrum. Those coins are gone.

**Comment by SomberNight** [comment]
Could you please share where you downloaded "electrum 4.0.0" from? We would at least try to get that website taken down.

**Comment by ecdsa** [comment]
closing, no answer from OP

**Comment by alexeydemin** [comment]
https://electrumportal.com
