### ISSUE TITLE
why my balance is zero.

### ISSUE THREAD

**Issue by charry99** [spesmilo/electrum#5277]
after my electrum wallet updated then showing zero balance. 
b0b70410fe4f8249e8dec892765e0f0d7a48124786914da99700d553eb897043

**Comment by SomberNight** [comment]
Did you get prompted by Electrum to download an "update", right after trying to send a transaction?

There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.

See #4968 and https://electrum-malware.surge.sh/

If you downloaded and used software from those phishing messages, then what you used was not Electrum. Those coins are gone.

**Comment by ecdsa** [comment]
closing, no answer
