### ISSUE TITLE
Connect over TCP Protocol from electrum android app

### ISSUE THREAD

**Issue by nixbitcoin** [spesmilo/electrum#5278]
Entering port 50001 in the server configuration on Electrum android does not result in the app making requests over tcp. I am using a Tor HS to connect to my electrs server so I do not require SSL.

**Comment by SomberNight** [comment]
Yes, you are correct, there is no way to not use SSL/TLS in the Android app.
This is also true for the Qt GUI; you would need to modify the config or use CLI options. (though that is at least feasible there)

I am unsure if this feature would be worth adding; you can configure your server to serve SSL over onion.

**Comment by nixbitcoin** [comment]
> I am unsure if this feature would be worth adding; you can configure your server to serve SSL over onion.

I went this route since it seemed easier and conforms to user expectations.

Relevant PR: https://github.com/jonasnick/nix-bitcoin/pull/45

**Comment by Engelberg** [comment]
Also interested in this. Generating certificates requires installing a lot of extra tooling, it means there's an expiry date so I need to remember to update it, and fronting the whole thing with nginx is one more thing to setup and one more thing to potentially screw up in a way that creates a vulnerability. Using TCP over hidden service was easy to set up and uncomplicated to maintain. Would love to be able to connect Android app to what I've set up.

**Comment by Engelberg** [comment]
Also, the electrum documentation itself says at http://docs.electrum.org/en/latest/protocol.html:
```
non-standard port would be announced this way: “t3300” for tcp on port 3300
```

So it would be reasonable for this to work here as well.  That would be a way to add it to the app without complicating the UI.  Just allow the user to type "t50001" in the port number field to specify TCP.

**Comment by k3tan172** [comment]
I would be interested in this feature also.

**Comment by ascisco** [comment]
Would like this feature as well. Trying to connect to my TOR electrs server through mobile and it rejects the connection because it is forced over SSL.

**Comment by ascisco** [comment]
Would like this feature as well. Trying to connect to my TOR electrs server through mobile but there is no way to specify TCP connection on electrum mobile.

**Comment by frndxyz** [comment]
So you guys means ssl not work for mac desktop app? I wonder in my case it connecting.

**Comment by SomberNight** [comment]
> So you guys means ssl not work for mac desktop app? I wonder in my case it connecting.

This issue is about having an option to disable SSL/TLS in the Android app. (It is force-enabled atm)
It has nothing to do with Mac.

**Comment by SomberNight** [comment]
Due to popular interest in this, we have now unified the host and port input fields, which allows optionally specifying the protocol as part of the string.
