### ISSUE TITLE
i'm updated electrum 4.0,after i update my wallet balance is zero. please help me.

### ISSUE THREAD

**Issue by charry99** [spesmilo/electrum#5280]
Hi, I have made 1 transaction from my electrum, 1 is my own electrum wallet address neither have went to them.
I believe it a software bug as I recently got prompted to update, please advise me as I'm losing my head iv lost a total of 0.05964762 BTC which is a lot to me.

**Comment by kangasbros** [comment]
There is no electrum 4.0 - the newest version is 3.3.4. Might be that you have been affected by a scam site which has tricked you into installing a client that stole your fund. Sorry for your loss.

**Comment by SomberNight** [comment]
> a software bug as I recently got prompted to update

There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.

See https://github.com/spesmilo/electrum/issues/4968 and https://electrum-malware.surge.sh/

If you downloaded and used software from those phishing messages, then what you used was not Electrum. Those coins are gone.

**Comment by SomberNight** [comment]
Could you please share where you downloaded "electrum 4.0.0" from? We would at least try to get that website taken down.

**Comment by ecdsa** [comment]
closing, no answer
