### ISSUE TITLE
Coins automatically sent unauthorized to unknown address, Was not phished/Used latest version for previous transaction

### ISSUE THREAD

**Issue by LLipton** [spesmilo/electrum#5282]
As title suggests, I was sent BTC by a trusted source to an Electrum wallet. 
I went to sleep thinking nothing of it. I woke the next day to find my balance at 0.00000, sent to an address I'm working on finding the private key of, using an unbelievably low transaction fee (5.2 sat/b)

It is impossible that I did this intentionally. There was no new version prompting me to update during the transaction.

This new transaction began after a single confirmation according to the sender, and I've been more than diligent in ensuring that I keep 'Spend Unconfirmed' set to Off/No. My transaction fees have never been set so low while I always make sure to check before every transaction I receive that I shouldn't be able to spend coins from unconfirmed transactions.

This unauthorized transaction occurred using the Electrum Android mobile-app that I have never previously had a problem with. I'd just downloaded the application to an unused phone that's been untouched for at least one year. As such, before, during, and after this transaction occurred, it was/is disconnected from service.

Thoughts?

**Comment by SomberNight** [comment]
> This unauthorized transaction occurred using the Electrum Android mobile-app

Did you only have the seed words/private keys for this wallet in the Electrum Android app? Or e.g. did you reuse this same wallet on a PC?

Where/how do you store the seed words/backups for this wallet?

**Comment by ecdsa** [comment]
it looks like your seed was compromised, hence @SomberNight's questions

**Comment by LLipton** [comment]
No, @SomberNight & @ecdsa and I never have.  I've never looked at my private keys for any wallet on any mobile device, much less saved.

I've always kept all my seeds on paper. I use a few wallets, but I've used the exact same Electrum wallet on my PC for almost three years now. I actually didn't even have the latest version on my main PC (obviously incapable of synchronization/connection to servers) for about two and half months prior to this incident. I didn't even upgrade Electrum on it until after it had occurred.  This is first time anything like this has ever occur with any of my wallets.

I monitor my network closely, and the only thing that's happened in the past four months was a TCP Port scan that ended with no packets neither attempting to be sent, nor would any have been accepted if tried. Over 5,000$ has gone thru it since I first used it. Transactions have ranged >1,000$ at a time, so it's just hard for me to believe an amount like this would've been a target.

It's very odd when I looked into it. The wallet's two most recent transactions were seemingly with itself, and then to another address which has been attempted to be sent out in a mass-pay. Funds haven't really moved since then. Both transactions had a much higher fee used and much less cumulatively has moved since then. I also obtained the public key for the second transaction's BTC address. I placed in a different wallet to watch,, and that group transaction has zero confirmations for that address currently since I first noticed it.

My fear is that it may have been a job done within the Electrum server list via a singular server. I highly doubt this for obvious reasons.

I'll email you both the transaction IDs, addresses, and my public key immediately for further inspection.

**Comment by LLipton** [comment]
No, and I never have. I typed out a much longer post that didn't seem to get posted unfortunately. 
Suffice to say overall:
I've never even looked at my private keys on mobile device, and I always keep my seeds on paper in a notebook.
My network is something I closely monitor. The only suspicious activity within the last four months was a TCP Port scan of three ports resulting in no packets attempting to be sent.

My biggest fear is that it may have been a singular server within the Electrum server list I selected for the transaction, but I have great doubt of this for obvious reasons.

I'll email you both the addresses, transaction IDs, and my public key for further inspection.

**Comment by ecdsa** [comment]
I received your email with the xpub.
your seed was stolen, and it is not possible to determine exactly how it was stolen.
it might be malware, but it might also be someone accessing your device.
note that servers are not able to steal your seed.
