### ISSUE TITLE
Import private keys does not properly validate compressed keys (not checking last byte)

### ISSUE THREAD

**Issue by Coding-Enthusiast** [spesmilo/electrum#5290]
Being compressed [is not just length](https://github.com/spesmilo/electrum/blob/b39c51adf7ef9d56bd45b1c30a86d4d415ef7940/electrum/bitcoin.py#L578), it also is the last byte being `1` and should reject anything that is not.  

Test case:
`KwFAa6AumokBD2dVqQLPou42jHiVsvThY1n25HJ8Ji8REf1wxAQb` decodes to the following bytes (in hex): `8000bf9c46a7c40aaf96ed20cfc0ab0f929d9be1748af89b37e9efb4cdb98da6b0cbb81a7b94`. Removing the checksum 4 bytes we have 34 bytes `80-00bf9c46a7c40aaf96ed20cfc0ab0f929d9be1748af89b37e9efb4cdb98da6b0cb` which passes on line 578 linked above. However the last byte is `0xcb` instead of being `0x01` and must be rejected.  

Disclaimer: the key is from [this topic on bitcointalk](https://bitcointalk.org/index.php?topic=5135547.0) which was the reason I found this bug.

**Comment by SomberNight** [comment]
Yes, indeed. Thanks.
