### ISSUE TITLE
Lost and gone forever? 

### ISSUE THREAD

**Issue by sharipaula1** [spesmilo/electrum#5291]
I sent some $130 worth of coin from wallet yesterday.  Purchase was actually <$110, I wondered why fee swallowed another $22 of BTC, depleting my wallet balance, now $0. 
 But after a day, my transaction has not cleared and is listed as "unpaid".  Thief or glitch? Coin gone into illdoer's hands?

**Comment by AbdussamadA** [comment]
what version of electrum are you using? what does it say for wallet type under wallet menu > information?

**Comment by ecdsa** [comment]
why dont you post the transaction ID?

**Comment by ecdsa** [comment]
if the fee was high and tx has not cleared after a day, it is probably that the transaction was consolidating a large number of utxos
