### ISSUE TITLE
BitPay BIP70 signing x509 cert has expired. Electrum will refuse to accept it.

### ISSUE THREAD

**Issue by armin884** [spesmilo/electrum#5292]
Running latest electrum 3.3.4 windows. I can't make any payments with bitpay payment link. Error: Certificate has expired. (bitpay.com) ? I'm running electrum for years never had this error...

**Comment by kyledrake** [comment]
Same issue.

**Comment by SomberNight** [comment]
Is this a bug report? Why are you not complaining to BitPay? :)
The x509 certificate using which they are signing the payment request has expired at 2019-04-25 17:11:00 UTC.
Electrum is checking that the cert is valid, which it is not (anymore).

**Comment by SomberNight** [comment]
Do you mean this a feature request to optionally accept expired certs?

**Comment by kyledrake** [comment]
Adding the expiration date of the cert would be helpful.

**Comment by hegjon** [comment]
Bitpay have fixed it on their side https://www.reddit.com/r/btc/comments/bhnnau/keys4coins_we_get_an_error_when_we_attempt_to_pay/elv5el1?utm_source=share&utm_medium=web2x

**Comment by SomberNight** [comment]
Thanks for saying so.
