### ISSUE TITLE
Testnet servers in servers_testnet.json is out of date

### ISSUE THREAD

**Issue by schildbach** [spesmilo/electrum#5293]
Either their hostname doesn't resolve, or they refuse connections, or they don't have a certificate on their TLS port (not even a self-signed one).

**Comment by SomberNight** [comment]
Unfortunately hardly anyone runs testnet servers. You are more than welcome to run one! :)

Also, some of these servers are run on the same machines as mainnet servers, and mainnet servers are heavily DDOS-ed now. The already low number of testnet servers is not taking the DDOS well...
