### ISSUE TITLE
User confuses testnet with mainnet

### ISSUE THREAD

**Issue by hardworkrio** [spesmilo/electrum#5295]
WONT LET ME TO SEND TO BLOCKCHAIN OR COINBASE FROM ELECTRUM WALLET

HELP!!!!!!!

**Comment by SomberNight** [comment]
Can you please take a screenshot of the error? Make sure the `Pay to` (top) line is visible.

**Comment by hardworkrio** [comment]
[image: image.png]

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56845409-c7e79b00-688e-11e9-8104-4eea218bdd72.png)

**Comment by ecdsa** [comment]
you are trying to send btc from a testnet wallet..

**Comment by AbdussamadA** [comment]
i think he may have been scammed. i think a warning dialog at startup similar to the one for watch-only wallets would help.

**Comment by hardworkrio** [comment]
> you are trying to send btc from a testnet wallet..

yea somehow I got it to this wallet... but I wanna get it back to reg wallet so I canc cashout to my blockchain

**Comment by hardworkrio** [comment]
> i think he may have been scammed. i think a warning dialog at startup similar to the one for watch-only wallets would help. alternatively a shortcut to the testnet version should not be installed because it only confuses users. advanced users can figure out how to run the testnet version if they really want to.

no I haven't been scammed... I had it in reg wallet but it didn't confirm all the way cause something I did... so some how my buddy got me to get my BTC confirmed but it went to testnet wallet... so now im trying to get my shit back to regular

**Comment by SomberNight** [comment]
Search for `Electrum` in the Windows Start menu. I think it should find a shortcut with "testnet" in the name and one without.

**Comment by hardworkrio** [comment]
> Search for Electrum in the Windows Start menu. I think it should find a shortcut with "testnet" in the name and one without.

imma screenshot my prob

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56851418-23407a00-68dd-11e9-83de-8cda32b03632.png)

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56851422-33585980-68dd-11e9-9194-4a0cad229354.png)


now this wallet saying OFFLINE btw... how do i turn back green

**Comment by hardworkrio** [comment]
testnet wallet got my btc...

**Comment by SomberNight** [comment]
testnet and mainnet are two different networks. Bitcoin Testnet is basically an altcoin.
Close the testnet window and forget about it. It is for **testing**.
What you see in mainnet "regular" Electrum is what matters; that's your real money.

**Comment by hardworkrio** [comment]
> testnet and mainnet are two different networks. Bitcoin Testnet is basically an altcoin.
> Close the testnet window and forget about it. It is for testing.
> What you see in mainnet "regular" Electrum is what matters; that's your real money.

I read that online as well... but this what im explaining...



I MY BTC WAS IN MY MAIN NET WALLET.. BUT IT DIDNT CONFIRM RIGHT... SO MY BUDDY GOT ON TEAMVIEW AND TRIED HELPING ME


WATEVER HE DID WORKED CAUSE MY SHIT GOT CONFIRMED CORRECTLY... BUT IT WONT SEND


IT WOULD SEND WHEN IT WAS IN MAIN WALLET TO AS WELL BTW

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56851504-05bfe000-68de-11e9-93e5-78bb386f00ad.png)


CONSTANTLY SAID THIS

**Comment by hardworkrio** [comment]
1Ad9zN5kk5PLv5XH2yC3wvvp6d5m3swMMf 

THIS THE ADDRESS I WANNA SEND TO

**Comment by SomberNight** [comment]
> THIS THE ADDRESS I WANNA SEND TO

You are trying to send monopoly money to an address that only accepts real money. You cannot do that?
Should I write in ALL CAPS too?

**Comment by hardworkrio** [comment]
> THIS THE ADDRESS I WANNA SEND TO
> 
> You are trying to send monopoly money to an address that only accepts real money. You cannot do that.
> Should I write in ALL CAPS too?

but this is my real money thats what im explaining bro... I dont even know how I got it to testnet mode

**Comment by hardworkrio** [comment]
![btvc](https://user-images.githubusercontent.com/50036779/56851731-854eae80-68e0-11e9-898c-a2cb4665fc4a.jpeg)
'



this my wallet b4 the testnet shit... but my btc didnnt confirm correctly

**Comment by SomberNight** [comment]
Tell us about those two transactions that show up in the mainnet wallet. What are those?

**Comment by hardworkrio** [comment]
> Tell us about those two transactions that show up in the mainnet wallet. What are those?

I had my settings set wrong... I hash btc and it works all time

this time I had my settings did wrong in wallet... my btc appeared but didn't confirm

so my buddy did something to where it transferred to testnet wallet but now I wanna get it back to main wallet 


when I hash b4 it worked and I could send back to my wallets

**Comment by hardworkrio** [comment]
some one told me I can take my seed from testnet and place into regular wallet and funds will appear.. idk how true this is bcuz I took my seed and downloaded electrum wallet on computer #B and used my seed but it didn't make my transations history or nothing appear

**Comment by SomberNight** [comment]
> Tell us about those two transactions that show up in the mainnet wallet. What are those?

>> I had my settings set wrong... 

Ok but could you please explain what those transactions are? e.g. "first one is me buying bitcoins from an exchange"
I am trying to figure out if your "buddy" scammed you.

**Comment by hardworkrio** [comment]
> Tell us about those two transactions that show up in the mainnet wallet. What are those?
> 
> 
> 
> I had my settings set wrong...
> 
> 
> Ok but could you please explain what those transactions are? e.g. "first one is me buying bitcoins from an exchange"
> I am trying to figure out if your "buddy" scammed you.

I send btc to my electrum wallet from blockchain using certain seeds giving... to hash my btc [ Double it ;)  ]


long story short... any other time I do it, it works, I done with .95 cent... doubled to 2$ and was able to cashout 

even done with 5$ btc and it work

**Comment by hardworkrio** [comment]
the transactions are basically to myself so nobody can scam me

**Comment by hardworkrio** [comment]
im not sending btc to anybody but myself and it lands in my wallet so i dont see a scam...

**Comment by SomberNight** [comment]
So what happened with that 0.226 btc you were trying to "double"? do you have it in your blockchain.info wallet?

**Comment by hardworkrio** [comment]
> So what happened with that 0.226 btc you were trying to "double"? do you have it in your blockchain.info wallet?

it didn't confirm right to the preferences I had set... so my buddy helped me but the btc led over to the testnet wallet

**Comment by hardworkrio** [comment]
and it confirmed when it went to the testnet wallet

**Comment by hardworkrio** [comment]
lemme ask this.. If I take my seed from the testnet wallet and put it on my computer #B wallet and set it to BIP39 Seed what would that do???????/

**Comment by SomberNight** [comment]
aha. I see what happened.

- you sent 0.226 btc from your blockchain.info wallet to your electrum wallet, in transaction A, to "double" it
- you tried to send 0.226 btc back from your electrum wallet to your blockchain.info wallet, in transaction B
- transaction B was unconfirmed for some time so you started to worry, and asked your buddy to help
- he teamviewered into your PC, and double-spent transaction B with transaction C that sent the 0.226 btc to him instead
- he also opened Electrum Testnet for you; created a new wallet there for you; and sent 2*0.226 btc in transaction D over testnet to that wallet
- now you are out of your 0.226 btc; but instead you have 0.452 testnet bitcoins

Was your buddy the one who had this phenomenal idea of doubling your bitcoins in the first place?

**Comment by hardworkrio** [comment]
> aha. I see what happened.
> 
> you sent 0.226 btc from your blockchain.info wallet to your electrum wallet, in transaction A, to "double" it
> you tried to send 0.226 btc back from your electrum wallet to your blockchain.info wallet, in transaction B
> transaction B was unconfirmed for some time so you started to worry, and asked your buddy to help
> he teamviewered into your PC, and double-spent transaction B with transaction C that sent the 0.226 btc to him instead
> he also opened Electrum Testnet for you; created a new wallet there for you; and sent 2*0.226 btc in transaction D over testnet to that wallet
> now you are out of your 0.226 btc; but instead you have 0.452 testnet bitcoins
> 
> Was your buddy the one who had this phenomenal idea of doubling your bitcoins in the first place?





you got it all right except this part


he teamviewered into your PC, and double-spent transaction B with transaction C that sent the 0.226 btc to him instead



he sent from wallet A wallet B which is testnet... he never sent to himself i watched him so he didnt rip or take my money

**Comment by hardworkrio** [comment]
but even if what your saying is "true" how could I know if he sent to himself or not?

**Comment by hardworkrio** [comment]
he sent the btc from wallet A cause it didn't confirm right... he somehow got it over to B

**Comment by hardworkrio** [comment]
![not right](https://user-images.githubusercontent.com/50036779/56852231-8da9e800-68e6-11e9-8ac1-63a82d44a9ae.jpg)



when I first sent from my block chain to electrum wallet it did this....

u see that yield sign


and u see 1 transaction had + and one had '  -  " thats how I knew I had settings wrong... so he got on team viewer

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56852256-e6798080-68e6-11e9-8319-4cd54e42b1a1.png)



LEFT IS WALLET "A" AND RIGHT IS TESTNET  WALLET "B"

**Comment by hardworkrio** [comment]
AND ALSO NOW MY TESTNET WALLET SAYING OFFLINE... HOW DO I GET BUBBLE TO GO GREEN AGAIN

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56852286-42dca000-68e7-11e9-93a8-3d3dfa22555b.png)



I TRACK TRANSACTION FROM WALLET A... AND I SEE THIS..

**Comment by SomberNight** [comment]
> AND ALSO NOW MY TESTNET WALLET SAYING OFFLINE... HOW DO I GET BUBBLE TO GO GREEN AGAIN

Click on it, and then in the newly opened `Network` dialog, in the `Server` tab, make sure `Select server automatically` is enabled.

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56852350-73710980-68e8-11e9-85f6-21817a5a2644.png)



IT IS

**Comment by SomberNight** [comment]
Ok, then uncheck it instead, and set server to
`bitcoin.cluelessperson.com`  with port `51002`

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56852481-1d9d6100-68ea-11e9-8f5b-58f0f4947f4f.png)

**Comment by hardworkrio** [comment]
now its online

**Comment by hardworkrio** [comment]
but can I copy the testnet wallet seed to another electrum wallet on my other computer... will my funds be there to?

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56852580-feeb9a00-68ea-11e9-920d-e8b1a99248e4.png)



what does invalid lines mean

**Comment by SomberNight** [comment]
So from your screenshots, I assume your mainnet electrum address is https://blockstream.info/address/153JmDtfoEbLgT6nhN9HjZ5quycGRcSCdT

Transaction A is https://blockstream.info/tx/7df3438f08d5d9a2a947d6426f77d841d097f7fedc5b1c501c15f49e1cac8caa

Transaction C is https://blockstream.info/tx/84177e15a8268095f1edf927bb72806229b0d24145933eaf2bcbe4288653e36d

note that the output of transaction C is already spent!!
https://blockstream.info/tx/a30f1ec93e35f39ac526474eea8e249a702855aaa874deb4f6c0dc45b99a6279?input:147

your friend has already moved your coins.

**Comment by SomberNight** [comment]
> what does invalid lines mean

it means that the address is not valid. This is true: you are trying to pay to a mainnet bitcoin address, using a testnet wallet. A mainnet bitcoin address is not a valid testnet address.

**Comment by hardworkrio** [comment]
> So from your screenshots, I assume your mainnet electrum address is https://blockstream.info/address/153JmDtfoEbLgT6nhN9HjZ5quycGRcSCdT
> Transaction A is https://blockstream.info/tx/7df3438f08d5d9a2a947d6426f77d841d097f7fedc5b1c501c15f49e1cac8caa
> Transaction C is https://blockstream.info/tx/84177e15a8268095f1edf927bb72806229b0d24145933eaf2bcbe4288653e36d
> note that the output of transaction C is already spent!!
> https://blockstream.info/tx/a30f1ec93e35f39ac526474eea8e249a702855aaa874deb4f6c0dc45b99a6279?input:147
> your friend has already moved your coins.

how could he moved my coins if I watched him and he didn't do it

**Comment by hardworkrio** [comment]
also I see what your saying about the BTC TRANSACTION C... BUT HOW IS IT SPENT IF I DIDNT SEND TO THAT ADDRESS

**Comment by hardworkrio** [comment]
KIND OF MAKE SENSE BUT DOESNT CAUSE... IF YOU LOOK AT YOUR OWN PERSONAL TRANSACTIONS ITLL SAY SPENT!

**Comment by SomberNight** [comment]
> how could he moved my coins if I watched him and he didn't do it

https://www.youtube.com/watch?v=yP-OvorryAU

**Comment by hardworkrio** [comment]
![image](https://user-images.githubusercontent.com/50036779/56852807-b1246100-68ed-11e9-9ea3-0b19c7147cec.png)



SO U SAYING HE MOVED TO THAT WALLET ON THE RIGHT?

**Comment by hardworkrio** [comment]
BUT HOW WHEN I FIRST SENT BTC TO MY ELECTRUM WALLET I TRACKED TRANS.... IT SAY IT WAS SENT TO THIS WALLET.... THIS WAS BEFORE HE GOT ON TEAM VIEWER

**Comment by hardworkrio** [comment]
so if he gave me a seed to use... would my btc go to him? or no

**Comment by hardworkrio** [comment]
help me understand... besides the youtube video that has nothing to do with this convo

**Comment by hardworkrio** [comment]
![not right](https://user-images.githubusercontent.com/50036779/56852915-0dd44b80-68ef-11e9-8c73-519d400eea09.jpg)


since you explained everything else.... can you tell me what this mean

cause this the orginal problem that got me ALLLL THE WAY HERE TO THIS TESTNET PROB

**Comment by hardworkrio** [comment]
![btvc](https://user-images.githubusercontent.com/50036779/56852936-46742500-68ef-11e9-9621-6503c90658ae.jpeg)



THEN AFTER THAT PIC ABOVE... I GOT THIS PROB... SO HOW COULD HE STOLE AND SENT BTC TO HIMSELF IF WHEN I TRACKED TH BLOCKCHAIN.INFO IT SAID SENT TO THAT ADDRESS B4 I EVEN HAD HIM GET ON TEAM VIEWER

**Comment by hardworkrio** [comment]
so if he gave me a seed to use... would my btc go to him? or no?????

**Comment by hardworkrio** [comment]
this my last question.... so say if he did send the btc to himself


how come the same btc you say he sent to himself... is in my testnet wallet... how can it appear in his wallet and also In my testnet… is that possible?


also he gave me a seed....
so if he gave me a seed to use... would my btc go to him?

**Comment by SomberNight** [comment]
> also he gave me a seed....

What did you do with this seed? You can try restoring from it I guess.

> how come the same btc you say he sent to himself... is in my testnet wallet... how can it appear in his wallet and also In my testnet… is that possible?

I already explained that above. He just sent you testnet coins separately. Testnet coins are almost worthless. There are websites on the Internet giving them out for free.

**Comment by hardworkrio** [comment]
> also he gave me a seed....
> 
> What did you do with this seed? You can try restoring from it I guess.
> 
> how come the same btc you say he sent to himself... is in my testnet wallet... how can it appear in his wallet and also In my testnet… is that possible?
> 
> I already explained that above. He just sent you testnet coins separately. Testnet coins are almost worthless. There are websites on the Internet giving them out for free.

but u didn't explain how he could sent my btc to himself when he never got in my wallet and sent anything to himself.... he just sent the btc from the reg wallet to the testnet wallet... shit so confusing

**Comment by hardworkrio** [comment]
I watched him... but I do get what your saying and your thinking the way i am and i know you know bit  more

**Comment by hardworkrio** [comment]
really this my real question thatll help me


so if he gave me a seed to use... would my btc go to him? i wanna know from you bro

**Comment by AbdussamadA** [comment]
The seed is supposed to be secret. You are supposed to let electrum generate it for you on your own device and you are not supposed to reveal it to anyone. Anyone who has knowledge of the seed can move the bitcoins sent to addresses generated from that seed. They don't need to do this on your PC they can do it on their own device at any time and place of their choosing. To use a seed that someone else gave you is setting yourself up for theft. Letting someone else access your PC remotely is setting yourself up for theft. Your buddy scammed you.

**Comment by cculianu** [comment]
As a Bitcoin Cash afficionado I will be that guy: may I point out had his original tx confirmed in a reasonable amount of time -- perhaps none of this would have happened.

Happy Orthodox Easter!

**Comment by SomberNight** [comment]
@cculianu block times are unpredictable. and note that based on the screenshots, the tx was not using RBF.
