### ISSUE TITLE
who is sending me this message?

### ISSUE THREAD

**Issue by bastiaandehaan** [spesmilo/electrum#5297]
I find this message in my history:

**Payment request for BitPay invoice GVWk2ZV122jw7uSAKfKLhq for merchant Cyando AG**

Any idea ? Both Bitpay as Cyando are non familiar names for me.

https://blockstream.info/tx/4ae669978b3bcf349f72b53b542f4106f8dfacf1c57dacdb1fdaaa14cd1aa829

![invoice](https://user-images.githubusercontent.com/50037841/56844931-16aa2a80-68b9-11e9-965a-fb00b9ecde4f.JPG)

**Comment by ecdsa** [comment]
you probably clicked on that invoice, so it was saved in your list of invoices
