### ISSUE TITLE
Mass payment

### ISSUE THREAD

**Issue by bitdaric** [spesmilo/electrum#5301]
is this possible?

**Comment by AbdussamadA** [comment]
See [here](http://docs.electrum.org/en/latest/faq.html#can-i-do-bulk-payments-with-electrum). Please close this issue. In future ask for help on the [community forums](https://electrum.org/#community).

**Comment by bitdaric** [comment]
> 
> 
> See [here](http://docs.electrum.org/en/latest/faq.html#can-i-do-bulk-payments-with-electrum). Please close this issue. In future ask for help on the [community forums](https://electrum.org/#community).

I need it from command line.

**Comment by AbdussamadA** [comment]
`usage: electrum paytomany [-h] [-v [VERBOSITY]] [-D ELECTRUM_PATH] [-P]
                          [-w WALLET_PATH] [--testnet] [--regtest] [--simnet]
                          [-f FEE] [-F FROM_ADDR] [-c CHANGE_ADDR] [--nocheck]
                          [-u] [--rbf RBF] [-W PASSWORD] [--locktime LOCKTIME]
                          outputs

Create a multi-output transaction.

positional arguments:
  outputs               list of ["address", amount]

optional arguments:
  -h, --help            show this help message and exit
  -f FEE, --fee FEE     Transaction fee (in BTC)
  -F FROM_ADDR, --from_addr FROM_ADDR
                        Source address (must be a wallet address; use sweep to
                        spend from non-wallet address).
  -c CHANGE_ADDR, --change_addr CHANGE_ADDR
                        Change address. Default is a spare address, or the
                        source address if it's not in the wallet
  --nocheck             Do not verify aliases
  -u, --unsigned        Do not sign transaction
  --rbf RBF             Replace-by-fee transaction
  -W PASSWORD, --password PASSWORD
                        Password
  --locktime LOCKTIME   Set locktime block number

global options:
  -v [VERBOSITY]        Set verbosity filter
  -D ELECTRUM_PATH, --dir ELECTRUM_PATH
                        electrum directory
  -P, --portable        Use local 'electrum_data' directory
  -w WALLET_PATH, --wallet WALLET_PATH
                        wallet path
  --testnet             Use Testnet
  --regtest             Use Regtest
  --simnet              Use Simnet
`
