### ISSUE TITLE
Audit logs for pull requests?

### ISSUE THREAD

**Issue by AnonEMousse** [spesmilo/electrum#5302]

**Comment by SomberNight** [comment]
> I am wondering if there is an audit log (maintained by either spesmilo or GitHub) of these pull requests that could help identify the malicious actor.

The Electrum project do not have a private log of any kind for pull requests/issues opened against the repository. Everything we have is publicly visible on the website (GitHub).

_(Note that the author of an issue/PR can freely edit it after the fact. In this case people who were subscribed to that issue/PR or the whole repository, do have the original issue/PR as an email in their mailbox ----- in this case, I don't have that, but I doubt it would be of much help)_

Your only chance is asking GitHub themselves, but I expect they only have an email address and a few IP addresses, both of which could have been "obfuscated" (throwaway email, Tor) by the owner of the account.

 Good luck
