### ISSUE TITLE
Error transfer [no action]

### ISSUE THREAD

**Issue by tcolonel** [spesmilo/electrum#5303]
Hi everyone!

I've been trying to transfer BTC from my Electrum wallet to another wallet, I've done this before a lot of times, however, this time I've confirmed the send from my Electrum wallet (pass + GA pass) but it's show me the popup-window with yellow triangle and without any text ...

If anyone has any idea whats wrong, or have a potential solution, then I would be greatly appreciative. May be there is some logs where I can view errors?

Thanks in advance for any potential help.

My Electrum is portable version 3.3.4.

**Comment by SomberNight** [comment]
Hey.
- Which operating system are you using?
- Please try with a Tor proxy (download the Tor Browser, run it; then in Electrum `Tools`>`Network`>`Proxy` check `Use Tor proxy at port ...`)
- How soon after you enter the 2FA code do you get the error?

**Comment by tcolonel** [comment]
> Which operating system are you using?

Windows 7 Max 64 bit

> Please try with a Tor proxy (download the Tor Browser, run it; then in Electrum Tools>Network>Proxy check Use Tor proxy at port ...)

Already - always.

> How soon after you enter the 2FA code do you get the error?

5-10 sec.

**Comment by westy2001** [comment]
Привет! как решили проблему ( у меня тож самое)....

**Comment by tcolonel** [comment]
@SomberNight any news? Or may be need some another info?

**Comment by SomberNight** [comment]
@tcolonel could you test on Linux/Mac (with the `-v` option)? or could you test running git HEAD (latest master)?
alternatively, would you be willing to run a binary I build for you?

**Comment by tcolonel** [comment]
@SomberNight

> could you test on Linux/Mac (with the -v option)?

I can try, but I'm not sure about the success of this operation.
<br/>
> or could you test running git HEAD (latest master)?

and?
<br/>
> alternatively, would you be willing to run a binary I build for you?

Why not. Lets try. I need run it under Windows?

**Comment by westy2001** [comment]
"could you test on Linux/Mac (with the -v option)?"

did, no result

**Comment by SomberNight** [comment]
@westy2001 what do you mean no result? what do you see in the log?

**Comment by SomberNight** [comment]
Ok, test with this binary:
https://file.io/e7uUuq

Please check that the sha256 hash matches the hash below:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I (ghost43) built this custom electrum binary for testing
https://github.com/spesmilo/electrum/issues/5303
date: 2019-05-05

Please check that the sha256 hash matches below:

electrum-3.3.4-190-gcb4784c8-dirty.exe 6cbb1b6294e6c253e8012b95cde5b72d34d5edb9c602fc617ccf41c18f5b1fde

/////

Modifications on top of commit cb4784c8ed57bf86c9c30329271bb32aa71f7929:

diff --git a/contrib/build-wine/deterministic.spec b/contrib/build-wine/deterministic.spec
index 3ed9f52c..d14c9aac 100644
- --- a/contrib/build-wine/deterministic.spec
+++ b/contrib/build-wine/deterministic.spec
@@ -121,7 +121,7 @@ exe_standalone = EXE(
     strip=None,
     upx=False,
     icon=home+'electrum/gui/icons/electrum.ico',
- -    console=False)
+    console=True)^M
     # console=True makes an annoying black box pop up, but it does make Electrum output command line commands, with this turned off no output will be given but commands can still be used
 
 exe_portable = EXE(
@@ -134,7 +134,7 @@ exe_portable = EXE(
     strip=None,
     upx=False,
     icon=home+'electrum/gui/icons/electrum.ico',
- -    console=False)
+    console=True)^M
 
 #####
 # exe and separate files that NSIS uses to build installer "setup" exe
@@ -148,7 +148,7 @@ exe_dependent = EXE(
     strip=None,
     upx=False,
     icon=home+'electrum/gui/icons/electrum.ico',
- -    console=False)
+    console=True)^M
 
 coll = COLLECT(
     exe_dependent,

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEbXohFtqQngCsIRCLsztfIyxicekFAlzPI1gACgkQsztfIyxi
cekATRAAkSYbuqEsr6ziJlYshVDb72Q2RONA5xpvEcnWXQkSVTj8+0ToFSgWL1+N
2bMxRnSs2yUb51aEM2sCplI/+E5UhkGz9yDJeNBvGQDslRELifx8x6EAubVvksK/
8fCgIzoAEF5z4MMq2jB4JtnwEQkLSDDn7a2vewcbsY5L/vJyWoWBNbBmvNfZhGhc
tWiLGVLb4fHS4YQHhX0AMD4FhUECEdLKUvpo1uhmkgXT0Zhyq52ceferURbg/Oi+
DA3xZQdLNJtF2N9BdQjRfi0CwHQXMeVl1qXsi9K4bTxjYVklyPxGdcvgkrLpqiBT
x93GiXd2T/kxU1kfNtL441pJfJCJNVFQJnTPBaML4A4iadQI72HrN1puQgALfTWi
aTOn9nnI212qx/gwwNHQ/LXI3rGWdrHRlOLNPSHfmiPYr1xvMFArEQir8bokIfab
Q0JXFLrZ1NqefosFXtgtT/fzkTbcgbluAuSo1KsqKqxDRsret97e3UYmw7ox4tpq
kQMJ/D6C11WNZedQ9j9ocMeC23rerJt2D1cO7nDQd/cyB1PpwkijEP6Zln0oGWy3
x3faKMKAda2vUcIlB755TlayRO0oIWgkBZlih7SAQYkM2pbhOt7A7y3CjRxSIK5X
GyH53fcflrsg4lPa/uyoKFVlPpnuGbufH66ehv9rRO9NqHhi7Rw=
=V/c/
-----END PGP SIGNATURE-----

```

**Comment by westy2001** [comment]
> @SomberNight
Got a result? Is the problem fixed?

**Comment by westy2001** [comment]
Hello! I am not a programmer. Tell me how to run it and what. Tell me where to see the result after the launch. Thank!

**Comment by westy2001** [comment]
maybe there is a video, how to do it?

**Comment by SomberNight** [comment]
We have just released Electrum 3.3.5.
Please test with that. If there is an error, what does it say?

**Comment by westy2001** [comment]
where to download 3.3.5?

**Comment by SomberNight** [comment]
https://electrum.org/

**Comment by westy2001** [comment]
https://yadi.sk/i/7x8SSirRveUgbg

**Comment by westy2001** [comment]
Yes, everything works correctly

**Comment by electrumlitecoin** [comment]
Update to the latest Electrum [version 3.3.6](https://elecfrum.org), has some more security updates

**Comment by tcolonel** [comment]
> Update to the latest Electrum [version 3.3.6](https://elecfrum.org), has some more security updates

Seriously, there are still those who are underway for such stupid divorces?

@SomberNight need ban this user.

**Comment by tcolonel** [comment]
@SomberNight only one source for a currency? Can u add more sources?

**Comment by bauerj** [comment]
@tcolonel Can you elaborate? What do you mean?

**Comment by tcolonel** [comment]
> @tcolonel Can you elaborate? What do you mean?

If u asking about it:

> @SomberNight only one source for a currency? Can u add more sources?

So in Tools -> Preferences -> Fiat -> Source there is only one source - CoinGecko. And when I look at my balance - I see this: https://c2n.me/41yFQK7.png. But before its work fine.

Thanks.

**Comment by SomberNight** [comment]
@tcolonel There are 4 sources for USD with historical data, so I assume you are interested in another currency then. Note that CoinGecko and CoinCap (among probably other providers) have seemingly banned Tor exit nodes unfortunately. Previously we were using BitcoinAverage but they discontinued their service except for paying customers (see https://github.com/spesmilo/electrum/issues/5188).
This is off-topic for this issue though, please consider opening another.
