### ISSUE TITLE
Use PGP signing on Release Tags

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#5304]
Given the level of targeted attacks on Electrum, it may be prudent to ensure that all official git release tags be signed by the committer as a condition of becoming an official release tag.

Tags [3.3.4](https://github.com/spesmilo/electrum/releases/tag/3.3.4), [3.3.3](https://github.com/spesmilo/electrum/releases/tag/3.3.3), [3.3.2](https://github.com/spesmilo/electrum/releases/tag/3.3.2) and  [3.3.1](https://github.com/spesmilo/electrum/releases/tag/3.3.1) are all unsigned.

Luckily [commit:b085d7c](https://github.com/spesmilo/electrum/commit/b085d7cc59281bbba9f395cb6d622f799546358b) (v3.3.3) is signed, but [commit:87c596f](https://github.com/spesmilo/electrum/commit/87c596fa1d685b9365c26b9dfabe9c566f806ea0) (v3.3.4), [commit:30845ee](https://github.com/spesmilo/electrum/commit/30845ee7769a66d736bbc3d451fc85c0d58e1ea1) (v3.3.2) and [commit:85b7129](https://github.com/spesmilo/electrum/commit/85b712967f9f66a6e2a1c4f1b8c33897da01eb51) (v3.3.1) are not.

I would think having the tag signed would be a minimum, since the tag-signing process could happen independent of whether or not the last commit of that tag was signed.  It may not always be obvious what the last commit of a release will be.

_Originally posted by @brianddk in https://github.com/spesmilo/electrum/issues/4968#issuecomment-488293612_

**Comment by SomberNight** [comment]
Well, ok, this is a reasonable request. Though note that the releases (distributed binaries, tar.gz, etc) themselves are all signed.

**Comment by SomberNight** [comment]
Turns out @ecdsa has been signing git tags all the time, his GPG pubkey was just not uploaded to his github profile.

You can test locally by running e.g. `git tag -v 3.3.4`

Now he also uploaded the key to github.

**Comment by brianddk** [comment]
> Turns out @ecdsa has been signing git tags all the time, his GPG pubkey was just not uploaded to his github profile.

Great, thank you!
