### ISSUE TITLE
after  updating  electrum wallet all coins gone

### ISSUE THREAD

**Issue by fart44** [spesmilo/electrum#5305]
after  updating  electrum wallet all coins gone
how to get back my coins?

**Comment by SomberNight** [comment]
Where did you download Electrum from?
Please copy the exact link from your browser history.

**Comment by fart44** [comment]
im allready have electrum wallet, then i want to transfere coins and from wallet coming out windows where have wraiting i need to update walet ,then i did update and start to do my tansaction but all coin was gone on diferent adress

**Comment by fart44** [comment]
im not using browser,only wallet windows

**Comment by SomberNight** [comment]
How did you download this "update" though? There must have been a linked you followed. You probably opened the link in a browser.

**Comment by fart44** [comment]
no ,after i did transaction comin out small windows then i put tere password, after comin out also small windows there was writing  install for widows ,for mac etc.

**Comment by SomberNight** [comment]
There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.

See https://github.com/spesmilo/electrum/issues/4968 and https://electrum-malware.surge.sh/

If you downloaded and used software from those phishing messages, then what you used was not Electrum. Those coins are gone.

**Comment by fart44** [comment]
hawe some posibility to get back my coins?

**Comment by fart44** [comment]
some one to simply stolen my coins and no one is responsebal for that?

**Comment by kcalvinalvin** [comment]
Unfortunately, in Bitcoin, you are your own bank. You are solely responsible for your coins.

**Comment by ecdsa** [comment]
the only thing we can do is blacklist the malicious website, if you post the URL here.

**Comment by ecdsa** [comment]
no answer, closing
