### ISSUE TITLE
Include PGP signature of tarball as an official asset of all tagged releases

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#5306]
I realize that all official releases on this git are mirrored at https://download.electrum.org/ , and that the `tar.gz.asc` files are included there for verifying the integrity of the tarball.  But given the recent targeted phishing attacks, I thought it would be prudent to ensure that all official git releases also include the same `tar.gz.asc` signature file as one of the included assets.

_Originally posted by @brianddk in https://github.com/spesmilo/electrum/issues/4968#issuecomment-488293612_

**Comment by ecdsa** [comment]
no, releases on this git are not the official releases.
the only official releases are on electrum.org
