### ISSUE TITLE
Cannot connect to RPC

### ISSUE THREAD

**Issue by hyph3nx** [spesmilo/electrum#5307]
I get authentication error when trying to connect to RPC.
username and password were set using setcon
 curl --data-binary '{"id":"curltext","method":"addrequest","params":{"amount":"3.14","memo":"test"}}' http://user:passwordPassword2@127.0.0.1:7777
127.0.0.1 - - [04/May/2019 01:17:57] code 401, message Authentication failed (bad credentials)
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 401</p>
        <p>Message: Authentication failed (bad credentials).</p>
        <p>Error code explanation: 401 - No permission -- see authorization schemes.</p>
    </body>
</html>

$electrum getconfig rpcuser   
user
$ electrum getconfig rpcpassword
passwordPassword2

netstat -a | grep 7777
tcp        0      0 localhost:7777          *:*                     LISTEN

**Comment by hyph3nx** [comment]
I am using the Electrum app image because its the only way I could figure out how to run Electrum on a server

**Comment by ecdsa** [comment]
could it be that you set username and password after starting the daemon?

**Comment by hyph3nx** [comment]
working on the new server. I didnt change password at all this time. Thanks for your help
