### ISSUE TITLE
Lost .48 BTC

### ISSUE THREAD

**Issue by bitcoin334455** [spesmilo/electrum#5309]
0.48 BTC stolen from my electrum wallet today. I don't think that electrum is trusted. 
Is there any way to refund the money?

**Comment by bauerj** [comment]
Did you install malware recently?

**Comment by bitcoin334455** [comment]
No I did't, but I updated latest version from https://electrum.org
I am sure, something on electrum. They are not secured at all.

**Comment by bauerj** [comment]
Can you send the full URL of the file you downloaded from your download history?

**Comment by bitcoin334455** [comment]
I don't have this now. I downloaded few month ago.

**Comment by bauerj** [comment]
Please post the transaction ID that stole your funds.

**Comment by bitcoin334455** [comment]
Is it refundable?

**Comment by bitcoin334455** [comment]
Transaction ID: 7eed8698268c54f877da98ceb473f620fe547c7e3579795336fabbb335e92f13

**Comment by bitcoin334455** [comment]
https://blockstream.info/tx/7eed8698268c54f877da98ceb473f620fe547c7e3579795336fabbb335e92f13

**Comment by sandrokensan** [comment]
What version of Electrum do you have? Is it 4.0?

**Comment by bitcoin334455** [comment]
This is Electrum 3.3.3

**Comment by sandrokensan** [comment]
I think Electrum is safe but Internet not, Windows is unsafe. The best way to deposit and use Bitcoin is hardware wallet. It is not safe 100% but a lot safe. 0.5 btc is a lot so you can buy a key like Trezor for 50 buck and live without pain.

There is a lot of thing that are unsafe in a PC, much less in a Trezor key.

**Comment by ecdsa** [comment]
your seed appears to have been stolen.
it is not possible to give you more details given the information you posted.

you should not expect Electrum to protect your computer against malware.
if you are not able to secure your computer, you should use Electrum with twofactor authentication, or with a hardware wallet
