### ISSUE TITLE
Block transaction from being spent

### ISSUE THREAD

**Issue by n0n0n0n0** [spesmilo/electrum#5313]
There are spam with 546 satoshis (spread attack) to identificate another victim addresses. Is there any way to block this transaction from being spent?

**Comment by bitcoingenerator** [comment]
On Windows version you can "freeze" the address by right clicking on it in the "Addresses" tab and select "Freeze"

**Comment by SomberNight** [comment]
You can freeze individual UTXOs since https://github.com/spesmilo/electrum/pull/5152
This will be in the next release.

As above though, you can already the freeze the whole address; or you can also use manual coin control to select the inputs.
