### ISSUE TITLE
Opening Electrum and Trezor ask my PIN

### ISSUE THREAD

**Issue by sandrokensan** [spesmilo/electrum#5315]
I have set Trezor that works with Electrum, I have not set a password for Electrum so at start up Electrum don't ask me any password. By the way I have Electrum that ask me Trezor's PIN: Why?

Is there any way to overcome the PIN request? Electrum have inside only public data like my public keys. The only privacy sensible data is the amount of bitcoin that I have. If that is not important for me it is useless the PIN request.

**Comment by sandrokensan** [comment]
TY. I can also non connect the Trezor device, at the pop-up that ask me to connect the hardware wallet I can answer "no". So I can read my fund and my public address (if I trust Electrum). If I want check a public address I can click on the Eye icon and by trezor I can get a safe address.

**Comment by sandrokensan** [comment]
TY. I can also non connect the Trezor device, at the pop-up that ask me to connect the hardware wallet I can answer "no". So I can read my fund and my public address (if I trust Electrum). If I want check a public address I can click on the Eye icon and by trezor I can get a safe address.

**Comment by SomberNight** [comment]
@sandrokensan Why did you reopen? Your message suggests the issue has been properly explained and resolved.

**Comment by sandrokensan** [comment]
> @sandrokensan Why did you reopen? Your message suggests the issue has been properly explained and resolved.

Yes, but It is not clear how this forum works. By the way I close and post the comment and then reload the page to see my post. TY.

**Comment by ecdsa** [comment]
the PIN is required to check that your trezor's pubkey matches with the wallet file.
you do not need to pass that check in order to open the wallet file, you can just cancel that.
if you later need to spend, you will beasked your PIN again
