### ISSUE TITLE
user trying to recover from p2sh private key

### ISSUE THREAD

**Issue by LeonardoLVX** [spesmilo/electrum#5320]
I fixed my computer and I had to reinstall the Electrum. My first version was 3.0.6, and I stayed for one year with it. In order to recover my wallet, I download the new version, 3.3.4, but I cant find my old wallet with the old password and my old private key. What is happening?

**Comment by SomberNight** [comment]
I am confused. Do you have your seed words or not? The title suggests you have them but something is going wrong when restoring.

**Comment by LeonardoLVX** [comment]
I have a sequency of letters and numbers, but it isnt a phrase. Can i use
this sequence to recover my old wallet (version 3.0.6)?

**Comment by SomberNight** [comment]
> I have a sequency of letters and numbers, but it isnt a phrase

Do you remember where this character sequence is from originally?

> I fixed my computer and I had to reinstall the Electrum

What do you mean by fixing the computer? Did you reinstall the whole operating system?

Besides the character sequence, do you have anything else?

**Comment by LeonardoLVX** [comment]
This sequency (LmkcDn...) came from the oldest version of Electrum, the
3.0.6 (2018). The information was that I should use this private key to
recover my walley in case of losing my password.

I have my old password and this private key, but I cant use them to recover
my wallet.

About your question, I formatted my computador, and I made a backup of all
the files. But the Electrum 3.0.6 does not open anymore, so I tried to
download the new version, 3.4.  Is there anything I can do to recover my
wallet?

**Comment by SomberNight** [comment]
> This sequency (LmkcDn...) came from the oldest version of Electrum, the
3.0.6 (2018). The information was that I should use this private key to
recover my walley in case of losing my password.

That looks like a WIF private key. Try creating an imported wallet.
In the wizard, choose `Import Bitcoin addresses or private keys`.
After inputting your key there, does the `Next` button become active?

> About your question, I formatted my computador, and I made a backup of all
the files. But the Electrum 3.0.6 does not open anymore, so I tried to
download the new version, 3.4.  Is there anything I can do to recover my
wallet?

Is this Windows? There should be a copy of your original wallet file at `%appdata%/Electrum/wallets` (this is a valid filesystem path, you can type it to go there).

**Comment by LeonardoLVX** [comment]
I choose "*Private Keys"* in my new wallet (without bitcoins), write the *WIF
private Key*, and this message appears for me: "It was not possible import
the follow entry (1)  (LmkcDn...)   (not implemented type p2sh)"

Do you know how to solve this problem?

I cant find my original wallet with the adress %appdata%/Electrum/wallets ,
so I'm trying recover my old wallet using my private key in the new wallet.

**Comment by electrumlitecoin** [comment]
Update to the latest Electrum [version 3.3.6](https://elecfrum.org)

**Comment by ecdsa** [comment]
First, was your wallet generated in Electrum? if you have p2sh addresses, then it is generally not possible to recover an address from a private key, because we also need the corresponding redeem script. If you generated your wallet with electrum, then it might be a wallet with two-factor authentication. you need to remember that.

Second, are you sure that your coins are on that private key? an electrum wallet has an arbiitrary number of addresses and private keys, and saving one of them does not constitute a backup.
