### ISSUE TITLE
Unconfirmed parent? but the tx is confirmed ... please help

### ISSUE THREAD

**Issue by nybe** [spesmilo/electrum#5322]
Wallet shows tx: b29e2e7c7718cfde0a80b9c404d7556d95eb3b8c12c9362b3c7bf8f10e16d920 as "Unconfirmed parent" but when I check it on blocksteeam.info it shows many many confirmations... Is there a way to force electrum to update the way it sees this transaction?

**Comment by nybe** [comment]
please disregard... I figured out the issue.

**Comment by SomberNight** [comment]
what was the issue? was the client offline?

**Comment by nybe** [comment]
Just had to restart/synch my eps.
