### ISSUE TITLE
Withdrawal ISSUE!!!

### ISSUE THREAD

**Issue by hnickens** [spesmilo/electrum#5324]
when trying to move btc in the amount of 276.41 it registers as <$6.00 randomly and i don't understand how to fix it.......need help i tried it 4 times and lost almost $20........please help

**Comment by SomberNight** [comment]
The default unit of bitcoins in Electrum is `mBTC`. `m` means `milli`, which stands for `1/1000`, it is from the International System of Units (SI).
1000 mBTC = 1 BTC
1 BTC is approx worth 6000 USD atm; so 1 mBTC is approx worth 6 USD.
Is this what's confusing to you?

**Comment by hnickens** [comment]
no sir i wish it was a noobish question like that...........i'm putting in the correct address and i checked to see if i'm using the correct currency...........i'm literally putting in the correct information........i'm wrinting .04 in btc and it has it in the output however i'm only ACTUALLY sending only the fee (i think).
https://imgur.com/a/9vuhwQC here is a visual aid
in green is the amount that i intended to send and i don't understand what is going on here

**Comment by SomberNight** [comment]
The address is highlighted in green because it is "receiving" address in your own wallet. (and yellow means "change")
You are sending coins to the same wallet.

Please double check that you are trying to send to the correct address.

**Comment by hnickens** [comment]
yes but i inputted the .04 amount but only a $4.9 payment was made.......

**Comment by SomberNight** [comment]
That 4.9 USD is the fee. As the transaction is sending coins from your wallet to your wallet, the difference from the wallet's perspective is only the fee.
