### ISSUE TITLE
Electrum says Not Connected!

### ISSUE THREAD

**Issue by edugrip** [spesmilo/electrum#5325]
I am using Version 3.1.3

and All it tells me is "Not connected". 
Tried plugging internet out and back in. 
I tried to manually enter a server's name but it  kept synchronizing.. but the number of blocks in the local copy did not change. 

If  the issue is about the OLD version of Electrum, Please suggest my How can I withdraw funds from this old versionof Electrum Installation. 

I am using Ubuntu 16.04. Electrum Wallet version is 3.1.3

Please help

**Comment by bauerj** [comment]
Hey,

no worries. Just update Electrum and you will be able to sync again.

You can download the AppImage from electrum.org and just run it.

**Comment by edugrip** [comment]
That's Great! Thankyou for help.

**Comment by bauerj** [comment]
If you can still access your wallet, sure.

**Comment by SomberNight** [comment]
see menu bar `Wallet`>`Seed`
closing this; assuming you've figured it out unless you say otherwise
