### ISSUE TITLE
balance_at_timestamp returns error

### ISSUE THREAD

**Issue by engenegr** [spesmilo/electrum#5326]
The reason is `NoneType` returned in `tx_mined_status.timestamp` when it tries to compare timestamps:

```
   if tx_mined_status.timestamp > target_timestamp:
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

I guess `get_history` must be improved.

**Comment by SomberNight** [comment]
Are you calling balance_at_timestamp from custom code? I don't see where it is called from.

**Comment by engenegr** [comment]
Right. From custom code.
