### ISSUE TITLE
ImportError: cannot import name 'set_verbosity' [Ubuntu 18.10 / Electrum 3.3.5]

### ISSUE THREAD

**Issue by repsorp** [spesmilo/electrum#5328]
Config:
Ubuntu 18.10
Kernel 4.18.0-18-generic

Electrum 3.3.5 installed with pip
'python3 -m pip install --user Electrum-3.3.5.tar.gz[fast]'

Following error message when trying to run Electrum in terminal:
~$ electrum 
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 74, in <module>
    from electrum.util import set_verbosity, InvalidPassword
ImportError: cannot import name 'set_verbosity'

Works fine (no error message) when launching Electrum application from the Dash

**Comment by SomberNight** [comment]
that traceback seems to be from an older version such as 3.3.4
try uninstalling electrum multiple times, then reinstall
```
python3 -m pip uninstall electrum
python3 -m pip uninstall electrum
python3 -m pip uninstall electrum
python3 -m pip install --user Electrum-3.3.5.tar.gz[fast]
````

**Comment by repsorp** [comment]
Perfect
Thanks
