### ISSUE TITLE
Consider relative imports in gui

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5339]
Most forks of Electrum try to avoid namespace collisions by renaming the `electrum` package to something else, e.g. `electrum_nmc`.  Unfortunately, this produces a lot of maintenance burden due to the GUI making heavy use of absolute imports; every time upstream Electrum changes an absolute import that includes the string `electrum`, forks encounter a Git merge conflict.  It would make downstream maintenance a lot easier if Electrum used relative imports instead.

For example, in https://github.com/spesmilo/electrum/blob/master/electrum/gui/qt/main_window.py , the following:

~~~
from electrum.bitcoin import COIN, is_address, TYPE_ADDRESS
~~~

Would be changed to:

~~~
from ...bitcoin import COIN, is_address, TYPE_ADDRESS
~~~

At the moment, a large supermajority of the time I spend keeping Namecoin's fork of Electrum updated with respect to upstream consists of dealing with Git merge conflicts caused by absolute imports, which (among other things) limits how much time I can spend on actually submitting useful PR's upstream.  Any chance you'd accept a PR that changes these imports to relative?

**Comment by SomberNight** [comment]
Using relative imports everywhere was briefly considered during
https://github.com/spesmilo/electrum/commit/097ac144d976eb46dff809e1809783dc78ab6d8b

We have found that using multiple dots gets confusing really quickly.
See e.g.
https://github.com/spesmilo/electrum/blob/d2a80f15a189f0de605814a5a39f6cec7ef62681/electrum/gui/kivy/uix/dialogs/tx_dialog.py#L16

This would become
```
from .....util import InvalidPassword
```

Is there maybe a workaround?
Maybe something like: (except this does not work...)
```
>>> import electrum as xxx
>>> from xxx import bitcoin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xxx'
```

**Comment by JeremyRand** [comment]
Hmm, there may be a workaround that can approximately do what your (non-working) example does.  It looks like it breaks Electrum-NMC, but I *think* that's due to poor code quality on my part (which I should fix).  I'll do some testing in the next few days and see if I can propose a workaround, will get back to you.

**Comment by JeremyRand** [comment]
Putting the following in `electrum_nmc/__init__.py` allows aliasing the imports:

~~~
import electrum_nmc
import sys
sys.modules['electrum'] = electrum_nmc
~~~

Thanks @SomberNight for pointing me in that direction.  Much less annoying than having a huge number of dots, and will allow Namecon's fork to avoid merge conflicts.

**Comment by JeremyRand** [comment]
Minor correction, I needed to do something slightly more complex to make all the unit tests pass:

~~~
import pkgutil
import importlib
import sys
electrum_nmc = importlib.import_module('electrum_nmc')
sys.modules['electrum'] = electrum_nmc
for _, name, _ in pkgutil.iter_modules(['electrum_nmc']):
    try:
        m = importlib.import_module('electrum_nmc' + '.' + name)
        sys.modules['electrum' + '.' + name] = m
    except:
        pass
~~~

I guess things like `import electrum.transaction` were getting broken when I aliased `electrum` but not `electrum.transaction`.  Anyway, the fix is now merged to Electrum-NMC and is passing all tests (and the GUI appears to function properly), so I consider this resolved.
