### ISSUE TITLE
Not reaciving payment on Electrum wallet

### ISSUE THREAD

**Issue by Dragan558** [spesmilo/electrum#5341]
I did not get the BTC that they sent two days ago, but I got this mail:
upgradebitcoin.eu@yahoo.com
To:
Dragan Jankovic

May 12 at 8:21 PM

Hello!!!

This is to let you know that your recieved bitcoin worth (0.75...) $5,023.00 has been temporarily blocked due to security protocols when receiving bitcoin from a Bitcoin VVIP premium holder.
(Why do we do this) A security checkpoint is available on every transaction made by a VVIP  premium holder. A currency converter fee of ($)310 is to be paid into your new bitcoin clearance address.

1GJHateMSGofMu2aevMKFNc21wmAp3Smgv

For the reflection of your recieved funds of 0.75btc in your wallet.

BLOCKCHAIN MANAGEMENT
All rights reserved world bank currency conversion policy. 
Do ensure to make clearance in due time.

Help us serve you better.

Can someone help me and explain what it is about.
Thanks in advance

**Comment by bauerj** [comment]
I'm sorry but this is a scam and you are (probably) not a VVIP.
