### ISSUE TITLE
BTCP Electrum 1.1.1 Wallet Not Syncing Entire Blockchain

### ISSUE THREAD

**Issue by NATURALCOIN** [spesmilo/electrum#5345]
My Electrum wallet as of May 7th appears to not be syncing the entire block chain. When I click Tools -> Network to check it reports block 525655, which is not correct. It does say connected successfully to one node, electrum.btcprivate.org on 5222 and at first glance looks like it is working normally. Not sure what the issue is or why it started around the 7th of May. The version of my wallet is 1.1.1 running on a Windows 7 x64 VM.

**Comment by wakiyamap** [comment]
It would be better to listen to btcp's electrum at this link.
https://github.com/BTCPrivate/electrum-btcp

**Comment by SomberNight** [comment]
Indeed, Electrum is for bitcoin only. Please consult the fork's repository.
