### ISSUE TITLE
zbarw download seems to have moved

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5347]
The download URL for zbarw that's in https://github.com/spesmilo/electrum/blob/master/contrib/build-wine/prepare-wine.sh#L9 ( https://sourceforge.net/projects/zbarw/files/zbarw-20121031-setup.exe/download ) now points to an HTML file.  A working URL is https://liquidtelecom.dl.sourceforge.net/project/zbarw/zbarw-20121031-setup.exe (tested with wget in a Whonix VM and got the correct hash).

**Comment by SomberNight** [comment]
The build script is not failing though.
If you `wget https://sourceforge.net/projects/zbarw/files/zbarw-20121031-setup.exe/download`, it still has the correct hash.
I suspect they check headers and if you are deemed to be a browser, you get the html file.

**Comment by JeremyRand** [comment]
The build script was failing for us at Electrum-NMC on Travis, and downloading the current URL via wget yielded an HTML file.  Looks like that behavior has reverted as of today, so I guess I'll chalk this up to a temporary misconfiguration yesterday at SourceForge.  No action needed.
