### ISSUE TITLE
incorrect payment

### ISSUE THREAD

**Issue by AntonKS** [spesmilo/electrum#5350]
I sent a bitcoin transfer to the trading platform, formed and signed a payment, 30 minutes passed, but the money was not written off, formed another payment, but it did not work, the program said that it was necessary to update the version of the wallet. Update downloaded from the link provided by the program. After the update, the payment automatically went down in history, but the wallet number in it was different! How to cancel the transfer?, I did not enter a new wallet address, an error occurred! Transfer number: bb5a2ae7d57eb82fb5bbcbfee0ee41fe9828627333c8cd2fa302ce58055507b7

**Comment by ecdsa** [comment]
you probably downloaded a fake version of electrum, from a phishing website.
what was the link you visited in orer to download the update?

**Comment by AntonKS** [comment]
Good day! Went to the link that was listed in the Annex. Here is this link 
https://electrumapp.net/download.php?file=4.0.0/electrum-4.0.0-setup.exe


>Четверг, 16 мая 2019, 19:26 +07:00 от ThomasV <notifications@github.com>:
>
>you probably downloaded a fake version of electrum, from a phishing website.
>what was the link you visited in orer to download the update?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Антон

**Comment by ja-heller** [comment]
@AntonKS 

Please mark the link as quote since it's a fake link. Do not post the link as hyperlink, since this may redirect other users to this fake version of electrum.

**Comment by AntonKS** [comment]
It's terrible, but is there a possibility to return the money?


>Пятница, 17 мая 2019, 13:45 +07:00 от Janis Heller <notifications@github.com>:
>
>@AntonKS
>Please mark the link as quote since it's a fake link. Do not post the link as hyperlink, since this may redirect other users to this fake version of electrum.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Антон

**Comment by ecdsa** [comment]
we cannot return your coins; bitcoin transactions are irreversible.
thank you for the link; we will try to have this website taken down asap

**Comment by ecdsa** [comment]
the website has been taken down

**Comment by PinonBlanco** [comment]
> the phishing website has been taken down

Not really. Same thing happened for me. And the message with the phissing link was surely displayed from Electrum app itself, not from the third party

**Comment by Osvifur** [comment]
I can confirm what PionBlanco said. I lost all my deposit when upgrading to 4.0.0 after a message asking me to do so from the Electrum app (3.3.2, Linux Mint distribution). This happened 19:29 GMT on June 1st. Website I was directed to for download was: https://www.electrumpad.com/#download and it is still up and running. Nasty trick and I totally fell for it....

**Comment by TheFuzzStone** [comment]
@Osvifur 

> Website I was directed to for download was: https://www.electrumpad.com/#download

Just a question, what format did you download your wallet from there? .**deb**? .**tar.gz**? AppImage?
