### ISSUE TITLE
unconfirmed transactions after 48hours on 3.3.5

### ISSUE THREAD

**Issue by Kilbrittain1** [spesmilo/electrum#5351]

**Comment by Kilbrittain1** [comment]
transaction not moving closer than 5 or 6kb in the mempool - 2 days i'm waiting! WTF

**Comment by ecdsa** [comment]
what do you mean?

**Comment by Kilbrittain1** [comment]
hi...i'm trying to transfer coin and its just not going! I'm on the 3.3.5 , have paid twice and rebroadcast but its still no closer to the tip. am I doing something wrong or is there a problem with the receiving address -

**Comment by ecdsa** [comment]
are you sure you are 5Kb from the tip? usually electrum shows that in Mb, nor Kb

**Comment by SomberNight** [comment]
Blocks are full, you need to pay high fees to get mined.
See https://jochen-hoenicke.de/queue/#0,4d
You can increase the fee, see https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

**Comment by Kilbrittain1** [comment]
Ya 5 mb  - ha,ah! blocks are super full if you have to wait +48hours - nightmare!

**Comment by ecdsa** [comment]
that's normal. you should bump the fee.

**Comment by Kilbrittain1** [comment]
its the longest I've ever waited - - thanks and will do
