### ISSUE TITLE
Electrum Network not connecting

### ISSUE THREAD

**Issue by hesam521** [spesmilo/electrum#536]
Hello,

I have the exact same issue as #503 - I am new to this and tried to send my bitcoins to my wallet via Coinbase.com. Coinbase said it sent successfully but nothing shows up in my Electrum wallet. It just says I am not connected, and nothing shows up when I choose Network. I am on Mac OS. Please help. I tried to send it over this morning, and it has been almost 12 hours, and still nothing.

Please contact me at your earliest convenience - thank you very much for your help

Hesam

**Comment by ab1jx** [comment]
I found this thread because mine wasn't connecting.  But by the time I got here it had without me doing anything at all.  Try just leaving it open overnight and let it work.
