### ISSUE TITLE
Нулевой баланс кошелька

### ISSUE THREAD

**Issue by ShewtsovNikolai** [spesmilo/electrum#5361]
При установке кошелька версии 3,3,6 с введением ssid и пароля кошелёк открывается.  Баланс  0. На сайте https://www.blockchain.com/btc/address/1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD все транзакции отображаются. Последняя транзакция кэш -b843948babd0d031b4a18d2529d1fa529b9d89761bc0eaf1d1771a2630b8bcb4 Баланс положительный. Как вернуть транзакции на установленный кошелёк?

**Comment by ldz1** [comment]
Please tell us more about your seed. Where it comes from? Where did you use it before?

You can try the following steps:
1. File 
2. New/Restore
3. Standard wallet
4. I already have a seed
5. Enter Seed (Options: Bip39 seed)
6. Next

Please tell us the result. 

Google translation:
Пожалуйста, расскажите нам больше о вашем семени. Откуда это? Где ты использовал это раньше?

Вы можете попробовать следующие шаги:
1. Файл
2. Новый / Восстановить
3. Стандартный кошелек
4. У меня уже есть семя
5. Введите семя (Опции: Bip39 семя)
6. Далее

Пожалуйста, сообщите нам результат.

**Comment by ShewtsovNikolai** [comment]
Кошелёк «Электрум» был установлен на ноутбуке, работал без нареканий. После переустановки ОС Windows 7 Home кошелёк не устанавливается. Проверка диска показала наличие битых секторов. При установке на стационарный компьютер [Восстановление по шагам:Файл, Новый / Восстановить, Стандартный кошелек, У меня уже есть семя, Введите семя (Опции: Bip39 семя), Далее]  - получается пустой кошелёк с нулевым балансом. Пробовал восстановить без опции Bir39, результат такой же. Есть секретная фраза (семя), есть пароль, есть номер депозита кошелька, есть транзакции на сайте https://www.blockchain.com/btc/address/1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD снимок экрана компьютера во вложенном файле.   --                Будь!      Николай Шевцов        +79885554334shewtsov.nikolai@yandex.ru   19.05.2019, 14:36, "ldz1" <notifications@github.com>:Please tell us more about your seed. Where it comes from? Where did you use it before?You can try the following steps:FileNew/RestoreStandard walletI already have a seedEnter Seed (Options: Bip39 seed)NextPlease tell us the result.Google translation:Пожалуйста, расскажите нам больше о вашем семени. Откуда это? Где ты использовал это раньше?Вы можете попробовать следующие шаги:ФайлНовый / ВосстановитьСтандартный кошелекУ меня уже есть семяВведите семя (Опции: Bip39 семя)ДалееПожалуйста, сообщите нам результат.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ShewtsovNikolai** [comment]
Стандартная установка кошелька «Electrum» в 2017 году. Предложенная контрольная фраза была сохранена и в дальнейшем успешно использовалась. Кошелёк несколько раз переустанавливался и продолжал работать. После последней транзакции прошло пол года. При очередной переустановке кошелька произошло то, что я описал в первом и втором случае. Кошелёк не отображает операции и баланс.

**Comment by ldz1** [comment]
Is your wallet connected (green circle)? I assume the 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD is your wallet address. Can you see this address in "Addresses" tab? Do you know another addresses from the old working wallet? Or would you say that the addresses in the new program are completely different than those in the old one? What about the attachment you have talked about?

I'm afraid I could not help anymore. It sounds like a user error or a bad bug (I think that's unlikely).

Google translation:
Ваш кошелек подключен (зеленый кружок)? Я предполагаю, что 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD - это адрес вашего кошелька. Вы можете увидеть этот адрес во вкладке «Адреса»? Вы знаете другие адреса из старого рабочего кошелька? Или вы бы сказали, что адреса в новой программе совершенно разные, чем в старой? Как насчет привязанности, о которой вы говорили?

Боюсь, я не мог больше помочь. Это звучит как ошибка пользователя или плохая ошибка (я думаю, что это маловероятно).

**Comment by ShewtsovNikolai** [comment]
Кошелёк подключен и синхронизирован.  1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD - это действительно адрес моего кошелька, по которому проходили все транзакции. bc1qdxae0p2eza5xh6ss4ttqakuva2tep6rurspsl4 - все адреса начинаются на символы - bc1q. Из старого рабочего кошелька сохранил только один номер и постоянно им пользовался, что видно на сайте - https://www.blockchain.com/ru/btc/address/1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD В чём заключается ошибка пользователя? Плохая ошибка? Как понять вопрос - What about the attachment you have talked about? (Как насчет привязанности, о которой вы говорили?) --                Будь!      Николай Шевцов        +79885554334shewtsov.nikolai@yandex.ru24.05.2019, 21:04, "ldz1" <notifications@github.com>:Is your wallet connected (green circle)? I assume the 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD is your wallet address. Can you see this address in "Addresses" tab? Do you know another addresses from the old working wallet? Or would you say that the addresses in the new program are completely different than those in the old one? What about the attachment you have talked about?
I'm afraid I could not help anymore. It sounds like a user error or a bad bug (I think that's unlikely).
Google translation:
Ваш кошелек подключен (зеленый кружок)? Я предполагаю, что 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD - это адрес вашего кошелька. Вы можете увидеть этот адрес во вкладке «Адреса»? Вы знаете другие адреса из старого рабочего кошелька? Или вы бы сказали, что адреса в новой программе совершенно разные, чем в старой? Как насчет привязанности, о которой вы говорили?
Боюсь, я не мог больше помочь. Это звучит как ошибка пользователя или плохая ошибка (я думаю, что это маловероятно).

**Comment by ldz1** [comment]
Your old electrum had only the "1..." addresses, right? The new installation contains only "bc1" addresses, right? 

"bc1" https://en.bitcoin.it/wiki/Bech32
https://en.bitcoin.it/wiki/Address

1. File
2. New/Restore
3. Wallet name
4. Standard wallet
5. I already have a seed
6. Enter you seed

Under the seed input box you can see "Seed Type". What Seed Type is it? I suppose "segwit". Segwit Type generates "bc1" addresses. Sorry, I do not know why you used to have "1" type addresses.

Google translation:
У вашего старого электрума были только адреса "1 ...", верно? Новая установка содержит только адреса "bc1", верно?

"bc1" https://en.bitcoin.it/wiki/Bech32
https://en.bitcoin.it/wiki/Address

1. Файл
2. Новый / Восстановить
3. Название кошелька
4. Стандартный кошелек
5. У меня уже есть семя
6. Введите свое семя

Под полем ввода семян вы можете увидеть «Тип семян». Какой это тип семян? Я полагаю, "Segwit". Segwit Type генерирует адреса "bc1". Извините, я не знаю, почему у вас были адреса типа "1".

**Comment by AbdussamadA** [comment]
If the seed was originally generated in electrum then do not use the bip39 option. The bip39 option is for seeds created by other wallet software.

Also please do answer ldz1's question regarding the seed type.

**Comment by ShewtsovNikolai** [comment]
Семя действительно было создано впервоначально в электруме. Большое спастбо за подсказку относительно опции  bip39. По поводу типа семени обязательно отвечу на вопрос ldz1. --                Будь!      Николай Шевцов        +79885554334shewtsov.nikolai@yandex.ru27.05.2019, 22:49, "Abdussamad Abdurrazzaq" <notifications@github.com>:If the seed was originally generated in electrum then do not use the bip39 option. The bip39 option is for seeds created by other wallet software.
Also please do answer ldz1's question regarding the seed type.

**Comment by ShewtsovNikolai** [comment]
Новая установка содержит действительно только адреса "bc1", верно..Какие адреса были у рабочего кошелька я затрудняюсь ответить, потому что по рекомендации авторов Electrum пользовался только одним номером (адресом). Это можно увидеть на сайте https://www.blockchain.com/ru/btc/address/1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD При очередном восстановлении кошелька: тип ввода семян - standart  Все адреса начинаются  с "1...". Первым адресом стоит 1CsPR7bUY8tS2UUuNwuWqPyBn5PBdhKj4C Моего адреса нет. Кошелёк пустой. Как восстановить баланс? --                Будь!      Николай Шевцов        +79885554334shewtsov.nikolai@yandex.ru27.05.2019, 22:24, "ldz1" <notifications@github.com>:Your old electrum had only the "1..." addresses, right? The new installation contains only "bc1" addresses, right?
"bc1" https://en.bitcoin.it/wiki/Bech32
https://en.bitcoin.it/wiki/Address

File
New/Restore
Wallet name
Standard wallet
I already have a seed
Enter you seed

Under the seed input box you can see "Seed Type". What Seed Type is it? I suppose "segwit". Segwit Type generates "bc1" addresses. Sorry, I do not know why you used to have "1" type addresses.
Google translation:
У вашего старого электрума были только адреса "1 ...", верно? Новая установка содержит только адреса "bc1", верно?
"bc1" https://en.bitcoin.it/wiki/Bech32
https://en.bitcoin.it/wiki/Address

Файл
Новый / Восстановить
Название кошелька
Стандартный кошелек
У меня уже есть семя
Введите свое семя

Под полем ввода семян вы можете увидеть «Тип семян». Какой это тип семян? Я полагаю, "Segwit". Segwit Type генерирует адреса "bc1". Извините, я не знаю, почему у вас были адреса типа "1".

**Comment by AbdussamadA** [comment]
It's hard to understand what you're saying. I suggest you try the things listed [here](https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet) especially 1c and 2b. Also [search](https://bitcoinelectrum.com/frequently-asked-questions/#how-can-i-tell-if-an-address-belongs-to-my-wallet) for your old address in your restored wallet.

If the above doesn't help find someone who is fluent in English and Russian to communicate on your behalf in this issue. There's a russian language sub-forum on bitcointalk.org where you may find suitable volunteers.

**Comment by AbdussamadA** [comment]
Oh and one last thing. Russian users have had trouble syncing with the network because of internet censorship in their country. I suggest installing and configuring tor proxy under tools > network >proxy tab.

**Comment by AbdussamadA** [comment]
Is your "seed/control phrase" 12 English words or [a wif private key](https://en.bitcoin.it/wiki/Private_key#Base58_Wallet_Import_format)?

**Comment by ShewtsovNikolai** [comment]
I have a control phrase of 12 words "Standart»  --                Be!      Nikolai Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   28.05.2009, 14:50, "Abdussamad Abdurrazzaq" <notifications@github.com>:Is your "seed/control phase" 12 English words or a wif private key ?—You are receiving this because you authorized the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ldz1** [comment]
Sorry, I don't quite follow you. You have talked about bc1 addresses in the new wallet, but you have also said your seed is "standard". It is contradictory. Then you tell about "1" addresses in the new wallet. I can not follow.

**Comment by ShewtsovNikolai** [comment]
My control phrase consists of 12 English words.  --                Be!      Nikolai Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   28.05.2009, 14:50, "Abdussamad Abdurrazzaq" <notifications@github.com>:Is your "seed/control phase" 12 English words or a wif private key ?—You are receiving this because you authorized the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ShewtsovNikolai** [comment]
Every time I try to recover Electrum wallet, I use Your tips. The control phrase of 12 words was used in the working wallet built-in "standard". Wallet synchronization passes, the circle in the lower right corner is green. In the "Addresses" tab, the number of the old working wallet is missing. 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrzd . Offered in the "network Settings" to change and configure the tor proxy. But the synchronization takes place, and the wallet number is not. For me, setting up a TOR network is a "dark forest." I am a pensioner with a disability.  What to do? --                Be!      Nikolai Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   29.05.2009, 20:28, "ldz1" <notifications@github.com>:Sorry, I don't quite follow you. You have talked about bc1 addresses in the new wallet, but you have also said your seed is "standard". It is contradictory. Then you tell about "1" addresses in the new wallet. I can not follow.—You are receiving this because you authorized the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ShewtsovNikolai** [comment]
In the restored purse "Electrum" synchronization with the network takes place. In the "Address" no address 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrzd How to find it?  --                Be!      Nikolai Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   28.05.2009, 14:45, "Abdussamad Abdurrazzaq" <notifications@github.com>:Oh and one last thing. Russian users have had trouble syncing with the network because of internet censorship in their country. I suggest installing and configuring tor proxy under tools > network >>proxy tab.—You are receiving this because you authorized the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ShewtsovNikolai** [comment]
При попытке найти старый адрес в восстановленном кошельке через консоль получаю ошибку>>ismine ("1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD")Traceback (most recent call last):^SyntaxError: invalid syntax During handling of the above exception, another exception occurred: Traceback (most recent call last):File "electrum\gui\qt\console.py", line 262, in runCommandFile "<string>", line 17wzNPu2DvkCMddAQnDDtzGCG3uhrrZD")^SyntaxError: invalid syntax --                Будь!      Николай Шевцов        +79885554334shewtsov.nikolai@yandex.ru28.05.2019, 14:40, "Abdussamad Abdurrazzaq" <notifications@github.com>:It's hard to understand what you're saying. I suggest you try the things listed here especially 1c and 2b. Also search for your old address in your restored wallet.
If the above doesn't help find someone who is fluent in English and Russian to communicate on your behalf in this issue. There's a russian language sub-forum on bitcointalk.org where you may find suitable volunteers.

**Comment by AbdussamadA** [comment]
to find out if the old address belongs to your restored wallet or not see 1b [here](https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet)

**Comment by ShewtsovNikolai** [comment]
I so understand that you are engaged in this question of restoration of a purse for a long time. Interesting to find out if someone to recover? Read all the comments on your link https://bitcoinelectrum.com/restoring-your-standard-wallet-from-seed/ the result is 0. Tried a lot of options. Still my address 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrzd in recoverable wallets is not.  --                Be!      Nikolai Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   30.05.2019, 09:02, "Abdussamad Abdurrazzaq" <notifications@github.com>:to find out if the old address belongs to your restored wallet or not see 1b here—You are receiving this because you authorized the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ShewtsovNikolai** [comment]
The old address 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD is still not displayed in the restored wallet. Balanes 0.0 remains. As I understand it, it’s useless to wait for help.

**Comment by ShewtsovNikolai** [comment]
The old address 1Cp7wzNPu2DvkCMddAQnDDtzGCG3uhrrZD is still not displayed in the restored wallet. Balanes 0.0 remains. As I understand it, it’s useless to wait for help. --                Будь!      Николай Шевцов        +79885554334shewtsov.nikolai@yandex.ru19.09.2019, 11:35, "ThomasV" <notifications@github.com>:Closed #5361.

**Comment by ecdsa** [comment]
it is difficult to help you with the information you provided

**Comment by ShewtsovNikolai** [comment]
What additional information should I provide?  --                Be!      Nikolay Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   19.09.2019, 17:02, "ThomasV" <notifications@github.com>:it is difficult to help you with the information you provided—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AbdussamadA** [comment]
Do the addresses on the addresses or receive tab begin with '1'? If the addresses tab is not visible go to view menu > show addresses.

Did you create other wallets in the past? Have you tried opening other wallets on your system? You can switch wallets via file > open or file > recently open

To search for addresses on the addresses tab press ctrl+f and paste in the address. 

Is electrum installed on a USB drive or microsd card? Were there file system or disk reliability issues recently?

**Comment by ShewtsovNikolai** [comment]
I will try to provide you with more information, although the same I have already described on the site in the comments there!1. In wallet Addresses on the addresses tab start with '1'.2. Other wallets in the past I did not create. 3. I have not tried to open other wallets in my operating system. Switch through File > Open or file >> open recently-leads to the same result-balance 0,0.4. Search for addresses on the "addresses" tab gives the result-0.5. Wallet electrum tried to install on a laptop with Windows 7, on a personal computer with Windows 8.1, problems with the file system was not observed. The result is 0.0.   --                Be!      Nikolay Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   20.09.2019, 10:42, "Abdussamad Abdurrazzaq" <notifications@github.com>:Do the addresses on the addresses tab or the receive begin with '1'? If the addresses tab is not visible go to view menu > show addresses.Did you create other wallets in the past? Have you tried opening other wallets on your system? You can switch wallets via file > open or file > open recentlyTo search for addresses on the addresses tab press ctrl+f and paste in the address.Electrum Is installed on a USB drive or microsd card? Were there file system or disk reliability issues recently?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AbdussamadA** [comment]
- Check your browser download history for the exact url you downloaded electrum from and share that with us if you can.

- There are clipboard altering malware programs now. So try copying any address from electrum and then paste it into notepad. Is it the same address you copied?

**Comment by ShewtsovNikolai** [comment]
Кошелёк загружаю с официального сайта: https://electrum.org/#download. Браузер Яндекс. В загрузках:  electrum-3.3.8-setup В свойствах файла всё необходимое присутствует.При открытии адресов в кошельке раздел "Адреса", копировании через буфер обмена и вставить в "Блокнот" символы все совпадают. Адрес тот же. --                Будь!      Николай Шевцов        +79885554334shewtsov.nikolai@yandex.ru   21.09.2019, 11:18, "Abdussamad Abdurrazzaq" <notifications@github.com>:Check your browser download history for the exact url you downloaded electrum from and share that with us if you can.There are clipboard altering malware programs now. So try copying any address from electrum and then paste it into notepad. Is it the same address you copied?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ShewtsovNikolai** [comment]
Wallet download from the official site: https://electrum.org/#download. Browser Yandex. In downloads: electrum-3.3.8-setup in properties file all necessary present.When you open the addresses in the wallet section "Addresses", copy through the clipboard and paste to Notepad the characters are all the same. Same address.  --                Be!      Nikolay Shevtsov        +79885554334shewtsov.nikolai@yandex.ru   21.09.2019, 11:18, "Abdussamad Abdurrazzaq" <notifications@github.com>:Check your browser download history for the exact url you downloaded electrum from and share that with us if you can.There are clipboard altering malware programs now. So try copying any address from electrum and then paste it into notepad. Is it the same address you copied?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AbdussamadA** [comment]
did you try increasing the gap limit?

go to view menu > show console if the console tab is hidden. Then switch to console tab and type this:

    wallet.change_gap_limit(200)

    for thing in range(1,20): wallet.create_new_address(True)

Then wait for it to synchronize and see if the balance on the history tab reflects what you expect it to.

**Comment by fourclub** [comment]
@ShewtsovNikolai нашел решение?
