### ISSUE TITLE
"Spend from" option on right click disappeared

### ISSUE THREAD

**Issue by goodc0re** [spesmilo/electrum#5370]
Electrum Bitcoin v. 3.3.6 on MacOS 

When right-clicking on a change Address or it's Label, even if the Address is unfrozen, the option to "Spend from" is no longer available. 

That was the single method I used to spend and the main reason for using Electrum, always being able to select the input(s) I want to spend from and avoiding inputs getting mixed together. 

How do I select a specific change input to spend from now? Is this a bug or was it removed?

**Comment by ecdsa** [comment]
it was not removed, but you need to select an address that actually has coins

**Comment by SomberNight** [comment]
The "spend from" option only appears if the address
- is not frozen itself
- has UTXOs that are
  - not frozen
  - mature

Also, for selecting which coins to spend, you can also use the `Coins` tab. :)
