### ISSUE TITLE
can't open LN channel from multisig/watchonly wallet

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5379]
The client will sign with the available cosigner, and then broadcast the partially signed txn as part of the channel open flow.

Conceptually this is the same issue as when opening a channel from a watch only wallet.

If during `channel_establishment_flow`, we cannot create a fully signed funding tx, the code currently will fail.
https://github.com/spesmilo/electrum/blob/c31fa059fe01a38ae5f382715283fbec5f6dca9a/electrum/lnpeer.py#L568

Note that a distinction whether the funding tx has all segwit inputs (or not) must be made:
if all inputs are segwit, we could continue the flow, and let the user export the partial funding tx, and have them broadcast it at their convenience.

**Comment by ecdsa** [comment]
here is a branch that fixes this issue:
https://github.com/spesmilo/electrum/tree/open_channel_without_signing

**Comment by SomberNight** [comment]
Nice! Indeed we could save the partial tx in the wallet as local, actually irrespective of whether it's complete or not. If it's complete then we also broadcast it; but if the server returns an error that is not handled well atm -- saving it as local ensures that the user can easily try to rebroadcast.
