### ISSUE TITLE
All HW wallet libraries required to use a single wallet.

### ISSUE THREAD

**Issue by Kixunil** [spesmilo/electrum#5380]
Electrum requires to install all HW wallet libraries even if one (or few) of them would suffice for a user that only has a single wallet.

Steps to reproduce:

* Install Electrum from Git repository
* Install Trezor python library
* Try to setup Trezor wallet

What happens:

Exception saying that libraries for all other wallets are missing.

Expected behavior:

Warning saying that the other libraries are missing, but Trezor library is present and usable. User should be allowed to setup Trezor even without e.g. Ledger library.

Electrum version: git commit e1c1a9d6a2bb2020329040a72666ff42346e3678
OS: QubesOS Fedora 26 template.

**Comment by SomberNight** [comment]
They are not required but they will flood the log with messages and traces.
I assume that is what you mean.
