### ISSUE TITLE
the program generates strange addresses to which it is impossible to send coins

### ISSUE THREAD

**Issue by RomK45** [spesmilo/electrum#5382]
the program generates strange addresses to which it is impossible to send coins
screenshots in links
[https://ibb.co/ZmdM5Wy](url)
[https://ibb.co/1dSX2hk](url)

**Comment by SomberNight** [comment]
These are bech32 bitcoin addresses. Please see https://github.com/spesmilo/electrum/issues/5371

Please complain to whoever fails to recognise these as valid addresses.

**Comment by bauerj** [comment]
Those are standard BIP173 addresses.

There might be some outdated wallets or services that don't support sending to it. If that's the case, please ask them to add support our use legacy addresses for the time being.
