### ISSUE TITLE
Нет обработки перевода

### ISSUE THREAD

**Issue by MarinaRus** [spesmilo/electrum#5383]
27.05.2019 в 10 часов 40 минут были списаны средства с кошелька Электрум на обменный ресурс https://60cek.org/. На кошелек номер: 36WFz2C7quobdPDVtvxGeEJ7baMLPW9kBx
Но обработки информации нет уже 6 часов. https://www.blockchain.com/btc/address/36WFz2C7quobdPDVtvxGeEJ7baMLPW9kBx
В чем проблема?

**Comment by bauerj** [comment]
Did you send from or to your Electrum wallet?

**Comment by MarinaRus** [comment]
Переводили средства с кошелька Electrum на другой кошелек, который указали

**Comment by bauerj** [comment]
Okay. Do you still see the transaction in your history? Can you post its ID?

**Comment by MarinaRus** [comment]
[Doc1.docx](https://github.com/spesmilo/electrum/files/3224038/Doc1.docx)

**Comment by MarinaRus** [comment]
23bbbce9db3dca9194aaa2ff2880f3a2e06d8309333adcde21ad9d1c720309c4

**Comment by bauerj** [comment]
It looks like you sent the funds to the wrong address. Do you have any idea how that could have happened?

**Comment by MarinaRus** [comment]
36WFz2C7quobdPDVtvxGeEJ7baMLPW9kBx  этот кошелек написали на сайте https://60cek.org/

**Comment by MarinaRus** [comment]
Как получить информацию на какой кошелек были переведены мои деньги???

**Comment by MarinaRus** [comment]
Как посмотреть куда переведены мои деньги?

**Comment by MarinaRus** [comment]
Чей это кошелек: 16mwxjdppK71XDvsLmYCrPAvcGYJmb3sb4  ?

**Comment by MarinaRus** [comment]
[перевод электрум-1-1.docx](https://github.com/spesmilo/electrum/files/3224203/-1-1.docx)

**Comment by MarinaRus** [comment]
это скопирован перевод который делали

**Comment by MarinaRus** [comment]
как оказалось что на другой кошелек ушли средства?

**Comment by MarinaRus** [comment]
почему средства ушли не на тот адрес который указывали?
[перевод электрум-1-1.docx](https://github.com/spesmilo/electrum/files/3224218/-1-1.docx)

**Comment by bauerj** [comment]
> как оказалось что на другой кошелек ушли средства?

Apparently so.

It was sent to 16mwxjdppK71XDvsLmYCrPAvcGYJmb3sb4. The most likely cause is that you copied the wrong address.

**Comment by MarinaRus** [comment]
[перевод электрум-1-2.docx](https://github.com/spesmilo/electrum/files/3224293/-1-2.docx)

**Comment by MarinaRus** [comment]
техподдержка сайта https://60cek.org пишет что кошелек был указан верно

**Comment by MarinaRus** [comment]
если бы кошелек указали неверный его нельзя было бы найти в поиске

**Comment by MarinaRus** [comment]
Да,все верно, кошелек указан правильный ,https://www.blockchain.com/ru/btc/address/36WFz2C7quobdPDVtvxGeEJ7baMLPW9kBx   ,так же вот транзакция,если бы кошелек был неверен ,его бы нельзя было найти в поиске
Так пишут на сайте  https://60cek.org

**Comment by MarinaRus** [comment]
как мог сам поменяться кошелек получателя платежа, автоматически что ли? я считаю, что это мошенничество! я буду на всех доступных мне сайтах в отзывах так и писать что вы мошенники.

**Comment by MarinaRus** [comment]
я буду везде в отзывах писать что вы мошенники. на всех доступных мне сайтах

**Comment by SomberNight** [comment]
What OS are you using?
What version of Electrum?
Where did you download Electrum from? Please copy exact URL from browser history.
If you know how, maybe post a hash (e.g. sha256) of the Electrum binary you have downloaded; or verify the the GPG signature.

**Comment by SomberNight** [comment]
Also, please upload a screenshot where you have Electrum open, with the `History` tab visible.

**Comment by MarinaRus** [comment]
[Doc2.docx](https://github.com/spesmilo/electrum/files/3224423/Doc2.docx)

**Comment by MarinaRus** [comment]
windows 7 prof,
Electrum 4.0.0

**Comment by MarinaRus** [comment]
[Doc3.docx](https://github.com/spesmilo/electrum/files/3224424/Doc3.docx)

**Comment by bauerj** [comment]
Please post the URL you downloaded Electrum from. It should be in your Browser's download history.

**Comment by MarinaRus** [comment]
напишите адрес официального сайта Electrum

**Comment by bauerj** [comment]
There is no version 4.0.0 on the official Electrum website. It seems like you downloaded a malware version of Electrum from an imposter website.
