### ISSUE TITLE
Phissing

### ISSUE THREAD

**Issue by 0aa123456** [spesmilo/electrum#5384]
I tried to transfer the amount from electrum to a bitcoin trade website, but when I clicked on send button it showed error message to update electrum version from 3.2.2 to 4.0.0. 

1st I checked website there had no such version I though error window message should be correct and updated the version from the link given on that error message. 

But when I login to that updated version all the amount swapped out. My condition got pity because I had earned that amount working hard since 1 year. 

I had a dream to complete from that amount but now I am feeling like I should commit suicide.

Amount was getting transferred in front or my eye and I was helpless, Can't stop it. I lost everything I had earn since 1 year. Loss is unbearable for me. Totally upset now.

**Comment by ldz1** [comment]
Please look at
https://github.com/spesmilo/electrum/issues/5350
https://github.com/spesmilo/electrum/issues/5305

"There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware."
SomberNight. 

electrum.org is the official web page.

I am afraid that no one can help. I'm sorry.

**Comment by ecdsa** [comment]
please report the theft to the police, and let us know about it (electrumdev@gmail.com)
