### ISSUE TITLE
украли деньги с кошелька

### ISSUE THREAD

**Issue by k002259** [spesmilo/electrum#5386]
Добрый день, проблема как оказывается известна, но мне была не знакома, решил отписаться и сообщить, что эта проблема имеет место быть и по сей день.
В общем хотел вывести с кошелька все свои 0.1 биткоина, но тут вылетело сообщение-предупреждение, что мне нужно обновить свой кошелек, чтобы осуществить перевод.
В этом предупреждении были ссылки на установщик нового кошелька, ну как вы понимаете я скачал "новую версию кошелька", авторизировался в нем и все... сразу же увидел как все мои несчастные 0.1 отправились какому-то более умному человеку (в отличии от меня) и собственно, вот.
Попался, я на эту удочку т.к. не знал о этой проблеме и удивило мастерство этих находчивых ребят, сообщение-предупреждение, с сылкой на скачивание от самого же кошелька не выглядела подозрительно, я и не подумал о взломе.
В общем пишу это чтобы вы были внимательнее меня и скачивали инсталлеры кошелька с сайта разработчиков, а не как я по ссылке преложеной самим же кошельком и в итоге потеряете все что у вас было на нём. А ну и как говорится не храните все яйца в одной корзинке. 
Сильно не ругайте и много помидоров не бросайте, удачного всем дня.

**Comment by peleion** [comment]
This is a well-known problem for some months now. Sorry for your loss. See:

Это известная проблема уже несколько месяцев. Сожалею о вашей потере. Увидеть:

https://github.com/spesmilo/electrum/issues/5384#issuecomment-496292824

**Comment by ecdsa** [comment]
please report the theft to the police of your jurisdiction, and email us the details of your police report (electrumdev@gmail.com)

**Comment by Asketrea1** [comment]
Greetings. Today I went into my Electrum wallet to send funds, and immediately saw the transaction a few days earlier, namely on 05.21.2020 all funds were withdrawn from my wallet in an unknown direction. Bitcoin stolen with Electrum. Funds lasted only about 8 days, an extremely unreliable wallet, some kind of scam

Stole money with Electrum 3.3.8
