### ISSUE TITLE
windows binary detected as malware. false positive

### ISSUE THREAD

**Issue by dhueys** [spesmilo/electrum#5387]
Windows Defender detects Trojan virus

**Comment by AbdussamadA** [comment]
see under "notes for windows users" on the [download page](https://electrum.org/#download).

**Comment by AbdussamadA** [comment]
also please close this issue since this is a known problem.

**Comment by SomberNight** [comment]
@dhueys Please submit it as a false positive to Microsoft
https://www.microsoft.com/en-us/wdsi/filesubmission
