### ISSUE TITLE
Leftover: Possibly unsafe / phishing hole in code (server side string shown to user)

### ISSUE THREAD

**Issue by cculianu** [spesmilo/electrum#5393]
I just caught this in Electron Cash -- and noticed you guys have this too:

https://github.com/spesmilo/electrum/blob/371e1a6ebff4cf7660edf7d586a47dfc940e4263/electrum/gui/qt/main_window.py#L1843

Note the `request.error` string comes from the server.  It can contain anything, including text that tells the user to do funny stuff.

**Comment by ecdsa** [comment]
Thanks. To clarify, we are talking about the server serving the payment request, not the electrum server. 
A server-originating string is appended to request.error here: https://github.com/spesmilo/electrum/blob/371e1a6ebff4cf7660edf7d586a47dfc940e4263/electrum/paymentrequest.py#L97

**Comment by cculianu** [comment]
Right, that is correct, so it's a minor attack surface -- probably will never happen. 

But .. a PR server is just any HTTPS server so.. it's not 10000% trusted.. hence probably shouldn't be displaying server-error strings to user.. :)

**Comment by SomberNight** [comment]
It looks to me that Bitcoin Core is doing the same:
https://github.com/bitcoin/bitcoin/blob/758c6d784da0f191c408fda97b3071dd7e1fe8a0/src/qt/paymentserver.cpp#L718-L726

Although I am not familiar with that codebase, I think the error message is displayed to the user in the GUI in a very similar fashion.

**Comment by cculianu** [comment]
Thanks for addressing this.. :)

**Comment by cculianu** [comment]
Opened an issue in core: https://github.com/bitcoin/bitcoin/issues/16154
