### ISSUE TITLE
Setting the wallet path does not work in cosole (without PyQt5)

### ISSUE THREAD

**Issue by ldz1** [spesmilo/electrum#5395]
Hello, I cannot set the -w option (WALLET_PATH) through the console. Maybe some of my points are not relevant, but I still left everything on what I did. 

My environment:
- Electrum 3.3.6
- Linux 4.19 
- Python 3.6
- System without GUI (no PyQt5)
- No users except root
- tar.gz extracted into /home/electrum/Electrum-3.3.6

Steps to reproduce:
1. Create new wallet. New wallet created at /root/.electrum/wallets/default_wallet (default path)
2. Rename default_wallet to mywallet
3. ./run_electrum listaddresses => "wallet file not found" (it's obvious)
4. ./run_electrum -w /root/.electrum/wallets/mywallet
(I have also tried ./run_electrum -w "/root/.electrum/wallets/mywallet"
5. Following error occurred:
"Error: Coult not import PyQt5 on Linux systems, you may try 'sudo apt-get install python3-pyqt5'
E | asyncio | Future exception was never retrieved
future: <Future finished exception=gaierror(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
      result = self.fn(*self.args, **self.kwargs)
   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution"

I would expect I can set the global options without PyQt5.

Thanks
ldz

**Comment by SomberNight** [comment]
If you invoke electrum CLI without a command, the default command will be executed. The default command is "gui", and the default gui is Qt. This is why if you just run the main script the Qt gui starts.

This is what is happening in your case.

What you should do is run:
```
./run_electrum -w /root/.electrum/wallets/mywallet listaddresses
```

So you should specify the wallet for each command that you run. (You might be able to use `setconfig` to set the wallet file for future CLI calls but this would most likely be really hacky)

The CLI was originally designed to be stateless, past calls should not affect future calls --- although this is not always the case now, e.g. fee/rbf/... preferences are read from the config.
-------- Original Message --------

**Comment by ldz1** [comment]
>If you invoke electrum CLI without a command, the default command will be executed. The default command is "gui", and the default gui is Qt. This is why if you just run the main script the Qt gui starts.

Thank you for explanation. 

>The CLI was originally designed to be stateless, past calls should not affect future calls --- although this is not always the case now, e.g. fee/rbf/... preferences are read from the config.

I'm not sure I understand it correctly. Maybe I ask something else from the user's point of view. Suppose the user does not have a UI and he wants to change the wallet's default name. "./run_electrum -w /root/.electrum/wallets/mywallet listaddresses". In the upper command -w works only per call, right? So, after renaming my wallet I cannot work like before and I have to set the -w parameter every time. 

Another use case. I would like to have two wallets and to switch between them. If I understand correctly, I can only have one fixed default wallet and I need to specify the -w option when working with another wallet. Is it right?

**Comment by AbdussamadA** [comment]
yes you have to specify the wallet file in the command line. electrum can't read your mind.

**Comment by ecdsa** [comment]
if you don't use the default wallet you have to set -w every time
