### ISSUE TITLE
Possible bug in upgrade version 17 code path? Not sure.. can submit a PR if you like..

### ISSUE THREAD

**Issue by cculianu** [spesmilo/electrum#5400]
Hi guys,

I've been reading over your "version 17+" upgrade code because we want to do similar in our wallet (that is, get rid of `prunted_txo`, use `spent_outpoints`, etc).

I noticed ~~two~~ one potential issue~~s~~:

1. ~~The upgrade code deserializes *all* the tx's in `self.transactions` -- and they remain deserialized in memory -- which could potentially eat tons of memory.  It was my impression that tx's in the transactions dict should remain non-deserialized whenever possible to save on memory consumption.  Note that deserialized tx's grow to 10x memory versus their raw non-deserialized counterparts.  The offending code is here:~~

https://github.com/spesmilo/electrum/blob/371e1a6ebff4cf7660edf7d586a47dfc940e4263/electrum/json_db.py#L421

~~Suggestion: do something like: `tx = Transaction(tx.raw)` to deserialize a *copy* of the tx, right above the linked line.~~

EDIT: Nevermind. I see `self.get` returns a `deepcopy` of the transactions... :)  But issue 2 below remains, perhaps!

2. The upgrade code appears to write an `int` for `prevout_n` in the `spent_outpoints` dict (second-level key) here:

https://github.com/spesmilo/electrum/blob/371e1a6ebff4cf7660edf7d586a47dfc940e4263/electrum/json_db.py#L426

Whereas the actual `spent_outpoints` dict appears to be on `prevout_hash : str -> prevout_n : str -> ...` as seen here:

https://github.com/spesmilo/electrum/blob/371e1a6ebff4cf7660edf7d586a47dfc940e4263/electrum/json_db.py#L597

Am I missing something?  I would have submitted a PR straight away but.. I just wasn't sure if I'm crazy. I can submit a PR to address this, if you like (it's basically just 2 lines of code, really).

Let me know!

**Comment by SomberNight** [comment]
Thank you for reporting this.

There was a deeper issue at play, which I hopefully fixed in https://github.com/spesmilo/electrum/commit/53d189fc7ae5994e360849a123e687bd257badc0
This made the situation difficult to analyse.

**Comment by cculianu** [comment]
Ha .. looks complex.  Thanks for fixing! :D
