### ISSUE TITLE
Electrum 3.3.6 shows "No FX rate available" at the bottom and shows "No Data" for the balances in FIAT

### ISSUE THREAD

**Issue by devtulio** [spesmilo/electrum#5404]
![Capturar](https://user-images.githubusercontent.com/51343209/58836223-92249780-862e-11e9-962d-2f3f541713dc.PNG)

**Comment by SomberNight** [comment]
Try changing the rate provider.
`Tools`>`Preferences`>`Fiat`>`Source`

**Comment by devtulio** [comment]
I tried, but there is only one option.
![Capturar](https://user-images.githubusercontent.com/51343209/58839392-10396c00-8638-11e9-8cf9-a0ab48d9b12b.PNG)

**Comment by AbdussamadA** [comment]
uncheck 'show history rates' to get more options for the data source

**Comment by devtulio** [comment]
Thank you all for your help!
uncheck 'show history rates' ;)
