### ISSUE TITLE
Android: unable to scan a multisig tx from QR code with if number of inputs > 3

### ISSUE THREAD

**Issue by gordonel** [spesmilo/electrum#5405]
OS: Android 9 Pie
Device: Google Pixel 3

Description:
I've been unable to scan transactions with more than 3 inputs on my multisig wallet, where Pixel has 1 key and the computer has the other. This might be a QR scanner limitation because none of the scanners I tried was able to pick up the QR code.

I'd suggest allowing pasting or otherwise loading raw transactions into the Android version. Adding the cosigner pool plugin would be another workaround.

**Comment by SomberNight** [comment]
Could you please clarify what the exact scenario is?
This is a 2-of-2 multisig wallet I gather? Do you create the unsigned transaction on Android or on the PC? You sign with that cosigner, and then display the QR code for the partially signed tx? And the QR code gets displayed but no camera seems to be able to scan it?

**Comment by gordonel** [comment]
@SomberNight , sorry, I did forget to include detailed steps to reproduce.

**Steps to reproduce:**
1. Create a 2-2 or 2-3 multisig with one seed on a computer and another on a phone
2. Fund the wallet with 3 transactions to create 3 UTXOs
3. Create and sign the transaction on a computer spending them all and display the partially signed tx as QR code
4. On the phone, go to Send > Camera button and attempt to scan the QR code

**Expected behaviour:**
QR code scans and the user is prompted to sign or remove the transaction

**Actual behaviour:**
QR code fails to scan

I tested this with transactions containing 3 inputs and 1 output, but have no idea how it affects transactions with a different number of outputs. My guess is that past the certain size, QR codes are not scannable by the scanner in Electrum. I'd very much like to have a cosigner pool, or loading transactions from a file, or pasting them

**Comment by SomberNight** [comment]
This is surprising to hear, as I also use Electrum in a similar config you describe, and often scan larger partial transactions. The maximum data a QR code can fit is around 3KB, which in practice e.g. can fit a 2-of-2 p2wsh multisig partially signed transaction with about 10 inputs. My Android phone is able to scan these QR codes (and it supposedly has a worse camera than the Pixel 3). What I often find to be an issue however is this maximum data the QR code can fit (according to the QR code standard).

In any case, with https://github.com/spesmilo/electrum/commit/1ebfcc0f364ecb806c0ce736a76de8a3256748fd and https://github.com/spesmilo/electrum/commit/6cf7aefe28bc2d248782623378e8eb624f744be7,
using next version you will be able to copy-paste transactions as text.
