### ISSUE TITLE
wrong bitcoin wallet from nowhere

### ISSUE THREAD

**Issue by brank57** [spesmilo/electrum#5409]
a couple days ago i sent the max amount bitcoin from my electrum wallet to my coinbase wallet. I copyied the address coinbase gave me and paste it into electrum. by tryna starting the transaction, there was an error, because i had electrum 3.3.2 and for sending bitcoin i needed to have 4.0, so i downloaded the 4.0 from the official page. by opening my wallet on electrum 4.0 there i saw, that the transaction had started, even tought there was an error on 3.3.2. By compliting the transaction i saw that my electrum wallet was empty, but on coinbase there was no info about the transaction. By cheking the transaction info on electrum, there was another address, the bitcoin were sent to. So i contacted coinbase, but they just said that they cant bring back amount not sent to one of there wallet addresses. The problem now is, before copying the wallet address of coinbase i had just an text in my clipboard. From where the unknown address? Is it maybe a fault of electrum? I never seen this address or used it for sending bitcoins. now i "lost" my bitcoins because what? I did everything right. Please help me

PS with the TID i saw the address the bitcoins were send to. Its the only transaction on the wallet. No other input, no output. There is just my amount of bitcoin on the unknown wallet.

**Comment by brank57** [comment]
the TID is 1af34b6c4412b38f73a539bcf182a7b005a4b6f1377277b7cb86c7bd86c745db

**Comment by ecdsa** [comment]
there is no version 4.0. your bitcoins have been stolen by malware.
can you post the url of the page where you downloaded that version?

**Comment by brank57** [comment]
https://electrumpad.com

**Comment by brank57** [comment]
its very funny because the official electrum wallet said to me i need to download the version 4.0

**Comment by SomberNight** [comment]
There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.

See https://github.com/spesmilo/electrum/issues/4968 and https://electrum-malware.surge.sh/

If you downloaded and used software from those phishing messages, then what you used was not Electrum. Those coins are gone.

**Comment by ecdsa** [comment]
please report the theft to the police, and email us about it (electrumdev@gmail.com)
