### ISSUE TITLE
Testnet Support

### ISSUE THREAD

**Issue by michaeljs1990** [spesmilo/electrum#541]
I would love to use electrum for my new bitcoin project however lack of testnet support drove my decision to just use bitcoind instead. Is Testnet integration in the plans for the electrum wallet?

**Comment by chris-martin** [comment]
This duplicates #21.

**Comment by knocte** [comment]
> there's a pr for testnet support in the server.
> it will probably be merged soon

Thomas, was this PR ever merged? Thanks

**Comment by ecdsa** [comment]
@knocte there is no PR, just an issue.
I guess it's worth reopening it, for segnet

**Comment by knocte** [comment]
I quoted you saying there was a PR in electrum-server, I was referring to that, not to this issue.

**Comment by ecdsa** [comment]
that quote is from 2 years ago...

**Comment by ecdsa** [comment]
I dont remember if it was merged, but this is completely irrelevant today; we need segnet.

**Comment by ecdsa** [comment]
hardcoded testnet version: https://github.com/petrkr/electrum/tree/testnet

**Comment by ecdsa** [comment]
initial testnet support: d042d6e970389f97331e9caae196bf7a3af1e293

**Comment by JikkuJose** [comment]
Is there testnet support now? I seem to getting errors complaining that `--testnet` flag is unrecognised. I just updated via `brew`.
