### ISSUE TITLE
Electrum wallet won’t send bitcoins 

### ISSUE THREAD

**Issue by alexanderthagr8** [spesmilo/electrum#5412]
Whenever I try to send bitcoins I get an error stating:( the server returned an error when broadcasting the transaction consider trying to connect to a different server, or updating electrum. 
Transaction could not be broadcast due to dust outputs.)
I have the latest version 3.3.6 and I’ve tried connecting to different servers but nothing worked PLEAS HELP I CANT USEY BITCOINS

**Comment by SomberNight** [comment]
Click `Preview` instead of `Send`; take a screenshot of the `Preview` dialog, and upload it here please.

**Comment by alexanderthagr8** [comment]
I can’t upload files to this thread

**Comment by alexanderthagr8** [comment]
![BEF43FB0-29AA-4B02-A5A6-05BCFDB08A65](https://user-images.githubusercontent.com/51498607/59149540-3702f400-89e4-11e9-9482-6a5da86cda12.jpeg)

**Comment by alexanderthagr8** [comment]
Had to switch to desktop version

**Comment by AbdussamadA** [comment]
upload it to imgur.com and share the link here.

also to switch servers you to go to tools > network > server tab, uncheck select server automatically, right click on a server and choose use server. left clicking doesn't do it.

**Comment by SomberNight** [comment]
Could it be that you have mixed up units, and e.g. entering BTC amounts instead of mBTC. That could explain the dust error.
