### ISSUE TITLE
electrum setconfig url_rewrite not working

### ISSUE THREAD

**Issue by Jozzy91** [spesmilo/electrum#5417]
Whenever I try to change the url with the following command:

`electrum setconfig url_rewrite "[ 'file///var/www/', 'https://example.com/' ]"`

I get a "true" as reply, but whenever I make a new request, it still starts with "file:///var/www/".

Solved: I missed a ":" after "file" and before "///".

EDIT: Also for some reason when I try to start a daemon and load_wallet, it says there is no daemon running even though the start command works.

It did all work before I installed the web socket server in this guide: http://docs.electrum.org/en/latest/merchant.html

Solved: Somehow it works when I just start electrum, instead of the daemon.

**Comment by ecdsa** [comment]
closing, nothing useful here
