### ISSUE TITLE
Implement Shamir backup ability for Trezor Model T

### ISSUE THREAD

**Issue by slush0** [spesmilo/electrum#5418]
Upcoming release of Trezor Model T will contain ability to create Shamir Backup and recover the seed into Trezor from such shares. It would be awesome to have support for Shamir Backup ability in create wallet / restore wallet for Trezor in Electrum, so users won't need to use official web wallet.

I kindly nominate @matejcik to implement this feature :-).

**Comment by fresheneesz** [comment]
Not sure if this might be helpful, but I found this very old post with instructions on how to do fragmented backups with electrum: https://bitcointalk.org/index.php?topic=526381.0

**Comment by SomberNight** [comment]
This is now implemented with https://github.com/spesmilo/electrum/pull/5692 merged
