### ISSUE TITLE
Implement support for SLIP 39 (Shamir backup)

### ISSUE THREAD

**Issue by slush0** [spesmilo/electrum#5419]
This is related to #5418.

It would be awesome to have the ability to (at least) recover SLIP-39 (Shamir Backup) directly into Electrum, as a disaster recovery option for users who lost an access to Trezor.

I understand Thomas is not a fan of BIP-39 and he'll probably dislike SLIP-39 for the same reasons, so I'm not proposing *creating* SLIP-39 shares by Electrum, but having the ability to recover into Electrum would be just amazing.

I kindly nominate @matejcik for this task :-).

**Comment by fresheneesz** [comment]
> Thomas is not a fan of BIP-39 and he'll probably dislike SLIP-39 for the same reasons

What reasons are those?

**Comment by SomberNight** [comment]
>> Thomas is not a fan of BIP-39 and he'll probably dislike SLIP-39 for the same reasons

> What reasons are those?

I guess this has the potential to quickly turn into off topic... :) see https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-August/013061.html

**Comment by fresheneesz** [comment]
Those seem like well thought out complaints. Is there any alternative proposal that doesn't have those issues?

**Comment by SomberNight** [comment]
As OP suggests, just as Electrum doesn't support creating BIP39 mnemonics, but does support recovering from them, we could have support for SLIP39 in a similar fashion.
A pull request that implements recovering from SLIP39 backups would be welcome.

Note that during recovery/restoring, with Electrum seeds and BIP39 seeds, there is only "one" seed to enter. With SLIP39, there are usually multiple shamir shares.
Hence this will probably involve some GUI work.

**Comment by andrewkozlik** [comment]
Has anyone started working on this? @brianddk, @matejcik? If not, then I might have a shot at this myself.
> Note that during recovery/restoring, with Electrum seeds and BIP39 seeds, there is only "one" seed to enter. With SLIP39, there are usually multiple shamir shares.
> Hence this will probably involve some GUI work.

The text box for seed entry is multiline, so we can simply ask the user to type one share per line. There is already a status label below the text box, which we can use to inform the user about the number of missing shares, invalid checksum, mismatching shares etc. So I don't think any GUI work is necessary to get this up and running. Of course if anyone wants to play around with the GUI to create a multidialog walkthrough, then that can easily go into another PR later on.

**Comment by brianddk** [comment]
@andrewkozlik go for it.  I made a little [mockup script here](https://github.com/brianddk/reddit/blob/master/python/slip39.py), but never really understood how the electrum plugin architecture worked, and my QT skills were spotty.  Here's what I imagined the GUI to look like.

![options](https://i.redd.it/6capamjkh0251.png)

**Comment by andrewkozlik** [comment]
I have a working prototype: https://github.com/andrewkozlik/electrum/tree/slip39

TODO list:
1. The UI still needs some love. One share per line in the multiline box works alright, but I am thinking of having separate text boxes, one for each share. Status messages also need some tweaking.
2. Add some tests.
3. Support SLIP-0039 in the Kivy GUI. I have no experience with Kivy. Are there any takers for this task?

So far the only GUI change is this:

![image](https://user-images.githubusercontent.com/42678794/95766911-43701e80-0cb4-11eb-976e-49972979bf99.png)

**Comment by SomberNight** [comment]
> Support SLIP-0039 in the Kivy GUI. I have no experience with Kivy. Are there any takers for this task?

The kivy GUI typically lags behind Qt in features. It's fine not to implement it there for now.

**Comment by andrewkozlik** [comment]
I finally got around to polishing the UI (screenshot below) and added unit tests.
PR: https://github.com/spesmilo/electrum/pull/6917

I should note that @matejcik would eventually like to create some kind of universal Qt plugin in our reference implementation https://github.com/trezor/python-shamir-mnemonic. So in the future you might consider switching to using the plugin instead, if you like.

![image](https://user-images.githubusercontent.com/42678794/103929187-35983100-511d-11eb-8367-dea8f9a1d37a.png)

**Comment by SomberNight** [comment]
This issue never got closed but it was implemented in https://github.com/spesmilo/electrum/pull/6917 a while ago.
