### ISSUE TITLE
using Trezor on Windows 10, getting LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by c1xx** [spesmilo/electrum#5420]
Hello,

I'm trying to connect my TREZOR-T device to Electrum 3.3.6 but without success. I get this error:
![electrum-3 3 6_2019-06-11_20-46-43](https://user-images.githubusercontent.com/24668586/59299932-2e354b00-8c8e-11e9-8a52-6ee1ee938590.png)

What can be the problem? I tried some older Electrum versions, but same issues.
On TREZOR web wallet I can connection without any problems.

Thank you,
Lukas

**Comment by c1xx** [comment]
**Issue resolved:** 

I replaced libusb.dll from this GitHub respository: https://github.com/libusb/libusb/releases/tag/v1.0.22

That's all.

Regards,
Lukas

**Comment by SomberNight** [comment]
Where did you replace it? Where was this DLL on your local filesystem? We should already be packaging that version IIRC

**Comment by c1xx** [comment]
> Where did you replace it? Where was this DLL on your local filesystem? We should already be packaging that version IIRC

I took the Electrum Setup package and replaced the "libusb.dll" in installation directory, so in "C:\Program Files (x86)\Electrum\"

**Comment by SomberNight** [comment]
I've just double-checked; we are already bundling that latest version of libusb in the Windows binaries.

The bundled dll is the file at `libusb-1.0.22.7z\MS32\dll\libusb-1.0.dll`
with sha256 hash `1269e6338da5ee738b4b4a24c091773a56559f0b515d002624e675e854c3ea3a`

Could you please try to reproduce the issue with the standalone or the portable binary?
Also, are you sure there was no other application accessing the Trezor at the same time (e.g. the webwallet)?

**Comment by c1xx** [comment]
Yes, there was not other application accesing the Trezor at the same time.
I checked my libsub-1.0.dll and sha256 hash is `67F2551E0132C21214BE01A079E9E41003B06D420DD98794E4981230D41B74BB`

I tried to use my TREZOR with standalone binary, but got same issue...

**Comment by SomberNight** [comment]
> I checked my libusb-1.0.dll and sha256 hash is 67f2551e0132c21214be01a079e9e41003b06d420dd98794e4981230d41b74bb

What is this hash for? Is this the one you downloaded and it started working with? Or is this the hash of the file you got installed alongside Electrum?

**Comment by c1xx** [comment]
> > I checked my libusb-1.0.dll and sha256 hash is 67f2551e0132c21214be01a079e9e41003b06d420dd98794e4981230d41b74bb
> 
> What is this hash for? Is this the one you downloaded and it started working with? Or is this the hash of the file you got installed alongside Electrum?

Hash for libusb-1.0.dll which I downloaded from https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z

I'm using the libusb-1.0.dll from MS64 folder (after extraction of libusb-1.0.22.7z archive)

**Comment by SomberNight** [comment]
Could you double-check that it works with the MS64 dll but not with the MS32 dll (which is what we package)?

**Comment by c1xx** [comment]
> Could you double-check that it works with the MS64 dll but not with the MS32 dll (which is what we package)?

MS32 dll is not working on my Win10 x64 OS, just MS64 is working fine.

**Comment by SomberNight** [comment]
> I'm using Windows 10 64 Bit

That's fine. AFAIU what should matter in this case is how Python was compiled. And the Python we bundle is a 32 bit Windows binary.

Could you please run the following command in the `Console` tab of Electrum:
```
import sys; print(sys.version)
```

**Comment by c1xx** [comment]
> > I'm using Windows 10 64 Bit
> 
> That's fine. AFAIU what should matter in this case is how Python was compiled. And the Python we bundle is a 32 bit Windows binary.
> 
> Could you please run the following command in the `Console` tab of Electrum:
> 
> ```
> import sys; print(sys.version)
> ```

Output is:
`3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]`

**Comment by SomberNight** [comment]
When it works, on the hardware device selection screen, what options do you see?
Do you see only `webusb`? (near end of line)
![Capture](https://user-images.githubusercontent.com/29142493/59370258-6d24d880-8d42-11e9-8201-5022e6610182.PNG)

**Comment by c1xx** [comment]
I get this:
![electrum-3 3 6_2019-06-12_19-21-43](https://user-images.githubusercontent.com/24668586/59372277-6f3d6600-8d47-11e9-9bdf-cb26cf3c72e7.png)

**Comment by SomberNight** [comment]
Ok, so it seems it does not see the device via libusb (/webusb), rather through the Trezor Bridge.

What if you delete `libusb-1.0.dll`? I imagine it still sees the device through the bridge then?

**Comment by c1xx** [comment]
> Ok, so it seems it does not see the device via libusb (/webusb), rather through the Trezor Bridge.
> 
> What if you delete `libusb-1.0.dll`? I imagine it still sees the device through the bridge then?

yes, still avaiable via **bridge**

**Comment by SomberNight** [comment]
Please [enable debug logging](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging), and see if there is anything interesting there. I am interested in the case where you don't modify the libusb dll and it fails to connect to the device.

**Comment by c1xx** [comment]
Output from logfile:

`
20190612T183740.667233Z |     INFO | logging | Electrum version: 3.3.6 - https://electrum.org - https://github.com/spesmilo/electrum
20190612T183740.679876Z |     INFO | logging | Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]. On platform: Windows-10-10.0.18362-SP0
20190612T183740.681003Z |     INFO | logging | Logging to file: C:\Users\XXXXX\AppData\Roaming\Electrum\logs\electrum_log_20190612T183740Z_18956.log
20190612T183740.681003Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20190612T183742.695714Z |     INFO | daemon | failed to connect to JSON-RPC server: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
20190612T183742.716648Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20190612T183742.724683Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20190612T183742.749782Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20190612T183742.761176Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20190612T183742.772252Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20190612T183742.776931Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20190612T183742.782051Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20190612T183742.788314Z |    DEBUG | util.profiler | Plugins.__init__ 0.0845
20190612T183742.806612Z |     INFO | network | blockchains [0]
20190612T183742.810611Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko
20190612T183742.815763Z |     INFO | network | starting network
20190612T183742.818533Z |     INFO | network | connecting to fortress.qtornado.com:50002:s as new interface
20190612T183742.860266Z |    DEBUG | util.profiler | Daemon.__init__ 0.0709
20190612T183743.163492Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
20190612T183743.608337Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.4354
20190612T183743.612121Z |     INFO | storage.WalletStorage | wallet path c:\users\XXXXX\appdata\roaming\electrum\wallets\default_wallet
20190612T183746.129472Z |     INFO | storage.WalletStorage | wallet path c:\users\XXXXX\appdata\roaming\electrum\wallets\default_wallet
20190612T183746.133460Z |     INFO | storage.WalletStorage | wallet path c:\users\XXXXX\appdata\roaming\electrum\wallets\default_wallet
20190612T183746.286416Z |     INFO | interface.[bitcoin3nqy3db7c.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183746.286416Z |     INFO | network | couldn't launch iface bitcoin3nqy3db7c.onion:50002:s -- CancelledError()
20190612T183746.433191Z |     INFO | interface.[enode.duckdns.org:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183746.434008Z |     INFO | network | couldn't launch iface enode.duckdns.org:50002:s -- CancelledError()
20190612T183746.916836Z |     INFO | interface.[fortress.qtornado.com:50002] | connection established. version: ['ElectrumX 1.12', '1.4']
20190612T183746.980613Z |     INFO | interface.[fortress.qtornado.com:50002] | set blockchain with height 580423
20190612T183746.989631Z |     INFO | interface.[fortress.qtornado.com:50002] | skipping header 580423
20190612T183746.989631Z |     INFO | network | no height for main interface
20190612T183746.997612Z |     INFO | network | switching to fortress.qtornado.com:50002:s
20190612T183747.539157Z |     INFO | network | fee_histogram [[95, 129243], [91, 108425], [60, 100271], [13, 128647], [8, 161114], [7, 849267], [6, 638059], [5, 397886], [4, 147439], [3, 452468], [2, 2175140], [1, 3105436]]
20190612T183747.540115Z |     INFO | network | fee_estimates {25: 48362, 10: 62409, 5: 68531, 2: 91078}
20190612T183747.541122Z |     INFO | network | fee_histogram [[95, 129243], [91, 108425], [60, 100271], [13, 128647], [8, 161114], [7, 849267], [6, 638059], [5, 397886], [4, 147439], [3, 452468], [2, 2175140], [1, 3105436]]
20190612T183747.541122Z |     INFO | network | fee_estimates {25: 48362, 10: 62409, 5: 68531, 2: 91078}
20190612T183747.713712Z |     INFO | interface.[electrumx.ml:50002] | connection established. version: ['ElectrumX 1.8.2', '1.4']
20190612T183747.816740Z |     INFO | interface.[electrumx.ml:50002] | set blockchain with height 580423
20190612T183747.824720Z |     INFO | interface.[electrumx.ml:50002] | skipping header 580423
20190612T183748.205873Z |     INFO | plugin.Plugins | loaded coldcard
20190612T183748.230149Z |     INFO | plugin.Plugins | loaded digitalbitbox
20190612T183748.382980Z |     INFO | plugin.Plugins | loaded keepkey
20190612T183748.425621Z |     INFO | plugin.Plugins | loaded ledger
20190612T183748.613013Z |     INFO | interface.[btc.cihar.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2a01:4f8:1c17:4099::1', 50002, 0, 0), [Errno 10061] Connect call failed ('78.46.177.74', 50002)",),)
20190612T183748.613013Z |     INFO | network | couldn't launch iface btc.cihar.com:50002:s -- CancelledError()
20190612T183748.694178Z |     INFO | plugin.Plugins | loaded safe_t
20190612T183749.098743Z |     INFO | plugin.Plugins | loaded trezor
20190612T183749.098743Z |     INFO | plugin.DeviceMgr | scanning devices...
20190612T183749.231106Z |    ERROR | trezorlib.transport | Failed to enumerate WebUsbTransport. USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
20190612T183749.266891Z |     INFO | plugins.trezor.qt.Plugin | connecting to device at bridge:7
20190612T183749.289226Z |     INFO | plugins.trezor.qt.Plugin | connected to device at bridge:7
20190612T183749.664720Z |    ERROR | plugin.DeviceMgr | failed to create client for trezor at bridge:7: TransportException('trezord: acquire/7/null failed with code 400: LIBUSB_ERROR_IO',)
20190612T183749.664720Z |     INFO | gui.qt.installwizard.InstallWizard | error getting device infos for trezor: trezord: acquire/7/null failed with code 400: LIBUSB_ERROR_IO
20190612T183750.840504Z |     INFO | interface.[VPS.hsmiths.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionRefusedError(10061, "Connect call failed ('127.0.0.127', 50002)"),)
20190612T183750.841506Z |     INFO | network | couldn't launch iface VPS.hsmiths.com:50002:s -- CancelledError()
20190612T183751.372092Z |     INFO | interface.[electrum5.hodlister.co:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20190612T183751.427942Z |     INFO | interface.[electrum5.hodlister.co:50002] | set blockchain with height 580423
20190612T183751.436904Z |     INFO | interface.[electrum5.hodlister.co:50002] | skipping header 580423
20190612T183807.291961Z |     INFO | interface.[tardis.bauerj.eu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('144.217.209.242', 50002)"),)
20190612T183807.294175Z |     INFO | interface.[b.ooze.cc:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2001:41d0:800:6cf::', 50002, 0, 0), [Errno 10060] Connect call failed ('145.239.252.207', 50002)",),)
20190612T183807.295381Z |     INFO | interface.[tomscryptos.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2a01:4f9:2a:1c8a::2', 50002, 0, 0), [Errno 10060] Connect call failed ('95.216.28.117', 50002)",),)
20190612T183807.296594Z |     INFO | network | couldn't launch iface tardis.bauerj.eu:50002:s -- CancelledError()
20190612T183807.297802Z |     INFO | network | couldn't launch iface b.ooze.cc:50002:s -- CancelledError()
20190612T183807.298798Z |     INFO | network | couldn't launch iface tomscryptos.com:50002:s -- CancelledError()
20190612T183807.323174Z |     INFO | interface.[fedaykin.goip.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('109.192.226.254', 50002)"),)
20190612T183807.324363Z |     INFO | network | couldn't launch iface fedaykin.goip.de:50002:s -- CancelledError()
20190612T183807.328466Z |     INFO | interface.[electrumx.bot.nu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('173.91.90.62', 50002)"),)
20190612T183807.329462Z |     INFO | network | couldn't launch iface electrumx.bot.nu:50002:s -- CancelledError()
20190612T183807.714248Z |     INFO | interface.[electrum.taborsky.cz:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2a01:430:17:1::ffff:1153', 50002, 0, 0), [Errno 10060] Connect call failed ('37.205.8.78', 50002)",),)
20190612T183807.719455Z |     INFO | interface.[bauerjda5hnedjam.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183807.720456Z |     INFO | interface.[hsmiths5mjk6uijs.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183807.721489Z |     INFO | network | couldn't launch iface electrum.taborsky.cz:50002:s -- CancelledError()
20190612T183807.721489Z |     INFO | network | couldn't launch iface bauerjda5hnedjam.onion:50002:s -- CancelledError()
20190612T183807.723676Z |     INFO | network | couldn't launch iface hsmiths5mjk6uijs.onion:50002:s -- CancelledError()
20190612T183808.031199Z |     INFO | interface.[vmd27610.contaboserver.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183808.031199Z |     INFO | network | couldn't launch iface vmd27610.contaboserver.net:50002:s -- CancelledError()
20190612T183808.160984Z |     INFO | interface.[dedi.jochen-hoenicke.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None),)
20190612T183808.162096Z |     INFO | network | couldn't launch iface dedi.jochen-hoenicke.de:50002:s -- CancelledError()
20190612T183810.804554Z |     INFO | interface.[electrum.leblancnet.us:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionRefusedError(10061, "Connect call failed ('205.197.210.30', 50002)"),)
20190612T183810.805552Z |     INFO | network | couldn't launch iface electrum.leblancnet.us:50002:s -- CancelledError()
20190612T183811.092450Z |     INFO | interface.[vmd30612.contaboserver.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183811.093336Z |     INFO | network | couldn't launch iface vmd30612.contaboserver.net:50002:s -- CancelledError()
20190612T183811.570044Z |     INFO | interface.[e2.keff.org:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20190612T183811.623261Z |     INFO | interface.[e2.keff.org:50002] | set blockchain with height 580423
20190612T183811.633011Z |     INFO | interface.[e2.keff.org:50002] | skipping header 580423
20190612T183816.505817Z |     INFO | network | couldn't launch iface electrum.villocq.com:50002:s -- TimeoutError()
20190612T183828.734655Z |     INFO | interface.[electrum.villocq.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2606:4700:30::681c:183f', 50002, 0, 0), [Errno 10051] Connect call failed ('2606:4700:30::681c:193f', 50002, 0, 0), [Errno 10060] Connect call failed ('104.28.24.63', 50002), [Errno 10060] Connect call failed ('104.28.25.63', 50002)",),)
20190612T183828.735689Z |     INFO | interface.[xray587.startdedicated.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('188.138.88.42', 50002)"),)
20190612T183828.735689Z |     INFO | network | couldn't launch iface xray587.startdedicated.de:50002:s -- CancelledError()
20190612T183828.737348Z |     INFO | interface.[icarus.tetradrachm.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2601:602:8a00:56d6:4b94:e3d3:1bc4:ee05', 50002, 0, 0), [Errno 10060] Connect call failed ('199.59.105.228', 50002)",),)
20190612T183828.738389Z |     INFO | network | couldn't launch iface icarus.tetradrachm.net:50002:s -- CancelledError()
20190612T183829.184423Z |     INFO | interface.[e.keff.org:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20190612T183829.239892Z |     INFO | interface.[e.keff.org:50002] | set blockchain with height 580423
20190612T183829.247216Z |     INFO | interface.[e.keff.org:50002] | skipping header 580423
20190612T183829.310293Z |     INFO | interface.[electrum.eff.ro:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2001:678:7dc:4::4', 50002, 0, 0), [Errno 10060] Connect call failed ('195.135.194.6', 50002)",),)
20190612T183829.311337Z |     INFO | network | couldn't launch iface electrum.eff.ro:50002:s -- CancelledError()
20190612T183829.408757Z |     INFO | interface.[ulrichard.ch:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('151.248.221.217', 50002)"),)
20190612T183829.410117Z |     INFO | network | couldn't launch iface ulrichard.ch:50002:s -- CancelledError()
20190612T183830.620584Z |     INFO | interface.[bitcoin.dragon.zone:50004] | connection established. version: ['ElectrumX 1.11.0', '1.4']
20190612T183830.760095Z |     INFO | interface.[bitcoin.dragon.zone:50004] | set blockchain with height 580423
20190612T183830.764087Z |     INFO | interface.[bitcoin.dragon.zone:50004] | skipping header 580423
20190612T183833.634180Z |     INFO | interface.[electrum.festivaldelhumor.org:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10061] Connect call failed ('::1', 50002, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 50002)",),)
20190612T183833.634180Z |     INFO | network | couldn't launch iface electrum.festivaldelhumor.org:50002:s -- CancelledError()
20190612T183837.229002Z |     INFO | interface.[electrum2.eff.ro:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2001:678:7dc:3::2', 50002, 0, 0), [Errno 10060] Connect call failed ('195.135.194.3', 50002)",),)
20190612T183837.229002Z |     INFO | network | couldn't launch iface electrum2.eff.ro:50002:s -- CancelledError()
20190612T183837.781118Z |     INFO | interface.[green-gold.westeurope.cloudapp.azure.com:56002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('137.117.183.106', 56002)"),)
20190612T183837.782121Z |     INFO | network | couldn't launch iface green-gold.westeurope.cloudapp.azure.com:56002:s -- CancelledError()
20190612T183837.874954Z |     INFO | interface.[electrum6.hodlister.co:50002] | disconnecting due to GracefulDisconnect('too many connected servers already in bucket 145.239.0.0/16',)
20190612T183837.875951Z |     INFO | network | couldn't launch iface electrum6.hodlister.co:50002:s -- CancelledError()
20190612T183837.925409Z |     INFO | network | couldn't launch iface electrum2.villocq.com:50002:s -- TimeoutError()
20190612T183838.217586Z |     INFO | interface.[electrum.qtornado.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None),)
20190612T183838.218544Z |     INFO | network | couldn't launch iface electrum.qtornado.com:50002:s -- CancelledError()
20190612T183838.721161Z |     INFO | interface.[vps5.hsmiths.com:50002] | connection established. version: ['ElectrumX 1.12', '1.4']
20190612T183838.750899Z |     INFO | interface.[e6.keff.org:50002] | disconnecting due to GracefulDisconnect('too many connected servers already in bucket 194.71.0.0/16',)
20190612T183838.752894Z |     INFO | network | couldn't launch iface e6.keff.org:50002:s -- CancelledError()
20190612T183839.341347Z |     INFO | interface.[vps5.hsmiths.com:50002] | set blockchain with height 580423
20190612T183839.347608Z |     INFO | interface.[vps5.hsmiths.com:50002] | skipping header 580423
20190612T183842.884599Z |     INFO | network | network: retrying connections
20190612T183847.539175Z |     INFO | network | fee_histogram [[106, 100059], [92, 145399], [83, 87736], [36, 131372], [11, 158963], [7, 994143], [6, 638656], [5, 397886], [4, 147439], [3, 452468], [2, 2176105], [1, 3105904]]
20190612T183847.539175Z |     INFO | network | fee_estimates {25: 48362, 10: 62409, 5: 68531, 2: 91078}
20190612T183850.087937Z |     INFO | interface.[electrum2.villocq.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(OSError("Multiple exceptions: [Errno 10051] Connect call failed ('2606:4700:30::681c:183f', 50002, 0, 0), [Errno 10051] Connect call failed ('2606:4700:30::681c:193f', 50002, 0, 0), [Errno 10060] Connect call failed ('104.28.24.63', 50002), [Errno 10060] Connect call failed ('104.28.25.63', 50002)",),)
20190612T183854.910563Z |     INFO | interface.[helicarrier.bauerj.eu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('5.135.68.240', 50002)"),)
20190612T183854.911562Z |     INFO | network | couldn't launch iface helicarrier.bauerj.eu:50002:s -- CancelledError()
20190612T183855.149750Z |     INFO | interface.[hsmiths5mjk6uijs.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183855.150749Z |     INFO | network | couldn't launch iface hsmiths5mjk6uijs.onion:50002:s -- CancelledError()
20190612T183859.256093Z |     INFO | interface.[electrum.mindspot.org:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('172.103.153.90', 50002)"),)
20190612T183859.256093Z |     INFO | network | couldn't launch iface electrum.mindspot.org:50002:s -- CancelledError()
20190612T183900.043646Z |     INFO | interface.[erbium1.sytes.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(TimeoutError(10060, "Connect call failed ('46.246.49.226', 50002)"),)
20190612T183900.043646Z |     INFO | network | couldn't launch iface erbium1.sytes.net:50002:s -- CancelledError()
20190612T183900.341311Z |     INFO | interface.[electrumx.ftp.sh:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(gaierror(11001, 'getaddrinfo failed'),)
20190612T183900.341311Z |     INFO | network | couldn't launch iface electrumx.ftp.sh:50002:s -- CancelledError()
`

**Comment by SomberNight** [comment]
Thanks.
So the interesting part is:

```
20190612T183749.098743Z |     INFO | plugin.Plugins | loaded trezor
20190612T183749.098743Z |     INFO | plugin.DeviceMgr | scanning devices...
20190612T183749.231106Z |    ERROR | trezorlib.transport | Failed to enumerate WebUsbTransport. USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
20190612T183749.266891Z |     INFO | plugins.trezor.qt.Plugin | connecting to device at bridge:7
20190612T183749.289226Z |     INFO | plugins.trezor.qt.Plugin | connected to device at bridge:7
20190612T183749.664720Z |    ERROR | plugin.DeviceMgr | failed to create client for trezor at bridge:7: TransportException('trezord: acquire/7/null failed with code 400: LIBUSB_ERROR_IO',)
20190612T183749.664720Z |     INFO | gui.qt.installwizard.InstallWizard | error getting device infos for trezor: trezord: acquire/7/null failed with code 400: LIBUSB_ERROR_IO
```

I guess maybe libusb (WebUsbTransport) is tried first, that fails, and that causes Bridge to fail too?
This would explain why it works without the libusb dll: it's because then the WebUsbTransport will be skipped (same if you replace the dll with the 64 bit version as then it fails sooner and again will be skipped).

What version of firmware do you have on the Trezor T?
Also, any chance you know what version of the Trezor Bridge you have installed?

**Comment by c1xx** [comment]
> What version of firmware do you have on the Trezor T?
2.1.1

> Also, any chance you know what version of the Trezor Bridge you have installed?
2.0.27

**Comment by LukAss741** [comment]
Today I started getting LIBUSB_ERROR_ACCESS error too after I restarted computer due to windows update.

Since advised approach to remove trezor from devices didn't work I updated trezor firmware and bridge to latest version.
After update I am getting different error on electrum:
![electrum](https://user-images.githubusercontent.com/8490744/59562515-f0d61200-902d-11e9-85a1-18968d66a9c7.png)

Note that if I first launch electrum and get LIBUSB_ERROR_IO and then go to https://beta-wallet.trezor.io then red box "Action was interrupted Error details: LIBUSB_ERROR_IO" appears on website too. As soon as I close electrum or reconnect trezor then https://beta-wallet.trezor.io starts working flawlessly.

Windows update might have caused some compatibility issue between electrum and trezor.

My electrum version is 3.3.6 but it behave the same also with 3.3.5
trezor T firmware version 2.1.1
trezor bridge version 2.0.27
windows 10 version 1903 (os build 18362.175)

**Comment by LukAss741** [comment]
Electrum started working after removing libusb-1.0.dll from electrum's directory.

**Comment by SomberNight** [comment]
@LukAss741 so the issue in your case specifically started after upgrading Windows?

**Comment by wakiyamap** [comment]
The same symptoms appeared here, but it fixed when I reverted the version from 1903 to 1809.

**Comment by LukAss741** [comment]
> @LukAss741 so the issue in your case specifically started after upgrading Windows?

Yes. It was one of those big updates which take about an hour to install.

**Comment by SomberNight** [comment]
Ok. Thanks for confirming. Tagging @matejcik in case it's to do with python-trezor
I'll have a closer look at this a bit later.

**Comment by c1xx** [comment]
> Ok. Thanks for confirming. Tagging @matejcik in case it's to do with python-trezor
> I'll have a closer look at this a bit later.

Means, it's an issue since latest Windows 10 update?

**Comment by cculianu** [comment]
@c1xx I believe it is.  On Windows 1803 (before latest update) it works perfectly. After.. broken.

Note: if you run Electrum as admin it will work again... They changed the permissions on USB devices.

**Comment by SomberNight** [comment]
Note that there is definitely an issue with python-trezor as well.

As established, there is an issue with Windows 10 1903, due to which the webusb transport only works with Administrator privileges.
**However, the bridge transport for some reason still works**! It would be nice to know what dark magic the Trezor Bridge does to pull this off, as I had thought it too just uses webusb under the hood.

The issue with python-trezor is that the Bridge transport will only work if you had not tried to use the WebUsbTransport first!

When we call `enumerate_devices` from python-trezor, that will try the WebUsbTransport first (well the order might depend on the python version as it is actually a set), which will fail, and **after that** the BridgeTransport will fail too.
https://github.com/trezor/trezor-firmware/blob/4938fb5461f67092c6461639751ba419dcac17b7/python/trezorlib/transport/__init__.py#L112

However if I manually disable the WebUsbTransport so it will not even get tried, then the BridgeTransport will work. (This is why when @c1xx deleted the libusb.dll, the issue suddenly went away and he could use the Bridge, see https://github.com/spesmilo/electrum/issues/5420#issuecomment-501377830)

If I run this in the Electrum console before scanning for hardware devices, then the Bridge can be used to connect to the trezor device:
```
import trezorlib
from trezorlib.transport.bridge import BridgeTransport
trezorlib.transport.all_transports = lambda: [BridgeTransport]
```

@matejcik @prusnak

**Comment by SomberNight** [comment]
> However, the bridge transport for some reason still works! It would be nice to know what dark magic the Trezor Bridge does to pull this off, as I had thought it too just uses webusb under the hood.

Oh wait, I have just realised that the Trezor Bridge is running as Administrator for me...
That's one mystery solved I guess.

**Comment by SomberNight** [comment]
Related: https://github.com/trezor/trezord-go/issues/167

**Comment by matejcik** [comment]
> Oh wait, I have just realised that the Trezor Bridge is running as Administrator for me...
> That's one mystery solved I guess.

still doesn't explain why it fails after webusb tries to enumerate.

FWIW you can also set `WebUsbTransport.ENABLED = False`, easier than overriding `all_transports`. 
I've been considering disabling all other transports when Bridge is available, but I feel that's a choice the application should make.

for Electrum, ISTM something like this would make sense:
```python
from trezorlib.transport.bridge import BridgeTransport, call_bridge
from trezorlib.transport import all_transports

try:
    call_bridge("enumerate")
    for transport in all_transports():
        if transport is not BridgeTransport:
            transport.ENABLED = False
except Exception:
    BridgeTransport.ENABLED = False
```
for added benefit, you get rid of duplicate entries when the user does have the bridge

**Comment by SomberNight** [comment]
Ok, so with https://github.com/spesmilo/electrum/commit/fb76fcc886b7c999387a6676f479678df742fdaa, we will now use only the Trezor Bridge if it is available.

@matejcik I've opted to test the Bridge on every scan instead of toggling `ENABLED` at plugin init (for instance), to gracefully handle the user installing/uninstalling the Bridge while Electrum is running. I guess it's a 100% overhead in the worst case, for each scan.

It would still be interesting to know why the bridge fails if we try with webusb first. I guess it must be some side-effect in libusb or further down the stack.
