### ISSUE TITLE
electrum won't start: hw_wallet not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by gygias** [spesmilo/electrum#5421]
Hi,

I installed Electrum 3.3.6 on Raspbian Stretch using the Liinux steps on the electrum.org downloads page, but it won't start with an error seemingly identical to #4951, which looks like it may have been closed due to unrelated comments. Mine looks like the original:
Exception: Error pre-loading electrum.plugins.hw_wallet: SystemError("Parent module 'electrum.plugins.hw_wallet' not loaded, cannot perform relative import",)

This is after installing Python 3.6.1 from source using steps, save for the version, identical to this:
https://gist.github.com/dschep/24aa61672a2092246eaca2824400d37f

I get the same error whether running from source, or the installed version. I'm not a python guy, but noticing a previous two plugins "coldcard" and "digitalbitbox" seemed to load and noting the differences, tried symlinking/renaming hw_wallet/plugin.py to hw_wallet/hw_wallet.py, which didn't help. The latest available version of Electrum from apt on this config is 2.7.9 and I had some issues with it vs. multisig wallet creation, so I'm hoping to get the latest version running.

Thank you for looking!

`user@user-MacBookPro:~$ cat electrum-issue.txt 
pi@raspberrypi:~ $ python3.6 --version
Python 3.6.1
pi@raspberrypi:~ $ python3.6 ~/.local/bin/electrum -v
I | logging | Electrum version: 3.3.6 - https://electrum.org - https://github.com/spesmilo/electrum
I | logging | Python version: 3.6.1 (default, Jun 11 2019, 00:54:12) 
[GCC 6.3.0 20170516]. On platform: Linux-4.14.98-v7+-armv7l-with-debian-9.8
I | logging | Logging to file: None
I | logging | Log filters: verbosity '*', verbosity_shortcuts ''
I | daemon | failed to connect to JSON-RPC server: unexpected EOF while parsing (<unknown>, line 0)
I/p | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
I/p | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.6/site-packages/electrum/plugin.py", line 76, in load_plugins
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__init__.py", line 1, in <module>
    from .plugin import HW_PluginBase
SystemError: Parent module 'electrum.plugins.hw_wallet' not loaded, cannot perform relative import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/bin/electrum", line 357, in <module>
    plugins = init_plugins(config, config.get('gui', 'qt'))
  File "/home/pi/.local/bin/electrum", line 265, in init_plugins
    return Plugins(config, gui_name)
  File "/home/pi/.local/lib/python3.6/site-packages/electrum/util.py", line 356, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
  File "/home/pi/.local/lib/python3.6/site-packages/electrum/util.py", line 352, in do_profile
    o = func(*args, **kw_args)
  File "/home/pi/.local/lib/python3.6/site-packages/electrum/plugin.py", line 64, in __init__
    self.load_plugins()
  File "/home/pi/.local/lib/python3.6/site-packages/electrum/plugin.py", line 78, in load_plugins
    raise Exception(f"Error pre-loading {full_name}: {repr(e)}") from e
Exception: Error pre-loading electrum.plugins.hw_wallet: SystemError("Parent module 'electrum.plugins.hw_wallet' not loaded, cannot perform relative import",)
pi@raspberrypi:~ $ cat ~/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__init__.py 
from .plugin import HW_PluginBase
from .cmdline import CmdLineHandler
pi@raspberrypi:~ $ find /home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/cmdline.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/qt.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/coldcard.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/__init__.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/__pycache__
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/__pycache__/cmdline.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/__pycache__/qt.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/__pycache__/coldcard.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/coldcard/__pycache__/__init__.cpython-36.pyc
pi@raspberrypi:~ $ find /home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/cmdline.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/qt.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/digitalbitbox.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/__init__.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/__pycache__
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/__pycache__/cmdline.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/__pycache__/qt.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/__pycache__/digitalbitbox.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/digitalbitbox/__pycache__/__init__.cpython-36.pyc
pi@raspberrypi:~ $ find /home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/plugin.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/cmdline.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/qt.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__init__.py
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__pycache__
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__pycache__/plugin.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__pycache__/cmdline.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__pycache__/qt.cpython-36.pyc
/home/pi/.local/lib/python3.6/site-packages/electrum/plugins/hw_wallet/__pycache__/__init__.cpython-36.pyc
`

**Comment by SomberNight** [comment]
Could you try modifying the source (path visible in your trace/logs) by deleting these two lines:
https://github.com/spesmilo/electrum/blob/c7b64f4794bbd9dd8a2b44046039c26d36d1db67/electrum/plugins/hw_wallet/__init__.py#L1-L2
(leaving the file empty)

also delete the `__pycache__` folder in the same folder (`.../electrum/plugins/hw_wallet/__pycache__`)

**Comment by SomberNight** [comment]
Ok, I've reproduced by compiling python 3.6.1 and installing electrum 3.3.6 from tar.gz via pip.
Not sure if this only happens on older python 3.6.x such as 3.6.1

**Comment by gygias** [comment]
I tried this, and now it starts up, thank you!

For anyone with this issue [on raspbian], I couldn't find PyQt5 available from a package manager, but was able to install from source, updating the source URLs, by referring to:
https://stackoverflow.com/questions/55062050/install-pyqt5-on-raspberry-for-python3-6
