### ISSUE TITLE
getprivatekeys gives no error but a random key if called on non existing address

### ISSUE THREAD

**Issue by federicoon** [spesmilo/electrum#5422]
I'm using Electrum 3.3.6 on Ubuntu 19.04
If I run:

`electrum getprivatekeys <address>`

and the given address does not belong to my wallet, then the command does not print any error message, rather it gives an apparently random private key:

`p2pkh:L123xy[...]`

Furthermore, if the command is passed a random string (i.e. not a valid bitcoin address), then an array is returned, whose length is the same as the string's lenght, and whose elements are all identical to the above mentioned private key:

`electrum getprivatekeys abcd

[
    "p2pkh:L123xy[...]",
    "p2pkh:L123xy[...]",
    "p2pkh:L123xy[...]",
    "p2pkh:L123xy[...]"
]`

I'd expect the command would report an error message about wrong address in both cases.

**Comment by SomberNight** [comment]
Thank you for reporting this.
The private key is not random; it's for the xprv itself.

**Comment by federicoon** [comment]
Thank you for fixing the issue so quickly!
