### ISSUE TITLE
Electrum websocket can't establish a connection to the server at wss://ip:9999

### ISSUE THREAD

**Issue by Jozzy91** [spesmilo/electrum#5423]
I followed this guide to install electrum as a merchant: http://docs.electrum.org/en/latest/merchant.html

I am stuck after this setting up electrum websocket.

```
electrum setconfig websocket_server example.com

electrum setconfig websocket_port 9999
```

When I create a payment and check in the firefox console I see this:

> Firefox can't establish a connection to the server at wss://192.168.2.41:9999

I haven't changed any configs or opened any ports, since I am pretty new to websockets. The only thing I know is it isn't working. Also I can't see the ports being open with netstat. I don't know if that is a problem.

**Comment by ecdsa** [comment]
this issue is deprecated. 
websockets are now handled by asyncio and use the default port

**Comment by aneesh2usman** [comment]
i have same issue the websocket port not open 
i check :
netstat -anp | grep 9999
 return Nothing
