### ISSUE TITLE
appimage build fails to open block explorer in browser when instructed by the user, but works fine in non-appimage installation.

### ISSUE THREAD

**Issue by rbrooklyn** [spesmilo/electrum#5425]
When right clicking a transaction in the history tab, the user is presented with a "view on block explorer" option.

On appimage build of Electrum, the following error is displayed in the terminal:

> kde-open5: /tmp/.mount_electrkqyQs4/usr/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5)
> kde-open5: relocation error: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference

When opening during a non-appimage installation of Electrum (in this specific case, downloading the source and running "python3 Electrum-3.3.6/run_electrum") , the software behaves as expected and Firefox opens the block explorer to the relevant address without any error messages.

This might be a issue specific to KDE, which is the desktop I am using.

**Comment by cculianu** [comment]
we have a similar problem on Electron Cash which we just noticed too.

The solution is to not remove the qt dbus stuff and leave it in the AppImage AppDir.

@SomberNight  -- We will make a patch to Electron Cash soon that does this and I will link it here so you can use it for inspiration if you want...

**Comment by cculianu** [comment]
This happens on Electron Cash too. I thought it was due to us removing qt dbus stuff but that's not it.  If we figure it out I'll write here later...

**Comment by cculianu** [comment]
See the referenced pull request for Electron Cash.  Turns out LD_LIBRARY_PATH was picking up stuff from appimage in kde.  The workaround was to unset LD_LIBRARY_PATH when opening a link in a fork of the process.

This workaround can easily be ported to Electrum...
