### ISSUE TITLE
payto should support coin selection

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5430]
It would be useful if the `payto` RPC command (and related commands like `paytomany`) accepted an argument `from_coins` that permitted the user to choose the coins used by `_mktx` instead of calling `self.wallet.get_spendable_coins`.  This functionality is already available in the Qt GUI via right-clicking on a coin and clicking `Spend`, and it would be great to try to keep the RPC interface at feature parity with the Qt GUI when feasible.

(I might even be up for submitting a PR for this, once my other pending PR is out of the way.)

**Comment by JeremyRand** [comment]
Currently working on a PR for this; will submit soon.

**Comment by ecdsa** [comment]
hi, could you rebase that pull request? thanks
