### ISSUE TITLE
transaction confirmed but no coin in wallet. help me please

### ISSUE THREAD

**Issue by alexreipol** [spesmilo/electrum#5431]
The transaction has been confirmed and there are Bitcoin coins in the account, but I don’t have them in the history. in the receiving window it says about the status of pending, but in fact the payment went through what to do?

**Comment by alexreipol** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/51899569/59579916-c2ad0c80-90d7-11e9-88ce-596358882b11.png)
![Screenshot_2](https://user-images.githubusercontent.com/51899569/59579918-c3de3980-90d7-11e9-8c10-5ff6343583d8.png)

**Comment by alexreipol** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/51899569/59579954-e6705280-90d7-11e9-87aa-05181fded18b.png)

**Comment by ecdsa** [comment]
the destination addresses in your screenshots do not match.
the coins were sent to another address, not to your wallet

**Comment by alexreipol** [comment]
so I had this address I would not write it here !!!

**Comment by alexreipol** [comment]
so I ask for a transaction without history and this address. As soon as I bought the coins, I threw everything into cold storage on the flash drive and forgot for a while about it, then I went in here !!!

**Comment by ecdsa** [comment]
might be user error or malware.
