### ISSUE TITLE
How to verify GPG signatures without installing third-party software like GPG Suite?

### ISSUE THREAD

**Issue by wzup** [spesmilo/electrum#5436]
The developer himself suggests to use third-party tool "GPG Suite" in order to verify its software Electrum on MacOS

Instruction to GPG Suite says I have to install it on my computer first. Which I don't want to do.

How to verify GPG signatures without installing third-party software? Are there any online solutions?

**Comment by ldz1** [comment]
https://en.wikipedia.org/wiki/GNU_Privacy_Guard
The tool is available on the Linux system by default. Yo can also install it for mac.

**Comment by peleion** [comment]
GPGtools (which GPG suite is based on) is an open source project and you can compile it yourself if that is what bothers you:

https://github.com/GPGTools/MacGPG2

There is no 3rd party online solution that I know of. Wouldn't you just be trusting some random internet site to verify your software if it existed? Much better to have the verification software installed locally.
