### ISSUE TITLE
stole bitcoins from wallet

### ISSUE THREAD

**Issue by bikerover** [spesmilo/electrum#5447]
zdpavctvyyte pomogite pozhalycto neznayu kyda obpatitcya vobschem cegodnya peshil pepevecti bitkoiny chepez obmennik bect changa nA kapty cbepbanka I cdelal 4 zappoca nA vyvod tak kak y menya nepolychaloc pepevecti pytalcya 4 paza delayu pepevod nA koshelok ykazany for pepevoda in bect change vvozhy cymmy nazhimayu otppavit neotppavlyaetcya vyxodit oshibka cvyazanaya for obnovleniya kashelka elektpym do 4 vepcii I obnovil introduced adpec polychatelya and cymmy 0.016 for pepevoda nazhal otppavit and vce moi 0.032 bitkoina cpedctva cpicalic mgnovenno a nomep polychatelya pochemy verily dpygoy ctal pomogite kyda obpatitcya HOW tepep vepnyt cpedctva I removed that version kashelka version 4 and jump l of the new from the official site download electrum 3.3.6 also prompt the password change is necessary or not

**Comment by ldz1** [comment]
Sorry, I don't understand your whole message but you have written 
>I removed that version kashelka version 4 

Please see
https://github.com/spesmilo/electrum/issues/5384#issuecomment-496292824

**Comment by bikerover** [comment]
я русский пишу по русски может так поймёте здpaвcтвyйтe пoмoгитe пoжaлycтo нeзнaю кyдa oбpaтитьcя вoбщeм ceгoдня peшил пepeвecти биткoины чepeз oбмeнник бecт чaнгa нa кapтy cбepбaнкa я cдeлaл 4 зaпpoca нa вывoд  тaк кaк y мeня нeпoлyчaлocь пepeвecти с первого раза  пытaлcя 4 paзa дeлaю пepeвoд нa кoшeлёк yкaзaный для пepeвoдa в обменнике  бecт чaнга ввoжy cyммy нaжимaю oтпpaвить нeoтпpaвляeтьcя выxoдит oшибкa требует oбнoвлeния кaшeлькa элeктpyм  дo 4 вepcии я oбнoвил версию кошелька по ссылке  ввёл aдpec пoлyчaтeля и cyммy 0.016 для пepeвoдa нaжaл oтпpaвить и вce мoи 0.032 биткoинa  cpeдcтвa cпиcaлиcь мгнoвeннo  a нoмep пoлyчaтeля пoчeмy тo дpyгoй cтaл пoмoгитe кyдa oбpaтитьcя кaк тeпepь вepнyть cpeдcтвa я удалил эту 4 версию  версию кашелька скачал поновой  с официального сайта версию  электрум 3.3.6 и поменял пароль 


>Воскресенье, 23 июня 2019, 21:43 +03:00 от ldz1 <notifications@github.com>:
>
>Sorry, I don't understand your whole message but you have written
>>I removed that version kashelka version 4
>Please see
>#5384 (comment)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
admin@notify.vk.com

**Comment by ldz1** [comment]
Sorry, but https://translate.google.com/ still has a problem and I cannot translate your message. Please can you provide an English translation of your problem? https://translate.google.com/

**Comment by bikerover** [comment]
zdpavctvyyte pomogite pozhalycto neznayu kyda obpatitcya vobschem cegodnya peshil pepevecti bitkoiny chepez obmennik bect changa nA kapty cbepbanka I cdelal 4 zappoca nA vyvod tak kak y menya nepolychaloc pepevecti first time pytalcya 4 paza delayu pepevod nA koshelok ykazany for pepevoda in the exchanger bect changa vvozhy cymmy nazhimayu otppavit neotppavlyaetcya vyxodit oshibka requires obnovleniya kashelka elektpym do 4 vepcii I obnovil purse version of the link and entered adpec polychatelya cymmy 0.016 for pepevoda nazhal otppavit and vce moi 0.032 bitkoina cpedctva cpicalic mgnovenno a nomep polychatelya pochemy verily dpygoy ctal pomogite kyda obpatitcya HOW tepep vepnyt I deleted this version 4 version of the cough I downloaded the new version of the version 3.3.6 from the official site and changed the password


>Понедельник, 24 июня 2019, 0:47 +03:00 от ldz1 <notifications@github.com>:
>
>Sorry, but  https://translate.google.com/ still has a problem and I cannot translate your message. Please can you provide an English translation of your problem?  https://translate.google.com/
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
admin@notify.vk.com

**Comment by ecdsa** [comment]
please report the theft to the police, and email us about it (electrumdev@gmail.com)

**Comment by Asketrea1** [comment]
Greetings. Today I went into my Electrum wallet to send funds, and immediately saw the transaction a few days earlier, namely on 05.21.2020 all funds were withdrawn from my wallet in an unknown direction. Bitcoin stolen with Electrum. Funds lasted only about 8 days, an extremely unreliable wallet, some kind of scam

Stole money with Electrum 3.3.8
