### ISSUE TITLE
My BTC Was sent to the wrong address but i copy and paste the correct address in???

### ISSUE THREAD

**Issue by AGway** [spesmilo/electrum#5448]
Hello, I had 0.0033btc on my account transfering it to my other btc account 3AzJUFU.... i pasted 3AzJUFU... address in but when i click details after i clicked send on my now confirming coin. It was sent to a completely different btc address. i was waiting all week to do this transaction but its now sent to the wrong address even tho i pasted the correct one in...... wtffff

**Comment by ecdsa** [comment]
check whether you downloaded Electrum from electrum.org

**Comment by ecdsa** [comment]
hello, can you please check if this is another case of phishing?

**Comment by ecdsa** [comment]
removing the maybe-malware label, because we are waiting for an answer.
I think it is more likely another case of phishing

**Comment by ecdsa** [comment]
closing, op did not follow-up
