### ISSUE TITLE
BSV transaction

### ISSUE THREAD

**Issue by JL258** [spesmilo/electrum#5449]
I have made one transaction from bitfinex to Electrum last friday. In Bitfinex appears as confirmed and in Electrum didnt appear the tokens (BSV). I have checked in blockchair and appears 395 confirmations but still is increasing…. how is this possible? Can somebody help me? Thanks in advance

**Comment by SomberNight** [comment]
Electrum only supports bitcoin.
There is a fork of Electrum for BSV, but it's **not maintained by us**: [ElectrumSV](https://github.com/electrumsv/electrumsv)

**Comment by JL258** [comment]
sorry I wanted to say to Electron Clash
