### ISSUE TITLE
Required Security Update (v4.0.0) Money locked in account

### ISSUE THREAD

**Issue by bgreen12** [spesmilo/electrum#5450]
So i deposited money into my wallet that i have used fine for ages, when i go to send the bitcoins i get this message "Required Security Update (v4.0.0)" and it wont let me send them PLEASE HELP!!!
![317f6fe75de8de2ea38e8c590045f76f](https://user-images.githubusercontent.com/52167368/60026715-008bd100-9694-11e9-997c-6d4af03079ba.png)

**Comment by SomberNight** [comment]
Do not follow those links. They are malware. (see https://github.com/spesmilo/electrum/issues/4968)

You should update from the official site ([https://electrum.org/](https://electrum.org/))

**Comment by bgreen12** [comment]
I haven't, so if i update is should work?

**Comment by SomberNight** [comment]
Yes.
You might also need to change server; but in any case you should update (from official site!) first.

**Comment by bgreen12** [comment]
All fixed thank you.

**Comment by SaintPatricksCoin** [comment]
Hey! I'm using Cointiply to earn free Bitcoin every day, use this link to join and start earning: https://cointiply.mobi/Szi1

- #SaintPatricksCoinpot@gmail.com
