### ISSUE TITLE
Electron clash

### ISSUE THREAD

**Issue by JL258** [spesmilo/electrum#5451]
I have made one transaction from bitfinex to Electrum last friday. In Bitfinex appears as confirmed and in Electron clash didnt appear the tokens (BSV). I have checked in blockchair and appears 395 confirmations but still is increasing…. how is this possible? Can somebody help me? Thanks in advance

**Comment by SomberNight** [comment]
already answered in https://github.com/spesmilo/electrum/issues/5449#issuecomment-505016332
