### ISSUE TITLE
Lost bitcoin

### ISSUE THREAD

**Issue by lukespear** [spesmilo/electrum#5456]
Basically I transferred bitcoin into my electrum wallet from coinbase. All went fine. However, I then sent it on to another receiving address and despite saying its had 20 confirmations there is no sign of it. This has already happened to my mate as well (the exact same thing). When I look at the output I definitely got it right so can anyone explain what happened?

**Comment by AbdussamadA** [comment]
right click on the transaction on the history tab and choose to view details. post the transaction id contained at the top of the window that shows up. it's a large hexadecimal number. also post the intended recipient's address and amount.

**Comment by Amitie10g** [comment]
¿Have you downloaded a such Electrum 4.0? That version does not exist; you may be downloaded malware.

Please post the link you downloaded Electrum. If it is not electrum.org, report it.

**Comment by ecdsa** [comment]
closing, no answer
