### ISSUE TITLE
Android: missing documentation about "./contrib/make_apk release"

### ISSUE THREAD

**Issue by dalijolijo** [spesmilo/electrum#5457]
I missing documentation about ``./contrib/make_apk release``  - expected [here].(https://github.com/spesmilo/electrum/blob/master/electrum/gui/kivy/Readme.md)

https://github.com/spesmilo/electrum/blob/4fc43da3444ce2ec3e09e333a9056576a1cf58dd/contrib/make_apk#L24-L31

Where I get the .keystore file?
What is the difference between debug and release version?

**Comment by SomberNight** [comment]
See these links:
https://stackoverflow.com/questions/38864358/difference-between-debug-and-release-apks
https://developer.android.com/studio/build/building-cmdline
https://developer.android.com/studio/build/building-cmdline#sign_cmdline
https://github.com/kivy/kivy/wiki/Creating-a-Release-APK

**Comment by SomberNight** [comment]
addressed in https://github.com/spesmilo/electrum/commit/baa02936207e5fdfbad446bf635d5d032f7cb398
