### ISSUE TITLE
Bitcoins sent from Electum but not received by Bitpanda

### ISSUE THREAD

**Issue by EGerbracht** [spesmilo/electrum#5458]
As the title says:I sent money from electrum (version 4.0.0) and the exit was verified. Nevertheless Bitpanda, from which I used the receiving address, has not acknowledged any Bitcoins received.

**Comment by SomberNight** [comment]
I'm sorry but there is no Electrum version 4.0.0.
The latest at the moment is 3.3.6, as can be seen in this repository and on the official website (https://electrum.org/)
You must have download malware that disguises itself as Electrum.

**Comment by EGerbracht** [comment]
And what should I do now? Is there any hope in recovering the bitcoins?

**Comment by ecdsa** [comment]
there is no version 4.0. you have downloaded malware.
you should report the theft to the police, and notify us (electrumdev@gmail.com)

**Comment by EGerbracht** [comment]
With which kind of information should I contact electrumdev@gmail.com ?

**Comment by ecdsa** [comment]
We have reported the phishing to german law enforcement, and we forward user reports to them. You may send us your identity, the transaction ID of the theft, in which jurisdiction you contacted the police, and any other information you find relevant
