### ISSUE TITLE
Lost BCT

### ISSUE THREAD

**Issue by tinhhn2** [spesmilo/electrum#5464]
Sent bitcoin to remitano and 100% put in the correct address and triple checked it and then after I sent it the address changed and it was sent somewhere else . Can anything be done?

**Comment by tinhhn2** [comment]
My wallet: 19bD3GqP6Lf7cvunnF9hi2ezfd5LZAthZr
Pay to: 3LhwVxsxuPJXiyKFjiyJV2LTJzidi9L1Wa
But receive: bc1qcla39fm0q8ka8th8ttpq0yxla30r430m4hgu3x
transaction: https://www.blockchain.com/btc/tx/d95565449760cd41820bb1223ca5fa54c54e5fe7e587d60c1919102da3b73454

**Comment by ecdsa** [comment]
this is another case of phishing. user reported using "version 4.0" in #5463

**Comment by ecdsa** [comment]
@tinhhn2 please report the theft to the police of your jurisdiction, and email us the police complaint number once you have done so. electrumdev@gmail.com
