### ISSUE TITLE
stolen bitcoin from electrum

### ISSUE THREAD

**Issue by Milos19** [spesmilo/electrum#5466]
all btc was stolen from my electrum wallet. Now I know becouse of Electrum 4.0.  But what about other electronic wallets? Can they steal BTCs from other wallets, or BTCs against this virus, which I downloaded into the electrum wallet in a safe? Today I noticed that all of the Bittrex foreign exchange was gone. Is it possible for them to steal these, too? I have already sent a question to Bittrex but so far no answer. Thank you

**Comment by bauerj** [comment]
Now that the virus is installed on your computer, it is not safe to use it any more. You should either restore to a clean backup or reinstall the operating system altogether.

It is possible that the malware also affects other wallets so you should take action against that now.

**Comment by Milos19** [comment]
I was afraid of that. thank you very much for answer
