### ISSUE TITLE
[BUG] Electrum doesnt work with wallet with more than 100k address

### ISSUE THREAD

**Issue by jackalmeida** [spesmilo/electrum#5468]
[BUG] Electrum doesnt work with wallet with more than 100k address.

This is our company's electrum wallet which has more than 100k address, and we have more than 100 BTC balance in this wallet.
We run electrum from the GitHub python latest source code today (2019/06/28)

and we used a Server which has no resource limit, so we successfully synchronized the wallet !

But it shows we only have 32 BTC in balance.  and from Electrum's history,  the past 2 month's transaction is gone.  in the past 2 months, everyday we received ton of btc payments.

If you think its the Server's issue, IT IS NOT. we also tried different Server,  its all the same result.

So the bug is,  

If the electrum wallet has many address like 100k,  electrum only synchronizd on some address,  and some not.  in the past 2 months,  every day we receive a lot of btc payments,  but on electrum history its disappeared.

So now our BTC is stucked in this wallet. we have no way to spend.

ThomasV and Ghost32 asked me to post this as an issue on GitHub. 

Thanks everyone.  if you need more details of this bug,  I will get more info for you

**Comment by lzsaver** [comment]
You said that some transactions disappeared. Have you restored the wallet from the seed?

Probably related: #3105
See also: [FAQ: What is the gap limit?](http://docs.electrum.org/en/latest/faq.html#what-is-the-gap-limit)

**Comment by SomberNight** [comment]
Yes indeed; this could be a gap limit issue. So try increasing that a bit.

In any case, in the console run these, and report back the results:
```
len(wallet.get_addresses())
len(wallet.get_receiving_addresses())
```

**Comment by SomberNight** [comment]
Also, on IRC you have said:
```
<JackWan> it keeps sychronizing
<JackWan> and when it reaches 66749
<JackWan> it restarted from 0/66749
<JackWan> and im pretty sure i have more than 66749 address in this wallet
<JackWan> at least 100k
```
Please check the logs, there could be something interesting there.

**Comment by jackalmeida** [comment]
> Yes indeed; this could be a gap limit issue. So try increasing that a bit.
> In any case, in the console run these, and report back the results:
> len(wallet.get_addresses())
> len(wallet.get_receiving_addresses())

I checked with :  wallet.gap_limit
and my current gap_limit value is 200
So its very big enough. 


You are connected to an ElectrumX 1.12 server.
>> len(wallet.get_addresses())
69518
>> len(wallet.get_receiving_addresses())
69416


that's the problem here.  Im pretty sure we have more than 100k address used in this wallet, but the command only shows 69518

**Comment by SomberNight** [comment]
The main issue was that a gap_limit of 200 was too low for this wallet.
Increasing to 500 revealed the missing transactions (thousands of them).
OP is using btcpayserver, and apparently btcpayserver never recycles unused addresses, so if enough invoices don't get paid in a row, large gaps happen.

There are some other issues with OP's gigantic wallet, particularly several-minute long GUI freezes, that are unrelated.
