### ISSUE TITLE
blockchain_headers full of zeros

### ISSUE THREAD

**Issue by HornedSalmon** [spesmilo/electrum#5469]
I'm trying to get a full copy of my blockchain_headers but when I open the file in my Electrum folder I'm getting a file that starts out with only 0's for hundreds of thousands of lines. 

The file I got from here: https://headers.electrum.org/blockchain_headers seems to be much more correct and I can find things like the Genesis header but doesn't go to the current block height. 

I cannot seem to make any sense of the file that's being generated by Electrum. Am I doing something wrong? How can I get all blockchain headers on the current chain?

**Comment by SomberNight** [comment]
The client no longer downloads all headers. Instead, there is a checkpoint block.
All headers after the checkpoint are downloaded;
before the checkpoint, only headers that are needed to SPV transactions in the wallet are downloaded.

**Comment by HornedSalmon** [comment]
I see. Is there any way to avoid this? Or a way to set a much older checkpoint?

**Comment by SomberNight** [comment]
Yes, you can just clear this file https://github.com/spesmilo/electrum/blob/935ab9a12f4cd6cf8e06c7207fafda72bb6ea1c7/electrum/checkpoints.json

**Comment by ecdsa** [comment]
Note for people landing on this page because they have wallet synchronization issues: There is absolutely no point doing that, your wallet will not "sync better". It will use more bandwidth instead.
