### ISSUE TITLE
electrum doesn't handle increased DPI setting well

### ISSUE THREAD

**Issue by dooglus** [spesmilo/electrum#5471]
I recently started using a custom DPI in my XFCE4 settings to make the fonts bigger across all the programs I use.

Most programs handled the change gracefully, but electrum 3.3.6 didn't quite. Some of the fields are very hard to read now.

Here's how it looks with the default DPI setting:

![Screenshot_2019-06-28_18-26-44](https://user-images.githubusercontent.com/573356/60378177-6bf6db00-99d3-11e9-8c57-fcc7726f3629.png)

and here's with a higher DPI setting:

![Screenshot_2019-06-28_18-27-29](https://user-images.githubusercontent.com/573356/60378183-7618d980-99d3-11e9-972b-2d6a118aca94.png)

Notice how the fonts and the rectangles are all bigger in the 2nd image, but not in the correct proportion. Whereas in the 1st image the amounts are separate from the words "BTC" in the 2nd image they are drawn on top of each other, making it very hard to read the numbers.

I'm using the XFCE4 desktop environment, and changing the DPI using `Settings > Appearance > Fonts > DPI`:

![Screenshot_2019-06-28_18-38-57](https://user-images.githubusercontent.com/573356/60378237-3f8f8e80-99d4-11e9-8307-0c2b7a1cdd01.png)

**Comment by dooglus** [comment]
It looks like the code is assuming a font size:

    ./electrum/gui/qt/amountedit.py-        # This seems sufficient for hundred-BTC amounts with 8 decimals
    ./electrum/gui/qt/amountedit.py:        self.setFixedWidth(140)
    ./electrum/gui/qt/amountedit.py-        self.base_unit = base_unit

140 pixels should be enough for anyone, right? :)

I guess I've found a workaround - I can simply change that 140 to something that suits the DPI I'm using. But better would be some way of dynamically determining how big a hundred-BTC amount with 8 decimals really does take up, allowing enough space for the trailing " BTC" too.

**Comment by dooglus** [comment]
How about something like this?

    diff --git a/electrum/gui/qt/amountedit.py b/electrum/gui/qt/amountedit.py
    index c3920b9d6..d55c5fc27 100644
    --- a/electrum/gui/qt/amountedit.py
    +++ b/electrum/gui/qt/amountedit.py
    @@ -3,11 +3,12 @@
     from decimal import Decimal
     
     from PyQt5.QtCore import pyqtSignal, Qt
    -from PyQt5.QtGui import QPalette, QPainter
    +from PyQt5.QtGui import QPalette, QPainter, QFont, QFontMetrics
     from PyQt5.QtWidgets import (QLineEdit, QStyle, QStyleOptionFrame)
     
     from electrum.util import (format_satoshis_plain, decimal_point_to_base_unit_name,
                                FEERATE_PRECISION, quantize_feerate)
    +from .util import MONOSPACE_FONT
     
     
     class MyLineEdit(QLineEdit):
    @@ -24,7 +25,7 @@ class AmountEdit(MyLineEdit):
         def __init__(self, base_unit, is_int=False, parent=None):
             QLineEdit.__init__(self, parent)
             # This seems sufficient for hundred-BTC amounts with 8 decimals
    -        self.setFixedWidth(140)
    +        self.setFixedWidth(QFontMetrics(QFont(MONOSPACE_FONT)).width('123.12345678 BTC'))
             self.base_unit = base_unit
             self.textChanged.connect(self.numbify)
             self.is_int = is_int

It seems to make the AmountEdit boxes a little too wide at the default DPI but about right at my higher DPI.

Here are screenshots after applying that diff:

![Screenshot_2019-06-28_20-04-24](https://user-images.githubusercontent.com/573356/60379047-9e5b0500-99e0-11e9-98da-0b4a0f8fedd7.png)

![Screenshot_2019-06-28_20-06-14](https://user-images.githubusercontent.com/573356/60379048-a024c880-99e0-11e9-9599-02bd14ddea30.png)

**Comment by SomberNight** [comment]
There are some other related issues, e.g. https://github.com/spesmilo/electrum/issues/4597 and https://github.com/spesmilo/electrum/issues/1927
Thanks for the QFontMetrics idea, that looks good!

**Comment by SomberNight** [comment]
Should be better now. Feel free to report dpi issues regarding other parts of UI (or any other issue :P).
