### ISSUE TITLE
Trying to build Windows binaries fails

### ISSUE THREAD

**Issue by buhrmi** [spesmilo/electrum#5474]
Hi all,

been following the [guide](https://github.com/spesmilo/electrum/blob/master/contrib/build-wine/README.md) to build windows binaries here, but get an error when trying to build:

```bash
sudo -E docker run -it --name electrum-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum --rm --workdir /opt/wine64/drive_c/electrum/contrib/build-wine electrum-wine-builder-img ./build.sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"./build.sh\": stat ./build.sh: no such file or directory": unknown.
```
Anybody got an idea what might be wrong?

**Comment by SomberNight** [comment]
> The docker commands should be executed in the project's root folder.

**Comment by buhrmi** [comment]
I found the problem. I was using WSL with Docker Desktop, and had my source code checked out at `/mnt/d/code`. Needed to follow [this guide](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly#ensure-volume-mounts-work) and change my working dir `to /d/code`.
