### ISSUE TITLE
The loss of 2.3 BTC

### ISSUE THREAD

**Issue by Digites99** [spesmilo/electrum#5477]
Hello. When sending bitcoin, a message appeared about the need to update the program with a link to download the file. I trusted Electrum, clicked on the link and downloaded the new version 4.0.0. After starting the program I saw transaction -2,301 BTC. Why doesn't anyone close this hole?
![-2,3 БИТКОИНА](https://user-images.githubusercontent.com/52423024/60456291-964dd000-9c41-11e9-94dc-95c201039435.jpg)

**Comment by ecdsa** [comment]
Sorry for your loss. You have downloaded malware, see the warning on our front page. The "hole" has been closed about 6 months ago, but people using old versions of electrum are still vulnerable.

**Comment by alex9522** [comment]
My frend these tiefs are stealing from their users. This is not possible to happens without their participation. Just delete their wallet and never use it anymore! They will never compensate you!

**Comment by alex9522** [comment]
I see this guy is using 3.3.6 verson. Why he lost his balance if he do not use old version????

**Comment by SomberNight** [comment]
That is *after* he downloaded 4.0.0 (malware). Without more context it is not possible to tell:
- either "4.0.0" simply displays its version string as 3.3.6
- or after downloading the malware and getting robbed, he then downloaded the legitimate 3.3.6.

-------- Original Message --------

**Comment by Amitie10g** [comment]
Where you downloaded the Electrum 4.0

Please report those fake websites to [Privacy Protect](http://www.privacyprotect.org/report-abuse/) and also your local police and the FBI.

**Comment by billyrubin22** [comment]
I was just phished by this Electrum 4.0.0 fake security update. Just my second btc transaction.  Where is the info on how to clean up after the fact?  Im new to BTC and dont need all the technical talk.....just the fix.  Where can I find it?  thanks

**Comment by ldz1** [comment]
@billyrubin22: Unfortunately, nobody can tell exactly how to clean it up, because nobody knows this software and can not take responsibility for this bad software. I think we can only talk about the right approach. This look like this.

1. Download from from the official web site https://electrum.org
2. Verify GPG signature http://docs.electrum.org/en/latest/gpg-check.html
3. Follow electrum on twitter for news https://twitter.com/electrumwallet
