### ISSUE TITLE
Cannot bump fee in watch only mode.

### ISSUE THREAD

**Issue by mdspawn** [spesmilo/electrum#5491]
I have Electrum 3.3.7 both on my Windows 10 and Android phone.  I have a watch only wallet on my PC and the same wallet with keys on my phone. I am able to create an unsigned transaction on my PC, sign it on my phone, and the broadcast it. However, when I try to bump the fee on my PC, and then scan the QR code with the unsigned transaction on my phone, it shows as signed, and then fails to broadcast. I did choose to bump the fee on PC, because it lets me choose a custom fee, unlike the phone version.

**Comment by SomberNight** [comment]
Thank you for reporting this.
