### ISSUE TITLE
Incorrect balance of earlier addresses

### ISSUE THREAD

**Issue by shikita** [spesmilo/electrum#5497]
Latest version of client and  server.

Tried to get balance of "1NY3Pr8EYgy74K5DwQCYkKsE4dYNeiGUGg"  got 0 but  on online block explorers it shows 50 BTC.  what might be the reason?

**Comment by kyuupichan** [comment]
It doesn't include P2PK payments

**Comment by shikita** [comment]
i got only little idea about P2PK. so there  won't be any new  p2pk payments ? is P2PK deprecated ?

**Comment by kyuupichan** [comment]
It works fine.  It is up to the people concerned how they receive payments; they may or may not choose to use P2PK or indeed P2PKH.  The assignment of bitcoin addresses to P2PK payments is non-standard and a hack anyway, so I'd argue the block explorers are responsible for the confusion.

**Comment by shikita** [comment]
what is  the reason for not including  the P2PK payments in ElectrumX?

**Comment by kyuupichan** [comment]
They are there, you just need a different query

**Comment by shikita** [comment]
would  you  give an  example to query  P2PK  transactions? Thank you very much for your patience.

**Comment by kyuupichan** [comment]
See the ElectrumX protocol docs.

**Comment by shikita** [comment]
hmmm. Ok. Thank you.

**Comment by SomberNight** [comment]
Note there is currently no way to monitor ("import") a P2PK script in Electrum (but any script can be monitored server-side). You can however sweep coins from P2PK scripts.

A reasonable way to support importing these scripts would be what Bitcoin Core started doing recently:
https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md
i.e. using output script descriptors
