### ISSUE TITLE
Odd Trezor behaviour when sending "max" amount.

### ISSUE THREAD

**Issue by partywave** [spesmilo/electrum#5498]
Trying to send/consolidate "max" amount with 3 inputs on Electrum 3.3.6/7 (incl latest trezor module 0.11.3) using Trezor T with f/w 2.1.1 to single output receiving address in same wallet.

Trezor does not ask for confirmation of send address, and also reports send amount incorrectly as only the mining fee. Not sure if this is a Trezor or Electrum issue but guessing Electrum.

**Comment by SomberNight** [comment]
> to single output receiving address in same wallet.

As the address is in the same wallet, this is expected behaviour.

In general, it's the responsibility of the trezor firmware to do the correct checks and display the pertinent information to the user on its own screen. If electrum could trick it not to display a destination address like you explained, that would be a serious bug with trezor.

**Comment by partywave** [comment]
Ok that's fine, what about the amount in Trezor reporting only the mining fee and not the total amount to send?

**Comment by SomberNight** [comment]
> Also when sending < max to same wallet the address confirmation is shown.

It's not about sending max, it's that the trezor firmware only allow bypassing confirmation for up to one output. Electrum provides the proof that an output is owned by the trezor and so the user does not need to confirm that output. If you send max, there will only be one output (usually), and hence no outputs need confirming; if you send less, then typically there will also be change, and only the confirmation for the change will be skipped in that case.

> what about the amount in Trezor reporting only the mining fee and not the total amount to send

The amount is a delta from the perspective of the wallet. As you are transferring coins from same wallet to same wallet, the effective change in coin amount will only be the fee.

**Comment by partywave** [comment]
Thanks for taking the time to answer these questions 🙏🏼
