### ISSUE TITLE
[Feature request] Upload electrum to Pypi

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#5505]
Thank you for your awesome software!
I have(and others probably too) a program(actually platform) that depends on electrum, and if usual dependency can be just put in requirements.txt file and installed like so:
`pip install -r requirements.txt`
So in case of electrum it can't be installed this way(or if someone needs to install it it id comfortable to just run pip install electrum)
To solve this I created a script that does that using official site, but everyone will need to run it, some people may forget, one time site had temporary issues, and command is quite long:
`wget https://raw.githubusercontent.com/MrNaif2018/bitcart-docker/master/scripts/electrum_version.py && python3 electrum_version.py`
Could electrum be placed on Pypi?
It has a lot of advantages:
1) On CI build it can be configured that when you create a release, it will automatically deploy to Pypi, or, you can do it manually too
2) If security is concern, Pypi checks https connection(from pypi docs)
It is also possible to provide gpg signature with electrum on pypi, plus it is possible to specify sha256 hash to verify electrum installation(taken from https://pip.pypa.io/en/stable/reference/pip_install/#id42)
3) Electrum installation would be easier and more libraries could be created
Package could be uploaded using twine, like so:
````
pip install wheel twine
python setup.py bdist
python setup.py bdist_wheel
# create gpg signature the usual way here
twine upload dist/*

**Comment by bauerj** [comment]
How would one check the GPG signature when installing through Pypi?

**Comment by MrNaif2018** [comment]
Well if signatures are uploaded to Pypi too, then it would be the same
`gpg --verify electrum.tar.gz.asc electrum.tar.gz`
And the same for wheel is possible

**Comment by ecdsa** [comment]
I don't see how Electrum installation would be easier in the case where signatures are verified. 
If signatures are not verified, then adding our software to Pypi seems like adding another element in the chain of trust.

**Comment by MrNaif2018** [comment]
Well, it seems like the same message I saw in issue in 2016, but now it is different.
It is not hard. 
Installation will be easier for projects(mine too) that depend on electrum
About trust, again, people still can verify it all and Pypi isn't hacked usually, all the packages lie here and aren't hacked, people can verify via gpg signature as it is the same as in electrum web site(like .tar.gz file and .tar.gz.asc file), or one more method, via sha256 hash(or a stronger one).
When it is specified, pip will check it, and refuse to install on hash mismatch.
I don't see a very big problem in uploading to Pypi and it would help a lot, I think that even a chance that Pypi is hacked is less than electrum.org down/hacked.
So, could it happen?

**Comment by bauerj** [comment]
How exactly does it make work easier for your project? Wouldn't you have to download the distribution and the signature from PyPi then?

**Comment by MrNaif2018** [comment]
Well probably I would have to, but it can't have CI cache for example, one time it failed because of site being down, and users woudn't need to run one more script(download from internet etc), but just to use normal way of installing dependencies. And about uploading electrum to Pypi I am talking it more about not as app(GUI isn't used at all), but as python library.

**Comment by MrNaif2018** [comment]
Or if this is not possible, it could still be helpful in those two cases:
1. Could I maintain electrum package on Pypi(or with other similar name) myself?
2. Or if not, is master branch counted stable enough to be included in pip requirements(git+ links)?

**Comment by SomberNight** [comment]
you can install a specific tag or branch with pip:
```
python3 -m pip install --user git+https://github.com/spesmilo/electrum.git@3.3.8
```

**Comment by MrNaif2018** [comment]
Hmm didn't think about that, thanks!
electrum on pip would still be appreciated, but it is a good solution too.
Thanks, closing this.
