### ISSUE TITLE
Feature request: add Child Pays for Parent (CPFP) button to Kivy / Android

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#5507]
We can use replace by fee (RBF) for outgoing transactions in Kivy / Android. Then, we will have on that particular tx a "Bump fee" button displayed after we click "Details" on the transaction in cause to learn more about it. This is great and very useful.

I think it's useful and rational to add a Child pays for the Parent button on incoming transactions in Kivy / Adnroid, displayed the same after we click "Details" on an incoming transaction.

Currently there is no way to use child pay for the parent on Kivy / Android and it's annoying when you receive a tx with low fee because you cannot control to spend it if you have other UTXOs in your wallet, and the only way is to send max to some new address but this is ugly.

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/pull/7487
