### ISSUE TITLE
I can't retrieve BTC even though I put the right Derivative Address

### ISSUE THREAD

**Issue by Redalio** [spesmilo/electrum#5510]
I finally figured out what Derivative is my BTC Segwit from the Ledger Live but I still can't see my address on Electrum.  I can't even import with xpub neither even though I got the xpub from Ledger Live!  Also on Ledger Live, it show's freshAddressPath": "49'/0'/0'/0/12"  I tried m/49'/0'/0'/0 & it doesn't work!  I even tried https://iancoleman.io/bip39/ to get the private key & it's doesn't work neither.  What am I doing wrong?  I have the right seeds & still can see on Ledger Live.

**Comment by Redalio** [comment]
I just found out it's easier that I had it as default of m/49'/0'/0' on Electrum than having the complicated m/49/0'/0'/0.  I was able get my BTC on Electrum that way!

**Comment by AbdussamadA** [comment]
please close the issue if it is solved
