### ISSUE TITLE
[Feature request] for Android app to have Networking options as the first form in first start (kivy, select server, network setup, before wallet creation)

### ISSUE THREAD

**Issue by bidelakbari** [spesmilo/electrum#5512]
Suppose you want to change the server and enable one server option, currently you have to create a temp wallet and go to settings and change the networking options. it would be very handy to have the network settings at the first view on the first run.
also when adding custom server's address it would be very helpful to have the scan QR code feature in case the address is rather long.

**Comment by gits7r** [comment]
I understand the need to have more at hand the network menu, so you can set custom server and potentially enable single server mode, given the latest spam attack we faced on public servers, but I don't understand in your description why you need to create a temp wallet? You mean for privacy reasons, in order not to "leak" the addresses of your real wallet to the server you are connecting to at first, before entering your custom one?

**Comment by gits7r** [comment]
And yes, I find it under optimal that, unlike the desktop version where the wizard that appears at first run asks you how you want to connect and to which servers / via which proxy, for Android this is not the case. At least for sever selection privacy reasons I think it's a good idea to show this particular step of the wizard in Android as well.

**Comment by relativisticelectron** [comment]
I think this is a useful feature too, and I started experimenting with the code, but I need some help: The choice dialog is not showing up for some reason: relativisticelectron@0a789c1#diff-d3ef59134ccb28b8db063f9f5926e58fR1135

Only if I call wizard.terminate() afterwards I can see the dialog (but this causes an exception).

**Comment by ecdsa** [comment]
you cannot mix sequential programming (in on-start) and callback-based programming (the wizard)

**Comment by relativisticelectron** [comment]
> you cannot mix sequential programming (in on_start) and callback-based programming (the wizard)

Thanks for the feedback. I thought the wizard starts a waiting loop (waiting for callback). But if I understand your answer correctly, I am mistaken. I will try to understand how the Installwizard works.

**Comment by ElectrumWontStartAirplane** [comment]
Electrum on my pixel will not start in airplane mode (sometimes)
See post on Reddit:

https://www.reddit.com/r/Electrum/comments/mj46il/electrum_on_old_google_pixel3_in_airplane_mode/
