### ISSUE TITLE
Problem starting 3.3.8 (mac) - MacOS:miner

### ISSUE THREAD

**Issue by HanZeno** [spesmilo/electrum#5514]
![Screen Shot 2019-07-15 at 19 36 51](https://user-images.githubusercontent.com/34787140/61236370-20b12c00-a738-11e9-884d-ce57f27ca63a.png)
Got a problem launching 3.3.8 as my avast says its affected with MacOS:Miner-AP (Trj). The electrum app has gone into my virus chest and wount open now.
Any suggestions?
downloaded from electrum.org

**Comment by HanZeno** [comment]
I downloaded 3.3.8.1 and it installed and electrum runs smoothly it appears

**Comment by SomberNight** [comment]
> I downloaded 3.3.8.1

... where did you find that?

**Comment by HanZeno** [comment]
sorry it's the 3.3.8 version

**Comment by magneticrob** [comment]
This is happening to me too, can't open 3.3.8 or 3.3.7, used to work fine

**Comment by ecdsa** [comment]
closing, antivirus false positive
