### ISSUE TITLE
Recurring payments to replace Patreon - feature request

### ISSUE THREAD

**Issue by vincecate** [spesmilo/electrum#5515]
I think it would be really great if Electrum could do recurring payments.   I am thinking of small monthly donations to youtube content creators to do the same job as Patreon but without any central control.   This gets particularly great when Lightning payments start working.  Then it would be very possible to donate $2/month to several different content creators.   

I think this would be a good "use case" for Lightning actually.   It gets rid of the cost and control of Patreon.   It would be a fun and easy way to make regular small donations.

I would like to have a list of recurring payments with where they go and the USD amount.  Then each month the wallet would automatically make payments, assuming I still had enough Bitcoin.

**Comment by ecdsa** [comment]
thank you but this kind of general discussion is not really useful here.
please post only about specific issues.

**Comment by vincecate** [comment]
Sorry.  Where should an Elecstrum feature request be discussed?

Thanks.
