### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vhammer666** [spesmilo/electrum#5517]
Создал новый кошелек после обновления, не могу с него вывести, пропадает пароль. SEED фраза есть, помогите вывести. Версия 3.3.8.

**Comment by brainard25** [comment]
some fraudulent bitcoin sites now scam wallet owners,by locking them out of there account.
A team of computer technician have discovered how bitcoin can be recovered,they where able to recover my locked bitcoins on coinbase. you can contact Matanari@ tutanota .C0M .they will help you recover your stolen.lost crypto currency. lets be careful of the kind of wallet we use and the information   we used in registering them account.

**Comment by ecdsa** [comment]
Google transate: "I created a new wallet after the update, I can’t withdraw from it, the password disappears. SEED phrase is, help deduce. Version 3.3.8."

**Comment by ecdsa** [comment]
not sure if we can really do anything with that report. 
maybe the user created a watching-only wallet...
