### ISSUE TITLE
Help when running Kivy on Linux computer

### ISSUE THREAD

**Issue by bitnota** [spesmilo/electrum#5519]
I am following the steps for running Kivy GUI directly on Linux I installed Kivy with Anaconda, made Atlas, but when i try the following command:

`$ electrum -g kivy`

i get this error on console:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/electrum", line 362, in <module>
    d.init_gui(config, plugins)
  File "/home/user/anaconda3/lib/python3.7/site-packages/electrum/daemon.py", line 348, in init_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
ModuleNotFoundError: No module named 'electrum.gui.kivy'
```

**Comment by ecdsa** [comment]
setup.py does not install the kivy module.
adding electrum.gui.kivy to setup.py does not solve the issue, because of where kivy expects to find its data directory.

**Comment by bitnota** [comment]
Thanks for the explanation. So what should I do to solve it?

**Comment by ecdsa** [comment]
do you actually need to solve it?
you can run the kivy gui if you clone the git repository

**Comment by bitnota** [comment]
What i need to do is play the Kivy GUI instead of QT in Linux desktop, to make some modifications to the visual code for an Altcoin wallet, and then compile the APK for Android, but I need to monitor in Linux.
my question is: how do I run the Kivy GUI from the git repository?
Excuse me if my question is very basic
Thank you in advance for your help

**Comment by SomberNight** [comment]
```
git clone https://github.com/spesmilo/electrum.git
cd electrum
(cd electrum/gui/kivy/; make theming)
./run_electrum -g kivy
```

**Comment by bitnota** [comment]
Thank you very much! It worked! that's what i need
