### ISSUE TITLE
Paper Wallet Generator of Seed

### ISSUE THREAD

**Issue by rickybobby1** [spesmilo/electrum#552]
Electrum watch-only wallet+a written copy of the 12 word seed makes a great "active" paper backup. Would be great to have a paper wallet generator like this one: https://github.com/bkkcoins/papergen , but at the generation of the 12-word seed. Maybe one that also made a watch-only wallet automatically for you, without ever writing the seeded wallet file to disk.

**Comment by ecdsa** [comment]
Closing. Too dangerous for newbies, and easy to achieve by other means

**Comment by rickybobby1** [comment]
Thanks for taking the time to consider the idea, and thanks for all the work you do. I don't quite see how it  would be any more dangerous for newbies than the current method for wallet creation (Also I wonder how many people save using a picture of the seed's QR code, then get robbed because they think it's secured but there's still a thumbnail out there that can be zoomed in on).


"Displaying messages in capitals is not how you get people to learn things. People learn much better by doing. If they first create a wallet that has a seed, newbies learn what a seed is."

Actually reading back I may have not communicated the ideas properly - The one about the "watch-only" wallet would still have a seed created just like creating a normal wallet, but then once the seed is typed again and verified by the user the seed would be removed (just like a wallet restored from the master public key, which the seed has to be reintroduced to make the wallet spendable). 

"Displaying messages in capitals is not how you get people to learn things. People learn much better by doing. If they first create a wallet that has a seed, newbies learn what a seed is."

I agree all-caps is condescending and may not be the most effective way to communicate something...but I guarantee you that the #1 reason the average bitcoin newbie learns about the importance of an HD wallet's seed is <drumroll>......they forgot their spending password and are now stuck with a wallet full of coins and no way to get them out.

Anyways again, thanks for all the work you do, to me you're a hero in the BTC world. MUCH appreciated.
