### ISSUE TITLE
Encrypt interface in command line

### ISSUE THREAD

**Issue by twhite00** [spesmilo/electrum#5521]
I used Electrum-3.3.3 on Ubuntu16.04 PC,
I encrypt a message with this command:
“./run_electrum encrypt mypubkey hello”
and it return a error “assertion error”

**Comment by ecdsa** [comment]
please try with the latest version.
if the error still occurs, post the traceback

**Comment by ecdsa** [comment]
closing: no answer, and cannot reproduce the issue
