### ISSUE TITLE
cannot signtransaction using custom privkey not from wallet

### ISSUE THREAD

**Issue by Telariust** [spesmilo/electrum#5522]
I did not find deprecated message for "--privkey" for watchonly wallet or custom privkey not from wallet. 
It must work?

last echo
>  Release 2.6.3 (bugfixes)
>  * fix command line parsing of transactions
>  * fix signtransaction --privkey (#1715)

Check it, runing test for **electrum-3.3.8**

`cat unsigntx.txt | electrum signtransaction --privkey [privkeyWIF_needful] - > signtx.txt`
> {
>     "complete": false,
>     "final": true,
>     "hex": "45505446ff0002000000019104a...."
> }

Here "complete=false" and "hex:45505446ff00020..." - sign failed (how if privkey is wrong, but it valid)
Without --privkey option - sign success (if privkey from wallet(seed/import))

Ok, maybe it only **CLI** problem? Then check it via **RPC**.

github.com/spesmilo/electrum/blob/master/electrum/commands.py
```
    @command('wp')
    def signtransaction(self, tx, privkey=None, password=None):
        """Sign a transaction. The wallet keys will be used unless a private key is provided."""
```

Try signtx using custom privkey
`curl --data-binary '{"id":1,"method":"signtransaction","params":["45505446ff0002000000019104a...","[privkeyWIF_needful]"]}'  http://user:pass@127.0.0.1:7777`

> {"result": {"hex": "45505446ff0002000000019104a...", "complete": false, "final": true}, "id": 1, "error": null}

sign failed

hmm... maybe?

`curl --data-binary '{"id":1,"method":"signtransaction","params":{"tx":"45505446ff0002000000019104a...","privkey":"p2pkh:[privkeyWIF_needful]"}}'  http://user:pass@127.0.0.1:7777`

> {"result": {"hex": "45505446ff0002000000019104a...", "complete": false, "final": true}, "id": 1, "error": null}

sign failed

but if **load_wallet** (seed/import) have needful privkey: 
`curl --data-binary '{"id":1,"method":"signtransaction","params":["45505446ff0002000000019104a..."]}'  http://user:pass@127.0.0.1:7777`

> {"result": {"hex": "02000000019104a...", "complete": true, "final": true}, "id": 1, "error": null}

sign success

It would be wonderful to signtx using custom privkey without importprivkey everytime.
Plz, fix it!

**Comment by ecdsa** [comment]
this is probably because you created the transaction with a wallet that has an xpub
--privkey works only if the watching-only wallet is made of imported addresses
