### ISSUE TITLE
I create a 2/3 multisig wallet, but after  restore wallet from seed, it become 3/4 multisig

### ISSUE THREAD

**Issue by past2017** [spesmilo/electrum#5527]
version: 3.3.8
steps:
1. create a 2/3 multisign wallet and works well on android app
2. import seed from this android-electrum.app to x64-electrum.exe
3.  After imported, send a transaction, in transaction sign page after the 1st person sign, sign number become 2/4 as below, it should be 1/3
![image](https://user-images.githubusercontent.com/25541244/61874646-7dbc9700-af1b-11e9-8368-3d8992d9a8d8.png)

**Comment by SomberNight** [comment]
In `Wallet`>`Information`, what is `Wallet type` and `Script type`?

**Comment by SomberNight** [comment]
Wait, actually, nvm.

The tx dialog shows it's partially signed `2/4`.
Note that there are two inputs, each of which should be 2-of-3 multisig; which means each input **needs** 2 signatures; so altogether 4 signatures are needed.
One cosigner has already signed and added 1 signature for each input, so 2 sigs are already there.
Hence `2/4`.
