### ISSUE TITLE
Error con una transacciond e bitcoin de Electrum Wallet a Uphold

### ISSUE THREAD

**Issue by horus2019** [spesmilo/electrum#5528]
Buenos días, mi problema es el siguiente:

Envié unos BTC desde la wallet electrum

Tx: https://www.blockchain.com/btc/tx/fac4bb097c669b8f35cf79a93e94e04dc60ce28002257aca33e221146d6b21f7

Pero en la wallet de la otra persona que es uphuold no se le han reflejado aún.

Gracias de antemano por su pronta solución.

**Comment by peleion** [comment]
Su transacción tiene más de 1.000 confirmaciones. Compruebe que la dirección de recepción es correcta y que el receptor tiene acceso a esta dirección/balsa.

Your transaction has over 1,000 confirmations. Check that the receiving address is correct and the receiver actually has access to this address/wallet.
