### ISSUE TITLE
3.3.8 Sends to random BC1 address

### ISSUE THREAD

**Issue by timmy46975** [spesmilo/electrum#5529]
I received a transaction from an exchange (CEX):
477bc809ea3189421f6ed470728136bec035119cce914bdec0329d47db4c95df

A few minutes after arriving in my wallet, the BTC were transferred to a BC1 wallet that isn't mine:
bc1q30nwqsa0utlvvz44uenn5wmu9kyadvr9aq0dw0

I verified the signature on my 3.3.8 version downloaded from the official site.

This is the first time anything like this has happened, would like some sort of idea where the coins actually are, if I'm just out of luck, etc.

**Comment by Talkless** [comment]
@timmy46975 Do you use any HW wallet? If not, please check if your computer is not compromised. If someone got your keys, then they can spend your coins from other software, ignoring the fact that you have valid Electrum installation.

**Comment by timmy46975** [comment]
@Talkless No sir.  The coins in question remain unspent in said BC1 wallet.  But I will check for said compromises.

**Comment by timmy46975** [comment]
System does not appear to be compromised after several scans with different software.  Got a false positive on an installer from 3.3.4 but it checked out with the signature as well.

Have raised the question in various locations to see if it has occurred to anyone else.

**Comment by peleion** [comment]
Discussed on Reddit also for anyone following:
https://www.reddit.com/r/Electrum/comments/chq5bv/338_automatically_transferred_to_random_bc1/
