### ISSUE TITLE
Issue with signing offline using a hardware wallet

### ISSUE THREAD

**Issue by anon-1-123** [spesmilo/electrum#5532]
Online machine:
mac 10.14.5, using electrum 3.3.8

Offline machine:
ubuntu 16.04, using electrum 3.3.8

i'm using ledger nano s, on online machine (ypub watch only) i created an unsigned transaction and moved it to the offline machine, confirmed the addresses were correct so my derivation path (SEGWIT) generated the right addresses. i loaded the transaction and pressed the "sign" button then i'm greeted with "no interface to do request on... gave up."

i'm currently unable to use the "--offline" flag as i'm running an AppImage and extracting/editing the contents for AppRun won't let me execute due to offline machine being out of date / missing packages. Can't use appimagetool as that's missing as well on my offline machine.

**Comment by SomberNight** [comment]
> i'm currently unable to use the "--offline" flag as i'm running an AppImage and extracting/editing the contents for AppRun won't let me execute due to offline machine being out of date / missing packages. 

You can use any flag / option with the AppImage. Just call it with `--offline`, it should work. Don't worry about extracting it or using appimagetool.
