### ISSUE TITLE
Bug not allowing sending btc

### ISSUE THREAD

**Issue by johnbrown1221** [spesmilo/electrum#5538]
Recieve this error after trying to send btc dymanic fees also dont work not sure what to do 
![2019-07-30 22_39_47-Electrum 3 3 4  -  wallet   standard](https://user-images.githubusercontent.com/53478722/62129857-0e7be400-b31b-11e9-8760-b33a46fd6ee6.png)

**Comment by SomberNight** [comment]
What version of Electrum?
What is the colour of the orb/circle in bottom right?
Did you try switching servers?

**Comment by johnbrown1221** [comment]
3.3.4 its red and yeah i have been switching servers to no avail

**Comment by johnbrown1221** [comment]
sorry i fixed it i am stupid the proxy was activated and it wasnt correct
