### ISSUE TITLE
history is empty

### ISSUE THREAD

**Issue by lera-valera** [spesmilo/electrum#5539]
Reinstalled electrum, everything work except history. Operations are not shown. Version 3.3.8
![пуп](https://user-images.githubusercontent.com/53487731/62147142-97852200-b2ff-11e9-8c66-73f38a6f2ca6.png)

**Comment by SomberNight** [comment]
Did this happen after restoring from seed words?
Please enable [debug logging](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging) and upload the log.

**Comment by ecdsa** [comment]
closing, no answer
