### ISSUE TITLE
Electrum Problem

### ISSUE THREAD

**Issue by Olizoo** [spesmilo/electrum#5540]
Does anyone know how I can send money from my electrum account since this scam started ? I cant send it anywhere because of the 4.0 scam and I don't know how to get around it . . .

**Comment by MrNaif2018** [comment]
Always verify, always download electrum from official site electrum.org Latest version is 3.3.8. 
Also check your computer for malware

**Comment by Olizoo** [comment]
Thanks for the reply

I updated to that version and now it seems to have worked :)
