### ISSUE TITLE
stole bitcoin from my wallet

### ISSUE THREAD

**Issue by lucander72** [spesmilo/electrum#5541]
I have been frauded!
On August 1st all my Bitcoin funds (0.06718267) have been stolen form my Electrum wallet

Transaction ID: 555bdd11472e31d6b80f5b0d511906b498e44920642f056659f9067870c770b9

I have never did this how can I get back  my funds?

this is the address where funds were my Bitcoin were sent
1NxCsqsns9Dej8rAUWvEUMRJCcwK87fYTF	     0.06690451

can somebody please help?

**Comment by ecdsa** [comment]
what version of Electrum are you using? did you upgrade recently? did you see a message asking you to upgrade?

**Comment by lucander72** [comment]
I am using version 4.0.0 but it was some time since checked my wallet. I did non see any message asking me to upgrade 
 see attached 
[BCT fraud transaction.pptx](https://github.com/spesmilo/electrum/files/3457531/BCT.fraud.transaction.pptx)

**Comment by lucander72** [comment]
it happened today at 16:54 CET

**Comment by ecdsa** [comment]
there is no version 4.0.0. you downloaded malware. 
see the warning on electrum.org

**Comment by lucander72** [comment]
so  it means I lost my Bitcoin?

**Comment by ecdsa** [comment]
yes. see also here: http://electrum-malware.surge.sh/

**Comment by lucander72** [comment]
that is very bad...I will make sure to uninstall Electrum and never use it again. Shame on Electrum
