### ISSUE TITLE
Feature Request: Fragmented backups

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#5545]
Edit: I think fragmented backups is superior to the original feature I requested that's detailed below.

I'd like to be able to create a wallet that I myself can use at will, but that is also accessible by a quorum of trusted friends, so that if I forget my password or die, my bitcoin can still be accessible. 

For example, a 1 OR 3-of-4 multisig wallet where the primary owner can use the wallet at will, but if that owner loses their private keys, they can recover with the help of 3 of the other 4 trusted friends/organizations. One key could be kept in a security deposit box at a bank, the other 3 could be distribute to friends. In the case of death of the owner, the security deposit box can be willed to one of the trusted friends or someone who can get the help of the trusted friends.

See [this SO answer](https://bitcoin.stackexchange.com/questions/89589/is-it-possible-to-do-a-3-of-5-or-1-multi-sig-for-backup-purposes/89590?noredirect=1#comment102505_89590) for details on the opcodes required to do this.

Ideally, I'd want to potentially use multiple hardware wallets to create a 2 OR 3-of-5 multisig wallet. However it would be best if users could choose their own parameters. 

As far as the interface, it might be a good idea to have a list of "templates" that could be taken from [this list of multisig applications](https://en.bitcoin.it/wiki/Multisignature#Multisignature_Applications). The user could browse through them and select one that makes sense. The "Distributed Backup" template could ask for what J, N, and M should be (with sliders like Electrum currently uses).

For more advanced cases, a user could be presented with an interface that allows them to construct a more complex multi-sig wallet. Maybe it would be reasonable to have a way for a user to enter the multi-sig set up in the form of a text source code, tho for semi-normal users, a simpler and more limited setup that allows just one level of ORs and one level of ANDs could be enough for most use cases.

I think this kind of setup could allow much more reliable backup that is robust even when the user's personal seed is irrecoverable. Non-sophisticated users could use this to safely backup their coins with for-pay services that won't have custody of the coins. I think something like this is the only way to effectively minimize loss of coins.

**Comment by fresheneesz** [comment]
Actually, what might be better than this is to support fragmented backups, like [Armory does](https://www.bitcoinarmory.com/tutorials/armory-advanced-features/fragmented-backups/). I found an old post about how to create fragmented backups for an electrum wallet: https://bitcointalk.org/index.php?topic=526381.0 - maybe those would be helpful in implementing that feature.

**Comment by SomberNight** [comment]
I guess you might be interested in this then: https://github.com/spesmilo/electrum/issues/5419

**Comment by fresheneesz** [comment]
Ah yes, I would be! I suppose this can be closed as a duplicate in that case.
