### ISSUE TITLE
jsonrpc getrequest the key is looking at the btc address. by id does not find

### ISSUE THREAD

**Issue by badhitman** [spesmilo/electrum#5554]
pay attention to the method 

> Electrum-3.3.8\electrum\commands.py -> line: 615

``` Python
@command('w')
    def getrequest(self, key):
        """Return a payment request"""
        r = self.wallet.get_payment_request(key, self.config)
        if not r:
            raise Exception("Request not found")
        return self._format_request(r)
```
the method searches the **request of payment** by a certain key. Note this code:
``` Python
r = self.wallet.get_payment_request(key, self.config)
```
I looked at the code of the called method `wallet.get_payment_request(key, self.config)`.
this method searches the btc address, not the request ID.

### a look from the other side
> Electrum-3.3.8\electrum\commands.py -> line: 655

When I create a **payment request**  `def addrequest(self, amount, memo='', expiration=None, force=False):` 
Electrum daemon returns the object of the created **payment request**. JSON rpc response example:
```json
{
	"time": 1565487654,
	"amount": 314000000,
	"exp": 3600,
	"address": "mpx5Tszu9cn9Yeo8774RC5jqiVfUjQ46xk",
	"memo": "test",
	"id": "3ccc9bc8f0",
	"URI": "bitcoin:mpx5Tszu9cn9Yeo8774RC5jqiVfUjQ46xk?amount=3.14",
	"status": "Pending",
	"amount (BTC)": "3.14"
}
```
The created **payment request** has an ID field. I expected that you need to search for such a **payment request** its ID (in example **3ccc9bc8f0**)
but this ID I can not find your payment and get an error. It's generated here:
> Electrum-3.3.8\electrum\commands.py -> line: 619
```Python
if not r:
            raise Exception("Request not found")
```

Is that normal? I created a payment request and have an ID from it. I want to use this ID to find my payment, but I can't. Electrum deamon jsonrpc searches for an object at btc address. When you generate an exception then at least point to this strange feature. For example
> Electrum-3.3.8\electrum\commands.py -> line: 619
```Python
if not r:
            raise Exception("Request not found. Need to search for a query in the address field")
```

**Comment by ecdsa** [comment]
the ID is used only if you serve requests with HTTP, as part of the path.
maybe we dont need to expose it in the RPC

**Comment by badhitman** [comment]
If in method
`def getrequest(self, key):`
the name parameter tells which key to look for? For example:
`def getrequest(self, btcaddress):`
And the name of the parameter key confused me. 've been trying to find this query using the id
Or make a hint at least in this line
`raise Exception("Request not found")`
Had to randomly cycle through different options. It was hard for me to guess what kind of key is used here. Was sure that this is a bug in Electrum. Then accidentally found. If the clues were there - it would be easier

**Comment by gits7r** [comment]
related is #5605 , to fix getrequest CLI permanently.

**Comment by badhitman** [comment]
> related is #5605 , to fix getrequest CLI permanently.

that's another problem. I was talking about something else. I didn't know about this bug.

**Comment by badhitman** [comment]
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L711

to solve my request, it is enough to describe the error more informatively. I really could not guess for a long time that the request to the address. for a long time I was sure that you need to look for the key created object payment request. okay I will not argue on what basis to seek, although I fundamentally disagree what to look for at normal. But okay! I agree that the author is right because he is the author. I only ask you to change the text of the error. It will be much easier for a programmer to look for a problem. this will save many hours of searching for different programmers all over the planet.

**Comment by badhitman** [comment]
and of course I dream that to all methods there were detailed descriptions of all parameters. in plain human language to write a bit about each parameter. **like jesus to a child [(c)](https://ru.wikipedia.org/wiki/Jesus_to_a_Child)**
