### ISSUE TITLE
Can't recover my BTC through Electrum Wallet

### ISSUE THREAD

**Issue by NetSailor** [spesmilo/electrum#5564]
Hi friend,
 
Recently I used the services of a Mixer, specifically with helixmixer.org .
His server was fallen at momen I did the transaction. They told me later that the way to recover my BTC was introducing a command in 'Console' of my Electrum Bitcoin Wallet where I was using to send BTC to him to make sure I didn't phishing. I entered the command they told me and appears a failure message that told me contact with Support. What I have to do for recover my BTC ?

Thanks for your attention.

**Comment by ecdsa** [comment]
looks like you have been scammed.
