### ISSUE TITLE
daemon load_wallet - in case of an encrypted wallet

### ISSUE THREAD

**Issue by wartjugger** [spesmilo/electrum#5568]
Using:
electrum daemon load_wallet -w wallet_file
prompts for a password when the wallet is encrypted. It is possible to provide the password as a command line parameter? I tried -W and --password (as done with the "restore" command") but none are recognized.

**Comment by ecdsa** [comment]
that is not possible at the moment, because 'load wallet' is a daemon subcommand, not a regular RPC
we will fix that soon

**Comment by wartjugger** [comment]
Is it possible to load a wallet using an RPC call then? I see it's possible to restore a wallet with the RPC but then do we need to order the daemon again to load it?

**Comment by ecdsa** [comment]
fixed in cc32fa36bb909109d6583f4515805aecd039cfe8
will be nerged soon
