### ISSUE TITLE
how to connect testnet on android

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5570]
I know the cmd on linux is ./run_electrum --testnet
how to connect the testnet on andriod？
thxs！！！

**Comment by shuaiLiWang** [comment]
@ghost43 please see the issue

**Comment by ecdsa** [comment]
you need to build your own APK for that

**Comment by ecdsa** [comment]
around line 320 of run_electrum, add 'testnet':True,

**Comment by shuaiLiWang** [comment]
> around line 320 of run_electrum, add 'testnet':True,

![add](https://user-images.githubusercontent.com/9347690/63247467-b12edf00-c297-11e9-94ae-de5737324543.png)

right？
but i try it，it not work 
I think I got it wrong.

**Comment by shuaiLiWang** [comment]
i modify config_options['testnet'] = true to config_options['server'] = 'testnet' ， it not ok too

> around line 320 of run_electrum, add 'testnet':True,

i modify config_options['testnet'] = true to config_options['server'] = 'testnet' ， it not ok

**Comment by shuaiLiWang** [comment]
> around line 320 of run_electrum, add 'testnet':True,

i modify config_options['testnet'] = true to config_options['server'] = 'testnet' ， it not ok

**Comment by ecdsa** [comment]
sorry, that would be line 314 in your code.

**Comment by shuaiLiWang** [comment]
> sorry, that would be line 314 in your code.

now the balance screen info is offline on andriod，Should I do some other settings?

**Comment by ecdsa** [comment]
you probably need to setup a testnet electrum server

**Comment by shuaiLiWang** [comment]
> you probably need to set a testnet electrum server in your config

Successful, thank you soooooooo much!!!!

**Comment by ejrhe** [comment]
Plz teach me this i want to enable testnet on electrum wallet in my android

**Comment by SomberNight** [comment]
To build a testnet android apk, uncomment this line:
https://github.com/spesmilo/electrum/blob/85ea2dfc484b7ee2de5863a1ee7a4531215600c1/contrib/android/make_apk.sh#L48
and then build normally, following the steps described in [`contrib/android/Readme.md`](https://github.com/spesmilo/electrum/blob/master/contrib/android/Readme.md).

**Comment by ejrhe** [comment]
Means if i uncomment that code and run it ./make_apk.sh will it make a testnet version electrum wallet .apk file in my linux terminal?

**Comment by ejrhe** [comment]
Which i can install by moving it to my sdcard ( i am using termux)
