### ISSUE TITLE
Can't RBF parent transaction

### ISSUE THREAD

**Issue by wartjugger** [spesmilo/electrum#5571]
Parent transaction with low fee.
Child with high fee.
When trying to increase the fee of the parent transaction (to the maximum fee possible, 11659 satoshi, or to any fee), I get: 

"The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

insufficient fee"

I'm using 3.3.6. Did try to change servers.

**Comment by wartjugger** [comment]
Now I set it to 30000 satoshi, the transaction was submitted (still unconfirmed, but with the high fee), but now the child transaction disappeared from history. So the parent somehow replaced the child.

**Comment by ecdsa** [comment]
that's normal. the child no onger exists if you RBF the parent.
