### ISSUE TITLE
Satoshi Nakamoto's BTC invisibles on Electrum Wallets? 

### ISSUE THREAD

**Issue by Belisarius-BTC** [spesmilo/electrum#5577]
Hello ! Crypto beginner here (with broken english)

Im slowly studying Electrum wallets fonctions, and my last discovery is the "read only" wallet.

For my first test, i used Satoshi's first addresses, and the one used by Hal Finney for the very first transaction. 
That's the moment i found something wrong: total and transaction number are differents, when i compare the informations sent by Electrum and what i can found on blockchain.com...

Satoshi's BTC seems invisibles!

https://i.ibb.co/cJtZqmr/Genesis.jpg

Is it a problem with Satoshi's mined BTC (blocked? "burned"? Deleted?)? Or Electrum database is uncomplete (nothing before the very end of 2010)?

https://i.ibb.co/7JJ0BqV/No-2009.jpg

I found the same kind of problem with Hal Finney wallet: the 10 BTC sent by Satoshi are not visibles.

I know the first 50 BTC, from the genesis block are unspendable. But what about the others rewards? 

If All the blocks (and their rewards) mined by Satoshi are considered unsendable by the network, this is the answer to the 10 billions dollars question: "Why Satoshi never used his BTC?"

I think that's probably not a bug, but im very curious about the answer.

**Comment by kyuupichan** [comment]
Neither.  Electrum only looks at P2PKH outputs, P2PK outputs are not queried.  If were modified to query them the values would show.

**Comment by Belisarius-BTC** [comment]
Thx for your answer. Unfortunatly, im a beginner and i don't understand what is P2PKH, P2PK and their differences.

**Comment by gits7r** [comment]
Yes, it could. P2PK means: pay to public key. This means the public key itself is stored in the blockchain with the utxo.

P2PKH is a double hash: RIPEMD160(SHA256(publickey)) and it was added to enhance security should secp256k1 ever be broken, the hash security will still remain as no public keys are directly stored in the UTXO set.  Unless the address where the coins are stored hasn't been previously used as input in another transaction of course - this is one of the most important reasons why address re-use is not recommended (the other one is privacy).

You could of course modify it to query the P2PK values. But I think you have better things to do with your time than this -- this is not useful at all. And P2PK will never be used.

**Comment by Belisarius-BTC** [comment]
Thx for your answer Gits7r.
Just a little question: if i download Bitcoin Core with the full blockchain (i didn't because of my bandwidth limitation), can i see all P2PK and P2PKH outputs?
