### ISSUE TITLE
lnaddr.py contains hardcoded Bech32 constants

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5581]
`lnaddr.py` contains the strings `'bc'` and `'tb'` in several places.  Normally I'd suggest simply modifying it to pull those in from `constants.py`, but since it looks like `lnaddr.py` is a fork of some code by Rusty Russell, it's not clear to me whether maybe it would be preferred to send patches to Rusty that add non-Bitcoin currencies.

Which do you think is a preferable approach?  I can send you a PR for the former if you think that's the best approach.

**Comment by ecdsa** [comment]
send the patch to us; I don't know if Rusty maintains that code
