### ISSUE TITLE
Delete ticket by scammers

### ISSUE THREAD

**Issue by Alexinfo2** [spesmilo/electrum#5586]
You delete my ticket right after I make it

I lose my life BTC with electrum.org

I download 3.8 update

All coming with virus

.exe work but i opened the wallet and got 4 times cmd in m y face. Knew it was fishy

I logged in with seed and send tranacation

When sending, it chnged my amount,

I cant click cancel but password box spamming wont let me cancel.

I lost my life

Send to scam address man why,
![fqwfqwsf](https://user-images.githubusercontent.com/54517705/63659540-e2347580-c7a9-11e9-9ea0-bf334fc6158f.PNG)
![14](https://user-images.githubusercontent.com/54517705/63659541-e2cd0c00-c7a9-11e9-890a-9340c48e7c96.png)
![Uploading 12.png…]()
![Uploading 13.png…]()

**Comment by ecdsa** [comment]
it that a case of phishing?
please provide a proper description of what happened.
also, which ticket was deleted, and by whom?

**Comment by ecdsa** [comment]
closing, no answer
