### ISSUE TITLE
Unit tests on Travis seem to stall nondeterministically

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#5587]
Since the merge of lightning, it appears that the unit tests on Travis are nondeterministically stalling.  An example of this is at https://travis-ci.org/spesmilo/electrum/jobs/576391903#L654-L657 .  Copy of output pasted below:

~~~
electrum/tests/test_network.py::TestNetwork::test_fork_noconflict PASSED [ 28%]

electrum/tests/test_regtest.py::TestLightning::test_breach PASSED        [ 28%]

electrum/tests/test_regtest.py::TestLightning::test_breach_with_spent_htlc 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
~~~

Based on some preliminary testing in Electrum-NMC's repo, it appears that if the stall happens, it's always on one of the `test_regtest.py` tests, but it's nondeterministic which one.  I haven't been able to track it down any more than that.

**Comment by ecdsa** [comment]
some steps in regtest.sh rely on time delays and are sensitive to execution speed

**Comment by ecdsa** [comment]
specifically, 'load_wallet' cannot be called immediately after 'start', because the daemon might not be listening yet. hence the 'sleep 1'

**Comment by ecdsa** [comment]
regtests are fixed now. 
I found several issues, see 
5ec1db4d51f0abf0e4327b6471b00dda6096572c
6f333bd86d1aa26cc23f09947f74358367262cf8
3e8080b669306894b572785e2d6ef6226fda7e90
