### ISSUE TITLE
Restoring a BIP39 wallet from a seed phrase on CLI and RPC

### ISSUE THREAD

**Issue by wartjugger** [spesmilo/electrum#5592]
On the GUI, we check "BIP39 seed" in the options under the seed textbox, then select the type of address (I found that "legacy" is the correct choice for a seed phrase generated by blockchain.com). That works well.

But using the command line, running 
`electrum restore "word1 word2 ... word12"`

raises the exception ""Seed or key not recognized".

Similarly, sending an RPC to the daemon with 
`{"id":"curltext","method":"restore","params":{"text":"'.$text.'"}}`
($text holds the seed phrase)

returns an error with the same exception.

I should note that all those methods of restoring wallets work for me very well with Electrum-generated seed phrases.

Are there corresponding settings to be used for CLI / RPC in the case of restoring a BIP39 wallet?

**Comment by ecdsa** [comment]
no, there's no such setting
