### ISSUE TITLE
Trojan warning from antivirus

### ISSUE THREAD

**Issue by hubba1** [spesmilo/electrum#5594]
![image](https://user-images.githubusercontent.com/20878396/63906488-9a962f80-c9dd-11e9-8d7e-9b33333aa628.png)

seems like an outgoing message from my electrum exe file?

**Comment by ecdsa** [comment]
is that the domain ame of an electrum server?

**Comment by hubba1** [comment]
it is an outbound message apparently from the electrum exe file

**Comment by ecdsa** [comment]
closing, this is not an issue with the electrum client
