### ISSUE TITLE
NameError: name 'gui' is not defined

### ISSUE THREAD

**Issue by wartjugger** [spesmilo/electrum#5595]
Console docs indicate:
>The GUI methods can be accessed through the gui variable.

http://docs.electrum.org/en/latest/console.html

However, running the example code in the console,

`gui.show_qrcode(dumpprivkey(listunspent()[0]['address']))`

returns:

> NameError: name 'gui' is not defined

Similarly, typing "gui." and pressing on the tab key does not show any available commands.

**Comment by ecdsa** [comment]
it's called 'window' now, not gui

**Comment by hansbkk** [comment]
Shouldn't the docs get fixed?

**Comment by ecdsa** [comment]
ah, I did not see that the docs still had that :-)

**Comment by ecdsa** [comment]
fixed now
