### ISSUE TITLE
I want to get a normal Bitcoin wallet address

### ISSUE THREAD

**Issue by adamhydra3** [spesmilo/electrum#5602]
Hello. I can’t use exchangers, as I have some strange bitcoin wallet number. My friend is normal, constantly changing, but I always have the same and strange. Can I get a regular one? My wallet is also red.

**Comment by SomberNight** [comment]
Hi. See https://github.com/spesmilo/electrum/issues/5371#issuecomment-494778751
(substitute "Localbitcoins" with whatever lazy exchange you are using)
