### ISSUE TITLE
can't find libsecp256k1 library error

### ISSUE THREAD

**Issue by bloctavius** [spesmilo/electrum#5606]
I ran all of the installation instructions in the development version's README, but I got this error. 

I have bitcoin core v0.18 installed, so shouldn't I have libsecp256k1 installed?
```
(venv) zach@zach-desktop ~/electrum/electrum $ python3.6 run_electrum
Traceback (most recent call last):
  File "run_electrum", line 80, in <module>
    from electrum.logging import get_logger, configure_logging
  File "/home/zach/electrum/electrum/electrum/__init__.py", line 3, in <module>
    from .wallet import Wallet
  File "/home/zach/electrum/electrum/electrum/wallet.py", line 50, in <module>
    from .simple_config import get_config
  File "/home/zach/electrum/electrum/electrum/simple_config.py", line 13, in <module>
    from . import constants
  File "/home/zach/electrum/electrum/electrum/constants.py", line 30, in <module>
    from . import bitcoin
  File "/home/zach/electrum/electrum/electrum/bitcoin.py", line 34, in <module>
    from . import ecc
  File "/home/zach/electrum/electrum/electrum/ecc.py", line 45, in <module>
    do_monkey_patching_of_python_ecdsa_internals_with_libsecp256k1()
  File "/home/zach/electrum/electrum/electrum/ecc_fast.py", line 189, in do_monkey_patching_of_python_ecdsa_internals_with_libsecp256k1
    raise Exception('libsecp256k1 library not available. '
Exception: libsecp256k1 library not available. Verifying Lightning channels is too computationally expensive without libsecp256k1, aborting.
```

**Comment by willcl-ark** [comment]
I just encountered this also. To make it work, I had to install as per these instructions:

https://github.com/bitcoin-core/secp256k1#build-steps

**Comment by SomberNight** [comment]
> To make it work, I had to install as per these instructions:
https://github.com/bitcoin-core/secp256k1#build-steps

Also see https://github.com/spesmilo/electrum-docs/blob/master/libsecp256k1-linux.rst

Note: since merging the lightning branch, libsecp256k1 became a mandatory dependency (was optional before). The README was not updated since.

- We need to decide whether we want libsecp256k1 to be mandatory; or test whether `lightning` is enabled and only hard fail then.
- The README should be updated
- tar.gz source distributables also need to be considered

**Comment by bloctavius** [comment]
Thanks!  It's working now.

**Comment by bloctavius** [comment]
Oh, I should probably leave this open...

**Comment by SomberNight** [comment]
> We need to decide whether we want libsecp256k1 to be mandatory; or test whether lightning is enabled and only hard fail then.

Did this in https://github.com/spesmilo/electrum/commit/251db638af2f9c892a41af941b587729ba1c6771 for now
Longer term we could/should make libsecp256k1 mandatory. Still unsure... so keeping this issue open.

**Comment by ecdsa** [comment]
yes let's make it mandatory

**Comment by ecdsa** [comment]
it would be possible to list it as a python dependency, see https://github.com/electrumsv/electrumsv-secp256k1

**Comment by cool007zqw** [comment]
a lazy solution will be:
```bash
sudo apt install libsecp256k1-dev
```

**Comment by Tectract** [comment]
build / run fails because of this. It should be mentioned in the readme, or fixed internally to drag this lib in during install.

**Comment by Tectract** [comment]
> since merging the lightning branch, libsecp256k1 became a mandatory dependency
Can we get the option to build without lightning? Have no interest in using that, ever.

**Comment by SomberNight** [comment]
> Can we get the option to build without lightning? Have no interest in using that, ever.

What exactly do you mean?
Lightning is not enabled by default.

The topic of this thread is whether to make libsecp256k1 a mandatory dependency.
Lightning is related in that libsecp256k1 is definitely needed if Lightning is enabled.
However, completely irrespective of that, there are reasons it might make sense to always require libsecp256k1.

**Comment by Tectract** [comment]
Hmmmmmmm, I'm running into an error here:

    W | ecc_fast | failed to load libsecp256k1: OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory',)

I don't know how to bypass it. I have installed libsecp256k1 on my system. libsecp256k1.s.0 is in /usr/local/lib. 

I can't run the new version from a clean build. What do I do?

**Comment by SomberNight** [comment]
> I don't know how to bypass it. I have installed libsecp256k1 on my system. libsecp256k1.s.0 is in /usr/local/lib.
I can't run the new version from a clean build. What do I do?

That's a warning, not an error.
Try symlinking it to `/usr/lib`, see:
https://github.com/spesmilo/electrum-docs/blob/master/libsecp256k1-linux.rst#symlink-so-file

**Comment by Thecreator1** [comment]
This has still not been solved.
I know how to solve it but it is just sad and disappointing to see that you download the package to run it on a offline computer just to see this error being thrown at you.
Not only this because being able to run it offline is part of the security protocol so we do not want to have to connect the computer to the internet to download whatever missing libraries to make the thing work.
The package should run straight away out of the box without the need for any dependencies and there should be no exceptions to this.
I consider this a severe security issue.

**Comment by SomberNight** [comment]
>  The package should run straight away out of the box without the need for any dependencies and there should be no exceptions to this.

@Thecreator1 If you use the AppImage (or Mac/Windows binaries), there are no dependencies. It is self-contained.

If you use the source tarball, it only contains python sources. It does not contain the non-pure-python dependencies.
If you want to run from source, as the [README](https://github.com/spesmilo/electrum/blob/9380b331e472e00d9870eb4f57c0319c1da123c5/README.rst#getting-started) says, you have to provide the missing parts yourself. (mainly `libsecp256k1`, `cryptography`, and `pyqt5`)

**Comment by rwst** [comment]
I still get the error. It seems that pip installs an empty package:
```
$ sudo python3 -m pip install libsecp256k1
Collecting libsecp256k1
  Downloading libsecp256k1-0.1.tar.gz (814 bytes)
Building wheels for collected packages: libsecp256k1
  Building wheel for libsecp256k1 (setup.py) ... done
  Created wheel for libsecp256k1: filename=libsecp256k1-0.1-py3-none-any.whl size=1286 sha256=e13542554348e8262dd3f627a07f0f773a856e4260065062c74921f3f14a9c7f
  Stored in directory: /root/.cache/pip/wheels/cd/6d/2c/584fd7c3ba781e91c1451aac7ed4cc3e5869481d696ebcdb09
Successfully built libsecp256k1
Installing collected packages: libsecp256k1
Successfully installed libsecp256k1-0.1

$ sudo pip3 show libsecp256k1 -f
Name: libsecp256k1
Version: 0.1
Summary: Alpha Version
Home-page: https://a.slashdotmedia.com/www/delivery/ck.php
Author: Slash Dot Media
Author-email: admin@slashdotmedia.com
License: MIT
Location: /usr/lib/python3.6/site-packages
Requires: 
Required-by: 
Files:
  libsecp256k1-0.1.dist-info/INSTALLER
  libsecp256k1-0.1.dist-info/METADATA
  libsecp256k1-0.1.dist-info/RECORD
  libsecp256k1-0.1.dist-info/REQUESTED
  libsecp256k1-0.1.dist-info/WHEEL
  libsecp256k1-0.1.dist-info/top_level.txt
  slashdot/__init__.py
  slashdot/__pycache__/__init__.cpython-36.pyc

```
Also, the given home page is empty. This makes electrum-4.0.9 unusable.

**Comment by Tectract** [comment]
> build / run fails because of this

It's not a warning if you can't build because of it, it's an error. Users should never need access to /usr/lib, so it should look in /usr/local/lib for any libs it needs for a normal user install.

**Comment by SomberNight** [comment]
@rwst see [README](https://github.com/spesmilo/electrum/blob/1c52203346f9049f6c3fe201f672960339d8273b/README.rst#not-pure-python-dependencies)

`libsecp256k1` is not a pip package, it is a `.so` library

@Tectract
> It's not a warning if you can't build because of it, it's an error

It used to be a warning when it was not a required dependency; it is an error since it became required.
