### ISSUE TITLE
what format should the recovery be line with the addresses?

### ISSUE THREAD

**Issue by badhitman** [spesmilo/electrum#5607]
I want to recover the wallet (read-only) from the bitcoin address list. how do I send back a string with address (e.g., 3 addresses at once)? I tried tab and space bar `electrum restore XXXXXXXXXXXXX YYYYYYYYYYYYYYY ZZZZZZZZZZZ`. The parameter is incorrect.

https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L218

**Comment by SomberNight** [comment]
try using quotes:
`electrum restore "addr1 addr2 addr3"`

**Comment by badhitman** [comment]
> try using quotes:
> `electrum restore "addr1 addr2 addr3"`

thanks bro. I tried everything but didn't think of it.
