### ISSUE TITLE
all methods of the json rpc commands become asynchronous?

### ISSUE THREAD

**Issue by badhitman** [spesmilo/electrum#5608]
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L218

I noticed in the json rpc file that the async qualifier has now been added to all methods. In my version 3.3.8 downloaded from the site I see that there are no qualifiers for the same methods. What's the meaning of that? in the new version, all these methods will work differently? how can this affect the performance of the jsonrpc interface?

**Comment by ecdsa** [comment]
yes they are all async. it should not afffect performance.
one notable distinction is that the --timeout parameter can be passed to all commands
