### ISSUE TITLE
Offer stability control. json rpc -> restore

### ISSUE THREAD

**Issue by badhitman** [spesmilo/electrum#5610]
there is a method of wallet recovery. here it is:
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L218

here is an attempt to read the user data string:
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L224

this method is called:
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/wallet.py#L2164

and look in this method that is happening. first, the presence of the wallet file is checked.
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/wallet.py#L2171

if it exists an error falls out. bang:
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/wallet.py#L2172

why so strict? let's go back to the jsonrpc method.
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L230

 what should he return?

```python
return
{
   'path': d['wallet'].storage.path,
   'msg': d['msg'],
}
```

Why not return an error message? To describe it in detail. Example:
```python
return
{
   'path': '',
   'msg': 'Remove the existing wallet first!',
}
```

or even so:

```python
try:
	d = restore_wallet_from_text(text,
			path=self.config.get_wallet_path(),
			passphrase=passphrase,
			password=password,
			encrypt_file=encrypt_file,
			network=self.network)
except Exception:
	return
	{
	   'path': '',
	   'msg': 'there would be to get the text from the inner exception. I don't speak Python. it's probably possible as that to',
	}
else:
	return
	{
	   'path': d['wallet'].storage.path,
	   'msg': d['msg'],
	}
```

there are many similar examples when jsonrpc throws an error and a stack trace. it would be desirable more stability and instead of trace the distinct clear answer in the form of valid json returned

> this will increase friendliness and bug tolerance. programmers will be pleased to see a clear concrete answer instead of a stack trace. Thanks

**Comment by ecdsa** [comment]
exceptions are now better handled.
please open a new issue if needed
