### ISSUE TITLE
error importing a large number of addresses.

### ISSUE THREAD

**Issue by badhitman** [spesmilo/electrum#5611]
using json rpc are trying to restore a wallet with addresses. it's here:
https://github.com/spesmilo/electrum/blob/3d7cb935ff6a262c58018408f3c19cf7e5221472/electrum/commands.py#L218

an example of a command:
```
electrum restore "xxxxxxxxxx yyyyyyyyyy"
```

so I'm trying to send 360 addresses. in the first command displays a curious trace:
```
[ecc] info: libsecp256k1 library not available, falling back to python-ecdsa. This means signing operations will be slower.
Recovering wallet...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum/interface.py", line 198, in get_socket
    s = context.wrap_socket(s, do_handshake_on_connect=True)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrum/util.py", line 882, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/usr/local/lib/python3.5/dist-packages/electrum/network.py", line 1085, in run
    self.wait_on_sockets()
  File "/usr/local/lib/python3.5/dist-packages/electrum/network.py", line 1067, in wait_on_sockets
    self.process_responses(interface)
  File "/usr/local/lib/python3.5/dist-packages/electrum/network.py", line 719, in process_responses
    self.process_response(interface, response, callbacks)
  File "/usr/local/lib/python3.5/dist-packages/electrum/network.py", line 646, in process_response
    if error is None and result > 0:
TypeError: unorderable types: NoneType() > int()
```

as a result, there are only about 100 addresses in the restored wallet. sometimes 101 sometimes 102. Strange that the value is not constant, but about 100

**Comment by badhitman** [comment]
tried locally and through ssh on other server on the Internet. tracing errors out only locally. through ssh I did not see the trace at all. the console took command and reported that successfully restored. but only 101 addresses are added remotely. a locally 102, but with error tracing. in both cases, the same command was used to restore the wallet from 360 addresses.

**Comment by badhitman** [comment]
addresses are restored locally. the console displays an error, but the addresses are imported. via ssh why it did not work the same. perhaps ssh itself imposes restrictions on the sent command line?

**Comment by badhitman** [comment]
> 
> 
> tried locally and through ssh on other server on the Internet. tracing errors out only locally. through ssh I did not see the trace at all. the console took command and reported that successfully restored. but only 101 addresses are added remotely. a locally 102, but with error tracing. in both cases, the same command was used to restore the wallet from 360 addresses.

addresses are restored locally. the console displays an error, but the addresses are imported. via ssh why it did not work the same. perhaps ssh itself imposes restrictions on the sent command line?

**Comment by SomberNight** [comment]
That traceback you have in the OP is really weird. From that it seems you are using a version of Electrum older than 3.3.0. Also, python <3.6 is no longer supported (well, in newer versions of Electrum).
Could you please test with either latest release or master?

**Comment by badhitman** [comment]
My mistake. I have two versions on my local computer. one long established with a symbolic reference to it. but I've been using Appimage for a long time. her recovery went well. Thanks

**Comment by badhitman** [comment]
on the remote ssh machine Ubuntu 18.4 and there is a Electrum3.3.8. Why this recovery does not pass through ssh is not yet clear

**Comment by SomberNight** [comment]
there might be some shell limitation to length of a parameter?? or length of a command?
100 addresses * (say) 40 chars is 4000 characters already
