### ISSUE TITLE
load_wallet CLI/RPC not working

### ISSUE THREAD

**Issue by domob1812** [spesmilo/electrum#5614]
Since the recent merge of Lightning support to `master`, it seems that I can no longer load wallets from the CLI/RPC interface (and consequently also not execute any wallet-related RPCs).

`electrum daemon load_wallet` throws a usage error and "unrecognized arguments: load_wallet", while `electrum load_wallet` simply returns `true` but I still cannot execute RPCs against wallets afterwards.

Looking at the code, the wallet-related methods (e.g. `Daemon.load_wallet`) are not marked as `async` like the other methods are now (e.g. `ping`, whichi works fine for me over RPC).  Does that mean this functionality is simply not fully converted and will be later, or am I doing something wrong?

**Comment by ecdsa** [comment]
"electrum load_wallet" is the correct way
if you still cannot execute RPCs then you should explain how they ffail

**Comment by domob1812** [comment]
When I do `electrum load_wallet -w /path/to/wallet`, it returns `true` and the log of Electrum itself shows this line:

    I | simple_config.SimpleConfig | electrum directory /home/daniel/.electrum

Afterwards, an CLI command like `electrum getbalance` actually works.  But an RPC call for the same method returns a "500 Internal Server Error" to the client, and shows this in the log:

    E | daemon.Daemon | error handling request: {"jsonrpc": "2.0", "id": "spk78pki", "method": "getbalance"}
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/dispatcher.py", line 124, in handle_exceptions
        yield handler
      File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py", line 40, in safe_call
        methods.items[request.method], *request.args, **request.kwargs
      File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py", line 34, in call
        return await validate_args(method, *args, **kwargs)(*args, **kwargs)
      File "/home/daniel/Projekte/electrum-nmc/electrum/commands.py", line 102, in func_wrapper
        raise Exception("wallet not loaded. Use 'electrum daemon load_wallet'")
    Exception: wallet not loaded. Use 'electrum daemon load_wallet'

**Comment by domob1812** [comment]
Also note that if `electrum load_wallet` is the correct command, then the error message logged is wrong.

**Comment by ecdsa** [comment]
A CLI command is an RPC call.

**Comment by domob1812** [comment]
Yes, but what I mean when I say RPC call is that I do the RPC call with an external tool manually ([jsonrpclib](https://github.com/joshmarshall/jsonrpclib) in my case, with an URL like `http://user:password@localhost:rpcport/`).  For some reason that generates the error shown in the log above, while the CLI itself works.

**Comment by domob1812** [comment]
The reason for that seems to be that the `Commands` instance assumes the wallet is passed as first argument for functions annotated as "needs wallet", e.g. like `Daemon.run_cmdline` does when it calls a command.  (And in fact, calling `run_cmdline({"cmd": "getbalance"})` via my RPC client works!)

Apparently the wallet is not passed correctly by direct RPC calls to the methods, like `getbalance()` itself on the JSON-RPC server.

I assume this is either a bug with the JSON-RPC server (it should intercept calls to those methods and add the wallet to them), or the JSON-RPC interface should not expose those methods at all and require everyone to call `run_cmdline` just like the `electrum` CLI client does.

**Comment by SomberNight** [comment]
Could you provide instructions to reproduce your issue?

E.g. this works for me:
```
curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"load_wallet"}' http://user:pass@127.0.0.1:7777
curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"getbalance"}' http://user:pass@127.0.0.1:7777
```

**Comment by ecdsa** [comment]
what changed since the last version is that you need to add the jsonrpc version: "jsonrpc":"2.0"

**Comment by domob1812** [comment]
@SomberNight:  That's very interesting - your commands also work for me.  However, what doesn't work for me is this:

    ./run_electrum load_wallet
    curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"getbalance"}' http://user:pass@127.0.0.1:7777

I.e. it seems that the CLI for `load_wallet` does not work, even though a direct RPC for `load_wallet` *does* work to load the wallet.  However, this *does* work for me:

    ./run_electrum load_wallet
    ./run_electrum getbalance

> what changed since the last version is that you now need to add the jsonrpc version: "jsonrpc":"2.0"

Ok, but that is not the issue here.  The logs show that the `"jsonrpc":"2.0"` is included in the request (and always was in my trials), and also non-wallet RPCs always worked fine for me.

**Comment by SomberNight** [comment]
> However, what doesn't work for me is this:
```
./run_electrum load_wallet
curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"getbalance"}' http://user:pass@127.0.0.1:7777
```

Ok, I can reproduce.
