### ISSUE TITLE
Windows Defender "Triggre" Trojan alert when building binaries for windows.

### ISSUE THREAD

**Issue by buhrmi** [spesmilo/electrum#5615]
Hi all,

just following the steps described here, using Docker Desktop for Windows, running Ubuntu 18.04 inside WSL 2.

when running
```
sudo docker run -it \
    --name electrum-wine-builder-cont \
    -v $PWD:/opt/wine64/drive_c/electrum \
    --rm \
    --workdir /opt/wine64/drive_c/electrum/contrib/build-wine \
    electrum-wine-builder-img \
    ./build.sh
```

Windows Defender activates itself multiple times with trojan warnings:
![](https://i.imgur.com/8DvLpvU.png)
![](https://i.imgur.com/95JDJCC.png)

The Fuerboos alert seems to be known as a false positive ( https://github.com/spesmilo/electrum/issues/4172). What about the other one?

**Comment by ecdsa** [comment]
see the note on https://electrum.org/#download
