### ISSUE TITLE
Malicious OP_RETURN data via Electrum wallet?

### ISSUE THREAD

**Issue by panagiotos** [spesmilo/electrum#5619]
This article states that "Attackers are sending Bitcoin loaded with malicious OP_RETURN data via Electrum wallet". Is there a risk of using Electrum Wallet?

Source : https://thenextweb.com/hardfork/2019/09/04/glupteba-malware-bitcoin-blockchain-cryptocurrency-electrum-wallet/

**Comment by ecdsa** [comment]
this looks like a piece of fud...

**Comment by SomberNight** [comment]
from linked article:
> The malware, which has been programmed with a hardcoded ScriptHash string, will then make its way through a public list of Electrum servers to find every transaction that was made by the attacker.
> Buried in those transactions is seemingly innocent OP_RETURN data which contains an encrypted C&C domain. The ScriptHash string is then used to decrypt that data.

So malware coders use Electrum.

> This article states that "Attackers are sending Bitcoin loaded with malicious OP_RETURN data via Electrum wallet". Is there a risk of using Electrum Wallet?

I heard terrorists drink water and wear shoes. You should not drink water and wear shoes then.

**Comment by panagiotos** [comment]
So electrum used by terrorists?

**Comment by SomberNight** [comment]
I did not say that. You are clearly missing the point.
