### ISSUE TITLE
electrum set transaction fee manually via cli

### ISSUE THREAD

**Issue by reardenlife** [spesmilo/electrum#5620]
I am trying to set the *fee_per_kb* manually as was suggested here: https://github.com/spesmilo/electrum/issues/2447#issuecomment-304517990

```bash
$ electrum setconfig fee_per_kb 1000
$ cat /root/.electrum/config | jq .fee_per_kb
1000
```

Then I am starting daemon and seeing a different fee:
```bash
$ electrum daemon status | jq .fee_per_kb
20191
```

So .. how to set the transaction fee manually?

**Comment by SomberNight** [comment]
You also need to disable dynamic fees:
`electrum setconfig dynamic_fees False`
