### ISSUE TITLE
get error when broadcast

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5622]
error info:
Script evaluated without error but finished with a false/empty top stack element 

raw_tx:
0200000001b22de80202c36ccebd9930a8da5f58acefe55f21ea4190f9195437d92629fb3101000000d90047304402200f2181ae0ee9198c8126407db834e1daf97566315083254ede1a2f98068d9886022069919aaeb6c5bbc88244564a87e44bfebd1e9915e90418dcc56291329b6b3d1b0147304402200f2181ae0ee9198c8126407db834e1daf97566315083254ede1a2f98068d9886022069919aaeb6c5bbc88244564a87e44bfebd1e9915e90418dcc56291329b6b3d1b0147522103d5d7b78e97094116c3f98f51b96f02981a787848b0ee6f244ea2b27f4108c95e2102518e6b6a9b1136851901af148ebeb282db0db8547d629d15a378abdbb953659c52aefeffffff02b0ad01000000000017a91404b9971e2c769074b12547eb8660c7f6435d386e87e2e402000000000017a9147f1f76646bc0739c583aace1bea363a06c3af1bb8722101800

**Comment by shuaiLiWang** [comment]
system is android @ecdsa

**Comment by shuaiLiWang** [comment]
@SomberNight please the issues

**Comment by ecdsa** [comment]
how did you create the transaction?

**Comment by ecdsa** [comment]
the input has twice the same signature, that's why it fails.
(multisig 2 of 2)

**Comment by shuaiLiWang** [comment]
> the input has twice the same signature, that's why it fails.
> (multisig 2 of 2)

0200000001b22de80202c36ccebd9930a8da5f58acefe55f21ea4190f9195437d92629fb3101000000d90047304402200f2181ae0ee9198c8126407db834e1daf97566315083254ede1a2f98068d9886022069919aaeb6c5bbc88244564a87e44bfebd1e9915e90418dcc56291329b6b3d1b0147304402203019e68eb5887287580bf93587b12b909eb09fc792282984fcb3466b8e92bb12022042aef0f4c873670040d146b92b1d141fb468f8c9e45e4cb80cb7e77f6ed58d7f0147522102518e6b6a9b1136851901af148ebeb282db0db8547d629d15a378abdbb953659c2103d5d7b78e97094116c3f98f51b96f02981a787848b0ee6f244ea2b27f4108c95e52aefeffffff02b0ad01000000000017a91404b9971e2c769074b12547eb8660c7f6435d386e87e2e402000000000017a9147f1f76646bc0739c583aace1bea363a06c3af1bb8732101800

i have changed, this is new tx, also have the save error

**Comment by shuaiLiWang** [comment]
> > the input has twice the same signature, that's why it fails.
> > (multisig 2 of 2)
> 
> 0200000001b22de80202c36ccebd9930a8da5f58acefe55f21ea4190f9195437d92629fb3101000000d90047304402200f2181ae0ee9198c8126407db834e1daf97566315083254ede1a2f98068d9886022069919aaeb6c5bbc88244564a87e44bfebd1e9915e90418dcc56291329b6b3d1b0147304402203019e68eb5887287580bf93587b12b909eb09fc792282984fcb3466b8e92bb12022042aef0f4c873670040d146b92b1d141fb468f8c9e45e4cb80cb7e77f6ed58d7f0147522102518e6b6a9b1136851901af148ebeb282db0db8547d629d15a378abdbb953659c2103d5d7b78e97094116c3f98f51b96f02981a787848b0ee6f244ea2b27f4108c95e52aefeffffff02b0ad01000000000017a91404b9971e2c769074b12547eb8660c7f6435d386e87e2e402000000000017a9147f1f76646bc0739c583aace1bea363a06c3af1bb8732101800
> 
> i have changed, this is new tx, also have the save error

on testnet

**Comment by shuaiLiWang** [comment]
> the input has twice the same signature, that's why it fails.
> (multisig 2 of 2)

0200000001b22de80202c36ccebd9930a8da5f58acefe55f21ea4190f9195437d92629fb3101000000d90047304402200f2181ae0ee9198c8126407db834e1daf97566315083254ede1a2f98068d9886022069919aaeb6c5bbc88244564a87e44bfebd1e9915e90418dcc56291329b6b3d1b0147304402203019e68eb5887287580bf93587b12b909eb09fc792282984fcb3466b8e92bb12022042aef0f4c873670040d146b92b1d141fb468f8c9e45e4cb80cb7e77f6ed58d7f0147522102518e6b6a9b1136851901af148ebeb282db0db8547d629d15a378abdbb953659c2103d5d7b78e97094116c3f98f51b96f02981a787848b0ee6f244ea2b27f4108c95e52aefeffffff02b0ad01000000000017a91404b9971e2c769074b12547eb8660c7f6435d386e87e2e402000000000017a9147f1f76646bc0739c583aace1bea363a06c3af1bb8732101800

i have changed, this is new tx, also have the same error
on testnet

**Comment by shuaiLiWang** [comment]
now i want sign by smart card, the pubkey read from smart card is 0200ae7963c26f7d3657021756a69331ea3f776f601fcaad463c4261eb22d01bd0 and 03b810de35e7a5302a0804241adf998213a382e9c6ea03b9e2abca5943ff331aee, the two pubkeys is master public 

> how did you create the transaction?

now i want sign by smart card, the pubkey read from smart card is 0200ae7963c26f7d3657021756a69331ea3f776f601fcaad463c4261eb22d01bd0 and 03b810de35e7a5302a0804241adf998213a382e9c6ea03b9e2abca5943ff331aee, the two pubkeys is master public

**Comment by shuaiLiWang** [comment]
> how did you create the transaction?

now i want sign by smart card, the pubkey read from smart card is 0200ae7963c26f7d3657021756a69331ea3f776f601fcaad463c4261eb22d01bd0 and 03b810de35e7a5302a0804241adf998213a382e9c6ea03b9e2abca5943ff331aee, the two pubkeys is master public

**Comment by shuaiLiWang** [comment]
> how did you create the transaction?

![xpub](https://user-images.githubusercontent.com/9347690/64408193-bd4cd600-d0b8-11e9-8079-6987c22b5afb.png)
the xpub info is stitched together like this，and Unable to modify

**Comment by ecdsa** [comment]
sorry, but is your initial issue resolved?

**Comment by shuaiLiWang** [comment]
> sorry, but is your initial issue resolved?
 yes thank you

**Comment by ecdsa** [comment]
you deleted the message about how you created the transaction.
should this issue be closed?
