### ISSUE TITLE
electrumx.ml in servers.json  is a phishing/bogus server, and should be banned 

### ISSUE THREAD

**Issue by user20190912** [spesmilo/electrum#5632]
In the servers.json, I found an entry electrumx.ml

This turns out to be a phishing ElectrumX server, which tries to direct users to "upgrade" to the bonus version of Electrum.

To find this out, just send   blockchain.transaction.broadcast  to the server, and it will return some HTML code which asks the user to install "an important security update".

**Comment by SomberNight** [comment]
Indeed, thanks.
We have already removed it from master in https://github.com/spesmilo/electrum/commit/01f582cc147fcd84555e7e13e366c397c85f7c78.

**Comment by jbumgarner** [comment]
The servers.json file in Electrum 3.3.8 still contains electrumx.ml.  On August 29, this domain was removed from the servers.json.  Most endpoint detection security applications have this server blacklisted.  How did this server get added back to the servers.json file?

**Comment by SomberNight** [comment]
> How did this server get added back to the servers.json file?

It did not get added back. 3.3.8 was released on July 11.

**Comment by jbumgarner** [comment]
This entry is the servers.json file for 3.3.8, which was downloaded from [here](https://electrum.org/#download)

"electrumx.ml": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },

It seems to be the same server.

**Comment by SomberNight** [comment]
@jbumgarner 
Again, 3.3.8 was released prior to this change.
Also answered in the new issue you opened: https://github.com/spesmilo/electrum/issues/5837#issuecomment-565069778

**Comment by jbumgarner** [comment]
Ok.  When will the next version be released that has the change?
