### ISSUE TITLE
Feature request : Autoupdate servers list 

### ISSUE THREAD

**Issue by panagiotos** [spesmilo/electrum#5637]
Updating servers list from trusted source ( eg electrum.org ) when client starts or after it started. This will avoid offline and bad servers. Are there any other use cases?

**Comment by undeath** [comment]
Currently the server list is updated with every release. This means it is understandable and verifiable what servers an electrum client contacts first (to receive more available servers). Adding some kind of auto-update mechanism means adding trust to a centralized server that may, for whatever reason, turn malicious and whose results may be impossible to replicate.

**Comment by panagiotos** [comment]
The client uses a centralized mechanism to check for new client version update. Even if electrum.org gets in to wrong hands the private key used to sign version number protects from malicious attacks. This mechanism can be implemented to servers also.

**Comment by SomberNight** [comment]
Providing a trusted list of servers requires creating one in the first place. We don't have the capacity to vet server operators nor do we want to. It would also mean the centrally hosted list is a single point of failure and we would need to make sure it always stays available.

> The client uses a centralized mechanism to check for new client version update

Note that the endpoint clients query for the latest version is not critical infrastructure as (1) the whole check is actually opt-in, (2) even if enabled, if the endpoint is down the client ignores the error and continues to function.

Anyone can run a public server and help serve clients. The protocol and the client itself is supposed to be designed in such a way such that there is not much a malicious server could do to harm a client; when this is not the case then that needs to be fixed.

The hardcoded list of servers is used as a bootstrap mechanism; servers also do peer discovery among each other, and the client queries servers for further server peers.

-----

> Updating servers list from trusted source ( eg electrum.org ) when client starts or after it started. This will avoid offline and bad servers. Are there any other use cases?

> offline servers

It's not a problem if some servers are offline. The client will try to connect, fail, and then try other servers.

> bad servers

If we set up a new endpoint that hosts a list of trusted servers, I assume you envision clients first querying that and trying to only connect to servers on that list. What if the same people who host the bad (I assume you meant malicious) servers DDOS-es the central endpoint? If clients failover to something akin to the current mechanism then there was no point in hosting the endpoint at all; and if clients do not failover but rather refuse to function then that endpoint becomes critical infrastructure that must be kept available at all times that we do not have the resources for (and we will not introduce single points of failures).
