### ISSUE TITLE
ERROR:Signature must be zero for failed CHECK(MULTI)SIG operation when Broadcast 

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5645]
os : andriod
segwit:true
testnet
raw tx：02000000000101b34d7311d819f43101cb547e985d6caa278a7989901a0215f459afd23b62dd210100000000feffffff021027000000000000220020f2abd1359cbf12d275504e0b33757020bad5a2462a90871ccb285c12e7c428e35f4d000000000000220020f2abd1359cbf12d275504e0b33757020bad5a2462a90871ccb285c12e7c428e30400473044022011c2e51780b4567994652ebfd81be4d129fce516afee363eb85e7fbab79d7b0802204a292b88ab12341e9ce5ee5d16a6c44d7e9ed275ce26d1f5eb0add9baf97d74a01483045022100fd35c875f8e86e6f5d1cbfcfb6ee84ba2117d670c287f44b2a3640ec2be3248a022076c035f1345448a80a7350c9eea25872b1708e6603298f739330e07d756e1b25014752210366575835e881949e83a87933d48ad07dadde21021bbb0103e8582e6a2e65427c2103964f0a9fd43028d378c357e452eb3033bd640911741cb8c356c80363e0a6582052ae50171800

**Comment by SomberNight** [comment]
How did you create the transaction?

**Comment by shuaiLiWang** [comment]
> How did you create the transaction?

I have found the reason. The order of the signature and the public key is incorrect. but not solved.

**Comment by SomberNight** [comment]
Did you create the transaction using Electrum? How? Do you have steps to reproduce? Did it happen as a consequence of you modifying the source?

**Comment by SomberNight** [comment]
not info info to debug; also not clear if (still) relevant
