### ISSUE TITLE
create multi-signature wallet by segwit master key 

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5647]
I create two wallet for segwit, now I want to create a multi-signature wallet used a master key
when i import the master public key ,i get the error  "Wrong key type p2wpkh"

**Comment by SomberNight** [comment]
You provided a `zpub`, but p2wsh multisig needs a `Zpub`.
Start creating a 2of2 multisig wallet in the wizard, choose I already have a seed, enter the seed, and then on the next screen it will show you what master public key you should share with your cosigners.

With legacy seeds, you could just reuse the single-signer xpub for multisig too, but this resulted in the reuse of the individual ecdsa public keys, which is a privacy leak on-chain. To counter this, for segwit seeds, it was decided we would derive different keys for singlesig and multisig, and show different and incompatible master public keys to the user.
