### ISSUE TITLE
Electrum 3.3.8 Problem

### ISSUE THREAD

**Issue by Pkrushkov** [spesmilo/electrum#5648]
![Screenshot from 2019-09-20 14-39-50](https://user-images.githubusercontent.com/55587163/65326398-08d3a980-dbba-11e9-8653-a27c891f7e3b.png)
![Screenshot from 2019-09-20 14-41-20](https://user-images.githubusercontent.com/55587163/65326399-08d3a980-dbba-11e9-8915-5228f94cd2cd.png)

**Comment by SomberNight** [comment]
May I ask, do you really have 331k BTC in that wallet?
Did it the wallet file get corrupted somehow? What kind of disk/filesystem do store it on?

Try restoring from seed words.

**Comment by SomberNight** [comment]
Note: a change of value in txi/txo could cause undetected balance-change; though it probably wouldn't explain those tx broadcast error dialogs.

**Comment by ecdsa** [comment]
closing; no answer from OP.
