### ISSUE TITLE
Build image failed (for windows)

### ISSUE THREAD

**Issue by wartjugger** [spesmilo/electrum#5650]
Following the instructions in https://github.com/spesmilo/electrum/tree/master/contrib/build-wine

the image building process stops, after 295 archives were fetched, with the following error:

> E: Failed to fetch https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-amd64/wine-stable-amd64_4.0~bionic_amd64.deb  Connection failed [IP: 151.101.114.217 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I tried twice, it fails at the same error. BTW I had no issues with the linux image.

I found this error mentioned in https://forum.winehq.org/viewtopic.php?p=120410

**Comment by SomberNight** [comment]
Travis also runs this build only every commit, and indeed it sometimes randomly fails, but it often succeeds.
My first suggestion hence would just be to simply retry a few times.

**Comment by wartjugger** [comment]
Thanks, running it again later worked.
