### ISSUE TITLE
payto command results in get_spendable_coins error

### ISSUE THREAD

**Issue by kkoenen** [spesmilo/electrum#5654]
When I issue a `electrum -v payto address amount`, the application responds with

`get_spendable_coins() takes 2 positional arguments but 3 were given`

Please advice.

**Comment by SomberNight** [comment]
What version of Electrum? Sounds like this might be master from a few days ago (before https://github.com/spesmilo/electrum/commit/a1d7d39f687c2dd6e7a1c812a589bab708b326cc).
Either use the latest release, or pull master again.
