### ISSUE TITLE
feature request:  Add "Offline" Button to Electrum 

### ISSUE THREAD

**Issue by skyerjoe** [spesmilo/electrum#5655]
It will be great to have on Button to switch the Electrum Walett in an "offline mode"

Even for tor u have to close the tor Browser but when use  the Tor-Net often it's not the best bet.

regards

**Comment by SomberNight** [comment]
Could you explain what exactly your use case is; what you would intend to do with such a mode?

Note that you can already start the application with the `--offline` flag, in which case it will not try to connect to servers. Is this what you want?

**Comment by skyerjoe** [comment]
Yes but my assumption was that will enhance also the security against things like "MITM"
if u can decide to only connect with the server if i want to create an transaction for example in an easy way.

or is this not the case  
and im off the track ?

best regards

**Comment by ecdsa** [comment]
no that's not the case

**Comment by skyerjoe** [comment]
could u explain that a little bit more precisely why it it so   

best regards

**Comment by SomberNight** [comment]
That was the local jsonrpc server. That requires no network connectivity. The vulnerability there was that anything that could access localhost could interact with the server as well. It was fixed by password-protecting the endpoint.
You need to be clear about what it is you are proposing/asking.

**Comment by skyerjoe** [comment]
@SomberNight: 
Thanks for clarification 

b2topic: 
No i just want to know why it doesn't enhance the common security from electrum.
My knowledge about deeper security topics is limited so i want to understand this. 

best regards

**Comment by ecdsa** [comment]
you might want to look at cold storage if you want your private keys to be offline.
adding an offline button is not useful
