### ISSUE TITLE
Error sending bitcoin

### ISSUE THREAD

**Issue by flinchwymer** [spesmilo/electrum#5657]
First time using Electrum and I managed to receive some bitcoin into my wallet but it won't let me send from it. I get the error message - 
"The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.
Transaction could not be broadcast due to dust outputs."

Can anyone help?

**Comment by AbdussamadA** [comment]
please close this issue. you've been told countless times that all you have to do is change the base unit to btc.
