### ISSUE TITLE
BTCP Electrum Wallet 

### ISSUE THREAD

**Issue by CEGE81** [spesmilo/electrum#5659]
Hello, 
i have installed my Electrum BTCP Wallet on an new device and connected it with my Ledger. 
The Problem is that die Balance is "matured". Means it is not verified. I have received this in March 2018. It must be verified. And it was verified on my old device. 
Anyone some ideas??

**Comment by ecdsa** [comment]
altcoin

**Comment by CEGE81** [comment]
What is this for an answer???
Very helpful!! And why you closed it??

**Comment by ecdsa** [comment]
because you are not using our software, Electrum.
we do not provide support for altcoins
