### ISSUE TITLE
Unclear which wallet I pay from

### ISSUE THREAD

**Issue by vporton** [spesmilo/electrum#5663]
In the Send tab there is Receiver and no Payer. So it is unclear which of my several wallets I pay from. It is a bug.

**Comment by SomberNight** [comment]
The whole "main window" corresponds to a single wallet. In which window the "Send" tab is, that is the wallet you are paying from.
Also, you can do coin selection or "from address" selection in the "Coins" and "Addresses" tabs (correspondingly). See e.g. `View`>`Show Coins`.
