### ISSUE TITLE
electrum mobile connecting to hidden service ssl

### ISSUE THREAD

**Issue by Tracachang** [spesmilo/electrum#5664]
When connecting electrumwallet  mobile to a hidden service it does not connect since mobile version doesn't allow to add a ":t" to force clearnet so SSL port must be used. 

Would it be possible to add a way to force clearnet as we already have in desktop (using command :t) ?

Thank you

https://twitter.com/hardmonies/status/1177678811665747974?s=19

**Comment by SomberNight** [comment]
please don't open duplicates
https://github.com/spesmilo/electrum/issues/5278

**Comment by Tracachang** [comment]
Apologies, didn't see it.
