### ISSUE TITLE
Payments failed

### ISSUE THREAD

**Issue by rocky70** [spesmilo/electrum#5674]
I made two separate orders on a Market site, in the BTC confirmations: in the first I have two transaction addresses, and in the second payment I have one of the addresses of the first, but no confirmation, instead in my portfolio it shows me a single transaction .. . but with the amount of the two orders, but without any confirmation, you can help me because I don't know how to proceed, thanks

**Comment by SomberNight** [comment]
nothing specific to go on. probably not directly related to any issue with Electrum
