### ISSUE TITLE
Reconnects every few seconds while on proxy

### ISSUE THREAD

**Issue by h2o10** [spesmilo/electrum#5679]
Latest release.
Wallet reconnects every few seconds while on proxy.

https://imgur.com/a/keFcplK

**Comment by SomberNight** [comment]
You should [enable debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging) and upload your logs.

**Comment by SomberNight** [comment]
There are many reasons this could happen, some of which are server-side.
