### ISSUE TITLE
No history, connection error in log

### ISSUE THREAD

**Issue by dorianbz** [spesmilo/electrum#5682]
Hello,

I no longer have access to the transaction history.
The connection indicator is green, it indicates the last block.

I have activated the log and I see that there are errors.

Attached is the log file

Thank you for your help

[electrum_log_20191006T170917Z_15636.log](https://github.com/spesmilo/electrum/files/3694679/electrum_log_20191006T170917Z_15636.log)

**Comment by SomberNight** [comment]
The errors are not that interesting. The client seems to be able to successfully connect to multiple servers.

Is the history tab empty? Did it used to have some transactions that at some point "disappeared"?
Check in the "Addresses" tab, do you see the expected addresses? Check the history of some of the addresses in a block explorer (e.g. blockstream.info); see if they have a history.

**Comment by dorianbz** [comment]
Hi,

Thanks, I realize that I used the wrong seed.

My bad, thanks for your help
