### ISSUE TITLE
P2PKH-P2SH unhardened derivation unexpected addresses

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#5683]
I've been trying to import a BIP39 seed phrase as a standard wallet but am not generating the expected addresses.

My wallet's ypub is 
ypub6ZK3zL1nwM563yxCQMDC3s6QVLzoLJenPDSFVwELNuq9CdTAHDu4W8TVDVScCuq2CHAFiov84gnW3ZXWEzYYcnVmfdNtia64vwvvPsKRkAW

I select "p2sh-segwit" and override the derivation path to be (unhardened) m/49/0/2

I expect that the first address derived at m/49/0/2/0/0 will be 383THG9V1ZPT9eoaJKBaqf1UeEZb4ycJH4 but Electrum generates 39Ea1CMSFhf4MCi6HP2fbEhkWxqe2jgNet

The second address m/49/0/2/0/1 should be 3Gsvi4QXtnivXdQ6gYG1epNhtwpud1xhos but Electrum generates 3KeP58pyuKcjHGKcZSYfwbcEoHRPTAatPk

I verified that the addresses I expect should be correct by using https://iancoleman.io/bip39/

Let me know if any additional information would help you debug / reproduce

**Comment by SomberNight** [comment]
Can you give a specific bip39 seed example? Is this with a hardware wallet?
You cannot specify a derivation path if you restore from a ypub.

**Comment by jlopp** [comment]
Well, I honestly don't know how I managed to reproduce this issue incorrectly the same way half a dozen times. But now I started over from scratch and am unable to reproduce - derivation works as intended. Can only assume I had written down the wrong but valid seed phrase and was copy/pasting it.
