### ISSUE TITLE
Electrum mnemonic to seed

### ISSUE THREAD

**Issue by jtomtan** [spesmilo/electrum#5684]
Hi, 

Where can I find the code logic for how to convert Electrum mnemonic (v2) to seed ?

Thanks.

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/blob/a51a2a7f8f822a63b5f04a26229bc12cbd937343/electrum/mnemonic.py#L131-L137

**Comment by ecdsa** [comment]
see also https://electrum.readthedocs.io/en/latest/seedphrase.html
