### ISSUE TITLE
electrum addrequest returns false

### ISSUE THREAD

**Issue by realSConway** [spesmilo/electrum#5693]
Hello all,
I have a question, hope you can help or point me in the right direction.

I'm running Electrum 3.3.8 on a raspberry pi.
My second pi is full btc node, so I run electrum demon with: `electrum daemon start --oneserver --server pi3:50002:s` to use it to validate transactions.

Electrum payment requests were working a few days a go, until today.
When I create a payment request. it just returns `false`.
```
user@pi2:~> electrum addrequest 3.14 -m "this is a test"
false
user@pi2:~>
```

What logs can I check out to troubleshoot this?

Thanks in advance.
Samuel

**Comment by AbdussamadA** [comment]
try adding --force. the reason it's giving you the false output is because it's hit the gap limit. if you use force it'll do it regardless.

**Comment by realSConway** [comment]
SOLVED! @AbdussamadA  you're a star!

Running `electrum addrequest 3.14 -m "this is a test" --force`
Returned JSON message I was expecting.

Now how could I have figured that out myself?

**Comment by AbdussamadA** [comment]
>Now how could I have figured that out myself? How could I have known how many deterministic sequence addresses I had already used?

if you start the gui version addresses beyond the gap limit appear highlighted in red on the addresses tab. you can also change the gap limit for the wallet via the GUI console command wallet.change_gap_limit(n) where n is the new gap limit. default is 20.

for your purposes it might be easier to simply use --force with addrequest everytime.

try `electrum help` and `electrum help addrequest` for the docs.

**Comment by realSConway** [comment]
I actually have one more question if you don't mind.


I'm using PHP to execute `curl_exec($ch);`

How do I add --force parameter to my CURLOPT_POSTFIELDS?
Full line looks like this
```
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"id\":\"curltext\",\"method\":\"addrequest\",\"params\":{\"amount\":\"0.00000001\"}--force}");
```

In case you need my full PHP it is as follows.
```
<?php
if (isset($_POST)) {

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "http://127.0.0.1:7777");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_POST , 1);
        curl_setopt($ch, CURLOPT_USERPWD , 'bitcoin:LQ4LYRsfgAPTz1xqxutBcOzL8CWj_ZRGGMB8b6B9v7A=');
        curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"id\":\"curltext\",\"method\":\"addrequest\",\"params\":{\"amount\":\"0.00000001\"}--force}");

        $result = curl_exec($ch);

        $obj = json_decode($result, true);
//      echo "<div id=\"sub><p>".$obj["result"]["address"]."</p></div>";
        echo $obj["result"]["address"];
//      echo "<div id=\"sub><p>css test</p></div>";

}
?>
```

Thanks in advance
