### ISSUE TITLE
Lightning Enhancement: Coin selection to open channel

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#5698]
Filing this as a request for future release.

Being able to spend entire coins when opening channels would be a killer privacy feature, as it eliminates the change outputs that are used for linking wallets together.
It should be implementable from the current Lightning Electrum with very little new functionality other than some minor UI.

UX:
In Coins menu, when right-clicking a coin. Below the Spend coin option there is an option "Use coin to open channel". This pre-populates the "Open Channel" screen with the maximum amount spendable, deducting the needed fees etc.

Alternative UI: 
This could also be a button on the Send screen which has a "send max" feature.

Alternative 2: 
It could also be a button next to the "Local amount" in the Open channel screen that says
"Use maximum channel size".

**Comment by SomberNight** [comment]
Yes good point, coin selection would be great.

In Qt, I was thinking the "open channel" dialog should reuse the "Send" tab,
- reusing coin-selection
- reusing fee selection
- freezing "Pay to"
- maybe reusing amount and "send max", where amount would be "local amount"; and we should probably remove "remote amount" (`push_msat`), it's probably not that useful and dangerous for newbies anyway

Somewhat related, it would be useful to be able to export an unsigned/partial funding tx, that you can sign offline or give to cosigners(??), and then broadcast to have the channel opened. (related: https://github.com/spesmilo/electrum/issues/5379)

**Comment by ziggamon** [comment]
Sounds good, not sure if this would make this a bigger project than necessary, but seems all bits are in place for that as well, freezing the Pay to AFAIK is done with BIP70.

Trying out the new LN mode now and it seems quite solid already by reckless standards so wouldn't want to hold up a release :)

And agree re removing the remote amount, or at least hiding it under some advanced setting. Local amount could then be renamed into just "channel size" or "channel".

**Comment by ecdsa** [comment]
note: this is fixed in dd6cb2caf7e1eff6a8af07a2e0363da371aa1b13
(not in master yet)

**Comment by ziggamon** [comment]
Awesome news! Please send a ping when merged in master and I'll test right away. Potentially killer feature right here!

**Comment by ecdsa** [comment]
note: only the coin selection is implemented at the moment; not the "send max" feature.
I am still working on that

**Comment by ecdsa** [comment]
done now :)
