### ISSUE TITLE
Electrum websocket can't establish a connection to the server port 9999

### ISSUE THREAD

**Issue by aneesh2usman** [spesmilo/electrum#5701]
Electrum merchant payment show in browser  WebSocket connection to 'wss://ip:9999/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by ecdsa** [comment]
wrong commit comment: it should fix #5707, not #5701

**Comment by ecdsa** [comment]
closing, duplicate of #5423
