### ISSUE TITLE
bug master Send Max -> Send overrides coin selection

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#5702]
In current master of 4.0 branch.

How to reproduce:

Have multiple coins in the wallet. Select a subset of the coins in the Coins menu. Right-click and choose "Spend". Select "Send Max". Everything good so far. The bug happens depending on how you send it from here:

Click "Send" and the sending transaction will actually load all coins in the wallet add them as inputs to the send. 

Click "Preview" and there is no issue, it shows the desired inputs and after Sign and Broadcast the correct transaction goes out. The same flow should happen when Send is clicked, and that was the case on the 3.x branch.

**Comment by SomberNight** [comment]
Thanks for reporting this... It is definitely not intended.

It happens because of the `do_clear` on line 1745:
https://github.com/spesmilo/electrum/blob/d480d0b265068ce0cc7a5a279b98e4af85bbc3ee/electrum/gui/qt/main_window.py#L1739-L1747

@ecdsa
