### ISSUE TITLE
Forced language

### ISSUE THREAD

**Issue by PELock** [spesmilo/electrum#5708]
I hate the forced language feature in Electrum, can't you make a selection in options somewhere, it drives me nuts.

**Comment by SomberNight** [comment]
Do you mean on the first startup?
You can already change the language once you have a wallet open, in the Preferences;
so I am not exactly clear what you mean here.

**Comment by SomberNight** [comment]
Also, I thought the default language in Qt is the language of the OS ?
Is that not working? Or is that what is bothering you that that is the default?
