### ISSUE TITLE
How to convert single public key to address using command line?

### ISSUE THREAD

**Issue by lizz-y** [spesmilo/electrum#5709]
How to convert single public key to address using command line?
For example : 
bc1quhc7qvukzgwtkpt6vw8p389qrzfe9g5ahfcd4v address having 
021674bbae037ddc10b327c6fc0814777fa5f2a2d9fca6f3a9ff46ddf90729a7ec pubkey. 

How to convert pubkey to address?

**Comment by SomberNight** [comment]
Why do you want to do this? What is the usecase?
There is no such method exposed at the moment.

You can do this in the Qt console:
```
bitcoin.pubkey_to_address('p2wpkh', '021674bbae037ddc10b327c6fc0814777fa5f2a2d9fca6f3a9ff46ddf90729a7ec')
```
As the command suggests, this method is in `bitcoin.py` in the source.

**Comment by lizz-y** [comment]
> Why do you want to do this? What is the usecase?

learning bitcoin. 

Thank you.
