### ISSUE TITLE
Receive tab needs to display only the address as well, not just the payment request URI

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#5710]
Currently, the withdraw-to-payment request is not implemented on most of the services, particularly exchange services that allow you to buy BTC and withdraw to your wallet. None of the biggest ones support withdrawing to payment request URI, instead, they only ask for the address. Same as for multiple services that offer bitcoin related services. All ask for a plain and simple 'receiving address' (if it's bech32 or not this is a different subject, but still they require just the address, not the payment request URI).

Users are used to "handing out a bitcoin address" in order to receive bitcoins from a friend or withdraw bitcoin from an exchange service, etc. It's not ideal to have them select just the address from the payment request URI and copy it because it's annoying and opens the door to mistakes.

Another downside is that our redesigned receive tab changed the long time behavior we had in previous versions where we would display the address in its own text field. On latest git master I can see there is a box in the right side of the receive tab where we can toggle from QR to Text, but it also displays the payment request URI instead of the plain and simple sole address.

I propose we should add 2 more tabs before and have a total of 4 possible representations:

1) Variant 1
a) Tab 1: Only Address (text), label = Address
b) Tab 2: Only Address (QR Code), label = Address (QR)
c) Tab 3: Payment request URI (text), label = Payment Request
d) Tab 4: Payment request URI (QR Code), label = Payment Request (QR)
The Tab displayed by default when is Tab 1: Address.

or
2) Variant 2
We add a right - left slider button with two positions: left and right, and describe left as "Address" and right as "Payment request URI". Default position is left (Address). Depending on each position of this slider, the tabs can be:

2.1 Slider set to Address (left) [DEFAULT POSITION]
a) Tab 1: Only Address (text), label = Address
b) Tab 2: Only Address (QR Code), label = Address (QR)

2.2 Slider set to Payment Request URI (right)
a) Tab 1: Payment request URI (text), label = Payment Request
b) Tab 2: Payment request URI (QR Code), label = Payment Request (QR)

Feel free to vote whichever you think will provide the best user experience. I am for Variant 1, so users have at hand the address if they need just the address as well as the URI if they need it. The right click menu from the bottom of the payment request window also includes a copy address link which is great and should stay there, so I think this should be sufficient.

**Comment by SomberNight** [comment]
- This also affects the kivy GUI. It also currently displays bip21 URIs and QR codes. Imagine going to a bitcoin ATM and it rejecting your QR codes...
- Exchanges don't accept bip21 URIs.
- When using a hardware wallet, the UI should encourage users to verify receive addresses before giving them out. The previous design did this with the "eye" icon quite well I think. In the current design, the user is not even shown text by default, and even if they choose to see that, they will be shown a bip21 URI. If they click the eye icon there, the hw device flow will start but the user will not see the actual bitcoin address to compare against on the monitor...

On the other hand, re what @gits7r suggests with having 4 options... well 4 sounds overkill; too many options.

Maybe like we had before on master, we could show a QR code and text at the same; and there could be 2 options (a toggle between): address / bip21 URI. (in case of a lightning payment request, in this case, there would only be one option).

**Comment by SomberNight** [comment]
Current master looks like this:
![electrum_4_0_0_receive_tab_mock](https://user-images.githubusercontent.com/29142493/66969946-1f670680-f07b-11e9-9c0f-a820f62e1879.png)

I propose keeping all this, but adding back the "bitcoin address" line at the top left, in a text field that has "show QR" and "copy" and "eye" action buttons. This text field would be sometimes invisible however.

- If the user has selected an on-chain request it would be **visible**.
- If the user has selected a LN request, the field would be **invisible**, but it would still take up the space (so that the other stuff on the left maintains a constant position).
- If no request is selected it would be **invisible**.

@ecdsa

**Comment by gits7r** [comment]
> I propose keeping all this, but adding back the "bitcoin address" line at the top left, in a text field that has "show QR" and "copy" and "eye" action buttons. This text field would be sometimes invisible, but it would still take up the space (so that the other stuff on the left maintains a constant position).
> 
>     * If the user has selected an on-chain request it would be **visible**.
> 
>     * If the user has selected a LN request, the field would be **invisible**.
> 
>     * If no request is selected it would be **invisible**.

I agree with this design. It sounds very nice and user friendly.
However, if we go with this I suggest we somehow not show the QR code of the payment URI as it would be confusing to have one QR code in the main window and when we click on the QR button at the end of the text field another QR code pops up.

We should add a title to the right part above the two tabs that state "Payment request URI" and default to displaying the text first, and user can click on the second QR tab. How does this sound?
