### ISSUE TITLE
SyntaxError in segwit_addr with Python 3.8

### ISSUE THREAD

**Issue by ysangkok** [spesmilo/electrum#5711]
```
electrum\segwit_addr.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert decode(hrp, ret) is not (None, None)
```

This error seems to be present since [merging into Electrum](https://github.com/spesmilo/electrum/commit/e853dde1113f5d3fb96b864aca283781abbd6f8e) even though it is not present in [sipa's code](https://github.com/sipa/bech32/blame/bdc264f84014c234e908d72026b7b780122be11f/ref/python/segwit_addr.py#L121). Weird.

**Comment by SomberNight** [comment]
changed in https://github.com/sipa/bech32/pull/27 I guess
