### ISSUE TITLE
[master] "Increase fee" crashes

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#5718]
Current master. How to reproduce:

Make RBF tx. Right click, "increase fee". Select a fee and click "send". Crashes. 

Error reporting tool subsequently also crashes.

**Comment by bauerj** [comment]
> Error reporting tool subsequently also crashes.

Hmm, that's interesting. Is there any output when you start it from a terminal?

**Comment by ziggamon** [comment]
Nothing related to these things, no. 

Running on updated master on Mac.

**Comment by SomberNight** [comment]
> Make RBF tx. Right click, "increase fee". Select a fee and click "send". Crashes.

Does it crash when you click "OK" in the "Bump fee" dialog (where you select the fee) before the "Transaction" dialog is shown ("preview");
or does it crash when you click something in the Transaction dialog?

Also, does this happen seemingly regardless of what the selected fee is?

Also, re bauerj's question about terminal output; to be clear, is there anything interesting in the logs of electrum? You probably already know this but [see this re debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging).

Also, if your tx got mined in the meantime, you can test with a "local" transaction. Create a new tx in the Send tab, click preview, sign and then "save". And then you will have a local tx in your history. You can try RBF-ing that.

**Comment by ziggamon** [comment]
Thanks for the tip re -v. Got some logs:

```
I | lnpeer.Peer.[94.52.112.227:9735] | Disconnecting: GracefulDisconnect('initialize failed: TimeoutError()')
I | lnworker.LNWallet | adding peer 036533303d73c34c58c35017cc286da18b5958a14ceed21f1d419eb818942e3698@84.157.209.189:9735
I | lnpeer.Peer.[31.176.214.152:9735] | Disconnecting: GracefulDisconnect('initialize failed: TimeoutError()')
E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/Users/kotliar/Code/electrum-lightning/electrum/electrum/gui/qt/history_list.py", line 636, in <lambda>
    menu.addAction(_("Increase fee"), lambda: self.parent.bump_fee_dialog(tx))
  File "/Users/kotliar/Code/electrum-lightning/electrum/electrum/gui/qt/main_window.py", line 3253, in bump_fee_dialog
    new_tx = self.wallet.bump_fee(tx=tx, new_fee_rate=new_fee_rate)
  File "/Users/kotliar/Code/electrum-lightning/electrum/electrum/wallet.py", line 1075, in bump_fee
    tx=tx, new_fee_rate=new_fee_rate)
  File "/Users/kotliar/Code/electrum-lightning/electrum/electrum/wallet.py", line 1129, in _bump_fee_through_coinchooser
    fee_estimator, self.dust_threshold())
  File "/Users/kotliar/Code/electrum-lightning/electrum/electrum/coinchooser.py", line 325, in make_tx
    self.penalty_func(base_tx, tx_from_buckets=tx_from_buckets))
  File "/Users/kotliar/Code/electrum-lightning/electrum/electrum/coinchooser.py", line 438, in penalty_func
    min_change = min(o.value for o in base_tx.outputs()) * 0.75
ValueError: min() arg is an empty sequence
```

**Comment by ziggamon** [comment]
>Does it crash when you click "OK" in the "Bump fee" dialog (where you select the fee) before the "Transaction" dialog is shown ("preview");

Yes

**Comment by SomberNight** [comment]
Great so we have a trace :)
It's interesting actually...

Regarding the tx you are trying to RBF, could you say how many outputs there are, and even more specifically, how many are "green"/"yellow"/uncoloured in the GUI (so how many ismine-non-change/ ismine-change/external outputs there are)? Actually a boolean for each might be enough information; whether there are any green, any yellow, any uncoloured.

**Comment by ziggamon** [comment]
There is one output, yellow (internal).

Actually I tried increase fee on another tx, also one output but that goes to an external address) and didn't get any crash. 
However those RBFs pull in extra inputs and create change, but that's a different issue :)

**Comment by SomberNight** [comment]
Oh there is only a single output and that is yellow? How did that tx come to be? :P

Ok I can reproduce.

**Comment by ziggamon** [comment]
Manual consolidation tx for privacy and cost reduction.

**Comment by SomberNight** [comment]
Thanks for reporting this and for helping figuring out the issue.

> Manual consolidation tx for privacy and cost reduction.

I would have expected the user would use a "receive" address in that case, which would have worked; although this expectation of mine also explains why what you did was not tested :P

**Comment by ziggamon** [comment]
>  would have expected the user would use a "receive" address in that case

IIRC those are still being reused by the GUI as receive addresses, have previously filed a ticket about that which IMO is incorrect behavior. 

Thanks for speedy fix and for your good work!
