### ISSUE TITLE
Electrum installed in ubuntu software center, the option restore wallet does not work

### ISSUE THREAD

**Issue by miquelcvcv** [spesmilo/electrum#5722]
Electrum installed in ubuntu software center, the option restore wallet does not work

File->Create/restore wallet-> I have a seed.->Write your seed->Next(does not work)

When you write the seed it does not enable next button correctly. Next button remains disable when it should not. So you can not restore your wallet

**Comment by SomberNight** [comment]
What is the version of Electrum in the "ubuntu software center"?
We don't officially distribute there. If it's too old, and you have e.g. a segwit seed, that would explain it.
You should always try to use the latest version.

**Comment by SomberNight** [comment]
closing, no answer
