### ISSUE TITLE
Add tag "latest" to release process

### ISSUE THREAD

**Issue by patrickstump** [spesmilo/electrum#5725]
Please start tagging your releases so that 
when the command 
```
curl -s https://api.github.com/repos/spesmilo/electrum/releases/latest | grep tag_name 
```
 is run we can the latest version.  This will help everyone's build process so we can auto grab your latest version.  Right now we have to continuously check back.

Thank you

**Comment by SomberNight** [comment]
What needs to be done specifically by us?

**Comment by SomberNight** [comment]
Looks like we need "full" releases for this.
Currently we just create git tags and push them, which do not support this functionality.

see
https://github.community/t5/How-to-use-Git-and-GitHub/Why-last-release-is-not-marked-as-quot-latest-release-quot/td-p/1762
https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by patrickstump** [comment]
Sorry for the drop.  Was pulled onto another project for a bit and didn't get notified.  I'll check the link out. Thanks!
