### ISSUE TITLE
TrustedCoin server signing timeout reached for tx with 220+ inputs

### ISSUE THREAD

**Issue by shakfaka** [spesmilo/electrum#5727]
Hello guys ,
unable to send any amount of BTC from my wallet. Always stuck at the point after entering 2FA code. After more then 20-30 sec Error pops in saying: Error connecting to TrustedCoin server:
TimeoutError() .

1)Tried checking Time settings on Phone and PC
2)Tried Tor way

Did not help.
Log attached.
Please help !

[electrum_log_20191025T230627Z_2604.log](https://github.com/spesmilo/electrum/files/3774120/electrum_log_20191025T230627Z_2604.log)

**Comment by SomberNight** [comment]
Hi. It looks like you have ~220 inputs in this transaction. The network timeout is 60 seconds client-side, and it seems that is reached.

You could try using the "Coins" tab in Electrum, manually selecting fewer coins, and creating a tx that way.

@badmofo just curious, is signing server-side using libsecp256k1? The client seems to sign in ~6.5 seconds in this case (using libsecp).

**Comment by badmofo** [comment]
@SomberNight the server does use libsecp256k1  The logs on my side don't show any large requests arriving during that time period and from the look of the client log I'd guess the problem has something to do with the proxying setup the user had configured (i.e. likely a bum Tor exit node).
