### ISSUE TITLE
"use change addresses" option resets to "yes" for new wallet

### ISSUE THREAD

**Issue by lizz-y** [spesmilo/electrum#5730]
"use change addresses" option resets to "yes" for new wallet. All other options remain except "use change addresses".

**Comment by AbdussamadA** [comment]
This option is stored in the wallet file so it can vary from wallet to wallet. I guess the default is yes for new wallets.

**Comment by lizz-y** [comment]
ok but why this option is not propagated like all other options?

**Comment by ecdsa** [comment]
the issue is that wallet settings are not indicated as such.
not sure how to fix that..
