### ISSUE TITLE
Stuck in Kivy build image stage

### ISSUE THREAD

**Issue by wartjugger** [spesmilo/electrum#5734]
at:

> Step 21/44 : RUN "${ANDROID_SDK_HOME}/tools/bin/sdkmanager" "platforms;android-24" > /dev/null &&     "${ANDROID_SDK_HOME}/tools/bin/sdkmanager" "platforms;android-28" > /dev/null &&     "${ANDROID_SDK_HOME}/tools/bin/sdkmanager" "build-tools;${ANDROID_SDK_BUILD_TOOLS_VERSION}" > /dev/null &&     "${ANDROID_SDK_HOME}/tools/bin/sdkmanager" "extras;android;m2repository" > /dev/null &&     chmod +x "${ANDROID_SDK_HOME}/tools/bin/avdmanager"
 ---> Running in ee7124351483

No progress at all for more than an hour. Breaking, running the following again:
>sudo docker build -t electrum-android-builder-img electrum/gui/kivy/tools

gets it stuck at the same place.

**Comment by ecdsa** [comment]
enable logs, setting log_level to 2 in buildozer.spec

**Comment by wartjugger** [comment]
Ok, I don't know why it took so long but in a repeated run eventually it does continue. 

Another remark for those trying the instructions on Debian: sudo apt-get install gettext is required before running ./contrib/pull_locale
