### ISSUE TITLE
Paste option disappears on server selection screen. 

### ISSUE THREAD

**Issue by ascisco** [spesmilo/electrum#5743]
Under the 'Network -> Server' option when long pressing the host or port field the paste option will popup momentarily but then disappears. If you are fast enough to click the paste it does work but ultimately disappears. 

Running a Google Pixel 1 using Android 10. Also reproduced this problem on various other Android phones.

**Comment by SomberNight** [comment]
ACK, can reproduce.

**Comment by accumulator** [comment]
kivy, outdated
