### ISSUE TITLE
4.0.0a0 generating plain unused addresses (UX complaint(s))

### ISSUE THREAD

**Issue by Chrozayis** [spesmilo/electrum#5744]
I accidentally upgraded to 4.0.0a0 through the Electrum-git AUR package. 
I tried to downgrade but encountered an error with my wallets being v19 and the AUR Electrum binary being v18.
It used to be that in the receive tab there was a fresh address I could copy and paste. But now the receive tab has only a payment request generator which is inconvenient for receiving from an exchange (and not quite as intuitive as I'd like).
For now, I've just copied an address out of the addresses tab. This led to another pain point, I apparently had to "copy column" => Address, which sounded like it would copy all my addresses. Instead, it just copied one, which is what I wanted, but not what I expected.

**Comment by Chrozayis** [comment]
Whoops. Duplicates https://github.com/spesmilo/electrum/issues/5710
Sorry for not checking thoroughly before posting.

**Comment by SomberNight** [comment]
>  For now, I've just copied an address out of the addresses tab. This led to another pain point, I apparently had to "copy column" => Address, which sounded like it would copy all my addresses. Instead, it just copied one, which is what I wanted, but not what I expected.

This is part is not a duplicate.
Would it be more intuitive if if was `Copy`>`Address`?
The old code, instead of a submenu for "Copy", offered only to copy the column where the right click itself happened. Did you find that more intuitive?

**Comment by Chrozayis** [comment]
My confusion is the use of "column". I think of a column as having multiple values, so "copy column > address" makes me think it will copy the entire address column, all my addresses.
Either of those options for the menu would work for me, although I expect most people are copying addresses so having a "copy address" in the top-level menu might be handy.

**Comment by ecdsa** [comment]
fixed in 5773097b085e5fa1993505aec63318138dc409bd
