### ISSUE TITLE
How I got my stolen Bitcoins recovered

### ISSUE THREAD

**Issue by Safarojas** [spesmilo/electrum#5745]
Have you ever gotten your coins stolen from your wallet or invested in an ICO that turned out to be a scam, you are not alone because this happened to me too. I initially lost $90,000 in just 3 months from Cryptoallday, I contacted the authorities and they refereed me to a bitcoin recovery company who helped me recover all my funds within less than 2 days... I'm speaking out to improve our awareness of these cryptocurrency thieves and help you if you have been a victim yourself. Simply visit their website at www.bitcoinbinaryretrieval.com

**Comment by SomberNight** [comment]
^ This is a scam. Prepare to lose your coins if you contact this guy.

**Comment by Safarojas** [comment]
> ^ This is a scam. Prepare to lose your coins if you contact this guy.

Who are you please?
