### ISSUE TITLE
Transaction QR codes are encoded using base43 (per Schildbach)

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5746]
Electrum since version 2.0 has been encoding transactions in QR codes as base43, following Andreas Schildbach's idea, as this results in a more efficient encoding. Same amount of data results in smaller (easier to scan) QR codes, and also the maximum tx size that can be displayed is larger.

It came up recently that, especially as we are now implementing PSBT support and PSBTs are "supposed to be" encoded as base64, we might want to drop base43, and just use base64 in QR codes as well. (Although note that we also encode fully signed txns as base43 right now... would we want them instead as hex??)

Further note that occasionally over the years, it's been a recurring issue that some user tries to decode the QR code with 3rd party software, and does not know what to do with the data they find.

To evaluate, it would be nice to get concrete numbers on the efficiency gains.

According to [wikipedia](https://en.wikipedia.org/wiki/QR_code#Storage), there are 4 data modes for a QR code: numeric (0-9), alphanumeric (45 chars, A-Z, 0-9, and a few special chars), binary, and kanji.
For the largest possible QR with the lowest possible error correction (`40-L`),
- alphanumeric mode can store 4,296 characters
- binary mode can store 2,953 characters

The base43 alphabet we use is intentionally a subset of the 45 chars allowed in alphanumeric mode ("space" and "%" are excluded).

Napkin maths suggests that:
- using base43 in alphanumeric mode, the max data we can encode is `ln(43)/ln(256)*4296 = 2913.9 bytes`. In practice this was 2913 bytes in my tests.
- using uppercase hex in alphanumeric mode, the max data we can encode is `ln(16)/ln(256)*4296 = 2148 bytes`. In practice this was 2148 bytes in my tests.
- using base64 in binary mode, the max data we can encode is `ln(64)/ln(256)*2953 = 2214.75 bytes`. In practice this was 2214 bytes in my tests.

If we put binary data directly into the QR code, using binary mode, then the max would be 2953 bytes; however this would make decoding via a 3rd party QR code decoder and then copy-pasting the contents (and decoding them yourself somehow) impossible in practice.
Note that recent Electrum versions accept the base43 text directly (e.g. from clipboard), specifically to accommodate at least some 3rd party decoder use cases.

I have verified these numbers using the following patch.

```patch
diff --git a/electrum/gui/qt/main_window.py b/electrum/gui/qt/main_window.py
index 34aeda932..d4225d2d8 100644
--- a/electrum/gui/qt/main_window.py
+++ b/electrum/gui/qt/main_window.py
@@ -2527,6 +2527,21 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, Logger):
         d = QRDialog(data, parent or self, title)
         d.exec_()
 
+    def qr_b64(self, num_bytes):
+        data = os.urandom(num_bytes)
+        data = base64.b64encode(data).decode('ascii')
+        QRDialog(data, self, _("QR code")).exec_()
+
+    def qr_hex(self, num_bytes):
+        data = os.urandom(num_bytes)
+        data = data.hex().upper()
+        QRDialog(data, self, _("QR code")).exec_()
+
+    def qr_b43(self, num_bytes):
+        data = os.urandom(num_bytes)
+        data = bitcoin.base_encode(data, base=43)
+        QRDialog(data, self, _("QR code")).exec_()
+
     @protected
     def show_private_key(self, address, password):
         if not address:

```

These commands successfully displayed a QR code; and these arguments were the largest that did not raise `qrcode.exceptions.DataOverflowError`.
```python
window.qr_hex(2148)
window.qr_b64(2214)
window.qr_b43(2913)
```

Note that the base43 max size over the base64 max size represents a 31% increase.

**Comment by SomberNight** [comment]
> the base43 max size over the base64 max size represents a 31% increase [in max tx size that can be represented]

Mainly because of this, I propose we keep using base43 for transactions in QR codes.

**Comment by ecdsa** [comment]
ACK

**Comment by SomberNight** [comment]
Ok, we can close this I think.
It's good for future reference though.
