### ISSUE TITLE
Electrum processes in MAC OS. Two processes instead of one (one is pyinstaller bootloader).

### ISSUE THREAD

**Issue by melaxon** [spesmilo/electrum#5747]
MAC OS El Capitan
Electrum 3.3.8

For some mysterious reason there are two processes of Electrum as shown below.

Is that normal?

```
$ ps aux | grep -i electrum
username   6953   0.9  1.0  2792496  43352   ??  S     1:28PM   0:15.79 /Applications/Electrum.app/Contents/MacOS/Electrum
username   6951   0.0  0.2  2531360   6876   ??  S     1:28PM   0:00.90 /Applications/Electrum.app/Contents/MacOS/Electrum
```
One of the processes is always "Not responding" and it is the parent of another one. If I kill either of them, then both processes will be terminated.

IMHO it was only one process in the past. Being little bit paranoid I installed Eset antivirus but it found no suspicious process (I did not scan the full disk as it takes ages and it heats the laptop like a pan)

Has anybody notices that as well?

**Comment by SomberNight** [comment]
I think this is due to PyInstaller, and so it also applies to Windows; as we use PyInstaller to build both the Mac and the Win binaries.
See https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#the-bootstrap-process-in-detail

IIRC we have been using PyInstaller for the Mac binaries since around 3.0

**Comment by judey040** [comment]
Stolen BTC (Bitcoin) is hard to recover i have to be sincere but then, I have been in your shoes before and thanks to joegrimes1010@gmail.com for helping me out when i had the same issues, I hope he sees this.
It started when i was in Italy for my Vacation, I was on the internet and came by this con site Swift Options. the deals were too good to be true. I invested 18 Thousand usd with the hope or let me say i would make 54Thousand if i invest 18k usd, that was the actual amount i made later lol (I was stupid).
i read their terms and i invested 18k. Days later, I logged into my dashboard and i saw i made 54k usd, I was so happy for investing called the number on the site and a guy spoke to me and we chatted later. I was gald and tried to withdraw my funds and i couldnt got to know later i had to deposit 20 percent of my investment and the profit. I made the 20% deposit without thinking and that how kept on doing that for a while till i realized it was a scam.
i stopped and was determined i would find a way to get my money back and paid some, Many recovery organisation and individuals, It was also scam! See its not easy?. I have sent a total of 150k usd to Swift Options and it was so annoying me being stupid. I met joegrimes1010@gmail.com  and i made up my mind he would be the last i will ask for help recovering my money. He tracked the site and where i spoke with the guy managing my account on the site and found out the wallet was attached to an exchange called Reminato. he logged some report and then we went through some time together and legally and which brought the guys involved down and i got my money in full you can also reach them through WhatsApp +19412410496
