### ISSUE TITLE
Color coding addresses in electrum android 

### ISSUE THREAD

**Issue by roth-a** [spesmilo/electrum#5750]
The color coding of addresses belonging to the wallet (when viewing/signing a transaction) is a very useful feature and I would like to see it on Electrum android too. 

Electrum-android version 3.3.7

**Comment by roth-a** [comment]
@SomberNight can you give me an idea where I would need to change the code?  Then I could start experimenting with electrum myself (for the first time).  Does the component listing the output transactions:  https://github.com/spesmilo/electrum/blob/master/electrum/gui/kivy/main.kv#L110  even support colored entries? Or would the component need to be changed?

**Comment by SomberNight** [comment]
The `OutputList` you link to, contains `OutputItem`s, which contains `TopLabel`s.
I expect you should be able to set `color` and/or `background_color` for these, such as at e.g.
https://github.com/spesmilo/electrum/blob/6e3875ceabf75ee96e722358bcff33f883dddbf5/electrum/gui/kivy/main.kv#L365
See https://kivy.org/doc/stable/api-kivy.uix.label.html

**Comment by SomberNight** [comment]
Note that you will probably want to set the colour dynamically from python code.
An example of modifying a property of a widget from python code is here:
https://github.com/spesmilo/electrum/blob/6e3875ceabf75ee96e722358bcff33f883dddbf5/electrum/gui/kivy/uix/dialogs/label_dialog.py#L53

**Comment by roth-a** [comment]
@SomberNight Thanks! That was very clear and helped a lot.

**Comment by roth-a** [comment]
Have a working implementation: https://github.com/roth-a/electrum/commit/aeb4afed4be3cd8a0a365083feeb3796c4ae832c   (still need to clean up code)

**Comment by roth-a** [comment]
@SomberNight : Is there a central file for kivy color schemes? Or is it all hard-coded?

**Comment by roth-a** [comment]
Added pull request: https://github.com/spesmilo/electrum/pull/5774

**Comment by roth-a** [comment]
Any chance of merging this in soon?
