### ISSUE TITLE
Error trying to withdraw from Electrum wallet?

### ISSUE THREAD

**Issue by Undefined-Variables** [spesmilo/electrum#5751]
I am trying to withdraw from my elecrum wallet but I am getting the following error...

The server returned an error when broadcasting the transaction. Consider tying to connect to a different server or updating Electrum

Unknown error

I have updated and connected to many different servers and I get the same error?

**Comment by ecdsa** [comment]
upgrade Electrum

**Comment by Undefined-Variables** [comment]
I have its running Electrum-3.3.8

**Comment by Undefined-Variables** [comment]
I managed to recover funds by installing electrum on a Linux VM and recovering wallet with the seed and this let me send it. I’m not sure what’s happened on windows 10 install but I will uninstall it and start again.
