### ISSUE TITLE
aiohttp 4's ClientSession does not support explicit loop

### ISSUE THREAD

**Issue by ysangkok** [spesmilo/electrum#5753]
See aio-libs/aiohttp@ddba4657162b23de7bca916460486e79c2dfdcfa . I suggest putting an upper version bound on the aiohttp dependency. Didn't figure out what they want users to do instead, but maybe more documentation will become available later (they havn't released 4.0.0 yet).

**Comment by SomberNight** [comment]
Not fully clear to me where we are using what is being removed in that commit.
One thing that I see is that the `loop` arg in `ClientSession.__init__` is being removed; which we use at e.g. https://github.com/spesmilo/electrum/blob/5773097b085e5fa1993505aec63318138dc409bd/electrum/daemon.py#L103

**Comment by AmazingDreams** [comment]
This error just popped up for me:

```
  File "REDACTED/electrum/electrum/daemon.py", line 103, in request_coroutine
    async with aiohttp.ClientSession(auth=auth, loop=loop) as session:
TypeError: __init__() got an unexpected keyword argument 'loop'
```

**Comment by SomberNight** [comment]
Ideally we would fix version incompatibilities instead of putting an upper version bound...
unless there are large breaking changes

In any case, please feel free to report aiohttp 4.0-related incompatibilities we have here.

**Comment by ysangkok** [comment]
There is an upper version bound now so I'll close this.
