### ISSUE TITLE
Electrum unsigned raw transaction format

### ISSUE THREAD

**Issue by vipsaini** [spesmilo/electrum#5754]
I am trying to decode the unsigned transaction hex generated inside unsigned.txn file.

"hex": "45505446ff00020000000120aeae03e30095ba23102c284f7154ffb395ef0e443b5852383eac24b38c4fe8010000005701ff4c53ff043587cf036b7cc9d480000000af56f53e4c58055a783b9f28401166d06bf8e3212b30d840f1bd0c98c09a9f0202d7360de672726d4049b4e6b816daa9575b1c78f5534970068a81c2f2cbb2f03401000000fdffffff02a0860100000000001976a9145599f7915a9e9b03b80c1b3ac2774e47205ad30d88acef674900000000001976a91487ffb918e8f5e15f0de9a1d51c00d5a2213b671d88acec3f1800"

Decoded Output:

Electrum Partial Tx Format : 45505446
Separator : ff
Electrum Partial Tx Version : 00
Network Version :  02000000
Number of Inputs : 01
Previous Tx Hash : 20aeae03e30095ba23102c284f7154ffb395ef0e443b5852383eac24b38c4fe8
Previous Output Index : 01000000
Script length : 57
**Unknown** : 01ff4c53
Extended Public Key Type : ff
Account Extended Public key: 043587cf036b7cc9d480000000af56f53e4c58055a783b9f28401166d06bf8e3212b30d840f1bd0c98c09a9f0202d7360de672726d4049b4e6b816daa9575b1c78f5534970068a81c2f2cbb2f034
**Bip32 Derivation** : 01000000
Sequence : fdffffff
Number of Output : 02
Amount : a086010000000000
Script Length : 19
Script Public Key : 76a9145599f7915a9e9b03b80c1b3ac2774e47205ad30d88ac
Amount : ef67490000000000
Script Length : 19
Script Public Key : 76a91487ffb918e8f5e15f0de9a1d51c00d5a2213b671d88ac
Locktime : ec3f1800

In the above decoded output I am no able to find out the significance of the 4-byte parameter(**Unknown**) after the Script length in transaction input.

Also in the **Bip32 Derivation** parameter, what exactly does 01000000 signifies here? Does it encode bip32 derivation path i.e m/44'/1'/0'/0/i if yes, then can anyone please help me to decode it correctly?

Note: I used the account extended public key(and purpose 44') to create a watch-only wallet.

Thanks

**Comment by SomberNight** [comment]
I guess the UTXO being spent is p2pkh; so the scriptSig in the input will in the end be <signature> <pubkey>

We put a single 0xff byte as a signature to signify NO_SIGNATURE.
So unknown is:
- push 1 byte
- 0xff
- OP_PUSHDATA1
- push 53 bytes
(- and then the extended pubkey is pushed)

The BIP32 derivation is 2 bytes per level, if it fits into 2 bytes, so 0100/0000 is I guess m/1/0. This is only the derivation "suffix" (starts from the xpub encoded before).
-------- Original Message --------

**Comment by vipsaini** [comment]
Thanks for the answer. 

I had another query: While signing the transaction offline using "Load transaction" option on electrum(loaded with bip39 seed) how does the electrum comes to know which output in the unsigned transaction is the recipient output and which one is the change output?

![tx_summary](https://user-images.githubusercontent.com/17548059/69802766-4b3fe500-1200-11ea-8e05-3d756fa5d3c2.jpg)
 
For example in the above image, addresses highlighted in green are recipients addresses and the one in yellow is a change address. But in the unsigned transaction file, I believe there is no special parameter that tell electrum about the position of the change output. 
So does electrum software assume the last output as change output or does it matches the hash160 of each output to every possible hash160 in the change branch?

**Comment by SomberNight** [comment]
Until the gap limit is hit, all receiving and change addresses are generated and stored in the wallet file. When you open a wallet, these are then loaded into memory. When you load a tx, addresses touched by the tx are tested against the addresses owned by the wallet; that's how the colouring happens.
