### ISSUE TITLE
Electrum cannot pair when more Trezors have same labels

### ISSUE THREAD

**Issue by matejcik** [spesmilo/electrum#5759]
to reproduce:

1. connect three Trezor devices to your PC*
2. create a new 2-of-2 multisig wallet
3. use 2 of the 3 Trezors as the cosigners
4. close Electrum
5. open Electrum again

a notice will be displayed: "Electrum cannot pair with your Trezor"

on master, there is no traceback. On 3.8.8, it's the following:

```
Traceback (most recent call last):
  File "/home/matejcik/projekty/prace/electrum/electrum/gui/qt/util.py", line 718, in run
    result = task.task()
  File "/home/matejcik/projekty/prace/electrum/electrum/plugins/trezor/trezor.py", line 179, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/home/matejcik/projekty/prace/electrum/electrum/plugin.py", line 457, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/home/matejcik/projekty/prace/electrum/electrum/plugin.py", line 505, in force_pair_xpub
    'receive will be unspendable.').format(plugin.device))
electrum.plugin.DeviceUnpairableError: Electrum cannot pair with your Trezor.
```

What *seems* to happen based on my understanding:

* electrum does not (properly) save paths for multisig cosigners
* therefore [this call](https://github.com/spesmilo/electrum/blob/master/electrum/plugin.py#L457) will return `None`
* the following lines will pick a Trezor at random and try to force-match it to one of the xpubs, which will fail in most cases.

if it is indeed the case, the problem should be reproducible with less than 3 Trezors :) using one emulator (not a cosigner), one physical device (cosigner) and an internal cosigner.

Reproducer instructions will probably depend on registration order, or on xpub order. For me the issue happens on every try, but I can imagine that in some cases this does not happen.

(you can also run at least two emulators at the same time: leave one on port 21325, run the other with `TREZOR_UDP_PORT=21425 TREZOR_PROFILE_DIR=something`, and run `trezord -e 21425` to force connect to the other emulator. The enumeration should then pick both the emulator on the standard port, and the bridge device on the nonstandard port, as well as the physical device.)

**Comment by SomberNight** [comment]
I have 2 T1s and 1 TT. Could not reproduce so far.
Do the devices have distinct labels btw? I think there is logic to distinguish them based on labels.
You might want to inspect the wallet file to see what was saved about the devices.

**Comment by SomberNight** [comment]
As I expected, I can reproduce if the labels collide. Please confirm if your report assumes a collision.

Made some changes so that we fall back to ask the user to select the device in case of a collision:
https://github.com/spesmilo/electrum/commit/56c3de0e1eb28f6017286f51c37c5c45b86690bd

**Comment by matejcik** [comment]
confirming; in particular, the devices I was testing with didn't have labels, so the reported label was `None`.

**Comment by matejcik** [comment]
a better strategy would be to select based on `device_id`, which is randomly generated each time the user wipes a device.

**Comment by SomberNight** [comment]
Do you mean `client.features.device_id`?

> which is randomly generated each time the user wipes a device

Ahh, that sounds nice. An ID with this kind of life-cycle seems ideal. I think the reason we did not persist usb serial numbers etc is due to privacy concerns (although for quite some time now, the user can encrypt the whole wallet file).

-----

TBH I imagine this present issue affects all hardware devices we support... and this has to be solved in the common code (e.g. `plugin.py`). So I am trying to come up with a generic solution.

We could save `device_id` for the devices that provide it (Trezor and clones), and use it as a tie-breaker (maybe in addition to labels).

Re the other devices, there's ledger, coldcard, digital bitbox.
Ledger and ColdCard are unlocked "on-device", so I guess they allow querying the xpub right away.
Trezor One (and clones), Trezor T, and dbb need help from host to get unlocked (enter PIN/passphrase/password).

Since merging [PSBT support](https://github.com/spesmilo/electrum/pull/5721), we store the bip32 root fingerprint in the keystore, so for devices that expose this during enumeration time, we could use this as an additional tiebreaker. (Or just compare the intermediate/account xpub that is also already stored)

This just leaves the digital bitbox, which does not have a label, or `device_id` (AFAIK), and does not expose xpubs either before password-entry.

**Comment by matejcik** [comment]
JFYI the `device_id` is used as a USB serial, and it's in the roadmap of trezorlib to provide something like `get_device_by_id()` without necessarily opening each USB device. Given the lifecycle, privacy implications should be lessened (or at least similar to saving the label).

Re the general solution, I don't think querying the xpub is viable for this purpose, regardless of whether you need host support or not. If the device is passphrase protected, you would be asking passphrase for all devices until you find the one you want -- presumably Ledger won't let you see the xpub without entering passphrase either?

**Comment by craigraw** [comment]
There exists a use case where multiple hardware devices from the same vendor could be configured with the same seed for redundancy or access reasons (e.g. not wanting to travel with a hardware wallet). In this case, the labels and ```device_id``` may differ but the xpubs/fingerprints would not. 

> If the device is passphrase protected, you would be asking passphrase for all devices until you find the one you want

I'm not sure why this unacceptable - it seems reasonable that if the device has been plugged in and Electrum is running there is an intent to attempt to pair with it, in which case full initialisation is normal at the start.

**Comment by matejcik** [comment]
> There exists a use case where multiple hardware devices from the same vendor could be configured with the same seed for redundancy or access reasons (e.g. not wanting to travel with a hardware wallet). In this case, the labels and `device_id` may differ but the xpubs/fingerprints would not.

That is true. Do you want to auto-detect such devices too? A question worth considering - maybe a different device should be set up explicitly?

> 
> I'm not sure why this unacceptable - it seems reasonable that if the device has been plugged in and Electrum is running there is an intent to attempt to pair with it, in which case full initialisation is normal at the start.

What if the user has separate wallets for some of the Trezors? I would expect Electrum to only unlock the Trezor for the wallet which is currently opening.

I mean, i have three Trezors plugged in most of the time for development purposes, plus perhaps an emulator. If I fire up Electrum to check a feature, I don't want to have to enter passphrase four times just to get through, most likely there's exactly one device I'm interested in.
Admittedly this is not a typical usecase :)

**Comment by JaredDahlke** [comment]
hello, I just created a 4/7 multisig with electrum 4.1.5 with ONE trezor1 device. They all have the same label. I am getting this error when i try to sign: "Electrum cannot pair with your Trezor."

I see some commits in this thread that claim to fix this. But 4.1.5 it is still problem . Is there anything I can do to fix this? Thank you

**Comment by SomberNight** [comment]
> I just created a 4/7 multisig with electrum 4.1.5 with ONE trezor1 device. They all have the same label.

if there is only a single trezor, what do you mean by "they all have the same label"?
please elaborate on your setup

**Comment by JaredDahlke** [comment]
@SomberNight sorry about that. What I mean is they all say "My Trezor" here:
![image](https://user-images.githubusercontent.com/32936978/157043652-9bf1fee3-c3d8-41f2-8fc0-5acbadc7c1fd.png)

When I try to send a transaction, I get this error:
![image](https://user-images.githubusercontent.com/32936978/157043922-ce4bb17e-71f2-4990-a172-e03103f61d3d.png)

Also maybe it will help to elaborate on how I created the electrum wallet:

I only have 1 trezor device so I created a wallet on trezor-suite, closed trezor-suite, then added it as a cosigner on my electrum 4/7. Open trezor-suite, wipe the trezor, create another on trezor-suite, repeat 7 times...

This all seemed to work fine , I was able to send TO the wallet, but i get that error when i try to spend FROM the wallet.

**Comment by JaredDahlke** [comment]
I just created another 4/7 being careful to name each trezor differently. same problem.

**Comment by matejcik** [comment]
fwiw you're doing exactly the thing that has been called out [here](https://github.com/spesmilo/electrum/issues/5759#issuecomment-558041182)

**Comment by JaredDahlke** [comment]
Well. It exactly . I’m only using one trezor . I wonder if this is error is
due to they all have the same device_id since it’s one trezor? The
resolution of this bug is not clear, not sure why the ticket is closed .
Should I start a new one ? I’m not even sure if buying 7 trezor would work

**Comment by JaredDahlke** [comment]
> What happens if you click the Trezor icon in the bottom right? Does it show a list of connected trezors and let you select one to force-pair with?

if i click the trezor icon in bottom right first you see this:
![image](https://user-images.githubusercontent.com/32936978/157740261-ddbecf2d-6898-4290-aa3b-2bf1e4cecdf4.png)


then when you click on ok you see this:
![image](https://user-images.githubusercontent.com/32936978/157740327-70d94612-6d94-467b-90d3-970327940fc6.png)

**Comment by SomberNight** [comment]
>> What happens if you click the Trezor icon in the bottom right? Does it show a list of connected trezors and let you select one to force-pair with?
>
> if i click the trezor icon in bottom right first you see this: [...]

Yes, that is as expected then -- it is the same screen you should see when you open the wallet or try to sign a tx; at least the first time after you re-initialise the hwd (assuming the auto-selection fails as the soft device id and the label both differ).

In the `Addresses` tab (menubar>`View`>`Show Addresses`), right-click an address, and select `Show on Trezor (...)`. There might be many such options in the context menu - one for each hardware device added to the wallet. The one that corresponds to the currently connected device should work. Please test that.

> I only have 1 trezor device so I created a wallet on trezor-suite, closed trezor-suite, then added it as a cosigner on my electrum 4/7. Open trezor-suite, wipe the trezor, create another on trezor-suite, repeat 7 times...

I've tested your method to create a 2of2 multisig with only one physical trezor one (re-initialised with new seed in-between). I could not reproduce your issue - I successfully created a signed tx (had to reset and restore seeds on device between signing steps ofc).

**Comment by JaredDahlke** [comment]
> I've tested your method to create a 2of2 multisig with only one physical trezor one (re-initialised with new seed in-between). I could not reproduce your issue - I successfully created a signed tx (had to reset and restore seeds on device between signing steps ofc).

OK this was my bad. I was missing 2 things.
1.  if you have k / n multisig, you actually have to create n multisig electrum wallets, each with 1 seed, and n - 1 MPKs ( i didnt actually finish creating the other 6 multisig electrum wallets)
2. once you have all n electrum multisig wallets, you have to transfer the signed transaction to the other electrum wallets.  I totally missed the 2nd part of the instructions which is 'Spending from a multisig' https://electrum.readthedocs.io/en/latest/multisig.html#spending. I'm very sorry for the confusion, hopefully someone down the road can read this and avoid my mistake!
