### ISSUE TITLE
[Lightning] Outgoing LN payments don't appear as red.

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#5762]
Outgoing on-chain payments appear as red, outgoing LN payments don't. It would be great if this was consistent.

<img width="1134" alt="Screenshot 2019-11-17 at 01 44 00" src="https://user-images.githubusercontent.com/2123375/68997849-92170c00-08dd-11ea-9a1c-cb34f20f8df2.png">

**Comment by lukechilds** [comment]
Tested on current tip of master: cbd146a

**Comment by lukechilds** [comment]
Submitted a PR to resolve this:

<img width="1226" alt="Screenshot 2019-11-17 at 15 31 39" src="https://user-images.githubusercontent.com/2123375/69005093-74828a80-094f-11ea-990d-a0332bc670b7.png">

However looking at the code it looks like this was intentionally disabled. What's the reasoning behind this? You only want to show red descriptions for reducing on-chain balance?

**Comment by ecdsa** [comment]
I think the reason is that earlier version of the code did not have the 'value' field.
we can make it consistent now, thanks for the PR

**Comment by lukechilds** [comment]
Awesome!
