### ISSUE TITLE
[Coin control] Coin control notification bar isn't readable.

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#5766]
The new global coin control feature is awesome! I especially love the status bar at the bottom.

However the bottom half of the text is cut off for me making it hard to read:

<img width="1226" alt="Screenshot 2019-11-17 at 13 13 37" src="https://user-images.githubusercontent.com/2123375/69004185-937a2000-0941-11ea-992c-eee6b4879868.png">

If it's relevant I'm testing on macOS Mojave 10.14. I have the light (default) Electrum theme enabled, NOT the dark theme. I"m using global dark mode in macOS which is inherited by many 3rd party apps. I'm not sure if the dark background I'm seeing in Electrum is something you've added or a default QT thing because it's picking up my dark mode macOS setting.

Tested on current tip of master: cbd146a

**Comment by ecdsa** [comment]
does it get fixed if you comment out line 1987:
`sb.setFixedHeight(3 * char_width_in_lineedit())`

**Comment by lukechilds** [comment]
It's visible, although now it's too big:

<img width="1226" alt="Screenshot 2019-11-17 at 21 24 51" src="https://user-images.githubusercontent.com/2123375/69008768-db6c6780-0980-11ea-8259-e0e43b425ec6.png">

Setting to:

```python
sb.setFixedHeight(3.5 * char_width_in_lineedit())
```

looks good:

<img width="1226" alt="Screenshot 2019-11-17 at 21 23 21" src="https://user-images.githubusercontent.com/2123375/69008782-f9d26300-0980-11ea-8ab9-9cd3bba75d93.png">

Although is this OS/font specific? Maybe 3.5 will look wrong on other OSs?

Would it be better to set a fixed pixel height and then horizontally centre the label inside it?

Any, PR using 3.5 for your convenience if you wanna test: https://github.com/spesmilo/electrum/pull/5769

**Comment by ecdsa** [comment]
yes, results are probably font specific.
I'll comment out that line for now
