### ISSUE TITLE
[Lightning] Wallet shows undescriptive error when trying to open channel with no balance

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#5783]
If you have no balance, go to open a channel, and then click the "Max" button, Electrum shows an error dialog with no helpful warning in the UI.

<img width="1130" alt="Screenshot 2019-11-21 at 08 03 55" src="https://user-images.githubusercontent.com/2123375/69291351-8ad16480-0c35-11ea-8308-f147c5c01602.png">

```
E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/Users/lukechilds/dev/oss/electrum/electrum/gui/qt/channels_list.py", line 180, in spend_max
    tx = make_tx(None)
  File "/Users/lukechilds/dev/oss/electrum/electrum/lnworker.py", line 834, in mktx_for_open_channel
    fee=fee_est)
  File "/Users/lukechilds/dev/oss/electrum/electrum/wallet.py", line 1000, in make_unsigned_transaction
    raise NotEnoughFunds()
electrum.util.NotEnoughFunds: Insufficient funds
```

Tested at 9fe79171186e9e98aab266282c055a90dac9de18

**Comment by SomberNight** [comment]
It's more generic than that.
When you click "max" in either the `Send` tab directly, or in the "Open channel" dialog, exceptions are not handled at all.
Under the hood, `wallet.make_unsigned_transaction` gets called, and there are at least two very common exceptions that can get raised: `NotEnoughFunds` and `NoDynamicFeeEstimates`

https://github.com/spesmilo/electrum/blob/9fe79171186e9e98aab266282c055a90dac9de18/electrum/gui/qt/main_window.py#L1294
https://github.com/spesmilo/electrum/blob/9fe79171186e9e98aab266282c055a90dac9de18/electrum/gui/qt/channels_list.py#L180

related: https://github.com/spesmilo/electrum/issues/5784
