### ISSUE TITLE
[Lightning] TEMPORARY_CHANNEL_FAILURE

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#5785]
I'm doing some testing paying between LN wallets.

I have two Lightning enabled Electrum wallets running and I'm trying to pay one from the other.

I create an invoice in one wallet and go to spend it in the other, however I keep getting the error:

```
<OnionFailureCode.TEMPORARY_CHANNEL_FAILURE: 4103>
```

<img width="1134" alt="Screenshot 2019-11-21 at 11 39 42" src="https://user-images.githubusercontent.com/2123375/69304709-2eca0880-0c54-11ea-9751-a0b88a65f589.png">

I have enough local capacity on the spending wallet and enough remote capacity on the receiving wallet. I also left plenty of space for fees.

Are you able to provide any more information on what this error means? Unable to find a route? Something else?

**Comment by ecdsa** [comment]
check if the channel ID that reports the failure is the recipient's channel, or an intermediate channel

**Comment by lukechilds** [comment]
@ecdsa Sorry I've deleted that wallet now so I'm not able to check.

I believe I opened the channel with a poorly connected peer. I got the same error trying to pay multiple different wallets that I know are all well connected.

I tried with a new wallet and manually specified a well connected peer to open a channel with, then payments to all the same wallets succeeded.

Also I noticed when submitting an issue it says GitHub is for bug reports, not general questions. This seemed like a grey area but is there somewhere else more suitable for asking questions?

**Comment by ecdsa** [comment]
poorly connected peers are a general issue, indeed

**Comment by ecdsa** [comment]
well, to answer your other question, we should write some documentation for lightning :-)

**Comment by SomberNight** [comment]
I would say ~on-topic technical questions that do not seem to be dupe are OK to be asked.
