### ISSUE TITLE
LN channel hangs on status 'opening'.

### ISSUE THREAD

**Issue by Coinomatron** [spesmilo/electrum#5786]
Installed 4.0.0a0, opened a LN channel (not testnet), but the status doesn't change, looks like it hangs on 'OPENING'. Short channel id says 'not yet established'. 66 confirmations on the original transaction from which the LN channel was opened. Wallet has bc1.... address format. Any ideas?

**Comment by ecdsa** [comment]
what happens if you restart electrum?
can you please post a verbose log of electrum?

**Comment by Coinomatron** [comment]
Here's some of the output from start-up. I'm using electrum personal server, perhaps that makes a difference.

D | util.profiler | AddressSynchronizer.check_history 0.0002
I | channel_db.ChannelDB | SQL thread started
I | channel_db.ChannelDB | Creating database
D | util.profiler | JsonDB._load_transactions 0.0000
D | util.profiler | AddressSynchronizer.load_local_history 0.0000
D | util.profiler | AddressSynchronizer.check_history 0.0000
I | lnworker.LNWallet | funding tx is still not at sufficient depth. actual depth: 0
D | util.profiler | WalletStorage.write 0.0000
I | lnworker.LNWallet | funding tx is still not at sufficient depth. actual depth: 0
D | util.profiler | AddressList.update 0.0209
D | util.profiler | Deterministic_Wallet.try_detecting_internal_addresses_corruption 0.0624
D | util.profiler | ElectrumWindow.load_wallet 0.1046
I | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
D | util.profiler | Abstract_Wallet.get_full_history 0.0005
D | util.profiler | HistoryModel.refresh 0.0013
D | util.profiler | AddressList.update 0.0061
I | lnworker.LNWallet | adding peer 0260fab633066ed7b1d9b9b8a0fac87e1579d1709e874d28a0d171a1f5c43bb877@54.245.57.153:9735
D | lnpeer.Peer.[54.245.57.153:9735] | Sending INIT
I | channel_db.ChannelDB | load data 34698 55047 5961
I | channel_db.ChannelDB | semi-orphaned: 30753
D | util.profiler | ChannelDB.load_data 1.7056
I | lnworker.LNGossip | adding peer 0379749b3a6bb297e746909df7531419bc4d05b5e31f21621c9f8ef52336b7909e@35.196.118.140:9735
I | lnworker.LNWallet | adding peer 0379749b3a6bb297e746909df7531419bc4d05b5e31f21621c9f8ef52336b7909e@35.196.118.140:9735
I | channel_db.ChannelDB | Deleting 3494 orphaned channels
D | lnpeer.Peer.[54.245.57.153:9735] | Sending PING
D | lnpeer.Peer.[54.245.57.153:9735] | Sending CHANNEL_REESTABLISH
I | lnpeer.Peer.[54.245.57.153:9735] | channel_reestablish: sent channel_reestablish with (next_local_ctn=1, oldest_unrevoked_remote_ctn=0)
I | lnpeer.Peer.[54.245.57.153:9735] | channel_reestablish: received channel_reestablish with (their_next_local_ctn=1, their_oldest_unrevoked_remote_ctn=0)
I | lnpeer.Peer.[54.245.57.153:9735] | channel_reestablish: replayed 0 unacked messages
I | lnpeer.Peer.[54.245.57.153:9735] | on_funding_locked. channel: eda152ac82d1eb45bc5157038538160b62840f3c4c91d1c23b682ed02ff9dcf4
I | lnworker.LNGossip | adding peer 03ec127a04ac464577bdba9637ca7c8edcd0e27c4ffeef5094a10ad69eeae76800@107.3.136.16:9735
I | lnworker.LNWallet | adding peer 03ec127a04ac464577bdba9637ca7c8edcd0e27c4ffeef5094a10ad69eeae76800@107.3.136.16:9735
I | lnpeer.Peer.[107.3.136.16:9735] | Disconnecting: GracefulDisconnect('initialize failed: ConnectionRefusedError(111, "Connect call failed (\'107.3.136.16\', 9735)")')
I | lnpeer.Peer.[107.3.136.16:9735] | Disconnecting: GracefulDisconnect('initialize failed: ConnectionRefusedError(111, "Connect call failed (\'107.3.136.16\', 9735)")')
I | lnworker.LNGossip | adding peer 03995b9141901356e796619f86778dac7047bafd9cd779de0fd4ec3ad3bed38f02@24surpavl2wraiid.onion:9735
I | lnworker.LNWallet | adding peer 03995b9141901356e796619f86778dac7047bafd9cd779de0fd4ec3ad3bed38f02@24surpavl2wraiid.onion:9735
I | lnpeer.Peer.[24surpavl2wraiid.onion:9735] | Disconnecting: GracefulDisconnect("initialize failed: gaierror(-2, 'Name or service not known')")
I | lnpeer.Peer.[24surpavl2wraiid.onion:9735] | Disconnecting: GracefulDisconnect("initialize failed: gaierror(-2, 'Name or service not known')")
I | lnworker.LNGossip | adding peer 03a69b27e8045aac09e2984ffbcbfaca6f8eb5bac4196b0ff851ed900575c23e34@hl264xkvj7ai3tktcfzxrhdbrdxmvhmptpedq57pxduc7cewv2jvgbad.onion:9735
I | lnworker.LNWallet | adding peer 03a69b27e8045aac09e2984ffbcbfaca6f8eb5bac4196b0ff851ed900575c23e34@hl264xkvj7ai3tktcfzxrhdbrdxmvhmptpedq57pxduc7cewv2jvgbad.onion:9735
I | lnpeer.Peer.[hl264xkvj7ai3tktcfzxrhdbrdxmvhmptpedq57pxduc7cewv2jvgbad.onion:9735] | Disconnecting: GracefulDisconnect("initialize failed: gaierror(-2, 'Name or service not known')")
I | lnpeer.Peer.[hl264xkvj7ai3tktcfzxrhdbrdxmvhmptpedq57pxduc7cewv2jvgbad.onion:9735] | Disconnecting: GracefulDisconnect("initialize failed: gaierror(-2, 'Name or service not known')")
I | lnworker.LNGossip | adding peer 02f1d4269294176bdd64088a38324de75b927baf3328047257fed3e087b0316b40@v42wljoh6gcf66bn2erlxjeqwip2laucdk356xavo63sr4jwztp2ofqd.onion:9735
I | lnworker.LNWallet | adding peer 02f1d4269294176bdd64088a38324de75b927baf3328047257fed3e087b0316b40@v42wljoh6gcf66bn2erlxjeqwip2laucdk356xavo63sr4jwztp2ofqd.onion:9735
I | lnpeer.Peer.[v42wljoh6gcf66bn2erlxjeqwip2laucdk356xavo63sr4jwztp2ofqd.onion:9735] | Disconnecting: GracefulDisconnect("initialize failed: gaierror(-2, 'Name or service not known')")
I | lnpeer.Peer.[v42wljoh6gcf66bn2erlxjeqwip2laucdk356xavo63sr4jwztp2ofqd.onion:9735] | Disconnecting: GracefulDisconnect("initialize failed: gaierror(-2, 'Name or service not known')")
D | lnpeer.Peer.[54.245.57.153:9735] | process_gossip 0 0 11
I | lnpeer.Peer.[54.245.57.153:9735] | adding 1 unknown channel ids
D | lnpeer.Peer.[54.245.57.153:9735] | on_channel_update: 7/11
I | lnworker.LNGossip | adding peer 02efddba17ca713f9ec065242c5e6582cc40b40

**Comment by ecdsa** [comment]
you cannot use EPS with lightning

**Comment by Coinomatron** [comment]
Oops :)

**Comment by Coinomatron** [comment]
Short follow up, the channel got established when not connecting through EPS. I connected via EPS again and see electrum is connected to 4 nodes in the LN network. The command line argument on start-up was  

./run_electrum --oneserver --server localhost:50003:s -v

**Comment by ecdsa** [comment]
you should not use EPS together with lightning. if you connect to EPS after the channel is established, your client will not react properly if the channel is closed.

@chris-belcher could you warn EPS users about that?

**Comment by Coinomatron** [comment]
Haven't made a LN transaction yet, if I don't connect via EPS, I should be able to close it ok?

**Comment by SomberNight** [comment]
Yes, you should be able to close it, even if you made some payments.
The issue with EPS is about detecting/handling force-closes (aka unilateral closes).
