### ISSUE TITLE
electrum not conected to servers 

### ISSUE THREAD

**Issue by carlska** [spesmilo/electrum#5790]
i try open my wallet but when i open electrum he try connected to servers but not connected 
95/98 ...  37/39  ...and other 
but  red circle  only 
how fix its ? 
internet conection is ok 
and i have other wallet with btc  i try open  and all ok

**Comment by ecdsa** [comment]
1. download the latest version of electrum
2. if that does not fix it, delete your "config" file

**Comment by carlska** [comment]
i have last version
where is config file ?

and i have other wallet with btc i try open and all ok on in pc 
its wallet not open 
where in config file ?

**Comment by SomberNight** [comment]
The config file is in the data directory, see
https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#where-is-the-electrum-datadir-located

Please [enable debug logging](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging), and upload the logs.

**Comment by carlska** [comment]
find delete
not help

**Comment by SomberNight** [comment]
Please upload debug logs.

**Comment by carlska** [comment]
I/n | network | fee_estimates {25: 6559, 10: 18274, 5: 20099, 2: 28328}
E/i | interface.[thanos.xskyx.net:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'),)
I/n | network | switching to electrum.jochen-hoenicke.de:50005:s
I/i | interface.[vmd27610.contaboserver.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(-2, 'Неизвестное имя или служба'),),)
I/n | network | couldn't launch iface vmd27610.contaboserver.net:50002:s -- CancelledError()
I/i | interface.[electrumx.kenrufe.com:50002] | disconnecting due to: ConnectError(ConnectionRefusedError(111, "Connect call failed ('108.183.77.12', 50002)"),)
I/n | network | couldn't launch iface electrumx.kenrufe.com:50002:s -- CancelledError()
I/n | network | fee_histogram [[46, 119948], [39, 94774], [29, 132366], [28, 135278], [25, 137485], [20, 477401], [19, 103714], [18, 55144], [16, 202488], [14, 186705], [12, 272243], [9, 509719], [8, 79794], [6, 756560], [5, 324824], [4, 742152], [3, 875319], [2, 1079612], [1, 2228693], [0, 2717786]]
I/n | network | fee_estimates {25: 6559, 10: 18274, 5: 20099, 2: 28328}
E/i | interface.[electrum.jochen-hoenicke.de:50005] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'),)
I/n | network | switching to xtrum.com:50002:s
I/i | interface.[electrumx.soon.it:50002] | disconnecting due to: ConnectError(ConnectionRefusedError(111, "Connect call failed ('185.11.145.76', 50002)"),)
I/n | network | couldn't launch iface electrumx.soon.it:50002:s -- CancelledError()
I/i | interface.[daedalus.bauerj.eu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(111, "Connect call failed ('151.80.161.244', 50002)"),),)
I/n | network | fee_histogram [[45, 130428], [30, 95306], [28, 157087], [26, 121159], [21, 119732], [20, 349512], [19, 100131], [17, 116006], [15, 236841], [13, 281254], [11, 171071], [9, 414518], [7, 206516], [6, 629023], [5, 324149], [4, 741701], [3, 875319], [2, 1079422], [1, 2193824]]
I/n | network | fee_estimates {25: 6559, 10: 18274, 5: 20099, 2: 28328}
I/n | network | couldn't launch iface daedalus.bauerj.eu:50002:s -- CancelledError()
E/i | interface.[xtrum.com:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'),)
I/n | network | switching to electrum.fedaykin.eu:50005:s
I/i | interface.[exs.ignorelist.com:50002] | connection established. version: ['ElectrumX 1.12', '1.4']
I/n | network | fee_histogram [[45, 124480], [30, 92310], [28, 153498], [26, 120412], [20, 464034], [19, 99697], [18, 53946], [17, 61611], [15, 236642], [13, 269112], [10, 293083], [9, 292506], [7, 206516], [6, 629023], [5, 323924], [4, 741697], [3, 875095], [2, 1079239], [1, 2193929]]
I/n | network | fee_estimates {25: 6559, 10: 18274, 5: 20099, 2: 28328}
I/i | interface.[exs.ignorelist.com:50002] | set blockchain with height 604917
I/i | interface.[exs.ignorelist.com:50002] | skipping header 604917
I/i | interface.[btc.usebsv.com:50006] | connection established. version: ['ElectrumX 1.13.0', '1.4']
I/i | interface.[btc.usebsv.com:50006] | set blockchain with height 604917
I/i | interface.[btc.usebsv.com:50006] | skipping header 604917
E/i | interface.[electrum.fedaykin.eu:50005] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'),)
I/n | network | switching to exs.ignorelist.com:50002:s
I/n | network | fee_histogram [[45, 125749], [30, 93866], [28, 155013], [26, 120412], [21, 116794], [20, 348515], [19, 99697], [17, 115557], [15, 236841], [13, 269482], [10, 293083], [9, 292506], [7, 206516], [6, 629023], [5, 323924], [4, 741923], [3, 875095], [2, 1079239], [1, 2193929]]
I/n | network | fee_estimates {25: 6559, 10: 18274, 5: 20099, 2: 28328}
I/i | interface.[ns3079944.ip-217-182-196.eu:50002] | disconnecting due to: ConnectError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)
I/n | network | couldn't launch iface ns3079944.ip-217-182-196.eu:50002:s -- CancelledError()
^C^CI/p | plugin.Plugins | stopped
I | storage.WalletStorage | saved /home/wallet/Рабочий стол/work-wallet/wallet-work
D | util.profiler | WalletStorage.write 1.8843
I/d | daemon.Daemon | shutting down network
I/n | network | stopping network
I/i | interface.[electrum3.hodlister.co:50002] | disconnecting due to: CancelledError()
I/i | interface.[currentlane.lovebitco.in:50002] | disconnecting due to: CancelledError()
I/n | network | couldn't launch iface electrumx.bot.nu:50002:s -- CancelledError()
I/i | interface.[electrum2.eff.ro:50002] | disconnecting due to: CancelledError()
I/n | network | couldn't launch iface electrum-server.ninja:50002:s -- CancelledError()
I/n | network | couldn't launch iface b.ooze.cc:50002:s -- CancelledError()
I/i | interface.[electrum-server.ninja:50002] | disconnecting due to: CancelledError()
I/i | interface.[electrum.hsmiths.com:50002] | disconnecting due to: CancelledError()
I/i | interface.[VPS.hsmiths.com:50002] | disconnecting due to: CancelledError()
I/n | network | couldn't launch iface btc.cihar.com:50002:s -- CancelledError()
I/i | interface.[btc.cihar.com:50002] | disconnecting due to: CancelledError()
I/n | network | couldn't launch iface electrum.hsmiths.com:50002:s -- CancelledError()
I/n | network | couldn't launch iface yuio.top:50002:s -- CancelledError()
I/i | interface.[btc.usebsv.com:50006] | disconnecting due to: CancelledError()
I/i | interface.[fortress.qtornado.com:443] | disconnecting due to: CancelledError()
I/i | interface.[electrum.hodl-shop.io:50002] | disconnecting due to: CancelledError()
I/i | interface.[exs.ignorelist.com:50002] | disconnecting due to: CancelledError()
I/d | daemon.Daemon | stopped

but other wallet with btc open

**Comment by carlska** [comment]
i try restore wallet with seed  
and restoring wallet same problem

**Comment by carlska** [comment]
how fix it ?

**Comment by SomberNight** [comment]
>  E/i | interface.[thanos.xskyx.net:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'),)

Servers keep kicking the client because it's asking for an address that has a too large history (in practice, probably >10k transactions). The client keeps switching servers and reconnecting.

Having addresses with very these very long histories is currently not supported.

closing in favour of https://github.com/spesmilo/electrum/issues/4315

**Comment by carlska** [comment]
how fix it or how send coin on other wallet ?

**Comment by SomberNight** [comment]
> how fix it or how send coin on other wallet ?

Approx how many transactions does this busy address have?
(it's not about the total number of transactions in your wallet; it's about a single address having too many transactions)

Addresses should not be reused anyway, it's generally considered bad practice; it greatly hurts your privacy.

**Comment by carlska** [comment]
Transactions
10,399

**Comment by SomberNight** [comment]
> Transactions
10,399

Ok I've increased the limit to around 4x on this server: `fortress.qtornado.com:443`
Try to connect to that.

Is this an imported address or is this an address in a deterministic wallet?
In any case, you should create a new wallet and send all coins from this address there.
Then, use that wallet from now on; and I would suggest not to reuse addresses (at least not this many times!) in the future.

**Comment by SomberNight** [comment]
Btw, may I ask what your usecase is? Why do you have that many transactions associated with a single address?
