### ISSUE TITLE
Error calling open_channel via rpc

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#5793]
Calling `open_channel` via jsonrpc with option `push_amount` I keep getting a `decimal.IvalidOperation: [<class 'decimal.ConversionSyntax'>]`.

The related logs are:
```
E | daemon.Daemon | error handling request: {"id": 1, "method": "open_channel", "params": [{"--push_amount": 0.01}, "038f548556317329f59ee3a049583e0f3fc571c8955595ce44a6f729cabd92cf0c@electrum_bob:9736", 0.0001], "jsonrpc": "2.0"}
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/jsonrpcserver/dispatcher.py", line 124, in handle_exceptions
yield handler
File "/usr/local/lib/python3.7/dist-packages/jsonrpcserver/async_dispatcher.py", line 40, in safe_call
methods.items[request.method], *request.args, **request.kwargs
File "/usr/local/lib/python3.7/dist-packages/jsonrpcserver/async_dispatcher.py", line 34, in call
return await validate_args(method, *args, **kwargs)(*args, **kwargs)
File "/srv/app/electrum/electrum/commands.py", line 121, in func_wrapper
return await func(*args, **kwargs)
File "/srv/app/electrum/electrum/commands.py", line 928, in open_channel
funding_sat = satoshis(amount)
File "/srv/app/electrum/electrum/commands.py", line 73, in satoshis
return int(COIN*Decimal(amount)) if amount not in ['!', None] else amount
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```
Am I calling it the wrong way?

I tried, instead of `{"--push_amount": 1e-06}`, also:
- "--push_amount 1e-06" 
- "push_amount 1e-06" 
- {"push_amount": 1e-06}
and I get the same result.

If it matters I'm calling it from python 3.5 (on a debian buster) using the `request` module.

**Comment by ecdsa** [comment]
try like this:
`"params": [{"push_amount": 0.01, "038f548556317329f59ee3a049583e0f3fc571c8955595ce44a6f729cabd92cf0c@electrum_bob:9736", "amount":"0.0001"}]`

**Comment by St333p** [comment]
I tried like you suggested but I get a `"RPC connection failure: 400 Bad Request"` both when I include the `push_amount` and when I don't. I tried both passing the amounts as `string` and as `int`.
Electrum doesn't log anything in this case.

**Comment by St333p** [comment]
The call seems to work properly if made like this:
```
"params": {"push_amount": 0.01, "connection_string":"038f548556317329f59ee3a049583e0f3fc571c8955595ce44a6f729cabd92cf0c@electrum_bob:9736", "amount": 0.0001}
```
Issue can be closed for me

**Comment by SomberNight** [comment]
> "push_amount": 0.01
> "amount": 0.0001

That sounds like you are pushing more than you have.

**Comment by St333p** [comment]
I hadn't noticed, but electrum returns no error in this last case.

I'll add a check before the call

**Comment by ecdsa** [comment]
indeed the reserve should be met

**Comment by ecdsa** [comment]
Errors returned by the remote peer in `open_channel` are now displayed on the command line
(see commit ac884eb3c34a42bd93aebc966a7dd0d764057f76)

Example:
```
voegtlin@electrum:~/electrum$ ./run_electrum open_channel 03456789cf938f466c0cc15d5be572535208735c342bb70acda048d6cfb130e449 0.001 --push_amount 0.001
Password:
Remote Lightning peer reported error: b'You gave bad parameters: Could not meet our fees and reserve: Funder cannot afford fee on initial commitment transaction'
```

One remaining issue is that the incompletely created channel remains in the wallet, I will fix that later.
