### ISSUE TITLE
lnpay doesn't return the payment preimage

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#5794]
Currently a call to `lnpay` returns a boolean `success`.
```
# file electrum/commands.py
async def lnpay(self, invoice, attempts=1, timeout=10, wallet: Abstract_Wallet = None):
    return await wallet.lnworker._pay(invoice, attempts=attempts)
# file electrum/lnworker.py
async def _pay(self, invoice, amount_sat=None, attempts=1):
        # more stuff here...
        success, preimage, failure_log = await self._pay_to_route(route, lnaddr)
            if success:
                log.append((route, True, preimage))
                break
            else:
                log.append((route, False, failure_log))
        self.network.trigger_callback('invoice_status', key, PR_PAID if success else PR_FAILED)
return success
```
- I would expect it to return the `preimage` as well since it has an important meaning in the context of the LN invoice. 
- It would also be nice to get info about the type of error that cause a payment to fail.

Is it maybe possible to get this info from elsewhere?

**Comment by ecdsa** [comment]
The preimage is now returned in the `lightning_history` command (per feb47b0a6ff7c5f0dd4ab09ccdb1443133198ff9)

**Comment by St333p** [comment]
As a new user I would still expect it from the `lnpay` call, but for the moment I guess it can work. Although I expect the payment process to be quite time consuming if I have to fetch a long `lightning_history` output all the time.
I'll test it in the next days and let you know.

**Comment by ecdsa** [comment]
fixed; lnpay now returns a list of values.
