### ISSUE TITLE
WIF key with scalar outside curve order is accepted

### ISSUE THREAD

**Issue by tnkmt** [spesmilo/electrum#5797]
I found this in the source code:

```
def _CKD_priv(parent_privkey: bytes, parent_chaincode: bytes,
              child_index: bytes, is_hardened_child: bool) -> Tuple[bytes, bytes]:
    try:
        keypair = ecc.ECPrivkey(parent_privkey)
    except ecc.InvalidECPointException as e:
        raise BitcoinException('Impossible xprv (not within curve order)') from e
    parent_pubkey = keypair.get_public_key_bytes(compressed=True)
    if is_hardened_child:
        data = bytes([0]) + parent_privkey + child_index
    else:
        data = parent_pubkey + child_index
    I = hmac_oneshot(parent_chaincode, data, hashlib.sha512)
    I_left = ecc.string_to_number(I[0:32])
    child_privkey = (I_left + ecc.string_to_number(parent_privkey)) % ecc.CURVE_ORDER
    if I_left >= ecc.CURVE_ORDER or child_privkey == 0:
        raise ecc.InvalidECPointException()
    child_privkey = ecc.number_to_string(child_privkey, ecc.CURVE_ORDER)
    child_chaincode = I[32:]
    return child_privkey, child_chaincode
```
Is this check only working when the private key is being generated from the master private key? Or it's not working at all?

The invalid Bitcoin key I used to test Electrum was `5Km2kuu7vtFDPpxywn4u3NLu8iSdrqhxWT8tUKiNTjDB7yUFUg3`.

Also, I tried the "Bitaddress", "TP's Go Bitcoin Tests - Private keys" and "Bitcoin Key Compression Tool - Ian Coleman" with this invalid WIF private key and they give error message like expected.

Coinbin also [have this bug](https://github.com/OutCast3k/coinbin/issues/204).

[Discussion on Reddit.](https://old.reddit.com/r/Bitcoin/comments/e0m6ft/are_all_possible_bip39_mnemonic_seeds_produce_a/)

**Comment by SomberNight** [comment]
Yes, you can import WIF keys where the ecc scalar falls outside the curve range. We take the privkey modulo the group order.
This is not a bug; it's a design decision.
https://github.com/spesmilo/electrum/blob/ddeb176b3da0c4fcbb6cf2b8d85dd319e2a2bf56/electrum/bitcoin.py#L610-L611

**Comment by SomberNight** [comment]
>def _CKD_priv(parent_privkey: bytes, parent_chaincode: bytes,
>              child_index: bytes, is_hardened_child: bool) -> Tuple[bytes, bytes]:

That method is about bip32.

**Comment by tnkmt** [comment]
What will happen if anyone is receiving coins to such address and then tries to spend them?
Coins will be unmovable (lost)?

**Comment by SomberNight** [comment]
No. It will work. You can test it on testnet/regtest.

**Comment by tnkmt** [comment]
It make sense. Nodes do not know the private key (they "see" only the addresses, public keys and signatures).

And it's not possible in practice to detect invalid private keys just by looking at their addresses, public keys and signatures. Right?

**Comment by SomberNight** [comment]
Effectively, with what we are doing, some group elements have two representations; while most only have one. Your "invalid" key contains a number that is too large to be a group element; but we subtract the group order from it and use that number instead. It's as if you imported the "valid" key in the first place.

In fact if you try to export it, we will give you the "valid" one.
Just try it: create an imported wallet from key `5Km2kuu7vtFDPpxywn4u3NLu8iSdrqhxWT8tUKiNTjDB7yUFUg3` and then try to export the key.
It will export `5HpHagT65TZzG1PH3CSu63kCkUBpkA7sBXKmV2joANEAPgL2Hb6` instead.

**Comment by chriswebstin** [comment]
Have you lost $5k and above while trading on Binary Option? Have you tried getting your money out from your binary account and was unable to place a withdrawal? Have you found your self wading through excessively complicated terms which might seem impossible to meet, all because you traded with an unregulated broker? Do not panic, I have good news for you. I lost over $200k to an unregulated broker who stocked my trading capital and denied me access to my account. But thank God I have recovered all my lost funds, through the help of a certified binary recovery expert. if his assistance is needed, kindly get in contact with him via gmail @ULTIMATEFUNDRECOVERY and he will guide you on effective steps to take and get back all your lost funds in just few days. he also has WHATSAPP  at +14079061584 TEXT :  +14079061584
