### ISSUE TITLE
Electrum 4.0.0a0 crashes on regular on chain payment

### ISSUE THREAD

**Issue by Coinomatron** [spesmilo/electrum#5802]
Opened an existing electrum wallet (I used with version 3.3.8 and lower), tried to do a transaction, but after clicking the 'sign' button, electrum crashes, verbose output below.

File "/home/user/electrum/electrum/gui/qt/transaction_dialog.py", line 305, in sign
self.main_window.sign_tx(self.tx, sign_done, self.external_keypairs)
AttributeError: 'PreviewTxDialog' object has no attribute 'external_keypairs'
Aborted (core dumped)

**Comment by SomberNight** [comment]
dupe of https://github.com/spesmilo/electrum/issues/5764 ?

**Comment by SomberNight** [comment]
As in, please try with latest master.

**Comment by Coinomatron** [comment]
Ah yes, probably a duplicate. Electrum 4 breaks compatibility with 3.3.8 wallets, that's a know thing I take it? Will reopen if I happen to stumble on it again.
