### ISSUE TITLE
Error when trying to open LN channel

### ISSUE THREAD

**Issue by theBergmann** [spesmilo/electrum#5805]
Hi, I am testing lightning functionality in Electrum.

I try to open a lightning channel with Electrum 4.0.

After doing init_lightning () I tryped this in the console:

open_channel('02929175ac215cb282cd965d21b8bde87cf18828a4824f6a6e12b0098631b9f535', '0.0005')

Something wrong with this command? I tried also the amount in Satoshi, but got "insufficient funds. I also tried it with and without quotation marks, also with the full lightning node address (adding ip + port).

**Comment by ecdsa** [comment]
> After doing init_lightning () I tryped this in the console:
you should restart electrum after typing init_lightning

**Comment by SomberNight** [comment]
Are you purposefully using the Qt console to test?
You can enable lightning in `Wallet`>`Information`;
and you can open/manage channels in the `Channels` tab :P

**Comment by theBergmann** [comment]
Didn't know it is in the gui. It's a bit hidden, so I assumed it was just in the console.

Now I'm opening a channel. Very cool. Will try this out, and post updates, if you don't mind.
