### ISSUE TITLE
Non intuitive (wrong?) behavior of the fee setup

### ISSUE THREAD

**Issue by ldz1** [spesmilo/electrum#5807]
**first issue:**
1. Fee option "Edit fees manually" was set.
2. Fee edit box contains min fee 1.9 sat/byte
3. Fee slide is light blue
4. Set focus inside the fee edit box
5. Set focus inside another edit box like "description" edit box
6. Fee slide color changes to gray

As a user I don't quite follow why the color has changed and what meaning it has.

**second issue:**
1. Fee option "Edit fees manually" was set.
2. Fee edit box contains min fee 1.9 sat/byte
3. Fee slide is light blue
4. Change fee inside the fee edit box to <1.9 sat/byte
5. Fee slide color has changed to gray
6. Send 
7. The transaction was sent with 1.9 sat/byte.

As a user I would expect that I can either send my transaction with  <1.9 sat/byte fee or I get a message that it is not working. Even better, it would not let me setup invalid value.

**Comment by SomberNight** [comment]
Please try with master; all this interface you describe has changed drastically.

**Comment by ldz1** [comment]
@SomberNight: Thanks, I will check it. I will give you feedback soon.
