### ISSUE TITLE
Tab switch when opening help

### ISSUE THREAD

**Issue by ldz1** [spesmilo/electrum#5808]
case 1:
1. Open a tab (such as History).
2. Switch to another tab.
3. Open Help -> Check for updates
4. Check for "Check for Updates" window pops up. Nothing special happens.

case 2:
1. Open a tab.
2. Switch to another tab.
3. Open Help -> About for updates
4. The tab changes twice. It happens pretty fast. After that "About" window pops up.

If you can not reproduce the case 2, try switching between the tabs several times.

In general, nothing is wrong here. However, changing the view when opening the about window is a bit surprising.

**Comment by ecdsa** [comment]
cannot reproduce.
maybe you pressed a keyboard shortcut that changes tab (Alt+number)

**Comment by SomberNight** [comment]
I could not reproduce either. I suspect it might be a Qt bug affecting a specific version of Qt.
