### ISSUE TITLE
Electrum wallet softwre on big wallets

### ISSUE THREAD

**Issue by bitcoinoplomo** [spesmilo/electrum#5813]
Lets say that I am using cold storage with Electrum.
So I have 2 machines. 
One machine will stay offline all the time and it only create and sign transactions and I will call it the signer.
The other machine is online and will create and broadcast transactions using watch only wallets and I will call it the online machine.

In  the online machine I am using electrs to connect to my bitcoin full node!
There is any limitation on the number of addresses I can use on the watch only machine?

Can I use a really big wallet, like having 5000 addresses? 

When restoring this really big wallet from the seedkey there will be any problem?

**Comment by SomberNight** [comment]
The setup you describe is explicitly supported and should work well.

> When restoring this really big wallet from the seedkey there will be any problem?

Read up on the [gap limit](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#what-is-the-gap-limit). Just leave the gap limit alone (can only be modified using the console) and you will be fine. Besides that, it should work.

> Can I use a really big wallet, like having 5000 addresses?

Electrum (the client) does not scale well for really large wallets. Performance degrades as the wallet becomes larger. Around 10k transactions (in history) or 10k addresses already generated, the GUI will sometimes freeze for several seconds.
If your wallet becomes this large, you should consider creating a new wallet and sending all coins from the old one there.

**Comment by bitcoinoplomo** [comment]
Thanks!

**Comment by chriswebstin** [comment]
The whole crypto currency investment is full of scam ,A lot of unregulated brokers and Account managers are operating illegally stealing fund from traders. I don’t comment on articles easily,but I need to share this for the sake of other followers.I lost my investment capital of over $340,000 USD to unregulated Binary option broker.After my account generated thousands of profits the requested for additional fee before my withdrawal request can be processed at the end I lost all my money.All my efforts to reach out to their customer support was unsuccessful, I was in pains and couldn’t tell anyone about it until my friend narrated how she also lost her fund until she met with Mr bruce willian who who helped her to recovered her money back . I narrated my story to her too and she advice me to contact same Mr bruce willian  who specialized in helping all scammed victims with valid proofs to get their fund back , I contacted Mr Frederick personal email he instructed me to provide all legal details of my investment, I did as instructed.All like a dream I was able to recovered all my money back through the help of Mr Frederick Morris and other financial authorities. I want to encourage you reading this , don’t sit back and cry why your Account Manager or broker enjoy your money , contact Mr bruce willian  he will guide you on how you can successfully get back your money . You can reach him via his Gmail .. @ULTIMATEFUNDRECOVERY 
WHATSAPP:+14079061584 
TEXT:  +14079061584
