### ISSUE TITLE
close_channel fails if not forced

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#5814]
When trying to close a channel with an online node I get a binary string as result (no errors, no logs) and the channel remains in the old state (be it 'OPEN' or 'OPENING'):
```
b'\x03\x8fT\x85V1s)\xf5\x9e\xe3\xa0IX>\x0f?\xc5q\xc8\x95U\x95\xceD\xa6\xf7)\xca\xbd\x92\xcf\x0c'
```
If I force the call the channel closes correctly and I get a correct `txid` like:
```
c716cd05285bc07f9f1471abb110f991abedda4784074c2836fe57f37addba5a
```

**Comment by St333p** [comment]
Any update on this?

**Comment by ecdsa** [comment]
I cannot reproduce this. it might have been a connectivity issue with the remote node

**Comment by St333p** [comment]
I updated electrum to the current master (commit e65ce96) and the issue is still there. I don't see how it can be a connectivity issue since I'm running everything in docker containers on the same machine and it consistently happened (at least 5 times and changing computer) only when trying a regular (non forced) close. I've not yet seen it working once.
I'm happy to help if you want to know more about my configuration to reproduce this.

**Comment by ecdsa** [comment]
did you have active HTLCs in the channel?
LND returns an error in that case: `cannot co-op close channel w/ active htlcs`

**Comment by St333p** [comment]
I was in a regtest environment between two electrum nodes, but same applied for a channel with a c-lightning node.
I repeated my tests now, updating electrum to b90cbeb and apparently the issue was solved in the meanwhile, works like a charm. I'll do further tests together with different kind of nodes, but for now it looks like we can close the issue.
