### ISSUE TITLE
Missing info about channel_reserve

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#5817]
As explained in https://github.com/spesmilo/electrum/issues/5795, electrum sets the `local_reserve` to 1% of the channel capacity by default (as suggeste by BOLT). 
However, since this behavior is not shared by all the other ln implementations (lnd has it fixed by default to 546) it's not possible for an electrum node to know the real inbound capacity of a channel.
Where is it possible to retrieve this information? If it's not, do you plan to add it to the `listchannels` API?

**Comment by SomberNight** [comment]
> lnd has it fixed by default to 546

lnd too uses 1% of capacity: https://github.com/lightningnetwork/lnd/blob/8755a35860faea412c491166b2b0f27b89090ab2/server.go#L1074-L1087

Both sides set the reserve for the other party; they are not necessarily equal.

We could expose this detail others via RPC though.

**Comment by St333p** [comment]
This is a channel created between a lnd node and an electrum node (view from lnd side), repeated trials give same result:
```
{
            "active": true,
            "remote_pubkey": "039af8351cb9fc7fb858fb441caf8ddc89c7353a56cf13ff57e5dd719dbc7b40d7",
            "channel_point": "66a23a443d8be6a1946dc88f382054e59b5f31edfdba6f19fdc832a99415f2bb:0",
            "chan_id": "2035196023341056",
            "capacity": "100000",
            "local_balance": "30950",
            "remote_balance": "60000",
            "commit_fee": "9050",
            "commit_weight": "724",
            "fee_per_kw": "12500",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "local_chan_reserve_sat": "546",
            "remote_chan_reserve_sat": "1000",
        }
```
Either their default misbehaves somehow or the reserve was set to a different amount. Either way it would be nice to have this information exposed via RPC.
