### ISSUE TITLE
Can anyone call the RPC of my electrum

### ISSUE THREAD

**Issue by debuggor** [spesmilo/electrum#5826]
I installed electrum-client locally,
  Can anyone call the RPC of my electrum

I can call my own RPC of 127.0.0.1 locally. How do others can call RPC of my electrum?
Or, how do I set it up so that others can call my RPC?
thanks

**Comment by SomberNight** [comment]
> I can call my own RPC of 127.0.0.1 locally. How do others can call RPC of my electrum?

Who are others? You mean e.g. other machines on a LAN? or the Internet?

You can set the `rpchost` config variable to something other than localhost, e.g. your LAN IP if you want LAN devices to be able to reach you. I think if you set it to `0.0.0.0` it binds all interfaces and then "anyone" can reach the endpoint.

However, see https://github.com/spesmilo/electrum-docs/blob/master/merchant.rst#jsonrpc-interface
Note the remarks about security; it's not safe to expose the RPC interface outside a trusted LAN, so e.g. to the global Internet. If you want that, you should set up a secure tunnel instead (SSH/VPN/stunnel), listen only on localhost with electrum RPC, listen on all interfaces with the tunnel (e.g. sshd), and connect over ssh and then use electrum RPC through the tunnel.

**Comment by debuggor** [comment]
Thanks, i solved
