### ISSUE TITLE
Regression: Don't clear send dialog

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#5829]
In master this new behavior has started, clicking Pay or Advanced etc clears the Send dialog. This means that if there is any type of error down the line the user loses state and has to start their process over, which can be cumbersome given coin selection etc.

**Comment by SomberNight** [comment]
Yes, so the current flow on master is the following:
- user fills in output(s) (addresses and amounts), and description
- this then gets saved as an invoice and the fields are cleared
- the invoice can then be paid
    - which includes e.g. fee selection
    - input selection is also done at this point (i.e. inputs are not saved as part of the invoice)

(note that e.g. multiple invoices can also be paid at the same time; introducing a perhaps more user-friendly way for pay-to-many/batching)

There are two relevant buttons in the Send tab: "Save" and "Pay".
- "Save" clears the fields and saves the outputs as an invoice.
- "Pay" clears the fields and saves the outputs as an invoice, and starts the payment flow for the invoice.

-----

What do you suggest should be changed?

One idea I was considering is that "Pay" should not save the invoice and it should not clear the fields.
However, note that (particularly if the user goes into "Advanced" mode) it is not fully obvious when to clear the Send tab fields.
So to clarify, if we don't clear the Send tab fields in the beginning, and the user ends up making the payment, at that point we should probably clear the Send tab fields to make accidental double-payments less likely, however it is not obvious when to do this (clear fields).

**Comment by ecdsa** [comment]
we could add an 'Edit' action to the invoice menu, that moves the invoice back to the pay fields.

**Comment by ziggamon** [comment]
I suggest that you clear the field only after the payment has successfully been sent. This was the case in the past.

New behavior is that whenever there is an error the user must restart the whole process, which is a double whammy.

**Comment by SomberNight** [comment]
Do you have an example for an "error"?
Do you mean mistyping an output amount for example?

**Comment by ziggamon** [comment]
For example if the electrum server you connect to is down. Or if bitcoind returns some type of error when trying to propagate the transaction. Lots of things can go wrong when making transactions, point is that it shouldn't be cleared until there is a "the transaction was sent successfully" dialog.

**Comment by ecdsa** [comment]
Note: For onchain payents, it makes sense to not to save the invoice if the amount was typed manually and the invoice raises a NotEnoughFunds exception. This means we should check that we can pay before actually paying

**Comment by ecdsa** [comment]
fixed in 56579c282ed72a6c123fab82a015bdac5fb400c1 (Qt) and 2f13e4eb8583266310719d2ea025b4020ec54e34 (kivy)

**Comment by SomberNight** [comment]
@ecdsa note that in Qt if you click "Advanced", the invoice is still saved and the fields are cleared
