### ISSUE TITLE
seed not recognized?

### ISSUE THREAD

**Issue by rocketdog56** [spesmilo/electrum#5831]
I'm having trouble with my wallet. The seed is correct, but I can't get my wallet to restore in electrum. When I go to send money from the wallet I'm getting an error that it isn't accepting my one-time password- which has worked in the past. What can I try to do to troubleshoot?

**Comment by SomberNight** [comment]
So this is for a 2FA wallet, right?

> I'm having trouble with my wallet. The seed is correct, but I can't get my wallet to restore in electrum.

Is the "Next" button grayed out?
When did you generate the seed approximately // what version of Electrum did you use?

> When I go to send money from the wallet I'm getting an error that it isn't accepting my one-time password

Are you using Google Authenticator or similar on a phone?
Try synchronising the clock.

**Comment by rocketdog56** [comment]
it's my electrum phone wallet. Yes, 2FA and the only thing I haven't verified is that my authenticator is hooked correctly. The "next" button is grayed out. I assume these two issues (seed not restoring wallet AND 'one time password' error) are linked, but don't know right now.

**Comment by SomberNight** [comment]
> I assume these two issues (seed not restoring wallet AND 'one time password' error) are linked

No, these are most likely two separate issues.

> it's my electrum phone wallet

So you are using the Android version of Electrum? (I was previously asking about the Authenticator app that generates the OTPs)

**Comment by rocketdog56** [comment]
yes, I'm using the android version of electrum.

And yes, I have the Authenticator app on my phone, as well.

**Comment by SomberNight** [comment]
Try synchronising the clock in the Authenticator app.

 When did you generate the seed approximately // what version of Electrum did you use? Did you originally generate the seed using the Android version of Electrum?

**Comment by rocketdog56** [comment]
I'm not seeing an option to sync my authenticator clock so I'm going to explore that a little and respond to the other questions.

I generated the seed in October and I believe there has been an update since I generated that seed. I generated the seed on the Android version of Electrum.

**Comment by rocketdog56** [comment]
I'm using the MSN authenticator if that makes a difference.

**Comment by rocketdog56** [comment]
electrum wallet version 3.3.7 on my phone

**Comment by SomberNight** [comment]
> I generated the seed in October and I believe there has been an update since I generated that seed. I generated the seed on the Android version of Electrum.

If the "next" button is greyed out then the seed is not valid. Double-check for typos and reordering words etc. If you have multiple seeds, maybe you mixed them up (?)
You should figure out why the seed is not being accepted.

Once you have the seed, you can re-request the QR code to set up another authenticator for OTPs; or just disable 2FA and send your coins out.

**Comment by AbdussamadA** [comment]
the clock on your phone needs to be set to the correct time for totp codes to work. you can do that via android settings. there is no separate authenticator clock.

**Comment by PleaseHelpMeToday** [comment]
I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  16qjcKKdjMxLhXmWQ8EoqLptTTKSd6HA9k

**Comment by ecdsa** [comment]
closing, no answer
