### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by ricky454** [spesmilo/electrum#5836]
not letting me send bitcoins it says insufficient funds but I have a good amount of funds and other times it says try connecting to a different server

**Comment by AbdussamadA** [comment]
Try the things suggested [here](https://bitcoinelectrum.com/frequently-asked-questions/#why-am-i-being-told-that-i-have-insufficient-funds) for the insufficient funds issue. For the server problem [learn to change servers](https://bitcoinelectrum.com/how-to-switch-to-a-different-electrum-server/).

**Comment by ecdsa** [comment]
thanks @AbdussamadA
