### ISSUE TITLE
Is electrumx.ml in the current servers.json file a phishing/bogus server?

### ISSUE THREAD

**Issue by jbumgarner** [spesmilo/electrum#5837]
This is following up to this:  https://github.com/spesmilo/electrum/issues/5632

The servers.json file in Electrum 3.3.8 still contains electrumx.ml. On August 29, this domain was removed from the servers.json. ref: [#5596](https://github.com/spesmilo/electrum/commit/01f582cc147fcd84555e7e13e366c397c85f7c78)

Most endpoint detection security applications have this server blacklisted. How did this server get added back to the servers.json file?

**Comment by SomberNight** [comment]
Electrum is free/libre software. The git history is an open book. You can verify yourself what happened. It is you who are confused. 3.3.8 was released on July 11. That commit dates August 29. Causality dictates the change cannot be present in 3.3.8. Git master does not contain the server you reference as expected.
