### ISSUE TITLE
Taxa envio metade do meu saldo

### ISSUE THREAD

**Issue by AlexBasto2017** [spesmilo/electrum#5848]
Sei que esta área é para informar BUGs ou problemas da electrum porém é gratuito para enviar bitcoins? não encontrei em nenhum site sobre estas informações de taxas da electrum, tudo oque encontrei é de que é gratuito e só tem taxa dos mineradores. porque vou enviar 0.00199706 BTC, e esta me descontando 0.00000294 BTC para mineradores e 0.00100000 BTC de taxas adicionais, não este um BUG do programa ja que deveria ser gratuito?
![TAXA ADICIONAL](https://user-images.githubusercontent.com/32179078/70996864-76f11500-20b2-11ea-95a8-cb12ce81bbe4.JPG)

**Comment by SomberNight** [comment]
This is because you are using a 2FA wallet. That 0.001 BTC is an extra fee for the 2FA server to cosign your transactions. It is prepayment for your next 20 transactions.
See https://api.trustedcoin.com/#/electrum-help
