### ISSUE TITLE
Signing transaction with OP_RETURN with ledger nano S fails

### ISSUE THREAD

**Issue by toxonaut** [spesmilo/electrum#5849]
As shown below I am trying to sign a transaction with an OP_RETURN in the Pay to field. The signing request never reaches the Ledger and after a while the empty popup appears (screenshot 2). 
![image](https://user-images.githubusercontent.com/6582883/71013448-00273c80-20f1-11ea-8fc7-d97b3bfa4ae0.png)
![image](https://user-images.githubusercontent.com/6582883/71013469-07e6e100-20f1-11ea-98f9-78743d63e799.png)

**Comment by SomberNight** [comment]
Sending to OP_RETURN with Ledger was not implemented before.
The error dialog is due to a failing assertion that checks that all outputs are addresses.
It should now work on master.

**Comment by toxonaut** [comment]
Many thanks. Tested it and it works now.
