### ISSUE TITLE
Electrum wallet doesn't send BTC

### ISSUE THREAD

**Issue by Ernesto891** [spesmilo/electrum#5851]
Good evening my Electrum wallet doesn't let me send BTC on another wallet. This is the following error: The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

Unknown error

**Comment by SomberNight** [comment]
What version of Electrum are you using?
Have you tried what the message suggests; i.e. choosing a different server, or updating Electrum if you are not on latest?

**Comment by Ernesto891** [comment]
i got the latest version, the 3.3.8.. Yes i tried to change the server but give anither error. What should i do?

**Comment by SomberNight** [comment]
What is the actual message the server is sending?
You can see it in the [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging).
As the log line will also tell you, do not trust the message you see there, it's arbitrary text;
just copy it here please.

**Comment by Ernesto891** [comment]
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

Transaction could not be broadcast due to dust outputs.
This is the message of error of the other server.

**Comment by SomberNight** [comment]
See https://bitcoinelectrum.com/frequently-asked-questions/#why-am-i-getting-the-error-message-dust-outputs

**Comment by Ernesto891** [comment]
Ok. Problem solved. Thank you so much.

**Comment by battleb2014** [comment]
Currently having the same issue.  I'm up to date with 4.0.9, trying to send 2.8mBTC.  I've had to selected every server multiple times at this point, and set the fee to max.

**Comment by battleb2014** [comment]
Error is about dust output

**Comment by SomberNight** [comment]
@battleb2014 so are you also seeing `Transaction could not be broadcast due to dust outputs` this error message?
That suggests some of the outputs are really small; less than 1000 sat.

Maybe share the raw transaction hex, or screenshot of transaction dialog (with tx outputs visible).

**Comment by battleb2014** [comment]
transaction hex?

**Comment by SomberNight** [comment]
In Send tab, fill in form, then click `Pay...`, then click `Advanced`, then click `Finalize`, click `Sign`,
then `Export`>`Copy to clipboard`.

**Comment by battleb2014** [comment]
02000000000101b5bb20463ca6202e65aec3b0b294304433cc2ca32b5a240edcfa3405eec6cda20100000000fdffffff02dc000000000000001976a914a4ebaf0d80cb408149161dfbf2d55118aab0506b88aca8f4030000000000160014d78199f83f834136b12084b7b9acad371f82c5920247304402206c1d73d889c110464fd7e1558790a9ff77bc996c86796920c921e7d7130452b602207c57650a0415fda535bacc73a8b5af02d9b6867d76220d2882abc8abfa489d0a012102dedb9a66b916f3ddf6eba3c2f9b0cc17cb628f9418c259a1250d4b44e2b3c7240d3f0a00

**Comment by SomberNight** [comment]
@battleb2014 Output 0 is 0.0000022 BTC (i.e. 220 sat). That is too small; it is dust

**Comment by battleb2014** [comment]
I forgot it was in mBTC.  Jeeezzz
