### ISSUE TITLE
Can't build AppImage

### ISSUE THREAD

**Issue by advius** [spesmilo/electrum#5855]
After successful build of docker image I tried to build AppImage using:

```
sudo docker run -it \
    --name electrum-appimage-builder-cont \
    -v $PWD:/home/user/electrum-3.3.8 \
    --rm \
    --workdir /home/user/electrum/contrib/build-linux/appimage \
    electrum-appimage-builder-img \
    ./build.sh

```

but docker said:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"./build.sh\": stat ./build.sh: no such file or directory": unkown.

OS:
Ubuntu 18.04

Docker version:
19.03.5

**Comment by SomberNight** [comment]
The [command in the README](https://github.com/spesmilo/electrum/tree/5f4162deaa20c5415ebee3844a28575c08275a21/contrib/build-linux/appimage) is:
```
$ sudo docker run -it \
    --name electrum-appimage-builder-cont \
    -v $PWD:/opt/electrum \
    --rm \
    --workdir /opt/electrum/contrib/build-linux/appimage \
    electrum-appimage-builder-img \
    ./build.sh
```
You have changed the paths, and that is why it failing for you.
The paths are inside the container, not on the host system, so there is absolutely no reason to change them.

**Comment by advius** [comment]
Thank you for help,

but after running 
```
$ sudo docker run -it \
    --name electrum-appimage-builder-cont \
    -v $PWD:/opt/electrum \
    --rm \
    --workdir /opt/electrum/contrib/build-linux/appimage \
    electrum-appimage-builder-img \
    ./build.sh
```
there is a error message 

> fatal: Not a git repository (or any parent up to mount point /opt/electrum)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
