### ISSUE TITLE
Revealer plugin no longer allows generating revealer image from revealer hex code

### ISSUE THREAD

**Issue by Engelberg** [spesmilo/electrum#5857]
Back in 3.2.2, the revealer plugin dialog asked you to either create a new revealer or enter a revealer's code. If you enter the code, it would then present you with the option to either generate the revealer pdf/png, or encrypt your seed.

Now in 3.3.8, the revealer plugin dialog still asks you to create a new revealer or enter a revealer's code. But when you enter the code, it only presents you with the option to encrypt a seed -- it does not allow you to re-generate the revealer.

This poses a signficant problem for those who have backed up the revealer code in the event that more instances of the transparency need to be generated.

**Comment by tiagotrs** [comment]
will look to restore this function or add a option to do that under 'advanced option'. 
Immediately, as a workaround, you can type the hex code and 'encrypt a custom secret' consisting only of spaces. This will generate a image that is exactly the same as the Revealer from the Hex you entered.

**Comment by tiagotrs** [comment]
Actually, If you type the code and click on "create new revealer", it will create it for you.  @Engelberg

**Comment by Engelberg** [comment]
Thank you for the clarification. That gives me the information I need. The way the interface is structured, I had no idea that "create new revealer" would generate from the code rather than creating a totally new revealer. I'll leave it up to you whether to close this issue, or keep it open if you think the interface could use some clarification. Much appreciated.
