### ISSUE TITLE
create a PSBT offline but can't be identified by electurn wallet 3.3.8

### ISSUE THREAD

**Issue by jiangjinyuan** [spesmilo/electrum#5862]
Hi, 
I create a PSBT where inputs and outputs are provided but without an unsigned tx  , and when I load the unsigned transaction  to the electrum wallet 3.3.8, it returns a error:
"Electrum was unable to deserialize the transaction: unpack_from requires a buffer of at least 4 bytes"

My PSBT is 70736274ff000100fda5010100000000010289a3c71eab4d20e0371bbba4cc698fa295c9463afa2e397f8533ccb62f9567e50100000017160014be18d152a9b012039daf3da7de4f53349eecb985ffffffff86f8aa43a71dff1448893a530a7237ef6b4608bbb2dd2d0171e63aec6a4890b40100000017160014fe3e9ef1a745e974d902c4355943abcb34bd5353ffffffff0200c2eb0b000000001976a91485cff1097fd9e008bb34af709c62197b38978a4888ac72fef84e2c00000017a914339725ba21efd62ac753a9bcd067d6c7a6a39d05870247304402202712be22e0270f394f568311dc7ca9a68970b8025fdd3b240229f07f8a5f3a240220018b38d7dcd314e734c9276bd6fb40f673325bc4baa144c800d2f2f02db2765c012103d2e15674941bad4a996372cb87e1856d3652606d98562fe39c5e9e7e413f210502483045022100d12b852d85dcd961d2f5f4ab660654df6eedcc794c0c33ce5cc309ffb5fce58d022067338a8e0e1725c197fb1a88af59f51e44e4255b20167c8684031c05d1f2592a01210223b72beef0965d10be0778efecd61fcac6f79a4ea169393380734464f84f2ab30000000000

And I found the unsigned transaction created by electrum is like this:
{
    "hex": "45505446ff0002000000000101f91daa9e219dde5f771ff131aae81c5245a7a8873480ebe83cbd111f9d311df0240000001dff001afd76a914c7f4d5b8c3a01858667118b158343b7e80fd37bd88acfdffffff01aa013501000000001976a914a2967f83f90a66eacf3fd87f55a1c9b81783d70888acfeffffffff24043501000000000000002d4d0900",
    "complete": false,
    "final": false
}

I guess the format of PSBT of electrum is different to others.
I don't know why it happen, please help me!

**Comment by SomberNight** [comment]
3.3.8 does not have PSBT support (well, there is some very limited support, when using a ColdCard hw wallet).
You need to use git master for now if you need PSBT support.
