### ISSUE TITLE
Dumb Question for experienced devs regarding Electrum UX 

### ISSUE THREAD

**Issue by johncodesit** [spesmilo/electrum#5874]
Hi!
I'm having some problems with my windows 10 PC. 
I need to perform a system restore, meaning that I'll be forced to uninstall my Electrum wallet in the process. Will I loose my Bitcoins if I do this? 
Is there a way to make a 'backup' and keep them somehow? 
I'm using the latests version of the wallet. 
Any advice would be awesome, 
Thanks in advance !

**Comment by SomberNight** [comment]
See https://bitcoinelectrum.com/how-to-backup-your-electrum-wallet/

It should be enough to backup your seed words.
As with all backups, it's prudent to test them; i.e. you can try restoring while you still have your current install.
