### ISSUE TITLE
Make the copy outpoint feature relevant again

### ISSUE THREAD

**Issue by bilthon** [spesmilo/electrum#5878]
This is actually something that was present in v3.3.8 of Electrum, but which I can see has changed on 4.0.0. The feature itself has to do with the copy to clipboard of outpoint data in the "coins" section.

UTXOs in the "coins" section are displayed in an abbreviated form, for instance:

> 9269f2c6a8c04bb5...:1

And that's still true for 4.0.0 and I agree that it is the right thing to do. However it used to be that when one right-clicked a specific outpoint and selected the "copy" option, the full data "txid:index" (without the shortening & ellipsis) ended up in the clipboard. What I see now after compiling 4.0.0 (at commit 29cf01524a286b3a6c884a6a05df12a8b759c12f) is that the clipboard data is also the abbreviated version.

I am experimenting with a side-project that would greatly benefit if the actual data being copied to clipboard is the full outpoint and not the abbreviated version, which is kind of useless if you come to think about it. The reasoning here is that if you went ahead and selected a specific outpoint and "copied" it to clipboard, you're likely interested in its full content, not just the abbreviated version.

I'm not that familiar with the codebase, but was able to narrow down the file at `gui/qt/utxo_list.py` as the potential modification target.

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/pull/5879
