### ISSUE TITLE
Notify never stop to send notification (same status, null included) even after confirmation

### ISSUE THREAD

**Issue by IronGiu** [spesmilo/electrum#5881]
Hello, i'm testing notify command for a project, i want to use it for each generated payment request, and thats work "fine", the problem is that electrum never stop to send notification of each address, even empty address (send null notification) the problem is that more address i have in noitfication, more electrum going to flood my server... i have 1 question and a fix suggestion:

Question: There are any way to "unsubscribe" from an address notification? i tried to update notify of a specific address with false instead of url and even with an empty url (empty comma '') but without success, that say "true" but keep notify the url given in the first subscription... (just tested that by stopping the daemon all the notification will be erased, not a problem, but is better to keep notification in memory, like the requests, and add a command to cancel notification for specific address)

Suggestion: do not notify if no status change is present (or if transaction is confirmed, for sure not on null status!), in fact i receive the same notification every time, with the exact same status:
{"address": "mqeooMcc8jz7ME2J3anzYnyDShfTCz6Z33", "status": "474baa5803d9447c43a42c8719530bbc16214482be2887c0518e7256488f9108"} (is a testnet address)

I have another little suggestion, maybe adding at least the txid in "plain format" to the post notification, just to avoid multiple rpc call if i want check that address after notification received.

Details of test:
Os: Centos 7
Python version: 3.6.6
Electrum Version: 3.3.7 (daemon mode with rpc)

**Comment by theborakompanioni** [comment]
Sorry for bringing this up again, but I found no other related issue or question. Is there a way to "undo" the "notify" command.. like unsubscribing from the notifications in order for electrum to stop making http post callbacks?

Use case is:
- User gets an address and has a certain amount of time to make the transaction
- Server url is registered with electrum via "notify <address> <callback_url>
- After user made the transaction and a hook is received -> "unsubscribe" from the notification
  or
  Timelimit has been reached -> "unsubscribe" from the notification

Currently the only way is to just ignore the notifications if address changes afterwards?
Would it be possible to be in control of all the requests electrum can/will make?
