### ISSUE TITLE
Gap Limit as a Merchant (Daemon mode)

### ISSUE THREAD

**Issue by timginn** [spesmilo/electrum#5882]
The scenario:
A merchant with a headless setup is running into issues with available wallets within the gap limit with electrum in daemon mode. Perhaps they've got lots of users or a particularly bored user who keeps refreshing a page many times constantly generating new wallet addresses before the expiry time kicks in.

The problem:
There isn't a simple way to do anything involving gap limits (at least as of 3.3.8) with a headless setup. Gap limit related functionality is not currently exposed to the CLI. For example:  wallet.min_acceptable_gap() or wallet.change_gap_limit(1000).

While a merchant can of course set the force option on addrequest, doing so leaves them without any easy way of restoring from seed because changing the gap limit isn't exposed to the CLI and the Qt console isn't headless. They can't easily do a typical workaround of say wallet.change_gap_limit(1000) when restoring from seed and would have to be more creative than should be necessary (e.g. digging into the code).

**Comment by SomberNight** [comment]
I think we could expose `wallet.min_acceptable_gap` and `wallet.change_gap_limit` to the CLI. Perhaps `change_gap_limit` could have a name that discourages casual users from using it without understanding what it does.

Related:
waxwing was asking a while ago about a setup where a user is doing standard cold signing but where the offline machine is CLI-only. So, online machine with watch-only wallet creates transaction (perhaps using Qt), offline machine is CLI-only and signs the tx.
This setup is already working and supported. However, careful users would want to give out receiving addresses from the offline (=trusted) machine, not the online one; or at least sometimes compare receiving addresses.
To do this, either something like `wallet.change_gap_limit` would be needed on the offline machine; or the user would need to call `createnewaddress` many times (in which case it would be nice if `createnewaddress` took an optional argument re number of addresses to create).
