### ISSUE TITLE
3.3.8 on windows crashes after scanning native segwit address QR code for spending

### ISSUE THREAD

**Issue by stefanwouldgo** [spesmilo/electrum#5883]
It worked once, now it just keeps crashing.

**Comment by SomberNight** [comment]
Hmm, I cannot reproduce so far.
Please [enable debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging), and see if there is something useful there.

**Comment by stefanwouldgo** [comment]
I can't find anything useful in the logs. However, electrum generates report.wer files when crashing. Would these be of interest?

**Comment by SomberNight** [comment]
So I guess the it's a hard crash, there is no python exception or similar.
Do you get "the application is not responding"?

> It worked once, now it just keeps crashing.

Does it work once every time you start Electrum; or do you mean that it only ever worked once?
When exactly does it crash (what do you click just prior etc)?

**Comment by stefanwouldgo** [comment]
> Do you get "the application is not responding"?

No, it just closes the app.

> Does it work once every time you start Electrum; or do you mean that it only ever worked once?

No, it just worked exactly one time after I upgraded Electrum to 3.3.8. Since I have closed and reopened the program, it reliably crashes.

> When exactly does it crash (what do you click just prior etc)?

I just click on the send tab, and then on the camera icon. The camera window appears, I scan a QR code (from Phoenix wallet), and it crashes. Every time.

**Comment by SomberNight** [comment]
Is this still applicable? Could you test using latest Electrum?

**Comment by stefanwouldgo** [comment]
I just tried it with Electrum 4.0.9 (on Windows) with QR codes from both Samourai wallet and Phoenix. They both seem to work now. 

Maybe it's of interest that the address was decoded in UPPERCASE for Samourai and lowercase for Phoenix.
