### ISSUE TITLE
Problem connecting to electrs on Windows

### ISSUE THREAD

**Issue by MrR-rrr** [spesmilo/electrum#5884]
I'm running a full node+electrs on rpi4 in my local network (using the raspibolt guide: https://stadicus.github.io/RaspiBolt/)

On my windows machine, when I connect to my node using:  
"C:\Program Files (x86)\Electrum\electrum-3.3.8.exe" --oneserver --server 192.168.0.20:50002:s

electrum doesn't connect to electrs (I get a no network indicator in the lower right corner)

On the same machine (through a linux vm) running:
~/electrum/electrum-3.3.8-x86_64.AppImage --oneserver --server 192.168.0.20:50002:s

electrum connects just fine...

Before running an electrs I ran electrum personal server on the rpi and had no issue connecting to it.

Anyone encountered such an issue?

**Comment by SomberNight** [comment]
Check [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging).

**Comment by MrR-rrr** [comment]
The Logs are below, seems to be an SSL certificate issue...

20200111T073941.726336Z |     INFO | interface.[192.168.0.20:50002] | disconnecting due to: ConnectError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)
20200111T073941.726336Z |     INFO | network | couldn't launch iface 192.168.0.20:50002:s -- CancelledError()
20200111T073941.796421Z |     INFO | interface.[E-X.not.fyi:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20200111T073941.796421Z |     INFO | network | couldn't launch iface E-X.not.fyi:50002:s -- CancelledError()
20200111T073941.826421Z |     INFO | interface.[btc.cihar.com:50002] | disconnecting due to: ConnectError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None),)
20200111T073941.836514Z |     INFO | network | couldn't launch iface btc.cihar.com:50002:s -- CancelledError()
20200111T073941.866348Z |     INFO | interface.[ndnd.selfhost.eu:50002] | disconnecting due to: ConnectError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None),)
20200111T073941.866348Z |     INFO | network | couldn't launch iface ndnd.selfhost.eu:50002:s -- CancelledError()
20200111T073942.026322Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.5196
20200111T073942.026322Z |     INFO | interface.[bitcoin.corgi.party:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20200111T073942.026322Z |     INFO | network | couldn't launch iface bitcoin.corgi.party:50002:s -- CancelledError()

looking up the error it seems there is a missing certifill python lib

**Comment by SomberNight** [comment]
Try deleting the pinned certificate in `%appdata%/Electrum/certs` for your hostname.

**Comment by MrR-rrr** [comment]
Yeah, that worked!

I saw it was created a while ago, probably when I was running eps...

Can Electrum detect such an issue automatically and delete the cert by itself?

Anyway, Thank you for your help!
