### ISSUE TITLE
python3-pyqt5 : Depends: qtbase-abi-5-2-1

### ISSUE THREAD

**Issue by Tectract** [spesmilo/electrum#5886]
unable to install on Linux Mint 17 because of package dependency issues with qtbase.

Upgrading to a newer version of Mint/Ubuntu is not an option, as we are specifically NOT going past 14.04, to avoid systemd.

    sudo apt-get install python3-pyqt5

The following packages have unmet dependencies:
 python3-pyqt5 : Depends: qtbase-abi-5-2-1

**Comment by SomberNight** [comment]
Maybe try installing pyqt5 from pip.
I think that bundles Qt.
`python3 -m pip install pyqt5`

**Comment by Tectract** [comment]
https://launchpad.net/~jonathonf/+archive/ubuntu/python-3.6

> This PPA has been removed from public access as part of a protest against the abuse of open-source projects by large companies. For more detail visit the main page here: https://launchpad.net/~jonathonf

oh jesus, lol. Still working on python 3.6.

Is there some reason my old electrum 2.6 is no longer syncing? It says "downloading block headers" but the block number never goes up :'(

**Comment by Tectract** [comment]
> https://joshspicer.com/python37-ssl-issue

Python 3.6/3.7 are incompatible with TLS on ubuntu, meaning you can't install pip by default. 

I'm falling down a code rabbit-hole

**Comment by SomberNight** [comment]
Try the AppImage maybe?

**Comment by Tectract** [comment]
Ok, I got it installed with python3.6. Had to link lebsecp256k1.so.0 into /usr/lib.

Now I'm seeing this. Yikes, hmmmmmm.

python3.6: relocation error: /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference

**Comment by Tectract** [comment]
hmmmm where is libdbus1.so.3....

**Comment by SomberNight** [comment]
(related: https://github.com/spesmilo/electrum/issues/5887)

As in other issue, this seems to be a dependency issue with Qt itself; at best tangentially related to Electrum.
Not sure how to help, sorry.
