### ISSUE TITLE
python3.6: relocation error

### ISSUE THREAD

**Issue by Tectract** [spesmilo/electrum#5887]
Linux Mint 17 / Ubuntu 14.04

run fails:

python3.6: relocation error: /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization, version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference

Updating OS is not an option, as we are locked to 14.04 because of the "systemd avalanche".

Help?

**Comment by Tectract** [comment]
relevant maybe

https://www.reddit.com/r/Cplusplus/comments/9i3hoi/set_up_qt_on_linux_and_im_having_issues/

**Comment by Tectract** [comment]
I ended up just using the appimage. fuck it, too hard to build on 14.04 any more.

**Comment by SomberNight** [comment]
This seems like to be a dependency issue with Qt itself; at best tangentially related to Electrum.
Not sure how to help, sorry.
