### ISSUE TITLE
How to generate new receiving address on electrum cli 3.3.4?

### ISSUE THREAD

**Issue by anonproject** [spesmilo/electrum#5891]
Apparently the wallet should have a gap limit and generate new unused addresses if there is less than a gap_limit unused addresses at the end of the list.
So I got an address via list_addresses | jq .[-1], made a transfer to it.  And I still see the same address on the top of the list (that is, 
no new addresses were generated). I do not understand how to generate new receving addresses via cli.

**Comment by anonproject** [comment]
Ha.  I loaded the wallet today and see exactly six new addresses added.
That is interesting because yesterday right after I made a transfer to the last address I haven't seen any new addresses added.  I haven't seen them after the transaction was conformed and after I closed the wallet, killed a daemon, started a daemon and open the wallet.   But I seem them now.

It is very unfortunate anyways that electrum doesn't seem to provide commands to generate the addresses manually.

**Comment by SomberNight** [comment]
> It is very unfortunate anyways that electrum doesn't seem to provide commands to generate the addresses manually.

https://github.com/spesmilo/electrum/blob/e65ce96f9d9080fcb46fedf3400007a6cd73abfc/electrum/commands.py#L785

>  So I got an address via list_addresses | jq .[-1], made a transfer to it. And I still see the same address on the top of the list (that is, no new addresses were generated). I do not understand how to generate new receving addresses via cli.
Ha. I loaded the wallet today and see exactly six new addresses added.

For gap limit purposes, an address is considered used after it has a tx that has at least 3 confirmations.
