### ISSUE TITLE
Electrum have update themselve and stole my money.

### ISSUE THREAD

**Issue by gerodoth** [spesmilo/electrum#5893]
my old electrum, which I had not touched for a long time, suggested that I update it, and after the update, through its own mechanism, it stole all my money.
here is details:
https://bitcointalk.org/index.php?topic=5218655.new#new

**Comment by SomberNight** [comment]
Based on the information in the bitcointalk thread, you have been a victim of phishing through https://github.com/spesmilo/electrum/issues/4968.
I am sorry but in this case the coins are lost.

If the amount of coins lost is non-negligible, consider reporting the theft to your local police department, and notify us (electrumdev@gmail.com).
We have reported the phishing to German law enforcement, and we forward user reports to them. You may send us your identity, the transaction ID of the theft, in which jurisdiction you contacted the police, and any other information you find relevant.
(This is all optional on your part of course)

**Comment by gerodoth** [comment]
russian police will try best to refuse me cause they don't know how to solve this kind of probles, so looks like ticket may be closed.
