### ISSUE TITLE
An Unconfirmed payment sent after moved to windows 

### ISSUE THREAD

**Issue by gribka** [spesmilo/electrum#5894]
I was using electrum on Tails, where I sent a payment that stayed unconfirmed for over a month after multiple attempts of receiving the bitcoin back I moved electrum on to windows. On windows, the unconfirmed payment became confirmed and sent to the intended address OVER A MONTH LATER. 
I am unable to do anything about it. The transaction was about 200 USD or 22 mBTC. 
I am unable to find any cause to this problem and am afraid the money is gone forever, I herd that unconfirmed payments return in 14 days but that was not the case for me and instead, it just confirmed a month later.
Are there any ways of receiving my funds back? as it was supposed to expire but didn't...

**Comment by ecdsa** [comment]
no, unconfirmed payments do not "return in 14 days"
you, or someone else, may have rebroadcast your transaction.
