### ISSUE TITLE
2FA timeout

### ISSUE THREAD

**Issue by dagaubj** [spesmilo/electrum#5895]
I want to send bitcoins out of Electrum. Because of there are a lot trivial coins, 2FA fails to package too many imputs. Each time it shows time out even if I transfer 1btc. Please help me to resolve the issue.

**Comment by SomberNight** [comment]
You are using Electrum 3.3.8, right?
How many inputs does the tx have that is timing out?
As a workaround, have you tried with fewer inputs?

**Comment by SomberNight** [comment]
closing, no response
