### ISSUE TITLE
Didnt recive the money

### ISSUE THREAD

**Issue by NicolasderFicker** [spesmilo/electrum#5897]
Hey i was at an Bitcoin ATM and i used the QR code to put Money on my Account... that was 3 weeks ago and i still dont have my money

**Comment by SomberNight** [comment]
Check the address you have given to the ATM on a block explorer (e.g. https://blockstream.info/ )

If there is no transaction there, you should contact the ATM operator.
If there is one, we can continue investigating here: maybe you are just not connected to any server, or have the wrong wallet open, etc.

**Comment by SomberNight** [comment]
stale
