### ISSUE TITLE
Update Check Failed

### ISSUE THREAD

**Issue by nc50lc** [spesmilo/electrum#5899]
**Version(s)**: 3.3.8 / 3.3.7 Stand-alone and Installer
**OS**: Windows10

Someone reported in [Bitcointalk](https://bitcointalk.org/index.php?topic=5219166.0) that he's been unable to check for updates using the "_Check for updates_" button in the 'Help' toolbar.
I've tried it myself using two versions and both seem unable to connect to the update server **but**,
directly visiting: [electrum.org/version](https://electrum.org/version) through the browser works fine.

I think it has something to do with the authentication or something in between the client and the server.

**Comment by SomberNight** [comment]
Please [enable debug logging](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging) and check the logs.

**Comment by nc50lc** [comment]
>20200122T024954.233014Z |     INFO | interface.[81-7-10-251.blue.kundencontroller.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(TimeoutError(10060, "Connect call failed ('81.7.10.251', 50002)"),),)
20200122T024954.236016Z |     INFO | network | couldn't launch iface 81-7-10-251.blue.kundencontroller.de:50002:s -- CancelledError()
**20200122T024959.788405Z |     INFO | gui.qt.update_checker.UpdateCheckThread | got exception: 'TimeoutError()'**
20200122T025003.969108Z |     INFO | network | couldn't launch iface e.keff.org:50002:s -- TimeoutError()

Others have responded to the BCT thread and most aren't affected.
Looks like an ISP, network config or Router issue.

**Comment by SomberNight** [comment]
I believe the timeout is 30 seconds.
Can you confirm that it "takes" 30 seconds?

**Comment by nc50lc** [comment]
Yes, exactly 30 seconds.

I also tried disabling both Firewall and AV, still failed.

**Comment by SomberNight** [comment]
Try running this in the Console tab:
```
network.send_http_on_proxy("get", "https://electrum.org/version")
```
What output do you get?
(note that the whole application will freeze while the network operation is ongoing)

After that, maybe try e.g.:
```
network.send_http_on_proxy("get", "https://electrum.org/version", timeout=120)
```

**Comment by SomberNight** [comment]
Does this only happen for Windows users?

**Comment by nc50lc** [comment]
Results of the 30sec timeout:
> Traceback (most recent call last):
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 384, in __get_result
  File "electrum\network.py", line 1245, in _send_http_on_proxy
  File "site-packages\aiohttp\client.py", line 1005, in __aenter__
  File "site-packages\aiohttp\client.py", line 575, in _request
  File "site-packages\aiohttp\helpers.py", line 585, in __exit__
concurrent.futures._base.TimeoutError

Results of the 120sec timeout (_worked_):
> '{ "version":"3.3.8", "signatures":{ "13xjmVAB1EATPP8RshTE8S8sNwwSUM9p1P":"IJarYcaoMWHFzR+n8NoF9K4W7Vl/1JWh5MPs8ezH3QTqcI7ZrAb3+IHU2FuzQy0R9AM8jZDk3r/P7DNNqZ69iI4="}}\n'

The other user also uses W10, IDK the other one.

**Comment by nc50lc** [comment]
Even 45 sec worked, I guess increasing the timeout to 1 minute wouldn't be a problem?

**Comment by SomberNight** [comment]
The need for a long timeout might potentially be related to Windows DNS issues (https://github.com/spesmilo/electrum/issues/4421 and related)
