### ISSUE TITLE
Unable to open Electrum 3.3.8 in Windows10

### ISSUE THREAD

**Issue by MrAncap** [spesmilo/electrum#5901]
I can not open Electrum 3.3.8 on my Windows 10 anymore.

I uninstalled and installed Electrum again, many times, even deleting Appdata folders, but it not worked.

On Windows Task Manager I can see "Electrum 3.3.8" running on the background but the program never opens.

Even if I kill this task and try to open Electrum.exe again, the software never start.

I tried Windows Installer, Standalone executable and even old Electrum releases but nothing worked.

The Electrum log file wrote this error:
"INFO | daemon | failed to connect to JSON-RPC server: unexpected EOF while parsing (<unknown>, line 0)"

I used Electrum for many years, it never happened before.

What can be done in that cases?

**Comment by SomberNight** [comment]
> The Electrum log file wrote this error:
"INFO | daemon | failed to connect to JSON-RPC server: unexpected EOF while parsing (, line 0)"

Could you please paste/upload the whole log file?

> Windows 10

What version of Window 10 exactly? Check in `cmd`, for example.

> I can not open Electrum 3.3.8 on my Windows 10 anymore.
I used Electrum for many years, it never happened before.

When did it stop working? Any idea what you had done around that time that might be the cause?

**Comment by MrAncap** [comment]
Sure. Windows 10 Buid SO 18362.592

It happened this saturday, 18th January.

I didn't have done nothing different on my PC.

Entire Electrum log file:
"
20200121T145358.909724Z |     INFO | logging | Electrum version: 3.3.8 - https://electrum.org - https://github.com/spesmilo/electrum
20200121T145358.911718Z |     INFO | logging | Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]. On platform: Windows-10-10.0.18362
20200121T145358.912719Z |     INFO | logging | Logging to file: C:\Users\Mypersonallaptop\AppData\Roaming\Electrum\logs\electrum_log_20200121T145358Z_9560.log
20200121T145358.912719Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20200121T145358.914366Z |     INFO | daemon | failed to connect to JSON-RPC server: unexpected EOF while parsing (<unknown>, line 0)
20200121T145358.918345Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20200121T145358.921341Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20200121T145358.931311Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20200121T145358.934303Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20200121T145358.937294Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20200121T145358.940288Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20200121T145358.943280Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20200121T145358.946272Z |    DEBUG | util.profiler | Plugins.__init__ 0.0319
"

**Comment by SomberNight** [comment]
This might be the same issue as https://github.com/spesmilo/electrum/issues/5888

From https://github.com/spesmilo/electrum/issues/5888#issuecomment-575970021
> I tested every previous electrum version and anything above 3.1.0 crashes, 3.0.6 is fine.

Could you try, just for debugging purposes, whether 3.0.6 works for you?

**Comment by MrAncap** [comment]
I always installed the "Windows Installer" version of Electrum from the oficial website.  However I few weeks ago, I installed the "Standalone Executable". It worked fine until saturday.  I don´t know if that info can help, since I don´t have a clue of what could had cause that problem.

**Comment by MrAncap** [comment]
Ok. I uninstalled Electrum 3.3.8 and installed the 3.0.6 release.
The software oppened !! 
However when I select my wallet and put my correct password, Electrum issues an error "Failed to execute script electrum".

Nothing was write on the log file. The log file was not created.

![Electrum 306 error](https://user-images.githubusercontent.com/60143390/72817021-db6e3980-3c47-11ea-9c58-818902d3cb35.jpg)

**Comment by SomberNight** [comment]
> Nothing was write on the log file. The log file was not created.

Unfortunately logging to file was only implemented in 3.3.5.

> I uninstalled and installed Electrum again, many times, even deleting Appdata folders, but it not worked.
>  However when I select my wallet and put my correct password, Electrum issues an error "Failed to execute script electrum".

Can you try with a fresh datadir (e.g. rename `%appdata%/Electrum`)?

**Comment by MrAncap** [comment]
This time the OS does not allowed me to rename the directory (it said it was in use, but Electrum was closed).
So I had to restart Windows 10.
I renamed the Electrum dir on Appdata as you told, but it not worked.
I get the same error.

**Comment by SomberNight** [comment]
So 3.0.6 starts (at least shows the wizard) but when you open the wallet it gives `Failed to execute script Electrum` error; and 3.3.8 does not even start at all?
What about 3.1.0?

If I built a custom binary for you, would you run that? (or can you build a Windows binary yourself from [instructions](https://github.com/spesmilo/electrum/blob/master/contrib/build-wine/README.md)?)

**Comment by MrAncap** [comment]
Yes, that´s right.
And I did not tried 3.1.0.
What is a custom binary?
Could you please tell me what the purpose of run a custom binary?  Is it safe?  Is it necessary to put my password on that custom binary?

**Comment by SomberNight** [comment]
>  And I did not tried 3.1.0.

Would you mind trying that version too?

>  What is a custom binary?
Could you please tell me what the purpose of run a custom binary? Is it safe? Is it necessary to put my password on that custom binary?

I was considering building a binary from git master (with latest development changes), and maybe some extra logging added, to see if I can figure out the root cause of the issue.
You would not need to enter your real wallet details into this (e.g. fresh appdata folder, and create new throwaway wallet).
Unless you are comfortable with this, let's no do it.

**Comment by MrAncap** [comment]
Ok. I tried Electrum 3.1.0 using a fresh new dir on Appdata.

The software opened, I selected my wallet, put my password , and after that Electrum just gone. The software closed itself without any error message. 

If that custom binary can solve the problem so we can do it.

I looked to the instructions on the link you provided to build a custom binary. The steps seems to be applied for Linux O.S. or to programmers. Do I need a specific software to do that or it can be done using Windows CMD or other native windows software?

**Comment by SomberNight** [comment]
> Ok. I tried Electrum 3.1.0 using a fresh new dir on Appdata.
The software opened, I selected my wallet, put my password , and after that Electrum just gone. The software closed itself without any error message.

If you tried with a fresh dir, it should not have your wallet either, so it could not ask for your password.
Or do you mean you browsed for your wallet file which was in some other directory?

> If that custom binary can solve the problem so we can do it.
I looked to the instructions on the link you provided to build a custom binary. The steps seems to be applied for Linux O.S. or to programmers. Do I need a specific software to do that or it can be done using Windows CMD or other native windows software?

Yes, the instructions are for programmers/technical people, and it requires Linux.
I am just trying to figure out why the issue occurs, not suggesting this as a fix itself.
I could build the binary for you, but you would basically have to trust me not to do anything malicious.

**Comment by MrAncap** [comment]
Yes, I browsed it selecting the wallet in the other directory renamed.

Ok, now I understand better this custom binary matter.
I know it´s more comfortable to you, but unfortunately I can not do that.

There should be another way to solve this.

**Comment by Transisto** [comment]
@MrAncap  I ran it in Sandboxie with network disabled, also the build is reproducable, check out https://github.com/spesmilo/electrum/issues/5888#issuecomment-577284849

**Comment by MrAncap** [comment]
Hello. I updated to Electrum 4.0.2 lastest version, and it worked now!

I updated Window 10 too, build OS 19041.423 - Wnidows 10 Home.

It was a scare to be unable to open and use Electrum wallet on the notebook with Windows 10.  But now everything is working fine.

Thank you.

**Comment by SomberNight** [comment]
Great; thank you for confirming it works.
