### ISSUE TITLE
Cannot Access Funds

### ISSUE THREAD

**Issue by Olizoo** [spesmilo/electrum#5904]
I have funds in my wallet but I cannot access them because it says they are 'Unconfirmed'

My version is 3.8.8

I have tried to update to the latest version but apparently I already have that so I dont know what else to try ?

Can anyone help please ?

**Comment by ecdsa** [comment]
funds are unconfirmed until the transaction is in a block.
this issue is not specific to Electrum, it is just how Bitcoin works.
