### ISSUE TITLE
Feature request: disable auto-broadcast after signing

### ISSUE THREAD

**Issue by jrimbolt** [spesmilo/electrum#5907]
**Describe the feature request**
Give users the option to disable auto-broadcasting.

It would benefit the likelihood of user error if it would be possible to verify the transaction information manually after clicking "send" and "sign", before broadcasting. This is not intended as a protection against malware attacks, but to allow users to triple-check that the address(es) being sent to are the correct ones. The hope is this will prevent users from sending bitcoin to the wrong address.

**Desired behavior**
If auto-broadcasting is disabled, after signing a transaction with a hardware wallet: bring up the transaction overview panel where all inputs and outputs are displayed and allows users to manually verify (yet again) that all receiving addresses are correct and click "broadcast" manually.

Disabling auto-broadcasting means **always** manually clicking "broadcast", even after having clicked "send" and "sign".

This way, the user can check receiving address(es) are correct three times:

- Upon entering the recipient address
- Upon signing the transaction on a hardware wallet
- Before broadcasting

**Comment by relativisticelectron** [comment]
The current (master) flow already supports exactly that you describe:

First click advanced:
![Screenshot_20200202_063113](https://user-images.githubusercontent.com/60378539/73603639-d2edfb00-4585-11ea-844a-a702aff6ecb6.png)

Then you have to press Finalize --> Sign --> Broadcast
![Screenshot_20200202_063209](https://user-images.githubusercontent.com/60378539/73603644-ec8f4280-4585-11ea-8537-c141c949d7a4.png)

**Comment by jrimbolt** [comment]
So this will be released with 4.0?

**Comment by jrimbolt** [comment]
Thank you! 

There is still something to be said for disabling broadcast-after-sign by default. New users might be unaware such alternative flows exist and are likely to just click Send. The option to disable auto-broadcasting in settings could decrease the likelihood of error for new users if disabled by default. It would allow users to enable auto-broadcasting when they are comfortable with it.

However, this solves my issue so this can be closed.

**Comment by ecdsa** [comment]
the option exists in settings, it is called 'advanced preview'

**Comment by jrimbolt** [comment]
> the option exists in settings, it is called 'advanced preview'

As of 4.0? Can't find it in 3.3.8.

**Comment by ecdsa** [comment]
yes, as of 4.0
please do not post issues regarding the interface of 3.3.8, it is wasting our time.
