### ISSUE TITLE
Not connected

### ISSUE THREAD

**Issue by TanjaNY** [spesmilo/electrum#5915]
After updates and installations NOT CONNECTED 
<img width="422" alt="not connected" src="https://user-images.githubusercontent.com/32233040/73268987-3bcb2100-41dc-11ea-91c0-64f64c362ceb.png">

**Comment by ecdsa** [comment]
nothing useful here.

**Comment by SomberNight** [comment]
Check the [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging) for potentially more info.
