### ISSUE TITLE
jsonrpc wallet_load has no effect

### ISSUE THREAD

**Issue by swtrse** [spesmilo/electrum#5919]
when trying to load a wallet from a custom location and then call getbalance the error "wallet not loaded" appear.

OS: Windows 10
Electrum Version: 4.0.0a0

Steps to reproduce:
Compile Electrum for Windows
Load electrum in daemon mode with custom data directory (in my case the directory is located in the same folder as the exe file.

Run curl with
curl --data-binary "{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"load_wallet\",\"params\":{\"wallet_path\":\"data\\wallets\\01_first_wallet\",\"password\":\"supersecretPassword\"}}" http://xxx:xxx@127.0.0.1:12345
The call returns:
{"jsonrpc": "2.0", "result": true, "id": 1}

After that run
curl --data-binary {\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getbalance\",\"params\":[]} http://xxx:xxx@127.0.0.1:12345
The call returns:
{"jsonrpc": "2.0", "error": {"code": -32000, "message": "wallet not loaded"}, "id": 1}

Other observations
A call of getinfo
returns a default_wallet of "data\wallets\default_wallet". That wallet does not exists since it is never created.

**Comment by ecdsa** [comment]
if you load a wallet with a nondefault path, you must pass the path to all commands, including `getbalance`
