### ISSUE TITLE
Kivy: Creating a wallet with "I already have a seed"  has a prefilled seed

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#5925]
Why is there a is_test behavior in https://github.com/spesmilo/electrum/blob/master/electrum/gui/kivy/uix/dialogs/installwizard.py#L864  ?
This might be convenient for testing, but the behavior on all platforms (no matter the ui) should be as identical as possible.

**Comment by relativisticelectron** [comment]
Would everyone be ok to remove this: https://github.com/relativisticelectron/electrum/commit/31a5ace2c9d3d18b44c0d16773b7bd284ed0c861

**Comment by ecdsa** [comment]
as the name says, this is for testing

**Comment by relativisticelectron** [comment]
I don't think it is a good idea to create varying behavior for different platforms. E.g. It makes testing the behavior a little bit more complicated , i.e. one needs to know that some elements have different behavior.
