### ISSUE TITLE
UX Improvement - Receive Tab - Please comment

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#5929]
I noticed the following post describing the "turning red" of the receive address after receiving: https://www.reddit.com/r/Electrum/comments/evadps/help_pleaseeeee_i_think_i_lost_money_a_lot/

If I put myself in the shoes of a beginner I have currently the following workflow: 

> Tab Receive --> Copy Address --> Put somewhere else and send -->  **The address turns red = bad**  --> Click button "New"  (Why should I click "New"? Did the old address turn bad somehow?)

![Screenshot_20200202_202622](https://user-images.githubusercontent.com/60378539/73613902-6e20b800-45fa-11ea-8487-ff855ae7cc8f.png)

I propose the following flow:

> Tab Receive --> Copy Address --> Put somewhere else and send -->  **A new receive address is created automatically** --> If an receive amount was entered, it is checked if all money arrived. **If all money arrived do nothing.**  If not all money arrived on the old address, the difference amount is prefilled and a message is presented to the user with "X BTC arrived of the requested Y BTC. You can receive on a new address the remaining Y-X BTC."

This flow has the following advantages:
- avoids address reuse just as effective
- If all amount is received, address field "turning red" and 1 click on the "New" button is removed --> Less information for the user to process
- If not all amount is received the user is notified.

**Do you think this should be improved? Do you have suggestions?**

**Comment by SomberNight** [comment]
Note that the Receive tab looks substantially different on master compared to 3.3.8.
Your picture suggests you have seen the new behaviour.

>  (Why should I click "New"? Did the old address turn bad somehow?)

The user is creating requests/invoices when clicking "New" (well, now called, "On-chain" and "Lightning").

With Lightning, each new incoming payment will require an invoice; and it would be nice if we could make the on-chain and the lightning "receive" flows highly similar. Please consider this before suggesting any changes.

**Comment by relativisticelectron** [comment]
> With Lightning, each new incoming payment will require an invoice; and it would be nice if we could make the on-chain and the lightning "receive" flows highly similar. Please consider this before suggesting any changes.

Ok. I agree the flow for LN and BTC invoices should be the similar.
