### ISSUE TITLE
RPC Json Result is double encoded for embedded objects.

### ISSUE THREAD

**Issue by swtrse** [spesmilo/electrum#5931]
This is a generalisation of #5868. I think this is a gerneral problem since I ran into this with an other command.
The problem is that embedded Objects are json encoded multible times twice and more.
For Example the Result of an onchain_history do look like somthing like this
{"id":1,result:"{\\n\"summary\":\"{\\\\n\\"balance\\":0.0}\""}
instead of
{"id":1,result:{\n"summary": {\n"balance":0.0}}
This is not the real result but it should give a good idea what the problem is.
As a result json encoder like newtonsoft can not deserialize the json string.

I would even consider the \n and \r and spaces that occur int the result json too much and they should also be eliminated.

**Comment by SomberNight** [comment]
> I think this is a gerneral problem since I ran into this with an other command

Which other command? Which commands besides `onchain_history` and `lightning_history` are affected?
