### ISSUE TITLE
Feature request: RBF on/off switch in the Send tab

### ISSUE THREAD

**Issue by uFire** [spesmilo/electrum#5938]
Most of the time I send payments with RBF enabled, but sometimes I need to make a transaction with RBF off, because some services accept unconfirmed payments instantly if it has no RBF flag. So I have to check everytime in the Electrum settings if it is enabled or not.

It would be useful to have a switch (or at least some indicator) right in the "Send" tab to change RBF state when creating a transaction.

I remember, that some time ago there were a checkbox for that but you have removed it.

**Comment by SomberNight** [comment]
On current master, if you click "Advanced" (which is the ~successor of "Preview"), you can toggle RBF. I believe that should be sufficient.

![tx_preview](https://user-images.githubusercontent.com/29142493/74095857-9161d080-4aee-11ea-98fe-2d8dbab5bf9f.PNG)

**Comment by uFire** [comment]
Sure, thats would be fine! 
I am on stable 3.3.8 (Windows) so I didn't saw it.
Thanks 👍
