### ISSUE TITLE
Max value on spend menu doesn't match balance

### ISSUE THREAD

**Issue by Kerelmeneer** [spesmilo/electrum#5940]
When I click on the Max button it doesn't show my actual value but a number significantly smaller, can't seem to use the rest of the coins either as the counter will turn red and when I try transferring it simply notifies me I don't have enough balance.
I've been using Electrum for 3 days now and all my transactions appear to be marked with a green checkmark, as well as my balance on the bottom of the client being correct. (I only have one wallet and have never transferred to another wallet due to this issue)
Client was verified with PGP as instructed on official website.
I don't see any other option than it being a bug, I have searched online for hours and haven't found anything quite like this issue.

**Comment by SomberNight** [comment]
- Is this a 2fa wallet?
- Have you considered the mining fee? Do you have many small value UTXOs?

**Comment by Kerelmeneer** [comment]
> * Is this a 2fa wallet?
Yes
> * Have you considered the mining fee? Do you have many small value UTXOs?
Yes, all of them are 3mBTC or less. They've all been confirmed and were made in the past 3 days.
The max mBTC the send menu displays isn't equal to any past transaction either, so I have no clue where this number comes from

**Comment by SomberNight** [comment]
You should use the "Preview" functionality to figure out exactly what is going on.
Check the tx size, the fee, the feerate, the outputs.

>> Is this a 2fa wallet?
>
> Yes

Note that there is a fee for using a 2fa wallet: https://api.trustedcoin.com/#/electrum-help
With default settings, it is 1 mBTC per every 20 transactions.

**Comment by Kerelmeneer** [comment]
> You should use the "Preview" functionality to figure out exactly what is going on.
> Check the tx size, the fee, the feerate, the outputs.
I have done all of these, nothing seems to indicate that I can't afford a transaction above the max prescribed to me
The preview seems to show my actual balance as well on the Inputs section
The fee of the transaction I'm trying to send (with no avail) is a fraction of my balance so it should be working fine

> Note that there is a fee for using a 2fa wallet: https://api.trustedcoin.com/#/electrum-help
> With default settings, it is 1 mBTC per every 20 transactions.
I'm well aware of this, I have even lowered the transfer rate to 1sat/byte with little results

The issue isn't the fees, it's the fact that my balance is twice the amount the send menu indicates

**Comment by Kerelmeneer** [comment]
Do I need to provide screenshots?

**Comment by SomberNight** [comment]
Yes, please, start preparing a tx that sends "max" to an address and then click "Preview", and show a screenshot of that window.
You can redact addresses/txids if you want.

**Comment by Kerelmeneer** [comment]
![2](https://user-images.githubusercontent.com/60856964/74111647-37184c80-4b8e-11ea-8d0a-e7d852ef98d3.png)
![1](https://user-images.githubusercontent.com/60856964/74111648-37b0e300-4b8e-11ea-879f-268f89e1d01e.png)

**Comment by Kerelmeneer** [comment]
I put in my own address to show you, the same happens with other addresses though.
As you can see the max is about half of my total balance.
I'm running the latest version, 3.3.8 in dark mode

**Comment by Kerelmeneer** [comment]
![3](https://user-images.githubusercontent.com/60856964/74111721-bb6acf80-4b8e-11ea-8577-b38d36c277a9.png)
Another one to prove my balance

**Comment by SomberNight** [comment]
There does not seem to be any inconsistency here.

The second output with the dark blue background with a value of 2.5 mBTC is the 2fa fee for the next 100 transactions, see link above.
You must have selected to prepay 100 txns instead of 20, hence the different amount than what I said previously. You can change this by clicking the shield icon in the bottom right.

If you did not realise that using a 2fa wallet has a cost, and would rather not use it in this case, then you can restore from your seed, select to disable 2fa, and send your coins out.

**Comment by Kerelmeneer** [comment]
thanks man, I really couldn't figure out that it was gonna charge me for 100 transactions at once as it wasn't notified anywhere
