### ISSUE TITLE
WATCH ONLY BUG

### ISSUE THREAD

**Issue by Ashyo153** [spesmilo/electrum#5941]
I am new to Bitcoin,
I made my first wallet with a extended passcode instead of the seed, and have no seed or Private key as neither were made. What do I do because that shouldn't be a possibility considering I've just searched for 5 hours trying to find a way around it. How can withdraw 80£ when neither key was created

**Comment by ecdsa** [comment]
you cannot withdraw from a watching-only wallet. it sounds like you created a watching only wallet with an extended pubkey (xpub), without knowing what you were doing. Did someone give you that extended pubkey ?
