### ISSUE TITLE
What's the meaning of 27 in the construct_sig65？

### ISSUE THREAD

**Issue by wheatli** [spesmilo/electrum#5942]
https://github.com/spesmilo/electrum/blob/master/electrum/ecc.py
`def construct_sig65(sig_string: bytes, recid: int, is_compressed: bool) -> bytes:
    comp = 4 if is_compressed else 0
    return bytes([27 + recid + comp]) + sig_string`

What's the meaning of magic number 27 in this function, why we need to add 27 when construct recovery id?

**Comment by SomberNight** [comment]
This is also what Bitcoin Core does.

https://github.com/bitcoin/bitcoin/blob/99813a9745fe10a58bedd7a4cb721faf14f907a4/src/key.cpp#L257
