### ISSUE TITLE
more than 6 months without a release

### ISSUE THREAD

**Issue by Gfloresechaiz** [spesmilo/electrum#5943]
Hi, 

I send my deepest gratitude towards the work being done on the Electrum Wallet. I would like to share one of my concerns : 

There hasn't been a release since July 2019 which is more than six months without a release. Electrum has a reputation of constant releases which makes it one of the most respected and used wallets on the market. 

I understand that adding Lightning was a big feature that has and still is being worked on but I was wondering when is a new release planned for? I believe there hasn't been an update on this situation for months

**Comment by ecdsa** [comment]
we are still working on the next version.
it will be released when it's done :-)
you can track our progress using github; there are new commits almost every day.
