### ISSUE TITLE
Create new Wallet with RPC Command and Wallet Path

### ISSUE THREAD

**Issue by MbrCoding** [spesmilo/electrum#5945]
Hi,

i'am looking for a RPC Command to create a new Wallet with a given Wallet Path. I saw that on the master branch the function is extended:

```
async def create(self, passphrase=None, password=None, encrypt_file=True, seed_type=None, wallet_path=None):
```

but in 3.8.8 it looks like this:
```
def create(self, passphrase=None, password=None, encrypt_file=True, segwit=False):
    d = create_new_wallet(path=self.config.get_wallet_path(),
```

So, is it possible to manipulate self.config with an RPC Command to create a Wallet with a given path?

Thanks

**Comment by SomberNight** [comment]
should work in both versions:
```
$ ./run_electrum create -w /some/path
```
Or are you trying to call `create` via JSON-RPC?

**Comment by marcelbraun1985** [comment]
Yes, that's the problem. I try it over RPC.

**Comment by ecdsa** [comment]
note that with the CLI, you need to run a daemon, or to pass `--offline` to the command

**Comment by SomberNight** [comment]
I think this worked already on master when OP asked, and since then there have been many releases from master, so should even work in newer releases now.
