### ISSUE TITLE
standard wallet incorrectly recognizes multisig input as ismine (if its pubkey is used as a cosigner)

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5948]
net:testnet 
1.I create two p2wpkh wallet  test_1 and test_2
2.I create multi-wallet with test_1_vpub and test_2_vpub(I change the vpub to Vpub)
3.I create a send transaction to a addr and export the tx info to a test_*.psbt
4.Into test_1 wallet and import test_*.psbt file and sign successful, export the signed tx into a signed_*.txn
5.Into test_2 wallet and import signed_*.txn file (Error occurred) 
    the error: the sign button not available 
This multisig is ok in version 3.3.8

**Comment by SomberNight** [comment]
Did this really work in 3.3.8? It does not work for me AFAICT.
Thanks for the bug report though, there is definitely an issue on master.

**Comment by SomberNight** [comment]
To sum up, you have two p2wpkh (standard) wallets, and created a 2of2 multisig wallet from their master public keys. You have then funded the multisig wallet, created an unsigned PSBT using it, and tried to sign this tx using one of the p2wpkh wallets. At this point the input was recognised as `is_mine` and the wallet was willing to sign.

Note that a potential change output going to the multisig wallet would also be recognised as `is_mine` by the p2wpkh wallet.

AFAICT this "feature" is not present in 3.3.8.
I think this was introduced in https://github.com/spesmilo/electrum/pull/5721.

In any case, this is a bug. The standard wallet should consider the tx as completely unrelated.

-----

The workflow you have tried is not how you should use a multisig wallet.
For a similar 2of2 case, cosigner1 would typically have a 2of2 wallet file with his seed/xprv + xpub of cosigner2, while cosigner2 would have the same but mirrored.

**Comment by shuaiLiWang** [comment]
In version 3.3.8,i do it like this:
1.I create two standard wallet test_1 and test_2
2.I create multi_wallet with test_1_xpub and test_2_xpub, then create a send tx and export to a file1
3.into test_1 wallet ,import file1 and sign and export new sign to file2
4.into test_2 wallet, import file2 and sign and broadcast 

but now i use this workflow(standard type),there is also an error at step 3, that is  when i create tx,i can not find the tx in send dialog, the invoices list not show

**Comment by shuaiLiWang** [comment]
Are there docments abount multi-sig

**Comment by SomberNight** [comment]
Well, there is a doc page: https://electrum.readthedocs.io/en/latest/multisig.html
However, as you can see from the pictures, it's unfortunately severely outdated. :/

**Comment by shuaiLiWang** [comment]
> To sum up, you have two p2wpkh (standard) wallets, and created a 2of2 multisig wallet from their master public keys. You have then funded the multisig wallet, created an unsigned PSBT using it, and tried to sign this tx using one of the p2wpkh wallets. At this point the input was recognised as `is_mine` and the wallet was willing to sign.
> 
> Note that a potential change output going to the multisig wallet would also be recognised as `is_mine` by the p2wpkh wallet.
> 
> AFAICT this "feature" is not present in 3.3.8.
> I think this was introduced in #5721.
> 
> In any case, this is a bug. The standard wallet should consider the tx as completely unrelated.
> 
> The workflow you have tried is not how you should use a multisig wallet.
> For a similar 2of2 case, cosigner1 would typically have a 2of2 wallet file with his seed/xprv + xpub of cosigner2, while cosigner2 would have the same but mirrored.

how to get the file (For a similar 2of2 case, cosigner1 would typically have a 2of2 wallet file with his seed/xprv + xpub of cosigner2)

**Comment by shuaiLiWang** [comment]
> To sum up, you have two p2wpkh (standard) wallets, and created a 2of2 multisig wallet from their master public keys. You have then funded the multisig wallet, created an unsigned PSBT using it, and tried to sign this tx using one of the p2wpkh wallets. At this point the input was recognised as is_mine and the wallet was willing to sign.
> Note that a potential change output going to the multisig wallet would also be recognised as is_mine by the p2wpkh wallet.
> AFAICT this "feature" is not present in 3.3.8.
> I think this was introduced in #5721.
> In any case, this is a bug. The standard wallet should consider the tx as completely unrelated.
> 
> The workflow you have tried is not how you should use a multisig wallet.
> For a similar 2of2 case, cosigner1 would typically have a 2of2 wallet file with his seed/xprv + xpub of cosigner2, while cosigner2 would have the same but mirrored.

1.I create test1 wallet with test1/seed+xpub with test2
2.I crete test2 wallet with test2/seed +xpub with test1
3.I create test3 wallet use the xpub with test1 and the xpub with test2
4.In test3 wallet, I create send tx and export to file test3_*.psbt
5.In test1 wallet, import test3_*.psbt file, but now  the sign button is unavailable, i do not know how to do next

**Comment by SomberNight** [comment]
> 1.I create test1 wallet with test1/seed+xpub with test2
2.I crete test2 wallet with test2/seed +xpub with test1

Where do you get the xpub? Are you still manually converting version bytes? You should use the xpub the wizard gives you.

**Comment by SomberNight** [comment]
Someone reported this again today, for 3.3.8, and I have managed to reproduce it.
The variant reported was:
- on online machine, create a 2of3 wallet ("online_wallet"): xpub1, xpub2, xpub3
- on offline machine, create a 2of2 wallet ("offline_wallet1"): xprv1, xpub2
- on offline machine, create a 2of2 wallet ("offline_wallet2"): xpub1, xprv2
- with online_wallet, create unsigned tx
- with offline_wallet1, load tx, sign it
- with offline_wallet2, load tx, sign it
- on online machine, broadcast tx

I want to emphasise that this behaviour was not intentional, and while it works in 3.3.8, it is not guaranteed to work, and in fact, this **already no longer works on master**.
