### ISSUE TITLE
"default-wallet" is unable to be deleted on Android

### ISSUE THREAD

**Issue by i6x** [spesmilo/electrum#5952]
I have two wallets on my device, one is named default-wallet and is not being used and the other is my main wallet named the name that I have given it. I wish to delete "default-wallet" however upon deleting it I am presented with the wallet creation screen which forces me to create a new wallet which I have no option to rename thus creating another default-wallet. This is also the wallet that I am presented with upon launching the application meaning that in order to access my actual wallet I have to go through additional steps and have to enter my PIN again.

**Comment by SomberNight** [comment]
Indeed, currently "there must always be a default_wallet" :)

> default-wallet. This is also the wallet that I am presented with upon launching the application 

If you exit the application via pressing the "back" button, it will save that wallet as last opened. From then on, the app will open to that one.

**Comment by i6x** [comment]
> If you exit the application via pressing the "back" button, it will save that wallet as last opened. From then on, the app will open to that one.

It doesn't do that for me

**Comment by SomberNight** [comment]
Well it does work for me, if I repeatedly press the back button to exit, but indeed it should work better.

**Comment by ecdsa** [comment]
fixed by 88bb5309c4d74adb7ba1ac24e5bcb05ef34b2bf9
