### ISSUE TITLE
Use .psbt extension for PSBT files

### ISSUE THREAD

**Issue by Sjors** [spesmilo/electrum#5954]
On the latest master branch, PSBT (binary) files are saved with a .txn extension. Bitcoin Core is probably going to use the `.psbt` extension, see https://github.com/bitcoin/bitcoin/pull/17509. An iOs app that I'm working on is able to [open .psbt files](https://github.com/Sjors/nthkey-ios/blob/master/NthKey/Info.plist#L90-L115) too, including launching the app by opening / airdropping the file. ColdCard is able to read `.psbt` files too.

[BIP174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#specification) didn't add a [magic byte](https://en.wikipedia.org/wiki/List_of_file_signatures) to the serialized format, so the file extension matters.

**Comment by SomberNight** [comment]
> On the latest master branch, PSBT (binary) files are saved with a .txn extension

Are you sure of this?
AFAICT, complete transactions are saved with `.txn`, and partial ones are saved with `.psbt`.

> BIP174 didn't add a magic byte to the serialized format, so the file extension matters.

I don't quite understand this point -- I expect these files would contain just a PSBT in binary, i.e. the first five bytes are known `70736274ff` (in hex)?

**Comment by Sjors** [comment]
I tried it with a 2-of-3 multisig (all external keys) today. Perhaps it misinterpreted it as complete?

**Comment by SomberNight** [comment]
> I tried it with a 2-of-3 multisig (all external keys) today. Perhaps it misinterpreted it as complete?

Well... not sure - I guess?
I've tried now with a 2of3 wallet comprised of 3 Upubs, created an unsigned tx and exported it directly. It resulted in a .psbt

The relevant code is here:
https://github.com/spesmilo/electrum/blob/111ef9ebb11380cf2ee49b327988a8e21e99934b/electrum/gui/qt/transaction_dialog.py#L302-L313

**Comment by Sjors** [comment]
> Well... not sure - I guess?

I distinctly remember renaming the file extension.

Mine uses Vpubs (native segwit multisig) in case that could matter.

**Comment by SomberNight** [comment]
> If I click Save instead of Export it crashes:

ignore that; unrelated. should be ok with https://github.com/spesmilo/electrum/commit/111ef9ebb11380cf2ee49b327988a8e21e99934b

> [image]

So this is on MacOS? What is your version of Qt?
`from PyQt5.QtCore import QT_VERSION_STR; from PyQt5.QtCore import PYQT_VERSION_STR; print(f"Qt: {QT_VERSION_STR}. PyQt: {PYQT_VERSION_STR}")`

I fear this will end up being a platform quirk.

**Comment by SomberNight** [comment]
Ah ok, I see you've actually said you built a binary.
Then the versions are pinned down.

**Comment by Sjors** [comment]
QT 5.14.1 via Homebrew. With your incantation: `Qt: 5.11.2. PyQt: 5.11.3` (not sure why those versions don't match)

**Comment by SomberNight** [comment]
Ok I confirm that all txns are saved with the `.txn` extension.
I have tested on Win10, Ubuntu 18.04, and MacOS 10.11 now.
It is only happening on MacOS.

As in your picture, on MacOS, the extension we set is being stripped from the name for some reason, and then I guess it is just picking the first extension listed in the filter, which is `.txn`.

**Comment by jpcummins** [comment]
I just tested this with 4.0.0a0 on Mac OS 10.15.3

In the save dialog, if one leaves the filename as-is (which is pre-populated as [filename].psbt), it saves with the .psbt extension. Otherwise, if one types a custom filename without an extension, '.txn' is appended.

**Comment by Sjors** [comment]
That did the trick.
