### ISSUE TITLE
Add full BIP32 derivation to PSBT

### ISSUE THREAD

**Issue by Sjors** [spesmilo/electrum#5955]
Thanks to #5721 Electrum can now export PSBT files. I tried this with a multi-signature setup (3 imported Vpubs) and inspected it in Bitcoin Core with `decodepsbt`. Looks good at first glance, except for the derivation paths, which in Electrum are relative to the xpub, not relative to the master key.

There's a case to be made for that. Multisig wallets should commit to the xpubs of their cosigners anyway, so they might as well use relative derivation.

However it would be nice to at least have the option of using the full path and the master key fingerprint. Perhaps this could be achieved by adding two optional fields during wallet setup: root derivation and master key fingerprint.

**Comment by SomberNight** [comment]
> the derivation paths, which in Electrum are relative to the xpub, not relative to the master key.

Indeed.

> However it would be nice to at least have the option of using the full path and the master key fingerprint. Perhaps this could be achieved by adding two optional fields during wallet setup: root derivation and master key fingerprint.

You are right to notice that the wallet itself currently does not even have the full path (only has derivation suffix) and the root fingerprint -- at least in the case when only given an xpub. This would require changes to the wizard. See https://github.com/spesmilo/electrum/issues/5715

Even if the wallet had this information, one could argue there are cases where it would be better not to include it in the PSBT (better for privacy) -- just like whether the global xpubs fields should be populated. see https://github.com/spesmilo/electrum/issues/5672#issuecomment-548481790

In some cases, e.g. when doing a coinjoin, it is best to strip almost all the fields (again, for privacy).
See https://github.com/spesmilo/electrum/pull/5440#issuecomment-549567042 for different flows (and what is included in each case)

-----
I'm not sure how to proceed with this matter in general. I guess https://github.com/spesmilo/electrum/issues/5715 is the blocker.

**Comment by ecdsa** [comment]
why would that be nice?

**Comment by Sjors** [comment]
To be compatible with existing software and hardware. For example with [HWI](https://github.com/bitcoin-core/HWI) you can ask a device for an xpub at any derivation depth, but you can't give a device an xpub; it won't recognise it. Hardware wallets generally don't store an xpub to deriviation path mapping.

Even multi-sig wallets, they have a security need to store the xpub of their cosigners (most don't atm), but no need to store their own xpub (which they can and probably should derive from the seed each time).

**Comment by relativisticelectron** [comment]
I am running into the same problem with version 4.0.2 in a watch-only-multisig: The PSBT contains only relative paths not absolute ones.
How can I tell electrum to include the full path in the PSBT?

**Comment by relativisticelectron** [comment]
I also checked 
```
wallet.get_keystores()[0].get_derivation_prefix()
"m/48'/0'/0'/2'"
```
but still the PSBT contains only relative paths.  Is there some other switch I have to enable to get full derivation paths in the PSBT?

**Comment by lucasmoten** [comment]
> * +1 For a 2 of 3 watch-only multisig with pure BIP39 seeds:  I now managed to set the root fingerprint and derivation_prefix for all wallets
> 
> ```
>  wallet.get_keystores()[<wallet_index>].add_key_origin(derivation_prefix="m/48h/0h/0h/2h", root_fingerprint="<fingerprint>")
> ```

I think this is part of what I did to get one of my test wallets to work for this a few months back. I need to dig into this again

**Comment by SomberNight** [comment]
Now with https://github.com/spesmilo/electrum/commit/c81551299ef470d8580b56c316be242a0b810d7c, I guess I will close this.

We now put full paths into the psbt, if the key origin is available.
Note however that it is often not available, but for that see other issues, e.g. https://github.com/spesmilo/electrum/issues/5715
