### ISSUE TITLE
Remove Archos Safe-T hardware wallet support 

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5968]
I am considering removing Archos Safe-T hardware wallet support.

1. The archos project seems dead: no commits in their main repositories for over a year.
    - Last commit in https://github.com/archos-safe-t/safe-t-mcu/tree/master is from Dec 2018.
    - Last commit in https://github.com/archos-safe-t/python-safet/tree/master is from Jan 2019.

2. Multisig broke in their last fw update, and that has not been fixed for many months.
    - see https://github.com/spesmilo/electrum/issues/5446

3. Including the `safet` package in the Windows binary is preventing us from shipping a newer Python interpreter than 3.6.x.
    - This outstanding PR (https://github.com/archos-safe-t/python-safet/pull/3) would fix that. It has been open for over a month.

Note that even if the plugin is removed, it can be re-added later at any point.
Currently I would want at the very least to have point (3) resolved.

@jcrona

**Comment by jcrona** [comment]
Hi @SomberNight 
I'm no longer working at Archos, however, the team in charge of the Safe-T mini is aware of the issues and is currently working fixes.

BR

**Comment by s-stark** [comment]
I just merged your PR and published safet-0.1.5. That should resolve (3)

**Comment by SomberNight** [comment]
Great! Thanks. I will close this for now.

Would be nice to also have the multisig bug (point 2) fixed :)

**Comment by gruve-p** [comment]
@s-stark My attempt to resolve (2): https://github.com/archos-safe-t/safe-t-mcu/pull/1

**Comment by gruve-p** [comment]
@SomberNight
The archos project seems dead: no commits in their main repositories for over 2 years. Can you reopen this issue?

Last commit in https://github.com/archos-safe-t/safe-t-mcu/tree/master is from Dec 2018.
Last commit in https://github.com/archos-safe-t/python-safet/tree/master is from Feb 2020.

This outstanding PR (https://github.com/archos-safe-t/safe-t-mcu/pull/1) would fix multisig. It has been open for over a month.
Emails sent to their support is not being answered.
