### ISSUE TITLE
3.3.8 Wont launch (could not import electrum.plot)

### ISSUE THREAD

**Issue by nc50lc** [spesmilo/electrum#5974]
**Operating System**: Windows 10
**Version**: Electrum v3.3.8 from website, all executables (_portable, installer and stand-alone_)

Last few lines from Log: 
> 20200220T032057.149728Z |     INFO | network | starting network
20200220T032057.149728Z |     INFO | network | connecting to electrumx.soon.it:50002:s as new interface
20200220T032057.151730Z |    DEBUG | util.profiler | Daemon.__init__ 0.0090
20200220T032057.154729Z |     INFO | exchange_rate.BlockchainInfo | getting fx quotes for USD
20200220T032057.317270Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.

It was working before but after I changed the GPU (_Radeon RX570_) and drivers (_Adrenaline Radeon Software_), Electrum wont launch at all.
IDK if it's the drivers that caused the issue. Windows Update is totally disabled.

**Previously tried**:
Using a fresh data directory wont solve the issue.
Some very old versions are still launching like 1.9.5.
Launching 3.3.8 from 'github/releases'' directly through Python works.

**Comment by ecdsa** [comment]
the log lines you posted are probably not related to your issue.

**Comment by nc50lc** [comment]
But there's nothing else past "This feature needs matplotlib to be installed."

**Comment by SomberNight** [comment]
might be same as https://github.com/spesmilo/electrum/issues/5888 ?

**Comment by nc50lc** [comment]
The complete log looks similar, 3.1.0 also crashed and 3.0.6 worked.

The only major update that I did before it failed to launch was installing AMD (GPU) drivers.
Events viewer for "_electrum errors_" are just filled with "_unknown_", wont be of help if I post them here.

Here's the latest event viewer log:
> Faulting application name: electrum-3.3.8.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x1088
Faulting application start time: 0x01d5e86db1495492
Faulting application path: _-snip-_\electrum-3.3.8.exe
Faulting module path: unknown
Report Id: f2caebf5-6933-48b6-9 _-snip-_
Faulting package full name: 
Faulting package-relative application ID:

**Comment by nc50lc** [comment]
I just upgraded the faulty PC's OS and now every version works.
I think it has something to do with a certain Windows10 build (_old 1511 IIRC_) and Radeon Adrenaline Drivers (_RX570 GPU_).
Nevertheless, this must be more of a Windows10-related issue than Electrum's.

This issue can be closed IMO, but I'll leave it to the Devs.
