### ISSUE TITLE
Forget channels if funding transaction inputs have been double spent

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#5975]
Per BOLT2:

>  A non-funding node (fundee): SHOULD forget the channel if it does not see the correct funding transaction after a reasonable timeout.
> From the point of waiting for funding_locked onward, either node MAY fail the channel if it does not receive a required response from the other node after a reasonable timeout.

this means we need to store an extra timestamp

**Comment by ecdsa** [comment]
The issue is what to do with a channel if we never see its funding transaction on the chain. The bolt mentions non-funding nodes. As a funding node, we should not delete a channel because we do not see the funding tx, because the electrum server can be lying by omission. Thus, the only safe way to allow the user to delete a channel is to wait until the inputs of the funding transaction have been double spent (and mined). Therefore, we should store the funding transaction until the channel is in the OPEN state. (we should not let the user delete the funding tx if it becomes local)

**Comment by SomberNight** [comment]
I'd argue these are separate issues then.
If we are not the funder, have a timeout and forget about the channel if we don't see funding tx even in the mempool when the timeout expires.
If we are the funder, we should only delete the channel if the funding tx inputs have been double-spent --- but note that they can only be double-spent by us. I think it's fine to allow deleting the local tx from the wallet if it becomes a local tx and then let the user attempt a double-spend -- if the funding tx gets confirmed even still, it will just get redownloaded.

**Comment by ecdsa** [comment]
I am mostly concerned by the case where we are the funder. Indeed we should allow the user to delete the local tx from history, but we must not delete the list of inputs. I will store it in the channel storage.
