### ISSUE TITLE
Coldcard Electrum Setup - No hardware device detected.

### ISSUE THREAD

**Issue by in3rsha** [spesmilo/electrum#5977]
I've recently tried to use Coldcard as a hardware device with Electrum, but I am getting the following error when running `electrum -v`:

```
I | plugins.coldcard.qt.Plugin | late failure connecting to device?
```

After editing `coldcard.py` to get a more detailed trace of the error I get:

```
E | plugins.coldcard.qt.Plugin | late failure connecting to device?
Traceback (most recent call last):
  File "/home/me/Desktop/Electrum-3.3.8/electrum/gui/qt/installwizard.py", line 93, in func_wrapper
    out = func(*args, **kwargs)
  File "/home/me/Desktop/Electrum-3.3.8/electrum/gui/qt/installwizard.py", line 467, in confirm_dialog
    self.confirm(message, title)
  File "/home/me/Desktop/Electrum-3.3.8/electrum/gui/qt/installwizard.py", line 473, in confirm
    self.exec_layout(vbox, title)
  File "/home/me/Desktop/Electrum-3.3.8/electrum/gui/qt/installwizard.py", line 368, in exec_layout
    raise GoBack from None
electrum.base_wizard.GoBack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/Desktop/Electrum-3.3.8/electrum/plugins/coldcard/coldcard.py", line 656, in create_client
    is_simulator=(device.product_key[1] == CKCC_SIMULATED_PID))
  File "/home/me/Desktop/Electrum-3.3.8/electrum/plugins/coldcard/coldcard.py", line 102, in __init__
    self.dev = ElectrumColdcardDevice(dev=hd, encrypt=True)
  File "/home/me/.local/lib/python3.6/site-packages/ckcc/client.py", line 65, in __init__
    self.resync()
  File "/home/me/.local/lib/python3.6/site-packages/ckcc/client.py", line 94, in resync
    raise RuntimeError('hidapi: '+err)
RuntimeError: hidapi: hid_error is not implemented yet
```

I have tried to connect the Coldcard on two different computers with two different cables, and I've had encountered the same problem on both. I'm not sure if this is a problem with my Coldcard or something else.

* **OS:** Ubuntu 18.04 bionic
* **Electrum:** 3.3.8
* **Coldcard Firmware:** 3.0.6

I asked this question on the #electrum IRC channel and @SomberNight suggested to open the issue here.

P.S. I was recommend to tag @peter-conalgo also.

**Comment by jlopp** [comment]
Have you added the udev rules? https://raw.githubusercontent.com/Coldcard/ckcc-protocol/master/51-coinkite.rules

Also I'd install the python library via:
sudo pip3 install ckcc-protocol

A final thing to note is that electrum 3.3.8 seems to have issues with using coldcard for multisig wallets; the fixes for this appear to be in the master branch.

**Comment by in3rsha** [comment]
These are the steps I have taken so far:

```
sudo apt-get install libusb-1.0-0-dev libudev-dev
sudo python3 -m pip install ckcc-protocol
wget https://raw.githubusercontent.com/Coldcard/ckcc-protocol/master/51-coinkite.rules
sudo mv 51-coinkite.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules && sudo udevadm trigger
```

I have also done this extra step to try and see if it helped:

```
sudo groupadd plugdev
sudo usermod -aG plugdev $(whoami)
sudo cp contrib/udev/*.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules && sudo udevadm trigger
```

I don't do much python, so I am concerned that using a variant of one of these has caused me a problem: `sudo pip3 install ckcc-protocol` or `sudo python3 -m pip install ckcc-protocol` or `python3 -m pip install ckcc-protocol`.

I don't know the difference (of if I should be using `sudo`).

**Comment by peter-conalgo** [comment]
It's some sort of breaking change in `hidapi`. Another user has [reported it here](https://github.com/Coldcard/ckcc-protocol/pull/9) and fix is merged but not released yet.

**Comment by in3rsha** [comment]
@peter-conalgo Okay thank you.

**Comment by peter-conalgo** [comment]
Please use version 1.0.1 of `ckcc-protocol` to get the bugfix ... perhaps this project's requirements.txt should be updated to match.

**Comment by resteinbock** [comment]
I am stuck with this issue and am not familiar with python. I have run the same commands as @in3rsha. How do I use `ckcc-protocol` version 1.0.1 ?
