### ISSUE TITLE
maybe make lightning node_id (node pubkey) deterministic

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5978]
Related: https://github.com/spesmilo/electrum/issues/5966

Currently the node_id is randomly generated.

Invoices are signed with this pubkey, and also for some recovery scenarios it might useful if it can be recovered from seed.

OTOH, some of our users reuse seeds between multiple devices, and so if they open channels on multiple devices with reused seed, these nodes would all share a node_id.
Remote nodes might get confused by this.
I expect two such devices might not be able to establish a ln p2p transport simultaneously with the same remote peer.
Depending on implementation, I guess it could happen that if we don't reply an unknown `channel_reestablish`, the remote force-closes that channel (but I think it's unlikely).

Note however that if the node_privkey was derived from the seed, we couldn't use lightning on a watch-only wallet or even a hardware wallet.

**Comment by SomberNight** [comment]
> Note however that if the node_privkey was derived from the seed, we couldn't use lightning on a watch-only wallet or even a hardware wallet.

Because of this point, this decision is deferred.

**Comment by ecdsa** [comment]
closing: we have decided to keep a random lightning seed, and to derive node_id from it.

**Comment by SomberNight** [comment]
note: https://github.com/spesmilo/electrum/pull/7112 made some of the LN keys, most notably the node_id, deterministic for wallets with electrum seeds. BIP39 seeded wallets, zprvs, or any existing wallet files with already generated lightning keys still use a random node_id.
