### ISSUE TITLE
Cannot save unsigned transaction in 3.3.8

### ISSUE THREAD

**Issue by Simel** [spesmilo/electrum#5983]
When I make an unsigned transaction from a read only wallet, then looking at the preview, the save button is disabled. pressing the export button leads to program freeze without any other message.
any idea, what the problem is? thanks in advance, S.

**Comment by Simel** [comment]
It is running on Windows 10 64bit.

**Comment by SomberNight** [comment]
> When I make an unsigned transaction from a read only wallet, then looking at the preview, the save button is disabled

This is expected. "Save" would save the tx in the history as a local tx. In 3.3.8 this is only allowed for completed/signed txns.

> pressing the export button leads to program freeze without any other message

Maybe try looking at [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging).

- What kind of wallet is it? Check menu bar `Wallet`>`Information`. "Wallet type" / "Script type" / "Keystore type"
- Anything special about the tx? E.g. does it have many inputs/outputs? Does the wallet itself have a long history (many txs), or many addresses? "many" here is e.g. >1000

**Comment by Simel** [comment]
it is a script type "p2pkh", keystore "old" wallet, 27 addresses, 1 transaction in history.
BUT: after once enabeling "write logs to file" - export works like excepted. 

now, it's not possible for me, to reproduce the behaviour it has before. thank you any way, SomberNight,  for your support!

best regards
