### ISSUE TITLE
Bug in a transaction

### ISSUE THREAD

**Issue by Neuropeptidus** [spesmilo/electrum#5988]
Hello !
I have a problem between Electrum 3.3.8 and a market site with a transaction witch is normally effective on Electrum but the amount never had been on the website.
This was not my first time and all the others times were well done.
I really don't understand?
Can you help me please ?
Thank you very much.
Buy.
Eric

**Comment by SomberNight** [comment]
Hi. You have not provided any details, so it's hard to help...
Did you send from Electrum to the website?
Does the tx show up in your History tab?
Has the tx been mined/confirmed?
