### ISSUE TITLE
"Unknown error" when trying to send a payment from portable desktop wallet 3.3.8

### ISSUE THREAD

**Issue by veluisg** [spesmilo/electrum#5990]
I've tried to send a payment from my desktop wallet (electrum-3.3.8-portable) and, when I pressed "send" the app asked me for password and then this message appears:

> The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.

Unknown error

I tried using different servers but the same happens.
Does anybody know what I did wrong?

**Comment by SomberNight** [comment]
Check [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging), those will show exactly what the remote server is saying. (don't follow links and don't trust that message blindly)

**Comment by veluisg** [comment]
I solved it. Trying with a bunch a servers, provided by the same wallet, until I found one who let me send the payment. Thanks @SomberNight
