### ISSUE TITLE
Unknown error on an Electrum transaction

### ISSUE THREAD

**Issue by Connando83** [spesmilo/electrum#5994]
Hi, 
I try to send some bitcoin and I get the following message (in French, translation below) :

"Le serveur a retourné une erreur lors de la transmission de la transaction.
Essayez de vous connecter à un serveur différent ou mettez à jour Electrum.

Erreur inconnue"
[The server returned an error during the transmission of the transaction. try to connect to a different server or update Electrum. Unknown error]
I have updated Electrum to 3.3.8 and I still get this message.
Thanks if anybody can help with this.

**Comment by SomberNight** [comment]
Try with a different server.

**Comment by Connando83** [comment]
I have tried this, too. And this does not work either.

**Comment by Connando83** [comment]
Ok, I have tried with 5 different servers, and it worked, at last...
