### ISSUE TITLE
ln: decouple receiving and settling of incoming HTLCs

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5997]
Currently the processing of incoming HTLCs is all tied together via internal coroutine state.
If we restart the process (or just simply lose connection to the remote peer) after having a received htlc committed but before having the removal committed, the affected channel will essentially get broken and have to be force-closed.

https://github.com/spesmilo/electrum/blob/e54c69b861c2990adf9cf618b68c6f1c7dd3ebea/electrum/lnpeer.py#L1141-L1143

**Comment by ecdsa** [comment]
see #6003
