### ISSUE TITLE
Electrome wallet problem

### ISSUE THREAD

**Issue by fardin1994** [spesmilo/electrum#5998]
Hi.
I use your company electrum wallet. At (2220-02-25) 23:22
The amount of 0.00750539 BTC to the address
(38N4QnKuUsRRfV3uudhcRWiWSz9R2mDDSS) I sent.
But when I hit send, the address changed and it was sent to this address
(bc1qcygs9dl4pqw6atc4yqudrzd76p3r9cp6xp2kny)
If I entered the previous address.
please follow up
Thankful

**Comment by SomberNight** [comment]
Hi. Where did you download Electrum from?
Check your browser history for a URL.
