### ISSUE TITLE
Reciving Adress gone - missed my transsaction!

### ISSUE THREAD

**Issue by Shaici** [spesmilo/electrum#6002]
Hi,
I've been waiting for trancaction since yesterday, and now it apears that that adrees that i had given is gone -  mean i didn't receive mony.
Trancaction was done - but i cant recive it because I dont have that adress any more!
HOW???
How can I recive that trancaction

**Comment by SomberNight** [comment]
Hi.

> now it apears that that adrees that i had given is gone 

What exactly do you mean?

Also, see https://bitcoinelectrum.com/frequently-asked-questions/#what-can-i-do-if-i-havent-received-bitcoins-sent-to-me

**Comment by Shaici** [comment]
I've just given my adress for transaction and now i can't find that adrees in electrum
