### ISSUE TITLE
wallet electrum can't restore

### ISSUE THREAD

**Issue by zelaskar** [spesmilo/electrum#6004]
hello, I come back to you again I have version 3.3.8 of Electrum, it is impossible for me to recover my funds on my wallet, I however followed the procedure, with password and sheath, but during the restoration the funds have disappeared:
Transaction: from 15/02/2020: address 15xQbsEmdhNQdtttfhLzJ7kLYa5Vazvw6x, from Paymium to Electrum, amount 0.016 Btc, please do what is necessary so that I recover my funds, 15 days that I struggle to restore and recover my money, thank you.

**Comment by SomberNight** [comment]
It's difficult to understand the situation from your description.
Maybe try restoring from seed?

See https://bitcoinelectrum.com/frequently-asked-questions/#what-can-i-do-if-i-havent-received-bitcoins-sent-to-me

Check whether that address belongs to your wallet: https://bitcoinelectrum.com/frequently-asked-questions/#how-can-i-tell-if-an-address-belongs-to-my-wallet

**Comment by zelaskar** [comment]
hello, thank you for your answer, I will try to be more clear, I
wanted to rewrite my wallet, following an update, first of all my
funds appeared, but impossible to use the wallet, I have donated a
restoration, and despite using it. the same name, password, and faine,
the restoration worked well but the funds have disappeared. I tried
all the manipulations explained on the FAQ, but nothing helps,. funds
are still in the blockchain, unspent. thank you for helping me.

**Comment by AbdussamadA** [comment]
there's an FAQ regarding wallet restoration [here](https://bitcoinelectrum.com/frequently-asked-questions/#my-seed-is-not-restoring-my-wallet-what-can-i-do) just in case you haven't seen it.

If the above doesn't help then please answer the following questions:

- was the seed originally generated using electrum or some other software?

- does the address in question 15xQ.. appear in your wallet? [how to tell](https://bitcoinelectrum.com/frequently-asked-questions/#how-can-i-tell-if-an-address-belongs-to-my-wallet)

- does the restored wallet have any transactions on the history tab i.e. the first tab to the extreme left?

**Comment by zelaskar** [comment]
hello first of all I deplore the lack of technical assistance from
Electrum, a lamentable and unacceptable lamentation, my problem is linked
to the disappearance of my history, and of my funds during a restoration of
my portfolios. What to do ? my funds always appear in the blockchain as
unused. Thank you for your help.

JOP.

**Comment by ecdsa** [comment]
Nobody will be able to help you if you cannot provide relevant information.

There are multiple possible reasons why you cannot restore your funds:
 - you might be using a wrong seed
 - you might be using the correct seed, but adding or omitting a seed extension
 - you might have messed with the gap limit of your wallet (you would know)
 - the transaction that you expect to send funds to your wallet has sent funds to an address that is not in your wallet (this can be caused by malware, but most of the time by user stupidity)

Without relevant information, we cannot help you more than that.

**Comment by zelaskar** [comment]
bjr, I have the version Electrum 3.3.8, a problem occurred, I followed the
procedure in order to restore my Wallet, with the chain of words the
Sheath, the password, but impossible to restore the Wallet, the system open
a new wallet every time. Operation: 15xQbsEmdhNQdtttfhLzJ7kLYa5Vazvw6x,
from 15/02/2020.
Sent from Paymium, to Electrum 3.3.8. Amount of 0.016 Btc, $ 159.10. I
cannot find my Electrum account identifier, but it is clearly stated in
your help icon comments, that it is enough to have the sheath phrase to
restore my account, or that does not work. It is not possible for me to
lose this transaction, you have all the elements to help me to recover this
operation, still not spent in the blockchain. In advance thank you, JOP

**Comment by ecdsa** [comment]
Sorry but you are just repeating yourself. You did not answer any of the questions from @AbdussamadA. To make things even more confusing, you are making up technical terms ("the Sheath", seriously?)

Please stop wasting our time or I will close that issue. And stop making unfunded statements such as "you have all the elements to help me to recover this operation", this is really wasting everybody's time.

**Comment by bitcoinheiro** [comment]
The most important thing is to KEEP your seed secure, don't share it with anyone. If funds have not moved from your address you should be good and they will be there in the future when you manage to work this out. Now go and learn in depth how it works (read french content) so you're able to do it yourself without the help of anyone. You have a 0.016 BTC incentive to enrich yourself with knowledge. Good luck
