### ISSUE TITLE
AttributeError: module 'logging' has no attribute 'Formatter'

### ISSUE THREAD

**Issue by Wilburunion** [spesmilo/electrum#6009]
Put Electrum 3.3.8 in /usr/lib/python3.6/site-packages and I put all the modules there..  Running on VPS OpenVZ Centos 7 server - no gui available.  Old 2.9.3 using fedora rpm worked fine.  The following command (Python 3.6.8) produces the error and it does not launch.

```
[root@main electrum]# /usr/bin/python3 -s /usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/electrum daemon start
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/electrum", line 79, in <module>
    check_imports()
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/electrum", line 64, in check_imports
    import jsonrpclib
  File "/usr/lib/python3.6/site-packages/jsonrpclib/__init__.py", line 29, in <module>
    from jsonrpclib.jsonrpc import Server, ServerProxy
  File "/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 62, in <module>
    import logging
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/logging.py", line 15, in <module>
    class LogFormatterForFiles(logging.Formatter):
AttributeError: module 'logging' has no attribute 'Formatter'
```

If I use run_electrum I get 
```
[root@main electrum]# /usr/bin/python3 -s /usr/lib/python3.6/site-packages/Electrum-3.3.8/run_electrum
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/run_electrum", line 362, in <module>
    d.init_gui(config, plugins)
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/daemon.py", line 348, in init_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/gui/qt/__init__.py", line 39, in <module>
    from PyQt5.QtGui import QGuiApplication
ModuleNotFoundError: No module named 'PyQt5.QtGui'
[root@main electrum]#
```
But there is no gui on the system so if I comment out beginning at line 251 as follows from run_electrum the call to gui as below 

```
        constants.set_simnet()

##    if cmdname == 'gui':
##         configure_logging(config)
##         fd, server = daemon.get_fd_or_server(config)
##        if fd is not None:
##          plugins = init_plugins(config, config.get('gui', 'qt'))
##            d = daemon.Daemon(config, fd)
##            d.init_gui(config, plugins)
##            sys.exit(0)
##        else:
##            result = server.gui(config_options)

##    elif cmdname == 'daemon':
   if cmdname == 'daemon':
```
I then get 
```
[root@main electrum]# python3 /usr/lib/python3.6/site-packages/Electrum-3.3.8/run_electrum
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/run_electrum", line 368
    if cmdname == 'daemon':
                          ^
IndentationError: unindent does not match any outer indentation level
[root@main electrum]#
```
But that was a hack-try

I installed the electrum merchant module but did not get that far as electrum does not launch.

Is there a setup  situation I am missing or doing wrong ??

**Comment by SomberNight** [comment]
> Put Electrum 3.3.8 in `/usr/lib/python3.6/site-packages` and I put all the modules there..

Well you should probably not put files manually into site-packages.

Try moving the `Electrum-3.3.8` folder to e.g. `/opt` or somewhere in `$HOME`.

>   ```
>  File "/usr/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 62, in <module>
>      import logging
>    File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/logging.py", line 15, in <module>
>      class LogFormatterForFiles(logging.Formatter):
>  AttributeError: module 'logging' has no attribute 'Formatter'
>  ```

As is, your setup seems broken as the local `logging` module inside electrum seems to have priority over the python standard library `logging` module.

**Comment by Wilburunion** [comment]
Does the same thing in /opt or /home . . .  so I disabled that logging.py script by turning it into logging_py and now it asks for me to install the SimpleWebsocket Server

I did so and configured the domain  and port in electrum using the page at https://electrum.readthedocs.io/en/latest/merchant.html

Putting Electrum 3.3.8 in the /usr/lib/python3.6/site-packages/ directory assures a good Python3 path and this is how th rpm files set up electrum.  I created and symlinked user/bin/electrum to /usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/electrum executable and now it works WITHOUT logging.py at all from /usr/lib/python3.6/site-packages/Electrum-3.3.8

So . . .  it appears there is a BUG in the script or other code pointing to logging.py

[root@main Electrum-3.3.8]# python3 /opt/Electrum-3.3.8/run_electrum
Traceback (most recent call last):
  File "/opt/Electrum-3.3.8/run_electrum", line 362, in <module>
    d.init_gui(config, plugins)
  File "/opt/Electrum-3.3.8/electrum/daemon.py", line 348, in init_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/opt/Electrum-3.3.8/electrum/gui/qt/__init__.py", line 39, in <module>
    from PyQt5.QtGui import QGuiApplication
ModuleNotFoundError: No module named 'PyQt5.QtGui'

[root@main Electrum-3.3.8]# python3 /opt/Electrum-3.3.8/electrum/electrum daemon start
Traceback (most recent call last):
  File "/opt/Electrum-3.3.8/electrum/electrum", line 79, in <module>
    check_imports()
  File "/opt/Electrum-3.3.8/electrum/electrum", line 64, in check_imports
    import jsonrpclib
  File "/root/.local/lib/python3.6/site-packages/jsonrpclib/__init__.py", line 29, in <module>
    from jsonrpclib.jsonrpc import Server, ServerProxy
  File "/root/.local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 62, in <module>
    import logging
  File "/opt/Electrum-3.3.8/electrum/logging.py", line 15, in <module>
    class LogFormatterForFiles(logging.Formatter):
AttributeError: module 'logging' has no attribute 'Formatter'
[root@main Electrum-3.3.8]# cd electrum
[root@main electrum]# electrum
Traceback (most recent call last):
  File "/usr/bin/electrum", line 79, in <module>
    check_imports()
  File "/usr/bin/electrum", line 64, in check_imports
    import jsonrpclib
  File "/root/.local/lib/python3.6/site-packages/jsonrpclib/__init__.py", line 29, in <module>
    from jsonrpclib.jsonrpc import Server, ServerProxy
  File "/root/.local/lib/python3.6/site-packages/jsonrpclib/jsonrpc.py", line 62, in <module>
    import logging
  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/logging.py", line 15, in <module>
    class LogFormatterForFiles(logging.Formatter):
AttributeError: module 'logging' has no attribute 'Formatter'

After changing the name to disable it 

[root@main electrum]# ^C
[root@main electrum]# python3 /opt/Electrum-3.3.8/electrum/electrum daemon start
install SimpleWebSocketServer
[root@main electrum]# electrum daemon status
install SimpleWebSocketServer

after doing so . . . 

[root@main electrum]# electrum setconfig websocket_port 9999
true
[root@main electrum]# python3 /usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/electrum daemon start
starting daemon (PID 7314)
[root@main electrum]# electrum daemon status
{
    "auto_connect": true,
    "blockchain_height": 573351,
    "connected": false,
    "current_wallet": null,
    "fee_per_kb": null,
    "path": "/root/.electrum",
    "server": "b.ooze.cc",
    "server_height": 0,
    "spv_nodes": 0,
    "version": "3.3.8",
    "wallets": {}
}
[root@main electrum]# ^C

So I I will fix the init.d and the rest of the setup to get out Bitcoin working again upon automatic reboot and restart 

Maybe the powers that be at electrum.org might want to build an RPM for CentOS 7 / PHEL 7 because it only has python 3.6.8  available and a glibc that is lower than Fedora 30  - so unlike with the electrum 2.9.3 version rpm for Fedora 26 - it cannot be used with the 3.3.4 rpms of Fedora because they need a higher glibc (2.29)  and there is no Python 3.7 rpm for Centos 7 - and may not be for a while if ever before Centos 8 comes out.

So literally the current Electrum traball could be put into n rpm to dump it into site packages and do a symlink from /usr/bin/electrum into /usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/electrum executable and do the other dependencies because I see this error I reported in lots of places around the web and it looks like now there is a bug in logging.py

**Comment by SomberNight** [comment]
> AttributeError: module 'logging' has no attribute 'Formatter'

What is `$PWD` when you are getting this error?
For some reason your `sys.path` is messed up.
Are you `cd`-d into the inner electrum folder where the `logging.py` file can be found? You should not be.

Maybe try `python3 -I` ([isolated mode](https://docs.python.org/3/using/cmdline.html#id2))

**Comment by Wilburunion** [comment]
PWD - is any
As you see from that above - it is run by hard path from the root user main directory
NOT in the same directory with logging.py

logging.py  must have a bug as described by the error - since there is a default logging python file - I removed it and it is working now

don't need to use python3 - as the system calls iy since the electrum symlink points into the python 3.6 directory  -  so checking the running processes shows electrum daemon start  is running under python3

logging.py must be the bug as described by the error

**Comment by SomberNight** [comment]
There is no bug in `logging.py`.

Clearly whatever is causing your particular issue, you are in the minority, as hardly anyone else is complaining.
Your `sys.path` contains the electrum package **before** the standard library, for some reason, hence our custom module is getting confused with the standard library module because of the name collision.

These kind of name collisions are allowed in modern python, and the standard library should have priority (unlike in your weird case). In fact, this should be the case since ~17 years ago, long before Python3. See [PEP-328](https://www.python.org/dev/peps/pep-0328/#id8):

> In Python 2.4 and earlier, if you're reading a module located inside a package, it is not clear whether
> 
> `import foo`
> 
> refers to a top-level module or to another module inside the package. As Python's library expands, more and more existing package internal modules suddenly shadow standard library modules by accident. It's a particularly difficult problem inside packages because there's no way to specify which module is meant. To resolve the ambiguity, it is proposed that foo will always be a module or package reachable from sys.path. This is called an absolute import.
> 
> The python-dev community chose absolute imports as the default because they're the more common use case and because absolute imports can provide all the functionality of relative (intra-package) imports -- albeit at the cost of difficulty when renaming package pieces higher up in the hierarchy or when moving one package inside another.

Note the mention of `sys.path`. Again, this is corrupted for you for some reason.

Try `python3 -I`, isolated mode.

**Comment by SomberNight** [comment]
> Try `python3 -I`, isolated mode.

Also try `python3 -s -E`.

**Comment by Wilburunion** [comment]
I do not see what any path has to do with this when the error ckearky points to a specific file and the line.

Here is my sys.path - and I do not see anything wrong with it.

[root@main ~]# python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/root/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']

/root/.local/lib/python3.6/site-packages is empty

I may be in the minority on this because almost no one uses electrum on a server to run in daemon mode   that uses this downloaded tarball - and run_electrum assumes and is looking for a gui it seems.  That will never work - there is no Qt installed and no desktop.  As I explained previously there is now no Centos7 rpm and the Fedora ones would work but cannot due to glibc higher version dependencies.  Launching electrum in daemon mode assumes you know how and where to find it.  I do not see anything work with my sys.path and it is a default Python 3.6.8 install from a Centos 7 rpm from the base repo via yum

Nothing is custom built from source that would be pathed wrong.  I do not see nor need to try python3  launches  with switches as "electrum daemon start"  is working now WITHOUT logging.py

Creating the symlink in usr/bin/electrum to the electrum executable which is in the Electrum-3-8-8 package assures it launches by python3 in my electrum service and without disturbing python 2.7 which is still on the system and must remain there or I risk trashing the CentOS completely

I am not a programmer but have done my share of code fixes - and according to the 10 plus sites I have seen this same error reported to it looks like to me like the error as reported is accurate and describes missing code - which is a bug - removing the file and electrum launches and runs as a daemon with no problems I have seen so far.  I never found a fix for it as each time the thread just stopped or died with no answer or solution

  File "/usr/lib/python3.6/site-packages/Electrum-3.3.8/electrum/logging.py", line 15, in <module>
    class LogFormatterForFiles(logging.Formatter):
AttributeError: module 'logging' has no attribute 'Formatter'

looks accurate and specific  to me.

**Comment by SomberNight** [comment]
> and run_electrum assumes and is looking for a gui it seems

This is incorrect. If you don't specify what you want, the gui is the default.
You can call `run_electrum daemon start` / `run_electrum help` or whatever you like.

**Comment by Wilburunion** [comment]
Nice to know . . .  that sentence show be on the download page at electrum.org - BUT no one running it as a daemon for a website would want to start their "electrum service" by  launching through a script file.  I was looking ideally for an upgrade to an rpm as an existing setup . . .  and I did try "run_electrum daemon start" on a guess and it gave me the same error until I removed the logging.py module by renaming it logging_py

**Comment by SomberNight** [comment]
> I did try "run_electrum daemon start" on a guess and it gave me the same error until I removed the logging.py module by renaming it logging_py

It cannot possibly work without that logging.py file however; so again, something weird is going on for you.
Try to figure out where it is importing logging.py now after the rename:
```
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from electrum import logging
>>> logging
<module 'electrum.logging' from '/home/user/wspace/electrum/electrum/logging.py'>
```

**Comment by Wilburunion** [comment]
Ah . . .  yes something is screwed up . . .  there is an "electrum" site-package - and it has no executable electrum file.  It is not the path it is that there are two electrum folders

If I remove that directory and rename the logging_py it still will not launch and gives the same error again

If I put that directory back it works again

[root@main ~]# python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from electrum import logging
>>> logging
<module 'electrum.logging' from '/usr/lib/python3.6/site-packages/electrum/logging.py'>

**Comment by Wilburunion** [comment]
Moving forward . . .  I now get a similar error starting electrum-merchant

AttributeError: module 'asyncio' has no attribute 'create_task'

I use WinSCP but I to find module 'asyncio'  all I get is a Python 2.7 version

[root@main ~]# find / -name asyncio.py
/usr/lib64/python2.7/site-packages/tornado/platform/asyncio.py

The create_task top-level function was added in Python 3.7, and I am using Python 3.6   See https://stackoverflow.com/questions/53247533/attributeerror-module-asyncio-has-no-attribute-create-task

[root@main ~]# python3 -m electrum-merchant
[2020-03-05 11:48:15,524] [INFO] Downloading and installing files into request directory
[2020-03-05 11:48:15,525] [INFO] copying index.html from flavour simple
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/electrum-merchant/__main__.py", line 133, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/electrum-merchant/__main__.py", line 99, in main
    downloader.download('jquery')
  File "/usr/local/lib/python3.6/site-packages/npmdownloader/packagedownloader.py", line 70, in download
    self.download_multiple([(name, version)])
  File "/usr/local/lib/python3.6/site-packages/npmdownloader/packagedownloader.py", line 67, in download_multiple
    loop.run_until_complete(self._download_packages(packages))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/npmdownloader/packagedownloader.py", line 50, in _download_packages
    for n, v in current_packages]
  File "/usr/local/lib/python3.6/site-packages/npmdownloader/packagedownloader.py", line 50, in <listcomp>
    for n, v in current_packages]
AttributeError: module 'asyncio' has no attribute 'create_task'

So I installed asyncio under Python3 as thus 

[root@main ~]# python3 -m pip install asyncio
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting asyncio
  Downloading https://files.pythonhosted.org/packages/22/74/07679c5b9f98a7cb0fc147b1ef1cc1853bc07a4eb9cb5731e24732c5f773/asyncio-3.4.3-py3-none-any.whl (101kB)
    100% |################################| 102kB 7.5MB/s
Installing collected packages: asyncio
Successfully installed asyncio-3.4.3
[root@main ~]#

Sane error as previously when run again and find does not find the new Python3 asyncio but it is a suite of modules so does not work

[root@main ~]# python3 -m pip install asyncio
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Requirement already satisfied: asyncio in /usr/local/lib/python3.6/site-packages
[root@main ~]#

[root@main ~]# electrum addrequest 3.14 -m "this is a test"

runs and produces the expected output

is electrum-merchant still for python2 only

**Comment by ecdsa** [comment]
electrum-merchant is deprecated.
the documentation has been updated to reflect that.
