### ISSUE TITLE
Channel state can transition from open to closed without verification

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6021]
A direct transition from OPEN to CLOSED is triggered when a channel has been force-closed by the remote. However, we do not check that the closing transaction has been mined, or even that it has correct signatures. This means we are vulnerable to a server telling us that our channels have been closed.

The address synchronizer does not verify signatures before adding transactions, because doing so is not sufficient to decide whether a transaction is valid or not; a malicious server can always craft a transaction with non-existing inputs, or break other consensus rules. Thus, unconfirmed transactions are considered inherently unsafe.

However, in the case of lightning channels, we know that the input exists. It would therefore make sense to verify the signature of closing transactions.

OTOH, verifying signatures is not a guarantee that the transaction will be mined, or even that it has been propagated to the miners. It might be better to introduce a new state, for transactions that are being force closed, but for which we have no SPV confirmations. The transition from OPEN to that new state would be reversible.

**Comment by SomberNight** [comment]
> A direct transition from OPEN to CLOSED is triggered when a channel has been force-closed by the remote.
> It might be better to introduce a new state, for transactions that are being force closed, but for which we have no SPV confirmations. The transition from OPEN to that new state would be reversible.

Sounds reasonable.
Note that it in the case of a local force-close, the transition must not be reversible.

**Comment by ecdsa** [comment]
the transition must not be reversible in the case of a cooperative close, because `shutdown` has been sent.

in the case of a local force close, the server can lie about propagating the transaction, so I don't think it should be distinguished from a remote force close.

**Comment by SomberNight** [comment]
> in the case of a local force close, the server can lie about propagating the transaction, so I don't think it should be distinguished from a remote force close.

In that case we should try to broadcast the same tx again.

We must not transition back to OPEN, it's not safe to continue using that channel: if we send a new REVACK, and then the tx gets propagated, that tx is then a breach.

**Comment by ecdsa** [comment]
on a second thought, we might be able to handle that without introducing a new state. If we see an unconfirmed closing transaction that is neither a cooperative close, nor a local force close, we can simply keep the channel in the OPEN state, until that transaction is confirmed.
