### ISSUE TITLE
Bitcoin wallet wiped out

### ISSUE THREAD

**Issue by code4actory** [spesmilo/electrum#6029]
Hello,
Launched my electrum app today and realized that my coin has been wiped out. The last transaction initiated by me was on 2020-03-07 09:37, balance after tx 0.28360094,  and i pretty much did not check my wallet again up until today, but now all coins are gone, transferred to a wallet i do not recognize on 2020-03-08 17:21. Am using version 3.3.8 and i have never experienced this with electrum before. Please Help!

**Comment by ecdsa** [comment]
your seed has been compromised. 
there is not enough information in your post to investigate how it happened.

**Comment by code4actory** [comment]
But how did this happen, kept my seed secured, this is scary.

**Comment by code4actory** [comment]
https://blockstream.info/tx/1beff89fbfe49ceae56f39c31f3b304ddec6c663e97f68a9de091798f6bfa999

this is the block explorer

**Comment by ecdsa** [comment]
either you did not really keep your seed as secured as you think, or you downloaded malware, or your computer was otherwise compromised.

**Comment by longuserelec** [comment]
is it possible to get everything back! whole wallet is empty and i wrote the seed down on paper . and there"s not even transactions in the account anymore HELP!

**Comment by SomberNight** [comment]
@longuserelec see https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet
