### ISSUE TITLE
How to know the index of an address?

### ISSUE THREAD

**Issue by h2o10** [spesmilo/electrum#6034]
How to get the index of an address generated in bulk using `createnewaddress()`

**Comment by SomberNight** [comment]
Do you mean something like this? In the Qt console:
```
>> wallet.get_address_index("bc1qlt9l3x35u4u4xldvs5gw0rrwphznzr8mutc37p")
(0, 6)
```

**Comment by ysangkok** [comment]
@h2o10  btw, I think this question would be better on bitcoin.stackexchange.com . Note how the Electrum webpage says the issue tracker is not for support.
