### ISSUE TITLE
Electrum creates a change address sending 0 BTC

### ISSUE THREAD

**Issue by oitdmser** [spesmilo/electrum#6035]
I'm attempting to spend an entire UTXO. I set my sending amount such that $sending_amt + $fee_amt = UTXO. Electrum still creates a spend address, but with an amount of 0, which means the server rejects the transaction. 
<img width="951" alt="Screen Shot 2020-03-14 at 2 33 08 PM" src="https://user-images.githubusercontent.com/44953598/76690828-86c0bc80-6601-11ea-8e09-fc7aec4ed78a.png">

**Comment by SomberNight** [comment]
Please describe in detail what you are doing - what buttons are you clicking etc.
For example, did you click the "Max" button?

**Comment by SomberNight** [comment]
If you still have this wallet open, please run `network.relay_fee` in the Qt console.

**Comment by SomberNight** [comment]
I have a reasonable idea of what could have happened, so I have tried to fix that, but more information would still be nice to confirm my theory.

**Comment by oitdmser** [comment]
I went to the 'Coins' tab and right clicked a specific UTXO.
I entered the 'Pay to' address and adjusted my amount to be UTXO_amt - fee_amt. 
I manually entered my fee as calculated above, so that spend_amt + fee_amt = UTXO_amount
Clicked 'Preview'

I did not click the 'Max' button. In my experience that sends the sum of all UTXOs in the current wallet.

I'm running Electrum against my own ElectrumX server v 1.13 and Bitcoin Core node, with fees set to minimums. As per your question, `network.relay_fee `returns a value of "1".

**Comment by oitdmser** [comment]
In my case, shouldn't there be only one output to the UTXO? It seems like Electrum should catch this case where change_amt=0 and create a transaction with only 1 transaction output

**Comment by SomberNight** [comment]
> I did not click the 'Max' button. In my experience that sends the sum of all UTXOs in the current wallet.

"Max" will spend all UTXOs that are selected. (so all in wallet without coin selection; or if using coin selection, all selected)

> I'm running Electrum against my own ElectrumX server v 1.13 and Bitcoin Core node, with fees set to minimums. As per your question, network.relay_fee returns a value of "1".

We calculate the dust limit (used as a cutoff below which we don't create e.g. change outputs) based on the relay fee. The relay fee is coming from the connected server. In today's bitcoin network, the default (and hence widespread) relay fee is 1000 sat/KB. For some reason on your server it is 1 sat/KB instead (i.e. your node will accept really low feerate txns but the neighbours of your node will likely reject and not propagate them anyway).

The change in https://github.com/spesmilo/electrum/commit/a500db371db414e4235e0609d6c328aa99eb135f enforces that even if the connected server tells us a lower than 1000 sat/KB relay fee, we will use a value of 1000 sat/KB.

I had expected that the server you connected to reported a relay fee of 0 sat/KB, as then the client would calculate a dust limit of 0 sat, and hence keep 0 sat change outputs.
However this is not the case it seems.

**Comment by SomberNight** [comment]
>> As per your question, network.relay_fee returns a value of "1".

> I had expected that the server you connected to reported a relay fee of 0 sat/KB, as then the client would calculate a dust limit of 0 sat, and hence keep 0 sat change outputs.

So now I believe this is fixed in https://github.com/spesmilo/electrum/commit/510399d3d258fef76a390786ad447bba40a2871b
It was a rounding issue which in your specific case resulted in the client calculating a dust limit of 0 sat instead of 1 sat.
