### ISSUE TITLE
how electrum-client handle orphan blocks.

### ISSUE THREAD

**Issue by frndxyz** [spesmilo/electrum#6036]
i am running electrum for altcoin. when orphan block found by electrumx it does reorg.

but how electrum-client that orphan block once it received and recorded to db.

is there some kind of reorg there in client too.

in my case it create fork file on "forks" folder .

but orphaned block still exist in "blockchain_headers" file. which should be replace by original block?

appreciate some guidance/help.

**Comment by ecdsa** [comment]
please no altcoins here

**Comment by frndxyz** [comment]
> please no altcoins here

you have to understand that this issue is not related to altcoin.

**Comment by SomberNight** [comment]
Please try to explain the potential issue better then.

**Comment by frndxyz** [comment]
> Please try to explain the potential issue better then.

actual issue is when orphan block received it still store in DB file. i think it should be override by new block which in not orphaned once electrumx reorg.

**Comment by SomberNight** [comment]
https://en.bitcoin.it/wiki/Orphan_Block

We don't store orphan blocks. After a reorg, the server sends us a the tip of the new best chain, which the client will recognise to be an orphan but it will download its parents (the prev blocks) and then store that whole fork.
The "blockchain_headers" file contains the headers for the best (most work) chain, while the "forks" folder contains all other known forks.
