### ISSUE TITLE
Confusing behavior of `list_requests`

### ISSUE THREAD

**Issue by St333p** [spesmilo/electrum#6037]
Lightning's `list_requests` returns something I would not expect, would be nice to know if it's a bug or there is some reason for it to be like this:

```
alice list_requests --expired
[]
alice list_requests --pending
[
    {
        "amount": 42000,
        "amount_BTC": "0.00042",
        "exp": 3600,
        "invoice": "lnbcrt420u...2nt02wpgccpehpwnc",
        "message": "",
        "rhash": "635e31ae4c0786...cdc3f7442725dab0a34",
        "status": 0,
        "status_str": [
            1,
            "Expired"
        ],
        "time": 1584269182,
        "type": 2
    }
]
```

First of all I don't get the inconsistency of the field `'status'` with the `'status_str'`, where the first is 0 and the second is 1, but since the second has a string `'Expired'`, I would expect the invoice to be expired.

However, if I call the function with `--expired` the invoice doesn't show up, while it does with `--pending`. Can anybody clarify this behavior?

**Comment by ecdsa** [comment]
that was a bug, thanks for reporting
