### ISSUE TITLE
import/export channel backups

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6038]
I think we should be able to export channel backups and import them in another wallet file (instead of having file backups).

I have been testing a few things on mainnet.
 - in order to have a channel force closed, it is not sufficient to send an error message. typically, the peer disconnects, and reconnection is possible.  "MUST fail the channel" does not seem to imply force-close in that context.
 - it is possible to have a channel force-closed without sending a valid `per_commitment_point.` for that, it seems that all we need is (remote_node_id, our_privkey, channel_id, host, port). 

However, we probably want more from channel backups than just the ability to request a force close: 
 - if we force close, we will receive funds on an address that is not recoverable from seed. if the wallet file is lost during the CSV delay, we want the backup to let us sweep funds. this requires delayed_basepoint and per_commitment_point. 
 - In the future, a CSV will probably be added to `to_remote`. I do not know if we still want the to_remote pubkey to be 100% derived from seed in that case, because it implies deriving a new sequence of adresses. the alternative will be to derive it from the channel backup.

For those reasons, I think we should probably store the random seed that was used to create the channel, (or do something similar to what Eclair does, but this has drawbacks for hardware and watching-only wallets)

**Comment by SomberNight** [comment]
> In the future, a CSV will probably be added to to_remote. I do not know if we still want the to_remote pubkey to be 100% derived from seed in that case, because it implies deriving a new sequence of adresses. the alternative will be to derive it from the channel backup.

Btw note that AFAIK no hardware wallet can spend these kind of CSV-locked scripts atm. So we should keep all lightning keys in software, which implies independent from seed.

**Comment by ecdsa** [comment]
Note: here is a [new branch](/spesmilo/electrum/commits/channel_backups)

**Comment by ecdsa** [comment]
the branch was merged
