### ISSUE TITLE
Electrum not sending BTC

### ISSUE THREAD

**Issue by jbeek81** [spesmilo/electrum#6041]
Hi,

I've transferred a small amount of BTC to a specific address. The recipient needs 2 conformations, but after 1230 conformations the BTC still doesn't show on the chosen address?
Transaction id: 133eecb4cf499c6e90edc66f1db24c610815c554562c5f5122070086ad7d56f9

**Comment by AbdussamadA** [comment]
you can clearly [see](https://www.blockchain.com/btc/tx/133eecb4cf499c6e90edc66f1db24c610815c554562c5f5122070086ad7d56f9) that 0.00406946 BTC was sent to 398hzme9YveWvLw55dJv58w2StsfQQWqFp . is this the intended amount and the intended recipient's address? if yes then you should take it up with the recipient.

**Comment by jbeek81** [comment]
> you can clearly [see](https://www.blockchain.com/btc/tx/133eecb4cf499c6e90edc66f1db24c610815c554562c5f5122070086ad7d56f9) that 0.00406946 BTC was sent to 398hzme9YveWvLw55dJv58w2StsfQQWqFp . is this the intended amount and the intended recipient's address? if yes then you should take it up with the recipient.

The address belongs to a marketplace on the deepweb. According to a topic on reddit the owner of the marketplace did an exitscam. So i think i lost my money.
