### ISSUE TITLE
Warn multisig users to backup public keys (xpub/ypub/zpub)

### ISSUE THREAD

**Issue by andronoob** [spesmilo/electrum#6043]
P2SH or P2WSH requires (witness) redeem script to spend, which could be a pitfall, that the user might think losing one of multiple cosigning private keys (mnemonic words) **and the corresponding public keys** doesn't matter - on the contrary, without the knowledge of **all** the cosigning public keys, it won't be possible to spend from corresponding multisig wallet.

**Comment by SomberNight** [comment]
Yes indeed it would be nice to put a warning somewhere.
