### ISSUE TITLE
Need help with electrum seed being weird (im newbie)

### ISSUE THREAD

**Issue by prraa** [spesmilo/electrum#6045]
Hi, got this electrum wallet that i have full access to, but the strange thing is that my seed is not a 12 word pass unless its a lot of numbers and symbols. when i try to send away the money its says "Forbidden character 61 for base 58" what do i do? :// im reaally new to this soo yeah..

**Comment by bauerj** [comment]
Hey,

it looks like your wallet file got corrupted somehow. Please restore your wallet from seed.

**Comment by prraa** [comment]
Yeah that's one problem because i kinda lost track of the original seed (had it on usb stick that i lost)... Is there any other way?

**Comment by bauerj** [comment]
Please explain what exactly happened. Did you just open your wallet some day and it was in this broken state? Do you need to enter a password to open your wallet?
