### ISSUE TITLE
"script_error_messages" needs a fix

### ISSUE THREAD

**Issue by Coding-Enthusiast** [spesmilo/electrum#6052]
https://github.com/spesmilo/electrum/blob/7ac1cace7a7caaa0d0cc32a1cb0a60c0ddc4c132/electrum/network.py#L919  

This was [a wrong error message](https://github.com/bitcoin/bitcoin/issues/18411) in bitcoin core which was fixed in [18412](https://github.com/bitcoin/bitcoin/pull/18412) today.  
You may need to add a condition before returning the correct message for backward compatibility.   

    if serverMsg == "Only non-push operators allowed in signatures" or  == "Only push operators allowed in signatures"
    return "Only push operators allowed in signatures"
    else
    // line 938 to 940 as it was before:
      for substring in script_error_messages:
          if substring in server_msg:
              return substring

**Comment by SomberNight** [comment]
Thanks.

>  You may need to add a condition before returning the correct message for backward compatibility.

You are right that this would be the nice approach but it also makes the code a bit more complicated.

I don't think I've ever seen this error message except when I was writing new code to manually construct transactions. It does not happen for production releases. And if it happens for a dev, they can just look at the log that contains the original message.

So, I think it's fine to only handle the msg returned by updated bitcoind.
