### ISSUE TITLE
Very Large HD Wallet Indexes Used - How to recover funds?

### ISSUE THREAD

**Issue by Kyzcreig** [spesmilo/electrum#6061]
Relevant thread on Bitcoin talk:
https://bitcointalk.org/index.php?topic=5236641

How can I access HD wallet indexes starting at 1222333444 or some other large (>1 billion) index?

**Comment by SomberNight** [comment]
There is no support for this kind of behaviour. As you have found, the wallet will not find transactions paying to these large indices well beyond the gap limit. There isn't either an easy way to make the wallet code work with them without ugly hacks that would be only useful for your specific case.

Still, fear not, you have not lost these coins.
I have added a new RPC/CLI command in https://github.com/spesmilo/electrum/commit/900a7631cf3588147857688cb5f8efe11c4b2924: `getprivatekeyforpath`.
Like other commands, it can also be invoked from the Qt console.

Example with Qt console:
```
>> getprivatekeyforpath("m/0/1222333444")
"p2wpkh:cQ1mzjDVwi2hbbVhYATQRkonvzm2yNZRQ6B22q8bLWUn2D4zn8fF"
>> getprivatekeyforpath([0, 1222333444])
"p2wpkh:cQ1mzjDVwi2hbbVhYATQRkonvzm2yNZRQ6B22q8bLWUn2D4zn8fF"
```
You should get these ("WIF") private keys for all your high-indexed addresses, and either
- create a new imported wallet, from where you can spend them, or
- sweep them into an existing HD wallet you have

**Comment by Kyzcreig** [comment]
Excellent thank you! So, get the private keys, then sweep them up!
