### ISSUE TITLE
Cannot create wallet with multiple Trezors

### ISSUE THREAD

**Issue by matejcik** [spesmilo/electrum#6063]
to reproduce:

1. connect at least two Trezor devices
2. wipe one of them
2. start Electrum -> Create new wallet -> Standard wallet -> Use a hardware device
3. from the list of Trezors, choose the wiped one. Should be shown as "An unnamed Trezor" 
  ![image](https://user-images.githubusercontent.com/596073/78012679-a0723b80-7345-11ea-916a-a8fb8031187d.png)

4. Let the device generate seed
5. all parameters on default
6. finish process on Trezor
7. leave Script type and Derivation path parameters on default

**expected**:

"Encrypt wallet file" dialog shows up (this is what happens normally), then wallet is created.

**actual result**:

Electrum asks _again_ to "Please select which Trezor device to use."

The unnamed trezor is shown with empty name:
![image](https://user-images.githubusercontent.com/596073/78012753-bed83700-7345-11ea-86a6-f93f2df6dcbd.png)

when you select it, an error is shown: 'InstallWIzard' object has no attribute 'wallet'.

Wallet file is not created.

stack trace:
```
E | gui.qt.installwizard.InstallWizard | 
Traceback (most recent call last):
  File "/home/matejcik/projekty/prace/electrum/electrum/base_wizard.py", line 540, in create_wallet
    password = k.get_password_for_storage_encryption()
  File "/home/matejcik/projekty/prace/electrum/electrum/keystore.py", line 768, in get_password_for_storage_encryption
    client = self.plugin.get_client(self)
  File "/home/matejcik/projekty/prace/electrum/electrum/plugins/trezor/trezor.py", line 184, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/home/matejcik/projekty/prace/electrum/electrum/plugin.py", line 462, in client_for_keystore
    info = self.select_device(plugin, handler, keystore, devices)
  File "/home/matejcik/projekty/prace/electrum/electrum/plugin.py", line 584, in select_device
    if handler.win.wallet is not None:
AttributeError: 'InstallWizard' object has no attribute 'wallet'
```

**Comment by matejcik** [comment]
Update: same thing happens when you fill out a label. The "unlabeled" thing was a red herring, what confused me is the incorrect name being shown on the second "choose trezor" dialog.

**Comment by SomberNight** [comment]
o_O
Thanks for the report.
I think there are several underlying issues here.
I think I've fixed the trace itself in https://github.com/spesmilo/electrum/commit/6760c3f252797d137ebceee5a71a7a86025f12ad

**Comment by SomberNight** [comment]
> expected:
> "Encrypt wallet file" dialog shows up (this is what happens normally), then wallet is created.
> 
> actual result:
> Electrum asks again to "Please select which Trezor device to use."

I believe this part is due to https://github.com/spesmilo/electrum/issues/5759
(label is used to select if there are multiple unpaired devices from same manufacturer, but a None label is special-cased and not used, and then the fallback is manual-selection)

**Comment by matejcik** [comment]
> > expected:
> > "Encrypt wallet file" dialog shows up (this is what happens normally), then wallet is created.
> > actual result:
> > Electrum asks again to "Please select which Trezor device to use."
> 
> I believe this part is due to #5759
> (label is used to select if there are multiple unpaired devices from same manufacturer, but a None label is special-cased and not used, and then the fallback is manual-selection)

That is in the "unlabeled" case though.
When you specify a label in the wallet setup phase, the same thing happens. Presumably the new label is not properly registered at that time?

**Comment by SomberNight** [comment]
Yes, you were right.

All right, hopefully it's all fixed now. :P
