### ISSUE TITLE
Electrum not connected

### ISSUE THREAD

**Issue by MrWarmth** [spesmilo/electrum#6073]
After trying for an hour to get electrum 4.0.0 to work, I ask for your guidance. 

Server is showing red, not connecting.
I watched videos on it, tried to click on and off on proxy, auto pick server, other servers , then this: fortress.qtornado.com:50002 which is impossible to select because it auto replaces it. 
Checked for updates but it doesn´t even connect to it.

I don´t understand it. 
If you have any idea, please let me know. 
I understand I have done nothing for the software and it´s even free to use, but I guess it is why it will be hard for "normal user" to mass buy bitcoin, it´s not easy to buy, all these setups then glitches, not user friendly overall, which is somewhat sad it is this way, but I guess it keeps things safe and encrypted.

Cheers, and thanks in advance
Alain

**Comment by MrWarmth** [comment]
![2020-04-07_130923](https://user-images.githubusercontent.com/63295054/78667550-112ed000-78d1-11ea-8f89-c49c6711be21.jpg)

**Comment by SomberNight** [comment]
> After trying for an hour to get electrum 4.0.0 to work, I ask for your guidance.

Where did you download that from?

The latest official release is 3.3.8.

**Comment by MrWarmth** [comment]
![delete this](https://user-images.githubusercontent.com/63295054/78672485-9c5f9400-78d8-11ea-8446-f662f199df30.jpg)
_

> > After trying for an hour to get electrum 4.0.0 to work, I ask for your guidance.
> 
> Where did you download that from?
> 
> The latest official release is 3.3.8.

I suspect I did it from the site. Maybe it was a beta release I don´t remember, but it was a while ago.

**Comment by SomberNight** [comment]
No, you have most definitely downloaded malware. There was never a release that had "4.0.0" as version string, but there are some known malware that use it.

**Comment by MrWarmth** [comment]
I still have the folder, but I have also installed tha latest 3.3.8 now. 
Considering they share files in AppData folder since they open the same transactions I have made etc. 

I have changed my password, but if it was malware, can they access it anyway since they could have my seed now and so they would have root access to it ?!

Thanks in advance if you can advise me to create a new account or keeping it with a changed password is enough ? .

THanks Alain

**Comment by MrWarmth** [comment]
> No, you have most definitely downloaded malware. There was never a release that had "4.0.0" as version string, but there are some known malware that use it.

I still have the folder, but I have also installed tha latest 3.3.8 now.
Considering they share files in AppData folder since they open the same transactions I have made etc.

I have changed my password, but if it was malware, can they access it anyway since they could have my seed now and so they would have root access to it ?!

Thanks in advance if you can advise me to create a new account or keeping it with a changed password is enough ? .

THanks Alain

**Comment by SomberNight** [comment]
As the bare minimum, you should assume that the seed of any wallets you have opened with the malware is now compromised.
You should create new seeds and transfer your coins, if they haven't been stolen yet.

The prudent approach would be to consider the whole machine to be compromised and to reinstall the operating system.

**Comment by MrWarmth** [comment]
> As the bare minimum, you should assume that the seed of any wallets you have opened with the malware is now compromised.
> You should create new seeds and transfer your coins, if they haven't been stolen yet.
> 
> The prudent approach would be to consider the whole machine to be compromised and to reinstall the operating system.

Thank you very much for your input.
