### ISSUE TITLE
Electrum won't connect to onion server

### ISSUE THREAD

**Issue by otaviobps** [spesmilo/electrum#6074]
I'm running Electrs on my server, over Tor. I can connect to it if I launch Tor on my client PC and configure Electrum to use SOCKS5.

I have, however, a VPN server that routes all traffic to the Tor network. The scheme is this:

`VPN Client -> VPN Server -> Tor -> Internet`

DNS and iptables are all configured correctly on the server, and I forward all traffic on my client PC to the Tor network. In other words, I can access the Tor network running just my VPN on my client PC.

Electrum, however, won't connect to my Electrs server over Tor. What I did was disable the SOCKS5 option, and set the server address my .onion server address. Since my VPN is routing all traffic thru Tor, Electrum should be able to connect to the onion server.

How can I see the log? I'm running on MacOS

**Comment by SomberNight** [comment]
> How can I see the log?

https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging
