### ISSUE TITLE
Dev Build from source version failing to start

### ISSUE THREAD

**Issue by OptimusOpus** [spesmilo/electrum#6078]
I am trying to build the dev version Electrum-4.0.0a0 from source. The installation using the provided instructions went fine however when I try to run it either via `electrum daemon status` or with imports `from electrum import bitcoin, crypto, ecc, util, transaction` I get 
```FileNotFoundError: [Errno 2] No such file or directory: '/home/t/lcs/electrum-test/venv/lib/python3.6/site-packages/electrum/lnwire/peer_wire.csv'```. I am on Ubuntu 18.04 and chose pycryptodomex. How can I generate `peer_wire.csv`? I currently have just rolled back to commit `3b7299bfde92262c0cf089c0692a3ceaaba69b95` which is working fine for me.

Thanks

**Comment by SomberNight** [comment]
Should work now.

**Comment by OptimusOpus** [comment]
Perfect, many thanks
