### ISSUE TITLE
Where does the electrum script/executable get installed on Linux?

### ISSUE THREAD

**Issue by Lightning076** [spesmilo/electrum#6082]
I've just spend two hours searching the web to find out that 'python3 -m pip install --user Electrum-3.3.8.tar.gz' installs the executable in ~/.local/bin

I think it should be mentioned on https://electrum.org/#download (or at the end of the installation script) ?

And why electrum.org does not have a link to "requested features" so I should not have to find a place (here) on the web to complain about ?

**Comment by SomberNight** [comment]
> I've just spend two hours searching the web to find out that 'python3 -m pip install --user Electrum-3.3.8.tar.gz' installs the executable in ~/.local/bin

Was this directory not in your `$PATH`?
(Or did you not know what the name of the executable is?)

`~/.local/bin` is on PATH by default on many distributions but it seems not all of them.
Particularly older debian-based distros won't have it by default (see https://github.com/pypa/pip/issues/3813)

We will try to update the docs to reflect this.

You are the first to complain about this. Bug reports are welcome, however only in a respectful tone.
I have changed the language in your comment for future readers' peace of mind.
