### ISSUE TITLE
Allow specifying SSL server fingerprint

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#6084]
It would be great if we could ensure an SSL connection is not being MITM'd on initial connection by specifying a known fingerprint.

E.g:

```
$ electrum --server bitcoin.lukechilds.co:50002:s:ED1FE28B21A5943A8810747B2A6DDFC0E3089115D6205125E5C4D3EE8E126F80
```

The above connection would fail if bitcoin.lukechilds.co:50002 doesn't respond with a certificate with a matching fingerprint.

I'm aware electrum pins certificates in `~/.electrum/certs`, however this is only ensures we can't be MITM'd after the initial connection has been made and manually verified. It doesn't guarantee a secure initial connection.

Using a fingerprint as part of the server URI guarantees a secure initial connection and is much more convenient for configuration and safely sharing between users.

For example, asking my friends and family to securely connect to my server is currently quite awkward and error prone:

1. Find your electrum config dir.
2. Create a file inside it called `./certs/bitcoin.lukechilds.co`.
3. Copy the contents of my certificate file into it:
```
-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIUL0ou+8rSEE17I9yGq7NeesxhgdkwDQYJKoZIhvcNAQEL
BQAwFDESMBAGA1UECgwJRWxlY3RydW1YMB4XDTE5MTExMTA0MzgxOFoXDTIwMTEx
MDA0MzgxOFowFDESMBAGA1UECgwJRWxlY3RydW1YMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAvJfIOHkhW7NTGYg4cFx7g2OL7TjxKq3NshZ1PpzEmHcg
AbCyrrOEfPp02CL43Q1MUsZZrKkJo47zo3vm93XPfENS3v/j96x5uaL3Gt71rp00
TVKkocjpz5SwIPNrm00kbBtJzGnIw9mhr89Iaw2sDeH7pSZQNDOUo+ENs6jkwA28
kOxFdt6tyGaIic19mnvnHdVM0uHja/DUSA/6lEG/eKxL5skcXw9R3Hwmw/7yyW1R
V0ZDVe09juer95it7R1UNWApKXbg8XYI+4F520tOsLf0Xjvp5K5DNms4lTXy2yHr
xGVLhdqUboy97vPNT/SW31fntwny0KpOwDnEMPzEbQIDAQABo1MwUTAdBgNVHQ4E
FgQUDlsfflhbRtoK4JN/af0hbQZ7HO0wHwYDVR0jBBgwFoAUDlsfflhbRtoK4JN/
af0hbQZ7HO0wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWwUo
OJA+aw0C9IqCTRWTeqjs4QDuC5oyBui/+nrSlCtYvDFWsjYqtvBWMkxRFUU9SQlR
8NOm7U/ly0+vLsO6onlye05KaSpX1a/2XjF3uwGBNUInoPxfUEeYJmvKZu9ch5pT
8XJb4cRAtKKkhWVdh618QEMPOfhaDc1QuU+AO9vfTQg9liIvVIYF7PDm8pwYhtXp
Skq5V4YPiM8ESplDfOwUVcf0uu1MhBVzmGA/Zwp7ReVtSe1FdUMNldTbYISJIc3s
Nsf62cmm6yh4twg5c0VYiW/HGPsR8/u/PdxjFLx0LeMdVMNGKrIgX74NaT4MolOU
88EAgVz/eYlJYKKIMw==
-----END CERTIFICATE-----
```
4. Run `electrum --server bitcoin.lukechilds.co:50002:s`.

I need to distribute both my connection string and my SSL certificate, the user also needs to understand how to correctly locate their Electrum config dir and create the files. Not trivial for people who aren't too tech savvy.

Supporting fingerprints would give the same security via just:

1. Run `electrum --server bitcoin.lukechilds.co:50002:s:ED1FE28B21A5943A8810747B2A6DDFC0E3089115D6205125E5C4D3EE8E126F80`.

**Comment by lukechilds** [comment]
If you're interested in accepting this change I'd be willing to have a go at implementing it.

**Comment by lukechilds** [comment]
Ok, one major issue is that it seems current versions of Electrum choke on the connection string and fall back to a random server.

```
W/n | network | failed to parse server-string; falling back to random.
```

Firstly I would suggest to change this behaviour. That means if someone mis-types a connection string to their own server which makes it unparsable, Electrum will fall back to using a random public server and potentially dox all of their UTXOs and their IP.

Instead if the connection string cannot be parsed Electrum should just fail with an error so the user can fix it.

I've created a separate issue to discuss this here: https://github.com/spesmilo/electrum/issues/6085

This could be resolved by

**Comment by lukechilds** [comment]
Ok, one major issue is that it seems current versions of Electrum choke on the connection string when a fingerprint is added and fall back to a random server.

```
W/n | network | failed to parse server-string; falling back to random.
```

Firstly I would suggest to change this behaviour. The current behaviour means if someone incorrectly types a connection string to their own server which makes it unparsable, Electrum will fall back to using a random public server and potentially dox all of their UTXOs and their IP.

Instead if the connection string cannot be parsed Electrum should just fail with an error so the user can fix it.

I've created a separate issue to discuss this further here: https://github.com/spesmilo/electrum/issues/6085

In regards to implementing fingerprint checking, this could be resolved by just specifying the server fingerprint in a separate argument.

E.g:

```
$ electrum --server bitcoin.lukechilds.co:50002:s --server-fingerprint ED1FE28B21A5943A8810747B2A6DDFC0E3089115D6205125E5C4D3EE8E126F80
```

This also has desirable behaviour of failing hard on old unsupported versions of Electrum as opposed to connecting to a random server or connecting to the specified server but without fingerprint validation:

```
electrum: error: unrecognized arguments: --server-fingerprint
```

**Comment by SomberNight** [comment]
> In regards to implementing fingerprint checking, this could be resolved by just specifying the server fingerprint in a separate argument.
E.g:
`$ electrum --server bitcoin.lukechilds.co:50002:s --server-fingerprint ED1FE28B21A5943A8810747B2A6DDFC0E3089115D6205125E5C4D3EE8E126F80`

> If you're interested in accepting this proposal I'd be willing to have a go at implementing it.

Sure, adding it as a CLI option like that does not really hurt anyone, so if it has a usecase, why not.

Some questions though:
1. How is the server op supposed to learn their fingerprint in the first place?
2. Does this only apply to self-signed certs? What if the server has a CA-signed cert?

**Comment by lukechilds** [comment]
>How is the server op supposed to learn their fingerprint in the first place?

**If you run a server**

First they generate their SSL cert:

```
$ openssl req -newkey rsa:2048 -sha256 -nodes -x509 -days 365 -subj "/O=ElectrumX" -keyout "electrumx.key" -out "electrumx.crt"
Generating a 2048 bit RSA private key
..............+++
.....................................................................................................................................................................+++
writing new private key to 'electrumx.key'
-----
```

Then they calculate the fingerprint:

```
$ openssl x509 -noout -fingerprint -sha256 -inform pem -in electrumx.crt
SHA256 Fingerprint=33:92:B9:37:94:7E:A5:BA:63:A9:0D:6D:60:E6:62:C0:D4:97:4E:93:6A:59:3F:4E:DD:B7:23:3B:88:8D:8D:A5
```

Now they can use that fingerprint to connect from any device without risk of MITM, as well as distribute it to friends and family who can also connect without risk of MITM.

>Does this only apply to self-signed certs? What if the server has a CA-signed cert?

You could do it with either, although I'm not sure it makes much sense with CA certs. CA certs are often have a relatively short expiration date and so are rotated quite regularly. If the cert is rotated every three months and you were connecting with `--server-fingerprint` it would mean Electrum would refuse to connect every three months. You'd have to manually update the fingerprint each time which then increases the chance of communicating the fingerprint over an insecure channel which could lead to a MITM attack defeating the purpose of the feature.

Self signed certs are typically issued with very long expiry dates and used for the lifetime of the service. So locking the connection down to a single fingerprint/cert makes much more sense.

That said, we definitely shouldn't ignore the `--server-fingerprint` option when connecting to a server with a CA cert. There may be people who want to verify the fingerprint of a CA cert and it would be dangerous to silently fail in this case. I just wouldn't expect a lot of people to do that.

**Comment by SomberNight** [comment]
> > Does this only apply to self-signed certs? What if the server has a CA-signed cert?

> You could do it with either, although I'm not sure it makes much sense with CA certs. 

Yes I agree.

> That said, we definitely shouldn't ignore the --server-fingerprint option when connecting to a server with a CA cert. 

Indeed I meant what to do if a user does provide a fingerprint and the cert turns out to be a CA-cert.
I think we should verify in this case too, to make the behaviour consistent.
Also, consider a MitM by a state level attacker who controls a CA.
If the server op sets up a self-signed cert and gives out a fingerprint of that to the user; and then the user provides the fingerprint to the client and gets presented with a CA-signed cert, that cert should probably be rejected.

**Comment by lukechilds** [comment]
>If the server op sets up a self-signed cert and gives out a fingerprint of that to the user; and then the user provides the fingerprint to the client and gets presented with a CA-signed cert, that cert should probably be rejected.

Yes, definitely.

Ok great, I will have a go at putting a PR together.
