### ISSUE TITLE
Don't fall back to a random public server if the connection string fails to parse

### ISSUE THREAD

**Issue by lukechilds** [spesmilo/electrum#6085]
If Electrum cannot parse the connection string it falls back to a random public server:

```
W/n | network | failed to parse server-string; falling back to random.
```

I don't think this is desirable behaviour. This means if a user incorrectly types a connection string to their own server which makes it unparsable, Electrum will fall back to using a random public server and potentially dox all of their UTXOs and their IP.

Consider the following:

1. User has a local Electrum server they want to connect to for improved privacy.
2. User starts Electrum with `electrum --server localhost:50001:t:`.
3. The typo (trailing `:`) means Electrum will fail to parse and fall back to a random public server.
4. Electrum proceeds to send all of the users addresses and their IP to a random public server.
5. The user is not made aware they are not connected to their own server and are broadcasting everything to a 3rd party if they don't manually check console logs or the network settings in the GUI.

Instead, if the connection string cannot be parsed Electrum, should just fail with an error so the user can fix it and avoid unexpected behaviour and potential major privacy leaks.

**Comment by lukechilds** [comment]
Related comment: https://github.com/spesmilo/electrum/issues/6084#issuecomment-613220016

**Comment by h2o10** [comment]
how it behaves if user species `--oneserver`?

**Comment by ecdsa** [comment]
indeed that is not desirable.
iirc the purpose of that fallback is to deal with corrupt config files.
I think we can remove it.
