### ISSUE TITLE
Not work QR code

### ISSUE THREAD

**Issue by DigitalMonster555** [spesmilo/electrum#6089]
Not work import TX by QR code on big transaction, content many address, e.g. 10 on Android app for sign second cosigner. How to sign such TX on Android app?
P.S. Send to cosigner pool not work on android app also

**Comment by SomberNight** [comment]
> Not work import TX by QR code on big transaction, content many address, e.g. 10

Yes, QR codes have a max size. They can only encode around 3 kilobytes of data.

> How to sign such TX on Android app?

You can copy-paste transactions as text.
When you have the raw tx (text) on your clipboard, just click "Paste" in the app.
