### ISSUE TITLE
Generating address betond gap limit using json rpc

### ISSUE THREAD

**Issue by FIVIL** [spesmilo/electrum#6090]
Hi, I was wondering how can I generate btc addresses beyond gap limit using electrum json rpc? 
In the documentation it is mentioned that using python console and by passing 'false' it is possible to generate address beyond gap limit. However, I could not find how to do so using json-rpc. 
Unfortunately, The documentation for json-rpc seems really immature and incomplete.

**Comment by SomberNight** [comment]
You can use the `createnewaddress` address command.

**Comment by FIVIL** [comment]
@SomberNight I am using this command in json-rpc mode. however, it does not generate address beyond the gap limit, I dont know maybe there is a switch or parameter that I should pass in??

**Comment by ecdsa** [comment]
yes it does. the doc even says it: 
"Create a new receiving address, beyond the gap limit of the wallet"
