### ISSUE TITLE
Commandline Binary

### ISSUE THREAD

**Issue by itsMikeLowrey** [spesmilo/electrum#6102]
I am looking for a way to create a command line binary of electrum using pyinstaller. I would like to be able to create a binary that could be executed in  a similar fashion to run_electrum, but dosen't require python to be installed on the machine that runs the binary. I have been trying to create this with pyinstaller, but I have run into several issues that make it seem like this method isn't the best. Is there a better way to accomplish my goals with electrum? Is it possible to do this with pyinstaller?

**Comment by itsMikeLowrey** [comment]
I have tried bulding run_electrum with pyinstaller with this command:
`pyinstaller run_electrum --hidden-import=libsecp256k1.0.dylib --onefile`
It gives me this error though 
`libsecp256k1 library failed to load. exceptions: [PyInstallerImportError("Failed to load dynlib/dll '/var/folders/l4/v0kcg3n11fq2mkqcxsplpnhw0000gn/T/_MEI737tSp/electrum/libsecp256k1.0.dylib'. Most probably this dynlib/dll was not found when the application was frozen."), PyInstallerImportError("Failed to load dynlib/dll 'libsecp256k1.0.dylib'. Most probably this dynlib/dll was not found when the application was frozen.")]
Error: Failed to load libsecp256k1.`
I am unsure how to correct this issue and I am not really sure if electrum commandline is able to be bundled up with pyinstaller.

**Comment by itsMikeLowrey** [comment]
If I use the latest release branch I avoid all of the warnings that were coming up with pyinstaller. At the time of writing this  that would be 3.3.38 from commit e81f4bdcd11a072e7c4f38fb1c7eec19c2f7e1a8. I have built it for mac and it works fine following the standard pyinstaller way of building an executable. Ill try and build for windows at a later date and update this thread if I run into any issues.

**Comment by SomberNight** [comment]
> I would like to be able to create a binary that could be executed in a similar fashion to run_electrum, but dosen't require python to be installed on the machine that runs the binary

I don't really follow. The build scripts in the repo that are using pyinstaller (Win and macOS builds) are also building binaries that do not require python (or almost anything really) to already be installed on the host.

**Comment by itsMikeLowrey** [comment]
Thank you so much for the response. I was unaware that I could unpack the dmg from the release page and it had a binary  in the contents file. Your response made me look at it again, thank you o much.
