### ISSUE TITLE
Trezor Model T firmware change for passphrases

### ISSUE THREAD

**Issue by Saicere** [spesmilo/electrum#6104]
The latest firmware for the Trezor T ([2.3.0 changelog](https://blog.trezor.io/details-of-firmware-updates-for-trezor-one-version-1-9-0-and-trezor-model-t-version-2-3-0-46deb141fc09)) alters how it interacts with passphrases. Previously when passphrases were enabled, the Trezor itself would prompt whether to enter the passphrase on the device or the host. Now, the user application is supposed to prompt whether or not the passphase should be entered on the device or the host.

Unfortunately, Electrum does not seem to support this and proceeds to ask directly for a passphrase, which means it is no longer possible to enter a passphrase on the device. Obviously, entering a passphrase on the host is much less secure than entering it on the device, so hopefully it will be updated to fully support the new firmware.

Note that the Trezor One never supported entering a passphrase on the device, and is unlikely to be affected by anything here.

**Comment by SomberNight** [comment]
This is already fixed on master (since https://github.com/spesmilo/electrum/pull/6064), and will be in the next release.
