### ISSUE TITLE
Address generated and btc sent, tails updated now address not mine

### ISSUE THREAD

**Issue by pezzzzzzz** [spesmilo/electrum#6110]
looking for some help... I created a new address bc1qdzhk4vsh0zgc7ch0n34phpqdwl0f43k6q4rlq3, sent some coins to the address, tails updated and restarted and now the coins in the address but the address is not linked to my seeded wallet. Any suggestions?

**Comment by ROSAISS81** [comment]
cambialas a otro nuevo elimina por completo el problema desde la raiz si
algo no funciona lo mejor es quitar el problema no de la rama sino
seguira generando problemas o perdidas es mejor quitarlo creo yo
rosaiselaperez@gmail.com rosa Isela perez martinez

**Comment by lastfrontier999** [comment]
You still seeking help   ???


I’m 57 single and will pay you money if we can meet so I may eat and lick
your pussy

**Comment by SomberNight** [comment]
> but the address is not linked to my seeded wallet. 

Why do you think the address is unrelated to the wallet?
Did you get the address from the wallet in the first place? But then it disappeared from the wallet?

Did you recreate the wallet from seed in the meantime?
(If not, try that.)
Or are you using persistence on Tails?

Please give more details re the timeline of events.

**Comment by ecdsa** [comment]
closing, user did not answer
