### ISSUE TITLE
16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation). Code:-26

### ISSUE THREAD

**Issue by princehuios** [spesmilo/electrum#6117]
16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation). Code:-26
i created a wallet and wanted to do a transaction.
but when it was time to broadcast the transaction i got the above

**Comment by SomberNight** [comment]
dupe of https://github.com/spesmilo/electrum/issues/6118
and https://github.com/spesmilo/electrum/issues/6116
