### ISSUE TITLE
An error occured: 16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation). Code:-26

### ISSUE THREAD

**Issue by princehuios** [spesmilo/electrum#6118]
I initiated a transaction on action coin block chain using https://coinbin.actioncoin.com/
the sending address :RCpP5UAgverL2RXtwaf8a9hJaaQMwPTwC7
receiving address: RFExtoZCqma9KF9qWbuAmmiZL2tmBdLjG8
when i wanted to broadcast the transaction i got the error above.
i am attaching screen shots of all steps so that you can see how to help me.
!Image 2020-04-26 at 7 48 10 PM](https://user-images.githubusercontent.com/39422213/80317234-799b0e00-87fa-11ea-9080-30aa68178de3.jpeg)
Image 2020-04-26 at 7 53 50 PM](https://user-images.githubusercontent.com/39422213/80317237-7c95fe80-87fa-11ea-90d4-923338d9d420.jpeg)
 Image 2020-04-26 at 7 54 55 PM](https://user-images.githubusercontent.com/39422213/80317239-7e5fc200-87fa-11ea-8304-7eab41aa0006.jpeg)
Image 2020-04-26 at 7 56 28 PM](https://user-images.githubusercontent.com/39422213/80317241-80c21c00-87fa-11ea-9416-f5314cd4e567.jpeg)
 Image 2020-04-26 at 7 57 32 PM](https://user-images.githubusercontent.com/39422213/80317242-828bdf80-87fa-11ea-9678-0a11078ac62d.jpeg)
Image 2020-04-26 at 8 00 28 PM](https://user-images.githubusercontent.com/39422213/80317244-84ee3980-87fa-11ea-80f4-3266ee1cc5d6.jpeg)
Image 2020-04-26 at 8 00 57 PM](https://user-images.githubusercontent.com/39422213/80317246-87509380-87fa-11ea-8bec-911979fab6df.jpeg)

Thank you for your support

**Comment by SomberNight** [comment]
We don't provide support for altcoins, and further it does not even look like you are using Electrum in the first place.
