### ISSUE TITLE
BTC transfer problem

### ISSUE THREAD

**Issue by fjcv2020** [spesmilo/electrum#6119]
Hello,

I sent BTC copying the address but they didn't receive them. Could I receive assistance about it? The hash is: 349ae4408041bd19b0ab3907e18e7eee19185710a5c7597d1756dd5f5fea32cb 
The bc1qcygs9dl4pqw6atc4yqudrzd76p3r9cp6xp2kny was not the target address I think. Maybe a troyan? How could I fix this?

Thank You.

**Comment by ecdsa** [comment]
indeed, probably a trojan. 
please understand that this website is not a support ticket system; it is for bug reports.
