### ISSUE TITLE
add 'spike buffer' to channel reserve

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6121]
see https://github.com/lightningnetwork/lightning-rfc/pull/740

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/commit/e59eb147c04572a313853e19b8c0e58416eb452f

(and related changes in https://github.com/spesmilo/electrum/commit/7fccd4fc5e0044d35b4cf717b1fc0137b6321b0e and https://github.com/spesmilo/electrum/commit/ccf50dc98087f756aa6f94ad680a06a9260cc6a3)

**Comment by ecdsa** [comment]
thanks!
