### ISSUE TITLE
Extract HTLC preimage from on-chain tx

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6122]
Consider multi-hop payment: Alice -> Bob -> Carol -> Dave.

Two scenarios:
1. Bob drops on-chain with HTLC output in ctx.
2. Alice drops on-chain with HTLC output in ctx.

Bob uses preimage to spend HTLC.

-----

Need to implement:
Alice (electrum) should extract preimage from on-chain txn, and consider the invoice paid.

**Comment by SomberNight** [comment]
Note that this functionality is security-critical for a forwarding node.

**Comment by ecdsa** [comment]
related: f53a10084da027c69e7108702cb3d89613aa5965

**Comment by ecdsa** [comment]
@SomberNight reopening in light of your comments. please suggest fixes.

**Comment by ecdsa** [comment]
that should be fixed now, see d7b853f2716acb2808278e552987bf598821a4e4
