### ISSUE TITLE
improve routing error handling: malicious/faulty nodes can keep sending soft errors indefinitely

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6124]
When trying to send a lightning payment, if we receive an error, atm we either
- ban an edge (~until app restart), or
- if there is a channel update in the error, we apply that

https://github.com/spesmilo/electrum/blob/ab5338b46b78152eb0f430837133ffd1ed855783/electrum/lnworker.py#L908-L916

Let's call the latter type of errors a soft error.

-----

The issue with this is that if a remote node deliberately keeps sending soft errors, it might get us "stuck" - as in we would keep retrying the same route.

**Comment by SomberNight** [comment]
We could solve this with more granular error-handling.
E.g. have some kind of banscore, which gets increased on all types of errors (possibly with different amounts). It could get decreased on successful payments for all edges involved in final route. It could also decrease over time. We don't necessarily need to persist this (for now?).

**Comment by SomberNight** [comment]
Relatedly, if `lnworker.handle_error_code_from_failed_htlc` raises (due to malformed contents in the error for instance), then we should ban the whole node. (atm nothing is banned - the exception is not handled well)

**Comment by ecdsa** [comment]
another related issue is that we currently reset the blacklist only when the client is restarted.
maybe we should use a delay instead

**Comment by ecdsa** [comment]
we could base our blacklisting plicy on the time difference between channel updates. In the scenario you describe, a malicious/faulty node would send updates with timestamps that are close to eachother.

**Comment by ecdsa** [comment]
A simple fix could be to require a minimum interval between channel updates, at the channel_db level. For example: 
```python
@@ -417,7 +417,7 @@ class ChannelDB(SqlDB):
         short_channel_id = ShortChannelID(payload['short_channel_id'])
         key = (start_node, short_channel_id)
         old_policy = self._policies.get(key)
-        if old_policy and timestamp <= old_policy.timestamp:
+        if old_policy and timestamp <= old_policy.timestamp + 60:
             return UpdateStatus.DEPRECATED
         if verify:
             self.verify_channel_update(payload)
```
This might result in us rejecting some legit updates, as BOLT7 does not seem to include any spam protection of that kind.

However, the issue of spam has been discussed on the mailing list, and c-lightning takes care not to generate channel_updates less than 300 seconds apart: https://lists.linuxfoundation.org/pipermail/lightning-dev/2019-September/002134.html

**Comment by ecdsa** [comment]
note that the above fix is in itself not sufficient against a malicious node, we also need to implement the following (bolt7):
> if the timestamp is unreasonably far in the future:
>     MAY discard the channel_update.
