### ISSUE TITLE
ln funding tx should not be allowed to be fee-bumped or coinjoined

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6127]
LN funding tx should not be allowed to be coinjoined (note: also "bump fee")
(e.g. xpub-only wallet)

  - maybe this is already solved via "psbt_only_widgets" ?
    - or maybe not, as for xpub-only wallet, funding tx will be visible while partial
  - note that from "Combine" dropdown, "merge sigs from" is useful... (but not "join")

-----

All changes to a funding tx between sending its txid to the remote node, and broadcasting it (well, getting it mined), that affects the txid are dangerous and should not be allowed.

**Comment by ecdsa** [comment]
what is the scenario where "bump fee" would become relevant?

**Comment by SomberNight** [comment]
I guess "bump fee" is already not reachable for a funding tx, though I think it's sort of accidental.

E.g. if we allowed fee-bumping non-RBF "local" transactions, which to me sounds like a change we might decide to make for whatever reason, we might forgot to consider this case (funding tx).
https://github.com/spesmilo/electrum/blob/6f7a4ab048bbdb4215ae47f206a878aa6215bf31/electrum/wallet.py#L528-L531

But re adding new inputs/outputs, one possible flow to trigger that:
- use watch-only wallet, with LN enabled
- in that watch-only wallet:
  - start opening a channel
  - tx now appears as "local" tx in history
  - in tx details, Combine>"Join inputs/outputs"

**Comment by ecdsa** [comment]
One solution would be to disable Coinjoin for transactions that are not RBF. 
That would be consistent with the assumption that 'final' transaction are not malleable.
