### ISSUE TITLE
maybe adapt Mac build script to macOS 10.15 madness

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6128]
macOS 10.15 "Catalina" continues the walled garden lock-down tradition of Apple,
in turn making things harder for developers, again.

see https://github.com/pyinstaller/pyinstaller/issues/4629

>  You can't notarize the app if it's not hardened runtime
> and you can't distribute the app to Catalina users if it's not notarized

-----
AFAIU:

- to make the app run on macOS 10.15
    - when signing the app, we need to enable hardened runtime
    - we need to "notarize" the app with Apple's central server
- during the build, to enable hardened runtime, we need to build on at least macOS 10.14
    - however this means the app will not run on older macOS

-----
Options:
1. We could build two binaries, a modern and a legacy/compat one.
    The modern binary would be built on either 10.14 or 10.15, and we would try to comply with all the maddeningly more and more complex quirks they want.
    The legacy binary would be built on 10.11 (as now), without any of the new requirements they impose.
    Then, users of modern Macs would use the modern binary, and users of older Macs could use the legacy binary.

2. We could build just a modern binary, that only runs on new Macs.

3. We could build just a legacy binary which is effectively what our current build script does. This runs on old Macs; and can be made to run on modern Macs too, at least for now, but the users need to go deep into the system settings every time they want to run such a binary for the first time.

4. We could even stop building binaries for MacOS completely because what Apple is doing is increasingly frustrating and is taking up non-negligible time of ours.

**Comment by ecdsa** [comment]
if we choose option 2, what is the lowest version it would run on?
note: https://gs.statcounter.com/macos-version-market-share/desktop/worldwide

**Comment by SomberNight** [comment]
If we build on macOS 10.14, I don't think there is any guarantee that it runs on older Macs than that.
In practice I have tested now, and such a binary also seems to run on macOS 10.13.

**Comment by ecdsa** [comment]
I think option 2 is reasonable.
option 1 is adding too much complexity.
