### ISSUE TITLE
Bitcoins stolen

### ISSUE THREAD

**Issue by DarkRedman** [spesmilo/electrum#613]
All the bitcoins I receive or I got are resent back (by Electrum client) to the bitcoin senders.

This is a huge security bug, so I've no bitcoin left!

I think this should be fixed. Meanwhile I should another bitcoin client I can trust.

![capture du 2014-03-10 04 01 52](https://f.cloud.github.com/assets/367844/2370316/899d37dc-a800-11e3-9cc0-c2be3dbb814b.png)

**Comment by purestmoney** [comment]
please help me, am about to be scammed too
