### ISSUE TITLE
Cold Storage Improvements - Air Gapped

### ISSUE THREAD

**Issue by crohkohl** [spesmilo/electrum#6130]
I would like to propose a feature to improve the cold storage functionality.
Right now it is quite time-consuming: unsigned tx export -> usb -> unsigned tx import -> signing -> tx export -> usb -> tx import ....

I think it would be fairly simple to do all communications via QR codes and cameras, i.e. encode the data files in QR codes and "send" them via camera / screen. 

I guess it would improve security and safe a lot of time in the handling of offline transactions.

Have there been already any developments in that direction?

Would be happy to contribute.

Are there any remarks, proposals or other issues I should look into? Any help would be appreciated.

**Comment by ecdsa** [comment]
you can already sign transactions with qr codes. 
have you taken the time to try? how come you missed it?

**Comment by crohkohl** [comment]
Hahaha ... sorry ... most likely because I am blind. The symbol was so small in the dialog.
Great work, sorry to bother you .... I will try it out in my next transaction!
