### ISSUE TITLE
Phishing: exs.ignorelist.com

### ISSUE THREAD

**Issue by derrickr** [spesmilo/electrum#6132]
Perhaps not technically a bug, but thought it should be brought to your attention:

MalwareBytes reporting 'exs.ignorelist.com' is a blocked site. Did a search and found a number of worrying results e.g. https://bitcointalk.org/index.php?topic=5235359.0

**Comment by SomberNight** [comment]
So what are you saying?

I don't see this domain in the list of hardcoded servers.
The client might connect to it if another server advertises it.

Btw, note that in the bitcointalk thread you've linked the only relevant claim being made is that MalwareBytes blocked that domain. No one even says that they saw a server at that domain phishing. The [file they link to](https://hodlister.co/server-verification.txt), which is maintained by a trusted party, atm mentions the domain in the "Valid servers which are working as expected" list.

In any case, there is not much we could do either way.
