### ISSUE TITLE
TimeoutError while sweep

### ISSUE THREAD

**Issue by Edward-pops** [spesmilo/electrum#6137]
H,

When I try to sweep It went to time out error and please let me know how to sweep using json rpc. Thought maintaining the multiple wallets.

thanks.

**Comment by ecdsa** [comment]
did you use command line or curl?
if you used command line, it might be fixed by this commit 085b6ca2ab7beaad3210cef65677ce931b4298b2

**Comment by Edward-pops** [comment]
Hi have used command line..

Please let know how to use sweep in curl..

**Comment by ecdsa** [comment]
please let me know if the commit above (in master) fixes it

**Comment by Edward-pops** [comment]
Same error exits: ```TimeoutError()```
When it occurs deamon stop running.

**Comment by ecdsa** [comment]
please post a log of the daemon

**Comment by Edward-pops** [comment]
How to get the daemon log

**Comment by ecdsa** [comment]
you can run the daemon in verbose mode:
`electrum daemon -v`
alternatively, you can enable logging to file
`electrum setconfig log_to_file true`

**Comment by ecdsa** [comment]
closing, no answer
