### ISSUE TITLE
I can no longer send bitcoin using Electrum.

### ISSUE THREAD

**Issue by ian807** [spesmilo/electrum#6141]
**Version**: 3.3.8

**Platform**: Windows

**VPN**: NordVPN (also tried without VPN)

**Steps to reproduce:**

1. Open Electrum 3.3.8

On the main window:
1. Click the "Send" tab.
2. Copy the receiving address into the "Pay to" field.
3. Click the "Max" button.
4. Click the "Send" button.
5. When the Enter Password dialog opens, type password in the "Password" text field.
6. Click the "OK" button.

**Expected result:** The transaction would go through, which it did, yesterday.
**Actual result:** Error received: "Can't send BTC using any server. The server returned an unexpected transaction ID."

**Steps to try and correct problem:**

1. Leave setting as they are on the main window.
2. Select "Tools > Network" from the main menu.

On the "Network" dialog:

1. Uncheck the "Select server automatically" checkbox.
2. On the "Default Servers" listbox, right-click the first server.
3. When the floating menu appears, select "Use as server."
4. Verify that the new server name appears in the "Server" text box (e.g. "electrum2.villocq.com").
5. Click the "Close" button.

On the main window:

1. Click the "Send" tab.

**Expected result:** The transaction would go through.
**Actual result:** Error received: "Can't send BTC using any server. The server returned an unexpected transaction ID."

OR

"BestEffortRequestFailed('no interface to do request on... gave up.',)" 

FYI, I have tried numerous servers and rebooting my system entirely. The results are the same.

**Comment by SomberNight** [comment]
>  Actual result: Error received: "Can't send BTC using any server. The server returned an unexpected transaction ID."

I wonder where this text is coming from. Is this exactly what it says? Or did you translate this from another language?

Could you upload a debug log? See [here how to get that](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging).

**Comment by ian807** [comment]
SomberNight,

I did not translate. The full message is: 

"The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.

Missing inputs"

Log attached. Thanks in advance for any help.


[electrum_log_20200503T162357Z_14908.log](https://github.com/spesmilo/electrum/files/4570955/electrum_log_20200503T162357Z_14908.log)


> 
> 
> > Actual result: Error received: "Can't send BTC using any server. The server returned an unexpected transaction ID."
> 
> I wonder where this text is coming from. Is this exactly what it says? Or did you translate this from another language?
> 
> Could you upload a debug log? See [here how to get that](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging).

**Comment by SomberNight** [comment]
> "The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.
Missing inputs"

So the error is "missing inputs", which means some of the coins you are trying to spend are not known to the server.

Do you have "local" transactions in your wallet? (in `History` tab)

**Comment by ian807** [comment]
I have transactions, one of which is labeled as "local." Should I remove this and retry?

**Comment by ian807** [comment]
Update: I removed the local transaction which was unfindable on the blockchain. My transactions went through after that. Thanks so much for your help!
