### ISSUE TITLE
send bitoins error

### ISSUE THREAD

**Issue by steverrr** [spesmilo/electrum#6143]
Hello,

I dont know what happened there but I sent bitcoins with electrum bitcoin wallet and I wanted to send only 0,000001 bitcoin to another bitcoin address, but then when I clicked on ok, I noticed that 0,005 bitcoins was sent to another bitcoin address. not sure what happened, and I didnt want to send this amount and now the electrum wallet is empty. you also can check on blockchain that I had exactly 0,005 bitcoins in the wallet, and this bitcoins was sent to another bitcoin address, but I wanted to send lower than that amount and now the bitcoin wallet is empty. what happened there and is there any support there who can help and how can I get the money back that have been send there to the other bitcoin address and thanks for your answers. 

Kind regards

Stever

**Comment by ROSAISS81** [comment]
mándame tu billetera publica para recuperarte lo perdido
rosaiselaperez@gmail.com rosa Isela perez martinez

**Comment by ecdsa** [comment]
@steverrr was is a wallet with two-factor authentication? in that case the 0.005 might have been the Trustedcoin fee. Please post the transaction id.

**Comment by SomberNight** [comment]
@ecdsa according to the [website](https://api.trustedcoin.com/#/electrum-help), a prepayment of 100 txns only costs 0.0025 BTC, so I don't think so.

**Comment by steverrr** [comment]
Hello,

and I`m not sure if the wallet has a two factor authentication. and I post the payment ID here and its e2ebfac89ce1d0a36240d7ea0962a5ffee6457ed1569bfe7015c0ae301400296 . so like I said not sure what happened there and I didnt wanted to send 0,005 bitcoins there, it went automatically when I clicked on ok and then the bitcoins was sent. so how to contact the owner from the bitcoin address so that they pay the bitcoins back to my bitcoin account. and I wanted to ask, do I have different bitcoin addresses and do they change sometimes. cause sometimes when I log in the electrum wallet it seems different there the numbers and letters and thanks for your answers.

Kind regards,

Stever

**Comment by ecdsa** [comment]
thanks for the transaction id.
it looks like the change address of your transaction.
are you familiar with how bitcoin works, and what a change address is?

**Comment by steverrr** [comment]
Hello,

yes, thanks for your answer and I figured out myself that in the etherum wallet it says mBTc and I can see the amount there and I sent bitcoin to another bitcoin address and there was also a fee there and there are different bitcoin addresses there and in one bitcoin address I still have 3.94 mBTC and I know how bitcoin works, I have another bitcoin address in counterwallet but I didnt have a bitcoin address in electrum before so I had first to look how it works there, cause its a bit different there and     why is that so confusing that you have different bitcoin addresses in electrum, I thought that I have only one in the etherum wallet and I can see in the etherum wallet there are different bitcoin addresses there and thanks for your answers.

Kind regards 

Stever
