### ISSUE TITLE
Reported Phishing Server

### ISSUE THREAD

**Issue by BittBurger** [spesmilo/electrum#6150]
I have zero experience with GitHub so if there are any standards or protocols for reporting something, I apologize in advance for not knowing them.   That said, I'm just going to type this out:

Last night I loaded up a brand new laptop and installed Electrum.  I have Malwarebytes latest version running on it.  When Electrum loaded up, (and this has never happened before with Malwarebytes installed on machines with Electrum) I got an alert popup in the lower right corner of the screen.  

Blocked Website Details-
Malicious Website:  1
C:\Program Files (x86)\Electrum\electrum-3.3.8.exe, Blocked, -1, 1, 0.0.0

-Website Data-
Category: Phishing
Domain:  endthefed.onthewifi.com
IP Address:  37.211.78.253
Port:  5002
Type:  Outbound

This is a server in the Electrum server list.  I mentioned this in the Telegram channel and they suggested I report it here in case someone wants to look into this particular server for security reasons.

Thanks

**Comment by ecdsa** [comment]
Thanks for the report, @EagleTM might want to add it to the blacklist.

Note that the fact that your client connected to a phishing server does not mean that you downloaded malware, nor that you are at risk. If you have the legit version of Electrum 3.3.8, no phishing message will be displayed to you.
