### ISSUE TITLE
Electrum adds additional hex characters to OP_RETURN outputs

### ISSUE THREAD

**Issue by Relaxo143** [spesmilo/electrum#6156]
For some reason the wallet adds 4 additional hex characters at the beginning of the hex string. It's only visible once the tx is signed/sent.

**Comment by SomberNight** [comment]
Do you have an example?
Otherwise I am just going to assume that the first byte is OP_RETURN and the second one is the push size, which is just how Bitcoin SCRIPT works.

**Comment by Relaxo143** [comment]
You might be right. I used a hex to text decoder to check the final string and it could be decoding those 2 bytes as well. Thanks for the response!
