### ISSUE TITLE
Pending Transaction JSON Bug

### ISSUE THREAD

**Issue by itsMikeLowrey** [spesmilo/electrum#6157]
When I ask the wallet for the wallet history, the returned JSON is not valid if there is a pending transaction. The bad JSON is:
`"monotonic_timestamp":Infinity,`
The infinity needs to have a quote around it. This only happens to pending transactions and goes away as soon as the requested wallet history has no pending transactions. I think the issue is based somewhere around [here](https://github.com/spesmilo/electrum/blob/e2c2c8998870ac48230890c3d9adc56838d67eb5/electrum/wallet.py#L617) in wallet.py .
 I am running on btc testnet with a build from the latest commit(e2c2c8998870ac48230890c3d9adc56838d67eb5) and connecting to the node via the jsonrpc interface. I can add more details if they are needed to reproduce this bug.

**Comment by itsMikeLowrey** [comment]
I replaced line 617 with:
`            if hist_item.tx_mined_status.timestamp:
                monotonic_timestamp = max(monotonic_timestamp, hist_item.tx_mined_status.timestamp)`
and it seems to have solved the issue for me.

**Comment by ecdsa** [comment]
Thanks for the report. Unfortunately your fix does not properly order onchain and lightning transactions. We could replace float('inf') with a large integer, or strip off 'monotonic_timestamp' from the returned json.
