### ISSUE TITLE
Sent to wrong wallet (Electrum 4.0)

### ISSUE THREAD

**Issue by umutaktu** [spesmilo/electrum#6159]
I have sent 70$ to wallet address 16bE8Jov5VkTXUkAsV69gKZtM2WzuouwdX but it ended up after 6 confirmations to bc1qcygs9dl4pqw6atc4yqudrzd76p3r9cp6xp2kny.

I already consulted with the company I was supposed to sent and check via blockchain with its Transaction ID. Unfortunately it was sent to the wrong wallet. I need a help in this on reverting this transaction or sending it to the correct address. 

Thank you in advance.
![Wrong Address 1](https://user-images.githubusercontent.com/36796082/81662350-1f2ebe00-9446-11ea-8e9f-abdea565ce16.PNG)
![Save 4](https://user-images.githubusercontent.com/36796082/81662432-3a99c900-9446-11ea-813f-0284ae783d37.PNG)
![save 6](https://user-images.githubusercontent.com/36796082/81662438-3d94b980-9446-11ea-974c-175d7c38660b.PNG)

**Comment by SomberNight** [comment]
There is no "Electrum 4.0.0". The latest version is 3.3.8.
You must have downloaded a malicious clone of Electrum from some unofficial source.

Already confirmed bitcoin transactions are not feasible to revert. Sorry for your loss.

**Comment by umutaktu** [comment]
I was using the older version of Electrum for sometime as I didn't need to use it because it was one time. However, while trying to send yesterday it gave an error by stating this is the old version, thus need the newer one and it directed to their site and downloaded from there. You think it was really a clone to cause this ?

**Comment by SomberNight** [comment]
Yes, in that case this bug applies: https://github.com/spesmilo/electrum/issues/4968 :(
