### ISSUE TITLE
coinchooser policy chose 50 inputs (all from same address) instead of a single input

### ISSUE THREAD

**Issue by jebbgrenham** [spesmilo/electrum#6162]
Check this transaction, sent with Electrum 3.3.8
https://blockstream.info/tx/0df62ea317960f98727c8ca7fa78c9c392af4cedc2d1b469b1aab2c5305957d1

With the fee slider dead centre, it still decided to use a ridiculous combination of inputs resulting in a 20% fee! I realize previewing is possible (and I didn't), but there's definitely some bad logic in the code. It had loads of different single inputs all exceeding the amount to choose from, but instead it went with 53 different inputs...

**Comment by SomberNight** [comment]
Note that all those 53 inputs (UTXOs) belong to the same address.
The coinchooser, for privacy reasons, when spending any UTXO from an address, it spends all of them.

Regarding why it didn't just use a single other UTXO that was large enough in itself (if there was one as you claim), the heuristics don't try to minimise the number of inputs (but rather the number of addresses touched by inputs, which is 1 here), hence the other heuristics (+randomness) decided.

If you think about it, there is no clear strategy, some user might want to spend all 50 inputs from address A, while another might want to spend the single input from address B.
E.g. assuming fees are now relatively low (compared to expected) the former is better; while if fees are relatively high the latter is better.

**Comment by gits7r** [comment]
This makes sense for imported addresses, a standard wallet should follow-up privacy / security guides and empty an address when an UTXO is spent, try not to re-use addresses, etc. etc. IMO even if the fees are high this should be the approach, otherwise have a setting for coin chooser labeled 'Low Privacy Mode' that will trade privacy against saving some fees.

**Comment by jebbgrenham** [comment]
It's a big fix; but electrum should allow custom selection of inputs - similar to how core works.

**Comment by ecdsa** [comment]
> It's a big fix; but electrum should allow custom selection of inputs - similar to how core works.

what makes you think Electrum does not support custom input selection? 
that feature might be too difficult to figure out, but I would like to know if you really tried.

**Comment by jebbgrenham** [comment]
> > It's a big fix; but electrum should allow custom selection of inputs - similar to how core works.
> 
> what makes you think Electrum does not support custom input selection?
> that feature might be too difficult to figure out, but I would like to know if you really tried.

On send tab, there is "Pay to", "amount", "description", fee slider fields, and buttons Max, Clear, Preview, and Send. The preview button (the only one which could be construed to perhaps allow changes to inputs) does not allow you to change inputs. Based on your statement, I'm guessing that the feature does exist (CLI perhaps?), but after a thorough search, I can't find it in GUI. On core, there's a GUI button that says "Inputs" right next to the payment form under Coin Control.

**Comment by jebbgrenham** [comment]
@SomberNight , the issue re-naming you made certainly describes the issue better, but the alarming thing about the feature/bug is that a user can send a transaction without anything more than a casual printout of the fee when putting in password; when no average user is going to expect the fee to be much higher than the average transaction fee (as I found out the hard way today). Some much improved readability any giving it it's own focus might be an admirable improvement. Ie, don't put it in a dialogue box where user is focussed on inputting their password.

**Comment by SomberNight** [comment]
I've added a red warning into the confirm dialog if fee/amount > 5% in https://github.com/spesmilo/electrum/commit/7da8c2dfe5ec887fa41064258117bc2f5e4ed057
(there has already been one if the feerate is > 600 sat/byte)

suggestions re coinchooser policy changes are welcome in a new issue

**Comment by SomberNight** [comment]
@jebbgrenham btw you can do manual coin selection in the Qt GUI: `View`>`Show Coins`, and then use the `Coins` tab
