### ISSUE TITLE
Coldcard cannot pair with hidapi 0.9 on Windows

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6181]
Using Electrum master with `ckcc-protocol==1.0.1` and `hidapi==0.9.0.post2` I **cannot** pair with a real coldcard on Windows.

Using Electrum master with `ckcc-protocol==1.0.1` and `hidapi-0.7.99.post21` I can pair with a real coldcard on Windows.
Using Electrum master with `ckcc-protocol==1.0.1` and `hidapi==0.9.0.post2` I can pair with a real coldcard on Ubuntu.

-----

see https://github.com/Coldcard/ckcc-protocol/pull/9#issuecomment-628089402

On Windows, with `hidapi-0.9.0.post2`, `Success` is returned from `dev.error()`.

```
E | plugins.coldcard.qt.Plugin | late failure connecting to device?
Traceback (most recent call last):
  File "...\electrum\electrum\plugins\coldcard\coldcard.py", line 519, in create_client
    rv = CKCCClient(self, handler, device.path,
  File "...\electrum\electrum\plugins\coldcard\coldcard.py", line 79, in __init__
    self.dev = ElectrumColdcardDevice(dev=hd, encrypt=True)
  File "...\Python38\site-packages\ckcc\client.py", line 65, in __init__
    self.resync()
  File "...\Python38\site-packages\ckcc\client.py", line 94, in resync
    raise RuntimeError('hidapi: '+err)
RuntimeError: hidapi: Success
```

@peter-conalgo could you please take a look?

**Comment by SomberNight** [comment]
@peter-conalgo ping

I might able to test on Windows if you have a patch in mind.
Otherwise we will do a release very soon, and this is currently broken. (although I have not tested since opening the issue but no related code changed since)

**Comment by peter-conalgo** [comment]
How long do I have?

**Comment by SomberNight** [comment]
We will try to do a release candidate tomorrow; unless something comes up. We haven't done a release in a very long time so I expect there could be some issues with the process itself which might delay it, but in a few days nevertheless.
I guess a week or so later a full release.
Don't worry though, there are so many unreleased changes that bugfix releases are bound to follow :P

If there is a really deep issue here, we could roll back to the old hidapi but I would rather use the new one. I have had some issues with the old one although frankly I don't remember what they were anymore :/

**Comment by peter-conalgo** [comment]
Please try ckcc-protocol v1.0.2  ... will accept 'Success' from error method, to aid Windows support. Untested tho

**Comment by SomberNight** [comment]
Thanks. Works here.
