### ISSUE TITLE
Stole money with Electrum 3.3.8

### ISSUE THREAD

**Issue by Asketrea1** [spesmilo/electrum#6183]
Greetings. Today I went into my Electrum wallet to send funds, and immediately saw the transaction a few days earlier, namely on 05.21.2020 all funds were withdrawn from my wallet in an unknown direction. Bitcoin stolen with Electrum. Funds lasted only about 8 days, an extremely unreliable wallet, some kind of scam. Stole money with Electrum 3.3.8

**Comment by relativisticelectron** [comment]
It is upon the user to ensure the security of the host computer. Electrum cannot undo any security vulnerabilities on the host computer.

**Comment by ecdsa** [comment]
Sorry about your loss. it is very likely that your seed was stolen. There is nothing we can do with that type of bug report, because you do not report how it was stolen.
