### ISSUE TITLE
Error. This addreses in this wallet are not bitcoin addreses

### ISSUE THREAD

**Issue by nikestaff** [spesmilo/electrum#6185]
![image](https://user-images.githubusercontent.com/66086935/83179795-2c78c780-a12b-11ea-8a51-ec91b7cf51bd.png)

I add backup file in my electrum and getting an error.

What's the matter? Help!****

**Comment by ecdsa** [comment]
maybe your backup file was for an altcoin?

**Comment by kipilk0** [comment]
Этот бекап от Bitcoin Private

**Comment by ecdsa** [comment]
we are not maintaining altcoin versions of electrum
