### ISSUE TITLE
Could not connect to network

### ISSUE THREAD

**Issue by AndreanoCuritello** [spesmilo/electrum#6189]
Hello! I have Electrum 3.3.8. wallet. I can't connect to any of the servers in the list.
![image](https://user-images.githubusercontent.com/13471862/83249634-8fac3d80-a1af-11ea-8b74-5be131d86392.png)

**Comment by ecdsa** [comment]
please read the FAQ, or ask for assistance in the forums.
Github is for bug reports, it is not a user support system
