### ISSUE TITLE
QR code reader

### ISSUE THREAD

**Issue by JJBronze** [spesmilo/electrum#6195]
Hi all,
I can't send btc from my ELectrum wallet using the QR reader. This is the error when I click the camera buttom: 
![error](https://user-images.githubusercontent.com/66306340/83507442-d90ace80-a4c8-11ea-950d-7084d3dcd84a.png)
Please help me!
thx
JJ

**Comment by SomberNight** [comment]
Hi. Thanks for the report. It looks to be a duplicate of https://github.com/spesmilo/electrum/issues/6018

**Comment by JJBronze** [comment]
Thanks a lot SomberNight!
