### ISSUE TITLE
lnpeer.htlc_switch can raise and crash Peer on certain malformed onions

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6200]
If there is an exception raised on this line:
https://github.com/spesmilo/electrum/blob/cfdfbd2bfe82088d4e3a3cde5e52ffbe543d09df/electrum/lnpeer.py#L1537
which gets handled here:
https://github.com/spesmilo/electrum/blob/cfdfbd2bfe82088d4e3a3cde5e52ffbe543d09df/electrum/lnpeer.py#L1545
`onion_packet` will not be set, hence `fail_htlc` will not handle the issue correctly:
https://github.com/spesmilo/electrum/blob/cfdfbd2bfe82088d4e3a3cde5e52ffbe543d09df/electrum/lnpeer.py#L1577
https://github.com/spesmilo/electrum/blob/cfdfbd2bfe82088d4e3a3cde5e52ffbe543d09df/electrum/lnpeer.py#L1333

**Comment by ecdsa** [comment]
`lnpeer.fail_htlc` is parameter soup, it is difficult to understand the logic.
we should split it into two methods, without optional parameter.
