### ISSUE TITLE
wallet.get_payment_status: TypeError: '>=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6203]
Report from IRC:
```
[2020-06-03 17:29:33 +0200] <Jackielove4u>	i am testing latest electrum
[2020-06-03 17:29:50 +0200] <Jackielove4u>	and got weird issue
[2020-06-03 17:30:04 +0200] <Jackielove4u>	trace ends with:
[2020-06-03 17:31:17 +0200] <Jackielove4u>	 if vsum >= amount:
[2020-06-03 17:31:17 +0200] <Jackielove4u>	TypeError: '>=' not supported between instances of 'int' and 'NoneType'
[2020-06-03 17:31:52 +0200] <Jackielove4u>	with latest i mean master branch
```

probably related to https://github.com/spesmilo/electrum/commit/6058829870fde0ef17b2e08a567110ecc381ab94

**Comment by ecdsa** [comment]
affected users will have to run `clear_requests`

**Comment by ziggamon** [comment]
Can you explain what to do to fix the issue? Because I'm getting this exact issue on one of the wallets I use with latest master on current OS X.

**Comment by ecdsa** [comment]
`/run_electrum -o -w your_wallet clear_requests`

**Comment by ziggamon** [comment]
Thanks! 

I got it to work. The ordering of params seems to be a bit different, this is what worked for me in the end:

`./run_electrum -o clear_requests -w ~/.electrum/wallets/your_wallet`

**Comment by SomberNight** [comment]
You could also use the `Console` tab in Qt, and run `clear_requests()` there.

**Comment by SomberNight** [comment]
emzy reported that this happens even if coming from 3.3.8
Running a CLI command is an OK fix if it only involves people running development versions,
but not if it affects stable releases.

**Comment by SomberNight** [comment]
@ecdsa 
I think we should do a storage upgrade that converts onchain invoice amounts of `None` to `0`.
At the same time, we can clean-up the typing re `OnchainInvoice`:
https://github.com/spesmilo/electrum/blob/a97cb88a1ab023967186ee9ade01d2c6f1b47d52/electrum/invoices.py#L116
https://github.com/spesmilo/electrum/blob/a97cb88a1ab023967186ee9ade01d2c6f1b47d52/electrum/invoices.py#L128
to clarify that it cannot be None

**Comment by ecdsa** [comment]
we could also make `get_amount_sat` return 0 if we stored None, and call it in place of `x.amout_sat`
