### ISSUE TITLE
Show fee in fiat in transaction details

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#6206]
As in when you go to History and check the details of a transaction.

The exchange rate that makes sense to use is the one at the time of the transaction. The point is to be able to check how much you paid in fees at the time.

The feature would be dependent on whether a Fiat Currency is selected or not.

Issue based on version 3.3.8, desktop.

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/pull/6968
