### ISSUE TITLE
Show fee in fiat in transaction details [Android]

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#6207]
Same as #6206 but on Android.
___
As in when you go to Balance and check the details of a transaction.

The exchange rate that makes sense to use is the one at the time of the transaction. The point is to be able to check how much you paid in fees at the time.

The feature wold be dependent on whether a Fiat Currency is selected or not.

Issue based on version 3.3.8, Android

**Comment by accumulator** [comment]
already done
