### ISSUE TITLE
Bug: clicking on "Details" in "outgoing payments" in "send" tab not working.

### ISSUE THREAD

**Issue by h2o10** [spesmilo/electrum#6210]
Commit : b3abea7d19da493ef98e8f8f126312b2b7edcdf0

Clicking on "Details" is unresponsive.

**Comment by ecdsa** [comment]
you might have to upgrade protobuf if you have not done so:
`python3 -m pip install --upgrade --user protobuf`

**Comment by SomberNight** [comment]
I think OP means the "Send" tab, as that is where "outgoing payments" are listed.
Indeed, if you right-click>Details an item there:
- for onchain invoices
    - for BIP70: it works
    - for non-BIP70: nothing happens
- for lightning invoices
    - there is an exception

**Comment by SomberNight** [comment]
Note that relatedly, in the History tab, all on-chain tx items that relate to an invoice have "View invoice" as a context menu item, but it is a no-op for non-BIP70 invoices.
