### ISSUE TITLE
Failed to sign a transaction with Trezor one

### ISSUE THREAD

**Issue by HanZYH** [spesmilo/electrum#6214]
Hi, I used Trezor one to create a standard wallet in Electrum 3.3.8 downloaded on electrum.org with Win10 laptop.
When I send bitcoin to someone and enter my pin code, there is a error window pop out with hex string that I can not read.
here is the string:
b'\x97\xb2C\xf7\x13\xe3fYFO?\xa7\xd9\xado<\x9a\xeba\xf3\xe70\xcb\xa7\xf1\x9f9H\xa0\xf5\xe4U'

And my Trrezor one just stuck on signing transaction page.
Sorry I can not put a pic here.

**Comment by HanZYH** [comment]
I will appreciate it if you can help me out of the problem, so that I can get my bitcoin out of the wallet.

**Comment by ecdsa** [comment]
that is probably because you upgraded your trezor firmware.
their firmware was upgraded after a security issue was discovered.
Electrum 4.0 will have the required changes and there will be a release candidate soon

**Comment by HanZYH** [comment]
Thank you so much.
Can you provide the version number of trezor firmware? Maybe I can upload the order firmware to my trezor one.

**Comment by HanZYH** [comment]
And when you ready to release Electrum 4.0?It's pretty exciting！！！

**Comment by prusnak** [comment]
Already fixed in https://github.com/spesmilo/electrum/pull/6198

**Comment by HanZYH** [comment]
ok, thank you all. I have sent my bitcoin out.
