### ISSUE TITLE
user claims they were phished when using electrum 3.3.8

### ISSUE THREAD

**Issue by shaokan9308** [spesmilo/electrum#6224]
It just happened to me in version 3.3.8, When making a transfer I got a pop-up from the same application telling me that for security reasons I should update to version 4.0. I do the normal, download and install the new version and just go in I see that I was making a transfer of my entire balance in btc. I do not understand how this can happen, supposedly only happening if I used a version lower than 3.3.4...

**Comment by SomberNight** [comment]
Are you sure you had been running Electrum 3.3.8? When did you download that version and from where?

Any idea which server you were connected to?
Do you maybe have a screenshot of the message?
Where did you download the fake "4.0" version from? (check url in browser history)

Client logs would also be nice but I don't suppose you have them.

-----

In any case, I've had another look at the code in 3.3.8 and this does not seem possible.

**Comment by gits7r** [comment]
We stripped the custom arbitrary error data. I don't see how this is possible as I have tested and tested all the combinations to make sure such things are impossible in the future. Being able to trigger this on 3.3.8 seams very questionable to me. I don't see it how it's possible.

**Comment by shaokan9308** [comment]
> Are you sure you had been running Electrum 3.3.8? When did you download that version and from where?
> 
> Any idea which server you were connected to?
> Do you maybe have a screenshot of the message?
> Where did you download the fake "4.0" version from? (check url in browser history)
> 
> Client logs would also be nice but I don't suppose you have them.
> 
> In any case, I've had another look at the code in 3.3.8 and this does not seem possible.

How can I share the photo around here? For those I fell because I had version 3.3.8 downloaded from the official website of electrum... I have capture of the address from where I download the supposed version 4.0...how do I get it to you?

**Comment by shaokan9308** [comment]
![IMG_20200611_131700_115](https://user-images.githubusercontent.com/58820575/84449266-e5a2cb80-ac1a-11ea-95f0-895dc75a3c7e.jpg)

**Comment by shaokan9308** [comment]
This is the address from which I downloaded it, it is a shame that I do not
have the capture of the pop-up message... But I can send you the version I
download

**Comment by shaokan9308** [comment]
Excuse me, it was a mistake on my part from the beginning ... believe me that since I had my head in that moment because of the loss of so much money in less than 30 minutes, I had not seen the mistakes I made. It had the 2 versions downloaded, 3.1.3 and 3.3.8 and apparently it had installed the 1st ... It was a serious error on my part. Thank you for assisting me. For my part this post is closed

**Comment by shaokan9308** [comment]
Hello, yesterday after I relaxed a little and analyze more clearly I saw
the mistake I had made. Excuse me, but when you see that sum of money gone
that here in Cuba it costs a world to do, to leave in less than 30 minutes
I had no head for more. Sorry for the inconvenience.
