### ISSUE TITLE
CLI sweep - Can't disable RBF?

### ISSUE THREAD

**Issue by avsync** [spesmilo/electrum#6231]
Electrum 3.3.8/Ubuntu 20.04

Sweeping from the command line I can't seem to disable RBF.

.electrum/testnet/config is set "use_rbf" = false. With this setting the GUI sweeps correctly without RBF but the command line seems to always have RBF enabled.

electrum --testnet sweep p2wpkh:cNiQ7CL3FXXXXXX tb1qwpXXXXX | electrum --testnet broadcast -

Am I missing a flag somewhere?

**Comment by ecdsa** [comment]
are you sure that the GUI lets you sweep without RBF?
sweep transactions should always have the RBF flag: 0a1ebea669464378d21621b8c002e641c6fe8fbc

**Comment by avsync** [comment]
Yip, pic from the GUI sweep. I imagine the difference is that with the GUI I was able to specify a fee but with the CLI I didn't. Hopefully specifying a fee in the CLI might change the RBF behavior.

![rbf](https://user-images.githubusercontent.com/11985756/84570290-de033400-ad8c-11ea-82f6-eee438c9fe3f.png)

**Comment by avsync** [comment]
Tested specifying a fee in the CLI with -f and it's still broadcast as RBF.

**Comment by avsync** [comment]
> are you sure that the GUI lets you sweep without RBF?
> sweep transactions should always have the RBF flag: [0a1ebea](https://github.com/spesmilo/electrum/commit/0a1ebea669464378d21621b8c002e641c6fe8fbc)

So it'is actually a bug in the GUI and what's happening in the CLI is intended behavior?

**Comment by SomberNight** [comment]
OP is right, `wallet.sweep` only gets called from the CLI, the GUI calls the lower-level `wallet.sweep_preparations` instead. `wallet.sweep` sets RBF to True unconditionally; while the GUI will set it according to whatever the user sets/has in config.
At the time of https://github.com/spesmilo/electrum/pull/3012, both the CLI and the GUI used to call `wallet.sweep`.

The justification in https://github.com/spesmilo/electrum/pull/3012 is no longer true, the user can set the fee now, so we could allow setting RBF too. In the CLI case, we could just respect the config setting.

**Comment by billygarrison** [comment]
@SomberNight A few things I've noticed related to this issue. I built from master to get the changes to use_rbf

1.  The old electrum binary is still installed at `/usr/local/bin/electrum`, so issuing commands with e.g. `electrum getconfig use_rbf` gives an error. Instead I used `./run_electrum getconfig use_rbf` and it works fine.
2.  It seems like I can run `./run_electrum getconfig use_rbf` as many times as I want, and as soon as I use `sweep`, I get the `TimeoutError`. Subsequent `./run_electrum getconfig use_rbf` commands also give `TimeoutError`.
3. `./run_electrum sweep -h works
4. `./run_electrum sweep ?` doesn't cause it to crash, but it just prompts "Enter argument" and it seems like regardless of how I enter it, I get the message `run_electrum sweep: error: the following arguments are required: destination`.

**Comment by SomberNight** [comment]
> The old electrum binary is still installed at /usr/local/bin/electrum,

If you are planning on running from a git clone, I suggest
```
$ cd ~
$ python3 -m pip uninstall electrum
[...]
$ cd /path/to/electrum/clone
$ python3 -m pip install --user -e .
```
note the `-e` which is short for editable

> ./run_electrum sweep ? doesn't cause it to crash, but it just prompts "Enter argument"

The `?` is syntax sugar we use. If you want to be prompted for an argument, type '?' or ':' (concealed) instead of the value as part of a command.

> regardless of how I enter it, I get the message run_electrum sweep: error: the following arguments are required: destination.

Yes because the `?` is a single argument but `sweep` expects two.

----

Re your `TimeoutError` issue I am not sure what is going on, but I suggest reinstalling electrum, making sure the daemon is stopped, and the testing again, as it sounds like you might have multiple installs potentially conflicting somehow.

**Comment by billygarrison** [comment]
> If you are planning on running from a git clone, I suggest
> 
> ```
> $ cd ~
> $ python3 -m pip uninstall electrum
> [...]
> $ cd /path/to/electrum/clone
> $ python3 -m pip install --user -e .
> ```
> 
> note the `-e` which is short for editable

I followed your steps but still get the `TimeoutError`. I am trying `./run_electrum sweep p2wpkh-p2sh:K********** 3*******************`


> Yes because the `?` is a single argument but `sweep` expects two.

Thank you for the info RE: ?`


> Re your `TimeoutError` issue I am not sure what is going on, but I suggest reinstalling electrum, making sure the daemon is stopped, and the testing again, as it sounds like you might have multiple installs potentially conflicting somehow.

Not sure what you mean by "making sure the daemon is stopped" - isn't it required to be running for the sweep command to work? With the daemon running, I still get the `TimeoutError`, and with the daemon stopped I get the error `Daemon not running; try 'electrum daemon -d'`


Some more info FYI:

- Ubuntu 18.04.4 LTS
- Python 3.6.9

`pip list`:
```
asn1crypto (0.24.0)
Click (7.0)
colorama (0.4.1)
cryptography (2.1.4)
Electrum (4.0.0a0)
enum34 (1.1.6)
Flask (1.0.2)
futures (3.2.0)
gyp (0.1)
idna (2.6)
ipaddress (1.0.17)
itsdangerous (1.1.0)
Jinja2 (2.10)
keyring (10.6.0)
keyrings.alt (3.0)
MarkupSafe (1.1.1)
numpy (1.16.1)
pandas (0.24.1)
pip (9.0.1)
pycrypto (2.6.1)
pygobject (3.26.1)
python-dateutil (2.8.0)
pytz (2018.9)
pyxdg (0.25)
SecretStorage (2.3.1)
setuptools (39.0.1)
six (1.12.0)
Werkzeug (0.15.1)
wheel (0.30.0)
```
