### ISSUE TITLE
Issue importing multi-sig PSBT from electrum into bitcoin core & LND

### ISSUE THREAD

**Issue by sako0938** [spesmilo/electrum#6257]
I am having an issue decoding a PSBT file generated with electrum. In my case I am using a Coldcard setup as a multisignature wallet.

lightningnetwork/lnd#4400

To replicate:
1. Open electrum skeleton file created by coldcard
2. Create a new transaction in electrum, save psbt to file on MicroSD.
3. Sign as many times needed for multi-sig (Optional)
4. Bring MicroSD back to computer

When sanity checking the psbt, is when I start seeing issues:
`base64 mypsbt-signed.psbt -w 0`
In addition, the unsigned psbt gives the same error, so I don't think the ColdCard is causing the issue.

`bitcoin-cli decodepsbt {base64 data from above}`

Results:
`error code: -22
error message:
TX decode failed PSBT is not sane.: iostream error`

From the linked issue, the LND developer said:

> I had a look at the PSBT. The binary encoding looks OK but it doesn't follow one of the rules for consistency that's why it's rejected.

> The violated rule is: if WitnessUtxo is nil then WitnessScript MUST also be nil.
It looks like Electrum might have accidentally put a witness UTXO as a NonWitnessUtxo? I can't find any of the UTXOs but that could be because my JSON serializer doesn't display them properly. To me this sounds like an issue should be opened in the Electrum repo.

**Comment by SomberNight** [comment]
see
https://github.com/bitcoin/bitcoin/pull/19215
https://github.com/bitcoin-core/HWI/pull/340
https://github.com/spesmilo/electrum/pull/6198
https://blog.trezor.io/details-of-firmware-updates-for-trezor-one-version-1-9-1-and-trezor-model-t-version-2-3-1-1eba8f60f2dd

in particular, see
https://github.com/spesmilo/electrum/pull/6198#issuecomment-638335792
> Yes, Core will need changes. I believe BIP 174 itself will need changes too.

What you are experiencing is a bug in Bitcoin Core and LND.
Electrum already updated its PSBT code to mitigate the hardware the bip143 sighash vulnerability.
