### ISSUE TITLE
error opening wallet

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#6263]
![image](https://user-images.githubusercontent.com/388716/85632599-9bbbdb80-b645-11ea-90ca-a603eb0ac87f.png)

**Comment by SomberNight** [comment]
Any chance you could upload debug logs? See https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging

You might be able to access the GUI settings if you open/create another wallet,
or alternatively, you could manually modify the `config` file to contain `"log_to_file": true,` (take care it's valid json).

**Comment by Transisto** [comment]
I haven't kept the log and haven't been able to reproduce, edited the issue with the name of the error, in case someone else has this error.

And closing
