### ISSUE TITLE
[UI] Lightning unicode char looks like a stack

### ISSUE THREAD

**Issue by rdymac** [spesmilo/electrum#6265]
Checkout the look of the unicode character/symbol for the Lightning balance:

<img width="179" alt="stack_ln" src="https://user-images.githubusercontent.com/2995401/85636805-c3309980-b681-11ea-9705-d29c4cd0e60e.png">

It looks like a UI bug

**Comment by SomberNight** [comment]
The issue is that this unicode character is not available in the system font.

We could package a font (or subset of a font) that has it, with the application, as was done in Electron Cash for emojis: https://github.com/Electron-Cash/Electron-Cash/pull/1496
I am not sure if it's worth the hassle.

**Comment by rdymac** [comment]
Would this symbol work? Maybe it doesn’t work on Windows or Linux, though:

↯

![860E1AA0-2201-4F3D-B5AB-90A9978533C3](https://user-images.githubusercontent.com/2995401/85809090-11639c80-b757-11ea-83d1-2b8da23eb06a.jpeg)

**Comment by SomberNight** [comment]
- so currently we are using &#x1f5f2; [0x1f5f2](https://www.fileformat.info/info/unicode/char/1f5f2/index.htm), added in unicode 7.0
  <details>
    <summary>pics</summary>

    ![ubuntu](https://user-images.githubusercontent.com/29142493/85810235-ee7ebb80-b749-11ea-9d8f-51462d77f1dc.PNG)
    ![mac](https://user-images.githubusercontent.com/29142493/85810240-efafe880-b749-11ea-812b-45b598a9e2b4.PNG)
    ![win](https://user-images.githubusercontent.com/29142493/85810242-f0e11580-b749-11ea-82fa-48401b989b69.PNG)
  </details>
- @rdymac suggested &#x21af; [0x21af](https://www.fileformat.info/info/unicode/char/21af/index.htm), added in unicode 1.1
  <details>
    <summary>pics</summary>

    ![ubuntu](https://user-images.githubusercontent.com/29142493/85810012-3c46f400-b749-11ea-89d7-83d6361c1920.PNG)
    ![mac](https://user-images.githubusercontent.com/29142493/85810020-3f41e480-b749-11ea-9ee8-5b0516f995d4.PNG)
    ![win](https://user-images.githubusercontent.com/29142493/85810025-410ba800-b749-11ea-9513-0b7ca258fd32.PNG)
  </details>
- I've also found &#x26a1; [0x26a1](https://www.fileformat.info/info/unicode/char/26a1/index.htm), added in unicode 4.0
  <details>
    <summary>pics</summary>

    ![ubuntu](https://user-images.githubusercontent.com/29142493/85810073-64ceee00-b749-11ea-987a-9bc2d38c68cb.PNG)
    ![mac](https://user-images.githubusercontent.com/29142493/85810075-66001b00-b749-11ea-8014-872df9aac19b.PNG)
    ![win](https://user-images.githubusercontent.com/29142493/85810079-6698b180-b749-11ea-97c4-5ee96ee1b60f.PNG)
  </details>

(pics from relatively fresh install of ~updated versions of each OS)

-----

we could also just replace the fancy char with some ascii text :D

**Comment by rdymac** [comment]
I can only see the last two. Looks like the last one work for you in all three OS, I would go for that one if the ascii one doesn’t work or doesn’t look better than the zap ⚡️.

**Comment by ecdsa** [comment]
0x26a1 is fine, although not as nice as 0x1f5f2 on linux
