### ISSUE TITLE
Electrum AppImage cant connect to Ledger Nano X

### ISSUE THREAD

**Issue by ju2wheels** [spesmilo/electrum#6267]
I am using Electrum 3.3.8 AppImage on Ubuntu 16.04 and getting the following trying to get it to connect to the Ledger Nano X:

```
Failed to create a client for this device.
Make sure it is in the correct state.
```
I have the Ledger udev rules in place and Ledger Live and other wallets distributed as AppImage can connect to it.

The device selection screen before the above error says:

```
An unnamed ledger [ledger, initialized, hid]
```

**Comment by SomberNight** [comment]
Try unplugging and replugging the device, and make sure the Bitcoin app is open on it.

**Comment by ju2wheels** [comment]
Ok, that worked.

Thanks,
