### ISSUE TITLE
macOS Qt refresh bugs with 4.0.0b0: swap dialog, open_channel dialog

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6269]
@rdymac reported on irc
as in title,
on macOS, with app dark mode disabled (default theme),
pressing buttons in the swap dialog and the open channel dialog have multiple refresh bugs
(icons/texts not updating properly)

The original reporter used macOS 10.15.5.
The 4.0.0b0 binary bundles PyQt 5.14.2 and Python 3.7.7.

I am testing on macOS 10.15.3, and can reproduce when using the binary.
I cannot reproduce when running from source with same python and pyqt versions.

**Comment by SomberNight** [comment]
these bugs seem related, except they claim they only affect 5.11 and not later
https://bugreports.qt.io/browse/QTBUG-68521
https://bugreports.qt.io/browse/QTBUG-68740

**Comment by SomberNight** [comment]
related:
https://github.com/spesmilo/electrum/issues/4777
https://github.com/spesmilo/electrum/commit/2a4b516f162ea94f963afead46ffd24e40dd93aa

**Comment by ecdsa** [comment]
why is that bug only affecting newly introduced gui elements (swaps, open_channel) and not the preexisting widgets (except xpub)?
