### ISSUE TITLE
Electrum 4.0 does not load

### ISSUE THREAD

**Issue by bitcoinmichi** [spesmilo/electrum#6273]
Having installed the new electrum 4.0 beta just ended in a full disaster. The wallet loads for about 1 second and then gets terminated automatically. Without any error message. When trying to restart with the older version 3.8 it says that the wallet is not compatible anymore and I can load it with the old version

Running on Windows10

**Comment by SomberNight** [comment]
Any chance you could upload debug logs? See https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging

You might be able to access the GUI settings if you open/create another wallet,
or alternatively, you could manually modify the `config` file to contain `"log_to_file": true,` (take care it's valid json) - you should make a backup of it first.

**Comment by bitcoinmichi** [comment]
![error1](https://user-images.githubusercontent.com/8032143/85760255-46300f00-b6d7-11ea-95ba-9daf15561de5.png)

**Comment by bitcoinmichi** [comment]
![error2](https://user-images.githubusercontent.com/8032143/85760324-56e08500-b6d7-11ea-8af8-ae366af90a20.png)

**Comment by SomberNight** [comment]
When exactly does it crash?

E.g. I assume you have a password set for the wallet, in which case it opens to "wizard" where you can either enter the pw or create a new wallet;
and then you enter your password, it starts loading the wallet, maybe some transactions show up in the history tab, and then it crashes? Please try to describe it like that.

---

In the meantime, you can re-create your wallet from seed in Electrum 3.3.8 and use it there.

**Comment by ecdsa** [comment]
there must have been a GUI screen before the wallet database upgrade, even if the wallet is not password protected.
so the GUI partially works, to the extent that it was able to display that screen

**Comment by SomberNight** [comment]
We released a beta1, could you try with that? https://download.electrum.org/4.0.0b1/

**Comment by drdran** [comment]
@SomberNight I prefer to work with source so I can debug with pdb there is a tag or a commit to refer?

**Comment by SomberNight** [comment]
well you can try with git HEAD,
or even the similarly named tag "4.0.0b1"

**Comment by bitcoinmichi** [comment]
> When exactly does it crash?
> 
> E.g. I assume you have a password set for the wallet, in which case it opens to "wizard" where you can either enter the pw or create a new wallet;
> and then you enter your password, it starts loading the wallet, maybe some transactions show up in the history tab, and then it crashes? Please try to describe it like that.
> 
> In the meantime, you can re-create your wallet from seed in Electrum 3.3.8 and use it there.

I downloaded the b1 update and the wallet is working again properly. Thanks
