### ISSUE TITLE
"Enable Lightning" button is hard to find in user interface

### ISSUE THREAD

**Issue by davterra** [spesmilo/electrum#6282]
Trying out 4.0.0b1

Having the "Enable Lightning" button buried inside Wallet/Information seems odd and it took me a few minutes to find it.
Seems like it would be more logical to put it in Tools/Preferences or Tools/Lightning Network.

**Comment by ecdsa** [comment]
Preferences and Lightning Network are not wallet-specific dialogs, so we are not going to put it there.

**Comment by davterra** [comment]
> Preferences and Lightning Network are not wallet-specific dialogs, so we are not going to put it there.

Fair enough. But it seems like a significant enough of a function to not be buried in a sub-menu. Especially when people long familiar with the wallet expect that Wallet/Information pertains to wallet parameters rather than functionality.

**Comment by ecdsa** [comment]
how about moving that button to the 'channels' tab?

**Comment by ecdsa** [comment]
closing, this button has been removed
