### ISSUE TITLE
show sat/byte on tx (fee not shown for incoming transactions)

### ISSUE THREAD

**Issue by kipilk0** [spesmilo/electrum#6285]
Why electrum 4.0 isn`t show the current fee on the unconfirmed tx ?

**Comment by SomberNight** [comment]
It should.
Could you upload a screenshot; or maybe better explain exactly what is shown or not shown and where?

**Comment by kipilk0** [comment]
> 
> 
> It should.
> Could you upload a screenshot; or maybe better explain exactly what is shown or not shown and where?

fd9b60a9261df3d3ff97b4149af23c0372ec33d155d272dfe28b4df54ddcffb3
![изображение](https://user-images.githubusercontent.com/20616242/85899716-fe4fdb80-b7ed-11ea-9336-becb7969d034.png)

**Comment by kipilk0** [comment]
All incoming TXs 'Fee: unknown' , and when TX waiting confirmations, on 'Date' column also can`t see current fee, need to open each TX in block explorer in browser.

**Comment by SomberNight** [comment]
That tx in your screenshot is already confirmed. It has always been the case that Electrum does not show fee for confirmed incoming transactions.

If all the inputs are owned by the wallet, Electrum calculates the fee and shows it to you.
If not all the inputs are owned by the wallet; if the tx is unconfirmed the server tells you the tx fee (but this cannot be verified) and the client shows it to you; if the tx is confirmed the fee is not shown.

**Comment by kipilk0** [comment]
![изображение](https://user-images.githubusercontent.com/20616242/85917807-f07d7300-b84c-11ea-9583-9f5c320075e2.png)
that`s what i mean, i receive new TX from partner and can`t see fee in electrum tab or TX details
