### ISSUE TITLE
Unused space in the window

### ISSUE THREAD

**Issue by kipilk0** [spesmilo/electrum#6287]
![изображение](https://user-images.githubusercontent.com/20616242/85902860-83d68a00-b7f4-11ea-8915-d6d43e9e25d8.png)

Why is between the border and transaction set free space? 

> 20pixels

**Comment by SomberNight** [comment]
Note that it's not always unused.

![qt_history_tree](https://user-images.githubusercontent.com/29142493/85903161-360e5180-b7f5-11ea-87e5-05a43fc0dde3.PNG)

**Comment by kipilk0** [comment]
ok, i am not yet testing LN
