### ISSUE TITLE
 show sat/byte on tx (fee not shown for incoming transactions)

### ISSUE THREAD

**Issue by kipilk0** [spesmilo/electrum#6289]
![изображение](https://user-images.githubusercontent.com/20616242/85917807-f07d7300-b84c-11ea-9583-9f5c320075e2.png)
that`s what i mean, i receive new TX from partner and can`t see fee in electrum tab or TX details

_Originally posted by @kipilk0 in https://github.com/spesmilo/electrum/issues/6285#issuecomment-650519954_

**Comment by ecdsa** [comment]
which server are you connected to?

**Comment by kipilk0** [comment]
> 
> 
> which server are you connected to?

now electrum.blockstream.info:50002
i also try to change server, still have this problem

i used the same servers on 3.3.8, there is no problem and show correct all fees
![изображение](https://user-images.githubusercontent.com/20616242/85917909-b5c80a80-b84d-11ea-9a80-1e038196e81a.png)

**Comment by ecdsa** [comment]
I can reproduce the issue with electrum.blockstream.info. 
It is a server side issue.
It seems that blockstream's electrum server implementation does not return fee information.
@greenaddress can you have a look?

**Comment by kipilk0** [comment]
> 
> 
> I can reproduce the issue with electrum.blockstream.info.
> It is a server side issue.
> It seems that blockstream's electrum server implementation does not return fee information.
> @greenaddress can you have a look?

It isnt problem with the server, on the same settings and same servers on 3.3.8 shows correct , on 4.0beta don`t see fees

**Comment by SomberNight** [comment]
Indeed, blockstream's server is not following the protocol spec. It sends histories without fee information.
Once you have downloaded the history for an address from their server, even connecting to another server won't fix it, as the scripthash status will be the same.
We now enforce that the fee must be present, and will disconnect if not, in https://github.com/spesmilo/electrum/commit/8d0c03caff5879edb0c038d33602fc3721109f32

**Comment by shesek** [comment]
I can confirm, esplora-electrs as well as the upstream electrs do not report the fee. I'll look into adding it to the former and I notified @romanz for the latter.
