### ISSUE TITLE
Since last update to Electrum 4.0.0b.0, No Connection and Network-Settings cannot be changed or deleted. 

### ISSUE THREAD

**Issue by TheTotalConnector** [spesmilo/electrum#6290]
I have updated to the above Beta?-"version". i see only "overview" and "proxy" in the network-window. 
Not connected, even though in Server it says: mynode local IP: 50002. 
I cannot change or delete it. next to it are 4 boxes only with question marks. 
I tried to connect via mynode-Tor-adddress, but I cannot replace the address in the field inside overview of Network.
In the Proxy-window, I could check-mark Tor at port 9150, with Socks5, 127.0.0.1 and port 9150, but i cannot do anything with this, because in the overview -window i cannot change the address. 

I am not home on my local network at this time, so not sure whether this would be necessary, since i had been already connected before update. 
i tried to follow the instructions of https://www.keepitsimplebitcoin.com/nodl-dojo-3-electrum/. he uses nodl, but settings should be same, correct?
Please, help. What can I do? Should or can I reverse back to the original version? 
Thx.

**Comment by ecdsa** [comment]
please send a screenshot of the network dialog

**Comment by TheTotalConnector** [comment]
![Network-Overview](https://user-images.githubusercontent.com/50043671/85918443-23cafc80-b863-11ea-934e-2c8d3757cd76.JPG)
![Network-Proxy](https://user-images.githubusercontent.com/50043671/85918447-2594c000-b863-11ea-9b35-d81e3cd1dd8e.JPG)
![Latest Version after Update](https://user-images.githubusercontent.com/50043671/85918449-27f71a00-b863-11ea-9c9e-40c8999b5c06.JPG)

**Comment by ecdsa** [comment]
I don't have time to watch the instruction video you followed, but I guess the problem comes from there.
they might have instructed you to pass the server IP from the command line. 
it would be nice if you could explain what you did, instead of expecting us to know

**Comment by TheTotalConnector** [comment]
Well, that´s exactly my question. I had not done anything besides updating. there was no connection and i can only see the two windows "Overview" and "Proxy".  
"Server" is missing. I cannot change anything in the overview window. 
After all failed, I asked @KISBitcoin for help. He works with Nodl, but that should not be the problem, I assume. Since my normal connection via my local IP;50002 is not working, I tried to connect via mynode-onion-address and adjust the settings, but i cannot even replace the address. 
So, the question is why? Thanks for your help.

**Comment by ecdsa** [comment]
"server" is not missing, we just simplified the GUI

**Comment by TheTotalConnector** [comment]
i am not a techy at all. i would need some guidance, because i cannot change, adjust or delete anything in these new "GUI"-windows

**Comment by ecdsa** [comment]
you cannot replace the address, probably because you passed the server on the command line, but omit to say it

**Comment by TheTotalConnector** [comment]
please, can you be more specific...and instruct me step by step what to do..or not to do?

**Comment by TheTotalConnector** [comment]
most important question: do i need to be home on my local network at all, to fix this issue?...because right now, i am not.

**Comment by ecdsa** [comment]
oh well, I had a look at the instruction video you linked, and I see that they told you to edit the config file.
so.. why are you not saying that you edited the config file? do you think it helps us to understand the situation?

I suggest you just remove that config file and restart from scratch.

**Comment by TheTotalConnector** [comment]
i started with the editing of the config file, after everything else failed. before that, the issue persisted, i had no connection whatsoever and i was not able to test or change my local IP. 
ok, thanks, i will remove the config file and start fresh...

**Comment by TheTotalConnector** [comment]
I even uninstalled the upated (beta-) version , deleted all files incl. config, and re-installed a fresh electrum with the original version 3.3.8. 
Now i see overview, server, and proxy. in server i have local IP with port 50002. 
I then inserted the -1 -s local IP:50002:s into the path-shortcut of electrum´s properties. 
Nope, still not connecting. 
Whatever issue I have, it is then not on my end. my mynode is perfectly up and running. 
I followed the instructions precisely. 
Is there anyone else, who is really willing to help me and guide me through this process?

**Comment by SomberNight** [comment]
>  I then inserted the -1 -s local IP:50002:s into the path-shortcut of electrum´s properties.

Note: that is exactly what @ecdsa meant by "you passed the server on the command line". If you specify the server like that, as a safety measure, the client will not let you change the server in the GUI. This is why the network dialog is basically disabled.

> I even uninstalled the upated (beta-) version , deleted all files incl. config, and re-installed a fresh electrum with the original version 3.3.8.
> Nope, still not connecting.

If you cannot connect even with 3.3.8, after starting from scratch, then it's clearly not a bug in the beta.
Please upload [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)

**Comment by TheTotalConnector** [comment]
yes, thank you, this was exactly what i did not understand. now, i do. 
connection with onion:50002 successful. 
a have a few questions about the config file. the server: onion.....50002:s 
should that be a s or t at the end after port?

**Comment by SomberNight** [comment]
`s` and `t` select the protocol
you should know what your server provides at what port
`s` is using TLS/SSL
`t` is plaintext TCP

**Comment by TheTotalConnector** [comment]
my original issue had not been resolved: with mynode local IP on electrum not connected (it had been running smoothly before) after trying out everything, i decided to connect it via onion and this finally worked. blue dot on. some techy guy in mynode telegram group sent me a link to a bunch of docs and pages to read. i could not even find a hint to my real issue, and would not even know where to look in all those technical descriptions (i am a layman). the issue could be anything, from open vpn settings to some other small detail?is there a user with same issues, and trying to connect via local IP outside home /local network?thanks. -- Sent from my Android phone with GMX Mail. Please excuse my brevity.On 6/28/20, 04:46 ghost43 <notifications@github.com> wrote:

   
  Closed #6290.

**Comment by SomberNight** [comment]
Does what you are trying to do work on 3.3.8; disregard if it worked in the past, try it now.
Please upload debug logs, as said above (for the case where it fails to connect).
Can you ping that IP it fails to connect to, from cmd/terminal?

**Comment by TheTotalConnector** [comment]
Not sure how to upload debug logs...and ping IP from cmd/terminal?is there a guide i can read or watch?i would need to replace the (functional) onion with mynode local IP:50002(?) again. anything else i need to re-adjust (config file)?thanks for help!-- Sent from my Android phone with GMX Mail. Please excuse my brevity.On 6/28/20, 16:06 ghost43 <notifications@github.com> wrote:

   
  Does what you are trying to do work on 3.3.8; disregard if it worked in the past, try it now. Please upload debug logs, as said above (for the case where it fails to connect). Can you ping that IP it fails to connect to, from cmd/terminal?
