### ISSUE TITLE
Question: Android Upgrade Test: Does upgrading Electrum Android 3.3.8 -->4.0 work?

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#6294]
I was unable to upgrade an older 4.0 (master) to a newer 4.0 (master) in Android.  I could only uninstall the older master apk and install the newer master apk.
Is this expected?  It would be great if a user could upgrade and all the application data (seeds, ...) would be preserved.

**Comment by SomberNight** [comment]
It should work? Why, what error did you get?

Note that it is a security feature of Android that applications are signed, and they are verified [TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use). i.e. all updates need to be signed by the original key. So you cannot install the official apk as an update if you already have the app installed signed with your custom key.

**Comment by relativisticelectron** [comment]
Thanks. I will try to test the upgrade. Right now I have trouble to build the 3.3.8 apk.

**Comment by relativisticelectron** [comment]
Well, I upgraded on linux and android and it worked well (so far) :-)
