### ISSUE TITLE
Android Startup crash

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#6296]
The current master 0d7bcde2db0fe72c29d61e6261adb963bab375c2 crashes on startup (after the Electrum logo is shown) when build as an apk and put on Android.  No crash_report screen is shown.

Reproduce the error:
- Uninstall Electrum from android
- Install Electrum (master)
- Startup --> crashes

PS: On linux the kivy version works.

**Comment by SomberNight** [comment]
Please see if you can provide logs: https://github.com/spesmilo/electrum/tree/0d7bcde2db0fe72c29d61e6261adb963bab375c2/contrib/android#how-can-i-see-logs-at-runtime

**Comment by relativisticelectron** [comment]
@SomberNight : Thanks! I (probably) found the problem:  I need to rename the application name (for test purposes) not only in https://github.com/spesmilo/electrum/blob/master/contrib/android/buildozer.spec#L7  but also in https://github.com/spesmilo/electrum/blob/master/run_electrum#L311.
