### ISSUE TITLE
issues with Advanced Preview tx dialog (empty fields)

### ISSUE THREAD

**Issue by lunarovic** [spesmilo/electrum#6306]
In 4.0.0b1 I cannot seem to spend unconfirmed transactions anymore, regardless of the state of the "Spend only confirmed coins" setting.

![image](https://user-images.githubusercontent.com/2381553/86039161-53842b00-ba42-11ea-97e3-29f1ebf641ba.png)

If I press the Max button, I get this:
![image](https://user-images.githubusercontent.com/2381553/86039102-3e0f0100-ba42-11ea-81cd-667b7fc7043b.png)

If I manually type a value <= than the unconfirmed balance and click Pay, I get this:
![image](https://user-images.githubusercontent.com/2381553/86039350-96de9980-ba42-11ea-849d-bde83dc95365.png)

Clicking on Advanced shows this, which is really bad if the "Advanced preview" setting is checked and you just get this window:
![image](https://user-images.githubusercontent.com/2381553/86039386-a6f67900-ba42-11ea-8478-d57e4bf55d54.png)

Finally, if I manually type a value > than the unconfirmed balance and click Pay, I get this:
![image](https://user-images.githubusercontent.com/2381553/86039997-9397dd80-ba43-11ea-91f6-64f7e6d63eec.png)
Notice the error message is different from the one when clicking the Max button, and also this creates the outgoing payment in the list, while the Max button doesn't.

**Comment by SomberNight** [comment]
Note that the unit you have configured is mBTC.
0.011 mBTC is 1100 sat. That is near dust territory, it might be too expensive to spend it.
Still, that half-empty tx preview dialog is clearly a bug that we should fix.

**Comment by lunarovic** [comment]
> 0.011 mBTC is 1100 sat. That is near dust territory, it might be too expensive to spend it.

But when I open the same wallet in 3.3.8, sending works. This is definitely not only a cosmetic problem with the "Advanced" window, a functionality is broken.

> Note that the unit you have configured is mBTC.

I know. Off topic, but interesting that you say "configured" since that is the default setting without any configuring, and I never understood why would mBTC be a good default setting, especially for beginners and especially since it never caught on, no other wallets use it by default.

**Comment by SomberNight** [comment]
> But when I open the same wallet in 3.3.8, sending works. This is definitely not only a cosmetic problem with the "Advanced" window, a functionality is broken.

In the "Confirm Transaction" window, I think you could just lower the feerate using the slider and then "sending" would work here too.

The Max button will say "insufficient funds" because there isn't enough money available to create a tx using the last used fee settings. This differs from 3.3.8 in that previously the user had a chance to configure the fee before pressing "Max" but now the UI has been reorganised so this is no longer possible.

**Comment by lunarovic** [comment]
> In the "Confirm Transaction" window, I think you could just lower the feerate using the slider and then "sending" would work here too.

Thanks, I already tried that and it didn't work, but now when you mentioned it, I fiddled with it more and I managed to get it working by changing from the default fee rate ETA to Static, so that I can set the fee at 1 sat/byte.

I also experimented with the empty Advanced window and if I type the fee in one of the custom text fields, the window will then populate, unless I type a fee which is larger than the available funds minus the sending amount, then the window becomes empty again.

**Comment by SomberNight** [comment]
Note: if Advanced Preview is enabled in the config, and the user tries to create a tx for more money than available, they will not get the insufficient funds error, instead the half-empty Advanced Preview dialog opens.
