### ISSUE TITLE
Funding transaction never broadcasted

### ISSUE THREAD

**Issue by garkelin** [spesmilo/electrum#6307]
Electrum version 4.0.0b1

When opening a channel , the funding transaction is not broadcasted. Status is stuck on "OPENING"

Work around: open funding transaction from contextual menu and clic "Broadcast". Before that, the transaction was signed but not broadcasted

Error Cause (guess): Probably because i have "Advanced preview" setting enabled in the Transaction preferences. If this is really the cause, the expected behaviour should be to open the advanced preview window when opening the channel and letting the user manually sign and broadcast the tx, but this windows was never shown.

**Comment by SomberNight** [comment]
> Work around: open funding transaction from contextual menu and clic "Broadcast". Before that, the transaction was signed but not broadcasted

Did the transaction appear as "Local" in the History tab?

What kind of wallet do you have; is it based on a software seed? (what is "wallet type" and "keystore type" in Wallet>Information?)

In case you have [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging), those might be useful.

> Error Cause (guess): Probably because i have "Advanced preview" setting enabled in the Transaction preferences

No, I don't think it's that. Well, at least that works for me.
