### ISSUE TITLE
How to add addresses for change manually through the console?

### ISSUE THREAD

**Issue by B10wfish** [spesmilo/electrum#6310]
I know how to manually add addresses using the console.
[wallet.create_new_address(False) for i in range(N)]
But how is it possible to manually add change addresses?
Thanks

**Comment by SomberNight** [comment]
Why do you want to add more change addresses?

See what that parameter that you set to False does:

https://github.com/spesmilo/electrum/blob/9547a4e60cf4ee8a05a48c96fb8694ff8f3cb767/electrum/wallet.py#L2439

**Comment by B10wfish** [comment]
I realized. In case I need a lot of addresses and I need to know them all at once. thank
