### ISSUE TITLE
os.urandom()->secrets.token_bytes()

### ISSUE THREAD

**Issue by wakiyamap** [spesmilo/electrum#6311]
This is a suggestion.

New modules(secrets) added since python 3.6.
https://docs.python.org/3.6/library/secrets.html

How about using `secrets.token_bytes()` instead of `os.urandom()` ?

```
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.urandom(32)
b'n\xcc\xe7~\xb6\xd3U5\xcc\xfd\xeb\n\xec|O<@\x12\xce\xfbpt\r_\xa5\xe0\xe1=\xa9}Lb'
>>> os.urandom(32)
b'\x05g\x88J\xacf\xff5\xe1b\xbe(\x05KI\x06A\xa4:\xef\xe9\xeb\xd2G.\xb4@i\xbd\xf4-\xf3'
>>> import secrets
>>> secrets.token_bytes(32)
b"\xcb\x85\xc6\xfd\x11W;\x07\x80W\xf0\x92\xc2\x86\xf0p\xf9\xa4\xef\t\xe3\xf0KA\x9f\x80'\xd0\xb2M\x13."
>>> secrets.token_bytes(32)
b'`N\x01t\xedl\xc6\xbb\xf9^\xa8\x84\x13\x90\xf3\xc2\x08\x1d\xdd\xeeL$W\x84\xdb\xc4KY\x821w\x07'
```

**Comment by hoganri** [comment]
secrets.token_bytes is just a wrapper for os.urandom(). See line 35: https://github.com/python/cpython/blob/3.8/Lib/secrets.py

**Comment by ecdsa** [comment]
thanks @hoganri

**Comment by wakiyamap** [comment]
Yeah. I don't really think the need to change it right now.
For the time being, if you know the existence of the secrets module, there is no problem.

thanks.

**Comment by SomberNight** [comment]
maybe we could replace `ecdsa.util.randrange` with `secrets.randbelow`

**Comment by ELHart05** [comment]
why? is os.urandom() vulnerable?
