### ISSUE TITLE
Where can users go to talk to other developers about electrum? How to get started with using electrum within a python script

### ISSUE THREAD

**Issue by frogeyedpeas** [spesmilo/electrum#6312]
I realize this isn't a bug but I do not have any way of reaching any human that has used electrum before other than this avenue, the IRC chat somehow was filled with ~172 ppl but absolutely no one was speaking and or responsive. If there is a better forum/discussion place for this please link it and i'll move this question there.

I want to find something akin to a getting started guide with electrum in python [the scripts folder seemed like a good starting place but it doesn't really explain whats happening] 

Where I got stuck: after reading this file
https://github.com/spesmilo/electrum/blob/master/electrum/scripts/quick_start.py

It feels very unclear how to connect to the normal BTC network as opposed to a test net, and open up my wallet after connecting to that. I.E. as a developer I have no idea what to replace the argument "{"testnet": True}" in line 11 of that file so I can go about making transactions with the actual network.

The command line interface seems to really package this nicely, just supply the wallet URI and it automatically connects to the real network by default via daemon. 

So what I'm looking for:

Is there a file demonstrating how to import electrum in python and create a wallet object that does almost exactly the command line command of

    "electrum daemon load_wallet -w [URL to wallet] " 

so that you can then use wallet.getBalance() next.

**Comment by frogeyedpeas** [comment]
I would like to also volunteer to create this getting started guide so that future python devs can read it. Once I understand how to use electrum in python myself

**Comment by ecdsa** [comment]
IRC is the place to go

**Comment by SomberNight** [comment]
re https://github.com/spesmilo/electrum/blob/6d2aee18d0bc5b68bff4123855f2b77b7efa1f3b/electrum/scripts/quick_start.py#L11-L12

just do `config = SimpleConfig()`
(rm testnet key; and don't call set_testnet)
