### ISSUE TITLE
Can't CPFP: unknown fee for parent transaction

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#6313]
Current latest master

Attempting to CPFP a transaction, gives me the above error.
The transactions themselves appear with a gear icon and label "Unconfirmed [rbf]"

To my knowledge these transactions should not have any unconfirmed inputs so shouldn't be any issues with calculating CPFP fee, and in any case better to have some options for it than none at all.

**Comment by SomberNight** [comment]
I think this might be related to https://github.com/spesmilo/electrum/issues/6289

**Comment by ziggamon** [comment]
Yes, I managed to get it to go away with another server, so the error is mainly w blockstream being down right now. But if possible a more pedagogical error message would be nice.

**Comment by SomberNight** [comment]
I don't think this error can be triggered under normal circumstances.
The server was misbehaving and the client was not checking the replies properly. With latest commits, the client will reject the reply and disconnect; so this error should not happen anymore.

The current message says "unknown fee for parent transaction" which might not be user-friendly but it describes the situation well: the fee for the tx to be CPFP-ed is missing (as the server did not send it).
