### ISSUE TITLE
Pay button doesn't work on most Recent Commit 392a648

### ISSUE THREAD

**Issue by frogeyedpeas** [spesmilo/electrum#6329]
Problem Description: 
Attempting to send BTC doesn't work with version 4.0.0.b1 of the wallet.
The calculator seems to run correctly but the Pay button doesn't register ANY of the clicks, (attempting to click it results it no visible changes on the screen, even though the pay button seems enabled since hovering over it causes the blue outline to appear). 

System: Mac OS High Sierra 10.13.6 on a macbook Pro
Electrum: 4.0.0.b1
Most Recent Commit: 392a648de5f6edf2e06620763bf0685854d0d56d 

[Screenshots here](https://imgur.com/a/Vgm1cLu)

**Comment by ecdsa** [comment]
not sure what you did, but commit 392a648 does not have the version number 4.0.0b1
