### ISSUE TITLE
can't find fee tab

### ISSUE THREAD

**Issue by micromatrix14** [spesmilo/electrum#6335]
In the newest version of electrum wallet 4.0.1 in the preferences window, there is no tab "fee" like in the previous 3.3.8
where I can enable edit fees manually option

**Comment by SomberNight** [comment]
The "edit fees manually" config option has been removed, as the user interface has been restructured and it no longer made sense.
In the "Send" tab, after clicking "Pay", in the "Confirm Tx Dialog", click "Advanced".

**Comment by Raviu56** [comment]
Advanced payment is really advanced and complicated, the payment needs many steps to accomplish there.
Please allow to edit fees as on version 3.x without going into advanced payment, and keep other advanced options in advanced tab.
Most of the users would need just "edit fees" so wouldn't need all this complication.

**Comment by silvernode** [comment]
no advanced dialog comes up after clicking pay. I just get "Not enough funds" no matter what I do. y money is stuck. I wish I could just edit fees like I used to.
