### ISSUE TITLE
Clicking on QR-button crashes the system. 

### ISSUE THREAD

**Issue by TheTotalConnector** [spesmilo/electrum#6336]
When I click on the camera-button for scanning QR-code, all disappears and I have to re-start the system. I was trying to set up a watch only wallet, but there seems to be a bug. 
Am I the only one with this issue? 
Thanks.

**Comment by ysangkok** [comment]
Which operating system are you on? Which version, and which version of Electrum?

When you say "all disappears", does that mean that everything on the screen disappears? Is it impossible for you to kill the Electrum process?

**Comment by SomberNight** [comment]
Closing, no answer.
Also, https://github.com/spesmilo/electrum/issues/6901 might be the same issue and has more details.
