### ISSUE TITLE
"Check for updates" in 4.0.1 lists Latest Version as 3.3.8.

### ISSUE THREAD

**Issue by jet24** [spesmilo/electrum#6338]
"Check for updates" in 4.0.1 lists Latest Version as 3.3.8.

electrum-4.0.1-x86_64.AppImage

![Screenshot at 2020-07-05 13-03-19](https://user-images.githubusercontent.com/26032616/86537843-02e85400-bec0-11ea-8884-744dd3e6a184.png)

**Comment by bauerj** [comment]
Yes, that's on purpose.

Since there are probably a few more bugs in the code, the updater will not prompt for an update for now. This will change in a few days.

**Comment by SomberNight** [comment]
@ecdsa I think enough time has passed by now and the `version` file could be updated.

**Comment by ecdsa** [comment]
ack

**Comment by ecdsa** [comment]
note: I have not updated the version because both myself and @SomberNight were on vacation.
we want to be able to keep up with new issues, and upgrading the version will certainly increase the rate of new issues.

**Comment by h0ek** [comment]
![image](https://user-images.githubusercontent.com/4890300/92381556-6171be80-f10b-11ea-8bac-ba6ac12b7a3b.png)

**Comment by SomberNight** [comment]
We have just released 4.0.3 and updated to version file on the webserver to 4.0.3
