### ISSUE TITLE
Add minimum size to LN information window

### ISSUE THREAD

**Issue by mkcisse** [spesmilo/electrum#6344]
Please see the following pics !

![Capture d’écran de 2020-07-06 22-59-51](https://user-images.githubusercontent.com/45665262/86643109-b5153e00-bfdc-11ea-84f5-5f0aec0303e5.png)
![Capture d’écran de 2020-07-06 23-00-05](https://user-images.githubusercontent.com/45665262/86643118-b8102e80-bfdc-11ea-9593-1495dd11f005.png)

**Comment by ysangkok** [comment]
specifying the max size in pixels is fragile because it will break with DPI changes

**Comment by mkcisse** [comment]
There is PyQT function which supports this feature without specifying a min size.
