### ISSUE TITLE
CentOS and libsecp256k1

### ISSUE THREAD

**Issue by robo2bobo** [spesmilo/electrum#6353]
A word of warning. I tried installing electrum 4.0.1 under CentOS 7 and it fails to work, because libsecp256k1 does not exist.

```
$ /usr/bin/python3.6 /home/user/.local/bin/electrum daemon start
E | ecc_fast | libsecp256k1 library failed to load. exceptions: [OSError('/home/user/.local/lib/python3.6/site-packages/electrum/libsecp256k1.so.0: cannot open shared object file: No such file or directory',), OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory',)]
Error: Failed to load libsecp256k1.
```

I tried looking for an epel package, but I couldn't find anything.

Interestingly, openssl does support it:

```
# openssl ecparam -list_curves | grep -i secp256
  secp256k1 : SECG curve over a 256 bit prime field
```

**Comment by robo2bobo** [comment]
I've read that libsecp256k1 is a requirement for the lightning network, something thats disabled and I will not use.

Maybe this dependency could be make optional? at least when the lightning network is not being used?

**Comment by robo2bobo** [comment]
In case anyone else wants to install libsecp256k1 under CentOS 7, here is how I did it:

install package dependencies as root:
```
yum install m4 perl-Thread-Queue automake mpfr libmpc cpp gcc libtool automake autoconf
```

as a user, download and compile the library. I use a dedicated user for running electrum:
```
mkdir contrib
cd contrib
wget 'https://raw.githubusercontent.com/spesmilo/electrum/master/contrib/build_tools_util.sh'
wget 'https://raw.githubusercontent.com/spesmilo/electrum/master/contrib/make_libsecp256k1.sh'
chmod +x build_tools_util.sh
chmod +x make_libsecp256k1.sh
./make_libsecp256k1.sh
ln -s ~/contrib/secp256k1/dist/lib/libsecp256k1.so.0 ~/.local/lib/python3.6/site-packages/electrum/libsecp256k1.so.0
```

remove package dependencies as root:
```
yum remove m4 perl-Thread-Queue automake mpfr libmpc cpp gcc libtool automake autoconf
```

**Comment by SomberNight** [comment]
We will aim to bundle those build scripts in the tar.gz for a subsequent release, see https://github.com/spesmilo/electrum/issues/6323

While it would be great to stay a pure-python package, and we will continue to try hard not to introduce non-python dependencies, there were multiple reasons why [libsecp256k1 had to become mandatory](https://github.com/spesmilo/electrum/pull/5947).
- `libsecp256k1` is significantly faster than any alternative, and when using Lightning this performance is needed (pure python alternatives such as `python-ecdsa` are around 2 orders of magnitude slower)
- as in linked PR, `python-ecdsa` changed its API multiple times recently which resulted in breakage
- if Bitcoin adopts the Schnorr soft fork ([BIP-340](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki) and related), which we consider very likely, neither `python-ecdsa` nor `openssl` could be used: only `libsecp256k1` will have support for that signature scheme in the foreseeable future (and it's unlikely any alternative would get comparable review)

**Comment by robo2bobo** [comment]
Thank you for taking the time to give a complete explanation.

At least, libsecp256k1 is very easy to compile and does not depend on a ton of 3rd party libraries.
