### ISSUE TITLE
json-rpc documentation with version 4 changes

### ISSUE THREAD

**Issue by robo2bobo** [spesmilo/electrum#6354]
My application uses the json-rpc commands to communicate with electrum. I tested the new electrum version 4 and immediately it was apparent that something was wrong.

For example, the getrequest method no longer returns a string as status, instead it returns an integer.

Are these changes documented somewhere?

Thank you.

**Comment by robo2bobo** [comment]
The json-rpc documentation is also lacking any references or information about the changes in electrum v4. Link: https://electrum.readthedocs.io/en/latest/jsonrpc.html

I am trying to read the git changes, but I'm not having much luck.

**Comment by robo2bobo** [comment]
I just tested the addrequest example from the jsonrpc documentation page and that also is wrong and needs to be updated in regards to electrum v4.

```
$ curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"addrequest","params":{"amount":"3.14","memo":"test"}}' http://username:password@127.0.0.1:7777

Invalid Request
```

**Comment by robo2bobo** [comment]
After further investigation, I found the following changes in v4:

- addrequest has been renated to add_request

- the status is now based on the following integers:
```
PR_UNPAID   = 0
PR_EXPIRED  = 1
PR_UNKNOWN  = 2     # sent but not propagated
PR_PAID     = 3     # send and propagated
PR_INFLIGHT = 4     # unconfirmed
PR_FAILED   = 5
PR_ROUTING  = 6
```

in another part of the source, I found the following piece of code that helps explain the integers:
```
PR_UNPAID:_('Pending'),
PR_EXPIRED:_('Expired'),
PR_UNKNOWN:_('Unknown'),
PR_PAID:_('Paid'),
PR_INFLIGHT:_('In progress'),
PR_FAILED:_('Failed'),
PR_ROUTING: _('Computing route...'),
```

**Comment by robo2bobo** [comment]
Nobody cares.

**Comment by dev-bre** [comment]
After 6months from closing this issue, the docs are still unbelievably wrong. This is totally unacceptable due to the fact that this wallet is heavily used in the community.

Thanks a lot for raising this issue, I myself wasted hours to understand why addrequest method wasn't working.

I hope the developers will start becoming more caring... Considering that they take a fee on each transaction sent using this wallet.

**Comment by SomberNight** [comment]
> I hope the developers will start becoming more caring... Considering that they take a fee on each transaction sent using this wallet.

If you mean the mining fee that all bitcoin transactions pay, that goes to the miners. The developer do not get any of it.
If you specifically mean the 2FA fee when using a twofactor wallet with Trustedcoin, then it is true, some of that funds the project.

But in any case, this is a FLOSS project, please help us improve the documentation and contribute.
