### ISSUE TITLE
Bug: Enabling lightning on Android works even without wallet password

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#6365]
Steps to reproduce:

- ON android, click on wallet name to see wallet information
- Click "Enable LN"
- Warning is printed, click "Yes"
- You are asked for the wallet password in order to generate lightning keys. Even if you enter a wrong password or try to cancel the operation it will say "Wrong password, lightning keys not initialized".  

But if you close the wallet and re-open it, it will have lightning activated.

**Comment by SomberNight** [comment]
This flow has changed since.
