### ISSUE TITLE
UX: Android: No way to get out of "Addresses" menu tab

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#6366]
If you go to Android drop-down menu -> Addresses tab, you can filter (used/unused | change/receive) - very good, you can click on an address so see it, its qr code, or private key - very good as well, but there is no "Close" button like all other popup submenus have to back to the main wallet window. Basically you are stuck on addresses, you can only "use" one so you go to the "Request" tab and clear it from there and navigate back to history, but this is under optimal and too much to play around in order to simply go back to the main window.

**Comment by SomberNight** [comment]
The native "back" button is supposed to be usable. Is this not the case?
See https://github.com/spesmilo/electrum/issues/6276#issue-645784906 and please test if the workaround works (to see if same issue)

**Comment by gits7r** [comment]
Oh, sorry - the Back button on the Android tool bar works. But it did not work that time for me (tried many times) -- my guess my device just hanged and it was something local, isolated to me. closing this for now.
