### ISSUE TITLE
Android: No way to enter backup directory, Save Wallet Backup cannot work

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#6367]
On Android, at settings we have a configuration to enable backups. Basically that is just ON/OFF setting, there is no way to enter an additional parameter (like a path, or select a location by browsing with the GUI). Then when we click on wallet name -> Save backup we will get an error that cannot save backup as Backup directory path is not configured.

**Comment by ecdsa** [comment]
android has a default backup path.
maybe your issue is fixed, or it is #6774
