### ISSUE TITLE
Minimum version of protobuf

### ISSUE THREAD

**Issue by hegjon** [spesmilo/electrum#6374]
I'm maintaining the Electrum package for Fedora Linux. Our newest version includes protobuf 3.11, I see in commit b3abea7d19da493ef98e8f8f126312b2b7edcdf0 that there was introduced a minimum 3.12 version for protobuf.

Is there something special about 3.12 or will Electrum work with protobuf 3.11?

**Comment by SomberNight** [comment]
You are free to use older protobuf; in that case you should generate the pb2 files yourself with a compatible protoc.

Consider the two commits as a whole:
https://github.com/spesmilo/electrum/commit/59681d04386f5f493a097388b78ee27959655889
https://github.com/spesmilo/electrum/commit/b3abea7d19da493ef98e8f8f126312b2b7edcdf0

You can generate that file with this command:
https://github.com/spesmilo/electrum/blob/995250948aa57b4ee7fff0565794d3f3192c4132/electrum/paymentrequest.py#L40

**Comment by hegjon** [comment]
Thanks, do you know about a good integration test? Any bitpay service?

**Comment by SomberNight** [comment]
Try e.g. https://bitpay.com/181852/donate

There is also https://test.bitpay.com/ on testnet, which I sometimes use, but their SSL cert expired over half a year ago, so you would need to comment out a check in the client...
https://github.com/spesmilo/electrum/blob/995250948aa57b4ee7fff0565794d3f3192c4132/electrum/x509.py#L309-L311
