### ISSUE TITLE
AppImage reproduciblity fails: hidraw and hid (addendum to #6357)

### ISSUE THREAD

**Issue by margre8** [spesmilo/electrum#6382]
Dear Electrum developers,

I would like to add to issue https://github.com/spesmilo/electrum/issues/6357 my observations.
In day of release reproducibility of AppImage worked without any problem.
When I saw issue https://github.com/spesmilo/electrum/issues/6357 I tried to build fresh docker image and output was same as differ from Travis ` 8e38095896df2a86c465a065ba120a274efa8af4fdeb0e4f61c18d7c44628a7b`.
My today test of Electrum created another differing file: `8e17d5f6ac0721a4025606bf850ca33ced83b66577086e64a79fd9a9fa547c85`.
After diff of extracted AppImages (official release & second differ file) I can see there is two more differing files to libcrypt and libnsl:
`hid.cpython-37m-x84_64-linux-gnu.so` and `hidraw.cpython-37m-x84_64-gnu.so`.

I think it looks like some dependences on PyPi were updated since last week.

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/issues/5859
