### ISSUE TITLE
Unconfirmed coins make impossible to use Electrum

### ISSUE THREAD

**Issue by melaxon** [spesmilo/electrum#6385]
Version 3.3.8 MacOS 10.11 (El Capitan)

Check this screenshot:
https://www.dropbox.com/s/10z1a6zs6v7ttqe/Screenshot%202020-07-14%2015.21.18.png?dl=0

I am going to send a small amount of BTC from an address with quite sufficient and confirmed balance.
I marked "Freez" the addresses with unconfirmed coins and they are greyed in address list
Now you can see that "spend from" address is not included in transaction preview.
It looks like Electrum collects Bitcoin dust anyway independant on settings and selected Spend from address.
If I sign and broadcast this transaction it will wait till the parent transactions get confirmed (may be for ages)
And this makes IMPOSSIBLE further use of Electrum till those coins are confirmed.

Please advise!!!

**Comment by SomberNight** [comment]
Please try with latest Electrum (4.0.2 at time of writing).
A lot of related code was changed since 3.3.8.
Although note that 4.0.x requires macOS 10.13 or newer :/
