### ISSUE TITLE
Zero Balance for existing change on Bech32 address

### ISSUE THREAD

**Issue by Emanresueht** [spesmilo/electrum#6390]
Hi All,

I loaded a bip39 seed into Electrum Wallet with derivation path m/0'. The imported transactions look good just the last one looks odd. 

So far I used Bread Wallet (BRD now) for all transactions. The last transaction in Bread Wallet has a Bech32 address as change address. The balance of this import is only the amount on this Bech32 change address.

I do not see the change amount for this last transaction under "Balance" on the History tab in Electrum Wallet, it only shows 0,00000000. When I open the last transaction in Electrum Wallet I see the change on the Bech32 address. I see the change amount in Bread Wallet as well. Do you know why I do not see the change amount in Electrum Wallet under "Balance" on the History tab?

Thanks

**Comment by SomberNight** [comment]
I think breadwallet manages a mixed script wallet, with most of your addresses being p2pkh but change being sent to p2wpkh.
This type of wallet is currently not supported Electrum; maybe it will be with https://github.com/spesmilo/electrum/issues/6016.
You should be able to access all your coins however by creating multiple wallet files in Electrum.

> I loaded a bip39 seed into Electrum Wallet with derivation path m/0'. 

bip39 is a mess for exactly this reason: you, the user, will have to figure out what derivation paths and script types are used by breadwallet.
