### ISSUE TITLE
Mobile wallet: funding transaction is never broadcast

### ISSUE THREAD

**Issue by gustavonalle** [spesmilo/electrum#6412]
Version 4.0.2 
Android GrapheneOS

Tried to open a channel by scanning a node, put the amount, clicked on "open", a popup appeared saying "Permission Denied".

In the other peer, the channel is pending but the funding transaction is never broadcast. Restarted the wallet and no sign of the transaction or the channel

**Comment by ecdsa** [comment]
the "permission denied" message was probably raised when trying to save a backup of your wallet.
in your settings, disable backups.

related: #6774
