### ISSUE TITLE
Android wallet files backup

### ISSUE THREAD

**Issue by rdymac** [spesmilo/electrum#6414]
In a non-rooted phone you are not able to find the Wallet folder where the Electrum wallet files are stored, not even using USB cable and the Android File Transfer app for Mac.

@bauerj:  _Yes, only the app itself can access it_

This might make the wallet files safer against brute-force attacks, but as a way to backup wallet files (for Lightning, labels, tx history, as a regular backup...) it is too difficult. This could cause wallet loses in cases where the app doesn't open or crashes, the user won't be able to extract the wallet files easily if needed.

I see the new option in `Settings > Backups` , but **does this option create a regular wallet file copy, or is that a backup for close-only channels as in the desktop client**? Also, it only seems to be triggered when new channels are created, so it cannot be triggered manually.

In my experience, people lose their funds due to seed lost and other app/phone failure reasons more than brute-force attacks.

@bauerj: _I think this was changed to improve security. Passcodes which would be used in a mobile app are very easy to brute-force_

If that's the reason for hiding the wallet files, maybe asking the user for a stronger password for encrypting the exported wallet files which can be used in the auto-backups and the _[feature that needs to be added for]_ manual backups could solve this concern.

**Comment by gits7r** [comment]
Related: #6367

**Comment by M83tUt3** [comment]
I think this definitely deserves to be looked at. I use electrum on my phone with a strong password because my phone is by far my most secure device (thanks GrapheneOS!). However if I want to make a backup of my wallet right now, I have to involve my desktop as I can't do it manually on Android. This is risky, and more or less defeats the point of using the Android app to begin with.

**Comment by ecdsa** [comment]
@rdymac the backup file contains channel backups, not channels. 
the backup can be triggered manually from the wallet information screen, but you first need to enable backups.

if it fails to save a backup, check if the issue is the same as #6774
