### ISSUE TITLE
Bug: required field 'fee' missing from dict

### ISSUE THREAD

**Issue by engenegr** [spesmilo/electrum#6416]
Tried to send tx from Green. I use self-hosted Electrs. 

```
assert_dict_contains_field(tx_item, field_name='fee')

electrum/interface.py", line 118, in assert_dict_contains_field
    raise RequestCorrupted(f'required field {field_name!r} missing from dict')
electrum.interface.RequestCorrupted: required field 'fee' missing from dict
```

**Comment by engenegr** [comment]
Transaction 8a37326c3a7b4e154869b31ba3d8cc190d28c2de2dfd589886c50b5bf4622031
Electrum works correctly with another wallet that doesn't contain unconfirmed transactions.

**Comment by SomberNight** [comment]
related:
https://github.com/spesmilo/electrum/issues/6289
https://github.com/spesmilo/electrum/issues/6308
you should update electrs

**Comment by engenegr** [comment]
Thank you @SomberNight .  Sorry for bothering. I tried search but haven't found those issues.
