### ISSUE TITLE
Electrum was unable to parse your transaction: Expecting value: 1 column 1 (char 0) 

### ISSUE THREAD

**Issue by matw6K** [spesmilo/electrum#6418]
Hello, 
  I tried many times to copy a raw transaction from a watch-only wallet to my default wallet through -> Tools ->Load transactions -> from file -> copy - paste the raw transaction and I've got  the same critical error msg
![Screen Shot 07-19-20 at 08 00 PM](https://user-images.githubusercontent.com/67791670/87880451-762eb180-c9fa-11ea-86c3-fd00445835d7.PNG)

mobile version for watch-only 4.0.2 and the desktop 3.3.8 no updates available

Any idea how to solve this issue ?

**Comment by SomberNight** [comment]
You should update the desktop Electrum to 4.0.x, as the partial tx format was incompatibly changed.
https://github.com/spesmilo/electrum/blob/52f8aafb604d05487a0612f65bacb966c0d0f569/RELEASE-NOTES#L50-L54

The update checker still sees the latest as 3.3.8 (related: https://github.com/spesmilo/electrum/issues/6338) but you can download the latest version from the website.

**Comment by matw6K** [comment]
Yes, that's it.
Thanks for your support
