### ISSUE TITLE
"used" addresses are confusing for some users

### ISSUE THREAD

**Issue by rodeoclownicp1** [spesmilo/electrum#642]
i still have bitcoin being sent to a wallet marked as used. i did not mark the wallet as used it just happened automatically. well i still have coin in pools being sent to that wallet address, but it is no longer working? is this the way the wallet works? is this correct? have i lost my coin? if i want to keep a number thats used i should have the option to do so

**Comment by bahner** [comment]
@rodeoclownicp1 Hepp!

I had an address and sent ~ 1.2 BTCto it, then I sent 0.010 BTC from it. Now it's marked as used - with zero value. NOW I do have the correct balance in my wallet (approx 1.3), BUT The 1.2 btc isn't connected to any address, when I click addresses. That's counter intuitive, and frankly: a bit scary.

Don't know if this is my bad, or what, but some docs would be nice.

KInd regards,
bahner

**Comment by gits7r** [comment]
@bahner that is normal. the rest was sent in a "Change" address. Electrum does this to ensure your privacy, so one can't tell which is the payment and which is the change. This is a very important and useful feature which takes care of privacy and solves a lot of things related to passive blockchain analysis and historic analysis. It's a feature, not a flaw.

**Comment by sandoche** [comment]
Is it possible to get the private key of the change address?

**Comment by dabura667** [comment]
yes

1. View > Show Addresses
2. On addresses tab, select change
3. right click the address, click Private Key
4. Enter password and private key will show up.

**Comment by sandoche** [comment]
Thanks that works!
