### ISSUE TITLE
user creating watch-only version of 2fa wallet incorrectly. created a watch-only wallet just from first keystore xpub, and sent coins there

### ISSUE THREAD

**Issue by matw6K** [spesmilo/electrum#6421]
From watch-only wallet (v.4.0.2) I succesgully created invoice (within 25 blocks) and copied to desktop default_wallet [2fa], Tools -> Load transactions -> From text. But Sign / Broadcast is off. 
![Screen Shot 07-20-20 at 07 47 AM](https://user-images.githubusercontent.com/67791670/87901044-a14aec80-ca5e-11ea-878c-d23289938156.PNG)

Any idea how to finger it out this issue ?

**Comment by SomberNight** [comment]
You have a 2fa wallet but the tx shown is trying to spend from a "1..." address.
As the transaction dialog says, the "transaction [is] unrelated to your wallet".

**Comment by matw6K** [comment]
Thanks for your support.
Before the update to 4.0.2 I did't have any issue I had made many transactions... how to fix it? do you have any suggestion ??

**Comment by SomberNight** [comment]
You must be doing something weird, so please describe in detail what you are trying to do and how you are trying to do it.
In particular, how did you create the watch-only wallet?

**Comment by matw6K** [comment]
Ok
From my phone, through the watch-only wallet 

Send ->scan the recipient QR -> amount-> save invoice -> select the invoice and Pay -> I select copy (raw transaction) through a text file on my pc to wallet  and through tools->load transaction->from text -> copy paste from the file and then the prntsreen from the previous post.

This is the procedure that I`ve followed at every transaction 

But now I can not sign and broadcast.

I ca not remember how to open the watch-only wallet on my phone, but I followed the quide from electrum.org

**Comment by matw6K** [comment]
I restored the watch-only wallet on my PC 
![Screen Shot 07-21-20 at 09 50 PM](https://user-images.githubusercontent.com/67791670/88094412-2e479000-cb9c-11ea-866f-f0b223b414fa.PNG)

I see the BTC and I created an outgoing payment

![Screen Shot 07-21-20 at 09 51 PM](https://user-images.githubusercontent.com/67791670/88094566-75ce1c00-cb9c-11ea-86f7-3b8a8319a0ad.PNG)

I can export the transaction

![Screen Shot 07-21-20 at 09 53 PM](https://user-images.githubusercontent.com/67791670/88094729-b9288a80-cb9c-11ea-8ad8-f815a9756e97.PNG)

But The wallets could not sign/Broadcast the transaction

![Screen Shot 07-21-20 at 10 00 PM](https://user-images.githubusercontent.com/67791670/88095486-e590d680-cb9d-11ea-981d-ac305ecead84.PNG)

These instractions  https://electrum.readthedocs.io/en/latest/coldstorage.html
 not working fom me, anymore 

I have this issue after the update to 4.0.2

Whats going on ??

**Comment by SomberNight** [comment]
You are creating the watch-only wallet incorrectly.
A 2fa wallet uses 2of3 multisig, it is not enough to scan a single xpub.

See guide here: https://bitcoinelectrum.com/creating-a-watch-only-version-of-your-2fa-wallet/

**Comment by SomberNight** [comment]
ahh I have just realised what is going on here... you have two logically distinct wallets.

First, you need to understand that a 2fa wallet uses 2-of-3 multisig (as above). It has three xpubs (3 keystores in the code). It cannot have "1..." addresses (legacy 2fa wallets have "3..." addresses, segwit 2fa wallets have "bc1q..." addresses)

What you have done, is taken the first xpub, and created a watch-only wallet from just that. This wallet is then not using multisig at all, it only has the one keystore. It has p2pkh ("1...") addresses.
You have been misusing a bug (https://github.com/spesmilo/electrum/issues/5948) which let you create signatures using the 2fa wallet for the transactions created by the p2pkh wallet.
The reason this stopped working is that the bug (linked issue) got fixed (https://github.com/spesmilo/electrum/commit/ab4e2dd9f0a083a7e1664a167dd9a1547289d80c) in 4.0.x.

Well, I am not even sure you have a 2fa wallet at all -- does it have a history?

-----

To properly create a watch-only wallet for a 2fa wallet, see guide here: https://bitcoinelectrum.com/creating-a-watch-only-version-of-your-2fa-wallet/

-----

To rescue your coins from your current non-2fa-wallet, open the 2fa wallet in desktop (Qt) Electrum (as in picture in your first comment),
go to `Console` tab (can be unhidden by going to `View`>`Show Console`), and enter:
```
getmasterprivate()
```
then create a new wallet file from that master private key. This wallet should be able to sign the txs created from your watch-only wallet.
Again, note that this wallet is not a 2fa wallet.

**Comment by matw6K** [comment]
Oh !! Now I get it !!  What a mess for a bug. :)
I'll try your solution. 

Thank for your support
