### ISSUE TITLE
Electrum 4.02. + Lightning: Payment failed No path found

### ISSUE THREAD

**Issue by curious0101** [spesmilo/electrum#6430]
Created new SegWit wallet, Lightning enabled.

Pasted ln invoice to Pay To field in Send tab. Clicked Pay.

Error message:
Payment failed
No path found

How can I fix that? How to create a channel? How new users supposed to know what to do next?

Thanks

**Comment by gits7r** [comment]
I get this as well. I tried to do an Electrum to Electrum transaction (via lightning) between two wallets on different machine and got the same error. I can see there are more reports about this also in separate issues. Looks like lightning does not work for me.

**Comment by davterra** [comment]
I've also experienced this. I opened a small (.002) channel with Boltz.

As a test, I later went to the boltz.exchange website and tried a submarine swap, to send Boltz most of the funds in my in Lightning channel and receive BTC into a Joinmarket address. 

When I pasted the Boltz receive/LN invoice in my Electrum wallet and tried to send, I got the "No Path Found" error, even though I have a channel open with the entity that I'm trying to send to.

**Comment by ecdsa** [comment]
@davterra "most of the funds" might have exceeded your channel reserve

**Comment by davterra** [comment]
> @davterra "most of the funds" might have exceeded your channel reserve
Thanks @ecdsa 
I tried again with a smaller amount and it went through. The "No Path Found" error did not suggest to me that the amount of the tx was part of the problem. I appreciate the quick and useful comment.

**Comment by ecdsa** [comment]
@gits7r how many channels did you open? did you open them with random nodes?
I suppose you are aware that opening a channel does not guarantee the existence of a path?

**Comment by dmp1ce** [comment]
I can pay to the node I created a channel with but not to any nodes on a second hop away from the Electrum node.

**Comment by ecdsa** [comment]
closing, no useful info here

**Comment by dmp1ce** [comment]
For reference, my issue was the node I connected to from Electrum had no public routes to anywhere else. So, I couldn't pay anything but the node I connected to.

**Comment by FiretronP75** [comment]
It defaults to Electrum trampoline. Is that a bad option (no paths)? If so, why does it get selected by default? And how do I get my bitcoin back from it? And this info should be added to the documentation.
