### ISSUE TITLE
Не показывает номер счета

### ISSUE THREAD

**Issue by Ananas34** [spesmilo/electrum#6431]
в вкладке получение нету номера счета не знаю как его узнать, он должен там показываться но его там нету, где его найти

**Comment by ZarusMods** [comment]
Во-первых пиши на английском,и во-вторых https://iancoleman.io/bip39/ через этот сайт сделай себе фразу. Потом выбери что ты хочешь восстановить,и выбери что у тебя BIP39 фраза. Дальше продолжить и профит!
