### ISSUE TITLE
Possible coin losses if clossing channel TX never gets confirmed

### ISSUE THREAD

**Issue by ChineseGeek** [spesmilo/electrum#6434]
What happens if a closing channel tx is not confirmed and after 2 weeks the nodes drop the tx? The channel state changes to OPEN again? Or those coins are going to be lost?

**Comment by SomberNight** [comment]
It depends a bit on how the channel got closed (mutual; or if force-closed, who closed?).

However in any case, the following still applies:
If any tx (related to the local wallet) was ever seen by the local wallet, but is dropped from the mempool for whatever reason, it then turns into a "local" transaction. It will be displayed as a local transaction in the History tab and you can e.g. rebroadcast it from there.
