### ISSUE TITLE
trezor freezes after clicking sign

### ISSUE THREAD

**Issue by LukAss741** [spesmilo/electrum#6437]
![IMG_20200724_101644](https://user-images.githubusercontent.com/8490744/88375698-54d41980-cd9c-11ea-8438-4b1659095444.jpg)
It stopped working today. Yesterday I updated trezor firmware.
However, sending transactions on wallet.trezor.io works flawlessly.

**Comment by amarett0** [comment]
Go to the official Electrum website and download the latest version.

**Comment by LukAss741** [comment]
It worked. Thanks.
Electrum's check for updates is still set to 3.3.8 being the newest version.

**Comment by relativisticelectron** [comment]
> It worked. Thanks.
> Electrum's check for updates is still set to 3.3.8 being the newest version.

Can you close this issue?

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/pull/6198
