### ISSUE TITLE
EXPIRY_TOO_SOON when sendinging funds from nodeid: aranguren to nodeid: endurance on testnet

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#6442]
When paying testnet invoice on Electrum 4.0.2, sendinging funds from [nodeid: aranguren](038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9) to [nodeid: endurance](https://1ml.com/testnet/node/03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134), I get an error stating `EXPIRY_TOO_SOON`, even though the invoice is not expired.

![expiry_too_soon](https://user-images.githubusercontent.com/5009148/88482995-7c58ec80-cf2a-11ea-8c59-b4aec212b306.png)

The sending client is Electrum 4.0.2, and the receiving client is Eclair (mobile) 0.4.12.  The issue seems to be a problem with one of the nodes in the route, but its unclear exactly which.

Eventually I opened a channel on Eclair to aranguren.  After balancing capacity I was able to send too and from Eclair without issue.

I also ran the same Electrum wallet from `master` which did not change the result.

### Sending Client

* Client: Electrum 4.0.2 - Run from python source against git tag `4.0.2`
* OS: Windows 10 version 1901
* Python: 3.7.1

### Recieving Client

* Client: Eclair Mobile Testent - version 0.4.12
* OS: Android 8.0.8

**Comment by ecdsa** [comment]
this error is not about the invoice, but about the expiry of the HTLC
since testnet has irregular block mining, I am not sure if that error is relevant for mainnet

**Comment by brianddk** [comment]
> I am not sure if that error is relevant for mainnet

@ecdsa, understood.  Thx for looking at it

Closing.
