### ISSUE TITLE
Lightning Invoice stuck "In progress"

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#6443]
While attempting to pay an invoice from https://testnet.boltz.exchange/ (not the `swap` button), the invoice simply never progressed from "In progress".  I eventually shutdown the client OS overnight and the next day the invoice is still listed as "In progress".  The result of `list_invoices` is:

```
{
    "amount_BTC": "0.00101321",
    "amount_msat": 101321000,
    "expiration": 3600,
    "invoice": "lntb1013210n1p0364slpp5m9m3y9edslw8thecfuj78ft629378llv63q8sx4x5s32frcw3yhsdql2djkuepqw3hjqsj5gvsxzerywfjhxuccqzptsp5nx7wes0dle4e65neepxjlpnulqqrgzpznnpeq7swuuz3td06nmeq9qy9qsqt8wnetfg84m72fudjl90xxmheyzeal28lcv3rz48ctsuad7s6qgz5v0szyz5ac7sl9lvvvu86afanhmc4w0mte3rkg5a6zhkhusm8egpv0dc2e",
    "is_lightning": true,
    "message": "Send to BTC address",
    "status": 4,
    "status_str": "In progress",
    "timestamp": 1595758111
},
```

I tried paying it again by simply paying the same invoice text, but Electrum (correctly) tells me that the invoice is expired since it is now almost half a day old.  I also tried `clear_invoices` but the reserve from the channel is still pending

![stuck_invoice](https://user-images.githubusercontent.com/5009148/88483703-44a07380-cf2f-11ea-88f2-2fb3c8754010.png)

* How do I free up the reserve 101321 sat that were reserved for that invoice without closing the channel?
* Why is the invoice stuck?

### Config

* Client: Electrum 4.0.2 - Run from python source against git tag `4.0.2`
* OS: Windows 10 version 1901
* Python: 3.7.1

**Comment by brianddk** [comment]
The original invoice (as noted above) was only good for 1 hour, but the payment "hung" for about 12 hours.  When I launched Electrum just now, I got a popup that the payment had finally failed, 11 hours after the invoice expired.

I'll close since "wait a while" is a fairly reasonable workaround.  If the wallet devs or users search, they can find this as record of the "wierdness".

**Comment by ecdsa** [comment]
HTLCs can get stuck for a long time. 
This is not really an Electrum issue, although it might be related to the route chosen
