### ISSUE TITLE
Testnet reverse_swap lightning node may be offline or out of capacity

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#6444]
Doing some debugging, as of this post, it appears that the testnet reverse_swap lightning node is operating with the pubkey `034cc6216fa9c95baf29f0f511d6fd2db0b145bafc45d7be91edf342f9c81db154`, but the invoices produced from the reverse_swap API are consistently non-payable.  It appears that either the testnet node handling the payments is offline or out of capacity.

### Reproduction

1. Run Electrum 4.0.2 on Testnet
1. Add `print(invoice)` after line [305 of submarine_swaps.py](https://github.com/spesmilo/electrum/blob/4.0.2/electrum/submarine_swaps.py#L305).
2. From console perform command `reverse_swap(0.00011321, 'dryrun')` to determine `onchain_amt`
3. Perform command `reverse_swap(0.00011321, 0.00010753)` to view the invoice produced
4. Note `No path found` message in Electrum
5. Note that the invoiced node is not visible in [1ML testnet node explorer](https://1ml.com/testnet/)
5. Manually attempt to find a path to that invoice using many different Testnet LN clients

### Config

* Client: Electrum 4.0.2 - with the small patch discussed above
* OS: Windows 10 version 1901
* Python: 3.7.1

**Comment by githorray** [comment]
Do you have an example of the invoice? Does it include any route hints?

**Comment by brianddk** [comment]
> Do you have an example of the invoice? Does it include any route hints?

@githorray 

Good point.  Here's a full invoice it just dropped and indeed, it has not `r` field:

Invoice: `lntb110140n1p0jf2yepp522ncxfqdaasytpvgfvx0gcfyzmxumcwh6p8dqlvzqsdwjma0zrjqdql2djkuepqw3hjqsj5gvsxzerywfjhxuccqzy0sp5kxegqa3xctk83mgpgxdm5xnlrdt40fwxrsdh9ef6g9xgqfcezyqq9qy9qsq7t49kh6jt68tuqh7f0agquefjgpq9p283km4v579d0v5gx9a68z5ephr5heuegjlt0tyxqt9mstxawjhngdwuzq8fhlpcndftaasq0qpvrjc55`

Decode:
```
{                                                                                                                           
    "hrp": "lntb110140n",                                                                                                   
    "timestamp": 1596237977,                                                                                                
    "p": "52a783240def604585884b0cf4612416cdcde1d7d04ed07d82041ae96faf10e4",                                                
    "s": "b1b2807626c2ec78ed01419bba1a7f1b5757a5c61c1b72e53a414c8027191100",                                                
    "d": "Send to BTC address",                                                                                             
    "c": 143,                                                                                                               
    "nine": "9qsq",                                                                                                         
    "signature": "7t49kh6jt68tuqh7f0agquefjgpq9p283km4v579d0v5gx9a68z5ephr5heuegjlt0tyxqt9mstxawjhngdwuzq8fhlpcndftaasq0qp",
    "checksum": "vrjc55"                                                                                                    
}                                                                                                                           
```

**Comment by githorray** [comment]
Maybe the node operator doesn't realize that if they only have private channels that they need to include route/hop hints when generating invoices?

**Comment by ecdsa** [comment]
@bitromortac can you have a look?

**Comment by bitromortac** [comment]
Yes, sure @ecdsa. For now I can tell that swaps should work on testnet as I did several of them (normal and reverse) in the last days.

**Comment by ecdsa** [comment]
all right, in that case I think we can close this.
