### ISSUE TITLE
Open Alias: Electrum doesn't understand it

### ISSUE THREAD

**Issue by theBergmann** [spesmilo/electrum#6446]
Hi there and thank you for the awesome work to provide the best wallet for bitcoin.

I tried OpenAlias. Registered it on my website, and it seems to work. At least the OpenAlias directory knows it:

https://openalias-web.herokuapp.com/donate.mobybit.shop

However, when I type it in Electrum, it doesn't resolve the address. When I try to send, it gives me this error log:

"Zeilennummer1: donate.mobybit.shop... (ValueError('not enough values to unpack (expected 2, got 1)',))"

I tried the standard donate.monero.cc address, and it resolves it. So it works, but not for my OpenAllias.

**Comment by fluffypony** [comment]
Works for me - are you on Electrum 4.0.1?

<img width="906" alt="Screenshot 2020-07-27 at 2 58 48 PM" src="https://user-images.githubusercontent.com/1944293/88544448-ae954780-d019-11ea-80de-14709fdb0975.png">

**Comment by fluffypony** [comment]
Also just checked 4.0.2 and it works fine on that too :)

**Comment by theBergmann** [comment]
Ah, very cool!

I am on version 4.0.1 --

I tried to replace it with donate@mobybit.shop, and now it has it. Maybe it got stuck after not finding it the first time. (but I restarted it several times).

Anyway - thank you very much.
