### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by giosisia84** [spesmilo/electrum#6448]
After sent a transaction and after 2 days with 0 confirmations it turns in local status and when trying to retransmit the transaction it shows "Server returned a error" without any details and I can't understand if transaction has been sent or not I can only remove it if click on icon of transaction with right button mouse...

**Comment by ysangkok** [comment]
Which server does the Network dialog show you being connected to? Do you have auto-connect enabled?

**Comment by giosisia84** [comment]
Yes, I've been selected  Server Automatically Inviato dal mio telefono Huawei-------- Messaggio originale --------Da: Janus Troelsen <notifications@github.com>Data: mer 29 lug 2020, 00:43A: spesmilo/electrum <electrum@noreply.github.com>Cc: giosisia84 <giosisia84@gmail.com>, Author <author@noreply.github.com>Oggetto: Re: [spesmilo/electrum] Server Error (#6448)
Which server does the Network dialog show you being connected to? Do you have auto-connect enabled?

**Comment by giosisia84** [comment]
Itbwas happened also another time when btc value was shifted up in the Market in my opinion it happen ever due to the low fees users sent to my address, because when I sent btc I use ever and ever the maximum fees options and usually I do not have any problems Inviato dal mio telefono Huawei-------- Messaggio originale --------Da: Janus Troelsen <notifications@github.com>Data: mer 29 lug 2020, 00:43A: spesmilo/electrum <electrum@noreply.github.com>Cc: giosisia84 <giosisia84@gmail.com>, Author <author@noreply.github.com>Oggetto: Re: [spesmilo/electrum] Server Error (#6448)
Which server does the Network dialog show you being connected to? Do you have auto-connect enabled?

**Comment by SomberNight** [comment]
The transaction could have turned into "local" as it was dropped from the server's mempool. Check the tx on a block explorer. If the explorer sees it, connect to a different server; if it does not, you can spend those coins again.

Re the error message from a/any server, there should be more text at the bottom of the dialog.
