### ISSUE TITLE
Trezor with autlock feature error when creating new or accessing old wallet

### ISSUE THREAD

**Issue by bosomt** [spesmilo/electrum#6457]
**Enviroment**
Latest Windows 10
Electrum 4.0.2
FW Trezor 2.3.2-731e9b7c

**Behavior**
When you enable autlock feature on Trezor T and device is locked and you will try to create new wallet or loading existing one.
You see error on screenshot and not proper unlock device dialogue. And of course device freezes for some time
Electrum probably check state of device and it gets confused ;)

Send, receive, sign and verify works fine ans it show unlock dialogue. 

@matejcik please check :1st_place_medal: 

**Screenshot**
![photo_2020-07-31_13-46-55](https://user-images.githubusercontent.com/31506317/89032317-b19f7900-d334-11ea-912e-ea055518fd08.jpg)

**Comment by tsusanka** [comment]
JFYI 2.3.2 is to be released on August 5th. We will try to look at it till that date.
