### ISSUE TITLE
Electrum's wordlist contains words who's first four characters are not unique

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#6458]
I've read many recommendations that you only have to back up the first four letters of each of your seed words. That seems to simply be not the case for electrum seeds. I know electrum [isn't BIP39 friendly](https://electrum.readthedocs.io/en/latest/seedphrase.html?highlight=bip39), but it seems prudent to choose word lists where the first four characters are unique for each word - or probably even better would be choosing a wordlist with only words that are less than 4 letters long, since it would eliminate any need for users to be aware of any four-letter uniqueness, since it would be obvious from the length of the words themselves.

Given that Electrum allows entering arbitrary seeds, changing the wordlist that seeds are generated from (and seed entry uses to auto-suggest words) would not be a huge issue. It would only make it slightly more difficult for users to recover from their old seeds.

Thoughts?

**Comment by SomberNight** [comment]
We have been using the BIP39 English wordlist to generate seeds since version 2.0 so it has this 4-char unique prefix property.

The old mnemonics before that used a [different wordlist](https://github.com/spesmilo/electrum/blob/f49e766b218649a5b64a196bcc055e41291fb223/electrum/old_mnemonic.py#L31).

**Comment by fresheneesz** [comment]
Then why am I still seeing both "good" and "goodbye" in the autocomplete when creating a new wallet with the latest Android version?

**Comment by SomberNight** [comment]
> Note that the [...] word suggestions in the GUI when entering a mnemonic are using the union of the two wordlists, so the prefixes are not unique there 

`good` and `goodbye` appear in the [old list](https://github.com/spesmilo/electrum/blob/f49e766b218649a5b64a196bcc055e41291fb223/electrum/old_mnemonic.py#L31), and
`good` appears in the [bip39 list](https://github.com/spesmilo/electrum/blob/f49e766b218649a5b64a196bcc055e41291fb223/electrum/wordlist/english.txt)

> Given that Electrum allows entering arbitrary seeds, changing the wordlist that seeds are generated from (and seed entry uses to auto-suggest words) would not be a huge issue. It would only make it slightly more difficult for users to recover from their old seeds.

This suggestion of yours could only apply to the Qt GUI as the kivy GUI does not allow restoring arbitrary seeds atm.

**Comment by fresheneesz** [comment]
> good and goodbye

So the autocomplete uses both lists? At some point the old list should be phased out entirely (and not even affect any autocomplete). Is there a date in your mind when the old word list should be removed entirely?

> the kivy GUI does not allow restoring arbitrary seeds atm.

Is that on the roadmap?

**Comment by SomberNight** [comment]
>> word suggestions in the GUI when entering a mnemonic are using the union of the two wordlists
>
> So the autocomplete uses both lists? 

By "union" I meant set theoretic union, so yes.

>>  the kivy GUI does not allow restoring arbitrary seeds atm.
>
> Is that on the roadmap?

Well the issue is the custom keyboard. We use a custom keyboard because we don't trust the Android keyboard with the seed.
This makes allowing "arbitrary" seeds difficult. It would be easy to allow freely inputting anything the custom keyboard can represent but then the next issue/ticket would request some accented characters or numbers... :/
