### ISSUE TITLE
"Check for Updates" Screen has a bug

### ISSUE THREAD

**Issue by maltokyo** [spesmilo/electrum#6462]
When checking for latest version on Mac version 4.0.2, I get this, it is confusing.

![image](https://user-images.githubusercontent.com/1388507/89123373-26a6b600-d4cf-11ea-982e-2f31ac53ab9e.png)

**Comment by danuker** [comment]
Have you installed Electrum from https://electrum.org/ ?

**Comment by ecdsa** [comment]
this has already been reported
