### ISSUE TITLE
not to use change address in rpc

### ISSUE THREAD

**Issue by sanada08** [spesmilo/electrum#6463]
Let me know how not to use change address in rpc. Whenever i am trying to transfer fund. Fund moved to change address. I dont want to use change address.

**Comment by SomberNight** [comment]
note: this is a per-wallet setting persisted in the wallet file:
https://github.com/spesmilo/electrum/blob/ec6baa12f81065ee5b110d6c277a24d752acb11d/electrum/wallet.py#L292

It is currently not configurable via CLI/RPC.

**Comment by sanada08** [comment]
Thanks. Let me try
