### ISSUE TITLE
Minor UI/UX improvements to the top section of electrum GUI setup pages

### ISSUE THREAD

**Issue by Bosch-0** [spesmilo/electrum#6466]
Just a few minor suggestions for a slightly better user experience for the setup pages of the electrum GUI. 

This was done on the windows installer version 4.0.2. 

1. The windows installer, even after installed, still says 'install wizard' (pictured below), this doesn't seem necessary and may add confusion to users. 

2. Currently there is no option to minimize the GUI window, this should be available for convenience as well as security - say if you need to quickly minimize the GUI when generating a wallet to prevent someone peering over your shoulder and seeing your seed phrase. 

3. Added a maximize window option - not entirely necessary but some users may want this option. 

4. Moved the help option to the bottom left to avoid cluttering the top section. Also changed from '?' to 'help' as ? can be ambiguous. 

changes are shown below before and after.

![2020-08-03_16-07-17](https://user-images.githubusercontent.com/55287964/89160665-0137ac00-d5a4-11ea-9b7a-69a4a26fd555.jpg)

**Comment by jingxi285** [comment]
Probably just "Electrum" is enough? keep-it-simple etc

**Comment by JeremyRand** [comment]
> The windows installer, even after installed, still says 'install wizard' (pictured below), this doesn't seem necessary and may add confusion to users.

> Probably just "Electrum" is enough? keep-it-simple etc

Note that the hardware wallet plugins' Qt GUI's refer to "the install wizard", so  if we rename this window, the hardware wallet GUI strings may need re-wording to avoid confusing users.

**Comment by accumulator** [comment]
fixed in 78fbc27ec0835781f91ef9db67ab756ddbe57643
