### ISSUE TITLE
"synchronising" during few days

### ISSUE THREAD

**Issue by adrastee** [spesmilo/electrum#6468]
I imported few private keys in a existing wallet.
Electrum is "synchronising... X/Y" for a few days now. Message is in the lower status bar.  After few hours Y going again at zero. bug?
Why so slow? How many minute/hour should it take in theory per private key?
Thanks.

**Comment by Pillagr** [comment]
The wallet must rescan the entire blockchain for these private keys. Thus, it could take a long time. Otherwise I cannot be of help. Hopefully someone else can provide more detail?

**Comment by adrastee** [comment]
What's the limits of the server?

**Comment by SomberNight** [comment]
Please check [debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging).

Limits depend on which server you connect to, it's typically a few thousand addresses.

**Comment by SomberNight** [comment]
cannot make progress here without logs
