### ISSUE TITLE
General issue with new version

### ISSUE THREAD

**Issue by venomone** [spesmilo/electrum#6469]
Hello,

since the release of electrum 4 commands like "electrum validateaddress"
are now just working if the wallet is running in daemon mode, why that?
I dont see the benefit for that and in most cases this will crush some implementations because they first have to
spawn up a daemon process before they can actually work.

For me the point is that I use electrum to validate addresses, but now i first have to run the daemon to make my functions work again :(

Any way to make this working without running spawning a daemon first?

**Comment by ecdsa** [comment]
you have to pass the -o option to run a command offline
`electrum validateaddress -o blah`
