### ISSUE TITLE
Need more fee steps in "Mempool" mode.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#6474]
Two problems
1mb is already too low for next block, need more steps below 1mb.
15mb is about by how low the mempool goes when it slows down between america's business hours and night time. 

https://github.com/spesmilo/electrum/blob/b6db20157079d271c8304fa1d3e6927617babce1/electrum/simple_config.py#L24

Suggested:
FEE_DEPTH_TARGETS = [15000000, 10000000, 5000000, 2000000, 1000000, 800000, 600000, 400000, 250000, 100000]

**Comment by Transisto** [comment]
@SomberNight @ecdsa 

This doesn't seems contentious,

Do you understand that 1mb is at least 2 block and 0.5 might be too high?

Almost everything requiring next block is happening below 1mb, So we would benefit form more intervals there.

**Comment by SomberNight** [comment]
Right, you make a good point that maybe there should be a few more steps below 1 MB.
However, it is not so simple -- the mempool data (compact histogram) often does not have a high enough resolution.

Consider this example, of recent data from mainnet from an electrumx server:
```
>>> config.mempool_fees = [[4.0, 125507], [3.1, 143778], [2.9, 126219], [2.4, 191563], [2.3, 1099738], [2.0, 54228], [1.9, 460051], [1.3, 399357], [1.1, 403772], [1.0, 425873]]
>>> config.depth_target_to_fee(100_000)
5000
>>> config.depth_target_to_fee(200_000)
4100
>>> config.depth_target_to_fee(300_000)
3900
>>> config.depth_target_to_fee(400_000)
3400
>>> config.depth_target_to_fee(500_000)
3400
>>> config.depth_target_to_fee(600_000)
3300
>>> config.depth_target_to_fee(700_000)
3300
>>> config.depth_target_to_fee(800_000)
3300
>>> config.depth_target_to_fee(900_000)
3300
>>> config.depth_target_to_fee(1_000_000)
3300
>>> config.depth_target_to_fee(1_500_000)
3300
>>> config.depth_target_to_fee(2_000_000)
2900
```

-----

Compare these compact histogram returned by two different servers (first electrumx, second electrs) at the ~same time for mainnet:
`I/n | network | fee_histogram [[17.3, 100784], [9.9, 116778], [6.4, 123093], [4.2, 136173], [2.9, 148152], [1.8, 208287], [1.3, 354395], [1.1, 451234], [1.0, 529717]]`
`I/n | network | fee_histogram [[26.032001495361328, 50337], [17.3880558013916, 54855], [10.095237731933594, 50483], [9.98532772064209, 63532], [8.6713285446167, 50124], [7.440706729888916, 51257], [6.055046081542969, 50175], [5.952952861785889, 50780], [5.667349815368652, 51013], [4.053811550140381, 50544], [3.492248058319092, 50042], [3.0224835872650146, 50115], [2.985321044921875, 51012], [2.349761486053467, 50557], [2.0617740154266357, 50056], [1.893869161605835, 89094], [1.7000000476837158, 50992], [1.5177935361862183, 50192], [1.3935309648513794, 55463], [1.300008773803711, 140813], [1.300005555152893, 90825], [1.2000131607055664, 135350], [1.190205693244934, 129027], [1.1325581073760986, 54767], [1.1272286176681519, 53091], [1.127142310142517, 51802], [1.0863513946533203, 61125], [1.0370125770568848, 50075], [1.0248756408691406, 57584], [1.0174672603607178, 51079], [1.0114942789077759, 50439], [1.006695032119751, 54622], [1.0036795139312744, 52822], [1.0034942626953125, 71367], [1.002659559249878, 50149], [1.0012986660003662, 50168], [1.0, 29712]]`

-----

The electrum protocol currently does not give any guarantees re resolution and precision of the mempool compact fee histogram. Looks like electrs gives higher resolution data than e-x. We could increase the resolution for e-x somewhat (too high resolution would waste bandwidth).

**Comment by SomberNight** [comment]
> We could increase the resolution for e-x somewhat 

done in https://github.com/spesmilo/electrumx/commit/265a5a87b8ad01f739049c0b1e80923aab318f58

**Comment by SomberNight** [comment]
> Suggested:
FEE_DEPTH_TARGETS = [15000000, 10000000, 5000000, 2000000, 1000000, 800000, 600000, 400000, 250000, 100000]

I've added more steps in https://github.com/spesmilo/electrum/commit/4dd94172a6dc87a32bd6b0542c7c985f23afab1f to the next block region. Used your suggestion, but left out the 15 MB step.

>  15mb is about by how low the mempool goes when it slows down between america's business hours and night time.

I think this is a rather arbitrary number and I don't see much value in adding it. If you want to pay a very low fee, you can just try with 1 s/b.

**Comment by Transisto** [comment]
Thank you very much, I just noticed that feature!
