### ISSUE TITLE
update_checker.py - version current>=latest 

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [spesmilo/electrum#6477]
latest reported as 3.3.8 but this is not latest.
causing 3.3.8 clients not get noticed about new major update.
![image](https://user-images.githubusercontent.com/46166740/89381614-bdef5180-d6f9-11ea-9e86-303b862cb5f8.png)

[https://electrum.org/version](https://electrum.org/version)

**Comment by amarett0** [comment]
check: #6338

**Comment by ecdsa** [comment]
closing, duplicate
