### ISSUE TITLE
Wierd Stuff: (1) Transaction disappeared! (2) Very very high fees added

### ISSUE THREAD

**Issue by haseebanjum** [spesmilo/electrum#6479]
This happened to me for the first time. Using Electrum v3.3.8 (latest so far).

I sent about $75 in BTC to a friend (0.00667974 BTC). The fee bar was set in the middle (and was showing around 50 sat). I pressed send and it deducted $112!! (so I paid $37 in fees???)

Also Next transaction, I sent 0.02187129 BTC to a wallet Fee bar was again in the middle. I could see the transaction (unconfirmed) on blockchain.. But after as while when I go to blockchain, it says transaction not found!!

The other wallet hasn't recieved it!! THIS IS THE ADDRESS: https://blockstream.info/tx/3c086a5ed7c02a2cc44d56f62c48bb11ad016e427a294941b648014afbfb2e97

Any ideas?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> I could see the transaction (unconfirmed) on blockchain.. But after as while when I go to blockchain, it says transaction not found!!
> Any ideas?

See:
https://www.blockchain.com/de/btc/tx/3c086a5ed7c02a2cc44d56f62c48bb11ad016e427a294941b648014afbfb2e97



> This happened to me for the first time. Using Electrum v3.3.8 (latest so far).

latest is v 4.0.2

**Comment by haseebanjum** [comment]
> 
> 
> > I could see the transaction (unconfirmed) on blockchain.. But after as while when I go to blockchain, it says transaction not found!!
> > Any ideas?
> 
> See:
> https://www.blockchain.com/de/btc/tx/3c086a5ed7c02a2cc44d56f62c48bb11ad016e427a294941b648014afbfb2e97
> 
> > This happened to me for the first time. Using Electrum v3.3.8 (latest so far).
> 
> latest is v 4.0.2

Thank you so much,

When I go to Help -> Check For Updates, I get this: (screenshot: https://imgur.com/a/muuTH74)

(Basically it says you are already using the latest version

Your versionL 3.3.8 - Latest version: 3.3.8

Using it on Windows 10 64 bit

Could it be a local issue (like virus/malware)? or something wrong with this specific version of electrum?

**Comment by ecdsa** [comment]
no, the version notification for 4.0.2 is not enabled yet.
your transaction is confirmed.
the fee you saw is around 50 sats/byte, not 50 sats total.
