### ISSUE TITLE
Error when use lightning

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#6481]
I create wallet A and wallet B and all start lightning
Now I open channel use NodeA(022ce35fa95a17cd032019ca69cbfc0a5329d43d9395343629b4cad4f287b612f8) and NodeB(03da4b559b40af12d00bb291a40140c51bd1e1218aafe3b1fbf28d6768384db33a) as shown below:
![2020-08-06 00-36-26 的屏幕截图](https://user-images.githubusercontent.com/9347690/89504500-f6843f00-d77c-11ea-8ca3-f9770f75d3b8.png)

but it failed,error is (Could not open channel: ConnStringFormatError("Don't know any addresses for node: 03da4b559b40af12d00bb291a40140c51bd1e1218aafe3b1fbf28d6768384db33a",)) as show below:
![2020-08-06 00-38-01 的屏幕截图](https://user-images.githubusercontent.com/9347690/89504949-b40f3200-d77d-11ea-85ef-99c16b71acd3.png)

**Comment by ecdsa** [comment]
that is normal.
you should pass a connection string, not just a pubkey.
the node you connect to should also be a listening node.

check our regtest examples if you want to do that

**Comment by shuaiLiWang** [comment]
> that is normal.
> you should pass a connection string, not just a pubkey.
> the node you connect to should also be a listening node.
> 
> check our regtest examples if you want to do that

Every time I restart the computer, I run the regtest examples program successfully the first time
Then it keeps failing. So i just test forwarding, The failed log is `not find path`  when lnpay

**Comment by ecdsa** [comment]
if you run the regtests manually, you need to stop the daemons started in the test once the test has completed
