### ISSUE TITLE
electrum 4 incompatible with my offline electrum 3 multisig wallet

### ISSUE THREAD

**Issue by farzher** [spesmilo/electrum#6483]
(2 of x multisig. 1 phone online 1 phone offline)

`"Unable to decode QR data"`

obviously you changed how QR codes work.

is there anyway to downgrade my auto-updated android electrum to v3?

if not, could you add a compatibility option to generate/read v3 QR codes?

i don't want to upgrade my offline wallet, and i don't want to uninstall electrum 4 then install electrum 3 from an apk because it might delete my wallets?

**Comment by ecdsa** [comment]
no, you cannot downgrade.
sorry but we will no longer support the old format; you will have to upgrade your offline wallet
