### ISSUE TITLE
[Android-REQ]: Add "swap" button next to "new" on channel dialog for submarine swaps

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#6486]
In Android there is no option (that I see) to get to the Submarine-Swap feature.  Please consider adding a "Swap" button next to the "New" button in the channel dialog.  This would provide parity with the QT interface which has the "Swap" button on the channel tab.

**Comment by bitromortac** [comment]
I could work on this next.

**Comment by ecdsa** [comment]
@bitromortac that would be great. I think the slider idea makes more sense on android.

**Comment by ecdsa** [comment]
closing this: #6916 was merged manually.
