### ISSUE TITLE
Not able to withdraw BTC, showing error

### ISSUE THREAD

**Issue by mohit1250** [spesmilo/electrum#6493]
To whomsoever knows about this type of error please help,
         I have BTC in my electrum wallet using hardware device and when I m trying to withdraw, it shows error and locked for 24 hours what should I do please help me.
Everytime it's getting locked.
Help please.
Thanks.

**Comment by ecdsa** [comment]
can you show the precise error message?

**Comment by SomberNight** [comment]
More details needed. For example, what kind of hardware wallet?

**Comment by ecdsa** [comment]
nothing useful in this report
