### ISSUE TITLE
not enough funds 

### ISSUE THREAD

**Issue by ryguyhelpme** [spesmilo/electrum#6497]
my bitcoin wont send i am unhappy with Electrum i want to transfer my coin elsewhere but it wont let me send it out

**Comment by lucasmoten** [comment]
It may be helpful if you provide more details about the specific error you are having.

If you have your seed words when you created the wallet, you should be able to load that up in another wallet.

**Comment by ecdsa** [comment]
this kind of report is useless.
sorry @ryguyhelpme but I am closing this until you change your mind and decide to provide helpful information
