### ISSUE TITLE
Spend a coin not working with Trezor

### ISSUE THREAD

**Issue by leinadyvon** [spesmilo/electrum#6498]
Hi. I'm trying to spend a specific coin (by going into Coins tab and clicking on Spend on a specific address) while connected to Trezor and I'm getting this weird error message (attached). Trezor screen stalls on  "Signing transaction...". I'm spending the whole coin amount (no change address). Any idea what could be the issue?

![trezor-electrum](https://user-images.githubusercontent.com/69481783/89823294-9ea45a00-db27-11ea-9bc2-8b5e2b1296ac.png)

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/pull/6198

This was fixed in 4.0.x. Please update from the official website.
