### ISSUE TITLE
PermissionError (WinError 5) failing to write wallet file to disk

### ISSUE THREAD

**Issue by PerunNL** [spesmilo/electrum#6501]
It is impossible to sell my bitcoins. They are in my Electrum wallet but whatever I do it hangs all the time. I have send multiply bug reports already. I use 4.0.2 on Windows 10. Please let me get rid of my coins.

When I press 'Pay' Electrum is gone. I have sold BTC in 2019 with the same wallet.

When using version 3.0.5 or 3.0.6 Electrum hangs immediately after submitting the wallet's password. Versions 3.3.5, 3.3.6 or 3.3.8 doesn't work either.

Windows logs mention Qt5Core.dll.

**Comment by rdymac** [comment]
Electron?

Do you realize you are opening and issue in the Electrum (BTC) github?

Unfortunately, nothing you’ve mentioned help understanding what could be wrong with your installation or the app itself. You need to share more information about what you are having issues with, and only if it is about the official Electrum (Bitcoin, BTC).

**Comment by PerunNL** [comment]
Yes I mean Electrum. How do I gather more information?

**Comment by AbdussamadA** [comment]
enable log files and then pastebin them:

https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging

https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#where-is-the-electrum-datadir-located

**Comment by PerunNL** [comment]
Thanks for providing the links. I assume the part "Using the Qt GUI" applies to Windows.
PasteBin doesn't work so I'll past the last part here: 

`20200811T014627.710770Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20200811T014627.710770Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0000
20200811T014627.712760Z |    DEBUG | util.profiler | AddressList.update 0.0000
20200811T014628.519001Z |     INFO | network | connecting to btc.litepay.ch:50002:s as new interface
20200811T014628.631155Z |     INFO | interface.[btc.litepay.ch:50002] | connection established. version: ['ElectrumX 1.14.0', '1.4']
20200811T014628.652147Z |     INFO | interface.[btc.litepay.ch:50002] | set blockchain with height 643147
20200811T014628.652147Z |     INFO | interface.[btc.litepay.ch:50002] | skipping header 643146
20200811T014628.653146Z |     INFO | network | switching to btc.litepay.ch:50002:s
20200811T014628.660151Z |     INFO | plugins.trustedcoin.trustedcoin.Wallet_2fa.[maatie] | set_up_to_date: False
20200811T014628.663147Z |     INFO | lnwatcher.LNWalletWatcher | set_up_to_date: False
20200811T014628.696318Z |     INFO | network | fee_histogram [[144, 100348], [142, 313209], [141, 6941], [120, 45219], [106, 168682], [55, 152362], [20, 198788], [16, 329069], [15, 379482], [14, 396690], [13, 709002], [12, 194013], [11, 183522], [10, 682805], [9, 140744], [8, 306552], [7, 223317], [6, 518185], [5, 840136], [4, 1549937], [3, 1286409], [2, 2095429], [1, 3617336]]
20200811T014628.769560Z |     INFO | lnwatcher.LNWalletWatcher | set_up_to_date: True
20200811T014628.769560Z |     INFO | plugins.trustedcoin.trustedcoin.Wallet_2fa.[maatie] | set_up_to_date: True
20200811T014628.813557Z |    ERROR | interface.[btc.litepay.ch:50002] | Exception in wrapper_func: PermissionError(13, 'Toegang geweigerd')
Traceback (most recent call last):
  File "electrum\util.py", line 1037, in wrapper
  File "electrum\interface.py", line 466, in wrapper_func
  File "electrum\interface.py", line 490, in run
  File "electrum\interface.py", line 630, in open_session
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 82, in _start_tasks
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 255, in main
  File "electrum\wallet.py", line 352, in set_up_to_date
  File "electrum\wallet.py", line 288, in save_db
  File "electrum\wallet_db.py", line 1216, in write
  File "electrum\wallet_db.py", line 1224, in _write
  File "electrum\util.py", line 390, in <lambda>
  File "electrum\util.py", line 386, in do_profile
  File "electrum\storage.py", line 112, in write
PermissionError: [WinError 5] Toegang geweigerd: 'c:\\users\\perun\\appdata\\roaming\\electrum\\wallets\\maatie.tmp.8624' -> 'c:\\users\\perun\\appdata\\roaming\\electrum\\wallets\\maatie'`

"Toegang geweigerd" means Access denied. I use Electrum as a user with Administrator rights. I get the same results when I forcefully open Electrum as a Administrator.

**Comment by ysangkok** [comment]
@PerunNL could you screenshot [the permissions window](https://www.online-tech-tips.com/computer-tips/set-file-folder-permissions-windows/#:~:text=There%20are%20basically%20six%20types,need%20to%20worry%20about%20those.)?

**Comment by SomberNight** [comment]
Try copying the wallet file and opening the copy. I suspect the file might be opened (and locked) by another process.

**Comment by PerunNL** [comment]
I sold all of my Bitcoin by using a live installation of Mint. I'm glad I'm freed from this.
