### ISSUE TITLE
signtransaction at the commandline prints 02000000000000000000 to stdout instead of the transaction

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#6502]
Electrum 3.x used to print the (partially) signed transaction to stdout when calling signtransaction from the CLI.
Electrum 4.0.2 (from the debian testing repos) instead always prints 02000000000000000000 to stdout.
The behavior is the same on testnet and mainnnet.

**Comment by ulrichard** [comment]
A zip with files to easily reproduce can be found at: 
https://ipfs.io/ipfs/Qmcd4gKytdi5zSmihVF3zFdiK5fGrhT99umciXAiwy5GKR?filename=ElectumBugreport.zip

**Comment by ulrichard** [comment]
[ElectumBugreport.zip](https://github.com/spesmilo/electrum/files/5056096/ElectumBugreport.zip)

**Comment by ulrichard** [comment]
So far, I tracked it to    invalidate_ser_cache() called from  transaction::combine_with_other_psbt()

**Comment by SomberNight** [comment]
Thank you for the detailed report.
Note that wallet1 and wallet2 are the same cosigner from the multisig set in your example (they have the same seed).
