### ISSUE TITLE
Electrum rejects Bitcoin Core 0.20.1 psbt's

### ISSUE THREAD

**Issue by Fonta1n3** [spesmilo/electrum#6503]
In the latest Bitcoin Core release psbt's may include both `non_witness_utxo` and `witness_utxo` to mitigate the vulnerability Trezor found recently.

Electrum rejects these psbt's as being invalid.

**Comment by lucasmoten** [comment]
This may be related to #6494 as the PSBT created by Electrum export is not compliant with BIP 174

**Comment by Fonta1n3** [comment]
@lucasmoten Sorry I will be more specific. I create a psbt with Bitcoin Core (using it as a watch-only wallet), sign it with Fully Noded, then pass to Electrum who is another signer in my quorum (have been using this setup without issue until now). With Bitcoin Core 0.20.1 Electrum returns this error:
<img width="419" alt="Screen Shot 2020-08-12 at 08 54 30" src="https://user-images.githubusercontent.com/30832395/89963267-b55ac600-dc79-11ea-92a5-2680aa5fbc74.png">

I use Electrum as signer in my setup and it really is quite nice, however this is a show stopper, I would like to be able to update Bitcoin Core and use Electrum.. The change in Bitcoin Core is only to help prevent the attack Trezor disclosed. I believe all you guys need to do is prevent this error from getting thrown and allow a psbt to be signed even if it has both utxo types in an input.

**Comment by lucasmoten** [comment]
It may help to provide more information

Does this appear when choosing Load Transaction? Or is the process different

What version of Fully Noded?

**Comment by Fonta1n3** [comment]
@lucasmoten in Electrum: "Tools" > "Load transaction" > "From file"

The psbt is passed as a .psbt file which I have been using with Electrum and Coldcard without issue. See this .zip of said file (it is a single sig as thats what I have set up on testnet now, still returns same error as my multisig mainnet psbt):
[FullyNodedPSBT 7.psbt.zip](https://github.com/spesmilo/electrum/files/5060135/FullyNodedPSBT.7.psbt.zip)

 I am the creator of Fully Noded fwiw so can answer any questions about how it does things. Its the latest version 0.1.68, but again the psbt is created with `bitcoin-cli` over json-rpc not by Fully Noded per say. 

As a test you can use the above file or this unsigned base 64 psbt which was created with `bitcoin-cli walletcreatefundedpsbt` using 0.20.1:

```
cHNidP8BAHECAAAAAbR6+xLd9ffZVYI9hLXwAUKTM8a8GtVU2p4aYAq3vtuNAAAAAAD9////AiBNzQAAAAAAFgAUI7Pw76botjxPDTlaX0JC5Ikn54RAQg8AAAAAABYAFBlxhyT9tQCDtWMlQ7wytPfJ0S1XAAAAAAABAHECAAAAAbYRDFzrrCjRacmscuGF3HQLqyH1pXBSG9fFbbPPe+wdAAAAAAD9////Au2P3AAAAAAAFgAUj9su0sUV8KaZE496YwSqkiVzmR8MnQIAAAAAABYAFPK6T5MCIQK9O1oFXZFQyNAH+a/BAAAAAAEBH+2P3AAAAAAAFgAUj9su0sUV8KaZE496YwSqkiVzmR8iBgNie7unPYgzjVI3nh7lwwrf6JSDCtBNcfci/USsTECaEhjCcFt+VAAAgAEAAIAAAACAAQAAABwAAAAAIgIC5+L0UDQHvPsjJIHUShEppZkifKQMEVlHbi3q1CK+EjEYwnBbflQAAIABAACAAAAAgAEAAAAgAAAAACICA9UODX0ogv4bExA3KMUO7NB+nKOBc9V1+1okhaVSZbFPGMJwW35UAACAAQAAgAAAAIAAAAAAHwAAAAA=
```

**Comment by lucasmoten** [comment]
I wonder if some of these issues may be addressed in the master branch.  Release 4.0.2 was in early July 8, but this commit occurred more recently (July 21) that seems to relate to your issue: https://github.com/spesmilo/electrum/commit/73cf007048b4f9381814d065c60999eda70e158c

**Comment by Fonta1n3** [comment]
> I wonder if some of these issues may be addressed in the master branch. Release 4.0.2 was in early July 8, but this commit occurred more recently (July 21) that seems to relate to your issue: [73cf007](https://github.com/spesmilo/electrum/commit/73cf007048b4f9381814d065c60999eda70e158c)

I will try.

**Comment by Fonta1n3** [comment]
@lucasmoten can confirm after building from master that the psbt is not rejected, but I am getting other issues now... Most importantly the sign button is not responsive along with pretty much every other button... I am on macos fwiw.

**Comment by Fonta1n3** [comment]
@lucasmoten So I have instead compiled from master on Ubuntu, buttons not frozen, however when I add the transaction as detailed above the "sign" button in Electrum is disabled... Any idea why that may be? I was using it in this manner previously without issues. Shall I raise a separate issue? I can export the private keys so I know it still holds the necessary keys to sign.

**Comment by SomberNight** [comment]
As above, the original issue should be fixed by https://github.com/spesmilo/electrum/commit/73cf007048b4f9381814d065c60999eda70e158c

I am unsure whether some of your follow-up problems are related. Feel free to open new issue(s) for them; if possible with reproduction steps.
