### ISSUE TITLE
client 4.0.2 doesn't show correct version

### ISSUE THREAD

**Issue by elwooddowd** [spesmilo/electrum#6504]
when performing an update-check via "_Help_" -> "_Check for updates_" the client shows 3.3.8 as the latest version

![2020-08-12-000679](https://user-images.githubusercontent.com/68039643/90024802-98dc7f00-dcb5-11ea-8977-8fd244b384f2.png)

**Comment by lucasmoten** [comment]
I think @ecdsa  needs to update the info at https://electrum.org/version manually which is where this check compares against.  It needs to be signed.  I asked Stephan Livera to ping Thomas and Ghost on this but it didn't come up in the recent podcast.

**Comment by amarett0** [comment]
Check: #6338
