### ISSUE TITLE
Cannot Spend (Watch Only Wallet)

### ISSUE THREAD

**Issue by Will8202** [spesmilo/electrum#6505]
I upgraded to 3.3.8 on Windows 10 with the latest updates and now my wallet will not spend. It has turned into an imported (Watch Only Wallet)

**Comment by engenegr** [comment]
Hey, @Will8202. Watch-only wallets can't spend coins by definition.

**Comment by Will8202** [comment]
Thank you for the reply, but can you tell me how to turn it back into a spend wallet? A watch-only wallet is useless to me and my BTC is trapped.

**Comment by engenegr** [comment]
@Will8202 you should have seed. Try to restore it using your seed words.

**Comment by Will8202** [comment]
When I try to restore the wallet to a 2FA wallet, after I finish
typing in my seed phrase the Next tab does not highlight. Thus, it
will not allow me to go any further.

On 8/13/20, llya Evdokimov <notifications@github.com> wrote:
> @Will8202 you should have seed. Try to restore it using your seed words.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/spesmilo/electrum/issues/6505#issuecomment-673536026


-- 
Thank you,

William Breaker
73's   KN4WTB

**Comment by ecdsa** [comment]
was your wallet 2FA in the first place?
also, no, upgrading does not turn your wallet into watching only
are you sure it is the same wallet you are opening?

**Comment by Will8202** [comment]
It was a long time ago that I created the wallet when I first got into crypto. I was mining to this wallet and never spent any so it is possible that it was a watch-only. 
It is the same wallet because I can see the receive transactions. I would like to move the BTC to my Ledger Nano wallet. 

Thank you,

William Breaker

**Comment by ecdsa** [comment]
do you remember if the seed was created by electrum?

**Comment by Will8202** [comment]
Yes, the seed was created by electrum. 

Thank you,

William Breaker

**Comment by engenegr** [comment]
@Will8202 I'm not familiar with 2FA wallets in Electrum but you have to be sure you are restoring wallets of the same types from the same seeds (in Electrum it might be Electrum seed or BIP39 seed).

**Comment by Will8202** [comment]
Okay, the wallet works as watch-only. How do I turn it into a spend wallet to transfer the BTC?

Thank you,

William Breaker

**Comment by ecdsa** [comment]
you did not answer my question: was your wallet a 2FA wallet in the first place?
why did you "restore to a 2FA"?

**Comment by Will8202** [comment]
It was a long time ago that I created the wallet. I am not sure what type of wallet it was. I never spent BTC from the wallet I just mined BTC to it. 
The wallet never did restore but it is a functional watch-only wallet that I would like to transfer the BTC to my Ledger hardware wallet. When I created it I probably made a mistake by creating a watch-only. How can I transfer the BTC?

Thank you,

William Breaker

**Comment by ecdsa** [comment]
try to restore as a a standard wallet.

**Comment by Will8202** [comment]
That worked like a charm. I over complicated things by looking on an
internet site which told me that it needs to be a 2FA wallet to spend.

Thank you so much for your help.


On 8/14/20, ThomasV <notifications@github.com> wrote:
> try to restore as a a standard wallet.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/spesmilo/electrum/issues/6505#issuecomment-674131554


-- 
Thank you,

William Breaker
73's   KN4WTB

**Comment by ecdsa** [comment]
reopening: I think the wizard should be robust to that and restore a standard wallet
