### ISSUE TITLE
Request Receiving BTC

### ISSUE THREAD

**Issue by aradour** [spesmilo/electrum#6506]
Hello everybody! What I noticed is that when I request to receive money I have the address okay, then I copy it but its different from the one I see, should I manually put the address I see or the one I copied is still the same but like multi address for security? Never seen this before, i'm worried that If I sent the money on the copied address I will not receive them. 
like Electrum shows me the address, I copy it, and it's different, I cannot scan as well. Anyone can tell me why or is it still secure that I will receive my BTC? 
![Immagine 2020-08-12 172338](https://user-images.githubusercontent.com/23318998/90035481-245c0d00-dcc2-11ea-9069-24178b38805e.png)

this is the address I see, when I copy it is 13pd7FkAaBwtg1WjuNfSy2YkdSxmAFZxAe

**Comment by githorray** [comment]
https://mempool.space/address/13pd7FkAaBwtg1WjuNfSy2YkdSxmAFZxAe

Maybe you have a malware infection.

https://techcrunch.com/2018/07/03/new-malware-highjacks-your-windows-clipboard-to-change-crypto-addresses/

**Comment by aradour** [comment]
Should I reinstall electrum?

**Comment by aradour** [comment]
oh god, But i have coins in mine still, if reinstalling it might help? Or what should I do any sugggestions?

**Comment by aradour** [comment]
I had my antivirus off for awhile for some stuff, should I turn it on and reintall maybe?

**Comment by aradour** [comment]
you were right! I had some virus! Thanks im glad I didnt charge up my wallet before knowing this. I just installed good antivirus programs and now everything is okay, thank you very much!

**Comment by githorray** [comment]
Good news. Don't forget to close the issue.

**Comment by aradour** [comment]
Thank you for your help! And sure!
