### ISSUE TITLE
Cant sign transaction

### ISSUE THREAD

**Issue by Rasar7** [spesmilo/electrum#6508]
I updated the wallet to version 4.0.2 and now, when I try to sign a transaction, I receive a message:
TrustedCoinException Error: 413 Request Entity Too Large

**Comment by ecdsa** [comment]
@badmofo can you have a look?

**Comment by Rasar7** [comment]
![err](https://user-images.githubusercontent.com/69670559/90272309-a5f49c00-de76-11ea-95b5-ec05592528d0.jpg)

**Comment by lucasmoten** [comment]
Yikes! Is that an infected version of Electrum?

**Comment by Rasar7** [comment]
> Yikes! Is that an infected version of Electrum?

????   No.

**Comment by lucasmoten** [comment]
I misunderstood the error message. I know Electrum supports api.trustedcoin.com, but I've never used it.  
Can you provide more details about the conditions of your transaction?  For example, number of UTXOs involved in the transaction you are setting up

**Comment by Rasar7** [comment]
> I misunderstood the error message. I know Electrum supports api.trustedcoin.com, but I've never used it.
> Can you provide more details about the conditions of your transaction? For example, number of UTXOs involved in the transaction you are setting up

The problems started immediately after updating the version to 4.0.2. I have already made many attempts to make various transactions to different wallets, with different fee levels, from two different computers with different providers. The result is the same. I even tried installing the old version of Electrum that I used before the update, but now the program reports that my wallet is not suitable for such an old version(Apparently 4.0.2 made some changes to the wallet file). Judging by the fact that the developers are not in a hurry to help in this situation (although their fault is obvious), perhaps they did it specifically to steal from me. Be careful not to store funds in your Electrum wallet.

**Comment by badmofo** [comment]
> @badmofo can you have a look?

Some of the request entity limits on api.trustedcoin.com weren't taking into account how much larger PSBT could potentially be compared to the legacy format.  I've just increased these limits 4x.  @Rasar7 can you retry your transaction?

**Comment by Rasar7** [comment]
> > @badmofo can you have a look?
> 
> Some of the request entity limits on api.trustedcoin.com weren't taking into account how much larger PSBT could potentially be compared to the legacy format. I've just increased these limits 4x. @Rasar7 can you retry your transaction?

Successfully done! thank you a lot!!
