### ISSUE TITLE
Ledger: New BIP44 checking in ledger firmware 1.6.1+ breaks electrum

### ISSUE THREAD

**Issue by smogm** [spesmilo/electrum#6511]
Since this new BIP44 enforce checking (https://github.com/LedgerHQ/app-bitcoin/commit/bae78c044ace0480945f84db84bf67a8790dfacb) in the app-bitcoin ledger app, the electrum ledger plugin seems not working anymore.

https://support.ledger.com/hc/en-us/articles/360015739499-Sign-or-derivation-path-is-unusual

During startup of the electrum client the Ledger shows "The derivation path is unusual" a few times which you have to "approve" each time.
Maybe the startup and initialization sequence of the electrum ledger plugin is not correct anymore?

Also see https://github.com/LedgerHQ/app-bitcoin/issues/161

**Comment by smogm** [comment]
I also supplied a fix for this: https://github.com/spesmilo/electrum/pull/6512

**Comment by SomberNight** [comment]
note: more discussion in https://github.com/spesmilo/electrum/pull/6512
