### ISSUE TITLE
Coldcard wallet error

### ISSUE THREAD

**Issue by ChineseGeek** [spesmilo/electrum#6515]
Despite I `python3 -m pip install ckcc-protocol` I still get this error...

![IMG_20200815_080445](https://user-images.githubusercontent.com/488773/90429099-0a8c4280-e093-11ea-935a-2085906c0f50.jpg)

**Comment by AbdussamadA** [comment]
try a user install :

    python3 -m pip install --user ckcc-protocol

**Comment by ChineseGeek** [comment]
> try a user install :
> 
> ```
> python3 -m pip install --user ckcc-protocol
> ```

Nop, that didn't work...

**Comment by lucasmoten** [comment]
Did you also do..
```
sudo apt-get install libusb-1.0-0-dev libudev-dev
```

As well as setup udev rules per
https://raw.githubusercontent.com/Coldcard/ckcc-protocol/master/51-coinkite.rules

**Comment by ChineseGeek** [comment]
Worked after a reboot. Thanks! Closed!
