### ISSUE TITLE
Right click menu filled with "View Invoice"

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#6516]
Version 4.0.2 mac, downloaded from the site. 

<img width="177" alt="Screenshot 2020-08-18 at 08 55 34" src="https://user-images.githubusercontent.com/92292/90480541-ab7d0b00-e130-11ea-943b-d04d630c13b2.png">

Presumably related to receive address being reused.

Wasn't a big deal before but now the top parts of the menu are not reachable, including the "Increase fee" dialog and others.

**Comment by ecdsa** [comment]
indeed, that is because the address has many invoices

**Comment by ziggamon** [comment]
Seems restart helped make the list scrollable again.

**Comment by SomberNight** [comment]
This duplication is also completely useless atm as the same callback is passed to all these context menu items.
https://github.com/spesmilo/electrum/blob/72950bf3794b2a2dce67c152ebc8fadb8d31b8a1/electrum/gui/qt/history_list.py#L702-L705
It should be something like this instead:
```
menu.addAction(_("View invoice"), lambda invoice=invoice: self.parent.show_onchain_invoice(invoice))
```
