### ISSUE TITLE
Sent transaction amount is showing as 'max' instead of actual amount.

### ISSUE THREAD

**Issue by randomlogin** [spesmilo/electrum#6518]
The title says it. It's ok to have a button which makes payment of maximum value. But after this payment is made, there is no way to see the actual amount of btc been sent. Neither in the list of sent txs, nor in the tx details.
Pic. 1
![image](https://user-images.githubusercontent.com/1616179/90526148-b78cbb00-e178-11ea-860e-ae1d6be4dd4a.png)
Pic. 2
![image](https://user-images.githubusercontent.com/1616179/90526534-2e29b880-e179-11ea-946e-e836dc11b853.png)

Version: 4.0.2, OS: ubuntu

**Comment by SomberNight** [comment]
The invoice is for "max". The list of invoices and the invoice details consequently show "max".

However, the transaction, see e.g. the `History` tab, is for a concrete amount.

While it might be a bit weird to have invoices with "max" amounts, it seems more work to fix than it is worth.
