### ISSUE TITLE
Electrum notify keeps sending notifications in daemon mode

### ISSUE THREAD

**Issue by eltNEG** [spesmilo/electrum#6523]
Thanks for this wonderful project

I am running an electrum client (v 4.0.2) in daemon mode and it is using tor proxy. I am using the electrum to watch addresses by subscribing (through RPC calls) using the notify method. Sometimes, Electrum keeps sending notifications to my server for the same transaction. I noticed that this happens when there is an outgoing transaction from one of the addresses being watched.

When I ran the command `lsof -i:$ELECTRUM_PORT`, it returns:

```
electrum 15341  opc   10u  IPv4 18944149      0t0  TCP *:cbt (LISTEN)
electrum 15341  opc   17u  IPv4 19514602      0t0  TCP localhost:cbt->localhost:44488 (ESTABLISHED)
electrum 15341  opc   18u  IPv4 19512777      0t0  TCP localhost:cbt->localhost:43198 (ESTABLISHED)
electrum 15341  opc   19u  IPv4 19512560      0t0  TCP localhost:cbt->localhost:42816 (ESTABLISHED)
electrum 15341  opc   21u  IPv4 19512049      0t0  TCP localhost:cbt->localhost:43100 (ESTABLISHED)
...
```
I noticed that the multiple notifications always happen when there are lots of these "ESTABLISHED" connections. I am not sure if this is the cause of the issue. I will be happy to provide more details in order to debug this.

**Question**: Will I be spamming electrum servers if I call notify on several addresses within a short period of time?

UPDATED:
`lsof -i:$ELECTRUM_PORT` return a closed wait state instead of established

```
electrum 9913  opc   41u  IPv4 24088508      0t0  TCP localhost:7774->localhost:51108 (CLOSE_WAIT)
```

**Comment by SomberNight** [comment]
> watch addresses by subscribing (through RPC calls) using the notify method
> Sometimes, Electrum keeps sending notifications to my server for the same transaction. I noticed that this happens when there is an outgoing transaction from one of the addresses being watched.

When using the `notify` method, the http post notification will be sent to your url every time the [status](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-basics.html#status) of the address changes.
For example, consider a you called `notify` on address A, and a tx T paying to address A was just broadcast.

When tx T is seen by the electrum daemon, when it is unconfirmed, the status of A has changed, so it will send the notification.
Then later, when tx T gets mined, the status of A changes again, so it will send the notification again.
Potentially, while not deeply mined, there could be a chain reorg, that affects tx T in a way that changes the status of A again, which too would result in a new notification being sent.

Hence even for the typical case, there might be multiple notifications for every tx.

> Question: Will I be spamming electrum servers if I call notify on several addresses within a short period of time?

It should put a similar load on servers as having a wallet open with the same addresses imported.

**Comment by eltNEG** [comment]
@SomberNight Thanks for the reply. I will keep a log of all the requests coming in from electrum to verify that electrum only sends notifications when the status of an address changes.

**Comment by eltNEG** [comment]
I found a way around this. I solved it by storing the status hash and checking  if the hash of new notifications already exist
