### ISSUE TITLE
Cannot Transfer BTC due to lost 2FA

### ISSUE THREAD

**Issue by zuhaibfarooqui92** [spesmilo/electrum#6524]
Version: 2.9.2
Wallet - I can see - Passwords, Master Public Keys, Private Keys, Label, Contacts, invoice, history, find, 

Using desktop, mac os

I do have the seed word, just no 2FA

**Comment by zuhaibfarooqui92** [comment]
I upgraded the wallet, follow the steps without 2fa as I do not have that.
The new wallet has been saying "synchronizing 6/30" for 15 minutes now. Any
chance I can get 5 minutes of your time via zoom?

**Comment by zuhaibfarooqui92** [comment]
Sorry for the back to back reply.. Is the idea here to send my BTC to this
new wallet within Electrum? My end goal is to transfer this back to my
exchange.

Really need the money as I am getting married soon!
Thanks for all your help.

Best,

Zuhaib

**Comment by ecdsa** [comment]
if you cannot sync, connect to a different server.

**Comment by zuhaibfarooqui92** [comment]
And is the btc supposed to just show up in the new wallet ?

**Comment by ecdsa** [comment]
if you restore from seed, yes.

**Comment by zuhaibfarooqui92** [comment]
And if I do with 2FA will it let me create a new 2FA? Also what server do i
need to connect to?
Any chance you can hop on a zoom call to help me out? I can pay you to help
if its worth your time.

**Comment by ecdsa** [comment]
sorry, no time for that. just try it out, it should not be complicated.

**Comment by AbdussamadA** [comment]
- when you restore from seed you are recreating the same wallet as before not a new wallet. to create a new wallet you let electrum generate a seed for you and don't enter your existing seed. to create or restore wallets go to file > new/restore. to switch between wallet files go to file > open.

- to change servers go to tools > network, uncheck select server automatically, right click on a server in the list and choose use server. try a few different servers if synchronizing doesn't work.
