### ISSUE TITLE
Question about Electrum release policy

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#6527]
Sorry for asking there as I didn't get an answer on IRC.
What is electrum's release policy regarding changes to public API (command line and RPC commands and their output formats especially)?
Does output format change every major release (4.0, 5.0, etc.), or is subject to change in any release?
Does electrum follow semver?

**Comment by SomberNight** [comment]
(answered on IRC)

> between e.g. 4.0.x and 4.1.x there might be breaking changes.  between patch versions it's unlikely
