### ISSUE TITLE
Calling payto too frequently results in same transactions broadcasted multiple times

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#6529]
When using payto+broadcast command multiple times without delays (sometimes up to 5 seconds), payto command seems to build the same raw transaction.
If rbf is enabled (by default it is), when broadcasting, transaction is replacing previous one. But as it has same settings, same fee calculated, etc., it is rejected. Error "insufficient fee" is returned, which is confusing.
In electrum debug logs it says actual message from bitcoind:
"Transaction not passing network rules. new fee <= old fee"
When rbf is off, usually tx conflict error is returned.
In some cases it is possible that broadcast function can broadcast same transaction multiple times, returning same txid, and then failing.
This error is easy to reproduce, assuming there is a function pay_to:

```
def pay_to(address, amount):
    tx_data = payto(address, amount)
    return broadcast(tx_data)
```

To reproduce, pay_to needs to be called 2 times in a row or a bit more, i.e.:
`pay_to("address", 0.1)
pay_to("address", 0.1)`
I have found this error on regtest initially, but I was able to reproduce it on testnet and mainnet too.
Because of that issue it is hard to use payto/paytomany in concurrent environment (for example, from multiple threads).

**Comment by SomberNight** [comment]
The tx is only added to the wallet history when the wallet learns of it from the server, after it broadcasts the tx.
So there is at the very least a full network round trip's worth of delay.

Workaround:
call `addtransaction` between `payto` and `broadcast`

Though this will clearly NOT provide atomicity, so there could still be a race, but it would be orders of magnitudes less likely.

**Comment by MrNaif2018** [comment]
Thanks, adding addtransaction during broadcast function helped. It failed after 25 txes (too-long-mempool-chain), but it is expected I think.
Should I open a PR to fix broadcast function, or is there a better fix?

**Comment by SomberNight** [comment]
`broadcast` should be independent of any wallet; it should be possible to broadcast any transaction you obtained in any way

perhaps `payto` could take a flag whether to have a side effect on the wallet and add the tx
