### ISSUE TITLE
Electrum no longer signs my multi-sig psbt's - sign button disabled

### ISSUE THREAD

**Issue by Fonta1n3** [spesmilo/electrum#6533]
I had been using a multi-sig wallet with Electrum for quite some time and it was working great in the official beta release for 4.0.2. However now Electrum refuses to sign my multisig psbt's even though it holds the private keys needed which can be exported in Electrum.

To reproduce: 
- create a 2/3 `m/48'/0'/0'/2'` multi-sig wallet
- build Electrum from source (master branch)
- recreate the wallet in Electrum by adding one signer as BIP39 words, then two cosigners as Zpub's
- create psbt with Bitcoin Core (0.20.1)
- sign the psbt with Coldcard
- pass the `part-.psbt` to Electrum 4.0.2 as a `.psbt` file to add the final signature (Electrum shows that the psbt was in fact already signed once)
- In Electrum
 - `tools`
 - `load transaction`
 - `from file`
- Note that the sign button is disabled

I was able to produce this issue on Ubuntu 18.04, on macOS all the buttons were not responsive. It could be a UI issue or perhaps the psbt is still getting rejected internally somewhere due to the Core 0.20.1 change?

**Comment by Fonta1n3** [comment]
nice to see no one gives a shit. Good bye Electrum!

**Comment by lucasmoten** [comment]
Is the coldcard one of the Zpubs?

**Comment by Fonta1n3** [comment]
@lucasmoten thanks for the response :) The Coldcard is one of the Zpubs.

**Comment by SomberNight** [comment]
I have tried to reproduce this now but you will have to hold my hand with Bitcoin Core I am afraid.

> create a 2/3 `m/48'/0'/0'/2'` multi-sig wallet
create psbt with Bitcoin Core (0.20.1)

How?

Here is what I have tried:

```
// create 2of3 wallet in electrum (not shown)

$ ~/wspace/electrum/run_electrum -o --regtest convert_xkey Vpub5n3MbBwqiSaeqw9QrVzaRtRdJ6G9V9T44BoahqKKQVF23FTzY11q7nmbFKkzjkj1c2E7CZMXvncLsU5954SqkbTppiJ3mGRGzQhrHZE4ubZ standard
tpubDFBRbXNvA84hPkZ82k5wDucCFMcS9RFX7mnehuth8dvGGZCFM8omREtmj4oUhdmByjveSW4QVzkzD4B7c5yA62AenXKoDDFVE69gEqh9bo4

// ... convert_xkey 
```
```
$ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest createwallet "ms2of3" true

$ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest getdescriptorinfo "wsh(sortedmulti(2,[b2768d2f/48h/1h/0h/2h]tpubDFBRbXNvA84hPkZ82k5wDucCFMcS9RFX7mnehuth8dvGGZCFM8omREtmj4oUhdmByjveSW4QVzkzD4B7c5yA62AenXKoDDFVE69gEqh9bo4/0/*,[045c5f3c/48h/1h/0h/2h]tpubDE9MoZJU8Rr3woj9jBbuNmuoECyEkhsMXVSeA2vZh9epJfEae4SJjCjqsHM9NDbY29yS3bhchAiJEsSncBLXfnpu7utfbzigkeKW4XYWPyZ/0/*,[0c0c27cb/48h/1h/0h/2h]tpubDFTGo9mYUAbM55vfcU6P6b5ZtALzbhgzBVCeaxzgwAEjFBaZrMFCXgK1jubSrBUXoz7mdd1a7tmbnRtwy4fDV6canBD6gdcRCFeD5gs1kYN/0/*))"
{
  "descriptor": "wsh(sortedmulti(2,[b2768d2f/48'/1'/0'/2']tpubDFBRbXNvA84hPkZ82k5wDucCFMcS9RFX7mnehuth8dvGGZCFM8omREtmj4oUhdmByjveSW4QVzkzD4B7c5yA62AenXKoDDFVE69gEqh9bo4/0/*,[045c5f3c/48'/1'/0'/2']tpubDE9MoZJU8Rr3woj9jBbuNmuoECyEkhsMXVSeA2vZh9epJfEae4SJjCjqsHM9NDbY29yS3bhchAiJEsSncBLXfnpu7utfbzigkeKW4XYWPyZ/0/*,[0c0c27cb/48'/1'/0'/2']tpubDFTGo9mYUAbM55vfcU6P6b5ZtALzbhgzBVCeaxzgwAEjFBaZrMFCXgK1jubSrBUXoz7mdd1a7tmbnRtwy4fDV6canBD6gdcRCFeD5gs1kYN/0/*))#7u7lfe85",
  "checksum": "mfx2yjxw",
  "isrange": true,
  "issolvable": true,
  "hasprivatekeys": false
}

// ... getdescriptorinfo 
```
```
$ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest -rpcwallet=ms2of3 importmulti '[{"desc": "wsh(sortedmulti(2,[b2768d2f/48h/1h/0h/2h]tpubDFBRbXNvA84hPkZ82k5wDucCFMcS9RFX7mnehuth8dvGGZCFM8omREtmj4oUhdmByjveSW4QVzkzD4B7c5yA62AenXKoDDFVE69gEqh9bo4/0/*,[045c5f3c/48h/1h/0h/2h]tpubDE9MoZJU8Rr3woj9jBbuNmuoECyEkhsMXVSeA2vZh9epJfEae4SJjCjqsHM9NDbY29yS3bhchAiJEsSncBLXfnpu7utfbzigkeKW4XYWPyZ/0/*,[0c0c27cb/48h/1h/0h/2h]tpubDFTGo9mYUAbM55vfcU6P6b5ZtALzbhgzBVCeaxzgwAEjFBaZrMFCXgK1jubSrBUXoz7mdd1a7tmbnRtwy4fDV6canBD6gdcRCFeD5gs1kYN/0/*))#mfx2yjxw", "internal": false, "range": [0, 1000], "timestamp": "now", "keypool": true, "watchonly": true}, {"desc": "wsh(sortedmulti(2,[b2768d2f/48h/1h/0h/2h]tpubDFBRbXNvA84hPkZ82k5wDucCFMcS9RFX7mnehuth8dvGGZCFM8omREtmj4oUhdmByjveSW4QVzkzD4B7c5yA62AenXKoDDFVE69gEqh9bo4/1/*,[045c5f3c/48h/1h/0h/2h]tpubDE9MoZJU8Rr3woj9jBbuNmuoECyEkhsMXVSeA2vZh9epJfEae4SJjCjqsHM9NDbY29yS3bhchAiJEsSncBLXfnpu7utfbzigkeKW4XYWPyZ/1/*,[0c0c27cb/48h/1h/0h/2h]tpubDFTGo9mYUAbM55vfcU6P6b5ZtALzbhgzBVCeaxzgwAEjFBaZrMFCXgK1jubSrBUXoz7mdd1a7tmbnRtwy4fDV6canBD6gdcRCFeD5gs1kYN/1/*))#7uds65kx", "internal": true, "range": [0, 1000], "timestamp": "now", "keypool": true, "watchonly": true}]'
[
  {
    "success": true
  },
  {
    "success": true
  }
]

// $ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest -rpcwallet=ms2of3 rescanblockchain 0

// $ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest generatetoaddress 1 $addr
```

```
$ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest -rpcwallet=ms2of3 getnewaddress
error code: -4
error message:
Error: This wallet has no available keys

$ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest -rpcwallet=ms2of3 walletcreatefundedpsbt '[]' '[{"bcrt1qm7ckcjsed98zhvhv3dr56a22w3fehlkxx7vrly":1}]' 0 '{"includeWatching":true}' true
error code: -4
error message:
Can't generate a change-address key. No keys in the internal keypool and can't generate any keys.
```

What am I doing wrong?

-----

> pass the part-.psbt to Electrum 4.0.2 as a .psbt file to add the final signature (Electrum shows that the psbt was in fact already signed once)

Alternatively, you could give me a testnet Electrum wallet file and a psbt that triggers the issue. The wallet does not even need to have testnet coins, as in, you could set up the reproduction prequisites and spend the coins after, as I can just test it offline without history.

**Comment by Fonta1n3** [comment]
First off thank you for taking the time to try and replicate, it is appreciated.

You have done the hard part! The issue is core does not allow you to add multisig keys to the keypool, so you need to generate them with `bitcoin-cli deriveaddresses` you can pass the descriptor and index as params. With `walletcreatefundedpsbt` you have to specify a change address as a param that you would generate with `deriveaddresses`.

I had been doing this on mainnet so do not have a testnet wallet handy to pass you, you should be able to complete the process quite easily from where you left off but if not I can get you a testnet wallet.

**Comment by SomberNight** [comment]
Thanks for the pointers. I think I've followed your instructions but I could not reproduce the issue.

For posterity, some more commands:
```
$ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest -rpcwallet=ms2of3 deriveaddresses "wsh(sortedmulti(2,[b2768d2f/48h/1h/0h/2h]tpubDFBRbXNvA84hPkZ82k5wDucCFMcS9RFX7mnehuth8dvGGZCFM8omREtmj4oUhdmByjveSW4QVzkzD4B7c5yA62AenXKoDDFVE69gEqh9bo4/0/*,[045c5f3c/48h/1h/0h/2h]tpubDE9MoZJU8Rr3woj9jBbuNmuoECyEkhsMXVSeA2vZh9epJfEae4SJjCjqsHM9NDbY29yS3bhchAiJEsSncBLXfnpu7utfbzigkeKW4XYWPyZ/0/*,[0c0c27cb/48h/1h/0h/2h]tpubDFTGo9mYUAbM55vfcU6P6b5ZtALzbhgzBVCeaxzgwAEjFBaZrMFCXgK1jubSrBUXoz7mdd1a7tmbnRtwy4fDV6canBD6gdcRCFeD5gs1kYN/0/*))#mfx2yjxw" "[0,2]"
[
  "bcrt1q9zxj5g5jh9w3ypy53hrhykw9f28lmsvkhj2czh6gmmryuthgekuslwce4d",
  "bcrt1qyqd4u56c0yjakz7qzw35h25ht9jjymgdsv76lnnqjmcj0psv656q065hre",
  "bcrt1qtr3mzcvv276mcczf8m8qx8xll640du9n7fd9e6dkchkfqcjfdd9q3nekk7"
]

$ bitcoin-cli -rpcuser=doggman -rpcpassword=donkey -rpcport=18554 -regtest -rpcwallet=ms2of3 walletcreatefundedpsbt '[]' '[{"bcrt1qm7ckcjsed98zhvhv3dr56a22w3fehlkxx7vrly":1}]' 0 '{"includeWatching":true, "changeAddress":"bcrt1qhe9a9cl063vhx3ut8x7a80u24t53qqncujj70ayru44zdx2ue80qwx8lay","feeRate":0.00001}' true
{
  "psbt": "cHNidP8BAH0CAAAAAdjLhzq5D9YXrUgLN9sCjUfde0wgpSCBZoiomCWWgGWHAQAAAAD+////AgDh9QUAAAAAFgAU37FsShlpTiuy7ItHTXVKdFOb/sZD4PUFAAAAACIAIL5L0uPv1FlzR4s5vdO/iqrpEAJ45KXn9IPlaiaZXMneAAAAAAABAH0CAAAAAR8HAbCbjHx0Hhq/nXOkk6igkeRPSWzcIi0OgoNNaEqKAAAAAAD9////AoRStAYAAAAAFgAUf7nxmzzlacBmb8fBk9GUzPQ0+9gAwusLAAAAACIAICiNKiKSuV0SBJSNx3JZxUqP/cGWvJWBX0jexk4u6M252AIAAAEBKwDC6wsAAAAAIgAgKI0qIpK5XRIElI3HclnFSo/9wZa8lYFfSN7GTi7ozbkBBWlSIQNSOEY68semDQJvEXSKCjpBTzoK2uNKkEXdYiyL1CyUbCEDkvwFMIGVE8Rqmi/lwJI78v9pQsxzB+zJO4m7GTYhxgshA7Q+QYeq01L3vXrexAh9pPuFZoXFEz9Kbuqfmfk4Y9pjU64iBgNSOEY68semDQJvEXSKCjpBTzoK2uNKkEXdYiyL1CyUbBwEXF88MAAAgAEAAIAAAACAAgAAgAAAAAAAAAAAIgYDkvwFMIGVE8Rqmi/lwJI78v9pQsxzB+zJO4m7GTYhxgscDAwnyzAAAIABAACAAAAAgAIAAIAAAAAAAAAAACIGA7Q+QYeq01L3vXrexAh9pPuFZoXFEz9Kbuqfmfk4Y9pjHLJ2jS8wAACAAQAAgAAAAIACAACAAAAAAAAAAAAAAAEBaVIhAoVrOTzJiko9RC0N03J7Ti3RTnZnKNyJQFEdu0xAjjDGIQK9FN7mvGaGmb1TgcIBHzQ2jHaZ1Q9z8CgyxS7xFUUnhCED+WRSa/BwzMOSt6avYunSaA3ooD+XH9+zMKWqGq/9MdJTriICAoVrOTzJiko9RC0N03J7Ti3RTnZnKNyJQFEdu0xAjjDGHLJ2jS8wAACAAQAAgAAAAIACAACAAQAAAAAAAAAiAgK9FN7mvGaGmb1TgcIBHzQ2jHaZ1Q9z8CgyxS7xFUUnhBwMDCfLMAAAgAEAAIAAAACAAgAAgAEAAAAAAAAAIgID+WRSa/BwzMOSt6avYunSaA3ooD+XH9+zMKWqGq/9MdIcBFxfPDAAAIABAACAAAAAgAIAAIABAAAAAAAAAAA=",
  "fee": 0.00000189,
  "changepos": 1
}
```

-----

Overall I have done the following, on local regtest:
- create wallet `test_ms_p2wsh_2of3_cc_t1_ledger` in Electrum; a 2of3 p2wsh multisig between 3 hw devices, all connected via usb.
- funded wallet `test_ms_p2wsh_2of3_cc_t1_ledger`
- went into Qt GUI `Wallet`>`Information` dialog, and in combination with `electrum convert_xkey` cmd manually constructed two output script descriptors for wallet
- also exported multisig wallet descriptions file for coldcard in same menu; moved file via sdcard to coldcard; imported multisig wallet onto coldcard
- used `bitcoin-cli getdescriptorinfo` to get checksum for descriptors
- created wallet `ms2of3` using bitcoin-cli
- with bitcoin-cli, used `importmulti`, `rescanblockchain`, and `walletcreatefundedpsbt` to create a tx spending from wallet
- copy-pasted base64 psbt into a file `from_core.psbt`. (so glad that coldcard can read this... it's against overly-strict bip174 spec, which would enforce a binary file)
- transported `from_core.psbt` to coldcard via sdcard; and signed it
- created a new Electrum wallet `issue_6533`. 2of3 p2wsh with bip39 seed (of Trezor) + Zpub + Zpub
- with sdcard back in PC, loaded `from_core-part.psbt` into Electrum wallet `issue_6533`
- Electrum wallet `issue_6533` could sign `from_core-part.psbt`
- used `bitcoin-cli testmempoolaccept` to validate the signed tx

-----

<details>
 <summary>Electrum wallet file `test_ms_p2wsh_2of3_cc_t1_ledger` excerpt (keystores in particular)</summary>

```
"x1/": {
        "ckcc_xpub": "tpubD6NzVbkrYhZ4WNChMzP6Has7XTPzx3TCSfSPrv6tgfUW2PRs4kVkT2q631Pt8zfQ3J8QE18BtGpD5FneE38x7ybJdWHmSXmURFxKFEqhpjJ",
        "derivation": "m/48'/1'/0'/2'",
        "hw_type": "coldcard",
        "label": "Coldcard b2768d2f",
        "root_fingerprint": "b2768d2f",
        "soft_device_id": null,
        "type": "hardware",
        "xpub": "Vpub5n3MbBwqiSaeqw9QrVzaRtRdJ6G9V9T44BoahqKKQVF23FTzY11q7nmbFKkzjkj1c2E7CZMXvncLsU5954SqkbTppiJ3mGRGzQhrHZE4ubZ"
    },
    "x2/": {
        "derivation": "m/48'/1'/0'/2'",
        "hw_type": "trezor",
        "label": "testing2",
        "root_fingerprint": "045c5f3c",
        "soft_device_id": "D5F391909FB8EE64712FBC8F",
        "type": "hardware",
        "xpub": "Vpub5m1HoDsPgkN1PzKSYwWYakjEGwcx6S4tTuTa9xMBxzya5MWKpveNRkcfPYJfQLZMeSGtoezk7xZeuHLp59pDLN85A6rvA3tUWxsg7LweWYr"
    },
    "x3/": {
        "cfg": {
            "mode": 0
        },
        "derivation": "m/48'/1'/0'/2'",
        "hw_type": "ledger",
        "label": " ",
        "root_fingerprint": "0c0c27cb",
        "soft_device_id": "0c0c27cb",
        "type": "hardware",
        "xpub": "Vpub5nKCnpLU2V7JXGWxSE12JZtzvtzhwRtX7uDaatRKD1ZV1srK3DTGEEBqGAYxtJSMSGREPgJhYgcxSqnyS38u9fukpNBMEgnCxaCP8QkZqGL"
    }
```
</details>

<details>
 <summary>Electrum wallet file `issue_6533` excerpt (keystores in particular)</summary>

```
"x1/": {
        "derivation": "m/48'/1'/0'/2'",
        "pw_hash_version": 1,
        "root_fingerprint": "045c5f3c",
        "type": "bip32",
        "xprv": "l9HTysjiaqrlLeUB751qVrukDARyUF6EJLTnuZukRldRAmopPkwSUVvO+0V66UKpUEiXFSYFIHztkIe5ve/E/iDyGnTPHjtl7NlQ4+u9vrtZuRlmTD5sr6iWqr52/d4vZ0mMPiuDAd5WiPG59epfG7NayuLmONI5eDADRLh6Zmk=",
        "xpub": "Vpub5m1HoDsPgkN1PzKSYwWYakjEGwcx6S4tTuTa9xMBxzya5MWKpveNRkcfPYJfQLZMeSGtoezk7xZeuHLp59pDLN85A6rvA3tUWxsg7LweWYr"
    },
    "x2/": {
        "derivation": null,
        "pw_hash_version": 1,
        "root_fingerprint": null,
        "type": "bip32",
        "xprv": null,
        "xpub": "Vpub5n3MbBwqiSaeqw9QrVzaRtRdJ6G9V9T44BoahqKKQVF23FTzY11q7nmbFKkzjkj1c2E7CZMXvncLsU5954SqkbTppiJ3mGRGzQhrHZE4ubZ"
    },
    "x3/": {
        "derivation": null,
        "pw_hash_version": 1,
        "root_fingerprint": null,
        "type": "bip32",
        "xprv": null,
        "xpub": "Vpub5nKCnpLU2V7JXGWxSE12JZtzvtzhwRtX7uDaatRKD1ZV1srK3DTGEEBqGAYxtJSMSGREPgJhYgcxSqnyS38u9fukpNBMEgnCxaCP8QkZqGL"
    }
```
</details>

**Comment by Fonta1n3** [comment]
Ok, perhaps one of my inputs was beyond the gap limit? I will do more testing on my end. Thank you.

**Comment by SomberNight** [comment]
> perhaps one of my inputs was beyond the gap limit? 

I think that would only matter if the signing keystore in `issue_6533` was created from a Zprv instead of bip39 mnemonic.
With a Zprv, the keystore will not recognise pubkeys beyond the gap limit as its own, as the keystore is missing its root fingerprint and hence cannot match based on that (against the root fingerprints in the psbt).

If you create the keystore from bip39 words, the keystore will have its root fingerprint, and the gap limit should matter in this respect.

**Comment by Fonta1n3** [comment]
Ok, I will try again on testnet and make sure I can’t replicate and get back to you. Thanks again.

**Comment by Fonta1n3** [comment]
Can confirm this works using the latest beta release, it was probably most likely some UI issue where building from source went wrong...
