### ISSUE TITLE
[Feature Request] Clear "Recently open" wallets

### ISSUE THREAD

**Issue by jrmsayag** [spesmilo/electrum#6536]
As suggested [here](https://bitcointalk.org/index.php?topic=2880900.msg29606016#msg29606016), it would be great to have an option to clear the history of recently open wallets (or maybe to be able to just deactivate the history completely).

I'm not sure it's the right place for a feature request, so feel free to close if that's not the case.

Cheers!

**Comment by SomberNight** [comment]
Why? What is the use case?
I assume you are concerned that it leaks the names of wallets you have recently opened, however your list of wallets can typically be seen in the data directory (e.g. `~/.electrum/wallets`) either way.

Please explain why this feature leaks privacy and against what kind of attacker.

**Comment by ecdsa** [comment]
I guess the wallet may be in another directory, eg USB drive

**Comment by SomberNight** [comment]
Note that every time you load a wallet, the list is updated to remove all paths that are no longer available. (so e.g. unplugged USB)

https://github.com/spesmilo/electrum/blob/fdaf6e775cdbe461a8466d1d7e46360c8a90e4d7/electrum/gui/qt/main_window.py#L637

**Comment by ecdsa** [comment]
right. well, I guess that's not really useful then. 
closing this. it would still be nice to hear back from the OP
