### ISSUE TITLE
new address stole BTC !!!

### ISSUE THREAD

**Issue by Khashiu** [spesmilo/electrum#6540]
i made new address and got new transaction
but BTC gone to another address how its possible ? 
when i got 1 confirmation (when i recive btc)  i see 2 notification about recive but one of them actually is send ... i dont know what happened 

![3](https://user-images.githubusercontent.com/33989078/91519286-682c5480-e907-11ea-9eea-99ce41ea1e48.png)
![4](https://user-images.githubusercontent.com/33989078/91519295-6bbfdb80-e907-11ea-975f-75e586b6ab96.png)
![1](https://user-images.githubusercontent.com/33989078/91519276-6367a080-e907-11ea-87dc-a61da28e091f.png)
![2](https://user-images.githubusercontent.com/33989078/91519282-65c9fa80-e907-11ea-8b40-0e9f9752f5ba.png)

**Comment by ecdsa** [comment]
it probably means that you are not the only person in control of the private key you imported in Electrum

**Comment by Khashiu** [comment]
> it probably means that you are not the only person in control of the private key you imported in Electrum

i made address with this 10 min before i send BTC to it 
the reciver balance not changed
https://blockchair.com/bitcoin/address/3EcP8yPEieGiY1GpTBpPJWqsPdwUL5tnP4
i want know how its possible i see 2 transaction progress in 1 sec ???
its not coming to my wallet . its like directlly go to other wallet . my wallet open but after 3 confirmation nothing in my wallet 
![6](https://user-images.githubusercontent.com/33989078/91598562-a6169080-e97a-11ea-9384-0b399c86d4fd.png)

**Comment by Khashiu** [comment]
check transaction , look at time .... its like my DIVERT in phone ... my address diverted to other address 
my wallet : https://blockchair.com/bitcoin/address/1HFeyEToLb4ZojL8wrJASGb1g1XTjC2LJL
that wallet : https://blockchair.com/bitcoin/address/3EcP8yPEieGiY1GpTBpPJWqsPdwUL5tnP4

**Comment by SomberNight** [comment]
Well maybe that "Bitcoin Address Utility by Casascius" is the culprit. It clearly has access to your keys.
Where did you download that from?

**Comment by Khashiu** [comment]
> Well maybe that "Bitcoin Address Utility by Casascius" is the culprit. It clearly has access to your keys.
> Where did you download that from?

i dont remember but download about days ago ... look like writen by Visual basic . But how fast they can access my pk 😪 its not coming to my wallet . Directly go for there

**Comment by ecdsa** [comment]
closing, it seems pretty clear how the coins were stolen. don't download malware.
