### ISSUE TITLE
Lightning channels was closed, probably by electrum client.

### ISSUE THREAD

**Issue by bandafix** [spesmilo/electrum#6543]
Lightning channels were closed, probably by electrum client. After connecting to lightning channels from two electrum clients simultaneously.

Scenario:

1.
Environment: VM with Linux Mint 19.3 Mate X64 installed on it.

2.
electrum 4.0.1 was downloaded from python source.

3.
After installing all the necessary dependencies, electrum 4.0.1 was turned on and run without installation by double click on “run_electrum” file. With the setting: "run a local watchtower" and "presist after all windows are closed"

4.
Six lightning channels was opened by me with main lightning nodes (bitstamp, bitrefill, etc..) No transaction was ever made in any of those channels.

5.
The VM was shut down and afterward full cloned. (as a backup method)

6.
The both VMs was turned on and electrum clients was turned on in both of them.

7.
When the second client was turned on and started to run, all the payment channels was closed, probably by my electrum client. 

8.
The payment channel closure transactions was made with relatively high fee (144 sat/byte) Total cost of fees for six channels closure: almost 120,000 satoshis.

9.
When I right click → view transaction on any of the channel closure transaction, the electrum wallet indicate next LockTime format: 

LockTime: 5******** (1987-**-** **:**:**)

(all the channel closure transactions appears with 9 digits block height. and indicating lock time as March, April or May 1987)

10.
I believe it is a problem that should be fixed. Beside the use case of opening two lightning wallets by two desktop or two VMs, as I described, I was also planned to use the same electrum addresses and the same lightning channels in desktop and android smartphone in the future, to be able to make payments by lightning wallet outdoor in physical stores, and also online from my PC.

11.
I opened the lightning payment channels to save in fees and to use them forever. But due to the incident indicated above, 0 lightning transactions were cost me as 120 on-chain transactions (based on the actual average on-chain transaction cost today) so it can be seen as a frustrating experience. 

12.
Do I need to change something in the electrum wallet setting in order to avoid similar incident in the future? Is it a bug that should be fixed? Is there any other thing I can do to avoid similar incident in the future?

**Comment by ecdsa** [comment]
that is expected.
you cannot run the same channels in two separate instances.
see the release notes:

>     - Lightning-enabled wallet files must not be copied

**Comment by ecdsa** [comment]
Also, note that your channels were not closed by the Electrum client, but by the remote nodes, because you tried to reestablish them with an old state.
