### ISSUE TITLE
transaction labels frequently get overwritten by invoice descriptions, even after changing label manually

### ISSUE THREAD

**Issue by aantonop** [spesmilo/electrum#6545]
When I make a pay-to-many transaction, the description label I write out gets concatenated onto an older transaction description label after a semicolon.

For example:

I make a new pay-to-many transaction (TxA) and write description "$3 to Alice and $5 to Bob". 

There's an older pay-to-many transaction  (TxB) from a month ago that is labeled "$7 to Charlie and $8 to David". 

Once I sign and broadcast the TxA, its description label changes to "$7 to Charlie and $8 to David; $3 to Alice and $5 to Bob" even though it is not in any obvious way related to the previous pay-to-many transaction. 

The description has an added semicolon and concatenates the new description on the end of the description from the older transaction. 

After several months of this bug, I have transaction descriptions with 4-5 labels concatenated with semicolons. If I try to edit the label, I can't. As soon as I finish editing (by removing the older description), it reverts back and concatenates whatever I submitted to the older labels with a semicolon.

Current Electrum version 4.0.2, but this happened on other v4 betas at least. Possibly on earlier v3 versions, but not sure of that

**Comment by SomberNight** [comment]
If you right-click the tx in the history tab, how many "View Invoice" options are there in the context menu?

**Comment by aantonop** [comment]
Context menu shows:

- T0 (most recent) Tx, has 3 payees, shows 6 x View Invoice in context menu
- T-1 (prev) Tx had 3 payees, showed 6 x View Invoice in context menu
- T-2 had 3 payees, 8 View Invoice in context
- T-3 had 3 payees, 6 View Invoice
- T-4 had 1 payee, 3 View Invoice

**Comment by SomberNight** [comment]
Related: https://github.com/spesmilo/electrum/issues/6516
In Electrum 4.0.2, as in linked issue, in the context menu for a tx there is a "View invoice" option for every relevant invoice. It is also bugged unfortunately: all these "View invoice" options have the same callback and will show you the same invoice. -- but that's just now fixed on master

-----

When a tx is added to the history, its label will get set to the concatenated description of relevant invoices.
This happens every time when `wallet.add_transaction(tx)` is called; which I think is whenever the history of any ismine address the tx touches changes.
If you reuse addresses, it might get called many times, overwriting your custom label.
(this overwriting is not intended, I had not realised the full extent of it before)

Note: an invoice is "relevant" to a tx if the tx pays any amount to any address listed in the invoice. (this allows settling an invoice using multiple transactions; or settling multiple invoices in a single transaction)

> If I try to edit the label, I can't. As soon as I finish editing (by removing the older description), it reverts back and concatenates whatever I submitted to the older labels with a semicolon.

Still, this seems even more extreme than what I just described. Are you sure it reverts back instantly?

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/commit/6d86f4dc18faaafd9f184c97c3433ec3313c7d69 might mitigate the issue somewhat.

I am still interested if there is a discernible pattern to when the labels get overwritten for you -- or if it's really instant.

Also, why do you have that many relevant invoices for these txs? :)

**Comment by aantonop** [comment]
Ok, I see the problem now: One of my "recipients" is using Coinbase
Commerce, which uses the same address for a recurring invoice. Each
transaction that uses that same address for that one recipient is suffering
from this bug. I'm not re-using addresses, but one of my payees is re-using
addresses and I hadn't noticed they are. Because of that, Electrum is
merging the descriptions (creating a *mess*).

The only redeeming irony? The payee whose address is getting reused is my
accountant who also has to deal with the label mess at the end of the year.

**Comment by aantonop** [comment]
As I'm editing, the field will lose focus, it's not actually overwriting it after I edit it. It's just very difficult to edit a long description because the edit field loses focus every 5 seconds. I have to be quick!

**Comment by SomberNight** [comment]
> As I'm editing, the field will lose focus, it's not actually overwriting it after I edit it.

Ah right ok. That explains it.

> It's just very difficult to edit a long description because the edit field loses focus every 5 seconds.

Yes, every time the list is refreshed the pending edit - if any - is lost. This is a separate issue.

> uses the same address for a recurring invoice. Each
transaction that uses that same address for that one recipient is suffering
from this bug.

All right, that explains that then.

-----

Ok, in that case I think https://github.com/spesmilo/electrum/commit/6d86f4dc18faaafd9f184c97c3433ec3313c7d69 is sufficient for now.

With that, the tx label will only be set once, when first added, to the concat of invoice descriptions.
After that, the user is free to change the tx label.
One minor quirk is that if the user clears the tx label, it might get re-set to the concat of invoice descriptions but this will unfortunately not happen reliably (only if `wallet.add_transaction` happens to get called again due to history change). This logic should ideally move into `wallet.get_default_label` but it would need further testing whether it is sufficiently performant to be put there. If there, we would always show the concat if the user clears the label, but this would require deserializing all wallet transactions on wallet-open, which might be too slow for large wallets.

**Comment by SomberNight** [comment]
> As I'm editing, the field will lose focus, it's not actually overwriting it after I edit it. It's just very difficult to edit a long description because the edit field loses focus every 5 seconds. I have to be quick!

Should be fixed in https://github.com/spesmilo/electrum/commit/1ea4e42a96f1dfc8aeb89dc8079cafcf7837e008

**Comment by aantonop** [comment]
Nice, I will be testing this soon
