### ISSUE TITLE
Sign a transaction and also get the signature

### ISSUE THREAD

**Issue by prayank23** [spesmilo/electrum#6549]
I have mentioned the details here: https://bitcoin.stackexchange.com/questions/98613/how-to-sign-a-transaction-and-also-get-the-signature-part-from-it-using-electrum

Basically trying to use [caravan](https://unchained-capital.github.io/caravan) with Electrum and used the public keys of 3 addresses from an Electrum wallet to create 2 of 3 multisig. To create the spending transaction using script explorer option in caravan you need to provide signatures. How do I get those signatures from Electrum console?

**Comment by SomberNight** [comment]
The `signtransaction` command is broken in 4.0.2 (https://github.com/spesmilo/electrum/issues/6502). Try on master.

**Comment by prayank23** [comment]
> The `signtransaction` command is broken in 4.0.2 (#6502). Try on master.

So tried the below steps and still getting some error:

`sudo apt-get install libsecp256k1-0`
`sudo apt-get install python3-pyqt5`
`sudo apt-get install python3-cryptography`
`git clone git://github.com/spesmilo/electrum.git`
`cd electrum`
`git submodule update --init`
`python3 -m pip install --user -e .`

`./run_electrum --testnet`


Create a 2 of 3 multisig address and redeem script in caravan using 3 public keys from top 3 addresses in electrum wallet:

<pre><code>Address: 2MxToWNgdez8mLXKBrggAFLDAKJ7NjHUE7H

Type: P2SH

Network: testnet

Quorum: 2-of-3

BIP32 Paths:
  * Public Key 1: Unknown (make sure you have written this down previously!): 02f2fd40d4a545e8ce9166fde3ed876714c192a9a81b5051cd6d76b89b512fb390
  * Public Key 2: Unknown (make sure you have written this down previously!): 033b1f7fb8ea20a35548a8e1ef1a55199199884af9f9ddd1d1e07bb5e634ea9c27
  * Public Key 3: Unknown (make sure you have written this down previously!): 03a68ae382e5dc9743517cdf96babc243f139fb393af7b409d00ac40eca88ed59d

Redeem Script: 522102f2fd40d4a545e8ce9166fde3ed876714c192a9a81b5051cd6d76b89b512fb39021033b1f7fb8ea20a35548a8e1ef1a55199199884af9f9ddd1d1e07bb5e634ea9c272103a68ae382e5dc9743517cdf96babc243f139fb393af7b409d00ac40eca88ed59d53ae
</pre></code>

Send 0.02 tBTC to 2MxToWNgdez8mLXKBrggAFLDAKJ7NjHUE7H

Get unsigned tx from [caravan script explorer](https://unchained-capital.github.io/caravan/#/script): `0100000001147b2ff23adcadf3dfa171b2561406db2fe261febdf0c22bca09cafde956563f0100000000ffffffff013dc81d0000000000160014950078b310fb72b96ac3bb1f243b264a54c968c900000000`

![image](https://user-images.githubusercontent.com/13405205/92207633-2a9b6e80-eea7-11ea-9bdc-82e394817646.png)

**Comment by prayank23** [comment]
And this is the result I get in the older version: 

![image](https://user-images.githubusercontent.com/13405205/92209577-dd210080-eeaa-11ea-8fbc-622fc10c1cba.png)

**Comment by SomberNight** [comment]
`signtransaction` needs a PSBT as an input. Your "unsigned tx" is not a PSBT.

**Comment by prayank23** [comment]
@SomberNight Does that mean caravan is not following BIP 174 to create the unsigned transaction which I am using in this case?

**Comment by SomberNight** [comment]
> Get unsigned tx from caravan script explorer: 0100000001147b2ff23adcadf3dfa171b2561406db2fe261febdf0c22bca09cafde956563f0100000000ffffffff013dc81d0000000000160014950078b310fb72b96ac3bb1f243b264a54c968c900000000

^ This is not a PSBT. It does not claim to be one either. It is an unsigned transaction in network serialization.
This is usually one field inside a PSBT (the field called "PSBT_GLOBAL_UNSIGNED_TX"). A PSBT has lots of other fields. For example, the redeem script you also specified separately above would be in another field of the PSBT (it's not part of the unsigned tx).

The `signtransaction` command expects a PSBT as an input, which would include more data than just the unsigned tx.
(Even a PSBT that *only* contained the unsigned tx would be formatted differently; what you have is not a PSBT but just one part of it.)
