### ISSUE TITLE
Wallet file selector (Windows)

### ISSUE THREAD

**Issue by strarsis** [spesmilo/electrum#6553]
When recovering a wallet file, first the wallet file has to be selected.
When the native file selector under windows is used, a new wallet can't be created.
Only by manually entering the file path into the text input a non-existing file can be specified (for creation).

Related: https://github.com/spesmilo/electrum/issues/3561

**Comment by SomberNight** [comment]
How is this not a duplicate of the linked issue (https://github.com/spesmilo/electrum/issues/3561)?

Also, what do you suggest to do?

**Comment by strarsis** [comment]
@SomberNight: Yes, the issue is so much related that it is a duplicate. 😸
