### ISSUE TITLE
bc1qcygs9dl4pqw6atc4yqudrzd76p3r9cp6xp2kny is the receivers address.

### ISSUE THREAD

**Issue by hosein1986** [spesmilo/electrum#6560]
bc1qcygs9dl4pqw6atc4yqudrzd76p3r9cp6xp2kny is the receivers address.

_Originally posted by @1400BitcoinStolen in https://github.com/spesmilo/electrum/issues/5072#issuecomment-683356120_

hello 
I know who hacked you

**Comment by 1400BitcoinStolen** [comment]
I am not interested in dealing with anyone that wants anything up front.

I have implemented security on my network to avoid hacking and I will not download any files you send.
