### ISSUE TITLE
trouble verifying gpg signature of release

### ISSUE THREAD

**Issue by nicolasssmaia** [spesmilo/electrum#6568]
I'm a new Linux user, and i'm trying to get Electrum in my new device, but when download it and try to verify, the message BAD SIGNATURE appears. And looking for the developers signature on github, i see it don't means with the signtaure on site electrum.org

Am I doing anything wrong?

**Comment by verretor** [comment]
Don't use it if it says bad signature.

**Comment by SomberNight** [comment]
see https://electrum.readthedocs.io/en/latest/gpg-check.html

check if you are using the correct syntax
