### ISSUE TITLE
implement LN multi part payments (basic MPP)

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6586]
We should implement the [`basic_mpp` feature](https://github.com/lightningnetwork/lightning-rfc/blob/master/09-features.md) for lightning. (https://github.com/lightningnetwork/lightning-rfc/pull/643)
Receive support is easier so probably that first, but then sending as well.

(also called `base AMP`)

**Comment by ecdsa** [comment]
note: receive support is required for trampoline.
see https://github.com/spesmilo/electrum/commits/basic_mpp

**Comment by ecdsa** [comment]
mpp receive is already implemented, and @bitromortac is currently working on mpp send.

**Comment by ecdsa** [comment]
merged.
