### ISSUE TITLE
suma nevalidata

### ISSUE THREAD

**Issue by IdioTrix** [spesmilo/electrum#6591]
When I tried today to send satoshi from my electrum wallet, I received the error "unvalidated amount". What is the reason? Have I been scammed?
![eroare](https://user-images.githubusercontent.com/71265440/93083170-e2e0c800-f69a-11ea-8a28-21588ab88d38.jpg)

**Comment by SomberNight** [comment]
In your image, you did not specify an amount. You typed the amount into the description field; it should go just below that.

**Comment by IdioTrix** [comment]
Sorry, you are write. I think I am confused from work.. or just became an idiot and did not check correctly the fields. Solved now, sorry again for being stupid..
