### ISSUE TITLE
Witness Utxo is missing on electurm 4.0.3 psbt qr code

### ISSUE THREAD

**Issue by aaronisme** [spesmilo/electrum#6600]
When using the Electrum 4.0.3, the bip 32 derivation path of the input is missing on psbt data when using the code, this function worked on 4.0.2. 

when using the file to export psbt, this issue does not exist. added the screenshot of qr code here.
![274091600235350_ pic](https://user-images.githubusercontent.com/7855886/93427989-4f550480-f8f1-11ea-94a2-c6c8630eee1c.jpg)

**Comment by SomberNight** [comment]
Indeed your QR code does not contain derivation path info, however when I try to create a QR code myself it does.
Could you detail how to reproduce?

**Comment by aaronisme** [comment]
@SomberNight 
Hi Here are the steps to reproduce:
1. create the wallet on electrum using the master public key
2. create a transaction on electrum
3. select Export -> For hardware devices; include xpubs -> Show as QR Code to present the QR Code of Unsigned PSBT.
here is the screenshot:
![WechatIMG27510](https://user-images.githubusercontent.com/7855886/93551578-d1503680-f9a0-11ea-8b0c-02f8505a1392.jpeg)

**Comment by aaronisme** [comment]
I can provide the master pub key if it can help to investigate and reproduce the issue @SomberNight Do you need it ?

**Comment by SomberNight** [comment]
Maybe I am misunderstanding the issue... but the second QR code you provided does have paths in the inputs (and outputs):

```
>>> import pprint
>>> from electrum.transaction import tx_from_any
>>>
>>>
>>> qr1 = "553+311+.ZPPB3GVFDL/QLO46ECZKDNH769PW3/-*M:.A/UY71GP:0O15OH5*97:GO9./XB-J4TBTNKOULBLHNR87ZWH*GS$+WMMB95C86P9I7SQJKGB/G9V6JF0Z6UPQX0HV913S/MLGA5IRSN75UN$:QKRK0IUEC2F-5:VJVM*9EB+0AU7KX0+*S*I784UG+KO1X$-MC174V4TODF6V.++XY875A8QYY.K-YX31/SWHU6RYKMBP812IU$$X8I.+1B+K.WOS$7F+T$NKYV29Q0FHJIT/DUQ+NPVJ.AG8++0KD5MB7I46-$LQ6EI1T5OYDDB50D8DQZ7USD4T-Q-W-/O5QHL4+O.0S*RQ$/.900YNDI3BF:W6CPXEP*Z+GLD9P.IWGHU16GJ.QE1ZHJPULVXU$4+GF:*DZA++C"
>>> qr2 = ".MJFXL+TF981VNACTQ0XU7UM:A$VBXNK*EJ*N--SIRXIV/K$L$AY0E4:9M+W:A504U2/IWKI932R0B9O/SSMJYFK1SK2WMW6WGFQA*F04.I8M9J846GRQ9VFHC*Y009S14$GK43R.9SF*APECKWHU*B:0Y$BJB$TCB-$EIPW0.K07HT+L0RJ+2Q$CKCV6A9TBKLA0LWWHS.D//LVVSV0O9TFEY*COBDSPI*HVUCF6R+:W*QO:K$9D$XYYW0TFTS3L+SXOI2*NZ-J$2*K*/1+V5Z8+8S+EXXTRRV..9DXI8+R3L4R-G2PA:9MOVA3NIWB0+WF9SF:K6V*VJ+6OFQSQ:9$SMTMPIPD9S*S-PO2BTTKF2Q9.54MD6QVSLG2ODD-X+CNRZLMN4W$/-D+VEK$W8P2DZ50YAKOC/2M3B*Q59DOTP:Q*SYM3Y.8+O87IXGJ-YTF30H52VDD--*EDLHILP+FZQ*XGHHQV642:DYM2MLD0F-NN2X86J951-:VRXW6R$Z1G188MBDT67TP1E+DO2WJSTJUSFD+DK5KPOCRTDYI4JYQ/*+/0C9$W3PY$FIM3FJJZKP./DM.MS38R3XW06DIENI4H-941PKC78WMU94LOE035/*U-+M:+ZQ435$J.OIQU/-TM*$-$J.C*03I$C1L/9/61LF$ECYL5D$/O$5:4PEI9MGGAWZRDF3CD9GE22+18.9E/UIW8ERUJA9EH3*5CNIJX9EWB4TKJZJBXT.MZBFZFS+9*-GYRZ1/+3AR9B5AFQ9:V$/3D3Z3XZZMFYK*JA4.IO:E6YKLKF5Z.IZ+S5B*S3MOHC+H-FQHLKMQMQ.3Z+LS5D0CTXPWP"
>>>
>>> t1 = tx_from_any(qr1)
>>> t2 = tx_from_any(qr2)
>>>
>>> pprint.pprint(t1.to_json())
{'inputs': [{'address': None,
             'bip32_paths': {},
             'coinbase': False,
             'height': None,
             'nsequence': 4294967293,
             'part_sigs': {},
             'prevout_hash': '111ac54b4bca521012620dec5e5478d2db8ae19eded0e049efa44ca843d5fd15',
             'prevout_n': 2,
             'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
             'sighash': None,
             'unknown_psbt_fields': {},
             'utxo': None,
             'value_sats': None,
             'witness_script': None,
             'witness_utxo': None},
            {'address': None,
             'bip32_paths': {},
             'coinbase': False,
             'height': None,
             'nsequence': 4294967293,
             'part_sigs': {},
             'prevout_hash': '94bb2f00ae968a2b6c6834257b65fbbf56b43efa18ef8056b61281921dada818',
             'prevout_n': 2,
             'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
             'sighash': None,
             'unknown_psbt_fields': {},
             'utxo': None,
             'value_sats': None,
             'witness_script': None,
             'witness_utxo': None},
            {'address': None,
             'bip32_paths': {},
             'coinbase': False,
             'height': None,
             'nsequence': 4294967293,
             'part_sigs': {},
             'prevout_hash': 'e9b821352e10deb59934cadf53237a124fe9e95c25ebd4c29c7c46f821721cd8',
             'prevout_n': 0,
             'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
             'sighash': None,
             'unknown_psbt_fields': {},
             'utxo': None,
             'value_sats': None,
             'witness_script': None,
             'witness_utxo': None}],
 'locktime': 648529,
 'outputs': [{'address': '3D13MJMnep6Gvc6PSYjCdo3XgPrijGrQ8B',
              'bip32_paths': {},
              'redeem_script': None,
              'scriptpubkey': 'a9147c120fdeddd0d7fbf7361c0b070de134d77054be87',
              'unknown_psbt_fields': {},
              'value_sats': 750,
              'witness_script': None},
             {'address': '32Hhx9CM3gYwChY2ZRFtHTYpJCeUaoypkj',
              'bip32_paths': {},
              'redeem_script': None,
              'scriptpubkey': 'a914068f8e57902905a7280962efeb0a7513d5af3ea287',
              'unknown_psbt_fields': {},
              'value_sats': 820,
              'witness_script': None}],
 'unknown_psbt_fields': {},
 'version': 2,
 'xpubs': {}}
>>> pprint.pprint(t2.to_json())
{'inputs': [{'address': None,
             'bip32_paths': {'02057656d1036539463e925e9f7f8232120750667b77cde62dcaa31d3011d65c67': ('1f244ecc',
                                                                                                    'm/0/0')},
             'coinbase': False,
             'height': None,
             'nsequence': 4294967293,
             'part_sigs': {},
             'prevout_hash': '111ac54b4bca521012620dec5e5478d2db8ae19eded0e049efa44ca843d5fd15',
             'prevout_n': 2,
             'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
             'sighash': None,
             'unknown_psbt_fields': {},
             'utxo': None,
             'value_sats': None,
             'witness_script': None,
             'witness_utxo': None},
            {'address': None,
             'bip32_paths': {'02057656d1036539463e925e9f7f8232120750667b77cde62dcaa31d3011d65c67': ('1f244ecc',
                                                                                                    'm/0/0')},
             'coinbase': False,
             'height': None,
             'nsequence': 4294967293,
             'part_sigs': {},
             'prevout_hash': '94bb2f00ae968a2b6c6834257b65fbbf56b43efa18ef8056b61281921dada818',
             'prevout_n': 2,
             'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
             'sighash': None,
             'unknown_psbt_fields': {},
             'utxo': None,
             'value_sats': None,
             'witness_script': None,
             'witness_utxo': None},
            {'address': None,
             'bip32_paths': {'02057656d1036539463e925e9f7f8232120750667b77cde62dcaa31d3011d65c67': ('1f244ecc',
                                                                                                    'm/0/0')},
             'coinbase': False,
             'height': None,
             'nsequence': 4294967293,
             'part_sigs': {},
             'prevout_hash': 'e9b821352e10deb59934cadf53237a124fe9e95c25ebd4c29c7c46f821721cd8',
             'prevout_n': 0,
             'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
             'sighash': None,
             'unknown_psbt_fields': {},
             'utxo': None,
             'value_sats': None,
             'witness_script': None,
             'witness_utxo': None}],
 'locktime': 648839,
 'outputs': [{'address': '3D13MJMnep6Gvc6PSYjCdo3XgPrijGrQ8B',
              'bip32_paths': {'02d885c4c492b3429f88a31e8378ba20f82056f69c8d663440f885d30172f7bcbc': ('1f244ecc',
                                                                                                     'm/1/25')},
              'redeem_script': '00140e50b8211938e2e878cf4a62195547edad526f37',
              'scriptpubkey': 'a9147c120fdeddd0d7fbf7361c0b070de134d77054be87',
              'unknown_psbt_fields': {},
              'value_sats': 758,
              'witness_script': None},
             {'address': '32Hhx9CM3gYwChY2ZRFtHTYpJCeUaoypkj',
              'bip32_paths': {'03b4099890430e2b6e5e58c1c2133d93866b45890b40561ee0ab7411b619fec114': ('1f244ecc',
                                                                                                     'm/0/2')},
              'redeem_script': '00142ea0e9b867aa329198897a1326fa18161d939c07',
              'scriptpubkey': 'a914068f8e57902905a7280962efeb0a7513d5af3ea287',
              'unknown_psbt_fields': {},
              'value_sats': 812,
              'witness_script': None}],
 'unknown_psbt_fields': {},
 'version': 2,
 'xpubs': {}}
>>>
```

**Comment by aaronisme** [comment]
> Maybe I am misunderstanding the issue... but the second QR code you provided does have paths in the inputs (and outputs):
> 
> ```
> >>> import pprint
> >>> from electrum.transaction import tx_from_any
> >>>
> >>>
> >>> qr1 = "553+311+.ZPPB3GVFDL/QLO46ECZKDNH769PW3/-*M:.A/UY71GP:0O15OH5*97:GO9./XB-J4TBTNKOULBLHNR87ZWH*GS$+WMMB95C86P9I7SQJKGB/G9V6JF0Z6UPQX0HV913S/MLGA5IRSN75UN$:QKRK0IUEC2F-5:VJVM*9EB+0AU7KX0+*S*I784UG+KO1X$-MC174V4TODF6V.++XY875A8QYY.K-YX31/SWHU6RYKMBP812IU$$X8I.+1B+K.WOS$7F+T$NKYV29Q0FHJIT/DUQ+NPVJ.AG8++0KD5MB7I46-$LQ6EI1T5OYDDB50D8DQZ7USD4T-Q-W-/O5QHL4+O.0S*RQ$/.900YNDI3BF:W6CPXEP*Z+GLD9P.IWGHU16GJ.QE1ZHJPULVXU$4+GF:*DZA++C"
> >>> qr2 = ".MJFXL+TF981VNACTQ0XU7UM:A$VBXNK*EJ*N--SIRXIV/K$L$AY0E4:9M+W:A504U2/IWKI932R0B9O/SSMJYFK1SK2WMW6WGFQA*F04.I8M9J846GRQ9VFHC*Y009S14$GK43R.9SF*APECKWHU*B:0Y$BJB$TCB-$EIPW0.K07HT+L0RJ+2Q$CKCV6A9TBKLA0LWWHS.D//LVVSV0O9TFEY*COBDSPI*HVUCF6R+:W*QO:K$9D$XYYW0TFTS3L+SXOI2*NZ-J$2*K*/1+V5Z8+8S+EXXTRRV..9DXI8+R3L4R-G2PA:9MOVA3NIWB0+WF9SF:K6V*VJ+6OFQSQ:9$SMTMPIPD9S*S-PO2BTTKF2Q9.54MD6QVSLG2ODD-X+CNRZLMN4W$/-D+VEK$W8P2DZ50YAKOC/2M3B*Q59DOTP:Q*SYM3Y.8+O87IXGJ-YTF30H52VDD--*EDLHILP+FZQ*XGHHQV642:DYM2MLD0F-NN2X86J951-:VRXW6R$Z1G188MBDT67TP1E+DO2WJSTJUSFD+DK5KPOCRTDYI4JYQ/*+/0C9$W3PY$FIM3FJJZKP./DM.MS38R3XW06DIENI4H-941PKC78WMU94LOE035/*U-+M:+ZQ435$J.OIQU/-TM*$-$J.C*03I$C1L/9/61LF$ECYL5D$/O$5:4PEI9MGGAWZRDF3CD9GE22+18.9E/UIW8ERUJA9EH3*5CNIJX9EWB4TKJZJBXT.MZBFZFS+9*-GYRZ1/+3AR9B5AFQ9:V$/3D3Z3XZZMFYK*JA4.IO:E6YKLKF5Z.IZ+S5B*S3MOHC+H-FQHLKMQMQ.3Z+LS5D0CTXPWP"
> >>>
> >>> t1 = tx_from_any(qr1)
> >>> t2 = tx_from_any(qr2)
> >>>
> >>> pprint.pprint(t1.to_json())
> {'inputs': [{'address': None,
>              'bip32_paths': {},
>              'coinbase': False,
>              'height': None,
>              'nsequence': 4294967293,
>              'part_sigs': {},
>              'prevout_hash': '111ac54b4bca521012620dec5e5478d2db8ae19eded0e049efa44ca843d5fd15',
>              'prevout_n': 2,
>              'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
>              'sighash': None,
>              'unknown_psbt_fields': {},
>              'utxo': None,
>              'value_sats': None,
>              'witness_script': None,
>              'witness_utxo': None},
>             {'address': None,
>              'bip32_paths': {},
>              'coinbase': False,
>              'height': None,
>              'nsequence': 4294967293,
>              'part_sigs': {},
>              'prevout_hash': '94bb2f00ae968a2b6c6834257b65fbbf56b43efa18ef8056b61281921dada818',
>              'prevout_n': 2,
>              'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
>              'sighash': None,
>              'unknown_psbt_fields': {},
>              'utxo': None,
>              'value_sats': None,
>              'witness_script': None,
>              'witness_utxo': None},
>             {'address': None,
>              'bip32_paths': {},
>              'coinbase': False,
>              'height': None,
>              'nsequence': 4294967293,
>              'part_sigs': {},
>              'prevout_hash': 'e9b821352e10deb59934cadf53237a124fe9e95c25ebd4c29c7c46f821721cd8',
>              'prevout_n': 0,
>              'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
>              'sighash': None,
>              'unknown_psbt_fields': {},
>              'utxo': None,
>              'value_sats': None,
>              'witness_script': None,
>              'witness_utxo': None}],
>  'locktime': 648529,
>  'outputs': [{'address': '3D13MJMnep6Gvc6PSYjCdo3XgPrijGrQ8B',
>               'bip32_paths': {},
>               'redeem_script': None,
>               'scriptpubkey': 'a9147c120fdeddd0d7fbf7361c0b070de134d77054be87',
>               'unknown_psbt_fields': {},
>               'value_sats': 750,
>               'witness_script': None},
>              {'address': '32Hhx9CM3gYwChY2ZRFtHTYpJCeUaoypkj',
>               'bip32_paths': {},
>               'redeem_script': None,
>               'scriptpubkey': 'a914068f8e57902905a7280962efeb0a7513d5af3ea287',
>               'unknown_psbt_fields': {},
>               'value_sats': 820,
>               'witness_script': None}],
>  'unknown_psbt_fields': {},
>  'version': 2,
>  'xpubs': {}}
> >>> pprint.pprint(t2.to_json())
> {'inputs': [{'address': None,
>              'bip32_paths': {'02057656d1036539463e925e9f7f8232120750667b77cde62dcaa31d3011d65c67': ('1f244ecc',
>                                                                                                     'm/0/0')},
>              'coinbase': False,
>              'height': None,
>              'nsequence': 4294967293,
>              'part_sigs': {},
>              'prevout_hash': '111ac54b4bca521012620dec5e5478d2db8ae19eded0e049efa44ca843d5fd15',
>              'prevout_n': 2,
>              'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
>              'sighash': None,
>              'unknown_psbt_fields': {},
>              'utxo': None,
>              'value_sats': None,
>              'witness_script': None,
>              'witness_utxo': None},
>             {'address': None,
>              'bip32_paths': {'02057656d1036539463e925e9f7f8232120750667b77cde62dcaa31d3011d65c67': ('1f244ecc',
>                                                                                                     'm/0/0')},
>              'coinbase': False,
>              'height': None,
>              'nsequence': 4294967293,
>              'part_sigs': {},
>              'prevout_hash': '94bb2f00ae968a2b6c6834257b65fbbf56b43efa18ef8056b61281921dada818',
>              'prevout_n': 2,
>              'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
>              'sighash': None,
>              'unknown_psbt_fields': {},
>              'utxo': None,
>              'value_sats': None,
>              'witness_script': None,
>              'witness_utxo': None},
>             {'address': None,
>              'bip32_paths': {'02057656d1036539463e925e9f7f8232120750667b77cde62dcaa31d3011d65c67': ('1f244ecc',
>                                                                                                     'm/0/0')},
>              'coinbase': False,
>              'height': None,
>              'nsequence': 4294967293,
>              'part_sigs': {},
>              'prevout_hash': 'e9b821352e10deb59934cadf53237a124fe9e95c25ebd4c29c7c46f821721cd8',
>              'prevout_n': 0,
>              'redeem_script': '001494cb85b5f8418d4c6b3dacdcd964ffaa2d104756',
>              'sighash': None,
>              'unknown_psbt_fields': {},
>              'utxo': None,
>              'value_sats': None,
>              'witness_script': None,
>              'witness_utxo': None}],
>  'locktime': 648839,
>  'outputs': [{'address': '3D13MJMnep6Gvc6PSYjCdo3XgPrijGrQ8B',
>               'bip32_paths': {'02d885c4c492b3429f88a31e8378ba20f82056f69c8d663440f885d30172f7bcbc': ('1f244ecc',
>                                                                                                      'm/1/25')},
>               'redeem_script': '00140e50b8211938e2e878cf4a62195547edad526f37',
>               'scriptpubkey': 'a9147c120fdeddd0d7fbf7361c0b070de134d77054be87',
>               'unknown_psbt_fields': {},
>               'value_sats': 758,
>               'witness_script': None},
>              {'address': '32Hhx9CM3gYwChY2ZRFtHTYpJCeUaoypkj',
>               'bip32_paths': {'03b4099890430e2b6e5e58c1c2133d93866b45890b40561ee0ab7411b619fec114': ('1f244ecc',
>                                                                                                      'm/0/2')},
>               'redeem_script': '00142ea0e9b867aa329198897a1326fa18161d939c07',
>               'scriptpubkey': 'a914068f8e57902905a7280962efeb0a7513d5af3ea287',
>               'unknown_psbt_fields': {},
>               'value_sats': 812,
>               'witness_script': None}],
>  'unknown_psbt_fields': {},
>  'version': 2,
>  'xpubs': {}}
> >>>
> ```

@SomberNight Thanks for your reply, the second QR code has the bip32 paths, but it missing witness utxo or utxo which will make the signer fail to sign the psbt.

**Comment by SomberNight** [comment]
indeed this is a regression; from https://github.com/spesmilo/electrum/commit/73cf007048b4f9381814d065c60999eda70e158c
