### ISSUE TITLE
Non-standard json rpc response

### ISSUE THREAD

**Issue by sharifzadesina** [spesmilo/electrum#6612]
As the JSON RPC protocol mentions, the response object must contain `jsonrpc` member.
In the past major version 3, this was ok, but it seems in version 4, we no longer get `jsonrpc` member which is for versioning.
This is non-standard and causes some libraries to report invalid response errors.
Reference: https://www.jsonrpc.org/specification#response_object

**Comment by SomberNight** [comment]
This is re the daemon, right? As opposed to json-rpc between electrum client and electrum server.

**Comment by sharifzadesina** [comment]
@SomberNight I am not aware of the electrum server. I am just using this repo, which is for the client.

**Comment by sharifzadesina** [comment]
This is an example, as you see the `jsonrpc` member is not included in the response.
![2020-09-23_22-37-27](https://user-images.githubusercontent.com/15300551/94058118-7f1e7380-fded-11ea-87af-12da488359c0.png)

**Comment by SomberNight** [comment]
Thanks for the report.
Could you please test if it master now behaves as expected?
