### ISSUE TITLE
Unconfirmed payment now for 5 days. I bumped up the fees to MAX day 1. still unconfirmed wtf is happpening

### ISSUE THREAD

**Issue by erkamzu** [spesmilo/electrum#6616]
Unconfirmed payment now for 5 days. I bumped up the fees to MAX day 1. still unconfirmed wtf is happpening

**Comment by SomberNight** [comment]
It is impossible to give advice with only the info you have given. Provide some details; e.g. a screenshot of the history tab and/or a txid.

**Comment by erkamzu** [comment]
https://gyazo.com/7b4734bc8fca67562a77a4636194ab9e

well now it says hours

**Comment by erkamzu** [comment]
https://gyazo.com/8b0b02e61db6e30cb1b41e26e714c5ee

**Comment by SomberNight** [comment]
> I bumped up the fees to MAX day 1

Image shows 3 sat/byte. What do you mean by "MAX" then? 3 s/b is a low fee.
Also, based on image, you don't have RBF (replace by fee) enabled (which it is by default, so you had manually disabled that), so now it's not that easy to bump the fee.
Anyway, see https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do
