### ISSUE TITLE
Right Click -> Copy -> Date on an unconfirmed transaction does not copy the date

### ISSUE THREAD

**Issue by br7369** [spesmilo/electrum#6626]
I am using Electrum 4.0.3 on Windows 7. If I right-click on an Unconfirmed transaction, select Copy, and select Date, the value put into the clipboard is actually the value of what is displayed instead of the value of a date.

As an example, the value "Unconfirmed [25.1 sat/b, 1.95 MB]" it put into my clipboard but I expect it to be a date/time of the transaction.

**Comment by ecdsa** [comment]
that's not really a bug
the date of an onchain transaction is the date of the block where is was confirmed.
that is not available for an unconfir,ed transaction.
