### ISSUE TITLE
Simplify lightning activation

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6627]
We want to get rid of enable/disable buttons for lightning. 

Note that the gossip process uses a node id that differs from the wallet's node id, because we don't want to request gossip multiple times if the user opens several wallets. Gossip is currently activated only if at least one lightning wallet is open.

@bitromortac suggested to enable lightning by default (create keys), and to restrict the activation of gossip to wallets that actually have channels.

I think it could work. 

The automatic node suggestion that we currently have is not very good, we should not try to keep it in its current form. Instead, we could suggest our own node (lightning.electrum.org) if the gossip has never been running.

If the user tries to send or receive with lightning but has no channels, the channel tab should be enabled and the channel creation popup should be displayed. (in the future, maybe also propose a swap to be able to receive)

Note: if lightning keys are created by default, a wallet storage upgrade will be needed for older wallets.

**Comment by SomberNight** [comment]
> bitromortac suggested to enable lightning by default (create keys), and to restrict the activation of gossip to wallets that actually have channels.

Sounds reasonable.

(1) I think LNGossip could run if there is "at least one wallet open that has any lightning channels" (even if all channels are closed).

(2) Another idea is to loosen this restriction: run LNGossip if the user has ever opened a channel in any wallets. We could maybe set a config key to signal this. In practice, we would then check for "at least one wallet open that has any lightning channels OR config key is set".

The motivation behind (2) is that we could start running LNGossip sooner: it could already start while the user is entering their password. It often takes me ~half a minute to enter my password on Android. Note that loading the gossip db from disk takes several seconds (on Android, even 20-40 seconds), so starting this while the user is entering their password could be worthwhile.

**Comment by ecdsa** [comment]
I don't like the idea of adding a config key in (2), because it would mean that creating a LN channel has a long term side effect, invisible to the user. 

I suggest we dissociate running LNGossip from loading the channel db. We can load the DB early and inconditionally, as you suggest, and run the gossip only if at least one open wallet has a lightning channel. This would solve the slow loading on android, without adding network overhead for users who do not use lightning

**Comment by SomberNight** [comment]
> I suggest we dissociate running LNGossip from loading the channel db. We can load the DB early and inconditionally

Sounds reasonable.

**Comment by ecdsa** [comment]
closing, fixed in #6639
