### ISSUE TITLE
Labels don't appear synchronised accross History/Addresses/Coins tab. label of coins/utxos cannot be changed/edited

### ISSUE THREAD

**Issue by Armantheparman** [spesmilo/electrum#6644]
Using Mac OS, version 4.03:

I double clicked the empty field to edit a label under the History tab.
It appeared under the respective coin in the coins tab, but under addresses tab it remained empty.

While writing this I tested editing a label under the addresses tab. I entered "test", and it did not appear under the correct UTXO in history or coins tab.

Also, in the coins tab, you can not double click to edit the labels. It doesn't respond.

**Comment by SomberNight** [comment]
Some of what you describe are definitely not bugs, although I acknowledge that overall how labels work is not really intuitive.

1. Atm only txids and addresses can have labels.
2. The History tab shows transactions, so labels of txids are shown there. If a txid has no label, then we fallback to a default txid label: concat the labels of output addresses.
3. The Addresses tab shows addresses, so labels of addresses are shown there.
4. The Coins tab showns coins (UTXOs). Coins do not have labels of their own. Atm we show the label of the corresponding txid.

**Comment by Armantheparman** [comment]
Thanks for that. "Bug" might not be the right word, sorry. 

I do think the behaviour was not as expected intuitively. It wasn't apparant to me that a tx label and an address label and a UTXO label (which doesnt exist) are not the same thing, possibly because they are all called labels and appear in the same column in the respective tabs, and because of the concatenation behaviour you described in "history".

It might be clearer to have column headings: "address label" and "Tx label"?

Also in "history" maybe have an "address label" column AND a "tx label" column which can optionally be shown or hidden? Right now for the concatenation behaviour described, is not intuitive what's going on.

I'd help, but still learning the basics of coding at this stage.

**Comment by SomberNight** [comment]
> Also in "history" maybe have an "address label" column AND a "tx label" column which can optionally be shown or hidden?

I don't think it's worth making the interface more complicated.
Also note that there are potentially many addresses associated with a transaction.

**Comment by Armantheparman** [comment]
OK, just a thought
