### ISSUE TITLE
"Sign" button greyed out on Tails

### ISSUE THREAD

**Issue by sunknudsen** [spesmilo/electrum#6648]
Hi,

I configured a test multi-sig wallet using Electrum macOS, Electrum Tails and a Trezor One.

The addresses are identical on Electrum macOS and Tails which means the multi-sig is configured properly right?

I prepared a send transaction on macOS and using the "Show as QR code" export feature, I am trying to sign the transaction on Tails ("Load transaction" / "From QR code").

The sign button is greyed out... what am I missing?

Thanks!

Sun

**Comment by sunknudsen** [comment]
FYI, "Transaction ID" is "Unknown" and "Fee" is "unknown" on Tails... not normal right?

**Comment by sunknudsen** [comment]
The issue is present on Electrum `4.0.2` on Tails.

**Comment by SomberNight** [comment]
Could you detail the multisig? How many cosigners and which machines exactly? Is it a 2of2 between macOS and Tails? Where does the Trezor come into play? Which machines are connected to the Internet, which are offline? What version of Electrum are you using on macOS?

**Comment by sunknudsen** [comment]
@SomberNight 

The multi-sig wallet is configured as a 2 of 3.

I was able to send sats using Electrum macOS and Trezor.

When I export a transaction from Electrum macOS (`4.0.3`) to Electrum Tails (`4.0.2`, offline), the above issue is present.

I just tried using the Electrum AppImage (`4.0.3`, offline ) on Tails and the same issue is present.

Thanks for your help!

**Comment by sunknudsen** [comment]
Forgot to mention I am using Tails `4.11`.

**Comment by SomberNight** [comment]
I think it's because of https://github.com/spesmilo/electrum/issues/6600
It's a regression in 4.0.3 - affects the machine that generates the QR code. Try with 4.0.2, or run from git master.

**Comment by SomberNight** [comment]
> FYI, when importing the transaction using QR code on Tails, the app hanged for a few seconds (I thought it was going to crash)... but finally everything worked.

should be fixed by https://github.com/spesmilo/electrum/commit/bde415cae781f12a96d7d971ecfd641d76c20bfb
