### ISSUE TITLE
Cannot edit description of "Paid" transactions in "Send" and "Receive"

### ISSUE THREAD

**Issue by sunknudsen** [spesmilo/electrum#6650]
Not sure if this is by design, but I recall being able to edit description in previous versions.

**Comment by SomberNight** [comment]
The Send tab lists invoices, and the Receive tab lists payment requests. The descriptions of these cannot be changed after creation. I don't recall this having changed. (what changed is that the Send tab previously only listed BIP70 invoices)
Also note that at least Lightning invoices/payment requests, and BIP70 invoices/payment requests contain a signature that commit to the description so in those cases it does not make sense to allow changing it.

The History tab lists transactions: the labels of these can be changed at any time.

**Comment by sunknudsen** [comment]
@SomberNight Thanks for the follow-up. 

> Also note that at least Lightning invoices/payment requests, and BIP70 invoices/payment requests contain a signature that commit to the description so in those cases it does not make sense to allow changing it.

I agree... must have been confused between the "History" tab and the two others.

**Comment by sunknudsen** [comment]
> The Send tab lists invoices, and the Receive tab lists payment requests. The descriptions of these cannot be changed after creation.

@SomberNight Do you have a moment to help me understand why these descriptions cannot be changed after creation? Are these descriptions written to the blockchain?

**Comment by SomberNight** [comment]
No, invoice descriptions are not stored in the blockchain.

There are multiple types of invoices/payment requests that need to be distinguished. (note that invoices and payment requests are the ~same, it is just terminology this codebase uses to distinguish direction; invoices are for outgoing payments; payment requests are for incoming payments. Here I will just say invoice for both cases.)

- Lightning invoices are signed.
- BIP70 invoices (used for some onchain payments, historically mainly by BitPay) are signed.
- BIP21 invoices (most common for onchain payments) are NOT signed.

If an invoice is signed that means changing any of their fields after creation requires changing the signature as well (signing it again). First of all, note that obviously you would not be able to re-sign for outgoing invoices (that someone else gave you).
Even for incoming invoices (that you created), you might have already given out the invoice to a friend/customer, who will see the old description regardless and they will have a signature from you attesting to that description.

If an invoice is not signed, we could allow changing its description for either direction. However note again that the description would only change for you locally. i.e. for outgoing invoices (that someone else gave you), the invoice creator would still see the old description; and for incoming invoices (that you created and gave out), the payer would still see the old description.
To avoid misunderstandings, I think it is simplest to not allow changing the description.

Note that in case of incoming invoices that you created, if you have not yet given them out, you can just delete and re-create them with a different description. Also, AFAICT this matches expectations from the real world, where you cannot simply modify an invoice unilaterally.

**Comment by sunknudsen** [comment]
Thanks for detailed explanation @SomberNight.
