### ISSUE TITLE
Can't Send BTC Help

### ISSUE THREAD

**Issue by Orion81200** [spesmilo/electrum#6655]
I can't send btc with app ( status Pending or Unsigned ) I tried backup on Win 10 but 0 btc wtf ?
Help Please

**Comment by matthewwsAlfa** [comment]
I Have the same problem , I can't send bitcoin to other btc address.

**Comment by SomberNight** [comment]
Sorry but these reports are useless. Please provide more details, e.g. a screenshot, or a full descriptions of what you are clicking and observing. "does not work" is not actionable.
