### ISSUE TITLE
New lightning channel not saved to wallet (funds lost!)

### ISSUE THREAD

**Issue by mwnx** [spesmilo/electrum#6656]
Hi,

I tried opening a lightning channel (using the GUI) and got a segfault very soon after the channel was created and the funding transaction was broadcast. The channel appeared in the GUI's channel list before the crash. This bug report isn't about the segfault however (which I wasn't able to look into since my system did not produce a core dump) but about the fact that my wallet was not saved to disk before the crash, hence why my funds (thankfully not a large amount) are lost.

The good news is I think I've identified the reason why the wallet was not saved to disk. In `lnworker.py`:
```
    def add_new_channel(self, chan):
        self.add_channel(chan)
        channels_db = self.db.get_dict('channels')
        channels_db[chan.channel_id.hex()] = chan.storage
        for addr in chan.get_wallet_addresses_channel_might_want_reserved():
            self.wallet.set_reserved_state_of_address(addr, reserved=True)
        self.wallet.save_backup() # !!!
```
I'm pretty sure `save_backup` should be `save_db`, like everywhere else in `lnworker.py`! In my case, `save_backup` did nothing since by default the config file does not specify a backup location and I did not set one manually.

By the way, I also wonder if `save_db` shouldn't also be called before calling `try_broadcasting` in `_open_channel_coroutine` to account for the possibility of a crash after the transaction has been broadcast. I'm guessing this would not lead to a loss of funds however and so would not be as much of an issue.

Also, just to satisfy my curiousity, in the same function, this condition has me a bit perplexed:
```
        if funding_tx.is_complete():
            await self.network.try_broadcasting(funding_tx, 'open_channel')
```
In what legitimate case would the funding transaction be incomplete, and how could the channel be properly opened if the transaction were to not be broadcast?

Thanks for your great work on Electrum by the way.

**Comment by SomberNight** [comment]
ack, I could reproduce :/
Thank you for the report!

> The good news is I think I've identified the reason why the wallet was not saved to disk. In lnworker.py:

Yes you are correct, the wallet db should be flushed to disk at that point.
I have changed this now in https://github.com/spesmilo/electrum/commit/c3fb79d412e0dc86b65f6ac8f117d28e0be08b4a

`chan.set_state` already results in a save to disk near the end of `channel_establishment_flow`, however a bit confusingly it is called just before actually adding the channel to the db, so it will not save the channel itself...
https://github.com/spesmilo/electrum/blob/82c8c4280f598c3755448eb988ad89821cd61a53/electrum/lnpeer.py#L662-L664

> By the way, I also wonder if save_db shouldn't also be called before calling try_broadcasting in _open_channel_coroutine to account for the possibility of a crash after the transaction has been broadcast. I'm guessing this would not lead to a loss of funds however and so would not be as much of an issue.

The channel should be saved before we try to broadcast, as it is fine to fail to broadcast but succeed to save, but not fine to broadcast but not save (and crash).

> In what legitimate case would the funding transaction be incomplete, and how could the channel be properly opened if the transaction were to not be broadcast?

You can use lightning with a watchonly wallet (xpub only). There the flow will give the user a partial tx, which can be exported and signed offline, and then imported back and broadcast to open the channel. Lightning keys are then stored on the online machine but keys for onchain addresses are offline.

-----

As for losing your coins, not all hope is lost.

Any chance you know what node you had opened the channel with? (its node ID)
If so, I have added a method `request_remote_force_close` in commit https://github.com/spesmilo/electrum/commit/82c8c4280f598c3755448eb988ad89821cd61a53 that you could try to use via the Qt `Console` tab.
I have reproduced the bug on testnet, and successfully used `request_remote_force_close` to get back the coins.

Even if you don't know the remote node id, as we enable `option_static_remotekey`, if the remote closes the channel, you will get your coins back -- unfortunately though I assume all the balance is on your side of the channel, so the remote is not in any kind of hurry to close it.

**Comment by mwnx** [comment]
> ack, I could reproduce :/
> Thank you for the report!
> 
> > The good news is I think I've identified the reason why the wallet was not saved to disk. In lnworker.py:
> 
> Yes you are correct, the wallet db should be flushed to disk at that point.
> I have changed this now in [c3fb79d](https://github.com/spesmilo/electrum/commit/c3fb79d412e0dc86b65f6ac8f117d28e0be08b4a)

Do we still want to call `save_backup` at this point? I'm guessing we don't since the only other places where it is called is from the GUI code. I removed it in my branch [1].

> > By the way, I also wonder if save_db shouldn't also be called before calling try_broadcasting in _open_channel_coroutine to account for the possibility of a crash after the transaction has been broadcast. I'm guessing this would not lead to a loss of funds however and so would not be as much of an issue.
> 
> The channel should be saved before we try to broadcast, as it is fine to fail to broadcast but succeed to save, but not fine to broadcast but not save (and crash).

I added a call to `save_db` for this case in my branch [1]. Of course, this does make the "save" performed through `add_new_channel` redundant when called from `channel_establishment_flow` (but not from `on_open_channel` —actually, isn't that function dead code? It doesn't seem to be called from anywhere).

> > In what legitimate case would the funding transaction be incomplete, and how could the channel be properly opened if the transaction were to not be broadcast?
> 
> You can use lightning with a watchonly wallet (xpub only). There the flow will give the user a partial tx, which can be exported and signed offline, and then imported back and broadcast to open the channel. Lightning keys are then stored on the online machine but keys for onchain addresses are offline.

Okay, that's pretty neat!

> As for losing your coins, not all hope is lost.
> 
> Any chance you know what node you had opened the channel with? (its node ID)
> If you have logs, there might be a clue there.
> If so, I have added a method `request_remote_force_close` in commit [82c8c42](https://github.com/spesmilo/electrum/commit/82c8c4280f598c3755448eb988ad89821cd61a53) that you could try to use via the Qt `Console` tab.
> I have reproduced the bug on testnet, and successfully used `request_remote_force_close` to get back the coins.

This worked. Thanks a lot for the (amazingly quick) commit and reply!

[1] https://github.com/spesmilo/electrum/pull/6663

**Comment by SomberNight** [comment]
> Do we still want to call save_backup at this point? I'm guessing we don't since the only other places where it is called is from the GUI code. I removed it in my branch [1].

Yes, let's keep that. If there is a backup dir configured, this makes a backup into that every time a new channel is opened.

>> The channel should be saved before we try to broadcast, as it is fine to fail to broadcast but succeed to save, but not fine to broadcast but not save (and crash).
>
> I added a call to `save_db` for this case in my branch [1]. Of course, this does make the "save" performed through `add_new_channel` redundant when called from `channel_establishment_flow`

What I was trying to say there is I don't think we need to save the channel right before the moment we broadcast; it is fine to save it somewhat earlier, in `add_new_channel`. I meant - in general - what should not happen is being in a state where we have broadcast the funding tx but have not persisted the channel to disk. Current master satisfies this now, thanks to your report.

> is does make the "save" performed through `add_new_channel` redundant when called from `channel_establishment_flow` (but not from `on_open_channel` —actually, isn't that function dead code? It doesn't seem to be called from anywhere).

It is called dynamically from here:
https://github.com/spesmilo/electrum/blob/21e46fb14796076afca148fcd6cc8ada11a7d17a/electrum/lnpeer.py#L188

**Comment by mwnx** [comment]
On Tue, Oct 20, 2020 at 06:53:15PM -0700, ghost43 wrote:
> > Do we still want to call save_backup at this point? I'm guessing we don't since the only other places where it is called is from the GUI code. I removed it in my branch [1].
>
> Yes, let's keep that. If there is a backup dir configured, this makes a backup into that every time a new channel is opened.

Oh, it just seemed rather arbitrary to me that a backup would only be
saved upon opening a channel and not in other situations.

> >> The channel should be saved before we try to broadcast, as it is fine to fail to broadcast but succeed to save, but not fine to broadcast but not save (and crash).
> >
> > I added a call to `save_db` for this case in my branch [1]. Of course, this does make the "save" performed through `add_new_channel` redundant when called from `channel_establishment_flow`
>
> What I was trying to say there is I don't think we need to save the channel right before the moment we broadcast; it is fine to save it somewhat earlier, in `add_new_channel`. I meant - in general - what should not happen is being in a state where we have broadcast the funding tx but have not persisted the channel to disk. Current master satisfies this now, thanks to your report.

I agree. My commit was about making sure the transaction named "Open
channel" was saved to disk. Of course, I'm sure the transaction would be
loaded back from the mempool or the blockchain in case of a crash
occurring after broadcasting the transaction, so the only loss would be
the transaction's label (i.e. "Open channel"), which I guess isn't a big
deal.

> > is does make the "save" performed through `add_new_channel` redundant when called from `channel_establishment_flow` (but not from `on_open_channel` —actually, isn't that function dead code? It doesn't seem to be called from anywhere).
>
> It is called dynamically from here:
> https://github.com/spesmilo/electrum/blob/21e46fb14796076afca148fcd6cc8ada11a7d17a/electrum/lnpeer.py#L188

Missed that. Thanks!

--
mwnx
GPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726
     ipfs.io/ipfs/QmdLc7sFYA3SeAocaFC5AaVJKfruj5ecePoj1iW2rWzgPS
