### ISSUE TITLE
cant send money

### ISSUE THREAD

**Issue by kilaue** [spesmilo/electrum#6658]
"The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

Transaction could not be broadcast due to dust outputs."

**Comment by scuila** [comment]
Same, but my error message is slightly different:
"The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.
Unknown error"
Ubuntu 18.04
This happened right after updating to Electrum 4.0.4
I have tried to manually connect to some of the servers on this list: https://1209k.com/bitcoin-eye/ele.php

![Screenshot from 2020-10-17 11-20-21](https://user-images.githubusercontent.com/5673356/96336694-df69a380-1081-11eb-898d-b9dc5f8f061f.png)

![Screenshot from 2020-10-17 11-20-38](https://user-images.githubusercontent.com/5673356/96336695-e09ad080-1081-11eb-944c-472f89ea415d.png)

**Comment by SomberNight** [comment]
@kilaue double-check the amounts and units. The default unit is mBTC, not BTC. 1 BTC = 1000 mBTC. (a dust output is an output that is too small)

@scuila check[ debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) to see the full error message as coming from the server. do not trust the message though, just check what it says, maybe there is a clue there.

**Comment by kilaue** [comment]
"The default unit is mBTC, not BTC. 1 BTC = 1000 mBTC. (a dust output is an output that is too small)"
That was the problem, 
moron=me   
:)  :)  :)
