### ISSUE TITLE
Provide estimate of fees in fiat, and warn if they are high

### ISSUE THREAD

**Issue by micah** [spesmilo/electrum#6664]
When you send coins, the fee estimator is extremely useful. However, it presents things only in btc, and it would be really convenient if it would use the Fiat currency setting to show approximately how much the fee translates to.

The other day I created a transaction, it was pretty small, but it had a lot of inputs. The fee looked reasonable to me, but I misread how many zeros there were after the decimal point, and I nearly sent a transaction with a 220$ fee. Fortunately, I took the fee number and checked it, but if electrum had shown me the fiat conversion, it would have been a lot easier.

Also, it would be *really* nice if Electrum issued a warning when you were about to send a fee over a certain "reasonable" threshold, to make sure you want to do that. It does ask you to confirm your transaction, but if it says "WARNING: Your fee is abnormally high: 220$! Are you sure you want to send with this fee?"

**Comment by SomberNight** [comment]
> the fee estimator [...] presents things only in btc, and it would be really convenient if it would use the Fiat currency setting to show approximately how much the fee translates to.
> if electrum had shown me the fiat conversion, it would have been a lot easier

Isn't the fee already shown in fiat too?
<details>
 <summary>pic1</summary>

![Capture](https://user-images.githubusercontent.com/29142493/96385081-11156400-1181-11eb-8df1-2dfa44e9683d.PNG)
</details>


> Also, it would be really nice if Electrum issued a warning when you were about to send a fee over a certain "reasonable" threshold, to make sure you want to do that. It does ask you to confirm your transaction, but if it says "WARNING: Your fee is abnormally high: 220$! Are you sure you want to send with this fee?"

There are already two warning conditions:
- if the fee exceeds 5% of the amount Electrum thinks you are sending
    <details>
     <summary>pic2</summary>
    
    ![Capture2](https://user-images.githubusercontent.com/29142493/96385084-14105480-1181-11eb-8f07-16745f4e73fb.PNG)
    </details>
- if the feerate is over 600 sat/byte
    <details>
     <summary>pic3</summary>
    
    ![Capture3](https://user-images.githubusercontent.com/29142493/96385136-76695500-1181-11eb-9f3b-656a29055140.PNG)
    </details>

What new warning condition would you like to see added specifically?

**Comment by micah** [comment]
Hum, you are right!

However, I was working in the 'advanced' section, which does not show
the fiat conversion.

I no longer have any coins to generate screenshots, I'm sorry.

**Comment by micah** [comment]
Here you go, as you can see here in the advanced dialog, it doesn't show me the conversion (although in the basic one it does):

![2020-10-18-170003_954x492_scrot](https://user-images.githubusercontent.com/2832/96385683-0361dd80-1185-11eb-81ab-35f357c8d9d7.png)

This is approximately 68$ fee.... I think the two warning conditions are nice... but it might be good to be able to configure these in some way in the preferences. For example, I would like to be warned if the fee is ever over $10, even if the fee is less than 5% of what I'm sending.

**Comment by mnaei** [comment]
How does this look? I put $$$$ where the fee estimates in USD would be displayed? 
![Capture4](https://user-images.githubusercontent.com/6119296/102277668-9ce40c00-3ef6-11eb-9561-490a917f8af4.PNG)

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/pull/6968 added fiat estimates for amounts and fees in the Advanced tx preview dialog, and
https://github.com/spesmilo/electrum/commit/f9f49daad7a9eee80abccd49ce43bee07258fd99 ported the missing warning conditions (namely high fee ratio (fee/amount)) to the Advanced tx preview dialog

Example:
![Capture](https://user-images.githubusercontent.com/29142493/109383774-a5869480-78e0-11eb-98b6-74291b922c40.PNG)


>> What new warning condition would you like to see added specifically?
>
> [...] This is approximately 68$ fee.... I think the two warning conditions are nice... but it might be good to be able to configure these in some way in the preferences. For example, I would like to be warned if the fee is ever over $10, even if the fee is less than 5% of what I'm sending.

Something like that could be added later; feel free to open another issue specifically asking for that if you feel strongly about it.

I am closing this, as I think the changes made mostly satisfy this issue.
