### ISSUE TITLE
Wallet corrupted after converting from v4.0.4 to v2.8.3

### ISSUE THREAD

**Issue by stefanfraga** [spesmilo/electrum#6667]
I've converted a wallet from v4.0.4 to v2.8.3 and now neither version can open the file. Does anyone know if there is a way to reverse this?

**Comment by SomberNight** [comment]
do you mean from 2.8.3 to 4.0.4?
what error do you get when opening the wallet file in 4.0.4?

**Comment by stefanfraga** [comment]
No, I accidentally opened a v4.0.4 wallet in an older version of electrum, not realizing the mistake I said yes to upgrade it to the correct version and it cannot be opened now.

Is this a process that I can reverse? I was thinking about checking out the 2.8.3 tag and trying to step through the code to see systematically what it does to the wallet file

**Comment by SomberNight** [comment]
ah, I see. Unfortunately, the db upgrade code was really stupid until 3.0 - e.g. it could not detect that the file is newer than the code

I think your best bet is to restore from seed.

**Comment by stefanfraga** [comment]
The seed is locked away somewhere I can't get to right now, is it worth trying to reverse the wallet changes or do you think that will be impossible?

**Comment by SomberNight** [comment]
I am not sure how it mangled the wallet file.
If you are a programmer, and have the wallet password, it should be possible to extract the seed from the file.

-----

Using latest Electrum, try a patch along these lines, and try to open the wallet file normally (e.g. with GUI):
```patch
diff --git a/electrum/wallet_db.py b/electrum/wallet_db.py
index fc792a8eba..d9ec192566 100644
--- a/electrum/wallet_db.py
+++ b/electrum/wallet_db.py
@@ -74,6 +74,10 @@ class WalletDB(JsonDB):
         else:  # creating new db
             self.put('seed_version', FINAL_SEED_VERSION)
             self._after_upgrade_tasks()
+        ks = self.get('keystore')
+        print(f"ks={ks}")
+        encrypted_seed = ks['seed']
+        print(f"encrypted_seed={encrypted_seed!r}")
 
     def load_data(self, s):
         try:

```

Then run a python interpreter and decrypt the seed you got above:
```
>>> from electrum.crypto import pw_decode
>>> pw_decode("my encrypted seed", password="my password", version=1)
```

**Comment by stefanfraga** [comment]
I do have the password so I will try that thank you! I program but I've never messed with this kind of stuff.

**Comment by stefanfraga** [comment]
Update: That worked perfectly thank you so much for helping

**Comment by SomberNight** [comment]
np, glad to hear
