### ISSUE TITLE
Electrum Support Email

### ISSUE THREAD

**Issue by ho3inshati77** [spesmilo/electrum#6668]
Hi
I want the email of electrum support to speak to recover an electrum wallet.
Can I have the email?

**Comment by Gangster8192** [comment]
Maintainers, support, really anyone of electrum cannot recover you wallet if you forgot the password.

**Comment by SomberNight** [comment]
We don't have the manpower to provide support privately. Feel free to detail your issue here, someone might be able to help. Obviously do not disclose sensitive information.

**Comment by ho3inshati77** [comment]
> Maintainers, support, really anyone of electrum cannot recover your wallet if you forgot the password.

I have an electrum wallet and I have my private keys as well and so I have my password but I have 10 characters of my password because my computer disturbed and formatted and I could return just 10 character. Can I recover it?

**Comment by ho3inshati77** [comment]
> We don't have the manpower to provide support privately. Feel free to detail your issue here, someone might be able to help. Obviously do not disclose sensitive information.

I have an electrum wallet and I have my private keys as well and so I have my password but I have 10 characters of my password because my computer disturbed and formatted and I could return just 10 character. Can I recover it?

**Comment by ecdsa** [comment]
do you have your seed?

**Comment by ho3inshati77** [comment]
> do you have your seed?

Yes, I have my 12 phrases right now but it is for the backup of the bitcoin core software that I have from my laptop that is formatted. is it useful for me?
Can you help me?

**Comment by SomberNight** [comment]
It is difficult to understand you.
Bitcoin Core does not use seed words.
If you have the seed words that were displayed by Electrum when you created your wallet, you can restore your wallet from that.

**Comment by ho3inshati77** [comment]
> It is difficult to understand you.
> Bitcoin Core does not use seed words.
> If you have the seed words that were displayed by Electrum when you created your wallet, you can restore your wallet from that.

my wallet was on the electrum wallet. i used bitcoin core software on my laptop. one time I have backed up the wallet to increase the security of the wallet and download the information wallet from the blockchain. half of the wallet information was in the BitLocker flash the rest of the information was on the bitcoin core software on the laptop. now I have just 12 phrases of blockchain and 10 characters of my wallet password. i should enter the information again in the blockchain and recover them from electrum wallet. all the story of my problem is this.

**Comment by ecdsa** [comment]
@ho3inshati77 this website is not a user support hotline, but a bug report system. 
This type of report is not interesting for us.
We accept only reports that help us improve Electrum, all the rest is a waste of developers time. 
I think your problem, although poorly expressed, finds its answer in the FAQ.
