### ISSUE TITLE
Problem running Electrum 4.0.4 on offline machine without libsecp256k1

### ISSUE THREAD

**Issue by aeh4h4eaan5e** [spesmilo/electrum#6669]
OS: Ubuntu 19.10
32bit Arch

Attempting to run the python "python3 Electrum-4.0.4/run_electrum" without installation on my offline machine gives me an expected error message of (I can't copy/paste verbatim) "cannot open shared object file: No such file or directory Error: Failed to load libsecp256k1"

Which is crazy, because I spun up a Digital Ocean 32 bit machine and built this library on there then copied the file over via USB into the electrum sub-folder. It's there, with proper 755 permissions. My Electrum 3.3.8 version runs fine but I'd like to upgrade.

I'm confused.

**Comment by SomberNight** [comment]
> and built this library on there then copied the file over via USB into the electrum sub-folder

Is it named `libsecp256k1.so.0`?

**Comment by aeh4h4eaan5e** [comment]
Yes sir

**Comment by SomberNight** [comment]
what does `file` say? e.g. `$ file electrum/libsecp256k1.so.0`

**Comment by SomberNight** [comment]
> OS: Ubuntu 19.10
32bit Arch

> I spun up a Digital Ocean 32 bit machine and built this library on there then copied the file over via USB

If the VM did not have the same arch as the target, you need to specify extra flags to cross-compile. By default it builds for the host machine.

I've added instructions here:
https://github.com/spesmilo/electrum/commit/21e46fb14796076afca148fcd6cc8ada11a7d17a
Note that they only work if the build machine has this commit (so you need git master).

**Comment by aeh4h4eaan5e** [comment]
Thanks - yeah I ran into that on a diff server I had that was 64 bit and it complained the ELF was wrong. I ran the file command for you, the output:

/home/user/Desktop/Electrum-4.0.4/electrum/libsecp256k1.so.0: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=a8de93eeef117c56571722e639dae19e8b9f7c7f, with debug_info, not stripped

**Comment by aeh4h4eaan5e** [comment]
Is there an Appimage I can run instead that is 32bit? I just tried the Appimage in the downloads section and that is 64bit.

**Comment by SomberNight** [comment]
No, unfortunately, atm we only build an x86_64 appimage.
However if someone could contribute code to build one for x86, that would be welcome.

**Comment by aeh4h4eaan5e** [comment]
Got it. I guess you can close this; I'll have to buy an x86_64 machine and rebuild my offline one. Thanks for your replies!

**Comment by SomberNight** [comment]
I'm still curious why you cannot get it to work to run from source on x86. Is it really libsecp causing trouble? I would have guessed PyQt instead...

**Comment by aeh4h4eaan5e** [comment]
It is a mystery to me too. The file is there. I even modified ecc_fast.py
(or whatever that file was) on line 49 and hardcoded the direct exact same
path to the file in the ctypes cdll loadlibrary command. Exact same error!
There isn't a .... Python cache right? That's ridiculous to think about.
Python 3.7

**Comment by SomberNight** [comment]
Just to make sure -- there should be two exceptions printed because it tries to load from two different paths.
e.g.:
`E | ecc_fast | libsecp256k1 library failed to load. exceptions: [OSError('/home/user/wspace/electrum/electrum/libsecp256k1.so.0: cannot open shared object file: Permission denied'), OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory')]`
- in my case the first is: `OSError('/home/user/wspace/electrum/electrum/libsecp256k1.so.0: cannot open shared object file: Permission denied'`
- and the second: `OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory')`

If you have copied `libsecp256k1.so.0` into the inner electrum folder, we would expect the first path to work - so it is the first exception that's interesting. The second exception is probably the same as mine above - it will just not find the file at that path.

What exactly do you get for the first exception? Does it differ from the second one?

**Comment by aeh4h4eaan5e** [comment]
Sure thing, just gave it another try and there's two exceptions being raised:

```
sorry@ubuntu:~/Electrum-4.0.4$ python3 run_electrum --offline
E | ecc_fast | libsecp256k1 library failed to load. exceptions: [OSError('/home/sorry/Electrum-4.0.4/electrum/libsecp256k1.so.0: cannot open shared object file: No such file or directory'), OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory')]
Error: Failed to load libsecp256k1.
```

I've confirmed the file has +x perms (but I gave it 777 because I was getting annoyed)

```
sorry@ubuntu:~/Electrum-4.0.4$ file /home/sorry/Electrum-4.0.4/electrum/libsecp256k1.so.0
/home/sorry/Electrum-4.0.4/electrum/libsecp256k1.so.0: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=a8de93eeef117c56571722e639dae19e8b9f7c7f, with debug_info, not stripped
```

**Comment by ValdikSS** [comment]
My guess is that 'no such file or directory' tells you that another dependent shared library could not be found.
Run: `ldd ./libsecp256k1.so.0`

**Comment by SomberNight** [comment]
no point keeping this open
