### ISSUE TITLE
Multisig wallet doesn't require co-signer if later submits same transaction as former initiated it.

### ISSUE THREAD

**Issue by jay25dec** [spesmilo/electrum#6673]
1. Configure multi-sig wallet with 2 co-signers requiring 2 signatures.
2. Deposit 0.16mBTC into newly created mutli-sig wallet.
3. One wallet is running on Desktop (v 3.3.8) and another one on mobile device(v 4.0.3).
4. Send transaction of 0.16mBTC from desktop wallet. This will be partially signed transaction. (Details in the attached document).
5. Instead of signing above transaction (in Step 4), same transaction (same amount, same recipient address) was initiated from mobile wallet. This transaction didn't require co-signer and it was sent for confirmation directly onto Blockchain. (Transaction details are available in attached document).

Should transaction in Step 5 require co-signer?

[Multisig Transaction.docx](https://github.com/spesmilo/electrum/files/5423172/Multisig.Transaction.docx)

**Comment by Transisto** [comment]
https://www.virustotal.com/gui/file-analysis/ZDk5NDVhYTRlZDg4Nzc5YjFkZjMyNDY3YmI5NWU4YjM6MTYwMzM5NzU5MQ==/detection

From DOCX

![image](https://user-images.githubusercontent.com/388716/96925074-9b134480-1481-11eb-9ef6-822d3826e9de.png)

**Comment by Transisto** [comment]
They're not the same transaction, they're one byte size difference and sending different amounts  fees.

**Comment by Transisto** [comment]
Possibly that 
![image](https://user-images.githubusercontent.com/388716/96925448-2f7da700-1482-11eb-8ac8-363fbdf35822.png)

just mean "would be position" since no node would include a partially signed transaction.

**Comment by jay25dec** [comment]
If its different transaction than how come last transaction didn't require co-signer's signature? It straightaway went out just like a standard wallet without need for co-signer.

**Comment by SomberNight** [comment]
How did you setup the wallet on Android exactly? Did you enter two seeds on the phone when creating the wallet?

**Comment by jay25dec** [comment]
Yes one for my own wallet and it asks for co-signer's seed phrase and I entered that.

**Comment by SomberNight** [comment]
but then the wallet file on the phone knows two secrets, out of two required, and so can (and will) sign for both cosigners.

For a 2of2 wallet you would instead want:
- machine1 has wallet file1 with: seed1 and master_public_key2
- machine2 has wallet file2 with: master_public_key1 and seed2
That way, both machines only have one secret

> One wallet is running on Desktop (v 3.3.8) and another one on mobile device(v 4.0.3).

Also note that 4.0.0 contains breaking changes in the partial transaction format and so you will need to upgrade Electrum on your desktop.
