### ISSUE TITLE
unit tests are failing: "AssertionError: file was created too soon"

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6676]
Some unit tests are failing since https://github.com/spesmilo/electrum/pull/6639: https://travis-ci.org/github/spesmilo/electrum/jobs/738180975
It's related to calling `init_lightning` from `Deterministic_Wallet.__init__`

_Originally posted by @SomberNight in https://github.com/spesmilo/electrum/pull/6639#issuecomment-714863022_

It might be as simple as removing this line:
https://github.com/spesmilo/electrum/blob/fcccb99a3b3f5dbefd53da02acfa578ed1c3fe08/electrum/wallet.py#L333
(but this needs some thought)

**Comment by ecdsa** [comment]
ack, I think that line can be removed
