### ISSUE TITLE
Lost my old btc wallet

### ISSUE THREAD

**Issue by Sneak71** [spesmilo/electrum#6679]
Hello. I would like to get some help please. I've lost my computer password few month ago and i've totally forget to save my wallet.dat sadly but i've saved my btc address and i've cypher it "chiffrage in french". I still have both codes... My address + the key but i don't know how to recover my funds. If someone can help me to resolve this issue please. Thank you very much by advance.

**Comment by SomberNight** [comment]
Do you have your seed words? You can just restore from that.

**Comment by Sneak71** [comment]
Is the seed words looking like that 13KChDcmYEfyAE9W3SYf3ctCXDSUsvMDKo   ???
I get that when i've cypher my btc wallet on bitcoicore 64bits if i remember well... I still have also my btc address but nothing else sadly :-(((
It wasn't a big loss but i don't like to loose my ca$h lol!

**Comment by SomberNight** [comment]
> Is the seed words looking like that 13KChDcmYEfyAE9W3SYf3ctCXDSUsvMDKo ???

No, that is a bitcoin address. Alphanumeric strings that start with "1", "3", "bc1" and are about 30-60 characters long are bitcoin addresses.

Private keys (WIF) looks similar but start with "5", "K", "L".

Seed words are a bunch of (12-24) natural language (usually English) words. They are given by Electrum when creating a "standard" wallet.

**Comment by Sneak71** [comment]
It was the code i get while cyphering my btc adress starting by 1442Sc4xm54YGX......
Anyways... :'(

**Comment by SomberNight** [comment]
If you only have bitcoin addresses, as those are public information available to anyone, your coins cannot be recovered. :/
