### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by Hila64** [spesmilo/electrum#6680]
Since a few days, I can no longer send payments, it automatically puts "Unconfirmed". When I increase the fees, it puts them in the form of other payments, which means that I no longer have enough money for anything. As a result, none of my payments can be made and I end up with payments without being able to delete them. So I am forced to add funds just to allow these bugs to be sent as payments.. I know I can’t cancel a payment. I’ve never had a problem before and now I have a problem. How do I do that?
![Electrum](https://user-images.githubusercontent.com/73349863/97014187-4d164380-154a-11eb-9d99-69357a90ef74.png)

**Comment by celtilander** [comment]
I have the same problem. I cannot send payments, all unconfirmed.
Wallet 4.0.4
Ubuntu 20.04
Installed with pip

**Comment by SomberNight** [comment]
See https://bitcoinelectrum.com/frequently-asked-questions/#what-does-replaceable-unconfirmed-unconfirmed-parent-low-fee-or-not-verified-mean-in-the-transaction-history

The mempool has a lot of high feerate transactions atm, so you also need to pay high fees if you want fast confirmations.

**Comment by Hila64** [comment]
Ok thank you. I pay with much more fees but it's boring :)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
