### ISSUE TITLE
Electrum fails with high-volume addresses, making my funds unspendable

### ISSUE THREAD

**Issue by CodeForcer** [spesmilo/electrum#6681]
I have a number of addresses with a large transaction history, for example `12o8XbGRjszE8YhLkMtV8Mb5aVA2MJDn9s`

Electrum refuses to load keys for my addresses into the wallet, failing with a `history too large` message.

Some of my addresses have significant stuck funds, which I seem unable to retrieve using my Electrum wallet.

What can I do to resolve this and recover my funds? Electrum is the only wallet I trust, I don't want to look for another wallet if possible.

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/4315

In particular, see https://github.com/spesmilo/electrum/issues/4315#issuecomment-683751285

In case you don't run your own server, try `fortress.qtornado.com:443:s`, it has a somewhat higher limit than default.

However, this is just a temporary workaround so that your existing coins are not stuck: I suggest you start giving out a new address from now on for new incoming txns. The current protocol is very inefficient for heavily reused addresses, to there is a max tx limit per address that is enforced as a DDOS-protection for servers. The default limit is around 10k txns for a given address btw.

**Comment by CodeForcer** [comment]
Thank you, I edited the `MAX_SEND` on my ElectrumX and then `network_max_incoming_msg_size` and it worked.

**Comment by SomberNight** [comment]
May I ask why you reuse addresses so many times? Is this a static donation address on a webpage?

**Comment by CodeForcer** [comment]
It's a hot address for processing payments, which receives funds from a cold wallet. Our cold computer only allows administration staff to sign a transaction within certain sizes and times to specified hot wallet addresses, and not anywhere else.

Also, I wanted to keep the setup as simple as possible, ie defending a singular private key, with a seperate server monitoring the address for anything suspicious.

However, we're actually in the process of deprecating our hot wallets altogether and moving all customers to non-custodial browser generated wallets with unique mnemonics.

The Electrum codebase has been really inspirational in demonstrating how to crawl XPUBs and then synchronise addresses by subscribing the script hashes with ElectrumX.

If you're interested, I actually wrote a walkthrough of our Bitcoin trading process demonstrated entirely with Electrum in Python:
https://github.com/LocalCoinSwap/bitcoin-trading-scripts

**Comment by SomberNight** [comment]
> It's a hot address for processing payments, which receives funds from a cold wallet. Our cold computer only allows administration staff to sign a transaction within certain sizes and times to specified hot wallet addresses, and not anywhere else.

I see.

> If you're interested, I actually wrote a walkthrough of our Bitcoin trading process demonstrated entirely with Electrum in Python

Very cool! Thanks for showing it.

Some of the stuff you are doing in that example is a bit low level; I think there are easier ways of doing it :)
For example, for [creating the witness](https://github.com/LocalCoinSwap/bitcoin-trading-scripts/blob/60cadf32c160b4700e6038c2bf1ba57aa1b1c1c1/CodeDemonstration.py#L203-L215), you could just do
`construct_witness([Signature, PubKey, JohnSecret, TradeInstruction, Script])`
Also, I've just added an analogous method, `construct_script` in https://github.com/spesmilo/electrum/pull/6685.

See an example for constructing a tx that spends an OP_CLTV input in the unit tests:
https://github.com/spesmilo/electrum/blob/8e9d6a4c913df9759fc54f0829d8569f223b35aa/electrum/tests/test_transaction.py#L885
