### ISSUE TITLE
Weird error while executing 'python3 -m pip install --user .[gui,crypto]'

### ISSUE THREAD

**Issue by glestwid** [spesmilo/electrum#6682]
Tried to do installation per the instruction at the site but got a weird error:

[electrum - weird error.txt](https://github.com/spesmilo/electrum/files/5431532/electrum.-.weird.error.txt)
  ERROR: Failed building wheel for sip
  Failed to build sip
  ERROR: Could not build wheels for sip which use PEP 517 and cannot be installed directly

What doe it want from me still beyond my understanding. Any ideas how to resolve the issue?

**Comment by SomberNight** [comment]
Is this on a 32 bit x86 architecture?
Which distribution?

Maybe try installing PyQt5 from apt, instead of PyPI using pip. So e.g.:
```
 sudo apt-get install python3-pyqt5 libsecp256k1-0 python3-cryptography 
python3 -m pip install --user .
```
