### ISSUE TITLE
Insufficient funds? 

### ISSUE THREAD

**Issue by aradour** [spesmilo/electrum#6683]
I tried to send a payment through my wallet, I Just deposit 31 euros and it says insufficient funds? I wanted to send 30, i dont  think the fee is this high to not let me use my funds? Even when I put " max" It doesn't let me see, it only says " insufficient funds" When the deposit is already done, I have no idea what to do!
![Immagine 2020-10-24 015451](https://user-images.githubusercontent.com/23318998/97062968-888e2d80-159d-11eb-98b8-c4b71ea1cd7f.png)

I already set up new wallet 2FA, so I dont think I caught another malware!

**Comment by aradour** [comment]
The thing is that when I open the request tab, it shows red on my address?

**Comment by aradour** [comment]
![Immagine 2020-10-24 020431](https://user-images.githubusercontent.com/23318998/97063257-e2dbbe00-159e-11eb-9f6b-3ea2d99e80d7.png)


Why like this?

**Comment by aradour** [comment]
why I can spend only 15 euros and not 30? thats shocking me!

**Comment by SomberNight** [comment]
> The thing is that when I open the request tab, it shows red on my address?

That just means that address has already been used -- and so you should not use that address again to receive, mainly for privacy reasons. (see tooltip on mouseover)

> why I can spend only 15 euros and not 30? thats shocking me!

Not sure. Probably mining fees. Maybe show a screenshot of the tx preview (click Pay > Advanced).
What is the tx size in bytes?

Btw, from the screenshot I see it's a 2fa wallet. If it is your first outgoing tx then there is also a prepayment of the 2fa for the next 20 or 100 txs. see https://api.trustedcoin.com/#/electrum-help

**Comment by aradour** [comment]
> > The thing is that when I open the request tab, it shows red on my address?
> 
> That just means that address has already been used -- and so you should not use that address again to receive, mainly for privacy reasons. (see tooltip on mouseover)
> 
> > why I can spend only 15 euros and not 30? thats shocking me!
> 
> Not sure. Probably mining fees. Maybe show a screenshot of the tx preview (click Pay > Advanced).
> What is the tx size in bytes?
> 
> Btw, from the screenshot I see it's a 2fa wallet. If it is your first outgoing tx then there is also a prepayment of the 2fa for the next 20 or 100 txs. see https://api.trustedcoin.com/#/electrum-help

so this means I paid for the next 20 payments or 100? and Need to deposit ? But if I paid why there's still 31 euros on my balance?

**Comment by aradour** [comment]
> > The thing is that when I open the request tab, it shows red on my address?
> 
> That just means that address has already been used -- and so you should not use that address again to receive, mainly for privacy reasons. (see tooltip on mouseover)
> 
> > why I can spend only 15 euros and not 30? thats shocking me!
> 
> Not sure. Probably mining fees. Maybe show a screenshot of the tx preview (click Pay > Advanced).
> What is the tx size in bytes?
> 
> Btw, from the screenshot I see it's a 2fa wallet. If it is your first outgoing tx then there is also a prepayment of the 2fa for the next 20 or 100 txs. see https://api.trustedcoin.com/#/electrum-help

How do I click on Pay - Advanced? I Fear that if I click pay i'll send to the address 15 euros and i'll need to send 30. So if I Click Pay is it still like wanting me to confirm the action?

**Comment by aradour** [comment]
also when I place my address in trusted wallet shows me there's no address linked there, so I mean I did connect it but how do i Find out which ?

**Comment by aradour** [comment]
i have 60 euros already and I can send only 28?

**Comment by aradour** [comment]
thats really crazy..
