### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by EGR789** [spesmilo/electrum#6686]
Hello, why electrum cant connect?

[IMG_8300.ZIP](https://github.com/spesmilo/electrum/files/5434686/IMG_8300.ZIP)

**Comment by SomberNight** [comment]
Could you please upload debug logs? [See here](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) how to get them.

**Comment by EGR789** [comment]
[electrum_log_20201026T052842Z_9156.zip](https://github.com/spesmilo/electrum/files/5437000/electrum_log_20201026T052842Z_9156.zip)

**Comment by SomberNight** [comment]
Thank you for the report and the log. I've pushed a fix so this should self-resolve with the next release.

For now, you can workaround this by going to the `Console` tab in the GUI, and running:
```
wallet.clear_history()
```
