### ISSUE TITLE
Missing sqlite3 requirement

### ISSUE THREAD

**Issue by ehaupt** [spesmilo/electrum#6690]
sqlite3 is imported:

https://github.com/spesmilo/electrum/blob/5481fd8af692b7e24b4e904b115ea6a1f80e6a0b/electrum/sql_db.py#L6

but it's not listed in https://github.com/spesmilo/electrum/tree/master/contrib/requirements.

Reference: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250594

**Comment by ecdsa** [comment]
sqlite3 is part of python.
the bug you linked to suggests that a library is missing##
see 
https://lists.freebsd.org/pipermail/freebsd-questions/2016-June/272241.html

**Comment by ehaupt** [comment]
> sqlite3 is part of python.

Indeed.

I've just realized that FreeBSD disables sqlite3 in its default version:

https://github.com/freebsd/freebsd-ports/blob/cece86014b7b1bc44f324d406dc207b478ac1d7c/lang/python37/Makefile#L32

I'll make sure the FreeBSD port pulls it in as a dependency and I'll close the issue.
