### ISSUE TITLE
Problem with send bitcoin to other address, order in warning(yellow) and unconfirmed

### ISSUE THREAD

**Issue by matthewwsAlfa** [spesmilo/electrum#6699]
look at my problem is that since yesterday I received approximately 400 euros . Then I needed to send them to another direction, which the application does not allow me to observe in the photo that this is "unconfirmed" and the other one with a yellow triangle proves to other directions and the same mistake, after receiving this money yesterday, I was not allowed to receive more money to other directions in electrrum, I tried to raise at high commission rate so that they were transferred immediately but I still have more than a day and I can't do anything with my problem, and I urgently need to use that money 
![IMG_1933](https://user-images.githubusercontent.com/72236898/97513758-de7f1e80-196b-11eb-90aa-dfffe5fc8ecd.jpeg)
![IMG_1934](https://user-images.githubusercontent.com/72236898/97513782-eccd3a80-196b-11eb-9fe9-94c24c3269e2.jpg)
![IMG_1935](https://user-images.githubusercontent.com/72236898/97513807-f9519300-196b-11eb-99f1-141c0f738be6.jpg)
![IMG_1936](https://user-images.githubusercontent.com/72236898/97513833-053d5500-196c-11eb-8c74-9947cf029f6d.jpg)
![IMG_1937](https://user-images.githubusercontent.com/72236898/97513861-11291700-196c-11eb-93dc-44118ef63251.jpg)

**Comment by SomberNight** [comment]
There is a huge backlog of transactions in the mempool at the moment.
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

**Comment by matthewwsAlfa** [comment]
thanks! the problem was solutioned!, only up the FD , thanks I think the
problem can be a big problem :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
