### ISSUE TITLE
I try pay a other btc address and after this I cancel this with FD double-spend, but this not cancell

### ISSUE THREAD

**Issue by matthewwsAlfa** [spesmilo/electrum#6701]
hello I try pay a other address btx but after this don't move  I pay a high FC and not was send so I cancell this with double-spend for cancel this transaction and this not function, I read the manual and don't have a answer there, so if someone have a answer thanks because the transactiont not cancell now

**Comment by ysangkok** [comment]
Is FC a force close? I am not sure it makes sense to double-spend a force-close transaction since your Lightning channel counterparty has to agree on the fee level, and you'd only do a force close if you can't reach the counterparty.

In the title you wrote FD, what does that mean?
