### ISSUE TITLE
Detect Existing Accounts

### ISSUE THREAD

**Issue by kipilk0** [spesmilo/electrum#6702]
Electrum doesn`t found the BRD wallet path m/0'

**Comment by SomberNight** [comment]
I assume you are talking about the BIP39 automatic scan feature.

Could you please elaborate? What is the script type of the addresses? Did you manage to restore the wallet after manually specifying the derivation path?

**Comment by kipilk0** [comment]
> Could you please elaborate? What is the script type of the addresses? Did you manage to restore the wallet after manually specifying the derivation path?

bech32 addresses
yes, i enter to my wallet using m/0' path

**Comment by SomberNight** [comment]
Well that combination is among those tried:
https://github.com/spesmilo/electrum/blob/70b03cb92007743ffbe02399284075aa43a77b08/electrum/bip39_wallet_formats.json#L32-L37

**Comment by ecdsa** [comment]
closing, no answer from user
