### ISSUE TITLE
Feature request: allow editing outgoing unpaid invoices

### ISSUE THREAD

**Issue by Raulo** [spesmilo/electrum#6704]
Imagine you have a large pay to many transaction. You click pay and realize that you have the amounts wrong. You have this in the outgoing payments tab but you can only change the fee, everything else is fixed. You have to start from the scratch. It would be nice if one can edit the invoice.

Alternatively, since it would be rarely needed for old invoices, do not clear the send tab when clicking the Pay button. This way if you make an error, you can close the pay tab and make some edits. Clear the send only after completed pay.

**Comment by ecdsa** [comment]
done in 56579c282ed72a6c123fab82a015bdac5fb400c1
