### ISSUE TITLE
clicking bip21 URI in browser replaces "Pay to" field in Send tab. request: it could add a new output instead.

### ISSUE THREAD

**Issue by Simkas45** [spesmilo/electrum#6707]
Do you know what a URI is?
this is a link from the browser by clicking which a transaction opens in the electrum window, only if you click on a similar link it replaces the first address, and I need her to add a second address for payment, so I ask how to do this?

Examples:
bitcoin:12zxtwHwdsefCniABcyL4FXgtiJsC39B16?amount=0.1

I need that by clicking these links, each address is added to the multi-send field, and it replaces the previous one for me, how to evaporate?
Please tell me how to correctly create a URI so that the wallet opens with the addition of a second payment address, and does not replace the first one.
How to make a multitransaction to several addresses?

**Comment by SomberNight** [comment]
I don't think [BIP21 URIs](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) allow specifying multiple outputs.

**Comment by SomberNight** [comment]
As a user, what you could do is, click on first URI, in Electrum `Send` tab, click `Save`. Then click on second URI, click `Save`. Then at the bottom of the `Send` tab, in the `Outgoing payments` list, multi-select both invoices, and click `Batch pay invoices`.

**Comment by SomberNight** [comment]
Why do you want to create a URI that pays to multiple outputs btw? What is the use case?

**Comment by Simkas45** [comment]
When I wire a payout on my pool, everything is arranged through the URI, and therefore I need it as in the bitcoin core
[my pool](https://sha256.mnshare.info)

**Comment by SomberNight** [comment]
> therefore I need it as in the bitcoin core

Please explain how it works in Bitcoin Core then.
I am not familiar with their wallet (I only use the node).
Do they support URIs with multiple addresses? How do those URIs look? Please give an example.

**Comment by SomberNight** [comment]
I guess I've found your [thread on bitcointalk](https://bitcointalk.org/index.php?topic=5285926).
So what you are asking for is this:
> this is a link from the browser by clicking which a transaction opens in the electrum window, only if you click on a similar link it replaces the first address, and I need her to add a second address for payment, so I ask how to do this?

Currently if you click multiple URIs in e.g. a browser, the latest one always replaces what's currently in the Send tab;
but you would like the behaviour to add a new output instead.

**Comment by Simkas45** [comment]
When I click on the links:
bitcoin:135QN3aLnGJvaeVFQzN6DAWCEVYZzrJBLS?amount=0.1&label=testuri1
bitcoin:12zxtwHwdsefCniABcyL4FXgtiJsC39B16?amount=0.1&label=testuri2
bitcoin:148NzbyVaWDtUPYoLUk4MVU1h5Y9svY43C?amount=0.1&label=testuri3
Each link one after another is added to the submission form, recorded in one transaction
![image](https://user-images.githubusercontent.com/43626253/98087399-0ea94e80-1e91-11eb-98f1-fc9769baae0e.png)

**Comment by ecdsa** [comment]
I think the current process (click "save", then pay multiple invoices at once) is better, because it makes things explicit.

In most cases, users do NOT want clicking on a link (or scanning a new qr code) to add an extra output to an existing payment (for example, it would be a footgun if they clicked twice on the same link)
