### ISSUE TITLE
Electrum 3.3.4 loses connection after upgrading to Fedora 32 

### ISSUE THREAD

**Issue by donob4n** [spesmilo/electrum#6716]
Hi,

I recently upgraded from Fedora 31 to 32 since EOL is coming soon. Testing a little I noticed that it was losing connection after a short while. I compared with the F31 version and I think they are identically except first uses Python 3.7 and later 3.8.

I think that the problem is here:
https://github.com/spesmilo/electrum/blob/87c596fa1d685b9365c26b9dfabe9c566f806ea0/electrum/exchange_rate.py#L483

Because in F32 I'm getting this exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/electrum/exchange_rate.py", line 482, in run
    await asyncio.wait_for(self._trigger.wait(), 150)
  File "/usr/lib64/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutErrror
```
It seems that the raised exception has changed. I tested catching all exceptions and it does not lose connection.

**Comment by SomberNight** [comment]
Yes, indeed python 3.8 broke that. Newer versions of Electrum are tested with Python 3.8, you should use those.

E.g. these commits changed the related exception-handling:
https://github.com/spesmilo/electrum/commit/4b3a285871161916708f31b0d43c25c13a1b5d7d
https://github.com/spesmilo/electrum/commit/308517d473d18fdc5a377e7296e0e6ab3f6c92b8

Seems to me, Fedora itself [packages newer Electrum](https://koji.fedoraproject.org/koji/packageinfo?packageID=23316). Still, you can always run from source (git clone, or use official tar.gz), or use the AppImage we distribute (one-click executable).

**Comment by donob4n** [comment]
Wops sorry, thanks.

> Seems to me, Fedora itself [packages newer Electrum](https://koji.fedoraproject.org/koji/packageinfo?packageID=23316). Still, you can always run from source (git clone, or use official tar.gz), or use the AppImage we distribute (one-click executable).

I think that I'm running the last fc32 version, I will ping this to the fedora maintainer.
