### ISSUE TITLE
Transaction could not be broadcast due to dust outputs

### ISSUE THREAD

**Issue by fucktheworld7** [spesmilo/electrum#6717]
This happends when im trying to send btx to other wallets but my own i could send to but i cant send to others only get this and yes i haved tryed to do what elektrum telling me upgrade and change server nothing haved worked yet plz hellp how to do to fix it.

Do not post issues aThe server returned an error when broadcasting the transaction.
Överväg att ansluta till en annan server, eller att uppdatera Electrum.

Transaction could not be broadcast due to dust outputs.bout non-bitcoin versions of Electrum. -->

Feel free to contact thanks for the help and cheers!

**Comment by SomberNight** [comment]
see https://bitcoinelectrum.com/frequently-asked-questions/#why-am-i-getting-the-error-message-dust-outputs

> This means you are trying to send very small amounts of bitcoin i.e. less than 5140 satoshis worth. In practice it usually means you are confusing bitcoin (btc) with millibitcoin (mbtc) which is 1/1000th of a bitcoin. So please change the unit of account in electrum to btc and try again. To change the unit of account go to tools > preferences > general tab > base unit option and set it to btc. Then try to send money again keeping in mind that you are now dealing with bitcoin and not millibitcoin.

**Comment by fucktheworld7** [comment]
Thank u alot its worked! You the best!

How long to it confirmed after sending?

Thanks and cheers!
