### ISSUE TITLE
"Not enough funds" error appears to me at any amount of btc

### ISSUE THREAD

**Issue by shifaka** [spesmilo/electrum#6728]
I can`t send any amount of BTC using electrum 4.04. Always same error: Not enough funds, but I am sure thats more then enough. I even have same error when pressing "max" button without entering any other data.

**Comment by SomberNight** [comment]
Assuming you are using the desktop (Qt) GUI,

- Go to statusbar>`Wallet`>`Information`. What is `Wallet type`?
- What is your approx balance? (bottom left corner) (if more than e.g. 0.1 BTC, just say that)
- In `Coins` tab, (enable from statusbar>`View`) approx how many lines/entries are there?

**Comment by shifaka** [comment]
1. wallet type: standart
2. more then 0.1 btc
3. 6 lines in coins tab

**Comment by shifaka** [comment]
I am sorry, that was my fault. I ve frozen the coins on coins tab and forgot about that option because haven`t used electrum for a long time. Since I unfreeze coins error dissapeared. Sorry for concern about it.
