### ISSUE TITLE
Mac Big Sur - Won't Open

### ISSUE THREAD

**Issue by shaggy35** [spesmilo/electrum#6729]
Can't get electrum to open on new mac OSX Big Sur. Just hangs. Have tried re-installing, still a no go.

**Comment by monosux** [comment]
Same here

**Comment by brewsterkahle** [comment]
same.   icon appears in launch bar, but the main window does not come up on 4.03.   installed 4.04, same thing.

**Comment by SomberNight** [comment]
duplicate of https://github.com/spesmilo/electrum/issues/6461
please search existing issues before opening a new one
