### ISSUE TITLE
Electrum not working with trezor hardware

### ISSUE THREAD

**Issue by Ramesh5688** [spesmilo/electrum#6742]
Hi Team,

I am using electrum wallet to connect trezor I am getting this error: 

no hardware device detected
To trigger a rescan, press 'Next'

On linuz, you might have to add a new permission to your udev rules.

Debug message
bitbox02: (error getting device infos)
missing libraries for bitbox2.
make sure you install it with python3
coldcard: (error getting device infos)
.............................
library version for 'trezor' is incompatiable
installed: unknown, Needed: 0.12.0 <= x <0.13
make sure you install it with python3

Any help is appreciated.

**Comment by SomberNight** [comment]
>  library version for 'trezor' is incompatiable
installed: unknown, Needed: 0.12.0 <= x <0.13

How are you running Electrum?
The trezorlib you have is too old. How it should be updated depends on how you are running Electrum.

**Comment by Ramesh5688** [comment]
I followed these steps:

git clone https://github.com/spesmilo/electrum.git
cd electrum
brew install automake libtool pyqt
pip3 install cryptography
./contrib/make_libsecp256k1.sh
pip3 install --user -e .
./run_electrum

**Comment by SomberNight** [comment]
try `pip3 install --upgrade trezor`

**Comment by Ramesh5688** [comment]
Did that, still not working, same error showing up.

**Comment by Ramesh5688** [comment]
thanks alot for the response.

**Comment by SomberNight** [comment]
Run this in terminal:
```
python3 -c "import trezorlib; print(trezorlib.__version__)"
```
What does that print?

**Comment by Ramesh5688** [comment]
it prints : 0.12.2

**Comment by Ramesh5688** [comment]
I am running electrum on macOS Big Sur

**Comment by SomberNight** [comment]
Using another wallet file, e.g. for a software wallet seed, in the main window, go to the "Console" tab, and run
```
>>> import trezorlib
>>> trezorlib.__version__
'0.12.2'
```

Does it print `0.12.2` for you too?

**Comment by Ramesh5688** [comment]
not sure where do run this command?

**Comment by SomberNight** [comment]
Once you already have a wallet open in Electrum, there is a "main window" with tabs (e.g. History, Send, Receive). One of the tabs (if you go to `View`>`Show Console`) is the Console tab. Run it there.

If needed, you can create a throwaway/temporary wallet (just to get to this window) and delete it after.

**Comment by Ramesh5688** [comment]
Thanks, Just created a dummy wallet, yes it print same '0.12.2'

**Comment by Ramesh5688** [comment]
I downloaded newer version of electrum, it works great, thanks for helping me out, appreciated.
