### ISSUE TITLE
Ledger Bitcoin 1.5.1 app causes Ledger not being detected

### ISSUE THREAD

**Issue by kodxana** [spesmilo/electrum#6745]
After updating app on device to version 1.5.1 Electrum not recognize Ledger Nano X. Was working fine before updating of Ledger.
![image](https://user-images.githubusercontent.com/16674412/99578070-85d7fa00-29dc-11eb-8b0a-39697ecd1b3c.png)

Electrum: 4.0.4
Bitcoin App: 1.5.1
Ledger firmware: 1.2.4-4

**Comment by SomberNight** [comment]
Right, thanks for the report.
It's already fixed on master (https://github.com/spesmilo/electrum/commit/b78cbcffd11364ed4651af1886d507b36bc1b013).

We were about to do a release anyway luckily, so there will soon be one with the fix.
