### ISSUE TITLE
Cannot restore wallet on latest version - weird derivation path

### ISSUE THREAD

**Issue by viperperidot** [spesmilo/electrum#6749]
I am attempting to restore an Electrum created wallet using the latest release of Electrum. I have entered my seed phrase and passphrase correctly however the correct wallet with it's associated XPUB does not restore. I noticed when I open the wallet information that it says the derivation path is m/0' but this cannot be correct can it? As far as I know that is an incomplete derivation path following Electrums formats. Is it possible there is an issue restoring wallets using the latest version? I know I am entering the seed phrase and passphrase correctly and the derivation path looks strange. Any help would be appreciated.
Thanks

**Comment by viperperidot** [comment]
Another thing to note which is strange is that it appears the passphrase is not case sensitive. If I restore a wallet using the same seed phrase and same passphrase but with some capital letters, I get the same XPUB. Aren't the passphrases supposed to be case sensitive?

**Comment by viperperidot** [comment]
Edit: I was able to restore after several more attempts, but I guess my question still remains about the derivation path displayed in the wallet information and the case sensitive of the passphrase.

**Comment by SomberNight** [comment]
Yes, the passphrase is not case sensitive.
The derivation path for an electrum seed is not something typical users need to be concerned with; it is only listed in the wallet>info dialog for completeness (and to make it similar to other wallet types).
