### ISSUE TITLE
Electrum electrum-4.0.5-x86_64.AppImage Application Version Internally is 4.0.4

### ISSUE THREAD

**Issue by sotarules** [spesmilo/electrum#6756]
I've just installed 4.0.5 on Ubuntu and when I launch the application the top bar says it is version 4.0.4.  Not sure how to confirm whether this is a matter of my own set up, just a heads up.

**Comment by ecdsa** [comment]
maybe an old electrum process, started before you upgraded?

**Comment by sotarules** [comment]
Bingo - after rebooting my machine I'm seeing 4.0.5 - sorry for this false alarm 👍
