### ISSUE TITLE
Handle new Bitcoin Core 0.21 error messages

### ISSUE THREAD

**Issue by ysangkok** [spesmilo/electrum#6760]
Bitcoin Core 0.21 will use a [different error message](https://github.com/bitcoin/bitcoin/commit/8f1290c60159a3171c27250bc95687548c5c1b84) when "absurdly-high-fee" was previously used, which is [currently referenced in network.py](https://github.com/spesmilo/electrum/blob/0b183444b46e6bf26622e8b41368004a73357dee/electrum/network.py#L963). If the new error message is not handled, I think the user will see "unknown error" instead of a helpful error message.

**Comment by ecdsa** [comment]
thanks!
