### ISSUE TITLE
bug found cancel transaction from Electrum

### ISSUE THREAD

**Issue by FMFigueroa** [spesmilo/electrum#6763]
Hola, encontré un error para la opción cancelar transacción cuando está activada la vista previa avanzada en las preferencias del usuario, he emparejado Electrum con mi Gold Wallet en modo 2FA. Cuando quiero cancelar la transacción e ingreso todos los datos como la dirección y la frase semilla, entonces no abre la ventana que muestra el código QR para confirmar con el autenticador que está configurado en mi celular.
Por favor, míralo..!
Saludos

**Comment by ecdsa** [comment]
cancel tx works with 2FA (trustedcoin). 
I don't understand how you can pair electrum with a Bitcoin Gold wallet.
