### ISSUE TITLE
Unable to connect to electrs server

### ISSUE THREAD

**Issue by florianfink** [spesmilo/electrum#6767]
Electrum 4.0.5 won't connect to my personal electrs server v0.8.5. It seems to be connecting/disconnecting in a continous loop. Works totally normal using Electrum 4.0.4.

Not sure if this is a electrs problem actually.

Electrs log:

> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.859+01:00 - TRACE - [127.0.0.1:40936] joining ThreadId(7880)
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.859+01:00 - INFO - [127.0.0.1:40936] connected peer
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.902+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"server.version\", \"id\": 0, \"params\": [\"electrum/4.0.5\", \"1.4\"]}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.940+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.headers.subscribe\", \"id\": 1}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.942+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 2, \"params\": [25]}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.943+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 3, \"params\": [10]}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.945+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 4, \"params\": [5]}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.945+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 5, \"params\": [2]}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.979+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"server.banner\", \"id\": 6}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.981+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"server.donation_address\", \"id\": 7}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.982+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"server.peers.subscribe\", \"id\": 8}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.982+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.relayfee\", \"id\": 9}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.984+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"mempool.get_fee_histogram\", \"id\": 10}\n")
> Nov 23 15:08:11 server electrs[1350]: 2020-11-23T15:08:11.986+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.subscribe\", \"id\": 11, \"params\": [\"redacted_for_privacy\"]}\n")
> Nov 23 15:08:12 server electrs[1350]: 2020-11-23T15:08:12.042+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.subscribe\", \"id\": 12, \"params\": [\"redacted_for_privacy\"]}\n")
> Nov 23 15:08:12 server electrs[1350]: 2020-11-23T15:08:12.139+01:00 - ERROR - [127.0.0.1:40936] connection handling failed: Error: failed to send {"id":12,"jsonrpc":"2.0","result":null}
> Nov 23 15:08:12 server electrs[1350]: Caused by: Broken pipe (os error 32)
> Nov 23 15:08:12 server electrs[1350]: 2020-11-23T15:08:12.139+01:00 - DEBUG - [127.0.0.1:40936] shutting down connection
> Nov 23 15:08:13 server electrs[1350]: 2020-11-23T15:08:13.533+01:00 - TRACE - [127.0.0.1:40938] spawned ThreadId(7884)

**Comment by SomberNight** [comment]
what is in the [client's log](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?

**Comment by florianfink** [comment]
There you go. This error ("fees must be in decreasing order") seems to be happening with a lot of servers (I guess electrs isn't returning the fees in decreasing order?)

> 20201123T145935.613737Z |     INFO | network | couldn't launch iface electrum.villocq.com:50002:s -- CancelledError()
> 20201123T145935.713533Z |    ERROR | interface.[192.168.178.220:50002] | Exception in wrapper_func: RequestCorrupted('fees must be in decreasing order')
> Traceback (most recent call last):
>   File "electrum/util.py", line 1039, in wrapper
>   File "electrum/interface.py", line 480, in wrapper_func
>   File "electrum/interface.py", line 504, in run
>   File "electrum/interface.py", line 647, in open_session
>   File "aiorpcx/curio.py", line 242, in __aexit__
>   File "aiorpcx/curio.py", line 211, in join
>   File "electrum/network.py", line 452, in _request_server_info
>   File "aiorpcx/curio.py", line 242, in __aexit__
>   File "aiorpcx/curio.py", line 211, in join
>   File "electrum/network.py", line 456, in _request_fee_estimates
>   File "electrum/interface.py", line 1004, in get_fee_histogram

**Comment by florianfink** [comment]
So after further research, this seems to be fixed in electrs already: https://github.com/romanz/electrs/issues/317

Sorry!
