### ISSUE TITLE
Electrum 4.0.5 unable to connect to electrs: fees must be in decreasing order

### ISSUE THREAD

**Issue by Kineticmb** [spesmilo/electrum#6772]
I updated to the latest Wallet on Android on two different phones (Samsung S10 and a Pixel 3)

In the "network" section the tor address was still in place and correct, auto connect on, one server mode on.

The wallet now continuously tries to connect to the remote node but is unable to connect. 
It is on a continuous loop of attempting the connection - Going from "Synchronizing" back to offline, repeat. 

This is the same on both phones since updating to this version and no matter how long I leave it attempting the process, it is not synchronising.

**Comment by primeroz** [comment]
I am experiencing the same problem after upgrading to 4.0.5 , in my case i use electrs and i can see there is an issue on their repo as well, not sure where the issue is ( electrum or electrs ) so cross-linking here https://github.com/romanz/electrs/issues/331

**Comment by primeroz** [comment]
Also , i tested removing TOR and connecting directly to electrs both on TCP and SSL , both are experiencing the same issue with the following error

```
electrs        | 2020-11-24T15:14:16.401+00:00 - ERROR - [192.168.88.230:41406] connection handling failed: Error: failed to send {"id":41,"jsonrpc":"2.0","result":null}
```

@Kineticmb what electrum server are you using ?

**Comment by Kineticmb** [comment]
@primeroz I am using electrs

**Comment by primeroz** [comment]
@Kineticmb ok, i was hoping that maybe you were using a different one so we would know the issue was likely to be on the electrum side :)

I wonder if you want to remove the TOR bit from the subject of the issue ? in my case it happens even without TOR connecting directly to the electrum server 

for reference this is the exception Electrum is reporting when running `./electrum-4.0.5-x86_64.AppImage --oneserver --server 192.168.88.252:50002:s -v=DEBUG`

```
I/n | network | connecting to 192.168.88.252:50002:s as new interface
I/i | interface.[192.168.88.252:50002] | connection established. version: ['electrs 0.8.5', '1.4']
I/i | interface.[192.168.88.252:50002] | set blockchain with height 658475
I/i | interface.[192.168.88.252:50002] | skipping header 658475
I/n | network | switching to 192.168.88.252:50002:s
I/W | lnwatcher.LNWalletWatcher.[test_wallet-LNW] | set_up_to_date: True
I/W | lnwatcher.LNWalletWatcher.[test_wallet-LNW] | set_up_to_date: True
I/n | network | fee_estimates {25: 3899, 10: 45433, 5: 52699, 2: 59132}
E/i | interface.[192.168.88.252:50002] | Exception in wrapper_func: RequestCorrupted('fees must be in decreasing order')
Traceback (most recent call last):
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/electrum/util.py", line 1039, in wrapper
    return await func(*args, **kwargs)
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/electrum/interface.py", line 480, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/electrum/interface.py", line 504, in run
    await self.open_session(ssl_context)
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/electrum/interface.py", line 647, in open_session
    await group.spawn(self.monitor_connection)
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/electrum/network.py", line 452, in _request_server_info
    await group.spawn(self._request_fee_estimates(interface))
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/electrum/network.py", line 456, in _request_fee_estimates
    histogram = await interface.get_fee_histogram()
  File "/tmp/.mount_electr8AgOO5/usr/lib/python3.7/site-packages/electrum/interface.py", line 1004, in get_fee_histogram
    raise RequestCorrupted(f'fees must be in decreasing order')
electrum.interface.RequestCorrupted: fees must be in decreasing order
```

4.0.4 can connect just fine and get the right estimation from electrs 
```
I/n | network | connecting to 192.168.88.252:50002:s as new interface
I/n | network | starting taskgroup.
I/i | interface.[192.168.88.252:50002] | connection established. version: ['electrs 0.8.5', '1.4']
I/i | interface.[192.168.88.252:50002] | set blockchain with height 658475
I/i | interface.[192.168.88.252:50002] | skipping header 658475
I/n | network | switching to 192.168.88.252:50002:s
I/n | network | fee_estimates {25: 2986, 10: 45454, 5: 53276, 2: 59746}
I/n | network | fee_histogram [[102.30208587646484, 100104], [83.89286041259766, 100183], [78.85185241699219, 100175], [76.43678283691406, 102797], [74.69340515136719, 103193], [72.60369873046875, 100314], [71.7562255859375, 101319], [69.7632064819336, 100260], [68.3849868774414, 100137], 
...
...
I | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
```

**Comment by primeroz** [comment]
Commit that introduced this issue https://github.com/spesmilo/electrum/commit/5481fd8af692b7e24b4e904b115ea6a1f80e6a0b

**Comment by Kineticmb** [comment]
Hi @primeroz , Ive changed the title. Fingers crossed they can find the bug and roll out the solution.

**Comment by viperperidot** [comment]
Hi guys, I just wanted to add to this issue that there are several myNode users who are running electrs that have upgraded their Electrum wallets to 4.0.5 that are reporting this issue. Downgrading on desktop is easy to do but harder on users using mobile wallets.

Here are the 2 issues with logs pasted: mynodebtc/mynode#438

mynodebtc/mynode#439

**Comment by Kixunil** [comment]
FYI `electrs` from `master` works.

**Comment by sundaywar** [comment]
Just to chime in that I'm seeing the same issue on Electrum 4.0.5 running on MacOS... impossible to connect to Electrum Server (MyNode). 

I had to downgrade to 4.0.4 to get it going.

**Comment by SomberNight** [comment]
As above, this is a bug in the server.

I have recently been adding multiple checks client-side for server sent responses; all checks for behaviour that were documented in the protocol spec and relied upon by the client but not checked/enforced before. Frankly I added them as sanity checks, not expecting they would break something.

In this specific case, mempool based fee estimates will not behave correctly if this constraint is not held, which it seemingly isn't by electrs.

Sorry for the inconvenience.

**Comment by Kixunil** [comment]
The new version of `electrs` which fixes the issue was released.
