### ISSUE TITLE
No FX rate or connection to Electrum servers

### ISSUE THREAD

**Issue by daniel-waniel** [spesmilo/electrum#6782]
I can still make transactions, but cannot check for updates, nor does any FX rate server work. Can you help?

**Comment by ecdsa** [comment]
please explain what you mean by "check for updates". 
also, is your client synchronized?

**Comment by SomberNight** [comment]
Are you using a proxy? What kind?
Also, please check [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging).

**Comment by ecdsa** [comment]
the user did not provide any useful information
