### ISSUE TITLE
Feature, Subtract fee from amount + RBF, Important for privacy. Offering 1.5m sat. ($350)

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#6783]
![image](https://user-images.githubusercontent.com/388716/100335911-84419f80-2fa3-11eb-8c99-ecd1802ee8a0.png)

Somewhere on this tab could be a "Subtract fees from amount" checkbox.

**Comment by ecdsa** [comment]
@Transisto what do you mean?

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/102684055-56ffa000-41a3-11eb-9a86-c52fa2b9d0b6.png)
BTCPAY

It would be extremely useful for accounting when a customer is asking to increase his transaction priority via RBF and has already paid with cash and left.

Having the option would also increase privacy chain wide by removing the general assumption that the extra fee for RBF is taken from the change.

**Comment by Transisto** [comment]
Sorry I meant 1m sat, bumping it to 1.5m sat (~350USD at of now)

**Comment by SomberNight** [comment]
To be clear, do you mean there could be an option for this in the "bump fee dialog"? So only when increasing the fee of an existing tx? -- as opposed to during initial construction of a tx

**Comment by Transisto** [comment]
I mean it'd be great if fee could be taken from amount when creating the first transaction, like the two wallets above, but for us that can already be calculated easily, What's more useful for us is to make the customer pay after he left but call to request a speed up. 

But yeah, doesn't need to be part of the fee increase dialog too if the wallet just remember where to take the fee when it was first created.

**Comment by SomberNight** [comment]
> BTW Bitcoin core take into account pay to many and will take the fee evenly from all outputs.

What does "evenly" mean?
Is the amount taken away linearly scaled according to the output values,
or are all outputs decreased by the same value?

**Comment by Transisto** [comment]
Good point, it should be based on data weight of the utxo but I think
disregarding the address type is good enough, although I think we should
consider doing the same thing as Bitcoin Core to avoid wallet fingerprints.
`subtractfeefrom'

https://chainquery.com/bitcoin-cli/sendmany

**Comment by SomberNight** [comment]
I think adding this "subtract fee from payment amount" option to the `Send` tab for normal tx creation is overkill. The `Send` tab is already versatile enough that you can achieve the same effect manually.

However, you can not achieve this currently with `bump_fee`. I think we could add such an option to the `bump_fee` dialog.
We could add a checkbox to either the dialog itself, or to `Preferences`, e.g. "decrease payment amounts".
If there is only one non-ismine output, it is clear what it should do.

So then the question is, what to do if there are multiple non-ismine outputs -- so for `Pay to many` / batched payments.
I am afraid that whatever answer we come up with, there will be users who complain that they want something else. So at least we should come up with an answer that we expect would satisfy most users.
(Maybe in the future we could have some complex expert screen that allows manually editing all amounts, but until then...)

**Comment by Transisto** [comment]
I'm not sure what non-isimine means but if it means, of different amount then I'd say only data weight of the output matters.

Transactions should be able to pay for their own weight and when batching someone buying for 50$ pays the same network fee as someone buying for 5000$

**Comment by SomberNight** [comment]
>> the question is, what to do if there are multiple non-ismine outputs -- so for `Pay to many` / batched payments.
>
> I'm not sure what non-isimine means but if it means, of different amount then I'd say only data weight of the output matters.

An address is `ismine` if it belongs to the wallet. A tx input or a tx output is `ismine` if the corresponding address is `ismine`.

So what I meant there is: the question is what to do if there are multiple external/foreign outputs.

**Comment by SomberNight** [comment]
I think a variant of this is now implemented with https://github.com/spesmilo/electrum/pull/7026.
That PR also made it easier to add more "strategies" later, if we can come up with ones that are useful.

Feel free to test and say if it does what you wanted.
If you like it, I can share an address or LN invoice privately for your bounty :P -- it's up to you though; I think it was a useful change either way.
