### ISSUE TITLE
Support trampoline routing

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6788]
Under development, see https://github.com/spesmilo/electrum/commits/trampoline

Note that the spec is not ready yet, only Phoenix currently uses it (with an Eclair node).

One issue with the incomplete spec is that trampoline fees have to be guessed; indeed, Eclair does not return a `node_update`  payload in its error messages, because the Acinq devs have not decided of the format for new gossip messages. Having to guess fees makes it difficult to perform multi-trampoline routing.

I think we should still deploy this now, the user experience is much better than with local routing. In addition, the gossip part of the spec might not make any progress for years if there is no demand for it.

**Comment by TheBlueMatt** [comment]
Given electrum is a desktop app that is capable of fetching the full routing table (its relatively small on desktop, and electrum servers could be used to speed it up greatly), does this make as much sense as on mobile where you regularly need to open from very stale routing knowledge and send a payment quickly? The privacy tradeoffs here may not make it a good candidate for default inclusion.

**Comment by ecdsa** [comment]
Note that Electrum is also a mobile app. But even on desktop, I tend to disagree: the typical usage pattern is not to keep Electrum running all the time, but rather to open the app, pay with it and close it. 

Regarding privacy tradeoffs: The current implementation uses payment paths that include two trampolines when we pay to a legacy recipient, and a single trampoline if we pay to a trampoline recipient.

**Comment by TheBlueMatt** [comment]
> to open the app, pay with it and close it.

Hmm, fair, does it not make sense to leverage electrum servers for quick routing table sync, though? The routing table is relatively small, very small if you trust the server and skip signature fetch/checks, and a diff-based table sync should be trivial-ish. I'm curious if this is an active pain point today - does opening the app and going to send block waiting for the table to sync for some long period for the average user, and how long is that?

> two trampolines when we pay to a legacy recipient, and a single trampoline if we pay to a trampoline recipient.

That's a pretty small privacy buffer (not that a lot of payments don't already have a frighteningly small number of hops).

**Comment by ecdsa** [comment]
> Hmm, fair, does it not make sense to leverage electrum servers for quick routing table sync, though? The routing table is relatively small, very small if you trust the server and skip signature fetch/checks, and a diff-based table sync should be trivial-ish. I'm curious if this is an active pain point today - does opening the app and going to send block waiting for the table to sync for some long period for the average user, and how long is that?

This is something we considered. One concern is that nobody knows how long the database is going to remain small. Also, bandwidth usage could become very large for public Electrum servers. If you decide to run your own private Electrum server, then of course things are different. We are currently considering to move pathfinding (as well as watchtower) to the Electrum server, if the server is private, see #6778

**Comment by TheBlueMatt** [comment]
> nobody knows how long the database is going to remain small

Hmm, this is a fair point, but it still seems that diff-based database updates are easy, requiring only a single initial sync, not to mention the actual contents are rather trivial if you remove signatures, making even mobile graph fetches feasible through millions of nodes.

One of the nice things of trampoline is you can still ship a large part of the graph, but cull nodes that don't have many channels or charge too high fees (or don't support trampoline), and then still require quite a few hops, relying on the server to enforce that you won't get screwed by misbehaving or high-fee nodes by simply removing those nodes from the graph. All this requires a lot more work, but allows you to avoid a lot of the privacy tradeoffs by utilizing the electrum servers to monitor for nodes you don't want to hop through.

**Comment by SomberNight** [comment]
> it still seems that diff-based database updates are easy (both code and bandwidth), requiring only a single initial sync

Diff-based updates only make sense if the diff is significantly smaller than re-downloading the whole thing.
How often do users need to start the application for that to be the case?
I imagine many users only make a single payment, say, once a week. Or maybe once every 3 days. I would guess a few days is already a long enough time for most of the channel updates to become stale.

Going even further, I think the majority of users don't/won't open the application more than once a day.
What percentage of the gossip gets stale in just one day? Probably at least 10%.
As the graph becomes larger, even 10% starts to become large. :/

> relying on the server to enforce that you won't get screwed by misbehaving or high-fee nodes by simply removing those nodes from the graph

I am not sure I understand what you mean here. Are you saying the client would not need to rely on the server as the client itself could locally remove high-fee nodes from its graph, or that the client could trust the server to already remove such nodes/channels from the graph before sending it?

I have doubts whether it is realistic to trust a public electrum server to impartially filter the graph server-side, or indeed for the client to trust to get the graph from the electrum server in any form: the server is incentivised to include channels/nodes that are related to the server operator. For example, the server operator might open many relatively high fee channels that connect most of the graph together, and exclude all lower-fee channels from the graph it sends to the client.

**Comment by Kixunil** [comment]
Would it make sense for **desktop** Electrum to register a small, simple daemon to launch after boot and sync the DB on the background? That way unless the user attempts to pay immediately after boot the DB should be already synced when Electrum is opened.

**Comment by ysangkok** [comment]
@Kixunil how would that work unless Electrum is always installed? and is there a cross-platform API to register services?

**Comment by Kixunil** [comment]
@ysangkok it doesn't need to be installed, it could be registered on first start. Can be Electrum binary itself launched in headless mode or something. 

 don't know of any multi-platform Python API but if it doesn't exist yet, I'm willing to write it. There's only a very few OSes to worry about and I have at least rough idea of how to do it on Linux and Windows - it's simple. I knew how to do it on Mac but can't remember now, it was also simple.

**Comment by ecdsa** [comment]
see #6966

**Comment by ecdsa** [comment]
merged, closing
