### ISSUE TITLE
Crashes on program closing

### ISSUE THREAD

**Issue by eddiezato** [spesmilo/electrum#6794]
The portable version sometimes crashes after closing the program.
File electrum-4.0.5-portable.exe.****.dmp appears in AppData/Local/CrashDumps

`Dump File:	electrum-4.0.5-portable.exe.1364.dmp : AppData\Local\CrashDumps\electrum-4.0.5-portable.exe.1364.dmp`
`Last Write Time:	2020.11.30 10:39:49`
`Process Name:	electrum-4.0.5-portable.exe : D:\Portable\Electrum\electrum-4.0.5-portable.exe`
`Process Architecture:	x86`
`Exception Code:	0xC0000005`
`Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.`
`Heap Information:	Not Present`

Electrum 4.0.5 Portable
Windows 10 x64 20H2 19042.630

**Comment by SomberNight** [comment]
closing this in favour of https://github.com/spesmilo/electrum/issues/6889
