### ISSUE TITLE
Kivy GUI loaded with wallet equal to None

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6796]
Several crashes are caused by a Kivy app loaded with `self.wallet` equal to `None`.

I'm opening this issue to centralize information:

#6662 (password_dialog)
#6427 (get_invoices)
#6397 (historyscreen show_item)
#6389 (get_sorted_requests)
#6346 
#6184 
#5863 
#4548 
#4525 
#4527 
#4506 
#4502 
#4501 

from the reports it seems that in some cases wallet is set to None after the wallet has been normally loaded. 
maybe `on_stop` is called by the system in an unexpected way

**Comment by ecdsa** [comment]
also, in `on_open_wallet`, an early return is executed if `StorageReadWriteError` is caught.
This would result in a GUI loaded with `wallet == None`

**Comment by ecdsa** [comment]
maybe relevant: https://github.com/akshayaurora/electrum/blob/trezorlib_integration/electrum/gui/kivy/main_window.py#L707

**Comment by ecdsa** [comment]
maybe relevant: on_wizard_complete event, simplified in 2923c00d384307e227391a519a914893f21b92bf

**Comment by ecdsa** [comment]
I found another execution path that leads to this: if the wizard terminates with `aborted=True`, a popup is shown with the question "Do you want to launch the wizard again?". If instead of tapping "No" the user taps the Back button, then the wizard terminates but the GUI is not stopped.

**Comment by ecdsa** [comment]
I think the previous execution path explains most of these bugs, and 5058cf9d22d2aac5c62bac396768dc521384eb80 fixes it.
I will leave this issue open to see whether new reports are coming

**Comment by SomberNight** [comment]
another execution path is to get an exception raised in the kivy wizard, have a crash reporter window open, and then dismiss the crash reporter window --> now the app does not stop and we have wallet=None

**Comment by ecdsa** [comment]
> another execution path is to get an exception raised in the kivy wizard, have a crash reporter window open, and then dismiss the crash reporter window --> now the app does not stop and we have wallet=None

actually, you don't even need to dismiss the crash reporter window. it happens whatever you choose to do :-)

**Comment by ecdsa** [comment]
closing, I expect these issues to be fixed in 4.0.8
