### ISSUE TITLE
RBF "Increase fee": how to force wallet to decrease/reduce output value/amount instead of adding new inputs (bump fee, bump_fee)

### ISSUE THREAD

**Issue by AlexanderPavlenko** [spesmilo/electrum#6800]
It is unexpected and undesired for me that instead of reducing the output amount it now tries to use an additional input to cover the increased fee. Is there a way to toggle this behavior?

**Comment by SomberNight** [comment]
This changed around 3.3.7.
Now it works such that if there is an ismine output, it decreases its value, if there isn't it adds a new input.

bump_fee supports manual coin selection: just select the inputs you want to add in the `Coins` tab (if using Qt)
To fall back to the behaviour of reducing the output amount, you can right-click>`Spend (select none)`.

**Comment by AlexanderPavlenko** [comment]
Thanks!
