### ISSUE TITLE
Daemon not started (edit: on requested port)

### ISSUE THREAD

**Issue by VanillaScent** [spesmilo/electrum#6803]
I updated to 4.0.5, seems like new commands and etc.

So I tried to start the daemon using `./run_electrum daemon -d`
which says "starting daemon" but seems like its not actually online
Yesterday this wasn't happening, really weird
I'm using a normal ubuntu server, and as it worked before requirements should be met
Any clues?

Electrum acts as if its running, tho connecting to the daemon doesn't work
Enabled logs and whatnot, but nothing to be seen there

this is my config
`
{
    "blockchain_preferred_block": {
        "hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
        "height": 0
    },
    "config_version": 3,
    "rpcpassword": "pwzsBGheMkviC-3o8uFvpQ==",
    "rpcport": 7777,
    "rpcuser": "user"
}
`

`curl: (7) Failed to connect to 127.0.0.1 port 7777: Connection refused`

**Comment by verretor** [comment]
I recommend changing your password.

**Comment by VanillaScent** [comment]
That doesn't solve my issue, the local daemon host remains not contactable

**Comment by ecdsa** [comment]
did you modify the port after you started the daemon?

**Comment by ecdsa** [comment]
closing, no answer
