### ISSUE TITLE
Hi can you contact me privately?

### ISSUE THREAD

**Issue by 1400BitcoinStolen** [spesmilo/electrum#6811]
Hello
I had a similar situation 2 months ago.
36.5 Bitcoin was stolen from my address 36xej1oQw82Jz51kjBhcmV3Eb8a8vkwtrw to bc1qy303ar4jjy2x0efn00aqdlfvn48a0gddj355fv - https://blockchair.com/bitcoin/transaction/34ce7a78c6379d3176200deffd26798901dba1c726663e177d6ca9c1cf18643e

Now stolen Bitcoin are at addresses:
bc1qpk0w9pvhqrxn29vzpxpjl87w4g9hlvmv0jkmv0 (9.8181 BTC)
bc1qwtanse4pk26v0kvxcpxrfnzmnjgcxl9vkkw05t (5.4984 BTC)
bc1qstdm72hj07fxwn30j3cecxrfxnzh6ssx02thqa (4.93063517 BTC)
bc1q9wt8rfmk473nz7nh7hpgl7euhrem3n8kmag0e8 (7.83 BTC)
bc1qxn4xt0sfev5snxdgr0anrjtt5346att0gedaxz (5.55171966 BTC)

Some of the stolen Bitcoin went to Binance, but they ignore my appeals and do not return.
Cover up fraudsters.

_Originally posted by @Cryptbtcaly in https://github.com/spesmilo/electrum/issues/5072#issuecomment-683666105_

**Comment by 1400BitcoinStolen** [comment]
Hi do you have evidence of your email contact to Binance?

**Comment by daves4** [comment]
@1400BitcoinStolen Yes. Let me know your email address.

**Comment by 1400BitcoinStolen** [comment]
poolcompsopportunity@gmail.com
