### ISSUE TITLE
incorrect blockchain information

### ISSUE THREAD

**Issue by cchadwicka** [spesmilo/electrum#6814]
when creating a watch only wallet for this address:  1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF

it reports the wrong info.  march 1, 2011 deposit is displayed at; 79956000.xx btc when it should say 79956.x btc

the final balance is wrong.  attached are two screenshots.
![Screenshot (13)](https://user-images.githubusercontent.com/24611248/101255479-09882b00-36ed-11eb-8f3e-91f4e801049a.png)
![Screenshot (14)](https://user-images.githubusercontent.com/24611248/101255490-0a20c180-36ed-11eb-9b20-aabda153c6c6.png)
![Screenshot (15)](https://user-images.githubusercontent.com/24611248/101255495-0a20c180-36ed-11eb-80f2-c2c78c975076.png)

**Comment by ecdsa** [comment]
units are mBTC
