### ISSUE TITLE
Electrum Personal Server does no longer work even w/o Lightning usage

### ISSUE THREAD

**Issue by SteffenIvanhoe** [spesmilo/electrum#6815]
Using Electrum Personal Server (EPS) with a local Bitcoin node does no longer work with Electrum 4.0.6 (but did with 4.0.4). Despite for not needing Lightning, the EPS can't be used any longer! There is a bug which forces a wallet disconnect shortly after a connect.

It would be nice to have an option to NOT use Lightning if this would allow to use EPS, which for many users might be more important (otherwise they either loose privacy or access to their wallet).

Please correct the disconnect bug or make sure that Lightning can be switched off and EPS can be used again!

**Comment by ecdsa** [comment]
lightning is actually switched off until a channel is created.
I am not sure how EPS detects if lightning is used. you should submit the issue to EPS, not here

**Comment by SomberNight** [comment]
Please check the logs for both the client and the server, the issue might be unrelated to lightning.
