### ISSUE TITLE
Electrum 2fa not working unable to move funds out of wallet

### ISSUE THREAD

**Issue by Leeviker** [spesmilo/electrum#6818]
I recently installed a new wallet to restore some eth classic i purchased years ago. I was able to restore theold wallet and move the funds to a new electrum wallet on a new PC. However, now when I go into Electrum to move that eth classic out of that electrum wallet, I get prompted for 2fa, even thuogh I never set this up. I have tried restoring the wallet over again,to NO avail!!! I AM STUCK and my funds are STUCK in this wallet! How in the WORLD ca I send my coin ANYWEHERE but in this STUPID fup wallet? Electrum and 2FA SUCKS!! ANyone have a clue how to get out of this pickle? And PLEASE, restore with seed is not an option caus ethe "seed" option in the wallet is "grayed out"!!! WHy can NOT see my seed? All kinds of issue here.

**Comment by ecdsa** [comment]
all kinds of issue(s) indeed. Electrum is a Bitcoin wallet, not an Ethereum wallet...

**Comment by Leeviker** [comment]
WHy would this be closed with no solution?

**Comment by Leeviker** [comment]
Regardless I need help with this. There has to be a WAY to fix this stupid 2fa crap. I do not ver rememebr setting up 2fa and I do not have trustedcoin on my phone authenticater

**Comment by ecdsa** [comment]
> WHy would this be closed with no solution?
because there is no usable information in your report. it is not even clear which cryptocurrency you are talking about.

> I do not ver rememebr 
well, if you did not set it up, then someone else did, and that wallet is not your wallet. 
do you remember giving access to your computer to other people?
