### ISSUE TITLE
The amount sent show 0. BTC in create transation dialog.

### ISSUE THREAD

**Issue by aldrinpscastro** [spesmilo/electrum#6827]
The amount sent always show 0. BTC in create transation dialog.
![Captura de tela_2020-12-08_00-11-00](https://user-images.githubusercontent.com/48888803/101435366-fe025300-38ea-11eb-802c-1717184cba3c.png)

**Comment by ecdsa** [comment]
that is because you are sending to yourself

**Comment by aldrinpscastro** [comment]
Don't you think it is better to put the values anyway?

**Comment by ecdsa** [comment]
No. Electrum has been used by millions of people for almost 10 years, and so far we have received very little complaints about that.
In addition, the output values are visible.

**Comment by SomberNight** [comment]
"amount sent" is a sort of a diff from the point of view of the current wallet
In complex transactions, it's non-trivial to figure out "amount sent": the current method is one approach that always works and gives reasonable numbers.
