### ISSUE TITLE
Addition of Electrum to PortableApps.com!

### ISSUE THREAD

**Issue by Peppernrino** [spesmilo/electrum#6830]
I have packaged Electrum in .paf.exe format for PortableApps.com, and would like to finally inform you!

https : // portableapps.com/node/63156

Let me know what you think. If there are no bugs, etc, we can put it on the list to be added to the official list of apps. :)

[edit by ThomasV: link disabled]

**Comment by SomberNight** [comment]
What is the difference between this exe and the "portable" exe that we distribute?

**Comment by ecdsa** [comment]
Note to users: we do NOT endorse binaries distributed by third parties.
The above link could lead you to download bitcoin stealing malware.

**Comment by Peppernrino** [comment]
yeah... but it doesn't. lol. please leave the fear politics on facebook. :P 
i would appreciate some actual testing to show that i haven't malformed the package in any way. you know, as requested. 💯 

quite honestly, being in the crypto community for many years, i can tell you quite confidently that people should have just as much faith in official packages.

pretty offended that my gesture is being regarded as some kind of malware. check the package out. lol. the intent is to include it as an official package. if your claim is that portableapps.com is altogether... unsavoury... then we can further that conversation. otherwise, i think you're just being a poop. :)

**Comment by Peppernrino** [comment]
to answer @SomberNight : it is just packaged in PortableApps.com format. the original .exe is absolutely untouched. there is only a layer of NSIS stuff that moves directories back and forth when opening and closing the program, and helps the PA.c frontend recognize it etc. it's pretty nifty actually. i have no desire to steal anyone's bitcoins. i'd say we're lucky i'm the guy doing it. lol.

feel free to package it up yourself to see there are no differences. hell, you might even end up with the same md5 if you copy me exactly. who knows? but yeah.... i'm here to help, not steal. lol

**Comment by Peppernrino** [comment]
after some time with this, i wanted to posit the idea that someone could very well say the same thing about Electrum, as it is not Bitcoin Core.

has anyone discovered any programs that could test for a difference in compilation? that could be useful here.
