### ISSUE TITLE
Нет ползунка комиссии. Версия последняя.

### ISSUE THREAD

**Issue by APTEMOH** [spesmilo/electrum#6839]
Нет ползунка комиссии. Версия последняя.
Что делать?
Спасибо!

**Comment by ValdikSS** [comment]
>Что делать?

Прежде всего, писать по-английски. Ни один из разработчиков не говорит по-русски. Ваша задача, как человека, сообщающего об ошибке — сообщить о ней в понятном разработчикам форме, чего вы не сделали.

Закройте этот issue и создайте новый, на английском, указав версию, операционную систему, подробно расписав проблему и приложив скриншот.
