### ISSUE TITLE
There is no slider to select the commission when sending.

### ISSUE THREAD

**Issue by APTEMOH** [spesmilo/electrum#6840]
There is no slider to select the commission when sending.

Version 4.0.7

Windows 8.1  64

https://prnt.sc/vzxe4o
![foto_1](https://user-images.githubusercontent.com/20337954/101803667-d21ce280-3b21-11eb-826f-e6f19ef5b2b1.png)
![foto_2](https://user-images.githubusercontent.com/20337954/101803672-d2b57900-3b21-11eb-9e01-ee6a99ddd708.png)

**Comment by SomberNight** [comment]
You can configure the fee in a dialog, after clicking "Pay..."
