### ISSUE TITLE
Will an old seed phrase for an Electrum wallet created prior to Version 0.31 recover funds in 4.0.5? (incompatible breaking change in early seed format, key derivation)

### ISSUE THREAD

**Issue by giantmonster** [spesmilo/electrum#6844]
I created a wallet years ago in an early version of Electrum. I have the seed phrase however 4.0.5 does not recover the funds.
The release notes for Electrum 0.56 state:
> Version 0.34: The key derivation was changed again in version 0.34, in order to offer "type 2 wallet" capabilities. 
> Version 0.31: This version fixes a vulnerability in the key generation function.

Does the current method used for recovering an old wallet recover from an early wallet prior to Version 0.31?

**Comment by SomberNight** [comment]
No. Seeds created prior to version 0.34 are not supported anymore.

Version 0.34 was released around ~40 days after Electrum became publicly available at all, in late 2011. At that time, there were no binaries, you could only run from source. It was only available on the bitcointalk forums, and you would have had to closely follow the forums to even notice it existed. Bugs were all too common, and there was a release every few days.

You would know if you had such a seed.

Electrum [0.25 was the first](https://github.com/spesmilo/electrum/commit/8687c632263115d3868894a6c0d712856d77ac93) public version, [released 2011-11-05](https://bitcointalk.org/index.php?topic=50936.msg607510#msg607510).

relevant change in 0.31: https://github.com/spesmilo/electrum/commit/d03e60b0565ed79961685d6d0df81883b0bcdf31
relevant change in 0.34: https://github.com/spesmilo/electrum/commit/ca32d29a9c7665daa54395622b7277728722e684, released with https://github.com/spesmilo/electrum/commit/c0bf69e3b36ca0023651ee759d23a11c11a25f35 (around 2011-12-16)

**Comment by giantmonster** [comment]
Yes, I recall that and that the code was unstable. 
Was there a beta version of Electrum available in Feb/Mar 2011? I have valid seed phrase words from the first mnemonic list that do not currently generate a funded wallet.

**Comment by ecdsa** [comment]
No, Electrum did not exist in Feb/Mar 2011. Are you sure that you used Electrum prior to version 0.31?
You might simply have an "old seed" (prior to version 2)
Note that the old seed format does not include a checksum, so any list of words would be valid.
