### ISSUE TITLE
Sync drop issue

### ISSUE THREAD

**Issue by mikejnpc** [spesmilo/electrum#6845]
The client indicates its syncing at the bottom ... but then resets....
Server choice and client version are irrelevant as it still resets ...  

Its not my internet connect dropping.... 

Is there a memory limit or private key limit ? .... any advice would be appreciated
![dropping_connection](https://user-images.githubusercontent.com/39205831/101980654-c7467880-3c1b-11eb-8e82-c642137c7ee7.JPG)
... 

Thank you.

**Comment by SomberNight** [comment]
please check [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)

**Comment by mikejnpc** [comment]
Should i post the log or just the associated errors? 
There are a few ... 

> 
> 
> please check [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)

**Comment by mikejnpc** [comment]
WARNING | NotificationSession | MemoryError('dropping message over 1,000,000 bytes and re-synchronizing')
20201212T101209.379602Z |     INFO | interface.[blockstream.info:700] | requesting chunk from height 411878
20201212T101209.395227Z |     INFO | interface.[blockstream.info:700] | disconnecting due to RequestTimedOut("request timed out: ('blockchain.scripthash.get_history', ['402fabfeed56a98c9d17eee5c045e564e3df1a15dfc7cedeeaa40534be63b92f']) (id: 38511)")
20201212T101209.410850Z |     INFO | interface.[electrum2.villocq.com:50002] | disconnecting due to: ConnectError(gaierror(11001, 'getaddrinfo failed'))
20201212T101209.410850Z |     INFO | network | couldn't launch iface electrum2.villocq.com:50002:s -- CancelledError()


20201212T101209.664959Z |     INFO | interface.[bitcoin3nqy3db7c.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))

20201212T101209.680601Z |     INFO | interface.[bitcoin.aranguren.org:50002] | disconnecting due to RequestTimedOut("request timed out: ('blockchain.estimatefee', [25]) (id: 15)")

20201212T101209.850042Z |     INFO | network | couldn't launch iface electrum.hodlister.co:50002:s -- CancelledError()
20201212T101209.950358Z |     INFO | interface.[wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
20201212T101209.950358Z |     INFO | network | couldn't launch iface wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002:s -- CancelledError()

disconnecting due to: ConnectError(OSError("Multiple exceptions: [Errno 10060] Connect call failed ('2001:678:7dc:6::2', 50002, 0, 0), [Errno 10061] Connect call failed ('195.135.194.6', 50002)"))

20201212T102526.872347Z |     INFO | network | couldn't launch iface electrum.eff.ro:50002:s -- CancelledError()
20201212T102526.887969Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102526.887969Z |     INFO | lnwatcher.LNWalletWatcher.[3.3-wallet-LNW] | set_up_to_date: True
20201212T102527.405009Z |     INFO | interface.[xtrum.com:50002] | connection established. version: ['ElectrumX 1.15.0', '1.4']
20201212T102527.505300Z |     INFO | interface.[213.109.162.82:50002] | connection established. version: ['ElectrumX 1.15.0', '1.4']
20201212T102527.574358Z |     INFO | interface.[xtrum.com:50002] | set blockchain with height 661022
20201212T102527.574358Z |     INFO | interface.[xtrum.com:50002] | skipping header 661022
20201212T102527.674747Z |     INFO | interface.[213.109.162.82:50002] | set blockchain with height 661022
20201212T102527.674747Z |     INFO | interface.[213.109.162.82:50002] | skipping header 661022
20201212T102527.690334Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102527.752832Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102531.117996Z |     INFO | interface.[electrum.qtornado.com:50002] | disconnecting due to: ConnectError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
20201212T102531.117996Z |     INFO | network | couldn't launch iface electrum.qtornado.com:50002:s -- CancelledError()
20201212T102531.889462Z |     INFO | interface.[fortress.qtornado.com:443] | connection established. version: ['ElectrumX 1.15.0', '1.4']
20201212T102532.052339Z |     INFO | interface.[fortress.qtornado.com:443] | set blockchain with height 661022
20201212T102532.052339Z |     INFO | interface.[fortress.qtornado.com:443] | skipping header 661022
20201212T102532.221377Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102532.622710Z |     INFO | exchange_rate.CoinGecko | received fx quotes
20201212T102532.622710Z |    DEBUG | util.profiler | AddressList.update 0.0000
20201212T102533.626316Z |     INFO | interface.[btc.lastingcoin.net:50002] | connection established. version: ['ElectrumX 1.15.0', '1.4']
20201212T102533.795727Z |     INFO | interface.[btc.lastingcoin.net:50002] | set blockchain with height 661022
20201212T102533.795727Z |     INFO | interface.[btc.lastingcoin.net:50002] | skipping header 661022
20201212T102533.980731Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102550.940645Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102553.565724Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102553.666052Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102553.697315Z |     INFO | network | fee_estimates {25: 20083, 10: 59460, 5: 59460, 2: 59460}
20201212T102556.707753Z |     INFO | synchronizer.[3.3-wallet] | receiving history 
20201212T102557.741610Z |     INFO | synchronizer.[3.3-wallet] | receiving 
20201212T102557.863991Z |     INFO | verifier.[3.3-wallet] | requested merkle c219824da713ac23b6cedc910162c9f13c3fb3e361e368fa263cbb838fbe19ec
20201212T102600.419785Z |     INFO | verifier.[3.3-wallet] | verified c219824da713ac23b6cedc910162c9f13c3fb3e361e368fa263cbb838fbe19ec
20201212T102601.454747Z |     INFO | synchronizer.[3.3-wallet] | received tx c219824da713ac23b6cedc910162c9f13c3fb3e361e368fa263cbb838fbe19ec height: 256961 bytes: 446
20201212T102606.024068Z |     INFO | synchronizer.[3.3-wallet] | receiving 
20201212T102615.156183Z |     INFO | gui.qt.update_checker.UpdateCheckThread | valid sig for version announcement '4.0.7' from address '13xjmVAB1EATPP8RshTE8S8sNwwSUM9p1P'
20201212T102623.416133Z |    ERROR | interface.[bitcoin.alephnullptr.net:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))
20201212T102623.516466Z |     INFO | network | switching to btc.lastingcoin.net:50002:s


INFO | interface.[bitcoin.dragon.zone:50004] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(OSError("Multiple exceptions: [Errno 10060] Connect call failed ('2607:5300:60:84ec::70', 50004, 0, 0), [Errno 10060] Connect call failed ('149.56.79.70', 50004)")))





Just loops thru the various errors. …

**Comment by SomberNight** [comment]
> WARNING | NotificationSession | MemoryError('dropping message over 1,000,000 bytes and re-synchronizing')

>  20201212T102623.416133Z | ERROR | interface.[bitcoin.alephnullptr.net:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))

Those are the relevant errors.
It means you have an address with a very long history (>10k transactions touching it).
See https://github.com/spesmilo/electrum/issues/4315#issuecomment-683751285

**Comment by mikejnpc** [comment]
so my choices are to create a new wallet ... or run my own server to que from? 
i need to parse it atleast.... kinda stuck until i do and am able to update the history to be able to send a txn...

**Comment by SomberNight** [comment]
closing this; all the relevant details are in the linked issue
