### ISSUE TITLE
warn users if electrum is not synced with latest chain tip

### ISSUE THREAD

**Issue by nioncode** [spesmilo/electrum#6847]
I'm running my own full node with Bitcoin Core and electrs and connect my Electrum client to that node with the `-1 -s server.onion` command line options.

Today I noticed that when my node is behind the chain tip, then Electrum does not display any warning or 'synchronizing' message in the ui. I did a transaction last night, then I put my node in suspend mode to save power. This morning I turned it on again and checked whether my transaction went through, and it looked like it did not. I suspected this might be because of too low fees and checked the mempool, but it looked like it should have processed my transaction. When I checked back in Electrum, the transaction was confirmed.

What I suspect happened is:
- after turning off my node, it got out of sync
- when restarting it, Bitcoin Core noticed it is behind the chain tip and requested the new blocks
- after receiving the blocks, electrs indexed them
- then Electrum displayed the transaction as confirmed

Bitcoin Core (and most likely electrs) already know that they are behind the chain tip, so they could inform Electrum that the server is still syncing to the latest tip and this could then be displayed in the status bar on the client.

**Comment by SomberNight** [comment]
> and connect my Electrum client to that node with the -1 -s server.onion command line options

In fact if you did not use the `-1` oneserver option, the client would connect to multiple servers.
All other servers besides your main one are only used for block headers, which are checked for proof of work, which is the best kind of proof that you are not synced to chaintip.

**Comment by ecdsa** [comment]
Do you fully understand the implications of the `-1` (oneserver) option you are using? Electrum knows that its server is behind the tip only if you DO NOT use it.

I am against adding a protocol change where the server would send its SPV-verified tip instead of its full blocks tip, because that would add a lot of complexity to the protocol for very little benefits.

**Comment by nioncode** [comment]
Most likely I am not understanding all of the implications of the `-1` flag. I assumed this is the recommended way to use Electrum in the most private way.

How would Electrum behave if I don't use the `-1` flag? As far as I understood now, all address lookups go only to my server and the other servers are exclusively used to detect the longest chain – so the only privacy loss that I have without using `-1` is that some other servers see that my IP is running an Electrum client and asks for block headers, but does not learn anything about my addresses. However, my server is still the source of truth right, so in case of forks the other chains are ignored, is this correct?

Let's assume my scenario from my initial post:
- my server is at height 100
- all other servers are at height 120

Will Electrum now display any warning that my server is behind the other servers? Or do I have to manually go to the 'network' settings and check that other servers are on a different height?

**Comment by ecdsa** [comment]
> Most likely I am not understanding all of the implications of the `-1` flag. I assumed this is the recommended way to use Electrum in the most private way.

Recommended by whom? If it was recommended by us, it would not be a command line option, it would be a default. We do not purposefully hide things that are recommended. If something requires you to use the command line, that is because we do not recommend it. 

> How would Electrum behave if I don't use the `-1` flag? As far as I understood now, all address lookups go only to my server and the other servers are exclusively used to detect the longest chain – so the only privacy loss that I have without using `-1` is that some other servers see that my IP is running an Electrum client and asks for block headers, but does not learn anything about my addresses. However, my server is still the source of truth right, so in case of forks the other chains are ignored, is this correct?
> 

yes, that is correct

> Let's assume my scenario from my initial post:
> 
>     * my server is at height 100
> 
>     * all other servers are at height 120
> 
> 
> Will Electrum now display any warning that my server is behind the other servers? Or do I have to manually go to the 'network' settings and check that other servers are on a different height?

it would be displayed it in the status bar. in fact, Electrum had this feature even before Bitcoin core.

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum-docs/blob/dc7ab58359c2f874272b190da7ce95b021f6e457/faq.rst#does-electrum-trust-servers

**Comment by nioncode** [comment]
> Recommended by whom? If it was recommended by us, it would not be a command line option, it would be a default. We do not purposefully hide things that are recommended. If something requires you to use the command line, that is because we do not recommend it.

This was recommended by many tutorials that I consider good resources as they are from known privacy advocates:
- Chris Belcher: https://github.com/chris-belcher/electrum-personal-server
- openoms: https://openoms.github.io/bitcoin-tutorials/electrs/
- BTCPay Server: https://docs.btcpayserver.org/ElectrumPersonalServer/

**Comment by ecdsa** [comment]
How good can those tutorials be, if they do not teach users about the implications of the options they recommend?

Github is not a support hotline, developers should not have to spend their time answering questions like that.
Next time please take the time to learn what the options you use are doing.

**Comment by nioncode** [comment]
Actually in the Electrum documentation itself both ways are described and from my understanding it reads like `--oneserver` is the recommended approach (emphasis is mine): https://electrum.readthedocs.io/en/latest/tor.html

> Please note that when using electrum through tor there are two main ways. The first way has the most Privacy but also requires the most trust in the server you are connecting too. This is because normally Electrum connects to a few different servers and downloads block headers and checks that they match. This prevents / makes it more difficult for Rogue servers to send you bad information. **However this can also present a privacy issue because you could be connecting to none .onion servers for these headers.**

So by reading this statement it looks like 'if you want to have best privacy, use -1' without explaining the downsides. Should the documentation and/or the FAQ updated to mention that `-1` is most likely not what you want to have since you don't know if you are behind the tip anymore?

**Comment by ecdsa** [comment]
yes, indeed. please feel free to post a pull request for the documentation.
