### ISSUE TITLE
Ver. 3.3.6 - cannot connect to server

### ISSUE THREAD

**Issue by ivanovd** [spesmilo/electrum#6848]
I have downloaded the 64-bit Windows version of the wallet, however it doesn't connect to any of the default servers: 

![image](https://user-images.githubusercontent.com/4889583/102207793-40bdbf80-3ed7-11eb-93fa-69c7f80b5929.png)
![image](https://user-images.githubusercontent.com/4889583/102207856-54692600-3ed7-11eb-8b61-6969e8166548.png)

Any idea how to fix this?

**Comment by SomberNight** [comment]
> I have downloaded the 64-bit Windows version of the wallet

What exactly have you downloaded, from where?
Please give us URL from browser history / downloads tab of browser.

**Comment by ecdsa** [comment]
please have the decency to use the latest version of Electrum before you open a new issue.

**Comment by SomberNight** [comment]
@ecdsa they are not using Electrum. network dialog shows over 2 million blocks.
It's either altcoin client or malware.

**Comment by ivanovd** [comment]
![image](https://user-images.githubusercontent.com/4889583/102210634-18d05b00-3edb-11eb-9f6c-aaafc853b2b9.png)

The download link is: https://github.com/project-ecc/electrum-ecc/releases/download/3.3.6-ecc/electrum-ecc-3.3.6-ecc-windows-setup.exe

**Comment by ivanovd** [comment]
@ecdsa can you please elaborate why you closed the issue? If I made a mistake, please let me know what it is.

**Comment by ecdsa** [comment]
@ivanovd when you opened the issue, did you not see the following message in the textbox:

```
Note: This website is for bug reports, not general questions.
Do not post issues about non-bitcoin versions of Electrum
```

**Comment by ivanovd** [comment]
@ecdsa I apologize for thinking that not being able to connect to the default servers is a bug.

**Comment by SomberNight** [comment]
Electrum is for Bitcoin only. You seem to be using a fork of the project specifically modified for an altcoin.
This project here is not affiliated with the site you linked in any way.

**Comment by ivanovd** [comment]
I see now. Thank you for the explanation and apologies for my mistake, I was unaware of this.
