### ISSUE TITLE
impersonator (not this) repo contains fake electrum malware

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [spesmilo/electrum#6849]
Can you take down this malware electrumltc fake please? Don't follow link **Attention Malware** repo: 
https://github.com/ marc-hayden/electrum-multi-wallet
I searched for electrum on GitHub https://github.com/search?q=electrum and got malware as a result.

The particular noted disappeared thanks. but still some online:

https://www.virustotal.com/gui/file/ba0508d75cbc354a37a10ab9ebb76593b6462183dee47389ef7df898567402f5/relations
> `Ad-Aware
> 
> Gen:Variant.Razy.605355
> Alibaba
> 
> TrojanPSW:MSIL/Azorult.6acc8d50
> ALYac
> 
> Gen:Variant.Razy.605355
> Antiy-AVL
> 
> Trojan[PSW]/MSIL.AZORult
> SecureAge APEX
> 
> Malicious
> Arcabit
> 
> Trojan.Razy.D93CAB
> Avast
> 
> Win32:Malware-gen
> AVG
> 
> Win32:Malware-gen
> Avira (no cloud)
> 
> TR/Dropper.Gen
> BitDefender
> 
> Gen:Variant.Razy.605355
> BitDefenderTheta
> 
> Gen:NN.ZemsilF.34196.wq0@aa6A@Yd
> CAT-QuickHeal
> 
> Trojanpws.Msil
> Comodo
> 
> Malware@#e41u3qkk26la
> CrowdStrike Falcon
> 
> Win/malicious_confidence_100% (W)
> Cybereason
> 
> Malicious.f7604d
> Cylance
> 
> Unsafe
> Cynet
> 
> Malicious (score: 100)
> Cyren
> 
> W32/Trojan.HCIJ-3817
> DrWeb
> 
> Trojan.Inject3.22777
> eGambit
> 
> Unsafe.AI_Score_99%
> Elastic
> 
> Malicious (high Confidence)
> eScan
> 
> Gen:Variant.Razy.605355
> ESET-NOD32
> 
> A Variant Of Generik.CTXZRJN
> F-Secure
> 
> Trojan.TR/Dropper.Gen
> FireEye
> 
> Generic.mg.e19508a7e53c5bce
> Fortinet
> 
> MSIL/Azorult.GT!tr.pws
> GData
> 
> Gen:Variant.Razy.605355
> Ikarus
> 
> Trojan.Dropper
> K7AntiVirus
> 
> Riskware ( 0040eff71 )
> K7GW
> 
> Riskware ( 0040eff71 )
> Kaspersky
> 
> HEUR:Trojan-PSW.MSIL.Azorult.gen
> MAX
> 
> Malware (ai Score=82)
> MaxSecure
> 
> Trojan.Malware.73815250.susgen
> McAfee
> 
> PWS-Zbot.gen.gt
> Microsoft
> 
> PWS:Win32/Stimilina.E!rfn
> NANO-Antivirus
> 
> Trojan.Win32.Azorult.fvhqjx
> Palo Alto Networks
> 
> Generic.ml
> Panda
> 
> Trj/GdSda.A
> Qihoo-360
> 
> Win32/Trojan.PSW.a72
> Rising
> 
> Dropper.Generic!8.35E (CLOUD)
> Sangfor Engine Zero
> 
> Malware
> SentinelOne (Static ML)
> 
> DFI - Malicious PE
> Sophos
> 
> Mal/Generic-S
> Sophos ML
> 
> Heuristic
> Symantec
> 
> ML.Attribute.HighConfidence
> Tencent
> 
> Msil.Trojan-qqpass.Qqrob.Ajbh
> TrendMicro
> 
> TROJ_GEN.R002C0PGH20
> TrendMicro-HouseCall
> 
> TROJ_GEN.R002C0PGH20
> VBA32
> 
> TScope.Trojan.MSIL
> VIPRE
> 
> Trojan.Win32.Generic!BT
> Yandex
> 
> Trojan.Agent!A4ZgFUsLqrk
> Zillya
> 
> Backdoor.PePatch.Win32.112596
> ZoneAlarm by Check Point
> 
> HEUR:Trojan-PSW.MSIL.Azorult.gen
> Dr.Web vxCube
> 
> MALWARE

`

**Comment by SomberNight** [comment]
We don't have an "in" with GitHub.
The only thing that can be done is reporting the repository to GitHub.
Anyone with an account can do this, please do so here: https://github.com/contact/report-content

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, I filled my first report now of the named malware repo, as linked to, thanks anyway. Just for note.
