### ISSUE TITLE
Invalid one-time passcode - error message when I try to send Bitcoin from Electrum to Binance

### ISSUE THREAD

**Issue by deenihs2** [spesmilo/electrum#6850]
Hello, I have tried sending Bitcoin from Electrum to Binance multiple times, but I keep getting the same error.
I guess it's related to my Google Authenticator code, but I don't see how it could be wrong.
(I have just upgraded to version 4.0.7)

**Comment by SomberNight** [comment]
So this is for a 2FA wallet, right?

One-time passwords are based on time, so the clock must not be off by a lot: try resyncing your system clock (e.g. if you use Google Authenticator on Android, there is an option for this in settings).

If that does not fix it - are you sure you are trying the correct OTPs? (if you have many secrets imported into Google Auth, or if you have multiple Electrum wallets, it's easy to mix them up)

If everything looks correct, you can try restoring your wallet from seed words. When doing this, you are given two choices: (1) keep 2FA, or (2) disable 2FA. I suggest trying keep 2FA first, and then choosing "I have lost my Google Authenticator account", in which case you will be shown your 2FA secret QR code again. Scan that, and try again.

If that still does not work, you can just restore from seed words and select "disable 2FA".

**Comment by deenihs2** [comment]
Thanks for the info! I finally realised that I had changed phones since I last used Electrum, so I had to restore from seed to re-connect with the Google Auth app 👍
