### ISSUE TITLE
Android: Imported address wallet will not show it under "request"

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#6852]
On Android, if you would like to import an address to have it as watch only, it will allow you to create the wallet, display the correct balance and transaction history but if you go to "receive" it will say that there are too many pending requests and there's no usuable address. This is not too good if you want to have such an wallet as a cold storage, maybe you want to go somewhere and people scan that QR code of that address to send some coins, while you have no possibility to spend them of course you need to at least be able to receive.

This happens both if you have a single watch only address in the wallet or more addresses that are all used.

I did not have the chance to try with private key import (or public key import) because this would defeat the purpose of what i was trying to achieve but my guess is that it happens the same -- anyway we should check this too while addressing this issue.

**Comment by gits7r** [comment]
In fact, this might not be a problem. You can still get the address by going to "Addresses" -> Click on the address to get the QR code and be able to receive in watch only mode. You cannot create a request because a request by itself includes a fresh address. I will leave this issue open for few more hours so more eyes can see it, and if we think current behavior is good we can close it.

**Comment by ecdsa** [comment]
we should probably do what qt does

**Comment by gits7r** [comment]
In this case we have a minor undesired behavior. In qt, it will warn that it's an imported wallet, and it's recommended to have a deterministic wallet and etc. but if you click yes proceed it will generate the payment request marked as "paid" and flagged with red, as we do for funded / used addresses. This is ok and expected.

Kivy does not give you that pop-up, it only says there are no usuable addresses. So you cannot proceed with the payment request further.

See:
![ele1](https://user-images.githubusercontent.com/6549887/102336028-8b4b4480-3f88-11eb-97ac-d45f12de434e.png)

and:
![ele2](https://user-images.githubusercontent.com/6549887/102336049-91d9bc00-3f88-11eb-86eb-c60745bee1ae.png)

**Comment by gits7r** [comment]
Can someone test this for CLI / console too? So we apply the fix with this warning everywhere?
