### ISSUE TITLE
 I cannot send money from my wallet

### ISSUE THREAD

**Issue by Lucianeko** [spesmilo/electrum#6856]
Today I tried to send bitcoin out of my wallet (the maximum amount I have)
![image](https://user-images.githubusercontent.com/75849289/102488132-df7b2500-406b-11eb-91d9-9d822d5ed2c9.png)

 but when I try to pay Electrum tells me that I do not have enough funds even though I have the amount. 
![image](https://user-images.githubusercontent.com/75849289/102488191-f6217c00-406b-11eb-9203-40c9cb20ce82.png)

If I press the max button at the level of the amount it puts me an amount which is not at all my maximum. So I am stuck.
![image](https://user-images.githubusercontent.com/75849289/102488222-020d3e00-406c-11eb-962f-3250c68d0516.png)

**Comment by SomberNight** [comment]
Press "max", and then press "Pay...". Then on the next screen you can adjust the mining fee.

**Comment by Lucianeko** [comment]
> Press "max", and then press "Pay...". Then on the next screen you can adjust the mining fee.

Yeah but why does it say 3.09 euros ?

**Comment by Lucianeko** [comment]
> Press "max", and then press "Pay...". Then on the next screen you can adjust the mining fee.

It litteraly don't want to send all my money the maximum for Electrum it's 3.09 euros (altough i have around 21 euros) i don't know why and it's not the minig fee

**Comment by SomberNight** [comment]
Do you have a 2FA wallet? Click the blue shield icon in the bottom right.
I suspect the difference is the [2FA fee for the next 20 transactions](https://api.trustedcoin.com/#/electrum-help), which is atm 0.001 BTC.
This was explained during wallet creation.

**Comment by Lucianeko** [comment]
> Do you have a 2FA wallet? Click the blue shield icon in the bottom right.
> I suspect the difference is the [2FA fee for the next 20 transactions](https://api.trustedcoin.com/#/electrum-help), which is atm 0.001 BTC.
> This was explained during wallet creation.

Hello yes i have a 2FA wallet. So why can't i send all my 0.00116659 bitcoin ?

**Comment by ecdsa** [comment]
You have to either pay the Trustedcoin fee, or disable 2FA on your wallet (you can do that by restoring from seed)

Please do us a favor, and explain to us how we could make that information more visible so that you would not have posted this issue.

**Comment by Lucianeko** [comment]
> You have to either pay the Trustedcoin fee, or disable 2FA on your wallet (you can do that by restoring from seed)
> 
> Please do us a favor, and explain to us how we could make that information more visible so that you would not have posted this issue.

Hello i don't know how to pay the Trustedcoin fee or disable 2FA by restoring so....
