### ISSUE TITLE
No bar for transaction fees available in Electrum 4.0.8

### ISSUE THREAD

**Issue by Crypotbear** [spesmilo/electrum#6861]
Hello. I just installed Electrum 4.0.8 on a Win 7-32 machine.
When I tried to make my first transaction with this version I was notified that the transaction fee would be very high, almost as high as the transaction itself.
I was looking for the bar to adjust the fees like I know from version 3.3.8.
But there was no such bar.
Is it a bug or related to my system??

thanks

**Comment by ecdsa** [comment]
please post a screenshot

**Comment by ecdsa** [comment]
closing, I guess this user didn't see the slider in the very same dialog
