### ISSUE TITLE
Big mess in my wallet, unable to do anything

### ISSUE THREAD

**Issue by Wise800** [spesmilo/electrum#6862]
Hi folk,

I have a big issue with Eletrum transactions, very weird one, and I don't find solution...

3 days ago, I sent BTC in a wallet, after 2 confirmations, the payment has been marked as received.

Few hours later, I sent another BTC to another wallet, the transaction has been marked as "unconfirmed parent", and after 10 hours, still no confirmation... And the first transaction has been marked as "unconfirmed"! (it was ok before the second payment, it's what I don't get).

I waited 2 days but nothing more happened.

Few hours ago, I canceled the first order (double-spend), then now I have a new transaction "unconfirmed parent" ( the refund).

So, if you understood me, I now have 1 "unconfirmed" and 2 "unconfirmed parent", and nothing happens......!

I'm pretty new to crypto, I guess I did wrong, but seriously why a payment has been marked has received, and after another transaction, it returned to 0 confirmations??

I also guess that the parent transaction need to be confirmed, but after 3 days it's not....

Someone able to help me? :/

**Comment by ecdsa** [comment]
please learn about bitcoin fees and confirmation
