### ISSUE TITLE
0. 067 btc stolen

### ISSUE THREAD

**Issue by Programiks** [spesmilo/electrum#6869]

**Comment by Programiks** [comment]
0. 067 btc stolen (id a357c6eb1d8a3177303612c050eae4f35756f0e25085071bfaad4ce60b055df5)
Can you please tell me what are the chances of getting them back? Thank you
Regards,
Sergey

**Comment by Transisto** [comment]
Your only chance is asking or forcing the thief to send them back to you.

Bitcoin would not roll back transactions even if 10 billion were stolen.

**Comment by ecdsa** [comment]
closing this; without a description of how the theft happened, there is no reason to believe it was caused by a bug in Electrum.
