### ISSUE TITLE
Can't get fiat rates or sync labels.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#6870]
When I try to download labels I get: 
![image](https://user-images.githubusercontent.com/388716/102676551-205a6300-416c-11eb-9dec-ceb162760e1d.png)

and $ value show as No Data since Nov 23rd.
![image](https://user-images.githubusercontent.com/388716/102676591-5b5c9680-416c-11eb-9ffa-9fcc38a58874.png)

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/6748#issuecomment-731094655
please close the issue if that fixes it

**Comment by Transisto** [comment]
Worked thanks!
