### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by 1datatec** [spesmilo/electrum#6873]
Not really a bug, but an ability to increase font size could've been great. I assume it's hard to implement with QT?

**Comment by ecdsa** [comment]
please post a screenshot so we can see how it looks for you

**Comment by 1datatec** [comment]
It looks normal :)
But i have 2k 27" monitor and bad eyes. So I'm increasing font size everywhere. System DPI is 100%. In Electrum i don't see a way to change font size to 12 or 14. Do i miss something?

**Comment by ecdsa** [comment]
are you saying that Electrum does not increase its DPI when you change the System DPI?
does it behave differently than other apps?
what OS are you using?

**Comment by 1datatec** [comment]
No. I don't change system dpi. But an ability to change font size IN Electrum itself would've been very useful.
Something like this:
![2020-12-19_12-00-02](https://user-images.githubusercontent.com/2266644/102686664-5ee23300-41e9-11eb-8dd6-6369288228f2.png)

**Comment by ecdsa** [comment]
sorry, no, we will not do that.
it is enough to change the font from the system
