### ISSUE TITLE
Unable to import xpub from ledger live

### ISSUE THREAD

**Issue by 1datatec** [spesmilo/electrum#6874]
I'm trying to import xpub from ledger live software for watch-only wallet.

Ledger live shows this format:
`{
  "xpub": "xpubXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "index": 0,
  "freshAddressPath": "84'/0'/0'PATH",
  "id": "libcore:1:bitcoin:xpubXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:native_segwit",
  "blockHeight": 662029
}`

I import xpub and nothing shows up in Electrum.
If i take xpub from ledger, convert it to zpub and import to Electrum watch-only then it works.
If i create new wallet with ledger in Electrum, copy zpub from Wallet Info and import to Electrum watch-only then it works.

**Comment by ecdsa** [comment]
that is expected. an xpub is ambiguous, and we cannot fix that.
