### ISSUE TITLE
Cant send my coin

### ISSUE THREAD

**Issue by sanyhendrik** [spesmilo/electrum#6877]
Helo, i need help. I have a balance on my electrum wallet but it cant send. Always show error message when sending transaction

**Comment by ecdsa** [comment]
upgrade to current version, give relevant details, and I might reopen this issue.

**Comment by sanyhendrik** [comment]
just upgraded but still can't send. I have 2 wallet which is have 26btc and 392btc on my balance wallet, try to send 0.03 btc to bc1xxx wallet it still can't. It says not enough funds and than show error but my balance is still on the wallet, cant do anything with it.
