### ISSUE TITLE
Button to Send to address pasted from clipboard.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#6878]
![image](https://user-images.githubusercontent.com/388716/102849151-86e9b600-43e4-11eb-9df6-74845621d618.png)

**Comment by ecdsa** [comment]
it would be better to have distinct (but related) icons for copy and paste

**Comment by stickies-v** [comment]
I'm happy to have a go at this but I'm not sure I understand the requirements 100%. Effectively, this new button would paste the contents from clipboard into the "Pay to" field? Would this not be equivalent to just using ctrl+v (or using the context menu)?

**Comment by Transisto** [comment]
Yes, it would be consistent with clicking the button to copy the address
instead of doing ctrl-c.
