### ISSUE TITLE
Problem with a transfer

### ISSUE THREAD

**Issue by Aldogtz09** [spesmilo/electrum#6879]
Idk if the problem is from my internet but i send 0.00057789 btc to my wallet and i dont recive that :/, i have a screenshot of the transfer idk if someone can help me, i know dont is much money but i need that, can someone help me??

**Comment by SomberNight** [comment]
Do you have a txid? If so, look it up on a [block explorer](https://blockstream.info/). Compare expected and actual addresses of the tx.

**Comment by Aldogtz09** [comment]
The adress of my transfer is the same but idk why dont recive the btc

**Comment by ecdsa** [comment]
closing, not useful
