### ISSUE TITLE
Problem with my Gold Wallet

### ISSUE THREAD

**Issue by FMFigueroa** [spesmilo/electrum#6880]
Every  time I transfer from minincity to my Gold Wallet the address of my wallet is changed, this seems to me that it is not normal, what do you think?

**Comment by SomberNight** [comment]
(1) What is a a "Gold Wallet"? Electrum is for Bitcoin only. Altcoins are off-topic.
(2) Even with Bitcoin, you should never reuse addresses if at all possible, so any decent wallet will give you a fresh address every time.
