### ISSUE TITLE
New wallet window has wrong title

### ISSUE THREAD

**Issue by jingxi285** [spesmilo/electrum#6884]
v4.0.9

New wallet window has wrong window title "Install wizard"  should be "Create new wallet"

**Comment by ecdsa** [comment]
what this windows does depends on the context. it does not always create a new wallet.

**Comment by SomberNight** [comment]
related: https://github.com/spesmilo/electrum/issues/6466

These are not the only occasions people complained about the "Install Wizard" name being confusing.
I think maybe we should rename it to just "Wizard"; or maybe "Wallet Wizard".
IMO it is the "Install" term that is misleading.

**Comment by ecdsa** [comment]
note that part of the install process is not related to the wallet: how to connect to servers (and possibly more in the future)
ideally, we should separate the configuration wizard from the wallet creation wizard, but that is not done yet.

**Comment by jingxi285** [comment]
thank you. I just posted a comment on #6466
Probably just a window title of "Electrum" is enough? keep-it-simple etc :-)

**Comment by ecdsa** [comment]
closing this; one issue is enough.
