### ISSUE TITLE
Restore electrum seed on Trezor not working

### ISSUE THREAD

**Issue by jingxi285** [spesmilo/electrum#6885]
Adding my electrum 12 word seed to Trezor does not find the balance. I know I can use Trezor seed on Electrum (native segwit p2wpkh). hoped electrum seed would work on trezor too.

**Comment by jingxi285** [comment]
using latest electrum and trezor firmware

**Comment by jingxi285** [comment]
electrum balance is regular P2PKH 1-prefix addresses

my purpose is, I would like to start using a hw wallet.

**Comment by ecdsa** [comment]
Electrum seeds are not compatible with Trezor.

please read https://electrum.readthedocs.io/en/latest/seedphrase.html

**Comment by jingxi285** [comment]
thank you for your reply. will have a good read of this.

**Comment by Engelberg** [comment]
How much work would it be to write custom firmware for the Trezor to support electrum seeds? I'm a programmer; is this something that the developer community could point me in the right direction and guide me if I wanted to take this on?

It seems to me that there would be real value in implementing this. I think a lot of people who started out with electrum seeds have seen the value of their holdings grow so much that they no longer feel safe accessing their btc on an online computer. It would be more secure to enter the electrum seed into a hardware wallet like Trezor that had the appropriate firmware to understand the electrum seed format.

**Comment by ecdsa** [comment]
@Engelberg I do not know about Trezor, but that has been done with Ledger, and I do not think it took them a lot of work (although their management did not follow-up with commercialization). @btchip is the developer who did it.

**Comment by SomberNight** [comment]
@Engelberg Just in case you haven't realised, you can do offline signing using two computers without a hardware wallet involved.
Offline PC would have private keys, online PC would have watch-only wallet.
