### ISSUE TITLE
Cosigning server is down

### ISSUE THREAD

**Issue by Asafffff** [spesmilo/electrum#6887]
When using the cosigner plugin, an error pops up:
```
Failed to send transaction to cosigning pool:
<ProtocolError for cosigner.electrum.org/: 301 Moved Permanently>
```
The server itself redirects to itself infinite number of times - 
http://cosigner.electrum.org/

**Comment by ecdsa** [comment]
the server was restarted on Friday. can you check if it is working now?

**Comment by bauerj** [comment]
Hey @Asafffff 

there are some hardware issues with the server right now. We will keep you updated once we know more.

**Comment by bauerj** [comment]
Server is back up and running. We will continue to investigate the cause of this issue.
