### ISSUE TITLE
My bitcoins disappeared from my electrum wallet

### ISSUE THREAD

**Issue by ronaldinhodeep** [spesmilo/electrum#6888]
hello, I created a wallet in 2017 and sent bitcoins there, today I restored the wallet on a new device using a seed and did not see my bitcoins, what should I do

**Comment by SomberNight** [comment]
see https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet

**Comment by ronaldinhodeep** [comment]
I changed Gap, but it didn't work, my BTC not found

**Comment by ecdsa** [comment]
Given information you gave to us, there is no reason to believe you need anything else than the the link posted above.

**Comment by ronaldinhodeep** [comment]
Why?

**Comment by ronaldinhodeep** [comment]
My BTC not found

**Comment by ecdsa** [comment]
because the information you post is useless to us. 
what do you expect us to do?
this is a bug report system, not a support hotline.

**Comment by ronaldinhodeep** [comment]
Where I can find hot support?
27 дек. 2020 г., 12:46 +0200, spesmilo/electrum <reply@reply.github.com>, писал:

**Comment by ecdsa** [comment]
there is no official support hotline. you can ask for support on forums (bitcointalk, reddit), but I suggest you first try the different options in the faq.

**Comment by ronaldinhodeep** [comment]
Can you send me faq, please? I am worrying a lot
27 дек. 2020 г., 13:12 +0200, ThomasV <notifications@github.com>, писал:

**Comment by ecdsa** [comment]
https://bitcoinelectrum.com/frequently-asked-questions/
