### ISSUE TITLE
electrum cant send coins 

### ISSUE THREAD

**Issue by cranepatrick** [spesmilo/electrum#6891]
when i want to send coins an error comes and it says : 

"bitcoinadress"... (ValueError('not enough values to unpack (expected 2, got 1)'))

**Comment by ecdsa** [comment]
please post the complete traceback, and indicate the version number of Electrum you used

**Comment by cranepatrick** [comment]
4.0.3 is the version number 

and it says : 

Warning !
Invalid Lines found:

Line #1: 1B3FoQvmFYyNqChm7qfDQ﻿pT9VN6a7tZXXX... (ValueError('not enough values to unpack (expected 2, got 1)')

**Comment by ecdsa** [comment]
please try with the latest version. reopen if the issue persists
