### ISSUE TITLE
Qt GUI segfaults with QT_QPA_PLATFORM=offscreen

### ISSUE THREAD

**Issue by snex** [spesmilo/electrum#6892]
Ubuntu 20.04, Electrum immediately Seg faults on startup with the following output:

```
> ./run_electrum 
/usr/lib/python3/dist-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Callable
QObject::connect: Cannot connect (null)::systemTrayWindowChanged(QScreen*) to QSystemTrayWatcher::systemTrayWindowChanged(QScreen*)
Segmentation fault (core dumped)
```

**Comment by SomberNight** [comment]
Saying "Ubuntu 20.04" is oversimplifying things; you would not be the only one affected.

- What window manager do you use?
- And what window system; x11 or wayland?
- What do you get running `$ set | grep QT_` ?
- How did you install Electrum? More specifically, how did you install Qt? Are you using the Qt/PyQt from `apt` or from `pip`?
-  Try running Electrum as `$ QT_QPA_PLATFORM=xcb ./run_electrum`

**Comment by snex** [comment]
> What window manager do you use? And what window system; x11 or wayland?

Gnome3 on X11

```
> set | grep QT_
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
QT_QPA_PLATFORM=offscreen
```

> How did you install Electrum? 

Through following the instructions on the homepage as well as the git repo. I tried all available options (run tar.gz directly, extract and run ./run_electrum, and clone git repo and do everything in there), and get the same result from all of them.

> More specifically, how did you install Qt? Are you using the Qt/PyQt from apt or from pip?

No idea as I did this years ago and Electrum worked at that time. I have not used it for longer than a year (and on Ubuntu 16.04 LTS) so I also cannot say when it stopped working.

> Try running Electrum as $ QT_QPA_PLATFORM=xcb ./run_electrum

This seems to work.

**Comment by SomberNight** [comment]
>> Try running Electrum as `$ QT_QPA_PLATFORM=xcb ./run_electrum`
>
> This seems to work.

>> What do you get running `$ set | grep QT_` ?
>
> `QT_QPA_PLATFORM=offscreen`

Well clearly that is the issue then.
Any idea why that is set?

**Comment by snex** [comment]
No, I don't even really know what these options are used for.

**Comment by snex** [comment]
I figured it out - QT_QPA_PLATFORM=offscreen is something required by phantomJS, a headless javascript engine. Looks like they have no intention of fixing this on their end either. :(

Users of both Electrum and phantomJS will need to manage this env var manually, it seems.

**Comment by SomberNight** [comment]
Not sure what to do about this, or whether we can do anything.
