### ISSUE TITLE
The transaction did not reach, although it is confirmed

### ISSUE THREAD

**Issue by balkow** [spesmilo/electrum#6893]
Good day. I am using electrum version 4.0.9. Yesterday I made a request to get "bc1qv0c2eq386t8g0xr7g6vj0zd305vy3gxslmfuvm". As a result, the verification of the transaction says that the transfer took place, but in fact nothing came to the wallet, and the request also weighs in waiting for another 6 days. Here is the transaction check https://www.blockchain.com/btc/address/bc1qv0c2eq386t8g0xr7g6vj0zd305vy3gxslmfuvm. Tell me how to be in this situation?
![30 12](https://user-images.githubusercontent.com/76773816/103345076-764ed500-4aa1-11eb-80a3-ae574885f481.jpg)

**Comment by ecdsa** [comment]
is the transaction shown in your history?
