### ISSUE TITLE
wizard can create invalid wallet file in some flows. WalletFileException: Unknown wallet type: None

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#6895]
I've managed to get the Qt wizard to create a wallet that then fails to be opened.

To reproduce (scenario 1):
- open wizard, create new wallet
- select "standard wallet"
- select "I already have seed"
- enter `9dk` as seed text
- click "Options", select "Extend this seed with custom words"
- click "Next"
- on "Seed extension" screen now, click "Back"
- enter `9dk` as seed text
- click "Next"
- click "Next"
- invalid wallet file gets created

To reproduce (scenario 2):
- open wizard, create new wallet
- select "standard wallet"
- select "I already have seed"
- click "Options", select "BIP39 seed"
- enter `all all all all all all all all all all all all` as seed text
- click "Next"
- on "Derivation path" screen now, click "Back"
- click "Options", select "BIP39 seed"
- enter `all all all all all all all all all all all all` as seed text
- click "Next"
- click "Next"
- invalid wallet file gets created

```
E | gui.qt.ElectrumGui | 
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/gui/qt/__init__.py", line 257, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/home/user/wspace/electrum/electrum/daemon.py", line 495, in load_wallet
    wallet = Wallet(db, storage, config=self.config)
  File "/home/user/wspace/electrum/electrum/wallet.py", line 2859, in __new__
    WalletClass = Wallet.wallet_class(wallet_type)
  File "/home/user/wspace/electrum/electrum/wallet.py", line 2869, in wallet_class
    raise WalletFileException("Unknown wallet type: " + str(wallet_type))
electrum.util.WalletFileException: Unknown wallet type: None
```

maybe related: https://github.com/spesmilo/electrum/issues/5548  (although that is for kivy/android)

**Comment by ObscenityIB** [comment]
just had this issue myself, creating a wallet with an extended seed

**Comment by ecdsa** [comment]
this is because we enter a new screen without `run`.
- screens that have the back button should always be entered through `run`
- `can_go_back` should actually check that this was the case, and return False if that was not the case

**Comment by ecdsa** [comment]
this fixes the current bug:

```diff --git a/electrum/base_wizard.py b/electrum/base_wizard.py
index c17289ed6..7245a8eab 100644
--- a/electrum/base_wizard.py
+++ b/electrum/base_wizard.py
@@ -509,7 +510,8 @@ class BaseWizard(Logger):
         self.opt_ext = True
         is_cosigning_seed = lambda x: mnemonic.seed_type(x) in ['standard', 'segwit']
         test = mnemonic.is_seed if self.wallet_type == 'standard' else is_cosigning_seed
-        self.restore_seed_dialog(run_next=self.on_restore_seed, test=test)
+        f = lambda *args: self.run('on_restore_seed', *args)
+        self.restore_seed_dialog(run_next=f, test=test)
 
     def on_restore_seed(self, seed, is_bip39, is_ext):
         self.seed_type = 'bip39' if is_bip39 else mnemonic.seed_type(seed)
```

But the issue remains that this code is fragile. The stack logic was introduced without taking into account the fact that `run` is not systematically called. We should try to fix that at a more fundamental level.

**Comment by ecdsa** [comment]
I pushed the previous fix, because a systematic solution will take more time. To really fix this, we could create a `frame` decorator, and apply it to all the wizard methods that require to push something in the stack:

```python
    def frame(func):
        def wrapper(self, *args, **kwargs):
            db_data = copy.deepcopy(self.data)
            self._stack.append(WizardStackItem(func, args, kwargs, db_data))
            func(self, *args, **kwargs)
        return wrapper
```

In addition, we could try to get rid of the `run` method, but the plugins make that difficult.
