### ISSUE TITLE
Errors while trying to open a lightning channel.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#6896]
![image](https://user-images.githubusercontent.com/388716/103397349-00c92000-4b06-11eb-81ff-3283188e69c7.png)

![image](https://user-images.githubusercontent.com/388716/103397356-07f02e00-4b06-11eb-8558-6a170d813e95.png)

Trying to send 5$ at 5sat/b

**Comment by ecdsa** [comment]
how did you choose the remote node? was it with the suggest button?

**Comment by Transisto** [comment]
yes, suggest button

**Comment by bitromortac** [comment]
Could it be a problem connecting to a tor node which is suggested by lnrater?

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/103572225-3bcaab00-4e9a-11eb-87d9-07a1178ba937.png)

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/103614322-53378180-4ef6-11eb-9fa6-8972aa492f2f.png)

**Comment by Transisto** [comment]
It's hard to know it these messages are from electrum or passed form the node.

**Comment by ecdsa** [comment]
The minimum amount of 200000 sats is a constant set by Electrum.
I can see that it is probably too high.

**Comment by Transisto** [comment]
> The minimum amount of 200000 sats is a constant set by Electrum.
> I can see that it is probably too high, give the current price.

It's too high for what seems to be very experimental.
