### ISSUE TITLE
Why only pgp sig not other like sh256  for verifying the download file  ? 

### ISSUE THREAD

**Issue by skyerjoe** [spesmilo/electrum#6898]
Why is only pgp for verifying the download file  availiable ? 

best regards

**Comment by ecdsa** [comment]
Because sha256 is not a signature, it is a checksum.
A checksum provides zero protection against our website being compromised.

Please do not post a github issue whenever you have a newbie question, it is wasting our time.

**Comment by skyerjoe** [comment]
may , but i've also suggested long time ago before to check the electrum version in the software directly. 

*thankgod*it*was*about*time*u*did*it

so may i'm not so firm in some things but this is not fair. 

no offense 

happy new years eve
