### ISSUE TITLE
After Update Bitcoin gone

### ISSUE THREAD

**Issue by FiB-20** [spesmilo/electrum#6899]
Hi everybody, I´ve just installed an update of Electrum and all my Bitcoins are gone.
I´ve read on the internet that is a malware and all my bitcoin are gone. Is it true? there is a way to get them back?
I´ll be greatful for your answer.
Thank you - FiB  
![Malware Bitcoin](https://user-images.githubusercontent.com/76821903/103421225-7f23d180-4b9b-11eb-83ff-bc1a08e121fe.PNG)

**Comment by Transisto** [comment]
The only way to get them back is from the person who took them.

The place to start would be investigating from where you downloaded that malware.

**Comment by ecdsa** [comment]
This is another case of phishing, see the warning on our website.
Please report this to the police of your jurisdiction. 
If you live in Germany, please report it to the Cybercrime unit of the LKA Berlin
