### ISSUE TITLE
Electrum crash when launching QR code reader. (zbar, freeze, camera, scan)

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#6901]
![image](https://user-images.githubusercontent.com/388716/103435467-d0a08080-4bdc-11eb-9cfc-c90bffa4f3fe.png)

on win10
zbar window shows up for 3-10 second then electrum disappear.

Logs don't seems to show anything about the crash.

rebooted PC, reinstalled electrum, same.

Could be related : https://github.com/spesmilo/electrum/issues/6336

**Comment by Transisto** [comment]
I tested installing just zbar itself, it works fine.

Also when asking electrum to scan while cam is in use Zbar open and electrum stay frozen.

![image](https://user-images.githubusercontent.com/388716/103435711-b072c080-4be0-11eb-84b2-68d5fbdbc1ce.png)

**Comment by SomberNight** [comment]
maybe related: https://github.com/spesmilo/electrum/pull/6593
could you test with 4.0.3?

**Comment by Transisto** [comment]
> maybe related: #6593
> could you test with 4.0.3?

![image](https://user-images.githubusercontent.com/388716/103574147-6e29d780-4e9d-11eb-84fc-cc5ff92bd5d5.png)
on 4.0.3
BTW it used to work fine

**Comment by SomberNight** [comment]
ok, re last comment, that's identical to https://github.com/spesmilo/electrum/issues/6018, which is what https://github.com/spesmilo/electrum/pull/6593 intended to fix

I cannot reproduce the issue in OP; zbar works for me on win10.
Good to know you can reproduce https://github.com/spesmilo/electrum/issues/6018 as I could not reproduce that either.

>  BTW it used to work fine

when? what changed?

**Comment by rafaelpac** [comment]
I have the same issue.
I started using Electrum on Feb 10, 2021 for some tests (portable version 4.0.9).
It was working fine, I don't know what might have happened, but something along the last 30 or 40 days, and now Electrum crashes every time I try to scan something.
The camera works fine on other apps.
I have installed the installed version 4.0.9 and same problem.

**Comment by SomberNight** [comment]
git master now has another method to access the camera, using QtMultimedia (see https://github.com/spesmilo/electrum/pull/7365).
For the Windows binary we will use that method to scan QR codes.
(in contrast with the previous method of using zbar+directshow to access the camera)

I still could not reproduce this issue however, hopefully this fixes it.
