### ISSUE TITLE
Electrum 3.3.8 .exe considered as PUA:Win32/CoinMiner

### ISSUE THREAD

**Issue by dexX7** [spesmilo/electrum#6902]
Hey guys,

I'm still using the .exe of Electrum 3.3.8 on Windows 10 x64. Last usage was no longer than a month ago, but now it's considered by Windows as PUA:Win32/CoinMiner.

The app can be whitelisted, but it may be good to check new versions on Windows as well.

**Comment by ecdsa** [comment]
upggrade
