### ISSUE TITLE
Electrum lightning network testnet: When selecting the option: close channel, the wallet is completely inoperable and this warning does not disappear

### ISSUE THREAD

**Issue by jonjonez** [spesmilo/electrum#6908]
After I opened the channel and did some tests making small payments, I tried to close one of the channels I had opened to get the funds back at one of the addresses derived from my wallet, however when I click close channel, a pop-up appears that never disappears , I already left the wallet open for hours but Electrum does not close the channel ...

And the channel status is like SHUTDOWN, I don't know if I can use it again ...

What should I do to close a channel already in that state?

OBS:The channel I'm trying to close is the last one below: demo2.lndexplorer.com which is currently in SHUTDOWN status.

Problem image: https://imgur.com/4SmDAZC

**Comment by bitromortac** [comment]
What did you see in the popup? Did you see the failing of the channel closing? If you have logs, could you provide them? After sending shutdown yourself, the channel has to clear its pending HTLCs if there are any. If there's a hickup of some sort you can still perform a force close and the funds should be sent to you.

**Comment by ecdsa** [comment]
the screenshot suggests that there are no pending HTLCs.
the remote node might just not be sending `closing_signed`, and they may not have broadcast the closing tx.
as @bitromortac suggested, try to force close the channel
