### ISSUE TITLE
Electrum has not picked up the rest of the transfer

### ISSUE THREAD

**Issue by bysiar** [spesmilo/electrum#6909]
Hi! Electrum wallet 4.0.9 segwit. I sent a BTC transfer from segwit bc1... to address 3N.... The rest came back to legacy address 1Nn.... Unfortunately, the wallet cannot see legacy addresses and I cannot access the address. How can I recover the lost funds? Someone can help me?
Transaction details:
https://www.blockchain.com/btc/tx/db8eacc3470466622517a4fe4a7247a83b292dc9f250bdabfffb319c8b20ba2e

**Comment by ecdsa** [comment]
was the transaction created in Electrum?

**Comment by bysiar** [comment]
The transaction was taken from the private key for the amount of 0.11572179 BTC. The rest should go back to the wallet, but not. I mean, she's back, but she's not on the wallet.

**Comment by ecdsa** [comment]
how was the transaction created?

**Comment by ecdsa** [comment]
it would be interesting to know if 1Nn... has the same public key as your segwit address. (you can see it in address->details)

**Comment by bysiar** [comment]
The private key has been imported by another program. I don't know what. I can check the bc1... public key. I can't read the 1Nn... key :(

**Comment by ecdsa** [comment]
Please be accurate: the private key has not been imported BY another program. Either it has been imported BY you FROM Electrum IN another program, or it has been imported BY you FROM another program IN Electrum. Do you understand the difference?

**Comment by bysiar** [comment]
I'm sorry, my english is not good. The private key has been imported from electrum in another program.

**Comment by ecdsa** [comment]
thank you for the clarification. this is not an Electrum issue, then. I suggest you learn how that other program works.

**Comment by ecdsa** [comment]
note: you can try to import the private key into a new Electrum wallet, without the p2wphk: prefix. 
maybe the change address has the same key.

**Comment by bysiar** [comment]
Thanks for the hint. I'll try to do that...

**Comment by bysiar** [comment]
Success! Thank you very much!!! How can I repay you for your help! :)
