### ISSUE TITLE
No funds message / cannot send my bitcoin

### ISSUE THREAD

**Issue by cimetovsan** [spesmilo/electrum#6912]
I have this problem for months now.
I have 0.00176... btc on my wallet, but anytime i try to send my funds, it always says "no funds". no matter how much funds i choose to send, even a small portion of it, nothing works. 
If i click on "max" it just fills in the blanks with 0. 

please help me fix this issue

<img width="905" alt="Screen Shot 2021-01-05 at 8 13 37 AM" src="https://user-images.githubusercontent.com/32026758/103592792-f1dfd480-4f2e-11eb-939c-8c55b2c18e13.png">

<img width="236" alt="Screen Shot 2021-0

<img width="549" alt="Screen Shot 2021-01-05 at 8 15 31 AM" src="https://user-images.githubusercontent.com/32026758/103592826-0ae88580-4f2f-11eb-9cb5-f6a084c9b8ec.png">
1-05 at 8 13 55 AM" src="https://user-images.githubusercontent.com/32026758/103592816-03c17780-4f2f-11eb-9feb-6b5f5b372860.png">

My funds are completely unusable, and i dont understand why this happens. 
Im using the latest version of Electrum, and before i never had an issue with this... 
but now my funds are stuck here...

**Comment by ecdsa** [comment]
you don't have enough funds to pay the mining fee.
use the latest version, it will let you adjust the fee rate on the next screen.

and please do not post issues before trying the latest version. always mention which version you are using.

**Comment by cimetovsan** [comment]
Dear, i am using version 4.0.9

<img width="380" alt="Screen Shot 2021-01-06 at 8 32 20 AM" src="https://user-images.githubusercontent.com/32026758/103714556-e0afca00-4ff9-11eb-84f3-4416319e35a2.png">

**Comment by cimetovsan** [comment]
> you don't have enough funds to pay the mining fee.
> use the latest version, it will let you adjust the fee rate on the next screen.
> 
> and please do not post issues before trying the latest version. always mention which version you are using.

i already mentioned in the post before that i use the latest version of the electrum, sorry but its not true that i didnt mentioned the version. just read my post till the end.

**Comment by cimetovsan** [comment]
i still have this issue, and my btc are frozen, so you shoudlnt close this issue, because its still open. 
i still have the problem and my btc are frozen
i never get to see the window where i set the transaction fee... 
can someone please help me

**Comment by SomberNight** [comment]
Have you frozen any of your addresses/coins? (check `Addresses` and `Coins` tab)

**Comment by cimetovsan** [comment]
> Have you frozen any of your addresses/coins? (check `Addresses` and `Coins` tab)

thanks man! i checked my coins tab and i found out that my coins were frozen, but not sure how this happened, or what led to that...
now i just clicked unfroze, and it was all fine. 
problem solved.
Thank you so much SomberNight, it took me a whole moth to solve this issue ...
