### ISSUE TITLE
Cannot send funds

### ISSUE THREAD

**Issue by checkbacklater** [spesmilo/electrum#6913]
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

bad-txns-inputs-missingorspent

I am trying to sen but keep getting the above error message, i am using the current version

**Comment by ecdsa** [comment]
Consider trying to connect to a different server?

**Comment by checkbacklater** [comment]
I have tried numerous different servers with no luck
________________________________

**Comment by ecdsa** [comment]
how did you create the transaction? was it created in Electrum?

**Comment by SomberNight** [comment]
Go to the History tab, and manually delete all transactions there marked as "Local".

**Comment by ecdsa** [comment]
closing, no answer
