### ISSUE TITLE
Error getting TrustedCoin account info

### ISSUE THREAD

**Issue by Spacov** [spesmilo/electrum#6923]
The error occurs whenever I try to send or view.
Latest version 3.3.9
Network connected at elerctrumx1.fujicoin.org and elerctrumx2.fujicoin.org
the same error occurs in the installed and Portable versions.

I appreciate your attention in advance.

**Comment by ecdsa** [comment]
please upgrade to the latest version before you open an issue

**Comment by Spacov** [comment]
As I left in the comment, I am using the latest version 3.3.9.

**Comment by SomberNight** [comment]
There was never a version 3.3.9.
Also, is this for an altcoin? Electrum only supports Bitcoin. Forks of Electrum are independent projects maintained by different people.

**Comment by Spacov** [comment]
I installed it according to the Fujicoin.org website as you can see on the website https://www.fujicoin.org/wallet.php

**Comment by SomberNight** [comment]
again,

> Electrum only supports Bitcoin. Forks of Electrum are independent projects maintained by different people.

That project is unrelated to us.
