### ISSUE TITLE
Cannot reestablish lightning network channel

### ISSUE THREAD

**Issue by chrissv** [spesmilo/electrum#6927]
Using version 4.0.9 portable on Windows 10.
Weeks ago I had established a lightning network channel, and funded it.
I just noticed that Electrum does not successfully reestablish the LN channel.
In the "Channels" tab, it shows disconnected. But every couple of seconds, it quickly flickers like it tries and fails to establish the channel.

Here is an image of the channels tab:

![image](https://user-images.githubusercontent.com/3324281/104113100-58b11500-52c4-11eb-94f7-fc35a22e99cf.png)

I enabled logging, and I see this section of messages appear over and over again:
```
20210110T021133.449200Z |    DEBUG | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | Sending INIT
20210110T021133.578857Z |    DEBUG | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | Sending PING
20210110T021134.386693Z |    DEBUG | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | Sending CHANNEL_REESTABLISH
20210110T021134.388688Z |     INFO | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | channel_reestablish (661112x1125x0): sent channel_reestablish with (next_local_ctn=4, oldest_unrevoked_remote_ctn=3)
20210110T021134.390683Z |    DEBUG | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | Sending CHANNEL_REESTABLISH
20210110T021134.392677Z |     INFO | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | channel_reestablish (feb771e0f9c528fa7c658378c894d461129fa2af8c483f40513b9d653645a14a): sent channel_reestablish with (next_local_ctn=1, oldest_unrevoked_remote_ctn=0)
20210110T021134.393674Z |     INFO | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | channel_reestablish (661112x1125x0): received channel_reestablish with (their_next_local_ctn=4, their_oldest_unrevoked_remote_ctn=3)
20210110T021134.396666Z |     INFO | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | channel_reestablish (661112x1125x0): replayed 0 unacked messages
20210110T021134.440556Z |     INFO | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | saved remote_update
20210110T021134.446627Z |     INFO | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | remote peer sent error [DO NOT TRUST THIS MESSAGE]: unknown channel
20210110T021134.451520Z |     INFO | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | Disconnecting: LightningPeerConnectionClosed()
```

Any ideas?

**Comment by ecdsa** [comment]
The remote node (acinq) does not know the first channel in your list. An error might have occurred during channel creation. In order to tell, we would need to see the part of the log with the channel creation. Was the channel funding transaction ever broadcasted?

**Comment by chrissv** [comment]
Regarding the channel creation, are you talking about when I created the channel weeks ago? If so, I don't have logs from back then.
I remember reading that you need to be careful closing down / deleting a channel so the coins aren't lost.
Is there a way I can close this down so that I could recreate it? I'm OK with a delay in receiving the reserved Bitcoin.

**Comment by ecdsa** [comment]
the error is caused by the first on the list "not yet available". if it was created weeks ago, it is likely that the funding transaction was never in the blockchain, and therefore no funds are actually in the channel. 
Can you check if you see "View funding transaction" in the local menu, and post a screenshot of that?
Also, is the channel opening transaction in your history?

**Comment by chrissv** [comment]
This was the funding for the second channel:
![image](https://user-images.githubusercontent.com/3324281/104130936-825c5180-5341-11eb-969c-22524bc5f9e0.png)

And there is a record of this in my history as well (second line below):
![image](https://user-images.githubusercontent.com/3324281/104130962-aa4bb500-5341-11eb-94d6-dd4ba808d566.png)
You can also see in the first line that I sent a lightning transaction to my phoenix wallet as a test, and it was successful.

**Comment by ecdsa** [comment]
sorry if it was not clear, but I would like to see the funding transaction of the first channel in your list.
as I said before, the second channel is fine.

**Comment by chrissv** [comment]
Right clicking the first channel does not show me an option for "View funding transaction"
![image](https://user-images.githubusercontent.com/3324281/104133898-66ae7680-5354-11eb-8c80-09e837bf7578.png)

By the way, this is the "Details" screen for the first channel:
![image](https://user-images.githubusercontent.com/3324281/104133933-a1181380-5354-11eb-8193-e3684d63c514.png)

Clicking on the "funding outpoint" link yeilds a "not found" error in Electrum, since as was commented, there doesn't look like there was a transaction completed.

**Comment by ecdsa** [comment]
is the funding transaction in your history, as a "local transaction"? 
if not, do you remember having deleted a local transaction?

**Comment by ecdsa** [comment]
also, did you create that channel with 4.0.9, or with an earlier version?
it would be nice to know if the creation was before this commit 0e420e6f9d

**Comment by chrissv** [comment]
Here is the full history of the lightning transactions. I have not deleted any local transactions:
![image](https://user-images.githubusercontent.com/3324281/104135281-50f17f00-535d-11eb-96d7-5064c57898d8.png)

The earlier two open and close channel transactions relate to the two "REDEEMED" channels listed in the first post.

I did all of this activity with 4.0.7 portable.

**Comment by ecdsa** [comment]
Well, without proper logs, I will assume you created the channel with a version that did not have 0e420e6 (earlier than 4.0.9)
You will have to delete the channel manually from the python console:
```
from electrum.lnchannel import ChannelState
chan = [c for c in wallet.lnworker.channels.values() if c.channel_id.hex().startswith("feb771e0")][0]
chan.set_state(ChannelState.REDEEMED)
wallet.lnworker.remove_channel(chan.channel_id)
```

**Comment by chrissv** [comment]
> You will have to delete the channel manually from the python console:

When executing this line:
`chan.set_state(ChannelState.REDEEMED)`

I received the following error:
```
Traceback (most recent call last):
Exception: Transition not allowed: SHUTDOWN -> REDEEMED
```

**Comment by chrissv** [comment]
Should I execute the 4th statement (remove_channel) anyway?

**Comment by ecdsa** [comment]
> Should I execute the 4th statement (remove_channel) anyway?

no, it will not work in that state...

**Comment by chrissv** [comment]
Yes, I remember creating the 1 ACINQ channel that I closed (redeemed) and then I created only 1 other. I do not know why there are 2 ACINQ channels showing up.

There is an option to "force close" the 2nd channel. Should I try that? Would it put my BTC in that channel in peril?

**Comment by ecdsa** [comment]
> There is an option to "force close" the 2nd channel. Should I try that? Would it put my BTC in that channel in peril?

That option will not work either, because the channel was never created.
What you can do is this:
```
chan.set_state(ChannelState.CLOSED)
chan.set_state(ChannelState.REDEEMED)
```
and then the remove_channel statement from above

**Comment by chrissv** [comment]
**Wonderful!**

That seemed to fix the problem. This is what I now see, and it looks 100% appropriate.
![image](https://user-images.githubusercontent.com/3324281/104135968-2bff0b00-5361-11eb-98d9-9e5a495b985c.png)

Thank you all soooo much for your help!

Side Q: I don't know if it had anything to do with my situation, but is there any problem keeping a lightning channel open for long periods of time (months)?

**Comment by ecdsa** [comment]
No, a channel can be kept open indefinitely.
I do not know exactly what happened in your case. 
I guess we will not know without logs.
