### ISSUE TITLE
Ledger library mismatched versions: requires btchip > 0.1.30 - but is failing as 0.1.31 is installed

### ISSUE THREAD

**Issue by techsmyth** [spesmilo/electrum#6928]
Error message:
W | gui.qt.installwizard.InstallWizard | error getting device infos for ledger: Library version for 'ledger' is incompatible. // Installed: 0.1.31, Needed: 0.1.30 <= x < inf // Make sure you install it with python3

Environment:
- OS: Mint 20
- Electrum 4.0.9

Ledger is being detected fine via udev rules.

**Comment by SomberNight** [comment]
Could you open a python interpreter and run these?
```
import hid
import btchip
from btchip.btchipComm import HIDDongleHIDAPI, DongleWait
from btchip.btchip import btchip
from btchip.btchipUtils import compress_public_key,format_transaction, get_regular_input_script, get_p2sh_input_script
from btchip.bitcoinTransaction import bitcoinTransaction
from btchip.btchipFirmwareWizard import checkFirmware, updateFirmware
from btchip.btchipException import BTChipException
```

Do you get any exceptions?

**Comment by techsmyth** [comment]
thanks for the quick follow up.

Responses below - only the btchip.btchip game an error:

Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hid
>>> import btchip
>>> from btchip.btchipComm import HIDDongleHIDAPI, DongleWait
>>> from btchip.btchip import btchip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nsmyth/.local/lib/python3.8/site-packages/btchip/btchip.py", line 25, in <module>
    from .btchipKeyRecovery import *
  File "/home/nsmyth/.local/lib/python3.8/site-packages/btchip/btchipKeyRecovery.py", line 3, in <module>
    import ecdsa
ModuleNotFoundError: No module named 'ecdsa'
>>> from btchip.btchipUtils import compress_public_key,format_transaction, get_regular_input_script, get_p2sh_input_script
>>> from btchip.bitcoinTransaction import bitcoinTransaction
>>> from btchip.btchipFirmwareWizard import checkFirmware, updateFirmware
>>> from btchip.btchipException import BTChipException
>>>

**Comment by techsmyth** [comment]
ok, installed the ecdsa package and that seems to have sorted it!

pip3 install ecdsa

**Comment by SomberNight** [comment]
ahh I see
how did you install Electrum?

**Comment by SomberNight** [comment]
also, how did you install btchip-python?

**Comment by techsmyth** [comment]
running electrum directly from the extracted archive (i.e. not installed)

re btchip, forget exactly where I picked up the need to install that :( Been a struggle to get this working...

**Comment by SomberNight** [comment]
relevant: https://github.com/LedgerHQ/btchip-python/pull/42

**Comment by techsmyth** [comment]
thanks for addressing this, indeed two items - the missing ecdsa dependency and the error message given. Thanks for the nice work.
