### ISSUE TITLE
Why if I open the tab with private keys, there are keys that are generated when I want to receive a transfer to my bitcoin account? That is, the keys in the private tab are the same as in the "Receive" tab

### ISSUE THREAD

**Issue by Gigoshkin** [spesmilo/electrum#6929]
Why if I open the tab with private keys, there are keys that are generated when I want to receive a transfer to my bitcoin account? That is, the keys in the private tab are the same as in the "Receive" tab

**Comment by SomberNight** [comment]
> the tab with private keys

Which tab is that?

> the "Receive" tab

There are no keys in the Receive tab, only addresses and requests.

**Comment by Gigoshkin** [comment]
> > the tab with private keys
> 
> Which tab is that?
> 
> > the "Receive" tab
> 
> There are no keys in the Receive tab, only addresses and requests.

private keys tab
![private_keys](https://user-images.githubusercontent.com/64779512/104133210-81580e00-539b-11eb-9a6d-a4dd1867c578.png)

The key I have overwritten is the same as one of the keys on the private key tab
![key](https://user-images.githubusercontent.com/64779512/104133258-e14eb480-539b-11eb-8cdc-3743b8a407cb.png)

**Comment by ecdsa** [comment]
> Why if I open the tab with private keys, there are keys that are generated when I want to receive a transfer to my bitcoin account? That is, the keys in the private tab are the same as in the "Receive" tab

what else would you expect?

**Comment by ecdsa** [comment]
I guess the confusing part is that the privkey list has two columns, but with segwit addresses you need to enlarge the window to realize it.

**Comment by Gigoshkin** [comment]
> > Why if I open the tab with private keys, there are keys that are generated when I want to receive a transfer to my bitcoin account? That is, the keys in the private tab are the same as in the "Receive" tab
> 
> what else would you expect?

So, in order to get a transfer to my account, I have to send someone a private key?

**Comment by ecdsa** [comment]
> So, in order to get a transfer to my account, I have to send someone a private key?

OMG.... which part of "all your private keys are secret" did you not understand?

**Comment by Gigoshkin** [comment]
> > So, in order to get a transfer to my account, I have to send someone a private key?
> 
> OMG.... which part of "all your private keys are secret" did you not understand?

then if these keys are secret, why are they generated in the "recieve" window ? 
![Screenshot_7](https://user-images.githubusercontent.com/64779512/104135213-1fea6c00-53a8-11eb-9e40-44fed650bba0.png)

**Comment by ecdsa** [comment]
the addresses are not secret.

**Comment by ecdsa** [comment]
enough noob questions
