### ISSUE TITLE
Why, when I press the "maximum" button, it only shows me half of the total amount available?

### ISSUE THREAD

**Issue by Gigoshkin** [spesmilo/electrum#6930]
![Screenshot_6](https://user-images.githubusercontent.com/64779512/104134632-5de59100-53a4-11eb-8569-5a8df9e2ebdb.png)

**Comment by ecdsa** [comment]
because of the fees. 
you can adjust them on the next screen.

**Comment by Gigoshkin** [comment]
> because of the fees.
> you can adjust them on the next screen.

And can you tell me more about where I can change the commission?
