### ISSUE TITLE
clicking BIP21 URI (on e.g. website) on macOS results in "Error parsing URI"

### ISSUE THREAD

**Issue by hrolus** [spesmilo/electrum#6933]
I was find request bug 
Last version, any web browser. Quick request from web or QR code don't working

Bug like
Error parsing URI:
expected string, not PyQt5.QtCore.QByteArray(b'bitcoin:1EirfocnzGTWZDryeKMbt5JH3ERNkVWkjF?amount=0.00151251')

**Comment by hrolus** [comment]
Clarification. The error occurs only on macOS, Windows and Android is working good

**Comment by hrolus** [comment]
Anybody home? QR request broken on MacOS

**Comment by hrolus** [comment]
![Снимок экрана 2021-01-15 в 09 18 38](https://user-images.githubusercontent.com/77299817/104758935-31e55980-5770-11eb-9dbd-917852c94693.png)

**Comment by SomberNight** [comment]
Note: the error dialog only surfaced now because the functionality did not work at all for our binaries for macOS prior to https://github.com/pyinstaller/pyinstaller/pull/5276 - which was merged into pyinstaller 4.1, which we started using for our binaries with Electrum 4.0.7

**Comment by SomberNight** [comment]
Thank you for the report. It should work in the next version.
