### ISSUE TITLE
2 factor authentication not working when sending funds on electrum?

### ISSUE THREAD

**Issue by pnh207** [spesmilo/electrum#6939]
when I try send anyhting it says my google 2fa code is invalid? is there any way i cna get access to my funds this is worrying that 2fa isnt working, and also you cannnot make a normal accoint w/out 2fa it forces u

**Comment by ecdsa** [comment]
> when I try send anyhting it says my google 2fa code is invalid? 

check if your phone's clock needs to be reset. the 2fa code depends on the time

> is there any way i cna get access to my funds this is worrying that 2fa isnt working

if 2fa is not working you can always restore from seed

> and also you cannnot make a normal accoint w/out 2fa it forces u

very sad. so unfair.
