### ISSUE TITLE
Question: Is sending to stealth addresses something we want to support?

### ISSUE THREAD

**Issue by dabura667** [spesmilo/electrum#694]
I have modified my 1.9.8 locally to be able to send to stealth addresses.

I would like to hear everyone's thoughts on stealth addresses and support for sending to them (even if we can't generate our own) for 2.0.

My personal thoughts is that if 2.0 is coming out very soon, I don't think Dark Wallet (the only current implementation) will be ready nor will stealth addresses be set in stone enough to merit putting it into 2.0. If 2.0 is still out maybe 2 months or so, then maybe things will be more concrete by then.

What is everyone's thoughts?

**Comment by ecdsa** [comment]
the gui now allows users to type arbitrary output script (in hex). closing this.
