### ISSUE TITLE
Multisig: Coldcard backup doesn't support multiple derivation paths

### ISSUE THREAD

**Issue by sohomang** [spesmilo/electrum#6940]
Using Specter-Desktop to create a 2-of-2 multisig setup between:
- Coldcard (`m/48'/0'/0'/2'`)
- Electrum hot wallet (`m/1'`)

Here's the .txt backup file I get in `Wallet > Information > Export for Coldcard` :
```
# Exported from Electrum
Name: TEST
Policy: 2 of 2
Format: P2WSH

# derivation: m/1'
J84KF93F: Zpub6ex[...]

# derivation: m/48'/0'/0'/2'
C47BF394: Zpub6uJ[...]
```

Importing it in my Coldcard leads to a failure: `empty deriv`.
Uncommenting  the derivation paths allowed the backup file to be imported successfully.

Is there any way to support this automatically intead of having to manually edit the backup file?

**Comment by SomberNight** [comment]
was this not resolved by https://github.com/spesmilo/electrum/pull/6922 ?

**Comment by sohomang** [comment]
@SomberNight Just tested whats on `master`, works fine 👍
