### ISSUE TITLE
"Successfully send" (unpaid)

### ISSUE THREAD

**Issue by tsneed2000** [spesmilo/electrum#6941]
![electrum transfer](https://user-images.githubusercontent.com/63324939/104626382-76330580-565b-11eb-9cc5-0658f3ea136b.JPG)
(url)

I am trying to send mBTC to another broker. It should be instant or within 30 minutes. The status says unpaid and I have confirmed multiple times that it has been sent. I haven't received anything yet. Is there something I'm missing or do I need to wait for a couple hours?

**Comment by tsneed2000** [comment]
https://www.reddit.com/r/Electrum/comments/kx9d9y/successfully_sent_status_upaid/

I posted this on reddit too. One person replied and said it was in mempool and I can't delete it. Moreover mempool "is deep" right now and he said good luck to me. 

I don't know what that meant because I selected static because it was the cheapest.

If I deposit enough to cover the fees, will the transaction go through??

**Comment by ecdsa** [comment]
your client is not synchronized, see status bar.
it cannot whether it has sent the payment until it is synchronized.

please also read https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by tsneed2000** [comment]
![electrum (attempt 2)](https://user-images.githubusercontent.com/63324939/104633314-95826080-5664-11eb-9d26-181091ac6e15.JPG)

https://mempool.space/tx/14683b389901cd5206df23234c0844eb79cf6162cbce9197bebeef7acd71bbb2

I tried again with a higher fee. It is shown in mempool to have been completed but it is not showing that on Electrum and the money has not arrived to my broker.

**Comment by ecdsa** [comment]
be careful, you paid twice.
again, make sure that your client is synchronized before you take a screenshot.
if necessary, switch to a faster server.
