### ISSUE TITLE
LNBackups INIT features are incorrect

### ISSUE THREAD

**Issue by JulianTosh** [spesmilo/electrum#6943]
My lightning enabled wallet (software version 4.0.9), with two channels, shows a greyed out lightning bolt. When I click on it, it says "Lightning gossip not active. 7849 nodes. 33032 channels". I can see the two channels listed, but each has 0.00 local and remote coins. both status say "funded". Channel status message says "Can send 0. BTC; can receive 0. BTC".

Any tips on how to get the channels active again?

**Comment by ecdsa** [comment]
what is the state of those channels? could you share a screenshot?

**Comment by JulianTosh** [comment]
Screenshot: https://ibb.co/2gJ8k8n

**Comment by ecdsa** [comment]
Everything is normal; these are not channels, but channel backups.
You probably created a backup of your wallet file, and you opened it in place of your wallet.
It is normal not to have gossip active in that case.

**Comment by JulianTosh** [comment]
Ok. This makes sense (it being a backup file), but now I'm faced with how to make this "backup" file a "restore" file - the original file with the channels was destroyed.

**Comment by ecdsa** [comment]
you cannot do that. 
the only thing you can do with the backup is it to request the channels to be force closed.

**Comment by JulianTosh** [comment]
I requested a force-close and got this error message:
https://ibb.co/M8GdxJm

**Comment by ecdsa** [comment]
I can reproduce that. I opened a channel to that node, and tried to force close.

**Comment by ecdsa** [comment]
@JulianTosh this is fixed in github master. 
if you use binaries, please wait until the next release.
