### ISSUE TITLE
Multisig wallet defaults to P2SH with xpubs, but P2WSH with Zpubs

### ISSUE THREAD

**Issue by mmikeww** [spesmilo/electrum#6946]
Tested on 4.0.9 on Windows, and 4.0.2 on Tails. When creating a new 2 of 3 multisig watch-only wallet, by choosing "use key" for all 3 cosigners... 

If you use the `Zpub` version of the 3 extended public keys, then Electrum generates the `bc1` P2WSH addresses. 

However, if you use the same exact extended public keys, but use the `xpub` format, then Electrum generates the `3`prefix P2SH addresses. 

I think that Electrum should offer the user the choice for what type of addresses should be generated when creating this multisig wallet, instead of just using defaults that the user cannot change.

I confirmed this against Caravan:  
https://unchained-capital.github.io/caravan

**Comment by ecdsa** [comment]
the distinction between xpub and Zpub is not a different format, it is a different purpose.
the purpose of Zpub is to create p2wsh wallets.
