### ISSUE TITLE
Kivy gui doesn't show bump fee options

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#6950]
So sometimes the kivy gui does not show bump fee options for unconfirmed transactions even though it should be showing them. You can tap on the transaction on the history tab and then it should display a new screen with an options button in the bottom left. But that's not happening for some reason or the other. This was reported on reddit and I've seen it myself now. In my case the transaction turned local and then unconfirmed again so that may have something to do with it. When it was local the option was there but now it's no longer there. CPFP should be an option for such a transaction.

electrum version 4.0.9

**Comment by SomberNight** [comment]
Does the issue persist through closing and reopening the tx details dialog?

**Comment by AbdussamadA** [comment]
yes

**Comment by AbdussamadA** [comment]
looking at the code i see that the bump fee option is enabled only if can_rbf or can_bump is true. i was under the mistaken impression that you guys had unified the options for cpfp and rbf. the kivy version does not check for cpfp at all.

**Comment by ecdsa** [comment]
so, the transaction was not rbf?

**Comment by AbdussamadA** [comment]
yes it's rbf but it's an incoming one. cpfp should be available

**Comment by ecdsa** [comment]
see #5507
