### ISSUE TITLE
sending bitcoin

### ISSUE THREAD

**Issue by tuluh** [spesmilo/electrum#6952]
I did not know you had to save the code from the google authenticator and when i go to send money it says i need it, it also says to restore youre wallet to be able to request a new qr code, and i did that i have my seed saved but i dont know how to request a new code please let me know as i dont know what else to do

**Comment by ecdsa** [comment]
if google authenticator is too difficult for you, use a standard wallet.

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/issues/5035#issuecomment-457876314

> Restore from seed, and choose to `keep` 2FA enabled, and check `I have lost my Google Authenticator account`

to see the QR code again

**Comment by tuluh** [comment]
> [#5035 (comment)](https://github.com/spesmilo/electrum/issues/5035#issuecomment-457876314)
> 
> > Restore from seed, and choose to `keep` 2FA enabled, and check `I have lost my Google Authenticator account`
> 
> to see the QR code again 

where do I check i have lost my google authenticator account i did the seed and all that other stuff but never seen something like that to check

**Comment by ecdsa** [comment]
@tuluh we cannot help you if you do not describe your situation with more details. you should not assume that we know what you are experiencing.

**Comment by tuluh** [comment]
i did state my problem im tryna send bitcoin but my wallet asks for the password and the google authenticator code wich i did not save as i didnt know you needed to save it and it says to request a new code if lost the old one and i dont know how to pull the new code back up and someone told me to click lost the qr code but i dont see no where that says that
