### ISSUE TITLE
PAYMENT  unconfirmed

### ISSUE THREAD

**Issue by TUPAK007** [spesmilo/electrum#6953]
[http://prntscr.com/x72h36](url)    OR THIS ONE http://prntscr.com/x731ci

I have a problem with the transmission of payments is not made is waiting for 2 days now I have this thing will withdraw my money or newer if the palace address expires no more payment

**Comment by ecdsa** [comment]
https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by TUPAK007** [comment]
THX
