### ISSUE TITLE
Electrum won't open

### ISSUE THREAD

**Issue by goyaounds** [spesmilo/electrum#6954]
Hi there,

I have updated to the most recent version of electrum on OSX (Catalina 10.15.5), but the Electrum app won't open. The app bounces for a while then crashes. How can I fix this? (Not a tech expert here, someone set it up for me)

Thanks

**Comment by SomberNight** [comment]
Try running with the `-v` option from terminal to see some logs; hopefully there is a clue there:
`Electrum.app/Contents/MacOS/run_electrum -v`
So e.g. if you have the `Electrum.app` file in `/Applications`:
```
$ /Applications/Electrum.app/Contents/MacOS/run_electrum -v
```
