### ISSUE TITLE
Request payment issue

### ISSUE THREAD

**Issue by hrolus** [spesmilo/electrum#6956]
![Снимок экрана 2021-01-15 в 09 18 38](https://user-images.githubusercontent.com/77299817/105231962-bcff8e80-5b78-11eb-972d-8bf7b1b73bbc.png)

This is normal? Quick payment link dont working. Electron cash everything OK

**Comment by SomberNight** [comment]
please don't open duplicate issues (https://github.com/spesmilo/electrum/issues/6933)

this is a bug, yes; anyone can submit a fix
