### ISSUE TITLE
Payment btc electrum 4.0.9

### ISSUE THREAD

**Issue by TUPAK007** [spesmilo/electrum#6957]
I can't make payments for four days, this thing shows me what to do

![Screenshot_1](https://user-images.githubusercontent.com/77587685/105232083-8e7db580-5b70-11eb-8f9e-75549e2590df.png)

**Comment by SomberNight** [comment]
You can right-click>`Remove` those local transactions.

**Comment by TUPAK007** [comment]
> You can right-click>`Remove` those local transactions.

I know this, but how can I pay because I don't pay anymore?

**Comment by SomberNight** [comment]
I don't understand. Please elaborate.

**Comment by TUPAK007** [comment]
I tried and other payments make me the same thing the payment does not leave the first time it shows me unconfirmed after which what you see in the picture what to do

**Comment by SomberNight** [comment]
The mempool has lots of transaction. Bitcoin nodes with a default mempool size of 300 MBs are regularly dropping 1 sat/byte transactions now.
Use a higher fee.

**Comment by TUPAK007** [comment]
I will try this too but I haven't had any problems so far, thank you

**Comment by TUPAK007** [comment]
what else can I do that I tried 5sat  10sat  the same does not leave the payment you advise me to do

**Comment by TUPAK007** [comment]
I would like to know how many villages to use before any value went to the village now what is happening

**Comment by ecdsa** [comment]
@TUPAK007 please document yourself on how the bitcoin mempool works.
it is not our job to answer questions like that.

**Comment by TUPAK007** [comment]
I managed with 10 villages started paying thanks for the support  in 24h thx 4 support close plz
