### ISSUE TITLE
Network One Server Configuration

### ISSUE THREAD

**Issue by dgyg** [spesmilo/electrum#6967]
At the moment it is not possible to configure a electrs backend server using Tor in the GUI.

According to 

  https://github.com/romanz/electrs/blob/master/doc/usage.md#electrum-client 

a ``:t`` must be added in the _Server_ field:

![electrum](https://user-images.githubusercontent.com/7886722/105752601-66f76600-5f3f-11eb-8bf4-6ad6ac917820.png)

That only works once after configuring the proxy server on the next tab and clicking _Close_ afterwards. 

However the ``:t`` part is not saved in the preferences for the next application start.

**Comment by SomberNight** [comment]
What version of Electrum are you using?
There was a related fix in 4.0.4: https://github.com/spesmilo/electrum/commit/292016d28375c8412c790ee77efd34f7c38b1c33

**Comment by dgyg** [comment]
Sorry, my mistake. I was not using the latest 4.x version.
