### ISSUE TITLE
verify checksum of bitcoin whitepaper before writing it to disk.

### ISSUE THREAD

**Issue by yeschacha** [spesmilo/electrum#6974]
Commit : [d7515b936e32efc02f6b4b0dd97b8520b5c447a7](https://github.com/spesmilo/electrum/commit/d7515b936e32efc02f6b4b0dd97b8520b5c447a7)

Since the source of data is not trusted its better to do at-least 2 checksums like SHA256, SHA512, MD5 before writing the file to disk.

Edit : @SomberNight @ecdsa

**Comment by ecdsa** [comment]
the transaction hash is verified
