### ISSUE TITLE
btc not showing

### ISSUE THREAD

**Issue by uazikfw** [spesmilo/electrum#6978]
Hello just sent bitcoin but it is not showing in my balance as unconfirmed transaction!!

It was showing unconfirmed transactions before, so why it is not working??????

**Comment by SomberNight** [comment]
Hi. This is not enough information to help.
Maybe show a screenshot of the History tab.

**Comment by TUPAK007** [comment]
THE SAME MY   LOOK http://prntscr.com/xuyh81

**Comment by ecdsa** [comment]
closing, OP not answering
