### ISSUE TITLE
Electrum stop it work it 

### ISSUE THREAD

**Issue by TUPAK007** [spesmilo/electrum#6979]
Hello . 
I can't send a payment, I'm waiting for 48 hours and I didn't set anything on 32sat enough to put before 2sat went
http://prntscr.com/xu1v2k  32 sat
http://prntscr.com/xu35vl    20sat
what settings to make as a village to put I try everything that happens I lose ....

**Comment by SomberNight** [comment]
learn about fees
https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do
