### ISSUE TITLE
Electrum crash payments

### ISSUE THREAD

**Issue by TUPAK007** [spesmilo/electrum#6980]
I'm still trying to pay, the money isn't going away, what is to be done, I tried different villages 2sat-32sat nothing the same as you can see, the picture remained for 48 hours, 

http://prntscr.com/xus9wo
Thx

**Comment by ecdsa** [comment]
please learn how bitcoin and RBF works, and increase the fees of your transactions.

Please stop posting issues here. 
We are not here to explain you how bitcoin works, we are here to fix bugs.
