### ISSUE TITLE
Electrum not work it...

### ISSUE THREAD

**Issue by TUPAK007** [spesmilo/electrum#6982]
Hello ,

I have blocked payments I can no longer remove or add what you advise me to do ..
I tried 10sat 20 sat village 30sat  village does not leave the payment remains uncofirmed ..... 
. thank you for your support

**Comment by SomberNight** [comment]
Stop spamming the issue tracker.
Learn about how fees in bitcoin work. Read the links already provided in your previous issues.

https://github.com/spesmilo/electrum/issues/6953
https://github.com/spesmilo/electrum/issues/6957
https://github.com/spesmilo/electrum/issues/6979
https://github.com/spesmilo/electrum/issues/6980
