### ISSUE TITLE
Electrum wont let me change the transaction fee/send bitcoin

### ISSUE THREAD

**Issue by staybaked** [spesmilo/electrum#6988]
Hi,

I´ve recently startet using Electrum as my BitCoin wallet. The problem is when I try to send BitCoin, I can only send a very small amount of my accounts balance(As you guys can see from the screenshot) . I´ve tried clicking on send and then change the fee but that also wont let me send more BitCoin.

Please help me.

Best regards staybaked
![Screenshot Electrum](https://user-images.githubusercontent.com/78453596/106679628-62752200-65bd-11eb-9813-ac0d56631736.png)

**Comment by SomberNight** [comment]
The difference between your balance and the "max" amount is due to miner fees + 2fa fees

You can see this if you click "Pay..." (and in detail if after that you also click "Advanced").

-----

from https://bitcoinelectrum.com/frequently-asked-questions/#why-am-i-being-told-that-i-have-insufficient-funds
> **Miner Fees**: Generally when people speak of transaction fees they mean miner fees that go to the bitcoin miner that mines the block containing your transaction. Miner fees apply to all wallet types. To view miner fees in Electrum see the article here.

> **2fa fees**: If your wallet is a 2 factor authentication (2fa) wallet then there are additional fees that go to the cosigning company trusted coin. You can tell if you have this type of wallet by going to wallet > information. If you have a 2fa wallet you can find out the specific amount in fees by clicking on ‘pay’ and then ‘advanced’ on the send tab. 2fa fees show up as a blue highlighted output in the transaction preview window that appears. You can learn more about these fees by clicking on the little blue shield icon in the bottom right of the main electrum window. Note that the fees are prepayment for a batch of outgoing transactions.If you don’t want to pay these fees restore your wallet from seed. To begin the process go to file > new/restore, enter a unique and meaningful filename and click next. Follow on-screen instructions for the rest. To avoid 2fa fees be sure to choose to disable 2fa protection when asked.

see https://api.trustedcoin.com/#/electrum-help

**Comment by staybaked** [comment]
So, since I´m pretty new to Crypto, I can´t change that? So this max amount Electrum is proposing is final?
I also don´t have an "advanced" button after I clicked "Pay".

**Comment by SomberNight** [comment]
>  I also don´t have an "advanced" button after I clicked "Pay".

Please make a screenshot.

> So, since I´m pretty new to Crypto, I can´t change that? So this max amount Electrum is proposing is final?

You can configure miner fees after you click "Pay..." (using slider) or in more detail if you click "Advanced".

Re 2FA fees, you can choose not to use a 2FA wallet if you don't want to pay them. Re your coins already in there, you can move them out if you disable 2FA; see paragraph above.

**Comment by staybaked** [comment]
I see the slider with whom I can adjust the miner fee, but even when, as you can see in the screenshot the miner fee is at 0.0000259, I can´t send more BitCoin.

I´m really loosing it rn. 



![Screenshot Electrum](https://user-images.githubusercontent.com/78453596/106724723-d983d800-6608-11eb-9f96-644d7a6b10af.png)

**Comment by staybaked** [comment]
Hi,
So I understood the 2fa now, but now that I have a non 2fa wallet I don´t know how to get my BitCoin from my old wallet into this new one. 

Pls help

Thx in advance

**Comment by staybaked** [comment]
I think I understand it now, thanks for your time have a nice day.
