### ISSUE TITLE
2FA (or XFA) for lightning spends

### ISSUE THREAD

**Issue by ArbenKarb** [spesmilo/electrum#6990]
Feature request:

Build some sort of Multifactor authentication to create authorization levels for balances in lightning channels sourced from Multisig wallets, to mirror multisig Setup onchain.

**Comment by ecdsa** [comment]
Thank you, but this is not really useful. 
The reason why we do not have that feature is not because we did not think about it. :-)

Closing this, because we are trying to keep the number of open issues to a reasonable level

**Comment by ArbenKarb** [comment]
Understand re open issues - but why did you conclude that it wouldn't be useful? I guarantee you this will be necessary if lightning should become a thing, especially in the corporate world. And electrum is in the pole position to serve as bitcoin tool in the corporate world

**Comment by SomberNight** [comment]
The feature would be useful; I think @ecdsa meant that re the issue itself.
We do not yet know how cryptographicly enforced multi-factor auth could be implemented for LN payments.

Note that 2FA here is only useful if it is cryptographically ensured, as it is with e.g. Electrum's on-chain 2FA wallets.
