### ISSUE TITLE
Android app crashes if a Yubikey is connected to the USB port

### ISSUE THREAD

**Issue by ghost** [spesmilo/electrum#6991]
I use a Yubikey for 2FA. If I want to use the Yubikey 2FA app to confirm a bitcoin purchase, I need to have the Yubikey inserted into the lightning drive. However, when I do this, Electrum crashes and the token expires before I am able to reopen the app.

**Comment by SomberNight** [comment]
probably same as https://github.com/spesmilo/electrum/issues/6907

**Comment by SomberNight** [comment]
to clarify, by "lightning drive", do you mean usb port?

**Comment by cttillman** [comment]
> to clarify, by "lightning drive", do you mean usb port?

Yeah

**Comment by SomberNight** [comment]
closing as duplicate in favour of https://github.com/spesmilo/electrum/issues/6907

**Comment by checo2** [comment]
``
