### ISSUE TITLE
can't send bitcoin

### ISSUE THREAD

**Issue by mcm2424** [spesmilo/electrum#6996]
I am trying to send bitcoin and keep getting msg saying no interface to send request on. I've tried sending to multiple places to make sure it wasn't on their end. Please advise. also ive tried updating and it's up to dATE.

**Comment by SomberNight** [comment]
Please enable [debug logging](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) and upload your log.

**Comment by mcm2424** [comment]
I have no idea what that means.

**Comment by mcm2424** [comment]
ARE YOU TALKING ABOUT ON ELECTRUM OR ON HERE?

**Comment by mcm2424** [comment]
i HAVE WINDOWS.

**Comment by mcm2424** [comment]
i debugged the logs and still not working.

**Comment by SomberNight** [comment]
- In Electrum, go to Tools menu > Preferences > General tab, and tick “Write logs to file”.
- Restart Electrum.
- Try sending bitcoin (broadcasting a transaction) again, to reproduce the error.
- On your computer, go to this folder: `%APPDATA%/Electrum/logs`, and get the last file you see there, and upload it as part of a comment here on GitHub.

**Comment by TUPAK007** [comment]
> I am trying to send bitcoin and keep getting msg saying no interface to send request on. I've tried sending to multiple places to make sure it wasn't on their end. Please advise. also ive tried updating and it's up to dATE.

everything you sent will arrive later I had and I have this problem and I lost the payments you will lose the money if where you sent it will not recognize the payment do not try to make more payments waiting for a new update or the bug to disappear

**Comment by SomberNight** [comment]
> I am trying to send bitcoin and keep getting msg saying no interface to send request on

I think the most likely reason for this is that your client is not connected to the network. Make sure the orb/circle in the bottom right is either green or blue.

**Comment by mcm2424** [comment]
How do i restart electrum?
*Mitchell C. Maloney*

**Comment by mcm2424** [comment]
the orb is blue btw and im now getting a msg now that say's no interface
but when i send payments they can't be confirmed i've tried two different
places.
*Mitchell C. Maloney*

**Comment by mcm2424** [comment]
it say's unconfirmed parent please help me get this back to normal .
*Mitchell C. Maloney*

**Comment by chios70** [comment]
[electrum_log_20210205T231059Z_4436.log](https://github.com/spesmilo/electrum/files/5935787/electrum_log_20210205T231059Z_4436.log)

**Comment by mcm2424** [comment]
what is that?

*Mitchell C. Maloney*

**Comment by mcm2424** [comment]
i can't find this file %APPDATA%/Electrum/logs

**Comment by mcm2424** [comment]
> > I am trying to send bitcoin and keep getting msg saying no interface to send request on. I've tried sending to multiple places to make sure it wasn't on their end. Please advise. also ive tried updating and it's up to dATE.
> 
> everything you sent will arrive later I had and I have this problem and I lost the payments you will lose the money if where you sent it will not recognize the payment do not try to make more payments waiting for a new update or the bug to disappear

`thank you i will stop using electrum

**Comment by chios70** [comment]
ok I'm sorry

Il giorno sab 6 feb 2021 alle ore 00:45 mcm2424 <notifications@github.com>
ha scritto:
