### ISSUE TITLE
I can not make a payment from Electrum

### ISSUE THREAD

**Issue by roor210** [spesmilo/electrum#7000]
I have had real   problems using Electrum.   I have been trying to make a payment on orders for some days with out success.   A first when making an order on electrum i get the following message: 
BestEffortRequestFailed('no   interface to do request on... gave up.') 
I dont know what happened or what I  did but after many attempts the payment was made. I have made 3 payments but   they were so long getting to the market place that the orders were cancelled   Today i got the following message and still no payments have been made. The server returned an error when broadcasting the   transaction.   Consider trying to connect to a different server, or updating Electrum.   Transaction could not be   broadcast due to dust outputs.`   
I have update electrum to 4.0.9 and have tried a different server with no   success   
What am I doing wrong? Can   you help me or have any suggestions?  
 Thanks for your help. it is appreciated   roor210

**Comment by SomberNight** [comment]
> BestEffortRequestFailed('no interface to do request on... gave up.')

I think the most likely reason for this is that your client was not connected to the network. Make sure the orb/circle in the bottom right is either green or blue.

-----

>>  Transaction could not be broadcast due to dust outputs

See https://bitcoinelectrum.com/frequently-asked-questions/#why-am-i-getting-the-error-message-dust-outputs

> Why am I getting the error message "dust outputs"?
>
> This means you are trying to send very small amounts of bitcoin i.e. less than 5140 satoshis worth. In practice it usually means you are confusing bitcoin (btc) with millibitcoin (mbtc) which is 1/1000th of a bitcoin. So please change the unit of account in electrum to btc and try again. To change the unit of account go to tools > preferences > general tab > base unit option and set it to btc. Then try to send money again keeping in mind that you are now dealing with bitcoin and not millibitcoin.

**Comment by roor210** [comment]
Thank you for your advice. It worked! Great
