### ISSUE TITLE
extra commissions Chios70

### ISSUE THREAD

**Issue by chios70** [spesmilo/electrum#7002]
![extra commissions'](https://user-images.githubusercontent.com/78623624/107096555-54b4dc00-680b-11eb-90dd-1d1593bbca62.JPG)
![extra commissions'2](https://user-images.githubusercontent.com/78623624/107096601-6c8c6000-680b-11eb-8690-af9089be1b78.JPG)
It is not possible to pay all these extra fees, they can be refunded!
my address; bc1q2x3p9dxyk46vackzakvx6mvjn4457yr7fv0c3hm electrum

**Comment by SomberNight** [comment]
I don't understand. What are you trying to say?
The fees you pay when making a transaction go to the miners, not to the Electrum developers.

**Comment by chios70** [comment]
but before I paid much less, how should I set the commission? static,
mempool ...

Il giorno ven 5 feb 2021 alle ore 23:54 ghost43 <notifications@github.com>
ha scritto:

**Comment by SomberNight** [comment]
Learn about bitcoin fees. Maybe start here https://en.bitcoin.it/wiki/Miner_fees

**Comment by chios70** [comment]
Il giorno ven 5 feb 2021 alle ore 23:59 Davide Podda <dvdpdd@gmail.com> ha
scritto:
