### ISSUE TITLE
cant send bitcoin

### ISSUE THREAD

**Issue by mcm2424** [spesmilo/electrum#7003]
i can't send bitcoin yesterday i was getting a different msg but now it lets me send the payment but receiver can't confirm it says parent unconfirmed ive tried multiple places that ive sent before no luck. i'm not a programmer so please give simple instructions. also, how do i restart electrum?

**Comment by ecdsa** [comment]
Electrum has an option to spend only confirmed coins. If you enable it, it will not allow you to create a transaction with unconfirmed parent. 

If that explanation is too technical for you, please learn how bitcoin works. The purpose of this website is not to educate users by answering their questions.
