### ISSUE TITLE
Balance in fiat

### ISSUE THREAD

**Issue by phone3355** [spesmilo/electrum#7006]
I have 4.0.5 version and I dont see my balance in FIAT

I have still: No FX rate available

How to fix it? 

I changed is settings fiat currency and source and still nothing.

**Comment by SomberNight** [comment]
First of all, please update to the latest version first, before opening an issue.

Second, please search existing issues. e.g. https://github.com/spesmilo/electrum/issues/6407 https://github.com/spesmilo/electrum/issues/6547 https://github.com/spesmilo/electrum/issues/5404#issuecomment-498450905

As in those issues, try changing the rate provider, and keep in mind that if you use a VPN or Tor, some providers ban those.
