### ISSUE TITLE
fAILED TO POST "pAY TO" LINE.(then lists wallet address),  Exception('invalid address or script.')

### ISSUE THREAD

**Issue by ElCuco68** [spesmilo/electrum#7007]
![eLECTRUM BUG REPORT](https://user-images.githubusercontent.com/78689775/107148846-743f2800-6923-11eb-9961-315a2eae47e7.JPG)

**Comment by ElCuco68** [comment]
This happens when I leave "amount" filled out or not

**Comment by ecdsa** [comment]
I guess you made a typo in the address

**Comment by ElCuco68** [comment]
No, me and the addressee have been over it numerous times. It's no typo.

**Comment by ecdsa** [comment]
please paste the address here, and we will check

**Comment by ElCuco68** [comment]
Hi Ecdsa!  The address is actually on both the "Pay to" line, and in thr "Warning" box.

**Comment by ElCuco68** [comment]
Why was this closed?

**Comment by ecdsa** [comment]
because I am 99% sure you have a typo in the address. 
I don't feel like copying it by hand from your screenshot; the minimum you could have done is to paste it.
