### ISSUE TITLE
UnknownTxinType: cannot construct witness for txin_type: unknown

### ISSUE THREAD

**Issue by masterleo123** [spesmilo/electrum#7009]
Hey ! When I try to send some btc out of my wallet this happend, 
"UnknownTxinType: cannot construct witness for txin_type: unknown"
How can I fix this ?

**Comment by SomberNight** [comment]
What version of Electrum are you using?

(assuming you are using the Qt GUI) in the menubar, in `Wallet`>`Information`,
what is "wallet type" and "keystore type" and "script type"?

Also, do you get a full traceback when getting this error? Or could you upload a screenshot maybe?

**Comment by masterleo123** [comment]
![image](https://user-images.githubusercontent.com/78707794/107213755-cefa8180-6a00-11eb-92e8-419cdff5a353.png)

**Comment by masterleo123** [comment]
![image](https://user-images.githubusercontent.com/78707794/107213801-e46fab80-6a00-11eb-8167-6a65d8124609.png)

**Comment by SomberNight** [comment]
Thanks for the screenshots.

Could you please [enable debug logging](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging), and then reproduce the error, and upload a log file?
