### ISSUE TITLE
SIGSEGV on exit sometimes

### ISSUE THREAD

**Issue by af7567** [spesmilo/electrum#7012]
Currently using Electrum 4.0.9 on slackware64-current, but this has been happening for a few years. I am sure I commented on a bug about it before but I can't find it anywhere.
When exiting Electrum, about 20% of the time it segfaults and I find a core dump in my home directory. I have tried exiting using the menu, ctrl-q, or just closing the window. I have tried leaving it running for a while before exiting and also exiting just after opening. I can't find anything that triggers it, it just seems random and I usually don't know about it until I notice the coredump.

It seems to be something to do with Qt from the backtrace:
```
#0  0x00007ffff7f15560 in PyCFunction_Type () from /usr/lib64/libpython3.9.so.1.0
#1  0x00007ffff24665e1 in ?? () from /usr/lib64/python3.9/site-packages/PyQt5/QtCore.so
#2  0x00007ffff50b2498 in ?? () from /usr/lib64/python3.9/site-packages/PyQt5/sip.so
#3  0x00007ffff246632c in ?? () from /usr/lib64/python3.9/site-packages/PyQt5/QtCore.so
#4  0x00007ffff7ca84a7 in ?? () from /usr/lib64/libpython3.9.so.1.0
#5  0x00007ffff7de6ff7 in ?? () from /usr/lib64/libpython3.9.so.1.0
#6  0x00007ffff7d81400 in Py_FinalizeEx () from /usr/lib64/libpython3.9.so.1.0
#7  0x00007ffff7d81b38 in Py_Exit () from /usr/lib64/libpython3.9.so.1.0
#8  0x00007ffff7d8607f in ?? () from /usr/lib64/libpython3.9.so.1.0
#9  0x00007ffff7d874bb in PyRun_SimpleFileExFlags () from /usr/lib64/libpython3.9.so.1.0
#10 0x00007ffff7da4238 in Py_RunMain () from /usr/lib64/libpython3.9.so.1.0
#11 0x00007ffff7da46d3 in Py_BytesMain () from /usr/lib64/libpython3.9.so.1.0
#12 0x00007ffff784492a in __libc_start_main () from /lib64/libc.so.6
#13 0x000000000040107a in _start ()
```

**Comment by SomberNight** [comment]
maybe related: https://github.com/spesmilo/electrum/issues/6889

**Comment by SomberNight** [comment]
Closing this in favour of the other one.
