### ISSUE TITLE
Why does electrum sucks?

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7013]
We can't completely rely on reliability or privacy of random servers,

We can't tell electrum to use a preferred list of "trusted" servers.

Sorry for the clickbait title but that's by far the biggest problem I have with it.

Besides that, it's simply the best ;)

related
https://github.com/spesmilo/electrum/issues/6402

**Comment by ecdsa** [comment]
thank you, but if that feature is your priority then why don't you write a pull request for it?
