### ISSUE TITLE
Any version requirement for secp256k1? (minimum required)

### ISSUE THREAD

**Issue by ar-jan** [spesmilo/electrum#7014]
I am [packaging](https://github.com/void-linux/void-packages/pull/28305) a new version of Electrum for Void Linux. In Void Linux `secp256k1` is available via the [libbitcoin/secp256k1](https://github.com/libbitcoin/secp256k1), because there's a preference for using released versions. The current `libbitcoin/secp256k1` release dates to August 2017 (and the last commit included dates to Dec 28, 2016).

Would that version work for Electrum? Or are there new features it relies on? I can open and create wallets using that version of secp256k1, but I don't know if there are other areas which might function incorrectly.

**Comment by SomberNight** [comment]
> version requirement for secp256k1
> the last commit included dates to Dec 28, 2016

uh that's really old. Try running the unit tests (of Electrum) with it.
In terms of features, I think if the tests pass, it should be ok.
I don't know if there ever were serious bugfixes etc however.

Note that when taproot activates on mainnet, we might require a libsecp256k1 that has the BIP340 code.

**Comment by SomberNight** [comment]
maybe related: https://github.com/spesmilo/electrum/issues/7021

**Comment by SomberNight** [comment]
I'll close this as there is nothing to be done here.
Maybe when the libsecp project starts tagging versions (https://github.com/bitcoin-core/secp256k1/issues/286), we can properly solve this. Until then, I expect the status quo remains the same: if the tests pass, it is considered good enough.
