### ISSUE TITLE
change that never returned to my wasllet 

### ISSUE THREAD

**Issue by TRTCz** [spesmilo/electrum#7015]
is:issue is:open 20201003T020854.331109Z |    DEBUG | util.profiler | WalletStorage.write 0.0535 not appearing in my wallet idk how much of the log is safe to post

**Comment by SomberNight** [comment]
In the History tab, right click the transaction in question and then choose `View Transaction`. Maybe post a screenshot of that window.

**Comment by TRTCz** [comment]
sry i didnt see this email till now hell i didnt think i succeeded at
posting anything
