### ISSUE TITLE
Crash at exit (sip.cp37-win32.pyd error)

### ISSUE THREAD

**Issue by VVallterBreneka** [spesmilo/electrum#7016]
From time to time Electrum crashes at exit (X button)
Win7 x64 Ultimate, Electrum 4.0.9

  Nazwa zdarzenia problemu:	APPCRASH
  Nazwa aplikacji:	electrum-4.0.9.exe
  Wersja aplikacji:	0.0.0.0
  Sygnatura czasowa aplikacji:	00000000
  Nazwa modułu z błędem:	sip.cp37-win32.pyd
  Wersja modułu z błędem:	0.0.0.0
  Sygnatura czasowa modułu z błędem:	5f4a3213
  Kod wyjątku:	c0000005
  Przesunięcie wyjątku:	00004cf6
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.1
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	0a9e
  Dodatkowe informacje 2:	0a9e372d3b4ad19135b953a78882e789
  Dodatkowe informacje 3:	0a9e
  Dodatkowe informacje 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by SomberNight** [comment]
Thanks for the report. Please always search existing issues before opening a new one.
Probably duplicate of https://github.com/spesmilo/electrum/issues/6889

**Comment by VVallterBreneka** [comment]
Should I move the issue to the #6889?

**Comment by SomberNight** [comment]
No, it is already referenced from there.
Just click "subscribe" in #6889 so that you get emails about progress and can potentially answer questions.

**Comment by VVallterBreneka** [comment]
Thanks!
