### ISSUE TITLE
Electrum 4.0.9 hangs trying to view Trezor transactions

### ISSUE THREAD

**Issue by DavidVeksler** [spesmilo/electrum#7017]
4.0.9, M1 Mac running Big Sur 11.2 

When I try to view any transactions in my bech32 Trezor wallet, Electrum hangs.

Non-Trezor wallets are fine.

**Comment by SomberNight** [comment]
Thanks. This is probably a duplicate of https://github.com/spesmilo/electrum/issues/6914
