### ISSUE TITLE
The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.  insufficient fee.

### ISSUE THREAD

**Issue by Rklosnet** [spesmilo/electrum#7018]
Summary: In total six transactions are stuck. Four of them are payments I made. I am on a timer and getting desperate..

Hello. I always mix my coins whenever I pay someone with them, when I don't know the person well and don't want them to see my wallet etc. I have four orders open with a mixing service. After three days the orders are canceled, so when my bitcoin arrive too late I think I lost them. I sometimes sent Bitcoin for 5 sat/byte and they get confirmed in one night. Now I sent orders with 50, 40, 50 and 125 sat per byte and they are not confirmed after more than 24 hours. I tried everything to increase the fee, but nothing works. I could only increase the fee of my last payment, hence it's 125 sat/byte but because the rest is stuck in front, even this transaction does not confirm after hours. I literally did everything I could find online to increase the fee, all I get are more error messages. 

One tutorial says I need to look up the change address and press "spend from" but it doesn't give me the option, because there is 0 btc on the change address since it never arrived. I also dissabled the "spend only confirmed coins", doesn't matter. When I try the increase fee option, I get the error message like in the title of this post. 

I am getting desperate. Bitcoin can be so frustrating and complicated. Hope someone can help. I am paying tens of euro's on fees, and they're are still not confirming.

Thanks

Roy

P.s. Yes I have the latest version and I tried connecting to several different servers

**Comment by SomberNight** [comment]
> The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.
> insufficient fee

The interesting bit is `insufficient fee`. You can [check the debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) for more info, specifically exact numbers on how much you are paying and how much you should be paying to be able to replace your existing transactions.
In short, you probably have a chain of unconfirmed txs, and to be able to replace the older ones you need to pay a lot of fees. This is how RBF (BIP-0125) works.

**Comment by Rklosnet** [comment]
> > The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.
> > insufficient fee
> 
> The interesting bit is `insufficient fee`. You can [check the debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) for more info, specifically exact numbers on how much you are paying and how much you should be paying to be able to replace your existing transactions.
> In short, you probably have a chain of unconfirmed txs, and to be able to replace the older ones you need to pay a lot of fees. This is how RBF (BIP-0125) works.

Hi thanks for the fast reply! I am a total noob and the logs are overwhelming. I am not really sure what to look for.
Is this what you mean?

20210209T210148.748269Z |     INFO | network | fee_estimates {25: 106005, 10: 123066, 5: 134798, 2: 141792}
20210209T210148.883343Z |     INFO | network | fee_estimates {25: 106005, 10: 123066, 5: 134798, 2: 141792}
20210209T210149.004189Z |     INFO | network | fee_estimates {25: 106005, 10: 123066, 5: 134798, 2: 141792}
20210209T210149.016970Z |     INFO | network | fee_estimates {25: 106005, 10: 123066, 5: 134798, 2: 141792}
20210209T210150.503023Z |     INFO | network | fee_estimates {25: 106005, 10: 123066, 5: 134798, 2: 141792}
20210209T210152.144559Z |     INFO | network | fee_estimates {25: 106005, 10: 123066, 5: 134798, 2: 141792}

**Comment by SomberNight** [comment]
> I am not really sure what to look for.

search the logs for `DO NOT TRUST THIS MESSAGE` (which is printed before the error message)

**Comment by Rklosnet** [comment]
> > I am not really sure what to look for.
> 
> search the logs for `DO NOT TRUST THIS MESSAGE` (which is printed before the error message)

Can you e-mail me on rknet@cmail.nu what I should look for? I only see "Do not trust this message" in your message.

**Comment by SomberNight** [comment]
yes, that is what you should look for :P it says do not trust, because that error message itself is not to be trusted in general

**Comment by Rklosnet** [comment]
Ah I see :p well to be sure I searched for it prior, but there is no such text in the log file "electrum_log_20210209T205846Z_19272" When I look for 'trust' only I only get Trustedcoin. There is no other text with trust in it :/

**Comment by Rklosnet** [comment]
Update: I don't know why but all transactions went through last night. So everything is OK. Faith in the network RESTORED
