### ISSUE TITLE
Cannot connect to network. Using 1.9.7 in Windows Virtual Machine on Mac. 

### ISSUE THREAD

**Issue by cph77** [spesmilo/electrum#7019]
I am using version 1.9.7 because I have an old seed that apparently needs pre-1.9.8 in order to recover my wallet.

I have tried disabling auto connect and cycling through the other servers. Port is 50002. Protocol is SSL and Proxy is none. I have turned off firewalls on Windows and Mac. Does anyone have a suggestion? Your help is much appreciated.

**Comment by SomberNight** [comment]
> I am using version 1.9.7 because I have an old seed that apparently needs pre-1.9.8 in order to recover my wallet.

Why do you think so? Your premise is likely incorrect.

You should always use the latest version of Electrum. The project maintains the ongoing guarantee that seeds generated by Electrum are supported in any later version.
What version of Electrum did you use to generate your seed? Or, as an approximation, when did you generate that seed?

**Comment by cph77** [comment]
Thanks for your response. [This was the thread](https://bitcointalk.org/index.php?topic=990306.0) that led me to believe that. I have a 24 word seed that was generated around 2013 -2014

**Comment by SomberNight** [comment]
In that thread the OP generated their seed manually using custom external tools.
If you used any released version of Electrum to generate the seed for you, any later version of Electrum will recognise and accept the seed.

What did you do?

**Comment by SomberNight** [comment]
Btw AFAICT re what the OP in the linked thread did, support was re-added a few days later: https://github.com/spesmilo/electrum/pull/1095

**Comment by cph77** [comment]
Ah I see. I would have used Electrum to generate. Is there any reason then why the "Next" button is greyed out after I enter my seed in the current version?

**Comment by SomberNight** [comment]
There are two likely reasons. Either
(1) you have made a typo when writing down your seed
(2) you don't remember correctly and the seed was not generated by Electrum

re (2), if you used another tool beside Electrum to generate the seed, the seed might be using the BIP39 specification.
Electrum supports restoring BIP39 seeds too. Just click "Options" when you enter the seed, and then check "BIP39". When you do so, just below the text box containing your seed, what does it say for "Checksum"?
If the checksum is "ok", your seed is most likely a BIP39 seed and it was not generated by Electrum.

**Comment by cph77** [comment]
With BIP39 selected it says "checksum: ok". I then check for existing accounts and it does not find any. So perhaps I should try another wallet provider?

**Comment by SomberNight** [comment]
> With BIP39 selected it says "checksum: ok". 

Right, so in that case your seed was not generated by Electrum (as Electrum never generated BIP39 seeds).

> I then check for existing accounts and it does not find any.

The problem with BIP39 seeds is that they leave a lot of configuration options open to the software/user, such as the derivation path and the script type to use. (when you click "Detect Existing Accounts", Electrum scans the blockchain, trying commonly used options)
Electrum seeds encode this information in the seed itself so they are less flexible but much more user-friendly.

Try to remember what wallet software you used. Good luck.

**Comment by cph77** [comment]
Thank you
