### ISSUE TITLE
Money are not sended and not confirmed

### ISSUE THREAD

**Issue by muRmot** [spesmilo/electrum#7023]
What me to do next to make this money sended?
Do not understand.
Why this unconfirmed?
![фыв](https://user-images.githubusercontent.com/71072060/107779578-9c30f000-6d56-11eb-876c-1e8518a2d297.jpg)

**Comment by muRmot** [comment]
![фыв](https://user-images.githubusercontent.com/71072060/107780265-85d76400-6d57-11eb-9168-08459bdddeba.jpg)

**Comment by spidyhackx** [comment]
increase fees and broadcast it

**Comment by muRmot** [comment]
> increase fees and broadcast it

tried already, thank you

**Comment by muRmot** [comment]
how much time is needed for my transaction to be approved?

**Comment by ecdsa** [comment]
https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
