### ISSUE TITLE
Electrum crashes

### ISSUE THREAD

**Issue by Marlebeast** [spesmilo/electrum#7024]
I have two unconfirmed transactions. One has been that way for more than a day. When I attempt to view either transaction or increase fee, the program locks up, and I have to use force quit. Once reopened, there is no change. I have uninstalled and reinstalled Electrum. I have Electrum 4.0.9 and am using it on MacOS Big Sur. 

The transaction IDs for the two unconfirmed transactions are 

ef97b1d5fd6655c6c949a55db66327b6ef847221b848b4ccccddf8304307574e

and

d8f2150ba58b264fabfaac63c7fb452cc63e38478a517973cef6a7afd015bfd6

I used another program, and my transactions were complete in less than 30 minutes, and they were small amounts. 

Please help!

**Comment by ecdsa** [comment]
please read the FAQ https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by SomberNight** [comment]
> When I attempt to view either transaction or increase fee, the program locks up, and I have to use force quit
> I have Electrum 4.0.9 and am using it on MacOS Big Sur.

duplicate of https://github.com/spesmilo/electrum/issues/6914

This is a bug introduced by macOS. For workaround, see https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046
