### ISSUE TITLE
Advanced Spends Locks Up

### ISSUE THREAD

**Issue by RHavar** [spesmilo/electrum#7028]
Using Electrum 4.0.9 with a trezor HWW I can reliably reproduce lockups by trying to use do advanced spends

1. Go to "Address" tab, click an address with lost of dust (in this case, 9 outputs) and go "Spend from"
2. Go to "Send" and put in an amount
3. Click "Pay"
4. Hit "Advanced" in the dialog

<img width="365" alt="Screen Shot 2021-02-15 at 10 08 11 AM" src="https://user-images.githubusercontent.com/9326759/107980856-d3c9b300-6f75-11eb-8987-1f14422628c9.png">

Boom. Guaranteed lock up.

Even leaving it run for a long time, results in 100% CPU usage and never ending climbing memory usage:
<img width="575" alt="Screen Shot 2021-02-15 at 9 55 52 AM" src="https://user-images.githubusercontent.com/9326759/107980910-ee039100-6f75-11eb-852d-d06f861fdd9f.png">

I've watched it get to >5GiB before killing it. 

During this time there does not appear to be network activity.

**Comment by SomberNight** [comment]
That looks like macOS. In that case https://github.com/spesmilo/electrum/issues/6914 ?

If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).

**Comment by RHavar** [comment]
lmao, thanks, yeah dark theme fixes it.
