### ISSUE TITLE
Trans_action

### ISSUE THREAD

**Issue by muRmot** [spesmilo/electrum#7031]
This is general question, but for me it is a BUG.
ME made a transaction of money from A to B.
Put the Fee (no in-build GUIDE how to use it) , as a NEW COMER of your wallet me DID NOT KNOW about the fee.
So, 1 time me made a trans_action and put random fee without even any idea about it. It was made for 1 night. Alright.
Second time me  put another trans_action, put the fee and nothing happens, it says it is local now, alright, someone said to me to increase thee fee, me increased it 2 times up to 7.1SAT for mb. So the trans_action now is unconfirmed, BUT it is unconfirmed for about 4-6 days, no option to increase the fee more. 
And the top valuse balances between 60 mb, 10 mb, 6 mb. Now it is 23.28. 
Me JUST WANT money to be appeared on the B section, why me should meet your "politics"? 
It is not simple, actually.

**Comment by ecdsa** [comment]
https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by muRmot** [comment]
the comissions are stacked or what? 16.02.2021, 16:21, "ThomasV" <notifications@github.com>: https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by muRmot** [comment]
how much me should put to for the payment to be confirmed??  16.02.2021, 16:21, "ThomasV" <notifications@github.com>: https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by muRmot** [comment]
this is what you mean? 16.02.2021, 16:23, "Олег Олегович Муравицкий" <inkot@yandex.by>:how much me should put to for the payment to be confirmed??  16.02.2021, 16:21, "ThomasV" <notifications@github.com>: https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by muRmot** [comment]
me do not see the "fees tab" me doing something wrong ? 16.02.2021, 16:27, "Олег Олегович Муравицкий" <inkot@yandex.by>:this is what you mean? 16.02.2021, 16:23, "Олег Олегович Муравицкий" <inkot@yandex.by>:how much me should put to for the payment to be confirmed??  16.02.2021, 16:21, "ThomasV" <notifications@github.com>: https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
