### ISSUE TITLE
Can't increase fee

### ISSUE THREAD

**Issue by TMCYTB** [spesmilo/electrum#7033]
I'm new to this stuff and so 2 hours earlier I didn't know how fees worked. 
Now I do and I made the fee higher, the only problem is that I keep getting this error if I try to increase it to something under 20sat/bytes:
"SerializationError('tx needs to have at least 1 output')"

and if I try to increase it to something like 167.2 it tells me:
"Cannot bump fee: could not find suitable outputs"

Now my transaction is basically stuck and I can't do anything about it. 
Transaction ID: 534181541d22440caa040e42fe82d8c5d38a9c925a448b6b08aa1ef1acee0a4e

**Comment by SomberNight** [comment]
Your tx has a single 3401 sat input and is creating a 557 sat output.
These amounts are just too small. The output is already barely over the dust limit.
On-chain bitcoin transactions are uneconomical for small amounts. You can try using Lightning for those.

**Comment by TMCYTB** [comment]
Lightning network is grayed out for some reason... And what happens with that transaction? Did I basically lost my money?
