### ISSUE TITLE
onchain_history filter by time

### ISSUE THREAD

**Issue by mariobyn** [spesmilo/electrum#7036]
Hello, I've noticed in the old versions of electrum we had a time filter for history so we won't get the whole history of the wallet. Any reason why that was removed? Any other workaround? 
Why I am asking is because, if my wallet has over 1m transactions, onchain_history will have a hard time retrieving everything.

Thank you

**Comment by SomberNight** [comment]
Indeed the old `history` command had `from_height`, `to_height` parameters, and also `year`;
while the newer `onchain_history` command only has `year`. (changed in https://github.com/spesmilo/electrum/commit/af7d7e883c760caedbe8ba738e450fae535b1886)

**Comment by mariobyn** [comment]
> Indeed the old `history` command had `from_height`, `to_height` parameters, and also `year`;
> 
> while the newer `onchain_history` command only has `year`. (changed in https://github.com/spesmilo/electrum/commit/af7d7e883c760caedbe8ba738e450fae535b1886)
> 
> 
> 
> 

Yes, i also noticed that, does anyone know the reason why this was removed? It had any implications?

**Comment by ecdsa** [comment]
IIRC I removed that before creating separate commands for onchain history and lightning history. With lightning transactions, those options do not make sense. I later decided to have two separate commands, and I guess I forgot to add those options back.

**Comment by mariobyn** [comment]
> IIRC I removed that before creating separate commands for onchain history and lightning history. With lightning transactions, those options do not make sense. I later decided to have two separate commands, and I guess I forgot to add those options back.

Ah ok, so no other considerations, any idea if it will be added back? i can also create a pull request if needed

**Comment by ecdsa** [comment]
sure, a PR would be fine.

**Comment by mariobyn** [comment]
> sure, a PR would be fine.

done
[#7043 ](https://github.com/spesmilo/electrum/pull/7043/commits/0f5bee87b70756453adf62e736f2345a37f1aa38)
