### ISSUE TITLE
Insufficient funds BUG

### ISSUE THREAD

**Issue by Drac971** [spesmilo/electrum#7037]
There is a problem with Electrum.
I've received a certain amount of BTC today (validated, transaction finished)
I would like to send some BTC to a friend.
My amount in my wallet is less that the amount I would like to send.
When I try they it says : "Insufficient funds".
Why?
Look at my screenshot
![Sans titre 1](https://user-images.githubusercontent.com/79222891/108254613-9d389780-7131-11eb-9ea0-8e1c4c0ff96c.jpg)
![Sans titre](https://user-images.githubusercontent.com/79222891/108254932-ee488b80-7131-11eb-8579-c9a8cc02648c.jpg)

**Comment by ecdsa** [comment]
please upgrade to 4.0.9

**Comment by Drac971** [comment]
Hi.
I did already.
I don't understand why it's not working..............
