### ISSUE TITLE
"insufficient funds" but I've got the fund ! I don't understand

### ISSUE THREAD

**Issue by Drac971** [spesmilo/electrum#7039]
There is a problem with Electrum.
I've received a certain amount of BTC today (validated, transaction finished)
I would like to send some BTC to a friend.
My amount in my wallet is less that the amount I would like to send.
When I try they it says : "Insufficient funds".
Why?
My electrum version is updated : 4.0.9 already

Look at my screenshot
![108254932-ee488b80-7131-11eb-8579-c9a8cc02648c](https://user-images.githubusercontent.com/79222891/108267524-b0ebfa00-7141-11eb-89e9-1e09dce7a019.jpg)
![108254613-9d389780-7131-11eb-9ea0-8e1c4c0ff96c](https://user-images.githubusercontent.com/79222891/108267531-b3e6ea80-7141-11eb-97c7-e35c55126595.jpg)

**Comment by SomberNight** [comment]
I guess the difference is due to fees. (either miner fees, or 2fa fees if it is a 2fa wallet)
btw, your screenshot is definitely not from 4.0.9, it is older than 4.0. Please update.

**Comment by Drac971** [comment]
Sure I took the screenshot bf updating.
So what's the solution?
I have to send 32.6 EUR and I have 50 EUR on my wallet. Doesn't make sense, plus when I click on "max", it put me the amount of money I had on my wallet before adding more today (which is approved, not in process anymore).
I don't get it.
Do you need more screenshot?

**Comment by SomberNight** [comment]
> Do you need more screenshot?

Sure, it might help.
Please make sure the full window is visible, including title/statusbar (but you can redact private details).

**Comment by ecdsa** [comment]
closing: this is not an issue, but rather a user question. I also doubt this guy is going to reply.
