### ISSUE TITLE
Wallet opens/restores correctly in v3.3.8 but not 4.0.9

### ISSUE THREAD

**Issue by RR82** [spesmilo/electrum#7040]
Hello,
I have a legacy wallet with an address that contains a large number of transactions. It will open correctly on electrum-3.3.8-x86_64.AppImage accessing my server running electrs v0.7.0 (takes about 1.5hrs to sync)

However, when I try to open (or restore) this wallet with the latest versions of electrum and electrs (electrum-4.0.9-x86_64.AppImage and electrs 0.8.6), it gets stuck syncing and never completes, even leaving it overnight. There are no obvious errors reported in the logs for electrum or electrs.

I have other wallets that may have the same issue, but I'd rather not access them with outdated Electrum/electrs. What are the risks in using these older versions?

**Comment by ecdsa** [comment]
besides possible security fixes, new versions often upgrade the wallet file structure.
In that case the old version cannot open the upgraded wallet file.
