### ISSUE TITLE
Android app copies/shows bip21 uri instead of bitcoin address

### ISSUE THREAD

**Issue by iduno8912** [spesmilo/electrum#7042]
On Electrum on Android when I go to "Receive" and click "Request" I am presented with a screen that lets me copy the address to the clipboard with a copy button. When I paste the data into another wallet, it isn't recognized as a valid address because there is additional data added. The address is preceded by "bitcoin:" and proceeded by "time=" and "exp=". I have to manually delete this data to make the address recognizable by another wallet. 

Since I am unable to select just the address and copy it, this is the only way for me to copy the address into another wallet. Obviously using the QR code is out of the question if I am only using one device. Am I missing something or will this be fixed in the future?

**Comment by SomberNight** [comment]
Ideally

**Comment by iduno8912** [comment]
> 
> What gets copied is a [BIP21 URI](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki). This is 9 year old format is a widely recognised standard at this point, and I am inclined to say that it is the other wallet's fault that they do not handle it.

There is absolutely no reason to not let the user just copy the address by itself. If you are intent on keeping you formatting, at least add an option to highlight or copy just the address. Coinbase is one of the most used exchanges and wallets in the entire world and constitutes a huge portion of the Bitcoin community. They do not recognize BIP21 URI when transferring funds. Why would you not at least give the option to copy an address without formatting? Do we not want Electrum to be a good choice for such a big userbase?

**Comment by SomberNight** [comment]
> There is no reason to not let the user just copy the address by itself

There is always a reason for UI decisions, you either add functionality or keep the UI simple. Often you have to choose.

> at least add an option to highlight or copy just the address

I agree that the address itself should ideally be copiable in some way though.

Looking at the code, the intent was already to make it clickable so that it could be copied. I'll fix that.

> and assuming it should be standard is kinda tone def IMO.

I am not assuming anything; it is a standard :P I simply haven't realised you are trying to paste it into an exchange's app, instead of a proper wallet. Exchanges are notorious for not implementing standards, just think of how slow bech32 adoption was.

**Comment by iduno8912** [comment]
> > There is no reason to not let the user just copy the address by itself
> 
> There is always a reason for UI decisions, you either add functionality or keep the UI simple. Often you have to choose.
> 
> > at least add an option to highlight or copy just the address
> 
> I agree that the address itself should ideally be copiable in some way though.
> 
> Looking at the code, the intent was already to make it clickable so that it could be copied. I'll fix that.
> 
> > and assuming it should be standard is kinda tone def IMO.
> 
> I am not assuming anything; it is a standard :P I simply haven't realised you are trying to paste it into an exchange's app, instead of a proper wallet. Exchanges are notorious for not implementing standards, just think of how slow bech32 adoption was.

Cool thank you! A lot of people using Electrum are simply trying to pull their coins off an exchange. Keep us in mind :D
