### ISSUE TITLE
Loading TX from text with light color themed Electrum freezes and force to quit

### ISSUE THREAD

**Issue by Sh0ham** [spesmilo/electrum#7044]
I noticed it on Electrum 4.0.9 on macOS 11.2.1 (MacBook Pro 2018 i7 and Mac mini M1).
Sometimes it happens with normal TXs I tried to sign.

It seems that on dark mode it works just fine; which has the old fashion design.
<img width="943" alt="Dark" src="https://user-images.githubusercontent.com/24498412/108531536-74ee9b80-72df-11eb-8830-3b20e8dff709.png">
<img width="932" alt="Light" src="https://user-images.githubusercontent.com/24498412/108531545-76b85f00-72df-11eb-93f1-daaa7a62c355.png">

**Comment by ecdsa** [comment]
this has already been reported before.
until the next release, the workaround is to use the dark theme.
