### ISSUE TITLE
Trezor passphrase is being asked on every operation since 4.0.3

### ISSUE THREAD

**Issue by ejose19** [spesmilo/electrum#7045]
It seems that somewhere in https://github.com/spesmilo/electrum/compare/4.0.2...4.0.3 broke the "cache" mechanism of passphrase and now it's being asked on every single wallet operation, probably related to #6561.

To Reproduce:
1. Use any version ```>=4.0.3```
2. Unlock trezor (both pin and passphrase)
3. Go to address tab, select any address and click "Show on Trezor"
4. passphrase is being asked (even though wallet is unlocked)
5. after typing the passphrase and repeating the 3rd step, passphrase is being asked again

Expected Behavior:
Electrum should respect wallet timeout and use the given passphrase for subsequent calls

Actual Behavior: 
Electrum ask for passphrase on every wallet operation

**Comment by prusnak** [comment]
@matejcik can you please check whether trezor plugin sends session_id like it's supposed to do?

**Comment by ejose19** [comment]
I've updated Trezor to the latest firmware and the issue no longer occurs. Perhaps setting a min firmware version in Electrum and displaying a warning if the connected device is below it? That way users can either: 

a) Upgrade firmware to have a compatible version 
b) Proceed acknowledging that some incompatibilities may occur.

**Comment by prusnak** [comment]
> setting a min firmware version

This is already set via python-trezor dependency. But your version was considered compatible (it still works, although the UX is not very nice).
