### ISSUE TITLE
Password field not being highlighted

### ISSUE THREAD

**Issue by 2pac1** [spesmilo/electrum#7048]
UI/UX improvement proposal
-------------------

Hey guys,
 
When one gets to the part of creating a wallet where the settings of password happens, it would be good that password field is highlighted or that it has a cursor blinker on it. Something.
Now it doesn't have anything and one can think that the password cannot even be set.
Even when you click on the input box, you still do not see the cursor.

Take care

**Comment by SomberNight** [comment]
Do you mean on kivy (Android) or Qt (desktop)?

**Comment by 2pac1** [comment]
Desktop
