### ISSUE TITLE
UI/UX improvement: Amount sent: 0 (when sending within same wallet)

### ISSUE THREAD

**Issue by 2pac1** [spesmilo/electrum#7052]
Hey guys,
 
So when one sends funds from within his own wallet, to the next available free address within the same wallet, the confirmation screen is showing (advanced screen that is) Amount sent: 0.
Simple payment screen prior that is normally showing amount being sent.

That could be confusing (and is confusing).
One could argue that:
-showing full amount being sent would be more logical (same way simple payment screen is showing).
-showing after Amount sent: 0 to add text or full sum within () or something like that.

Current workflow is confusing because simple payment screen shows amount being sent and lists it while advanced payment screen is showing zero (0).

I want to hear your thoughts?!

Tnx

**Comment by ecdsa** [comment]
what you call the confirmation screen is an advanced preview of the transaction.
it shows the outputs of the transaction, and the amount leaving the wallet.

if you cannot get used to it, do not use the advanced preview.
