### ISSUE TITLE
URGENT - is electrum-4[.]github[.]io run by admins here?

### ISSUE THREAD

**Issue by ssaleem9** [spesmilo/electrum#7053]
Came across this domain for a new update for electrum while on a site. I know there have been scams in the past, and wanted to know the validity of this. 

who runs this github host? electrum-4[.]github[.]io? I checked the digital signature of the .exe and it LOOKS fine, but need to confirm. the host autodirected me saying an update is needed due to previous version being vulnerable.

**Comment by ecdsa** [comment]
not run by us. obviously a scam. how did you "come across"?

**Comment by ssaleem9** [comment]
it failed the gpg signature check, nvm. I meant it looked fine via eyeballing it. Had to learn how to verify it
