### ISSUE TITLE
paytomany to split max among multiple outputs (allow specifying weights for max amounts, send max, exclamation mark, sharing revenue)

### ISSUE THREAD

**Issue by pooofdevelopment** [spesmilo/electrum#7054]
Hey hey,

Quick question: I want to be able to split all funds in the wallet to multiple addresses on a JSONRPC call. Is this possible already?

Else, is there a possibility for a paymaxtomany()-method? It would do exactly the same as paytomany() but instead, it calculates the maximum according to a provided feerate, and instead of hard-coded amounts, it takes percentages.

**Example JSONRPC array for this:**
`{
   "jsonrpc":"2.0",
   "id":"curltext",
   "method":"paymaxtomany",
   "params":{
      "outputs":[
         [
            "tb1qq0g39r3n38y37t6yptru564m9vme6szjjy0nks", 75
         ],
         [
            "tb1qqdkj9feahthysuwdypxznwu94w4hl0uqyj3x5p", 12.5
         ],
         [
            "tb1qsl5sn4frf4tu0f3zajgv3ggqgx6wjqk8sdejjv", 12.5
         ]
      ],
      "feerate":1
   }
}`

Where **75 = 75% of the maximum** that we can send and **12.5 = 12.5% of maximum** that we can send.

If anyone has a solution for this, do let me know. It'd be great!
I don't know if this even possible, but it would be a blessing to us (and I think many others 👍).

**Comment by SomberNight** [comment]
> instead of hard-coded amounts, it takes percentages.

No, that is not possible atm.

One thing you can do now, if you don't want a change output, is to use "!" an exclamation mark as amount which will mean "max". This can be used in `paytomany` and other commands or in GUI, and you can still have other fixed amount as well.
So e.g. you can create a tx that pays to `["addr1", 0.5], ["addr2", "!"], ["addr3", 0.15]`, and there will be exactly those 3 outputs.

**Comment by ecdsa** [comment]
I think there has already been a discussion about such a syntax, but I could not find it...

**Comment by MrNaif2018** [comment]
@ecdsa I think there: #1698

**Comment by pooofdevelopment** [comment]
@ecdsa @SomberNight As of right now, I take the complete amount, divide it into the percentages I need, and indeed: I then proceed to use ! to take the fee of off that specific remaining amount.

I'd love to have it get divided across the 3 amounts though... 

Thanks in advance guys!

**Comment by SomberNight** [comment]
from https://github.com/spesmilo/electrum/issues/1698#issuecomment-223773525

> The "mathematically correct" way would be to use weights
> `<address1>, 1!`
> `<address2>, 2!`

I like the weights idea. IMHO we should also restrict the weights to be integers.
i.e. these amounts would be strings concatted from an int and an exclamation mark `!` (both internally and user-exposed)

If implemented, this would be in `wallet.py` or similar, not on the CLI/RPC layer, so that the GUI can use it too (with multiline paytomany in Send tab),
We would take a pull request for this.

**Comment by SomberNight** [comment]
This is now implemented on master.

Example usage from CLI:
```
./run_electrum -v --testnet paytomany -w /home/user/.electrum/testnet/wallets/test_segwit_2 '[["tb1qk3g0t9pw5wctkzz7gh6k3ljfuukn729s67y54e", 0.002],["tb1qr7evucrllljtryam6y2k3ntmlptq208pghql2h", "2!"],["tb1qs3msqp0n0qade2haanjw2dkaa5lm77vwvce00h", 0.003],["tb1qar4ye43tdfj6y5n3yndp9adhs2wuz2v0wgqn5l", "3!"]]' --feerate 1
```

Example usage via RPC:
```
curl --data-binary '{"id":"curltext","method":"paytomany","params":{"outputs":[["tb1qk3g0t9pw5wctkzz7gh6k3ljfuukn729s67y54e", 0.002],["tb1qr7evucrllljtryam6y2k3ntmlptq208pghql2h", "2!"],["tb1qs3msqp0n0qade2haanjw2dkaa5lm77vwvce00h", 0.003],["tb1qar4ye43tdfj6y5n3yndp9adhs2wuz2v0wgqn5l", "3!"]], "fee": 0.00005, "wallet": "/home/user/.electrum/testnet/wallets/test_segwit_2", "password": "1234"}}' http://user:password@127.0.0.1:7777
```
