### ISSUE TITLE
No ability to create change address via JSON API

### ISSUE THREAD

**Issue by bodangly** [spesmilo/electrum#7055]
There is no ability to create a change address specifically via the JSON API. This is because the createnewaddress command hardcodes the for_change parameter to False. This suggested patch would fix that.
```
--- Electrum-4.0.9/electrum/commands.py       2000-11-11 12:11:11.000000000 +0100
+++ Electrum-4.0.9.bodangly/electrum/commands.py      2021-02-21 07:39:07.980831388 +0100
@@ -792,9 +792,9 @@
         return [wallet.export_request(x) for x in out]

     @command('w')
-    async def createnewaddress(self, wallet: Abstract_Wallet = None):
+    async def createnewaddress(self, for_change: bool = False, wallet: Abstract_Wallet = None):
         """Create a new receiving address, beyond the gap limit of the wallet"""
-        return wallet.create_new_address(False)
+        return wallet.create_new_address(for_change)

     @command('w')
     async def changegaplimit(self, new_limit, iknowwhatimdoing=False, wallet: Abstract_Wallet = None):
@@ -1183,6 +1183,7 @@
     'encrypt_file':(None, "Whether the file on disk should be encrypted with the provided password"),
     'receiving':   (None, "Show only receiving addresses"),
     'change':      (None, "Show only change addresses"),
+    'for_change':  (None, "Create a change address if true"),
     'frozen':      (None, "Show only frozen addresses"),
     'unused':      (None, "Show only unused addresses"),
     'funded':      (None, "Show only funded addresses"),
```

**Comment by SomberNight** [comment]
Why would you want to create a change address?
The other name for "change" address is "internal" address (e.g. in bip32): they are supposed to be managed internally.

**Comment by bodangly** [comment]
In my case I have an offline hot wallet I am keeping in sync with an online watch-only wallet. As I am keeping a certain amount of addresses pre-generated as well, I keep length of the length of receive addresses in my wallet and change addresses.

**Comment by SomberNight** [comment]
> offline hot wallet 

Using the traditional definitions a hot wallet cannot be offline; offline is usually a synonym for cold. So what do you mean?

> offline hot wallet I am keeping in sync with an online watch-only wallet

What do you mean "keeping in sync"? You don't need to keep an offline wallet and an online wallet "in sync"... The offline wallet does not need state. State is provided in the partial transactions when signing.

> I keep track of the length of receive addresses 

What is the length of an address? Do you mean the number of generated addresses?

**Comment by bodangly** [comment]
The wallet which is watch only is connected to a web server. It is generating addresses and transactions to be signed by the offline wallet which has the master private key. The offline wallet receives the transactions and signs them. To make sure it has the keys in the wallet which it needs, I tell it how many generated receive and change addresses the online wallet has. It then generates more addresses if it needs to, and then signs the transaction and sends it back to be broadcast. The offline wallet is connected via serial to a proxy machine that is receiving the transactions and wallet metadata (receive address pool length, change address pool length).

**Comment by SomberNight** [comment]
> The offline wallet receives the transactions and signs them. To make sure it has the keys in the wallet which it needs, I tell it how many generated receive and change addresses the online wallet has

You don't need to do this. When the online wallet creates a partial transaction, it encodes the derivation path for each pubkey involved, and the offline wallet will then derive keys on demand. The offline wallet does not have to have the keys already derived.

**Comment by bodangly** [comment]
> > The offline wallet receives the transactions and signs them. To make sure it has the keys in the wallet which it needs, I tell it how many generated receive and change addresses the online wallet has
> 
> You don't need to do this. When the online wallet creates a partial transaction, it encodes the derivation path for each pubkey involved, and the offline wallet will then derive keys on demand. The offline wallet does not have to have the keys already derived.

I see, was this always working? Could have sworn I received an error when trying this, but this code is something I am coming back to after several years. In any case I will close the issue then.

**Comment by SomberNight** [comment]
Yes, I think this has always worked in Electrum.

Note that e.g. in Bitcoin Core, it works differently. There they use a huge gap limit of (I think) 1000, and they can only sign if the offline wallet already has the needed keys derived, just as you assumed here.

**Comment by bodangly** [comment]
> Yes, I think this has always worked in Electrum.
> 
> Note that e.g. in Bitcoin Core, it works differently. There they use a huge gap limit of (I think) 1000, and they can only sign if the offline wallet already has the needed keys derived, just as you assumed here.

I have switched around the library I was using a few times so perhaps this is a misunderstanding in my own code inherited from Bitcoin Core or another wallet. Thanks for such a quick answer. Simplifies my life too.
