### ISSUE TITLE
Error message on exit

### ISSUE THREAD

**Issue by electrumrabbit** [spesmilo/electrum#7056]
The program gives an error message on exit. Wonder if it will affect its operation. It's working ok but i'm a noobie and don't know if it's a serious problem or not. Any ideas?
![error message](https://user-images.githubusercontent.com/79423121/108639052-81235600-74a3-11eb-9bfc-2181c646b5bc.jpg)

**Comment by SomberNight** [comment]
duplicate of https://github.com/spesmilo/electrum/issues/6889

Feel free to ignore the crash.
