### ISSUE TITLE
Adress lost

### ISSUE THREAD

**Issue by Alle71** [spesmilo/electrum#7063]
So I bought some bitcoins copied a adress from the adress tab , but I never received any bitcoins. now it seems like the adress is some how not linked to my wallet. How can something like that happen I just payed for nothing

**Comment by SomberNight** [comment]
You should check if the address you copied (if you still have it) appears in the Addresses tab (View>"Show Addresses").
Also, do you have a txid for the transaction that is supposed to pay you?

Many things that could have happened, for example:
- the sender did not send a transaction
- the sender sent a transaction but to a different address
- you copied an address from the Receive tab, but clipboard malware on the machine changed the contents of your clipboard

**Comment by Alle71** [comment]
> You should check if the address you copied (if you still have it) appears in the Addresses tab (View>"Show Addresses").
> Also, do you have a txid for the transaction that is supposed to pay you?
> 
> Many things that could have happened, for example:
> 
> * the sender did not send a transaction
> * the sender sent a transaction but to a different address
> * you copied an address from the Receive tab, but clipboard malware on the machine changed the contents of your clipboard

Its was bought from a swedish bitcoin site, they sent a blockhain link and everything, thats the thing the adress does not appear anymore in the adress tab

**Comment by Alle71** [comment]
> You should check if the address you copied (if you still have it) appears in the Addresses tab (View>"Show Addresses").
> Also, do you have a txid for the transaction that is supposed to pay you?
> 
> Many things that could have happened, for example:
> 
> * the sender did not send a transaction
> * the sender sent a transaction but to a different address
> * you copied an address from the Receive tab, but clipboard malware on the machine changed the contents of your clipboard

Thank you for your help I just realised that I actually have clipboard malware. Fuck!
