### ISSUE TITLE
Issue with QR Code Reader for Combine Signatures

### ISSUE THREAD

**Issue by dhdadev** [spesmilo/electrum#7064]
Good Afternoon,
    Just wanted to give you heads up, I am trying to use the QR code reader to combine a signed PSBT and it errors when trying to launch...here is the exact infoL
Traceback
Traceback (most recent call last):
  File "electrum/gui/qt/qrtextedit.py", line 64, in qr_input
AssertionError
 
Additional information
Electrum version: 4.0.9 
Python version: 3.7.9 (default, Sep 11 2020, 17:18:37) [Clang 11.0.0 (clang-1100.0.33.17)] 
Operating system: Darwin-19.6.0-x86_64-i386-64bit 
Wallet type: standard 
Locale: en_US 
Electrum is a watch only wallet, and here are the steps I take to cause the crash:
Create a transaction
1. Click Pay
2. Click Finalize
3. Export as QR for hardware device
4. Click Combine...and select merge signatures
5. Click the camera...and it errors out...
When I click the camera on other parts of the app...it works without issue
Let me know if you need more info...
Thanks and I like the app!

**Comment by SomberNight** [comment]
This might already be fixed on master with https://github.com/spesmilo/electrum/commit/096d85348218398c09915e33cabd11e34e323329
will have to test

**Comment by SomberNight** [comment]
Ok, I can reproduce on 4.0.9, and it is already fixed on master.
Thanks for the detailed report!
