### ISSUE TITLE
How to do an spv resync?

### ISSUE THREAD

**Issue by viperperidot** [spesmilo/electrum#7068]
I had a tx that I was receiving get kicked from the mempool due to low fee. However it still shows up as incoming in my Electrum wallet. I think I need to do an spv resync to remove this tx from my wallet correct? I looked around and couldn't find anywhere to do this. Or maybe Electrum is supposed to auto detect if a tx is kicked from the mempool and this is a bug? Thanks

**Comment by SomberNight** [comment]
How does the tx show up in the History tab? Is it marked confirmed/unconfirmed/local/etc?

**Comment by viperperidot** [comment]
It shows up as 'Unconfirmed'.

**Comment by SomberNight** [comment]
In that case the server you are connected to still has that tx in its mempool.
There is no global mempool. Each bitcoin node has their own view of the mempool.
If the connected server no longer had the tx in its mempool, the tx would become "local" in the History tab of the client.

**Comment by viperperidot** [comment]
Ok so eventually my node and mempool will kick out the tx just like the originating server did?

**Comment by SomberNight** [comment]
Maybe. There are no guarantees. The tx might even get mined.
If you want a guarantee it cannot get mined, you need to double-spend it, i.e. create a conflicting tx that spends the same inputs.

In practice, using the GUI, if your tx is RBF, you can either increase its fee to get it mined, or "cancel" it by sending the coins back to yourself.
If it's not urgent, you can just wait; but in theory, if you do nothing, the tx might still get mined even 10 years from now -- but if you keep using the wallet and create new transactions they will conflict with this old tx and then you will have a guarantee it cannot get mined anymore.

**Comment by SomberNight** [comment]
btw, note that you can try connecting to a few different servers, to see each of their mempools: the tx might turn into local with some servers but unconfirmed with others

**Comment by viperperidot** [comment]
Ok interesting, this was sent from a bisq wallet so there is no RBF option and also no option to spend the funds again until it is dropped from the mempool and you do a spv resync. I think I will just do the double spend method and use a good fee this time, never had this happen before. But I guess fees have not been this consistent in a while. So just to confirm, once the double spend gets confirmed then the original tx will just stay in that unconfirmed state forever or get kicked from all pools? But the real utxo is confirmed at the new address and the original is just like a ghost record.

**Comment by SomberNight** [comment]
There cannot be conflicting transactions in the blockchain; consensus enforces that. If any one of a set of conflicting txs gets mined, none of the others can get mined.
There are always blockchain reorgs too of course, but reorgs longer than a few blocks basically never happen.
