### ISSUE TITLE
Issue when sending money with electrum (bad-txns-inputs-missingorspent)

### ISSUE THREAD

**Issue by Lectia** [spesmilo/electrum#7076]
**
i want to send some bitcoins from electrum to my binance account. i have previously sent bitcoins on the binance acount, but now i receive the following message:
bad-txns-inputs-missingorspent
i do not have any experience in programming or things llike that.

**Comment by SomberNight** [comment]
You might have a "local" transaction in your wallet that this transaction builds on top. You need to either broadcast or remove the local tx.
