### ISSUE TITLE
Text predictor includes non BIP39 words after entering 4 characters

### ISSUE THREAD

**Issue by wmoon2594** [spesmilo/electrum#7077]
I was testing the restoring of a wallet that had the word "violin" in its seed phrase.  When typing out "viol", the predictor suggested "violin", and "violence"(not bip39).  Within the same seed, I also had "apol", which lead to a suggestion of "apology"(correct) and "apologize"(not bip39).  Not from the same seed, but another example is "conc" leading to suggestions of "concert"(correct) and "concrete"(not bip39).

I see this as a hurdle if I was trying to restore a seed from a steel plate that only saved the first 4 chars.  One helpful workaround is enabling the BIP39 option.  When enabled, it showed the warning when a word was not BIP39.  It would be helpful to have that shown on non bip39 as well, since I ran into the "concert" example while restoring an electron created seed.    This was using Electrum 4.0.9's appimage on linux.

**Comment by ecdsa** [comment]
it is not a helpful workaround: if you want to enter a bip39 seed it is mandatory to enable that option

**Comment by SomberNight** [comment]
we already colour non-bip39 words as yellow, is that not enough?
https://github.com/spesmilo/electrum/commit/7120c344b2d12b60be8c5fe82e7a9964425075c9

**Comment by wmoon2594** [comment]
You're right, that makes sense now.  I had not seen that linked issue, or was aware of an old list of words.  I knew Electrum's seed phrase isn't the standard bip39, but I incorrectly assumed only bip39 words were always used.  Still learning here.  Thanks.

**Comment by SomberNight** [comment]
The old Electrum seed format (before Electrum 2.0) had its own wordlist; this is what is called the "old" list in the code.
Modern Electrum seeds are independent of any wordlist (decoding a seed does not require a wordlist), but in practice seed-generation uses the BIP39 English wordlist for them.
