### ISSUE TITLE
no module named aes

### ISSUE THREAD

**Issue by ekg** [spesmilo/electrum#708]
What are electrum's dependencies?

I get this on startup, so I think I'm missing something:

```
./electrum 
Traceback (most recent call last):
  File "./electrum", line 39, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "/home/erik/src/electrum/lib/__init__.py", line 3, in <module>
    from wallet import WalletSynchronizer, WalletStorage
  File "/home/erik/src/electrum/lib/wallet.py", line 29, in <module>
    import aes
ImportError: No module named aes
```

**Comment by dooglus** [comment]
I just tried following that guide.

./contrib/make_locale doesn't exist, and I still get "ImportError: No module named aes" when I try to run the electrum script.

**Comment by robertkarl** [comment]
Same here, going to try to reopen as this could be made a little bit smoother for first time setup

**Comment by lupa18** [comment]
I installed some days ago, and now I'm getting this error.

**Comment by prg4hire** [comment]
I am also seeing this error. 

Here is how I get this error: 

1. I cloned electrum git

2. executed ./electrum. Got the error no module named dns. Then I installed python package dnspython , and the error went away. 

3. But now I get the error "no module named aes". I installed pycrypto module, but that does not resolve this issue. 

I am running Anaconda python, on a Win32 Windows 7 machine.

**Comment by prg4hire** [comment]
Ok, I fixed this issue by just downloading this file: http://anh.cs.luc.edu/331/code/aes.py

this was mentioned in https://github.com/spesmilo/electrum/issues/1514#issuecomment-150810477

**Comment by drschwabe** [comment]
Where do you put aes.py ?  On Ubuntu 14

**Comment by prg4hire** [comment]
@drschwabe Place it in the main electrum folder. In electrum/ wherever it is installed.

**Comment by dabura667** [comment]
`pip install slowaes`
