### ISSUE TITLE
[URGENT]Can't send funds from my wallet: Error while trying to create a payment/send transaction

### ISSUE THREAD

**Issue by tifDev** [spesmilo/electrum#7080]
Hello, 

I was testing my first sending of funds from my cold storage wallet. 

First I tried with fee static and use the defaults. I got this error when hit "Broadcast":

```
    The server returned an error when broadcasting the transaction.
    Consider trying to connect to a different server or update Electrum.
    mempool min fee not met
```

Then I tried with MEMPOOL and ETA, when I try to export the transaction to a file I get this:

``` python

Traceback
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/electrum/gui/qt/transaction_dialog.py", line 259, in <lambda>
    action.triggered.connect(lambda: self.export_to_file(tx=gettx()))
  File "/usr/lib/python3/dist-packages/electrum/gui/qt/transaction_dialog.py", line 348, in export_to_file
    f.write(tx.serialize_as_bytes())
  File "/usr/lib/python3/dist-packages/electrum/transaction.py", line 1871, in serialize_as_bytes
    self._serialize_psbt(fd)
  File "/usr/lib/python3/dist-packages/electrum/transaction.py", line 1692, in _serialize_psbt
    inp._serialize_psbt_section(fd)
  File "/usr/lib/python3/dist-packages/electrum/transaction.py", line 1102, in _serialize_psbt_section
    self.serialize_psbt_section_kvs(wr)
  File "/usr/lib/python3/dist-packages/electrum/transaction.py", line 1279, in serialize_psbt_section_kvs
    wr(PSBTInputType.NON_WITNESS_UTXO, bfh(self.utxo.serialize_to_network(include_sigs=True)))
  File "/usr/lib/python3/dist-packages/electrum/transaction.py", line 806, in serialize_to_network
    witness = ''.join(self.serialize_witness(x, estimate_size=estimate_size) for x in inputs)
  File "/usr/lib/python3/dist-packages/electrum/transaction.py", line 806, in <genexpr>
    witness = ''.join(self.serialize_witness(x, estimate_size=estimate_size) for x in inputs)
  File "/usr/lib/python3/dist-packages/electrum/transaction.py", line 656, in serialize_witness
    raise UnknownTxinType(f'cannot construct witness for txin_type: {_type}')
electrum.transaction.UnknownTxinType: cannot construct witness for txin_type: unknown
 
Additional information
Electrum version: 4.0.9 
Python version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0] 
Operating system: Linux-5.10.0-3-amd64-x86_64-with-debian-10.8 
Wallet type: standard 
Locale: en_US 
```

How can I solve this? 
**Are my funds at risk?**

**Note:** I'm using last Tails version

**Comment by SomberNight** [comment]
No, the funds are of course NOT at risk.

As for fixing the issue; I am trying to figure out how to reproduce...
Do you have any "local" transactions in the "History" tab?

**Comment by tifDev** [comment]
> Do you have any "local" transactions in the "History" tab?
Yes, Local [rbf] for an unsigned transaction (for one of those failed transactions that I tried to create to send from my wallet)

Steps to (hopefully) reproduce:
1. Install tails in 2 usb sticks (1 online and other airgapped)
2. Use last tails version
3. Create a transaction with STATIC
4. Sign this transaction in offline machine
5. try to broadcast it in online machine (it should give an error)
6. Then add another transaction but using ETA
7. Export to file (for me it created an empty file)
8. Try to create another with Mempool
9. When click "Export to file" the bug starts appearing.
10. At this point any transaction Send that you create will trigger the bug.

Hope this helps.



**Other note:** I tried to use appimage and sometimes it worked but it stopped working in both offline and online machines. When I double click it does nothing. So I'm just using the Electrum provided by tails.

**Comment by tifDev** [comment]
> No, the funds are of course NOT at risk.
That's what I thought also but I still not very confident to keep sending funds to this wallet until I'm sure that I can send funds from it :)

**Comment by SomberNight** [comment]
Ok, I can reproduce.
Try after removing the local transactions from your wallet.

**Comment by SomberNight** [comment]
probably same as https://github.com/spesmilo/electrum/issues/7009 and https://github.com/spesmilo/electrum/issues/6482

To reproduce, save an unsigned local transaction tx1 into the wallet history, and then create tx2 that spends from tx1.
The exception arises when trying to serialize tx2.

**Comment by tifDev** [comment]
Is there any ongoing fix for this in future releases?

How can I fix this for the moment? Any workaround?

Thank you.

**Comment by tifDev** [comment]
I really need to send funds out of it to be at peace of mind

**Comment by SomberNight** [comment]
> How can I fix this for the moment? Any workaround?

Yes, I explicitly said so above:

>  Try after removing the local transactions from your wallet.

**Comment by tifDev** [comment]
I've removed the transactions from "Send tab" but it keeps the error.

**Comment by tifDev** [comment]
I've removed the transactions from "Send tab" but it keeps the error.

**Comment by SomberNight** [comment]
The "Send" tab does not show transactions. It shows invoices.
You should remove transactions marked as "Local" in the "History" tab.

**Comment by tifDev** [comment]
Thanks it worked.
 Do you know the root cause of this issue?
