### ISSUE TITLE
URGENT!!!! I need help fast transferring my coins from my  Electrum wallet.

### ISSUE THREAD

**Issue by johneringo** [spesmilo/electrum#7081]
Lets just say I have minimal experience in coding etc. But a friend suggested I should use a "tumbler" for my bitcoins for tax reasons. But the the tumbling took ages and I actually stayed up all night trying to figure out what the hell it was doing. I got in touch with them (Chipmixer) and for some reason my coins landed in a watch only wallet so I can´t move them. The chipmixer support offered to sweep the money for me to my reguar adress but after 4 proposed adresses and 20 hours later nothing has happened. And now itäs just about 20 hours before their "timer" runs out and they basically take my money. So is there any chance of transferring from a  watching only wallet to a regular one...? I´d really appreciate any help I could get. Rookie mistakes....  Thanks.

**Comment by SomberNight** [comment]
A watching only wallet is called as such because it does not have private keys; which means it is impossible to spend from it. Typically it is created "from" a wallet that has private keys. So the question is, who the keys for this wallet?

> The chipmixer support offered to sweep the money for me 

That sounds like chipmixer has custody of the coins. You might have been scammed.

I fail to see how this is at all related to Electrum.
It is akin to buying a kitchen knife (tool), stabbing yourself with it, and asking the shop that sold the knife for help. Oh and the knife was for free. This issue tracker is here to make the knife sharper, easier/safer to use, etc.

**Comment by johneringo** [comment]
Ok come on thar hurt! I f—-d up, no need to rub it in! 🥺😂 They were ranked no 1 so i figuref  they would lose more from scamminf people for peanuts. But i mafe a few mistaked due to the lack of sleep so I cant blame them for everything. Me reching out to you guys was more a last desperate attempt to seevif there was any way to bypass it because i think the watching phone is wstchim the default wallet thst i can’t figure out where input the login information 😆
Skickat från min iPhone

3 mars 2021 kl. 20:53 skrev ghost43 <notifications@github.com>:

﻿

Closed #7081<https://github.com/spesmilo/electrum/issues/7081>.

**Comment by johneringo** [comment]
So is it you guys or those greedy litte swiss pricks at dicklickers that I should be grateful to for you guys saving on fees while stealing my money?
You saidI had been scammed but you never said by who..?

________________________________
Från: ghost43 <notifications@github.com>
Skickat: den 3 mars 2021 20:53
Till: spesmilo/electrum <electrum@noreply.github.com>
Kopia: johneringo <j_o_abrahamsson@hotmail.com>; Author <author@noreply.github.com>
Ämne: Re: [spesmilo/electrum] URGENT!!!! I need help fast transferring my coins from my Electrum wallet. (#7081)


Closed #7081<https://github.com/spesmilo/electrum/issues/7081>.

**Comment by SomberNight** [comment]
Presumably the custodial trusted mixed that you used stole your coins.

- Can you share the website for the mixer you used?
- Did they ask you to go into the "Console" tab in Electrum?
