### ISSUE TITLE
Can't restore wallet from seed from Electrum version circa 1.7.3

### ISSUE THREAD

**Issue by skrat** [spesmilo/electrum#7082]
I haven't found any documentation or anything regarding how to restore wallets from past versions of Electrum. Any help would be greatly appreciated.

When I restore the wallet on recent (4.x.x) Electrum, it shows blank wallet with no transactions. I tried using older Electrum versions, but those won't synchronize or even connect to a server.

**Comment by SomberNight** [comment]
> I haven't found any documentation or anything regarding how to restore wallets from past versions of Electrum

They don't exist because they are unnecessary. Any seed generated since Electrum 1.0 is supported using any later version.

In the wallet creation wizard, when you enter your seed, right below the text box, what does it say for "Seed Type"?

**Comment by skrat** [comment]
Yes it does say "old" when restoring

**Comment by SomberNight** [comment]
Is it a 12 word seed that you have, or something more exotic (e.g. a hex string)?

Most likely, either
(1) you wrote down the seed incorrectly, or
(2) have generated multiple seeds back then, and mixed them up (so this is not the one you sent coins to)

Re (1), the problem with "old" seeds is that they don't have a checksum; the only thing the program can check is whether all words are from the expected wordlist. That is, if you wrote down your seed incorrectly (e.g. changing word order, or replacing words with other similar valid words), it would not be detected -- you would simply see no history when restoring (as the resulting keys are different).

**Comment by skrat** [comment]
Thanks, (1) is very unlikely, (2) that could be the case but I doubt it. It's just 12 words, I also stored some 34 character long alphanumeric string. So, are there are any unit tests that you use to ensure that Electrum can restored wallets from seed from version 1.7.x or how does it work? How can you be sure that it works?

**Comment by SomberNight** [comment]
> So, are there are any unit tests that you use to ensure that Electrum can restore wallets from seed from version 1.7.x or how does it work? How can you be sure that it works?

There is no distinction between seeds created between specific Electrum versions such as 1.7.x -- the only difference between seeds is the "type", such as "old". All seeds prior Electrum 2.0 are "old" seeds (with identical key derivation between them).
More types here: https://github.com/spesmilo/electrum/blob/ec6baa12f81065ee5b110d6c277a24d752acb11d/electrum/mnemonic.py#L243

Yes, there are unit tests, but none relevant that go back to ~1.7.x.
This test that would be testing exactly this was added around version 3.0:
https://github.com/spesmilo/electrum/blob/ec6baa12f81065ee5b110d6c277a24d752acb11d/electrum/tests/test_wallet_vertical.py#L146
Note that this unit test, using seed `powerful random nobody notice nothing important anyway look away hidden message over`, generates a wallet which has `1FJEEB8ihPMbzs2SkLmr37dHyRFzakqUmo` as its first receiving address.
I have just now tested with Electrum 1.8 and reproduced this manually.

You could do the same. Download an old version of Electrum and compare the addresses it generates from your seed with the addresses generated by modern Electrum. Note that old versions cannot connect to servers but network connectivity is not needed to generate addresses.

To test with Electrum 1.8, you could just grab it from https://download.electrum.org/ (please verify the GPG signature), and cancel all popups that seem to try to connect to servers. When the application's main window finally opens, go to the Console tab and run: `wallet.addresses()`. Note that it will return an empty list as it failed to connect to any server. Now run `wallet.synchronize()` to force it to generate addresses anyway. Now run `wallet.addresses()` again, to see the list of addresses. They should match what you see in the "Addresses" tab in Electrum 4.0.x.

**Comment by anarchymachines** [comment]
> > I haven't found any documentation or anything regarding how to restore wallets from past versions of Electrum
> 
> They don't exist because they are unnecessary. Any seed generated since Electrum 1.0 is supported using any later version.
> 
> In the wallet creation wizard, when you enter your seed, right below the text box, what does it say for "Seed Type"?

The seed is "supported" in the sense that it will be recognized as a valid seed (of the old variety) but it will not generate the old wallet. It will instead generate a new wallet with the version 2 (and above) key derivation method, which means you'll get a bunch of shiny new (empty) addresses.

From the version 0.32 release notes:


"version 0.31 fixes a vulnerability in the key generation function.
Unfortunately, this means that wallets created prior to 0.31 are
incompatible with newer versions. We apologize for the
inconvenience. We try to keep this kind of upgrades as rare as
possible.

If you use an older wallet, you will see a message asking you to
create a new wallet and to move your balance to the new wallet.

...

Note that you may keep your current seed. For this, all you need to do
is to create the new wallet using the wallet recovery procedure. You
will not recover your old wallet with the new software, but you will
get a new wallet instead."


Unfortunately I do not know what the solution is. I've had the same problems as the OP...trying to get the older versions to work is frustrating to say the least.

**Comment by ecdsa** [comment]
@anarchymachines I do not think your comment is helpful. The seed of the OP is recognized as "old". That would not be the case with a pre-0.31 seed.

anyway, closing this issue, the OP never replied.

**Comment by anarchymachines** [comment]
> @anarchymachines I do not think your comment is helpful. The seed of the OP is recognized as "old". That would not be the case with a pre-0.31 seed.
> 
> anyway, closing this issue, the OP never replied.

Wait, really? How were the pre-0.31 seeds different? And what would it say if you entered one while attempting recovery (if not "seed type: old"). Genuinely very curious. I haven't been able to find a lot of information on this.

**Comment by skrat** [comment]
@ecdsa @anarchymachines I don't care about petty developer issues, Electrum failed me, I lost coin, moved on to HW wallet. End of story
