### ISSUE TITLE
Le serveur a retourné une erreur lors de la transmission

### ISSUE THREAD

**Issue by Gwegoo78** [spesmilo/electrum#7084]
bonjour

Après tentative d'envoi j'ai le message d'erreur suivant  : 
Le serveur a retourné une erreur lors de la transmission de la transaction.
Essayez de vous connecter à un serveur différent ou mettez à jour Electrum.

mempool min fee not me

J'ai changer plusieurs fois de serveur mais sans résultat

Merci pour votre aide

Greg

**Comment by Transisto** [comment]
Would it be possible that your transaction is invalid?

**Comment by Gwegoo78** [comment]
Bonjour effectivement je n’avait pas mis assez de frais pour la transaction 
Merci pour vôtre réponse 😊
