### ISSUE TITLE
Documentation error (actually, just missing exchange rate info)

### ISSUE THREAD

**Issue by dscotese** [spesmilo/electrum#7085]
Searches for the words price, value, exchange, and rate on the https://electrum.readthedocs.io/ page do NOT turn up anything that explains how the wallet fills in the "USD" box displayed in the image at https://electrum.readthedocs.io/en/latest/_images/paytomany.png (which I use only because it shows that the documentation itself shows that the wallet does something to fill that box but doesn't explain how anywhere that is easy to find).

It may be the case that "everyone knows" how Electrum gets BTC prices except for me and my friend, but even so, one of the FAQs should be "How does Electrum get exchange rates?"

Also, it would be nice if the wallet allowed other sources to be used for the exchange rate, assuming something is hardcoded.

**Comment by SomberNight** [comment]
What is the root problem here? Are you trying to configure exchange rates?
See menubar>`Tools`>`Preferences`>`Fiat`

**Comment by dscotese** [comment]
The documentation at readthedocs.io is the root of the problem.

**Comment by dscotese** [comment]
I see now that the documentation is in a different project.  I'll take care of it over there.
