### ISSUE TITLE
Error:  mempool min fee not met

### ISSUE THREAD

**Issue by aquatic7** [spesmilo/electrum#7086]
OS: Manjaro 20.2.1 Nibia
Kernel: x86_64 Linux 5.11.1-1-MANJARO
DE: KDE 5.79.0 / Plasma 5.21.1
Electrum: Version 4.0.9

When I try to send, I get this error:

```
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

mempool min fee not met
```

I've tried to change server with no different result. I've also set it to automatic with no different result.
How to fix this bug?

**Comment by SomberNight** [comment]
Your transaction is paying a fee that is so low that the bitcoin node cannot fit it into its mempool.
The mempool is already full of hundreds of megabytes of transactions that all pay higher fees.
Try to increase the fee.

**Comment by ecdsa** [comment]
maybe we should display a better error message in that case

**Comment by SomberNight** [comment]
master already shows an explanation for this error, I've copied my comment from there.
https://github.com/spesmilo/electrum/blob/6ddd02506eefcbef358c18bcb5fb8106400a3c2b/electrum/network.py#L1002-L1006
