### ISSUE TITLE
maybe remove ripemd.py (fallback from hashlib, for RIPEMD160)

### ISSUE THREAD

**Issue by abderraouf-adjal** [spesmilo/electrum#7093]
_Hello,_

I would like to highlight a file that contain a possible dead-code: [/electrum/ripemd.py](https://github.com/spesmilo/electrum/blob/de6f5a8e0357b201b5f0ffe20195b36cad66824d/electrum/ripemd.py)

I see that electrum uses _hashlib_ library to perform RIPEMD160, so does this file have a purpose?

_Kind regards,_

**Comment by SomberNight** [comment]
It is used as a fallback if `hashlib` does not have `ripemd160` available.
https://github.com/spesmilo/electrum/blob/5339e0054c6e473ec4b5858ea9bb11aeb37be109/electrum/crypto.py#L312-L320


Note that `ripemd160` is not guaranteed to be available in `hashlib`:

```
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> hashlib.algorithms_guaranteed
{'sha384', 'shake_256', 'md5', 'sha1', 'sha256', 'sha512', 'shake_128', 'blake2s', 'sha3_256', 'sha3_224', 'sha3_384', 'blake2b', 'sha3_512', 'sha224'}
```

Historically, our Android builds had a hashlib which did not have it.
I think it is not the case anymore but I would have to check.

See the git blame
https://github.com/spesmilo/electrum/commit/56c4a8746f949423d05b9268f79bfe65724cc9e7
https://github.com/spesmilo/electrum/commit/67780bb8b950d0fbb5679ce7a098db70295607a9
https://github.com/spesmilo/electrum/commit/126bbff948840836b3113ebd0c31bc820e847618

related: https://github.com/spesmilo/electrum/pull/3441#issuecomment-349210225

**Comment by SomberNight** [comment]
Note that `cryptography` [does not provide ripemd160](https://github.com/pyca/cryptography/commit/0d6aaf49c1890378ce7ecf741a3a40c859d3b9fb); `pycryptodomex` [has it though](https://github.com/Legrandin/pycryptodome/blob/7bc6d4d548596e5bfa3da0dd253a068b403b7c51/src/RIPEMD160.c).
If `cryptography` had it, we could use it as fallback. (as `cryptography` is a required dependency)
