### ISSUE TITLE
App Unresponsive when pay-to-many on testnet MacOS

### ISSUE THREAD

**Issue by count-null** [spesmilo/electrum#7096]
Using the MacOS v4.0.9 launched in command line with `--testnet`

I have found that when doing a pay-to-many with 4 or more "pay to" addresses, the application becomes unresponsive and must be force quit after clicking "Pay..."

It works fine with less than four addresses.

This is an example payload that broke it:
```
tb1qu4taev8ap6ams50dr5wd9qd4zvjxtt4tfqep8x, 0.01
tb1qnx7sw9vew0utezp4nwng607hwlvcmtc0shwswp, 0.01
tb1qf2fqxnr4af8y9vgqzcv6mp4ll5rexfwgyrtwrz, 0.01
tb1qly499w4gg9h5fevpy3qevxlzkm7wdnf2lcgz86, 0.01
```

I have not tried on mainnet or on a non-MacOS machine.

**Comment by SomberNight** [comment]
That looks like https://github.com/spesmilo/electrum/issues/6914 ?

If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).

**Comment by count-null** [comment]
Switching to dark theme works! Closing since duplicate issue.
