### ISSUE TITLE
Bad TXNS-Inputs-MissingOrSpent on wallet with sufficient money.

### ISSUE THREAD

**Issue by bpracht** [spesmilo/electrum#7097]
I'm using Electrum 4.0.9. I'm on FC 30 and the image was downloaded as an AppImage format today. I suspect it's about as current as it's going to get.

As of last night:
Amount to be sent: 1.66 mBTC Mining fee: 0.01805 mBTC (hope that's fair) MEMPOOL

It results in error dialog:

The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

bad-txns-inputs-missingorspent

My wallet has 1.81005 unconfirmed

Today in the log for Outgoing payments:
2021-03-10 02:27 1.66 Unpaid
2021-03-10 02:20 0.00166 Paid

Balance:
1.81381 mBTC [-0.00376 unconfirmed]

**Comment by SomberNight** [comment]
You might have a local transaction in your wallet (History tab) that this transaction builds on top.
You need to either broadcast or remove the local tx.

**Comment by bpracht** [comment]
I have this:
Date                         Description Amount    Balance
Local [rbf,0.1 sat/b]                     -0.00188 1.81005
Local [rbf,0.1 sat/b]                     -0.00188 1.81193
2021-03-10 02:32                       +1.81381 1.81381

The last one has a checkmark by it and the other two have some other blue computer like icon.
As of 2021-03-11 15:08 EST, my balance is:
 1.81381 mBTC [-0.00376 unconfirmed]

**Comment by SomberNight** [comment]
right-click>Remove the local transactions
