### ISSUE TITLE
Cannot send/receive more than 42 mBTC using Lightning (HTLC max value)

### ISSUE THREAD

**Issue by MundoDasCPUs** [spesmilo/electrum#7100]
Hello, recently i discovery than electrum have a implementation to receive and send only 4294967295 msat in channels, even your inbound channel capacity is bigger than the invoice amount. In next version, please, expand this limit to send/receive in LN. Thanks!  

HTLC value over protocol maximum: xxxxxxxx > 4294967295 msat

Now the electrum version used is Electrum version 4.0.9

**Comment by SomberNight** [comment]
> HTLC value over protocol maximum: xxxxxxxx > 4294967295 msat

Note that as the message says, this is a restrition imposed by the BOLT (Lightning protocol) specs.
The protocol spec says that a single HTLC cannot be larger than ~42 mBTC.

https://github.com/lightningnetwork/lightning-rfc/blob/b201efe0546120c14bf154ce5f4e18da7243fe7a/02-peer-protocol.md#requirements-9
> Adding an HTLC: `update_add_htlc`
> Requirements
>   - A receiving node:
>      - for channels with `chain_hash` identifying the Bitcoin blockchain, if the four most significant bytes of `amount_msat` are not 0:
>          - MUST fail the channel.

A workaround is to use MPP (multi path payments) and hence split the payment into multiple HTLCs, each below the limit.
There has already been some work done towards this on master (there is rudimentary MPP support), although it still needs more work.

**Comment by SomberNight** [comment]
Some things we should check:
- when sending MPP, we should check how the split logic interacts with this HTLC max value
- re submarine swaps, check if support (and maybe implement if not) swaps above HTLC max value

**Comment by MundoDasCPUs** [comment]
The update includes the function called Wumbo in August 2020 don't solved this problem? The electrum don't have implemented?

**Comment by SomberNight** [comment]
No, that's unrelated. You mean `option_support_large_channel`, which is about the max channel capacity only.
https://github.com/lightningnetwork/lightning-rfc/blob/b201efe0546120c14bf154ce5f4e18da7243fe7a/09-features.md

Without `option_support_large_channel`, the max channel capacity is 2**24 sat (~167 mBTC); with it, there is no limit.
We don't currently implement that option; it is better to be cautious with storing large amounts for now. Again, this is unrelated to your opening post.

**Comment by MundoDasCPUs** [comment]
Understood....well if the protocol HTLC cannot be larger than ~42 mBTC, don't have any wallet to send more than this value in LN? Or this protocol is specific of electrum? My question is because i saw a transaction received a invoice in another wallet with 49mBTC.

**Comment by SomberNight** [comment]
As I said,
> this is a restrition imposed by the BOLT (Lightning protocol) specs.
> The protocol spec says that a single HTLC cannot be larger than ~42 mBTC.

As I said,
> A workaround is to use MPP (multi path payments) and hence split the payment into multiple HTLCs, each below the limit.

**Comment by MundoDasCPUs** [comment]
@SomberNight Ok, thanks. Best regards
