### ISSUE TITLE
The BTC / Euro converting view

### ISSUE THREAD

**Issue by Cyberhulp** [spesmilo/electrum#7106]
![Screenshot_20210314_111416](https://user-images.githubusercontent.com/80622974/111064838-a4e02780-84b6-11eb-936d-9818bdbd3710.jpg)
The view how many Euri's are in my wallet, is gone. The view in BTC is still working fine.

**Comment by SomberNight** [comment]
Try changing exchange rate providers: Settings>Fiat>Source

**Comment by Cyberhulp** [comment]
Hey thank you Happy Day. Changing the exchange rate provider did the job. Now I can see again how rich I really am; ahum, kuch, kuch. Simple solutions makes live even better.

![Screenshot_20210314_124724](https://user-images.githubusercontent.com/80622974/111067204-79176e80-84c3-11eb-92a8-6e1bab8f1509.jpg)
