### ISSUE TITLE
Multisig wallet freezes on certain UTXOs (ARM Mac)

### ISSUE THREAD

**Issue by softsimon** [spesmilo/electrum#7108]
I have a multisig Electrum wallet and I am unable to spend from certain UTXOs. Simply opening the "details dialog" of some of the UTXOs in the Coins list causes Electrum to freeze and get stuck on 100% CPU and needs to be force closed, but other UTXOs are fine. There are no clues in the electrum logs to as what is happening.

I tried older versions. I tried clean and reinstall Electrum and set up as a new wallet. Same issue.

Using
Electrum 4.0.9
OSX 11.2.1 on M1 ARM architecture

**Comment by strey450** [comment]
I can help you out with that

**Comment by SomberNight** [comment]
That looks like https://github.com/spesmilo/electrum/issues/6914 ?

If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).

**Comment by softsimon** [comment]
> That looks like #6914 ?
> 
> If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).

Yes, that fixed it for me ..
