### ISSUE TITLE
ELECTRUM WALLET 4.0.9 bugs and crashes

### ISSUE THREAD

**Issue by whynot100** [spesmilo/electrum#7109]
Using wallet 4.0.9 on Mac and every time I try to send btc it either freezes or crash INSTANTLY. I'm coming from wallet 3.3.8 where everything was fine a couple hours before, was able to send with no problem this is new to me so any info will help thanks.

**Comment by whynot100** [comment]
do have 1 unconfirmed transaction in wallet

**Comment by SomberNight** [comment]
When exactly does the freeze/crash happen?

**Comment by whynot100** [comment]
> When exactly does the freeze/crash happen?

if I try to send btc or if I click the unconfirmed transaction. It was freezing last night on "Preparing transaction" now its just crashes as soon as I do one or the other.

**Comment by SomberNight** [comment]
Could be https://github.com/spesmilo/electrum/issues/6914 ?

If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).

**Comment by whynot100** [comment]
<img width="1440" alt="Screen Shot 2021-03-15 at 10 59 43 AM" src="https://user-images.githubusercontent.com/80692581/111174439-cf48e800-857d-11eb-9bfd-b0e0bd60e080.png">

**Comment by whynot100** [comment]
> Could be #6914 ?
> 
> If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).

^ in dark mode same thing this what pops up.

**Comment by whynot100** [comment]
connected to 10 nodes, I'm a nubie to btc wallet for the most part lol 3.8.8 was WAY more simple a couple clicks to do whatever you wanted. Just want to get this resolved its stressful, feeling like my BTC is stuck lol

**Comment by SomberNight** [comment]
I will try to reproduce on a mac.
Regardless, your coins are not stuck as you can always use a sane operating system that does not introduce breaking changes every few months; or even try to use different wallet software and restore from your seed.

**Comment by whynot100** [comment]
somber night helped me out big time

**Comment by SomberNight** [comment]
Why did you close the issue? Have you figured out why it is crashing?

**Comment by SomberNight** [comment]
We want to fix issues for all users. Please help us do that.

>> Could be #6914 ?
>> 
>> If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).
>
> ^ in dark mode same thing this what pops up.

To be clear, there is a dark mode setting as an operating system preference in macOS; and there is also a dark theme in Electrum:
menubar>`Tools`>`Preferences`>`General`>`Color theme`.
Have you tried setting the color theme to dark in the Electrum preferences?
