### ISSUE TITLE
electrum wallet XPUB works not anymore

### ISSUE THREAD

**Issue by AxlRoseFoley** [spesmilo/electrum#7111]
I connected my electrum wallet to Accointing.com account with the XPUB of the wallet.
Several weeks everything worked fine. Since some days there is an error on Accointing.com reportet but they can't solve the problem. So the problem must be at electrum.

Any ideas?

**Comment by ecdsa** [comment]
no, sorry. 
unless you tampered with you gap limit, but if that was the case you would know.

**Comment by AxlRoseFoley** [comment]
never the less Accointing.com says that the XPUB isn't work anymore


here is the answer from Accointing.com
**********************************************It seems your address is incorrect, nothing can be found for it on blockchain.com either.

Blockchain.com Explorer | BTC | ETH | BCH

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Blockchain.com Explorer | BTC | ETH | BCH

The easiest and most trusted transaction search engine and block explorer.
 |

 |

 |




To be on the safe side I have converted the whole thing into an xpub   (https://jlopp.github.io/xpub-converter/) 
Unfortunately, no result either:
https://www.blockchain.com/btc/xpub/xpub68ph4FzEDY8wDx7uEi5QswGTjEAuYKpn3cjEn3B9LiG629bC2rj4aN7ffaconVFTQU5HUnvkmZZ3nxNnK15pLYwdhLsvCUmiPCQrv4iPy9P?view=balances


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Blockchain.com Explorer | BTC | ETH | BCH

The easiest and most trusted transaction search engine and block explorer.
 |

 |

 |







**********************************************
    Am Dienstag, 16. März 2021, 15:57:45 MEZ hat ThomasV ***@***.***> Folgendes geschrieben:  
 
 


no, sorry.
unless you tampered with you gap limit, but if that was the case you would know.

**Comment by SomberNight** [comment]
> To be on the safe side I have converted the whole thing into an xpub   (https://jlopp.github.io/xpub-converter/) 

Right but do you know what you are doing though?
I just manually converted the xpub back to a zpub and found some transactions there.
Try restoring an Electrum wallet from zpub below and see tx history.

```
>>> convert_xkey("xpub68ph4FzEDY8wDx7uEi5QswGTjEAuYKpn3cjEn3B9LiG629bC2rj4aN7ffaconVFTQU5HUnvkmZZ3nxNnK15pLYwdhLsvCUmiPCQrv4iPy9P", "p2wpkh")
"zpub6nVDfbL4WuDtvYW8uRefJ7TU5AToRZomsqmgLpxv6j1r8MDeYB4BpVRwhzXynJZJDkJtyk7sgtG9ZXbukPuqw2JqS2GmNJQgveY9hCCP3de"
```
