### ISSUE TITLE
Cannot recover p2wpkh wallet using an xpub

### ISSUE THREAD

**Issue by stevenroose** [spesmilo/electrum#7115]
It seems that the "master key" setup dialog expects ypubs and zpubs etc when you want to do non-p2pkh wallets.

There should be a way to input a regular BIP32 xpub and then chose which address type to use, like p2pkh for bip44, p2wpkh for bip84 etc.

**Comment by SomberNight** [comment]
That would defeat the point of ypubs and zpubs in the first place.
You are presumably looking at this issue as a highly technical user, but note that this would complicate the UX for casual users.
Note that if you exported such an xpub/ypub/zpub from Electrum, it would always have the expected type/header.

For the time being, you can convert the xpub to ypub/zpub, e.g. using the `convert_xkey` CLI command.
Somewhat longer term we would also accept output script descriptors (https://github.com/spesmilo/electrum/issues/5694) in that (or a replacement) dialog.
