### ISSUE TITLE
Che cosa è uploading electrum 

### ISSUE THREAD

**Issue by giusicb** [spesmilo/electrum#7116]

**Comment by giusicb** [comment]
Salve non riesco a dopo inviare i miei bt 
All avvio della moneta mi dice Che dovrei fare un altro server o uploading electrum potete consigliarmi

**Comment by SomberNight** [comment]
Please upload a screenshot of the error message.
Or alternatively copy-paste the full error message text here.

**Comment by giusicb** [comment]
Thanks so: the server returned an error when broadcasting the trasanction. Consider traying to connect to a different server or updating electrum 

B-ad-txns-imputs-missingorspent 


Somebody can help me please ?

**Comment by SomberNight** [comment]
You might have a local transaction in your wallet that this transaction builds on top. You need to either broadcast or remove the local tx. Check the History tab.
