### ISSUE TITLE
Electrum hangs for 20 seconds on GUI exit

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#7118]
@SomberNight this might be related to the recent changes that make `stop` async

it specifically occurs when certain servers are in my list of peers.
```
I/i | interface.[electrum.emzy.de:50002] | disconnecting due to: CancelledError()
I/i | interface.[electrum.bitkoins.nl:50512] | disconnecting due to: CancelledError()
I/i | interface.[VPS.hsmiths.com:50002] | disconnecting due to: CancelledError()
I/i | interface.[electrumx.electricnewyear.net:50002] | disconnecting due to: CancelledError()
I/i | interface.[fulcrum.grey.pw:51002] | disconnecting due to: CancelledError()               <-- waits for 30 seconds before outputing next line
I/i | interface.[btc.electroncash.dk:60002] | disconnecting due to: CancelledError()
I/n | network | taskgroup stopped.
I | daemon.Daemon | removing lockfile
I | daemon.Daemon | stopped
I/p | plugin.Plugins | stopped
```

**Comment by SomberNight** [comment]
That server is running Fulcrum, so might be related: https://github.com/spesmilo/electrum/issues/7083

However I cannot seem to reproduce... Can you reliably reproduce?

If so, what version of `aiorpcx` do you have? Note that if you have a `packages` folder, Electrum will use the dependency from there.
If other than `aiorpcx==0.18.7`, could you try with that? That has https://github.com/kyuupichan/aiorpcX/commit/82048a219aac575f91a07102fa7f818288846826

**Comment by SomberNight** [comment]
Ok, I've managed to reproduce. It happens somewhat reliably if multiple connected servers are running Fulcrum.
Put e.g. this in your `recent_servers`:
```
[
    "btc.electroncash.dk:60002:s",
    "e2.keff.org:50002:s",
    "blackie.c3-soft.com:57002:s",
    "electrumx.no-ip.eu:50002:s"
]
```

It is fixed by that change in `aiorpcx`.

**Comment by ecdsa** [comment]
indeed, updating aiorpcx seems to have fixed it. thanks
