### ISSUE TITLE
unpaid status

### ISSUE THREAD

**Issue by cem2021** [spesmilo/electrum#7124]
I have a newly downloaded electrum wallet, 4.09.  Used it twice to receive crypto with no issues but now for my third time, I have a major issue with having an unpaid status for the past 8 days, since 03/12.  The icon keeps blinking from icon to unknown back to icon.  The exchange says withdrawal successful.  New to this wallet, had pretty good reviews. Can you please help me as I cannot afford to just lose these funds please!!!   Is this a bug you can fix or at least lend some support?--

**Comment by SomberNight** [comment]
What colour is the orb/circle in the bottom right?
Do you the transaction in the History tab?

>  The exchange says withdrawal successful

Do you have a TXID (transaction ID)? Try looking it up on a block explorer such as https://blockstream.info/

**Comment by cem2021** [comment]
The color of the orb under "status" is tan with the amount of the transaction to the left and it says unpaid at the right.
I looked up the transaction aed7c9618dbbe6061666a733ae77ff1c7a35fb16779473d2298add56362e1c89

**Comment by SomberNight** [comment]
> The color of the orb under "status" is tan with the amount of the transaction to the left and it says unpaid at the right

No, I mean the orb in the bottom right of the whole window; the network orb. That shows whether you are connected to a server.
Should be green or blue.

Also, like I said, please look at the "History" tab. That is the authoritative source of what has happened.

>  I looked up the transaction aed7c9618dbbe6061666a733ae77ff1c7a35fb16779473d2298add56362e1c89

Do you see the expected address (your address) among the outputs of this transaction?

**Comment by cem2021** [comment]
The network orb is green.  Yes I do see my address listed.  It is the one that starts with bc1q9f6.

**Comment by SomberNight** [comment]
So how does the History tab look? Is the tx there?

Maybe upload a screenshot of both the History tab and the Receive tab... you can redact private information (e.g. other txs; overall balance)

**Comment by cem2021** [comment]
![1EC4EF0C-36DE-4C0C-8B4B-687540AFDCC1](https://user-images.githubusercontent.com/81054904/111890711-
![26BD295C-3A63-4A7E-8E4C-9CC12DC6FA90](https://user-images.githubusercontent.com/81054904/111890723-a2a03080-89c2-11eb-8154-b66a6155e882.jpeg)
8bf9d980-89c2-11eb-88b8-f274710875ce.jpeg)

**Comment by cem2021** [comment]
![1EC4EF0C-36DE-4C0C-8B4B-687540AFDCC1](https://user-images.githubusercontent.com/81054904/111890760-032f6d80-89c3-11eb-96f1-1418ce2b1aaf.jpeg)

**Comment by SomberNight** [comment]
The History tab shows the tx. Just look at the dates and amounts, it is there; it's the topmost one.
You have received `0.144355 BTC` as part of that tx, just as the block explorer says.
However the payment request you have created is for a higher amount: `0.144855 BTC`, hence it cannot be marked paid.
The sender did not fulfill what you have requested as they underpaid.

**Comment by cem2021** [comment]
Thank you for teaching me where to look for the answers.  I now see what happened and I am happy for your help.
