### ISSUE TITLE
WORST WALLET EVER

### ISSUE THREAD

**Issue by bmode2259** [spesmilo/electrum#7128]
Hackers stole my bitcoins, my wallet was offline, 
and never my wallet ask me for password  for the transaction (that they stole me)
NEVER AGAIN

**Comment by ecdsa** [comment]
your probably downloaded malware, or your seed was stolen offline.
anyway, this is more a rant than a bug report, we cannot do anything with it

**Comment by bmode2259** [comment]
so whats the point of password ?
where is my security?

**Comment by verretor** [comment]
> so whats the point of password ?
> where is my security?

If you want maximum security, you should get a hardware wallet.
