### ISSUE TITLE
Increase Fee Crash Electrum for Mac

### ISSUE THREAD

**Issue by szola1** [spesmilo/electrum#7132]
Hi

I am trying to increase the fee on my transaction but whenever I try to do this my application freezes and I have to "force quit" the app. After clicking "increase fee" the normal pop-up appears where you enter the new fee but as soon as I click "ok" the app freezes. 

The same thing happens if I try to cancel the transaction or view the transaction, except in this case the app freezes as soon as I click view transaction.

**Comment by SomberNight** [comment]
That looks like https://github.com/spesmilo/electrum/issues/6914 ?

If so, try [dark theme workaround](https://github.com/spesmilo/electrum/issues/6914#issuecomment-770245046).

**Comment by szola1** [comment]
Yes this worked, Thanks!
