### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by Croney5** [spesmilo/electrum#7139]
Where can I ask my question about refunding my bitcoins back to my banc account?
The website refers only to a public forum

**Comment by SomberNight** [comment]
Electrum is a free software project. There is no way to buy or sell bitcoins directly using Electrum; it can only be used to store/receive/send them, hence you must have bought your bitcoins elsewhere. Further, Electrum is non-custodial, at any point in time the user is in full control of their coins. You are your own bank. As we don't have control over your coins we cannot possibly "refund" you.
