### ISSUE TITLE
Edit saved  outgoing payment [Feature]

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7148]
Add option to edit saved outgoing payment
![image](https://user-images.githubusercontent.com/388716/112768983-b8c67600-8fec-11eb-9b13-8bfe523a78ab.png)

This option would repopulate the top fields with the tx information, amount address and description, and then delete it from the list.

**Comment by ecdsa** [comment]
not relevant with version 4.1. 
payment will be removed from the list as soon as they are paid

**Comment by SomberNight** [comment]
Though there could still be an option to edit an unpaid invoice.

**Comment by Transisto** [comment]
Yes, I only meant editing those still not sent.

**Comment by ecdsa** [comment]
An invoice is created by the receiver, and possibly signed. I don't think there is value in letting the payer edit it.

**Comment by Transisto** [comment]
Didn't know that panel was used for lightning invoices, We're using that feature only for preparing a batch of on chain transactions.

**Comment by ecdsa** [comment]
@Transisto could you explain which fields of the invoice you would want to edit, and why it is useful in batch payments?

**Comment by Transisto** [comment]
The description. Most of the time everything is right but the description
was forgotten. The amount and address then need to be retrieved again to
redo with a description.
