### ISSUE TITLE
Unauthorized withdrawal

### ISSUE THREAD

**Issue by wiccario** [spesmilo/electrum#7149]
Today, when accessing my Electrum wallet, I saw an unauthorized withdrawal of bitcoins. The version I use is 4.0.9. Who was it that withdrew my bitcoins without my authorization?
![withdrawal](https://user-images.githubusercontent.com/81544705/112782667-f266a380-9023-11eb-83c9-05ec01226037.png)

**Comment by ecdsa** [comment]
Electrum is not a custodial service. We have no way to know who spent those coins.

**Comment by wiccario** [comment]
My seed is well hided. There's no way someone had stole it!!!
By the way, I'm facing some trouble by withdrawal my btc to another wallet. It's incredible that someone else could do it and I couldn't.

**Comment by ecdsa** [comment]
The Cryptotab outputs are small, I guess they might be too expensive to redeem.
That is probably why you are having some trouble spending them. (although you give no detail)
Why do you think the thief did not take them?
