### ISSUE TITLE
Funds stuck in Lightning channel after closing/unsuccessful closing of the channel 

### ISSUE THREAD

**Issue by VladimirVil** [spesmilo/electrum#7175]
Hi all

I have 0.002BTC locked in a lightning node channel. Originally I tried to force-close it, but from the beginning getting the same error(image attached).
Right now I am on Electrum 4.0.9, but I believe the channel was opened on an earlier version - 4.0.5 or 4.00.7 (but not sure 100%). Also, at least 5 other channels were opened and closed (using force close) without any issues)

List of channels (the problematic one is the           "channel_id":"0fb1f8d45cd60d6999bea1d816adb9c87fa7625228cca60f4e21c63be046c9f6", )

```
>>> list_channels()
[
    {
        "channel_id": "fdbc3b5ffa6f3fca45fbbaf2189c6220ff095801ff96b36322ebfd214fb2e638",
        "channel_point": "39e6b24f21fdeb2263b396ff015809ff20629c18f2bafb45ca3f6ffa5f3bbcfd:1",
        "local_balance": 202000,
        "local_reserve": 2020,
        "local_unsettled_sent": 0,
        "peer_state": "DISCONNECTED",
        "remote_balance": 0,
        "remote_pubkey": "03d28ac32e13a26bc2bc4c2e24adde07d8db2c27557de8047767e41537304bc64d",
        "remote_reserve": 2020,
        "remote_unsettled_sent": 0,
        "short_channel_id": "666830x1885x1",
        "state": "REDEEMED"
    },
    {
        "channel_id": "93ed49caac05df18d7c464eb37b877985115cc5aab4241914a28f63c2b7f709c",
        "channel_point": "9d707f2b3cf6284a914142ab5acc15519877b837eb64c4d718df05acca49ed93:1",
        "local_balance": 200000,
        "local_reserve": 2000,
        "local_unsettled_sent": 0,
        "peer_state": "DISCONNECTED",
        "remote_balance": 0,
        "remote_pubkey": "034c75c8349d6b11f601d7063d8dc306f8a464bbfc1eaa24bab951247188d44c34",
        "remote_reserve": 2000,
        "remote_unsettled_sent": 0,
        "short_channel_id": "655029x1368x1",
        "state": "REDEEMED"
    },
    {
        "channel_id": "b94d9b111bfd93ee9125db1d36188e8cfd2e141f53d15940ce51bb2cf49c3764",
        "channel_point": "64379cf42cbb51ce4059d1531f142efd8c8e18361ddb2591ee93fd1b119b4db9:0",
        "local_balance": 250000,
        "local_reserve": 2500,
        "local_unsettled_sent": 0,
        "peer_state": "DISCONNECTED",
        "remote_balance": 0,
        "remote_pubkey": "02f31ff9c53e1773431f248ea81b97f09f98bb8798747e67e9f080d1d20b7d644d",
        "remote_reserve": 2500,
        "remote_unsettled_sent": 0,
        "short_channel_id": "655171x1338x0",
        "state": "REDEEMED"
    },
    {
        "channel_id": "0fb1f8d45cd60d6999bea1d816adb9c87fa7625228cca60f4e21c63be046c9f6",
        "channel_point": "f7c946e03bc6214e0fa6cc285262a77fc8b9ad16d8a1be99690dd65cd4f8b10f:1",
        "local_balance": 200000,
        "local_reserve": 2000,
        "local_unsettled_sent": 0,
        "peer_state": "REESTABLISHING",
        "remote_balance": 0,
        "remote_pubkey": "0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0",
        "remote_reserve": 2000,
        "remote_unsettled_sent": 0,
        "short_channel_id": null,
        "state": "SHUTDOWN"
    },
    {
        "channel_id": "52483242ca03609b32b5e0b2677b18a3fd722a09d3ebfa0887c669e964f5a843",
        "channel_point": "42a8f564e969c68708faebd3092a72fda3187b67b2e0b5329b6003ca42324852:1",
        "local_balance": 210000,
        "local_reserve": 2100,
        "local_unsettled_sent": 0,
        "peer_state": "DISCONNECTED",
        "remote_balance": 0,
        "remote_pubkey": "03ecbf7a937aa362ea3af9395320072a0006c01195cf74f4d26467f9c5d095019e",
        "remote_reserve": 2100,
        "remote_unsettled_sent": 0,
        "short_channel_id": null,
        "state": "REDEEMED"
    },
    {
        "channel_id": "0c0ad9dbebba3df4255fc50a49125046583fd3fb1097a2a0951f407cc6289451",
        "channel_point": "519428c67c401f95a0a29710fbd33f58465012490ac55f25f43dbaebdbd90a0c:0",
        "local_balance": 247514,
        "local_reserve": 2500,
        "local_unsettled_sent": 0,
        "peer_state": "DISCONNECTED",
        "remote_balance": 2485,
        "remote_pubkey": "02f31ff9c53e1773431f248ea81b97f09f98bb8798747e67e9f080d1d20b7d644d",
        "remote_reserve": 2500,
        "remote_unsettled_sent": 0,
        "short_channel_id": "655269x1352x0",
        "state": "REDEEMED"
    }
]
>>> 
```

Attaching some more information in the screenshots

Please   help to identify root cause of the issue

Best Regards,
 V.
![11electrum_version](https://user-images.githubusercontent.com/23189384/113506868-887c5b80-9547-11eb-8f5a-116807feec72.png)
![12channel_details](https://user-images.githubusercontent.com/23189384/113506869-89ad8880-9547-11eb-919d-13d770fa578c.png)
![13force_close_channel_1](https://user-images.githubusercontent.com/23189384/113506870-89ad8880-9547-11eb-99dd-73a0394af637.png)
![14force_close_channel_2-error-message](https://user-images.githubusercontent.com/23189384/113506871-8a461f00-9547-11eb-9f96-1a6f5cc11f37.png)
![15LN-LNBIG-REestablishing](https://user-images.githubusercontent.com/23189384/113506872-8a461f00-9547-11eb-91ed-543590a10d89.png)

**Comment by ecdsa** [comment]
The funding transaction f7c946e03bc6214e0fa6cc285262a77fc8b9ad16d8a1be99690dd65cd4f8b10f is not in the blockchain.
Maybe it was dropped from the memory pool, or maybe it was never broadcast.

Thus, no funds are stuck in that channel. 

Is the funding transaction visible in your history?

**Comment by VladimirVil** [comment]
Hi
Thanks for the fast reply
I do have the history of transactions in the wallet. There are 6 channels opened, I assume , based on the amount = 0.002btc ( how could  verify this is the relevant transaction?) it is :
Transaction ID:
9d707f2b3cf6284a914142ab5acc15519877b837eb64c4d718df05acca49ed93

Attaching an image as well

Let me know if any additional info needed 
Regards,
 V.
 
![transaction_info](https://user-images.githubusercontent.com/23189384/113507317-fc1f6800-9549-11eb-914a-d194c4e72394.png)

**Comment by SomberNight** [comment]
>  I do have the history of transactions in the wallet. There are 6 channels opened, I assume , based on the amount = 0.002btc ( how could verify this is the relevant transaction?) it is :
Transaction ID:
9d707f2b3cf6284a914142ab5acc15519877b837eb64c4d718df05acca49ed93

That channel point has already been spent, see:
https://blockstream.info/tx/9d707f2b3cf6284a914142ab5acc15519877b837eb64c4d718df05acca49ed93?expand
https://blockstream.info/tx/2515ae3e4788afa4315031e3dd64356be7a9352986fb60661bf79b358ac2d020?input:0

**Comment by SomberNight** [comment]
maybe related: https://github.com/spesmilo/electrum/issues/7177

**Comment by SomberNight** [comment]
In the "Channel Details" dialog, what happens if you click the funding outpoint?

**Comment by VladimirVil** [comment]
Thanks SomberNight.
 What does 7177 actually mean ?
 
Also, If I click on "funding outpoint" I am getting an error(screenshot attached)

![click_on_funding_outpoint](https://user-images.githubusercontent.com/23189384/113514762-d0fc3f00-9570-11eb-821b-53f66be5ff20.png)

**Comment by SomberNight** [comment]
> Also, If I click on "funding outpoint" I am getting an error(screenshot attached)

Right, so that means the wallet history does not have the funding tx.

> What does 7177 actually mean ?

It means there was an electrum-server-related error during the channel open, and the tx never got broadcasted. In that case the channel would appear in the Channel tab in an "opening" state but it would never open of course. In that case your coins have never been spent (they were not put into a channel).
Basically the bug is that the program shows you a channel when there is none.

**Comment by VladimirVil** [comment]
@SomberNight  got it. Thank you a lot for the fast help! :)

**Comment by SomberNight** [comment]
Ok, so I am closing this for https://github.com/spesmilo/electrum/issues/7177
