### ISSUE TITLE
Cannot withdraw funds

### ISSUE THREAD

**Issue by bhicks50** [spesmilo/electrum#7176]
When trying to transfer funds to another wallet I get a message that the transaction is being process.  The program closes and nothing happens.  I am using 4.1.1 at this time the problem started 4.01

**Comment by SomberNight** [comment]
Could you upload a screenshot of the error?

**Comment by bhicks50** [comment]
I went back two days later and everything worked Thank for your quick reponse Sent from Mail for Windows 10 From: ghost43Sent: Thursday, April 8, 2021 5:24 AMTo: spesmilo/electrumCc: bhicks50; AuthorSubject: Re: [spesmilo/electrum] Cannot withdraw funds (#7176) Could you upload a screenshot of the error?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
