### ISSUE TITLE
mpp splitting improvements

### ISSUE THREAD

**Issue by bitromortac** [spesmilo/electrum#7180]
Currently, when we have a single channel and want to send a large payment (yet to be defined), we only try to send over the channel with the large amount until we have to give up. Instead, we could detect the large payment amount and split it. If the payment amount is intermediate and we can't succeed to send it, we should be able to send it in smaller chunks over the single channel.

When having more than one channel and multiple payment attempts already happened, we should increase the number of splits dynamically, which is why a feedback into the splitting algorithm is needed (via split penalty).

To solve these issues, I suggest to extend the split algorithm to also allow for sub-splittings within a channel. When we quantify an amount as large, we should already allow for splits from the get go. Then, one should track the attempts keyed by the sending amount and make the split penalty dependent on that number. When a new amount is encountered, we should reset the split penalty.

I would start to work on this now and be happy for feedback.

**Comment by SomberNight** [comment]
Sounds good!

It's a bit hard to give non-generic feedback without seeing some code or suggested API changes. :P
But again, the ideas sound good.

Feel free to refactor related code if it makes things simpler/easier (but do that in separate commits).

**Comment by bitromortac** [comment]
I ended up redesigning the whole splitting algo in #7180, so unfortunately no small diffs, but I think it is now easier to understand.

**Comment by bitromortac** [comment]
#7180 addresses only splitting via a single channel, however the feedback still needs to be implemented. In particular when connected to a hub with many large channels, there are too many routes for a singlepart payment to try. When the receiving end doesn't have the necessary funds inside a single channel  (but distributed over some channels) to support the payment, we will likely give up after 10 attempts. Alternatively we should also be able to detect the receiving channels' balance and factor that in via liquidity hints (need to check whether we do that already).
