### ISSUE TITLE
Open channel to Electrum trampoline error

### ISSUE THREAD

**Issue by billylarsson** [spesmilo/electrum#7182]
I'm getting this error: 

Exception: Remote peer reported error [DO NOT TRUST THIS MESSAGE]: b'local/remote feerates are too different: remoteFeeratePerKw=1166 localFeeratePerKw=20785'

Is it a bug or something I can do about it?

**Comment by ecdsa** [comment]
the trampoline (eclair) thinks Electrum's fee estimate is to low.
your fee estimate comes from the Electrum server.
I suggest retrying at a later time, or trying with another Electrum server.

Fees went down yesterday, but 1166 sat/kw is really very low.. 
do you know which server you were connected to?

**Comment by billylarsson** [comment]
> do you know which server you were connected to?

I use my own server (electrs) with default values, so this is most likeley my fault.

**Comment by ln2max** [comment]
Workaround: use non-trampoline Lightning channels (Tools | Preferences | Lightning | uncheck "Use trampoline routing").

**Comment by Kixunil** [comment]
Didn't try LN with Electrum yet, is it possible to connect to a different trampoline? Just to check that indeed it's `electrs` bug and not a weird trampoline.

**Comment by ln2max** [comment]
On Mon, Jun 14, 2021 at 05:26:40AM -0700, Martin Habovštiak wrote:
>Didn't try LN with Electrum yet, is it possible to connect to a different trampoline? Just to check that indeed it's `electrs` bug and not a weird trampoline.

There are 3 hard-coded trampolines in Electrum, and I tried all of them
with the same result.
