### ISSUE TITLE
Installwizard.py crashes if you try to go back to step 1

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#7189]
Got a crash. To reproduce:
Electrum -> New/Restore wallet -> Standard -> I already have a seed -> enter seed + tick Options/BIP39 seed -> go to the derivation path menu, then click Back , Back, Back to go to phase 1 (step before I already have a seed). It'll crash with this:

![bugtrace](https://user-images.githubusercontent.com/6549887/113936816-de6f2e80-97e7-11eb-86f9-e28f83da6b58.png)

Also our automated crash report does not work:

![crashof crash](https://user-images.githubusercontent.com/6549887/113936844-e9c25a00-97e7-11eb-91d1-21738eaa1dba.png)

**Comment by ecdsa** [comment]
thanks, this explains #6301

**Comment by SomberNight** [comment]
No longer relevant. The qt wizard was rewritten mostly from scratch.
