### ISSUE TITLE
Version 4.1.1 android 8 btc sending error

### ISSUE THREAD

**Issue by darksiders2** [spesmilo/electrum#7190]
After updatin from 4.09 to 4.1.1 
Getting error while trying to sent fund.please help.
![Capture+_2021-04-08-16-58-05](https://user-images.githubusercontent.com/21069653/114028307-93a7f200-988d-11eb-9f96-0a40f9ec1cfd.png)

**Comment by SomberNight** [comment]
Thanks very much for the report!
We will fix this soon.
