### ISSUE TITLE
How to confirm integrity of multi-signature wallet created using BIP39 mnemonic?

### ISSUE THREAD

**Issue by sunknudsen** [spesmilo/electrum#7194]
Noticed “Wallet” / “Seed” is greyed out when 2 of 3 multi-signature wallet is created using BIP39 mnemonic extended with passphrase and two hardware wallets.

Using paper backup of 24-word BIP39 mnemonic and passphrase (in one’s mind), how can one confirm integrity of wallet without requiring access to hardware wallets (in other words, without regenerating wallet from scratch).

**Comment by SomberNight** [comment]
I will give a more generic answer than your specific case. It's hard to give a very specific answer though as "confirm integrity" is not a precise enough question.

-----

What kind of attack/bug do you have in mind; i.e. what is your threat model here?

I assume we are considering "some keys/addresses getting replaced/corrupted in the wallet file".
I have a few scenarios in mind you might want to consider, but maybe you have others:

Consider the Cartesian product of these sets:

- set1 ("history")
    - HAS_HISTORY: wallet already has some history (txs touching its addresses)
    - NO_HISTORY: wallet has no history
- set2 ("when")
    - CREATION: upon wallet file creation
    - EXISTING: at some point when using an existing wallet file
- set3 ("why")
    1. reproducible bug that always happens under some circumstance
    2. rare probabilistic bug
    3. malware on the system / intelligent adversary
- set4 ("how")
    - a) xpub(s) match xprv; but addresses do NOT match the xpub(s)
    - b) xpub(s) do NOT match xprv; and all addresses match the xpub(s)
    - c) xpub(s) do NOT match xprv; and some addresses do NOT match the xpub(s)
    - d) xpub(s) or addresses fail their own checksum (e.g. bitflip)
    - e) xprv do not match seed (but xpub matches xprv, and addresses match xpub)


-----

Every time a deterministic wallet is opened, we randomly check a few addresses whether they can be re-derived from the xpubs:

https://github.com/spesmilo/electrum/blob/1d8b1ef69897ccb94f337a10993ca5d2b7a46741/electrum/gui/qt/main_window.py#L527
https://github.com/spesmilo/electrum/blob/1d8b1ef69897ccb94f337a10993ca5d2b7a46741/electrum/wallet.py#L2848-L2856

As intended, this automatically protects against every case involving either `a` or `c`.

As a byproduct, this automatically protects against every case involving `d` for the xpubs, and the addresses are covered by the Synchronizer subscribing to all addresses to sync the history.

This leaves us with `b` and `e`.

-----

`try_detecting_internal_addresses_corruption` also handles {`HAS_HISTORY`}x{`*`}x{`*`}x{`b`,`e`} as this attack/bug would replace *all* shown history which would likely raise red flags to the user.


This leaves us with {`NO_HISTORY`}x{`*`}x{`*`}x{`b`,`e`}.

-----

Re `b`:

Note that for USB-connected hardware wallets specifically, a successful pairing of the device implies no corruption for the corresponding xpub.

The xprv, when stored in the wallet (e.g. for software seeds), is usually stored encrypted with the password; hence its integrity cannot be compared against the xpub without the user entering the password.
When the UI prompts you for the wallet password, the integrity of the xprv->xpub link is checked.
One example is when you change the wallet password.

https://github.com/spesmilo/electrum/blob/1d8b1ef69897ccb94f337a10993ca5d2b7a46741/electrum/keystore.py#L571-L578

So, e.g. changing your wallet password (even to the same password) covers every case involving `b`.

-----

Re `e`:

Note that it means the private keys are available and you can spend from the wallet, but you will run into problems when trying to restore it from seed.

Hence, (`*`,`*`,`3`,`e`) does not make much sense: malware would not leave you the option of moving the coins.

AFAICT there is no defense implemented atm against {`NO_HISTORY`}x{`*`}x{`1`,`2`}x{`e`}

-----

Note that re-creating your wallet from your backup (especially on a different machine), and manually comparing a few generated addresses, would detect ALL scenarios mentioned above.

Like the old mantra says, "test your backups".
At the very least, especially for significant amounts (e.g. cold storage), you should test the backup before receiving your first tx. That is, you should re-create the wallet file from scratch, only using your backups. That would instantly eliminate all the `CREATION` and all the `NO_HISTORY` cases.
This is definitely what I would recommend.

-----

Note that in your specific case of a multisig wallet where some cosigners are hardware wallets, and you don't have access to the hardware wallets, you can still test the full "integrity" (i.e. all cases above) of the other cosigners if you recreate the wallet file (substituting the hardware cosigners with their xpub), and compare some addresses manually.

**Comment by sunknudsen** [comment]
Hey @SomberNight, thanks so much for the thorough answer.

It sheds light on how well thought-out Electrum is and how lucky we are as users (learned a lot, thanks!).

I will focus my question a little...

When one creates a 2 of 3 multi-signature wallet using an Electrum mnemonic (vs a BIP39 mnemonic) extended with passphrase and two hardware wallets (using `electrum make_seed --nbits 264 --offline` for example), to verify if Electrum mnemonic paper backup matches wallet, one can use “Wallet” / “Seed”.

That option is not available when using BIP39 mnemonic.

When using a BIP39 mnemonic, is there a way to verify if paper backup matches wallet without recreating wallet?

Hoping there exists a safe way to run a command (in console perhaps) to enter BIP39 mnemonic, derive its master public key and compare it with wallet master public key (which, I believe, would confirm backed up BIP39 mnemonic and passphrase match wallet... equivalent to using “Wallet” / “Seed”).

That being said, simulating creating a new multi-signature wallet using BIP39 mnemonic extended with passphrase appears to solve the above use case given master public key is displayed.

Is this a reliable way to determine if paper backup and passphrase match wallet using “Wallet” / “Information”?

> We do not guarantee that BIP39 imports will always be supported in Electrum.

Also, is it safe to use BIP39 mnemonics with Electrum (which increases interoperability)?

> That is, you should re-create the wallet file from scratch, only using your backups.

Great advice!

Thanks again for helping out. 🤓

**Comment by SomberNight** [comment]
> That being said, simulating creating a new multi-signature wallet using BIP39 mnemonic extended with passphrase appears to solve the above use case given master public key is displayed.

Yes, you can do simply do that. Just start creating the wallet in the wizard and stop when the xpub gets displayed and compare that with what is shown in Wallet>Information.
(Recreating the whole wallet is even better though.)

> Is this a reliable way to determine if paper backup and passphrase match wallet using “Wallet” / “Information”?

Yes, this tests that particular cosigner (obviously it does not test the other cosigners, e.g. hardware wallets in your case).

> Also, is it safe to use BIP39 mnemonics with Electrum (which increases interoperability)?

Sure, it is safe. The warning text is there because writing down just the words is not really a sufficient backup for a BIP39 seed (while it is for an electrum seed): you also need at least a derivation path and the script type used.

> Hoping there exists a safe way to run a command (in console perhaps) to enter BIP39 mnemonic, derive its master public key and compare it with wallet master public key (which, I believe, would confirm backed up BIP39 mnemonic and passphrase match wallet... equivalent to using “Wallet” / “Seed”).

I recommend using the wizard, as above, instead.

If you are really so inclined, you can run something like this in the Qt console though:
```
>>> electrum.keystore.from_bip39_seed(seed="fiscal acid lens forest tackle luggage damage vault bunker cat unlock assume", passphrase="", derivation="m/48'/1'/0'/2'", xtype="p2wsh").xpub
'Vpub5kmgCCFuDAV6F9qjcic2SgnZfv5vXnfzgwdBTi8BVRK3Yjx3bjsTfeM8n6cvSAQYigAeRKvqK9uMogm4LXzQMW8rhAGRKNsud4u6ewLCuvZ'
```
Note that the wallet file remembers the last few commands ran in the Qt console; but if your wallet file is encrypted this should not be an issue.

**Comment by sunknudsen** [comment]
Hey @SomberNight, thanks again for your generous answers.

> Sure, it is safe. The warning text is there because writing down just the words is not really a sufficient backup for a BIP39 seed (while it is for an electrum seed): you also need at least a derivation path and the script type used.

It is my understanding that in the context of Electrum multi-signature SegWit wallets, script type is always `p2wsh` and default derivation path is `m/48'/0'/0'/2'`.

I assume both could be found in docs at a later time when trying to rebuild wallet from paper backups. Is this assumption correct?

> I recommend using the wizard, as above, instead.

👍

> If you are really so inclined, you can run something like this in the Qt console though:

Thanks so much for sharing!

> Note that the wallet file remembers the last few commands ran in the Qt console; but if your wallet file is encrypted this should not be an issue.

Thanks for mentioning this... is there a way to clear history?

Again, thanks so much for helping out.

**Comment by SomberNight** [comment]
> It is my understanding that in the context of Electrum multi-signature SegWit wallets, script type is always p2wsh and default derivation path is m/48'/0'/0'/2'.
> I assume both could be found in docs at a later time when trying to rebuild wallet from paper backups. Is this assumption correct?

The defaults reflect current best practices and might be updated as that changes.
Note that the support of multi-signature wallets with bip39/hww cosigners in Electrum predates the segwit softfork;
clearly the defaults were different then. (they were `p2sh` with path `m/45h/0` (the current "legacy" option))

If you want to avoid the headache of having to write down this stuff in addition to the seed words, use electrum seeds.

>> Note that the wallet file remembers the last few commands ran in the Qt console; but if your wallet file is encrypted this should not be an issue.
>
> Thanks for mentioning this... is there a way to clear history?

`window.console.history.clear()`  clears it from memory; and then clears it from the file after you close the wallet
