### ISSUE TITLE
4.1.2 on windows. No fx rate, can't check for updates.

### ISSUE THREAD

**Issue by 1datatec** [spesmilo/electrum#7199]
Hey, updated recently to 4.1.2. Now when i launch it says no fx rate. If i try to close it hangs. If i go to check for updates takes it over a minute. 4.1.1 was fine.

**Comment by SomberNight** [comment]
Could you upload [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?

**Comment by 1datatec** [comment]
Nop, it works fine today all day. Sorry.
