### ISSUE TITLE
Creating New Transaction With Earlier Transaction Unconfirmed

### ISSUE THREAD

**Issue by schulzemic** [spesmilo/electrum#7201]
I don't know if this is a bug, but at least it doesn't do what I expected.
I created two transactions in  a legacy (Trezor) wallet, with coin control. The first only sends a single output to different addresses in the same wallet. The transaction is broadcast, but not yet confirmed. Using Electrum 4.1.2 Linux AppImage.
Then I create another transaction from a different output. Note that the output that I spent in the first transaction is not even visible any more in the "Coins" tab, so I couldn't have it selected as an input for the new transaction. But when I create the new transaction, it shows two inputs, name the intended one and also the one that was used first transaction. It also shows the outputs for the first transaction as outputs for the new transaction, but not the same change as the first transaction. The new transaction only has a single change output, and it uses the change address that was also used in the first transaction.
It seems that the creation of new transaction is somehow mangled up with the first one that is already broadcast (but not yet confirmed). I would have expected the second transaction to be completely independent of the first one. Hopefully, this description makes sense.

**Comment by schulzemic** [comment]
To add: The first transaction is confirmed now. If I create the second transaction again (without making any changes in the GUI), the transaction looks just as I would have expected it from the start. It also uses a new change address now.

**Comment by ecdsa** [comment]
This is probably because you have enabled RBF batching.
In your preferences, there is a checkbox called "batch RBF transactions". 
It is disabled by default, but I guess you must have enabled it.

**Comment by schulzemic** [comment]
Oh, indeed! I had no idea, thank you. I guess I can close this now.
