### ISSUE TITLE
Customizable minimum change threshold. (dust)

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7204]
I'm creating that new issue to bump that older one, https://github.com/spesmilo/electrum/issues/5359

Beside the 2017-2018 big block fee attack the cost for blockspace now seems to have permanently raised above what make sense for the fixed dust limit.

![image](https://user-images.githubusercontent.com/388716/114496856-d0a61880-9bee-11eb-88ce-b8c18f3a7d45.png)

At 10 sat/bytes (low for last 4 months) it now cost more than 1000 sats to spend a single UTXO while the hardcoded dust avoidance threshold is set to 546 sats.

Fees fluctuate constantly making it contentious to codify what should be considered at any point in time a spendable amount for an UTXO.

I recommend letting users edit a setting to select what BTC amount is considered dust by the coin selection algorithm.  Possibly with input validation between min 0.00000546 and 0.0001 (~5$) as to not to cause unintended over-spending.

**Comment by SomberNight** [comment]
Please do not create new issues to "bump" existing ones. Especially if the existing issue is not even closed.
You are more than welcome to move this comment  to the existing issue.
