### ISSUE TITLE
Unauthorized withdrawal of btc from e-wallet version 4.0.7

### ISSUE THREAD

**Issue by Trololosha17** [spesmilo/electrum#7206]
The wallet was created in 2017. I rarely used it, I only kept the keywords in my head from a secure computer, the password was complex, except for me no one could get to it. Yesterday 0.017 bitcoin was withdrawn to the bc1q65usegx7mqmqxzf6rkzlkwkny73vfxypn8pxyr wallet
how could a hack happen? The computer on which the wallet was located was turned off, the Anti-Virus was installed. What questions to answer so that others do not make mistakes, like me. All recommendations have been implemented.

**Comment by Trololosha17** [comment]
<a href="https://ibb.co/Mc9jg98"><img src="https://i.ibb.co/dP73f7b/1.jpg" alt="1" border="0"></a>

**Comment by Transisto** [comment]
There's so many things that could have happened that has nothing to the design of electrum

There is no link between the time your keys were extracted from either your back or your hot wallet and the time the transaction was broadcasted.

Use a hardware wallet or multi-signature, Antivirus are rarely useful at detecting new viruses.

**Comment by ecdsa** [comment]
too little information here. 
if you really want to know, you should have your computer examined by a security expert.
the fact that you mention anti-virus suggests that you are using windows, where there is all kind of malware.
