### ISSUE TITLE
Status of transaction being shown as 'signed' by default on the advanced preview tab while creating an outgoing transaction even before clicking on 'finalize'!

### ISSUE THREAD

**Issue by Milo007-github** [spesmilo/electrum#7207]
I have the latest version (v 4.1.2) of electrum installed on my computer. An oddity that I have noticed while trying to create an outgoing transaction and proceeding to the advanced preview tab (to set a custom fee rate) is that the status of the transaction is being shown as 'signed' by default even before I finalize the transaction. As far as I know the transaction should appear 'unsigned' at this stage and one is supposed to sign the transaction by typing in the wallet encryption password after finalizing the same before broadcasting it.

When I try to repeat the steps in the testnet everything goes as expected. The status is shown as 'unsigned' before I click on the finalize button. Then I am asked to sign it with the wallet encryption password so that I can broadcast it to the network.

Is this an intended change included in the latest update or is it a bug?

**Comment by SomberNight** [comment]
No it is not intended. I cannot reproduce however...

What kind of wallet do you have? In the Qt GUI, go to menubar>Wallet>Information; and please share the values of "wallet type", "script type", "keystore type".

**Comment by ecdsa** [comment]
screenshot please

**Comment by Milo007-github** [comment]
> No it is not intended. I cannot reproduce however...
> 
> What kind of wallet do you have? In the Qt GUI, go to menubar>Wallet>Information; and please share the values of "wallet type", "script type", "keystore type".

Wallet type : standard 
Script type : p2wpkh
Keystore type : bip32

![Wallet Information](https://user-images.githubusercontent.com/82448112/114662279-072a8300-9d16-11eb-80e0-040b54e9d091.png)

![Advanced Preview Tab](https://user-images.githubusercontent.com/82448112/114662870-0b0ad500-9d17-11eb-83ea-153d531b538f.png)

**Comment by Milo007-github** [comment]
> screenshot please

I have uploaded the screenshots in a comment above. You could see the transaction status as 'signed' in the advanced preview tab of the mainnet application. I am also attaching a screenshot of the testnet interface which is working fine.

![Advacned Preview Tab - Testnet](https://user-images.githubusercontent.com/82448112/114663822-86b95180-9d18-11eb-9a8f-8137976a0e12.png)

**Comment by ecdsa** [comment]
The GUI is showing "signed" because the transaction has no inputs. (therefore "all outputs are signed").
It would help to know how you created a transaction with no inputs in Electrum.

**Comment by SomberNight** [comment]
Next time please make redactions obvious, e.g. by using coloured rectangles.
Due to the nature of the bug, not being able to tell what is redacted and what was not even there in the first place is quite confusing.

@ecdsa 
I can sort of reproduce:
try to create a tx with a zero value output, and explicitly set either the fee or the feerate to 0.

It does not seem to fully explain OP's bug as they seem to have the empty string in `feerate_e` (and not "0").

**Comment by Milo007-github** [comment]
> The GUI is showing "signed" because the transaction has no inputs. (therefore "all outputs are signed").
> It would help to know how you created a transaction with no inputs in Electrum.

I removed the input address using a picture editing tool to hide the address. I thought it would be unsafe to post my public addresses in the internet. Should I create a new wallet and re-upload the screenshot unedited?

**Comment by Milo007-github** [comment]
> The GUI is showing "signed" because the transaction has no inputs. (therefore "all outputs are signed").
> It would help to know how you created a transaction with no inputs in Electrum.

I created a new standard wallet without any balance in it to get used to the interface of electrum before importing my seed phrase from another wallet. I am a new user of electrum. Is it showing 'signed' because I have 0 BTC in my wallet addresses and hence no inputs?

**Comment by SomberNight** [comment]
Thanks for the report! This will be fixed in the next version.

Note that the bug here was that Electrum was willing to create transactions with zero inputs. Signed/unsigned is meaningless in such case, as that is a property of the inputs. Any Bitcoin transaction must have at least 1 input; this is enforced by consensus rules. (i.e. these "transactions" we were creating were invalid)
