### ISSUE TITLE
Feature Request: View Master Public Key on Electrum Android

### ISSUE THREAD

**Issue by xmready** [spesmilo/electrum#7210]
I would like to request a way to view the master public key when using the Android version of Electrum. I cannot find any way to view or display it. 

It would also be helpful to display "Watch Only" somewhere if the wallet is a watch only wallet. Electrum tells you when first importing a master public key that it is watch only, but after that there is no indication while using it.

**Comment by ecdsa** [comment]
just tap on the wallet name...
