### ISSUE TITLE
the money did not reach the recipient 

### ISSUE THREAD

**Issue by Kostese** [spesmilo/electrum#7226]
The money did not reach the recipient and did not come back. payment stuck. The recipient support says that the instruction how to give it back is sent to my email. But when I opened an Electrum account I did not use any email for this...
How to give my money back?

**Comment by Transisto** [comment]
You most likely simply didn't pay enough fees, 

check out https://github.com/spesmilo/electrum/issues/7229#issuecomment-823701933
