### ISSUE TITLE
Withdrawal unconfirmed. I need help

### ISSUE THREAD

**Issue by BNC7** [spesmilo/electrum#7227]
Goodmorning,
Yesterday i made a withdrawal to my Binance Wallet of BTC, i made it like 12 hours ago and its has been in "Local State" since the first 20 minutes.
Can anyone help me?
I dont know if i made the withdrawal corretly but i dont think it is normal that i havent recieve it yet in my Binance Wallet,
I appreciate your help,
Borja
![image](https://user-images.githubusercontent.com/82874228/115373508-3e90a800-a1cc-11eb-95a4-6ff5714f2b70.png)

**Comment by Transisto** [comment]
Anything below 15 satoshi/bytes currently is considered as not even existing in the mempool, 
It will show the "Local" icon, which allows you to just delete it from the wallet and send those funds again.

I'm curious what made you decide on 2sat/bytes, the fees are currently around 200

**Comment by ecdsa** [comment]
A lot of users have no idea what fees are for. 
The software should explain it better.
