### ISSUE TITLE
Commission fee is higher than the transaction itself!!!

### ISSUE THREAD

**Issue by nveryche** [spesmilo/electrum#7230]
my last 3 transactions were all 100% of the transaction itself.
One time I’ve paid 0.00089 and the transaction fee was 0.000905!!!!
the sat/byte are relatively high: 201.9 sat/byte , 244.4 sat/byte , 267.8 sat/byte
what can I do about it???

**Comment by ecdsa** [comment]
The high fee situation depends on the network congestion.
there is not much you can do about it. 
you can wait until the fees go down (it might take several weeks).
you can also try to use lightning (ask the merchant if they accept lightning payment)

**Comment by nveryche** [comment]
Is there a way to know WHEN the network is busy?

**Comment by ecdsa** [comment]
If you use "mempool" in your fee settings, Electrum will show you the fee you need to pay in order to be at a certain position in the mempool. You can also see this information on various websites, such as https://jochen-hoenicke.de/queue/#BTC,24h,weight
