### ISSUE TITLE
High transaction size and fee

### ISSUE THREAD

**Issue by Youngzedd** [spesmilo/electrum#7235]
![image](https://user-images.githubusercontent.com/83068231/115857605-c8877d80-a425-11eb-958b-1ee53708dd5d.png)

Why is Electrum adding my wallet address in the output of the transaction thereby increasing the size of the transaction. Any solution to this?    

The output should be one (1) which is the recipient address.

Kindly take a look at the sample image.

**Comment by as-schug** [comment]
That is correct. It´s a change address. If you don´t have it, the diference between what you are sending and what you have, goes to miners as fees. Change address receive that diference. You should read more about how bitcoin works, or about BITCOIN UTXO and CHANGE ADDRESS

**Comment by Youngzedd** [comment]
> That is correct. It´s a change address. If you don´t have it, the diference between what you are sending and what you have, goes to miners as fees. Change address receives that diference, creating a new UTXO. You should read more about how bitcoin works, or about BITCOIN UTXO and CHANGE ADDRESS

I understand better now because when I send using max button, it doesn't add such output.

I also read about BITCOIN UTXO.

Thank you.
