### ISSUE TITLE
Unconfirmed since 3 days

### ISSUE THREAD

**Issue by Gwegoo78** [spesmilo/electrum#7241]
Hi

My payment is Unconfirmed since 3 days

What's the problem?
Can I cancel the trasaction?

Thanks for your help

**Comment by Transisto** [comment]
Please learn about the fee market.

1. You didn't pay enough fees.
2. Your transaction most likely confirmed by now. (unless you paid less than 14 sat/byte)

**Comment by Gwegoo78** [comment]
Hi

It s ok since yesterday
Thank you so mutch for your anser

Envoyé de mon iPhone

Le 25 avr. 2021 à 21:58, Transisto ***@***.***> a écrit :

﻿

Please learn about the fee market.

  1.  You didn't pay enough fees.
  2.  Your transaction most likely confirmed by now. (unless you paid less than 14 sat/byte)
