### ISSUE TITLE
Swap from LN to BTC doesn't work

### ISSUE THREAD

**Issue by alexander-koval** [spesmilo/electrum#7243]
I'm trying make a swap from LN channel to BTC wallet. But after some attemps its failed. 
Message "Giving up after 10 attemps"

[electrum_log_20210424T163303Z_197398.log](https://github.com/spesmilo/electrum/files/6371258/electrum_log_20210424T163303Z_197398.log)

**Comment by bitromortac** [comment]
This means that you couldn't find a route to the Electrum testnet swap server, either because you are connected to an illiquid routing node (you are not, because you're using Acinq's endurance) or that the Electrum testnet swap Lightning node doesn't have enough inbound liquidity.
