### ISSUE TITLE
all block header download

### ISSUE THREAD

**Issue by zsharifian** [spesmilo/electrum#7250]
In previous versions, the header of all blocks was downloaded, but in the current version, only the header of some blocks is downloaded. Is it possible to change the download of all block headers?

**Comment by SomberNight** [comment]
Why do you want to download all block headers?

This was changed ~3 years ago, in version 3.1.0.
See
https://github.com/spesmilo/electrum/blob/1dfa81e7b6faf2e33dac253a5520a8db0d4c4a9b/RELEASE-NOTES#L633-L636

**Comment by zsharifian** [comment]
I actually need the all hash of blocks of 2020 (Sorted by height) to do my PhD thesis, and activating a full node to access this information is very difficult for me.

**Comment by zsharifian** [comment]
Of course, I also installed a number of versions less than 3, but for various reasons I could not get the information I needed. I would be very happy if you could help me with this.

**Comment by zsharifian** [comment]
Thank you very much
