### ISSUE TITLE
Please help with a problem regarding cosigning multisig transactions

### ISSUE THREAD

**Issue by Sixteenzips** [spesmilo/electrum#7252]
I have two online Electrum wallets that I set up to be able to cosign multisig transactions for one another.

On the first wallet (which is a standard 2of2 multisig wallet), I create the transaction, and then export the transaction to my clipboard as seen in the following pictures:

![#1](https://user-images.githubusercontent.com/52508819/116225511-cadc2700-a706-11eb-8c11-9fe3105809cc.png)

![#2](https://user-images.githubusercontent.com/52508819/116225602-e5160500-a706-11eb-8e4a-fc55174b6779.png)

Then, in my 2FA Trusted Coin enabled wallet, I go to Tools > Load transaction > from Text, and then copy and paste the transaction code into the box and hit "Load transaction"

In the box that pops up, the "Sign" button is greyed out and I am unable to sign the transaction as seen in the following picture:

![#3](https://user-images.githubusercontent.com/52508819/116226046-6372a700-a707-11eb-9934-a7de00947d3f.png)

I noticed it says "Transaction unrelated to your wallet" on the final window where I am unable to sign the transaction, I'm not sure if this has anything to do with the problem but I thought I'd point that out. I don't know why this would be the case because I am confident I set up the wallets to be able to cosign for one another correctly, as I provided each wallet with the others public master key when I created them.

I have tried this on Windows 10 and Tails OS and the problem is the same on both.

Please help me resolve this issue

**Comment by SomberNight** [comment]
What exactly are you trying to do? Why do you have two wallet files for a 2FA wallet?
The typical way to use a 2FA wallet is to have a single wallet file on an online machine and essentially use it as a hot wallet. The extra security comes from multisig (the other signer being a remote server), not from offline signing.

**Comment by Sixteenzips** [comment]
@SomberNight I am trying to get the second signature required to be able to withdraw funds from my 2of2 multisig wallet that you see in the first picture.

**Comment by SomberNight** [comment]
Are you just trying to use the 2fa wallet as usual or is this some kind of disaster-recovery where you have lost your second factor?
I still don't understand what you are doing, please give more complex, in either scenario there is an easier way.

Regardless, read https://api.trustedcoin.com/#/faq
2fa wallets use 2of3 multisig, not 2of2.

**Comment by Sixteenzips** [comment]
@SomberNight When I created the multisig wallet that I am trying to withdraw from, it asked me to enter the Master Public Key of my co-signer. I entered in the Master Public Key of the 2FA wallet. I am now trying to withdraw my funds from the multisig wallet, but don’t know how. Is it even possible or are my funds stuck in the multisig wallet forever?

**Comment by SomberNight** [comment]
> I entered in the Master Public Key of the 2FA wallet.

Note that a 2FA wallet has three master public keys, all of which are needed to watch it.

> I am now trying to withdraw my funds from the multisig wallet, but don’t know how. Is it even possible or are my funds stuck in the multisig wallet forever?

@Sixteenzips please detail exactly how you have created the 2of2 multisig wallet.

**Comment by Sixteenzips** [comment]
@SomberNight 

It asked "What kind of wallet do you want to create?" and I selected "Multi-signature wallet".

Then it said "Choose the number of signatures needed to unlock funds in your wallet" and I selected "From 2 cosigners" and "Require 2 signatures"

Then it said "Do you want to create a new seed, or to restore a wallet using an existing seed?" and I selected "Create new seed"

It then gave me my Master Public Key which I saved somewhere

Then it said "Add a cosigner to your multi-sig wallet" and I selected "Enter a cosigner key"

Then it said "Please enter the master public key (xpub) of your cosigner. Enter their master private key (xprv) if you want to be able to sign for them"

So I entered in the Master Public Key of my 2FA wallet that I got from Wallet > Information > Master Public Key inside my 2FA TrustedCoin wallet.

It then said "Choose a password to encrypt your wallet keys. Leave this field empty if you want to disable encryption" so I decided to use a password.

That is how I created my multisig 2of2 wallet.

**Comment by SomberNight** [comment]
> So I entered in the Master Public Key of my 2FA wallet that I got from Wallet > Information > Master Public Key inside my 2FA TrustedCoin wallet.

Again, there are three master public keys in every 2fa wallet. Please confirm this by checking now in your 2fa wallet.
Which one of the three did you use?

**Comment by Sixteenzips** [comment]
@SomberNight Yes, I see now that there are 3. "Keystore 1", "Keystore 2", and "Keystore 3". I'm assuming I used Keystore 1 since that's the one that is displayed when you first click on the Wallet Information tab.

**Comment by SomberNight** [comment]
> I'm assuming I used Keystore 1 since that's the one that is displayed when you first click on the Wallet Information tab.

Ok, in that case your coins are recoverable. Keystore1 is the hot user key, keystore2 is the cold user key, and keystore3 is a key held by Trustedcoin.

You can get the master private key for keystore1 by going to the `Console` tab (after un-hiding it via menubar>`View`>`Show Console`), and running:
```
getmasterprivate()
```

> Then it said "Choose the number of signatures needed to unlock funds in your wallet" and I selected "From 2 cosigners" and "Require 2 signatures"
> Then it said "Do you want to create a new seed, or to restore a wallet using an existing seed?" and I selected "Create new seed"

With the xprv returned by `getmasterprivate()`, and with the seed you have created at this step, you can spend your coins that are locked in the 2of2 multisig.
For example, you can create a new wallet file, set it to 2of2 multisig, and provide seed words as cosigner1, and the xprv as cosigner2. Then this new wallet file will have both secrets (so the multisig aspect will not provide extra security) and be able to spend directly. More complex setups are possible too but I suggest you make sure you can move your coins.

I would also like to suggest never to do custom stuff like this you don't understand.

In the interest of making the software better for others, could you please explain what gave you the idea to do this?

**Comment by Sixteenzips** [comment]
Firstly, I'd like to say I greatly appreciate your help @SomberNight . I was able to withdraw my funds. I was concerned they might be lost forever. <3

Secondly, I've set up lots of custom things in the past without anyone's help and I enjoy doing it especially when I figure it out, but I learned an important lesson this time and that is to not attempt to set anything new up with large amount of funds or any amount of funds I'm not willing to potentially lose.

However, I thought it was intuitive that you would be able to do a setup like this, and rather counterintuitive that Electrum allows you to set it up without any warnings or information.

I wanted to set it up like this because I thought having my separate cosigner wallet be a 2FA wallet would add a great deal more security to my setup.

I'm still confused about whether this is possible though. Is it?

If so, how do you do it?

**Comment by SomberNight** [comment]
Electrum lets you create generic k of n multisig wallets where there are n cosigners and any k of them can sign to be able to spend from the wallet. This simply uses an OP_CHECKMULTISIG opcode in bitcoin Script which itself lets you specify `k`, and n pieces of public keys.

With convience but still more security than a singlesig in mind, Electrum also lets you create "2FA" wallets, which are simply 2 of 3 multisig wallets, where the user has two keys (both derived from the seed words, but only one stored in the wallet file) and a remote central server operated by Trustedcoin has the third key. During wallet creation, a QR code is shown to the user, which Trustedcoin will also have, this QR code encodes a shared secret between the user and Trustedcoin.
Trustedcoin will sign your tx in automated way if you can prove you have the QR code: the user needs to provide a TOTP (time based one time passwords) every time it wants Trustedcoin to sign.
Just like the generic multisig wallet, this too uses an OP_CHECKMULTISIG opcode in bitcoin Script, specifically with `k=2` and `n=3`.

The two constructions cannot be embedded into each other.
