### ISSUE TITLE
feature: Lightning payment requests via BIP21/lightning prefix

### ISSUE THREAD

**Issue by bitromortac** [spesmilo/electrum#7253]
We could support paying to lightning invoices via BIP21 URIs using the `&lightning=` key or by using the `lightning:` prefix, see
https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#encoding-overview

**Comment by SomberNight** [comment]
I think we already support the `lightning:` prefix for bolt11 invoices. If it does not work then that's a bug.
https://github.com/spesmilo/electrum/blob/1dfa81e7b6faf2e33dac253a5520a8db0d4c4a9b/electrum/util.py#L985-L992

> support paying to lightning invoices via BIP21 URIs using the `&lightning=` key 

What exactly does the BOLT suggest there?
Is it about a practically empty bip21 URI that only has this single key, as in
`bitcoin:?lightning=lnbc1asdasd`
? (as in no bitcoin address given - AFAIR this is a valid bip21 URI)

If it allows mixing a bitcoin address and a lightning invoice, and the bip21 URI contains both, how should that be handled?

**Comment by bitromortac** [comment]
> I think we already support the `lightning:` prefix for bolt11 invoices. If it does not work then that's a bug.

I tested `./run_electrum bitcoin:bip21url`, which works and `./run_electrum lightning:lninvoice` which errors with `unknown_command`.

> https://github.com/spesmilo/electrum/blob/1dfa81e7b6faf2e33dac253a5520a8db0d4c4a9b/electrum/util.py#L985-L992
> 
> > support paying to lightning invoices via BIP21 URIs using the `&lightning=` key
> 
> What exactly does the BOLT suggest there?
> Is it about a practically empty bip21 URI that only has this single key, as in
> `bitcoin:?lightning=lnbc1asdasd`
> ? (as in no bitcoin address given - AFAIR this is a valid bip21 URI)
> 
> If it allows mixing a bitcoin address and a lightning invoice, and the bip21 URI contains both, how should that be handled?
> 
> Also, do you know of any project/service that creates bip21 URIs with a lightning key?

Exactly, we could give precedence for Lighting invoices as done here: https://github.com/LN-Zap/zap-desktop/pull/3131

**Comment by SomberNight** [comment]
> I tested `./run_electrum bitcoin:bip21url`, which works and `./run_electrum lightning:lninvoice` which errors with `unknown_command`.

Ah, right, for that we need to change:
https://github.com/spesmilo/electrum/blob/2b0561599595ade8cebbc699f2946b4830ef671f/run_electrum#L346-L351
https://github.com/spesmilo/electrum/blob/2b0561599595ade8cebbc699f2946b4830ef671f/electrum/gui/qt/__init__.py#L414

> Exactly, we could give precedence for Lightning invoices as done here: https://github.com/LN-Zap/zap-desktop/pull/3131

Ok, so you mean if there is a lightning key in the bip21 URI, ignore the onchain address completely.
(well except, if the user does not have any channels, maybe we could do the opposite and ignore the lightning key)

**Comment by bitkarrot** [comment]
hi! Not sure if this issues is still open. 

Is there interest in getting Electrum to generate its own BIP21 QR code? 

an effort being led here: https://bitcoinqr.dev/

**Comment by SomberNight** [comment]
> an effort being led here: https://bitcoinqr.dev/
> ```
> bitcoin:bc1qylh3u67j673h6y6alv70m0pl2yz53tzhvxgg7u?amount=0.00001
> &label=sbddesign%3A%20For%20lunch%20Tuesday
> &message=For%20lunch%20Tuesday
> &lightning=lnbc10u1p3pj257pp5yztkwjcz5ftl5laxkav23zmzekaw37zk6kmv80pk4xaev5qhtz7qdpdwd3xger9wd5kwm36yprx7u3qd36kucmgyp282etnv3shjcqzpgxqyz5vqsp5usyc4lk9chsfp53kvcnvq456ganh60d89reykdngsmtj6yw3nhvq9qyyssqjcewm5cjwz4a6rfjx77c490yced6pemk0upkxhy89cmm7sct66k8gneanwykzgdrwrfje69h9u5u0w57rrcsysas7gadwmzxc8c6t0spjazup6
> ```

I see, so the idea is to put a `lightning` key into a bip21 uri.


> Not sure if this issues is still open.

The part about handling the `lightning:` prefix is implemented, including the part which was missing when the issue was opened (registering MIME types in the OS),
the part about recognising the `&lightning=` key in bip21 URIs is not done.

@ecdsa this is another approach to consider re your "invoice-unification" idea

**Comment by bitkarrot** [comment]
@SomberNight, can I be assigned to the part that is not done? 

Looking to get started as a new contributor and this looked interesting.

**Comment by SomberNight** [comment]
Feel free to have a look.

There are many ways to do it, with different implications and complexities.
I think the easiest, is to call `parse_URI` inside `maybe_extract_bolt11_invoice`.
https://github.com/spesmilo/electrum/blob/3e42f2f33d56308455a5c75a460f2262c7a576bd/electrum/util.py#L1053
https://github.com/spesmilo/electrum/blob/3e42f2f33d56308455a5c75a460f2262c7a576bd/electrum/util.py#L938
This has the implication that if the `lightning` key is set inside a bip21 URI, then we always use it, and in that case we disregard all the other fields in the bip21 URI.

**Comment by accumulator** [comment]
In a BOLT11 invoice there can be a fallback onchain address too (currently not implemented in electrum AFAICS). 
We should definitely support this as well, but this leads to a potential 'conflict' when the lightning invoice as part of the bip21 uri contains a fallback and it differs from onchain address in the bip21 uri.

**Comment by ecdsa** [comment]
Note: BOLT11 fallback addresses are currently being implemented in the branch named `seamless_lightning`

**Comment by SomberNight** [comment]
I think this was done in the payment_identifiers refactor (https://github.com/spesmilo/electrum/pull/8462) or maybe even earlier.
