### ISSUE TITLE
auto import, add coolwallet S weird derivation path

### ISSUE THREAD

**Issue by jpph** [spesmilo/electrum#7259]
Would be nice to auto detect also coolwallet S derivation path.
In file bip39_wallet_formats.json :
{        "description": "coolwallet S derivation path using bip44 but with  segwit script format",
        "derivation_path": "m/44'/0'/0'",
        "script_type": "p2wpkh-p2sh",
        "iterate_accounts": true
}
see https://help.coolwallet.io/article/160-recover-btc-using-coolwallet-s-seed-without-the-wallet for their recovery instruction

**Comment by SomberNight** [comment]
please create a pull request.

**Comment by jpph** [comment]
pr 7230 done
