### ISSUE TITLE
Cancel (double-spend)

### ISSUE THREAD

**Issue by gregorycoles** [spesmilo/electrum#7268]
Hello.

I recently saw the Cancel feature (Double-Spend) in one of the latest versions of the Electrum.

1. You can find out for what transactions this function appears and can it be used?

2. Will I be able to use the function if I transferred the full amount from the Bitcoin-address and the transaction unconfirmed? Those. At the exit of unconfirmed transaction, must remain any balance or not?

3. And in general, you can find out the details - that it represents. In Google did not find :-( You have in FAQ too.

Thank you.

**Comment by Transisto** [comment]
Only unconfirmed RBF transaction can be "canceled".

Not sure I understand your questions.

**Comment by gregorycoles** [comment]
Those. If I sent a transaction with RBF - I can increase the commission on the fly and push it - I understand it.

But I can also cancel the transaction, redirecting to another bitcone address - correctly I understand or not?

Thank you for your time.

Sincerely yours, Gregory Coles

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Transisto** [comment]
Yes, RBF flag override the miners first seen policy.

The transaction with the most fee will be "mined".

**Comment by SomberNight** [comment]
Any RBF-enabled unconfirmed transaction that spends coins from your wallet and has at least one external output (not owned by the wallet) can be cancelled by paying a higher fee.
Yes, even if the tx is spending all the coins in the wallet, it can be cancelled, as the fee can still be increased by decreasing the output value.
If cancelling a tx, the newly created replacement tx will pay "back" to your wallet, regardless of what the original destination was.
