### ISSUE TITLE
Electrum issues need help please

### ISSUE THREAD

**Issue by romiaka** [spesmilo/electrum#7269]
Hi , electrum would not load from desktop. countinually had 'fatal error' 
After this Icon disappeared from destop.
Tried to update wallet, would not download constant message ' cant write'
How can i retrieve wallet?

**Comment by SomberNight** [comment]
Hi.
- What operating system do you use?
- Where did you download Electrum from? Please paste link/URL.
- > electrum would not load from desktop. countinually had 'fatal error'

   Could you please upload a screenshot with this error visible?
- > Tried to update wallet, would not download constant message ' cant write'

   How did you try to update?
   Could you please upload a screenshot with this error visible?
