### ISSUE TITLE
Old transaction labels get injected seemingly at random in batch transaction labels.

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7271]
Related to https://github.com/spesmilo/electrum/issues/7272

**Comment by Transisto** [comment]
Found the problem, Everytime BTC are sent to a previously used address it shows the label of the previous transaction as part of that label.

These were filled as description of transaction not address labels, So I don't think they should be shown.

**Comment by SomberNight** [comment]
Not sure I understand. Are the transactions "incoming" or "outgoing"?
Maybe it would be best if you could give specific example steps to reproduce.

**Comment by Transisto** [comment]
When reusing address the label of the other transaction show up.

Doesn't seems like a big or common issue. Closing

**Comment by ecdsa** [comment]
@Transisto if a tx has no label, it falls back to the address label if there is any.
See `_get_default_label_for_txid`
