### ISSUE TITLE
Menubar missing on Xfce4

### ISSUE THREAD

**Issue by azazar** [spesmilo/electrum#7274]
Menubar is not available right after it started.

![image](https://user-images.githubusercontent.com/2816075/116920530-30329980-ac6c-11eb-92fd-798553d111dd.png)

I'm using Xfce4 on Ubuntu 20.04.2 LTS.

**Comment by SomberNight** [comment]
Some window system put the menubar outside the window, to the top of the screen. Is it not there?

**Comment by azazar** [comment]
No. Xfce4 doesn't do anything like that.

**Comment by azazar** [comment]
There's a [similar issue with LibreOffice](https://superuser.com/questions/1408837/menu-bar-missing-from-libreoffice-apps-after-uninstalling-xfce4-appmenu-plugin-a). Can it have the same cause?

**Comment by azazar** [comment]
There was a problem with various *appmenu packages, which I've reinstalled and the problem is gone.
