### ISSUE TITLE
UNPAID STATUT

### ISSUE THREAD

**Issue by xavxav007** [spesmilo/electrum#7277]
Hi, 
I send my key wallet yesterday to get pay from someone.

I din't received incoming notification and the transaction on my side is on unpaid.
On his side it shows unconfirmed.

Technically I was supposed to receive a notifcation and see transaction incoming in my history.
Due to the amount I am very stressed and you like to sort this out.

Please help me.

**Comment by Transisto** [comment]
If the fee paid was extremely low the transaction might not show up in the mempool of the server you're using.

Do you know what fee was paid in sat/bytes?

You should have nothing extra to worry about unless you consider unfirmed fund to be worth more than 0.

**Comment by xavxav007** [comment]
I don't know the fees transisto, 
It apparently been rejected with an error 22.
It quite a serious amount of money and I am starting to freak out

**Comment by Transisto** [comment]
Tell the other side to send it again, It clearly didn't never worked. 

Doesn't seems like the transaction ever made it out to the network,

**Comment by xavxav007** [comment]
Hi Guys, 
The guy is a scammer, 
When I ask for what you ask for He just fanished.
Just get scammed for 0.89BTC.
Now I have to find a way to get to him and expose him to make sure that it will not happen to anybody.

**Comment by rkfg** [comment]
Damn, that's very sad to hear. I wish you best of luck finding and exposing this criminal! Hope there are laws in your country regarding cryptocurrencies so you can involve the police.

**Comment by xavxav007** [comment]
Thanks Rkfg, 
As I speak, I am sure that he is reading my post since the first time I posted he sended to me a screenshoot of it, saying that we were looking at the same think. Me to find a slotuion and apparantly  him to make up excuses.
I'll get him, even if it takes years...Police already aware.
