### ISSUE TITLE
Wallet creation error

### ISSUE THREAD

**Issue by Filin-cyber** [spesmilo/electrum#7278]
When restoring a standard wallet by phrase - writes this message - Unable to create a window for the wallet:
PermissionError (13, 'Permission denied')

**Comment by SomberNight** [comment]
Could you share [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?

What operating system is this on?

Most likely, the Electrum process does not have permissions to create a file at the location you have specified.

**Comment by Filin-cyber** [comment]
Windows 10, но исполняет файл 4.0.2 portable, новую версию 4.1.2 не выполняет так же.

**Comment by Filin-cyber** [comment]
указанное место это диск С
