### ISSUE TITLE
перевод завис, что делать ?помогите!!!

### ISSUE THREAD

**Issue by dimitrii7575** [spesmilo/electrum#7280]
вот что выдаёт консоль

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "electrum\gui\qt\console.py", line 262, in exec_command
  File "<string>", line 1
    File "electrum\gui\qt\console.py"
         ^
SyntaxError: invalid syntax

bitcoin:bc1qx2aa0gmnky8wwhlulmewju98snh9vhu567g3kw?time=1620147879&exp=3600

**Comment by SomberNight** [comment]
I think the traceback is from the user trying to paste the BIP21 URI into the Console tab...

**Comment by dimitrii7575** [comment]
04.06.2021, 14:11, "ghost43" ***@***.***>:
I think the traceback is from the user trying to paste the BIP21 URI into the Console tab...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Please tell me what is the way out, what needs to be done? Please help me out!😃Отправлено из быстрой Яндекс.Почтыhttp://mail.yandex.ru/neo2/collect/?exp=1&t=5

**Comment by SomberNight** [comment]
What is the problem you are having?
You haven't explained what your issue is clearly; so it is not possible to help.
