### ISSUE TITLE
no action;

### ISSUE THREAD

**Issue by tetrashop** [spesmilo/electrum#7283]
![New Bitmap Ima](https://user-images.githubusercontent.com/53708652/117345025-5306bd00-aebb-11eb-9481-b337e54dd8c1.jpg)
a saw it at least for 2 weeks;
get a reason set my coverage;

**Comment by Transisto** [comment]
tried changing server?

**Comment by tetrashop** [comment]
ye;

**Comment by SomberNight** [comment]
What is the problem being reported? Is it the "no FX rate available" or that the txs have a "0.0000 mBTC" amount?
If the latter, could you show the details of one of the txs (e.g. screenshot of tx dialog)?

**Comment by tetrashop** [comment]
no history; not address used; or paid; i am engaged where is my bitcon; where my receiving dose not work; must  i'
am waiting at most four weeks; should be certainly balance zero auto;

**Comment by Transisto** [comment]
right click one of the a transaction to show the information then share it
here.

**Comment by tetrashop** [comment]
![New Bitmap Im](https://user-images.githubusercontent.com/53708652/117428927-c3edb980-af3b-11eb-89dd-9b217f6d02bb.jpg)

**Comment by tetrashop** [comment]
i am not sure but i guessed;

**Comment by Transisto** [comment]
?

There's nothing to understand of this issue.
