### ISSUE TITLE
Android App crashed on execution

### ISSUE THREAD

**Issue by ArbenKarb** [spesmilo/electrum#7285]
Electrum V. 4.1.2.0

Android version 10

Suddenly stopped working

- forced stopped
- restarted phone
- fiddled with permissions

Nothing worked

**Comment by SomberNight** [comment]
So what happens when you launch the application now?
Is it crashing on startup?

Could you try to extract logs via `adb`? e.g. `adb logcat | grep python`
(Which OS do you use on your PC?)

**Comment by bottemann** [comment]
I previously used Electrum Android on a Pixel 3A with Ledger Nano S and KeepKey hardware wallets. Now when entering my Nano S pin, the Electrum app screen disappears and a message says" Electrum keeps stopping".  If I first enter the Nano pin, the start Electrum, I get a very brief Electrum splash that vanishes and then see the same "keeps stopping" message.  
Keepkey hardware wallet still works OK.
I'd be happy to provide debug log, but don't know how.

**Comment by SomberNight** [comment]
> I previously used Electrum Android on a Pixel 3A with Ledger Nano S and KeepKey hardware wallets. Now when entering my Nano S pin, the 4.1.2 Electrum app screen disappears and a message says" Electrum keeps stopping". If I first enter the Nano pin, then start Electrum, I get a very brief Electrum splash that vanishes and then see the same "keeps stopping" message.

Electrum for Android has never supported hardware wallets. (see https://github.com/spesmilo/electrum/issues/6320)

The crash itself is probably same as https://github.com/spesmilo/electrum/issues/6907 and https://github.com/spesmilo/electrum/issues/6907

**Comment by ArbenKarb** [comment]
Apologies for the late reply, it suddenly worked again
