### ISSUE TITLE
LNURL support

### ISSUE THREAD

**Issue by rkfg** [spesmilo/electrum#7287]
Currently, Electrum only supports Lightning invoices but not LNURL which makes payments easier and there's less data to show or transfer to the payer. Maybe I'm not doing it correctly but when I copy the LNURL to Electrum and fill other fields I get this message:
![2021-05-08_15-41-43](https://user-images.githubusercontent.com/184066/117539553-e6530600-b013-11eb-83bf-6413d8a55aff.png)

Would be nice to support it, ~~especially since it's not even that hard. It's just a BECH32-encoded URL that the client should query using GET method and receive a JSON-encoded invoice.~~ It's actually [a pretty convoluted spec](https://github.com/fiatjaf/lnurl-rfc) with multiple purposes. But the UX would be tremendously better!

**Comment by bitromortac** [comment]
Some wallets/services that are implementing LNURL: https://github.com/fiatjaf/awesome-lnurl

**Comment by samthelion** [comment]
So... Is this being worked on? I sometimes need to use a telegram bot as an intermediary. Would be great to have LNURL support in Electrum.

**Comment by rkfg** [comment]
LNURL is gaining a lot of traction and is well supported in most mobile wallets. Electrum is one of the few desktop wallets that support LN (Zap is the only other I know but it uses an external node instead of a built-in implementation).

Not all LUDs are urgently needed but Pay and Withdraw are the two used most often. A more recent addition is [Lightning Address](https://lightningaddress.com/) which is an email-like address that resolves into an LNURL Pay link. The flow is really good. I'd say LNURL is the third layer that provides application services on top of Lightning invoices and cryptography, it integrates Lightning and Web and as such is crucial for LN success in general.

**Comment by ecdsa** [comment]
to which extent is LNURL going to be deprecated by offers? 
https://github.com/lightningnetwork/lightning-rfc/pull/798/files

**Comment by rkfg** [comment]
I'm not an expert so don't take my word on it. I think offers are quite convoluted and need to be supported by the lightning node implementations to be useful (or working at all). They sure are nice to have but they're still WIP while LNURL works already and requires no changes in the underlying infrastructure. It's just URLs pointing to JSON. Since LNURL is already widely spread we need to support it even when offers are finished and implemented in all major lightning daemons. Some features like LNURL Auth, LNURL Channel request and Lightning Address are outside of the offers scope completely and they're all valid use cases.

**Comment by samthelion** [comment]
So, LNURL is going to be deprecated, or not? I wonder how hard could it be to add this feature to our trusted wallet, i mean, i can't code, but i can certainly test! There's a LNURL playground [here](https://lnurl.fiatjaf.com/)

**Comment by rkfg** [comment]
I don't see why LNURL would be deprecated. It covers a lot of use cases that can't be solved by offers. Offers at most would deprecate LNURL Pay but all the other branches should stay.

**Comment by bitromortac** [comment]
I opened a PR (#7573) for lnurl-pay and lightning address, if somebody wants to have an early look.

**Comment by SomberNight** [comment]
lnurl-pay support was merged in https://github.com/spesmilo/electrum/pull/7839 (based on https://github.com/spesmilo/electrum/pull/7573).
If someone wants to argue for other subtypes of lnurl, we can track that in a separate issue.
