### ISSUE TITLE
Lightning protocol handling

### ISSUE THREAD

**Issue by rkfg** [spesmilo/electrum#7288]
Electrum doesn't seem to support `lightning:` protocol which makes it not possible to prefill forms from the browser by clicking URLs. It supports `bitcoin:` though. A simple test case:
- create and copy a Bitcoin receive request
- run `electrum 'bitcoin:bc1qe<...>?message=Donation&time=1620376567'` (removed the address)
- Electrum opens the Send tab and fills the fields
- same happens if it's integrated in your system; on Linux it's usually XDG, can be checked with `xdg-open 'bitcoin:bc1qe<...>?message=Donation&time=1620376567'`; if it's not then it can be added manually in `~/.local/share/applications/mimeapps.list` as `x-scheme-handler/bitcoin=electrum.desktop` (make sure `electrum.desktop` file exists in `~/.local/share/applications`)
- but it doesn't work for Lightning at all, running `electrum lightning:lnbc10u1psfdp...` results in `unknown command: lightning:lnbc10u1psfdp...`

So paying Lightning invoices and, if/when #7287 is fixed, LNURLs is currently inconvenient from browser.

**Comment by bitromortac** [comment]
We recently discussed this in #7253.

**Comment by rkfg** [comment]
Yeah, I think it's what I meant. I searched for `lnurl` and `lightning url` but didn't try `lightning uri` which is the correct term.
