### ISSUE TITLE
The electrumsys wallet is not connecting to the network.

### ISSUE THREAD

**Issue by jjdewit** [spesmilo/electrum#7295]
Hello,

The electrumsys wallet from electrum.syscoin.org is not connecting to the network. I have the (portable) electrum wallet for Syscoin version 1.0.0. I opened port 58882 in my router, tried to connect using Tor and even tried different computers.

The version of the wallet on the website Electrum Syscoin Wallet van also not connect.

So far no luck. Do you have an idea of solving this? I don’t know what step I am missing. It used to work, I sent SYS to it a few months ago.

Is it possible that you update the wallet please? I use it with a Trezor hardware key and there is no solution to send them to another wallet. Nor can I export the seed from the Trezor to import to a QT wallet.

Awaiting your response.

**Comment by mrbury** [comment]
Any update on this?  I'm on version 3.3.8 and it does not appear I'm connected to the server.  There is no FX rate available for conversions and I can not check for updated versions.  Will I be able to receive funds if requested?  Will they still go through?

**Comment by mrbury** [comment]
now working for me..

**Comment by jjdewit** [comment]
How did you fix it? And was it the electrum wallet from here https://electrum.syscoin.org/#download or not?

**Comment by mrbury** [comment]
It just came back, was connected and the fx was updating again.  It had been out for a couple days.  Yes, that’s where I downloaded the wallet.


On May 15, 2021, at 2:09 PM, jjdewit ***@***.******@***.***>> wrote:



How did you fix it? And was it the electrum wallet from here https://electrum.syscoin.org/#download or not?

**Comment by verretor** [comment]
Please, stop.

**Comment by SomberNight** [comment]
Do not post issues about non-bitcoin versions of Electrum.
