### ISSUE TITLE
Asking for wallet password when none was created 

### ISSUE THREAD

**Issue by viperperidot** [spesmilo/electrum#7309]
I have a few watch only wallets on Electrum Android version and when I created them was not prompted to create a password. I have been able to open them with no password up until today when the application started asking me for a password. When I leave the field blank that does not work so I cannot open these wallets anymore.

**Comment by SomberNight** [comment]
@viperperidot Could you confirm that worked?

**Comment by viperperidot** [comment]
Sorry, yes it worked.
