### ISSUE TITLE
[Danger!] Transaction already sent but if not yet confirmed they get included to be sent again as part of next batch. 

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7315]

**Comment by Transisto** [comment]
This is extremely dangerous.
![image](https://user-images.githubusercontent.com/388716/119239290-20450180-bb16-11eb-9a96-915964633b61.png)

**Comment by Transisto** [comment]
Might be loosely related to https://github.com/spesmilo/electrum/issues/7272

**Comment by Transisto** [comment]
Cannot reproduce, It's only happening on a wallet with ~4000 addresses.

**Comment by SomberNight** [comment]
Is this related to menubar>"Tools">"Preferences">"Transactions">"Batch RBF transactions"?
