### ISSUE TITLE
Uncomfirmed

### ISSUE THREAD

**Issue by cyberfarfar** [spesmilo/electrum#7320]
My transaction (ID 1f7a678265fcbf55df79ad7785a449340baa9e4f3702301cc1f63d205ae7e60a) never gets confirmed. I didnt know what i was doing and put a low fee and now when im trying to bump it wont work i just get this message "The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

insufficient fee
Your transaction is trying to replace another one in the mempool but it does not meet the rules to do so. Try to increase the fee."

**Comment by SomberNight** [comment]
That error message means you are not increasing the fee by a high enough margin.
Bitcoin nodes enforce BIP125 as policy, and that mandates certain rules re at least how much the fee must be increased to allow replacing the old tx.
