### ISSUE TITLE
Android: NoDynamicFeeEstimates()  ( Electrum v4.1.2)

### ISSUE THREAD

**Issue by odomdev** [spesmilo/electrum#7326]
On Android click send then fill receeving  address, amount => click pay => showed NoDynamicFeeEstimates()  How to fix that issue ?

**Comment by SomberNight** [comment]
This can happen if there is no network connectivity, or if the connected server did not yet send dynamic estimates.
As user, to work around it, you can simply set a static fee.

You can change the fee estimation method to use static fees by tapping the "target".
The UI is a bit confusing though. It should be made more obvious what is and what is not a button.

![Capture](https://user-images.githubusercontent.com/29142493/121020764-35659580-c790-11eb-8da3-4158e934431f.PNG)

**Comment by dnsdev9** [comment]
How to set static fee ?
