### ISSUE TITLE
LN channel can't connect to node and Invoice is stuck

### ISSUE THREAD

**Issue by alexander-koval** [spesmilo/electrum#7328]
Hello! I've got an error with ln invoice. I try to receive invoice but it stuck and node status always change status OPEN->DISCONNECT->OPEN->DISCONNECT. In logs I see that an error occured

```
389726a2abad61588dfef07557e9dabc, cltv_expiry=685915, timestamp=1622536893, htlc_id=2)
20210601T084133.833147Z |    ERROR | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | Exception in main_loop: RemoteMisbehaving(PaymentFailure('HTLC value over protocol maximum: 4749517000 > 4294967295 msat'))
Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnchannel.py", line 898, in receive_htlc
    self._assert_can_add_htlc(htlc_proposer=REMOTE, amount_msat=htlc.amount_msat)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnchannel.py", line 819, in _assert_can_add_htlc
    raise PaymentFailure(f"HTLC value over protocol maximum: {amount_msat} > {LN_MAX_HTLC_VALUE_MSAT} msat")
electrum.lnutil.PaymentFailure: HTLC value over protocol maximum: 4749517000 > 4294967295 msat

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/util.py", line 1091, in wrapper
    return await func(*args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 317, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 335, in main_loop
    await group.spawn(self.process_gossip())
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 481, in _message_loop
    self.process_message(msg)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 216, in process_message
    execution_result = f(*args)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnpeer.py", line 1367, in on_update_add_htlc
    chan.receive_htlc(htlc, onion_packet)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnchannel.py", line 900, in receive_htlc
    raise RemoteMisbehaving(e) from e
electrum.lnutil.RemoteMisbehaving: HTLC value over protocol maximum: 4749517000 > 4294967295 msat
```

[electrum_log_20210601T085458Z_585155.log](https://github.com/spesmilo/electrum/files/6575088/electrum_log_20210601T085458Z_585155.log)

**Comment by alexander-koval** [comment]
[electrum_log_20210601T084117Z_582543.log](https://github.com/spesmilo/electrum/files/6574895/electrum_log_20210601T084117Z_582543.log)

**Comment by alexander-koval** [comment]
Hello! For now, my ln invoice is expired. I didn't get any money and payer didn't return anything. Exception is happening constantly. Channel status changes constantly OPEN->DISCONNECT->OPEN->DISCONNECT. 
What should I do?

**Comment by alexander-koval** [comment]
Related issue is (https://github.com/spesmilo/electrum/issues/7100). So why electrum wallet can create LN invoice more than 42mBTC and after that can't receive it? And why Phoenix wallet can create and receive payment more than 42mBTC, but electrum wallet not?

**Comment by SomberNight** [comment]
As explained in https://github.com/spesmilo/electrum/issues/7100#issuecomment-798611741, it is a protocol violation to send an HTLC over 42 mBTC.

> why Phoenix wallet can create and receive payment more than 42mBTC, but electrum wallet not?

Electrum can receive larger payments but not larger HTLCs. It is the sender's responsibility to split up the payment into multiple smaller HTLCs (this should happen automatically by the sender's software and use MPP).

> `20210601T084133.833147Z |    ERROR | lnpeer.Peer.[LNWallet, 34.239.230.56:9735] | Exception in main_loop: RemoteMisbehaving(PaymentFailure('HTLC value over protocol maximum: 4749517000 > 4294967295 msat'))`

Looks like it might be the ACINQ node forwarding the large HTLCs. Per my reading of the spec, this is illegal.
@t-bast any idea why the ACINQ node might be forwarding these large HTLCs?

**Comment by t-bast** [comment]
I think the restriction you're referring to (`MUST set the four most significant bytes of amount_msat to 0`) is an old artifact that should have been removed from the spec...it was probably there in the early days to avoid losses (just like the maximum channel size).

AFAIK c-lightning and lnd also allow sending arbitrary amounts (as long as `max_htlc_value_in_flight_msat` is honored). I don't see a reason to have that static restriction, you can use `max_htlc_value_in_flight_msat` to more flexibly configure limits. I'll remove it from the spec and see what others think.

**Comment by t-bast** [comment]
I started the discussion here, let's see what the general feeling about this restriction is: https://github.com/lightningnetwork/lightning-rfc/pull/877
