### ISSUE TITLE
How import Paper Wallet with p2sh address (3...)

### ISSUE THREAD

**Issue by netsuke1** [spesmilo/electrum#7333]
I have a credit (UTXO) on a p2sh address (3..).
If I import the private key e.g. with the Electrum wallet
the wallet always finds only one p2pkh-address (1...) on which 
there is no credit to be found.

Here you can test it
https://segwitaddress.org/ 

How can I import the Paper Wallet or
how can I transfer the UTXO.

**Comment by NovellaShields** [comment]
use p2wpkh-p2sh:your private key
example: p2wpkh-p2sh:L2m3B54x9zmSuiGhuCmLmcXpb8qFaQ2AXGVZQZGGuS24sXyN6auX
