### ISSUE TITLE
User manually corrupted imported wallet by replacing address to 1FeexV

### ISSUE THREAD

**Issue by Avanakitavra** [spesmilo/electrum#7338]
when sending a transaction, it returns an error ,, the server returned an error ,try connecting to another server ,, tried everything, nothing helps(

**Comment by Avanakitavra** [comment]
![4](https://user-images.githubusercontent.com/70520026/121021119-3e278d00-c7cb-11eb-8e2a-f2725e8d9802.jpg)
![2](https://user-images.githubusercontent.com/70520026/121021127-3ff15080-c7cb-11eb-9c4c-bbbec800f5c4.jpg)
![3](https://user-images.githubusercontent.com/70520026/121021137-41bb1400-c7cb-11eb-8def-35feea72e3e6.jpg)

**Comment by Avanakitavra** [comment]
Sorry to lose

**Comment by SomberNight** [comment]
Please, do not waste our limited time.
Note for readers: it is easy to manually to corrupt a wallet file. OP most likely simply opened the file in a text editor and replaced the address. The private key shown (but redacted) in the picture hence does not correspond to the address.
