### ISSUE TITLE
Lightning Channels Back Up Missing

### ISSUE THREAD

**Issue by nbourbon** [spesmilo/electrum#7339]
After saving a backup from my wallet where I have a Lightning Channel Opened, I restored the backup in another place (File.backup)

All other things worked correctly, all my labels were restored etc but none of the lightning channels were stored and I don't know where to find that option

Shouldn't this automatically save all Lightning BackUps? or at least, allow us to save those backups separately?
Nico

**Comment by SomberNight** [comment]
Can reproduce.
This is a regression from https://github.com/spesmilo/electrum/commit/64a931f21e6f6699f192158e54ff8f2883682604,
which introduced "onchain_channel_backups", and renamed the old "channel_backups" key to "imported_channel_backups".

The `save_backup` method was not changed to use the new "imported_channel_backups" key, so the channel backups are in the backup file but they are ignored.
https://github.com/spesmilo/electrum/blob/7e6d65ec11c0dccfc24478471c5951d3ae586937/electrum/wallet.py#L321
