### ISSUE TITLE
Verbose transactions are currently unsupported with verbose flag of blockchain.transaction.get

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#7342]
Electrum version: 4.0.3 ([exact commit](https://github.com/spesmilo/electrum/tree/6bd1a04aee3d1adc052731793e7ebfb5023f7f56))

In our APIs we provide a `get_transaction` RPC call, which works a bit different than usual `gettransaction` command
https://github.com/spesmilo/electrum/blob/53d6eeb3f3150425a3b3a40c341998a2bda39a41/electrum/interface.py#L933
We do the same, but with `verbose` parameter turned on. 

[Here is](https://github.com/bitcartcc/bitcart/blob/6296d0dc8b29285077b970cc52b377e1ffda9147/daemons/base.py#L539-L545) how it is implemented in our API

It works perfectly in most cases and returns an additional field: `confirmations` in addition to usual transaction JSON output. 
But in some cases, more frequently on testnet, and especially often in our CI runs, we get the following error:
`aiorpcx.jsonrpc.ProtocolError: (-32600, 'ill-formed response error object: verbose transactions are currently unsupported')`

[CI Run logs](https://app.circleci.com/pipelines/github/bitcartcc/bitcart-sdk/349/workflows/d23f4218-2694-47b5-833e-af5b85293d2a/jobs/521/tests)
[The failing test](https://github.com/bitcartcc/bitcart-sdk/blob/6970e489f3c0cd6f13faecee4d4f1da930ad582a/tests/coins/btc/test_without_wallet.py#L63)
Note: the SDK being tested is just calling that `get_transaction` method on daemon directly, it's still electrum

Are those servers with unsupported verbose transactions just running some old version of ElectrumX? Is there a way to filter them out from the list of servers to connect to, or is there a better way to get confirmations for an arbitrary transaction (not always wallet-related)?

**Comment by SomberNight** [comment]
> `verbose transactions are currently unsupported`

No idea which server implementation this might be coming from.

> Are those servers with unsupported verbose transactions just running some old version of ElectrumX?

I don't think it is ElectrumX.

> Is there a way to filter them out from the list of servers to connect to

No, the protocol does not really support optional features / feature negotiation.
There is only protocol version negotiation; and servers are supposed to support all features defined for the negotiated protocol version.

> or is there a better way to get confirmations for an arbitrary transaction (not always wallet-related)?

With current protocol (1.4), you would need to
- ndeserialise the tx,
- request the history for one of its output addresses (which will include the txid and the block height it is mined at),
- if you want SPV guarantees, get merkle proof for txid at block height
- 
With protocol 1.5 (https://github.com/spesmilo/electrumx/pull/90), you will be able to just use `blockchain.transaction.get_merkle(txid)`

**Comment by MrNaif2018** [comment]
From my tests looks like the server lacking verbose support is Blockstream electrs. It can be reproduced by setting server to `electrum.blockstream.info:50002:s`. It happens on our CI systems when this server gets randomly picked, or other servers running electrs by blockstream. I will try to push adding verbose support to it forward, and with protocol 1.5 (or maybe earlier) will implement proper SPV checking of transactions

**Comment by MrNaif2018** [comment]
> With current protocol (1.4), you would need to
> 
>     deserialise the tx,
>     request the history for one of its output addresses (which will include the txid and the block height it is mined at),
>     if you want SPV guarantees, get merkle proof for txid at block height


@SomberNight, I have tried implementing the approach you mentioned, that's what I've got:

```
async def verify_transaction(self, tx_hash, tx_height):
    merkle = await self.network.get_merkle_for_transaction(tx_hash, tx_height)
    tx_height = merkle.get("block_height")
    pos = merkle.get("pos")
    merkle_branch = merkle.get("merkle")
    async with self.network.bhi_lock:
        header = self.network.blockchain().read_header(tx_height)
    self.electrum.verifier.verify_tx_is_in_block(tx_hash, merkle_branch, pos, header, tx_height)


async def get_transaction(self, tx_hash):
    result = await self.network.get_transaction(tx_hash)
    tx = self.electrum.transaction.Transaction(result)
    tx.deserialize()
    result_formatted = tx.to_json()
    address = None
    for output in result_formatted["outputs"]:
        if output["address"] is not None:
            address = output["address"]
            break
    if address is None:
        raise Exception("Invalid transaction: output address is None")
    scripthash = self.electrum.bitcoin.address_to_scripthash(address)
    history = await self.network.get_history_for_scripthash(scripthash)
    tx_height = None
    for tx_info in history:
        if tx_info["tx_hash"] == tx_hash:
            tx_height = tx_info["height"]
            break
    if tx_height is None:
        raise Exception("Invalid transaction: not included in address histories")
    current_height = self.network.get_local_height()
    confirmations = 0 if tx_height == 0 else current_height - tx_height + 1
    result_formatted.update({"confirmations": confirmations})
    await self.verify_transaction(tx_hash, tx_height)
    return result_formatted
```

Is that secure now? The only thing that concerns me is that it is fetching history for the whole address. Is that a current limitation in 1.4 protocol? But at least that exception is no longer here. Would you accept a PR changing gettransaction or adding new command to receive confirmations for a transaction in an SPV safe way? Something like mentioned here: https://github.com/spesmilo/electrum/pull/5660#issuecomment-549020370

**Comment by SomberNight** [comment]
Yes, something like that should work.

> The only thing that concerns me is that it is fetching history for the whole address. Is that a current limitation in 1.4 protocol? 

Yes, there is no neat way to do this with the current protocol. :/
It can get quite expensive to download the full history of a busy address...

> Would you accept a PR changing gettransaction or adding new command to receive confirmations for a transaction in an SPV safe way? 

I think we should wait for protocol 1.5 first. After that, yes, we could add a new method that takes a txid, and returns an SPV verified number of confirmations.

**Comment by shesek** [comment]
> From my tests looks like the server lacking verbose support is Blockstream electrs.

Yes, that is correct, the Blockstream electrs fork does not support the `verbose` option. See https://github.com/Blockstream/electrs/pull/36 for more information.
