### ISSUE TITLE
kann da jemand helfen

### ISSUE THREAD

**Issue by chris197676** [spesmilo/electrum#7343]
Diese Geldbörse ist nur lesend nutzbar. Das bedeutet, dass sie die Bitcoins nicht ausgeben können. Stellen Sie sicher, im Besitz der Seed-Worte oder der privaten Schlüssel zu sein, bevor Sie Bitcoins für diese Geldbörse anfordern.

**Comment by kw005** [comment]
Du brauchst deinen Seed (passphrase, bei Installation/Create deiner wallt) oder private key.
