### ISSUE TITLE
[request] Option to filter out addresses with transactions and no funds

### ISSUE THREAD

**Issue by neuro-fishy** [spesmilo/electrum#7345]
Hi.
It should not be a big task, imho, could you please be so kind and offer for Electrum's Addresses tab an _option_ to filter out (don't show) the addresses that have transactions and no (longer) have funds on them?
Thank you.

**Comment by SomberNight** [comment]
duplicate of https://github.com/spesmilo/electrum/pull/5823
I've just merged that now.
