### ISSUE TITLE
bitcoin private key

### ISSUE THREAD

**Issue by Avanakitavra** [spesmilo/electrum#7347]
why is no one confused by the fact that no exchange in the world will provide you with a private key to your BTC address ?absolutely all exchanges, without exception, have access to all users ' private keys ,has anyone thought about it?if you ask technical support to provide you with your private key, you will be refused with 100% probability ,and if they do, then know that your private key is known by the exchange
What kind of security can we talk about then ?

**Comment by SomberNight** [comment]
Electrum is a wallet, not an exchange. Electrum is non-custodial; the user and only the user has the keys to their coins.
