### ISSUE TITLE
Error "close_wallet"  TimeoutError()

### ISSUE THREAD

**Issue by kw005** [spesmilo/electrum#7348]
Downloaded and installed 4.1.2 on Debian 10

Restore, load_wallet + changegaplimit 500 + getbalance worked fine.
But close_wallet does not work:  TimeoutError()
After receiving the TimeoutError, command like getbalance  do not work either :(

Can anybody help?

**Comment by kw005** [comment]
When is this bug solved, when can we download the new release?

 Electrum got quite buggy over the years :(

**Comment by SomberNight** [comment]
> When is this bug solved, when can we download the new release?

We will try to do a new release soon.
Note that you can always run from source.

> Electrum got quite buggy over the years :(

You are welcome to review pull requests, recent changes, and contribute tests or other code.

**Comment by kw005** [comment]
I did and made the changes in the two files. It works fine now.

Thank you.
