### ISSUE TITLE
Lightning Channel on Mobile

### ISSUE THREAD

**Issue by ElvaGinonTeMata** [spesmilo/electrum#7351]
Hi, I'm having problems with lightning channels created on desktop, I can't see them on mobile. I don't find a way to import the channel on mobile.

**Comment by ElvaGinonTeMata** [comment]
![IMG_20210617_220551.jpg](https://user-images.githubusercontent.com/65188763/122465286-3a102200-cfb8-11eb-929a-151048c6c1b0.jpg)
This is what I can see on mobile, on desktop it's fully operational.

**Comment by ecdsa** [comment]
check the wallet information screen, to see if lightning is available

**Comment by ElvaGinonTeMata** [comment]
> check the wallet information screen, to see if lightning is available

Thank you! Now I have access to creating channels, but I can't import them. Is there any way to import channels on android?

**Comment by SomberNight** [comment]
You can import a channel backup: go to Send tab and click Scan, to scan a QR code of a backup.
A backup can only be used to close a channel and recover your coins onchain.
Just by importing a backup, the channel will not be closed, you can do that later at any point manually.

Full channels cannot be migrated/imported (so a channel you have on desktop, cannot somehow be imported on Android and then used for payments on both devices). Channels have state and using them on multiple devices would require some kind of ongoing blocking synchronisation between the devices. We haven't figured out a good way for this kind of usage yet.

**Comment by ElvaGinonTeMata** [comment]
> You can import a channel backup: go to Send tab and click Scan, to scan a QR code of a backup.
> A backup can only be used to close a channel and recover your coins onchain.
> Just by importing a backup, the channel will not be closed, you can do that later at any point manually.
> 
> Full channels cannot be migrated/imported (so a channel you have on desktop, cannot somehow be imported on Android and then used for payments on both devices). Channels have state and using them on multiple devices would require some kind of ongoing blocking synchronisation between the devices. We haven't figured out a good way for this kind of usage yet.

Ok, clear!
