### ISSUE TITLE
Make the receive description field changeable

### ISSUE THREAD

**Issue by peterfarge** [spesmilo/electrum#7353]
Could you make the description field in the Receive Tab writable again? I dont want to edit the JSON file manually.

**Comment by SomberNight** [comment]
looks same as https://github.com/spesmilo/electrum/issues/6650
please read comments there, and close this issue if you think it is a duplicate

**Comment by peterfarge** [comment]
I'm still using the legacy wallet. In my REQUEST text or QR code is no r-parameter set -> Its a unhashed Bip21 payment request. The description is added within the message parameter. If I already send out the QR Code, the local change of the description would not change the message parameter in the already send QR Code. Therefore you dont want to make the field changeable. Hm.

Personally I only give out the Bitcoin address for payment, nothing more. I have done some errors in the payment address <-> description assignment. Can you give me a hint how I can decrypt the wallet into a plain JSON file? And then encrypt it again? I know that I have to make a backup and be very careful...
