### ISSUE TITLE
[request] QR codes to sign TX w/ cold wallet & broadcast with watch only

### ISSUE THREAD

**Issue by xmready** [spesmilo/electrum#7356]
In addition to saving a signed transaction to a file and broadcasting it with the watch only wallet, QR codes could make this process easier for some use cases:

1. Generate QR code for an unsigned TX on the watch only wallet
2. Scan QR code with offline cold wallet and automatically prompt to sign the TX
3. Cold wallet signs TX and generates QR code of the signed transaction
4. Scan QR code with watch only wallet and prompt to broadcast transaction.

**Comment by SomberNight** [comment]
This use case have been supported for many years. Have you tried using the application?
I don't understand what you are asking.

**Comment by xmready** [comment]
Sorry if I'm not seeing it, but where on my Android app can I generate a QR code for an unsigned transaction? I want to scan it with my offline cold wallet device

**Comment by SomberNight** [comment]
If you have a watch-only wallet configured on your phone, just try creating a tx. As it does not have the private keys, it will not be able to sign it, and will simply show you a QR code for the unsigned tx.

> The guide only talks about saving a file and using a USB or something

Which guide?

**Comment by xmready** [comment]
Thanks! I guess I never created the TX yet. This is the doc I'm refering to:
https://electrum.readthedocs.io/en/latest/coldstorage.html#create-an-unsigned-transaction

Would be great to have the doc mention QR codes in addition to USB drives, since that seems easier for some use cases. Unless there is a doc I don't know about. Would be happy to help you update docs, but unsure about how to make PRs
