### ISSUE TITLE
Revealer plugin links to insecure (abandoned?) site

### ISSUE THREAD

**Issue by rocketeerbkw** [spesmilo/electrum#7358]
The main help button in the plugin window shows the following text "For more information, visit https://revealer.cc/." But that link sends you to a webpage that a) has an expired SSL cert and b) is just a splash page that says it's shutting down. I'm including a screenshot of the current page in case the whole site disappears.

<img width="707" alt="revealer_cc" src="https://user-images.githubusercontent.com/92499/122698907-f44c9700-d20d-11eb-9418-4e9384f90a2b.png">

There are [other links](https://github.com/spesmilo/electrum/search?q=revealer.cc) in the plugin that point to deeper URLs, and those appear to still have content.

Suggestions:

- Completely remove links to revealer.cc
- Incorporate the information into https://github.com/spesmilo/electrum-docs

If it's OK to copy the docs I'll open a PR over there.

**Comment by SomberNight** [comment]
> If it's OK to copy the docs I'll open a PR over there.

Sure, please do.

**Comment by SomberNight** [comment]
Thanks for the report.
The links have been removed by https://github.com/spesmilo/electrum/pull/7359
