### ISSUE TITLE
Bump qdarkstyle version?

### ISSUE THREAD

**Issue by hno** [spesmilo/electrum#7361]
Packaging electrum for Fedora, and the qdarkstyle version used in Fedora is currently 3.0.2 which is higher than the < 2.9 version required by electrum. And Fedora packaging policy do not allow bundling older versions.

Can this be bumped to accept a higher version, or is there a good reason why electrum requires qdarkstyle < 2.9?

The last commit related to qdarkstyle version (d1f860ccf39229121433bb125e5c12770c206270) only talks about current version beeing good. No obvious rationale behind the < 2.9 requirement, but I suppose 2.8 was the current version at the time.

I can patch this in the Fedora packaging if not suitable to bump the default max version (or remove upper limit entirely), but not if there is a valid reason why the version is locked.

**Comment by SomberNight** [comment]
Historically, there have often been issues with new versions of qdarkstyle.
The upper bound restriction was mainly there for this reason: to ~force manually testing new versions.

There is no known issue with newer versions atm.

Unfortunately it is a chore to test as Linux/Windows/mac should all be looked at.
Besides GUI elements, another thing to check is whether they grew new dependencies :)

**Comment by hno** [comment]
The same question also applies to dnspython where Fedora have moved to 2.1.0 already. But for dnspython the reasoning why the version is limited is explicitly mentioned: added build time deps. The added build time deps is not an issue here (dnspython already built separately) and there is no added runtime deps.

Have done some light testing with qdarkstyle 3.0.2 and dnspython 2.1.0 and so far no visible defects. There is no coins in this dummy test wallet to test transactions with, but at least the GUI dialogs looks sharp and it does connect successfully to the network.

**Comment by hno** [comment]
Further testing with some testnet transactions and suddenly there was a "Please wait" popup without content other than the title. Resizing it showed just garbage from the sceen (not refreshed). Not sure what the popup was really about, and it could be closed like any other window and everything seemed to work fine after.

Received an external transaction to fund the wallet.

Sent out part of it to another wallet while still unconfirmed.

Noticed the second transaction in the receiving wallet.

Then noticed the odd  popup window. May have been when the first received transaction was confirmed which happened around then.

**Comment by SomberNight** [comment]
Done in:
https://github.com/spesmilo/electrum/commit/d9b55ae5c828f490611d9198cf60eb2be186e63d
https://github.com/spesmilo/electrum/commit/1ad30e86b6d1926d0ac5bf10a69288430d3df6c6

---

> Further testing with some testnet transactions and suddenly there was a "Please wait" popup without content other than the title. Resizing it showed just garbage from the sceen (not refreshed). Not sure what the popup was really about, and it could be closed like any other window and everything seemed to work fine after.

That's unrelated. See https://github.com/spesmilo/electrum/issues/3956
