### ISSUE TITLE
Electrum wallet setup with hardware

### ISSUE THREAD

**Issue by Adrianvic032** [spesmilo/electrum#7368]
Hi there, I was trying to setup electrum wallet with Ledger Nano x as hardware but I found that the electrum on my windows 10 desktop was transmitting data of my Hardware to https://electrum.hodlister.co - Is this normal?. Please let me know. Adrianvic032@gmail.com

**Comment by SomberNight** [comment]
Electrum connects to multiple remote servers for e.g. bitcoin block headers.
`electrum.hodlister.co` is one of the default electrum servers
So yes, it is normal.

**Comment by Adrianvic032** [comment]
I have personnel node running with electrum rust server and is trying to
connect the local network but electrum app does not permit to do so. If the
data is transmitted online then there are possibilities that someone can
hack my wallet.
