### ISSUE TITLE
[Feature]  In setting, button to set as default wallet for bitcoin protocol URI

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7374]
Everytime I install either a sparrow of electrum update the last install take over my browser default wallet.

Was only able to change this by editing the windows registry manually, big PITA.

The install process change this protocol association but sometime I just want to test a wallet without it taking over my default.

**Comment by SomberNight** [comment]
there are more details in https://github.com/spesmilo/electrum/issues/8867
