### ISSUE TITLE
Cannot verify sombernight's key on Debian

### ISSUE THREAD

**Issue by johnnyApplePRNG** [spesmilo/electrum#7375]
I am following the instructions to verify signatures for linux as outlined here : https://electrum.org/#download

Verifying Thomas' key works:
```

$ gpg --verify Electrum-4.1.4.tar.gz.ThomasV.asc Electrum-4.1.4.tar.gz
gpg: Signature made Thu 17 Jun 2021 08:57:16 AM EDT
gpg:                using RSA key 6694D8DE7BE8EE5631BED9502BD5824B7F9470E6
gpg: Good signature from "Thomas Voegtlin (https://electrum.org) <thomasv@electrum.org>" [unknown]
gpg:                 aka "Thomas Voegtlin <thomasv1@gmx.de>" [unknown]
gpg:                 aka "ThomasV <thomasv1@gmx.de>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6694 D8DE 7BE8 EE56 31BE  D950 2BD5 824B 7F94 70E6
```

It did not work until I did the following:
```

$ gpg --keyserver keyserver.ubuntu.com --recv-keys 6694D8DE7BE8EE5631BED9502BD5824B7F9470E6
gpg: /home/coins/.gnupg/trustdb.gpg: trustdb created
gpg: key 2BD5824B7F9470E6: public key "Thomas Voegtlin (https://electrum.org) <thomasv@electrum.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Verifying SomberNight's key does not work:
```
$  gpg --verify Electrum-4.1.4.tar.gz.sombernight_releasekey.asc Electrum-4.1.4.tar.gz 
gpg: Signature made Thu 17 Jun 2021 09:20:21 AM EDT
gpg:                using RSA key 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC
gpg: Can't check signature: No public key

```

And neither does trying to import 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC via keyserver.ubuntu.com ... ???
```
$ gpg --keyserver keyserver.ubuntu.com --recv-keys 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC
gpg: keyserver receive failed: No data
```

What am I doing wrong?

**Comment by SomberNight** [comment]
The `keyserver.ubuntu.com` simply did not have the key uploaded. I have uploaded it now manually.

Note that the key is [committed into this git repo](https://github.com/spesmilo/electrum/blob/3bc8ef6651ed9d9aff0531b3597f80eca4886301/pubkeys/sombernight_releasekey.asc), you can get it from there even if all keyservers were down.

**Comment by johnnyApplePRNG** [comment]
Saw that there, thanks!

Just curious what this key is then?

```
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEDu3P1cr7RZBnNJsjyp7uxD35EdwFAmDLTBUACgkQyp7uxD35
EdySHA/7BR3OPHXX1wQ1fFjwEuJ/51DJhzgSL+ONF4w5r/089IIj2Kq96zpKrjVa
5/4W/K+k5n0b93jpxLSlqxdKJnLrN++0pP6j9HHUOUm2xKsR7zfjZgnlGpkDd3CN
zp6M0cJfnSBkgZtQoEPeKK4G+lxMX7Q2XPpiLVmMCWu6a5HW6CNQFUjqYtWn8Kw/
NZf896JTNcGXWricCTxgbs3dhADEaebxw2/q8gu6z4v9w72V5r6cHPvXvubwKFKz
7OQfrFTrp3LjQwOAbpcBK+oNo1o+IlPVlOUBT/CIM0eNvaCBeXfdtQ18xO+ZY78L
dpUAnRwyIU7zkwO2u8FvzF7/IhejydaaJjZ/mcHezI+g9kunMvWWBjUdP9kPFXay
yfZeCx64sVi7q96Xjg0x/EBEut8cdQBdr+9sSzzOZv7PkODo81m0ua8AnhsYaqQS
jFxUecH3g9sVpkQH/Di+uZj1WjtMLwrYb8s5Mc46LqOR9NUPvbw8DnWiEf/BqnlW
fkBuIvkc4BV8r/wTPTeFdW3wZvxjFzRMfCm6AL3y4tBt1MtOheTU6WWZkGZuzu9u
vNkxkzJ0mdw/ORE94rZgyg4NmuGTzb2BhPNIOBOovIw7dAsEE6yIJY8LJwk/yuHL
URrECHYOFns1mvxV31Bt7CyzJAdCDnjs2YIr5E00BDjNb0hkcCE=
=D/sF
-----END PGP SIGNATURE-----
```

That's what I downloaded from electrum.org just earlier today..?

Thanks for doing all the work you do on this great project btw!

**Comment by SomberNight** [comment]
> `-----BEGIN PGP SIGNATURE-----`

That is not a key but rather a signature (created with key for a message).
There are three types of objects: key(pair)s, messages, and signatures.

A private key can sign a message, which results in a signature.
Having the public key, the message, and the signature, anyone can verify whether the owner of the key indeed signed that message.

When creating releases, the message is usually a file (the released binary) (or sometimes a list of filenames and checksums in other projects).
Any user of the project (that has the public key of the developers) can download the binaries and the signatures for them, and verify that the keys indeed signed the binaries (attesting that it was the owner of the keys building the binaries instead of another party).
