### ISSUE TITLE
Login through fingerprints

### ISSUE THREAD

**Issue by nicolasmaia** [spesmilo/electrum#7381]
It would be great to have a system in which you can use biometrics like fingerprinting to log in, in lieu of your password.

**Comment by gruve-p** [comment]
For Android or for the desktop versions?

**Comment by nicolasmaia** [comment]
Android

**Comment by gruve-p** [comment]
Duplicate of https://github.com/spesmilo/electrum/issues/7560

**Comment by ecdsa** [comment]
indeed, closing as duplicate
