### ISSUE TITLE
another electrum website, is it scam

### ISSUE THREAD

**Issue by eelsisy** [spesmilo/electrum#7386]
I got these people asking me to open Electrum wallet but under a different website domain. Electrum.io
is it a scam? here is the latest correspondence with them
Quote
This email comes as a response to you completing your registration and regarding your inability to access your bitcoins which is currently locked on our platform.

We are pleased you have completing secured your account verifying by comply with the Anti-Money Laundering (AML) and Know Your Customer (KYC) policy and to let you know that our platform support Blockchain Technology as our API system interacts with the extraction software on your  wallet programmatically. This by extension means that your deposits was approved by our platform. However, the difficulty experienced while completing the integration on our platform is because the bitcoins are identified as stolen coins and it is not registered to any bitcoin hash and block, which puts it at the risk of being frozen by the mining pool. The hacked wallet where your bitcoin was extracted from has been placed on restriction as it was reported for it's illegitimate transactions by the several local authorities from different countries thereby tagging the tokens as unregistered.

As regards your bitcoins not being registered to any public hash and blocks, you would need to integrate it back into the digital ledger and make it legitimate coins for spending, and by doing so, you will need to deposit or transfer some bitcoins from a registered hash (at least 9.5% of the total extracted tokens) into your electrum wallet. The hash generated from this transaction will automatically register the extracted one. Once this is completed, your Deposit Balance will be equal to the Available Balance and you will receive a notification to be able to withdraw your funds automatically. Kindly be aware that the 9.5% will added in your available balance as well and you will be able to send it out along with the recovered tokens.

Note :  Privacy is of utmost importance at electrum wallet, We recognize the significance of protecting information which is stored on our servers or network or is intended to be stored on your servers or network and which relates to our users of our platform. This follows to say that your information will not be disclosed to any third party or parties except by your express written instructions and consent.

Sincerely,

Electrum Support Team.
Unquote

**Comment by SomberNight** [comment]
Scam.
