### ISSUE TITLE
Curl issues with Electrum Daemon - Won't load wallet or wallet not found with curl 

### ISSUE THREAD

**Issue by sudobash01** [spesmilo/electrum#7391]
I'm trying to get curl to run with the Electrum daemon, my process is below:

```
electrum-appimage load_wallet -w '/home/user/.electrum/wallets/wallet_1' 
Password:
true
```

I can run that and it runs true, I can also run this in curl:

`curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"load_wallet","params":{"wallet_path":"/home/user/.electrum/wallets/wallet_1", "password":"password"}}' http://user:password@127.0.0.1:7777`

And my output is this:

`{"id": "curltext", "jsonrpc": "2.0", "result": true}`

However, when I run this:

`curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"listaddresses","params":{"funded":true}}' http://user:password@127.0.0.1:7777`

My output is this:

```
{"id": "curltext", "jsonrpc": "2.0", "result": true}
{"id": "curltext", "jsonrpc": "2.0", "error": {"code": 1, "message": "wallet not loaded"}}
```
May I have the proper format for listaddresses, getbalance, createnewaddress, etc so that it works with the daemon using curl?

Thanks,
sudobash

**Comment by SomberNight** [comment]
You need to explicitly pass the wallet path for every command that needs a wallet.
This is because you might have multiple wallets loaded/open at the same time (using `load_wallet`).

See e.g.:

`curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"listaddresses","params":{"wallet":"~/.electrum/testnet/wallets/test_segwit_2"}}' http://user:pass@127.0.0.1:7777`

`curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"getseed","params":{"password":"1234", "wallet":"~/.electrum/testnet/wallets/test_segwit_2"}}' http://user:pass@127.0.0.1:7777`

**Comment by sudobash01** [comment]
Thank you SomberNight!

I run:

`curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"createnewaddress","params":{"password":"1234", "wallet":"~/.electrum/testnet/wallets/test_segwit_2"}}' http://user:pass@127.0.0.1:7777`

And my output is:

`{"id": "curltext", "jsonrpc": "2.0", "result": "bc1qvy0flgneyq8yrur4pna4sf2d0az3vksh6xf3e0"}`

How may I format **getaddressbalance** so that I can look up the balance for the address (bc1qvy0flgneyq8yrur4pna4sf2d0az3vksh6xf3e0) that was just generated in curl?

Thanks,
sudobash01

**Comment by sudobash01** [comment]
It worked, however, when I try to run **getaddressbalance**:

`curl --data-binary '{"id":"curltext","jsonrpc":"2.0","method":"getaddressbalance","params":{"address":"1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX","wallet":"~/.electrum/testnet/wallets/test_segwit_2"}}' http://user:pass@127.0.0.1:7777`

The output is:

`{"id": "curltext", "jsonrpc": "2.0", "error": {"code": 1, "message": "getaddressbalance() got an unexpected keyword argument 'wallet'"}}`

How do I format this with **getaddressbalance** and **payto**?

**Comment by sudobash01** [comment]
This solves my issue! Thank you!
