### ISSUE TITLE
transaction failed

### ISSUE THREAD

**Issue by Vit120586** [spesmilo/electrum#7392]
Good time! I have your wallet version 4.0.9 installed. A transaction was made to my wallet, but the money never arrived. Help with this unpleasant situation! The link to the translation is indicated below.

https://www.blockchain.com/btc/tx/45dd169ffecfd34bbcfbffb856fb2b666af1de5113cc032466d69c5c265bb008

**Comment by Vit120586** [comment]
hello, can anyone help?

**Comment by SomberNight** [comment]
That tx has already confirmed so the some money went from somewhere to somewhere.
Make sure your client is connected to the network and synchronized (green or blue orb in the bottom right).
Check that the destination address in the tx matches what you expected.
Also, if the sender was not you, they might have scammed you.
