### ISSUE TITLE
Error while building mac_osx - curl libusb-1.0.23 returns "Forbidden"

### ISSUE THREAD

**Issue by stallingerl** [spesmilo/electrum#7393]
curl https://homebrew.bintray.com/bottles/libusb-1.0.23.high_sierra.bottle.tar.gz causes Error and returns "Forbidden!"

Can't continue make_osx. Url is not working and needs to be changed.

**Comment by SomberNight** [comment]
:/
I wonder if they stopped hosting it because high sierra is too old now.
Maybe we can build it from source.

**Comment by SomberNight** [comment]
Should work now.
Try with latest master, it is now compiled from source instead.
