### ISSUE TITLE
Android tor connection has gotten less reliable

### ISSUE THREAD

**Issue by Engelberg** [spesmilo/electrum#7402]
I'm using the electrum mobile wallet, connecting over tor to an onion node that I control for the server used to query my history. Auto-connect is off. One-server mode is off.

Very frequently, the mobile wallet shows the message "Offline", even though Orbot is running on my phone and I am certain the electrum server on the onion node is operational (I can connect to it from a desktop). When I go into the Network menu and look at the status, it just says "(connecting...)

Sometimes when I get lucky and can connect, the wallet tends to show the synchronizing message over and over, repeatedly and rapidly, such that the balance is not visible for long. And then, after a while, it goes back to Offline.

Is this a problem with the mobile wallet, or is it an Orbot issue (I've seen no problems with Orbot with other apps)? Any other tips on how to get this working more reliably?

**Comment by gits7r** [comment]
if you are using your trusted server which you control why don't you set oneserver true?  Wouldn't it be better from many points of view, including but not limited to connectivity, Tor bandwidth/ circuits creation -> CPU usage / battery usage?

Second, what kind of an onion address does your server have? v2 or v3 (longer one, new one or short one, legacy?)

For me electrum + Tor on Android works fine. I use it with oneserver: true though and a v3 onion service. If these two are not to blame in your case check settings for Orbot and any kind of battery saving tools, etc. that could cut its uptime.

**Comment by Engelberg** [comment]
Hmm, I hadn't thought deeply about the oneserver setting, I just assumed it would be beneficial to be comparing block height against a wide variety of servers, so I know if my server goes down for some reason.

I'm using the long v3 onion address.

I'll assume that orbot is just being flaky; thanks for the tips.

**Comment by SomberNight** [comment]
It would help if there was a way to get verbose logs when running release build apks: https://github.com/spesmilo/electrum/issues/7409
