### ISSUE TITLE
Implement more SIGHASH types besides SIGHASH_ALL

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7408]
When spending a UTXO, the input spending it usually contains signatures (e.g. to satisfy an OP_CHECKSIG opcode) using a pubkey that the UTXO committed to.
The specific message the signature covers (the UTXO being spent, the rest of the inputs/outputs of the spending txs) depends on the sighash flags (which are chosen by the party creating the signature). Most transactions on Bitcoin mainnet use the SIGHASH_ALL flag, in which case the signature covers ~all of the spending transaction.

Other sighash flags e.g. allow not-invalidating the tx when adding more inputs, as a signature created for a specific input could simply *not* commit to what any of the other tx inputs are.

We currently only implement signing with SIGHASH_ALL.
Just grep [`transaction.py`](https://github.com/spesmilo/electrum/blob/ea24ab593f6f8fa5069e7fcb880b4c11cee4f5c5/electrum/transaction.py) for `SIGHASH_ALL`.

However, we should implement signing/verifying with the other sighash flags besides SIGHASH_ALL.

- Note that combinations of flags is also possible, such as `SIGHASH_SINGLE|SIGHASH_ANYONECANPAY`.
- Note that the sighash flags and the construction of the preimage (what is being signed) differs when spending legacy inputs and segwit inputs (and also when spending taproot inputs).
  I think legacy inputs are not worth caring about.
  The segwit sighash behaviour is documented in [bip-0143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki).
  The taproot sighash behaviour is also out of scope for now (until we implement spending from taproot utxos at least).
- Our current code supports SIGHASH_ALL for the legacy input case, and SIGHASH_ALL for the segwit input case; nothing else atm.
- We will need at least to be able to sign/verify signatures with the `SIGHASH_SINGLE|SIGHASH_ANYONECANPAY` flags to be able to implement [anchor outputs for LN](https://github.com/spesmilo/electrum/issues/6588).

So what I suggest, for now, is implementing support for all sighash flags for the segwit input case.

also see https://en.bitcoin.it/wiki/OP_CHECKSIG

**Comment by MorenoProg** [comment]
I am currently working on adding silent payment (bip-352) to electrum. I wonder if anything about SIGHASH has changed in the meantime. For silent payments, it is unsafe to use SIGHASH_ANYONECANPAY, since it would mess up the shared secret derivation. So it would be important to know, if electrum has added this feature. Also, if the behavior is different in different scopes (lets say, it is only enabled for imported wallets, and not for standard single-sig wallets (p2wpkh). Do you know anything regarding this issue?

**Comment by ecdsa** [comment]
@MorenoProg do you mean to send silent payments in Electrum, or both to send and receive them?

BIP352 receiver addresses require spending from taproot addresses, which we do not support yet.

**Comment by MorenoProg** [comment]
@ecdsa Only the sender part. The sender is not required to be able to spend taproot addresses. He is only required the send to taproot addresses, which is supported (I tested this in testnet4). There are a few more questions I struggled to get specific answers for, especially regarding wallet types in electrum, as it is important that the unspent utxos in the wallet are of a specific type ("p2pkh, p2wpkh, p2sh-p2wpkh, (p2tr: which, like you said, is not supported yet)). Do you know where I can ask specific questions regarding electrum/bip-352 integration?

**Comment by ecdsa** [comment]
You can open a separate issue if you have questions regarding integrating bip352.
