### ISSUE TITLE
I cannot show "funded or unused" filter option after close in qt gui.

### ISSUE THREAD

**Issue by aldrinpscastro** [spesmilo/electrum#7419]
After close "funded or unused" filter option in address tab, I cannot show it again.

**Comment by SomberNight** [comment]
Please elaborate; I don't fully understand the issue.
Is it that you saw the filter option at one point but after restarting the application it is no longer there (but the other filter options are there)?

**Comment by ecdsa** [comment]
I guess this user expects this filter to be displayable without going through the menu.

**Comment by aldrinpscastro** [comment]
This feature release in version 4.1.5; GUIs: add "funded or unused" filter option to Addresses tab (#5823). 
When I did go test the feature in my wallet, it is was there but after that I clicked on the "x" that was next to the feature I cannot do appear again.

**Comment by SomberNight** [comment]
You can enable it again in menubar>`Wallet`>`Addresses`>`Filter`.

**Comment by aldrinpscastro** [comment]
Thank you very much!
