### ISSUE TITLE
zero balance after replenishment

### ISSUE THREAD

**Issue by sultanovm2011** [spesmilo/electrum#7428]
The balance was replenished yesterday. www.blockchain.com shows that everything is in order. But the wallet shows that there was no transaction and the balance is -0. Screenshots in the attachment.

![Снимок экрана от 2021-07-21 17-54-16](https://user-images.githubusercontent.com/48181616/126510162-a33cad75-d231-4af9-a91a-86b2203e2581.png)
![Снимок экрана от 2021-07-21 17-53-30](https://user-images.githubusercontent.com/48181616/126510181-e5076e7f-5c80-47d6-9858-93fa92f718e9.png)

**Comment by SomberNight** [comment]
Please do not download Electrum from the ubuntu snap store. It is not maintained by us and it has a very old version that does not work anymore. Download from the official website: https://electrum.org/

**Comment by sultanovm2011** [comment]
Thank you. After installing the latest version, everything worked.
