### ISSUE TITLE
Electrum Wallet: Copy problem

### ISSUE THREAD

**Issue by mcg-simple** [spesmilo/electrum#7430]
Hi,

![grafik](https://user-images.githubusercontent.com/40126383/126877564-32b0fff8-9488-4619-aabf-8a79f118a424.png)

I've tried to copy this wallet by right clicking it and when it was in my clipboard, then another wallet address just got pasted.

![grafik](https://user-images.githubusercontent.com/40126383/126877579-6e9987a3-5073-4562-b753-10b52c6f4ac8.png)

And it turns out: This wallet is NOT owned by me, and I don't have any access to it.

Why does it copy another wallet address?

The wallet address is:
![grafik](https://user-images.githubusercontent.com/40126383/126877627-23c4f5e9-152c-4989-9fa8-b7e11c43e310.png)
And I just became: bc1qxf8rf8j72xppwn3k4h49w8mv0kwul9tw6rdgn8

What is this susposed to be? A known buddy has already lost $120 because of this issue.

Regards

**Comment by SomberNight** [comment]
Hi. Sounds like your machine is infected with a clipboard malware. This is unrelated to Electrum; it is another program, basically a virus, that detects when you are copy-pasting bitcoin addresses and changes them to attacker-controlled addresses.

see e.g. https://www.bleepingcomputer.com/news/security/clipboard-hijacker-malware-monitors-23-million-bitcoin-addresses/
