### ISSUE TITLE
JSONRPC

### ISSUE THREAD

**Issue by Masoud-garazhian** [spesmilo/electrum#7436]
i couldnt find jsonRPC api interface files in the repo, what repo they are in ?!

**Comment by SomberNight** [comment]
The same commands are available to both JSON-RPC and the CLI, you can find them in commands.py.
In particular, look for the `@command` function decorator, e.g.:
https://github.com/spesmilo/electrum/blob/07219cc4c6435011afacda546f652cea91d98cd4/electrum/commands.py#L632-L633
