### ISSUE TITLE
Lightning: Open Channel is grayed out

### ISSUE THREAD

**Issue by ondra-novak** [spesmilo/electrum#7442]
I am trying to setup new wallet using Electrum 4.1.5

Using HW wallet - Trezor

Button Open Channel is grayed out (disabled). How to enable the feature? 

Using native segwit wallet.

![image](https://user-images.githubusercontent.com/9439234/128059956-132ba9df-9721-4053-b1f9-ceed46a8fc80.png)

**Comment by SomberNight** [comment]
In menubar>`Wallet`>`Information`, what does it say for `Lightning`?

**Comment by ondra-novak** [comment]
Ok, I didn't expect the option here. It was not enabled here. ( I searched the options). Probably some navigation would help (for other users)
