### ISSUE TITLE
I sent my bitcoins from electrum to the wrong receiver

### ISSUE THREAD

**Issue by hamsterpsykos** [spesmilo/electrum#7451]
Hello. I did a terrible misstake. As you can read in the title I sent my bitcoins to the wrong receiver. Is there any chance to get them back to my wallet on electrum. And if so, what can I do? Thanks for help.

**Comment by SomberNight** [comment]
Hi. If the transaction already has confirmations then there is nothing you can do.
Btw, how did you end up sending to an unintended recipient?
