### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by Ou7law007** [spesmilo/electrum#7452]
I'm new here and trying to get myself started. 

I would really appreciate it if somebody were to update this example code as it doesn't work (for me at least):
https://github.com/spesmilo/electrum/blob/d3f65e24e143121e6209547d49463171af01b1a0/electrum/scripts/quick_start.py
And maybe the other code snippets in the 'scripts' directory :)

The error I'm getting is: __new__() missing 1 required positional argument: 'db' 
At this line: wallet = Wallet(storage)

Pretty sure I got a few more errors a few days ago when I tried it for the first time, but I manage to 'fix' them.

Thanks

**Comment by SomberNight** [comment]
You are looking at an old version of that file, see the [current HEAD of master](https://github.com/spesmilo/electrum/blob/master/electrum/scripts/quick_start.py).
(atm https://github.com/spesmilo/electrum/blob/e9f08ef69e3ec331fe0e7b166d47c4c4db157579/electrum/scripts/quick_start.py)

**Comment by SomberNight** [comment]
(Let us know if still have issues with the up-to-date script though. I've just tested it and it works for me)

**Comment by Ou7law007** [comment]
Awesome. Thank you

**Comment by Ou7law007** [comment]
OK, nvm.

Closing the GUI fixed it. It seems like there's some kind of locking going on, no clue.

Thank you anyway
