### ISSUE TITLE
daemon.stop() does not halt and stop() crashes the GUI

### ISSUE THREAD

**Issue by Ou7law007** [spesmilo/electrum#7456]
I'm unable to stop the daemon using daemon.stop() on testnet nor on mainnet with SimpleConfig and no 'offline' flag.

I'm trying to use the example code: https://github.com/spesmilo/electrum/blob/e9f08ef69e3ec331fe0e7b166d47c4c4db157579/electrum/scripts/quick_start.py

I wrapped some of the functionality and split it in multiple functions. Each function starts by creating daemon (I know this is inefficient but I can't keep the code running and I can't shutdown the whole script). I keep getting "Network is a singleton!" on the second initialization of daemon. daemon.stop() doesn't halt, not sure what to do at this point!

Also, calling stop() in the GUI causes a crash in both testnet and mainnet. (Windows 10, Electrum 4.1.5)

**Comment by SomberNight** [comment]
> Also, calling stop() in the GUI causes a crash in both testnet and mainnet.

It's a documented known issue that the CLI stop command cannot stop the GUI.
see https://github.com/spesmilo/electrum/blob/c338cebe556ddd0a9e2e5e3579a56c807b992c6e/electrum/commands.py#L217-L220

--

Re your other problems, I suspect it's due to your custom code, and it is not possible to help without seeing it.

**Comment by Ou7law007** [comment]
@SomberNight, thank you for responding.
Opps, I did not think it was necessary to post my code, since it's literally just calling this script twice https://github.com/spesmilo/electrum/blob/master/electrum/scripts/quick_start.py
Here's a snippet:
When main gets called for the second time, I get "Exception has occurred: AssertionError
Network is a singleton!" at `daemon = Daemon(config, listen_jsonrpc=False)`

````
import ctypes
import os
import asyncio
def main():
    ctypes.cdll.LoadLibrary(
        r"C:\Users\my_username\VS_Code\elect\electrum\libsecp256k1-0.dll")

    from electrum.simple_config import SimpleConfig
    from electrum import constants
    from electrum.daemon import Daemon
    from electrum.storage import WalletStorage
    from electrum.wallet import Wallet, create_new_wallet
    from electrum.wallet_db import WalletDB
    from electrum.commands import Commands
    from electrum.util import create_and_start_event_loop, log_exceptions

    loop, stopping_fut, loop_thread = create_and_start_event_loop()

    config = SimpleConfig({"testnet": True})  # to use ~/.electrum/testnet as datadir
    constants.set_testnet()  # to set testnet magic bytes
    daemon = Daemon(config, listen_jsonrpc=False)
    network = daemon.network
    assert network.asyncio_loop.is_running()

    # get wallet on disk
    wallet_dir = os.path.dirname(config.get_wallet_path())
    wallet_path = os.path.join(wallet_dir, "test_wallet")
    if not os.path.exists(wallet_path):
        create_new_wallet(path=wallet_path, config=config)

    # open wallet
    wallet = daemon.load_wallet(wallet_path, password=None, manual_upgrades=False)
    wallet.start_network(network)

    # you can use ~CLI commands by accessing command_runner
    command_runner = Commands(config=config, daemon=daemon, network=network)
    print("balance", network.run_from_another_thread(command_runner.getbalance(wallet=wallet)))
    print("addr",    network.run_from_another_thread(command_runner.getunusedaddress(wallet=wallet)))
    print("gettx",   network.run_from_another_thread(
        command_runner.gettransaction("bd3a700b2822e10a034d110c11a596ee7481732533eb6aca7f9ca02911c70a4f")))

    # but you might as well interact with the underlying methods directly
    print("balance", wallet.get_balance())
    print("addr",    wallet.get_unused_address())
    print("gettx",   network.run_from_another_thread(network.get_transaction("bd3a700b2822e10a034d110c11a596ee7481732533eb6aca7f9ca02911c70a4f")))
    stopping_fut.set_result(1)  # to stop event loop
if __name__ == '__main__':
    main()
    main()
````

**Comment by Ou7law007** [comment]
@SomberNight The problem is still present. Any suggestions?

**Comment by SomberNight** [comment]
> I'm unable to stop the daemon using daemon.stop() on testnet nor on mainnet with SimpleConfig and no 'offline' flag.
> [...]
> Also, calling stop() in the GUI causes a crash in both testnet and mainnet. (Windows 10, Electrum 4.1.5)

Stopping the daemon should now work with https://github.com/spesmilo/electrum/commit/3643b9f0560dcdc06e3f656af38e535deee99678 in ~any configuration.

However note that your `"Network is a singleton!"` error is unrelated from this.
