### ISSUE TITLE
Can't pay with Lightning

### ISSUE THREAD

**Issue by rkfg** [spesmilo/electrum#7457]
Bisecting suggests that after c65caf6c688f6775e5c5698de041ecb04513999f the `Pay` button no longer works for lightning invoices in the desktop version.

Generate an invoice (in Electrum or any other wallet), copy and paste it to the Send tab, press Pay. Nothing happens, no errors anywhere. It works in the latest AppImage release. I checked the code around a bit and [this line](https://github.com/spesmilo/electrum/blob/e9f08ef69e3ec331fe0e7b166d47c4c4db157579/electrum/gui/qt/main_window.py#L1604) seems to make it exit silently, `self.payto_e.lightning_invoice` is `None` even though it's correctly set before. Maybe it's overwritten somewhere else.

**Comment by bitromortac** [comment]
Thanks, will take care about this.
