### ISSUE TITLE
Produce packager-friendly tarballs

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#7479]
[Debian policy](https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code) states the following recommendation for upstream tarballs:

> Please do not include other code (like libraries) or data that are also shipped separately inside your source archive

[Debian policy](https://wiki.debian.org/UpstreamGuide#Pristine_Upstream_Source) also states:

> The source code archive should contain source files only, never any files that are automatically generated from other files.

[Debian policy](https://wiki.debian.org/UpstreamGuide#Pristine_Upstream_Source) also states:

> we need to rebuild all generated files to make sure that they can really be built from source, so please include methods to regenerate these files

In order to comply with Debian policy, we should distribute a packager-friendly tarball with the following changes relative to the current tarballs:

* Do not include the `packages` folder.
* Do not include `paymentrequest_pb2.py`.
* Include a script in `contrib` to generate `paymentrequest_pb2.py` from `paymentrequest.proto`.

I'm happy to implement this if it gets a Concept ACK.

**Comment by SomberNight** [comment]
> * Include a script in `contrib` to generate `paymentrequest_pb2.py` from `paymentrequest.proto`.

Instructions to generate that file are printed here in case the file is missing.

https://github.com/spesmilo/electrum/blob/2968720fb176f6eb7b08c42ce3b2cdf9f309f481/electrum/paymentrequest.py#L36-L40


> * Do not include the `packages` folder.
> * Do not include `paymentrequest_pb2.py`.

If we changed the main tarball like that, it would make it more difficult for users to run the application from it. :/
Especially when running on an offline machine, having most dependencies bundled makes things much easier.
Or do you suggest distributing *another* tarball to help packaging for Debian (and perhaps other distros)?

**Comment by SomberNight** [comment]
Alternatively, maybe we could maintain a README for packagers that contains a list of files they might want to remove from the tarball.

Note also that we include "compiled" locale files too, see
https://github.com/spesmilo/electrum/blob/2968720fb176f6eb7b08c42ce3b2cdf9f309f481/contrib/build-linux/sdist/make_sdist.sh#L36-L38
Those too are included for user convenience.

**Comment by JeremyRand** [comment]
> Or do you suggest distributing _another_ tarball to help packaging for Debian (and perhaps other distros)?

@SomberNight Yes, I'm suggesting a separate tarball.  I'm not proposing removing those files from the tarballs that average users use.  I think most distros have similar recommendations to Debian's, though I haven't explicitly looked.  The intended goal of the Debian policy is to make it easy for Debian devs to quickly audit that the compiled files haven't been tampered with (e.g. via backdoored compilers); this goal is better achieved by simply not having those files in the tarballs rather than writing a document saying which files to remove, since this way, if the set of compiled files changes, the Debian devs will immediately notice that things are broken, rather than silently including potentially sketchy binaries.

My reading of the `sdist` build scripts is that it should be quite easy to generate an extra tarball with these changes, and since all the tarballs are signed at the same time, it shouldn't impose much overhead.  Maybe I've missed some detail about how you guys handle this workflow though.

Good point about the locale files, I had missed those.

**Comment by SomberNight** [comment]
All right. We can have this if there is an organic desire for it.

That is, just for the sake of complying with every "should" in the debian upstream guide, I don't think it's worth it, but if there is an actual packager who says it would help them if we did this, then ok. i.e. I would like to hear from someone who would actually use this new file we would distribute.

Or are you such a someone? :P It might help if you provided context for where you got the idea from.

**Comment by JeremyRand** [comment]
> Or are you such a someone? :P It might help if you provided context for where you got the idea from.

@SomberNight  Yes, I am.  :)  We are packaging Electrum-NMC for Debian, and this came to our attention because there are Namecoin-specific files that we will also need to exclude.  Specifically, we generate the Namecoin-specific GUI forms from Qt-Designer XML files so that we can reuse the GUI between Namecoin Core and Electrum-NMC.  Therefore the Python code that is generated from our XML files needs to be excluded from our tarballs that we use for Debian packaging.  That's why we noticed that there are some files in upstream Electrum that also have that issue.  Because we want to keep the time commitment on Debian's end as minimal as possible so that we avoid friction getting Electrum-NMC packaged (i.e. we want to just send them the package source and have them be able to quickly approve and upload it), we want to make sure that the tarballs we send to Debian are following their policy as closely as possible.

On a practical note, I checked Debian's current Electrum package and they are not regenerating the Protobuf file from source, presumably because the maintainer didn't notice that they needed to, and no one else at Debian noticed that the resulting package violates the Debian free software policy (which mandates that all packages in the `main` repo be built from source).  Removing these files from the tarball would have prevented the Debian maintainers from overlooking this, since it's a lot easier to audit "does the package run without errors" than to audit "are there generated files in the tarball that we need to be sure to rebuild from source".

**Comment by SomberNight** [comment]
Okay. So in that case if you/someone contribute(s) the changes, we can distribute an additional sdist for packagers.

Obviously, this new distributable should be built reproducibly, but I imagine that should be easy given the current sdist being reproducible.
