### ISSUE TITLE
the wallet cannot sign the transaction, has not withdrawn money from f2pool for 3 months. what is the problem here? 

### ISSUE THREAD

**Issue by ilkizp** [spesmilo/electrum#7480]
the wallet cannot sign the transaction, has not withdrawn money from f2pool for 3 months. what is the problem here? 
34GQFkYX1umBr1MBgRcd2uszJeFiA4X1cW

**Comment by SomberNight** [comment]
I don't understand the problem. We cannot help without a more detailed explanation of the issue.
Also, if your money is stored with f2pool, then it is them you should contact.
