### ISSUE TITLE
Electrum client shows wrong reject message for small transactions

### ISSUE THREAD

**Issue by Coding-Enthusiast** [spesmilo/electrum#7483]
Bitcoin core [rejects](https://github.com/bitcoin/bitcoin/blob/81f4a3e84d6f30e7b12a9605dabc3359f614da93/src/validation.cpp#L579-L580) any transaction that has a serialized size without witness of smaller than [82 bytes](https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/policy/policy.h#L26) as non-standard. The error message will contain `tx-size-small`, however when Electrum is parsing `policy_error_messages` it doesn't have this message and instead has another error message that contains the shorter [`tx-size`](https://github.com/spesmilo/electrum/blob/a39bfba2d9a2e7509bcc1638afa67b042c1b0868/electrum/network.py#L914) for big transactions (weight > 400k), so it ends up returning a misleading error message ("too large" instead of "too small").  

This was reported on [bitcointalk](https://bitcointalk.org/index.php?topic=5358157.0).

**Comment by SomberNight** [comment]
Right... so actually network.py has both strings but they are tested in the wrong order...
https://github.com/spesmilo/electrum/blob/a39bfba2d9a2e7509bcc1638afa67b042c1b0868/electrum/network.py#L914
https://github.com/spesmilo/electrum/blob/a39bfba2d9a2e7509bcc1638afa67b042c1b0868/electrum/network.py#L995
