### ISSUE TITLE
Unauthorized withdrawal

### ISSUE THREAD

**Issue by KryptoCoinsWorld** [spesmilo/electrum#7507]
In my Electrum Wallet I find a BTC withdrawal which I did not authorize.
I would like to have this withdrawal refunded.
![Auszahlung NICHT autorisiert](https://user-images.githubusercontent.com/55102719/134417128-b54d3dac-a681-4c9f-9509-639941581826.JPG)

**Comment by SomberNight** [comment]
If the tx was not created by you, then your PC is either infected with malware or you have lost and leaked your seed words somewhere. Bitcoin transactions are irreversible so there is nothing that can be done if your coins are stolen.
