### ISSUE TITLE
Reduced gap limit but still syncing all 10000 addresses

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7512]
![image](https://user-images.githubusercontent.com/388716/134753225-3b02eba1-4482-45f9-a2a9-96e5bd396f89.png)

Is there a way to reverse having typed 
wallet.change_gap_limit(10000)

with something like wallet.change_gap_limit(100) ?

All red address are I guess supposed not to be monitored, but the syncing take a lot of time checking all of those.

**Comment by AbdussamadA** [comment]
restore from seed in a new wallet file. you can begin via file >new/restore
