### ISSUE TITLE
"Save backup" for an LN wallet results in a lightning-disabled wallet copy with imported channels backups hidden in Qt GUI

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7513]
Steps:
- have wallet with some existing lightning channels in Qt GUI open
- go to menubar>`File`>`Save backup`, complete dialog and create a backup wallet
- open backup wallet file
- notice that Channels tab is empty
    - ^ bug. there should be "imported channel backups" there
    - note that the channel backups exist, they are just not shown (see e.g. `wallet.db.get("imported_channel_backups")`)
- notice that lightning is disabled
- go to menubar>`Wallet`>`Information`, enable Lightning
- the Channels tab is now populated with the imported channel backups

**Comment by ecdsa** [comment]
This can be fixed by removing the line `new_db.put('lightning_xprv', None) in `save_backup
However, weird things arise from the fact that we create imported backups from channels that have an onchain backup.
For example, I can delete the imported backup, and no "onchain backup" is shown.

**Comment by ecdsa** [comment]
the above issue was fixed in af1fb1ae9f5776ca8f197e2d14bd2bdca7f0afe5
in addition, backups of redeemed channels are auto-removed: 90610de58ec99a83a419d14ac27f445312a9672b
