### ISSUE TITLE
Lost BTC

### ISSUE THREAD

**Issue by publee77** [spesmilo/electrum#7529]
Electrum did not accept my password when logging in. That's why I restored it with Pharse. BTC addresses and Master Public key are unchanged. But last night’s referral amount (BTC) is missing.

Thank you in advance for your help.

**Comment by publee77** [comment]
> What if someone knew your password, had access, and transfer the funds (and also, maybe changed the password)? Don't you think it's weird that Electrum didn't accept your password?

Then I shouldn't see it in the transaction after I reset Account  with pharse? unfortunately I don’t know because that was my first try

**Comment by publee77** [comment]
> It is difficult to understand the situation. You've restored from seed, checked that the addresses match, but some "amount is missing" -- do you mean there are no transactions in the history or that there is a new transaction that you do not recognise sending out your coins?

unfortunately it has no hystory... the interesting thing is that the wallet addresses are the same

but thank you for all..!

**Comment by dolcalmi** [comment]
@publee77 check your xpub, ypub or zpub in https://www.blockonomics.co/
