### ISSUE TITLE
Electrum-4.1.5/packages/bitstring.py:36: DeprecationWarning: invalid escape sequence \

### ISSUE THREAD

**Issue by Lancelight** [spesmilo/electrum#7551]
The error here isnt on line 36.  It's actually above that where there is incorrect usage of the \ character in order to draw some sort of chart in the header comments.  You cant just go using \ willy nilly as you see fit.  Those types of "drawings" dont belong in python strings.  They belong in README files.

**Comment by SomberNight** [comment]
[`bitstring`](https://github.com/scott-griffiths/bitstring) is a third party dependency, not part of this project directly.
Not sure how you are running Electrum, but e.g. if from a released tar.gz, the `packages` folder contains bundled dependencies.

I've [updated the bundled bitstring from 3.1.7 to 3.1.9](https://github.com/spesmilo/electrum/commit/6a0d7dfd48c391c44ffe30567fa6df42fbafa444) now, which it looks [might include a fix](https://github.com/scott-griffiths/bitstring/commit/b9fb32afcf513be596e75a0abfaec4e77ba9cf57#diff-6ddf46a10a246ba10e74e8e67a39d67256715d9410fc946b40e1b55ca3564372).

**Comment by Lancelight** [comment]
Ahh ok I didnt even realize it was a 3rd party lib :P  I added 3.1.9 to my 4.1.5 release of electrum and that solves the issue.
