### ISSUE TITLE
Use Unix domain sockets by default

### ISSUE THREAD

**Issue by yanmaani** [spesmilo/electrum#7553]
In principle, this change is easy, I even accidentally did it for #7545:

```
 def get_rpcsocket_default_type(osname):
+    return 'unix' if osname == 'posix' else 'tcp'
-    return 'tcp'
```

However, it should probably be tested before it's done. @JeremyRand suggested we move the conversation about this to a separate issue

**Comment by SomberNight** [comment]
I am thinking something like this:
```
def get_rpcsock_default_type():
    # Use unix domain sockets when available,
    # with the extra paranoia that in case windows "implements" them,
    # we want to test it before making it the default there.
    if hasattr(socket, 'AF_UNIX') and sys.platform != 'win32':
        return 'unix'
    return 'tcp'
```

---

I've manually tested now that daemon.py with unix sockets works:
- on ubuntu 20.04
- on macos 10.15
- on macos 11.0

It does not work on windows 10 20H2, as expected.

(from previous thread)
> I think it's reasonable to desire CI tests on macOS and Windows before we change the default, so that it's obvious if we broke something on those platforms.

Not sure what kind of CI tests you have in mind @JeremyRand. What exactly is the scenario that the tests should detect?
Is it that e.g. a future version of macos breaks unix socket support? Or maybe a future version of python? Unless the CI would always run such a test on bleeding edge OS/python versions, such breakage would not get caught.
If you mean there might be breakage right now on e.g. older macos or a flavour of *BSD or some obscure OS, not sure if CI would help with that.
My point is that ISTM we might as well just manually test now a single time on whatever configuration would be available to CI.
