### ISSUE TITLE
[Feature request] Ability to store public keys in cleartext

### ISSUE THREAD

**Issue by fennectech** [spesmilo/electrum#7556]
I would love to be able to have public keys for addresses stored without crypto.  This would allow for electrum to start without prompting a password without compromising security.   Would you guys be willing to implement this?

**Comment by SomberNight** [comment]
You can already do this in the Qt (desktop) app: when changing the password, untick "encrypt wallet file", in which case only the private keys (keystore) will be encrypted. Or is that not what you mean?
What is your use case for this btw?

**Comment by fennectech** [comment]
Not what i mean.  I want to still have to use a password for sending transactions but NOT at startup.

**Comment by SomberNight** [comment]
Right. Please try what I have described to see for yourself.
You can disable encrypting the whole wallet file but still encrypt the private keys.

**Comment by fennectech** [comment]
Ill have to try that.  Thanks
