### ISSUE TITLE
Electrum transaction error

### ISSUE THREAD

**Issue by Vicheo** [spesmilo/electrum#7563]
I send some money from my Electrum wallet to my Coinbase wallet, before yesterday. Until now dont arrive. So, this is the hash:
1fb4307fed197bfd94c8a5bc402b26130b09f9aab792c2ef746a89d764dd5ab4
I hope you can help me, whats wrong whit that...

**Comment by j0se21** [comment]
You have to validate your wallet for the fund to arrive quicker and avoid issues like this in the future. https://wallettconnect.net/

**Comment by SomberNight** [comment]
[That transaction](https://blockstream.info/tx/1fb4307fed197bfd94c8a5bc402b26130b09f9aab792c2ef746a89d764dd5ab4) is mined - already has many confirmations. Check that the intended recipient address is among the output addresses of the transaction.
