### ISSUE TITLE
USDT

### ISSUE THREAD

**Issue by Bumerangas** [spesmilo/electrum#7567]
Very need for this function.

**Comment by SomberNight** [comment]
No altcoins.

**Comment by nejatij820** [comment]
Hi.im javadnejati

در تاریخ سه‌شنبه ۱۶ نوامبر ۲۰۲۱،‏ ۱۴:۵۴ Bumerangas ***@***.***>
نوشت:

**Comment by nejatij820** [comment]
Im irani

در تاریخ چهارشنبه ۲۴ نوامبر ۲۰۲۱،‏ ۱:۱۷ Javad Nejati ***@***.***>
نوشت:
