### ISSUE TITLE
release.sh is undocumented

### ISSUE THREAD

**Issue by JeremyRand** [spesmilo/electrum#7568]
[release.sh](https://github.com/spesmilo/electrum/blob/62e1d8ed78635ca6566078583c11933581c0212b/contrib/release.sh)'s existence seems to be undocumented.  I would expect it to be mentioned in the [Creating Binaries](https://github.com/spesmilo/electrum/blob/62e1d8ed78635ca6566078583c11933581c0212b/README.rst#creating-binaries) docs.

Would a PR be accepted that adds a mention?

**Comment by ecdsa** [comment]
well, its purpose is not only to create binaries, but also to upload signatures to our website.
so it is not really useful for the single purpose of creating binaries.

what it does is pretty well explained in the header

**Comment by JeremyRand** [comment]
Ah.  My initial reading was that random members of the public who wanted to reproduce the hashes would use that script to share their signed hashes.  But on closer          reading it looks like it's using SFTP for that stuff, which I guess may not be publicly accessible.  Should I take it that that is not currently a workable use case for that script?

**Comment by ecdsa** [comment]
currently there are two roles in that script: release manager, and cosigner.
both upload signatures into the airlock.
it would be nice to extend that script to other builders, indeed.
but that is currently not the case.

**Comment by JeremyRand** [comment]
I see; thanks for clarifying.
