### ISSUE TITLE
brute force import delay

### ISSUE THREAD

**Issue by c4pt000** [spesmilo/electrum#7571]
BRUTE FORCE DELAY

./electrum/electrum daemon -d
 
 ./electrum/electrum load_wallet
                                   
 ./electrum/electrum importprivkey L4LcsctevYCPDj7wK@5u6sCqehLLpHE67WSweZyf5AfNS8KAotb5
if not wallet.can_import_privkey():
            return "Error: This type of wallet cannot import private keys. Try to create a new wal>
        try:
            addr = wallet.import_private_key(privkey, password)
            out = "Keypair imported: daemon will restore in 30 seconds.  " + addr
            time.sleep(30)
        except Exception as e:
            out = "Error: " + repr(e)
        return out

**Comment by c4pt000** [comment]
electrum/commands.py

requires "import time" at beginning of file for imports

**Comment by ecdsa** [comment]
not sure what this is about...
