### ISSUE TITLE
Jeffrey Fauni Caldejon

### ISSUE THREAD

**Issue by SantaFe0** [spesmilo/electrum#7578]
Address 2303 west Tudor road anchorage Alaska 99517 or my checking account number 124303162 Routing#(checking account # 15100337832287 go2bank thanks or either or mail the ✓ or deposited send me an email please salamat

**Comment by Babloskobar** [comment]
7578

0960593530

في الجمعة، ٢٦ نوفمبر ٢٠٢١ ٧:٥٥ ص SantaFe0 ***@***.***> كتب:

**Comment by mariabrit** [comment]
En español por favor que no hablo inglés 

Enviado desde mi iPhone
