### ISSUE TITLE
recieved half of bitcoin from sender in electrum wallet, please help me with this.

### ISSUE THREAD

**Issue by Mahu1123** [spesmilo/electrum#7581]
hello i am new to this crypto wallet stuff. So, few i made new electrum wallet and said my mate to transfer 80 aud to my wallet but when he did i only recieved half of it in my wallet. another thing to note i dont know if it is important is my friend used swyftx i think and made a payment in btc whereas electrum wallet is in mbtc so dioes that affect it?

**Comment by dolcalmi** [comment]
Please compare your btc amounts, also depending on what other wallets you are using maybe is better to change default base unit to BTC or Sats (if you are using a Lightning wallet).
