### ISSUE TITLE
bc1qs66pjuws4zm4v8mx89xz9kdzwzjsvmvyzqvrq6

### ISSUE THREAD

**Issue by Canpolat17** [spesmilo/electrum#7585]

**Comment by Canpolat17** [comment]
bc1qs66pjuws4zm4v8mx89xz9kdzwzjsvmvyzqvrq6

**Comment by dolcalmi** [comment]
> bc1qs66pjuws4zm4v8mx89xz9kdzwzjsvmvyzqvrq6

@Canpolat17 is this just spam? please close the issue or add additional information
