### ISSUE TITLE
Strange return statement in channel announcement logic with code succeeding it.

### ISSUE THREAD

**Issue by lightning-developer** [spesmilo/electrum#7595]
While reviewing https://github.com/lightning/bolts/pull/625#pullrequestreview-829402383 I also checked how electrum handles this and stumbled upon this piece of code: 

https://github.com/spesmilo/electrum/blob/56b03e2e8d6923c4d396c1272d3fafed57919a8f/electrum/lnpeer.py#L1112

It seems as if the code after the return statement is never executed and thus channels are never announced. I am a bit confused right now and thought I will just open an issue. If it is on purpose that channels are never announced then why having code after the return statement?

**Comment by bitromortac** [comment]
I'm not familiar with this part, but Electrum is currently not meant to be run as a routing node, so channels don't need to be announced.

**Comment by SomberNight** [comment]
there is a comment two lines above: "don't announce our channels"
It is as @bitromortac said. This is just currently disabled code; atm you can only have private channels.
