### ISSUE TITLE
Can't get Electrum to Broadcast / Send BTC .. frequent errors even when switching servers?

### ISSUE THREAD

**Issue by BTCetcLTC** [spesmilo/electrum#7597]
Hi all,

I have $2500 in my Electrum wallet that is stuck and I'm unable to get it out.

And is Electrum fees always so high? the fee was 50% of what I was trying to send and that was 1 / static ....

The wallet I was trying to send to was a Tor wallet, but I can't even send it to a coinbase wallet it won't broadcast or connect to the server. 

Please help

**Comment by BTCetcLTC** [comment]
I need this money back ASAP so if someone helps me and figures this out send me your BTC wallet code and I'll tip you $100 I can't figure this out for the life of me and I've already lost money in cancelled transactions but the fees still hit me for some reason...

**Comment by BTCetcLTC** [comment]
I was able to withdraw to Coinbase with a green dot instead of a blue one, is the newest version of Electrum blocking Tor outputs?

**Comment by ecdsa** [comment]
looks like you were having issues using tor.
your description does not contain any info useful for us, though.
