### ISSUE TITLE
Binaries built on macOS 10.14.6 do not work on other versions

### ISSUE THREAD

**Issue by kralverde** [spesmilo/electrum#7607]
This may not be an electrum specific issue, but here it goes

Built a binary on 10.14.6 (and signed it with a developer cert to test it) as per the build_osx readme. The app works on that mac, but when moving it to a MacOS Big Sur 11.6.1 (20G224) we get the following error:

```
Downloads/Electrum.app/Contents/MacOS/run_electrum 
Error: Failed to load libsecp256k1.
E | ecc_fast | libsecp256k1 library failed to load. exceptions: [PyInstallerImportError("Failed to load dynlib/dll '/Users/USER/Downloads/Electrum.app/Contents/MacOS/libsecp256k1.0.dylib'. Most probably this dynlib/dll was not found when the application was frozen."), PyInstallerImportError("Failed to load dynlib/dll '/Users/USER/Downloads/Electrum.app/Contents/MacOS/libsecp256k1.0.dylib'. Most probably this dynlib/dll was not found when the application was frozen.")]
```

**Comment by kralverde** [comment]
Can anyone else try and replicate to see if I'm crazy or not?

**Comment by gruve-p** [comment]
Try building the binary on 10.14.6 without signing it with a dev cert, does that work on other versions?

**Comment by kralverde** [comment]
Don't have access to my mac hardware right now... will try in a few days.

**Comment by SomberNight** [comment]
We've just released 4.2.0, which was again built on 10.14.6. I've tested that the binary works in a VM running 10.15.3.

-----

Please test that `libsecp256k1.0.dylib` is actually included in the app you built:
```
$ file $HOME/Desktop/Electrum420.app/Contents/MacOS/libsecp256k1.0.dylib
/Users/user/Desktop/Electrum420.app/Contents/MacOS/libsecp256k1.0.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

Assuming the file is found, try loading it using python:
```
$ python3
Python 3.9.10 (main, Jan 15 2022, 11:48:15) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.cdll.LoadLibrary("/Users/user/Desktop/Electrum420.app/Contents/MacOS/libsecp256k1.0.dylib")
<CDLL '/Users/user/Desktop/Electrum420.app/Contents/MacOS/libsecp256k1.0.dylib', handle 7fa8edc359b0 at 0x10d3f5fd0>
```

**Comment by vertiond** [comment]
Thanks!  I will try again soon.

**Comment by vertiond** [comment]
Successfully built in 10.14.6 and it works in a VM running 10.15.7.
