### ISSUE TITLE
Feature request: Make a booteable Electrum ISO

### ISSUE THREAD

**Issue by i-rme** [spesmilo/electrum#761]
Using any Bitcoin wallet can be tricky, if you have any malware your bitcoins may be potentialy stolen, my solution to this is to take a small linux ISO, to embed electrum in it, to make it bootable and to copy the iso into a CD / DVD.

If a user boots this CD / DVD into his computer the Electrum wallet cannot be affected by any virus because its running in a totally different operating system that only has Electrum.

Example:
Bob uses Windows 7, he has some malware installed because he does not know how to keep secure his pc. He downloads the Electrum LiveCD ISO and burns it into a CD / DVD, he inserts that CD / DVD into his computer and he restarts the computer.
Boom, now Bob is in a linux safe enviroment, no browser, no downloads, no anything, only Electrum.
He types his seed (or restores a backup via USB) and he is into his wallet.

This could be very popular because it could be as safe as a hardware wallet without beeing offline.

**Comment by wozz** [comment]
I agree with dabura, this seems out of scope for the electrum project itself.
