### ISSUE TITLE
Phishing

### ISSUE THREAD

**Issue by madrik2** [spesmilo/electrum#7611]
Hello! I have a problem. When copying the address, I did not notice that the copied address differs from the one written in the wallet. I downloaded the application from the official site. Apparently, I became a victim of phishing. Tell me, can you do something about this?

**Comment by cricktor** [comment]
Did you verify that the downloaded Electrum is genuine?
I assume you copied an address from your Electrum wallet to receive receive some coins e.g. from an exchange or so. Now the pasted receive address differs from what you copied before. Correct?
If yes, sounds like you have some clipboard malware on your device which recognizes crypto addresses and swaps them for the attacker's own ones. Consider your device as compromized.

**Comment by ecdsa** [comment]
this is not called phishing. if you copy and paste a bitcoin address and the pasted address differs, it means that your computer is infected with malware. there is nothing we can do for you.
