### ISSUE TITLE
Need help please on downloading iPhone

### ISSUE THREAD

**Issue by Brikkbaby87** [spesmilo/electrum#7614]
Need help on downloading to iPhone

**Comment by Brikkbaby87** [comment]
Help

**Comment by dolcalmi** [comment]
@Brikkbaby87 as far as I know there is no version for iOS only for OS X

**Comment by SomberNight** [comment]
There is no iOS version of Electrum atm, only Linux/Win/macOS/Android.

Also, please do not open duplicate issues (https://github.com/spesmilo/electrum/issues/7613).
