### ISSUE TITLE
Expose Lightning is_fee_sane defaults in preferences

### ISSUE THREAD

**Issue by SkanderHelali** [spesmilo/electrum#7622]
At the moment, is_fee_sane defines two defaults, a flat 5 sat acceptable fee, or up to a 1% transaction fee as acceptable/sane limits. These aren't really communicated to the user.

Both should be configurable. The current defaults can cause 200000 sat transactions to use 2000 sat fees without warning - considerably more expensive than on-chain as seen here: https://www.reddit.com/r/Electrum/comments/rzfk0p/lightning_network_fees/

https://github.com/spesmilo/electrum/blob/bdbd59300fbd35b01605e66145458e5f396108e8/electrum/lnrouter.py#L161-L168

**Comment by ecdsa** [comment]
what do you suggest to make configurable? the percentage?

**Comment by SkanderHelali** [comment]
Preferably the percentage and perhaps the cutoff (currently 5 sat).
