### ISSUE TITLE
android.py code not updated and does not work

### ISSUE THREAD

**Issue by rPman** [spesmilo/electrum#763]
Android version does not work.

I make e4a-198.zip using make_packages script from git source.
After start and 'create/restore wallet' dialog, it is fail with error:

<pre>Traceback (most recent call last):
  File "/storage/sdcard0/sl4a/scripts/e4a-1.9.8/e4a.py", line 201, in <module>
    gui = gui.ElectrumGui(config, network)
  File "/storage/sdcard0/sl4a/scripts/e4a-1.9.8/gui/android.py", line 904, in _
init__
    wallet.init_seed(None)
AttributeError: 'OldWallet' object has no attribute 'init_seed'</pre>

https://bitcointalk.org/index.php?topic=701110.msg7939026#msg7939026

**Comment by ecdsa** [comment]
fixed now
