### ISSUE TITLE
Why can't you pay BTC when you use a multi sign wallet? How to solve。thanks

### ISSUE THREAD

**Issue by metabitcoin** [spesmilo/electrum#7641]
![image](https://user-images.githubusercontent.com/98207977/150630319-48128deb-ae7d-47f3-8301-b821762fa51c.png)
Why can't you pay BTC when you use a multi sign wallet? How to solve
。thanks

**Comment by ecdsa** [comment]
can you provide more info? which version of electrum are you using?

**Comment by metabitcoin** [comment]
Thank you for your reply. It is the latest version of electromagnet. The hardware wallet uses OneKey. I contacted OneKey. It's their problem. At present, the multi sign function of OneKey wallet is not perfect. Can only wait for updates. thank you

**Comment by SomberNight** [comment]
What is "OneKey"?

**Comment by SkanderHelali** [comment]
> OneKey

I'm assuming it's this hardware wallet: https://shop.onekey.so/

**Comment by SomberNight** [comment]
Ok... but in that case, is OP using a custom plugin or how is Electrum able to communicate with that device?
Anyway, sounds like it's not our bug.
