### ISSUE TITLE
Not displayed Segwit / Standart window (selector)

### ISSUE THREAD

**Issue by MorozovAll** [spesmilo/electrum#7642]
Big Sur 11.6.2 + Electrum 4.1.5

I installed electrum, and accidentally selected the Segwit address type - and when I try to create a Standard address type, the dialog box with the choice of the wallet type does not appear. I have reinstalled electrum several times, deleted all the folders and reinstalled - it was not possible to select the standard wallet type. How to choose it again?

**Comment by ecdsa** [comment]
There is no reason to keep using old address formats.
Old seed types can be created using the command line, eg: `electrum create --seed_type standard`
