### ISSUE TITLE
Can I upgrade an old wallet to add Lightning support?

### ISSUE THREAD

**Issue by 501st-alpha1** [spesmilo/electrum#7644]
I have an old-style wallet generated a few years ago.  The Wallet Information page says that the wallet type is `standard`, script type is `p2pkh`, seed available is `True (old)`, and keystore type is `old`.

Next to Lightning it says `Not available for this wallet.`, and the help button next to that shows this message: `Lightning is currently restricted to HD wallets with p2wpkh addresses.`

So the question: is it possible to upgrade my wallet or otherwise add p2wpkh addresses to my current wallet, or do I have to create a new wallet and sweep my Bitcoin there?  I'm guessing it's the latter, but I wanted to ask to make sure I didn't miss something.

**Comment by ecdsa** [comment]
No, you cannot. Lightning requires segwit addresses.
Electrum seeds encode information about the type of addresses that are derived; this is why you nedd a new seed.

**Comment by 501st-alpha1** [comment]
Makes sense, thanks for the confirmation!
