### ISSUE TITLE
Many trampoline payment attempts due to wrong TrampolineFeeInsufficient attribution

### ISSUE THREAD

**Issue by bitromortac** [spesmilo/electrum#7648]
Consider a trampoline payment via two forwarders:
starting with fee levels 
```
trampoline_fee_levels = {'T1': 0, 'T2': 0}
```
sender -> T1 -> T2 -> receiver (100 sat)

* on first attempt, T1 complains that it doesn't get enough fees to forward to T2:
```
f.a.e.p.relay.NodeRelay PAY - completed incoming multi-part payment with parts=1 paidAmount=100000 msat
f.a.e.p.relay.NodeRelay PAY - rejecting trampoline payment reason=TrampolineFeeInsufficient
```
so the fee level is bumped for T1, where the `erring_node_id` is that of T1
https://github.com/spesmilo/electrum/blob/a3e1d2e25e78231b30ff1103345095827a909d88/electrum/lnworker.py#L1242

* on the second try, T1 accepts the incoming trampoline payment and searches a route to T2:
```
INFO  f.a.e.p.relay.NodeRelay PAY - completed incoming multi-part payment with parts=1 paidAmount=101010 msat
INFO  f.a.e.p.relay.NodeRelay PAY - relaying trampoline payment (amountIn=101010 msat expiryIn=CltvExpiry(2139982) amountOut=100000 msat expiryOut=CltvExpiry(2139406))
INFO  f.a.eclair.router.Router PAY - finding routes 02bf82e22f99dcd7ac1de4aad5152ce48f0694c46ec582567f379e0adbf81e2d0f->03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 with assistedChannels= ignoreNodes= ignoreChannels= excludedChannels=
INFO  f.a.eclair.router.Router PAY - finding routes with randomize=false params=RouteParams(false,SearchBoundaries(1010 msat,0.0,6,CltvExpiryDelta(576)),Left(WeightRatios(0.0,0.05,0.4,0.55,RelayFees(500 msat,200))),MultiPartParams(15000000 msat,5),control,true)
INFO  f.a.e.p.s.MultiPartPaymentLifecycle PAY n:03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 - 1 routes found (attempt=1/5)
INFO  f.a.e.p.s.PaymentLifecycle PAY - route found: attempt=1/1 route=03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 channels=2001467x54x1
```
T2 fails back, because it doesn't get any fees at that point.
T1 sees:
```
WARN  f.a.e.p.s.PaymentLifecycle PAY - received an error message from target nodeId=03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134, failing the payment (failure=TrampolineFeeInsufficient)
WARN  f.a.e.p.s.MultiPartPaymentLifecycle PAY - multi-part payment failed
```
And the sender receives this `TrampolineFeeInsufficient` error from T1 and falsely bumps the fee level of T1. The problem is that T1 should wrap the trampoline error with its shared secret, I think (see [trampoline proposal](https://github.com/lightning/bolts/blob/038575ac38ced9eee5ace09dd5ec9ba7515cad55/proposals/trampoline.md)), but it doesn't. This way, we can't attribute the failure to the second node, which is why we bump the fee level for T1 indefinitely until we give up, or another order of forwarders is chosen such that the payment can go through.

To circumvent these problems, I suggest to remove all second trampoline scenarios where possible (trampoline to legacy payments) and bump a global fee level applied to all trampoline forwarders in the e2e case where we sometimes have to use two trampoline forwarders (with the downside of paying double the fees).

**Comment by SomberNight** [comment]
I think this was mostly "solved" by using a global "trampoline fee level" (in https://github.com/spesmilo/electrum/pull/7623) (it is actually per `PaySession` now, but the point is that it is shared between the TFs).

The issue is not only that the trampoline proposal lacks attribution of errors, but also that the error messages do not contain the actual expected forwarding fees. If we had both these, payments could resolve with much fewer retries.
This is out of our control however.
