### ISSUE TITLE
Funds stolend from Electron Wallet 

### ISSUE THREAD

**Issue by radubirsan** [spesmilo/electrum#7649]
<img width="849" alt="Screenshot 2022-02-03 at 01 40 09" src="https://user-images.githubusercontent.com/3396903/152257231-144462a8-ede6-44df-b214-df74ec61098d.png">
Electrum 4.0.9 MacOS Big Sur
Never shared the private keys.
Here is the transaction hash:
a56513ac091f6afceeab954f4bdfc9217283ba762deea2611cb192511728b8f4

took 0.5 btc from me and a total of 26 from other users

**Comment by ecdsa** [comment]
sorry, but we cannot help you.
the most likely explanation is that your seed has been compromised
