### ISSUE TITLE
copy paste do not work well 

### ISSUE THREAD

**Issue by Zoran8** [spesmilo/electrum#7651]
When the wallet address is copied, the paste is incorrect.
![electrum issue](https://user-images.githubusercontent.com/94904971/152540456-47c70949-be1c-4c06-b546-c204a59d1aad.jpg)

**Comment by ecdsa** [comment]
The issue is not with Electrum. It is very likely that your computer is infected with malware.
( Note: I wonder why the pasted address contains uppercase characters. Maybe it is a deliberate choice, to make visual comparison more difficult.)
