### ISSUE TITLE
Electrum Wallet Not Connected

### ISSUE THREAD

**Issue by cryptoking20** [spesmilo/electrum#7659]
My electrum wallet will not connect. I tried opening my wallet in tails and on windows. No matter what I do it just will not connect. I've tried selecting on/off proxy and auto-connect, nothing seems to help. Any idea how I can get connected back to my Electrum wallet as I have funds on it. I have my private seed but have deleted the wallet and tried restoring. This doesn't help either. It all of a sudden went unconnected in the middle of confirming a transaction. I've used my setup the exact same for months. Not sure what caused this. Any ideas?

**Comment by SomberNight** [comment]
If latest, please share [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging).
