### ISSUE TITLE
Invalid address displayed during message signing with Trezor

### ISSUE THREAD

**Issue by bosomt** [spesmilo/electrum#7670]
See screenshot vs photo of device during same operation.
Signing bech32 wallet/address but Legacy address displayed on device display including unknown derivation path.
Maybe @matejcik  can check it ?

I was able to reproduce issue with 
2.4.3 0x595b14254c1abb2be3f69e42c7932f1eca8cf1b1 and
2.4.4 0x0e27423cffb3b6047028c61890bec43bf626adc7

<img width="618" alt="Screenshot 2022-02-17 at 15 59 32" src="https://user-images.githubusercontent.com/31506317/154509002-736af660-99a0-492d-8ce9-538ffcd24184.png">

<img width="703" alt="Screenshot 2022-02-17 at 16 02 27" src="https://user-images.githubusercontent.com/31506317/154509163-4a564d44-b6de-4c96-9a7c-b85837aa1175.png">

<img width="754" alt="Screenshot 2022-02-17 at 16 02 40" src="https://user-images.githubusercontent.com/31506317/154509109-3e62f4ea-0cf0-4fc0-a1af-1af3fcba664e.png">

edit: latest version of electrum 4.1.5 macOS

<img width="373" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/154509626-10c32b0c-7c74-4109-bf34-6fd66a4d83c8.png">

**Comment by bosomt** [comment]
restes with T1 

**QA NOK** 1.10.6 /same commit/  legacy address and warning displayed
**QA OK**  1.10.5 /public version commit 0xffa96205fb5e22b43e7b08a3dbc3cdeee0931de3/ bech32 address displayed

**Comment by andrewkozlik** [comment]
I think Electrum is sending the wrong script type in order to force Trezor to generate a signature without the BIP-137 script type information. As @matejcik stated, this can be done properly by setting the correct script type and `no_script_type=True`.

**Comment by SomberNight** [comment]
I guess you are talking about this line?
https://github.com/spesmilo/electrum/blob/dcbbcf9fb1215d7c2055ad3144f0a64bd4935fdc/electrum/plugins/trezor/clientbase.py#L235-L239
https://github.com/trezor/trezor-firmware/blob/2b6f1a4d5c73c352170c360a49041d3b87adf95b/python/src/trezorlib/btc.py#L215-L216
We are not setting either argument atm.

**Comment by SomberNight** [comment]
@matejcik 
> I suspect this might have been deliberate, to allow Trezor signing without our custom tweaks. FWIW it is now possible to pass no_script_type which will show the correct address but doesn't do the tweaks. Also there is the option of explicitly stripping the tweak away.

By "tweaks" do you mean the "BIP-137 script type information" @andrewkozlik mentioned? (i.e. the value of the first byte of the sig)

**Comment by matejcik** [comment]
> By "tweaks" do you mean the "BIP-137 script type information

yes, i was not aware that there is a BIP for that

**Comment by SomberNight** [comment]
I tested with a Trezor 1, firmware 1.9.1, and `no_script_type=True` was ignored.
After updating fw to 1.10.5, it is respected.
