### ISSUE TITLE
Hey, I've exported my Electrum wallet private key from my legacy wallet; addresses start with 1. I am now trying to import that wallet as BC1 (because I've accidentally received funds to it via my btpayserver) so I can recover my btcpay wallet.

### ISSUE THREAD

**Issue by wifenill** [spesmilo/electrum#7673]
Hey, I've exported my Electrum wallet private key from my legacy wallet; addresses start with 1. I am now trying to import that wallet as BC1 (because I've accidentally received funds to it via my btpayserver) so I can recover my btcpay wallet.

What I did:
1. Exported private key as CSV
2. Created a wallet in electrum, imported CV but cannot click on the Next as it's grayed out.

What's the best way for me to import my legacy wallet keys and add segwit format to it?
Also, can I just export my recovery seed as I haven't backed up my wallet on the initial setup?

**Comment by ecdsa** [comment]
try importing them with the following prefix `p2wpkh:<private key here>`

**Comment by SomberNight** [comment]
> Created a wallet in electrum, imported CV but cannot click on the Next as it's grayed out.

You cannot create a wallet directly from the exported CSV.
The CSV has a column that has WIF private keys. You can try to create a wallet from a whitespace-separated list of private keys.

Given a privkey such as `p2pkh:cRyfp9nJ8soK1bBUJAcWbMrsJZxKJpe7HBSxz5uXVbwydvUxz9zT`,
the first part (`p2pkh`) is about the script type.
To get bc1 addresses, change that to `p2wpkh`.

>  Also, can I just export my recovery seed as I haven't backed up my wallet on the initial setup?

Go to menubar>`Wallet`>`Information`. What are the first few lines there - and in particular `Seed available`?
