### ISSUE TITLE
im forgot my seeds in desktop app!!!

### ISSUE THREAD

**Issue by parsrango** [spesmilo/electrum#7678]
hi 
i have my account information but forgot my seeds how can i recover my account please help me !!
its so important for me , if you can help me send a email on this account samimi464@gmail.com

**Comment by SomberNight** [comment]
Hi. What type of information do you remember (do not reveal passwords/etc)?
Do you have your wallet file? Do you know the password for it? What type of wallet have you created with Electrum?

In general we cannot help you recover your wallet - Electrum is a non-custodial wallet, not a bank, the user has control of their money which comes with responsibility.

**Comment by parsrango** [comment]
> Hi. What type of information do you remember (do not reveal passwords/etc)? Do you have your wallet file? Do you know the password for it? What type of wallet have you created with Electrum?
> 
> In general we cannot help you recover your wallet - Electrum is a non-custodial wallet, not a bank, the user has control of their money which comes with responsibility.

i have my id & password & receive address & master publickey & wallet type is standard

**Comment by parsrango** [comment]
I have my password ,id , receive address , master public key & wallet type
is standard

**Comment by ecdsa** [comment]
you have been asked "do you have your wallet file".
you did not reply, I guess it means "no".
if you do not have your wallet file, your password is useless, and your coins are lost.
