### ISSUE TITLE
Bug in RPC command `getaddressbalance`

### ISSUE THREAD

**Issue by cculianu** [spesmilo/electrum#7684]
There is a bug in the daemon RPC command `getaddressbalance` which ultimately calls into protocol command `blockchain.scripthash.get_balance`.

This check here [in interface.py get_balance_for_scripthash](https://github.com/spesmilo/electrum/blob/master/electrum/interface.py#L1023) asserts that the `'unconfirmed'` balance cannot be negative. This is wrong. It  most certainly can be negative.  See for reference ElectrumX server implementaton here:

- [Implementation of get_balance](https://github.com/spesmilo/electrumx/blob/c8d2cc0d5cf9e549a90ca876d85fed9a90b8c4ed/electrumx/server/session.py#L1133)
- Which ultimately calls [this function in mempool.py to get the unconfirmed balance](https://github.com/spesmilo/electrumx/blob/c8d2cc0d5cf9e549a90ca876d85fed9a90b8c4ed/electrumx/server/mempool.py#L368), which can return a negative value in the case where mempool spends are spending confirmed coins.

Steps to reproduce:

1. Get an address that has confirmed coins on it only (no mempool coins) initially.
2. Check its balance first using RPC `getaddressbalance XXX`. You should see some nonzero value in `'confirmed'` and `0` in `'unconfirmed`'.
3. Next, spend all of the confirmed coins to **another address**
4. Then, quickly, before the block confirms, run electrum RPC command `getaddressbalance XXX` for that first address again. The server returns a negative value in `'unconfirmed'` now.
5.  Observe the RPC fail on that assertion that unconfirmed balance cannot be negative (which it now is, of course).

Suggest: [relax the assertion such that it can be negative, here](https://github.com/spesmilo/electrum/blob/master/electrum/interface.py#L1023).

**Comment by cculianu** [comment]
For reference, [original bug was reported to Fulcrum](https://github.com/cculianu/Fulcrum/issues/105), but this happens in ElectrumX as well, so the bug really is in Electrum.

**Comment by coval3nte** [comment]
Proposed fix #7685

**Comment by ecdsa** [comment]
merged, closing this
