### ISSUE TITLE
Rpcsock Managing Suggestion

### ISSUE THREAD

**Issue by coval3nte** [spesmilo/electrum#7686]
In the electrum's developing version there's the possibility to communicate through an unix socket (recently implemented by @SomberNight).
This is what I found on [daemon.py. line 254](https://github.com/spesmilo/electrum/blob/master/electrum/daemon.py#L254)
`self.socktype = sockettype if sockettype != 'auto' else get_rpcsock_default_type()`
The issue is that if I set through setconfig an rpchost\port etc, the rpcsock doesn't honour this clause, so it end up spawning an unix socket instead of a tcp one. 

Suggested fix:
Edit the _if clause_ in order to consider the rpchost variable.

**Comment by SomberNight** [comment]
Well, the functionality was added by yanmaani (see https://github.com/spesmilo/electrum/pull/7545), so credit goes to them.
I made it the default, if that is what you mean.

Okay, I suppose if `sockettype == "auto"`, we could set it to tcp if `rpchost` is set.
Feel free to open a PR. I suggest passing config to `get_rpcsock_default_type`, and adding the logic inside that method.
