### ISSUE TITLE
could not open channel

### ISSUE THREAD

**Issue by AlbertoDL** [spesmilo/electrum#7705]
I installed Electrum 4.1.5 windows version.

I could not open a channel with a trampoline node
I choose the trampoline node (I tried with all the three of them), I choose the amount, set the fee, then click on Send.

This pop-up error message always appear: 

Could not open channel: StorageReadWriteError(OSError(FileNotFoundError(2, 'No such file or directory')))

**Comment by ecdsa** [comment]
looks like you have a disk/storage issue.
is your wallet stored on a usb stick?

**Comment by AlbertoDL** [comment]
I don't have disk/storage issues, the wallet is on a desktop computer. However, I tried on a different computer and it works. So it is something related to this computer even if I am not able to understand what exactly

**Comment by ecdsa** [comment]
please post a more comprehensive log

**Comment by SomberNight** [comment]
see [this re how to get debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)

**Comment by AlbertoDL** [comment]
Thank you. I copy paste here below. It seems there is no directory such as "backup electrum" there and I don't understand why it looks for that file/directory: c:\\users\\alberto\\desktop\\backup electrum

20220315T081729.821430Z |     INFO | coinchooser.CoinChooserPrivacy | Total number of buckets: 3
20220315T081729.821430Z |     INFO | coinchooser.CoinChooserPrivacy | Num candidates considered: 3. Winning penalty: 0
20220315T081729.821430Z |     INFO | coinchooser.CoinChooserPrivacy | using 1 inputs
20220315T081729.822429Z |     INFO | coinchooser.CoinChooserPrivacy | using buckets: ['00146f2e5a26df65d139f84fd715317699f719787b1c']
20220315T081731.227458Z |     INFO | lnworker.LNWallet.[transito] | adding peer 02ce014625788a61411398f83c945375663972716029ef9d8916719141dc109a1c@trampoline.hodlister.co:9740
20220315T081731.341825Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Sending INIT
20220315T081731.396623Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Received INIT
20220315T081731.425605Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Sending OPEN_CHANNEL
20220315T081731.440068Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Received QUERY_CHANNEL_RANGE
20220315T081731.441077Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Received GOSSIP_TIMESTAMP_FILTER
20220315T081731.464405Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Received CHANNEL_REESTABLISH
20220315T081731.519736Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Received ACCEPT_CHANNEL
20220315T081731.519736Z |     INFO | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | upfront shutdown script received: b''
20220315T081731.525743Z |     INFO | lnchannel.Channel | sign_next_commitment 0
20220315T081731.534737Z |     INFO | transaction | adding signature for 02e3b276bfa5e2a9a7d7cea3119668a1bcae16350459fe927d9f4518ca674742bc
20220315T081731.538735Z |    DEBUG | transaction | is_complete False
20220315T081731.540734Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Sending FUNDING_CREATED
20220315T081731.630847Z |    DEBUG | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Received FUNDING_SIGNED
20220315T081731.630847Z |     INFO | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | received funding_signed
20220315T081731.631846Z |     INFO | lnchannel.Channel | receive_new_commitment. ctn=0, len(htlc_sigs)=0
20220315T081731.643838Z |    DEBUG | lnchannel.Channel | (f0e171a795cb757d20e7ae94f40228832dd917ecdeac3bba5a3db45697764b3f) Setting channel state: PREOPENING -> OPENING
20220315T081731.668823Z |     INFO | storage.WalletStorage | saved c:\users\alberto\appdata\roaming\electrum\wallets\transito
20220315T081731.669823Z |    DEBUG | util.profiler | WalletDB._write 0.0240
20220315T081731.670822Z |     INFO | lnwatcher.LNWalletWatcher.[transito-LNW] | set_up_to_date: False
20220315T081731.688809Z |     INFO | storage.WalletStorage | saved c:\users\alberto\appdata\roaming\electrum\wallets\transito
20220315T081731.688809Z |    DEBUG | util.profiler | WalletDB._write 0.0170
20220315T081731.705799Z |    DEBUG | util.profiler | WalletDB._load_transactions 0.0070
20220315T081731.706799Z |     INFO | storage.WalletStorage | wallet path c:\users\alberto\desktop\backup electrum\transito.backup
20220315T081731.706799Z |    DEBUG | lnchannel.Channel | (f0e171a795cb757d20e7ae94f40228832dd917ecdeac3bba5a3db45697764b3f) Setting channel state: OPENING -> REDEEMED
20220315T081731.719790Z |     INFO | storage.WalletStorage | saved c:\users\alberto\appdata\roaming\electrum\wallets\transito
20220315T081731.719790Z |    DEBUG | util.profiler | WalletDB._write 0.0130
20220315T081731.720790Z |    ERROR | lnpeer.Peer.[LNWallet, trampoline.hodlister.co:9740] | Exception in channel_establishment_flow: StorageReadWriteError(OSError(FileNotFoundError(2, 'No such file or directory')))
Traceback (most recent call last):
  File "electrum\util.py", line 1598, in test_read_write_permissions
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\alberto\\desktop\\backup electrum\\transito.backup.tmptest.13812'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "electrum\storage.py", line 67, in __init__
  File "electrum\util.py", line 1604, in test_read_write_permissions
OSError: [Errno 2] No such file or directory: 'c:\\users\\alberto\\desktop\\backup electrum\\transito.backup.tmptest.13812'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "electrum\util.py", line 1118, in wrapper
  File "electrum\lnpeer.py", line 573, in wrapper
  File "electrum\lnpeer.py", line 756, in channel_establishment_flow
  File "electrum\lnworker.py", line 1023, in add_new_channel
  File "electrum\wallet.py", line 329, in save_backup
  File "electrum\storage.py", line 69, in __init__
electrum.storage.StorageReadWriteError: [Errno 2] No such file or directory: 'c:\\users\\alberto\\desktop\\backup electrum\\transito.backup.tmptest.13812'
20220315T081731.723788Z |    ERROR | lnworker.LNWallet.[transito] | Exception in _open_channel_coroutine: StorageReadWriteError(OSError(FileNotFoundError(2, 'No such file or directory')))
Traceback (most recent call last):
  File "electrum\util.py", line 1598, in test_read_write_permissions
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\alberto\\desktop\\backup electrum\\transito.backup.tmptest.13812'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "electrum\storage.py", line 67, in __init__
  File "electrum\util.py", line 1604, in test_read_write_permissions
OSError: [Errno 2] No such file or directory: 'c:\\users\\alberto\\desktop\\backup electrum\\transito.backup.tmptest.13812'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "electrum\util.py", line 1118, in wrapper
  File "electrum\lnworker.py", line 999, in _open_channel_coroutine
  File "asyncio\tasks.py", line 494, in wait_for
  File "electrum\util.py", line 1118, in wrapper
  File "electrum\lnpeer.py", line 573, in wrapper
  File "electrum\lnpeer.py", line 756, in channel_establishment_flow
  File "electrum\lnworker.py", line 1023, in add_new_channel
  File "electrum\wallet.py", line 329, in save_backup
  File "electrum\storage.py", line 69, in __init__
electrum.storage.StorageReadWriteError: [Errno 2] No such file or directory: 'c:\\users\\alberto\\desktop\\backup electrum\\transito.backup.tmptest.13812'
20220315T081731.839432Z |     INFO | lnwatcher.LNWalletWatcher.[transito-LNW] | set_up_to_date: True
20220315T081732.195187Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220315T081732.195187Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0000
20220315T081732.200184Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220315T081742.155100Z |     INFO | gui.qt.main_window.[transito] | close_wallet c:\users\alberto\appdata\roaming\electrum\wallets\transito
20220315T081742.369346Z |     INFO | storage.WalletStorage | saved c:\users\alberto\appdata\roaming\electrum\wallets\transito
20220315T081742.369346Z |    DEBUG | util.profiler | WalletDB._write 0.0270
20220315T081742.409317Z |     INFO | daemon.Daemon | on_stop() entered. initiating shutdown
20220315T081742.409317Z |     INFO | gui.qt.ElectrumGui | closing GUI
20220315T081742.410316Z |     INFO | daemon.Daemon | stopping all wallets
20220315T081742.410316Z |     INFO | daemon.Daemon | stopping network and taskgroup
20220315T081742.411317Z |     INFO | network | stopping network
20220315T081742.415314Z |     INFO | daemon.Daemon | taskgroup stopped.
20220315T081742.453351Z |     INFO | interface.[fulcrum.grey.pw:51002] | disconnecting due to: CancelledError()
20220315T081742.472971Z |     INFO | interface.[electrum.qtornado.com:50002] | disconnecting due to: CancelledError()
20220315T081742.480593Z |     INFO | interface.[electrumx.erbium.eu:50002] | disconnecting due to: CancelledError()
20220315T081742.535166Z |     INFO | interface.[guichet.centure.cc:50002] | disconnecting due to: CancelledError()
20220315T081742.692001Z |     INFO | interface.[2ex.digitaleveryware.com:50002] | disconnecting due to: CancelledError()
20220315T081743.606063Z |     INFO | interface.[94.23.247.135:50002] | disconnecting due to: CancelledError()
20220315T081744.429271Z |     INFO | daemon.Daemon | removing lockfile
20220315T081744.430270Z |     INFO | daemon.Daemon | stopped
20220315T081744.522346Z |     INFO | plugin.Plugins | stopped

**Comment by SomberNight** [comment]
> It seems there is no directory such as "backup electrum" there and I don't understand why it looks for that file/directory: c:\users\alberto\desktop\backup electrum
> ```
>  File "electrum\lnworker.py", line 1023, in add_new_channel
>  File "electrum\wallet.py", line 329, in save_backup
>  File "electrum\storage.py", line 69, in __init__
>  electrum.storage.StorageReadWriteError: [Errno 2] No such file or directory: 'c:\users\alberto\desktop\backup electrum\transito.backup.tmptest.13812'
> ```

You have `'backup_dir'` config key set to that path. That gets set when you use menubar>`File`>`Save backup`.
It is used when you manually choose to backup the wallet, and also every time a channel-open is initiated.

note: maybe the application could try to create the missing folders on the path, similar to `mkdir -p`

**Comment by ecdsa** [comment]
fixed in a15dac2b8cf15d0bfd6cb50f5c83a69b30897ffb
