### ISSUE TITLE
[Solved] Open RPC request 

### ISSUE THREAD

**Issue by TheSlackOne** [spesmilo/electrum#7714]
How I can setup the daemon to accept RPC from external hosts (`0.0.0.0`)? By default it runs for `127.0.0.1`

Edit: [I've tried this](https://github.com/spesmilo/electrum/issues/5826), but still listening to `127.0.0.1` after restarting the server.

**Comment by TheSlackOne** [comment]
Solution:

Setup RPC host:
`$ electrum setconfig rpchost 0.0.0.0`

Restart daemon:
`$ electrum stop`
`$ electrum daemon -d`

**Comment by SomberNight** [comment]
Yes, that looks correct. As said in the other thread (https://github.com/spesmilo/electrum/issues/5826), this is not recommended however.
