### ISSUE TITLE
in "Transaction -> Export -> copy to clipboard" produces base64 transaction data not hex.

### ISSUE THREAD

**Issue by Jessie-1** [spesmilo/electrum#7722]
Please make it hex so that it can be used with other services.

**Comment by SomberNight** [comment]
The spec ([BIP-0174](https://github.com/bitcoin/bips/blob/34d211aa93931fa9edb6daee98499c68c7ac0b60/bip-0174.mediawiki#encoding)) says:
> A PSBT can be represented in two ways: in binary (as a file) or as a Base64 string using the encoding described in [RFC4648](https://tools.ietf.org/html/rfc4648#section-4).

Which other services expect hex?

note: when importing (loading tx), we accept many encodings including hex

**Comment by Jessie-1** [comment]
I tried to decode base64 unsigned transaction using bitcoin core but it throws an error.

```
bitcoin-cli decoderawtransaction 'cHNidP8BAFICAAAAAXSR1JTo5cdbvq2ohAri4N1Ph6YToY8kl2IO4sE9WSQNAQAAAAD9////AcfMIwAAAAAAFgAUNpjjkt7RUJEmTGEUFs5MLUT/AEicHAsAAAEA3wIAAAAAAQG+467FYM29pkwidieC5TSkrEdLgloOJVwTYjhUHf956wEAAAAA/////wLlcCwAAAAAABepFJlkal9OuGr+ypquwHdnHyTLg2zrhxPRIwAAAAAAFgAUNpjjkt7RUJEmTGEUFs5MLUT/AEgCRzBEAiAzjM8q6FkFxlXPb6Hyp+7xgmiEk1b9oscBvFRgByq0MgIgOr8x0X5pVYXmHUXzvK9JFmLEqW1p4UzLAnoE3yPQpSABIQKmEysY3om34q2NykTiAuHSCer+7duJ1KxA8roPOX4PsQAAAAAAAA=='
error code: -22
error message:
TX decode failed
```

But its working with hex input:

```
bitcoin-cli decoderawtransaction '01000000017491d494e8e5c75bbeada8840ae2e0dd4f87a613a18f2497620ee2c13d59240d010000001f143698e392ded15091264c611416ce4c2d44ff0048000813d1230000000000fdffffff01f8cf2300000000001600143698e392ded15091264c611416ce4c2d44ff004800000000'
{
  "txid": "c65f080aa3a5bd1cbf6f5fe50a69b94e2ed5fcf9c80db5392b3155e91f676e90",
  "hash": "c65f080aa3a5bd1cbf6f5fe50a69b94e2ed5fcf9c80db5392b3155e91f676e90",
  "version": 1,
  "size": 113,
[REDACTED UNNCESSARY OUTPUT]
```

**Comment by SomberNight** [comment]
Try `bitcoin-cli decodepsbt` instead.
`decoderawtransaction` does not work for PSBTs.

**Comment by SomberNight** [comment]
Also note that the difference between your examples is much more than purely decoding base64 to hex.
They use entirely different serialisation formats. Your hex example seems to use bitcoin-core's old unsigned tx format, while the base64 example uses bip-174.
