### ISSUE TITLE
Opening "Preferences" results in segfault on macOS (crash, QtMultimedia camera handling)

### ISSUE THREAD

**Issue by bitkarrot** [spesmilo/electrum#7725]
See attached file for crash report. Happens when clicking on 'preferences' or while closing open wallets.
[electrum_crash.txt](https://github.com/spesmilo/electrum/files/8310726/electrum_crash.txt)

**Comment by SomberNight** [comment]
> Happens when clicking on 'preferences'

Maybe that's related to `QtMultimedia` and the camera-handling...

Could you test going into the `Console` tab (menubar>`View`>`Show Console`), and then running:
```
from PyQt5.QtMultimedia import QCameraInfo
```

Also, to try to narrow things down, could you test if Electrum 4.1.5 also reproduces the crash?

> crash happens [...] while closing open wallets

if you mean during application shutdown (e.g. closing last open wallet), that might be https://github.com/spesmilo/electrum/issues/6889

**Comment by bitkarrot** [comment]
> Could you test going into the `Console` tab (menubar>`View`>`Show Console`), and then running:
> 
> ```
> from PyQt5.QtMultimedia import QCameraInfo
> ```
<img width="358" alt="Screen Shot 2022-03-20 at 4 57 44 PM" src="https://user-images.githubusercontent.com/73979971/159191562-5dedbc84-3fa0-47bb-b6f0-ecc6130e88e2.png">

this import actually returns nothing. 

tried to repeat the 'preferences' crash from last night. i noticed that just open/closing wallets today its okay. when new wallets are closed and opened, that's when the crash happens, sometimes on preferences, sometimes when closing wallets. 

i'm on bigsur 11.6 if that helps. 

when i get a chance to uninstall i'll try out the earlier version

> 
> if you mean during application shutdown (e.g. closing last open wallet), that might be #6889

yes, its definitely #6889

**Comment by bitkarrot** [comment]
i installed the .dmg, not sure if that had an impact. 

perhaps i should run from source? (need to set up dev environment anyway ;)

**Comment by danshao** [comment]
Also crashes on non M1.

I'm on Mac OS Monterey 12.3 Macbook Air 2019. Crash occurs whenever I hit the Preferences menu button.

**Comment by SomberNight** [comment]
Could you either of specifically test the following steps:
- start Electrum, open a wallet
- go into the `Console` tab (menubar>`View`>`Show Console`), and then run:
  ```
  from PyQt5.QtMultimedia import QCameraInfo
  ```
- open Preferences, see if it crashes

That is, assuming the crash is related to `QtMultimedia`, I would like to test whether it helps to run the import before the Preferences dialog is opened.

**Comment by danshao** [comment]
Does not crash after I type that into console.

**Comment by bitkarrot** [comment]
Mine does not crash anymore when the above is run. 

> Could either of you specifically test the following steps:
> 
>     * start Electrum, open a wallet
> 
>     * go into the `Console` tab (menubar>`View`>`Show Console`), and then run:
>       ```
>       from PyQt5.QtMultimedia import QCameraInfo
>       ```
> 
>     * open Preferences, see if it crashes
> 
> 
> That is, assuming the crash is related to `QtMultimedia`, I would like to test whether it helps to run the import before the Preferences dialog is opened.

**Comment by SomberNight** [comment]
Thanks. So this seems identical to the issue described in https://github.com/Electron-Cash/Electron-Cash/pull/1545.
I could not so far reproduce this (tried on macos 10.15.3 and 11.3).

Regardless, looking at that PR, it seems https://github.com/spesmilo/electrum/pull/7727 might be enough to fix this.
Would either of you be able to test running from source, try to reproduce, and see if https://github.com/spesmilo/electrum/pull/7727 works?

**Comment by bitkarrot** [comment]
i checked out [SomberNight:202203_qtcamera_preferences_crash](https://github.com/SomberNight/electrum/tree/202203_qtcamera_preferences_crash)

on M1 Apple, Big Sur, version 11.6

built fine, however pycryptodomex', 'cryptography missing from the build process and also https://github.com/spesmilo/electrum/issues/6948

```
$  ./run_electrum
Error: Failed to load libsecp256k1.
E | ecc_fast | libsecp256k1 library failed to load. exceptions: [OSError('dlopen(/Users/bitcarrot/electrum/electrum/libsecp256k1.0.dylib, 6): image not found'), OSError('dlopen(libsecp256k1.0.dylib, 6): image not found')]
```
I can try to build this on an intel mac later tonight see if we can get an electrum working.

**Comment by bitkarrot** [comment]
I was able to get libsecp256 issue resolved, by installing bitcoin-core version, however Building on Apple M1 Big Sur has issue with PyQt5, as posted in Dec 2021, see issue also described here: 
https://github.com/bordaigorl/rmview/issues/119

I will try rosetta to get PyQt5 installed tomorrow when i have time and see if that can get electrum running on this OS

**Comment by bitkarrot** [comment]
Problem solved for running from source: 
An alternative to getting PyQt5 installed on Apple M1 Big Sur: 
https://www.zhihu.com/question/437075754/answer/1993415429

Do the following since `pip install pyqt5` won't work: 
```
brew install pyqt5
echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc
echo 'export PATH="/opt/homebrew/opt/pyqt@5/5.15.4_1/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
```

Running it and clicking 'Preferences' is ok. Does not crash. 
Here are the logs from ./run_electrum on https://github.com/SomberNight/electrum/tree/202203_qtcamera_preferences_crash, 

 there are some exceptions thrown: 

```
E | asyncio | Task exception was never retrieved
future: <Task finished name='Task-136' coro=<Interface.get_estimatefee() done, defined at /Users/bitcarrot/github/electrum/electrum/interface.py:1093> exception=RequestTimedOut("request timed out: ('blockchain.estimatefee', [2]) (id: 6)")>
Traceback (most recent call last):
  File "/Users/bitcarrot/github/electrum/electrum/interface.py", line 171, in send_request
    response = await asyncio.wait_for(
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/bitcarrot/Library/Python/3.9/lib/python/site-packages/aiorpcx/session.py", line 540, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/Users/bitcarrot/Library/Python/3.9/lib/python/site-packages/aiorpcx/session.py", line 512, in _send_concurrent
    return await future
  File "/Users/bitcarrot/Library/Python/3.9/lib/python/site-packages/aiorpcx/curio.py", line 382, in __aexit__
    raise TaskTimeout(self._secs) from None
aiorpcx.curio.TaskTimeout: task timed out after 30s

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bitcarrot/github/electrum/electrum/interface.py", line 1100, in get_estimatefee
    res = await self.session.send_request('blockchain.estimatefee', [num_blocks])
  File "/Users/bitcarrot/github/electrum/electrum/interface.py", line 175, in send_request
    raise RequestTimedOut(f'request timed out: {args} (id: {msg_id})') from e
electrum.interface.RequestTimedOut: Network request timed out.
E | asyncio | Task exception was never retrieved
future: <Task finished name='Task-135' coro=<Interface.get_estimatefee() done, defined at /Users/bitcarrot/github/electrum/electrum/interface.py:1093> exception=RequestTimedOut("request timed out: ('blockchain.estimatefee', [5]) (id: 5)")>
Traceback (most recent call last):
  File "/Users/bitcarrot/github/electrum/electrum/interface.py", line 171, in send_request
    response = await asyncio.wait_for(
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/bitcarrot/Library/Python/3.9/lib/python/site-packages/aiorpcx/session.py", line 540, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/Users/bitcarrot/Library/Python/3.9/lib/python/site-packages/aiorpcx/session.py", line 512, in _send_concurrent
    return await future
  File "/Users/bitcarrot/Library/Python/3.9/lib/python/site-packages/aiorpcx/curio.py", line 382, in __aexit__
    raise TaskTimeout(self._secs) from None
aiorpcx.curio.TaskTimeout: task timed out after 30s

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bitcarrot/github/electrum/electrum/interface.py", line 1100, in get_estimatefee
    res = await self.session.send_request('blockchain.estimatefee', [num_blocks])
  File "/Users/bitcarrot/github/electrum/electrum/interface.py", line 175, in send_request
    raise RequestTimedOut(f'request timed out: {args} (id: {msg_id})') from e
electrum.interface.RequestTimedOut: Network request timed out.
```

**Comment by SomberNight** [comment]
Ok, so https://github.com/spesmilo/electrum/pull/7727 hopefully fixes this. Closing.

**Comment by bitkarrot** [comment]
Regarding the build from source notes on Apple M1, is there a place on electrum-docs or elsewhere I can consolidate my notes? It was a bit cumbersome the build process?

Thanks @SomberNight

**Comment by SomberNight** [comment]
@bitkarrot you can create a file, e.g. `notes_for_arm.md` inside `contrib/osx`, and make a PR.
