### ISSUE TITLE
Feature request: Make "contacts" applied to all wallets.

### ISSUE THREAD

**Issue by Jessie-1** [spesmilo/electrum#7726]
Currently contacts are confined to individual wallets.

**Comment by ecdsa** [comment]
this would imply that they are stored outside the wallet file, and probably unencrypted. 
not sure if that is a good idea

**Comment by Jessie-1** [comment]
True. There will be a compromise of privacy and one can change contact bitcoin address if an attacker gets hold of the device. 

How about having an option to import contacts from other wallet by decrypting a wallet ?

**Comment by ecdsa** [comment]
There already is an import/export function for contacts, in the Qt menu.

**Comment by Jessie-1** [comment]
Oh great. My bad. Sorry to waste your time.
