### ISSUE TITLE
Where's ThomasV's public key?

### ISSUE THREAD

**Issue by uskrusader** [spesmilo/electrum#7734]
How do I import ThomasV's public key using the ubunto command line?

Instructions on electrum.org do not seem to be up to date.

![image](https://user-images.githubusercontent.com/77032141/159837020-61f78ceb-e5d9-421c-ba57-86d73877f6f3.jpeg)

![image](https://user-images.githubusercontent.com/77032141/159837037-f8b78057-9dec-4f91-8ed4-512c78ccd080.jpeg)

**Comment by accumulator** [comment]
You need to download the signature file. Link can be found on [this page](https://electrum.org/#download)

**Comment by uskrusader** [comment]
> You need to download the signature file. Link can be found on [this page](https://electrum.org/#download)

I am using that page:
"gpg --import ThomasV.asc"  does not work, see pic above?!

**Comment by uskrusader** [comment]
ok, I'm pretty new to Linux/ubunto, so how do I import the key at:

https://github.com/spesmilo/electrum-web/blob/c2629bf07d54e959fe7fbf173ae7bbbcf0df6318/panel-download.html#L8

....into linux if `gpg --import ThomasV.asc` does not work?

It seems pretty hard to verify the signature with instructions given on the website. 
I appreciate the feedback

**Comment by SomberNight** [comment]
`$ wget https://raw.githubusercontent.com/spesmilo/electrum/master/pubkeys/ThomasV.asc`

**Comment by uskrusader** [comment]
finally figured it out, thank you!
