### ISSUE TITLE
Error when opening Electrum App

### ISSUE THREAD

**Issue by mastawitcha** [spesmilo/electrum#7735]
I've just downloaded the newest version for Windows 10 of Electrum and I get a loadlibrary failed with error 87. How do I fix this? Someone said DAPPS, that doesn't make sense

**Comment by SomberNight** [comment]
Could you test with Electrum 4.1.5?

**Comment by gruve-p** [comment]
Can you try with [4.1.5](https://download.electrum.org/4.1.5/electrum-4.1.5-setup.exe)

**Comment by SomberNight** [comment]
Also try with 4.2.1.
Among other things, it might give you a more detailed error message (due to using newer pyinstaller).
