### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by ChaBoiTrump** [spesmilo/electrum#7752]
i sent a payment on 2022-04-01 for 0.00688259BTC
and when i sent this payment for some reason it started another transaction to an address im not sure where it came from it never asked me to put in my password or anything After i logged back into electrum i saw that 5 hours AFTER i sent the payment to myself  this random payment has been confirmed going who knows where

 transaction id 94ecd7c45f94cf69e80eb6b848d8c2c4dfd7bf77c45ec7b33be66c5e2c06fd6e 
sent to 
1DSKooTPHD3wadYBKi18KbEnqcYok6CPp9
sent from 
bc1qs2g6me8hv4s2gjqqz69pfsuqm0hfvky8ksz6gx

original payment that i made
transaction id
bd1e2e10457c306c2535e1667cdfd53085841846b486c8bc0539dbfb837f6dc2
sent from
 bc1q446umq2y44ekzk8gzxn209s4h64n54zfltncc9
sent to 
3K8TC6u8RZL2zWqttNzMAZrdUMhzcct6of and 3K8TC6u8RZL2zWqttNzMAZrdUMhzcct6of

https://www.chain.so/address/BTC/bc1qs2g6me8hv4s2gjqqz69pfsuqm0hfvky8ksz6gx

**Comment by SkanderHelali** [comment]
Did you download Electrum for the official website **and verified the binary as instructed?**
There are plenty of phishing websites that will show up on Google and link you to a malicious version of Electrum.

Regardless, transactions are irreversible. Secure your system and make sure your Electrum is actually downloaded from the official website for future transactions.

Consider your current wallet / seed compromised.

**Comment by ChaBoiTrump** [comment]
Ive been using the same wallet for around 7 months tho and this is the
first issue

**Comment by BlackHatHacker111** [comment]
I helped a lot of with this issue to recover there’s perfectly send me a friend request on discord let me help you with yours my discord is BlackHatHacker111#2333
