### ISSUE TITLE
Resolved

### ISSUE THREAD

**Issue by GitTankMusic** [spesmilo/electrum#7766]
#7767

**Comment by SomberNight** [comment]
This has been possible for many years.
See https://github.com/spesmilo/electrum/issues/7767#issuecomment-1103568291

**Comment by GitTankMusic** [comment]
> This has been possible for many years. See [#7767 (comment)](https://github.com/spesmilo/electrum/issues/7767#issuecomment-1103568291)

I didn't enter the Non-English language again when app appears the "unknown", after that I tried to use the bit39 tool(downloaded it and used it offline) to get back my private key, it worked, still thanks, good day to you!
