### ISSUE TITLE
Is there any way to get my private key from the 12 BRD recovery phrase word?

### ISSUE THREAD

**Issue by GitTankMusic** [spesmilo/electrum#7767]
BRD wallet don't give users the private keys, is there a way to get my BRD private key from my 12 BRD recovery phrase word? BRD wallet closed down, my recovery phrase is non-english recovery phrase, it seems that the non-english recovery phrase is unfortunately not compatible, so I want to use the private key to recovery my coins in new wallet.

**Comment by arslan-raza-143** [comment]
@GitTankMusic

**Comment by SomberNight** [comment]
AFAIK the "12 word BRD recovery phrase" is a BIP39 seed. You can restore from that using Electrum. During restore, go into the options and select "BIP39". Non-English language seeds are also supported, just enter your words in the application and the UI will simply say "unknown wordlist".

Regarding the derivation path and the script type, which you will be asked on the next screen after entering the seed phrase, you will have to do some trial and error. This is a weakness of BIP39.
According to https://walletsrecovery.org/ , you should try with path m/0' (note aposthrope). For the script type, try both legacy p2pkh and native segwit p2wpkh.

Report back whether it worked! :)

**Comment by GitTankMusic** [comment]
> AFAIK the "12 word BRD recovery phrase" is a BIP39 seed. You can restore from that using Electrum. During restore, go into the options and select "BIP39". Non-English language seeds are also supported, just enter your words in the application and the UI will simply say "unknown wordlist". Regarding the derivation path and the script type, which you will be asked on the next screen after entering the seed phrase, you will have to do some trial and error. This is a weakness of BIP39. According to https://walletsrecovery.org/ , you should try with path m/0' (note aposthrope). For the script type, try both legacy p2pkh and native segwit p2wpkh. Report back whether it worked! :)

I didn't enter the Non-English language again when app appears the "unknown", after that I tried to use the bit39 tool(downloaded it and used it offline) to get back my private key, it worked, still thanks, good day to you!
