### ISSUE TITLE
Cannot Swap "Cannot connect to host swaps.electrum.org ..." Windows 11

### ISSUE THREAD

**Issue by Churchexe** [spesmilo/electrum#7775]
I'm trying to swap some funds off of lightning and onto the chain but everytime I click "swap" I get this popup 
https://gyazo.com/63a9054b6ff5028973800fa21cb43bd5
then the swap menu doesn't really work. I can still use the bar for ETA and type in numbers, but the changes don't cascade. I.e. if I type 0.001 for the amount I want to swap, the other field for amount recieved doesn't update. I just updated electrum and I'm still having the issue, I am also running Windows 11 but I was running it about a week ago as well and I swapped funds to lightning without issue so I don't think that has anything to do with it but I could be wrong.

**Comment by SkanderHelali** [comment]
I can replicate on Linux.

**Comment by ecdsa** [comment]
should work now. sorry for the inconvenience.

**Comment by ecdsa** [comment]
@bitromortac the certificate was renewed, but nginx had to be restarted.
there is a `/etc/letsencrypt/renewal-hooks/` on the server, should it be used to restart nginx?

**Comment by Churchexe** [comment]
I just looked in electrum again, and now swap is just completely greyed out.
