### ISSUE TITLE
invoice-key mismatch for pre-4.0.8 outgoing onchain invoices

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7777]
On master, in the Qt `Send` tab, right-clicking an old onchain invoice results in an error:
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/gui/qt/invoice_list.py", line 155, in create_menu
    if invoice.is_lightning():
AttributeError: 'NoneType' object has no attribute 'is_lightning'
```

This is because around version 4.0.8, the key for outgoing invoices was changed: https://github.com/spesmilo/electrum/commit/cdfaaa260942b807f809c2c0414fb242a03e945a

such example invoices I have saved in a wallet:
```
a1. inv=Invoice(amount_msat=100000000, message='', time=1591209612, exp=0, outputs=[<TxOutput script=00140f4dcc26e0ac0ec1890223c4b8c5b48808cc1d67 address=tb1qpaxucfhq4s8vrzgzy0zt33d53qyvc8t8pnqg8n value=100000>], height=0, bip70=None, lightning_invoice=None)
a2. realkey='654b80e92a5032f63c251cad2ce8d109' expected_key='bcc8ea937f'
a1. inv=Invoice(amount_msat=1000000000, message='', time=1592943967, exp=0, outputs=[<TxOutput script=6a0401020304 address=None value=0>, <TxOutput script=ac21020202020202020202020202020202020202020202020202020202020202020202 address=None value=1000000>], height=0, bip70=None, lightning_invoice=None)
a2. realkey='35c7f061df3f00e195af3b205492468e' expected_key='18e079e36e'
a1. inv=Invoice(amount_msat=5500000000000, message='', time=1593687959, exp=0, outputs=[<TxOutput script=0014ec8f27fdb283bfb5f76937e3640c1e4631e9827c address=tb1qaj8j0ldjswlmtamfxl3kgrq7gcc7nqnun4dwn6 value=5500000000>], height=0, bip70=None, lightning_invoice=None)
a2. realkey='849c7f4067a248ad1dfd9a3e8c62b29c' expected_key='8d9fdab586'
```

Until recently (https://github.com/spesmilo/electrum/commit/e392197ab94715815c00503d8fd5cb881d0a26c3), there was an "id" field stored in invoices, but now we are computing the id on demand using the "new algorithm", which does not work for pre-4.0.8 invoices.

**Comment by SomberNight** [comment]
bip70 invoices also do not work.
any past bip70 invoice exhibits the issue, as they have their own "id" definiton, which we used to just copy into the invoice but not anymore:
https://github.com/spesmilo/electrum/blob/90e5984b647eb0211524e604b6fedff08894f6fd/electrum/invoices.py#L151
https://github.com/spesmilo/electrum/blob/90e5984b647eb0211524e604b6fedff08894f6fd/electrum/paymentrequest.py#L278-L279
https://github.com/spesmilo/electrum/blob/90e5984b647eb0211524e604b6fedff08894f6fd/electrum/paymentrequest.py#L138

I think there might be issues even with newly created bip70 invoices, looking at e.g.:
https://github.com/spesmilo/electrum/blob/63c8aeb54c9f161b6bfca73c77304a7e3e088ca9/electrum/gui/qt/main_window.py#L2095-L2096

**Comment by SomberNight** [comment]
Note: if we have to touch this anyway, I would like to move away from using `repr(TxOutput)` as part of the key, as it implies a hidden requirement that we never change that `repr` implementation.
https://github.com/spesmilo/electrum/blob/5f7388a475cd796c30caab688e7f8136a8c6ac27/electrum/wallet.py#L2386
https://github.com/spesmilo/electrum/blob/5f7388a475cd796c30caab688e7f8136a8c6ac27/electrum/transaction.py#L160-L161

**Comment by accumulator** [comment]
IMO the better solution is to move to opaque keys and add a few invoice lookup functions (e.g. `wallet.invoice_by_rcv_address(a)` and `wallet.invoice_by_rhash(h)` ).

This will probably be a bigger delta to implement, but it eliminates the need to recalculate keys or handle bugs accidentally introduced in past versions. The only requirement then will be that the key is unique.

Also, the same issue with calculated keys creates issues on the payment request side, where a new onchain payment request can be assigned the same receive address as an existing, expired recieve request, thereby both having the same key (yes that was recently worked around in a patch by @ecdsa, but this might encounter hitting the gap limit a bit sooner if a user is keeping a fair amount of expired payment requests)
