### ISSUE TITLE
all channels down if remote server sends an unknown channel

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#7783]
I caught a situation when ACINQ node was sending me messages for some completely unknown channel. Currently `process_message` throws an exception in such case:

https://github.com/spesmilo/electrum/blob/master/electrum/lnpeer.py#L211
```python
            if message_type not in ('error', 'warning') and 'channel_id' in payload:
                chan = self.get_channel_by_id(payload['channel_id'])
                if chan is None:
                    raise Exception('Got unknown '+ message_type)
                args = (chan, payload)
```
And this causes all other open channels to be disconnected as well. (Electrum enters reconnect loop in such case, trying to reopen channels every couple seconds)

I worked around that situation temporarily by ignoring such messages completely:

```diff
--- a/electrum/lnpeer.py
+++ b/electrum/lnpeer.py
@@ -208,7 +208,8 @@ class Peer(Logger):
             if message_type not in ('error', 'warning') and 'channel_id' in payload:
                 chan = self.get_channel_by_id(payload['channel_id'])
                 if chan is None:
-                    raise Exception('Got unknown '+ message_type)
+                    self.logger.info(f"unknown channel {payload['channel_id'].hex()}")
+                    return
                 args = (chan, payload)
             else:
                 args = (payload,)
```

Electrum version: 4.2.0

**Comment by ecdsa** [comment]
hi, can you also print the message type in the log, and post what you received from ACINQ?

**Comment by Rogach** [comment]
Awesome, thank you for the quick fix!

> hi, can you also print the message type in the log, and post what you received from ACINQ?

Unfortunately the problem went away after a while, so I can't reproduce it now, and I neglected to save the output when I was debugging the issue. I vaguely remember that message type was `channel_reestablish`, and I made an attempt of finding the corresponding funding transaction - but was unsuccessful.
