### ISSUE TITLE
AppImage fails to run: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full

### ISSUE THREAD

**Issue by marozsas** [spesmilo/electrum#7784]
I had a wallet created and running just fine with electrum-4.1.4-x86_64.AppImage.
When I tried to open my wallet today (after months without any use) I got the error message: 
`$ /home/miguel/Downloads/electrum-4.1.4-x86_64.AppImage
/tmp/.mount_electrb0wnFj/usr/bin/python3.7: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full`
Then I've tried to download the latest version, both as tar file and as appImage. Both failed:
As tar image, without installation method as described on site:
`$ python3 Electrum-4.2.1/run_electrum
Error: Failed to load libsecp256k1.
E | ecc_fast | libsecp256k1 library failed to load. exceptions:
[OSError('/home/miguel/tmp/Electrum-4.2.1/electrum/libsecp256k1.so.0: cannot open
shared object file: No such file or directory'), OSError('libsecp256k1.so.0: cannot open
shared object file: No such file or directory')]`

As App Image:
`$ /home/miguel/Downloads/electrum-4.1.4-x86_64.AppImage                                                                                            
/tmp/.mount_electrj4sCFu/usr/bin/python3.7: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full`

To run from tar file, my system fill the requirements:
`$ rpm -qa | grep -iE "python38-qt5|libsecp256k1|cryptography"
libsecp256k1-0-20150430-2.39.x86_64
python38-qt5-sip-12.9.0-2.4.x86_64
python38-cryptography-36.0.2-3.1.x86_64
python38-qt5-5.15.6-3.5.x86_64
python38-qt5-devel-5.15.6-3.5.x86_64`

My system: OpenSuse TW, updated to 20220415 

As result, I can't run Electrum to open my wallet to access my bitcoins. So it is a big deal for me, and I ask for help, please ?

**Comment by SomberNight** [comment]
First of all, please try using the latest AppImage, so 4.2.1.

> `$ /home/miguel/Downloads/electrum-4.1.4-x86_64.AppImage /tmp/.mount_electrb0wnFj/usr/bin/python3.7: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full`

This looks to be this upstream issue: https://github.com/AppImage/AppImageKit/issues/1162,
and looking at https://github.com/project-slippi/Ishiiruka/issues/323, please try running like this:
```
$ LD_PRELOAD=/lib64/libgmodule-2.0.so /home/miguel/Downloads/electrum-4.1.4-x86_64.AppImage
```

-----

> ` $ python3 Electrum-4.2.1/run_electrum Error: Failed to load libsecp256k1. E | ecc_fast | libsecp256k1 library failed to load. exceptions: [OSError('/home/miguel/tmp/Electrum-4.2.1/electrum/libsecp256k1.so.0: cannot open shared object file: No such file or directory'), OSError('libsecp256k1.so.0: cannot open shared object file: No such file or directory')]`

Electrum cannot find the libsecp256k1 shared lib. This is completely unrelated from the AppImage issue.
See https://github.com/spesmilo/electrum-docs/blob/master/libsecp256k1-linux.rst

**Comment by marozsas** [comment]
What a relief ! I got it running again and regain access to my wallet. Thank you very much !

**Comment by marozsas** [comment]
Running as instructed (LD_PRELOAD=/lib64/libgmodule-2.0.so /home/miguel/Downloads/electrum-4.1.4-x86_64.AppImage) solved the issue. Thank you.

**Comment by SomberNight** [comment]
reopening as the underlying issue is not fixed
