### ISSUE TITLE
Electrum Windows 

### ISSUE THREAD

**Issue by paulderbac** [spesmilo/electrum#7794]
I found a seed phrase, on Blockchain it says that there are 0.10293000 BTC ($3,918.42) in that wallet but when i go to Electrum using that seed phrase and it says that there are 0 BTC in that wallet. What should i do?

**Comment by SomberNight** [comment]
What software did you use to create the seed phrase originally? What kind of seed is it?

**Comment by SEREMERT** [comment]
Добрый день не знаю как создать новое обращение напишу сюда(( Более 20 часов назад отправил с кошелька деньги до сех пор нет не 1 подтверждения как сделать чтоб деньги вернулись??

**Comment by ecdsa** [comment]
closing, no answer
