### ISSUE TITLE
Helpwith lost payment

### ISSUE THREAD

**Issue by soundtechdude** [spesmilo/electrum#7800]
Hi 
I cancelled two payments from Electron that were being confirmed. Blockchain says they have been paid but the receiver has not got them.
Help !

**Comment by SomberNight** [comment]
Look up txids on [a block explorer](https://blockstream.info/), check what output addresses and amounts it says there.

**Comment by soundtechdude** [comment]
Says the correct address for the original recipient .

**Comment by SomberNight** [comment]
So what is the issue then? The recipient got paid.

**Comment by soundtechdude** [comment]
The recipient is claiming they have not been paid

**Comment by soundtechdude** [comment]
I did try and cancel. Is there a chance that action hasn't been recognised by Electrum?

**Comment by ecdsa** [comment]
@soundtechdude you cannot reverse a bitcoin payment. if the recipient claims they have not been paid, that is their problem, not a technical issue.

**Comment by soundtechdude** [comment]
HI Thanks. The payment was cancelled while waiting for confirmations.
[Cancelled transaction showing as paid RobinD.pdf](https://github.com/spesmilo/electrum/files/8646717/Cancelled.transaction.showing.as.paid.RobinD.pdf)

**Comment by panalangin** [comment]
I do not know why I lost my coins in my wallet when I dont touch then

**Comment by soundtechdude** [comment]
Recipient not stating as paid.
