### ISSUE TITLE
Fee estimates are way out of reality

### ISSUE THREAD

**Issue by jbrepogmailcom** [spesmilo/electrum#7802]
Hello, my electrum (linux version) gives about 5-10x higher estimates for fees. For example current estimated fee for next block is 10 sat (confirmed by reality and by https://privacypros.io/tools/bitcoin-fee-estimator/ , but electrum shows for next block about 50 sat per byte.

Estimates cannot be reliably used.

**Comment by SomberNight** [comment]
The ETA estimates come from bitcoind's `estimatesmartfee` (corresponding to the electrum server you are connected to).
The "next block" estimate is just 1.5x `estimatesmartfee(2)` (as bitcoind does not provide an estimate for the next block).
Note that you can use mempool-depth-based estimates too (just select it from the dropdown menu).

What exactly do you suggest?

**Comment by jbrepogmailcom** [comment]
Hm so there could be some problem with ```estimatesmartfee```. I checked several estimate web sites and the one that reflects reality best is https://privacypros.io/tools/bitcoin-fee-estimator/.
