### ISSUE TITLE
Load wallet from JSONRPC

### ISSUE THREAD

**Issue by bar-boss** [spesmilo/electrum#7803]
Hello.
My command:
`curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"load_wallet","params":{"wallet_path":"/home/address/wallet"}}' http://user:PASSWORD@127.0.0.1:7777`
Answer, it's OK.
`{"id": "curltext", "jsonrpc": "2.0", "result": true}`

My next command:
`curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"listaddresses","params":{"funded":true,"wallet_path":"/home/address/wallet"}}' http://user:PASSWORD==@127.0.0.1:7777`
Answer, not OK.
`{"id": "curltext", "jsonrpc": "2.0", "error": {"code": 1, "message": "wallet not loaded"}}`

Why previous command does not load my wallet '/home/address/wallet' ?

If this command:
electrum listaddresses -w /home/address/wallet

Answer gives me a list of addresses.

**Comment by SomberNight** [comment]
> My next command:
`curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"listaddresses","params":{"funded":true,"wallet_path":"/home/address/wallet"}}' http://user:PASSWORD==@127.0.0.1:7777`
Answer, not OK.
`{"id": "curltext", "jsonrpc": "2.0", "error": {"code": 1, "message": "wallet not loaded"}}`

Note that `load_wallet` has an arg named `wallet_path`, but most of the commands (`listaddresses` included) has an arg named `wallet`. Try with that.


https://github.com/spesmilo/electrum/blob/2e99ac9a94b45ac2b37e1ad5a4f2edb664534a25/electrum/commands.py#L233
https://github.com/spesmilo/electrum/blob/2e99ac9a94b45ac2b37e1ad5a4f2edb664534a25/electrum/commands.py#L814
