### ISSUE TITLE
MEU ENVIO DE BTC AINDA NÃO FOI CONFIRMADO 

### ISSUE THREAD

**Issue by nattynha** [spesmilo/electrum#7814]
FIZ UM ENVIO DE BTC A MAIS DE 24 HORAS E ELE AINDA NÃO FOI EFETIVADO
![Captura de tela 2022-05-14 133756](https://user-images.githubusercontent.com/105557912/168440777-b02627d7-c639-4dc2-bf26-4424e7e0a7ee.png)

**Comment by SomberNight** [comment]
The mempool is full. You need to either increase the fee or wait it out. See e.g. https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

**Comment by nattynha** [comment]
> O mempool está cheio. Você precisa aumentar a taxa ou esperar. Veja, por exemplo [, https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do](https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do)

Muito obrigada pela informação
