### ISSUE TITLE
Ghost windows from Electrum alerts on bspwm

### ISSUE THREAD

**Issue by hitchhooker** [spesmilo/electrum#7816]
Every time I send transaction electrum spawn empty ghost cell when tx confirmation message pops. its quite annoying to have these.

![image](https://user-images.githubusercontent.com/15621959/168660666-e201fcea-5832-4ae0-8985-ebaa0ce14d29.png)

**Comment by SomberNight** [comment]
There is nothing visible on your screenshot.
Is the red arrow supposed to be pointing at an "invisible window"? How do you know it is there?
