### ISSUE TITLE
restore wallet electrum error local rbf

### ISSUE THREAD

**Issue by la841** [spesmilo/electrum#7823]
I haved restored an electrum wallet in a new system, and although I get history transaction, a message  is shown saying trasaction is on local rbf. It asks me to broadcast transaction, however they are already in the blockchain.

Any help would  be much appreciated

**Comment by SomberNight** [comment]
Could you upload a screenshot with the History tab visible? You can redact bitcoin amounts if you want.

**Comment by la841** [comment]
> Could you upload a screenshot with the History tab visible? You can redact bitcoin amounts if you want.

![screen](https://user-images.githubusercontent.com/82597056/169656412-b9fcf4fa-9cd7-47f8-8c79-f670fc4ccfb1.png)

**Comment by SomberNight** [comment]
- what version of electrum?
- what is the colour of the orb/circle in the bottom right?
- click orb in the bottom right and upload a screenshot of the "Network" dialog

**Comment by la841** [comment]
> * what version of electrum?
> Version 4.2.1
>     * what is the colour of the orb/circle in the bottom right?
       blue
> 
>     * click orb in the bottom right and upload a screenshot of the "Network" dialog
It says connected to 1 server.

![screenshot](https://user-images.githubusercontent.com/82597056/169658721-4e6b21cd-4de9-4e27-ae79-8541c48f5979.png)

**Comment by SomberNight** [comment]
> click orb in the bottom right and upload a screenshot of the "Network" dialog

Please upload a screenshot of the Network dialog's "Overview" tab, with the full window visible.

For example:
![network-overview](https://user-images.githubusercontent.com/29142493/169659078-6aea97c5-944a-4d18-9eab-02d92dd1d6fa.png)

**Comment by la841** [comment]
> > click orb in the bottom right and upload a screenshot of the "Network" dialog
> 
> Please upload a screenshot of the Network dialog's "Overview" tab, with the full window visible.
> 
> For example: ![network-overview](https://user-images.githubusercontent.com/29142493/169659078-6aea97c5-944a-4d18-9eab-02d92dd1d6fa.png)
![1](https://user-images.githubusercontent.com/82597056/169660194-96da364f-3c53-4331-ba90-838b70d47e0a.png)
![2](https://user-images.githubusercontent.com/82597056/169660196-78b31424-2e5f-4e83-9bc3-cac4fe1b55f3.png)
![3](https://user-images.githubusercontent.com/82597056/169660197-f0ea28b1-3453-4664-a32a-c20e1be73e35.png)
I have hidden server (it is an onion address on 50002).  Connected node the same onion address

**Comment by SomberNight** [comment]
- Are you connected to your own server?
- And do you have --oneserver enabled?

These are things you should have said right at the start.
The issue likely stems from the single server you are connected to. Have you tried with another server?

> I haved restored an electrum wallet in a new system, and although I get history transaction, a message is shown saying trasaction is on local rbf. It asks me to broadcast transaction, however they are already in the blockchain.

How do you know the transactions are already in the blockchain?
- if you copy the txid of one of them from electrum, and search for it on a block explorer, does it say it's already mined there?
- if you run your own server, have you checked what your bitcoind says about that txid?

**Comment by la841** [comment]
Sorry, no 



> * Are you connected to your own server?
> Yes, sorry I didnt know it was relevant.
>     * And do you have --oneserver enabled?
What do you men excactly? Electrum says connected to the server and the circle is blue.
I have checked the address in serveral explorerr and the funds are there and also in other server. But as you says in this server I ask bitcoin-cli and it reports 0 funds.

> 
> 
> These are things you should have said right at the start. The issue likely stems from the single server you are connected to. Have you tried with another server?
> 
> > I haved restored an electrum wallet in a new system, and although I get history transaction, a message is shown saying trasaction is on local rbf. It asks me to broadcast transaction, however they are already in the blockchain.
> 
> How do you know the transactions are already in the blockchain?
> 
>     * if you copy the txid of one of them from electrum, and search for it on a block explorer, does it say it's already mined there?
> 
>     * if you run your own server, have you checked what your bitcoind says about that txid?

**Comment by SomberNight** [comment]
>> * Are you connected to your own server?
>
> Yes, sorry I didnt know it was relevant.
> [...]
> But as you says in this server I ask bitcoin-cli and it reports 0 funds.

What exactly are you testing?
I assume your bitcoind has txindex enabled.
Grab one of the txids of the local transactions from electrum, and run `getrawtransaction` in verbose mode for it, e.g.:

`$ bitcoin-cli getrawtransaction 0dff8a26dedc1d6379b34b9271cd518397580e675298f1532c2bd138b62d8d4c true`

In particular, if bitcoind finds the tx, look at the number of `confirmations`, to see whether your node thinks it's mined. e.g.:

`$ bitcoin-cli getrawtransaction 0dff8a26dedc1d6379b34b9271cd518397580e675298f1532c2bd138b62d8d4c true | jq .confirmations`

>> And do you have --oneserver enabled?
>
> What do you men excactly? Electrum says connected to the server and the circle is blue.

Your Electrum client is only connected to a single server. Why is that?
There is a config option called `oneserver` which can be used to achieve this. Have you enabled that? It is not exposed to the GUI.

-----

It would be much easier if you could test connecting to another server -- temporarily, just to test.
If you don't want to connect to a random server, e.g. `ecdsa.net:110` and `electrum.emzy.de:50002` are run by trusted community members / developers.

**Comment by la841** [comment]
> > > * Are you connected to your own server?
> > 
> > 
> > Yes, sorry I didnt know it was relevant.
> > [...]
> > But as you says in this server I ask bitcoin-cli and it reports 0 funds.
> 
> What exactly are you testing? I assume your bitcoind has txindex enabled. Grab one of the txids of the local transactions from electrum, and run `getrawtransaction` in verbose mode for it, e.g.:
> 
> `$ bitcoin-cli getrawtransaction 0dff8a26dedc1d6379b34b9271cd518397580e675298f1532c2bd138b62d8d4c true`
> 
> In particular, if bitcoind finds the tx, look at the number of `confirmations`, to see whether your node thinks it's mined. e.g.:
> 
> `$ bitcoin-cli getrawtransaction 0dff8a26dedc1d6379b34b9271cd518397580e675298f1532c2bd138b62d8d4c true | jq .confirmations`
> 
> > > And do you have --oneserver enabled?
> > 
> > 
> > What do you men excactly? Electrum says connected to the server and the circle is blue.
> 
> Your Electrum client is only connected to a single server. Why is that? There is a config option called `oneserver` which can be used to achieve this. Have you enabled that? It is not exposed to the GUI.
> 
> It would be much easier if you could test connecting to another server -- temporarily, just to test. If you don't want to connect to a random server, e.g. `ecdsa.net:110` and `electrum.emzy.de:50002` are run by trusted community members / developers.

I checked with bitcoin-cli getreceivedbyaddres but it says 0.0000 . But if  use bitcoin-cli getrawtransaction (with your example and mine) i get the datails about the transaction. I have already tried whit other server  and it works. So apparently the problem is this new server. Where can i find the config option you mention? the path i use to boot electrum stars by  "electrum --oneserver ...."

**Comment by SomberNight** [comment]
No point in quoting the previous comment in full.

> I checked with bitcoin-cli getreceivedbyaddres but it says 0.0000 

`getreceivedbyaddress` is a `wallet` RPC, it only works if the provided address is imported into bitcoind's wallet. That is not applicable to you.

> if use bitcoin-cli getrawtransaction (with your example and mine) i get the datails about the transaction

and does it say some positive number of confirmations for your transactions?

> I have already tried whit other server and it works

Ok. Good to know.

Please describe your setup (re your server).
- What bitcoind do you use? I assume it is Bitcoin Core. Which version?
- What kind of electrum server software do you use? Is it ElectrumX? What version?
- is there anything interesting in your server logs? what about the logs of the electrum client?

> the path i use to boot electrum stars by "electrum --oneserver ...."

Right, so that's why your client is only connected to a single server. Ok.
How come you did not know what I meant when I mentioned `--oneserver`, seeing that you use it?

**Comment by la841** [comment]
> No point in quoting the previous comment in full.
> 
> > I checked with bitcoin-cli getreceivedbyaddres but it says 0.0000
> 
> `getreceivedbyaddress` is a `wallet` RPC, it only works if the provided address is imported into bitcoind's wallet. That is not applicable to you.
> 
> > if use bitcoin-cli getrawtransaction (with your example and mine) i get the datails about the transaction
> 
> and does it say some positive number of confirmations for your transactions?
> 
> > I have already tried whit other server and it works
> 
> Ok. Good to know.
> 
> Please describe your setup (re your server).
> 
>     * What bitcoind do you use? I assume it is Bitcoin Core. Which version?
> 
>     * What kind of electrum server software do you use? Is it ElectrumX? What version?
> 
>     * is there anything interesting in your server logs? what about the [logs of the electrum client](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?
> 
> 
> > the path i use to boot electrum stars by "electrum --oneserver ...."
> 
> Right, so that's why your client is only connected to a single server. Ok. How come you did not know what I meant when I mentioned `--oneserver`, seeing that you use it?

It says some positive number of confirmations. I use Bitcoin Core 23.0 and electrum personal server 0.2.3. No idea about server logs.. when I installed the server I had to write the path oneserver...

**Comment by SomberNight** [comment]
> I use Bitcoin Core 23.0 and electrum personal server 0.2.3

Please check the logs of EPS.

**Comment by la841** [comment]
> > I use Bitcoin Core 23.0 and electrum personal server 0.2.3
> 
> Please check the logs of EPS.

Do you know where to find logs folder for EPS? I asked for the status of eps service and it says active and running. It shows a correct address but 0 txex.
Obtaining bitcoin addresses to monitor . . .
Obtained list of addresses to monitor in 3.729785680770874sec
Building history with 2000 addresses . . .
Found 0 txes. History built in 0.9886360168457031sec
Synchronizing mempool . . .
Found 5 mempool entries. Synchronized mempool in 156.64444875717163sec
Listening for Electrum Wallet on ('127.0.0.1', 50002)

**Comment by la841** [comment]
> > I use Bitcoin Core 23.0 and electrum personal server 0.2.3
> 
> Please check the logs of EPS.
I have found this thread that looks related to my issue. After rescanning I can see in Electrum wallet 1 address with funds, but not the rest.
The problem when rescanning is that it takes a wallet I created with Bitcoin Core GUI. That is not the one I want to rescan, 
When rescaning debug.log shows this:
[wallet Bitcoin Core GUI] Still rescanning. At block 684919. Progress=0.877497

**Comment by Etverbumcarofactum** [comment]
> I haved restored an electrum wallet in a new system, and although I get history transaction, a message  is shown saying trasaction is on local rbf. It asks me to broadcast transaction, however they are already in the blockchain.
> 
> Any help would  be much appreciated
