### ISSUE TITLE
Get a bitcoin address on MainNet

### ISSUE THREAD

**Issue by Arctrix** [spesmilo/electrum#7824]
Hello,

I have some bitcoin on Pionex exchange. I'd like to send it to my electrum wallet.
All the bitcoin addresses I own start with "bc1".
Pionex refuses to send to addresses starting with "bc", displaying that error : 
"Haven't supported the BTC lightning network. Please change to another address not beginning with bc."

I tried everything on my wallet, but I can't find how to generate a MainNet address, starting with something else than "bc".

Here is the information from my wallet :
Wallet type : standard
Script type : p2wpkh
Keystore type : bip32
Lightning : Enabled

Thanks for your help

**Comment by SomberNight** [comment]
"bc1.." addresses are mainnet bitcoin addresses. They have nothing to do with Lightning. These are native segwit addresses, introduced in 2017. Modern services and wallets should be able to send to them. You should complain to that exchange to implement support for "sending to bech32".

-----

See https://bitcoinelectrum.com/frequently-asked-questions/#why-am-i-being-told-my-address-is-an-invalid-bitcoin-address
> If the receive address you got from Electrum begins with “bc1” then you may find that some other wallets and exchanges have trouble sending money to it. These addresses use a new form of encoding called [bech32](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) which results in lower transaction fees when spending bitcoin but support for sending coins to them is not yet universal.
>
> The solution to this problem is to run electrum with the --nosegwit command line switch and [create a new Electrum wallet](https://bitcoinelectrum.com/creating-an-electrum-wallet/).
>
> Once you’ve created a new wallet you can receive coins to it instead. You can also switch between wallets via file > open or file > recently open.

and https://en.bitcoin.it/wiki/Bech32_adoption

**Comment by Arctrix** [comment]
Thanks for your answer. I'll look into it, maybe I'll have to open a new wallet with CLI.
