### ISSUE TITLE
Electrum-TrustedCoin -- ErrorConnectingServer (Timeout Error())

### ISSUE THREAD

**Issue by Emivg** [spesmilo/electrum#7826]
Hello,

Today I reset my disk and I decided to reinstall and restore my Electrum wallet from the seed (2fa wallet)

Everything was going ok until the terms and conditions page of TrustedCoin (the 2fa method). Nothing appeared, I was not able to press "Accept" and after a few seconds I received this error message:
https://i.imgur.com/5rWvuRW.png (its in spanish, it basically says that terms of service could be loaded)

I have another question, I remember to add three words of extension to my seed, but electrum didn't ask for them. Was I supposed to add them into any field?

ps: I tried reinstalling electrum and my pc (I have good connection and TrustedCoin website seems to be OK)

Thank you

**Comment by SomberNight** [comment]
> I have another question, I remember to add three words of extension to my seed, but electrum didn't ask for them. Was I supposed to add them into any field?

When you enter your seed words, on the same screen, click the "Options" button.
There is a checkbox there: "Extend this seed with custom words".

> Everything was going ok until the terms and conditions page of TrustedCoin (the 2fa method). Nothing appeared, I was not able to press "Accept" and after a few seconds I received this error message:
https://i.imgur.com/5rWvuRW.png (its in spanish, it basically says that terms of service could be loaded)

I've just tested and it works for me now. It could be that your IP is banned for some reason. :/

First of all, note that when you are asked "Do you want to keep using two-factor authentication with this wallet", you can select "Disable" to disable the 2FA, in which case you can spend your coins unilaterally - they are not locked in.

However, I assume you would like to keep using 2FA, in which case, maybe try using a proxy.

The easiest way to do so, is by using the [Tor Browser](https://www.torproject.org/download/). Just download and start the Tor Browser, and have it run in the background.
You can configure Electrum to use the local Tor proxy (created by the Tor Browser) in the Network dialog of Electrum (proxy tab):
on the system tray (task bar), right-click the Electrum icon, and choose `Network`:
![asd2](https://user-images.githubusercontent.com/29142493/169705669-1b9ac14b-1ddb-46d1-88e4-431d2103f6da.png)

**Comment by SomberNight** [comment]
Did the proxy suggestion work?

**Comment by Emivg** [comment]
> Did the proxy suggestion work?

Yeah, it worked. Thank you!
