### ISSUE TITLE
Closing Electrum always leads to "EXC_CORPSE_NOTIFY" (Crash report) on M1 MacBook

### ISSUE THREAD

**Issue by xdemiansmithx** [spesmilo/electrum#7827]
Hi,
whenever I close electrum 4.2.1 on my MacBook, I get the "This application crashed" error message, if a hardwarewallet is connected.

macOS Monterey 12.4 (21F79) on a MacBook Air (M1, 2020). It crashes on  "Crashed Thread:        0  Dispatch queue: com.apple.main-thread"

Should i be concerned?

**Comment by SomberNight** [comment]
duplicate of https://github.com/spesmilo/electrum/issues/7738
