### ISSUE TITLE
Version mismatch for trezor library (0.13.0 vs 0.13)

### ISSUE THREAD

**Issue by fturco** [spesmilo/electrum#7832]
I'm running electrum 4.1.5 on a Void Linux system.
I installed the trezor-0.13.0 package with pip.

Electrum doesn't recognize my Trezor hardware wallet due to the following error message:

```
W | gui.qt.installwizard.InstallWizard | error getting device infos for trezor: Library version for 'trezor' is incompatible. // Installed: 0.13.0, Needed: 0.12.0 <= x < 0.13 // Make sure you install it with python3
```

Basically there's a mismatch between version 0.13.0 and 0.13.

**Comment by SomberNight** [comment]
So, to be clear, it is not about the extra 0, but the nature of strict vs non-strict comparison.
```
>>> (0, 13, 0) < (0, 13)
False
>>> (0, 13) < (0, 13)
False
```
There is no bug here.
