### ISSUE TITLE
Wizard: cannot restore from standard seed when creating 2FA wallet

### ISSUE THREAD

**Issue by umquat** [spesmilo/electrum#7837]
The GUI desktop app and the Android app do not restore from a particular seed. The CLI works fine

I checked using the CLI and I was able to create an offline wallet using this seed, I fired up the GUI and it updated the history and everything seems ok.

For comparison I tried restoring from another seed I found In [a comment](https://github.com/spesmilo/electrum/issues/7082#issuecomment-790855708) in bug #7082 with no success.

OTOH If I generate a seed on the Android app, write that down and use that seed to restore it does work. Kind of the same behavior in the desktop GUI.

So it seems to me that my seed is not recognized in this particular version.

What can I do to help debug this issue?

Thanks for your help!

**Comment by SomberNight** [comment]
> For comparison I tried restoring from another seed I found In https://github.com/spesmilo/electrum/issues/7082#issuecomment-790855708 in bug https://github.com/spesmilo/electrum/issues/7082 with no success.

What do you mean "no success"? Were you not able to restore a wallet using that seed (`powerful random nobody notice nothing important anyway look away hidden message over`)? Or does it not have the expected addresses?

> The GUI desktop app and the Android app do not restore from a particular seed

Let's consider the Qt GUI for simplicity. What *exactly* do you mean by "do not restore"? When you type your seed in the wizard, is the `Next` button disabled?

> I checked using the CLI and I was able to create an offline wallet using this seed

How did you restore from your seed via CLI? Just for sanity's sake, I would like to see the exact command with sensitive arguments redacted, if possible.

> So it seems to me that my seed is not recognized in this particular version.

When did you generate the seed in question, using what version of Electrum, approximately?

**Comment by umquat** [comment]
El lun, 30-05-2022 a las 13:01 -0700, ghost43 escribió:
> > For comparison I tried restoring from another seed I found In #7082
> > (comment) in bug #7082 with no success.
> What do you mean "no success"? Were you not able to restore a wallet
> using that seed (powerful random nobody notice nothing important
> anyway look away hidden message over)? Or does it not have the
> expected addresses?
The Android app keeps the "Next" button greyed out

The QT Gui recognizes the seed as "old" but the next button is greyed
out

> 


> > The GUI desktop app and the Android app do not restore from a
> > particular seed
> Let's consider the Qt GUI for simplicity. What exactly do you mean by
> "do not restore"? When you type your seed in the wizard, is the Next
> button disabled?
The Qt GUI recognizes the seed as standard, but the next button is
greyed out.

> > I checked using the CLI and I was able to create an offline wallet
> > using this seed
> How did you restore from your seed via CLI? Just for sanity's sake, I
> would like to see the exact command with sensitive arguments
> redacted, if possible.

> > So it seems to me that my seed is not recognized in this particular
> > version.
> When did you generate the seed in question, using what version of
> Electrum, approximately?
Maybe somewhere around May, 2019 but I'm not sure on that.

I forgot to add that I'm running on Linux using the AppImage binary.

Best,
Rubén

**Comment by SomberNight** [comment]
> The Android app keeps the "Next" button greyed out

What version of Electrum?

> The QT Gui recognizes the seed as "old" but the next button is greyed out
> I forgot to add that I'm running on Linux using the AppImage binary.

What version of Electrum?
Sounds weird... if the seed is recognized as "old", the next button should not be greyed out.

>>  When did you generate the seed in question, using what version of
>>  Electrum, approximately?
>
> Maybe somewhere around May, 2019 but I'm not sure on that.

`old`-type seeds are seeds that versions prior to Electrum 2.0 generated, which was released mid-2015. Although I guess if you used a package from a distro's package manager, that could have been years outdated.

> There were some attached images to this email. Bummer :-(

Images don't work with email replies I guess. An image of the Qt GUI showing "seed type" `old`, and the "Next" button greyed out, would be appreciated. (only if you are confident you can redact the seed words, do not share those with anyone)

**Comment by umquat** [comment]
![Imagen-5LZ0M1](https://user-images.githubusercontent.com/64426978/171664221-db0015bb-3e57-4959-8b4d-55f0d93c9c3d.png)
![Imagen-R8Z9M1](https://user-images.githubusercontent.com/64426978/171664243-520195b5-d757-4efc-82cd-020e43eab3bf.png)
![Imagen-VYXBN1](https://user-images.githubusercontent.com/64426978/171664256-03c2738b-57fb-4056-b33f-0b1dfa2b76d9.png)

**Comment by umquat** [comment]
Thanks a bunch!

If I may make a suggestion, Maybe start asking 1) Do you have a seed to restore or you prefer to create from scratch? -> If the user has a seed, then instruct to type it, analyze it and inform the user what the outcome will be. (Unrecognized, 2fa, standard etc)

If you think about it when a seed is present there is only two possible outcomes. Unrecognized / invalid or valid for a single type of wallet, no choosing is necessary (unless it is, but maybe do the choosing after detecting it?)

IMHO please don't pile on me since I'm just saying this from the user's perspective, maybe the nuance and particulars make this happy path impractical, I wouldn't know :-)

Thanks again :-)

**Comment by SomberNight** [comment]
Note: if you select "Standard wallet">"I already have a seed", all types of electrum-seeds are accepted, including 2FA seeds.
However, if you select "Wallet with two-factor authentication">"I already have a seed", only 2FA seeds are accepted.

The current architecture is such that you can transform a generic "wizard" to a 2fa-specific wizard, but not the other way around (instead, you would have to close the wizard, and open a new one).

Anyway, I don't want to spend time on redesigning/refactoring this part of the code now, so instead I have added a small warning text in https://github.com/spesmilo/electrum/commit/450476dcb60f02935ec6960021d12c843dbf73dd.

![pic5](https://user-images.githubusercontent.com/29142493/171912662-b1b42c07-8d0e-4fed-a0d2-763c1b3a9fc7.png)
