### ISSUE TITLE
Watch-only wallet and JSON-RPC

### ISSUE THREAD

**Issue by odiferousmint** [spesmilo/electrum#7841]
Hello. Why am I unable to, say, get the balance of a watch-only wallet ONLY through JSON-RPC? It tells me that the wallet is not loaded.

```php
<?php

require 'vendor/autoload.php';

$client = new \Electrum\Client('http://127.0.0.1', 7777, 0, 'foo', 'foobar');

$load_wallet = new \Electrum\Request\Method\Wallet\LoadWallet($client);
$load_wallet->execute(['wallet_path' => '~/.electrum/wallets/watch']);

$list_wallets = new \Electrum\Request\Method\Wallet\ListWallets($client);
$list_wallets->execute();

$balance = new \Electrum\Request\Method\Wallet\GetBalance($client);
$balance->execute();

?>
```

Output:

```
array(3) {
  ["id"]=>
  int(0)
  ["jsonrpc"]=>
  string(3) "2.0"
  ["result"]=>
  bool(true)
}
array(3) {
  ["id"]=>
  int(1)
  ["jsonrpc"]=>
  string(3) "2.0"
  ["result"]=>
  array(1) {
    [0]=>
    array(2) {
      ["path"]=>
      string(37) "/home/odiferousmint/.electrum/wallets/watch"
      ["synchronized"]=>
      bool(true)
    }
  }
}
array(3) {
  ["id"]=>
  int(2)
  ["jsonrpc"]=>
  string(3) "2.0"
  ["error"]=>
  array(2) {
    ["code"]=>
    int(1)
    ["message"]=>
    string(17) "wallet not loaded"
  }
}
```

Any ideas? I ran the daemon, and then I did (the reason I specified the path to the wallet was that otherwise it gave me `false`[1]):

```
$ electrum load_wallet -w ~/.electrum/wallets/watch
```

It was successful, but `$ electrum getbalance` still says that the wallet file was not found. That said:

```
$ electrum getbalance -w ~/.electrum/wallets/watch
```

does work and return:

```
{
    "confirmed": "0"
}
```

So I am not sure why it does not work with PHP. Any ideas? I tried both https://github.com/matasarei/JsonRPC.git and https://github.com/oasin/php-electrum-api.git and they both return the same error, which is that the wallet is not loaded. It works if there is a wallet that is not watch-only.

---

It might be the wrong place to submit this issue, in which case I will submit it to either (or both) of these other projects, but I figured you (or someone reading this) may know the reason.

---

[1] 
![2022-06-02-125422_840x400_scrot](https://user-images.githubusercontent.com/43568459/171614573-dff2c7c9-4ac3-49be-8d49-46c4c644de06.png)

---

So... it seems like that watch-only wallets do not seem to work with the daemon / JSON-RPC for some reason, unless you specify the path to it with `-w`, but that is not going to work with JSON-RPC clients unfortunately.

**Comment by SomberNight** [comment]
You need to specify the wallet for every command that operates on a wallet.

via CLI you might do:
`./run_electrum -v --testnet load_wallet -w ~/.electrum/testnet/wallets/test_segwit_2`

and via RPC:
`curl --data-binary '{"id":"curltext","method":"load_wallet","params":{"wallet_path":"/home/user/.electrum/testnet/wallets/test_segwit_2", "password":"1234"}}' http://user:yMx9TyMCCVenQaBBfjn5TQ==@127.0.0.1:7777`

**Comment by SomberNight** [comment]
Note that most commands have a `wallet` parameter, but some have `wallet_path` instead; it's not entirely consistent.

https://github.com/spesmilo/electrum/blob/b7b53e56bc9bfab5eefb49bd1f0404555a57bb47/electrum/commands.py#L233
https://github.com/spesmilo/electrum/blob/b7b53e56bc9bfab5eefb49bd1f0404555a57bb47/electrum/commands.py#L519

**Comment by odiferousmint** [comment]
Okay, it does work apparently!

```
array(3) {
  ["id"]=>
  int(0)
  ["jsonrpc"]=>
  string(3) "2.0"
  ["result"]=>
  bool(true)
}
array(3) {
  ["id"]=>
  int(1)
  ["jsonrpc"]=>
  string(3) "2.0"
  ["result"]=>
  array(1) {
    [0]=>
    array(2) {
      ["path"]=>
      string(37) "/home/odiferousmint/.electrum/wallets/watch"
      ["synchronized"]=>
      bool(false)
    }
  }
}
array(3) {
  ["id"]=>
  int(2)
  ["jsonrpc"]=>
  string(3) "2.0"
  ["result"]=>
  array(1) {
    ["confirmed"]=>
    string(1) "0"
  }
}
```

I consider it solved. The issue indeed was using `wallet_path` instead of `wallet` for `getbalance`. Thank you!
