### ISSUE TITLE
how to run from source (git clone) on Windows 10

### ISSUE THREAD

**Issue by hui09-m** [spesmilo/electrum#7849]
If you want to run this project on windows10, do you need to download python in the virtual machine, or can you directly operate it on windows10? Mainly because I see that your instructions are all under the linux system

**Comment by SomberNight** [comment]
It is perfectly possible to run from source on Windows. I run from source on all of: desktop Linux, Windows, and macOS.
The easiest platform to do development on is Linux however.

Re Windows, the main pain point is compiling `libsecp256k1`.

Anyway, I've added a [guide for Windows](https://github.com/spesmilo/electrum/blob/master/contrib/build-wine/README_windows.md) now in https://github.com/spesmilo/electrum/commit/941db4214c74d51c193c942e9e7ff633a5ff3a36. Please see that.

Related: https://github.com/spesmilo/electrum/issues/5976
