### ISSUE TITLE
[regression] In Qt Addresses tab, "beyond gap limit" addresses are not coloured red

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7851]
This is a regression from https://github.com/spesmilo/electrum/commit/e362d1aac4c326917592bcfe1f5d679f7649366a.

"beyond gap limit" addresses are supposed to be coloured red here:
https://github.com/spesmilo/electrum/blob/2841cbeade52550e52be40009c97d270ba44469a/electrum/gui/qt/address_list.py#L201-L202
but this colouring is lost as it is overridden a few lines below here:
https://github.com/spesmilo/electrum/blob/2841cbeade52550e52be40009c97d270ba44469a/electrum/gui/qt/address_list.py#L206

Note we are using `wallet.get_all_known_addresses_beyond_gap_limit()`,
https://github.com/spesmilo/electrum/blob/2841cbeade52550e52be40009c97d270ba44469a/electrum/gui/qt/address_list.py#L166
and instead we would now need per-address lookups -- it would be prohibitively expensive to call the current method for every address.

**Comment by SomberNight** [comment]
note: before `wallet.get_all_known_addresses_beyond_gap_limit()`, the code was using `wallet.is_beyond_limit(address)`. The change was specifically done to improve performance, in https://github.com/spesmilo/electrum/commit/1ca6f6f306a1f9f376c7519b9b80662aa39768ee. I believe it's mostly interesting for large gap limits. Unfortunately whoever made that commit was likely too lazy to include benchmarks re how useful the change was... 

Regardless, instead of going back to that, the wallet could keep internal state about which addresses are beyond the gap limit (e.g. have a private set of such addresses), and expose simple lookup functions. However this would likely conflict with the heavy refactoring of `AddressSynchronizer` in the [`persist_lnwatcher`](https://github.com/spesmilo/electrum/tree/persist_lnwatcher) branch, so will wait for that to get merged first.

**Comment by SomberNight** [comment]
Here is a more comprehensive history of the performance of `is_beyond_limit`.
We used to have a function, that essentially worked like this:
```python
def is_beyond_limit(self, address):
    is_change, i = self.get_address_index(address)
    limit = self.gap_limit_for_change if is_change else self.gap_limit
    if i < limit:
        return False
    addrs =  self.get_change_addresses() if is_change else self.get_receiving_addresses()
    prev_addresses = addrs[max(0, i-limit): max(0, i)]
    for addr in prev_addresses:
        if self.db.get_addr_history(addr):
            return False
    return True
```
This was fast in practice due to breaking the loop - i.e. for most addresses, only 1-2 iterations were needed until breaking out.

- after jsondb/walletdb was split from wallet, `get_receiving_addresses()` started to make a copy of all the addresses.
    - see https://github.com/spesmilo/electrum/commit/56ced1dfd5e3f402aba9270b721ebf6db04b05b7
    - bad performance for any "large_wallet"
- then we added slicing support to `get_receiving_addresses()` so that it would only copy `len(prev_addresses)`-sized chunk.
    - see https://github.com/spesmilo/electrum/commit/c6a54f05f5ba431e069cba0eef14a2df1e596c14
    - bad performance for "large_wallet with large_gap_limit"
- then we changed to a single `get_all_known_addresses_beyond_gap_limit()` computation instead of many `is_beyond_limit()` calls.
    - https://github.com/spesmilo/electrum/commit/1ca6f6f306a1f9f376c7519b9b80662aa39768ee

-----

Now, regarding what to do, we could tradeoff some space for time, to have a fast `is_beyond_limit(address)`...
Options:

1. revert back to naive `is_beyond_limit(address)` that has bad performance for large gap limits

2. sorted set
    - The wallet could e.g. maintain a sorted set that contains used address indices.
    - It could then expose a `wallet.is_beyond_limit(address)` function, which would call `get_address_index` and then bisect the sorted set to find the largest index to the left of the insertion point.
    - Unfortunately there is no sorted set/list, tree map, etc in the python stdlib :(
    - There is a nice pure python package we could use though: https://github.com/grantjenks/python-sortedcontainers
        - Obviously, at first glance it seems overkill to add a new dependency just for this...
        - As far as dependencies go, it's quite nice actually. Mature, well-documented code, ~small, no transitive deps, pure python. It should be part of the stdlib!

3. elaborate caching
    - have a naive `is_beyond_limit(address)`, but cache results
    - need to invalidate the whole cache if gap limit changes
    - need to invalidate cache if address history changes
        - for all addresses "within" gap limit of change
    - note that during e.g. initial history sync, the cache invalidation itself might have significant cpu costs...

**Comment by ecdsa** [comment]
What do you mean by "large gap limits", how large is that?  Also, does the issue arise if the gap limit is unchanged from its default value, but the user created a large number of addresses beyond the gap limit?

The option of changing the gap limit was available in very early versions of Electrum, then I removed it because it creates more harm than good. The recommended way of obtaining more addresses is not to increase the gap limit, but to create addresses beyond it, which are shown in red. I really do not want to introduce a new dependency just because some users decide to ignore that...

**Comment by ecdsa** [comment]
Having a closer look at the issue, I think it does not have to be that complicated.
We can store `addresses_beyond_gap_limit` in `update`, and use it in `refresh_row`.
Wallet event that affect addresses beyond gap limit will be calling `wallet.update_tabs`, and that will recompute that set.
