### ISSUE TITLE
test_pyaes_is_available & test_pycryptodomex_is_available

### ISSUE THREAD

**Issue by hui09-m** [spesmilo/electrum#7853]
When I run the command “pytest electrum/tests/test_bitcoin.py -v”，it shows like this:
![image](https://user-images.githubusercontent.com/83063300/173189661-ef13b96c-e455-45aa-906e-fa1b0cb7fdef.png)
I don't know how to solve them.
And when I run the command “./run_electrum”, nothing comes out, is this corect?

**Comment by ecdsa** [comment]
use `python3 -m unittest electrum/tests/test_bitcoin.py`
