### ISSUE TITLE
Feature request: Password protected hardware wallets

### ISSUE THREAD

**Issue by eugenesan** [spesmilo/electrum#7856]
Currently there is only an option to encrypt hardware wallet using hardware device.
It would be extremely useful to be able to create a password protected hardware wallets.
The use case is to be able to monitor the wallet and require hardware device only for creating transactions.

**Comment by ecdsa** [comment]
this is a duplicate of an existing issue, see #5561 
please do a minimum of research before posting

**Comment by eugenesan** [comment]
@ecdsa 
My bad.
I failed to find it.
Thanks.
