### ISSUE TITLE
Electrum Daemon returns crazy high fees sometimes

### ISSUE THREAD

**Issue by kanuku** [spesmilo/electrum#7860]
I am currently using the electrum daemon to estimates fees. 
Sometimes it happens that the fees on testnet get way too high, for example:
```
{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "getfeerate",
    "params": [
        "eta",
        "0.75"
    ]
}
```

This is the result:
```
{
    "id": "1",
    "jsonrpc": "2.0",
    "result": 526232
}
```
on a previous calls the values were around
```
{
    "id": "1",
    "jsonrpc": "2.0",
    "result": 3077
}
```

Is this a bug and can it be avoided? If yes, how?

**Comment by ecdsa** [comment]
block mining on testnet is irregular. not an electrum issue.
