### ISSUE TITLE
Can't recieve the money

### ISSUE THREAD

**Issue by hui09-m** [spesmilo/electrum#7863]
I use https://kuttler.eu/en/bitcoin/btc/faucet/ to test electrum. However it success in the website, electrum system does'nt get the money. Why?
![image](https://user-images.githubusercontent.com/83063300/174576196-cdd98a19-abd7-41b1-b2fa-2c2bc971621e.png)
![image](https://user-images.githubusercontent.com/83063300/174576343-8cb13390-8aa2-493d-bdb2-8f6aceb4f7b8.png)
![image](https://user-images.githubusercontent.com/83063300/174576382-9163a155-9c2a-4e97-849f-6cd993216651.png)
![image](https://user-images.githubusercontent.com/83063300/174576427-b2d6ce5d-1630-40d5-a56c-81c348e7e4c6.png)

**Comment by ecdsa** [comment]
the faucet works with testnet addresses, not mainnet.

**Comment by hui09-m** [comment]
I just want to test it ,how to do? Can it be testnet?

**Comment by henrysmit420** [comment]
Mine bitcoin for free here https://www.btcs.love/invite/4nc58
