### ISSUE TITLE
Signing Key Electrum 4.2.2

### ISSUE THREAD

**Issue by nbourbon** [spesmilo/electrum#7872]
I downloaded version 4.2.2 but the signature came from Stephan Oeste 637D B1E2 F84A CCE0 3152 347D 07DA 627C and in the web page it doesn't mention Stephan as a signer nor I had it in my trusted signatures before.

Can you confirm if this is ok?
Thanks

**Comment by SomberNight** [comment]
What program are you using the check the signature?
The sig files have multiple (three atm) signatures, as the binaries are signed by multiple people and they can one sig corresponding to each people.

Decent GPG tools, such as `gpg --verify` on the CLI, should list and verify each signature; but it seems some tools might only look at the first signature in the sig file, see https://github.com/spesmilo/electrum/issues/7810

> the web page it doesn't mention Stephan as a signer 

His nick is `emzy` and is listed near the top of the download page:
https://github.com/spesmilo/electrum-web/blob/6333decec706b88ac8db412416fa2c924c2e5402/panel-download.html#L7-L8

**Comment by SomberNight** [comment]
note: there are also split gpg sig files on the download server here: https://download.electrum.org/4.2.2/

**Comment by nbourbon** [comment]
Thanks you can close this ticket now. I found rest of the signatures and Thomas, yours and Stephan. I added them to my Ultimate Trust list now. Thanks!

**Comment by SomberNight** [comment]
Ok, great.
Could you please say what program you are using to verify the signatures?
