### ISSUE TITLE
It's saying can't connect to server 

### ISSUE THREAD

**Issue by mekzcyb** [spesmilo/electrum#7875]
![image](https://user-images.githubusercontent.com/108562240/176985701-9a8028e5-c5bf-4342-8fb5-03e793d1610e.JPG)
 I can't connect to my Server on electrum portable version, it's telling me can't connect to server, i need help please

**Comment by SomberNight** [comment]
This looks like malware. Where did you do download it from? Copy the exact URL from your browser history.

**Comment by ecdsa** [comment]
indeed, the error popup is not from Electrum.
closing
