### ISSUE TITLE
[Feature Request] Unique Lightning node ID for each private channel opened

### ISSUE THREAD

**Issue by PoisonFrog** [spesmilo/electrum#7878]
Not sure if this is the right place for this, but can an option to treat each lightning channel as if it belonged to a separate node be implemented? I think this would be great for privacy. The actual behavior is definitely the better default, but an option to create a new node ID for each new channel opened would be great.

**Comment by ecdsa** [comment]
how would you get paid? 
you would need to show a different invoice for each of your channels...

**Comment by PoisonFrog** [comment]
> how would you get paid? you would need to show a different invoice for each of your channels...

Yeah, this would be for people that want to use lightning to spend and don't care that much about receiving funds. The way lightning works spending funds is way more private than receiving funds. This would be an optional feature to enhance the privacy of those that are going to use the Electrum lightning implementantion to spend sats mostly.

**Comment by ecdsa** [comment]
yeah, well, I guess you did not think it through.
this is the kind of feature that creates complexity for nearly zero benefit. sorry.
