### ISSUE TITLE
Importing a BitGo/Nuri wallet in electrum shows zero balance and different addresses

### ISSUE THREAD

**Issue by aspacca** [spesmilo/electrum#7879]
Hello,

I'm trying to import a BitGo/Nuri wallet in electrum.

From what I got on the following links everything seems done properly:
https://api.bitgo.com/docs/#address-derivation-bip-32
https://github.com/spesmilo/electrum/issues/4352#issuecomment-387730064

But once the wallet is created it shows zero balance and the addresses are different from the one available on the Nuri app.

These are the step I've gone through:
1. Create a 2of3 multi-signature wallet
2. Import the existing xpub key
3. Import the first existing BIP39 seed
4. Set the derivation path for (3) as m/0/0/10/0
5. Import the second existing BIP39 seed
6. Set the derivation path for (5) as m/0/0/10/0

Notes:
- In the Nuri app only a single bc1 format address is shown as default. You can generate a legacy address in the 3x format. Still there's no match from what I got from electrum

**Comment by ecdsa** [comment]
please, do not ask us to check other wallets derivations; we do not have time to do support for other wallets.
Create an electrum seed, and send your funds to it.

**Comment by aspacca** [comment]
@ecdsa , please, don't take me wrong: setting a custom derivations, as well importing from other wallets with BIP39 are features present in electrum, and I supposed that they were supported.

If your answer has to be read as: "there might something wrong in the Nuri derivation, and we don't support finding the correct one", all clear.

It's then up to me to be sure and proof that the derivation is correct, but if it's so: the facts that the balance is zero and the addressess are different once the wallet is imported, would they be considered a bug/issue on electrum or not?

thanks :)

**Comment by SomberNight** [comment]
Both the derivation path and the script type needs to match.
If both match then you should see the same addresses in Electrum, otherwise there is a bug.
By "script type" I mean something like what is shown as "Address Type" in the BitGo doc you linked (although script type is more generic).

You said BitGo/Nuri gives you bc1 addresses - do you also see bc1 addresses in the wallet in Electrum?

**Comment by aspacca** [comment]
thanks for the clarification @SomberNight 

 >You said BitGo/Nuri gives you bc1 addresses - do you also see bc1 addresses in the wallet in Electrum?

it depends on how I try to import the wallet in electrum: if I start from the seeds I can define the "Address Type" in the BitGo doc and have bc1 addresses. for that I have to convert the xpub to Zpub, I'm not sure how much reliable this conversion is indeed

to exclude the xpub/Zpub conversion variable I've generated a P2SH address in Nuri, and tried the import again with
`m/0/0/0` as derivation path of the seeds and using the original xpub key: still there is no matching address between the ones generated my electrum and the balance is zero.

in order to understand if this is a bug in electrum or rather an error in the derivation path I'd need to understand if the `n` in `m/0/0/n` must match the sequence of the adresses I've generated on Nuri or using `0` for `n` will be good enough

I will look into that
