### ISSUE TITLE
No option to choose script type and derivation path when creating keystore from master key

### ISSUE THREAD

**Issue by eugenesan** [spesmilo/electrum#7880]
I am trying to create a watch only wallet from public key.

With xpub import, it defaults to p2pkh with m/0 derivation path and shows incorrect for BIP84 addresses.
With zpub import, it defaults to p2wpkh with m/0 derivation path but somehow shows addresses for m/84'/0'/0'.

While, it works with zpub+BIP84 combination, it make it impossible to import xpub+BIP84.

Now, when zpub is being phased out due incompatibility with taproot, it seems like xpub is becoming the default again and we need an option to import xpub+BIP84.

**Comment by ecdsa** [comment]
the z in zpub means segwit.
we will probably use a different system with taproot.
