### ISSUE TITLE
Bad derivation path v4.1

### ISSUE THREAD

**Issue by mrx23dot** [spesmilo/electrum#7881]
So I generated a default seed, electrum/segwit kind:
`pilot aerobic kitchen armor gallery tell congress tower dove table please saddle`

Under Addresses tab the first receiving address says it has a derivation path of: **m/0/0** and address of 
`bc1q59vf7wl76f2y5c32jnnkrpnfzpevq7a6zl9llx`

When I run this with an external lib I get:
`bc1q6t3jrdwsengd5dv3k5dx877y8lazpr7vkmdp4k`

So who's lying? Is it true that there is no hardening in deriv.path?

They agree when I import bip44 into electrum, but that's not the default.

electrum v4.1.5

**Comment by SomberNight** [comment]
No one is lying, you are simply confused.
Given a seedphrase/mnemonic, there are many steps until an address is created.
At least there are these, simplified:
1. seedphrase -> bip32_rootseed
2. bip32_rootseed -> bip32_root_xprv
3. bip32_root_xprv + derivation path + script_type -> address

In particular you made a mistake in step 1.

> When I run this with an external lib I get:
bc1q6t3jrdwsengd5dv3k5dx877y8lazpr7vkmdp4k

You get this address at `m/0/0` when you force-interpret the given seedphrase as a BIP39 seedphrase.
That is, in step1, you do the conversion as if it was BIP39.
Spec and code for that is here:
https://github.com/bitcoin/bips/blob/df443f8db30862b4776b4c06c47b62ded0790dc5/bip-0039.mediawiki#from-mnemonic-to-seed
https://github.com/spesmilo/electrum/blob/c463f5e23daff71f05486f53ab04510d538dbec7/electrum/keystore.py#L896-L902

But that seedphrase is an electrum seed, so it should be interpreted as such.
Code for that is here:
https://github.com/spesmilo/electrum/blob/c463f5e23daff71f05486f53ab04510d538dbec7/electrum/mnemonic.py#L159-L164

**Comment by SomberNight** [comment]
> bip39? (which was later replaced by bip44)

bip39 was not replaced by bip44. they are orthogonal (and most often used together)

> Why electrum defaults to a custom algo instead of the standard bip39?

see https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-August/013061.html
