### ISSUE TITLE
Невозможно вывести средства,нет кнопки с подписью

### ISSUE THREAD

**Issue by Svetlaja88** [spesmilo/electrum#7888]
Здравствуйте,создал кошелек для просмотра,и введя в него открытый ключ от блокчайна,и по ошибке завел средства на данный кошелек,кнопки подписи нет,можно каким нибудь образом вывести средства?

**Comment by SomberNight** [comment]
If you don't have private keys from an address, then you can't spend from it.
A watching-only wallet cannot spend coins.

**Comment by Svetlaja88** [comment]
Подскажите,что делать?

**Comment by Svetlaja88** [comment]
Почему два заимодействущих кошелька,1 из них для просмотра, суммы разные?
