### ISSUE TITLE
AddressSynchronizer.add_transaction() got an unexpected keyword argument 'notify'

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#7895]
Seems that `notify` parameter was changed to `notify_GUI`, but one place in `lnwatcher.py` wasn't updated: https://github.com/spesmilo/electrum/blob/master/electrum/lnwatcher.py#L532

This causes errors like these:
```
lnwatcher.LNWalletWatcher.[wallet-name-LNW] | could not add future tx: our_ctx_to_local ...... AddressSynchronizer.add_transaction() got an unexpected keyword argument 'notify'
```

**Comment by ecdsa** [comment]
thanks
