### ISSUE TITLE
LN channels are force-closed sporadically

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#7906]
LN channels sometimes are force-closed automatically, right after wallet startup. The log contains the following message:

```
force-closing due to expiring htlcs
```

The channel in question was opened a couple days ago, and only had a single outgoing payment sent through it, which completed successfully. The details of the channel list only one HTLC, in the "Fulfilled HTLC" category.

Expiry time for the HTLC (746650) is indeed below the current block head. But why do we need to close the channel in this case? It was my understanding that negotiating for new HTLCs invalidates the old HTLCs, so even if some fulfilled HTLC approaches expiry then it shouldn't matter.

**Comment by ecdsa** [comment]
can you post the transaction ID of the closing tx? do you remember which node you opened the channel with?

**Comment by Rogach** [comment]
> how many times did that happen?

Several times, each from a different wallet.

> can you post the transaction ID of the closing tx?

Unfortunately I would prefer not to, due to confidentiality reasons.

> do you remember which node(s) you opened the channel with?

That was Nicehash node, ID 037659a0ac8eb3b8d0a720114efc861d3a940382dcfa1403746b4f8f6b2e8810ba. They had some trouble with their node recently, so maybe this bug is a fluke - however the issue was happening even on channels opened even after their node started working normally.


I tried debugging the issue myself, and it seems that for some reason LOCAL and REMOTE ctn's do not match. Here's the HTLCManager log state for the channel:

```
{
  <HTLCOwner.LOCAL: 1>: {
    'adds': {
      0: UpdateAddHtlc(amount_msat=8000000000, timestamp=1658830798, htlc_id=0)
    },
    'locked_in': {
      0: {
        <HTLCOwner.LOCAL: 1>: 1,
        <HTLCOwner.REMOTE: -1>: 2
      }
    },
    'settles': {
      0: {
        <HTLCOwner.LOCAL: 1>: 2,
        <HTLCOwner.REMOTE: -1>: 3
      }
    },
    'fails': {},
    'fee_updates': {
      0: FeeUpdate(rate=253, ctn_local=0, ctn_remote=0),
      1: FeeUpdate(rate=254, ctn_local=1, ctn_remote=1),
      2: FeeUpdate(rate=254, ctn_local=1, ctn_remote=2)
    },
    'revack_pending': False,
    'next_htlc_id': 1,
    'ctn': 2,
    'unacked_updates': {},
    'was_revoke_last': False
  },
  <HTLCOwner.REMOTE: -1>: {
    'adds': {},
    'locked_in': {},
    'settles': {},
    'fails': {},
    'fee_updates': {
      0: FeeUpdate(rate=253, ctn_local=0, ctn_remote=0)
    },
    'revack_pending': False,
    'next_htlc_id': 0,
    'ctn': 3
  }
}
```

Sending a new transaction through this channel works - but the ctn numbers are still different.

**Comment by ecdsa** [comment]
thanks for the log. it looks like we are sending too many fee updates.
I suspect the code in https://github.com/spesmilo/electrum/blob/master/electrum/lnpeer.py#L1901 get executed more than once.

**Comment by ecdsa** [comment]
just for clarification, what is the version of Electrum you were running?

**Comment by Rogach** [comment]
I'm running the git version, currently at commit 1568c10ca (sorry, forgot to include this in the original submission).

**Comment by ecdsa** [comment]
I think the sending of unnecessary fee_updates could be fixed by this:

```diff
@@ -1896,7 +1896,7 @@ class Peer(Logger):
             self.logger.info("FEES HAVE FALLEN")
         elif feerate_per_kw > chan_fee * 2:
             self.logger.info("FEES HAVE RISEN")
-        elif chan.get_oldest_unrevoked_ctn(REMOTE) == 0:
+        elif chan.get_oldest_unrevoked_ctn(REMOTE) == 0 and not chan.hm.is_revack_pending(REMOTE):
             # workaround eclair issue https://github.com/ACINQ/eclair/issues/1730
             self.logger.info("updating fee to bump remote ctn")
             if feerate_per_kw == chan_fee:

```

Now regarding your problem, that might only be a side issue. 
`chan.should_be_closed_due_to_expiring_htlcs` might be misbehaving when `ctns` are off by one.

**Comment by ecdsa** [comment]
ok, I think I have found the issue. The CTN passed to htlcs_by_direction is not consistent with the subject (ctx owner).
@SomberNight can you have a look at this fix? 

```diff
index 456d6e610..6d1174494 100644
--- a/electrum/lnchannel.py
+++ b/electrum/lnchannel.py
@@ -1576,8 +1576,8 @@ class Channel(AbstractChannel):
         # to the present, then unilaterally close channel
         recv_htlc_deadline = lnutil.NBLOCK_DEADLINE_BEFORE_EXPIRY_FOR_RECEIVED_HTLCS
         for sub, dir, ctn in ((LOCAL, RECEIVED, self.get_latest_ctn(LOCAL)),
-                              (REMOTE, SENT, self.get_oldest_unrevoked_ctn(LOCAL)),
-                              (REMOTE, SENT, self.get_latest_ctn(LOCAL)),):
+                              (REMOTE, SENT, self.get_oldest_unrevoked_ctn(REMOTE)),
+                              (REMOTE, SENT, self.get_latest_ctn(REMOTE)),):
             for htlc_id, htlc in self.hm.htlcs_by_direction(subject=sub, direction=dir, ctn=ctn).items():
                 if not self.hm.was_htlc_preimage_released(htlc_id=htlc_id, htlc_proposer=REMOTE):
                     continue
@@ -1588,8 +1588,8 @@ class Channel(AbstractChannel):
         # will unilaterally close the channel and time out the HTLC
         offered_htlc_deadline = lnutil.NBLOCK_DEADLINE_AFTER_EXPIRY_FOR_OFFERED_HTLCS
         for sub, dir, ctn in ((LOCAL, SENT, self.get_latest_ctn(LOCAL)),
-                              (REMOTE, RECEIVED, self.get_oldest_unrevoked_ctn(LOCAL)),
-                              (REMOTE, RECEIVED, self.get_latest_ctn(LOCAL)),):
+                              (REMOTE, RECEIVED, self.get_oldest_unrevoked_ctn(REMOTE)),
+                              (REMOTE, RECEIVED, self.get_latest_ctn(REMOTE)),):
             for htlc_id, htlc in self.hm.htlcs_by_direction(subject=sub, direction=dir, ctn=ctn).items():
                 if htlc.cltv_expiry + offered_htlc_deadline > local_height:
                     continue

```

**Comment by SomberNight** [comment]
> ok, I think I have found the issue. The CTN passed to htlcs_by_direction is not consistent with the subject (ctx owner).

Oh, right. That is indeed a bug in `should_be_closed_due_to_expiring_htlcs`. The patch looks good.

> I think the sending of unnecessary fee_updates could be fixed by this
> ```
> -        elif chan.get_oldest_unrevoked_ctn(REMOTE) == 0:
>+        elif chan.get_oldest_unrevoked_ctn(REMOTE) == 0 and not chan.hm.is_revack_pending(REMOTE):
> ```

just use `chan.get_latest_ctn(REMOTE) == 0`.
but yes, it's a separate issue

> I tried debugging the issue myself, and it seems that for some reason LOCAL and REMOTE ctn's do not match

That can happen during typical operation and should be fine.

**Comment by Rogach** [comment]
Can confirm that this patch fixes the issue on my channels. Thank you!
