### ISSUE TITLE
Qt receive tab: receive_tabs widget looks broken on macOS

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7908]
QTabWidget with "West" tab position and horizontal text looks completely broken on macOS
(despite looking good on e.g. Ubuntu GNOME and Windows).

It seems the `VTabBar` code responsible for rotating the text so that the tab labels are horizontal does not work.
https://github.com/spesmilo/electrum/blob/ad9030bd1588db65ce93e6d0277ee8de51bf79cd/electrum/gui/qt/util.py#L1573-L1604

(There are other code snippets on stackoverflow, e.g. [this](https://stackoverflow.com/questions/50578661/how-to-implement-vertical-tabs-in-qt/50579369#50579369) and [this](https://stackoverflow.com/questions/46607298/pyqt-qtabwidget-horizontal-tab-and-horizontal-text-in-qtdesigner/63198915#63198915) but those too misbehave on macOS. I am not sure what the root cause is though.)

-----

See pictures:

<details>
 <summary>macOS pics</summary>

![Capture](https://user-images.githubusercontent.com/29142493/181862064-e44e2c59-e4a1-4455-a3fc-18b62a4cf099.PNG)
![Capture2](https://user-images.githubusercontent.com/29142493/181862066-cf35f521-e504-47e2-bdd9-f3a6f4402ffa.PNG)
![Capture](https://user-images.githubusercontent.com/29142493/181862068-fefc62dc-e96c-424d-b055-53cf38065116.PNG)
</details>

As a baseline, compare to Linux/Win:
<details>
 <summary>Ubuntu GNOME pics</summary>

![Capture](https://user-images.githubusercontent.com/29142493/181862425-e9c6b7df-8c90-4c3b-99ca-49317e22302b.PNG)
![Capture2](https://user-images.githubusercontent.com/29142493/181862426-0f39bd55-50a1-4cee-90c7-a446890aa443.PNG)
![Capture](https://user-images.githubusercontent.com/29142493/181862432-7eaa6d70-c261-477f-9bca-60cd0cb63d75.PNG)
![Capture2](https://user-images.githubusercontent.com/29142493/181862434-5a3986db-ad35-4761-9775-39eadf972709.PNG)
</details>

<details>
 <summary>Windows pics</summary>

![Capture](https://user-images.githubusercontent.com/29142493/181862457-f3119444-8c8b-42e8-b9ca-972d3bdcc48a.PNG)
![Capture2](https://user-images.githubusercontent.com/29142493/181862460-661a7baf-59af-4f7d-8928-ae21a8ff65f5.PNG)
![Capture](https://user-images.githubusercontent.com/29142493/181862464-176ae10a-c279-424c-b725-ffff056a31b5.PNG)
![Capture2](https://user-images.githubusercontent.com/29142493/181862466-c1f94144-f60a-482e-a898-9bc8521bb50c.PNG)
</details>

**Comment by ecdsa** [comment]
aaaah that's a pity.. I should have tested on MacOS
