### ISSUE TITLE
cannot sweep channel after local-force-close, from on-chain backup

### ISSUE THREAD

**Issue by Konstantinbochkarev** [spesmilo/electrum#7912]
![Снимок экрана 2022-08-02 в 20 47 31](https://user-images.githubusercontent.com/110522573/182543651-598bf6bb-ebaa-4a9c-94fc-f8f8269de62b.png)

**Comment by Konstantinbochkarev** [comment]
Канал успешно закрыт, но деньги на основной счет так и не поступили. Прошло 2 недели

**Comment by SomberNight** [comment]
Looks like the channel was opened in [this tx](https://blockstream.info/tx/c8fe4a930a7d0990d880ccf3224f6c8b118e48b760f0931b62baf4f7d51f7031), and immediately [force-closed with this tx](https://blockstream.info/tx/6499d96582892d2013f75adc1fff2fe3a71f307bbe1f66fcf02601ea460b128e), in the same block.
Not sure who force-closed but I would guess it's the opener (so local electrum) as all the money is going to a p2wsh address.

Note that the wallet in the picture only has a backup of the channel (and likely only an onchain backup).
An onchain backup is not sufficient to sweep a local-force-close, you either need an imported backup or the full channel for that.
You should open the wallet file in which you created the channel to get back the funds.
