### ISSUE TITLE
Electrum wallet hack

### ISSUE THREAD

**Issue by Ignatmishin** [spesmilo/electrum#7916]
Good afternoon.

As a result of a virus attack, my wallets were hacked - bc1q7avjf8tmykzcka56ks976h9y3hljua7qa2x9ff, 12grfgCuohZQFPHWsPDDHMKHqnzT6JneKw, 1K4XwrnTKFZbuquC6q6MncbrCkf3KAYAAB. All funds from wallets are transferred to the wallet - bc1qatfhtl3mspy9hn9a2e6gtfcdzzwkgeyennksxt. Please help in blocking the wallet to which the funds were transferred or contact me. Thanks

**Comment by ecdsa** [comment]
Sorry but we have no way to block funds sent to a bitcoin address.
We are a software provider, and this issue tracker is here to report and fix bugs.

**Comment by Ignatmishin** [comment]
Thank you, can you send the address of the technical support of the developers of the Electrum wallet?

**Comment by SomberNight** [comment]
You misunderstand. No one can freeze/move those coins except whoever has the private keys for them. There is no central authority in Bitcoin.

When using Electrum, the user has sole control of their private keys. The developers/maintainers of Electrum don't have any access to or visibility of user funds. We cannot help you recover the coins.

**Comment by hackmistress69** [comment]
![E28B81D5-1AE6-4AF2-8B68-FFB9260FA29E](https://user-images.githubusercontent.com/106688202/184520635-471e2319-6d02-4a58-a3c3-5bdffa716414.jpeg)
