### ISSUE TITLE
History tab description not set to receive request's

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#7919]
Upgraded to 4.3.0 and noticed that the description one enters on the receive tab is not reflected on the history tab when receiving payment. The description is lost because the receive request also gets deleted from the receive tab once the payment is received.

**Comment by ecdsa** [comment]
I cannot reproduce that.. was it on-chain or lightning?

**Comment by SomberNight** [comment]
I can reproduce. On-chain.
