### ISSUE TITLE
i cant use my electron wallet, help me out

### ISSUE THREAD

**Issue by Rickcoins** [spesmilo/electrum#7925]
![mm](https://user-images.githubusercontent.com/110949180/183792171-ba84df15-9bca-43c6-ae52-fb15978d4bc1.jpg)

**Comment by SomberNight** [comment]
Even beside the error popup, there are multiple minor hints in your image suggesting this is not Electrum but a malicious clone that likely wants to steal your money and potentially cause other harm. Consider the machine infected.

**Comment by Rickcoins** [comment]
this is electrum wallet, but old
![Screenshot (5)](https://user-images.githubusercontent.com/110949180/183796903-af060e52-1ad0-4c47-b460-ea168f59bb3d.png)

**Comment by SomberNight** [comment]
In your first screenshot, there is a "Channels" tab, which suggests it is at least Electrum 4.0, but the version number is missing from the window title. Already just from those two pieces of info, I can guarantee you that this is not the legitimate Electrum.
That "clear-cache" exe in particular just screams malware.
Consider everything on that computer to be compromised.

**Comment by Rickcoins** [comment]
What you're trying to say is I can't access my Bitcoins anymore, there must
be a way to fix this please tell me what to do because it always pop up
Blockchain sync error

**Comment by ecdsa** [comment]
consider your computer as compromised.
try to restore your wallet from see, on another machine.

**Comment by Rickcoins** [comment]
> consider your computer as compromised. try to restore your wallet from see, on another machine.

i have tried on a windows 10 pc and yet still not working, i tried importing my wallet on the newer version of electrum but its not working, please what else should i do
