### ISSUE TITLE
The channel has been closed, but the funds have not been returned.

### ISSUE THREAD

**Issue by xinyang89** [spesmilo/electrum#7930]
The channel has been closed, but the funds have not been returned.
`Traceback (most recent call last):
  File "electrum\gui\qt\history_list.py", line 742, in <lambda>
AttributeError: 'ElectrumWindow' object has no attribute 'show_channel'`

**Comment by SomberNight** [comment]
- What version of Electrum are you using?
- How did you close your channel?
- Does your wallet have the full channel or only a channel backup?

More context needed in general.

Also, thanks for the traceback, though it is most likely unrelated.
I am not quite sure how you triggered it, but it should now be fixed with https://github.com/spesmilo/electrum/commit/767b058946d5a4ebd9a434be8ad027a0ac67afdc.

**Comment by xinyang89** [comment]
Thanks&nbsp; for reply.


I'm not sure if I can reply directly here.
But I can send pictures here, which makes it easier to describe the problem.


1,What version of Electrum are you using?
&nbsp; Electrum version 4.3.0


2, How did you close your channel?
&nbsp; Right click and select close


3,Does your wallet have the full channel or only a channel backup?
&nbsp; Full











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spesmilo/electrum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spesmilo/electrum] The channel has been closed, but the funds have not been returned. (Issue #7930)





  
What version of Electrum are you using?
 
How did you close your channel?
 
Does your wallet have the full channel or only a channel backup?
  
More context needed in general.
 
Also, thanks for the traceback, though it is most likely unrelated.
 I am not quite sure how you triggered it, but it should now be fixed with 767b058.

**Comment by SomberNight** [comment]
>> 2, How did you close your channel?
>
> Right click and select close

Hmm... Could you share the transaction ID of the closing tx?

**Comment by xinyang89** [comment]
transaction ID:&nbsp;&nbsp;63696fd41abe3fbc4a30ae25b24b260cf0ff9fecb31c7d74548a055a676dfb32


I recorded a video in the attachment.
Please check!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spesmilo/electrum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spesmilo/electrum] The channel has been closed, but the funds have not been returned. (Issue #7930)





   
2, How did you close your channel?
  
Right click and select close
  
Hmm... Could you share the transaction ID of the closing tx?

**Comment by ecdsa** [comment]
The transaction looks like a force-close, not a regular close.
The channel was force closed only 2 blocks after it was funded, so all the funds still belong to the channel initiator.
The output address is p2wsh, so I guess it was force-closed by electrum, not by the remote.

Did you consciously force-close instead of close?

You should see a local transaction in your wallet history, that can only be broadcast in the future.

**Comment by xinyang89** [comment]
1 Did you consciously force-close instead of close?
&nbsp; &nbsp;No, not forc-close


2 You should see a local transaction in your wallet history
&nbsp; &nbsp;Yes.
&nbsp; &nbsp;A pop-up prompt appears when I pay, so I thought that deleting this record should make the payment successful.
&nbsp;


Now I want to know if the funds can finally be returned to my account,


adn what do I need to do to achieve that.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spesmilo/electrum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spesmilo/electrum] The channel has been closed, but the funds have not been returned. (Issue #7930)





 
The transaction looks like a force-close, not a regular close.
 The channel was force closed only 2 blocks after it was funded, so all the funds still belong to the channel initiator.
 The output address is p2wsh, so I guess it was force-closed by electrum, not by the remote.
 
Did you consciously force-close instead of close?
 
You should see a local transaction in your wallet history, that can only be broadcast in the future.

**Comment by ecdsa** [comment]
ah, I see, there is a bug that prevents the local transaction from being added to history.
I just fixed it in 90580007919ebe59c8f6757ca69fbf5097b4ea78

@xinyang89 :
That bug does not affect your funds, only what is displayed in your history.
When a channel is force closed, the funds are locked for a certain period of time, typically 720 blocks (approx 5 days).

**Comment by xinyang89** [comment]
Okay , thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spesmilo/electrum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spesmilo/electrum] The channel has been closed, but the funds have not been returned. (Issue #7930)





 
ah, I see, there is a bug that prevents the local transaction from being added to history.
 I just fixed it in 9058000
 
@xinyang89 :
 That bug does not affect your funds, only what is displayed in your history.
 When a channel is force closed, the funds are locked for a certain period of time, typically 720 blocks (approx 5 days).

**Comment by ecdsa** [comment]
closing, outpoint has been spent
