### ISSUE TITLE
cant import old wallet file

### ISSUE THREAD

**Issue by Rickcoins** [spesmilo/electrum#7934]
Hell please am finding it difficult to open my old version Electrum wallet file on the newer version i don't really know what to do
![Screenshot (7)](https://user-images.githubusercontent.com/110949180/184499572-a78add88-6f7a-4542-98bd-7a8d909043fc.png)

**Comment by ecdsa** [comment]
- is the file encrypted?
- what is the most recent version of Electrum that can open the file?

**Comment by Rickcoins** [comment]
> * is the file encrypted?
> * what is the most recent version of Electrum that can open the file?

i don't really know if the file is encrypted and i cant encrypt it
- what version of electrum can be able to open the file, because currently i downloaded the latest version but its not working

**Comment by Rickcoins** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/110949180/184501105-bfb98d37-644e-4142-a9ae-78f0447d246f.png)

**Comment by ecdsa** [comment]
>    what version of electrum can be able to open the file, because currently i downloaded the latest version but its not working

Sorry, but I cannot help you if you do not answer my question.  
Is there an old version of Electrum that is able to open your wallet file? 

if you are not able to answer that question, I suggest you try to restore your wallet from its seed

**Comment by ecdsa** [comment]
ah, same user as #7925
you have installed malware, there is no "clear-cache" executable in the legit Electrum.
I suppose the malware has corrupted your wallet file.

**Comment by ecdsa** [comment]
Please do not reopen a new issue: your issues have been closed because we cannot help you.

The only thing you can do is restore from seed on a clean computer, and see if your coins have been stolen.
If you did type your password while running the malware, then it is likely they have been stolen.
