### ISSUE TITLE
After upgrading to v4.3 Electrum won't connect to own electrum server

### ISSUE THREAD

**Issue by wchancao** [spesmilo/electrum#7937]
After upgrading Electrum to v4.3 the wallet does not connect to my own electrum server, ignoring my electrum.desktop file with the --oneserver flag, and instead connecting automatically to random public servers. Did something change in this version? Or anything new i should configurate to connect to my own server?

**Comment by ecdsa** [comment]
are you sure that is related to the upgrade? 
maybe it has to do with your desktop environment.

try to run the command in your electrum.desktop in a terminal, and see if it works

**Comment by SomberNight** [comment]
Re the electrum.desktop file, I think the only related change is https://github.com/spesmilo/electrum/commit/a15ed939b72c8d8e4488e7b287e20b6320983c2c - which is to do with where that bundled file is unpacked during installation.

> ignoring my electrum.desktop file with the --oneserver flag, and instead connecting automatically to random public servers

Did you put the --oneserver and --server params inside your .desktop file? Did those modifications maybe get overwritten when installing the new version?

**Comment by wchancao** [comment]
Running with `electrum --oneserver --server 192.168.0.7:50021:t` works.
I've tried to `sudo desktop-file-install electrum.desktop` without success, my .desktop file is originally in Downloads folder and i copied it to /home/user/.local/share too, the content of the .desktop file is this:

[Desktop Entry]
Comment=Lightweight Bitcoin Client
Exec=sh -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; electrum --oneserver --server 192.168.0.7:50021:t %u"
GenericName[en_US]=Bitcoin Wallet
GenericName=Bitcoin Wallet
Icon=electrum
Name[en_US]=Electrum Bitcoin Wallet
Name=Electrum Bitcoin Wallet
Categories=Finance;Network;
StartupNotify=true
StartupWMClass=electrum
Terminal=false
Type=Application
MimeType=x-scheme-handler/bitcoin;
Actions=Testnet;

[Desktop Action Testnet]
Exec=sh -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; electrum --testnet %u"
Name=Testnet mode

It was working before the 4.3 upgrade, so, dont know what else i can try to make it to connect to my own server other than running from CLI.

**Comment by SomberNight** [comment]
> `Exec=sh -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; electrum --oneserver --server 192.168.0.7:50021:t %u"`

Ok, so you have modified the .desktop file directly, I see.
So is it that when you double-click it to start Electrum, it launces but seemingly those parameters are ignored?
What if you also set e.g. `--testnet` there, is that also ignored?

**Comment by wchancao** [comment]
Yes. modified that line as
`Exec=sh -c "PATH=\"\\$HOME/.local/bin:\\$PATH\"; electrum --testnet --oneserver --server 192.168.0.7:50021:t %u"`
Run `sudo desktop-file-install electrum.desktop` and still ignores the testnet and the --oneserver flag. And yes, its when i click the icon to open the app.

**Comment by accumulator** [comment]
It might be that `desktop-file-install` installs the `.desktop` file in a system-wide location, and you also have a user` .desktop` file overriding it.

Check the contents of `$HOME/.local/share/applications/electrum.desktop`

**Comment by wchancao** [comment]
Yes, you are right. Added --oneserver in that .desktop file and is working now. Thank you!!
Solved and closing.
