### ISSUE TITLE
`request_status` event is sometimes triggered redundantly, resulting in confusing notifications to user about receiving money

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7943]
The `request_status` event should only trigger when we receive money satisfying a payment request.
However, there is another scenario it's triggered, erroneously.

-----

Consider scenario (all onchain, we are Alice):
- Alice creates payreq for addr1, amt1
- Bob pays to addr1, amt1,  in onchain tx1 -> creating utxo1
- Alice sees payreq is now satisfied; `request_status` is triggered, in Qt e.g. Alice sees an OS notification about receiving money
- ...some time passes, say multiple weeks...
- Alice pays Carol some money, in onchain tx2, and it so happens that utxo1 is an picked as one of the inputs of tx2
- due to implementation details, as tx2 now changed the history of addr1, all txs touching addr1 are reprocessed and `AddressSynchronizer.add_transaction` is called, ultimately triggering `request_status` for payreq again

This happens because,
- again, tx2 touches addr1, so addr1's history changes
- Alice's client will get an address status changed notification from the connected electrum server
- https://github.com/spesmilo/electrum/blob/0f227b177c93225a2ed92e25d003a490a77baf69/electrum/address_synchronizer.py#L427
- https://github.com/spesmilo/electrum/blob/0f227b177c93225a2ed92e25d003a490a77baf69/electrum/address_synchronizer.py#L340
- https://github.com/spesmilo/electrum/blob/0f227b177c93225a2ed92e25d003a490a77baf69/electrum/wallet.py#L489
- https://github.com/spesmilo/electrum/blob/0f227b177c93225a2ed92e25d003a490a77baf69/electrum/wallet.py#L2454

**Comment by SomberNight** [comment]
@ecdsa

How about something like this?
```patch
diff --git a/electrum/address_synchronizer.py b/electrum/address_synchronizer.py
index 33f1e226ef..0cf90df5ed 100644
--- a/electrum/address_synchronizer.py
+++ b/electrum/address_synchronizer.py
@@ -242,7 +242,7 @@ class AddressSynchronizer(Logger, EventListener):
     def get_transaction(self, txid: str) -> Transaction:
         return self.db.get_transaction(txid)
 
-    def add_transaction(self, tx: Transaction, *, allow_unrelated=False, notify_GUI=True) -> bool:
+    def add_transaction(self, tx: Transaction, *, allow_unrelated=False, notify_GUI=True, check_invoices_and_reqs=True) -> bool:
         """
         Returns whether the tx was successfully added to the wallet history.
         Note that a transaction may need to be added several times, if our
@@ -337,7 +337,7 @@ class AddressSynchronizer(Logger, EventListener):
             # save
             self.db.add_transaction(tx_hash, tx)
             self.db.add_num_inputs_to_tx(tx_hash, len(tx.inputs()))
-            util.trigger_callback('adb_added_tx', self, tx_hash, notify_GUI)
+            util.trigger_callback('adb_added_tx', self, tx_hash, notify_GUI, check_invoices_and_reqs)
             return True
 
     def remove_transaction(self, tx_hash: str) -> None:
@@ -424,7 +424,8 @@ class AddressSynchronizer(Logger, EventListener):
             tx = self.db.get_transaction(tx_hash)
             if tx is None:
                 continue
-            self.add_transaction(tx, allow_unrelated=True, notify_GUI=False)
+            # note: check_invoices_and_reqs=False is set to avoid triggering redundant events.
+            self.add_transaction(tx, allow_unrelated=True, notify_GUI=False, check_invoices_and_reqs=False)
 
         # Store fees
         for tx_hash, fee_sat in tx_fees.items():

diff --git a/electrum/wallet.py b/electrum/wallet.py
index 521ff735ae..4e6debbef1 100644
--- a/electrum/wallet.py
+++ b/electrum/wallet.py
@@ -473,7 +473,7 @@ class Abstract_Wallet(ABC, Logger, EventListener):
             self.logger.info(f'set_up_to_date: {up_to_date}')
 
     @event_listener
-    def on_event_adb_added_tx(self, adb, tx_hash, notify_GUI):
+    def on_event_adb_added_tx(self, adb, tx_hash, notify_GUI, check_invoices_and_reqs):
         if self.adb != adb:
             return
         tx = self.db.get_transaction(tx_hash)
@@ -486,7 +486,8 @@ class Abstract_Wallet(ABC, Logger, EventListener):
         self._maybe_set_tx_label_based_on_invoices(tx)
         if self.lnworker:
             self.lnworker.maybe_add_backup_from_tx(tx)
-        self._update_request_statuses_touched_by_tx(tx_hash)
+        if check_invoices_and_reqs:
+            self._update_request_statuses_touched_by_tx(tx_hash)
         if notify_GUI:
             util.trigger_callback('new_transaction', self, tx)
 
```

**Comment by SomberNight** [comment]
note: there is a related FIXME here:
https://github.com/spesmilo/electrum/blob/0f227b177c93225a2ed92e25d003a490a77baf69/electrum/gui/qt/main_window.py#L1142
however, the approach I suggest above would not fully fix that (e.g. we would still duplicate the event if there is a mempool double-spend or a chain reorg)

**Comment by ecdsa** [comment]
Why the extra parameter? `notify_GUI` and `check_invoices_and_reqs` are always equal.

**Comment by ecdsa** [comment]
Actually, all the tasks performed in `on_event_adb_added_tx` do not need to be performed again if the transaction was already added. I think we can remove that `notify_GUI` parameter, and trigger the callback only if the transaction is new.

**Comment by ecdsa** [comment]
done in 60c493dc156620931a0b22170ab8c76cc5349b20
