### ISSUE TITLE
Question about Electrum seed word lists

### ISSUE THREAD

**Issue by tadeubas** [spesmilo/electrum#7956]
In the [electrum docs](https://electrum.readthedocs.io/en/latest/seedphrase.html#security-implications) it says: Electrum currently use the same wordlist as BIP39 (2048 words)

I've tested changing the language, but the same english words are used to generate the seed, which is awesome! So my question is, why other word lists exists in the repository? https://github.com/spesmilo/electrum/tree/master/electrum/wordlist

**Comment by ecdsa** [comment]
initially we planned to create localized versions of the word list.
then we realized it is a bad idea, so we gave up on the idea.
the main reason is that it makes it complicated to propose auto-completions
