### ISSUE TITLE
Cannot sweep to_local from channel backup because assert is_static_remotekey_enabled fails

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#7959]
This is a consequence of 1f403d1ca1737178de8eb6a10784f35cdf1cba92

```
Traceback (most recent call last):
  File "/opt/electrum/electrum/util.py", line 1239, in wrapper
    return await func(*args, **kwargs)
  File "/opt/electrum/electrum/lnwatcher.py", line 208, in trigger_callbacks
    await callback()
  File "/opt/electrum/electrum/lnwatcher.py", line 225, in check_onchain_situation
    keep_watching = await self.do_breach_remedy(funding_outpoint, closing_tx, spenders)
  File "/opt/electrum/electrum/util.py", line 1239, in wrapper
    return await func(*args, **kwargs)
  File "/opt/electrum/electrum/lnwatcher.py", line 443, in do_breach_remedy
    sweep_info_dict = chan.sweep_ctx(closing_tx)
  File "/opt/electrum/electrum/lnchannel.py", line 264, in sweep_ctx
    our_sweep_info = self.create_sweeptxs_for_our_ctx(ctx)
  File "/opt/electrum/electrum/lnchannel.py", line 514, in create_sweeptxs_for_our_ctx
    return create_sweeptxs_for_our_ctx(chan=self, ctx=ctx, sweep_address=self.sweep_address)
  File "/opt/electrum/electrum/lnsweep.py", line 208, in create_sweeptxs_for_our_ctx
    assert chan.is_static_remotekey_enabled()
AttributeError: 'ChannelBackup' object has no attribute 'is_static_remotekey_enabled'

```

To reproduce, run test_backup from regtest and then open the alice wallet in the gui.

I believe the issue is older than that commit: The channel backup object used to have a method `is_static_remotekey_enabled` that was returning `False`. As a consequence, I suppose that `lnsweep` was deriving a wrong `to_remote_address`. This had no consequence on the capability to sweep `to_local` from our ctx, because the `to_local_address` was unaffected. 

If the `chan` object is a channel object, not a backup, the correct generation of `to_remote_address` is needed, in case there are HTLCs to sweep, and no to_local output. However, channel backups do not have that capability. Thus, we could branch on `chan.is_backup()` to decide whether we derive `to_remote_address`

**Comment by SomberNight** [comment]
> I believe the issue is older than that commit: The channel backup object used to have a method `is_static_remotekey_enabled` that was returning `False`. As a consequence, I suppose that `lnsweep` was deriving a wrong `to_remote_address`.

Looks like it, yes.

> This had no consequence on the capability to sweep `to_local` from our ctx, because the `to_local_address` was unaffected. 

Right.

> If the `chan` object is a channel object, not a backup, the correct generation of `to_remote_address` is needed, in case there are HTLCs to sweep, and no to_local output.

Yes, and AFAICT this works both after and before the change.

> However, channel backups do not have that capability. Thus, we could branch on `chan.is_backup()` to decide whether we derive `to_remote_address`

Ok, sounds good.

So, if I understand correctly, the bug only affects channel backups: in the old code it happened to be harmless, but in the new code it causes the method to raise and not to sweep `to_local`, right?
