### ISSUE TITLE
GPG Verification presents error, I want to verify that the download source is not compromised before usage.

### ISSUE THREAD

**Issue by dzyphr** [spesmilo/electrum#7964]
I imported the relevant keys for checking the gpg signature for the elctrum binary. The verification gave the following output:

>  wget https://download.electrum.org/4.3.1/Electrum-4.3.1.tar.gz.asc
> gpg --verify Electrum-4.3.1.tar.gz.asc
> --2022-09-01 15:23:00--  https://download.electrum.org/4.3.1/Electrum-4.3.1.tar.gz.asc
> Resolving download.electrum.org (download.electrum.org)... 172.67.160.221, 104.21.89.144, 2606:4700:3031::6815:5990, ...
> Connecting to download.electrum.org (download.electrum.org)|172.67.160.221|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 2499 (2.4K) [application/octet-stream]
> Saving to: ‘Electrum-4.3.1.tar.gz.asc’
> 
> Electrum-4.3.1.tar. 100%[===================>]   2.44K  --.-KB/s    in 0.001s  
> 
> 2022-09-01 15:23:00 (2.56 MB/s) - ‘Electrum-4.3.1.tar.gz.asc’ saved [2499/2499]
> 
> gpg: assuming signed data in 'Electrum-4.3.1.tar.gz'
> gpg: Signature made Thu 18 Aug 2022 03:44:19 AM CDT
> gpg:                using RSA key 637DB1E23370F84AFF88CCE03152347D07DA627C
> gpg: Can't check signature: No public key
> gpg: Signature made Wed 17 Aug 2022 02:48:39 PM CDT
> gpg:                using RSA key 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC
> gpg: Can't check signature: No public key
> gpg: Signature made Wed 17 Aug 2022 02:29:45 PM CDT
> gpg:                using RSA key 6694D8DE7BE8EE5631BED9502BD5824B7F9470E6
> gpg: Good signature from "Thomas Voegtlin (https://electrum.org) <thomasv@electrum.org>" [unknown]
> gpg:                 aka "ThomasV <thomasv1@gmx.de>" [unknown]
> gpg:                 aka "Thomas Voegtlin <thomasv1@gmx.de>" [unknown]
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the 
> 
> 
> 
> Primary key fingerprint: 6694 D8DE 7BE8 EE56 31BE  D950 2BD5 824B 7F94 70E6 

As you can see there are three RSA signatures that cannot be checked as they do not contain a public key, therefore GPG will assert that this is not a trusted signature.

> gpg: assuming signed data in 'Electrum-4.3.1.tar.gz'
> gpg: Signature made Thu 18 Aug 2022 03:44:19 AM CDT
> gpg:                using RSA key 637DB1E23370F84AFF88CCE03152347D07DA627C
> gpg: Can't check signature: No public key
> gpg: Signature made Wed 17 Aug 2022 02:48:39 PM CDT
> gpg:                using RSA key 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC
> gpg: Can't check signature: No public key
> gpg: Signature made Wed 17 Aug 2022 02:29:45 PM CDT
> gpg:                using RSA key 6694D8DE7BE8EE5631BED9502BD5824B7F9470E6

 

 I am aware this may not be a fatal flaw or may not represent a breach, but it does not instill me with confidence as I cannot verify the binary. The RSA keys used to sign the binary should be verifiable.

**Comment by dzyphr** [comment]
I noticed the extra public keys within this git repo, but in general I think it would be appropriate to put all of the 4 signer keys on the current release on the download page. The only one listed there is for ThomasV.

**Comment by dzyphr** [comment]
I added all of the gpg keys manually and only Emzy, Sombernight, and ThomasV match the signatures.

**Comment by ecdsa** [comment]
> As you can see there are three RSA signatures that cannot be checked

Not three, but two. 

> as they do not contain a public key, 

Not "signatures that [...] do not contain a public key", but signatures for which you have not imported the public key

> therefore GPG will assert that this is not a trusted signature.

The final warning is about the third key, that you have imported. You need to tell GPG that you trust this keys, if you do not want to see that warning.

> The RSA keys used to sign the binary should be verifiable.

This sentence does not really mean anything, cryptographically speaking.

> I noticed the extra public keys within this git repo, but in general I think it would be appropriate to put all of the 4 signer keys on the current release on the download page. The only one listed there is for ThomasV.

You are not understanding this at all. The signer keys MUST NOT be on the download page. The purpose of all this is to protect against a scenario where the download page is compromised. In that scenario, the attacker would change those keys. Therefore, the signing keys SHOULD be fetched from other sources. The git repo is another source. You can also find those keys elsewhere.

**Comment by dzyphr** [comment]
If I cannot verify the keys, what purpose do they serve? Why put one of the keys on the download page? If you are going to include others then include all of them so that the user can verify them. The binary is signed by keys that are completely un-verifiable, meaning as far as I (THE USER) knows it could be completely compromised. What is the point of the USER checking a GPG signature for which they cannot verify?
