### ISSUE TITLE
REOPENED DUE TO FORCEFUL CLOSING BY POTENTIALLY MALICIOUS ACTOR - GPG Verification presents error, I want to verify that the download source is not compromised before usage.

### ISSUE THREAD

**Issue by dzyphr** [spesmilo/electrum#7965]
ORIGINAL POST: https://github.com/spesmilo/electrum/issues/7964

If I cannot verify the keys, what purpose do they serve? Why put one of the keys on the download page? If you are going to include others then include all of them so that the user can verify them. The binary is signed by keys that are completely un-verifiable, meaning as far as I (THE USER) knows it could be completely compromised. What is the point of the USER checking a GPG signature for which they cannot verify?

Please, explain to me how Im just supposed to TRUST my bitcoin on an unverified binary blob signed by mysterious signers?

**Comment by dzyphr** [comment]
allow me to provide an excerpt from a point in Monero's history before anyone verified GPG keys:

> As reported and confirmed by multiple users on [GitHub](https://github.com/monero-project/monero/issues/6151), [Reddit](https://www.reddit.com/r/Monero/comments/dyfozs/security_warning_cli_binaries_available_on/) and [Twitter](https://twitter.com/DarkDotFail/status/1196668999519657984), the Monero website delivered potentially malicious binaries with not matching hashes a little over 30 minutes. At the moment all binaries are clean as they are currently delivered from a secure fallback hosting server.
> 
> 
> Users are encouraged by moderators on the Monero subreddit to "check the integrity of the binaries and verify that they were signed by Fluffypony's GPG key."
> 
> Guides on how to check if the downloaded binaries have the corrected hashes are available for Windows [here](http://src.getmonero.org/resources/user-guides/verification-windows-beginner.html) and for Linux and macOS [here](http://src.getmonero.org/resources/user-guides/verification-allos-advanced.html).
> 
> Although Windows and macOS files haven't been reported to be compromised, users of all platforms should check the hashes for all downloaded Monero binaries since all of them could've been switched with malicious versions.

The nerve you have to tell me that I should just use the file without being able to verify the keys is absolutely shocking.

**Comment by dzyphr** [comment]
Excerpt: https://security.gatech.edu/pgpbasics

>  By default the signatures of thee valid keys with "marginal trust" is enough to validate an unknown key.
You signed with only 3 keys. only two are verifiable and that is AFTER I went through the manual work to add all of the keys from your github. To me this shows a complete waste of GPG or in the worst scenario malicious intentions on the binary being distributed.

**Comment by accumulator** [comment]
Nobody is telling you you should use the code without verification. As explained in https://github.com/spesmilo/electrum/issues/7964#issuecomment-1235051391 you need to properly use gpg. That means importing the three public keys and signing them with your own key (after verifying you have the correct ones) to mark them as trusted. This is a process *you* need to follow to be able to properly verify the integrity of the artifact you want to use.

**Comment by dzyphr** [comment]
This is completely ignorant of the information I have provided, I already added all of the keys and attempted to verify them. That is the whole point. Clearly you did not read one word of my issue.
