### ISSUE TITLE
Can't find wallet after recovery

### ISSUE THREAD

**Issue by Uypflo** [spesmilo/electrum#7968]
Hello guys,

I want to help a friend who doesn't find his Bitcoin after recovering his electrum wallet.

Is it possible that when you use your 12 words that some wallets are getting lost?

We see that the Bitcoins are still on the blockchain in the wallet but we can't find the adress in the electrum app. How is it possible that electrum is not showing the wallet?

This is the Adress we don't find after recovering:
bc1q9y2jmzsm5q7mtfpxl4v5qxpj2crf200c9kx6cl

**Comment by fwittingham** [comment]
Use your 12 words with another wallet or try different derivations.

**Comment by Uypflo** [comment]
Which wallet can I use there?

fwittingham ***@***.***> schrieb am So., 11. Sept. 2022,
08:06:

**Comment by fwittingham** [comment]
Try different derivations in Electrum or try Ledger Live with the HW wallet or Exodus,

**Comment by SomberNight** [comment]
Was the seed originally generated using Electrum?
When you restore it using Electrum, what does it say for "seed type" just under the textbox where you write the seed? See:
![seedtype](https://user-images.githubusercontent.com/29142493/191810581-1fe75ca9-0c53-4f24-9925-5993f1bb1048.png)

**Comment by UncipheredLLC** [comment]
Hi @Uypflo 

Are you still having trouble? We're happy to review at Unciphered. https://www.unciphered.com

We also just helped the Electrum Wallet project getting a flaw fixed with the BIP70 QR code issue: https://github.com/spesmilo/electrum/security/advisories/GHSA-4fh4-hx35-r355

We're here to help!

**Comment by BlackHatHacker111** [comment]
I helped a lot of with this issue to recover there’s perfectly send me a friend request on discord let me help you with yours my discord is BlackHatHacker111#2333
