### ISSUE TITLE
Cannot run Appimage on 32 bit ARM.

### ISSUE THREAD

**Issue by mudd9** [spesmilo/electrum#7973]
I try to run the electrum appimage version on the newest puppy linux 32 bit on rpi 2.

`./electrum-4.3.1-x86_64.AppImage`
`bash: ./electrum-4.3.1-x86_64.AppImage: cannot execute binary file: Exec format error`

It looks like the appimage isn't prepared for 32 bit systems. If so, do you intend to do this?

**Comment by accumulator** [comment]
There's no AppImage for ARM yet, see #5159
