### ISSUE TITLE
Sending suspicious requests from electrum

### ISSUE THREAD

**Issue by mohammadhadiabb** [spesmilo/electrum#7980]
What is sending a request to Deep Web?
[
kittycp2gatrqhlwpmbczk5rblw62enrpo2rzwtkfrrr27hq435d4vid.onion:50002 
nuzzg3pku3xbctgamzq3pf7ztakkiidnmmier64arqwh3ajdddovatad.onion:50002
kittycp2gatrqhlwpmbczk5rblw62enrpo2rzwtkfrrr27hq435d4vid.onion:50002 
udfpzbte2hommnvag5f3qlouqkhvp3xybhlus2yvfeqdwlhjroe4bbyd.onion:60002 
udfpzbte2hommnvag5f3qlouqkhvp3xybhlus2yvfeqdwlhjroe4bbyd.onion:60002
wsw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion:50002 
....
]
and IP
[
167.172.226.175:50002
142.93.6.38:50002
94.23.247.135:50002 
73.92.198.54:50002 
...
]
And IPV6
[
2604:a880:2:d1::63:4001:50002
2603:6011:af41:7214::3:50002
2a03:b0c0:2:f0::c4:b001:50002 
...
]
URL
[
vmd84592.contaboserver.net:50002
osr1ex1.compumundohipermegared.one:50002
electrum.blockstream.info:50002 
2ex.digitaleveryware.com:50002 
electrum.org:443 
...
]
URL IMAGE
https://i.ibb.co/zJw2Mcz/Screenshot-from-2022-09-17-00-43-19.png
sh link
https://ibb.co/4dxSqyH

**Comment by ecdsa** [comment]
probably block headers subscriptions?
Electrum connects to more than a single server.
