### ISSUE TITLE
Failed to connect to 127.0.0.1 port 7777: Connection refused

### ISSUE THREAD

**Issue by bar-boss** [spesmilo/electrum#7981]
Ubuntu 20.04.5 LTS
1. start electrum deamon
`electrum daemon -d`
starting daemon (PID 1055)
2. load wallet
`electrum load_wallet -w /path/to/wallet`
true
3. get balance
`electrum -o -w /path/to/wallet getbalance`
{
    "confirmed": "0.000405"
}
4. get balance throung jsonrpc
curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"getbalance","params":[]}' http://user:PASSWORD@127.0.0.1:7777
curl: (7) Failed to connect to 127.0.0.1 port 7777: Connection refused

Why cURL can't connect to 127.0.0.1 port 7777?

**Comment by SomberNight** [comment]
Have you configured electrum to listen on that port?
`$ electrum setconfig rpcport 7777`
