### ISSUE TITLE
libsecp256k1 build not working for M1 Mac

### ISSUE THREAD

**Issue by Jiacheng-Liu** [spesmilo/electrum#8015]
Following instructions to manually build is not working.

**Comment by SomberNight** [comment]
please provide more details... what commands are you running exactly, and following instructions where?

**Comment by Jiacheng-Liu** [comment]
I was following instructions here https://github.com/spesmilo/electrum/blob/master/contrib/osx/README_macos.md

The last step: $ ./run_electrum failed, error message:

`Error: Failed to load libsecp256k1.
E | ecc_fast | libsecp256k1 library failed to load. exceptions: [OSError("dlopen(/Users/jiacheng/electrum/electrum/libsecp256k1.0.dylib, 0x0006): tried: '/Users/jiacheng/electrum/electrum/libsecp256k1.0.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))"), OSError("dlopen(libsecp256k1.0.dylib, 0x0006): tried: '/Users/jiacheng/opt/anaconda3/lib/libsecp256k1.0.dylib' (no such file), '/Users/jiacheng/opt/anaconda3/lib/libsecp256k1.0.dylib' (no such file), '/Users/jiacheng/opt/anaconda3/lib/python3.9/lib-dynload/../../libsecp256k1.0.dylib' (no such file), '/Users/jiacheng/opt/anaconda3/lib/libsecp256k1.0.dylib' (no such file), '/Users/jiacheng/opt/anaconda3/bin/../lib/libsecp256k1.0.dylib' (no such file), 'libsecp256k1.0.dylib' (no such file), '/usr/local/lib/libsecp256k1.0.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/lib/libsecp256k1.0.dylib' (no such file), '/Users/jiacheng/electrum/libsecp256k1.0.dylib' (no such file)")]`

I ended up just using the windows for my purpose but thought it would be good to raise some attention to this.

**Comment by SomberNight** [comment]
> ```
> libsecp256k1 library failed to load. exceptions:
> [OSError("dlopen(/Users/username/electrum/electrum/libsecp256k1.0.dylib, 0x0006):
> tried: '/Users/username/electrum/electrum/libsecp256k1.0.dylib' 
> (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))"),
> ```

Looks like you have successfully built the platform-native arm64 libsecp256k1 library as expected, however your python is x86_64.
So it is actually the python interpreter you have that is causing the issue.

Looking at the other paths in your error message, you seem to be using anaconda. Maybe try installing python in another way (from brew, or using pyenv, or isn't there a python pre-installed with the system?).

**Comment by Jiacheng-Liu** [comment]
Yes! I just tested with the pre-installed python, it does work with arm-based python. I think we can close this now.
