### ISSUE TITLE
Electrum Wallet stuck on startup, not syncing to blockchain.

### ISSUE THREAD

**Issue by abrahamOgba** [spesmilo/electrum#8019]
My electrum wallet is stuck on startup. It shows a dialog box that says "unable to sync to blockchain, manually run the clear-cache.cmd and restart the application." But when I clear the cache the problem still persists. Electrum still opens in the background and I can see my balance but I cannot interact with the Electrum app window while the dialog box is still open. When I close the dialog box or click "ok", both the dialog box and Electrum closes.

**Comment by SomberNight** [comment]
There is no `clear-cache.cmd`. It sounds like you have downloaded malware.
Consider your computer compromised. I recommend doing a full reinstall of the whole operating system.

Where did you download "electrum" from? You can copy the exact download link from your browser history or from the downloads window (press `ctrl+J` in firefox or chrome).
