### ISSUE TITLE
Five files have CRLF formatting issues

### ISSUE THREAD

**Issue by sorenstoutner** [spesmilo/electrum#8025]
I am using git-buildpackage to package Electrum for Debian.  This creates branches in Git to hold the pristine tarball, the the upstream source, and the Debian specific directory.  As part of the build process the system moves back and forth between these branches.  Apparently, it really doesn't like certain CRLF <-> LF issues in text files.  I believe that what is happening is that these fields are being auto-substituted by Git `push` and `pull`, which is then causing the verification stage to fail because the files have changed unexpectedly.  There are five specific text files that give it hard time:

electrum/gui/kivy/data/fonts/tron/License.txt
electrum/gui/kivy/data/fonts/tron/Readme.txt
electrum/gui/qml/fonts/PTMono.LICENSE
electrum/ripemd.py
electrum/wordlist/portuguese.txt

![CRLF](https://user-images.githubusercontent.com/26014704/196820308-a0f233ef-006c-4882-9f6d-c9b5648bf40c.png)

I don't consider myself an expert on this subject, but I think that the attached five files are formatted in a way that would make Git happier. (I had to add .txt to the end of PTMono.LICENSE and ripemd.py to make GitHub happy.  The original file name should be restored.)

[License.txt](https://github.com/spesmilo/electrum/files/9824907/License.txt)
[portuguese.txt](https://github.com/spesmilo/electrum/files/9824908/portuguese.txt)
[Readme.txt](https://github.com/spesmilo/electrum/files/9824909/Readme.txt)
[PTMono.LICENSE.txt](https://github.com/spesmilo/electrum/files/9824921/PTMono.LICENSE.txt)
[ripemd.py.txt](https://github.com/spesmilo/electrum/files/9824922/ripemd.py.txt)

**Comment by SomberNight** [comment]
please open a pull request with the changes you suggest instead of attaching files :P

**Comment by sorenstoutner** [comment]
I will.  The question is, given the automatic CFLF <-> LR conversion that some Git servers and clients are performing on these files, and given that I don't know enough of GitHub's configuration on the back end, they might or might not make it all the way through in the proper format.  It will be interesting to test.

**Comment by SomberNight** [comment]
maybe try tweaking `core.autocrlf` - maybe set to `input`? not sure
https://git-scm.com/docs/git-config
https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by SomberNight** [comment]
For future reference, files with CRLF line endings can be listed like this (from https://stackoverflow.com/a/73969):
```
$ find . -not -type d -exec file "{}" ";" | grep CRLF
./electrum/wordlist/portuguese.txt: ASCII text, with CRLF line terminators
./electrum/gui/qml/fonts/PTMono.LICENSE: Unicode text, UTF-8 (with BOM) text, with CRLF line terminators
./electrum/gui/kivy/data/fonts/tron/License.txt: ASCII text, with CRLF, LF line terminators
./electrum/gui/kivy/data/fonts/tron/Readme.txt: ASCII text, with CRLF, LF line terminators
./electrum/ripemd.py: Python script, ASCII text executable, with CRLF line terminators
```

**Comment by sorenstoutner** [comment]
Thanks.

**Comment by SomberNight** [comment]
Thanks for the PR.
I was looking into how to avoid this reoccurring in the future. See https://github.com/spesmilo/electrum/pull/8029
