### ISSUE TITLE
Trezor plugin: call clear_session after some user inactivity timeout?

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#803]
When trezor is connected, passphrase and PIN entered, the trezor will cache these so the user doesn't have to constantly enter the PIN.

According to stick, "Since firmware 1.2.1 there is a message called ClearSession that forces TREZOR to "forget" cached PIN and passphrase. The idea is that client sends this message after few minutes of user inactivity or when a screensaver kicks in or when a screen is locked."

Maybe electrum could do this? I've caught myself leaving the house with electrum open and trezor "unlocked"... not good.

**Comment by kyuupichan** [comment]
I will get round to this soon as part of the trezor improvements I'm making.
