### ISSUE TITLE
Electrum loop connecting to own node

### ISSUE THREAD

**Issue by zndtoshi** [spesmilo/electrum#8031]
On the lastest version of Electrum
Connected to my own node
Created a PSBT tx
After loading the signed tx in Electrum the wallet went in a loop and doesn't sync anymore.
Video:
https://youtu.be/53wCpOygjGA

**Comment by SomberNight** [comment]
Please upload [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging).

**Comment by zndtoshi** [comment]
Once the tx got 1 conf on chain the wallet synced. Will try again later to see if I can replicate the loop with debug logs true.

**Comment by SomberNight** [comment]
what server software (including version) do you use?

**Comment by zndtoshi** [comment]
Bitcoin core 22.0 on a ubuntu machine.

**Comment by SomberNight** [comment]
ok, but you also need an electrum server, e.g. ElectrumX, electrs, EPS, fulcrum
bitcoind in itself is not enough

**Comment by zndtoshi** [comment]
Electrs 0.8.10

**Comment by zndtoshi** [comment]
Created a new tx and I see this error in log:
20221028T044838.822986Z |    ERROR | interface.[192.168.0.100:50002] | Exception in run: RequestCorrupted('heights of confirmed txs must be in increasing order')

**Comment by SomberNight** [comment]
That looks to be related to https://github.com/spesmilo/electrum/issues/7058,
which should be fixed in https://github.com/romanz/electrs/issues/297 in electrs 0.9.0.
Please try to update the server and see if that fixes it.

**Comment by SomberNight** [comment]
closing. please reopen if still occurs with recent electrs
