### ISSUE TITLE
problem for money transfer

### ISSUE THREAD

**Issue by anapa777** [spesmilo/electrum#8032]
what to do if I have already transferred money to my 2 wallet 2 days ago and the money is still coming. is it possible to cancel the transaction somehow in order to make a quick transfer

**Comment by shreyansh012** [comment]
I don't think electrum has the option for RBF(Replace by fee) to bump the fee up and speed up the transaction. Secondly, transactions are irreversible, so all you can do is wait. Further you can check your transaction on mempool.space to know in which block it is and how long till it gets a confirmation.

**Comment by SomberNight** [comment]
> I don't think electrum has the option for RBF(Replace by fee) to bump the fee up and speed up the transaction

?? I am not sure how to make it more clear than already is in the interface that you can bump the fee...
You can bump the fee of opt-in RBF txs, or you can cancel them (via double-spending to yourself). Or you can CPFP if you control any of the outputs. These are all options available directly in the UI.
The bump fee option has been there for over 6 years (https://github.com/spesmilo/electrum/commit/bc1bef60a0e9c01dedc37368f9a64ae9621a7d35)...

@anapa777 more details are needed re the tx. are you the sender or the receiver of this tx? also, the mempool is pretty much empty atm, is the tx still unconfirmed? can you share the txid?
