### ISSUE TITLE
"No hardware device detected." on all Electrum versions after 4.1.5

### ISSUE THREAD

**Issue by polaris1205** [spesmilo/electrum#8042]
- HW Trezor One
- OS: Ubuntu 20.04
- Electrum versions where this problem persisted: 4.2.0-4.3.2

Just updated my Electrum to 4.3.2, and the error below appears when trying to connect a Trezor HW. Does anyone know how to fix it?

I also followed steps from [here](https://www.reddit.com/r/TREZOR/comments/snxf8m/unable_to_use_trezor_on_ubuntu/), [here](https://electrum.readthedocs.io/en/latest/hardware-linux.html) and [here](https://trezor.io/learn/a/electrum-and-trezor), but they have not helped. 

I ended up going backwards, and my Trezor was finally recognized on Electrum version 4.1.5. I tried every version after that one, and the HW was not recognized.

Error log:

> No hardware device detected.
>     To trigger a rescan, press 'Next'.
>     On Linux, you might have to add a new permission to your udev rules.
> 
>     Debug message
>     bitbox02: (error getting device infos)
>     Missing libraries for bitbox02.
>     ImportError()
>     Make sure you install it with python3
>     coldcard: (error getting device infos)
>     Missing libraries for coldcard.
>     ModuleNotFoundError("No module named 'ckcc'")
>     Make sure you install it with python3
>     jade: (error getting device infos)
>     Missing libraries for jade.
>     ModuleNotFoundError("No module named 'cbor'")
>     Make sure you install it with python3
>     keepkey: (error getting device infos)
>     Missing libraries for keepkey.
>     Make sure you install it with python3
>     ledger: (error getting device infos)
>     Missing libraries for ledger.
>     ModuleNotFoundError("No module named 'btchip'")
>     Make sure you install it with python3
>     safe_t: (error getting device infos)
>     Missing libraries for safe_t.
>     ModuleNotFoundError("No module named 'safetlib'")
>     Make sure you install it with python3
>     trezor: (error getting device infos)
>     Library version for 'trezor' is incompatible.
>     Installed: 0.12.2, Needed: 0.13.0 <= x < 0.14
>     Make sure you install it with python3

**Comment by accumulator** [comment]
> ```
> trezor: (error getting device infos)
> Library version for 'trezor' is incompatible.
> Installed: 0.12.2, Needed: 0.13.0 <= x < 0.14
> Make sure you install it with python3
> ```

The error message explains your issue. Your `trezor` library is too old. Upgrade to 0.13.x

(to avoid dependency problems, you can also use the [AppImage](https://electrum.org/#download))

**Comment by polaris1205** [comment]
That's what I have been trying to do, but this is what I get when I try to update the trezor library:
> pip3 install trezor[hidapi]
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: trezor[hidapi] in /usr/local/lib/python3.8/dist-packages **(0.12.2)**
Any advice?

I tried running the Appimage, but I can't seem to point Electrum to my node with --oneserver.

**Comment by SomberNight** [comment]
> pip3 install trezor[hidapi]
    Defaulting to user installation because normal site-packages is not writeable
    Requirement already satisfied: trezor[hidapi] in /usr/local/lib/python3.8/dist-packages (0.12.2)

You probably have `python3-trezor` installed from the package manager (apt). You could uninstall that.
Also, try `$ python3 -m pip install --user --upgrade trezor[hidapi]`

> I tried running the Appimage, but I can't seem to point Electrum to my node with --oneserver.

Why? the AppImage takes the same CLI parameters (and config keys) as running from source.

**Comment by polaris1205** [comment]
Running `$ python3 -m pip install --user --upgrade trezor[hidapi]` helped! 

Thanks!
