### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by xanikin-skywalker** [spesmilo/electrum#8048]
Electrum won't let me spend my bitcoins. Message says, "Insufficient funds" even though I have more than enough.

**Comment by SomberNight** [comment]
Try to click "max" instead of manually typing an amount. Do you get any errors or see any messages?
Is it a 2FA wallet?
Do you have any addresses/coins frozen? (click pie chart in bottom left corner)
Do you have a lot of small UTXOs/coins?

**Comment by xanikin-skywalker** [comment]
Thanks, I was not aware of the relatively large fee for the next amount of
transactions.

**Comment by Kalliingi** [comment]
![Uploading image.jpg…]()

**Comment by SomberNight** [comment]
What helped understand the issue?
Why is the fee large - is the tx large in bytes (lots of inputs), or is it a 2FA fee?

**Comment by Kallinn82** [comment]
I think I found my hacker vas it 4oktober? Give me my wallet back
