### ISSUE TITLE
Freezing watch only wallets 

### ISSUE THREAD

**Issue by seydanic** [spesmilo/electrum#8063]
freezing watch only wallets actually effecting that wallet without private key?

**Comment by SomberNight** [comment]
What do you mean? Are you asking about the "freeze address" functionality?
Freezing an address simply means the wallet will not choose coins from that address when creating a new transaction.
The setting is local to the wallet instance where you set it. That is, if you have two instances of the same logical wallet (e.g. wallet files on different computers), setting it on one does not affect the other.

**Comment by seydanic** [comment]
ok cool yea was watching wallets that have billions of coin in it like 6 billion in bitcoin and when i tried freezing the address bitcoin dropped in value out of no where like right when i did it

**Comment by seydanic** [comment]
was hoping it was a coincidence cause that would have been scary
