### ISSUE TITLE
Error when RECEIVING Bitcoin: mempool min fee not met Your transaction is paying a fee that is so low that the bitcoin node cannot fit it into its mempool. The mempool is already full of hundreds of megabytes of transactions that all pay higher fees. Try to increase the fee.

### ISSUE THREAD

**Issue by zjlerman** [spesmilo/electrum#8069]
A transaction that started yesterday around 955am never completed. It now says "Local" on my end and when I hit "Broadcast", I get the following error:

The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

mempool min fee not met
Your transaction is paying a fee that is so low that the bitcoin node cannot fit it into its mempool. The mempool is already full of hundreds of megabytes of transactions that all pay higher fees. Try to increase the fee.

However, I am the recipient and not the sender. The sender says everything looks correct on their end and there is nothing they can do. Is there a way I can incresase the fee on my end that I am not seeing to restart the transaction. I apologize if I am posting this to the wrong forum and thank you in advance, I'm just desperate here.

**Comment by SomberNight** [comment]
The error message is accurate, and I believe quite descriptive. The mempool is "full".
The sender can increase the fee of the tx via RBF. They set a too low fee, it is their responsibility to correct that.

Alternatively, anyone who controls an output of the tx (e.g. change output for sender, or output intended for recipient) might be able to use CPFP ("child pays for parent") - however with the "mempool min fee not met" error it's not so simple. CPFP works by having a node consider a low fee parent tx and a high fee child tx as a whole, and seeing it's worth it to mine them both to get the fee paid by the child tx - but in this case the parent tx pays a fee so low that nodes kick it out of their mempool instantly, before they see the child. Doing CPFP here would require something called "package relay" (to broadcast the low fee parent tx and the high fee child tx together), which is not yet implemented in Bitcoin.

Note that the size of the mempool is configurable and hence different between bitcoin nodes (and hence electrum servers). You can likely find electrum servers with very large mempools which still have your tx if you try a few. If you find one, there you can broadcast a CPFP, however it likely won't propagate well in the p2p network: it will only propagate to other bitcoin nodes that have large mempools. Best case scenario, it might get to a miner and get mined.

Frankly, in short, it is the sender's responsibility to solve, and obviously, as usual, you should not consider the invoice you created to be paid until the tx has a few confirmations.

**Comment by zjlerman** [comment]
Hi, I really appreciate the quick response. I agree with everything you said, and I tried doing CPFP earlier with some instructions I found on this forum, but I always get the following error:

The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

bad-txns-inputs-missingorspent
You might have a local transaction in your wallet that this transaction builds on top. You need to either broadcast or remove the local tx.

I think I followed everything correctly.

In regards to the sender, I agree with you, but I am unfortunately at the behest of basically a nameless entity, and they are saying they've released the funds and it is out of there hands, and since the error said I needed a larger fee to complete the transaction, I was hoping there was a way I could that on my end since the sender is being intransigent.
