### ISSUE TITLE
Could not bump fee. Could not find suitable outputs? PLEASE HELP Unconfirmed TXIDs

### ISSUE THREAD

**Issue by NoobAsYoutube** [spesmilo/electrum#8076]
Hello all,  I am new to this forum but i am in need of some grave assistance if someone can help me please? I have a couple of Unconfirmed transactions that got stuck in Mempool and have been stuck for multiple days. I am simply trying to move my BTC to another wallet . Im just in super need of the funds now as it was about a $500 BTC transaction. I am using Electrum wallet now to try to speed things up based on some info some other folks told me to do ( like using CPFP and RBF) but i think it kind of confused me and seemed to make it worse i think. I initially had 1 UNCONFIRMED transaction but after attempting those i now have 1 unconfirmed trans and 2 unconfirmed parent trans. I cant push them through because the initial fee on trans was too low.  As ive exhausted all avenues. Then the one transaction with RBF enabled gives me error code " COULD NOT BUMP FEE: COULD NOT FIND SUITABLE OUTPUTS". So i cant add any additional money to help raise the fee anymore.  I even tried to use the rebroadcast TXIDs sites. And its not helping. Anyone able to assist me with getting these confirmed and on the block? If i could increase fee somehow anymore in the transactions i would but, it wont allow me. Will tip a BTC wallet of anyone that can help me complete issue.  Would really appreciate it. Or at least some tips in what to do. Most avenues i seem to use always lead to a dead end.  Was using ELECTRUM wallet to try to bump fees. 

Thanks for any help

TRANSACTION IDS: 

eeb59265f7794e8725d5d6d5eac90affdcd91bb86e9709604589a7cf0ce35d47  - UNCONFIRMED original

8cb56da286ba3d4519aff1f92151b859b6e6650fbd9178358919fedf110695f3  - UNCONFIRMED parent

6b52706f2c14224556c8e0baf0328d73a1a127f23876caadfda8f915eb4d2e64  - UNCONFIRMED parent 2 with rbf ( This is the one that give error code)

**Comment by Samson777** [comment]
Попробуй здесь, не так давно сам попал в эту ситуацию: https://www.viabtc.com/tools/txaccelerator

**Comment by SomberNight** [comment]
> Then the one transaction with RBF enabled gives me error code " COULD NOT BUMP FEE: COULD NOT FIND SUITABLE OUTPUTS". 
> 6b52706f2c14224556c8e0baf0328d73a1a127f23876caadfda8f915eb4d2e64 - UNCONFIRMED parent 2 with rbf ( This is the one that give error code)

This tx has a single input of 4261 sats and is already paying 3674 sats in fees. You were getting the error as the bump_fee method could not figure out how to increase the fees further to the feerate selected. Given how almost all coins moved in that tx already go to fees, this does not look surprising.

Anyway, the listed txs have since been mined.
