### ISSUE TITLE
Is there a plan to support the keysend function?

### ISSUE THREAD

**Issue by yopoing** [spesmilo/electrum#8077]
Is there a plan to support the keysend function?keysend is very important.

**Comment by ecdsa** [comment]
I don't see any reason not to support it. pull requests are welcome

**Comment by yopoing** [comment]
> 

Thank you, when will electrum wallet support keysend? I want to use electrum to make a chat function similar to sphinx chat, but electrum does not support the keysend method to send transactions. If I want to implement the keysend method to send transactions on electrum, what work do I need to do?

**Comment by ecdsa** [comment]
For a chat function you need to both send and receive.
Correct me if I am wrong, but I think `keysend` works only if your node is public (that is, has public channels)

**Comment by ecdsa** [comment]
closing; there is no issue here.
no need to keep open issues for inactive conversations.
