### ISSUE TITLE
UNAUTHORIZED TRANSACTION

### ISSUE THREAD

**Issue by DJDAVIDGOMEZ** [spesmilo/electrum#8084]
Hello, 2 days later after registering with Electrum, and having deposited my BTC, today at 12:35 p.m. I had the balance at 0, and there is an exit movement to an address that I do not know.
Can someone help me please? it's all my savings.

**Comment by ecdsa** [comment]
you probably downloaded malware, or you did not protect your seed properly.

**Comment by DJDAVIDGOMEZ** [comment]
Hello, I don't think they took my seed, I've only been in Electrum for 4 days, and we have checked my personal computer, which I only have at home, and there is no spymware or anything malicious, which I ask for your help in verifying if it has been a breach to your system. The money has gone to this account

bc1qkwkkr9uanhjxa37dzumv0jnq5mzlpc5n7d4jh8

It is also your account and you can see that they have not entered through my computer.

Please try to check it out, because it's all my life savings.

Thank you very muchEl 26 nov 2022 6:42, ThomasV ***@***.***> escribió:
you probably downloaded malware, or you did not protect your seed properly.

**Comment by ecdsa** [comment]
There is no "account" that we can check. 
We do not have any user data, everything is on your computer.

The only thing we can do is help determine if you have downloaded malware instead of Electrum.
maybe you could tell us if you verified the GPG signatures?

**Comment by DJDAVIDGOMEZ** [comment]
Hello, Download the link from the web, I attach the link itself so you can verify. Thank youhttps://download.electrum.org/4.3.2/electrum-4.3.2-portable.exeEl 26 nov 2022 9:20, ThomasV ***@***.***> escribió:
There is no "account" that we can check.
We do not have any user data, everything is on your computer.
The only thing we can do is help determine if you have downloaded malware instead of Electrum.
maybe you could tell us if you verified the GPG signatures?

**Comment by DJDAVIDGOMEZ** [comment]
Hello, have you been able to check if we can recover the money? It's all my savings.

The money has been transferred to this account that I don't know whose it is

bc1qkwkkr9uanhjxa37dzumv0jnq5mzlpc5n7d4jh8

Thank you so muchEl 26 nov 2022 10:47, David Gomez Calveras ***@***.***> escribió:Hello, Download the link from the web, I attach the link itself so you can verify. Thank youhttps://download.electrum.org/4.3.2/electrum-4.3.2-portable.exeEl 26 nov 2022 9:20, ThomasV ***@***.***> escribió:
There is no "account" that we can check.
We do not have any user data, everything is on your computer.
The only thing we can do is help determine if you have downloaded malware instead of Electrum.
maybe you could tell us if you verified the GPG signatures?

**Comment by ecdsa** [comment]
no, we cannot recover your money.
this is not a bank, we have no way of interfering with transactions.

**Comment by DJDAVIDGOMEZ** [comment]
Hello, I understand that you are not a bank, but have you been able to check if this executable (downloaded from the web) is correct? I have not lost the seed or given it to anyone, in 3 days everything has happened to me, I signed up for Electrum and stole all my savings. You as creators of this platform can investigate something, right? Thank you


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: David Gomez ***@***.***>
Enviado: sábado, 26 de noviembre de 2022 10:48
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [spesmilo/electrum] UNAUTHORIZED TRANSACTION (Issue #8084)


Hello, Download the link from the web, I attach the link itself so you can verify. Thank you




https://download.electrum.org/4.3.2/electrum-4.3.2-portable.exe




El 26 nov 2022 9:20, ThomasV ***@***.***> escribió:

There is no "account" that we can check.
We do not have any user data, everything is on your computer.

The only thing we can do is help determine if you have downloaded malware instead of Electrum.
maybe you could tell us if you verified the GPG signatures?

**Comment by ecdsa** [comment]
the download link you provided is correct.
that does not mean that your computer is safe, though.
the possible causes for theft are:
 - your computer might be infected by malware.
 - someone had access to your computer
 - someone had access to your seed paper backup.

**Comment by ecdsa** [comment]
closing this; I don't think we can help.
