### ISSUE TITLE
Bitcoin legacy wallet import with 18 keywords address start with 1*

### ISSUE THREAD

**Issue by dvdinh307** [spesmilo/electrum#8089]
I have 18 keywords bitcoin wallet but i can't recover my wallet with Electrum.
How i can import them. I see Electrum only support 12 keywords. Please help me! THanks

**Comment by ecdsa** [comment]
you need to tick bip39 in the options of the wizard dialog

**Comment by dvdinh307** [comment]
I get checksum: Fail.
What i need do next bro :(

**Comment by dvdinh307** [comment]
> you need to tick bip39 in the options of the wizard dialog

I get error checksum : Fail.
I import 18 keywords and check BIp39 and this result show.

**Comment by ecdsa** [comment]
this probably means you did not write your seed down correctly.
do you know which wallet generated that seed? more details would help.

**Comment by SomberNight** [comment]
It might not even be a bip39 seed. OP should have written down more details together with the seed.
For example, IIRC blockchain.info legacy "mnemonics", pre-2016, were 15-21 word long, and used a custom format. That mnemonic was not a HD seed, it was simply an encoding of the user's password (so useless in itself). See e.g. https://bitcoin.stackexchange.com/questions/70613/recover-keys-from-legacy-blockchain-wallets-mnemonic

Anyway, it's off-topic to Electrum.

**Comment by SNikala27** [comment]
Let me know my next move please  I haven't received any payments
