### ISSUE TITLE
Export a unsigned transaction by QRCODE encoding

### ISSUE THREAD

**Issue by massmux** [spesmilo/electrum#8092]
During testing with specter DIY we got aware that the format electrum (encoding) exports QR codes is not standard. In this way the exported unsigned TX by QRCODE cannot be imported by specter diy.
So it would be useful for all the community that electrum may implement the standard encoding so that electrum can deal also with diy with qrcodes.

Here the needed resources:

please see this python implementation: https://github.com/Foundation-Devices/foundation-ur-py
implementation in DIY: https://github.com/diybitcoinhardware/f469-disco/tree/master/libs/common/microur
specifications: https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md

**Comment by massmux** [comment]
thanks to @stepansnigirev and @Polto for having helped in debugging

**Comment by SomberNight** [comment]
same as https://github.com/spesmilo/electrum/issues/7905 ?

**Comment by stepansnigirev** [comment]
> same as #7905 ? EDIT: if so, please close this one and comment there instead

Yes.
Most wallets only implement crypto-psbt stuff (see two python implementations in the issue text).
The specs are overcomplicated, but everybody adopted this format, and it works pretty well for large transactions.
