### ISSUE TITLE
QR Image Fails to Show

### ISSUE THREAD

**Issue by bgillin58** [spesmilo/electrum#8095]
I installed the windows standalone and the windows installer. During the setup it would not display the QR for the 2fa setup. I tried again with both version not using 2fa. I then used the send function and received the message that a QR was not found on the screen. I then attempted an the wallet QR did not show.

**Comment by SomberNight** [comment]
> During the setup it would not display the QR for the 2fa setup

This is a known bug in the last release, already fixed on master. (https://github.com/spesmilo/electrum/issues/8071)

> I tried again with both version not using 2fa. I then used the send function and received the message that a QR was not found on the screen.

What exactly did you do? Based on the error message, in the Send tab "Pay to" field, I guess you might have tried to use the "Read QR from screen" function. Was there a QR code shown on the screen that you were trying to scan?

> I then attempted an the wallet QR did not show.

Again, not sure what you were trying to do.

**Comment by bgillin58** [comment]
Thank you for the response. Due to the error I decided to remove the app.
