### ISSUE TITLE
I need help with...

### ISSUE THREAD

**Issue by xchak** [spesmilo/electrum#8106]
I need help with how to set a new server address: for the LBRY vault wallet.

I have tried everything and have not been able to get my wallet connected to the server.
pls see screen shot

The 2 servers listed do not work any more, + I was trying to add a new one/server address, but it will not let me add anything.
I have contacted lbry.com and they didn't know and said I should try to reach out the developer?

I thought that they were the developer but I guess not? I have been trying to find Thomas Voegtlins email address, but haven't been able to find out any way to contact him? = he is the developer.

Anyways, If anyone has any ideas for me to try? pls post   thank you
![screenshot](https://user-images.githubusercontent.com/9570626/209658583-20927550-9fe1-4701-a432-93b416a17d08.JPG)

**Comment by accumulator** [comment]
The wallet you're using is a fork of electrum for a different coin, without apparently removing contact information. We don't support forks nor any coin other than Bitcoin. Please direct your questions to the fork maintainer.
