### ISSUE TITLE
Electrum doesn't recognize Ledger after latest BTC app upgrade 2.1.0 (6702)

### ISSUE THREAD

**Issue by razimih** [spesmilo/electrum#8111]
Hello,

Think this issue was not raised already, if is was pls. point me to it.

Electrum desktop (4.3.2) does not recognize my Ledger nano X after I updated the Bitcoin app on the Ledger through Ledger Live. (version 2.1.0). Before this update was working with no issues. I am on Win 11, Ledger is USB connected.

I even tried to create a new wallet (standard, hardware) and I am getting:

**Debug message
ledger: (error getting device infos)
Exception : Invalid status 6702**

even tried as admin, as the message suggests.  
As well, I tried it on a Mac OS Monterey (12.5.1) - same message , just different code : **6e00**

Any thoughts ? Thanks

**Comment by realAP** [comment]
Hello,

i have the same problem.
Using Bitcoin App with version 2.1.0

I am using the AppImage (4.3.2) on ArchLinux.

Debug Message:
**E | plugin.DeviceMgr | failed to create client for ledger at b'0001:0025:00': BTChipException('Invalid status 6e00', 28160)**

Ledger is connected, unlocked and Bitcoin App is started.

**Comment by SomberNight** [comment]
This is already fixed on master, but not in a release yet. See https://github.com/spesmilo/electrum/issues/7897#issuecomment-1365971126

As a workaround, until there is a new release of Electrum, I believe there might be a "Bitcoin Legacy" App for the Ledger that supports the old protocol. @bigspider might be able to confirm/correct.

@ecdsa we should probably do a release; and figure out whether from master or a branch.

**Comment by bigspider** [comment]
Yes, the "Bitcoin Legacy" app is available after enabling "Experimental features ==> Developer mode" in the settings.

**Comment by SomberNight** [comment]
4.3.3 is released now, should work there.
