### ISSUE TITLE
`get_request_by_addr` incorrectly maps addresses to request ids

### ISSUE THREAD

**Issue by MrNaif2018** [spesmilo/electrum#8113]
When using payment requests feature for some time (details below), `get_request_by_addr` returns incorrect id, often expired or already paid and not the one pending, which leads to `request_status` event sending wrong notifications, thus those who listen on that event are unable to correctly process payments.
https://github.com/spesmilo/electrum/blob/30079c06a8b01feeefd713dc18f28219bc4f4842/electrum/wallet.py#L2446-L2448
I think something is wrong here:
https://github.com/spesmilo/electrum/blob/30079c06a8b01feeefd713dc18f28219bc4f4842/electrum/wallet.py#L2358-L2359

How I was able to reproduce it:
Create first invoice, pay it. Create second invoice, pay it. Create third invoice, let it expire. Create fourth one, pay it - `request_status` sends id of the expired invoice instead.

I think I found out why: get_request_by_addr iterates over each payment request ever existing for an address, so while the old id was expired before, when the payment arrived it happens that get_invoice_status returns PR_PAID for an expired invoice (and for non-expired too), expired one is first in the list and gets returned first
Related: #8061, but it is more critical than before because it can be seen easily due to change to use request ids instead of addresses for payment requests

**Comment by MrNaif2018** [comment]
@SomberNight One of the ways to fix this issue is to introduce status to payment requests and store it together in the wallet storage. Then it can just refer to stored status and not compute each time. What do you think?

**Comment by MrNaif2018** [comment]
There's another possible bug I found:
https://github.com/spesmilo/electrum/blob/d52afee6357475fbae194724ca9b3f0b5e4e5ac0/electrum/wallet.py#L2399

If we paid partially, status is still Unpaid, but list of tx hashes isn't updated because of is_paid check here. I think it could be omitted?

**Comment by SomberNight** [comment]
I've pushed a fix/workaround in https://github.com/spesmilo/electrum/commit/9a0fff2571fa4e992b30e2ee5c1aa7bc8ee7b21f. Please see if you can still reproduce.

Indeed the proper fix would be to solve https://github.com/spesmilo/electrum/issues/8061.

> How I was able to reproduce it:
Create first invoice, pay it. Create second invoice, pay it. Create third invoice, let it expire. Create fourth one, pay it - request_status sends id of the expired invoice instead.

This looks needlessly complicated unless I am missing something. 
`test_wallet_get_request_by_addr` added in https://github.com/spesmilo/electrum/commit/7dcaa4b2049ee190ab9ff7a6518775955036c048 should reproduce the issue I think you are describing. It only reproduces it sometimes (i.e. test is flaky without fix in subsequent commit) - the bug depends on the internal order of items in a set.

**Comment by MrNaif2018** [comment]
Thanks! Yes, just checked, the fix works
