### ISSUE TITLE
android qml UI improvements before release

### ISSUE THREAD

**Issue by accumulator** [spesmilo/electrum#8125]
This bug contains a list of small UI issues needing improvement before release.

- [x] option to display wallet seed
- [x] QR type indicator on ReceiveDialog more clear (underline?)
- [x] frozen address color in line with electrum-desktop (plus legend?)
- [x] wallet list from top menu wallet name click
- [x] trampoline/gossip dropdown -> switch with confirm dialog
- [x] menu not modal, propagates outside click when open
- [x] lightning indicator next to onchain indicator
- [x] menu to left side, remove back button
- [x] socks5/tor autodetect (remove explicit Tor option)
- [x] scan network-serialized fully signed TX
- [x] after partially signing, present next page to show to cosigner
- [x] remove Electrum logo from top bar

**Comment by SomberNight** [comment]
> option to display wallet seed/master privkey

Show seed option would be enough, no need to expose xprv. Other GUIs don't do it either.

**Comment by accumulator** [comment]
> Show seed option would be enough, no need to expose xprv. Other GUIs don't do it either.

updated issue.

**Comment by ecdsa** [comment]
looks good so far. I think we could also remove the electrum logo from the top bar.
