### ISSUE TITLE
Cannot receive multi-trampoline payment from Phoenix

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#8141]
This issue was probably introduced in 7d9f20f8ab3d6a77f68de9c4a47acfcae3724d6e
In that commit, we decided to use the same temporary feature bits in Electrum as in Phoenix.

However Phoenix apparently is not able to create multi-trampoline routes such as:
`Phoenix client -> ACINQ Trampoline -> Electrum Trampoline -> Electrum client`
@t-bast can you confirm that?

I did not notice that issue earlier because my test wallet also had a direct channel with ACINQ.
The ACINQ node was using that direct channel instead of the invoice routing hint.

Until this is resolved in Phoenix, I suppose that we should use different temporary bits than ACINQ.
That way, Phoenix will perform a legacy payment (this is how it used to work before 7d9f20f8ab3d6a77f68de9c4a47acfcae3724d6e).

**Comment by t-bast** [comment]
> However Phoenix apparently is not able to create multi-trampoline routes such as:
Phoenix client -> ACINQ Trampoline -> Electrum Trampoline -> Electrum client
@t-bast can you confirm that?

Yes, we're waiting to get feedback from other implementations on the spec before updating phoenix and eclair's support for trampoline. In the meantime phoenix only supports a single trampoline hop through our node.

> Until this is resolved in Phoenix, I suppose that we should use different temporary bits than ACINQ.
That way, Phoenix will perform a legacy payment (this is how it used to work before https://github.com/spesmilo/electrum/commit/7d9f20f8ab3d6a77f68de9c4a47acfcae3724d6e).

That's IMO the best solution in the short-term. I really hope we see progress on the trampoline spec effort in 2023 to put those not-so-temporary hacks behind us!

**Comment by ecdsa** [comment]
@t-bast thanks for the clarification.
