### ISSUE TITLE
Question on use of Tron font

### ISSUE THREAD

**Issue by sorenstoutner** [spesmilo/electrum#8148]
In preparing the 4.3.3 Debian package, I am trying to understand the usage of the Tron (Tr2n) font.

```
soren@soren-desktop:~/Downloads/Electrum-4.3.3$ grep -R Tr2n
electrum/gui/kivy/uix/dialogs/installwizard.py:                font_name: f'{KIVY_GUI_PATH}/data/fonts/tron/Tr2n.ttf'
Electrum.egg-info/SOURCES.txt:electrum/gui/kivy/data/fonts/tron/Tr2n.ttf
```

It appears to only be used in installwizard.py.  My question is, what are all the mechanisms that file can be called, and does it have any practical use for someone who is installing Electrum from a Debian package?

**Comment by ecdsa** [comment]
That font was used to create the logo.
Again, you don't need to bundle the kivy GUI for a Debian distro.

**Comment by sorenstoutner** [comment]
OK, thanks.  It is fairly easy for me to just exclude a subdirectory when preparing the package.

**Comment by sorenstoutner** [comment]
Would it be safe for me to assume that installwizard.py is not used once the program is installed (and thus, isn't needed when shipping a Debian package)?

**Comment by sorenstoutner** [comment]
Disregard the previous question.  For some reason I though installwizard.py was outside the Kivy subdirectory.  If I just exclude all of Kivy the answer to that question becomes obvious.
