### ISSUE TITLE
stuck, unconfirmed transaction

### ISSUE THREAD

**Issue by cem2021** [spesmilo/electrum#8154]

**Comment by cem2021** [comment]
Issue with stuck, unconfirmed transaction using the updated Electrum wallet today. Yesterday made 5 similar transactions without any issues. I can provide the necessary transaction information in a private manner.  I transacted like I did yesterday, don't know what's different. This was the first transaction of the day so not sure if a wallet glitch. It is so unnerving to have issues in which there is no readily available support. Trying all morning to figure this out and look for for information.  Can someone please reach out to provide help and support. Thanks for any person's time to help me.

**Comment by ecdsa** [comment]
please learn about fees and how to bump them
