### ISSUE TITLE
Does not show balance

### ISSUE THREAD

**Issue by btccoreblock** [spesmilo/electrum#8160]
Why is that?
![Screenshot_9](https://user-images.githubusercontent.com/107360104/213919549-8d2413b7-e58e-4010-8cf0-75b073f0df16.jpg)

1126GDuGLQTX3LFHHmjCctdn8WKDjn7QNA

**Comment by ecdsa** [comment]
transaction 80f324e3831bde67476d4a670b2e3d52057bdcd9394bbe09c275017b96562584 is a block mining reward that was sent to a P2PK script, with the same pubkey as your address.
blockchain.com aggregates P2PK and P2PKH outputs in the same "address".
That is not really correct. Other Block explorers do not do that
See for example https://blockstream.info/address/1126GDuGLQTX3LFHHmjCctdn8WKDjn7QNA

**Comment by ecdsa** [comment]
Note: if you are the owner of these coins, and you are trying to spend them, you cannot do that in Electrum.
See #2857

**Comment by seega** [comment]
> transaction 80f324e3831bde67476d4a670b2e3d52057bdcd9394bbe09c275017b96562584 is a block mining reward that was sent to a P2PK script, with the same pubkey as your address. blockchain.com aggregates P2PK and P2PKH outputs in the same "address". That is not really correct. Other Block explorers do not do that See for example https://blockstream.info/address/1126GDuGLQTX3LFHHmjCctdn8WKDjn7QNA

What it incorrect here? The blockchain explorer you specified just makes the same mistake as Electrum.

![photo_2023-05-27_01-10-37](https://github.com/spesmilo/electrum/assets/19250962/230c4cfa-ac27-4bea-80d6-8295a389a6e6)
