### ISSUE TITLE
Error synchronising labels

### ISSUE THREAD

**Issue by ATButteaux** [spesmilo/electrum#8161]
When forcing a download of labels, I receive this error:
`Error synchronising labels:
ErrorConnectingServer(ClientConnectorCertificateError(ConnectionKey(host='labels.electrum.org', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-3114812414391988202), SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))`

**Comment by ecdsa** [comment]
it tshould be fixed now
