### ISSUE TITLE
Cosigner certificate expired

### ISSUE THREAD

**Issue by Lvenizerv** [spesmilo/electrum#8163]
Getting an error while using cosigning, an ssl error

SSL_CERTIFICATE_VERIFICATION_FAILURE
probably because https://cosigner.electrum.org/ certificate expired on Jan 19 2023
fix pls

**Comment by ecdsa** [comment]
should work now

**Comment by ecdsa** [comment]
Note: in the long term, it would be better to use a decentralized service for cosigning.
Maybe we could try to rewrite this plugin so that it uses Nostr. 
@1440000bytes That could be a first step towards a coinjoin plugin.

**Comment by 1440000bytes** [comment]
Sounds good. PSBTs can easily be sent using encrypted DM (NIP 4) if 2of2 multisig or encrypted channel (NIP 38 or NIP 48) if more than 2 signers are involved.
