### ISSUE TITLE
Missing money from my electrum wallet 

### ISSUE THREAD

**Issue by Modee01** [spesmilo/electrum#8164]
I had parallel trial version installed on my mac, electrum wallet was installed on windows. the trial expired on 1/20/2023 at the same date all bitcoins in my wallet were transferred to another wallet, I didn't transfer any money from my wallet. Further, the electrum wallet was removed from my windows, I had to install it back. I can see all my transaction history.
Did the money go to a safe account or stolen?

**Comment by ecdsa** [comment]
this looks like theft, although there is no way to be sure with the information you provided.
Does your history show an outgoing transaction that is emptying the wallet? better post a screenshot of the history.
There is no "safe account" withdrawal initiated by us, we have no control over users wallets.

**Comment by Modee01** [comment]
![Capture](https://user-images.githubusercontent.com/123423728/214924331-29fb6f7c-ed1b-431d-bcfb-8b99f7579a9a.PNG)
Yes there is

**Comment by Modee01** [comment]
if this is a theft should I create a new wallet and disregard this one

**Comment by ecdsa** [comment]
you should consider that your computer is compromised.
do not create a new wallet on the same computer if you do not know how the theft occured.
