### ISSUE TITLE
[Feature request] Support for option_support_large_channel for advanced users

### ISSUE THREAD

**Issue by spotty-banana** [spesmilo/electrum#8165]
I have an use case that would greatly benefit from option_support_large_channel to allow greater capacity for offchain transactions. Are there plans to support that in electrum?

**Comment by ecdsa** [comment]
ACK. I think we should definitely allow large capacity channels.

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/commit/40f2087ac3cde164eb3e69d69c3775d9d970792f
