### ISSUE TITLE
distutils is deprecated and will not work in Python 3.12

### ISSUE THREAD

**Issue by sorenstoutner** [spesmilo/electrum#8183]
Debian Lintian provides the following info:

```
This package uses the Python distutils module.

In Python 3.10 and 3.11, distutils has been formally marked as deprecated.
Code that imports distutils will no longer work from Python 3.12.

Please prepare for this deprecation and migrate away from the Python
distutils module.

See-Also: https://peps.python.org/pep-0632
```

Is there a plan to replace the distutils dependency?

**Comment by SomberNight** [comment]
I don't think electrum depends on distutils. We use a very small part of it that we explicitly vendor (https://github.com/spesmilo/electrum/pull/7797).
Does your linter give more hints why it thinks we need distutils?

**Comment by sorenstoutner** [comment]
As far as I know, Electrum is just using it for `version.py`.

```
soren@soren-desktop:~/Downloads/Electrum-4.3.4$ grep -R distutils
contrib/make_packages.sh:# FIXME aiohttp will compile some .so files using distutils
contrib/build_tools_util.sh:    # This ensures that if setuptools calls distutils which then calls easy_install,
contrib/build_tools_util.sh:    DISTUTILS_CFG="${HOME}/.pydistutils.cfg"
contrib/build_tools_util.sh:    DISTUTILS_CFG_BAK="${HOME}/.pydistutils.cfg.orig"
contrib/build_tools_util.sh:        warn "Overwriting python distutils config file at '$DISTUTILS_CFG'. A copy will be saved at '$DISTUTILS_CFG_BAK'."
electrum/gui/qt/update_checker.py:from electrum._vendor.distutils.version import StrictVersion
electrum/_vendor/distutils/version.py:# distutils/version.py
electrum/_vendor/distutils/version.py:    in the distutils documentation.
electrum/_vendor/distutils/__init__.py:"""(part of) distutils, taken from the cpython standard library
electrum/_vendor/distutils/__init__.py:at commit https://github.com/python/cpython/tree/9d38120e335357a3b294277fd5eff0a10e46e043/Lib/distutils
Electrum.egg-info/SOURCES.txt:electrum/_vendor/distutils/LICENSE
Electrum.egg-info/SOURCES.txt:electrum/_vendor/distutils/__init__.py
Electrum.egg-info/SOURCES.txt:electrum/_vendor/distutils/version.py
```

According to https://peps.python.org/pep-0632, you should replace that behavior with the `packaging` package.

```
For these modules or types, use the standards-defined Python Packaging Authority packages specified:

    distutils.version — use the packaging package
```

Currently, in Debian, I remove the copy of version.py that you install and depend on Debian's distutils package.  But based on what https://peps.python.org/pep-0632 says, that isn't going to work either at your level or in Debian with Python 3.12.

```
Code that imports distutils will no longer work from Python 3.12.
```

**Comment by SomberNight** [comment]
As in the linked PR (https://github.com/spesmilo/electrum/pull/7797), we specifically started to vendor `version.py` from distutils because of this deprecation. Also, as mentioned in the PR, the `packaging` 3rd party package does not provide a good-enough replacement of`distutils.version.StrictVersion` (the only class we use from distutils) for our use case.

> Currently, in Debian, I remove the copy of version.py that you ship and depend on Debian's distutils package. But based on what https://peps.python.org/pep-0632 says, that isn't going to work either at your level or in Debian with Python 3.12.

Why would the deprecation/removal affect us (assuming you don't patch out the vendored copy of the file we need :P)?

**Comment by sorenstoutner** [comment]
They say that `Code that imports distutils will no longer work from Python 3.12.`  I assume that means that line 19 of `electrum/gui/qt/update_checker.py` will fail.

```
from electrum._vendor.distutils.version import StrictVersion
```

However, maybe that won't be enough to trigger the error.  I am uncertain how strict their import checking will be.

**Comment by accumulator** [comment]
> They say that `Code that imports distutils will no longer work from Python 3.12.` I assume that means that line 19 of `electrum/gui/qt/update_checker.py` will fail.
> 
> ```
> from electrum._vendor.distutils.version import StrictVersion
> ```
> 
> However, maybe that won't be enough to trigger the error. I am uncertain how strict their import checking will be.

No, I think this simply means that distutils will no longer be part of the python Standard Library (`python3-distutils` package / `python3-stdlib-extensions` source package in Debian).

Importing from within `electrum._vendor.distutils` namespace will succeed as it's shipped with Electrum.

**Comment by sorenstoutner** [comment]
That makes sense.  In which case, like you said, I can just consider this file to be part of your code under a different license, especially since upstream is going away, so you will be the new upstream for this file.

**Comment by SomberNight** [comment]
Right, sounds good then.
