### ISSUE TITLE
running multiple instances

### ISSUE THREAD

**Issue by elandorr** [spesmilo/electrum#8188]
I assume c7e2125f intentionally broke this?

Or is there still a way to run multiple instances (with different wallets)?

**Comment by SomberNight** [comment]
You can use the `--dir` option.
https://github.com/spesmilo/electrum/blob/0eea47c78dd53b44863f8e88e9bed133edc83f6e/electrum/commands.py#L1536

**Comment by elandorr** [comment]
Thank you. Copying all except the wallets and sock seems reasonable to you? Or could everything except those two be symlinked?

```
blockchain_headers
cache
certs
config
daemon_rpc_socket
forks
recent_servers
wallets
```

**Comment by SomberNight** [comment]
What are you trying to do? Note that you can run a single daemon with multiple wallets open simultaneously.

**Comment by elandorr** [comment]
I'm trying to open multiple wallets. Using the same settings and cache would be of benefit.

The `--dir` option recreates a new structure for each, which makes sense. I'm not aware of how the daemon works, could you please explain?

**Comment by SomberNight** [comment]
> I'm not aware of how the daemon works, could you please explain?

Why don't you just use the GUI? It is trivial to open multiple wallets there.

Are you trying to run CLI commands (or RPCs)? Otherwise you don't need to use the daemon, just use the GUI.

To use the daemon, you would use the "load_wallet" command to open a wallet in memory and operate on it. Other commands can be given the `-w` switch to specify which wallet you want to use, e.g.:
```
$ ./run_electrum daemon --testnet -d
$ ./run_electrum load_wallet -w ~/.electrum/testnet/wallets/test_segwit_2 --testnet
$ ./run_electrum load_wallet -w ~/.electrum/testnet/wallets/test_segwit_3 --testnet
$ ./run_electrum add_request 0.001 -m "test" -w ~/.electrum/testnet/wallets/test_segwit_2 --testnet
$ ./run_electrum add_request 0.001 -m "test" -w ~/.electrum/testnet/wallets/test_segwit_3 --testnet
$ ./run_electrum --testnet stop
```
You only need the `--dir` option if you want to run multiple independent instances of the electrum process, e.g. multiple daemons. But again, a single daemon is capable of opening multiple wallets.

**Comment by elandorr** [comment]
>Why don't you just use the GUI?

I never tried, haha! I got the appimage, verified your sig, ran it twice. Don't really like appimages, but it's probably the easiest verifiable way to get a current electrum on a fresh system. Don't really need the CLI/RPC at the moment, besides opening wallets.

Is there a way to open several wallets from CLI? As in telling electrum to use the existing daemon, like it does when you use the GUI?

load_wallet only seems to work when electrum has been started in explicit daemon mode. The daemon seems 'internal' when running the GUI.

Goal is avoiding accidents by having them appear in the same spot onscreen every time, by running one command/bash script. A script is safer than sleep deprived clicking.

Thanks for your help!

**Comment by SomberNight** [comment]
> Is there a way to open several wallets from CLI? As in telling electrum to use the existing daemon, like it does when you use the GUI?

I gave an example just above your comment. The daemon there has two wallets loaded, and I ran the `add_request` command for both of them.

> load_wallet only seems to work when electrum has been started in explicit daemon mode

Most CLI commands that use your wallet need a synchronised wallet to be useful, to make that practical they need an explicitly started daemon that handles network activity and keeps the wallets synchronised.
The daemon runs in a separate, long-running process, and you can run CLI commands in one-shot short-lived processes that communicate with the daemon. That's the model: it needs a daemon.

> The daemon seems 'internal' when running the GUI.

Indeed.

**Comment by elandorr** [comment]
I know, but I was thinking of a way without explicitly running the daemon, as that requires you to deal with that properly in your scripts as well. Otherwise, you may end up leaving one running, after you're done.

The `-d` for detach isn't listed in `-h` by the way.

And I just tried, I think there's a misunderstanding. Your way is only for actual usage via CLI only. You can't run the GUI on top of the daemon.

```
./electrum-4.3.4-x86_64.AppImage gui
Error: Electrum is running in daemon mode. Please stop the daemon first.
```

My goal is, quoting myself:

>Goal is avoiding accidents by having them appear in the same spot onscreen every time, by running one command/bash script. A script is safer than sleep deprived clicking.

Which is why I attempted running the binary multiple times, as I'd do with other programs. Then the window manager can be used to position them.

The only way to achieve this is thus what I wrote in my initial reply:

```
./electrum-4.3.4-x86_64.AppImage -D wallet1 &
./electrum-4.3.4-x86_64.AppImage -D wallet2 &
```

This creates a new dir structure every time, which is why I asked what would be safe to symlink, to avoid duplication. At least the config file would be nice for not having to redo the settings, but, if there's any chance both may try to write, that's of course dangerous.

The interactive way is using a single dir, and then clicking file-open. But that's error-prone and inefficient, which is what I wanted to avoid in the first place.

**Comment by SomberNight** [comment]
Ok, I think I finally understand what you are trying to do. I am surprised it does not work already, I think it's a regression from https://github.com/spesmilo/electrum/commit/a43be6657defe92631872d401fa0a940b680a540.
Fixed in https://github.com/spesmilo/electrum/commit/d3a10c422550ec863b5d9359e6286cfa48548474.

**Comment by elandorr** [comment]
You, my friend, work ridiculously fast. Thanks!

Please excuse me not testing with the master source right now, I'm busy, and can wait for a release. Just read that electrum is pure python, that's pretty neat! Makes me reconsider using the appimage. But then again, self-contained, portable, single-file-sig-verifiable, that's nice too.

**Comment by SomberNight** [comment]
closing, let us know if there's still a problem
