### ISSUE TITLE
coinbase address balance not detected

### ISSUE THREAD

**Issue by accumulator** [spesmilo/electrum#8195]
Testing on testnet, with imported address wallet.

import e.g `mg4bQva8w7Cjs8KaKHeEbyXUaCzoQAcXyH`, address is added to wallet, but balance stays 0

**Comment by ecdsa** [comment]
A zero balance is correct for this address. 
The block reward was paid to the pubkey, not to the pubkey hash
See 
https://blockstream.info/testnet/tx/455a31ad20c84f7f63459d66d14fd052ed9c8f9e82e724d4357c0d10bf0daa41
