### ISSUE TITLE
Coin control active: 1 выводов доступно (всего 1),Активен контроль монет

### ISSUE THREAD

**Issue by Pudinggg** [spesmilo/electrum#8196]
Первый раз пополнил кошелек Электрум, на транзакции пополнения уже 3 подтверждения, хочу их потратить, сразу снизу вылезает зелёное окошко
Coin control active: 1 выводов доступно (всего 1)
что это может быть ??? помогите пожалуйста

**Comment by SomberNight** [comment]
You must have manually activated "coin control" in either the "Addresses" or the "Coins" tab, by right-clicking some addresses/coins.
You can click "reset" in the right-end of the green bar to close it.

**Comment by Pudinggg** [comment]
Первый способ не работает, нет такого пункта монеты
Нажав кнопку сбросить ни чего не меняется
