### ISSUE TITLE
Не пришли бтс на кошелёк 

### ISSUE THREAD

**Issue by CrazyMenn** [spesmilo/electrum#8198]
Здравствуйте, не знаю куда писать, поэтому пишу сюда
отправил два раза на один кошелёк бтс, вторая транзакция не пришла на счет ! 
что делать? кошелек : 3PPSB1hWzm14QZQNps3fZQUgyriaGXHog3
7.02.23 - 0.263 btc

**Comment by SomberNight** [comment]
There is not enough info here to help.
And this is a bug tracker, not a support forum.
Maybe try to ask for help on [bitcointalk or reddit](https://electrum.org/#community).
