### ISSUE TITLE
Missing fingerprints in multisig wallets

### ISSUE THREAD

**Issue by sad-error** [spesmilo/electrum#8206]
When adding cosigners through xpubs/Zpubs this results in missing fingerprints in the wallet - some hw wallets (coldcard for one) seem to require the fingerprint in order to decide if they are involved in the psbt. The only way to solve this that I could find is go into the raw wallet json and fix the

`"root_fingerprint": null`

I think it would be useful to have a fingerprint input field along side the xpub/zpub when adding cosigners.

**Comment by SomberNight** [comment]
~duplicate: https://github.com/spesmilo/electrum/issues/5715
related: https://github.com/spesmilo/electrum/issues/5715#issuecomment-548602270

there is a workaround here: https://github.com/spesmilo/electrum/issues/5715#issuecomment-762271103
(still cumbersome but preferred over modifying the wallet file by hand)

I will close this issue in favour of that one - though I admit your description is easier to understand than digesting that whole thread.

I am working on https://github.com/spesmilo/electrum/issues/5694 now, I imagine at a later stage of that work I will have to revisit this issue.
