### ISSUE TITLE
Robo de cuenta

### ISSUE THREAD

**Issue by pope19264** [spesmilo/electrum#8210]
A los 4 meses ingreso a mi cuenta y está totalmente vacía con una transacción realizada el 26 de enero de 2023 a las 20:03, nadie me da respuesta ni soporte para ubicar esa transacción o bloquear la cuenta que me robó.

**Comment by SomberNight** [comment]
Either you have malware on your device, or you leaked your seed somehow.
There is not enough info here to help.
