### ISSUE TITLE
open multi gui from cmd 

### ISSUE THREAD

**Issue by ubuntuabd4** [spesmilo/electrum#8216]
Hi,i want start multi wallet electrum from command line
./electrum-4.3.4.exe gui -w "D:\test\wallet1"
./electrum-4.3.4.exe gui -w "D:\test\wallet2"
./electrum-4.3.4.exe gui -w "D:\test\wallet3"....
but only the first wallet shows, the next wallets don't show GUI, what should I do

**Comment by SomberNight** [comment]
Hi. Thanks for the report.
This is a known bug in recent releases, and is now fixed on master since https://github.com/spesmilo/electrum/commit/d3a10c422550ec863b5d9359e6286cfa48548474.
