### ISSUE TITLE
Bitcoin unconfirmed and lightning is not working.

### ISSUE THREAD

**Issue by joshuaperez1976** [spesmilo/electrum#8221]
I need some help. My Bitcoin has been unconfirmed and can not be found in blockchain when I search for Tx. Also my lightning is not working. Can someone help me. If anyone can help I will gladly provide reimbursement. 
![Screenshot (115)](https://user-images.githubusercontent.com/50599376/219944382-081b9831-5178-4e95-9070-3079d12cfded.png)
![Screenshot (115)](https://user-images.githubusercontent.com/50599376/219944462-a10e8dd6-d57b-4bdd-9db4-e5ac89800327.png)
![Screenshot (116)](https://user-images.githubusercontent.com/50599376/219944510-5691218e-714d-4374-bc26-ba083ea05150.png)

**Comment by SomberNight** [comment]
Please don't waste our time with fake wallets / txs.

**Comment by joshuaperez1976** [comment]
How is this fake.

**Comment by joshuaperez1976** [comment]
I can see it on blockchain because it was not mined.

**Comment by joshuaperez1976** [comment]
Can not see it on blockchain due to never been mined.

**Comment by SomberNight** [comment]
And why was your tx paying you 300k btc not mined? Did you skimp out on fees?
There is no tx even in the mempool for [that address](https://blockstream.info/address/bc1qdeke9j6py05jh4x8prme9qx047wmx09ghch3sj).

**Comment by joshuaperez1976** [comment]
That is we’re I have the problem. Anyway I can prove that this is a legitimate problem. It came from 12ib7dApVFvg82TXKycWBNpN8kFyiAN1dr I attempted to reach out to him to to resend but had not heard from him. It was sent but never confirmed due to low fee transaction I placed.

**Comment by joshuaperez1976** [comment]
![EE275C8F-005D-40E0-BF5B-B47EBA08F2FC](https://user-images.githubusercontent.com/50599376/220117227-7c5e8bc0-d64c-45de-92eb-a4a35b067793.jpeg)
![45D047B3-3B51-41DB-AD27-641A3C93D455](https://user-images.githubusercontent.com/50599376/220117250-91133a08-7605-48da-b293-5594307d2046.jpeg)
![297EFE2E-193A-4851-B8DB-BFB126B948E7](https://user-images.githubusercontent.com/50599376/220117257-b16be559-5911-4ee1-9ee2-0b99ff0325bd.jpeg)

This is my other address on my wallet Sombernight you can see this is a real wallet and with low fee I can not get my coins mined. Pls help
