### ISSUE TITLE
Hack or bug

### ISSUE THREAD

**Issue by SashaMarti** [spesmilo/electrum#8222]
Good afternoon, I created a portable Electrum wallet, replenished the balance in two days, went into the wallet, a transaction appeared on the addresses to change the wallet, canceled the transaction and turned off the addresses for change, replenished the wallet by another 0.20 btc, the balance disappeared the next day, how to explain this

3726b520824ba66bc32b9ba82cd92b66d957c7aea70eb5c69c1d80442a3ac3bc
![Screenshot_24](https://user-images.githubusercontent.com/125823715/219967116-a35b4aca-81ad-44fe-b4ff-07bb2c36f94b.png)
![Screenshot_23](https://user-images.githubusercontent.com/125823715/219967117-f8645ce5-ab34-491d-b0ef-461129085750.png)

**Comment by ecdsa** [comment]
not sure what you mean, but "change addresses" are not here "to change the wallet".
if your wallet seed has been compromised, money will be stolen again if you replenish it.

**Comment by BlackHatHacker111** [comment]
Yes you’ve been hacked message me on discord to recover all stolen coins my discord is BlackHatHacker111#2333
