### ISSUE TITLE
Where is my money?

### ISSUE THREAD

**Issue by heelpnow** [spesmilo/electrum#8223]
https://www.blockchain.com/explorer/addresses/btc/16D2zAGMUCiiW397LQ43bFe3TD8AtXEDAe

I did not received the money into my Electrum Wallet, there is no history and no balance, what's next?

**Comment by heelpnow** [comment]
I installed Electrum 2.6.4 on Ubuntu with sudo snap install electrum? What is the problem?

**Comment by SomberNight** [comment]
We do not distribute Electrum in the Ubuntu Snap store. The version there is unofficial and unmaintained.

Get Electrum from the official website instead: https://electrum.org/#download

**Comment by heelpnow** [comment]
They stole my money?

**Comment by heelpnow** [comment]
Who have access to my money?

**Comment by SomberNight** [comment]
Old versions of Electrum can no longer communicate with modern Electrum servers. That's why they show no history, they cannot connect at all.

**Comment by heelpnow** [comment]
Then how can we save that transaction?

**Comment by heelpnow** [comment]
I am sure I am not alone!

**Comment by heelpnow** [comment]
Why do you let this appear: https://snapcraft.io/electrum ?

**Comment by heelpnow** [comment]
The wallet is there but Electrum 2.6.4 is can not access to it...

**Comment by heelpnow** [comment]
If I go to Electrum-4.3.4 and use "Your wallet generation seed is:" I can access to it?

**Comment by heelpnow** [comment]
Problem solved. Thank you!
