### ISSUE TITLE
my wallet disappears all the balance I put in it immediately

### ISSUE THREAD

**Issue by danielvitor61** [spesmilo/electrum#8226]
![Sem título](https://user-images.githubusercontent.com/73726479/220963599-310df836-9bf0-45b0-a6d6-95ee16aa3b15.jpg)

my wallet disappears all the balance I put in it immediately does anyone know if it's a problem or bug? immediately look at the time when the balance comes in it comes out

**Comment by SomberNight** [comment]
Your wallet is probably compromised. Either your PC has bitcoin-stealing malware, or you downloaded a fake/malicious clone of Electrum, or your seed was leaked/stolen somehow (e.g. by storing it in cloud storage and that account getting compromised).

You should wipe and reinstall that PC, and create a new seed/wallet.

**Comment by danielvitor61** [comment]
how to close this wallet°?
