### ISSUE TITLE
Android APP - after importing a priv key QR and closeing the APP, the app apears with QR image in open app show slide

### ISSUE THREAD

**Issue by vlc33** [spesmilo/electrum#8227]

**Comment by SomberNight** [comment]
Not sure I understand the bug report. I guess the claim is that the secret QR code is visible in the "[recents](https://developer.android.com/guide/components/activities/recents)" screen?
If so, the qml app is setting FLAG_SECURE in those cases (see e.g. https://github.com/spesmilo/electrum/issues/8351), so I think this was fixed.

In any case, closing as the kivy GUI was removed in https://github.com/spesmilo/electrum/pull/8591
