### ISSUE TITLE
Android APP - no way to delete or change the name of Wallets

### ISSUE THREAD

**Issue by vlc33** [spesmilo/electrum#8228]

**Comment by SomberNight** [comment]
There is a way to delete a wallet. Click the wallet name on the top bar to open the wallet info dialog, in which there is a "delete" button at the bottom.

**Comment by vlc33** [comment]
In my Android App I could not reach such a button.
![Screenshot_20230301-164442_Electrum](https://user-images.githubusercontent.com/43541146/222191689-2a7d9ba2-95ba-448d-b5d5-da6de053645c.png)
![Screenshot_20230301-164455_Electrum](https://user-images.githubusercontent.com/43541146/222191697-d44105cd-311e-4bb9-a9da-86fcc99c3053.png)
![Screenshot_20230301-164506_Electrum](https://user-images.githubusercontent.com/43541146/222191700-efc2e74c-1549-450e-bc69-cc6937d31a48.png)
![Screenshot_20230301-164554_Electrum](https://user-images.githubusercontent.com/43541146/222191703-e46c46ad-ac57-4386-bf8b-7d9d34536669.png)
