### ISSUE TITLE
sweep() missing 1 required positional argument: 'destination

### ISSUE THREAD

**Issue by ubuntuabd4** [spesmilo/electrum#8236]
when i try to run comand from cmd and postmand, how i can fix it, thank you

`curl --location "http://user:abcd@127.0.0.1:7777" --header "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"id\":\"curltext\",\"method\":\"sweep\",\"params\":[{\"privkeys\": [\"p2wpkh:cNMzaSFKjzMdpd4ov9CKdz34RxFRHNMBVeTmC2coVvciQkArRrLD\"], \"destination\": \"bc1q2rzgphx4ndjq6xl7f6u9a03lnyq0xvumq26lyx\"}]}"
`

it say 
{
    "id": "curltext",
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "sweep() missing 1 required positional argument: 'destination'"
    }
}

**Comment by SomberNight** [comment]
I haven't tested but looks like you have too many levels of nesting for params.
Instead of a list containing a dict, just use the dict directly.

Try:
```
{"jsonrpc":"2.0","id":"curltext","method":"sweep","params":{"privkeys": ["p2wpkh:cNMzaSFKjzMdpd4ov9CKdz34RxFRHNMBVeTmC2coVvciQkArRrLD"], "destination": "bc1q2rzgphx4ndjq6xl7f6u9a03lnyq0xvumq26lyx"}}
```
Also note that the arg name is `privkey`, not `privkeys`.
And note that you cannot use a mainnet address for testnet.

**Comment by ubuntuabd4** [comment]
hi, thank i try but it say Invalid Request

**Comment by SomberNight** [comment]
Here is a working example:
```
$ curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"sweep","params":{"privkey": "p2wpkh:cNMzaSFKjzMdpd4ov9CKdz34RxFRHNMBVeTmC2coVvciQkArRrLD", "destination": "tb1qyvufkfkz7vvd0gsj4kjkvpke34mnpqdru9p80a"}}' http://user:pass@127.0.0.1:7777
```
