### ISSUE TITLE
Problem with wallet

### ISSUE THREAD

**Issue by hipsollek** [spesmilo/electrum#8246]
Hi, i have a problem with wallet. I generated adress to buy btc and then disappeared adress, 
i no have money and i have a ticket from bitomat but transaction not realized. 

please help me.

**Comment by hipsollek** [comment]
Sorry, i see this transaction on my wallet. but i don't know why this monet out my wallet to not known without my participation.

**Comment by ecdsa** [comment]
sorry, but this type of report is useless.
we cannot help you if you do not provide precise information

**Comment by hipsollek** [comment]
Yesterday i buy bitcoin in bitomat. when i come to home i saw two transaction, but second transaction is not my job, i don't know why this btc go out from my wallet. 

![obraz](https://user-images.githubusercontent.com/127994092/225655760-5f312bb7-c7e7-47c0-ac1a-1c3b43ad4c34.png)

What is this? i not send this.

![obraz](https://user-images.githubusercontent.com/127994092/225656499-56cff6c1-ab5b-4d29-b51f-e2cbd6b53cd7.png)

u need more information?

**Comment by SomberNight** [comment]
Either your seed or your computer probably got compromised, and hence the money stolen.

**Comment by hipsollek** [comment]
Omg, how, my comp is safe i think. Only me use this comp. Can it be unscrewed somehow?
