### ISSUE TITLE
qml invoice dialog, onchain payment, cannot click Pay while editing amount

### ISSUE THREAD

**Issue by accumulator** [spesmilo/electrum#8252]
allow click Pay while editing amount (if valid)

**Comment by ecdsa** [comment]
Another issue with the current buttons is that the user is allowed to edit the amount, even if the invoice contains an amount.
With the current GUI, I can receive a lightning invoice for a certain amount and modify that amount. I have not tested what happens if I click pay, but I guess nothing good :-)

The amount should be frozen if the invoice contains an amount, editable otherwise. There is no need for buttons that enable and disable editing.

**Comment by accumulator** [comment]
The problem is, once the amount is edited, it is stored in the invoice. So after setting an amount, it would become uneditable, even if the original invoice had no amount specified.

**Comment by ecdsa** [comment]
I don't understand what you mean...
I can still edit non-zero lightning amount after this commit: a57145117959b19c1dfdbd2a6082a1535239d5a1
it does not seem to have an effect on the saved invoice, but that is not the point. 
the point is: why would we want to let users edit that amount at all?

**Comment by accumulator** [comment]
> I can still edit non-zero lightning amount after this commit: [a571451](https://github.com/spesmilo/electrum/commit/a57145117959b19c1dfdbd2a6082a1535239d5a1) 

Yes that commit is not blocking edits, it is  a fix for _this_ issue. We should create a separate issue for your additional comment.

> it does not seem to have an effect on the saved invoice, but that is not the point. the point is: why would we want to let users edit that amount at all?

scan address, amount is unspecified. Edit amount, save invoice -> amount is fixed.

**Comment by ecdsa** [comment]
Maybe I was not clear, but I do understand that it is useful to edit amounts when no amount is specified. this is not the point...

The reason why I did not open a separate issue is, I do not see why the editing widgets are useful at all. Their purpose is to switch between editing mode and non-editing mode. But my point is that there is no reason to ever switch between those modes. Thus, I think a deeper rework of InvoiceDialog is needed, that would remove all those buttons, and probably fix all issues at once.

**Comment by accumulator** [comment]
I can remove the edit mode toggle and just present the invoice amount OR the edit mode if no amount is specified. 
However my point is what to do with the Save button. Do we just save the original invoice, or do we want to save with the user-entered amount?

**Comment by ecdsa** [comment]
we should save the entered amount if the original invoice did not have an amount.

**Comment by accumulator** [comment]
see 24a3d6e10f1722adcf5d6302258bf4b2531eb0c7
not yet saving user entered amount

**Comment by ecdsa** [comment]
> not yet saving user entered amount

I will try to fix that. any issue I should know?
