### ISSUE TITLE
QML should display Disconnected status in place of balance

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#8253]
If we are not connected to a history server, the Balance field is either empty (on startup), or it shows the balance from the previous connection (for example, if we get disconnected because we choose a new server that is offline).

The user needs to see the text "Disconnected" in relation with the red orb, in order to learn its meaning.
Otherwise, you are just assuming that they already know what it means, e.g. because they use the desktop version.

**Comment by accumulator** [comment]
was done in 64dde8bc0bde63f8b0f32fafb7607e121aeb9634

**Comment by ecdsa** [comment]
sorry, looks like I broke it in 49683d6.
this is why I opened that issue
