### ISSUE TITLE
qml: change "receive flow": prompt for amount/description before creating request

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8258]
related to discussion in https://github.com/spesmilo/electrum/issues/8254

I propose:

1. clicking the "Receive" button opens the "Edit payment request" popup, except it would be named ~"Create payment request", while still on the history screen (in the background)
    - the user can then enter an amount/description/expiration here
        - if the user cancels the popup, a payment request is not created, and they are back in the history screen
        - if the user clicks "Apply" (maybe renamed to ok/create), the payment request is created and saved, and the "Receive" screen opens
2. in the Receive screen, I think there would be no more need for the "Edit" button/functionality - once a request is created, no need to allow changing it
3. for expiration time, there should not be a "never" option
    - this would make hitting the gap limit less likely, as we reuse addresses for expired requests
4. still open question: what to do if the gap limit is hit anyway? maybe it is sufficient to show the existing "warning/create_anyway" popup...

**Comment by ecdsa** [comment]
Regarding 4 (what to do if the gap limit is hit), see #8254

**Comment by SomberNight** [comment]
note: Thomas has some work-in-progress code for this

**Comment by accumulator** [comment]
This is much better actually :+1:
