### ISSUE TITLE
Paying through RPC/CLI could be 1 sat lower than the actual payment amount.

### ISSUE THREAD

**Issue by jplix7k** [spesmilo/electrum#8274]
For example if we set ["address", 0.00033389] in the params of paytomany method. It always results in 0.00033388 btc in transaction. Through investigation, looks like it is caused by type casting from Decimal to Int in satoshis function.  (https://github.com/spesmilo/electrum/blob/master/electrum/commands.py#L86)

<img width="768" alt="image" src="https://user-images.githubusercontent.com/51077262/226845736-effd0f75-80c8-4cd4-9d68-7852b948cdb6.png">
Test shows that rounding the amount before type casting can solve this issue. Could we please add a fix for it?

**Comment by ecdsa** [comment]
I cannot reproduce this.
Here is the syntax:
`./run_electrum -o paytomany "[[\"address\",0.00033389]]" --fee 0`

**Comment by ecdsa** [comment]
rather than using round, I would suggest this:

```diff --git a/electrum/commands.py b/electrum/commands.py
index d7e1af79e..965cefed3 100644
--- a/electrum/commands.py
+++ b/electrum/commands.py
@@ -1456,7 +1456,7 @@ command_options = {
 
 # don't use floats because of rounding errors
 from .transaction import convert_raw_tx_to_hex
-json_loads = lambda x: json.loads(x, parse_float=lambda x: str(Decimal(x)))
+json_loads = lambda x: json.loads(x, parse_float=lambda x: str(Decimal(str(x))))
 arg_types = {
     'num': int,
     'nbits': int,

```

but again, I cannot reproduce your issue

**Comment by SomberNight** [comment]
I suggest amounts to be strings already on the caller side.

> For example if we set ["address", 0.00033389] in the params of paytomany method.

Just set `["address", "0.00033389"]`
Otherwise, rounding might happen at the language level before we can do anything about it.

**Comment by SomberNight** [comment]
Thanks for reporting this. Should be fixed on master now.

I still suggest using string amounts though :P (which you can also do on the latest release, as it should work around this issue)

**Comment by jplix7k** [comment]
@ecdsa @SomberNight 
Thank you for confirming and solving the issue. I'm very impressed by the efficiency. Could you please tell me roughly when the next version's release would be?

**Comment by ecdsa** [comment]
we are targeting next week for a release
