### ISSUE TITLE
When building for android: "ValueError: invalid literal for int() with base 10"

### ISSUE THREAD

**Issue by gustavklopp** [spesmilo/electrum#8284]
I am trying to build an apk for android on my arch Linux system.
After an hour of building, the build stopped with this error:
```
        File "/home/user/wspace/electrum/contrib/.venv_make_packages/lib/python3.9/site-packages/setuptools_scm/_entrypoints.py", line 40, in _call_entrypoint_fn
          return fn(root, config=config)
        File "/home/user/wspace/electrum/contrib/.venv_make_packages/lib/python3.9/site-packages/setuptools_scm/hacks.py", line 27, in parse_pkginfo
          return meta(version, preformatted=True, config=config)
        File "/home/user/wspace/electrum/contrib/.venv_make_packages/lib/python3.9/site-packages/setuptools_scm/version.py", line 229, in meta
          return ScmVersion(
        File "/home/user/wspace/electrum/contrib/.venv_make_packages/lib/python3.9/site-packages/setuptools_scm/version.py", line 141, in __init__
          date_epoch = int(os.environ["SOURCE_DATE_EPOCH"])
      ValueError: invalid literal for int() with base 10: ''
      [end of output]

× Encountered error while generating package metadata.
╰─> See above for output.
```
Thanks

**Comment by SomberNight** [comment]
What are the exact commands you run to build?

> ```
>           date_epoch = int(os.environ["SOURCE_DATE_EPOCH"])
>      ValueError: invalid literal for int() with base 10: ''
>```

Did you set that environment variable manually?
What is it set to?
`$ echo "$SOURCE_DATE_EPOCH"`

**Comment by gustavklopp** [comment]
Thanks for your help!

> What are the exact commands you run to build?
`$ ./build.sh kivy x86_64 release`
> > ```
> >           date_epoch = int(os.environ["SOURCE_DATE_EPOCH"])
> >      ValueError: invalid literal for int() with base 10: ''
> > ```
> 
> Did you set that environment variable manually? What is it set to? `$ echo "$SOURCE_DATE_EPOCH"`
No, I didn't set anything before. and I get:
```
$ echo "$SOURCE_DATE_EPOCH"

```
that is, a blank line.

**Comment by SomberNight** [comment]
Is it this line that ultimately errors?
https://github.com/spesmilo/electrum/blob/5fd6d2af4b902022f545b7324de38eee23acf018/contrib/make_packages.sh#L51-L52

if so, maybe this line a bit above errored silently?
https://github.com/spesmilo/electrum/blob/5fd6d2af4b902022f545b7324de38eee23acf018/contrib/make_packages.sh#L37

Could you put an `echo "hello there. pwd=$PWD"` at the beginning of this script, and see what that says?
You are building from a git clone, right?

**Comment by gustavklopp** [comment]
> You are building from a git clone, right?
That was it! I downloaded the zip file and this made the error.
Sorry, I didn't know it matters...
