### ISSUE TITLE
Electrum hangs when scanning for Ledger Nano S

### ISSUE THREAD

**Issue by holding06ice** [spesmilo/electrum#8293]
If I try to create a new wallet using Ledger Nano S (firmware 1.6.1, BTC app 1.4.7), Electrum 4.3.4 hangs at "Scanning devices..." If I then close BTC app on the Ledger, Electrum displays the device but I'm unable to connect to it because it's not in the correct state.

I'm able to connect to a wallet created in Electrum 4.3.2 using the Ledger. If I open this wallet in 4.3.4 I can intermittently connect to it with the Ledger, but not always. 

I suspect this may be due to #8041. Perhaps BTC app versions < 2.1.0 are not fully supported for Electrum 4.3.3+, is this the case?

**Comment by merlinana** [comment]
@holding06ice Talk to Ledger Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by SomberNight** [comment]
I have tested with a "nano s" (btc app version 1.6.3, secure element 2.0.0) on master now and cannot reproduce this.
I can create new wallets, open existing ones, and it pairs with the device OK.

Are you running from source or a binary? Which OS?

> Perhaps BTC app versions < 2.1.0 are not fully supported for Electrum 4.3.3+, is this the case?

No, they explicitly should be supported.

**Comment by holding06ice** [comment]
I'm running from the directory without installing, "./run_electrum" on Raspbian 11 (bullseye). 

Connecting with the nano s is intermittent. Usually Electrum says missing python libraries for bitbox, Jade, keepkey and safe-t (which I haven't installed), then hangs.

With an older nano s (btc app version 1.3.17, secure element 1.6.0) it will not connect at all and instead crashes with "Segmentation fault".

But these Ledgers work fine connecting to older versions of Electrum such as 4.1.4 running on Raspbian 10 (buster). 

Good to know that older versions of BTC app and firmware are still supported. Problem might be with my 4.3.2/4.3.4 setup on Debian 11 bullseye. 

Are old wallets from ~4.0.0 still supported by 4.3.4?

**Comment by SomberNight** [comment]
> Are old wallets from ~4.0.0 still supported by 4.3.4?

Yes, wallet file compatibility goes back at least to 2.0 (~2015; further back is untested).

> I'm running from the directory without installing, "./run_electrum" on Raspbian 11 (bullseye).

I assume you've seen the ["Hardware wallets on Linux"](https://github.com/spesmilo/electrum-docs/blob/0778c7c96074d8034fd510c68ff3c2d91d5433a1/hardware-linux.rst) doc file.
Are the versions of the other software dependencies such as libusb (from apt), hidapi (from pip or apt), and btchip-python (from pip or apt) consistent between your tests?

**Comment by holding06ice** [comment]
Yes, I've seen the "Hardware wallets on Linux" file. Other hardware wallets are working smoothly, only Ledger is causing trouble.

My machine is permanently air-gapped so I installed the other software dependencies such as libusb, hidapi and bitchip-python manually from individually downloaded files. After some trial and error the dependencies for 4.3.4/4.3.2 installed successfully on Debian 11 at greater than or equal to recommended versions. But the dependency versions are not all the same as in 4.1.4 on Debian 10, since dependency version requirements have advanced.

Electrum also required additional python libraries for Ledger which presumably was resolved by installing ledger-bitcoin as well. But even after installing these libraries I'm getting "Segmentation fault" and Electrum hang errors.

**Comment by SomberNight** [comment]
I think I've managed to reproduce! See if https://github.com/spesmilo/electrum/commit/33d394c9d76acceeffaa3adb032e51bed38dfe87 fixes it for you -- you can cherry-pick just that commit if needed.

I could trigger it on Linux now, but not on Windows. Turns out that I was testing with ledgercomm==1.1.0 locally on Linux, as opposed to the bundled ledgercomm==1.1.1. Version 1.1.0 has a bug that happens to mask this hanging behaviour entirely (changed in https://github.com/LedgerHQ/ledgercomm/commit/3e37fd4edb9a62753ea3448a3dc36135302ebd8e between 1.1.0 and 1.1.1), and that's why I could not reproduce. With that bug fixed, the issue surfaces:
on certain ledger devices there are two usb interfaces exposed, both picked up by hidapi, and we should only try to communicate with the `:0` one. The hang arises if we try the other one - it won't reply and we block forever.

**Comment by holding06ice** [comment]
Excellent, 33d394c fixes the hang. Thanks!
