### ISSUE TITLE
qml: reverse swap seems to be triggered multiple times

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#8295]
Not sure what happened.. 
Could it be that several swap dialogs are hanging in memory and responding to the same event?

```
04-05 09:20:47.578  3506  3547 I python  : 5963.18 | D | gui.qml.qeswaphelper | <electrum.gui.qml.qeswaphelper.QESwapHelper object at 0x6eed04f430>
04-05 09:20:47.579  3506  3547 I python  : 5963.18 | W | gui.qml.qeapp | auth using method pin
04-05 09:20:47.579  3506  3547 I python  : 5963.18 | D | gui.qml.auth | Proceeding with authed fn()
04-05 09:20:47.579  3506  3547 I python  : 5963.18 | D | gui.qml.auth | (<function QESwapHelper._do_execute_swap at 0x6ef0a4d040>, (), {}, None)
04-05 09:20:47.582  3506  3547 I python  : 5963.18 | D | gui.qml.qeswaphelper | <electrum.gui.qml.qeswaphelper.QESwapHelper object at 0x6eed04f430>
04-05 09:20:47.582  3506  3547 I python  : 5963.19 | W | gui.qml.qeapp | auth using method pin
04-05 09:20:47.583  3506  3547 I python  : 5963.19 | D | gui.qml.auth | Proceeding with authed fn()
04-05 09:20:47.584  3506  3547 I python  : 5963.19 | D | gui.qml.auth | (<function QESwapHelper._do_execute_swap at 0x6ef0a4d040>, (), {}, None)
04-05 09:20:47.589  3506  3547 I python  : 5963.19 | D | gui.qml.qewallet.[wallet_1] | wallet_updated
04-05 09:20:47.970  3506  3547 I python  : 5963.57 | D | gui.qml.qewallet.[wallet_1] | SYNC False -> True
04-05 09:20:47.987  3506  3547 I python  : 5963.59 | I | gui.qml.qewallet.[wallet_1] | Synchronizing... (269/914)
04-05 09:20:48.149  3506  3558 I python  : 5963.75 | I | storage.WalletStorage | saved /data/data/org.electrum.electrum/files/data/wallets/wallet_1
04-05 09:20:48.149  3506  3558 I python  : 5963.75 | D | util.profiler | WalletDB._write 0.1464 sec
04-05 09:20:48.150  3506  3558 I python  : 5963.75 | I | lnworker.LNWallet.[wallet_1] | pay_invoice starting session for RHASH=c0fda07cf86d552670f506c39a5399e0811aba4bca7ddd65be2e51fdd2792d7b
04-05 09:20:48.150  3506  3558 I python  : 5963.75 | D | gui.qml.qewallet.[wallet_1] | invoice status update for key c0fda07cf86d552670f506c39a5399e0811aba4bca7ddd65be2e51fdd2792d7b to 4
04-05 09:20:48.151  3506  3558 I python  : 5963.75 | I | lnworker.LNWallet.[wallet_1] | invoice status triggered (2) for key c0fda07cf86d552670f506c39a5399e0811aba4bca7ddd65be2e51fdd2792d7b and status 4
04-05 09:20:48.152  3506  3558 I python  : 5963.75 | I | lnworker.LNWallet.[wallet_1] | channels_with_funds: {(b"r'\xa2\xc9\xa8\xbbn\xb5M\xcdF>V\xdao\xe7\xd8\xe7f\xda4\x18^\xa2\xb4\xcd.\x8b\x02\xdb\xa0\xd0", b'\x03\x86N\xf0%\xfd\xe8\xfbX}\x98\x91\x86\xcejJ\x18h\x95\xeeD\xa9&\xbf\xc3p\xe2\xc3fYz?\x8f'): 1964356376}
04-05 09:20:48.154  3506  3558 I python  : 5963.76 | I | lnworker.LNWallet.[wallet_1] | suggest_split 1017089000 returned 1 configurations
--
04-05 09:20:48.901  3506  3558 I python  : 5964.50 | I | lnchannel.Channel.[7227a2c9a8bb6eb54dcd463e56da6fe7d8e766da34185ea2b4cd2e8b02dba0d0] | receive_new_commitment. ctn=2, len(htlc_sigs)=1
04-05 09:20:49.031  3506  3558 I python  : 5964.63 | I | P/lnpeer.Peer.[LNWallet, 03864ef025-a23a449e] | send_revoke_and_ack. chan 784005x1295x2. ctn: 1
04-05 09:20:49.031  3506  3558 I python  : 5964.63 | I | lnchannel.Channel.[7227a2c9a8bb6eb54dcd463e56da6fe7d8e766da34185ea2b4cd2e8b02dba0d0] | revoke_current_commitment
04-05 09:20:49.227  3506  3558 I python  : 5964.83 | I | storage.WalletStorage | saved /data/data/org.electrum.electrum/files/data/wallets/wallet_1
04-05 09:20:49.227  3506  3558 I python  : 5964.83 | D | util.profiler | WalletDB._write 0.1499 sec
04-05 09:20:49.228  3506  3558 I python  : 5964.83 | D | P/lnpeer.Peer.[LNWallet, 03864ef025-a23a449e] | Sending REVOKE_AND_ACK
04-05 09:20:49.475  3506  3547 I python  : 5965.08 | D | gui.qml.qechannellistmodel | updating our channel 784005x1295x2
04-05 09:20:49.779  3506  3558 I python  : 5965.38 | D | P/lnpeer.Peer.[LNWallet, 03864ef025-a23a449e] | Received UPDATE_FAIL_HTLC
04-05 09:20:49.780  3506  3558 I python  : 5965.38 | I | P/lnpeer.Peer.[LNWallet, 03864ef025-a23a449e] | on_update_fail_htlc. chan 784005x1295x2. htlc_id 0
04-05 09:20:49.781  3506  3558 I python  : 5965.38 | I | lnchannel.Channel.[7227a2c9a8bb6eb54dcd463e56da6fe7d8e766da34185ea2b4cd2e8b02dba0d0] | receive_fail_htlc
04-05 09:20:49.797  3506 17264 I python  : 5965.40 | E | gui.qml.qeswaphelper | rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.797  3506 17265 I python  : 5965.40 | E | gui.qml.qeswaphelper | rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.874  3506  3547 I python  : 5965.48 | D | gui.qml.qechannellistmodel | updating our channel 784005x1295x2
04-05 09:20:49.889  3506  3547 I python  : 5965.49 | W | gui.qml.qeapp | swap failed: rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.896  3506  3547 I python  : 5965.50 | W | gui.qml.qeapp | swap failed: rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.899  3506  3547 I python  : 5965.50 | W | gui.qml.qeapp | swap failed: rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.906  3506  3547 I python  : 5965.51 | W | gui.qml.qeapp | swap failed: rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.907  3506  3547 I python  : 5965.51 | W | gui.qml.qeapp | swap failed: rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.907  3506  3547 I python  : 5965.51 | W | gui.qml.qeapp | swap failed: rswap check failed: onchain_amount is less than what we expected: 1008025 < 1008174
04-05 09:20:49.911  3506  3558 I python  : 5965.51 | D | P/lnpeer.Peer.[LNWallet, 03864ef025-a23a449e] | Received COMMITMENT_SIGNED
04-05 09:20:49.911  3506  3558 I python  : 5965.51 | I | P/lnpeer.Peer.[LNWallet, 03864ef025-a23a449e] | on_commitment_signed. chan 784005x1295x2. ctn: 3.
04-05 09:20:49.911  3506  3558 I python  : 5965.51 | I | lnchannel.Channel.[7227a2c9a8bb6eb54dcd463e56da6fe7d8e766da34185ea2b4cd2e8b02dba0d0] | receive_new_commitment. ctn=3, len(htlc_sigs)=0
04-05 09:20:49.918  3506  3558 I python  : 5965.52 | I | P/lnpeer.Peer.[LNWallet, 03864ef025-a23a449e] | send_revoke_and_ack. chan 784005x1295x2. ctn: 2
```

**Comment by ecdsa** [comment]
maybe related: https://forum.qt.io/topic/46113/qml-messagebox-onyes-called-two-times-after-click

**Comment by ecdsa** [comment]
Note: `qeswaphelper._do_execute_swap` was called 3 times with the same instance (the above log is incomplete, it shows only the last 2 calls). The network received new fee estimates between the first call and the last 2. The outdated fee estimate explains why the last 2 calls failed (rswap check failed). The 2 failing calls each trigger a swapFailed event. The two swapFailed events are received by 3 SwapProgressDialogs, which explain why there are 6 lines showing`gui.qml.qeapp | swap failed: rswap check failed`

I still do not know why `_do_execute_swap` was called 3 times. It could be that the event is triggered multiple times (see above links). It is worth noting that the first call occurs several seconds the two others:
```
04-05 09:20:43.265  3506  3547 I python  : 5958.87 | D | gui.qml.qeswaphelper | <electrum.gui.qml.qeswaphelper.QESwapHelper object at 0x6eed04f430>
04-05 09:20:47.578  3506  3547 I python  : 5963.18 | D | gui.qml.qeswaphelper | <electrum.gui.qml.qeswaphelper.QESwapHelper object at 0x6eed04f430>
04-05 09:20:47.582  3506  3547 I python  : 5963.18 | D | gui.qml.qeswaphelper | <electrum.gui.qml.qeswaphelper.QESwapHelper object at 0x6eed04f430>
```

The cause could be a Qt bug like in the above links. It could also be caused by the network being likely disconnected (the log shows that it received new fee estimates and set up to date to False in the interval)

**Comment by accumulator** [comment]
added logging in e02ca6b2d896181f7b39535c80041b95226d334d so we can see if multiple instances are involved

**Comment by accumulator** [comment]
Since a single QESwapHelper instance should never be used concurrently I added a busy property that is True around an active swap session. See 5d350184a4762f343b33b328906090d6b9788053

**Comment by SomberNight** [comment]
First off, I haven't looked at this in detail, and could not reproduce it.

> Since a single QESwapHelper instance should never be used concurrently I added a busy property that is True around an active swap session. See 5d350184a4762f343b33b328906090d6b9788053
>
>> maybe related: https://forum.qt.io/topic/46113/qml-messagebox-onyes-called-two-times-after-click https://bugreports.qt.io/browse/QTBUG-91650
>
> This commit should work around these potential bugs

If there is a qt bug where some button clicks or events can get delivered multiple times, that could affect other functionality besides swaps. For example, double-paying invoices. So it would be good to have a better understanding, even if only to apply some generic hackish protection against it.

re https://github.com/spesmilo/electrum/commit/e02ca6b2d896181f7b39535c80041b95226d334d, note that BalanceDetails.qml has that duplicated:
https://github.com/spesmilo/electrum/blob/e77b0560bf1ccc5e35578e3eac619c60de8a4b08/electrum/gui/qml/components/BalanceDetails.qml#L203-L206

**Comment by ecdsa** [comment]
Notes:

1. According to the documentation, `MessageDialog` uses a native dialog on Android, iOS and MacOS, and it uses a fallback on other platforms. (https://doc.qt.io/qt-6/qml-qtquick-dialogs-messagedialog.html#availability). This means that it is probably meaningless to run the app on the desktop in order to hunt for a possible bug where the `yesClicked` event is fired multiple times.

2. I do not see any visual difference between the message dialog on Android and on Linux. Does that mean that the native dialog is not used on my phone? how does it look for you guys? 

3. If my phone is using native dialogs, and if the issue indeed comes from native dialogs, would it be possible to compile python for android in such a way that it always uses the fallback?

4. We cannot rely on calling `destroy()` to expect an object to be immediately destroyed. The documentation states that the object will be destroyed "sometime between the end of that script block and the next frame". (https://doc.qt.io/qt-6/qtqml-javascript-dynamicobjectcreation.html#deleting-objects-dynamically)

**Comment by ecdsa** [comment]
All right, I wish I had realized earlier that we have a local version of the MessageDialog code.

I was able to play with `MessageDialog`, and I can reproduce the issue if I disable the calls to `dialog.close()` in both `MessageDialog.qml` (line 64) and in `main.qml` (line 386).

Since these are event handlers, I guess that it is possible to click on the button more than once (and thus to emit multiple `yesClicked` signals) before the first signal handler is called. This is even more likely if the app has to do something else at the same time, like in my case, where it was dealing with a network disconnect and reconnect.

This is confirmed by this thread: https://stackoverflow.com/questions/65688478/how-to-prevent-qml-button-multiple-click-in-a-short-period, where a patch is proposed:

```
Button {
    onClicked: {
        if (this.enabled) {  // Don't allow multiple clicks
            console.log('clicked')
            this.enabled = false
            do_something()
            this.enabled = true
        }
    }
}
```
This patch looks good to me (without `this.enabled = true`, which is unwanted in our case), because it takes place at the earliest possible point in the event flow.

**Comment by accumulator** [comment]
It might be sufficient to remove `yesClicked` altogether and instead rely on the accept() method (which implicitly closes the dialog) and associated `accepted` signal. `yesClicked` was initially added to be able to distinguish between potentially more than just Yes and No answers, but that was eventually never needed.

Calling `close()` in the `yesClicked` event handler is redundant anyway as `MessageDialog` closes itself, so line 386 in `main.qml` should be removed anyway.

Using the default logic of `accept()/reject()` of the `Dialog` type might inhibit multiple clicks in its implementation, although I can't find this explicitly stated.

**Comment by accumulator** [comment]
Looking at the Qt code for `accept()/reject()`, there is no protection against multiple events. There is just a implicit `close()`, which for Dialogs comes down to` setVisible(false)`, which is subject to a event queue delay.

**Comment by accumulator** [comment]
> indeed, it might be possible to remove `yesClicked`. 

I was planning to do that already before this issue came up, and instead use the standard `accepted`/`rejected` system which `Dialog` already provides.

> However, if Qt has no protection against `accepted` being triggered more than once, it might make sense to use `this.enabled` with `yesClicked` as a protection against multiple events.

The problem with setting `enabled` to false is that it overwrites a property binding that maybe was set on it. That's probably fine in most cases, unless a dialog instance is re-used or lives longer than this single interaction. Downside is that we have to repeat this line every time before calling accept(), which might be forgotten in future commits.

Instead of setting `enabled` to false, I've added a generic solution in `ElDialog` that ensures a single `accepted`/`rejected` signal. See a0939aad753e212064645be3bc3171cb1f50829a

**Comment by sueliitj** [comment]
Ok

**Comment by ecdsa** [comment]
> We can destroy `swaphelper` from python once a swap operation finishes, although we can then not access any state in `swaphelper` from the `swapFailed`/`swapSuccess` signal handlers, as `swaphelper` is destroyed. The associated `SwapDialog` should be destroyed too at that point.

Why wait until the swap operation finishes? Those events (swapFailed and swapSuccess) are only used in SwapDialog and SwapProgessDialog. We could get rid of the `swaphelper` when both dialogs are closed, because those events are not going to be handled anymore. From a UX perspective, I think it would be nice to consolidate SwapDialog and SwapProgressDialog into a single dialog; there is no real reason to take the user to a new screen when the swap is initiated, and it obscures the amount of the ongoing swap.

**Comment by accumulator** [comment]
swaphelper is already freed after swap since b0778d0281858614b8bb3267827490d0c3168495
