### ISSUE TITLE
[FR] option to exclude frozen address balances from main balance or show separately

### ISSUE THREAD

**Issue by ITwrx** [spesmilo/electrum#8296]
The ability to freeze addresses is nice for a pseudo savings account, but right now, frozen addresses' balances are still included in the main/only balance. This just causes you to not know how much "spending money" you really have until you figure it out the hard way. :) It would be nice if frozen balances were segregated in some way.  The simplest might be to show `spendable/frozen/total` or something like that.

thanks

**Comment by SomberNight** [comment]
Have you you tried clicking your balance in the bottom left corner (assuming you use the Qt gui)? It should enlarge the pie chart (in a new dialog) and include such a breakdown there.

**Comment by ITwrx** [comment]
whoops! i didn't think that was clickable and never tried. that pie chart should be good enough. thanks!
