### ISSUE TITLE
missing list in new android qml

### ISSUE THREAD

**Issue by pony-montana** [spesmilo/electrum#8303]
Hi, testing the new android qml app I feel very optimistic about it! By my point of view, the most notably missing feature to make it really usable are:

1) Possibility to freeze single UTXO to achieve full coin control.
2) Possibility for the user to insert a custom sat/vbyte fee when making transactions.
3) Fix the strange touch behaviour in address list section and also present in other sections (to replicate it, try to exit from address list section using the android "back" gesture).
4) Possibility to copy addresses from transaction details (in general, expand the possibility to copy data from every section that could be useful for user).

I tested only on-chain, not lightning yet.

For the future, also make possible to do PSBT with seedsigner will be great, but it is something that is discussed in other issues.

**Comment by accumulator** [comment]
Thank you for testing and providing feedback. 

>     1. Possibility to freeze single UTXO to achieve full coin control.

Yes, expanding on the current Addresses view with filtering, search, Coins (UTXOs) and per-address history is planned after the next release, as well as the privacy analysis tools that are already implemented for the desktop version.

>     2. Possibility for the user to insert a custom sat/vbyte fee when making transactions.

Planned after the next release.

>     3. Fix the strange touch behaviour in address list section and also present in other sections (to replicate it, try to exit from address list section using the android "back" gesture).

We haven't tested gestures yet. There might be limitations of Qt here, but we'll look into it.

>     4. Possibility to copy addresses from transaction details (in general, expand the possibility to copy data from every section that could be useful for user).

More technical details will be added to transaction details after the next release.

**Comment by pony-montana** [comment]
2 over 4 of the feature requests has been completed, so I'm closing this issue and creating two separate new issues for the remaining enanchements (coin control and custom fees)
