### ISSUE TITLE
Localization issue: "Share" as verb vs as noun

### ISSUE THREAD

**Issue by lionkmp** [spesmilo/electrum#8314]
Word "Share" is translated as one localization string for these appearances:

Key: Share
#: electrum/gui/qt/transaction_dialog.py:470 electrum/slip39.py:300
#: electrum/slip39.py:304

But (AS I UNDERSTAND) in regards so the Slip39, this is a noun, refers to a share of the seed (a part of it basically), while on the transaction_dialog this refers to sharing something (QR or URL maybe, I didn't dig this yet).

These two cases (noun vs. verb) require different word in some languages, including my language, Hungarian.

Can you please make two separated strings? Thanks in advance!

**Comment by SomberNight** [comment]
I am not quite sure how to introduce such a verb/noun distinction to translations.
It might be possible with [`pgettext`](https://docs.python.org/3/library/gettext.html#gettext.pgettext) or `dgettext`, I don't know.

Instead, I've changed how the strings are constructed there.
See if https://github.com/spesmilo/electrum/commit/cbb4c3ceb2771c33de1633644d77601ee18a11f7 looks good.

**Comment by lionkmp** [comment]
That's perfect, thank you. This is how all strings would be best, that are made up from parts.

One little improvement would be if Python supports indexed variables, so that instead of "{} and {} and {}" there could be "{1} and {2} and {3}". There was one string, where I wanted to change order of two values for better grammar of the translation - but I could not. Managed it this way, so it's OK for now. But other languages may also have problem, especially if there are 3 variables.
