### ISSUE TITLE
Support external pre-signed inputs on Trezor

### ISSUE THREAD

**Issue by matejcik** [spesmilo/electrum#8324]
It is currently not possible to use Trezor to sign a partial transaction where some inputs come pre-signed.

steps to reproduce:
1. set up an Electrum wallet from Trezor, and another one with hot seed
2. in the Trezor-based wallet, generate a transaction, finalize it but do not sign, Export -> For HWW
3. in the hot wallet, generate a transaction, Combine -> Inputs / outputs
4. paste result from step 2
5. sign transaction
6. back in Trezor-based wallet, Load transaction from text, paste result of step 5
7. try to sign the transaction

This is the [error](https://github.com/spesmilo/electrum/blob/1a4e48e2d4799579d1f5fd7ba39e0f27537ed185/electrum/plugins/trezor/trezor.py#L335): `unexpected txin type: unknown`.

coming from `tx_inputs` line 418: https://github.com/spesmilo/electrum/blob/1a4e48e2d4799579d1f5fd7ba39e0f27537ed185/electrum/plugins/trezor/trezor.py#L418

(don't have the actual traceback on me, sorry.)

What I _guess_ is happening is, Electrum loads the previously signed transaction and does not know how to stream the signed inputs into Trezor.

It is necessary to specify script type `EXTERNAL`, and provide the `script_sig`

**Comment by SomberNight** [comment]
I had a look at this. Could you please review https://github.com/spesmilo/electrum/pull/8483 ?
I reproduced your example with a model T, fw 2.6.0, and it seems to work. Before updating the firmware, with fw version 2.1.x, I was getting an error on the device, but I guess that's ~ok.

**Comment by matejcik** [comment]
> with fw version 2.1.x, I was getting an error on the device, but I guess that's ~ok.

Yes, that's very old and the EXTERNAL script type is not supported there. I wouldn't worry about it.

**Comment by hynek-jina** [comment]
@SomberNight Will this be included in 4.4.6?
I don't see it in [release notes](https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES) 😞

**Comment by SomberNight** [comment]
No, sorry, it was apparently not cherry-picked. 4.4.6 is already tagged and will be released very soon.

**Comment by hynek-jina** [comment]
Yes, but for this feature I need 4.4.7, right? And it isn't there.

**Comment by SomberNight** [comment]
The CI builds binaries for Linux and Windows (though not for macOS). You can grab a build for master. E.g. https://cirrus-ci.com/task/6327841411825664
Alternatively, you can run from source or build your own binaries.
