### ISSUE TITLE
qml: add option to show onchain address in ReceiveDetailsDialog

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8331]
In qml, when creating a receive request, there is no way to inspect the corresponding on-chain address (as text). Only a QR code is shown. If the user wants the address as text, they use the "Copy" button, but the text itself is not shown in-app.
Just consider the at-one-point-prevalent-on-desktop clipboard malware: the address we copy on to the clipboard and then paste somewhere else might be hijacked.

-----

<details>
 <summary>qml pic</summary>

![pic3](https://user-images.githubusercontent.com/29142493/233704038-67405cbf-9160-4536-8aae-4809f4d5c559.png)
</details>

-----

In kivy, clicking the QR code switched to show the text instead:

<details>
 <summary>kivy pics</summary>

![pic1](https://user-images.githubusercontent.com/29142493/233704044-106b6aed-39a1-4e02-9ced-a160b944023f.png)
![pic2](https://user-images.githubusercontent.com/29142493/233704048-0c11e0bf-d92e-4dd6-8bb4-22f8d686f6ab.png)
</details>

(in qml, clicking the QR code atm is another redundant way to cycle through Lightning/URI/Address)

-----

I think we could reintroduce the same UX that kivy had here: clicking the QR code shows the text, clicking the text shows the QR code again. No need to make the text selectable/etc, as the dedicated "Copy" button would still be there at the bottom.

**Comment by ecdsa** [comment]
related: https://twitter.com/ElectrumWallet/status/1649377046009716737

**Comment by SomberNight** [comment]
Done, in a barebones way, in https://github.com/spesmilo/electrum/commit/22fa84a0d51471f30fabd4a4dbb9936dc6a057a0
Feel free to improve on the visuals :P
