### ISSUE TITLE
Read QR from camera doesn't seem to work anymore in last version 4.4.0

### ISSUE THREAD

**Issue by razimih** [spesmilo/electrum#8342]
The Read QR Code with camera gives:

**TypeError("QDialog(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 'parent' has unexpected type 'PayToEdit'")**

on Windows 11
This worked OK in previous version.
Thanks

**Comment by SomberNight** [comment]
Thanks for the report.
Should be fixed on master now.
