### ISSUE TITLE
android: not possible to paste long text due to virtualkeyboard (e.g. password from external pw manager, onion address)

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8352]
On Android (qml), as we use the in-app qt virtualkeyboard (https://github.com/spesmilo/electrum/pull/8275), it is not possible to copy-paste in text fields.
It is by design that the user should not be able to copy-paste the seed (https://github.com/spesmilo/electrum/issues/8256), however unfortunately this also prevents users from pasting from an external password manager app into the wallet password field to unlock their wallet.

Not sure if there is a workaround while still using the qt virtualkeyboard... if not, perhaps we should consider dropping the virtualkeyboard and just implementing our own keyboard widget exclusively for entering seeds (like it worked in kivy).

**Comment by prescot-ww** [comment]
Also you can't paste the TOR server address to link the wallet to my personal node.
You can't expect from users to type a very long tor address (56  characters for .onion v3).

**Comment by accumulator** [comment]
Apparently nobody noticed, but yeah this is horrible. I agree, we should remove the vkbd.

**Comment by SomberNight** [comment]
Another option would be to add explicit "paste" buttons near text fields where we expect it to be useful, such as the wallet-password, or electrum server hostname, proxy fields, etc.

But to be honest, I think it might be best to just use the system kb everywhere except the seed entry screen. The original motivation of the vkbd was to secure (and restrict what is possible on) just that screen, so let's just do that. And I think it's fine to only have the latin alphabet for seeds. It worked like that for years anyway. It would be great if it was possible to use the qt virtualkeyboard selectively just on some screens :/

**Comment by accumulator** [comment]
merged #8372, closing
