### ISSUE TITLE
not able to sign message using bitcoin address (Ledger)

### ISSUE THREAD

**Issue by rieseflo** [spesmilo/electrum#8364]
When trying to sign a message with my bitcoin address using Electrum the error "invalid literal for int() with base 10: '84h' appears. Are there any other possibilites to sign a message using a ledger? Or is there a possible way to fix this?

**Comment by SomberNight** [comment]
This is already fixed on master in https://github.com/spesmilo/electrum/commit/499f51535ffa54607fd75eb4bf817cb96bd0e0cd but not released yet.

For the time being, as a workaround, you can try using Electrum version 4.3.4.
