### ISSUE TITLE
cannot open older wallets and make new wallets in 4.4.0 and 4.4.1

### ISSUE THREAD

**Issue by JessieRaspi** [spesmilo/electrum#8367]
The problem occurred first after update to 4.4.0. I couldn't open my walletfiles in 4.4.0. I couldn't find a solution, so I downgraded to 4.3.4, but then I couldn't open the walletfiles that I had tried to open in 4.4.0. So I had to use my backup walletfiles. 

I hoped, the problem was fixed with 4.4.1. 

Before the update to 4.4.1, I now first made a testwallet in 4.3.4 and after that, updated Electrum to 4.4.1 and then tried to open the wallet in 4.4.1. 

I get the following message":
_Cannot load wallet(2) :
TypeError("setChecked(self, bool): argument 1 has unexpected type 'str'")_

I also tried to make a new wallet in 4.4.1, but that didn't succeed either.

I removed the update, did a downgrade again to 4.3.4 and tried to open the testwallet I made earlier in 4.3.4. , but then got this message:
_Cannot load wallet (1):
WalletFileException('This version of Electrum is too old to open this wallet.\n(highest supported storage version: 50, version of this file: 51)')_
Apparently there were made changes in that walletfile while trying to open it in 4.4.1.

Now I removed the update and downgraded to 4.3.4 again and everything is working smoothly.

I wonder what the problem could be and how to solve it, I never encountered this. 

I'm on Windows 10, use Electrum with and  without hardware wallet and I have it connected to my own node (Raspiblitz with Electrs).

**Comment by ecdsa** [comment]
thanks for the report. Are there more traceback lines preceding
` TypeError("setChecked(self, bool): argument 1 has unexpected type 'str'")`

**Comment by SomberNight** [comment]
IIRC the GUI error dialog only shows the last line of the trace (i.e. only the exception). However, the full trace is logged.

@JessieRaspi Please include debug logs, or at least the full traceback as found in the debug logs.
See here: https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging

(Btw, I would guess it's a config var having the wrong type)

**Comment by JessieRaspi** [comment]
Herewith the log you have asked for. I installed 4.4.1 again, but failed to make a new wallet in 4.4.1, so couldn't open Electrum. 

There are two wallets in the log. Both failed, the first one because I made an error in retyping the seed, for the other one I could retype the seed, but failed to open the wallet.

20230429T142611.434334Z |    ERROR | gui.qt.ElectrumGui | 
Traceback (most recent call last):
  File "electrum\gui\qt\__init__.py", line 365, in start_new_window
  File "electrum\gui\qt\__init__.py", line 305, in _create_window_for_wallet
  File "electrum\gui\qt\main_window.py", line 215, in __init__
  File "electrum\gui\qt\main_window.py", line 1036, in create_history_tab
  File "electrum\gui\qt\main_window.py", line 1338, in create_list_tab
  File "electrum\gui\qt\history_list.py", line 553, in create_toolbar
  File "electrum\gui\qt\my_treeview.py", line 86, in addConfig
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "electrum\gui\qt\__init__.py", line 365, in start_new_window
  File "electrum\gui\qt\__init__.py", line 305, in _create_window_for_wallet
  File "electrum\gui\qt\main_window.py", line 215, in __init__
  File "electrum\gui\qt\main_window.py", line 1036, in create_history_tab
  File "electrum\gui\qt\main_window.py", line 1338, in create_list_tab
  File "electrum\gui\qt\history_list.py", line 553, in create_toolbar
  File "electrum\gui\qt\my_treeview.py", line 86, in addConfig
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
20230429T142612.774340Z |     INFO | storage.WalletStorage | saved c:\users\xxxxx\appdata\roaming\electrum\wallets\testwallet new in 441
20230429T142612.774340Z |    DEBUG | util.profiler | WalletDB._write 0.0801 sec
20230429T142612.774340Z |     INFO | wallet.Standard_Wallet.[testwallet new in 441] | set_up_to_date: True
20230429T142626.785804Z |     INFO | network | fee_histogram [[2047, 220], [1023, 550], [511, 748], [255, 8435], [127, 27067], [63, 991562], [31, 1348888], [15, 4533113], [7, 16471101], [3, 24877914], [1, 30911], [0, 0]]
20230429T142649.623914Z |     INFO | exchange_rate.CoinGecko | getting fx quotes for EUR
20230429T142649.746303Z |     INFO | exchange_rate.CoinGecko | received fx quotes
20230429T142700.316235Z |     INFO | daemon.Daemon | stop() entered. initiating shutdown
20230429T142700.316235Z |     INFO | gui.qt.ElectrumGui | closing GUI
20230429T142700.316235Z |     INFO | daemon.Daemon | stopping all wallets
20230429T142700.317235Z |     INFO | lnworker.LNWallet.[testwallet github] | taskgroup stopped.
20230429T142700.317235Z |     INFO | lnworker.LNWallet.[testwallet new in 441] | taskgroup stopped.
20230429T142700.318235Z |     INFO | wallet.Standard_Wallet.[testwallet github] | taskgroup stopped.
20230429T142700.372202Z |     INFO | storage.WalletStorage | saved c:\users\xxxxxx\appdata\roaming\electrum\wallets\testwallet github
20230429T142700.372202Z |    DEBUG | util.profiler | WalletDB._write 0.0520 sec
20230429T142700.373201Z |     INFO | wallet.Standard_Wallet.[testwallet new in 441] | taskgroup stopped.
20230429T142700.410181Z |     INFO | storage.WalletStorage | saved c:\users\xxxxx\appdata\roaming\electrum\wallets\testwallet new in 441
20230429T142700.410181Z |    DEBUG | util.profiler | WalletDB._write 0.0370 sec
20230429T142700.410181Z |     INFO | daemon.Daemon | stopping network and taskgroup
20230429T142700.411195Z |     INFO | network | stopping network
20230429T142700.411195Z |     INFO | daemon.Daemon | taskgroup stopped.
20230429T142700.460064Z |     INFO | interface.[192.xxx.xxx.xxx:50002] | disconnecting due to: CancelledError()
20230429T142700.460064Z |     INFO | network | taskgroup stopped (0x520b2b0).
20230429T142700.460064Z |     INFO | daemon.Daemon | removing lockfile
20230429T142700.470053Z |     INFO | daemon.Daemon | stopped
20230429T142700.492051Z |     INFO | plugin.Plugins | stopped

**Comment by accumulator** [comment]
It looks like somehow there's an unexpected value ending up in your config file (not wallet file). Can you try to toggle (at least once) Preferences > Fiat > Download historical rates and see if that helps?

**Comment by JessieRaspi** [comment]
Yes! Solved! Thanks a lot!

**Comment by SomberNight** [comment]
Any idea how this happened though?
I think I will resurrect https://github.com/spesmilo/electrum/pull/5649 soon and add some generic protection against this...

**Comment by SomberNight** [comment]
should be fixed in https://github.com/spesmilo/electrum/commit/3bdda3a8616fff8a1d53c4168e54a688f4961994
