### ISSUE TITLE
docker build is not working

### ISSUE THREAD

**Issue by mohammadrafigh** [spesmilo/electrum#8370]
Docker build is not working for v4.4.1 at `RUN apt update -qq > /dev/null && apt install -qq --yes --no-install-recommends --allow-downgrades     locales &&     locale-gen en_US.UTF-8` with this error:

```
#0 60.72 Package locales is not available, but is referred to by another package.
#0 60.72 This may mean that the package is missing, has been obsoleted, or
#0 60.72 is only available from another source
#0 60.72 
#0 60.72 E: Package 'locales' has no installation candidate
```

**Comment by accumulator** [comment]
This is probably a temporary issue. The repository we use for the docker container is throttled and can sometimes reject connections.

**Comment by mohammadrafigh** [comment]
You are right about that step, It's now passed but still there are more errors at next step:

```
docker run -it --rm --name electrum-android-builder-cont --volume /tmp/test_org.electrum.electrum/app:/home/user/wspace/electrum --volume /tmp/test_org.electrum.electrum/app/.buildozer/.gradle:/home/user/.gradle --workdir /home/user/wspace/electrum electrum-android-builder-img /bin/bash -c './contrib/android/make_apk kivy all release-unsigned;
        echo "CTRL-D to continue";
  bash'
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: line 1: ./contrib/android/make_apk: No such file or directory
CTRL-D to continue
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

The interesting line might be `/bin/bash: line 1: ./contrib/android/make_apk: No such file or directory`

**Comment by SomberNight** [comment]
I don't know what you are doing but `make_apk` [was renamed](https://github.com/spesmilo/electrum/commit/1cecd2c6e89941e1afbea734118d088762ea82f3) to `make_apk.sh` 7 months ago. Looking at your copied commands, you have custom modifications, which is fine, but then please keep them up-to-date and check for upstream changes *before* asking for help.

**Comment by mohammadrafigh** [comment]
@SomberNight ouch I didn't notice that. Thanks for your help. Actually we are doing reproducibility tests for a lot of wallets, so we sometimes miss things like this.
