### ISSUE TITLE
Can't open my Multisig wallet after updating to newest Electrum version.

### ISSUE THREAD

**Issue by Szpoti** [spesmilo/electrum#8380]
I have a 3-2 multisig wallet that I used with Bitcoin Core & Electrum Personal Server for a long time. Now after half a year, I redid everything like before:
- Started BItcoin Core(0.17.1), waited for sync.
- Started Electrum Personal Server(0.1.7), waited to sync.
- Started Electrum(3.3.8).

I was able to open the wallet, but my Electrum couldn't connect to the personal server due to `OSError: IOError`.
So I updated everything to the latest stable version. Still the same error on the personal server, but now my Electrum throws the following error when I try to open my wallet:
```
Cannot load wallet(2) :
TypeError('fromhex() argument must be str, not None')
```

When I tried to downgrade Electrum back to 3.3.8,it said that the wallet version is too new to open in old version.
What Can I do to this error?

**Comment by SomberNight** [comment]
> ```
> Cannot load wallet(2) :
> TypeError('fromhex() argument must be str, not None')
> ```

You will find a full traceback in the logs for this error, please share that.
See https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by accumulator** [comment]
old wallet version and we don't have relevant logs. Closing. Feel free to re-open if you think it's relevant to current version.
