### ISSUE TITLE
Flaws in the v4.4.2 for android

### ISSUE THREAD

**Issue by ik105** [spesmilo/electrum#8392]
In version 4.4.2 for android, there is no option to enter a passphrase when restoring a wallet. 

It is also no longer possible to enter a seed phrase created with a custom dictionary. 

The virtual keyboard has very small font and no backspace key. 

Hopefully this will be fixed in the next versions, but for now I'm going back to the previous one.

**Comment by SomberNight** [comment]
![pic](https://user-images.githubusercontent.com/29142493/236439500-59f4fe14-6f71-45bd-abab-1ba8544afa37.png)

> there is no option to enter a passphrase when restoring a wallet.

> The virtual keyboard has [...] no backspace key.

Do I need to put red circles in the image?

-----

> The virtual keyboard has very small font 

well, ok, maybe they could be increased a tiny-tiny bit more, but there is not much space... what are you comparing against? The keys in 4.4.1 on the qt virtual keyboard were roughly the same size.

> It is also no longer possible to enter a seed phrase created with a custom dictionary.

Indeed and this has *always* been the case except for 4.4.0 and 4.4.1. What is your use case?

**Comment by ik105** [comment]
> Do I need to put red circles in the image?

No, I can see that now. I just didn't realise that I had to scroll the screen, otherwise I can't see the bottom of the screen. It wasn't required before.

> well, ok, maybe they could be increased a tiny-tiny bit more, but there is not much space... what are you comparing against? The keys in 4.4.1 on the qt virtual keyboard were roughly the same size.

The size of the buttons could remain the same, just make the font larger, as it was before.

> Indeed and this has always been the case except for 4.4.0 and 4.4.1.

Yes, I know. I missed it, and I was glad when it became possible here.

**Comment by SomberNight** [comment]
I think most of these are fixed in later versions (atm latest is 4.5.0), except for:

> It is also no longer possible to enter a seed phrase created with a custom dictionary.

As said already, this was ~never really possible. If you really want this feature, open a new issue for it and state your use case(s).
