### ISSUE TITLE
"Wallet not loaded"

### ISSUE THREAD

**Issue by iamwasabi** [spesmilo/electrum#8394]
Hello, 
I'm trying to get the balance via RPC.

curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"getbalance","params":{}' http://user:pass==@127.0.0.1:7777

I've tried EVERYthing. From CLI electrum load_wallet -w path (returning true)
to method:"load_wallet" with the path, returning true.

But when I run, 
curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"getbalance","params":{}' http://user:pass==@127.0.0.1:7777

No matter what. 
I'll get "Wallet not loaded".

Is there something I'm missing here?

**Comment by SomberNight** [comment]
In addition to running load_wallet (either via RPC or CLI), you then also need to specify which wallet to use to every command you run.

I haven't tested, but try something like this:
```
curl --data-binary '{"jsonrpc":"2.0","id":"curltext","method":"getbalance","params":{"wallet":"~/.electrum/testnet/wallets/test_segwit_2"}' http://user:pass==@127.0.0.1:7777
```
