### ISSUE TITLE
Seed words not visible in 2fa wallet details

### ISSUE THREAD

**Issue by Barracuda116** [spesmilo/electrum#8400]
How to find out the seed phrase on a wallet installed on android? Wallet version 4.4.2.0.  it's not in the settings. I don't remember it.

**Comment by SomberNight** [comment]
Tap wallet name on top > `Wallet details`. Then there should be a field showing the seed (or the text `Tap to show seed`).

If it's not there, what kind of wallet do you have? In `Wallet details`, there are badges/icons near the top. What badges do you see?

**Comment by Barracuda116** [comment]
![1683377233202](https://user-images.githubusercontent.com/132566147/236625041-add4460c-aec4-4698-bc84-98edc3f2346f.jpg)

**Comment by Barracuda116** [comment]
![1683377411270](https://user-images.githubusercontent.com/132566147/236625255-cb0e3c5b-5289-449b-af81-eba176a6287b.jpg)

**Comment by Barracuda116** [comment]
![Uploading 1683377392961.jpg…]()

**Comment by Barracuda116** [comment]
![1683377375438](https://user-images.githubusercontent.com/132566147/236625280-4637f599-edec-4350-97e0-b95d75fb5cd2.jpg)

**Comment by SomberNight** [comment]
Open your wallet, so e.g. you see its history, then tap top-left, go into `Wallet details`, and say what badges are listed at the top.

**Comment by Barracuda116** [comment]
Wallet details
Addresses 
Canals
Other wallets

**Comment by Barracuda116** [comment]
![1683377867856](https://user-images.githubusercontent.com/132566147/236625637-137dcd62-3266-49ad-b750-a9054a46fe6a.jpg)

**Comment by SomberNight** [comment]
Ah ok, so you have a 2fa wallet. Well that's why. The seed is not stored in the wallet file, as with the seed alone all your coins can be spent and 2fa circumvented. If you have lost/forgotten the seed words and don't have it backed up anywhere, I suggest you create a new wallet and move your coins. The new wallet can also be 2fa, or it can be a standard wallet too, whatever you like.

**Comment by Barracuda116** [comment]
How do I move my coins to a new wallet?
