### ISSUE TITLE
Can't create 2-of-2 multisig wallet on Android

### ISSUE THREAD

**Issue by jfitie** [spesmilo/electrum#8415]
Android version 4.4.2

Reproduce bug as follows:
 Stop app/clear data
 Open app. No Tor, auto connect
 Create new wallet, 2-of-2 multisig
 1st key: Enter a valid Electrum Segwit seed
 2nd key: Enter a valid public key

Behaviour:
 No wallet created, button on screen to create new wallet

Expected behaviour:
 Multisig wallet file created and opened

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by SomberNight** [comment]
Seems to be working for me (can't reproduce).

>  1st key: Enter a valid Electrum Segwit seed
2nd key: Enter a valid public key

I am testing with:
cosigner1: `title burst cute horn hand march gravity abandon extra rotate ski wreck`
cosigner2: `Zpub6vZyhw1ShkEwNgMJutvLdYQ4J2ziGXbjiTdXHGdNaawrbbQiHApueJ5M5BXHJSbejB69VmGC26XRdsGgdV2MLqczCYSheFJucocgDtcDvds`
(these don't have money on them; don't write your real seed/xpub here)

>  2nd key: Enter a valid public key

What kind of thing are you providing there? Is it a "Zpub"-typed master public key like in my example?

-----

It is possible to get debug logs from the device:
- in the app, go into "Preferences", check "Enable debug logs" at the bottom
- in Android (the OS), enable "developer mode", and enable "USB debugging"
- connect phone to PC via USB cable
- install `adb` (android debug bridge) on PC
- `$ adb logcat | grep python`

I think there should be an exception trace in the debug logs.

**Comment by jfitie** [comment]
With my own seed (12 word Segwit, Electrum) and, indeed, Zpub master public key I can still reproduce the issue as described above. With the seed and mpk posted in your reply the wallet file gets generated and opened correctly and the issue cannot be reproduced. I will try and see what causes this, and why there is a difference between both similar cases.

**Comment by SomberNight** [comment]
Can you try and see, with the same seed and Zpub, whether you can create a wallet in the desktop app (Qt GUI)?

**Comment by SomberNight** [comment]
One way to reproduce is with duplicate cosigners: enter seed for cosigner 1, and enter Zpub of same seed for cosigner 2.

electrum 4.5.0 shows some error text at the bottom for such a case,  "Error: duplicate master public key". I don't remember how far back this error text was added though.
