### ISSUE TITLE
Command line option "-v verbosity" not described

### ISSUE THREAD

**Issue by de-served** [spesmilo/electrum#8424]
electrum-4.4.2-portable.exe -v needs "verbosity level" but help is not clear which types/numbers can be used.
Foun "\*" in sources (if verbosity == '\*' or not isinstance(verbosity, str): in logging.py), tried to use this - it didn't work.
Update sources to be clear.

**Comment by SomberNight** [comment]
You can just set `-v`, which will be mapped onto `-v=*`, as in previous versions.

Your issue is likely simply that stdout/stderr do not work with the windows binaries. See https://github.com/spesmilo/electrum/issues/2592

**Comment by SomberNight** [comment]
also https://github.com/spesmilo/electrum/issues/8425#issuecomment-1549575997
