### ISSUE TITLE
Can't start daemon or communicate with started (python), electrum-4.4.3(-portable).exe

### ISSUE THREAD

**Issue by de-served** [spesmilo/electrum#8425]
```
    process = subprocess.Popen(f"{electrum_path} -v getinfo", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, errors = process.communicate()
    print(output.decode("utf-8"))
```
-> "Daemon not running"
next lines:
```
        process = subprocess.Popen(f"{electrum_path} -v daemon -d", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = process.communicate()
        print(output.decode("utf-8"))
```
-> "Daemon already running (lockfile detected). Run 'electrum stop' to stop the daemon."

"-v" option didn't work, "-v \*" option didn't work.
Which lockfile? Where? Can't find anything. No running processes electrum-4.4.2-portable.exe in memory

There are much harder problems, more digging at #8429

Windows 10, py3.11

**Comment by desirepl** [comment]
There is much harder problems. More digging at #8429

**Comment by SomberNight** [comment]
Running the official release .exe binaries on Windows in non-GUI mode is basically not supported.
stdout/stderr do not work with the windows binaries. See https://github.com/spesmilo/electrum/issues/2592

You should either run from python sources, or build your own exe with the `console=True` option, or use the bundled [`-debug` exe](https://github.com/spesmilo/electrum/issues/2592#issuecomment-985466861) provided [as part of the `-setup exe`](https://github.com/spesmilo/electrum/pull/6603) (installer).

Further, running as daemon is only supported in non-detached (foreground) mode (see https://github.com/spesmilo/electrum/issues/5511#issuecomment-1549571984).
