### ISSUE TITLE
Ignored commandline options -w, -D, --dir, -v. Absolutely unusable wallet software in commandline/scripts (GUI works)

### ISSUE THREAD

**Issue by de-served** [spesmilo/electrum#8429]
1. [For example] two directories exists:
1.1) D:\Test1\Electrum\electrum_data
1.2) D:\Test2\Electrum\electrum_data
2. There are directories "wallets" in both 1.1 and 1.2 
3. There are "electrum_wallet" files inside both 2's. They have 1 WIF-key/address inside and works ok in GUI mode.
4. There are "electrum-4.4.3-portable.exe" inside D:\Test1\Electrum and D:\Test2\Electrum.
5. There are "electrum-4.4.3.exe" ("standalone") inside D:\Test1\Electrum and D:\Test2\Electrum.

Begin of testing:
-1-
```
cd D:\Test1\Electrum
electrum-4.4.3-portable.exe daemon
```
Result: 2 processes electrum-4.4.3-portable.exe started - parent and child. (Second exists possible because of "portable". Just a guess, no matter now)

-2- ***ERROR***
`electrum-4.4.3-portable.exe getinfo`
Result: just one (or two) blank line written to console, nothing more.

-3-
`electrum-4.4.3-portable.exe getinfo>status.txt`
Result: status.txt written, seems ok for now, some lines of the answer:
```
    "blockchain_height": 789745,
    "default_wallet": "D:\\Test1\\Electrum\\electrum_data\\wallets\\default_wallet",
    "network": "mainnet",
    "version": "4.4.3"
```

-4-
`electrum-4.4.3-portable.exe getbalance>status.txt`
Result: "Error: Wallet file not found." in status.txt. Seems ok, because "default_wallet" in -3-.

-5- ***ERROR***
`electrum-4.4.3-portable.exe daemon stop` (or just `electrum-4.4.3-portable.exe stop` as said in https://electrum.readthedocs.io/en/latest/cmdline.html)
Result: two new processes spawned for a moment and closed. Two processes created after -1- is not closed.
UPDATE:
```
start electrum-4.4.3.exe daemon
[wait until 2 processes raised]
electrum-4.4.3.exe getinfo>2_getinfo.txt
electrum-4.4.3.exe stop>3_stop.txt
```
This combination works: "Daemon stopped".

-6- ***ERROR***
`electrum-4.4.3-portable.exe daemon stop>status.txt`
Result: same as -5-, but "status.txt" is 0 bytes now.

-7-
Killing two processes made in -1-.
```
electrum-4.4.3-portable.exe -w D:/Test2/Electrum/electrum_data/wallets/electrum_wallet daemon
electrum-4.4.3-portable.exe getinfo>status.txt
```
Result (no matter "-w=" or "-w " - result the same):
```
    "default_wallet": "D:/Test2/Electrum/electrum_data/wallets/electrum_wallet",
    "network": "mainnet",
    "path": "D:\\Test1\\Electrum\\electrum_data",
```

-8- ***ERROR***
`electrum-4.4.3-portable.exe importprivkey SOMEWIFKEY>status.txt`
Result: "Error: *Wallet file not found*." in status.txt.
Process is trying to search D:\\Test1\\Electrum\\electrum_data\\wallets\\default_wallet (used Sysinternals Process Monitor to see it) and ignores that daemon is started with forced external wallet file.

-9- ***ERROR***
`electrum-4.4.3-portable.exe -w D:/Test2/Electrum/electrum_data/wallets/electrum_wallet importprivkey SOMEWIFKEY>status.txt`
Result: the same as in -8-, Electrum is ignoring wallet forced in daemon and ignored current "-w" in commandline.

-10- ***ERROR***
Killing two processes again.
```
electrum-4.4.3-portable.exe -w=D:/Test2/Electrum/electrum_data/wallets/electrum_wallet -D=D:/Test2/Electrum/electrum_data daemon
electrum-4.4.3-portable.exe getinfo>status.txt
```
Result (no matter "-w=" or "-w ", "-D=" or "-D ", "--dir=" or "--dir " - result the same):
```
    "default_wallet": "D:/Test2/Electrum/electrum_data/wallets/electrum_wallet",
    "network": "mainnet",
    "path": "D:\\Test1\\Electrum\\electrum_data",
```
Electrum totally ignores -D or --dir option.

Let's try not "portable" but standalone, maybe there are problem just with portable?
-11-
```
cd D:\Test1\Electrum
electrum-4.4.3.exe daemon
```
Result: 2 processes electrum-4.4.3.exe started - parent and child. (a guess that second process is because of "portable" is now destroyed)

-12- ***ERROR***
`electrum-4.4.3.exe getinfo`
Result: just one (or two) blank line written to console, nothing more.

-13-
`electrum-4.4.3.exe getinfo>status.txt`
Result: status.txt written, seems ok for now, some lines of the answer:
```
    "default_wallet": "C:\\Users\\username\\AppData\\Roaming\\Electrum\\wallets\\default_wallet",
    "path": "C:\\Users\\username\\AppData\\Roaming\\Electrum",
```

-14- ***ERROR***
`electrum-4.4.3.exe daemon stop`
Result: two new processes spawned for a moment and closed. Two processes created after -11- is not closed.

-15-
Killing two processes made in -11-.
```
electrum-4.4.3.exe -w D:/Test2/Electrum/electrum_data/wallets/electrum_wallet daemon
electrum-4.4.3.exe getinfo>status.txt
```
Result (no matter "-w=" or "-w " - result the same):
```
    "default_wallet": "D:/Test2/Electrum/electrum_data/wallets/electrum_wallet",
    "path": "C:\\Users\\username\\AppData\\Roaming\\Electrum",
```

-16- ***ERROR***
`electrum-4.4.3.exe importprivkey SOMEWIFKEY>status.txt`
Result: "Error: *Wallet file not found*." in status.txt.
Process is trying to search C:\\Users\\username\\AppData\\Roaming\\Electrum\\wallets\\default_wallet (used Sysinternals Process Monitor to see it) and ignores that daemon is started with forced external wallet file.

-17- ***ERROR***
`electrum-4.4.3.exe -w D:/Test2/Electrum/electrum_data/wallets/electrum_wallet importprivkey SOMEWIFKEY>status.txt`
Result: status.txt 0 bytes now.

-18- ***ERROR***
Killing two processes made in -15-
```
electrum-4.4.3.exe -w=D:/Test2/Electrum/electrum_data/wallets/electrum_wallet -D=D:/Test2/Electrum/electrum_data daemon
electrum-4.4.3.exe getinfo>status.txt
```
Result: "Daemon not running; try \"electrum daemon -d\"" in status.txt (2 processes exists).

-19- ***ERROR***
```
electrum-4.4.3.exe importprivkey SOMEWIFKEY>status.txt
```
Result: the same as in -16-.

-20- ***ERROR***
```
electrum-4.4.3.exe -w D:/Test2/Electrum/electrum_data/wallets/electrum_wallet importprivkey SOMEWIFKEY>status.txt
```
Result: "Daemon not running; try \"electrum daemon -d\"" in status.txt (2 processes exists).

So the wallet is totally unusable in commandline/scripting.
I've spent a ton of time to understand that it's not my python script is not working but Electrum is full of bugs.
Don't want to install Electrum to see the same results and spend again a new ton of time.

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/8425#issuecomment-1549575997
