### ISSUE TITLE
tx details: will "share -> save to file (bin)" option be useful?

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#8433]
Currently "share -> save to file" button in transaction details dialog saves the hex-encoded transaction to file. It's only a minor inconvenience to convert it back to binary, but maybe it will be useful to add a second option, like "save to file (binary)"? (while renaming the old button to "save to file (hex)")

I'll make a PR if that will be considered a useful change.

**Comment by SomberNight** [comment]
What is the use case? Which other program expects the tx in binary form?

**Comment by Rogach** [comment]
For example [fq](https://github.com/wader/fq), binary parser useful for inspecting the transaction contents.

**Comment by SomberNight** [comment]
`fq` is not bitcoin-specific. All the bitcoin tools I know expect hex-formatted txs - if the tx is complete. For partial txs, usually either a base64-formatted or a raw bytes PSBT is expected.

I would rather not complicate the UI with a "save tx as binary" option, unless there is a good use case for it. You being a single advanced/techy user inspecting/debugging raw txs occasionally does not justify this new UI-visible option IMHO. :P
Sorry.

**Comment by Rogach** [comment]
No problem, I understand. "advanced/techy users" like myself won't have much problem converting hex back to binary.
