### ISSUE TITLE
insane unexplainable fee upon closing chan..

### ISSUE THREAD

**Issue by xeverse** [spesmilo/electrum#8441]
now i need to know what the closing-tx-feez would be
exactly if i were to coop/force wind up a chan right now?
how can i get these estimatesmartfeez from el-console?

**Comment by xeverse** [comment]
1. alright then, now tell me how can i patch the py-code
& get rid of all localReserve & feeSpikeBuff restrictions i 
just wanna push all sats on the other side of the chan..

2. can such htlc auto-trigger any force close broadcast tx 
of other ln-daemons. do you know of any implementations?

**Comment by ecdsa** [comment]
you don't unilaterally get rid of things that are part of the lightning protocol. 
please learn what channel reserve is.

this issue is redundant with #8413 and #8419.
please do not open new issues for it; this is not going to get you more attention.

**Comment by xeverse** [comment]
not looking 4  no fattention.. just
resolve the issues at hand properly.. please
give detailed answers why you've  implemented
such pyCode prioritizing proto interest over end-users?
& how it can be remedied with the current limbo state..
