### ISSUE TITLE
Проблема 

### ISSUE THREAD

**Issue by Richard555777** [spesmilo/electrum#8443]
Здравствуйте, как это понимать, пополнил кошелёк на 136 тысяч рублей, а в итоге пришли только 10 тысяч рублей, то есть тупо украли деньги 😡😡😡

**Comment by Ericrowlowland** [comment]
Какой кошелек вы используете, как это произошло?

**Comment by Richard555777** [comment]
Отправил с одного кошелька на Ваш кошелёк 136 тысяч рублей. Пришли вместо суммы выше - 10 тысяч рублей, вот так

**Comment by Ericrowlowland** [comment]
Мой кошелек?

**Comment by Richard555777** [comment]
Если электрум это Ваш кошелёк, тогда да

**Comment by SomberNight** [comment]
- This issue tracker is for bug reports, not user support.
- Your problem description does not contain enough concrete details or context to be intelligible.
- The preferred language to be used is English.

Maybe share a screenshot of what you see in Electrum and explain how that differs from what you expected.

**Comment by Richard555777** [comment]
![IMG_20230518_054503](https://github.com/spesmilo/electrum/assets/133930952/0a29d1ca-3fd7-4b3d-bebb-e7d7d0a8dae3)

**Comment by Richard555777** [comment]
0.004, а должно было прийти 0.062

**Comment by Richard555777** [comment]
Мне поступило 0.004 должно было поступить 0.062 разница слишком велика

**Comment by Ericrowlowland** [comment]
Когда вы отправили деньги, это до 4 дней, если не до 4 дней, я могу помочь
вам вернуть деньги на ваш кошелек

**Comment by Richard555777** [comment]
То есть они придут в течение 4 дней?

**Comment by Richard555777** [comment]
Тогда почему пришли 0.004)?

**Comment by SomberNight** [comment]
You should contact whoever sent the transaction. They only sent 0.0047 btc. This has nothing to do with Electrum.

**Comment by Ericrowlowland** [comment]
***@***.***

Отправь мне сообщение на это письмо, я помогу тебе вернуть их, хорошо?
