### ISSUE TITLE
I do new wallet and dont remeber password and seed. but i have txt where this password created! 20% for help! 

### ISSUE THREAD

**Issue by SamSem12222** [spesmilo/electrum#8445]
Hello its not possible! i create new wallet in electrum and dont save txt. Why i cant restore this???!!! i have laptop where this wallet created! And i know past of password! Please help me!

**Comment by SamSem12222** [comment]
3.9$

**Comment by ecdsa** [comment]
sorry, please. 
this is an issue tracker.

**Comment by Tonylam1234** [comment]
Kiếm tiền nhiều
