### ISSUE TITLE
Upgrade problem Ubuntu 20 -> 22

### ISSUE THREAD

**Issue by Coinomatron** [spesmilo/electrum#8452]
Electrum 3.3.8 worked fine on Ubuntu 20 / python3.8. With Ubuntu 22 comes python 3.10 and I'm getting this error:

Cannot create window for wallet:
setMinimumHeight(self, int): argument 1 has unexpected type 'float'

EPS 0.2.4 still works, as far as I can tell.

I'd like to keep using 3.3.8. Is there an easy fix to this, or is the only option here either system reverting or using the 3.3.8 appimage? Thanks

**Comment by Coinomatron** [comment]
Thanks for the reply. I'm just comfortable with 3.3.8 and don't need lightning or the latest developments on electrum (for now). It's also in sync with the rest of the machines I have. Anyway, it was going to happen sooner or later on this online system, with necessary OS upgrades. If I ever figure out what the problem is, I'll make a note here for prosperity.

**Comment by Coinomatron** [comment]
For anyone landing on this page, the solution is rediculously simple. The paytoedit.py in electrum/qt/qui/ contains these lines. self.setMinimumHeight(h)
self.setMaximumHeight(h)

It errors on h being a float, don't try to make it an integer, you'll get all sorts of other issues. (thanks GPT, for wasting hours of my time) SImply change 'h' to a number.

**Comment by molecular** [comment]
diff --git a/gui/qt/paytoedit.py b/gui/qt/paytoedit.py
index 47981fdf1..babe05ff1 100644
--- a/gui/qt/paytoedit.py
+++ b/gui/qt/paytoedit.py
@@ -192,7 +192,7 @@ class PayToEdit(CompletionTextEdit, ScanQRTextEdit):
     def update_size(self):
         lineHeight = QFontMetrics(self.document().defaultFont()).height()
         docHeight = self.document().size().height()
-        h = docHeight * lineHeight + 11
+        h = (int)(docHeight * lineHeight + 11)
         if self.heightMin <= h <= self.heightMax:
             self.setMinimumHeight(h)
             self.setMaximumHeight(h)
