### ISSUE TITLE
Unable to send, getting "MissingSolutionPiece..." with Blockstream Jade over USB

### ISSUE THREAD

**Issue by ReichardKonige** [spesmilo/electrum#8463]
I'm on PopOS Linux 22.04:
Linux pop-os-laptop 6.2.6-76060206-generic #202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M x86_64 x86_64 x86_64 GNU/Linux

Using Electrum App Image 4.4.4
udev rules in place.

Blockstream Jade hardware wallet on latest firmware 0.1.48
Connected to Electrum Server on Umbrel over Tor
I can connect, view addresses, and receive BTC fine.

However If I go to pay/send BTC I get the error described in the subject. Sometimes a dialog box stating "please wait" will come up but it stays there for ages (over 10 minutes) without closing. If I close it and select send I get the error. If I have a saved payment then open it and hit send it does not give the "please wait" dialog it just immediately errors.  I'm attaching the log of the error when both methods are done. Perhaps you can help. I have not tried this on a windows machine.
[electrum_log_20230602T043837Z_44469.log](https://github.com/spesmilo/electrum/files/11632036/electrum_log_20230602T043837Z_44469.log)
![Screenshot from 2023-06-02 00-40-09](https://github.com/spesmilo/electrum/assets/31149763/ea44545e-374e-44e8-bf6d-b77b94d5c6fd)

**Comment by SomberNight** [comment]
Thank you for the detailed report.
No need to test on Windows, Linux has first-party support here :)

Should be fixed on master now. This is a regression from 4.4.0, so e.g. 4.3.4 should also work.

**Comment by Ericrowlowland** [comment]
Have you get your coins safe
