### ISSUE TITLE
android gesture navigation interferes with app

### ISSUE THREAD

**Issue by accumulator** [spesmilo/electrum#8464]
Mentioned earlier in #8303 and now also in a play store review.

Especially android 13 seems to be problematic.

https://developer.android.com/develop/ui/views/touch-and-input/gestures/gesturenav

**Comment by SomberNight** [comment]
I have a samsung phone with android 13 but AFAICT it does not seem to reproduce these issues.
Though if the problem is with the "predictive back gesture" in particular, then apparently samsung devices [don't have that ](https://www.sammobile.com/news/android-14-to-include-the-predictive-back-gesture-by-default/)implemented yet.

**Comment by accumulator** [comment]
I was able to test on an android 13 with gestures enabled. 
The transaction history list items receive a mouse-down when starting the back gesture from the left side, which is completed to a click event once the back gesture is activated.

Interestingly, the right side worked correctly, as that was covered by a drag-event only mousearea which doesn't care about click events. 

I've added a dummy mousearea on the left side of the transaction history list, which seems to solve the issue at the expense of items not being clickable on the far left side, see d83149f66880b6945fc4757c2ec2124677e4a3a0

Other lists in the UI have a wider margin, and seem to be ok without change.

**Comment by accumulator** [comment]
reopened, Preferences is problematic still

**Comment by SomberNight** [comment]
note: the original report is re the addresses list, not the history. So I imagine that list is still affected.

**Comment by accumulator** [comment]
> note: the original report is re the addresses list, not the history. So I imagine that list is still affected.

Indeed

**Comment by accumulator** [comment]
worked around in 583afefe33d7999fd3dfbcc5821be840e8dc1b4b
