### ISSUE TITLE
Unable to sign multisig transaction with Blockstream Jade

### ISSUE THREAD

**Issue by MButcho** [spesmilo/electrum#8465]
I have 2/3 multisig wallet, Trezor / Ledger and Jade. I am able to sign tx with Trezor & Ledger, but not with Jade. The error during sign with Jade is:
![image](https://github.com/spesmilo/electrum/assets/41790777/2b09fc23-7617-4d88-a1ee-7868586b99d2)

I created:
1. 1 wallet with all HW devices => same issue
2. 3 wallets, each with 1 HW => same issue

Tried with versions 4.4.2, 4.4.3 and 4.4.4

**Comment by SomberNight** [comment]
same as https://github.com/spesmilo/electrum/issues/8463
You can use master or go back to 4.3.4 for now.
