### ISSUE TITLE
Replace-By-Fee

### ISSUE THREAD

**Issue by melaxon** [spesmilo/electrum#8466]
In latest versions there is no Replace-By-Fee checkbox. Not sure how to switch it off. Please help. 
Is it a bug or a feature?

**Comment by SomberNight** [comment]
It was removed from the settings on purpose. See https://github.com/spesmilo/electrum/issues/8088
You can comment in that issue why you would want to switch it off.

**Comment by melaxon** [comment]
I would want to switch it off sometimes to send payments via Bitpay to different providers and merchants as Bitpay requires RBF to be switched off. Bitpay is widely used and it's good idea to take it into account. Thank you in advance

**Comment by sh3ll4rpw** [comment]
Please add this function back

**Comment by plundermun** [comment]
Yes please bring it back as long as some big payment gateways use it for some business logic.
Had to downgrade to 4.3 for now.

**Comment by Reza-qezell** [comment]
Hello fellas. Can u please charge my wallet? Have no laptop to contribute more

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
