### ISSUE TITLE
Mobile app of Electrum doesn't update the balance properly (on-chain and frozen)

### ISSUE THREAD

**Issue by creativefrisbee** [spesmilo/electrum#8471]
I'm using desktop and mobile app of Electrum.
In the desktop version, the coin tab has option freeze coins that I don't need to use currently. So, when I unfreeze the coins I need, I can use them for any payment and all works fine.

However, in the mobile version the balance doesn't update at all and all coins remains to be spendable.
I'm using the latest version (4.4.4) for both desktop and mobile version.

**Comment by creativefrisbee** [comment]
> Can't reproduce. What version are you using?

As I already wrote - 4.4.4
The desktop version is on Windows 10 and the mobile version is on Android phone.

**Comment by creativefrisbee** [comment]
> Do you mean to say you expect to be able to freeze coins on the desktop app, and have that reflected automagically in the android app? There is no such synchronization.

Yes, that's right. Such a shame it's not possible to do such synchronization, because the mobile app doesn't have coin settings feature at all.

**Comment by accumulator** [comment]
> the mobile app doesn't have coin settings feature at all.

Incorrect. You can (un)freeze on address level from the Addresses page

**Comment by gits7r** [comment]
@accumulator the problem with latest Android app is that you can go to `Addresses` but you can just scroll down, it's not possible any more to filter by: used|unsued|funded and type receive|change. Those were useful, if you wanted to freeze or unfreeze a particular address.

**Comment by accumulator** [comment]
@gits7r We are planning to re-introduce these address filters in a future release.
