### ISSUE TITLE
electrum re-requests all LN channels on each startup

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#8477]
It seems that lnpeer sends `query_channel_range` messages with `first_blocknum = 497000` on every startup: https://github.com/spesmilo/electrum/blob/master/electrum/lnpeer.py#L481

Is it intentional?

My understanding was that normally we already have most of the channels stored in local gossip_db, so re-requesting all of them is just wasting time and resources. Perhaps we can only query channels that are newer than the latest channel we know about? Something like this:

```diff
--- a/electrum/lnpeer.py
+++ b/electrum/lnpeer.py
@@ -479,8 +479,13 @@ class Peer(Logger):
                 await self.get_short_channel_ids(todo)
 
     async def get_channel_range(self):
-        first_block = constants.net.BLOCK_HEIGHT_FIRST_LIGHTNING_CHANNELS
-        num_blocks = self.lnworker.network.get_local_height() - first_block
+        last_block = self.lnworker.network.get_local_height()
+        last_known_channel_block = self.lnworker.channel_db.get_last_known_channel_block()
+        if last_known_channel_block is None:
+            first_block = constants.net.BLOCK_HEIGHT_FIRST_LIGHTNING_CHANNELS
+        else:
+            first_block = min(last_known_channel_block, self.lnworker.network.get_local_height()) - 3 * 144
+        num_blocks = last_block - first_block
         self.query_channel_range(first_block, num_blocks)
         intervals = []
         ids = set()

--- a/electrum/channel_db.py
+++ b/electrum/channel_db.py
@@ -348,6 +348,13 @@ class ChannelDB(SqlDB):
         with self.lock:
             return set(self._channels.keys())
 
+    def get_last_known_channel_block(self):
+        with self.lock:
+            if len(self._channels) == 0:
+                return None
+            else:
+                return max(short_channel_id.block_height for short_channel_id in self._channels.keys())
+
     def add_recent_peer(self, peer: LNPeerAddr):
         now = int(time.time())
         node_id = peer.pubkey
```

**Comment by SomberNight** [comment]
The gossip messages in general are not really suited for an only-occasionally-online light client, on the protocol level. Hopefully it will be better in a gossip v2 with minisketch.

In any case, re your concrete remark, it is intentional, yes. query_channel_range only requests the short chan ids, which are only 8 bytes per channel. And note that it is not possible to detect lying by omission: if we used your proposal, and some client in the past didn't tell us about some channels, we would never get to learn about them.

**Comment by Rogach** [comment]
Makes sense, thank you for the explanation! Is there any place where I can read about gossip v2?
