### ISSUE TITLE
Electrum starts, but I see an error in the terminal (Ubuntu 20.04)

### ISSUE THREAD

**Issue by aydaraliev** [spesmilo/electrum#8486]
```
~/Desktop$ ./electrum-4.4.4-x86_64.AppImage
/usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601  
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

```
The program seems to be working, but something is not right. I downloaded the latest version from the website. I am on Ubuntu 20.04. If you need any additional info I am happy to provide it.

**Comment by accumulator** [comment]
Since Electrum seems to work correctly, I'm closing this as a wontfix. Feel free to re-open if you think any functionality of the wallet is impaired .
