### ISSUE TITLE
Can't open wallets stored on WinFSP/FUSE mounted drive

### ISSUE THREAD

**Issue by tayl** [spesmilo/electrum#8495]
I'm using Cryptomator to store some things in Google Drive and noticed today that Electrum is unable to read wallet files in a filesystem mounted by Cryptomator using WinFSP (FUSE).

![image](https://github.com/spesmilo/electrum/assets/3814633/ef4ee343-2eb4-4c8b-a171-70f07713bb4b)

Opening the file using the exact same file path in something like Notepad works as expected. Possibly this is related to how Cryptomator is mounting the filesystem, and how Electrum is referencing the path? Unsure..

**Comment by SomberNight** [comment]
Can you get the full traceback from the [debug log](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?

**Comment by tayl** [comment]
The wallet path as logged is slightly different from the path selected in the explorer interface. Accessing this path fails, but accessing the path as provided in the UI works.

`20230630T030814.812366Z |     INFO | i18n | gettext setting initial language to None
20230630T030815.043105Z |     INFO | simple_config.SimpleConfig | electrum directory C:\Users\Taylor\Desktop\Temporary\electrum_data
20230630T030815.082518Z |     INFO | __main__ | get_default_language: detected default as lang='en_UK'
20230630T030815.082518Z |     INFO | i18n | setting language to 'en_UK'
20230630T030815.087501Z |     INFO | logging | Electrum version: 4.4.5 - https://electrum.org - https://github.com/spesmilo/electrum
20230630T030815.151867Z |     INFO | logging | Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:24:45) [MSC v.1929 32 bit (Intel)]. On platform: Windows-10-10.0.19044-SP0
20230630T030815.151867Z |     INFO | logging | Logging to file: C:\Users\Taylor\Desktop\Temporary\electrum_data\logs\electrum_log_20230630T030815Z_6400.log
20230630T030815.151867Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20230630T030815.155865Z |     INFO | plugin.Plugins | registering hardware bitbox02: ('hardware', 'bitbox02', 'BitBox02')
20230630T030815.160862Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20230630T030815.162861Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20230630T030815.164860Z |     INFO | plugin.Plugins | registering hardware jade: ('hardware', 'jade', 'Jade wallet')
20230630T030815.165860Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20230630T030815.167858Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20230630T030815.170857Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20230630T030815.171857Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20230630T030815.172855Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20230630T030815.174857Z |     INFO | plugin.Plugins | registering hardware jade: ('hardware', 'jade', 'Jade wallet')
20230630T030815.175854Z |    DEBUG | util.profiler | Plugins.__init__ 0.0230 sec
20230630T030815.175854Z |     INFO | network | blockchains [0]
20230630T030815.179851Z |     INFO | network | setting proxy None
20230630T030815.179851Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko
20230630T030815.181863Z |    DEBUG | util.profiler | Daemon.__init__ 0.0060 sec
20230630T030815.181863Z |     INFO | daemon.Daemon | starting taskgroup.
20230630T030815.181863Z |     INFO | daemon.Daemon | launching GUI: qt
20230630T030815.183850Z |     INFO | daemon.CommandsServer | now running and listening. socktype=tcp, addr=('127.0.0.1', 16754)
20230630T030815.278862Z |     INFO | gui.qt.ElectrumGui | Qt GUI starting up... Qt=5.15.2, PyQt=5.15.9
20230630T030815.406730Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.1279 sec
20230630T030815.406730Z |     INFO | daemon.Daemon | starting network.
20230630T030815.406730Z |     INFO | network | starting network
20230630T030815.408729Z |     INFO | network | setting proxy None
20230630T030815.408729Z |     INFO | network | connecting to assuredly.not.fyi:50002:s as new interface
20230630T030815.408729Z |     INFO | network | starting taskgroup (0x4edf0b8).
20230630T030815.409729Z |     INFO | storage.WalletStorage | wallet path c:\users\taylor\desktop\temporary\electrum_data\wallets\default_wallet
20230630T030815.412727Z |    DEBUG | util.profiler | Daemon._load_wallet 0.0040 sec
20230630T030815.959379Z |     INFO | interface.[assuredly.not.fyi:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
20230630T030815.974386Z |     INFO | storage.WalletStorage | wallet path c:\users\taylor\desktop\temporary\electrum_data\wallets\default_wallet
20230630T030815.976369Z |     INFO | network | couldn't launch iface assuredly.not.fyi:50002:s -- CancelledError()
20230630T030816.161153Z |     INFO | interface.[34.67.22.216:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20230630T030816.226086Z |     INFO | interface.[34.67.22.216:50002] | set blockchain with height 796496
20230630T030816.227085Z |     INFO | interface.[34.67.22.216:50002] | skipping header 796496
20230630T030816.227085Z |     INFO | network | no height for main interface
20230630T030816.298033Z |     INFO | network | fee_estimates {25: 11962, 10: 18069, 5: 22130, 2: 31097}
20230630T030816.304028Z |     INFO | interface.[ty6cgwaf2pbc244gijtmpfvte3wwfp32wgz57eltjkgtsel2q7jufjyd.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
20230630T030816.305027Z |     INFO | network | couldn't launch iface ty6cgwaf2pbc244gijtmpfvte3wwfp32wgz57eltjkgtsel2q7jufjyd.onion:50002:s -- CancelledError()
20230630T030816.330513Z |     INFO | network | switching to 34.67.22.216:50002:s
20230630T030816.390497Z |     INFO | network | fee_histogram [[35.0, 30050], [33.7, 33022], [32.3, 46470], [28.9, 40501], [27.9, 44789], [25.7, 83771], [23.1, 58990], [20.4, 59540], [17.7, 81111], [13.5, 72763], [11.5, 79915], [10.8, 180587], [10.6, 179684], [10.5, 134442], [10.4, 2291854], [10.3, 583935], [10.1, 107878], [10.0, 3974395], [9.9, 500882], [9.8, 152190], [9.7, 1423095], [9.6, 921935], [9.5, 4696260], [9.4, 751857], [9.3, 440220], [9.2, 2844076], [9.1, 600312], [9.0, 3007270], [8.9, 1111221], [8.7, 607439], [8.6, 655919], [8.5, 521761], [8.4, 1901699], [8.2, 806006], [8.1, 853758], [8.0, 7212225], [7.8, 1136611], [7.3, 1169053], [7.0, 1942118], [6.4, 1239412]]
20230630T030816.401395Z |     INFO | network | fee_histogram [[35.0, 30050], [33.7, 33022], [32.3, 46470], [28.9, 40501], [27.9, 44789], [25.7, 83771], [23.1, 58990], [20.4, 59540], [17.7, 81111], [13.5, 72763], [11.5, 79915], [10.8, 180587], [10.6, 179684], [10.5, 134442], [10.4, 2291854], [10.3, 583935], [10.1, 107878], [10.0, 3974395], [9.9, 500882], [9.8, 152190], [9.7, 1423095], [9.6, 921935], [9.5, 4696260], [9.4, 751857], [9.3, 440220], [9.2, 2844076], [9.1, 600312], [9.0, 3007270], [8.9, 1111221], [8.7, 607439], [8.6, 655919], [8.5, 521761], [8.4, 1901699], [8.2, 806006], [8.1, 853758], [8.0, 7212225], [7.8, 1136611], [7.3, 1169053], [7.0, 1942118], [6.4, 1239412]]
20230630T030816.605785Z |     INFO | interface.[skbxmit.coinjoined.com:50002] | connection established. version: ['ElectrumX 1.15.0', '1.4']
20230630T030816.721179Z |     INFO | interface.[guichet.centure.cc:50002] | succeeded in getting cert
20230630T030816.767784Z |     INFO | interface.[skbxmit.coinjoined.com:50002] | set blockchain with height 796496
20230630T030816.768783Z |     INFO | interface.[skbxmit.coinjoined.com:50002] | skipping header 796496
20230630T030816.904825Z |     INFO | network | fee_estimates {25: 11511, 10: 18598, 5: 22134, 2: 31097}
20230630T030816.936794Z |     INFO | interface.[electrum.hsmiths.com:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
20230630T030816.966789Z |     INFO | interface.[elx.bitske.com:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20230630T030817.023731Z |     INFO | interface.[guichet.centure.cc:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20230630T030817.087258Z |     INFO | interface.[guichet.centure.cc:50002] | set blockchain with height 796496
20230630T030817.088256Z |     INFO | interface.[guichet.centure.cc:50002] | skipping header 796496
20230630T030817.152106Z |     INFO | interface.[electrum.hsmiths.com:50002] | set blockchain with height 796496
20230630T030817.153105Z |     INFO | interface.[electrum.hsmiths.com:50002] | skipping header 796496
20230630T030817.154104Z |     INFO | network | fee_estimates {25: 11958, 10: 19098, 5: 22131, 2: 31097}
20230630T030817.166060Z |     INFO | interface.[electrum.blockstream.info:50002] | connection established. version: ['electrs-esplora 0.4.1', '1.4']
20230630T030817.183091Z |     INFO | interface.[elx.bitske.com:50002] | set blockchain with height 796496
20230630T030817.184088Z |     INFO | interface.[elx.bitske.com:50002] | skipping header 796496
20230630T030817.293667Z |     INFO | interface.[2electrumx.hopto.me:56022] | succeeded in getting cert
20230630T030817.336668Z |     INFO | interface.[electrum.blockstream.info:50002] | set blockchain with height 796496
20230630T030817.337670Z |     INFO | interface.[electrum.blockstream.info:50002] | skipping header 796496
20230630T030817.359645Z |     INFO | network | fee_estimates {25: 11527, 10: 18584, 5: 22130, 2: 31097}
20230630T030817.360772Z |     INFO | network | fee_estimates {25: 11958, 10: 19096, 5: 22130, 2: 31097}
20230630T030817.386837Z |     INFO | network | fee_estimates {25: 11959, 10: 19097, 5: 22130, 2: 31097}
20230630T030817.839078Z |     INFO | interface.[electrum.qtornado.com:50002] | disconnecting due to GracefulDisconnect('too many connected servers already in bucket 45.154.0.0/16')
20230630T030817.841077Z |     INFO | network | couldn't launch iface electrum.qtornado.com:50002:s -- CancelledError()
20230630T030817.929404Z |     INFO | interface.[2electrumx.hopto.me:56022] | connection established. version: ['ElectrumX 1.16.0', '1.4']
20230630T030818.091501Z |     INFO | interface.[2electrumx.hopto.me:56022] | set blockchain with height 796496
20230630T030818.091501Z |     INFO | interface.[2electrumx.hopto.me:56022] | skipping header 796496
20230630T030818.235528Z |     INFO | network | fee_estimates {25: 11961, 10: 19097, 5: 22130, 2: 31097}
20230630T030818.692517Z |     INFO | interface.[blockstream.info:700] | connection established. version: ['electrs-esplora 0.4.1', '1.4']
20230630T030818.843211Z |     INFO | interface.[blockstream.info:700] | set blockchain with height 796496
20230630T030818.844212Z |     INFO | interface.[blockstream.info:700] | skipping header 796496
20230630T030818.873187Z |     INFO | network | fee_estimates {25: 11959, 10: 19096, 5: 22130, 2: 31097}
20230630T030827.152491Z |     INFO | storage.WalletStorage | wallet path \\cryptomator-vault\_qnxgff6h3fp\temporary\electrum\electrum_data\wallets\test_wallet
20230630T030830.115040Z |     INFO | daemon.Daemon | stop() entered. initiating shutdown
20230630T030830.115040Z |     INFO | gui.qt.ElectrumGui | closing GUI
20230630T030830.115040Z |     INFO | daemon.Daemon | stopping all wallets
20230630T030830.116038Z |     INFO | daemon.Daemon | stopping network and taskgroup
20230630T030830.116038Z |     INFO | network | stopping network
20230630T030830.117038Z |     INFO | daemon.Daemon | taskgroup stopped.
20230630T030830.118038Z |     INFO | network | couldn't launch iface 73.92.198.54:50002:s -- CancelledError()
20230630T030830.118038Z |     INFO | network | couldn't launch iface node.degga.net:50002:s -- CancelledError()
20230630T030830.162013Z |     INFO | interface.[electrum.blockstream.info:50002] | disconnecting due to: CancelledError()
20230630T030830.171008Z |     INFO | interface.[34.67.22.216:50002] | disconnecting due to: CancelledError()
20230630T030830.179003Z |     INFO | interface.[guichet.centure.cc:50002] | disconnecting due to: CancelledError()
20230630T030830.255250Z |     INFO | interface.[2electrumx.hopto.me:56022] | disconnecting due to: CancelledError()
20230630T030830.260913Z |     INFO | interface.[skbxmit.coinjoined.com:50002] | disconnecting due to: CancelledError()
20230630T030830.263341Z |     INFO | interface.[blockstream.info:700] | disconnecting due to: CancelledError()
20230630T030830.304960Z |     INFO | interface.[electrum.hsmiths.com:50002] | disconnecting due to: CancelledError()
20230630T030830.323897Z |     INFO | interface.[elx.bitske.com:50002] | disconnecting due to: CancelledError()
20230630T030830.324926Z |     INFO | network | taskgroup stopped (0x4edf0b8).
20230630T030830.328923Z |     INFO | daemon.Daemon | removing lockfile
20230630T030830.329922Z |     INFO | daemon.Daemon | stopped
20230630T030830.361009Z |     INFO | plugin.Plugins | stopped
`

**Comment by SomberNight** [comment]
I see this path logged:
```
storage.WalletStorage | wallet path \\cryptomator-vault\_qnxgff6h3fp\temporary\electrum\electrum_data\wallets\test_wallet
```

> Accessing this path in notepad fails, but accessing the path as provided in the UI works.

How does that "UI-provided" path look like?

**Comment by SomberNight** [comment]
Ok, I can reproduce in a Win10 VM.

The issue is caused by `util.standarize_path`, specifically [`os.path.realpath`](https://docs.python.org/3/library/os.path.html#os.path.realpath).
https://github.com/spesmilo/electrum/blob/6b43eac6fdba2d42a36291185c3c0337e98e0b43/electrum/util.py#L524-L530
For some reason, the path returned by `os.path.realpath()` does not work.

```py
PS C:\Users\user> python3
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> p = "Y:/9dk"
>>> sp = os.path.normcase(os.path.realpath(os.path.abspath(os.path.expanduser(p))))
>>>
>>> sp
'\\\\cryptomator-vault@42427\\xhzyuh8fjkdx\\test_vault\\9dk'
>>> os.path.normcase(os.path.abspath(os.path.expanduser("Y:/9dk")))
'y:\\9dk'
>>> os.path.exists(p)
True
>>> os.path.exists(sp)
False
```

The `os.path.realpath()` call was added in https://github.com/spesmilo/electrum/commit/b06b8753e6c88a6d1074ca59fbd2e8c85f234129 regarding https://github.com/spesmilo/electrum/issues/5088 - to resolve symlinks.

**Comment by SomberNight** [comment]
Looks related: https://github.com/spesmilo/electrum/issues/7537

**Comment by SomberNight** [comment]
Thanks for the report. It should work now on master.
