### ISSUE TITLE
Questions regarding bundled PTMono fonts

### ISSUE THREAD

**Issue by sorenstoutner** [spesmilo/electrum#8502]
In my ongoing efforts to fully clean up the Debian packages, I have the following question.  `electrum/gui/qml` bundles two PTMono fonts.  These are used by `qeapp.py`, which includes the following code.

```
# add a monospace font as we can't rely on device having one
        self.fixedFont = 'PT Mono'
        not_loaded = QFontDatabase.addApplicationFont('electrum/gui/qml/fonts/PTMono-Regular.ttf') < 0
        not_loaded = QFontDatabase.addApplicationFont('electrum/gui/qml/fonts/PTMono-Bold.ttf') < 0 and not_loaded
        if not_loaded:
            self.logger.warning('Could not load font PT Mono')
            self.fixedFont = 'Monospace' # hope for the best
```

PTMono is not currently packaged in Debian.  Work could be done to package it, but based on the code above it looks like any monospace font is sufficient.  I am unfamiliar with what `qeapp.py` does.  How can I test to make sure that that it is correctly falling back on the system monospace font if the PTMono fonts are removed from the package?

**Comment by SomberNight** [comment]
Unclear if it makes sense to package the qml gui.

It is the (new) GUI used on Android (old one was kivy), see
https://github.com/spesmilo/electrum/blob/c85139009a84539e891fcdf01ee2ed35c1cdbee2/contrib/android/Readme.md

but it *can* run on a desktop, see
https://github.com/spesmilo/electrum/blob/c85139009a84539e891fcdf01ee2ed35c1cdbee2/contrib/android/Readme.md#the-qml-gui-can-be-run-directly-on-linux-desktop-how

**Comment by sorenstoutner** [comment]
Thanks for the links to the well written documentation.

For now, I think I will just drop QML from the Debian package.  If things ever change and you decide to use QML for the recommended desktop experience let me know.

By the way, it looks like ever since Oreo (Android 8, API 26) the AOSP project has included a couple of monospace fonts.

https://stackoverflow.com/questions/19691530/valid-values-for-androidfontfamily-and-what-they-map-to
