### ISSUE TITLE
Translation of expiration values does not work on Windows (Linux OK)

### ISSUE THREAD

**Issue by lionkmp** [spesmilo/electrum#8507]
Please see this screenshot. On Windows these words are not translated on the expiration **Button** and on the **Dialog**. But those words are translated to Hungarian and they work OK on Linux version. Tested 4.4.4 and 4.4.5 - same result. I've used the "Standalone Executable".

They seem to be these strings, 1 week etc:

https://github.com/spesmilo/electrum/blob/97768a13b99023d25b0402ca9ef3914dd381af8c/electrum/invoices.py#L67

Thanks in advance.

![ele_bug_exp_win2](https://github.com/spesmilo/electrum/assets/5088657/e4237102-a216-4820-9f66-387cc06a6936)

**Comment by SomberNight** [comment]
This is an instance of https://github.com/spesmilo/electrum/issues/4621
see https://github.com/spesmilo/electrum/issues/4621#issuecomment-1613437066 for explanation

**Comment by lionkmp** [comment]
Thank you. Then it's not OS specific, but my Linux is hu_HU by default and my Windows is English. So the default language in step 1 is set differently.

Can't you please move these 5 strings to be GUI strings? In mentioned comment you wrote, GUI strings are OK. Besides the outdated kivy, this array is referenced in **receive_tab.py** only, as far as I can see. I know this is suboptimal for an array that is needed on multiple places, but this array does not look to be regularly changed. 

This error was reported to me by users, who tested the translations.

(However I now noticed there is another similar array of strings in the same file, the `pr_tooltips` array.)

**Comment by SomberNight** [comment]
fixed in https://github.com/spesmilo/electrum/commit/621a397b70a6ba18382c7321eceffc871553ab41
