### ISSUE TITLE
Can't create testnet wallet from p2pkh:WIF private key

### ISSUE THREAD

**Issue by gosupport1** [spesmilo/electrum#8514]
I generate private key in WIF format and run electrum with --testnet flag, put p2pkh:"WIFPK" in the text area, but no continue button available (exactly same thing work if I run without --testnet flag).

**Comment by SomberNight** [comment]
Note that WIF keys differ between mainnet and testnet. The magic bytes in the header are not the same.
(see e.g. [here](https://en.bitcoin.it/wiki/Wallet_import_format#Private_key_to_WIF))

**Comment by gosupport1** [comment]
@SomberNight thanx! it would be nice to see validation errors wich show source of a problem.
