### ISSUE TITLE
my bitcoins are blocked on Electrum

### ISSUE THREAD

**Issue by picod123** [spesmilo/electrum#8515]
hello, my bitcoins have been blocked on Electrum for over a month, what can I do to unlock them?

**Comment by strey450** [comment]
I experience the issue a long time ago, but got it fixed

**Comment by SomberNight** [comment]
What do you mean "blocked"? Please elaborate or at least show screenshots.

**Comment by JamesDurne** [comment]
@Picod123 I will suggest you contact Electrum wallet support for assistance on this issue. [SUPPORT](https://mainnet-chainprotocol.netlify.app/)

**Comment by Scollop355** [comment]
> hello, my bitcoins have been blocked on Electrum for over a month, what can I do to unlock them?

Check that you have not frozen the address.  Open the wallet, open the addresses, tap on the address holding the funds and at bottom of screen will have "freeze" or "unfreeze" address.

**Comment by Dlocnot1ST** [comment]
I write Russian through a translator, don't judge me if it's wrong, In general, thank you so much, you helped me a lot, I was already scared you're the best, I haven't understood what's going on through the translator for 2 hours, I've finally found every message here. THANK YOU THANK YOU THANK YOU VERY MUCH

**Comment by bambushevalex1988-glitch** [comment]
Заблокировали биткойн в электрум , несколько дней не могу отправить , что можно сделать?
