### ISSUE TITLE
The pin length of Trezor One

### ISSUE THREAD

**Issue by ik105** [spesmilo/electrum#8526]
My Trezor One with a 12 digit pin cannot be paired with an Electrum because of the 9 digit pin length limitation. In Trezor Suite this limit is 50 digits. Please raise this limit.

**Comment by SomberNight** [comment]
Re the commit, @accumulator, features.model is never "2" I think. Check get_trezor_model().

**Comment by accumulator** [comment]
Ugh, I need a bigger font/reading glasses. 

Thx, and fixed.
