### ISSUE TITLE
#Lightning Trampoline issue》》#

### ISSUE THREAD

**Issue by Fuccthisandfuccu** [spesmilo/electrum#8527]
Is it just my thread or does it really take 2 days between each response? Or is it the name, which I admit is one of the dumbest names possible for somebody trying to get help, completely regret it. No responses, I'd respect that, but two days between each response? Way too long. Not trying to be pen pals with anybody on here. 2 minutes, thats all it would take.

**Comment by ecdsa** [comment]
please do not open multiple issues, it is not helpful.
