### ISSUE TITLE
Can't synchronize wallet on app and have lost $180

### ISSUE THREAD

**Issue by ThirdEyeSharp** [spesmilo/electrum#8537]
How do i synchronize my wallet on the android app? It won't sych and I've lost $180 as of now. Someone please help me troubleshoot

**Comment by Scollop355** [comment]
Losing sync won't cause you to lose bitcoin.
 If round light upper right red then tap the light select Network, Proxy settings and untick
 "enable proxy" if it's enabled.  The light should be green or blue if you are running tor network.

Are you running a firewall app, if so try disabling it tempory.

**Comment by ecdsa** [comment]
closing, no info here
