### ISSUE TITLE
Please fix these bugs

### ISSUE THREAD

**Issue by Scollop355** [spesmilo/electrum#8538]
I made a transaction on a watch only wallet on Android using electrum v4.4.5.0.

When I tried to export the transaction as a QR code I got the following message.

"Warning: Some data (prev txs / "full utxos") was left out of the QR code as it would not fit.  This might cause issues if signing offline.  As a workaround, try exporting the tx as file or text instead."

Now, there is no option on android electrictrum to save as a file.  This slows the process right down to sign on an air gapped computer,, so please get the QR scanning function working and at least an option to save the transaction in file format.

**Comment by ecdsa** [comment]
if the data won't fit in a qr code, then it won't fit.
add more information to your bug reports if you want them to be useful.
