### ISSUE TITLE
Enabling lightning network on watch only wallets should not be allowed

### ISSUE THREAD

**Issue by enorrmann** [spesmilo/electrum#8539]
I was confused because in the wallet information section of my watch only wallet, the button to enable lightning channels was present and even working.
"Warning: this wallet type does not support channel recovery from seed. You will need to backup your wallet everytime you create a new channel. Create lightning keys?"
I choose yes, then
"Lightning keys have been initialized."
I think that option should not be available on watch only wallets, IMHO

**Comment by ecdsa** [comment]
that is debatable.
