### ISSUE TITLE
Is this a bug 

### ISSUE THREAD

**Issue by Scollop355** [spesmilo/electrum#8540]
I imported 2 master public keys from Android Electrum to Windows Electrum.

When I checked all the addresses in Electrum on Windows I noted both wallets were missing an address.

On android the addresses go from 0 to 20
On window the addresses go from 1 to 20

Address 20 on android is missing from the addresses list in windows.  Surely the master public key should have created all 21 addresses from Android to Windows.

All the change addresses were present.

**Comment by Scollop355** [comment]
Show 0 to 19 green addresses if I create a new seed, but 0 to 20 addresses if I import a master public key.

**Comment by ecdsa** [comment]
please provide more specific information, this kind of report is not useful
