### ISSUE TITLE
Bug in wallet funds display.

### ISSUE THREAD

**Issue by Scollop355** [spesmilo/electrum#8541]
Electrum on windows and Blue wallet and Green wallet on Android are showing my BTC balance correctly whilst electrum on Android is showing a balance substantially lower.  Other wallets on Electrum Android are being shown correctly.

**Comment by ecdsa** [comment]
not enough info here.

**Comment by Scollop355** [comment]
You wanted more information.  The problem is with version APK 4.4.5.0 showing an incorrect wallet amount as 1.07  BTC instead of 1.37 BTC.   The previous version showed the wallets amounts correctly.  It looks to me as if the wallet is not accounting for the whole wallet history.

**Comment by ecdsa** [comment]
And it looks to me as if you are using a non-electrum seed generated by another wallet, and are expecting things to work.
BIP39 is broken. Don't use it, or go complain about it with the people who created that standard.

**Comment by ecdsa** [comment]
Of course, there might as well be a bug in Electrum, but you are not providing enough information to assess that.

**Comment by Scollop355** [comment]
The seed was generated in electrum.  I have never used bip 39 to generate
my electrum wallets.  I have had this wallet for several years and it has
displayed the correct amount until this latest version of electrum on
Android.  I don't know what further information to supply.

**Comment by ecdsa** [comment]
so, your seed was generated in Electrum and then what? you entered that seed in Blue Wallet and in Green wallet?

**Comment by Scollop355** [comment]
I exported a master public key (not the seed) from an electrum wallet in
Tails to the Android APK 4.4.5.0.  I exported the same master public key to
the windows version of electrum and blue wallet and green wallet.  All but
and Android version of electrum show the correct balance.

**Comment by ecdsa** [comment]
well, OK,  so this is basically the same issue as #8540. 
Please refrain from opening multiple issues for the same problem.

**Comment by Scollop355** [comment]
No.  That was a different issue about the number of addresses showing which
having spoken to the bitcointalk community seem to be resolved.

**Comment by Scollop355** [comment]
I just deleted the wallet on android and created the wallet again by
importing the Electric master public key from windows Electrum and now the
balance is correctly showing on Android.

There must have been a problem with the previous importing of the master
public key as transfering it to other wallets from android would give the
correct balance whilst on android it would give the incorrect balance.

Consider this solved.  Thanks.
