### ISSUE TITLE
Unable to send any payments | No option to enter address manually

### ISSUE THREAD

**Issue by karanbhagat95** [spesmilo/electrum#8554]
Electrum used to work swiftly while sending and receiving payments. Been using it for years. Just updated the app and I cannot send any payment anymore.

Upon clicking the "Send" button, it shows a scanner that scans absolutely nothing. Been trying to scan the QR code for sending some BTC for a while but it just doesn't do anything.

Is there anything I am doing wrong? Because it used to work the same way before. There is not even any option to enter the address manually in case the scanning is not working.

(Android app issue)

**Comment by ecdsa** [comment]
To rule out a problem with your camera, can you scan the qr code with another application?
For example, you can install Barcode Scanner and scan any QR code with it.
Note that barcode scanner will let you copy the address to the clipboard, which you can paste it in Electrum.

**Comment by karanbhagat95** [comment]
Tried it with normal phone camera instead of electrum send scanner and it worked. It copied the address and I could paste it. It was easier before when we could just scan the QR code within the electrum app and it would fill in all the details like amount to send etc.

**Comment by SomberNight** [comment]
In 4.5.0 we changed back to the old zxing-based qr scanner in Android.
Also btw, while it is true you cannot type an address, you can copy-paste it -- the user is not "forced" to use the camera to scan.
