### ISSUE TITLE
how can i recover my old "wallet.dat"   the private keys dont correspond to the address holding the funds and the seed is showing empty balance. please help. its an old electrum  "wallet.dat"

### ISSUE THREAD

**Issue by Humble2020** [spesmilo/electrum#8558]

**Comment by accumulator** [comment]
`wallet.dat` is typically a filename used by Bitcoin Core.

**Comment by Humble2020** [comment]
> `wallet.dat` is typically a filename used by Bitcoin Core, not Electrum.

OK. that's not the case because if i remove the extension it still acts the same...
the balance reflects but when sending.. it signs on the platform but it says that it cant broadcast with an error. when i searched the error it meant that the key that was used in signing was not actually the correct key.
my question is why is it then displaying in the platform as being signed, under sending preview status? and also when i used "ismine("address")  on console with the address with balance is returned true. why? is electrum messing with me right now? can't my keys be recovered?

**Comment by Humble2020** [comment]
> > `wallet.dat` is typically a filename used by Bitcoin Core, not Electrum.
> 
> OK. that's not the case because if i remove the extension it still acts the same... the balance reflects but when sending.. it signs on the platform but it says that it cant broadcast with an error. when i searched the error it meant that the key that was used in signing was not actually the correct key. my question is why is it then displaying in the platform as being signed, under sending preview status? and also when i used "ismine("address") on console with the address with balance is returned true. why? is electrum messing with me right now? can't my keys be recovered?

inspecting the file --> wallet.dat
it starts with the string:  "addr_history": {

i created a new wallet with electrum and inspected and the new file starts with same string, so how is my key not there?

**Comment by ecdsa** [comment]
old electrum seeds did not have a checksum to protect users against typos.
it is likely that you did not type your seed correctly, and entered a wrong seed.

**Comment by Humble2020** [comment]
> old electrum seeds did not have a checksum to protect users against typos. it is likely that you did not type your seed correctly, and entered a wrong seed.

please, i know that its only you that can explain better and that is why i want to give you the file to check out. plus as the programmer you will have better view than me and know exactly why the private key is displaying signed on the software but can't broadcast. i have asked for your email to be sent to you privately

**Comment by ecdsa** [comment]
No, you cannot send a wallet file with funds inside to us; we do not want to be held responsible if funds disappear.
There are wallet recovery services companies, you might want to try with one of them.

**Comment by ecdsa** [comment]
wallet recovery services can help you if you have a typo in your seed; it is a matter of finding variations on the already known seed.

**Comment by ecdsa** [comment]
> when i searched the error it meant that the key that was used in signing was not actually the correct key.

can you elaborate on that? do you actually have a wallet file with funded addresses? in that case the problem is not a typo.

**Comment by Humble2020** [comment]
i cant post picture here

**Comment by ecdsa** [comment]
no need for a picture. just post the signed transaction in hexadecimal, and the error message you deemed unnecessary to post because you "searched the error"

**Comment by Humble2020** [comment]
> no need for a picture. just post the signed transaction in hexadecimal, and the error message you deemed unnecessary to post because you "searched the error"

https://github.com/Humble2020/unExplained/blob/main/readme.md

**Comment by Humble2020** [comment]
> no need for a picture. just post the signed transaction in hexadecimal, and the error message you deemed unnecessary to post because you "searched the error"

the error is captured in screenshot.

**Comment by Humble2020** [comment]
your tool just lost keys to a huge sum with your upgrade and you cant even fix it

**Comment by Humble2020** [comment]
> no need for a picture. just post the signed transaction in hexadecimal, and the error message you deemed unnecessary to post because you "searched the error"

your tool just lost keys to a huge sum with your upgrade and you cant even fix it

**Comment by Humble2020** [comment]
you don't have an answer to what went wrong in the way your downgraded tool handled the keys

**Comment by Humble2020** [comment]
> no need for a picture. just post the signed transaction in hexadecimal, and the error message you deemed unnecessary to post because you "searched the error"

if i reduce the input by freezing addresses..its still same error with above transaction

**Comment by Humble2020** [comment]
> no need for a picture. just post the signed transaction in hexadecimal, and the error message you deemed unnecessary to post because you "searched the error"

verified as signed on coinb so there is something off here

**Comment by SomberNight** [comment]
> how can i recover my old "wallet.dat" the private keys dont correspond to the address holding the funds and the seed is showing empty balance

You are trying to spend utxos mined around block height 39k in early 2010. These predate Electrum, contradicting your whole story.

> forget about the funds. afterall its a small fee thats there. i just want to know the explanation and if it get messed up and can be recoverable.

2200 btc is not a small amount for most people.

**Comment by hannah11110** [comment]
I am a happy person today having to have recovered a large amount of money worth 10,000, which I had lost in the hands of Bitcoin fraudulent, It has been an unfortunate year for me trying to recover my money back for the last 2months but luckily a friend of mine who also went through the same scamming issue referred me to this recovery agent called (BRIGADIA TECH REMIKEABLE) It took 3days for them to recovery the full amount at first I was hesitant and scared to believe them since I have also lost some money trying to recover my money back, But my friend assured me that they are very reliably and I decided to try it a try I have never been happy in my life until today, I would advise anyone out here trying to recover your money back you all should trust  BRIGADIA TECH REMIKEABLE If you are a victim of bitcoin scam and believe in recovering all your lost funds, Their insights, and dedication showed me a path to success I never knew existed. This is the Email address you can use to reach them   (Email: brigadiatechremikeable (@) proton.me) Telegram +1(323) 9 1 0 1 6 0 5
