### ISSUE TITLE
Difference in derivation path p2pkh

### ISSUE THREAD

**Issue by nullsavvy** [spesmilo/electrum#8562]
Using the following BIP32 Extended Key at http://bip32.org
xprv9s21ZrQH143K2RNTXyvRSpYo18F2u9zxag3PwCqZgZbyEATwSERJQixPzL5cXHrV7EiVPTWp1u5UTZ1gdYqcRVqf2bf4iapyxsLDYM7Vd68
and the custom derivation path m/44'/0'/0'/0/...

Gives addresses that are equal to Electrum (menu select; Wallet -> Private keys -> Export) up to the address at index 19
Starting from index 20 up to 29 the addresses in Electrum are not equal to the addresses at http://bip32.org

Electrum v4.4.5 (index 0): 1ZCvL8v6H1qehbZMybhrgN3CSUfNaCd7c
http://bip32.org (m/44'/0'/0'/0/0): 1ZCvL8v6H1qehbZMybhrgN3CSUfNaCd7c
.................
Electrum v4.4.5 (index 18): 12wWHxCNxPrJLfBeLxuF7Kre8bRPNRgkUw
http://bip32.org (m/44'/0'/0'/0/18): 12wWHxCNxPrJLfBeLxuF7Kre8bRPNRgkUw

Electrum v4.4.5 (index 19): 1ExNZ3wknG2AvxmRwWVZ4KyFxFEaig1Mc2
http://bip32.org (m/44'/0'/0'/0/19): 1ExNZ3wknG2AvxmRwWVZ4KyFxFEaig1Mc2

Electrum v4.4.5 (index 20): 1Pf4nvfsT2CKwLQnYcgPxJwhPYYyNC9gCV
http://bip32.org (m/44'/0'/0'/0/20): 1DCcxvVrj6tFrPfg4YZWYme4BYNS1d34D6

Electrum v4.4.5 (index 21): 1Kpxk91gKVd2NxV3rUrXZSh1qvSVmh1ANU
http://bip32.org (m/44'/0'/0'/0/21): 1NHueDEy5KtRjTtw6UviZee92MC81P8itw
.......
Electrum v4.4.5 (index 29): 15xLDSDTwDFScUh3LyswwUk8kCvt7P9BbU
http://bip32.org (m/44'/0'/0'/0/29): 19vy187GqLmUKmYcDhYVJVp3jceYU4Fo1f

Why?

**Comment by SomberNight** [comment]
How did you create the Electrum wallet with that xprv? Please give exact steps.

**Comment by iancoleman** [comment]
Related to https://github.com/iancoleman/bip39/issues/639

Steps to create the Electrum wallet:

File -> New

Standard Wallet

I already have a seed

Options -> BIP39

`mystery sorry truck rural express wait method winner enforce logic gospel silent alone fantasy ride pilot price pool token chair dress mansion canvas current`

Legacy (p2pkh)

Wallet -> Export

**Comment by SomberNight** [comment]
> Electrum v4.4.5 (index 20): 1Pf4nvfsT2CKwLQnYcgPxJwhPYYyNC9gCV
http://bip32.org/ (m/44'/0'/0'/0/20): 1DCcxvVrj6tFrPfg4YZWYme4BYNS1d34D6

The path to `1Pf4nvfsT2CKwLQnYcgPxJwhPYYyNC9gCV` is `m/44'/0'/0'/1/0`.
Electrum by default generates `m/0/{0-19}` and `m/1/{0-9}`.

![pic1](https://github.com/spesmilo/electrum/assets/29142493/7fcba0a5-35c9-456f-ab67-6a6efd4943fa)

**Comment by nullsavvy** [comment]
Thank you very much for the clarification.
