### ISSUE TITLE
I can make Electrum for iOS

### ISSUE THREAD

**Issue by Andrey1029** [spesmilo/electrum#8563]
Hello! I want to participate in Electrum development and add an iOS app to your ecosystem. I already have a strong experience in developing such wallets on iOS. Also I can improve MacOS version.

In my opinion there are very few trusted open-source BTC wallets and unfortunately there are almost no one for iOS. I mean I can’t trust most BTC wallets on the App Store for different reasons. Some of them were made by weird companies and others are not open-source.

And I want to fix it. I’ve already sent my CV to [somber.night@protonmail.com](mailto:somber.night@protonmail.com) and [electrumdev@gmail.com](mailto:electrumdev@gmail.com) but still haven’t got any answer. Maybe I can reach Electrum developers here.

**Comment by ecdsa** [comment]
if you have a recipe to compile the existing mobile GUI for iOS, feel free to submit it.
If you are talking about developing a new GUI, we will not have the resources to review it.

**Comment by SomberNight** [comment]
AFAIK reproducible builds are not possible for iOS. Is this still the case? If so, whoever builds the official binaries for it would become a single point of failure, they could be blackmailed or worse, which we would like to avoid.

This is a key question that needs to be considered before working on an iOS app. One could try to just create a sample app with nothing in it and see if they can reproducibly build that.

**Comment by Andrey1029** [comment]
Yes, I agree, making reproducible builds could be a problem. I will research this issue this week and send you result of my research. 

What's the best way of communication with you? Just comments in this thread or maybe Signal/Telegram?

**Comment by accumulator** [comment]
I'd like to mention that by recently replacing the Kivy client by the QML client, we gained the option to start sharing more and more UI code between the mobile client and the desktop client (as both are now Qt based). This is currently done only very minimally, but at least there's great potential to reduce the code base. 

As Qt/QML also supports iOS, a candidate iOS client would ideally also be based on this framework.

**Comment by Andrey1029** [comment]
Hello @SomberNight 

I explored reproducible builds issue. It's extremely difficult to make them reproducible, we need to make patches to swift language and customize build system.

The best solution is to have third party server for code compiling. In that case developers can't modify code before publishing it, so it's very secure.

**Comment by johnnynanjiang** [comment]
Any progress or followup on this initiative? @just-software-dev @SomberNight 

iOS is a gap worth filling for Electrum I believe, more than happy to be part of the work.

**Comment by ecdsa** [comment]
@johnnynanjiang we are not actively trying to build for iOS. feel free to try if you want to participate
