### ISSUE TITLE
Unable to open my app

### ISSUE THREAD

**Issue by Larry04222** [spesmilo/electrum#8579]
This app is so frustrating, i have not been able to open my eletrum wallet on my pc, it keep giving me error message saying (a problem occured when attempting to sync with the Blockchain. Try manually running resync.cmd)
I have tried this and it has refused to work and i really need to use my money in the act please help me resolve this issues.
![IMG-20230818-WA0007](https://github.com/spesmilo/electrum/assets/142585741/59d44384-0020-4ead-b619-0ea1a512287b)

**Comment by ecdsa** [comment]
You have downloaded bitcoin stealing malware. There is no resync.cmd in Electrum.
DO NOT TRY TO RUN THAT FILE.

Please indicate where you downloaded Electrum from.

**Comment by Larry04222** [comment]
Okay thanks

**Comment by trre123** [comment]
it looks like a very old version of electrum that had the resync option
