### ISSUE TITLE
qt send tab PaymentIdentifier regression: pasting onchain address and "!" amount sometimes raises

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8583]
Two bugs in qt gui send tab:

-----

bugA:
1. open an empty wallet (needs to have zero balance)
2. in send tab, paste `tb1qmjzmg8nd4z56ar4fpngzsr6euktrhnjg9td385` into payto_e
3. type `!` into amount
4. "Not enough funds" error popup appears, click OK
5. click "Clear"
6. paste `tb1qmjzmg8nd4z56ar4fpngzsr6euktrhnjg9td385` into payto_e again
7. type `!` into amount
8. crash reporter appears
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/gui/qt/send_tab.py", line 227, in spend_max
    assert self.payto_e.payment_identifier is not None
AssertionError
```

It is a timing issue/race, steps 5-7 need to be done fast.

-----

bugB:
0. (does not need empty wallet)
1. in send tab, paste `bitcoin:tb1qmjzmg8nd4z56ar4fpngzsr6euktrhnjg9td385` into payto_e
2. type `!` into amount
3. crash reporter appears
```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/gui/qt/send_tab.py", line 228, in spend_max
    assert self.payto_e.payment_identifier.type in [PaymentIdentifierType.SPK, PaymentIdentifierType.MULTILINE,
AssertionError
```
^ maybe we should just also include the BIP21 type there

**Comment by accumulator** [comment]
OP_RETURN output with zero amount now allowed again, 307cf25fd415c3d83139118c93d16f6e2e46b6db
