### ISSUE TITLE
Revealer dialog cuts off text with large fonts

### ISSUE THREAD

**Issue by sorenstoutner** [spesmilo/electrum#8586]
I noticed that the Revealer dialog cuts off text with large fonts (especially noticeable on high DPI screens).

![Standard DPI Layout Problems](https://github.com/spesmilo/electrum/assets/26014704/d30c70eb-eb2a-4099-9056-48da0cef18e5)

![High DPI Layout Problems](https://github.com/spesmilo/electrum/assets/26014704/111bddd3-7d1a-478f-94bd-ca550c8ec725)

This is due to some maximum sizing of items being hardcoded into the layout.

If you like, I would be willing to take a crack at removing the layout restrictions so it could auto resize.  My Qt layout experience is mostly with .ui XML files and C++, but I think it would transition to Python.

**Comment by SomberNight** [comment]
Sure, feel free to see if you can fix it. :)

**Comment by SomberNight** [comment]
fixed in https://github.com/spesmilo/electrum/pull/8587
