### ISSUE TITLE
LNWorker.choose_preferred_address chooses incorrect (old) address

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#8589]
If there are several IP addresses for a given node, [choose_preferred_address](https://github.com/spesmilo/electrum/blob/master/electrum/lnworker.py#L513) chooses the first one. Sometimes this address is the incorrect one - for example ACINQ recently changed their IP address to `3.33.236.230`, but my Electrum still tries to connect to `34.239.230.56`.

I've tried the following fix, seems to work:

```diff
--- a/electrum/lnworker.py
+++ b/electrum/lnworker.py
@@ -491,8 +491,8 @@ class LNWorker(Logger, EventListener, NetworkRetryManager[LNPeerAddr]):
     @staticmethod
     def choose_preferred_address(addr_list: Sequence[Tuple[str, int, int]]) -> Tuple[str, int, int]:
         assert len(addr_list) >= 1
-        # choose first one that is an IP
-        for host, port, timestamp in addr_list:
+        # choose the most recent one that is an IP
+        for host, port, timestamp in sorted(addr_list, key=lambda a: -a[2]):
             if is_ip_address(host):
                 return host, port, timestamp
         # otherwise choose one at random
```

**Comment by ecdsa** [comment]
thank you, fixed in 4d0ec8d1776e1d16c48d49855bd0d58311bdbaf4
