### ISSUE TITLE
HELP Electrum wallet I don't see my bitcoin

### ISSUE THREAD

**Issue by Arti2212** [spesmilo/electrum#8598]
please help! a year later I went into the electrum by my seed phrase, she was faithful I tested. A wallet with balance 0 and an empty transaction history is now opening. I don't remember the key password. What should I do? HELP!!

**Comment by ecdsa** [comment]
an empty history means that your bitcoins have not been stolen.
I guess you might have extended your seed with extra words, and you don't remember them.

**Comment by Arti2212** [comment]
if I make a mistake he doesn't let me on. When registering, he asks to repeat the phrase. Additionally, I tried it in case of losing my password and everything was fine. A year later, I enter it and see 0 on the balance sheet and no operations

**Comment by Arti2212** [comment]
Thanks a lot! You made me check everything carefully. I found a typo in the word. Thank God there was still a copy of the phrase where there was no typo. My inattention almost ruined me. Of the minuses, i started smoking again. Thank you
