### ISSUE TITLE
Delete Local RBF transaction to my wallet and it's dissapperead

### ISSUE THREAD

**Issue by co-s** [spesmilo/electrum#8599]
Transaction successfully got all confirmations, but it was marked as "local" transaction. After all - i decided to delete her - and its dissapperead

Also, theres no opportunity to just find an Private key for this bitcoin wallet :

Wallet : bc1qkve3ld0hzct77gd27eysd8msrr7lfsra9c6tdw
transaction hash : 8ae87f53a708bb55446443236c9c283d8776cbddac692e06f09e662cec886fdc

and screenshot
![telegram-cloud-photo-size-2-5458471544645866426-x](https://github.com/spesmilo/electrum/assets/42977460/c6fb39c1-48bd-4e9b-96c8-c9dc7fca222c)

**Comment by SomberNight** [comment]
> 8ae87f53a708bb55446443236c9c283d8776cbddac692e06f09e662cec886fdc

That tx is mined. Are you sure the selected history item in your screenshot is the same tx? The feerate is different.
You could try connecting to a different server.

What exactly is the issue?

**Comment by co-s** [comment]
So, a had an transaction To my wallet, although this is incoming transaction to My wallet - it was shown as a "Local" transaction 

I tried to send it via "Sign" but it show me an error ( probably because it's not my transaction ) 

And now - the transaction is not existing in History and do not displaying this income 

I tried to find the Adress, but i am using MacOS version and there's no Tab named "Adresses"

**Comment by SomberNight** [comment]
> I tried to find the Adress, but i am using MacOS version and there's no Tab named "Adresses"

menubar>`View`>`Addresses`

How is the local transaction shown in your screenshot related to the other mentioned tx `8ae87f53a708bb55446443236c9c283d8776cbddac692e06f09e662cec886fdc`?

**Comment by co-s** [comment]
Im using MacOS, can you please navigate me - there's no menubar here 
<img width="657" alt="image" src="https://github.com/spesmilo/electrum/assets/42977460/7829a0a1-344c-4161-9938-1ad110efc28c">

**Comment by SomberNight** [comment]
It's top of the screen, not the window, because of how the window manager works on macos.
See e.g. this screenshot:
<img width="1680" alt="screen-shot-2015-06-15-at-11-49-25-am" src="https://github.com/spesmilo/electrum/assets/29142493/551a33ad-13fb-4f0d-a887-b0acc88b0a31">
Notice how File, Edit, View, etc is at the top of the screen instead of the window.

**Comment by co-s** [comment]
Damnn.. you my savior

I found an private key for this wallet, should i Sweep him into my Electrum?
