### ISSUE TITLE
Unconfirmed transaction / change adress

### ISSUE THREAD

**Issue by Meszigues** [spesmilo/electrum#8601]
Hi everyone !
I have an unconfirmed transaction since yesterday and a _change adress_ notification (in yellow).
What does it mean, what can I do ?
The Electrum version I've made the sending with was 4.3.4. I've ugraded to the latest 4.4.6 since then.
Thanx in advance for help.

**Comment by SomberNight** [comment]
This issue tracker is for bug reports and development, not general questions.
For unconfirmed txs, [see e.g. here](https://bitcoinelectrum.com/frequently-asked-questions/#what-does-replaceable-unconfirmed-unconfirmed-parent-low-fee-or-not-verified-mean-in-the-transaction-history).
and for change addresses see https://en.bitcoin.it/wiki/Change
