### ISSUE TITLE
 command line bumpfee giving `attempt to read past end of buffer`

### ISSUE THREAD

**Issue by almqq** [spesmilo/electrum#8603]
Hi, I am trying to increase the fee of a transaction I created (also at the command line)

I tried this:

`$ electrum bumpfee 39e05fa9a63d650c5476e02d79acd3ede9e4813cdb381b2c9087fff25c226728 18`

but got this error message:

`attempt to read past end of buffer`

Electrum ver 4.4.6, Linux machine, Ubuntu 22.04.3 LTS

**Comment by SomberNight** [comment]
Hi. This is because the bumpfee command expects a raw tx, not a txid, as its first argument.
https://github.com/spesmilo/electrum/blob/a560841f3f38292a0241edb123d39ae585376bb3/electrum/commands.py#L781

Though perhaps we could change it to accept either.

**Comment by almqq** [comment]
OK thanks. Yes accepting either would make a lot of sense
Or easier, perhaps be clearer in the documentation (electrum help bumpfee)

**Comment by ecdsa** [comment]
Is it too difficult to combine commands?
`$ electrum gettransaction <txhash> <feerate> | electrum bumpfee - | electrum broadcast -`

**Comment by accumulator** [comment]
This should be useful to add to the examples in the documentation
