### ISSUE TITLE
Incorrect Bitcoin address

### ISSUE THREAD

**Issue by Brux22** [spesmilo/electrum#8606]
I just bought Bitcoin on a website and wanted to send it to my electrum wallet when I made the shipment after I noticed that the bitcoin address was incorrenta. So I clicked again on the address of the wallet in electrum and I noticed that simpre that I try to copy it copies a different one that are these twobc1qv0g248zn8fk5ewudg24upasmzwjp5vwgk0q7rn  bc1q8madz8mjyzgu8e40vek500ygkrnmr7qpqztwa5

**Comment by ecdsa** [comment]
you have malware.

**Comment by Ericrowlowland** [comment]
How much bitcoin did you sent to the address
