### ISSUE TITLE
getconfig does not return default values

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#8607]
If a config variable is not explicitly set in the user config file, `getconfig` will not return its default value.
For example, `electrum getconfig swapserver_url` returns None.

related #8454

**Comment by SomberNight** [comment]
Note that this is not new behaviour. The `getconfig` command never returned default values. But sure, we can try to fix this.

**Comment by SomberNight** [comment]
Relatedly, the type-check happens in the ConfigVar setter, and is side-stepped completely if calling the `setconfig` command.
