### ISSUE TITLE
qml wizard create_seed page layout issues on some devices

### ISSUE THREAD

**Issue by wenesga** [spesmilo/electrum#8611]
Textos cortados nos dispositivos Galaxy Note 4 (Android 6.0.1) e no POCO F4 GT (Android 13)

![20230912_095400](https://github.com/spesmilo/electrum/assets/13321239/944bbbb1-fab1-4e6e-b733-48637521eae5)
![20230912_094638](https://github.com/spesmilo/electrum/assets/13321239/60388097-bba5-4127-99b7-819c4947bc80)

**Comment by SomberNight** [comment]
Thanks for the report.
