### ISSUE TITLE
проблема с выводом средств с кошелька электрум 

### ISSUE THREAD

**Issue by Otezorla** [spesmilo/electrum#8621]
Добрый день при переводе с кошелька на кошелек 100к рублей выдает минимальную комиссию в 35к , и не дает перевести 
вот что пишет 
Сервер вернул ошибку при отправке транзакции.
Попробуйте подключиться к другому серверу или обновить Electrum.

Транзакция была отвергнута из-за слишком большого размера (в байтах).

Помогите найти решение проблемы

**Comment by SomberNight** [comment]
The max standard tx size is 100 KB. You might have many small value inputs.
Try creating multiple smaller value txs that each fit within 100 KB. You can do this by trying to send a lower amount, or by selecting coins/UTXOs manually (using the `Coins` tab).

**Comment by Otezorla** [comment]
откуда могут быть входные данные? если туда уже деньги месяца 3 не поступают вообще

**Comment by helpau** [comment]
@Otezorla можете подробнее рассказать о транзакции(сколько там входных адресов, выходных адресов)? Также полезно знать, из каких UTXO приложение пытается составить требуемую сумму. Если я не ошибаюсь, у Electrum есть некая стратегия выбора UTXO, использующая и объединяющая маленькие UTXO. Возможно, вам поможет опция Coin Control, вы сможете заблокировать маленькие UTXO для формирования транзакций, отправить вашу транзакцию, и объединить маленькие UTXO при более низких комиссия, и в более продвинутом кошельке(без промежуточного сервера).
![image](https://github.com/spesmilo/electrum/assets/30323047/ad6dd192-86a6-48b2-9330-fd3949dd66db)
Auto-generated translation:
can you tell me more about the transaction (how many input addresses, output addresses)? It would also be useful to know which UTXOs the application is trying to compose the required amount from. If I'm not mistaken, Electrum has some kind of UTXO selection strategy that utilizes and aggregates small UTXOs. Maybe the Coin Control option would help, you can block small UTXOs to form transactions, and combine them at lower fees, and in a more advanced wallet (no intermediate server).
