### ISSUE TITLE
Allow non-SSL slectrum server option

### ISSUE THREAD

**Issue by softsimon** [spesmilo/electrum#8629]
**Feature request**

Allow the connection to non SSL electrum servers with for example a switch called "Use SSL" True/False.

**Rationale**

I run a local Electrs instance, but it does not serve on SSL by default, so I am unable to use this server as my self hosted Electrum Server in Electrum. I am required to setup a SSL proxy just to be able to connect.

**Comment by accumulator** [comment]
You can. Use <server>:<port>:t as the server string
