### ISSUE TITLE
QML should allow requests that never expire

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#8631]
The 'never' option was removed from QML at some point, because user access to the requests list had been removed.

Now that we have reintroduced access to the requests list, there is no reason not to have never expiring requests.

**Comment by accumulator** [comment]
I guess this would only generate on-chain requests, not lightning requests.

**Comment by ecdsa** [comment]
> I guess this should only generate on-chain requests, not lightning requests.

why?

**Comment by accumulator** [comment]
> > I guess this should only generate on-chain requests, not lightning requests.
> 
> why?

A bolt11 is not really suited for no expiry. 
1. can only be paid once, so it's different from e.g. a reserved onchain 'donation' address.
2. routing hints can become invalid
3. combined with fallback address might exhaust addresses if invoice don't get paid and user doesn't remove
