### ISSUE TITLE
2FA Fee 

### ISSUE THREAD

**Issue by Xirrrus** [spesmilo/electrum#8638]
It may be a pathetic amount for other users but i have about 15 bucks on etherum. When i try to withdraw it onto a platform the 2FA fee itself is about 14 bucks. Is there a way to lower it or skip through it?

**Comment by ecdsa** [comment]
restore from seed if you dont want to use the service.
see https://electrum.readthedocs.io/en/latest/2fa.html#restoring-from-seed
