### ISSUE TITLE
Block height disappeared from "Coins" tab. Is it somewhere else?

### ISSUE THREAD

**Issue by nostitos** [spesmilo/electrum#8642]
I have half a dozen transsaction that are too low fee, I want to make a single CPFP using an output from of each transactions.

I used to sort UTXO by blockheight to select those with 0, meaning unconfirmed, Now we can't see that anymore.

Has endpoint replaced that column? Doesn't look like an equivalent alternative.

**Comment by ecdsa** [comment]
For confirmed coins, the block height is the first part of the output point:  `height x position x index`
For unconfirmed coins, the format is different. they will still be at the bottom of the list with the default sorting
