### ISSUE TITLE
4.4.5 and 4.4.6 crash on OSX 14.1

### ISSUE THREAD

**Issue by nostitos** [spesmilo/electrum#8643]
Electrum was working fine until I updated the OS, 

"
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               run_electrum [1668]
Path:                  /private/var/folders/*/Electrum.app/Contents/MacOS/run_electrum
Identifier:            Electrum
Version:               4.4.6 (???)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2023-10-08 14:11:16.7275 -0400
OS Version:            macOS 14.1 (23B5056e)
Report Version:        12
Anonymous UUID:        AC28B2B5-32F1-784B-764A-E5691DF09ACE

Time Awake Since Boot: 420 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x7FF8A622AA78)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   run_electrum [1668]

Application Specific Information:
abort() called

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x7FF8A622AA78)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff8a622aa78 ???
1   libsystem_kernel.dylib        	    0x7ff815d4c7ae __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff815d84f30 pthread_kill + 262
3   libsystem_c.dylib             	    0x7ff815ca3a49 abort + 126
4   libc++abi.dylib               	    0x7ff815d3dc72 abort_message + 241
5   libc++abi.dylib               	    0x7ff815d2fe1a demangling_terminate_handler() + 266
6   libobjc.A.dylib               	    0x7ff8159d066b _objc_terminate() + 96
7   libc++abi.dylib               	    0x7ff815d3d0cb std::__terminate(void (*)()) + 6
8   libc++abi.dylib               	    0x7ff815d3d086 std::terminate() + 54
9   libdispatch.dylib             	    0x7ff815bdd5ae _dispatch_client_callout + 28
10  libdispatch.dylib             	    0x7ff815bde7cb _dispatch_once_callout + 20
11  TextInputUIMacHelper          	    0x7ffc17273196 +[TUINSCursorUIController sharedInstance] + 46
12  AppKit                        	    0x7ff8195a8893 -[NSTextInputContext activate] + 526
13  AppKit                        	    0x7ff8193d35cf +[NSTextInputContext currentInputContext_withFirstResponderSync:] + 341
14  AppKit                        	    0x7ff8193d31b1 -[NSApplication updateWindows] + 100
15  AppKit                        	    0x7ff819881fba __38-[NSApplication setWindowsNeedUpdate:]_block_invoke_2 + 51
16  AppKit                        	    0x7ff81988738c ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
17  CoreFoundation                	    0x7ff815e5ef0c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
18  CoreFoundation                	    0x7ff815e5ee31 __CFRunLoopDoObservers + 493
19  CoreFoundation                	    0x7ff815e5e3b3 __CFRunLoopRun + 850
20  CoreFoundation                	    0x7ff815e5da99 CFRunLoopRunSpecific + 557
21  HIToolbox                     	    0x7ff820bc39d9 RunCurrentEventLoopInMode + 292
22  HIToolbox                     	    0x7ff820bc3616 ReceiveNextEventCommon + 201
23  HIToolbox                     	    0x7ff820bc3531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
24  AppKit                        	    0x7ff8193ce6e5 _DPSNextEvent + 880
25  AppKit                        	    0x7ff819cc0ab8 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
26  AppKit                        	    0x7ff8193bfc5a -[NSApplication run] + 603
27  libqcocoa.dylib               	       0x113a5e03e QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 974
28  QtCore                        	       0x10dbd6f27 QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 39
29  QtCore.abi3.so                	       0x10ce6c54a 0x10cd70000 + 1033546
30  Python                        	       0x10a0bf48b cfunction_call + 59
31  Python                        	       0x10a080357 _PyObject_MakeTpCall + 359
32  Python                        	       0x10a158cbc call_function + 876
33  Python                        	       0x10a1560c2 _PyEval_EvalFrameDefault + 25554
34  Python                        	       0x10a080ac8 function_code_fastcall + 104
35  Python                        	       0x10a082b0a method_vectorcall + 202
36  Python                        	       0x10a158c2c call_function + 732
37  Python                        	       0x10a1560c2 _PyEval_EvalFrameDefault + 25554
38  Python                        	       0x10a159923 _PyEval_EvalCode + 2611
39  Python                        	       0x10a080a51 _PyFunction_Vectorcall + 289
40  Python                        	       0x10a08012f _PyObject_FastCallDictTstate + 159
41  Python                        	       0x10a080d38 _PyObject_Call_Prepend + 152
42  Python                        	       0x10a0da8b5 slot_tp_init + 165
43  Python                        	       0x10a0d5d69 type_call + 345
44  Python                        	       0x10a080357 _PyObject_MakeTpCall + 359
45  Python                        	       0x10a158cbc call_function + 876
46  Python                        	       0x10a156208 _PyEval_EvalFrameDefault + 25880
47  Python                        	       0x10a080ac8 function_code_fastcall + 104
48  Python                        	       0x10a158c2c call_function + 732
49  Python                        	       0x10a15609e _PyEval_EvalFrameDefault + 25518
50  Python                        	       0x10a159923 _PyEval_EvalCode + 2611
51  Python                        	       0x10a080a51 _PyFunction_Vectorcall + 289
52  Python                        	       0x10a080722 PyVectorcall_Call + 162
53  Python                        	       0x10a1567a9 _PyEval_EvalFrameDefault + 27321
54  Python                        	       0x10a159923 _PyEval_EvalCode + 2611
55  Python                        	       0x10a080a51 _PyFunction_Vectorcall + 289
56  Python                        	       0x10a082b0a method_vectorcall + 202
57  Python                        	       0x10a158c2c call_function + 732
58  Python                        	       0x10a156208 _PyEval_EvalFrameDefault + 25880
59  Python                        	       0x10a159923 _PyEval_EvalCode + 2611
60  Python                        	       0x10a080a51 _PyFunction_Vectorcall + 289
61  Python                        	       0x10a158c2c call_function + 732
62  Python                        	       0x10a15609e _PyEval_EvalFrameDefault + 25518
63  Python                        	       0x10a080ac8 function_code_fastcall + 104
64  Python                        	       0x10a158c2c call_function + 732
65  Python                        	       0x10a15609e _PyEval_EvalFrameDefault + 25518
66  Python                        	       0x10a159923 _PyEval_EvalCode + 2611
67  Python                        	       0x10a080a51 _PyFunction_Vectorcall + 289
68  Python                        	       0x10a158c2c call_function + 732
69  Python                        	       0x10a156208 _PyEval_EvalFrameDefault + 25880
70  Python                        	       0x10a159923 _PyEval_EvalCode + 2611
71  Python                        	       0x10a080a51 _PyFunction_Vectorcall + 289
72  Python                        	       0x10a158c2c call_function + 732
73  Python                        	       0x10a15616b _PyEval_EvalFrameDefault + 25723
74  Python                        	       0x10a159923 _PyEval_EvalCode + 2611
75  Python                        	       0x10a14fbcb PyEval_EvalCode + 139
76  run_electrum                  	       0x10096bd18 0x100969000 + 11544
77  run_electrum                  	       0x10096c411 0x100969000 + 13329
78  dyld                          	       0x2010373a6 start + 1942

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffdd1294 0x7ff7ffdcd000 + 17044

Thread 2:
0   runtime                       	    0x7ff7ffdef94c 0x7ff7ffdcd000 + 141644

Thread 3:
0   runtime                       	    0x7ff7ffdef94c 0x7ff7ffdcd000 + 141644

Thread 4:
0   runtime                       	    0x7ff7ffdef94c 0x7ff7ffdcd000 + 141644

Thread 5:
0   ???                           	    0x7ff8a622aa78 ???
1   libsystem_kernel.dylib        	    0x7ff815d4a70e kevent + 10
2   select.cpython-39-darwin.so   	       0x109c41d53 select_kqueue_control + 915
3   Python                        	       0x10a0890a6 method_vectorcall_FASTCALL + 278
4   Python                        	       0x10a158c2c call_function + 732
5   Python                        	       0x10a15609e _PyEval_EvalFrameDefault + 25518
6   Python                        	       0x10a159923 _PyEval_EvalCode + 2611
7   Python                        	       0x10a080a51 _PyFunction_Vectorcall + 289
8   Python                        	       0x10a158c2c call_function + 732

**Comment by punndcoder28** [comment]
Facing the same issue on macOS - 14.1 and electrum version - 4.4.6

**Comment by smackenny** [comment]
I had the same issue, had v 4.4.4 in my Mac, it crashed on opening, updated wallet to 4.4.6, same issue.  need access to my wallet, any ideas?

**Comment by smackenny** [comment]
does anyone know a way to get to the Electrum developers so they know about the issue?  I hope I don't have to wait weeks to access my wallet!

**Comment by ecdsa** [comment]
we are aware of the issue. 

Sorry, but I cannot give an estimate of how long it will take to fix this.
If you need to access your funds urgently, you can always restore your wallet from seed on another device.

**Comment by nostitos** [comment]
I recomend green wallet, If your seed was generated on electrum it might be hard to find a compatible wallet. 
Check out Electrum on android.

**Comment by smackenny** [comment]
thanks, but I don’t have an android device.  iPhone, iPad, and MacBook Pro.  all with latest software, and electrum worked on my computer up until the latest software update.  My seed was generated on Electrum.  Thanks for the ideas

**Comment by nostitos** [comment]
Use Sparrow Wallet, it's OSX compatible and allow for direct import of
electrum wallet files.

**Comment by ecdsa** [comment]
> Use Sparrow Wallet, it's OSX compatible and allow for direct import of electrum wallet files.

Please do not recommend that. It will only work if users do not have lightning channels. 
If the wallet has lightning channels, creating copies of the file is dangerous, because channels will be in a revoked state.
If you want to import an Electrum file in another wallet, you need to use the "export backup" function of Electrum, not the wallet file itself.

**Comment by nostitos** [comment]
Good point, Is electrum still generating seeds not compatible with other wallets anyway?

**Comment by ecdsa** [comment]
well, I just installed MacOS Sonoma 14.1 on a new laptop, and I was not able to reproduce the issue.
My laptop is a Macbook Air with a M2 chip.

Can you check the details of your system, what kind of chip dos it have? (to to "about this mac" in the apple menu)

**Comment by smackenny** [comment]
This sounds promising. However, if electrum won’t open, how will it transfer in its files?Sent from my iPhoneOn Oct 11, 2023, at 11:04, ThomasV ***@***.***> wrote:﻿
well, I just installed MacOS Sonoma 14.1 on a new laptop, and I was not able to reproduce the issue.
My laptop is a Macbook Air with a M2 chip.
Can you check the details of your system, what kind of chip dos it have? (to to "about this mac" in the apple menu)

**Comment by smackenny** [comment]
I will send you my system details in a few minutes. Thank you for working on this.Sent from my iPhoneOn Oct 11, 2023, at 12:52, stephen mackenzie ***@***.***> wrote:﻿This sounds promising. However, if electrum won’t open, how will it transfer in its files?Sent from my iPhoneOn Oct 11, 2023, at 11:04, ThomasV ***@***.***> wrote:﻿
well, I just installed MacOS Sonoma 14.1 on a new laptop, and I was not able to reproduce the issue.
My laptop is a Macbook Air with a M2 chip.
Can you check the details of your system, what kind of chip dos it have? (to to "about this mac" in the apple menu)

**Comment by nostitos** [comment]
> well, I just installed MacOS Sonoma 14.1 on a new laptop, and I was not able to reproduce the issue. My laptop is a Macbook Air with a M2 chip.
> 
> Can you check the details of your system, what kind of chip dos it have? (to to "about this mac" in the apple menu)

 I was on beta channel, M1

**Comment by smackenny** [comment]
my wallet just opened!  very good!
thank you
Shm

**Comment by ecdsa** [comment]
my version of the beta is 23B5067a

**Comment by smackenny** [comment]
2.4GHz 8 core intel i9
32 GB 2667MHz DDR4
Sonoma 14.1  the MBP is 16in 2019
it started working again yesterday without any software upgrade from either Apple or Electrum

please let me know if there is anything more I can provide to help trouble-shoot this issue.
Thank you
SHM

**Comment by smackenny** [comment]
also my OS is the same Beta as yours

**Comment by nostitos** [comment]
Updating to Beta 3 fixed it.

**Comment by nostitos** [comment]
Osx
