### ISSUE TITLE
cana ln nao recebe

### ISSUE THREAD

**Issue by mysats** [spesmilo/electrum#8647]
canal ln mesmo com liquides alta nao recebe ,sò envia ,feito swap no trampolim,..teria q fazer na acinq..

**Comment by ecdsa** [comment]
please give more details about the nature of the problem. in English if possible.

**Comment by mysats** [comment]
Hello <https://dictionary.cambridge.org/dictionary/english-portuguese/hello>, my <https://dictionary.cambridge.org/dictionary/english-portuguese/my> fault <https://dictionary.cambridge.org/dictionary/english-portuguese/fault>,don <https://dictionary.cambridge.org/dictionary/english-portuguese/don>'t put <https://dictionary.cambridge.org/dictionary/english-portuguese/put> the <https://dictionary.cambridge.org/dictionary/english-portuguese/the> description <https://dictionary.cambridge.org/dictionary/english-portuguese/description> on <https://dictionary.cambridge.org/dictionary/english-portuguese/on> envoice
-- 
 Enviado com Tuta; aproveite e-mails seguros e sem anúncios: 
 https://tuta.com 


12 de out. de 2023, 10:39 por ***@***.***:
