### ISSUE TITLE
label sync plugin: multiple "sync successful" popups

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#865]
when going to settings -> plugins -> label sync, there are 2 buttons "force upload" and "force download". Using them syncs labels and acknowledges successful sync with a popup.

Sometimes I get multiple popups in rapid succession.

The number of popups depends on how often I went to the plugins settings page (and closed it again)

There should only be one popup.

**Comment by ecdsa** [comment]
ok I get it: it calls connect everytime the user opens the settings window

**Comment by ecdsa** [comment]
fixed in bfb42409488d8bba704e2dd0cd90877ad1874fe6
