### ISSUE TITLE
trying to pay onchain+lightning combined invoice does not allow onchain fallback

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8654]
User on Linux desktop with only onchain funds, reported a merchant generated invoice that can be paid with either LN or onchain: but electrum did not offer paying it via onchain.

The invoice is bip21, contains an onchain addr, and a `lightning` key. The lightning key maps to a bolt11 that lacks a fallback address.

Example invoice:
```
bitcoin:tb1qldfm352fwhu9jq36e7l7dnvvd4phnuf3f5tt67?amount=0.001&message=example11&lightning=lntb1m1pjjan2mpp5mjacensqfnh09tk09fhvkujvkp4p9kkr3ze4qnlvrtfzt39ljefqsp542z3lwu5hup4cwuzwswjhx8p68t0vzft2g52nsf50tl6l4pl0axsdq0v4uxzmtsd3jnzvgcqzynxq8zals8sq9qlzqqqqqqqqqqqqqqqqqqqqqqqqqq9scqrzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cng8vsq5qqq2qqqqqqqqlgqqqqqeqqjqrzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cngq3etvuwr5lpagqqqqlgqqqqqeqqjqv79xevum20qxjhdetsfufh5ujjvmnx0l039dtzcgyt2suyw0wnujn3jv36xrw0ewjqkxrqgt8y95yfweve937tl7ugvkhdltgzhy37qq2w9t3s
```

Cause here: (we only look at the bolt11-fallback address)
https://github.com/spesmilo/electrum/blob/0273659e6e4327289fcb717e64376fa253922469/electrum/gui/qt/send_tab.py#L658
https://github.com/spesmilo/electrum/blob/0273659e6e4327289fcb717e64376fa253922469/electrum/invoices.py#L305-L309

-----

For comparison, here is another invoice that also has bolt11-fallback address in it:
```
bitcoin:tb1qldfm352fwhu9jq36e7l7dnvvd4phnuf3f5tt67?amount=0.001&message=example11&lightning=lntb1m1pjjanx7pp5mjacensqfnh09tk09fhvkujvkp4p9kkr3ze4qnlvrtfzt39ljefqsp542z3lwu5hup4cwuzwswjhx8p68t0vzft2g52nsf50tl6l4pl0axsdq0v4uxzmtsd3jnzvgcqzynxq8zals8sq9qlzqqqqqqqqqqqqqqqqqqqqqqqqqq9scqfppqldfm352fwhu9jq36e7l7dnvvd4phnuf3rzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cngq3etvuwr5lpagqqqqlgqqqqqeqqjqrzjqwfn3p9278ttzzpe0e00uhyxhned3j5d9acqak5emwfpflp8z2cng8vsq5qqq2qqqqqqqqlgqqqqqeqqjqy2n22j06jtgdx3h7uw8ndmfwpsm2wsvsu46lv6fskpahgravy9n8padg36hqlyfg9s7j98qrehvecn89kqmwehmulgxl3muruaef4lcq2fen4w
```

note: test matrix is huge here.
- has lightning with enough liquidity vs has lightning but no liquidity vs lightning disabled
- qt desktop vs qml
- bip21 top-level address vs bolt11 fallback vs both vs neither

**Comment by SomberNight** [comment]
note: it would be good to move as much of this logic into non-gui-specific (shared) code as possible. At least, it would good to abstract away the difference between a bip21 top-level address and a bolt11 fallback address from the GUI.

**Comment by accumulator** [comment]
> note: it would be good to move as much of this logic into non-gui-specific (shared) code as possible. At least, it would good to abstract away the difference between a bip21 top-level address and a bolt11 fallback address from the GUI.

Yes, and it is accessible separately in `PaymentIdentifier`, but not in `Invoice` yet, which is an issue when e.g. paying a saved invoice. I have a patch adding the bip21 specified address in `Invoice.outputs`, but more is needed in the `pay_invoice` call path

**Comment by SomberNight** [comment]
(testing on qt desktop)
https://github.com/spesmilo/electrum/commit/ec8500bd553939b991bf2be4dd5f5e1af7c79fc0 fixes the "has lightning but no liquidity" case
but it does not fix the "lightning disabled" case (which looks like it does not work due to a different bug in the PI code)

Like I said, the test matrix is huge...

**Comment by accumulator** [comment]
ref 6ce8a583fd626b3fa080bae087bf6c5b735af007

**Comment by accumulator** [comment]
@SomberNight I think this can be merged

**Comment by SomberNight** [comment]
Ok, let's close the issue.
I wanted to write unit tests for some of the PI code but did not get around to it.
