### ISSUE TITLE
failed payments to zero amount invoices

### ISSUE THREAD

**Issue by bitromortac** [spesmilo/electrum#8658]
There is a report of a user (@slack-coder) failing to pay zero-amount invoices from lnd to electrum: https://github.com/lightningnetwork/lnd/discussions/8073.

I could reproduce this and there may be an issue with checking the zero-amount condition, see:
https://github.com/lightningnetwork/lnd/discussions/8073#discussioncomment-7359838

**Comment by accumulator** [comment]
Fix in #8659

**Comment by ecdsa** [comment]
thanks
