### ISSUE TITLE
Inaccurate getaddressbalance amount

### ISSUE THREAD

**Issue by adrastee** [spesmilo/electrum#8663]
getaddressbalance  is not accurate:

```
$ ./electrum-4.4.6/run_electrum  getaddressbalance 18jANvQ6AuVGJnea4EhmXiAf6bHR5qKjPB
{
    "confirmed": "0.00099822",
    "unconfirmed": "0"
}
```
But real balance is 30.99099822 BTC
see https://blockchair.com/bitcoin/address/18jANvQ6AuVGJnea4EhmXiAf6bHR5qKjPB
and
https://blockchain.info/balance?active=18jANvQ6AuVGJnea4EhmXiAf6bHR5qKjPB

**Comment by SomberNight** [comment]
(due to p2pk vs p2pkh address scheme)
