### ISSUE TITLE
Private key export does not include private keys for privacy address

### ISSUE THREAD

**Issue by rparp** [spesmilo/electrum#8677]
If your bitcoins are sent to a privacy address, your wallet fails to provide a clear solution to the user on how to sweep the private keys for that address. The only types of addresses you support are change and receiving. The privacy address is listed as a 2nd recieving address but you still cannot export private keys for it.

![image](https://github.com/spesmilo/electrum/assets/100044934/aad7b8a1-8a08-4cb9-99cd-24b6c67812c8)
![image](https://github.com/spesmilo/electrum/assets/100044934/7db97e6d-1a93-4e2c-bd5c-167ee3c8c0c3)
![image](https://github.com/spesmilo/electrum/assets/100044934/f3d41f33-23d1-4dc8-af72-87d11e7f45ed)
![image](https://github.com/spesmilo/electrum/assets/100044934/44f8b239-11c7-4d22-9b59-ae673f4db89b)

This kind of bug prevents the user from sweeping funds into their wallet for spending

https://www.reddit.com/r/Electrum/comments/kckgxo/multiple_publicprivate_keys_in_wallet/
https://bitcoin.stackexchange.com/questions/11433/no-sign-of-my-private-keys-in-electrum-wallet-where-do-i-find-them

**Comment by rparp** [comment]
The wallet shows the public receiving addresses (including those receiving addresses which I used to receive the coins) and the amount of coins received in these transactions. Electrum creates a new receiving address and puts the coins there which makes me extremely uncomfortable as a user.

 My problem is that I can't see the private addresses anywhere and don't feel confident that the coins are still in my possession. I feel uneasy that I cannot see the private addresses anywhere and its disappointing for electrum to move coins like that without user permission. Also if your sending coins to a new receiving address for privacy, why does the export function not include that address.

To move funds to a new receiving address without user input is not legal and makes the app hard to use.

**Comment by SomberNight** [comment]
That does not sound like normal behaviour.

Sounds like you might have downloaded a malicious clone of Electrum or maybe some other malware, which stole your bitcoins.  Double-check the exact URL where you have downloaded Electrum from.
Unfortunately in this case, bitcoin transactions are final, and we have no way to help you recover your coins.

**Comment by rparp** [comment]
https://bitcoin.stackexchange.com/questions/120387/receiving-money-on-electrum/120388#120388

This behavior has been replicated even with a new wallet, new seed and $10. It looks like the behavior of electrum to send your deposits to a new recieving address for privacy is expected behavior. This really throws the ledger off and its impossible for someone to spend your coins from a hardware wallet like coldcard without signing it. Also if there are 2 transactions which happened tied to the same recieve address. we should be able to expand on the recieve address.

Blockchain explorer confirms my balance is correct but electrum does not. 

https://www.blockchain.com/explorer/assets/btc/xpub/xpub6DEuMR1qRNskccxK8Au4aXDW6iLxZGzMT9qLKC3BdTiZHFExnPH92gHVwWmmcjhsiomU4VRNx8sNfaFwNH5k5YDx5DUgwGLuvzrs1uoYE6o

**Comment by SomberNight** [comment]
> This behavior has been replicated even with a new wallet, new seed and $10

Have you done this experiment on a new independent machine with independently downloaded Electrum from the website?

If your machine is compromised by malware, it will steal your coins in every "experiment".

**Comment by rparp** [comment]
Transaction script pictures have been uploaded. As you can see the script for the address ending with suns has no witness so trying to understand what the data means and how to spend

**Comment by rparp** [comment]
Also the wallet was setup as watch only with passphrase downloaded from https://electrum.org/. Dont randomly claim its malware when its downloaded from a legit website.

**Comment by rparp** [comment]
https://bitcoin.stackexchange.com/questions/120387/receiving-money-on-electrum/120388#120388

I’ve seen a lot of users experiencing this lately and it’s extremely sad your devs are not willing to evaluate this vulnerability. Don’t randomly call out malware especially when the app is downloaded from the official website.

I’ve had the funds on a ledger live wallet using ledger live app in watch only on same computer for over a issue and never seen this issue.

**Comment by rparp** [comment]
https://bitcoin.stackexchange.com/questions/11433/no-sign-of-my-private-keys-in-electrum-wallet-where-do-i-find-them

I have the same issue as him and it appears the export function is suppose to spit out all the keys if your app is going to send it to a new receiving address without any user input.
Not a good user experience and no funds can leave a new cold storage wallet with a strong seed without signing

**Comment by rparp** [comment]
The auto consolidation is expected but after that happens, how can the user send funds from the address the consolidated funds are sent to? The UI is extremely confusing on how to spend when this has happened.

**Comment by rparp** [comment]
The address ending with suns is the new address your app is sending the consolidated funds to without user input. It's listed as tx2 on the original receiving address funds are linked to.

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/439e7db1-d99c-41d0-9fda-4c5e0627d94e)

**Comment by rparp** [comment]
https://github.com/spesmilo/electrum/issues/8686

**Comment by rparp** [comment]
https://github.com/spesmilo/electrum/issues/8686

**Comment by ecdsa** [comment]
> The auto consolidation is expected but after that happens, how can the user send funds from the address the consolidated funds are sent to? The UI is extremely confusing on how to spend when this has happened.

No, the auto-consolidation is NOT expected. Electrum does NOT send funds to a new address without user interaction. It is very likely that you have downloaded malware. Please let us know which OS you use, and how you installed Electrum.

**Comment by rparp** [comment]
https://electrum.org/. Win10 and funds were stored on ledger live moved to branch new coldcard mk4.

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/350c8960-31f9-4197-9196-1fda63ac7913)
It has no witness data looking at the transaction script so to spend it, you'd have to sign.

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/ce12e5e2-311c-44f8-b618-55dc346cde7f)
This deposit was confirmed by me so it has signatures

**Comment by ecdsa** [comment]
You mentioned that funds were stored on a hardware wallet (not clear whether it is ledger or coldcard).
Did you, at any point, create a wallet in electrum by entering the 12 words seed you received from ledger?

**Comment by rparp** [comment]
I exported the json out of coldcard. This sets up the wallet in watch only. Here is another transaction where a similar behavior has been replicated.

![image](https://github.com/spesmilo/electrum/assets/100044934/f8414f62-71de-42c8-b67a-6ca4868ef0e7)
![image](https://github.com/spesmilo/electrum/assets/100044934/d76e9375-c928-4d5c-a271-5e3d831de745)

This was for a very small amount.

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/2129b486-b06e-4875-b5b9-239c9e024f58)
![image](https://github.com/spesmilo/electrum/assets/100044934/77a543d8-ab42-4155-b7f8-986f6e485e09)
![image](https://github.com/spesmilo/electrum/assets/100044934/3399bf74-78fd-48cf-a6c1-dc54c5ddf1ac)

**Comment by rparp** [comment]
If I sent to the address ending with suns, it would have witness data in Pkscript like other recieve addresses. The witness data is not there

**Comment by lionkmp** [comment]
@SomberNight  @ecdsa I've read these recent reports of "weird transactions" - not stating that I understand this particular case to any degree, just would like to add a small comment:

At multiple places you asked whether Electrum was downloaded from the real website, or suggested that user might be using a malware version. I don't know - but I'd rather think about leaked seed phrases. (Or even OTHER malware on the computer.) E.g. there was that huge case this year where many users stored seed phrases on LastPass, that was hacked, all data stolen, so I guess hackers are slowly decrypting the encrypted items.  (So any LastPass user is recommended to create a new walled and move funds.) ( https://www.techradar.com/pro/security/lastpass-security-breach-linked-to-a-string-of-crypto-heists ) 

Also there was that fake Ledger Live app directly on Microsoft Store recently (@rparp  you mentioned this app's name, however Mac version is different I guess)  ( https://www.bleepingcomputer.com/news/security/fake-ledger-live-app-in-microsoft-store-steals-768-000-in-crypto/ ) that asked for the seed phrase, which no software should ever ask when using a HW wallet. 

So I'd rather think about attackers already listening to the addresses (or other malware) than a fake Electrum copy. But I guess you have more experience in this, just wanted to add what I see in the news. (Sorry, @rparp I know this comment does not advance your case at all.) (By the way, I totally love that every address is used only once.)

**Comment by rparp** [comment]
I've had the ledger app live for a while holding my funds with no issues. Also the app was downloaded from a website recommended inside the box. Very careful about that.

Malware will mask your original recieve address with something else. Here the recieve addresses are confirmed to be mine as coldcard address explorer shows it.

**Comment by rparp** [comment]
Brand new coldcard device setup with all recommended dice rolls, pin and passphrase.

**Comment by SomberNight** [comment]
Unclear what can be done...
Here is a doc describing re common precautions and malware: https://electrum.readthedocs.io/en/latest/malware.html

**Comment by SomberNight** [comment]
> Brand new coldcard device setup with all recommended dice rolls, pin and passphrase.

@rparp how many dice rolls did you do?

-----

Curious that you opened this issue around ~1 week after [this video](https://www.youtube.com/watch?v=oj_W3xOlt6U) was released publicly about insecure dice-based seeds generated by coldcard.
@ecdsa looks like coldcard allows the user to generate dice-based seeds, and there is an option to either mix the dice-rolls with the device PRNG or use the dice rolls exclusively. There were a few firmware versions where it was easy to select the dice-rolls-exclusively option and there was no minimum number of dice rolls enforced - the fw let you create a seed from just a single dice roll. New firmware now enforces a minimum of 50 dice rolls (~129 bits of entropy).

**Comment by rparp** [comment]
I did 12 word seed with no dice rolls. Very disappointing and shocked.

More than willing to share my Xpub key
