### ISSUE TITLE
mempool min fee not met

### ISSUE THREAD

**Issue by MaxBennett561** [spesmilo/electrum#8679]
v 4.4.6 cannot send BTC. error message

```
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

mempool min fee not met
Your transaction is paying a fee that is so low that the bitcoin node cannot fit it into its mempool. The mempool is already full of hundreds of megabytes of transactions that all pay higher fees. Try to increase the fee. 
```

I have been using this wallet for many years and have never had this issue. i have more than enough funds to cover the stated mining fee. I have tried multiple servers. This errr makes no sense based on my situation.

**Comment by SomberNight** [comment]
What part of the error message is not clear?
Have you tried paying a higher fee? Your chosen fee is simply too low given current prices.

**Comment by MaxBennett561** [comment]
The part that wasn't clear is why the mining fee was 100000% of the amount to be sent. Either nobody was mining last night or their was a major error
