### ISSUE TITLE
strange error sending to p2sh address using btchip "{u'message': u'64: non-canonical', u'code': -26}"

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#868]
I'll say this right away: I fail to reproduce this one, so feel free to close it. But maybe it looks familiar to someone.

I made a transaction to a p2sh address and after signing when trying to broadcast, I get this popup:

![image](https://cloud.githubusercontent.com/assets/589745/4361637/eadc5058-4285-11e4-8385-696935bb94d6.png)

nothing on console.

I tried again, then it worked.

any ideas?

**Comment by btchip** [comment]
Very likely fixed with 1.4.14, can be closed
