### ISSUE TITLE
Was I scammed?

### ISSUE THREAD

**Issue by MaxBennett561** [spesmilo/electrum#8681]
Electrum was going Haywire for me last night. I attempted to send a transaction and I was charged a very very large mining fee  but the transaction was never sent to the intended recipient. It appears as though I was charged a mining fee for nothing. The transaction ID:  f345babe6550b85bc61520cb87c12f53255916d62d0012c7038292ceba9c3ca6

Can someone help me understand what happened with this transaction? Was I scammed?

**Comment by ecdsa** [comment]
The transaction shows a very high fee, indeed. Note that Bitcoin mining fees are not "charged", they are chosen by the sender. If you have ever sent other bitcoin transactions, you should know that. Electrum gives you multiple ways of choosing your mining fee. You do not seem to be aware of that, was it your first transaction with Electrum?

As for the recipient of the transaction, it is not possible for me to tell. Did you receive an invoice with a different address? did you copy and paste a bitcoin address in Electrum? Some bitcoin-stealing malware works by detecting bitcoin addresses in the clipboard, and replacing them with a different address. Maybe you could check that.

**Comment by MaxBennett561** [comment]
I have done more than 100 blockchain transaction in my time. The fee that I was charged was not the amount negotiated at the time of initiation. The strange part is electrum platform confirmed and broadcasted the correct transaction amount. I then came back to electrum some hours later and the original transaction was broken down to unrecognizable amounts and the final recipient is not an address I  know. The intended address was completely different. I never agreed to that mining fee nor did I type in the address of the final recipient at any point. Again I have done many transactions using many different wallets and exchanges. This is the only transaction that I can look at the details and have no clue how it transpired.

**Comment by MaxBennett561** [comment]
I was running it on a Mac and behind multiple layers of security and on a foreign location VPN address. Not sure how someone would invade that or why. I'm not doing large transactions.

**Comment by MaxBennett561** [comment]
Also when I review my sent transaction history list on Electrum it still shows all transactions from that day as unpaid.

**Comment by ecdsa** [comment]
what you are describing looks like theft from bitcoin-stealing malware. 
maybe your password has been stolen when you signed the transaction, and it has been replaced with the new one.

**Comment by rparp** [comment]
@MaxBennett561 It appears the application has a bug. Firstly, if you dont send your funds within a certain amount of time, it auto consolidates your UTXO's. Once they are consolidated, a address linked to your inputs holds the funds. Electrum will list it as tx2 to your original recieve address.

The developer does not know how to fix this and and it's sad every related post gets tagged as malware with no response to it

**Comment by rparp** [comment]
The funds can never leave your hardware wallet without you creating and signing a tx. I think electrum is very buggy and this is a security issue which needs to be looked at.

**Comment by nostitos** [comment]
Don't listen to what @rparp is saying, What he's saying makes no sense, 

Also, Electrum is one of the most trust worthy wallet out there.

**Comment by rparp** [comment]
https://github.com/spesmilo/electrum/issues/8686 Answer this from another user

**Comment by rparp** [comment]
I dont think the funds are stolen. Electrum is auto consolidating the UTXO and sending it to a address which is listed as tx2 in recieving transaction

**Comment by nostitos** [comment]
What's do you mean by tx2?

What does it matters that it consolidate?

Coins are either sent to addresses of the wallet or they're not.

**Comment by rparp** [comment]
The recieve addresses are confirmed to show on coldcard but the address where the program sends your coins to is dropped from address list.

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/fcc83d62-f382-489d-8e2e-9229074be9cd)
![image](https://github.com/spesmilo/electrum/assets/100044934/b6b7a177-fa92-44e7-b2ba-8f0578464eb8)

**Comment by rparp** [comment]
The inputs can be confirmed on coldcard using the address explorer but not sure what the address ending with suns is.

**Comment by rparp** [comment]
https://github.com/spesmilo/electrum/issues/8686 Another user with same issue

**Comment by ecdsa** [comment]
> I dont think the funds are stolen. Electrum is auto consolidating the UTXO and sending it to a address which is listed as tx2 in recieving transaction

No, Electrum is not doing that.

**Comment by rparp** [comment]
> I have done more than 100 blockchain transaction in my time. The fee that I was charged was not the amount negotiated at the time of initiation. The strange part is electrum platform confirmed and broadcasted the correct transaction amount. I then came back to electrum some hours later and the original transaction was broken down to unrecognizable amounts and the final recipient is not an address I know. The intended address was completely different. I never agreed to that mining fee nor did I type in the address of the final recipient at any point. Again I have done many transactions using many different wallets and exchanges. This is the only transaction that I can look at the details and have no clue how it transpired.

Can you share your transaction id and script

**Comment by SomberNight** [comment]
Unclear what can be done...
Here is a doc describing re common precautions and malware: https://electrum.readthedocs.io/en/latest/malware.html
