### ISSUE TITLE
Anything i can do?

### ISSUE THREAD

**Issue by tide88** [spesmilo/electrum#8686]
Just had all my currency stolen from my wallet. I made a deposit from coinbase and then there was an outgoing transaction for the btc balance in the wallet. Whats strange is the two transactions had the same timestamp. Anything i can do?

**Comment by rparp** [comment]
Can you post screenshots of your ledger

**Comment by rparp** [comment]
Does it show the deposit made and then another transaction which says spent equal to the same deposit amount

**Comment by tide88** [comment]
i see nothing about "spent equal". What exactly is the Ledger?

**Comment by rparp** [comment]
Are you using electrum? If so can you click a snapshot of your history and send it here

**Comment by tide88** [comment]
![ledger](https://github.com/spesmilo/electrum/assets/133076989/19537892-43a1-4624-89c1-aa2ef517de1c)

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/e63e0657-8837-4b00-a01f-6b3431fd9784)
Same issue here

**Comment by rparp** [comment]
I made one more deposit to see if that fixes it but no

**Comment by rparp** [comment]
Looks like its a bug

**Comment by rparp** [comment]
Can you upload address tab picture

**Comment by tide88** [comment]
![ledger address](https://github.com/spesmilo/electrum/assets/133076989/56879e4d-b285-4b2e-9875-ca42eb03edb1)
![ledger trans](https://github.com/spesmilo/electrum/assets/133076989/cd992d96-eeda-4262-beb8-57f28274a2e8)

**Comment by rparp** [comment]
The address at output is not listed as wallet address or change address correct?

**Comment by tide88** [comment]
No its not from what i can see.

**Comment by rparp** [comment]
I’m so stuck here with same issue. How does one spend from these addresses given the UTXO exists there.

**Comment by ecdsa** [comment]
@tide88 both transactions have the same timestamp because they were mined in the same block.
Can you tell us which operating system you use, and where /how did you download Electrum?

**Comment by rparp** [comment]
https://electrum.org/ This was the website I downloaded from

**Comment by rparp** [comment]
Also if there is malware, the receive addresses where funds are received cannot be confirmed on device itself

**Comment by ecdsa** [comment]
@rparp could you please answer in the issue that was opened by you, instead of here? this issue was opened by @tide88, and there is no indication that they used a hardware wallet. Adding comments relative to your own case to issues opened by other people only increase the confusion. Thank you.

**Comment by rparp** [comment]
@tide88 What wallet are you using? Coldcard!

**Comment by rparp** [comment]
Can you put your transaction in blockchain explorer and show the transaction script for the output address

**Comment by tide88** [comment]
> @tide88 What wallet are you using? Coldcard!

Electrum 4.4.6 on a  usb

**Comment by tide88** [comment]
> Can you put your transaction in blockchain explorer and show the transaction script for the output address

![blkchn out](https://github.com/spesmilo/electrum/assets/133076989/c65e5a8a-d505-4442-a0c7-41713338c78e)

**Comment by tide88** [comment]
> https://electrum.org/ This was the website I downloaded from

thats where i dl from

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/354b5a0d-978e-465d-8c16-b6dec15690fe)
Here how it should look for the output which holds your currency. Can you share?

Please use blockchain explorer

![image](https://github.com/spesmilo/electrum/assets/100044934/af652857-65cc-4c9a-b020-3bd707fba717)

**Comment by rparp** [comment]
https://www.blockchain.com/explorer Add your transaction ID in search explorer

**Comment by rparp** [comment]
> > @tide88 What wallet are you using? Coldcard!
> 
> Electrum 4.4.6 on a usb

I used airgapped Coldcard MK4 - NEW ONE

**Comment by rparp** [comment]
Also please upload your scripts for one of your deposits which get sent to output without your input

**Comment by tide88** [comment]
> https://www.blockchain.com/explorer Add your transaction ID in search explorer

https://www.blockchain.com/explorer/transactions/btc/1b04513fa0335b4e7b1cee762469cbbe8e08d0cb95dabfe4ee9ae15113070015

**Comment by tide88** [comment]
> Also please upload your scripts for one of your deposits which get sent to output without your input



> Also please upload your scripts for one of your deposits which get sent to output without your input

![Uploading deposit btc.png…]()

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/a7c77755-68e7-4d82-bda4-1c4d165afb1d)
Same as mine

**Comment by rparp** [comment]
![IMG_0052](https://github.com/spesmilo/electrum/assets/100044934/3498c6ff-428e-42f6-9944-a44c590b402c)

this is yours.

lol I don’t know why this is done and how to handle this from UI

**Comment by rparp** [comment]
If this was signed it would contain witness data but it does not.

**Comment by rparp** [comment]
![image](https://github.com/spesmilo/electrum/assets/100044934/ff9ee7c5-9007-4ace-9b70-50d5d26b0cd0)

**Comment by rparp** [comment]
![IMG_0053](https://github.com/spesmilo/electrum/assets/100044934/e91d616e-b138-42e1-a755-5baf856b48f1)
This is signed confirmed to be used by us as a receiver

**Comment by tide88** [comment]
Well thanks for the help. I guess im just screwed

**Comment by rparp** [comment]
No your not screwed. Look at the transaction script for the address at your output. It has no witness data so your funds are on your wallet

**Comment by rparp** [comment]
Which wallet are you using and what software?

**Comment by tide88** [comment]
> Which wallet are you using and what software?

Electrum 4.4.6 portable

**Comment by rparp** [comment]
Which hardware wallet along with your electrum software? Ledger live or coldcard or trezor

**Comment by tide88** [comment]
Im just using Electrum

**Comment by rparp** [comment]
So no hardware wallet with it. Just a hot new wallet on electrum?

**Comment by tide88** [comment]
Yes, electrum is installed on a usb

**Comment by rparp** [comment]
Interesting. I’ve seen this behavior on sparrow, electrum and specter. I had blockchain analyst look at mine and he said it’s coinmixing and coinjoin.

Unchained capital will be helping me going back to ledger live wallets

**Comment by tide88** [comment]
I will have to rethink my security

**Comment by rparp** [comment]
I’m happy to use a hardware wallet so funds can never leave without my signature from the device and I also use it airgapped. Given the three apps show this behavior, it looks like they all pull their dough from the same bucket and it’s just a different front end for each

**Comment by tide88** [comment]
> I’m happy to use a hardware wallet so funds can never leave without my signature from the device and I also use it airgapped. Given the three apps show this behavior, it looks like they all pull their dough from the same bucket and it’s just a different front end for each

I will defiantly be going that route

**Comment by rparp** [comment]
If you dont mind me asking, how many BTC did you deposit. You can try contacting Unchained capital as well

**Comment by tide88** [comment]
> @tide88 both transactions have the same timestamp because they were mined in the same block. Can you tell us which operating system you use, and where /how did you download Electrum?

Win11 always dl from https://electrum.org/

**Comment by tide88** [comment]
> If you dont mind me asking, how many BTC did you deposit. You can try contacting Unchained capital as well

.0105 was the last deposit

**Comment by kkrott877** [comment]
Well, just looking by the screenshot shared it's crystal clear to me that you guys used a fake version of the electrum wallet. like this one from this post on reddit.

https://www.reddit.com/r/Electrum/comments/9yg8dx/psa_it_seems_that_on_ubuntus_software_center_a/

**Comment by SomberNight** [comment]
Unclear what can be done...
Here is a doc describing common precautions and malware: https://electrum.readthedocs.io/en/latest/malware.html
