### ISSUE TITLE
Cannot translate: "7% of amount", "Unpaid"

### ISSUE THREAD

**Issue by lionkmp** [spesmilo/electrum#8689]
This string part is always English (Electrum 4.4.6). This is shown when amount of transaction fee looks too high and a little note is appended to the string saying e.g. ("7% of amount")

https://github.com/spesmilo/electrum/blob/4006a2f54899f5149e69beb1a2de05342b0021c7/electrum/wallet.py#L3021

Attached a screenshot from Linux release, and at bottom the Android release too.

![btc_amount_of](https://github.com/spesmilo/electrum/assets/5088657/ca6e4c97-67c7-4746-b050-f37b891349c2)

And as a sub-bug, "Unpaid" is also English, on Android: (This one appears on "Transifex", translated to Hungarian 7 months ago, and appears to be English in 4.4.6.)

![android_electrum_04_mentve](https://github.com/spesmilo/electrum/assets/5088657/f4f80ea3-2eed-4a01-b2d3-3f518fb71736)
![android_electrum_05_fizetes](https://github.com/spesmilo/electrum/assets/5088657/154691e5-f740-4b28-bd83-ec079217540e)
![android_electrum_06_fizetes2](https://github.com/spesmilo/electrum/assets/5088657/88c8a1d4-486a-498f-957e-585b290d1058)

Excuse me for coming with such a small issue. :) Thanks in advance!

**Comment by accumulator** [comment]
thanks for reporting
