### ISSUE TITLE
BTChip setup process: 2 occurences of "BTChip dongle not found" for no apparent reason

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#869]
During setup procedure, after clicking next on the following screen, the shown popup pops up (doesn't depend on any preconditions, this has happened every time I tried the setup procedure so far)

![image](https://cloud.githubusercontent.com/assets/589745/4362019/a1d4c4c2-4289-11e4-94b4-16723eabb1dc.png)

console says: 

```
=> e0c4000000
```

(side-remark: its confusing to have yes/no buttons here since no question was asked. The user is told to click 'OK', which is not even an option.)

clicking yes (without replugging the device) just repeats '=> e0c4000000' on the console.

clicking yes (with replugging the device) show this popup:

![image](https://cloud.githubusercontent.com/assets/589745/4362052/eeca317c-4289-11e4-856e-fe1c52c0b43c.png)

(essentially the same one, just the dialog in the background is closed)

also console says this:

```
=> e0c4000000
```

only after replugging once again does the process continue.

It's not apparent to me why a replug at this point is necessary, let alone 2 in rapid succession.

**Comment by btchip** [comment]
Detection issues should also be fixed in 1.4.14
