### ISSUE TITLE
keyboard not resize in android electrum wallet

### ISSUE THREAD

**Issue by GabrielRCL** [spesmilo/electrum#8691]
im using Samsung Galaxy A01 and bitcoin electrum wallet
When I go to enter my seed to recover my bitcoin wallet the keyboard does not resize and I cannot press the "P" key

video:
https://www.veed.io/view/f015eceb-b39d-4de0-a22e-9b146904c9ac

**Comment by accumulator** [comment]
duplicate of #8611, and already fixed. This will be available in the next release.
