### ISSUE TITLE
Проблема с подписанием 

### ISSUE THREAD

**Issue by Frenkiroma** [spesmilo/electrum#8692]
Доброе утро у меня такая проблема до этого я сделал три перевода и все четко!!!а сейчас не могу подтвердить транзакцию!!!на воду на кьюар код и меня переводит на страницу перевода но без кнопки потвердить вот что остаётся на экране больше не чего сделать не могу!!!!,как быть дальше эта транзакция удалена!что на фото
![Screenshot_20231116-013448](https://github.com/spesmilo/electrum/assets/150979411/4e1ac953-1001-45c3-bc8a-019fc3319eb2)
 Вот
![Screenshot_20231116-013454](https://github.com/spesmilo/electrum/assets/150979411/791dbd11-4bf6-4c60-a4ea-9b99efba5f75)

**Comment by Frenkiroma** [comment]
Но перевод будет на этот кошелек

**Comment by SomberNight** [comment]
I don't understand the issue. What exactly is the problem?
As shown on your image, that tx is a *local* transaction. You can try deleting it, or broadcasting/publishing it.

**Comment by Frenkiroma** [comment]
Вот как мне опубликовать или транслировать эту транзакцию я не могу понять
у меня не получается ничего

пт, 17 нояб. 2023 г., 18:33 ghost43 ***@***.***>:

**Comment by accumulator** [comment]
The transaction shown in the screenshot is Unsigned, and the wallet itself is a watch-only wallet. 

You can only sign transactions from wallets that contain private key or seed

**Comment by Frenkiroma** [comment]
![Screenshot_20231123-204320](https://github.com/spesmilo/electrum/assets/150979411/a591b148-7a0d-4266-8278-63e95bf0c7f2)в![Screenshot_20231123-204256](https://github.com/spesmilo/electrum/assets/150979411/c56a62f4-9225-4c51-a95a-67f96716a5ed)
Вот почему в в одном кошельке я могу посмотреть есть ключ а в другом нет

**Comment by Frenkiroma** [comment]
Как восстановить исходный кошелёк с закрытыми ключами если удалили
приложение с телефона

чт, 23 нояб. 2023 г., 16:31 accumulator ***@***.***>:

**Comment by Frenkiroma** [comment]
Смотрите у меня есть доступ к кошельку который предназначен только для просмотра!!! В нём нету сид ключей! Телефон на котором был установлен основной кошелёк приложения удалили на нём!!!! Жена думала обновить его скачав по новой и всё заработает! Решила с умничать.
А кошелёк с исходными кодами удалён! Мне нужно или как то востоновить сид фразу или хотя бы вывести финансы
И есть приватный мастер ключ! Что можно сделать что бы вывести финансы

**Comment by SomberNight** [comment]
Stop opening multiple issues for the same problem. (https://github.com/spesmilo/electrum/issues/8702, https://github.com/spesmilo/electrum/issues/8707)

You should have written down your seed words on *paper* as instructed by the program when creating the wallet (or at least should have made some type of backup).

A watching-only wallet *cannot* be used to spend your money, it is for *watching only*. Having just the watching-only wallet is basically useless. If you deleted the original wallet, and you don't have your seed words, you have lost the money and there is nothing anyone can do to help.

-----

From the translation, it seems you are saying you have a master private key. I assume it is actually a master public key though. What are the first four letters of it?
