### ISSUE TITLE
How to restore bip21 URI opening with electrum?

### ISSUE THREAD

**Issue by nostitos** [spesmilo/electrum#8696]
We've clicked in btcpay "Register with payment links"

![image](https://github.com/spesmilo/electrum/assets/48504624/86ef05ef-6e14-490c-9100-a8f97b701fc6)

I used to be able to reinstall electrum and it'd take back control of URI links but not anymore.

Should there be a place in settings to restore that assignation?

**Comment by ecdsa** [comment]
could you give more context? what are you trying to do?

**Comment by nostitos** [comment]
That when I click a bitcoin: link it opens electrum not a browser tab with btcpay

**Comment by accumulator** [comment]
In Firefox, you can select the action to take from Settings > General > Applications

**Comment by SomberNight** [comment]
Note that we have some code that should install the OS-level association for windows and macos:
https://github.com/spesmilo/electrum/blob/8db68cadcd44af2c62d4d36e6558084d053a9e92/contrib/build-wine/electrum.nsi#L135
https://github.com/spesmilo/electrum/blob/8db68cadcd44af2c62d4d36e6558084d053a9e92/contrib/osx/osx.spec#L129
