### ISSUE TITLE
Как востоновить сид фразу!?

### ISSUE THREAD

**Issue by Frenkiroma** [spesmilo/electrum#8702]
В общем остался кошелёк только для просмотра основной кошелёк случайно короче удалили приложение и сидит сразу вместе с ней как восстановить Сид фразу

**Comment by Frenkiroma** [comment]
Подскажите как можно восстановить Сид фразу без короче основного кошелька со всеми ключами есть только кошелёк для просмотров

**Comment by SomberNight** [comment]
It is hard to understand you.
However,
- if you have your seed words, you can restore from that
- if you have your wallet file and password, just use that
- if you have neither, you are out of luck.

**Comment by Frenkiroma** [comment]
Смотрите у меня есть доступ к кошельку который предназначен только для просмотра!!! В нём нету сид ключей! Телефон на котором был установлен основной кошелёк приложения удалили на нём!!!! Жена думала обновить его скачав по новой и всё заработает! Решила с умничать

**Comment by Frenkiroma** [comment]
Вот кошелёк с исходным кодом удалён с телефона жены!!!! Как можно востоновить сид фразу или хотя бы сделать вывод средств!?
