### ISSUE TITLE
Submarine Swap error

### ISSUE THREAD

**Issue by git70** [spesmilo/electrum#8703]
Hi

Electrum 4.4.6 Appimage

When trying to do a Submarine Swap on Electrum Trampoline I get this error:

```ClientResponseError(RequestInfo(url=URL('https://swaps.electrum.org/api/createswap'), method='POST', headers=<CIMultiDictProxy('Host': 'swaps.electrum.org', 'User-Agent': 'Electrum', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '619', 'Content-Type': 'application/json')>, real_url=URL('https://swaps.electrum.org/api/createswap')), (), status=500, message='Internal Server Error', headers=<CIMultiDictProxy('Server': 'nginx/1.18.0', 'Date': 'Thu, 23 Nov 2023 20:07:23 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '55', 'Connection': 'keep-alive')>)```

What can I do to diagnose the problem?

**Comment by Jalibiya** [comment]
Check and see if you have internet connection

**Comment by ecdsa** [comment]
Normal swaps (from on-chain to lightning) have been temporarily disabled due to a protocol change.
They will be enabled in the next version of Electrum.

**Comment by callcenter1aa** [comment]
same problem, any solution ?
