### ISSUE TITLE
btchip error when signing in non-hardened mode: Invalid status 6a80

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#871]
With BTChip setup up in PIN-only (non-hardened) mode, I tried to sign a message, after seeing 'checking device' for a couple of seconds (not seeing 'signing'), I am getting this error:

![image](https://cloud.githubusercontent.com/assets/589745/4362407/b7eef6e4-428c-11e4-8566-f735d8e962e5.png)

nothing related on the console

**Comment by btchip** [comment]
Error message added in the upcoming commit
