### ISSUE TITLE
Not enough funds for lightning so it gives me the option to swap but this fails.

### ISSUE THREAD

**Issue by marcusdeman** [spesmilo/electrum#8715]
ClientResponseError(RequestInfo(url=URL('https://swaps.electrum.org/api/createswap'), method='POST', headers=<CIMultiDictProxy('Host': 'swaps.electrum.org', 'User-Agent': 'Electrum', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '619', 'Content-Type': 'application/json')>, real_url=URL('https://swaps.electrum.org/api/createswap')), (), status=500, message='Internal Server Error', headers=<CIMultiDictProxy('Server': 'nginx/1.18.0', 'Date': 'Fri, 01 Dec 2023 08:31:12 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '55', 'Connection': 'keep-alive')>)

Getting this problem.

Running latest Electrum 4.4.6

**Comment by ecdsa** [comment]
normal swaps (from on-chain to lightning) have been temporarily disabled
they will be available again with the next release.
sorry for the inconvenience.

**Comment by SomberNight** [comment]
Maybe we should serve a human-readable error to the client (even if this needs changing client logic and won't help in the current instance).

**Comment by SiLiKhon** [comment]
@ecdsa should they be working now? getting "Swap service unavailable" on 4.5.4 (Android)

**Comment by ecdsa** [comment]
sorry, I restarted the daemon without enabling the plugin
it should work now.
