### ISSUE TITLE
trezor safe 3 not compatible?

### ISSUE THREAD

**Issue by needmorebattery** [spesmilo/electrum#8722]
when i try to connect my new trezor safe 3 to electrum, it says this version of trezor is not supported... has anyone else experienced this? i have the trezor python scripts installed and the udev codes in the rules.d folder.  The wallet recognizes the hardware, however it says it is not supported.

**Comment by SomberNight** [comment]
Can you test with newer [trezorlib](https://pypi.org/project/trezor/) (python-trezor)?
What version are you trying?
E.g. `$ pip install --upgrade trezor`

@prusnak Could we ask for some devices of this new model for development/testing purposes? :)

**Comment by prusnak** [comment]
> @prusnak Could we ask for some devices of this new model for development/testing purposes? :)

Please send me the shipping address(es) to my email and I'll try to arrange that.

**Comment by needmorebattery** [comment]
Trezor firmware 2.6.3, up to date.
using electrum 4.4.6, newest version.
i have not yet tried command line trezor
as of today, still says unsupported
thanks for the help

**Comment by needmorebattery** [comment]
it was the trezorlib you were speaking of, however i just havent had the
chance to dive into the command line.
i am running mint and electrum is the appimage.

**Comment by sashazykov** [comment]
Works for me on mac os. Tested restoring an existing wallet and signing transactions.

**Comment by alexrecuenco** [comment]
Same here!

- It works with Version 4.5.0b1
- It doesn't work with Version 4.4.6 (unsupported error mentioned above)

Would it be a lot of effort to consider creating a 4.4.7, backporting the trezorlib upgrade?

**Comment by prusnak** [comment]
> Would it be a lot of effort to consider creating a 4.4.7, backporting the trezorlib upgrade?

Why you don't want to use 4.5.0?

**Comment by alexrecuenco** [comment]
Maybe I am mistaken, but I just saw 4.5.0 reach beta on Dec 19th, so I was imagining a couple more months on that stage, if not more.

I would prefer not to use beta-software when handling bitcoin. Is that a bit too much scrutiny?

Or do you consider electrum 4.5.0-b1 to be stable already? 


In any case, if it is something that is non-trivial, please disregard my suggestion. I wouldn't want anyone to waste time.

**Comment by prusnak** [comment]
> electrum 4.5.0-b1 to be stable already?

I am not talking about 4.5.0-b1, I was talking about 4.5.0. But now I understand what you meant by your comment: that you have no reason why not to use 4.5.0 when it reaches stable release.

**Comment by alexrecuenco** [comment]
Perhaps I explained myself poorly, so just to fully clarify:

I will say that my only concern is with using software in beta for financial transactions. I do plan to use 4.5.0 (although the change is quite significant, so I might wait a month or two after release to make sure everything is ok) 

Thank you for your time @prusnak :)

**Comment by SomberNight** [comment]
Consider the 4.5.0 beta to be a release candidate, we just can't easily put rc in the name due to some limitations with what update checks in old versions can parse. And we did not want to do a "full" release (that ~everyone will download) so close to xmas, not having proper time for follow-up bugfix releases, but still wanted to do *a* release because of lots of fixes on master. Seeing you are a technical user, by all means upgrade.

**Comment by zx9r** [comment]
I am running trezorlib 0.13.8 and Electum 4.5.2

I installed trezorlib with:

```
pip3 install --upgrade trezor
pip3 install --upgrade trezor[hidapi]

```
Connected a new Trezor Safe 3 and it seems electrum recognizes it well. However when creating a new wallet and initalizing the device (just before the step when the 12 seed words would be created) Electrum says this error:

`RuntimeError('UnexpectedMessage: Unexpected message')`

Also I can see this in electrum logs:

> 18.19 | W | gui.qt.wizard.wallet.WCChooseHWDevice | error getting device infos for safe_t: Missing libraries for safe_t. //     ModuleNotFoundError("No module named 'safetlib'") // Make sure you install it with python3

How can I install that safetlib module ?

**Comment by prusnak** [comment]
> How can I install that safetlib module ?

Don't worry. This error is unrelated to Trezor. You should still be able to use Trezor without that library (which is for another wallet).

**Comment by zx9r** [comment]
OK, but what about the error when trying to generate the 12 words seed?

> RuntimeError('UnexpectedMessage: Unexpected message')

I get this error in Electrum and nothing else happens so I cannot create the seed and initialize the wallet

**Comment by prusnak** [comment]
Open a new issue please.

**Comment by zx9r** [comment]
Done here: https://github.com/spesmilo/electrum/issues/8892
