### ISSUE TITLE
Unable to connect to the block chain

### ISSUE THREAD

**Issue by alecthenice** [spesmilo/electrum#873]
It seems as if in the mac version of 1.9.8 I am unable to connect via auto connect. This is not typical per the install videos I have seen. I am new to btc use and I am not ruling out user error. Any feedback will be greatly appreciated.

**Comment by jambolo** [comment]
I also had this problem using 1.9.8 on a Mac Book Pro. After a fresh install, auto-connect would not connect. I switched to manual connect and connected, and now auto-connect works.
