### ISSUE TITLE
key is not certified plus user is currently NOT AUTHENTICATED

### ISSUE THREAD

**Issue by MaxwellDupre** [spesmilo/electrum#8740]
None of the users that have signed electrum are authenticated on WOT on bitcoin:
eg
https://bitcoin-otc.com/viewratingdetail.php?nick=emzy&sign=ANY&type=RECV

**Comment by SomberNight** [comment]
`#bitcoin-otc` is for trading. Also, is it even actively used these days?
Not sure what you expect exactly...

**Comment by ecdsa** [comment]
yeah, that is irrelevant. WOT refers to the PGP web of trust, not to the bitcoin-otc web of trust.
