### ISSUE TITLE
UR qr formats questions

### ISSUE THREAD

**Issue by pony-montana** [spesmilo/electrum#8744]
Hi, BC-UR qr codes (https://github.com/BlockchainCommons/crypto-commons) are today very popular for managing PSBT with argapped signer.
Electrum doesn't implement this standard, but I manage my airgapped qr PSBT transactions using electrum + this simple tool (https://github.com/pythcoiner/SeedQReader) + seedsigner in a unix-like environment.
The flow is really good for an experienced user, a bit complex for a noob. 

My question is: what's your intentions about integrating the UR qr standard in electrum?

I see 3 possible way:

1) Integrate it directly in electrum, as a replacement/alternative of the qr standard used today.

pros: better ux for people using this feature, hopefully easy to port on android qml where this feature is most useful.
cons: a lot of work, risk to add complexity and technical depth for a standard that could be redesigned and reimplemented better in the next future.

2) Integrate it as an electrum module.

pros: still possible to implement a good ux, mitigating the cons of  the option 1).
cons: how could it be ported on android qml, avoiding to create more work to do and more complexity?

3) Don't adopt it in electrum at all.

pros: nothing to do and no technical debth added, power users will combine electrum with other tools if they want to use it with argapped UR qr signs.
cons: the ux on android will sucks, even implementing something like that (https://github.com/pythcoiner/SeedQReader) as a standalone android app, the copy-paste flow will probably be sub-optimal and insecure. In my opinion, this would be unfortunate for a mobile wallet.

Thanks for the patience :)

-------PM

**Comment by SomberNight** [comment]
I'll close this in favour of the other linked issue.
