### ISSUE TITLE
my transaction is not confirming

### ISSUE THREAD

**Issue by Usovsergey** [spesmilo/electrum#8745]
Здравствуйте.

Вчера отправил 2 платежа. Платежи повисли, решил отменить, но ничего не получается. Точнее так понимаю отмена по второму платежу прошла, но средства не возвращаются на кошелек. 

Во первый платеж висит. 

Прошу помощи. 
Номера транзакций: 

№ 1. a139d66ad5f88c6829d2422d53dd68125a085af931811aa722918ff5df9a58e6
№ 2. 773122cc9dd008ae52bbae35557a93001140dc6cf4bf7ad77002b24bbc942d5b

**Comment by Usovsergey** [comment]
Yesterday I made 2 payments and errors occurred on them, I returned one payment for a refund, the operation has not been executed for a long time. An error appears on the second payment. Please help me or redirect my request to Electrum wallet support.
Transactions: 
№ 1. a139d66ad5f88c6829d2422d53dd68125a085af931811aa722918ff5df9a58e6
№ 2. 773122cc9dd008ae52bbae35557a93001140dc6cf4bf7ad77002b24bbc942d5b

**Comment by SomberNight** [comment]
There are a lot of transactions in the bitcoin mempool atm and it looks like you are using low fees.
Try bumping the fee.
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

**Comment by Usovsergey** [comment]
> There are a lot of transactions in the bitcoin mempool atm and it looks like you are using low fees. Try bumping the fee. See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

I have sent two payments, both of which are not being executed.

I am trying to increase the commission on the first payment (a139d66ad5f88c6829d2422d53dd68125a085af931811aa722918ff5df9a58e6) an error appears:
"The server returned an error when sending the transaction. Try connecting to another server or updating Electrum
Insufficient free
your transaction is trying to replace another one in my pool, but does not comply with the rules for this. Try to increase the fee." Electrum has been updated to the latest version.

Canceled the second payment (5728b2dde262b52d47fe4588409a66ca277f23cc20927ff1a2d32a11f8b4725) and increased the commission to the level of 2 blocks, nothing happens.

Please figure it out and help me.
![Ошибка электрум 2](https://github.com/spesmilo/electrum/assets/153731906/5f779feb-8db7-41df-a48c-c751f99f5d5b)
![Ошибка электрум](https://github.com/spesmilo/electrum/assets/153731906/b439dbbc-9844-4259-b815-936c96befcee)

**Comment by Usovsergey** [comment]
Good afternoon.
The second operation was canceled, the funds were returned to the wallet.
The first execution operation, the cost has been raised, has been in the queue for a mespule (0.30 MB) for a long time.
I checked the operation on my field (5df47a882a78e88cb0ca0a40017d65bfb02512c0f2008d807ba08656358222d5) it is not there.
What should I do, what do you recommend to do?
Please help me.
![Ошибка электрум 3](https://github.com/spesmilo/electrum/assets/153731906/21e923ff-a2fc-4c1b-bd46-da0cea425dce)
![Ошибка электрум 4](https://github.com/spesmilo/electrum/assets/153731906/5041fe26-e26d-4e0d-a368-0cbc38775f87)
![Ошибка электрум 5](https://github.com/spesmilo/electrum/assets/153731906/9aa6adb9-bd67-405c-b93a-59c934a61423)

**Comment by Usovsergey** [comment]
Hello.

It came back as it was, the first and second operations were not performed.

**Comment by Usovsergey** [comment]
Please let me know are you working on solving my problem? My application is closed, I'm worried. I need help.

**Comment by Usovsergey** [comment]
I raised the commission to the maximum value to complete the operations, as a result, everything was confirmed. 

Thank you for your help.
