### ISSUE TITLE
my transaction has not been confirmed for a long time, increasing the fee does not help

### ISSUE THREAD

**Issue by Usovsergey** [spesmilo/electrum#8747]
I have sent two payments, both of which are not being executed.

I am trying to increase the commission on the first payment (a139d66ad5f88c6829d2422d53dd68125a085af931811aa722918ff5df9a58e6) an error appears:
"The server returned an error when sending the transaction. Try connecting to another server or updating Electrum
Insufficient free
your transaction is trying to replace another one in my pool, but does not comply with the rules for this. Try to increase the fee." Electrum has been updated to the latest version.

Canceled the second payment (5728b2dde262b52d47fe4588409a66ca277f23cc20927ff1a2d32a11f8b4725) and increased the commission to the level of 2 blocks, nothing happens.

Please figure it out and help me.
![Ошибка электрум 2](https://github.com/spesmilo/electrum/assets/153731906/6f78f9f9-4662-4c1a-8f8e-50cd5720cb8f)
![Ошибка электрум](https://github.com/spesmilo/electrum/assets/153731906/6b5b3be8-b44e-4716-9a56-9cb74d033a38)

**Comment by ecdsa** [comment]
please do not reopen a new issue because the previous one has been closed.
you can still write in the closed issue

**Comment by Usovsergey** [comment]
Well Thanks, one payment was completed, I'm waiting for the second one to be completed.
