### ISSUE TITLE
my transaction is not confirming

### ISSUE THREAD

**Issue by Yarkndr** [spesmilo/electrum#8749]
Добрый день. Выполнял транзакцию BTC с Electrum 4.2.2. Так как есть RBF, то выбрал сеть static и установил среднюю комиссию этой сети 4 доллара на тот момент. 
Уже прошло ровно 24 часа, транзакция становится еще дальше в очереди, подтверждений нет. 
Подскажите почему майнеры полностью игнорируют транзакцию ? Так как ранее 4 доллара комиссии было вполне достаточно.
Связано ли это со static  и возможно ли повлиять (ускорить процесс)?

**Comment by SomberNight** [comment]
There are a lot of transactions in the bitcoin mempool atm and it sounds like you might be using low fees.
Try bumping the fee.
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

The absolute value of the fee, especially in fiat terms, (e.g. "4 USD" is irrelevant to the system). Only fee/byte (sat/vbyte) matters.

**Comment by gector77** [comment]
У меня такая же проблема, только оттягивается операция, хотя комиссия 10% от суммы
