### ISSUE TITLE
my transaction is not confirming

### ISSUE THREAD

**Issue by gector77** [spesmilo/electrum#8750]
Более двух суток пытаюсь разными транзакциями вывести деньги.
По крайней транзакции оплатил комиссию в 10$ (до 20 блоков) по итогу после 17 блоков статус поменялся на 144 блока. 
c9568d1b9c08f9103c63df59aae0f94f0aa5173b448f2dae927a92612cb1956f
Разберитесь, пожалуйста. Вижу что у людей такие же проблемы

**Comment by SomberNight** [comment]
There are a lot of transactions in the bitcoin mempool atm and it sounds like you might be using low fees (compared to what others are willing to pay).
Try bumping the fee.
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do
