### ISSUE TITLE
Cannot import a Bitcoin Core private key into an Electrum wallet that supports Lightning

### ISSUE THREAD

**Issue by Geremia** [spesmilo/electrum#8751]
I can't import a Bitcoin Core private key into an Electrum wallet that supports Lightning.

Running `importprivkey` in the Electrum console, I get:
>Error: This type of wallet cannot import private keys. Try to create a new wallet with that key.

When I create a new Electrum wallet with the private keys, Lightning disabled for that wallet.

I'm using Lightning 4.4.6 on Linux.

**Comment by SomberNight** [comment]
Lightning is unrelated. Deterministic wallets are not allowed to import keys. You need to create an "imported wallet", or sweep the coins.

**Comment by Geremia** [comment]
@SomberNight Whether a wallet is deterministic or not would seem unrelated to Lightning. Why can't non-HD wallets use Lightning in Electrum?

**Comment by Geremia** [comment]
@SomberNight I found the answer:

🎩-tip [nc50lc on BitcoinTalk][1]:

>Electrum's lightning wallet requires a master private key where the private keys to be used in your lightning transactions' HTLC (*Hashed Timelock Contract*).
>
>It can't rely on imported keys since it'll eventually run out of available unused keys after few transactions and reusing those isn't an option because it's unsafe to reuse used keys in old HTLC.


  [1]: https://bitcointalk.org/index.php?topic=5478171.msg63355373#msg63355373
