### ISSUE TITLE
mempool min fee not met

### ISSUE THREAD

**Issue by Arsenjuuf** [spesmilo/electrum#8752]
Здравствуйте. хочу отправить транзакцию вот что выходит
Сервер вернул ошибку при отправке транзакции.
Попробуйте подключиться к другому серверу или обновить Electrum.
mempool min fee not met
Your transaction is paying a fee that is so low that the bitcoin node cannot fit it into its mempool. The mempool is already full of hundreds of megabytes of transactions that all pay higher fees. Try to increase the fee.

**Comment by SomberNight** [comment]
>  mempool min fee not met
> Your transaction is paying a fee that is so low that the bitcoin node cannot fit it into its mempool. The mempool is already full of hundreds of megabytes of transactions that all pay higher fees. Try to increase the fee.

What is it about the error message that is not clear?
