### ISSUE TITLE
У меня такая же проблема, только оттягивается операция, хотя комиссия 10% от суммы

### ISSUE THREAD

**Issue by Yarkndr** [spesmilo/electrum#8755]
У меня такая же проблема, только оттягивается операция, хотя комиссия 10% от суммы

_Originally posted by @gector77 in https://github.com/spesmilo/electrum/issues/8749#issuecomment-1858855288_
            

Так же хочу найти решение этого вопроса. Потому что удалось повысить комиссию и все равно без изменений.

**Comment by accumulator** [comment]
duplicate of https://github.com/spesmilo/electrum/issues/8754
