### ISSUE TITLE
Electrum Mobile Wallet - Lightning bug _"Can send" stuck to 0

### ISSUE THREAD

**Issue by Skyman21m** [spesmilo/electrum#8763]
Hey everyone,

I've been trying your mobile LN wallet for few months now and it works really decently congrats, with the LSP features.

I'm having an issue right now. I can't send any LN payment even if I still have enough sats on my side. The "can send" balance stays stuck at 0 and even if I try receiving more sats it stays to 0. THe channel I have is with ACINQ node FYI.

Have you an idea of what it could be ?

Thanks very much !
![2b2fc706c8b8c10f33b429972ae251ba95b5f0485a694d4918cdf9ea145094b3](https://github.com/spesmilo/electrum/assets/116360712/e3b1b687-1ab7-401d-b366-44d35a8fd3f1)

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/8419#issuecomment-1544254370

**Comment by Skyman21m** [comment]
Thank you very much, that's what I thought but the fees seemed too high. Thanks for the detailed explanation.
