### ISSUE TITLE
my transaction is not confirming

### ISSUE THREAD

**Issue by sdaryp1** [spesmilo/electrum#8766]
Транзакции висят уже более трёх дней, комиссию ставил высокую  уже повышел, но транзакции не проходят !

**Comment by sdaryp1** [comment]
<img width="415" alt="Screenshot_1" src="https://github.com/spesmilo/electrum/assets/154506636/9308f313-dbe5-4ab5-b418-94fb131f3e3e">

**Comment by SomberNight** [comment]
There are a lot of transactions in the bitcoin mempool atm and it sounds like you might be using low fees (compared to what others are willing to pay).
Try bumping the fee. Or if it is not urgent, you can just wait.
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

**Comment by sdaryp1** [comment]
Увеличить комиссию не получается !!! 
<img width="250" alt="Screenshot_1" src="https://github.com/spesmilo/electrum/assets/154506636/9b4f4d93-5e8b-4565-b0f4-a44378a2e96f">

**Comment by SomberNight** [comment]
"mempool min fee not met" means that you did not try to increase the fee by a large enough amount.

**Comment by AlexSel1** [comment]
Завис вывод, уже 65 часов весит
