### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BrendaFidder** [spesmilo/electrum#8773]
I use Electrum 4.3.1 and that version always worked well. But now, when I want to send money to a bitcoinadress it says that it can't find the server. I tried to update my version, but that's not possible. I get an error message and the installation process is aborted.
Then I installed the newest version on another computer. When I enter my seed to restore my wallet it's not possible to click on the button 'next', so that doesn't work either. 
I'm hitting one bug after another and it's making me despondent. Can you help me?

Kind regards,
Brenda Fidder

**Comment by SomberNight** [comment]
What OS are you using, where do you download Electrum from, which binary are you using, etc?
What version of Electrum are you testing with now?

> when I want to send money to a bitcoinadress it says that it can't find the server.

Please quote exact error message and show screenshot.

> I get an error message and the installation process is aborted.

Please quote exact error message and show screenshot. 

> When I enter my seed to restore my wallet it's not possible to click on the button 'next', so that doesn't work either.

What kind of seed do you have? Did you use Electrum to generate it originally? Make sure there are no typos when you enter it. How many words are there in the seed? Are they English words?

**Comment by BrendaFidder** [comment]
My OS is windows 10. I think I downloaded Electrum from https://electrum.org. 

I work with Electrum 4.3.1 and had no problems with this version earlier. 

 

See screenshot below for what’s going wrong when I want to pay. 

 



 

 

When I push the HELP-button in 4.3.1 I can check on updates. Then this gives also a failure. See screenshot below. 

 



 

 

Then I tried to download the latest version of Electrum (4.4.6) for windows at electrum.org. This also gives a failure. See screenshot below.

 

 



 

 

The next thing I tried is to install the latest version of Electrum on another computer, on my laptop.

The install wizzard asks fort he seed. I’ve got a seed of 12 English words created by Electrum. But when I write those words I can’t push the button NEXT. 

 

I hope you can help me.

 

Kind regards,

Brenda Fidder 

 

 

Van: ghost43 ***@***.***> 
Verzonden: zaterdag 23 december 2023 01:13
Aan: spesmilo/electrum ***@***.***>
CC: BrendaFidder ***@***.***>; Author ***@***.***>
Onderwerp: Re: [spesmilo/electrum] Bug (Issue #8773)

 

What OS are you using, where do you download Electrum from, which binary are you using, etc?
What version of Electrum are you testing with now?

when I want to send money to a bitcoinadress it says that it can't find the server.

Please quote exact error message and show screenshot.

I get an error message and the installation process is aborted.

Please quote exact error message and show screenshot.

When I enter my seed to restore my wallet it's not possible to click on the button 'next', so that doesn't work either.

What kind of seed do you have? Did you use Electrum to generate it originally? Make sure there are no typos when you enter it. How many words are there in the seed? Are they English words?

**Comment by SomberNight** [comment]
The screenshots are not visible, probably because you tried to attach them to the reply-email. That does not work -- you have to log in to github to attach them, or you need to upload them somewhere and link them.

**Comment by BrendaFidder** [comment]
My OS is windows 10. I think I downloaded Electrum from https://electrum.org/. 
I work with Electrum 4.3.1 and had no problems with this version earlier. 

See screenshot below for what’s going wrong when I want to pay. 

 
![image](https://github.com/spesmilo/electrum/assets/154621818/ae34ec3b-65
![electrum1](https://github.com/spesmilo/electrum/assets/154621818/c0e469f1-ec2d-4897-a511-ae76be801041)
![electrum2](https://github.com/spesmilo/electrum/assets/154621818/11c3ac67-b1e5-4157-a0d9-d1a64756e0b2)
![electrum3](https://github.com/spesmilo/electrum/assets/154621818/f410d621-a386-4534-8823-c7da7ff8a8a3)
a6-4246-baf3-266aa568d63c)



When I push the HELP-button in 4.3.1 I can check on updates. Then this gives also a failure. See screenshot below. 

 


Then I tried to download the latest version of Electrum (4.4.6) for windows at electrum.org. This also gives a failure. See screenshot below.


 


The next thing I tried is to install the latest version of Electrum on another computer, on my laptop.
The install wizzard asks fort he seed. I’ve got a seed of 12 English words created by Electrum. But when I write those words I can’t push the button NEXT. 

I hope you can help me.

Kind regards,
Brenda Fidder

**Comment by SomberNight** [comment]
> See screenshot below for what’s going wrong (1) when I want to pay.
> 
> <details>
>  <summary>pic1</summary>
> 
> ![electrum1](https://github.com/spesmilo/electrum/assets/154621818/c0e469f1-ec2d-4897-a511-ae76be801041)
> </details>

Looks potentially interesting. Please enable [debug logging](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) and upload logs here.

> When I push the HELP-button in 4.3.1 I can check on updates. Then this gives also a failure. See screenshot below.
> <details>
>  <summary>pic2</summary>
> 
> ![electrum2](https://github.com/spesmilo/electrum/assets/154621818/11c3ac67-b1e5-4157-a0d9-d1a64756e0b2)
> </details>

Looks potentially interesting. Please enable [debug logging](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging) and upload logs here.

> Then I tried to download the latest version of Electrum (4.4.6) for windows at electrum.org. This also gives a failure. See screenshot below.
> <details>
>  <summary>pic3</summary>
> 
> ![electrum3](https://github.com/spesmilo/electrum/assets/154621818/f410d621-a386-4534-8823-c7da7ff8a8a3)
a6-4246-baf3-266aa568d63c)
> </details>

Electrum is probably already running in the background. That's why the file is being used. You need to close the program before running the installer.

> The next thing I tried is to install the latest version of Electrum on another computer, on my laptop.
> The install wizzard asks fort he seed. I’ve got a seed of 12 English words created by Electrum. But when I write those words I can’t push the button NEXT.

Make sure there are no typos when you type the seed.
(note: based on pic1, it looks like you have a 2fa wallet. make sure you select that type (2fa) when trying to restore from seed in the wizard)
