### ISSUE TITLE
my transaction is not confirming

### ISSUE THREAD

**Issue by AlexSel1** [spesmilo/electrum#8779]
![photo_2023-12-24_10-47-36](https://github.com/spesmilo/electrum/assets/154611396/f5a654c1-196a-4205-9656-0628dc46ba41)

4 дня весит вывод средств , Комиссию не могу увеличить, потому что вывожу все средства.
![photo_2023-12-24_10-47-36](https://github.com/spesmilo/electrum/assets/154611396/f5a654c1-196a-4205-9656-0628dc46ba41)
 когда будет возврат средств? Прошло больше 72 часов

**Comment by SomberNight** [comment]
There are a lot of transactions in the bitcoin mempool atm and it looks like you are using low fees (compared to what others are willing to pay).
Try bumping the fee. Or if it is not urgent, you can just wait.
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

Note that it is possible to increase the fee even if you are emptying the wallet (sending all).

**Comment by AlexSel1** [comment]
Еще раз повторяю!!!! комиссию не могу увеличить так как все средства вывожу! Как сделать отмену?

**Comment by AlexSel1** [comment]
У вас всегда один и тот же ответ?

**Comment by AlexSel1** [comment]
верните деньги !

**Comment by AlexSel1** [comment]
![Uploading photo_2023-12-24_14-51-51.jpg…]()

**Comment by AlexSel1** [comment]
![photo_2023-12-24_14-51-51](https://github.com/spesmilo/electrum/assets/154611396/2189ad32-8328-46ae-a9ff-d931f17fdbf8)

**Comment by AlexSel1** [comment]
Не работайте с Electrum. Они воры и обманьшики!

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/8774#issuecomment-1870054419
