### ISSUE TITLE
Wallet file corruption detected

### ISSUE THREAD

**Issue by payambaba1360** [spesmilo/electrum#8780]
i backup my wallet and chenge my pc but when open wallet and load wallet after load i see this message 

> Wallet file corruption detected. Please restore your wallet from seed, and compare the addresses in both files

and  i press ok 
i send bug yesterday but dont solve my problem 
i try to send my coin to another wallet address but i see this message 

> The server returned an error when broadcasting the transaction.
> Consider trying to connect to a different server, or updating Electrum.
> 
> Script failed an OP_EQUALVERIFY operation

i chenge server but dont solve this error 
i use  Electrum 4.4.6 version
please help me

**Comment by cylyl** [comment]
When a Bitcoin nodes receives transaction B, it runs a script using output A and Input B (input B is put on the top of the stack, and output A on the bottom). It seems that you are thinking that the script gets run on Input B and Output B, but this would clearly fail when running OP_EQUALVERIFY.

https://bitcoin.stackexchange.com/questions/8812/how-op-equalverify-works-in-a-standard-transaction

**Comment by SomberNight** [comment]
> i backup my wallet and chenge my pc but when open wallet and load wallet after load i see this message
Wallet file corruption detected.

When did you first see this message? Was the file not corrupted on the first PC, and immediately corrupted when opened on the second PC?

>  i try to send my coin to another wallet address but i see this message
>> The server returned an error when broadcasting the transaction.
>> Consider trying to connect to a different server, or updating Electrum.
>> 
>> Script failed an OP_EQUALVERIFY operation

Well, yes, the wallet file is corrupted... It does not have the correct private keys.

>  Wallet file corruption detected. Please restore your wallet from seed, and compare the addresses in both files

^ Like the error message says, you should restore from seed words.

**Comment by payambaba1360** [comment]
i restore my wallet but  when  i open it after restore  my i lose my
address and my btc
please help me

**Comment by SomberNight** [comment]
More details and context would be needed, like I asked for in my previous message.
