### ISSUE TITLE
Cannot build .exe

### ISSUE THREAD

**Issue by AlienGit** [spesmilo/electrum#879]
In Ubuntu,

wine: cannot find 'c:/python26\Scripts\easy_install.exe'

when running, 

./prepare-wine.sh

**Comment by wozz** [comment]
Please see this other repository to build for windows: https://github.com/maran/electrum-winbuild

**Comment by EagleTM** [comment]
I've seen some recent pull requests merged with regards to building in wine. I think we might close here. If it's still an issue, please reopen or open a new one
