### ISSUE TITLE
[ Feature Request ] Implement coinjoin support for desktop/mobile Apps

### ISSUE THREAD

**Issue by jayb-g** [spesmilo/electrum#8802]
Currently there are a handful of desktop wallets that have in-built support for coinjoin and no mobile wallets. Are there any plans or possibility in future for electrum to support coin-join in Desktop/Mobile Apps? It would be amazing to have that especially in mobile apps.

**Comment by jayb-g** [comment]
I have no idea how coinjoin works but it seems to be important for crypto wallet users. Well, no dev seems to be interested in the feature so take it as a no?

**Comment by ecdsa** [comment]
We have no plans to implement coinjoin in Electrum.
Some third party coinjoin plugins for Electrum are under development, you might try those.
