### ISSUE TITLE
bech32_decode: use find instead of rfind

### ISSUE THREAD

**Issue by floyddeadshot** [spesmilo/electrum#8812]
Probably a misunderstanding on my end, but shouldn't the below line be

`pos = bech.find('1')` instead of rfind?

https://github.com/spesmilo/electrum/blame/d660c57808d415334fcdeebcfe3df37e4e29678c/electrum/segwit_addr.py#L93C26-L93C26

**Comment by SomberNight** [comment]
That comes from the reference code.
https://github.com/sipa/bech32/blob/7a7d7ab158db7078a333384e0e918c90dbc42917/ref/python/segwit_addr.py#L79

https://github.com/bitcoin/bips/blob/deae64bfd31f6938253c05392aa355bf6d7e7605/bip-0173.mediawiki#bech32
> The separator, which is always "1". In case "1" is allowed inside the human-readable part, the last one in the string is the separator[[3](https://github.com/bitcoin/bips/blob/deae64bfd31f6938253c05392aa355bf6d7e7605/bip-0173.mediawiki#cite_note-3)].
