### ISSUE TITLE
Installing ZBar QR code reader on Windows

### ISSUE THREAD

**Issue by stefaang** [spesmilo/electrum#882]
It is not easy to get ZBar and the python bindings installed on Windows, as easy_install and pip are failing. I finally got around with these instructions: https://code.google.com/p/qrdecoder/wiki/zbarInstallation

**Comment by ecdsa** [comment]
can this be closed, since the commit was merged?

**Comment by Tafelpoot** [comment]
Sure.
I saw that pyinstaller is able to include zbar in the windows executables, which is also nice.

**Comment by cdokolas** [comment]
There is still no release that includes the fix. What's up?

**Comment by ecdsa** [comment]
reopening as a reminder

**Comment by dermoth** [comment]
Hi,

The wiki path in OP is no longer accessible and not archived in the wayback machine (NB: it's been archived; I checked the link before redirect too).

Anyone happens to recall the procedure?

**Comment by Tafelpoot** [comment]
install zbar for windows with **development headers enabled**
http://sourceforge.net/projects/zbar/files/zbar/0.10/zbar-0.10-setup.exe/download

download the python package source (tar or zip)
https://pypi.python.org/pypi/zbar

edit setup.py as follows

put this on line 3
`from distutils.sysconfig import get_config_vars`

add this to the extension call -- with the correct path to the lib / include folder ofcourse.
````
         library_dirs=["""d:\zbar\lib"""],
         include_dirs=[get_config_vars('INCLUDEDIR'),
                              get_config_vars('INCLUDEPY'),
                             """d:\zbar\include"""]
```

now install zbar by running these commands
`python setup.py build -c=mingw32`
`python setup.py install`

thanks for the steps: https://sourceforge.net/p/zbar/discussion/664596/thread/e732b1d8/

**Comment by BillBridge** [comment]
@Tafelpoot : Hi, you did mention that PyInstaller is supporting zbar. Unfortunately I can't find this info on the PyInstaller website. Can you refer me to that article or if possible could you post an example on what to add to a .spec file?

**Comment by ecdsa** [comment]
note: the pyinstaller3 branch of this repo has zbar
