### ISSUE TITLE
[Testnet] Lightning Channel creation fails ("new channel" button greyed-out)

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#8826]
* OS: Windows 11 AMD64
* Version: 4.5.0 (standalone windows binary)
* Testnet Balance: 0.0709104 tBTC
* Confirmations: 6+
* Server: testnet.hsmiths.com

I'm following the procedure outlined in [issue #148][1], and I can't click the "New Channel" button in the Lightning tab because it is greyed out.  Are Electrum's Testnet Lightning Channels offline this week?

[1]: https://github.com/spesmilo/electrum-docs/issues/148

**Comment by SomberNight** [comment]
What does it say in menubar>Wallet>Information, for Lightning?

**Comment by brianddk** [comment]
> What does it say in menubar>Wallet>Information, for Lightning?

Thank you.  Lighting was not enabled.  I can never remember where that button is, thank you for reminding me.

Sorry for the spam.

**Comment by brianddk** [comment]
Went into `menubar>Wallet>Information` and enabled Lightning

For `Lightning:` it reports `Enabled, non-recoverable channels` with a crossed out cloud icon.

Node-id: `025e66e613a0f771312e2bbdfc9a45c95a57cf0f73126b1bbd274887a0b9739fb3`

Perhaps it's syncing LN routes now.  IIRC that took a minute or two on the original release.

**Comment by SomberNight** [comment]
>> What does it say in menubar>Wallet>Information, for Lightning?
>
> Thank you. Lighting was not enabled. I can never remember where that button is, thank you for reminding me.

Note that Lightning is enabled by default if you create a new wallet file using a segwit electrum seed.
But yes, otherwise it's off by default. And it can only be enabled for standard deterministic wallets with p2wpkh script.
