### ISSUE TITLE
Add a requirements.txt file.

### ISSUE THREAD

**Issue by skorokithakis** [spesmilo/electrum#883]
Please add a requirements.txt file with the necessary packages and versions so installation from source can fetch these easily.

**Comment by ecdsa** [comment]
was the problem with `slowaes` ?

**Comment by ecdsa** [comment]
I guess you had the problem described in issue #956 
it is fixed by running pip with the --pre flag, and the README was updated.
please reopen this issue if the problem persists.

**Comment by skorokithakis** [comment]
I think slowaes was one of the problems. I will reopen if I run into it again, thanks.
