### ISSUE TITLE
При переводе BTC,  пишет что недостаточно средств, хотя деньги имеются. 

### ISSUE THREAD

**Issue by DimDim2021** [spesmilo/electrum#8832]
При переводе денег, пишет, что не достаточно средств, комиссию ставил от маленькой, до самой большой. Електрум обновлен до версии 4.5.0. Что делать? Удалял и устанавливал кошелек по ceed фразе.

**Comment by SomberNight** [comment]
Not enough details. At the very least, to start,
- say how much you are trying to pay, and what is the balance of the wallet
- is it a lightning payment?

**Comment by ecdsa** [comment]
closing, inactive
