### ISSUE TITLE
Didn't receive btc after send to CORRECT WALLET ADDRESS

### ISSUE THREAD

**Issue by Aebeeh** [spesmilo/electrum#8836]
Hello hello. Kindly treat this mail as urgent.
I sent bsv from your wallet to my btc address I still haven't received it yet and it's been more than 30minutes.!
What's going on?
I need it sorted out ASAP thanks
Reach out to my email for any details you need.

**Comment by SomberNight** [comment]
> I sent bsv 

Altcoins are not supported. You must have used some other software.

**Comment by Aebeeh** [comment]
I used electrum bro.

**Comment by Aebeeh** [comment]
What do I do now?

**Comment by LorenzoAncora** [comment]
@Aebeeh Electrum handles the cryptocurrency _Bitcoin_ (**BTC**).
The cryptocurrency _Bitcoin Satoshi Vision_ (**BSV**) is managed via [ElectrumSV](https://electrumsv.io/).
In this case you should ask for support in their [official repository](https://github.com/electrumsv/electrumsv).
