### ISSUE TITLE
RuntimeError('DataError: bytes overflow')  <electrum multisig error message

### ISSUE THREAD

**Issue by italianbtc1** [spesmilo/electrum#8841]
Hi,

Not sure why this issue. Trying to send a transaction from my multi sig set up using trezor and ledger.

The transaction is 822 bytes so there should be no problem. Using latest version on all things.

Could someone help me out?

**Comment by italianbtc1** [comment]
also, the trezor is showing the fee as the amount I'm trying to send. Superweird.

**Comment by italianbtc1** [comment]
I was forced to use version 4.4.6 and an old wallet file to be able to send a transaction. There seems to be some sort of bug on the new electrum version. 

Is anyone aware?

**Comment by SomberNight** [comment]
Please don't open duplicate issues. We can reopen the existing one.
