### ISSUE TITLE
PSBT join/combine operations fail recognize identical outputs

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#8869]
When doing a join/combine operation on multiple unsigned PSBTs that all send to the same output the expected behavior would be for those identical outputs to only be included as one output in the final psbt.  But the join/combine operation produces three outputs instead.

## Creation

1. Intialize the Trezor-T hardware wallet as instructed in `mk-psbt.sh` (attached)
2. Create three `testnet` wallet files using Trezor one for P2PKH, P2SH-Segwit, P2WPKH.
3. Load each wallet file ~ 1M sat each
4. Use `payto` to make three PSBTs each with one input and the same output (see `mk-psbt.sh`)
5. Open the P2WPKH wallet file in the Desktop GUI ensuring good connectivity to Trezor
6. From the GUI load the unsigned `segwit.psbt` file created earlier
7. Use the combine operation to join/combine inputs and outputs from the other two PSBTs
8. Notice that you have three inputs in three outputs, the outputs are redundant

## Environment

* OS: Windows 10 22H2 / WSL2 Ubuntu 22.04.2 Jammy
* Electrum: Standalone v4.5.2 / Source v4.5.2
* Hardware: Trezor-T firmware v2.6.4
* Related issues: https://github.com/spesmilo/electrum/issues/8868
* Attachment: [psbt-error.tar.gz](https://github.com/spesmilo/electrum/files/14160039/psbt-error.tar.gz)

**Comment by SomberNight** [comment]
Have you seen `config.WALLET_MERGE_DUPLICATE_OUTPUTS`?
see https://github.com/spesmilo/electrum/pull/8474

![Screenshot from 2024-02-05 06-42-36](https://github.com/spesmilo/electrum/assets/29142493/e6b67f0d-7afb-4024-b699-e05d04a6eb9e)

**Comment by brianddk** [comment]
That control didn't show up on PSBTs output from `payto` calls, but I can try through the GUI with that checkbox enabled, and will report back

**Comment by SomberNight** [comment]
You can do `$ electrum setconfig wallet_merge_duplicate_outputs true` from the CLI or similar via RPC.
I am pretty sure that should solve this.
