### ISSUE TITLE
pycharm: ModuleNotFoundError: No module named 'logging.handlers'; 'logging' is not a package

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8882]
It is difficult to run the tests with pycharm (IntelliJ-based IDE).
Our logging module `electrum/logging.py` collides in name with the standard library `logging` module. And by default pycharm does a lot of trickery and guessing when setting `$PWD`, `$PYTHONPATH` (and relatedly `sys.path`) when running tests. 

If one opens the project in pycharm, with default settings, and uses hotkeys or click the "run test" icon to run one of the unit tests, it will error out:
```
Error
Traceback (most recent call last):
  File "...\Python310\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: electrum
Traceback (most recent call last):
  File "...\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "...\electrum\electrum\__init__.py", line 19, in <module>
    from .util import format_satoshis
  File "...\electrum\electrum\util.py", line 24, in <module>
    import concurrent.futures
  File "...\Python310\lib\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "...\Python310\lib\concurrent\futures\_base.py", line 7, in <module>
    import logging
  File "...\electrum\electrum\logging.py", line 6, in <module>
    import logging.handlers
ModuleNotFoundError: No module named 'logging.handlers'; 'logging' is not a package
```

This is because pycharm sets `$PWD` to the inner `electrum` directory and puts that into `$PYTHONPATH`, and so the import system gets confused on `import logging`.

One can do a lot of fighting with the settings in pycharm and make the tests run. It is not trivial and every potential contributor needs to do it, and then do it again if they reinstall their system. Instead, it would be nice to either change our code to prevent this problem from arising, or to maybe commit some pycharm-specific settings into the repo which are then picked up automatically (e.g. into the `.idea` folder).

-----

Workarounds/solutions:

1. Interestingly, if you run a test from a test module that relative imports `electrum`, that prevents the problem. For some reason, this makes pycharm set `$PWD` one directory higher, to the project dir.
Unfortunately, doing a relative import in `tests/__init__.py` is apparently not sufficient, it would have to be done in every test module...
```diff
diff --git a/electrum/tests/test_bolt11.py b/electrum/tests/test_bolt11.py
index 433af331c6..9d279124e8 100644
--- a/electrum/tests/test_bolt11.py
+++ b/electrum/tests/test_bolt11.py
@@ -4,7 +4,7 @@ from binascii import unhexlify, hexlify
 import pprint
 import unittest
 
-from electrum.lnaddr import shorten_amount, unshorten_amount, LnAddr, lnencode, lndecode, u5_to_bitarray, bitarray_to_u5
+from ..lnaddr import shorten_amount, unshorten_amount, LnAddr, lnencode, lndecode, u5_to_bitarray, bitarray_to_u5
 from electrum.segwit_addr import bech32_encode, bech32_decode
 from electrum import segwit_addr
 from electrum.lnutil import UnknownEvenFeatureBits, derive_payment_secret_from_payment_preimage, LnFeatures, IncompatibleLightningFeatures
```

2. We could hack our logging module to remove itself from `sys.path`. The hack would have to go directly into `logging.py`, not e.g. into `electrum/__init__.py` (which would be more generic, to cover all other potential collisions).

```diff
diff --git a/electrum/logging.py b/electrum/logging.py
index f0c137ba33..949e086130 100644
--- a/electrum/logging.py
+++ b/electrum/logging.py
@@ -2,6 +2,10 @@
 # Distributed under the MIT software license, see the accompanying
 # file LICENCE or http://www.opensource.org/licenses/mit-license.php
 
+import os, sys
+if os.path.dirname(__file__) in sys.path:
+    sys.path.remove(os.path.dirname(__file__))
+
 import logging
 import logging.handlers
 import datetime
```

3. AFAICT we could move `$PROJECT_ROOT/electrum/tests` to `$PROJECT_ROOT/tests`, and that would fix the issue.
Looking at a few other python projects, that seems to be the convention (or the usual practice) anyway.

-----

So, I think we should just do (3).

**Comment by accumulator** [comment]
(3) in #8897
