### ISSUE TITLE
Lost Bitcoin from coldcard!!! 

### ISSUE THREAD

**Issue by murtaxataha** [spesmilo/electrum#8885]
I sent bitcoin from my ledger to my new cold card connected to electrum. I don't understand what happened but I received the bitcoin and then instantly they were sent to some other address. How is this even possible if I am using the cold card?? Wouldn't I have to sign the transaction on the device before it is sent out.

This was like 800 dollars worth of BTC!!!

**Comment by accumulator** [comment]
Sounds like https://www.youtube.com/watch?v=oj_W3xOlt6U

**Comment by SomberNight** [comment]
How is this related to Electrum? The coldcard manages your private keys, and the threat model explicitly includes the wallet software on the connected host PC to be malicious.
