### ISSUE TITLE
Cannot verify seed phrase

### ISSUE THREAD

**Issue by nbvich** [spesmilo/electrum#8893]
I have had an electrum wallet for over a year, and I can login using 2fa. However, I want to verify my seed phrase. When I click on seed through the menu, I cannot see it. 
![seed](https://github.com/spesmilo/electrum/assets/74522251/02c3a812-0308-4da9-98bb-1ebef0298092)

How can I see my seed phrase for my electrum wallet?

**Comment by accumulator** [comment]
You can't. Storing the seed for a 2FA wallet would defeat its purpose, as this allows you to circumvent the 2FA process, because the seed is enough to sign transactions without the co-signing server.

**Comment by nbvich** [comment]
Ok, I think I understand that purpose then. How could I verify I wrote down the correct seed phrase though?

**Comment by SomberNight** [comment]
You dry-run the actual disaster recovery: create a new wallet file, choosing to restore from seed.

Create a new wallet file, choose `Wallet with two-factor authentication`>`I already have a seed`, then choose to "keep" 2fa enabled, and go through all the steps. Then compare the addresses of the freshly created wallet file with the existing one (menubar>`View`>`Addresses`). If it all checks out, you might want to delete the newer wallet file, just to keep things simple.

**Comment by nbvich** [comment]
@SomberNight Worked like a charm. I appreciate it.
