### ISSUE TITLE
Trezor One cannot sign tx that has external pre-signed inputs

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8910]
Consider two standard (singlesig) wallets trying to do a coinjoin.
If the last signer is a Trezor One, it raises `RuntimeError('ProcessError: Unverifiable external input.')`.

Example steps for manual coinjoin:
1. wallet1 creates unsigned tx1, paying itself (e.g. 1 input, 2 outputs)
2. in wallet1, go to tx Preview. Share>"Include SLIP-19 ownership proofs"
    - this step is optional, might be needed depending on the requirements of wallet2 (namely if it is a Trezor)
3. in wallet1, tx dialog, Share>"Copy to clipboard"
    - let's call the exported tx "psbt1"
4. wallet2 creates unsigned tx2, paying itself (e.g. 1 input, 2 outputs)
5. in wallet2, go to tx Preview. Combine>"Join inputs/outputs", paste psbt1.
    - now the tx preview dialog shows a new tx, "tx3", which has 2 inputs and 4 outputs
6. in wallet2 still, tx dialog, now you can click "Sign"
    - the inputs of tx3 that are owned by wallet2 will be signed now
7. in wallet2 still, tx dialog, click Share>"Copy to clipboard"
    - let's call the exported tx "psbt2"
8. in wallet1, menubar>Tools>"Load transaction">"From text". paste psbt2.
9. in wallet1, tx dialog, now you can click "Sign"
    - the inputs of tx3 that are owned by wallet1 will be signed now
10. tx3 is now fully signed and you can broadcast it

-----

- If wallet1 uses a Trezor One (fw 1.12.1), e.g. with p2wpkh scripts, it will raise on step 9: `RuntimeError('ProcessError: Unverifiable external input.')`.
    - wallet2 could be a software wallet with p2wpkh scripts, or a Trezor T, does not matter
- If wallet1 uses a Trezor T, and wallet2 uses a Trezor One, no errors
- If wallet1 uses a Trezor Safe 3, and wallet2 uses a Trezor T, no errors
- If wallet1 uses a Trezor T, and wallet2 uses a  Trezor Safe 3, no errors

-----

It looks like the Trezor One is refusing to sign a tx with external pre-signed inputs. The other trezor models work however.
@matejcik any idea?

-----

originally reported at https://github.com/spesmilo/electrum/pull/8871#issuecomment-1959662113 by @hynek-jina
related https://github.com/spesmilo/electrum/issues/8324

**Comment by matejcik** [comment]
Trezor One has limited support for EXTERNAL features. Only ownership proofs are accepted and only for segwit/taproot inputs. Pre-signed inputs are not supported.

cc also @andrewkozlik

**Comment by hynek-jina** [comment]
Now it works even for `Trezor One`, thank you! 🙏
