### ISSUE TITLE
Electrum Not Showing Bitcoin SV Balance

### ISSUE THREAD

**Issue by GOLDENEAGLE313** [spesmilo/electrum#8914]
Current Behavior

HI, I swapped XRP for Bitcoin SV and sent to this address:
1NdFZTfeHvuX7ibfDDXaiPxYo2x8GVDUBC

The transaction Hash can be found ere.
https://whatsonchain.com/address/1NdFZTfeHvuX7ibfDDXaiPxYo2x8GVDUBC

Expected Behavior

I was hoping to receive my BitcoinSV funds direclty into my wallet because I had sent the funds to the address copied and pasted from the wallet, but when I open my Electrum wallet there are no funds for BSV. I am guessing that this wallet does not support BSV and I should have downloaded and sent to ElectrumSV. How can I recover my funds and send them out to the correct wallet?

**Comment by SomberNight** [comment]
Hi. Altcoins are off-topic. Maybe try downloading that fork of electrum for BSV and restore from the same seed there. Note that any secret (e.g. the seed) that you enter into other software is at an increased risk of compromise. Good luck.
