### ISSUE TITLE
Accidentally lost funds on channel opening: Seeking Assistance

### ISSUE THREAD

**Issue by sanrinconr** [spesmilo/electrum#8915]
First of all, this not is a software issue, is a issue for seek contact info, feel free to close the issue if you consider it.
 
I initiated a channel opening with Electrum Trampoline using LND through the following command:

`lncli openchannel --sat_per_vbyte 16 --private --min_confs=0 03ecef675be448b615e6176424070673ef8284e0fd19d8be062a6cb5b130a0a0d1 1700000 1500000
`

The issue arose with the parameter 1500000, which represents the "push_amt." According to the documentation, this parameter signifies:

> Note that the push-amt is deducted from the specified local-amt, which implies that the local-amt must be greater than the push-amt. Also note that specifying push-amt means you give that amount to the remote node as part of the channel opening.

I see that question https://bitcoin.stackexchange.com/questions/91847/lost-funds-on-my-lightning-node?noredirect=1&lq=1

Soo, in other words, this implies that I unintentionally provided 1500000 bitcoins (sats) to the counterparty without receiving anything in return.

The potential solution involves reaching out to the counterparty. However, I'm unable to locate any contact information for the owner of the Electrum Trampoline. The only information available is the IP address: [195.201.207.61:9740](https://195.201.207.61:9740/).

That is the node: https://1ml.com/node/03ecef675be448b615e6176424070673ef8284e0fd19d8be062a6cb5b130a0a0d1

And that the opening transaction (channel is still open): https://blockchair.com/bitcoin/transaction/d337836cd20babab905fc6a02cede41cbdc3e81cdd4e514b333f0adb574c59cf

Does anyone know contact details for the owner of the Electrum Trampoline? Thanks!

**Comment by ecdsa** [comment]
I am running that node. I can send you the funds back without an invoice if your node supports `keysend`.

However, I would need to see a proof that you actually pushed sats during channel opening. 
Do you know how to display this using Eclair's command line? 
I have been trying to extract that info using `eclair audit` and `eclair channels`, but it does not seem to display that

**Comment by sanrinconr** [comment]
Something that i forget to tell you was the node pubkey :stuck_out_tongue: , is: `024a70d0ba6e589f8fa907c4435b9893947c33534396ba2bd10c7be65e8de0fef4`

**Comment by ecdsa** [comment]
indeed, it is a bit cumbersome, but I could verify the amount.

I was not able to send you back 15mBTC because of the channel reserves. 
(and I cannot rebalance your channel because it is pivate)
So I sent you back 14.5 mBTC using 4 keysend paymrénts (amounts 5, 5, 4 and 0.5)

**Comment by sanrinconr** [comment]
Received! Thank you very much for your help. I am really grateful to you.

Have a good day and again, thank you very much!

Anything I can help with in the future, write to me.

**Comment by cooper-david-a** [comment]
@ecdsa
Hello, I was directed here from this thread on bitcoin talk.  
https://bitcointalk.org/index.php?topic=5463079.new;topicseen#new

My hard drive died and took my electrum wallet with it.  I recovered the wallet via a seed phrase but have an open channel that I can no longer access.  I am pretty sure it was opened with the Electrum Trampoline server back in September.

txid: 5ef933b5f958eda84e3198303b580a63cffeb1260bc3a695e8eb64a5e1da1b39

If you could force close the channel, I would be grateful.  I assume force close is the only way to close it in this situation.  I'll reimburse you for your time and cost.  It was the minimum channel size so I'm not going to starve either way.

I don't know how I'll be able to verify myself, if that is necessary.

**Comment by ecdsa** [comment]
1. restore your wallet from seed
2. open the channels list
3. you should see a line corresponding to the onchain channel backup
4. in the menu, select "request force close"

**Comment by cooper-david-a** [comment]
Thank you for the response.

I recovered my wallet from the seed.  I can see all of my on-chain transactions but not my one channel.

I don't see that line you refer to in step 3.  I think I saw that there was an option at the channel creation to make it a "recoverable channel" or something.  If so, I'm assuming I didn't have it selected.

I think that means my only option is to ask you to close it from your end.

Do you have a policy to close abandoned channels after some period of time?  I could just wait for it to die a natural death.

**Comment by ecdsa** [comment]
The txid you posted has an op_return output. This means it is "recoverable".
Electrum uses this op_return in order to make your channel backup recoverable from seed.
If you restore from seed, you should see your channel in the channels tab.

> I recovered my wallet from the seed. I can see all of my on-chain transactions but not my one channel.

do you see the channel funding transaction? just to make sure this is the right wallet seed.

> I think that means my only option is to ask you to close it from your end.

you would need to provide a proof that you are the channel owner.
for example sign a message with the private key used to fund the channel.

> Do you have a policy to close abandoned channels after some period of time? I could just wait for it to die a natural death.

yes, we force close after 1 year of inactivity

**Comment by cooper-david-a** [comment]
Thanks, that's good to know.  Is there an additional step required to restore the lightning channel?
Yes, I see the funding transaction.

I am running this from an appimage on linux if that matters to you.

<img width="796" height="576" alt="Image" src="https://github.com/user-attachments/assets/f506ccb0-c67b-4d6b-b716-aa785c5f59c1" />

<img width="776" height="436" alt="Image" src="https://github.com/user-attachments/assets/0b6607ef-4ef8-4b86-a200-d17e63626812" />

**Comment by ecdsa** [comment]
This looks like a bug; the channel backup should be visible in the channels tab.
Could you try to restore from seed one more time? I would like to know if the issue is reproducible.

**Comment by cooper-david-a** [comment]
There it is. Funny. Thanks.
It went through a synchronization this time that I don't remember the first time.

[image.png]

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
