### ISSUE TITLE
P2PKH address under "Donate to server"

### ISSUE THREAD

**Issue by paboum** [spesmilo/electrum#8917]
After my two recent issues were resolved nicely by the team I'd like to make a donation. Yet, I've found no relevant information in `README.md` and on electrum.org. Clicking Help -> Donate to server yields a legacy address which I'm reluctant to use for various reasons. It also presets tx description to "donation for bitcoins.sk" which seems really outdated.

**Comment by ecdsa** [comment]
we cannot fix that.
the donation address depends on which server you are connected to, not on the electrum software.

**Comment by paboum** [comment]
Does the team accept donations?
