### ISSUE TITLE
how to build android apk

### ISSUE THREAD

**Issue by ejrhe** [spesmilo/electrum#8918]
dear sir when ever i am trying to build testnet version of electrum apk using ./make_apk.sh it show this error 💬 INFO:  preparing electrum-locale.
pt_BR/electrum.po:416: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 1 fatal error
/home/shri-krishna/electrum/contrib/android /home/shri-krishna/electrum/contrib/android
💬 INFO:  apk building phase starts.
🗯 ERROR: unknown build type

how can i fix it and successfully build my testnet electrum apk for my android device?

**Comment by SomberNight** [comment]
Follow the steps described in [`contrib/android/Readme.md`](https://github.com/spesmilo/electrum/blob/master/contrib/android/Readme.md).
For example, run `$ ./build.sh qml arm64-v8a debug`.

Do not run make_apk.sh directly unless you can read and understand code and don't need help.

-----

To build for testnet, as said already in https://github.com/spesmilo/electrum/issues/5570#issuecomment-1961606303,
you need to uncomment this line:
https://github.com/spesmilo/electrum/blob/85ea2dfc484b7ee2de5863a1ee7a4531215600c1/contrib/android/make_apk.sh#L48

**Comment by SomberNight** [comment]
In what way is `./build.sh qml arm64-v8a debug` not working?

**Comment by ejrhe** [comment]
It is just showing the usage and do nothing after that.
