### ISSUE TITLE
Crashing app when loading old wallet

### ISSUE THREAD

**Issue by ssj4maiko** [spesmilo/electrum#8923]
Version 4.5.3 (Google Play version
Android 13

When I open the app to access my wallets, **just as I open the app and it asks for the password**, and I type the **correct** password _(wrong password just gives me a red alert that it's incorrect)_, I get something like a crash telling me to send a report to github _(I would send it, but the supposed link shown doesn't open anything, and I couldn't find it on github)_.

I was able to press back, returning to the original screen with no wallets loaded, and tried to enter on my newer wallet, I typed the password, and it loaded everything normally.

I went back, and tried to access my original (older) wallet, and it crashed giving me the same screen to report an error, here is a screenshot, since I couldn't copy and paste..

![signal-2024-02-29-141752_002](https://github.com/spesmilo/electrum/assets/1388443/cf71295e-cc46-47b6-9efc-8c69f27689b1)

The only characteristic I can think of is that this is an older wallet, I created it many years ago with another app, and imported it to Electrum, where I was able to learn that it didn't had support for some of the newer technologies, such as the Lightning network (which I enabled via Electrum). So I don't know if it could be related to something similar.

**Comment by accumulator** [comment]
known issue, see #8913
