### ISSUE TITLE
при переводе биткоин с кошелька ELEKTRUM на Биржу ByBiT, перевод завис. как мне вернуть биткоин назад в Электрум ?

### ISSUE THREAD

**Issue by REGARSKI** [spesmilo/electrum#8928]
при переводе биткоин с кошелька Электрум на Биржу ByBiT, перевод завис. как мне вернуть биткоин назад в Электрум ? 
![Без имени](https://github.com/spesmilo/electrum/assets/161912472/7301e448-e1d9-438b-b389-ad05b4b310ab)
![334](https://github.com/spesmilo/electrum/assets/161912472/4050a442-595f-4894-b92a-a489e3f393f6)

**Comment by accumulator** [comment]
https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
