### ISSUE TITLE
Geld bei Bitcoin-Zahlung nicht bei Adresse angekommen!

### ISSUE THREAD

**Issue by georg60** [spesmilo/electrum#8945]
Ich habe eine Zahlung mit Bitcoin über Electrum durchgeführt. Das Geld ist weg aber die Zahlung kam nicht an.

Transaktions ID: ef90606526f8c135db5a722f1f683a57d61f0d8ffbb68f898aa7aac984c1564d

**Comment by SomberNight** [comment]
More context is needed. Did you *send from* your Electrum wallet? (or was expecting to *receive to* your Electrum wallet?)
Who is the other party? (an exchange address, or a merchant, or a friend, etc?)
The mentioned tx is already included in the blockchain, so likely there is some misunderstanding regarding the output (/recipient) addresses.

**Comment by georg60** [comment]
Ich habe von meinem Electrum wallet gesendet. Die andere Partei ist ein Multihoster (Debrid-Link). Es lief ein Countown-Zähler. Die Bezahlung bei meinem wallet war fertig. (Grüner Haken). Bei der Payseite des Mulihosters gab es eine Fehlermeldung. Der Multihoster sagte er habe keine Zahlung erhalten aber auf meinen wallet ist das Geld weg.

**Comment by georg60** [comment]
Ich habe von meinem Electrum wallet gesendet. Die andere Partei ist ein Multihoster (Debrid-Link). Es lief ein Countown-Zähler. Die Bezahlung bei meinem wallet war fertig. (Grüner Haken). Bei der Payseite des Mulihosters gab es eine Fehlermeldung. Der Multihoster sagte er habe keine Zahlung erhalten aber auf meinen wallet ist das Geld weg. 

Am 13-Mar-2024 15:26:26 +0100 schrieb ***@***.***: 

More context is needed. Did you _send from_ your Electrum wallet? (or was expecting to _receive to_ your Electrum wallet?)
Who is the other party? (an exchange address, or a merchant, or a friend, etc?)
The mentioned tx is already included in the blockchain, so likely there is some misunderstanding regarding the output (/recipient) addresses. 

--
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:   

-------------------------------------------------------------------------------------------------
FreeMail powered by mail.de - MEHR SICHERHEIT, SERIOSITÄT UND KOMFORT

**Comment by ecdsa** [comment]
Make sure you sent to the proper address.
Closing this, because Electrum does not seem to be the issue here.
