### ISSUE TITLE
ea0fe5a5bf0c04f9cc955b2966b614f5f378c6f6

### ISSUE THREAD

**Issue by Emadalshamery** [spesmilo/electrum#8949]
bitcoin:bc1qata55ff6h8xnfxy50jzne09any5r2583h6c9cp?message=ea0fe5a5bf0c04f9cc955b2966b614f5f378c6f6&time=1710378335&exp=86400

**Comment by Naung926** [comment]
myanmar wave money account 
09976881298
Htet Myo Khant
![Uploading Screenshot_2024-03-12-15-21-22-017_mm.com.wavemoney.wavepay.jpg…]()
