### ISSUE TITLE
Missing possibility to manually enter fee as described in docs

### ISSUE THREAD

**Issue by Franselbaer** [spesmilo/electrum#8953]
I am testing Electrum and followed the docs under: https://electrum.readthedocs.io/en/latest/faq.html#can-i-do-bulk-payments-with-electrum-batching

In the, obviously older versions in the docs, is a possibility shown to manually override the fee. In current version 4.5.4 this seems to be completely lost or can I activate that somehow?

Best regards

**Comment by ecdsa** [comment]
in the dropdown menu, tick "edit fees manually"
