### ISSUE TITLE
Amount sent is aways 0.BTC when making a transaction [4.5.3]

### ISSUE THREAD

**Issue by anonnfr** [spesmilo/electrum#8955]
I was going to make a transaction, but the amount sent is wrongly displaying 0.BTC instead of the actual amount. The fee is correct, but the amount sent is set to zero. I am ultra-paranoid so I did not make de transaction because of that small detail, for I am not sure if the mistake is just in showing the number or it can affected the transaction in anyhow.

![Mar14::212856](https://github.com/spesmilo/electrum/assets/149641827/df991fb0-1fa0-4bb8-97f5-5e6d9702d820)

**Comment by anonnfr** [comment]
BTW, I increased the zeroes after decimal point in settings, but it still only displays 0 instead of the actual value.

![Mar14::214010](https://github.com/spesmilo/electrum/assets/149641827/a23a3e41-5580-42c4-a989-40b14d6f9e36)

**Comment by ecdsa** [comment]
this probably indicates that you are sending to yourself; coins are not leaving your wallet.

**Comment by anonnfr** [comment]
I just checked, you are right. And that makes perfect sense, I feel dumb now, lol. Thank you very much for the quick response, Sir.
