### ISSUE TITLE
Missing possibility to manually enter fee as described in docs

### ISSUE THREAD

**Issue by Franselbaer** [spesmilo/electrum#8957]
There's no option to set a fee manually as described in the docs.

<img width="1320" alt="snap" src="https://github.com/spesmilo/electrum/assets/11044625/7dc894ca-7110-447e-9119-8c11cec6d784">

**Comment by ecdsa** [comment]
in the drop-down menu of the transaction creation window

**Comment by Franselbaer** [comment]
Got it. You need to really click "pay" to come to the second screen

<img width="1138" alt="snap2" src="https://github.com/spesmilo/electrum/assets/11044625/6ad75568-7286-43c2-9739-a4bb23d4bab8">
