### ISSUE TITLE
Spend only confirmed coins in paytomany function

### ISSUE THREAD

**Issue by bar-boss** [spesmilo/electrum#8966]
Hello.
I have Windows version of Electrum. In preferences in Transaction tab I check "Spend only confirmed coins".
Where I can find this settings in "paytomany" function in commands.py file?

**Comment by ecdsa** [comment]
in the same place as for a regular payment.

**Comment by bar-boss** [comment]
> in the same place as for a regular payment.

There is no "spend only confirmed coins" settings.

async def paytomany(self, outputs, fee=None, feerate=None, from_addr=None, from_coins=None, change_addr=None,
                        nocheck=False, unsigned=False, rbf=True, password=None, locktime=None, addtransaction=False, wallet: Abstract_Wallet = None):

**Comment by ecdsa** [comment]
In the "New transaction" dialog, after you click Pay

**Comment by bar-boss** [comment]
> In the "New transaction" dialog, after you click Pay

I'm talking about the console version of Electrum, not the desktop

**Comment by ecdsa** [comment]
ah sorry. you should use the `setconfig` command

`./run_electrum -o setconfig confirmed_only true`

**Comment by bar-boss** [comment]
Thank you
