### ISSUE TITLE
Kyc rule

### ISSUE THREAD

**Issue by Trias54** [spesmilo/electrum#8972]
Hi

I read yesterday about a new rule 
https://www.coinlive.com/news/eu-implements-new-aml-laws-bans-anonymous-crypto-wallets

It will be possible to use your wallet in the future without kyc? 

Greetings

**Comment by ecdsa** [comment]
The term "wallet" is ambiguous. It may refer to a wallet service providers, or to wallet software. We are a wallet software distributor, and we have no control over what users do with our software.

We have yet to see what the regulator means. However, if it becomes illegal to use self-custodial wallet software, then it will also become illegal to use the Bitcoin Core software (we are not different from Bitcoin Core in that regard). This would mean that Bitcoin itself becomes illegal. As far as I understand, this is not what the law is about.
