### ISSUE TITLE
make bip-39 view-only wallets capable of PSBT on android

### ISSUE THREAD

**Issue by pony-montana** [spesmilo/electrum#8977]
Hi, I think would be good to make the android version capable to do psbt with bip-39 view only wallets.

EDIT:

A solution could be:

- Integrate an explicit way to populate the [derivation path] and [fingerprint] field when importing bip-39 view-only wallets. On desktop it is possible to do that using the console or importing some specially crafted json. On android, as far as I tried, it is not possible as android electrum lacks console and the "import wallet" possibility.

I think a GUI explicit solution in the wizard would be the best and it would expand electrum compatibility with bip-39 either on desktop and android.

If this solution wouldn't be considered well, a way to give power users a workaround is to integrate in the android version at least one of these functions, to make it "on pair" with desktop:

- console.
- import wallet from file (to import view-only wallet with populated fields from electrum desktop or from HW). This feature seems to me the less controversial to implement.

**Comment by pony-montana** [comment]
studying better I found that much of the problem I encountered hacking around with PSBTs on electrum are caused by a not full-support of bip-39. For example, importing a zpub from an electrum HD wallet populate also the fingerprint and the derivation path of the wallet. I know this is a bip-39 fault and it improper design, but bip-39 today is defacto standard and need "full-support".
Full support of bip-39 is implement an explicit way to populate these field of the wallet.

So, remoduling part of my issue, my request become:

- integrate an explicit way to populate the [derivation path] and [fingerprint] field when importing bip-39 view-only wallets. On desktop it is possible to do that using the console or importing some specially crafted json. On android, as far as I tried, is not possible, and android electrum lacks the function of "import wallet". I think a GUI explicit solution in the wizard would be really useful.

**Comment by SomberNight** [comment]
This is not really related to the android/qml gui.

It should get solved as part of necessary wizard changes once we have https://github.com/spesmilo/electrum/issues/5715 / https://github.com/spesmilo/electrum/issues/5694.

I will close this now as I would prefer not to add temporary hacks just for this.
