### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

### ISSUE THREAD

**Issue by GEEKGEEKOP** [spesmilo/electrum#8992]
```
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```
WTF?

**Comment by SomberNight** [comment]
`aiorpcx` has `websockets` as an optional dependency
Looks like you have `websockets` installed, but it is a very [old version](https://github.com/python-websockets/websockets/blob/e217458ef8b692e45ca6f66c5aeb7fad0aee97ee/docs/project/changelog.rst#90). At the same time, you are using a fairly recent version of python. This old vs new mismatch is causing the problem.

You will need to either upgrade or delete the `websockets` package.

**Comment by accumulator** [comment]
As mentioned above, nothing we can do. closing.

**Comment by SomberNight** [comment]
> ```
> [noroozi@fedora ~]$ pip install websockets
> Requirement already satisfied: websockets in ./.local/lib/python3.11/site-packages (6.0)
> ```

The flag you want is `--upgrade`:
`$ pip install --upgrade websockets`
