### ISSUE TITLE
New channel with onion address: ConnStringFormatError: Hostname does not resolve (getaddrinfo failed)

### ISSUE THREAD

**Issue by KeefeJ** [spesmilo/electrum#9002]
For example, if I try to open a new channel with the following connection string:
`020b831768ded7615eef25b34639c14b912496137ff5218ad3277d0efd57a32e09@555jr2qys2id2dfaxllj27rhqz4ue3v4s5aiivip4kma7uasow2vigid.onion:9735`

I get the error even though I have the Tor proxy enabled here and Tor running:
![image](https://github.com/spesmilo/electrum/assets/845582/b07c6704-ee26-4a14-92ab-da92abee4f2e)

The culprit appears to be this code in add_peer() in lnworker.py:
https://github.com/spesmilo/electrum/blob/5f95d91/electrum/lnworker.py#L545-L550
```            # Try DNS-resolving the host (if needed). This is simply so that
            # the caller gets a nice exception if it cannot be resolved.
            try:
                await asyncio.get_running_loop().getaddrinfo(host, port)
            except socket.gaierror:
                raise ConnStringFormatError(_('Hostname does not resolve (getaddrinfo failed)'))
```

When I remove that code, Electrum proceeds to successfully connect to the node, presumably over the Tor network via the configured proxy. I guess that asyncio's getaddrinfo() isn't using the proxy for this (ephemeral?) DNS lookup, but the subsequent code that actually establishes the connection _does_ use the proxy for the lookup?

Besides this being a functional flaw, is this also an unexpected info leak, if it does all new-peer DNS lookups initially in plaintext even when a proxy is configured?

**Comment by SomberNight** [comment]
> Besides this being a functional flaw, is this also an unexpected info leak, if it does all new-peer DNS lookups initially in plaintext even when a proxy is configured?

Good point. This is not addressed by https://github.com/spesmilo/electrum/pull/9010

I don't quite understand which DNS lookups go through the proxy and which don't. I think only the aiorpcx and aiohttp stuff might be going through the proxy.
This was last changed in https://github.com/spesmilo/electrum/commit/297568a148879967f944b123d96d78cc0115e4fb.
@accumulator What do you think?
I remember that change was made to work around something, but I don't remember what it was...

**Comment by accumulator** [comment]
> > Besides this being a functional flaw, is this also an unexpected info leak, if it does all new-peer DNS lookups initially in plaintext even when a proxy is configured?
> 
> Good point. This is not addressed by #9010
> 
> I don't quite understand which DNS lookups go through the proxy and which don't. I think only the aiorpcx and aiohttp stuff might be going through the proxy. This was last changed in [297568a](https://github.com/spesmilo/electrum/commit/297568a148879967f944b123d96d78cc0115e4fb). @accumulator What do you think? I remember that change was made to work around something, but I don't remember what it was...

- `SOCKS4` does not support resolving for the client, the client resolves hostnames locally
- `SOCKS5` and `TOR` can resolve for the client, and this is configured for `aiohttp` requests (rdns=True), `aiorpcx` (https://github.com/spesmilo/electrum/blob/3b0cdef871a67403bf454541b2fc6da6638667bc/electrum/util.py#L1905) and `xmlrpc` (wraps around `make_aiohttp_session`)

**Comment by accumulator** [comment]
If I remember correctly, part of the issue with the monkeypatch was that it was incompatible with IPv6.

BTW, is SOCKS4 in use anywhere nowadays? I remember having trouble finding an implementation to test against :)

**Comment by accumulator** [comment]
w.r.t. privacy, we should avoid all direct `getaddrinfo` calls if a proxy is configured.

Resolving OpenAlias is a special case here, and leaks. A fix would be to resolve OpenAlias over `DNS-over-HTTPS-over_Proxy`

**Comment by SomberNight** [comment]
> If I remember correctly, part of the issue with the monkeypatch was that it was incompatible with IPv6, and not fixable without doing a lookup, which defeats the purpose

Ah indeed. It is a bit disappointing though that we can't find a generic DNS-leak fix. The old one was quite elegant IMO (but yeah it is ipv4-only).

I was experimenting a bit with at least logging something if there is a DNS-leak, though not sure how useful that is. (https://github.com/SomberNight/electrum/commit/f4ff83ae18bcc279b70af0d71aef8b4c33ddc72b - but looking at it now it would at least need another special exemption for the proxy address. Also, this does not cover dnspython.)

> BTW, is SOCKS4 in use anywhere nowadays? I remember having trouble finding an implementation to test against :)

No idea. Perhaps it is not then.

> w.r.t. privacy, we should avoid all direct getaddrinfo calls if a proxy is configured.

Right... how about simply not doing the DNS lookup in this specific example?
```diff
diff --git a/electrum/lnworker.py b/electrum/lnworker.py
index c7e944dc8b..d518476ab8 100644
--- a/electrum/lnworker.py
+++ b/electrum/lnworker.py
@@ -543,14 +543,10 @@ class LNWorker(Logger, EventListener, NetworkRetryManager[LNPeerAddr]):
                     host, port, timestamp = self.choose_preferred_address(list(addrs))
             port = int(port)
 
-            if host.endswith('.onion'):
-                if not self.network.proxy:
-                    raise ConnStringFormatError(_('.onion address, but no proxy configured'))
-                if not self.network.is_proxy_tor:
-                    raise ConnStringFormatError(_('.onion address, but proxy is not a TOR proxy'))
-            else:
+            if not self.network.proxy:
                 # Try DNS-resolving the host (if needed). This is simply so that
                 # the caller gets a nice exception if it cannot be resolved.
+                # (we don't do the DNS lookup if a proxy is set, to avoid a DNS-leak)
                 try:
                     await asyncio.get_running_loop().getaddrinfo(host, port)
                 except socket.gaierror:
```

**Comment by accumulator** [comment]
If no proxy is configured, we still need to exclude `.onion` address lookups
