### ISSUE TITLE
Coin selection using more input than needed

### ISSUE THREAD

**Issue by GeetaCX** [spesmilo/electrum#9022]
I'd like to know why did electrum use two input while the smallest one was large enough.

The transaction paid more than 60$ in fees, not really a good time to consolidate.

![image](https://github.com/spesmilo/electrum/assets/167935789/08477faf-bd5e-489b-b8e3-aa34ba9c5b73)

There was 5 other input that were large enough for 0.0579265 on their own, Why chose two?

**Comment by SomberNight** [comment]
Hmm. Not sure. Normally the coinchooser would not add unnecessary inputs atm.

Did you manually select coins?
What did you specify in the "pay to" field? Was it multi-line, or was it just the "...q7986" address?

**Comment by GeetaCX** [comment]
Afaik was the most regular type of transaction possible.

RBF by default,  No coin selection, No pay to many.

Will follow up if something like that happens again.
