### ISSUE TITLE
Bypass Lightning channel closure fee reservation

### ISSUE THREAD

**Issue by khell** [spesmilo/electrum#9023]
Hi! The situation is I opened a Lightning channel around the bare minimum required BTC (0.002) but due to the insane fees on L1 and Electrum's hardcoded requirement to reserve + buffer enough BTC to close a channel, my channel is frequently unusable to send BTC when fees are high. This effectively means Lightning usage in Electrum is still tied heavily to L1 fees. I know this is from a safety perspective, but if we don't want to close a channel why do we need this check? Could you add an option for us to bypass this check?

**Comment by SomberNight** [comment]
- The channel reserve is enforced by both nodes, so we cannot have an option that lets us unilaterally ignore it.
- The closing fees are paid by the channel opener, and they are "reserved" on every commitment transaction, to ensure the channel can be unilaterally closed by either party.
    - The fee spike buffer was added "on top" of the this, to make it less likely that channels become ["stuck"](https://github.com/lightningnetwork/lightning-rfc/issues/728).

> if we don't want to close a channel why do we need this check?

What if the other node wants to close the channel? The opener pays for the close in either case.
Also, what if the other node disappears? You would want to be able to close the channel then.
