### ISSUE TITLE
Вывод биткоина.

### ISSUE THREAD

**Issue by opahopasws** [spesmilo/electrum#9024]
Доброго Дня! Выводил btc через обменник, и почему то, мой btc решили вернуть обратно на счет кошелька. Но есть нюанс, вернули не те деньги. Прошу Вас помочь разобраться, получается что 20 тысяч рублей остались у Вас где то! 
Грубо говоря было отправлено btc с электрума (0.00463761) - а вернулось (0.00214438), прошу помочь разобраться!!
![photo_2024-04-24_12-16-58](https://github.com/spesmilo/electrum/assets/167974182/be60782a-54c4-46c8-bddd-cabedd199dee)

**Comment by SomberNight** [comment]
Hi. It is difficult to understand your description.
It seems you might be confused about ["change"](https://en.bitcoin.it/wiki/Change) and ["mining fees"](https://en.bitcoin.it/wiki/Miner_fees).
Note that mining fees have recently become unusually high, and indeed your transaction pays ~2.2 mBTC as fees.
Is that the amount you are "missing"?
Anyway, please read the linked articles.
