### ISSUE TITLE
Acinq trampoline fees have been raised recently

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#9033]
According to @t-bast, the trampoline routing fees of the Acinq node were recently raised to 0.4%
The highest fee level tried by Electrum is 0.3% plus a base fee of 100 sats:
```
    {
        'fee_base_msat': 100000,
        'fee_proportional_millionths': 3000,
	'cltv_expiry_delta': 576,
    },

```

**Comment by t-bast** [comment]
That is correct, we indeed raised our trampoline fees to 0.4% + 4 sats. We do reject payments that use a lower fee. This can be an issue in the multi-trampoline setting, but as was discussed with the introduction of blinded paths, there won't be a need for multi-trampoline payments in the future: a single trampoline node paying to a blinded path guarantees privacy while being more efficient than using multiple trampoline nodes.
