### ISSUE TITLE
`ledger-bitcoin` update to 0.3.0

### ISSUE THREAD

**Issue by carlosala** [spesmilo/electrum#9035]
It seems like https://github.com/LedgerHQ/app-bitcoin-new/issues/192#issuecomment-1946251482 dependencies issues have been resolved. Shall we update to the latest version?
0.2.1 is working fine though 👍🏻

**Comment by SomberNight** [comment]
I wanted to update now, but I could not find a changelog. Without that, I am reluctant.
Opened https://github.com/LedgerHQ/app-bitcoin-new/issues/295.
