### ISSUE TITLE
Address on Receive tab goes outside the window

### ISSUE THREAD

**Issue by helpau** [spesmilo/electrum#9049]
Set up: the wallet shows transactions at startup (I imported a random testnet address with transactions when creating the wallet)
1. Open electrum
2. Go to Receive
3. Сlick Create request

Expected: address shown in full
Actual: the element with the address is cropped
![image](https://github.com/spesmilo/electrum/assets/30323047/d75807a7-2353-447d-be07-09ec1f49692b)
Walkaround: full screen window
![image](https://github.com/spesmilo/electrum/assets/30323047/a8091a4e-98fa-42c4-b4bf-c745bb8b18bd)

**Comment by SomberNight** [comment]
With https://github.com/spesmilo/electrum/commit/4159ceee3524024a2dee2322a509cac3c9ebb308, there is a new quirk. The size of the square on the right becomes dependent on its content, notably help texts become huge:

<details>
 <summary>pic1</summary>

![pic1](https://github.com/spesmilo/electrum/assets/29142493/7c451d15-b63d-4871-8c4c-2944787141e6)
</details>

<details>
 <summary>pic2</summary>

![pic2](https://github.com/spesmilo/electrum/assets/29142493/dbe89f46-2901-4eb4-8845-c3b05a37ae27)
</details>

Layouting the receive tab is starting to become notoriously difficult :P

**Comment by helpau** [comment]
Confirm fix, can't reproduce on [3d189d9](https://github.com/spesmilo/electrum/commit/3d189d99a5ae1458a659c8d39320cd1e42627ca1)
