### ISSUE TITLE
When entering BIP39 mnemonic with Portuguese words auto-complete only suggests English words, and checksum not validated ("unknown wordlist")

### ISSUE THREAD

**Issue by Pauleiras** [spesmilo/electrum#9051]
O programa não reconhece as palavras (SEEDS) em português na aba para cadastrar novas carteiras. Só é reconhecidas palavras em inglês. Eu gerei 12 palavras (SEEDS) em português no ian coleman e ao tentar cadastrar essas palavras no campo "Enter Seed" elas são sugeridas autocompletar em INGLÊS e ao final no check sum aparece a mensagem: Lista desconhecida! Por favor, adicionem a lista d palavras em português.

**Comment by Pauleiras** [comment]
![WhatsApp Image 2024-05-13 at 23 03 43](https://github.com/spesmilo/electrum/assets/169736070/73462d32-5aef-4dd9-984a-a7abf03b4c35)
![WhatsApp Image 2024-05-13 at 23 03 44(2)](https://github.com/spesmilo/electrum/assets/169736070/ec87a312-4cce-4a36-804c-89be3d99950d)
![WhatsApp Image 2024-05-13 at 23 03 44(1)](https://github.com/spesmilo/electrum/assets/169736070/ea470da4-85d6-4473-b7fe-b650f34a092d)
![WhatsApp Image 2024-05-13 at 23 03 44](https://github.com/spesmilo/electrum/assets/169736070/da84d24e-bab9-4537-98c1-5bbe2ad89e4f)

**Comment by SomberNight** [comment]
> Eu gerei 12 palavras (SEEDS) em português no ian coleman e ao tentar 

If you used Ian Coleman's website to generate a seed, I imagine you have a BIP39 mnemonic. (from https://iancoleman.io/bip39/)

You should click "Options", and select BIP39 there.

> e ao final no check sum aparece a mensagem: Lista desconhecida!

Indeed you will get the "wordlist unknown" warning. It is not a hard error and you can simply ignore it.

> elas são sugeridas autocompletar em INGLÊS

The software would have to recognise that you are trying to use the Portuguese wordlist (and have that wordlist in the first place). (I guess it could ask the user for the language...)
I am sorry but there are simply too many languages to support all. Non-English mnemonics have bad portability in general and are difficult to support. Even the authors of BIP39 have changed their opinion over the years and the BIP now officially [recommends against](https://github.com/bitcoin/bips/blob/e2f7481a132e1c5863f5ffcbff009964d7c2af20/bip-0039.mediawiki#wordlists) internationalisation.

Electrum lets you restore from non-English BIP39 seeds, but indeed there is no auto-completion of words and there is an "unknown wordlist" warning when doing so. We do not plan to add more support for different language seeds.
