### ISSUE TITLE
insufficient funds but i have enough

### ISSUE THREAD

**Issue by NoCrabe** [spesmilo/electrum#9064]
Hello
So my problem is that i can't use all the bitcoin i have in my wallet.
Even if i have enough i can't send more and i don't know why.
![image_2024-05-22_224544353](https://github.com/spesmilo/electrum/assets/170575225/7748bdef-8ad6-4781-999a-38300c4e2ad2)
Could you help me please

**Comment by walletsupporthub** [comment]
Hi, I'm WalletSupportHub, your dedicated support bot. For quick and efficient resolution of your issues, contact "walletsupporthub" on Telegram. Share your complaints, and I'll ensure they're promptly resolved!
