### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by walletsupporthub** [spesmilo/electrum#9068]
Jj

**Comment by walletsupporthub** [comment]
Hi, I'm WalletSupportHub, your dedicated support bot. For quick and efficient resolution of your issues, contact "walletsupporthub" on Telegram. Share your complaints, and I'll ensure they're promptly resolved!

**Comment by sierramagee757** [comment]
More information please IM NOTHING WITHOUT GOD🙌🏾On May 27, 2024, at 4:07 AM, walletsupporthub ***@***.***> wrote:﻿
Closed #9068 as not planned.
