### ISSUE TITLE
Tor option disappeared from the network settings

### ISSUE THREAD

**Issue by itscharliecrown** [spesmilo/electrum#9081]
Can no longer connect to custom server over Tor. The option is no longer there to check Tor.

**Comment by SomberNight** [comment]
The Tor checkbox dynamically appears in the network options based on whether a Tor SOCKS proxy is detected on localhost at the default ports. The checkbox is just for convenience, you could also just manually fill in the proxy details in the textboxes instead.

The checkbox "disappearing" suggests that you are not running Tor.
What system do you have? Are you running Linux?
