### ISSUE TITLE
ELECTRUM version 4.5.5

### ISSUE THREAD

**Issue by KRISTOBALLE** [spesmilo/electrum#9084]
Bonjour d'habitude j'utilise  électrum sur mon pc pour faire divers transactions et la depuis 2 mois je m'étais absenter j'ai ré  ouvert électrum pour faire un envois et l'option payer est genre grisé je ne peut pas payer alors je comprend pas j'ai mis a jour j'ai regarder ce qui pouvait ne pas aller mai j'ai rien trouver et je comprend pas pourquoi je ne peut plus faire de transactions alors que je peut en recevoir sur ce compte je vous remercie de me venir en aide cordialement kristoballe

**Comment by ecdsa** [comment]
there is not enough information to help you.
note that an attacker with access to your computer might have replaced your wallet with a watching-only wallet.
