### ISSUE TITLE
payment unconfirmed

### ISSUE THREAD

**Issue by BrendaFidder** [spesmilo/electrum#9109]
![2024-06-28 15_29_20-Praktijk - Outlook - Outlook](https://github.com/spesmilo/electrum/assets/154621818/d671be70-06de-429e-91d0-ad182e9abe85)
![2024-06-28 15_29_20-Praktijk - Outlook - Outlook](https://github.com/spesmilo/electrum/assets/154621818/36d89dbb-d205-49a8-a94b-a22fd05f7151)
 Good afternoon, 

I've got problems with paying by Electrum. See attachment. For almost 2 weeks my payment stays unconfirmed. 
Can you please confirm my payment so I can get my order.

Kind regards,
Brenda Fidder

**Comment by accumulator** [comment]
> I've got problems with paying by Electrum. See attachment. For almost 2 weeks my payment stays unconfirmed. Can you please confirm my payment so I can get my order.

We are no miners, but you can try bumping the fee to e.g. 10 sat/vB
