### ISSUE TITLE
Feature request: add fields to CSV export

### ISSUE THREAD

**Issue by PierreRochard** [spesmilo/electrum#911]
Please add fields such as the address you're receiving with / sending to and utxo index. They would be helpful for reconciling the CSV export data to block chain data.

Thanks,

Pierre

**Comment by ecdsa** [comment]
The transaction id has been added to the csv/json data.

**Comment by ecdsa** [comment]
The addresses you are receiving with or sending to are not always unique, so we woud need to include them as lists. That does not work well with CSV..
I guess the txid is sufficient.

**Comment by PierreRochard** [comment]
Thank you @ecdsa, downloading new version now for testing

**Comment by PierreRochard** [comment]
Looks good, any plans to include the utxo index @ecdsa ?

**Comment by ecdsa** [comment]
what do you mean by that? a transaction typically spends several utxos, so it's a list, like addresses

**Comment by PierreRochard** [comment]
I see two possible solutions:

1\ Have input and output columns that each has a list of tuples format [(txid, index), ... ] - not great for CSV
or
2\ Break up rows so that each row is a unique (input or output, txid, index, amount, timestamp)

It may make sense to have this as part of an "advanced" or "detailed" export.
