### ISSUE TITLE
GPG fingerprint clarification

### ISSUE THREAD

**Issue by saisonxiang** [spesmilo/electrum#9119]
Can anyone within the github umbrella give me a copy copy on the following fingerprint of the fresh electrum.dmg for MacOS of a wonderland build that may end up south of Mexicali someday?

The GPG suite shows it as valid but not trusted. I would just like some sort of clarification on what we are to do in this instance when performing checksum hashes for a .dmg that is a possible target of man-in-the-middle hookwink shennanigans. GPG says it checks out but it wants me to validate the trust on my own. My research rat tendencies led me to a long winded how do you do with a old page I've poured over before and gotten crotchety responses from the key validators when I attempted to verify the fingerprint via email or via voice chat. They say they shouldn't be expected to field every wet behind the ears researcher that wants a validation but I don't really get the point of the exercise if that is the case. We build hoops to jump through and then none of you want us to jump through the hoops you built for us to jump through. You want tips on your bitcoin wallet projects and spammy help pages that cause our systems to be over run by telepathic psycho asian waifu buddhist federation members that want to talk about things my mother wouldn't approve of. What kind of summer course is this? JK. I love this s***

637D B1E2 3370 F84A FF88 CCE0 3152 347D 07DA 627C

**Comment by accumulator** [comment]
Trust is something you assign to a key yourself, when you have sufficiently validated it.

E.g., fetch the public key from a github project, then verify the fingerprint through another channel, for instance the twitter profile bio of the developer.
