### ISSUE TITLE
I can't open the PSBT transaction to sign offline on electrum

### ISSUE THREAD

**Issue by GabrielChaves1** [spesmilo/electrum#9120]
I'm trying to sign a PSBT transaction and I get this error when scanning the transaction QR code, can anyone help me to solve it?

**Electrum 4.3.4 version**

```
Electrum was unable to parse your transaction:
SerializationError('Failed to recognise tx encoding, or to parse transaction.
raw: 027ada81df7d086bd884a2f17f245a...')
```

**Comment by accumulator** [comment]
version 4.3.4 is quite old, please retry with 4.5.5

**Comment by GabrielChaves1** [comment]
Hi, I installed the new version of electrum but got the same error

**Comment by GabrielChaves1** [comment]
> version 4.3.4 is quite old, please retry with 4.5.5

Hi, I installed the new version of electrum but got the same error

**Comment by mrdqc** [comment]
Como resolveu?

**Comment by mrdqc** [comment]
I had the same error

**Comment by GabrielChaves1** [comment]
> I had the same error

I was using a different wallet for watch only, I did the offline setup with electrum and I'm using a watch wallet on electrum too and now it works

**Comment by raulpacheco2k** [comment]
Você forneceu poucos detalhes, é difícil ajudar nessa situação. Você está tentando ler o QR Code?
