### ISSUE TITLE
I'm having  a hard time sending my Bitcoin 

### ISSUE THREAD

**Issue by tkrepel** [spesmilo/electrum#9123]
I'm having an issue when I try to send my Bitcoin one it says it's unpaid when I do it through the laptop and two when I use the mobile app that I started it all with it will not allow me to scan the address with the camera or input the address manually in any way it just freezes on my phone and stops working then shuts down I even reinstalled the app but nothing so now I thought around $35 in Bitcoin that is stuck in your guys's app that I cannot access or send to anywhere anyway not very happy I feel as if this app is intention is to rip me off because it was more than willing to accept the payment going in but will not allow me to send payments out

**Comment by accumulator** [comment]
On mobile the camera could be flaky with certain device models and buggy camera drivers (I can't be sure until I can have a look at logs), but on the laptop you should be able to create and send a transaction.

It isn't totally clear to me what you are doing. 
What are the exact steps you are taking? How did you create the wallet on your laptop? Did you import the wallet seed?

**Comment by tkrepel** [comment]
I don't remember what I did but I can try again
