### ISSUE TITLE
New wizard does not set keystore password if storage is not encrypted

### ISSUE THREAD

**Issue by ik105** [spesmilo/electrum#9147]
If in v4.5.0+ you create a wallet, set a password but uncheck "Encrypt wallet file", then secrets in the file will not be encrypted.

**Comment by ecdsa** [comment]
what do you mean by "secrets" ?

**Comment by ik105** [comment]
seed phrase and private master key

**Comment by ecdsa** [comment]
oh indeed. Thanks for reporting.
This seems to be a wizard issue. 
The encrypt wallet file checkbox works correctly in the "change password" dialog.

**Comment by ecdsa** [comment]
I think this line is the reason:
https://github.com/spesmilo/electrum/blob/76f5d6ceb07b49e403f63488832fd6cb397ee91b/electrum/wizard.py#L609

Apparently the new wizard does not set keystore encryption if the storage is not encrypted.

**Comment by ecdsa** [comment]
@SomberNight can you check if the above fix works with hardware wallets?
