### ISSUE TITLE
MASALAH KONEKSI

### ISSUE THREAD

**Issue by BAIET** [spesmilo/electrum#9150]
Masalah koneksi kenapa ga bisa kebuka wallet saya, jaringan merah terus padahal bagus jaringannya
![Screenshot_2024-07-23-22-44-27-114_org electrum electrum](https://github.com/user-attachments/assets/056a8cf8-efe4-4b83-8a3f-7500f0baf37a)

**Comment by ecdsa** [comment]
please post in English...
