### ISSUE TITLE
Cursor in password field

### ISSUE THREAD

**Issue by greggluhring** [spesmilo/electrum#9157]
For the past several versions, when runnung Electrum or a wallet if it's already open, the cursor used to automatically be in the password field, so I could begin typing immediately. Lately, the field must be clicked and then the password typed. It's extra mouse movement that over the years I've gotten used to not being necessary.

Sorry, I don't know the lingo of what to call the fields or the initial cursor placement. I hope I make sense.

Thank you.

**Comment by pbies** [comment]
This is crucial for design. Now I need to press Tab 3 times to get cursor in password field. It should be right at the password prompt! +1

**Comment by Johannesbyte** [comment]
$ pytest tests/test_bitcoin.py -v
