### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [spesmilo/electrum#9159]
### Description:

In the "electrum/electrum/plugins/digitalbitbox/digitalbitbox.py", I have identified a security vulnerability about hardcode salt.  And do not use hardcode/static salt in the PBKDF, which would make output easy to predict.

### Location:

https://github.com/spesmilo/electrum/blob/master/electrum/plugins/digitalbitbox/digitalbitbox.py#L151

```python
return to_hexstr(hashlib.pbkdf2_hmac('sha512', key, b'Digital Bitbox', iterations = 20480))
```

https://github.com/spesmilo/electrum/blob/master/electrum/storage.py#L175

```python
secret = hashlib.pbkdf2_hmac('sha512', password.encode('utf-8'), b'', iterations=1024)
```

### Reference

- CWE-330: Use of Insufficiently Random Values

### Recommendations

- Generate salt with cryptographic secure PRNG.

**Comment by SomberNight** [comment]
- storage.py#L175
    This is a known issue, duplicate of https://github.com/spesmilo/electrum/issues/3147.
    Please search existing issues before opening a new one. This one is even tagged security.

- digitalbitbox.py#L151
    The inner workings of the digitalbitbox firmware are out of our control, and modifying this KDF would require modifying the firmware also (not just the plugin). Also, the digitalbitbox is probably not really supported by the vendor (bitbox) anymore. So this won't be fixed.
