### ISSUE TITLE
The Main CyberCrime Department of the Criminal Police of the Ministry of Internal Affairs of the Republic of Belarus  - ncp-by@htcd.gov.by

### ISSUE THREAD

**Issue by syshchik** [spesmilo/electrum#9168]
The Main CyberCrime Department of the Criminal Police of the Ministry of Internal Affairs of the Republic of Belarus is supporting the criminal case initiated under Article 206 of the Criminal Code of the Republic of Belarus (Robbery) on the fact of attempted armed robbery involving entry into the home of a citizen of the Republic of Belarus.
In the course of the criminal case it was found out that on August 15, 2024, at about 13:00 (UTC +3) in Minsk, two unknown persons, disguised as employees of public utilities, entered the dwelling and, threatening the owner with a gun, beating him and torturing him with a stun gun, fastened the latter to a table, after which they demanded to transfer to the cryptocurrency wallet bc1q4dsuxuxmnx26jj2ajhdnd8e9ufszhzzhzgu8aeasynj the amount of 23,000 bitcoins (the owner is a programmer who previously worked for a foreign company). The owner refused, explaining that he did not have such an amount. The attackers left the apartment, stating that they gave him 24 hours to think about it. After that, the victim called law enforcement authorities.
On the basis of the above, we ask you to assist in solving this crime by providing us with information to the official mailbox ncp-by@htcd.gov.by: whether the wallet bc1q4dsuxuxmnx26jjj2ajhdnd8e9ufszhzzhzgu8aeasynj was allocated to any of the users of your service. In case the wallet was allocated by your service, please provide us with all possible information about the client who registered it, or keep this information until sending an international request for legal assistance.

**Comment by SomberNight** [comment]
Your profile is not convincing enough.
