### ISSUE TITLE
Ledger Flex supported?

### ISSUE THREAD

**Issue by man55** [spesmilo/electrum#9179]
Is Ledger Flex wallet supported or is there some bug or malfunction?

The Electrum cannot detect connected hardware wallets when Flex is connected to PC.
At the same time if I connect Nano S, then everything is fine, electrum can detect it.

Win11 fresh.
Electrum 4.5.5
Flex with latest fw.

**Comment by Clarevero1** [comment]
> Is Ledger Flex wallet supported or is there some bug or malfunction?

@man55 Are you having any issues with it ?

**Comment by man55** [comment]
> > Is Ledger Flex wallet supported or is there some bug or malfunction?
> 
> @man55 Are you having any issues with it ?

Yes, the Electrum cannot detect connected hardware wallets when Flex is connected to PC. 
At the same time if I connect Nano S, then everything is fine, electrum can detect it.

Win11 fresh.
Electrum 4.5.5
Flex with latest fw.

**Comment by Clarevero1** [comment]
> > > Is Ledger Flex wallet supported or is there some bug or malfunction?
> > 
> > 
> > @man55 Are you having any issues with it ?
> 
> Yes, the Electrum cannot detect connected hardware wallets when Flex is connected to PC. At the same time if I connect Nano S, then everything is fine, electrum can detect it.
> 
> Win11 fresh. Electrum 4.5.5 Flex with latest fw.


@man55 okay this could be a hardware failure It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledger live support](https://thedappsupport.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by man55** [comment]
@Clarevero1 you are a scammer, report

**Comment by Clarevero1** [comment]
> @Clarevero1 you are a scammer, report

@man55 what do you mean I’m a scammer I’m just trying to help you out

**Comment by man55** [comment]
Thanks a lot. We look forward to the release of the new version!

**Comment by man55** [comment]
Could you please release a new version with Ledger Flex support?
After all, it is not necessary to wait long for these bugs to be fixed for 4.5.6?
TNX.
![Снимок экрана 2024-09-18 132247](https://github.com/user-attachments/assets/87ca38b5-5787-4e5b-bacd-e626ccf4cda4)

**Comment by man55** [comment]
Time goes by, Flex support is still not added. I bought a Flex and can't use it normally, although I got used Electrum for 8 years. It is impossible to wait forever. Today I found out that Sparrow wallet added Flex support three weeks ago, I tried it and it works great. And now I'm afraid I will stay with Sparrow and forget about Electrum. It's a pity. Sorry.
