### ISSUE TITLE
Cannot create LN channel on 4.5.5

### ISSUE THREAD

**Issue by tricopol** [spesmilo/electrum#9180]
When I try to create a channel on Electrum 4.5.5, I receive a message stating that the channel was succesfully opened, but the funding transaction is stuck as "Local", if you attempt to broadcast it the server rejects the TX with error "Some of the outputs pay to a non-standard script". The funding TX has for some reason 2 outputs, one of them a SCRIPT.
<img width="403" alt="image" src="https://github.com/user-attachments/assets/d01274fc-a1ef-4792-9932-58a470fea1f2">

**Comment by SomberNight** [comment]
> The funding TX has for some reason 2 outputs, one of them a SCRIPT.

The OP_RETURN output is there due to the `use_recoverable_channels` config option (default enabled).
Not sure why the bitcoind considers that output to be nonstandard. Which electrum server are you connected to when getting this? Maybe try with another one.

**Comment by tricopol** [comment]
I'm using my own Electrum server (latest version) and bitcoin node (27.0.0), Electrum server displays the following error when attempting to broadcast the TX:

`2024-09-03 00:33:58,113:INFO:ElectrumX:[800] error sending transaction: scriptpubkey`

**Comment by SomberNight** [comment]
Are you running unmodified Bitcoin Core, or do you have some patches / config changes / or running maybe Knots/etc?

**Comment by tricopol** [comment]
Unmodified Bitcoin Core here.

**Comment by tricopol** [comment]
Resolved: bitcoin node had `datacarrier=0` on its config. Removed it and it now works.
