### ISSUE TITLE
Incorrect 0 balance showing

### ISSUE THREAD

**Issue by Nisaba** [spesmilo/electrum#9185]
The thing is that I use also Green wallet with the same Seed phrase in another PC, in same time with Electrum.
I made a transaction in Green -> OK.

But the same transaction makes the balance to 0 under Electrum because it doesn't recognize the chargeback address generated by Green.

Please correct this, thank you.

**Comment by SomberNight** [comment]
Hi. More details would be needed. How does Green generate the change address? (e.g. derivation path, script type)
If you don't know, can you at least tell if the change address ~looks similar to the other addresses? Or show the transaction.

**Comment by Nisaba** [comment]
Thank you for your feedback.
Do you have a PM to send you the transaction link ?

**Comment by SomberNight** [comment]
You can send the txid to the email in my github profile.

**Comment by Nisaba** [comment]
OK, done.
Thank you

**Comment by Nisaba** [comment]
OK, it worked ! Thanks
