### ISSUE TITLE
Consider replacing Source Sans Pro with Source Sans 3 in Revealer

### ISSUE THREAD

**Issue by sorenstoutner** [spesmilo/electrum#9186]
Revealer currently embeds the Source Sans Pro font.  However, this has been superseded upstream by Source Sans 3.

https://github.com/adobe-fonts/source-sans/issues/192

If you are interested, I would be willing to create a pull request that makes this change (which would slightly simplify my Debian packaging).

**Comment by SomberNight** [comment]
Feel free to PR the change if it helps you.

**Comment by sorenstoutner** [comment]
I have created a PR at:

https://github.com/spesmilo/electrum/pull/9190
