### ISSUE TITLE
"No seed" error on Ubuntu 14.10

### ISSUE THREAD

**Issue by lfairy** [spesmilo/electrum#919]
When run, Electrum 1.9.8 displays the first-run popup ("Electrum could not find an existing wallet. What do you want to do?") as expected.

However, when I choose any option and click "Next", the same dialog is displayed again.

Clicking "Next" a second time results in a "No seed" error [(screenshot)][1]. The app then closes.

Any ideas? I have only encountered this bug on Ubuntu 14.10 -- 14.04 works fine -- so likely it's a platform specific issue. A couple of [forum users][2] have encountered the bug as well.

[1]: http://i.imgur.com/5MHa40j.png
[2]: https://bitcointalk.org/index.php?topic=843419.0

**Comment by ecdsa** [comment]
ok, so it seems to be fixed then. thanks.

**Comment by valerio-bozzolan** [comment]
(Related: https://bugs.launchpad.net/ubuntu/+source/electrum/+bug/1397752)
