### ISSUE TITLE
Feature Request: Testnet 4 support

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#9193]
Testnet4 has been live for several months and will be available in Bitcoin Core with the next release in a month or so. Would be great for Electrum client and servers to support it.

https://testnet4.com/

**Comment by SomberNight** [comment]
done in https://github.com/spesmilo/electrum/pull/9197

**Comment by accumulator** [comment]
Is there a testnet4 faucet somewhere?

**Comment by wakiyamap** [comment]
The first link, testnet4.com, has a list of faucets.
