### ISSUE TITLE
Android: does not show existing seed extension word

### ISSUE THREAD

**Issue by prof7bit** [spesmilo/electrum#9204]
When you have used a seed extension word on Desktop wallets and you click the show seed icon it will show the seed AND the extra word.

When you do the equivalent on Android it will only show the seed and nothing else! Not even a hint that there might be an extra word. It also seems impossible to export or show (QR) the private master key.

I have just spent a few frustrating hours trying to move my mobile wallet to my new phone using the "show seed" function. Only shortly before i was ready to give up and transfer it on-chain to a new wallet it dawned on me that there could be an extra word and I tried some of the words I might have used and about 15 attempts later I found it.

* [bug] Existing wallet does not show extra word (possible loss of coin due to incomplete backup ability)

* [Annoyance] Android wallet has a very cumbersome UI for entering the extra word, you have to scroll down to even find that hidden option and then the android keyboard pops up without scrolling it further up to see the line of text.

**Comment by accumulator** [comment]
> When you have used a seed extension word on Desktop wallets and you click the show seed icon it will show the seed AND the extra word.
> 
> When you do the equivalent on Android it will only show the seed and nothing else! Not even a hint that there might be an extra word. 

Indeed, thx. Provisionally fixed in #9205.

>     * [Annoyance] Android wallet has a very cumbersome UI for entering the extra word, you have to scroll down to even find that hidden option and then the android keyboard pops up without scrolling it further up to see the line of text.

Agreed, this could be improved.
