### ISSUE TITLE
artifact url improvment for f-droid binaries

### ISSUE THREAD

**Issue by thecockatiel** [spesmilo/electrum#9210]
Hi
I'm trying to do the necessary work for releasing this app on f-droid, regarding issue #1700 
it would be nice if there could be some adjustments made to the website to help ease stuff a bit for reproducible builds
currently the url is like this: `https://download.electrum.org/4.5.5/Electrum-4.5.5.0-arm64-v8a-release.apk`

it would be nice if you can make `https://download.electrum.org/4.5.5.0/Electrum-4.5.5.0-arm64-v8a-release.apk` also point to the same file ( `4.5.5.0` -> `4.5.5` redirection)

I'll also open a PR for adding the fastlane metadata files for f-droid, which can help you control the metadata without opening MRs on f-droid
if you don't like the idea of metadata living inside the repo, I can still add it directly to f-droid repo, It's your decision

**Comment by thecockatiel** [comment]
I have made the required metadata to build the app, but I'm having a hard time reproducing the exact apk
any tips ?
I have used the same env, sdk, ndk ,ant and steps of the dockerfile inside the gitlab runner, but it's producing different apk by a few kilobytes
most notably the pyc files inside the apk have a slightly different size than the one produced from docker image
the python version seems to be the same, so I am having a hard time tracking down the issue

**Comment by thecockatiel** [comment]
can you list possible things that can cause the build to vary ?

**Comment by thecockatiel** [comment]
I even tried replacing the base image with `registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm` and deleting the existing user with id 1000 and tried building the image and it still fails

**Comment by thecockatiel** [comment]
the `private.tar` that is included in the apk is one part of the issue. the path at which the project is built affects the reproduction. for example inside the `main.pyc` inside the `private.tar` that is included in the assets of the apk we see this path:
![image](https://github.com/user-attachments/assets/68bc5be2-14d3-4d59-bcc3-06904cc2a57f)

which should not be there I think, but is.

**Comment by SomberNight** [comment]
Thank you for looking into this!

>  it would be nice if there could be some adjustments made to the website to help ease stuff a bit for reproducible builds
currently the url is like this: https://download.electrum.org/4.5.5/Electrum-4.5.5.0-arm64-v8a-release.apk
>
> it would be nice if you can make https://download.electrum.org/4.5.5.0/Electrum-4.5.5.0-arm64-v8a-release.apk also point to the same file ( 4.5.5.0 -> 4.5.5 redirection)

I think we could drop the trailing `.0` from the android apks. It is a historical thing that we don't need/utilise anymore. (Some years ago, prior to reproducible builds at least, sometimes we had `.1` and `.2` releases just for android-specific bugs.)
https://github.com/spesmilo/electrum/blob/9a5edfdd74972d935247d15b3be41b254ee3a07e/electrum/version.py#L1-L2

We could have `APK_VERSION = ELECTRUM_VERSION`, however it is not that easy, as it also affects the android `versionCode`.
python-for-android is used to generate`versionCode` from this version string, see e.g. https://github.com/SomberNight/python-for-android/commit/edb7e4fe6db9965caf887aee97605daf124502df

Maybe we could pass in the versionCode ourselves via an environment variable (`APP_ANDROID_NUMERIC_VERSION` might work, but have to double-check [what buildozer expects](https://github.com/kivy/buildozer/blob/f3c5bb336bc648e77f1ba3f1a33749b252075f81/buildozer/targets/android.py#L1273)) in [make_apk.sh](https://github.com/spesmilo/electrum/blob/9a5edfdd74972d935247d15b3be41b254ee3a07e/contrib/android/make_apk.sh#L90-L104). We would need to calculate it from `ELECTRUM_VERSION` and the arch.

**Comment by thecockatiel** [comment]
hmmm
I think it would be fine if the website only do the redirect mentioned (if not hard), then we probably don't have to make any other change

**Comment by thecockatiel** [comment]
and I think as you pointed out dropping the trailing 0 would cause the generated versionCode number to be less than previous builds, and needs manual generation with taking into account the dropped 0

**Comment by thecockatiel** [comment]
I have opened the MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15858

**Comment by thecockatiel** [comment]
F-droid has requested that the arch number to be put at the end of the version code:
`Per arch number should be at the end of the versionCode, the metadata is sorted by versionCode, eg. Good = 40505002, Bad = 24050500`

**Comment by SomberNight** [comment]
> F-droid has requested that the arch number to be put at the end of the version code:
`Per arch number should be at the end of the versionCode, the metadata is sorted by versionCode, eg. Good = 40505002, Bad = 24050500`

Ok, so that's another reason to change the versionCode calculation (in addition to dropping the `.0` suffix). I will do that.

**Comment by thecockatiel** [comment]
hmm,
@SomberNight can you add create a branch on top of 4.5.5 and add the metadata commits to it, so we can reference the commit for releasing 4.5.5 ?
otherwise we have to release 4.5.6 and update the merge request

**Comment by SomberNight** [comment]
> can you add create a branch on top of 4.5.5 and add the metadata commits to it, so we can reference the commit for releasing 4.5.5 ?

I don't know if it's still possible to reproduce the same binary as 4.5.5 if we include a commit such as https://github.com/spesmilo/electrum/commit/6b713676fb74a5d1418c868aab4123d4629c6c5a.

I will try to cherry-pick stuff and then have a 4.5.6 released.

**Comment by thecockatiel** [comment]
hmm, with exclusion commit and fastlane metadata on top of 4.5.5 tag, its possible to get the same release I believe,
But I guess waiting for 4.5.6 release is probably a better idea if it's around the corner, as we can go and enable the auto update on the MR

**Comment by thecockatiel** [comment]
Uh. I completely forgot about SOURCE_DATE_EPOCH in makefile. can you make an amend with a new commit with the date of the one on 4.5.5 ? is it possible ?

**Comment by thecockatiel** [comment]
Also, I'm not sure, but maybe it's a good idea to fix the SOURCE_DATE_EPOCH on future releases ?

**Comment by thecockatiel** [comment]
oh okay, we can just rebase to 4.5.5 in prebuild it seems. you don't need to do anything.

**Comment by SomberNight** [comment]
> Uh. I completely forgot about SOURCE_DATE_EPOCH in makefile. can you make an amend with a new commit with the date of the one on 4.5.5 ? is it possible ?
> Also, I'm not sure, but maybe it's a good idea to fix the SOURCE_DATE_EPOCH on future releases to a specific date ?

I thought about this a bit now.
The problem is that, as [the comment there](
https://github.com/spesmilo/electrum/blob/267df91c0b6a305eed0189cb0d2b9c03d539d98d/contrib/android/Makefile#L10) says, p4a's logic determining whether to update the code running on a device depends on the version+timestamp. A hardcoded timestamp would mean that if someone built their own apk in release mode, they would not be able to upgrade unless they manually change either the version number or the hardcoded timestamp. I think this has the potential for the occasional major confusion (even for the people actively working on the project).

Maybe we could change p4a not to rely on the timestamp when deciding whether to unpack new files. I guess the naive way would be to have it hash the archive that it is considering to unpack, and use that hash as basis of comparison (instead of version+timestamp). I imagine they are not doing this because it is expensive to read and hash the whole archive on every app start. But maybe there is a faster alternative, e.g. it might be possible to grab a crc32 checksum in constant time (if it's stored as an attribute of the archive) and use that for comparison.

**Comment by thecockatiel** [comment]
Also I think as we no longer need to change the url, I'll close this issue
