### ISSUE TITLE
Cannot load wallet (2): BitcoinException('invalid bitcoin address: ltc1q5us27kfx56l93....')

### ISSUE THREAD

**Issue by zubilo-afk** [spesmilo/electrum#9214]
Cannot access wallet. I see the following error message after entering my password: "Cannot load wallet (2): BitcoinException('invalid bitcoin address: ltc1q5us27kfx56l93....')".

At this point it seems my Litecoin are inaccessible.

Any help is much appreciated.

**Comment by ecdsa** [comment]
this is not the repo of electrum-ltc
