### ISSUE TITLE
address copied from qt receive tab differs from address shown in qr code

### ISSUE THREAD

**Issue by scoial404** [spesmilo/electrum#9217]
I bought bitcoin and I'm using electrum 4.4.5 and blockchain it shows that the purchase was transferred but it didn't bring me the money, it's been 24 hours since the purchase. what to do
https://www.blockchain.com/explorer/transactions/btc/08f78bbbc91899cbfb235ddb23b4717596b9419c91c1058dc7aa23f3c7d39219

**Comment by Support-techCommunity** [comment]
Hello,

We've received your report, kindly forward the received/recipient 
address so we can run some checks.
What exchange did you purchase your asset from?

Regards.

On 2024-09-29 16:09, scoial404 wrote:

> I bought bitcoin and I'm using electrum 4.4.5 and blockchain it shows 
> that the purchase was transferred but it didn't bring me the money, 
> it's been 24 hours since the purchase. what to do
> https://www.blockchain.com/explorer/transactions/btc/08f78bbbc91899cbfb235ddb23b4717596b9419c91c1058dc7aa23f3c7d39219
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>


Links:
------
[1] https://github.com/spesmilo/electrum/issues/9217
[2]

**Comment by scoial404** [comment]
btc

**Comment by scoial404** [comment]
https://www.dropbox.com/scl/fi/1tzv1vd167sveubj5inyd/2024-09-29-19-19-02.mp4?rlkey=0hr8g4rwgat2wd9dmx66nrgbm&st=n408vn4w&dl=0

and it shows me that I have 0
and also what it shows on the website (from the video) is not mine because I should only have about $133

**Comment by Support-techCommunity** [comment]
Kindly forward the receivers address; We don't accept links.

On 2024-09-29 17:28, scoial404 wrote:

> https://www.dropbox.com/scl/fi/1tzv1vd167sveubj5inyd/2024-09-29-19-19-02.mp4?rlkey=0hr8g4rwgat2wd9dmx66nrgbm&st=n408vn4w&dl=0 
> [1]
> 
> and it shows me that I have 0
> and also what it shows on the website (from the video) is not mine 
> because I should only have about $133
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you commented.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://www.dropbox.com/scl/fi/1tzv1vd167sveubj5inyd/2024-09-29-19-19-02.mp4?rlkey=0hr8g4rwgat2wd9dmx66nrgbm&st=n408vn4w&dl=0
[2] 
https://github.com/spesmilo/electrum/issues/9217#issuecomment-2381417573
[3]

**Comment by scoial404** [comment]
bc1qqhrgpmvt43v5l0kxnhp58g5j8eyjqes0chp8nk

**Comment by SomberNight** [comment]
Hi. Ignore the previous commenter "Support-techCommunity", they are most likely a scammer.

I watched your video. Note that the address you copy-paste is different than the one in the QR code, here:
![Screenshot from 2024-09-29 19-14-41](https://github.com/user-attachments/assets/72707c34-6049-41ba-9c75-13ddfae6bef7)

That is highly suspicious and is not expected at all.

-----

Just as a sanity check, could you double-check if the copy-pasted address belongs to your wallet?
See https://bitcoinelectrum.com/frequently-asked-questions/#how-can-i-tell-if-an-address-belongs-to-my-wallet
In the application, go to the `Console` tab, and run
```
>>> ismine("bc1qqhrgpmvt43v5l0kxnhp58g5j8eyjqes0chp8nk")
```
What do you get as result?

-----

Also, where did you download Electrum from? Try to find the exact URL in your browser history/downloads.

**Comment by SomberNight** [comment]
>>  and also what it shows on the website (from the video) is not mine because I should only have about $133
>
> Just as a sanity check, could you double-check if the copy-pasted address belongs to your wallet?
> What do you get as result?

Ah, sorry, I missed the part where this address had already received 12 transactions. Well, in that case, it definitely is not yours.
That confirms that either you downloaded a modified malicious copy of Electrum, or you have another malicious program running in the background, which hijacks your clipboard.
See https://electrum.readthedocs.io/en/latest/malware.html#clipboard-hijacker


> Also, where did you download Electrum from? Try to find the exact URL in your browser history/downloads.

^ this question is still relevant.

**Comment by scoial404** [comment]
![image](https://github.com/user-attachments/assets/ad3b2c97-9a01-4cb5-90c1-c93e8d67da2e)
![Screenshot 2024-09-30 074159](https://github.com/user-attachments/assets/ce968e0d-753d-4d48-97ee-f982d988c6ff)

ad the ismine command says false for me

**Comment by scoial404** [comment]
the link - https://download.electrum.org/4.5.5/electrum-4.5.5-setup.exe

**Comment by SomberNight** [comment]
That link is good, so it might be the other option: you have another malicious program running in the background, which hijacks your clipboard.
You could try copy-pasting some addresses, and see if they paste correctly. E.g. ctrl+C this address: `1BitcoinEaterAddressDontSendf59kuE` and paste it into Notepad. See if it pasted correctly.

**Comment by scoial404** [comment]
It became 1LMgJdMyDH5cRJswVgmtcCwPx5exUGGW5o
![Screenshot 2024-09-30 152244](https://github.com/user-attachments/assets/78dec819-5040-4ace-af1d-a6fd759f7054)
