### ISSUE TITLE
Electrum is unable to load ANY Keepkey hardware wallet with pass phrase 

### ISSUE THREAD

**Issue by louiscardinal** [spesmilo/electrum#9222]
Currently Electrum wallet works fine with Keepkey hardware wallets however it fails with any passphrases used.

I have confirmed that the keepkey passphrase functions fine with other wallets, confirming that it is an electrum specific issue.

Screenshot provided showing that the electrum client only allows users to click 'Back', no 'Finish' is possible after entering a pass phrase:
![z1](https://github.com/user-attachments/assets/bcc6eba3-1cdf-41f0-a68a-53ed379c56fd)

The client just makes you stuck, unable to load any pass phrase wallets.

**Comment by Kiari26** [comment]
Hello @louiscardinal i will suggest you message support on telegram https://t.me/Electrum_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks

**Comment by Larede29** [comment]
Hello @louiscardinal i will suggest you message support on telegram https://t.me/Electrum_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks

**Comment by accumulator** [comment]
I can't verify, as I don't have a keepkey. @SomberNight?

**Comment by Bryan1722-alt** [comment]
Hello @louiscardinal i will suggest you message support on telegram https://t.me/Electrum_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks

**Comment by SomberNight** [comment]
@louiscardinal I am unable to reproduce the issue. Could you provide exact reproduction steps?

What I have noticed however is that the passphrase is ~cached for the session, and so it is not practical to open multiple wallets corresponding to the same hardware device which use different passphrases.
(This however is not specific to keepkey, you can test with e.g. a Trezor One too.)

Example of what I mean:
- Have two wallet files, both standard wallets with single hw keystore, using keepkey. One has passphrase "apple", other has no passphrase. Both are encrypted.
- freshly connect hw device now, and freshly start electrum
- try to open "apple" wallet
- decryption flow --> wizard asks for PIN, wizard asks for passphrase
  - enter passphrase "apple"
- wallet "apple" successfully opens
- open new wizard
- try to open no-passphrase wallet
- decryption flow --> error
  - the wizard does not ask for the PIN, does not ask for the passphrase. Instead the existing hw device session is reused.
  - error: `This hardware device could not decrypt this wallet. Is it the correct one?`

workaround:
Reconnect hw device (or maybe even close/reopen Electrum) to clear session.

@louiscardinal ^ is this what you mean?

**Comment by louiscardinal** [comment]
So I found a solution and isolated the issue. If you create a wallet (along with a wallet file stored locally) initially with one passphrase, it will only work with that specific passphrase.

If you want to use the same seed but a different passphrase, only by generating a new wallet on electrum will it be readable and work.

Therefore, I am unsure if this is a feature or a bug, but you cannot use one wallet file for multiple passphrases with a given hardware wallet device.

**Comment by SomberNight** [comment]
> Therefore, I am unsure if this is a feature or a bug, but you cannot use one wallet file for multiple passphrases with a given hardware wallet device.

You need to create one wallet file per master public key. The passphrase is mixed into the bip32 root entropy, hence it results in a separate tree of keys, and so also a new master public key. Also, when you encrypt the wallet file using a hw device, the encryption key is derived from the bip32 tree: this is why you cannot decrypt the wallet file if you enter the incorrect passphrase.

You need to create a separate wallet file for each passphrase you use the hw device with.
