### ISSUE TITLE
Stolen Bitcoin's

### ISSUE THREAD

**Issue by Draincorp** [spesmilo/electrum#9229]
I Think you guys should fix the bugs for real idk how its possible my BTCs to get stolen and i dont even know how !
I never added anything suspicious and i never shared my SeedPhrases with no one Plus i had a password to withdraw the funds !
So how that happened i really need an explanation about it !!!
Please guys fix this issue this aint even possible !
My electrum wallet got hacked so freaking easy and im pretty sure is because of ur developers they need to add more safety shit in electrum !

**Comment by Dapssupport11** [comment]
> I Think you guys should fix the bugs for real idk how its possible my BTCs to get stolen and i dont even know how !
> I never added anything suspicious and i never shared my SeedPhrases with no one Plus i had a password to withdraw the funds !
> So how that happened i really need an explanation about it !!!
> Please guys fix this issue this aint even possible !
> My electrum wallet got hacked so freaking easy and im pretty sure is because of ur developers they need to add more safety shit in electrum !




Hey @Draincorp ,

I recommend reaching out to the support team for recovery  assistance. You can find the dedicated support link below:

[Electrum wallet dApps Support Requests](thedappsupport.com).

**Tip: Click the live chat icon at the bottom-right corner of the page to connect with a support agent in real-time.**

**Comment by Harrystarafk** [comment]
> I Think you guys should fix the bugs for real idk how its possible my BTCs to get stolen and i dont even know how ! I never added anything suspicious and i never shared my SeedPhrases with no one Plus i had a password to withdraw the funds ! So how that happened i really need an explanation about it !!! Please guys fix this issue this aint even possible ! My electrum wallet got hacked so freaking easy and im pretty sure is because of ur developers they need to add more safety shit in electrum !

They will never reply you on here and they can’t do anything I almost lost about 10 ethereum few days ago when my wallet got hacked and all my funds withdrawn but thanks to blackhathacker who helped me recover my coins from the scammers  message him on telegram https://t.me/Blackhathacker110

**Comment by rparp** [comment]
I encountered theft as well using sparrow wallet. Same like electrum

**Comment by ecdsa** [comment]
Sorry, but this kind of report is not useful; there is no information about a possible bug in electrum.
The most likely explanation is that you either exposed your seed to a third party, or that your computer has malware.
