### ISSUE TITLE
Is there an anti-clipper feature for electrum?

### ISSUE THREAD

**Issue by DarkBit-hash** [spesmilo/electrum#9230]
A few days ago, while sending bitcoin to someone via electrum wallet, I sent bitcoin to another address (the attacker's address) because of the clipper. this is not the electrum wallet's problem, of course, but my question is: if someone wrote a built-in anti-clipper code for electrum wallet and made a pull request, would you accept it?

**Comment by accumulator** [comment]
The clipboard contents are outside of our control.

**Comment by SomberNight** [comment]
Out of curiosity, how would this "anti-clipper" work?

**Comment by DarkBit-hash** [comment]
> Meraktan, bu "kesme önleyici" nasıl çalışır?
if a btc address is copied to the clipboard it makes a note of that address and then checks a few times to see if what was copied to the clipboard is the same as the address. i have written some code for this and if given the green light that it will be approved i will make a pull request for it
