### ISSUE TITLE
Default settings allow using `electrum lnpay $invoice` without any confirmation or password

### ISSUE THREAD

**Issue by Midar** [spesmilo/electrum#9236]
The default settings allow using `electrum lnpay $invoice` without any confirmation or password. That seems a bit risky, as anyone who can get access to the socket gets to spend all available LN balance.

**Comment by SomberNight** [comment]
> anyone who can get access to the socket gets to spend all available LN balance

Note: on Linux/macOS, the default is to use unix sockets for the RPC, on Windows we listen on a TCP port on localhost.
In either case, the RPC is protected with a random password, which is stored in the config file. So in practice to be able to run commands such as `lnpay`, the conditions are that (1) the wallet has to be open, (2) read access for the config file is needed.
(read access to the config file implies access to the unix socket or localhost tcp also)

**Comment by Midar** [comment]
Hm, isn't the wallet always encrypted when using a HW wallet? In any case I'm seeing the lock symbol in Electrum and I can just use `lnpay` without any confirmation whatsoever.

**Comment by SomberNight** [comment]
> Hm, isn't the wallet always encrypted when using a HW wallet?

No, you can click the lock and disable file encryption.

> I can just use lnpay without any confirmation whatsoever.

On master? Can you give repro steps?

**Comment by Midar** [comment]
No, this was on 4.5.5, waiting for the next signed release before I let this touch my wallet ;). What I meant to say is that before this change at least, it already had access, even with a HW wallet.

**Comment by SomberNight** [comment]
> Before this change, all commands worked without password-authentication (compare e.g. signmessage (which started a CLI hw handler), and lnpay (which just executed), both of which worked). Quirk: the "requires_password" commands required the user to explicitly pass a dummy password.

Yes that's already what I meant there ^

**Comment by SomberNight** [comment]
The mentioned changes were included in the recent releases.
I am not fully satisfied with how it works now, but not sure how we can improve on this easily. We can revisit if there is a better idea.

**Comment by Midar** [comment]
I checked now and it told me to unlock my wallet. It was unlocked, but a HW wallet, so I would guess this means it's WAI now, except for maybe a slightly confusing error? (I guess "Command `lnpay` cannot be used with a hardware wallet" would be more accurate).
