### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by EurekaIgnem** [spesmilo/electrum#9240]
If privacy is important, the FAQs should offer the readers a Question - Answer near the top of the stack?    Are Descriptions for send/receive transactions completely hidden from all entities outside the sphere of the electrum wallet?     Suggested Answer:  Presently,  entitites outside of the Electrum wallet which are located along the transaction path, close to the point of transaction origin, could access the description.

**Comment by SomberNight** [comment]
Sorry but I have a trouble understanding what you are saying. What precisely do you mean by "transaction", "description", and "transaction path"?
