### ISSUE TITLE
Electrum IOS fork

### ISSUE THREAD

**Issue by rosariopizza** [spesmilo/electrum#9247]
Hi,

I’ve been using Electrum for 11 years, but I really miss it on iOS. I’m thinking about creating a fork for iPhone users. What features would you like to see? Are there any improvements you’d want compared to the Android version? Also, what privacy and other features do you think would be useful?

If this is really of interest to someone else besides me, I can try to create an open-source version for iOS.

**Comment by accumulator** [comment]
I'm not sure what you are suggesting. Do you want to create a fork and work outside of this project on a client? Or do you want to contribute within this project?

Please be aware that although `buildozer`, which we use in the build process, has support for iOS but there's no Qt6 bootstrap available yet (AFAIK), so either that has to be added, or a GUI will have to be implemented in the native iOS UI stack. Also, there's currently no CI support for iOS, and that's not trivial to add. Lastly, we do value the fact that we can build reproducibly.

If you can get to a reproducibly built 'Hello World' app on iOS, with Electrum's backend code loaded, that would already be quite a feat.

Either way, I think we can close this issue, as there's no actionable thing to do for us.
