### ISSUE TITLE
UI Help button doesn't work for "Sweep Private Key"

### ISSUE THREAD

**Issue by nostitos** [spesmilo/electrum#9255]
![image](https://github.com/user-attachments/assets/1b51a50a-8ee8-4fce-bdf6-15313edfa523)

**Comment by SomberNight** [comment]
I don't have that button.
What OS are is this? If Linux, what DE?

**Comment by nostitos** [comment]
Windows

**Comment by ecdsa** [comment]
it looks like a tooltip, not a button

**Comment by nostitos** [comment]
Tooltip show when over the question mark, question mark does nothing, It turn into a 🚫

**Comment by ecdsa** [comment]
That question mark is not an Electrum widget, it is part of your window manager.
Do you see it on other dialogs?

**Comment by nostitos** [comment]
This is from another machine
![image](https://github.com/user-attachments/assets/2df20e07-fee4-4af8-a72d-c3535e601974)

It's not anywhere else.

**Comment by SomberNight** [comment]
On Windows, that question mark button is there is a lot of dialogs.
It is also there in the "Wallet Information" dialog, in the "Network" dialog, in the "Preferences". It's in lots of dialogs and it is "not working" in any of them. It is either Qt or the window manager that decides to put it there.

Nevertheless, on master we have upgraded from Qt5 to Qt6 (though existing releases all still use Qt5), and it looks like "?" button is no longer there with Qt6.
