### ISSUE TITLE
Electrum bitcoin windows intaller gives 3 PGP signatures

### ISSUE THREAD

**Issue by kewpiedoll** [spesmilo/electrum#9267]
verification therefore produces this:

`gpg: Signature made 10/16/24 06:58:49 Pacific Daylight Time
gpg:                using RSA key 637DB1E23370F84AFF88CCE03152347D07DA627C
gpg: Can't check signature: No public key
gpg: Signature made 10/16/24 06:21:05 Pacific Daylight Time
gpg:                using RSA key 0EEDCFD5CAFB459067349B23CA9EEEC43DF911DC
gpg: Can't check signature: No public key
gpg: Signature made 10/16/24 05:46:06 Pacific Daylight Time
gpg:                using RSA key 6694D8DE7BE8EE5631BED9502BD5824B7F9470E6
gpg: Good signature from "Thomas Voegtlin (https://electrum.org) <thomasv@electrum.org>" [unknown]
gpg:                 aka "ThomasV <thomasv1@gmx.de>" [unknown]
gpg:                 aka "Thomas Voegtlin <thomasv1@gmx.de>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.`

The signatures download has 3 sigs. Where are the other 2 public keys and what are they for? I can't find an answer on the internet, or YT videos. Is this is a good download?

**Comment by ecdsa** [comment]
The website says:
> The current executables have been signed by [ThomasV](https://raw.githubusercontent.com/spesmilo/electrum/master/pubkeys/ThomasV.asc), [SomberNight](https://raw.githubusercontent.com/spesmilo/electrum/master/pubkeys/sombernight_releasekey.asc), [Emzy](https://raw.githubusercontent.com/spesmilo/electrum/master/pubkeys/Emzy.asc).
