### ISSUE TITLE
Electrum android version on Google Play is still at 4.5.5.0

### ISSUE THREAD

**Issue by xrviv** [spesmilo/electrum#9272]
Electrum Android version on Google Play is still at 4.5.5.0

![image](https://github.com/user-attachments/assets/06084d97-5dce-4e12-86ac-de97391edc1f)
![image](https://github.com/user-attachments/assets/198b6906-19d5-408c-b8ba-ffc4beac4c24)

**Comment by accumulator** [comment]
Actually, v4.5.6 is on the play store, but it's on a limited 20% rollout. We found a regression in this version and are in the process of preparing v4.5.7
