### ISSUE TITLE
Security Proposal

### ISSUE THREAD

**Issue by ghostn4444** [spesmilo/electrum#9317]
**Feedback pgp** 

Why don't you provide the hash of the installation file? It would be easier to verify the integrity of the program.

Validating pgp requires a program, which could lead to a possible serious error of security. It would be much easier to validate an md5, cha-256 or do as Linux Tails validates the file.

Thank you for your attention. 🙏

**Comment by ecdsa** [comment]
from our website:

>  GPG signatures are a proof that distributed files have been signed by the owner of the signing key. For example, if this website was compromised and the original Electrum files had been replaced, signature verification would fail, because the attacker would not be able to create valid signatures. (Note that an attacker would be able to create valid hashes, this is why we do not publish hashes of our binaries here, it does not bring any security).
