### ISSUE TITLE
Blank Wallet

### ISSUE THREAD

**Issue by rnt3400** [spesmilo/electrum#9319]
HI, I add some money via qr code, next day the history was blank, and on adress show a lot of transacrions.

![erro1](https://github.com/user-attachments/assets/b78d0d58-1816-4475-846a-e1635c746eb4)
![erro2](https://github.com/user-attachments/assets/cc895f72-4309-4bdc-948f-57534f0ca969)

**Comment by Gordonhills** [comment]
Hello @rnt3400 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ELE07638
Please see the link below to our dedicated support line:
[Electrum Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Gordonhills** [comment]
@rnt3400 Did you talk to the support team yet ?

**Comment by Gordonhills** [comment]
@rnt3400 and for you to see the wallet you will have to select other wallet on the url

**Comment by rnt3400** [comment]
@Gordonhills  looks like they don't have a support team, i have to find the an wanswer on foruns, etc

**Comment by blockscout-oss** [comment]
> HI, I add some money via qr code, next day the history was blank, and on adress show a lot of transacrions.
> 
> ![erro1](https://private-user-images.githubusercontent.com/189466337/389210272-b78d0d58-1816-4475-846a-e1635c746eb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTUyODUsIm5iZiI6MTczMjQ1NDk4NSwicGF0aCI6Ii8xODk0NjYzMzcvMzg5MjEwMjcyLWI3OGQwZDU4LTE4MTYtNDQ3NS04NDZhLWUxNjM1Yzc0NmViNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxMzI5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmU2YzgyNTFhMzY1M2YxN2IwNzM5NTE0YTk2YjZkN2Y5NWFkNTA5NTVlMjJmNzYyMzdhZGMzZDE1MjUxOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UcM3SE7aEuxdCGlysH1irubB58sTOr1RcxPz7kU7Cmw) ![erro2](https://private-user-images.githubusercontent.com/189466337/389210273-cc895f72-4309-4bdc-948f-57534f0ca969.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTUyODUsIm5iZiI6MTczMjQ1NDk4NSwicGF0aCI6Ii8xODk0NjYzMzcvMzg5MjEwMjczLWNjODk1ZjcyLTQzMDktNGJkYy05NDhmLTU3NTM0ZjBjYTk2OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxMzI5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTkxMzk3ODRiZTE1ZmRiZDE0OWM5ZTA5NzRkMzQ4MGIxMTFjMjgwYzlhMTZiZTQ5ZjNiM2U4YTRmNzM0NzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jzE54UnM-DD7O2OGjnfKmE_jGgKvX4ZU3XwRe7iCxVQ)

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Electrum Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Gordonhills** [comment]
@rnt3400 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Gordonhills** [comment]
@rnt3400 ignore blockscout message there’s nothing like electrum help centre

**Comment by ecdsa** [comment]
> @Gordonhills looks like they don't have a support team, i have to find the an wanswer on foruns, etc

please do not follow "support" links posted by random profiles. these are scammers trying to steal your funds

**Comment by ecdsa** [comment]
FTR, I just blocked @Gordonhills and @blockscout-oss

**Comment by ecdsa** [comment]
regarding the original issue, there is not enough info to say anything.
it might be malware, or user confusion between different wallets.
