### ISSUE TITLE
RiskWare/Win32.Kryptik.a - Latest version of Electrum

### ISSUE THREAD

**Issue by Makkie121** [spesmilo/electrum#9334]
Hello,

When downloading the latest version of Electrum - which is verified with the signatures, it is flagged as RiskWare/Win32.Kryptik.a.

VirusTotal: https://www.virustotal.com/gui/file/0ac63dbba76d46c290f8439f43b9dafcfb05a4c13ad5aac6c29d227b0fd1b645?nocache=1

**Comment by ecdsa** [comment]
not our fault. please report to the antivirus distributor.

**Comment by Makkie121** [comment]
Thank you — can I please confirm this is in fact a false positive? I shouldn’t be concerned?

I emailed AV yesterday too.

Thank you


On 1 Dec 2024, at 07:49, ThomasV ***@***.***> wrote:

﻿

not our fault. please report to the antivirus distributor.
