### ISSUE TITLE
LN 

### ISSUE THREAD

**Issue by mahalamobile** [spesmilo/electrum#9338]
electrum stop
electrum -o init_lightning
electrum daemon -d

am getting this error: unknown command: init_lightning -> version 4.5.8. is LN enabled already ??

ive also tried electrum -w /home/ubuntu/mywallet add_lightning 
unknown command: add_lightning

any help apprecaited.
wallet has been created and loads correctly, all CLI

**Comment by contribution-hub** [comment]
Hi @mahalamobile 
Contact the [Support page](https://generalwebfixes.web.app) to report your error for further assistance.
Note: Initiate a chat with the live agent on the chat button to get more information about your request via [Support chat](https://generalwebfixes.web.app)

**Comment by mahalamobile** [comment]
Deceptive site ahead

MetaMask flagged the site you're trying to visit as potentially deceptive.
Attackers may trick you into doing something dangerous. Learn more
<https://cryptoscamdb.org/search>

Potential threats on https://generalwebfixes.web.app/ include:

   - Fake versions of MetaMask
   - Secret Recovery Phrase or password theft
   - Malicious transactions resulting in stolen assets


Advisory provided by multiple sources, including Ethereum Phishing
Detector, SEAL, ChainPatrol, and PhishFort.


If we're flagging a legitimate website, please report a detection problem.
<https://metamask.github.io/phishing-warning/v3.0.3/#>

If you understand the risks and still want to proceed, you can continue to
the site.

**Comment by s1ckoleg** [comment]
No need in initiating lightning, it works when you run the daemon. So you can try to run open_channel

**Comment by mahalamobile** [comment]
great thanks
