### ISSUE TITLE
The maximum transfer amount is offered almost 100 times less than what is on the balance! 

### ISSUE THREAD

**Issue by ProstoEx** [spesmilo/electrum#9373]
The maximum transfer amount is offered almost 100 times less than what is on the balance! I can't send it to the address.

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [ELECTRUM SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Parkeragan** [comment]
> The maximum transfer amount is offered almost 100 times less than what is on the balance! I can't send it to the address.

**Comment by ecdsa** [comment]
please provide a screenshot or more details.

**Comment by ProstoEx** [comment]
![изображение_2024-12-21_061741644](https://github.com/user-attachments/assets/18493ba0-6e5e-4e6a-b782-5921117ffdf4)
Please.... what I got to do?

**Comment by ecdsa** [comment]
This is a 2FA wallet. I suppose that it has not yet paid the Trustedcoin fee, so it is adding that fee to the next transaction.
If that is not what you want, I suggest you disable the 2FA service (you will need to restore from seed), and send your funds to a standard wallet (this will save you mining fees, because the 2FA wallet uses 2-of-3 multisig addresses).

**Comment by ProstoEx** [comment]
Oh my God! Apparently, this is exactly what is happening... I just found out about this unnecessary service from the wallet.... Please tell me how can I disable 2fa? I'm very weak on this issue...

**Comment by ecdsa** [comment]
https://electrum.readthedocs.io/en/latest/2fa.html
