### ISSUE TITLE
Feature request: pagination / limited transaction history

### ISSUE THREAD

**Issue by cryptonaut420** [spesmilo/electrum#951]
Sitting at 2,000+ transactions now in my wallet, and it has become slow as HELL to use...  Loading electrum up takes at least a couple minutes just for the GUI to fully load and be usable. Every time it synchronizes my transactions, the program hangs for about at least 30 seconds (cant click on anything else).. and even just entering anything into the "Amount" or "Fee" fields in the Send tab causes huge lag.

Im not sure on the technicals behind this, but any way that there could be an option to only display transactions from X # of previous blocks or something unless otherwise requested? The lag that occurs when you start having a large transaction history makes electrum very difficult / frustrating to use. Note that when switching to a fresh wallet or one with small history, everything works very fast for me.

**Comment by cryptonaut420** [comment]
Not sure how to easily check how many UTXOs are available, but I would imagine that a lot of unspent outputs goes hand in hand with having a long transaction history across several addresses (for e.g, lots of various affiliate/referral link payments that come in every day or so)

**Comment by dabura667** [comment]
> (for e.g, lots of various affiliate/referral link payments that come in every day or so)

Yeah, that's probably it... those utxos aren't worth the bytes they were printed on... so then you get a bloated wallet that will cost you more fees in miner fees than they're worth...

It's a lot better if you periodically send your entire balance to another one of your addresses. That really helps with the slow down.

However at this point, trying to send your whole balance will most likely take forever to sign and result in a large tx that will cost a ton...

**Comment by cryptonaut420** [comment]
Tried the sending-the-whole-balance thing, and looks like UTXO isnt my problem at the moment (only used a few outputs, must have spent the rest recently already). Actually, the fee calculation and transaction signing happened pretty fast, so large UTXO set may have been the issue with that before, however the transaction history list lags quite a bit before updating. Also if I close the wallet and open up the program again, it can take upwards of 5 to 10 minutes for the transaction history to be loaded and displayed.

Seems like there is two separate problems: 1) a large UTXO set can make fee calculations and signing transactions very slow and 2) a large general transaction history makes the "History" tab very slow to load

**Comment by ecdsa** [comment]
I guess the best thing to do is to send your balance to a new wallet, when it reaches that point.
this is the most sensible method of "pagination"
I don't think we want this to be done automatically, though

**Comment by ecdsa** [comment]
still, if you want to share the master public key with me, I can have a look

**Comment by ecdsa** [comment]
note: if the wallet was showing only payment requests (bip70), instead of Bitcoin addresses, then it would be possible to consider that a given address has expired (along with the associated request), and to implement such a "pagination".

**Comment by cryptonaut420** [comment]
@ecdsa sure, is there an email I can send you the pub key to? I would rather not post it publicly

**Comment by ecdsa** [comment]
you can send it to thomasv@electrum.org
I am currently trying to optimize the loading of large wallet files, it might be useful to have a look

**Comment by ecdsa** [comment]
commit e3de121be9a56c84ec80ce79a84f7ce1ae6b9b20 introduces an optimization that makes wallet loading much faster. it will be in version 2.1

**Comment by cryptonaut420** [comment]
just following up to this - can confirm that as of 2.1 everything is working way faster, nice work!
