### ISSUE TITLE
Feature request: Searching and filtering of transaction history

### ISSUE THREAD

**Issue by cryptonaut420** [spesmilo/electrum#952]
This is a feature that would be nice to have. Basically, just some controls in the "history" tab that lets you filter the transaction list based on bitcoin address and/or date range, and then also an option to search based on label/description. "Total Sent" and "Total Received" might be handy to show along with this as well

**Comment by ecdsa** [comment]
I guess the gui could have a search box in place of the current account selector

**Comment by EagleTM** [comment]
Also see #140

**Comment by ecdsa** [comment]
done in 45081b1c8b20598cff2c9eff91518325f5afa6c7
