### ISSUE TITLE
Could not find a version that satisfies the requirement slowaes (from versions: 0.1a1)

### ISSUE THREAD

**Issue by strk** [spesmilo/electrum#956]
On an ubuntu 14.04.1 LTS system, `sudo pip install slowaes` results in the following message:
```
Downloading/unpacking slowaes
  Could not find a version that satisfies the requirement slowaes (from versions: 0.1a1)
Cleaning up...
No distributions matching the version for slowaes
Storing debug log for failure in /home/strk/.pip/pip.log
```

The README file said to run that command. On which system does it work ?

**Comment by ecdsa** [comment]
it's weird, because it works fine if you run: `sudo python setup.py install`

**Comment by ecdsa** [comment]
it required the --pre flag, because it's a prerelease version.
please reopen this issue if it's not fixed.

**Comment by tisto** [comment]
robotframework-djangolibrary 1.0a2 has been released. This works for me now:

    $ mkdir test
    $ cd test/
    $ virtualenv .env
    $ source .env/bin/activate
    $ pip install Django==1.6.9
    $ pip install robotframework-djangolibrary --pre

=> Django version is still 1.6.9
