### ISSUE TITLE
Empty wallet file

### ISSUE THREAD

**Issue by arsenische** [spesmilo/electrum#960]
I don't know how to reproduce the problem, but it happens to me time to time. I experienced it in Electrum 1.9.x and in 2.0 too. 

I start Electrum 2.0 in Ubuntu 14.04:

~/.electrum $ electrum -w mywallet.dat

and get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 5, in <module>
    pkg_resources.run_script('Electrum==2.0', 'electrum')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.0-py2.7.egg/EGG-INFO/scripts/electrum", line 208, in <module>
    gui.main(url)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.0-py2.7.egg/electrum_gui/qt/__init__.py", line 152, in main
    storage = WalletStorage(self.config)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.0-py2.7.egg/electrum/wallet.py", line 58, in __init__
    self.read(self.path)
  File "/usr/local/lib/python2.7/dist-packages/Electrum-2.0-py2.7.egg/electrum/wallet.py", line 100, in read
    raise IOError("Cannot read wallet file.")
IOError: Cannot read wallet file.
```
I check the wallet file -- it is empty (file size is 0). How is it even possible?

I do restore a wallet from a seed or from backup and it works, but it takes long to synchronize because I have thousands of bitcoin addresses and transactions.

**Comment by lazzarello** [comment]
I have encountered the same problem when upgrading from 1.6.2 to 1.9.8. Large version bump I know but I had trouble finding a solution other than this issue. It seems that the RELEASE-NOTES from version 1.7.2 says 

```
* Due to an internal format change, your history may be pruned when
  you open your wallet for the first time after upgrading to 1.7.2. If
  this is the case, please visit a full server to restore your full
  history. You will only need to do that once.
```

It is unclear what a "full server" means though, so I was hesitant to restore from the seed. That appears to be the only workaround.

**Comment by ecdsa** [comment]
@lazzarello this is not related.

**Comment by lazzarello** [comment]
Should I open a new issue for mine?

**Comment by ecdsa** [comment]
no, it's probably the same issue. 
what you read in the release notes is unrelated.

**Comment by arsenische** [comment]
It just happened again, so I can provide few details.

I started Electrum from terminal window:

~/.electrum $ electrum -w mywallet.dat

It started and I saw that there was 1 unconfirmed outgoing transaction. I added 1 more transaction that was unconfirmed as well.

Then couple new blocks appeared in the blockchain (#345870 and #345871, just a minute apart from each other) and Electrum displayed that it was 2 blocks behind.

Then Electrum became unresponsive. I tried to close Electrum, but it still was unresponsive (I didn't force Ubuntu to close it). 

Then I executed "ls -l mywallet.dat" and saw that the wallet file was ~14 mb as expected.

Eventually Electrum window disappeared and I noticed these messages in the console window:
```
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 18 (X_ChangeProperty)
  Resource id:  0x4ad1deb
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 25 (X_SendEvent)
  Resource id:  0x4ad1deb
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 18 (X_ChangeProperty)
  Resource id:  0x4ad4329
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 25 (X_SendEvent)
  Resource id:  0x4ad4329
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 18 (X_ChangeProperty)
  Resource id:  0x4ad4493
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 25 (X_SendEvent)
  Resource id:  0x4ad4493
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 18 (X_ChangeProperty)
  Resource id:  0x4ad5461
X Error: BadWindow (invalid Window parameter) 3
  Major opcode: 25 (X_SendEvent)
  Resource id:  0x4ad5461
```

I executed "ls -l mywallet.dat" and noticed that the file size became 0 :(

**Comment by ecdsa** [comment]
I believe this is caused by daemon threads writing to the wallet file; 
since your wallet file is quite large, a daemon thread might be killed during the write

**Comment by ecdsa** [comment]
replaced all daemon threads, 72688a5cfa25066d1fd6eee646b874725359ff04
it should fix it; otherwise, reopen this issue

**Comment by arsenische** [comment]
Thanks a lot! Will be testing.

**Comment by arsenische** [comment]
@ecdsa The size of my electrum wallet file decreased from ~15Mb to ~4Mb. Is it normal?

PS: I used increased gap limit when I originally created a wallet years ago but now I don't see customizable gap limit. Not sure whether it matters though.

**Comment by chiguireitor** [comment]
This just happened to me with trunk, it seems the wallet gets corrupted somehow. Had to restore from seed. The traceback:

    Traceback (most recent call last):
      File "electrum", line 247, in <module>
        gui.main(url)
      File "\electrum\gui\qt\__init__.py", line 152, in main
        storage = WalletStorage(self.config)
      File "\electrum\lib\wallet.py", line 58, in __init__
        self.read(self.path)
      File "\electrum\lib\wallet.py", line 100, in read
        raise IOError("Cannot read wallet file.")
    IOError: Cannot read wallet file.

**Comment by arsenische** [comment]
@chiguireitor it looks like a test file with json data, I assume private keys are encrypted.

Btw, are you using the latest version of Electrum? The changes to fix this issue were released less than 2 weeks ago.

**Comment by chiguireitor** [comment]
"Already up to date"... i'm on master so probably the fix is on another branch

**Comment by arsenische** [comment]
My Electrum has been synchronizing for a while.

I executed "ls -l mywallet.dat" several times to check whether the data is there. About half of the times it returned 0 as filesize. 

I assume if my computer suddenly shuts down while it is 0 then my wallet data will be lost.
