### ISSUE TITLE
update for #953 (problem with restoring from seed)

### ISSUE THREAD

**Issue by klocpl** [spesmilo/electrum#965]
1.im made new wallet with im never used (was suckesfully sunchonized)
2.after about 1week im made format 
3.somebody send me some 0.0001btc just for check and im realized i have to restore my wallet 
when im restored from seed im recived new addres set 

so it was half cent and i dont need it, but try to confirm "it" maybe it is rare bug

**Comment by ecdsa** [comment]
I guess you did not enter the correct seed phrase

**Comment by klocpl** [comment]
LIKE IM SAID RESTORE WAS SUCKESFULL IM STILL USING THIS WALLET EVERYDAY
WITH THAT SECEND SET OF ADDRES AND ITS WORKING FINE IM EVEN RESTORED IT
ONCE

2015-01-05 5:35 GMT+00:00 ThomasV <notifications@github.com>:
