### ISSUE TITLE
Improve privacy with input selection

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#966]
I didn't look this up in the code, but from looking at the behaviour, i think input selection works somehow like this:
Go through the unspent inputs in priority order, and collect them until the amount is equal or greater than required.  
But if say the last one collected is big enough for the outgoing tx, it would be better for privacy to not include the prior inputs.

unspent0 : 0.01
unspent1 : 0.01
unspent2 : 0.01
unspent3 : 1.0

send 0.5 to 1xxx...

At the moment, all the unspent inputs would be consumed, while unspent3 would be enough. Consuming them all, makes it easy to see that the addresses they belong to, belong to the same wallet.

**Comment by ecdsa** [comment]
@ulrichard  see ae957f37364d0c61f6658c6b877d5efbc5e3c5a4
