### ISSUE TITLE
Multisig restore - preventable user error

### ISSUE THREAD

**Issue by hdbikeroh** [spesmilo/electrum#968]
While playing with 2 of 3 Multisig, I went to restore my wallet.  I entered the seed for the wallet (seed 1), and accidentally pasted the same master public key (mpk 2) as the other two keys.  Electrum happily created new multisig addresses, although it should have probably provided a warning or error of some sort as two keys were the same.

When I tried to create a new wallet again, I accidentally keyed the seed for one wallet (seed 1) and pasted its master public key (mpk 1, not a different wallets mpk) and for the third master public key used another one (mpk 2).  Again, electrum did not complain and generated new multisig addresses.

Perhaps there should be some validation that none of the master public keys are duplicates AND that none of them match the mpk for the provided seed.  This would go a long way to preventing user errors and funds that cannot be recovered.  While I was able to figure out the combination of seeds and mpk's to use so I could sign transactions, this is a problem that can be prevented.

**Comment by nmarley** [comment]
def add_master_public_key(self, name, xpub):
    +        if xpub in self.master_public_keys.values():
    +            raise BaseException('Duplicate master public key')
             self.master_public_keys[name] = xpub
             self.storage.put('master_public_keys', self.master_public_keys, True)

I don't think this should throw an exception, maybe just add a warning. I actually have a multisig wallet where I want this to be the case... the same xpub key multiple times. This is a possibly desired thing, and it was just quashed with commit # 9f9bab6. How would I then restore my wallet? Not possible with this change.
