### ISSUE TITLE
Fee enforce 

### ISSUE THREAD

**Issue by Abd3lk4d3r** [spesmilo/electrum#969]
hello 
I want you to make the fee optional i can't send 0.000048 btc because it say fee must be 0.0001 
and i want to set it 0.00001

**Comment by dabura667** [comment]
it is already set to minimum 0.00001 on git.

**Comment by Abd3lk4d3r** [comment]
I'm using windows version

**Comment by dabura667** [comment]
Which one?:
Installer?
Portable?
Standalone?

**Comment by Abd3lk4d3r** [comment]
I'm installing installer latest version

**Comment by dabura667** [comment]
Ok

1. Search for the install folder: it should be `C:\Program Files (x86)\Electrum` or something of the like.
2. In the install folder find `\lib\bitcoin.py`
3. Right click bitcoin.py and click "Open with..."
4. Choose "Wordpad" (not "Notepad", this is important)
5. Search the document with Ctrl + F and search for `MIN_RELAY_TX_FEE`
6. There should only be one, and it will say `MIN_RELAY_TX_FEE = 10000`
7. Change it to `MIN_RELAY_TX_FEE = 1000`
8. click Save
9. Close the document.
10. Open Electrum (or close then open, if it was already open)
11. Click Options -> Preferences
12. Set the fee to 0.00001 BTC or 0.01 mBTC

You can now send transactions with 0.00001 BTC fees.

Please note that while it is possible to send 0 fee transactions by setting `MIN_RELAY_TX_FEE = 0` it is not recommended, as any transaction with less than 0.00001 BTC per kb will not be relayed.

**Comment by Abd3lk4d3r** [comment]
Thanks man
