### ISSUE TITLE
Commit #9f9bab6 (fix for #968) breaks my multisig wallet

### ISSUE THREAD

**Issue by nmarley** [spesmilo/electrum#970]
This commit introduced an exception for multiple public keys for multisig derivation. But I believe this should be a warning instead.

The standard allows for it, and I have used the same xpub key multiple times for my own multisig wallet. Now my wallet is broken with this commit (#9f9bab6).

**Comment by nmarley** [comment]
Wait, is this even possible? I'm guessing this won't work since I won't be able to sign multiple times with the same key. Or is that possible?

**Comment by dabura667** [comment]
*mind blown*
`<sig_from_A><sig_from_A><2><pubkey_A><pubkey_A><pubkey_B><3><CHECKMULTISIG>`
I wonder if this would be valid...

if so, you have a weak multisig and should probably migrate anyways.....

**Comment by dabura667** [comment]
Have you ever tried sending from your multisig with the 2 same pubkey devices?

**Comment by ecdsa** [comment]
what's the use case for that?

**Comment by nmarley** [comment]
Just for simplicity, I don't think it is desirable, except maybe obfuscation. Certainly not for security.

**Comment by ecdsa** [comment]
well, in that case I think it's better to keep the current behaviour.
