### ISSUE TITLE
Feature Request: Bitcoin URIs not to open a new electrum window everytime

### ISSUE THREAD

**Issue by Tafelpoot** [spesmilo/electrum#971]
Currently, clicking a Bitcoin URI opens a new electrum window.
It would be nice if clicking the URI would reuse the existing electrum window, or at least to have an option for this behavior.

This can be done by passing the bitcoin URI to the daemon, which should trigger its connected window interface to prepare a transaction window.

In Qt terms, the server needs a slot bitcoinURIsend emiting the signal bitcoinURIreceived[str]. The UI is then connected to this slot.

**Comment by ecdsa** [comment]
can you write a pull request?

**Comment by Tafelpoot** [comment]
well.. I'm having troubles to get a list of GUIs connected to the daemon... if you could give me a headstart on this, I'd finish it up gladly :)

**Comment by ecdsa** [comment]
could this work without the daemon?

**Comment by Tafelpoot** [comment]
The recommended way in PyQt is to use a QLocalServer. However we already have a daemon, which would be able to do the job as well.

I did a bit more research and found [this interesting snippet](http://stackoverflow.com/questions/12712360/qtsingleapplication-for-pyside-or-pyqt).
More info [here](http://developer.nokia.com/community/wiki/Run_only_one_instance_of_a_Qt_application)

**Comment by ecdsa** [comment]
fixed in 92e0744470f90dbb52e09bee764d64b6937dc7c4

**Comment by larafale** [comment]
any idea why this does not work on osx ?
