### ISSUE TITLE
Can't send Trezor Transactions on Electrum 2.0 on Windows.

### ISSUE THREAD

**Issue by tl121** [spesmilo/electrum#972]
I have built and installed Electrum 2.0 and Trezor on Ubuntu 14.04 and it works fine.  (This is an all 64 bit installation.)  I have also built and installed on Windows 7.  (This is a 64 bit O/S but Python, Cython, Python-QT are all 32 bits.)  The Windows 7 version works for all the functions I tested including signing, with the exception of sending bitcoins. 

Attempting to send bitcoins results (after multiple "confirm" on Trezor) in an Electrum pop up:
"[Errno 9] Bad file descriptor"
Clicking OK  to this leaves the transaction cancelled and the Trezor hung. (Cancel on the Trezor does nothing.)

Note:  When this failure occurs Electrum is connected (Green dot) to the server.  I have tried with several servers with the same result.

**Comment by tl121** [comment]
The problem had nothing to do with Trezor.  It also happens when restoring a normal wallet from seed, provided that a windows shortcut targeted a .pyw file. This leaves no place to go for the restored address output.  Starting electrum with a .py file avoids this problem and electrum runs OK, including Trezor send transactions. 

Is there some way to suppress this output or send it to a log file or do I have to build a complete Windows .exe file?

**Comment by ecdsa** [comment]
can you post a traceback, and explain how you "built and installed on Windows" ?

**Comment by Tafelpoot** [comment]
How and where do you get a "pyw" file with electrum?
You can build a windows executable using the contrib\build-wine\deterministic.spec with pyinstaller ...

**Comment by tl121** [comment]
I followed the instructions on Github, running ">Python setup.py" from  a Windows command prompt.   ">Python.electrum" works with all functionality that I have tested, including Trezor.  When I was satisfied that this was working, I copied "electrum" to two identical files, named "electrum.py" and "electrum.pyw". 

Using the Windows File Manager, double clicking on "electrum.py" brings up a blank Qt Window and then after a brief delay the Electrum GUI window.  The GUI window works fine. However, doing certain operations from the Electrum GUI (such as restoring a wallet from seed) cause certain messages to appear in the blank Qt window (such as a list of restored addresses).  These are the same messages that one would get in the Windows command window after starting the GUI with "Python Electrum".  There being no errors, there is no traceback.

Also, using the Windows File Manager, double clicking on "electrum.pyw" suppresses the Qt console window and just shows the Electrum window.  Electrum runs properly from the QUI window when started this way, until such time as doing an operation (such as restoring a wallet from seed) that would have produced console output. At this point a Qt popup appears with "[Errno 9] Bad file descriptor". Unfortunately, when started this way there is no traceback since the window needed to display it does not exist.

Given that it's a beta it's probably better to have all the console output for debugging purposes, so I will close this issue.  When I get a chance I will try the build process which is the best way to solve this problem.

**Comment by tl121** [comment]
If you go to the closed thread I posted all the details I have.

Thanks.



On 1/8/2015 4:10 AM, ThomasV wrote:
> can you post a traceback, and explain how you "built and installed on
> Windows" ?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spesmilo/electrum/issues/972#issuecomment-69153285>.
> 

-- 

"You are never alone or helpless. The force that guides the stars,
guides you too."


www.aglauck.com
