### ISSUE TITLE
Imported private keys - BTChip shouldn't be used, I think!

### ISSUE THREAD

**Issue by MuhammedZakir** [spesmilo/electrum#973]
Hello! I setuped Electrum-2.0 with BTChip and it worked. Then I imported 2 private keys to Electrum and when I tried to sign a message or TX, it is using BTChip to do it. Why is it like that? BTChip shouldn't be used when signing a message/TX with an imported address, right? Or do I have to do anything before importing? Thanks!

![](http://i.imgur.com/rjTHLsJ.jpg)

Kindly,
    Muhammed Zakir

**Comment by ecdsa** [comment]
@btchip  can you have a look?

**Comment by btchip** [comment]
I will in a couple days

**Comment by btchip** [comment]
Seems the latest Electrum doesn't let you import keys here (grayed out), so it should be fixed

**Comment by ecdsa** [comment]
indeed
