### ISSUE TITLE
should daemon start/stop always be explicit?

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#977]
Currently a command that requires a network connection will spawn a network daemon, and the daemon will self-terminate after a timeout of inactivity has been reached. I am not sure if this is really the most user friendly behaviour; should we enforce `daemon start` and `stop` instead? please comment.

**Comment by Tafelpoot** [comment]
When you run a network command, it should check if the daemon is running.
If daemon is running, it should use the daemon and leave the daemon running when the command has finished.
If the daemon is not running, it should start the daemon, execute the command and shut down the daemon when the command has finished.

Where would you enforce daemon start and stop?

**Comment by Tafelpoot** [comment]
Regarding daemon behavior, I find it a bit strange that `python electrum -d` causes a GUI to load, with the daemon in background. On shutdown of the GUI, the daemon keeps running.

I'd rather have that command behaving the same as `python electrum daemon start` OR to close the daemon on window shutdown.

**Comment by ecdsa** [comment]
The main purpose of the daemon is not to serve GUIs, but scripts. When a script involves commands that require the network, a new network connection is opened and closed for each command in 1.9.x, which is wasteful. That's why we have a daemon that does not shut itself down after the command has finished, but later.

**Comment by atweiden** [comment]
Typically daemons work better when you can explicitly enable / disable them. Systemd units may one day depend on electrum.service running the daemon for instance. OTOH, services which depend on electrum-server data may want to query the server directly instead of -> script queries the client -> client queries the server. See: https://github.com/zouppen/stratum-tool

**Comment by ecdsa** [comment]
done in 0200778ac1adbe6d2a4068c2afa86a25a786f8ac
