### ISSUE TITLE
Invalid password?

### ISSUE THREAD

**Issue by UP4012** [spesmilo/electrum#979]
Is there some sort of password reset feature for Electrum? I set up a new wallet (other than default_wallet) and password protected it. I made an internal transfer using this password just fine, and, suddenly, when I went to make an external transfer, my password was invalid. I know exactly what I used as a password (all of this happened over the span of about a half hour) but now my BTC is locked up in default_wallet asking for a password... The only seed I was ever shown seems to be for the second wallet, as I've tried regenerating that several times only to find the balance I had in there as opposed to the (much larger) balance I have showing in default_wallet...

**Comment by dabura667** [comment]
There is no password reset feature for Electrum.

Calm down, and remember the last time you sent bitcoins from your default_wallet. You will remember your password as soon as you stop worrying.

Also, make sure your keyboard is set in the right mode. (No Caps Lock on or anything like that)

**Comment by UP4012** [comment]
I never forgot my password. I wrote it down as soon as I made it, and it's a password I use for other things as well. I can type it from muscle memory. I have never sent bitcoins from default_wallet.

**Comment by dabura667** [comment]
try something close to your password... maybe something you might have mistyped.

**Comment by UP4012** [comment]
I've retyped it, sloppily, precisely, etc, numerous times, capslock on and off.

**Comment by UP4012** [comment]
It seems to me that this has to be on electrum's end. As I mentioned, the password worked for an internal transfer and suddenly stopped working. I find it hard to believe that I made the same error in entering it twice when i was setting it up and again when i used it for the internal transfer...

**Comment by dabura667** [comment]
What OS are you using?
What version of Electrum are you using? (number version AND type of installer [portable, full install, executable, etc.])
What exactly does Electrum say when you type in an incorrect password?
How many transactions show up in your history tab?

**Comment by UP4012** [comment]
OS is Win 8.1
Electrum Version 1.9.8, full install, runs as a .exe, installed to C:/Program Files (x86)/Electrum by default
The only transaction which shows in default_wallet is from coinbase, when I transferred the btc from my account there.
Electrum comes up with a dialog box saying "Message" at the top and "Invalid Password" with an OK button underneath.

**Comment by Tafelpoot** [comment]
Try displaying the seed of the wallet. This involves less risk on bugs compared to sending a transaction.
Recreate the default_wallet with the seed.
