### ISSUE TITLE
Electrum ERROR: u'message': u'', u'code': -25

### ISSUE THREAD

**Issue by Technologov** [spesmilo/electrum#980]
v1.9.8
I get error {u'message': u'', u'code': -25}
Cannot send my Bitcoins anymore Sad

Running on Windows 7 x64
any ideas?

**Comment by ecdsa** [comment]
duplicate

**Comment by Technologov** [comment]
Duplicate of which bug ?
Please re-open. (until we have the number of the other bug)

**Comment by wozz** [comment]
#962
