### ISSUE TITLE
export history CSV with description as reference

### ISSUE THREAD

**Issue by jangos** [spesmilo/electrum#985]
I want to be able to export that text from the editable description as a data column within the transaction CSV export to e.g. identity individual transactions

Is there a way to manage it?

**Comment by ecdsa** [comment]
did you check "File->Export history" ?

**Comment by jangos** [comment]
Sure the transactions are included but not my manual notes ("description")

**Comment by dabura667** [comment]
For me there is a "label" column on the csv output from 1.9.8

It includes all my manual notes in it.

@jangos can you post the top row of the csv output (the row with all the headers for the columns, so it shouldn't have any of your information)

**Comment by jangos** [comment]
Thanks, I got it - I opened the CSV with libre office and the import kind of failed).

**Comment by dabura667** [comment]
yes, the CSV is exported in UTF-8, so if you use non-English characters it is difficult to display properly in Libre.
