### ISSUE TITLE
Network window crashes when specifying a proxy as a parameter

### ISSUE THREAD

**Issue by andscho** [spesmilo/electrum#990]
Problem Description:
Electrum connects fine using the specified proxy but when I want to have a look at the network window the window never shows up.

Version: 
This is using the latest development version (56e8056) but the same issue is also present in 1.9.8. 

Stacktrace:

user@host:~/Downloads/electrum_dev/electrum$ ./electrum -p socks5:localhost:4444
Traceback (most recent call last):
  File "/home/user/Downloads/electrum_dev/electrum/gui/qt/main_window.py", line 2773, in run_network_dialog
    NetworkDialog(self.wallet.network, self.config, self).do_exec()
  File "/home/user/Downloads/electrum_dev/electrum/gui/qt/network_dialog.py", line 159, in __init__
    self.proxy_mode.setCurrentIndex(self.proxy_mode.findText(str(proxy_config.get("mode").upper())))
AttributeError: 'str' object has no attribute 'get'

**Comment by ecdsa** [comment]
I can reproduce it. 
I will fix it today.

**Comment by ecdsa** [comment]
fixed
