### ISSUE TITLE
electrum 2.0 outputs icons error

### ISSUE THREAD

**Issue by BrendaFdez** [spesmilo/electrum#993]
I have been trying to run electrum 2.0 on elementaryOS Freyja (Ubuntu 14.04 LTS). After following the instructions on the website to install the development version and installing a number of missing modules, I still can'r run it; i keep getting the following message

Error: Could not import icons_rc.py, please generate it with: 'pyrcc4 icons.qrc -o gui/qt/icons_rc.py'

I have already run the command an confirmed that file icons_rc.py exists in the proper location.

I'm somewhat of a newbie and clueless how to go on from here, but I'd assume it's a bug. If there's some important information missing from my report just let me know.

**Comment by ecdsa** [comment]
are you running electrum from its directory, or did you install it on your system using setup.py?
in the second case, you might need to reinstall after you generated the icons

**Comment by BrendaFdez** [comment]
I had installed it using setup.py, and I did try to run the setup script again after generating the icons, but it's still the same error. Now that you mentioned the possibility of just running it from the directory, i tried that and it runs just fine that way, although i'd still get the error message if I try to run it from other locations or the system menu. Now it's just a minor issue for me.
