### ISSUE TITLE
fee calculation and exclamation mark operator when creating a new transaction

### ISSUE THREAD

**Issue by andscho** [spesmilo/electrum#995]
The fee calculation of the current electrum 2.0 dev version doesn't work as well as it could work:

E.g. I often want to send the whole balance of an address to an exchange. I use "!" to set the
value to the maximum possible value minus the fee. So far so good. 
However, Electrum's fee calculation somehow calculates too low fees in my opinion and I end up with 
transactions that do not get confirmed in the next block but often much later (at least it feels that way...). 

If I change the fee manually to a higher value, the value of the transaction has to be adapted 
manually which can be quite cumbersome (e.g. if you have many transactions on an address and want to send them, good luck summing them all up manually...)

Expected behaviour:
If I change the fee manually, the transaction value should adapt accordingly to the maximum possible value.

**Comment by dabura667** [comment]
Set the fee higher in your preferences.

If you set the fee to about 4x what you want to pay, most transactions will come out around what it is you want to pay.

If you want to pay clean numbered fees, then the current fee algorithm is not for you and you should set it manually.

**Comment by andscho** [comment]
Right, I agree with what you are saying.

I think there is currently no way to turn off the automatic fee calculation.

I would like to have it work like this:
I enter a fee of let's say 0.0001 and then jump to the transaction value field and type "!" to get the maximum amount possible given this fee.

Currently, I cannot set the fee manually before entering a transaction value...

**Comment by kyuupichan** [comment]
Fixed.
