### ISSUE TITLE
2.0-beta: Can't connect through Tor on Tails

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#998]
Using 1.9.8, I can connect through Tor on Tails using the settings:

server: auto-connect
protocol: TCP
proxy: SOCKS5 localhost 9050

However, using the same settings with 2.0-beta, no connection is made. The red indicator dot in the lower right continues to show red.

**Comment by ecdsa** [comment]
you cannot use tor with auto-connect, you need to indicate a .onion server

**Comment by ecdsa** [comment]
I found it, it is because there is a difference between SocksiPy (on sourceforge) and the newer SocksiPy-branch
1.9.8 was shipped with the older version

**Comment by rapodaca** [comment]
@ecdsa How difficult would it be to switch over to the other version of SockPy and resolve the issue?

**Comment by ecdsa** [comment]
done a90f3e00276b67f5a5853dbedd8f91c763dc83cf
