### ISSUE TITLE
Label sync: incompability to pre-deterministic iv encryption

### ISSUE THREAD

**Issue by dexX7** [spesmilo/electrum#999]
https://github.com/spesmilo/electrum/commit/42bbce4cb309bfd8af2388219603053e5f6a0dd0 and https://github.com/spesmilo/electrum/commit/e4dfd3129a5126c6936f69510b8e97e6b9a31410 basically changed AES decryption of labels from:
```python
key  = map(ord, self.encode_password)
iv   = map(ord, data[:16])
data = map(ord, data[16:])
```
To:
```python
key  = map(ord, self.encode_password)
iv   = map(ord, hashlib.sha256(self.encode_password).digest()[:16])
data = map(ord, data)
```

As consequence currently encrypted values are decrypted to [16 byte junk][clear text message].

I have not much understanding of the inner workings, and I'm very surprised that the only side effect is the 16 byte junk prefix (which can cause `.decode('utf8')` to throw an exception).

My idea now is to decrypt the labels I have via the old scheme, then force an upload of labels and finally switch back to the new approach.

Is this something I could have prevented somehow?

**Comment by ecdsa** [comment]
this will probably not be fixed.
